### ISSUE TITLE
Mohon Ditambahkan Fitur Surat Keterangan Penghasilan Orang Tua

### ISSUE THREAD

**Issue by kayangan** [OpenSID/OpenSID#1004]
**Mohon Di Tambahkan Surat Keterangan Peghasilan Orangtua**

Kayanya Di DonjoLib Helper terdapat Rumus ( Rp ) Penjumlahan uang dan Rumus Converter Angka Ke alfabet.
Semoga Para Master bisa memprioritasknnya... Terimaksasih
[surat_keterangan_penghasilan_orangtua.docx](https://github.com/OpenSID/OpenSID/files/1986378/surat_keterangan_penghasilan_orangtua.docx)

**Comment by roaddee** [comment]
Saya sudah mencoba membuat surat keterangan harga tanah, dan sudah bisa keluar Terbilangnya. coba saya buatkan.

**Comment by roaddee** [comment]
saya sudah buatkan, dan saya ujicoba di lokal bisa, namun ada satu function yang saya pikir bisa diletakkan di helper, yaitu fungsi terbilang, mungkin bisa dipakai untuk surat yang lain.

**Comment by eddieridwan** [comment]
> saya sudah buatkan, dan saya ujicoba di lokal bisa, namun ada satu function yang saya pikir bisa diletakkan di helper, yaitu fungsi terbilang, mungkin bisa dipakai untuk surat yang lain.

@roaddee silakan kirim pull requestnya, atau lampirkan di sini.

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR #2004
