### ISSUE TITLE
Perubahan Data Penduduk 

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#1009]
### Bagaimana alurnya sampai muncul masalah?
Di Menu Penduduk Operator memiliki akses untuk mengubah data !!!!

### Seperti apa yang diharapkan?
1. Demi Keamanan data seperti yang diterapkan oleh Dinas Dukcapil yang bisa merubah data ada 
    khusus yang menanganinya sehingga perubahan data bisa dipertanggungjawabkan
2. bisa saja ditambahkan nama pengguna yang khusus bisa merubah data
### Apa yang terjadi?
ketika semua perangkat desa yang punya akses mengubah data maka data tersebut bisa saja berubah tanpa ada dasar yang kuat sedangkan dari dinas dukcapil ketika melalukan perubahan data harus ada dasar yang kuat

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by suphm** [comment]
[WIP] Saya sedang mencoba menerapkan RBAC untuk ini.

**Comment by eddieridwan** [comment]
Teman2 sudah menyepakati spesifikasi hak akses http://bit.ly/2Vhqmyz, yang sekarang telah diterapkan.
