### ISSUE TITLE
Bug: Komentar di Artikel Tidak Bisa Captcha Salah

### ISSUE THREAD

**Issue by wongcilikpoenya** [OpenSID/OpenSID#1011]
Pada saat mau memberikan komentar pada artikel, penulisan captcha salah terus, padahal sudah benar menulis captcha tersebut. Opensid pasca 2.12 sebelumnya d opensid 2.11 bisa tdak ada masalah.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Masalahnya disebabkan karena ada yang berbeda dalam penanganan session dari Codeigniter 2.x ke 3.1.8, sehingga penggunaan session oleh Securimage tidak tersimpan. Sayangnya tidak ketemu cara mengatasi masalah session ini.

Akhirnya solusi yg diterapkan adalah menyimpan status Securimage di database dan tidak di session. Konfigurasi database yg digunakan di Securimage diambil dari `desa/config/database.php`. Pengambilan ini dilakukan di `securimage/config.inc.php`.

Sudah dicommit ke master.

**Comment by ariandii** [comment]
mencoba komemtar di demo.opensid.info kode selalu salah. 

![screenshot_2019-02-28-07-29-10-33](https://user-images.githubusercontent.com/46939846/53532789-db92b180-3b2a-11e9-99b9-4cd4a29c9918.png)_

**Comment by eddieridwan** [comment]
@ariandii  Sebaiknya buat issue baru, karena kalau timbul masalah serupa di versi baru, penyebabnya akan berbeda (kecuali kalau yakin masalah yg sama). Dalam hal ini, saya baru saja coba di demo.opensid.info dan beta.opensid.info, tidak bermasalah. Tapi memang di demo.opensid.info databasenya rusak diubah pengguna dan saya restore dulu.

Selalu usahakan mencoba di beta.opensid.info sebelum melaporkan masalah, karena beta.opensid.info berisi berubahan sejak rilis terakhir.
