### ISSUE TITLE
Template Engien

### ISSUE THREAD

**Issue by happyagung25** [OpenSID/OpenSID#1022]
### Bagaimana alurnya sampai muncul masalah?
Mohon di buatkan template engien untuk OpenSID dong biar enak dan memudahkan para pegiat OpenSID membuatkan template utuk OpenSID

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
Pak @eddieridwan, apakah ini akan diterapkan???

**Comment by eddieridwan** [comment]
Saya tutup dulu. Kita usahakan memudahkan pembuatan template secara pelan2 sambil jalan.
