### ISSUE TITLE
Tampilkan jumlah surat di Arsip Layanan > Grafik Surat Keluar

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#1023]
### Bagaimana alurnya sampai muncul masalah?
Perlu dibuatkan keterangan di masing-masing surat supaya kita tau setiap surat itu berapa kali di cetak/ dibuatkan jumlah rekapan masing-masing surat

### Seperti apa yang diharapkan?

Adanya jumlah rekapan masing-masing surat
### Apa yang terjadi?
Ketika ada instansi yg minta berapa jumlah surat keterangan TDK mampu yg SDH dikeluarkan oleh desa kita jadi perlu hitung satu persatu

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by balongbesuk** [comment]
![untitled](https://user-images.githubusercontent.com/35319600/40268899-2b8db042-5ba0-11e8-86e8-6f328a4e74b6.jpg)

grafik surat keluar perlu ditambahkan jumlah surat keluar per bulan / pertahun

**Comment by MUHAMMADRANGSEL** [comment]
Perbulan boleh pertahun juga boleh

Pada tanggal Sab, 19 Mei 2018 21.12, balongbesuk <notifications@github.com>
menulis:

**Comment by MUHAMMADRANGSEL** [comment]
Betul sekali di grafik yg sekarang menampilkan berbentuk persentase saja

Pada tanggal Min, 20 Mei 2018 04.17, MUHAMMAD SPD <muhammadrangsel@gmail.com>
menulis:

**Comment by LIQRGV** [comment]
![image](https://user-images.githubusercontent.com/5935057/41819215-d0addaea-77e6-11e8-95ef-c6d5ec77df2c.png)

Seperti ini bisa diterima ?

**Comment by LIQRGV** [comment]
Data pada total akan menyesuaikan jumlah data.
Contoh pada screenshot masih salah.
Akan di-update segera.

**Comment by LIQRGV** [comment]
Yang baru seperti ini:

![image](https://user-images.githubusercontent.com/5935057/41819684-d701c32c-77ee-11e8-95a7-a32efe5a594e.png)

**Comment by MUHAMMADRANGSEL** [comment]
Mantap

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR #1122
