### ISSUE TITLE
Nama Gelar Pada KK

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#1024]
### Bagaimana alurnya sampai muncul masalah?
nama penduduk yang menambahkan gelar pada kk membentuk huruf besar semua

### Seperti apa yang diharapkan?
solusi nama gelar sesuai penulisan tidak huruf besar semua

### Apa yang terjadi?
ketika cetak surat /  kk nama gelar tercetak huruf besar

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | pasca-2.12
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
> 
> 
> ### Bagaimana alurnya sampai muncul masalah?
> nama penduduk yang menambahkan gelar pada kk membentuk huruf besar semua
> 
> ### Seperti apa yang diharapkan?
> solusi nama gelar sesuai penulisan tidak huruf besar semua
> 
> ### Apa yang terjadi?
> ketika cetak surat /  kk nama gelar tercetak huruf besar
> 
> | Tanya            | Jawab
> | ---------------- | ---
> | Versi OpenSID    | pasca-2.12
> | Versi PHP        | 
> | System operasi   |
> 

Ini beda pak sma issue yg sy buat, klw issue ini bisa dilampirkan aturan mengenai nama gelar yg ada di KK. Krn data di KK mengacu pd data penduduk masing2. 

Klw di modul pemerintah desa ada tabel khusus untuk menyimpan nama walaupun data referensi dr data penduduk tp masih bisa di ubah di tabel tsb.

**Comment by balongbesuk** [comment]
https://dukcapil.kemendagri.go.id/files/SE/2011/471-7717-MD_(24-11-2011).pdf

saya kurang tahu ini masuh berlaku atau tidak, tp sy jg lebih memilih data penduduk murni tanpa gelar

**Comment by balongbesuk** [comment]
> 
> 
> > https://dukcapil.kemendagri.go.id/files/SE/2011/471-7717-MD_(24-11-2011).pdf
> > saya kurang tahu ini masuh berlaku atau tidak, tp sy jg lebih memilih data penduduk murni tanpa gelar
> 
> Issue yg sy buat untuk pemerintah desa yg memeliki gelar(kepala desa, sekretaris, dll, untuk saat ini belum bisa menambahkan gelar jika data di ambil dari data penduduk.
> 
> Mungkin issuenya bisa di close jika tdk sesuai aturan yg berlaku.


ooo saya kira gelar akademik, gelar kehormatan ( H. Prof. Dr. Alm. R.A, dll,) kepala desa, sekretaris desa, dll gelar jabatan,

**Comment by afa28** [comment]
Apakah ini masih bermasalah??? Kalau tdk silahkan di close.
