### ISSUE TITLE
Menu Cetak Surat Directory Forbidden Access

### ISSUE THREAD

**Issue by MbakVita** [OpenSID/OpenSID#1027]
semua fitur bisa dijalankan namun hanya direktori cetak surat  ini yang tidak bisa dibuka. begitu dibuka muncul tulisan directory access is forbiden
### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Harap lampirkan tampilan layar, supaya terlihat url yang anda gunakan.

Coba lihat panduan https://github.com/OpenSID/OpenSID/wiki/Tanya-Jawab-Install-dan-Update. Apakah masalah anda terjawab oleh `T: Mengapa error seperti berikut pada waktu mencetak surat?`.

**Comment by MbakVita** [comment]
Maaf mas.  Barusan udah saya oprek ternyata udah bisa

Pada tanggal Sen, 21 Mei 2018 18.28, Eddie Ridwan <notifications@github.com>
menulis:

**Comment by MbakVita** [comment]
Iya.  Mohon maaf sebelumnya

Pada tanggal Sen, 21 Mei 2018 18.39, Eddie Ridwan <notifications@github.com>
menulis:
