### ISSUE TITLE
Tambahkan Fitur cara menampilkan  hasil pencarian web dan kategori 

### ISSUE THREAD

**Issue by dobbleone** [OpenSID/OpenSID#1029]
Penambahan fitur yang dimaksud diatas adalah : 
-tambahkan function pada donjo-app /controllers frist. Php dan penyesuaian pada donjo-app /model  agar kategori Web dan hasil pencarian di load pada halaman kategori dan pencarian jika : 
    a. Tersedia kategori.php pada folder layouts di dalam themes opensid
    b. Tersedia search.php pada folder layouts di dalam themes opensid
     c. Kategori dan hasil pencarian di tampilkan seperti biasa jika kategori.php dan search.php seperti yang dimaksud pada poin a. Dan b. Tidak tersedia pada folder layouts di themes opensid.

**Comment by eddieridwan** [comment]
@dobbleone : Tidak jelas apa yang anda inginkan.

Harap lampirkan contoh hasil pencarian yg dibayangkan. Apakah daftar artikel atau sesuatu yg lain. Atau apakah anda mengusulkan solusi teknis? Jika mengusulkan solusi teknis jelaskan apa keuntungan yg diharapkan dari solusi anda.

**Comment by afa28** [comment]
Mungkin maksunya, pencarian yg dilakukan hasilnya banyak bisa di kelompokkan berdasar kategori artikel tsb.

**Comment by afa28** [comment]
Mungkin maksunya, pencarian yg dilakukan hasilnya banyak bisa di kelompokkan berdasar kategori artikel tsb.

**Comment by afa28** [comment]
Sudah tersedia.
https://berputar.opensid.or.id/first/kategori/berita-desa
