### ISSUE TITLE
Penambahan upload lampiran file PHP surat

### ISSUE THREAD

**Issue by happyagung25** [OpenSID/OpenSID#1030]
### Bagaimana alurnya sampai muncul masalah?
Tidak dapat menambahkan file lampiran PHP pada proses pembuatan surat baru yang memerlukan formulir lampiran. Sehingga harus mengedit database pada tweb_surat_format untuk memasukan file php
### Seperti apa yang diharapkan?

Mohon ditambahkan field upload untuk upload file php lampiran surat untuk surat-surat yang memiliki lampiran. Misal, Surat Permohonan KTP untuk WNI (f-1.21) pada proses pembuatan surat baru.
### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Tantangan untuk fitur ini adalah bagaimana menghindari pengunggahan script PHP backdoor, yang akan membuka celah keamanan.

Salah satu opsi adalah untuk hanya menyediakan fitur untuk menambahkan lampiran ke database, sehingga tidak perlu mengubah database langsung. Tetapi berkas PHP tetap diunggah menggunakan Windows Explorer atau cPanel di hosting. 

Caranya dengan mengembangkan proses berbagi surat yang dijelaskan di https://github.com/OpenSID/OpenSID/wiki/Berbagi-Surat: 
(1) tambahkan subfolder surat yang mau ditambah, lengkap dengan semua unsur surat yg diperlukan  (https://github.com/OpenSID/OpenSID/wiki/Berbagi-Surat), termasuk lampiran; kemudian
(2) jalankan migrasi supaya sistem bisa menemukan surat baru tersebut dan menambahkan ke database. **Jadi tinggal ditambah fasilitas untuk mendaftarkan lampiran.**

**Comment by mizwaruddin** [comment]
@afa28 solusi sdh ada di wiki.
