### ISSUE TITLE
Bug: Form Pengajuan KK Baru, Nama Kepala Keluarga masih tercantum pada form anggota keluarga

### ISSUE THREAD

**Issue by makhbub** [OpenSID/OpenSID#1033]
# 
pada form pengajuan KK, Nama Kepala Keluarga masih tercantum dalam daftar anggota keluarga, padahal menurut petunjuk Tata cara pengisian Permohonan Kartu Keluarga (KK) yang baru, pada form anggota keluarga di isi anggota keluarga selain Kepala Keluarga
 
# yang di inginkan
form anggota keluarga hanya di isi anggota keluarga selain Kepala Keluarga

**Comment by makhbub** [comment]
penambahan gambar pendukung

**Comment by eddieridwan** [comment]
![surat-kk](https://user-images.githubusercontent.com/249563/40594994-8d9bb898-6275-11e8-93aa-7dc52eb8f588.jpg)
![surat-kk-peraturan](https://user-images.githubusercontent.com/249563/40595003-95b7f83e-6275-11e8-903e-e9f526e7115e.jpg)

**Comment by balongbesuk** [comment]
![33110029_10210874522370854_1992505589984395264_n](https://user-images.githubusercontent.com/35319600/40596157-401c1f98-6263-11e8-99a6-4fce797fff11.jpg)

diperjelas, 
1.jumlah anggota keluarga tidak termasuk kepala keluarga, point 06
2.daftar anggota keluarga kepala keluarga tetap tercantum point 07 *

**Comment by eddieridwan** [comment]
Sudah diubah:

1. #1033: Sekarang lampiran F-1.15 untuk surat permohonan kartu keluarga menampilkan jumlah dan daftar anggota keluarga tidak termasuk kepala keluarga. Di form, pemohon dibatasi pada kepala keluarga saja. [bug-fix]
2. #1033: Sekarang lampiran F-1.16 untuk surat permohonan perubahan kartu keluarga menampilkan jumlah dan daftar anggota keluarga tidak termasuk kepala keluarga. Di form, pemohon dibatasi pada kepala keluarga saja. [bug-fix]

Sudah dicommit ke master.
