### ISSUE TITLE
Bug: menambah data persil secara manual menghasilkan data duplikat

### ISSUE THREAD

**Issue by mizwaruddin** [OpenSID/OpenSID#1035]
### Bagaimana alurnya sampai muncul masalah?
saat saya ingin menambahkan data persil secara manual, yg muncul 80 data untuk satu nama. 

### Seperti apa yang diharapkan?
pada data persil tidak harus diambilkan dari data penduduk yg tersimpan di open sid. karena banyak tanah yg sudah dimiliki oleh orang luar desa/kota.
ada jg tanah yg peiliknya sdh mati tp blm di balik nama.
### Apa yang terjadi?
saat ini saat memasukkan nama yg sdh terekam di database penduduk. 
saat mengisi manual terjadi masalah karena satu orang yg muncul di data 80 dg nama dan data yg sama.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.12
| Versi PHP        | 5.20
| System operasi   | 7/10

**Comment by eddieridwan** [comment]
Masalah ini terjadi karena saat ini kolom `nik` di tabel `data_persil` diisi nama pemilik untuk pemilik luar desa. NIK non-alpha tersebut akan dicocokkan dengan semua penduduk yang mempunyai NIK 0 (yaitu NIK tidak diketahui). Jadi kalau ada 80 penduduk dengan NIK 0, maka persil untuk orang luar desa tsb akan muncul 80 kali.

Solusinya, diperlukan penanganan khusus untuk pemilik luar desa. Saat ini kami buat asumsi informasi orang luar desa belum disimpan di tabel sendiri. Yaitu, data mengenai orang luar desa terkait persil disimpan di tabel `data_persil` saja.

Saat ini sudah ada kolom `alamat_ext` untuk menyimpan alamat pemilik dari luar desa. Kami akan tambahkan kolom berikut:

1. `jenis_pemilik`, untuk menandakan pemilik desa atau luar desa
2. `nama_ext`, untuk menyimpan nama pemilik luar desa

Dan kolom NIK untuk pemilik luar desa diisi dengan bilangan yang tidak akan cocok dengan NIK siapapun di `tweb_penduduk`. Kami akan gunakan bilangan '999' untuk keperluan ini.

**Comment by mizwaruddin** [comment]
Bagaimana dg tanah yg dimiliki warga desa yg sdh meninggal tp blm
dialihnamakan?

Pada tanggal Sen, 4 Jun 2018 08.33, Eddie Ridwan <notifications@github.com>
menulis:

**Comment by eddieridwan** [comment]
Script persil tidak mengikuti coding style standar view kita. Jadi perlu diubah dulu mengikut standar.
Juga sekalian memperbaiki berbagai error.

Sudah dicommit ke master.
