### ISSUE TITLE
Program Bantuan Session.php

### ISSUE THREAD

**Issue by Janah6770** [OpenSID/OpenSID#1036]
Ingin menulis Program Bantuan, saat mau di simpan keluar ini Unable to locate the specified class: Session.php. Bagaimana solusinya?

**Comment by Janah6770** [comment]
versi 3, pasca-2.12 gan. maaf kalo salah, masih kurang mengerti

**Comment by MUHAMMADRANGSEL** [comment]
ini juga terjadi di situs demo http://demo.opensid.info

**Comment by MUHAMMADRANGSEL** [comment]
di Offline yang kami punya berjalan lancar

**Comment by egodasa** [comment]
Versi demo Saya tes versi 18.06 tidak ada masalah. @Janah6770 Apakah versi punya Anda sudah di upgrade ke 18.06?

**Comment by Janah6770** [comment]
saya tidak terlalu mengerti cara mengupgradenya

**Comment by suphm** [comment]
ini panduannya
 https://github.com/OpenSID/OpenSID/wiki/Panduan-Update-OpenSID

bagian mana yang kurang dipahami?

**Comment by RahmanSaputra** [comment]
Saya juga mengalami hal tersebut saat klik menu sekretariat.. Saya debuging terjadi notifikasi error 503 Service Unavaible.

**Comment by metalab25** [comment]
@RahmanSaputra : pake versi berapa ?

**Comment by RahmanSaputra** [comment]
@metalab25 versi 18.06 om

**Comment by metalab25** [comment]
@RahmanSaputra : baiknya buat issue terpisah dan lampirkn errornya beserta informasi lainnya

**Comment by RahmanSaputra** [comment]
Solved dengan penambahan beberapa script pada file my.cnf

**Comment by muhammad-ihsan** [comment]
@RahmanSaputra bisa di bantu apa yang ditambahnya mas? biar issuenya bisa di close

**Comment by afa28** [comment]
Pak @Janah6770, ijin tutup issue ini krn versi sdah terlalu jauh. Jika mmang mash ada kendala bisa buat issue baru.
