### ISSUE TITLE
Bug: Pilihan penduduk hilang di form tambah peserta program bantuan kalau ada tanda petik dua (") di nama penduduk

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#1037]
### Bagaimana alurnya sampai muncul masalah?
Ketika ingin menambahkan penduduk yg menerima bantuan form input penduduk TDK ada

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Harap lampirkan tampilan layar masalah, supaya lebih jelas. Apakah sudah dicoba di situs demo http://demo.opensid.info?

**Comment by MUHAMMADRANGSEL** [comment]
Masalah ini terjadi hanya pada masyarakat penerima bantuan kategori PENDUDUK
![screenshot 2018-06-02 04 09 10](https://user-images.githubusercontent.com/25834335/40861221-f11303ec-661a-11e8-8058-b35dd821d507.png)

dan masalah ini pun terjadi hanya di situs http://demo.opensid.info

**Comment by MUHAMMADRANGSEL** [comment]
dan issue ini saya closed bung eddie dikarenakan terbyata di situs http://demo.opensid.info sekarang sudah bisa setelah saya klik menu MIGRASI DB

**Comment by MUHAMMADRANGSEL** [comment]
di Sasaran  Keluarga juga ada yang bermaslah
![screenshot 2018-06-02 04 16 12](https://user-images.githubusercontent.com/25834335/40861443-b5aa1150-661b-11e8-9d5b-1c1f1ec93314.png)

**Comment by MUHAMMADRANGSEL** [comment]
dan maslah ini terjadi di situs DEMO Bung http://demo.opensid.info

**Comment by MUHAMMADRANGSEL** [comment]
dan mungkin database di http://demo.opensid.info perlu di perbaiki bung eddie kalau di offline yang kami punya semua berjalan dengan lancar

**Comment by eddieridwan** [comment]
Masalah ini muncul karena ada nama penduduk berisi karakter tanda petik dua ("). Bahkan error akan terjadi di banyak tempat lainnya (seperti surat).

Ternyata saat ini pengisian nama penduduk tidak divalidasi -- bisa diisi karakter apa saja.

Solusinya adalah menambahkan validasi pengisian/perubahan nama penduduk supaya hanya boleh alpha + spasi + tanda petik satu (').

**Comment by MUHAMMADRANGSEL** [comment]
Betul sekali bung Eddie

**Comment by eddieridwan** [comment]
@MUHAMMADRANGSEL perbaikan data yang salah perlu dilakukan secara manual. Yaitu di daftar penduduk atau di phpmyadmin, cari penduduk yang namanya berisi petik dua (") dan ubah.

**Comment by eddieridwan** [comment]
Sekarang sudah ditambahkan validasi menjaga agar nama penduduk hanya boleh berisi karakter alpha, spasi dan tanda petik.

Data yang terlanjur salah perlu diperbaiki secara manual.

**Comment by eddieridwan** [comment]
Sekarang form program bantuan bisa menampilkan pilihan di mana nama penduduk berisi tanda kutip.

Sudah dicommit ke master.
