### ISSUE TITLE
Request Halaman Statis Pencarian Data

### ISSUE THREAD

**Issue by kelbatuix** [OpenSID/OpenSID#1038]
Bisakah membuat halaman statis untuk halaman website (dapat diakses umum) untuk pencarian data penduduk, data persil (no persil/nama/alamat), dan data PBB(NOP/nama/alamat)?
tentunya yang ditampilkan hanya informasi umum seperti  data penduduk hanya menampilkan nomor NIK dan Nama serta status seperlunya, data persil dan data pbb menampilkan jenis persil, nama pemilik serta alamat?

**Comment by afa28** [comment]
Sebaiknya ditampilkan di layanan mandiri.
