### ISSUE TITLE
Input Data Persil

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#1043]
### Bagaimana alurnya sampai muncul masalah?
Setelah Downloads Pasca 18.06 masalah input data persil pada waktu menyimpan data muncul seperti ini : 
![image](https://user-images.githubusercontent.com/25834335/40928909-80f650e0-6855-11e8-932d-8f2e5a3cc650.png)
muncul seperti gambar dibawah ini : 
![image](https://user-images.githubusercontent.com/25834335/40928802-28dcbb1a-6855-11e8-9a08-f7c1e0471cd9.png)
Dan Daftar Persil yang masih ada seperti gambar dibawah ini juga perlu dihapus
![image](https://user-images.githubusercontent.com/25834335/40929200-a2dbb6b8-6856-11e8-8bb9-09958f61a32d.png)

### Apa yang terjadi?
Data Tidak bisa tersimpan

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 18.06 - Pasca
| Versi PHP        | 
| System operasi   |

**Comment by MUHAMMADRANGSEL** [comment]
ini disebabkan karena belum adanya Data Jenis Persil dan Peruntukan Tanah, setelah saya tambahkan ternyata data berhasil disimpan dan hasilnya ok seperti gambar dibawah ini : 
![image](https://user-images.githubusercontent.com/25834335/40929523-91ed2e12-6857-11e8-91c3-f9d1239bbdf9.png)

**Comment by eddieridwan** [comment]
@MUHAMMADRANGSEL : ubah saja issue ini untuk mengharuskan pengisian Data Jenis Persil dan Peruntukan Tanah sebelum bisa menyimpan Persil. Supaya tidak muncul error membingungkan.
