### ISSUE TITLE
[Bug] Buatkan Pesan Error Deskriptif

### ISSUE THREAD

**Issue by suphm** [OpenSID/OpenSID#1046]
### Apa yang terjadi?
Setiap error selalu yang muncul ```Unable locate session.php```

### Seperti apa yang diharapkan?
Sebaiknya gunakan pesan yang deskriptif
- untuk development
	- tampilkan pesan error termasuk database query, trace line. 
	- selalu log message untuk semua level debug, info, error
- untuk production
	- cukup tampilkan ```Error gopek (500)```
	- hanya log pesan dengan level error

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | sejak 2.12
| Versi PHP        | 7
| System operasi   |

**Comment by LIQRGV** [comment]
![image](https://user-images.githubusercontent.com/5935057/41984350-acf1e396-7a5a-11e8-8b03-79f743fd9668.png)

Ini bakalan jadi issue berat sepertinya.
Setelah mencoba, saya mendapati bahwa error message CI semuanya hasil dari output buffer, lalu diberikan response.
Jika mau ada error yang jelas, yang saya pikirkan hanya jika setiap error dilakukan throw exception,
salah satunya di file system/core/Common.php.
Contoh pada gambar di atas jika konfigurasi database salah.
Tapi berhubung file tersebut bukan kode OpenSID, tetapi kode CI, saya ragu untuk mengubahnya.

**Comment by LIQRGV** [comment]
http://www.universidadecodeigniter.com.br/whoops-error-handling-personalizado-no-codeigniter/

Quote:
"Note
It is important to be aware that this implementation will not handle framework-specific errors, such as calling a view whose file does not exist in the application / views directory ."

Dalam kasus ini, import file core gagal karena ada exception yang di-handle sendiri oleh CI.

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
