### ISSUE TITLE
[tampilan-desa] Identitas Desa > Kantor Desa dan Identitas Desa > Wilayah Desa bermasalah

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#1047]
### Bagaimana alurnya sampai muncul masalah?
SID Home > Identitas Desa > Kantor Desa, dan SID Home > Identitas Desa > Wilayah Desa

### Seperti apa yang diharapkan?
Peta ditampilkan dengan fitur untuk mengubah lokasi marker kantor desa.
Peta ditampilkan dengan fitur untuk mengubah poligon wilayah desa.

### Apa yang terjadi?
Hanya sebagian peta tampil, dan tidak ada control untuk mengubah peta.
<img width="1371" alt="admin-kantor-desa" src="https://user-images.githubusercontent.com/249563/40970508-31d746aa-68fe-11e8-9c99-3a67c0dd64a6.png">

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by egodasa** [comment]
@eddieridwan Yang memperbaiki issue ini siapa Mas?

**Comment by egodasa** [comment]
Sepertinya kantor desa bermasalah karena skrip dan css leaflet dihilangkan. Saya tidak menemukan skrip berikut di `views/header.php`
```
<link rel="stylesheet" href="<?php echo base_url()?>assets/css/leaflet.css" />
<link rel="stylesheet" href="<?php echo base_url()?>assets/css/leaflet.pm.css" />
<script src="<?php echo base_url()?>assets/js/leaflet.js"></script>
<script src="<?php echo base_url()?>assets/js/leaflet.pm.min.js"></script>
```

**Comment by egodasa** [comment]
Di `views/home/ajax_wilayah_desa_maps.php`, form petanya hilang sehingga peta wilayah desa tidak muncul.

**Comment by fitamrin** [comment]
@egodasa link ke plugin leaftlet ada di file ajax_wilayah_desa_maps.php
kok di tempat saya jalan...??
[
![peta_wilayah](https://user-images.githubusercontent.com/39846379/40991318-9e4a575e-691d-11e8-9d17-f39c988a5c4c.jpg)
![peta_desa](https://user-images.githubusercontent.com/39846379/40991319-9eb3259a-691d-11e8-8cf3-35e0b13e38b9.jpg)

](url)

**Comment by eddieridwan** [comment]
Sudah diperbaiki di #1064
