### ISSUE TITLE
[tampilan-desa] Style modul Web terpengaruh

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#1048]
### Bagaimana alurnya sampai muncul masalah?
Buka halaman Web http://demo-admin.opensid.info/index.php/first

### Seperti apa yang diharapkan?
Tampil dengan style dan operasi widget seperti biasa.

### Apa yang terjadi?
Style menu dll terpengaruh. Juga teks berjalan dan slider tidak bergerak.
<img width="1298" alt="admin-web" src="https://user-images.githubusercontent.com/249563/40970897-4690879a-68ff-11e8-9c14-ff5bfb9592b8.png">

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by ombimo** [comment]
mungkin file asli jangan di hapus terlebih dahulu, cukup tidak digunakan saja di halaman admin.

**Comment by fitamrin** [comment]
css dan js yang ada rupanya digunakan secara gotong royong antara template admin dan template website.
sepertinya perlu diupload ulang file css dan js yang digunakan oleh template website.
alangkah bagusnya dipisah, padahal sudah ada tempatnya untuk website di folder assets/front. tapi konsekuensinya merubah header dan footer masing masing template website yang ada...

**Comment by eddieridwan** [comment]
@fitamrin Memang di SPK Pasal 2.1 pemisahan itu perlu anda lakukan:

> Tata ulang semua stylesheet yang digunakan modul Admin, dengan memisahkan secara jelas stylesheet untuk modul Admin supaya berbeda dengan stylesheet untuk modul Web. Hapus stylesheet yang tidak berlaku lagi setelah proses modernisasi.

Dan js juga perlu ditata ulang.

**Comment by eddieridwan** [comment]
Sudah dikerjakan di #1056
