### ISSUE TITLE
[tampilan-admin] Di SID Home > Pemerintahan Desa kolom Aksi tidak perlu wrap

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#1050]
### Bagaimana alurnya sampai muncul masalah?
1. SID Home > Pemerintahan Desa
2. Persempit layar supaya kolom tabel mengecil

### Seperti apa yang diharapkan?
Tombol di kolom aksi tidak wrap 

### Apa yang terjadi?
Tombol di kolom aksi wrap; tapi kalau sudah sempit sekali kembali tidak wrap.

<img width="1151" alt="admin-pemerintahan" src="https://user-images.githubusercontent.com/249563/40972302-9cc393c4-6903-11e8-85c8-790bcea62475.png">

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by metalab25** [comment]
tombol "Batalkan" belum berfungi pada menu Pemerintah desa

**Comment by eddieridwan** [comment]
@metalab25 setiap masalah perlu dibuatkan issue tersendiri. Masalah tombol _Batal_ sudah dilaporkan di #1049.

**Comment by eddieridwan** [comment]
Sudah dikerjakan di #1056 . Tapi ada issue susulan #1059
