### ISSUE TITLE
[tampilan-admin] tidak ada lambang dan nama desa di header modul Admin

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#1051]
### Bagaimana alurnya sampai muncul masalah?
Buka modul Admin. Perhatikan header.

### Seperti apa yang diharapkan?
Ada lambang desa dan ada nama desa/kecamatan/kabupaten

### Apa yang terjadi?
Info itu tidak tampil.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by balongbesuk** [comment]
sepertinya bagus replace pada tulisan opensid = [logo + nama desa] SID = logo desa, 

pendapat sekilas,

**Comment by fitamrin** [comment]
Nanti saya kirim PR perubahannya. seperti contoh dibawah ini, bagaimana ??
![nama_desa](https://user-images.githubusercontent.com/39846379/40993859-e52ed8dc-6924-11e8-8951-d98afdf18ac7.jpg)

**Comment by eddieridwan** [comment]
@fitamrin saya akur. Yang lain, bagaimana?

**Comment by balongbesuk** [comment]
lanjut

**Comment by suphm** [comment]
saya setuju keduanya, usulan om @balongbesuk alternatif untuk tampilan hp/tab

**Comment by eddieridwan** [comment]
Sudah dikerjakan di PR #1056. Tapi ada issue susulan: #1058
