### ISSUE TITLE
[tampilan-admin] tampilan di dalam Data Penduduk masih berantakan

### ISSUE THREAD

**Issue by metalab25** [OpenSID/OpenSID#1052]
### Bagaimana alurnya sampai muncul masalah?
Masuk ke menu Data Penduduk > Wilayah Administratif
### Seperti apa yang diharapkan?
Yang adalah normal

### Apa yang terjadi?

![screenshot_41](https://user-images.githubusercontent.com/19917739/40985797-6f654a94-6917-11e8-9021-e33f6d063753.png)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | opensid pasca 18.06
| Versi PHP        | 
| System operasi   | Browser Demo AdminLTE

**Comment by balongbesuk** [comment]
"Saat ini yg siap diuji adalah layout tampilan dan modul SID Home"

yang bagian itu masih belum dikerjakan sepertinya pak, (termasuk menu pada SID Home yang tombol link menuju ke bagian menu penduduk dkk)
