### ISSUE TITLE
[tampilan-admin] sepertinya meta view port ketinggalan/ terhapus

### ISSUE THREAD

**Issue by ombimo** [OpenSID/OpenSID#1053]
sepertinya meta viewport terhapus, tampilan masih desktop ketika saya buka di hp/ menggunakan device toolbar chrome
`<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">`

### Bagaimana alurnya sampai muncul masalah?
membuka demo di opensid.info

### Seperti apa yang diharapkan?
masuk ke tampilan mobile

### Apa yang terjadi?
tampilan masih desktop

### Informasi tambahan 
![screenshot_20180605-230318](https://user-images.githubusercontent.com/20896126/40988505-75f02e1c-6915-11e8-8b23-9dbd2662fcec.png)
![image](https://user-images.githubusercontent.com/20896126/40988517-80e856d2-6915-11e8-9406-fd65a4cef615.png)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by balongbesuk** [comment]
nyoba test buka lewat HP sepertinya tampilannya memang perlu diperbesar, ( terlalu kecil masih butuh bantuan zoom in)

**Comment by metalab25** [comment]
Masih tampilan desktop

**Comment by eddieridwan** [comment]
Sudah dikerjakan di PR #1056
