### ISSUE TITLE
[tampilan-admin] Lakukan minimalisasi error pada inspect -> console

### ISSUE THREAD

**Issue by didikkurniawan** [OpenSID/OpenSID#1054]
Terdapat beberapa fungsi script yang tidak ke load, untuk browser chrome dapat dibuka dengan cara klik kanan browser -> inspect -> console. 

### Bagaimana alurnya sampai muncul masalah?
Ini terjadi pada menu home SID pada saat dilakukan inspect element console.

### Seperti apa yang diharapkan?
meminimalisasi error seperti itu agar performance web dapat terjaga. 

### Apa yang terjadi?
terjadi 16 error 1 warning

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 7.x
| System operasi   |  Windows

![capture](https://user-images.githubusercontent.com/11713976/41012404-8b79bc02-696b-11e8-889f-b675ca968d96.PNG)

**Comment by eddieridwan** [comment]
Mungkin error ini yg mengakibatkan masalah yg dilaporkan di #1048.

**Comment by didikkurniawan** [comment]
Kemungkinan bgtu pak, kalau udah minim error apalagi bisa 0 kemungkinan ada bug yang gagal load tidak akan terjadi. jadi tampilan normal kembali. @eddieridwan

**Comment by eddieridwan** [comment]
@didikkurniawan mohon periksa issue ini apakah sudah diperbaiki di commit https://github.com/fitamrin/OpenSID/commit/4346390f2e11c0d1e5910275df9a9c0b43603007

**Comment by eddieridwan** [comment]
Sudah dikerjakan di PR #1056
