### ISSUE TITLE
[tampilan-admin] [luar-spk] Tata ulang menu/submenu SID Home

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#1055]
Catatan: Issue ini mungkin di luar ruang lingkup SPK. Yaitu, bung @fitamrin tidak wajib melakukan.

Dengan penataan ulang menu utama + submenu, lebih tampak kejanggalan menu _SID Home_.

Supaya lebih konvensional, sebaiknya menu _SID Home_ ditata ulang sebagai berikut:

1. _SID Home_ diganti menjadi _Home_ saja dan langsung menampilkan halaman _Home_. Tidak mempunyai submenu.
2. Buat menu utama baru, _Data Desa_ dengan submenu
    1. _Identitas Desa_
    2. _Pemerintahan Desa_
3. Gabung isi halaman _Donasi_ ke dalam halaman _SID Home_.

**Comment by suphm** [comment]
tandai saja om ```luar-spk``` atau ```out-of-scope```

**Comment by afa28** [comment]
Pak @eddieridwan , apakah ini masih perlu???
