### ISSUE TITLE
[tampilan-admin] Coding style views perlu diperbaiki

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#1057]
### Bagaimana alurnya sampai muncul masalah?
Periksa script di file views yang siap di-review.

### Seperti apa yang diharapkan?
Coding style mengikuti http://platesphp.com/v3/templates/syntax/ seperti tertulis di SPK.

### Apa yang terjadi?
Masih ada script yg belum mengikuti coding style yg ditentukan.
Masih ada penggunaan kurung kurawal.

Contoh di `header.php`:
```
<?php if($foto){?>
	<img src="<?php echo AmbilFoto($foto)?>" class="user-image" alt="User Image"/>
<?php }else{?>
	<img src="<?php echo base_url()?>assets/files/user_pict/kuser.png" class="user-image" alt="User Image"/>
<?php }?>	
```

Seharusnya:
```
<?php if($foto): ?>
	<img src="<?php echo AmbilFoto($foto)?>" class="user-image" alt="User Image"/>
<?php else; ?>
	<img src="<?php echo base_url()?>assets/files/user_pict/kuser.png" class="user-image" alt="User Image"/>
<?php endif; ?>
```

Masih ada penggunaan `<?php echo $variable ?>`. Seharusnya `<?= $variable ?>`.

**Comment by eddieridwan** [comment]
Tambahan dari @suphm : 

- untuk membuat class 'active' atau icon-nya buat sebelum tag <li>
- sebisa mungkin hindari penggunaan '' (string kosong)

Selain itu, juga hindari adanya spasi sesudah statement (kalau menggunakan sublime text atau editor lainnya, mungkin ada setting supaya trailing spaces dihapus secara otomatis).

**Comment by eddieridwan** [comment]
@suphm , mohon periksa apakah issue ini sudah diperbaiki di PR #1060 . Terima kasih.

**Comment by eddieridwan** [comment]
Di `konfigurasi_form.php`:

- kurung kurawal perlu diganti:
```
<?php foreach($list_provinsi AS $data){?>
	<option value="<?php echo $data['nama']?>" data-kode="<?php echo $data['kode']?>" <?php if(strtolower($main['nama_propinsi'])== strtolower($data['nama'])) :?>selected<?php endif?>><?=$data['nama']?></option>
<?php }?>
```
- penggunaan `<?php echo $variable ?>` perlu diganti menjadi `<?= $variable ?>`

Di `pengurus.php`, `pengurus_form.php`, `footer.php`, `header.php` penggunaan `<?php echo $variable ?>` perlu diganti menjadi `<?= $variable ?>` (diganti global saja). 

Di `pengurus_form.php`, indentasi salah:
```
<label><input id="group1" type="radio" value="1" name="pamong_status" <?php if($pamong['pamong_status'] == '1' OR $pamong['pamong_status'] == ''):?>checked<?php endif?>></input>Aktif</label>&nbsp;&nbsp;
```
Di semua file di `views/home`, `header.php`, `footer.php`, `nav.php`, `setting.php` semua trailing spaces perlu dihapus. Ganti saja setting di editor anda supaya menghapus spasi di ujung kalimat secara otomatis.

**Comment by fitamrin** [comment]
@eddieridwan, Di pengurus.php, pengurus_form.php, footer.php, header.php penggunaan <?php echo $variable ?> perlu diganti menjadi <?= $variable ?> 
dibagian mana ? mohon lebih detail. Setau sayasudah ganti semua, kecuali untuk  $variable yang tergolong panjang..

**Comment by eddieridwan** [comment]
Contoh di `pengurus.php` , baris 6
`<li class="active">Pemerintahan <?php echo ucwords($this->setting->sebutan_desa)?></li>`
baris 16
`<i class="fa fa-plus"></i>Tambah Staf Pemerintahan <?php echo ucwords($this->setting->sebutan_desa)?>`

Cari saja `<?php echo` dan ubah menjadi `<?= `. Paling mudah global replace saja.

**Comment by eddieridwan** [comment]
@fitamrin perubahan `<?php echo` menjadi `<?= ` masih belum dikerjakan untuk `pengurus.php`, `pengurus_form.php`, `konfigurasi_form.php`.

Contoh di `pengurus.php` , baris 6
`<li class="active">Pemerintahan <?php echo ucwords($this->setting->sebutan_desa)?></li>`

Tinggal melakukan global replace saja.

**Comment by suphm** [comment]
ya om @eddieridwan, @fitamrin
masih ada beberapa yang kurang mengenai control strukture.
clue nya 
- gunakan operasi binary/ternary untuk echo sekata / duakata 
- gunakan if, else, endif, foreach hanya untuk output yang kompleks

misalnya masih ada kode ini
```<body class="skin-purple sidebar-mini  <?php if($hidmenu==1):?>sidebar-collapse<?php endif?>">```

```<label><input id="group1" type="radio" value="1" name="pamong_status" <?php if($pamong['pamong_status'] == '1' OR $pamong['pamong_status'] == ''):?>checked<?php endif?>></input>Aktif</label>&nbsp;&nbsp;```

bisa ganti ke ini
```<label><input id="group1" type="radio" value="1" name="pamong_status" <?php ($pamong['pamong_status'] == '1' OR !$pamong['pamong_status']) and print('checked') ?>></input>Aktif</label>&nbsp;&nbsp;```

```<body class="skin-purple sidebar-mini <?php $hidmenu and print('sidebar-collapse') ?>">```

atau seperti ini 
~~~
<?php $hidmenu or $hidmenu = 'sidebar-collapse' ?>
<body class="skin-purple sidebar-mini <?= $hidmenu ?>">
~~~

dan untukk title kerna terlalu panjang, sebaiknya pindahkan saja ke helper, buatkan fungsi dan pakai ```<?= page_title() ?>```

**Comment by eddieridwan** [comment]
Tutup issue ini.
Buka issue terpisah untuk perubahan spesifik, seperti #1118
