### ISSUE TITLE
Fitur: Log Penduduk perlu menampilkan semua peristiwa ubah status dasar

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#106]
Langkah yang diikuti:
- Ubah status dasar penduduk menjadi Pindah
- Di Log Penduduk, ubah status dasar penduduk tersebut kembali menjadi Hidup

Log bahwa penduduk itu tadinya pindah tidak akan ditampilkan lagi di Log Penduduk. Supaya riwayat penduduk tidak hilang, sebaiknya log bahwa penduduk tersebut pindah dan kembali lagi tetap ditampilkan di Log Penduduk.

**Comment by afri18** [comment]
ternyata masih ada kekurangan bung eddie, untuk penduduk yang mati,hilang atau pndah betul sudah tidak muncul di form kk, akan tetapi masih terhitung, bisa nggak untuk penduduk yang mati,hilang atau pindah tidak dihitung sebagai jumlah anggota keluarga lagi ??

**Comment by mizwaruddin** [comment]
@afri18 Apakah masih bermasalah?

**Comment by afa28** [comment]
Sudah diperbaiki di modul bumindes, jika masih terjadi masalah silahkan reopen issue ini.
