### ISSUE TITLE
[tampilan-admin] [luar-spk] Buatkan Pembagian halaman 

### ISSUE THREAD

**Issue by sup-ham** [OpenSID/OpenSID#1063]
### Seperti apa yang diharapkan?
Buatkan Pembagian halaman. misalnya daftar pamong desa, 10 baris per halaman
Opsi:
- menggunakan setting aplikasi
- menggunakan dropdown di toolbar

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | >= 3
| System operasi   |

**Comment by eddieridwan** [comment]
Apakah maksudnya tambahkan _paging_? Kalau iya, sebaiknya menggunakan paging yg disediakan Codeigniter, seperti halaman lainnya.

**Comment by suphm** [comment]
ya om, sepertiny  belum dipakai secara keseluruhan ya

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3261
