### ISSUE TITLE
[tampilan-admin] Ratakan form Identitas desa

### ISSUE THREAD

**Issue by suphm** [OpenSID/OpenSID#1065]
### Seperti apa yang diharapkan?
Buat nip camat, propinsi, tombol samakan  col-sm-8 saja 

### Apa yang terjadi?
![image](https://user-images.githubusercontent.com/3823496/41095107-99852920-6a7a-11e8-9923-590bd1c54409.png)
Tips: cek responsive di chrome dev tools

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 18.06
| Versi PHP        | &gt;= 3
| System operasi   |

**Comment by eddieridwan** [comment]
Sdh dikerjakan
