### ISSUE TITLE
[Bug] Log penduduk ganda pada penduduk tanpa Nomor KK

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#1067]
### Bagaimana alurnya sampai muncul masalah?
Ketika penduduk tanpa nomor KK (Pecah KK) di rubah status dasarnya pindah / mati / hilang data pada Log penduduk menjadi ganda

### Seperti apa yang diharapkan?
mungkin bisa di akali dengan melarang penduduk tanpa nomor KK merubah status dasarnya / perbaikan pada log penduduk untuk penduduk yang tanpa nomor KK

### Apa yang terjadi?
operator desa kami selalu mengambil cara praktis tersebut yaitu pecah anggota keluarga, lalu merubah status dasar anggota diluar pecah KK  tersebut, 

### Informasi tambahan 
![asas](https://user-images.githubusercontent.com/35319600/41137572-01f312e8-6b06-11e8-8b33-06a685b7788c.jpg)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 18.06
| Versi PHP        |  3.6
| System operasi   | win7

**Comment by eddieridwan** [comment]
Ini terjadi karena tabel _log_penduduk_, selain berisi rekaman aksi ubah status dasar, juga berisi rekaman semua aksi pecah KK (dan tambah penduduk domisili, dll). Sedangkan tampilan Log Penduduk saat ini hanya dimaksudkan untuk memperlihatkan daftar penduduk yang status dasarnya bukan 'Hidup', dan belum digunakan untuk menampilkan rekaman perubahan penduduk lainnya.

Solusi sementara adalah dengan membatasi tampilan Log Penduduk supaya hanya menunjukkan aksi perubahan status dasar, dan tidak menunjukkan rekaman aksi lainnya.
