### ISSUE TITLE
[tampilan-admin] Isi info sistem masih ada yang tidak beraturan

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#1076]
isi info sistem masih ada yang tidak beraturan

**Comment by eddieridwan** [comment]
@balongbesuk perlu lampirkan tampilannya, dan tunjukkan yang bermasalah.

**Comment by egodasa** [comment]
Sepertinya issue ini perlu diperbaiki. Mulai dari judul dan isi issue harus sesuai dengan template.
Ini foto menu pengaturan -> info sistem
![download 1](https://user-images.githubusercontent.com/9961837/41287065-c18ad54c-6e6b-11e8-81b4-3861ba588c8d.jpeg)

**Comment by balongbesuk** [comment]
nah sudah di tambahkan mas @egodasa, saya tidak sertakan karena sangat panjang,

**Comment by egodasa** [comment]
Maaf Mas @balongbesuk sebaiknya judul issue ini ditambahkan prefik [tampilan-admin] dan mungkin juga isi issue lebih dirapikan sesuai template.

**Comment by balongbesuk** [comment]
siap pak @egodasa

**Comment by eddieridwan** [comment]
@balongbesuk @egodasa : saya rapikan dan hapus comment supaya lebih jelas bagi @fitamrin .

**Comment by eddieridwan** [comment]
Sudah dikerjakan di #1108
