### ISSUE TITLE
[tampilan-admin] Perbaikan tombol di form manajemen modul

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#1077]
![untitled1](https://user-images.githubusercontent.com/35319600/41277104-6a9090b2-6e50-11e8-8391-54b4fdee4bf1.jpg)

**Comment by eddieridwan** [comment]
Setuju, tapi perubahan ini di luar ruang lingkup SPK. Jadi kita saja yg kerjakan nanti.

**Comment by balongbesuk** [comment]
saya usulkan karena saya bandingkan dengan opensid "lama", 

![untitled1](https://user-images.githubusercontent.com/35319600/41288719-81ad02d2-6e71-11e8-836a-eb9ad65dae92.jpg)

siap pak

**Comment by eddieridwan** [comment]
Sudah dikerjakan di #1108
