### ISSUE TITLE
[tampilan-admin] Ejaan dan penyamaan tombol di Pengaturan > Database > Impor

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#1079]
### Bagaimana alurnya sampai muncul masalah?
1. Buka halaman _Pengaturan > Database > Impor_
2. Perhatikan ejaan dan kedua tombol _Impor_.

### Seperti apa yang diharapkan?
Ejaan tertulis 'impor' (tanpa 't'), sesuai KBBI.
Ejaan tertulis 'di bawah' sesuai kaidah BI.
Tombol _Impor_ berukuran sama.

### Apa yang terjadi?
Ejaan tertulis 'import'
Ejaan tertulis 'dibawah'
Ukuran tombol _Impor_ berbeda.

<img width="1318" alt="ejaan-impor" src="https://user-images.githubusercontent.com/249563/41284625-319c57c8-6e7d-11e8-9aba-877c1d2eebfe.png">

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | tampilan-admin Tahap 2
| Versi PHP        | 
| System operasi   |

**Comment by balongbesuk** [comment]
intermezzo kalau ejaannya mengikuti bahasa baku,

Export > Ekspor
Backup / Restore > Cadangan / Mengembalikan ( jadi terasa janggal )

**Comment by balongbesuk** [comment]
![untitled1](https://user-images.githubusercontent.com/35319600/41313702-d3240942-6eb4-11e8-84cf-4a40e0be4d30.jpg)

dan jika mengikuti tampilan Opensid lama ada tambahan Database
(jika memang ditambahkan mungkin Migrasi DB tidak perlu disingkat? > Migrasi Database)

**Comment by eddieridwan** [comment]
@balongbesuk , kita samakan dulu dengan yg sdh ada di v18.06:

- sdh menggunakan 'ekspor', 'impor', 'unduh'
- masih menggunakan 'backup', 'restore'

Perubahan peristilahan sebaiknya nanti kita bahas terpisah dari SPK..

Mengenai judul submenu, saya kira biarkan seperti sdh dibuat di Tahap 2. Karena nanti saya usulkan kita tinjau ulang -- misalnya memindahkan submenu _Ekspor_, _Impor_, _Impor (BIP)_ ke menu _Penduduk_. Tapi kita bahas terpisah supaya tidak membingungkan @fitamrin .

**Comment by eddieridwan** [comment]
Sudah dikerjakan di #1108. 
Masih ada yang salah, akan dibuatkan issue baru.
