### ISSUE TITLE
[tampilan-admin]Penyamaan Tombol dan layout pada Backup / Restore

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#1082]
### Bagaimana alurnya sampai muncul masalah?
Buka halaman Pengaturan > Database > BackUp / Restore

### Seperti apa yang diharapkan?
mungkin desain layoutnya bisa "disamakan"

### Apa yang terjadi?
desain layoutnya tampil berbeda - beda,

### Informasi tambahan 

![untitled1](https://user-images.githubusercontent.com/35319600/41312770-2fdc8216-6eb2-11e8-801b-c743f55d648a.jpg)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | tampilan-admin Tahap 2
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dikerjakan di #1108.
