### ISSUE TITLE
[tampilan-admin] Perbesar Size Tulisan

### ISSUE THREAD

**Issue by SahlaniAfnan** [OpenSID/OpenSID#1086]
### ukuran tulisan isi agar size nya dinaikkan supaya agak seimbang dengan size judul

![1 rentang tulisan](https://user-images.githubusercontent.com/15683308/41321651-1c93e1f0-6ecf-11e8-8409-d186048527f4.jpg)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
@SahlaniAfnan di halaman Donasi, ukuran font 13px, sedangkan di halaman lainnya 11px. 
Mungkin di halaman Donasi, judulnya diperkecil supaya seimbang.
Tapi apakah kita naikkan ukuran font di semua halaman supaya defaultnya 13px? Karena 11px sepertinya terlalu kecil.

Mungkin kita perlu bahas dengan teman2 lain?

**Comment by MUHAMMADRANGSEL** [comment]
perlu disesuikan supaya cantik dan mudah dibaca

**Comment by afa28** [comment]
Pak @eddieridwan , apakah ini masih perlu ???

**Comment by afa28** [comment]
Apakah ini masih bermasalah??? Kalau tdk silahkan di close.

**Comment by mizwaruddin** [comment]
Apakah masih bermasalah?

**Comment by afa28** [comment]
Silahkan di reopen issue ini jika masih bermasalah.
