### ISSUE TITLE
Bug: Error pada Penduduk_model.php

### ISSUE THREAD

**Issue by metalab25** [OpenSID/OpenSID#1093]
### Bagaimana alurnya sampai muncul masalah?
Iseng-iseng buka error-log di hosting ech isinya nongol beginian

### Seperti apa yang diharapkan?
yang diharapkan adalah tidak terdapat error seperti ini

### Apa yang terjadi?
Tidak tau apa yang terjadi, sepertiny ini berkaitan dengan data penduduk dan data statistik

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 18.06
| Versi PHP        |  5.6
| System operasi   | Hosting

![screenshot_56](https://user-images.githubusercontent.com/19917739/41496283-770ac206-716e-11e8-859d-099c5c708b2d.png)

**Comment by eddieridwan** [comment]
@metalab25 : masalah anda tidak bisa di-replikasi di http://demo.opensid.info. Sepertinya ada setting/file yang kurang di hosting anda. Kelihatannya file helper `opensid_helper.php` tidak berhasil di-load, dan tidak ditemukan.

**Comment by metalab25** [comment]
Saya akan cek dulu apakah helper_opensid.php sudah ada didalam hosting atau tidak

**Comment by eddieridwan** [comment]
Apakah masih bermasalah?

**Comment by metalab25** [comment]
Masih

**Comment by eddieridwan** [comment]
Satu cara yg mungkin anda bisa coba: ganti script di file `index.php` seperti terlihat di gambar berikut. Perubahan ini akan menulis log file secara rinci untuk membantu melacak masalah. Kemudian coba replikasi kegiatan apa yg kira2 menyebabkan error tersebut -- lihat log file. Kalau error itu ditemukan di log file, silakan lampirkan seluruh log file tersebut di issue ini (dan jelaskan kegiatan apa yg dilakukan).

Sesudah itu kembalikan file `index.php` ke semula, supaya log file tidak membengkak.

<img width="1308" alt="log-rinci" src="https://user-images.githubusercontent.com/249563/42736686-8cdfd8fe-88ad-11e8-945a-4d1f44c0384f.png">

**Comment by eddieridwan** [comment]
Error ini sepertinya sudah tidak ditemukan di v18.08. Kami tutup issue ini. Silakan buka lagi kalau masih bermasalah -- dengan melampirkan informasi tambahan menjelaskan alur sampai terjadinya masalah.
