### ISSUE TITLE
[tampilan-admin] UX yang lebih baik

### ISSUE THREAD

**Issue by suphm** [OpenSID/OpenSID#1094]
### Seperti apa yang diharapkan?
Lebih baik semua button ditempatkan di bawah
1 "kembali" untuk back
1 "batal" untuk  reset
1 "simpan" untuk save
dan gunakan juga breadcrumb dari adminlte untuk link menu/submenu

**Comment by eddieridwan** [comment]
@suphm , aturan umum ini sudah ditambahkan di https://github.com/OpenSID/OpenSID/wiki/Aturan-Penulisan-Script.

Untuk issue dikerjakan, perlu dijelaskan/didaftarkan di halaman mana saja dan apa saja yg perlu diubah.

**Comment by eddieridwan** [comment]
Issue ini ditutup. Kalau ada perubahan spesifik, silakan buat issue baru.
