### ISSUE TITLE
Bug: Page Donasi Pengembangan OpenSID terlupa / hilang?

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#1096]
### Bagaimana alurnya sampai muncul masalah?
SID home >> Tab Donasi >> tekon tombol donasi pengembangan Opensid >> page donasi sepertinya lupa dibuat pada opensid.info 

### Seperti apa yang diharapkan?
bung @metalab25 bisa konfirmasi 

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 18.06
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Halaman _Donasi_ sudah selesai diubah dan disetujui sebagai bagian dari pekerjaan Memodernkan Tampilan Modul Admin. Karena itu, semua perubahan pada halaman _Donasi_ harus melalui pull request pada branch _tampilan-admin_, tidak lagi branch _master_.

**Comment by metalab25** [comment]
apakah maksudnya ini harus di PR pada branch "tampilan-admin" ????

**Comment by balongbesuk** [comment]
fix closed
