### ISSUE TITLE
[inventaris] Tampilan penanda tangan Inventaris

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#1097]
### Bagaimana alurnya sampai muncul masalah?
inventaris >> pilih tab inventaris (mana saja) >> unduh excel

### Seperti apa yang diharapkan?
perbaikan tampilan seperti pada tombol print

### Informasi tambahan 
![untitled1](https://user-images.githubusercontent.com/35319600/41498636-fc35586e-719c-11e8-9ab2-e8dbf23d6b76.jpg)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | pasca-18.06
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
@didikkurniawan lihat review di #1104 -- mohon diperbaiki dan dikirim ulang. Terima kasih.
