### ISSUE TITLE
[inventaris] Tampilan Search Inventaris kekecilan?

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#1098]
### Bagaimana alurnya sampai muncul masalah?
pilih menu inventaris

### Seperti apa yang diharapkan?
mungkin bisa diperbesar?

### Informasi tambahan 
![untitled1](https://user-images.githubusercontent.com/35319600/41498666-a17be770-719d-11e8-8081-254806a628cf.jpg)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | pasca 18.x
| Versi PHP        | 
| System operasi   |

**Comment by didikkurniawan** [comment]
Mohon direview untuk perbaikian issue ini, referensi pull req #1104

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR #1104.

Tetapi hanya kotak cari yg diperbesar. Font isiannya masih tampak kecil. Tetapi kami tutup issue ini, karena masalah font (jenis dan ukuran) perlu dibahas secara menyeluruh.
