### ISSUE TITLE
External Link yang ada di halaman backend OpenSID dibuat open new tab (target="_blank")

### ISSUE THREAD

**Issue by metalab25** [OpenSID/OpenSID#1100]
### Bagaimana alurnya sampai muncul masalah?
Pada saat coba klik link/url (external link) masih mengeksekusi halaman yang ada jadi halaman asli tertutup dengan halaman yang baru

### Seperti apa yang diharapkan?
Link yang ada (external link) seharusnya tidak menutup/atau menggantikan halaman yang ada jadi sebaiknya dibuat open new tab (target="_blank") pada tiap url/link External

### Apa yang terjadi?
saat ini masih menutupi atau menggantikan halaman yang ada

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | Demo Halaman Admin
| Versi PHP        |  Online
| System operasi   |  Online

**Comment by eddieridwan** [comment]
Aturan umum sudah ditambahkan di https://github.com/OpenSID/OpenSID/wiki/Aturan-Penulisan-Script.
