### ISSUE TITLE
[Inventaris] Tambahkan Fitur OpenMap

### ISSUE THREAD

**Issue by SahlaniAfnan** [OpenSID/OpenSID#1103]
### Lebih mempermudah menginventarisir asset desa
![browse ke openmap](https://user-images.githubusercontent.com/15683308/41691039-ae112e9a-7522-11e8-96db-490c914ce0cb.jpg)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by didikkurniawan** [comment]
mungkin untuk issue ini saya masih perlu belajar mengenai OpenMap soalnya belum dapat pengalaman mengerjakan OpenMap.

**Comment by eddieridwan** [comment]
@didikkurniawan : issue ini masih perlu pembahasan lebih lanjut. Seperti usul dari Il Ham (di FB), lebih baik tanah di menu Inventaris dikaitkan dengan persil di menu Persil. Kemudian pengaitan dengan lokasi di OpenStreetMap dilakukan di Persil, bukan di Inventaris (lihat issue #284.
