### ISSUE TITLE
[inventaris] Hilangkan error javascript yg tampak di inspector browser

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#1106]
### Bagaimana alurnya sampai muncul masalah?
1. Buka halaman inventaris mana saja, misalnya _Inventaris > Tanah_.
2. Perhatikan console javascript di inspector browser (misalnya Chrome)

### Seperti apa yang diharapkan?
Tidak ada error

### Apa yang terjadi?
Ada error `jquery.elastic.js:3 Uncaught TypeError: $(...).elastic is not a function`.

<img width="1254" alt="error-js-inventaris" src="https://user-images.githubusercontent.com/249563/41710378-dd009dec-7588-11e8-9e2a-dadfe20c02a7.png">

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 18.06-pasca
| Versi PHP        | 
| System operasi   |

**Comment by didikkurniawan** [comment]
Pak untuk issue #1106, ternyata error dimunculkan karena adanya konfik antar jquery yang diload di file https://github.com/OpenSID/OpenSID/blob/master/donjo-app/views/header.php dengan file https://github.com/OpenSID/OpenSID/blob/master/donjo-app/views/inventaris/nav.php .

Mungkin issue ini bisa diperbaiki setelah selesai modernisasi tampilan soalnhya di versi itu jquery sudah ditetapkan dan modul inventaris akan mengikuti versi tersebut.

**Comment by eddieridwan** [comment]
@didikkurniawan, setuju.

**Comment by eddieridwan** [comment]
Masalah ini sudah tidak muncul lagi di versi tampilan-admin.
