### ISSUE TITLE
Bug: Filter Aktif/Tidak Aktif tidak berfungsi di Pengaturan > Manajemen Modul

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#1114]
### Bagaimana alurnya sampai muncul masalah?
Buka Pengaturan >> Manajemen Modul

Sebelumnya saya bingung memasukkan isue ini pada tampilan admin / opensid karena issue ini ada pada keduanya, untuk issuenya saya jelaskan pada Gambar

### Informasi tambahan 
![untitled1](https://user-images.githubusercontent.com/35319600/41760260-c87030c4-761c-11e8-846a-53f084f36b71.jpg)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 18.06
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
@balongbesuk karena masalah ini ada di v18.06, memperbaiki ini menjadi issue biasa, bukan untuk pekerjaan [tampilan-admin]

**Comment by eddieridwan** [comment]
Sudah dicommit ke master. Sekalian memperbaiki fitur cari.
