### ISSUE TITLE
[tampilan-admin] Foto Pemerintah Desa mengecil?

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#1116]
### Bagaimana alurnya sampai muncul masalah?
Buka tampilan HP Home >> Pemerintah Desa

### Seperti apa yang diharapkan?
Mungkin bisa tidak ikut mengecil?

### Apa yang terjadi?
Foto pemerintah Desa Mengecil

### Informasi tambahan 
![untitled1](https://user-images.githubusercontent.com/35319600/41760667-bfe54df2-761e-11e8-8b45-439846b6cf0d.jpg)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | tampilan-admin Tahap 2
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dicommit di #1119
