### ISSUE TITLE
Ketika Artikel Terlalu banyak Tanda Panah menunjukkan alamat ikut kebawah

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#1121]
### Bagaimana alurnya sampai muncul masalah?
Dihalaman Depan Ketika artikel sudah banyak maka tanda panahnya yang menandakan halan berikutnya juga ikut kebawah seperti Gambar dibawah ini : 
![screenshot 2018-06-24 18 36 04](https://user-images.githubusercontent.com/25834335/41818281-fccb3a90-77dd-11e8-8583-71d153d9c941.png)

### Seperti apa yang diharapkan?

Supaya Tanda Panah Tidak Kebawah dicukupkan sampai halaman 16 langsung tanda panah
### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | Pasca 18.06
| Versi PHP        | 
| System operasi   |

**Comment by LIQRGV** [comment]
Kalau dibatasi hingga 5 saja seperti ini bagaimana?

![image](https://user-images.githubusercontent.com/5935057/41820189-b01ea21c-77f7-11e8-9533-2598088bc26d.png)

**Comment by MUHAMMADRANGSEL** [comment]
nah yang ini juga boleh,,, hehhe mantap bung LIQRGV

**Comment by LIQRGV** [comment]
Jadi seperti ini?
![image](https://user-images.githubusercontent.com/5935057/41820601-6b6f1938-77fe-11e8-9cd9-9468b4cb81a5.png)

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR #1125
