### ISSUE TITLE
Bug: Ketika Data Suplemen di Unduh Dalam Format Excel data hanya separuh

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#1126]
### Bagaimana alurnya sampai muncul masalah?
Klik Menu Penduduk ==> Data Suplemen, ketika ingin mengunduh Data Suplemen dan data yang bisa ditampilkan hanya sampai 200 org/ KK, ketika ingin unduh dengan data diatas 200 seperti contoh 201- 1000 dan seterusnya maka tidak bisa diunduh semuanya
![screenshot 2018-06-26 01 21 41](https://user-images.githubusercontent.com/25834335/41865347-53af17e4-78df-11e8-849c-06c9c59e72fa.png)

### Seperti apa yang diharapkan?
Ketika ingin mengunduh data dalam bentuk excel di data suplemen maka datanya yang bisa diunduh tidak ada batasannya atau sesuai dengan data yang ada

### Apa yang terjadi?
Opertaor akan berulang kali mengunduh data dengan secara bertahap-tahap, dan bikin file data jadi numpuk

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | Pasca 18.06
| Versi PHP        | 
| System operasi   |

**Comment by MUHAMMADRANGSEL** [comment]
untuk issue ini sdh saya coba kerjakan namun perlu di koreksi bung eddie
[Suplemen.zip](https://github.com/OpenSID/OpenSID/files/2137440/Suplemen.zip)

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
