### ISSUE TITLE
[tampilan-admin] Fitur cari di Admin Web > Komentar tidak berfungsi

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#1130]
### Bagaimana alurnya sampai muncul masalah?
1. Buka _Admin Web > Komentar_
2. Asumsi ada beberapa komentar
3. Gunakan fitur _Cari_ untuk menampilkan komentar yg berisi kata tertentu

### Seperti apa yang diharapkan?
Fitur _Cari_ berfungsi normal seperti di v18.06

### Apa yang terjadi?
Fitur _Cari_ tidak berfungsi.
<img width="1333" alt="cari-komentar" src="https://user-images.githubusercontent.com/249563/41950604-1e3e4f04-7a0a-11e8-83f2-5d68c186239d.png">

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | tampilan-admin Tahap 3
| Versi PHP        | 
| System operasi   |

**Comment by ombimo** [comment]
pencarian di adminweb artikel juga tidak berfungsi, perlu dibuat issue baru kah ?

**Comment by eddieridwan** [comment]
@ombimo ya, perlu buat issue baru supaya lebih mudah diperiksa ulang.

**Comment by eddieridwan** [comment]
Sudah dikerjakan di PR #1179.
