### ISSUE TITLE
[tampilan-admin] checkbox terlalu lebar jika dibuka di layar kecil

### ISSUE THREAD

**Issue by ombimo** [OpenSID/OpenSID#1131]
![image](https://user-images.githubusercontent.com/20896126/41950707-8140bd12-79f1-11e8-9efb-ba9982a52b98.png)

### Bagaimana alurnya sampai muncul masalah?
Klik submenu Tahap 3, di menu Admin Web

### Seperti apa yang diharapkan?
tidak terlalu lebar jika di buka di layar kecil (HP)

### Apa yang terjadi?
checkbox yang terlalu lebar

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | tampilan-admin tahap 3
| Versi PHP        | 
| System operasi   |

**Comment by balongbesuk** [comment]
masalah check box ini terjadi dibanyak tempat (tampilan dilayar kecil / HP), seperti pada, 
home >> pemerintahan desa
SMS
Pengaturan
Laporan

**Comment by eddieridwan** [comment]
@balongbesuk : daftarkan saja semua tempat ditemukan. Untuk nanti diperiksa ulang sesudah diperbaiki.

**Comment by eddieridwan** [comment]
Sudah dikerjakan di PR #1179.
