### ISSUE TITLE
[tampilan-admin] pilihan di slider tidak menjadi terang jika ada yg dipilih lainnya

### ISSUE THREAD

**Issue by ombimo** [OpenSID/OpenSID#1133]
### Bagaimana alurnya sampai muncul masalah?
ke menu adminweb -> slider
ingin mengubah jenis slider yang tampil

### Seperti apa yang diharapkan?
warna pilihan berubah ke pilihan yang akan di pilih, dan sisanya berwarna terang

### Apa yang terjadi?
![image](https://user-images.githubusercontent.com/20896126/41951667-347c708e-79f6-11e8-9622-0fef51242ec6.png)
warna pilihan yang dipilih dan yang dipilih sebelumnya berubah ke gelap semua

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | tampilan-admin tahap 3
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
@ombimo jangan lupa menyalin link issue ke https://opensid.slack.com/messages/CA46X3NMC/details/ (channel #tampilan-admin) karena perjanjian kita begitu. Juga beri label 'tampilan-admin' pada issue supaya bisa lebih mudah difilter issue yg perlu dikerjakan. Terima kasih.

**Comment by eddieridwan** [comment]
Sudah dikerjakan di PR #1179
