### ISSUE TITLE
[Bug] Fitur cari di Admin Web > Dokumen tidak berfungsi

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#1138]
### Bagaimana alurnya sampai muncul masalah?
1. Buka _Admin Web > Dokumen_
2. Coba fitur _Cari_

### Seperti apa yang diharapkan?
Fitur _Cari_ berfungsi normal

### Apa yang terjadi?
Fitur _Cari_ menhasilkan error.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 18.06
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Masalah serupa di:

1. _Sekretariat > SK Kades_
2. _Sekretariat > PERDES

**Comment by agungsugiarto** [comment]
1. Bug terkait tidak bisa menambahkan dokumen baru jika tidak menyertakan unggah dokumen.
2. Fitur cari pada beta.opensid berfungsi normal namun tidak berfungsi pada demo.opensid.

**Comment by eddieridwan** [comment]
@agungsugiarto 
- demo.opensid.info menampilkan v18.08,
- beta.opensid.info menampilkan branch _master_, lebih terkini. Kalau normal berarti error tersebut sudah dikerjakan.

Batasi laporan issue menggunakan versi terkini, yaitu di beta.opensid.info.

Mengenai bug terkait (butir 1 di comment anda) sebaiknya buatkan issue baru.

**Comment by agungsugiarto** [comment]
Sudah ditambahkan ke issue

**Comment by eddieridwan** [comment]
Sudah diperbaiki, walaupun commitnya tidak jelas yg mana.
