### ISSUE TITLE
Tampilan Dimensi Image Pada Artikel Belum Presisi

### ISSUE THREAD

**Issue by akangazay** [OpenSID/OpenSID#1159]
![image](https://user-images.githubusercontent.com/5108522/42010174-ac16df00-7ab7-11e8-927b-da78ba5b069f.png)

### Bagaimana alurnya sampai muncul masalah?
1. Tampilan Dimensi image Blm presisi dengan layout artikel.
2. Belum ada Opsi Pengaturan Image pada text editor, (Size, Deskripsi, Title image)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
@akangazay sudah coba pada versi v18.06 di http://demo.opensid.info?
Kalau masalahnya ada di versi itu, ini menjadi bug biasa, bukan untuk pekerjaan Tampilan Modul Admin.

**Comment by afa28** [comment]
Upgrade tymce untuk isian artikel sdah bisa menyesuaikan letak komponen2 yg ada didalamnya. Silahkan dipelajari lg.
