### ISSUE TITLE
[Bug] bullet List tidak tampil

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#1163]
### Bagaimana alurnya sampai muncul masalah?
buat daftar menggunakan bullet list pada artikel

### Seperti apa yang diharapkan?
menampilkan bullet list

### Apa yang terjadi?
bullet list tidak tampil pada postingan di website

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by metalab25** [comment]
tambahkan pada file css anda

ul {
    list-style: square;
    margin: 0;
    margin-left: 40px;
    padding: 0px;
}

**Hasilnya** 
![screenshot_93](https://user-images.githubusercontent.com/19917739/42014918-7c19ceb4-7ad7-11e8-8529-ee9904022a75.png)

**Comment by eddieridwan** [comment]
@balongbesuk apakah sudah coba pada versi v18.06 di http://demo.opensid.info?
Kalau masalahnya ada di versi itu, ini menjadi bug biasa, bukan untuk pekerjaan Tampilan Modul Admin.

**Comment by balongbesuk** [comment]
saya coba pada demo-admin pak,

**Comment by eddieridwan** [comment]
Ya, jadi bug kita, bukan karena pekerjaan tampilan-admin.

**Comment by metalab25** [comment]
Ini memang bukan pekerjaan tampilan admin, memang bug bawaan sid. 
Tadi saya coba menambahkan code style diatas pada default.css

**Comment by eddieridwan** [comment]
Karena terkait tampilan yang sudah dikerjakan di `tampilan-admin`, sebaiknya issue ini diperbaiki nanti setelah pekerjaan Memodernkan Tampilan Modul Admin selesai.

**Comment by eddieridwan** [comment]
Karena ini akan bentrok dengan pekerjaan`tampilan-admin`, issue ini perlu ditunda menunggu selesainya `tampilan-admin`

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
