### ISSUE TITLE
[inventaris] Perbaikan tampilan menu inventaris

### ISSUE THREAD

**Issue by happyagung25** [OpenSID/OpenSID#1164]
### Bagaimana alurnya sampai muncul masalah?
![screenshot_92](https://user-images.githubusercontent.com/19917739/42014657-faf4266e-7ad5-11e8-80ef-95214cdef727.png)

Perlu ditambahkan margin-bottom dan sebaiknya penggunaan style hardcode dihindari dan dipindahkan ke file css

### Seperti apa yang diharapkan?

![screenshot_91](https://user-images.githubusercontent.com/19917739/42014692-25d17b3e-7ad6-11e8-8a6b-6c201d60b9d2.png)

Menjadi seperti ini tidak telalu menempel dengan top bar menu.

### Informasi tambahan 
Apabila berkenan saya akan bantu perbaikan

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 18.06-pasca
| Versi PHP        | 5.6.33
| System operasi   | Windows 7

**Comment by eddieridwan** [comment]
@metalab25 dengan tampilan-admin baru, apakah issue ini sudah bisa ditutup?
