### ISSUE TITLE
[tampilan-admin] tooltips "Rincin anggota" tidak muncul di SMS > Kontak > Group Kontak

### ISSUE THREAD

**Issue by sugiantoe** [OpenSID/OpenSID#1172]
### Bagaimana alurnya sampai muncul masalah?
1. Buka SMS > Daftar Kontak > Group Kontak
2. Arahkan kursor pada tombol Rincian Anggota

### Seperti apa yang diharapkan?
muncul tooltips "Rincian Anggota" pada tombol tersebut

### Apa yang terjadi?
tidak muncul tooltips pada tombol Rincian Anggota

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | tampilan admin tahap 3
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dikerjakan di PR #1179.
