### ISSUE TITLE
[Bug] Kesalahan di SMS > Kontak > Daftar Kontak, detail kontak penduduk menampilkan data penduduk lain

### ISSUE THREAD

**Issue by sugiantoe** [OpenSID/OpenSID#1173]
### Bagaimana alurnya sampai muncul masalah?
1. SMS > Kontak > Daftar kontak
2. klik nama penduduk

### Apa yang terjadi?
Detail penduduk menampilkan data penduduk yang lain.
![image](https://user-images.githubusercontent.com/28652833/42046812-e2377c40-7b28-11e8-8e2f-612f1b81021a.png)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | OpenSID 18.06-pasca
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR #1559
