### ISSUE TITLE
[SECURITY BUG] - Reflected Cross Site Scripting (XSS) On Parameter Cari

### ISSUE THREAD

**Issue by jrsfaisal** [OpenSID/OpenSID#1175]
Sserangan XSS merupakan serangan yang menginjeksikan script ke situs web
untuk tujuan tertentu seperti mengambil cookies, mengarahkan korban ke malicious site dsb.
Serangan ini terjadi pasa sisi client side (browser).

### Bagaimana alurnya sampai muncul masalah?
1. Pada menu pencarian inputkan payload XSS seperti <script>alert('XSS')</script> atau payload XSS umum yang lain.
2. XSS akan tereksekusi pada URL http://ip-address/index.php/first?cari=%3Cimg+src%3Dx+onerror%3Dalert%28%27XSS%27%29%3E

![xss](https://user-images.githubusercontent.com/13029584/42132327-f9757380-7d3f-11e8-9715-cc6fd2ebcac1.png)

### Seperti apa yang diharapkan?
Pengembang perlu melakukan filter spesial karakter, tag html dan javascript untuk memfilter atau menggunakan library anti XSS yang terdapat pada CI untuk megantisipasi serangan XSS.

### Apa yang terjadi?
Serangan XSS dapat berdampak pada sisi client. Melalui serangan ini dapat dimanfaatkan oleh attacker untuk mengambil cookies korban, mengalihkan kehalaman yang mengandung malware atau phising site.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | OpenSID 18.06-pasca
| Versi PHP        | PHP 5.5.9-1ubuntu4.25
| System operasi   | Ubuntu 14.04.2 LTS

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.

**Comment by Lali12345** [comment]
Ok

**Comment by Lali12345** [comment]
'><img src="https://c.top4top.io/p_2009s6hcr0.jpg" height="200" width="100">'
