### ISSUE TITLE
Perlu perbaikan kembali surat masuk seperti rilis opensid 2.11

### ISSUE THREAD

**Issue by Gunturwijay** [OpenSID/OpenSID#1181]
### Bagaimana alurnya sampai muncul masalah?
Sekretariat>surat masuk>ubah>simpan

### Seperti apa yang diharapkan?
Diharapakan:
1. file gambar pada surat masuk tidak hilang saat melakukan perubahan data
2. Pada saat aksi unduh (lihat file gambar) sebaiknya jangan unduh download, tapi unduh lihat gambar seperti rilis opensid 2.11

### Apa yang terjadi?
1. File gambar hilang
2. File gambar unduh download

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Masalah gambar hilang sudah tidak ditemukan lagi di v18.09.
Kalau file gambar ditampilkan langsung. Kalau file PDF atau lainnya, diunduh.
