### ISSUE TITLE
[Bug] Nama yang ada tanda titik (.) tidak bisa tersimpan

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#1194]
### Bagaimana alurnya sampai muncul masalah?
Ketika mengubah data penduduk, dan pada nama penduduk yang terdapat tanda titik contoh seperti M. AHLUL tidak bisa tersimpan sepeti gambar diatas
![image](https://user-images.githubusercontent.com/25834335/42199048-95e9548c-7ebe-11e8-962b-c2c9f9fc147d.png)

### Seperti apa yang diharapkan?
untuk nama yang ada tanda titik (.) bisa tersimpan seperti sebelumnya

### Apa yang terjadi?
Data Penduduk yang ada tanda titik (.) tidak bisa tersimpan 

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 18.07
| Versi PHP        | 
| System operasi   |

**Comment by MUHAMMADRANGSEL** [comment]
mohon ini segera dikerjakan, karena sangat mengganggu sekali, mengingat kami sedang melakukan update data

**Comment by eddieridwan** [comment]
Heheh... dulu pra-rilis dan situs demo tidak sempat diuji-coba, ya?

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
Tapi harap diperhatikan, pra-rilis juga berisi solusi xss filtering sehingga artikel berisi iframe tidak akan menampilkan iframe tersebut. Lihat issue https://github.com/OpenSID/OpenSID/issues/1178

**Comment by MUHAMMADRANGSEL** [comment]
Terima kasih banyak bung eddie
