### ISSUE TITLE
[tampilan-admin] Posisi icon di SID Home > SID Home menjadi salah

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#1199]
### Bagaimana alurnya sampai muncul masalah?
1. Buka _SID Home > SID Home_
2. Perhatikan penampilan tombol2 dashboard

### Seperti apa yang diharapkan?
Icon terlihat rapi, tidak seperti di gambar berikut.
<img width="1322" alt="icon-home" src="https://user-images.githubusercontent.com/249563/42298943-e1b915bc-804b-11e8-89ae-a50af37e7c80.png">

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | tampilan-admin Tahap 3
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dikerjakan di PR #1200

**Comment by palahen** [comment]
- modul plan, maps tidak muncul pada lokasi, garis... dan belum pahan dengan lainnya
