### ISSUE TITLE
Membuat Peta Desa

### ISSUE THREAD

**Issue by buchary** [OpenSID/OpenSID#120]
Bagaimana cara membuat peta desa seperti gambar berikut: 
![peta desa](https://cloud.githubusercontent.com/assets/20512335/18336293/7f9a78b6-75b8-11e6-9a1a-867b2fd340bf.png)
Sehingga pada saat dibuka yang tampil peta wilayah desa.

**Comment by eddieridwan** [comment]
Mr Bur, silakan cari info dan buat panduannya.

**Comment by eddieridwan** [comment]
Sekarang sudah disediakan di edit Wilayah Desa di menu SID Home > Identitas Desa.
