### ISSUE TITLE
[Bug] Nama penduduk perlu bisa berisi karakter koma (,)

### ISSUE THREAD

**Issue by heisanonymous** [OpenSID/OpenSID#1203]
### Bagaimana alurnya sampai muncul masalah?
Ketika hanya karakter alpha, spasi dan tanda petik yang bisa digunakan maka kami kesulitan ketika data dalam kk menggunakan gelar akademik yang memerlukan tanda "," dan "."

### Seperti apa yang diharapkan?
ditambahkan untuk tanda "," dan "."

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 18.07
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Issue #1194 sudah dikerjakan untuk membolehkan nama berisi titik (.). Issue ini untuk juga membolehkan nama berisi koma (,).

**Comment by MUHAMMADRANGSEL** [comment]
kami juga mengalami masalah ini dan untuk issue ini kami mencoba mencari solusinya dan alhamdulillah berhasil dan bersama ini kami lampirkan perubahn scripnya : 
[Penduduk_model.zip](https://github.com/OpenSID/OpenSID/files/2205306/Penduduk_model.zip)

**Comment by eddieridwan** [comment]
@MUHAMMADRANGSEL sepertinya anda perlu belajar mengirim pull request, supaya perubahan anda bisa lebih cepat digabung..

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.

**Comment by MUHAMMADRANGSEL** [comment]
Kepingin sekali bisa bung Eddie,, namun saya kurang paham

**Comment by eddieridwan** [comment]
@MUHAMMADRANGSEL coba pelan2 pelajari https://www.petanikode.com/github-workflow/
