### ISSUE TITLE
[tampilan-admin] footer Bantuan > Tambah Program Bantuan memotong sidebar

### ISSUE THREAD

**Issue by tasdiek** [OpenSID/OpenSID#1204]
1. Buka _Bantuan > Tambah Program Bantuan_.
2. Perhatikan footer.

Pada program bantuan di tampilan admin modern, waktu create bantuan footer (yang warna putih) memotong sidebar

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | tampilan-admin Tahap 4
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dikerjakan di PR #1260
