### ISSUE TITLE
[tampilan-admin] tampilan legenda pada layar kecil tidak muncul

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#1206]
### Bagaimana alurnya sampai muncul masalah?
buka tampilan HP peta >> legenda 

### Seperti apa yang diharapkan?
legenda bisa muncul

### Apa yang terjadi?
saat ini tombol legenda ketika ditekan tidak memunculkan menu legenda / tampilan kurang 

### Informasi tambahan 
![untitledasas](https://user-images.githubusercontent.com/35319600/42356869-2abe31a8-80ff-11e8-8703-f00864d6a234.jpg)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dikerjakan di PR #1260
