### ISSUE TITLE
[tampilan-admin] Nomor pada grafik dan tabel berbeda

### ISSUE THREAD

**Issue by ombimo** [OpenSID/OpenSID#1207]
### Bagaimana alurnya sampai muncul masalah?
ke menu statistik -> statistik kependudukan -> umur -> grafik data

### Seperti apa yang diharapkan?
nomornya di grafik dan tabel sama, biar tidak terjadi kebingungan

### Apa yang terjadi?
nomor di grafik dan tabel berbeda

### Informasi tambahan 
![image](https://user-images.githubusercontent.com/20896126/42357223-0d4b8984-8101-11e8-86d6-1c64eedec813.png)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | tampilan admin tahap 4
| Versi PHP        | 
| System operasi   |

**Comment by balongbesuk** [comment]
hal ini terjadi di seluruh bagian menu data statistik pada tampilan grafik data

**Comment by eddieridwan** [comment]
Sudah dikerjakan di PR #1260
