### ISSUE TITLE
[tampilan-admin] Statistik > Laporan Bulanan > cetak/unduh tidak menampilkan Jabatan dan TTD

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#1208]
### Bagaimana alurnya sampai muncul masalah?
statistik > laporan bulanan > pilih staf pemerintahan dan jabatan > coba cetak / unduh

### Seperti apa yang diharapkan?
jabatan dan nama perangkat terisi

### Apa yang terjadi?
saat ini tidak terisi / kosong

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dikerjakan di PR #1260
