### ISSUE TITLE
[tampilan-admin] tombol aksi peta pada menu Plan > Lokasi tidak menampilkan peta

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#1209]
### Bagaimana alurnya sampai muncul masalah?
planj ?? cek kembali tombol aksi lokasi yang menampilkan peta

(Menu _Plan > Lokasi_, tombol lokasi/peta di kolom _Aksi_)
### Seperti apa yang diharapkan?
peta muncul

### Apa yang terjadi?
untuk saat ini peta tidak muncul

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
PR #1260 belum memperbaiki. Ada error js console.
<img width="1234" alt="lokasi-lokasi" src="https://user-images.githubusercontent.com/249563/42551273-cdd2d8b2-8519-11e8-97fa-8e8ef20e346b.png">

**Comment by eddieridwan** [comment]
Sudah dikerjakan di PR #1279
