### ISSUE TITLE
[Bug] warna tipe poligon tidak muncul --> tambahkan Migrasi DB

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#1210]
### Bagaimana alurnya sampai muncul masalah?
plan >> type poligon

### Seperti apa yang diharapkan?
tampilkan warna

### Apa yang terjadi?
saat ini tidak tampil

### Informasi tambahan 
![untitled1](https://user-images.githubusercontent.com/35319600/42371566-096d84dc-813a-11e8-9f57-636002ce108e.jpg)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Dari @fitamrin : Untuk #1210 masalah warna tidak muncul di tabel.    Masalah ini muncul karena pada versi 18.07 input field warna tidak menggunakan tanda pagar (#). Sedangkan pada versi bootstrap input field warna menggunakan plugin colorpicker sehingga input warna otomatis menggunakan tanda pagar (#) (standar penulisan color di css). Silakan diedit ulang data nya untuk menampilkan warna.

Saya rasa penggunaan plugin colorpicker lebih memudahkan bagi pegguna. dan saya lihat sepertinya belum ada efek samping perubahan ini . Namun terserah pada teman pemeriksa, jika menginginkan model lama, akan saya ubah tanpa pengguna plugin colorpicker (manual).

**Comment by eddieridwan** [comment]
Terima kasih. Mengenai #1210 lebih baik menggunakan colorpicker. Data warna yg ada bisa diubah menggunakan Migrasi DB di _Database_model.php_ sekalian nanti dengan semua perubahan database lainnya untuk pekerjaan ini.

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
