### ISSUE TITLE
[tampilan-admin] tampilan peta pada browser chrome bermasalah

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#1211]
### Bagaimana alurnya sampai muncul masalah?
buka menu peta dengan browser chrome tampilannya aneh (peta terpotong dan control panel melebar)
(saya menggunakan monitor wide screen 21:9 mungkin tampilan tersebut hanya di browser saya, sudah coba refresh cache hasilnya tidak berubah)

### Informasi tambahan 
![untitled1](https://user-images.githubusercontent.com/35319600/42372176-be1e2c32-813b-11e8-9dd2-464a3cd8adb8.jpg)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dikerjakan di PR #1260
