### ISSUE TITLE
wpsid error

### ISSUE THREAD

**Issue by L007** [OpenSID/OpenSID#1223]
Database gagal terkoneksi dan Path SID salah, padahal sudah benar
mohon pencerahannya untuk langkah-langkah installasi setelah activate plugin
terimakasih

![image](https://user-images.githubusercontent.com/15906655/42409122-d82ecf7c-81ff-11e8-9da5-6be51bf96e6d.png)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 18.07
| Versi PHP        |  7.1.2
| System operasi   | Windows 8.1

**Comment by metalab25** [comment]
ach disaya kok baik" aja bahkan sampe saya buat installer WP+WPNdeso+WPSID+OpenSID.
dan sepertinya disini bukan tempat kirim issue terkait WPSID

**Comment by eddieridwan** [comment]
Pertanyaan cara penggunaan sebaiknya di https://www.facebook.com/groups/OpenSID/. Issue dibatasi untuk masalah yg memang perlu perbaikan script.

Issue ini kami tutup. Silakan lanjutkan di FB.
