### ISSUE TITLE
Pindahkan Posisi Form Nomor Kartu Peserta dan Form Gambar Kartu Peserta

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#1233]
### Bagaimana alurnya sampai muncul masalah?
Waktu Menambahkan Peserta untuk Form
1. Nomor Kartu Peserta
2. Gambar Kartu Peserta
yang Posisinya sekarang dibawah Form Warganegara / Agama KK
sebaiknya di Pindahkan ke bawah
1. Form Nomor Kartu Peserta dipindahkan ke atas Form NIK
2. Form Gambar Kartu Peserta dipindahkan ke bawah Form Alamat
![screenshot 2018-07-08 00 27 41](https://user-images.githubusercontent.com/25834335/42412843-c36cf32e-8246-11e8-9aa1-03779516fd13.png)
![screenshot 2018-07-08 00 29 50](https://user-images.githubusercontent.com/25834335/42412845-c3adc066-8246-11e8-8683-c8ef6c8dcaad.png)

### Seperti apa yang diharapkan?
Supaya lebih rapi

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah ada di v18.07.

**Comment by andriawan** [comment]
saya sempat cek scriptnya. perubahan posisi form dengan script yang sekarang sulit untuk direalisasikan karena secara teknis ada 2 tag form html yang berbeda. pendekatan terbaik mengubah salah satu form menjadi request ajax.

**Comment by metalab25** [comment]
Mungkin yang dimaksud seperti gambar dibawah ini ????
![screenshot_184](https://user-images.githubusercontent.com/19917739/45918681-3f9ab500-bebd-11e8-8dd1-d6979c15ba93.png)

**Comment by metalab25** [comment]
Perubahan" ringan seperti ini boleh saya tangani ????
Plis command bung @eddieridwan

**Comment by eddieridwan** [comment]
@metalab25, siapa saja tentu boleh mengerjakan. Silakan. Pull requestnya ditunggu.

Mohon diperhatikan aturan penulisan script di https://github.com/OpenSID/OpenSID/issues/1287, yang sekarang perlu kita patuhi di semua script.

**Comment by metalab25** [comment]
apa hubungannya issue ini dengan #1287.

**Comment by metalab25** [comment]
bung @eddieridwan mohon direview dulu.... hanya bisa seperti itu

**Comment by eddieridwan** [comment]
Telah dicommit ke master melalui PR #1693.
