### ISSUE TITLE
Status Kehamilan di Data Kesehatan 

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#1234]
### Bagaimana alurnya sampai muncul masalah?
Untuk Pilihan Status Kehamilan di Data Kesehatan masih kelihatan walaupun jenis kelamin Laki-Laki

### Seperti apa yang diharapkan?
Untuk Status Kehamilan hanya muncul bagi yang statusnya Kawin dan khusus untuk Jenis Perempuan dan bisa saja bagi yang perempuan status cerai 

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
