### ISSUE TITLE
Fitur: Sinkronkan biodata yg dikumpulkan di form penduduk dengan tabel tweb_penduduk

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#124]
Saat ini, ada kolom di tabel tweb_penduduk yang tidak ada tempat pengisian atau penyuntingannya, yaitu tidak muncul di form biodata penduduk. Seperti kolom:
- akta/tanggal perkawinan
- akta/tanggal perceraian
- sakit menahun

Perlu dicek semua kolom dan form isian, untuk men-sinkronkan. Juga perlu disinkronkan dengan surat keterangan biodata -- yang saat ini meminta pengguna untuk mengisi data yang sebagian besar ada di tabel tweb_penduduk.

**Comment by eddieridwan** [comment]
Kolom di tabel tweb_penduduk:

|kolom|form edit|rincian penduduk|
|------|---------|-----------|
|id| tidak-perlu|Y|
|nama|Y |Y|
|nik|Y|Y 
`id_kk`
`kk_level`
`id_rtm` 
`rtm_level`
`sex` 
`tempatlahir` 
`tanggallahir` 
`agama_id` 
`pendidikan_kk_id` 
`pendidikan_id` 
`pendidikan_sedang_id`
`pekerjaan_id` 
`status_kawin` 
`warganegara_id` 
`dokumen_pasport` 
`dokumen_kitas` 
`ayah_nik`
`ibu_nik` 
`nama_ayah` 
`nama_ibu`
`foto`
`golongan_darah_id`
`id_cluster`
`status` 
`alamat_sebelumnya`
`alamat_sekarang`
`status_dasar`
`hamil` 
`cacat_id`
`sakit_menahun_id` 
`akta_lahir` 
`akta_perkawinan` 
`tanggalperkawinan` 
`akta_perceraian`
`tanggalperceraian`
`cara_kb_id` 
`telepon`  
`tanggal_akhir_paspor`
`no_kk_sebelumnya`

**Comment by eddieridwan** [comment]
Pertanyaan:

1. Apakah ada yg menggunakan kolom pendidikan_id. Sebaiknya di hapus saja supaya tidak membingungkan. 'Pendidikan dalam KK' menggunakan kolom pendidikan_kk_id. 'Pendidikan Sedang Ditempuh' menggunakan kolom pendidikan_sedang_id.
2. Apakah kolom 'Sakit Menahun' (kolom sakit_menahun_id) ingin ditampilkan dan diedit? Kalau tidak diperlukan, sebaiknya dihapus.

**Comment by metalab25** [comment]
Sebaiknya kolom pendidikan_sedang_id dihapus karena itu akan terus berubah. Lebih baik gunakan Pendidikan Dalam KK

**Comment by r0edyhart0n0** [comment]
1. Setuju dihapus
2. Setuju dihapus
3. Attachment img

Untuk pendidikan_sedang_id masih dibutuhkan

Attachment:
https://user-images.githubusercontent.com/4936934/34664632-bd2299b8-f454-11e7-9a9e-518ad401052e.png

**Comment by MUHAMMADRANGSEL** [comment]
###Sebaiknya kolom pendidikan_sedang_id dihapus karena itu akan terus berubah## usul ini saya TDK setuju walaupun datanya  selalu berubah2 tetapi point ini saya penting sekali Krn pemerintah desa bisa mengecek dan melihat masyarakatnya yg sdg sekolah dan juga di profil desa ini ada

**Comment by MUHAMMADRANGSEL** [comment]
Point 1. Apakah ada yg menggunakan kolom pendidikan_id? Kalau tidak, sebaiknya di hapus saja supaya tidak membingungkan. 'Pendidikan dalam KK' menggunakan kolom pendidikan_kk_id. 'Pendidikan Sedang Ditempuh' menggunakan kolom pendidikan_sedang_id.
Yang dimaksud  kolom_id yg perlu dihapus Krn sdh menggunakan kolom_kk_id

**Comment by afri18** [comment]
bisa di tambahkan untuk berat_lahir, panjang_lahir, penolong_lahir, no_srt_ket_lahir > tujuan biar biodata penduduk nantinya akan lebih komplit, dan bisa d link langsung dengan permohonan akte

**Comment by MUHAMMADRANGSEL** [comment]
Sudah pas sesuai dengan tabel yg mas Eddie paparkan, kalaupun dimasukkan untuk khusus yg bayi dan balita ditambahkan berat lahir, panjang_lahir seperti yg diusulkan mas syafri

**Comment by eddieridwan** [comment]
Penambahan data kelahiran telah dipindahkan ke issue #746.

**Comment by eddieridwan** [comment]
Sdh dicommit ke master
