### ISSUE TITLE
[Bug] Plan > Garis > Lokasi garis salah

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#1245]
### Bagaimana alurnya sampai muncul masalah?
1. Buka _Plan > Garis > Lokasi garis (tombol di kolom _Aksi_)
2. Perhatikan tampilan dan fitur yg ada

### Seperti apa yang diharapkan?
Seharusnya membuka peta dengan fitur untuk menggambarkan garis.

### Apa yang terjadi?
Dialog tampilan kosong.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | v18.07
| Versi PHP        | 
| System operasi   |

**Comment by egodasa** [comment]
@eddieridwan Saat Saya menambahkan garis baru, terdapat input kategori. Kategori ini datangnya dari mana Mas? Saya lihat isi kategori garis tidak sama dengan tipe garis yang ada.

**Comment by egodasa** [comment]
@eddieridwan Bagaimana cara menampilkan garis di tampilan peta Mas? Apakah mengklik "properti desa"?

**Comment by eddieridwan** [comment]
Penamaan kategori/jenis memang agak rancu di Plan > Lokasi/Garis/Area. Dan sayangnya contoh data awal untuk Plan juga membingungkan. 

Saya sudah coba perbaiki peristilahnnya di branch master. 'Jenis' adalah istilah yg lebih umum (misalnya 'Jalan') --> lebih spesifik adalah 'Kategori' (misalnya, 'Jalan kampung').

Saya sudah pasang di http://beta.opensid.info. Silakan lihat.

**Comment by eddieridwan** [comment]
Mengenai menampilkan di peta, saya kira perlu ada pilihan tambahan. Mungkin anda bisa usulkan menu apa yg cocok untuk menampilkan fitur2 seperti jalanan, sungai atau fitur geografis berbentuk garis lainnya? Sepertinya idealnya menu rinci yang berisi pilihan jenis garis yg ada, seperti sungai, jalan, dsbnya.

**Comment by egodasa** [comment]
@eddieridwan Menurut Saya, kategori menampung nama dan jenis item di peta. seperti kategori jalan adalah garis, sawah adalah poligon, kantor,bidan dll adalah Marker. Tapi sepertinya kalau kategori seperti ini, mungkin menu plan bisa diringkas menjadi kategori saja. jadi tidak perlu bikin menu point, garis dll yang kurang dimengerti orang awam.

Kalau tetap dengan model lama, sebaiknya setiap point, line, poligon setidaknya mempunyai kategori. jadi di menu peta, kita tinggal menampilkan nama semua kategori saja Mas.

**Comment by eddieridwan** [comment]
Usul yang bagus. Silakan anda rancang. Kemudian bahas rancangan di forum FB untuk mendapatkan tanggapan pengguna (mungkin buat dokumen yg menjelaskan konsepnya). Sebaiknya jangan diterapkan sebelum disetujui pengguna. Mungkin lihat contoh dari aplikasi pemetaan desa lainnya.

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR #1636
