### ISSUE TITLE
Fitur: Sinkronkan surat keterangan biodata dengan data yang disimpan di tweb_penduduk

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#125]
Saat ini, surat keterangan biodata penduduk meminta pengguna mengisi biodata yang kebanyakan sudah ada kolomnya di tabel tweb_penduduk. 

Tinjau ulang -- sinkronkan -- kalau perlu tambah kolom lagi di tabel tweb_penduduk.

Juga sinkronkan dengan penampilan biodata penduduk, termasuk fitur cetak yang disediakan.

**Comment by MUHAMMADRANGSEL** [comment]
Dengan adanya perubahan di form isian maka sinkronisasi surat keterangan biodata dgn tweb_penduduk SDH bisa dilakukan

**Comment by eddieridwan** [comment]
Issue ini sudah lama dibuat. Sejak itu Surat Biodata Penduduk (F-1.01) telah diterapkan dan sekarang form isian surat tidak lagi perlu diisi dengan data penduduk. Semua data sudah diambil dari database.

Jadi issue ini bisa ditutup.
