### ISSUE TITLE
usul tombol aktif / tidak aktif diseragamkan?

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#1257]
### Bagaimana alurnya sampai muncul masalah?
menu tombol aktif tidak aktif dibeberapa menu memiliki perbedaan, menggunakan tombol dan ubah dulu dan simpan

### Seperti apa yang diharapkan?
apa perlu diseragamkan?

### Informasi tambahan 
contoh fungsi aktif tidak aktif yang berbeda cara penanganan
![2](https://user-images.githubusercontent.com/35319600/42433471-b39b9336-8379-11e8-8f7b-0f67eaf6b3be.jpg)

![1](https://user-images.githubusercontent.com/35319600/42433475-bbbea5a8-8379-11e8-8bc9-d2b35af1266f.jpg)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3138
