### ISSUE TITLE
Data Calon Pemilih harusnya TNI POLRI tidak ikut masuk

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#1258]
### Bagaimana alurnya sampai muncul masalah?
TNI POLRI untuk saat ini tidak memiliki hak pilih pada pemilihan umum, mungkin DPT bisa difilter dengan tambahan untuk tidak memasukkan anggota keluarga yang bekerja sebagai TNI POLRI

### Apa yang terjadi?
di Opensid untuk saat ini TNI Polri masih ikut termasuk dalam DPT

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
