### ISSUE TITLE
[Bug] Calon Pemilih >> pencarian Spesifik

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#1259]
### Bagaimana alurnya sampai muncul masalah?
buka menu calon pemilih > pencarian spesifik > isi rentan usia 17 - 17

### Seperti apa yang diharapkan?
menampilkan 17 tahun saja

### Apa yang terjadi?
Pencarian Spesifik rentan umur 17 - 17 menampilkan umur 18 tahun juga

### Informasi tambahan 
![1](https://user-images.githubusercontent.com/35319600/42487243-5559dd08-842a-11e8-8ae6-0189ac71e115.jpg)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by egodasa** [comment]
@eddieridwan Saya coba di demo dan di lokal bug ini tidak muncul Mas.

**Comment by eddieridwan** [comment]
@balongbesuk , harap tes di http://beta.opensid.info/. Tutup issue ini kalau sudah tidak bermasalah.

**Comment by balongbesuk** [comment]
Bugnya hilang Closed

**Comment by balongbesuk** [comment]
bug ini ternyata masih ada ketika saya cek data pada tanggal 19 - 04 -2019 pemilu tahun depan
sepertinya pencarian spesifik menjadi bingung mungkin dikarenakan masa 1 tahun berjalan?

![untitled12](https://user-images.githubusercontent.com/35319600/43790071-c6fb8ae2-9a9b-11e8-8070-1d54de53f562.jpg)

**Comment by egodasa** [comment]
@balongbesuk , @eddieridwan  Maaf Pak, pada saat kita memilih rentang umur 17 -17, hasil yang diinginkan bagaimana? Apakah menampilkan penduduk dengan umur 17-17 disaat sekarang atau menampilkan penduduk umur 17 -17 disaat 19 April 2019? 

Saya sudah cek programnya dan ternyata filter umur ini acuannya adalah umur sekarang, bukan umur penduduk pada saat tanggal 19 April 2019.

**Comment by balongbesuk** [comment]
ooo begitu jadi niat saya menggunakan fungsi tersebut adalah untuk melihat pemilih baru umur 17 tahun pada tanggal pemilihan, dikarenakan KPU meminta data pemilih baru untuk dapat dimasukkan DPT,

kalo memang begitu bug ini ditutup saja, sepertinya saya yang salah paham dengan hasil pencarian muncul umur 18 tahun itu, saya paham sekarang.

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR #1591
