### ISSUE TITLE
[Bug] Peta tidak muncul jika terdapat tanda kutip pada nama item peta

### ISSUE THREAD

**Issue by egodasa** [OpenSID/OpenSID#1261]
### Bagaimana alurnya sampai muncul masalah?
Klik menu plan -> tambah -> pada nama tempat, Saya memasukan nama asal-asalan dengan memasukan tanda kutip satu ' dan kutip dua " pada bagian nama tempat. Alhasil, pada saat membuka menu peta, peta tidak muncul. 

### Seperti apa yang diharapkan?
Peta muncul seperti biasa

### Apa yang terjadi?
Peta tidak muncul dengan error pada console

### Informasi tambahan 
Sepertinya diperlukan validasi data dengan melarang penggunaan tanda kutip pada nama tempat (menu plan) baik tipe poligon, marker dll. Kalau tidak salah bug ini mirip dengan issue #1037 

Percobaan dilakukan di web demo.
| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by egodasa** [comment]
Saya hanya melakukan test di web demo Mas.

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR #1576
