### ISSUE TITLE
[tampilan-admin] Menu plan tidak bisa diakses setelah memfilter item

### ISSUE THREAD

**Issue by egodasa** [OpenSID/OpenSID#1262]
### Bagaimana alurnya sampai muncul masalah?
Setelah Saya menemukan issue #1261 , Saya membukan menu plan dan memilih menu filter dibagian atas tabel. Dan saya memilih "SMA", kemudian menu plan memunculkan error "Unable to locate the specified class: Session.php" dan akhirnya menu plan tidak bisa dibuka sampai sekarang.

### Seperti apa yang diharapkan?
Menu plan bisa dibuka seperti biasa

### Apa yang terjadi?
Menu plan memunculkan error "Unable to locate the specified class: Session.php"

### Informasi tambahan 
Percobaan pada web demo
| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
@egodasa ini duplikat #1247 -- dan bug yg sudah ada sejak v18.07.
