### ISSUE TITLE
[tampilan-admin] Menu Bantuan, Error pada console saat mengganti banyak halaman

### ISSUE THREAD

**Issue by egodasa** [OpenSID/OpenSID#1263]
### Bagaimana alurnya sampai muncul masalah?
Klik menu bantuan, ganti banyak data yang ingin dimunculkan dari 20 ke 50 dst memunculkan pesan error pada console. Namun tidak berpengaruh terhadap kinerja halaman.
![error1](https://user-images.githubusercontent.com/9961837/42507496-952e52b6-846f-11e8-8492-42642a0116a9.jpg)

### Seperti apa yang diharapkan?
Error tidak muncul saat mengganti pilihan banyak data pada halaman

### Informasi tambahan 
Percobaan pada web demo
| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | tampilan-admin Tahap 4
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dikerjakan di PR #1279
