### ISSUE TITLE
Bug: Error Log di hosting

### ISSUE THREAD

**Issue by metalab25** [OpenSID/OpenSID#1265]
### Bagaimana alurnya sampai muncul masalah?
![screenshot_23](https://user-images.githubusercontent.com/19917739/42517097-85f93208-8491-11e8-8fd2-ff32fb321125.png)

### Seperti apa yang diharapkan?
Tidak ada lagi error

### Apa yang terjadi?
![screenshot_23](https://user-images.githubusercontent.com/19917739/42517097-85f93208-8491-11e8-8fd2-ff32fb321125.png)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 18.06
| Versi PHP        | PHP 5
| System operasi   |

**Comment by eddieridwan** [comment]
Kegiatan apa yg dilakukan, yaitu menu mana, tombol mana -- yang kira2 menghasilkan error ini? Apakah ada fungsi user yang terpengaruh?

Sangat sulit melacak masalah ini kalau tidak bisa direplikasi.

**Comment by eddieridwan** [comment]
Satu cara yg mungkin anda bisa coba: ganti script di file `index.php` seperti terlihat di gambar berikut. Perubahan ini akan menulis log file secara rinci untuk membantu melacak masalah. Kemudian coba replikasi kegiatan apa yg kira2 menyebabkan error tersebut -- lihat log file. Kalau error itu ditemukan di log file, silakan lampirkan seluruh log file tersebut di issue ini.

Sesudah itu kembalikan file `index.php` ke semula, supaya log file tidak membengkak.

<img width="1308" alt="log-rinci" src="https://user-images.githubusercontent.com/249563/42736686-8cdfd8fe-88ad-11e8-945a-4d1f44c0384f.png">

**Comment by pandigresik** [comment]
Sepertinya file2 dalam views/error/html adalah bukan file asli bawaan CI ( sudah ada perubahan ),
``<?php
	$ci = new CI_Controller();
	$ci =& get_instance();
	$ci->load->helper('url');
?>``
salah satu contoh pada file error_general terdapat code yang redundant, lebih baik code $ci = new CI_Controller() dihapus saja, karena untuk mendapatkan instance CI sudah disediakan melalui function get_instance

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
