### ISSUE TITLE
[tampilan-admin] Error pada console, menu persil. Mirip issue #1263

### ISSUE THREAD

**Issue by egodasa** [OpenSID/OpenSID#1266]
### Bagaimana alurnya sampai muncul masalah?
Masuk ke menu persil, pada bagian menu paginasi, saya mengganti banyak data perhalaman dari 50 ke 100 dst memunculkan error seperti pada gambar. Mirip issue #1263 
![error-persil](https://user-images.githubusercontent.com/9961837/42550712-85041f86-84fd-11e8-8176-21183d2d0b58.jpg)
Dan setelah kejadian diatas, Saya juga mengklik form input cari atau fokus ke form input cari. Dan error yang sama juga muncul kembali. Sepertinya setelah error pada paginasi juga menyebabkan error pada form pencarian.

Error tidak mempengaruhi kinerja halaman.

### Seperti apa yang diharapkan?
Tidak muncul error pada console

### Informasi tambahan 
Percobaan pada web demo
| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | tampilan-admin Tahap 4
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
@egodasa bisa bantu periksa kembali di http://demo-admin.opensid.info? Terima kasih.

**Comment by eddieridwan** [comment]
Sudah diperbaiki di PR #1279

**Comment by egodasa** [comment]
Maaf Mas @eddieridwan error masih muncul dibrowser. 
![persil](https://user-images.githubusercontent.com/9961837/42610769-31145402-85bd-11e8-806a-9e6e801c2b8b.jpg)
Dan selepas saya fokus kebagian "tampilkan", saya berpindah fokus ke kotak pencarian dan error yang sama juga muncul.
