### ISSUE TITLE
[tampilan-admin] Menu persil, kesalahan pada penulisan tombol "cetak"

### ISSUE THREAD

**Issue by egodasa** [OpenSID/OpenSID#1267]
### Bagaimana alurnya sampai muncul masalah?
Buka menu persil, lihat tombol cetak. Seharusnya tulisan tombol cetak adalah "Cetak", tapi kenyataannya malah tulisan "Catak".
![error-catak](https://user-images.githubusercontent.com/9961837/42550843-33c08082-84fe-11e8-86a1-23186181ea85.jpg)

### Informasi tambahan 
Percobaan pada web demo
| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | tampilan-admin Tahap 4
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah diperbaiki di PR #1279
