### ISSUE TITLE
[BUG] Report Bug pada widget/kategori Agenda

### ISSUE THREAD

**Issue by metalab25** [OpenSID/OpenSID#1277]
### Bagaimana alurnya sampai muncul masalah?
Menonaktifkan artikel/agenda pada kategori agenda desa

### Seperti apa yang diharapkan?
Artikel /Agenda yang dinonaktifkan seharusnya hilang dari widget Agenda Desa

### Apa yang terjadi?
Artikel/Agenda yang telah dinonaktifkan tetap tampil pada widged Agenda Desa
![bug_report](https://user-images.githubusercontent.com/19917739/42568644-693f56e2-8540-11e8-8c1d-252fc77d96ad.jpg)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x12
| Versi PHP        | PHP 5.6
| System operasi   | Hosting

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR #1596
