### ISSUE TITLE
Impor Datebase Daftar Program Bantuan 

### ISSUE THREAD

**Issue by arcom6456** [OpenSID/OpenSID#1278]
### Seperti apa yang diharapkan?
Dengan menyiapkan Format import datebase pada daftar Program Bantuan akan mempermudah admin mengolah data di Aplikasi, 

### Apa yang terjadi?
admin tidak akan mengentry data penduduk satu persatu di setiap Daftar Menu Program Bantuan 
![ice_screenshot_20180711-225432](https://user-images.githubusercontent.com/24196842/42580552-6a61f60c-855d-11e8-9145-3b0a59204a7b.jpeg)

### Informasi tambahan 
![ice_screenshot_20180711-224359](https://user-images.githubusercontent.com/24196842/42580170-89c6fa66-855c-11e8-8ee2-637cc655ae9e.jpeg)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by MUHAMMADRANGSEL** [comment]
Betul sekali pak arcom, supaya kita tinggal impor saja data sdh masuk kedalam aplikasi

**Comment by usupha** [comment]
ini adakah contoh berkas sumbernya? seperti BIP untuk data penduduk

**Comment by hasap86** [comment]
Sebetulnya cukup mengimport data NIK untuk bantuan Penduduk dan KK untuk bantuan keluarga, ditambah nomor kartu sementara itu yg penting dan wajib diisi ketika menambah peserta. Data lainnya otomatis terisi ambil dari database.

**Comment by hirudi** [comment]
Up.. semoga ada yang mengerjakan..

**Comment by aziz-opensidluwu** [comment]
Kami sangat memerlukan fitur import ini karena data desa kami sangat banyak penerima bantuan selama Covid-19 dalam bentuk excel office file. (Pemdes Komba Selatan,  Kec. Larompong - Kab. Luwu)

**Comment by eddieridwan** [comment]
@aziz-opensidluwu silakan lampirkan contoh file Excel yg diharapkan dapat di impor. Atau sekalian langsung saja usul format Excel yg diiginkan.

**Comment by aziz-opensidluwu** [comment]
> @aziz-opensidluwu silakan lampirkan contoh file Excel yg diharapkan dapat di impor. Atau sekalian langsung saja usul format Excel yg diiginkan.

Contoh data penerima bantuan :
[DATA PENERIMA BANTUAN BLT DD - Copy 1.xlsx](https://github.com/OpenSID/OpenSID/files/5581129/DATA.PENERIMA.BANTUAN.BLT.DD.-.Copy.1.xlsx)

Untuk data kartu peserta jk ada yg kosong bisa diambil dari pencarian data berdasarkan NIK yg terdaftar.

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3849
