### ISSUE TITLE
Tambahkan fitur rincian penduduk pada laporan bulanan perkembangan penduduk,

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#1285]
### Seperti apa yang diharapkan?
laporan penduduk bulanan dapat menampilkan rincian penduduk

### Apa yang terjadi?
untuk saat ini laporan penduduk bulanan hanya menampilkan jumlah

### Informasi tambahan 
![untitled1](https://user-images.githubusercontent.com/35319600/42720991-55d6b032-875c-11e8-8103-9b5fed0e7e9f.jpg)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by anamrifai** [comment]
Semoga ini cepat dikerjakan dan segera bisa dipakai buat laporan tiap bulan, karena sangat bermanfaat untuk laporan ke kabupaten

**Comment by uncu29** [comment]
untuk di kecamatan saya menggunakan laporan seperti ini
![Sistem Informasi Desa Desa Hibrida Jaya - Laporan Rt - Mozilla Firefox 13_07_2019 19 38 45](https://user-images.githubusercontent.com/51182125/61171779-7a81ec80-a5a6-11e9-8eb2-9b9f989f329c.png)

**Comment by balongbesuk** [comment]
Close issue pindah ke #2802
