### ISSUE TITLE
Mohon Arsip Layanan diberi filter dan laporan surat per kategori

### ISSUE THREAD

**Issue by hanamaze** [OpenSID/OpenSID#1287]
### Seperti apa yang diharapkan?
1. Ada filter Arsip Layanan misal berdasr tanggal, jenis dll
2. Ada kolom cari Arsip Layanan
3. Laporan surat sekaligus cetak dan eksport file berdasrkan jenis/tanggal/tahun dll

### Apa yang terjadi?

Menu di arsip layanan belum ada filter berdasrkan jenis surat , tanggal dll dan belum ada menu laporan surat misal per hari / per bulan dll
### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 18.07
| Versi PHP        | 5.6
| System operasi   | Windows 10 64bit

**Comment by ombimo** [comment]
saya ambil issue ini,
tp untuk yang no 3 saya masih belum paham maksudnya ? bisa dijelaskan lagi lebih lanjut ? @hanamaze

**Comment by eddieridwan** [comment]
@ombimo , terima kasih bung!  Saya kira maksudnya selain fitur Grafik Surat Keluar, juga bisa membuat laporan surat yg ada di Arsip Layanan hasil pilah/filter di point (1). Laporan itu seperti biasa bisa ditampilkan dan juga diunduh. 

Format laporan persisnya sebaiknya dikonsultasikan dengan pengguna di FB. Tapi mungkin buat draft dulu dan draft itu yg dibahas.

**Comment by eddieridwan** [comment]
Permintaan (1) dan (2) sudah dicommit ke master: Arsip Layanan sekarang dapat dicari berdasarkan nomor surat, nama pemohon dan nama penandatangan. Arsip Layanan dapat juga dipilih menurut tahun dan jenis surat.

Permintaan cetak/unduh laporan surat dibuatkan issue baru: #1801
