### ISSUE TITLE
[tampilan-admin] ubah tombol cancel menjadi tombol batal pada pengaturan RT

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#1288]
### Bagaimana alurnya sampai muncul masalah?
data penduduk >> wilayah administrasi >> rincian sub wilayah >> rincian sub wilayah rw >> tombol ubah

### Seperti apa yang diharapkan?
nama tombol cancel di ganti batal

### Informasi tambahan 
![untitled1](https://user-images.githubusercontent.com/35319600/42724615-a1fa4990-879f-11e8-8ebd-a5a2cfe059c5.jpg)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah diperiksa @egodasa . Sudah dikerjakan di PR #1395
