### ISSUE TITLE
[tampilan-admin]Fungsi ubah alamat penduduk dalam desa

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#1289]
### Bagaimana alurnya sampai muncul masalah?
Data Penduduk >> Keluarga >> Tekan tombol ubah Alamat 

### Seperti apa yang diharapkan?
1. Perbaiki tampilan Nik nama dan TTL kepala keluarga yang akan pindah 

2. Perbaiki tampilan pilihan RW dan RT

### Apa yang terjadi?
1. Nik nama dan TTL kepala keluarga yang akan pindah kosong

2. tampilan pilihan RW dan RT berdimpitan

### Informasi tambahan 
![untitled1](https://user-images.githubusercontent.com/35319600/42724783-adbed248-87a2-11e8-8dec-757572b81abf.jpg)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | tampilan-admin Tahap 5
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah diperiksa @egodasa . Sudah dikerjakan di PR #1395
