### ISSUE TITLE
[tampilan-admin]No KK tidak dapat ditekan

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#1290]
### Bagaimana alurnya sampai muncul masalah?
data penduduk >> keluarga 

### Seperti apa yang diharapkan?
pada opensid 18.07 ketika No KK ditekan akan menampilkan daftar Keluarga yang dipilih 

### Apa yang terjadi?
No KK pada menu keluarga tidak dapat ditekan

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah diperiksa @egodasa . Sudah dikerjakan di PR #1395
