### ISSUE TITLE
[tampilan-admin] tombol cetak pada salinan kartu keluarga menampilkan halaman kosong

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#1291]
### Bagaimana alurnya sampai muncul masalah?
data penduduk >> penduduk >> pilih no kk (sembarang) >> tekan tombol cetak

### Seperti apa yang diharapkan?
tombol cetak menampilkan cetak KK

### Apa yang terjadi?
untuk saat ini menampilkan halaman kosong

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by MUHAMMADRANGSEL** [comment]
![image](https://user-images.githubusercontent.com/25834335/42730941-4dd5f012-8835-11e8-99af-38c5daf18f6d.png)

**Comment by eddieridwan** [comment]
Sudah diperiksa @egodasa . Sudah dikerjakan di PR #1395
