### ISSUE TITLE
[tampilan-admin] Kesalahan penulisan pada biodata penduduk/

### ISSUE THREAD

**Issue by egodasa** [OpenSID/OpenSID#1292]
### Bagaimana alurnya sampai muncul masalah?
Klik menu penduduk -> klik pilih aksi -> klik biodata penduduk, terdapat penulisan yang salah atau kurang sesuai. 
![dempet](https://user-images.githubusercontent.com/9961837/42724925-727bff5a-87a5-11e8-90b3-814c535d2c32.jpg)

### Seperti apa yang diharapkan?
Tulisan biodata penduduk menggunakan spasi

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Duplikat #1298.
Saya tutup yg ini.
