### ISSUE TITLE
[tampilan-admin]Seragamkan tampilan subjudul ubah data penduduk

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#1293]
### Bagaimana alurnya sampai muncul masalah?
data penduduk >> penduduk >> ubah data penduduk

### Seperti apa yang diharapkan?
"background border judul" seragam secara global

### Apa yang terjadi?
ada 2 tampilan "background border judul"

### Informasi tambahan 
<img width="1265" alt="sub-judul-biodata" src="https://user-images.githubusercontent.com/249563/42740738-4dc8d56a-88e6-11e8-92ad-1d968d09fc34.png">
<img width="1265" alt="style-subjudul-list" src="https://user-images.githubusercontent.com/249563/42740751-653c8296-88e6-11e8-939d-4f3bdbd08228.png">

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | tampilan-admin Tahap 5
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
@balongbesuk: saya edit issue ini untuk menyeragamkan tampilan subjudul secara global

**Comment by eddieridwan** [comment]
Sudah diperiksa @egodasa . Sudah dikerjakan di PR #1395
