### ISSUE TITLE
[Bug][Inventaris] inventaris tidak dapat menyimpan data,

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#1294]
### Bagaimana alurnya sampai muncul masalah?
pada [tampilan-admin] sekretariat >> inventaris >> isi data
dan pada opensid 18.07 menu >> inventaris (diskominfo bandung)  >> tambah data

### Seperti apa yang diharapkan?
ketima menambahkan data inventaris data dapat tersimpan

### Apa yang terjadi?
ketu menambahkan data inventaris data tersebut tidak dapat tersimpan

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by balongbesuk** [comment]
bug ini ternyata ada di opensid 18.07

**Comment by eddieridwan** [comment]
@didikkurniawan dkk: apakah teman2 bisa mengerjakan issue ini? Terima kasih.

**Comment by eddieridwan** [comment]
Sudah ok di tampilan-admin.
