### ISSUE TITLE
[tampilan-admin]TTD Default sepertinya mengalami bug

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#1295]
### Bagaimana alurnya sampai muncul masalah?
sid home >> pemerintah desa >> ttd default

### Apa yang terjadi?
tombol cetak tidak menampilkan ttd default perangkat desa  di menu yang memiliki tombol cetak

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Saat ini baru digunakan di form _Cetak Surat > Cetak Surat_.
Saya sudah cek dan berfungsi ok. Saya akan tutup issue ini.
