### ISSUE TITLE
[tampilan-admin]menu sekretariat tidak mempunyai logo / icon

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#1296]
### Bagaimana alurnya sampai muncul masalah?
menu sekretariat tidak mempunyai logo / icon

### Seperti apa yang diharapkan?
memiliki logo / icon

### Apa yang terjadi?
saat ini menu sekretariat tidak memiliki logo / icon

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by balongbesuk** [comment]
logo iconnya tiba tiba muncul, issue ini saya close

**Comment by balongbesuk** [comment]
logo sekretariat hilang lagi, sepertinya ada yang salah pada script dalam, tolong di check, issuenya saya buka kembali

**Comment by eddieridwan** [comment]
Karena databasenya belum diupdate dari contoh data awal. Nanti dimasukkan ke Migrasi DB. Juga bisa edit di _Pengaturan > Modul_.
