### ISSUE TITLE
[tampilan-admin]Lokasi Tempat Tinggal Bug?

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#1297]
### Bagaimana alurnya sampai muncul masalah?
data penduduk >> penduduk >> cari lokasi tempat tinggal

### Seperti apa yang diharapkan?
peta berjalan lancar

### Apa yang terjadi?
di tempat saya saja tampilan peta terkadang bisa dan terkadang tidak,

mungkin teman teman yang lain yang mencoba fungsi ini dan berjalan lancar, issue ini bisa di tutup

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sepertinya masalah sinyal internet dan mapbox. Kami tutup issue ini.
