### ISSUE TITLE
[tampilan-admin]Lihat Detail biodata penduduk

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#1298]
### Bagaimana alurnya sampai muncul masalah?
data penduduk >> penduduk >> pilih aksi >> lihat detail biodata penduduk

### Seperti apa yang diharapkan?
1. judul biodatapenduduk kurang spasi "Biodata Penduduk" 
2. mungkin perpaduan warna biru merah bisa dirubah? 

### Informasi tambahan 
![untitled1](https://user-images.githubusercontent.com/35319600/42725456-c0502668-87ad-11e8-9e42-4cee1b1c18bb.jpg)

Seragamkan style subjudul dengan Persil. Buat class yang sama untuk jenis style ini supaya nanti mudah diubah di satu tempat secara global.
<img width="1265" alt="style-subjudul-list" src="https://user-images.githubusercontent.com/249563/42740579-3d2f8390-88e4-11e8-870a-05569cdf99f8.png">

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | tampilan-admin Tahap 5
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah diperiksa @egodasa . Sudah dikerjakan di PR #1395
