### ISSUE TITLE
[tampilan-admin]tampilan HP, tambah KK Baru

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#1299]
### Bagaimana alurnya sampai muncul masalah?
data penduduk >> keluarga >> tambah KK Baru

### Seperti apa yang diharapkan?
samakan tampilan pilihan dusun rw dan rt

### Apa yang terjadi?
untuk saat ini tampilan pilihan dusun tidak "sama" dengan tampilan rw rt

### Informasi tambahan 
![untitled1](https://user-images.githubusercontent.com/35319600/42725563-b5c372b6-87af-11e8-8973-049ceaeeb125.jpg)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah diperiksa @egodasa . Sudah dikerjakan di PR #1395
