### ISSUE TITLE
[tampilan-admin]ubah data KK belum tersentuh modernisasi

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#1302]
### Bagaimana alurnya sampai muncul masalah?
data penduduk >> keluarga >> ubah data 

### Seperti apa yang diharapkan?
modernisasi tampilan

### Apa yang terjadi?
untuk saat ini belum tersentuh modernisasi

### Informasi tambahan 
![untitled1](https://user-images.githubusercontent.com/35319600/42725734-29a64e44-87b3-11e8-847f-e31b8ba42f25.jpg)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah diperiksa @egodasa . Sudah dikerjakan di PR #1395
