### ISSUE TITLE
[tampilan-admin] masih ada kurung kurawal di view  di blok php-nya

### ISSUE THREAD

**Issue by suphm** [OpenSID/OpenSID#1303]
### Seperti apa yang diharapkan?
ikuti aturan syntax di view

### Apa yang terjadi?
masih ada kurung kurawal di blok php-nya juga belum mengganti echo ke ```<?=``` 
file: manajemen_kuisioner_form.php

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sepertinya tidak digunakan. Sudah ditambahkan ke issue https://github.com/OpenSID/OpenSID/issues/1254 untuk dihapus.
