### ISSUE TITLE
[tampilan-admin]ubah tombol cancel menjadi batal pada menu tambah RW

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#1304]
### Bagaimana alurnya sampai muncul masalah?
data penduduk >> wilayah administrasi >> tambah RW tombol "cancel"  ubah nama menjadi batal
juga data penduduk >> wilayah administrasi >> tambah RT tombol "cancel"  ubah nama menjadi batal

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dikerjakan di PR #1395
