### ISSUE TITLE
[tampilan-admin]hapus Logo "T" pesan konfirmasi penghapusan

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#1305]
### Bagaimana alurnya sampai muncul masalah?
tekan tombol hapus untuk munculkan pesan konfirmasi penghapusan

### Seperti apa yang diharapkan?
icon / Logo " T " pada pesan konfirmasi dihilangkan?

** Sebaiknya diganti dengan icon yang lebih cocok, dan dilakukan secara global.

### Informasi tambahan 
![untitled1](https://user-images.githubusercontent.com/35319600/42725990-72e30bb6-87b7-11e8-8ecf-27b529e03240.jpg)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Comment dari @fitamrin : Issue #1305 pada poin yang berkaitan dengan menghapus/mengganti icon T di semua header modal tidak dapat dilakukan, karena banyak merubah/menghapus di setiap tempat. mengapa tidak di issuekan sejak awal.

**Comment by eddieridwan** [comment]
Bisa dikerjakan sebagai bagian dari pemeriksaan akhir. Sepertinya bisa diubah menggunakan global replace.

**Comment by eddieridwan** [comment]
Sudah dikerjakan di PR #1533
