### ISSUE TITLE
[tampilan-admin] bug: label menu  SID berubah jadi Inventaris 

### ISSUE THREAD

**Issue by suphm** [OpenSID/OpenSID#1306]
### Bagaimana alurnya sampai muncul masalah?
lakukan migrasi ke >=18.07

### Apa yang terjadi?
Di sidebar, labelnya: Home > Inventaris 

### Seperti apa yang diharapkan?
Di sidebar, labelnya: Home > SID

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by balongbesuk** [comment]
nah ini yang dari tadi saya bingung, submenu pada menu Home berubah ubah,
logo sekretariat dari ada tiba tiba hilang lagi, tadi juga sempet ada menu surat keluar pada menu sekretariat,

wkwkwk

**Comment by eddieridwan** [comment]
Karena database belum diupdate dari contoh data awal. Nanti dimasukkan ke Migrasi DB (sekarang belum). Juga bisa diedit di _Pengaturan > Modul_.

Saya tutup issue ini.
