### ISSUE TITLE
Sub menu inventaris perlu di-Indonesia-kan

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#1307]
### Bagaimana alurnya sampai muncul masalah?
1. 2. Sekretariat >> inventaris >> mutasi inventaris (cek kembali)
2. Sekretariat >> inventaris >> kategori inventaris (cek kembali)

### Seperti apa yang diharapkan?
1. pergunakan bahasa baku indonesia
2. beberapa submenu tampilan responsive

### Apa yang terjadi?
1. beberapa menu masih berbahasa inggris
2. beberapa submenu sepertinya tidak tersentuh modernisasi

### Informasi tambahan 
![untitled1](https://user-images.githubusercontent.com/35319600/42729797-1c069a0e-880e-11e8-80a0-a9c5337ad075.jpg)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | tampilan-admin Tahap 5
| Versi PHP        | 
| System operasi   |

**Comment by agungsugiarto** [comment]
Saya sudah mengerjakan issues #1307, apakah boleh saya boleh melakukan pull requests ?

**Comment by balongbesuk** [comment]
tampilan katogori inventaris > konstruksi dan pengerjaan masih belum benar

**Comment by eddieridwan** [comment]
Dari @fitamrin: "ssue #1307 pada point merubah bahasa inggris ke indonesia, masalah memang sudah ada dimaster 18.07 (silakan lihat). Dan masalah issue seperti ini tidak termasuk bagian kerja di projek ini (lihat SPK)."

**Comment by eddieridwan** [comment]
Ya, memang belum di-Indonesia-kan di v18.07. Issue ini diubah menjadi issue biasa.

**Comment by eddieridwan** [comment]
@didikkurniawan dkk: apakah teman2 bisa mengerjakan issue ini? Terima kasih.

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR #2012
