### ISSUE TITLE
[tampilan-admin]filter aktif/tidak aktif pada menu SK Kades bermasalah

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#1309]
### Bagaimana alurnya sampai muncul masalah?
buka sekretariat > SK Kades > check fungsi filter / tidak altif

### Seperti apa yang diharapkan?
fungsinya menjadi benar

### Apa yang terjadi?
untuk saat ini ketika fungsi filter aktif / tidak aktif dipilih fungsi tersebut melompat menampilkan menu pada (admin web > dokumen)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah diperiksa @egodasa . Sudah dikerjakan di PR #1395
