### ISSUE TITLE
[tampilan-admin]tambah surat masuk tersimpan tetapi tidak tampil

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#1310]
### Bagaimana alurnya sampai muncul masalah?
sekretariat > surat masuk > tambah surat baru

### Apa yang terjadi?
ketika tambah surat baru data berhasil disimpan tetapi tidak muncul pada tabel

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dicek, dan sepertinya tidak bermasalah. Saya akan tutup. Bisa dibuka lagi kalau nanti bermasalah lagi
