### ISSUE TITLE
[tampilan-admin]tampilan tambah analisis baru perlu diseragamkan

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#1311]
### Bagaimana alurnya sampai muncul masalah?
pilih menu analisis > tambah analisis baru

### Seperti apa yang diharapkan?
tampilannya bisa seragam

### Apa yang terjadi?
untuk saat ini ada yang menjorok ke kiri, dan ada yang melebar

### Informasi tambahan 
![untitled1](https://user-images.githubusercontent.com/35319600/42730001-5d32e1d0-8814-11e8-83d4-e8092783f81a.jpg)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah diperiksa @egodasa . Sudah dikerjakan di PR #1395

**Comment by eddieridwan** [comment]
Comment dari @fitamrin : Issue #1311, pada poin yang berkaitan semua field isian sama panjang, saya abaikan karena kelihatan kurang sesuai.
