### ISSUE TITLE
Nomor Urut Sekretariat > Surat Masuk perlu dibuat otomatis

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#1312]
### Bagaimana alurnya sampai muncul masalah?

Menu Sekretariat ==>Surat Masuk ==>Tambah Surat Masuk
![screenshot 2018-07-15 13 03 20](https://user-images.githubusercontent.com/25834335/42730784-15f05dfe-8830-11e8-8ac1-7a956a95d9af.png)

### Seperti apa yang diharapkan?
Supaya Nomor Urut tidak duplicate 

### Apa yang terjadi?
Nomor Urut masih bisa dengan nomor yang sama

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | v18.07
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Masalah ini sudah ada di v18.07.

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR #1764
