### ISSUE TITLE
[tampilan admin] perlu ditambahkan kata masuk

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#1314]
### Bagaimana alurnya sampai muncul masalah?
Menu Sekretariat ==> Surat Masuk ==> **Tambah Surat Baru** 
![surat masuk](https://user-images.githubusercontent.com/25834335/42730819-c39c60f0-8831-11e8-9c2e-542e6a93e32d.png)

### Seperti apa yang diharapkan?
 **Tambah Surat Baru** perlu dirubah menjadi **Tambah Surat Masuk Baru** 

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dikerjakan di PR #1395
