### ISSUE TITLE
[tampilan admin]  Seragamkan kalimat pada menu SK Kades

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#1315]
### Bagaimana alurnya sampai muncul masalah?
Di Sub Menu SK kades perlu disamakan
![sk kades](https://user-images.githubusercontent.com/25834335/42730842-e984d102-8832-11e8-8708-a12c47bc37c9.png)

### Seperti apa yang diharapkan?
1. Hilangkan kata **"Pengaturan Dokumen"**
2. **SK Kepala Desa** di ganti menjadi **SK Kades**
3. **Tambah Dokumen baru** di ubah menjadi **Tambah SK Kades Baru**

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah diperiksa @egodasa . Sudah dikerjakan di PR #1395
