### ISSUE TITLE
[tampilan admin] Seragamkan kalimat pada menu Perdes

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#1316]
### Bagaimana alurnya sampai muncul masalah?
![perdes](https://user-images.githubusercontent.com/25834335/42730865-9aa2c8cc-8833-11e8-81d9-74a15a50a229.png)

### Seperti apa yang diharapkan?
1. Hilangkan kata "Pengaturan Dokumen"
2. Peraturan Desa di ganti menjadi Perdes
3. Tambah Dokumen baru di ubah menjadi Tambah Perdes Baru

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah diperiksa @egodasa . Sudah dikerjakan di PR #1395
