### ISSUE TITLE
[tampilan-admin] Form Biodata Penduduk di Pilih Status Kehamilan masih salah

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#1317]
### Bagaimana alurnya sampai muncul masalah?
pada waktu Tambah Anggota Keluarga  di Form Isian di Pilih Status kehamilan masih salah yang muncul Pilih Jenis Kelamin
![form biodata](https://user-images.githubusercontent.com/25834335/42731012-e12d1678-8836-11e8-856d-52075429974f.png)

### Seperti apa yang diharapkan?
**Pilih Jenis Kelamin** di ganti menjadi **Pilih Status kehamilan** 

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dikerjakan di PR #1395
