### ISSUE TITLE
Di Form Isian Perlu ditambahkan Form Baru Lagi

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#1319]
### Bagaimana alurnya sampai muncul masalah?
DI Form Isian Penduduk di Data Status Perkawinan Perlu di Tambahkan Form Baru lagi
Bila Perlu dibuatkan secara otomatis
A. Jika Status Perkawinannya KAWIN maka Form Kepemilikan Buku Nikah secara otomatis harus diisi 
    dengan ada pilihan Ada atau Tidak Ada
B. Begitu juga jika status Kawinnya CERAI maka Form Kepemilikan Akta Perceraian Harus diisi dengan 
    Pilihan Ada atau Tidak Ada
Catatan : 1. Apabila Pilihan Pada Kepemilikan Buku Nikah  **Ada** maka Form No. Akta Nikah (Buku 
                   Nikah)/Perkwainan **Wajib diisi**
               2. Apabila Pilihan Kepemilikan Akta Cerai **Ada** Maka Form No. Akta Perceraian **Wajib 
                   diisi**

1. Form Kepemilikan Buku Nikah jika Status Perkawinannya KAWIN 
    Pilihannya : 1. Ada
                       2. Tidak Ada
2. Form Kepemilikan Akte Perceraian  jika Status Perkawinannya Cerai Hidup
    Pilihannya : 1. Ada
                       2. Tidak Ada

![form baru](https://user-images.githubusercontent.com/25834335/42731165-25d3bfe0-883a-11e8-99e9-008ab82bf283.png)

Ini semua saya usulkan mengingat di Form Data SIAK Kabupaten Form tersebut ada
### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Mengapa perlu ditambah kolom terpisah?

Dengan adanya status kawin baru: KAWIN TERCATAT dan KAWIN TIDAK TERCATAT sepertinya sudah jelas:

1. KAWIN TERCATAT, berarti ada akta nikahnya. Kalau kolom AKTA NIKAH masih kosong, maka perangkat desa perlu mendapatkan nomor akta nikahnya untuk direkam.
2. KAWIN TIDAK TERCATAT, berarti tidak ada akta nikah, dan kolom AKTA NIKAH tidak perlu diisi.
