### ISSUE TITLE
[BUG] Berkas Scan Surat Masuk, hilang ketika dilakukan perubahan

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#1322]
### Bagaimana alurnya sampai muncul masalah?
Sekretariat > surat masuk > ubah data > simpan

### Seperti apa yang diharapkan?
berkas scan surat tetap tersimpan

### Apa yang terjadi?
Berkas Scan Surat Masuk, hilang ketika dilakukan perubahan/ataupun tidak dilakukan perubahan, setelah mengklik tombol simpan

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by balongbesuk** [comment]
bug ini ternyata ada di opensid 18.07

**Comment by eddieridwan** [comment]
Dari @fitamrin: "Issue #1322 pada point data upload hilang setelah klik tombol simpan, masalah ini memang sudah ada di Master 18.07."

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
