### ISSUE TITLE
Bug Sekretariat > SK Kades  (Contoh data tidak dapat diunduh)

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#1323]
### Bagaimana alurnya sampai muncul masalah?
buka Sekretariat > SK Kades 

### Seperti apa yang diharapkan?
berkas SK Kades Dapat Diunduh

### Apa yang terjadi?
untuk saat ini ketika mengunduh berkas SK Kades, hanya menampilkan Blank Kosong ( Mungkin contoh datanya yang tidak menyertakan file yang dimaksud? )

### Informasi tambahan 
tetapi ketika saya mencoba membuat SK Kades Sendiri, dan file perkas SK kades dapat diunduh

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sepertinya disebabkan sk kades ada di database, tapi berkasnya sendiri tidak ikut diunggah di demo. Saya akan tutup issue ini, karena sepertinya bukan bug.
