### ISSUE TITLE
[tampilan-admin]Fungsi Tombol Cari penduduk dan keluarga

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#1324]
### Bagaimana alurnya sampai muncul masalah?
Data Penduduk >> penduduk / keluarga >> masuk ke fungsi cari

### Seperti apa yang diharapkan?
fungsi cari seperti opensid 18.07 yang menampilkan nama penduduk yang memiliki "kemiripan" ikut muncul

** Autocomplete (drop down) menampilkan nama penduduk yg mirip dengan karakter yg dicari

### Apa yang terjadi?
fungsi cari pada modernisasi opensid sedikit berbeda dengan opensid 18.07

** Autocomplete menampilkan kata2 yg dicari sebelumnya.
<img width="1337" alt="autocomplete-penduduk" src="https://user-images.githubusercontent.com/249563/42740182-89feebda-88de-11e8-8b08-e130b38bfa20.png">

### Informasi tambahan 

pencarian versi opensid 18.07 seperti gambar
![untitled1](https://user-images.githubusercontent.com/35319600/42733238-0958bee2-8858-11e8-92ef-f4e8ecfad551.jpg)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dikerjakan di PR #1395
