### ISSUE TITLE
Tampilan Photo perlu disesuaikan

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#1325]
### Bagaimana alurnya sampai muncul masalah?
1. Ketika upload photo di Biodata Poto yang tampil perlu disesuaikan lagi terutama **Tinggi**
![biodata1](https://user-images.githubusercontent.com/25834335/42733661-0f3053f6-8868-11e8-942b-4c356a7c828b.png)
2. Ketika Cetak Biodata Photo yang tampil juga perlu disesuaikan terutama **tingginya**
![biodata2](https://user-images.githubusercontent.com/25834335/42733666-2e31cdac-8868-11e8-859a-fb9eb002bf47.png)

### Seperti apa yang diharapkan?
Supaya Poto yang tampil setengah badan seperti SUKET yang dari DUKCAPIL
![h4mq4au5bxce3t7xsk87xw0f](https://user-images.githubusercontent.com/25834335/42733675-4abb4e3a-8868-11e8-8fe2-ef63a5fb7891.jpg)

atau seperti hasil Upload Poto yang ada di Menu Pengguna
![image](https://user-images.githubusercontent.com/25834335/42733800-b94f2c84-886a-11e8-9f88-ef4147e9bf42.png)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Masalah ini sudah ada di v18.07.

**Comment by eddieridwan** [comment]
@MUHAMMADRANGSEL , apakah issue ini sudah bisa ditutup?

**Comment by MUHAMMADRANGSEL** [comment]
Bisa saya saja yg tutup bung
