### ISSUE TITLE
[Bug] Statistik Kepemilikan KTP

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#1353]
### Bagaimana alurnya sampai muncul masalah?
Buka Menu Statistik ==>Kepemilikan KTP jumlah Belum Mengisi 6 setelah di Klik Tampilan Kosong
![kepemilkan ktp](https://user-images.githubusercontent.com/25834335/42800980-6a639396-89d0-11e8-8ef3-090d90d4c330.png)
![ktp](https://user-images.githubusercontent.com/25834335/42800992-73110a96-89d0-11e8-971e-d742baa1988c.png)

### Seperti apa yang diharapkan?
Supaya apa yang ditampilkan sesuai 

### Apa yang terjadi?
Membingungkan data siapa yang belum mengisi

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by metalab25** [comment]
Ini berkaitan dengan error pada Penduduk_model.php cuma saya tidak ada tanggapan dari pihak pengembang

**Comment by eddieridwan** [comment]
@MUHAMMADRANGSEL  saya tidak bisa replikasi error ini. Apakah anda bisa coba ulangi di http://demo.opensid.info/? Beritahu di sini kalau error itu juga ditemukan di situs demo.

**Comment by MUHAMMADRANGSEL** [comment]
Permaslahan ini sudah ditemukan solusinya 
1. Penduduk yang sebelumnya berumur dibawah 17 tahun 
    Wajib KTP      = belum
    KTP el             = belum
    Status Rekam = belum wajib
    maka ketika sudah berumur 17 keatas atau status Wajib KTP berubah secara otomatis berubah 
    menjadi wajib sedangkan 
    KTP el             = belum ==> tidak berubah
    Status Rekam = belum wajib ==> tidak berubah
    dengan demikian maka akan muncul maslah seperti diatas
2 . Solusinya adalah
    Wajib KTP      = Wajib ==> berubah secara otomatis
    KTP el             = belum
    Status Rekam = belum wajib dirubah menjadi belum rekam atau yang lainnya

SEKIAN penjelasan tentang solusi maslah diatas

**Comment by eddieridwan** [comment]
@MUHAMMADRANGSEL Kalau issuenya berubah dan perlu dilakukan, jangan lupa membuka kembali.

**Comment by MUHAMMADRANGSEL** [comment]
Siap bung eddie

Pada tanggal Sen, 17 Sep 2018 08.37, Eddie Ridwan <notifications@github.com>
menulis:

**Comment by eddieridwan** [comment]
@MUHAMMADRANGSEL sepertinya solusi anda perlu penjelasan tambahan; yaitu solusi mengubah status _KTP el_ dan _Status Rekam_ secara otomatis hanya dapat dilakukan kalau kedua kolom tersebut sudah ada isinya -- sesuai dengan keterangan yg anda berikan.

Tapi kalau ada warga yg kolom _KTP el_ dan _Status Rekam_ masih kosong, maka walaupun umurnya sudah Wajib KTP, kolom _KTP el_ dan _Status Rekam_ seharusnya tidak diubah secara otomatis. Data di kedua kolom itu diperoleh dari Disdukcapil. Jika kedua kolom ini kosong artinya warga tersebut belum terdaftar di Disdukcapil. Jadi kalau diisi secara otomatis, informasi ini akan hilang.

Betul?

**Comment by eddieridwan** [comment]
@MUHAMMADRANGSEL -- apakah mengisi kedua kolom tersebut akan nantinya menyebabkan ketidak-cocokan dengan data di Disdukcapil? Bukankah data di kedua kolom tersebut data yg dikelola oleh Disdukcapil? Kalau diubah secara otomatis di OpenSID tidakkah akan bisa menjadi berbeda dgn data Disdukcapil?

**Comment by MUHAMMADRANGSEL** [comment]
Maksud saya begini bung Eddie,  ketika misalkan kita sdh mendapatkan data
dari dinas dukcapil dan desa melakukan update data yang dimana penduduk
yang pada waktu update data penduduk tersebut belum umur 17 tahun
Wajib KTP:  belum wajib
Status KTP:  belum
Status rekam:  belum wajib
Beberapa bulan kemudian penduduk tersebut berumur genap 17
Maka di wajib KTP secara otomatis terisi wajib
Status KTP:  belum
Status rekam:  belum wajib dirubah menjadi belum rekam/ sudah rekam sesuai
dengan laporan yg diperoleh dari penduduk yg bersangkutan


Pada tanggal Sen, 17 Sep 2018 18.59, Eddie Ridwan <notifications@github.com>
menulis:

**Comment by MUHAMMADRANGSEL** [comment]
Ya betul bung

Pada tanggal Sen, 17 Sep 2018 18.30, Eddie Ridwan <notifications@github.com>
menulis:

**Comment by MUHAMMADRANGSEL** [comment]
Ya memang sesuai dengan data dukcapil

Pada tanggal Sen, 17 Sep 2018 18.59, Eddie Ridwan <notifications@github.com>
menulis:

**Comment by MUHAMMADRANGSEL** [comment]
Memang sebenarnya harus dikosongkan di Kolom KTP El dan Status Rekam bagi penduduk yang usianya belum 17 tahun,  hanya saja kemarin kami lakukan update dengan mengisi kolom KTP el dan status rekam bagi yang belum usia 17 tahun

**Comment by MUHAMMADRANGSEL** [comment]
Ya bung Eddie perlu dimasukkan di panduan siapa tau nanti apa desa yang mengalami masalah seperti diatas

**Comment by eddieridwan** [comment]
Ok, sudah ditambahkan sementara di https://github.com/OpenSID/OpenSID/wiki/Pengisian-Data-Penduduk.

Tetapi seperti anda ketahui, seluruh panduan perlu diperbaharui.

Issue ini akan kami tutup.
