### ISSUE TITLE
[Bug] Cari periode analisis tidak berfungsi

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#1381]
### Bagaimana alurnya sampai muncul masalah?
1. Buka _Analisis > Rincian Analisis > Periode Sensus/Survei_
2. Perhatikan tampilan dan coba fitur

### Seperti apa yang diharapkan?
Masalah di gambar berikut telah diperbaiki
<img width="1374" alt="cari-periode-analisis" src="https://user-images.githubusercontent.com/249563/42856235-3ed9a33c-8a7f-11e8-98f6-03a663f32698.png">

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | v18.07
| Versi PHP        | 
| System operasi   |

**Comment by agungsugiarto** [comment]
bug berada pada query, akan segera saya kirimkan pull request 

![commit](https://user-images.githubusercontent.com/10989147/43754540-945a44ae-9a35-11e8-9040-48ec8af3caf1.png)

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR #1559
