### ISSUE TITLE
[tampilan admin] Seragamkan icon unduh 

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#1394]
### Bagaimana alurnya sampai muncul masalah?
Sekretariat > Surat Masuk Icon Unduh masih salah
![unduh](https://user-images.githubusercontent.com/25834335/42924011-f5ffa512-8b5a-11e8-9dd3-30cf64a94a81.png)

### Seperti apa yang diharapkan?
Iconnya diseragamkan dengn yang lain

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dikerjakan di PR #1395
