### ISSUE TITLE
Fitur: Tambahkan formulir permohonan KTP dan KK sesuai Permendagri 19 tahun 2010

### ISSUE THREAD

**Issue by SetiawanRidwan** [OpenSID/OpenSID#141]
sebenarnya saya juga sedang membuat formulir-formulir ini, hanya saja sedang keterbatasan waktu jadi belum tergarap. semoga ada pengoprek yang juga membutuhkan dan membuatkannya

**Comment by mizwaruddin** [comment]
@afa28 formulir KK sdh ada di master. Sedangkan formulir permohonan KTP sdg tidak dibutuhkan,
