### ISSUE TITLE
[Bug] Tombol Paginasi? Admin Web Tidak tampil dengan benar

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#1411]
### Bagaimana alurnya sampai muncul masalah?
Admin Web > Artikel

### Seperti apa yang diharapkan?
Fungsi Paginasi tertampil dengan benar

### Apa yang terjadi?
saat ini menu paginasi pada admin web > artikel hanya memunculkan kotak kecil

### Informasi tambahan 
![untitled1](https://user-images.githubusercontent.com/35319600/43072965-150a3522-8ea2-11e8-9b85-b64c20e05475.jpg)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by egodasa** [comment]
@eddieridwan Apakah bug ini masih akan dikerjakan Mas? Karena sudah ada proyek memodernkan tampilan admin.

**Comment by eddieridwan** [comment]
@egodasa: masih. Tapi tunggu saya gabung dulu pekerjaan tampilan-admin ke branch _master_. Yaitu langsung kerjakan tampilan baru.

**Comment by eddieridwan** [comment]
@egodasa , saya sudah gabungkan pekerjaan _tampilan-admin_ ke branch _master_. Jadi silakan kalau mau kerjakan.

**Comment by egodasa** [comment]
@eddieridwan Saya menemukan kejanggalan dengan method xss_clean bawaan CI Mas. xss_clean tidak berjalan dengan baik jika data yang diterima adalah object. Jika data yang diterima array, maka tidak ada masalah.
Seperti yang dapat dilihat di https://github.com/OpenSID/OpenSID/blob/master/donjo-app/controllers/Web.php#L74 , `$data` diproses oleh xss_clean. Tapi didalam `$data['paging']`, ternya

**Comment by eddieridwan** [comment]
@egodasa mungkin cari solusi di mana xss_clean dilakukan secara selektif. Misalanya, pindahkan baris `$data['paging']  = $this->web_artikel_model->paging($cat,$p,$o);` sesudah baris xss_clean, sehingga `$data['paging'] ` tidak terpengaruh.

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR #1561
