### ISSUE TITLE
[tampilan-admin]Tabel penduduk Tidak tampil dengan benar

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#1414]
### Bagaimana alurnya sampai muncul masalah?
Buka Data Penduduk > penduduk

### Seperti apa yang diharapkan?
tabel tertampil dengan benar

### Apa yang terjadi?
untuk saat ini ketika menu opensid muncul > tabel tampil tidak benar

### Informasi tambahan 
![untitled1](https://user-images.githubusercontent.com/35319600/43074581-0177d7b6-8ea8-11e8-93c4-07a9ce3b7b58.jpg)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by balongbesuk** [comment]
sepertinya bug ini muncul di layar monitor widescreen 21:9, (2560x1080)

berikut saya sertakan Video tangkapan pada layar 
https://drive.google.com/file/d/1y_63Hnen13VR2Po1-fOhIa2NaPtZ33lQ/view

**Comment by eddieridwan** [comment]
Sudah diperiksa @egodasa. Sudah ok di PR #1422

**Comment by balongbesuk** [comment]
kemarin sempat saya baca dari pull komentar kontraktor, dan akhirnya saya coba banding kan dengan komputer non layar lebar dirumah ternyata memang tidak ada masalah, masalah tersebut muncul ketika saya coba di monitor layar lebar, yang saya sertakan video tampilan ketika menggunakan monitor layar lebar tersebut diatas,

nanti saya coba lagi,

**Comment by balongbesuk** [comment]
sudah saya coba pada layar lebar, aman #closed
