### ISSUE TITLE
[tampilan admin] Nama Desa dengan kecamatan perlu dirapatkan

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#1416]
### Bagaimana alurnya sampai muncul masalah?
Nama Desa dengan nama Kecamatan perlu masih ada jarak
![nama desa](https://user-images.githubusercontent.com/25834335/43076511-06557ac2-8eb7-11e8-8f53-f5dc53b12679.png)

### Seperti apa yang diharapkan?
Nama Desa dengan nama kecamatan tidak usah ada jarak

### Apa yang terjadi?
Tampilan kurang enak dilihat

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah diperiksa @egodasa. Sudah ok di PR #1422
