### ISSUE TITLE
Di Form Isian Penduduk Kata Kg di ganti Gram

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#1417]
### Bagaimana alurnya sampai muncul masalah?
di Form isian Penduduk pada Form Berat Lahir Keterangan Kg diganti Gram 
![form penduduk](https://user-images.githubusercontent.com/25834335/43076893-4a38a1fa-8eb8-11e8-8f01-f11673697399.png)

### Seperti apa yang diharapkan?
Kata Kg diganti Gram sesuai dengan Surat Keterangan Lahir yang ada di Buku Posyandu dari Bidan

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Ini sudah ada di v18.07, jadi bukan issue tampilan-admin, melainkan issue biasa.

**Comment by MUHAMMADRANGSEL** [comment]
untuk issue ini sudah kami coba selesaikan sehingga dengan itu kami lampirkan perubahan scripnya : 
[penduduk_form_isian.zip](https://github.com/OpenSID/OpenSID/files/2222674/penduduk_form_isian.zip)

**Comment by eddieridwan** [comment]
Data berat_lahir yg sudah tersimpan perlu juga dikonversi dari kg menjadi gram.

Sudah dicommit ke master melalui PR #2014
