### ISSUE TITLE
Kode isian surat untuk bulan dalam angka Romawi

### ISSUE THREAD

**Issue by djowah** [OpenSID/OpenSID#1418]
Bisakah fitur nomor surat ditambah bulan dalam angka ROMAWI sebelum Tahun?
![screenshot_15](https://user-images.githubusercontent.com/36688215/43113327-272524d8-8f24-11e8-8c77-05d953f191b1.png)

**Comment by balongbesuk** [comment]
bisa, lanjut di grup facebook Opensid nanti saya jawab disana https://www.facebook.com/groups/OpenSID/

**Comment by eddieridwan** [comment]
@djowah apakah fitur ini masih dibutuhkan?

**Comment by MUHAMMADRANGSEL** [comment]
Masih bung

**Comment by suphm** [comment]
untuk penomoran surat ini bisa dengan isian berupa format/string interpolation. terinspirasi fungsi php printf()/sprintf('%s %u ...'), date('Y-m-d'), juga variabel di pemerograman misalnya dengan mengisikan ```Nomor: {nomor}/{bulan}/{tahun}```

**Comment by eddieridwan** [comment]
Terapkan sebagai kode isian yang dimasukkan ke dalam template _rtf_. Untuk penjelasan kode isian bisa dilihat di https://github.com/OpenSID/OpenSID/wiki/Kode-Isian-Template-Surat.

Jadi sediakan kode isian [bulan-romawi] yang akan digantikan dengan tulisan bulan dalam angka Romawi.

Penggantian kode isian yang bersifat umum dilakukan di method `surat_rtf()`.

Algoritma menulis bulan dalam angka Romawi sebaiknya diletakkan di dalam helper `opensid_helper.php`.

**Comment by hansahdarmawan** [comment]
Apakah issue tersebut diharapkan agar penomoran sesuai bulan dan tahun secara automatis berdasarkan pembuatan surat???  Jd aparatur desa tidak dapat membuat surat berdasarkan waktu tertentu.

**Comment by eddieridwan** [comment]
Kalau sudah ada method `bulan_romawi($bulan)` di `opensid_helper.php`, maka di method `surat_rtf()` di `Surat_model.php` anda tinggal sisipkan satu baris saja di bagian Data Surat, seperti terlihat di contoh bawah:

```
//DATA SURAT
$array_replace = array(
	"[kode_surat]" => "$surat[kode_surat]",
	"[judul_surat]" => strtoupper("surat ".$surat['nama']),
	"[tgl_surat]" => "$tgl",
	"[tahun]" => "$thn",
        "[bulan_romawi]" => bulan_romawi(date("m"))
);
```

Dengan cara ini, algoritma `bulan_romawi()` dapat digunakan di tempat lain, dan tidak akan membuat method `surat_rtf()` lebih rumit lagi.

**Comment by eddieridwan** [comment]
Di template surat `.rtf`, pengguna tinggal memasukkan kode isian `[bulan_romawi]` di setiap tempat di mana ingin ditampilkan bulan menggunakan angka Romawi.

**Comment by MUHAMMADRANGSEL** [comment]
Top

Pada tanggal Rab, 3 Okt 2018 12.49, Eddie Ridwan <notifications@github.com>
menulis:

**Comment by hansahdarmawan** [comment]
oke baik untuk helpernya akan saya perbaiki dan saya pull request kembali,,,

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
