### ISSUE TITLE
Nama, nik, alamat tidak muncul pada lampiran surat ket kelahiran

### ISSUE THREAD

**Issue by makhbub** [OpenSID/OpenSID#1419]
Pada lampiran F-2.01 pada saat membuat surat keterangan kelahiran, Nik, nama, alamat dan pekerjaan ayah/ ibu tidak muncul

**Comment by makhbub** [comment]
[bug]

**Comment by eddieridwan** [comment]
@makhbub mohon lampirkan tampilan layar lampiran yg bermasalah, dan jelaskan data apa yg diisi.

**Comment by metalab25** [comment]
Sepertinya tidak ada masalah, saya coba normal muncul dengan baik seperti gambar terlampir dibawah ini

![screenshot_52](https://user-images.githubusercontent.com/19917739/53290619-86c90100-37e1-11e9-9905-e0c1b71858ca.png)

**Comment by makhbub** [comment]
Betul pak, sepertinya masalahnya ada pada Opensid yang saya pakai

Saya juga sudah mencoba opensid yang baru dan dapat berfungsi normal,

kemudian saya masukan data base dari opensid yg biasa saya pakai, masalah
tersebut kembali muncul

Pada tanggal Min, 24 Feb 2019 02.09, Happy <notifications@github.com>
menulis:

**Comment by ariandii** [comment]
Setelah diperiksa pada OpenSID versi 19.07-pasca untuk Lampiran Surat Keterangan Kelahiran sudah tidak ada masalah lagi, semua kolom sudah terisi dengan benar.

Berikut terlampir screenshot Lampiran surat tersebut maupun screenshot rtf nya.

![image](https://user-images.githubusercontent.com/46939846/61554661-a2ca8900-aa87-11e9-9d59-59fe2a11a489.png)

![image](https://user-images.githubusercontent.com/46939846/61554632-93e3d680-aa87-11e9-8e32-421e0eb05cdb.png)

**Comment by eddieridwan** [comment]
Terima kasih, bung @ariandii . Issue ini saya tutup.
