### ISSUE TITLE
Bug: Jumlah Laporan Kependudukan Bulanan salah kalau ada data WNA

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#143]
<img width="1322" alt="laporan-bulanan" src="https://user-images.githubusercontent.com/249563/40893460-a28a55a6-67e4-11e8-9cd9-068fe66ce11f.png">

Jumlah di Laporan Kependudukan Bulanan salah kalau ada Penduduk WNA.

**Comment by pandigresik** [comment]
ini laporan yang mana ya ? apakah ada screenshot yang bisa membantu

**Comment by egodasa** [comment]
@eddieridwan Issuenya kurang jelas Mas. Biasanya ngikut pakai template issue.

**Comment by egodasa** [comment]
Saya barusan tambah data WNA baru dan dilaporan muncul 1 wna.

**Comment by eddieridwan** [comment]
@egodasa : issue telah diubah. Lihat di atas. 

Untuk penjelasan cara kerja Laporan Kependuduk Bulanan, silakan lihat https://github.com/OpenSID/OpenSID/wiki/Laporan-Kependudukan-Bulanan.

**Comment by egodasa** [comment]
![wna](https://user-images.githubusercontent.com/9961837/40899460-4960822c-67f1-11e8-98a4-fbc55b7ef7c6.jpg)
Kalau seperti ini betul tidak Mas? Ini di local saya coba. Jumlahnya udah benar. Untuk WNA nomor KK nya gimana Mas?

**Comment by eddieridwan** [comment]
Jumlah penduduk WNI di baris 7 (_Penduduk akhir bulan ini_) seharusnya tidak menghitung WNA. Jadi di contoh anda, seharusnya WNI Laki-laki bernilai 46 di baris 7. Perlu juga ada _Penduduk akhir bulan ini_ (baris 7) untuk WNA.

**Comment by egodasa** [comment]
Maaf Mas, untuk bagian "penduduk akhir bulan ini" kolom WNA kosong karena https://github.com/OpenSID/OpenSID/blob/master/donjo-app/models/Laporan_bulanan_model.php#L236
Disana, WNA ditulis langsung 0.

Dan ditabel log_bulanan, disana hanya tersedia kolom lk dan pr. Dan kolom ini pun juga tidak menunjukkan perbedaan antara WNA dan WNI sehingga di laporan, WNA dan WNI digabung jadi satu.
Bagaimana koreksinya Mas @eddieridwan ?

**Comment by eddieridwan** [comment]
Untuk jangka panjang, lebih aman tabel `log_bulanan` diubah untuk membedakan:

- wni_lk, wni_pr
- wna_lk, wna_pr

Method `Laporan_bulanan_model->tulis_log_bulanan()` perlu disesuaikan.

Kemudian perlu dicari cara migrasi data yang sudah ada di tabel `log_bulanan` supaya ikut dipilah.

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
