### ISSUE TITLE
[tampilan-admin]Tabel Submenu kategori inventaris tidak responsif

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#1430]
### Bagaimana alurnya sampai muncul masalah?
buka Sekretariat > inventaris > cek seluruh tabel sub menu pada kategori inventaris (tampilan HP)

### Seperti apa yang diharapkan?
tabel sub menu pada kategori inventaris menjadi responsif

### Apa yang terjadi?
untuk saat ini sub menu kategori inventaris tidak ramah dengan tampilan HP

### Informasi tambahan 
![untitled](https://user-images.githubusercontent.com/35319600/43239037-fb7650a8-90ba-11e8-95c3-96d2daf0cb40.jpg)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sepertinya memang sudah maksimal responsifnya. Tabelnya tampaknya tidak bisa diperkecil lagi.

Sudah dikerjakan di PR #1433.
