### ISSUE TITLE
[Bug]Penduduk (Mati/pindah/hilang) Menampilkan data ganda

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#1438]
### Bagaimana alurnya sampai muncul masalah?
penduduk > jadikan penduduk lepas > ubah status penduduk (mati/pindah/hilang) > sortir (mati/pindah/hilang) 

### Seperti apa yang diharapkan?
data penduduk yang di sortir tidak ganda

### Apa yang terjadi?
data penduduk lepas ketika dirubah status (mati/pindah/hilang) data penduduk tersebut menjadi ganda pada sortir tampilan

### Informasi tambahan 
![untitled1](https://user-images.githubusercontent.com/35319600/43304304-c7c84f16-919d-11e8-8fff-f53669f2d2fc.jpg)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
@balongbesuk ini sepertinya karena database yang salah. Nanti coba dilacak. Mengubah status penduduk lain tidak menimbulkan masalah. Apakah anda bisa coba replikasi masalah ini untuk penduduk lain di http://demo.opensid.info?

**Comment by balongbesuk** [comment]
![untitled1](https://user-images.githubusercontent.com/35319600/43305209-1197c074-91a1-11e8-9b84-5b4c63be934e.jpg)

pada tampilan modernisasi penduduk ahlul

**Comment by eddieridwan** [comment]
Sudah dicommit ke branch _beta_.
