### ISSUE TITLE
[Bug] Biodata penduduk dengan status mati/pindah/hilang seharusnya tidak bisa diubah

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#1439]
### Bagaimana alurnya sampai muncul masalah?
1. Untuk penduduk dengan status mati/hilang/pindah, katakanlah dengan id 2, di address bar, masukkan url `http://localhost:8080/OpenSID/index.php/penduduk/form/1/0/2`.
2. Ubah data dan simpan

### Seperti apa yang diharapkan?
Seharusnya perubahan data tidak bisa disimpan

### Apa yang terjadi?
Sekarang masih bisa disimpan.

** Juga periksa di tempat lain di mana data penduduk bisa diubah **

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | v18.07
| Versi PHP        | 
| System operasi   |

**Comment by egodasa** [comment]
@eddieridwan Apakah ada yang mengerjakan issue ini Mas? Saya baru mengerjakan issue ini, dimana perubahan tidak akan disimpan untuk update data, dan update lokasi penduduk juga tidak akan disimpan. Apakah ada tempat update data penduduk lainnya?

**Comment by eddieridwan** [comment]
@egodasa belum ada yg mengerjakannya. Silakan anda kerjakan. Untuk issue ini perlu menerapkan pencegahan update langsung di `Penduduk_model.php` dan `donjo-app/controllers/Penduduk.php` (tidak hanya di UI).

Misalnya, di `Penduduk_model.php`, cegah update di `function update($id=0)` dan di `function update_position($id=0)`. Cek kalau ada function update lainnya.

**Comment by egodasa** [comment]
@eddieridwan Untuk manajemen berkas penduduk bagaimana Mas? Apakah dimatikan fitur ini jika penduduk berstatus selain hidup?

**Comment by eddieridwan** [comment]
@egodasa sepertinya dokumen penduduk perlu bisa diubah, karena mungkin ada dokumen terkait status pindah/mati/hilang yang perlu diunggah.

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR #1556
