### ISSUE TITLE
Fitur: Cetak laporan perkembangan penduduk perlu menampilkan perkembangan keluarga

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#144]
Statistik > Laporan Kependudukan Bulanan

Tampilan laporan dilayar telah ditambahkan data perkembangan keluarga. Data ini perlu juga ditampilkan di dalam fitur Cetak untuk laporan tersebut.

**Comment by afa28** [comment]
Sudah tersedia di versi terbaru, silahkan di reopen jika masih bermasalah.
