### ISSUE TITLE
[tampilan admin] Panduan surat

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#1442]
### Bagaimana alurnya sampai muncul masalah?
Cetak Surat > Panduan 
![panduan](https://user-images.githubusercontent.com/25834335/43351891-01cae9b8-924c-11e8-9b40-9344a9c57139.png)

### Seperti apa yang diharapkan?
![panduan 1](https://user-images.githubusercontent.com/25834335/43351888-fc89c17c-924b-11e8-8d6e-51e2433d2e7e.png)

### Apa yang terjadi?
Hasilnya Blank

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
URL-nya salah, seharusnya http://demo-admin.opensid.info/index.php/surat/panduan. Jalan normal. Jadi issue ini kami tutup.
