### ISSUE TITLE
[tampilan admin] Hapus Surat di Layanan Arsip

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#1443]
### Bagaimana alurnya sampai muncul masalah?
Cetak Surat > Arsip Layanan ketika ingin menghapus arsip layanan yang muncul not found
![hapus surat](https://user-images.githubusercontent.com/25834335/43351997-a05e2840-924e-11e8-9916-8a1434d92330.png)
![konfirmasi hapus](https://user-images.githubusercontent.com/25834335/43352002-b180060c-924e-11e8-809f-fea9f9c4bb6a.png)
![not found](https://user-images.githubusercontent.com/25834335/43352003-bdbd805c-924e-11e8-9786-636a830be0db.png)

### Seperti apa yang diharapkan?
Harapannya supaya seperti di rilis 18.07 pasca

### Apa yang terjadi?
tidak bisa menghapus surat di arsip layanan

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dikerjakan di PR #1533
