### ISSUE TITLE
[tampilan-admin]surat keterangan penduduk tidak tersentuh modernisasi

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#1447]
### Bagaimana alurnya sampai muncul masalah?
cetak surat > cetak surat > surat keterangan penduduk

### Seperti apa yang diharapkan?
perbaiki tampilan

### Apa yang terjadi?
untuk saat ini surat tersebut belum tersentuh modernisasi

### Informasi tambahan 
![untitled1](https://user-images.githubusercontent.com/35319600/43353207-597571fa-925c-11e8-81a0-a5a70234d141.jpg)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by balongbesuk** [comment]
surat ini hilang pada situs demo-admin

**Comment by eddieridwan** [comment]
@balongbesuk disebabkan ada surat ubahan di folder desa/surat. Setelah dihapus, surat ini ok.
