### ISSUE TITLE
[tampilan-admin]surat keterangan kelahiran

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#1448]
### Bagaimana alurnya sampai muncul masalah?
Cetak surat > Cetak Surat > Surat keterangan Kelahiran

### Seperti apa yang diharapkan?
Samakan dengan surat kelahiran pada master 18.07

### Apa yang terjadi?
beberapa fungsi surat tidak muncul

### Informasi tambahan 
![untitled1](https://user-images.githubusercontent.com/35319600/43353280-6c412098-925e-11e8-8739-ce7e37d91102.jpg)

![untitled1](https://user-images.githubusercontent.com/35319600/43353320-98d08e40-925f-11e8-85c5-ca35fc5f037d.jpg)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by MUHAMMADRANGSEL** [comment]
mASLAHNYA JUGA EXPOR DOC TIDAK BERFUNGSI
