### ISSUE TITLE
[tampilan-admin]Surat Permohonan Perubahan Kartu Keluarga (F-1.16 & F-1.01)

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#1450]
### Bagaimana alurnya sampai muncul masalah?
Cetak surat > ceta surat > Cetak Surat Permohonan Perubahan Kartu Keluarga (F-1.16 & F-1.01)

### Seperti apa yang diharapkan?
fungsi surat berjalan seperti pada opensid 18.07

### Apa yang terjadi?
ketika alasan pemohon dipilih penambahan / pengurangan anggota keluarga, sistem surat masih tetap mewajibkan mengisi kolom lainnya 

### Informasi tambahan 
![untitled1](https://user-images.githubusercontent.com/35319600/43355537-ffd6fa2a-9287-11e8-9d63-26e76b812853.jpg)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by balongbesuk** [comment]
![untitled1](https://user-images.githubusercontent.com/35319600/43594134-aa0c0bf6-96a3-11e8-99fe-fab0eb91d7e7.jpg)

mungkin ini yang kelupaan untuk dilaporkan, pemohon surat wajib diisi

pada [tampilan-admin] kebanyakan surat ketika pemohon surat tidak diisi bisa dicetak

**Comment by eddieridwan** [comment]
Di issue #1450, kolom _Alasan Lainnya_ wajib diisi kalau _Alasan Permohonan_ adalah _Lainnya_. Juga _NIK / Nama_ pemohon wajib diisi.

**Comment by eddieridwan** [comment]
Dari @fitamrin: Issue #1450 pada point  kolom Alasan Lainnya wajib diisi kalau Alasan Permohonan adalah Lainnya. Juga NIK / Nama pemohon wajib diisi, bug ini sudah ada dimaster 18.07

**Comment by eddieridwan** [comment]
Issue #1450 sudah diperbaiki pada tahap perbaikan sebelumnya, mengapa masih belum ditutup?

**Comment by eddieridwan** [comment]
@fitamrin : Issue #1450: di http://demo.opensid.info bisa dilihat bahwa NIK / Nama wajib diisi. Sedangkan di PR #1552 tidak.
<img width="1300" alt="perubahan-kk" src="https://user-images.githubusercontent.com/249563/43693298-76197002-9970-11e8-9292-10c9001241ac.png">
<img width="1300" alt="perubahan-kk-baru" src="https://user-images.githubusercontent.com/249563/43693312-8024fc92-9970-11e8-99d9-b2149dd65a35.png">

**Comment by eddieridwan** [comment]
Sudah dikerjakan di PR #1552.
