### ISSUE TITLE
Perlebar Scroll Bar di Menu Navigasi

### ISSUE THREAD

**Issue by hirudi** [OpenSID/OpenSID#1452]
### Bagaimana alurnya sampai muncul masalah?

Scrollbar nya terlalu tipis....

![opensid-tampilan-admin](https://user-images.githubusercontent.com/4936934/43355671-81b7fac4-928a-11e8-8242-8f7e00814e5a.png)

### Informasi tambahan 
Sy cek di Chrome dan Edge, win 10

**Comment by eddieridwan** [comment]
Solusinya tidak boleh mengubah file asli bawaan plugin. Melainkan di file css terpisah. File css ubahan ada di `assets/css/admin-style.css`. Letakkan perubahan di situ.

![ubah-scrollbar](https://user-images.githubusercontent.com/249563/45062491-44115080-b0fd-11e8-9ef5-9715a5a4cce1.jpg)
