### ISSUE TITLE
[tampilan admin] form di semua surat perlu disesuaikan

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#1453]
### Bagaimana alurnya sampai muncul masalah?
Menu Cetak Surat => Cetak Surat => ada beberapa form yang perlu disesuaikan panjangnya
![form](https://user-images.githubusercontent.com/25834335/43355919-f33daae6-9298-11e8-8647-74b5b27638b2.png)

### Seperti apa yang diharapkan?
Form perlu di pendekkan seperti
1. Form NIK/ Nama 
2. Form Nomor Surat 
3. Form Berlaku dari dan sampai 
4. Form Staf Pemerintah Desa
5. Form Menjabat sebagai

SUPAYA LEBIH MENARIK di LIHAT

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Dari @fitamrin : Issue #1453 pada point masalah panjang form sudah saya sesuaikan kecuali untuk form nomor surat, saya rasa yang ada lebih tepat.

**Comment by eddieridwan** [comment]
Dari @fitamrin :  Issue #1453 sudah saya perbaiki, berhubung tidak ada pemeriksaan atas perbaikan ini dan waktu pemeriksaan habis maka issue ini dianggap selesai.

@MUHAMMADRANGSEL : harap anda periksa apakah issue ini sudah bisa ditutup.

**Comment by MUHAMMADRANGSEL** [comment]
Setelah Kami Periksa satu persatu tinggal 2 form surat yang masih perlu di sesuiakan lagi
1. Surat Permohonan Perubahan Kartu Keluarga (F-1.16 & F-1.01)
2. Surat Keterangan Kelahiran

**Comment by MUHAMMADRANGSEL** [comment]
1. Surat Permohonan Perubahan Kartu Keluarga (F-1.16 & F-1.01)
![perubahan kk](https://user-images.githubusercontent.com/25834335/43685250-24a30514-98e2-11e8-8080-c269a2ffc9eb.png)
2. Surat Keterangan Kelahiran
![kelahiran](https://user-images.githubusercontent.com/25834335/43685246-1be689f0-98e2-11e8-95f1-7affb08467a8.png)

**Comment by MUHAMMADRANGSEL** [comment]
Kalau surat yang lain sudah OK semua

**Comment by eddieridwan** [comment]
Sudah dikerjakan di PR #1552
