### ISSUE TITLE
# Tambahkan Kolom poto

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#1454]
### Bagaimana alurnya sampai muncul masalah?
Menu Data Penduduk =>Penduduk perlu di tambahkan kolom untuk poto
![kolom poto](https://user-images.githubusercontent.com/25834335/43356475-d138dffa-92a3-11e8-85da-c8f941226222.png)

### Seperti apa yang diharapkan?
Kedepannya untuk menjadikan data menjadi lebih mantap lagi dengan ada poto

### Informasi tambahan 
Mengingat di Sistem SIAK DUKCAPIL ada kolom poto di menu Penduduk

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by MUHAMMADRANGSEL** [comment]
Poto yang akan kami masukkan adalah poto yang ada di E-KTP dengan cara kami SCAN sehingga poto yang ada di Data di DUKCAPIL dengan OPENSID sama

**Comment by MUHAMMADRANGSEL** [comment]
ini juga supaya pemerintah desa bisa tau wajah masyarakat desa tersebut

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR #2066
