### ISSUE TITLE
tambah menu upload di layanan mandiri

### ISSUE THREAD

**Issue by jagoankitegoku** [OpenSID/OpenSID#1457]
untuk layanan mandiri sekiranya ditambahkan menu upload berkas, gunanya masyarakat bisa upload berkas secara mandiri tidak bergantung pada operator desa,,ini juga meringankan beban operator

**Comment by eddieridwan** [comment]
Seperti dijelaskan di https://github.com/OpenSID/OpenSID/wiki/Pengelolaan-Masalah-dan-Permintaan-Perbaikan-SID, untuk suatu issue diprioritaskan, perlu informasi yang jelas, rinci dan lengkap. Misalnya, berkas apa yg akan diunggah, untuk apa, apa aturannya, dsbnya. Permintaan yg bersifat umum sukar diterapkan.

**Comment by MUHAMMADRANGSEL** [comment]
Upload berkas berupa gambar gambar atau pdf

**Comment by jagoankitegoku** [comment]
Berkas berupa gambar hasil scan atau pdf dibuat kan salah satu atau
keduanya bagus

Pada tanggal Rab, 24 Okt 2018 06.50, MUHAMMADRANGSEL <
notifications@github.com> menulis:

**Comment by afa28** [comment]
Pak @eddieridwan , ini sudah ada fiturnya di layanana mandiri melalui fitur premium. Mungkin bisa di close
