### ISSUE TITLE
[Bug] Hanya satu entri surat 'Cetak' yg tampil di Arsip Layanan

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#1463]
### Bagaimana alurnya sampai muncul masalah?
1. Buka _Cetak Surat > Cetak Surat_
2. Buat beberapa surat 'Cetak' (lebih dari satu)
3. Buka _Cetak Surat > Arsip Layanan_
4. Perhatikan tampilan

### Seperti apa yang diharapkan?
Masalah di gambar berikut telah diperbaiki.
<img width="1279" alt="surat-cetak" src="https://user-images.githubusercontent.com/249563/43363321-8f52ae52-9345-11e8-92ee-265e01c2be0d.png">

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | v18.07
| Versi PHP        | 
| System operasi   |

**Comment by suphm** [comment]
bukannya ada di wikinmya bahwa surat yang dicetak tidak akan diarsipkan.
saya juga pernah [berkomentar mungkin serupa disini](/OpenSID/OpenSID/issues/971#issuecomment-390489236). Nah apakah sebaiknya surat yang  dicetak, direkam juga, om?

**Comment by eddieridwan** [comment]
@suphm Suratnya sendiri tidak arsipkan. Tetapi pada versi sebelumnya setiap pencetakan tercatat di arsip layanan (yaitu surat jenis apa, pada tgl berapa, untuk siapa) -- entah kapan tidak jalan lagi.

**Comment by eddieridwan** [comment]
Sudah dicommit ke master
