### ISSUE TITLE
Untuk petugas penandatangan surat disamakan semua

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#1470]
### Bagaimana alurnya sampai muncul masalah?
Cetak Surat => Cetak Surat, disemua sebagian besar petugas Penanda Tangan belum ada an. dan ub seperti gambar dibawah ini : 
![penanda tangan1](https://user-images.githubusercontent.com/25834335/43365133-85e9b3e6-935a-11e8-92ec-216da2c745a6.png)

### Seperti apa yang diharapkan?
yang diharapkan di semua form surat untuk penanda tangan surat disamakan seperti gambar dibawah ini : 
![penanda tangan](https://user-images.githubusercontent.com/25834335/43365123-6738d774-935a-11e8-89a7-31ccd8d8f60d.png)

### Apa yang terjadi?
Tidak ada an. dan ub 

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
@MUHAMMADRANGSEL, ini bukan issue [tampilan-admin] karena sudah ada di v18.07.

**Comment by prihantosimbah** [comment]
Isian Menjabat Sebagai bagaimana kalau dihilangkan saja.
hasil cetak surat tergantung dari penandatangan;
jika bukan Kepala Desa atau Sekretaris Desa maka pada surat tercetak "an. Kepala Desa"

Untuk list Staf Perangkat Desa hanya berisi staf yang diperbolehkan menandatatangani surat, tidak semua Staf Perangkaat Desa Aktif misal:
Kepala Desa; Sekretaris Desa; Kasi Pemerintahan.

**Comment by MUHAMMADRANGSEL** [comment]
Memang Betul Sekali om prihantosimbah kalau bisa diatur seperti itu semakin lebih mantap lagi, saya setuju
