### ISSUE TITLE
Perubahan isian KTP Berlaku di form surat keterangan pindah penduduk

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#1472]
### Bagaimana alurnya sampai muncul masalah?
Cetak surat ==> Cetak Surat ==> Form Surat Keterangan Pindah penduduk di form KTP berlaku S/D dibuat supaya bisa diubah disamping otomatis karena tidak semua penduduk memiliki KTP apalagi yang umurnya bawah 17 tahun dan yang belum buat ktp sama sekali
![ktp](https://user-images.githubusercontent.com/25834335/43365258-a3e07cc0-935c-11e8-8bc0-870d77bafd8b.png)

### Seperti apa yang diharapkan?
disamping otomatis bisa diubah juga melalui form surat

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
@MUHAMMADRANGSEL Ini bukan issue [tampilan-admin] karena sudah ada di v18.07.

Juga, ketentuan KTP dibuat selalu seumur hidup disetujui di issue https://github.com/OpenSID/OpenSID/issues/282 - dari pembahasan panjang di FB dan di issue. Kalau tidak salah, @afri18 (bung Syafri) berperan dalam diskusi ini.

Kalau ingin diubah, perlu ada pembahasan ulang untuk disepakati teman2 yg berkepentingan dan mengetahui peraturan, dsbnya.
