### ISSUE TITLE
[tampilan-admin] Tambah KK tidak bisa cari NIK 

### ISSUE THREAD

**Issue by tasdiek** [OpenSID/OpenSID#1476]
pada waktu tambah KK di form tidak bisa memuncul nik/nama yang akan di cari

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by tasdiek** [comment]
`
![kk](https://user-images.githubusercontent.com/23473751/43432121-6d5463e8-949b-11e8-98e1-d5d08441ace8.PNG)
`

**Comment by eddieridwan** [comment]
@tasdiek , itu bukan error. Memang tidak ada data untuk ditampilkan. Pilihan yg tampil di situ hanya penduduk yg masih 'lepas', yaitu yang data kartu keluarganya kosong.

Silakan coba buat penduduk baru menggunakan menu _Data Penduduk > Penduduk > Penduduk Domisili_. Penduduk baru tersebut akan tampil sebagai pilihan di fitur _Tambah KK_.

Info lebih lanjut ada di https://github.com/OpenSID/OpenSID/wiki/Pengisian-Data-Keluarga.
