### ISSUE TITLE
Fitur: Tambahkan catatan pembuatan dan penghapusan keluarga

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#148]
Saat ini pada waktu menambah keluarga baru atau menghapus keluarga tidak ada catatannya. Sekarang dengan adanya log_keluarga, ada baiknya ditambahkan catatan pada waktu menambah atau menghapus keluarga:

Dari bung Syafri:

Penambahan catatan mungkin keterangan kenapa KK tersebut ada atau di hilangkan, cukup > 
1. pendatang (satu keluarga datang)
2. pecah_kk, (terjadinya perceraian/anggota keluarga membuat kk baru)
3 kk_baru, (artinya penduduk yang baru berumah tangga)
4. kepala_kk_pindah (karna kepala kk pindah, biasanya di disdukcapil no kk jadi baru)
5. kepala_kk_mati (kalau kepala kk mati di disdukcapil no kk jadi baru)
6. kk_pindah (satu keluarga pindah)

**Comment by afri18** [comment]
![image](https://cloud.githubusercontent.com/assets/6611881/18793702/31cd81b6-81e6-11e6-9ab1-02b8acce59b4.png)
gambarannya : bisa diambil di log penduduk dengan acuan kk_level 1 (satu) di tweb_penduduk

**Comment by eddieridwan** [comment]
Kosong karena yang dilaporkan di #118 dan #146 adalah jumlah *KELUARGA* sesuai dengan yang tampil di laman Penduduk > Keluarga. Yaitu bukan melaporkan jumlah *Kepala Keluarga* (penduduk).

Saat ini jumlah KELUARGA hanya berubah saat menambah keluarga atau menghapus keluarga (semua fitur di laman Keluarga).

Kemudian, bagaimana kalau Kepala Keluarga status dasarnya berubah? Saya sudah tanyakan ini di https://www.facebook.com/groups/OpenSID/, di https://www.facebook.com/groups/sisteminformasidesa/ dan juga di #146, tetapi tidak ada yang menanggapi.

Jadi yang diterapkan di #146 adalah:
- pada saat seorang penduduk yang Kepala Keluarga status dasarnya berubah menjadi pindah/mati/hilang, dia tidak menjadi kepala keluarga lagi, tetapi
- KELUARGA yang ditinggal tidak dihapus. Masih ada dan tampil di laman Keluarga, tetapi Kepala Keluarganya kosong. Jadi dalam hal ini tidak ada perubahan KELUARGA di tabel laporan bulanan (tetapi tentunya ada di perubahan PENDUDUK).

Ini dengan asumsi, nanti sesudah dibuat Nomor KK baru dan adanya kepala keluarga baru, Keluarga yang lama akan dihapus dan diganti dengan Keluarga yang baru. 

Bung @afri18 , anda punya pendapat/pendekatan yang lain?

**Comment by afri18** [comment]
dalam SOP disdukcapil bila Kepala Keluarga pindah/mati/hilang automatis anggota keluarga yang ditinggal membuat Kartu Keluarga Baru
dalam hal ini saya berfikir perlunya diberi keterangan/riwayat kenapa muncul kartu keluarga baru,
ini saya dapati setiap akhir tahun desa  melaporkan tentang kepala keluarga > baru, datang, pindah,mati,
selama ini laporan tersebut harus dicari secara manual

**Comment by afri18** [comment]
tapi yang jelas OPENSID selangkah bahkan lebih inovatif dibandingkan CRI,
SALUT buat bung EDDIE

**Comment by afri18** [comment]
terjadi kekeliruan jumlah ??
![image](https://cloud.githubusercontent.com/assets/6611881/18807289/4eba5a1a-826d-11e6-9f35-9c3735e0497e.png)

**Comment by MUHAMMADRANGSEL** [comment]
Dan juga bisa ditambahkan keterangan selain hidup, mati, hilang, pindah juga ada double atau data ganda spy data double tidak dihapus tetapi tersimpan di log penduduk spy desa ada refrensi berapa jumlah kepala keluarga yg memiliki lebih dari 1 Kartu Keluarga

**Comment by MUHAMMADRANGSEL** [comment]
Seperti sistem yg ada di dinas dukcapil bahwa data yg ganda mempunyai tempat khusus yg sering disebut data hilang yg kemudian masyarakat harus melapor dulu ke dinas dukcapil tuk memunculkan data tersebut

**Comment by MUHAMMADRANGSEL** [comment]
Dimana sekarang ini dengan adanya aturan baru tentang peninggalan data NIK 1 org 1 BAIK untuk selamanya

**Comment by eddieridwan** [comment]
@MUHAMMADRANGSEL, @afri18  dan teman2 POKJA:
Issue ini untuk "Tambahkan catatan pembuatan dan penghapusan keluarga". Untuk dikerjakan diperlukan:

1. contoh tampilan layar untuk form isian (mungkin lebih dari satu?) meng-entri catatan tersebut. Di menu mana catatan tersebut akan di-ketiikkan?
1. contoh tampilan layar di mana catatan tersebut akan ditampilkan

Kalau ada usul tambahan lain (seperti di comment2 @MUHAMMADRANGSEL di atas), silakan buatkan issue baru.

Satu issue perlu dibatasi hanya untuk satu masalah/tugas/usul.

**Comment by MUHAMMADRANGSEL** [comment]
1. Jika Kepala Keluarga Mati maka Anggota Keluarga akan dibuatkan Nomor KK Baru
2. Jika Kepala Keluarga Pindah Maka Anggota Keluarga akan dibuatkan Nomor KK Baru
===>> dan menurut keterangan dari Petuga Dinas DUKCAPIL KABUPATEN LOMBOK TIMUR bahwa Nomor Kartu Keluarga sudah melekat kepada KEPALA KELUARGA

**Comment by MUHAMMADRANGSEL** [comment]
Sehingga Ketika Kepala Keluarga diubah status dasarnya menjadi mati maka secara otomatis Istrinya menjadi Kepala Keluarga dengan Nomor Kartu Keluarga 0 dulu

**Comment by afa28** [comment]
pak @eddieridwan,  apakah ini masih bermasalah??

**Comment by eddieridwan** [comment]
Sepertinya masih perlu ditinjau lagi di dalam konteks Laporan Bulanan dan Buku Rekapitulasi Jumlah Penduduk. Terutama terkiat pecah_kk dan buat kk_baru karena menikah, dsbnya.
