### ISSUE TITLE
[Bug] Hapus kolom isian di Surat Keterangan Domisili Usaha

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#1483]
### Bagaimana alurnya sampai muncul masalah?
1. Buka _Cetak Surat > Cetak Surat > buat Surat Keterangan Domisili Usaha_
2. Perhatikan tampilan dan coba fitur

### Seperti apa yang diharapkan?
Tidak ada kolom isian 'Keterangan' (tidak dipakai).

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | v18.07
| Versi PHP        | 
| System operasi   |

**Comment by agungsugiarto** [comment]
Tidak dipakai, maksudnya hanya perlu dihapus saja form yg saya tandai ini om @eddieridwan ?

![form](https://user-images.githubusercontent.com/10989147/43765118-5c12d6b4-9a59-11e8-84cc-13fea8b29d7b.png)

**Comment by eddieridwan** [comment]
@agungsugiarto , ya kolom isian itu tidak digunakan untuk surat tsb.

**Comment by agungsugiarto** [comment]
Baik akan saya commit besok

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR #1574
