### ISSUE TITLE
[Bug] Tinjau ulang Surat Pernyataan Belum Memiliki Akta Lahir

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#1486]
### Bagaimana alurnya sampai muncul masalah?
1. Buka _Cetak Surat > Cetak Surat > buat Surat Pernyataan Belum Memiliki Akta Lahir_
2. Perhatikan tampilan dan coba fitur

### Seperti apa yang diharapkan?
Semua data di form isian memang digunakan.
Semua informasi di surat Ekspor Doc terisi dengan benar.
Sekarang sepertinya bermasalah. Apakah surat ini masih digunakan?

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | v18.07
| Versi PHP        | 
| System operasi   |

**Comment by MUHAMMADRANGSEL** [comment]
Memang selama ini TDK ada yg pernah buat surat pernyataan belum memiliki akta

**Comment by egodasa** [comment]
Bagaimana kelanjutan issue ini Mas? Apakah masih perlu diperbaiki?

**Comment by eddieridwan** [comment]
Sepertinya perlu dibahas di forum FB dengan pengguna untuk meyakinkan masih digunakan -- dan untuk mengetahui perubahan apa yg diperlukan.

**Comment by afri18** [comment]
Nggak pernah buat, bahkan saat pertama Lom pernah buat, saran hapus ...

**Comment by eddieridwan** [comment]
Lihat http://cigelam.desa.id/first/artikel/185 untuk contoh syarat memperoleh akta kelahiran, dan surat/dokumen terkait.

**Comment by afa28** [comment]
Apakah ini masih bermasalah??? Kalau tdk silahkan di close.

**Comment by agungsugiarto** [comment]
Pembahasan sebelumnya https://web.facebook.com/groups/OpenSID/permalink/1823016931196613

**Comment by eddieridwan** [comment]
Sdh dicommit ke `bug-fix` melalui https://github.com/OpenSID/premium/pull/183
