### ISSUE TITLE
[tampilan-admin] Perbaikan tampilan table inventaris jalan

### ISSUE THREAD

**Issue by agungsugiarto** [OpenSID/OpenSID#1490]
### Bagaimana alurnya sampai muncul masalah?
1. Buka _Sekretariat >Inventaris > Jalan, Irigasi dan Jaringan_
2. Perhatikan tampilan

### Seperti apa yang diharapkan?
Sebaiknya tampilan table konsisten dengan table lain.

![issues](https://user-images.githubusercontent.com/10989147/43384847-6c4e5e50-9409-11e8-93d5-16683831fb20.png)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Dari @fitamrin Issue #1490 pada point menyamakan tabel inventaris dengan tabel lainya, tidak dapat ditindak lanjuti, masalah ini sudah ada di master 18.07 selain itu disebabkan banyak fitur pada modul inventaris yang belum tersedia seperti pencarian (autocomplate), sorting, pagging dll. Sementara itu fitur yang ada merupakan fitur bawaan dari datatable (bootstrap).

**Comment by eddieridwan** [comment]
Bukan issue tampilan-admin. Untuk dikerjakan sebagai issue biasa.

**Comment by agungsugiarto** [comment]
Maksud saya om @eddieridwan, dibuatkan border ditable, sama seperti table pada inventaris lainnya. 
Seperti ini yang saya harapkan 
![untitled](https://user-images.githubusercontent.com/10989147/43620154-7b854ee8-96fb-11e8-8fb7-044baa06712d.png)

**Comment by eddieridwan** [comment]
Issue #1490 sudah diperjelas. Harap dibuatkan border ditable, sama seperti table pada inventaris lainnya.

**Comment by eddieridwan** [comment]
Sudah dikerjakan di PR #1601
