### ISSUE TITLE
[tampilan-admin] Perbaikan fungsi edit data pada Inventaris Tanah

### ISSUE THREAD

**Issue by didikkurniawan** [OpenSID/OpenSID#1491]
### Bagaimana alurnya sampai muncul masalah?
1. Buka Sekertariat-> Inventaris ->Tanah -> Edit Data
2. Perhatikan tampilan dan coba fitur

### Seperti apa yang diharapkan?
1. Tombol yang tertulis simpan ganti dengan tombol tertulis **"Ubah"**
1. Pada saat mengubah data lalu ditekan simpan maka data akan berubah.
2. Pada saat tekan batal maka akan kembali kehalaman inventaris admin tanpa merubah data

### Apa yang terjadi?
1. Data tidak berubah saat di tekan simpan.
2. tombol batal tidak berfungsi.

![image](https://user-images.githubusercontent.com/11713976/43386500-fb908454-940d-11e8-8749-01315a672107.png)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | tampilan-admin Tahap 6
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
@didikkurniawan @fitamrin , supaya konsisten, kita gunakan istilah 'Simpan' untuk semua tombol tambah maupun ubah. Artinya, 'simpan perubahan yg telah dibuat di form'

**Comment by eddieridwan** [comment]
@didikkurniawan yang bisa ditutup, langsung ditutup saja. Terima kasih.

**Comment by eddieridwan** [comment]
Issue #1491: fitur ubah inventaris berjalan normal di http://demo.opensid.info/index.php/inventaris_tanah

**Comment by eddieridwan** [comment]
Sudah dikerjakan di PR #1601
