### ISSUE TITLE
[tampilan-admin] Perbaikan Tampilan Tabel Inventaris Tanah

### ISSUE THREAD

**Issue by didikkurniawan** [OpenSID/OpenSID#1493]
### Bagaimana alurnya sampai muncul masalah?
1. Buka Sekertariat-> Inventaris ->Tanah
2. Perhatikan tampilan dan coba fitur

### Seperti apa yang diharapkan?
Untuk data yang sudah di lakukan mutasi diberikan warna yang berbeda dengan data yang belum dimutasi. bertujuan agar admin lebih mudah memberdakan barang yang belum dan sudah dimutasi.

### Apa yang terjadi?
Baik data yang sudah dimutasi dan belum dimutasi memiliki warna yang sama
![image](https://user-images.githubusercontent.com/11713976/43386896-26424f42-940f-11e8-89db-9979f1cb0081.png)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | tampilan-admin Tahap 6
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Dari @fitamrin : Issue #1493 permasalahan bug ini memang sudah ada dimaster 18.07 dan tidak termasuk dalam tugas projek ini. Projek tampilan-admin sebatas merubah desain tampilan admin versi 18.06/18.07 ke bootstrap dan bukan menyelesai issue bug yang memang sudah ada dimaster 18.06/18.07.

**Comment by eddieridwan** [comment]
Issue #1493: perbedaan inventaris yang sudah dimutasi berjalan normal di http://demo.opensid.info/index.php/inventaris_tanah

<img width="1116" alt="perbedaan-mutasi" src="https://user-images.githubusercontent.com/249563/43638694-24eee96a-975d-11e8-81cb-017f4a144aa5.png">

**Comment by eddieridwan** [comment]
Sudah dikerjakan di PR #1601
