### ISSUE TITLE
[tampilan-admin] Perbaikan fungsi edit data pada Mutasi Inventaris Tanah

### ISSUE THREAD

**Issue by didikkurniawan** [OpenSID/OpenSID#1495]
### Bagaimana alurnya sampai muncul masalah?
1. Buka _Sekertariat-> Inventaris ->Tanah -> Mutasi Inventaris -> Edit Data_
2. Perhatikan tampilan dan coba fitur

### Seperti apa yang diharapkan?
1. Tombol yang tertulis simpan ganti dengan tombol tertulis **"Ubah"**
2. Pada saat mengubah data lalu ditekan simpan maka data akan berubah.
3. Pada saat tekan batal maka akan kembali kehalaman inventaris admin tanpa merubah data

### Apa yang terjadi?
1. Data tidak berubah saat di tekan simpan.
2. tombol batal tidak berfungsi.
![image](https://user-images.githubusercontent.com/11713976/43387675-457439aa-9411-11e8-851f-f325790d93e8.png)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | tampilan-admin Tahap 6
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
@didikkurniawan @fitamrin , kita gunakan istilah 'Simpan' untuk semua tombol tambah atau ubah data, supaya konsisten. Di sini artinya 'simpan perubahan data yg telah diisi di form'

**Comment by balongbesuk** [comment]
fungsi tombol batal mengembalikan data seperti sebelum di adakan ubahan (misal ganjaran kasi pelayanan >ubah ke ganjaran kasi keuangan > tekan batal > maka isian akan kembali menjadi ganjaran kasi pelayanan ), dan tombol tersebut berfungsi

tombol kembali ke halaman inventaris sudah disediakan tombol warna biru di pojok kiri atas pada gambar

jika dimaksudkan fungsi gambar berubah seperti point 3, sepertinya juga akan merubah tombol batal di menu lainnya,

awalnya saya juga mengira tombol batal itu tidak berfungsi pada issue #1301 , 

yang saya pikir juga saya seperti pak didik fungsinya kembali kemenu sebelum edit

saya pikir fungsi batal

**Comment by eddieridwan** [comment]
@balongbesuk , @didikkurniawan 

Semua tombol 'Batal' sudah digunakan secara konsisten menggantikan tombol di v18.07 yg berjudul 'Bersihkan', yaitu untuk membatalkan perubahan form -- tetapi tetap berada di form itu.

Tombol 'Kembali' juga konsisten untuk pindah ke halaman lain.

Tombol 'Tutup' juga konsisten untuk menutup form modal tanpa melakukan perubahan,

Tombol 'Simpan' digunakan untuk menyimpan perubahan atau tambahan data.

**Comment by eddieridwan** [comment]
@fitamrin @didikkurniawan jadi butir (3) di issue di atas tidak dikerjakan. Yaitu, tombol 'Batal' tidak pindah, hanya mengembalikan data ke aslinya.

**Comment by balongbesuk** [comment]
berarti bugnya ada pada point 2,

**Comment by eddieridwan** [comment]
Dari @fitamrin : ssue #1495 pada pont tombol simpan dan batal edit data pada modul inventaris, permasalahan bug ini memang sudah ada dimaster 18.07ah ada dimaster

**Comment by eddieridwan** [comment]
Issue #1495, fitur simpan berjalan normal di http://demo.opensid.info/.

**Comment by eddieridwan** [comment]
Sudah dikerjakan di PR #1601
