### ISSUE TITLE
Perbaikan surat keterangan lahir mati

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#1496]
### Bagaimana alurnya sampai muncul masalah?
1. Buka _Cetak Surat > Cetak Surat > buat Surat Keterangan Lahir Mati_
2. Perhatikan tampilan dan coba fitur

### Seperti apa yang diharapkan?
Tinjau ulang surat ini, termasuk:
- nama ibu, pilihan hanya perempuan
- hari terisi secara otomatis

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | v18.07
| Versi PHP        | 
| System operasi   |

**Comment by junandia** [comment]
![gambar](https://user-images.githubusercontent.com/10545975/61019461-7c8c5580-a3c4-11e9-9c59-2724142cacab.png)

apakah nama ibu itu yang ini pak @eddieridwan ?

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR #2143
