### ISSUE TITLE
[tampilan-admin] Perbaikan fungsi edit data pada Inventaris peralatan dan mesin

### ISSUE THREAD

**Issue by didikkurniawan** [OpenSID/OpenSID#1507]
### Bagaimana alurnya sampai muncul masalah?
1. Buka Sekertariat-> Inventaris ->Peralatan dan Mesin-> Edit Data
2. Perhatikan tampilan dan coba fitur

### Seperti apa yang diharapkan?
1. Pada saat mengubah data lalu ditekan simpan maka data akan berubah.

### Apa yang terjadi?
1. Data tidak berubah saat di tekan simpan.

![image](https://user-images.githubusercontent.com/11713976/43434253-17884056-94a5-11e8-84dc-a3709dde2651.png)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | tampilan-admin Tahap 6
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Dari @fitamrin : Issue #1507 pada point masalah fungsi edit data di inventaris peralatan dan mesin, masalah ini memang sudah ada di master 18.07.

**Comment by eddieridwan** [comment]
Dari @fitamrin : Issue #1520 pada point masalah fungsi edit data di inventaris asset Tetap Lainnya, masalah ini memang sudah ada di master 18.07.

**Comment by eddieridwan** [comment]
Issue #1507, fitur ini berjalan normal di http://demo.opensid.info/ (branch _master_).

**Comment by eddieridwan** [comment]
#1507 bisa diubah, tetapi data yg sudah ada hilang di form edit, seperti terihat di gambar berikut:
<img width="1325" alt="ubah-inventaris" src="https://user-images.githubusercontent.com/249563/44012248-0cf06e64-9f01-11e8-9b48-570af35cc56a.png">

**Comment by eddieridwan** [comment]
Sudah dikerjakan di PR #1609
