### ISSUE TITLE
 [tampilan-admin] Perbaikan Tampilan Tabel Inventaris Peralatan dan Mesin

### ISSUE THREAD

**Issue by didikkurniawan** [OpenSID/OpenSID#1508]
### Bagaimana alurnya sampai muncul masalah?
1. Buka Sekertariat-> Inventaris ->Peralatan dan Mesin
2. Perhatikan tampilan dan coba fitur

### Seperti apa yang diharapkan?
Untuk data yang sudah di lakukan mutasi diberikan warna yang berbeda dengan data yang belum dimutasi. bertujuan agar admin lebih mudah membedakan barang yang belum dan sudah dimutasi.

### Apa yang terjadi?
Baik data yang sudah dimutasi dan belum dimutasi memiliki warna yang sama.
![image](https://user-images.githubusercontent.com/11713976/43434474-f4e94918-94a5-11e8-8146-77349fd4b6c8.png)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | tampilan-admin Tahap 6
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Dari @fitamrin : Issue #1508 pada point memberikan warna berbeda antara data yang sudah dimutasidan yang belum, masalah ini sudah ada master 18.07. Sebenar sudah yang ada sudah bisa dibedakan antar data yang sudah mutasi atau belum yaitu tampil dan sembunyinya tombol mutasi data.
