### ISSUE TITLE
[tampilan-admin] Perbaiki tombol yang tidak berfungsi pada menu Mutasi Inventaris Peralatan dan Mesin

### ISSUE THREAD

**Issue by didikkurniawan** [OpenSID/OpenSID#1509]
### Bagaimana alurnya sampai muncul masalah?
1. Buka Sekertariat-> Inventaris ->Peralatan dan Mesin-> Mutasi Inventaris -> Lihat Data
2. Perhatikan tampilan dan coba fitur

### Seperti apa yang diharapkan?
Hilangkan tombol Batal dan Simpan
Tombol tersebut tidak ada fungsinya pada saat lihat data.

![image](https://user-images.githubusercontent.com/11713976/43434612-9c2ded78-94a6-11e8-9ad5-7c6cb7cb5d17.png)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | tampilan-admin Tahap 6
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dikerjakan di PR #1533
