### ISSUE TITLE
 [tampilan-admin] Perbaikan fungsi edit data pada Mutasi Inventaris Peralatan dan Mesin

### ISSUE THREAD

**Issue by didikkurniawan** [OpenSID/OpenSID#1510]
### Bagaimana alurnya sampai muncul masalah?
1. Buka Sekertariat-> Inventaris ->Peralatan dan Mesin-> Mutasi Inventaris -> Edit Data
2. Perhatikan tampilan dan coba fitur

### Seperti apa yang diharapkan?
1. Pada saat mengubah data lalu ditekan simpan maka data akan berubah.

### Apa yang terjadi?
Data tidak berubah saat di tekan simpan.

![image](https://user-images.githubusercontent.com/11713976/43434767-4c9b56be-94a7-11e8-967e-500a1d2db82e.png)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | tampilan-admin Tahap 6
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Dari @fitamrin : Issue #1510 pada point masalaH fungsi edit data di sub modul inventaris peralatan dan mesin, masalah ini sudah ada di master 18.07.

**Comment by eddieridwan** [comment]
Sudah dikerjakan di PR #1601
