### ISSUE TITLE
[tampilan-admin] Memunculkan Alert Pada saat Mengubah Data di modul inventaris 

### ISSUE THREAD

**Issue by didikkurniawan** [OpenSID/OpenSID#1512]
### Bagaimana alurnya sampai muncul masalah?
1. Buka _Sekertariat-> Inventaris ->**[nama_inventaris]** -> Ubah Data_
2. Menekan tombol simpan.

### Seperti apa yang diharapkan?
pada saat menekan tombol simpan pada modul inventaris agar ada alert, agar user paham bahwa data telah berhasil terubah.

![image](https://user-images.githubusercontent.com/11713976/43435153-e89ef2ae-94a8-11e8-9675-0bc838b671d3.png)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | tampilan-admin Tahap 6
| Versi PHP        | 
| System operasi   |

**Comment by didikkurniawan** [comment]
Issue ini mohon perhatikan tampilan dan fungsinya pada rilis yang belum di lakukan modernisasi yaitu rilis 18.06. sesuaikan dengan fungsi yang terdahulu.

**Comment by didikkurniawan** [comment]
@eddieridwan pak issue ini apakah termasuk yang dimaster 18.07. bagaimana untuk mengerjakan alert pada saat mengubah data soalnya fungsi edit tidak berfungsi.

**Comment by eddieridwan** [comment]
Issue #1512: ubah data inventaris jalan normal di http://demo.opensid.info/. Dan juga ada alert memberitahu ubah berhasil. Di tampilan-admin gunakan alert standar.

**Comment by eddieridwan** [comment]
Sudah dikerjakan di PR #1601
