### ISSUE TITLE
[tampilan-admin] Perbaikan Tampilan pada Modul Simpan Data Inventaris Asset Tetap Lainnya

### ISSUE THREAD

**Issue by didikkurniawan** [OpenSID/OpenSID#1516]
### Bagaimana alurnya sampai muncul masalah?
1. Buka _Sekertariat -> Inventaris -> Asset Tetap Lainnya -> Tambah Data_
2. Perhatikan tampilan dan coba fitur

### Seperti apa yang diharapkan?
Pada saat memilik kolom **Jenis Asset**, kolom harus menyesuaikan sesuai jenis asset. Berikut merupakan ketentuan dalam tambah data asset lainnya.

| Jenis Asset | Kolom yang muncul
| ---------------- | ----------------
| Buku | Judul dan Pencipta Buku, Spesifikasi Buku
| Barang Kesenian | Asal Daerah Kesenian, Pencipta Kesenian, Bahan Kesenian
| Hewan Ternak| Jenis Hewan Ternak, Ukuran Hewan Ternak
| Tumbuhan   | Jenis Tumbuhan, Ukuran Tumbuhan

![image](https://user-images.githubusercontent.com/11713976/43436943-d8103dc8-94b0-11e8-96d1-4297df84cd78.png)

![image](https://user-images.githubusercontent.com/11713976/43436950-e261044c-94b0-11e8-826b-c98ac78db42d.png)

![image](https://user-images.githubusercontent.com/11713976/43436967-ef86db06-94b0-11e8-8584-aebf80a8fdc2.png)

![image](https://user-images.githubusercontent.com/11713976/43436973-fa8b07f2-94b0-11e8-9a05-35ac667c2e57.png)

Hilangkan fungsi **_required_** pada kolom tertentu.

### Apa yang terjadi?
Kolom tidak menyesuikan jenis dan masih bersifat require.

![image](https://user-images.githubusercontent.com/11713976/43436897-9d8bf476-94b0-11e8-9954-b88efdce135b.png)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by didikkurniawan** [comment]
Issue ini mohon perhatikan tampilan dan fungsinya pada rilis yang belum di lakukan modernisasi yaitu rilis 18.06. sesuaikan dengan fungsi yang terdahulu.

**Comment by didikkurniawan** [comment]
Issue ini sudah dapat di close

**Comment by didikkurniawan** [comment]
Issue ini sudah dapat diclose

**Comment by eddieridwan** [comment]
@didikkurniawan yang bisa ditutup, langsung ditutup saja. Terima kasih.
