### ISSUE TITLE
Catat riwayat tanah di tabel data_persil_log

### ISSUE THREAD

**Issue by afri18** [OpenSID/OpenSID#152]
Setelah saya amati ternyata ada table yg tertinggal > data_persil_log
saya kirim via inbox fb, disini filenya tetep nggak bisa

**Comment by eddieridwan** [comment]
[mastersid.zip](https://github.com/eddieridwan/OpenSID/files/494402/mastersid.zip)

**Comment by eddieridwan** [comment]
@afri, Tabel data_persil_log tidak dipakai di script SID saya (tidak ada referensi ke data_persil_log). Apakah SID anda mempergunakan tabel ini?

**Comment by afri18** [comment]
Data_persil_log untuk mencatat riwayat tanah
Pada tanggal 27 Sep 2016 08.31, "Eddie Ridwan" <notifications@github.com>
menulis:

**Comment by eddieridwan** [comment]
Ya, tapi apakah di SID anda ada scriptnya? Misalnya, script untuk mengisi data ke tabel itu, dan menampilkan data log itu, dsbnya.

**Comment by eddieridwan** [comment]
@afri18 , Di SID 3.10 ada tabel _data_persil_log_, tetapi tidak ada script yang menampilkan maupun mengisi data tabel itu. Di versi SID CRI mana ada scriptnya?

**Comment by afri18** [comment]
saya lupa seingat saya saat pertama menggunakan sid yg ada layanan mandiri cuma saya kesulitan mencari foldernya, yg sid 3.10 malah nggak ada data persilnya kemungkinan CRI menata ulang

**Comment by afri18** [comment]
keistimewaan SID 3.10 menurut saya faviconnya bisa menggunakan logo kabupaten/desa

**Comment by agungsugiarto** [comment]
pAK @eddieridwan, apakah issue ini bisa tutup atau dirubah ke permintaan fitur ?

**Comment by afa28** [comment]
Sudah tersedia menu pertanahan baru, silahkan di cek ulang, Jika masih bermasalah, silahkan dibuatkan issue baru.
