### ISSUE TITLE
[tampilan-admin] Perbaikan fungsi edit data pada Inventaris Asset Tetap Lainnya

### ISSUE THREAD

**Issue by didikkurniawan** [OpenSID/OpenSID#1520]
### Bagaimana alurnya sampai muncul masalah?
1. Buka Sekertariat-> Inventaris ->Asset Tetap Lainnya -> Edit Data
2. Perhatikan tampilan dan coba fitur

### Seperti apa yang diharapkan?
Pada saat mengubah data lalu ditekan simpan maka data akan berubah.

### Apa yang terjadi?
Data tidak berubah saat di tekan simpan.
![image](https://user-images.githubusercontent.com/11713976/43442009-df913406-94c6-11e8-9a11-92a8601c4eb0.png)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | tampilan-admin Tahap 6
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Dari @fitamrin : Issue #1520 pada point masalah fungsi edit data di inventaris asset Tetap Lainnya, masalah ini memang sudah ada di master 18.07.

**Comment by eddieridwan** [comment]
#1520 masih bermasalah. Seharusnya hanya menampilkan data sesuai dengan jenis asset.
<img width="1325" alt="aset-lainnya" src="https://user-images.githubusercontent.com/249563/44012522-178851d2-9f03-11e8-8c75-ab8c0c8b04d1.png">

**Comment by eddieridwan** [comment]
#1520, masih bermasalah. Sekarang tombol _Simpan_ tidak berfungsi, karena masih mewajibkan pengisian semua kolom isian, walaupun tidak relevan untuk jenis aset yg berlaku.
<img width="1325" alt="asset-tetap-error" src="https://user-images.githubusercontent.com/249563/44124184-2d7b7330-a06f-11e8-8ee9-48b80d57a20c.png">

**Comment by eddieridwan** [comment]
Sudah dikerjakan di PR #1620
