### ISSUE TITLE
[tampilan-admin] Perbaikan fungsi edit data pada Mutasi Asset Tetap Lainnya

### ISSUE THREAD

**Issue by didikkurniawan** [OpenSID/OpenSID#1524]
### Bagaimana alurnya sampai muncul masalah?
1. Buka Sekertariat-> Inventaris -> Asset Tetap Lainnya -> Mutasi Inventaris -> Edit Data
2. Perhatikan tampilan dan coba fitur

### Seperti apa yang diharapkan?
Pada saat mengubah data lalu ditekan simpan maka data akan berubah.

### Apa yang terjadi?
Data tidak berubah saat di tekan simpan.

![image](https://user-images.githubusercontent.com/11713976/43443570-749a7086-94cb-11e8-9030-ea1cd116edc9.png)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | tampilan-admin Tahap 6
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Dari @fitamrin : Issue #1524 pada point masalah fungsi edit data di Mutasi Asset Tetap Lainnya, masalah ini memang sudah ada di master 18.07.

**Comment by eddieridwan** [comment]
Issue #1524 fitur ini berjalan normal di http://demo.opensid.info/index.php/inventaris_asset.

**Comment by eddieridwan** [comment]
Sudah dikerjakan di PR #1601
