### ISSUE TITLE
[tampilan-admin] Perbaikan fungsi edit data pada Inventaris Kontruksi Dalam Pengerjaan

### ISSUE THREAD

**Issue by didikkurniawan** [OpenSID/OpenSID#1527]
### Bagaimana alurnya sampai muncul masalah?
1. Buka _Sekertariat-> Inventaris -> Kontruksi Dalam Pengerjaan -> Edit Data_
2. Perhatikan tampilan dan coba fitur

### Seperti apa yang diharapkan?
Pada saat mengubah data lalu ditekan simpan maka data akan berubah.

### Apa yang terjadi?
Data tidak berubah saat di tekan simpan.
![image](https://user-images.githubusercontent.com/11713976/43445316-47df4620-94d0-11e8-93d4-afce2a10b58f.png)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | tampilan-admin Tahap 6
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Dari @fitamrin : Issue #1527 pada point masalah fungsi edit data di inventaris Kontruksi Dalam Pengerjaan, masalah ini memang sudah ada di master 18.07.

**Comment by eddieridwan** [comment]
Issue #1527. Fungsi edit berjalan normal di http://demo.opensid.info/ (branch _master_).

**Comment by eddieridwan** [comment]
#1527, data inventaris bisa diedit, tetapi data di gambar berikut hilang di form ubah:
<img width="1325" alt="edit-konstruksi" src="https://user-images.githubusercontent.com/249563/44013142-1bd4c28a-9f07-11e8-8c24-b20a08eed4d2.png">

**Comment by eddieridwan** [comment]
Sudah dikerjakan di PR #1609
