### ISSUE TITLE
 [tampilan-admin] Perbaiki fungsi simpan pada menu mutasi Kontruksi Dalam Pengerjaan

### ISSUE THREAD

**Issue by didikkurniawan** [OpenSID/OpenSID#1528]
### Bagaimana alurnya sampai muncul masalah?
1. Buka Sekertariat-> Inventaris -> Kontruksi Dalam Pengerjaan -> Mutasi Data

### Seperti apa yang diharapkan?
Muncul form mutasi data Kontruksi Dalam Pengerjaan

### Apa yang terjadi?
Muncul tulisan  Error Session.php
![image](https://user-images.githubusercontent.com/11713976/43445939-c41ddf52-94d1-11e8-86a6-0a2445453c40.png)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | tampilan-admin Tahap 6
| Versi PHP        | 
| System operasi   |

**Comment by didikkurniawan** [comment]
Apabila Mutasi data sudah tersimpan maka jalankan fungsi edit dan perbaikan tombol fungsi. sesuaikan dengan modul inventaris yang lainnya.

**Comment by eddieridwan** [comment]
Dari @fitamrin : Issue #1528 fungsi mutasi data dan ubah data mutasi tidak tersedia di master 18.07. jadi tombol mutasi data di tabel inventaris kontruksi dalam Pengerjaan saya hapus.
