### ISSUE TITLE
Hilangkan atau sembunyikan fungsi Cetak Surat

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#1529]
Apa sebaiknya fungsi cetak ini kita hilangkan saja, karena disamping tidak dapat mengarsip surat keluar fungsi ini berdampingan dengan export doc yang fungsinya sama 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by MUHAMMADRANGSEL** [comment]
kalau saya saya hilangkan semua yang ada cetaknya seperti pertimbangan om balongbesuk, memang kalau saya lihat lebih enak yang expor doc disamping juga bisa mengarsipkan surat

**Comment by MUHAMMADRANGSEL** [comment]
dan juga kalau kita buat surat baru lebih cepat jadi yang expor doc daripada cetak

**Comment by eddieridwan** [comment]
Solusi yg kami usulkan sebagai transisi untuk nantinya sepenuhnya menghapus fitur Cetak:

1. tambahkan setting di Pengaturan > Aplikasi untuk menampilkan tombol _Cetak_ pada form surat. 
2. Defaultnya adalah tidak menampilkan tombol _Cetak_.
3. Buat method helper surat untuk menampilkan tombol Cetak/Unduh pada form surat. Method ini menampilkan/menyembunyikan tombol _Cetak_ berdasarkan setting aplikasi
4. Ubah semua surat bawaan sistem supaya menggunakan helper tombol Cetak/Unduh tersebut

**Comment by MUHAMMADRANGSEL** [comment]
Usul bagus bung,  sehingga ketika ada desa yang mau pakai cetak saja atau
Export saja tdk maslah tergantung desa itu sendiri

Pada tanggal Kam, 27 Sep 2018 08.09, Eddie Ridwan <notifications@github.com>
menulis:

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
