### ISSUE TITLE
Surat Kuasa

### ISSUE THREAD

**Issue by djowah** [OpenSID/OpenSID#1530]
Para Suhu OpenSID boleh usul penambahan fitur Surat Kuasa?
![screenshot_3](https://user-images.githubusercontent.com/36688215/43560483-e480e354-963c-11e8-986e-fb045303fabe.jpg)

**Comment by hendriendric** [comment]
kalau membuat ini sebenarnya mudah, tinggal copas codingnya dari surat lain

**Comment by mizwaruddin** [comment]
@afa28 sdh ada di master
