### ISSUE TITLE
Tanda penghubung (-) pada nama

### ISSUE THREAD

**Issue by mizwaruddin** [OpenSID/OpenSID#1532]
### Bagaimana alurnya sampai muncul masalah?
Ketika menambahkan data penduduk baru, ada nama yg menggunakan tanda baca penghubung (-). Ketika sya inputkan ternyata ditolak oleh sistem.

### Seperti apa yang diharapkan?
Mohon ditambahkan tanda baca penghubung (-) pada input nama.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by MUHAMMADRANGSEL** [comment]
Mohon diselesaikan issue ini bung kebetulan Tiang  sdh lampirkan solusinya
