### ISSUE TITLE
[tampilan-admin]Surat keterangan Kematian

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#1535]
### Bagaimana alurnya sampai muncul masalah?
Cetak Surat > Cetak Surat > Surat Keterangan Kematian

### Seperti apa yang diharapkan?
1. ketika data pemohon > ayah > ibu terisi tidak menghilang ketika pelapor / saksi saksi diinput
2.  nama ibu tidak terisi pada Lampiran surat .pdf
3. Sebab kematian pada surat .rtf terisi
4. Hari / Tanggal / Jam [Hari Kematian]

### Apa yang terjadi?
1. data nama ayah dan nama ibu menghilang  ketika pelapor / saksi saksi diinput
2. Lampiran surat (walaupun data ibu sudah terisi) nama ibu tidak terisi
3. Sebab kematian pada surat .rtf tidak tertulis
4. Hari / Tanggal / Jam Lahir [Hari Lahir]

### Informasi tambahan 
![untitled1](https://user-images.githubusercontent.com/35319600/43595256-6bb849b6-96a6-11e8-9a14-fa3cc64c100f.jpg)

![untitled1](https://user-images.githubusercontent.com/35319600/43595391-bcfef112-96a6-11e8-9f8a-14fca210bdce.jpg)

![untitled1](https://user-images.githubusercontent.com/35319600/43595472-fc6279dc-96a6-11e8-8c66-b7c5f5ffad0c.jpg)

![untitled1](https://user-images.githubusercontent.com/35319600/43595806-c44a5ce4-96a7-11e8-92bd-0bef8f7a280d.jpg)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
@balongbesuk maaf tertinggal. Nanti kita tambahkan pada tahap pemeriksaan akhir.

**Comment by balongbesuk** [comment]
penyebab kematian masih belum benar / masih kosong tidak muncul

![](https://user-images.githubusercontent.com/35319600/43595472-fc6279dc-96a6-11e8-8c66-b7c5f5ffad0c.jpg)

NIK Ibu tidak wajib diisi

![untitled](https://user-images.githubusercontent.com/35319600/44009590-3c85e610-9ed7-11e8-86b7-fcba46eef493.jpg)

**Comment by balongbesuk** [comment]
Bug Penyebab Kematian tidak tertulis ternyata ada di master opensid,

**Comment by eddieridwan** [comment]
Dari @fitamrin : Issue #1535 pada point penyebab kematian tidak muncul pada ekspor dok untuk cetak dokumen surat keterangan kematian, sebenarnya keterangan penyebab kematian ini muncul, penyebab tidak muncul adalah ketika merubah pilihan pelapor/saksi1/saksi2 dari warga desa menjadi warga luar desa atau sebaliknya menyebabkan data keterangan kematian hilang (pada field hidden). Jadi untuk meampilkan keterangan ini harus memilih kembali isian keterangan kematian. Masalah ini juga terdapat pada master v.18.08.

**Comment by balongbesuk** [comment]
sudah fix closed
