### ISSUE TITLE
[tampilan-admin]surat keterangan kelahiran

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#1536]
### Bagaimana alurnya sampai muncul masalah?
Cetak Surat > Cetak Surat > Surat Keterangan Kelahiran

### Seperti apa yang diharapkan?
1. Nomor surat tidak hilang ketika data data isian pemohon surat diinput
2. Buat penduduk baru terkoneksi database penduduk,

### Apa yang terjadi?
1. Nomor surat hilang ketika data data isian pemohon surat diinput
2. Tombol Buat penduduk baru tidak terkoneksi database penduduk,

### Informasi tambahan 

![untitled1](https://user-images.githubusercontent.com/35319600/43597199-8e5d1582-96ab-11e8-9a56-aa574844b7bc.jpg)

![untitled1](https://user-images.githubusercontent.com/35319600/43597137-5f275a8e-96ab-11e8-929f-c302a34d1390.jpg)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
@balongbesuk 

1. Nomor surat tidak hilang ketika data data isian pemohon surat diinput - sudah dikerjakan di PR #1552.

2. Buat penduduk baru terkoneksi database penduduk - bukan issue [tampilan-admin]. Di v18.08 data penduduk baru tersimpan secara otomatis pada saat mencetak Ekspor Dok. Jika ingin cara lain, lebih baik buat issue baru.

**Comment by balongbesuk** [comment]
untuk point 2 saya coba di demo.opensid.info data bayi ketika ditekan tombol "buat penduduk baru" data bayi tersebut langsung tersimpan dalam KK orang tua walaupun belum saya cetak "ekspor Dok"

apakah berarti ini bug? karena data tersimpan dalam KK orangtua sebelum dicetak?

**Comment by eddieridwan** [comment]
@balongbesuk, ternyata saya keliru, maaf. Di v18.08 betul ada tombol _Buat Penduduk Baru_, untuk situasi di mana ibu dari database. Ok, saya buatkan issue baru khusus untuk kasus ini.

**Comment by eddieridwan** [comment]
@balongbesuk sudah dibuatkan issue baru https://github.com/OpenSID/OpenSID/issues/1555. Terima kasih anda telah memberi koreksi atas kekeliruan saya.
