### ISSUE TITLE
Import Lokasi/Garis/Wilayah dari file [enhancement]

### ISSUE THREAD

**Issue by nugraha103** [OpenSID/OpenSID#1550]
### Bagaimana alurnya sampai muncul masalah?
Sebagai contoh pada menu SID Home -> Identitas Desa -> Kantor / Wilayah Desa hanya terdapat pilihan edit lokasi langsung pada peta

### Seperti apa yang diharapkan?
Permintaan Fitur Edit maupun Tambah Data yang berkaitan dengan Peta baik itu Lokasi/Point, Garis/Line, maupun Area/Polygon dengan menggunakan : 
- Form koordinat (manual)
- Import File seperti KML, KMZ, GeoJSON, ataupun format lain

### Apa yang terjadi?
- Pilihan input koordinat manual bisa sangat berguna jika user telah mendapatkan data melalui survey lapangan
- Pilihan import data akan memudahkan pengisian data lokasi yang sudah dihasilkan/diperoleh dari aplikasi GIS maupun data Geospasial lain

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 18.08
| Versi PHP        | 5.6.37
| System operasi   |

**Comment by egodasa** [comment]
@nugraha103 Import data dari GeoJSON sepertinya bisa. Tapi harus ada aturan yang dibuat dalam tata cara export GeoJSON nya. Seperti properti apa saja yang bisa dipakai pada GeoJSON agar nanti properti tersebut bisa ditampilkan pada web, serta properti style agar style pada apliaksi GIS offline juga bisa muncul di web. Dibutuhkan mysql versi 5.7 untuk menyimpan data GeoJSON. Dan dengan fitur seperti ini, kita juga bisa membuat semacam peta dengan menampilkan legenda peta disamping peta. Seperti di https://leafletjs.com/examples/choropleth/. Tetapi menu plan sendiri belum selesai semuanya. Mungkin sebaiknya kita tunggu proyek memodernkan tampilan admin selesai.

**Comment by nugraha103** [comment]
Terimakasih @egodasa.
Aturan export maupun import GeoJSON baiknya mengikuti spesifikasi https://tools.ietf.org/html/rfc7946.

Bahan referensi load file dari komputer lokal
https://github.com/makinacorpus/Leaflet.FileLayer

**Comment by egodasa** [comment]
@nugraha103 Terima kasih atas linknya. Maaf, maksud Saya buka aturan seperti itu. Saat kita mengexport geojson dari aplikasi GIS, biasanya aturan penulisan geojson yang didapat sudah sesuai dengan aturan pada link diatas. Jadi kita tidak perlu membuat atau mengedit lagi geojsonnya.

Dan maksud Saya aturan penulisan disini adalah :
Untuk menampilkan style dari item pada layer peta seperi style marker (gambar icon, ukuran marker), line dan poligon (ketebalan garis, warna garis, warna isian poligon dll). Informasi mengenai style ini masing-masing aplikasi  GIS atau programmer mempunyai cara tersendiri.
Misalkan penulisan yang umum atau yang sering saya temukan diinternet:
```
"properties": {
        "stroke": "#faefef",
        "stroke-width": 1,
        "stroke-opacity": 3,
        "fill": "#de3838",
        "fill-opacity": 0.5
      }
```
Object properties berisi style dari sebuah poligon. Informasi tersebut tersimpan diroot dari properties. Sedangkan di OpenSID sekarang, penulisan stylenya adalah seperti ini :
```
"properties": {
       "style": {
              "stroke": "#faefef",
              "stroke-width": 1,
              "stroke-opacity": 3,
              "fill": "#de3838",
              "fill-opacity": 0.5
        },
        "message": "Ini isi pesan"
      }
```
Style dibuat didalam object style agar lebih mudah dimaintenace. Dan hal selain style seperti pesan yang ingin ditampilkan saat hover pada marker atau line disimpan di object message.

Nah, style seperti ini yang harus diperhatikan. Kita perlu membuat aturan tentang cara penulisan properties style dan informasi lain di geojson terlebih dahulu seperti pada contoh diatas. Karena diprogram nantinya harus ditentukan tentang properties mana yang merupakan style, properties mana yang merupakan pesan.

Nanti aturan ini harus diikuti oleh semua orang yang ingin import data geojson ke opensid. kalau tidak diikuti, nanti hasil style yang sudah diterapkan di aplikasi GIS tidak akan keluar di peta opensid.

**Comment by eddieridwan** [comment]
@egodasa saran yg baik sekali. Mungkin anda langsung saja buatkan style guide di wiki OpenSID berdasarkan penelitian anda. Untuk diikuti oleh teman2 yg lain. Toh nanti kalau ada usul lain, kita bisa bahas bersama dan ubah/lengkapi kalau perlu.

Silakan buatkan halaman wiki baru dan tambahkan tautannya di https://github.com/OpenSID/OpenSID/wiki/Aturan-Penulisan-Script.

**Comment by egodasa** [comment]
Guidenya mungkin nanti dibuat Mas jika fitur ini memang akan diterapkan. Mungkin penerapan finalnya sesudah proyek memodernkan tampilan admin selesai. Untuk saat sekarang saya baru coba-coba diweb dummy lain.

**Comment by nugraha103** [comment]
@egodasa kalau saya sendiri malah ga kepikiran sampai styling. baru belajar pake aplikasi GIS, malah baru tau ternyata GeoJSON bisa simpan/bawa style.

**Comment by naufdotal** [comment]
Saya kemarin coba pake yang versi beta 19.10-pasca sudah diterapkan leaflet yang bisa import garis lokasi. Kebetulan saya dapet lokasinya dengan cara import lokasi menggunakan .GPX yang didapatkan lewat website https://www.gpsvisualizer.com/convert_input dengan memasukkan link koordinat yang diimpor dari openstreetmap.

Namun sayangnya ketika saya mencoba simpan (save), tidak ada perubahan dari sisi mapnya. 
Apakah sudah ada yang mencoba?

**Comment by eddieridwan** [comment]
Pull request https://github.com/OpenSID/OpenSID/pull/2439 belum digabungkan. Jadi v19.10-pasca belum berisi fitur ini.

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR #2476
