### ISSUE TITLE
[tampilan-admin] Perbaikan surat keterangan kelahiran

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#1555]
### Bagaimana alurnya sampai muncul masalah?
1. Buka _Cetak Surat > Cetak Surat > buat Surat Keterangan Kelahiran
2. Pilih ibu dari database penduduk
3. Isi data kelahiran
4. Klik tombol _Buat Penduduk Baru_

### Seperti apa yang diharapkan?
Masalah di gambar berikut telah diperbaiki.
<img width="1359" alt="simpan-data-lahir-3" src="https://user-images.githubusercontent.com/249563/43701130-72c038dc-9998-11e8-9829-a0cbc872a382.png">

Fungsi tombol itu di v18.07 bisa dilihat di gambar2 berikut:
<img width="1359" alt="simpan-data-lahir-1" src="https://user-images.githubusercontent.com/249563/43701153-83d779d2-9998-11e8-90de-7f11fda5b3b3.png">
<img width="1359" alt="simpan-data-lahir-2" src="https://user-images.githubusercontent.com/249563/43701154-840abeb4-9998-11e8-9967-2144bbf25b89.png">

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | tampilan-admin Tahap Akhir
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
#1555, penduduk baru bisa ditambah, tetapi NIK/Nama tidak tampil
<img width="1325" alt="penduduk-baru-lahir" src="https://user-images.githubusercontent.com/249563/44013833-6c9a13e2-9f0b-11e8-9f95-56ba7bd40821.png">

**Comment by balongbesuk** [comment]
issue diatas sudah fix, tetapi masih ada issue baru, ketika memilih saksi warga desa, muncul tabel jenis kelamin yang seharusnya tidak tampil

![untitled](https://user-images.githubusercontent.com/35319600/44067937-fe574142-9fa1-11e8-9222-e48993d73d01.jpg)

**Comment by balongbesuk** [comment]
sudah fix

**Comment by eddieridwan** [comment]
@balongbesuk melaporkan sudah dikerjakan di PR #1620
