### ISSUE TITLE
[tampilan-admin] Peta tidak muncul/error di console saat update area di menu peta

### ISSUE THREAD

**Issue by egodasa** [OpenSID/OpenSID#1557]
### Bagaimana alurnya sampai muncul masalah?
Buka menu peta -> area -> update salah satu area, peta tidak muncul.
![peta](https://user-images.githubusercontent.com/9961837/43725710-753c1c1e-99c7-11e8-9ce4-87647d9f55cc.jpg)
Saya lihat di sourcenya di views/area/maps.php baris 72, sintaks PHP terbawa kedalam javascript (sintaks if yang salah disana). Difile ini, data peta diolah menggunakan javascript, bukan PHP. 

### Seperti apa yang diharapkan?
Peta muncul. Muncul di demo.opensid.info. Tapi di demo-admin tidak.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 18.08
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dikerjakan di PR #1557
