### ISSUE TITLE
[tampilan-admin] Tulisan pada tombol tambah dan hapus teks berjalan salah

### ISSUE THREAD

**Issue by egodasa** [OpenSID/OpenSID#1560]
### Bagaimana alurnya sampai muncul masalah?
Buka menu admin web -> artikel -> Teks berjalan. Terdapat tulisan yang salah ditombo tambah dan hapus.
![selection_734](https://user-images.githubusercontent.com/9961837/43760397-1a5eaf70-9a4c-11e8-8771-ca0a888826d9.png)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 18.08
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
@egodasa : Error ini sudah ada di v18.08. Jadi bukan masalah [tampilan-admin]. Juga sebaiknya kita langsung kerjakan issue #938 untuk menerapkan teks_berjalan sebagai fitur terpisah, seperti slider.

Saya tutup, ya....
