### ISSUE TITLE
Gagal Menambah User + Fix

### ISSUE THREAD

**Issue by ndunks** [OpenSID/OpenSID#1563]
### Bagaimana alurnya sampai muncul masalah?
Menambah user baru error

### Apa yang terjadi?
Error DB karena tidak ada default value untuk kolom user->last_login

### Informasi tambahan 
Quick Fix:
```
ALTER TABLE `user` CHANGE `last_login` `last_login` DATETIME DEFAULT NULL;
```

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 8.08-pasca ( dev / git cloned )
| Versi PHP        | 7
| System operasi   | Debian

**Comment by eddieridwan** [comment]
Ya, masalah STRICT_TRANS_TABLES (https://github.com/OpenSID/OpenSID/wiki/Tanya-Jawab-Install-dan-Update). Ada banyak field di database yg tidak ada nilai default.
