### ISSUE TITLE
[tampilan-admin]Font Kurang Besar?

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#1564]
Sepertinya fontnya kurang besar? perbandingan tampilan admin dan modernisasi
![untitled1](https://user-images.githubusercontent.com/35319600/43780113-0e5c7cb0-9a84-11e8-9f47-ad34c45c64b1.jpg)

**Comment by rahardjo-mk** [comment]
Font di nano vna kurang besar.. sehingga sulit di lihat...
