### ISSUE TITLE
[Usul]Maksimalkan Zoom peta seperti di OpenMap

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#1565]
### Bagaimana alurnya sampai muncul masalah?
buka peta > zoom in

### Seperti apa yang diharapkan?
zoom in dapat di perbesar lagi seperti pada openstreetmap

### Apa yang terjadi?
zoom in kurang maksimal sehingga data penduduk pada gis terlihat sangat berhimpitan

### Informasi tambahan 

![untitled12](https://user-images.githubusercontent.com/35319600/43782528-c9c5542c-9a89-11e8-90f5-488d0a0d3de0.jpg)

![untitled1](https://user-images.githubusercontent.com/35319600/43782530-c9fa8430-9a89-11e8-82cf-3ce8464f026b.jpg)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by egodasa** [comment]
@balongbesuk Untuk menerapkan zoom yang lebih dalam, Mas bisa coba langsung edit kodenya. Silahkan buka folder `/donjo-app/views/gis/maps.php` dan cari tulisan `maxZoom: 18,` lokasinya sekitar baris 24. Silahkan ganti angka 18 ke 19. Dan coba buka petanya. Kalau diset ke 20, ditempat saya peta jadi hilang pas zoom maksimal.

**Comment by balongbesuk** [comment]
terima kasih mas @egodasa

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR #1723
