### ISSUE TITLE
[Template-Surat] Data Ayah kandung di Surat Keterangan Kelahiran

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#1570]
### Bagaimana alurnya sampai muncul masalah?
Layanan Surat => Cetak Surat => Surat Keterangan Lahir 
1. ketika data Ibu dari Database penduduk dan ayah ada didatabase secara otomatis muncul yang ini sudah OK
2. Ketika data Ibu dari Database penduduk sedangkan ayah tidak ada secara otomatis form input muncul ini sudah OK
3. ketika data Ibu tidak terdata di database penduduk sedangkan data ayah sudah ada di database namun datanya tidak muncul INI yang BERMASLAH

![kelahiran](https://user-images.githubusercontent.com/25834335/43790529-76512d18-9aa5-11e8-8929-7e362e7ab7fc.png)

### Seperti apa yang diharapkan?
1. Yang diharapkan adalah ketika data ayah sudah ada didatabase sedangkan data ibu berlum terdata 
    maka data ayah yang ada seharusnya muncul
2. dibuatkan pilihan Tombol seperti data ibu 
3. Yang diharpkan juga sebenarnya di ARSIP LAYANAN di Kolom Nama Penduduk yang terekam itu nama 
    anaknya bukan nama ibunya INI MENURUT SAYA karena yang buat surat keterangan lahir itu 
    ANAKNYA bukan IBUNYA sehingga kita bisa tau siapa nama anak/ penduduk yang sudah buat surat 
    keterangan lahir
   ![sss](https://user-images.githubusercontent.com/25834335/43790896-8b4383c8-9aa6-11e8-815d-902c92590aee.png)

### Apa yang terjadi?
Data ayah input manual seperti input data ibu padahal data ayah sudah ada didatabase

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by ndunks** [comment]
Kenapa ini di close? sudah adakah solusinya?

**Comment by afa28** [comment]
pak @MUHAMMADRANGSEL, apakah ini masih bermasalah???

**Comment by andifahruddinakas** [comment]
Pak @MUHAMMADRANGSEL apakah masih bermaslah???

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/OpenSID/issues/6385
