### ISSUE TITLE
Admin Web > Dokumen > Tambah Dokumen Umum Baru

### ISSUE THREAD

**Issue by agungsugiarto** [OpenSID/OpenSID#1579]
### Bagaimana alurnya sampai muncul masalah?
1. Buka Admin Web > Dokumen >Tambah Dokumen Umum Baru

### Seperti apa yang diharapkan?
1. Bisa menambahkan dokumen baru tanpa menyertakan unggah dokumen

### Apa yang terjadi?
1. Tidak bisa menambahkan dokumen baru karena tidak menyertakan ungggah dokumen.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 18.08-pasca
| Versi PHP        | 
| System operasi   |

**Comment by balongbesuk** [comment]
apa tidak lebih baik mewajibkan pengguna untuk mengunggah berkas, karena nama menunya saja sudah "dokumen", apakah tidak jadi aneh nanti jika yang diisikan hanya judulnya saja.

**Comment by agungsugiarto** [comment]
Saya setuju usualan mewajibkan pengguna untuk mengunggah berkas, mungkin bisa didiskusikan dulu dengan pegiat yg lain
