### ISSUE TITLE
[tampilan admin] Paging Page di Data Suplemen hilang

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#1583]
### Bagaimana alurnya sampai muncul masalah?
https://beta.opensid.info/index.php/suplemen/rincian/1/2 paging page tidak ada di Data Suplemen Sasaran Keluarga/KK, Penduduk
![data suplemen1](https://user-images.githubusercontent.com/25834335/43882083-fc1451e6-9be0-11e8-83cd-c7c6ad92ceeb.png)
![data suplemen3](https://user-images.githubusercontent.com/25834335/43882477-566504e6-9be2-11e8-8c6b-2d48109575a9.png)

### Seperti apa yang diharapkan?
paging page seperti di https://demo.opensid.info/index.php/suplemen/rincian/1/1
![data suplemen](https://user-images.githubusercontent.com/25834335/43882113-183e4304-9be1-11e8-8cd3-1e07b7af7cb8.png)
![data suplemen2](https://user-images.githubusercontent.com/25834335/43882480-5bae7158-9be2-11e8-903a-5ce66a58d9ef.png)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
#1583 masih ada yang kurang, seperti terlihat di gambar berikut:
<img width="1325" alt="rincian-suplemen" src="https://user-images.githubusercontent.com/249563/44014371-05d27f7e-9f0f-11e8-9564-8c5aa9904481.png">

**Comment by eddieridwan** [comment]
Sudah dikerjakan di PR #1609
