### ISSUE TITLE
[Bug] Penduduk dengan status dasar selain HIDUP tampil di peta

### ISSUE THREAD

**Issue by egodasa** [OpenSID/OpenSID#1584]
### Bagaimana alurnya sampai muncul masalah?
Klik menu peta -> legenda disebelah kanan atas peta -> klik keluarga atau penduduk.

### Seperti apa yang diharapkan?
Penduduk dengan status selain HIDUP tidak muncul dipeta.

### Apa yang terjadi?
Penduduk dengan status selain HIDUP muncul dipeta.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 18.08
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR #1585
