### ISSUE TITLE
[tampilan-admin] Mungkin Seharusnya "Kriteria" bukan "Kreteria"

### ISSUE THREAD

**Issue by suphm** [OpenSID/OpenSID#1587]
### Bagaimana alurnya sampai muncul masalah?
Dari Menu > Data Penduduk > Calon Pemilih > pencarian spesifik

Judul form-nya tertulis "Pencarian Dengan Kreteria"

### Informasi tambahan 
Di v18.08 Judul form-nya tertulis "Pencarian Spesifik"

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 18.07-pasca
| Versi PHP        | 7.2
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dikerjakan di PR #1601
