### ISSUE TITLE
[tampilan-admin] Judul statistik tampilan penduduk hilang

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#1592]
### Bagaimana alurnya sampai muncul masalah?
1. Buka _Statistik > Statistik Kependudukan > sembarang statistik (misalnya Pendidikan Dalam KK)_
2. Di tabel data, klik sembarang tautan bilangan jumlah data, misalnya _SLTA/Sederajat > Laki-laki_
3. Perhatikan tampilan

### Seperti apa yang diharapkan?
Ada judul yang menjelaskan data penduduk yang ditampilkan, seperti terlihat di gambar v18.08 di bawah.

<img width="1391" alt="judul-statistik-baru" src="https://user-images.githubusercontent.com/249563/43988128-34c8b1f2-9d72-11e8-8c5b-d351e6cee536.png">
<img width="1391" alt="judul-statistik-lama" src="https://user-images.githubusercontent.com/249563/43988129-34fd1b86-9d72-11e8-9e1e-f85668562546.png">

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | tampilan-admin Tahap Akhir
| Versi PHP        | 
| System operasi   |

**Comment by balongbesuk** [comment]
bug tersebut juga ada pada laporan kelompok rentan

**Comment by balongbesuk** [comment]
saya kira sudah fix

**Comment by eddieridwan** [comment]
Sudah dikerjakan di PR #1609
