### ISSUE TITLE
[tampilan-admin] Menu Utama Tidak Dapat Di Scroll

### ISSUE THREAD

**Issue by hasanmabrur** [OpenSID/OpenSID#1594]
### Bagaimana alurnya sampai muncul masalah?

Ketika kita membuka tampilan admin modern melalui PC pada bagian menu utama (sebelah kiri) tidak bisa di scroll kebawah, hal ini sangat menyulitkan karena harus meng zoom out agar bisa mengakses menu yang ada di paling bawah. (masalah ini tidak berlaku jika diakses melalui smartphone)

### Seperti apa yang diharapkan?

diberikan scroll seperti gambar

![contoh menu utama dengan scroll](https://2.bp.blogspot.com/-zB3Ir9oSZxQ/W254KK-giVI/AAAAAAAAEI0/y4IBoZXFXQ0-qy_n4NGe-jrumK2ezCdigCLcBGAs/s1600/sid.PNG)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah coba menggunakan track pad?

**Comment by balongbesuk** [comment]
sudah ditambahkan, bisa ditutup

**Comment by eddieridwan** [comment]
Sudah dikerjakan di PR #1609
