### ISSUE TITLE
#link_gambar

### ISSUE THREAD

**Issue by afri18** [OpenSID/OpenSID#160]
saat di editor web gambar keluar sedangkan di halaman web nggak muncul, kenapa ya ???
![image](https://cloud.githubusercontent.com/assets/6611881/19178418/ad493114-8c7c-11e6-89ee-41566a585ef5.png)

saya dah pindah ke opensid cuma link buat gambar kok jadi nggak muncul ya ? lihat cigelam.desa.id

**Comment by MUHAMMADRANGSEL** [comment]
Apakah sebelumnya bisa mas syafri

**Comment by hadyanwijaya** [comment]
coba dicek link gambarnya

**Comment by afa28** [comment]
Apakah ini masih bermasalah pak @afri18 ????

**Comment by afri18** [comment]
belum saya periksa ulang, hanya embede tidak muncul sejak gantikucidesa >

**Comment by afa28** [comment]
Buat issue baru jika masih bermasalah.
