### ISSUE TITLE
Hilangkan tombol "simpan" di peta yang hanya untuk dilihat / readonly

### ISSUE THREAD

**Issue by suphm** [OpenSID/OpenSID#1602]
### Bagaimana alurnya sampai muncul masalah?
Buka Menu > Data penduduk > penduduk
Klik pilih aksi > cari
muncul peta

### Seperti apa yang diharapkan?
menurut saya itu mode ```readonly``` jadi tak perlu tombol "simpan"

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 18.08-pasca
| Versi PHP        | 7.2
| System operasi   |

**Comment by MUHAMMADRANGSEL** [comment]
Hanya sekedar menambahkan gambarnya
![image](https://user-images.githubusercontent.com/25834335/44569883-67a7d300-a7ae-11e8-9764-de989a238d5b.png)
![lokasiok](https://user-images.githubusercontent.com/25834335/44569975-b5bcd680-a7ae-11e8-9330-1fb343854f54.png)

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
