### ISSUE TITLE
[bug] surat kematian > sebab kematian tidak tercantum / kosong

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#1603]
### Bagaimana alurnya sampai muncul masalah?
cetak surat kematian > lihat surat > sebab kematian tidak tercantum / kosong

### Seperti apa yang diharapkan?
sebab kematian tertulis

### Apa yang terjadi?
saat ini sebab surat kematian tidak tertulis

### Informasi tambahan 
![](https://user-images.githubusercontent.com/35319600/43595472-fc6279dc-96a6-11e8-8c66-b7c5f5ffad0c.jpg)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
