### ISSUE TITLE
[Bug] Kode Pin warga bisa diisi dibawah 6 digit

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#1604]
### Bagaimana alurnya sampai muncul masalah?
laporan > layanan mandiri > hasilkan pin

### Seperti apa yang diharapkan?
hasilkan Pin minimal 6 digit

### Apa yang terjadi?
 pin dimasukkan 1 digit angka dapat terbuat, 

### Informasi tambahan 
![untitled](https://user-images.githubusercontent.com/35319600/44009910-4bceb1ea-9ed9-11e8-8192-782ec4a5c868.jpg)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR #1607
