### ISSUE TITLE
menu Edit Halaman Yang telah diposting untuk administrator

### ISSUE THREAD

**Issue by andryrukandifauzy** [OpenSID/OpenSID#1610]
### Tidak Ada Menu Edit dalam halaman posting untuk Administartor

- 
![screenshot_7](https://user-images.githubusercontent.com/42363553/44068259-5765ecb0-9fa3-11e8-8426-c09f36ea5755.jpg)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 18.08
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Ini bukan bug. Ini warisan artikel di contoh data awal. Lihat penjelasan di https://github.com/OpenSID/OpenSID/wiki/Tanya-Jawab-Install-dan-Update.

Kami tutup issue ini. Kalau belum terjawab, silakan buka lagi.
