### ISSUE TITLE
[tampilan-admin] Data Wilayah Administratif tidak masuk/disimpan  (Dusun RW dan RT)

### ISSUE THREAD

**Issue by andryrukandifauzy** [OpenSID/OpenSID#1611]
### Bagaimana alurnya sampai muncul masalah?

Tambah penduduk melalui menu _Data Penduduk > Penduduk > Penduduk Domisili_.

pak data dusun rw dan rt tidak masuk/disimpan
![screenshot_15](https://user-images.githubusercontent.com/42363553/44069557-87a25b74-9fa9-11e8-826d-0bed610616ba.jpg)

![screenshot_16](https://user-images.githubusercontent.com/42363553/44069566-9479af64-9fa9-11e8-8e41-3ea8b56b0ac6.jpg)
![screenshot_17](https://user-images.githubusercontent.com/42363553/44069567-94afe57a-9fa9-11e8-9acf-1b9b8c98e496.jpg)

### Seperti apa yang diharapkan?

Data nya bisa disimpan

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 18.08-pasca
| Versi PHP        | 
| System operasi   |

**Comment by andryrukandifauzy** [comment]
![screenshot_18](https://user-images.githubusercontent.com/42363553/44071645-a7105dde-9fb4-11e8-890d-779bab9b6b14.jpg)
![screenshot_19](https://user-images.githubusercontent.com/42363553/44071646-a7f12de6-9fb4-11e8-8813-2bc7f1f10564.jpg)
![screenshot_20](https://user-images.githubusercontent.com/42363553/44071647-a871da54-9fb4-11e8-8097-73ea91be4ffd.jpg)


Mas jadi begini

saya input data dusun rw dan rt di tambah penduduk teteapi pas di simpan terus di munculkan namanya data dusun rw dan rt nya tidak kesimpan kalau yang versi di laptop

kalau yang di beta.opensid.info itu dusunnya jadi salah dan rw rt nya tidak ada

**Comment by eddieridwan** [comment]
@fitamrin : fitur ini berjalan normal di http://demo.opensid.info (v18.08).

**Comment by andryrukandifauzy** [comment]
Untuk di Aplikasi opensid 18.08 pasca tidak berjalan dengan normal

**Comment by eddieridwan** [comment]
@andryrukandifauzy , ya jadi perlu diperbaiki oleh kontraktor pekerjaan Memodernkan Tampilan Modul Admin. Patokannya http://demo.opensid.info (v18.08).

**Comment by andryrukandifauzy** [comment]
Baik pak :)

**Comment by andryrukandifauzy** [comment]
baik pa:)

**Comment by balongbesuk** [comment]
Sepertinya sudah fix

**Comment by andryrukandifauzy** [comment]
sudah fix :)

**Comment by eddieridwan** [comment]
@balongbesuk dan @andryrukandifauzy melaporkan sudah diperbaiki di PR #1620
