### ISSUE TITLE
menu suplemen tidak memiliki paginasi

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#1613]
### Bagaimana alurnya sampai muncul masalah?
buka penduduk > data suplemen

### Seperti apa yang diharapkan?
memiliki paginasi seperti yang lain

### Apa yang terjadi?
data suplemen tidak memiliki paginasi

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by MUHAMMADRANGSEL** [comment]
![image](https://user-images.githubusercontent.com/25834335/44100122-dbd42d0e-a016-11e8-9cbe-10a4a6412882.png)

**Comment by MUHAMMADRANGSEL** [comment]
diharapkan seperti gambar dibawah ini : 
![paginasi suplemen ok](https://user-images.githubusercontent.com/25834335/44317417-c2b29080-a463-11e8-9610-516f41b75e4c.png)

**Comment by junandia** [comment]
Adakah kemungkinan jumlah data nya > 100? 
@balongbesuk @MUHAMMADRANGSEL

**Comment by afa28** [comment]
Apakah ini masih bermasalah??? Kalau tdk silahkan di close.

**Comment by mizwaruddin** [comment]
senggol @ianskids

**Comment by eddieridwan** [comment]
Sdh dicommit melalui https://github.com/OpenSID/premium/pull/53
