### ISSUE TITLE
Tampilan artikel dan widget website hilang

### ISSUE THREAD

**Issue by kelbatuix** [OpenSID/OpenSID#1619]
Mohon bantuannya, website kami setelah di update ke v18.08, Tampilan artikel dan widget hilang di semua beranda maupun halaman/menu kecuali halaman rangkuman demografi. Penyalinan master sudah menggunakan file baru semua, tidak di copas kecuali artikel dan galeri.
Untuk widget juga timbul permasalahan pada pembuatan widget baru dengan kalender gmail.
Mohon kiranya dapat membantu memberikan penjelasan. Halaman website kel-batuix.go.id 
![screenshot 13](https://user-images.githubusercontent.com/25999158/44155735-47eae5a2-a0d8-11e8-9cf1-317d645a1dfc.png)
![screenshot 14](https://user-images.githubusercontent.com/25999158/44155748-4e4474ae-a0d8-11e8-8e37-60d6a3fc705e.png)

**Comment by suphm** [comment]
coba detilkan alurnya, kenapa bisa seperti itu?
sudahkah mengikuti panduan pembaruannya?

bisa juga ini masalah dari tema. coba uji dengan mengganti tema di pengaturannya.

**Comment by kelbatuix** [comment]
Kalau setiap pembaharuan harus ditimpa, jika saya mau install ulang apa harus download dari beberapa versi sebelumnya??
Untuk migrasi DB setiap pembaharuan slalu di migrasikan.

**Comment by eddieridwan** [comment]
@kelbatuix issue untuk melaporkan sesuatu yg nyata2 berupa bug. Pertanyaan penggunaan sebaiknya dilakukan di https://www.facebook.com/groups/OpenSID/.

**Comment by eddieridwan** [comment]
@kelbatuix : sepertinya masalah artikel dan widget yg hilang pada tema hadakewa sudah diperbaiki di v18.09. Harap coba lagi. Kalau masih bermasalah, silakam buka lagi.
