### ISSUE TITLE
[Bug] Perbaikan untuk modul Inventaris Gedung dan Bangunan

### ISSUE THREAD

**Issue by didikkurniawan** [OpenSID/OpenSID#1621]
### Bagaimana alurnya sampai muncul masalah?
Buka menu inventaris -> pilih inventaris gedung dan bangunan -> tekan tombol edit. 

### Seperti apa yang diharapkan?
1. Tidak ada typo.
2. Semua field edit berfungsi.
3. Saat simpan hasil edit semua dapat tersimpan sesuai dengan yang diedit dan tidak menghapus field yang diedit melainkan mengubahnya.

### Apa yang terjadi?
1. Masih ada typo pada tombol "kembali".
![image](https://user-images.githubusercontent.com/11713976/44181979-1143f000-a12f-11e8-9426-8f96bfe197ef.png)

2. Untuk field "KONDISI BANGUNAN" dan "STATUS TANAH" tidak dapat pilihan untuk menggubahnya.
![image](https://user-images.githubusercontent.com/11713976/44182070-6e3fa600-a12f-11e8-8acd-dcfaca8fed26.png)

3. Pada saat simpan hasil edit terdapat data yang diedit malah KOSONG yaitu field "NOMOR REGISTRASI" dan "ASAL USUL"
![image](https://user-images.githubusercontent.com/11713976/44182344-cdea8100-a130-11e8-9f13-84fbf4690f58.png)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | tampilan-admin
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Dari @fitamrin : Issue #1621, pada point field "KONDISI BANGUNAN" dan "STATUS TANAH" tidak dapat pilihan untuk menggubahnya, masalah ini memang sudah ada dimaster v.18.08.(http://demo.opensid.info)

**Comment by eddieridwan** [comment]
Karena sudah ada di v18.08, issue ini dikeluarkan dari [tampilan-admin]. Bug biasa.

**Comment by eddieridwan** [comment]
@didikkurniawan : mungkin anda bisa perbaiki error ini?

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR #1638
