### ISSUE TITLE
[tampilan-admin] Perbaikan untuk modul Inventaris Kontruksi dalam Pengerjaan

### ISSUE THREAD

**Issue by didikkurniawan** [OpenSID/OpenSID#1624]
### Bagaimana alurnya sampai muncul masalah?
Buka menu inventaris -> pilih inventaris kontruksi dalam pengerjaan. 

### Seperti apa yang diharapkan?
Total harga sesuai dengan kolom nilai kontrak

### Apa yang terjadi?
Total harga masih di kolom asal usul biaya
![image](https://user-images.githubusercontent.com/11713976/44183698-2f611e80-a136-11e8-8091-e7359c93434e.png)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | tampilan-admin
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dikerjakan di PR #1630
