### ISSUE TITLE
Logo Surat Belum berubah

### ISSUE THREAD

**Issue by andryrukandifauzy** [OpenSID/OpenSID#1626]
### Bagaimana alurnya sampai muncul masalah?
layanan surat>cetak surat>Ekspor/print
dan 
ketika pilih print langsung di document terdpat double text

ketika di ekspor dan dibuka filenya logobelum berubah dengan logo desa
![screenshot_23](https://user-images.githubusercontent.com/42363553/44218484-fe1f3780-a1a3-11e8-8487-5b2bd9f054ee.jpg)
![screenshot_24](https://user-images.githubusercontent.com/42363553/44218576-30c93000-a1a4-11e8-8c4b-d05b9e6a9182.jpg)
![screenshot_25](https://user-images.githubusercontent.com/42363553/44218577-30c93000-a1a4-11e8-9fcd-2264615c705d.jpg)
![screenshot_26](https://user-images.githubusercontent.com/42363553/44218579-3161c680-a1a4-11e8-84bc-031f9c9c6570.jpg)

### Seperti apa yang diharapkan?

Logo nyaberubah jadi logo desa ketika di ekspor dan ketika di print tidak ada double teks
### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    |18.08-pasca 
| Versi PHP        | 
| System operasi   |

**Comment by MUHAMMADRANGSEL** [comment]
1. MASALAH LOGO DESA DI EXPOR DOK HARUS DIRUBAH MANUAL YANG BERADA DI FOLDER SURAT .RTF
2. MASALAH ketika pilih CETAK langsung terdapat double text di ganti di folder surat .php diperkecil ukuran huruf untuk judulnya

dimasing-masing surat tedapat 
1. surat.php
2. print_surat.php
3. surat.rtf
