### ISSUE TITLE
[tampilan-admin] Data RW dan RT tidak masuk/disimpan di tambah KK baru

### ISSUE THREAD

**Issue by andryrukandifauzy** [OpenSID/OpenSID#1627]
### Bagaimana alurnya sampai muncul masalah?

data penduduk>keluarga>tambah KK baru

ketika di save untukdata rw dan rt tidak masuk

![screenshot_27](https://user-images.githubusercontent.com/42363553/44273329-6ab03a00-a269-11e8-8c7d-204698755fd4.jpg)
![screenshot_28](https://user-images.githubusercontent.com/42363553/44273330-6b48d080-a269-11e8-90e7-3aba8c0c0d52.jpg)
![screenshot_29](https://user-images.githubusercontent.com/42363553/44273332-6b48d080-a269-11e8-8a7e-17be3b562602.jpg)

### Seperti apa yang diharapkan?

Data rw dan rt dapat disimpan 

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 18.08-pasca
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dikerjakan di PR #1630
