### ISSUE TITLE
Tombol Batal Tidak berfungsi di Data Penduduk

### ISSUE THREAD

**Issue by andryrukandifauzy** [OpenSID/OpenSID#1631]
### Bagaimana alurnya sampai muncul masalah?

Data Penduduk>penduduk>tambah penduduk

>keluarga>tambah keluarga

ketika akan membatalkan proses penambahan data tombol batal tidak berfungsi

### Seperti apa yang diharapkan?

Tombol batal berfungsi dalam pembatalan proses input data
### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 18.08-pasca
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Ini bukan bug.

Fungsi tombol2 dijelaskan di https://github.com/OpenSID/OpenSID/wiki/Aturan-Penulisan-Script:

* "Kembali" untuk tombol keluar dari form isian tanpa menyimpan data
* "Batal" untuk tombol mengembalikan perubahan isian data menjadi seperti semula
* "Simpan" untuk tombol menyimpan pengisian/perubahan isian data
