### ISSUE TITLE
[Bug] error log di hosting

### ISSUE THREAD

**Issue by andryrukandifauzy** [OpenSID/OpenSID#1640]
### Bagaimana alurnya sampai muncul masalah?
buka file error logs

![screenshot_37](https://user-images.githubusercontent.com/42363553/44460650-242b5880-a638-11e8-988c-12c14d4ccd52.jpg)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 18.08-pasca
| Versi PHP        | 
| System operasi   |

**Comment by andryrukandifauzy** [comment]
Mas @eddieridwan  saya mau bertanya ,berhubungan dengan bug diatas ,
saya upload opensid ke  hosting dan terus di onlinekan  pertnyaanya baru dibuka satu kali  halaman websitenya /siteman nya  untuk Entry prosess langsung cepat penuh  itu barubuka satukali
dan dibuka beberapa kali akhirnya hostingnya lngsung limit resource reached

Entry prosess 
![screenshot_39](https://user-images.githubusercontent.com/42363553/44468709-0b2ea180-a650-11e8-82d4-587e58ac7adb.jpg)


Penyebanya kenapa ya mas ?
apakah dari  banyak pemanggilan script?

terimakasih

**Comment by andryrukandifauzy** [comment]
Untuk detil error logs 
[error_log (2).zip](https://github.com/OpenSID/OpenSID/files/2310732/error_log.2.zip)

**Comment by balongbesuk** [comment]
untuk date timezone jika pak andry bermain .htaccess saya menggunakan ini pada isian .htaccess

php_value date.timezone 'Asia/Jakarta'

bug date timezone sudah tidak muncul lagi

pengalaman jika entri proses cepat penuh biasanya dikarenakan memang terlalu banyak Java script yang memproses halaman tersebut,

**Comment by eddieridwan** [comment]
Error tema hadakewa telah diperbaiki di branch master.

**Comment by eddieridwan** [comment]
Sepertinya masalah di issue ini sudah tertangani. Issue ini kami tutup. Kalau masih bermasalah silakan buka lagi dengan penjelasan tambahan.

**Comment by eddieridwan** [comment]
@andryrukandifauzy Coba upgrade ke versi pra-rilis terkini. Pastikan tidak menggunakan PHP v7.

**Comment by andryrukandifauzy** [comment]
Baik om @eddieridwan  sudah normal kembali
