### ISSUE TITLE
Sesuaikan dengan PHP v7 (jadi support PHP 5.3.7 s/d 7.x

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#1642]
### Bagaimana alurnya sampai muncul masalah?
Jalankan menggunakan PHP v5.3.7 s/d PHP v7

### Seperti apa yang diharapkan?
Beroperasi normal di semua versi PHP tersebut

### Apa yang terjadi?
Saat ini ada error bila menggunakan PHP v7

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | v18.08
| Versi PHP        | 
| System operasi   |

**Comment by rokhibsimrs** [comment]
Manut mawon pak

**Comment by suphm** [comment]
yang pernah saya tahu masalah di PHP7 ada di import/expor database sering muncul pesan `deprecated` ada juga data statistik yang  tidak muncul di website

**Comment by eddieridwan** [comment]
Website http://demo.opensid.info (rilis v18.09) dan http://beta.opensid.info (branch _master_) sekarang menggunakan PHP 7.2.7.

Semua pengguna diharapkan melakukan testing pada kedua website itu. Dan jika menemukan masalah, dimohon membuat issue baru, dengan memberi prefix _[php7]_, supaya programmer mengetahui error apa yg perlu diperbaiki.

**Comment by eddieridwan** [comment]
Karena sudah tidak ada laporan masalah terkait PHP v7 di website http://beta.opensid.info, issue ini dianggap sudah dikerjakan.
