### ISSUE TITLE
Buat URL artikel pada website mengikuti Judul artikel

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#1645]
### Bagaimana alurnya sampai muncul masalah?
1. Buka Artikel (sembarang) pada website opensid
2. Perhatikan URL 

### Seperti apa yang diharapkan?
harapannya agar nomor artikel dapat diganti menjadi judul artikel

### Apa yang terjadi?
saat ini judul artikel menggunakan nomor

### Informasi tambahan 
![untitled1](https://user-images.githubusercontent.com/35319600/44562916-f6ecc080-a785-11e8-9bfd-e77994eb4e63.jpg)

![format tanggal lahir](https://user-images.githubusercontent.com/35319600/47170198-afbb2000-d32f-11e8-90d0-d6a42989a5ae.png)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by suphm** [comment]
duplikat #59

**Comment by hasap86** [comment]
dalam pengerjaan ini harus ada pilihan di seting Permalink, defaultnya seperti sekarang, tapi bisa juga seperti yg diharapkan issue ini. untuk referensi bisa kita ambil contoh konsep permalink Wordpress.

[https://codex.wordpress.org/Using_Permalinks](https://codex.wordpress.org/Using_Permalinks)

**Comment by balongbesuk** [comment]
bisa jadi bahan bacaan https://codeigniter.com/user_guide/general/routing.html

*masih mencari code yang harus dirubah

**Comment by suphm** [comment]
https://devdocs.io/codeigniter~3/tutorial/static_pages

**Comment by suphm** [comment]
https://devdocs.io/codeigniter~3/tutorial/news_section

**Comment by agungsugiarto** [comment]
Sedang saya kerjakan masih perlu beberapa ubahan di template.

![slug](https://user-images.githubusercontent.com/10989147/52568576-b8d17f00-2e41-11e9-84e1-108b5c5491ac.png)

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR #1980

**Comment by balongbesuk** [comment]
Url artikel masih ada yang tertinggal

https://beta.opensid.my.id/first/artikel/93

**Comment by eddieridwan** [comment]
@balongbesuk , issue ini sudah ditutup. Silakan buat issue baru untuk mengubah artikel statis supaya juga menggunakan url tulisan.
