### ISSUE TITLE
Buat URL Kategori mengikuti judul kategori

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#1646]
### Bagaimana alurnya sampai muncul masalah?
1. Buka Kategori Berita (sembarang) pada website opensid
2. Perhatikan Alamat URL

### Seperti apa yang diharapkan?
Harapannya agar nomor kategori dapat diganti menjadi judul kategori

### Apa yang terjadi?
saat ini nama URL artikel menggunakan nomor

### Informasi tambahan 
![untitled1](https://user-images.githubusercontent.com/35319600/44563084-cd806480-a786-11e8-9ece-6a26875633ac.jpg)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dicommit ke `master` melalui PR #2783
