### ISSUE TITLE
[Bug] Ketika membuat PIN baru dengan tidak isi PIN data gagal disimpan

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#1648]
### Bagaimana alurnya sampai muncul masalah?
Layanan Mandiiri ===>Pendaftar Layanan Mandiri ==> Hasilkan Pin
Ketika Hasilkan Pin dengan tanpa mengisi PIN 
*) Jika PIN tidak di isi maka sistem akan menghasilkan PIN secara acak.

**) 6 (enam) digit Angka.

tetapi ketika PIN tidak diisi hasilnya data gagal disimpan
![screenshot 2018-08-28 20 35 11](https://user-images.githubusercontent.com/25834335/44723564-f3996200-ab02-11e8-8e62-63549208861e.png)
![screenshot 2018-08-28 20 35 15](https://user-images.githubusercontent.com/25834335/44723578-fbf19d00-ab02-11e8-8168-aaaac9670c4c.png)

### Seperti apa yang diharapkan?
1. Menghasilkan PIN secara Acak oleh Sistem
2. Data Bisa disimpan seperti di versi sebelumnya

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
