### ISSUE TITLE
Tampilan halaman form cetak surat keterangan penduduk

### ISSUE THREAD

**Issue by doublegunz** [OpenSID/OpenSID#1649]
### Bagaimana alurnya sampai muncul masalah?

1. Buka Layanan Surat > Cetak Surat > Keterangan Penduduk.
2. Pada saat membuka halaman form untuk cetak surat keterangan pendudukan. tampilan halaman tampak seperti gambar di bawah..
![selection_004](https://user-images.githubusercontent.com/13196484/44941756-4bb7b900-adce-11e8-887a-0830eb346549.png)

### Seperti apa yang diharapkan?
Sama seperti halaman form cetak surat lainnya. Misalkan halaman form untuk cetak surat Keterangan Pengantar: 
![selection_005](https://user-images.githubusercontent.com/13196484/44941798-4e66de00-adcf-11e8-8225-1e733c52df1c.png)

### Apa yang terjadi?
Tampilan tidak rapi.

### Informasi tambahan 
diujicoba di halaman [demo](http://demo.opensid.info/index.php/surat/form/surat_ket_penduduk)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | Versi 18.09
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Ini bukan bug. Melainkan di folder desa/surat ada yg mengunggah versi form surat lama. Sesudah dihapus, dan menggunakan form bawaan sistem, tampil normal. Sepertinya info ini perlu ditambahkan di panduan. Mudah2an ada yg bersedia menulisnya.
