### ISSUE TITLE
[Bug] ketika klik migrasi DB icon Sekretariat Hilang

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#1650]
### Bagaimana alurnya sampai muncul masalah?
pada awalnya sukses tapi ketika Update ke rilis 18.09 pas waktu klik migrasi DB icon sekretrait hilang
![icon skerteriat](https://user-images.githubusercontent.com/25834335/44942207-6ba3a880-addf-11e8-8d0b-5ad7c5109c4f.png)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Bisa perbaiki sendiri melalui menu _Pengaturan > Modul_. Ubah _ikon_ modul _Sekretaria_ menjadi `fa-archive`.

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
