### ISSUE TITLE
[Bug] Link Nomer KK di Data Calon Pemilih 404

### ISSUE THREAD

**Issue by mananya** [OpenSID/OpenSID#1652]
### Bagaimana alurnya sampai muncul masalah?

Home > Kependudukan > Calon Pemilih

404 pada saat klik link "No. KK"

![1](https://user-images.githubusercontent.com/27580502/44946063-f8ba2200-ae1e-11e8-8eb5-b90612cf290a.jpg)

### Seperti apa yang diharapkan?

Data keluarga berdasarkan nomer yang dilink Calon Pemilih

### Apa yang terjadi?

http 404 "Not Found"

![2](https://user-images.githubusercontent.com/27580502/44946070-22734900-ae1f-11e8-9840-15a669e8f531.jpg)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 18.09-pasca
| Versi PHP        |  7.2.8
| System operasi   | Windows

**Comment by eddieridwan** [comment]
Sudah dicommit ke master

**Comment by eddieridwan** [comment]
@mananya terima kasih telah melaporkan. Anda sudah ditambahkan ke daftar kontributor di bagian bawah halaman https://github.com/OpenSID/OpenSID.
