### ISSUE TITLE
[SMS] Link Data nomer Hp penduduk ke daftar kontak SMS

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#1653]
untuk perkembangan Opensid kedepan fitur Daftar kontak Sebaiknya saling terkoneksi dengan Biodata Penduduk yang isian No Telepon terisi

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by metalab25** [comment]
Saya sudah pernah requert dulu tapi tidak pernah ditanggapi

**Comment by pandigresik** [comment]
Bisa diperjelas lagi, mungkin ditambahkan screenshot supaya mudah dipahami perubahan yang diinginkan

**Comment by balongbesuk** [comment]
![weeee](https://user-images.githubusercontent.com/35319600/52630709-87af8800-2eef-11e9-851b-585ff0f2f9bb.jpg)
