### ISSUE TITLE
[Bug] Kirim SMS mewajibkan pengguna mengisi data penduduk, walaupun data penduduk sudah terisi 

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#1654]
### Bagaimana alurnya sampai muncul masalah?
SMS > SMS > Tulis Pesan Baru > Pilih No Tujuan > Kirim

### Seperti apa yang diharapkan?
dapat mengirim Pesan 

(pada OpenSID 18.06 ketika tombol kirim ditekan sms berhasil "terkirim" masuk pada pesan tertunda (mungkin karena tidak menggunakan modem yang support SMS) )

### Apa yang terjadi?
memunculkan error data pilih no tujuan belum terisi

### Informasi tambahan 
![untitled12](https://user-images.githubusercontent.com/35319600/44947747-206bb300-ae3c-11e8-9728-f2ab381d503e.jpg)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR #1679
