### ISSUE TITLE
Contoh Data Disetiap Modul OpenSID

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#1655]
### Bagaimana alurnya sampai muncul masalah?
Tambahkan Contoh data disetiap menu Opensid Agar Pengguna Memiliki gambaran fungsi pada menu yang belum memiliki contoh data

### Seperti apa yang diharapkan?
beberapa menu di demo opensid tidak memiliki contoh data, yang kadang membuat pengguna baru bingung akan fungsi menu tersebut, dan juga lebih memudahkan dan mempercepat menemukan bug ketika ada ubahan baru yang berefek ke fungsi menu yang lain

### Apa yang terjadi?
saat ini beberapa menu demo opensid belum memiliki contoh data

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Teman2 yg telah menyatakan bersedia membantu melengkapi panduan:
- https://web.facebook.com/desararangselatan 
- https://web.facebook.com/nafis.mahmudi2
- https://web.facebook.com/afdal.luddin
- https://web.facebook.com/pemnagsitapa111

**Comment by eddieridwan** [comment]
Pembuatan contoh data akan menggunakan data Rarang Selatan. Nama/NIK/No KK penduduk akan diubah untuk menjaga privasi data penduduk sebenarnya.

Untuk itu, kita perlu memperbaiki struktur tabel berikut, supaya tidak menyimpan data NIK secara langsung:

- `data_persil`, dan
- `tweb_penduduk_mandiri`

Seharusnya kedua tabel ini berisi id penduduk, dan seharusnya ada relational constraint supaya data di kedua tabel itu dihapus secara otomatis kalau data penduduk yg bersangkutan dihapus.

**Comment by eddieridwan** [comment]
Untuk mengacak data pribadi dari Rarang Selatan, yang akan diubah adalah:

1. NIK
2. Nomor KK
3. Nama 

Struktur NIK dijelaskan di tautan ini: https://www.brilio.net/news/ini-rahasia-di-balik-kode-angka-dalam-nik-e-ktp-kamu-belum-tahu-kan-150520z.html. Jadi yang akan diubah secara acak adalah 4 angka terakahir (Nomor Komputerisasi).

**Comment by afa28** [comment]
Tambahkan data penduduk dgn variasi yg berbeda setiap datanya, ini biasa digunakan untuk melihat perbandingan yg ada di modul kependudukan > statistik. Krn contoh data awal yg diberikan tdk bervariasi, sehingga contributor yg mengerjakan issue statistik agak kesulitan dan harus mengubah datanya sendiri.

**Comment by afa28** [comment]
Hapus jg contoh data yg sdah tdk digunakan.
