### ISSUE TITLE
penambahan tombol import file pemetaan

### ISSUE THREAD

**Issue by NikySrundenk** [OpenSID/OpenSID#1660]
### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by NikySrundenk** [comment]
mungkin dibawah ini sedikit gambaran tombol import file pemetaan pak.. 
![import area](https://user-images.githubusercontent.com/42955474/45026317-23e38200-b068-11e8-9292-bd906437f2b0.jpg)
![import jalan desa](https://user-images.githubusercontent.com/42955474/45026318-247c1880-b068-11e8-982c-dd366f78954f.jpg)
![import wilayah desa](https://user-images.githubusercontent.com/42955474/45026320-247c1880-b068-11e8-8369-c839f4d1bb83.jpg)

**Comment by afa28** [comment]
Sudah tersedia di versi terbaru.

![1234567](https://user-images.githubusercontent.com/57283157/85587878-5ced4c00-b66c-11ea-87b9-797e4ae1a755.JPG)
