### ISSUE TITLE
Tambahkan fitur RSS feed untuk artikel baru

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#1661]
### Bagaimana alurnya sampai muncul masalah?
Pelajari berkas berikut:
1. `donjo-app/controllers/Feed.php`
1. `donjo-app/models/Feed_model.php`
1. `donjo-app/views/feed.php`

Saat ini fitur itu tidak berfungsi. Apakah bisa dimanfaatkan?

### Seperti apa yang diharapkan?
Kalau bermanfaat, perbaiki sampai operasional.
Kalau tidak diperlukan, hapus berkas2 tersebut

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 18.09
| Versi PHP        | 
| System operasi   |

**Comment by siayi** [comment]
Saya sendiri, sebagai pengguna (pemanfaat) fitur feed / Rss. Saya mengikuti umpan RSS / Feed situs web (khususnya website desa di Kabupaten Bandung). Hal ini memberi saya kesempatan untuk tetap mendapatkan update/informasi terbaru dari website2 desa tersebut. Dengan menggunakan aplikasi feed reader, saya bisa mengetahui update dari banyak wesbite tersebut secara aggregat.

**Comment by siayi** [comment]
Ilustrasi (Tampilan Feed reader), tidak bisa menjangkau website desa yang berbasis OpenSID, sejak fitur feed tidak berfungsi.
![tidak-ada-update-opensid](https://user-images.githubusercontent.com/1229849/63008933-bcf05f00-bead-11e9-80f5-b3d60178e2a2.jpg)

**Comment by eddieridwan** [comment]
Feed yg dulu ada di OpenSID telah dihapus karena tidak berfungsi dan tidak digunakan.

Tapi kita bisa buat RSS feed baru, karena akan bermanfaat bagi inisiatif OpenDesa - Jejaring Desa Fase II.

Lihat penjelasan penyusunan RSS: https://www.w3schools.com/xml/xml_rss.asp

**Comment by eddieridwan** [comment]
Yg perlu ditentukan adalah:
- apa yg akan ditampilkan di RSS feed -- artikel saja atau lain juga? Mungkin tahap awal artikel saja.
- apakah perlu ada pengaturan untuk setting apa yg akan ditampilkan?

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR #2292
