### ISSUE TITLE
error saat import bip di hosting

### ISSUE THREAD

**Issue by andryrukandifauzy** [OpenSID/OpenSID#1662]
### Bagaimana alurnya sampai muncul masalah?
impor bip
http 500 error

cek error log
![screenshot_13](https://user-images.githubusercontent.com/42363553/45014224-f7b80900-b047-11e8-91e0-436d8c41064f.jpg)

### Seperti apa yang diharapkan?

jika upload bip di localhost tidak ada masalah,ingin lancarseperti import bip offline
### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 18.09-pasca
| Versi PHP        | 
| System operasi   |

**Comment by andryrukandifauzy** [comment]
dan ketika di import database
muncul error
![screenshot_15](https://user-images.githubusercontent.com/42363553/45014526-0c48d100-b049-11e8-93fa-11d081ff4536.jpg)

**Comment by eddieridwan** [comment]
@andryrukandifauzy : untuk error impor data, lihat panduan https://github.com/OpenSID/OpenSID/wiki/Error-Impor-Data-Kependudukan 

Kalau impor BIP jalan normal di localhost, dan juga normal di http://demo.opensid.info, berarti bukan bug -- melainkan masalah di hosting anda. 

Mengenai timezone, seharusnya default Asia/Jakarta. Bisa periksa/ubah di Pengaturan > Aplikasi, lihat https://github.com/OpenSID/OpenSID/wiki/Panduan-Konfigurasi-Aplikasi.

Mengenai error lainnya sepertinya bermasalah di setting PHP di hosting. Bandingkan dengan yg di localhost dan samakan.

Issue di github hanya untuk masalah yg betul2 bug. Masalah anda sepertinya bukan bug dan sebaiknya ditanyakan di https://web.facebook.com/groups/OpenSID/.

Issue ini akan ditutup. Kalau ada masalah yg memang terbukti bug, silakan buka issue baru.

**Comment by andryrukandifauzy** [comment]
Om @eddieridwan  saya coba di demo.opensid.info ternyata sama tidak biasa impor bip
![screenshot_18](https://user-images.githubusercontent.com/42363553/45025450-b9314700-b065-11e8-95d3-26b88d4ae049.jpg)
![screenshot_19](https://user-images.githubusercontent.com/42363553/45025451-b9314700-b065-11e8-8e84-3f22d72ea52a.jpg)

dan jikadi cek dierror logs nya seperti itu
