### ISSUE TITLE
[bug] Tidak bisa impor bip di hosting

### ISSUE THREAD

**Issue by andryrukandifauzy** [OpenSID/OpenSID#1663]
### Bagaimana alurnya sampai muncul masalah?
pengaturan>database>impor bip> impor file

![screenshot_18](https://user-images.githubusercontent.com/42363553/45025606-26dd7300-b066-11e8-81ef-7f0a02680579.jpg)
![screenshot_19](https://user-images.githubusercontent.com/42363553/45025607-27760980-b066-11e8-825e-7f0f5b378a91.jpg)

dan untuk error logs nya seperti punya saya
![screenshot_16](https://user-images.githubusercontent.com/42363553/45025643-3bba0680-b066-11e8-9bd3-93ccf2b1b8d7.jpg)
![screenshot_17](https://user-images.githubusercontent.com/42363553/45025645-3c529d00-b066-11e8-87ee-120a4190546b.jpg)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 18.09-pasca
| Versi PHP        | 
| System operasi   |

**Comment by andryrukandifauzy** [comment]
setelah di reload sepertiini
![screenshot_20](https://user-images.githubusercontent.com/42363553/45025746-8b98cd80-b066-11e8-8661-70a79024ef65.jpg)

**Comment by eddieridwan** [comment]
Terima kasih telah melaporkan. Ternyata masalahnya karena di hosting nama file case sensitive, sedangkan di lokal tidak.

Sudah dicommit ke master.
