### ISSUE TITLE
statistik KTP tidak menampilkan data 

### ISSUE THREAD

**Issue by irull22** [OpenSID/OpenSID#1664]
statistik kepemilikan KTP tidak menampilkan data .. meskipun sudah di input di biodata penduduk..

Tambahan : Kalau bisa diberikan opsi range seperti di statistik umur..supaya ada opsi penampilan data..karena ada kabupaten yang data tersebut sulit didapatkan..seperti kaupaten kami yang hanya menampilkan opsi sudah rekam atau belum rekam..

terima kasih..

**Comment by eddieridwan** [comment]
Di http://beta.opensid.info, statistik kepemilikan KTP tampil normal.
Yang ditampilkan adalah status rekam KTP.
![rekam-ktp](https://user-images.githubusercontent.com/249563/45078501-51056280-b144-11e8-9545-bc3d1e53c6d3.jpg)
![statistik-ktp](https://user-images.githubusercontent.com/249563/45078502-51056280-b144-11e8-92ea-1a7c2269c558.jpg)

**Comment by eddieridwan** [comment]
Mengenai masalah tambahan, mohon buat issue terpisah. Satu issue digunakan untuk satu masalah saja, jangan digabung -- karena masing2 masalah dikerjakan sendiri-sendiri. 

Juga harap gunakan template pelaporan issue yg sudah disediakan, supaya memudahkan bagi yang me-review issue anda.

**Comment by eddieridwan** [comment]
Coba lampirkan tampilan layar memperlihatkan pengisian biodata dan hasil statistik KTP seperti yg dilampirkan di atas. Pastikan anda tidak menggunakan PHP v7.

**Comment by irull22** [comment]
maaf jaringan sedang error kemarin


Rab, 5 Sep 2018 pukul 15.42 Eddie Ridwan <notifications@github.com> menulis:

**Comment by MUHAMMADRANGSEL** [comment]
Perlu di closed untuk issue ini karena sdh tdk ada masalah

**Comment by eddieridwan** [comment]
@irull22 issue ini, mengenai statistik KTP, kami tutup. Kalau masih ada masalah, silakan buka lagi dengan penjelasan tambahan.

Kalau masih menginginkan laporan statistik kepemilikan KTP berdasarkan rentang umur, silakan buat issue baru. Jangan lupa melampirkan rincian seperti apa laporan yg diinginkan.
