### ISSUE TITLE
[bug] Tidak Bisa Cetak Surat Masuk di hosting

### ISSUE THREAD

**Issue by andryrukandifauzy** [OpenSID/OpenSID#1665]
### Bagaimana alurnya sampai muncul masalah?
sekretariat>Surat masuk>pilih surat>cetak surat dan unduh surat masuk

mungkin sama error log hosting 

![screenshot_48](https://user-images.githubusercontent.com/42363553/45081817-33270600-b122-11e8-8baa-e80fc1f87a42.jpg)

,cetak surat,dan unduh surat

![screenshot_49](https://user-images.githubusercontent.com/42363553/45081867-4afe8a00-b122-11e8-9f30-aaccd476d6a3.jpg)
![screenshot_50](https://user-images.githubusercontent.com/42363553/45081879-518d0180-b122-11e8-8cf5-e64b1c4f5185.jpg)
![screenshot_51](https://user-images.githubusercontent.com/42363553/45081880-518d0180-b122-11e8-94f7-8baee1957d62.jpg)
![screenshot_52](https://user-images.githubusercontent.com/42363553/45081881-52259800-b122-11e8-909e-a85ea2db8bca.jpg)
![screenshot_53](https://user-images.githubusercontent.com/42363553/45081883-52259800-b122-11e8-9fb4-5b2f48115885.jpg)

C
### Seperti apa yang diharapkan?

Cetak surat Normal
### Apa yang terjadi?
Tidak Bisa Cetak Surat

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 18.09-pasca
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
