### ISSUE TITLE
Masukan untuk navigasi admin - subvertical collapse menu

### ISSUE THREAD

**Issue by mananya** [OpenSID/OpenSID#1666]
### Bagaimana alurnya sampai muncul masalah?

1. Menu admin
2. Klik salah satu Collapse Menu kemudian klik submenu
    // Pengaturan - Info system
   
![1](https://user-images.githubusercontent.com/27580502/45120855-9435f480-b189-11e8-8d0a-454b3e83664b.jpg)

### Seperti apa yang diharapkan?

Collapse menu vertikal terbuka dan memunculkan submenunya tanpa harus melakukan scrool.

![2](https://user-images.githubusercontent.com/27580502/45121123-61403080-b18a-11e8-8a20-01687e1e92e3.jpg)

Kemudian pada saat klik submenu setelah collapse
Mis. Pengaturan - Info system

Menu tetap di posisi : Pengaturan - Info system

![3](https://user-images.githubusercontent.com/27580502/45121437-589c2a00-b18b-11e8-8e20-afffdd283897.jpg)

### Apa yang terjadi?

Collapse menu vertikal terbuka setelah keluar submenunya kemudian harus melakukan scrool kesubmenu tujuan.

![4](https://user-images.githubusercontent.com/27580502/45121543-a749c400-b18b-11e8-9784-846e932d530e.jpg)

Kemudian pada saat klik pada submenu collapse
Mis. Pengaturan - Info system
Navigasi menu dan submenu navigasi nge-scrool keatas

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    |  18.09-pasca
| Versi PHP        |  5.6.37
| System operasi   | Linux Centos

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
