### ISSUE TITLE
Statistik Laporan Kelompok Rentan

### ISSUE THREAD

**Issue by WAHAB01** [OpenSID/OpenSID#1671]
### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
@WAHAB01 harap judul dibuat singkat. Penjelasan dimasukkan sesuai template yg disediakan. Terima kasih.

**Comment by WAHAB01** [comment]
Ya,
Di laporan kelompok rentan menampilkan semua data penduduk baik yg sudah pindah, hilang, atau mati. Disarankan hanya menampikan data penduduk yg aktif saja
