### ISSUE TITLE
[Bug] Statistik Laporan Kelompok Rentan seharusnya hanya menampilkan penduduk aktif

### ISSUE THREAD

**Issue by WAHAB01** [OpenSID/OpenSID#1672]
Di Statistik Laporan Kelompok Rentan menampilkan semua data penduduk, baik penduduk yang sudah pindah, hilang, tau mati itu semua di tampilkan. Diharapkan hanya menampilkan data penduduk yang aktif saja.

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.

**Comment by WAHAB01** [comment]
Terima Kasih,,,
