### ISSUE TITLE
Update Format Kartu Keluarga sesuai Permendagri 118 Tahun 2017

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#1673]
### Bagaimana alurnya sampai muncul masalah?
Saat ini Kartu Keluarga Penduduk memiliki model isian baru, status perkawinan tercatat dan tidak tercatat,
bagi penduduk dengan status perkawinan tercatat wajib mencantumkan tanggal perkawinan,
bagi penduduk yang berstatus kawin tidak  tercatat, tanggal perkawinan kosong / tidak diisi

![untitled12](https://user-images.githubusercontent.com/35319600/45211623-fa6f6400-b2bc-11e8-8f21-691d6b4b833c.jpg)

catatan : perlu konfirmasi lebih lanjut informasi yang ada ke teman teman dinas capil di grup Facebook Opensid

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by MUHAMMADRANGSEL** [comment]
Dan juga ada penambahan kolom kolom golongan darah yg posisinya di tabel atas

**Comment by MUHAMMADRANGSEL** [comment]
![perubahan tampilan cetak kk](https://user-images.githubusercontent.com/25834335/45250842-88efee00-b36e-11e8-8730-bd80c1355551.png)
![perubahan tampilan kk](https://user-images.githubusercontent.com/25834335/45250843-89888480-b36e-11e8-81d0-c253f80f9568.png)
[Perubahan Tampilan Blangko KK.zip](https://github.com/OpenSID/OpenSID/files/2363047/Perubahan.Tampilan.Blangko.KK.zip)

**Comment by balongbesuk** [comment]
dari komentar facebook : 

> Pemerintahan Desa Kedamean : Salam semuanya ikut nambah untuk KK bru memang ada penambahan elemen data ( nomor & tggl nikah yg sdh dicatat atau belum dicatatkan, Golongan darah, status hubungan FAMILI Lain menjadi FAMILI )

pembagian status Kawin (tercatat dan tidak tercatat), Famili lain > Famili

**Comment by metalab25** [comment]
Apakah yang dimaksud menjadi seperti ini ????
![screenshot_189](https://user-images.githubusercontent.com/19917739/45955401-5cacc080-c042-11e8-8250-e14cc0da3d29.png)
![screenshot_190](https://user-images.githubusercontent.com/19917739/45955402-5cacc080-c042-11e8-8fb7-e282d2217f36.png)

**Comment by metalab25** [comment]
bung @eddieridwan mohon di review

**Comment by eddieridwan** [comment]
@balongbesuk @MUHAMMADRANGSEL : apakah status 'KAWIN BELUM TERCATAT' pengertiannya sama dengan 'KAWIN' untuk:

- penentuan wajib-ktp
- penentuan calon pemilih
- merekam data cara-kb
- dll?

**Comment by MUHAMMADRANGSEL** [comment]
Ya bung

Pada tanggal Sel, 25 Sep 2018 19.50, Eddie Ridwan <notifications@github.com>
menulis:

**Comment by MUHAMMADRANGSEL** [comment]
Ya bunga Eddie,
1.kawin belum tercatat = kawin tp tdk punya buku nikah/akta kawin
2. Kawin tercatat = kawin dan memiliki buku nikah

**Comment by eddieridwan** [comment]
Data penduduk yang ada sekarang hanya menggunakan status 'KAWIN'. Bagaimana cara migrasinya ke salah satu:

1. KAWIN TERCATAT, atau
2. KAWIN BELUM TERCATAT?

Apakah berdasarkan ada atau tidaknya akta nikah? Atau anggap saja semua sebagai KAWIN TERCATAT dan operator akan mengubah ke KAWIN BELUM TERCATAT secara manual, kalau perlu?

**Comment by eddieridwan** [comment]
Perubahan ini sesuai dengan PERATURAN MENTERI DALAM NEGERI REPUBLIK INDONESIA NOMOR 118 TAHUN 2017 TENTANG BLANGKO KARTU KELUARGA, REGISTER DAN KUTIPAN AKTA PENCATATAN SIPIL.

[Permen No.118 TH 2017.pdf](https://github.com/OpenSID/OpenSID/files/2415236/Permen.No.118.TH.2017.pdf)

**Comment by MUHAMMADRANGSEL** [comment]
Menurut saya bung Eddie perlu ada penambahan form isian penduduk kepemilikan buku nikah seperti issue yang sudah saya buat

**Comment by MUHAMMADRANGSEL** [comment]
Di Form Isian Perlu ditambahkan Form Baru Lagi #1319

**Comment by eddieridwan** [comment]
Format salinan Kartu Keluarga telah dicommit ke master melalui PR #1696.

Tetapi issue ini belum bisa ditutup, karena masih ada yg belum dikerjakan:

1. menambah status kawin `KAWIN TERCATAT` dan `KAWIN TIDAK TERCATAT`
2. migrasi data penduduk, mengubah yang sekarang memiliki status kawin `KAWIN` menjadi KAWIN TERCATAT` atau `KAWIN TIDAK TERCATAT` tergantung apakah kolom `Akta Nikah` terisi atau tidak.
3. mengubah status hubungan dalam keluarga dari `FAMILI LAIN` menjadi `FAMILI`

**Comment by metalab25** [comment]
Bukankah dengan adanya nomor akta nikah sudah menguatkan bahwa penduduk tersebut sudah kawi  tercatat

**Comment by eddieridwan** [comment]
Ya, logika itu yg digunakan sebagai dasar migrasi di point 2 di atas.

**Comment by eddieridwan** [comment]
@balongbesuk @MUHAMMADRANGSEL : untuk perubahan seperti ini, yg dilakukan untuk menyesuaikan dgn peraturan, harap selalu melampirkan peraturan dan juklak terkait --- supaya acuannya jelas.

**Comment by MUHAMMADRANGSEL** [comment]
> Format salinan Kartu Keluarga telah dicommit ke master melalui PR #1696.
> 
> Tetapi issue ini belum bisa ditutup, karena masih ada yg belum dikerjakan:
> 
> 1. menambah status kawin `KAWIN TERCATAT` dan `KAWIN TIDAK TERCATAT`
> 2. migrasi data penduduk, mengubah yang sekarang memiliki status kawin `KAWIN` menjadi `KAWIN TERCATAT` atau `KAWIN TIDAK TERCATAT` tergantung apakah kolom `Akta Nikah` terisi atau tidak.
> 3. menghapus status kawin `KAWIN` setelah dilakukan migrasi di langkah (2) di atas.
> 4. mengubah status hubungan dalam keluarga dari `FAMILI LAIN` menjadi `FAMILI`

**Pas Sudah ini Bung**

**Comment by MUHAMMADRANGSEL** [comment]
Ketika Sudah Terisi Kolom Akta Nikah Terisi maka status kawinnya tercatat kalau dia tidak terisi maka belum tercatat

**Comment by MUHAMMADRANGSEL** [comment]
dan untuk issue ###Di Form Isian Perlu ditambahkan Form Baru Lagi #1319### saya tutup saja

**Comment by MUHAMMADRANGSEL** [comment]
http://mediaindonesia.com/read/detail/171234-kemendagri-terbitkan-panduan-penerbitan-kk-bagi-aliran-kepercayaan.html

**Comment by balongbesuk** [comment]
kawin tercatat maupun tidak tercatat saya kira yang menentukan hal tersebut dispendukcapil > sikron data dengan KUA, mungkin sementara tidak perlu dirubah dulu,

**Comment by metalab25** [comment]
Penentuan variable "KAWIN TERCATAT" dan "KAWIN TIDAK TERCATAT" dasarnya apa. Sebaiknya harus dibahas dulu agar pengguna tidak bingung

**Comment by MUHAMMADRANGSEL** [comment]
Lombok Timur Sudah mulai menerapkan perubahan di kolom status kawin di Kartu Keuarga
1. Status Kawin Tercatat
   ![kawin tercatat](https://user-images.githubusercontent.com/25834335/46565975-866ebd00-c949-11e8-85e0-727e9b1507fb.jpg)
2. Status Kawin Tidak Tercatat
   ![kawin tidak tercatat](https://user-images.githubusercontent.com/25834335/46565976-87075380-c949-11e8-81a8-b06989b5e4b8.jpg)

sebagai refrensi contoh Form Isian yang ada di Database SIAK seperti Gambar dibawah ini
![whatsapp image 2018-10-05 at 18 03 35](https://user-images.githubusercontent.com/25834335/46566058-7dcab680-c94a-11e8-9481-b68d8e9a5221.jpeg)

**Comment by MUHAMMADRANGSEL** [comment]
Sehingga menurut saya di OpenSID mungkin perlu ada penambahan form isian

**Comment by MUHAMMADRANGSEL** [comment]
Di Kabupaten Lombok Timur sudah diberlakukan untuk perubahan Kartu keluarga
![img_20181012_0032](https://user-images.githubusercontent.com/25834335/46868097-cbb75100-ce59-11e8-9982-5d57eb3c2b20.jpg)

**Comment by eddieridwan** [comment]
Sudah dikerjakan sisa issue ini sebagai berikut:

1. Tampilkan status kawin penduduk sebagai 'KAWIN TIDAK TERCATAT' atatu 'KAWIN TERCATAT' tergantung ada tidaknya akta perkawinan. Tetapi di database tetap tersimpan sebagai 'KAWIN'.
2. Ganti SHDK 'FAMILI LAIN' menjadi 'FAMILI'.

Sudah di pra-rilis.
