### ISSUE TITLE
Form Buku Administrasi Pemerintah Desa_Permendagri No 47 tahun 2016

### ISSUE THREAD

**Issue by HaeryPutraChan** [OpenSID/OpenSID#1677]
### Bagaimana alurnya sampai muncul masalah?
Bisa nggak ditambahkan format Buku Administrasi Pemerintah Desa,,??

### Seperti apa yang diharapkan?
 Format Buku Administrasi Pemerintah Desa sesuai dengan Permendagri Nomor 47 Tahun 2016.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by MUHAMMADRANGSEL** [comment]
[permen_no.47_th_2016.zip](https://github.com/OpenSID/OpenSID/files/2363933/permen_no.47_th_2016.zip)

**Comment by HaeryPutraChan** [comment]
Maksudnya format Buku administrasi pemerintah desa berdasarkan permendagri no 47 tahun 2016, bisa dimasukan/ditambahkan pada menu aplikasi OpenSID,,???

**Comment by MUHAMMADRANGSEL** [comment]
Selama ada programer yang mau kontribusi insya Allah bisa,  kita berdoa saja mudah2an segera bisa diterapkan

**Comment by eddieridwan** [comment]
Supaya lebih jelas, lampirkan informasi mengenai format yg diperlukan. Lampirkan Permen yg dimaksud, beserta lampirannya, termasuk juklak terkait. Ingat, programmer bukan perangkat desa, dan bukan pula ahli adminduk.

**Comment by MUHAMMADRANGSEL** [comment]
Sudah diatas kami lampirkan bung

**Comment by balongbesuk** [comment]
lampiran yang pak @MUHAMMADRANGSEL tidak ada isinya kosong

**Comment by mizwaruddin** [comment]
@afa28 ganda
