### ISSUE TITLE
>>>>> Link gambar wiki (v18.09+)

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#1684]
[siskeudes_2019.zip](https://github.com/OpenSID/OpenSID/files/3896145/siskeudes_2019.zip)

[mdbconvert.sh.zip](https://github.com/OpenSID/OpenSID/files/3895236/mdbconvert.sh.zip)

![jenis-informasi-publik](https://user-images.githubusercontent.com/249563/67644629-30ffb680-f977-11e9-8271-a6f2a3dddf35.jpg)

![daftar-produk-hukum](https://user-images.githubusercontent.com/249563/67352768-9e3cd180-f59c-11e9-9969-2e4f2328f0ca.jpg)

![menu-produk-hukum](https://user-images.githubusercontent.com/249563/67352467-ce37a500-f59b-11e9-9f63-d31df6c18146.jpg)

![no-default-value](https://user-images.githubusercontent.com/249563/65104470-1ba47d80-da04-11e9-8ada-d07a792cf7c2.jpg)

![responsive-filemanager-kosong](https://user-images.githubusercontent.com/249563/61795156-1abcf880-ae66-11e9-88b6-d9cf46158d8c.jpg)

![error-surat](https://user-images.githubusercontent.com/249563/61193682-5afed700-a700-11e9-98d0-815166026b39.jpg)

![penandatangan-atas-nama](https://user-images.githubusercontent.com/249563/60474232-13b22880-9cb4-11e9-9d3d-d1ed6439d8b6.jpg)
![jumlah-impor](https://user-images.githubusercontent.com/249563/61578100-c7306f00-ab34-11e9-9914-f7386439d822.jpg)
![jumlah-penduduk](https://user-images.githubusercontent.com/249563/61578101-c7c90580-ab34-11e9-9a57-b4b6f08de923.jpg)

![aksi-informasi-publik](https://user-images.githubusercontent.com/249563/67645779-b63a9980-f97e-11e9-876f-a40e6cc3b56d.jpg)
![form-informasi-publik](https://user-images.githubusercontent.com/249563/67645781-b63a9980-f97e-11e9-92b4-95527dd0751e.jpg)
![informasi-publik](https://user-images.githubusercontent.com/249563/67645782-b63a9980-f97e-11e9-875c-58a3f808e8dc.jpg)
![tambah-informasi-publik](https://user-images.githubusercontent.com/249563/67645783-b6d33000-f97e-11e9-82a6-011188c0eaad.jpg)
![contoh-website](https://user-images.githubusercontent.com/249563/67661282-e2710d00-f9b4-11e9-8b17-0eb7ddd2f9dd.jpg)

![atas-nama-2](https://user-images.githubusercontent.com/249563/59564742-bf1f7400-904a-

11e9-876f-779e21fac7bf.jpg)
![atas-nama-1](https://user-images.githubusercontent.com/249563/59564746-c6468200-904a-11e9-9394-65dddea4a86d.jpg)
![atas-nama-3](https://user-images.githubusercontent.com/249563/59564749-d5c5cb00-904a-11e9-830d-2404b1c6524d.jpg)
![tandatangan-default](https://user-images.githubusercontent.com/249563/59564776-2ccba000-904b-11e9-8df2-f80680de6a67.jpg)
![kode-isian-penandatangan](https://user-images.githubusercontent.com/249563/59564810-a3689d80-904b-11e9-8ba5-631d9398a97d.jpg)

**Comment by HerryWanda** [comment]
![pertanahan](https://user-images.githubusercontent.com/32125282/45529452-7ca4de80-b80f-11e8-897f-1d510fded6ae.jpg)

**Comment by HerryWanda** [comment]
![tambah data persil](https://user-images.githubusercontent.com/32125282/45529849-afe86d00-b811-11e8-97a7-274d9caa1566.png)

**Comment by HerryWanda** [comment]
![daftar persil](https://user-images.githubusercontent.com/32125282/45530086-0efab180-b813-11e8-8d2e-a6e549adaf0c.png)

**Comment by balongbesuk** [comment]
![identitas desa](https://user-images.githubusercontent.com/35319600/45582342-0ddf8800-b8d8-11e8-852f-f55f41d5540d.jpg)

**Comment by balongbesuk** [comment]
![form identitas desa](https://user-images.githubusercontent.com/35319600/45582491-459bff00-b8db-11e8-92cd-f622fd4caeb6.jpg)

**Comment by balongbesuk** [comment]
![pemerintah desa](https://user-images.githubusercontent.com/35319600/45584163-32982780-b8f9-11e8-8b6f-77c107f28ebc.jpg)

![tambah staf](https://user-images.githubusercontent.com/35319600/45584201-bd792200-b8f9-11e8-8279-42bf4dfc0ff2.jpg)

![isian staf](https://user-images.githubusercontent.com/35319600/45584249-67f14500-b8fa-11e8-86a3-c1c3f1e22fac.jpg)

![edit staf](https://user-images.githubusercontent.com/35319600/45584299-4b094180-b8fb-11e8-9078-ff0d588e66d1.jpg)

![status staf](https://user-images.githubusercontent.com/35319600/45584324-b9e69a80-b8fb-11e8-8192-1f3c0368655e.jpg)

![hapus staf](https://user-images.githubusercontent.com/35319600/45584363-56a93800-b8fc-11e8-8bd9-631f7f6ec8f0.jpg)

![ttd surat](https://user-images.githubusercontent.com/35319600/45584391-c91a1800-b8fc-11e8-85cd-1bd00f44fecc.jpg)

![ganti ttd](https://user-images.githubusercontent.com/35319600/45584448-e0a5d080-b8fd-11e8-8adb-85e1a65f8aba.jpg)

**Comment by balongbesuk** [comment]
![daftar widget](https://user-images.githubusercontent.com/35319600/45592016-39bc4580-b98c-11e8-9e45-040736b89c13.jpg)

![tambah widget](https://user-images.githubusercontent.com/35319600/45592027-b8b17e00-b98c-11e8-8d81-52c5c36fbc44.jpg)

![form widget dinamis](https://user-images.githubusercontent.com/35319600/45592062-85232380-b98d-11e8-9497-46e77cde71a0.jpg)

![form widget statis](https://user-images.githubusercontent.com/35319600/45592094-902a8380-b98e-11e8-9748-21d310bd9a12.jpg)

![status widget](https://user-images.githubusercontent.com/35319600/45592122-5c9c2900-b98f-11e8-84c4-b8cbfbfaed68.jpg)

![urutan widget](https://user-images.githubusercontent.com/35319600/45592141-da603480-b98f-11e8-8245-28536ee6e946.jpg)

![ubah isian widget](https://user-images.githubusercontent.com/35319600/45592177-97529100-b990-11e8-9125-13fb435eb092.jpg)

**Comment by balongbesuk** [comment]
![tampilan tabel penduduk](https://user-images.githubusercontent.com/35319600/45913805-742e5280-be64-11e8-8749-502b34e3be93.jpg)

![tambah penduduk](https://user-images.githubusercontent.com/35319600/45914000-801c1380-be68-11e8-835f-187e44a799d7.jpg)

![biodata penduduk](https://user-images.githubusercontent.com/35319600/45914309-574a4d00-be6d-11e8-9733-9bed364b58a2.jpg)

![simpan data](https://user-images.githubusercontent.com/35319600/45914187-852e9200-be6b-11e8-8d4f-2ee109ca2a8f.jpg)

![impor bip](https://user-images.githubusercontent.com/35319600/45914610-6c28df80-be71-11e8-99b4-763341d75a99.jpg)

![pilih berkas bip](https://user-images.githubusercontent.com/35319600/45914720-3684f600-be73-11e8-9d8c-cb53397ef5c3.jpg)

![berkas bip](https://user-images.githubusercontent.com/35319600/45914754-a3988b80-be73-11e8-8a17-7c16f11271b8.jpg)

![centang bip](https://user-images.githubusercontent.com/35319600/45914845-f1fa5a00-be74-11e8-8bcf-30834a06b38e.jpg)

**Comment by balongbesuk** [comment]
![format tanggal lahir](https://user-images.githubusercontent.com/35319600/47168507-4802d600-d32b-11e8-99cc-725a0fb6611d.png)

**Comment by balongbesuk** [comment]
![updatedatapenduduk](https://user-images.githubusercontent.com/35319600/49488846-ff6f8f80-f87a-11e8-8c96-7fef707f4993.jpg)

**Comment by balongbesuk** [comment]
![keluarga](https://user-images.githubusercontent.com/35319600/52048243-7bd1d680-257d-11e9-87d3-93dbb01992c1.png)

![tambah keluarga](https://user-images.githubusercontent.com/35319600/52048472-0d414880-257e-11e9-97d9-c470ff6ba4ae.png)

![alamat keluarga](https://user-images.githubusercontent.com/35319600/52048638-79bc4780-257e-11e9-8836-1b507b5173e2.png)

![biodata kepala keluarga](https://user-images.githubusercontent.com/35319600/52049043-5e9e0780-257f-11e9-888e-fa25d271fbb8.png)

![keluarga baru](https://user-images.githubusercontent.com/35319600/52049356-29de8000-2580-11e9-92b9-5e838fd3ca7a.png)

![keluarga baru](https://user-images.githubusercontent.com/35319600/52049703-ff40f700-2580-11e9-900f-22087e1d13bf.png)

![pilih kepala keluarga baru](https://user-images.githubusercontent.com/35319600/52049988-c81f1580-2581-11e9-93f5-228476462102.png)

![pecah kk](https://user-images.githubusercontent.com/35319600/52050441-226ca600-2583-11e9-8205-5c86923ee16c.png)

![pilih kepala keluarga baru](https://user-images.githubusercontent.com/35319600/52050761-2b11ac00-2584-11e9-866a-a7656c83afde.png)

![cetak kk](https://user-images.githubusercontent.com/35319600/52050892-86439e80-2584-11e9-9536-afffb2f451ec.png)

![unduh kk](https://user-images.githubusercontent.com/35319600/52051026-ec302600-2584-11e9-8873-147acc029cac.png)

![aksi ganda](https://user-images.githubusercontent.com/35319600/52051335-e850d380-2585-11e9-845d-58a97f77f89e.png)

![pilah kk](https://user-images.githubusercontent.com/35319600/52051657-c441c200-2586-11e9-82ca-b8e910d2659d.png)

![pilah kk](https://user-images.githubusercontent.com/35319600/52051949-a2950a80-2587-11e9-9488-88fae2a38e4e.png)

![pilah kk](https://user-images.githubusercontent.com/35319600/52052116-23540680-2588-11e9-833d-ab77d0af841a.png)

![rincian kk](https://user-images.githubusercontent.com/35319600/52052545-5fd43200-2589-11e9-8713-b06ffaa50cbd.png)

![rincian kk](https://user-images.githubusercontent.com/35319600/52053239-66fc3f80-258b-11e9-8902-3b160f99071d.png)

![cari](https://user-images.githubusercontent.com/35319600/52053677-9a8b9980-258c-11e9-9afb-db95c7fd1a7c.png)

![kartu keluarga](https://user-images.githubusercontent.com/35319600/52054464-2dc5ce80-258f-11e9-81e1-42b6ca60917d.png)

**Comment by Galiarta** [comment]
![image](https://user-images.githubusercontent.com/33612251/58250236-849c2180-7d93-11e9-8b75-a8b20029eedb.png)

**Comment by Galiarta** [comment]
![image](https://user-images.githubusercontent.com/33612251/58250552-389dac80-7d94-11e9-9757-6674e544d618.png)

**Comment by Galiarta** [comment]
![image](https://user-images.githubusercontent.com/33612251/58256264-473e9080-7da1-11e9-8ee3-aa2417f637b4.png)
![image](https://user-images.githubusercontent.com/33612251/58256400-88cf3b80-7da1-11e9-917a-bb39e37837e0.png)
![image](https://user-images.githubusercontent.com/33612251/58256609-e5325b00-7da1-11e9-8d03-e58898405a2a.png)
![image](https://user-images.githubusercontent.com/33612251/58256749-2296e880-7da2-11e9-96a4-f4bd76811315.png)
![image](https://user-images.githubusercontent.com/33612251/58256971-87ead980-7da2-11e9-961d-09050cadf1ab.png)
![image](https://user-images.githubusercontent.com/33612251/58257289-3bec6480-7da3-11e9-816a-44f3bd334725.png)
![image](https://user-images.githubusercontent.com/33612251/58257483-94bbfd00-7da3-11e9-8f8b-21dabb15bb4c.png)
![image](https://user-images.githubusercontent.com/33612251/58257603-caf97c80-7da3-11e9-9ecb-ef76137c24cd.png)
![image](https://user-images.githubusercontent.com/33612251/58257777-19a71680-7da4-11e9-98ea-62ce1ceb4d20.png)
![image](https://user-images.githubusercontent.com/33612251/58257918-5ecb4880-7da4-11e9-9a0b-ef55704f90bf.png)
![image](https://user-images.githubusercontent.com/33612251/58258022-8e7a5080-7da4-11e9-8bf3-b97b37743917.png)
![image](https://user-images.githubusercontent.com/33612251/58258174-d600dc80-7da4-11e9-8749-394de0211da8.png)
![image](https://user-images.githubusercontent.com/33612251/58258230-f6c93200-7da4-11e9-8984-7bd7b8b1f940.png)
![image](https://user-images.githubusercontent.com/33612251/58258272-09dc0200-7da5-11e9-8a51-10e39217f337.png)
![image](https://user-images.githubusercontent.com/33612251/58258350-2aa45780-7da5-11e9-951e-e36a32dfff58.png)
![image](https://user-images.githubusercontent.com/33612251/58258470-62ab9a80-7da5-11e9-9746-5718e7711e5f.png)
![image](https://user-images.githubusercontent.com/33612251/58258532-840c8680-7da5-11e9-9d67-abfc6597978d.png)
![image](https://user-images.githubusercontent.com/33612251/58258586-97b7ed00-7da5-11e9-8eb2-0b66cb031482.png)
![image](https://user-images.githubusercontent.com/33612251/58258747-e36a9680-7da5-11e9-955c-02fdd13ce139.png)
![image](https://user-images.githubusercontent.com/33612251/58259534-588a9b80-7da7-11e9-9b98-63810bc7e58e.png)

**Comment by Galiarta** [comment]
![image](https://user-images.githubusercontent.com/33612251/58260782-a2748100-7da9-11e9-898a-66fa1f1bc43a.png)
![image](https://user-images.githubusercontent.com/33612251/58260942-f717fc00-7da9-11e9-80b8-efeb0aba55c2.png)
![image](https://user-images.githubusercontent.com/33612251/58261019-1f075f80-7daa-11e9-9899-7d912d1deb83.png)
![image](https://user-images.githubusercontent.com/33612251/58261349-b8367600-7daa-11e9-989a-2f9c25793447.png)
![image](https://user-images.githubusercontent.com/33612251/58261429-e2883380-7daa-11e9-9ef2-ac096f316e74.png)
![image](https://user-images.githubusercontent.com/33612251/58261579-2a0ebf80-7dab-11e9-84b9-aa251b62993e.png)
![image](https://user-images.githubusercontent.com/33612251/58261702-65a98980-7dab-11e9-9535-e6469293a4d1.png)

**Comment by Galiarta** [comment]
![image](https://user-images.githubusercontent.com/33612251/58298705-ffeee900-7e0e-11e9-9d93-e75524f66deb.png)
![image](https://user-images.githubusercontent.com/33612251/58298847-9e7b4a00-7e0f-11e9-88d4-ff8f6365a81e.png)
![image](https://user-images.githubusercontent.com/33612251/58299097-8b1cae80-7e10-11e9-93ed-136f4fae8147.png)
![image](https://user-images.githubusercontent.com/33612251/58299186-e5b60a80-7e10-11e9-98f3-5a89b1597d27.png)
![image](https://user-images.githubusercontent.com/33612251/58299317-6ffe6e80-7e11-11e9-900c-ca9ba5bf79b6.png)
![image](https://user-images.githubusercontent.com/33612251/58299375-96bca500-7e11-11e9-852d-21da6ad35178.png)
![image](https://user-images.githubusercontent.com/33612251/58299560-24989000-7e12-11e9-90d5-aac856308278.png)
![image](https://user-images.githubusercontent.com/33612251/58299768-c8823b80-7e12-11e9-8fad-c150909ea856.png)
![image](https://user-images.githubusercontent.com/33612251/58299836-fb2c3400-7e12-11e9-9d97-3f09f85b8e63.png)
![image](https://user-images.githubusercontent.com/33612251/58299936-52ca9f80-7e13-11e9-95db-091380b7acea.png)
![image](https://user-images.githubusercontent.com/33612251/58300142-10559280-7e14-11e9-80ae-9dc6b03ef22b.png)

**Comment by Galiarta** [comment]
![image](https://user-images.githubusercontent.com/33612251/58302641-ce7e1980-7e1e-11e9-8ebd-62b1229ae3f4.png)
![image](https://user-images.githubusercontent.com/33612251/58302911-0df93580-7e20-11e9-81e0-02d6ef5a4cd1.png)
![image](https://user-images.githubusercontent.com/33612251/58302951-400a9780-7e20-11e9-8d52-21217563cc25.png)
![image](https://user-images.githubusercontent.com/33612251/58303051-dc349e80-7e20-11e9-8b3b-9c5aafc82e4b.png)
![image](https://user-images.githubusercontent.com/33612251/58303129-4e0ce800-7e21-11e9-970b-c227b0296ac2.png)

**Comment by Galiarta** [comment]
![image](https://user-images.githubusercontent.com/33612251/58367301-4f690e00-7f10-11e9-9ab8-cc63d13e33f6.png)
![image](https://user-images.githubusercontent.com/33612251/58367374-02396c00-7f11-11e9-9637-04c908c7472f.png)
![image](https://user-images.githubusercontent.com/33612251/58367395-4167bd00-7f11-11e9-9fc8-971f809da231.png)
![image](https://user-images.githubusercontent.com/33612251/58367418-9b688280-7f11-11e9-970e-2741849bf9e9.png)
![image](https://user-images.githubusercontent.com/33612251/58367577-7d9c1d00-7f13-11e9-9bc7-b94ee311c149.png)
![image](https://user-images.githubusercontent.com/33612251/58367589-a91f0780-7f13-11e9-8364-2bc466c0559e.png)
![image](https://user-images.githubusercontent.com/33612251/58367629-34000200-7f14-11e9-992d-93493ca98f09.png)
![image](https://user-images.githubusercontent.com/33612251/58367659-8a6d4080-7f14-11e9-9fad-967c311e19a3.png)
![image](https://user-images.githubusercontent.com/33612251/58367712-e637c980-7f14-11e9-86f3-ec4256ae5399.png)
![image](https://user-images.githubusercontent.com/33612251/58367843-a8d43b80-7f16-11e9-8eaf-293a4c554492.png)

**Comment by Galiarta** [comment]
![image](https://user-images.githubusercontent.com/33612251/58370109-3de62d00-7f35-11e9-8ebe-fa4ee840340e.png)
![image](https://user-images.githubusercontent.com/33612251/58370129-8aca0380-7f35-11e9-9727-fc537958dd20.png)
![image](https://user-images.githubusercontent.com/33612251/58370195-36735380-7f36-11e9-842e-262562f0676b.png)

**Comment by Galiarta** [comment]
![image](https://user-images.githubusercontent.com/33612251/58371344-0da58b00-7f43-11e9-9790-ebba97f8534b.png)
![image](https://user-images.githubusercontent.com/33612251/58371484-fd41e000-7f43-11e9-96fb-df51980d702f.png)
![image](https://user-images.githubusercontent.com/33612251/58371518-6b86a280-7f44-11e9-86f3-2682b1e8a648.png)
![image](https://user-images.githubusercontent.com/33612251/58371683-fae08580-7f45-11e9-9a3a-fd8aee4ac3c2.png)
![image](https://user-images.githubusercontent.com/33612251/58371716-4eeb6a00-7f46-11e9-8202-c68be280ee50.png)

**Comment by Galiarta** [comment]
![image](https://user-images.githubusercontent.com/33612251/58405002-085a5480-8099-11e9-94ee-dec589a8fbd9.png)
![image](https://user-images.githubusercontent.com/33612251/58405101-3f306a80-8099-11e9-9a22-cf6085a9f8d3.png)
![image](https://user-images.githubusercontent.com/33612251/58405174-70109f80-8099-11e9-95ee-640aaac14e60.png)
![image](https://user-images.githubusercontent.com/33612251/58405288-a77f4c00-8099-11e9-8b47-173f032c002f.png)
![image](https://user-images.githubusercontent.com/33612251/58405499-21afd080-809a-11e9-8c29-dac37e0d6d71.png)
![image](https://user-images.githubusercontent.com/33612251/58405583-5b80d700-809a-11e9-8ea7-9595eba64c89.png)
![image](https://user-images.githubusercontent.com/33612251/58405956-2c1e9a00-809b-11e9-8798-95778d73c6a4.png)
![image](https://user-images.githubusercontent.com/33612251/58406229-b8c95800-809b-11e9-9579-c95a8951ec5f.png)
![image](https://user-images.githubusercontent.com/33612251/58406505-50c74180-809c-11e9-8ab2-bcab2c92770d.png)
![image](https://user-images.githubusercontent.com/33612251/58406604-8c620b80-809c-11e9-94c9-823136bdff34.png)
![image](https://user-images.githubusercontent.com/33612251/58406658-af8cbb00-809c-11e9-8385-565ea9e1f128.png)
![image](https://user-images.githubusercontent.com/33612251/58406824-0e523480-809d-11e9-8a7d-8b2bb52edb69.png)
![image](https://user-images.githubusercontent.com/33612251/58406917-422d5a00-809d-11e9-9248-26a812f3c0cb.png)
![image](https://user-images.githubusercontent.com/33612251/58407170-c253bf80-809d-11e9-9610-3c4c7d0ebbc7.png)
![image](https://user-images.githubusercontent.com/33612251/58407255-ef07d700-809d-11e9-94e7-89d7f2c0df5a.png)
![image](https://user-images.githubusercontent.com/33612251/58407288-08a91e80-809e-11e9-98d5-019d4a794258.png)
![image](https://user-images.githubusercontent.com/33612251/58407381-3a21ea00-809e-11e9-951a-997c56cad1f3.png)
![image](https://user-images.githubusercontent.com/33612251/58422956-7ec17b80-80c6-11e9-9ba0-a49af18f9560.png)
![image](https://user-images.githubusercontent.com/33612251/58423015-afa1b080-80c6-11e9-9ea2-8655101c48d3.png)
![image](https://user-images.githubusercontent.com/33612251/58423080-d364f680-80c6-11e9-9f90-8e2dfb72c040.png)
![image](https://user-images.githubusercontent.com/33612251/58423204-1921bf00-80c7-11e9-88e3-37a4444eb7ed.png)
![image](https://user-images.githubusercontent.com/33612251/58423260-36ef2400-80c7-11e9-956f-51fab6c1c69d.png)
![image](https://user-images.githubusercontent.com/33612251/58423383-8afa0880-80c7-11e9-8e18-e3cb9b2e92d1.png)
![image](https://user-images.githubusercontent.com/33612251/58423418-a6fdaa00-80c7-11e9-8fc7-f1e492e8d134.png)
![image](https://user-images.githubusercontent.com/33612251/58423490-d90f0c00-80c7-11e9-893e-aa4d9ad254d9.png)
![image](https://user-images.githubusercontent.com/33612251/58423567-05c32380-80c8-11e9-8cdd-ae4375a8455c.png)

**Comment by uncu29** [comment]
![IMG_20190618_121114](https://user-images.githubusercontent.com/51182125/59655019-003a9400-91c3-11e9-8a39-837229c984d4.jpg)

**Comment by uncu29** [comment]
![IMG_20190618_121114](https://user-images.githubusercontent.com/51182125/59657500-1c423380-91cb-11e9-8e57-beeaaf5268e6.jpg)
![IMG_20190618_130021](https://user-images.githubusercontent.com/51182125/59657501-1d736080-91cb-11e9-81a1-9b5f1cba785c.jpg)
![IMG_20190618_130101](https://user-images.githubusercontent.com/51182125/59657509-219f7e00-91cb-11e9-9d58-479f081444ac.jpg)

**Comment by uncu29** [comment]
![IMG_20190618_121114](https://user-images.githubusercontent.com/51182125/59657881-3d575400-91cc-11e9-8883-614a519ba315.jpg)
![IMG_20190618_130021](https://user-images.githubusercontent.com/51182125/59657883-3defea80-91cc-11e9-92d4-5f6352a5b7cd.jpg)
![IMG_20190618_130101](https://user-images.githubusercontent.com/51182125/59657884-3e888100-91cc-11e9-9d8d-e3957d20c604.jpg)

**Comment by uncu29** [comment]
![IMG_20190619_124017](https://user-images.githubusercontent.com/51182125/59740346-077ca300-9292-11e9-8727-5c55c7f735d9.png)

**Comment by uncu29** [comment]
![Sistem Informasi Desa Desa Hibrida Jaya - Program Bantuan - Form 3 - Mozilla Firefox 28_06_2019 12 58 04](https://user-images.githubusercontent.com/51182125/60320806-11468a80-99a5-11e9-8990-0c086ff5f358.png)

**Comment by uncu29** [comment]
![Sistem Informasi Desa Desa Hibrida Jaya - Penduduk - Mozilla Firefox 09_07_2019 19 43 17](https://user-images.githubusercontent.com/51182125/60889218-c4a35f00-a282-11e9-96fe-94c5ed2c5934.png)
![Sistem Informasi Desa Desa Hibrida Jaya - Penduduk - Mozilla Firefox 09_07_2019 19 44 22](https://user-images.githubusercontent.com/51182125/60889219-c5d48c00-a282-11e9-809d-9f0781aa62d3.png)
![Sistem Informasi Desa Desa Hibrida Jaya - Penduduk - Mozilla Firefox 09_07_2019 19 45 03](https://user-images.githubusercontent.com/51182125/60889221-c66d2280-a282-11e9-9ed9-1e2c722ae02c.png)

**Comment by uncu29** [comment]
![IMG_20190719_202117](https://user-images.githubusercontent.com/51182125/61541119-3b9ddc00-aa69-11e9-97a4-880ceff82d2c.png)
![IMG_20190719_202806](https://user-images.githubusercontent.com/51182125/61541120-3b9ddc00-aa69-11e9-8cfd-11fcf264d669.png)
![IMG_20190719_205436](https://user-images.githubusercontent.com/51182125/61541122-3d679f80-aa69-11e9-9aa4-c78a68124c21.jpg)
![IMG_20190719_210240](https://user-images.githubusercontent.com/51182125/61541123-3e003600-aa69-11e9-90d2-7d3bdee0630a.jpg)

**Comment by uncu29** [comment]
![Microsoft Excel - format_bip_2016_luwutimur   Compatibility Mode  20_07_2019 22 00 27](https://user-images.githubusercontent.com/51182125/61580259-162cd300-ab3a-11e9-99b7-9f74bf6a4a46.png)
![Microsoft Excel - format_bip_2016_luwutimur   Compatibility Mode  20_07_2019 22 01 07](https://user-images.githubusercontent.com/51182125/61580261-162cd300-ab3a-11e9-989b-68bbcf798a5f.png)
![Microsoft Excel - format_bip_ektp   Compatibility Mode  20_07_2019 21 57 53](https://user-images.githubusercontent.com/51182125/61580262-16c56980-ab3a-11e9-95fb-93b0b22b7caa.png)

**Comment by uncu29** [comment]
![bip](https://user-images.githubusercontent.com/51182125/61580775-9e61a700-ab3f-11e9-8bf5-4844731d4b53.png)

**Comment by uncu29** [comment]
![impor 5](https://user-images.githubusercontent.com/51182125/61586138-28892a00-ab97-11e9-915d-440117a57b42.png)

**Comment by HerryWanda** [comment]
![Informasi Publik](https://user-images.githubusercontent.com/32125282/67658920-9eb6dd00-f98d-11e9-8912-19ee1b38dfec.jpg)

**Comment by HerryWanda** [comment]
![hapus](https://user-images.githubusercontent.com/32125282/68104843-37f66e00-ff0f-11e9-9c2a-42c3fe5bc9ce.jpg)

**Comment by uncu29** [comment]
![modul](https://user-images.githubusercontent.com/51182125/68497028-34077a80-0286-11ea-9d82-b18ab8894a42.jpg)

**Comment by uncu29** [comment]
![Sistem Informasi Desa Kampung Hibrida Jaya - Hom Desa - Konfigurasi - Google Chrome 12 Nov 2019 22 37 35](https://user-images.githubusercontent.com/51182125/68685707-1c3d3880-059d-11ea-858b-727532e23ea8.png)
![Untitled-2](https://user-images.githubusercontent.com/51182125/68687238-79d28480-059f-11ea-86ca-b782bf0203f2.jpg)

**Comment by uncu29** [comment]
![Untitled-3](https://user-images.githubusercontent.com/51182125/68695426-97a6e600-05ad-11ea-935e-e05bb7dcae32.jpg)

**Comment by uncu29** [comment]
![Untitled-6](https://user-images.githubusercontent.com/51182125/68836288-95977100-06ec-11ea-9c14-a69f33d22687.jpg)
![Untitled-7](https://user-images.githubusercontent.com/51182125/68836725-8fee5b00-06ed-11ea-99ba-e62a4453e542.jpg)

**Comment by uncu29** [comment]
![Untitled-14](https://user-images.githubusercontent.com/51182125/68841941-17d96280-06f8-11ea-9005-e2a9efabf0b7.jpg)

**Comment by HerryWanda** [comment]
![issue Informasi Publik](https://user-images.githubusercontent.com/32125282/71573672-b76f7a80-2b17-11ea-9b1f-fd0251d379ca.jpg)

**Comment by HerryWanda** [comment]
![sekretaria](https://user-images.githubusercontent.com/32125282/71574110-dbcc5680-2b19-11ea-8fb8-8a1c13b969b8.jpg)

**Comment by HerryWanda** [comment]
![ER](https://user-images.githubusercontent.com/32125282/71574489-78432880-2b1b-11ea-85cf-348d6c0b5ffa.jpg)

**Comment by HerryWanda** [comment]
![AART](https://user-images.githubusercontent.com/32125282/71574611-159e5c80-2b1c-11ea-8d64-b73d0bee0b7e.jpg)

**Comment by HerryWanda** [comment]
![Halaman Layanan Mandiri](https://user-images.githubusercontent.com/32125282/73812730-73575000-4810-11ea-9407-2db75bc7177e.jpg)

**Comment by HerryWanda** [comment]
![Layanan Mandiri](https://user-images.githubusercontent.com/32125282/73812935-1b6d1900-4811-11ea-917d-0a8cabc82767.jpg)

**Comment by HerryWanda** [comment]
![Layanan Mandiri](https://user-images.githubusercontent.com/32125282/73813147-b2d26c00-4811-11ea-8ced-ff516d43f08d.jpg)

**Comment by HerryWanda** [comment]
![permohonan surat](https://user-images.githubusercontent.com/32125282/73813398-73584f80-4812-11ea-8257-5887e46fe785.jpg)

**Comment by HerryWanda** [comment]
![Halaman Layanan Mandiri](https://user-images.githubusercontent.com/32125282/73813505-c5997080-4812-11ea-90dc-db024f419f8c.jpg)

**Comment by HerryWanda** [comment]
![lay mandiri](https://user-images.githubusercontent.com/32125282/73813777-9c2d1480-4813-11ea-9f83-260b71e9723b.jpg)

**Comment by HerryWanda** [comment]
![hasilkan pin](https://user-images.githubusercontent.com/32125282/73813884-fb8b2480-4813-11ea-8392-61c4960450e9.jpg)

**Comment by HerryWanda** [comment]
![pin](https://user-images.githubusercontent.com/32125282/73813904-0e055e00-4814-11ea-9dac-ded9ec658b3b.jpg)

**Comment by HerryWanda** [comment]
![pin hasil](https://user-images.githubusercontent.com/32125282/73813952-342afe00-4814-11ea-9132-e8b206533867.jpg)

**Comment by HerryWanda** [comment]
![hadekawa](https://user-images.githubusercontent.com/32125282/73814169-d3e88c00-4814-11ea-9e6e-a39f640e5d64.jpg)

**Comment by HerryWanda** [comment]
![pilih surat](https://user-images.githubusercontent.com/32125282/73814454-b7008880-4815-11ea-9568-eb9b05d83984.jpg)

**Comment by HerryWanda** [comment]
![SYARAT DOKUMEN](https://user-images.githubusercontent.com/32125282/73814712-6fc6c780-4816-11ea-8994-be00521112ea.jpg)

**Comment by HerryWanda** [comment]
![KLIK ISI](https://user-images.githubusercontent.com/32125282/73814938-0abfa180-4817-11ea-99f6-76cd17e51e42.jpg)

**Comment by HerryWanda** [comment]
![KIRIM](https://user-images.githubusercontent.com/32125282/73815354-49a22700-4818-11ea-809f-438e9fa65372.jpg)

**Comment by HerryWanda** [comment]
![NOTIFIKASI](https://user-images.githubusercontent.com/32125282/73815880-d7cadd00-4819-11ea-8f61-ec9085ea3014.jpg)

**Comment by HerryWanda** [comment]
![NOTIFIKASI2](https://user-images.githubusercontent.com/32125282/73816015-237d8680-481a-11ea-951f-24fe017abbc2.jpg)

**Comment by HerryWanda** [comment]
![kelengkapan dokumen](https://user-images.githubusercontent.com/32125282/73816223-b0c0db00-481a-11ea-9c7d-2a5f5e433cb7.jpg)

**Comment by HerryWanda** [comment]
![sambungan-](https://user-images.githubusercontent.com/32125282/73816302-e4036a00-481a-11ea-95d5-b7912728dc9f.jpg)

**Comment by HerryWanda** [comment]
![CETAKSURAT](https://user-images.githubusercontent.com/32125282/73816422-2dec5000-481b-11ea-9a44-3d12036dba40.jpg)

**Comment by HerryWanda** [comment]
![lengkap](https://user-images.githubusercontent.com/32125282/73816510-65f39300-481b-11ea-9252-dbe77104e42f.jpg)

**Comment by HerryWanda** [comment]
![lm](https://user-images.githubusercontent.com/32125282/77605164-d7f87680-6f46-11ea-967a-9e9fd514b06a.jpg)

**Comment by HerryWanda** [comment]
![st](https://user-images.githubusercontent.com/32125282/79207070-69824680-7e6a-11ea-8d04-0c0f93273e4d.jpg)

**Comment by HerryWanda** [comment]
![r](https://user-images.githubusercontent.com/32125282/88263380-2ac71c80-ccf4-11ea-8427-258804ab5a16.jpg)

**Comment by HerryWanda** [comment]
![kd](https://user-images.githubusercontent.com/32125282/88263711-a6c16480-ccf4-11ea-87d7-eb5b29911135.jpg)

**Comment by eddieridwan** [comment]
@HerryWanda untuk memasukkan gambar di issue langsung saja di issue ybs. Gambar yg di issue ini khusus untuk panduan wiki -- karena di wiki tidak ada cara untuk langsung unggah gambar ke wiki.

**Comment by HerryWanda** [comment]
Ok pak
