### ISSUE TITLE
[Bug] Menghapus Data KK seharusnya ikut terhapus juga data KK di analisis

### ISSUE THREAD

**Issue by WAHAB01** [OpenSID/OpenSID#1685]
Ketika menghapus Data Kepala Keluarga, Data Kepala Keluarga di Analisis KK tidak ikut terhapus. Diharapkan data Kepala Keluarga di Analisis KK juga ikut terhapus sehingga Data Kepala keluarga akan tampil normal di halaman Utama/Home.

**Comment by eddieridwan** [comment]
@WAHAB01 harap masalahnya diperjelas. Apakah yg dimaksud jumlah keluarga yg ditampilkan di halaman berikut? Atau yg lain?

![jml-keluarga](https://user-images.githubusercontent.com/249563/46714435-2f4d4d00-cca7-11e8-8c2a-196f639d2654.jpg)

Yang ditampilkan adalah jumlah Keluarga, bukan jumlah orang yg berstatus Kepala Keluarga. Untuk menghapus Keluarga, lakukan di halaman Keluarga (bukan halaman Penduduk). 

Kalau orang yg berstatus kepala keluarga dihapus di halaman Penduduk, jumlah Keluarga yg ditampilkan di halaman muka tidak akan berubah, karena Keluarga itu masih ada. Bisa saja Keluarga itu belum sempat diisikan data kepala keluarganya.

**Comment by WAHAB01** [comment]
Iya, masalahnya seperti yg Bapak tunjukan di atas,,,

**Comment by eddieridwan** [comment]
Kalau begitu bukan bug. Yang mungkin dapat dilakukan adalah penjelasan yg lebih lengkap di panduan, mengenai perbedaan menghapus Keluarga dan menghapus penduduk yang berstatus Kepala Keluarga.

Ok, issue ini kami tutup. Mudah2an ada yg bersedia melengkapi panduan.

**Comment by eddieridwan** [comment]
Ok, sekarang halaman _Home > SID_ menampilkan jumlah keluarga dengan KK berstatus dasar 'HIDUP' saja. Jadi tidak menghitung keluarga yang KK-nya kosong atau hilang/mati/pindah.

Sudah dicommit ke master.
