### ISSUE TITLE
[Bug] Arsip Layanan hasilnya kosong

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#1687]
### Bagaimana alurnya sampai muncul masalah?
Ketika Buka Arsip Layanan terkadang hasilnya kosong seperti gambar dibawah ini
![screenshot 2018-09-18 10 30 42](https://user-images.githubusercontent.com/25834335/45660939-d10cce80-bb2d-11e8-95ec-6d4496972e8f.png)

### Seperti apa yang diharapkan?
Surat yang sudah dicetak di arsip layanan berjalan normal seperti versi sebelumnya

### Apa yang terjadi?
tidak bisa melihat data arsip layanan

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by balongbesuk** [comment]
sepertinya pencarian penduduk ada yang "nyantol" di arsip layanan, saya pernah mengalami waktu develop modernisasi, tapi mau dilaporkan eror tersebut hilang, 

muncul error tersebut ketika operator di pencarian penduduk / keluarga kemudian melompat ke arsip layanan, arsip layanan akan menampilkan halaman kosong,

**Comment by eddieridwan** [comment]
Masalah ini disebabkan session variable belum dihapus sebelum menampilkan Arsip Layanan.
Solusinya adalah dengan mengubah URL pemanggilan modul _Arsip Layanan_ dari `keluar` menjadi `keluar/clear`. Lakukan perubahan ini sebagai bagian dari migrasi DB.

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
