### ISSUE TITLE
Bantu pengguna koneksi ke database pada waktu install awal

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#1688]
### Bagaimana alurnya sampai muncul masalah?
1. install OpenSID tetapi belum menyiapkan `desa/config/database.php` dengan benar
2. coba jalankan OpenSID

### Seperti apa yang diharapkan?
Sistem membantu pengguna menyiapkan koneksi ke database. Lihat PR #1547 dan pembahasan di https://opensid.slack.com/messages/C6AJT8T9S/details/

![diskusi-cek-db](https://user-images.githubusercontent.com/249563/45853614-c2225800-bd89-11e8-8aa9-5ece521b0f9a.jpg)

### Apa yang terjadi?
Sekarang tampil error koneksi DB.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | v18.09
| Versi PHP        | 
| System operasi   |

**Comment by rizalblue** [comment]
Apa yg dimaksud contohnya seperti installasi wordpress ? pengguna tinggal memasukkan parameter yg diperlukan tanpa edit filenya.

**Comment by afa28** [comment]
Pak @eddieridwan , apakah sudah sesuai dgn alur script installer yg sy buat??

**Comment by eddieridwan** [comment]
Bung @afa28 , pindahkan/salin repo anda ke Github OpenSID. Kalau sudah dipindahkan, issue ini bisa ditutup.

**Comment by afa28** [comment]
> Bung @afa28 , pindahkan/salin repo anda ke Github OpenSID. Kalau sudah dipindahkan, issue ini bisa ditutup.

Sudah sy fork ke OpenID pak
