### ISSUE TITLE
ERROR Tambah anggota keluarga dari penduduk yang sudah ada melalui menu keluarga

### ISSUE THREAD

**Issue by Gunturwijay** [OpenSID/OpenSID#1689]
Bagaimana alurnya sampai muncul masalah?### Menu Keluarga>Rincian Anggota Keluarga (KK)>Tambah Anggota Keluarga

Seperti apa yang diharapkan?### diharapkan dapat menambah dari penduduk yang sudah ada

Apa yang terjadi?### tidak dapat menambah penduduk dari penduduk yang sudah ada

### Informasi tambahan 
![image](https://user-images.githubusercontent.com/40741591/45913423-4cd38780-be5c-11e8-9a34-1fa9971c9a89.png)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

>

**Comment by balongbesuk** [comment]
pastikan anggota keluarga yang akan ditambahkan sudah lepas dari KK keluarga lama,

**Comment by eddieridwan** [comment]
Seperti dijelaskan oleh @balongbesuk, masalah ini bukan error.
Penduduk yang bisa ditambahkan hanya yang belum menjadi anggota keluarga, yaitu no_kk nya kosong. Sama halnya seperti penambahan kepala keluarga baru yang dijelaskan di https://github.com/OpenSID/OpenSID/wiki/Pengisian-Data-Keluarga.

Memang panduan belum lengkap, dan juga perlu diperbaharui. 

Silakan teman2 ikut bantu memperbaharui dan melengkapi panduan.

Issue ini akan kami tutup.

**Comment by Gunturwijay** [comment]
terima kasih pak @eddieridwan, sekarang saya sudah mengerti

**Comment by eddieridwan** [comment]
@Gunturwijay , supaya lebih jelas sekarang di form tambah KK dan form tambah anggota KK telah ditambah keterangan. Silakan lihat di http://beta.opensid.info. Sudah ada di versi pra-rilis.
