### ISSUE TITLE
[bug] error 500 saat menambahkan peserta bantuan raskin

### ISSUE THREAD

**Issue by metalab25** [OpenSID/OpenSID#1691]
### Bagaimana alurnya sampai muncul masalah?
Saat akan mencoba menambah peserta bantuan raskin , saat pilih NIK/Penduduk langsung diredirect ke halaman error 500 (gambar terlampir)
![screenshot_182](https://user-images.githubusercontent.com/19917739/45918598-f302aa00-bebb-11e8-8cb6-fbd7b250e486.png)

![screenshot_180](https://user-images.githubusercontent.com/19917739/45918586-cd75a080-bebb-11e8-83fd-bd08daba6791.png)
namun setelah saya back browsernya penduduk yang di pilih tetap terisi
![screenshot_183](https://user-images.githubusercontent.com/19917739/45918608-0d3c8800-bebc-11e8-8807-5d80f5fdc19a.png)

### Seperti apa yang diharapkan?
tidak terjadi atau tidak diredirect ke halaman error 500

### Apa yang terjadi?
tidak terjadi atau tidak diredirect ke halaman error 500

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 18.09
| Versi PHP        |  5.6.30
| System operasi   | Windows 10

**Comment by metalab25** [comment]
Siap sesegera mungkin akan saya kirimkan. Bwt ini offline yah

**Comment by eddieridwan** [comment]
Terima kasih. Ternyata masalah ini hanya terjadi pada server tertentu.
Sudah diperbaiki di versi pra-rilis.
