### ISSUE TITLE
[Bug] Cetak Kartu Keluarga dengan mencentang beberapa kepala keluarga

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#1697]
### Bagaimana alurnya sampai muncul masalah?
Cetak Kartu Keluarga dengan mencentang beberapa kepala keluarga dengan mengklik aksi data terpilih konfirmasi yang muncul salah seperti gambar dibawah ini
![image](https://user-images.githubusercontent.com/25834335/45964735-31819b80-c059-11e8-9bc9-795f695cdfa8.png)
![cetak kk al](https://user-images.githubusercontent.com/25834335/45964796-4f4f0080-c059-11e8-82f9-1ad834294fa9.png)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by metalab25** [comment]
sebenarnya simplenya diganti dengan "Apakah Anda yakin ingin melakukan aksi pada data ini?"

**Comment by MUHAMMADRANGSEL** [comment]
Ya mas happy saya sendiri bisa sih ganti hanya saja perlu diperbaiki yang di github supaya ketika rilis besok tdk terdapat lagi masih yang sama

**Comment by eddieridwan** [comment]
@MUHAMMADRANGSEL heheh... sepertinya terlewat pada waktu kita ramai2 melakukan testing hasil kerja kontraktor -- karena memang sedikit sekali teman2 yg ikut testing. Jadi pasti masih ada beberapa masalah seperti ini yg akan muncul.

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
