### ISSUE TITLE
Tidak Tahu Password Mengelola Situs Desa

### ISSUE THREAD

**Issue by MuhammadRapii** [OpenSID/OpenSID#1698]
Saya staff baru di Desa, Saya diberi tugas untuk mengisi web desa, tetapi password yang diberikan tidak bisa masuk ke open sid. kemarin webnya dibuatkan oleh Mahasiswa KKN. sudah dihubungi passwordnya tetap tidak bisa. Tolong beritahu saya cara untuk mendapatkan kembali password web desa saya.

**Comment by eddieridwan** [comment]
@MuhammadRapii issue digunakan untuk melaporkan bug/usulan untuk diperbaiki/dikerjakan.

Seperti dijelaskan pada template pada waktu anda membuat issue, masalah penggunaan silakan tanyakan di https://www.facebook.com/groups/OpenSID/ atau di WA https://bit.ly/opensid-whatsapp.  Banyak yg bisa bantu di situ.

Ok, kami akan tutup issue ini.
