### ISSUE TITLE
#surat jenis suami istri

### ISSUE THREAD

**Issue by afri18** [OpenSID/OpenSID#170]
saya mencoba membuat surat sejenis [surat_persetujuan_mempelai] , pertama dibuat seperti surat pengantar/penduduk, lalu saya gantikan isinya dengan [surat_persetujuan_mempelai].
hambatan : 
saat dipanggil muncul, hanya saja nggak bisa menginput data suami kenapa ya ?
![image](https://cloud.githubusercontent.com/assets/6611881/19441210/0dc8e28e-94af-11e6-90a0-2cd1edc419ad.png)

**Comment by MUHAMMADRANGSEL** [comment]
Itu disebabkan kqrna belum ditqmbahkan disurat model.php sbg alat tuk memanggilnya tp bisa dibuat hanya memasukkan nama suami nanti nama istri secara otomatis terisi di exportnya
