### ISSUE TITLE
lama untuk mengakses layanan mandiri

### ISSUE THREAD

**Issue by hansahdarmawan** [OpenSID/OpenSID#1700]
### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by balongbesuk** [comment]
itu tergantung hosting pak, bukan aplikasinya

**Comment by hansahdarmawan** [comment]
m

**Comment by hansahdarmawan** [comment]
mohon maaf issue ini bukan dibuat oleh saya., tadi ada yg bajak laptop saya oleh rekan
