### ISSUE TITLE
[Bug] Simbol Tipe Lokasi tidak muncul setelah Kosongkan DB

### ISSUE THREAD

**Issue by hirudi** [OpenSID/OpenSID#1702]
### Bagaimana alurnya sampai muncul masalah?
Error terjadi setelah Kosongkan DB... symbol2 peta tidak muncul

![ss3](https://user-images.githubusercontent.com/4936934/46567110-d99b3c80-c956-11e8-81d5-d059343cd1d1.jpg)

![ss1](https://user-images.githubusercontent.com/4936934/46567113-e455d180-c956-11e8-9d7b-ee1dc98c7bd3.jpg)

![ss2](https://user-images.githubusercontent.com/4936934/46567116-ec157600-c956-11e8-87a2-0d5e2ee27842.jpg)

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.

**Comment by hirudi** [comment]
Setelah kami coba issue ini masih terjadi..

**Comment by eddieridwan** [comment]
@hirudi : apakah sudah restore dulu database asli? 

Perbaikan yg dilakukan tidak mengembalikan data yg sdh terhapus. Perbaikan yg dilakukan adalah supaya Kosongkan DB sekarang tidak lagi menghapus data gis simbol.

Kalau data gis simbol anda sudah terhapus sebelumnya, perlu dikembalikan dengan melakukan Pengaturan > Database > Restore ke database sebelumnya.

**Comment by hirudi** [comment]
Sudah sy coba fresh install pak, dan menemukan masalah sbb:
1. Import database -> Impor Data Kependudukan jadi bermasalah ..
2. Backup/Restore -> Restore Database SID error menjadi HTTP ERROR 500

Perlu testing ulang di menu Expor/Impor database
