### ISSUE TITLE
[Bug] Gambar yg diupload melalui editor artikel tampil salah

### ISSUE THREAD

**Issue by ZulIhwandi** [OpenSID/OpenSID#1704]
Harap untuk untuk di perbaiki halkaman artikel publik  yang posisi gambarnya tidak bisa di tengah dan tidak bisa tampin tampil gambar tersebut.

https://web.facebook.com/photo.php?fbid=1863860277065488&set=pcb.1082814808550166&type=3&theater&ifg=1

seharusnya pas kita buat artikel saat tampilan pubik nya sesui seperti yang kita ingin kan seperti tampil seperti di halam pegeditan artikel

![a](https://user-images.githubusercontent.com/34672169/46570070-f2244a80-c988-11e8-8aa0-922848ce2bb0.png)
![b](https://user-images.githubusercontent.com/34672169/46570072-f8b2c200-c988-11e8-9d9a-a9725b630fc0.png)
![c](https://user-images.githubusercontent.com/34672169/46570075-ff413980-c988-11e8-8822-5ab80fb6a786.png)

**Comment by eddieridwan** [comment]
@ZulIhwandi : 

1. masalah gambar tidak muncul bukan bug. Cek folder `desa/upload/media` dan `desa/upload/thumbs` sudah dibuat di server anda.
2. penampilan gambar sekarang sudah dibuat standar, supaya sesuai dengan setting di form isian artikel. Perbaikan ini sudah bisa digunakan di versi pra-rilis (https://github.com/OpenSID/OpenSID/wiki/Unduh-script-OpenSID).
3. penampilan gambar bisa diatur di form isian artikel, dengan mengubah setting _styles_, seperti terlihat di gambar berikut.

![style-gambar-artikel](https://user-images.githubusercontent.com/249563/46713554-075bea80-cca3-11e8-90bf-1d4eabf29621.jpg)

**Comment by ZulIhwandi** [comment]
ok bang eddie terimaksih informasi nya

Pada tanggal Rab, 10 Okt 2018 pukul 11.45 Eddie Ridwan <
notifications@github.com> menulis:
