### ISSUE TITLE
[Database] Sesuaikan Format Unduhan Data Penduduk dengan Format BIP 2016

### ISSUE THREAD

**Issue by WAHAB01** [OpenSID/OpenSID#1706]

**Comment by eddieridwan** [comment]
@WAHAB01 : harap beri penjelasan lebih rinci apa yg diinginkan. Apakah yg diinginkan fitur untuk mengunduh data penduduk dalam format BIP? Mengapa fitur ini dibutuhkan?

**Comment by WAHAB01** [comment]
Iy sperti itu, 
Agar data pendduk tersusun dengan baik, dimulai dengan susunan Kepala Keluarga, Istri kemudian anak pertama dan selanjutnya. Klo sprti yg sekarng susunan keluarganya msih acak,,
