### ISSUE TITLE
Unable to locate the specified class: Session.php

### ISSUE THREAD

**Issue by dbudihartono** [OpenSID/OpenSID#1708]
saya menemukan kendala Unable to locate the specified class: Session.php pada saat update versi 18.10 dengan rilis 2.12 opensid rbac

**Comment by eddieridwan** [comment]
@dbudihartono : vers 18.10 lebih terkini dari versi 2.12. Database yg digunakan v18.10 berbeda dgn v2.12. Migrasi DB hanya berfungsi naik versi (2.12 -> 18.10), tidak bisa digunakan untuk mundur versi.

Mengapa anda ingin mundur ke v2.12?

**Comment by eddieridwan** [comment]
Karena masalah ini sepertinya bukan bug, kami tutup. Kalau ada informasi tambahan, silakan dibuka kembali.
