### ISSUE TITLE
[Bug] Tanggal Lahir Unduh excel Penduduk berbeda Format

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#1709]
### Bagaimana alurnya sampai muncul masalah?
Kependudukan > Penduduk > Pilih aksi lain > Unduh

### Seperti apa yang diharapkan?
sesuaikan format

### Apa yang terjadi?
Bulan November tertulis panjang tidak seperti yang lain yang tersingkat 

### Informasi tambahan 
![wee](https://user-images.githubusercontent.com/35319600/46918135-52099980-cff8-11e8-9d79-e38ee5deada4.jpg)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by rizalblue** [comment]
Saya sudah mengerjakan issue ini, bagaimana caranya saya melakukan pull request ? @eddieridwan

**Comment by eddieridwan** [comment]
@balongbesuk : Di v18.10, _Kependudukan > Penduduk / Keluarga > Unduh_ menghasilkan laporan seperti di gambar berikut. Format ini berbeda dgn yg anda laporkan di issue ini. Apakah anda membuat versi ubahan sendiri? Atau ada di menu lain?

**Comment by balongbesuk** [comment]
maaf saya ralat pak eddie tanggal lahir pada format unduhan excel penduduk format bulan november berbeda dengan format bulan lain, 

keluarga tidak menampilkan tanggal lahir

**Comment by eddieridwan** [comment]
@balongbesuk , masalah ini tidak ditemukan di http://beta.opensid.info. Data tanggal terekspor dalam format _yyyy/mm/dd_ . Tetapi untuk lebih pasti, sekarang semua tanggal diekspor dalam format _yyyy-mm-dd_ untuk memudahkan impor kembali.

Sudah dicommit ke master.

**Comment by balongbesuk** [comment]
apakah sudah masuk pada beta.opensid.info ? 

karena saya coba masih tidak ada perubahan

penduduk > pilih aksi lain > unduh

![untitled2221](https://user-images.githubusercontent.com/35319600/46931857-2bd70e80-d077-11e8-9e6f-b036ba8bbfc5.jpg)

**Comment by eddieridwan** [comment]
@balongbesuk : ooh di situ. Yang diperbaiki yang Pengaturan > Database > Expor Database > Ekspor Data Keluarga. Makanya, pada waktu membuat issue harus selalu tampilkan secara jelas alur terjadinya masalah. Kalau tidak mudah salah tafsir, dan yg lain yg dikerjakan. Mohon diperhatikan pada issue2 selanjutnya.

**Comment by balongbesuk** [comment]
alurnya sudah saya tuliskan dengan jelas pada bagian "Bagaimana alurnya sampai muncul masalah?" pak eddie

**Comment by eddieridwan** [comment]
@balongbesuk heheh.... itu saya yg tambahkan setelah anda jelaskan di atas... sebelumnya data keluarga. Tapi terima kasih. Dan sepertinya sudah diperbaiki oleh @rizalblue

**Comment by balongbesuk** [comment]
oya pak maaf perasaan saya juga sempat saya tambahkan penduduk / keluarga ternyata bapak sendiri yang edit sudah mengeditnya, terimakasih, (mohon maaf sewaktu melaporkan tidak mengecek yang versi unduh excel keluarga)

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR #1710.
