### ISSUE TITLE
Mengubah Footer Untuk Pengguna

### ISSUE THREAD

**Issue by buchary** [OpenSID/OpenSID#171]
Boleh atau tidak kita tambah kan seperti gambar berikut di footernya.. Kalau kita tambahkan, apakah akan berpengaruh pada saat update release terbaru.. Terima Kasih
![screen](https://cloud.githubusercontent.com/assets/20512335/19543172/e449bf46-96a7-11e6-839b-88bf0c568f9d.png)

**Comment by batudaa** [comment]
Tambahkan saja. Kalau ada rilis baru dan tulisan itu hilang, ditambahkan saja lagi,,, :)

**Comment by MUHAMMADRANGSEL** [comment]
Menurut kami issue ini ditutup saja

**Comment by agungsugiarto** [comment]
Pak @dedy85 untuk menanyakan hal tersebut silahkan lakukan di grup telegram atau di grup facebook. Issue ditujukan hanya untuk masalah bug / permintaan fitur baru. Terima kasih
