### ISSUE TITLE
Kop surat

### ISSUE THREAD

**Issue by sukrimalendra** [OpenSID/OpenSID#1711]
Bisakah kop suratnya seperti digambar ini
![e0e7d7f7-ec9e-46e1-bd66-307e48e62870](https://user-images.githubusercontent.com/30992964/46928104-705cad00-d06b-11e8-8fab-af3673071843.jpeg)

**Comment by MUHAMMADRANGSEL** [comment]
Silahkan rubah di surat.rtf nya

**Comment by MUHAMMADRANGSEL** [comment]
Karena kita fokus di export bukan cetak

**Comment by balongbesuk** [comment]
Bisa diedit dan disesuaikan di surat .rtf nya pak

**Comment by sukrimalendra** [comment]
Baik. Terimakasih

**Comment by ariandii** [comment]
Closed
