### ISSUE TITLE
layanan mandiri tidak memiliki fungsi bagi pengguna yang lupa pasword

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#1712]
### Bagaimana alurnya sampai muncul masalah?
Layanan Mandiri > pendaftaran Layanan Mandiri

### Seperti apa yang diharapkan?
user terdaftar ketika lupa pasword, admin dapat mereset / membuatkan pasword baru

### Apa yang terjadi?
untuk saat ini ketika terdapat user layanan mandiri yang lupa pasword, mengharuskan admin menghapus user tersebut dan membuatkan ulang user tersebut dengan pin baru, 

### Informasi tambahan 
Pendapat pribadi > tombol reset password ( yang menghasilkan pin secara acak / pin default misal "123456" ) disamping tombol hapus

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by suphm** [comment]
opsi lain ditambah kontak email/hp bisa reset password sendiri

**Comment by mojosar** [comment]
saya pengguna openSID dengan website : sumbersono.com
saya ingin di website saya , setelah user membuka web, dan memasukan nomor NIK serta pasword nya, user bisa masuk menu layanan dan yang saya inginkan adalah menambah sub menu cetak surat.
jadi user yang sudah masuk bisa membuat surat sendiri tanpa harus datang ke operator

**Comment by mojosar** [comment]
tolong bisa dikoneksikan ke layanan cetak surat ya. makasih

**Comment by happyagung25** [comment]
> saya pengguna openSID dengan website : sumbersono.com
> saya ingin di website saya , setelah user membuka web, dan memasukan nomor NIK serta pasword nya, user bisa masuk menu layanan dan yang saya inginkan adalah menambah sub menu cetak surat.
> jadi user yang sudah masuk bisa membuat surat sendiri tanpa harus datang ke operator

buat isssue sendiri dan kalo bisa buat permintaan yang berkaitan sama banyak pengguna

**Comment by afa28** [comment]
Sudah dicommit ke `master `melalui PR #2902
