### ISSUE TITLE
[Bug] Impor BIP Penduduk

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#1715]
### Bagaimana alurnya sampai muncul masalah?
Pengaturan > Database > import File BIP penduduk Excel

### Seperti apa yang diharapkan?
Letak Data Baris Gagal tidak memunculkan baris error BIP
Total Data berhasil Di Impor memunculkan jumlah total

### Apa yang terjadi?
Letak Data Baris Gagal tidak memunculkan pesar error
Total Data berhasil Di Impor tidak memunculkan jumlah total

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
@balongbesuk , harap jelaskan/lampirkan:
1. OpenSID versi berapa?
2. Format BIP yang mana (ada beberapa format)
3. Lampirkan screenshot laporan hasil impor

**Comment by eddieridwan** [comment]
#1715: Sekarang impor BIP menampilkan jumlah keluarga dan penduduk yang berhasil diimpor. Juga sekarang gagal impor apabila kode tulisan yang diisi salah. [bug-fix]

Sudah dicommit ke master.
