### ISSUE TITLE
Ganti library pembaca file Excel supaya bisa membaca Excel 2007 (.xslx)

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#1718]
### Bagaimana alurnya sampai muncul masalah?
Gunakan fitur impor Excel, seperti _Pengaturan > Database > Impor BIP_.
Coba baca file Excel dengan format 2007+, dengan extensi .xslx.

### Seperti apa yang diharapkan?
File Excel dengan format 2007+, dengan extensi .xslx, berhasil diimpor.

### Apa yang terjadi?
Di v18.10 file Excel format 2007+, dengan extensi .xlsx, tidak bisa diimpor.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | v18.10
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Contoh library yg bisa membaca Excel 2007: https://github.com/shuchkin/simplexlsx

**Comment by afa28** [comment]
Sudah di `master`
