### ISSUE TITLE
Di Rincian data Suplemen perlu menampilkan Tempat dan Tanggal lahir

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#1719]
### Bagaimana alurnya sampai muncul masalah?
tempat dan tanggal lahir belum ada di Rincian Data Suplemen baik Penduduk maupun Keluarga
![image](https://user-images.githubusercontent.com/25834335/47250778-792df400-d45a-11e8-9dfb-747e4879f809.png)

### Seperti apa yang diharapkan?
memunculkan tempat dan tanggal lahir di Rincian data suplemen sehingga ketika mau print data lebih enak dan akurat apalagi dengan kita lakukan verifikasi menggunakan KK dan KTP Lebih Enak
![image](https://user-images.githubusercontent.com/25834335/47250769-2b18f080-d45a-11e8-969e-b58e238c999c.png)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR #1833.
