### ISSUE TITLE
DI BUTUHKAN SURAT PERMOHONAN KARTU KELUARGA BARU UNTUK ORANG YG BARU MENIKAH

### ISSUE THREAD

**Issue by ZulIhwandi** [OpenSID/OpenSID#1720]
ISI Data penduduk desa setemapt dan isi data dari luar desa
karna bisajadi istri nya dari luar desa dan bisajadi dari satu desa tersebut,

![permohanan-kk](https://user-images.githubusercontent.com/249563/47480331-3027d680-d884-11e8-8cb6-0d9a064fe0d7.png)

**Comment by MUHAMMADRANGSEL** [comment]
Silahkan pakai format F1. 01 pak

**Comment by MUHAMMADRANGSEL** [comment]
Yang dicari dukcapil dan kecamatan adalah pengantar kartu keluarga form F1. 01 silahkan buka di lampiran surat pengantar KK

**Comment by balongbesuk** [comment]
Pengajuan KK format baru? / sudah terbiasa pengajuan dengan model surat KK seperti itu? Bisa diakali dengan mengedit format di cetak KK,

"Istri dari luar desa" dibuatkan KK? kenapa tidak pindah masuk? Apakah hal ini tidak menggandakan data "istri" tersebut?

**Comment by eddieridwan** [comment]
@ZulIhwandi apa perbedaannya dengan F-1.01? Mengapa F-1.01 tidak bisa digunakan untuk keperluan anda?

![f-1 01](https://user-images.githubusercontent.com/249563/47480226-d4f5e400-d883-11e8-9d04-4327c3458918.jpg)

Apa dasar peraturan untuk form yang anda gunakan? Apa nama formnya (misalnya F-9.99)? Harap lampirkan peraturannya, termasuk petunjuk pengisiannya.

**Comment by MUHAMMADRANGSEL** [comment]
Di Lombok Timur hanya diminta form F1. 01 kalau untuk KK baru,  tdk ada form lain yg diminta dari disdukcapil maupun kecamatan,

**Comment by MUHAMMADRANGSEL** [comment]
Menurut saya issue ini closed saja, karena sdh ada pengantar F.1.01

**Comment by MUHAMMADRANGSEL** [comment]
perlu ditutup untuk issue ini
