### ISSUE TITLE
plugin wordpres opensid perlu di update

### ISSUE THREAD

**Issue by ZulIhwandi** [OpenSID/OpenSID#1721]
plugin pwopensid tdak bias gukan pak, mukin ada solusi biar bisa di fungsikan kembali

![capture-20181011-044756](https://user-images.githubusercontent.com/34672169/47324010-5123d800-d688-11e8-886f-53a2cb7d7b28.png)

**Comment by siayi** [comment]
Sudah dicoba dengan penyeseuaian sebagaimana di link ini https://github.com/OpenSID/wpsid-shortcode/tree/ayi-dev

**Comment by ZulIhwandi** [comment]
ok terimakasih pak

**Comment by metalab25** [comment]
Bang @siayi mohon juga wpsid layanan mandiri perlu perbaikan

**Comment by afa28** [comment]
issue ini bisa dibuat di repo https://github.com/OpenSID/wpsid-shortcode
