### ISSUE TITLE
penambahan group user

### ISSUE THREAD

**Issue by irsa04** [OpenSID/OpenSID#1722]
penambahan group user :
1. DAWIS (hanya bisa melihat/mengakses/mengupdate kk/penduduk per dusun, per rw, per rt, per dawis)
2. RT (hanya bisa melihat/mengakses/mengupdate kk/penduduk per dusun, per rw, per rt, seluruh anggota dawis berkaitan)
3. RW hanya bisa melihat/mengakses/mengupdate kk/penduduk per dusun, per rw, seluruh anggota rt berkaitan beserta dawisnya)

**Comment by eddieridwan** [comment]
@irsa04 , apa yg dimaksud dengan DAWIS? Apakah sesuai dengan pengertian di https://rieslelono.wordpress.com/2015/03/28/dawis-dasa-wisma-yang-bukan-sepuluh-rumah/? Yaitu unit lebih kecil di bawah RT?

Saat ini OpenSID belum menyediakan unit wilayah lebih kecil dari RT. Apakah pembagian wilayah sampai tingkat DAWIS berlaku umum? Selama ini belum ada desa lain yg menyampaikan kebutuhan ini.

**Comment by irsa04** [comment]
yup betul DAWIS seperti website tersebut diatas. DAWIS seperti nya tidak umum. kendala yang sering terjadi ditempat saya bila ada event selalu meminta fotokopi ktp dan kk. solusi saya menggunakan opensid hanya di pembagian group usernya saja, jadi tetap terkontrol untuk olah datanya. sebenarnya ada yang lebih komplek yaitu penyimpanan data untuk penarikan sampah, keamanan, uang kematian, kas dan lain2 tetapi saya hanya request penambahan di group user nya saja. kalo untuk keuangan seperti saya contohkan diatas, saya bisa kerjakan dengan excel. apabila memang belum tersedia di opensid, ya tidak apa2. kami bisa tetap melanjutkan dengan tulis manual atau menggunakan excel
terima kasih sebelum dan sesudah atas respon nya :)

**Comment by eddieridwan** [comment]
Bisa jelaskan sedikit cara pengoperasian SID di desa anda? Siapa yg akan diberikan akun dengan grup-user DAWIS, RT dan RW itu? Apakah ketua dari masing2 wilayah tersebut? Dari mana mereka akses? Dari rumah mereka? Dan apa saja yg dibayangkan mereka akan lakukan setelah login?

Apakah user2 tersebut dianggap terpecaya untuk mengubah data penduduk di wilayah mereka?

**Comment by PWidodo** [comment]
DAWIS yang dimaksud apakah DASA WISMA, kalau iya berarti DAWIS tersebut tidak masuk struktural pemerintahan desa, karena yang umum hanya sampai pada tingkat RT. Dan betul apa kata Bang EddieRidwan, kebanyakan RT dan RW di Desa tidak akses SID, mereka hanya dimintai data fisik oleh Kadus (Kepala Dusun) atau Kawil (Kepala Wilayah). Walaupun ada mungkin hanya 1:1000 (satu banding seribu).

**Comment by eddieridwan** [comment]
Serupa dengan #1994. Terapkan fitur untuk menambah group user baru, di mana hak aksesnya dapat dipilih oleh admin.

**Comment by afa28** [comment]
Duplicate #1994
