### ISSUE TITLE
Impor Data Kependudukan copy paste

### ISSUE THREAD

**Issue by sukrimalendra** [OpenSID/OpenSID#1724]
Backup data kependudukan dari setiap desa berbeda-beda. untuk memudahkan proses Impor Data Kependudukan pada menu database diperlukan teknis pengentrian data penduduk dengan cara copy paste pada format impor data kependudukan.
![issu](https://user-images.githubusercontent.com/30992964/47603223-4e700c80-da13-11e8-9ff8-c7982ace0810.JPG)

**Comment by balongbesuk** [comment]
Disitu memang tinggal copy paste sesuaikan dengan kolom jenisnya saja, macro secara otomatis akan mengubah menjadi angka
