### ISSUE TITLE
Ubah Style tampilan HP pada jumlah penduduk dan keluarga

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#1726]
### Bagaimana alurnya sampai muncul masalah?
Buka kependudukan > Pilih penduduk / keluarga > Ubah Tampilan HP > lihat penomoran halaman

### Seperti apa yang diharapkan?
Persempit Jumlah Penomoran yang tampil / buat responsive

### Apa yang terjadi?
saat ini jumlah penomoran menampilkan banyak nomor, terkesan berantakan,

### Informasi tambahan 
![wee2](https://user-images.githubusercontent.com/35319600/47644239-337ed300-dba0-11e8-9533-a1605292107b.jpg)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by metalab25** [comment]
kalo mau coba tampilan mobile pake extension atau addon mobile device tester di browser

**Comment by balongbesuk** [comment]
pake bawaan browsernya jg bs gak perlu addon addon.an

**Comment by afa28** [comment]
Ini tergantung banyaknya jumlah penduduk di desa tsb. makin banyak jumlah penduduk dan setting per halaman maka makin banyak juga halaman yg ditampilkan. Untuk saat ini, maksmimal 20 halaman yg ditampilkan.
