### ISSUE TITLE
bug? Pendaftaran Layanan Mandiri

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#1728]
### Bagaimana alurnya sampai muncul masalah?
Buka layanan Mandiri > Pendaftaran Layanan Mandiri

### Seperti apa yang diharapkan?
Tertampil dengan benar

### Apa yang terjadi?
terjadi Error 

### Informasi tambahan 
![untitled221](https://user-images.githubusercontent.com/35319600/47768302-09e1bb00-dd0a-11e8-9aec-f9deef482533.jpg)

saya coba migrasi database namun tidak berjalan

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Waktu upgrade ke 18.10-pasca?

**Comment by balongbesuk** [comment]
Saya coba di website demo sekarang pak eddie, saya pikir jika kesalahan basis data mungkin databasenya belum dimigrasi, mungkin saya yang salah,

**Comment by eddieridwan** [comment]
Sepertinya masalahnya karena mungkin ada yg mengubah databasenya. Sesudah direstore ke data contoh berjalan normal.
