### ISSUE TITLE
[Bug] Jumlah KK di Halaman Utama Tidak Sama Dengan Jumlah KK di Wilayah Dusun

### ISSUE THREAD

**Issue by WAHAB01** [OpenSID/OpenSID#1730]

**Comment by WAHAB01** [comment]
![capture11](https://user-images.githubusercontent.com/34742217/47838750-e63e7380-dde2-11e8-92c6-a508d405a929.PNG)
![capture12](https://user-images.githubusercontent.com/34742217/47838785-02421500-dde3-11e8-92f4-f6650b431860.PNG)

**Comment by eddieridwan** [comment]
@WAHAB01 Terima kasih telah melaporkan.

Masalah ini terjadi karena:
1. Pada tweb_keluarga, kolom nik_kepala menunjuk pada seorang penduduk A
2. Sedangkan penduduk A, kolom kk_level bukan 1

Solusinya:
1. Pada waktu ubah data penduduk, kalau kk_level berubah dari 1 menjadi nilai lain, maka kolom nik_kepala di record tweb_keluarga yg bersangkutan dikosongkan (menandakan tidak ada KK)
2. Pada waktu ubah data penduduk, kalau kk_level diubah menjadi 1, dan kk yang bersangkutan sudah ada nik_kepala yg lain, maka tampilkan error "Keluarga ini sudah ada kepala keluarga", dan perubahan data gagal disimpan
3. Pada waktu ubah data penduduk, kalau kk_level diubah menjadi 1, dan kk yang bersangkutan tidak ada nik_kepala yg lain, maka ubah nik_kepala supaya menunjuk ke penduduk itu.

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
