### ISSUE TITLE
Penomoran Otomatis antara surat cetak, surat masuk dan surat keluar disatukan

### ISSUE THREAD

**Issue by Gunturwijay** [OpenSID/OpenSID#1731]
### untuk model penomoran otomatis sekarang  tidak sesuai dengan yang diterapkan di desa, karena penomoran antara surat cetak, surat masuk dan surat keluar digabungkan dan dicatat didalam satu buka

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by suphm** [comment]
[perlu penjelsan]

**Comment by suphm** [comment]
https://github.com/OpenSID/OpenSID/wiki/Surat-Masuk

Panduan belum diperbarui untuk UI yang baru
yang lama menunya di cetak surat > surat masuk
yang baru di sekretariat > surat masuk|keluar

**Comment by eddieridwan** [comment]
Ya, sudah sering meminta bantuan teman2 untuk memperbaharui panduan. Ternyata belum ada yg bersedia membantu.

**Comment by eddieridwan** [comment]
@suphm 
Solusi untuk dipertimbangkan.

Ganti pilihan untuk setting `nomor_terakhir_semua_surat` di _Pengaturan > Aplikasi_ menjadi:

|Pilihan| Keterangan|
|---|-----|
|Per jenis surat layanan| Nomor surat terakhir tahun ini untuk jenis surat layanan yg sedang dicetak|
|Per semua surat layanan| Nomor surat terakhir tahun ini untuk semua surat layanan tidak memandang jenis|
|Per semua surat layanan, surat masuk dan surat keluar|Nomor surat terakhir tahun ini untuk semua surat, termasuk surat layanan, surat masuk dan surat keluar|

Pilihan `Per jenis surat layanan` sama dengan pilihan `Tidak` di v18.11.
PIlihan `Per semua surat layanan` sama dengan pilihan `Ya` di v18.11.

Pilihan ketiga adalah yg baru yg perlu diterapkan. Nomor terakhir diambil dari tabel `log_surat`, `surat_keluar` dan `surat_masuk` menggunakan cara pengambilan serupa dgn yg diterapkan di v18.11. Atau ditambah tabel khusus untuk menyimpan nomor surat terakhir yang perlu diupdate setiap kali mencetak/menambah surat layanan, surat masuk dan surat keluar.

**Comment by suphm** [comment]
Saya belum paham.

1. Layanan cetak surat itu mencetak surat dari konsep
2. Surat Masuk/keluar itu kelola surat layaknya inbox/outbox pada email
3. cetak surat menyediakan isian nomor surat otomatis berdasarkan aturan __nomor_terakhir_semua_surat__
4. Surat Masuk/keluar nomor suratnya berasal dari dokumen surat yang diupload, input manual.

Ref: wiki
>**nomor_terakhir_semua_surat**| Setting ini untuk menentukan apakah nomor surat terakhir yang ditampilkan di form surat merupakan nomor terakhir untuk surat sejenis (Tidak) atau nomor surat terakhir untuk semua jenis surat (Ya).

>Tab Surat Masuk digunakan untuk mengelola surat masuk yang diterima oleh kantor desa

>Tab Surat Keluar digunakan untuk mengelola surat keluar non-layanan yang dikeluarkan oleh kantor desa.

**Comment by eddieridwan** [comment]
Ya, istilah `Nomor Surat` agak rancu. Yang dicatat di buku agenda sebenarnya sepertinya adalah `nomor urut buku agenda surat`. Di Layanan Surat, sudah terlanjur digunakan sebutan `Nomor Surat` untuk nomor ini, walaupun sebenarnya hanya merupakan bagian dari _Nomor Surat_ lengkap (yg umumnya juga berisi kode klasifikasi dan tahun). Di pilihan (3), SEMUA surat layanan, surat masuk dan surat keluar dicatat dalam satu buku agenda dengan dengan nomor urut terpadu.

Yg digunakan untuk menentukan `nomor surat terakhir` di issue ini adalah kolom `nomor_urut` di tabel `surat_masuk` & `surat_keluar`, dan kolom `nomor_surat` di tabel `log_surat`.

@Gunturwijay @fathurvbf dll : harap konfirmasi pengertian ini.

**Comment by eddieridwan** [comment]
> Kalao di desa saya, surat masuk dan keluar urutanya beda, karena tergantung berapa banyak surat yang keluar dan surat yang masuk

Ya, karena itu issue ini untuk menyediakan pilihan di setting aplikasi.

**Comment by makhbub** [comment]
Kalau di desa saya, surat keluar dibedakan dengan surat keterangan/pengantar
Surat keluar adalah surat yg ditujukan utk org atau lembaga
Sedangkan surat keterangan/pengantar fungsinya sebagai pengantar  warga ke instansi yg dituju seperti urus ktp/kk, ke bank dll
Sehingga antara keduanya penomoranya terpisah

Sedangkan antara surat masuk dan  keluar, penomoran surat tetap sendiri-sendiri tetapi saat pencatatan/pengarsipan dalam biku menjadi satu nomor urut berdasar yang lebih dulu dibuat/diterima

**Comment by makhbub** [comment]
Kurang lebih seperti itu, surat masuk bisa dari perseorangan, tetangga desa atau instansi diluar desa seperti kec dan kab.. tetapi surat keterangan Penduduk datang tidak termasuk karena sifatnya sama dengan surat pengantar

Surat keluar selain ke bupati bisa juga ke perseorangan seperti surat undangan pertemuan

Demikian pemahaman saya, monggo dikoreksi kembali

**Comment by suphm** [comment]
apakah surat yang dicetak bisa juga disebut surat keluar?

**Comment by eddieridwan** [comment]
> apakah surat yang dicetak bisa juga disebut surat keluar?

Sepertinya teman2 perangkat desa menggunakan istilah _surat layanan_ untuk surat pengantar bagi warga yg dicetak melalui menu _Layanan Surat > Cetak Surat_. Sedangkan _surat keluar_ adalah surat yg bukan surat pengantar, seperti undangan, pemberitahuan, surat pada instansi lain, dsbnya. Seperti dijelaskan oleh @makhbub di atas, desa menangani kedua jenis surat ini secara berbeda.

**Comment by eddieridwan** [comment]
Nanti mungkin saja ada fitur untuk mencetak _surat keluar_, tapi fitur ini tetap akan terpisah dari menu _Layanan Surat_.

**Comment by Gunturwijay** [comment]
Karena ada perbedaan penggunaan penomoran surat di berbagai desa, maka saran saya sebaiknya dibuatkan setingan untuk 3 opsi diatas, jadi desa tinggal pilih dipengaturan surat opsi mana yang sesuai dengan desanya

**Comment by Gunturwijay** [comment]
Karena ada perbedaan penggunaan penomoran surat di berbagai desa, maka saran saya sebaiknya dibuatkan setingan untuk 3 opsi diatas, jadi desa tinggal pilih dipengaturan surat opsi mana yang sesuai dengan desanya

**Comment by suphm** [comment]
belum ada push solusi sebaiknya jangan ditutup dulu

**Comment by devtechid** [comment]
ada satu masalah lagi yang saya temukan mas, jadi pas per_semua_surat layanan, kenapa nomornya otomatis berhenti di nomor 10, dan untuk nomor 11 dan seterusnya tidak bisa dilanjutkan secara otomatis.

**Comment by eddieridwan** [comment]
@Gunturwijay apakah anda tutup issue ini karena tidak diperlukan lagi, atau sebab lain?

**Comment by eddieridwan** [comment]
@devtechid 
> ada satu masalah lagi yang saya temukan mas, jadi pas per_semua_surat layanan, kenapa nomornya otomatis berhenti di nomor 10, dan untuk nomor 11 dan seterusnya tidak bisa dilanjutkan secara otomatis.

Harap diperhatikan: masing2 issue HANYA untuk satu masalah; masalah berbeda SELALU dimasukkan ke issue terpisah. Juga jangan lupa melihat dulu apakah masalahnya sudah dilaporkan sebelumnya. Masalah yg anda sebutkan itu sudah dilaporkan sebelumnya di issue #1747 yang sudah dikerjakan (yaitu solusinya sudah di versi pra-rilis).

**Comment by suphm** [comment]
Opsi ketiga ini saya  kira table ```surat_masuk```  ```surat_keluar``` ```surat_format``` ```log_surat``` harus disatukan dan untuk membedakan dibuat kategori

**Comment by Gunturwijay** [comment]
kalaulah tidak ada opsi penggabungan nomor surat omomatis untuk surat
layanan, surat masuk dan surat keluar, mohon dibuatkan opsi untuk
pengnonaktifkan nomor surat otomatis, karena saya menggunakan semua nomor
urut surat, mulai dari surat layanan, surat masuk dan surat keluar

Pada tanggal Min, 18 Nov 2018 pukul 11.26 Yusup Hambali <
notifications@github.com> menulis:

**Comment by eddieridwan** [comment]
Opsi penggabungan nomor surat otomatis untuk surat layanan, surat masuk dan surat keluar telah dicommit ke master melalui PR #1764

**Comment by KASWANDI** [comment]
sangat mempermudah jika pada saat eksport atau cetak surat juga secara otomatis bisa tercatat di menu Sekretariat/surat keluar
