### ISSUE TITLE
[BUG] Daftar Pemilih Tetap tidak muncul error 500

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#1732]
### Bagaimana alurnya sampai muncul masalah?
lihat data statistik daftar pemilih tetap

### Seperti apa yang diharapkan?
tertampil dengan benar

### Apa yang terjadi?
muncul error 500

### Informasi tambahan 
![wee23](https://user-images.githubusercontent.com/35319600/47962493-fc04a080-e04f-11e8-927a-ba0b06413e04.jpg)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
@balongbesuk , di situs demo, DPT berjalan normal http://demo.opensid.info/index.php/dpt.

URL apa yg digunakan?

**Comment by balongbesuk** [comment]
yang di tampilan website depan pak

https://demo.opensid.info/first/dpt

![wee23](https://user-images.githubusercontent.com/35319600/47964281-0338a800-e06a-11e8-8126-ec6dc0a46087.jpg)

seharusnya muncul seperti ini

![wee233](https://user-images.githubusercontent.com/35319600/47964304-793d0f00-e06a-11e8-9ce5-467591e8195f.jpg)

**Comment by eddieridwan** [comment]
Berkas `views/statistik/dpt.php` terhapus pada v18.08 pada waktu pengerjaan Modernisasi Tampilan Modul Admin. Sudah dikembalikan dan dicommit ke master.
