### ISSUE TITLE
BUG Hapus Data Terpilih Pamong

### ISSUE THREAD

**Issue by abangid** [OpenSID/OpenSID#1733]
### Bagaimana alurnya sampai muncul masalah?
Ketika Memilih Semua Pamong/Pemerintah Desa, dan klik data terpilih, maka info sukses keluar dan data tidak terhapus.

### Seperti apa yang diharapkan?
botton hapus yang dipilih bekerja dengan yang baik.

### Apa yang terjadi?
tidak bisa menghapus data yang dipilih

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 18.11
| Versi PHP        | 7.1
| System operasi   | Linux

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR #1738
