### ISSUE TITLE
Lampiran Menampilkan Kode macro Bukan Data

### ISSUE THREAD

**Issue by andryrukandifauzy** [OpenSID/OpenSID#1735]
### Bagaimana alurnya sampai muncul masalah?
Layanan Surat>Cetak Surat>Biodata Ok
Layana Surat>Arsip Layanan > Lihat Lampiran Biodata yang telah di cetak

Dalam Lampiran Tersebut terdapat kode isian bukan data
![screenshot_48](https://user-images.githubusercontent.com/42363553/48038462-4cd8de00-e1a3-11e8-9cad-34f1e3f27a99.jpg)

### Seperti apa yang diharapkan?
Dalam lampiran tidak Ada kode isian atau kode macro

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 18.11
| Versi PHP        | 7.2
| System operasi   | windows

**Comment by andryrukandifauzy** [comment]
![screenshot_111](https://user-images.githubusercontent.com/42363553/48038853-0b493280-e1a5-11e8-8d63-96f034c4c6de.jpg)
![screenshot_112](https://user-images.githubusercontent.com/42363553/48038854-0b493280-e1a5-11e8-848b-016aaa6f436f.jpg)

**Comment by andryrukandifauzy** [comment]
pak @eddieridwan Itu Ketika membuka file lampiran sebagian berisi  berkode macro seharusnya menampilkan data contohnya jenis kelamin menampilkan Laki-laki atau  perempuan dan yang gambar di atas  pada data jenis kelamin hanya menampilkan kode macro
dan untuk yang lainnya juga pak...

**Comment by balongbesuk** [comment]
Bapak sudah baca tata cara pengisian F.1-01 Belum?

![untitled22](https://user-images.githubusercontent.com/35319600/48041989-3ede8980-e1b2-11e8-8265-09ff8adc28b1.jpg)

**Comment by MUHAMMADRANGSEL** [comment]
Silahkan dibaca sesuai arahan balongbesuk

**Comment by andryrukandifauzy** [comment]
Belum pakk saya pelajari dahulu , Terimakasih arahannya .
