### ISSUE TITLE
error saat impor data penduduk

### ISSUE THREAD

**Issue by rizalzaelani** [OpenSID/OpenSID#1736]
### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 18.11
| Versi PHP        | 7
| System operasi   | windows 10

**Comment by eddieridwan** [comment]
Issue ini kami tutup, karena info yg dibutuhkan belum disediakan oleh @rizalzaelani . Silakan buka lagi kalau info yg dibutuhkan sudah disedidakan.
