### ISSUE TITLE
[Bug] tabel kode isian kosong 

### ISSUE THREAD

**Issue by suphm** [OpenSID/OpenSID#1737]
### Bagaimana alurnya sampai muncul masalah?
- Buka Menu Layanan Surat > Pengatuan
- Klik Kode Isian 

### Seperti apa yang diharapkan?
Tabel berisi kode isian seperti di [panduan](https://github.com/OpenSID/OpenSID/wiki/Kode-Isian-Form-Surat)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 18.11
| Versi PHP        | 7.2
| System operasi   |

**Comment by eddieridwan** [comment]
@suphm , coba lampirkan screenshotnya. Surat bawaan sistem atau surat desa?

**Comment by andryrukandifauzy** [comment]
Ini pak @eddieridwan  kode isian semua surat kosong ...
![screenshot_114](https://user-images.githubusercontent.com/42363553/48105903-dce25a80-e26b-11e8-8da4-ef9e273e17fe.jpg)
![screenshot_115](https://user-images.githubusercontent.com/42363553/48105904-dce25a80-e26b-11e8-9041-5ffb4c86712e.jpg)

**Comment by eddieridwan** [comment]
Masalah di PHP v7.1.
Sudah dicommit ke master.
