### ISSUE TITLE
Bug Penambahan User/Pengguna

### ISSUE THREAD

**Issue by abangid** [OpenSID/OpenSID#1739]
### Bagaimana alurnya sampai muncul masalah?
Ketika menambahkan user dengan role "administrator" sukses, 
dan ketika mencoba untuk login, Notif "password dan username salah"

### Seperti apa yang diharapkan?
ketika penambahan user dengan role "administrator" maka user baru bisa login

### Apa yang terjadi?
tidak bisanya user baru login dengan role "administrator" di siteman Opensid

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 18.11
| Versi PHP        |  7.1
| System operasi   | Linux

**Comment by balongbesuk** [comment]
setiap penambahan user baru, > pada menu manajemen pengguna jangan lupa aktifkan (unlock / buka kunci) agar user yang baru dibuat dapat login, 

secara default penambahan pengguna / user akan otomatis terkunci pastikan kunci pengguna / user baru tersebut dibuka

**Comment by eddieridwan** [comment]
Issue ini ditutup karena bukan bug untuk diperbaiki.
