### ISSUE TITLE
[Bug] Pengaturan modul Tidak tampil karena session variable filter & cari belum dikosongkan

### ISSUE THREAD

**Issue by andryrukandifauzy** [OpenSID/OpenSID#1744]
### Bagaimana alurnya sampai muncul masalah?
Pengaturan>Modul

Pengaturan Tidak Muncul sama sekali setelah mencoba versi opensid yang terbaru / commit terakhir dari repo github
![screenshot_2](https://user-images.githubusercontent.com/42363553/48357235-ae7cd900-e6ca-11e8-8f13-2f1164469c93.png)

### Seperti apa yang diharapkan?
pengaturan Modul ada ...

### Apa yang terjadi?

Tidak bisa menonaktifkan modul 
### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 18.11
| Versi PHP        | 7.2.1
| System operasi   | windows

**Comment by suphm** [comment]
saya pakai 7.2 tidak masalah, demo tidak masalah. jadi apa ya? coba lihat logs

**Comment by eddieridwan** [comment]
Sepertinya karena session variable untuk filter & cari belum dikosongkan. Coba buka dengan url `index.php/modul/clear`.

Ok, saya akan ganti nama issue ini untuk mengubah url di menu menjadi `modul/clear`

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR #1746
