### ISSUE TITLE
penanggalan kode hijri belum bisa?

### ISSUE THREAD

**Issue by andryrukandifauzy** [OpenSID/OpenSID#1745]
### Bagaimana alurnya sampai muncul masalah?
sebelumcetak surat sudah disisipkan kodepenanggalan hijri kesurat yg akan d cetak
layanansurat>cetak surat>skck>lihat ekspor doc>penanggalan hiji masih berupa kode

![screenshot_4](https://user-images.githubusercontent.com/42363553/48427589-ad67ac80-e79b-11e8-85c4-db0522f7f99c.png)
![screenshot_5](https://user-images.githubusercontent.com/42363553/48427620-bd7f8c00-e79b-11e8-96f8-25a1ed38108f.png)

### Seperti apa yang diharapkan?
Tanggal hijri muncul

### Apa yang terjadi?

tidak dapat melihat tanggalhijri
### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    |18.11
| Versi PHP        | 7.2
| System operasi

**Comment by balongbesuk** [comment]
yang benar [tgl_surat_hijri]

**Comment by eddieridwan** [comment]
Gunakan kode isian [tgl_surat_hijri]. Lihat https://github.com/OpenSID/OpenSID/wiki/Kode-Isian-Template-Surat.

Judul pull request #1740 salah.

Kami akan tutup issue ini.
