### ISSUE TITLE
[Bug] PERBAIKAN NOMOR SURAT TERAKHIR DI MENU CETAK SURAT

### ISSUE THREAD

**Issue by HerryWanda** [OpenSID/OpenSID#1747]
### Bagaimana alurnya sampai muncul masalah?
- Nomor Surat Terakhir yang muncul "999" padahal nomor surat telah lebih dari 1000 nomor. Contoh nya nomor di cetak surat : 1151, namun yang muncul di nomor surat terkahir "999".

### Seperti apa yang diharapkan?
- Nomor terkhir surat yang muncul seharusnya nomor terkahir surat yang dicetak, bukaan "999" yang ada sekarang ini di Layanan cetak surat.

### Apa yang terjadi?
-  Nomor Surat Terakhir yang muncul "999" padahal nomor surat telah lebih dari 1000 nomor ?

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 8.11
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Masalah itu karena saat ini nomor 'terakhir' diurut berdasarkan abjad bukan angka. Jadi '999' lebih besar dari '1153'. Karena itu '999' selalu muncul sebagai nomor 'terakhir'.

Solusinya: ubah supaya terurut sebagai bilangan, bukan alphanumeric.

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
