### ISSUE TITLE
kolom input file dan input klasifikasi ngga lurus

### ISSUE THREAD

**Issue by sup-ham** [OpenSID/OpenSID#1748]
### Bagaimana alurnya sampai muncul masalah?
buka menu sekretaris > surat masuk
klik [tambah]

### Apa yang terjadi?
![2018-11-17_1366x768_scrot](https://user-images.githubusercontent.com/3823496/48647074-6f79bb00-ea1d-11e8-8e74-209d0f1cc072.png)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 18.11
| Versi PHP        | 7
| System operasi   |

**Comment by eddieridwan** [comment]
Tampilan di beberapa ukuran lebar layar terlihat di bawah (setelah perubahan https://github.com/OpenSID/OpenSID/pull/2027), masih kurang pas.

Kode/klasifikasi surat sepertinya menjadi tidak responsif, ukurannya tidak berubah.
Saya juga usul, kolom2 berikut tidak 100% untuk layar besar, mungkin 40% dan 60% untuk layar medium:

1. Tanggal penerimaan
2. Berkas Scan Surat Masuk
3. Kode/Klasifikasi surat
4. Tanggal surat

Layar besar:
![form-lg](https://user-images.githubusercontent.com/249563/56482178-118a5b80-6506-11e9-9d5f-3d688a92a483.jpg)

Layar medium:
![form-md](https://user-images.githubusercontent.com/249563/56482197-2830b280-6506-11e9-99b4-6c5a0348a8d3.jpg)

Layar kecil:
![form-xs](https://user-images.githubusercontent.com/249563/56482218-3ed70980-6506-11e9-8390-a7f6a4ffdb8f.jpg)

**Comment by eddieridwan** [comment]
Sudah dicommit ke `master` melalui PR #3035
