### ISSUE TITLE
Error 500 Import Database setelah update ke PHP 7.0.8

### ISSUE THREAD

**Issue by abahaka** [OpenSID/OpenSID#1749]
### Bagaimana alurnya sampai muncul masalah?
Setelah melakukan Update dari PHP 5.6.10 ke PHP 7.0.8.
Dilakukan proses Import Database.

### Seperti apa yang diharapkan?
Proses Import Database harusnya berhasil tanpa kendala/error

### Apa yang terjadi?
Muncul Error sebagai berikut :

This Page isn't working
Localhost is currently unable to handle this request.
HTTP error 500

![screen shot 2018-11-16 at 6 14 31 pm](https://user-images.githubusercontent.com/14047966/48666090-635d2e80-eaed-11e8-83cc-623d1a37c2bf.png)

log-nya sebagai berikut :

<?php defined('BASEPATH') OR exit('No direct script access allowed'); ?>

ERROR - 2018-11-17 03:25:01 --> Severity: error --> Exception: Call to undefined function split() /Applications/MAMP/htdocs/opensid1811_php7/donjo-app/helpers/excel_helper.php 79
ERROR - 2018-11-17 03:33:10 --> Severity: error --> Exception: Call to undefined function split() /Applications/MAMP/htdocs/opensid1811_php7/donjo-app/helpers/excel_helper.php 79
ERROR - 2018-11-17 03:41:07 --> Severity: error --> Exception: Call to undefined function split() /Applications/MAMP/htdocs/opensid1811_php7/donjo-app/helpers/excel_helper.php 79
ERROR - 2018-11-17 03:56:34 --> Severity: error --> Exception: Call to undefined function split() /Applications/MAMP/htdocs/opensid1811_php7/donjo-app/helpers/excel_helper.php 79

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 18.11
| Versi PHP        | 7.0.8
| System operasi   | Windows 10, OSX 10.9.5

**Comment by eddieridwan** [comment]
Seperti sudah diberitahu di WA, masalah ini sudah diperbaiki di versi pra-rilis.
