### ISSUE TITLE
Penambahan kolom dan data pada menu Info Desa/Pemerintahan Desa

### ISSUE THREAD

**Issue by PWidodo** [OpenSID/OpenSID#1750]
### Bagaimana alurnya sampai muncul masalah?
Pihak Pemerintah Kecamatan sering meminta Data Perangkat Desa secara berkala, padahal didalam Opensid sudah ada menunya tetapi masih kurang lengkap dan tidak dapat dicetak

### Seperti apa yang diharapkan?
Operator Desa nantinya dapat sekali klik tombol "Cetak Laporan" atau "Cetak Data"

### Apa yang terjadi?
Mohon kepada pegiat OpenSID lainnya untuk membuatkan coding cetaknya, untuk script yang sudah saya edit saya lampirkan.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
[Script-Menu-Pemerintahan-Desa.zip](https://github.com/OpenSID/OpenSID/files/2599145/Script-Menu-Pemerintahan-Desa.zip)

**Comment by eddieridwan** [comment]
![daftar-pamong](https://user-images.githubusercontent.com/249563/48894172-2d75cc80-ee96-11e8-8e81-b4325e6f89de.jpg)
![form-pamong](https://user-images.githubusercontent.com/249563/48894174-2d75cc80-ee96-11e8-8fe6-3e8b8483757f.jpg)

**Comment by siayi** [comment]
> Apakah bisa untuk data perangkat desa mengambil dari data penduduk? alurnya mungkin sebelum mengisi ada pilihan apakah Perangkat Desa adalah Penduduk atau bukan? Jika Pilihannya Penduduk maka tinggal ambil data dirinya, Jika Bukan Penduduk baru isi Form tersebut.

untuk kasus di desa saya (saat ini),, untuk Penjabat (Pj.) Kepala Desa ternyata bukan penduduk desa, karena yang bersangkutan adalah PNS dari Pemda Kabupaten ... dan Kepala Desa dalam OpenSID masuk dalam daftar nominatif Aparatur Pemerintah Desa ...

**Comment by eddieridwan** [comment]
Penambahan kolom dan pengambilan data dari database penduduk sudah dicommit ke master.
Penambahan fitur Cetak/Unduh telah dibuatkan issue terpisah di #1778
