### ISSUE TITLE
penambahan Peangkat desa hanya sampai 4 orang

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#1752]
![image](https://user-images.githubusercontent.com/25834335/48814103-82212680-ed74-11e8-972a-44385aa389db.png)

### Bagaimana alurnya sampai muncul masalah?
ketika mengisi data perangkat desa lebih dari 4 orang maka data akan terjadi maslah

### Seperti apa yang diharapkan?
tdk muncul maslah seperti diatas seperti rilis sebelumnya

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
@MUHAMMADRANGSEL Tidak ada masalah di http://demo.opensid.info. Biasakan konfirmasi masalah dengan mencoba di situs demo juga. Sepertinya masalah di database anda.

![jml-pamong](https://user-images.githubusercontent.com/249563/48814654-accca880-ed8f-11e8-8705-c4d9584577ca.jpg)

**Comment by MUHAMMADRANGSEL** [comment]
![image](https://user-images.githubusercontent.com/25834335/48817810-3629ae00-ed83-11e8-8a43-70346d99f9cd.png)

**Comment by MUHAMMADRANGSEL** [comment]
OK SIAP KALAU GITU NANTI SAYA PERIKSA DATABASENYA BUNG

**Comment by MUHAMMADRANGSEL** [comment]
OK, SETELAH SAYA CEK DATABASE YANG SAYA PUNYA TERNYATA MASALAHNYA DI TWEB_PAMONG NYA YANG BERMASLAH DAN SEKARANG SUDAH BISA, SHG ISUUE INI SAYA TUTUP
