### ISSUE TITLE
Penambahan dan perbaikan Fitur Wilayah Administratif

### ISSUE THREAD

**Issue by gugel88** [OpenSID/OpenSID#1753]
### Bagaimana alurnya sampai muncul masalah?
1.) Pada saat memilih menu Wilayah Administratif Dusun seharusnya pada tabel muncul Jumlah data/record RW serta RT sesuai wilayah/dusun masing-masing
2.) Pada saat memilih link pada record Column RW Row Record Jumlah RW seharusnya pada tabel muncul Jumlah data/record RT sesuai wilayah Administratif RW

### Seperti apa yang diharapkan?
Menambahkan dua menu/fitur baru yakni Wilayah Administratif RW dan Wilayah Administratif RT, seperti halnya menu Wilayah Administratif Dusun

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 18.10-pasca
| Versi PHP        | 5.4.45
| System operasi   | Linux

**Comment by eddieridwan** [comment]
@gugel88 : bukankah fitur ini sudah ada? Coba tampilkan screenshot untuk menjelaskan permintaan anda. Pengelolaan Dusun, RW dan RT sepertinya sudah lengkap.

**Comment by gugel88** [comment]
Siap fitur ini sudah lengkap dan sempurna di update an 18.12
