### ISSUE TITLE
Tombol Kembali saat Ubah Biodata Penduduk

### ISSUE THREAD

**Issue by hasap86** [OpenSID/OpenSID#1756]
### Bagaimana alurnya sampai muncul masalah?
Saat berada di form Ubah Biodata Penduduk tidak ada tombol Kembali

### Seperti apa yang diharapkan?
sediakan tombol Kembali untuk kembali ke data penduduk

### Apa yang terjadi?
harus pilih menu lagi

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 18.11
| Versi PHP        | 5.6.38
| System operasi   | Linux

**Comment by eddieridwan** [comment]
Sudah dicommit melalui PR #1834
