### ISSUE TITLE
[Artikel] Artikel/Halaman Statis Web tak perlu di tampilan sebagai artikel blog di tampilan web, hanya untuk dipanggil di menu atau link widget/manual

### ISSUE THREAD

**Issue by hasap86** [OpenSID/OpenSID#1757]
### Bagaimana alurnya sampai muncul masalah?
Munculnya artikel/halaman statis di artikel terkini web

### Seperti apa yang diharapkan?
Seharusnya Artikel/Halaman Statis hanya untuk dipanggil di menu atau link widget/manual

### Informasi tambahan 
Atau diberikan pilihan centang apakah ingin di tampilkan pada artikel berita web atau tidak.

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 18.11
| Versi PHP        | 
| System operasi   |

**Comment by andifahruddinakas** [comment]
mas @arifpriadi, PR ini sudah digabungkan melalui commit https://github.com/OpenSID/premium/commit/b5de01dbb9e7a624e79c94634f21dd3d9aee8eed  dengan penyesuaian yang ada di branch rilis-dev.
