### ISSUE TITLE
[Layanan Mandiri] Laporan Masuk tambahkan Keterangan & Status

### ISSUE THREAD

**Issue by hasap86** [OpenSID/OpenSID#1758]
### Bagaimana alurnya sampai muncul masalah?
Saat ini pada menu laporan masuk hanya ada status tindak lanjut Ya / Tidak dan tidak ada keterangan yang diisi oleh petugas/staf.

### Seperti apa yang diharapkan?
Seharusnya Status tindak lanjut dibuat menjadi 3 proses:

1. Menunggu Diproses, status default awal
2. Sedang Diproses, dirubah oleh staf saat sedang menangani laporan
3. Selesai Diproses, dirubah oleh staf saat laporan sudah terselesaikan

sertakan juga inputan keterangan yang diisi oleh staf yg menangani laporan.
kemudian disisi Pelapor / Warga saat login dibawah Form Laporan, disertakan Daftar Aduan / Lapor beserta status dan keterangannya. (halaman view diperlukan)

### Apa yang terjadi?
Yang terjadi saat ini, Pelapor / Warga tidak mengetahui sejauh mana proses laporan dan apa yg sedang diprosesnya dikarenakan tidak ada keterangan.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 18.11
| Versi PHP        | 
| System operasi   |

![status-lapor-1](https://user-images.githubusercontent.com/45263721/48925761-fcc77e80-eef9-11e8-9c49-239423913274.jpg)
![status-lapor-daftar-aduan](https://user-images.githubusercontent.com/45263721/48925762-fd601500-eef9-11e8-96e7-b25c33e906e4.jpg)

**Comment by afa28** [comment]
Apakah ini masih bermasalah??? Kalau tdk silahkan di close.

**Comment by afa28** [comment]
Issue berkaitan dengan layanan mandiri di lanjutkan setelah issue PR https://github.com/OpenSID/premium/pull/47 atau issue https://github.com/OpenSID/OpenSID/issues/3696 selesai digabung.

**Comment by eddieridwan** [comment]
Telah digabung ke issue sistem keluhan/pengaduan/lapor di https://github.com/OpenSID/OpenSID/issues/512
