### ISSUE TITLE
[Statistik] Laporan Kehamilan di Statistik

### ISSUE THREAD

**Issue by hasap86** [OpenSID/OpenSID#1759]
### Bagaimana alurnya sampai muncul masalah?
Pihak desa tidak bisa mengetahui warganya yang sedang hamil dan umur kehamilannya

### Seperti apa yang diharapkan?
Adanya Laporan Kehamilan warga beserta umur kehamilannya pada menu **Statistik >> Laporan Kehamilan** yang menyajikan data warga hamil beserta umur kehamilan, Umur Kehamilan hasil dari inputan form ubah warga > DATA KESEHATAN > Status Kehamilan > Perkiraan Tgl. Kehamilan.

### Apa yang terjadi?
Pihak desa menjadi lebih bisa memperhatikan warganya yang hamil, dan mengetahui kapan akan lahiran sehingga pihak desa bisa menyiapkan jauh jauh hari untuk mempersiapkan kehamilan warganya untuk membantu dari mulai mobil ambulance dan tenaga kesehatan.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

![form-input-kehamilan-warga](https://user-images.githubusercontent.com/45263721/48926233-a7da3700-eefe-11e8-9d60-581975332e73.jpg)

**Comment by hasap86** [comment]
untuk sementara bisa dibbuatkan seperti ini datanya

No. KK | Kepala Keluarga | Alamat | Dusun | RT | RW | NIK | Nama | Nomor Telepon | Gol. Darah | Umur Kehamilan | Status Rekam KTP

**Comment by andifahruddinakas** [comment]
Sudah digabung ke `PREMIUM` melalui PR https://github.com/OpenSID/premium/pull/567
