### ISSUE TITLE
[Layanan Mandiri] Pendaftaran Layanan Mandiri

### ISSUE THREAD

**Issue by hasap86** [OpenSID/OpenSID#1760]
### Bagaimana alurnya sampai muncul masalah?
Tidak ada fitur Pendaftaran Layanan Mandiri di Web Desa.

### Seperti apa yang diharapkan?
Adanya Pendaftaran Fitur Layanan Mandiri di web desa selain menghubungi ke Operator Desa. Sediakan tautan `Daftar` di halaman login Layanan Mandiri

Pendaftaran Layanan Mandiri mengisi NIK, nomor KK, Tgl. Lahir dan nomor HP, email atau akun Telegram. Melampirkan scan KTP dan Kartu Keluarga, beserta foto selfie. Juga pendaftar diminta memilih PIN sendiri.

Setelah data ini diisi, status pendaftaran adalah `draf`. Pengguna dapat login ke akun `draf` menggunakan NIK dan PIN yg diisi. 

Untuk melengkapi pendaftaran, alamat email dan akun Telegram perlu diverifikasi dulu oleh sistem. Jadi issue https://github.com/OpenSID/OpenSID/issues/4558 perlu dikerjakan dulu untuk verifikasi akun Telegram.

Setelah akun Telegram diverifikasi, status pendaftaran adalah `siap diperiksa operator desa`.

Disisi Admin. operator melihat permintaan, memverifikasi data, menyetujui. Setelah disetujui, konfirmasi beserta PIN awal otomatis dikirim ke alamat email atau akun Telegram yang telah diverifikasi. PIN ini mengganti PIN yg dibuat oleh pengguna sendiri pada pendaftaran `draf`. 

### Apa yang terjadi?
Proses menjadi lebih cepat tanpa perlu datang ke desa

### Informasi tambahan 

Jika NIK tersebut sudah terdaftar Layanan Mandiri, tampilkan pesan memberitahu. Jangan daftar ulang, atau mengubah data yg sudah ada.

Jika NIK, nomor KK atau tgl lahir tidak cocok dengan data penduduk, process pendaftaran gagal. Tampilkan pesan penduduk tidak dikenal dan untuk menghubungi operator desa. 

Pada proses validasi/verifikasi oleh petugas, perlu memeriksa semua isian sudah sesuai dengan data yg tersimpan di data kependudukan OpenSID. Termasuk memeriksa foto selfie adalah serupa dengan foto yg di KTP. Sebagai langkah standar, petugas dapat memanggil melalui nomor HP/WA/Telegram untuk bicara langsung dengan pendaftar (menggunakan video kalau perlu). Dan kalau masih ragu meminta pendaftar datang ke kantor desa.

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 18.11
| Versi PHP        | 
| System operasi   |

**Comment by suphm** [comment]
kalau ada pakai nik orang lain tanpa persetujuan.
gimana?

**Comment by hasap86** [comment]
> kalau ada pakai nik orang lain tanpa persetujuan.
> gimana?

kan disitu saya jelaskan adanya verifikasi dari operator / petugas staf desa untuk memastikan yg mendaftar benar dan valid.

**Comment by sup-ham** [comment]
harus tatap muka untuk validasi nya

**Comment by hasap86** [comment]
jaman sudah canggih, adanya digital untuk mempercepat pelayanan...
saran saya mungkin bisa dibuatkan setingan apakah pendaftaran mau diaktifkan atau harus datang ke desa. jadi bagi desa digital yg sudah menerapkan pendaftaran online bisa menggunakan pendaftaran online dengan validasi digital, atau di off kan bagi desa yang mau melakukan pendaftaran secara tradisional...

**Comment by afa28** [comment]
Masalah akan timbul jika yg mendaftar menggunakan data dr org lain (berupa identitas, dokumen org tsb atau lainnya). Mungkin mmang sebaiknya pendaftaran dilakukan scr tatap muka dan dsni jg bisa dimanfaatkankan sbgai validasi data penduduk tsb.

**Comment by mizwaruddin** [comment]
@afa28 lebih banyak yg sepakat pendaftaran akun layanan mandiri dilakukan oleh operator.

**Comment by afa28** [comment]
Issue berkaitan dengan layanan mandiri di lanjutkan setelah issue PR https://github.com/OpenSID/premium/pull/47 atau issue https://github.com/OpenSID/OpenSID/issues/3696 selesai digabung.

**Comment by afa28** [comment]
> @afa28 lebih banyak yg sepakat pendaftaran akun layanan mandiri dilakukan oleh operator.

Solusi tambahkan nomer WA yg bisa di hubungi pd login mandiri.

**Comment by FirlianiF** [comment]
mulai pengerjaan issue #1760

**Comment by agungsugiarto** [comment]
> Masalah akan timbul jika yg mendaftar menggunakan data dr org lain (berupa identitas, dokumen org tsb atau lainnya). Mungkin mmang sebaiknya pendaftaran dilakukan scr tatap muka dan dsni jg bisa dimanfaatkankan sbgai validasi data penduduk tsb.

Pak @eddieridwan, bagaimana dengan pertimbangan dari mas @andifahruddinakas ini?
Sementara validasi dibawah ini rawan jika sebelumnya data sudah bocor?
- [ ] NIK
- [ ] KK
- [ ] Tanggal Lahir
- [ ] Nomor HP
- [ ] Email
- [ ] Telegram
- [ ] Scan KTP
- [ ] Scan KK
- [ ] Foto Selfie

**Comment by eddieridwan** [comment]
- [ ] Tambahkan pengaturan untuk me-aktif/nonaktifkan fitur pendaftaran Layanan Mandiri ini. Jadi desa bisa memilih untuk tidak menyediakan. 

Dengan begitu banyaknya data identitas yg perlu disediakan, termasuk foto selfie, saya kira kecil sekali kemungkinan adanya orang yg secara sengaja mengambil data identitas orang lain hanya untuk mendapatkan akses ke Layanan Mandiri. 

Sebagai langkah standar validasi/verifikasi, petugas dapat memanggil melalui nomor HP/WA/Telegram untuk bicara langsung dengan pendaftar (menggunakan video kalau perlu). Dan kalau masih ragu meminta pendaftar datang ke kantor desa.

@scqolbu24  Mohon terus diterapkan untuk v22.01-premium.

**Comment by scqolbu24** [comment]
baik pak, siap mengerjakan.

**Comment by scqolbu24** [comment]
Pak @eddieridwan, mau menanyakan ketika proses pendaftaran dan verifikasi diperlukan Nomor KK atau tidak?

**Comment by agungsugiarto** [comment]
Sudah masuk ke rilis premium melalui pr https://github.com/OpenSID/premium/pull/540
