### ISSUE TITLE
Popup view jika gambar artikel / gallery di klik

### ISSUE THREAD

**Issue by hasap86** [OpenSID/OpenSID#1761]
### Bagaimana alurnya sampai muncul masalah?
Ketika sebuah gambar baik dari artikel atau gallery di klik, pengunjung disuguhkan ke link gambar tersebut, sehingga tampilan web menjadi hilang.

### Seperti apa yang diharapkan?
Jika gambar baik di artikel ataupun gallery di klik, menampilkannya Popup di halaman yg sama tidak diarahkan ke link gambar tersebut.
![gambar-popup](https://user-images.githubusercontent.com/249563/65925981-595aca80-e436-11e9-927b-cd2d0191921c.jpg)

![popup-galeri](https://user-images.githubusercontent.com/249563/66383562-fa362080-ea08-11e9-9160-bfab8b7045fd.jpg)

### Apa yang terjadi?
agar tidak keluar dari halaman web sehingga pengunnjung tidak tersesat.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19.10
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Telah dicommit ke master melalui PR #2350
