### ISSUE TITLE
Style Paging Data Penduduk, Keluarga, dll

### ISSUE THREAD

**Issue by hasap86** [OpenSID/OpenSID#1762]
![style-paging](https://user-images.githubusercontent.com/45263721/48961172-078b1d80-efa5-11e8-887e-3a99c8df112e.jpg)

### Bagaimana alurnya sampai muncul masalah?
style paging baik di Data Penduduk, Keluarga, dan lainnya tidak beraturan ke bawah.

### Seperti apa yang diharapkan?
mungkin seharusnya style paging dijadikan 1 baris saja tidak perlu ke bawah

### Apa yang terjadi?
kurang enak dilihatnya

### Informasi tambahan 
nilai lebar saat ini 50%, mungkin bisa dijadikan dipecah sebelah kiri untuk info jumlah baris total data desa menjadi 30%, untuk paging sebelah kanan 70%.

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 18.11
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
Sdh digabung ke `master` melalui PR #3684, untuk selanjutnya bisa gunakan format paging yg sudah disediakan pd modul lainnya.
