### ISSUE TITLE
Default Tgl. Surat

### ISSUE THREAD

**Issue by hasap86** [OpenSID/OpenSID#1763]
### Bagaimana alurnya sampai muncul masalah?
Proses memilih tgl. berlaku surat

### Seperti apa yang diharapkan?
otomatis terisi default per hari ini (tgl. dibuatnya surat) s.d 30 hari kedepan (atau dibuatkan seting lamanya masa berlaku surat)

### Apa yang terjadi?
memudahkan dan mempercepat proses pembuatan surat

### Informasi tambahan 
![default-tgl-surat](https://user-images.githubusercontent.com/45263721/48962011-7ae45d80-efac-11e8-9b57-d09e058f7939.jpg)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 18.11
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sebagian telah dikerjakan dan dicommit ke master:

1. semua form surat yg berisi tgl berlaku sekarang mengharuskan tgl akhir selalu minimal satu hari setelah tgl mulai
2. tgl mulai default tgl hari sekarang. Tidak otomatis diisi, tapi tinggal di-klik saja
3. setelah tgl mulai diisi, tgl akhir otomatis diisi tgl 1 bulan setelah tgl mulai, dan bisa diubah.

**Comment by eddieridwan** [comment]
Yang belum dikerjakan:

1. mengisi tgl mulai/tgl akhir awal secara otomatis
2. menyediakan setting aplikasi untuk menentukan 'nilai default masa berlaku surat'

**Comment by afa28** [comment]
Apakah ini masih bermasalah??? Kalau tdk silahkan di close.

**Comment by eddieridwan** [comment]
Setting masa berlaku dibuat untuk masing-masing jenis surat. Awalnya gunakan setting default. 

![masa-berlaku](https://user-images.githubusercontent.com/249563/98535279-ef1f8500-22d9-11eb-83a9-4cf01318ec07.jpg)

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3733
