### ISSUE TITLE
Otomatisasi Jabatan Staf Penandatangan Laporan Kependudukan Bulanan

### ISSUE THREAD

**Issue by hasap86** [OpenSID/OpenSID#1765]
![ttd-laporan-bulanan](https://user-images.githubusercontent.com/45263721/48970362-d90d5100-f03d-11e8-97df-72f655b3d5f3.jpg)

### Bagaimana alurnya sampai muncul masalah?
Ketika Memilih Staf Sebagai Penandatangan Laporan Kependudukan Bulanan pada menu Statistik > Laporan Bulanan Jabatan tidak otomatis mengikuti jabatan staf terpilih.

### Seperti apa yang diharapkan?
Jabatan Staf otomatis terpilih sesuai dengan jabatan staf yang dipilih

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 18.11
| Versi PHP        | 
| System operasi   |

**Comment by hasap86** [comment]
> Bos, itu sudah ada fiturnya. Silakan diexplore

masa sih? kalo yg lain setiap pilih nama staf memang jabatannya sudah otomatis mengikuti, tapi yg ini nggak otomatis kayaknya. seperti halnya cetak surat, jika kita memilih staf maka jabatan otomatis terisi sesuai jabatan staf yg dipilih.

**Comment by hasap86** [comment]
> Makanya bos di explore, fitur default penandatangan sudah ada bos

kalo fitur itu sudah saya gunakan bos, yg saya maksud bukan itu, dan bahkan fitur default penandatangan tidak jalan di Laporan Kependudukan Bulanan, sudah coba dibuka belum Laporan Kependudukan Bulanannya, barangkali disana bisa disaya gak bisa? :)

**Comment by hasap86** [comment]
Sekalipun Default TTD diaktifkan pada salah satu staf, namun di TTD Laporan Bulanan tidak berjalan
![default-ttd](https://user-images.githubusercontent.com/45263721/48975263-574e0f80-f09f-11e8-8534-2889d81d7629.jpg)

Dicetak Surat Berjalan
![default-ttd-surat](https://user-images.githubusercontent.com/45263721/48975291-81073680-f09f-11e8-9033-3d3ee391b475.jpg)

Di Laporan Bulanan Tidak Berjalan
![default-tgl-laporanbulanan](https://user-images.githubusercontent.com/45263721/48975301-911f1600-f09f-11e8-8a94-c39aed2900be.jpg)

Bahkan ketika dipilih Staf, Jabatannya tidak otomatis seperti yg lainnya
![default-ttd-jabatan-tdk-otomatis](https://user-images.githubusercontent.com/45263721/48975336-405bed00-f0a0-11e8-9fb8-1774c0177b88.jpg)

**Comment by abahaka** [comment]
Mohon maaf, karena bukan seorang programer, tapi saya jungan ingin aplikasi ini mendekati kesempurnaan dan berupaya juga untuk menutupi apa yang kurang semampunya saya.
Untuk Issue ini diatas coba perbaiki file /donjo-app/views/laporan/bulanan.php dengan mengadopsi script pada _pamong.php dan sedikit perubahan.

_pada baris 65 :_
<select name="pamong" class="form-control input-sm" >

_ganti dengan :_
<select class="form-control required input-sm" id="pamong" name="pamong" onchange="var nip=$(this).find(':selected').data('nip'); $('#pamong_nip').val(nip);$(this).closest('.box-body').find('select[name=jabatan]').val($(this).find(':selected').data('jabatan')) ">

_pada baris 68 :_
<option value="<?= $data['nama']?>"><?= $data['nama']?> (<?= $data['jabatan']?>)</option>

_ganti dengan :_
<option value="<?= $data['nama']?>" data-jabatan="<?= trim($data['jabatan']) ?>" <?php if ($data['pamong_ttd']==1): $pamong_nip =	$data['pamong_nip']; ?>selected <?php endif; ?> data-nip="<?= $data['pamong_nip']?>">
<?= $data['nama']?> (<?= $data['jabatan']?>) <?php if (!empty($tmp_nip)): ?>NIP: <?= $data['pamong_nip'];?><?php endif; ?>
</option>

Mohon maaf Jika cara diatas kurang tepat, semoga Para Master dapat penutupi kekurangan dari saya. Terima Kasih

**Comment by hasap86** [comment]
Bung @eddieridwan mungkin script diatas bisa dicek dan dimasukan pada update berikutnya. Terimakasih

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR #2015
