### ISSUE TITLE
[Bug] Merubah Nama Ketua RW, Nama Ketua RT Ikut Berubah

### ISSUE THREAD

**Issue by hasap86** [OpenSID/OpenSID#1766]
![ganti-rw](https://user-images.githubusercontent.com/45263721/49016030-62945e80-f1b7-11e8-9148-f5809c15d3e7.jpg)
![ganti-rw-rt-ganti](https://user-images.githubusercontent.com/45263721/49016034-658f4f00-f1b7-11e8-91c3-af838ac58433.jpg)

### Bagaimana alurnya sampai muncul masalah?
Ketika merubah nama ketua RW, semua Nama Ketua RT pada RW tersebut ikut berubah menjadi nama ketua RW.

### Seperti apa yang diharapkan?
seharusnya ketika merubah nama ketua RW tidak merubah nama ketua RT di RW tersebut.

### Apa yang terjadi?
harus ikut merubah nama ketua RT satu per satu kemabli

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 18.11-pasca
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dicommit melalui PR #1780
