### ISSUE TITLE
Input Data Anggota Kelompok tambahkan Jabatan & No. Surat Keputusan

### ISSUE THREAD

**Issue by hasap86** [OpenSID/OpenSID#1767]
### Bagaimana alurnya sampai muncul masalah?
Input data kelompok saat ini tidak ada isian Jabatan & No. Surat Keputusan

### Seperti apa yang diharapkan?
tambahkan input Jabatan & No. Surat Keputusan

### Apa yang terjadi?
kurang lengkap

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 18.11-pasca
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sdh dicommit ke Rilis Premium melalui PR #3499
