### ISSUE TITLE
[Bug] Input Peserta Program Bantuan sasaran Keluarga salah penulisan title

### ISSUE THREAD

**Issue by hasap86** [OpenSID/OpenSID#1768]
![input-rincian-program](https://user-images.githubusercontent.com/45263721/49022439-7647c100-f1c7-11e8-93b0-08dceb219cad.jpg)

### Bagaimana alurnya sampai muncul masalah?
Di Form input **Peserta Program Bantuan** dengan sasaran Keluarga, penulisan title **NIK / Nama Penduduk** salah
### Seperti apa yang diharapkan?
Title Seharusnya **No. KK / Nama KK** karena data yg diambil berdasarkan No. KK bukan NIK

### Apa yang terjadi?
jadi tidak ada data karena list data yg ditampilkan berdasarkan No. KK bukan NIK

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
@hasap86 terima kasih telah melaporkan.
Data  NIK, Nama, dsbnya memang sengaja dikumpulkan secara manual dari Kartu Peserta, karena menurut teman2 desa, data yg ada di database sering berbeda dgn data yg tertera di Kartu Peserta. Jadi mereka ingin merekam data yg ada di Kartu Peserta.

**Comment by hasap86** [comment]
Baik bung @eddieridwan ikut yg sudah pengalaman... terimakasih

**Comment by eddieridwan** [comment]
Sudah dicommit ke master
