### ISSUE TITLE
[Bug] Pencarian Wilayah Administratif Dusun nyangkut inputan pencarian lain

### ISSUE THREAD

**Issue by hasap86** [OpenSID/OpenSID#1769]
![wilayah-administratif-pencarian](https://user-images.githubusercontent.com/45263721/49023491-e35c5600-f1c9-11e8-8580-74b2067f09fc.jpg)

### Bagaimana alurnya sampai muncul masalah?
Ketika membuka data Wilayah Administratif Dusun, pada inputan pencarian terdapat isian pencarian lain.

### Seperti apa yang diharapkan?
Seharusnya ketika membuka Wilayah Administratif Dusun inputan pencarian kosong

### Apa yang terjadi?
sehingga data Wilayah Administratif Dusun menjadi kosong karena ada nyangkut isian pencarian sebelumnya di menu lain

### Informasi tambahan 
Ujicoba lakukan pencarian Penduduk, lalu buka Menu Wilayah Administratif Dusun.

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 18.11-pasca
| Versi PHP        | 5.6.38
| System operasi   | Linux

**Comment by hasap86** [comment]
Langkah Pertama, Lakukan pencarian di menu Data Penduduk

![pencarian-data-penduduk](https://user-images.githubusercontent.com/45263721/49407017-ce636200-f789-11e8-9e45-ef43968ce5b4.jpg)

Langkah Kedua, Setelah hasil pencarian muncul, klik menu Wilayah Administratif

![wilayah-administratif](https://user-images.githubusercontent.com/45263721/49407079-feab0080-f789-11e8-9ccc-569daf8101bb.jpg)

Maka Akan terlihat data input pencarian tadi di Data Penduduk terbawa di input pencarian Wilayah Adinistratif Dusun, sehingga Data Dusun tidak muncul karena terfilter oleh inputan pencarian sebelumnya.

![input-pencarian-ngikut](https://user-images.githubusercontent.com/45263721/49407101-171b1b00-f78a-11e8-8e1f-bfe79c34a62e.jpg)

**Comment by hasap86** [comment]
saya menggunakan versi PHP 5.6.38 Linux

**Comment by hasap86** [comment]
Saya coba dmenggunakan subdomain lain ternyata benar aman, saya sedang mencari letak masalahnya di domain yg mengalami masalah ini, dan segera saya laporkan jika sudah ketemu permasalahannya

**Comment by suphm** [comment]
mungkin masalah session

**Comment by eddieridwan** [comment]
@hasap86  Apakah masih mengalami masalah ini? Apakah sudah menjalankan Migrasi DB di domain yg bermasalah? Mohon dicek lagi, supaya issue ini bisa ditutup.

**Comment by eddieridwan** [comment]
@hasap86 coba periksa isi tabel `setting_modul` di _phpmyadmin_. Pada baris dengan `id` = 20, kolom `url` seharusnya berisi `sid_core/clear`.

![sid-core-clear](https://user-images.githubusercontent.com/249563/50514322-8d910b80-0af1-11e9-8ef6-1deb945a39fd.jpg)

**Comment by Apkrovoot123** [comment]
164722

**Comment by Apkrovoot123** [comment]
Open
[Bug] Pencarian Wilayah Administratif Dusun nyangkut inputan pencarian lain #1769
@hasap86
hasap86 opened this issue about 1 month ago • edited 25 days ago

**Comment by Apkrovoot123** [comment]
hasap86 opened this issue about 1 month ago • edited 25 days ago
