### ISSUE TITLE
Format Laporan Buku Administrasi Desa Terbaru

### ISSUE THREAD

**Issue by hasap86** [OpenSID/OpenSID#1770]
### Bagaimana alurnya sampai muncul masalah?
Format laporan banyak yang belum terfasilitasi di OpenSID dan perlu penyesuaian

### Seperti apa yang diharapkan?
sesuai Format Buku Administrasi Desa

### Apa yang terjadi?
harus membuat lagi manual

### Informasi tambahan 
Biasanya setiap tahun akhir masa jabatan setiap desa diminta laporan dalam bentuk Buku Administrasi Desa tersebut (Format Terlampir)

FILE: [BUKU ADMINISTRASI DESA TERBARU.xlsx](https://github.com/OpenSID/OpenSID/files/2618390/BUKU.ADMINISTRASI.DESA.TERBARU.xlsx)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 18.11-pasca
| Versi PHP        | 
| System operasi   |

**Comment by muhtar-coder** [comment]
Maaf untuk #1770 kalo lengkapnya yang di tuntut kepada setiap desa pelaporanya seperti ini:
https://drive.google.com/file/d/131RLA1zVmXR20nQkvfBc5JphA7GPE799/view?usp=drivesdk

**Comment by eddieridwan** [comment]
@muhtar-coder , link anda tidak bisa dibuka. Hak aksesnya perlu diubah supaya bisa dibuka umum.

**Comment by eddieridwan** [comment]
@muhtar-coder Kalau Permen No 47 sudah banyak yg melampirkan, termasuk di https://github.com/OpenSID/OpenSID/issues/2388, https://github.com/OpenSID/OpenSID/issues/2272, https://github.com/OpenSID/OpenSID/issues/1677. Ada banyak, karena teman2 tidak memeriksa dulu apakah sudah ada yg melaporkan, sebelum membuat issue.
