### ISSUE TITLE
[DPT] Input Jadwal Pemilihan di Menu Kependudukan > Calon Pemilih

### ISSUE THREAD

**Issue by hasap86** [OpenSID/OpenSID#1772]
![jadwal-pemilu](https://user-images.githubusercontent.com/45263721/49080048-e95b4100-f274-11e8-8a05-7dafa41f0c20.jpg)

### Bagaimana alurnya sampai muncul masalah?
Saat ini hanya baru mendukung 1 waktu pemilihan, sehingga ketika terubah tanggalnya ke tgl. hari ini ketika dibuka menu Calon Pemilih _(mungkin seharusnya tidak berubah ke tgl. hari ini saat dibuka jika sebelumnya sudah menentukan tgl. pemilihan)_ tanggal pemilihan harus kita tentukan kembali, karena jika tidak tampilan di web pun mengikuti pemilihan pada tanggal hari ini (saat dibuka menu Calon Pemilih.

### Seperti apa yang diharapkan?
Mungkin dibuatkan inputan Jadwal Pemilihan dengan Nama Pemilihan dan Tanggalnya, Misal Pemilihan Presiden, Pemilihan Gubernur, Pemilihan Kepala Desa, Pemilihan, RT, RW, dan sebagainya. dengan penyajian data berdasarkan jadwal tersebut termasuk di web.

### Apa yang terjadi?
saat ini harus selalu menentukan tanggal ketika membuka menu Calon Pemilih

### Informasi tambahan 
mungkin perlu juga pilihan beberapa kriteria pemilih pada saat pembuatan jadwal, misal untuk seluruh penduduk untuk pemilihan gubernur/walikota/presiden/legislatif. Namun untuk pemilihan RT, RW, Dusun tertentu kriteria RT, RW berapa saja ada pemilahannya.

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 18.11-pasca
| Versi PHP        | 
| System operasi   |

**Comment by andifahruddinakas** [comment]
Sudah digabungkan melalui commit https://github.com/OpenSID/premium/commit/f81c8a237e88c4b16074eb309c21f4f974501d79 dengan penyesuaian pada fitur premium.
