### ISSUE TITLE
Kesalahan penulisan Jabatan pada Staf Pemerintahan

### ISSUE THREAD

**Issue by hasap86** [OpenSID/OpenSID#1773]
![tulisan-jabatan-staf-pemerintahan](https://user-images.githubusercontent.com/45263721/49081497-a8196000-f279-11e8-9d0d-ce3f1ca34cf4.jpg)

### Bagaimana alurnya sampai muncul masalah?
Penulisan Title Jabatan di menu penambahan dan pengeditan Staf Pemerintah Desa tertulis **Jabtan**

### Seperti apa yang diharapkan?
seharusnya **Jabatan**

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | Versi 18.11-pasca
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah diperbaiki pada issue #1750
