### ISSUE TITLE
Info RW & Dusun saat input/edit RT

### ISSUE THREAD

**Issue by hasap86** [OpenSID/OpenSID#1774]
![info-rw-saat-edit-rt](https://user-images.githubusercontent.com/45263721/49084394-ec106300-f281-11e8-8152-901374b9f525.jpg)
![info-rw-saat-edit-rt-contoh](https://user-images.githubusercontent.com/45263721/49084395-eca8f980-f281-11e8-97cb-801697662b5f.jpg)

### Bagaimana alurnya sampai muncul masalah?
Ketika melakukan edit/tambah RT tidak terdapat informasi RW & Dusunnya

### Seperti apa yang diharapkan?
di infokan RW & Dusunnya supaya tidak lupa sedang mengedit/tambah RT di RW & Dusun mana.

### Apa yang terjadi?
haru melakukan back untuk mengetahui info RW & Dusunnya

### Informasi tambahan 
terkadang ketika saat mau melakukan input kelupaan posisinya sedang di RW & Dusun mana.

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | Versi 18.11-pasca
| Versi PHP        | 
| System operasi   |

**Comment by lukman48** [comment]
Apakah ini sama dengan issue {##1771} atau {##1766} bukan yach pa?

**Comment by lukman48** [comment]
kalau misalkan breadcumb diganti menjadi **home - [nama dusun yang dipilih] - [nama rt]** yang menu sebelah kanan atas. jadi biar tahu posisi terakhirnya

**Comment by hasap86** [comment]
Contoh tampilannya samakan saja dengan tampilan ketika kita melihat Data Dusun, Data RW, Data RT seperti ini ditampilkan informasinya, ketika kita membuka RW, ada informasi Dusun Apa, Ketika Membuka RT ada informasi RW berapa Dusun Apa, namun ketika Edit informasi itu tidak ditampilkan, seharusnya ditampilkan juga seperti gambar dibawah ini saat kita melihat data RT.

![info-rw-saat-edit-rt-contoh](https://user-images.githubusercontent.com/45263721/49084395-eca8f980-f281-11e8-97cb-801697662b5f.jpg)
