### ISSUE TITLE
Module pemetaan Tidak Tampil Selalu meminta konfigurasi Identitas Desa

### ISSUE THREAD

**Issue by andryrukandifauzy** [OpenSID/OpenSID#1775]
### Bagaimana alurnya sampai muncul masalah?
pilih module pemetaan > Meminta konfigurasi identitas desa
padahal identitas desa sudah di isi dan unntuk peta kantor desa dan wilyayah desa sudah di isi 

### Seperti apa yang diharapkan?
ketikan dibuka module pemetaan muncul normal seperti biasa

### Apa yang terjadi?

Selalu meminta konfigurasi padahal sudah diisi,tidak bisa membuka module peta atau GIS
### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 
| Versi PHP        | 
| System operasi   |

**Comment by andryrukandifauzy** [comment]
untuk yang di demo atau beta itu lancar , tapi yang terjadi dengan opensid punya saya tidak tahu kenapa selalu minta untuk konfigurasi terus pak

**Comment by hasap86** [comment]
Versi berapa? Offline atau Online?

**Comment by andryrukandifauzy** [comment]
versi terbaru  Online
