### ISSUE TITLE
[Bug] Lambang Desa tidak terupload saat pertama kali mengisi Identitas Desa

### ISSUE THREAD

**Issue by hasap86** [OpenSID/OpenSID#1776]
### Bagaimana alurnya sampai muncul masalah?
ketika pertama kali mengisi Identitas Desa, Lambang Desa tidak terupload sedangkan data lain tersimpan.

### Seperti apa yang diharapkan?
seharusnya ikut terupload bersamaan dengan mengisi form identitas desa

### Apa yang terjadi?
harus mengupload ulang

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 18.11-pasca
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
