### ISSUE TITLE
arsip surat untuk database yang sudah di update nama pemohon tidak sesuai

### ISSUE THREAD

**Issue by hendriendric** [OpenSID/OpenSID#1777]
### Bagaimana alurnya sampai muncul masalah?
setelah update database kependudukan, tampilan nama pemohon untuk arsip surat tidak sesuai, kemungkinan ini terjadi karena id penduduk sudah berubah di database yang baru. dan nama pemohon menggunakan id sebagai acuan bukan NIK

### Seperti apa yang diharapkan?
nama pemohon agar sama dengan yang diharapkan, sehingga ketika akan mengambil arsip surat tidak salah.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 18.11
| Versi PHP        | 5.6.33
| System operasi   | windows 10

**Comment by eddieridwan** [comment]
@hendriendric : Database penduduk diupdate menggunakan cara apa? Beri contoh perubahan yg dilakukan dan jelaskan mengapa dilakukan dengan cara itu.

**Comment by eddieridwan** [comment]
Cara memasukkan data dari SIAK seperti apa? Menu impor mana? Atau ketik langsung? Apakah dengan cara menghapus data lama?

**Comment by hendriendric** [comment]
impor dengan menghapus data lama master

**Comment by eddieridwan** [comment]
Ya, kalau data lama dihapus, jelas id data penduduk akan berubah, dan kaitan ke SEMUA data lainnya (surat, bantuan, rumah tangga, kelompok, analisis, peta, dsbnya) akan terputus, karena memang menggunakan id. Mengapa menggunakan id dan tidak NIK? Karena pengisian NIK bisa saja salah dan nanti diubah (misalnya penduduk yg belum memiliki NIK diberikan isian 0).

Jadi pada waktu impor, data lama jangan dihapus (yaitu jangan centang box pilihan hapus data lama). Pada waktu impor, data yg diimpor akan menggantikan data di database dengan NIK yg sama.

Tetapi sepertinya strategi data anda tidak sesuai dengan fungsi SID teman2 desa lain. Justru mereka paham data SID mereka tidak akan selalu sama dengan yg di Disdukcapil, di mana data SID di desa biasanya akan LEBIH MUTAKHIR, lebih benar dan lebih lengkap (ada data tambahan untuk keperluan desa selain Disdukcapil). Dan itu justru kelebihan SID desa -- kedaulatan data desa, menggunakan data desa untuk maksimal manfaat desa.

Silakan anda bahas ini di forum FB (https://www.facebook.com/groups/OpenSID/) untuk mendapatkan pengalaman/perspektif teman2 desa lainnya.

**Comment by hendriendric** [comment]
baru tahu bung eddie kalau tanpa mencentang hapus pun data lama tetap akan digantikan data baru yang niknya sama jika ada perubahan. saya kira apabila saya tidak mencentang hapus, data yang sudah ada nik di dalamnya tidak bisa masuk lagi. jadi data tidak terupdate

**Comment by eddieridwan** [comment]
Issue ini bisa ditutup, karena masalah sudah terjawab.
