### ISSUE TITLE
Backup & Restore Error

### ISSUE THREAD

**Issue by hasap86** [OpenSID/OpenSID#1779]
![error-restore](https://user-images.githubusercontent.com/45263721/49203685-bf705e80-f3db-11e8-87b3-217ff0fcb3f7.jpg)

### Bagaimana alurnya sampai muncul masalah?
Ketika melakukan Restore dari data hasil Backup terjadi Error

### Seperti apa yang diharapkan?
tidak terjadi error

### Apa yang terjadi?
tidak bisa restore

### Informasi tambahan 
Catatan Error : [Error-Restore.txt](https://github.com/OpenSID/OpenSID/files/2627867/Error-Restore.txt)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 18.11-pasca
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui #2133
