### ISSUE TITLE
Penambahan Modul SPPD dan Surat Tugas

### ISSUE THREAD

**Issue by asepzhepots** [OpenSID/OpenSID#1781]
### Bagaimana alurnya sampai muncul masalah?
Di menu sekretatiat terdapat sub menu pembuatan surat, tetepi belum ada sub menu SPPD (Surat Perjalanan Dinas)

### Seperti apa yang diharapkan?
Agar menambahkan modul SPPD dan Surat Tugas

### Apa yang terjadi?
Saya rasa akan semakin lengkap jika modul itu ada dan menambah nilai bagi Opensid

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by suphm** [comment]
sebelum posting isu baru sebaiknya dicari dulu.
sepertinya ini duplikat #720

**Comment by suphm** [comment]
sebelum posting isu baru sebaiknya dicari dulu.
jika  ini duplikasi #720, harap isu ini ditutup.
trims
