### ISSUE TITLE
[Bug] Tambah Surat Baru dengan nama sama

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#1782]
### Bagaimana alurnya sampai muncul masalah?
Ketika tambah Surat baru dengan nama Surat yang sudah ada pada opensid terjadi error basis data

### Seperti apa yang diharapkan?
mungkin bisa diganti dengan error message / lainnya

### Apa yang terjadi?
terjadi error basis data

### Informasi tambahan 
![wee3](https://user-images.githubusercontent.com/35319600/49304648-98ab4880-f4ff-11e8-9dd3-36087a35499b.jpg)
| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | beta.opensid.info
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR #1788
