### ISSUE TITLE
Tambahkan Setting Surat Nomor Berurutan dengan Kode Surat yang Sama

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#1783]
### Bagaimana alurnya sampai muncul masalah?
ditempat kami surat keterangan a, b, c, d, e, dst (masuk dalam satu Kode Surat Yang Sama (100 - Pemerintahan) sedangkan Pindah datang pindah keluar (473 - Informasi Kependudukan) atau Kelahiran Kematian (472 - Pencatatan Sipil) ) (surat masuk maupun surat keluar sama)

### Seperti apa yang diharapkan?
ditambahkan Setting Surat berurutan Dengan Kode Surat Yang Sama

### Apa yang terjadi?
belum ada,

### Informasi tambahan 

![wee3](https://user-images.githubusercontent.com/35319600/49305981-76b3c500-f503-11e8-80f2-0cda351f988c.jpg)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by suphm** [comment]
urutkan berdasarkan kode surat, ya.

**Comment by balongbesuk** [comment]
Iya mas, satu kode surat memiliki beberapa jenis surat, (misal kode surat 100 memiliki banyak jenis surat seperti surat keterangan tidak mampu, surat keterang status, surat keterangan usaha, dll (biasanya diawali dengan surat keterangan ...... )),
