### ISSUE TITLE
Detail Artikel Statis Agenda

### ISSUE THREAD

**Issue by hasap86** [OpenSID/OpenSID#1784]
### Bagaimana alurnya sampai muncul masalah?
Kurang Inputan Detail Agenda, sehingga saat penyajian di widget kurang informatif bahkan salah penyajian, biasanya yg dimunculkan itu tanggal agendanya bukan tanggal postingnya

![agenda](https://user-images.githubusercontent.com/45263721/49322992-00858180-f548-11e8-91c9-c9d287ecdb84.jpg)

### Seperti apa yang diharapkan?
Ditambahkan Detail Inputan Agenda seperti 

- Tanggal : 
- Jam :
- Lokasi :
- Kontak :

### Apa yang terjadi?
lebih mudah dalam pengisian Agenda jika ada inputan detail

### Informasi tambahan 
detail inputan di tampilkan di web publik dalam bentuk Agenda berdasarkan inputan bukan hanya sekedar artikel biasa (menu khusus Agenda)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 18.11-pasca
| Versi PHP        | 
| System operasi   |

**Comment by suphm** [comment]
kalo saya melihat contoh artikel agenda isinya berita agenda yang telah dilaksanakan.

**Comment by suphm** [comment]
kalo saya melihat contoh artikel agenda isinya berita agenda yang telah dilaksanakan.

sedangkan fitur yang diminta saya kira bisa dibuatkan widget dan halaman kalender

**Comment by suphm** [comment]
https://github.com/eboominathan/Basic-Crud-in-Full-Calendar-Using-Codeigniter-3.0.3

**Comment by eddieridwan** [comment]
Tanggal agenda sudah dikerjakan di issue #1944

**Comment by eddieridwan** [comment]
Inti issue ini telah dicommit ke master melalui PR #1955. 
Untuk pengembangan agenda selanjutnya, silakan buat issue baru.
