### ISSUE TITLE
Level Sub Menu ditambah

### ISSUE THREAD

**Issue by hasap86** [OpenSID/OpenSID#1785]
### Bagaimana alurnya sampai muncul masalah?
Keterbatasan Level Sub Menu hanya 1 sub menu

### Seperti apa yang diharapkan?
ditambahkan di Sub Menu bisa menambah 1 Submenu lagi, Menu > Submenu 1 > Submenu 2

### Apa yang terjadi?
Alur Menu bisa bersub sub.... Menu > Submenu 1 > Submenu 2

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 18.12
| Versi PHP        | 
| System operasi   |

**Comment by suphm** [comment]
ini di admin atau webnya?

**Comment by hasap86** [comment]
> ini di admin atau webnya?

tentunya input di admin web, dimunculkan di web publiknya

**Comment by afa28** [comment]
Mungkin u/ sementara tambah 1 level submenu.
