### ISSUE TITLE
[Bug] Error ketika klik menu surat masuk

### ISSUE THREAD

**Issue by pandigresik** [OpenSID/OpenSID#1786]
### Bagaimana alurnya sampai muncul masalah?
Klik menu Sekretariat - Surat Masuk atau Surat Keluar

### Seperti apa yang diharapkan?
Tidak terjadi error database

### Apa yang terjadi?
![cuplikan layar dari 2018-12-02 06-55-10](https://user-images.githubusercontent.com/1853475/49334110-c5df2000-f5ff-11e8-82f0-e4a53798d0bc.png)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 18.12-pasca
| Versi PHP        |  PHP 7.2.10-0ubuntu0.18.04.1
| System operasi   | Linux Mint 19

**Comment by pandigresik** [comment]
https://github.com/OpenSID/OpenSID/pull/1787

**Comment by pandigresik** [comment]
Sudah diperbaiki branch fix-bug-surat-masuk

**Comment by eddieridwan** [comment]
Error ini hanya terjadi kalau setting mysql strict mode.

Sudah dicommit ke master melalui PR #1789
