### ISSUE TITLE
[Bug] Cetak Surat tidak menampilkan nama penandatangan staf desa 

### ISSUE THREAD

**Issue by gugel88** [OpenSID/OpenSID#1790]
### Bagaimana alurnya sampai muncul masalah?
Saat mencetak surat, Nama tanda tangan Staf Pemerintah Desa tidak muncul hanya muncul Jabatan saja

### Apa yang terjadi?
Bug ini terjadi ketika ada perubahan Staf Pemerintah Desa dari TIDAK TERDATA menjadi DARI DATABASE PENDUDUK

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 18.12-pasca
| Versi PHP        | 5.4.45
| System operasi   | Linux

**Comment by gugel88** [comment]
![screenshot_16](https://user-images.githubusercontent.com/27330955/49336088-03f33880-f62e-11e8-800d-898ff44a866e.png)

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
