### ISSUE TITLE
Naik Turun Widget Admin Web

### ISSUE THREAD

**Issue by hasap86** [OpenSID/OpenSID#1791]
### Bagaimana alurnya sampai muncul masalah?
Saat kita menaikan / menurunkan Widget di Admin Web pada posisi halaman 2 dst, halaman kembali ke halaman 1, padahal posisi widget yg kira rubah masih di halaman 2 dst.

### Seperti apa yang diharapkan?
Seharusnya saat menaikan / menurunkan posisi widget, halaman dipertahankan pada posisi dimana halaman itu berada kecuali jika widget itu urutannya sudah memasuki halaman 1.

### Apa yang terjadi?
jika tidak dipertahankan, maka karena saat menaikan / menurunkan posisi widget di halaman 2 pindah ke halaman 1, padahal posisi widget masih di halaman 2.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 18.11-pasca
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR #1827.
