### ISSUE TITLE
[Bug] Nama Kepala Dusun menjadi kosong setelah mengubah data Dusun lainnya.

### ISSUE THREAD

**Issue by hasap86** [OpenSID/OpenSID#1792]
### Bagaimana alurnya sampai muncul masalah?
Saat merubah data dusun, misalnya **Dusun 1** menjadi **Dusun I**, Nama Kepala Dusunnya menjadi Kosong setelah disimpan

### Seperti apa yang diharapkan?
harusnya tidak kosong / pertahankan data yg ada

### Apa yang terjadi?
harus merubah nama kepala dusun kembali satu persatu

### Informasi tambahan 
kasusnya mirip seperti pada issue #1771 pada RT

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 18.12-pasca
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR #1798
