### ISSUE TITLE
Title Halaman Web menggunakan Judul

### ISSUE THREAD

**Issue by hasap86** [OpenSID/OpenSID#1793]
### Bagaimana alurnya sampai muncul masalah?
Saat ini judul halaman web berdasarkan website title + nama desa - nomor artikel (Atikel 110), sehingga setiap halaman web hampir sama judulnya.

### Seperti apa yang diharapkan?
seharusnya Title web berdasarkan Judul Artikel / berdasarkan nama kategori / dll. embel embel pemerintah desa nya setelah Judul Artikel / Kategori. 
Cth Title Web: 

1. **Profil Wilayah Desa - Pemerintah Desa A**, 
2. **Visi & Misi - Pemerintah Desa A**

Khusus halaman Awal Web mengambil data setingan Website Title Homepage (perlu dibuat input baru)

### Apa yang terjadi?
di data pencarian mesin pencari kurang optimal

### Informasi tambahan 
Title web mempengaruhi hasil pencarian di mesin pencari khususnya google, sehingga untuk mengoptimalkan Search Engine Optimization (SEO) pada mesin pencari harus merubah struktur Title Web menjadi yg lebih informatif.

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 18.12-pasca
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Apakah ini sama dengan #1645 ?

**Comment by hasap86** [comment]
Berbeda, tapi bisa jadi satu kesatuan untuk mengoptimalkan Search Engine Optimization (SEO) pada mesin pencari ... pada Issue #1645 itu struktur link urlnya, untuk Issue ini Title Browsernya...

**Comment by hasap86** [comment]
![seo-url-title](https://user-images.githubusercontent.com/45263721/49346542-d4443f00-f6c6-11e8-8b3d-99c4a23c417c.png)

**Comment by balongbesuk** [comment]
ini kalau tidak salah perlu ubahan pada header meta themanya,

<meta property="og:type" content="article"/>
<?php if(isset($single_artikel)): ?>
	<title><?php echo $single_artikel["judul"] . " - $desa_title" ?></title>
	<meta name='description' content="<?php echo str_replace('"', "'", substr(strip_tags($single_artikel['isi']), 0, 400)); ?>" />
	<meta property="og:title" content="<?php echo $single_artikel["judul"];?>"/>
	<?php if (trim($single_artikel['gambar'])!=''): ?>
	<meta property="og:image" content="<?php echo base_url()?><?php echo LOKASI_FOTO_ARTIKEL?>sedang_<?php echo $single_artikel['gambar'];?>"/>
	<?php endif; ?>
	<meta property='og:description' content="<?php echo str_replace('"', "'", substr(strip_tags($single_artikel['isi']), 0, 400)); ?>" />
<?php else: ?>
	<title><?php $tmp = ltrim(get_dynamic_title_page_from_path(), ' -'); echo (trim($tmp)=='') ? $desa_title : "$tmp - $desa_title"; ?></title>
	<meta name='description' content="<?php echo $this->setting->website_title . ' ' . $desa_title; ?>" />
	<meta property="og:title" content="<?php echo $desa_title;?>"/>
	<meta property='og:description' content="<?php echo $this->setting->website_title . ' ' . $desa_title; ?>" />
<?php endif; ?>
<meta property='og:url' content="<?php echo current_url(); ?>" />

**Comment by balongbesuk** [comment]
tambahkan og:type

![untitled222](https://user-images.githubusercontent.com/35319600/49348500-6bfe5900-f6d8-11e8-965c-f92b8619f805.jpg)

![untitled221](https://user-images.githubusercontent.com/35319600/49348511-74ef2a80-f6d8-11e8-9ef5-219623fa9b2b.jpg)
