### ISSUE TITLE
[Bug] Artikel Teks Berjalan tetap muncul di Scroller dalam kondisi Artikel Non Aktif

### ISSUE THREAD

**Issue by hasap86** [OpenSID/OpenSID#1794]
### Bagaimana alurnya sampai muncul masalah?
Artikel Teks Berjalan Non Aktif tetap muncul di Scroller

### Seperti apa yang diharapkan?
seharusnya tidak muncul dalam kondisi Non Aktif

### Apa yang terjadi?
tidak sesuai kondisi

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 18.12-pasca
| Versi PHP        | 
| System operasi   |

**Comment by agungsugiarto** [comment]
Oh ternyata mas @lukman48 sudah melakukan PR duluan untuk issue ini, baru sadar saya.

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR #1798

**Comment by balongbesuk** [comment]
maksud teks berjalan kan memang niatnya dikunci akan tidak ditampilkan di beranda berita desa dan hanya tampil pada bar tampilan teks berjalan?
