### ISSUE TITLE
Security: Password Cpanel

### ISSUE THREAD

**Issue by mugi789** [OpenSID/OpenSID#1795]
Ganti password cpanel dari domain opensid.info

### Bagaimana alurnya sampai muncul masalah?
Pas waktu dulu masih upload di setting avatar, saya klik config > menemukan password database di configuration.php

### Seperti apa yang diharapkan?
Jangan samakan password cpanel sama password DB

### Apa yang terjadi?
Bisa menguasai seluruh isian website opensid.info

### Informasi tambahan 
Saya kira passwordnya udh diganti, ternyata sampe sekarang belum diganti. Cepet2 ganti ya pak :)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.5
| Versi PHP        | 
| System operasi   |

**Comment by mugi789** [comment]
Untuk semua yg baca issues ini, intinya "Jangan Samakan Password Cpanel dengan Password DB (Database)"

**Comment by hasap86** [comment]
gimana proses bibsa ketauan password databasenya?

**Comment by mugi789** [comment]
waktu dulu masih terdapat bug upload shell di avatar, saya upload shell > view configuration.php
saya coba copy passwordnya > lalu coba2 login cpanel, dan ternyata bisa masuk

sampe sekarang pass nya blm diganti

**Comment by metalab25** [comment]
sudah saya ganti
