### ISSUE TITLE
Penambahan Tombol aksi naik/turun pada menu Info Desa/Pemerintahan Desa

### ISSUE THREAD

**Issue by PWidodo** [OpenSID/OpenSID#1797]
![tombol aksi untuk mengurutkan data](https://user-images.githubusercontent.com/45189822/49350158-7d4b6380-f6e0-11e8-9e96-90d41242eceb.png)

### Bagaimana alurnya sampai muncul masalah?
Data pamong yang di entri pertamakali biasanya adalah Kepala Desa/Kepala Kampung/Lurah dsb, lalu setelah data pamong lain seperti Sekretaris (Desa/Kampung/Gampong/Nagari/Lurah), para kasi, para kaur, para kawil/kadus, dan para staf urusan di entry, data jabatan Kepala Desa atau sebutan lain tergeser otomatis pada posisi ditengah atau paling akhir urutan data.

### Seperti apa yang diharapkan?
Sesuai dengan urutan jabataannya (SOTK), Pemerintah Desa atau sebutan lain harusnya struktur datanya sbb:
1. Kepala Desa atau sebutan lain
2. Sekretaris Desa atau sebutan lain
3. Kasi Pemerintahan
4. Kasi Kesejahteraan
5. Kasi Pelayanan
6. Kaur Keuangan
7. Kaur Perencanaan
8. Kaur Umum dan Tata Usaha
9. Kepala Dusun/Kepala Wilayah, atau sebutan lain
10. Staf Urusan

### Apa yang terjadi?
Jika pada form tersebut diberi tombol AKSI (naik/turun) untuk mengurutkan Data Pamong, maka masalah ini dapat teratasi.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 18.12
| Versi PHP        | 
| System operasi   |

**Comment by hasap86** [comment]
di form tambah / edit, dikasih 1 inputan aja **No. Urut**, jadi di tampilkan sesuai urutan 1,2,3 dst... sehingga tiap desa bisa menyesuaikan sendiri urutannya :)

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.

**Comment by andryrukandifauzy** [comment]
https://github.com/OpenSID/OpenSID/issues/1803
