### ISSUE TITLE
Tidak Bisa Mencetak KK dan Biodata Di layanan Mandiri WPSID Shortcode

### ISSUE THREAD

**Issue by andryrukandifauzy** [OpenSID/OpenSID#1799]
### Bagaimana alurnya sampai muncul masalah?
Masuk layanan Mandiri> Cetak KK atau Biodata

Tidak Bisa Mencetak 

![screenshot_13](https://user-images.githubusercontent.com/42363553/49363891-712dc900-f715-11e8-9c16-ab9df2a3872d.png)

### Seperti apa yang diharapkan?

Bisa Mencetak KK seperti  di layanan mandiri biasa
### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 18.12
| Versi PHP        | 
| System operasi   |
wpsidshortcode

**Comment by eddieridwan** [comment]
@andryrukandifauzy issue wpsid mohon dimasukkan ke repo https://github.com/OpenSID/wpsid-shortcode. Perbaikan wpsid dilakukan di situ. Silakan pindahkan, dan kemudian tutup issue ini. Terima kasih.
