### ISSUE TITLE
Databas Error Pamong_model.php Di Hosting

### ISSUE THREAD

**Issue by andryrukandifauzy** [OpenSID/OpenSID#1803]
### Bagaimana alurnya sampai muncul masalah?

Setelah mencoba repo terbaru muncul begini di hosting
![screenshot_14](https://user-images.githubusercontent.com/42363553/49484156-9717b280-f868-11e8-9322-1f9c5e0e102c.png)
![screenshot_15](https://user-images.githubusercontent.com/42363553/49484173-ab5baf80-f868-11e8-83a7-32d9fc7aa7bb.png)

### Seperti apa yang diharapkan?

Normal kembali
### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
@andryrukandifauzy apakah sudah menjalankan Migrasi DB?

**Comment by andryrukandifauzy** [comment]
Saya install baru pak, Belum bisa masuk Ke siteman, Langsung Muncul error

**Comment by eddieridwan** [comment]
Langsung saja ke siteman (masukkan http://server-anda/index.php/siteman di browser). Bisa login di situ, terus jalankan Migrasi DB.

**Comment by andryrukandifauzy** [comment]
oke pak saya coba

**Comment by hasap86** [comment]
iya biasanya kalo gitu langsung masuk aja ke siteman, lalu jalankan migrasi DB...

**Comment by andryrukandifauzy** [comment]
ok solved
