### ISSUE TITLE
Penambahan Role Pengguna/User

### ISSUE THREAD

**Issue by gugel88** [OpenSID/OpenSID#1804]
### Bagaimana alurnya sampai muncul masalah?
-

### Seperti apa yang diharapkan?
**Menambahakan role pengguna/user baru, contoh:**
1. **Operator Inventaris** dimana user ini hanya boleh mengelola menu Inventaris saja, sebagaimana di atur dalam regulasi UU No. 6 th 2018 ttg Desa serta  Permendagri No. 1 th 2016 ttgPengelolaan Aset Desa
2. **Operator Kependudukan / Petugas Registrasi Desa** dimana user ini hanya boleh mengelola menu Kependudukan saja, sebagaimana di atur dalam regulasi UU No 23 Tahun 2006, UU 24 Tahun 2013, dan Permendagri 119 tahun 2017

### Apa yang terjadi? Selanjutnya
Ini akan mempermudah Administrator/Operator/Perangkat Desa dalam menjalankan tugas, pokok, dan fungsinya

### Informasi tambahan 
Bisa saja ada pengaturan khusus untuk setiap menu/fitur dapat dikelola oleh user/pengguna yang telah di tentukan/disetting sebelum nya, contoh: Menu A hanya boleh di akses oleh User Role A, Menu B hanya boleh di akses oleh User Role B, dan seterusnya.

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 18.12-pasca
| Versi PHP        | 5.4.45
| System operasi   | Linux

**Comment by eddieridwan** [comment]
Serupa dengan #1994. Terapkan fitur untuk menambah grup user baru dengan hak akses yg bisa dipilih.

**Comment by afa28** [comment]
Duplicate #1994
