### ISSUE TITLE
Bug? Kirim Laporan Pada Menu Layanan Mandiri

### ISSUE THREAD

**Issue by mugi789** [OpenSID/OpenSID#1807]
![screenshot_20181206_094405](https://user-images.githubusercontent.com/32443765/49558090-791b8200-f93c-11e8-9345-9f7290cfe145.png)

### Bagaimana alurnya sampai muncul masalah?
Ketika mau mengirimkan laporan di menu layanan mandiri, Nama Pengirim & NIK bisa diubah, dengan cara inspect element (f12) 

![screenshot_20181206_102303](https://user-images.githubusercontent.com/32443765/49559388-41630900-f941-11e8-9227-a73e9e63fc31.png)

![screenshot_20181206_102327](https://user-images.githubusercontent.com/32443765/49559401-4922ad80-f941-11e8-8ac9-2f176346a4ef.png)

### Apa yang terjadi?
Bisa mengirimkan laporan "kurang pantas" dengan Nama dan NIK orang lain

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 18.12
| Versi PHP        | 
| System operasi   |

**Comment by metalab25** [comment]
Kalo dibuat readonly bisa ga ?

**Comment by mugi789** [comment]
> 
> 
> Kalo dibuat readonly bisa ga ?

kemungkinan bisa

**Comment by suphm** [comment]
sama saja.
solusinya validasi session di php

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR #1861
