### ISSUE TITLE
halaman utama / beranda

### ISSUE THREAD

**Issue by afri18** [OpenSID/OpenSID#1808]
### Bagaimana alurnya sampai muncul masalah?
Membagi halaman beranda di FB yg timbul gambar asal asalan

### Seperti apa yang diharapkan?
Timbulkan gambar artikel utama

### Apa yang terjadi?
Timbulnya gambar ngaco saat membagi halaman beranda

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 18.12
| Versi PHP        | 
| System operasi   |

**Comment by agungsugiarto** [comment]
Silahkan diedit om @afri18 untuk melengkapi issue yang ingin disampaikan.
