### ISSUE TITLE
Penyesuaian Lembar Cetak Data Aparat Pemerintahan Desa

### ISSUE THREAD

**Issue by PWidodo** [OpenSID/OpenSID#1810]
### Bagaimana alurnya sampai muncul masalah?
Halaman cetak yang saat ini sudah ada pada OpenSID versi 18.12-pasca sudah lengkap dan baik, tetapi akan lebih bagus lagi apabila lembar cetak tersebut sesuai dengan format Buku Data Aparat Desa Model A.4 yang ada di desa, gampong, nagari, kelurahan atau sebutan lainnya.

### Seperti apa yang diharapkan?
Format lembar cetak yang kami harapkan, kami lampirkan dalam bentuk pdf

### Apa yang terjadi?
Efisiansi administrasi desa, karena OpenSID telah menyediakan laporan data aparatur desa.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 18.12-pasca
[Buku Data Aparat Pemerintahan Desa.pdf](https://github.com/OpenSID/OpenSID/files/2660271/Buku.Data.Aparat.Pemerintahan.Desa.pdf)

| Versi PHP        | 
| System operasi   |

**Comment by PWidodo** [comment]
![lembar cetak data aparat desa](https://user-images.githubusercontent.com/45189822/49695261-0411ac00-fbcb-11e8-900a-0a7e87f44fb5.png)

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
