### ISSUE TITLE
droupdown dusun>rw>rw

### ISSUE THREAD

**Issue by afri18** [OpenSID/OpenSID#1812]
### Bagaimana alurnya sampai muncul masalah?
setelah saya merubah nama dusun

### Seperti apa yang diharapkan?
seharusnya sama seperti semula

### Apa yang terjadi?
droupdown rw dan rt tidak muncul saat merubah/update alamat
![image](https://user-images.githubusercontent.com/6611881/49741363-d6129180-fcc8-11e8-9036-6929d8567725.png)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 18.12
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
@afri18 apakah sudah mencoba di v18.12-pasca? Saya coba, tidak bermasalah. Memang ada beberapa perubahan di v18.12-pasca yg mungkin telah memperbaiki masalah ini.

**Comment by afri18** [comment]
Itu sudah yg 18.12 pasca

**Comment by afri18** [comment]
Kalau d save jadi no KK kosong (nggak ada kepala keluarga Rp anggota ada), sama persis dengan edit biodata Kep keluarga ( baru d temukan tadi saat ada yg d edit)

**Comment by eddieridwan** [comment]
@afri18 apakah sudah menggunakan v18.12-pasca?

**Comment by eddieridwan** [comment]
Apakah sudah jalankan Migrasi DB? Coba ulangi di http://beta.opensid.info. Kalau bermasalah di situ, harap beritahu detailnya, supaya saya bisa periksa. Di lokal saya, tidak ada masalah.

**Comment by afri18** [comment]
Pasca tgl 05-12-2018

**Comment by eddieridwan** [comment]
Kalau edit biodata Kep keluarga memang bermasalah. Perbaikan untuk masalah ini akan segera disiapkan.

Tapi yg lain terkait perubahan nama dusun, ubah alamat KK tidak bermasalah di komputer lokal kami.

**Comment by afri18** [comment]
barusan saya unduh yg pasca baru tetap dropdown RW dan RT tidak muncul setelah di migrasi
![image](https://user-images.githubusercontent.com/6611881/49798093-06fbd080-fd74-11e8-908d-c1c4f6b4c754.png)

**Comment by afri18** [comment]
![image](https://user-images.githubusercontent.com/6611881/49798318-8ee1da80-fd74-11e8-99c9-0cc154bba2f3.png)
sukses
![image](https://user-images.githubusercontent.com/6611881/49798347-a3be6e00-fd74-11e8-9d7d-76cb2387123d.png)
hasil
![image](https://user-images.githubusercontent.com/6611881/49798447-d9635700-fd74-11e8-9444-50ab9e897b48.png)
tetep dropdown RW dan RT tidak muncul

**Comment by eddieridwan** [comment]
Ok, masalahnya terkait adanya karakter non alphanumeric di nama dusun. Yaitu adanya tanda kurung. Apakah harus menggunakan kurang? Kalau tidak ganti saja ke nama tanpa kurung.

**Comment by afri18** [comment]
betul bung @eddieridwan  setelah saya hilangkan tanda kurung jadi ada lagi
tadinya nama dusun "Satu" saya ganti menjadi "1 (Satu)" agar di tampilan berurutan
kalau Satu, Dua dan Tiga urutannya make abjad kalau dikasih nomor jadi berurutan
![image](https://user-images.githubusercontent.com/6611881/49798936-2693f880-fd76-11e8-9d7e-90789ab32cec.png)
bisa ditutup kalau begitu

**Comment by eddieridwan** [comment]
Ok, @afri18: Sudah diperbaiki. Sekarang nama dusun bisa berisi karakter kurung (). Juga perbaiki error mengubah data kepala keluarga. [bug-fix].

Sudah dicommit ke master (di versi pra-rilis).

**Comment by afri18** [comment]
okeh saya coba unduh lagi
