### ISSUE TITLE
BUG pada Keluarga ketika edit Bio Data kepala Kepala Keluarga

### ISSUE THREAD

**Issue by markunyil** [OpenSID/OpenSID#1814]
### Seperti apa yang diharapkan?
Daftar pada Keluarga tidak merubah atau tidak menghilangkan kepala KK, dalam tabel tweb_keluarga kepala KK menjadi NULL

### Apa yang terjadi?
Keluarga masuk dalam daftar KK kosong

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
@markunyil harap jelaskan persisnya langkah yg dilakukan sampai menghasilkan masalah ini. Lampirkan tampilan layarnya.

**Comment by afri18** [comment]
saya bantu karna di saya juga timbul
Apa yang terjadi ?
saat edit biodata kepala keluarga 
Seperti apa yang diharapkan ?
Seharusnya tidak merubah apapun kecuali biodata saja sedangkan data Keluarga tidak berubah
Apa yang terjadi ?
Nomor KK menjadi tidak ada nama Kepala Keluarga
![image](https://user-images.githubusercontent.com/6611881/49799344-4bd53680-fd77-11e8-9985-6f695920f2a1.png)

**Comment by markunyil** [comment]
![keluarga 1](https://user-images.githubusercontent.com/22595100/49799235-59b99600-fd3c-11e8-819d-0558c837a906.jpg)
Saya melakukan demo di demo.opensid.info pak, saya Kelurga dari penduduk lepas menjadi kepala KK.
![penduduk edik](https://user-images.githubusercontent.com/22595100/49799394-bb7a0000-fd3c-11e8-9234-517c67e21b98.jpg)
Kemudian saya melakukan edit biodata nama tersebut.
![kepala kk](https://user-images.githubusercontent.com/22595100/49799459-e5332700-fd3c-11e8-9767-dc36909ae108.jpg)
Nama kepala keluarga hilang.

Terimakasih Pak Syafri telah mengecek juga

**Comment by afri18** [comment]
sebenarnya dari versi 18.11 sudah terjadi, saya baru cek betul saat data Keluarga berkurang setelah edit biodata Kepala Keluarga di versi 18.12

**Comment by afri18** [comment]
mengembalikan data no KK, alamat, rt dan rw yang kosong gimana ???padahal sebelum di edit ada
![image](https://user-images.githubusercontent.com/6611881/49807790-8f3a9f80-fd8d-11e8-86b1-402c3cfb8c84.png)

**Comment by markunyil** [comment]
Sementara pake trik aja dulu, pindah status kepala keluarga sebelumnya sebagai anak atau yang lain. Refresh kemudian kembalikan lagi menjadi kepala keluarga. semoga membantu

**Comment by markunyil** [comment]
Mungkin cara saya sementara pada Penduduk_model di 
public function update($id=0)
.
. dst
//$this->keluarga_model->update_kk_level($id, $pend['id_kk'], $data['kk_level'], $data['kk_level_lama']);
kasih tanda // biar script tidak berjalan. saya coba bisa. Tapi apakah mempengaruhi yang lain saya kurang paham.

**Comment by afri18** [comment]
Yg d 18.12pasca sudah bisa , pengembalian rubah hubungan lalu jadi Kep keluarga lagi
Barusan update

**Comment by markunyil** [comment]
SIP pak

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
