### ISSUE TITLE
Admin Web media pdf

### ISSUE THREAD

**Issue by afri18** [OpenSID/OpenSID#1815]
### Bagaimana alurnya sampai muncul masalah?
Saat memasukan file pdf di artikel
![image](https://user-images.githubusercontent.com/6611881/49805190-19cbd080-fd87-11e8-9ae4-31a0dff0b420.png)
berhasil membuat link nya, begitu juga saat di intip/PREVIEW Berhasil
![image](https://user-images.githubusercontent.com/6611881/49805415-a2e30780-fd87-11e8-8d78-c07bbf97c16f.png)

### Seperti apa yang diharapkan?
Seharusnya dalam tampilan publik/web juga muncu ini tidak malah embed nya yg keluar
![image](https://user-images.githubusercontent.com/6611881/49805283-57c8f480-fd87-11e8-940c-0710e614f930.png)

### Apa yang terjadi?
belum tahu

### 
| Tanya            | Jawab
| apa ada cara memunculkan file pdf (embed yang lain???? | ---
| Versi OpenSID    | 18.12 pasca
| Versi PHP        | 
| System operasi   |

**Comment by PWidodo** [comment]
Coba edit file "config.php" yang terletak pada direktori htdocs/desa/config   lalu pada coding $config['user_admin'] = 0;    ganti angka 0 menjadi angka 1   pasti gambar dengan link kode embed akan tampil di halaman website.
![screenshot_43](https://user-images.githubusercontent.com/45189822/49923324-ae4c4500-fee5-11e8-8db5-f16b4adb2e39.png)

**Comment by eddieridwan** [comment]
@afri18 dijelaskan di panduan https://github.com/OpenSID/OpenSID/wiki/Menulis-Artikel

**Comment by afri18** [comment]
Terlewati yg ini rupanya, terimakasih @Pwidodo , @eddieridwan

**Comment by afri18** [comment]
Kalau d hp nggak muncul
Media TDK didukung

**Comment by dikisiswanto** [comment]
Sepertinya issue ini bisa ditutup

**Comment by afa28** [comment]
Pak @eddieridwan , ini mungkin sudah bisa di close.
