### ISSUE TITLE
NOMOR SURAT OTOMATIS KEMBALI KE NO 1, SETELAH HABIS TAHUN BERJALAN.

### ISSUE THREAD

**Issue by HerryWanda** [OpenSID/OpenSID#1816]
### Bagaimana alurnya sampai muncul masalah?
- Setelah akhir tahun (31 Desember 2018) dan masuk tahun baru (1 januari 2019), maka setiap registrasi nomor surat layanan di tahun baru akan dibuat baru mulai dari no. 1 --- Jadi registrasi surat yang ditahun sebelumnya akan jadi Arsip.

### Seperti apa yang diharapkan?
 " Diharapkan ada tambahan fitur secara otomatis, setelah akhir tahun (31 Desember ) maka di bulan Januari , nomor surat kembali ke awal...

### Informasi tambahan 
-- bagaimana pendapat teman2 yg lain.. mungkin issue saya bisa dijelaskan oleh teman2 yg lain...
| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by suphm** [comment]
saya barusaja menguji ini. yaitu mengatur tanggal di komputer (server yang terinstall OpenSID) ke tanggal 31-12-2020 23:57 lalu membuat beberapa surat setelah tanggal 1-1-2021 dibuat surat lagi. hasilnya
dengan setting penomoran surat = semua surat hasilnya ok

**Comment by eddieridwan** [comment]
Saya sudah tes untuk semua kasus. Tidak menemukan masalah. 

Bisa dites tanpa mengubah setting tanggal server, cukup dengan mengubah data tanggal di log_surat. 

Misalnya, untuk kasus 'setting per jenis surat':
1. cetak surat jenis x dgn nomor surat 1
2. buka form surat jenis x lagi, dan verifikasi no surat diisi dengan nilai '2'
3. di log_surat, ubah tanggal untuk surat itu menjadi tahun lalu
4. buka form surat jenis x lagi, dan verifikasi no_surat diisi dengan nilai '1

**Comment by HerryWanda** [comment]
Ok pak eddie,..
Sekrang kita close aja issue ini ya pak...
