### ISSUE TITLE
format import data penduduk disamakan dengan hasil export siak

### ISSUE THREAD

**Issue by hendriendric** [OpenSID/OpenSID#1817]
### Bagaimana alurnya sampai muncul masalah?
ketika akan import data penduduk, pengguna yang kebanyakan mengambil dari data siak harus mengolah dahulu datanya agar sama dengan format opensid

### Seperti apa yang diharapkan?
pengguna tidak harus mengolah data lagi ketika akan import data yang diperoleh dari siak, sehingga hasil export siak langsung bias diimport

### Apa yang terjadi?
dengan begitu pengguna akan lebih mudah beriku saya lampirkan format yang dari siak

### Informasi tambahan 
[FORMAT SIAK.xlsx](https://github.com/OpenSID/OpenSID/files/2671937/FORMAT.SIAK.xlsx)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by hendriendric** [comment]
[FORMAT SIAK.xlsx](https://github.com/OpenSID/OpenSID/files/2679863/FORMAT.SIAK.xlsx)
sesuai petunjuk bung Eddie saya lampirkan data real

**Comment by eddieridwan** [comment]
@hendriendric kolom NIK/No KK berbeda di file pertama dan file kedua:

1. di file pertama, berbentuk '35.2318.00000000000'
2. di file kedua, berbentuk '1000000103170000'

Yang mana yang betul?

**Comment by eddieridwan** [comment]
@hendriendric , beberapa pertanyaan lainnya:
1. contoh di kolom Gol. Darah berisi kode 'Tdk Th', sedangkan data dari Disdukcapil menggunakan kode 'TIDAK TAHU'. Apakah contoh kode anda betul?
2. di kolom Status, ada kode 'Ganda' dan 'Tidak Valid'. Baris dengan kode status seperti itu diapakan? Tetap diimpor atau tidak? Di OpenSID tidak ada kolom status seperti itu, karena penduduk tidak boleh ganda dan data harus selalu valid.
3. di kolom Status, ada kode 'pindah dalam negeri' dan 'pindah luar negeri'. OpenSID tidak membedakan tempat kepindahan. Jadi yang bisa dilakukan saat ini adalah diimpor sebagai pindah, dan luar/dalam negeri bisa ditambahkan di catatan peristiwa. 
4. di kolom Status, ada kode 'mati',  'pindah dalam negeri' dan 'pindah luar negeri'. OpenSID akan merekam data ini sebagai peristiwa ubah status dasar. Tanggal peristiwa akan menggunakan tanggal di kolom 'Tgl Entri'. Apakah ini ok?
5. kolom2 berikut tidak ada di OpenSID, sehingga tidak akan dimpor (sepertinya lebih berurusan dengan layanan Disdukcapil). Ok?
    1. Deskripsi Pekerjaan
    2. Cetak KTP
    3. Ganti KTP
    4. KTP Berakhir
    5. Petugas Registrasi
    6. Tgl Ubah
    7. Petugas Entri
    8. Tgl Entri

**Comment by hendriendric** [comment]
1. yang hasil export memang untuk kode 13 isinya tdk th
2. data dianggap ganda biasanya karena ada 2 data yang identik, tetapi di database tidak berani menghapus tanpa ada konfirmasi dari yang bersangkutan, untuk tidak valid adalah data yang terdaftar dalam database namun selama 8 tahun tidak bergerak dan atau orang yang tidak pernah melakukan perekaman ektp ketika usianya sudah lebih dari 17 tahun. data tersebut harus masuk dan harus melakukan perekaman agar datanya menjadi valid
3. ok mungkin ini tidak masalah
4. ok. selama ini mati pindah tidak menemukan masalah.
5. untuk kolom yang tidak ada di opensid bisa dilewati namun untuk import data kolomnya di excel tetap ada, soalnya hasil exportnya memang seperti itu

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
