### ISSUE TITLE
Perlu dibuatkan Statistik Kependuduk berdasarkan sakit menahun 

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#1819]
### Bagaimana alurnya sampai muncul masalah?
Di Form isian penduduk untuk data kesehatan ada form untuk sakit menahun dan di data kesehatan untuk sakit menahun belum ada di statistik Kependudukan 
![image](https://user-images.githubusercontent.com/25834335/50007240-454ef500-ffeb-11e8-8b32-863b3a2ea845.png)
![image](https://user-images.githubusercontent.com/25834335/50007251-513ab700-ffeb-11e8-952e-9c65b7fa572b.png)

### Seperti apa yang diharapkan?
Adanya Statistik Kependudukan berdasarkan Sakit menahun

### Apa yang terjadi?
Belum tersedianya statistik kependudukan berdasarkan Sakit menahun di desa melalui aplikasi OpenSID

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by dikisiswanto** [comment]
Sudah dibuatkan fitur lihat statistik berdasarkan sakit menahun. Berikut tangkapan layar dari hasil pengerjaan untuk issue ini:

![image](https://user-images.githubusercontent.com/22239074/50382723-ecfdae80-06e0-11e9-9812-9a98a057e69c.png)
_Menu lihat statistik_

![image](https://user-images.githubusercontent.com/22239074/50382745-57aeea00-06e1-11e9-818e-4e6e68661f9e.png)
_Daftar penduduk dengan kategori terkait_

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR #1832
