### ISSUE TITLE
Penyesuaian Format Cetak Laporan Bulanan pada OpenSID dengan Format Desa/Kelurahan Model A-9

### ISSUE THREAD

**Issue by PWidodo** [OpenSID/OpenSID#1820]
### Bagaimana alurnya sampai muncul masalah?
Pihak Pemerintah Kecamatan yang rutin meminta Laporan Perkembangan Penduduk setiap akhir bulan masih menganggap bahwa Laporan Bulanan Penduduk dari OpenSID masih kurang "Data Perincian Pindah" dan meminta format disamakan, sehingga kami mengetik ulang pada form kosong, mengambil data dari OpenSID.

### Seperti apa yang diharapkan?
Efisiensi kerja administrasi desa, apabila CETAK LAPORAN BULANAN pada OpenSID sesuai dengan Format A-9 yang dipakai di Pemerintahan Desa/Kelurahan

### Apa yang terjadi?
-

### Informasi tambahan 
Kami lampirkan gambar Form A-9.png dan pdf nya sebagai contoh

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 18.12
| Versi PHP        | 
[Form Laporan Bulanan Perkembangan Penduduk.pdf](https://github.com/OpenSID/OpenSID/files/2682425/Form.Laporan.Bulanan.Perkembangan.Penduduk.pdf)
![form laporan bulanan penduduk](https://user-images.githubusercontent.com/45189822/50039663-60137f00-0068-11e9-8d16-06d30756c805.png)

| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
