### ISSUE TITLE
Fitur Impor BIP Format RT

### ISSUE THREAD

**Issue by ekoexsa** [OpenSID/OpenSID#1821]
### Bagaimana alurnya sampai muncul masalah?
Kami menggunakan versi OpenSID 18.12. BIP yang kami punya adalah BIP RT yang kami konvert dari file PDF. Sampai saat issue ini kami sampaikan kami mesih belum berhasil melakukan import BIP. Format yang paling dekat bentuknya adalah BIP Format 2012.

### Seperti apa yang diharapkan?
Kami sangat berharap Opensid dapat melakukan proses import BIP dari Format RT yang dion

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 18.12
| Versi PHP        | 
| System operasi   |

**Comment by ekoexsa** [comment]
Berikut kami lampirkan file BIP RT format excel hasil konversi dafil file PDF
[BIP_RT.xlsx](https://github.com/OpenSID/OpenSID/files/2682927/BIP_RT.xlsx)

**Comment by ekoexsa** [comment]
berikut format bip hasil editan yang sudah disesuaikan semirip mungkin tapi masih gagal di impor
[format_bip_2012.zip](https://github.com/OpenSID/OpenSID/files/2688562/format_bip_2012.zip)

**Comment by eddieridwan** [comment]
Lampirkan screenshot errornya.

**Comment by ekoexsa** [comment]
![2018-12-18_17-45-38](https://user-images.githubusercontent.com/23462989/50149147-f7890400-02ec-11e9-8eb7-35e34f539293.jpg)
Letak baris gagal adalah fomat bip yang saya sisipkan dari BIP RT yang sukses terimpor adalah data asli dari file template

**Comment by afa28** [comment]
Apakah ini masih bermasalah??? Kalau tdk silahkan di close.

**Comment by mizwaruddin** [comment]
Bisa disiasati dengan meng-copy paste dari format BIP RT ke format yg sudah disediakan di Impor BIP.
