### ISSUE TITLE
Mengubah status penduduk mati ketika salah input

### ISSUE THREAD

**Issue by hendriendric** [OpenSID/OpenSID#1822]
### Bagaimana alurnya sampai muncul masalah?
Ketika salah input data penduduk yang statusnya mati dan pindah ke luar desa tidak dapat ditarik lagi dan harus input seperti penduduk baru.

### Seperti apa yang diharapkan?
diberikan akses untuk mengembalikan penduduk yang mati dan pindah keluar desa menjadi penduduk hidup karena ada kemungkinan pengguna salah memasukkan data penduduk mati dan pindah

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 18.12
| Versi PHP        | 5.6
| System operasi   | win 10

**Comment by eddieridwan** [comment]
Sudah ada fiturnya. Lihat gambar di bawah.
Panduan memang belum dilengkapi/diperbaharui. Mungkin anda bersedia membantu melengkapi di wiki halaman Penduduk?

![kembalikan-status](https://user-images.githubusercontent.com/249563/50135113-27350d80-02e7-11e9-9c67-763c82a70fdf.jpg)

**Comment by eddieridwan** [comment]
@hendriendric sebaiknya tanya dulu di https://www.facebook.com/groups/OpenSID/, dan hanya buat issue kalau sudah yakin memang sesuatu yg perlu dikerjakan.
