### ISSUE TITLE
Tambahkan fungsi hapus arsip surat otomatis untuk arsip surat yang lebih dari 2 - 5 tahun

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#1823]
### Bagaimana alurnya sampai muncul masalah?
arsip surat yang lebih dari satu tahun atau lebih harus menghapus manual dari folder arsip

### Seperti apa yang diharapkan?
bisa ditambahkan setting hapus arsip surat otomatis berjangka waktu dengan opsi, ( tidak dihapus, 1 tahun lebih, 2 tahun lebih 3 tahun lebih, 4 tahun lebih, 5 tahun lebih ) agar kapasitas penyimpanan tetap ramping 

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by suphm** [comment]
mungkin pertimbangkan: hapus yang sudah tidak berlaku

**Comment by boedyirh** [comment]
Sebaiknya tidak dihapus, Cukup diberi field IsDeleted. Yang mana 1 adalah tanda tidak ditampilkan. 0 berarti masih dipakai.

**Comment by afri18** [comment]
Betuuul jangan d hapus, justru itu salah satu andalan OPENSID

**Comment by balongbesuk** [comment]
ini hanya optional (agar kapasitas penyimpanan di hosting tidak membengkak)

> bisa ditambahkan setting hapus arsip surat otomatis berjangka waktu dengan opsi, ( tidak dihapus, 1 tahun lebih, 2 tahun lebih 3 tahun lebih, 4 tahun lebih, 5 tahun lebih ) agar kapasitas penyimpanan tetap ramping

**Comment by afri18** [comment]
Arsip d sekretariat jangan dihapus, kalau arsip surat keluar/layanan tiap tahun setuju

**Comment by mizwaruddin** [comment]
untuk mengatasi pembengkakan kapasitas penyimpanan di hosting, bisa dilakukan dengan membackup-nya di komputer.
