### ISSUE TITLE
Perbaikan CHAPTA untuk Keamanan Komentar

### ISSUE THREAD

**Issue by PWidodo** [OpenSID/OpenSID#1826]
### Bagaimana alurnya sampai muncul masalah?
Gambar CHAPTA kurang besar sedikit sehingga pengunjung yang hendak meninggalkan/mengirim komentar susah mengidentifikasi KODE CHAPTA.
### Seperti apa yang diharapkan?
Gambar CHAPTA untuk diperbesar agar mudah di identifikasi serta  setelah klik tombol KIRIM posisi artikel tetap pada posisinya saat memasukkan Chapta (tidak kembali ke header artikel) tapi tetap pada posisi footer artikel.

### Apa yang terjadi?
Mempermudah dan mempersingkat koreksi Komentar tersebut TERKIRIM atau GAGAL

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    |18.12-pasca
| Versi PHP        | 7.2.12
| System operasi   | Windows 10

**Comment by MUHAMMADRANGSEL** [comment]
betul sekali KODE CHAPTA kecil sekali

**Comment by abahaka** [comment]
Jika ingin tampilan CAPTCHA lebih besar dari default-nya,
edit file pada folder ~/assets/front/css/first.css

untuk tinggi image CAPTCHA, pada baris 1491 ganti
	`height: 40px;` menjadi (misalnya) `height: 80px;` 

untuk lebar image CAPTCHA, pada baris 1497 ganti
	`width: 100px;` menjadi (misalnya) `width: 200px;`

maka tampilan CAPTCHA akan menjadi lebih besar, sehingga lebih mudah untuk diidentifikasi

Semoga bermanfaat.

**Comment by abahaka** [comment]
sudah di resize menjadi 2 kali lebih besar dari ukuran semula.

https://github.com/OpenSID/OpenSID/commit/9dffec33c2c2a0ba2a49161ba7735634eb934e2f

**Comment by afa28** [comment]
Apakah ini masih bermasalah???

**Comment by MUHAMMADRANGSEL** [comment]
Chapca masih kecil dan agak ruwet, perlu penyederhanaan

Pada tanggal Sen, 24 Agt 2020 13.45, Andi Fahruddin Akas <
notifications@github.com> menulis:

**Comment by afa28** [comment]
https://github.com/OpenSID/OpenSID/issues/4334
