### ISSUE TITLE
Perbaikan Script Tombol Share Artikel (Fb, Tweet, +Google, Whatsapp)

### ISSUE THREAD

**Issue by PWidodo** [OpenSID/OpenSID#1829]
![gambar script coding share artikel](https://user-images.githubusercontent.com/45189822/50374461-4c948500-0621-11e9-963b-0f4db87cb63f.jpg)

### Bagaimana alurnya sampai muncul masalah?
Pada OpenSID versi 18.12 baik yang murni maupun pasca ternyata tombol share Tweet tidak berfungsi sebagaimana mestinya. Tombol lain yang berfungsi seperti Fb, G+, dan Whastaap itupun manakala di klik untuk share artikel terkait, ternyata tidak membuka tab laman baru pada Browser, sehingga otomatis tampilan Website hilang tergantikan link Share.

### Seperti apa yang diharapkan?
Seperti halnya website atau blog lain pada umumnya, manakala tombol share di klik maka otomatis akan membuka tab baru pada browser, sehingga website aktif tidak hilang tergantikan link share tersebut.

### Apa yang terjadi?
Setelah saya pelajari scriptnya yang terletak pada direktori htdocs/themes/default atau hadakewa/partials/artikel.php  ternyata masih kurang coding perintah share di tab baru (halaman kosong) pada browser yaitu tidak adanya coding perintah  target="_blank" 

### Informasi tambahan 
Saya lampirkan juga script  artikel.php  yang sudah saya edit untuk dirapikan dan dipasang pada direktori sebagaimana tersebut diatas pada OpenSID versi selanjutnya. Tombol Share sudah saya test, semua berfungsi normal dan sesuai yang diharapkan, termasuk tombol share Tweet.

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 18.12-pasca
| Versi PHP        | 7.2.12
| System operasi   | Windows 10

**Comment by PWidodo** [comment]
Berikut Perbaikan Script coding atikel.php pada bagian Tombol Share : 

<?php endif; ?>
		<div class="form-group" style="clear:both;">
			<ul id="pageshare" title="Bagikan ke teman anda" class="pagination">
				<li class="sbutton" id="fb"><a name="fb_share" href="http://www.facebook.com/sharer.php?u=<?php echo site_url().'first/artikel/'.$single_artikel['id']?>"target="_blank"><i class="fa fa-facebook-square"></i>&nbsp;Share</a></li>
				<li class="sbutton" id="rt"><a href="http://twitter.com/share?url=<?php echo site_url().'first/artikel/'.$single_artikel['id'].'&hl=id'?>"target="_blank" class="twitter-share-button"><i class="fa fa-twitter"></i>&nbsp;Tweet</a></li>
				<li class="sbutton" id="gpshare"><a href="https://plus.google.com/share?url=<?php echo site_url().'first/artikel/'.$single_artikel['id'].'&hl=id'?>"target="_blank"><i class="fa fa-google-plus" style="color:red"></i>&nbsp;Bagikan</a></li>
				<li class="sbutton" id="wa_share"><a href="whatsapp://send?text=<?php echo site_url().'first/artikel/'.$single_artikel['id']?>"target="_blank"><i class="fa fa-whatsapp" style="color:green"></i>&nbsp;WhatsApp</a></li>
			</ul>
			
		</div>

**Comment by agungsugiarto** [comment]
Lakukan PR Pull Request om, untuk panduan melakukan ada disini: https://github.com/OpenSID/OpenSID/wiki/Panduan-mengirimkan-perubahan-repo-OpenSID

**Comment by PWidodo** [comment]
Sepertinya dari Perbaikan untuk Issue#1829 masih kurang broo, coba test tombol Share Tweet , artikel terkait langsung masuk share di tab baru tidak. karena saya coba yang keluar hanya link sahare http://twitter.com/share  pada tab Baru, link artikel terkait tidak ikut masuk, tapi kalau codingnya saya lengkapi seperti ini : <li class="sbutton" id="rt"><a href="http://twitter.com/share?url=<?php echo site_url().'first/artikel/'.$single_artikel['id'].'&hl=id'?>"target="_blank" class="twitter-share-button"><i class="fa fa-twitter"></i>&nbsp;Tweet</a></li>
Maka artikel terkait lanmgsung masuk share di tab baru beserta gambar utama artikelnya.

**Comment by PWidodo** [comment]
Bisa cek hasil perubahannya di http://sered-banjarnegara.desa.id

**Comment by balongbesuk** [comment]
kenapa saya menggunakan kode diatas syntac error? akhirnya ubek ubek google tes sana sini dan berhasil menggunakan kode ini

`<li id='rt'><a href='http://twitter.com/share?url=".site_url()."first/artikel/".$single_artikel["id"]."' class='twitter-share-button'><i class='fa fa-twitter text-info'></i><span class='hidden-xs'> Tweet</span></a></li>`

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR #1831
