### ISSUE TITLE
[Bug] Laporan Kelompok Rentan berdasarkan dusun tidak berfungsi

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#1836]
### Bagaimana alurnya sampai muncul masalah?
Ketika ingin melihat Laporan Kelompok Rentan Berdasrkan dusun tidak berfungsi
![image](https://user-images.githubusercontent.com/25834335/50402397-55c45400-07d1-11e9-942a-c8b92c29a99e.png)

### Seperti apa yang diharapkan?
data pilah berdasarkan Dusun di Laporan Kelompok Rentan berfungsi sebagaimana mestinya

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by dikisiswanto** [comment]
Issue ini sudah diperbaiki pada PR #1838 . Berikut tangkapan layar dari hasil perbaikan yang dibuat.

![image](https://user-images.githubusercontent.com/22239074/50417539-037f4380-0862-11e9-9e24-143a69067069.png)

_Sebelum memilah data_

![image](https://user-images.githubusercontent.com/22239074/50417556-21e53f00-0862-11e9-9de7-9ad8dd2db46c.png)

_Setelah data dipilah berdasarkan dusun tertentu_

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR #1838
