### ISSUE TITLE
mohon pencerahan buat versi 18.12

### ISSUE THREAD

**Issue by dbudihartono** [OpenSID/OpenSID#1837]
### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by dbudihartono** [comment]
![opera snapshot_2018-12-25_000137_127 0 0 1](https://user-images.githubusercontent.com/43698618/50404252-53192d00-07d8-11e9-8e78-5f3f96f0deaf.png)

**Comment by eddieridwan** [comment]
@dbudihartono harap masalah install dan penggunaan OpenSID ditanyakan dulu di https://www.facebook.com/groups/OpenSID/.

Issue dibatasi pada hal2 yg terbukti bug/error yg perlu diperbaiki.

Terima kasih.
