### ISSUE TITLE
Penambahan Tombol UP DOWN di Daftar Gambar Album

### ISSUE THREAD

**Issue by Gunturwijay** [OpenSID/OpenSID#1839]
### Admin Web > Galeri>Pilih Daftar Album
![image](https://user-images.githubusercontent.com/40741591/50471761-ae216e80-09e8-11e9-87ea-6eb55fc72a0a.png)
Daftar Gambar Album
![image](https://user-images.githubusercontent.com/40741591/50471793-cf825a80-09e8-11e9-8e77-23c047eac168.png)

### diharapkan jika ada tombol Up Down dapat mengatur gambar sesuai gambar mana yang ingin di tampilkan urutannya di dalam web?
![image](https://user-images.githubusercontent.com/40741591/50471883-20924e80-09e9-11e9-9e97-8e011b0fb8f7.png)
![image](https://user-images.githubusercontent.com/40741591/50471905-33a51e80-09e9-11e9-9064-8c000adf9edd.png)

### 

### Informasi tambahan 

Contoh tombol NAIK | TURUN ada di beberapa halaman, termasuk di menu _Info Desa > Pemerintahan Desa_.
![tombol-urut](https://user-images.githubusercontent.com/249563/65925600-e735b600-e434-11e9-8ccb-218a75904a4b.jpg)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19.10
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dicommit ke `master`
