### ISSUE TITLE
[Bug] Pilihan sakit menahun tidak berfungsi di form tambah keluarga baru

### ISSUE THREAD

**Issue by afri18** [OpenSID/OpenSID#1840]
### Bagaimana alurnya sampai muncul masalah?
Tambah keluarga baru (entry)

### Seperti apa yang diharapkan?
Sakit menahun bisa drop down

### Apa yang terjadi?
Sakit menahun d biodata kepala keluarga baru tidakberfungsi

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | pra rilis
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
@afri18 : issue ini harap dilengkapi...

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
