### ISSUE TITLE
Surat Keterangan Untuk Nikah (N-1 s/d N-7) perlu disesuaikan dengan Keputusan Dirjen Bimas Islam Nomor 713 Tahun 2018

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#1841]
### Bagaimana alurnya sampai muncul masalah?
Layanan Surat ==> Cetak Surat Surat Keterangan Untuk Nikah (N-1 s/d N-7). 
Sesuai dengan Keputusan Direktur Jendral Bimbingan Masyarakat Islam Nomor 713 Tahun 2018 Tentang Penetapan Formulir dan Laporan Pencatatan Perkawinan atau Rujuk.
Setelah saya teliti ternyata perbedaan banyak sekali. Adapun Perbedaannya sebagai berikut : 
1. SURAT KETERANGAN UNTUK NIKAH (N-1) berubah istilah menjadi SURAT PENGANTAR PERKAWINAN (N-1)
2. SURAT KETERANGAN UNTUK NIKAH (N-1)  dan SURAT KETERANGAN ASAL USUL (N-2) di gabung menjadi SURAT PENGANTAR PERKAWINAN (N-1)
3. SURAT KETERANGAN ASAL USUL (N-2) tidak ada lagi
4. SURAT PERSETUJUAN MEMPELAI (N-3) tetap namun ada perubahan redaksi
5. SURAT KETERANGAN TENTANG ORANG TUA (N-4) tidak ada lagi
6. SURAT IZIN ORANG TUA (N-5) berubah menjadi SURAT IZIN ORANG TUA (N-4)
7. Surat Pemberitahuan Kehendak Nikah (N-7) berubah menjadi Surat Permohonan Kehendak Nikah (N-2)
 8. SURAT KETERANGAN KEMATIAN SUAMI/ ISTRI (N-6) tetap hanya saja ada perubahan redaksi
9. Model N-5 tidak ada lagi karena N-5 sesuai dengan aturan baru adalah pemebritahuan kekurangan syarat/penolakan perkawinan atau rujuk yang dibuat oleh KUA
Screnshot format terbaru sebagai berikut : 
1. format N-1
![image](https://user-images.githubusercontent.com/25834335/50538483-7a427680-0bab-11e9-8ed5-e3bb6eaa34c5.png)
![image](https://user-images.githubusercontent.com/25834335/50538492-96461800-0bab-11e9-88ec-e6a1f5007c3b.png)

2. format N-2
![image](https://user-images.githubusercontent.com/25834335/50538508-ca213d80-0bab-11e9-9340-9308a93a6b1c.png)

3. format N-3
![image](https://user-images.githubusercontent.com/25834335/50538515-eb822980-0bab-11e9-93ea-bcdeacfcba14.png)

4. format N-4
![image](https://user-images.githubusercontent.com/25834335/50538529-0bb1e880-0bac-11e9-8fd0-966096f161eb.png)
![image](https://user-images.githubusercontent.com/25834335/50538533-12406000-0bac-11e9-936d-e7c0c0fdd86f.png)

5. format N-5
![image](https://user-images.githubusercontent.com/25834335/50538549-4287fe80-0bac-11e9-8c58-eef6b7ca9cd1.png)

6. format N-6
![image](https://user-images.githubusercontent.com/25834335/50538566-76632400-0bac-11e9-9f5b-0161511ddcd3.png)

7. format N-7 dibuat KUA atau penghulu
![image](https://user-images.githubusercontent.com/25834335/50538583-92ff5c00-0bac-11e9-948d-bad73eb94a99.png)
![image](https://user-images.githubusercontent.com/25834335/50538600-ba562900-0bac-11e9-9422-7579450af0fd.png)

adapun formatnya terlampir
[Perdirjen 713 tahun 2018 tentang formulir dan laporan.pdf](https://github.com/OpenSID/OpenSID/files/2716383/Perdirjen.713.tahun.2018.tentang.formulir.dan.laporan.pdf)

### Seperti apa yang diharapkan?
Perlu disesuaikan formatnya sesuai dengan Keputusan Direktur Jendral Bimbingan Masyarakat Islam Nomor 713 Tahun 2018 Tentang Penetapan Formulir dan Laporan Pencatatan Perkawinan atau Rujuk.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by PWidodo** [comment]
Mantap.

**Comment by boedyirh** [comment]
Informasi yg sangat berguna

**Comment by metalab25** [comment]
saya sudah coba buatkan di jawaban dari issuenya om @afri18 silakan diperiksa mik, apakah sudah benar ?

https://github.com/OpenSID/OpenSID/issues/1915?fbclid=IwAR3Akh8Rs6_iwnTqUyznk5umIk4a6hrIgKBimwT36UYj2XAeCm10MGmaStQ#issuecomment-466674863

**Comment by afri18** [comment]
Dicoba dulu @metalab25

**Comment by MUHAMMADRANGSEL** [comment]
siap tuk dicoba

**Comment by MUHAMMADRANGSEL** [comment]
menurut saya cukup jadi satu bung happy, N1, N2, N4 untuk laki2 dan hasil exportnya satu tidak dipisah antara laki dengan perempuan

**Comment by MUHAMMADRANGSEL** [comment]
1.  SURAT PENGANTAR NUMPANG NIKAH dibuatkan menyendiri
2. SURAT KETERANGAN KEMATIAN SUAMI / ISTERI (N6) dibuat menyendiri
3. SURAT PERSETUJUAN MEMPELAI (N3)

**Comment by MUHAMMADRANGSEL** [comment]
karena menurut pengalaman yang biasa buat surat pengantar Numpang Nikah khusus untuk pengantin Laki-Laki

**Comment by MUHAMMADRANGSEL** [comment]
sehingga yang muncul di arsip layanan Nama penduduk yang membuat Surat ada yang laki ada yang perempuan.
untuk yang sekarang yang masuk diarsip layanan hanya laki-laki saja

**Comment by afri18** [comment]
Kalau sendiri-sendiri sama aja dengan manual, menurut saya disatukan nanti saat print tinggal pilih.
Lagi pula tidak menutup kemungkinan perempuan pun bisa numpang nikah
Bahkan ke2 nya bisa aja numpang nikah diluar wilayah nya karena suatu hal, misal karena yg perempuan wali nya ada dilain kabupaten dan tidak mampu atau kehendak walinya maka keduanya numpang nikah , saya pernah membuat nya maka timbul ide sekali input untuk 13 sampai 16 surat yg dibutuhkan

**Comment by metalab25** [comment]
Saua buat berdasarkan format dari om @afri18. Memang setau saya sejarah pernikahan kan pada dasarnya kan diselenggarakan di lokasi mempelai wanita. karena adat dan agama menghendaki seperti itu mas

**Comment by metalab25** [comment]
Coba disiskusikan dulu maunya seperti apa, beberapa sumber saya mengatakan memang bahwa N1 itu isinya data dari mempelai wanita

**Comment by afri18** [comment]
Kenapa N1 pertama saya tujukan untuk laki-laki ?
Karena yg laki2 umumnya numpang nikah kecuali dengan wanita sekecamatan/sewilayah KUA, jadi saat diprint cukup lihat print preview laki aja
Kalau k2pengantin sewilayah apalagi desa, nggak usah bolak balik input data lagi dan nomor surat juga tetap karena peristiwa nya sama

**Comment by metalab25** [comment]
Ayo ditetapkan dulu

**Comment by afri18** [comment]
Yg penting PHP nya aja om, untuk rtf/doc disesuaikan kebutuhan masing 2

**Comment by metalab25** [comment]
mohon dipastikan dulu @MUHAMMADRANGSEL @afri18  biar cepat saya kirim PR

**Comment by ai-skematik** [comment]
Kalau di daerah saya, surat untuk nikah N-1 s/d N4 di buat sesuai alamat pengantin,, jadi ketika pengantin pria menikah di desa lain, dia harus sudah membuat surat untuk nikah dr daerah asal,,

**Comment by afri18** [comment]
@happyagung25 yg penting anggap aja kedua mapelai satu desa, yg lain improve ,
Memang betul @ai-skematik alamat pengantin sesuai alamat KTP, tidak sama berarti numpang nikah
Kalau saya dah pernah buat untuk keduanya numpang nikah di daerah walinya, dan ada juga keduanya numpang di desa saya karena ngikutin  walinya

**Comment by happyagung25** [comment]
Ok om @afri18, kira-kira apa yang kurang lagi. Bagaimana dengan data walinya

**Comment by ai-skematik** [comment]
Kalau numpang nikah itu, suratnya dr KUA. Itu untuk mempelai yang nikah di
luar kecamatan. Nama suratnya rekomendasi Nikah..

Pada tanggal Sab, 2 Mar 2019 11:48, Happy <notifications@github.com>
menulis:

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR #1957
