### ISSUE TITLE
Nik dan nama ortu

### ISSUE THREAD

**Issue by afri18** [OpenSID/OpenSID#1843]
### Bagaimana alurnya sampai muncul masalah?
Salah entry nik atau nama orang tus

### Seperti apa yang diharapkan?
Saat entry nik ayah muncul nama ayah atau sebaliknya, saat entry nama ayah muncul nik ayah
Begitu juga dengan nik dan nama ibu

### Apa yang terjadi?
Salah nama atau nik ayah atau ibu

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by MUHAMMADRANGSEL** [comment]
Memang seharusnya untuk NIK dan Nama Orang Tua di Otomatiskan tapi bisa diubah untuk menghindari kesalahan penulisan NIK dan Nama Orang Tua

**Comment by PWidodo** [comment]
Setuju om Syafri dan MuhammadRangsel, bahwasannya kedepan untuk nama orang tua diinputkan otomatis dari database. Dengan 2 pilihan juga (1). Warga Desa, atau (2) Warga Luar Desa. Khusus untu pilihan (2) Banyak penduduk pendatang yang menikah dengan penduduk asli desa, otomatis nama/nik di database tidak tercantum, makanya perlu ada pilihan (2).

**Comment by MUHAMMADRANGSEL** [comment]
Belum

Pada tanggal Kam, 3 Jan 2019 15.25 anamrifai <notifications@github.com
menulis:

**Comment by afri18** [comment]
Yg penting bila orang tua ada di database bisa langsung ke deteksi 
Kalau orang tua tidak ada dalam database entry manual baik nik ataupun namanya

**Comment by dikisiswanto** [comment]
Baik, issue ini sudah saya coba kerjakan pada PR #1852 , tinggal menunggu peninjauan kode untuk bisa diterapkan pada versi pra-rilis

**Comment by eddieridwan** [comment]
Maaf teman2, baru sempat menanggapi.

Ada beberapa hal untuk diperhatikan.

1. Kalau orang tua ada di KK seharusnya bisa otomatis diambil dari status hubungan dalam keluarga.
2. Kolom nama/nik ayah/ibu sebaiknya dianggap sebagai ibu/ayah kandung, sehingga bisa digunakan untuk mengisi otomatis pada surat nikah dll.
3. Kalau ayah/ibu kandung berbeda dengan yang di KK, maka kolom ayah/ibu perlu diisi secara manual dengan nama/nik ayah/ibu kandung. 
4. Kalau ayah/ibu kandung diisi manual dan ortu yang bersangkutan ada di database penduduk, maka perlu bisa dipilih secara otomatis.
5. Tapi kalau ayah/ibu kandung dari luar desa atau sudah lama meninggal dan tidak terekam di database, maka kolom ayah/ibu juga perlu diisi secara manual.

**Comment by eddieridwan** [comment]
@dikisiswanto , solusinya bisa ambil contoh seperti di form surat, seperti gambar berikut. Daftar pilihan ibu kandung dibatasi penduduk wanita yang sudah pernah kawin. Daftar pilihan ayah kandung dibatasi penduduk laki-laki yang sudah pernah kawin. 

![luar-desa](https://user-images.githubusercontent.com/249563/50730754-d2c7d400-11a8-11e9-80bb-aabf405fdc88.jpg)
![warga-desa](https://user-images.githubusercontent.com/249563/50730755-d3606a80-11a8-11e9-8101-9d2eb8f047fe.jpg)

**Comment by dikisiswanto** [comment]
Untuk poin nomor 1, sumber datanya dari kotak isian yang mana ya pak @eddieridwan selain dari kotak status hubungan?

**Comment by eddieridwan** [comment]
@dikisiswanto , pada form edit, kalau kolom NIK dan nama ortu sudah terisi:

1. jika NIK ditemukan di database, ortu adalah warga desa, dan di form edit tampilkan sebagai pilihan warga desa, dengan nama yg diambil dari database
2. kalau NIK tidak ditemukan di database atau berisi angka nol (0), anggap ortu sebagai orang luar desa (atau tidak terrekam di database) dan di form edit tampilkan demikian, dengan data sebagaimana sudah terisi
