### ISSUE TITLE
Perlu ada Penambahan Fitur Permohonan surat secara online di aplikasi OpenSID

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#1844]
### Bagaimana alurnya sampai muncul masalah?
Aplikasi OpenSID merupakan aplikasi yang manfaatnya luar biasa sangat membantu desa terutama dalam penyediaan data dan pelayanan surat menyurat. Namun di Aplikasi OpenSID masyarakat belum bisa melakukan permohonan surat menyurat menggunakan Hp Android disebabkan karena belum ada fitur khusus yang disedikan didalam aplikasi OpenSID.
Dan Alhamdulillah tadi malam saya mendapatkan scrip aplikasi pelayanan secara online terutama untuk permohonan surat. scrip ini kalau saya tidak salah merupakan tugas akhir yang di buat untuk Nagari Padang Lua yang di upload supaya disa dimanfaatkan untuk desa.
Dan setelah saya coba teliti ini sangat cocok untuk digabung di OpenSID sebagai tambahan fitur untuk permohonan surat secara online.
melalui kesempatan ini saya akan upload scrip nya sejaligus databasenya
dan bagi yang ingin mencoba bisa instal dilaptop
username : admin
pass          : admin
Aplikasinya : 
[suratonline.zip](https://github.com/OpenSID/OpenSID/files/2717110/suratonline.zip)
### Seperti apa yang diharapkan?
harapannya bisa menjadi tambahan fitur didalam aplikasi OpenSID

![image](https://user-images.githubusercontent.com/25834335/50547090-f7cebb00-0c6d-11e9-9f4b-bcad1406e4ba.png)
![image](https://user-images.githubusercontent.com/25834335/50547091-fef5c900-0c6d-11e9-86d9-d6457f4a67ec.png)
![image](https://user-images.githubusercontent.com/25834335/50547094-061cd700-0c6e-11e9-84f0-267d504eddd2.png)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by MUHAMMADRANGSEL** [comment]
Aplikasi ini sangat sederhana bung eddie dan kawan2 para programer dan penggiat openSID, sehingga saya yakin sangat bisa digabungkan kedalam openSID

**Comment by afa28** [comment]
Sudah tersedia di layanan mandiri.
