### ISSUE TITLE
Raskin

### ISSUE THREAD

**Issue by afri18** [OpenSID/OpenSID#1845]
### Bagaimana alurnya sampai muncul masalah?
Raskin oleh pemerintah diganti menjadi Bantuan Pemerintah Non Tunai BPNT

### Seperti apa yang diharapkan?
agar tidak rancu/kagok sebaiknya istilah RASKIN ganti menjadi BPNT

### Apa yang terjadi?
Istilah jadi seragam dengan program pemerintah

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by pandigresik** [comment]
![image](https://user-images.githubusercontent.com/1853475/51063622-5f9de200-162e-11e9-9aeb-ae2da1a1ed44.png)
bisa langsung edit, silakan klik icon pensil saja untuk mengedit nama program

**Comment by eddieridwan** [comment]
Daftar program bantuan hanya merupakan contoh data awal. Bisa diubah sendiri menggunakan menu Bantuan.

Contoh data awal telah diubah di versi pra-rilis.
