### ISSUE TITLE
Hanya ada tombol Export doc ?

### ISSUE THREAD

**Issue by deanvhin2** [OpenSID/OpenSID#1846]
### Apa yang terjadi?
Kenapa 
![screenshot from 2019-01-01 17-17-09](https://user-images.githubusercontent.com/25787673/50572009-cd097180-0de9-11e9-9e3b-6ce543f69ef3.png)
Tidak ada tombol cetak ?

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19.01
| Versi PHP        | 7.0
| System operasi   | LINUX

**Comment by MUHAMMADRANGSEL** [comment]
Silahkan ubah settingannya di menu pengaturan

**Comment by deanvhin2** [comment]
ok makasih
