### ISSUE TITLE
di browser tampilan front end tetap berputar

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#1847]
### Bagaimana alurnya sampai muncul masalah?
yang saya maksud seperti gambar dibawah ini : 
![tetap berputar](https://user-images.githubusercontent.com/25834335/50574237-26d85e80-0e1f-11e9-8390-226585ff417b.png)

Kalau saya tes di demo tidak ada maslah

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by suphm** [comment]
coba om, buka  dev tool (F12)
lihat bagian tab network 
ada yang pending disana?
