### ISSUE TITLE
cari penduduk

### ISSUE THREAD

**Issue by afri18** [OpenSID/OpenSID#1849]
### Bagaimana alurnya sampai muncul masalah?
Cari nama yg berbeda satu huruf atau tanda spasi atau petik

### Seperti apa yang diharapkan?
Di menu penduduk saat cari bisa memasukan nama atau nik seperti di menu surat

### Apa yang terjadi?
Susah menemukan mana huruf yg benar, padahal ada nik, 

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by balongbesuk** [comment]
memperjelas issue

![pencarian3](https://user-images.githubusercontent.com/35319600/50684969-093b0d00-104a-11e9-9d79-21c0a06937c9.jpg)

**Comment by dikisiswanto** [comment]
Issue ini sudah dikerjakan pada PR #1853. Berikut tangkapan layar hasil pengerjaan pada PR tersebut.
![image](https://user-images.githubusercontent.com/22239074/50723011-df015200-1112-11e9-8610-37f1d8f6e72d.png)
_memilih keyword pencarian_
![image](https://user-images.githubusercontent.com/22239074/50723086-da896900-1113-11e9-8089-58977993d8b4.png)
_setelah proses pencarian dijalankan_

**Comment by hasap86** [comment]
Bung @dikisiswanto apakah masih bisa melakukan pencarian seperti sebelumnya, bebas mengetik nama? Karena disediakannya nama ortu di tabel untuk memudahkan pencarian nama yg sama

**Comment by hasap86** [comment]
Betul, maksud saya ketika mencari nama penduduk ketika menemukan nama yg sama sebagai pembedanya kita tanya ortunya siapa, di tabel disediakan nama ortu untuk membedakan nama penduduk hasil pencarian yg sama

**Comment by dikisiswanto** [comment]
Kolom yang ditampilkan tetap sama, bisa dilihat tangkapan layar yang saya bagikan pada komentar sebelumnya pak @hasap86

**Comment by afri18** [comment]
Pembedanya ya nik p @hasap86

**Comment by hasap86** [comment]
@dikisiswanto bukan kolom hasilnya, tapi saat pencariannya apa masih bisa seperti sebelumnya tanpa langsung memilih list autocomplete? Pake sembarang kata dan menampilkan beberapa hasil?

**Comment by hasap86** [comment]
@afri18 betul pembeda nik, tapi lebih cepat menyebutkan nama ortu ketimbang menyebutkan deretan angka nik

**Comment by afri18** [comment]
Anda keliru @hasap86 , sebelumnya cuma cari nama di menu penduduk
Saya sering cari data penduduk berdasarkan Poto copy ktp, karena suatu hal nama d KTP dengan database tidak sama, mau ketik nik nggak bisa karena fasilitas seperti itu hanya ada d menu surat di file input nama/nik.
Makanya saya buat issue ini.
Pembeda ortu ribet di programmer nya nanti, lagi pula mau yg di sandingkan nama ayah atau ibu atau keduanya, bagaimana data ortu yg masih kosong, perlu di ingat nggak semua kolom isian nama ayah ibu sudah terisi apa lagi data awal 2010.
Jadi menurut saya sudah pas nama disandingkan kode unik dari nik yg nggak mungkin sama, nama ortu masih ada yg sama, kalau data masih dibawah 3000an mungkin mudah, tapi kalau sudah diatas 5000 an , tingkat kesulitan makin tinggi

**Comment by afri18** [comment]
Setelah saya baca ulang ternyata maksud @hasap86 hasilnya
Hasilnya ya sama bung @hasap86 ada nama ayah dan ibu
Juga maksudnya ketik nama bisa menghasilkan beberapa unsur nama yg sama
Misal ketik Agus bisa muncul semua nama yg ada unsur agus di hasil pencarian

**Comment by eddieridwan** [comment]
Teman2, maaf terlambat menanggapi. 
@afri18 pencarian penduduk berdasarkan NIK sudah lama bisa. Tinggal masukkan saja NIK atau sebagian NIK ke kota pencarian. Memang saat ini tidak muncul di autocomplete, tapi tetap dicari.
Lihat gambar di bawah.

![cari-nik](https://user-images.githubusercontent.com/249563/50729922-73f95f00-1196-11e9-8b49-d5f03f6dc4cb.jpg)

**Comment by eddieridwan** [comment]
Saya sepakat dengan @hasap86. Dalam pencarian ini, sebaiknya boleh bebas, tidak harus memilih satu penduduk saja seperti halnya di form surat. Karena seperti dikatakan @hasap86 dan @afri18 pencarian penduduk sering bersifat meraba-raba dengan data yg belum tentu terisi dengan benar (salah tulis, ejaan berbeda, dsbnya). Jadi dalam situasi seperti ini, lebih leluasa lebih baik.

Mungkin teman2 lupa, juga ada fitur Pencarian Spesifik, yang bisa digabungkan dengan pencarian menggunak kotak cari. Sehingga misalnya di contoh di bawah, bisa dicari penduduk dengan:

1. nama atau NIK berisi 'ma'
2. berumur antara 5 s/d 15 tahun

![menu-pencarian-spesifik](https://user-images.githubusercontent.com/249563/50730018-e585dd00-1197-11e9-852f-752b364deefa.jpg)
![form-pencarian-spesifik](https://user-images.githubusercontent.com/249563/50730021-f5052600-1197-11e9-8452-13a448dda11b.jpg)
![hasil-cari-gabungan](https://user-images.githubusercontent.com/249563/50730022-f5052600-1197-11e9-805a-aba56107587d.jpg)

**Comment by eddieridwan** [comment]
Kalau pencarian menggunakan nama orang tua dianggap penting, bisa saja kolom itu ditambahkan di Pencarian Spesifik (bukan di kotak cari). Kalau memang perlu silakan buatkan issue baru.

**Comment by hasap86** [comment]
betul bung @eddieridwan rasanya sudah nyaman dengan fItur pencarian saat ini, bisa bebas melakukan pencarian bebas, mau NIK maupun Nama. sekedar saran kalopun mau fitur pencarian yang saat ini hanya ditambahkan informasi NIK sebelum List Nama _(yang saat ini hanya muncul info nama lengkap)_, **tetapi tidak wajib memilih salah satu di pencarian**.

**Comment by hasap86** [comment]
> Kalau pencarian menggunakan nama orang tua dianggap penting, bisa saja kolom itu ditambahkan di Pencarian Spesifik (bukan di kotak cari). Kalau memang perlu silakan buatkan issue baru.

nah bisa juga menambahkan  pencarian spesifik Dusun, RW & RT

**Comment by eddieridwan** [comment]
Bung @dikisiswanto, dengan alasan di atas, solusi anda di PR anda #1853 tidak bisa digabung. Solusi alternatif yg lebih sesuai dengan pencarian fleksibel adalah dengan juga menampilkan daftar NIK di autocomplete. Jadi pada waktu memasukkan angka di kotak cari, NIK yg berisi angka tersebut akan tampil.

Contoh solusi seperti ini ada di `donjo-app/models/Data_persil_model.php`.

**Comment by hasap86** [comment]
> Bung @dikisiswanto, dengan alasan di atas, solusi anda di PR anda #1853 tidak bisa digabung. Solusi alternatif yg lebih sesuai dengan pencarian fleksibel adalah dengan juga menampilkan daftar NIK di autocomplete. Jadi pada waktu memasukkan angka di kotak cari, NIK yg berisi angka tersebut akan tampil.
> 
> Contoh solusi seperti ini ada di `donjo-app/models/Data_persil_model.php`.

jika bisa juga mungkin dilengkapi ketika mencari Nama diinfokan NIKnya, jika mencari NIK diinfokan Namanya dgn format (<NIK> - <Nama Lengkap>)

**Comment by eddieridwan** [comment]
> jika bisa juga mungkin dilengkapi ketika mencari Nama diinfokan NIKnya, jika mencari NIK diinfokan Namanya dgn format **NIK** - **Nama Lengkap**.

@hasap86 gabungan seperti itu tidak bisa di tampilkan di autocomplete, karena autocomplete bebas sifatnya hanya potongan teks yang otomatis diisi.

**Comment by hasap86** [comment]
> > jika bisa juga mungkin dilengkapi ketika mencari Nama diinfokan NIKnya, jika mencari NIK diinfokan Namanya dgn format **NIK** - **Nama Lengkap**.
> 
> @hasap86 gabungan seperti itu tidak bisa di tampilkan di autocomplete, karena autocomplete bebas sifatnya hanya potongan teks yang otomatis diisi.

Siap...

**Comment by afri18** [comment]
Ternyata bung @eddie benar, nggak tau sejak versi berapa bisanya
Kalau begitu pertahankan saja, karena sudah bisa mencari nama atau nik
Issue ini di tutup
