### ISSUE TITLE
Perbaikan Menu Sekretariat>Surat Masuk>Disposisi

### ISSUE THREAD

**Issue by PWidodo** [OpenSID/OpenSID#1850]
### Bagaimana alurnya sampai muncul masalah?

1. Disaat kami entry data surat masuk dengan nomor Surat lebih dari 20 digit, yang tersimpan dalam Form surat Masuk hanya 20 digit yang menyebabkan arsip surat masuk pada kolom Nomor Surat tidak sesuai dengan sebenarnya. 

2. Pada lembar cetak Disposisi Surat seharusnya tercantum Nama jabatan dan Tanda Tangan Kades atau Sekretaris Desa pada bagian bawah sebelah kanan.

### Seperti apa yang diharapkan?
Khusus untuk point 1, sudah saya atasi dengan merubah struktur database pada phpMyAdmin pada tabel Surat Masuk>Nomor Surat, gambar saya lampirkan dibawah.
Untuk Point 2 saya mohon untuk diperbaiki oleh Pihak Master Opensid.

### Apa yang terjadi?
Untuk penyesuaian dengan kondisi surat di desa.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19.01
![surat masuk 1](https://user-images.githubusercontent.com/45189822/50677763-45f90b00-102e-11e9-9915-1a43488154bc.jpg)
![surat masuk 2](https://user-images.githubusercontent.com/45189822/50677779-57421780-102e-11e9-9fc5-38b8d2fa9eef.jpg)

![surat masuk 3](https://user-images.githubusercontent.com/45189822/50677794-69bc5100-102e-11e9-8d3b-ad9c8c8fcb8a.jpg)

| Versi PHP        | 
| System operasi   |

**Comment by MUHAMMADRANGSEL** [comment]
Bila perlu tambah jadi 30 supaya aman

**Comment by eddieridwan** [comment]
#1850: Panjang maksimum nomor surat di Surat Keluar dan Surat Masuk telah diubah menjadi 35 karakter. Sudah di versi pra-rilis.

Penambahan penandatangan menunggu perubahan PR #1871 dari @agungsugiarto .

**Comment by agungsugiarto** [comment]
Pak @PWidodo Apakah hanya diperlukan penandatangan saja? Untuk tandatangan mengetahui apakah diperlukan juga  ?

**Comment by MUHAMMADRANGSEL** [comment]
Ya diperlukan juga mas agung sugiarto

**Comment by agungsugiarto** [comment]
> Ya diperlukan juga mas agung sugiarto

Apakah seperti ini yang diharapkan dibuatkan dialog untuk pilihan Laporan Ditandatangani dan Laporan Diketahui ?
![1](https://user-images.githubusercontent.com/10989147/51426385-92db0500-1c1c-11e9-8e92-873cf0e61069.png)

**Comment by PWidodo** [comment]
Besok saya lihat permendagrinya, untuk form disposisi suratnya agar sesuai, dan untuk sub menu sekretariat juga masih perlu ada penambahan menu. Sedang saya susun tapi belum selesai, sedg sibuk pengerjaan SPJ belum kelar.

**Comment by eddieridwan** [comment]
Penandatangan/mengetahui sudah dicommit ke master melalui PR #1871.

@PWidodo Permintaan tambahan silakan dibuat issue terpisah.
