### ISSUE TITLE
Tambahkan alamat RT RW pada pencarian penduduk di surat menyurat seperti pada Opensid lama

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#1851]
### Bagaimana alurnya sampai muncul masalah?
cetak surat > pencarian data penduduk > lihat tampilan

### Seperti apa yang diharapkan?
ada alamat Dusun RT RW seperti pada opensid lama

### Apa yang terjadi?
saat ini pencarian data penduduk yang akan dibuatkan surat hanya menampilkan nik dan nama saja yang lumayan menyusahkan ketika nama penduduk sama

### Informasi tambahan 

![pencarian2](https://user-images.githubusercontent.com/35319600/50684531-79489380-1048-11e9-80f8-53a26d812d4d.jpg)
tampilan pencarian penduduk opensid baru

![pencarian](https://user-images.githubusercontent.com/35319600/50684532-79e12a00-1048-11e9-9e57-9c089224d0e3.jpg)
tampilan pencarian penduduk opensid lama

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by afri18** [comment]
Kalau ketik nama cocokan nik nya, atau biar akurat ketik nik, lebih pas

**Comment by balongbesuk** [comment]
terkadang penduduk yang minta surat tidak membawa KTP / KTP hilang, yang mana akhirnya kita harus memilah di data penduduk filtering dusun rw dan rt / cek data KK menyesuaikan nama istri yang mana itu juga memakan waktu,

**Comment by hasap86** [comment]
Saran dari staf desa kami, untuk pencarian disandingkan menggunakan tambahan nama orang tua, misalnya NIK: 1234567890 - ALPANI bin <Nama Bapak>, ditambahkan alamat seperti yg lama dibaris keduanya lebih baik lagi...

**Comment by afri18** [comment]
Pakai pencarian spesifik dah bisa ...

**Comment by eddieridwan** [comment]
Sudah dicommit melalui PR #1863
