### ISSUE TITLE
Status Kawin

### ISSUE THREAD

**Issue by afri18** [OpenSID/OpenSID#1854]
### Bagaimana alurnya sampai muncul masalah?
kadang saat milih status belum kawin tanggal terinput tgl sekarang, begitu juga tanggal perceraian , memakai tombol tab saat pindah isian

### Seperti apa yang diharapkan?
1. Kalau pilih Status Kawinnya Belum Kawin otomatis isian No Akta Nikah dan Tgl Perkawinan Tidak serta No Akta Nika dan Tgl Cerai tidak aktif.
2. Kalau Pilih Kawin yg aktif hanya isian No Akta Nikah dan Tgl Perkawinan sedangkan No Akta Cerai dan Tgl Cerai Pasif
3. Kalau pilih Cerai Hidup yg aktif hanya  No Akta cerai dan Tgl Cerai yg lain Pasif
4. Kalau Pilih Cerai Mati berarti kolom Isian yg lain tidak aktif sama dengan pilih Belum Kawin hanya saja bila data sudah terisi tidak menjadi hilang

### Apa yang terjadi?
Selalu terisi tgl perkawinan dan tgl perceraian dengan tgl sekarang saat menggunakan tombol TAB untuk pindah isian

### Informasi tambahan 
![image](https://user-images.githubusercontent.com/6611881/50731509-26322600-1199-11e9-9ee7-3128d015efff.png)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by MUHAMMADRANGSEL** [comment]
Memang ini yang saya harapkan

**Comment by dikisiswanto** [comment]
Apakah kotak isian akseptor KB juga perlu dibuat tampil/tidak tampil sesuai status perkawinan ini pak?

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR #1855
