### ISSUE TITLE
sesuaikan cetak Laporan Kelompok Rentan

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#1856]
### Bagaimana alurnya sampai muncul masalah?
Menu Statistik ==> Laporan Kelompok Rentan ==> untuk Cetak dan untuk perlu disesuiakan dengan Tampilan view
![kelompok rentan](https://user-images.githubusercontent.com/25834335/50736258-1f85cc00-11f6-11e9-95fd-9bce03bcedf6.png)
![kelompok rentan1](https://user-images.githubusercontent.com/25834335/50736259-201e6280-11f6-11e9-8317-bad6cfc80c68.png)

### Seperti apa yang diharapkan?
Tampilan antara view dengan cetak dan unduk sama

## Apa yang terjadi?
Tampilan tidak sama dengan viewnya
### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by dikisiswanto** [comment]
Apakah perubahan ini cukup penting untuk diterapkan?

**Comment by MUHAMMADRANGSEL** [comment]
Penting mas supaya seragam

Pada tanggal Sen, 7 Jan 2019 17.16 Diki Siswanto <notifications@github.com
menulis:

**Comment by dikisiswanto** [comment]
Apakah perlu penyesuaian juga pada format excel nya juga pak @MUHAMMADRANGSEL ?

**Comment by MUHAMMADRANGSEL** [comment]
Ya

Pada tanggal Min, 3 Mar 2019 13.00, Diki Siswanto <notifications@github.com>
menulis:

**Comment by dikisiswanto** [comment]
Apakah seperti ini?

![image](https://user-images.githubusercontent.com/22239074/53784931-bef2e100-3f51-11e9-9383-a2db7067735b.png)

**Comment by MUHAMMADRANGSEL** [comment]
Ya

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
