### ISSUE TITLE
Tulis ulang pencatatan dan penghitungan perubahan status penduduk, termasuk lahir, datang, mati, pindah, hilang

### ISSUE THREAD

**Issue by afri18** [OpenSID/OpenSID#1859]
### Bagaimana alurnya sampai muncul masalah?
Susuah membedakan mana form tambah penduduk karna Kelahiran atau Penduduk Datang/Tambah Baru (bukan Kelahiran)

### Seperti apa yang diharapkan?
1. Saat Menambahkan Penduduk Karna Lahir Hanya bisa dari Menu Kartu Keluarga dan dicatat sebagai data kelahiran pada bulan pencatatan/isi/entry walaupun sudah lewat bulannya dan formnya di data kelahiran komplit
![tmbah_penduduk_lahir](https://user-images.githubusercontent.com/6611881/50835033-2b08fc80-1388-11e9-916e-353a29e0184d.png)

form isian di Kelahiran Komplit
![data kelahiran full](https://user-images.githubusercontent.com/6611881/50835220-b8e4e780-1388-11e9-959b-5338e75b5e6d.png)

Tidak ada kolom isian alamat asal maupun No KK terdahulu

2. Saat Menambahkan Penduduk dari menu Penduduk atau Keluarga
![tmbah_penduduk](https://user-images.githubusercontent.com/6611881/50835287-e0d44b00-1388-11e9-8afc-de129d26f93e.png)

Form Isisan Data Kelahiran Hanya No Akta Lahir, Tempat Lahir dan Tanggal Lahir
![data kelahiran bkn lahir](https://user-images.githubusercontent.com/6611881/50835326-006b7380-1389-11e9-95a5-8d4db06f2124.png)
Ada Isisn Alamat Asal dan No KK terdahulu
### Apa yang terjadi?
1. Sulit Membedakan mana form tambah Penduduk Karna Lahir atau dari Penambahan Karna Kedatangan dan Data Kelahiran kadang terisi Jam Lahir
2. Data Kelahiran didata/tercatat saat data diinput/entry/isi karna lahir walau tanggal lahir di bulan yg sudah lewat, saat ini malah tercatat sebagai penduduk datang padahal tidak ada penduduk yg datang akibatnya data penduduk jadi kacau antara lahir dan datang

### Informasi tambahan 
tidak tumpang tindih antara penduduk datang dan lahir (orang tua sudah warga desa)
bisa di gabung dengan Isian NIK dan Nama Orang tua secara otomatis bila karna Kelahiran

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
Apakah issue sudah solved?? Silahkan di close klw sdah.

**Comment by afri18** [comment]
sepertinya belum ada perbaikan @afa28

**Comment by balongbesuk** [comment]
apa cukup di judul tombolnya saja yang dirubah?, 

di menu  Salinan Kartu Keluarga + tambah Anggota / Kelahiran
di menu Daftar Anggota Keluarga + tambah Anggota / Kedatangan

**Comment by mizwaruddin** [comment]
Bukan hanya di tombol. Tp di laporan bulanan hrs tercatat dg benar penambahan penduduk krn kelahiran atau krn kedatangan.

**Comment by eddieridwan** [comment]
Mungkin cara pencatatan dan penghitungan perubahan status penduduk perlu ditulis ulang, untuk disesuaikan dengan umpan balik dan kebutuhan pengguna -- dan sesuai dengan Permen yg mengatur.

**Comment by muhtar-coder** [comment]
setuju dengan issue ini,,merupakan hal yang mendasar dalam penggunaan opensid yang menunjukan tata kelola laporan penduduk sudah benar atau belum. sampai saat ini data laporan kami pun sulit di mengerti, karena semua tidak dapat membedakan mana penduduk tambahan karena lahir atau karena kedatangan,dan jumlah pun tidak sinkron antara bulan awal - datang-pergi-dan bulan akhir.

**Comment by eddieridwan** [comment]
@muhtar-coder , silakan jelaskan alur, ketentuan dan peraturan pencatatan dan penerbitan laporan kependudukan bulanan. Tanpa info itu, sulit bagi programmer menerapkan bagaimana menulis ulang.

**Comment by balongbesuk** [comment]
saya coba cari peraturannya belum ketemu (mayoritan yang saya temukan hanya peraturan untuk melaporkan administrasi penduduk setiap bulannya),

secara umum pencatatan kependudukan

pindah datang --> penduduk luar desa yang pindah datang ke desa tujuan (dicatat pada tanggal laporan ybs)
pindah keluar --> penduduk desa yang melakukan pindah ke luar desa (dicatat pada tanggal laporan ybs)
kematian --> penduduk yang mengalami peristiwa meninggal dunia (dicatat pada tanggal laporan ybs)
kelahiran --> penduduk yang mengalami peristiwa melahirkan (dicatat pada tanggal laporan ybs)

**Comment by eddieridwan** [comment]
Sdh dicommit ke `rilis-dev` di rilis Premium.
