### ISSUE TITLE
Cetak & Unduh Inventaris Penandatangan tidak muncul

### ISSUE THREAD

**Issue by hasap86** [OpenSID/OpenSID#1860]
### Bagaimana alurnya sampai muncul masalah?
Saat mencetak atau Unduh Inventaris (Sekretariat > Inventaris) Penandatangan tidak muncul

### Seperti apa yang diharapkan?
seharusnya muncul penandatangan di hasil cetak atau unduh

### Apa yang terjadi?
tidak sesuai

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19.01-pasca
| Versi PHP        | 5.6.39
| System operasi   |

**Comment by eddieridwan** [comment]
Penandatangan laporan inventaris muncul di v19.04-pasca.
