### ISSUE TITLE
Gambar tidak terupload

### ISSUE THREAD

**Issue by deanvhin2** [OpenSID/OpenSID#1864]
### Bagaimana alurnya sampai muncul masalah?
Di localhost aplikasi lancar jaya , pas di hosting tidak bisa upload gambar artikel maupun galeri .

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19.01
| Versi PHP        | 7.0
| System operasi   | linux

**Comment by pandigresik** [comment]
Mungkin masalah file permission aja

**Comment by deanvhin2** [comment]
Udh di ubah ke 777 ttep aja kang ? Knp ya?

**Comment by metalab25** [comment]
Coba dulu di beta.opensid.info atau di demo.opensid.info

**Comment by deanvhin2** [comment]
Bsa kang , klo itu .d Localhost juga lncr jaya kang . Apa di disk hosting nya gtu ? Pdhl msh ada 35%'an lg tersedia

**Comment by deanvhin2** [comment]
![screenshot from 2019-01-13 20-21-21](https://user-images.githubusercontent.com/25787673/51085907-18206e80-1772-11e9-88fc-c9db78a4e1e7.png)

ini setelah di upload gambar mini nya juga ga terupload kang .

**Comment by eddieridwan** [comment]
@deanvhin2 : 

1. Periksa semua subfolder desa lengkap. Lihat panduan https://github.com/OpenSID/OpenSID/wiki/Folder-Desa
2. Periksa permission untuk folder desa dan setiap subfoldernya adalah 755 atau minimal 751

Info ini sudah ditambahkan ke panduan di https://github.com/OpenSID/OpenSID/wiki/Tanya-Jawab-Install-dan-Update.

Karena ini merupakan pertanyaan install/update, bukan bug yang perlu diperbaiki, kami tutup issue ini. Pertanyaan susulan terkait masalah anda bisa ditanyakan di https://www.facebook.com/groups/OpenSID/ atau di grup WA.

Bagi teman2 yg bisa membantu menjelaskan lebih lanjut, silakan lengkapi keterangan di https://github.com/OpenSID/OpenSID/wiki/Tanya-Jawab-Install-dan-Update.

**Comment by Yasserarafat1507** [comment]
![Uploading Desain tanpa judul.jpg…]()
ini gan bang?
