### ISSUE TITLE
Untuk Penomoran surat menggunakan angka 3 digit

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#1865]
### Bagaimana alurnya sampai muncul masalah?
Layanan surat==> Cetak Surat untuk nomor surat perlu ada settingan atau sejenisnya supaya nomor yang muncul secara otomatis menggunkan 3 digit contohnya sekarang yang ada untuk nomor 10 muncul 10 seharusnya 010
![image](https://user-images.githubusercontent.com/25834335/51083383-63c41f80-1754-11e9-9f12-f9b3e25b8f83.png)

### Seperti apa yang diharapkan?
diharapkan untuk nomor menggunakan 3 digit angka contoh : 470/010/PEM/2019 

### Apa yang terjadi?
belum bisa menggunakan secara maksimal untuk penomoran otomatis

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dicommit ke master. 
Solusinya: Sediakan kode isian nomor_surat yang bisa ditentukan panjangnya, diisi karakter '0' di sebelah kiri kalau perlu. Contoh [nomor_surat,3] menghasilkan '012'.
