### ISSUE TITLE
[Bug] Laporan masuk tidak tersimpan

### ISSUE THREAD

**Issue by maswidtuban7** [OpenSID/OpenSID#1866]
Laporan masuk tidak tersimpan di feature layanan mandiri
![untitled](https://user-images.githubusercontent.com/46660445/51093321-ef7d9080-17d4-11e9-9d92-a338c816f209.png)

**Comment by MUHAMMADRANGSEL** [comment]
Betul saya juga mengalami seperti ini

**Comment by eddieridwan** [comment]
Sudah diperbaiki di versi pra-rilis beberapa hari yg lalu. Silakan coba di http://beta.opensid.info.

Sebelum melaporkan issue, harap cek dulu apakah sudah diperbaiki di pra-rilis.

**Comment by eddieridwan** [comment]
Sudah di pra-rilis
