### ISSUE TITLE
[Bug] Link Salah

### ISSUE THREAD

**Issue by boedyirh** [OpenSID/OpenSID#1872]
### Bagaimana alurnya sampai muncul masalah?
Link RT diclick Error

![image](https://user-images.githubusercontent.com/10396931/51179296-ab36e100-18f7-11e9-93dc-93d5ea84cd43.png)

![image](https://user-images.githubusercontent.com/10396931/51179214-77f45200-18f7-11e9-9ffa-042b48ad6a97.png)

### Seperti apa yang diharapkan?
Link masuk ke RT

### Apa yang terjadi?

Error 404
### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19.01
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.

**Comment by boedyirh** [comment]
Terima kasih Pak
