### ISSUE TITLE
Login dgn akun Operator, Klik Menu Analisis langsung keluar

### ISSUE THREAD

**Issue by boedyirh** [OpenSID/OpenSID#1875]
### Bagaimana alurnya sampai muncul masalah?
Login dengan akun yang memiliki hak akses Operator.
Klik menu Analisis...langsung keluar ke halaman login

![image](https://user-images.githubusercontent.com/10396931/51219625-3e0d6500-1964-11e9-965f-9a4b10cb0d5a.png)

### Seperti apa yang diharapkan?
Jika Operator tidak memiliki akses ke Menu Analisis, sebaiknya Menu itu tidak ditampilkan di laman Operator.
Atau jika Operator memiliki hak akses pada menu tersebut, berarti script untuk mengecek hak akses perlu diperbaiki

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19.01
| Versi PHP        | 
| System operasi   |

**Comment by balongbesuk** [comment]
issue ini bisa ditutup di prarilis sudah diperbaiki
