### ISSUE TITLE
Saat Import, Alamat tidak bisa masuk

### ISSUE THREAD

**Issue by boedyirh** [OpenSID/OpenSID#1876]
Coba import xls dengan (Import database) , Kolom alamat tidak ikut terimport
### Seperti apa yang diharapkan?
Semua data bisa masuk

### Apa yang terjadi?
Semua data bisa masuk kecuali alamat.

### Informasi tambahan 
Saya cek di database, field yg ada adalah alamat_sekarang.
sedangkan di array, tertulis hanya alamat. 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19.01
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
@boedyirh apakah sudah melihat panduan https://github.com/OpenSID/OpenSID/wiki/Error-Impor-Data-Kependudukan (lihat bagian **Dusun, RW, RT tidak tampil**). 

Biasakan membaca panduan dulu. Juga biasakan memeriksa dulu di situs demo rilis http://demo.opensid.info dan demo pra-rilis di http://beta.opensid.info untuk konfirmasi apakah masalah ada di anda atau di aplikasi.

Issue HANYA untuk masalah yg betul2 error/bug yg perlu diperbaiki. Kalau belum yakin, tanyakan dulu di https://www.facebook.com/groups/OpenSID/ -- karena mungkin masalah yg anda hadapi adalah karena kurang info saja.

**Comment by eddieridwan** [comment]
Memang saat ini panduan https://github.com/OpenSID/OpenSID/wiki/Pengisian-Data-Penduduk tidak jelas mengenai penanganan Alamat KK dan Alamat Penduduk. Dan perlu diperjelas. Lihat komentar saya pada solusi di fork anda.

**Comment by boedyirh** [comment]
Terima kasih Pak.  Noted
