### ISSUE TITLE
Eror saat penambahan penduduk Domisili di menu Penduduk

### ISSUE THREAD

**Issue by Galiarta** [OpenSID/OpenSID#1877]
### Bagaimana alurnya sampai muncul masalah?
Ketika Menambah penduduk domisili terjadi errror seperti gambar diatas. Dicoba di demo.opensid.info bisa, dicoba di beta.opensid.info error.

### Seperti apa yang diharapkan?
Tidak terjadi error, bisa menambahkan penduduk.

### Apa yang terjadi?
Terjadi error
![image](https://user-images.githubusercontent.com/33612251/51383045-54c5de80-1b53-11e9-85b6-bde27afdd188.png)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19.01 Pasca
| Versi PHP        |     7.0
| System operasi   | Windows 10

**Comment by MUHAMMADRANGSEL** [comment]
Coba cek databasenya

**Comment by eddieridwan** [comment]
Telah diperbaiki di master.
