### ISSUE TITLE
[bug] Modul Inventaris Tidak Sesuai dengan Permendagri No. 1 Tahun 2016 tentang Pengelolaan Aset Desa

### ISSUE THREAD

**Issue by siayi** [OpenSID/OpenSID#1878]
### Bagaimana alurnya sampai muncul masalah?
Saat ini **Modul Inventaris** masih berdasarkan pada Permendagri No. 4 tahun 2007 tentang Pedoman Pengelolaan Kekayaan Desa [(lihat rilis v18.07)](https://github.com/OpenSID/OpenSID/releases/tag/v18.07) dan untuk Kategori Inventaris / Kodefikasi masih merujuk pada Permendagri No. 17 Tahun 2007 tentang Pedoman Teknis Pengelolaan Barang Milik Daerah. Padahal saat ini telah ada **Permendagri No. 1 Tahun 2016 tentang Pengelolaan Aset Desa**.

### Seperti apa yang diharapkan?
Modul Inventaris disesuaikan agar sesuai dengan Permendagri No. 1 Tahun 2016 tentang Pengelolaan Aset Desa.

### Apa yang terjadi?
Modul Inventaris tidak sesuai dengan peraturan yang berlaku. Padahal fitur OpenSID diharapkan senantiasa sesuai dengan peraturan yang berlaku.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19.01
| Versi PHP        | 
| System operasi   |

**Comment by MUHAMMADRANGSEL** [comment]
Ini sdh ada aplikasi SIPaDES yang dikeluarkan oleh kementerian desa

**Comment by siayi** [comment]
> Ini sdh ada aplikasi SIPaDES yang dikeluarkan oleh kementerian desa

Berarti Modul Inventaris di OpenSID yang ada saat ini sdh tidak aktual dong. Lalu bagaimana dengan desa-desa yang tidak mengimplemetasikan SIPaDES ??

**Comment by afa28** [comment]
Apakah ini masih bermasalah???

**Comment by MUHAMMADRANGSEL** [comment]
Ini bisa diclosed karena nanti pas pembuatan buku Administrasi desa akan
tercover

Pada tanggal Sen, 24 Agt 2020 13.45, Andi Fahruddin Akas <
notifications@github.com> menulis:
