### ISSUE TITLE
Statistik Kependudukan bisa ditampilkan per wilayah

### ISSUE THREAD

**Issue by nockturno** [OpenSID/OpenSID#1879]
### Bagaimana alurnya sampai muncul masalah?
Kepala Wilayah atau Kepala Dusun sering diminta data terkait seperti data balita batita, pengguna akseptor KB, data pendidikan yang sedang ditempuh dll diwilayahnya masing-masing

### Seperti apa yang diharapkan?
Untuk memenuhi permintaan data tersebut diatas agar bisa ditampilkan statisik kependudukan per dusun/ wilayah. 

### Apa yang terjadi?
![image](https://user-images.githubusercontent.com/36945918/51448985-94abe200-1d5c-11e9-9f77-01218d1f7c44.png)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by andriawan** [comment]
saya coba bantu penanganan issue ini @eddieridwan. dari yang dapat saya analisa, perlu adanya mekanisme filter (berupa tampilan UI dropdown pada statistik kependudukan.

**Comment by eddieridwan** [comment]
Silakan.

**Comment by andriawan** [comment]
![image](https://user-images.githubusercontent.com/13099373/62816881-fe080c80-bb57-11e9-9bbf-1342c21d88f8.png)

apakah klasifikasi dusun/wilayah nantinya akan sepsifik ke rt rw yang terkait atau hanya sebatas klasifikasi dusun/wilayah saja @eddieridwan @nockturno

**Comment by andriawan** [comment]
![image](https://user-images.githubusercontent.com/13099373/62816902-6bb43880-bb58-11e9-95dc-57c708ebc7f8.png)
saya ingin memastikan juga apakah data kolom dari tweb_penduduk yaitu id_cluster mengacu ke tweb_wil_clusterdesa?

**Comment by eddieridwan** [comment]
Saya kira sampai dusun/rw/rt.
Ya, `id_cluster` mengacu ke `tweb_wil_clusterdesa`.

**Comment by af-lazuardi** [comment]
apakah issue ini masih progress pengerjaan Pak @andriawan ?

**Comment by andriawan** [comment]
Tentu @af-lazuardi silahkan jika ingin dilanjutkan... kebetulan masih ada deadline dari pekerjaan utama. terima kasih telah memberikan tanggapan dan bantuan.

**Comment by dikisiswanto** [comment]
Apakah issue ini hanya dikhususkan untuk statistik penduduk (tidak termasuk statistik keluarga dan statistik program bantuan) ?

**Comment by andriawan** [comment]
Sepertinya issue sedang dikerjakan mas @dikisiswanto.. maaf belum bisa PR dikarenakan masih memprioritaskan kepentingan kantor

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR #2361
