### ISSUE TITLE
Tampilkan laporan penduduk bulanan di halaman website

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#1881]
Laporan penduduk bulanan agar dapat tampil di halaman website seperti data statistik penduduk

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
Duplicate of #3855
