### ISSUE TITLE
Error 500 pada menu Daftar Rekam Surat di Layanan Mandiri via Hp

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#1884]
### Bagaimana alurnya sampai muncul masalah?
Login di Layanan Mandiri melalui laptop:
Saat pilih menu Daftar Rekam Cetak Surat normal.

### Seperti apa yang diharapkan?
Mengatasi permasalahan dimaksud di versi 19.01 maupun 19.01-Pasca

### Apa yang terjadi?
Berbeda jika buka Layanan Mandiri melalui Hp, muncul halaman error 500 pada menu Daftar Rekam Cetak Surat tersebut.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by ariandii** [comment]
perihal error 500 tersebut, saya akses secara online, script opensid berada di hosting.

**Comment by ariandii** [comment]
informasi:
Permasalahan error tersebut muncul kembali. 

singkat cerita, 
karena terjadi error di salah satu perangkat, kadang di laptop, kadang di hp. 

misal error muncul di laptop, maka saya buka di hp lancar, kemudian buka di laptop menjadi lancar juga, begitu pula sebaliknya.
(ibarat perlu dipancing dulu).

**Comment by eddieridwan** [comment]
Apa isi file log terakhir di folder _logs_ sesudah terjadi error 500? Coba lampirkan.

**Comment by ariandii** [comment]
Berikut terlampir log pada saat error tersebut.

[log-2019-01-23.zip](https://github.com/OpenSID/OpenSID/files/2792191/log-2019-01-23.zip)

**Comment by metalab25** [comment]
Memangnya menu rekam surat ada di Layanan Mandiri yah ???

**Comment by ariandii** [comment]
> Memangnya menu rekam surat ada di Layanan Mandiri yah ???

Sesuai judul Issues pak, Menu Daftar Rekam Surat,
bukan menu rekam surat.

![tanpa judul](https://user-images.githubusercontent.com/46939846/51688727-c6a49900-2027-11e9-900c-cf68a6be7647.png)

**Comment by metalab25** [comment]
Apakah yang dimaksud menu Layanan ???

**Comment by ariandii** [comment]
betul pak.

**Comment by eddieridwan** [comment]
@ariandii setelah mempelajari isi file log anda, sepertinya script anda salah.

Seharusnya di file `donjo-app/models/Keluar_model.php` berisi method sbb:

```
	private function list_data_sql()
	{
		$sql = " FROM log_surat u
			LEFT JOIN tweb_penduduk n ON u.id_pend = n.id
			LEFT JOIN tweb_surat_format k ON u.id_format_surat = k.id
			LEFT JOIN tweb_desa_pamong s ON u.id_pamong = s.pamong_id
			LEFT JOIN tweb_penduduk p ON s.id_pend = p.id
			LEFT JOIN user w ON u.id_user = w.id
			WHERE 1 ";
		$sql .= $this->search_sql();
		$sql .= $this->filter_sql();
		$sql .= $this->jenis_sql();
		return $sql;
	}
```

Tapi pada script anda berbeda. Sebaiknya diulangi updatenya. Ingat: pada waktu update SEMUA script inti harus diganti. Sebaiknya HAPUS semua script dulu, kecuali folder `desa`, baru update.

**Comment by ariandii** [comment]
baik pak, akan saya coba ganti ke 19.01-pasca update per hari ini.

terima kasih atas bantuannya.

**Comment by ariandii** [comment]
> @ariandii setelah mempelajari isi file log anda, sepertinya script anda salah.
> 
> Seharusnya di file `donjo-app/models/Keluar_model.php` berisi method sbb:
> 
> ```
> 	private function list_data_sql()
> 	{
> 		$sql = " FROM log_surat u
> 			LEFT JOIN tweb_penduduk n ON u.id_pend = n.id
> 			LEFT JOIN tweb_surat_format k ON u.id_format_surat = k.id
> 			LEFT JOIN tweb_desa_pamong s ON u.id_pamong = s.pamong_id
> 			LEFT JOIN tweb_penduduk p ON s.id_pend = p.id
> 			LEFT JOIN user w ON u.id_user = w.id
> 			WHERE 1 ";
> 		$sql .= $this->search_sql();
> 		$sql .= $this->filter_sql();
> 		$sql .= $this->jenis_sql();
> 		return $sql;
> 	}
> ```
> Tapi method ini pada script anda berbeda. Sebaiknya diulangi updatenya. Ingat: pada waktu update SEMUA script inti harus diganti. Sebaiknya HAPUS semua script dulu, KECUALI folder `desa`, baru update.

Informasi:
Proses hapus seluruh folder sudah saya lakukan, dan saya ganti dengan versi 19.01-pasca hasil download sore ini.

Namun ternyata error masih terjadi, berikut saya cantumkan screenshot dan file attachment log nya.

Mohon bantuan.
[log-2019-01-25.zip](https://github.com/OpenSID/OpenSID/files/2795866/log-2019-01-25.zip)
![tanpa judul](https://user-images.githubusercontent.com/46939846/51743763-4a19c500-20d0-11e9-9211-39ca039c0c35.png)

**Comment by ariandii** [comment]
Berhasil pak, Terima kasih bantuannya.

![fix](https://user-images.githubusercontent.com/46939846/51747182-47709d00-20db-11e9-9d76-43cf1c0bdfc6.png)
