### ISSUE TITLE
Validasi Jumlah Karakter Untuk Pencarian Hanya Dilakukan di Sisi Client

### ISSUE THREAD

**Issue by xanarciz** [OpenSID/OpenSID#1886]
### Bagaimana alurnya sampai muncul masalah?
Filter teks pencarian sudah dilakukan validasi agar dibatasi hanya 50 karakter, tetapi tidak ada validasi dari sisi server. Sehingga masih bisa dimanipulasi dengan mengubah parameter cari pada url.

### Seperti apa yang diharapkan?
Akan lebih baik jika dilakukan validasi pada sisi server.

### Apa yang terjadi?
Dengan mengubah parameter cari yang ada pada url, masih bisa melewati filter pembatasan jumlah karakter. Misalnya seperti link dibawah
http://localhost/OpenSID/index.php/first?cari=Lorem%20ipsum%20dolor%20sit%20amet%2C%20cras%20etiam%20pede%20eu%2C%20suspendisse%20volutpat%20duis%20accumsan%20eu%20pellentesque%2C%20faucibus%20vivamus%20etiam%20suscipit%20arcu%20laoreet%20ipsum.%20Rutrum%20nulla.%20Magna%20viverra%20cum%20a%20curabitur%2C%20metus%20accumsan.%20Euismod%20lectus%20in%2C%20nunc%20sodales%20morbi%20rutrum%20libero%20taciti%20porta%2C%20luctus%20consequat%20nibh%20wisi%20enim%20mauris%20in.%20Cum%20placerat%20sem%2C%20et%20quam%20velit%20ultrices%20urna%2C%20blandit%20est%20vel%20odio%20rutrum%2C%20ac%20tincidunt%20ac%20ornare%2C%20consectetuer%20auctor%20ante%20convallis%20vestibulum.%20Sed%20nibh%20sed%20iaculis%20diam%20eleifend%20tincidunt%2C%20imperdiet%20feugiat%20nonummy%20arcu%20elit%2C%20in%20leo%20parturient%20minus%2C%20id%20tellus%2C%20at%20nulla%20ante%20erat.%20Lacus%20dictum%20ac%20ridiculus%20purus%2C%20ac%20et%20massa%20vulputate.%20Et%20arcu%20sed%2C%20id%20odio%2C%20integer%20diam%2C%20sed%20tortor%20leo%20tempor%2C%20per%20nullam.%20Lectus%20pharetra%20malesuada%20parturient%20tempor%20nunc%2C%20ac%20adipiscing%20arcu%20dolor%20aliquam%20viverra%20enim%2C%20id%20mauris%20vitae%20hac%20suspendisse.%20Reiciendis%20mollis%2C%20quis%20donec%20at%20arcu.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 1.9
| Versi PHP        | 7.2 
| System operasi   | Ubuntu 18.04.01

**Comment by eddieridwan** [comment]
Telah dicommit ke master melalui PR #1887
