### ISSUE TITLE
Widget Artikel Populer

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#1888]
### Bagaimana alurnya sampai muncul masalah?
Masih terkendala mencari artikel terdahulu (terlebih pada halaman yang sudah banyak) dan artikel mana yang sering dikunjungi.

### Seperti apa yang diharapkan?
Adanya widget memunculkan beberapa artikel populer (sering dibaca).

### Apa yang terjadi?
Mengetahui artikel yang sering dibuka pengunjung.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by metalab25** [comment]
Sepertinya perlu ditambahkan metode "hit" agar bisa menghitung seberapa popular artikel yang akan ditampilkan dalam widget "Artikel Popular"

**Comment by eddieridwan** [comment]
Sudah dicommit ke `master` melalui PR #3058
