### ISSUE TITLE
Error hasil export surat yang berisi table

### ISSUE THREAD

**Issue by happyagung25** [OpenSID/OpenSID#1889]
### Bagaimana alurnya sampai muncul masalah?
Setelah membuat master surat baru file RTF dan file php disesuaikan dengan kebutuhan, lalu mencoba buat surat terjadi keanehan pada hasil export surat yang berisi table

### Seperti apa yang diharapkan?
Dharapkan hasil sesuai dengan template master RTF surat

### Apa yang terjadi?
yang terjadi tidak sesuai dengan template master RTF surat

### Informasi tambahan 
isi folder surat yang bersangkutan 
[surat_keterangan_pengantar_kayu.zip](https://github.com/OpenSID/OpenSID/files/2798803/surat_keterangan_pengantar_kayu.zip)

Hasil export Surat

[surat_keterangan_pengantar_kayu_5201140706966997_2019-01-26_5.zip](https://github.com/OpenSID/OpenSID/files/2798805/surat_keterangan_pengantar_kayu_5201140706966997_2019-01-26_5.zip)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19.01-pasca
| Versi PHP        |  7.2
| System operasi   | Windows 7

**Comment by adighoro13** [comment]
1. ekstrack "surat_keterangan_pengantar_kayu.zip" ke folder C:\xampp\htdocs\opensid\desa\surat
2. buka pada web browser localhost/opensid/index.php/surat_master
3. tambhkan format surat dengan nama layanan "surat_keterangan_pengantar_kayu"
4. cetak layanan surat "surat_keterangan_pengantar_kayu" maka tampilannya seperti pada gambar

![image](https://user-images.githubusercontent.com/45155815/51958433-c0307a00-248a-11e9-84f9-d0eb47a0f415.png)

5. hasil word kira2 seperti ini.

![image](https://user-images.githubusercontent.com/45155815/51958578-83b14e00-248b-11e9-8d9d-5430209c00b3.png)

**Comment by metalab25** [comment]
Kok disaya beda yah. Pake php berapa om ?

**Comment by adighoro13** [comment]
php 7.2 om

**Comment by ariandii** [comment]
![IMG_20190712_180307](https://user-images.githubusercontent.com/46939846/61123751-5a332e80-a4cf-11e9-9f65-86ba6fdf863c.jpg)

pengalaman saya. jika muncul huruf c pada kode isian rtf, coba hapus kode isian tersebut kemudian ketik ulang mulai dari tanda [ sampai tanda ]

catatan: HARUS ketik manual mulai awal kode [ sampai akhir  penutup ] , bukan copy paste atau edit kode.

**Comment by afa28** [comment]
Buat issue baru jika masih bermasalah.
