### ISSUE TITLE
Keliru Data Pekerjaan Saksi pada lampiran F 2.29

### ISSUE THREAD

**Issue by redjoel** [OpenSID/OpenSID#1890]
### Bagaimana alurnya sampai muncul masalah?
Ketika mencetak surat keterangan kematian, data pekerjaan saksi saksi yang ditampilkan di form f.2.29 keliru dan bernilai sama

### Seperti apa yang diharapkan?
Harusnya sih ga gini

### Apa yang terjadi?
Data pekerjaan saksi Tidak sesuai dengan data sebenarnya

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19.01 pasca
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
@redjoel Mohon tampilkan screenshot yg menjelaskan masalahnya.

**Comment by metalab25** [comment]
sepertinya tidak ada masalah, saya coba sudah benar seperti gambar terlampir

![screenshot_51](https://user-images.githubusercontent.com/19917739/53290462-f984ad00-37de-11e9-8ec2-9786469e350a.png)

**Comment by redjoel** [comment]
> sepertinya tidak ada masalah, saya coba sudah benar seperti gambar terlampir
> 
> ![screenshot_51](https://user-images.githubusercontent.com/19917739/53290462-f984ad00-37de-11e9-8ec2-9786469e350a.png)

berarti sudah diperbaiki pak.. 
Terima Kasih
