### ISSUE TITLE
Validasi Hapus data terpilih

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#1892]
### Bagaimana alurnya sampai muncul masalah?
Ketika tidak ada data terpilih ketika menekan tombol [ hapus data terpilih ] program tetap menjalankan fungsinya walaupun tidak ada data yang dipilih untuk dihapus

### Seperti apa yang diharapkan?
Ketika tidak ada data terpilih ketika menekan tombol [ hapus data terpilih ] program memberitahu kepada pengguna untuk "mewajibkan" memilih data yang akan dieksekusi / dihapus

### Apa yang terjadi?
tombol [hapus data terpilih] tidak mengecek / memvalidasi data apakah ada yang dipilih oleh user atau tidak

### Informasi tambahan 
![weee](https://user-images.githubusercontent.com/35319600/52068102-940e1980-25ae-11e9-9b57-fbd4b9ec664d.jpg)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dicommit ke master. Sekalian mengubah penggunaan tombol Hapus Data Terpilih di semua menu.
