### ISSUE TITLE
Tambahkan alamat pada pencarian penduduk pada rekam surat perorangan 

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#1896]
### Bagaimana alurnya sampai muncul masalah?
layanan surat > arsip layanan > rekam surat perorangan

### Seperti apa yang diharapkan?
menyertakan alamat rt rw dusun

### Apa yang terjadi?
saat ini pencarian penduduk hanya menampilkan nik dan nama

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR #1897
