### ISSUE TITLE
link di laporan bulanan 

### ISSUE THREAD

**Issue by nockturno** [OpenSID/OpenSID#1898]
### Bagaimana alurnya sampai muncul masalah?
statistik---->laporan bulanan

### Seperti apa yang diharapkan?

laporan yang dihasilkan berupa angka dan bisa nge-link ke angka tersebut
### Apa yang terjadi?

laporan yang dihasilkan hanya berupa angka dan tidak nge-link
### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by agungsugiarto** [comment]
Sepertinya ini duplikat dengan issue #1285

**Comment by nockturno** [comment]
Makasih mas koreksi nya.  Issue nya saya tutup.

Pada tanggal Sen, 4 Feb 2019 15.45 Agung Sugiarto <notifications@github.com
menulis:
