### ISSUE TITLE
Notifikasi pada halaman dashboard

### ISSUE THREAD

**Issue by metalab25** [OpenSID/OpenSID#1899]
### Bagaimana alurnya sampai muncul masalah?
Sepertinya dihalaman dashboard OpenSID belum ada notifikasi kalo ada laporan masuk dari warga atau belum ada notifikasi masuk apabila ada komentar di artikel.
sehingga admin/operator kadang terlewat membaca laporan masuk dan komentar

### Seperti apa yang diharapkan?
adanya notifikasi laporan dan komentar masuk pada halaman dashboar

### Apa yang terjadi?
admin/operator kadang terlewat membaca laporan masuk dan komentar

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | Semua Versi OpenSID
| Versi PHP        | Semua Versi PHP
| System operasi   | Semua Versi Sistem Operasi

**Comment by suphm** [comment]
buat table
 'notif' (judul, berita summary, link, date)
di ui nya adminlte sediakan icon notif/lonceng di kanan atas kalau di buka, list kan notifnya berdasarkan date. kakau entry di klik buka link menuju pagenya. entrinya bisa laporan masuk atau [update opensid](#593) atau lainnya.

bisa bantu ga om :D

**Comment by metalab25** [comment]
Hehehhehe.... saya ga mampu om

Saya mainan style css aja deh om

**Comment by metalab25** [comment]
Nah kira-kira bisa diterapkan kah ?

**Comment by xanarciz** [comment]
mirip issue #500 . saya kebetulan lagi coba-coba juga..
mungkin nantinya semua notif ada di satu table.
terus tambahan satu table lagi untuk simpan flag.

**Comment by metalab25** [comment]
Yup benar sekali

**Comment by xanarciz** [comment]
susah om.. haha :laughing:

**Comment by suphm** [comment]
saya lagi fokus di [aauth](/suphm/opensid/commits/aauth) nanti ada fungsi set_user_var($key, $value, $id) buat simpan flag nya

**Comment by suphm** [comment]
atau bisa pakai [onesignal ](/pomerla/OneSignal-Codeigniter-Push-Notification/blob/master/README.md)

**Comment by metalab25** [comment]
Wah saya ga mampu om

**Comment by eddieridwan** [comment]
Sudah dicommit ke master, hasil Edwin Potte dengan bantuan Happy Agung.
