### ISSUE TITLE
Halaman atau widget download Dokumen

### ISSUE THREAD

**Issue by happyagung25** [OpenSID/OpenSID#1900]
### Bagaimana alurnya sampai muncul masalah?
Dengan OpenSID desa-desa mampu memberi pelayanan publik secara cepat, efisien, terbuka dan akuntable, namun sampai saat ini dokumen-dokumen berkas peraturan yang bisa di uplod di halaman Admin Web > Dokumen belum ditampilkan untuk bisa di download oleh publik

### Seperti apa yang diharapkan?
Diharapkan tersedia halaman atau widget yang menampilkan dokumen-dokumen peraturan yang bisa di download publik

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by mizwaruddin** [comment]
@afa28 dokumen2 sprt informasi publik, produk hukum skrg sudah bisa ditampilkan di web dan didownload.
