### ISSUE TITLE
Ketika ubah data keluarga, tanggal cetak KK berubah dengan sendirinya

### ISSUE THREAD

**Issue by rullydamara** [OpenSID/OpenSID#1901]
### Bagaimana alurnya sampai muncul masalah?
ketika ubah data keluarga, tanggal cetak KK nya otomatis berubah tidak sesuai dengan tanggal yang telah kita input sebelumnya.

### Seperti apa yang diharapkan?
Tanggal cetak KK tidak otomatis berubah/ berubah dengan sendirinya

### Apa yang terjadi?
Tanggal KK Berubah dengan sendirinya

### Informasi tambahan 
Screenshot : https://drive.google.com/file/d/1NiluFROOEjtS-66fuUgqcdBsWjusfTZ4/view

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19.02
| Versi PHP        | 
| System operasi   | Windows 10

**Comment by MUHAMMADRANGSEL** [comment]
<script type="text/javascript" src="<?= base_url()?>assets/js/jquery.validate.min.js"></script>
<script type="text/javascript" src="<?= base_url()?>assets/js/validasi.js"></script>
<script>
	$('#tgl_1').datetimepicker(
	{
		format: 'DD-MM-YYYY'
	});
</script>
<form action="<?= $form_action?>" method="post" id="validasi">
	<div class='modal-body'>
		<div class="row">
			<div class="col-sm-12">
				<div class="box box-danger">
					<div class="box-body">
						<div class="form-group">
							<label for="no_kk">Nomor KK</label>
							<input class="form-control input-sm required" type="text" placeholder="Nomor KK" name="no_kk" value="<?= $kk['no_kk']?>"></input>
							<input name="id" type="hidden" value="<?= $kk['id']; ?>">
						</div>
						<div class="form-group">
							<label for="tgl_cetak_kk">Tanggal Cetak Kartu Keluarga <code> (Exp: 31/12/1980 )</code> </label>
							<div class="input-group input-group-sm date">
								<div class="input-group-addon">
									<i class="fa fa-calendar"></i>
								</div>
								<input class="form-control input-sm" name="tgl_cetak_kk" id="tgl_1" type="text" value="<?= **tgl_indo_out**($kk['tgl_cetak_kk'])?>"/>
							</div>
						</div>												
						<div class="form-group">
							<label>Kelas Sosial</label>
							<select class="form-control input-sm"  id="kelas_sosial" name="kelas_sosial">
								<option value="">Pilih Tingkatan Keluarga Sejahtera</option>
								<?php foreach ($keluarga_sejahtera as $data): ?>
									<option value="<?= $data['id']?>" <?php if ($kk['kelas_sosial'] == $data['id']): ?>selected <?php endif; ?>><?= strtoupper($data['nama'])?></option>
								<?php endforeach;?>
							</select>
						</div>
						<div class="form-group">
							<label>Peserta Program Bantuan Keluarga</label>
							<?php foreach ($program as $bantuan): ?>
								<div class="checkbox">
									<label>
										<input type="checkbox" name="id_program[]" value="<?= $bantuan['id']?>"/<?php if ($bantuan['peserta'] != ''): ?>checked <?php endif; ?>>
										<a href="<?= site_url('program_bantuan/detail/1/'.$bantuan['id'])?>" target="_blank"><?= $bantuan['nama']?></a>
									</label>
								</div>
							<?php endforeach; ?>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="modal-footer">
		<button type="reset" class="btn btn-social btn-flat btn-danger btn-sm" data-dismiss="modal"><i class='fa fa-sign-out'></i> Tutup</button>
		<button type="submit" class="btn btn-social btn-flat btn-info btn-sm" id="ok"><i class='fa fa-check'></i> Simpan</button>
	</div>
</form>

**Comment by MUHAMMADRANGSEL** [comment]
ini solusinya tinggal di tindih file ajax_edit_nokk yang ada di folder View/sid/kependudukan

[ajax_edit_nokk.zip](https://github.com/OpenSID/OpenSID/files/2836186/ajax_edit_nokk.zip)

**Comment by rullydamara** [comment]
Oke Pak akan saya coba.
Terima Kasih Sebelumnya

**Comment by rullydamara** [comment]
Oke Mantap Pak.
![screenshot 321](https://user-images.githubusercontent.com/45301948/52386135-45cdae80-2ab7-11e9-96b3-489f54c551ca.png)

**Comment by MUHAMMADRANGSEL** [comment]
Jangan ditutup dulu issue ini bung rullydamara spy nanti bune Eddie bisa gabungkan ke rilis

**Comment by MUHAMMADRANGSEL** [comment]
Dan bila perlu kalau bung Rully bisa buat full request nya

**Comment by rullydamara** [comment]
Oke siap pak.

**Comment by eddieridwan** [comment]
Sudah dicommit ke master
