### ISSUE TITLE
Format tanggal lahirnya keliru, Tambahkan Kolom NIK di sebelah kanan kolom KK untuk Program Bantuan jenis sasaran KK

### ISSUE THREAD

**Issue by rullydamara** [OpenSID/OpenSID#1902]
### Bagaimana alurnya sampai muncul masalah?
Format Tanggal Lahir Keliru pada Program Bantuan. 

### Seperti apa yang diharapkan?
Tolong perbaiki format tanggal lahir serta 
Tambahkan Kolom NIK di sebelah kanan kolom KK untuk Program Bantuan jenis sasaran KK, begitu juga
Tambahkan Kolom KK di sebelah kiri kolom NIK untuk Program Bantuan jenis sasaran Penduduk.
Tambahkan Kolom Jenis Kelamin dan Umur

### Informasi tambahan 
![screenshot 322](https://user-images.githubusercontent.com/45301948/52386655-8fb79400-2ab9-11e9-9fc9-ecf23c5720b5.png)
![screenshot 323](https://user-images.githubusercontent.com/45301948/52386675-a0680a00-2ab9-11e9-92f2-b201fb8d0409.png)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19.02
| Versi PHP        | 
| System operasi   | Windows 10

**Comment by boedyirh** [comment]
Saya lihat ini perlu merubah struktur table. Karena pada penerima program bantuan ada satu field peserta (yang itu bisa berisi NIK atau NoKK) Tergantung Jenis program. 
Perlu dibuat referensi field NIK dan NoKK tersendiri

**Comment by mdandidarmawan** [comment]
Untuk format tanggal, apakah perlu dirubah menjadi _DD/MM/YYYY_ ?

**Comment by mdandidarmawan** [comment]
Untuk format tanggal pada tampilan tersebut, apakah perlu dirubah menjadi `DD/MM/YYYY`?

**Comment by boedyirh** [comment]
Untuk memudahkan dengan format di Indonesia bisa dirubah menjadi DD-MM-YYY. Tidak perlu merubah struktur tabel.  hanya reformat tanggal yg ada.
<?php
$tgl 	= '2018-12-18';
$tglformatbaru     = date('d-m-Y' , strtotime($tgl));
?>

**Comment by mdandidarmawan** [comment]
> Untuk memudahkan dengan format di Indonesia bisa dirubah menjadi DD-MM-YYY. Tidak perlu merubah struktur tabel. hanya reformat tanggal yg ada.
> 
> $tgl = '2018-12-18';
> $tglformatbaru = date('d-m-Y' , strtotime($tgl));

Iya, yang saya maksud ditampilan kok, bukan struktur tabel, hehe

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
