### ISSUE TITLE
perlu ditambahkan status data ganda di log penduduk

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#1903]
### Bagaimana alurnya sampai muncul masalah?
data masyarakat banyak yang ganda sehingga data itu langsung dihapus, dan bikin desa bingung

### Seperti apa yang diharapkan?
perlu ditambahkan di log penduduk status GANDA sehingga pemerintah desa bisa mengetahui masyarakatnya yang ganda
### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by MUHAMMADRANGSEL** [comment]
![screenshot 2019-02-08 16 27 27](https://user-images.githubusercontent.com/25834335/52467098-45203f80-2bbf-11e9-9c73-487daa121ce4.png)

**Comment by afa28** [comment]
Duplicate #3520
