### ISSUE TITLE
Perbaikan visual (center text)

### ISSUE THREAD

**Issue by boedyirh** [OpenSID/OpenSID#1904]
### Bagaimana alurnya sampai muncul masalah?
Perbaikan visual saja

### Seperti apa yang diharapkan?
beberapa text lebih bagus jika di center
![image](https://user-images.githubusercontent.com/10396931/52483779-4c5b4380-2be7-11e9-9976-82514b12bee4.png)

### Apa yang terjadi?
ada beberapa field yg di pinggir

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19.02
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
Style untuk kolom bilangan dan no_urut bisa diubah oleh desa melalui `desa/css/siteman.css`
