### ISSUE TITLE
Perbaikan Visual Laporan Kependudukan Bulanan

### ISSUE THREAD

**Issue by boedyirh** [OpenSID/OpenSID#1905]
### Bagaimana alurnya sampai muncul masalah?
Laporan bulanan, untuk data penduduk rata kanan

### Seperti apa yang diharapkan?
data penduduk sebaiknya center
secara konsep:
Untuk Nama Rata Kiri
Untuk Uang Rata Kanan
Untuk NIK center 
Untuk NoKK center

![image](https://user-images.githubusercontent.com/10396931/52510352-391f9680-2c2e-11e9-8b22-33aafd2cc4f3.png)

### Apa yang terjadi?
Laporan bulanan, untuk data penduduk rata kanan

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19.02x
| Versi PHP        | 
| System operasi   |

**Comment by dikisiswanto** [comment]
Baiknya untuk issue ini dan issue-issue terkait dilakukan pull request pak supaya bisa digabung

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR #2018
