### ISSUE TITLE
Perbaikan Visual Laporan Bulanan Cetak

### ISSUE THREAD

**Issue by boedyirh** [OpenSID/OpenSID#1906]
### Bagaimana alurnya sampai muncul masalah?
Laporan Bulanan Cetak, tidak center.

### Seperti apa yang diharapkan?
Laporan Bulanan Cetak, Center
![image](https://user-images.githubusercontent.com/10396931/52512176-185b3f00-2c36-11e9-9c3b-aff90c607f57.png)

### Apa yang terjadi?
Laporan bulanan Cetak tidak bisa center, banyak class tidak jalan. Karena bootstrap.min.css belum diload

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19.02
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR #2019
