### ISSUE TITLE
Perbaikan Visual (Tampilan Bulanan)

### ISSUE THREAD

**Issue by boedyirh** [OpenSID/OpenSID#1907]
### Bagaimana alurnya sampai muncul masalah?
Pada saat cetak, ada garis yg seharusnya tidak ada
![image](https://user-images.githubusercontent.com/10396931/52515699-b9a3be80-2c51-11e9-9b3f-18a0b7b0ba65.png)

### Seperti apa yang diharapkan?
![image](https://user-images.githubusercontent.com/10396931/52515709-ccb68e80-2c51-11e9-8239-162f5a247133.png)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19.02
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR #2026
