### ISSUE TITLE
[Bug] Tautan di daftar Program Bantuan saat diklik muncul error 404

### ISSUE THREAD

**Issue by boedyirh** [OpenSID/OpenSID#1908]
### Bagaimana alurnya sampai muncul masalah?
Daftar Program Bantuan, pada kolom sasaran terdapat link. Yang kalau diklik muncul error 404
![image](https://user-images.githubusercontent.com/10396931/52519290-94cc3d00-2c8b-11e9-8e59-afdb07ce6753.png)

### Seperti apa yang diharapkan?
Seharusnya tidak ada link. Kolom Sasaran tersebut hanya informasi saja. Link cukup ada di Nama Program

### Apa yang terjadi?
Terdapat link di kolom sasaran.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19.02
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
@boedyirh saya coba di website demo tidak bermasalah (v19.02-pasca) : http://beta.opensid.info/index.php/program_bantuan

Coba tampilkan screenshot pada waktu ada error 404. Apakah update ke v19.02 berjalan lengkap dan lancar? Apakah sudah jalankan migrasi DB?

**Comment by eddieridwan** [comment]
@boedyirh link itu untuk menampilkan program bantuan hanya untuk sasaran itu. Mungkin solusi yang lebih baik adalah dengan menggunakan filter supaya konsisten dengan halaman yg lain.

**Comment by boedyirh** [comment]
> 
> 
> @boedyirh saya coba di website demo tidak bermasalah (v19.02-pasca) : http://beta.opensid.info/index.php/program_bantuan

Saya cek di beta, ketika link diklik, tidak pergi ke mana mana. Tapi memang tidak muncul error 404.

> 
> Coba tampilkan screenshot pada waktu ada error 404. Apakah update ke v19.02 berjalan lengkap dan lancar? Apakah sudah jalankan migrasi DB?

Saat ini sudah saya modifikasi, link saya hilangkan. Untuk address issue #1909 
Sudah jadi tinggal memberi tanda di github (ada penambahan field asaldana (Varchar) di table program, dan field status saya rubah menjadi statusprogram (karena status adalah reserved word di MySQL, kadang mendapat masalah saat query) , dan minta ijin jika dibolehkan untuk merge ke master.

![image](https://user-images.githubusercontent.com/10396931/52533323-c5cc7080-2d64-11e9-9067-ffd840d4301a.png)

**Comment by eddieridwan** [comment]
@boedyirh kalau ingin mengirimkan perubahan script, silakan ikuti prosedur di https://github.com/OpenSID/OpenSID/wiki/Panduan-mengirimkan-perubahan-repo-OpenSID. Penulisan script harap mengikuti aturan di https://github.com/OpenSID/OpenSID/wiki/Aturan-Penulisan-Script. Kalau mengubah struktur database, ikuti prosedur di https://github.com/OpenSID/OpenSID/wiki/Menambah-Migrasi-Database.

**Comment by eddieridwan** [comment]
@boedyirh , tautan untuk menampilkan daftar program bantuan untuk suatu sasaran telah dihilangkan dan diganti dengan filter sasaran untuk menampilkan daftar program bantuan untuk sasaran yg dipilih. Ini konsisten dengan penggunaan filter pada menu lain.

Jadi issue ini kami tutup. Tetapi silakan kirimkan pull request untuk perubahan yang anda lakukan untuk issue #1909.
