### ISSUE TITLE
Daftar Program Bantuan perlu ada keterangan lebih

### ISSUE THREAD

**Issue by boedyirh** [OpenSID/OpenSID#1909]
### Bagaimana alurnya sampai muncul masalah?
Program bantuan tidak memiliki keterangan tentang status,jumlah peserta dan asal dana. Akan lebih memudahkan bila ada keterangan tersebut.
Misalkan sudah ada program bantuan tahun 2017 dan 2018, Dan sekarang ada baru. maka status bisa diset Non-Aktif. Dan program bantuan yg ada di Tahun 2019 diset Aktif.
Asal Dana juga perlu diinfokan (Desa,Pemkot/Pemkab, Propinsi, Pusat) 

Jika suatu Program bantuan sudah ada pesertanya, Sebaiknya tombol delete tidak muncul. Untuk meminimalisir salah delete. dan ada orphan link di table program_peserta

### Seperti apa yang diharapkan?
![image](https://user-images.githubusercontent.com/10396931/52519457-1e7d0a00-2c8e-11e9-9ca9-94d7c7fbed8d.png)

![image](https://user-images.githubusercontent.com/10396931/52519674-9e58a380-2c91-11e9-98e9-970b97656447.png)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19.02x
| Versi PHP        | 
| System operasi   |

**Comment by boedyirh** [comment]
Khusus untuk table ada penambahan field di Table program dengan field asaldana varchar(20) issue #1909
ALTER TABLE `program` ADD COLUMN `asaldana` VARCHAR(30) NULL DEFAULT NULL AFTER `nama`;

**Comment by happyagung25** [comment]
kenapa tidak kirim Pull Request om @boedyirh

**Comment by eddieridwan** [comment]
@boedyirh , apakah bisa sediakan apa saja pilihan untuk kolom isian `Asal Dana`?

**Comment by boedyirh** [comment]
Asal Dana.
Dana Pemerintah Pusat.
Dana Propinsi
Dana Pemerintah Kota/Kabupaten
Lain-lain (Dana Pihak ke 3)
