### ISSUE TITLE
Share Artikel Warna Warni 

### ISSUE THREAD

**Issue by banez** [OpenSID/OpenSID#191]
[artikel.zip](https://github.com/eddieridwan/OpenSID/files/574854/artikel.zip)

penampakanya :
http://prntscr.com/d43j7w

**Comment by MUHAMMADRANGSEL** [comment]
#closed

**Comment by MUHAMMADRANGSEL** [comment]
Di closed saja

**Comment by eddieridwan** [comment]
Tidak akan diterapkan
