### ISSUE TITLE
Akses Login lever Redaksi. 

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#1910]
### Bagaimana alurnya sampai muncul masalah?
Artikel yang sudah ada tanpa sengaja terhapus oleh akun redaksi lain. 

### Seperti apa yang diharapkan?
Dalam lever redaksi mungkin bisa dibedakan antar username, misalnya:
Redaksi A tidak tidak bisa edit maupun hapus Artikel yang sudah dibuat oleh Redaksi B. apalagi akses artikel yang dibuat oleh admin. 

Level admin punya hak akses penuh atas artikel yang dibuat oleh seluruh level redaksi. 

### Apa yang terjadi?
Menghindari salah edit, salah hapus artikel yang dibuat oleh redaksi lain maupun oleh admin

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dicommit ke master:
#1910: Kecuali admin, sekarang pengguna hanya dapat mengubah artikel yang dibuat oleh pengguna itu sendiri.
