### ISSUE TITLE
Penambahan SLUG pada OpenSID

### ISSUE THREAD

**Issue by happyagung25** [OpenSID/OpenSID#1911]
### Bagaimana alurnya sampai muncul masalah?
Sepertinya perlu di terapkan SLUG pada opensid untuk penerapan SEO dan friendly URL untuk search engien lainnya serta membuat simple URL artikel OpenSID

### Seperti apa yang diharapkan?
agar berubah dari  URL : http://localhost/opensidpasca1902/index.php/first/artikel/93
menjadi
URL : http://localhost/opensidpasca1902/index.php/first/artikel/visi-misi (contohnya saja)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by suphm** [comment]
sama lah #1645

**Comment by balongbesuk** [comment]
https://github.com/ericlbarnes/CodeIgniter-Slug-Library

**Comment by xanarciz** [comment]
https://github.com/ausi/slug-generator ini kalo mau yang lebih komplit. karakter yang gak biasa, bakal di normalize juga.

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR #1980
