### ISSUE TITLE
[Bug] surat Izin Orang tua / Suami / Istri

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#1912]
### Bagaimana alurnya sampai muncul masalah?
Buat surat izin orang tua / suami / istri > pilih data penduduk > cek memberi ijin suami / istri

### Seperti apa yang diharapkan?
muncul data suami / istri

### Apa yang terjadi?
ketika memberi ijin suami / istri > data yang diberi ijin tidak muncul

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 18.02
| Versi PHP        | 
| System operasi   |

**Comment by balongbesuk** [comment]
![weeee](https://user-images.githubusercontent.com/35319600/52630374-abbe9980-2eee-11e9-8c12-e2a9c0f3f444.jpg)

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR #1927
