### ISSUE TITLE
[Bug] Tes Ubah Logo file .rtf surat biodata Penduduk

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#1913]
### Bagaimana alurnya sampai muncul masalah?
Tes Ubah Logo file .rtf surat biodata Penduduk > simpan 

### Seperti apa yang diharapkan?
tidak dianggap korrup oleh word

### Apa yang terjadi?
ketika mencetak surat yang telah diubah logonya tadi, surat cetak menjadi korup

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 18.02
| Versi PHP        | 
| System operasi   |

**Comment by boedyirh** [comment]
Saya pernah mengalami. Open file rtf. Begitu logo sudah dirubah simpan (save as)  file ke format docx
Kemudian buka ulang (file yg sudah disimpan format docx) save as ke format rtf.
Dan gunakan file rtf tersebut sebagai template surat.

**Comment by balongbesuk** [comment]
sudah saya coba dan berhasil terima kasih

**Comment by boedyirh** [comment]
Ini menurut saya bukan bug di aplikasi. Tapi mungkin ada permasalahan struktur di file rtf originalnya. sehingga file rtf tersebut harus dibuild ulang oleh MSWord.
Solusinya bisa file rtf yg bermasalah tersebut diupload ulang pada master github. direplace dengan file rtf yg telah diperbaiki strukturnya.
