### ISSUE TITLE
surat_ket_nikah

### ISSUE THREAD

**Issue by afri18** [OpenSID/OpenSID#1915]
### Bagaimana alurnya sampai muncul masalah?
timbulnya format baru pengantarnikah dengan adanya 
" Keputusan Direktur Jenderal Bimbingan Masyarakat Islam Nomor 713 Tahun 2018 
Tentang Penetapan Formulir dan Laporan Pencatatan Perkawinan atau Rujuk "

### Seperti apa yang diharapkan?
biar sama dengan format baru
dan mohon disempurnakan
[surat_ket_nikah.zip](https://github.com/OpenSID/OpenSID/files/2851562/surat_ket_nikah.zip)

### Apa yang terjadi?
saya tidak pahap degan php jadinya masih kesulitan saat mensingkronkan dengan data luar desa

### Informasi tambahan 
sebagian sudah saya perbaiki tapi tidak sempurna
| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by metalab25** [comment]
ini om sudah saya sesuaikan suratnya, mohon di cek
[surat_ket_nikah.zip](https://github.com/OpenSID/OpenSID/files/2897102/surat_ket_nikah.zip)

**Comment by karangkamulyan** [comment]
Mantapp.. kapan di update .. surat nikah opensidnya??

**Comment by karangkamulyan** [comment]
Bagaimana caranya merubah surat_nikah??

**Comment by metalab25** [comment]
Lah udah saya buatkan, silakan diupdate aja

**Comment by agungsugiarto** [comment]
Om @metalab25 sebaiknya dibuatkan pull request untuk perubahannya.

**Comment by afri18** [comment]
Untuk wali bisa auto bung @metalab25 ? 
Maksudnya kalau ayah pengantin wanita ada di kartu keluarga langsung terisi seperti data ayah , manual kalau tidak ada di database

**Comment by metalab25** [comment]
Memang saya belum coba kalo pake wali, nanti saya coba coding lagi

**Comment by happyagung25** [comment]
> engantin wanita ada di kartu keluarga langsung terisi seperti data a

bukankah apa bila pengantin wanita masih ada ayahnya memang tidak diperlukan wali, dan bukankah wali berlaku apabila ayah dari pengantin wanita tidak ada jadi sepertinya form wali memang harus diisi manual

**Comment by afri18** [comment]
Form wali tetap diisi walau ayah hidup, karena itu sebaiknya auto, kan ada Ket hub wali dgn pengantin wanita ..

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR #1957
