### ISSUE TITLE
Excel Hasil Eksport mencamtumkan Kecamatan

### ISSUE THREAD

**Issue by boedyirh** [OpenSID/OpenSID#1917]
### Bagaimana alurnya sampai muncul masalah?
Ketika eksport kependudukan ke excel (xls) tidak ada field data kecamatan. Hal ini akan membantu sekali jika kecamatan meminta data kependudukan pada desa, dan Pemkab/Pemkot meminta data tersebut dari kecamatan, 

Ini untuk memudahkan pengumpulan data di kecamatan.

### Seperti apa yang diharapkan?
Ketika eksport juga muncul field kecamatan

### Apa yang terjadi?
Ketika eksport kependudukan ke excel (xls) tidak ada field data kecamatan

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19.02.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
@boedyirh di menu Keluarga > Unduh, atau di Pengaturan > Database > Ekspor Database > Ekspor Data Keluarga?
