### ISSUE TITLE
[Bug] Error input data penduduk setelah kosongkan database

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#1918]
### Bagaimana alurnya sampai muncul masalah?
Fress Install gunakan Opensid Pasca > kosongkan database > tambahkan penduduk baru

### Seperti apa yang diharapkan?
menambahkan data data penduduk tidak menghasilkan error

### Apa yang terjadi?
ketika menambahkan data penduduk > simpan data > memunculkan error basis data 
(tapi data penduduk masuk)

### Informasi tambahan 
![weeee](https://user-images.githubusercontent.com/35319600/52632596-951b4100-2ef4-11e9-9b3f-8738211c7271.jpg)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19-02-Pasca
| Versi PHP        | 
| System operasi   |

**Comment by MUHAMMADRANGSEL** [comment]
Tweb_ktp dan setingan nomor urut surat juga bermasalah

**Comment by eddieridwan** [comment]
Telah dicommit ke master.
