### ISSUE TITLE
Export bantuan perorangan atau keluarga

### ISSUE THREAD

**Issue by boedyirh** [OpenSID/OpenSID#1919]
### Bagaimana alurnya sampai muncul masalah?
Pada bantuan yg menyasar keluarga maka data yang tersimpan adalah nomer KK
Pada bantuan yg menyasar perorangan maka data yg tersimpan adalah NIK
Dua duanya bisa diexport ke Excel dengan informasi NIK atau Nomer KK, yg tercantum

### Seperti apa yang diharapkan?
Pada pengajuan bantuan, data yg harus diajukan adalah data NIK dan Data KK.
Sehingga pada bantuan yg menyasar baik perorangan ataupun keluarga data yg muncul pada export excel adalah NoKK dan NIK.

### Apa yang terjadi?
Export Excel hanya memunculkan data NoKK pada bantuan keluarga
Export Excel hanya memunculkan data NIK pada bantuan perorangan.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19.02.x
| Versi PHP        | 
| System operasi   |

**Comment by MUHAMMADRANGSEL** [comment]
Ya betul sekali

**Comment by afa28** [comment]
Bisa gunakan unduh/download yg sdah ada. Klw masih bermasalah, issue bisa dibuka kembali.

![11111111](https://user-images.githubusercontent.com/57283157/96420214-6902a800-121f-11eb-9064-a559f086b35f.JPG)
