### ISSUE TITLE
Perbedaan Jumlah KK

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#1920]
### Bagaimana alurnya sampai muncul masalah?
Jumlah KK pada halaman utama OpenSID adalah 502.
![kk](https://user-images.githubusercontent.com/46939846/52710521-18ef2f00-2fc2-11e9-9292-543e1d67b550.png)

Sedangkan jumlah di file excel utama data desa dan hasil export Data Keluarga menunjukkan 504.
![kk2](https://user-images.githubusercontent.com/46939846/52710540-299fa500-2fc2-11e9-9765-8d744604d38e.png)

### Seperti apa yang diharapkan?
Mohon bantuan untuk solusinya supaya muncul Jumlah KK seharusnya apakah 502 atau 504.
Terima kasih.

### Apa yang terjadi?
perbedaan pun terjadi pada saat menampilkan jumlah KK menggunakan script sendiri berdasarkan database OpenSID.
![kkweb](https://user-images.githubusercontent.com/46939846/52710881-150fdc80-2fc3-11e9-8873-78207bedda0d.png)

Berikut scriptnya.
![kkscript](https://user-images.githubusercontent.com/46939846/52710987-48eb0200-2fc3-11e9-9cdf-5b8318eb056f.png)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by balongbesuk** [comment]
bagi script statistik penduduknya dunk bang @ariandii

**Comment by ariandii** [comment]
Ini pak, script yang saya gunakan untuk statistik penduduk. masih ada selisih jumlah KK dengan tampilan yang ada di halaman admin.


![tanpa judul](https://user-images.githubusercontent.com/46939846/52758093-9f932300-3039-11e9-8e62-ffd7feb7a53d.png)

**Comment by balongbesuk** [comment]
seperti yang saya bilang sebelumnya cek kembali data penduduknya pak biasaya ada data keluarga yang tidak mempunyai status Kepala Keluarga

untuk scriptnya sepertinya akan bermasalah ketika opensid berjalan seiring waktu, karena tweb_penduduk akan menyimpan data penduduk (hidup, pindah, mati) dan twep_keluarga akan menyimpan (kk aktif dan tidak)

**Comment by eddieridwan** [comment]
Seperti dikatakan @balongbesuk, jumlah entri di tweb_keluarga belum tentu yang aktif semua. Keluarga dengan KK yang tidak aktif tidak akan tampil di halaman Dashboard maupun di halaman Keluarga dengan filter KK Aktif.

@ariandii Silakan periksa data anda di halaman Keluarga, dengan menggunakan filter KK Kosong dan lainnya.

Kalau sudah jelas, silakan tutup issue ini, karena bukan error untuk diperbaiki.
