### ISSUE TITLE
Perbaikan Tombol SHARE artikel Tweet

### ISSUE THREAD

**Issue by PWidodo** [OpenSID/OpenSID#1921]
### Bagaimana alurnya sampai muncul masalah?
Manakala tombol share Tweet di klik tidak menyertakan link artikel terkait untuk di share, tetapi hanya membuka link Tweet pada tab baru.

### Seperti apa yang diharapkan?
Yang diharapkan tombol share Tweet tersebut dapat berfungsi seperti tombol share lainnya, manakala di klik maka gambar utama dan link artikel muncul pada tab baru akun tweeter.

### Apa yang terjadi?
Hal tersebut karena coding perintahnya tidak mengikutsertakan directory link artikel terkait

### Informasi tambahan 
Akan saya coba Pull Request untuk Bug ini
| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19.02
| Versi PHP        | 
| System operasi   |

**Comment by PWidodo** [comment]
Saran Perbaikan sudah saya buat pada Pull request #1922

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
