### ISSUE TITLE
[Security] Bug XSS Komentar dan Validasi field No. HP

### ISSUE THREAD

**Issue by xanarciz** [OpenSID/OpenSID#1923]
### Bagaimana alurnya sampai muncul masalah?
Ketika pengunjung menginputkan script xss pada komentar, browser admin bisa mengeksekusi scriptnya. Selain itu feild nomer handphone tidak difilter untuk hanya bisa memasukan nomer saja.

### Seperti apa yang diharapkan?
XSS filtering, validasi field nomer handphone.

### Apa yang terjadi?
XSS bisa merusak tampilan pada menu komentar pada admin, menjalankan script berbahaya untuk admin, membuat halaman palsu untuk social engineering dll.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19.02
| Versi PHP        |  7.2
| System operasi   | Ubuntu 18.04.1

**Comment by eddieridwan** [comment]
@xanarciz apakah ada contoh serangan XSS untuk kolom isian komentar? Sepertinya penggunaan `strip_tags` sudah menangkis?

**Comment by xanarciz** [comment]
Mohon maaf baru sempat membalas karna keadaan saya yang minggu-minggu ini agak kurang sehat. Dalam kasus ini strip_tags memang sudah cukup untuk menangkal serangan XSS. Saya kelupaan menghapus testing komentar yang saya update melalui menu admin. XSS hanya berlaku untuk komentar yang di edit oleh admin saja, jadi aplikasi masih aman dari tangan jahil diluar admin.
