### ISSUE TITLE
[Bug] Ketika kosongkan database tweb_status_ktp dan setting_aplikasi_options kosong

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#1925]
### Bagaimana alurnya sampai muncul masalah?
Ketika baru instal Aplikasi OpenSID dan setelah itu melalalku kosongkan database ternyata tweb_status_ktp dan setting_aplikasi_options kosong 

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by MUHAMMADRANGSEL** [comment]
Isian 2 tweb tersebut kosong

**Comment by suphm** [comment]
maksudnya diimpor lagi terus kosong?

**Comment by MUHAMMADRANGSEL** [comment]
Setelah di kosongkan database untuk 2 tweb tersebut hasilnya blank

Pada tanggal Sab, 16 Feb 2019 17.24 Yusup Hambali <notifications@github.com
menulis:

**Comment by agungsugiarto** [comment]
yang diharapkan isian dari 2 table tersebut tidak kosong ?

**Comment by suphm** [comment]
pengisian table tsb oleh proses migrasi

**Comment by MUHAMMADRANGSEL** [comment]
Ya betul, karena setelah kosongkan database, mengisi data dengan data
penduduk di menu statistik penduduk berdasarkan kepemilikan KTP tdk muncul
dan waktu setting penomoran surat juga kosong

Pada tanggal Min, 17 Feb 2019 19.37 Agung Sugiarto <notifications@github.com
menulis:

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
