### ISSUE TITLE
Bug Pengelolaan Dusun

### ISSUE THREAD

**Issue by mazsam** [OpenSID/OpenSID#1926]
### Bagaimana alurnya sampai muncul masalah?
Kosongkan Penduduk -> kosongkan dusun -> tambahkan dusun dengan nama kepala dusun kosong

### Seperti apa yang diharapkan?
Ketika nama kepala dusun tidak dipilih / dikosongkan simpan dengan string kosong / 0

### Apa yang terjadi?
Ketika kepala dusun kosong muncul error

### Informasi tambahan 
![screenshot from 2019-02-17 17-37-02](https://user-images.githubusercontent.com/17076855/52911756-e94e6880-32da-11e9-8d13-15d00a9c22f7.png)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19.02
| Versi PHP        | 7.2
| System operasi   | Ubuntu

**Comment by metalab25** [comment]
Bukankah nama Kepala Dusun memang harus diisi dan bisa diisi dengan menginput manual

**Comment by eddieridwan** [comment]
Error ini tidak ditemukan di http://beta.opensid.info.
@mazsam coba update ke versi pra-rilis. Kalau masih mengalami masalah, silakan buka issue ini lagi.
