### ISSUE TITLE
gunakan  continuous integration

### ISSUE THREAD

**Issue by sup-ham** [OpenSID/OpenSID#1928]
### Seperti apa yang diharapkan?
Menggunakan layanan CI (continuous integration) untuk otomasi
- Testing aplikasi 
- Memperbaiki code mengikuti aturan penulisan

Biar kayak proyek-proyek keren lainnya 8-)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | all
| Versi PHP        |  >= 3.7
| System operasi   | all

**Comment by suphm** [comment]
- [Pilihan layanan CI](https://github.com/marketplace/category/continuous-integration), diantaranya gratis untuk proyek opensource.

**Comment by balongbesuk** [comment]
ini kayak "addon" nya CI kah pak?

**Comment by suphm** [comment]
ini addon github

**Comment by suphm** [comment]
selama ini kita mengandalkan 2 hari sebelum rilis untuk testing. dengan ini testingnya dikakukan otomatis setiap ada commits/pullrequest ke github

**Comment by agungsugiarto** [comment]
Pakai punya microsoft azure pipeline gratis

**Comment by mdandidarmawan** [comment]
Harus ada yang siap untuk menyiapkan Test cases nya..

**Comment by dikisiswanto** [comment]
Mungkin bisa dipertimbangkan pak @eddieridwan

**Comment by yus-ham** [comment]
saya udah jarang ikuti proyek ini.
ini sudah ada fiturnya ya?

**Comment by andifahruddinakas** [comment]
> saya udah jarang ikuti proyek ini.
> ini sudah ada fiturnya ya?

Sudah ada untuk point 2 tp belum digabungkan ke rilis umum.
