### ISSUE TITLE
tambahkan pencarian pada filter jenis surat di Arsip Layanan surat

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#1929]
### Bagaimana alurnya sampai muncul masalah?
layanan surat > arsip surat > user hanya bisa memilih surat (tidak ada pencarian surat)

### Seperti apa yang diharapkan?
ditambahkan pencarian surat aga memudahkan sortir arsip surat

### Apa yang terjadi?
ketika desa memiliki jenis surat yang banyak ketika sortir surat akan memakan waktu, dengan ditambahkan pencarian surat akan mempercepat mencari arsip surat yang akan disortir

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR #1930
