### ISSUE TITLE
Form kematian pelapor kembali ke atas

### ISSUE THREAD

**Issue by boedyirh** [OpenSID/OpenSID#1931]
### Bagaimana alurnya sampai muncul masalah?
Pada saat mengisi Pelapor kematian dari luar desa, form tiba tiba loading ulang ke halaman paling atas, sehingga harus discroll balik secara manual

![image](https://user-images.githubusercontent.com/10396931/52946029-a3aaa200-33a5-11e9-800c-9489967a2b79.png)

### Seperti apa yang diharapkan?
Seharusnya saat dipilih pelapor dari luar desa, form tetap (atau kembali pada lokasi semula) agar memudahkan pengisian. 

### Apa yang terjadi?
Form melakukan reload semua web, dari pertama.
### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19.02 pasca
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR #1932
