### ISSUE TITLE
dengan adanya perper no 96 tahun 2018 permintaan database ke dispendukcapil tidak bisa berupa file pdf atau excel tetapi lewat jaringan yang terhubung dispenduk capil. jadi untuk pengguna baru aplikasi opensid kesusahan database. yang diharapkan aplikasi opensid dalam hal database dapat terintegrasi dengan dispendukcapil

### ISSUE THREAD

**Issue by didikmdm** [OpenSID/OpenSID#1933]
### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by boedyirh** [comment]
apakah itu maksudnya setiap desa akan bisa memiliki akun untuk mengakses database Disdukcapil (mungkin via VPN). Sehingga desa bisa mengakses data desa mereka sendiri.

**Comment by didikmdm** [comment]
Betul pak setiap desa akan bisa memiliki akun untuk mengakses database Disdukcapil (via VPN)

**Comment by didikmdm** [comment]
Dengan adanya sistem baru dalam hal akses database di disdukcapil, bagaimakah cara penerapan opensid untuk mengatasi hal tersebut?

**Comment by suphm** [comment]
adakah contoh  struktur databasenya. biasanya mendownload  json dari server
