### ISSUE TITLE
URL /webupdate16610

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#1934]
### Bagaimana alurnya sampai muncul masalah?
Asik-asik ketik artikel hingga beberapa paragraf kemudian pada saat klik simpan, halaman logout secara otomatis.

### Seperti apa yang diharapkan?
Kelancaran dan kenyamanan akses halaman admin OpenSID.

### Apa yang terjadi?
Pada case ini saat klik simpan artikel, sering terjadi secara berulang
1. halaman admin logout dengan sendirinya,
2. pada saat login kembali muncul halaman 404 dengan URL /webupdate16610.
3. setelah klik reload, baru masuk halaman admin.
4. masuk menu artikel, ketik-ketik, saat klik simpan, kembali ke nomor 1.
Namun kadang normal, artikel disimpan tanpa terjadi logout.

Info tambahan:
Hal ini terjadi setelah ada 1 artikel yang saya nonaktifkan (artikel nomor 65).
Artikel nomor 66 sulit untuk disimpan. edit pun begitu, saat simpan lalu logout dengan sendirinya.

![tanpa judul](https://user-images.githubusercontent.com/46939846/53261553-e7374000-3706-11e9-8e81-980e7a6b976c.png)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19.2
| Versi PHP        | 
| System operasi   | Windows 10 Original

**Comment by mdandidarmawan** [comment]
Ada baiknya untuk mengirimkan table artikelnya

**Comment by ariandii** [comment]
> Ada baiknya untuk mengirimkan table artikelnya

ternyata bukan pada saat klik simpan artikel saja, namun error tersebut "kadang" terjadi saat klik menu Artikel pada kategori Admin Web.
Setelah logout otomatis, kemudian login kembali URL yang muncul /webupdate

![artikel](https://user-images.githubusercontent.com/46939846/53280427-9ea27580-374c-11e9-8f5d-29276c7c3b2b.png)

**Comment by metalab25** [comment]
kirimkan error log nya biar bisa dianalisa

**Comment by ariandii** [comment]
berikut terlampir file log dari cpanel. 

[log-2019-02-23.zip](https://github.com/OpenSID/OpenSID/files/2897379/log-2019-02-23.zip)

**Comment by ariandii** [comment]
Berikut terlampir error log tanggal 24 dan 25.

[log-2019-02-25.zip](https://github.com/OpenSID/OpenSID/files/2900264/log-2019-02-25.zip)

**Comment by ariandii** [comment]
berikut terlampir error log tgl 26.

[log-2019-02-26.php.zip](https://github.com/OpenSID/OpenSID/files/2906202/log-2019-02-26.php.zip)

**Comment by agungsugiarto** [comment]
Om @ariandii apakah error juga ditemukan di demo.opensid.info ?

**Comment by ariandii** [comment]
sampai saat ini di demo belum saya temukan hal serupa, mohon bantuan perkiraan itu kenapa ya pak, sebab klik menu apapun sering logout sendiri dan saat login ulang masuk halaman 404 seperti error log di atas.

berikut jawaban dari admin hosting yang saya tanya. 

![img_20190301_173547](https://user-images.githubusercontent.com/46939846/53633017-ecd1e000-3c48-11e9-871c-b58d451f86fe.jpg)

**Comment by ariandii** [comment]
Salam.
Ternyata terjadi kesalahan pada server hosting yang menyebabkan service php melakukan restart tiap menit. Mungkin hal tersebut yang mempengaruhi session pada web natairaya.mtk.web.id selama beberapa hari ini.

Terima kasih.
