### ISSUE TITLE
Tidak Bisa edit Alamat pada KL

### ISSUE THREAD

**Issue by MallaAli** [OpenSID/OpenSID#1936]
### Apa yang terjadi?

Saya tidak bisa edit alamat pada KK

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
@MallaAli harap lihat panduan https://github.com/OpenSID/OpenSID/wiki/Pengisian-Data-Keluarga, lihat bagian _Pindah Keluarga Ke Wilayah Lain Dalam Desa_, dan juga lihat https://github.com/OpenSID/OpenSID/wiki/Pengisian-Data-Penduduk lihat bagian _Pindah Penduduk Ke Wilayah Lain Dalam Desa_.

Masalah seperti ini adalah kurang informasi penggunaan OpenSID dan sebaiknya ditanyakan di https://web.facebook.com/groups/OpenSID/. Issue hanya untuk hal2 yg bersifat error untuk diperbaiki melalui programming.

**Comment by eddieridwan** [comment]
@MallaAli rajin2 membaca panduan.

**Comment by MallaAli** [comment]
Saya tanya di fb, dianjurkan tanya kesini, sebaliknya juga bgitu, jadi saya harus gmn😥

**Comment by eddieridwan** [comment]
Itu jawabannya sudah diberikan di atas. Saya ulangi:

Harap lihat panduan https://github.com/OpenSID/OpenSID/wiki/Pengisian-Data-Keluarga, lihat bagian _Pindah Keluarga Ke Wilayah Lain Dalam Desa_, dan juga lihat https://github.com/OpenSID/OpenSID/wiki/Pengisian-Data-Penduduk lihat bagian _Pindah Penduduk Ke Wilayah Lain Dalam Desa_.

Sekali lagi, tempat bertanya penggunaan di FB. Issue hanya untuk masalah yg memerlukan programming.

**Comment by eddieridwan** [comment]
@MallaAli kalau memang ada error yg tampil, silakan lampirkan screenshot errornya. Cara melaporkan masalah diberikan di https://github.com/OpenSID/OpenSID/wiki/Pengelolaan-Masalah-dan-Permintaan-Perbaikan-SID.

**Comment by benioke** [comment]
Baca panduan sob
