### ISSUE TITLE
Surat Pindah Penduduk - Tidak Sesuai di Kab.Lima Puluh Kota

### ISSUE THREAD

**Issue by HerryWanda** [OpenSID/OpenSID#1937]
### Bagaimana alurnya sampai muncul masalah?
Surat pengantar pindah penduduk yang dicetak menggunakan openSid tidak diterima oleh kecamatan maupun Dukcapil Kabupaten Lima Puluh Kota karna berbeda format ...

### Seperti apa yang diharapkan?
1. Diharapkan bisa disesuaikan dengan format yang diberikan DUKCAPIL kabupaten Lima PUluh kota
2. Jenis Surat Pindah Yang digunakan :  
    - 	PERPINDAHAN PENDUDUK ANTAR NAGARI DALAM SATU KECAMATAN
        * Formulir B.1 (di nagari)
        * Formulir B.2 (di Nagari)
        * Formulir B.3 (kecamatan)

    - 	PERPINDAHAN PENDUDUK ANTAR KECAMATAN DALAM SATU KABUPATEN
        * Formulir C.1 (di nagari)
        * Formulir C.2 (di nagari)
        * Formulir C.3 (kecamatan)

    - 	PERPINDAHAN PENDUDUK ANTAR KAB/KOTA DALAM SATU PROVINSI ATAU ANTAR PROVINSI
        * Formulir B.1 (di nagari)
        * Formulir D.1 (di nagari)
        * Formulir D.2 (di nagari)
        * Formulir D.3 (DUKCAPIL KABUPATEN)

### Apa yang terjadi?
surat pindah yang di openSid belum bisa digunakan dikabupaten Lima Puluh Kota.... karna tidak diterima oleh Kecamatan dan DUKCAPIL KABUPATEN karna beda format...

### Informasi tambahan 
PENDAFTARAN PINDAH DATANG PENDUDUK 
DI KABUPATEN LIMA PULUH KOTA 

A.	PERPINDAHAN PENDUDUK DALAM SATU NAGARI
Tata Cara Pendaftaran Pindah Datang:
1.	Penduduk melapor kepada Wali Nagari  
2.	Penduduk mengisi dan menandatangani Formulir Permohonan Pindah (Formulir A.1.)
3.	Petugas registrasi mencatat dalam Buku Harian Peristiwa Kependudukan dan Peristiwa Penting (BHPKPP)
4.	Petugas registrasi melakukan verifikasi dan validasi data penduduk;
5.	Wali Nagari menerbitkan dan menandatangani Surat Keterangan Pindah Datang (Formulir A.2.)
6.	KTP yang bersangkutan dicabut dan dimusnahkan oleh Wali Nagari
7.	Petugas registrasi mencatat dalam Buku Induk Penduduk (BIP) dan Buku Mutasi Penduduk (BMP) 
8.	Wali Nagari mengirimkan tembusan Surat Keterangan Pindah Datang ke Kantor Kependudukan dan Catatan Sipil untuk perekaman ke dalam database kependudukan.
9.	Surat Keterangan Pindah berlaku selama 30 (tiga puluh) hari kerja dan berlaku sebagai pengganti KTP selama KTP baru belum diterbitkan.

B.	PERPINDAHAN PENDUDUK ANTAR NAGARI DALAM SATU KECAMATAN
Persyaratan:
1.	Surat pengantar dari Wali Jorong (Formulir B.1.)
2.	KK
3.	KTP
Tata Cara Pendaftaran Pindah Datang:
1.	Penduduk melapor kepada Wali Nagari dengan memenuhi syarat-syarat di atas
2.	Di Kantor Wali Nagari tempat asal:
a.	Penduduk mengisi dan menandatangani Formulir Permohonan Pindah (Formulir B.2.)
b.	Petugas registrasi mencatat dalam Buku Harian Peristiwa Kependudukan dan Peristiwa Penting (BHPKPP)
c.	Petugas registrasi melakukan verifikasi dan validasi data penduduk
d.	Wali Nagari menerbitkan dan menandatangani Surat Keterangan Pindah (Formulir B.3.)
e.	KTP yang bersangkutan dicabut dan dimusnahkan oleh Wali Nagari
f.	Petugas registrasi mencatat dalam Buku Induk Penduduk (BIP) dan Buku Mutasi Penduduk (BMP)
g.	Surat Keterangan Pindah sebagaimana dimaksud pada huruf d diserahkan kepada penduduk untuk dilaporkan kepada Wali Nagari tujuan
h.	Wali Nagari mengirimkan tembusan Surat Keterangan Pindah ke Kantor Kependudukan dan Catatan Sipil untuk perekaman ke dalam database kependudukan
3.	Penduduk melaporkan kedatangannya kepada Wali Nagari tempat tujuan dengan menunjukkan Surat Keterangan Pindah dari tempat asal
4.	Di Kantor Wali Nagari tempat tujuan:
a.	Penduduk mengisi dan menandatangani Formulir Permohonan Pindah Datang untuk mendapatkan Surat Keterangan Pindah Datang (Formulir …)
b.	Petugas registrasi mencatat dalam Buku Harian Peristiwa Kependudukan dan Peristiwa Penting (BHPKPP)
c.	Petugas registrasi melakukan verifikasi dan validasi data penduduk
d.	Wali Nagari menerbitkan dan menandatangani Surat Keterangan Pindah Datang (Formulir…)
e.	Wali Nagari mengirimkan tembusan Surat Keterangan Pindah Datang ke Kantor Kependudukan dan Catatan Sipil untuk perekaman ke dalam database kependudukan.
5.	Surat Keterangan Pindah berlaku selama 30 (tiga puluh) hari kerja dan berlaku sebagai pengganti KTP selama KTP baru belum diterbitkan

C.	PERPINDAHAN PENDUDUK ANTAR KECAMATAN DALAM SATU KABUPATEN
Persyaratan:
1.	Surat pengantar dari Wali Jorong  (Formulir C.1.)
2.	KK
3.	KTP
Tata Cara Pendaftaran Pindah Datang:
1.	Penduduk melapor kepada Wali Nagari dengan memenuhi syarat-syarat di atas
2.	Di Kantor Wali Nagari tempat asal:
a.	Penduduk mengisi dan menandatangani Formulir Permohonan Pindah (Formulir C.2.)
b.	Petugas registrasi melakukan verifikasi dan validasi data penduduk
c.	Petugas registrasi mencatat dalam Buku Harian Peristiwa Kependudukan dan Peristiwa Penting (BHPKPP)
d.	Wali Nagari mengetahui dan membubuhkan tanda tangan pada Surat Pengantar dari Wali Jorong 
e.	Petugas registrasi mencatat dalam Buku Induk Penduduk (BIP) dan Buku Mutasi Penduduk (BMP)
f.	Wali Nagari/Petugas registrasi meneruskan berkas Formulir Permohonan Pindah sebagaimana dimaksud dalam huruf a dan Surat Pengantar sebagaimana dimaksud pada huruf d kepada Camat
3.	Di Kantor Camat tempat asal:
a.	Petugas melakukan verifikasi dan validasi data penduduk; 
b.	Camat menerbitkan dan menandatangani Surat Keterangan Pindah (Formulir C.3.)
c.	KTP yang bersangkutan dicabut dan dimusnahkan oleh Camat
d.	Surat Keterangan Pindah sebagaimana dimaksud pada huruf b diserahkan kepada penduduk untuk dilaporkan ke daerah tujuan
e.	Camat mengirimkan tembusan Surat Keterangan Pindah ke Kantor Kependudukan dan Catatan Sipil untuk perekaman ke dalam database kependudukan
4.	Penduduk melaporkan kedatangannya kepada Wali Nagari tempat tujuan dengan menunjukkan Surat Keterangan Pindah dari tempat asal
5.	Di Kantor Wali Nagari tempat tujuan:
a.	Penduduk mengisi dan menandatangani Formulir Permohonan Pindah Datang (Formulir…)
b.	Petugas registrasi mencatat dalam Buku Harian Peristiwa Kependudukan dan Peristiwa Penting (BHPKPP)
c.	Petugas registrasi melakukan verifikasi dan validasi data penduduk
d.	Wali Nagari menandatangani dan meneruskan Formulir Permohonan Pindah Datang sebagaimana dimaksud dalam huruf a kepada Camat
6.	Di Kantor Camat tempat tujuan:
a.	Petugas melakukan verifikasi dan validasi data penduduk 
b.	Camat menerbitkan dan menandatangani Surat Keterangan Pindah Datang (Formulir …)
c.	Camat mengirimkan tembusan Surat Keterangan Pindah Datang ke Kantor Kependudukan dan Catatan Sipil untuk perekaman ke dalam database kependudukan
7.	Surat Keterangan Pindah berlaku selama 30 (tiga puluh) hari kerja dan berlaku sebagai pengganti KTP selama KTP baru belum diterbitkan

D.	PERPINDAHAN PENDUDUK ANTAR KABUPATEN ATAU KOTA DALAM SATU PROVINSI ATAU ANTAR PROVINSI
Persyaratan:
1.	Surat pengantar dari Wali Jorong  (Formulir B.1.)
2.	KK
3.	KTP
Tata Cara Pendaftaran Pindah Datang:
1.	Penduduk melapor kepada Wali Nagari dengan memenuhi syarat-syarat di atas
2.	Di Kantor Wali Nagari tempat asal:
a.	Penduduk mengisi dan menandatangani Formulir Permohonan Pindah (Formulir D.1.)
b.	Petugas registrasi mencatat dalam Buku Harian Peristiwa Kependudukan dan Peristiwa Penting (BHPKPP)
c.	Petugas registrasi melakukan verifikasi dan validasi data penduduk
d.	Wali Nagari menandatangani Surat Pengantar Pindah antar kabupaten/kota atau antar provinsi (Formulir D.2.)
e.	Petugas registrasi mencatat dalam Buku Induk Penduduk (BIP) dan Buku Mutasi Penduduk (BMP)
f.	Wali Nagari/Petugas registrasi meneruskan berkas Formulir Permohonan Pindah sebagaimana dimaksud pada huruf a dan Surat Pengantar Pindah sebagaimana dimaksud pada huruf d kepada camat
3.	Di Kantor Camat tempat asal:
a.	Petugas melakukan verifikasi dan validasi data penduduk
b.	Camat menandatangani Surat Pengantar Pindah antar kabupaten/kota atau antar provinsi sebagaimana dimaksud pada poin 2 huruf f
c.	Petugas registrasi menyampaikan Formulir Permohonan Pindah sebagaimana dimaksud pada poin 2 huruf f dan Surat Pengantar Pindah sebagaimana dimaksud pada poin 3 huruf b kepada Kepala Kepala Kantor Kependudukan dan Catatan Sipil  sebagai dasar penerbitan Surat Keterangan Pindah
4.	Kepala Kantor Kependudukan dan Catatan Sipil menerbitkan dan menandatangani Surat Keterangan Pindah serta menyerahkan kepada penduduk untuk dilaporkan ke daerah tujuan (Formulir D.3.)
5.	KTP yang bersangkutan dicabut dan dimusnahkan oleh Kepala Kantor Kependudukan dan Catatan Sipil
6.	Perekaman ke dalam database kependudukan
7.	Surat Keterangan Pindah berlaku selama 30 (tiga puluh) hari kerja dan berlaku sebagai pengganti KTP selama KTP baru belum diterbitkan

Lampiran (Formulir ) :  

- [BLANKO-BI.docx](https://github.com/OpenSID/OpenSID/files/2903549/BLANKO-BI.docx)
- [BLANKO-B2.pdf](https://github.com/OpenSID/OpenSID/files/2903553/BLANKO-B2.pdf)
- [BLANKO-B3.pdf](https://github.com/OpenSID/OpenSID/files/2903561/BLANKO-B3.pdf)

- [BLANKO-C1.pdf](https://github.com/OpenSID/OpenSID/files/2903564/BLANKO-C1.pdf)
- [BLANKO-C2.pdf](https://github.com/OpenSID/OpenSID/files/2903565/BLANKO-C2.pdf)

- [BLANKO-D1.pdf](https://github.com/OpenSID/OpenSID/files/2903566/BLANKO-D1.pdf)
- [BLANKO-D2.pdf](https://github.com/OpenSID/OpenSID/files/2903567/BLANKO-D2.pdf)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by metalab25** [comment]
apakah format surat pindah ini baku untuk keseluruh desa-desa/kelurahan di indonesia.
mohon tanggapannya @HerryWanda @MUHAMMDADRANGSEL dan @afri18

**Comment by HerryWanda** [comment]
Kalo untuk pengantar dari desa/nagari kemungkinab ada yg berbeda...
Klo di 50 kota, seperti ini pengantarnya dari nagari ke dukcapil nya mas...

Pada tanggal Rab, 27 Feb 2019 17.40 Happy <notifications@github.com menulis:

**Comment by metalab25** [comment]
nanti saya coba buatkan

**Comment by mizwaruddin** [comment]
@HerryWanda apakah masih dibutuhkan?

**Comment by andifahruddinakas** [comment]
Silahkan dibukan kembali jika masih bermaslah.
