### ISSUE TITLE
SURAT PENGANTAR KARTU KELUARGA (KK) BARU - DARI NAGARI KE KEC/DUKCAPIL KABUPATEN

### ISSUE THREAD

**Issue by HerryWanda** [OpenSID/OpenSID#1938]
### Bagaimana alurnya sampai muncul masalah?
Format pengantar Pembuatan Kartu Keluarga (KK) baru tidak diterima di DUKCAPIL Kabupaten Lima Puluh Kota , karna ada perbedaan format pengantar.

### Seperti apa yang diharapkan?
"Diharapkan format pengantar pembuatan Kartu Keluarga (KK) baru dapat ditambahkan sesuai dengan yang digunakan diKabupaten Lima Puluh Kota.

### Apa yang terjadi?
Untuk saat ini untuk pengantar pembuatan Kartu Keluarga (KK) Baru sampai sekarang , data masih diketik Manual, karna formatnya belum sesuai dari DUKCAPIL Kab.Lima Puluh Kota.

### Informasi tambahan 
Lampiran Format Formulir Pengantar KK baru di Kab.Lima Puluh Kota : 

- [FORMULIR F.1.0.1.pdf](https://github.com/OpenSID/OpenSID/files/2903584/FORMULIR.F.1.0.1.pdf)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by metalab25** [comment]
loh bukannya F1.01 sudah ada di OpenSID

**Comment by HerryWanda** [comment]
Beda formatny f.1.0.1 disini mas.. kan dah pernah dibilang juga sama mas
dulu..

Pada tanggal Rab, 27 Feb 2019 18.09 Happy <notifications@github.com menulis:

**Comment by metalab25** [comment]
nah masalahnya ini berlaku secara nasional apa tidak, kalo dalam opensid harus berskala nasional biar semua bisa pake

**Comment by mizwaruddin** [comment]
@HerryWanda apakah masih dibutuhkan?
