### ISSUE TITLE
[Bug] Error pada kolom Tgl SK Pengangkatan

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#1940]
### Bagaimana alurnya sampai muncul masalah?
pada menu info desa -> pemerintahan desa -> staf desa, saat edit kolom tanggal SK selalu berubah. 

### Seperti apa yang diharapkan?
seperti seharusnya, walau edit tanggal SK tetap sesuai dengan input awal. 

### Apa yang terjadi?
setiap klik edit staf desa, pada kolom tanggal SK pengangkatan selalu berubah ke tahun 2020.

![img_20190226_174213](https://user-images.githubusercontent.com/46939846/53407525-fa8c2900-39ee-11e9-9dc0-7951edd79c95.jpg)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR #1941
