### ISSUE TITLE
TAMBAH FITUR CETAK SURAT DI DASHBOARD>SID 

### ISSUE THREAD

**Issue by benioke** [OpenSID/OpenSID#1942]
Bagaimana alurnya sampai muncul masalah?
Belum adanya fitur cetak surat di dashboard>sid 

Seperti apa yang diharapkan?

adanya fitur cetak surat di dashboard>sid
![capture8](https://user-images.githubusercontent.com/47577404/53501042-1b7f7780-3ade-11e9-9056-9745f371be5f.jpg)

Apa yang terjadi?

Pada saat ini ada 6 fitur yang ada.fitur wilayah dusun, penduduk, keluarga, program bantuan, dan kelompok.Mengingat fitur ini sering di gunakan maka perlu di tambah fiturnya menjadi 7 fitur.fitur itu adalah fitur cetak surat

 Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19.02
| Versi PHP        | 
| System operasi   |

**Comment by benioke** [comment]
Mf semuanya kalau ada kesalahan tata cara penulisan..baru perdana membuat issues.silahkan admin tutup issue nya.biar bikin issue yang baru

**Comment by suphm** [comment]
baiknya bookmark di browser aja pak

**Comment by happyagung25** [comment]
widget dihalaman depan sepertinya bukan shortcut tapi adalah menampilkan statistik, itu pemahaman saya

**Comment by eddieridwan** [comment]
Sudah dicommit melalui PR #2064
