### ISSUE TITLE
Penambahan "Tanggal Kegiatan Agenda"

### ISSUE THREAD

**Issue by happyagung25** [OpenSID/OpenSID#1944]
Pada PR ini saya menambahkan "Tanggal Kegiatan Agenda" jadi nantinya yang ditampilkan pada widget agenda bukan lagi tanggal upload Kegiatan/Agenda namun yang ditampilkan adalah Tanggal kegiatan dari Agenda tersebut

**Comment by dikisiswanto** [comment]
Apakah sama dengan issue #1784 pak?

**Comment by happyagung25** [comment]
Iya namun hanya sebatas tanggal kegiatan agenda, untuk lokasi dan detailnya tidak saya tambahkan

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
