### ISSUE TITLE
PERBAIKAN FORMAT TANGGAL PADA FORM SURAT TERAKHIR DI FORM SURAT

### ISSUE THREAD

**Issue by benioke** [OpenSID/OpenSID#1945]
Bagaimana alurnya sampai muncul masalah?

Format tanggal di form surat terakhir sekarang ini adalah Y-m-d
![capture11](https://user-images.githubusercontent.com/47577404/53501160-4c5fac80-3ade-11e9-9b10-d1e45932d52c.jpg)

Seperti apa yang diharapkan?

 Di ubah dengan format d-m-Y
![capture12](https://user-images.githubusercontent.com/47577404/53501195-597c9b80-3ade-11e9-80dd-aceda1b77b47.jpg)

 Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19.02
| Versi PHP        | 
| System operasi   |

**Comment by metalab25** [comment]
tolong lampirkan gambar pada bagian mana format yang salah

**Comment by benioke** [comment]
Pada tanggal Rab, 27 Feb 2019 19:13, Happy <notifications@github.com>
menulis:

**Comment by benioke** [comment]
![capture11](https://user-images.githubusercontent.com/47577404/53500624-4e753b80-3add-11e9-80f1-736812eae5a3.jpg)
![capture12](https://user-images.githubusercontent.com/47577404/53500650-5cc35780-3add-11e9-840a-8d0d89ffc764.jpg)

**Comment by benioke** [comment]
Coba coba mas agungg...contoh itu di surat pengantar..itu halaman formnya

**Comment by metalab25** [comment]
apakah maksudnya menjadi seperti gambar dibawah 
![screenshot_73](https://user-images.githubusercontent.com/19917739/53505284-833dbe80-3aee-11e9-8fee-f71f22958b2c.png)
Kalo seperti itu saya hanya merubah pada form surat masing-masing, cuma hal ini tidak efisien karena harus merubah semua file php form surat.
saya masih mencari cara agar dapat mengubah 1 untuk semua form surat

**Comment by benioke** [comment]
Okee mas happy agung...

Pada tanggal Rab, 27 Feb 2019 23:20, Happy <notifications@github.com>
menulis:

**Comment by eddieridwan** [comment]
Sudah dicommit ke `master`.
