### ISSUE TITLE
Penambahan WhatsApp pada widget Sosial Media

### ISSUE THREAD

**Issue by happyagung25** [OpenSID/OpenSID#1952]
Penambahan whatsapp di widget "Sosial Media" ini diharapkan membantu mempermudah komunikasi antara warga dan perangkat desa atau operator dalam memperoleh informasi layanan.
Dengan format text WhatsApp yang di sesuaikan fitur ini bisa digunakan sebagai media permohonan surat atau pendaftaran Layanan Mandiri atau pun sebagai laporan langsung

![screenshot_75](https://user-images.githubusercontent.com/19917739/53546274-e0755680-3b66-11e9-9a9b-b669bebdde0a.png)

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
