### ISSUE TITLE
[Bug] Operator, Redaksi, Kontributor tidak bisa buat artikel baru

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#1954]
### Bagaimana alurnya sampai muncul masalah?
Ketika Operator, Redaksi, Kontributor Mau buat artikel baru tidak
![image](https://user-images.githubusercontent.com/25834335/53677565-0593d180-3ced-11e9-8c7e-0ac62a25b6ee.png)
di http://demo.opensid.info juga tidak bisa
![image](https://user-images.githubusercontent.com/25834335/53677579-3ffd6e80-3ced-11e9-8991-876ccaa1fa24.png)

### Seperti apa yang diharapkan?
Seharusnya bisa buat artikel

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
