### ISSUE TITLE
Penambahan detail Artikel/Agenda Kegiatan Desa

### ISSUE THREAD

**Issue by happyagung25** [OpenSID/OpenSID#1956]
Penambahan detail Artikel/Agenda Kegiatan Desa yang ditampilkan di Widget Agenda
![screenshot_86](https://user-images.githubusercontent.com/19917739/53678893-274a8400-3d00-11e9-9798-b77b7f3bfc68.png)
![screenshot_87](https://user-images.githubusercontent.com/19917739/53678894-274a8400-3d00-11e9-94d5-fc9a1a17e82f.png)
![screenshot_88](https://user-images.githubusercontent.com/19917739/53678895-27e31a80-3d00-11e9-8ffe-39cbe63a7117.png)

**Comment by eddieridwan** [comment]
Telah dicommit ke master melalui PR #1955
