### ISSUE TITLE
Perlu bisa simpan lokasi peta tempat tinggal pada waktu membuat penduduk baru

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#1958]
### Bagaimana alurnya sampai muncul masalah?
1. Buka _Penduduk > Penduduk Domisili > Cari Tempat Tinggal_
2. Coba ubah lokasi tempat tinggal

Juga di 
1. _Keluarga > Tambah KK Baru_, dan
2. _Keluarga > Tambah Anggota Keluarga_

### Seperti apa yang diharapkan?
Lokasi bisa disimpan (di form), walaupun penduduk belum ada di database; dan tersimpan di database pada waktu menyimpan biodata lainnya.

### Apa yang terjadi?
Lokasi tidak bisa disimpan

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | v19.03
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
Duplicate #2659
