### ISSUE TITLE
[Bug] Tombol 'Batal' ada tapi tidak berfungsi di Layanan Surat

### ISSUE THREAD

**Issue by dikisiswanto** [OpenSID/OpenSID#1961]
### Bagaimana alurnya sampai muncul masalah?
* Buka menu _Layanan Surat > Cetak Surat_
* Pilih salah satu jenis surat

Perhatikan di bawah sebelah kiri dari _form_ terdapat tombol _Batal_, namun tidak berfungsi, kecuali pada surat Keterangan Penduduk.

![image](https://user-images.githubusercontent.com/22239074/53691819-866fcd80-3dc0-11e9-89cd-ab9aca3f68ca.png)

### Seperti apa yang diharapkan?
Tombol _Batal_ berfungsi sesuai peruntukannya atau lebih baik dihapus kalau tidak diperlukan.

### Apa yang terjadi?
Tombol _Batal_ tidak memiliki aksi apapun setelah ditekan.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19.03
| Versi PHP        | 7.2
| System operasi   | Windows

**Comment by eddieridwan** [comment]
Sudah dicommit ke master
