### ISSUE TITLE
Tidak Bisa Edit Artikel

### ISSUE THREAD

**Issue by xanarciz** [OpenSID/OpenSID#1962]
### Bagaimana alurnya sampai muncul masalah?
Admin web > Artikel > klik tombol ubah data pada salah satu artikel.

### Seperti apa yang diharapkan?
Seharusnya menu edit artikel muncul dan berjalan normal.

### Apa yang terjadi?
Ketika ingin melakukan edit artikel, menu tidak muncul, hanya halaman kosong saja tanpa menampilkan error code.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19.03-pasca
| Versi PHP        | 7.2.15
| System operasi   | Ubuntu 18.04.1

**Comment by eddieridwan** [comment]
@xanarciz , di http://beta.opensid.info berjalan normal. Kesalahan ada di database anda. Periksa database anda. Kembalikan ke backup anda sebelumnya, kalau perlu.

**Comment by Zulkarnaimni** [comment]
Kolom Jumlah (Pengurangan) pada Grafik Statisti Pak Eddie

![image](https://user-images.githubusercontent.com/64481641/87718606-46a25e00-c7dc-11ea-9658-b74bb94e517e.png)

**Comment by eddieridwan** [comment]
> Kolom Jumlah (Pengurangan) pada Grafik Statisti Pak Eddie
> 
> ![image](https://user-images.githubusercontent.com/64481641/87718606-46a25e00-c7dc-11ea-9658-b74bb94e517e.png)

@Zulkarnaimni harap buat issue terpisah untuk masalah tidak terkait. Harap tidak membuat komentar yg tidak terkait issue ini. Terima kasih.
