### ISSUE TITLE
[Bug] Penduduk datang dan kelahiran tidak tercatat

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#1963]
### Bagaimana alurnya sampai muncul masalah?
statistik > laporan bulanan

### Seperti apa yang diharapkan?
penduduk pendatang (pindah datang) dan kelahiran tercatat

### Apa yang terjadi?
ketiak operator menambahkan penduduk pindah datang dan kelahiran pada kolom laporan bulanan tidak tercatat

### Informasi tambahan 
![weee3](https://user-images.githubusercontent.com/35319600/53745978-cd4de800-3ed2-11e9-9dfe-ada47124af75.jpg)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by ai-skematik** [comment]
Sy punya juga seperti itu, hasil akhir bertambah,, tp pada rincian tidak terisi.

**Comment by dikisiswanto** [comment]
Ini bug karena salah memilih parameter date di controller laporan.

**Comment by eddieridwan** [comment]
Telah dicommit ke master

**Comment by eddieridwan** [comment]
Perbaikan yg dilakukan untuk menampilkan data pendatang.

Tampilan data kelahiran berjalan normal dan tidak error. Jumlah yg dilaporkan adalah yg TANGGAL LAHIRNYA adalah pada bulan laporan. Jadi pastikan tanggal lahir penduduk benar.

**Comment by redjoel** [comment]
thank you pak @dikisiswanto
