### ISSUE TITLE
Ada tanah persil yang dimiliki oleh warga di luar desa

### ISSUE THREAD

**Issue by boedyirh** [OpenSID/OpenSID#1964]
### Bagaimana alurnya sampai muncul masalah?
Ketika akan mengisi informasi pemilik tanah, hanya disuguhkan daftar warga, Sehingga tidak bisa mengisi nama pemilik jika pemilik tersebut adalah warga di luar desa
![image](https://user-images.githubusercontent.com/10396931/53769045-4d913f00-3f0d-11e9-8210-7b2041eabe8a.png)

### Seperti apa yang diharapkan?
Karena kepemilikan bisa lintas desa/kota. Diharapkan field tersebut bisa diisi dengan informasi warga di luar desa

### Apa yang terjadi?
Dropdown menu hanya menampilkan pilihan warga desa

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19.03
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
@boedyirh harap lihat https://github.com/OpenSID/OpenSID/wiki/Persil.
Anda dapat membantu dengan menlengkapi panduan persil. Petunjuknya di https://github.com/OpenSID/OpenSID/wiki/Mengembangkan-Panduan-OpenSID. Silakan.

**Comment by boedyirh** [comment]
Oh...Terima kasih Pak
