### ISSUE TITLE
Kategori Lokasi Untuk Sarana Kesahatan, tidak muncul

### ISSUE THREAD

**Issue by boedyirh** [OpenSID/OpenSID#1965]
### Bagaimana alurnya sampai muncul masalah?
Membuka daftar tipe lokasi untuk sarana kesehatan

### Seperti apa yang diharapkan?
Terdapat Rumah Sakit

### Apa yang terjadi?
Menampilkan field, tapi nama masih kosong.
![image](https://user-images.githubusercontent.com/10396931/53772359-b92cd980-3f18-11e9-8ad2-541b468e083f.png)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19.03
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
@boedyirh tinggal diubah saja bung (itu ada tombol ubah). Jenis sarana kesehatan tinggal dibuat sesuai dgn kebutuhan desa (Tambah Kategori Sarana Kesehatan).

Silakan bantu lengkapi panduan https://github.com/OpenSID/OpenSID/wiki/Pengaturan-Peta. Sepertinya panduan akan membantu teman2 lain seperti anda yg juga meraba-raba. OpenSID untuk kita kembangkan bersama-sama. Silakan!
