### ISSUE TITLE
Typo tautan breadcrumb pada laman Home > SID

### ISSUE THREAD

**Issue by dikisiswanto** [OpenSID/OpenSID#1966]
### Bagaimana alurnya sampai muncul masalah?
* Buka laman _Home > SID_
* Arahkan kursor ke tautan _home_ pada breadcrumb
* Klik tautan

### Seperti apa yang diharapkan?
Tidak terjadi typo pada tautan breadcrumb

### Apa yang terjadi?
Salah tautan

![image](https://user-images.githubusercontent.com/22239074/53779145-0ec5ae00-3f3a-11e9-9585-7708dcfd1872.png)

![image](https://user-images.githubusercontent.com/22239074/53779237-649a5600-3f3a-11e9-9d67-3d73acabc61b.png)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dicommit ke master
