### ISSUE TITLE
[Bug] Detail penduduk dari Laporan Kelompok Rentan tidak muncul

### ISSUE THREAD

**Issue by dikisiswanto** [OpenSID/OpenSID#1969]
### Bagaimana alurnya sampai muncul masalah?
* Buka menu _Statistik > Laporan Kelompok Rentan_
* Klik pada jumlah penduduk yang ditampilkan di statistik, khususnya pada kolom sakit menahun dan cacat

### Seperti apa yang diharapkan?
Tampil detail penduduk sesuai jumlah yang ditampilkan

### Apa yang terjadi?
Tidak menampilkan penduduk yang bersangkutan.

Berikut tangkapan layar sebagai pendukung dari issue ini:

![image](https://user-images.githubusercontent.com/22239074/53847229-cd410b80-3fea-11e9-9cc0-39beebde3b6b.png)
_Jumlah penduduk tidak cacat berjumlah 1_

![image](https://user-images.githubusercontent.com/22239074/53847310-25780d80-3feb-11e9-9cf6-0e8df8511edb.png)
_Tidak tampil detail penduduk yang dimaksud_

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19.03-pasca
| Versi PHP        | 7.2
| System operasi   | Windows

**Comment by agungsugiarto** [comment]
Saya tidak menemukan masalah yang dimaksud.
![lap_1](https://user-images.githubusercontent.com/10989147/53871941-c092d680-402f-11e9-9f66-ba7e20b9101e.png)

![lap_2](https://user-images.githubusercontent.com/10989147/53871963-c983a800-402f-11e9-9d28-0e281ed29456.png)

**Comment by dikisiswanto** [comment]
Saya sudah mencoba di komputer lokal dan di [demo.opensid.info](https://demo.opensid.info)

**Comment by agungsugiarto** [comment]
Saya juga sudah mencoba di demo dan beta opensid, iya ternyata di demo menemukan error yang dimaksud tapi tidak di beta.

**Comment by eddieridwan** [comment]
Detail yg tidak tampak ternyata adalah penduduk pendatang/domisili. Karena statistiknya mengikut-sertakan penduduk pendatang, detailnya perlu menampilkannya juga.

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
