### ISSUE TITLE
[Layout] Merapikan tampilan arsip artikel

### ISSUE THREAD

**Issue by happyagung25** [OpenSID/OpenSID#1970]
Merapikan tampilan arsip artikel dari 

Tampilan Awal 
![screenshot_119](https://user-images.githubusercontent.com/19917739/53905260-12188100-4083-11e9-874d-742aea2a2ec0.png)

Menjadi 
![screenshot_118](https://user-images.githubusercontent.com/19917739/53905270-193f8f00-4083-11e9-95a4-6ef889cdc779.png)

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR #1971
