### ISSUE TITLE
penambahan menu cetak surat di website

### ISSUE THREAD

**Issue by mojosar** [OpenSID/OpenSID#1972]
### Seperti apa yang diharapkan?
tambahkan menu cetak surat di website

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by hasap86** [comment]
Untuk menandatanganinya oleh Kades atau Sekdes bagaimana?

**Comment by mojosar** [comment]
bisa lansung datang ke kades atau sekdes. nanti akan kita tambahkan QR kode
untuk verifikasinya. bisa bantu penambahan menu cetak surat di website ya

Pada tanggal Min, 21 Apr 2019 07:03, Hari Saputra <notifications@github.com>
menulis:

**Comment by afa28** [comment]
Silahkan gunakan layanan mandiri, adapaun masalah teknis yg ada di desa bisa disesuaikan sendiri oleh pemerintah desa bersangkutan.
