### ISSUE TITLE
[Bug] Jabatan Tidak Tampil Ketika Akan Di Cetak Di SK Kades dan Perdes

### ISSUE THREAD

**Issue by muhamaddifa** [OpenSID/OpenSID#1973]
### Bagaimana alurnya sampai muncul masalah?
Ketika Klik Cetak Di Menu SK Kades Dan Perdes Jabtana Tidak Tampil ,Dan Penempatan TTD Tidak Rapih 
![image](https://user-images.githubusercontent.com/38423803/54065484-3081a680-4254-11e9-83fd-f7fce1c126a4.png)

### Seperti apa yang diharapkan?
Jabatan Tampil Dan Penempatan TTD  Yang rapih , Keinginan Seperti Surat Masuk Dan Surat Keluar Ketika Di Cetak 

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
@muhamaddifa supaya rapi, seperti apa yg diinginkan -- harap beri contoh tampilan yg diinginkan.

**Comment by eddieridwan** [comment]
Jabatan sekarang sudah tampil. Sudah dicommit ke master.

**Comment by eddieridwan** [comment]
ttd sudah dirapikan. Issue ini ditutup.
