### ISSUE TITLE
tambahkan tombol kartu keluarga pada biodata penduduk

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#1974]
### Bagaimana alurnya sampai muncul masalah?
ketika mengupdate data keluarga operator di tuntut untuk mengubah biodata penduduk yang mana ketika sudah diedit dan disimpan, operator harus mencari kembali data keluarga yang lain di menu pencarian penduduk / keluarga

### Seperti apa yang diharapkan?
ada tombol untuk menu kartu keluarga yang bersangkutan di menu biodata penduduk

### Apa yang terjadi?
setelah menyimpan data penduduk yang berubah tidak ada tombol untuk menuju daftar keluarga 

### Informasi tambahan 
![Untitled1111](https://user-images.githubusercontent.com/35319600/54176161-4e534380-44c0-11e9-872f-33bb28796025.jpg)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by balongbesuk** [comment]
saya sudah cb menambahkan tombol tersebut namun sepertinya KK yang dimaksud tidak mendeteksi no KK dengan data biodata yang ditampilkan yang akhirnya tombol tersebut malah memunculkan KK dengan kartu keluarga nol dengan seluruh isian data keluarga dengan KK nol,

maaf kurang ilmu

**Comment by happyagung25** [comment]
saya kerjakan issue ini

**Comment by eddieridwan** [comment]
Sudah dicommit melalui PR #1975
