### ISSUE TITLE
bisa tambahkan menu cetak surat 

### ISSUE THREAD

**Issue by mojosar** [OpenSID/OpenSID#1976]
### Bagaimana alurnya sampai muncul masalah?
kami minta ditambahkan menu cetak surat di menu layanan

### Seperti apa yang diharapkan?
user atau pengguna bisa mengakses surat lewat website tanpa datang ke operator 

### Apa yang terjadi?
karena kami menambahkan alat anjungan pelayanan mandiri.
jadi yang kami harapkan setelah user memasukan nomor NIK dan PIN
maka data user terbuka dan bisa mengakses menu layanan cetak surat sesua yang dipilih oleh user

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by happyagung25** [comment]
ini permintaan ?

**Comment by balongbesuk** [comment]
coba langsung hubungi pengembang

duplicate #1972

**Comment by mojosar** [comment]
iya bisa dikususkan untuk desa saya

Pada tanggal Rab, 13 Mar 2019 11:07, balongbesuk <notifications@github.com>
menulis:

**Comment by ariandii** [comment]
Bisa hubungi pak @eddieridwan untuk permintaan tersebut.

**Comment by eddieridwan** [comment]
Apakah ini sama dengan #2235, #791, #341, #398?

Sepertinya fitur ini penting bagi banyak desa. Cara untuk mempercepat fitur ini adalah supaya desa2 yg memerlukan menganggarkan secara patungan, supaya kita bisa bayar programmer.

**Comment by mojosar** [comment]
BERAPA BIAYA NYA

**Comment by mojosar** [comment]
bisa komunikasi via wa untuk siapa yang bisa bantu saya menambahkan menu
cetak surat pada tampilan depan website

**Comment by eddieridwan** [comment]
@mojosar , silakan hubungi kami dari OpenDesa di WA/Telegram +62 420 870 776 untuk membahas kebutuhan anda ini.

**Comment by eddieridwan** [comment]
Kita gunakan issue #2235 sebagai issue tunggal untuk layanan permohonan surat di Layanan Mandiri. Mohon gabungkan spesifikasi yg diperlukan ke issue tersebut.

**Comment by eddieridwan** [comment]
Sudah dicommit sebagai fitur premium
