### ISSUE TITLE
Bug import data penduduk 

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#1977]
### Bagaimana alurnya sampai muncul masalah?
di facebook ada pengguna yang kesulitan mengimpor data penduduk desanya, setelah saya cermati ternyata data penduduk pada kolom pekerjaan, kewarganegaraan, dan cacat tidak dapat mengenal isian huruf, 

### Seperti apa yang diharapkan?
bisa mengenal isian huruf kembali

### Apa yang terjadi?
ketika mengimpor data penduduk dengan isian huruf pada kolom pekerjaan, warganegara dan cacat terjadi error kode tidak dikenal

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
@balongbesuk menggunakan cara impor yg mana?
Perlu lampirkan contoh data yg bermasalah.

**Comment by balongbesuk** [comment]
impor data penduduk format excel 

[Copy of Book1.zip](https://github.com/OpenSID/OpenSID/files/2959732/Copy.of.Book1.zip)

**Comment by haqi89** [comment]
Coba download formatnya ulang krna kalau dilihat tulisan/keterangan yg dblok dengan warna hijau di hapus..

**Comment by redjoel** [comment]
apakah issue ini sudah selesai pak @balongbesuk ?

**Comment by balongbesuk** [comment]
![Untitled12121](https://user-images.githubusercontent.com/35319600/60559717-8cc68400-9d77-11e9-8b61-d9ffb2e7b294.jpg)

isian pekerjaan berupa huruf masih belum bisa masuk

**Comment by balongbesuk** [comment]
contoh data sesuai dengan contoh diatas

**Comment by eddieridwan** [comment]
@balongbesuk , sesuai https://github.com/OpenSID/OpenSID/issues/999, kode 'PETANI/PERKEBUNAN' telah diganti menjadi 'PETANI/PEKEBUN'. Kalau kode huruf lain seharusnya berhasil diimpor.

**Comment by balongbesuk** [comment]
saya pakai contoh format impor pada bawaan opensid pak, 

![Untitled12121](https://user-images.githubusercontent.com/35319600/60561168-d5347080-9d7c-11e9-8a1a-eab4c9e5de0a.jpg)

mungkin file tersebut perlu diupdate

**Comment by balongbesuk** [comment]
petani / pekebun sudah bisa masuk

untuk isian huruf WNI masih belum bisa masuk

![Untitled12121](https://user-images.githubusercontent.com/35319600/60561334-5c81e400-9d7d-11e9-97ff-f3200aa63f0d.jpg)

**Comment by balongbesuk** [comment]
isian huruf untuk cacat juga belum bisa masuk

![Untitled12121](https://user-images.githubusercontent.com/35319600/60561455-bda9b780-9d7d-11e9-964f-6588bb08955a.jpg)
