### ISSUE TITLE
PENAMBAHAN DATA PAJAK DAN BUMI BANGUNAN YANG HARUS DI BAYAR WARGA

### ISSUE THREAD

**Issue by arifrohman99** [OpenSID/OpenSID#1978]
Mohon di tambahkan fitur dimana warga dapat melihat besaran pajak atas tanah atau bangunan sebagaimana di Surat Pemberitahuan Pajak Terhutang (SPPT) Pajak Bumi dan Bangunan
jadi warga tinggal masukkan nomor objek pajak (NOP) di website kemudian di suguhkan data :
- nama dan alamat wajib pajak
- Nomor onjek pajak
- Besaran Pajak Yang Harus Di bayar
- Keterangan sudah terbayar dan belum terbayar.

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by ariandii** [comment]
artinya apakah disediakan kolom untuk input data NJOP tiap tahun nya? pertanyaannya sediakah input NJOP sebanyak lokasi yang ada di desa tersebut?

**Comment by arifrohman99** [comment]
iya betul,

Pada tanggal Sel, 28 Mei 2019 00.21, Ariandi Ryan Kahfi <
notifications@github.com> menulis:

**Comment by mizwaruddin** [comment]
@afa28 fitur PBB sudah ada utk pengguna premium. Untuk pengecekan besaran pajak yang dibayarkan saya rasa tidak perlu krn sdh ada petugas yg membagikan SPPT PBB kepada wajib pajak.

**Comment by afa28** [comment]
Sudah tersedia di Aplikasi terpisah. Silahkan hubungi pengurus opendesa untuk memperoleh aplikasinya.
