### ISSUE TITLE
Foto tidak terbaca di artikel jika nama filenya ada tanda ( )

### ISSUE THREAD

**Issue by WAHYUDIK** [OpenSID/OpenSID#1979]
### Bagaimana alurnya sampai muncul masalah?
ketika upload foto yang nama filenya ada tanda ( ). foto tidak muncul diartikel
![image](https://user-images.githubusercontent.com/31026980/54474897-6a871580-481d-11e9-9c9d-b2e10a7c2d1c.png)

### Seperti apa yang diharapkan?
diharapkan untuk upload file/foto meskipun nama filnya ada tanda () tidak terjadi masalah. sehingga user tidak usah merubah nama file.

### Apa yang terjadi?
sudah uji coba untuk delet tanda () akhirnya bisa terbca 

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19.03 Pasca
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dicommit ke `master`.
