### ISSUE TITLE
Tambahkan Settingan SKIN (Tema Sistem)

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#1981]
### Bagaimana alurnya sampai muncul masalah?
 Opensid dibangun dengan dasar thema AdminLTE

pada web AdminLTE https://adminlte.io ternyata ada settingan yang menarik bernama "SKIN (tema sistem)" 

![weee3](https://user-images.githubusercontent.com/35319600/54490058-43941680-48e5-11e9-84aa-330f016e0d7b.jpg)

### Seperti apa yang diharapkan?
adanya settingan SKIN (tema sistem) pada Opensid

### Apa yang terjadi?
fiturnya ada namun belum dapat diterapkan pada aplikasi Opensid

### Informasi tambahan 

![weee4](https://user-images.githubusercontent.com/35319600/54490185-43e0e180-48e6-11e9-8e28-3fe120dfe43c.jpg)

![weee6](https://user-images.githubusercontent.com/35319600/54490142-e6e52b80-48e5-11e9-9a05-71b378cfc222.jpg)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by dikisiswanto** [comment]
Issue ini sudah saya coba kerjakan melalui PR #1983 

Berikut tampilan contoh penerapan setting skin_sid di modul administrasi OpenSID. 
![image](https://user-images.githubusercontent.com/22239074/54603484-622e1500-4a7f-11e9-8597-5a1bd45f7d2b.png)

**Comment by eddieridwan** [comment]
Sudah dicommit melalui PR #1983
