### ISSUE TITLE
Perlu Ada Edit Alamat Di Ubah Biodata Penduduk atau di Menu Keluarga 

### ISSUE THREAD

**Issue by muhamaddifa** [OpenSID/OpenSID#1982]
### Bagaimana alurnya sampai muncul masalah?
![image](https://user-images.githubusercontent.com/38423803/54575926-bd80e880-4a28-11e9-8319-3f4d54f7d759.png)
Tidak Bisa Edit Alamat di Ubah Biodata  Penduduk, Apabila Ketika Mengimport data penduduk masi ada yang salah tidak harus mengimport ulang 

### Seperti apa yang diharapkan?
Ada Menu Edit alamat  di Ubah Biodata  Penduduk, atau di Kartu Keluarga 
![image](https://user-images.githubusercontent.com/38423803/54576213-cde59300-4a29-11e9-8da0-cbe233c3764f.png)
Boleh Juga Disini ada Menu edit Alamat 
![image](https://user-images.githubusercontent.com/38423803/54576303-20bf4a80-4a2a-11e9-8737-30e4d8973c57.png)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by muhamaddifa** [comment]
Sudah Di Temukan Permasalhan nya

**Comment by dikisiswanto** [comment]
Duplicate #1958

**Comment by KASWANDI** [comment]
Perlu penambahan menu ubah alamat, #1958

**Comment by haqi89** [comment]
> Sudah Di Temukan Permasalhan nya

Caranya gimana bang?? saya juga masih bingung

**Comment by eddieridwan** [comment]
Sudah dicommit ke master:
#1982: Sekarang bisa ubah alamat/dusun/rw/rt keluarga di form Ubah Data KK.

**Comment by eddieridwan** [comment]
#1982: Sekarang bisa ubah alamat/dusun/rw/rt keluarga di form Ubah Data KK dan di form Ubah Biodata anggota keluarga. Juga bisa ubah alamat/dusun/rw/rt penduduk lepas di form Ubah Biodata.

Sudah dicommit ke master.
