### ISSUE TITLE
[Bug] Url Donasi Pengembangan Opensid menampilkan halaman 404

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#1985]
### Bagaimana alurnya sampai muncul masalah?
Buka Home > Donasi > Cek Url Donasi Pengembangan Opensid, 

### Seperti apa yang diharapkan?
menampilkan halaman yang semestinya

### Apa yang terjadi?
mengulang laporan #1096 mungkin lupa dikerjakan,

### Informasi tambahan 

opsi lain mungkin dibikinkan pop up aplikasi didalam opensid yang muncul sehari sekali

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
