### ISSUE TITLE
Halaman Utama tidak muncul usai migrasi DB

### ISSUE THREAD

**Issue by choky183** [OpenSID/OpenSID#1987]
### Bagaimana alurnya sampai muncul masalah?
dashboard admin normal ketika link home page di klik  tidak muncul.
00
Sebuah Kesalahan Basis Data Telah Terjadi

Error Number: 1146

Table 'open_sid1903.agenda' doesn't exist

SELECT a.*, g.*, u.nama AS owner, k.kategori AS kategori FROM artikel a LEFT JOIN user u ON a.id_user = u.id LEFT JOIN agenda g ON g.id_artikel = a.id LEFT JOIN kategori k ON a.id_kategori = k.id WHERE id_kategori='1000' AND a.enabled = 1 AND a.tgl_upload < NOW() ORDER BY a.tgl_upload DESC

Filename: C:/OpenSID/htdocs/OpenSID/system/database/DB_driver.php

Line Number: 691

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
> ### Bagaimana alurnya sampai muncul masalah?
> dashboard admin normal ketika link home page di klik tidak muncul.
> 00
> Sebuah Kesalahan Basis Data Telah Terjadi
> 
> Error Number: 1146
> 
> Table 'open_sid1903.agenda' doesn't exist
> 
> SELECT a._, g._, u.nama AS owner, k.kategori AS kategori FROM artikel a LEFT JOIN user u ON a.id_user = u.id LEFT JOIN agenda g ON g.id_artikel = a.id LEFT JOIN kategori k ON a.id_kategori = k.id WHERE id_kategori='1000' AND a.enabled = 1 AND a.tgl_upload < NOW() ORDER BY a.tgl_upload DESC
> 
> Filename: C:/OpenSID/htdocs/OpenSID/system/database/DB_driver.php
> 
> Line Number: 691
> 
> ### Seperti apa yang diharapkan?
> ### Apa yang terjadi?
> ### Informasi tambahan
> Tanya	Jawab
> Versi OpenSID	2.x
> Versi PHP	
> System operasi

Pak @eddieridwan , sy baru lihat beberapa kesalahan pemanggilan query. Salah satu contoh pemanggilan query pd modul agenda seperti gambar di atas. Harusnya yg di jadikan sumber itu adalah tabel agenda dan mengabil data rujukan ke artikel, bukan sebaliknya. 

Query = SELECT, FORM->agenda bukan FROM artikel.

**Comment by Nurhidayat29** [comment]
sudah teratasi di OpenSID terbaru
