### ISSUE TITLE
[Bug] [Security] Upload File di Unggah Gambar Artikel

### ISSUE THREAD

**Issue by mugi789** [OpenSID/OpenSID#1988]
### Bagaimana alurnya sampai muncul masalah?
Ketika saya mengunggah file png yg saya isi script html, masih bisa masuk
dengan cara tamper data

![gambar](https://user-images.githubusercontent.com/32443765/54870539-66896380-4dda-11e9-8416-db798657b9d2.png)

![gambar](https://user-images.githubusercontent.com/32443765/54870546-7e60e780-4dda-11e9-8bd8-228071cbc638.png)

Dan ini contoh file yg saya unggah [http://sid.languagetechnologies.com/desa/upload/artikel/kecil_1553368380_test.html](http://sid.languagetechnologies.com/desa/upload/artikel/kecil_1553368380_test.html)

### Seperti apa yang diharapkan?
Hanya file gambar saja yg dpt dingguah

### Apa yang terjadi?
Dapat mengunggah file pada form unggah gambar di artikel dengan cara tamper data

### Informasi tambahan 
Tidak hanya extensi .html saja yg bisa masuk, file lainnya pun dpt masuk. Contohnya .txt .jsp . phtml

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19.03
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
@mugi789 terima kasih telah melaporkan.

Sekarang file gambar yg bisa diunggah harus bereksensi .jpg, .jpeg atau .png. Silakan tes lagi di https://belajar.opendesa.id. Sementara situs ini digunakan untuk testing.

Tapi file anda masih bisa diunggah kalau diganti ektensinya menjadi .png, .jpg atau .jpeg. Dalam hal ini apakah masih ada celah? Saya lihat contoh file anda ada html setelah IEND di file png. Saya coba ganti menjadi javascript atau php -- dan tidak berhasil diungguh. 

Apakah anda mempunyai contoh file png atau jpg berisi script PHP atau javascript yg berhasil diunggah?

**Comment by mugi789** [comment]
> Apakah anda mempunyai contoh file png atau jpg berisi script PHP atau javascript yg berhasil diunggah?

kalo untuk png yg berisi script php saya ndak punya mas

**Comment by mugi789** [comment]
> Sekarang file gambar yg bisa diunggah harus berekstensi .jpg, .jpeg atau .png. Silakan tes lagi di https://belajar.opendesa.id. Sementara situs ini digunakan untuk testing.

Oke mas, udh fix
![gambar](https://user-images.githubusercontent.com/32443765/54874932-619ed100-4e27-11e9-9875-9c1046409448.png)

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
