### ISSUE TITLE
[BUG] [XSS] Script XSS Pada Form Menu / Nama Desa

### ISSUE THREAD

**Issue by mugi789** [OpenSID/OpenSID#1989]
### Bagaimana alurnya sampai muncul masalah?
1. Login http://belajar.opendesa.id/index.php/siteman
![gambar](https://user-images.githubusercontent.com/32443765/54882345-a2c8cc80-4e8b-11e9-8a74-2b716037747a.png)

2. Lanjut ke page http://belajar.opendesa.id/index.php/menu/form/1 > Tambah Menu Baru
![gambar](https://user-images.githubusercontent.com/32443765/54881998-4f08b400-4e88-11e9-9768-317d3720be3a.png)
3. Isi kata2 **<script>alert("Apakah Ini Bug XSS ?")</script>** pd kolom Nama > pilih jenis link Artikel Status > lalu klik Simpan
![gambar](https://user-images.githubusercontent.com/32443765/54882024-7a8b9e80-4e88-11e9-9989-2b315382a8c8.png)
4. Dan ini yg akan terjadi
![gambar](https://user-images.githubusercontent.com/32443765/54882056-b888c280-4e88-11e9-9af4-5afc9b9eac05.png)

### Seperti apa yang diharapkan?
Saya blm bisa jawab, dikarenakan saya sendiri belum paham soal javascipt ataupun XSS

### Apa yang terjadi?
Masih bisa menambahkan script xss pd form nama di halaman menu

### Informasi tambahan 
Ini penampakan pd halaman utama [http://belajar.opendesa.id/index.php/first/](http://belajar.opendesa.id/index.php/first/)
![gambar](https://user-images.githubusercontent.com/32443765/54882064-d6eebe00-4e88-11e9-915d-2e466fea2aee.png)

### Tambahan
Dan ini bug pada form Nama Desa
http://belajar.opendesa.id/index.php/hom_desa/konfigurasi
![gambar](https://user-images.githubusercontent.com/32443765/54882310-3cdc4500-4e8b-11e9-8383-f4eee6c1c943.png)
![gambar](https://user-images.githubusercontent.com/32443765/54882323-69905c80-4e8b-11e9-89ae-77792ea63ae2.png)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19.03-pasca
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dicommit ke master
