### ISSUE TITLE
[BUG] [Security] Form Upload Dokumen

### ISSUE THREAD

**Issue by mugi789** [OpenSID/OpenSID#1990]
### Bagaimana alurnya sampai muncul masalah?
1. Login http://belajar.opendesa.id/index.php/siteman
![1l](https://user-images.githubusercontent.com/32443765/55057116-d2015880-509a-11e9-93d7-842956f5c6b4.png)
2. Lalu ke halaman artikel http://belajar.opendesa.id/index.php/web
3. Klik "Tambah Berita Baru" http://belajar.opendesa.id/index.php/web/form/1
![2l](https://user-images.githubusercontent.com/32443765/55057145-e47b9200-509a-11e9-8412-8ffe5a7b49b1.png)
4. Pada form dokumen lampiran lalu pilih file .pdf yg akan diupload
5. Kemudian lakukan tamper data
6. Ubah extensinya yg awalnya .pdf ganti dengan .html
7. Dan ini contoh file yg telah saya upload
[http://belajar.opendesa.id/desa/upload/dokumen/test.html](http://belajar.opendesa.id/desa/upload/dokumen/test.html)
![3l](https://user-images.githubusercontent.com/32443765/55057155-ed6c6380-509a-11e9-8a85-6523e256106d.png)

### Seperti apa yang diharapkan?
Hanya dpt mengunggah file dokumen

### Apa yang terjadi?
Dpt mengunggah file selain file dokumen

### Informasi tambahan 
Selain html, file lain pun bisa masuk, kecuali ext .php

### Update 
Extension .php5 lolos, bisa masuk
http://belajar.opendesa.id/desa/upload/dokumen/x.php5
![gambar](https://user-images.githubusercontent.com/32443765/55057839-efcfbd00-509c-11e9-951f-4db8a5bfe418.png)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19.03-pasca
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
