### ISSUE TITLE
Ukuran poto penduduk perlu diubah dari 100x100 menjadi 200x250

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#1992]
### Bagaimana alurnya sampai muncul masalah?
Ketika upload poto penduduk di menu penduduk kualitas dan ukurannya masih belum sesuai, dimana sekarang ukuran potonya 100x100 px

### Seperti apa yang diharapkan?
Ukuran poto di tambah menjadi ukuran 200x250 seperti gambar dibawah ini
![Screenshot 2019-03-29 00 41 49](https://user-images.githubusercontent.com/25834335/55176177-a033e300-51bb-11e9-88a8-6d7d78053fdf.png)

### Apa yang terjadi?
Kualitas dan ukuran poto kurang pas

### Informasi tambahan 
Saya sudah mencoba untuk merubahnya menjadi 200x250 hasilnya kualitas dan ukuran menjadi pas/ cocok.
Adapun file yang saya rubah disini
![image](https://user-images.githubusercontent.com/25834335/55175702-c6a54e80-51ba-11e9-9413-c168c22ff13d.png)
==> donjo-app/helpers/pict_helper dan perubahnnya saya lampirkan disini
[pict_helper.zip](https://github.com/OpenSID/OpenSID/files/3019158/pict_helper.zip)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by dikisiswanto** [comment]
Bisa lakukan pull request terhadap file yang diubah pak supaya bisa direview dan diterapkan

**Comment by MUHAMMADRANGSEL** [comment]
Saya tdk bisa mas diki

**Comment by MUHAMMADRANGSEL** [comment]
Maklum kurang paham coding

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
