### ISSUE TITLE
Script Code Pada Artikel Mendadak Error

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#1993]
### Bagaimana alurnya sampai muncul masalah?
Sisipkan kolom kode pada sebuah artikel di versi 19.03 tampilan awalnya normal, namun setelah update ke versi 19.04 secara otomatis menampilkan error pada artikel tersebut.

Tampilan Normal versi 19.03:
![IMG_20190401_172852](https://user-images.githubusercontent.com/46939846/55321533-14b09f80-54a4-11e9-97d3-40a799d7e2d4.jpg)

Tampilan Error pada versi 19.04:
![IMG_20190401_172815](https://user-images.githubusercontent.com/46939846/55321552-272ad900-54a4-11e9-976b-8d52d5cc3990.jpg)

### Seperti apa yang diharapkan?
Sesuai dengan posting artikel sebelumnya, walau mencantumkan kode tidak terjadi error.

### Apa yang terjadi?
Seharusnya menampilkan script pada kolom tertentu disebuah artikel.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by ariandii** [comment]
Info tambahan,

Muncul script asing pada tampilan website bagian atas pada artikel tersebut.

Berikut link nya https://natairaya.mtk.web.id/first/artikel/79

![error](https://user-images.githubusercontent.com/46939846/55321747-9a344f80-54a4-11e9-8807-41d870507989.png)

**Comment by eddieridwan** [comment]
@ariandii apakah sudah menyempatkan diri membaca panduan. Coba lihat https://github.com/OpenSID/OpenSID/wiki/Menulis-Artikel bagian _Memasukkan video ke artikel_. Mungkin dapat menolong.

**Comment by ariandii** [comment]
Sukses pak, setelah update ke 19.04 lupa untuk edit config.php nya.

Terima kasih bantuannya, mohon ijin saya close.

**Comment by eddieridwan** [comment]
@ariandii ingat, pada waktu update OpenSID, folder `desa` **JANGAN** diupdate. Folder itu berisi semua file dan ubahan desa.
