### ISSUE TITLE
Penambahan pengaturan hak akses 

### ISSUE THREAD

**Issue by haqi89** [OpenSID/OpenSID#1994]
### Bagaimana alurnya sampai muncul masalah?
1) Pada saat login dengan akses operator pada app muncul banyak menu yang tidak sesuai dengan jobdesk KAUR
2) Pada saat lupa password bingung harus ngapain, 

### Seperti apa yang diharapkan?
1) Adanya pengaturan menu hak akses oleh admin web
contohnya 
![2-0](https://user-images.githubusercontent.com/44763080/55415772-d8f70200-5597-11e9-9170-a3c154f5327e.png)
2) Penambahan fitur lupa/reset password via email

### Apa yang terjadi?
1) Untuk KAUR yang GAPTEK sangat kebingungan dengan tampilan menu diluar jobdesknya
2) Pada saat lupa password, database dihapus dan mulai dari nol lagi

### Informasi tambahan 

| Tanya                   | Jawab
| ----------------     | ---
| Versi OpenSID     | 19.4
| Versi PHP             | 7.3.3
| System operasi    | Windows

**Comment by dikisiswanto** [comment]
coba baca postingan ini https://www.facebook.com/groups/OpenSID/permalink/1189841567847489/
