### ISSUE TITLE
[BUG] Modul GIS

### ISSUE THREAD

**Issue by redjoel** [OpenSID/OpenSID#1996]
### Bagaimana alurnya sampai muncul masalah?
https://demo.opensid.my.id/index.php/gis

### Seperti apa yang diharapkan?
Modul GIS tidak ditampilkan sebagaimana mestinya

### Apa yang terjadi?

Error - 500
### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19.04
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
@redjoel yang error bukan di situ, tetapi di filter dusun di pencarian penduduk di peta. 
Sudah diperbaiki di master, versi pra-rilis. Cek di beta.opensid.my.id.
