### ISSUE TITLE
GantiLink Demo di halaman Github opensid

### ISSUE THREAD

**Issue by andryrukandifauzy** [OpenSID/OpenSID#1997]
![Screenshot_3](https://user-images.githubusercontent.com/42363553/55615452-b5ab9d00-57b9-11e9-9f13-ba609a2a871e.jpg)

### Bagaimana alurnya sampai muncul masalah?

Link demo masih pakai demo.opensid.info
### Seperti apa yang diharapkan?

link baru muncul
### Apa yang terjadi?
demo tidak bisa dibuka oleh new user

### Informasi tambahan 

semua link yang dulu diganti dengan link yang baru
| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
