### ISSUE TITLE
[Bug] Icon bar tidak muncul

### ISSUE THREAD

**Issue by KASWANDI** [OpenSID/OpenSID#1998]
### Bagaimana alurnya sampai muncul masalah?
Beberapa Iconbar tidak muncul setelah upgrade ke versi 19.04

### Seperti apa yang diharapkan?
Iconbar muncul kembali
https://www.facebook.com/groups/OpenSID/permalink/1199062656925380/

### Apa yang terjadi?
Perbaikan bug yang terjadi

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dicommit ke master
