### ISSUE TITLE
Perbaikan bug anggota keluarga dan alamat

### ISSUE THREAD

**Issue by KASWANDI** [OpenSID/OpenSID#1999]
### Bagaimana alurnya sampai muncul masalah?
Daftar anggota keluarga tdk muncul smua, dan pada saat mencetak jga tdk muncul, kolom alamat jga pada daftar keluarga jg tidak muncul

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
@KASWANDI Di http://demo.opensid.my.id dan di http://beta.opensid.my.id tidak bermasalah.

Silakan cek versi anda dan database anda sudah benar. Kalau perlu update ke versi pra-rilis. Kalau masih bermasalah, silakan lampirkan screenshot halaman keluarga, daftar anggota keluarga dan cetak keluarga yg bersangkutan.

**Comment by haqi89** [comment]
Bang @eddieridwan cara edit alamat RT dan RW dimana ya?? udah pake ubah data penduduk tetapi tidak muncul edit RT dan RW?? mohon pencerahannya

**Comment by redjoel** [comment]
maaf ini bukan bug di code
kemungkinan di server lokal bapak sendiri

**Comment by balongbesuk** [comment]
Close issue? Bug tdk ditemukan
