### ISSUE TITLE
Nama Kepala Desa Tidak Tampil Di Cetak Laporan Statistika Kependudukan  

### ISSUE THREAD

**Issue by muhamaddifa** [OpenSID/OpenSID#2000]
### Bagaimana alurnya sampai muncul masalah?
1. Ketika Cetak Laporan  Ttd Kepala Desa Tidak Ada 
2. Nomor Laporan Bermasalah 
![image](https://user-images.githubusercontent.com/38423803/55925605-3d6d2d80-5c38-11e9-9c5a-44b1d4b57689.png)

### Seperti apa yang diharapkan?
1. Menu Cetak Seperti  Laporan Kependuduk Bulanan ,Bisa Memilih Siapa Yang TTD 
2. Lebih Baik Nomor Laporan Di Input Secara Manual : Bisa Input Menu Nya dI Di bawah Ttd Pamong 
![image](https://user-images.githubusercontent.com/38423803/55925742-bf5d5680-5c38-11e9-9ed9-06823b28d90f.png)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR #2001
