### ISSUE TITLE
Versi 19.04 Tiba-Tiba logout sendiri

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#2002]
### Bagaimana alurnya sampai muncul masalah?
Di Versi 19.04 tiba-tiba log out Sendiri dan tampilannya seperti gambar dibawah ini
![image](https://user-images.githubusercontent.com/25834335/56033898-35a4aa80-5d58-11e9-857c-c3ad82051c2a.png)

### Seperti apa yang diharapkan?
Harapanya jangan lagout sendiri

### Apa yang terjadi?
Ketika sedang bekerja tiba-tiba keluar maka pekerjaan itu kita ulang kembali

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Waktu logout default ditentukan oleh Codeigniter di `donjo-app/config/config.php`, selama 7200 detik (yaitu 2jam):
`$config['sess_expiration'] = 7200;` 

Artinya, setelah 2 jam tidak ada aksi yg mengakses server, browsernya akan dilogout. Mengisi tulisan di artikel tidak mengakses server, karena hanya bekerja di browser. Tetapi kalau artikel itu disimpan, aksi itu mengakses server, dan waktu 2 jam di-reset.

Setting in sudah ada sejak awal SID CRI dan bukan sesuatu yang baru.

Tujuan logout ini demi keamanan, supaya kalau browser ditinggal, orang lain yg lewat tidak bisa mengakses tanpa harus login lagi.

Kalau ingin mengubah, setting itu bisa ditambahkan di `desa/config/config.php` dengan nilai lain. Misalnya, 'config['sess_expiration'] = 0;` akan mengakibatkan tidak ada waktu logout.

**Comment by MUHAMMADRANGSEL** [comment]
Yang terjadi disaya,  belum sampai satu jam sdh log out,  dan log out terjadi ketika sdh bekerja

**Comment by afri18** [comment]
Di saya normal, itu offline apa online ???

**Comment by MUHAMMADRANGSEL** [comment]
Online

**Comment by afri18** [comment]
Biasanya gangguan seperti itu karena jaringan tidak stabil, beberapa detik jaringan putus aplikasi langsung log out sendiri, itu pengalaman saya saat jaringan masih belum 3g

**Comment by eddieridwan** [comment]
> Biasanya gangguan seperti itu karena jaringan tidak stabil, beberapa detik jaringan putus aplikasi langsung log out sendiri, itu pengalaman saya saat jaringan masih belum 3g

Ini sangat mungkin. Kalau ada koneksi baru atau IP baru (karena jaringan tidak stabil), akan dilogout otomatis. Dan itu juga demi keamanan. Lebih baik gunakan offline dalam situasi seperti ini.

**Comment by MUHAMMADRANGSEL** [comment]
terima kasih atas informasinya dan issue ini saya tutup

**Comment by pangaribuanantonius** [comment]
untuk php native gimana 

> Waktu logout default ditentukan oleh Codeigniter di `donjo-app/config/config.php`, selama 7200 detik (yaitu 2jam): `$config['sess_expiration'] = 7200;`
> 
> Artinya, setelah 2 jam tidak ada aksi yg mengakses server, browsernya akan dilogout. Mengisi tulisan di artikel tidak mengakses server, karena hanya bekerja di browser. Tetapi kalau artikel itu disimpan, aksi itu mengakses server, dan waktu 2 jam di-reset.
> 
> Setting in sudah ada sejak awal SID CRI dan bukan sesuatu yang baru.
> 
> Tujuan logout ini demi keamanan, supaya kalau browser ditinggal, orang lain yg lewat tidak bisa mengakses tanpa harus login lagi.
> 
> Kalau ingin mengubah, setting itu bisa ditambahkan di `desa/config/config.php` dengan nilai lain. Misalnya, `config['sess_expiration'] = 0;` akan mengakibatkan tidak ada waktu logout.

kalo untuk php native gimana mas ?
mohon pencerahannya
