### ISSUE TITLE
(BUG) timbul karakter garis Horizontal bar (underscore) pada nama dusun

### ISSUE THREAD

**Issue by benioke** [OpenSID/OpenSID#2005]
Bagaimana alurnya sampai muncul masalah?

Jika mengisi nama dusun lebih dari satu kata maka setelah di simpan dan ketika klik ubah data maka muncul seperti ini

Seperti apa yang diharapkan?

Harus nya nama dusun yang lebih dari satu kata bisa di simpan sama dengan data yang di input tanpa ada garis underscore

Apa yang terjadi?
Berpengaruh pada hasil cetak surat dimana nama dusun nya terdapat garis Horizontal bar (underscore)
 Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19.03
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
@benioke harap lampirkan screenshot tampilan masalahnya.

**Comment by benioke** [comment]
Misalkan nama dusun terdiri dari dua kata
Contoh kita buat nama dusun nya LOCCO BARU
Lihat gambar di bawah 
![Capture55 copy](https://user-images.githubusercontent.com/47577404/56100805-b1dfef00-5f0c-11e9-82ab-da5665131531.jpg)

Setelah kita simpan dan waktu kita edit nama dusun nya secara otomatis nama dusun nya ada tanda underscore
Lihat gambar bawah
![Capture66 copy](https://user-images.githubusercontent.com/47577404/56100831-100cd200-5f0d-11e9-92b4-fa5dafc06ae4.jpg)

**Comment by dikisiswanto** [comment]
Bagaimana kalau alamat dusun pada surat saja yang diperbaiki (tanda underscore dihilangkan), pak @benioke ?

**Comment by eddieridwan** [comment]
Sudah diperbaiki di `master`. Dusun yg sudah terlanjur diberi underscore silakan diubah saja.
