### ISSUE TITLE
(Bug)muncul secara otomatis tidak bisa di hapus angka nol (0) pada nomor kitas di data penduduk

### ISSUE THREAD

**Issue by benioke** [OpenSID/OpenSID#2006]
Bagaimana alurnya sampai muncul masalah?
Setelah di input data penduduk, ketika di simpan muncul angka nol secara otomatis di nomor kitas pada biodata penduduk.

Seperti apa yang diharapkan?
Harus nya angka nol (0) di nomor kitas bisa di hilangkan jika belum mengisi nomor kitas.

Apa yang terjadi?
Angka nol otomatis di cetak di cetak kk

![Capture44](https://user-images.githubusercontent.com/47577404/56100986-e654aa80-5f0e-11e9-82c8-221235e9c03e.jpg)

Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19.03
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
