### ISSUE TITLE
perlu ditambahkan Kolom L/P dan Perubahan Format Tanggal Lahir di Data Suplemen

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#2008]
### Bagaimana alurnya sampai muncul masalah?
Di Rincian Data Suplemen perlu ditambahkan Kolom Jenis Kelamin (L/P) dan Perubahan Format Tanggal-BUlan_Tahun Lahir
![Screenshot 2019-04-15 14 38 47](https://user-images.githubusercontent.com/25834335/56112285-222e5500-5f8d-11e9-857c-e4cd697e2cf9.png)

### Seperti apa yang diharapkan?
Ada Kolom Jenis Kelamin dan Tanggal Bulan Tahun Lahir dengan format DD-MM-YYY

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by MUHAMMADRANGSEL** [comment]
Mantap ini,  saya suka

Pada tanggal Sen, 15 Apr 2019 22.43, I Kadek Galiarta <
notifications@github.com> menulis:

**Comment by MUHAMMADRANGSEL** [comment]
Tinggal penambahan kolom jenis kelamin saja

Pada tanggal Sel, 16 Apr 2019 01.55, MUHAMMAD SPD <muhammadrangsel@gmail.com>
menulis:

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR #2012
