### ISSUE TITLE
Penambahan Keterangan di Widget Statistik

### ISSUE THREAD

**Issue by Galiarta** [OpenSID/OpenSID#2010]
Penamabahan Keterangan di Widget Statistik Penduduk

### Bagaimana alurnya sampai muncul masalah?
Di Widget statistik penduduk, keterangan jumlah dan jenis kelamin penduduk tidak kelihatan secara langsung. Hanya akan kelihatan ketika mouse over.
![image](https://user-images.githubusercontent.com/33612251/56137030-86b9d600-5fc6-11e9-98a6-ff0564e19d4a.png)

### Seperti apa yang diharapkan?
Kelihatan Detail jenis kelamin dan atau jumlah penduduk sesuai jenis kelamin dan totalnya.
![image](https://user-images.githubusercontent.com/33612251/56137092-a6e99500-5fc6-11e9-99f6-4ade49a5874d.png)

### Informasi tambahan 
Saya mencoba membuat perubahan di folder view>widget>statistik. Di thema batudaa desktop, dan hadakewa mobile sudah seperti harapan, namun di batudaa mobile dan hadakewa desktop tampilannya seperti ini :
![image](https://user-images.githubusercontent.com/33612251/56137266-02b41e00-5fc7-11e9-8d8f-2de5fd9438e0.png)

File yang saya edit:

[statistik.zip](https://github.com/OpenSID/OpenSID/files/3080391/statistik.zip)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19.03 pasca
| Versi PHP        | 7
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR #2012
