### ISSUE TITLE
tidak bisa menambahkan data keluaraga

### ISSUE THREAD

**Issue by KASWANDI** [OpenSID/OpenSID#2011]
### Bagaimana alurnya sampai muncul masalah?
Pada saat menambahkan data keluarga / KK baru from meminta data RW dan RT jika mengklik tombol simpan padahal beberapa desa tidak dilengkapi RT atau RW

### Seperti apa yang diharapkan?
Penyesuaian menu pilihan untuk desa yang tak punya RT/RW

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
@KASWANDI , apabila dusun tidak memiliki RW atau RT, anda tetap dapat menambah KK baru atau anggota keluarga baru, dengan memilih pilihan RW dan RT '-'. Pilihan ini otomatis dibuat untuk setiap dusun sengaja untuk kasus anda.

Apabila info ini tidak ada di panduan, silakan anda ikut membantu melengkapi panduan di https://github.com/OpenSID/OpenSID/wiki/Keluarga.

![tidak-ada-rwrt](https://user-images.githubusercontent.com/249563/56279865-44220600-614c-11e9-861b-f12ca57b4df3.jpg)

![dusun-tidak-ada-rwrt](https://user-images.githubusercontent.com/249563/56279975-919e7300-614c-11e9-82a5-d17290b4a0c9.jpg)

**Comment by eddieridwan** [comment]
Karena masalah ini tidak memerlukan perubahan script, issue ini kami tutup.

**Comment by MUHAMMADRANGSEL** [comment]
![image](https://user-images.githubusercontent.com/25834335/56422829-018f3380-62dc-11e9-94b5-9b58a942e204.png)
saya bermaslah waktu menambahkan KK baru tidak muncul RW dan RT nya

**Comment by eddieridwan** [comment]
@MUHAMMADRANGSEL apakah sudah dicoba menggunakan versi pra-rilis? 
Bisa coba di beta.opensid.my.id.

**Comment by MUHAMMADRANGSEL** [comment]
Bisa

Pada tanggal Sab, 20 Apr 2019 10.40, Eddie Ridwan <notifications@github.com>
menulis:
