### ISSUE TITLE
Tambah Tag ID Card eKTP

### ISSUE THREAD

**Issue by hasap86** [OpenSID/OpenSID#2016]
![DSC_0519](https://user-images.githubusercontent.com/45263721/56449285-6e88e480-6341-11e9-818f-94309c8e29e9.JPG)

### Bagaimana alurnya sampai muncul masalah?
Setiap kartu ID eKTP memiliki Tag Chip yg berisi angka yang bisa dibaca menggunakan IC Card Reader.

### Seperti apa yang diharapkan?
adanya penambahan isian **Nomor Tag ID Card** di data penduduk pada **Status Kepemilikan KTP**, data isian nomor Tag ID Card ini kemudian digunakan untuk pencarian data penduduk di Layanan Cetak Surat dan pencarian penduduk lainnya menggunakan IC Card Reader untuk membaca tag eKTP yg dimiliki warga.

![penambahan-tag-id-eKTP](https://user-images.githubusercontent.com/45263721/56449344-ff5fc000-6341-11e9-9801-aeedb0035e46.jpg)

### Apa yang terjadi?
Proses pencarian data lebih cepat tanpa mengetik nama atau nomer ktp, hanya melakukan scan eKTP, sehingga proses pelayanan desa lebih cepat baik untuk pencarian data maupun untuk Layanan Cetak Surat, terhindar dari data nama sama.

![scan-tag-id-card](https://user-images.githubusercontent.com/45263721/56449353-19010780-6342-11e9-85a0-2bede0906f40.jpg)

### Informasi tambahan 
Alat Scan eKTP Reader ini dijual seharga kisaran 750rb

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19.04 Demo
| Versi PHP        | 
| System operasi   |

**Comment by haqi89** [comment]
cara mendapatkan Tag ID card dimana pak??

**Comment by hasap86** [comment]
> cara mendapatkan Tag ID card dimana pak??

pake alat Reader ini
![_20190420_121801](https://user-images.githubusercontent.com/45263721/56453089-7dce5900-6366-11e9-876d-e0d63eaf07fa.JPG)

**Comment by eddieridwan** [comment]
@hasap86 : Apakah IC Card Reader dapat membaca data lain di eKTP selain dari Nomor Tag ID Card it sendiri? Yaitu, apakah ada data lain yg juga terrekam di kartu eKTP?

**Comment by eddieridwan** [comment]
https://blog.compactbyte.com/2018/06/10/membedah-e-ktp/

Apakah ada eKTP reader resmi yg boleh digunakan desa, yang dapat membaca seluruh data yg ada di eKTP? 

https://www.len.co.id/e-ktp-reader-pembaca-ktp-elektronik/
https://teknologi.bisnis.com/read/20150122/84/394121/e-ktp-bppt-ciptakan-alat-lebih-praktis-ketimbang-card-reader

**Comment by hasap86** [comment]
> @hasap86 : Apakah IC Card Reader dapat membaca data lain di eKTP selain dari Nomor Tag ID Card itu sendiri? Yaitu, apakah ada data lain yg juga terrekam di kartu eKTP?

Hanya membaca nomor id tag saja

**Comment by hasap86** [comment]
> https://blog.compactbyte.com/2018/06/10/membedah-e-ktp/
> 
> Apakah ada eKTP reader resmi yg boleh digunakan desa, yang dapat membaca seluruh data yg ada di eKTP?
> 
> https://www.len.co.id/e-ktp-reader-pembaca-ktp-elektronik/
> https://teknologi.bisnis.com/read/20150122/84/394121/e-ktp-bppt-ciptakan-alat-lebih-praktis-ketimbang-card-reader
> http://printerkartu.com/reader-e-ktp-lencrd-ektp01/
> https://penanegeri.com/kemendagri-dorong-gunakan-card-reader-untuk-deteksi-keaslian-ktp-elektronik/2951/
> http://www.aureajaya.com/dual-i-de620-ektp-.html
> http://www.globalmegah.co.id/

Untukndesa tidak ada, hanya ada utk dukcapil, pernah tanya tapi harus sebagai instansi dukcapil, adapun yg versi yg koneksi ke dukcapil harganya sangat mahal dan tidak bisa dimanfaatkan untuk OpenSID

**Comment by eddieridwan** [comment]
@hasap86 , ketiga alat ini sepertinya boleh untuk umum?

1. http://printerkartu.com/reader-e-ktp-lencrd-ektp01/
2. http://www.aureajaya.com/dual-i-de620-ektp-.html
3. http://www.globalmegah.co.id/

**Comment by eddieridwan** [comment]
Disdukcapil Yogya membagikan eKTP reader kepada kelurahan: https://nusantara.medcom.id/jawa-tengah/peristiwa-jateng/GNGMAZzk-disdukcapil-kota-yogyakarta-beli-50-card-reader-untuk-ktp-el

**Comment by hasap86** [comment]
> @hasap86 , alat2 berikut ini sepertinya boleh untuk umum?
> 
> 1. http://printerkartu.com/reader-e-ktp-lencrd-ektp01/
> 2. http://www.aureajaya.com/dual-i-de620-ektp-.html
> 3. http://www.globalmegah.co.id/
> 4. http://www.inti.co.id/index.php/id/2015-06-18-06-16-48/infrastruktur/e-ktp-reader
> 5. https://www.jualo.com/elektronik-lainnya/iklan-alat-pembaca-ktp-ktp-el-e-ktp-mesin-pembaca-ktp-reader-ktp. Yang ini dijual di dengan harga Rp8.800.000 di https://shopee.co.id/Reader-KTP-Alat-Pembaca-e-KTP-Mesin-Pembaca-KTP-el-i.22116921.253771905

Mahal mahal, yg saya tes seharga 750rb

**Comment by hasap86** [comment]
> Disdukcapil Yogya membagikan eKTP reader kepada kelurahan: https://nusantara.medcom.id/jawa-tengah/peristiwa-jateng/GNGMAZzk-disdukcapil-kota-yogyakarta-beli-50-card-reader-untuk-ktp-el

Yg terpenting OpenSID kita siapin dulu inputan nomor tagnya, supaya bisa digunakan pelayanan menggunakan card reader, apapun jenisnya dan bagaimanapin cara mendapatkannya ya

**Comment by eddieridwan** [comment]
> > Disdukcapil Yogya membagikan eKTP reader kepada kelurahan: https://nusantara.medcom.id/jawa-tengah/peristiwa-jateng/GNGMAZzk-disdukcapil-kota-yogyakarta-beli-50-card-reader-untuk-ktp-el
> 
> Yg terpenting OpenSID kita siapin dulu inputan nomor tagnya, supaya bisa digunakan pelayanan menggunakan card reader, apapun jenisnya dan bagaimanapin cara mendapatkannya ya

Kalau menggunakan eKTP reader lengkap, tidak perlu menambah kolom nomor tag, dan juga bisa periksa keabsahan kartu eKTPnya. Alat yg hanya membaca nomor tag tidak bisa verifikasi kartu itu sendiri, karena hanya membaca id dari kartunya sendiri (yg bisa sembarang).

**Comment by hasap86** [comment]
> > > Disdukcapil Yogya membagikan eKTP reader kepada kelurahan: https://nusantara.medcom.id/jawa-tengah/peristiwa-jateng/GNGMAZzk-disdukcapil-kota-yogyakarta-beli-50-card-reader-untuk-ktp-el
> > 
> > 
> > Yg terpenting OpenSID kita siapin dulu inputan nomor tagnya, supaya bisa digunakan pelayanan menggunakan card reader, apapun jenisnya dan bagaimanapin cara mendapatkannya ya
> 
> Kalau menggunakan eKTP reader lengkap, tidak perlu menambah kolom nomor tag, dan juga bisa periksa keabsahan kartu eKTPnya. Alat yg hanya membaca nomor tag tidak bisa verifikasi kartu itu sendiri, karena hanya membaca id dari kartunya sendiri (yg bisa sembarang).

Kembali lagi ke fungsinya, issue ini untuk mempercepat pencarian data menggunakan fasilitas tag eKTP yg sudah dimiliki warga, kalo harus konek ke dukcapil opensid gak berfugsi, kan data di opensid desa kita sepakati adalah data paling ter update

**Comment by eddieridwan** [comment]
Sepertinya eKTP reader tidak harus tersambung ke Disdukcapil. Datanya terekam di kartunya sendiri. Tujuan menggunakan eKTP reader bukan untuk mengupdate database OpenSID, tetapi sebagai bukti identitas seseorang yg memerlukan layanan dengan membawa kartu bukti diri (dan tentunya juga untuk mempercepat pencarian data melalui NIK yg terbaca dari eKTP).

Tetapi sebagai langkah sementara, kita bisa tambahkan kolom nomor tag eKTP dan menggunakan RFID reader biasa, tetapi itu bukan merupakan solusi yg ideal.

**Comment by hasap86** [comment]
> Sepertinya eKTP reader tidak harus tersambung ke Disdukcapil. Datanya terekam di kartunya sendiri (lihat https://blog.compactbyte.com/2018/06/10/membedah-e-ktp/). Tujuan menggunakan eKTP reader bukan untuk mengupdate database OpenSID, tetapi sebagai bukti identitas seseorang yg memerlukan layanan dengan membawa kartu bukti diri (dan tentunya juga untuk mempercepat pencarian data melalui NIK yg terbaca dari eKTP).
> 
> Tetapi sebagai langkah sementara, kita bisa tambahkan kolom nomor tag eKTP dan menggunakan RFID reader biasa, tetapi itu bukan merupakan solusi yg ideal.

Siap,

**Comment by eddieridwan** [comment]
@hasap86 , panjang Nomor Tag ID Card berapa digit?  Nama kolom di tabel enaknya apa?

**Comment by hasap86** [comment]
Buat aja minimal 10 digit maksimal 15, alat yg saya gunakan membaca 10digit ini 3928913668, namanya Tag ID Card juga boleh kali ya

**Comment by eddieridwan** [comment]
Penambahan kolom tag_id_card sudah dicommit ke master. Tapi belum terkoneksi langsung dengan NFC/RFID reader. Buat issue baru untuk koneksi langsung, termasuk untuk eKTP reader.

**Comment by hasap86** [comment]
Sudah ditambahkan pencarian berdasarkan id tag di pencarian penduduk dan cetak surat?

**Comment by eddieridwan** [comment]
Sudah, silakan dites.
