### ISSUE TITLE
Asuransi Kesehatan

### ISSUE THREAD

**Issue by afri18** [OpenSID/OpenSID#2020]
tambahkan fitur "Kepemilikan Asuransi Kesehatan di menu Kesehatan di Biodata Penduduk agar mudah mengetahui penduduk yang belum nasuk Asuransi Kesehatan
![image](https://user-images.githubusercontent.com/6611881/56452683-2cba6700-635e-11e9-92f6-e5aa7b3d3d2c.png)

### Bagaimana alurnya sampai muncul masalah?
tidak bisa mengetahui apakah penduduk punya Askes atau tidak

### Seperti apa yang diharapkan?
Agar Pemerintahan Desa tau kepemilikan Asuransi Kesehatan

### Apa yang terjadi?
Saat pertolongan tidak tau penduduk ada di Asuransi aau tidak

### Informasi tambahan 
Cepat dalam tidakan pertolongan kesehatan
| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by junandia** [comment]
Askes sekarang kan bpjs kesehatan?
![gambar](https://user-images.githubusercontent.com/10545975/62993556-f01cf900-be81-11e9-9238-019d0bef2bf5.png)
apakah seperti ini?

**Comment by afri18** [comment]
Jangan no BPJS, tapi jenis asuransi kesehatan, bisa BPJS BPI , BPJS mandiri atau asuransi kesehatan lainnya

**Comment by junandia** [comment]
![gambar](https://user-images.githubusercontent.com/10545975/63227570-f8728c80-c211-11e9-8497-0b45a6785996.png)

seperti ini pak @afri18 ?

**Comment by afri18** [comment]
Betuullll , kalau bisa tambah nama asuransi bisa juga manual takut nggak ada, BPJS kesehatan ada dua, satu mandiri yg satunya, pbi ( penerima bantuan iuran) jadi tau warga penerima bantuan BPJS kesehatan , mantaaab banget ini ....

**Comment by junandia** [comment]
Bisa kok tambah manual, soalnya ini ambil data asuransinya dari database.

Pada tanggal Sen, 19 Agt 2019 06.33, Syafri <notifications@github.com>
menulis:

**Comment by afri18** [comment]
Okeh kalau begitu, mantaaab , bisa input warga yg punya Askes, dan makin kompliit opensid , 
TOP

**Comment by eddieridwan** [comment]
Terima kasih pada @junandia yang telah mengirim PR #2211. 

Solusi bung Junandia untuk daftar kode asuransi berbeda dengan penanganan daftar kode yg lain, seperti pekerjaan, pendidikan, cara KB, dstnya. PR #2211 menyediakan daftar dan form supaya desa bisa mengubah daftar kode asuransi sendiri. Sehingga nantinya masing2 desa bisa memiliki daftar asuransi yang berbeda.

Pada tabel kode yg ada saat ini, semuanya dibakukan -- dalam arti pengguna tidak diberi akses untuk mengubahnya. Jadi semua pengguna OpenSID menggunakan kode yg sama, misalnya untuk agama atau cara KB. keuntungannya, statistik antar desa bisa dibandingkan dan proses ekspor/impor bisa konsisten. Tapi untuk mengubahnya perlu dilakukan melalui rilis OpenSID.

Apakah daftar asuransi berbeda? Apakah ok kalau dikelola oleh desa masing2? Apakah nanti ada kebutuhan untuk membuat statistik (misalnya di dashboard kecamatan OpenDK) antar desa terkait asuransi? Ok, pertanyaan ini perlu dilempar ke forum pengguna di https://www.facebook.com/groups/OpenSID/.

![daftar-asuransi](https://user-images.githubusercontent.com/249563/63660678-d4f3a700-c7fa-11e9-8f5f-37dea19ace92.jpg)

**Comment by eddieridwan** [comment]
Telah dicommit ke master melalui PR #2211, sbb:

1. Kode asuransi dibatasi BPJS saja dan 'Asuransi Lainnya'
2. Untuk asuransi lainnya, pengguna bisa mencatat nama dan nomor asuransi, tetapi tidak dimasukkan ke tabel kode asuransi.

Alasan pendekatan ini:
- untuk statistik dan pelaporan, yg diperlukan apakah ada askes dan jenis BPJS mana yg diambil. 
- asuransi jenis lain hanya sebagai info saja, dan jenis ini banyak dan bisa berubah-ubah
