### ISSUE TITLE
Tampilan di form tambah penduduk ada yang ganjil

### ISSUE THREAD

**Issue by dikisiswanto** [OpenSID/OpenSID#2021]
### Bagaimana alurnya sampai muncul masalah?
* Buka menu *Kependudukan > Penduduk*
* Tambah Penduduk Domisili
* Perhatikan *form* pada bagian Status Kepemilikan KTP 

### Seperti apa yang diharapkan?
Tampilan diperbaiki

### Apa yang terjadi?
Ada paging dalam form

### Informasi tambahan 

Screenshots
![image823](https://user-images.githubusercontent.com/22239074/56452762-3ba61700-6368-11e9-8748-e73ff20608f2.png)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    |  19.04-pasca
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah diperbaiki di pra-rilis

**Comment by hasap86** [comment]
ini terjadi juga saat ubah data penduduk, sudah saya buatkan issuenya di #2022
