### ISSUE TITLE
Tampilan Ubah Data Penduduk Aneh / Tidak Sesuai

### ISSUE THREAD

**Issue by hasap86** [OpenSID/OpenSID#2022]
![ubah-data-penduduk](https://user-images.githubusercontent.com/45263721/56462556-3f30b100-63ef-11e9-8cac-b6160e849455.jpg)

### Bagaimana alurnya sampai muncul masalah?
ketika Ubah Data Penduduk ada tampilan yang tidak sesuai, adanya pilihan jumlah tampilan dan paging

### Seperti apa yang diharapkan?

seharusnya tidak ada
### Apa yang terjadi?
jadi tidak sesuai

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | Demo
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah diperbaiki di master.
