### ISSUE TITLE
Status kawin di detail tidak sama dengan inputan di ubah data penduduk

### ISSUE THREAD

**Issue by haqi89** [OpenSID/OpenSID#2028]
### Bagaimana alurnya sampai muncul masalah?
Pada kolom **status kawin** di detail data penduduk muncul **KAWIN TIDAK TERCATAT** sedangkan diubah data penduduk pilihannya hanya : **BELUM KAWIN, KAWIN, CERAI HIDUP, CERAI MATI**

### Seperti apa yang diharapkan?
Seharusnya pada menu **detail data penduduk** pada kolom **STATUS KAWIN** menampilkan status yang sama sesuai pilihan pada **UBAH DATA PENDUDUK** 

### Informasi tambahan 
![BG 1](https://user-images.githubusercontent.com/44763080/56772491-6b2fa600-67e4-11e9-8272-8c35c9c1d980.jpg)
![BG 2](https://user-images.githubusercontent.com/44763080/56772492-6b2fa600-67e4-11e9-893e-4435869151b5.jpg)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
@haqi89 silakan simak pembahasan di https://github.com/OpenSID/OpenSID/issues/1673.

Kawin tercatat/tidak tercatat tergantung diisi tidaknya no. akta perkawinan.
Silakan anda bantu memperbaiki/melengkapi panduan pengisian data penduduk di https://github.com/OpenSID/OpenSID/wiki/Pengisian-Data-Penduduk.

Memang seluruh panduan perlu dirombak/disesuaikan. Tanpa bantuan teman2, tidak mungkin bisa terlaksana.

Issue ini saya tutup. Silakan buka kembali kalau masih ada yg perlu diperbaiki.
