### ISSUE TITLE
Penambahan QR Code pada Surat

### ISSUE THREAD

**Issue by Gunturwijay** [OpenSID/OpenSID#2029]
### Setiap Surat yang dibuat oleh sistem tertera kode Barcodenya?

![image](https://user-images.githubusercontent.com/40741591/56827009-cbc3ef00-6887-11e9-93c3-80827327714d.png)

### di harapkan dapat di akses seperti ini dan surat dapat di download kembali
![image](https://user-images.githubusercontent.com/40741591/56826909-8f908e80-6887-11e9-8139-a09ca4d2a9f3.png)

 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by KASWANDI** [comment]
Saya sangat setuju dengan penambahan fitur barcode pada surat untuk memastikan keaslian surat, apalagi disiskeudes versi 2.0 kuitansinya sdh ada barcodenya

**Comment by KASWANDI** [comment]
@eddieridwan Mas apakah ini bsa jdi prioritas?

**Comment by eddieridwan** [comment]
@fusionid @afa28 @af-lazuardi : solusi untuk dipertimbangkan:
1. Isi QR Code untuk surat dapat ditentukan pengguna melalui setting di Layanan Surat > Pengaturan Surat. Setting itu bisa menyisipkan data surat terbatas seperti judul surat, nomor surat, nama pemohon dsbnya. Mungkin bisa gunakan kode sisipan bagi setiap data yg boleh disisipkan.
2. Sediakan kode_isian [qr_code] yg ditambahkan di template rtf surat yg memerlukan. Pada saat mencetak surat, kode_isian itu diganti dengan QR Code secara otomatis

**Comment by afa28** [comment]
Mas @agungsugiarto, ini sudah ada di versi premium terbaru.

**Comment by agungsugiarto** [comment]
@Gunturwijay, issue ini saya tutup karena di versi terbaru sudah disediakan fitur qrcode untuk surat. Terimakasih
