### ISSUE TITLE
Menu aksi pada halaman admin tidak beraturan

### ISSUE THREAD

**Issue by sukrimalendra** [OpenSID/OpenSID#2030]
### Bagaimana alurnya sampai muncul masalah?
- menu aksi pada halaman admin tidak beraturan.

### Seperti apa yang diharapkan?
![aksi2](https://user-images.githubusercontent.com/30992964/57002811-54c28980-6bec-11e9-9890-3808869123a7.PNG)
![aksi3](https://user-images.githubusercontent.com/30992964/57002812-54c28980-6bec-11e9-8e75-a3d83ce40e9f.PNG)

### Apa yang terjadi?
![aksi](https://user-images.githubusercontent.com/30992964/57002815-5f7d1e80-6bec-11e9-8bc7-351559bb2ec9.PNG)
![aksi1](https://user-images.githubusercontent.com/30992964/57002816-6015b500-6bec-11e9-9aa8-d4aa79ff2e0c.PNG)

### Informasi tambahan 
-terjadi pada OpenSID V.19.05

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
@sukrimalendra , lihat pembahasan di https://www.facebook.com/groups/OpenSID/permalink/1212140288950950/?hc_location=ufi

Saya akan tutup issue ini. Silakan buka kembali kalau masih bermasalah.
