### ISSUE TITLE
TAMBAHKAN HALAMAN KATEGORI

### ISSUE THREAD

**Issue by doubble46** [OpenSID/OpenSID#2032]
Dengan semakin banyaknya data, informasi yang ditampilkan oleh website opensid dan juga semakin banyak tema-tema website desa opensid yang mulai dibangun, apakah tidak sebaiknya dibuatkan akses untuk menampilkan KATEGORI 
Fitur yang diharapkan : 
1. Kategori tidak diload pada halaman depan website tetapi ditampilkan pada halaman kategori.

2. Pada saat pembuatan KATEGORI di pengaturan Web tambahkan pilihan halaman kategori apakah ingin ditampilkan setandar (kategori.php) atau membuat halaman kategori baru (nama-kategori.php).

**Comment by afa28** [comment]
Mohon di perjelas dan buat issue baru.
