### ISSUE TITLE
Modul : Absensi Pengurus

### ISSUE THREAD

**Issue by redjoel** [OpenSID/OpenSID#2033]
### Bagaimana alurnya sampai muncul masalah?
Opensid Selain menampilkan Data data Desa, juga menampilkan data data pengurus kampung, sehingga, data data  seperti kehadiran pengurus di kantor bisa bukan diawasi tapi dimonitor oleh warga.

### Seperti apa yang diharapkan?
Bisa dalam bentuk form Isian, atau toggled button yang juga bisa ditampilkan di front line mirip ketika kita berkunjung ke kantor kantor tertentu yang menampilkan Ada atau tidak adanya Pejabat yang berwenng di kantor

### Apa yang terjadi?
Saat ini belum di implementasikan

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19.05
| Versi PHP        | 5.6
| System operasi   | Windows 7

**Comment by KASWANDI** [comment]
Bagus jika diterapkan di mene sekretariatan jdi bsa memantau absen kehadiran aparat desanya, apalagi bsa disingkronkan dngan pemindai sidik jari pada ceklok

**Comment by Ferrobae** [comment]
Sip lah usulan sy #4085 ditutup krna sudah ada yg mendahului

Cuma ada detail pengalaman krna sudah pernah pake absen online by aplikasi semoga bisa sama

Jd metode Web Cam untuk selfie kehadiran pagi dibatasi jam kerja jika lewat bisa terlambat baru alpa
Pas absen pulang dimulai sampe tengah malam

Jg sinkron dengan e kinerja yg di acc atasan sehingga untuk riwayat pekerjaan tiap bulan bisa tercetak jika sedang dinas luar bisa Surat Perintah Perjalanan terbit secara online jg


Semoga menjadi prioritas pada update v21. 05

**Comment by Fajar-blackdeath** [comment]
Apa kekurangan yg ingin diatasi?
ingin menmbahkan fitur layanan absen untuk aparatur desa

Beri keterangan singkat dan jelas mengapa fitur ini diperlukan.
fitur ini diperlukan untuk mengetahui kinerja dari para aparatur dilihat dari kedisplinan aparatur desa. sehingga dapat menjadi acuan untuk kinerja aparatur desa.

Jelaskan solusi yg diinginkan
mohon dibuatkan layanan absen aparatur agar terlihat kedisplinan aparatur

Apakah ada alternatif lain
absen bia mengunakan rfid ataupun sidikjari tergantung kemudahan kita. bila ada alat yang lebih murah itu lebih bagus.

Beri keterangan singkat dan jelas solusi lain yg telah anda pertimbangkan untuk kebutuhan ini.
saat ini banyak aparatur desa yang tidak bekerja sesuai dengan tupoksi masing masing dan masih banyak aparatur yang melalikan tugasnya sehingga pelayanan di kantor desa terkadang tersendat akibat keterlambatan aparatur.

Untuk versi OpenSID mana
premium @
Fitur ini diusulkan untuk versi Rilis Umum (mis. v21.03) atau Rilis Premium (mis v21.03-premium) yg mana?
21.04

Informasi tambahan
mohon ini di utamakan
Beri informasi lainnya yg dapat membantu menjelaskan permintaan ini.
-->
layanan absen aparatur deesaaa[](url)
[penggunan rfid atau finger print.docx](https://github.com/OpenSID/OpenSID/files/6237563/penggunan.rfid.atau.finger.print.docx)
[absen format.xlsx](https://github.com/OpenSID/OpenSID/files/6237565/absen.format.xlsx)

**Comment by eddieridwan** [comment]
Versi terbatas issue ini, khusus untuk kehadiran desa sebagai informasi bagi warga, ada di issue Kehadiran Perangkat Desa #4323

**Comment by Fajar-blackdeath** [comment]
Semangat pak

Pada tanggal Sab, 26 Mar 2022 09.42, Andi Fahruddin Akas <
***@***.***> menulis:
