### ISSUE TITLE
(BUG) pada biodata penduduk kolom Kelahiran Anak ke tampil sebagai '0' jika kosong.

### ISSUE THREAD

**Issue by benioke** [OpenSID/OpenSID#2034]
Bagaimana alurnya sampai muncul masalah?

Bug nya hampir sama seperti issue #2006 yang sudah diperbaiki di opensid ver 19.05. Sekarang pada Kolom Kelahiran Anak ke menampilkan '0' jika masih kosong
![IMG_20190501_211502](https://user-images.githubusercontent.com/47577404/57074194-65b6ec00-6d0d-11e9-8ddc-93b0c0dc4872.jpg)

Seperti apa yang diharapkan?
Harus nya tidak tampil '0' karna masih kosong
![LAHIR 2 copy](https://user-images.githubusercontent.com/47577404/57074238-82ebba80-6d0d-11e9-8a5a-c4b4dbd94633.jpg)

Apa yang terjadi?
Angka '0' muncul otomatis dan tidak bisa dihapus

Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19.05
| Versi PHP        | 
| System operasi   |

**Comment by Galiarta** [comment]
Bisa dicoba ditambahkan 
`if ($data['kelahiran_anak_ke'] == '') $data['kelahiran_anak_ke'] = NULL;` di penduduk model dan
 setting kelahiran_anak_ke menjadi NULL defaultnya di database. 

@eddieridwan benar seperti itu pak?

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR #2035
