### ISSUE TITLE
BUG -- Input Data Suplemen

### ISSUE THREAD

**Issue by redjoel** [OpenSID/OpenSID#2036]
### Bagaimana alurnya sampai muncul masalah?
Ketika mencoba menambah Warga dalam data SUplemen
http://demo.opensid.my.id/index.php/suplemen/form_terdata/2

### Seperti apa yang diharapkan?
Data Warga bisa diambil dan dimasukkan kedalam suplemen

### Apa yang terjadi?
Error 500
Error Number: 1064

You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 4

SELECT `p`.`id` as `id`, `p`.`nik` as `nik`, `p`.`nama`, `w`.`rt`, `w`.`rw`, `w`.`dusun` FROM `tweb_penduduk` `p` LEFT JOIN `tweb_wil_clusterdesa` `w` ON `w`.`id` = `p`.`id_cluster` WHERE `p`.`id` NOT IN ()

Filename: models/Suplemen_model.php

Line Number: 98

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19.05
| Versi PHP        | 7
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
