### ISSUE TITLE
[Bug] Pengguna operator tidak bisa memilih Dusun/RW/RT di form isian KK baru

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#2040]
### Bagaimana alurnya sampai muncul masalah?
Pada waktu input Kepala Keluarga Baru dengan status pengguna Operator tidak bisa, pada waktu memilih RW KK dan RT KK
![image](https://user-images.githubusercontent.com/25834335/57173180-45e30d80-6e5e-11e9-8a4f-232f579dc3d0.png)

### Seperti apa yang diharapkan?
Status Pengguna Operator bisa menambahkan KK Baru

### Apa yang terjadi?
Harus Login sebagai Admin sajabaru bisa menambahkan KK baru

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
