### ISSUE TITLE
Daftar keluarga perlu bisa diurut berdasarkan tanggal terdaftar

### ISSUE THREAD

**Issue by benioke** [OpenSID/OpenSID#2041]
Bagaimana alurnya sampai muncul masalah?
Setelah melakukan upgrade ke versi 19.05. Pada menu keluarga Menampilkan tanggal terdaftar yang tidak beraturan/tanggal nya acak.
Versi 19.03.Sebelum di upgrade ke ver 19.05
![IMG_20190507_174314](https://user-images.githubusercontent.com/47577404/57294279-50690580-70f1-11e9-929f-1c3c5ef1c7fe.JPG)

Setelah di upgrade dan migrasi ke versi 19.05 
![IMG_20190507_174359](https://user-images.githubusercontent.com/47577404/57294339-7f7f7700-70f1-11e9-9a68-90abe2ac7339.JPG)

Seperti apa yang diharapkan?
Harus nya tanggal terdaftar pada KK tampil secara berurutan seperti versi sebelumnya tidak menampilkan tanggal secara acak

Apa yang terjadi?
Menyebabkan tampilan tanggal nya kurang rapi.

Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19.05
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
@benioke ini bukan bug. Sekarang daftar keluarga secara default diurut menurut nomor KK. Issue ini diubah menjadi permintaan agar daftar keluarga juga bisa diurut berdasarkan tanggal terdaftar.

**Comment by benioke** [comment]
Oke pak eddie..

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
