### ISSUE TITLE
[Bug] menambah anggota baru hasil input tgll/bln/tahun lahir salah

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#2042]
### Bagaimana alurnya sampai muncul masalah?
ketika input data kk baru atau menambah anggota keluarga baru dan setelah disimpan tanggal/bulan/tahun lahir yang tersimpan beda dengan hasil yang diinput

### Seperti apa yang diharapkan?
Tanggal/Bulan/tahun lahir yang diinput sama dengan yang disimpan

### Apa yang terjadi?
Data yang tersimpan salah dan harus diedit kembali

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19.05
| Versi PHP        | 
| System operasi   |

**Comment by MUHAMMADRANGSEL** [comment]
issue ini perlu penanganan segera, supaya tdk perlu di edit

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
