### ISSUE TITLE
Tambah Menu Ubah Kepala Desa menjadi Wali Nagari

### ISSUE THREAD

**Issue by mr703** [OpenSID/OpenSID#2043]
### Bagaimana alurnya sampai muncul masalah?

Di Sumatera Barat, Pemerintahan Desa dinamakan dengan Pemerintahan Nagari yang di Kepalai Oleh Wali Nagari.
### Seperti apa yang diharapkan?

Sebutan Kepala Desa di Ubah Menjadi Wali Nagari khusus untuk sumatera barat
### Apa yang terjadi?

Ketika cetak surat muncul Kepala Desa , Seharusnya Wali Nagari.
### Informasi tambahan 
Mohon ada penambahan menu ubah kepala desa menjadi wali nagari

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
@mr703 harap jelaskan surat mana yg dimaksud. Semua surat Ekspor Dok sudah otomatis mengambil jabatan dari daftar Pemerintahan Desa. Di situ, pengisian jabatan sepenuhnya tergantung desa.

Kalau yg dimaksud surat Cetak (langsung), rilis OpenSID tidak akan mengembangkan lebih lanjut. Seperti dijelaskan di https://github.com/OpenSID/OpenSID/wiki/Panduan-Mencetak-Surat, kami anjurkan semua desa menggunakan surat Ekspor Dok saja.

**Comment by mr703** [comment]
Mohon Petunjuk Untuk Robah Coding Kepala Desa menjadi Wali Nagari

Pada tanggal Kam, 9 Mei 2019 09.35, Eddie Ridwan <notifications@github.com>
menulis:

**Comment by eddieridwan** [comment]
@mr703 maksudnya untuk surat Cetak (langsung)?

**Comment by mr703** [comment]
Iya Mas Eddie,
Di Surat-Surat dan di Aplikasi.

Diharapkan : Kata2 Kepala Desa di ubah menjadi Wali Nagari

Pada tanggal Kam, 9 Mei 2019 09.40, Eddie Ridwan <notifications@github.com>
menulis:

**Comment by eddieridwan** [comment]
Di aplikasi, tinggal ubah setting aplikasi. Baca petunjuk di https://github.com/OpenSID/OpenSID/wiki/Panduan-Konfigurasi-Aplikasi.

Untuk surat Ekspor Dok, otomatis, tidak perlu diubah. Isi saja jabatan di Pemerintahan Desa.

Untuk surat Cetak, silakan pelajari https://github.com/OpenSID/OpenSID/wiki/Mengubah-Template-Surat-Cetak

OpenSID sengaja dirancang supaya bisa digunakan di semua desa. Silakan konsultasi dengan Nagari Tanjung Haro Sikabukabu Padang Panjang di Kec Luak, Sumbar. Seknas OpenDesa di situ. Mereka desa percontohan OpenSID di Sumbar. Pasti bisa membantu.

**Comment by eddieridwan** [comment]
Issue bukan tempat bertanya. Silakan bertanya penggunaan OpenSID di https://www.facebook.com/groups/OpenSID/.

Saya akan tutup issue ini, karena bukan sesuatu yg memerlukan perubahan sistem.
