### ISSUE TITLE
tambahkan list baris teksberjalan

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#2044]
### Bagaimana alurnya sampai muncul masalah?
penangannan teks berjalan saat ini (prarilis) hanya bisa diisi satu kalimat saja sedangkan penerapan di desa bisa terdapat lebih dari beberapa kalimat

### Seperti apa yang diharapkan?
bisa ditambahkan kalimat kalimat lain 

### Apa yang terjadi?
tidak bisa menambah kalimat lain, (walaupun diakali dengan spasi tetap tertampil 1 kalimat)

### Informasi tambahan 
![weee5](https://user-images.githubusercontent.com/35319600/57767405-74e96100-7733-11e9-8f47-1165918d89b2.jpg)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
