### ISSUE TITLE
Tambahkan Isian Link pada Teks Berjalan supaya bisa di klik

### ISSUE THREAD

**Issue by hasap86** [OpenSID/OpenSID#2045]
### Bagaimana alurnya sampai muncul masalah?
Teks Berjalan sebatas informasi singkat, detailnya tidak ada

### Seperti apa yang diharapkan?
diberikan link pada inputan teks berjalan yg merujuk ke artikel detail informasi dengan tambahan teks link detailnya, cth: selengkapnya / info detail

### Apa yang terjadi?
informasi detail tidak bisa ditampilkan saat ini

### Informasi tambahan 
2 inputan yg perlu ditambahkan, 
1. Link Rujukan
2. Teks Link

Contoh setelah ditambahkan link dan teks link: **Jadwal Imsak untuk wilayah jakarta dan sekitarnya...[Selengkapnya](http://demo.opensid.my.id)**

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | Versi 19.05-pasca
| Versi PHP        | 
| System operasi   |

**Comment by ariandii** [comment]
Untuk tema natra sudah membaca otomatis teks berjalan yang mengandung kata www menjadi link URL dan mengubahnya menjadi kata "Selengkapnya...".

https://github.com/OpenSID/tema-natra

**Comment by eddieridwan** [comment]
@hasap86 beri contoh seperti apa yg diinginkan.

**Comment by hasap86** [comment]
![link-teks-berjalan](https://user-images.githubusercontent.com/45263721/57975857-b5c7cb00-79fc-11e9-93ad-77cd37ca3d1c.jpg)

seperti ini mungkin contoh inputannya

**Comment by eddieridwan** [comment]
Sudah dicommit ke master
