### ISSUE TITLE
Input Peta menggunakan titik koordinat peta

### ISSUE THREAD

**Issue by hasap86** [OpenSID/OpenSID#2046]
### Bagaimana alurnya sampai muncul masalah?
Saat ini untuk menentukan lokasi pemetaan sangat sulit karena menggunakan peta langsung, sehingga tidak bisa tepat.

### Seperti apa yang diharapkan?
berikan inputan titik koordinat peta contoh -6.946955, 106.449525

### Apa yang terjadi?
saat ini kesulitan menentukan titik lokasi menggunakan peta

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | Versi 19.05-pasca
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
@hasap86 persisnya di menu mana?

**Comment by hasap86** [comment]
1. Identitas Desa > Peta Kantor / Wilayah Desa (Kantor Desa)
2. Penduduk > Lokasi Tempat Tinggal

**Comment by topanzhr** [comment]
Setuju saya, 
Sekedar tambahan, untuk daerah dengan sinyal lemah, sangat sulit untuk menentukan titik koordinat dengan peta langsung.

![Untitled](https://user-images.githubusercontent.com/39410359/60827260-00ceb500-a1da-11e9-901c-4b0ff8bfb82d.png)

**Comment by agungsugiarto** [comment]
Untuk peta wilayah desa, akan lebih sulit lagi kalau dibuat input -lat, lng seperti ini.

![image](https://user-images.githubusercontent.com/10989147/62332538-4d13c900-b4ea-11e9-8bec-c4d7bde4e45e.png)

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR #2276
