### ISSUE TITLE
Template Surat di Pengaturan Surat Tidak Bisa di Unduh

### ISSUE THREAD

**Issue by hasap86** [OpenSID/OpenSID#2047]
### Bagaimana alurnya sampai muncul masalah?
Tidak Bisa Unduh Template Surat

### Seperti apa yang diharapkan?
Bisa Unduh Template Surat untuk di edit

### Apa yang terjadi?
Tidak Bisa Edit Template Surat

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | Versi 19.05-pasca
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
@hasap86 apa errornya?

**Comment by hasap86** [comment]
![error-unduh-surat-pengaturan](https://user-images.githubusercontent.com/45263721/57975774-8b750e00-79fa-11e9-9591-419cfe4f4365.jpg)

Seperti tidak ada file di lokasi unduhannya..

**Comment by eddieridwan** [comment]
@hasap86 , saya coba di https://demo.opensid.my.id/index.php/surat_master, normal saja.
Melihat dari pesan error anda di atas, kemungkinannya masalah ada pada .htaccess anda. Apakah anda membuat .htaccess sendiri atau menyalin dari htacces.txt yg disediakan di rilis?

**Comment by hasap86** [comment]
betul di demo bisa, makanya saya unduh dari demo trus upload, nah kalo gitu baru bisa diunduh, apa mungkin file bawaannya utk install awal tidak terbawa?

**Comment by eddieridwan** [comment]
Masalahnya, server anda mengiri url itu adalah bagian dari controller `surat` bukan folder `surat`. Seperti sudah diminta di atas, periksa fild `.htaccess` anda. Masalahnya di situ.

**Comment by hasap86** [comment]
htaccess dari bawaannya saya ganti jadi .htaccess aja bung

**Comment by wawan1985** [comment]
sama kasusnya dengan saya bung Edi, untuk mencari htaccess dmn ya bung

**Comment by wawan1985** [comment]
![image](https://user-images.githubusercontent.com/32692160/58341600-7554bc80-7e03-11e9-93bd-32bcd85f103f.png)

**Comment by eddieridwan** [comment]
URL website anda apa?
Coba rename file `.htaccess` supaya menjadi non-aktif. Apakah masih error?

**Comment by hasap86** [comment]
tetep masih error, kayaknya ini bermasalah untuk yg instal pertama kali untuk script yg sekarang

**Comment by eddieridwan** [comment]
@hasap86 Kalau mau, silakan kirim login cPanel anda ke PM dan saya akan coba lacak masalah di server hosting anda.

**Comment by eddieridwan** [comment]
> sama kasusnya dengan saya bung Edi, untuk mencari htaccess dmn ya bung

Bung @wawan1985, karena anda menggunakan layanan OpenDesa, silakan bertanya di group Telegram _Support Hosting OpenDesa_ untuk dibantu di sana.

**Comment by ariandii** [comment]
Apakah ini masih bermasalah?

**Comment by hasap86** [comment]
> Apakah ini masih bermasalah?

masih bermasalah ketika saya coba install ulang untuk pertama kalinya lagi

**Comment by eddieridwan** [comment]
Sudah dicommit ke `master` melalui PR #2759
