### ISSUE TITLE
#2048 ada menu sinkronisasi bagi desa memanfaatkan opensid secara offline

### ISSUE THREAD

**Issue by Refi992001** [OpenSID/OpenSID#2048]
Masih banyak desa yang jaringan internetnya belum bagus, mungkinkah penambahan fitur sinkronisasi untuk desa yang memanfaatkan opensid secara offline agar dapat memperbarui opensid online nya secara berkala.

**Comment by KASWANDI** [comment]
Fitur sinkronisasi sangat dibutuhkan bgi desa2 dngan kbutuhan jaringan internet yg blum stabil

**Comment by redjoel** [comment]
saat ini sinkronisasi memang masih perlu manual.
saya menggunakan fitur backup dan restore untuk database kemudian melakukan sinkronisasi folder arsip didalam folder desa menggunakan FTP

**Comment by eddieridwan** [comment]
Opsi sinkron terbatas, dengan asumsi:
1. offline digunakan untuk semua fungsi kecuali yg dilakukan oleh pengunjung web, termasuk Layanan Mandiri
2. online HANYA digunakan untuk fitur pengunjung web dan Layanan Mandiri.

Yaitu, online TIDAK digunakan untuk mengelola data penduduk, mencetak surat, atau mengelola data apapun.

Dengan demikian, sinkronisasi data bisa disederhanakan:
1. dari online -> offline, hanya transfer data:
    1. komentar
    2. data yg diisi oleh pengguna Layanan Mandiri
    3. statistik pengunjung
2. dari offline -> online, transfer semua data yang ditampilkan di web, kecuali (1) di atas.

**Comment by eddieridwan** [comment]
Untuk sinkronisasi offline <-> online, yg disinkronkan cukup data yg berubah saja, supaya lebih efisien.  Jadi semua data yg menjadi sasaran sinkronisasi perlu mencatat waktu diubahnya.
Dan juga perlu ada log sinkronisasi, untuk mencatat kapan dilakukan sinkronisasi terakahir.

**Comment by afa28** [comment]
> Untuk sinkronisasi offline <-> online, yg disinkronkan cukup data yg berubah saja, supaya lebih efisien. Jadi semua data yg menjadi sasaran sinkronisasi perlu mencatat waktu diubahnya.
> Dan juga perlu ada log sinkronisasi, untuk mencatat kapan dilakukan sinkronisasi terakahir.

Tabel apa sja yg perlu sinkronisasi??

**Comment by eddieridwan** [comment]
Issue ini dipecah menjadi bagiannya:

- https://github.com/OpenSID/OpenSID/issues/3984
- dilanjutkan...

**Comment by andifahruddinakas** [comment]
Perlu di rancang ulang
