### ISSUE TITLE
Penambahan fitur untuk Siskeudes V2.0

### ISSUE THREAD

**Issue by depcapps** [OpenSID/OpenSID#2049]
### Bagaimana alurnya sampai muncul masalah?
Untuk memaksimakan kerja dari perangkat desa, terutama untuk kasi dan kaur dalam penggunaan aplikasi Siskeudes V2.0. Dalam artian nantinya setiap kasi dan kaur akan membuat SPP ( Surat Perintah Pembayaran ) sesuai dengan tupoksi masing-masing. tanpa melibatkan Kaur Keuangan/Bendahara Desa dalam membuat SPP Kegiatan. 

SPP Kegiatan tersebut akan dibuat oleh masing-masing kasi dan kaur sampai dengan pembuatan SPJ. Bendahara Desa dan Sekretaris desa hanya akan menverivikasi SPP tersebut untuk segera/tidak melakukan pencairan.

### Seperti apa yang diharapkan?
1. Memaksimalkan tupoksi kerja dari Kasi dan Kaur pada Perangkat Desa
2. Siskeudes tersebut akan bisa diakses dimanapun berada
3. Sebagai Backup dari aplikasi apabila terjadi eror pada komputer/pc/laptop
4. 

### Apa yang terjadi?
1. nantinya siskeudes akan berbasis Web

### Informasi tambahan 
1. database siskeudes adalah .mde sedangkan SID SQL
2. Saya masih awam mengnai SID, tetapi desa memiliki SID yng dikeloah dari Kabupaten
http://sid.sidoarjokab.go.id

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by Gunturwijay** [comment]
saya sangat setuju kalau fitur pembuatan spj dimasukkan kedalam opensid, karena dalam aplikasi siskeudes tanggal pembuatan spj tidak bisa di undur, sementara yang terjadi selama ini tanggal pembuatan spj harus di undur dari tanggal penarikan uang pada bank. kalau bagi saya kurang tertarik dengan aplikasi siskeudes, karena untuk pengusaaan aksesnya tidak diberikan penuh kepada desa.

**Comment by jufrissi2016** [comment]
perlu dipahami alur dalam Aplikasi Siskeudes Ada namanya SPP Definitif dan SPP panjar.  
1. ketika kita menggunakan SPP Definitif Kegiatan Sudah dilakukan, bukti2 sdh ada, setelah dana cair langsung dipertanggungjawabkan
1. SPP Panjar kita bisa pahami semua apa namanya panjar.... meminta kemuadian mempertanggung jwabkan kemudian...

**Comment by mizwaruddin** [comment]
@afa28 sudah ada impor siskeudes.
