### ISSUE TITLE
Fitur: Tambah laporan kependudukan bulan per dusun

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#205]
Statistik > Laporan Kependudukan Bulanan

Sekarang menampilkan data keselurahan desa dan perubahan selama sebulan.

Desa di Kecamatan Gerung, Lombok Barat juga menerbitkan laporan kependudukan bulanan yang dirinci per dusun.

[Laporan kependudukan.pdf](https://github.com/eddieridwan/OpenSID/files/612467/Laporan.kependudukan.pdf)

**Comment by afa28** [comment]
pak @eddieridwan, apakah issue ini masih diperlukan atau ada pembaharuan ???

**Comment by eddieridwan** [comment]
Sudah ada laporan per dusun di Buku Rekapitulasi Jumlah Penduduk. Jadi saya tutup.
