### ISSUE TITLE
 Sekarang daftar penduduk belum bisa diurut berdasarkan Tanggal Terdaftar

### ISSUE THREAD

**Issue by benioke** [OpenSID/OpenSID#2050]
Bagaimana alurnya sampai muncul masalah?
Seperti issue #2014 daftar keluarga bisa diurut berdasarkan Tanggal Terdaftar
Perlu di buat juga untuk daftar penduduk agar bisa di urut berdasarkan Tanggal terdaftar penduduk baik itu penduduk baru atau pun dari tambah anggota dari baru
Seperti apa yang diharapkan?
Agar nanti nya operator bisa tahu penduduk mana yang baru masuk atau anggota keluarga baru yang masuk dari dusun berapa, rw berapa, dan rt berapa melalui tanggal terdaftar nya.Sekarang laporan penduduk bulanan hanya menampilkan angka saja.
Apa yang terjadi?
Daftar penduduk belum bisa di urut berdasarkan Tanggal Terdaftar nya
Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19.05
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dicommit ke master
