### ISSUE TITLE
Perlu dibuatkan menu untuk singkronisasi data dengan Profil Desa Online

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#2051]
### Bagaimana alurnya sampai muncul masalah?
Mengingat Profil Desa Online (prodeskel) dalam penginputan data masih dilakukan satu persatu, maka pemerintah desa dalam proses penginputan data sangat kesulitan, sehingga perlu ditambahkan fitur singkronisasi dengan aplikasi Prodeskel seperti yang ada di Aplikasi SIDEKA

### Seperti apa yang diharapkan?
Adanya fitur singkronisasi data OpenSID dengan Aplikasi Profil Desa Online (Prodeskel)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
Pak @MUHAMMADRANGSEL issue ini masih diperlukan, klw tdk bisa di close sj

**Comment by andifahruddinakas** [comment]
Perlu di rancang ulang
