### ISSUE TITLE
Tampilannya baik Menu Statis maupun Dinamis berurutan mulai dari Kategori ==> Sub Kategori di SUB MENU ARTIKEL

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#2052]
### Bagaimana alurnya sampai muncul masalah?
Ketika menambahkan Sub menu di menu Artikel sub menunya bertambah kebawah
![image](https://user-images.githubusercontent.com/25834335/58197050-0b9eba80-7cfe-11e9-91cc-19019aca104b.png)
### Seperti apa yang diharapkan?
Adanya Sub menu 

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by ariandii** [comment]
Sudah tersedia sebelumnya sub menu pada Admin Web -> Menu -> dengan klik tanda + pada table artikel.

![image](https://user-images.githubusercontent.com/46939846/58377394-a3740100-7fa9-11e9-8ac5-47ebfd727246.png)

**Comment by MUHAMMADRANGSEL** [comment]
Yang saya maksud seperti ini : 
![1](https://user-images.githubusercontent.com/25834335/58433836-7a5b8980-80eb-11e9-887a-6f1975889ba2.png)
![2](https://user-images.githubusercontent.com/25834335/58433845-80ea0100-80eb-11e9-9657-d4d889a1825c.png)
![3](https://user-images.githubusercontent.com/25834335/58433847-81829780-80eb-11e9-8622-36fe4c470898.png)
![4](https://user-images.githubusercontent.com/25834335/58433848-821b2e00-80eb-11e9-8443-49068f7f2b62.png)
![5](https://user-images.githubusercontent.com/25834335/58433849-821b2e00-80eb-11e9-9a91-2b357b964083.png)

**Comment by MUHAMMADRANGSEL** [comment]
Tampilannya baik Menu Statis maupun Dinamis berurutan mulai dari Kategori ==> Sub Kategori di SUB MENU ARTIKEL

**Comment by ariandii** [comment]
itu sudah ada screenshot sesuai keinginannya, apa tidak sebaiknya script perubahan yang Anda buat tersebut langsung dikirimkan pull request saja.

**Comment by MUHAMMADRANGSEL** [comment]
Itu saya edit pakai word bung ariandii,

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3252
