### ISSUE TITLE
Bug Klik Data Statistik

### ISSUE THREAD

**Issue by Galiarta** [OpenSID/OpenSID#2054]
### Bagaimana alurnya sampai muncul masalah?
Masuk ke : [http://demo.opensid.my.id/index.php/statistik/index/1](http://demo.opensid.my.id/index.php/statistik/index/1)
Klik salah satu link statistik, misal statistik pekerjaan >> pelajar >> Laki-laki
![image](https://user-images.githubusercontent.com/33612251/58259185-a226b680-7da6-11e9-884b-55c1019f6e44.png)

Terjadi Error 500
![image](https://user-images.githubusercontent.com/33612251/58259249-bf5b8500-7da6-11e9-9edc-194cf40df8f0.png)

### Seperti apa yang diharapkan?
Data penduduk tampil normal

### Apa yang terjadi?
Error 500, seperti pada gambar.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19.05 pasca
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dicommit ke master
