### ISSUE TITLE
Menu Teks Berjalan Menjadi Banyak

### ISSUE THREAD

**Issue by hasap86** [OpenSID/OpenSID#2055]
![menu-teks-berjalan-banyak](https://user-images.githubusercontent.com/45263721/58375280-3ea0b280-7f79-11e9-9dae-e18c47d9a250.png)

### Bagaimana alurnya sampai muncul masalah?
Terdapat beberapa menu Teks Berjalan

### Seperti apa yang diharapkan?
seharusnya 1 

### Apa yang terjadi?
tidak beraturan

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | Versi 19.05-pasca
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
@hasap86 jelaskan langkah yg anda lakukan sampai terjadinya error ini. Bagaimana caranya anda melakukan Migrasi DB? Dari versi OpenSID berapa? Versi PHP berapa?

Lampirkan database anda untuk diperiksa.

**Comment by hasap86** [comment]
awalnya Versi 19.05 lalu di update ke Versi 19.05-pasca yg #2045: Teks berjalan sekarang bisa ditambahkan tautan ke artikel terkait. lakukan migrasi, jadi seperti itu

**Comment by eddieridwan** [comment]
@hasap86 Apakah sudah coba dari v19.05 dan update ke versi 19.05-pasca terbaru (commit kemarin)? Versi terbaru telah memperbaiki proses migrasi. Sepertinya masalah anda karena proses migrasi sebelumnya yg mungkin menyebabkan error ini.

**Comment by hasap86** [comment]
sudah dicoba tadi sebelum saya buatkan issue ini pak, mungkin akan saya coba lagi dengan database baru dari contoh db terakhir... untuk memastikan letak errornya

**Comment by hasap86** [comment]
oh ternyata, setiap saya melakukan migrasi, menu Teks Berjalannya bertambah 1.

**Comment by hasap86** [comment]
Tapi saya coba di demo gak masalah, hehe

**Comment by eddieridwan** [comment]
Apakah sudah coba dengan versi terbaru?

**Comment by hasap86** [comment]
ini menggunakan script terbaru pak

**Comment by eddieridwan** [comment]
Apakah juga menggunakan database bawaan di versi itu?

**Comment by eddieridwan** [comment]
PHP versi berapa?

**Comment by hasap86** [comment]
Sudah saya coba Install ulang dengan menggunakan database bawaan yg terbaru dan tidak ada masalah, mungkin karena database sebelumnya yg bermasalah... saya close saja issue ini ya
