### ISSUE TITLE
Ubah Teks Berjalan, Konten Kosong

### ISSUE THREAD

**Issue by hasap86** [OpenSID/OpenSID#2056]
![ubah-teks-berjalan-kosong](https://user-images.githubusercontent.com/45263721/58375302-c25a9f00-7f79-11e9-99be-1837c6f70471.png)

### Bagaimana alurnya sampai muncul masalah?
Saat Ubah Teks Berjalan, Konten yang akan diubah Kosong

### Seperti apa yang diharapkan?
seharusnya saat diubah konten yg diubah muncul

### Apa yang terjadi?
tidak bisa ubah konten teks berjalan yang sudah ada

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | Versi 19.05-pasca
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
@hasap86 sepertinya database anda ada yg salah. Di demo.opensid.my.id tidak bermasalah.
Coba lampirkan database anda.

**Comment by hasap86** [comment]
[backup-on-2019-05-26-05-56-06.zip](https://github.com/OpenSID/OpenSID/files/3219823/backup-on-2019-05-26-05-56-06.zip)

berikut saya lampirkan

**Comment by hasap86** [comment]
ini install awal dari database bawaan yg Versi 19.05-pasca

**Comment by eddieridwan** [comment]
@hasap86 apakah sudah coba lagi mengubah teks berjalan?

**Comment by hasap86** [comment]
Alhamdulillah saya coba upliad script commit terbaru dengan database baru bawaannya, tidak ada masalah, sepertinya memeang karena database sebelumnya yg bermasalah
