### ISSUE TITLE
Export Data Artikel Beserta Kategorinya

### ISSUE THREAD

**Issue by hasap86** [OpenSID/OpenSID#2057]
### Bagaimana alurnya sampai muncul masalah?
belum ada fitur export khusus artikel saja

### Seperti apa yang diharapkan?
adanya fitur export data artikel

### Apa yang terjadi?
memudahkan saat membuat database baru jika terjadi masalah pada db.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
@hasap86 fitur ini tidak diperlukan. 

Pengguna selalu disarankan membuat backup keseluruhan database secara rutin untuk menjaga adanya masalah. Sebaiknya tidak membuat backup per tabel. Tujuan utama fitur ekspor adalah untuk supaya bisa diimpor ke aplikasi lain -- atau apabila ada proses perubahan manual yg lebih efisien dilakukan di luar aplikasi.
