### ISSUE TITLE
Gagal simpan Pengaturan Youtube pada Widget Sosial Media

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#2058]
### Bagaimana alurnya sampai muncul masalah?
Mengaktifkan widget Sosial Media,
Gagal pada saat klik simpan pada Pengaturan Youtube jika kolom masih kosong.
Namun sukses jika dilakukan pada Pengaturan Sosial Media lainnya.

### Seperti apa yang diharapkan?
Berfungsinya tombol simpan walau kolom dalam keadaan kosong.

### Apa yang terjadi?
Muncul keterangan seperti gambar berikut:

![image](https://user-images.githubusercontent.com/46939846/58376480-7c600400-7f96-11e9-92a2-9a743e809095.png)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR #2062
