### ISSUE TITLE
Validasi saat edit data penduduk

### ISSUE THREAD

**Issue by virgantara** [OpenSID/OpenSID#2059]
### Bagaimana alurnya sampai muncul masalah?
Saya mencoba update data penduduk dengan mengosongkan beberapa field, yaitu:
1. ktp_el
2. status_rekam

### Seperti apa yang diharapkan?
Ekpektasi saya, seharusnya ada validasi untuk field yg mandatory. Atau, at least, munculkan tanda * di field yg mandatory. Bentuk validasi pun kalau bisa dua sisi, frontend dan backend. Kalau hanya backend, dengan field sebanyak itu, user akan dipaksa menunggu ketika Simpan. Sedangkan jika validasi dari sisi frontend, user akan mendapat popup saat itu juga sebelum data POST.  

### Apa yang terjadi?
Namun, ketika saya tekan Simpan, langsung muncul Error dari database untuk default value field tersebut.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19.05
| Versi PHP        |  7.3
| System operasi   | Ubuntu 18.04

**Comment by eddieridwan** [comment]
@virgantara saat ini pada pengisian form data penduduk sedikit sekali kolom isian yg diharuskan. Yang harus diisi saat ini sudah diperiksa menggunakan javascript. Anda bisa lihat kolom mana saja yg saat ini diharuskan dengan menekan tombol simpan pada form kosong. Pemeriksaan itu dilakukan di browser.

Sedangkan validasi dilakukan di server.

Selama ini, pengisian data dibuat cukup longgar dengan tidak memaksa semua data perlu diisi pada saat menambah penduduk. Kalau anda beranggapan ada yg lain yg sebaiknya juga HARUS diisi, sebaiknya anda konsultasi dengan pengguna lain di https://www.facebook.com/groups/OpenSID untuk mendapat persetujuan kolom apa saja yg akan diharuskan.

**Comment by eddieridwan** [comment]
Usul anda untuk memberi tanda (misalnya '*') pada kolom isian yg harus diisi baik untuk diterapkan. Juga sebagian validasi yg saat ini dilakukan di server dapat juga dipindahkan ke browser (misalnya NIK harus 16 digit atau 0).

Kalau anda programmer, silakan anda pelajari dan kirim pull request untuk menerapkan usul anda tersebut.

**Comment by virgantara** [comment]
Validasi yang saya maksudkan adalah ketika edit data penduduk. Ada beberapa field yg saya sebutkan di atas (ktp el, status rekam), non-mandatory, ketika di Simpan kosongan terjadi error karena default value tidak ada. Sedangkan di database, column tsb NOT NULL.

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR #2061
