### ISSUE TITLE
Fitur: Tambah laporan kepemilikan KK

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#206]
Statistik > Statistik Kependudukan Bulanan

Desa di Kecamatan Gerung, Lombok Barat menerbitkan laporan Tabel Data Kepemlikian KK yang dirinci per dusun. Contoh terlampir tidak ada tanggal - sebaiknya ditambahkan tanggal tabel dicetak. Asumsi data di kolom 'Jumlah KK Yang Terbit' adalah untuk bulan laporan, tetapi perlu dikonfirmasi.

[Laporan pemilikan KK.pdf](https://github.com/eddieridwan/OpenSID/files/612469/Laporan.pemilikan.KK.pdf)

**Comment by afri18** [comment]
Laporan kepemilikan KK bisa dilacak di tanggal cetak KK

**Comment by afa28** [comment]
pak @eddieridwan, apakah issue ini masih diperlukan atau ada pembaharuan ???

**Comment by eddieridwan** [comment]
Saya akan tutup dulu. Kalau ada yg membutuhkan, bisa dibuka lagi.
