### ISSUE TITLE
Widget memunculkan arsip artikel secara acak

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#2060]
### Bagaimana alurnya sampai muncul masalah?
Terjadinya persamaan informasi (urutan) antara artikel yang ditampilkan pada halaman utama dengan widget "Arsip Artikel".

### Seperti apa yang diharapkan?
Adanya widget memunculkan beberapa artikel secara acak.

### Apa yang terjadi?
Mengetahui artikel yang sudah pernah dibuat sebelumnya.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR #2062
