### ISSUE TITLE
teks_berjalan' doesn't exist

### ISSUE THREAD

**Issue by Refi992001** [OpenSID/OpenSID#2063]
error 500
Table 'u4717341_SidBMC.teks_berjalan' doesn't exist

SELECT `teks`, `tautan`, `judul_tautan` FROM `teks_berjalan` WHERE `status` = 1 ORDER BY `urut`

Filename: models/Teks_berjalan_model.php

Line Number: 16

Harap laporkan masalah ini, agar kami dapat mencarikan solusinya. Untuk sementara Anda dapat kembali ke halaman awal.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 7.2
| System operasi   |linux

**Comment by eddieridwan** [comment]
@Refi992001 apakah sudah menjalankan _Pengaturan > Database > Migrasi DB_?

Harap membaca panduan dulu.

**Comment by Refi992001** [comment]
belum bisa masuk ke admin, pak .... baru masukkan alamat webnya sdh muncul
error 500

**Comment by Refi992001** [comment]
Sebuah Kesalahan Basis Data Telah Terjadi

Error Number: 1146

Table 'u4717341_SidBMC.teks_berjalan' doesn't exist

SELECT `teks`, `tautan`, `judul_tautan` FROM `teks_berjalan` WHERE `status`
= 1 ORDER BY `urut`

Filename: models/Teks_berjalan_model.php

Line Number: 16
Harap laporkan masalah ini, agar kami dapat mencarikan solusinya. Untuk
sementara Anda dapat kembali ke halaman awal <http://bamasco.info/>.

**Comment by Refi992001** [comment]
![image](https://user-images.githubusercontent.com/50808748/58428971-70775d80-80ce-11e9-82b8-dc6507bf87b8.png)

dari offline jg ternyata sama, ada link lain ga opensid 19.05

**Comment by ariandii** [comment]
bisa masuk di http://localhost/sid/siteman pak,

lalu pilih menu pengaturan -> database -> migrasi db -> klik tombol merah.

![image](https://user-images.githubusercontent.com/46939846/58429784-2fcd1380-80d1-11e9-8c8a-890fb0efd2e2.png)

**Comment by Refi992001** [comment]
tq pak
