### ISSUE TITLE
Sekarang penduduk belum bisa di temukan di pencarian jika nik nya "0"

### ISSUE THREAD

**Issue by benioke** [OpenSID/OpenSID#2065]
Bagaimana alurnya sampai muncul masalah?
Penduduk belum bisa di temukan jika nik nya ' 0 '

Seperti apa yang diharapkan?
Seharus nya bisa ditemukan jika nik penduduk nya ' 0 '

Apa yang terjadi?
Perlu ditemukan jika nik nya ' 0 ' setelah nik nya sudah ada tinggal di edit nik nya dengan nik yg sebenar nya.

Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19.05 pasca
| Versi PHP        | 
| System operasi   |

**Comment by ariandii** [comment]
saya coba pencarian jika nik 0, sukses pak.

**Comment by ariandii** [comment]
![image](https://user-images.githubusercontent.com/46939846/58429540-66eef500-80d0-11e9-8a16-22a747cdb54e.png)

**Comment by benioke** [comment]
Itu cari nya melalui nama penduduk.Jika penduduk nya lebih dari 100 orang yang nik nya 0 .bagai mana cara filter nya..

**Comment by eddieridwan** [comment]
@benioke bisa gunakan fitur _Pencarian Spesifik_

![pencarian-spesifik](https://user-images.githubusercontent.com/249563/58442160-ce865e00-812b-11e9-91d6-49cd2ad949ab.jpg)

**Comment by eddieridwan** [comment]
Kalau yg diinginkan adalah melihat penduduk dengan NIL '0', anda dapat mengurut daftar penduduk berdasar NIK (klik judul kolom NIK). Semua penduduk dengan NIK '0' dapat ditampilkan di awal daftar penduduk.

**Comment by eddieridwan** [comment]
@benioke kalau info yg diberikan di sini bermanfaat, mohon anda ikut membantu dengan merekam petunjuk ini di panduan OpenSID di https://github.com/OpenSID/OpenSID/wiki

**Comment by ariandii** [comment]
> Itu cari nya melalui nama penduduk.Jika penduduk nya lebih dari 100 orang yang nik nya 0 .bagai mana cara filter nya..

bukan hanya 100, tapi saya praktekkan di database penduduk berjumlah 1.647 record.

![image](https://user-images.githubusercontent.com/46939846/58450357-c41e9100-8138-11e9-9139-8703777946fd.png)

![image](https://user-images.githubusercontent.com/46939846/58450360-c97bdb80-8138-11e9-8c23-91d880ca75d7.png)

**Comment by eddieridwan** [comment]
@benioke , apakah issue ini bisa ditutup? Atau apakah masih ada yg bermasalah?

**Comment by benioke** [comment]
Oke pak eddie..issue ini bisa di tutup
