### ISSUE TITLE
Sebutan 'desa' pada Pengaturan Database tidak seperti yang seharusnya

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#2067]
### Bagaimana alurnya sampai muncul masalah?
Sebutan desa pada pada menu Pengaturan -> Database -> Ekspor Database belum sesuai dengan sebutan desa seharusnya.

![2](https://user-images.githubusercontent.com/46939846/58451679-ae13cf00-813e-11e9-8497-bea5eb4f10be.png)

### Seperti apa yang diharapkan?
Menampilkan sebutan desa sesuai dengan yang sudah disetting.

![1](https://user-images.githubusercontent.com/46939846/58451681-b3711980-813e-11e9-9329-1357d1879432.png)

### Apa yang terjadi?
Muncul sebutan desa pada header menu Ekspor Database sama dengan sebutan seharusnya.

![3](https://user-images.githubusercontent.com/46939846/58451727-da2f5000-813e-11e9-8cb8-f4680a0be610.png)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19.05-pasca
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR #2066
