### ISSUE TITLE
Perlu Sediakan tombol pindah posisi ke atas dan pindah posisi ke bawah untuk Wilayah Administratif Dusun, RW, RT

### ISSUE THREAD

**Issue by benioke** [OpenSID/OpenSID#2068]
Bagaimana alurnya sampai muncul masalah?

Untuk wilayah administratif dusun,rw,dan rt .saat ini belum ada tombol pindah posisi ke atas/ke bawah seperti yang ada dimodul Pemerintahan desa seperti gambar di bawah ini
![fitur1](https://user-images.githubusercontent.com/47577404/58478493-6f066d80-8180-11e9-81ab-6ab81c65481b.JPG)

Seperti apa yang diharapkan?
Perlu adanya di buat sperti modul pemerintahan desa
![fitur2](https://user-images.githubusercontent.com/47577404/58478513-7cbbf300-8180-11e9-8b71-7c517cdbe483.JPG)

Apa yang terjadi?
Operator tidak bisa mengatur sendiri posisi nama dusun sesuai degan keinginan nya.

Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19.05 pasca
| Versi PHP        | 
| System operasi   |

**Comment by usupha** [comment]
kenapa harus seperti itu pak?

**Comment by benioke** [comment]
Untuk mempermudah pengguna untuk mengatur dusun nya..sesuai dengan urutan yang di inginkan

**Comment by afa28** [comment]
Pak @eddieridwan, apakah ini perlu???

**Comment by eddieridwan** [comment]
Sepertinya bermanfaat.

**Comment by sup-ham** [comment]
pengurutan biasanya pake colum sorting aja

**Comment by afa28** [comment]
> pengurutan biasanya pake colum sorting aja

Jd bagusnya pakai yg mana, tambah kolom urut beserta tombolnya atau gunakan pengurutan pd tabel???

**Comment by eddieridwan** [comment]
Sepertinya pengurutannya perlu bisa berlaku juga bagi fitur cetak/unduh. Bagaimana @benioke ?

**Comment by benioke** [comment]
Oke pak

Pada tanggal Kam, 25 Jun 2020 11:01, Eddie Ridwan <notifications@github.com>
menulis:

**Comment by eddieridwan** [comment]
Urut dusun sudah dicommit ke 'rilis-dev'. Tapi belum urut RW atau RT.

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR https://github.com/OpenSID/premium/pull/59
