### ISSUE TITLE
Fitur: Tambah laporan Lembar Pokok Pemakaman

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#207]
Statistik > Statistik Kependudukan Bulanan

Desa di Kecamatan Gerung, Lombok Barat menerbitkan laporan Lembar Pokok Pemakaman yang berisi data kematian/pemakaman setiap bulan.

[Laporan pemakaman.pdf](https://github.com/eddieridwan/OpenSID/files/612477/Laporan.pemakaman.pdf)

**Comment by afa28** [comment]
pak @eddieridwan, apakah issue ini masih diperlukan atau ada pembaharuan ???

**Comment by eddieridwan** [comment]
Saya akan tutup. Kalau ada yg memerlukan bisa dibuka lagi.
