### ISSUE TITLE
Import BIP sukses tapi data kosong format bip 2012

### ISSUE THREAD

**Issue by andryrukandifauzy** [OpenSID/OpenSID#2070]
### Bagaimana alurnya sampai muncul masalah?
Saat impor database sukses tapi data masuk kosong

### Seperti apa yang 
![Screenshot_1](https://user-images.githubusercontent.com/42363553/58690908-d7d62b80-83b4-11e9-89ab-1420685bc410.png)
![Screenshot_2](https://user-images.githubusercontent.com/42363553/58690909-d86ec200-83b4-11e9-96e8-77ec0c1589c5.png)
![Screenshot_3](https://user-images.githubusercontent.com/42363553/58690910-d86ec200-83b4-11e9-8cc8-2b4632056111.png)

diharapkan?
data ada seteleah upload

### Apa yang terjadi?
data penduduktidak ada

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19-05 pasca
| Versi PHP        | 7.2
| System operasi   | debian 9 server

**Comment by andryrukandifauzy** [comment]
![Screenshot_4](https://user-images.githubusercontent.com/42363553/58691318-cd686180-83b5-11e9-8998-d803c9b716c5.png)

Sama semuacontoh bip sukses upload tapi data tidak masuk
![Screenshot_5](https://user-images.githubusercontent.com/42363553/58691319-cd686180-83b5-11e9-9f81-d1071a945723.png)
![Screenshot_6](https://user-images.githubusercontent.com/42363553/58691320-cd686180-83b5-11e9-883b-ca518134aacc.png)
![Screenshot_7](https://user-images.githubusercontent.com/42363553/58691321-ce00f800-83b5-11e9-9d3e-59009f515cec.png)

**Comment by eddieridwan** [comment]
@andryrukandifauzy , di https://demo.opensid.my.id, impor BIP berjalan normal. 
Di server anda, apa isi log file (di folder _logs_)? Apakah ada error tercatat di situ?
Coba dengan pra-rilis versi hari ini.

**Comment by eddieridwan** [comment]
@andryrukandifauzy apakah issue ini sudah bisa ditutup?

**Comment by andryrukandifauzy** [comment]
boleh di tutup saja dahulu Pak Eddie, Belum saya coba lagi karena kesibukan

Pada tanggal Sen, 3 Jun 2019 19.23, Eddie Ridwan <notifications@github.com>
menulis:

**Comment by eddieridwan** [comment]
Kirim datanya ke PM dan saya coba lihat.

**Comment by andryrukandifauzy** [comment]
[solved] Sekian lama mencari masalahnya akhirnya ketemu, 
kesalahan dalam menentukan owner folder /var/www/html/ di os linux

harus nya owner nya itu adalah apache

untuk merubahnya dengan cara seperti ini

chown apache:apache -R /var/www/html/

dan masukan user kita kedalam group apache
dengan cara usermod -a -G apache userkita

Terimakasih
