### ISSUE TITLE
Data alamat tidak termuat dalam file .xls hasil ekspor

### ISSUE THREAD

**Issue by adeas-rakit** [OpenSID/OpenSID#2071]
### Bagaimana alurnya sampai muncul masalah?
https://demo.opensid.id/database , mencoba ekspor data ke .xls 

### Seperti apa yang diharapkan?
Kolom alamat terisi dengan data _Alamat Sekarang_

### Apa yang terjadi?
Kolom alamat tidak memuncukkan data _Alamat Sekarang_

### Informasi tambahan 
isi file .xls hasil ekspor yang diubah menjadi .html
![penduduk_01_06_2019 html](https://user-images.githubusercontent.com/22555462/58742167-79f52280-844c-11e9-90cf-69957944b361.png)

data yang sudah diubah dengan mengisi alamat melalui fitur pindah penduduk dalam desa
![Opera Snapshot_2019-06-01_090502_demo opensid id](https://user-images.githubusercontent.com/22555462/58742176-a14bef80-844c-11e9-9112-13e468e2b830.png)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19.04
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
@adeas-rakit , kolom `alamat_sekarang` di tabel Penduduk (`tweb_penduduk`)  saat ini hanya berlaku pada penduduk yg bukan anggota KK, yaitu 'penduduk domisili' atau 'penduduk lepas'. Bagi penduduk yg anggota KK, alamatnya diambil dari kolom `alamat` di tabel Keluarga (`tweb_keluarga`).

Dengan info tersebut di atas, apakah anda tetap usulkan kolom `alamat_sekarang` tersebut dimasukkan ke ekspor Excel data penduduk?

**Comment by adeas-rakit** [comment]
@eddieridwan , terima kasih mas tanggapannya...
mungkin akan lebih baik jika kedua data alamat (alamat dari tweb_penduduk & tweb_keluarga) itu dapat ikut serta pada output ekspor, mengingat mudahnya ketika akan melihat apakah itu alamat atas data keluarga/penduduk lepas,

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR #2291
