### ISSUE TITLE
Surat baru Surat Keterangan Penghasilan Ayah

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#2072]
### Bagaimana alurnya sampai muncul masalah?
Lihat daftar surat di Pengaturan Surat

### Seperti apa yang diharapkan?
Ada pilihan Surat Keterangan Penghasilan Ayah

### Apa yang terjadi?
Belum ada.

### Informasi tambahan 

[Surat Keterangan Penghasilan Ayah.zip](https://github.com/OpenSID/OpenSID/files/3244625/Surat.Keterangan.Penghasilan.Ayah.zip)

Periksa dulu, apakah ada kesamaan dengan Surat Keterangan Penghasilan Orang Tua (#1004)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19.06
| Versi PHP        | 
| System operasi   |

**Comment by ariandii** [comment]
Sebelum kirim pull, saya lampirkan file Surat Keterangan Penghasilan Ayah dengan tambahan input nama Sekolah dan Keperluannya.

[surat_ket_penghasilan_ayah.zip](https://github.com/OpenSID/OpenSID/files/3271734/surat_ket_penghasilan_ayah.zip)

**Comment by upperhead93** [comment]
Sudah cukup pak, Tks.
Hanya dibagian kop surat apakah bisa dibuat dengan struktur seperti ini:
PEMERINTAH [NAMA_KAB]
KANTOR DESA [NAMA_DESA]
KECAMATAN [ NAMA_KEC]

**Comment by ariandii** [comment]
Berikut file yang sudah disesuaikan dengan urutan kop surat di atas.

[surat_ket_penghasilan_ayah.zip](https://github.com/OpenSID/OpenSID/files/3274144/surat_ket_penghasilan_ayah.zip)

**Comment by eddieridwan** [comment]
@upperhead93 @ariandii apakah teman2 sudah memeriksa Surat Keterangan Penghasilan Orangtua yg sudah ada di OpenSID? 

Apakah perlu juga ada variasi Surat Keterangan Penghasilan Ayah (https://github.com/OpenSID/OpenSID/issues/2072) dan Surat Keterangan Penghasilan Ibu (https://github.com/OpenSID/OpenSID/issues/2073)?

Bagaimana kalau Surat Keterangan Penghasilan Orangtua saja yg ditambahkan supaya ada keterangan keperluannya?

Sebaiknya kita tidak sediakan surat2 yg sebenarnya mirip, karena akan membingungkan operator. Kalau bisa, sebaiknya kita sederhanakan.

Contoh Surat Keterangan Penghasilan Orangtua yg sdh ada: 
[surat_ket_penghasilan_orangtua_5201140706966997_2019-06-15_004.rtf.zip](https://github.com/OpenSID/OpenSID/files/3292971/surat_ket_penghasilan_orangtua_5201140706966997_2019-06-15_004.rtf.zip)

**Comment by ariandii** [comment]
Di Desa kami sering terima permohonan surat keterangan penghasilan ayah atau ibu. dan hampir tidak pernah mengeluarkan keterangan penghasilan kedua orang tua dalam 1 surat.

Bagaimana dengan wilayah lain?

**Comment by eddieridwan** [comment]
@ariandii , kalau sudah selesai, mohon digabungkan ke rilis menggunakan pull request, termasuk menambahkan surat ini sebagai surat sistem melalui migrasi db di Database_model.php.

**Comment by ariandii** [comment]
Koreksi blok penandatangan.

[surat_ket_penghasilan_ayah.zip](https://github.com/OpenSID/OpenSID/files/3294815/surat_ket_penghasilan_ayah.zip)

**Comment by ariandii** [comment]
Update: Menyesuaikan kop surat hasil insert dari kop_surat_desa_kumba.rtf

[kop_surat_desa_kumba.zip](https://github.com/OpenSID/OpenSID/files/3308199/kop_surat_desa_kumba.zip)

[surat_ket_penghasilan_ayah.zip](https://github.com/OpenSID/OpenSID/files/3308200/surat_ket_penghasilan_ayah.zip)

**Comment by eddieridwan** [comment]
Contoh `kop_surat_desa_kumba.rtf` sudah ditambahkan di folder `desa-contoh/surat/raw` di branch `master`.  Saya juga sudah hapus image siluman di dalam semua template rtf bawaan sistem, dan juga di `kop_surat.rtf` dan `kop_surat_desa_kumba.rtf` sehingga ukuran file sekarang lebih kecil.

**Comment by eddieridwan** [comment]
Bung @ariandii : mohon perbaiki penulisan script di `data_rtf_surat_ket_penghasilan_ayah.php` (di copas di bawah) supaya mengikuti aturan penulisan script. Setelah itu, mohon digabungkan ke rilis menggunakan pull request, termasuk menambahkan surat ini sebagai surat sistem melalui migrasi db di Database_model.php.

```
// -- penghasilan ayah
	if (isset($input['hasil_ayah']))
		$hasil_ayah = preg_replace("/[^0-9,]/", "", $input['hasil_ayah']);
		$buffer = str_replace("[hasil_ayah]", Rupiah($hasil_ayah), $buffer);
		$buffer = str_replace("[tbl_hasil_ayah]", ucwords(number_to_words($hasil_ayah)), $buffer);
```

**Comment by ariandii** [comment]
Script di atas, perbedaannya apa ya pak dengan yang sudah diterapkan pada `data_rtf_surat`?

Karena setelah saya copas dan bandingkan, tidak ada yang berubah.

**Comment by eddieridwan** [comment]
Itu hanya copas, menunjukkan script yg perlu diperbaiki, bukan perbaikanya....

**Comment by ariandii** [comment]
Saya ikuti yang sudah diterapkan pada commit perbaikan script di:

https://github.com/OpenSID/OpenSID/commit/c1e31b7febf859e8701e3902761b02e2ce932aae

![image](https://user-images.githubusercontent.com/46939846/59972052-17f28d80-95b2-11e9-822e-6cd624654690.png)

Yang bertanda merah dan biru hasil perbaikan, saya perhatikan script tersebut juga tidak ada yang berubah.

Mohon pencerahan pak.

**Comment by eddieridwan** [comment]
@ariandii perbaikan yg diperlukan hanya indentasi. Indentasi saat ini tidak mengikuti aturan. Ikuti contoh perbaikan indentasi seperti di https://github.com/OpenSID/OpenSID/commit/c1e31b7febf859e8701e3902761b02e2ce932aae.

Indentasi yg benar akan menghindari kekeliruan mempelajari script.

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR #2110
