### ISSUE TITLE
Surat baru Surat Keterangan Penghasilan Ibu

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#2073]
### Bagaimana alurnya sampai muncul masalah?

Lihat daftar surat di Pengaturan Surat.

### Seperti apa yang diharapkan?
Ada Surat Keterangan Penghasilan Ibu

### Apa yang terjadi?
Tidak ada

### Informasi tambahan 
[Surat Keterangan Penghasilan Ibu.zip](https://github.com/OpenSID/OpenSID/files/3244627/Surat.Keterangan.Penghasilan.Ibu.zip)

Lihat juga #2072, #1004 - apakah ada kesamaan dan bisa digabung

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19.06
| Versi PHP        | 
| System operasi   |

**Comment by ariandii** [comment]
Sebelum kirim pull, saya lampirkan file Surat Keterangan Penghasilan Ibu dengan tambahan input nama Sekolah dan Keperluannya.

[surat_ket_penghasilan_ibu.zip](https://github.com/OpenSID/OpenSID/files/3271749/surat_ket_penghasilan_ibu.zip)

**Comment by upperhead93** [comment]
Sudah cukup pak, Tks.
Hanya dibagian kop surat apakah bisa dibuat dengan struktur seperti ini:
PEMERINTAH [NAMA_KAB]
KANTOR DESA [NAMA_DESA]
KECAMATAN [ NAMA_KEC]

**Comment by ariandii** [comment]
Bisa pak, akan disesuaikan kop nya.

**Comment by ariandii** [comment]
Berikut file yang sudah disesuaikan dengan urutan kop surat di atas.

[surat_ket_penghasilan_ibu.zip](https://github.com/OpenSID/OpenSID/files/3274148/surat_ket_penghasilan_ibu.zip)

**Comment by eddieridwan** [comment]
@upperhead93 @ariandii apakah teman2 sudah memeriksa Surat Keterangan Penghasilan Orangtua yg sudah ada di OpenSID? 

Apakah perlu juga ada variasi Surat Keterangan Penghasilan Ayah (https://github.com/OpenSID/OpenSID/issues/2072) dan Surat Keterangan Penghasilan Ibu (https://github.com/OpenSID/OpenSID/issues/2073)?

Bagaimana kalau Surat Keterangan Penghasilan Orangtua saja yg ditambahkan supaya ada keterangan keperluannya?

Sebaiknya kita tidak sediakan surat2 yg sebenarnya mirip, karena akan membingungkan operator. Kalau bisa, sebaiknya kita sederhanakan.

Contoh Surat Keterangan Penghasilan Orangtua yg sdh ada: 
[surat_ket_penghasilan_orangtua_5201140706966997_2019-06-15_004.rtf.zip](https://github.com/OpenSID/OpenSID/files/3292971/surat_ket_penghasilan_orangtua_5201140706966997_2019-06-15_004.rtf.zip)

**Comment by ariandii** [comment]
Di Desa kami sering terima permohonan surat keterangan penghasilan ayah atau ibu. dan hampir tidak pernah mengeluarkan keterangan penghasilan kedua orang tua dalam 1 surat.

**Comment by eddieridwan** [comment]
@ariandii , kalau sudah selesai, mohon digabungkan ke rilis menggunakan pull request, termasuk menambahkan surat ini sebagai surat sistem melalui migrasi db di Database_model.php.

**Comment by ariandii** [comment]
Koreksi blok penandatangan.

[surat_ket_penghasilan_ibu.zip](https://github.com/OpenSID/OpenSID/files/3294817/surat_ket_penghasilan_ibu.zip)

**Comment by ariandii** [comment]
Update: Menyesuaikan kop surat hasil insert dari kop_surat_desa_kumba.rtf

[kop_surat_desa_kumba.zip](https://github.com/OpenSID/OpenSID/files/3308199/kop_surat_desa_kumba.zip)

[surat_ket_penghasilan_ibu.zip](https://github.com/OpenSID/OpenSID/files/3308212/surat_ket_penghasilan_ibu.zip)

**Comment by eddieridwan** [comment]
Bung @ariandii : mohon perbaiki penulisan script di data_rtf_surat_ket_penghasilan_ibu.php (di copas di bawah) supaya mengikuti aturan penulisan script. Setelah itu, mohon digabungkan ke rilis menggunakan pull request, termasuk menambahkan surat ini sebagai surat sistem melalui migrasi db di Database_model.php.

```
// -- penghasilan ibu
	if (isset($input['hasil_ibu']))
		$hasil_ibu = preg_replace("/[^0-9]/", "", $input['hasil_ibu']);
		$buffer = str_replace("[hasil_ibu]", Rupiah($hasil_ibu), $buffer);
		$buffer = str_replace("[tbl_hasil_ibu]", ucwords(number_to_words($hasil_ibu)), $buffer);
```

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR #2111
