### ISSUE TITLE
Surat baru Surat Pengantar Permohonan Penerbitan Buku Pas Lintas

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#2074]
### Bagaimana alurnya sampai muncul masalah?
Lihat daftar surat di Pengaturan Surat

### Seperti apa yang diharapkan?
Ada Surat Pengantar Permohonan Penerbitan Buku Pas Lintas

### Apa yang terjadi?
Tidak ada

### Informasi tambahan 
[Surat Pengantar Permohonan Penerbitan Buku Pas Lintas Batas.zip](https://github.com/OpenSID/OpenSID/files/3244628/Surat.Pengantar.Permohonan.Penerbitan.Buku.Pas.Lintas.Batas.zip)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19.06
| Versi PHP        | 
| System operasi   |

**Comment by ariandii** [comment]
Memastikan untuk poin nomor 13 list pengikut/anggota keluarga apakah menampilkan seluruh anak usia dibawah 18 tahun dan belum memiliki KTP dalam satu KK tersebut, atau memungkinkan untuk dipilih beberapa anak saja?

**Comment by upperhead93** [comment]
Untuk poin 13 dibuat supaya memungkinkan untuk dipilih beberapa anak saja pak,

**Comment by ariandii** [comment]
Berikut terlampir file Surat Pengantar Permohonan Penerbitan Buku Pas Lintas sebagaimana contoh yang diberikan.

[surat_pengantar_permohonan_penerbitan_buku_pas_lintas.zip](https://github.com/OpenSID/OpenSID/files/3274994/surat_pengantar_permohonan_penerbitan_buku_pas_lintas.zip)

**Comment by eddieridwan** [comment]
@ariandii, mohon sesuaikan solusi anda dengan menggunakan kode isian `[penandatangan]`.

Selain itu, ada beberapa perbaikan/penyederhanaan script yg perlu dilakukan:
1. Ganti bentuk berikut yg agak rentan 
```
	if ($individu['sex'] == 'Laki-laki') {
		$buffer = str_replace("[s1]", "1", $buffer); }
	else if ($individu['sex'] == 'Perempuan') {
		$buffer = str_replace("[s1]", "2", $buffer); }
```
menggunakan
`$buffer = str_replace("[s1]", $individu['sex_id'], $buffer`

2. demikian juga, untuk _Agama_, langsung gunakan `$individu['agama_id']`

3. untuk 'status_kawin', saya telah ubah `get_data_surat()` di `Surat_model.php` supaya menyediakan kolom `status_kawin_id`. Jadi bisa langsung gunakan `$individu['status_kawin_id']`.

**Comment by eddieridwan** [comment]
@ariandii, Di script `data_rtf_surat_pengantar_permohonan_penerbitan_buku_pas_lintas.php` penyederhanaan berikut juga dapat dilakukan:

1. Ganti bentuk seperti ini
```	
        $buffer = str_replace("[ktp1]", $ktp[0], $buffer);
	$buffer = str_replace("[ktp2]", $ktp[1], $buffer);
       ..................
	$buffer = str_replace("[ktp15]", $ktp[14], $buffer);
	$buffer = str_replace("[ktp16]", $ktp[15], $buffer);
```
dengan bentuk seperti ini untuk lebih mudah diubah/diperiksa
```
for ($i=1; $i<=16; $i++)
{
  $buffer = str_replace("[ktp{$i}]", $ktp[$i-1], $buffer);
}
```

**Comment by eddieridwan** [comment]
@ariandii , beberapa hal di tampilan surat:
![f-1 66a](https://user-images.githubusercontent.com/249563/59552263-f1ff3480-8f84-11e9-995e-ee33c08e2ac4.jpg)
![f-1 66b](https://user-images.githubusercontent.com/249563/59552265-f297cb00-8f84-11e9-9907-4c0822a34b4b.jpg)

**Comment by eddieridwan** [comment]
@ariandii , catatan untuk form surat:
![buku-pas-lintas](https://user-images.githubusercontent.com/249563/59552325-bb75e980-8f85-11e9-84e2-b3d571c25c27.jpg)

**Comment by eddieridwan** [comment]
@ariandii , kalau sudah selesai, mohon digabungkan ke rilis menggunakan pull request, termasuk menambahkan surat ini sebagai surat sistem melalui migrasi db di `Database_model.php`.

**Comment by ariandii** [comment]
Berikut revisi surat tersebut:

[surat_pengantar_permohonan_penerbitan_buku_pas_lintas.zip](https://github.com/OpenSID/OpenSID/files/3294755/surat_pengantar_permohonan_penerbitan_buku_pas_lintas.zip)

**Comment by ariandii** [comment]
Pada surat di atas, penempatan nama_pamong saya simpan di luar kotak, dengan pertimbangan saat memilih a.n. ataupun Ub. agar tetap sejajar dengan nama penanda tangan jika ada di sisi kiri surat.

![contoh3](https://user-images.githubusercontent.com/46939846/59571018-6e4f6000-90ca-11e9-8f81-0f3c771c0b9a.png)

![contoh4](https://user-images.githubusercontent.com/46939846/59571014-67c0e880-90ca-11e9-8327-485cd9f05d30.jpg)

**Comment by ariandii** [comment]
Update menyesuaikan kop surat terbaru.

Pada Surat Pengantar Permohonan Penerbitan Buku Pas Lintas ini, kop surat langsung disisipkan pada file .rtf dengan pertimbangan, menyesuaikan format surat yang tidak menggunakan Alamat pada kop surat.

[surat_pengantar_permohonan_penerbitan_buku_pas_lintas.zip](https://github.com/OpenSID/OpenSID/files/3306053/surat_pengantar_permohonan_penerbitan_buku_pas_lintas.zip)

**Comment by eddieridwan** [comment]
Bung @ariandii :
1. file sementara `desa/surat/surat_pengantar_permohonan_penerbitan_buku_pas_lintas/%7E%24rat_pengantar_permohonan_penerbitan_buku_pas_lintas.rtf` perlu dihapus
2. di form `surat_pengantar_permohonan_penerbitan_buku_pas_lintas.php`, perbaiki masalah terlihat di gambar berikut
![surat-lintas-batas](https://user-images.githubusercontent.com/249563/59951330-e1fdbe00-9478-11e9-8576-2563d6b163d9.jpg)

**Comment by eddieridwan** [comment]
@ariandii , kalau sudah selesai, mohon digabungkan ke rilis menggunakan pull request, termasuk menambahkan surat ini sebagai surat sistem melalui migrasi db di Database_model.php.

**Comment by eddieridwan** [comment]
@ariandii untuk mengaktifkan fungsi centang di `surat_pengantar_permohonan_penerbitan_buku_pas_lintas.php`, ikuti contoh di `donjo-app/views/sid/kependudukan/penduduk.php`. 

Ubah menggunakan `id="checkall"` bukan class. Dan hapus `function change_all(total)`.

`<th><input type="checkbox" id="checkall"/></th>`

Kalau menggunakan id, javascript di `script.js` terkait akan menjadi aktif.

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR #2107
