### ISSUE TITLE
Perbaiki Surat Keterangan Kelahiran

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#2075]
### Bagaimana alurnya sampai muncul masalah?
Jalankan Surat Keterangan Kelahiran

### Seperti apa yang diharapkan?
Menghasilkan surat dan lampiran seperti contoh terlampir.

### Apa yang terjadi?
Belum sepenuhnya sesuai.

### Informasi tambahan 
[Surat Keterangan Kelahiran.zip](https://github.com/OpenSID/OpenSID/files/3244638/Surat.Keterangan.Kelahiran.zip)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19.06
| Versi PHP        | 
| System operasi   |

**Comment by KASWANDI** [comment]
terjadi corrput file saat download surat

**Comment by ariandii** [comment]
Berikut terlampir surat dimaksud:
[surat_ket_kelahiran.zip](https://github.com/OpenSID/OpenSID/files/3365418/surat_ket_kelahiran.zip)

**Comment by eddieridwan** [comment]
@ariandii , lampiran `f-2.01.php` perlu diubah juga sesuai dengan contoh yg disediakan di atas.

**Comment by KASWANDI** [comment]
Apakah masalah ini sdh diperbaiki mas?

**Comment by ariandii** [comment]
Lampiran `f-2.01`

[f-2.01.php.zip](https://github.com/OpenSID/OpenSID/files/3370701/f-2.01.php.zip)

**Comment by eddieridwan** [comment]
@ariandii , hasilnya belum pas. Juga menjadi dua halaman.

[surat_ket_pindah_penduduk_5201142005716996_2019-07-09_1_lampiran.pdf.zip](https://github.com/OpenSID/OpenSID/files/3370832/surat_ket_pindah_penduduk_5201142005716996_2019-07-09_1_lampiran.pdf.zip)

**Comment by ariandii** [comment]
Setelah install ulang XAMPP versi terbaru untuk 32 bit. Lampiran Surat Keterangan kelahiran normal kembali (tidak blank).

Berikut terlampir berkas tersebut.

[f-2.01.zip](https://github.com/OpenSID/OpenSID/files/3371050/f-2.01.zip)

**Comment by eddieridwan** [comment]
@ariandii , NIP melar ke halaman ke-2. Coba kurangi padding di bagian bawah tabel sebelum ttd.
[surat_ket_kelahiran_5201146510916995_2019-07-09_4_lampiran.pdf](https://github.com/OpenSID/OpenSID/files/3372943/surat_ket_kelahiran_5201146510916995_2019-07-09_4_lampiran.pdf)

**Comment by ariandii** [comment]
Coba saya revisi, sebab lampiran diatas saya uji coba sudah cukup 1 halaman.

[surat_ket_kelahiran_5201144609786995_2019-07-09_7_lampiran.pdf](https://github.com/OpenSID/OpenSID/files/3372978/surat_ket_kelahiran_5201144609786995_2019-07-09_7_lampiran.pdf)

**Comment by ariandii** [comment]
Lampiran dengan memberi padding 0 pada tabel bawah.

[f-2.01.zip](https://github.com/OpenSID/OpenSID/files/3373016/f-2.01.zip)

**Comment by eddieridwan** [comment]
@ariandii ok, sudah muat 1 halaman. Siip.

Sudah dicommit ke master.
