### ISSUE TITLE
Perbaiki Surat Keterangan Pindah Penduduk

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#2076]
### Bagaimana alurnya sampai muncul masalah?
Jalankan Surat Keterangan Pindah Penduduk

### Seperti apa yang diharapkan?
Menghasilkan surat dan lampiran seperti contoh terlampir.

### Apa yang terjadi?
Belum sepenuhnya sesuai.

### Informasi tambahan 
[Surat Keterangan Pindah Penduduk.zip](https://github.com/OpenSID/OpenSID/files/3244643/Surat.Keterangan.Pindah.Penduduk.zip)

Lihat juga #1937 -- apakah ada kesamaan,

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19.06
| Versi PHP        | 
| System operasi   |

**Comment by ariandii** [comment]
Berikut terlampir surat dimaksud:
[surat_ket_pindah_penduduk.zip](https://github.com/OpenSID/OpenSID/files/3365420/surat_ket_pindah_penduduk.zip)

**Comment by eddieridwan** [comment]
@ariandii , lampiran `f-1.25.php` perlu diubah sesuai contoh yang disediakan di atas.

**Comment by ariandii** [comment]
Lampiran `f-1.25.php` pada Surat Keterangan Pindah Penduduk.

[f-1.25.php.zip](https://github.com/OpenSID/OpenSID/files/3370666/f-1.25.php.zip)

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
