### ISSUE TITLE
Perbaikan Surat Permohonan Kartu Keluarga

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#2077]
### Bagaimana alurnya sampai muncul masalah?
Jalankan Surat Permohonan Kartu Keluarga

### Seperti apa yang diharapkan?
Menghasilkan surat dan lampiran seperti contoh terlampir.

### Apa yang terjadi?
Belum sepenuhnya sesuai.

### Informasi tambahan 
[Surat Permohonan Kartu Keluarga.zip](https://github.com/OpenSID/OpenSID/files/3244646/Surat.Permohonan.Kartu.Keluarga.zip)

Lihat juga #1720, apakah bisa digabungkan.

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19.06
| Versi PHP        | 
| System operasi   |

**Comment by ariandii** [comment]
Berikut terlampir ubahan Surat dimaksud:
[surat_permohonan_kartu_keluarga.zip](https://github.com/OpenSID/OpenSID/files/3365417/surat_permohonan_kartu_keluarga.zip)

**Comment by eddieridwan** [comment]
Ini sepertinya sudah sesuai permintaan.

**Comment by eddieridwan** [comment]
Karena yg di bawaan sistem sudah ok, saya tutup issue ini.
