### ISSUE TITLE
Perbaikan Surat Permohonan Perubahan Kartu Keluarga

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#2078]
### Bagaimana alurnya sampai muncul masalah?
Jalankan Surat Permohonan Perubahan Kartu Keluarga

### Seperti apa yang diharapkan?
Menghasilkan surat dan lampiran mengikuti contoh terlampir

### Apa yang terjadi?
Belum sepenuhnya sesuai

### Informasi tambahan 
[Surat Permohonan Perubahan Kartu Keluarga.zip](https://github.com/OpenSID/OpenSID/files/3244650/Surat.Permohonan.Perubahan.Kartu.Keluarga.zip)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19.06
| Versi PHP        | 
| System operasi   |

**Comment by ariandii** [comment]
Berikut terlampir ubahan Surat Permohonan Perubahan Kartu Keluarga:
[surat_permohonan_perubahan_kartu_keluarga.zip](https://github.com/OpenSID/OpenSID/files/3365410/surat_permohonan_perubahan_kartu_keluarga.zip)

**Comment by eddieridwan** [comment]
Ini sepertinya sudah sesuai permintaan.

**Comment by eddieridwan** [comment]
Karena surat bawaan sistem sudah sesuai dengan kebutuhan Desa Kumba (kecuali kop surat), issue ini saya tutup.
