### ISSUE TITLE
Penyesuaian Kop Surat semua surat

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#2079]
### Bagaimana alurnya sampai muncul masalah?
Cetak surat manapun

### Seperti apa yang diharapkan?
Kop surat mengikuti contoh terlampir

### Apa yang terjadi?
Belum sepenuhnya sesuai

### Informasi tambahan 

Contoh: 
[contoh penyesuain kop surat, nomor surat dan penanda tangan surat.zip](https://github.com/OpenSID/OpenSID/files/3244660/contoh.penyesuain.kop.surat.nomor.surat.dan.penanda.tangan.surat.zip)

Lihat juga #1711 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19.06
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Bandingkan dengan kop surat yang ada. Apakah kop surat yg diminta Desa Kumba dapat digunakan sebagai default untuk semua desa -- yaitu apakah lebih baik dari yang sudah ada? 

Apakah ada cara untuk memudahkan perubahan kop pada setiap surat?

**Comment by ariandii** [comment]
Saat ini untuk kop surat di Kabupaten kami, urutan kop surat:
Kabupaten
Kecamatan
Desa
Alamat

Berbeda dengan urutan pada contoh surat di atas.

**Comment by hasap86** [comment]
di kabupaten Sukabumi, Jawa Barat untuk Kop Surat ada 2 tipe, antara yg tanda tangan kepala desa dan bukan kepala desa berbeda, khusus kepala desa pake burung garuda

**Comment by hasap86** [comment]
Berikut terlampir Tata Naskah Dinas untuk Kop Surat sesuai yang menandatangani **Kepala Desa** dan **Sekretariat Desa**

**1. Kop Naskah Dinas Kepala Desa**
![Kop_Surat_Naskah_Dinas_Kepala_Desa](https://user-images.githubusercontent.com/45263721/59705948-a6b98000-9229-11e9-8498-3517e5f7a7d1.jpg)

**2. Kop Naskah Dinas Sekretariat Desa**
![Kop_Surat_Naskah_Dinas_Sekretariat_Desa](https://user-images.githubusercontent.com/45263721/59705994-b6d15f80-9229-11e9-93e3-ec714292ff08.jpg)

jadi harus cari cara bagaimana ketika beda penandatangan maka kop surat berbeda anatara kepala desa dan selain kepala desa

**Comment by eddieridwan** [comment]
Bung @ariandii , di master saya beri contoh kop surat `surat/raw/kop_surat.rtf` yang bisa diinsert ke template surat. Di Word, : 

1. copy contoh kop surat, buat kop surat baru
2. hapus kop surat di setiap surat yang akan diganti
3. insert file kop surat yg baru menggunakan menu Insert > File.
4. simpan

Sekarang di versi pra-rilis, logo default akan otomatis diganti dengan logo desa pada waktu mencetak surat. PERHATIAN: proses penggantian ini HANYA berlaku apabila kop surat berisi logo default bawaan sistem.

**Comment by hasap86** [comment]
Apakah kode insert alamat bisa dipisah saja supaya bisa disesuaikan dengan kebutuhan masing masing, karena di kabupaten sukabumi harus menyertakan alamat web, email, fax... atau bisa dijadikan default seperti contoh di atas yg saya sertakan....

**Comment by ariandii** [comment]
Penyesuaian semua surat bawaan sistem dengan kop surat Desa Kumba menggunakan contoh/surat/raw/kop_surat_desa_kumba.rtf 

[surat.zip](https://github.com/OpenSID/OpenSID/files/3316285/surat.zip)


> Bung @ariandii , di master saya beri contoh kop surat `surat/raw/kop_surat.rtf` yang bisa diinsert ke template surat. Di Word, :
> 
> 1. copy contoh kop surat, buat kop surat baru
> 2. hapus kop surat di setiap surat yang akan diganti
> 3. insert file kop surat yg baru menggunakan menu Insert > File.
> 4. simpan
> 
> Sekarang di versi pra-rilis, logo default akan otomatis diganti dengan logo desa pada waktu mencetak surat. PERHATIAN: proses penggantian ini HANYA berlaku apabila kop surat berisi logo default bawaan sistem.

**Comment by eddieridwan** [comment]
Bung @ariandii , karena Surat Keterangan Penghasilan Ayah, Surat Penghasilan Ibu dan Surat Pengantar Permohonan Penerbitan Buku Pas Lintas bawaan sistem telah diubah, versi dengan kop surat Desa Kumba perlu dibuat ulang. Terima kasih.

**Comment by ariandii** [comment]
Berikut 3 surat tersebut dengan menyesuaikan kop surat Desa Kumba.

[surat_update.zip](https://github.com/OpenSID/OpenSID/files/3332472/surat_update.zip)

**Comment by pemdestangkolo** [comment]
> Berikut terlampir Tata Naskah Dinas untuk Kop Surat sesuai yang menandatangani **Kepala Desa** dan **Sekretariat Desa**
> 
> **1. Kop Naskah Dinas Kepala Desa**
> ![Kop_Surat_Naskah_Dinas_Kepala_Desa](https://user-images.githubusercontent.com/45263721/59705948-a6b98000-9229-11e9-8498-3517e5f7a7d1.jpg)
> 
> **2. Kop Naskah Dinas Sekretariat Desa**
> ![Kop_Surat_Naskah_Dinas_Sekretariat_Desa](https://user-images.githubusercontent.com/45263721/59705994-b6d15f80-9229-11e9-93e3-ec714292ff08.jpg)
> 
> jadi harus cari cara bagaimana ketika beda penandatangan maka kop surat berbeda anatara kepala desa dan selain kepala desa



> Berikut terlampir Tata Naskah Dinas untuk Kop Surat sesuai yang menandatangani **Kepala Desa** dan **Sekretariat Desa**
> 
> **1. Kop Naskah Dinas Kepala Desa**
> ![Kop_Surat_Naskah_Dinas_Kepala_Desa](https://user-images.githubusercontent.com/45263721/59705948-a6b98000-9229-11e9-8498-3517e5f7a7d1.jpg)
> 
> **2. Kop Naskah Dinas Sekretariat Desa**
> ![Kop_Surat_Naskah_Dinas_Sekretariat_Desa](https://user-images.githubusercontent.com/45263721/59705994-b6d15f80-9229-11e9-93e3-ec714292ff08.jpg)
> 
> jadi harus cari cara bagaimana ketika beda penandatangan maka kop surat berbeda anatara kepala desa dan selain kepala desa

@hasap86 Apakah topik ini sudah terselesaikan ?

**Comment by eddieridwan** [comment]
> Berikut terlampir Tata Naskah Dinas untuk Kop Surat sesuai yang menandatangani **Kepala Desa** dan **Sekretariat Desa**
> 
> **1. Kop Naskah Dinas Kepala Desa**
> ![Kop_Surat_Naskah_Dinas_Kepala_Desa](https://user-images.githubusercontent.com/45263721/59705948-a6b98000-9229-11e9-8498-3517e5f7a7d1.jpg)
> 
> **2. Kop Naskah Dinas Sekretariat Desa**
> ![Kop_Surat_Naskah_Dinas_Sekretariat_Desa](https://user-images.githubusercontent.com/45263721/59705994-b6d15f80-9229-11e9-93e3-ec714292ff08.jpg)
> 
> jadi harus cari cara bagaimana ketika beda penandatangan maka kop surat berbeda anatara kepala desa dan selain kepala desa

Bung @hasap86, silakan buat issue baru untuk permintaan pembedaan kop surat.
Issue yg sekarang ini #2079 adalah khusus untuk permintaan Desa Kumba. Terima kasih.

**Comment by MUHAMMADRANGSEL** [comment]
untuk memudahkan desa dalam penyesuaian kop surat juga di File SURAT_MODEL perlu ada dibedakan antara [alamat_des] dengan [alamat_desa] dibuatkan terpisah seperti dibawah ini : 
                "[alamat_des]"        => $alamat_desa,
               "[alamat_desa]"       => "$config[alamat_kantor]",
                "[email_desa]"        => "$config[email_desa]",
                "[kode_desa]"         => "$config[kode_desa]",
                "[kode_kecamatan]"    => "$config[kode_kecamatan]",
                "[kode_kabupaten]"    => "$config[kode_kabupaten]",
                "[kode_pos]"          => "$config[kode_pos]",
                "[kode_provinsi]"     => "$config[kode_propinsi]",
                "[nama_des]"          => "$config[nama_desa]",
                "[nama_kab]"          => "$config[nama_kabupaten]",
                "[nama_kabupaten]"    => "$config[nama_kabupaten]",
                "[nama_kec]"          => "$config[nama_kecamatan]",
                "[nama_kecamatan]"    => "$config[nama_kecamatan]",
                "[nama_provinsi]"     => "$config[nama_propinsi]",
                "[nama_kepala_camat]" => "$config[nama_kepala_camat]",
                "[nama_kepala_desa]"  => "$config[nama_kepala_desa]",
                "[nip_kepala_camat]"  => "$config[nip_kepala_camat]",
                "[nip_kepala_desa]"   => "$config[nip_kepala_desa]",
                "[pos]"               => "$config[kode_pos]",
                "[telepon_desa]"      => "$config[telepon]",
                "[website_desa]"      => "$config[website]",

**Comment by MUHAMMADRANGSEL** [comment]
atau 
if (!empty($config[email_desa]))
				$alamat_des = "$config[alamat_kantor] Email: $config[email_desa] Kode Pos: $config[kode_pos]";
			else
				$alamat_desa = "$config[alamat_kantor] Kode Pos: $config[kode_pos]";

**Comment by eddieridwan** [comment]
@MUHAMMADRANGSEL , usul/permintaan anda mohon dimasukkan ke issue terpisah. Issue yg sekarang ini #2079 sebenarnya khusus terkait permintaan Desa Kumba. Terima kasih.

**Comment by eddieridwan** [comment]
Bung @ariandii , untuk menyelesaikan issue ini (dan semua permintaan Desa Kumba), mohon anda ulangi pembuatan perubahan semua template surat yang ada di rilis (sekarang semua surat baru/perubahan permintaan Desa Kumba sudah masuk rilis), menggunakan kop surat Desa Kumba. Yang perlu diubah hanya template rtf saja. 

Sesudah selesai lampirkan semua subfolder ubahan surat di sini untuk kita serahkan pada Desa Kumba, sehingga Desa Kumba dapat langsung memasukkan ke folder desa. Terima kasih.

**Comment by ariandii** [comment]
Terlampir seluruh template surat bawaan sistem yang sudah disesuaikan dengan kop surat Desa Kumba.

[surat.zip](https://github.com/OpenSID/OpenSID/files/3373705/surat.zip)

**Comment by eddieridwan** [comment]
Sudah diserahkan kepada Desa Kumba. 
Kalau nanti ada yg masih perlu disempurnakan, agar membuka issue baru.
