### ISSUE TITLE
Fitur: Tambah laporan Data Kepemilikan KTP dan KK

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#208]
Statistik > Statistik Kependudukan Bulanan

Desa di Kecamatan Gerung, Lombok Barat menerbitkan Laporan Data Kepemilikan KTP dan KK setiap bulan. Perlu diketahui informasi KTP-el diperoleh dari mana?

[Laporan KTP.pdf](https://github.com/eddieridwan/OpenSID/files/612488/Laporan.KTP.pdf)

**Comment by afri18** [comment]
kalau KTP-eL sulit untuk di lacak, karna warga langsung ke disdukcapil, yang tau hanya admin KTP-eL / Disdukcapil, karna desa nggak punya kewenangan , sungguh aneh kalau ada laporan KTP-eL

**Comment by afa28** [comment]
pak @eddieridwan, apakah issue ini masih diperlukan atau ada pembaharuan ???

**Comment by eddieridwan** [comment]
Saya tutup saja, karena sepertinya tidak ada yg memerlukan.
