### ISSUE TITLE
Perubahan semua lampiran surat

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#2082]
### Bagaimana alurnya sampai muncul masalah?
Cetak sembarang surat yang ada lampiran

### Seperti apa yang diharapkan?
Lampiran-lampiran surat ditambahkan Mengetahui Camat, dan di bagian Kepala desa ditambahkan Atas Nama (An.) atau Untuk Beliau (Ub.)

### Apa yang terjadi?
Belum sepenuhnya sesuai.

### Informasi tambahan 
Contoh: 
[contoh penyesuain kop surat, nomor surat dan penanda tangan surat.zip](https://github.com/OpenSID/OpenSID/files/3244670/contoh.penyesuain.kop.surat.nomor.surat.dan.penanda.tangan.surat.zip)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19.06
| Versi PHP        | 
| System operasi   |

**Comment by ariandii** [comment]
Untuk surat apa saja yang perlu ditambah mengetahui camat? karena ada beberapa surat yang secara umum tidak seharusnya ada tanda tangan camat.

**Comment by eddieridwan** [comment]
@ariandii , bukan surat, tetapi lampiran. Persisnya, lampiran sbb:

[Surat Keterangan Kelahiran.zip](https://github.com/OpenSID/OpenSID/files/3337164/Surat.Keterangan.Kelahiran.zip)
[Surat Keterangan Pindah Penduduk.zip](https://github.com/OpenSID/OpenSID/files/3337165/Surat.Keterangan.Pindah.Penduduk.zip)
[Surat Permohonan Kartu Keluarga.zip](https://github.com/OpenSID/OpenSID/files/3337166/Surat.Permohonan.Kartu.Keluarga.zip)
[Surat Permohonan Perubahan Kartu Keluarga.zip](https://github.com/OpenSID/OpenSID/files/3337167/Surat.Permohonan.Perubahan.Kartu.Keluarga.zip)

Maaf, kurang jelas penulisan issuenya.

**Comment by upperhead93** [comment]
yang perlu ditambahkan keterangan mengetahui camat ada di surat keterangan kelahiran dan surat keterangan pindah  penduduk pak,

**Comment by upperhead93** [comment]
di format asli memang tidak ada bagian mengetahui camatnya, tapi di capil kami diminta demikian,

**Comment by upperhead93** [comment]
iya pak, 2 lampiran itu. selain itu hnya struktur penanda tangananan surat sprti yg sudah di bpk buat,

**Comment by ariandii** [comment]
Berikut terlampir ubahan dengan menambah Mengetahui Camat.
1. Surat Keterangan Kelahiran:
[surat_ket_kelahiran.zip](https://github.com/OpenSID/OpenSID/files/3365402/surat_ket_kelahiran.zip)

2. Surat Keterangan Pindah Penduduk:
[surat_ket_pindah_penduduk.zip](https://github.com/OpenSID/OpenSID/files/3365403/surat_ket_pindah_penduduk.zip)

**Comment by eddieridwan** [comment]
Bung @ariandii , yg perlu ditambahkan 'Mengetahui Camat' adalah lampiran `f-2.01.php` dan `f-1.25.php`. Lihat contoh yg disediakan oleh @upperhead93 :

[surat_ket_kelahiran_6107076005990001_2019-03-11_6_lampiran.pdf](https://github.com/OpenSID/OpenSID/files/3367356/surat_ket_kelahiran_6107076005990001_2019-03-11_6_lampiran.pdf)
[surat_ket_pindah_penduduk_6107070708690001_2019-02-25_2_lampiran.pdf](https://github.com/OpenSID/OpenSID/files/3367357/surat_ket_pindah_penduduk_6107070708690001_2019-02-25_2_lampiran.pdf)

**Comment by ariandii** [comment]
Lampiran `f-2.01.php` dan `f-1.25.php`

[f-2.01.zip](https://github.com/OpenSID/OpenSID/files/3371082/f-2.01.zip)

[f-1.25.php.zip](https://github.com/OpenSID/OpenSID/files/3371087/f-1.25.php.zip)

**Comment by eddieridwan** [comment]
Saya akan tutup issue ini, karena menjadi duplikasi dengan issue untuk masing2 surat terkait.
