### ISSUE TITLE
Tidak bisa menampilkan bulan romawi untuk penomoran surat versi 19.06 pasca

### ISSUE THREAD

**Issue by WAHYUDIK** [OpenSID/OpenSID#2083]
### Bagaimana alurnya sampai muncul masalah?

Ketika ingin menampilkan bulan romawi pada penomoran surat tidak bisa, padahal di pengaturan aplikasi sudah ditambai [bulan_romawi].
### Seperti apa yang diharapkan?

bisa menampilkan bulan secara otomatis, sama halnya dengan tahun ketika exportdoc 
### Apa yang terjadi?

ketika sudah selesai menambah [bulan_romawi] di pengaturan aplikasi akan tetapi hasil exportdoc nya tidak menambilkan bulan romawi.
### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19.06 - Pasca
| Versi PHP        | 
| System operasi   |

**Comment by MUHAMMADRANGSEL** [comment]
untuk issue ini dia normal-normal saja
![gambar](https://user-images.githubusercontent.com/25834335/59270149-62efd500-8c83-11e9-91cf-eab93a3c9763.png)

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR #2089
