### ISSUE TITLE
Format Surat Permohonan Kartu Keluarga

### ISSUE THREAD

**Issue by sukrimalendra** [OpenSID/OpenSID#2084]
### Bagaimana alurnya sampai muncul masalah?
Di desa kami surat permohonan Kartu Keluarga tidak sesuai dengan yang ada di aplikasi.

### Seperti apa yang diharapkan?
Mohon dibuatkan surat Permohonan Kartu keluarga sebagaimana file yang terlampir di bawah ini
[surat_permohonan_kartu_keluarga.docx](https://github.com/OpenSID/OpenSID/files/3275264/surat_permohonan_kartu_keluarga.docx)

### Apa yang terjadi?
Pembuatan surat permohonan kartu keluarga pada aplikasi tidak bisa digunakan. mohon kepada master2 untuk membuatkan format seperti format pada file lampiran diatas.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by sukrimalendra** [comment]
Pengisian tidak menggunakan kode atau nomor

**Comment by ariandii** [comment]
bisa lampirkan contoh yang sudah terisi lengkap.

**Comment by MUHAMMADRANGSEL** [comment]
sangat beda sekali format yang ini

**Comment by sukrimalendra** [comment]
Ini contoh yang terisi lengkap mas **ariandii**
[KK Baru - PAKE UMUM.pdf](https://github.com/OpenSID/OpenSID/files/3276928/KK.Baru.-.PAKE.UMUM.pdf)

**Comment by ariandii** [comment]
> Ini contoh yang terisi lengkap mas **ariandii**
> [KK Baru - PAKE UMUM.pdf](https://github.com/OpenSID/OpenSID/files/3276928/KK.Baru.-.PAKE.UMUM.pdf)

Centang yang ada di bagian atas, apakah manual saja melalui .rtf yang sudah didownload?

**Comment by sukrimalendra** [comment]
Kalo boleh dibuat otomatis sesuai dengan KK yang di buat. Misal jika yang dibuat KK no. 1 yg dicentang berkas lampiran yg ada no. 1 nya saja. Tp kalo tidak memungkinkan biar nanti dicentang di rtfnya saja mas

**Comment by ariandii** [comment]
Sementara seperti ini pak.

[surat_permohonan_kk.zip](https://github.com/OpenSID/OpenSID/files/3281312/surat_permohonan_kk.zip)

**Comment by redjoel** [comment]
ada Lampiran F101 dan F115 setiap kali permohonan kartu keluarga dibuat, pak @sukrimalendra sayangnya format ini memang tidak menyatu dengan rtf. Bisa dipahami memang karena tidak setiap Desa diberikan tugas mengisi formulir formulir tersebut. seperti di area kami, desa hanya perlu mengajukan surat permohonan kk tanpa perlu lampiran untuk kemudian dibawa ke disdukcapil.

ada beberapa kekurangtan memang di isian form berbentuk pdf tersebut

**Comment by sukrimalendra** [comment]
Terimakasih banyak mas @ariandii ini sudah lebih dari cukup untuk pelayanan permohonan kami.

Siap mas @redjoel 
kalo gitu saya akan tutup isu ini.
