### ISSUE TITLE
Penambahan Kode PEM seharusnya tidak berlaku untuk semua surat

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#2085]
### Bagaimana alurnya sampai muncul masalah?
Untuk Versi 19.06-Pasca penambahan kode PEM langsung di menu Pengaturan/Aplikasi/format_nomor_surat dan settingan tersebut berlaku untuk semua surat yang ada, sedangkan untuk kode PEM tidak berlaku untuk semua surat karena ada kode lain seperti KESRA, TRANTIB dll sesuai kebutuhan desa
![gambar1](https://user-images.githubusercontent.com/25834335/59271331-2ec9e380-8c86-11e9-96f0-720cac9278eb.png)

### Seperti apa yang diharapkan?
Untuk Penambahan Kode PEM, KESRA, TRANTIB dan lainnya bisa di atur melalui MENU Layanan Surat/Pengaturan Surat
![gambar2](https://user-images.githubusercontent.com/25834335/59271594-bca5ce80-8c86-11e9-9f7e-f00d09b704d2.png)

Untuk mempermudah pemerintah desa terutama Operator Desa dalam menentukan kode yang akan ditaruhkan dimasing-masing surat

### Apa yang terjadi?
Belum bisa diterapkan disemua desa 

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by ariandii** [comment]
Di desa kami tidak menggunakan PEM pada penomoran surat pak,

Saran saya, coba pada pengaturan aplikasi cukup ditulis 

> [kode_surat]/[nomor_surat, 3]/[tahun]
(tanpa PEM),

dan bisa ditambahkan PEM,KESRA,TRANSTIB pada file .rtf nya diakhir penomoran.
Misalnya menjadi :

> [format_nomor_surat]_PEM

**Comment by roaddee** [comment]
Mungkin kalau kode PEM dan lain2 itu kebetulan letaknya di belakang memang bisa kita atur di file RTF, tp kalau seperti :
`[kode_surat]/[nomor_surat, 3]/PEM/[tahun]`
saya kira juga tidak bisa memisahnya, padahal kita juga berhadapan dengan 'mungkin' Perangkat desa yang tidak mau tahu, karena contoh dari Kabupaten setempat seperti itu

**Comment by MUHAMMADRANGSEL** [comment]
Kalau menurut saya lebih baik ditambahkan kolom satu lagi di pengaturan surat untuk kolom PEM,  KESRA dll

**Comment by MUHAMMADRANGSEL** [comment]
Shgg desa lebih mudah menentukan sendiri

**Comment by roaddee** [comment]
Kalau saya cenderung di pengaturan aplikasi untuk nomor surat ada 3 kolom dan masing2 kolom bisa diisi filed2 untuk penomoran surat, jadi PEM dan kawan2 itu bisa dimasukkan di sana, jadi :
form_penomoran_surat = `[kode_surat]/[nomor_surat, 3]/` `PEM` `/[tahun]`

**Comment by ariandii** [comment]
> Kalau saya cenderung di pengaturan aplikasi untuk nomor surat ada 3 kolom dan masing2 kolom bisa diisi filed2 untuk penomoran surat, jadi PEM dan kawan2 itu bisa dimasukkan di sana, jadi :
> form_penomoran_surat = `[kode_surat]/[nomor_surat, 3]/` `PEM` `/[tahun]`

untuk membedakan jenis surat apa saja yang masuk ke masing-masing kode tersebut bagaimana?

**Comment by roaddee** [comment]
intinya itu ini untuk mengakomodir usulan bang @MUHAMMADRANGSEL atau desa lain yang ingin ada atau tidak ada PEM dkk. jadi 3 kolom ini sama saja dengan 1 kolom karena yg nanti ditampilkan di surat adalah gabungan ketiganya, tidak terpisah. Jadi kalau ada desa yang mungkin di depan/tengah/belakang ada text yg tidak diakomodir oleh OpenSID, tinggal tambahin sendiri saja.
jadi tidak membedakan jenis surat.

**Comment by KASWANDI** [comment]
Harus diakomodir juga penggunaan kodes surat menggunakan bulan dalam angka romawi

**Comment by ariandii** [comment]
> Harus diakomodir juga penggunaan kodes surat menggunakan bulan dalam angka romawi

bulan dalam angka romawi sudah terwujud.

**Comment by roaddee** [comment]
iya, sy tidak lihat, ternyata sdh pull request, akhirnya saya batalkan pull request saya soal angka romawi

**Comment by MUHAMMADRANGSEL** [comment]
Untuk membedakan nya nanti desa sendiri sesuai dengan kondisi desa disuatu daerah masing2

**Comment by roaddee** [comment]
betul, karena tiap daerah tidak sama ......

**Comment by MUHAMMADRANGSEL** [comment]
Untuk memudahkan desa saja bang rudi spy nanti kalau dengan yng menggunakan kode PEM bisa diisi sendiri kalau tdk pakai tggl dikosongkan

**Comment by roaddee** [comment]
mungkin seperti ini ?
![penomoran_surat](https://user-images.githubusercontent.com/45786885/59400596-28408680-8dc2-11e9-95c6-311837706c9a.png)

**Comment by MUHAMMADRANGSEL** [comment]
Hari ini Kamis,  13 Juni 2019 kami menghadiri lokakarya dan menanyakan terkait penomoran surat,  dan untuk pemberian Kode PEM,  KESRA dll,  sudah tdk berlaku lagi, dN kode PEM,  KESRA cukup dgn kode klasifikasi surat

**Comment by MUHAMMADRANGSEL** [comment]
Sehingga saya secara pribadi menutup issue ini,

**Comment by roaddee** [comment]
Berarti, issue ini sudah tidak relevan lagi pak ?

**Comment by eddieridwan** [comment]
@MUHAMMADRANGSEL apa acuan peraturan yg mengatakan kode PEM, KESRA dsbnya tidak diperlukan lagi?
