### ISSUE TITLE
Terjadi Error saat memasukan tag HTML, dibagian current_version

### ISSUE THREAD

**Issue by orangmiliter** [OpenSID/OpenSID#2087]
### Bagaimana alurnya sampai muncul masalah?
mencoba memasukan tag html pada current version di menu setting aplikasi. 

### Seperti apa yang diharapkan?
memaksakan inputan int pada bagian `current_version`.

### Apa yang terjadi?
saat menyimpan website hanya menampilkan blank putih. contoh : `http://demo.opensid.my.id/`

### Informasi tambahan 
berikut kelengkapan screenshot : https://ibb.co/CQ2GM4r

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19.06
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Setting `current_version` telah dibuat _readonly_, karena memang tidak perlu diubah.
