### ISSUE TITLE
[Security] Stored XSS Pada judul berita di Menu Berita Desa

### ISSUE THREAD

**Issue by orangmiliter** [OpenSID/OpenSID#2090]
### Bagaimana alurnya sampai muncul masalah?
mencoba baris perintah `<h1>judul berita</h1>` pada judul berita di menu `Kategori Artikel > Berita Desa`

### Seperti apa yang diharapkan?
mencoba gunakan `html entities` untuk mengatasi masalah serangan `XSS`

### Apa yang terjadi?
halaman mengeksekusi dengan baik baris perintah `html` tanpa ada nya pembatasan

### Informasi tambahan 
berikut saya sertakan url foto [xss berita 1](https://ibb.co/kDBsCtw), [xss berita 2](https://ibb.co/RNRks5Z)
xss juga terjadi pada menu edit user [xss edite user](https://ibb.co/nMGkcGd)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19.06
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
