### ISSUE TITLE
Lambang Desa digunakan sebagai Favicon Web / Upload Tersendiri

### ISSUE THREAD

**Issue by hasap86** [OpenSID/OpenSID#2093]
### Bagaimana alurnya sampai muncul masalah?
Saat ini untuk gambar favicon harus upload melalui file hosting / cpanel

### Seperti apa yang diharapkan?
gunakan Lambang Desa di Identitas Desa sebagai Favicon

### Apa yang terjadi?
supaya mempermudah tampilan favicon

### Informasi tambahan 
Bisa juga ditambahkan fitur upload favicon tersendiri di menu Identitas Desa

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19.06
| Versi PHP        | 
| System operasi   |

**Comment by PWidodo** [comment]
Untuk favicon sebelum upload ke housting dirubah dahulu sesuai logo/lambang Kabupaten masing-masing. Ganti favicon asli yang ada pada folder Master OpenSID (htdoc)sbb:
![favicon](https://user-images.githubusercontent.com/45189822/60515197-52bc9a00-9d05-11e9-8ed0-f956f8294dc5.png)

**Comment by hasap86** [comment]
tiap update hatus merubah, sekaranng kebanyakan modelnya ambil dari logo default biar gak rubah rubah tiap update

**Comment by eddieridwan** [comment]
@hasap86 , saat ini favicon ubahan desa disimpan di file `desa/logo/favicon.ico` dan akan diambil otomatis oleh sistem. File ini akan aman dan tidak tertimpa pada waktu update.

Info ini sudah ada yg menambahkan di panduan https://github.com/OpenSID/OpenSID/wiki/Mengubah-favicon-logo-website-kecil-di-tab-browser. Kalau kurang jelas, silakan anda lengkapi info ini di panduan.

Tapi setuju usul anda untuk menyediakan menu untuk memudahkan pembuatan dan pengubahan favicon.

**Comment by uncu29** [comment]
logo diambli dari folder desa/logo sesuai dengan unggahan pada identitas desa->lambang desa
![Sistem Informasi Desa Desa Hibrida Jaya - Hom Desa - Konfigurasi - Mozilla Firefox 19_07_2019 21 52 39](https://user-images.githubusercontent.com/51182125/61544871-79eac980-aa70-11e9-9b27-89123ab09119.png)
![Sistem Informasi Desa Desa Hibrida Jaya - Hom Desa - Konfigurasi - Mozilla Firefox 19_07_2019 21 53 06](https://user-images.githubusercontent.com/51182125/61544873-7b1bf680-aa70-11e9-99e0-9d16591bb9fc.png)

**Comment by uncu29** [comment]
untuk mengubah header web dimana ya pak @eddieridwan tempat?
belum jumpa 
![Website Resmi Desa Hibrida Jaya - Mozilla Firefox 19_07_2019 22 09 55](https://user-images.githubusercontent.com/51182125/61545591-fe8a1780-aa71-11e9-85dd-61c3146f945d.png)

**Comment by eddieridwan** [comment]
@uncu29 kalau yg anda maksud adalah "bagaimana mengubah favicon yg tambil di tab browser?" jawabannya ada di panduan https://github.com/OpenSID/OpenSID/wiki/Mengubah-favicon-logo-website-kecil-di-tab-browser 

Jadi untuk issue ini, yang perlu dibuat adalah: pada saat mengunggah lambang desa, konversi lambang tersebut secara otomatis menjadi favicon untuk menggantikan `desa/logo/favicon.ico`.

**Comment by uncu29** [comment]
yang saya maksud ini pak.
![67043631_2645416785508179_1192664950120644608_n](https://user-images.githubusercontent.com/51182125/61575500-cf69b980-aaf6-11e9-84a5-95a1b48d113a.jpg)

**Comment by uncu29** [comment]
Maksudnya begini pak  ketika unggah lambang desa otomats logo diatas jga berubah menjadi logo kabupatennya. Kalau di opensidnya sdh ketemu scriptnya.

**Comment by uncu29** [comment]
jika maksud issue ini seperti gambar dibawah, ketika lambang desa diubah maka otomatis faviconnya juga ikut berubah.
![Sistem Informasi Desa Desa Hibrida Jaya - Hom Desa - Konfigurasi - Mozilla Firefox 19_07_2019 21 52 39](https://user-images.githubusercontent.com/51182125/61576114-e3fe7f80-aaff-11e9-93db-96b05243bb6a.png)
![Website Resmi Desa Hibrida Jaya - Mozilla Firefox 20_07_2019 14 50 46](https://user-images.githubusercontent.com/51182125/61576115-e52fac80-aaff-11e9-97e5-94b9ff05bdd9.png)
![Website Resmi Desa Hibrida Jaya - Mozilla Firefox 20_07_2019 14 51 23](https://user-images.githubusercontent.com/51182125/61576116-e52fac80-aaff-11e9-9f55-421e6aee1f59.png)

**Comment by eddieridwan** [comment]
Sudah dicommit ke master menggunakan solusi:

1. resize image menjadi 16 x 16
2. ganti nama file dan simpan sebagai `desa/logo/favicon.ico`.
