### ISSUE TITLE
Statistik Data Program Bantuan untuk di web munculkan data pesertanya

### ISSUE THREAD

**Issue by hasap86** [OpenSID/OpenSID#2094]
### Bagaimana alurnya sampai muncul masalah?
saat ini tidak ada informasi data pesertanya di Data Penerima Bantuan Web

### Seperti apa yang diharapkan?
Munculkan Data Penerima Bantuannya

### Apa yang terjadi?
Untuk Transparansi Masyarakat memantau layak & tidak layaknya

### Informasi tambahan 
Data Peserta yang disertakan
**No.** | **Nama Peserta** | **Nama Kepala Keluarga** | **Alamat**

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19.06
| Versi PHP        | 
| System operasi   |

**Comment by hasap86** [comment]
saat ini di rilis 20.05-pasca sudah terdapat daftar penerima bantuan namun dalam kelompok perorangan dan keluarga. Belum dimunculkan pada statistik Program Bantuan yang Per-program.

**Menu > Jenis Link Statistik Program Bantuan**

menu Statistik Program Bantuan ini lebih ke perprogram dan kiranya bisa dimunculkan Daftar Penerima Bantuannya.

**Comment by afa28** [comment]
Sudah di master

**Comment by hasap86** [comment]
Saya coba munculkan di menu penerima bantuan BPNT di, tapi tidak ada daftar pesertanya. mohon dicek ulang
