### ISSUE TITLE
Halaman Maintanance Mode

### ISSUE THREAD

**Issue by hasap86** [OpenSID/OpenSID#2095]
### Bagaimana alurnya sampai muncul masalah?
Belum ada halaman khusus Maintanance Mode

### Seperti apa yang diharapkan?
Saat kondisi di **Pengaturan** > **Aplikasi** > **offline_mode** kondisinya = **Web dan peta hanya bisa diakses admin/operator/redaksi**, maka ketika publik mengakses halaman website utama, **munculkan halaman Maintanance Mode** bahwa _Website Sedang dalam perbaikan, silahkan kembali lagi nanti dan menggunakan gambar simbol maintanance_.

### Apa yang terjadi?
Saat ini publik yang mengunjungi website dialihkan ke menu login admin

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19.06
| Versi PHP        | 
| System operasi   |

**Comment by junandia** [comment]
boleh dicoba pak, jika ingin meng custom silahkan edit file offline_mode.php
di folder : donjo_app/views/offline_mode.php
contoh offline mode yang saya buat :
![Screenshot_2019-07-04 Offline Mode - Desa Senggig1](https://user-images.githubusercontent.com/10545975/60658992-840ca580-9e7e-11e9-9b76-7ae06fa5b5cb.png)

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR #2095
