### ISSUE TITLE
Isian Form Tempat dilahirkan di Form Isian Penduduk perlu disesuaikan lagi dengan Surat Keterangan Lahir di Buku Posyandu

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#2096]
### Bagaimana alurnya sampai muncul masalah?
Pada waktu menambah anggota penduduk di Pilihan di form isian Tempat dilahirkan masih ada yang belum sesuai dengan Surat Keterangan Lahir yang ada di Buku Posyandu

### Seperti apa yang diharapkan?
Disesuaiakn dengan Surat Keterangan Lahir di Buku Posyandu
![form kelahiran](https://user-images.githubusercontent.com/25834335/59551012-942f1480-8fa5-11e9-9f49-2c9e7ede0d65.png)
![kelahiran](https://user-images.githubusercontent.com/25834335/59551013-942f1480-8fa5-11e9-8130-88938dde6ccf.png)

### Apa yang terjadi?
Belum Sesuai

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
Apakah ini masih bermasalah???

**Comment by MUHAMMADRANGSEL** [comment]
Bisa diclosed

Pada tanggal Sen, 24 Agt 2020 13.39, Andi Fahruddin Akas <
notifications@github.com> menulis:
