### ISSUE TITLE
Menambahkan Kategori Artikel di Menu Statis

### ISSUE THREAD

**Issue by hasap86** [OpenSID/OpenSID#2097]
### Bagaimana alurnya sampai muncul masalah?
Belum ada fasilitas menambahkan Kategori Artikel di Menu Statis

### Seperti apa yang diharapkan?
Bisa menambahkan Kategori Artikel di Menu Statis

### Apa yang terjadi?
SUpaya bisa dimunculkan di template yang Fitur Menunya hanya 1 Menu Statis

### Informasi tambahan 
Ketika Tambah Sub Menu Statis, pada saat pilih **Jenis Link**, munculkan link **Kategori Artikel**, kemudian ada pilihan lagi nama nama kategori artikelnya

![menu-kategori-artikel-statis](https://user-images.githubusercontent.com/45263721/59559481-42809b80-9032-11e9-822f-b577fa45256c.jpg)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19.06
| Versi PHP        | 
| System operasi   |

**Comment by PWidodo** [comment]
Bung Hasap86, Yang anda maksud mungkin Buat Menu Dinamis seperti Menu Statis yang dapat memilih Jenis Link kategori artikel, maaf kalau salah. Memang betul untuk MENU DINAMIS jenis link artikel terkaitnya sesuai judul Sub Menunya dan otomatis akan terinsert pada bagian ARTIKEL yang dengan nama yang sama dengan Sub Menunya.
![Menu Dinamis-1](https://user-images.githubusercontent.com/45189822/60516817-b1374780-9d08-11e9-82b4-a42ac7c0870b.png)
![Menu Dinamis-2](https://user-images.githubusercontent.com/45189822/60516843-bac0af80-9d08-11e9-9254-e708b62bea67.png)

**Comment by hasap86** [comment]
intinya supaya bisa menampilkan artikel berita sesuai kategori artikel pada template yang hanya memiliki 1 menu dan hanya menu Statis saja.

**Comment by afa28** [comment]
Mungkin maksunya menambahkan kategori artikel ke menu statis.

**Comment by lasnoeffendi** [comment]
> 
> 
> Bung Hasap86, Yang anda maksud mungkin Buat Menu Dinamis seperti Menu Statis yang dapat memilih Jenis Link kategori artikel, maaf kalau salah. Memang betul untuk MENU DINAMIS jenis link artikel terkaitnya sesuai judul Sub Menunya dan otomatis akan terinsert pada bagian ARTIKEL yang dengan nama yang sama dengan Sub Menunya.
> ![Menu Dinamis-1](https://user-images.githubusercontent.com/45189822/60516817-b1374780-9d08-11e9-82b4-a42ac7c0870b.png)
> ![Menu Dinamis-2](https://user-images.githubusercontent.com/45189822/60516843-bac0af80-9d08-11e9-9254-e708b62bea67.png)

Kalau menu dinamis tidak muncul ketika dipilih error dari apa ya pak @PWidodo 
![image](https://user-images.githubusercontent.com/66335570/93044196-56281100-f67e-11ea-8c69-0b7dacd5dca9.png)

untuk sekarang sudah bisa tambah kategori pak @hasap86 ?

**Comment by hasap86** [comment]
Belum ada pilihan Kategori Artikel di Menu Statis

![link-kategori-artikel](https://user-images.githubusercontent.com/45263721/97845264-f87b8100-1d1e-11eb-8805-a98c2913aedd.jpg)

**Comment by eddieridwan** [comment]
Harap bandingkan dulu dengan CMS lain, seperti Wordpress. Misalnya, apakah di Wordpress menu dapat mengarah ke kategori artikel? Kita perlu selalu berusaha supaya OpenSID tidak terlalu menyimpang dari kebiasaan/standar CMS lain yg umum digunakan.

**Comment by hasap86** [comment]
issue ini saya buat karena memang kebiasaan saya di CMS lain (Wordpress) seperti itu, sudah biasa menu mengarah ke kategori artikel, bahkan di wordpress bisa juga ke Tag.

**Comment by eddieridwan** [comment]
Kalau diterapkan, apakah akan ada perbedaan antara `menu statis` dan `menu dinamis`? Apakah tetap dipertahankan adanya `menu dinamis` yang hanya mengarah ke kategori artikel (tidak ke artikel statis)? Apakah `menu statis` menjadi `menu utama` (karena tidak lagi terbatas pada artikel statis)?

**Comment by hasap86** [comment]
untuk tema yang memiliki 2 lokasi menu mungkin berfungsi menu dimanis, tetapi yang hanya memiliki 1 menu statis saja, kemunculan menu kategori ini sangat diperlukan untuk memunculkan beberapa kategori artikel (berita berdasarkan kategori)

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3727
