### ISSUE TITLE
Tidak Bisa Mengubah Logo Pada Template Surat Sesuai Petunjuk

### ISSUE THREAD

**Issue by hasap86** [OpenSID/OpenSID#2099]
### Bagaimana alurnya sampai muncul masalah?
beberapa template surat pada Logo tidak bisa dirubah sesuai petunjuk, diantaranya:

1. surat_ket_wali_hakim.rtf
2. surat_ket_penghasilan_orangtua.rtf

### Seperti apa yang diharapkan?
seharusnya bisa dirubah sesuai petunjuk klik kanan di gambar > Change Picture > Pilih Logo desa > Insert.

### Apa yang terjadi?
tidak sesuai dengan petunjuk

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19.06
| Versi PHP        | 
| System operasi   |

**Comment by ariandii** [comment]
DIhapus saja logo yang ada, kemudian insert ulang dan sesuaikan ukurannya.

**Comment by hasap86** [comment]
ya betul, begitu yg saya lakukan, namun supaya seragam dengan template lain dan memudahkan bagi yg awam, lebih baik disamakan supaya bisa dirubah seperti yg lainnya.

**Comment by ariandii** [comment]
Bisa cek Issue Penyesuaian Kop Surat semua surat #2079 
Sembari nantinya untuk merapikan kop surat.

**Comment by eddieridwan** [comment]
@hasap86 di pra-rilis sekarang logo default (berbentuk rumah) diubah secara otomatis ke logo desa pada saat mencetak surat. Jadi sekarang logo default bisa dibiarkan saja di template rtf (tidak perlu diubah).

Issue ini saya tutup, ya.
