### ISSUE TITLE
Fitur: Tambah surat SPORADIK

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#210]
Tambah surat pernyataan penguasaan fisik bidang tanah (SPORADIK). Terlampir contoh dari Desa Dasan Tapen, Kecamatan Gerung, Lombok Barat.

![sporadik](https://cloud.githubusercontent.com/assets/249563/20618154/70dad6f4-b352-11e6-8e18-5bc3c067e142.jpg)

**Comment by MUHAMMADRANGSEL** [comment]
SIlahkan surat pernyataan penguasaan fisik bidang tanah (SPORADIK) digabung dirilis dan sudah saya buatkan form dan exportnya dan mohon juga kalau ada perlu penyesuaian disesuaikan lagi

[surat_sporadik_sertifikat.zip](https://github.com/OpenSID/OpenSID/files/1484382/surat_sporadik_sertifikat.zip)

**Comment by eddieridwan** [comment]
@MUHAMMADRANGSEL apakah Saksi1, Saksi2 selalu warga desa atau bisa dari luar desa?

**Comment by MUHAMMADRANGSEL** [comment]
Buatkan juga saksi dr luar mas

Pada tanggal 21 Nov 2017 12:48, "Eddie Ridwan" <notifications@github.com>
menulis:

**Comment by MUHAMMADRANGSEL** [comment]
Dan juga mas eddie tuk pemohon sproradik bukan hanya dari penduduk desa tp
ada juga penduduk dari luar desa

Pada tanggal 21 Nov 2017 12:49, "MUHAMMAD SPD" <muhammadrangsel@gmail.com>
menulis:

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.

Pemohon hanya bisa penduduk desa. Untuk opsi pemohon luar desa, perlu buat issue terpisah. Sudah ditambah sebagai bagian issue #650.
