### ISSUE TITLE
Data Peserta Bantuan Diisi Otomatis Sesuai Data Penduduk

### ISSUE THREAD

**Issue by hasap86** [OpenSID/OpenSID#2101]
![data-bantuan-diisi-otomatis](https://user-images.githubusercontent.com/45263721/59974484-e213d000-95d6-11e9-9d73-5662d2a68105.jpg)

### Bagaimana alurnya sampai muncul masalah?
Saat ini untuk mengisi data peserta bantuan harus manual, padahal datanya kebanyakan sama dengan data penduduk

### Seperti apa yang diharapkan?
data peserta penerima bantuan terisi otomatis sesuai data penduduk terpilih, namun tetap bisa dirubah sesuai kebutuhan jika ternyata data penduduk dan data kartu peserta berbeda

### Apa yang terjadi?
harus input manual padahal kebanyakan datanya sama

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19.06-pasca
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR #2112
