### ISSUE TITLE
[Bug] Jumlah Data pada Daftar Peserta Program Bantuan yang ditampilkan tidak berfungsi

### ISSUE THREAD

**Issue by hasap86** [OpenSID/OpenSID#2102]
![tampil-data-bantuan](https://user-images.githubusercontent.com/45263721/59975509-a1ba4f00-95e2-11e9-922c-7e218639a7af.jpg)

### Bagaimana alurnya sampai muncul masalah?
1. Klik menu _Bantuan_
2. Lihat rincian salah satu program bantuan
3. Tambahkan jumlah peserta sehingga melebihi 20
4. Di bagian bawah kiri, ubah tampilan untuk menampilkan 50 atau 100.

Saat memilih jumlah data peserta bantuan yang ditampilkan 50 atau 100 tampilan data tidak refresh dan tidak menampilkan jumlah data sesuai yang dipilih.

### Seperti apa yang diharapkan?
seharusnya jumlah data yang ditampilkan sesuai yang dipilih pada data yg ditampilkan

### Apa yang terjadi?
tidak sesuai fungsi

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19.06
| Versi PHP        | 
| System operasi   |

**Comment by kerupuksambel** [comment]
Bug tersebut terjadi karena adanya elemen `<form id="paging">` di dalam elemen `<form id="mainform">`, dan event trigger onchange di elemen `<select>` hanya akan mensubmit form paging, yang tidak dianggap valid di beberapa browser. 

Perbaikan dapat dilakukan dengan cara mengganti `$("#paging").submit()` dengan `$("#mainform").submit()`.

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR #2145
