### ISSUE TITLE
Tampilkan nama ibu kandung pada saat tambah peserta program bantuan

### ISSUE THREAD

**Issue by hasap86** [OpenSID/OpenSID#2103]
### Bagaimana alurnya sampai muncul masalah?
saat ini data nama ibu kandung tidak dimunculkan pada saat menambahkan peserta program bantuan

### Seperti apa yang diharapkan?
munculkan data nama ibu kandung saat menambahkan peserta program bantuan dan Daftar Peserta Program

### Apa yang terjadi?
untuk verifikasi data peserta kurang lengkap

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19.06-pasca
| Versi PHP        | 
| System operasi   |

**Comment by uncu29** [comment]
Apakah seperti ini maksud anda?
<br><br><img src="https://user-images.githubusercontent.com/51182125/60320806-11468a80-99a5-11e9-8990-0c086ff5f358.png" width="80%">

<br><br><img src="https://user-images.githubusercontent.com/51182125/60321158-2f60ba80-99a6-11e9-8001-c17916da7dbc.png" width="80%">

**Comment by eddieridwan** [comment]
@hasap86 apakah Nama Ibu Kandung informasi yg ada di kartu peserta? Atau apakah maksud anda informasi itu untuk membantu meyakinkan telah memilih penduduk yang benar?

**Comment by hasap86** [comment]
> @hasap86 apakah Nama Ibu Kandung informasi yg ada di kartu peserta? Atau apakah maksud anda informasi itu untuk membantu meyakinkan telah memilih penduduk yang benar?

tidak ada di kartu peserta, tetapi ada di daftar list peserta yang dipegang petugas, kemungkinan untuk verifikasi data.

**Comment by hasap86** [comment]
> Apakah seperti ini maksud anda?
> 
> 
> <img alt="" width="80%" src="https://user-images.githubusercontent.com/51182125/60320806-11468a80-99a5-11e9-8990-0c086ff5f358.png">
> 
> 
> 
> <img alt="" width="80%" src="https://user-images.githubusercontent.com/51182125/60321158-2f60ba80-99a6-11e9-8001-c17916da7dbc.png">

Benar seperti itu

**Comment by afa28** [comment]
Pak @eddieridwan, apakah ini perlu???

**Comment by eddieridwan** [comment]
Bung @hasap86 , apakah kebutuhan ini sdh terpenuhi dgn fitur bisa memilih istri/anak di program bantuan keluarga?

**Comment by afa28** [comment]
Apakah ditambahkan sebagai informasi untuk mengkonfirmasi kebenaran data peserta bantuan???

**Comment by eddieridwan** [comment]
@hasap86 @afa28 , untuk penerapan anda di #3496, perlu dibuat asumsi bahwa kolom `tweb_penduduk.nama_ibu` dan `tweb_penduduk.nama_ayah` (juga nik ayah/ibu) berisi data ibu dan ayah **kandung**. Jadi bukan ibu/ayah tiri/angkat. Selama ini penggunaan kedua kolom tersebut belum dibatasi demikian. Jadi selama ini bisa saja berisi data ibu/ayah tiri/angkat. 

Mohon anda segera mulai/pandu pembahasan di https://www.facebook.com/groups/OpenSID untuk mendapatkan persetujuan komunitas pengguna tentang hal ini. Dan setelah mendapatkan persetujuan, harap informasi ini segera ditambahkan ke panduan wiki -- supaya jelas dan tidak ada kekeliruan. 

Bung @afa28 , kalau disetujui komunitas pengguna, berarti setiap form perlu jelas bahwa nama/nik tersebut adalah untuk ayah/ibu kandung. 

Dengan demikian, kalau ada ayah/ibu tiri atau angkat, direkam hanya di kartu keluarga, melalui hubungan keluarga yg berlaku.

**Comment by eddieridwan** [comment]
@hasap86 @Nurhidayat29 : apakah pengertian data nik/nama ayah/ibu di tabel penduduk sudah dibahas di https://www.facebook.com/groups/OpenSID? Untuk mendapat persetujuan digunakan untuk `orang tua kandung`, bukan orang tua tiri/angkat. Kepastian itu diperlukan sebelum issue ini dapat diselesaikan.

**Comment by mizwaruddin** [comment]
Saya rasa ini tidak diperlukan.
