### ISSUE TITLE
[Bug] Hasil cetak dan unduh pada alamat rw,rt pada modul penduduk,modul keluarga, dan log penduduk tidak sama

### ISSUE THREAD

**Issue by benioke** [OpenSID/OpenSID#2105]
Bagaimana alurnya sampai muncul masalah?
Hasil cetak sama hasil undul di excel tidak sama pada nomor rw dan no rt nya
Ini gambar nya
1.hasil cetak keluarga
![cetak keluarga](https://user-images.githubusercontent.com/47577404/59979898-2d9a9e00-9618-11e9-9b0e-1a77bdc42e72.jpg)

  Hasil unduh keluarga
![unduh keluarga](https://user-images.githubusercontent.com/47577404/59979901-3db27d80-9618-11e9-9110-7e8c7c40dd5c.jpg)

2.hasil cetak penduduk
![cetak penduduk](https://user-images.githubusercontent.com/47577404/59979904-4c993000-9618-11e9-8593-5aff143c6027.jpg)

  Hasil unduh penduduk
![unduh penduduk](https://user-images.githubusercontent.com/47577404/59979908-5cb10f80-9618-11e9-9bf8-0e984a876822.jpg)

3.hasil cetak log penduduk
![cetak log](https://user-images.githubusercontent.com/47577404/59979914-6aff2b80-9618-11e9-9227-e003eef13570.jpg)

   Hasil unduh log penduduk
![unduh log](https://user-images.githubusercontent.com/47577404/59979917-73effd00-9618-11e9-8580-979b9249cb0e.jpg)

Seperti apa yang diharapkan?
Seharus nya hasil nya nya sama baik cetak maupun di unduh ke excel

Apa yang terjadi?
Berbeda hasil cetak dan hasil unduh untuk alamat rt dan rw nya

 Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19.06
| Versi PHP        | 
| System operasi   |

**Comment by uncu29** [comment]
Coba anda beri tanda ( ' ) seperti ini ('0), kemudian import lagi databasenya.

**Comment by benioke** [comment]
Bgaimana caranya..

**Comment by benioke** [comment]
Bgaimana caranya..

**Comment by benioke** [comment]
Ini spertinya bukan soal imporr pak..tapi hasil unduhan data nya..misalkan alamat saya rt 002/rw 003 di sistem..tapi hasil unduhan nya yang di conver kek .excel..menjadi rt 1/rw 2.itulah masalah nya..coba anda unduh data penduduk anda..liat perbedaan alamat rt dan rw nya

**Comment by benioke** [comment]
Ini spertinya bukan soal imporr pak..tapi hasil unduhan data nya..misalkan alamat saya rt 002/rw 003 di sistem..tapi hasil unduhan nya yang di conver kek .excel..menjadi rt 1/rw 2.itulah masalah nya..coba anda unduh data penduduk anda..liat perbedaan alamat rt dan rw nya

**Comment by uncu29** [comment]
iya pak sudah saya coba, kita tunggu para master untuk memperbaikinya.

**Comment by benioke** [comment]
Itu juga terjadi pada modul calon pemilih dan juga data rumah tangga..coba di cek mas..mana tw saya salah..coba unduh.liat hasil alamat rt rw nya...

**Comment by uncu29** [comment]
kemungkin untuk export yang ada RW dan RT nilainya seperti itu pak

**Comment by benioke** [comment]
Mudah mudahan aja pak eddie..kasih pencerahan

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
