### ISSUE TITLE
Tambah Fungsi Pencarian Data di Rincian Program Bantuan untuk beberapa data

### ISSUE THREAD

**Issue by hasap86** [OpenSID/OpenSID#2106]
### Bagaimana alurnya sampai muncul masalah?
Saat ini pencarian data di Rincian Program Bantuan hanya sebatas pencarian nama saja, tidak bisa melakukan pencarian data berdasarkan NIK, No KK atau Nomor Peserta.

### Seperti apa yang diharapkan?
bisa melakukan pencarian data berdasarkan NIK, No KK atau Nomor Peserta.

### Apa yang terjadi?
kendala pencarian data berdasarkan NIK, No KK atau Nomor Peserta.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19.06-pasca
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR #2146
