### ISSUE TITLE
Fitur: Tambah Surat Keterangan Domisili

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#211]
Tambah Surat Keterangan Domisili. Di bawah contoh dari Desa Dasan Tapen, Kecamatan Gerung, Lombok Barat.

![surat keterangan domisili](https://cloud.githubusercontent.com/assets/249563/20618250/dffdc9ba-b352-11e6-88fe-fd497bf084f0.jpg)

**Comment by MUHAMMADRANGSEL** [comment]
tuk surat domisili kami memakai ini dan silahkan mas eddie digabung di rilis 
[surat_ket_domisili.zip](https://github.com/OpenSID/OpenSID/files/1496144/surat_ket_domisili.zip)

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR #1729
