### ISSUE TITLE
(Bug)Hasil cetak dan unduh pada alamat rw,rt pada modul Calon Pemilih dan modul Rumah Tangga tidak sama

### ISSUE THREAD

**Issue by benioke** [OpenSID/OpenSID#2113]
Bagaimana alurnya sampai muncul masalah?
Terkait issues 2105 yang sudah di perbaiki.yang yg sama juga terjadi di modul Calon Pemilih dan modul Rumah Tangga.
Hasil cetak sama hasil undul di excel tidak sama pada nomor rw dan no rt nya
Ini gambar nya
1.Data Calon Pemilih
![data_calon_pemilih 1](https://user-images.githubusercontent.com/47577404/60304768-8d6cae00-9964-11e9-84aa-e66b4527f926.jpg)

  Hasil cetak Calon Pemilih
![cetak_calon_pemilih 1](https://user-images.githubusercontent.com/47577404/60304779-99587000-9964-11e9-9609-19681c05d74c.jpg)

  Hasil unduh Calon Pemilih
![unduh_calon_pemilih 1](https://user-images.githubusercontent.com/47577404/60304800-a70df580-9964-11e9-9275-6ba2214d286d.jpg)

2.Data Rumah Tangga
![data_rumah_tangga 1](https://user-images.githubusercontent.com/47577404/60304814-b42ae480-9964-11e9-91c1-bb87c3519107.jpg)

  Hasil cetak Rumah Tangga
![cetak_rumah_tangga 1](https://user-images.githubusercontent.com/47577404/60304846-d15fb300-9964-11e9-88bf-be36e422e8f4.jpg)

  Hasil unduh Rumah Tangga
![unduh_rumah_tangga 1](https://user-images.githubusercontent.com/47577404/60304861-d91f5780-9964-11e9-88c7-ea16469fadc1.jpg)

Seperti apa yang diharapkan?
Seharus nya hasil nya nya sama baik cetak maupun di unduh ke excel

Apa yang terjadi?
Berbeda hasil cetak dan hasil unduh untul alamat rt dan rw nya

Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19.06
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sdh dicommit ke master.
