### ISSUE TITLE
Ubah migrasi mengikuti standar Codeigniter

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#2115]
### Bagaimana alurnya sampai muncul masalah?
Saat ini migrasi menggunakan cara kustom yg tidak mengikuti standar codeigniter

### Seperti apa yang diharapkan?
Migrasi mengikuti standar codeigniter

### Apa yang terjadi?
Script untuk migrasi campur aduk dengan script lain di dalam file `Database_model.php`.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19.06
| Versi PHP        | 
| System operasi   |

**Comment by dikisiswanto** [comment]
pak @eddieridwan , apakah issue ini belum dikerjakan?
