### ISSUE TITLE
Alamat Sekarang dapat dihapus?

### ISSUE THREAD

**Issue by afri18** [OpenSID/OpenSID#2116]
### Bagaimana alurnya sampai muncul masalah?
sepertinya Alamat sekarang tidak berfungsi dengan fitur yang sekarang, agar tidak mubajir diganti saja dengan Memasukan Nomor Dokumen Surat Pindah dari Daerah asal dan mengupload dokumen tersebut sebagai arsip dan bukti kedatangan

### Seperti apa yang diharapkan?
kita bisa melihat dokumen kedatangan penduduk yang datang dan mengupload dokumennya

### Apa yang terjadi?
data akan lebih komplit

### Informasi tambahan 
![image](https://user-images.githubusercontent.com/6611881/60321788-eb6eb500-99a7-11e9-844d-cd1528da8c27.png)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by MUHAMMADRANGSEL** [comment]
Usulan bagus

**Comment by pemdestangkolo** [comment]
@afri18 itu SID versi berapa mas?

**Comment by eddieridwan** [comment]
@afri18 @MUHAMMADRANGSEL @pemdestangkolo : surat pindah dan surat kependudukan lainnya bisa diunggah melalui fitur yg sudah ada: `Upload Dokumen Penduduk`
![unggah-surat-pindah](https://user-images.githubusercontent.com/249563/62339294-d80eb680-b51e-11e9-8c13-c1e868e68b39.jpg)

**Comment by eddieridwan** [comment]
@afri18 , anda mengusulkan untuk kolom `Alamat Sekarang` untuk dihilangkan. Tetapi saat ini kolom itu digunakan untuk menyimpan alamat 'penduduk domisili', yaitu penduduk yg KK-nya bukan di desa. Berbeda dengan alamat penduduk yg KK-nya di desa, yaitu `Alamat KK`.

Jadi kolom itu tidak bisa dihapus dari tabel `tweb_penduduk`. Tapi mungkin bisa disembunyikan, yaitu tidak ditampilkan pada biodata penduduk yg KK-nya di desa.

**Comment by eddieridwan** [comment]
Sudah dicommit ke master sbb:
Alamat Sekarang disembunyikan, yaitu tidak ditampilkan pada biodata penduduk yg KK-nya di desa. Hanya ditampilkan bagi 'penduduk domisili' (penduduk yg KK-nya bukan di desa).

**Comment by afri18** [comment]
Atau tampilkan dokumen pendukung berikut nomornya agar saat entry data tidak bolak balik

**Comment by eddieridwan** [comment]
@afri18 issue ini sudah ditutup. Silakan buat issue baru kalau ada yg ingin diusulkan. Seperti biasa, pastikan melampirkan contoh tampakan layar untuk fitur yg diinginkan.
