### ISSUE TITLE
[Inventaris] Sesuaikan Pengguna Barang pada menu Inventaris

### ISSUE THREAD

**Issue by sukrimalendra** [OpenSID/OpenSID#2117]
### Bagaimana alurnya sampai muncul masalah?
Testing Menu Inventaris

### Seperti apa yang diharapkan?
Di Desa saya menganggarkan Barang untuk Puskesdes. Untuk pencatatan yang sesuai dengan keadaan, harapan saya isian Pengguna Barang bisa ditambah atau disesuaikan. 

### Apa yang terjadi?
tidak tersedianya penggunaan untuk Poskesdes

### Informasi tambahan 
![inventaris](https://user-images.githubusercontent.com/30992964/60379133-7d81c680-9a57-11e9-85a4-d45f79541ad8.PNG)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19.06-pasca
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Solusi untuk issue ini perlu merombak cara pengelolaan daftar penggunaan inventaris. Saat ini menggunakan copas, sehingga duplikasi dan rentan kesalahan. Solusinya perlu mengelola daftar penggunaan di satu tempat, sehingga mudah diubah atau ditambah.

**Comment by afa28** [comment]
Apakah ini masih bermasalah???
