### ISSUE TITLE
[BUG] XSS di Form Nama Pengguna

### ISSUE THREAD

**Issue by mugi789** [OpenSID/OpenSID#2118]
### Bagaimana alurnya sampai muncul masalah?
Pertama login dulu ke admin page
![gambar](https://user-images.githubusercontent.com/32443765/60384979-560a1880-9aae-11e9-82c8-332d8009ee7d.png)
Kedua klik pengaturan pengguna yg ada di pojok kanan atas, lalu ganti kata Administrator dengan **<script>alert("XSS")</script>**
![gambar](https://user-images.githubusercontent.com/32443765/60385009-b13c0b00-9aae-11e9-9b11-68854f297f82.png)
![gambar](https://user-images.githubusercontent.com/32443765/60385014-bb5e0980-9aae-11e9-9450-574b7251c8c7.png)
Lalu terkahir klik _Simpan_

### Apa yang terjadi?
Bila mengakses halaman utama ataupun yg lainnya akan muncul popup seperti ini
[http://demo.opensid.my.id/index.php/first](http://demo.opensid.my.id/index.php/first)
![gambar](https://user-images.githubusercontent.com/32443765/60385052-522ac600-9aaf-11e9-99f1-59bbbfd35308.png)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19.06-pasca
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
