### ISSUE TITLE
[Template Surat] Tambah surat SKTM

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#212]
Tambah Surat Keterangan Tidak Mampu (SKTM). Berikut contoh dari Desa Dasan Tapen, Kecamatan Gerung, Lombok Barat.

![sktm](https://cloud.githubusercontent.com/assets/249563/20618331/411be902-b353-11e6-95b5-529a327c4a4d.jpg)

**Comment by ariandii** [comment]
pada contoh surat ini dibuat oleh dusun dan diketahui kepala desa, 

surat yang akan dibuat apakah begitu atau langsung ttd kepala desa saja?

**Comment by balongbesuk** [comment]
outdate bs s close
