### ISSUE TITLE
Tambahkan surat kuasa

### ISSUE THREAD

**Issue by R4HMAT** [OpenSID/OpenSID#2123]
Silahkan untuk dibuatkan surat kuasa yang pemberi dan penerima harus ada opsi warga dan non warga template yang ada cuman penerima kuasa aja yang ada opsi non warganya.
![keluh2](https://user-images.githubusercontent.com/43318683/60396099-5c100000-9b67-11e9-858e-43fcea9540e2.png)

**Comment by roaddee** [comment]
Apakah pemberi kuasa dari luar desa ?, kalau memang iya, apakah sesuai Kantor Desa memberikan Surat Kuasa untuk orang yang bukan Warga nya ?

**Comment by R4HMAT** [comment]
Memang kita tidak bolh membuatkn warga itu jika pemberi kuasa dari luar
desa akan tetapi knp saya minta utk dibuatkan pemberi kuasa ada non warga
di karenakn ketika warga yg dibuatkn surat kuasa tidak ada datanya kan bisa
diketikan di surat tersebut.

Pada tanggal Min, 7 Jul 2019 19:38, Rudi Purwanto <notifications@github.com>
menulis:

**Comment by roaddee** [comment]
oke coba sy buatkan, semoga cepat selesai, hahahah

**Comment by R4HMAT** [comment]
Shipp.. makash sebelumnya.

Pada tanggal Min, 7 Jul 2019 20:49, Rudi Purwanto <notifications@github.com>
menulis:

**Comment by roaddee** [comment]
tapi kok saya cari di folder surat tidak ada surat kuasa ya ? apa itu dulunya buatan sendiri atau surat bawaan system opensid, karena saya tidak menemui surat kuasa di system opensid

**Comment by R4HMAT** [comment]
Ntr ta kirimin format suratnya iya.

Pada tanggal Sen, 8 Jul 2019 07:36, Rudi Purwanto <notifications@github.com>
menulis:

**Comment by R4HMAT** [comment]
Pada tanggal Sen, 8 Jul 2019 pukul 07.02 rahmat jumhur <
rahmatjumhur92@gmail.com> menulis:

**Comment by R4HMAT** [comment]
ne model surat kuasanya.

Pada tanggal Sen, 8 Jul 2019 pukul 13.38 rahmat jumhur <
rahmatjumhur92@gmail.com> menulis:

**Comment by R4HMAT** [comment]
![kuasa contoh](https://user-images.githubusercontent.com/43318683/60788054-f1be1780-a185-11e9-98d1-462479a22917.png)

ne contoh surat kuasanya.

**Comment by R4HMAT** [comment]
ne master suratnya

Pada tanggal Sen, 8 Jul 2019 pukul 13.39 rahmat jumhur <
rahmatjumhur92@gmail.com> menulis:

**Comment by roaddee** [comment]
sudah selesai, tapi saya cobanya dulu

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR #2148.

Tapi mohon perhatian @R4HMAT @roaddee: kalau memang pemberi kuasa HARUS warga desa, maka SEHARUSNYA surat kuasa ini tidak memberi opsi memilih pemohon yg belum terdata. 

Prosedur yg SEHARUSNYA teman2 ikuti adalah: apabila pemberi kuasa belum ada di database, maka MASUKKAN dulu sebelum membuat surat. Hanya dengan cara itulah data penduduk desa akan lengkap. Kalau teman2 hanya mengisi di form surat, data penduduk tersebut tidak akan masuk ke database penduduk.
