### ISSUE TITLE
Tanggal lahir penduduk dengan tanggal lahir pada kartu identitas penduduk otomatisnya pada Data Peserta Bantuan tidak sama

### ISSUE THREAD

**Issue by benioke** [OpenSID/OpenSID#2124]
Bagaimana alurnya sampai muncul masalah?
Berbeda tanggal lahir penduduk dengan tanggal lahir kartu identitas penduduk nya
![1](https://user-images.githubusercontent.com/47577404/60403485-37984000-9bc8-11e9-96e8-29ac1b74acca.JPG)

Seperti apa yang diharapkan?
Seharus nya hasil nya sama

Apa yang terjadi?
Harus di ubah manual pada tanggal lahir di kartu identitas

 Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19.06 pasca
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
