### ISSUE TITLE
Format tanggal lahir pada kartu identitas penduduk Y-m-d

### ISSUE THREAD

**Issue by benioke** [OpenSID/OpenSID#2125]
Bagaimana alurnya sampai muncul masalah?

Format tanggal lahir penduduk di kartu identitas penduduk pada daftar peserta program sekarang ini adalah Y-m-d
![2](https://user-images.githubusercontent.com/47577404/60403625-dd987a00-9bc9-11e9-8d36-b5b6085a4136.JPG)

Seperti apa yang diharapkan?

 Di ubah dengan format d-m-Y

 Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19.06 pasca
| Versi PHP        | 
| System operasi   |

**Comment by uncu29** [comment]
Coba ganti pengaturan tanggal di PC atau smartphone anda.

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
