### ISSUE TITLE
[Bug] Data List RW Tidak Muncul

### ISSUE THREAD

**Issue by pemdestangkolo** [OpenSID/OpenSID#2126]
### Bagaimana alurnya sampai muncul masalah?
Ketika menambahkan data penduduk baru di http://localhost/opensid/index.php/penduduk/form dan data keluarga baru di http://localhost/opensid/index.php/keluarga/form, setelah memilih nama Dusun, data list (pilihan) RW tidak muncul.

![IMG1](https://user-images.githubusercontent.com/52306493/60563953-04041400-9d88-11e9-8efc-5104ce76c85b.jpg)

### Seperti apa yang diharapkan?
Pilihan RW harus muncul untuk selanjutnya memilih kolom RT, seperti halnya ketika melakukan filter di halaman "Data Penduduk".

![img2](https://user-images.githubusercontent.com/52306493/60564068-85f43d00-9d88-11e9-9a6e-19dfc92db022.JPG)

### Apa yang terjadi?
Tidak dapat melakukan penyimpanan data.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19.06
| Versi PHP        | 4.3.11
| System operasi   | Windows 8.1 Pro x32

**Comment by uncu29** [comment]
Di OpenSID saya muncul pak setelah pilih dusun kemudian RW->RT, di wilayah administratif apakah muncul untuk daftar RW?
jika tidak coba bapak lakukan impor ulang dan isi manual RW dan RT atau COPY PASTE.

**Comment by pemdestangkolo** [comment]
> Di OpenSID saya muncul pak setelah pilih dusun kemudian RW->RT, di wilayah administratif apakah muncul untuk daftar RW?
> jika tidak coba bapak lakukan impor ulang dan isi manual RW dan RT atau COPY PASTE.

@uncu29 Form Wilayah Administratif sudah diisi. Mulai dari Dusun -> RW -> RT.

![img4](https://user-images.githubusercontent.com/52306493/60769655-b1ff1d80-a0fc-11e9-9717-a067783e41cc.jpg)
![img5](https://user-images.githubusercontent.com/52306493/60769656-b297b400-a0fc-11e9-8d70-32030d3938e8.jpg)

Keterangan yg saya beri tanda panah apakah tidak mempengaruhi ?

**Comment by eddieridwan** [comment]
@pemdestangkolo : apakah masalah ini masih ditemukan pada v19.08? 
Kalau masih bermasalah, mohon lampirkan isi tabel `tweb_wil_clusterdesa` untuk dipelajari.

**Comment by agungsugiarto** [comment]
Saya tidak menemukan masalah ini di https://demo.opensid.my.id, untuk petujuk menambahkan rw dan rt bisa dilihat disini https://github.com/OpenSID/OpenSID/wiki/Wilayah-Administratif

**Comment by sup-ham** [comment]
yang terbaru tidak ditemukan masalah ini. mungkin bisa ditutup saja.

**Comment by afa28** [comment]
Pak @eddieridwan , ini mungkin sudah bisa di close.
