### ISSUE TITLE
[Bug] Tampilan Tanggal Lahir di Menu Bantuan Sasaran Keluarga tidak sesuai

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#2127]
### Bagaimana alurnya sampai muncul masalah?
Menu Bantuan ==> Rincian Program Bantuan==> Sasaran Kepala Keluarga (KK) tanggal lahir yang muncul 47--1-12-1 yang seharusnya 12-11-1947

![Bantuan Keluarga](https://user-images.githubusercontent.com/25834335/60604545-82919d80-9dea-11e9-9cb4-354f2214c2c8.png)

### Seperti apa yang diharapkan?
Tampilan Tanggal Lahir dengan Format DD-MM-YYYY (12-11-1947)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by MUHAMMADRANGSEL** [comment]
Untuk Sasaran Penduduk, Rumah Tangga dan Kelompok/Organisasi Kemasyarakatan tampilannya sudah benar/ PAS

**Comment by junandia** [comment]
boleh dicoba ini pak
https://github.com/junandia/OpenSID/commit/2cdf39f8206b81ba6efac73661bbe61387aac69a

**Comment by eddieridwan** [comment]
Masalahnya adalah karena `tgl_indo_out()` dilakukan dua kali pada kartu tanggal lahir sasaran Keluarga. Perbaikan yg dilakukan sekalian merombak `Program_bantuan_model->get_program()` supaya lebih mudah dimengerti dan diperbaiki.

Telah dicommit ke master.
