### ISSUE TITLE
[Template Surat] Tambah surat pertanggung jawaban/izin orang tua/wali

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#213]
Surat Pertanggung Jawaban/Izin Orang Tua/Wali dikeluarkan oleh Desa Dasan Tapen, Kecamatan Gerung, Lombok Barat.

Apakah desa lain juga menerbitkan surat serupa. Ada contoh lainnya?

![surat izin orang tua](https://cloud.githubusercontent.com/assets/249563/20618408/bd9a4500-b353-11e6-9339-21b8352f18e5.jpg)

**Comment by andifahruddinakas** [comment]
Sudah bisa tambahkan melalu surat TinyMCE, namun masih perlu ditambahkan kode isian kepala dusun/rt/rw.

https://github.com/OpenSID/OpenSID/issues/6592
