### ISSUE TITLE
Error Path Upload file

### ISSUE THREAD

**Issue by garras16** [OpenSID/OpenSID#2131]
### Bagaimana alurnya sampai muncul masalah?
Saat mencoba upload file ke sistem, selalu error karena link menjadi c:\fakepath.
Sistem yang digunakan menggunakan linux.

### Seperti apa yang diharapkan?
Link upload file bisa menyesuaikan linux maupun windows

### Apa yang terjadi?
File salah format, atau salah link pada sistem operasi linux

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19.07
| System operasi   | Linux

**Comment by roaddee** [comment]
ini yang di facebook kan ? sepertinya sudah terselesaikan.

**Comment by nurjazim** [comment]
kirimkan link solve masalah ini yg di facebook gan, ane cari di grup gak ketemu.

**Comment by afa28** [comment]
Pak @eddieridwan , apa ini perlu di close???

**Comment by nurjazim** [comment]
kalau ada link atau tutorial buat solve masalah ini bisa di close, saya belum menemukan solusinya.
