### ISSUE TITLE
Hilangkan `DEFINER=...` di sql saat impor database

### ISSUE THREAD

**Issue by sup-ham** [OpenSID/OpenSID#2133]
### Apa yang terjadi?
Ketika admin Opensid akan melakukan backup database maka kemungkinan bisa melalui fitur ekspor, atau yang lainnya seperti phpmyadmin dan sejenisnya. 
Saat mengimpor kembali database melalui fitur impor database beberapa dilaporakan error seperti #1779, #2104, #3. Itu karena pada file hasil backup biasanya berisi ```DEFINER=`root`@`localhost``` yang menyebabkan error saat mengimpornya.

### Bagaimana alurnya sampai muncul masalah?
Sebaiknya dibuat di kode saja untuk menghilangkan ```DEFINER=`root`@`localhost```` sebelum mengimpornya.

### Informasi tambahan 
- Solusinya masih manual, tertuang pada dokumentasi wiki: [T: Error import menggunakan phpmyadmin](https://github.com/OpenSID/OpenSID/wiki/Tanya-Jawab-Install-dan-Update#t-error-import-menggunakan-phpmyadmin).
- Sudah diterapkan juga (saat issu ini dibuat) proses menghilangkan ```DEFINER=`root`@`localhost` ``` saat  mengekspor database https://github.com/OpenSID/OpenSID/blob/416e4d9d127ea956f316d7a531908656d2674c43/donjo-app/models/Export_model.php#L123
- https://hemantnemade.wordpress.com/2013/07/12/fixphpmyadmin-error-1227-access-denied-you-need-at-least-one-of-the-super-privileges-for-this-operation/

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | *
| System operasi   | *

**Comment by roaddee** [comment]
saya lihat hasil export sudah tidak ada DEFINER nya

**Comment by eddieridwan** [comment]
Sekarang di master hasil ekspor phpmyadmin dapat di-restore menggunakan menu _Pengaturan > Database > Restore_
