### ISSUE TITLE
Jumlah KK tidak bertambah dan tidak tampil di keluarga setelah pecah KK

### ISSUE THREAD

**Issue by uncu29** [OpenSID/OpenSID#2134]
### Apa yang terjadi?
Jumlah KK tidak bertambah dan tidak tampil di keluarga setelah pecah KK

### Bagaimana alurnya sampai muncul masalah?
Ketika pecah KK, penduduk yang dipecah KK tidak tampil di Keluarga dan jumlah Keluarga tidak bertambah.

### Seperti apa yang diharapkan?
otomatis tampil di Keluarga dan bertambah jumlah Keluarga.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19.07
| Versi PHP        | 
| System operasi   |

**Comment by benioke** [comment]
Screenshot masalah.nya..kirim.gambar nya nya.kurang paham
