### ISSUE TITLE
Alamat desa di Kop surat agar tidak menampilkan email

### ISSUE THREAD

**Issue by WAHYUDIK** [OpenSID/OpenSID#2138]
### Bagaimana alurnya sampai muncul masalah?
Ketika exportdoc alamat desa di kop surat isinya tidak hanya alamat saja, akan tetapi ikut ditampilkan email desa

### Seperti apa yang diharapkan?
untuk alamat desa yang dikop surat agar dibuatkan 2 baris. yakni baris 1 berisi alamat, nomor telpon dan kode pos saja, baris ke 2 berisi website dan email desa.

### Apa yang terjadi?
yang tampil berisi alamat,email dan kode pos

### Informasi tambahan 
![image](https://user-images.githubusercontent.com/31026980/60933655-70819480-a2ed-11e9-97b2-42530ef67571.png)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19.07
| Versi PHP        | 
| System operasi   |

**Comment by PWidodo** [comment]
Di buat sendiri bisa pak, misal seperti gambat dibawah ini :
![Screenshot_10](https://user-images.githubusercontent.com/45189822/60967146-24157380-a344-11e9-9c79-ca5a63d70d24.png)

**Comment by PWidodo** [comment]
Dan Hasilnya seperti ini :
![Screenshot_11](https://user-images.githubusercontent.com/45189822/60967377-b3228b80-a344-11e9-9a15-015659851458.png)

**Comment by ariandii** [comment]
Untuk menerapkan alamat Kop Surat sesuai yang diharapkan issue ini, dapat menggunakan kode isian [alamat_surat] pada template rtf.

![2](https://user-images.githubusercontent.com/46939846/60989239-98194100-a36f-11e9-8dd2-4e097be4e8b4.png)

**Comment by ariandii** [comment]
atau bisa juga menggunakan kode isian unit terkecil dari masing-masing yang diperlukan. Sudah ditambah kode isian baru [alamat_kantor] sesuai alamat pada identitas desa.

Seperti contoh berikut. 

![IMG_20190711_002425_233](https://user-images.githubusercontent.com/46939846/60990337-635ab900-a372-11e9-8672-7152e643a98a.jpg)

**Comment by WAHYUDIK** [comment]
terima kasih

**Comment by redjoel** [comment]
Saya setuju untuk dibuatkan 2 baris

**Comment by R4HMAT** [comment]
ini pakai versi brp sidnya agar bisa pakai kode seperti ini @
![60990337-635ab900-a372-11e9-8672-7152e643a98a](https://user-images.githubusercontent.com/43318683/61062835-230a4200-a429-11e9-9dff-11f6ca22381b.jpg)

**Comment by R4HMAT** [comment]
padahal udah di ganti di rtf surat tapi alamat kantor ndk berubah. ini edit rtf dan hasil expor surat Docnya.
![kl2](https://user-images.githubusercontent.com/43318683/61092162-638cae80-a46f-11e9-8edc-b78f864ec197.png)
![kl1](https://user-images.githubusercontent.com/43318683/61092190-84ed9a80-a46f-11e9-94b7-0b37dcee471f.png)

**Comment by R4HMAT** [comment]
saya pakai OPENSID Versi 19.07 Pasca.

**Comment by ariandii** [comment]
> padahal udah di ganti di rtf surat tapi alamat kantor ndk berubah. ini edit rtf dan hasil expor surat Docnya.
> ![kl2](https://user-images.githubusercontent.com/43318683/61092162-638cae80-a46f-11e9-8edc-b78f864ec197.png)
> ![kl1](https://user-images.githubusercontent.com/43318683/61092190-84ed9a80-a46f-11e9-94b7-0b37dcee471f.png)

Cermati sebelum komentar.

![3](https://user-images.githubusercontent.com/46939846/61095836-4069fb00-a47f-11e9-831b-855ad57b6d87.png)

**Comment by eddieridwan** [comment]
Kode isian [alamat_surat] dan [alamat_kantor] sudah dicommit ke master. Mohon ada yg melengkapi panduan https://github.com/OpenSID/OpenSID/wiki/Kode-Isian-Template-Surat menambahkan kedua kode isian tersebut.

**Comment by R4HMAT** [comment]
ariandii@ salah kirim tyu screnshotnya. emang utk alamat kantor tidak bisa berubah tetap dia walapun udh di ganti di rtf suratnya.
![kl2](https://user-images.githubusercontent.com/43318683/61120352-01f82e80-a4c7-11e9-8a04-11f3da6d1f9f.png)
![kl3](https://user-images.githubusercontent.com/43318683/61120361-07ee0f80-a4c7-11e9-9fa2-2cf9f76c867c.png)

**Comment by ariandii** [comment]
Silakan dicoba dengan menggunakan OpenSID 19.07-pasca terbaru.

**Comment by R4HMAT** [comment]
Oke.

Pada tanggal Jum, 12 Jul 2019 18:21, Ariandi Ryan Kahfi <
notifications@github.com> menulis:

**Comment by R4HMAT** [comment]
berhasil 👍

Pada tanggal Jum, 12 Jul 2019 pukul 18.25 rahmat jumhur <
rahmatjumhur92@gmail.com> menulis:
