### ISSUE TITLE
[Template Surat] Tambah surat SPTJM

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#214]
Blanko SPTJM dikeluarkan oleh Disdukcapil. Saat ini biasanya ditulis tangan. 

* Menurut Muhammad Zainaini, desa sebaiknya punya format sptjm...karena peristiwa penting yg tercatat di sptjm.jg seharusnya tercatat di desa.
* Syafri mengusulkan sebaiknya sid menyediakan fitur surat sejenis, nantinya biar pengguna yg edit d doc.rtf

Dua jenis SPTJM terlampir. Belum diketahui apakah ada yang lain.

![sptjm 2](https://cloud.githubusercontent.com/assets/249563/20618537/808bae14-b354-11e6-9ad2-8369701b2874.jpg)
![sptjm 1](https://cloud.githubusercontent.com/assets/249563/20618538/808bcb10-b354-11e6-872a-55c83d9d61c3.jpg)

**Comment by MUHAMMADRANGSEL** [comment]
Blangko yang diatas sesuai dengan PERATURAN MENTERI DALAM NEGERI REPUBLIK INDONESIA NOMOR 9 TAHUN2016 TENTANG PERCEPATAN PENINGKATAN CAKUPAN KEPEMILIKAN AKTA KELAHIRAN dan sudah baku dan ini juga perlu segera dimasukkan di release dan dengan ini kami lampirkan yang berbentuk docx
[SPTJM.zip](https://github.com/OpenSID/OpenSID/files/1454415/SPTJM.zip)

**Comment by MUHAMMADRANGSEL** [comment]
[surat_pernyataan_tanggung_jawab_mutlak_kelahiran_.zip](https://github.com/OpenSID/OpenSID/files/1500411/surat_pernyataan_tanggung_jawab_mutlak_kelahiran_.zip)

**Comment by MUHAMMADRANGSEL** [comment]
untuk SPTJM ini kami sudah buat untuk lombok timur dan kalau masih ada yang belum pas mas eddie mohon di perbaiki : 
1. SPTJM Kebenaran Data Kelahiran
2. SPTJM Kebenaran Pasangan Suami Istri
[surat.zip](https://github.com/OpenSID/OpenSID/files/1685912/surat.zip)

**Comment by MUHAMMADRANGSEL** [comment]
dan setelah kami konsultasikan kepihak DUKCAPIL ternyata SPTJM digunakan untuk pengurusan pembuatan akta kelahiran.
1, Ketika tidak bisa menunjukkan surat keterangan kelahiran maka dibuatkan SPTJM kebenaran Data Kelahiran
2. Ketika tidak bisa menunjukkan Buku Nikah maka dibuatkan SPTJM Kebenaran sebagai pasangan suami istri 
Format SPTJM tersebut sudah baku karena itu langsung dari PUSAT
