### ISSUE TITLE
Download Versi 19.07 Pasca Logo di Tampilan Front End Menyempit

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#2144]
### Bagaimana alurnya sampai muncul masalah?
Setelah Update ke versi 19.07 pasca tampilan logo di front end menyempit/mengecil 
![menyempit](https://user-images.githubusercontent.com/25834335/61057507-0de0e380-a428-11e9-9f92-e6a6933ef52f.png)

### Seperti apa yang diharapkan?
Tampilan logo seperti versi sebelumya

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by MUHAMMADRANGSEL** [comment]
Tampilan Widget Info Media Sosial Juga menyempit
![ddd](https://user-images.githubusercontent.com/25834335/61058106-30bfc780-a429-11e9-9ff1-e4d1a32294fb.png)

**Comment by MUHAMMADRANGSEL** [comment]
setelah saya cek ternyata dampaknya dari ini untuk logo:
![image](https://user-images.githubusercontent.com/25834335/61058483-edb22400-a429-11e9-9c06-316a27e9c24f.png)

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
