### ISSUE TITLE
tambah surat keterangan bukan ahmadiyah bagi calon jamaah haji dan domisi calhaj pake tanda tangan camat

### ISSUE THREAD

**Issue by M-A-Haris** [OpenSID/OpenSID#2149]
]

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by karangkamulyan** [comment]
> ]
> ### Bagaimana alurnya sampai muncul masalah?
> ### Seperti apa yang diharapkan?
> ### Apa yang terjadi?
> ### Informasi tambahan
> Tanya	Jawab
> Versi OpenSID	2.x
> Versi PHP	
> System operasi

**Comment by karangkamulyan** [comment]
untuk syarat ibadah haji di kabupten Ciamis Kementerian agama mengeluarkan sejumlah persyaratan diantaranya surat keterangan domisili yang ditandatangani pemohon diatas materai dan ditandatangani camat dan kepala desa

juga surat keterangan bukan anggota jamaah ahmadiyah yang ditandatangani  Pemohon diatas materai, Kepala Kepala Desa, Kepala KUA dan Camat

**Comment by karangkamulyan** [comment]
https://github.com/karangkamulyan/surat_ket_bukan_ahmadiyah

**Comment by karangkamulyan** [comment]
belajar kontribusi untuk opensid.. meski sederhana ..

**Comment by uncu29** [comment]
masukkan ke PR pak jika suratnya sudah diuji coba

**Comment by rdsetiawan** [comment]
untuk persyaratan pendaftaran ibadah haji, cukup menggunakan surat keterangan domisili yang di tanda tangan kepala desa diatas materai dan camat, tanpa tanda tangan pemohon. untuk surat keterangan bukan jemaat ahmadiyah cukup menggunakan **surat pernyataan** yang ditandatangani pemohon bermaterai, tanpa tanda tangan lainnya

**Comment by mizwaruddin** [comment]
@afa28 surat ini tidak berlaku secara nasional. Bisa dikembangkan sendiri oleh daerah yg membutuhkan melalui tambah surat.
