### ISSUE TITLE
Mengarsipkan data Log Penduduk

### ISSUE THREAD

**Issue by benioke** [OpenSID/OpenSID#2150]
Bagaimana alurnya sampai muncul masalah?
Belum ada tombol hapus penduduk untuk menghapus data penduduk di log penduduk.

Seperti apa yang diharapkan?
Tombol hapus ini diperlukan jika sewaktu waktu dibutuhkan misalkan
1.suami sebagai kepala keluarga meninggal dan isri nikah lagi otomatis KK atau no KK nya berubah tidak mungkin lagi untuk kembali kan status nya
2.penduduk hilang,mati,atau pindah lebih dari 10 tahun atau lebih
Dan hal-hal yang mengharus kan data penduduk tersebut untuk di hapus di sistem.seperti di windows ada recaybin.kita dapat mengrestore file(kembali kan file) atau delete file.

Apa yang terjadi?
Belum ada nya tombol hapus akan membuat penumpukan data penduduk yang benar benar tidak diperlukan lagi.tergantung lagi dari pengguna sistem untuk mengambil langkah nya, apakah data penduduk tersebut di hapus permanen karna tidak mungkin lagi dikembalikan status nya semula di sebabkan faktor tertentu.

 Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19.07 pasca
| Versi PHP        | 
| System operasi   |

**Comment by uncu29** [comment]
Apakah seperti ini maksud anda?
![Sistem Informasi Desa Desa Indra Sari Jaya - Penduduk Log - Mozilla Firefox 18_07_2019 21_15_11](https://user-images.githubusercontent.com/51182125/61464855-2d848880-a9a1-11e9-9574-d9917b9eb544.png)

**Comment by benioke** [comment]
Mantap

**Comment by eddieridwan** [comment]
@benioke @uncu29 : Tombol hapus di log penduduk SENGAJA dihilangkan (tadinya ada). Secara prinsip administrasi, data pemerintahan tidak dihapus. 

Kebutuhan anda untuk '_membuat penumpukan data penduduk yang benar benar tidak diperlukan lagi_' tidak didukung oleh prinsip administrasi. Arsip penduduk seharusnya tidak boleh dihapus. Beberapa tahun ke depan, SID seharusnya masih bisa menjawab pertanyaan seperti: 'kapan si A meninggal', 'apakah si B dulu betul penduduk desa ini', dsbnya?

Tentunya kita perlu suatu proses untuk 'mengarsipkan data' setelah tenggat waktu yg didukung oleh aturan pengarsipan data (supaya data tidak meluap). Misalnya, data transaksi (seperti log_penduduk) disimpan di database aktif selama 7 tahun. Setelah itu dapat diarsipkan, yaitu diunduh untuk disimpan di arsip digital di luar database aktif. 

Jadi, kalau teman2 mau, bisa ganti issue ini untuk menyediakan fitur 'mengarsipkan data log_penduduk'. Tetapi issue tersebut perlu melampirkan peraturan pengarsipan data yg berlaku.

Untuk kasus (1) anda terkait KK yg sudah tidak berlaku, mohon perhatian bahwa data KK di `tweb_keluarga` juga tidak boleh dihapus permanen, tetapi nanti hanya ditandai sebagai sudah tidak berlaku lagi. Kalau sudah ditandai demikian, penduduk yang sudah masuk ke log_penduduk tidak bisa lagi dikembalikan statusnya ke KK tersebut.

**Comment by mizwaruddin** [comment]
@afa28 Bisa di close
