### ISSUE TITLE
Edit Sub Menu "Arsip Layanan Surat"

### ISSUE THREAD

**Issue by PWidodo** [OpenSID/OpenSID#2151]
Pada menu LAYANAN SURAT > Sub Menu ARSIP LAYANAN SURAT perlu ditambah kolom "Kode Surat" didepan Nomor Urut Surat, serta kolom Keterangan dibelakang kolom Nama Penduduk, agar sesuai dengan "Buku Pelayanan Surat Umum Desa". gambar terlampir beserta lembar cetaknya.
-->

### Bagaimana alurnya sampai muncul masalah?
Pada Buku layanan surat umum desa, terdapat kolom Kode Surat, dan keterangan maksud surat tersebut dibuat, sedangkan pada lembar cetak Arsip layanan surat OpenSID tidak ada, dan hanya Nomor urut surat keluar yang tertera.

### Seperti apa yang diharapkan?
Hasil cetak Arsip layanan surat sama seperti data Arsip Layanan Surat Umum yang dipergunakan di Desa/Kelurahan, disertai tanda tangan Sekretaris Desa dan Mengetahui Kepala Desa.

### Apa yang terjadi?
Saya sudah edit tampilan dengan tambahan kolom sebagaimana tersebut diatas, akan tetapi karena keterbatasan pengetahuan saya tentang coding PHP sehingga perlu saya buat pada issue ini.

### Informasi tambahan 
Gambar tampilan menu Arsip layanan surat dan Printout saya lampirkan
| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19.07-pasca
| Versi PHP        | 7.2
| System operasi   | Windows
![Edit Arsip Layanan Surat](https://user-images.githubusercontent.com/45189822/61399740-f65a9c80-a8f8-11e9-99a3-b2e9ef84f400.png)
![Cetak Arsip Layanan Surat](https://user-images.githubusercontent.com/45189822/61399756-fd81aa80-a8f8-11e9-9d21-2f785d019fbf.png)

**Comment by uncu29** [comment]
Kirim file scriptnya pak

**Comment by PWidodo** [comment]
directory perubahanya (yang saya rubah) pada 👍 
1. donjo-app/views/surat/surat_keluar.php
2. donjo-app/views/surat/keluar_print.php
3. donjo-app/views/surat/surat_keluar_perorangan.php
Maaf untuk kirim scriptnya dimana yah....? taitan insert dibawah komentar ini hanya untuk image (gambar)

**Comment by ariandii** [comment]
Bisa coba pelajari link berikut untuk kirim script melalui Pull Request. 

https://www.petanikode.com/github-workflow/

**Comment by uncu29** [comment]
untuk keterangan saya sepertinya agak sulit ;-) , karena setiap surat berbeda isiannya, ada yang memiliki form isian keperluan ada yang tidak dan juga sudah ada di menu sekretariat=>surat keluar untuk isian singkat surat keluar.

**Comment by uncu29** [comment]
Untuk menambah keterangan belum dapat scriptnya 
![Sistem Informasi Desa Desa Indra Sari Jaya - Keluar - Mozilla Firefox 19_07_2019 10_07_29](https://user-images.githubusercontent.com/51182125/61506707-2e530400-aa0d-11e9-8758-7a82a657a1b2.png)
![Sistem Informasi Desa Desa Indra Sari Jaya - Keluar - Mozilla Firefox 19_07_2019 10_07_45](https://user-images.githubusercontent.com/51182125/61506708-2e530400-aa0d-11e9-9c8d-48876736dbec.png)

**Comment by PWidodo** [comment]
Keterangan Surat yang ada di Menu SEKRETARIAT itu kan Arsip Surat Dinas (masuk/keluar) baik dari atau ke Instansi/ Dinas/ Lembaga. lan Issue ini adalah untuk Arsip Pelayanan Umum (warga masyarakat/non warga) jadi terpisah.

**Comment by redjoel** [comment]
Keren ini kalau bisa jadi perbaikan ;)

**Comment by uncu29** [comment]
mungkin bung redjoel bisa memasukan dalam PR ;)

**Comment by eddieridwan** [comment]
Saya kira menampilkan kode surat tidak susah -- mungkin @uncu29 atau @redjoel bisa.

Tapi kolom keterangan bermasalah. Untuk apa? Apa yg akan diisikan? Dan diisikan di mana -- di form surat -- pada waktu mencetak atau lainnya? Apakah diambil dari isian 'keterangan' di beberapa form surat? Sepertinya ini contoh peraturan/format laporan yg tidak dipikirkan secara matang oleh pencetusnya. Atau apakah ini hanya untuk Surat Dinas, bukan Surat Layanan?

**Comment by eddieridwan** [comment]
@PWidodo kalau mau melampirkan script di issue, compress dulu file yg akan dilampirkan ke format .zip. Kemudian lampirkan file .zip itu.

**Comment by eddieridwan** [comment]
@PWidodo, @redjoel , @uncu29  untuk menerapkan issue ini, diperlukan kejelasan mengenai kolom `Keterangan`. Isinya diambil dari mana?

1. Apakah ditambahkan kolom isian baru di setiap form surat?
2. Apakah diambil dari kolom isian yang sudah ada di masing2 form surat? Kalau begitu, harap jelaskan kolom isian mana yg diambil per surat -- karena saat ini berbeda untuk setiap surat
3. Apakah ada pop-up khusus pada waktu mencetak surat untuk mengisi `Keterangan`?

Kejelasan ini diperlukan sebelum permintaan ini bisa diterapkan.

**Comment by PWidodo** [comment]
Kolom keterangan diisi dari form ['keperluan'] masing-masing surat. Karena seperti itulah Tabel Buku Pelayanan Administrasi Umum di Desa kami, kalau mungkin berbeda di Desa/Wilayah lain, Kolom Keterangan diisi manual saja atau mungkin ditiadakan.

**Comment by uncu29** [comment]
jika diambil dari form ['keperluan'] masing surat berbeda, jika memang keterangan diperlukan diisi secara manual.

**Comment by eddieridwan** [comment]
Salah satu solusinya bisa sebagai berikut:

1. periksa setiap surat. Seragamkan penamaan kolom isian terkait 'keperluan'. 
2. kalau tidak ada kolom isian 'keperluan' periksa apakah ada kolom isian 'keterangan'. Seragamkan nama kolom itu dan gunakan
3. simpan isian 'keterangan' atau 'keperluan' dari form surat ke tabel `log_surat` -- tambah kolom 'keterangan'.
4. kalau tidak ada kolom isian 'keperluan' atau 'keterangan' di form surat, kosongkan kolom 'keterangan' di tabel `log_surat`.
5. sediakan fitur untuk mengubah entri Arsip Layanan Surat, supaya kolom 'keterangan' bisa diubah kalau perlu

**Comment by eddieridwan** [comment]
Bagaimana @uncu29, bisa terapkan?

**Comment by uncu29** [comment]
saya coba pak

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR #2217 .
Tetapi yg berikut belum dikerjakan:
- Periksa semua surat untuk menyeragamkan penamaan kolom isian `keterangan` dan `keperluan`.
- Sediakan fitur untuk mengubah entri Arsip Layanan Surat, supaya kolom 'keterangan' bisa diubah kalau perlu
