### ISSUE TITLE
Sesuaikan pencatatan dan pelaporan data persil dengan C-Desa

### ISSUE THREAD

**Issue by PWidodo** [OpenSID/OpenSID#2152]
### Bagaimana alurnya sampai muncul masalah?
Dalam Administrasi Pertanahan di desa terdapat 2 (dua) kriteria jenis tanah yaitu Tanah Kering (pekarangan, tegalan, kebun) dan Tanah Basah (sawah) dengan nomor persil atau Blok yang berbeda-beda. 1 (satu) orang Pemilik Tanah mendapatkan Nomor C-Desa satu atau contoh Nomornya 001 dan dalam isian C-Desa tersebut ada perincian Nomor Persil/Blok, Luas, Kelas Desa, Sebab dan Tanggal Perubahan.  Kolom Sebab dan tanggal perubahan tersebut berisi tanggal perubahan tanah karena dijual sebagaian atau seluruhnya, waris dari.... atau hibah dari.... Dan apabila perubahanya karena Pembelian otomatis akan memunculkan data persil baru dibawahnya.

### Seperti apa yang diharapkan?
Kalau bisa Menu PERTANAHAN dibuat sebagaimana gambar yang saya lampirkan beserta lembar cetaknya.

### Apa yang terjadi?
Hal tersebut saya usulkan agar OpenSID dapat mencakup semua administrasi Desa.

### Informasi tambahan 
Gambar saya lampirkan
| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19.07-pasca
| Versi PHP        | 
| System operasi   | Windows
![database tanah](https://user-images.githubusercontent.com/45189822/61400772-2efb7580-a8fb-11e9-8be7-708d810ff23b.png)
![Lembar cetak3](https://user-images.githubusercontent.com/45189822/61400788-3884dd80-a8fb-11e9-8496-0cc7c2f21535.png)
![lembar cetak1](https://user-images.githubusercontent.com/45189822/61400798-3cb0fb00-a8fb-11e9-86bb-d43ce94dac32.png)
![Lembar cetak2](https://user-images.githubusercontent.com/45189822/61400804-40448200-a8fb-11e9-88a7-d06e1d4e162e.png)

**Comment by HerryWanda** [comment]
Berarti ini sama nantinya untuk buku C.Desa ya pak parso...

**Comment by PWidodo** [comment]
Ya Betul pak.

**Comment by mizwaruddin** [comment]
Catatan: 1. Berarti utk nama pemilik tdk perlu diambilkan dr data penduduk skrg, krn dalam buku C tertulis pemilik pertama (yg kemungkinan sdh meninggal semua). 2. Tdk prlu ada tambahan keterangan nomor SPPTB krn data di SPPT banyak yg menggunakan nama orang sekarang.

**Comment by PWidodo** [comment]
Untuk engambilan Nama Pemilik dibuat 2 mode pak yang bersebelahan seperti pada menu Aparatur Desa Pak, bisa diambilkan dari database penduduk dan manual

**Comment by PWidodo** [comment]
seperti ini barangkali : 
![image](https://user-images.githubusercontent.com/45189822/73429678-c3489980-436e-11ea-90ab-320da442b0bf.png)

**Comment by PWidodo** [comment]
Untuk kriteria Tanah mungkin diganti seperti ini : 
![image](https://user-images.githubusercontent.com/45189822/73429819-1de1f580-436f-11ea-90f2-7771b33705e6.png)

**Comment by PWidodo** [comment]
untuk Kelas Desa biasanya menggunakan kode ( D-1) adalah tanah darat atau kering yang terletak dekat dengan permukiman warga atau dekat dengan jalan desa. (D-2) agak jauh, (D-3) jauh, dan (D-4) sangat jauh. begitupun untuk tanah Basah, biasanya menggunakan kode (S-1), (S-2), (S-3) dan (S-4). untuk isiannya dibuatkan tombol pilihan saja, seperti menu combo.

**Comment by PWidodo** [comment]
Kelas desa tersebut berpengaruh pada nilai jual tanah

**Comment by mizwaruddin** [comment]
![FORM BUKU C](https://user-images.githubusercontent.com/39736008/73432480-6a303400-4375-11ea-91a7-ec996931dd7e.PNG)

**Comment by PWidodo** [comment]
OK 👍

Pada tanggal Kam, 30 Jan 2020 15.30, mizwaruddin <notifications@github.com>
menulis:

**Comment by PWidodo** [comment]
Oh ya satu lagi bung, pemilik tanah juga ada yg berasal dari luar desa.
Yaitu warga luar desa yg memiliki tanah di desa kita.

Pada tanggal Kam, 30 Jan 2020 16.02, Parso Thok <parsowidodo081@gmail.com>
menulis:

**Comment by PWidodo** [comment]
Tambahkan pula tombol pencarian, khusus untuk mencari nomor C Desa tertentu, dengan mengetikan Nama Pemiliknya, Jika pada data C yang telah dientry ternyata ada nama pemilik yang sama (lebih dari 1 orang dengan nama yg sama) maka akan keluar semua, kita tinggal pilih nama A atau nama B yang dimaksud.

**Comment by PWidodo** [comment]
Nomor C terdiri dari 4 digit (otomatis dibuat oleh sistem) Contoh : 0001 - 9999

**Comment by karangkamulyan** [comment]
saya coba yang sederhana lebih pada beban penarikan PBB oleh desa, yang diubah hanya kolom "kelas tanah" menjadi Jumlah PBB Rp. 

![jumlah_pbb](https://user-images.githubusercontent.com/46555658/74329413-54cdf780-4dc2-11ea-9455-ee89bd4e981b.png)

**Comment by karangkamulyan** [comment]
perubahan tersebut dipicu dari dok DHKP dinas keuangan yang setiap tahun diserahkan kepada desa dalam bentuk file excel 
![dhkp](https://user-images.githubusercontent.com/46555658/74330508-687a5d80-4dc4-11ea-9442-89838ea8dd5b.png)

**Comment by PWidodo** [comment]
Dasar hukum terkait C-Desa atau Letter-C https://www.atrbpn.go.id/Publikasi/Peraturan-Perundangan/Undang-Undang/undang-undang-nomor-5-tahun-1960-920

**Comment by PWidodo** [comment]
untuk mengetahui bagaimana fungsi  Registrasi Desa (Letter C) dalam pembuktian hak milik atas tanah dan bagaimana kedudukan hukum Registrasi Desa  (Letter C) di dalam undang-undang No 5 Tahun 1960 tentang Peraturan Dasar Pokok-Pokok Agraria.  Dengan menggunakan metode penelitian yuridis normatif dapat disimpulkan: 1. Untuk memperoleh hak milik atas tanah harus dilakukanpembuktian yang menurut Pasal 24 Peraturan Pemerintah No. 24 Tahun 1997 Tentang Pendaftaran Tanah,berupa bukti-bukti tertulis, keterangan saksi dan atau pernyataan yang bersangkutan.Registrasi Desa (Letter C) merupakan salah satu bukti tertulis untuk memperoleh hak milik atas tanah, yang dalam hal ini dapat melahirkan surat tanda bukti hak atau sertifikat hak milik sebagai mana yang dimaksud dalam Pasal 19 ayat (2) huruf c UUPA. 2. Registrasi Desa (Letter C) tidak tertib administrasi karna tidak sesuai dengan UUPA yang menyatakan bahwa untuk melaksanakan tertib administrasi harus di terbitkan sertifkat hak milik bagi pemegang hak atas tanah. Tetapi jika Registrasi Desa (Letter C) dapat dibuktikan kebenaran Data Fisik dan Data Yuridisnya, maka Registrasi Desa (Letter C) dapat digunakan sebagai tanda bukti kepemilikan hak atas tanah penganti sertifikat yang belum diterbitkan.

**Comment by ianskids** [comment]
Berikut Pak @eddieridwan informasi dari bung @PWidodo

**Comment by eddieridwan** [comment]
Dari @mizwaruddin :
![Screenshot_2020-02-20-17-34-11](https://user-images.githubusercontent.com/249563/74980567-d25dcb80-5484-11ea-8867-90b3bb206d81.png)

**Comment by eddieridwan** [comment]
Supaya stabil dan mengurangi kemungkinan adanya kerancuan, penerapan modul Pertanahan perlu menggunakan struktur data yg dapat mewakili struktur pertahanan se-akurat mungkin. Dari pembahasan dengan bung @mizwaruddin  di Slack, informasi yg kami peroleh sejauh ini adalah sebagai berikut:

1. Persil adalah bidang tanah dengan nomor unik, yg tidak berubah. Kita simpan data berikut untuk setiap persil:
    - Kelas tanah (S-1 s/d D-IV )
    - Lokasi
2. Persil dapat dipecah menjadi beberapa bidang tanah, yg mana setiap bagian tersebut bisa dipecah atau digabung lagi sesuai mutasi pertanahan. Setiap bagian bidang tanah tersebut mempunyai `nomor bagian persil` atau juga dikenal sebagai `nomor urut bidang`. Tetapi menurut @mizwaruddin , pada saat mencatat mutasi di buku C-Desa, bidang tanah baru hasil pemecahan masih tetap menggunakan 'nomor urut bidang' sebelumnya. Yaitu, untuk sementara, kita tidak dapat membuat asumsi bahwa `nomor urut bidang` unik dan nomor tsb tidak bisa digunakan untuk mengindentifikasi suatu bidang tanah secara unik.

Karena itu, sementara ini, yg dapat kita simpan adalah mutasi bidang tanah, dan bukan data bagian persil secara unik, dan yg dicatat di C-Desa adalah mutasi tersebut. Untuk setiap mutasi bidang tanah yg tercatat di C-Desa, data yg kita simpan adalah sebagai berikut:
    - Nomor persil di mana tanah tersebut terletak
    - Jenis tanah
    - Peruntukan
    - Pajak
    - Nomor SPPT PBB
    - Nomor bagian persil / nomor urut bidang
    - Luas tanah
    - keterangan mutasi lainnya
3. C-Desa adalah pencatatan kepemilikan tanah oleh seseorang. Yg dicatat di C-Desa adalah mutasi bidang tanah bagian persil sebagaimana dijelaskan di (2) di atas. Setiap C-Desa memiliki nomor unik. Setiap C-Desa mencatat semua mutasi bidang tanah yg dimiliki seseorang.
4. Seorang penduduk, katakanlah Nasran dapat tercatat di lebih dari satu buku C-Desa, di mana masing C-Desa berisi satuan kepemilikan yg berbeda. Nasran dapat tercatat sebagai nama pemilik yg beserta nama bapak atau istri. Contoh
    - Nasran b Karsan: Nasran bin Karsan
    - Nasran / Solekah : Nasran bersama istrinya Solekah
Masing2 satuan kepemilikan tersebut tercatat di buku C-Desa yg berbeda. Dalam contoh kedua di atas, C-Desa tersebut tercatat pada penduduk Nasran dan juga pada penduduk Solekah.

Mohon teman2 periksa keterangan di atas, dan silakan berikan komentar dan perbaikan. Terima kasih. @PWidodo @mizwaruddin @ianskids @M-A-Haris

**Comment by eddieridwan** [comment]
@PWidodo @mizwaruddin @M-A-Haris @ianskids , mohon periksa data model untuk Persil berikut. Silakan beri komentar dan perbaikan.
<img width="477" alt="Persil_ER_Diagram" src="https://user-images.githubusercontent.com/249563/76694016-6bb58180-66c1-11ea-8ab8-22896d331bbd.png">

**Comment by mizwaruddin** [comment]
Hasil Review C-DESA
1.	Apa perbedaan Nama Pemilik dan Nama Kepemilikan? Kalau yang dimaksud Nama Pemilik adlh pemilik sekarang dan Nama Kepemilikan adalah pemilik lama (dalam Buku C-Desa) maka saya kurang sependapat. Pemilik baru sebaiknya dicatat dalam ketengan (mutasi) saja. Alasannya adalah pemilik lama bisa saja memiliki beberapa bidang tanah yang kemungkinan besar tidak dimiliki semua oleh pemilik baru.
2.	Ketika pemili dalam C-Desa sudah meninggal dan belum/tidak tercatat dalam OpenSID maka dimasukkan di mana?
3.	Pada input Persil ditambahkan LUAS. Saat ini luas bidang diambil dari input MUTASI.
4.	Input Bidang Persil sebaiknya ditiadakan karena tidak ada kaitannya dengan Buku C-DESA. Untuk pencatatan NOP/SPPT sebaiknya difokuskan di fitur PBB saja.
5.	Saat ini dalam keterangan (yg diambil dari mutasi) belum menyertakan sebab mutasi.
6.	Pada input MUTASI, field keterangan diganti ke … (nama pemilik baru)
7.	Saat ini MUTASI hanya dilakukan sekali. Jika diedit, maka catatan mutasi sebelumnya hilang. Artinya jejak perpindahan/mutasi tanah hilang. Seharusnya mutasi bisa dilakukan berkali-kali tanpa menghilangkan catatan mutasi sebelumnya.

**Comment by eddieridwan** [comment]
Menurut pembahasan sebelumnya (di atas), yg saya tangkap adalah konsep Persil sebagai bidang tanah yg terdiri dari beberapa bidang persil. Yg saya tangkap, sebenarnya yg dimutasikan (dijual/beli/hibah/dsbnya) adalah masing2 bidang persil tersebut, bukan suatu Persil secara keseluruhan. Jadi suatu Persil misalnya seluas 1000m2, tetapi yg dimutasikan bisa sebagian saja, yaitu bidang persil seluas 500m2, dstnya. 

Jadi suatu Persil bisa terdiri dari beberapa bidang persil yg dimiliki oleh pemilik yg berlainan. Yaitu suatu Persil tidak berubah -- selalu konstan -- sedangkan bagian dari Persil, yaitu bidang persil adalah unit yg dimutasikan. 

Apakah saya salah tangkap?

**Comment by eddieridwan** [comment]
Keterangan yg ditemukan @fusionid :

https://l.facebook.com/l.php?u=http%3A%2F%2Feprints.undip.ac.id%2F56968%2F%3Ffbclid%3DIwAR2J8m9BsyydRXTOgKc9GaPmKQBJsDV-hkGqT5CaSMu9DSPif-9ukQ3lGWU%23%3A~%3Atext%3DLetter%2520C%2520diberikan%2520kepada%2520pemilik%2Cmembayar%2520pajak%2520sebagai%2520tanda%2520buktinya.%26text%3DPerlindungan%2520hukum%2520bagi%2520kepemilikan%2520tanah%2Catas%2520hak%2520tanah%2520yang%2520sebenarnya&h=AT1l2wVRTCXjtHuIwWvg3LMxPZRM52cBdEgJ4soIX-gUysf1DQQdyMojQyTdYt9spKLrK1X9xLHKrVHhWHsb_IXvvK8AhVgwLYRhjdVSCL2buCVZrB4x5IIpWryic6hNrfnJZQlFhvz3AuKcMV8

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master`

**Comment by jetak77** [comment]
ini aplikasinya didapat dari mana?
bisa ngambil dari mana, share geratis atau berbayar?
