### ISSUE TITLE
Perbaikan Format An. dan Ub. pada Surat.rtf

### ISSUE THREAD

**Issue by PWidodo** [OpenSID/OpenSID#2154]
### Bagaimana alurnya sampai muncul masalah?
Susunan penandatanganan surat pada Pemerintah Desa/Kelurahan sesuai permendagri adalah, jika Kepala Desa tidak ditempat (kantor), maka yang berhak menanda tangani surat adalah Sekretaris Desa, dengan format :
A.n. Kepala Desa........
Sekretaris Desa

NAMA SEKRETARIS DESA

Selanjutnya jika Sekretaris Desapun tidak berada di tempat (kantor) maka yang menanda tangani surat adalah Perangkat Desa lainnya dengan Format: 

A.n. Kepala Desa ...........
Sekretaris Desa 
Ub.
Jabatan Pamong (selain kades dan sekdes)

NAMA PAMONG (selain kades dan sekdes)

### Seperti apa yang diharapkan?
Dalam OpenSID ini sudah ada Ub, tapi belum sesuai dengan format yang sesuai dengan tata naskah dinas di kantor Desa/Kelurahan.

### Apa yang terjadi?
Pemerintah Kecamatan memberikan masukan pada kami agar formatnya untuk disesuaikan dengan tata naskah dinas yang berlaku. Harapannya hal ini menjadi kritik/saran guna penyempurnaan OpenSID pada rilis kedepannya

### Informasi tambahan 
Gambar contoh baik An. maupun Ub. saya lampirkan
| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19.07-pasca
| Versi PHP        | 
| System operasi   | Windows
![format AN](https://user-images.githubusercontent.com/45189822/61551306-fe444900-aa7e-11e9-9f6e-a1a375af010b.png)
![format UB](https://user-images.githubusercontent.com/45189822/61551316-0603ed80-aa7f-11e9-86fc-774dc8079da9.png)

**Comment by ariandii** [comment]
Bisa berikan contoh berupa gambar format yangsudah diterapkan opensid dan format seharusnya?

**Comment by PWidodo** [comment]
Dibawah ini gambar yang sudah diterapkan di OpenSID yang belum sesuai format, sedangkan Format seharusnya sebagaimana gambar diatas dibawah issue.
![Ub1](https://user-images.githubusercontent.com/45189822/61555443-9f380180-aa89-11e9-929e-36b2439cf42c.png)
![Ub2](https://user-images.githubusercontent.com/45189822/61555450-a52de280-aa89-11e9-9a53-911c1ff23913.png)
![Ub3](https://user-images.githubusercontent.com/45189822/61555460-ab23c380-aa89-11e9-94c8-8f9445ec7c7a.png)

**Comment by PWidodo** [comment]
Ini saya unggah lagi gambar format yang seharusnya, dengan Keterangan Rinci sbb:

1. Jika pada form penanda tanganan surat yang dipilih default, maka otomatis hanya berisi jabatan Kepala Desa dan Nama Kepala Desa.

2. Jika pada form penanda tanganan yang dipilih Atas Nama, maka otomatis berisi "An. Kepala...... lalu dibawahnya berisi Sekretaris Desa, dan dibawahnya lagi berisi Nama Sekretaris Desa"

3. Jika pada form penanda tanganan yang dipilih Untuk Beliau, maka pada surat berisi "An. Kepala Desa.... lalu dibawahnya berisi Sekretaris Desa, dan dibawahnya berisi Ub. dan dibawahnya lagi berisi Jabatan Pamong sesuai pilihan pada Form, dan terakhir dibawahnya berisi Nama Pamong sesuai pilihan pada Form surat. 

contoh gambar format yang seharusnya
![Format Penandatangan surat](https://user-images.githubusercontent.com/45189822/61556910-0c996180-aa8d-11e9-8d62-ef7136dcc105.png)
 sbb:

**Comment by ariandii** [comment]
Bukankah OpenSID sudah menerapkan Ub seperti halnya di atas? seperti pada wiki berikut:

https://github.com/OpenSID/OpenSID/wiki/Blok-Penandatangan-Surat

**Comment by redjoel** [comment]
Saya gulung issue ini pak. 
Malahan ini issue major karena ini fitur berbayar yang diminta sama salah satu desa.
Apa yang pak Parso sebut memang benar. Format An Dan UB Masih belum tepat di implementasikan didalam OpenSID kita

**Comment by redjoel** [comment]
Betul memang sudah ada pak @ariadii hanya hasil export doc, Masih belum sesuai dengan ketentuan (yang diharapkan).
Penjelasan pak @PWidodo diatas, cukup lengkap
;)

**Comment by ariandii** [comment]
> Betul memang sudah ada pak @ariadii hanya hasil export doc, Masih belum sesuai dengan ketentuan (yang diharapkan).
> Penjelasan pak @PWidodo diatas, cukup lengkap
> ;)

belum sesuainya bagian mana ya pak? maaf saya masih gagal memahaminya.

**Comment by eddieridwan** [comment]
Sepertinya bung @redjoel dan @PWidodo belum membaca panduan https://github.com/OpenSID/OpenSID/wiki/Blok-Penandatangan-Surat, dan belum paham penggunaan setting `a.n` dan `u.b` di halaman _Pemerintahan Desa_.

Setelah membaca panduan itu dan melihat contoh blok penandatangan surat yg dihasilkan, mohon jelaskan sekali lagi persisnya di mana letak masalahnya.

Terima kasih, bung @ariandii telah menanggapi. Mohon dipantau terus.

**Comment by PWidodo** [comment]
OK terimakasih @eddieridwan dan @ariandii   ternyata issue ini telah ada sebelumnya dan telah dikerjakan oleh @ariandii. setelah saya baca panduannya hasilnya sudah sesuai dengan yang saya harapkan. terimaksih banyak dan maaf atas kurangnya frekwensi membaca panduan saya di wiki. Dengan demikian Issue#2154 ini saya batalkan atau saya tutup.
