### ISSUE TITLE
Fitur: Buat formulir dengan model F-1.16

### ISSUE THREAD

**Issue by Dedi83** [OpenSID/OpenSID#216]
Surat surat di bawah ini sering keluar di desaku, sementara ini masih manual dalam pengerjaannya. apakah ada yang bisa membantu untuk di includkan ke database ini.

![formulir permohonan perubahan kartu keluarga -f-1 16](https://cloud.githubusercontent.com/assets/19701605/20640227/96b88728-b40a-11e6-9962-b8c626195c40.jpg)

**Comment by MUHAMMADRANGSEL** [comment]
issue ini sama dengan issue (PENTING) Bantuan Pembuatan Form surat Perubahan KK (F-1.16) #706

**Comment by metalab25** [comment]
@Dedi83 dan om @MUHAMMADRANGSEL, mohon kirimkan formulirnya dalam format doc atau rtf biar saya bisa mengerjakan issue ini dengan cepat. Saya tidak mahir menggunakan aplikasi word hehehehhe

**Comment by MUHAMMADRANGSEL** [comment]
Kalau berbentuk docx atau rtf tdk ada mas happy tapi dia sama persis seperti permohonan kartu keluarga

**Comment by metalab25** [comment]
Benar" sama persis atau apa ada perbedaan kolom isiannya ????

**Comment by MUHAMMADRANGSEL** [comment]
Untuk perubahan kartu keluarga biasanya dilakukan apabila : 
1. Ada penambahan anggota keluarga disebabkan  kelahiran atau ada numpang
2. Pengurangan anggota keluarga disebabkan mati,  pindah
3. Pindah domisili

**Comment by MUHAMMADRANGSEL** [comment]
Untuk kolom memang ada perbedaan dan diatas sdh dilampirkan formnya

**Comment by metalab25** [comment]
Format master Surat Permohonan Perubahan Kartu Keluarga sudah selesai saya buat.
@eddieridwan, ini saya PR atau saya attach di sini. Saya PR dbnya juga tidak akan ikut masuk ke PR

**Comment by eddieridwan** [comment]
@metalab25:
1. sebaiknya kalau alasan permohonan adalah 'lainnya', disediakan kolom isian di form surat supaya alasan tersebut bisa tercetak langsung di F-1.16, dan tidak harus ditulis tangan.
2. apakah pada butir 11 di F-1.16, kepala keluarga ikut terdaftar atau hanya anggota keluarga saja? @MUHAMMADRANGSEL @Dedi83 : harap konfirmasi.

**Comment by MUHAMMADRANGSEL** [comment]
1. Point 1 sediakan Kolom isian supaya bisa dicetak langsung seperti di kolom surat pindah
2. Point 2 hanya diisi oleh Anggota Keluarga

**Comment by MUHAMMADRANGSEL** [comment]
dan juga disamping lampiran surat permohonan perubahan KK F-1.16 juga lampiran F-1.01
sehingga tuk surat permohonan perubahan kartu keluarga ada 2 lampiran : 
1. F-1.16
2. f-1.01

**Comment by metalab25** [comment]
Baik akan saya revisi dulu bung @eddieridwan

**Comment by metalab25** [comment]
ini yang sudah saya perbaiki silakan dicoba kembali.
om @MUHAMMADRANGSEL sekarang lampiran sudah ada F-1.01 dan F-1.16
bung @eddieridwan Alasan Permohonan "Lainnya" sudah diisi dengan kolom input manual
[surat_permohonan_perubahan_kartu_keluarga.zip](https://github.com/OpenSID/OpenSID/files/1588535/surat_permohonan_perubahan_kartu_keluarga.zip)

**Comment by eddieridwan** [comment]
@metalab25 Daftar anggota keluarga di F-1.16 kosong, harusnya ada isinya:

[surat_permohonan_perubahan_kartu_keluarga_5201141003666996_2017-12-27_235_lampiran.pdf](https://github.com/OpenSID/OpenSID/files/1588667/surat_permohonan_perubahan_kartu_keluarga_5201141003666996_2017-12-27_235_lampiran.pdf)

Dan di form surat, perlu dijelaskan ada lampiran F-1.01 juga. Seperti di form Surat Permohonan Kartu Keluarga Baru.

**Comment by metalab25** [comment]
Waktu saya coba ada isinya bung

**Comment by eddieridwan** [comment]
@metalab25 coba lampirkan contoh lampiran F-1.16 berisi daftar anggota keluarga.

**Comment by metalab25** [comment]
Bung @eddieridwan , berikut ini surat/formulir F-1.16 yang sudah saya perbaiki seperti pada gambar dibawah
[surat_permohonan_perubahan_kk_5201141003666996_2017-12-27_qwe4r569_lampiran.pdf](https://github.com/OpenSID/OpenSID/files/1589146/surat_permohonan_perubahan_kk_5201141003666996_2017-12-27_qwe4r569_lampiran.pdf)
![screenshot_18](https://user-images.githubusercontent.com/19917739/34383562-ead34ec8-eb50-11e7-9843-946188300702.png)
[surat_permohonan_perubahan_kartu_keluarga.zip](https://github.com/OpenSID/OpenSID/files/1589148/surat_permohonan_perubahan_kartu_keluarga.zip)

**Comment by metalab25** [comment]
maaf ada sedikit perbaikan
[surat_permohonan_perubahan_kartu_keluarga.zip](https://github.com/OpenSID/OpenSID/files/1589159/surat_permohonan_perubahan_kartu_keluarga.zip)

**Comment by eddieridwan** [comment]
@metalab25 : Trims. 

Sudah dicommit ke master.
