### ISSUE TITLE
[Bug] KK kosong serta KK tidak aktif ikut terhitung di menu statistik

### ISSUE THREAD

**Issue by makhbub** [OpenSID/OpenSID#2160]
### Bagaimana alurnya sampai muncul masalah?
Pada menu statistik --> statistik program bantuan, mencakup rekap data /prosentase penduduk penerima bantuan
### Seperti apa yang diharapkan?
Jumlah KK yang dipakai pada statistik program bantuan hanya KK aktif

### Apa yang terjadi?
KK kosong serta KK hilang/pindah/mati ikut terhitung di menu statistik sehingga hasil hitungan prosentase tidak sesuai dengan keadaan sebenarnya
### Informasi tambahan 
Jenis KK yang ada di menu Kependudukan -> Keluarga
1. KK Aktif
2. KK Hilang/Pindah/Mati
3. KK Kosong
| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dicommit ke master
