### ISSUE TITLE
Pemaggilan Nama dan Nik Lelet

### ISSUE THREAD

**Issue by R4HMAT** [OpenSID/OpenSID#2161]
Bagaimana alurnya sampai muncul masalah?
pas ketika pembuatan surat menyurat untuk pemanggilan Nama dan Nik lama/lelet munculnya tempat penulisan Nama dan NIK.

Apa yang terjadi?
Hal tersebut saya usulkan agar OpenSID dapat berjalan ketika jumlah penduduk dengan jumlah banyak

Informasi tambahan
Gambar saya lampirkan
| Tanya | Jawab
| ---------------- | ---
| Versi OpenSID | 19.07-pasca
| Versi PHP |
| System operasi | Windows 10 64 Bit
![KELH11](https://user-images.githubusercontent.com/43318683/61619359-e47e4e00-ac98-11e9-9f37-86aff52a3260.png)
![kelh12](https://user-images.githubusercontent.com/43318683/61619372-ee07b600-ac98-11e9-92a7-250a12d1cc1a.png)

**Comment by uncu29** [comment]
Opensid saya normal dengan data penduduk 889

**Comment by R4HMAT** [comment]
jumlah penduduk 9.501 jiwa


Pada tanggal Sen, 22 Jul 2019 23:15, Nur Hidayat <notifications@github.com>
menulis:

**Comment by eddieridwan** [comment]
Mungkin bisa gunakan opsi ajax yg disediakan Select2 : https://select2.org/data-sources/ajax

**Comment by eddieridwan** [comment]
Sudah dicommit ke master, pemanggilan daftar pilihan penduduk menggunakan ajax. Tetapi masih belum menggunakan paginasi. Telah dibuat issue https://github.com/OpenSID/OpenSID/issues/2180 untuk menerapkan paginasi.
