### ISSUE TITLE
Halaman Layanan Mandiri Terpisah

### ISSUE THREAD

**Issue by Didinzein** [OpenSID/OpenSID#2164]
### Bagaimana alurnya sampai muncul masalah?
Pengunjung tidak memahamai bahwa widget layanan mandiri adalah portal LOGIN untuk menuju database warga yang terdaftar. maka perlu diberikan halaman sendiri agar lebih fokus pada prosedur LOGIN maupun pendaftaran

### Seperti apa yang diharapkan?
Layanan Mandiri dibuatkan halaman sendiri seperti //webdesa/siteman

### Apa yang terjadi?
karena saya blm faham alur controller, untuk sementara saya ambil alih halaman arsip melalui thema "cosmos" sebagai laman Login Layanan Mandiri, bisa dicoba melalui link berikut : https://desadagan.id/first/arsip

### Informasi tambahan 
Saya lampirkan script modifikasi halaman siiteman menjadi layanan mandiri
[Mandiri.zip](https://github.com/OpenSID/OpenSID/files/3431952/Mandiri.zip)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    |19.07
| Versi PHP        |  7
| System operasi   |

**Comment by ruanglabs5** [comment]
file tersebut dimasukin di widget bukan pak ?

**Comment by afa28** [comment]
Sistem OpenSID perlu dibagi menjadi 3 bagian:
1. Web/Konten berita.
2. Admin
3. Mandiri

agar lebih terstruktur baik di susunan controller, model dan view nya.

**Comment by afa28** [comment]
Sudah di Fitur Premium, http://berputar.opensid.my.id/mandiri_web
