### ISSUE TITLE
[Bug] Pekerjaan Saksi di lampiran F.2.29

### ISSUE THREAD

**Issue by rdsetiawan** [OpenSID/OpenSID#2167]
### Seperti apa yang diharapkan?
Pekerjaan saksi sesuai data

### Apa yang terjadi?
di Issue #1890 sudah closed, tp saat coba di demo masih keliru..
saksi 1 dan saksi 2 keduanya keliru
![isue](https://user-images.githubusercontent.com/53161330/62024667-0ed38c80-b200-11e9-9250-8129788aa014.png)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
