### ISSUE TITLE
ERROR Cetak Layanan Surat

### ISSUE THREAD

**Issue by zmetal** [OpenSID/OpenSID#2168]
### Bagaimana alurnya sampai muncul masalah?
Ketika membuat sebuah surat baru pada Menu Layanan Surat halaman yang diload tidak ditampilkan atau terjadi ERROR :

sedangkan pada contoh demo dihalaman website https://demo.opensid.id/surat/form/surat_ket_jual_beli menu cetak surat tidak mengalami error apapun.

### Seperti apa yang diharapkan?
Menu Cetak Layanan Surat tampil seperti seharusnya yang ada pada web demo
https://demo.opensid.id/surat/form/surat_ket_jual_beli

### Apa yang terjadi?
Terjadi error pada menu Layanan Cetak Surat, dengan pesan tampilan seperi dibawah ini:

 500
Sebuah Kesalahan Basis Data Telah Terjadi

Error Number: 1054

Unknown column 'pamong_ub' in 'where clause'

SELECT * FROM `tweb_desa_pamong` WHERE `pamong_ub` = 1

Filename: models/Pamong_model.php

Line Number: 287
Harap laporkan masalah ini, agar kami dapat mencarikan solusinya. Untuk sementara Anda dapat kembali ke halaman awal. 

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | OpenSID 19.07-pasca
| Versi PHP        | 7.2.20
| System operasi   | Linux (Manjaro x64)
![Screenshot from 2019-07-29 23-08-11](https://user-images.githubusercontent.com/36635705/62064280-b8456d00-b256-11e9-9559-4e46490621ea.png)
![Screenshot from 2019-07-29 23-08-56](https://user-images.githubusercontent.com/36635705/62064282-b8456d00-b256-11e9-9bcc-c8a7ff11dabe.png)

**Comment by eddieridwan** [comment]
@zmetal : jalankan _Pengaturan > Database > Migrasi DB_. Proses migrasi ini diperlukan untuk menyesuaikan struktur database kalau anda update ke rilis OpenSID baru atau ke rilis _pasca terbaru.

Ok, karena ini bukan error, issue ini akan kami tutup. Silakan buka lagi kalau masih bermasalah.
