### ISSUE TITLE
Error ketika masuk ke setting aplikasi

### ISSUE THREAD

**Issue by AlfaridzhE** [OpenSID/OpenSID#2170]
Saya baru install lagi opensid, dan ternyata tak semudah opensid yang dulu saya kenal.
Saya tidak akan panjang lebar, mohon bantuannya, ketika klik Pengaturan->Aplikasi, ketemu error seperti ini.

**500
Sebuah Kesalahan Basis Data Telah Terjadi

Error Number: 1054

Unknown column 'kode' in 'field list'

SELECT `id`, `kode`, `value` FROM `setting_aplikasi_options` WHERE `id_setting` = '24'

Filename: C:/xampp/htdocs/opensid/system/database/DB_driver.php

Line Number: 691
Harap laporkan masalah ini, agar kami dapat mencarikan solusinya. Untuk sementara Anda dapat kembali ke halaman awal.** 

Mohon pencerahannya !!! Terimakasih.

**Comment by eddieridwan** [comment]
Sesuai dengan petunjuk install/update OpenSID, apakah sudah menjalankan _Pengaturan > Database > Migrasi DB_?

**Comment by AlfaridzhE** [comment]
belum pak, saya coba dulu.
tapi sebelumnya saya kena masalah saat import db ke phpmyadmin (XAMPP), saya input manual krna cara yang di kasih lewat file bat tetep gak bisa, db nya hanya ter-import sebagian saja.

**Comment by eddieridwan** [comment]
Masalah penggunaan mohon anda tanyakan di https://www.facebook.com/groups/OpenSID/. Banyak yg bisa membantu di situ. Issue dimaksudkan untuk bugs/error/permintaan yg memerlukan perbaikan script.

Issue ini akan kami tutup. Silakan buka lagi kalau ada error yg memerlukan perbaikan aplikasi.

**Comment by AlfaridzhE** [comment]
ok teerima kasih.
