### ISSUE TITLE
Tombol cetak di menu cetak surat -> buat surat tidak muncul

### ISSUE THREAD

**Issue by ayadiyulianto** [OpenSID/OpenSID#2171]
Baru menginstall opensid di localhost, migrasi db sudah dilakukan, tapi pada menu cetak surat -> buat surat, tombol cetak tidak muncul, hanya tombol ekspor dok saja. Tidak error yg terdeteksi.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2019.07-pasca
| Versi PHP        | 7
| System operasi   | W10

**Comment by eddieridwan** [comment]
@ayadiyulianto apakah sudah membaca panduan https://github.com/OpenSID/OpenSID/wiki/Panduan-Konfigurasi-Aplikasi? Lihat setting `tombol_cetak_surat`.

Seperti dijelaskan di https://github.com/OpenSID/OpenSID/wiki/Cetak-Surat, fitur cetak surat langsung akan dihapus pada rilis v20.01 (tgl 1 Januari 2020). Jadi sebaiknya tidak digunakan.

Usahakan mencari informasi di panduan sebelum bertanya. Panduan adalah temanmu.

Untuk bertanya penggunaan OpenSID harap bertanya di https://www.facebook.com/groups/OpenSID/. Issue adalah untuk bugs/error/permintaan yg memerlukan perubahan script.

Issue ini akan kami tutup.

**Comment by ayadiyulianto** [comment]
Terima kasih atas respon cepatnya, mohon maaf saya tadi tidak berhasil menemukan cetak surat di panduan penggunaan opensid 18.09 keatas, saya mencoba bergabung grup fb namun belum disetujui.
Problem solved :)
