### ISSUE TITLE
Cari Lokasi Tempat Tinggal di Ubah Biodata Tanda Markernya Tidak sesuai dengan settingan Lokasi Peta Desa dan Wilayah Desa

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#2174]
### Bagaimana alurnya sampai muncul masalah?
Ketika ingin menambahkan lokasi tempat tinggal penduduk Tanda Markernya Tidak sesuai dengan Settingan yang ada di Peta desa dan Wilayah Desa, Lokasi Yang pertama kali muncul adalah wilayah Yogyakarta, sehingga operator sangat kewalahan untuk memindahkan marker tersebut.
![image](https://user-images.githubusercontent.com/25834335/62304072-dce85180-b4af-11e9-9560-2f6b06ce0fb8.png)

### Seperti apa yang diharapkan?
Harapannya Titik marker tersebut berdasarkan settingan peta desa atau peta wilayah sehingga lebih mempermudah dalam memindahkannya

### Apa yang terjadi?
Operator dan pemerintah desa kesulitan karena posisi terlalu jauh

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR #2175
