### ISSUE TITLE
Lampiran F-2.05 di Surat Kelairan

### ISSUE THREAD

**Issue by muslihramin1** [OpenSID/OpenSID#2176]
### Bagaimana alurnya sampai muncul masalah?
Di Surat Kelahiran tidak ada lampiran f-2.05

### Seperti apa yang diharapkan?
Adanya lampiran F-2.05 pada surat kelahiran

### Apa yang terjadi?
bisa melengkapi persyaratan pengajuan akta kelahiran

### Informasi tambahan 
Di dinas dukcapil disyaratkan form f-2.05 dalam pengajuan akte kelahiran
| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
@muslihramin1 harap lampirkan peraturan terkait termasuk contoh form F-2.05 beserta petunjuk pengisiannya.

**Comment by mizwaruddin** [comment]
@afa28  Lampiran F-2.05 adalah untuk surat keterangan lahir mati.

**Comment by afa28** [comment]
Silahkan reopen jika bermasalah.
