### ISSUE TITLE
Kk tidak bisa di download & surat keteranhan lahir tdak bisa d doenload 

### ISSUE THREAD

**Issue by dagangan352309** [OpenSID/OpenSID#2177]
### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
@dagangan352309 untuk dibantu selalu lampirkan tampakan layar terjadinya error. Dan jelaskan seperti apa data terkait errornya. Kalau di https://demo.opensid.my.id fitur ini berjalan normal, berarti masalah ada di sistem anda, dan tempat bertanyanya di https://www.facebook.com/groups/OpenSID/.

Issue HANYA untuk tempat melaporkan hal2 yg telah diverifikasi memerlukan perbaikan script.

**Comment by uncu29** [comment]
Tidak ada respon dari pembuat issue, bsa diclose pak.
