### ISSUE TITLE
bang tambahin forum satu di situ kayak tempet bergaur masayarakat gitu sama notifikasi kalok ada artikel baru 

### ISSUE THREAD

**Issue by wahyutaqdirulaziz** [OpenSID/OpenSID#2179]
### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
@wahyutaqdirulaziz silakan bergabung di www.facebook.com/groups/OpenSID atau di http://bit.ly/2DG6Beb. Di issue bukan tempat bertanya. Issue adalah tempat mendaftarkan pekerjaan yg memerlukan perubahan script OpenSID.

**Comment by wahyutaqdirulaziz** [comment]
siap bang
