### ISSUE TITLE
Tambahkan paginasi pengambilan pilihan penduduk untuk surat melalui ajax

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#2180]
### Bagaimana alurnya sampai muncul masalah?
Buka form surat sembarang. 
Ketik di kotak pencarian penduduk

### Seperti apa yang diharapkan?
Daftar penduduk tampil sebatas halaman paginasi, supaya tampil lebih cepat

### Apa yang terjadi?
Yang tampil semua penduduk yg memenuhi kriteria pencarian, yang mungkin berjumlah besar.

### Informasi tambahan 

Lihat setting paginasi ajax untuk select2 di https://select2.org/data-sources/ajax

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | v19.08
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.

**Comment by R4HMAT** [comment]
Mantap dan sudah di cobak di Versi Pasca lancar Jos.

**Comment by eddieridwan** [comment]
@R4HMAT jangan lupa laporkan di https://www.facebook.com/groups/OpenSID/ supaya ikut menyebarkan info pengembangan OpenSID dari segi pandang pengguna.

**Comment by R4HMAT** [comment]
Oke Siapa.


Pada tanggal Rab, 7 Agu 2019 pukul 06.33 Eddie Ridwan <
notifications@github.com> menulis:
