### ISSUE TITLE
[keuangan] Perbaikan widget keuangan

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#2184]
### Bagaimana alurnya sampai muncul masalah?
Impor data keuangan
Lihat widget keuangan di halaman web

### Seperti apa yang diharapkan?
Widget keuangan tampak rapi dan mudah dibaca

### Apa yang terjadi?
Tampilan widget perlu perbaikan sebagai berikut:
![perbaikan-widget](https://user-images.githubusercontent.com/249563/62441330-f67ee700-b796-11e9-8283-94872d073ba1.jpg)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | keuangan
| Versi PHP        | 
| System operasi   |

**Comment by stanleydsk** [comment]
Saran tampilan. karena fiturnya memang STATISTIK .. maka sebaiknya setiap realisasi pendapatan desa, juda diberikan minimal prosentasi perbandingan dengan KESELURUHAN TOTAL pendapatan tahun yang ditampilkan ... misalnya item Hasil Usaha Desa (28% dari 100% total pendapatan 2016)

**Comment by eddieridwan** [comment]
Sebagian sudah dikerjakan. Issue ini ditutup. Dan dibuat issue baru untuk yg masih perlu diperbaiki.
