### ISSUE TITLE
format laporan surat masuk dan surat keluar harus 1 lembar

### ISSUE THREAD

**Issue by sukrimalendra** [OpenSID/OpenSID#2186]
### Bagaimana alurnya sampai muncul masalah?
testing

### Seperti apa yang diharapkan?
dalam format pencatatan agenda surat masuk dan surat keluar harus 1 lembar. gambar seperti lampiran pada **informasi tambahan**.

### Apa yang terjadi?
sedangkan laporan pencatatan agenda surat masuk dan surat keluar pada openSID terpisah.

### Informasi tambahan 
![Agenda Surat](https://user-images.githubusercontent.com/30992964/62451714-f8e24080-b798-11e9-987f-d36d3c415e9d.PNG)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
@sukrimalendra untuk perubahan seperti ini, harap lampirkan peraturan terkait, karena perubahan semacam ini akan berdampak pada semua desa. Dengan demikian perlu berbasis peraturan yg jelas.

**Comment by sukrimalendra** [comment]
Format pada poto diatas sesuai dengan Permendagri Nomor 47 Tahun 2016 tentang Administrasi Desa terbaru yang menggantikan Permendagri Nomor 32 Tahun 2006 tentang Pedoman Administrasi Desa yg sudah tidak berlaku.

**Comment by eddieridwan** [comment]
Bung @sukrimalendra akan sangat membantu apabila lampiran peraturan tersebut langsung dilampirkan di issue ini. Kali ini saya lampirkan. Tapi mohon untuk issue selanjutnya anda usahakan agar informasi lengkap disediakan untuk memudahkan programmer. Terima kasih.

[Permendagri_No.47_TH_2016_Lampiran_Administrasi-Pemerintahan-Desa.pdf](https://github.com/OpenSID/OpenSID/files/3475127/Permendagri_No.47_TH_2016_Lampiran_Administrasi-Pemerintahan-Desa.pdf)

**Comment by sukrimalendra** [comment]
Siap bung eddie. Terimakasih

**Comment by afa28** [comment]
Apakah ini masih bermasalah???

**Comment by andifahruddinakas** [comment]
Sudah di master.
