### ISSUE TITLE
Tambah KK baru untuk RW dan RT Tidak Muncul

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#2187]
### Bagaimana alurnya sampai muncul masalah?
Ketika Tambah KK baru setelah memilih Dusun RW dan RT tidak Muncul
![image](https://user-images.githubusercontent.com/25834335/62525580-3e227300-b86a-11e9-966b-65aacc359653.png)

### Seperti apa yang diharapkan?
RW dan RT muncul seperti Versi 19.07

### Apa yang terjadi?
Tidak Bisa Tambah KK baru

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by MUHAMMADRANGSEL** [comment]
Maslah ini terdapat di penduduk_form_isian.php

**Comment by uncu29** [comment]
lihat komen di [Bug] Data List RW Tidak Muncul #2126

**Comment by MUHAMMADRANGSEL** [comment]
SUDAH PAK
