### ISSUE TITLE
Merapikan Panel Statistik halaman Dashboard Home > SID

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#2191]
### Bagaimana alurnya sampai muncul masalah?
Saat belum memiliki data "Bantuan Program" pada dashboard Home > SID, panel statistik bantuan program muncul 0 dengan huruf besar semua.
![Untitled](https://user-images.githubusercontent.com/46939846/62590548-f990e900-b8f6-11e9-84d9-dcf1d5b65a1c.png)

### Seperti apa yang diharapkan?
Agar besar kecil huruf dapat diseragamkan dengan panel statistik lainnya.
![Edited](https://user-images.githubusercontent.com/46939846/62590638-378e0d00-b8f7-11e9-82ee-e8c6caa05bbb.png)

### Apa yang terjadi?
Tampilan panel statistik yang ada di dashboard Home > SID menjadi lebih rapi.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19.08-pasca
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR #2215
