### ISSUE TITLE
[keuangan] Perbaikan widget keuangan

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#2192]
### Bagaimana alurnya sampai muncul masalah?
Impor data keuangan
Lihat widget keuangan di halaman web

### Seperti apa yang diharapkan?
Widget keuangan tampak rapi dan mudah dibaca

### Apa yang terjadi?
Tampilan widget perlu perbaikan sebagai berikut:
![perbaikan-widget-1](https://user-images.githubusercontent.com/249563/62617804-14467a80-b956-11e9-87f2-d361ff057f79.jpg)
![perbaikan-widget-2](https://user-images.githubusercontent.com/249563/62617807-14467a80-b956-11e9-9607-44ff6c81d24c.jpg)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | keuangan
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Masih ada yg perlu diperbaiki, sbb:
![modul-keuangan-4](https://user-images.githubusercontent.com/249563/62821407-a26d6b80-bbb7-11e9-901d-6b8bdc91caad.jpg)

**Comment by kerupuksambel** [comment]
Terimakasih atas koreksinya, namun untuk tulisannya, bila tidak diberi shadow, saya takut akan terkaburkan dengan latar bila panjang grafiknya pendek.

**Comment by eddieridwan** [comment]
> namun untuk tulisannya, bila tidak diberi shadow, saya takut akan terkaburkan dengan latar bila panjang grafiknya pendek.

Ok. Kerjakan sisanya saja.

**Comment by eddieridwan** [comment]
Sudah dikerjakan.
