### ISSUE TITLE
Penambahan Kolom di Unduh Ekspor (Data Penduduk)

### ISSUE THREAD

**Issue by R4HMAT** [OpenSID/OpenSID#2193]
**Bagaimana alurnya sampai muncul masalah?**
    Unduh data Ekspor  Penduduk. 

**Seperti apa yang diharapkan?**
Supaya file format  Ekspor dan Impor Data tersebut supaya sama 
![image](https://user-images.githubusercontent.com/43318683/62747376-58cd3580-ba7e-11e9-9ab6-d1567b8cc6d7.png)

**Apa yang terjadi?**
Ketika mengunduh Ekspor Data Desa (Data Penduduk) untuk Kolom Status Rekam dan Kepemilikan KTP-el tidak ada. 

Tanya             | Jawab
-- | --
Versi OpenSID | Penamabahan kolom
Versi PHP |  
System operasi

**Comment by eddieridwan** [comment]
Telah dicommit ke master melalui PR #2198

**Comment by R4HMAT** [comment]
apakah bisa di cek di demo pasca pra rilis.
