### ISSUE TITLE
[Bug] Tanda (') petik tidak muncul di penduduk

### ISSUE THREAD

**Issue by R4HMAT** [OpenSID/OpenSID#2194]
**Bagaimana alurnya sampai muncul masalah?**
tanda petik (') pada nama penduduk tidak muncul di penduduk dan di Ekspor penduduk
Data sebelum di Impor tanda (') Petik pada nama ada sesuai dengan format impor penduduk

![klh16](https://user-images.githubusercontent.com/43318683/62748423-c0857f80-ba82-11e9-8ec1-f4278cb7dc1b.png)
Data sesudah di Impor tanda (') Petik pada nama tidak ada pada menu penduduk di Aplikasi

**Seperti apa yang diharapkan?**
Supaya file format Excel sebelum di impor dan  di Ekspor dan atau sudah masuk di aplikasi ada tanda (') petik pada nama penduduk.

![klh17](https://user-images.githubusercontent.com/43318683/62749303-16a7f200-ba86-11e9-88a2-557934117127.png)

Tanya | Jawab
-- | --
Versi OpenSID | Penamabahan Tanda (') Petik
Versi PHP |  
System operasi

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR #2197

**Comment by R4HMAT** [comment]
apakah sudah bisa di cobak di master Pra Rilis.
