### ISSUE TITLE
[Database] Penambahan Kolom pada format Impor dan Ekspor

### ISSUE THREAD

**Issue by R4HMAT** [OpenSID/OpenSID#2201]
**Bagaimana** alurnya sampai muncul masalah?**
   Cek kembali Format  Impor data Penduduk dan Ekspor data penduduk.
 
![klh 19](https://user-images.githubusercontent.com/43318683/62825482-83320680-bbd6-11e9-8688-91b9699e3cb8.png)

**Seperti apa yang diharapkan?**
Supaya file format Ekspor dan Impor perlu di tambahkan kolom Pekerjaan dalam KK dan Pekerjaan yang sedang di tempuh  **seperti pendidikan dlm KK dan pendidikan sedang ditempuh ** dikarenakan sebagian besar masyarakat ketika membuat KK pada saat pengisian pekerjaan tidak sesuai dengan keadaan yang sebenarnya.

Tanya | Jawab
-- | --
Versi OpenSID | Penamabahan kolom
Versi PHP |  
System operasi

**Comment by af-lazuardi** [comment]
@eddieridwan , apakah issue ini bisa dikerjakan? dengan menambah field pekerjaan_saat_ini di data penduduk?

**Comment by eddieridwan** [comment]
@af-lazuardi , boleh, tapi perlu juga:
- menambahkan ke semua form isian penduduk
- menampilkan di semua laporan rincian biodata penduduk

**Comment by af-lazuardi** [comment]
Siap, saya trace dulu keperluannya dimana saja

**Comment by R4HMAT** [comment]
ta tunggu iya pak @af-lazuardi

**Comment by afa28** [comment]
Apakah ini masih bermasalah???

**Comment by af-lazuardi** [comment]
saya sudah lama gak ngikuti mas, coba dicek

**Comment by mizwaruddin** [comment]
Menurut saya hal ini cukup diselesaikan dengan cara menanyakan kembali pekerjaan kepada pemohon saat melakukan perbaikan KK.

**Comment by afa28** [comment]
> Menurut saya hal ini cukup diselesaikan dengan cara menanyakan kembali pekerjaan kepada pemohon saat melakukan perbaikan KK. 

Mungkin untuk membedakan pekerjaan yg di KK dan yg saat ini, sama halnya dgn pendidikan.
