### ISSUE TITLE
Tampilan citra satelit pada peta sekarang tidak tersedia

### ISSUE THREAD

**Issue by egodasa** [OpenSID/OpenSID#2202]
### Bagaimana alurnya sampai muncul masalah?
Pada halaman beranda, lihat dibagian widget peta.

### Seperti apa yang diharapkan?
Ada pilihan citra satelit untuk widget peta, termasuk juga dengan fitur peta pada halaman admin opensid.

### Apa yang terjadi?
Tidak adanya pilihan untuk menampilkan citra satelit pada fitur peta opensid.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Citra satelit telah ditampilkan di Pemetaan > Peta dan di Pemetaan > Pengaturan Peta.

Issue ini belum ditutup, karena citra satelit belum ditampilkan di widget wilayah desa atau di widget lokasi kantor desa.

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR dari @fusionid
