### ISSUE TITLE
link artikel dari komentar masih menggunakan id

### ISSUE THREAD

**Issue by bizanniusz** [OpenSID/OpenSID#2204]
### Bagaimana alurnya sampai muncul masalah?
pada update slug, link artikel dari widget komentar belum menggunkan slug

### Seperti apa yang diharapkan?
link artikel dari widget komentar juga harus menggunakan slug

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by kusmantopratama** [comment]
setelah update terjadi error di query ..  pesan error "Unknow Column slug in where clause" ,,, column slug ini di tambah nya di table apa ya ? saya ubek di contoh file .sql nya ga ada colom slug

**Comment by adlersentinel** [comment]
> setelah update terjadi error di query .. pesan error "Unknow Column slug in where clause" ,,, column slug ini di tambah nya di table apa ya ? saya ubek di contoh file .sql nya ga ada colom slug

itu issue baru di update belum 24jam, clone ulang trus migrasi database

**Comment by dikisiswanto** [comment]
@kusmantopratama lakukan migrasi DB

**Comment by kusmantopratama** [comment]
ok work .. thanks... oh iya . untuk slug ini sudah ada helper buat meta di themes nya ? atau untuk slug ini tidak di masukan ke meta data ?

**Comment by adlersentinel** [comment]
> ok work .. thanks... oh iya . untuk slug ini sudah ada helper buat meta di themes nya ? atau untuk slug ini tidak di masukan ke meta data ?

itu tergantung masing2 thema

**Comment by kusmantopratama** [comment]
> > ok work .. thanks... oh iya . untuk slug ini sudah ada helper buat meta di themes nya ? atau untuk slug ini tidak di masukan ke meta data ?
> 
> itu tergantung masing2 thema

ok makasih pak.

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR #2205
