### ISSUE TITLE
tidak bisa akses halaman layanan mandiri , dan beberapa halaman lain seperti halaman arsip . selalu redirect ke halaman 404 page not found

### ISSUE THREAD

**Issue by kusmantopratama** [OpenSID/OpenSID#2206]
### Bagaimana alurnya sampai muncul masalah?
setelah update beberapa menit lalu saya mencoba fungsi login untuk mengakses halaman mandiri ... 
ketika submit form hanya meredirect ke  
urlhostsid/index.php/first/auth dan hanya muncul halaman eror 404 .. sudah cek dan di coba berkali2 dengan nik dan pin yang benar tetap meredirect ke halaman eror 404 

kemudian di web demo juga sama . dan bukan hanya halaman mandiri saja tapi di halaman lain juga sama seperti halaman arsip, dan beberapa halaman lain nya

### Seperti apa yang diharapkan?
bisa login kembali untuk mengakses halaman mandiri . 

### Apa yang terjadi?
pengguna yang ingin mengakses halaman mandiri tidak bisa login . 

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by uncu29** [comment]
Untuk demo ap lokal pak?

**Comment by uncu29** [comment]
Apakah sudah coba yg didemo?

**Comment by kusmantopratama** [comment]
Di demo juga sama .. bukan hanya pada halaman mandiri saja tapi berdampak pada semua halaman atau method yang ada di controller first kecuali untuk halaman artikel saja

**Comment by uncu29** [comment]
Seteleah saya coba distus demo mmng benr terjdi error. Data sdh benar
![Screenshot_2019-08-12-23-15-41-233_com android chrome](https://user-images.githubusercontent.com/51182125/62880334-5eb16800-bd57-11e9-9f99-86b77fbd97bc.png)

**Comment by uncu29** [comment]
Untuk arsip dbagian mna error pak, saya buka tdr error

**Comment by kusmantopratama** [comment]
> Untuk arsip dbagian mna error pak, saya buka tdk error

pas di widget ada widget Arsip . ketika di klik  title arsip .. akan mengarah ke URL "http://demo.opensid.my.id/index.php/first/arsip" .. pada versi sebelum ditambahkan slug ... ini bisa membuka halaman data arsip ... tapi setelah update penambahan fitur slug halaman tersebut jadi error 404 ... apabila menambahkan parameter halaman misal "http://demo.opensid.my.id/index.php/first/arsip/1" maka data muncul .

**Comment by uncu29** [comment]
Setelah saya masuk melalui laptop tidak ada masalah pak
![Website Resmi Desa Banyu Urip - Arsip - Mozilla Firefox 13_08_2019 08_42_04](https://user-images.githubusercontent.com/51182125/62909328-59c7d500-bda6-11e9-93c8-05710cf4fc99.png)
![Website Resmi Desa Banyu Urip - Arsip - Mozilla Firefox 13_08_2019 08_42_23](https://user-images.githubusercontent.com/51182125/62909330-5a606b80-bda6-11e9-975d-46ec40cc275d.png)

**Comment by kusmantopratama** [comment]
Ok sudah fix ... saya lihat terakhir commit oleh pak eddi dengan message "hapus route yg mengganggu" dan akhir nya issue ini sudah fix ..

**Comment by Yuzaku27** [comment]
<img width="662" alt="Image" src="https://github.com/user-attachments/assets/ba0243e9-db14-426c-8f09-20437f6a25f0" />


seperti ini bagaimana solusinya
