### ISSUE TITLE
Tampilan resume APBDes untuk untuk umum dalam siskeudes seperti ini

### ISSUE THREAD

**Issue by M-A-Haris** [OpenSID/OpenSID#2207]
![lamp-i-ringkasan-apbdes-dan-lampiran-ii-rincian-abdes-1-638](https://user-images.githubusercontent.com/46555658/62868787-9fea4d80-bd40-11e9-89ce-cc8b0cc1cb01.jpg)

### Bagaimana alurnya sampai muncul masalah?
Terlalu lebar dan lebih rinci, namjn sesuai dengan permendagri 20 tentang keuangan desa

### Seperti apa yang diharapkan?
Bisa didownload dengan tampilan reaume APBDes Siskeudes

# Apa yang terjadi?
Yang dibutuhkan link kode rekening Sesuai permendagri dan jenis sumber anggaran ADD, DD, PBH,

**Comment by mizwaruddin** [comment]
@afa28 laporan keuangan dari siskeudes/manual sdh bisa ditampilkan di web.
