### ISSUE TITLE
Error 500 di php v 7.x saat akses link artikel dengan parameter id

### ISSUE THREAD

**Issue by kusmantopratama** [OpenSID/OpenSID#2208]
### Bagaimana alurnya sampai muncul masalah?
pada php versi 7.1 keatas terjadi error ketika akses halaman artikel menggunakan id bukan menggunakan slug .. ini terjadi ketika redirect setelah mengirim komentar... sudah di coba di local dan di host tetap error seperti ini . 
![Capture](https://user-images.githubusercontent.com/16215220/62939170-d2588100-bdfa-11e9-8e69-605154eaf0b4.JPG)

### Seperti apa yang diharapkan?
dapat membuka link artikel dengan parameter id , 

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19.08-pasca
| Versi PHP        |  7.2
| System operasi   | windows, linux

**Comment by eddieridwan** [comment]
Apakah sudah coba di demo.opensid.my.id? Artikel bisa diakses menggunakan id atau tulisan.

**Comment by kusmantopratama** [comment]
@eddieridwan  sudah pak di demo berjalan normal ... tapi ketika di local saya , dan di hosting terjadi error tersebut ... ketika saya tambahkan value default untuk parameter pada method artikel aplikasi berjalan normal kembali. ... saya pake php versi 7.2 .

**Comment by eddieridwan** [comment]
Telah dicommit ke master melalui PR #2209
