### ISSUE TITLE
HTTP ERROR 500 saat akses homepage 

### ISSUE THREAD

**Issue by bakhtiyarsierad** [OpenSID/OpenSID#2210]
### Bagaimana alurnya sampai muncul masalah?
Setelah upload data penduduk melalui proses  lewat siteman, database, import bip. Selesai upload, home page menjadi http eror 500. namun saya masih bisa akses halaman admin nya

![Capture](https://user-images.githubusercontent.com/7570307/62946193-739b0380-be0a-11e9-8419-16f89006c3e5.PNG)

### Seperti apa yang diharapkan?
Harapannya dapat diakses tampil normal

### Apa yang terjadi?
halaman homepage tidak dapat diakses. namun halaman admin masih bisa diakses

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19.07
| Versi PHP        | 5.6
| System operasi   | Linux

**Comment by junandia** [comment]
Mungkin bisa dicek di log error nya pak

**Comment by tyrsrd** [comment]
> Mungkin bisa dicek di log error nya pak

untuk log eror nya seperti berikut

```
ERROR - 2019-08-15 19:23:46 --> Severity: error --> Exception: Session: Configured save path '/opt/alt/php56/var/lib/php/session' is not a directory, doesn't exist or cannot be created. /home/pakelmon/domains/pakel-montong.desa.id/public_html/system/libraries/Session/drivers/Session_files_driver.php 138
ERROR - 2019-08-15 19:23:46 --> Session: Unable to open file '17calltlobdtndtbivhllj5s6ivtq0pt'.
ERROR - 2019-08-15 19:23:51 --> Severity: error --> Exception: Session: Configured save path '/opt/alt/php56/var/lib/php/session' is not a directory, doesn't exist or cannot be created. /home/pakelmon/domains/pakel-montong.desa.id/public_html/system/libraries/Session/drivers/Session_files_driver.php 138
ERROR - 2019-08-15 19:23:51 --> Session: Unable to open file '17calltlobdtndtbivhllj5s6ivtq0pt'.
ERROR - 2019-08-15 19:24:02 --> Severity: error --> Exception: Session: Configured save path '/opt/alt/php56/var/lib/php/session' is not a directory, doesn't exist or cannot be created. /home/pakelmon/domains/pakel-montong.desa.id/public_html/system/libraries/Session/drivers/Session_files_driver.php 138
ERROR - 2019-08-15 19:24:02 --> Session: Unable to open file '17calltlobdtndtbivhllj5s6ivtq0pt'.
```

**Comment by eddieridwan** [comment]
Coba lampirkan di sini file `donjo-app/config/config.php` .

**Comment by redjoel** [comment]
Error ini berkaitan dengan kurang lengkapnya Database terimport

Silakan cek database, apakah sudah memiliki tabel sebanyak 111 di 19.07 kebawah (di 19.09 jadi 113 sih)

**Comment by afa28** [comment]
Ini menggunakan versi lama, coba lakukan proses tsb di versi terbaru. Jika masih mengalami masalah silahkan reopen atau buat issue baru mengenai hal ini. 🙏
