### ISSUE TITLE
>>>>>>>>>>>> Link gambar modul keuangan (panduan) -- arsip

### ISSUE THREAD

**Issue by ekasatriabahari** [OpenSID/OpenSID#2219]
![keuangan 1](https://user-images.githubusercontent.com/39932698/63138593-acef9100-c00d-11e9-9dae-cdedc8f149fe.png)
![keuangan 2](https://user-images.githubusercontent.com/39932698/63138594-acef9100-c00d-11e9-9a1c-f082d2eee074.png)
![keuangan 3](https://user-images.githubusercontent.com/39932698/63138595-ad882780-c00d-11e9-99fe-cc5118f611de.png)
![keuangan 4](https://user-images.githubusercontent.com/39932698/63138597-ad882780-c00d-11e9-8a67-94130a4819fd.png)
![keuangan 5](https://user-images.githubusercontent.com/39932698/63138599-ad882780-c00d-11e9-80c7-e0b6bb54c00b.png)

**Comment by ekasatriabahari** [comment]
![keuangan 9](https://user-images.githubusercontent.com/39932698/63232502-347e0f80-c25b-11e9-9fd5-763b6eaa980b.png)
![keuangan 6](https://user-images.githubusercontent.com/39932698/63232503-347e0f80-c25b-11e9-8c18-f8463049210a.png)
![keuangan 7](https://user-images.githubusercontent.com/39932698/63232505-3516a600-c25b-11e9-94b5-2175b2029f4a.png)
![keuangan 8](https://user-images.githubusercontent.com/39932698/63232506-3516a600-c25b-11e9-8019-5a4a48d7c689.png)

**Comment by ekasatriabahari** [comment]
![field8](https://user-images.githubusercontent.com/39932698/64233079-e1c47900-cf25-11e9-9627-d0e85beea105.png)
![field1](https://user-images.githubusercontent.com/39932698/64233081-e25d0f80-cf25-11e9-910f-d137ba0c747d.png)
![field2](https://user-images.githubusercontent.com/39932698/64233082-e25d0f80-cf25-11e9-88e0-d2b63577d6ea.png)
![field3](https://user-images.githubusercontent.com/39932698/64233083-e25d0f80-cf25-11e9-9e42-149f2f840ce8.png)
![field4](https://user-images.githubusercontent.com/39932698/64233084-e2f5a600-cf25-11e9-83a6-c9a7da80c537.png)
![field5](https://user-images.githubusercontent.com/39932698/64233086-e2f5a600-cf25-11e9-9dab-51c5a33d1f17.png)
![field6](https://user-images.githubusercontent.com/39932698/64233087-e38e3c80-cf25-11e9-95db-69cdb39ef935.png)
![field7](https://user-images.githubusercontent.com/39932698/64233088-e38e3c80-cf25-11e9-9cc4-d065d5bfd46e.png)

**Comment by kerupuksambel** [comment]
![Widget - 1](https://user-images.githubusercontent.com/24503760/65029275-a6836a80-d967-11e9-9345-33ee5538d9b7.png)
![Widget - 2](https://user-images.githubusercontent.com/24503760/65029276-a7b49780-d967-11e9-9edc-9f17e4aa1745.png)
![Widget - 3](https://user-images.githubusercontent.com/24503760/65029277-a7b49780-d967-11e9-9cdd-b5284dfc5e82.png)
![Widget - 5](https://user-images.githubusercontent.com/24503760/65029278-a84d2e00-d967-11e9-914c-4011d9f954c9.png)

**Comment by uncu29** [comment]
![The conversion was successful! - RebaseData - Mozilla Firefox 11_10_2019 22 44 58](https://user-images.githubusercontent.com/51182125/66665817-877fac00-ec79-11e9-83b5-e3fc92760c6c.png)
![The conversion was successful! - RebaseData - Mozilla Firefox 11_10_2019 22 46 36](https://user-images.githubusercontent.com/51182125/66665820-88184280-ec79-11e9-8985-565452cd35c2.png)
