### ISSUE TITLE
edit no KK dan alamat

### ISSUE THREAD

**Issue by afri18** [OpenSID/OpenSID#222]
![image](https://cloud.githubusercontent.com/assets/6611881/21072780/50c37a1a-bf00-11e6-99d2-19117edfbeb2.png)

<script type="text/javascript" src="<?php echo base_url()?>assets/js/jquery.validate.min.js"></script>
<script type="text/javascript" src="<?php echo base_url()?>assets/js/validasi.js"></script>
<script type="text/javascript" src="<?php echo base_url()?>assets/js/donjoscript/donjoscript2.js"></script>
<form action="<?php echo $form_action?>" method="post" id="validasi">
<table style="width:100%">
	<tr>
		<th align="left">Nomor KK</th>
		<td>
			<input type="text" name="no_kk" value="<?php echo $kk['no_kk']?>" class="inputbox required">
		</td>
	</tr>
	<tr>
	<th align="left">Alamat</th>
		<td>
			<input type="text" name="alamat" value="<?php echo $kk['alamat']?>" class="inputbox required" size="60">
		</td>
	</tr>
	<tr>
		<th align="left">Tanggal Cetak Kartu Keluarga</th>
		<td>
			<input name="tgl_cetak_kk" type="text" value="<?php echo $kk['tgl_cetak_kk']?>" class="inputbox  datepicker" size="20">
		</td>
	</tr>
<?php /*
<tr>
	<th align="left">Kelas Sosial</th>
	<td>
	<div class="uiradio">
	<input type="radio" id="ks1" name="kelas_sosial" value="1"/<?php if($kk['kelas_sosial'] == '1'){echo 'checked';}?>>
	<label for="ks1">Sangat Miskin</label>
	<input type="radio" id="ks2" name="kelas_sosial" value="2"/<?php if($kk['kelas_sosial'] == '2' OR $kk['kelas_sosial'] == '0'){echo 'checked';}?>>
	<label for="ks2">Miskin</label>
	<input type="radio" id="ks3" name="kelas_sosial" value="3"/<?php if($kk['kelas_sosial'] == '3'){echo 'checked';}?>>
	<label for="ks3">Hampir Miskin</label>
	<input type="radio" id="ks4" name="kelas_sosial" value="4"/<?php if($kk['kelas_sosial'] == '4'){echo 'checked';}?>>
	<label for="ks4">Tidak Miskin</label>
	</div>
	</td>
</tr>
*/?>
<tr>
	<th align="left">Raskin</th>
	<td>
	<div class="uiradio">
	<input type="radio" id="rs1" name="raskin" value="1"/<?php if($kk['raskin'] == '1'){echo 'checked';}?>>
	<label for="rs1">Ya</label>
	<input type="radio" id="rs2" name="raskin" value="2"/<?php if($kk['raskin'] == '2' OR $kk['raskin'] == ''){echo 'checked';}?>>
	<label for="rs2">Tidak</label>
	</div>
	</td>
</tr>
<tr>
	<th align="left">BLSM</th>
	<td>
	<div class="uiradio">
	<input type="radio" id="rs1" name="id_blt" value="1"/<?php if($kk['id_blt'] == '1'){echo 'checked';}?>>
	<label for="rs1">Ya</label>
	<input type="radio" id="rs2" name="id_blt" value="2"/<?php if($kk['id_blt'] == '2' OR $kk['id_blt'] == ''){echo 'checked';}?>>
	<label for="rs2">Tidak</label>
	</div>
	</td>
</tr>
<tr>
	<th align="left">PKH</th>
	<td>
	<div class="uiradio">
	<input type="radio" id="rs1" name="id_pkh" value="1"/<?php if($kk['id_pkh'] == '1'){echo 'checked';}?>>
	<label for="rs1">Ya</label>
	<input type="radio" id="rs2" name="id_pkh" value="2"/<?php if($kk['id_pkh'] == '2' OR $kk['id_pkh'] == ''){echo 'checked';}?>>
	<label for="rs2">Tidak</label>
	</div>
	</td>
</tr>
<tr>
	<th align="left">Bedah Rumah</th>
	<td>
	<div class="uiradio">
	<input type="radio" id="rs1" name="id_bedah_rumah" value="1"/<?php if($kk['id_bedah_rumah'] == '1'){echo 'checked';}?>>
	<label for="rs1">Ya</label>
	<input type="radio" id="rs2" name="id_bedah_rumah" value="2"/<?php if($kk['id_bedah_rumah'] == '2' OR $kk['id_bedah_rumah'] == ''){echo 'checked';}?>>
	<label for="rs2">Tidak</label>
	</div>
	</td>
</tr>
</tbody>
        </table>
<div class="buttonpane" style="position:absolute;bottom:0px;right:0px;">
    <div class="uibutton-group">
        <button class="uibutton" type="button" onclick="$('#window').dialog('close');">Tutup</button>
        <button class="uibutton confirm" type="submit">Simpan</button>
    </div>
</div>
</form>

**Comment by eddieridwan** [comment]
Apakah yang diinginkan adalah penampilan form ini sebagai tabel? Atau ada yang lainnya?

**Comment by eddieridwan** [comment]
Bung @afri18 , tolong jelaskan apa yang dimaksud dengan issue ini. Perubahan apa yang diinginkan? Harap dirinci.

**Comment by eddieridwan** [comment]
Issue ini ditutup karena form Ubah Data KK sudah berubah. Silakan buat issue baru bila perlu.
