### ISSUE TITLE
Tidak bisa tambah artikel baru di OpenSID 19.08-pasca

### ISSUE THREAD

**Issue by af-lazuardi** [OpenSID/OpenSID#2225]
### Bagaimana alurnya sampai muncul masalah?
Setelah fresh instal aplikasi OpenSID 19.08-pasca dan import data awal dari contoh_data_awal_20190731.sql. Saat ingin membuat artikel baru, data artikel baru tidak dapat disimpan. 

### Seperti apa yang diharapkan?
Data harusnya berhasil tersimpan di database. Dan dapat dilihat penambahan artikel baru di situs website.

### Apa yang terjadi?
muncul error sebagai berikut:
![error](https://user-images.githubusercontent.com/13193883/63220845-c2092300-c1b9-11e9-97d1-b8ebaf84b9cf.png)

### Informasi tambahan 
Setelah dilihat di structure database pada tabel artikel memang tidak terdapat atribut 'slug' pada tabel tersebut.
![structure](https://user-images.githubusercontent.com/13193883/63220847-cf261200-c1b9-11e9-9a09-2f3b40033442.png)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19.08-pasca
| Versi PHP        | PHP Version 7.0.33
| System operasi   | ubuntu0.16.04.1

**Comment by af-lazuardi** [comment]
Problem ini sudah saya solve dengan menambahkan atribut 'slug' dengan tipe 'varchar(255)'. Jika memang seperti ini solusinya, Pada file contoh_data_awal_20190731.sql bisa saya tambahkan atribut tersebut pada structure tabel artikel, dan saya commit perbaikan strkturnya. Mohon konfirmasi Pak @eddie

**Comment by af-lazuardi** [comment]
Problem ini sudah saya solve dengan menambahkan atribut 'slug' tipe 'varchar(255) pada struktur table 'artikel'. Jika memang begitu solusinya, saya bisa tambahkan di file contoh_data_awal_20190731.sql atribut tersebut, dan saya commit(PR) perbaikannya. Mohon konfirmasi Pak @eddieridwan
terima kasih

**Comment by af-lazuardi** [comment]
/home/rif/Pictures/Screenshot from 2019-08-18 12-38-41.png

**Comment by af-lazuardi** [comment]
file:///home/rif/Pictures/error.png

**Comment by adlersentinel** [comment]
seharusnya, setelah import sql lakukan migrasi database, karna perubahan pembaharuan tabel itu dilakukan saat migrasi database

**Comment by af-lazuardi** [comment]
Oke, mungkin berarti solusinya bisa ada 2 pendekatan:
1. menambahkan petunjuk untuk melakukan migrasi setelah fresh install di https://github.com/opensid/opensid/wiki/Panduan-Install-OpenSID
2. menambahkan atribut slug tersebut di contoh_data_awal_xxxxx.sql

Lebih efektif mana kira2 Pak @adlersentinel ?

**Comment by adlersentinel** [comment]
> Oke, mungkin berarti solusinya bisa ada 2 pendekatan:
> 
> 1. menambahkan petunjuk untuk melakukan migrasi setelah fresh install di https://github.com/opensid/opensid/wiki/Panduan-Install-OpenSID
> 2. menambahkan atribut slug tersebut di contoh_data_awal_xxxxx.sql
> 
> Lebih efektif mana kira2 Pak @adlersentinel ?

sebenarnya efektif itu sesuai petunjuk yaitu migrasi database itu udah sesuai aturan dan system yg sudah dibuat tujuannya untuk mempermudah pengguna awam, karna perbaikan tabel database banyak dilakukan saat migrasi database, supaya tidak terjadi error 500 akibat table yg tidak tersedia

**Comment by af-lazuardi** [comment]
Oke, berarti ini di panduan instalasi perlu ditambahi langkah untuk melakukan migrasi DB ya Pak. Saya bisa tambahi petunjuk tersebut di md nya. Ini kasusnya untuk fresh install Pak, bukan update OpenSID dari versi sebelumnya ke versi terbaru.

Untuk fresh install tidak ada petunjuk melakukan migrasi DB. 

Saya pikir kalau untuk mempermudah pengguna awam, justru solusi nomor 2 yang menambahkan atribut slug pada contoh_data_awal_xxxx.sql itu lebih mempermudah mereka. Sehingga kita tidak perlu update petunjuk lagi di wiki cara instalasi openSID.

Bagaimana?

**Comment by adlersentinel** [comment]
sebenarnya tujuannya tidak hanya melakukan update, tapi juga perkenalan tools krna sayang dibuat tapi tidak dimanfaatkan sebagaimana mestinya.

**Comment by af-lazuardi** [comment]
> sebenarnya tujuannya tidak hanya melakukan update, tapi juga perkenalan tools krna sayang dibuat tapi tidak dimanfaatkan sebagaimana mestinya.

tools migrasi DB maksudnya Pak? Fitur tersebut pasti akan selalu digunakan buat yang mau udpate OpenSID dari versi sebelumnya ke versi terbaru Pak.

Baik gimana ini baiknya solusi yang dipilih, 

> Oke, mungkin berarti solusinya bisa ada 2 pendekatan:
> 
> 1. menambahkan petunjuk untuk melakukan migrasi setelah fresh install di https://github.com/opensid/opensid/wiki/Panduan-Install-OpenSID
> 2. menambahkan atribut slug tersebut di contoh_data_awal_xxxxx.sql
> 
> Lebih efektif mana kira2 Pak @adlersentinel ?
Dikerjakan salah satunya saja, atau bahkan kedua solusi itu dikerjakan semua. Saya ready untuk PR. Kita tunggu pertimbangan dari Pak @eddieridwan aja ya.

**Comment by eddieridwan** [comment]
@af-lazuardi @adlersentinel :
1. contoh data awal saat ini hanya dilengkapi untuk rilis resmi (v19.07, v19.08 dstnya) yang dirilis setiap tgl 1. Pengguna pemula dianjurkan menggunakan versi rilis resmi ini, yg umumnya juga disediakan installer untuk Windows. Yang menginstal awal menggunakan rilis resmi tidak perlu melakukan migrasi, karena contoh data awal sudah lengkap. 
2. branch `master` dimaksudkan untuk commit perbaikan dan perubahan secepat mungkin supaya bisa dimanfaatkan oleh pengguna yg sudah mapan (bukan pemula). Commit ke branch `master` bisa dilakukan setiap saat. Pelengkapan contoh data awal tidak praktis dilakukan setiap kali ada commit yg mengubah struktur database. Pengguna ya membutuhkan commit terkini dianggap cukup mampu untuk menjalankan migrasi DB.

**Comment by eddieridwan** [comment]
Mungkin panduan bisa dilengkapi untuk menjelaskan: apabila melakukan instal awal menggunakan versi pra-rilis (branch `master`), maka perlu melakukan migrasi DB. 

Perbaikan panduan itu mungkin bisa ditambahkan di https://github.com/OpenSID/OpenSID/wiki/Panduan-Install-OpenSID. 

Silakan kalau teman2 mau melengkapi panduan. Tapi pastikan telah membaca panduan install/update yg ada secara seksama dulu, supaya tidak ada duplikasi dan informasinya diletakkan di tempat yg paling tepat.

**Comment by eddieridwan** [comment]
Untuk proses pelengkapan contoh data awal, silakan teman2 ikuti proses melakukan rilis setiap tgl 1: https://github.com/OpenSID/OpenSID/wiki/Proses-Rilis

**Comment by af-lazuardi** [comment]
Baik Pak. Saya tambahkan saja informasi untuk melakukan migrasi jika menggunakan versi pra rilis di panduan wiki install opensid (solusi no 2 yang diajukan).

Terima kasih @eddieridwan dan @adlersentinel

**Comment by af-lazuardi** [comment]
saya sudah tambah informasi migrasi db bagi pengguna baru OpenSID yang menggunakan versi pra rilis di [05fcff4](https://github.com/OpenSID/OpenSID/wiki/Panduan-Install-OpenSID/05fcff45f88bd38c6634e2b761752d094d68ed05)
