### ISSUE TITLE
Sediakan fitur untuk ubah isian Keterangan pada log surat di Arsip Layanan

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#2226]
### Bagaimana alurnya sampai muncul masalah?
1. Buka Layanan Surat > Arsip Layanan
2. Cari fitur untuk mengubah isian Keterangan

### Seperti apa yang diharapkan?
Ada tombol Aksi untuk mengubah isian Keterangan.

### Apa yang terjadi?
Tidak ada fitur untuk mengubah Keterangan

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | v19.08
| Versi PHP        | 
| System operasi   |

**Comment by uncu29** [comment]
Bsa diterima prny pak?

**Comment by eddieridwan** [comment]
Ada dua pull request untuk issue ini. Bung @kusmantopratama akan melakukan review untuk menentukan pull request mana yg dapat digabung.

**Comment by uncu29** [comment]
> 
> 
> Ada dua pull request untuk issue ini. Bung @kusmantopratama akan melakukan review untuk menentukan pull request mana yg dapat digabung.

ok pak

**Comment by kusmantopratama** [comment]
Baik pak @eddieridwan  terimakasih atas kesempatan nya untuk bisa ikut serta berkontribusi. 

Terimakasih juga kepada bung @uncu29  dan bung @agungsugiarto , berdasarkan hasil review yang saya terima keduanya sudah memenuhi harapan pada thread issue ini yaitu menambahkan fungsi edit keterangan ...  namun ada sedikit perbedaan dari hasil yang di pull oleh bung @uncu29  dan bung @agungsugiarto ,, fitur yang di buat hanya penambahan form untuk **"Edit kolom keterangan"** . dan berikut hasil reviewnya : 

1. bung @uncu29  menambahkan kalimat "Sebagai Surat {klasifikasi} + keterangan di database" pada setiap kolom kenetrangan baik itu di tampilan tabel aplikasi nya maupun di tampilan cetak atau print.  sementara bung @agungsugiarto  tidak menambahkan kata seperti pull request dari bung @uncu29 
2. untuk form edit nya bung @uncu29 menggunakan form biasa sementara bung @agungsugiarto  menggunakan form popup atau modals.
3. **"KEKURANGAN MINOR"** baik bung @uncu29  dan bung @agungsugiarto  sama2 tidak menerapken fungsi request sesuai dengan aturan dari framework yang digunakan sehingga tidak bisa memfilter inputan **XSS**  ... sebenernya ini tidak terlalu krusial karena untuk fitur ini tidak di open ke public .. tapi alangkah baiknya membiasakan untuk pengamanan form .



selanjutnya pak @eddieridwan  yang dapat memutuskan pull request milik siapa yang akan di merge... untuk fitur edit kolom **komentar** keduanya sudah bisa melakukan editing data pada kolom tersebut. 

Terimakasih.

**Comment by eddieridwan** [comment]
Terima kasih pada @uncu29 dan @agungsugiarto yg telah mengerjakan issue ini. Sebagai info, sebaiknya periksa dulu apakah sudah ada yg mengirim pull request sebelum mengerjakan -- untuk menghindari duplikasi.

Terima kasih pada @kusmantopratama yg telah melakukan review awal.

Sayang hanya satu solusi yg bisa diambil. Ok, kita akan gunakan solusi dari bung @agungsugiarto , karena sepertinya cukup menggunakan form modal dialog. Maaf, bung @uncu29 , PR anda ditutup saja. Sekali lagi terima kasih.

Bung @kusmantopratama , mohon anda sekarang review kembali PR https://github.com/OpenSID/OpenSID/pull/2229 dan beri 'review comments` di PR-nya meminta perubahan yg diperlukan, misalnya menjaga terhadap serangan XSS.  Juga melihat tampilan di halaman arsip sekarang tampaknya terlalu ramai, terutama di kolom Aksi. Mungkin tulisan di tombol unduh surat dan unduh lampiran bisa dihapus saja. Terima kasih.

**Comment by MUHAMMADRANGSEL** [comment]
Mungkin **Keterangan** di Ganti dengan **Keperluan** menurut saya lebih tepat, karena kebanyakan surat tertulis **Keperluan**

**Comment by MUHAMMADRANGSEL** [comment]
Mengubah keperluan hanya admin

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR #2229
