### ISSUE TITLE
[kab50kota] Penambahan fitur Permohonan surat pada Layanan Mandiri

### ISSUE THREAD

**Issue by jutexs** [OpenSID/OpenSID#2235]
### Bagaimana alurnya sampai muncul masalah?
Layanan mandiri hanya berisi data penduduk yang login, dan penduduk hanya dapat memberikan saran dan kritik saja.

### Seperti apa yang diharapkan?
Pada layanan mandiri penduduk dapat memohon surat, dengan cara memilih jenis surat, dan mengisi keperluan. Ketika admin login ke layanan mandiri, pada menu itu bukan hanya kotak masuk, tetapi ada penambahan permohonan surat dari penduduk, admin desa bertugas memverifikasi dan mencetak surat yang dimohon penduduk, setelah yang bersangkutan datang ke kantor desa.

### Apa yang terjadi?
Desa bisa memberikan layanan self service pada masyarakat dan secara otomatis masyarakat yang mengunjungi web desa akan meningkat.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
@jutexs : apakah ini sama dengan #398, #791, #341, #1976?

Sepertinya fitur ini penting bagi banyak desa. Cara untuk mempercepat fitur ini adalah supaya desa2 yg memerlukan menganggarkan secara patungan, supaya kita bisa bayar programmer.

**Comment by jutexs** [comment]
Iya betul bang...

**Comment by WAHYUDIK** [comment]
siap patungan pak...jika ada desa yang siap berdonasi untuk fitur tersebut

**Comment by eddieridwan** [comment]
@WAHYUDIK mudah2an ada desa lain yg bersedia patungan. Untuk mengerjakan permohonan surat melalui Layanan Mandiri perlu dibuatkan alur permohonan dan pencetakan surat yg RINCI dan yang DISEPAKATI. Jadi mohon ada yg bersedia membuat rinciannya untuk disepakati.

**Comment by fusionid** [comment]
@eddieridwan mohon direview pull request #2275

**Comment by eddieridwan** [comment]
Teman2. Mari kita gunakan issue ini sebagai tempat untuk menyusun spesifikasi rinci alur, aturan, form dan laporan yg diperlukan. Saya akan tandai issue terkait sebagai duplikat dan mengarahkan agar digabung ke issue yg ini.

**Comment by fusionid** [comment]
Apakah prefixnya bisa diganti lebih global supaya teman2 di daerah lain juga merasa issuenya berkaitan dengan mereka?

**Comment by eddieridwan** [comment]
@fusionid tujuan prefix itu untuk menandakan issue yg akan diterapkan sebagai kerjasama dengan Diskominfo Kab 50 Kota. Kita sedang berusaha supaya Diskominfo Kab 50 Kota pindah dari versi ubahan mereka kembali menggunakan rilis resmi OpenSID. Issue yg diberi prefix [kab50kota] adalah untuk fitur yg mereka sudah terapkan dan yang perlu diterapkan di rilis OpenSID sebelum mereka pindah.

**Comment by eddieridwan** [comment]
Alur proses permohonan surat melalui Layanan Mandiri ada di http://bit.ly/2QK17Gj

**Comment by eddieridwan** [comment]
Sudah dicommit sebagai fitur premium
