### ISSUE TITLE
[Bug] Kesalahan Menampilkan Kodepos pada Lampiran

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#2236]
### Bagaimana alurnya sampai muncul masalah?
Saat cetak surat Permohonan Perubahan Kartu Keluarga, pad Lampiran lembar ke 2 terdapat kolom kodepos yang isinya bukan seharusnya. 
![IMG_20190823_074657](https://user-images.githubusercontent.com/46939846/63559272-d878fb00-c57a-11e9-9bec-22a2a29ea084.jpg)

### Seperti apa yang diharapkan?
Menampilkan kodepos seharusnya sesuai yang ada di pengaturan. 

### Apa yang terjadi?
Kolom kodepos di lembar 2 pada lampiran saat ini terisi angka Kode Desa. 

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR #2237
