### ISSUE TITLE
Jumlah Pengunjung di menu statisti pengunjung perlu di sempurnakan

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#2239]
### Bagaimana alurnya sampai muncul masalah?
Ketika jumlah pengunjung sudah lebih seratus ribu pengunjung contoh : 0000101700 maka tampilan jumlah pengunjung kebawah sedangkan masih 
![statistik pengunjung](https://user-images.githubusercontent.com/25834335/63636126-c9d73480-c69d-11e9-9667-d75e7c6b956c.png)

### Seperti apa yang diharapkan?
apabila jumlah pengunjung mencapai ratusan ribu maka angka 0000 sebanyak 4 digit secara ototmatis berkurang 
![hhstatistik pengunjung](https://user-images.githubusercontent.com/25834335/63636183-977a0700-c69e-11e9-9e69-44b2f84dc5a5.jpg)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3034
