### ISSUE TITLE
[Template Surat] Surat Pernyataan Haji Suami Istri tidak menampilkan nama suami

### ISSUE THREAD

**Issue by afri18** [OpenSID/OpenSID#224]
saya menambahkan surat sejenis surat persetujuan mempelai, sayangnya nama suami tidak muncul saat diklik, surat ini hampir setiap musim umroh dipergunakan, mohon bantuan
![image](https://cloud.githubusercontent.com/assets/6611881/21079767/86f2e28c-bfce-11e6-998f-de175319b6ec.png)

**Comment by eddieridwan** [comment]
@afri18 silakan lampirkan script form/print/rtf untuk surat ini, agar bisa diperiksa.

**Comment by afri18** [comment]
sya nggak bisa upload zip/file di sini, nggak tau kenapa

**Comment by eddieridwan** [comment]
Mungkin coba gunakan 7-zip http://www.7-zip.org/download.html.

**Comment by eddieridwan** [comment]
[surat_pernyataan_haji_suami_istri.zip](https://github.com/eddieridwan/OpenSID/files/746008/surat_pernyataan_haji_suami_istri.zip)

**Comment by eddieridwan** [comment]
@afri18 , yang anda kirim hanya berisi template surat export doc. Silakan juga kirimkan script untuk form surat_pernyataan_haji_suami_istri.php yang bermasalah, seperti yang anda diperlihatkan pada tampilan layar di atas.

**Comment by afri18** [comment]
tetep nggak bisa zip nya

**Comment by eddieridwan** [comment]
File php dan rtf:
[surat_pernyataan_suami_istri.zip](https://github.com/eddieridwan/OpenSID/files/752595/surat_pernyataan_suami_istri.zip)

**Comment by MUHAMMADRANGSEL** [comment]
Lebih baik begini modelnya tggl masukkan nama suami nanti untuk nama istri secara otomatis.ngambil di database

**Comment by afri18** [comment]
bagus tuh kalau bisa begitu

**Comment by mizwaruddin** [comment]
Apakah masih bermasalah?
