### ISSUE TITLE
Database Error

### ISSUE THREAD

**Issue by ridwanhadipranata** [OpenSID/OpenSID#2240]
### Bagaimana alurnya sampai muncul masalah?
Import awal
500
Sebuah Kesalahan Basis Data Telah Terjadi
Error Number: 1054

Unknown column 'b.slug' in 'field list'

SELECT a.*, b.*, YEAR(b.tgl_upload) AS thn, MONTH(b.tgl_upload) AS bln, DAY(b.tgl_upload) AS hri, b.slug as slug FROM komentar a INNER JOIN artikel b ON a.id_artikel = b.id WHERE a.enabled = 1 AND a.id_artikel <> 775 ORDER BY a.tgl_upload DESC LIMIT 10

Filename: C:/xampp/htdocs/OpenSID-master/system/database/DB_driver.php

Line Number: 691

Harap laporkan masalah ini, agar kami dapat mencarikan solusinya. Untuk sementara Anda dapat kembali ke halaman awal.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by kusmantopratama** [comment]
Lakukan migrasi database di menu database @ridwanhadipranata

**Comment by kusmantopratama** [comment]
Masuk ke siteman nya disana ada menu database dan lakukan migrasi

**Comment by eddieridwan** [comment]
@ridwanhadipranata penggunaan OpenSID mohon ditanyakan di https://www.facebook.com/groups/OpenSID/.

Sebelum membuat issue, pastikan bukan karena anda belum membaca panduan. Issue dibatasi pada masalah yg sdh dipastikan adalah error atau permintaan yg perlu perbaikan. 

Issue ini akan kami tutup. Silakan buka lagi kalau masih ada masalah dengan melampirkan penjelasan tambahan. Terima kasih.
