### ISSUE TITLE
Import Rumah Tangga tidak tersimpan jika Nomor RTMnya lebih dari 11 digit

### ISSUE THREAD

**Issue by WAHYUDIK** [OpenSID/OpenSID#2241]
### Bagaimana alurnya sampai muncul masalah?
Ketika proses import data rumah tangga masih lancar dan tidak ada keterangan gagal, setelah klik lanjut barulah muncul keterangan (data gagal tersimpan), seperti gambar dibawah:
![Untitled1](https://user-images.githubusercontent.com/31026980/63644002-34bd5580-c708-11e9-8829-0a93b7e012f9.png)
![Untitled3](https://user-images.githubusercontent.com/31026980/63644003-3dae2700-c708-11e9-9be1-bb6c7522b9a5.png)

sehingga di rumah tangga tidak ada isinya.

### Seperti apa yang diharapkan?
data bisa disimpan meskipun Nomor Rumah Tangganya lebih dari 11 digit

### Apa yang terjadi?
sampai saat ini masih belum bisa menyimpan hasil import rumah tangga yang nomornya lebih dari 11 digit

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19.08 Pasca
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Solusi untuk issue ini minimal memerlukan perubahan kolom berikut dari 11 digit menjadi varchar:

- `tweb_rtm.id`
- `tweb_penduduk.id_rtm`
- kolom2 `id_subjek` di tabel2 analisis
- kolom peserta di tabel2 program bantuan
- dan di tempat lainnya di mana rumah tangga ikut serta.

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
