### ISSUE TITLE
Error 500 : Filename: controllers/Main.php  Line Number: 7

### ISSUE THREAD

**Issue by kamalmstp** [OpenSID/OpenSID#2247]
### Bagaimana alurnya sampai muncul masalah?
Ketika saya menginstal di localhost berjalan dengan lancar, ketika hosting ada muncul error database, padahal databasenya sudah disesuaikan dengan database hosting, file errornya mengarah ke controller, kan biasanya ketika error salah tulis dbname, dbuser, atau dbpass pasti arah file nya ke DB_driver.php

### Seperti apa yang diharapkan?
Bisa berjalan di hosting

### Apa yang terjadi?
Error 500 Ada kesalahan dalam pemasangan OpenSID 

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.0
| Versi PHP        | 7.1
| System operasi   | Windows 10

![Screenshot_1](https://user-images.githubusercontent.com/32252971/63674174-894ff600-c818-11e9-8b19-4aaf36bf8ec4.jpg)

**Comment by eddieridwan** [comment]
Kalau betul masih menggunakan v2.0, update dulu ke versi terbaru. 
Untuk error 500 selalu periksa file di folder `logs` untuk menampilkan penjelasan errornya.

Harap masalah penggunaan/install ditanyakan dulu di https://www.facebook.com/groups/OpenSID/. Issue digunakan untuk hal2 yg sudah terbukti perlu perbaikan script. 

Ok, kami akan tutup issue ini. Silakan buka lagi kalau sudah ada konfirmasi error yg perlu diperbaiki.

**Comment by DesaTonjong** [comment]
Cara mengatasi Error 500 : Filename: controllers/Main.php Line Number: 47...???
