### ISSUE TITLE
modul keuangan tidak ada

### ISSUE THREAD

**Issue by ridwanhadipranata** [OpenSID/OpenSID#2251]
### Bagaimana alurnya sampai muncul masalah?
modul keuangan tidak ada

### Seperti apa yang diharapkan?
Modul keuangan muncul

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19.08
| Versi PHP        | 7.3.8
| System operasi   | XAMPP, Windows

**Comment by dikisiswanto** [comment]
Modul keuangan memang belum masuk rilis, masih dalam tahap pengembangan dan dapat diujicoba di situs http://beta.opensid.my.id/index.php/first

**Comment by eddieridwan** [comment]
Issue ini kami tutup, karena:
1. issue dimaksudkan untuk usulan/permintaan pengembangan sesuatu yg spesifik, dengan spesifikasi aturan, tampilan, data yg jelas; bukan untuk sesuatu yg umum atau besar atau yang banyak interpretasinya
2. modul transparansi keuangan sedang dibuat, sehingga issue yg dapat diterima adalah terkait perbaikan pada pekerjaan yg sudah dibuat (lihat FB untuk info lebih lanjut).

@ridwanhadipranata sebelum anda membuat issue, harap baca dulu secara seksama panduannya di https://github.com/OpenSID/OpenSID/wiki/Pengelolaan-Masalah-dan-Permintaan-Perbaikan-SID.
