### ISSUE TITLE
Penerapan SLUG sedikit mengganggu

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#2253]
### Bagaimana alurnya sampai muncul masalah?
Saat buat artikel baru dan sudah dibagikan oleh banyak orang baik melalui Facebook, Telegram maupun Whatsapp, semua baik-baik saja dan menarik perhatian karena sudah menerapkan slug pada tombol shared.

Namun itu akan menjadi kendala ketika judul artikel (misal) ada kesalahan ketik sehingga perlu direvisi. Dampaknya link yang sudah banyak dibagikan sebelumnya akan menampilkan error 404.

### Seperti apa yang diharapkan?
Harapannya supaya judul artikel tidak berpengaruh pada slug yang sudah ada. Mungkin dengan membedakan antara kalimat Judul dengan kalimat SLUG yang akan diterapkan.

### Apa yang terjadi?
Supaya tidak khawatir akan terjadinya error 404 ketika Judul artikel di rename. misal judul slug dibuat pada kolom tersendiri. (walau slug ada kesalahan kalimat, tidak terpengaruh pada judul artikel).

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by adlersentinel** [comment]
slug dibuat berdasarkan judul, ketika judul diganti slug tetap ikut terganti, karna slug duplikasi dari judul, masalah id mungkin di demo belum di update, sebab dari scriptnya artikel dapat ditampilkan berdasarkan id dan slug

**Comment by ariandii** [comment]
sudah saya jelaskan panjang lebar di atas. tidak perlu dijelaskan ulang.

**Comment by adlersentinel** [comment]
> sudah saya jelaskan panjang lebar di atas. tidak perlu dijelaskan ulang.

saya menjelaskan dari script yg sudah dibuat, bukan dari yg bapak harapkan, karna tidak akan terjadi error 404 karna artikel dibaca berdasarkan id atau slug walaupun judul artikel di update

**Comment by ariandii** [comment]
silakan dicoba.

**Comment by adlersentinel** [comment]
> silakan dicoba.

saya sudah coba berulang2 karna saya yg buat. mungkin pengaruh thema yg bapak pakai,

**Comment by ariandii** [comment]
Begini saja, buka web berikut. 

http://demo.opensid.my.id/index.php/first/artikel/2016/8/26/sejarah-desa

kemudian silakan klik bagikan.

apakah URL nya pakai SLUG atau pakai ID?

1. Jika pakai ID, semua kan lancar. gak ada beda. 

2. Jika hasil share diubah ke SLUG dan juduo diedit. apa yanh terjadi? 

Silakan dipraktekkan Share nya. dan perhatikan URL nya.

**Comment by adlersentinel** [comment]
> Begini saja, buka web berikut.
> 
> http://demo.opensid.my.id/index.php/first/artikel/2016/8/26/sejarah-desa
> 
> kemudian silakan klik bagikan.
> 
> apakah URL nya pakai SLUG atau pakai ID?
> 
> 1. Jika pakai ID, semua kan lancar. gak ada beda.
> 2. Jika hasil share diubah ke SLUG dan juduo diedit. apa yanh terjadi?
> 
> Silakan dipraktekkan Share nya. dan perhatikan URL nya.

artikel juga bisa dibuka pakai id 
http://demo.opensid.my.id/index.php/first/artikel/99
id artikelnya 99 bisa cek di database

**Comment by adlersentinel** [comment]
saya sudah sudah bahas di groun facebook dan share artikel pakai id dan slug tidak ada error 404

**Comment by ariandii** [comment]
yang saya maksud di atas adalah ketika hasil sharenya pakai SLUG pak, pakai SLUG.

Kalau pakai ID mah gak saya permasalahkan. 

Coba deh dibaca lagi dengan seksama. 

Saya ndak ada urusan sama si pembuatnya, yang saya pertanyakan tentang hasil share jika URL nya pakai SLUG.

**Comment by ariandii** [comment]
Silakan coba klik URL yang sudah Anda bagikan di Facebook melalui komentar pada halaman berikut.

https://m.facebook.com/groups/626787397486245?view=permalink&id=1305477989617179&fs=2&focus_composer=0&ref=m_notif&notif_t=group_activity

![Screenshot_2019-08-31-23-34-48-40](https://user-images.githubusercontent.com/46939846/64066756-f9f77800-cc47-11e9-9531-3cc9cadcfc54.png)

dan sekarang sudah saya edit judulnya. 

![Screenshot_2019-08-31-23-31-52-50](https://user-images.githubusercontent.com/46939846/64066762-0d0a4800-cc48-11e9-98cb-8418c7f80a38.png)

ini hasilnya.

![Screenshot_2019-08-31-23-32-04-37](https://user-images.githubusercontent.com/46939846/64066745-d6343200-cc47-11e9-8ac0-f06d851badff.png)

Bagaimana?

**Comment by eddieridwan** [comment]
@adlersentinel @ariandii , opsi solusinya:

1. slug hanya dibuat pada waktu membuat artikel; tidak diubah pada waktu update artikel; atau
2. slug diberi prefix/suffix id artikel; pada waktu berusaha mengakses artikel menggunakan slug tidak berhasil, ambil prefix/suffix tersebut dan akses menggunakan id.
3. solusi lain?

Opsi (1) berarti slug bisa berbeda dari judul artikel. 
Opsi (2) berarti bisa saja orang membuat bookmark artikel yg sama menggunakan slug yg berbeda (slug berbeda untuk setiap judul).

Saya cenderung memilih opsi (2). Bagaimana dengan teman2?

**Comment by ariandii** [comment]
Mohon ijin pak @eddieridwan 
saya masih menunggu respon pembuatnya pak. sesuai quote di bawah ini. 

![IMG_20190901_000341](https://user-images.githubusercontent.com/46939846/64071252-335bd200-cca0-11e9-99e0-a81a9e243cf6.jpg)

**Comment by eddieridwan** [comment]
@ariandii masalah yg anda laporkan sudah diverifikasi memang terjadi. Jadi tinggal pilih opsi solusi dan terapkan.

**Comment by eddieridwan** [comment]
Bung @ariandii , saya kira berikut yg paling cocok:

- slug diberi prefix id artikel; pada waktu berusaha mengakses artikel menggunakan slug tidak berhasil, ambil prefix/suffix tersebut dan akses menggunakan id.

Jadi slug berbentuk sbb: [id]-[slug-biasa], contoh
`99-slug-yg-dibuat-dari-judul-artikel`

Coba akses menggunakan slug secara keseluruhan. Kalau tidak ketemu, coba menggunakan prefix `99` sebagai id.

**Comment by dypras666** [comment]
Saran 
bisa juga pake histori perubahan slug, 
jadi ketika visitor mengakses link  lama,
langsung redirect ke slug baru

**Comment by sup-ham** [comment]
menurut saya  URL slug harus nya dibuat sekali saja karena dicatat mesin pencari.

**Comment by fusionid** [comment]
Apa yg disampaikan @ariandii  memang pasti akan terjadi pada beberapa situs opensid, tetapi ini bukan dikarenakan SLUG.

Penyebabnya adalah nilai ID di database artikel = 0 ketika create/edit artikel padahal semestinya nilai ID harus NOT NULL, AUTO_INCREMENT dan yg paling penting diset sebagai PRIMARY KEY.

Kenapa ID menjadi 0 ? tidak ada yg salah dgn user dan script app tetapi dikarenakan proses import file .sql ke Mysql.  Ada 2 metode generate file. sql yg nanti akan diimport yaitu lewat fitur Export di phpMyAdmin dan Fitur Backup di OpenSID. Kedua fitur itu akan sama2 generate file .sql, tetapi dengan structure table yg berbeda.

**1. Fitur Export di phpMyAdmin :**

CREATE TABLE `artikel` (
  **`id` int(11) NOT NULL,**
  `gambar` varchar(200) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
   XXXXXXXXXX
  `slug` varchar(200) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

**2. Fitur Backup di Opensid :**

CREATE TABLE `artikel` (
  **`id` int(11) NOT NULL AUTO_INCREMENT,**
  `gambar` varchar(200) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
   XXXXXXXXXX
  `slug` varchar(200) DEFAULT NULL,
  **PRIMARY KEY (`id`)**
) ENGINE=InnoDB AUTO_INCREMENT=107 DEFAULT CHARSET=utf8;

phpMyAdmin -> ID = NOT NULL, tidak AUTO_INCREMENT, tidak diset sbg PRIMARY KEY
OpenSID -> ID = NOT NULL, AUTO_INCREMENT dan diset sbg PRIMARY KEY

Jadi sebaiknya restore kembali database dengan memakai file .sql yg digenerate OpenSID atau manual edit struktur ID di tabel Artikel menjadi NOT NULL, AUTO_INCREMENT, PRIMARY KEY tetapi prosesnya jadi panjang karena bukan tabel artikel saja yg harus diedit tetapi semua tabel di database juga harus diedit.

**Comment by afa28** [comment]
Pak @eddieridwan , ini juga mungkin???

**Comment by eddieridwan** [comment]
Untuk issue ini, penerapan slug artikel perlu diperbaiki supaya slug tidak diupdate secara otomatis pada saat mengubah judul artikel.

**Comment by afa28** [comment]
> Untuk issue ini, penerapan slug artikel perlu diperbaiki supaya slug tidak diupdate secara otomatis pada saat mengubah judul artikel.

mungkin pada update artikelnya, field slug tdk perlu di update jg. biarkan menggunakan slug yg lama, untuk menghindari artikel yg lama pernah dishare pakai slug masih bisa di akses.

**Comment by eddieridwan** [comment]
Sudah dicommit ke `master` melalui PR #2797
