### ISSUE TITLE
[keuangan] Grafik keuangan ada yg terlalu renggang

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#2254]
### Bagaimana alurnya sampai muncul masalah?
1. Buat artikel berisi semua jenis grafik keuangan
2. Tampilkan di web
3. Perhatikan tampilan grafik

### Seperti apa yang diharapkan?
Semua grafik tampak rapi

### Apa yang terjadi?
Ada grafik yang terlalu renggang dan tidak terlihat rapi.
![terlalu-renggang-1](https://user-images.githubusercontent.com/249563/63919786-c7e8e900-ca82-11e9-9e11-2d2b95ebb921.jpg)
![terlalu-renggang-2](https://user-images.githubusercontent.com/249563/63919797-cae3d980-ca82-11e9-81c0-b5fe644356a8.jpg)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | keuangan
| Versi PHP        | 
| System operasi   |

**Comment by ekasatriabahari** [comment]
sudah dikirim perbaikan di #2257

**Comment by eddieridwan** [comment]
Sudah dikerjakan.
