### ISSUE TITLE
@af-lazuardi , boleh, tapi perlu juga:

### ISSUE THREAD

**Issue by R4HMAT** [OpenSID/OpenSID#2256]
@af-lazuardi , boleh, tapi perlu juga:
- menambahkan ke semua form isian penduduk
- menampilkan di semua laporan rincian biodata penduduk

_Originally posted by @eddieridwan in https://github.com/OpenSID/OpenSID/issues/2201#issuecomment-522292517_

**Comment by eddieridwan** [comment]
???

**Comment by R4HMAT** [comment]
Penambahn pada Kolom Pekerjaan seakrang dengan pekerjaan dalam KK
