### ISSUE TITLE
Penambahan Fitur RPJMDes dan RKPDes

### ISSUE THREAD

**Issue by arcom6456** [OpenSID/OpenSID#2263]
Seperti apa yang diharapkan?
RPJM Desa adalah dokumen perencanaan untuk periode 6 (enam) tahun dan merupakan penjabaran dari visi dan misi Desa yang memuat arah kebijakan pembangunan desa, arah kebijakan keuangan desa, kebijakan umum, program dan empat kegiatan pembangunan Desa.
Apa yang terjadi?
Supaya Pembangunan Desa selalu terarah sesuai visi dan misi Kepala Desa selama Periode 6 (Enam) Tahun
### Informasi tambahan 
[Book1.xlsx](https://github.com/OpenSID/OpenSID/files/3563615/Book1.xlsx)
[format RKPDes.xlsx](https://github.com/OpenSID/OpenSID/files/3563618/format.RKPDes.xlsx)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by M-A-Haris** [comment]
Ini sudah ada isu terkait permintaan fitur RPJMDes dan RKPDes yang bisa disinergikan dengan fitur APBDes Opensid .
