### ISSUE TITLE
Tammbahkan Featur Surat Pernyataan Tidak Dalam Sengketa

### ISSUE THREAD

**Issue by kayangan** [OpenSID/OpenSID#2266]
1. Saya Pernah Membuat Surat Pernyataan Tidak Dalam Sengketa Di Aplikasi Opensid Di Desa Saya Copas Dari SURAT SPORADIK Namun Setelah Export surat sedikit ada tampilan yang kurang enak yaitu Tampilan Tanggal Lahir Pemohon dari warga menampilkan Tanggal Digit Kebalik Seperti 1979-12-31 Begitu juga sebaliknya Jika pemohon luar Desa Menampilkan tanggal lahir 31-12-1979 saya tidak bisa oprek karena ilmu koding terbatas bisa tidak tanggal lahir itu dinormalkan Seperti Berikut : 31 Desember 1979 ..Terima Kasih.
2. Berikut Saya Lampirkan Surat Pernyataan Tidak Dalam Sengketa Yang pernah Saya Buat
https://drive.google.com/file/d/1MwW8rw6e7xTxntV7-LGTtBEl5CJOT29T/view?usp=sharing

[surat_pernyataan_tanah_tidak_dalam_sengketa_5208033112790122_2019-09-03_4010.pdf](https://github.com/OpenSID/OpenSID/files/3567912/surat_pernyataan_tanah_tidak_dalam_sengketa_5208033112790122_2019-09-03_4010.pdf)

**Comment by kayangan** [comment]
https://drive.google.com/file/d/0B8uuZYCAEDFnSHl6UjU5cXZYbERNVldKaUFGWVp5dEdHTWF3/view?usp=sharing

**Comment by roaddee** [comment]
![image](https://user-images.githubusercontent.com/45786885/64146045-8de26300-ce45-11e9-82fb-987c47db82b9.png)

**Comment by junandia** [comment]
itu di drive kok surat perjalanan dinas ya pak?
dan FYI untuk ubah format date bisa pakai fungsi date(d-m-Y, strtorime('2019-09-18'));

#CMIIW

**Comment by kayangan** [comment]
Sudah saya Perbaiki Linknya Silahkan Di Cek Atau di Pull Request
