### ISSUE TITLE
Laporan Bulanan di Menu Statistik tidak sesuai dengan permendagri 47 tahun 2016 dan Tidak Bisa Menampilkan Rincian BNBA

### ISSUE THREAD

**Issue by WAHYUDIK** [OpenSID/OpenSID#2272]
### Bagaimana alurnya sampai muncul masalah?
ketika ingin melihat laporan bulan yang lengkap dengan nama dan alamat tidak bisa. hanya menampilkan jumlah saja. dan  juga tidak sesuai dengan dengan format pada Permendagri 47 tahun 2016,, buku b.2 dan buku b.3,,
![image](https://user-images.githubusercontent.com/31026980/64321561-f7e83d00-cfea-11e9-8c5d-7b6b7e10a057.png)

### Seperti apa yang diharapkan?
laporan bulanan sesuai dengan peraturan yang ada. dan bisa menampilkan BNBAnya seperti laporan statistik yang lain. jika klik jumlah bisa langsung mengarah ke data penduduknya.

### Apa yang terjadi?
jumlah penduduk yang di laporan bulanan tidak bisa menampilkan BNBA

### Informasi tambahan 

[10010000204_permen_no.47_th_2016.docx](https://github.com/OpenSID/OpenSID/files/3578064/10010000204_permen_no.47_th_2016.docx)
[Permen No.47 TH 2016_Lampiran.docx](https://github.com/OpenSID/OpenSID/files/3578065/Permen.No.47.TH.2016_Lampiran.docx)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Laporan bulanan yg baru adalah sbb, yang diambil dari lampiran permen di atas.

Terlihat di lampiran tersebut, tidak diberikan pengertian cara menghitung masing2 data di laporan tersebut. 

Sebagai contoh, apakah laporan jumlah yg lahir setiap bulan dihitung berdasarkan:

1. tgl di-entri ke OpenSID , atau
2. tgl lahir masing2 penduduk yg ditambahkan?
Kalau jawabannya (1), apakah bermasalah kalau pada waktu di-entri, penduduk baru tersebut tgl lahirnya dua atau tiga bulan sebelumnya.

![Permen No 47 TH 2016_Lampiran](https://user-images.githubusercontent.com/249563/86203074-5c424180-bba7-11ea-9938-c534bd040d68.jpg)


[Permen.No.47.TH.2016_Lampiran.pdf](https://github.com/OpenSID/OpenSID/files/4855666/Permen.No.47.TH.2016_Lampiran.pdf)

**Comment by balongbesuk** [comment]
https://format-lengkap-administrasi-desa.blogspot.com/2016/09/format-baru-administrasi-desa.html

tatacara pengisian

**Comment by Gunturwijay** [comment]
Sebaiknya untuk menambahkan penduduk  dibuatkan katagori:
1. Lahir
2. Pindah Masuk
Agar dapat membedakan angka pertambahan penduduk, dan agar penduduk yg baru lahir dan penduduk yg UD lama lahir dapat dimasukkan dalam angka katagori lahir.

**Comment by eddieridwan** [comment]
Issue ini sepertinya sudah kadaluarsa, karena Buku Rekapitulasi Jumlah Penduduk sedang dikembangkan di rilis Premium, @af-lazuardi .

Permintaan @Gunturwijay sudah diterapkan di menu Penduduk/Keluarga di rilis Premium.

**Comment by eddieridwan** [comment]
Yg belum diterapkan adalah bisa klik tautan di masing2 jumlah di tabel untuk menampilkan log terkait.

**Comment by eddieridwan** [comment]
Sdh tersedia di rilis Premium. Kalau yg kurang silakan dibuka issue baru.
