### ISSUE TITLE
Nominal di widget statistik keuangan desa kurang jelas

### ISSUE THREAD

**Issue by WAHYUDIK** [OpenSID/OpenSID#2278]
### Bagaimana alurnya sampai muncul masalah?
Ketika melihat widget statistik keuangan desa kurang jelas angkanya, itu disebabkan karena ada efek warna putih diteksnya. dan ketika kursor diarahkan ke nominal popupnya tidak jelas/terpotong
![image](https://user-images.githubusercontent.com/31026980/64483055-adeb9b00-d226-11e9-9f01-f2c3f64de495.png)
dan untuk realisasi belanja desanya muncul 2 kali dengan jumlah yang berbeda, salah satu contohnya
bidang penyelenggaraan pemerintah desa di atas menampilkan nominal sejumlah 1.104.404.253 dan dibawah juga menampilkan bidang penyelenggaraan pemerintah desa dengan jumlah yang berbeda, yakni 330.173.468

### Seperti apa yang diharapkan?
diberi 1 warna saja, misalkan hitam. sehingga nominalnya lebih jelas

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sepertinya ini sudah dikerjakan. Silakan buka lagi kalau masih ada yg perlu diperbaiki
