### ISSUE TITLE
user "operator" diberi hak akses pecah KK

### ISSUE THREAD

**Issue by makhbub** [OpenSID/OpenSID#2281]
### Bagaimana alurnya sampai muncul masalah?
user operator tidak memiliki akses untuk pecah KK, padahal itu diperlukan untuk membuat KK baru dari penduduk yang sudah terdaftar. sedangkan dalam peraturan, operator diperbolehkan edit data dasar penduduk, pecah KK bagian dari edit data dasar penduduk

### Seperti apa yang diharapkan?
operator diberi hak akses ke menu Pecah KK (logo gunting) yang merupakan bagian dari edit data dasar desa

### Apa yang terjadi?
jika operator tidak memiliki akses pecah KK, maka pada saat pelayanan penduduk membuat KK baru dari penduduk yang sudah ada, harus menghubungi dulu administrator untuk pecah KK, **saya rasa itu kurang efektif**

### Informasi tambahan 
sebagai informasi tambahan saya sertakan aturan user Opensid
![IMG_20190909_151620](https://user-images.githubusercontent.com/38773660/64584926-ec1cc200-d3c0-11e9-8541-36fa7c018bae.jpg)
![IMG_20190910_114550](https://user-images.githubusercontent.com/38773660/64584927-ecb55880-d3c0-11e9-94aa-8d4ec58eb9ae.jpg)
![IMG_20190910_114456](https://user-images.githubusercontent.com/38773660/64584929-ecb55880-d3c0-11e9-9466-5ed76e71d7b9.jpg)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
