### ISSUE TITLE
perlu dimasukan dengan fitur komposisi keanggotaan BPD pada menu dashbord

### ISSUE THREAD

**Issue by zurffin** [OpenSID/OpenSID#2286]
### Bagaimana alurnya sampai muncul masalah?
sebagai tambahan fitur untuk keanggotaan BPD

### Seperti apa yang diharapkan?
agar supaya administrasi kelembagaan BPD dapat dilakukan secara baik

### Apa yang terjadi?
memudahkn pemerintah desa dalam mengelola program bersama BPD

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by andifahruddinakas** [comment]
Bisa gunakan modul kelompok atau lembaga.
