### ISSUE TITLE
Error saat edit biodata di hosting

### ISSUE THREAD

**Issue by myshandry** [OpenSID/OpenSID#2287]
### Bagaimana alurnya sampai muncul masalah?
pada menu penduduk saat 1. klik lihat detail biodata pendduk 
                                            2. klik edit biodata penduduk

kl di localhost lancar tap kl di hosting eror

### Apa yang terjadi?
kluar error seperti :

 Sebuah Kesalahan Basis Data Telah Terjadi
Error Number: 1054
Unknown column 'u.updated_by' in 'on clause'

SELECT u.sex as id_sex, u.*, a.dusun, a.rw, a.rt, t.nama AS status, o.nama AS pendidikan_sedang, m.nama as golongan_darah, h.nama as hubungan, b.nama AS pendidikan_kk, d.no_kk AS no_kk, d.alamat, u.id_cluster as id_cluster, ux.nama as nama_pengubah, ucreate.nama as nama_pendaftar, (CASE when u.status_kawin <> 2 then k.nama else case when u.akta_perkawinan = '' then 'KAWIN TIDAK TERCATAT' else 'KAWIN TERCATAT' end end) as kawin, (SELECT DATE_FORMAT(FROM_DAYS(TO_DAYS(NOW())-TO_DAYS(`tanggallahir`)), '%Y')+0 FROM tweb_penduduk WHERE id = u.id) AS umur, x.nama AS sex, w.nama AS warganegara, p.nama AS pekerjaan, g.nama AS agama, c.nama as cacat, kb.nama as cara_kb, sm.nama as sakit_menahun, sd.nama as status_dasar, u.status_dasar as status_dasar_id, (select tweb_penduduk.nama AS nama from tweb_penduduk where (tweb_penduduk.id = d.nik_kepala)) AS kepala_kk, log.no_kk as log_no_kk FROM tweb_penduduk u LEFT JOIN tweb_keluarga d ON u.id_kk = d.id LEFT JOIN tweb_wil_clusterdesa a ON u.id_cluster = a.id LEFT JOIN tweb_penduduk_pendidikan o ON u.pendidikan_sedang_id = o.id LEFT JOIN tweb_penduduk_pendidikan_kk b ON u.pendidikan_kk_id = b.id LEFT JOIN tweb_penduduk_warganegara w ON u.warganegara_id = w.id LEFT JOIN tweb_penduduk_status t ON u.status = t.id LEFT JOIN tweb_penduduk_pekerjaan p ON u.pekerjaan_id = p.id LEFT JOIN tweb_penduduk_kawin k ON u.status_kawin = k.id LEFT JOIN tweb_penduduk_sex x ON u.sex = x.id LEFT JOIN tweb_penduduk_agama g ON u.agama_id = g.id LEFT JOIN tweb_golongan_darah m ON u.golongan_darah_id = m.id LEFT JOIN tweb_penduduk_hubungan h on u.kk_level = h.id LEFT JOIN tweb_cacat c ON u.cacat_id = c.id LEFT JOIN tweb_sakit_menahun sm ON u.sakit_menahun_id = sm.id LEFT JOIN tweb_cara_kb kb ON u.cara_kb_id = kb.id LEFT JOIN tweb_status_dasar sd ON u.status_dasar = sd.id LEFT JOIN log_penduduk log ON u.id = log.id_pend LEFT JOIN user ux ON u.updated_by = ux.id LEFT JOIN user ucreate ON u.created_by = ucreate.id WHERE u.id='18'

Filename: models/Penduduk_model.php

Line Number: 939

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19.06
| Versi PHP        | PHP Version 7.1.32
| System operasi   | hosting

**Comment by myshandry** [comment]
> ### Bagaimana alurnya sampai muncul masalah?
> pada menu penduduk saat 1. klik lihat detail biodata pendduk
> 2. klik edit biodata penduduk
> 
> ### Seperti apa yang diharapkan?
> mesti na tidak tidak terjadi error
> 
> ### Apa yang terjadi?
> kluar error seperti :
> 
> Sebuah Kesalahan Basis Data Telah Terjadi
> Error Number: 1054
> Unknown column 'u.updated_by' in 'on clause'
> SELECT u.sex as id_sex, u.*, a.dusun, a.rw, a.rt, t.nama AS status, o.nama AS pendidikan_sedang, m.nama as golongan_darah, h.nama as hubungan, b.nama AS pendidikan_kk, d.no_kk AS no_kk, d.alamat, u.id_cluster as id_cluster, ux.nama as nama_pengubah, ucreate.nama as nama_pendaftar, (CASE when u.status_kawin <> 2 then k.nama else case when u.akta_perkawinan = '' then 'KAWIN TIDAK TERCATAT' else 'KAWIN TERCATAT' end end) as kawin, (SELECT DATE_FORMAT(FROM_DAYS(TO_DAYS(NOW())-TO_DAYS(`tanggallahir`)), '%Y')+0 FROM tweb_penduduk WHERE id = u.id) AS umur, x.nama AS sex, w.nama AS warganegara, p.nama AS pekerjaan, g.nama AS agama, c.nama as cacat, kb.nama as cara_kb, sm.nama as sakit_menahun, sd.nama as status_dasar, u.status_dasar as status_dasar_id, (select tweb_penduduk.nama AS nama from tweb_penduduk where (tweb_penduduk.id = d.nik_kepala)) AS kepala_kk, log.no_kk as log_no_kk FROM tweb_penduduk u LEFT JOIN tweb_keluarga d ON u.id_kk = d.id LEFT JOIN tweb_wil_clusterdesa a ON u.id_cluster = a.id LEFT JOIN tweb_penduduk_pendidikan o ON u.pendidikan_sedang_id = o.id LEFT JOIN tweb_penduduk_pendidikan_kk b ON u.pendidikan_kk_id = b.id LEFT JOIN tweb_penduduk_warganegara w ON u.warganegara_id = w.id LEFT JOIN tweb_penduduk_status t ON u.status = t.id LEFT JOIN tweb_penduduk_pekerjaan p ON u.pekerjaan_id = p.id LEFT JOIN tweb_penduduk_kawin k ON u.status_kawin = k.id LEFT JOIN tweb_penduduk_sex x ON u.sex = x.id LEFT JOIN tweb_penduduk_agama g ON u.agama_id = g.id LEFT JOIN tweb_golongan_darah m ON u.golongan_darah_id = m.id LEFT JOIN tweb_penduduk_hubungan h on u.kk_level = h.id LEFT JOIN tweb_cacat c ON u.cacat_id = c.id LEFT JOIN tweb_sakit_menahun sm ON u.sakit_menahun_id = sm.id LEFT JOIN tweb_cara_kb kb ON u.cara_kb_id = kb.id LEFT JOIN tweb_status_dasar sd ON u.status_dasar = sd.id LEFT JOIN log_penduduk log ON u.id = log.id_pend LEFT JOIN user ux ON u.updated_by = ux.id LEFT JOIN user ucreate ON u.created_by = ucreate.id WHERE u.id='18'
> 
> Filename: models/Penduduk_model.php
> 
> Line Number: 939
> 
> Harap laporkan masalah ini, agar kami dapat mencarikan solusinya. Untuk sementara Anda dapat kembali ke halaman awal.
> 
> kl di localhost lancar tap kl di hosting eror
> Unknown column 'u.updated_by' in 'on clause'
> 
> ### Informasi tambahan
> Tanya	Jawab
> Versi OpenSID	19.06
> Versi PHP	PHP Version 7.1.32
> System operasi	hosting

**Comment by ai-skematik** [comment]
Sudah di coba di http://demo.opensid.my.id?

**Comment by myshandry** [comment]
maxudnad coba gmana saya sudah masuk ke demo di atas lancar

**Comment by myshandry** [comment]
saya cb restore pake db saya nama db na apa biar sinkronin d konfig na

**Comment by eddieridwan** [comment]
Error ini disebabkan versi MySQL tidak memenuhi syarat seperti dijelaskan di Panduan-Install-OpenSID. Untuk mengatasi ini, upgrade MySQL supaya minimal versi 5.6.5 (2012-04-10, Milestone 8). Minta hosting untuk mengupdate versi MySQL.

Varian dari masalah ini dijelaskan di https://github.com/OpenSID/OpenSID/wiki/Tanya-Jawab-Install-dan-Update

**Comment by myshandry** [comment]
sudah saya minta ke hosting na katana ga bisa krn share hosting versi saat ini pada hosting 5.5.64

**Comment by eddieridwan** [comment]
@myshandry sebaiknya anda pindah hosting saja. Hosting yang disediakan OpenDesa (https://www.opendesa.id/mengonlinekan-opensid/) memenuhi syarat dan dapat digunakan desa anda.
