### ISSUE TITLE
Menambahkan fitur tabel pengisian APBDes

### ISSUE THREAD

**Issue by Agus-Heriyanto** [OpenSID/OpenSID#229]
Memasukkan kebutuhan yang sekiranya penting dan diharapkan oleh masyarakat untuk transparansi informasi dari desa yang bisa ditampilkan dalam portal SID namun tidak dalam bentuk dokumen akan tetapi bisa dalam bentuk aplikasi yang mungkin bisa dibuat lewat excel dan bisa terintegrasi kedalam sid.Ini juga bisa membantu desa dalam menuyusun APBDesnya yang langsung menyatu dengan SID. Saya belum bisa mengirimkan struktur APBDes karen lagi koordinasi dengan BPMD untuk bisa mendapatkan struktur APBDes dan teknik pengisiannya.Apakah bisa juga untuk RPJMDes atau RKPDes?

**Comment by mizwaruddin** [comment]
@afa28 sdh ada impor siskeudes
