### ISSUE TITLE
Sediakan halaman pada web untuk menampilkan data regulasi desa yang di input pada modul sekretariat

### ISSUE THREAD

**Issue by dobbleone** [OpenSID/OpenSID#2290]
### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

Mengingat banyaknya produk hukum yang di keluarkan oleh desa seperti perdes, perades, perkades, perakades, dan sk kades sangat dibutuhkan untuk penampahan fitur halaman kusus yang dapat menampilkan data produk hukum yang sudah di input dalam modul sekretariat.
A. Penambahan fitur yang dimaksud:
1. Dibuatkan halaman pada web desa opensid yang berisikan judul, nomor, tahun beserta link yang menuju dokumen tersebut agar mudah di lihat/di uduh.
2. Data yang ditampilkan dapat difilter menurut kategori dan tahun.
B. Latar belakang pengajuan issue
1. Efesiensi pemerintah desa dalam memberikan informasi terkait produk hukum di desa.
2. Tersedianya informasi produk hukum desa yang mudah diperoleh warga.
3. Optimalkan modul Sekretariat untuk keterbukaan publik.

Gambaran Fitur yg diharapkan :

![Screenshot_2019-09-13-06-54-10](https://user-images.githubusercontent.com/34769878/64909532-6db97a80-d748-11e9-8d23-f3158b9ca7b0.png)

**Comment by eddieridwan** [comment]
Untuk halaman produk hukum desa ini diperlukan fitur cari berdasarkan nama. Kalau bisa juga lebih spesifik sesuai dengan data di kolom `attr` (lihat tabel `dokumen`). Contoh yg diinginkan lihat di https://jdih.surabaya.go.id/
![Home___JDIH_Kota_Surabaya](https://user-images.githubusercontent.com/249563/65003300-85505900-d92a-11e9-96c8-e73a76b9dd20.jpg)

Dan juga bisa difilter berdasarkan kategori. Lihat tabel `dokumen`.

**Comment by ekasatriabahari** [comment]
untuk fitur tersebut pada pemerintahan pada umum nya di sebut JDIH seperti yg dicontohkan di atas
mungkin lebih baik di tata pada halaman admin OpenSID untuk penambahan field2 seperti gambar di atas agar mempermudah filtering dokumen yg dicari
bagaimana?
untuk Peraturan & SK dropdown saja

**Comment by dobbleone** [comment]
-pada defould hanya tampilkan peraturan desa terbaru lengkap dengan judul/tentang, nomor, dan tahun.
-jumlah defaul dari masing-masing kategori peraturan dibatasi 10-15 (dapat disesuaikan)
- filter bisa hanya kategori dan tahun terbit 
- tampilkan hasil filter dengan Ajax dan jquery tanpa Reload halaman

**Comment by ekasatriabahari** [comment]
bisa, berarti ada penyesuaian untuk halaman admin OpenSID nanti
kalau boleh tau klasifikasi surat2nya bisa diperjelas?

**Comment by ekasatriabahari** [comment]
Apakah kategori dokumen nya seperti ini??

![image](https://user-images.githubusercontent.com/39932698/65309120-0c692f80-dbbe-11e9-9a23-3320ece71471.png)

**Comment by dobbleone** [comment]
Sebaiknya nomor hanya berisi nomor peraturan. Uraian singkat di ubah dengan
tgl ditetapkan

Pada tanggal 20 Sep 2019 4:48 PM, "Eka Satria Bahari" <
notifications@github.com> menulis:

**Comment by dobbleone** [comment]
Apakah sudah disediakan halaman yang menampilkan hasil input pada modul
tersebut pada web desa

Pada tanggal 20 Sep 2019 11:30 PM, "MD WONE" <mdwone18@gmail.com> menulis:

**Comment by ekasatriabahari** [comment]
belum, secepatnya akan diselesaikan

**Comment by ekasatriabahari** [comment]
![image](https://user-images.githubusercontent.com/39932698/65406779-25b6e980-de13-11e9-8d92-45dd5d976aca.png)
Kurang Lebih seperti itu ya??

**Comment by R4HMAT** [comment]
kapan di comite ke prarilis model seperti ini
https://github.com/OpenSID/OpenSID/issues/2290#issuecomment-533981249

**Comment by eddieridwan** [comment]
Bung @R4HMAT , karena ini adalah issue pesanan, desa anda juga dihimbau untuk ikut kontribusi pada biaya pengerjaannya -- supaya kebutuhan dananya terpenuhi. Silakan PM kalau bisa.

**Comment by R4HMAT** [comment]
Shipp.

Pada tanggal Sel, 1 Okt 2019 11:06, Eddie Ridwan <notifications@github.com>
menulis:

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
