### ISSUE TITLE
Kustomisasi Tema Default

### ISSUE THREAD

**Issue by muhamaddifa** [OpenSID/OpenSID#2293]
### Seperti apa yang diharapkan?
Perlu adanya helper tema seperti popoji cms

https://www.popojicms.org/pages/helper-tema

Helper Tema Opensid 

agar dapat mempermudah custom tema  bagi web developer pemula untu belajar brekerasi atau bagi pemula pun dapat berkerasi 

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Fitur kustomisasi masing2 tema nanti dapat diakses melalui halaman pengaturan tema. Lihat issue https://github.com/OpenSID/OpenSID/issues/2486.

**Comment by afa28** [comment]
Duplicate https://github.com/OpenSID/OpenSID/issues/2486
