### ISSUE TITLE
[Template Surat] Perlu tambahkan surat keterangan pengalihan hak atas tanah, istilahnya surat jual beli (kompensasi)

### ISSUE THREAD

**Issue by zurffin** [OpenSID/OpenSID#2294]
### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
@zurffin untuk permintaan surat seperti ini, perlu dilampirkan contoh suratnya; dan juga ketentuan pengisian data yang diperlukan. Mohon ingat, programmer BUKAN perangkat desa dan umumnya sama sekali tidak mengerti administrasi desa.
