### ISSUE TITLE
perlu ditambahkn fitur PBB/pajak di web admin dn opensid

### ISSUE THREAD

**Issue by zurffin** [OpenSID/OpenSID#2295]
### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
@zurffin sebelum menambahkan permintaan, harap selalu periksa dulu apakah sudah ada yg meminta sebelumnya. Dalam hal ini, permintaan PBB sudah ada di beberapa issue lainnya, termasuk  di https://github.com/OpenSID/OpenSID/issues/486 dan https://github.com/OpenSID/OpenSID/issues/806.

Selain itu, selalu ingat, permintaan tidak akan dikerjakan kalau tidak ada spesifikasi yg jelas seperti apa fitur yg diperlukan. Apa basis peraturan/hukumnya, seperti apa formnya, format laporannya seperti apa, dsbnya.

**Comment by afa28** [comment]
Duplicate #486
