### ISSUE TITLE
[Template Surat] Buat formulir pencatatan perkawinan F-2.12

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#2296]
### Bagaimana alurnya sampai muncul masalah?
1. buka Layanan Surat > Cetak Surat
2. cari Formulir Pencatatan Perkawinan F-2.12

### Seperti apa yang diharapkan?
Formulir Pencatatan Perkawinan F-2.12 tersedia

### Apa yang terjadi?
Formulir itu tidak tersedia.

### Informasi tambahan 
[F-2.12_FORMULIR_PENCATATAN_PERKAWINAN.pdf](https://github.com/OpenSID/OpenSID/files/3635859/F-2.12_FORMULIR_PENCATATAN_PERKAWINAN.pdf)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19.09
| Versi PHP        | 
| System operasi   |

**Comment by MantoAta** [comment]
Pak @eddieridwan , tolong dong surat ini. Sangat dipelukan di daerah-daereah yang mayoritas non-muslim.
[suket nikah.docx](https://github.com/OpenSID/OpenSID/files/4466059/suket.nikah.docx)
[F-212_FORMULIR_PENCATATAN_PERKAWINAN.pdf](https://github.com/OpenSID/OpenSID/files/4466060/F-212_FORMULIR_PENCATATAN_PERKAWINAN.pdf)
