### ISSUE TITLE
[Template Surat] Buat F-2.40 Formulir Pelaporan Pengesahan Anak

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#2297]
### Bagaimana alurnya sampai muncul masalah?
1. buka Layanan Surat > Cetak Surat
2. cari F-2.40 Formulir Pelaporan Pengesahan Anak

### Seperti apa yang diharapkan?
F-2.40 Formulir Pelaporan Pengesahan Anak tersedia

### Apa yang terjadi?
Formulir itu tidak tersedia.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19.09
| Versi PHP        | 
| System operasi   |

**Comment by uncu29** [comment]
[F-2.40_FORMULIR_PELAPORAN_PENGESAHAN_ANAK.pdf](https://github.com/OpenSID/OpenSID/files/3637328/F-2.40_FORMULIR_PELAPORAN_PENGESAHAN_ANAK.pdf)

**Comment by emanuel-simon** [comment]
formulir ini juga sangat penting dan sering digunakan di kabupaten saya
