### ISSUE TITLE
Untuk Sub Menu Agenda perlu dipisahkan supaya menyendiri 

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#2299]
### Bagaimana alurnya sampai muncul masalah?
Adminweb>artikel>Artikel Statis>Agenda, untuk saat ini Agenda termasuk jenis artikel

Agenda kegiatan muncul di 2 tempat, ada di berita dan ada diwidget
![6](https://user-images.githubusercontent.com/25834335/65391095-ff615300-dd19-11e9-8b51-6aec57573796.png)

### Seperti apa yang diharapkan?
Untuk **Sub Menu  Agenda** supaya dipisah seperti **sub menu Teks Berjalan**
dengan FOrm Isian
1. Judul
2. Tanggal Kegiatan 
3. Lokasi Kegiatan
4. Koordinator Kegiatan
dan untuk Agenda ini hanya muncul diwidget saja
![7](https://user-images.githubusercontent.com/25834335/65391100-1d2eb800-dd1a-11e9-9e46-e697caaa8ed4.png)

### Apa yang terjadi?
Agenda Kegiatan masuk sebagai artikel atau berita baru

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by stanleydsk** [comment]
Usul saya: untuk Agenda tetap dimunculkan di Widget, kontennya berisi kegiatan2 atau info kegiatan yang belum dilaksanakan (atau akan dilaksanakan) di masa mendatang;
sedangkan untuk berita adalah berisi konten SETELAH sebuah kegiatan selesai dilakukan ...

**Comment by MUHAMMADRANGSEL** [comment]
Ya memang seperti itu yg diinginkan, untuk agenda dia ada di widget sedangkan berita kegiatan itu nanti dia artikel

**Comment by stanleydsk** [comment]
Apa kita tidak perlu menambahkan fitur, tapi yang perlu dilakukan hanyalah MENAMBAHKAN KETERANGAN dalam Panduan Pengguna OpenSID terkait Fitur Agenda dan Fitur Artikel???

**Comment by ropelid** [comment]
apakah yang di harapkan seperti ini pak @MUHAMMADRANGSEL 
[pimisahan Sub Menu Agenda supaya menyendiri OpenSID#2299](https://github.com/ropelid/OpenSID/commit/5090c64002cd6028dc2758fbb8a42fc869083420)

**Comment by MUHAMMADRANGSEL** [comment]
Ada gambarnya bang

**Comment by ropelid** [comment]
Seperti Ini

![image](https://user-images.githubusercontent.com/33674500/65448280-a6e99d00-de62-11e9-9bb9-0b9ea8165513.png)

**Comment by MUHAMMADRANGSEL** [comment]
Ya pass

**Comment by afa28** [comment]
Mungkin Issue Ini Bisa Ditutup Pak @MUHAMMADRANGSEL

**Comment by afa28** [comment]
Sudah dicommit ke master melalui PR #2690
