### ISSUE TITLE
Ass.wr.wbr. Saya Coba Upload Artikel sama gambar  tetapi Tidak Muncul gambarnya namun data tersimpan. Bagaimana ini

### ISSUE THREAD

**Issue by irawanrada** [OpenSID/OpenSID#2301]
### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by uncu29** [comment]
tidak muncul?
disitus demo tidak ada masalah, muncul berarti msalh ada diserver anda. silahkan gabung digrup fb opensid. dan mohon dibaca cara mengirimkan issue
![Website Resmi Desa Dasan Borok - Google Chrome 23_09_2019 23 38 36](https://user-images.githubusercontent.com/51182125/65444942-57ec3980-de5b-11e9-9d30-e67382be1283.png)

**Comment by eddieridwan** [comment]
@irawanrada , untuk bertanya penggunaan harap di https://www.facebook.com/groups/OpenSID/.

Ok, kami akan tutup issue ini, karena bukan pekerjaan untuk programmer.
