### ISSUE TITLE
Situs demo.opensid.my.id  Masih Masih menggunakan  sistem lama

### ISSUE THREAD

**Issue by andryrukandifauzy** [OpenSID/OpenSID#2302]
### Bagaimana alurnya sampai muncul masalah?
banyaknya error yang muncul ketika saya menginstall opensid di sitem terbaru ( php7x > dan database mysql/mariadb 8.X /10.X > )
![Screenshot_3](https://user-images.githubusercontent.com/42363553/65480417-9285be80-debb-11e9-9ddf-e3a6f898e83f.png)

Ketika mengecek error di website demo itu tidak terjadi apa apa/ tidak error sesuai sistem yang digunakan oleh user . 

### Seperti apa yang diharapkan?
sistem yang digunakan website demo harus sesuai standar atau sistem lebih baru 

### Apa yang terjadi?

tidak bisa menegeck error di sistem terbaru karena sistem lama masih ok ok saja terhadap error di sistem lebih baru
### Informasi tambahan 

saya menggunakan ph 7.3.9.x dan maridaDB 10.x
sistem operasi linux
| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    latest
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
Pak @eddieridwan, ini kyaknya sdah disesuaikan.
