### ISSUE TITLE
[Bug][keuangan] perlu perbaikan di widget keuangan dan artikel keuangan

### ISSUE THREAD

**Issue by WAHYUDIK** [OpenSID/OpenSID#2303]
### Bagaimana alurnya sampai muncul masalah?

1. ketika kita melihat widget keuangan ada beberapa yang tampil 2 (dua) kali, seperti contoh (bidang penyelenggaraan pemerintah desa) tampil dua kali dengan nilai rupiah yang berbeda.
![image](https://user-images.githubusercontent.com/31026980/65578003-29777700-df9f-11e9-8729-d3670f30b68b.png)
2.  nama di submenu semuanya realisasi
![image](https://user-images.githubusercontent.com/31026980/65578116-62175080-df9f-11e9-8f19-04b4a4ecf856.png)
3. Tampilan artikel keuangan kurang userfrendly baik ketika dilihat di laptop ataupun di hp
![image](https://user-images.githubusercontent.com/31026980/65578262-a86caf80-df9f-11e9-820a-77a9e7b5e0b2.png)
![WhatsApp Image 2019-09-25 at 2 13 10 PM](https://user-images.githubusercontent.com/31026980/65578222-92f78580-df9f-11e9-865d-d4d9171bd4c3.jpeg)

### Seperti apa yang diharapkan?
1.  ketika kita melihat realisasi belanja untuk bidangnya tidak tampil 2 (dua) kali, seharunya hanya ada 5 bidang,
2.  nama di submenu agar tidak semuanya realisasi, melainkan 
3. agar diberikan tombol scrol atas/bawah dan kanan/kiri

### Informasi tambahan 
untuk tampilan baik widget sama artikel perlu sedikit perbaikan. 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
@WAHYUDIK , biasakan membuat SATU issue untuk masing2 masalah. Tidak digabung seperti yg anda buat ini. Karena itu akan menyulitkan proses penerapan dan reviewnya.

**Comment by WAHYUDIK** [comment]
iya pak

**Comment by eddieridwan** [comment]
Bung @WAHYUDIK , apa yg anda maksud dengan `nama di submenu agar tidak semuanya realisasi, melainkan`. Mohon anda perjelas, dan mungkin beri contoh apa masalahnya. Terima kasih.

**Comment by WAHYUDIK** [comment]
contoh yang sudah ada
1. Realisasi Pelaksanaan APBDes
2. Realisasi Pendapatan APBDes
3. Realisasi Belanja Desa

Disiskeudes itu hanya
1. Pendapatan APBDes
2. Realisasi APBDes
![image](https://user-images.githubusercontent.com/31026980/66022908-9f3c8f00-e519-11e9-8208-b8bcc4a4eb85.png)

**Comment by eddieridwan** [comment]
Perbaikan sudah dicommit ke `master`
