### ISSUE TITLE
Penambahan Tombol Aksi HAPUS Pada Menu Keuangan>Impor

### ISSUE THREAD

**Issue by PWidodo** [OpenSID/OpenSID#2304]
### Bagaimana alurnya sampai muncul masalah?
Hasil convert database siskeudes CSV yang telah diimportkan ke menu Keuangan pada sub menu impor bisa lebih dari 3 file (contoh: tahun 2016, tahun 2017, tahun 2018) manakala kita ingin menghapus salah satu file tersebut perlu membuka database cPanel atau localhost/phpmyadmin dan mencari tabel sumber data tersebut tersimpan.

### Seperti apa yang diharapkan?
Kalau dibuatkan tombol aksi Hapus, maka kita dapat menghapus salah satu data siskeu yang telah terimport dengan mudah.
![Tombol Hapus](https://user-images.githubusercontent.com/45189822/65630549-de418080-dfff-11e9-910c-91ae87a8e1e8.jpg)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by uncu29** [comment]
Begini mas?

![Sistem Informasi Desa Desa Hibrida Jaya - Keuangan - Impor Data - Mozilla Firefox 26_09_2019 20 18 16](https://user-images.githubusercontent.com/51182125/65691328-d682ea00-e09a-11e9-82d5-1656a6a3d6f9.png)

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR #2305
