### ISSUE TITLE
TAMBAH DATA PENDUDUK ERROR 

### ISSUE THREAD

**Issue by HAWARIEZ** [OpenSID/OpenSID#2306]
| Versi OpenSID    | terbaru

**Comment by uncu29** [comment]
Bisakh dilampirkan errorny?

**Comment by eddieridwan** [comment]
Segera lengkapi issue ini sesuai petunjuk https://github.com/OpenSID/OpenSID/wiki/Pengelolaan-Masalah-dan-Permintaan-Perbaikan-SID.

Issue yg tidak lengkap atau jelas akan ditutup.

**Comment by roaddee** [comment]
juga di bisa dicek terlebih dulu dengan mencoba langkah yg error di situs demo.opensid.my.id, jika di situs tersebut tidak terjadi error, berarti masalahnya bukan di script opensid. tapi yang lain.

**Comment by eddieridwan** [comment]
Ok, issue ini ditutup, karena yg melaporkan tidak melengkapi.
