### ISSUE TITLE
cara menampilkan import data siskeudes, dan menonaktifkan pilihan rt dan rw

### ISSUE THREAD

**Issue by supantara** [OpenSID/OpenSID#2307]
Mohon ijin untuk digunakan sebagai system di desa saya, saya coba install offline untuk di pelajari fitur-fitru yang terdapat di opensid.

kendala:
1. bagaimana cara import data siskeudes ke opensid karena menu keuangan tidak muncul di administrator.
2. bagaimana cara mengatasi tambah dan edit data penduduk. karena kami disini rt dan rw tidak ada, sedangkan itu harus diisi

mohon petunjuk, karena saya baru. dan tertarik menggunakan system ini

**Comment by eddieridwan** [comment]
@supantara issue adalah untuk hal2 yg akan dikembangkan di OpenSID, bukan tempat bertanya.

Untuk penggunaan OpenSID, silakan bertanya di https://www.facebook.com/groups/OpenSID.

Ok, issue ini akan kami tutup.
