### ISSUE TITLE
[Data awal] Tambahkan tabel keuangan_master

### ISSUE THREAD

**Issue by msazzuhair** [OpenSID/OpenSID#2309]
### Bagaimana alurnya sampai muncul masalah?
Mengimpor file "contoh_data_awal_20190831.sql" ke mysql. Akan tetapi, Keuangan_model.php membuat koneksi ke tabel keuangan_master yang belum ada sehingga muncul HTTP error 500

### Seperti apa yang diharapkan?
Tambahkan struktur tabel keuangan_master + sampel data

### Apa yang terjadi?
Muncul pesan 500 error karena tabel keuangan_master tidak ada

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 7.2.11
| System operasi   | Linux

**Comment by eddieridwan** [comment]
Kalau install dari versi pra-rilis, jalankan Pengaturan > Database > Migrasi DB untuk memutakhirkan struktur database. Data contoh nanti dilengkapi di rilis resmi pada setiap tgl 1. Dijelaskan di panduan. Silakan baca panduan.

Issue ini akan ditutup, karena bukan sesuatu untuk diperbaiki.
