### ISSUE TITLE
[jdih] Jquery loaded beberapa kali & pop up muncul

### ISSUE THREAD

**Issue by ekasatriabahari** [OpenSID/OpenSID#2315]
### Bagaimana alurnya sampai muncul masalah?

Jquery muncul beberapa kali, menyebabkan conflict, saya sudah hapus di local untuk duplikasi jquery tapi malah muncul pop up seperti di gambar.

### Seperti apa yang diharapkan?

Jquery tidak duplikat dan Pop Up hilang

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 7.2
| System operasi   | Windows 10

![conflict-jquery](https://user-images.githubusercontent.com/39932698/65927379-1a277c00-e42c-11e9-8a28-2285977f197b.png)
![pop-up](https://user-images.githubusercontent.com/39932698/65927380-1ac01280-e42c-11e9-8cc2-3ff4085fd093.png)

**Comment by eddieridwan** [comment]
Sudah dikerjakan.
