### ISSUE TITLE
[Surat] Penandatanganan di cetak keluarga ketika Plt Kepala desa tidak bisa berubah

### ISSUE THREAD

**Issue by WAHYUDIK** [OpenSID/OpenSID#2317]
### Bagaimana alurnya sampai muncul masalah?
Ketika mau mencetak Kartu Keluarga yang muncul di penandatanganan tetap kepala desa, tidak bisa secara otomatis berganti dengan plt, padahal penandatangan di pemerintah desa sudah dirubah ke plt.
![image](https://user-images.githubusercontent.com/31026980/65970342-8e940680-e490-11e9-9519-ff365ab3a64a.png)
![image](https://user-images.githubusercontent.com/31026980/65970347-92c02400-e490-11e9-8af3-780fca6ce6f8.png)

### Seperti apa yang diharapkan?
ketika kepala desa sudah cuti/berhenti, dan digantikan oleh PLT/PJ, setelah pengaturan penandatanganan di pemerintah desa sudah dirubah ke plt/pj maka setiap penandatanganan secara otomatis berubah juga.
### Apa yang terjadi?
saat ini masih dipersuratan dan cetak laporan bulana saja yang sudah otomatis berubah ketika status kepala desa berganti ke PLT/PJ, untuk penandatangana lainnya masih mengikuti nama kepala desa di pengaturan identitas desa.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by ai-skematik** [comment]
Kalau di ganti nama kepala desa di identitas desa?

**Comment by WAHYUDIK** [comment]
klo dirubah dari sana hanya nama saja yang berubah pak, jabatan tetap tidak berubah
![image](https://user-images.githubusercontent.com/31026980/65972727-79b97200-e494-11e9-870e-ef8af89262aa.png)

**Comment by ai-skematik** [comment]
![image](https://user-images.githubusercontent.com/48144047/66018462-5da3e800-e509-11e9-8883-88194890da15.png)

**Comment by ai-skematik** [comment]
maksudnya jabatannya jadi plt mengikuti jabatan di info desa -> pemerintahan desa ?

**Comment by WAHYUDIK** [comment]
iya pak seperti itu. jadi ketika ada pergantian kepala desa enk. cukup seting di info desa>Pemerintah desa>

**Comment by balongbesuk** [comment]
ini berdampak juga bada seluruh blanko F (lampiran surat) tidak berubah ketika penanda tangan dirubah ke Plt. Kepala Desa

**Comment by WAHYUDIK** [comment]
> ini berdampak juga bada seluruh blanko F (lampiran surat) tidak berubah ketika penanda tangan dirubah ke Plt. Kepala Desa

saya coba surat pindah di lampirannya sudah ikut pengaturan pemerintahan

**Comment by balongbesuk** [comment]
rata ada di permohonan kartu keluarga dan permohonan kartu keluarga baru

**Comment by afa28** [comment]
Apakah ini masih bermasalah???

**Comment by WAHYUDIK** [comment]
![image](https://user-images.githubusercontent.com/31026980/91007574-86900880-e606-11ea-8ddf-b9d8e33d85d3.png)
masih sama mas @afa28 , mungkinkah ketika akan cetak Kartu Keluarga dibuatkan pilihan siapa yang akan ttd?seperti dipersuratan?sehingga lebih mempermudah operator/admin ketika mau cetak KK apa bila kepala desa tidak ada

**Comment by andifahruddinakas** [comment]
Mas @vickyrolanda, mungkin bisa dijelaskan konsep Plt dan sekalian dengan solusi (alurnya).
Mas @devrakapriyo mohon diperiksa, apakah bug?

**Comment by andifahruddinakas** [comment]
Solusi : 
1. Tambahkan tombol plt pada pengurus jika kepala desa tidak ada.
2. Sediakan pengaturan sebutan plt desa.
3. Kepala desa otomatis terganti sesuai dengan plt yg terpilih.
4. Terapkan di semua modul yang berkaitan dengan penanda tangan.

**Comment by vickyrolanda** [comment]
Solusinya bisa dengan : 

- [ ] Non-aktifkan kepala desa
- [ ] Edit jabatan kepala desa menjadi Plt.Kepala Desa
- [ ] tambah pejabat kepala desa dengan jabatan Plt.Kepala desa.
<img width="537" alt="image" src="https://user-images.githubusercontent.com/59082428/197998762-91934747-807b-4d6b-9fe1-7b8ad55c307a.png">

Jika punya saran yang lain bisa commentar dan reopen kembali issue ini pak.
