### ISSUE TITLE
Perbaiki Restore Database - "Sebaiknya hasil restore DB tidak menghapus data tapi hanya menimpa data saja"

### ISSUE THREAD

**Issue by HerryWanda** [OpenSID/OpenSID#2318]
### Bagaimana alurnya sampai muncul masalah?
Menggunakan dua server OpenSID "Offline dan Online"
Offline digunakan untuk layanan supaya space hosting online tidak penuh.
Online digunakan untuk update informasi dan Lainnya.

Jadi saya mau melakukan restore database offline untuk mengisi arsip layanan surat baik itu layanan dan arsip sekretariat surat masuk & keluar maupun perubahan data yang dilakukan di offline oleh operator layanan.

Setelah melakukan restore, database berhasil di restore sesuai database yg offline..
Namun setelah terestore semuanya, data yang ada di Online hilang semuanya (baik itu artikel dan DLL) data yang ada hanya data yang sama seperti di opensid offline.

### Seperti apa yang diharapkan?
Yang diharapkan : restore database opensid hendaknya tidak menghapus data yang ada baik itu di offline maupun online, sebaiknya hanya menambah/menimpa/ data yang belum ada sehingga data yang ada tidak hilang/ terhapus.

### Apa yang terjadi?
1.Setelah melakukan restore database offline berhasil, data yang ada di Online hilang semuanya (baik itu artikel , data dan DLL) data yang ada hanya data yang kita restore / data offline tadi. database online hilang/terhapus.
2. Pengaturan yang di atur di online juga berubah saat melakukan restore database offline, pengaturan berubah menjadi pengaturan yang kita lakukan di offline.

ini salah satu hasil restore :
Artikel yang muncul setelah direstore database offline - artikel nya artikel yg ada di offline , pengaturan thema juga berubah.
![Artikel web offline- lama](https://user-images.githubusercontent.com/32125282/66017761-55967900-e506-11e9-901e-ecb563bc9e95.jpg)

Artikel di online : yang sebanarny udah sampai bulan september .
![Artikel web online- baru](https://user-images.githubusercontent.com/32125282/66017783-6e9f2a00-e506-11e9-8438-c2d1b67f800e.jpg)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah ada issuenya, bung @HerryWanda . Lihat https://github.com/OpenSID/OpenSID/issues/2048. Kalau sama, silakan tutup yg ini.
