### ISSUE TITLE
[jdih] Pindahkan pilihan link 'Peraturan Desa'

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#2319]
### Bagaimana alurnya sampai muncul masalah?
1. Buka _Admin Web > Menu > Menu Statis_
2. Buat menu atau submenu baru
3. Klik pilihan _Jenis Link_. 
4. Perhatikan pilihan yg ada
5. Klik pilihan _Statistik Lainnya_
6. Klik pilihan _Link_
7 Perhatikan pilihan yang ada

### Seperti apa yang diharapkan?
Seperti dijelaskan di gambar2 berikut. 
![pilihan-jenis-link](https://user-images.githubusercontent.com/249563/66021397-fe0c0380-e52d-11e9-85c1-f2a7d01a89ae.jpg)
![pilihan-link](https://user-images.githubusercontent.com/249563/66021398-fea49a00-e52d-11e9-865c-277713136514.jpg)

### Apa yang terjadi?
Pilihan 'Peraturan Desa' masih pilihan _Jenis Link_ dan belum merupakan pilihan _Link_ 'Halaman Statis Lainnya'.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | jdih
| Versi PHP        | 
| System operasi   |

**Comment by dikisiswanto** [comment]
Link peraturan desa ini ada di mana ya pak? mau coba buat menu tapi tidak ada di pilihan.

![image](https://user-images.githubusercontent.com/22239074/66266850-290f9380-e85d-11e9-9f01-d0fea4d1ca84.png)

![image](https://user-images.githubusercontent.com/22239074/66266854-42184480-e85d-11e9-8a51-8038a99d7e12.png)

**Comment by eddieridwan** [comment]
Sudah dikerjakan.
