### ISSUE TITLE
[keuangan] Unggah laporan keuangan Siskeudes

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#2320]
### Bagaimana alurnya sampai muncul masalah?
1. Lihat pilihan submenu _Keuangan_ di navigasi kompenen Admin

### Seperti apa yang diharapkan?
Ada submenu _Laporan Siskeudes_. Halaman yg ditampilkan oleh submenu ini:
- tombol untuk mengunggah laporan Siskeudes dalam berbagai format yg disediakan Siskeudes
- mendaftarkan laporan Siskeudes yang telah diunggah, dengan informasi tahun anggaran, jenis laporan, tanggal diunduh dari Sisikeudes, tanggal diunggah
- aksi untuk menghapus laporan yg telah diunggah
- aksi untuk mengubah (mengunggah file pengganti) untuk suatu laporan
- filter untuk memilah daftar berdasarkan tahun anggaran dan jenis laporan
- daftar bisa diurut berdasarkan tanggal unduh dari Siskeudes
- daftar bisa diurut berdasarkan tanggal unggah 

### Apa yang terjadi?
Submenu _Laporan Siskeudes_ belum ada.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19.10
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Jenis file yg boleh diunggah adalah segala jenis laporan yang dihasilkan oleh Siskeudes, termasuk:

- pdf
- html
- csv
- smd
- xlsx

**Comment by eddieridwan** [comment]
Pekerjaan untuk issue ini sudah dimulai di branch `https://github.com/OpenSID/OpenSID/tree/lap-siskeudes`. Teruskan saja branch `lap-siskeudes` tersebut.

**Comment by wawan87aja** [comment]
@eddieridwan  saya coba mengerjakan fitur upload laporan siskeudes, tapi bukan dalam bentuk dokumen. saya coba membuat fungsi upload laporan siskeudes, tapi dalam bentuk data. sehingga nantinya bisa dikembangkan untuk menampilkan grafik keuangan dan juga solusi bagi desa-desa yang kesulitan untuk menggunakan menu upload file csv.
saya masih dalam tahap belajar jadi mohon bimbingannya

[https://github.com/wawan87aja/opensid-siskeudes](url)

**Comment by eddieridwan** [comment]
Bung Wawan, terima kasih.

Sebaiknya dibahas di Slack (http://bit.ly/slack-opensid). Teman2 programmer
membahas teknis di situ.

Silakan bergabung di channel #keuangan-desa di Slack.

**Comment by afa28** [comment]
Sudah di `rilis-dev`.
