### ISSUE TITLE
[keuangan] Kirim laporan Siskeudes ke OpenDK

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#2321]
### Bagaimana alurnya sampai muncul masalah?
Lihat issue https://github.com/OpenSID/OpenSID/issues/2320 dan anggap telah diterapkan.
1. Buka _Keuangan > Laporan Siskeudes_
2. Di daftar laporan cari _Aksi > Kirim ke OpenDK_

### Seperti apa yang diharapkan?
Ada tombol _Aksi > Kirim ke OpenDK_.
Fitur ini akan mengirim laporan ybs ke server OpenDK yg ada di setting aplikasi.
Laporan yg telah dikirim tidak dapat dihapus.
Tanggal/waktu pengiriman akan ditampilkan di daftar laporan.
Ada filter untuk menampilkan laporan yg telah dikirim da belum dikirim.
Daftar bisa diurut berdasarkan waktu pengiriman.

### Apa yang terjadi?
Belum ada _Aksi > Kirim ke OpenDK_.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | jdih
| Versi PHP        | 
| System operasi   |

**Comment by mizwaruddin** [comment]
Ditambah kirim laporan keuangannya menggunakan API
