### ISSUE TITLE
Membuat nilai default kewarganegaraan menjadi WNI

### ISSUE THREAD

**Issue by lastingdone** [OpenSID/OpenSID#2322]
### Bagaimana alurnya sampai muncul masalah?
Saat import dari data penduduk excel ke openSID, kewarganegaraan tidak otomatis WNI

### Seperti apa yang diharapkan?
Saat import data, kewarganegaraan sudah auto WNI

### Apa yang terjadi?
Saat sudah saya impor, tidak auto WNI. Jadi untuk mengubah data WNI supaya muncul mata pilih harus merubah data tiap penduduk. Jadinya lama

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by balongbesuk** [comment]
![12121](https://user-images.githubusercontent.com/35319600/66093053-d44bee80-e5b8-11e9-9306-fe1f94aa3431.jpg)

**Comment by lastingdone** [comment]
Saya import dari Data SIAK, tapi tidak auto WNI... Mohon bisa diperjelas alur nya

**Comment by balongbesuk** [comment]
apakah data siak tersebut terdapat kolom WNI?

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
