### ISSUE TITLE
Pemanggilan NIK di beberapa surat yang belum terindex (terload semua data penduduknya)

### ISSUE THREAD

**Issue by WAHYUDIK** [OpenSID/OpenSID#2323]
### Bagaimana alurnya sampai muncul masalah?
ketika kita kita mau membuat surat, dimana untuk pilihan warganya bisa milih dari database/non database, masih terbaca seluruh penduduk, tidak terindex seperti surat2 yang lainnya. salah satu contoh yakni surat keterangan lahir.
![image](https://user-images.githubusercontent.com/31026980/66043387-31a85700-e549-11e9-89de-84fb9379b964.png)
dan juga pemanggilan NIKnya tidak menampilkan ID sama alamat, 
![image](https://user-images.githubusercontent.com/31026980/66043420-484eae00-e549-11e9-93e4-00e08d850006.png)

### Seperti apa yang diharapkan?
agar disemua surat yang pemanggilan data penduduknya yang ada 2 pilihan bisa terindex semua, seperti halnya surat-surat yang lain

### Apa yang terjadi?
saat ini masih belum semua pemanggilan NIK terindex

### Informasi tambahan 
Surat-surat yang masih tidak terindex pemanggilan NIKnya:
1. surat keterangan kelahiran
2. surat kematian> saksi 1 dan saksi 2, untuk pelapor sudah terindex
3. Penghasilan orang tua
4. 
| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
