### ISSUE TITLE
[keuangan] nilai rupiah di realisasi berada di tabel sisa anggaran

### ISSUE THREAD

**Issue by WAHYUDIK** [OpenSID/OpenSID#2324]
### Bagaimana alurnya sampai muncul masalah?
setelah import database siskeudes hasil realisasinya terdapat kesalahan posisi nilai rupiah di tabelnya, yang seharunya berada di kolom realisasi, akan tetapi saat ini berada di kolom sisa anggaran
![image](https://user-images.githubusercontent.com/31026980/66048710-36263d00-e554-11e9-972a-f04838f57ed4.png)
kemudian ketika kita melihat laporan, jumlah anggaran nilainya tidak sama dengan dipendapatan
![image](https://user-images.githubusercontent.com/31026980/66048821-6f5ead00-e554-11e9-9b08-c9bcc62adaed.png)

### Seperti apa yang diharapkan?
nilai rupiah berada di posisi masing-masing kolom dan tabel

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by ekasatriabahari** [comment]
sudah pastikan tidak ada data tahun yang duplikat di import keuangan?? 
untuk gambar nomor 2 merupakan total keseluruhan anggaran dari semua jenis belanja (kode 4, 5, 6)

**Comment by ai-skematik** [comment]
Gambar no 2 maksudnya pendapatan+belanja+pembayaan?

**Comment by ekasatriabahari** [comment]
iya @ai-skematik , ada menu di side bar untuk klasifikasi masing2 jenis belanja

**Comment by WAHYUDIK** [comment]
> sudah pastikan tidak ada data tahun yang duplikat di import keuangan??
> untuk gambar nomor 2 merupakan total keseluruhan anggaran dari semua jenis belanja (kode 4, 5, 6)

sudah pak. itu sya hanya mengimport database yang 2018 saja. 
unutk gambar nomor 2 itu maksudnya penjumlahannya jadi 2 kali lipat dari jumlah pendapatan

**Comment by ekasatriabahari** [comment]
> > sudah pastikan tidak ada data tahun yang duplikat di import keuangan??
> > untuk gambar nomor 2 merupakan total keseluruhan anggaran dari semua jenis belanja (kode 4, 5, 6)
> 
> sudah pak. itu sya hanya mengimport database yang 2018 saja.
> unutk gambar nomor 2 itu maksudnya penjumlahannya jadi 2 kali lipat dari jumlah pendapatan

gambar nomor 2 itu total seluruh anggaran, bukan untuk pendapatan saja pak, coba menu sidebarnya ada klasifikasi anggaran

**Comment by WAHYUDIK** [comment]
maksudnya total seluruh anggaran (pendapatan+belanja)?

**Comment by ekasatriabahari** [comment]
> maksudnya total seluruh anggaran (pendapatan+belanja)?
iya seluruh jenis belanja,
jika ada pendapata, belanja & pembiayaan maka akan tertotal pada grafik default
untuk rincian ada di menu sidebar

**Comment by ai-skematik** [comment]
Total anggaran itu seharusnya hanya menampilkan pendapatan dan penerimaan pembiayaan.

**Comment by ekasatriabahari** [comment]
> Total anggaran itu seharusnya hanya menampilkan pendapatan dan penerimaan pembiayaan.

yang ini tidak ada di briefing modul kemarin, silahkan buat issue baru pak @ai-skematik

**Comment by eddieridwan** [comment]
Perbaikan sudah dicommit ke `master`
