### ISSUE TITLE
[jdih] Perbaikan halaman peraturan desa di web

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#2326]
### Bagaimana alurnya sampai muncul masalah?
1. Buat menu statis dengan link ke Peraturan Desa
2. Tampilkan halaman Peraturan Desa di web
3. Perhatikan isi tampilan

### Seperti apa yang diharapkan?
Masalah yg dicatat di gambar berikut telah diperbaiki
![perbaikan-peraturan-desa](https://user-images.githubusercontent.com/249563/66094992-4c2a1100-e5d9-11e9-9ce8-93e604738930.jpg)

### Apa yang terjadi?
Belum diperbaiki

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | jdih
| Versi PHP        | 
| System operasi   |

**Comment by ekasatriabahari** [comment]
apa maksudnya `hasil salah` pada input tentang tersebut pak?

**Comment by eddieridwan** [comment]
Misalnya, di contoh di atas, masukkan teks 'miau' yg akan dicari. Tetapi hasilnya kosong, padahal ada yg nama dokumennya berisi 'Miau'. Yaitu, cari perlu juga memeriksa nama dokumen.

**Comment by eddieridwan** [comment]
Selain itu, setelah menjalankan 'Cari' (atau setelah memilah) filter (misalnya Tahun) yg digunakan perlu tetap tampil, supaya jelas apa filter yg diterapkan pada daftar peraturan yg tampil. Saat ini semua filter menjadi kosong.

**Comment by ekasatriabahari** [comment]
jadi menggunakan button cari atau onchange saja pak @eddieridwan ??
