### ISSUE TITLE
[jdih] Buat filter halaman Peraturan Desa menjadi horizontal

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#2328]
### Bagaimana alurnya sampai muncul masalah?
1. Lihat halaman Peraturan Desa di web
2. Perhatikan isian filter

### Seperti apa yang diharapkan?
Filter tampil secara horizontal mengikuti penampilan filter di modul Admin

### Apa yang terjadi?
Masih vertikal
![filter-horizontal](https://user-images.githubusercontent.com/249563/66096271-c9f01b80-e5dd-11e9-997d-7d77ec17c3ef.jpg)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | jdih
| Versi PHP        | 
| System operasi   |

**Comment by junandia** [comment]
![gambar](https://user-images.githubusercontent.com/10545975/66117940-6bd43000-e5ff-11e9-925b-63e309886eba.png)
apakah seperti ini pak?

**Comment by eddieridwan** [comment]
Sudah dikerjakan melalui PR #2334. Terima kasih @junandia
