### ISSUE TITLE
[Bug] Error Modul Submodul Saat Mengubah Status

### ISSUE THREAD

**Issue by FahruddinAKas** [OpenSID/OpenSID#2330]
### Bagaimana alurnya sampai muncul masalah?
Langkah Kesalahan : 
- Success = Menu > Pengaturan > Modul > Lihat Submodul > Ubah Data > Simpan (Edit Kecuali status).

- Success = Menu > Pengaturan > Modul > Lihat Submodul > Ubah Data > Simpan (Edit Semua).

Keterangan :
Terjadi Error Update DB saat mengedit submenu dengan perubahan kondisi aktif menjadi tidak aktif atau sebaliknya. Setelah mengklik tombol simpan akan dialihkan ke halaman error DB, namun setelah halaman error DB di refresh data tersimpan secara normal.

![submenu](https://user-images.githubusercontent.com/7290110/66098385-9eb10080-e5cc-11e9-94eb-469bfe553270.PNG)

### Seperti apa yang diharapkan?
Perbaikan error edit Submodul 

### Apa yang terjadi?
Edit Submodul jadi lancar tanpa Error DB

### Informasi tambahan 
Berjalan normal jika status Submodul tidak dirubah

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
