### ISSUE TITLE
Mohon Surat Keterangan Nikah .. Di tambahi Form Surat keterangan Wali Nikah...Kayaknya Belum Ada... terima Kasih

### ISSUE THREAD

**Issue by fathan002** [OpenSID/OpenSID#2331]
### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by pahrulirfan** [comment]
wali nikah sudah disediakan kok, tempet kurangnya dimana mas @fathan002 ???

**Comment by uncu29** [comment]
Sepertinya issue ini bsa diclose pak eddie
