### ISSUE TITLE
Perlu Perbaikan Menu Bantuan Perorangan

### ISSUE THREAD

**Issue by Gunturwijay** [OpenSID/OpenSID#2333]
1. Perlu dihapus salah satu kolom alamat.
2. Perlu dibuat kolom nama dan NIK ayah ibu.
3. Perlu Penyempurnaan hasil dari ekspor.
4. Perlu penambahan tombol aksi pertahun, perdusun dan tombol aksi sesuai abjad

### Bagaimana alurnya sampai muncul masalah?
Menu Utama>Bantuan>Rincian Program Bantuan

### Seperti apa yang diharapkan?
1. Kolom alamat cukup 1 (satu) saja.
2. Tersedianya data nama dan nik orang tua.
3. Penyajian bentuk ekspor data sudah rapi dan sempurna.
4. Tersedianya tombol aksi pertahun, perdusun dan tombol aksi sesuai abjad
 

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
1. Kolom alamat cukup 1 (satu) saja. (Sudah tersedia)
3. Penyajian bentuk ekspor data sudah rapi dan sempurna. (Sudah tersedia, walaupun tdk sempurna)

**Comment by afa28** [comment]
Untuk point 2 dan 4 silahkan buat issue terpisah.
