### ISSUE TITLE
[rbac] Tambahkan migrasi untuk mempertahankan user yg sudah ada

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#2336]
### Bagaimana alurnya sampai muncul masalah?
1. Upgrade ke `rbac`. Jalankan migrasi DB
2. Periksa daftar pengguna dan grup

### Seperti apa yang diharapkan?
Pengguna dan grup yg sebelumnya ada masih tetap ada dengan hak akses yg sama.

### Apa yang terjadi?
Pengguna dan grup lama hilang dan diganti dengan pengguna dan group contoh.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19.10
| Versi PHP        | 
| System operasi   |

**Comment by fusionid** [comment]
Daftar pengguna dan grup akan disalin ke table baru secara otomatis ketika melakukan impor file **opensid-rbac-migrasi.sql** ke database yg sudah ada,  karena perintahnya sudah ditulis di file sql ini.
misalnya untuk copy pengguna yg sdh ada: 

INSERT INTO `users` ( `username`, `password`, `email`, `last_login`, `active`, `first_name`, `company`, `phone`, `user_img`, `id_grup`) SELECT `username`, `password`, `email`,  `last_login`, `active`, `nama`, `company`, `phone`, `foto`, `id_grup` FROM `user`;

Table lama = user dan Table baru = users

Proses migrasi ini **harus** dilakukan **sebelum** masuk ke app, karena proses otenifikasi sudah berubah.

**Comment by eddieridwan** [comment]
@fusionid sudah dilakukan persis seperti itu. Tapi pengguna lama hilang dan yg muncul pengguna contoh.

**Comment by eddieridwan** [comment]
Saya lihat di `opensid-rbac-migrasi.sql` ada script:
```
INSERT INTO `users` (`id`, `ip_address`, `username`, `password`, `email`, `activation_selector`, `activation_code`, `forgotten_password_selector`, `forgotten_password_code`, `forgotten_password_time`, `remember_selector`, `remember_code`, `created_on`, `last_login`, `active`, `first_name`, `last_name`, `company`, `phone`, `user_img`, `id_grup`) VALUES
(1, '::1', 'administrator', '$2y$12$VCCzq5PRAqu35pCZvB9OTu2zFeWojWzzi8CDod4IJgPftkZKc4bDi', 'admin@opendesa.id', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1569987030, 1569987233, 1, 'administrator', 'administrator', 'opendesa', '08100000000', 'opensid_logo4.png', 0),
(2, '::1', 'operator', '$2y$10$qXSD5Q.VPB4A4/rB2PMjsOt.acZje6o/UDFnEZMkZNss7WY8.7B5O', 'operator@opendesa.id', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1569987815, 1569993160, 1, 'operator', 'operator', 'opendesa', '08100000000', NULL, 0),
(3, '::1', 'redaksi', '$2y$10$3.yQJwZ/0dzTuFP6QAm.devK84PxGYXs3sNFitQFofER5uY55Flvm', 'redaksi@opendesa.id', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1569987949, NULL, 1, 'redaksi', 'redaksi', 'opendesa', '08100000000', NULL, 0),
(4, '::1', 'kontributor', '$2y$10$5jg96gMw3bwFJt5KtScxuuW3V/dFddBJGcjHQ.9MWe.GHcatAmfdy', 'kontributor@opendesa.id', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1569988078, 1569988201, 1, 'kontributor', 'kontributor', 'opendesa', '08100000000', NULL, 0);
```
Sepertinya ini yg menang.

**Comment by fusionid** [comment]
Proses otentifikasi akan memakai **Alamat Email**. tidak boleh ada pengguna yg memakai alamat email yg sama.

**Simulasi 1** 
![Screen Shot 10-04-19 at 07 21 PM](https://user-images.githubusercontent.com/10391199/66207869-13c02b00-e6de-11e9-9a76-0911e20f8067.PNG)

**Simulasi 2** 
![Screen Shot 10-04-19 at 07 22 PM](https://user-images.githubusercontent.com/10391199/66207880-191d7580-e6de-11e9-88b7-8c3fc20d3ec6.PNG)

Sebelum migrasi pastikan alamat email lengkap dan tidak ada yg sama.

**Comment by roaddee** [comment]
berarti 1 user harus dengan 1 alamat email ?

**Comment by fusionid** [comment]
1 user harus dengan 1 alamat email. 
Tapi bagi yg tidak online, alamat email bisa dummy / create alamat email sendiri saja.

**Comment by eddieridwan** [comment]
@fusionid, kita tidak bisa asumsi pengguna OpenSID memiliki alamat email, dan juga tidak bisa mengasumsi alamat email yg ada unik; karena memang selama ini alamat email tidak berfungsi aktif di OpenSID.

Karena itu, proses migrasi harus berasumsi status terburuk dan HARUS bisa menanganinya. Karena kita tidak bisa memaksa pengguna yg relatif awam IT untuk melakukan perubahan sebelum mereka siap. Kita ingin menghindari sebanyak mungkin error nanti pada waktu desa update ke rilis baru yg berisi RBAC.

Yaitu, proses migrasinya perlu melakukan sbb:
1. kalau alamat email belum ada bagi user, secara otomatis mengisi alamat email sementara (dummy)
2. kalau ada alamat email duplikat, secara otomatis membuat alamat email unik sementara bagi user tersebut

**Comment by eddieridwan** [comment]
@fusionid petunjuk menambah migrasi DB ada di https://github.com/OpenSID/OpenSID/wiki/Menambah-Migrasi-Database. 
Lihat contoh migrasi sebelumnya ada di `donjo-app/models/Database_model.php` dan di folder `donjo-app/models/migrations`. 

Kita perlu membuat proses update ke setiap rilis baru semudah mungkin.

**Comment by fusionid** [comment]
Setuju pak @eddieridwan kita perlu membuat proses update ke setiap rilis baru semudah mungkin, maka utk data alamat email pada proses migrasi ini akan menyalin langsung dari username pengguna yg sudah ada (karena valuenya unique) dengan ditambah "@opensid.id".
Pengguna tidak perlu melengkapi alamat email pada database lama dan bisa login dengan username seperti biasanya, hanya ditambah "@opensid.id" di belakang namanya.  misalnya yg selama ini login dgn memasukan username "admin" nantinya tetap input ke kolom login dgn "admin" plus "@opensid.id"  => "admin@opensid.id" dan dengan password yg selama ini sudah dipakai.

Mengenai migrasi DB, karena struktur manajemen login dan otenifikasi diupgrade dari siteman ke ion-auth maka migrasi DB hanya bisa dilakukan sebelum proses login. sebenarnya ada beberapa step yg bisa dilakukan dengan klik tombol migrasi pada menu pengaturan database, namun akan ada 2x proses migrasi : pra dan pasca login, untuk sementara step ini digabung ke step pra. tapi nanti setelah semua pengguna sudah paripurna migrasi ke rbac, proses migrasi bisa melalui menu pengaturan database saja.

File sql untuk migrasi dan contoh awal sudah diperbaharui.

**Comment by eddieridwan** [comment]
Sekarang masih sulit bagi pengguna untuk update ke versi `rbac`, karena harus secara manual mengimpor `opensid-rbac-migrasi.sql`. Idealnya transparan saja. 

Satu cara yg dapat anda gunakan adalah nebeng pada `donjo-app/models/Setting_model.php` untuk memaksa menjalankan migrasi pada saat masuk ke aplikasi. Model ini sengaja dibuat sebagai model pertama yg di-load sebelum aplikasinya aktif. Model in sudah pernah digunakan untuk memaksa migrasi pada saat tabel belum siap untuk menjalankan aplikasi.

Lihat gambar script di model itu. Tambahkan saja kasus rbac di situ. Dan masukkan script migrasi rbac ke file migrasi biasa, yaitu tambahkan ke `donjo-app/models/migrations/Migrasi_1910_ke_1911.php`.

![paksa-migrasi](https://user-images.githubusercontent.com/249563/66726824-3ba25200-ee87-11e9-8e82-d6cc9336ed31.jpg)

**Comment by fusionid** [comment]
Sekarang ketika user masuk ke halaman login admin dari frontpage maka akan dicek apakah databasenya sudah RBAC, Jika belum maka DB lama akan dimigrasi secara otomatis ke DB RBAC

https://github.com/OpenSID/OpenSID/commit/c455cb72c53ad002ca10b7a2b535f50f8415a897

**Comment by afa28** [comment]
Sudah di `rilis-dev`
