### ISSUE TITLE
Real Time Countdown Saat Error Login 3 Kali

### ISSUE THREAD

**Issue by ZER07URN** [OpenSID/OpenSID#2337]
### Bagaimana alurnya sampai muncul masalah?
Page Error Login 3 Kali Tidak Berjalan Real Time, Sihingga Tiap Saat Page Harus Di refressh

### Seperti apa yang diharapkan?
Page Harusnya Real Time Countdown

### Apa yang terjadi?
Supaya Tidak Tekan Refresh Terus

### Informasi tambahan 
Skrip untuk issu ini sudah saya edit walaupun masih kurang bagus. saya belum tau cara upload di opensid. masih pemula soalnya

![realtime](https://user-images.githubusercontent.com/7290110/66199151-35aeb300-e6c8-11e9-9606-fb73e59a433e.PNG)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by ZER07URN** [comment]
Saya sudah upload scripnya di github saya, tp tidak tahu untuk intgrasikan ke github opensid

**Comment by afa28** [comment]
Pak @eddieridwan , ini mungkin sudah bisa di close.

Issue Terkait #2701
