### ISSUE TITLE
[rbac] modul pengguna

### ISSUE THREAD

**Issue by afri18** [OpenSID/OpenSID#2340]
### Bagaimana alurnya sampai muncul masalah?
saat mencaba menambahkan pengguna baru tidak ada modul yang bisa dipilih untuk di aktifkan atau di nonaktifkan atau batasan pengguna

### Seperti apa yang diharapkan?
sebaiknya saat menambahkan pengguna disediakan modul yang bisa diaktifkan maupun yang di non aktifkan 
### Apa yang terjadi?
sama dengan cara yg lama

### Informasi tambahan 
agar ketua RW atau RT nantinya bisa mengakses data wilayahnya masing masing , nantinya bisa sebagai koreksi langsung dari ketua RT, RW ataupun kelompok posyandu
ma'af bila analisa saya salah

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by fusionid** [comment]
OpenSID-RBAC : mengatur kategori pengguna dan hak akses melalui RBAC (Role Based Access Control) dengan pengelompokan task berdasarkan Group.

Alur Kerjanya :

1. Membuat Group yang dikelompokan berdasarkan jenis tugas atau jabatannya
![task-1](https://user-images.githubusercontent.com/10391199/66215852-95b85000-e6ee-11e9-8326-dfcc29ec9bb0.PNG)

![task-1a](https://user-images.githubusercontent.com/10391199/66215863-9f41b800-e6ee-11e9-93ba-26d1969139b2.PNG)

2. Menentukan Modul yang bisa diakses oleh Group ini beserta kriteria hak aksesnya (Lihat / Tambah / Ubah / Hapus / Cetak(unduh)

![task-2](https://user-images.githubusercontent.com/10391199/66215902-b08ac480-e6ee-11e9-8497-84f0caf8162a.PNG)

3. Menambah Pengguna dan menentukan pilihan grup sesuai  jenis tugas atau jabatannya
![task-3](https://user-images.githubusercontent.com/10391199/66216136-1ecf8700-e6ef-11e9-95e9-d246eb39a156.PNG)
![task-3a](https://user-images.githubusercontent.com/10391199/66216152-242cd180-e6ef-11e9-8c4c-d4f766aea286.PNG)

- Jumlah grup dan konfigurasi hak akses tidak terbatas
- 1 Pengguna bisa dimasukan ke beberapa grup

**Comment by eddieridwan** [comment]
Sudah dikerjakan.
