### ISSUE TITLE
[rbac] user login

### ISSUE THREAD

**Issue by afri18** [OpenSID/OpenSID#2341]
### Bagaimana alurnya sampai muncul masalah?
saat sudah menambahkan pengguna baru lalu login yang di pakai bukan nama user tapi email

### Seperti apa yang diharapkan?
sebaiknya saat login tetap menggunakan nama user yang dibuat, email hanya sebagai koerksi

### Apa yang terjadi?
terlalu panjang kadang kalau menggunakan user memakai email, karna kalau yg online biasanya sudah ada menyediakan email untuk pengguna, misal opcigelam@email.desa.id

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by fusionid** [comment]
Login yang di pakai bukan nama user tapi email dengan pertimbangan dari aspek keamanan dan akan digunakan pada beberapa fungsi lainnya seperti mengirim password yg lupa (lupa kata sandi ?) atau reset password, jadi kalau pengguna lupa password tidak perlu bulak-balik menghubungi admin.

![Screen Shot 10-04-19 at 09 50 PM](https://user-images.githubusercontent.com/10391199/66217157-ff395e00-e6f0-11e9-8d33-1eadda5fa30f.PNG)

**Comment by MUHAMMADRANGSEL** [comment]
Bagus juga nih,,  sehingga tdk harus merubah lewat phpmyadmin

**Comment by afri18** [comment]
Itu yang di maksud, user tetap user login bukan email tapi pemulihan make emai

**Comment by fusionid** [comment]
@afri18 proses login sudah diperbaharui, sekarang bisa login dengan Email atau Username. 
Email tetap diperlukan untuk reset password.

**Comment by eddieridwan** [comment]
Sudah dikerjakan

**Comment by mering22** [comment]
@fusionid  maaf mas mau tanya login di opensid 20.01 kami erorr gak bisa masuk semua user gimna solusinya ya mas
