### ISSUE TITLE
Perlu dibuatkan Statistik Kependudukan berdasarkan Asuransi yang dimiliki

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#2342]
### Seperti apa yang diharapkan?
Di Form Isian penduduk sekarang sudah ada form untuk jenis asuransi yang dimiliki dan statistik kependudukan beum ada statistik berdasarkan jenis asuransi
![image](https://user-images.githubusercontent.com/25834335/66252552-5b4ec180-e787-11e9-9583-0bbcd0889c14.png)
![image](https://user-images.githubusercontent.com/25834335/66252557-643f9300-e787-11e9-9d03-1a88c5cf12ff.png)
Harapannya dengan adanya statistik kependudukan berdasarkan jenisa asuransi akan mempermudah desa dalam melihat siapa saja yang sudah memiliki asuransi
### Apa yang terjadi?
Belum adanya sstatistik kependudukan berdasakan jenis asuransi

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by afri18** [comment]
Tadinya mau buat, cuma malu, karna menunya ane yg usul ....

**Comment by MUHAMMADRANGSEL** [comment]
Kita bagi2 bang.. .

**Comment by dikisiswanto** [comment]
![image](https://user-images.githubusercontent.com/22239074/66266103-16905c80-e853-11e9-9bad-b450e60a53ca.png)

Apakah seperti ini, pak? Untuk judul statistiknya sudah tepat atau belum?

**Comment by MUHAMMADRANGSEL** [comment]
Pass

Pada tanggal Min, 6 Okt 2019 16.07, Diki Siswanto <notifications@github.com>
menulis:

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR #2347
