### ISSUE TITLE
[Bug] Menu Pemetaan>>Pengaturan Peta tdk aktif

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#2343]
### Bagaimana alurnya sampai muncul masalah?
![image](https://user-images.githubusercontent.com/25834335/66252599-bc769500-e787-11e9-8b85-b066f693e6b7.png)
![image](https://user-images.githubusercontent.com/25834335/66252605-cb5d4780-e787-11e9-9b4d-a7e26acbd33a.png)

### Seperti apa yang diharapkan?
Supaya Aktif seperti versi sebelumnya

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
