### ISSUE TITLE
bug 404 page not found

### ISSUE THREAD

**Issue by uncu29** [OpenSID/OpenSID#2344]
### Bagaimana alurnya sampai muncul masalah?

1. Buka Sekretariat > Peraturan Desa
2. halaman error 404 page not found

### Informasi tambahan 
![404 Page Not Found - Google Chrome 06_10_2019 03 09 14](https://user-images.githubusercontent.com/51182125/66260392-3b031f00-e7e8-11e9-89f0-5fe128ee0fa2.png)
| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19.10-pasca
| Versi PHP        | 
| System operasi   |

**Comment by ZER07URN** [comment]
Error Kalau Yang Pakai Slug, Kalau Pakai ID Masih Aman.

https://github.com/OpenSID/OpenSID/issues/2253

**Comment by ZER07URN** [comment]
https://github.com/OpenSID/OpenSID/issues/2253

**Comment by eddieridwan** [comment]
Menu _Peraturan Desa_ seharusnya belum masuk ke pra-rilis. Masih dalam tahap pengembangan. Sudah dihapus.
