### ISSUE TITLE
[JDIH]  Tidak tampilkan peraturan yg tidak aktif 

### ISSUE THREAD

**Issue by R4HMAT** [OpenSID/OpenSID#2345]
### Bagaimana alurnya sampai muncul masalah?

    1. Lihat halaman Peraturan Desa di web
    2, Perhatikan isian tampilan

### Seperti apa yang diharapkan?
ketika icon kunci di aktifkan supaya Nama Documen tidak muncul.
![tc1](https://user-images.githubusercontent.com/43318683/66265892-de375100-e847-11e9-996c-65876fccc29f.png)

![tc2](https://user-images.githubusercontent.com/43318683/66265894-e55e5f00-e847-11e9-8c1c-39d2bc05595f.png)

### Tanya | Jawab
-- | --
Versi OpenSID | jdih
Versi PHP |  
System operasi |

**Comment by ZER07URN** [comment]
Mungkin Kesalahan Pada Perintah SQLnya, Mungkin Perlu Ditambahkan Kondisi Dokumen Ditampilkan Dengan Kodisi Aktif Saja.

**Comment by eddieridwan** [comment]
Sudah dikerjakan melalui PR #2348. Terima kasih @dikisiswanto
