### ISSUE TITLE
Bug Ganti Password

### ISSUE THREAD

**Issue by ZER07URN** [OpenSID/OpenSID#2346]
### Bagaimana alurnya sampai muncul masalah?
Setelah Ganti Password Oleh Pengguna, Halaman Masih Bisa Diakses.

### Seperti apa yang diharapkan?
Setelah Ganti Password Pengguna Harus Dialihkan Terlebih Dahulu Untuk Login Kembali

### Apa yang terjadi?
Untuk Keamanan Saja

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
Pak @eddieridwan , ini mungkin sudah bisa di close.

Issue Terkait #2701
