### ISSUE TITLE
[jdih] Terapkan filter dan cari peraturan desa menggunakan ajax

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#2353]
### Bagaimana alurnya sampai muncul masalah?
1. Tampilkan halaman peraturan desa di web
2. Klik filter
3. Perhatikan bagaimana hasilnya ditampilkan

### Seperti apa yang diharapkan?
Hasil filter ditampilkan tanpa reload halaman.

### Apa yang terjadi?
Halaman masih direload

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | jdih
| Versi PHP        | 
| System operasi   |

**Comment by ekasatriabahari** [comment]
sudah dikerjakan dan dikirim pada PR https://github.com/OpenSID/OpenSID/pull/2364
