### ISSUE TITLE
[jdih] Jangan tampilkan dokumen lain di peraturan desa

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#2355]
### Bagaimana alurnya sampai muncul masalah?
1. Buat dokumen lain yg bukan peraturan desa
2. Tampilkan halaman peraturan desa
3. Perhatikan daftar peraturan

### Seperti apa yang diharapkan?
Dokumen yg bukan peraturan desa tidak tampil

### Apa yang terjadi?
Dokumen yg bukan peraturan desa juga tampil
![perbaikan-jdih](https://user-images.githubusercontent.com/249563/66389384-02478d80-ea14-11e9-9469-5a8b4328477f.jpg)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | jdih
| Versi PHP        | 
| System operasi   |

**Comment by ekasatriabahari** [comment]
sudah dikerjakan dan dikirim pada PR https://github.com/OpenSID/OpenSID/pull/2364
