### ISSUE TITLE
[Bug] Menu Pencarian di Peta tidak jalan

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#2356]
### Bagaimana alurnya sampai muncul masalah?
Setelah memasukkan titik koordinat di menu penduduk, setelah itu di menu pengaturan melakukan pencarian warga menu  Pemetaan>>Peta tidak berfungsi
![dd](https://user-images.githubusercontent.com/25834335/66389389-7bce8400-e9f2-11e9-813c-4867b3d66dc2.png)

### Seperti apa yang diharapkan?
Menu Pencarian di menu Pemetaan>>Peta berjalan seperti versi sebelumnya

### Apa yang terjadi?
Pencarian lokasi penduduk tdk muncul

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
