### ISSUE TITLE
[jdih] Tidak bisa unduh peraturan desa yg namanya berisi '/'

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#2357]
### Bagaimana alurnya sampai muncul masalah?
1. Buat peraturan desa dengan nama berisi karakter '/'
2. Tampilkan halaman peraturan desa
3. Coba unduh peraturan tersebut

### Seperti apa yang diharapkan?
Peraturan berhasil diunduh

### Apa yang terjadi?
Terjadi error, karena url salah
![perbaikan-jdih](https://user-images.githubusercontent.com/249563/66389518-55214500-ea14-11e9-958d-72344430c154.jpg)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | jdih
| Versi PHP        | 
| System operasi   |

**Comment by ekasatriabahari** [comment]
sudah dikerjakan dan dikirim pada PR https://github.com/OpenSID/OpenSID/pull/2364

**Comment by ekasatriabahari** [comment]
sudah dikerjakan dan dikirim pada PR https://github.com/OpenSID/OpenSID/pull/2364

**Comment by eddieridwan** [comment]
@ekasatriabahari solusi anda hanya khusus `' /'`. Bagaimana kalau `'/'` atau kombinasi karakter lain.

Coba lihat https://code-examples.net/en/q/28b936 untuk solusi untuk membuat nama file yg aman.

**Comment by ekasatriabahari** [comment]
sudah dikerjakan
