### ISSUE TITLE
[jdih] Sidebar navigasi perlu di-collapse supaya tidak terlalu sempit

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#2358]
### Bagaimana alurnya sampai muncul masalah?
1. Buka halaman _Sekretariat > Peraturan Desa_
2. Perhatikan isi tabel peraturan dan sidebar navigasi

### Seperti apa yang diharapkan?
Sidebar navigasi dalam status collapsed (minimized) dan data di tabel tidak terlihat terlalu sempit.

### Apa yang terjadi?
Sidebar navigasi terbuka dan data di tabel terlihat sempit.
![terlalu-sempit](https://user-images.githubusercontent.com/249563/66390619-c104ad00-ea16-11e9-8ce1-a4996c609a97.jpg)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | jdih
| Versi PHP        | 
| System operasi   |

**Comment by ekasatriabahari** [comment]
sudah dikerjakan dan dikirim pada PR https://github.com/OpenSID/OpenSID/pull/2364
