### ISSUE TITLE
[jdih] Tidak bisa filter peraturan desa apabila admin tidak login

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#2359]
### Bagaimana alurnya sampai muncul masalah?
1. Logout dari modul admin
2. Tampilkan halaman peraturan desa di web
3. Coba filter daftar peraturan desa

### Seperti apa yang diharapkan?
Daftar peraturan desa berhasil difilter.

### Apa yang terjadi?
Dialihkan ke halaman login ke modul Admin.
![logout](https://user-images.githubusercontent.com/249563/66391008-ada61180-ea17-11e9-932a-5e9f4439bd76.jpg)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | jdih
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Masalah ini disebabkan script untuk filter diletakkan di `donjo-app/controllers/Dokumen_sekretariat.php` yang merupakan controller `Admin_Controller`.

Solusinya adalah dengan membuat controller baru yg mengambil dari `Web_Controller` (seperti halnya `donjo-app/controllers/First.php`, dan masukkan action untuk filter peraturan desa di web di controller tersebut. Dengan demikian hak akses untuk filter tersebut sudah sesuai dengan hak akses web lainnya.

**Comment by fusionid** [comment]
Controller untuk Web dan Admin tidak boleh disatukan dlam satu Controller, 
saat ini disatukan di "Dokumen_sekretariat.php", seharusnya dipisah :

ADMIN
Controller : /Controller/Dokumen_sekretariat_admin.php (class Dokumen_sekretariat_admin extends Admin_Controller)
Model : /Model/Web_dokumen_model.php
Views : /Views/dokumen/*.php

- Di file /Controller/Dokumen_sekretariat_admin.php, semua kalimat "dokumen_sekretariat" diganti menjadi "dokumen_sekretariat_admin"
- Di semua file /views/dokumen/*.php, semua kalimat "dokumen_sekretariat" diganti menjadi "dokumen_sekretariat_admin"

WEB
Controller : /Controller/Dokumen_sekretariat_web.php (class Dokumen_sekretariat_web extends Web_Controller)
Model : /Model/Web_dokumen_model.php
Views : views/peraturan_desa/peraturan.php

- Di file Dokumen_sekretariat_web.php, semua kalimat "dokumen_sekretariat" diganti menjadi "dokumen_sekretariat_web"
- Di file /Views/peraturan_desa/peraturan.php , semua kalimat "dokumen_sekretariat" diganti menjadi "dokumen_sekretariat_web"

Di table Setting_modul ubah URL dari "dokumen_sekretariat/peraturan_desa" menjadi "dokumen_sekretariat_admin/peraturan_desa"

**Comment by ekasatriabahari** [comment]
sudah dikerjakan dan dikirim pada PR https://github.com/OpenSID/OpenSID/pull/2364
