### ISSUE TITLE
Auto Installer Online SID

### ISSUE THREAD

**Issue by Evostaff** [OpenSID/OpenSID#236]
Kalo di buatkan auto installernya seperti open soure CMS lainnya.. misal wordpress, joomla dan lainnya.. sepertinya akan lebih efektif dan simple... terima kasih

**Comment by telo99** [comment]
Setuju, mungkin bisa mencontoh yang branch sid 3.10.

Untuk yang update (sudah pernah terpasang opensid versi sebelumnya), mungkin bisa melalui proses:
1. hapus semua file. upload file² opensid terbaru.
2. install menggunakan installer, hanya perlu mengisi config database.
3. installer mendeteksi apakah pernah terpasang opensid sebelumnya dengan memeriksa database yang sudah ada. jika ada perubahan database, installer juga yang melakukannya.

Note: Jika ada proses hapus semua file, ada kemungkinan file galeri dan dokumen ikut terhapus. akan lebih baik jika dibuatkan folder "upload" di root folder (semua file dari pengguna disimpan di folder ini), jadi nantinya prosesnya hapus semua file kecuali folder upload

**Comment by eddieridwan** [comment]
Gunakan tool kit gratis/open source, seperti http://www.jrsoftware.org/isinfo.php.

**Comment by ghostcall** [comment]
@eddieridwan saya setuju pakai innosetup, kebetulan saya pernah pakai untuk buat installer web offline.

**Comment by ghostcall** [comment]
; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "OpenSid"
#define MyAppVersion "2.8"
#define MyAppPublisher "Combine Resource Institution"
#define MyAppURL "www.lumbungkomunitas.net"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{FCCF5BB8-5EF0-4585-8E1F-E729502D1F4E}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName=c:\{#MyAppName}
DisableProgramGroupPage=yes
LicenseFile=D:\packing opensid\opensid\htdocs\LICENSE
OutputBaseFilename=setup_opensid_2.8
SetupIconFile=D:\packing opensid\favicon.ico
Compression=lzma
SolidCompression=yes
PrivilegesRequired=admin
AlwaysRestart=No
UninstallDisplayName=OpenSid
UninstallRestartComputer=True

[Languages]
Name: "indonesian"; MessagesFile: "D:\packing opensid\Indonesian.isl";

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "D:\packing opensid\opensid\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{commondesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppName}.url"; Tasks: desktopicon; IconFilename: "{app}\img\opensid.ico"; 
Name: "{group}\Opensid"; Filename: "{app}\{#MyAppName}.url"; IconFilename: "{app}\img\opensid.ico";
Name: "{group}\{cm:UninstallProgram,{#MyAppName}}"; Filename: "{uninstallexe}"; IconFilename: "{app}\img\recycle.ico";

[Run]
Filename: "{app}\apache\apache_installservice.bat"; Parameters: "install"; Flags: runhidden
Filename: "{app}\mysql\mysql_installservice.bat"; Parameters: "install"; Flags: runhidden

[UninstallRun]
Filename: "{app}\apache\apache_uninstallservice.bat"; Parameters: "install"; Flags: runhidden
Filename: "{app}\mysql\mysql_uninstallservice.bat"; Parameters: "install"; Flags: runhidden

[UninstallDelete]
Type:files; Name: "{app}"
[INI]
Filename: "{app}\{#MyAppName}.url"; Section: "InternetShortcut"; Key: "URL"; String: "http://localhost/"

**Comment by ghostcall** [comment]
[script installer opensid.zip](https://github.com/OpenSID/OpenSID/files/1679829/script.installer.opensid.zip)

**Comment by ghostcall** [comment]
@eddieridwan ok.

**Comment by eddieridwan** [comment]
@ghostcall : saya ubah sedikit sesuai dengan folder laptop saya. Hampir jalan. Tapi nyangkut waktu di akhir 'run', tidak bisa menyelesaikan install. Kenapa, ya? Aplikasinya jalan, walaupun Mysql tidak otomatis hidup. Bisa coba lihat dan betulkan?

[script-installer-opensid-2.9.zip](https://github.com/OpenSID/OpenSID/files/1689691/script-installer-opensid-2.9.zip)

**Comment by eddieridwan** [comment]
@ghostcall: Hasilnya cukup besar: lebih dari 132Mb. Yang saya lakukan: 
1. Siapkan packing-opensid
- install XAMPP ke folder _opensid_; 
- install OpenSID dengan contoh data awal
- matikan Apache, MySQL dan control panel XAMPP
- salin seluruh folder _opensid_ ke folder _packing-opensid_ 
2. Build innosetup

Apakah proses ini sudah benar? Apa yang bisa dilakukan untuk memperkecil file installernya? File2 apa saja yang bisa dihapus dari bawaan XAMPP?

**Comment by ghostcall** [comment]
@eddieridwan tidak semua isi xampp di ambil, kita hanya butuh folder apache mysql php htdocs

**Comment by ghostcall** [comment]
@eddieridwan  kalau untuk testing coba ini saja perintahnya supaya bisa dilihat error nya, kita hilangkan script Flags: runhidden
[Run]
Filename: "{app}\apache\apache_installservice.bat"; Parameters: "install"; 
Filename: "{app}\mysql\mysql_installservice.bat"; Parameters: "install"; 

[UninstallRun]
Filename: "{app}\apache\apache_uninstallservice.bat"; Parameters: "install"; 
Filename: "{app}\mysql\mysql_uninstallservice.bat"; Parameters: "install";

**Comment by ghostcall** [comment]
https://drive.google.com/open?id=16L1vIe2ANdAVt9gGkuvuUI0pFSCdU6eG

**Comment by afa28** [comment]
Untuk script installer alur kerjanya mengikuti wordpress sdah disediakan di repo OpenSID, silahkan bantu kembangkan.
