### ISSUE TITLE
[jdih] Tampilan filter di tema hadakewa perlu dirapikan

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#2360]
### Bagaimana alurnya sampai muncul masalah?
1. Pilih tema hadakewa
2. Tampilkan halaman peraturan desa
3. Perhatikan tampilan peraturan desa

### Seperti apa yang diharapkan?
Tampilan peraturan desa terlihat rapi

### Apa yang terjadi?
Tampilan filter tidak rapi -- tidak rata
![filter-tidak-rapi](https://user-images.githubusercontent.com/249563/66392415-881b0700-ea1b-11e9-8361-ef9fc0e38d2a.jpg)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | jdih
| Versi PHP        | 
| System operasi   |

**Comment by ekasatriabahari** [comment]
sudah dikerjakan dan dikirim pada PR https://github.com/OpenSID/OpenSID/pull/2364
