### ISSUE TITLE
Grafik data statistik di web tidak tampil dengan semestinya

### ISSUE THREAD

**Issue by dikisiswanto** [OpenSID/OpenSID#2362]
### Bagaimana alurnya sampai muncul masalah?
1. Buka salah satu menu statistik di web yang menerapkan tema default
2. Lihat pada bagian grafik data

### Seperti apa yang diharapkan?
Grafik dapat tampil dengan semestinya.

### Apa yang terjadi?
Grafik tidak tampil karena ada dua versi jquery yang berbeda dalam satu laman. Jquery yang dimuat terakhir tidak kompatibel dengan plugin chartJS
![image](https://user-images.githubusercontent.com/22239074/66447663-90a62880-ea81-11e9-9f2a-a1d645fc5328.png)
![image](https://user-images.githubusercontent.com/22239074/66447685-a4ea2580-ea81-11e9-97c6-9af55f9844ce.png)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19.10-pasca
| Versi PHP        | 7.2
| System operasi   | Windows 10

**Comment by MUHAMMADRANGSEL** [comment]
Tenyata bukan di saya saja

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR #2363
