### ISSUE TITLE
[jdih] Hapus pilihan 'dokumen umum' dan ganti 'dokumen' menjadi 'peraturan'

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#2366]
### Bagaimana alurnya sampai muncul masalah?
1. Buka halaman peraturan desa di web
2. Perhatikan tampilan dan pilihan filter

### Seperti apa yang diharapkan?
Error di halaman2 berikut telah diperbaiki.

![peraturan-1](https://user-images.githubusercontent.com/249563/66474706-8d408a80-eadd-11e9-825d-437f21c4360b.jpg)
![peraturan-2](https://user-images.githubusercontent.com/249563/66474707-8d408a80-eadd-11e9-89cb-5a64cc30df95.jpg)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | jdih
| Versi PHP        | 
| System operasi   |

**Comment by ekasatriabahari** [comment]
sudah dikerjakan
