### ISSUE TITLE
[jdih] Halaman Admin Web > Dokumen terpengaruh Peraturan Desa

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#2367]
### Bagaimana alurnya sampai muncul masalah?
1. Buka _Sekretariat > Peraturan Desa > SK Kades_
2. Buka _Admin Web > Dokumen_
3. Perhatikan tampilan

### Seperti apa yang diharapkan?
Perubahan yg dilakukan untuk `Peraturan Desa` telah berdampak pada menu lain yg juga menggunakan tabel `dokumen` dan `donjo-app/models/Web_dokumen_model.php`.

Karena perubahan yg dilakukan untuk `Peraturan Desa`, sekarang halaman di menu _Admin Web > Dokumen_ salah.
![error-dokumen](https://user-images.githubusercontent.com/249563/66524410-243d2f00-eb3e-11e9-9ed7-60257c10a4f8.jpg)

Seharusnya tampilan di halaman _Admin Web > Dokumen_ adalah sebagai berikut:
![error-dokumen-2](https://user-images.githubusercontent.com/249563/66524397-1c7d8a80-eb3e-11e9-8b8b-53042d671834.jpg)

### Informasi tambahan 
Untuk melihat seperti apa _Admin Web > Dokumen_ aslinya di branch `master`, silakan buka demo.opensid.my.id.

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | jdih
| Versi PHP        | 
| System operasi   |

**Comment by ekasatriabahari** [comment]
sudah dikerjakan
