### ISSUE TITLE
Tambah kolom untuk foto rumah di modul Rumah Tangga

### ISSUE THREAD

**Issue by benioke** [OpenSID/OpenSID#2369]
Bagaimana alurnya sampai muncul masalah?
Belum ada nya kolom foto rumah di modul rumah tangga

Seperti apa yang diharapkan?
Seharus nya di tambah kolom foto rumah sesudah no rumah tangga sehingga operator bisa melihat no rumah tangga sekaligus detail foto rumah nya.walaupun bisa di lakukan di modul kependudukan dengan upload foto dokumen.tapi akan lebih detail foto rumah nya ada di modul rumah tangga.selain melihat no rumah tangga sekaligus foto rumah nya.

Apa yang terjadi?
Saat ini hanya ada no rumah tangga tanpa di lengkapi foto rumah.

 Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19.10 pasca
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
Duplicate issue #3373
