### ISSUE TITLE
Opensid Versi Bhabinkamtibmas

### ISSUE THREAD

**Issue by omdiky** [OpenSID/OpenSID#2372]
### Seperti apa yang diharapkan?
Saya berharap ada Opensid versi Bhabinkamtibmas, karena Bhabinkamtibmas juga sama melakukan pendataan warga, dan melaporkan segala kegiatan yang ada di desa.
Mohon maaf ini hanya harapan saya selaku bhabinkamtibmas, karena saya senang dengan konten yang sudah ada pada opensid. Mudah-mudahan ada versi bhabinkamtibmasnya. Terima kasih

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by balongbesuk** [comment]
kalau desa bapak sudah menerapkan opensid, bapak tinggal minta akun / akses ke desa saja

**Comment by sukrimalendra** [comment]
ini usulan yang bagus, tapi Opensid versi Bhabinkamtibmas yang bagaimana maksudnya bapak?
Bagaimana bentuk pendataanya?
data apa saja yang diperlukan?
Bentuk laporannya bagaimana?
harus jelas pak agar bisa dimengerti oleh programer opensid. terimakasih.

**Comment by omdiky** [comment]
Terimaksih bapak atas tanggapan bapak.
Saya rasa bapak kalau untuk pendataan sudah bagus dengan konten yang sudah
ada pada opensid.
Terkait pelaporannya, sama halnya surat menyurat desa pak.

Namun formatnya saja mungkin khusun pelaporan bhabinkamtibmas, sehingga
bhabinkamtibmas bisa melakukan laporan melalui web atau aplikasi tsb.
Intinya untuk konten yang ada pada opensid sudah lengkap untuk kegiatan
bhabinkamtibmas, dikarenakan info yang ada di desa sudah ada pada opensid.

Hanya terkait seperti identitas desa pada opensid, harapan saya menjadi
identitas aplikasi bhabinkamtibmas, perangkat desa menjadi data
bhabinkamtibmas itu sendiri.

Dan mohon maaf jika opensid di fungsikan untuk bhabinkamtibmas ada 1
kekurangannya pak, yaitu tidak bisa menambah desa. Sementara
bhabinkamtibmas ada yang membina desa 3 s/d 4 desa sendirian.

Jadi jika bhabinkamtibmas mendata penduduk, hanya 1 desa saja.

Pada tanggal Sen, 14 Okt 2019 15:59, Muh Sukri Malendra <
notifications@github.com> menulis:

**Comment by omdiky** [comment]
Saya sering menyarankan mereka, untuk menggunakan opensid. Namun pak khusus
di desa2 yang saya bina mereka cenderung kepada prodeskel.
Sudah beberapa sekertaris desa yang saya bantu instalkan opensid, namun
saya kurang tahu mereka malah cenderung pada prodeskel.

Pada tanggal Jum, 11 Okt 2019 09:32, balongbesuk <notifications@github.com>
menulis:

**Comment by afa28** [comment]
Jika ingin menggunakan core OpenSID diluar penggunaan di desa/kelurahan bisa disesuaikan sendiri dgn melakukan modifikasi source sesuai kebutuhan anda.
