### ISSUE TITLE
Status Kawin Tidak Tercatat berganti Kawin Belum Trecatat

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#2383]
### Bagaimana alurnya sampai muncul masalah?
lihat Kartu Keluarga Penduduk > lihat Status Perkawinan Penduduk

### Seperti apa yang diharapkan?
Status Kawin Tidak Tercatat berubah menjadi Kawin Belum tercatat

### Apa yang terjadi?
update status perkawinan

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

![WhatsApp Image 2019-10-14 at 09 14 11](https://user-images.githubusercontent.com/35319600/66726581-68913d80-ee64-11e9-8988-a77c843d33c6.jpeg)

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR #2386
