### ISSUE TITLE
[rbac] Sesuaikan tampilan dan fitur halaman pengguna seperti sebelumnya

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#2384]
### Bagaimana alurnya sampai muncul masalah?
1. Buka halaman _Pengaturan > Pengguna_
2. Perhatikan tampilan dan fitur yg ada

### Seperti apa yang diharapkan?
Tampilan dan fitur serupa dengan yang ada pada rilis sebelum rbac.
![demo-user](https://user-images.githubusercontent.com/249563/66727082-b750ce80-ee88-11e9-8585-52aafc1bad7a.jpg)

### Apa yang terjadi?
Tampilan tidak serasi dengan aplikasi dan banyak fitur yg tidak tersedia, antara lain:

- filter
- cari
- paginasi
- urut kolom
- tombol aksi tidak dikumpulkan di kolom aksi di sebelah kiri 

![rbac-users](https://user-images.githubusercontent.com/249563/66727098-c33c9080-ee88-11e9-8511-a483836cbb7a.jpg)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | rbac
| Versi PHP        | 
| System operasi   |

**Comment by fusionid** [comment]
Done. Perbaikan sudah dicommit

**Comment by afa28** [comment]
Sudah di `rilis-dev`
