### ISSUE TITLE
[rbac] Sesuaikan tampilan halaman Pengaturan Group sesuai pola halaman lainnya

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#2385]
### Bagaimana alurnya sampai muncul masalah?
1. Buka halaman _Pengaturan > Group / Hak Akses_
2. Perhatikan tampilan dan fitur yg ada

### Seperti apa yang diharapkan?
Tampilan dan fitur serupa dengan yang ada pada halaman OpenSID lainnya.
![demo-user](https://user-images.githubusercontent.com/249563/66727082-b750ce80-ee88-11e9-8585-52aafc1bad7a.jpg)

### Apa yang terjadi?
Tampilan tidak serasi dengan aplikasi dan banyak fitur yg tidak tersedia, antara lain:

- filter
- cari
- paginasi
- urut kolom
- tombol aksi tidak dikumpulkan di kolom aksi di sebelah kiri 

![group-rbac](https://user-images.githubusercontent.com/249563/66727989-211fa700-ee8e-11e9-9809-5f5478e8e9b3.jpg)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | rbac
| Versi PHP        | 
| System operasi   |

**Comment by fusionid** [comment]
Done. Perbaikan sudah dicommit

**Comment by afa28** [comment]
Sudah di `rilis-dev`
