### ISSUE TITLE
Format Laporan Administrasi di Opensid Sesuai dengan Lampiran Permendagri No 47 Tahun 2016 Tentang Administrasi Pemerintah Desa

### ISSUE THREAD

**Issue by sukrimalendra** [OpenSID/OpenSID#2388]
### Bagaimana alurnya sampai muncul masalah?
Testing Opensid

### Seperti apa yang diharapkan?
Harapan saya semua laporan administrasi yang ada di Opensid sesuai dengan Lampiran Permendagri No 47 Tahun 2016 Tentang Administrasi Pemerintah Desa. agar format laporannya dapat diterima disemua daerah. terimakasih.
[Permendagri_No.47_TH_2016_Lampiran_Administrasi-Pemerintahan-Desa.pdf](https://github.com/OpenSID/OpenSID/files/3723728/Permendagri_No.47_TH_2016_Lampiran_Administrasi-Pemerintahan-Desa.pdf)

### Apa yang terjadi?
Sebagian sudah sesuai. yang kurang sesuai ada di laporan :
1. Perdes
2. SK Kades
3. Agenda Surat Masuk dan Keluar
4. Dll.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by mizwaruddin** [comment]
@afa28 sama dengan issue Buku Administrasi Desa
