### ISSUE TITLE
[jdih] Lengkapi wiki dengan panduan Peraturan Desa

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#2389]
### Bagaimana alurnya sampai muncul masalah?
1. Cari petunjuk penggunaan fitur Peraturan Desa di wiki

### Seperti apa yang diharapkan?
Ada petunjuk lengkap mengenai penggunaan fitur Peraturan Desa

### Apa yang terjadi?
Belum ada

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | jdih
| Versi PHP        | 
| System operasi   |

**Comment by ekasatriabahari** [comment]
sudah dikerjakan di https://github.com/OpenSID/OpenSID/wiki/Peraturan-Desa
