### ISSUE TITLE
[jdih] data hilang ketika tombil sortir d tekan

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#2394]
### Bagaimana alurnya sampai muncul masalah?
tekan salah satu tombol sortir lihat hasil

### Seperti apa yang diharapkan?
berjalan seperti semestinya

### Apa yang terjadi?
data peraturan hilang

### Informasi tambahan 

![sedang_1569983427_pilkades](https://user-images.githubusercontent.com/35319600/66793621-71e3de00-ef28-11e9-9272-238a550d8435.jpeg)

**Comment by ekasatriabahari** [comment]
sudah dikerjakan pada PR #2393

**Comment by eddieridwan** [comment]
Sudah dikerjakan dengan menghapus fitur sortir kolom. Sepertinya saat ini belum perlu, karena sudah ada fitur pilah/filter.
