### ISSUE TITLE
[keuangan] Sesuaikan database keuangan dengan data Siskeudes 2019

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#2398]
### Bagaimana alurnya sampai muncul masalah?
1. Coba impor hasil konversi database Siskeudes 2019

### Seperti apa yang diharapkan?
Impor data Siskeudes 2019 berhasil

### Apa yang terjadi?
Impor tidak berhasil, karena error struktur datanya berbeda dengan tahun2 sebelumnya

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | v19.10
| Versi PHP        | 
| System operasi   |

**Comment by pandigresik** [comment]
Mungkin bisa di cek PR https://github.com/OpenSID/OpenSID/pull/2396

**Comment by eddieridwan** [comment]
Contoh data Siskeudes 2019 dari @pandigresik 
[siskeudes_2019.zip](https://github.com/OpenSID/OpenSID/files/3894518/siskeudes_2019.zip)

**Comment by eddieridwan** [comment]
Fitur ini diterapkan sebagai fitur 'pra-bayar'.

**Comment by eddieridwan** [comment]
Fitur ini sudah digabung ke rilis umum.
