### ISSUE TITLE
Lampiran surat tidak ikut tercetak di surat yang menggunakan lampiran.

### ISSUE THREAD

**Issue by rullydamara** [OpenSID/OpenSID#2399]
### Bagaimana alurnya sampai muncul masalah?
Lampiran surat tidak ikut tercetak/ekspor doc. Hanya suratnya saja. Sebagai contoh untuk surat permohonan perubahan kartu keluarga. Untuk lampiran F-1.16 maupun F-1.01 nya tidak tercetak.

### Seperti apa yang diharapkan?
Lampiran surat tercetak.

### Informasi tambahan 
![Screenshot_2019-10-16-11-57-27-99](https://user-images.githubusercontent.com/45301948/66889351-433f3380-f00c-11e9-90eb-b586104a6689.png)
![Screenshot_2019-10-16-11-57-57-18_c37d74246d9c81aa0bb824b57eaf7062](https://user-images.githubusercontent.com/45301948/66889367-518d4f80-f00c-11e9-91bd-919aef789f24.png)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by balongbesuk** [comment]
![sedang_1569983427_pilkades](https://user-images.githubusercontent.com/35319600/66890065-e729de80-f00e-11e9-96f8-58d070a28ede.jpeg)

**Comment by rullydamara** [comment]
Jadi harus masuk menu arsip layanan dulu ya?
Apakah tidak bisa di lakukan pada halaman pembuatan suratnya. Misalnya di samping tombol ekspor doc, atau bagaimana bagusnya?.

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR  #2608
