### ISSUE TITLE
Link Menu Data Desa

### ISSUE THREAD

**Issue by R4HMAT** [OpenSID/OpenSID#2400]
###Bagaimana alurnya sampai muncul masalah?
untuk menu Data Desa-Data Kelompok Umur- yang muncul Tabel Data Demografi Berdasar Pendidikan
![data1](https://user-images.githubusercontent.com/43318683/66899140-ad63d280-f024-11e9-94ac-ab4be7b3ec47.png)

![data2](https://user-images.githubusercontent.com/43318683/66899197-c7051a00-f024-11e9-97c5-ffed432aa350.png)

###Seperti apa yang diharapkan?
untuk link pada menu desa bagian data kelompok umur supaya yang muncul sesuai dengan sub menu data kelompok umur

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 9.10 Pasca
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
@R4HMAT itu salah isi di website demo saja. Isi masing2 menu status ditentukan masing2 desa. Lihat panduan cara mengatur menu statis : https://github.com/OpenSID/OpenSID/wiki/Peragaan-Menu-Statistik.

Ok, issue ini ditutup karena bukan sesuatu untuk programmer.
