### ISSUE TITLE
[Bug] Bug pada library ketika teks berjalan di non aktifkan

### ISSUE THREAD

**Issue by hirudi** [OpenSID/OpenSID#2401]
![ss](https://user-images.githubusercontent.com/4936934/66924289-86bd9000-f054-11e9-9c4b-5e5e12c9864f.jpg)

### Bagaimana alurnya sampai muncul masalah?
Ketika teks berjalan di non aktifkan terjadi error tersebut.. Slider gambar utama tidak jalan.. Widget aparatur desa slidernya tidak jalan..

### Seperti apa yang diharapkan?
Tidak terjadi error ketika menonaktifkan teks berjalan

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19.10
| Versi PHP        | 7.2
| System operasi   | Ubuntu

**Comment by hirudi** [comment]
Terjadi di tema hadakewa, nantra, cosmos dan tema custom yang lain... namun di tema default tidak terjadi error tersebut

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR #2415

**Comment by hirudi** [comment]
Apakah sudah diterapkan di web demo/beta? Karena masih terjadi error tersebut
