### ISSUE TITLE
[Bug] Tidak bisa tambah kategori kelompok

### ISSUE THREAD

**Issue by sugiantoe** [OpenSID/OpenSID#2409]
### Bagaimana alurnya sampai muncul masalah?
Klik menu Kependudukan > Kelompok > Kelola kategori kelompok

![image](https://user-images.githubusercontent.com/28652833/67064107-73650e80-f193-11e9-834a-6789f45878bf.png)

### Seperti apa yang diharapkan?
menambah kategori kelompok

### Apa yang terjadi?
Kategori tidak bisa ditambah, langsung kembali ke halaman Home
![image](https://user-images.githubusercontent.com/28652833/67063977-dbffbb80-f192-11e9-85c3-a82c5201a152.png)

### Informasi tambahan 

hal ini tidak terjadi pada versiVersi 19.09

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | Versi 19.10 dan Versi 19.10 pasca
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR #2417
