### ISSUE TITLE
menampilkan data bantuan per penduduk

### ISSUE THREAD

**Issue by sugiantoe** [OpenSID/OpenSID#2410]
### Bagaimana alurnya sampai muncul masalah?
Klik menu Kependudukan > Keluarga > Ubah data 

![image](https://user-images.githubusercontent.com/28652833/67064293-32b9c500-f194-11e9-818b-b8f86d6442ab.png)

muncul pop up yang menampilkan data Peserta program bantuan KELUARGA. data bantuan juga bisa dengan mudah diubah.

namun porgram bantuan dengan sasaran program PERORANGAN kita tidak bisa melihat/merubah secara langsung dari menu penduduk.

![image](https://user-images.githubusercontent.com/28652833/67064553-27b36480-f195-11e9-9272-5c4cd2edf7a0.png)

### Seperti apa yang diharapkan?

agar menu penduduk juga bisa menampilkan data program bantuan apa saja yang didapatkan nya (perpenduduk)

### Apa yang terjadi?

memudahkan melihat kepesertaan program bantuan per penduduk

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | Versi 19.10-pasca
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Daftar program bantuan yg diterima penduduk ditampilkan di halaman Biodata Penduduk.
Sdh dicommit ke `master` melalui PR #3251
