### ISSUE TITLE
[menu analisis] nilai klaisifikasi tidak bisa lebih dari nilai 999,99

### ISSUE THREAD

**Issue by WAHYUDIK** [OpenSID/OpenSID#2414]
### Bagaimana alurnya sampai muncul masalah?
ketika kita ingin merubah/menambah nilai klasifikasi  lebih dari 999,99 tidak bisa
![image](https://user-images.githubusercontent.com/31026980/67074019-7d4a3a00-f1b2-11e9-825c-de983f2ec3fc.png)

### Seperti apa yang diharapkan?
untuk nilai klasifikasi bisa lebih dari 999,99

### Apa yang terjadi?

saat ini masih maksimal 999,999
### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by uncu29** [comment]
lebihnya brpa pak? 
999.999

**Comment by WAHYUDIK** [comment]
seperti ini pak 
![image](https://user-images.githubusercontent.com/31026980/68572376-ce8ad800-0497-11ea-8a51-63c06226d50e.png)

**Comment by uncu29** [comment]
![Sistem Informasi Desa Desa Hibrida Jaya - Analisis Klasifikasi - Google Chrome 11_11_2019 19 43 18](https://user-images.githubusercontent.com/51182125/68588260-9b5a4000-04bb-11ea-9125-8d6f12f791b9.png)
seperti itu

**Comment by WAHYUDIK** [comment]
iya betuul seperti itu pak...untuk contoh data importnya
https://drive.google.com/file/d/1KPhRc1cKMs04VshDS0YQ6NdntH_FbUCQ/view?usp=sharing

**Comment by eddieridwan** [comment]
Telah dicommit ke master melalui PR #2471
