### ISSUE TITLE
Error Konfigurasi Database OpenSID versi 19.10

### ISSUE THREAD

**Issue by andriawan** [OpenSID/OpenSID#2418]
Ketika saya akan memulai pengembangan OpenSID, saya mengalamai kendala error 500. Kondisi terakhir saya menggunakan versi terbaru 19.10 dengan database awal _contoh_data_awal_20191001.sql_. Setelah saya liat log saya mendapati ada error seperti gambar berikut. Mohon arahan mungkin ada langkah-langkah yang saya lewati.

![image](https://user-images.githubusercontent.com/13099373/67153585-3ffebd00-f316-11e9-8e29-e9c81407a532.png)

dan setelah saya cek memang tabel tersebut tidak ada dalam database awal yang telah saya import

### Bagaimana alurnya sampai muncul masalah?
- ketika saya mencoba membuka halaman awal saya mendapati error 500
![image](https://user-images.githubusercontent.com/13099373/67153594-7f2d0e00-f316-11e9-8c43-aba5c6480e14.png)

### Seperti apa yang diharapkan?
Halaman awal dapat diakses dan database terkonfigurasi dengan benar

### Apa yang terjadi?
Saya mendapati error 500

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19.10
| Versi PHP        | 5.6
| System operasi   | Windows 10

**Comment by ai-skematik** [comment]
Apakah menggunakan versi 19.10-pasca?

**Comment by andriawan** [comment]
Saya ambil dari master branch. Bagaimana cara mengidentifikasi bahwa itu pasca atau bukan?

**Comment by ai-skematik** [comment]
Buat postingan di grup facebook, sepertinya yang bung alami tidak berhasil menginstal opensid,,

**Comment by eddieridwan** [comment]
@andriawan Di panduan dijelaskan bahwa anda perlu melakukan _Pengaturan > Database > Migrasi DB_ untuk menyesuaikan struktur database apabila menggunakan versi dari branch _master_ (pra_rilis) dan bukan rilis resmi.

Ok, issue ini akan ditutup karena bukan bug untuk programmer. Kalau panduan perlu diperjelas, silakan lengkapi menggunakan petunjuk di https://github.com/OpenSID/OpenSID/wiki/Mengembangkan-Panduan-OpenSID.
