### ISSUE TITLE
[peta] Ubah lokasi peta untuk RW/RT error

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#2419]
### Bagaimana alurnya sampai muncul masalah?
1. Buka Info Desa > Wilayah Administratif > Dusun > RW > Kantor RW
2. Perhatikan tampilan dan console javascript di browser

### Seperti apa yang diharapkan?
Peta tampil dan tidak ada error.

### Apa yang terjadi?
![kantor-rw](https://user-images.githubusercontent.com/249563/67153878-0b522c00-f33d-11e9-9719-fd9c06c4f72d.jpg)

### Informasi tambahan 
Masalah ini juga terjadi untuk Kantor RT, Wilayah Dusun dan Wilayah RT

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | peta
| Versi PHP        | 
| System operasi   |

**Comment by fusionid** [comment]
Ini bukan error tapi karena kordinat/posisi kantor datasnya belum diisi (posisi kantor dusun TIGA desa Rejsari kosong).  Ini disesuaikan dengan https://github.com/OpenSID/OpenSID/pull/2403#issuecomment-543552611  -> Jika posisi wilayah belum ada maka akan refer ke posisi wilayah tingkat atasnya, mis.posisi wilayah RT jika belum ada akan refer ke posisi wilayah Dusun.

**Comment by eddieridwan** [comment]
@fusionid sebaiknya digunakan lokasi default yg sudah ada untuk lokasi kantor desa. Jadi tidak membingungkan bagi pengguna.

**Comment by eddieridwan** [comment]
![lokasi-default](https://user-images.githubusercontent.com/249563/67154167-0abc9400-f343-11e9-98e7-ed3dc8568944.jpg)

**Comment by fusionid** [comment]
Pemakaian lokasi default malah membuat pengguna harus narik2 peta lebih banyak karena mencari lokasi desanya yg jauh dari lokasi default, kalau lokasi desanya dekat lokasi default mungkin tidak terlalu menjadi masalah karena mengenal daerah itu. 
Jika tidak salah hal ini pernah ada di salah satu issue.

**Comment by eddieridwan** [comment]
Urutan idealnya memang:
1. Ubah lokasi kantor/wilayah desa default ke lokasi sebenarnya
2. Ubah lokasi kantor/wilayah dusun menggunakan default lokasi desa
3. Ubah lokasi kantor/wilayah rw menggunakan default lokasi dusun
4. Ubah lokasi kantor/wilayah rt menggunakan default lokasi rw

Sebagai strategi alternatif, pada waktu mengubah lokasi kantor/wilayah X, kalau kantor/wilayah atasnya belum ada, lebih baik tampilkan pesan yg menjelaskan masalah (yaitu pengguna perlu mengubah dulu lokasi wilayah di atatsnya). Yaitu tidak menampilkan popup kosong dan juga tidak ada error di console.

**Comment by fusionid** [comment]
Done. https://github.com/OpenSID/OpenSID/commit/39f024b0fee391c88732f0b553fac844c84f6755

**Comment by eddieridwan** [comment]
Masih error pada waktu
