### ISSUE TITLE
[peta] Sederhanakan script kantor/wilayah dusun/rw/rt

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#2420]
### Bagaimana alurnya sampai muncul masalah?
1. Perhatikan file untuk lokasi kantor dusun/rw/rt
2. Perhatikan file unuk wilayah dusun/rw/rt

### Seperti apa yang diharapkan?
File digabung supaya lebih mudah diperiksa dan diperbaiki.

![gabung-file](https://user-images.githubusercontent.com/249563/67154291-7acc1980-f345-11e9-864a-529f05e5a804.jpg)

### Apa yang terjadi?
Copy/paste, tidak jauh beda.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | peta
| Versi PHP        | 
| System operasi   |

**Comment by fusionid** [comment]
Kelihatan sama tapi parameternya jauh berbeda, Malah dengan di split lebih mudah diperiksa dan diperbaiki.
