### ISSUE TITLE
[peta] Sesuaikan script dengan aturan penulisan script

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#2421]
### Bagaimana alurnya sampai muncul masalah?
1. Buka file yg diubah untuk pekerjaan lokasi kantor/wilayah dusun/rw/rt dengan text editor
2. Perhatikan penulisan script

### Seperti apa yang diharapkan?
Sesuai dengan aturan penulisan script di https://github.com/OpenSID/OpenSID/wiki/Aturan-Penulisan-Script

### Apa yang terjadi?
Masih ada yg belum sesuai.
![aturan-script](https://user-images.githubusercontent.com/249563/67154811-e74b1680-f34d-11e9-8b13-5ea207503784.jpg)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | peta
| Versi PHP        | 
| System operasi   |

**Comment by fusionid** [comment]
Siap. Nanti dirapihkan

**Comment by eddieridwan** [comment]
@fusionid mohon perbaiki penulisan script di SEMUA file yg anda ubah. Gambar berikut hanya sebagian file yg anda ubah. Terima kasih.

![semua-file-peta](https://user-images.githubusercontent.com/249563/67347019-92491380-f58c-11e9-8848-cb659fd4879c.jpg)

**Comment by eddieridwan** [comment]
Sudah dikerjakan
