### ISSUE TITLE
Insert Gambar di Artikel tidak Tampil pada URL Slug

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#2425]
### Bagaimana alurnya sampai muncul masalah?
Prakter buat artikel di http://demo.opensid.my.id dengan cara menyisipkan gambar pada artikel tersebut, seperti screenshot berikut:

![IMG_20191021_120525](https://user-images.githubusercontent.com/46939846/67178196-06a07d00-f3fc-11e9-84e8-340ef644e785.jpg)

Menyisipkan gambar pada sebuah paragraf atau sebuah baris di artikel, namun setelah di save gambar tersebut hanya muncul pada Link URL dengan menggunakan ID. Link suksesnya begini:
http://demo.opensid.my.id/index.php/first/artikel/100

![IMG_20191021_120549](https://user-images.githubusercontent.com/46939846/67178143-dce75600-f3fb-11e9-8370-9fb75538f89e.jpg)

### Seperti apa yang diharapkan?
Muncul gambar yang sudah diinsert pada artikel baik URL menggunakan ID maupun Slug

### Apa yang terjadi?
Saat buka artikel menggunakan URL Slug, gambar tidak tampil. 
Coba klik di sini:
http://demo.opensid.my.id/index.php/first/artikel/2019/10/21/coba-insert-image-di-artikel

![IMG_20191021_120540](https://user-images.githubusercontent.com/46939846/67178160-e96bae80-f3fb-11e9-8d1c-3e67dfbc5007.jpg)

Ingat:
yang dibahas adalah Insert Image saat Buat Artikel, BUKAN Insert saat Edit Artikel. 

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR #2472
