### ISSUE TITLE
Pemanggil NIK Dua Peran Berat Saat digunakan

### ISSUE THREAD

**Issue by kayangan** [OpenSID/OpenSID#2428]
Mohon Di Perbaiki Supaya Lebih Ringan Load NIK / Nama Pemohon Surat Terutama Pemanggilnya Dua Peran Warga Desa dan Warga Luar Desa Terutama bagi Kami Yang Data Penduduknya Dia atas 6000an Sangat Lambat sekali Memanggil Niknya kalau di surat keterangan lainnya Normal Berikut Contoh Suratnya :

Surat Pernyataan Jual Beli Tanah
https://drive.google.com/file/d/1-zXh9EB4JFc2b_MEFJ_ShWSMrgxRBI5m/view?usp=sharing

**Comment by balongbesuk** [comment]
apakah sudah menerapkan kembali ubahan dari issue #2161 

berlaku untuk semua ubahan kustom surat yang bapak buat,

**Comment by kayangan** [comment]
Maaf saya kurang ahli dalam koding itu surat yang saya buat saya copy dari
surat yang sudah ada, saya juga sudah mencoba menggunakan surat sporadik
yang ada di sistem disana juga menggunakan dua peran sama berat loadingnya
kecuali surat keterangan biasa itu ringan

Pada tanggal Sel, 22 Okt 2019 9:19 AM, balongbesuk <notifications@github.com>
menulis:

**Comment by kayangan** [comment]
Saya akan mencoba merubahnya lagi mudah2an bisa

Pada tanggal Sel, 22 Okt 2019 9:57 AM, Desa Kayangan <
genemkayangan@gmail.com> menulis:

**Comment by kayangan** [comment]
Wah saya mentok ga bisa untuk pemohonnya warga desa dan non warga  masih berat cuma pemanggil saksi-saksi saja yang sudah ringan... Untuk master "balongbesuk" silahkan dilanjut saya nyerah

**Comment by kayangan** [comment]
Oke sudah ketemu solusinya
