### ISSUE TITLE
Mal Function Tombol KIRIM dan RESET Laporan Pada Layanan Mandiri

### ISSUE THREAD

**Issue by PWidodo** [OpenSID/OpenSID#2430]
### Bagaimana alurnya sampai muncul masalah?
Setelah saya coba untuk versi pra rilis terbaru kemarin, ternyata Tombol Kirim laporan tidak berfungsi sebagaimana mestinya, dan pada bagian system layanan mandiri tidak ada laporan yang masuk (blank)

### Seperti apa yang diharapkan?
Tampilan form lapor sudah sangat bagus, dan harap untuk diperbaiki kedua tombol tersebut.
![Tombol Kirim dan reset layanan Mandiri tidak berfungsi](https://user-images.githubusercontent.com/45189822/67265924-1e016800-f4d9-11e9-9abc-afacf5cd6f62.png)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by WAHYUDIK** [comment]
Saya coba update perhari ini. Dan mencobq kirim laporan di payanan mandiri sukses terkirim pak

**Comment by PWidodo** [comment]
Php 7.3.1 saya mas diki, tapi tak coba kemarin laporan tak terkirim. Ok
saya coba lagi nanti.

Pada tanggal Sel, 22 Okt 2019 5.53 PM, WAHYUDIK <notifications@github.com>
menulis:

**Comment by WAHYUDIK** [comment]
Essip lanjutkan.....

**Comment by uncu29** [comment]
Reset dan Kirim Succes 
![Sistem Informasi Desa Desa Hibrida JayaLayanan Mandiri - Google Chrome 23_10_2019 00 53 49](https://user-images.githubusercontent.com/51182125/67315196-4a949e80-f530-11e9-884a-9f23f3b05c02.png)

**Comment by eddieridwan** [comment]
Ok. Issue ini akan ditutup. Kalau ada bug yg perlu diperbaiki, silakan buka kembali.
