### ISSUE TITLE
[peta] Perbaiki breadcrumb supaya tidak berhimpitan

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#2431]
### Bagaimana alurnya sampai muncul masalah?
1. Buka Info Desa > Wilayah Administratif > Dusun > RW > RT
2. Ubah data suatu RT dan ubah lokasi Kantor RT atau Wilayah RT
3. Perhatikan judul dan breadcrumb

### Seperti apa yang diharapkan?
Judul dan breadcrumb tidak berhimpitan

### Apa yang terjadi?
Judul dan breadcrumb berhimpitan karena terlalu panjang
![kantor-rt](https://user-images.githubusercontent.com/249563/67345779-e56c9780-f587-11e9-863b-4efbd9e85d85.jpg)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | peta
| Versi PHP        | 
| System operasi   |

**Comment by fusionid** [comment]
Done. https://github.com/OpenSID/OpenSID/commit/6115e688e736dde003d65059b31350cb44befead
