### ISSUE TITLE
[peta] Seragamkan pesan sukses/error

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#2432]
### Bagaimana alurnya sampai muncul masalah?
1. Ubah lokasi/wilayah dusun/rw/rt
2. Simpan
3. Perhatikan tampilan pesan sukses/error

### Seperti apa yang diharapkan?
Seharusnya seragam dengan pesan sukses/error di bagian aplikasi lainnya.
![pesan-sukses-yg-ada](https://user-images.githubusercontent.com/249563/67345933-8c513380-f588-11e9-8731-6f138a9372eb.jpg)

### Apa yang terjadi?
Tampilan pesan sukses/error berbeda
![pesan-sukses-berbeda](https://user-images.githubusercontent.com/249563/67346159-86a81d80-f589-11e9-8cc9-22e4400db40d.jpg)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | peta
| Versi PHP        | 
| System operasi   |

**Comment by fusionid** [comment]
Done. https://github.com/OpenSID/OpenSID/commit/2cd81705e9bfd6c8d287cdd013e3037308333600
