### ISSUE TITLE
[peta] Tautan di breadcrumb form lokasi kantor/wilayah rt salah

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#2433]
### Bagaimana alurnya sampai muncul masalah?
1. Buka form ubah lokasi Kantor/Wilayah RT
2. Coba tautan di breadcrumb

### Seperti apa yang diharapkan?
Tautan mengarahkan ke halaman yg benar

### Apa yang terjadi?
Tautan salah
![breadcrumb-salah](https://user-images.githubusercontent.com/249563/67360058-a868cb00-f5b0-11e9-93f5-e58e3c5573c3.jpg)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | peta
| Versi PHP        | 
| System operasi   |

**Comment by fusionid** [comment]
Done. https://github.com/OpenSID/OpenSID/commit/3cab24e7e2d1a9d007bfc82b7a0aed97c9019b9c
