### ISSUE TITLE
[peta] Perubahan data dusun/rw/rt hilang 

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#2435]
### Bagaimana alurnya sampai muncul masalah?
1. Buka form untuk ubah data dusun/rw/rt
2. Lakukan perubahan data pada form tersebut, misalnya ubah kepala dusun/rw/rt. JANGAN klik tombol Simpan
3. Buka form untuk ubah lokasi kantor/wilayah dusun/rw/rt
4. Simpan
5. Klik tautan di breadcrumb untuk kembali ke form ubah data dusun/rw/rt

### Seperti apa yang diharapkan?
Perubahan data pada form ubah data dusun/rw/rt tidak hilang (walaupun belum disimpan).

### Apa yang terjadi?
Data di form ubah data dusun/rw/rt yg belum tersimpan hilang. Yaitu, hilang setelah klik 'Simpan' di langkah #3 di gambar berikut.

![ubah-data-dusun](https://user-images.githubusercontent.com/249563/67436513-4785d500-f63a-11e9-991f-019563cbfb28.jpg)
![simpan-lokasi](https://user-images.githubusercontent.com/249563/67436525-5076a680-f63a-11e9-8540-62ca12e1b237.jpg)

### Informasi tambahan 
Hal ini terjadi karena form ubah lokasi kantor/wilayah sekarang menggunakan form biasa, bukan modal dialog ajax seperti sebelumnya di Identitas Desa. Karena perubahan ini, penanganannya juga perlu diubah untuk menghindari masalah seperti di issue ini.

Satu opsi adalah dengan memindahkan tombol ubah lokasi kantor/wilayah dusun/rw/rt dari form ubah data dusun/rw/rt menjadi pilihan aksi di halaman daftar dusun/rw/rt, sbb:
![aksi-lokasi](https://user-images.githubusercontent.com/249563/67436735-dc88ce00-f63a-11e9-88e5-007f5e0960e3.jpg)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 
| Versi PHP        | 
| System operasi   |

**Comment by fusionid** [comment]
Done. Sudah diperbaiki.

**Comment by eddieridwan** [comment]
Bung @fusionid masalahnya belum diperbaiki. Apa yg anda perbaiki?

**Comment by eddieridwan** [comment]
Masalahnya timbul karena akan membingungkan pengguna. Tombol peta kantor/wilayah penampilannya seperti bagian dari form ubah data wilayah. Jadi pengguna tidak merasa perlu klik Simpan dulu sebelum membuka peta kantor/wilayah. Tapi kenyataannya adalah form berbeda sama sekali -- dan data isian yg belum disimpan akan hilang semua.

**Comment by fusionid** [comment]
Kalimat issue anda di PR @2436  "Perubahan data identitas desa hilang setelah ubah peta kantor/wilayah desa" yg membuat jadi misleading padahal pointnya "Perubahan data identitas desa hilang karena belum disimpan setelah ubah peta kantor/wilayah desa" tapi hikmah positipnya menemukan bug lain yg sudah diperbaiki di commit ini (menjawab pertanyaan "Apa yg anda perbaiki?") yaitu parameter yg dipakai di semua form adalah NAMA DUSUN bukan ID, sehingga jika ada nama dusun dengan 2 kata dengan spasi maka data akan hilang/error.

**Comment by fusionid** [comment]
Apakah menunya akan dikumpulkan dalam satu menu aksi seperti ini ?

![Screen Shot 10-24-19 at 08 04 PM](https://user-images.githubusercontent.com/10391199/67488513-26ed6780-f69a-11e9-98e7-744e6f782c06.PNG)

![Screen Shot 10-24-19 at 08 06 PM](https://user-images.githubusercontent.com/10391199/67488549-3076cf80-f69a-11e9-9f91-82aab4b355db.PNG)

**Comment by eddieridwan** [comment]
Saya kira yg digabungkan cukup Peta Kantor/Wilayah saja. Yang lain biar terpisah.

**Comment by eddieridwan** [comment]
>  (menjawab pertanyaan "Apa yg anda perbaiki?") yaitu parameter yg dipakai di semua form adalah NAMA DUSUN bukan ID, sehingga jika ada nama dusun dengan 2 kata dengan spasi maka data akan hilang/error.

Bung @fusionid , **`mohon anda kemballikan lagi ke penerapan semula`**. Karena perubahan yg anda buat akan berdampak tidak terduga. Kalau anda menemukan tidak terkait mohon anda buat issue terpisah untuk dibahas lebih lanjut, sebelum diterapkan. Terima kasih.

Perhatikan, struktur tabel `tweb_wil_clusterdesa` yg diwarisi dari pengembang asli SID CRI menggunakan penentuan relasi antara dusun/rw/rt yg sangat tidak konvensional. Tetapi karena penggunaan tabel ini merambat kemana-mana selama ini belum berani untuk diotak-atik.

![nama-dusun](https://user-images.githubusercontent.com/249563/67530975-9439e080-f70c-11e9-8ae0-fe6b0de9a13d.jpg)

**Comment by fusionid** [comment]
Jangan khawatir hal ini sudah jadi sop bagi saya,  karena fitur yg sy tambah adalah adhoc, jadi tidak ada script yg sudah ada kemudian dirubah, hanya menambahkan script baru saja

**Comment by fusionid** [comment]
Penambahan tombol aksi untuk ubah peta di wilayah administrasi https://github.com/OpenSID/OpenSID/commit/82781f2e39a5b11691da0e18b0650713a197a6da

![Screen Shot 10-25-19 at 07 23 AM](https://user-images.githubusercontent.com/10391199/67534521-a9a50f80-f6f8-11e9-8e41-10594dfe6799.PNG)

![Screen Shot 10-25-19 at 07 23 AM 001](https://user-images.githubusercontent.com/10391199/67534527-b0cc1d80-f6f8-11e9-9945-a455288cfc82.PNG)

**Comment by eddieridwan** [comment]
Sudah dikerjakan.
