### ISSUE TITLE
[peta] Perubahan data identitas desa hilang setelah ubah peta kantor/wilayah desa

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#2436]
### Bagaimana alurnya sampai muncul masalah?
Lihat penjelasan di #2435. Masalah serupa terjadi juga di _Info Desa > Identitas Desa_.

![ubah-identitas-desa](https://user-images.githubusercontent.com/249563/67437644-122eb680-f63d-11e9-9b7a-f67681d4610a.jpg)

### Seperti apa yang diharapkan?
Solusi untuk _Identitas Desa_  tidak bisa menggunakan pendekatan yg diusulkan untuk Dusun/RW/RT di #2435 , karena tidak ada daftar desa.

Salah satu opsi adalah dengan menata _Identitas Desa_, supaya tidak langsung masuk ke form ubah. Melainkan tampilkan dulu data identitas desa sebagai read-only, dan sediakan tombol untuk ubah data identitas desa, ubah peta kantor/wilayah desa. Gambar berikut menunjukkan contoh di biodata penduduk.

![tampilan-identitas-desa](https://user-images.githubusercontent.com/249563/67437696-338fa280-f63d-11e9-9a45-31596bdd5491.jpg)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | peta
| Versi PHP        | 
| System operasi   |

**Comment by fusionid** [comment]
Tidak bisa replikasi masalah karena tidak data identitas desa hilang setelah ubah peta kantor/wilayah desa. Tapi sudah dire-commit untuk memastikan ulang.

**Comment by eddieridwan** [comment]
Masalah belum diperbaiki.

1. buka form identitas desa
2. isi alamat email desa atau kolom isian lainnya (jangan klik simpan)
3. buka form ubah kantor/wilayah desa
4. gunakan breadcrumb untuk kembali ke form identitas desa.

Semua perubahan di langkah (2) hilang semua (karena form belum sempat disimpan).

**Comment by fusionid** [comment]
Penambahan Halaman Muka Identitas Desa

![iden1](https://user-images.githubusercontent.com/10391199/67556631-b39d3180-f73d-11e9-8920-09d25a9478af.PNG)

![iden2](https://user-images.githubusercontent.com/10391199/67556660-c0ba2080-f73d-11e9-8d4c-87fb083296b8.PNG)

**Comment by eddieridwan** [comment]
Sudah diperbaiki.
