### ISSUE TITLE
Uncaught Error: Highcharts error #16

### ISSUE THREAD

**Issue by fusionid** [OpenSID/OpenSID#2440]
### Bagaimana alurnya sampai muncul masalah?`
1. Di Chrome -> buka window Developer tools -> Console
2. Klik menu Statistik 
3. Statistik Kependudukan
4. Umur
5. Klik Grafik Data

Console akan menampilkan "Uncaught Error: Highcharts error #16"

![error](https://user-images.githubusercontent.com/10391199/67650206-a31fcd80-f96e-11e9-907f-e9b29e8022ad.PNG)

### Seperti apa yang diharapkan?

TIdak boleh ada error di console

### Apa yang terjadi?

Library highcharts.js berusaha diloading lagi padahal sudah include di file exporting.js

### Informasi tambahan 

Solusinya hapus script ini di file donjo-app/views/statistik/penduduk_graph.php dan penduduk_pie.php 

"<script src="<?= base_url()?>assets/js/highcharts/highcharts.js"></script>"

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dicommit ke master. 
@fusionid kalau ada perbaikan lain silakan di pull request saja. Terima kasih.
