### ISSUE TITLE
Dropdown aksi di HP tidak responsive

### ISSUE THREAD

**Issue by fusionid** [OpenSID/OpenSID#2441]
### Bagaimana alurnya sampai muncul masalah?
1. Buka Demo OpenSID di HP
2. Kependudukan
3. Penduduk
4. Pilih Aksi
5. klik salahsatu menu
6. Tidak ada response

Hal ini terjadi juga di dropdown aksi Peta

![dropdown](https://user-images.githubusercontent.com/10391199/67653061-4cb88c00-f97a-11e9-8040-a0f8f5f32432.jpg)

### Seperti apa yang diharapkan?
Ada response ketika klik menu

### Informasi tambahan 

Kemungkinan di file admin-style.css 

@media (max-width: 767px) {
  .table-responsive .dropdown-menu {
    position: static !important;
  }
}
@media (min-width: 768px) {
  .table-responsive {
    overflow: visible;
  }
}

Perlu dirubah menjadi 

@media (max-width: 767px) {
    .table-responsive{
        overflow-x: auto;
        overflow-y: auto;
    }
}
@media (min-width: 767px) {
    .table-responsive{
        overflow: inherit !important; 
    }
}

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
