### ISSUE TITLE
Perbaiki database supaya sesuai setting sql_mode 'strict'

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#2444]
### Bagaimana alurnya sampai muncul masalah?
1. Buat setting sql_mode database OpenSID berisi STRICT_TRANS_TABLES.
2. Jalankan menu OpenSID untuk mengubah data penduduk atau lainnya 

### Seperti apa yang diharapkan?
Tidak ada error.

### Apa yang terjadi?
Ada error yg disebabkan setting sql_mode yg ada STRICT_TRANS_TABLES.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | v19.10
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Perlu buatkan migrasi DB untuk memperbaiki setiap tabel supaya semua kolom yg tidak harus diisi ada nilai defaultnya.

**Comment by fusionid** [comment]
@eddieridwan , Mohon dicek apakah tabel yg akan diperbaiki sudah masuk ke file script ini (file digenerate secara otomatis, jadi jika ada yg diperbaik, file ini akan digenerate lagi dalam hitungan detik)

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR #2450
