### ISSUE TITLE
Status Hubungan Dalam Keluarga tidak lengkap ketika menambah Anggota Keluarga di KK Baru

### ISSUE THREAD

**Issue by redjoel** [OpenSID/OpenSID#2445]
### Bagaimana alurnya sampai muncul masalah?
![tidak ada pilihan Istri](https://user-images.githubusercontent.com/22895596/67821539-5831c180-faf8-11e9-9ae7-b41acb04c766.png)
Tidak Ada pilihan Istri dalam Dropdown Status

### Seperti apa yang diharapkan?
Semestinya Lengkap

### Apa yang terjadi?
Harus Manual mengubah status Istri dari Ubah biodata 

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19.10
| Versi PHP        | WebHost
| System operasi   | WebHost

**Comment by eddieridwan** [comment]
Sepertinya terjadi pada kasus di mana No KK bernilai '0'.

**Comment by redjoel** [comment]
> Sepertinya terjadi pada kasus di mana No KK bernilai '0'.

maaf pak Kesalahan saya ketika memecah anggota keluarga, tidak langsung mengubah status perkawinan (harusnya belum menikah > menikah)
