### ISSUE TITLE
Perbaikan Lampiran Permohonan KK ==> F-1.15

### ISSUE THREAD

**Issue by PWidodo** [OpenSID/OpenSID#2446]
### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19.10-pasca
| Versi PHP        |  7.2.0
| System operasi   | Windows 10
![Kode Desa tertukar dengan Kode Pos](https://user-images.githubusercontent.com/45189822/67858983-167f3600-fb4d-11e9-8a48-c753e278fd21.png)

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR #2447
