### ISSUE TITLE
[Bug] Widget Keuangan Not Found

### ISSUE THREAD

**Issue by hirudi** [OpenSID/OpenSID#2455]
### Bagaimana alurnya sampai muncul masalah?

Buka menu Admin Web - Widget - Widget Keuangan

![image](https://user-images.githubusercontent.com/4936934/68006372-f82f4c80-fcaa-11e9-8c70-9a6f1e04f8e6.png)

![image](https://user-images.githubusercontent.com/4936934/68006389-04b3a500-fcab-11e9-8c64-c8311d3f5728.png)

### Seperti apa yang diharapkan?

Tidak terjadi error tersebut

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19.11
| Versi PHP        | 7.2

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
