### ISSUE TITLE
Failed to load plugin: filemanager from url http://jatisobo.id/assets/filemanager/plugin.min.js

### ISSUE THREAD

**Issue by ridwanhadipranata** [OpenSID/OpenSID#2456]
### Bagaimana alurnya sampai muncul masalah?
Load file manager gagak

### Seperti apa yang diharapkan?
File manager bisa kembali

### Apa yang terjadi?
Tidak bisa menggunakan file manager

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
@ridwanhadipranata Selalu tampilkan tampakan layar terjadinya error. Supaya bisa dilacak masalahnya.

Apakah sudah melihat apakah masalah anda ada di https://github.com/OpenSID/OpenSID/wiki/Tanya-Jawab-Install-dan-Update?

**Comment by ridwanhadipranata** [comment]
Pada tanggal Sab, 2 Nov 2019 16:41, Eddie Ridwan <notifications@github.com>
menulis:

**Comment by eddieridwan** [comment]
Issue ini akan ditutup, karena sepertinya masalah ada di instalasi anda. Silakan buka lagi kalau ditemukan bug yg perlu diperbaiki oleh programmer
