### ISSUE TITLE
[Bug] Surat Keterangan Pindah 

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#2457]
### Bagaimana alurnya sampai muncul masalah?
Ketika Ekspor Surat Keterangan Pindah muncul Seperti gambar dibawah ini
![image](https://user-images.githubusercontent.com/25834335/68080231-efb15000-fe29-11e9-83b6-2c408abbe1ae.png)
Tampilan ini muncul ketika menggunakan PHP versi 7.2.3 keatas
![image](https://user-images.githubusercontent.com/25834335/68080239-0d7eb500-fe2a-11e9-8d3e-c0470415634d.png)
Kalau menggunakan PHP 7.0.33 berjalan normal

### Seperti apa yang diharapkan?
Hasil Ekspor Seperti mengunakan PHP 7.0.33 atau dibawah nya

### Apa yang terjadi?
Tidak bisa cetak surat keterangan Pindah beserta lampirannya

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by MUHAMMADRANGSEL** [comment]
Ini hanya Terjadi di Surat Keterangan Pindah Saja, Kalau surat yang lain yang punya lampiran tidak ada maslah

**Comment by uncu29** [comment]
sepertinya belum update opensidnya, berikut ini opensid terbaru dan menggunakan phpmyadmin 7.2.3
![surat_ket_pindah_penduduk_5201142005716996_2019-11-04_1_lampiran pdf - Mozilla Firefox 04_11_2019 10_23_15](https://user-images.githubusercontent.com/51182125/68098090-58153580-feed-11e9-9224-d0d3f0f5b95f.png)

**Comment by MUHAMMADRANGSEL** [comment]
Coba yg F1. 08

Pada tanggal Sen, 4 Nov 2019 11.26, Nur Hidayat <notifications@github.com>
menulis:

**Comment by uncu29** [comment]
![surat_ket_pindah_penduduk_1404160708820005_2019-11-07_2_lampiran pdf - Adobe Reader 07_11_2019 21 00 48](https://user-images.githubusercontent.com/51182125/68395191-e1ed2900-01a1-11ea-932b-689c5cb3bd0c.png)
menggunakan php v 7.3.5

**Comment by MUHAMMADRANGSEL** [comment]
sudah ketemu permasalahannya karena saya menambahkan padded_string_center di lampiran F1.08 seperti contoh  **<?php echo padded_string_center(strtoupper($input['pamong']))?>**
seperti gambar dibawah ini sehingga tidak terbaca di PHP 7.1 ke atas
![image](https://user-images.githubusercontent.com/25834335/68409594-ede4e500-01b9-11ea-80a3-a2481e2aa384.png)

Sehingga issue ini bung eddie dan kawan-kawan saya tutup
