### ISSUE TITLE
Tombol scrol horizontal untuk kependudukan, keluarga dan arsip surat tidak tampil

### ISSUE THREAD

**Issue by WAHYUDIK** [OpenSID/OpenSID#2458]
### Bagaimana alurnya sampai muncul masalah?
Ketika kita mengakses menu Kependudukan>penduduk/Keluarga dan Menu Persuratan>arsip layanan tombol scrollnya tidak ada.
![image](https://user-images.githubusercontent.com/31026980/68098463-6ebc8c00-feef-11e9-8f51-06ce765ec186.png)
![image](https://user-images.githubusercontent.com/31026980/68098466-74b26d00-feef-11e9-9644-f81758b58759.png)
![image](https://user-images.githubusercontent.com/31026980/68098475-7b40e480-feef-11e9-88f5-01d894cc9623.png)

### Seperti apa yang diharapkan?
Tombol scrolnya muncul kembali

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR #2459
