### ISSUE TITLE
Format Keterangan Kelahiran

### ISSUE THREAD

**Issue by ciparanti** [OpenSID/OpenSID#2460]
Mohon Ditambahkan Format Keterangan lahir Seperti terlampir
![lahir](https://user-images.githubusercontent.com/57306366/68107571-dbe41780-ff17-11e9-8ad9-b55056353821.jpeg)
pir

**Comment by eddieridwan** [comment]
Harap lampirkan peraturan terkait beserta petunjuk pengisiannya.

**Comment by mizwaruddin** [comment]
@afa28 format ini juga tidak dibutuhkan.
