### ISSUE TITLE
Format Keterangan Kematian

### ISSUE THREAD

**Issue by ciparanti** [OpenSID/OpenSID#2461]
Mohon ditambah Keterangan Kematian Seperti Format Terlampir
![mati](https://user-images.githubusercontent.com/57306366/68107663-236aa380-ff18-11e9-8ce6-63fe55818220.jpeg)

**Comment by eddieridwan** [comment]
Harap lampirkan peraturan terkait beserta petunjuk pengisiannya.

**Comment by andryrukandifauzy** [comment]
Untuk Di beberapa daerah masih menggunakan  menggunakan format Seperti itu pak @eddieridwan , Bagus sekali jika format Seperti itu dimasukan kedalam rilis jadi nanti dalam lampiran kematian ada dua format f-2.17 dan f-2.29

dan juga ada penamaan format f-2.17 dengan f-2.16 saya tidak tahu yang benar tapi di daerah saya menggunakan f-2.17.
Petunjuk pengisiannya sama dengan yang f-2.29 mungkin 
berikut lampiran yang saya dapat
[F-2.16 SURAT KETERANGAN KEMATIAN.pdf](https://github.com/OpenSID/OpenSID/files/3807698/F-2.16.SURAT.KETERANGAN.KEMATIAN.pdf)

**Comment by mizwaruddin** [comment]
@afa28 format ini juga tidak dibutuhkan.
