### ISSUE TITLE
Formuli Tambah Biodata Penduduk

### ISSUE THREAD

**Issue by ciparanti** [OpenSID/OpenSID#2462]
Mohon ditambah Formulir Tambah Biodata Penduduk dengan format Terlampir

![tambah](https://user-images.githubusercontent.com/57306366/68107851-a8ee5380-ff18-11e9-98f4-15927df840df.jpeg)

**Comment by eddieridwan** [comment]
Harap lampirkan peraturan terkait, beserta petunjuk pengisiannya.

**Comment by mizwaruddin** [comment]
@afa28 tidak ada respon dari pembuat issue. 
Berdasarkan pengalaman saya di Pemdes, format lampiran ini juga tidak dibutuhkan.
