### ISSUE TITLE
[ Informasi Publik ] Batasi dokumen aktif saja yang bisa tampil di web 

### ISSUE THREAD

**Issue by R4HMAT** [OpenSID/OpenSID#2463]
Bagaimana alurnya sampai muncul masalah?

1. Lihat Laman Menu Informasi Publik
2, Perhatikan Screnshoot dibawah ini

![image](https://user-images.githubusercontent.com/43318683/68109327-d76e2d80-ff1c-11e9-9e31-daa0033b5bc4.png)

![image](https://user-images.githubusercontent.com/43318683/68109423-113f3400-ff1d-11e9-9a1e-4e6cd9932cdb.png)

Seperti apa yang diharapkan?
ketika icon kunci di aktifkan supaya Nama Documen tidak muncul.

Tanya | Jawab

-- | --
Versi OpenSID | 19.10. Pasca
Versi PHP |  
System operasi |

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
