### ISSUE TITLE
Sediakan data asuransi sebagai pilihan statistik kependudukan untuk menu statis

### ISSUE THREAD

**Issue by afri18** [OpenSID/OpenSID#2464]
### Bagaimana alurnya sampai muncul masalah?
saat menambah statistik di menu statis > data desa > tidak ditemukan link untuk Jenis Asuransi sedangkan di STATISTIK PENDUDUK ada

### Seperti apa yang diharapkan?
timbulkan semua link tentang STATISTIK KEPENDUDUKAN di menu statis tambah submenu

### Apa yang terjadi?
tidak bisa menampilkan submenu jenis asuransi di halaman web

### Informasi tambahan 
![image](https://user-images.githubusercontent.com/6611881/68181133-df83a700-ffc8-11e9-92ba-2a3ba52df092.png)

![image](https://user-images.githubusercontent.com/6611881/68181153-ee6a5980-ffc8-11e9-87a6-9ee1a5019b4e.png)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR #2466
