### ISSUE TITLE
Perbaikan menu Dusun RW RT pada Ubah Data KK

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#2473]
### Bagaimana alurnya sampai muncul masalah?
![121212](https://user-images.githubusercontent.com/35319600/68641082-54f8f580-053c-11ea-9fe0-deb5fd8d97cd.jpg)
![1212121](https://user-images.githubusercontent.com/35319600/68641081-54f8f580-053c-11ea-958f-a18c5069ca4d.jpg)

### Seperti apa yang diharapkan?
![1212122](https://user-images.githubusercontent.com/35319600/68641096-6215e480-053c-11ea-9787-6d742b263f05.jpg)
![1212123](https://user-images.githubusercontent.com/35319600/68641093-6215e480-053c-11ea-9eb6-f6522254174e.jpg)

### Apa yang terjadi?
menyesuaikan desain tampilan pilihan menu Dusun RW RT dengan Pilihan menu kelas sosial

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR #2474
