### ISSUE TITLE
[kab50kota] Kirim informasi publik ke PPID Kabupaten melalui API aplikasi PPID

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#2475]
### Bagaimana alurnya sampai muncul masalah?
Pengiriman data informasi publik melalui proses ekspor/impor merupakan cara yg dapat digunakan apabila belum tersedia cara integrasi langsung antara OpenSID dan PPID Kabupaten.

Pengiriman data informasi publik melalui API lebih efisien dan menghindari kerumitan proses dalam menangani file kiriman secara manual.

### Seperti apa yang diharapkan?
OpenSID dapat mengirim data informasi publik ke API yang disediakan aplikasi PPID Kabupaten. 

OpenSID dapat mengirimkan:
1. keseluruhan data informasi publik
2. data informasi publik yg telah berubah sejak tanggal tertentu

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | v19.11
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
API yg disediakan oleh PPID Kabupaten perlu bisa menerima:
- data informasi publik
- file untuk dokumen terkait masing2 informasi publik

API itu juga perlu bisa menangani:
- menggantikan keseluruhan informasi publik untuk suatu desa
- mengubah informasi publik suatu desa sesuai data perubahan yg dikiri,

**Comment by eddieridwan** [comment]
API yg disediakan oleh PPID Kabupaten perlu bisa menerima:
- data informasi publik
- file untuk dokumen terkait masing2 informasi publik

API itu juga perlu bisa menangani:
- menggantikan keseluruhan informasi publik untuk suatu desa
- mengubah informasi publik suatu desa sesuai data perubahan yg dikirim

**Comment by afa28** [comment]
Silahkan direopen jika masih bermasalah.
