### ISSUE TITLE
Statistik di Peta Tidak Tampil

### ISSUE THREAD

**Issue by mizwaruddin** [OpenSID/OpenSID#2479]
### Bagaimana alurnya sampai muncul masalah?
Statistik di peta tidak bisa tampil jika dalam desa terdiri atas Dusun, RW, dan RT.

### Seperti apa yang diharapkan?
Statistik di peta bisa tampil jika dalam desa terdiri atas Dusun, RW, dan RT.

### Apa yang terjadi?
Statistik di peta tidak bisa tampil jika dalam desa terdiri atas Dusun, RW, dan RT.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19.11-pasca
| Versi PHP        | 7.2
| System operasi   | win7
![statistik](https://user-images.githubusercontent.com/39736008/68996109-3aba7100-08c8-11ea-9f4a-2265548e1dda.PNG)

**Comment by fusionid** [comment]
Pastikan ada data penduduk dengan domisili/alamat di Dusun, RW, dan RT tersebut.
Statistik hanya akan tampil jika ada parameternya.

**Comment by mizwaruddin** [comment]
Data penduduk di desa sya sdh lengkap dg RT, RW, dan Dusun. 
![Screenshot_2019-11-17-07-51-44](https://user-images.githubusercontent.com/39736008/69001343-3f564800-090f-11ea-904e-d7c8441d4723.png)

**Comment by fusionid** [comment]
Terimakasih atas informasinya. 
Permasalahan statistik tidak tampil pada issue ini dikarenakan ada nama desa atau dusun memakai lebih dari 1 kata dan dipisah spasi.
Kami akan mencoba untuk mencarikan solusinya.

**Comment by fusionid** [comment]
Solusi sementara adalah menyisipkan underscore ( _ ) diantara nama desa/dusun misalnya "MUTIH KULON" menjadi "MUTIH_KULON"

**Comment by eddieridwan** [comment]
Sudah dikerjakan
