### ISSUE TITLE
Centang desa/dusun/rw/rt di peta tidak konsisten

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#2480]
### Bagaimana alurnya sampai muncul masalah?
1. Pastikan ada peta desa dan sedikitnya dusun
2. Di peta centang dusun 
3. Perhatikan desa ikut tercentang, dan yg tampil desa dan dusun
4. Hapus centang desa
5. Perhatikan hanya dusun yg sekarang tampil dan yg tercentang
<img width="1256" alt="tampilkan-peta-dusun" src="https://user-images.githubusercontent.com/249563/69049385-d7f5e080-0a53-11ea-9765-283621ef61e2.png">

6. Hapus centang dusun
7. Perhatikan sekarang desa tercentang dan yg tampil di peta

### Seperti apa yang diharapkan?
Masing2 pilihan desa/dusun/rw/rt hanya menampilkan/menyembunyikan wilayah bersangkutan di peta, dan tidak menampilkan wilayah yg lain.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | v19.11-pasca
| Versi PHP        | 
| System operasi   |

**Comment by fusionid** [comment]
Sudah diperbaiki di commit #2485

**Comment by eddieridwan** [comment]
Sudah dikerjakan
