### ISSUE TITLE
Tidak ada pilihan untuk menampilkan garis di peta

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#2481]
### Bagaimana alurnya sampai muncul masalah?
1. Buat tipe garis dan buat garis menggunakan tipe garis itu
2. Buka peta
3. Di peta buka pilihan untuk menampilkan berbagai unsur peta
4. Cari pilihan untuk menampilkan garis yg telah dibuat.

### Seperti apa yang diharapkan?
Ada pilihan untuk menampilkan garis

### Apa yang terjadi?
Tidak ada pilihan untuk menampilkan garis
<img width="1256" alt="tidak-ada-pilihan-garis" src="https://user-images.githubusercontent.com/249563/69049877-f7413d80-0a54-11ea-9fba-5314d9aa2dbd.png">

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | v19.11-pasca
| Versi PHP        | 
| System operasi   |

**Comment by fusionid** [comment]
Fitur baru ini sudah ditambahkan di commit #2485

**Comment by eddieridwan** [comment]
Sudah dikerjakan
