### ISSUE TITLE
[Bug] Peta tidak menampilkan warna area sesuai setting tipe area

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#2482]
### Bagaimana alurnya sampai muncul masalah?
1. Buat Pemetaan > Pengaturan Peta > Tipe Area, pastikan telah memilih warna area
2. Buat Area menggunakan Tipe Area yg telah dibuat
3. Buka Pemetaan > Peta
4. Centang Area untuk menampilkan semua Area
5. Perhatikan warna area yg dibuat di langkah (2)

### Seperti apa yang diharapkan?
Warna area ditampilkan di peta sesuai dengan setting warna tipe area.

### Apa yang terjadi?
Semua warna area sama, bisa berbeda dengan setting warna tipe area.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | v19.11-pasca
| Versi PHP        | 
| System operasi   |

**Comment by fusionid** [comment]
Sudah ditambahkan di commit #2485

**Comment by eddieridwan** [comment]
Sudah dikerjakan.
