### ISSUE TITLE
[Bug] Fitur cari penduduk di peta tidak berfungsi baik

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#2484]
### Bagaimana alurnya sampai muncul masalah?
1. Buka peta
2. Buka fitur cari penduduk dan isi form untuk memilah penduduk yg tampil di peta berdasarkan dusun/rw/rt
3. Perhatikan isi form cari penduduk setelah peta dipilah

### Seperti apa yang diharapkan?
<img width="1256" alt="cari-penduduk" src="https://user-images.githubusercontent.com/249563/69134870-4dbd8300-0b0c-11ea-9df5-9ca2c422d893.png">

### Apa yang terjadi?
<img width="1256" alt="cari-penduduk-di-peta" src="https://user-images.githubusercontent.com/249563/69133889-bc014600-0b0a-11ea-9ff3-b3cc9077e5c8.png">

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | v19.11-pasca
| Versi PHP        | 
| System operasi   |

**Comment by fusionid** [comment]
Fitur baru ini sudah ditambahkan di commit #2485

**Comment by eddieridwan** [comment]
@fusionid sesudah PR #2485, masih ada masalah:
- pemilihan RW tidak bisa menangani kasus tidak ada RW, yaitu di mana RW bernilai '-', seperti di contoh data awal

**Comment by eddieridwan** [comment]
Sudah dicommit ke master
