### ISSUE TITLE
Tampilkan Artikel Terbaru di Web Desa Dengan AJAX

### ISSUE THREAD

**Issue by dobbleone** [OpenSID/OpenSID#2494]
Pesanan Untuk memanfatkan AJAX dalam menampilkan artikel Terbaru pada web desa
Fitur yang diharapkan
1. Saat Kategori dipilih, Tampilkan data berdasarkan kategori terpilih tanpa meload web;
2. Saat paging di pindah, Halaman web tidak diload tampilkan data berdasarkan kategori dan paging
3. data yang dimaksud dapat diwakili oleh angka 3 pada gambar

![screenshot-localhost-2019 112](https://user-images.githubusercontent.com/34769878/69390552-f0475300-0d12-11ea-927a-109bf616ce74.png)

**Comment by sup-ham** [comment]
ini tema apa?

**Comment by afa28** [comment]
Silahkan direopen jika masih bermasalah.
