### ISSUE TITLE
[kab50kota] Tambah kolom Persyaratan dan Mandiri untuk surat layanan

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#2499]
### Bagaimana alurnya sampai muncul masalah?
Issue #2235 memerlukan adanya informasi persyaratan untuk setiap surat dan juga apakah surat ybs dapat diisi oleh oleh warga melalui layanan mandiri.

### Seperti apa yang diharapkan?
Di form Layanan Surat > Pengaturan Surat, disediakan kolom isian untuk memasukkan persyaratan surat dan untuk menandakan apakah surat itu dapat diisi oleh warga melalui layanan mandiri.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | v19.11
| Versi PHP        | 
| System operasi   |

**Comment by fusionid** [comment]
![draft1](https://user-images.githubusercontent.com/10391199/69537620-1854e180-0fb3-11ea-92c8-f9889794da5b.PNG)

![draft2](https://user-images.githubusercontent.com/10391199/69537629-1c80ff00-0fb3-11ea-9264-af79b6f2cb5f.PNG)

**Comment by eddieridwan** [comment]
Sudah dicommit sebagai fitur premium
