### ISSUE TITLE
[Bug] setelah kosongkan DB, jenis Asuransi dan klasifikasi surat ikut terhapus

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#2502]
### Bagaimana alurnya sampai muncul masalah?
pada waktu pertama kali install aplikasi dan mengosongkan DB, untuk jenis asuransi dan klasifikasi ikut terhapus

### Seperti apa yang diharapkan?
pada waktu mengosongkan DB, jenis asuransi dan klasifikasi tidak ikut terhapus

### Apa yang terjadi?
1. untuk jenis asuransi harus import manual
2. kalsifikasi harus import
### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
