### ISSUE TITLE
Penambahan karakter pada kolom isian NIP/NIAP

### ISSUE THREAD

**Issue by MSahid0102** [OpenSID/OpenSID#2505]
### Bagaimana alurnya sampai muncul masalah?
Pada isian NIP/NIAP pemerintah desa tidak dapan menambahkan spasi/titik

### Seperti apa yang diharapkan?
Mohon ditambahkan karakter spasi dan titik

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19.11-pasca
| Versi PHP        | 7.2.2
| System operasi   | Windows 10

**Comment by eddieridwan** [comment]
@MSahid0102 untuk permintaan seperti ini harap jelaskan ada alasannya. Apakah ada aturan terkait? Apakah ada form yg memerlukan?

**Comment by MUHAMMADRANGSEL** [comment]
Masalah ini juga di alami di kelurahan, penulisannya menggunakan spasi

**Comment by eddieridwan** [comment]
@MUHAMMADRANGSEL beri contoh masalahnya. Seperti apa penulisannya -- apakah baku? Dan apakah cara penulisan itu cukup hanya pada form isian saja, atau juga harus sampai ke ouput (surat, laporan) OpenSID?

**Comment by WAHYUDIK** [comment]
contoh penulisan NIP = 19770203 200001 1 001.

**Comment by eddieridwan** [comment]
@WAHYUDIK apakah itu cara penulisan yg baku? Apakah ada variasi lain penulisan NIP yg juga dianggap standar?

**Comment by WAHYUDIK** [comment]
Ini beberapa reverensi aturan tentang penulisan dan penerbitan NIP pak
![bkd-kabupaten-tapanuli-utara_wrx5w_14](https://user-images.githubusercontent.com/31026980/69765074-1783a180-11a5-11ea-8915-4ba649a9cd18.jpg)

https://bkd.taputkab.go.id/blog/serbaserbi/14-sekilas-tentang-nip-pns/

**Comment by eddieridwan** [comment]
@WAHYUDIK terima kasih. Mohon lain kali, info seperti itu langsung dilampirkan dari awal. Supaya jelas apa dan mengapa adanya permintaan.

**Comment by WAHYUDIK** [comment]
siap pak

**Comment by MSahid0102** [comment]
Untuk penulisan niap didesa penggunakan angka.spasi dan titik.contoh
11110022 1111 00.00.0 dan 11110022 1111 00.00.0.0 dan pada input data desa
niap kepala desa bisa menggunakan seperti contoh sedangkan pada input data
perangkat desa tidak bisa seperti contoh karena akan keluar pesan hanya
bisa diisi oleh angka saja dan rata2 desa di sini menggunakan niap seperti
contoh,atas perhatiannya saya ucapkan terima kasih.

Pada tanggal Sel, 26 Nov 2019 5.56 AM, Eddie Ridwan <
notifications@github.com> menulis:

**Comment by uncu29** [comment]
![Sistem Informasi Desa Desa Hibrida Jaya - Pengurus - Google Chrome 5 Des 2019 19 54 23](https://user-images.githubusercontent.com/51182125/70302604-164f1600-1830-11ea-8a86-1252e457899d.png)

**Comment by afa28** [comment]
Sudah di `master`
