### ISSUE TITLE
Error data base 2.09 lama ke versi 19.11

### ISSUE THREAD

**Issue by aindra0319** [OpenSID/OpenSID#2506]
membuat surat...
klik NIK .. PILIH.. langsng error??
sperti dibawah...

500
Sebuah Kesalahan Basis Data Telah Terjadi
Error Number: 1054

Unknown column 'u.waktu_lahir' in 'field list'

SELECT u.id AS id, u.nama AS nama, u.sex as sex_id, x.nama AS sex, u.id_kk AS id_kk, u.tempatlahir AS tempatlahir, u.tanggallahir AS tanggallahir, u.no_kk_sebelumnya, s.nama as status, u.waktu_lahir, u.tempat_dilahirkan, u.jenis_kelahiran, u.kelahiran_anak_ke, u.penolong_kelahiran, u.berat_lahir, u.panjang_lahir, u.id_cluster, (select (date_format(from_days((to_days(now()) - to_days(tweb_penduduk.tanggallahir))),'%Y') + 0) AS `(date_format(from_days((to_days(now()) - to_days(tweb_penduduk.tanggallahir))),'%Y') + 0)` from tweb_penduduk where (tweb_penduduk.id = u.id)) AS umur, w.nama AS status_kawin, f.nama AS warganegara,a.nama AS agama, d.nama AS pendidikan, j.nama AS pekerjaan, u.nik AS nik, c.rt AS rt, c.rw AS rw, c.dusun AS dusun, k.no_kk AS no_kk, k.alamat, (select tweb_penduduk.nama AS nama from tweb_penduduk where (tweb_penduduk.id = k.nik_kepala)) AS kepala_kk from tweb_penduduk u left join tweb_penduduk_sex x on u.sex = x.id left join tweb_penduduk_kawin w on u.status_kawin = w.id left join tweb_penduduk_agama a on u.agama_id = a.id left join tweb_penduduk_pendidikan_kk d on u.pendidikan_kk_id = d.id left join tweb_penduduk_pekerjaan j on u.pekerjaan_id = j.id left join tweb_wil_clusterdesa c on u.id_cluster = c.id left join tweb_keluarga k on u.id_kk = k.id left join tweb_penduduk_warganegara f on u.warganegara_id = f.id left join tweb_penduduk_status s on u.status = s.id WHERE u.id = '7'

Filename: C:/opensid/htdocs/opensid/system/database/DB_driver.php

Line Number: 691

**Comment by uncu29** [comment]
sudahkah migrasi db?

**Comment by uncu29** [comment]
struktur database telah berubah maka diperlukan migrasi db

**Comment by aindra0319** [comment]
sudah... 
dan saya coba hapus DB hasil resoter dan add penduduk baru.. 
masih error juga

**Comment by uncu29** [comment]
cba instal baru saja pak

**Comment by aindra0319** [comment]
maaf... ini tadi saya kosogkan data base... trus saya resoter ulang.... trus saya migrasi TERNYA BISA....
kemungkiinan kemaren ProSESnya belum selesai... karena rodok kesusu jadi klak klik klak klik saja....
karena tidak ada notifikasi kalo proses retore nya selesai..... 
terimkasih.....

**Comment by uncu29** [comment]
ashiaaapp, sami-sami
