### ISSUE TITLE
[bug][keuangan] Nilai yg tampil tidak betul

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#2507]
### Bagaimana alurnya sampai muncul masalah?
Laporan dari https://www.facebook.com/muslih.ramin (juga anggota https://app.slack.com/client/T6AH3NK50/C6ZES0SQ5/details/members). https://www.facebook.com/groups/OpenSID/permalink/1384377741727203/?comment_id=1384416121723365&reply_comment_id=1385153228316321

Fitur Siskeudes yang selama ini diterapkan tidak sesuai dengan siskeudes (angkanya) bisa sampai 4 kali lipat dari nilai yang sebenarnya.

### Seperti apa yang diharapkan?
Nilai yg tampil sesuai dengan Siskeudes

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | v19.11
| Versi PHP        | 
| System operasi   |

**Comment by muslihramin1** [comment]
Pak @eddieridwan ini lampirkan secara lengkap contoh masalahnya

![image](https://user-images.githubusercontent.com/51249936/69768481-50c30e00-11b3-11ea-9820-5a0e751ceba6.png)
![Laporan OpenSID](https://user-images.githubusercontent.com/51249936/69768748-5ff68b80-11b4-11ea-9618-35df218029d7.PNG)

![Siskeudes Anggaran](https://user-images.githubusercontent.com/51249936/69768770-83213b00-11b4-11ea-8a6c-ea738316a443.PNG)

[Result.zip](https://github.com/OpenSID/OpenSID/files/3899306/Result.zip)

**Comment by muslihramin1** [comment]
![Opensid](https://user-images.githubusercontent.com/51249936/69770005-d6e25300-11b9-11ea-8475-a0387585f462.png)

**Comment by eddieridwan** [comment]
@muslihramin1 , mohon di screenshot tampilan 'Informasi Anggaran' OpenSID, ditulis angka berapa yg seharusnya tampil. Maaf, karena kami buta huruf membaca laporan Siskeudes.

Mohon juga disediakan perbaikan serupa untuk Grafik Realisasi lainnya.

**Comment by muslihramin1** [comment]
![Perbdaan](https://user-images.githubusercontent.com/51249936/69773876-bf5d9700-11c6-11ea-9fe7-ba3003c0e8b8.png)

**Comment by muslihramin1** [comment]
Di OpenSID Realisasinya Tidak Terisi
![Realisasi Kosong](https://user-images.githubusercontent.com/51249936/69773933-f0d66280-11c6-11ea-908e-70ec86421ae2.PNG)

Sementara di SISKEUDES sudah ada data Realisasi
![Realisasi 2018](https://user-images.githubusercontent.com/51249936/69774000-28dda580-11c7-11ea-98ae-04927523a4d7.PNG)

**Comment by dobbleone** [comment]
perhatikan dalam pembiayaan desa ada dua (2) Kategori. 
1. penerimaan pembiayaan ( adalah uang sisa lebih dari realisasi tahun sebelumnya)
2. pengeluaran pembiayaan (adalah kode rekening yang diperuntukan untuk penyertaan modal desa )
masing-masing kode rekening memiliki realisasi yang berbeda. jadi tidak bisa ditambahkan seperti yang tampil pada statistik pembiayaan diatas

**Comment by dobbleone** [comment]
<img width="960" alt="2019-11-29 (4)" src="https://user-images.githubusercontent.com/34769878/69876648-73643c80-1303-11ea-87d9-25d43167731f.png">

**Comment by dobbleone** [comment]
dalam keuangan desa pembiayaan neto adalah asil pengurangan dari penerimaan pembiayaan dan pengeluaran pembiayaan serta memiliki realisasi masing2

**Comment by dobbleone** [comment]
<img width="960" alt="2019-12-05 (1)" src="https://user-images.githubusercontent.com/34769878/70234240-924f4c80-17a3-11ea-9d56-0bca151eed35.png">

**Comment by dobbleone** [comment]
terkait pembahasan pada https://www.facebook.com/groups/626787397486245?view=permalink&id=1390130031151974&notif_id=1575199385400393&notif_t=group_highlights&ref=notif

saya lampirkan gambar diatas
pada anggka 1, 2, 3 terdiri dari kolom Anggaran, Realisasi dan sisa/kurang.
sedangkan :
 1. baris Jumlah Pendapatan (4), Kolom Anggaran (1) terdapat jumlah pendapatan yang direncanakan akan diterima desa dalam satu tahun yang terdiri dari beberapa sumber pendapatan.
2. baris Jumlah Pendapatan (4), Kolom Realisasi (2) terdapat jumlah pendapatan yang telah terealisasi, artinya sejumlah uang yang telah diterima pada rekening kas desa (dalam contoh diatas telah diterima PAD, ADD Tahap I dan DD Tahap I)
3.baris Jumlah Pendapatan (4), Sisa/Kuang (3) terdapat jumlah selisih dari Anggaran dan Realisasi. artinya dana tersebut masih belum diterima desa.
pada intinya data setatistik Transparansi yang Akan ditampilkan bisa mewakili data tersebut.

4. perhitungan surplus/defisit (6) dihasilkan dari Jumlah pendapatan di kurang Jumlah Belanja 
5. pembiayaan netto (7) hasil dari Penerimaan Pembiayaan - Pengeluaran Pembiayaan

## mungkin penjelasan agak susah dimengerti, atau para programer lebih faham terkait data yang dihasilkan oleh aplikasi siskeudesa atau teman2 yang lain dapat membantu menjelaskan

**Comment by dobbleone** [comment]
<img width="960" alt="2019-12-05 (3)" src="https://user-images.githubusercontent.com/34769878/70238185-245b5300-17ac-11ea-82a0-6685dcf77694.png">

**Comment by ekasatriabahari** [comment]
> Di OpenSID Realisasinya Tidak Terisi
> ![Realisasi Kosong](https://user-images.githubusercontent.com/51249936/69773933-f0d66280-11c6-11ea-908e-70ec86421ae2.PNG)
> 
> Sementara di SISKEUDES sudah ada data Realisasi
> ![Realisasi 2018](https://user-images.githubusercontent.com/51249936/69774000-28dda580-11c7-11ea-98ae-04927523a4d7.PNG)

bisa kirimkan pdf laporannya disini??

**Comment by muslihramin1** [comment]
Assalamu'alaikum Bung @eddieridwan sesuai permintaan untuk melampirkan file pdf untuk laporan SISKEUDES, semoga dapat membantu untuk OpenSID yang lebih mantap
[Realisasi APBDes Smester I 2019.pdf](https://github.com/OpenSID/OpenSID/files/3942492/Realisasi.APBDes.Smester.I.2019.pdf)
[Realisasi Anggaran Smester I 2019.pdf](https://github.com/OpenSID/OpenSID/files/3942493/Realisasi.Anggaran.Smester.I.2019.pdf)

**Comment by ekasatriabahari** [comment]
> Assalamu'alaikum Bung @eddieridwan sesuai permintaan untuk melampirkan file pdf untuk laporan SISKEUDES, semoga dapat membantu untuk OpenSID yang lebih mantap
> [Realisasi APBDes Smester I 2019.pdf](https://github.com/OpenSID/OpenSID/files/3942492/Realisasi.APBDes.Smester.I.2019.pdf)
> [Realisasi Anggaran Smester I 2019.pdf](https://github.com/OpenSID/OpenSID/files/3942493/Realisasi.Anggaran.Smester.I.2019.pdf)

bung @muslihramin1 bisa kirimkan **result.zip** nya yang tahun 2019 juga?? karena yg dilampirkan sebelumnya itu untuk tahun anggaran **2017**

**Comment by ekasatriabahari** [comment]
![image](https://user-images.githubusercontent.com/39932698/70502954-326af400-1b5d-11ea-92df-58cfba3c27ae.png)

untuk data pada table **Anggaran** dan **Pencairan** tahunnya juga beda
apa bisa dijelaskan [ak @muslihramin1 ???

**Comment by muslihramin1** [comment]
@ekasatriabahari untuk data pada table Anggaran dan Pencairan tahunnya tidak beda
mungkin karena ada data 2017 yang dimasukkan di database 2018. Pada prinsifnya database siskeudes hanya satu tahun anggaran kalo Siskeudsnya 2018 maka dari penganggaran sampai pelaporan semuanya 2018. ini saya lampirkan File CSV Database 2019
[result2019.zip](https://github.com/OpenSID/OpenSID/files/3945015/result2019.zip)

**Comment by muslihramin1** [comment]
Ini file Realisasi APBDes
[Realisasi APBDes 2019.pdf](https://github.com/OpenSID/OpenSID/files/3945022/Realisasi.APBDes.2019.pdf)

**Comment by muslihramin1** [comment]
![Realisasi](https://user-images.githubusercontent.com/51249936/70536599-9c04f580-1b91-11ea-898e-43722c6e72f8.png)

**Comment by ekasatriabahari** [comment]
oke saya cek lagi pak @muslihramin1

**Comment by ekasatriabahari** [comment]
jadi untuk kolom total diganti dengan lebih / kurang ya pak @muslihramin1 ??
jika pendapatan lebih kecil daripada belanja gmna??

**Comment by dobbleone** [comment]
cara perhitungan yang sala menurut saya

**Comment by dobbleone** [comment]
https://user-images.githubusercontent.com/34769878/69876648-73643c80-1303-11ea-87d9-25d43167731f.png perhatikan gambar berikut

**Comment by dobbleone** [comment]
> jadi untuk kolom total diganti dengan lebih / kurang ya pak @muslihramin1 ??
> jika pendapatan lebih kecil daripada belanja gmna??

tidak lebih kurang dari perhitungan yang mana pak?

**Comment by ekasatriabahari** [comment]
> Ini file Realisasi APBDes
> [Realisasi APBDes 2019.pdf](https://github.com/OpenSID/OpenSID/files/3945022/Realisasi.APBDes.2019.pdf)

dari contoh yg ini pak @dobbleone

**Comment by ekasatriabahari** [comment]
![image](https://user-images.githubusercontent.com/39932698/70782566-419eab80-1dc2-11ea-9aa4-fcae8d84561c.png)

kemudian, field mana yg bisa saya relasikan ke rincian belanja nya dari table pencairan??

**Comment by dobbleone** [comment]
> jadi untuk kolom total diganti dengan lebih / kurang ya pak @muslihramin1 ??
> jika pendapatan lebih kecil daripada belanja gmna??

pendapatan lebih kecil dari belanja bisa ditutupi dengan penerimaan pembiayaan pak.  agak sulit menjelaskan karena semua saling berkaitan mungkin bisa via wa

**Comment by ekasatriabahari** [comment]
> > jadi untuk kolom total diganti dengan lebih / kurang ya pak @muslihramin1 ??
> > jika pendapatan lebih kecil daripada belanja gmna??
> 
> pendapatan lebih kecil dari belanja bisa ditutupi dengan penerimaan pembiayaan pak. agak sulit menjelaskan karena semua saling berkaitan mungkin bisa via wa

bisa lewat slack saja

**Comment by ekasatriabahari** [comment]
untuk me-relasikan realisasi dengan jenis belanja nya menggunakan field yg mana pada table `keuangan_ta_pencairan` pak @dobbleone ??

**Comment by eddieridwan** [comment]
@muslihramin1 , sepertinya file csv untuk `keuangan_ta_pencairan` kurang lengkap. Tidak ada kode rincian untuk masing2 baris pencairan.  Apakah anda bisa kirimkan file .mdb/.mde yg langsung dibackup dari Siskeudes? Nanti saya coba ulangi konversinya untuk melihat apakah ada kolom tambahan di tabel `keuangan_ta_pencairan`. Terima kasih.

**Comment by eddieridwan** [comment]
@muslihramin1 , ada tabel yg merinci `spp` dan juga `spj`. Apakah mungkin tabel ini yg digunakan untuk menghitung realisasi? Juga ada tabel `sts` dan `tbp`. Apakah anda tahu kira2 apa arti kedua tabel ini?

**Comment by eddieridwan** [comment]
Apakah ada keterangan penatausahaan Siskeudes yg lebih baik : https://updesa.com/penatausahaan-siskeudes/ ? @muslihramin1

**Comment by eddieridwan** [comment]
Bung @ekasatriabahari , sepertinya tabel `keuangan_ta_pencairan` relasinya ke tabel `keuangan_ta_spp` dan `keuangan_ta_spp_rinci` sebagai pencairan SPP (menggunakan kolom `No_SPP`. Kemudian kegiatan pencairan itu dapat diperoleh dari kolom `Kd_Rincian` di tabel `keuangan_ta_spp_rinci` . 

`keuangan_ta_pencairan` --> `keuangan_ta_spp_rinci` --> `keuangan_ta_anggran_rinci`

Relasi yg pertama melalui `No_SPP`. Relasi kedua menggunakan `Kd_Rincian`.

**Comment by fusionid** [comment]
![rapbdes](https://user-images.githubusercontent.com/10391199/70799872-6eac8780-1ddd-11ea-8589-9447fa76ef00.png)

**Comment by fusionid** [comment]
**Anggaran Pendapatan** = Tabel : keuangan_ta_anggaran_rinci, Key : Kd_Rincian, Value : AnggaranStlhPAK
**Anggaran Belanja** = Tabel : keuangan_ta_anggaran_rinci, Key : Kd_Rincian , Value : AnggaranStlhPAK

**Realisasi Pendapatan** = Tabel : keuangan_ta_tbp_rinci , Key : Kd_Rincian , Value : Nilai
**Realisasi Belanja** = Tabel : keuangan_ta_spp_rinci , Key : Kd_Rincian , Value : Nilai , Join : keuangan_ta_spp.No_SPP

**Akun Anggaran & Realisasi Pendapatan/Belanja** = Tabel : keuangan_ref_rek1, Key : Akun, Nama_Akun, id_keuangan_master
**Akun Sub Anggaran & Realisasi Pendapata/Belanja** = Tabel : keuangan_ref_rek2, Key : Kelompok, Nama_Kelompok
**Akun Sub-sub Anggaran & Realisasi Pendapatan/Belanja** = Tabel : keuangan_ref_rek3, Key : Kelompok, Jenis, Nama_Jenis

**Comment by wawan87aja** [comment]
nilai anggaran untuk APBDES perubahan yang tampil di OPENSID, sepertinya berasal dari nilai APBDES awal + PAK. mungkin sebaiknya diberikan opsi jika yang akan ditampilkan adalah APBDes perubahan maka data yang ditampilkan hanya anggaran PAK nya saja seperti pada aplikasi siskeudes. 
untuk realisasi pendapatan transfer, datanya diambil dari Ta_TBP. 
hasil realisasi belanja sudah benar sesuai dengan nilai SPJ, walaupun untuk anggaran kegiatannya masih salah (anggaran awal + PAK)
untuk database yang juga menyimpan data desa lain, hasilnya tercampur semua data yang ada d database. mungkin bisa diberikan opsi untuk memilih data kecamatan dan desa yang akan diimport sepert saat kita akan mengekspor/import data di siskeudes

**Comment by wawan87aja** [comment]
nilai anggaran untuk APBDES perubahan yang tampil di OPENSID, sepertinya berasal dari nilai APBDES awal + PAK. mungkin sebaiknya diberikan opsi jika yang akan ditampilkan adalah APBDes perubahan maka data yang ditampilkan hanya anggaran PAK nya saja seperti pada aplikasi siskeudes.
untuk realisasi pendapatan transfer, datanya diambil dari Ta_TBP.
hasil realisasi belanja sudah benar sesuai dengan nilai SPJ, walaupun untuk anggaran kegiatannya masih salah (anggaran awal + PAK)
untuk database yang juga menyimpan data desa lain, hasilnya tercampur semua data yang ada d database. mungkin bisa diberikan opsi untuk memilih data kecamatan dan desa yang akan diimport sepert saat kita akan mengekspor/import data di siskeudes

**Comment by wawan87aja** [comment]
![campuran Clip2](https://user-images.githubusercontent.com/57819811/71383320-26803700-261f-11ea-84f0-579e505f0a0d.png)
untuk data yang tidak difilter perdesa, datanya tercampur. setelah difilter, hasilnya seperti di bawah ini. akan tetapi karena saya menggunakan spp panjar dan spj, maka nilai realisasi belanjanya tidak terbaca

![Clip1](https://user-images.githubusercontent.com/57819811/71383120-3ba89600-261e-11ea-8788-4e564fb2f220.png)

**Comment by wawan87aja** [comment]
belanja operasional perkantoran lainnya mengambil data dari Ta_mutasi dengan kd_mutasi = 3
![bunga bank](https://user-images.githubusercontent.com/57819811/71383623-82978b00-2620-11ea-9801-4b5055e333ec.png)
![ta_mutasi](https://user-images.githubusercontent.com/57819811/71383627-84f9e500-2620-11ea-8be8-7b3404afa9d9.png)

**Comment by wawan87aja** [comment]
![kd_posting](https://user-images.githubusercontent.com/57819811/71383716-f174e400-2620-11ea-92a1-01a82b1ed21c.png)

data ta_anggaran dibedakan antara anggaran awal dengan anggaran PAK berdasarkan kode posting. jika tidak di filter dulu, maka akan terbaca d sistem open sid anggaran = anggaran awal + anggaran PAK

**Comment by fusionid** [comment]
Laporan Rincian Keuangan sudah diperbaharui di branch "keuangan", mohon ditest dan direview.

![siskeudes](https://user-images.githubusercontent.com/10391199/72206137-d0cfd980-34bc-11ea-9079-f8b7524cd2e4.png)

**Comment by eddieridwan** [comment]
Perbaikan sudah dicommit ke `master`
