### ISSUE TITLE
BUG? Tampilan Mapbox kosong

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#2508]
### Bagaimana alurnya sampai muncul masalah?
buka menu pemetaan > peta > pilih tampilan Mapbox

### Seperti apa yang diharapkan?
peta muncul

### Apa yang terjadi?
blank kosong

### Informasi tambahan 
![Halo-5-Guardians-625x352](https://user-images.githubusercontent.com/35319600/69770335-33923d80-11bb-11ea-9c48-34b61e4523eb.jpg)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | demo
| Versi PHP        | 
| System operasi   |

**Comment by fusionid** [comment]
Token belum diisi, lihat di https://github.com/OpenSID/OpenSID/pull/2503
Token di website DEMO hanya untuk sementara.

**Comment by balongbesuk** [comment]
jika dirasa memungkinkan mungkin bs ditambah pop up peringatan token belum diisi supaya pengguna baru tidak salah paham
