### ISSUE TITLE
BUG? Tampilan Peta pada tampilan HP

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#2509]
### Bagaimana alurnya sampai muncul masalah?
buka website demo.opensid.my.id menggunakan HP pilih menu pemetaan > peta > pilih menu tampilan peta 

### Seperti apa yang diharapkan?
pilihan tampilan peta tampil

### Apa yang terjadi?
pilihan tampilan peta hilang

### Informasi tambahan 
![Halo-5-Guardians-625x352](https://user-images.githubusercontent.com/35319600/69770826-0fcff700-11bd-11ea-91ff-cbdb6818ce15.jpg)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR #2511
