### ISSUE TITLE
Error Submit Identitas Desa Setelah Kosongkan DB

### ISSUE THREAD

**Issue by andryrukandifauzy** [OpenSID/OpenSID#2510]
### Bagaimana alurnya sampai muncul masalah?
Ketika mensubmit identitas desa muncul error seperti pada gambar
![error ketika ubah data identitas desa stelah kosongkan db](https://user-images.githubusercontent.com/42363553/69774137-a73a4780-11c7-11ea-810f-374718643770.png)
error tersebutterjadi setelah mengkosongkan db.
dan setelah melihat log error nya 
![log error ternyata banyak](https://user-images.githubusercontent.com/42363553/69774175-c76a0680-11c7-11ea-925b-304509d869d5.png)
.

 sebelum mengkosongkan DB itu tidak  terjadi error seperti di atas

### Seperti apa yang diharapkan?
tidak terjadi error

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by andryrukandifauzy** [comment]
Om @eddieridwan ,Saya buka log lagi...
ini kenapa ya ?
![Screenshot_1](https://user-images.githubusercontent.com/42363553/69776215-e370a680-11cd-11ea-9d10-ca30ff2d5915.png)

**Comment by eddieridwan** [comment]
Sudah dicommit ke master
