### ISSUE TITLE
Error Akses Menu Pengaturan > Pengguna | OpenSID 19.08

### ISSUE THREAD

**Issue by nurmatdjou** [OpenSID/OpenSID#2512]
500
Sebuah Kesalahan Basis Data Telah Terjadi
Error Number: 1054

Unknown column 'g.nama' in 'field list'

SELECT u.*, g.nama as grup FROM user u, user_grup g WHERE u.id_grup = g.id ORDER BY u.username LIMIT 0,500

Filename: C:/xampp/htdocs/OpenSID/system/database/DB_driver.php

Line Number: 691

Harap laporkan masalah ini, agar kami dapat mencarikan solusinya. Untuk sementara Anda dapat kembali ke halaman awal.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Mohon tanyakan masalah penggunaan OpenSID di https://www.facebook.com/groups/OpenSID. Issue digunakan hanya untuk hal2 yg telah dipastikan sebagai bug yg perlu diperbaiki.

Masalah anda kemungkinan besar karena impor data yg tidak sempurna. Sebaiknya update ke rilis terkini dan coba install lagi.

Issue ini akan kami tutup, karena bukan masalah untuk programmer.
