### ISSUE TITLE
[Template Surat] Penambahan surat keterangan hibah 

### ISSUE THREAD

**Issue by muhtar-coder** [OpenSID/OpenSID#2514]
### Bagaimana alurnya sampai muncul masalah?
surat keterangan ini menjadi dasar utama sebagian besar untuk berkas/alas dasar sebelum dibuatkan sporadik tanah untuk permohonan sertifikat terutama untuk program sertifikat masal dari presiden.program tanah sistematis lengkap (PTSL)
rata-rata setiap desa mengerjakan bidang tanah dengan dasar hibah/waris lebih dari 200 bidang yang selanjutnya di buat kan surat sporadik (dalam program PTSL).

### Seperti apa yang diharapkan?
petugas desa/aparatur desa/pokmas PTSL lebih cepat dan akurat dalam pembuatan berkas tersebut mengingat prgram tersebut merupakan program unggulan dari presiden yang jangka waktu nya serba cepat.

### Apa yang terjadi?
pihak desa bisa menyelesaikan pekerjaan dengan cepat,kurang dari waktu yang pada umumnya.

### Informasi tambahan 
format di atas dapat di sesuaikan dengan format yang lebih bagus kalau sekiranya kurang sesuai.

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by muhtar-coder** [comment]
[FORM PESAN SURAT HIBAH.pdf](https://github.com/OpenSID/OpenSID/files/3905794/FORM.PESAN.SURAT.HIBAH.pdf)

**Comment by mizwaruddin** [comment]
Kelihatannya Bang @muhtar-coder sdh menerapkan surat ini secara mandiri. Tinggal kirim PR saja.
