### ISSUE TITLE
MOHON DI TAMBAHKAN SURAT SURAT PERTANAHAN DAN SUKET NIKAH SIRI

### ISSUE THREAD

**Issue by kayangan** [OpenSID/OpenSID#2516]
Mohon Di Pull Surat Surat Pertanahan Dan Surat Pernyataan dan  Keterangan Nikah SIRI
NOT : 
Isi ZIP ==>
1. SURAT SURAT BARU
2. Luar Folder Ada Script Untuk Di Tambahkan Kedalam Surat Model Untuk Munculkan List RT/RW
Jika Ada Kekurangan Mohon Diperbaiki Para Suhu Sebab Saya Juga Pemula Andelan Ilmu Copas ..
Terimkasih Banyak Sebelumnya Semoga Bermanfaat Untuk Kita Semua 
[SURAT SURAT BARU.zip](https://github.com/OpenSID/OpenSID/files/3907747/SURAT.SURAT.BARU.zip)

**Comment by uncu29** [comment]
@kayangan silahkan belajar mengirimkan PR pak
https://github.com/OpenSID/OpenSID/wiki/Panduan-mengirimkan-perubahan-repo-OpenSID

**Comment by kayangan** [comment]
-
