### ISSUE TITLE
[Surat] Tambah kode isian untuk menampilkan nama hari di DATA SURAT

### ISSUE THREAD

**Issue by benioke** [OpenSID/OpenSID#2518]
Bagaimana alurnya sampai muncul masalah?
Belum ada nya kode isian untuk menampilkan nama hari di data surat. 

Seperti apa yang diharapkan?
Perlu adanya kode isian untuk menampilkan nama hari saat surat di cetak sebagai pelengkap selain tanggal surat

Apa yang terjadi?
Saat ini menampilkan kan nama hari nya masih manual(tidak otomatis) 

 Informasi tambahan 
| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19.10
| Versi PHP        | 
| System operasi   |

**Comment by benioke** [comment]
Tambah kan kode ini di opensid_helper.php

![15752189361003946386804697243315](https://user-images.githubusercontent.com/47577404/69917120-39c33b00-1495-11ea-82df-271419d3a990.jpg)

Tambah kan kode ini di Surat_model.php

![1575219025970906004577723418070](https://user-images.githubusercontent.com/47577404/69917144-6aa37000-1495-11ea-9ede-9c13a0b75d5b.jpg)

**Comment by eddieridwan** [comment]
@benioke silakan sekalian belajar cara mengirim script ke OpenSID. Petunjuknya ada di https://github.com/OpenSID/OpenSID/wiki/Panduan-mengirimkan-perubahan-repo-OpenSID.

**Comment by LIQRGV** [comment]
@benioke, sebaiknya buatlah PR (pull request) untuk menambahkan fitur ini.

**Comment by mizwaruddin** [comment]
Untuk surat layanan tidak membutuhkan hari.

**Comment by vickyrolanda** [comment]
Berdasarkan aturan yang berlaku pada "PERANRI NO. 5 TAHUN 2021 PEDOMAN UMUM TATA NASKA" untuk penulisan tanggal surat tidak di sertakan nama hari, cukup tanggal surat saja.

sehingga issue ini belum terlalu relevan untuk kita gunakan dan terapkan, namun jika issue ini memiliki referensi yang mengacu pada keharusan mohon untuk melampirkan referensi sehingga issue ini bisa diterapkan untuk semua surat pada system OpenSID.
