### ISSUE TITLE
[Surat] Tambah kode isian untuk menampilkan nama kepala dusun, ketua RT, dan ketua RW di DATA SURAT

### ISSUE THREAD

**Issue by benioke** [OpenSID/OpenSID#2519]
Bagaimana alurnya sampai muncul masalah?
Belum ada nya kode isian untuk menampilkan Kepala dusun, ketua rt dan ketua rw secara otomatis di data surat. 

Seperti apa yang diharapkan?
Perlu adanya kode isian untuk menampilkan nama kepala dusun, nama ketua rt dan nama ketua rw secara otomatis untuk keperluan beberapa surat..

Sebagai contoh surat
Diketahui
Ketua RT 001
Nama:eddie ridwan

Apa yang terjadi?
Saat ini untuk  menampilkan nya manual(tidak otomatis) 

 Informasi tambahan 
| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19.10
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
Krn dusun, rw dan rt sifatnya dinamis mungkin agak ssah di terapkn.

**Comment by mizwaruddin** [comment]
@afa28 apakah issue ini masih akan ditindaklanjuti?

**Comment by afa28** [comment]
> @afa28 apakah issue ini masih akan ditindaklanjuti?

Ini bisa diselesaikan, tp mungkin beri contoh pd surat yg ad di OpenSID yg menggunakan data ini.
