### ISSUE TITLE
Fitur: sediakan daftar kode klasifikasi surat

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#252]
Kode klasifikasi surat digunakan untuk memudahkan pengarsipan surat, supaya surat keluar lebih mudah dicari menurut klasifikasi isi surat.

Daftar kode klasifikasi surat yang terintegrasi, apabila tersedia, akan memudahkan petugas admin surat/menyurat, supaya tidak perlu membuka daftar tsb secara terpisah atau menghafal kode klasifikasi.

Perlu dikonfirmasi, apakah daftar berikut adalah kode klasifikasi surat yang baku, atau yang umum digunakan desa:

https://docs.google.com/file/d/0B5oOxjjjp5iDMFJJSy1Oa0c1ZE0/view

**Comment by kayangan** [comment]
[33 JENIS KODE KLASIFIKASI SURAT MENYURAT.docx](https://github.com/OpenSID/OpenSID/files/1577510/33.JENIS.KODE.KLASIFIKASI.SURAT.MENYURAT.docx)
Sudah Kami pakai Di Desa Kayangan Kecamatan Kayangan KLU, itu sudah sesuai dengan rekomendasi Dinas Perpustakaan dan Kearsipan Kabupaten Lombok Utara.

**Comment by eddieridwan** [comment]
Sudah dicommit ke master. Menggunakan klasifikasi surat dari Nur Akhwan (lihat #558)
