### ISSUE TITLE
Tambahkan Tombol Kembali saat edit Lokasi Kantor Desa

### ISSUE THREAD

**Issue by hasap86** [OpenSID/OpenSID#2520]
### Bagaimana alurnya sampai muncul masalah?
belum adanya tombol Kembali pada menu Info Desa > Identitas Desa > Lokasi Kantor Desa

### Seperti apa yang diharapkan?
Tambahkan tombol Kembali selain tombol Simpan

### Apa yang terjadi?
Ketika batal mengedit harus klik menu

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | Versi 19.12
| Versi PHP        | 
| System operasi   |

**Comment by fusionid** [comment]
Tombol Kembali / Batal menggunakan breadcrumb (lingkar merah)

![menu](https://user-images.githubusercontent.com/10391199/70045892-75761600-15f7-11ea-9747-b0827d6a9d23.png)

**Comment by eddieridwan** [comment]
Bung @fusionid , mohon issue jangan ditutup sebelum PR anda selesai direview dan digabungkan ke master. Terima kasih.

**Comment by fusionid** [comment]
Pak @eddieridwan ini bukan PR tapi menjawab permintaan untuk tambahkan tombol Kembali selain tombol Simpan

**Comment by hasap86** [comment]
Biasanya tombol kembali dibuatkan tombol, bukan klik link dari Breadcrumb

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR #2594
