### ISSUE TITLE
Jenis Produk Hukum Kosong pada Data Instalasi Awal

### ISSUE THREAD

**Issue by hasap86** [OpenSID/OpenSID#2522]
![jenis-produk-hukum](https://user-images.githubusercontent.com/45263721/69920139-c9c5ac80-14b6-11ea-869f-912c3c014bd5.jpg)

### Bagaimana alurnya sampai muncul masalah?
Jenis Produk Hukum kosong pada menu **Sekretariat > Produk Hukum** pada Instalasi pertama

### Seperti apa yang diharapkan?
Seperti Demo ada Item Pilihan Jenis Produk Hukum pada Instalasi Awal / Migrasi DB

### Apa yang terjadi?
Tidak muncul di tampilan web

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | Versi 19.12
| Versi PHP        | PHP Version 7.2.24
| System operasi   | Linux

**Comment by eddieridwan** [comment]
Pada v19.12 dan juga sebelumnya, contoh data awal berisi contoh produk hukum. Kalau tidak tampil di sistem anda, pertanda instal yg belum sempurna. Silakan tanya di forum FB atau Telegram. 

Issue ini akan ditutup, karena bukan error di aplikasi.
