### ISSUE TITLE
Paginasi perlu diseragamkan?

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#2524]
### Bagaimana alurnya sampai muncul masalah?
Menu Web > Informasi Publik > Lihat Paginasi

### Seperti apa yang diharapkan?
sama

### Apa yang terjadi?
tidak sama dengan paginasi di halaman awal

### Informasi tambahan 
![tema-gambar-mewarnai-istana-untuk-anak-anak](https://user-images.githubusercontent.com/35319600/69925771-4e7aef80-14e4-11ea-8475-23cd792ff1ba.jpg)
| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | demo
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Telah dicommit ke master melalui PR #2586
