### ISSUE TITLE
[bug] Tema Hakadewa saat membuka album fitur Teks Berjalan tidak berfungsi

### ISSUE THREAD

**Issue by hasap86** [OpenSID/OpenSID#2528]
### Bagaimana alurnya sampai muncul masalah?
saat membuka album foto pada tema Hakadewa, fitur teks berjalan tidak berfungsi / tidak berjalan

### Seperti apa yang diharapkan?
seharusnya berfungsi seperti biasa, teks berjalan

### Apa yang terjadi?
tidak sesuai

### Informasi tambahan 
Tema Hakadewa

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | Versi 19.12
| Versi PHP        | 7.1.33
| System operasi   | Linux

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR #2530
