### ISSUE TITLE
Edit Nama Album pada Fitur Galery Admin Web seharusnya tidak wajib upload gambar lagi

### ISSUE THREAD

**Issue by hasap86** [OpenSID/OpenSID#2529]
![edit-album-gallery](https://user-images.githubusercontent.com/45263721/70007997-e3452200-15a4-11ea-914c-6129c3fe5f53.jpg)

### Bagaimana alurnya sampai muncul masalah?
Pada saat Edit Nama Album pada Fitur Galery Admin Web gambar harus diunggah kembali padahal hanya mau edit nama saja

### Seperti apa yang diharapkan?
seharusnya jika mau edit nama, upload gambar tidak wajib diisi (mengambil gambar sebelumnya)

### Apa yang terjadi?
harus upload ulang gambar sehingga menambah file gambar yg sebenarnya sudah ada

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | Versi 19.12
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR #2539
