### ISSUE TITLE
Tambahkan Tombol View Artikel di Admin Web

### ISSUE THREAD

**Issue by hasap86** [OpenSID/OpenSID#2531]
### Bagaimana alurnya sampai muncul masalah?
Tidak bisa lihat link view artikel langsung dari admin web

### Seperti apa yang diharapkan?
tambahkan aksi view link artikel webnya buka jendela baru 

### Apa yang terjadi?
tidak bisa langsung lihat artikel

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | Versi 19.12
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dicommit ke `master` melalui PR #2621
