### ISSUE TITLE
[bug] Jenis produk hukum pada Sekretariat datanya terhapus setelah melakukan proses Kosongkan Database SID

### ISSUE THREAD

**Issue by hasap86** [OpenSID/OpenSID#2532]
![produk-hukum](https://user-images.githubusercontent.com/45263721/70019952-b0f3ee80-15bd-11ea-93fb-489314ac111b.png)

### Bagaimana alurnya sampai muncul masalah?
Jenis produk hukum pada Sekretariat datanya terhapus setelah melakukan proses Kosongkan Database SID, sedangkan user tidak bisa menambah item Jenis Produk Hukum.

### Seperti apa yang diharapkan?
seharusnya proses kosongkan database, item Jenis Produk Hukum tidak ikut terhapus karena user tidak bisa menambah sendiri

### Apa yang terjadi?
tidak bisa posting Produk Hukum

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | Versi 19.12
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Telah dicommit ke master melalui PR #2534
