### ISSUE TITLE
[bug] Statistik tidak sesuai dengan jumlah penduduk sebenarnya (terpengaruhi kondisi filter penduduk)

### ISSUE THREAD

**Issue by hasap86** [OpenSID/OpenSID#2533]
### Bagaimana alurnya sampai muncul masalah?
saat kondisi user/admin melakukan filter di Data Penduduk misalnya Dusun / RW / RT, statistik di website ikut terpengaruhi jumlahnya, sehingga tidak sesuai dengan jumlah keseluruhan penduduk.

### Seperti apa yang diharapkan?
seharusnya data statistik di website tidak terpengaruhi saat kondisi admin melakukan filter penduduk

### Apa yang terjadi?
Data tidak sesuai dengan jumlah sebenarnya

### Informasi tambahan 
Kondisi Penduduk Tanpa Filter
![kondisi-tanpa-filter](https://user-images.githubusercontent.com/45263721/70021133-29f54500-15c2-11ea-8c96-354e28d79121.jpg)

Jumlah Penduduk Statistik Sesuai
![jumlah-penduduk-tanpa-filter](https://user-images.githubusercontent.com/45263721/70021166-48f3d700-15c2-11ea-992c-4accb1cfa08a.jpg)

Kondisi Penduduk Saat di Filter Dusun
![filter-dusun](https://user-images.githubusercontent.com/45263721/70021187-5dd06a80-15c2-11ea-8b1b-35434cb29cb7.jpg)

Jumlah Penduduk saat filter dusun Statistik Tidak Sesuai (mengikuti jumlah filter penduduk)
![jumlah-penduduk-saat-filter](https://user-images.githubusercontent.com/45263721/70021215-79d40c00-15c2-11ea-8914-224d7aa7c427.jpg)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | Versi 19.12
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR #2538
