### ISSUE TITLE
Widget Agenda dibuat Filter Tab Hari Ini & Akan Datang

### ISSUE THREAD

**Issue by hasap86** [OpenSID/OpenSID#2536]
### Bagaimana alurnya sampai muncul masalah?
saat ini daftar Agenda di Widget memunculkan jadwal agenda  tanpa filter hari ini atau agenda yang akan datang

### Seperti apa yang diharapkan?
adanya tab yang memisahkan antara agenda hari ini dan agenda yang akan datang, jika perlu dengan agenda sebelumnya juga

### Apa yang terjadi?
data campur antara agenda hari ini, agenda yg akan datang.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | Versi 19.12
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
