### ISSUE TITLE
Ubah Kelahiran di Laporan Bulanan menggunakan Tanggal Lapor

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#2540]
### Bagaimana alurnya sampai muncul masalah?
Statistik > Laporan Bulanan

### Seperti apa yang diharapkan?
Kelahiran pada laporan terhitung ketika penduduk melaporkan kelahiran ke desa dan bukan tanggal lahirnya

### Apa yang terjadi?
Kelahiran pada laporan dihitung menggunakan tanggal lahir bukan tanggal laporan kelahiran

### Informasi tambahan 
ketika awal bulan berjalan biasanya pemdes membuat laporan bulanan akhir bulan yang mana mencatat seluruh laporan bulan sebelumnya dan ketika ada penduduk yang melaporkan kelahiran anaknya biasanya tidak ketika lahir itu mereka melaporkan kebanyakan 1 / 2 bulan bahkan menunggu sebelum masuk TK,

![WhatsApp Image 2019-12-09 at 08 45 00](https://user-images.githubusercontent.com/35319600/70402348-ad50e380-1a65-11ea-990e-096a02eca90d.jpeg)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by balongbesuk** [comment]
karena isian datanya tidak bisa dilihat perlu komfirmasi ulang apakah memang laporan kelahiran tersebut menggunakan tanggal lahir?

**Comment by ariandii** [comment]
saat penduduk tidak melapor kelahiran sampai anaknya mau masuk sekolah, apakah anak tersebut diakui penduduk desa adalah pada saat tanggal mau urus surat menyurat?

**Comment by balongbesuk** [comment]
secara administratif harus mengurus pengajuan (update) KK dahulu, difoto saya lampirkan penduduk yang melaporkan 1 / 2 bulan lewat yang kita tahu laporan bulan tersebut sudah masuk meja kecamatan, sehingga laporan yang bersangkutan tidak masuk di laporan bulanan bulan ini

**Comment by balongbesuk** [comment]
akan lebih baik jika pengguna juga tahu isian data penduduk pada laporan bulanan tersebut, bisa kroscek dengan buku register penduduk

**Comment by balongbesuk** [comment]
https://www.facebook.com/groups/OpenSID/1415398968625080/?comment_id=1415410745290569&reply_comment_id=1416139835217660&notif_id=1577506669429025&notif_t=group_comment
