### ISSUE TITLE
Tidak Ada Fitur Menambah Peserta Program Bantuan

### ISSUE THREAD

**Issue by luckysasaja** [OpenSID/OpenSID#2542]
### Bagaimana alurnya sampai muncul masalah?
Bantuan - Rincian Program Bantuan

### Seperti apa yang diharapkan?
bisa ditambahkan
![Screenshot_1](https://user-images.githubusercontent.com/58796380/70675842-a926ff00-1ccd-11ea-8488-cbbfeb469475.jpg)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19.12
| Versi PHP        | 7.3.12
| System operasi   | WIndows 10 64 bit

**Comment by eddieridwan** [comment]
Itu karena masa program bantuannya telah berakhir.  Perpanjang masa berlakunya kalau mau menambah peserta baru. Kalau info ini belum ada di panduan, silakan anda tambahkan.
