### ISSUE TITLE
Modul : Informasi Pembangunan

### ISSUE THREAD

**Issue by muslihramin1** [OpenSID/OpenSID#2543]
### Bagaimana alurnya sampai muncul masalah? 
Seringnya pihak desa diminta laporan Progress Foto Pembangunan Desa yang terkadang waktunya sangat mendesak.

### Seperti apa yang diharapkan?
Adanya Fitur Pebangunan seperti pada Modul Galeri hanya yang ini lebih lengkap datanya, ada form untuk upload Foto  0%, 30%, 60%, 100% dilengkapi Tombol cetak atau expor file

### Apa yang terjadi?
Belum adanya Fitur Laporan Pembangunan di OpenSID

### Informasi tambahan 
Nanti kira2 hasilnya seperti ini atau yg lebih baik lagi.
![Capture](https://user-images.githubusercontent.com/51249936/70676192-e7b4bd80-1cbd-11ea-87fc-9c8fb9224070.PNG)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19.12
| Versi PHP        | 7.3
| System operasi   | Windows

**Comment by muslihramin1** [comment]
![Fitur Pembangunan1](https://user-images.githubusercontent.com/51249936/70679272-3a46a780-1cc7-11ea-9a15-286f44472bba.png)

**Comment by eddieridwan** [comment]
Ada usul tambahan supaya foto tersebut juga dikaitkan dengan lokasi di peta.

**Comment by afa28** [comment]
> Ada usul tambahan supaya foto tersebut juga dikaitkan dengan lokasi di peta.

Ini masuk di modul apa pak??

**Comment by afa28** [comment]
> Ada usul tambahan supaya foto tersebut juga dikaitkan dengan lokasi di peta.

Pak @eddieridwan , ada informasi tambahan untuk modul ini??? Sy sedang mengerjakannya, sesuai gambar di atas dan beberapa improv dr sy.

**Comment by ahmadngudi** [comment]
Kalo progres pekerjaan 0%, 50% dan 100% gimana? 
biasanya kemendes juga minta lap progres bangunan seperti itu.

**Comment by afa28** [comment]
> Kalo progres pekerjaan 0%, 50% dan 100% gimana? 
> biasanya kemendes juga minta lap progres bangunan seperti itu.

Bisa lihat rancangan table dokumentasi_pembangunan. disitu dibuat dinamis, nanti user tinggal menentukan progresnya (mau 0%, 50% atau lainnya). Untuk contoh laporannya bisa di lampirkan di sni sbgai acuan (usahakan gunakan aturan yg jelas).

**Comment by afa28** [comment]
Issue ini sy tdk lanjut krja, dgn alasan tdk ada yg menanggapi serius. Jd, sy fikir mungkin belum prioritas.

**Comment by roaddee** [comment]
ini ada source code yang biasa digunakan oleh desa Mojotrisno di Jombang dalam penggunaan peta untuk pelaporan Progress Pekerjaan Pembangunan Fisik terutama (MMS=Mojotrisno Monitoring System). 
Diberikan/dihibahkan langsung oleh pak Sekdes Mojotrisno, Bpk Miftahul.
nb:
File tidak bisa diupload, karena ukurannya melebihi ukuran yg diijinkan oleh github, akan saya upload ke gdrive dulu, nanti di share.

**Comment by RomziJazz** [comment]
> Issue ini sy tdk lanjut krja, dgn alasan tdk ada yg menanggapi serius. Jd, sy fikir mungkin belum prioritas.

Isu ini penting untuk ditindak lanjuti. Apalagi sekarang sudah jaman digital. Sebagai bentuk transparansi kepada masyarakat.

**Comment by RomziJazz** [comment]
> ini ada source code yang biasa digunakan oleh desa Mojotrisno di Jombang dalam penggunaan peta untuk pelaporan Progress Pekerjaan Pembangunan Fisik terutama (MMS=Mojotrisno Monitoring System).
> Diberikan/dihibahkan langsung oleh pak Sekdes Mojotrisno, Bpk Miftahul.
> nb:
> File tidak bisa diupload, karena ukurannya melebihi ukuran yg diijinkan oleh github, akan saya upload ke gdrive dulu, nanti di share.

Boleh share linknya dong...

**Comment by muhtar-coder** [comment]
fitur ini sangat keren,,,setiap desa di minta laporan berikut domentasi tiap semester..  moga terlaksana ,,,   dan makin mudah di akses warga melalui halaman website desa.

**Comment by muhtar-coder** [comment]
tambahan,,sediakan tombol cetak setiap unit pembangunan,foto berikut data

**Comment by yayanmulyanto20** [comment]
fitur ini sangat di butuhkan di desa

**Comment by muhtar-coder** [comment]
betul,,,,saya buka mojotrisno ternyata luar biasa,,mudah2an kita bisa

**Comment by sutaga** [comment]
Tambahan pak, untuk contoh diatas itu bisa di pakai untuk jenis pembangunan di 1 titik. Bagaimana kalau misalkan ada kegiatan pengaspalan jalan atau rabat beton yang membutuhkan dokumentasi lebih dari 3 titik (titik pertama, titik tengah, dan titik akhir). Biasanya di daerah kami permintaan laporannya seperti itu pak 🙏

**Comment by eddieridwan** [comment]
> betul,,,,saya buka mojotrisno ternyata luar biasa,,mudah2an kita bisa

@muhtar-coder @sutaga @RomziJazz @yayanmulyanto20 , mohon lampirkan contoh laporan yg diinginkan/diperlukan. Harap ingat bahwa programmer bukan perangkat desa dan sama sekali tidak mengerti dan belum pernah melihat laporan yg teman2 perlukan. **Tanggung jawab teman2 untuk menyediakan informasi yg jelas -- supaya programmer tidak keliru menerapkan.**

Tanpa contoh yg jelas, akan sangat mungkin programmer akan keliru menerapkan.

**Comment by eddieridwan** [comment]
> ini ada source code

Bung @roaddee akan sangat membantu kalau juga disediakan tangkapan layar dan laporan dari aplikasi Mojotrisno tersebut (atau akses ke demonya). Karena belum tentu source code dapat digabungkan ke OpenSID.

**Comment by eddieridwan** [comment]
> Sy sedang mengerjakannya

@afa28 Jangan lupa assign diri anda pada issue yg anda kerjakan dan geser ke kolom 'Sedang Dikerjakan' di https://github.com/OpenSID/OpenSID/projects/1. Harap kerjakan di rep premium, bukan di repo rilis umum.

**Comment by sutaga** [comment]
<img width="271" alt="SAMPLE" src="https://user-images.githubusercontent.com/68897208/102067391-96d62880-3e2d-11eb-9e65-39e21b006913.PNG">


> > betul,,,,saya buka mojotrisno ternyata luar biasa,,mudah2an kita bisa
> 
> @muhtar-coder @sutaga @RomziJazz @yayanmulyanto20 , mohon lampirkan contoh laporan yg diinginkan/diperlukan. Harap ingat bahwa programmer bukan perangkat desa dan sama sekali tidak mengerti dan belum pernah melihat laporan yg teman2 perlukan. **Tanggung jawab teman2 untuk menyediakan informasi yg jelas -- supaya programmer tidak keliru menerapkan.**
> 
> Tanpa contoh yg jelas, akan sangat mungkin programmer akan keliru menerapkan. Sekali lagi **LAMPIRKAN CONTOH LAPORAN YG DIPERLUKAN** (penjelasan/kata2 saja tidak cukup).

@eddieridwan Maksud saya seperti ini pak 🙏
![Uploading SAMPLE.PNG…]()

**Comment by RomziJazz** [comment]
![Screenshot_20201214-173638_Chrome](https://user-images.githubusercontent.com/65128302/102075048-3dbfc200-3e38-11eb-87c0-2aa78fa7f1b8.png)
Ini contoh tampilan peta

![Screenshot_20201214-173626_Chrome](https://user-images.githubusercontent.com/65128302/102075055-41534900-3e38-11eb-96a6-c450b983c7d0.png)
Dan ini detail ketika diklik benderanya...

**Comment by muhtar-coder** [comment]
untuk versi sederhana dan standart saya setuju sampel   @sutaga,,,praktis dan permintaan data oleh pendamping memang seperti itu...   tapi kalo sampai seperti mojo trisno  lebih mantap lagi....    moga segera terealisasi

**Comment by eddieridwan** [comment]
Sebagian sudah dicommit ke `rilis-dev` melalui PR https://github.com/OpenSID/premium/pull/56.

Yg belum dikerjakan akan dimasukkan ke issue terpisah:
1. menampilkan laporan di menu statis web
2. mengintegrasikan dengan Peta > Lokasi, termasuk integrasi gambar dokumentasi
