### ISSUE TITLE
Ketika Operator, Redaksi dan Kontributor membuat artikel baru, artikel langsung terbit

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#2545]
### Bagaimana alurnya sampai muncul masalah?
Di versi 19.12 ketika pengguna terdiri dari Operator, Redaksi dan Kontributor membuat artikel ternyata artikel yang dibuat langsung terbit diwebsite

### Seperti apa yang diharapkan?
Harapannya Artikel yang dibuat oleh Operator, Redaksi dan Kontributor tidak langsung terbit namun perlu verifikasi oleh admin

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | v19.12
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
@MUHAMMADRANGSEL Saat ini artikel baru oleh Administrator, Operator dan Redaksi langsung aktif. Sedangkan artikel baru oleh Kontributor tidak aktif. 

Aturan ini sudah berlaku lama. Apakah perubahan yg anda usulkan akan disetujui oleh pengguna yg lain?

Apakah yg anda usulkan, HANYA Administrator yg dapat mengaktifkan artikel? Bukankah itu juga tugas Operator dan Redaksi?

**Comment by MUHAMMADRANGSEL** [comment]
Tadi pas pelatihan untuk kontributor juga langsung aktif

Pada tanggal Min, 15 Des 2019 15.46, Eddie Ridwan <notifications@github.com>
menulis:

**Comment by eddieridwan** [comment]
@MUHAMMADRANGSEL saya baru coba di demo.opensid.my.id. Artikel buatan kontributor tidak langsung aktif. Kalau terjadi di instalasi anda, ada sesuatu lain yg bermasalah. Coba lihat isi file logs.

**Comment by MUHAMMADRANGSEL** [comment]
Ok siap dicoba bung

Pada tanggal Min, 15 Des 2019 18.37, Eddie Ridwan <notifications@github.com>
menulis:
