### ISSUE TITLE
"tanggal terdaftar pada" biodata penduduk ikut berubah mengikuti "tanggal terakhir diubah" setelah ubah biodata penduduk

### ISSUE THREAD

**Issue by rullydamara** [OpenSID/OpenSID#2552]
### Bagaimana alurnya sampai muncul masalah?
"tanggal terdaftar pada" biodata penduduk ikut berubah mengikuti "tanggal terakhir diubah" setelah ubah biodata penduduk

### Seperti apa yang diharapkan?
seharusnya "tanggal terdaftar pada" tidak ikut berubah, setelah ubah biodata penduduk.

### Informasi tambahan 
![Screenshot (940)](https://user-images.githubusercontent.com/45301948/71140721-a8014f00-2244-11ea-9ba2-88e8713ce779.png)
Tanggal terdaftar sebelum ubah biodata penduduk

![Screenshot (941)](https://user-images.githubusercontent.com/45301948/71140737-ba7b8880-2244-11ea-89a5-4c2c44e07d35.png)
setelah ubah biodata penduduk

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19.12
| Versi PHP        | 
| System operasi   |

**Comment by uncu29** [comment]
saya coba di http://demo.opensid.my.id/ dan localhost saya tidak ada masalah

**Comment by rullydamara** [comment]
saya lihat di http://demo.opensid.my.id/ menggunakan versi 19.12-pasca, apa mungkin ini sudah difix sebelumnya?
saya menggunakan 19.12.

**Comment by uncu29** [comment]
kalau begitu silahkan bapak coba gunakan versi 19.12-pasca

**Comment by rullydamara** [comment]
sudah saya ganti menggunakan 19.12-pasca masih tetap

**Comment by rullydamara** [comment]
setelah saya coba buka databasenya terdapat perbedaan pada "created at" pada database saya dengan database 19.12-pasca. Apakah ini berpengaruh ?

![Screenshot (946)](https://user-images.githubusercontent.com/45301948/71302815-6f977780-23e2-11ea-89c8-9a7fdf665b97.png)
ini struktur database "penduduk_hidup" pada database yang saya gunakan, sedangkan

![Screenshot (947)](https://user-images.githubusercontent.com/45301948/71302821-8d64dc80-23e2-11ea-97e6-5a6283d12ae1.png)
Sedangkan ini adalah hasil impor database contoh dari opensid 19.12-pasca.

**Comment by rullydamara** [comment]
Kira-kira bagaimana cara menyamakannya?

**Comment by rullydamara** [comment]
oke sudah berhasil. 
ternyata di tabel `tweb_penduduk` untuk struktur `updated_at` berbeda dengan yang contoh awal database opensid 19.12-pasca.
pada database yang saya gunakan sebelumnya nilai defautnya berisi `0000-00-00 00:00:00` setelah saya ganti mengikuti database contoh menjadi `current_timestamp()` , semua berjalan normal.

![Screenshot (948)](https://user-images.githubusercontent.com/45301948/71302989-02391600-23e5-11ea-9c51-c687579eb4e2.png)
![Screenshot (949)](https://user-images.githubusercontent.com/45301948/71302996-23016b80-23e5-11ea-8a3a-b4ec835107ef.png)

**Comment by rullydamara** [comment]
dan saya juga heran pada database yang saya gunakan. untuk struktur `updated _at` nya banyak yang hilang. salah satu contohnya di informasi publik dan laporan penduduk mandiri.

![Screenshot (943)](https://user-images.githubusercontent.com/45301948/71303042-eaae5d00-23e5-11ea-9a9e-2e7f487c81d3.png)
![Screenshot (944)](https://user-images.githubusercontent.com/45301948/71303045-f26e0180-23e5-11ea-91ce-aed7e95d9a1b.png)

**Comment by eddieridwan** [comment]
Karena database MySQL anda versi lama yg tidak didukung OpenSID. Selalu baca panduan: https://github.com/OpenSID/OpenSID/wiki/Tanya-Jawab-Install-dan-Update

@rullydamara  Issue ini bukan error. Tapi kesalahan pada instalasi. Silakan anda tutup.

**Comment by eddieridwan** [comment]
@rullydamara upgrade MySQL anda supaya minimal versi 5.6.5 (2012-04-10, Milestone 8).

**Comment by rullydamara** [comment]
Saya menggunakan versi seperti gambar dibawah.
![IMG_20191221_201752](https://user-images.githubusercontent.com/45301948/71308448-5963d880-242f-11ea-89fa-da3688b365c6.jpg)

**Comment by eddieridwan** [comment]
Minta niagahoster upgrade versi MariaDB di hosting anda. Kalau tidak bisa, pindah saja ke layanan dari OpenDesa. https://opendesa.id/mengonlinekan-opensid/

Mohon tutup issue ini, dan teruskan pertanyaan di FB atau Telegram.

**Comment by rullydamara** [comment]
oke siap

**Comment by balongbesuk** [comment]
disini mariaDBnya sudah versi 10.2.29? apakah itu belum terbaru?

**Comment by eddieridwan** [comment]
libmysql - 5.6.43 
Masalah boleh default current_timestamp lebih dari satu ada di MySQL 5.6.5 ke atas.
