### ISSUE TITLE
Penambahan Menu Untuk Posyandu Mengingat sudah mulai ada Sistem informasi Posyandu

### ISSUE THREAD

**Issue by AdnanHunaifi** [OpenSID/OpenSID#2554]
### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by uncu29** [comment]
mohon ditambah detailnya lagi bung @AdnanHunaifi sistem informasi yang seperti apa?

**Comment by AdnanHunaifi** [comment]
Misalnya Menu Layanan Posyandu Online dimana Para Kader Posyandu bisa
melakukan Laporan kegiatan Posyandu karna ada beberapa desa yang sudah
melaksakan layanan Posyandu Online

https://www.youtube.com/watch?v=y5SOWsU-4OA&t=358s

Pada tanggal Min, 22 Des 2019 pukul 15.00 Nur Hidayat <
notifications@github.com> menulis:

**Comment by andifahruddinakas** [comment]
Duplikasi https://github.com/OpenSID/OpenSID/issues/4534
