### ISSUE TITLE
Jenis Produk Hukum tidak muncul

### ISSUE THREAD

**Issue by ahmadngudi** [OpenSID/OpenSID#2557]
Ketika saya akan menambah produk Hukum, disitu tidak muncul pilihan SK Kades atau Perdes

Versi OpenSID | 19.12
Versi PHP |  
System operasi |  Windows 10

**Comment by eddieridwan** [comment]
Menggunakan tema apa? Kalau bukan tema `default` atau `hadakewa`, bukan issue untuk OpenSID.

**Comment by ahmadngudi** [comment]
menggunakan tema default pak,

**Comment by eddieridwan** [comment]
Kalau begitu anda perlu menjelaskan secara rinci langkah yg anda ikuti sampai terjadi masalah ini. Lampirkan screenshot. Karena di demo https://demo.opensid.my.id berjalan normal. Jadi masalah ada di instalasi anda atau cara penggunaan anda.

**Comment by ahmadngudi** [comment]
apakah pengaruh dengan DB dikosongkan?

**Comment by eddieridwan** [comment]
Untuk dibantu, anda perlu jelaskan langkah yg anda lakukan sebelum terjadi masalah, dan perlu lampirkan screenshot yg menunjukkan masalahnya.

**Comment by ahmadngudi** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/57133748/71463898-67787700-27ea-11ea-9ddb-e6aba640cda2.png)

**Comment by eddieridwan** [comment]
Masalah ini sudah dilaporkan sebelumnya di https://github.com/OpenSID/OpenSID/issues/2532 dan sudah dikerjakan. Silakan update ke rilis v19.12-pasca.
