### ISSUE TITLE
[bug][keuangan] data siskeudes tidak terhapus sempurna

### ISSUE THREAD

**Issue by wawan87aja** [OpenSID/OpenSID#2558]
### Bagaimana alurnya sampai muncul masalah?
saat mencoba fitur keuangan, saya beberapa kali melakukan impor database. saat saya menghapus database yang sudah pernah diimpor, lalu mengimpor database yang baru, laporan keuangan menunjukkan jumlah anggaran menjadi beberapa kali lipat dari yang seharusnya

### Seperti apa yang diharapkan?
saat menghapus data, lalu mengimpor ulang datanya, data yang lama bisa terhapus sempurna sehingga jumlah anggarannya tidak semakin bertambah

### Apa yang terjadi?
Jika database yang ada ditimpa dengan yang baru, maka tidak ada masalah. akan tetapi, saat kita menghapus database, lalu meng-impor ulang datanya, maka data yang lama akan ditambah dengan data yang baru begitu seterusnya. jadi jika kita mengimpor sebanyak lima kali maka data anggarannya akan menjadi 5 kali lipat dari yang seharusnya

### Informasi tambahan 
![Screenshot (151)_LI](https://user-images.githubusercontent.com/57819811/71455070-caf8a980-27d6-11ea-9aa7-c7374c8ad0a0.jpg)
![Screenshot (152)_LI](https://user-images.githubusercontent.com/57819811/71455078-d0ee8a80-27d6-11ea-90a4-ee1fd31fffa4.jpg)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19.12
| Versi PHP        | 7
| System operasi   | windows 10

**Comment by eddieridwan** [comment]
Sudah dicommit ke `master`.
