### ISSUE TITLE
Menu pertanahan

### ISSUE THREAD

**Issue by muhtar-coder** [OpenSID/OpenSID#2559]
### Bagaimana alurnya sampai muncul masalah?
ketika kita mengimport data pertanahan hasil yang muncul hanya menampilkan nama/nik dari penduduk desa saja

### Seperti apa yang diharapkan?
hasil import dapat menampilkan daftar nama pemilik baik itu dari penduduk desa ataupun penduduk luar desa yang memiliki tanah di desa kita.
harapanya untuk pemilik tanah yang merupakan penduduk desa akan singkron dengan database kependudukan dan pemilik tanah dari luar desa dapat juga menampilkan nama dan nik sesuai ktp pemilik tanah.

### Apa yang terjadi?
jika hal tersebut di atas dapat di perbaiki,maka data pertanahan atau pemilik tanah yang sudah ter sertifikat seluruhnya dapat ter input dalam database pertanahan.sehingga data pertanahan di desa akan terdata keseluruhan.

### Informasi tambahan

![image](https://user-images.githubusercontent.com/55665526/71463792-2bddad00-27ea-11ea-9a4c-ec070701c681.png)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by muhtar-coder** [comment]
file import data pertanahan sudah sesuai dengan contoh yang tersedia di opensid.

No | NIK | Nomor Persil | persil_jenis_id | id_clusterdesa | Luas | Kelas | No SPPT/PBB | persil_peruntukan_id
-- | -- | -- | -- | -- | -- | -- | -- | --

**Comment by muhtar-coder** [comment]
sesuai Permen No 47 Tahun 2016 
pemerintah desa di wajibkan membuat laporan data tanah di desa seperti tabel berikut di bawah ini dan mungkin lebih baik nya hasil print out opensid sudah sesuai dengan perintah permen no 47 tahun 2016 tersebut.tabel nya adalah sebagai berikut :

![image](https://user-images.githubusercontent.com/55665526/71465049-17031880-27ee-11ea-9a4e-b988380fb69c.png)

**Comment by muhtar-coder** [comment]
@eddieridwan 
@happyagung25 
@roaddee 
@ariandii 
@uncu29 
@dikisiswanto

**Comment by Fandha** [comment]
Bisakah untuk kelas tanah diberikan opsi untuk menu penambahan dan pengurangannya. Contoh ditempat kami menggunakan kelas tanah dari kemenkeu kelas bumi dan bangunan.
Dan bisakah dilengkapi dengan perekaman peta gpsnya agar manajemen pertanahan dapat seperti di BPN.

**Comment by eddieridwan** [comment]
@Fandha sebaiknya buat issue baru. Batasi satu issue hanya berisi satu permintaan. Dan selalu lakukan berdasarkan fitur yg ada di OpenSID versi terbaru. Di v20.08, data pertanahan disimpan dalam konteks buku C-Desa. Jadi usulan anda di issue baru perlu menjelaskan sesuai konteks fitur yg sdh diterapkan. Dan selalu sediakan info sejelas mungkin. Lampirkan contoh menu atau laporan yg dapat membantu apa yg anda inginkan. Jadi misalnya, di issue mengenai kelas tanah, sebaiknya anda lampirkan kelas tanah dari Kemenkeu yg anda maskud. 

Usulan yg tidak jelas atau tdk lengkap sulit untuk diterapkan.

**Comment by Fandha** [comment]
Baik mas, terima kasih...

**Comment by mizwaruddin** [comment]
@afa28 bisa diclose karena modul pertanahan sudah diganti.
