### ISSUE TITLE
Tampilan Mapbox Streets Satellite 

### ISSUE THREAD

**Issue by R4HMAT** [OpenSID/OpenSID#2560]
### Bagaimana alurnya sampai muncul masalah?
Tampilan Mapbox Streets Satellite masih tampilan lama.
seperti Screnshot Ini.
![image](https://user-images.githubusercontent.com/43318683/71539074-615cd480-2969-11ea-866b-a83546e6e3a6.png)
tampilan google Map seperti Screnshot Ini.
![image](https://user-images.githubusercontent.com/43318683/71539083-894c3800-2969-11ea-820a-3d4fc7f33b39.png)

### Seperti apa yang diharapkan?
supaya tampilan Mapbox Streets Satellite di Aplikasi OpenSid tampilan terbaru seperti di Google Map Google.

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19.12 Pasca
| Versi PHP        | 
| System operasi   |

**Comment by fusionid** [comment]
Konten dan update peta Mapbox Streets Satellite di luar scope OpenSID. 
Silahkan lihat di https://www.mapbox.com/ untuk keterangan lebih lanjut.
