### ISSUE TITLE
Rubah pencarian penduduk menggunakan Ajax seperti di surat

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#2561]
### Bagaimana alurnya sampai muncul masalah?
kependudukan > penduduk > cari...

### Seperti apa yang diharapkan?
rubah fungsi pencarian penduduk seperti pada surat

### Apa yang terjadi?
kendala ini terjadi ketika penduduk berjumlah banyak dengan huruf awalan yang sama fungsi autocomplete terkadang membuat browser menjadi freze / hank

![Untitled](https://user-images.githubusercontent.com/35319600/71557079-a2d9a680-2a73-11ea-802f-67c7ba0d6702.jpg)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dicommit ke `master`.

Perlu diingat, kotak cari bukan untuk mencari SATU penduduk tertentu, tetapi berperan sebagai penyaring sebagaimana halnya penyaringan menggunakan jenis kelamin dan wilayah.  Yaitu fungsinya berbeda dengan di form surat -- di surat memang tujuannya untuk memilih SATU penduduk tertentu.
