### ISSUE TITLE
Error Ketika Memasukan Pengguna baru Setelah Kosongkan DB

### ISSUE THREAD

**Issue by andryrukandifauzy** [OpenSID/OpenSID#2562]
### Bagaimana alurnya sampai muncul masalah?
ketika mendaptarkan pengguna baru muncul error seperti yang di lampirakan ...
![errror](https://user-images.githubusercontent.com/42363553/71569488-13c79f80-2b02-11ea-9ba9-6ea874361b8c.png)
![errro2r](https://user-images.githubusercontent.com/42363553/71569493-1a561700-2b02-11ea-942d-6aa19a9c49dc.png)

### Seperti apa yang diharapkan?
tidak terjadi error ketika menambahkan pengguna baru 

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | lastest
| Versi PHP        | 
| System operasi   | linux

**Comment by andryrukandifauzy** [comment]
![Screenshot_7](https://user-images.githubusercontent.com/42363553/71571192-b6d0e700-2b0b-11ea-8181-e902c75db483.png)
Bahkan sebelum kosongkan db pun tetap error

**Comment by eddieridwan** [comment]
Sudah diperbaiki sebelumnya di versi 19.12-pasca.
