### ISSUE TITLE
Tambah : Pilih Pencarian "Kategori" pada halaman Informasi Publik.

### ISSUE THREAD

**Issue by HerryWanda** [OpenSID/OpenSID#2563]
Tambakan pilihan pencarian "KATEGORI" pada halaman informasi publik :
Kategori : 
1. Informasi Berkala
2. Informasi Setiap Saat
3. Informasi Serta Merta
4. Informasi dikecualikan.

yang sudah ada sekarang  "tampilan entri " dan pencarian.
### Bagaimana alurnya sampai muncul masalah?
1. Jika informasi publik sudah banyak , maka kita akan kesulitan mencari/memilah/menampilkan jenis "kategori" informasi  dihalaman informasi publik tersebut.

### Seperti apa yang diharapkan?
- Ditambahan pilihan pencarian berdasarkan ketegori : 
1. Informasi Berkala
2. Informasi Setiap Saat
3. Informasi Serta Merta
4. Informasi dikecualikan.

Sehingga kita mudah memilah dan menampilkan informasi publik berdasarkan kategori.

### Informasi tambahan 
Gambaran penambahan pilihan kategori :
![issue Informasi Publik](https://user-images.githubusercontent.com/32125282/71573672-b76f7a80-2b17-11ea-9b1f-fd0251d379ca.jpg)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by uncu29** [comment]
sepertinya sama dengan issue ini da #2429

**Comment by afa28** [comment]
Duplicate #2563
