### ISSUE TITLE
[Bumindes] Tambahkan "Link dokumen" di Menu Sekretariat pada sub menu"Informasi Publik"

### ISSUE THREAD

**Issue by HerryWanda** [OpenSID/OpenSID#2565]
### Bagaimana alurnya sampai muncul masalah?
1. Dokumen (file.pdf) tidak bisa di import jika ukurannya besar melebihi 50 Mb.

### Seperti apa yang diharapkan?
1. Diharapkan dengan penambahan kolom "link dokumen" tidak memberatkan saat upload dokumen dan space hosting jadi ringan.
2. Dengan adanya link dokumen tersebut, penyimpanan dokumen yg besar kita simpan di google drive.

### Apa yang terjadi?
1. File dokumen yang besar tidak bisa di upload pada saat menambahkan dokumen informasi publik (keluar peringatan melebihi maksimum)

### Informasi tambahan 
![sekretaria](https://user-images.githubusercontent.com/32125282/71574110-dbcc5680-2b19-11ea-8fb8-8a1c13b969b8.jpg)
| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 12.Pasca
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
@HerryWanda , maksudnya dokumennya tidak diunggah ke OpenSID, tetapi ada di tempat lain, seperti google drive?

**Comment by HerryWanda** [comment]
Iya sperti itu juga bisa pak...
Apa itu bisa dijadikan solusi jika file dokumen informasi publik ada yang besar pak...
Kalo gak solusinya bisa juga kapasitas untuk upload dokumen kita perbesar...
Gimana baiknya aja pak...
Untuk penggunaan sekarang saya suah terapkan dan berjalan normal, cuma file yang besar aja yang tidak bisa bisa upload..

**Comment by eddieridwan** [comment]
Batas ukuran upload file di setting di `php.ini`. Bukan di OpenSID. Solusinya sama dengan error pada waktu impor data Excel. Lihat https://github.com/OpenSID/OpenSID/wiki/Error-Import-Excel.

**Comment by mizwaruddin** [comment]
@afa28 apakah solusi dari Bang Eddie sdh menjawab issue ini?

**Comment by afa28** [comment]
> @afa28 apakah solusi dari Bang Eddie sdh menjawab issue ini?

Mungkin solusi selain itu, selain upload dokumen sediakan jg upload berupa url sj.

**Comment by kidnef10** [comment]
apakah sudah bisa embed dari google drive untuk file?

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1322
