### ISSUE TITLE
Artikel statis  "Agenda" tidak bisa dibuka pada artikel terbaru/terkini.

### ISSUE THREAD

**Issue by HerryWanda** [OpenSID/OpenSID#2566]
### Bagaimana alurnya sampai muncul masalah?
1. Membuat artikel statis "Agenda" pada artikel web, setelah disimpan maka artikel tersebut akan tampil di artikel terbaru/terkini. tapi setelah artikel tersebut di klik maka muncul error "MAFF DATA TIDAK DITEMUKAN"
![ER](https://user-images.githubusercontent.com/32125282/71574489-78432880-2b1b-11ea-85cf-348d6c0b5ffa.jpg)

TAPI :
Jika artikel tersebut di klik pada Widget Agenda maka artikel tersebut normal dan bisa dibuka.
![AART](https://user-images.githubusercontent.com/32125282/71574611-159e5c80-2b1c-11ea-8d64-b73d0bee0b7e.jpg)

### Seperti apa yang diharapkan?
yang diharapakan, setelah di klik "selengkapnya" artikel tampil seperti biasanya.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 12.pasca
| Versi PHP        | 
| System operasi   |

**Comment by ZER07URN** [comment]
1. Kenapa Agenda Yang muncul beranda web muncul pesan error karena agenda tidak menyimpan slug pada database.

2. Sedangkan pada widget muncul karena ditampilkan berdasarkan id_artikel bukan menggunakan slug.

Solusi sederhanannya, tambahkan slug saat menyimpan agenda.

**Comment by ZER07URN** [comment]
Coba perbaiki codenya di donjo-app -> models -> web_artikel_model.php

cari code : "$data['slug'] = $slug; // insert slug"
keluarkan dan simpan di baris atas if ($cat == AGENDA)

atau bisa dengan cari lain

**Comment by WAHYUDIK** [comment]
bukankah dulu rencana untuk agenda tidak dibuat otomatis muncul di artikel?

**Comment by ZER07URN** [comment]
@WAHYUDIK kurang tau mas, tapi sampai sekarang Agenda(1000) masih tetap muncul di artikel. Harusnya di beri pengecualian kalau tdk mau ditampilkan.

**Comment by eddieridwan** [comment]
Sudah dicommit melalui PR #2568
