### ISSUE TITLE
Setelah Update ke versi 20.01 Produk Hukum tetap tidak muncul

### ISSUE THREAD

**Issue by ahmadngudi** [OpenSID/OpenSID#2567]
### Bagaimana alurnya sampai muncul masalah?

di versi 19.12 kosongkan DB dan produk hukum tidak ada pilihan SK Kades dan perdes dan setelah di update ke versi 20.01 masih tidak mau muncul
### Informasi tambahan 

![Screenshot_4](https://user-images.githubusercontent.com/57133748/71640704-ceea6700-2cc1-11ea-9df0-22e49e33904c.png)

**Comment by fusionid** [comment]
1. Pengaturan -> Database -> Backup/Restore
2. Pilih File Sql : contoh_data_awal_20200101.sql
3. Restore
4. Setelah proses Restore berhasil lanjut dengan proses "Kosongkan DB"

**Comment by ahmadngudi** [comment]
setelah restore contoh_data_awal_20200101.sql malah begini 
![Screenshot_5](https://user-images.githubusercontent.com/57133748/71643007-3b775d00-2ce6-11ea-8cfe-7940e025fbe0.png)

**Comment by ZER07URN** [comment]
http://localhost/xxxxxxx/index.php/first

**Comment by ahmadngudi** [comment]
> 1. Pengaturan -> Database -> Backup/Restore
> 2. Pilih File Sql : contoh_data_awal_20200101.sql
> 3. Restore
> 4. Setelah proses Restore berhasil lanjut dengan proses "Kosongkan DB"

**Comment by ahmadngudi** [comment]
1. Pengaturan -> Database -> Backup/Restore
2. Pilih File Sql : contoh_data_awal_20200101.sql
3. Restore
4. Setelah proses Restore berhasil lanjut dengan proses "Kosongkan DB"

kalau mengikuti cara diatas berrti data desa kita hilang?

**Comment by tink-gal** [comment]
Nah ini berhasil...
![Untitled](https://user-images.githubusercontent.com/58603107/71675552-92496900-2db0-11ea-9cda-081134dcefee.png)
Nah.. pangkal solusi sementara ...  untuk solusi permanen nunggu dari developernya. Ada di file /themes/nama_tema/layout/halaman_statis.tpl.php
silahkan ambil di sini !
[https://github.com/tink-gal/OpenSID-me/blob/master/halaman_statis.tpl.php](url)

**Comment by tink-gal** [comment]
[https://github.com/tink-gal/OpenSID-me/blob/master/halaman_statis.tpl.php](https://github.com/tink-gal/OpenSID-me/blob/master/halaman_statis.tpl.php)

**Comment by ahmadngudi** [comment]
ini thema apa ya pak? saya pakai tema default

**Comment by tink-gal** [comment]
> 
> 
> ini thema apa ya pak? saya pakai tema default
Tema apapun: default,cosmos, netra, hadakewa, labs dll...
ada banyak perbedaan di kodingnya kecuali koding 
`<?php $this->load->view($halaman_statis); ?>`

**Comment by uncu29** [comment]
> 1. Pengaturan -> Database -> Backup/Restore
> 2. Pilih File Sql : contoh_data_awal_20200101.sql
> 3. Restore
> 4. Setelah proses Restore berhasil lanjut dengan proses "Kosongkan DB"
> 
> kalau mengikuti cara diatas berrti data desa kita hilang?

hilng, kemudian restore database yg telah dibackup!

**Comment by ahmadngudi** [comment]
> > 1. Pengaturan -> Database -> Backup/Restore
> > 2. Pilih File Sql : contoh_data_awal_20200101.sql
> > 3. Restore
> > 4. Setelah proses Restore berhasil lanjut dengan proses "Kosongkan DB"
> > 
> > kalau mengikuti cara diatas berrti data desa kita hilang?
> 
> hilng, kemudian restore database yg telah dibackup!


sudah di restore sesuai pentunjuk di atas, hasilnya tetep pak, perdes dan sk kades tidak muncul

**Comment by uncu29** [comment]
> > > 1. Pengaturan -> Database -> Backup/Restore
> > > 2. Pilih File Sql : contoh_data_awal_20200101.sql
> > > 3. Restore
> > > 4. Setelah proses Restore berhasil lanjut dengan proses "Kosongkan DB"
> > > 
> > > kalau mengikuti cara diatas berrti data desa kita hilang?
> > 
> > 
> > hilng, kemudian restore database yg telah dibackup!
> 
> sudah di restore sesuai pentunjuk di atas, hasilnya tetep pak, perdes dan sk kades tidak muncul

apakah sudah mengikuti cara diatas?

**Comment by ahmadngudi** [comment]
> > > > 1. Pengaturan -> Database -> Backup/Restore
> > > > 2. Pilih File Sql : contoh_data_awal_20200101.sql
> > > > 3. Restore
> > > > 4. Setelah proses Restore berhasil lanjut dengan proses "Kosongkan DB"
> > > > 
> > > > kalau mengikuti cara diatas berrti data desa kita hilang?
> > > 
> > > 
> > > hilng, kemudian restore database yg telah dibackup!
> > 
> > 
> > sudah di restore sesuai pentunjuk di atas, hasilnya tetep pak, perdes dan sk kades tidak muncul
> 
> apakah sudah mengikuti cara diatas?

sudah pak, mohon solusinya.
