### ISSUE TITLE
Buat User untuk Kepala Dusun

### ISSUE THREAD

**Issue by rullydamara** [OpenSID/OpenSID#2572]
### Bagaimana alurnya sampai muncul masalah?
Pembuatan User Kepala Dusun untuk login ke OpenSID.

### Seperti apa yang diharapkan?
Kepala Dusun dapat login ke OpenSID dan hanya dapat mengakses data kependudukan sesuai dengan wilayahnya.

Misalkan Kepala Dusun 01 hanya dapat mengakses, memperbarui, menambah data kependudukan pada Kepala Dusun 01. serta diharapkan Kepala Dusun dapat mengakses menu pelayanan surat sesuai dengan wilayahnya masing-masing.

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.1
| Versi PHP        | 
| System operasi   |

**Comment by ZER07URN** [comment]
Silahkan tunggu update rbac

**Comment by afa28** [comment]
Duplicate of #1994
