### ISSUE TITLE
File tidak berisi data Siskeudes

### ISSUE THREAD

**Issue by will2469** [OpenSID/OpenSID#2573]
### Bagaimana alurnya sampai muncul masalah?
Saya mencoba untuk mengupload database siskeudes yang telah saya eksport ke format csv, namun terdapat notifikasi seperti gambar berikut :

![image](https://user-images.githubusercontent.com/17868552/72004447-09ce3b00-327e-11ea-8fb1-ef7ed1cbe3db.png)

Notifikasi itu juga muncul saat saya mencoba upload database contoh yang ada di panduan opensid..

### Seperti apa yang diharapkan?
Mohon untuk dapat membantu permasalahan tersebut

### Apa yang terjadi?
 Muncul Notifikasi "File tidak berisi data Siskeudes" saat import database siskeudes

### Informasi tambahan 
1. Versi siskeudes yang digunakan V2.0 R2.0.2
2. Saya sudah memeriksa struktur masing-masing file csv contoh dan csv hasil export saya dan tidak ada perbedaan struktur database

  
| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.01
| Versi PHP        | 7.2.24
| System operasi   | Linux comet.jetorbit.net 3.10.0

**Comment by fusionid** [comment]
Pada file CSV hasil konversi MDE melalui MDBTOOLS, Table Header-nya tidak dilengkapi dengan Double Quote ("), maka ketika import data ke OpenSID akan mengalami kegagalan. Ini hanya terjadi di server dgn versi PHP 7.x dan jika datanya berisi beberapa desa, sedangkan di PHP 5.x akan berjalan normal.
Script import data sudah diperbaiki di commit https://github.com/OpenSID/OpenSID/commit/3d9dd97aaaebb2893a3a49e363f27e91e8add445

**Comment by will2469** [comment]
commit nya berhasil terimakasih.. sudah saya coba untuk php 7.2.24...
