### ISSUE TITLE
[Layanan Mandiri] Pendaftaran penduduk secara mandiri

### ISSUE THREAD

**Issue by azrockmonster** [OpenSID/OpenSID#2574]
### Bagaimana alurnya sampai muncul masalah?

Ketika ada masyarakat yang datanya belum terdaftar di database kantor desa, maka masyarakat bisa.mendaftarkan dirinya melalui website desa. Dengan melampirkan photo diri dan photo KK mereka.
Tentunya administratorlah yg akan menyetujui atau menplak pendaftaran tersebut. 

### Seperti apa yang diharapkan?
Verifikasi dan validasi data penduduk bisa.lebih cepat dan efisien. 

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by sukrimalendra** [comment]
Usulan ini bagus. Kebetulan saya di desa sedang melakukan pendataan penduduk untuk dijadikan sebagai Database di aplikasi OpenSid karena kami tidak diberikan data penduduk oleh Dukcapil di kabupaten saya. Saya menggunakan google form yang isiannya saya sesuaikan dengan isian di **FormatImportExcel** dan saya rekrut pendata di masing2 dusun untuk mendata penduduk kami, namun kendalanya banyak data penduduk yang ganda dan belum lagi data hasil pendataan di google form harus dicomvert ke **FormatImportExcel**. Mohon untuk dibuatkan sejenis form input data penduduk yang bisa diakses untuk masyarakat melalui website desa. Terimakasih

**Comment by afa28** [comment]
Pak @eddieridwan, apakah ini perlu???

**Comment by eddieridwan** [comment]
Duplikat https://github.com/OpenSID/OpenSID/issues/1760
