### ISSUE TITLE
Menu Bantuan

### ISSUE THREAD

**Issue by R4HMAT** [OpenSID/OpenSID#2577]
### Bagaimana alurnya sampai muncul masalah?
di Menu Bantuan 
Sasaran Peserta | :  Keluarga / KK
hasil unduhan tidak sesuai dengan data yang ada di data BIs untuk Kolom NIK tapi yang terisi Nomor KK
![klh2](https://user-images.githubusercontent.com/43318683/72203462-83447400-349e-11ea-85bf-69d74485ddc0.png)

Hasil unduhan format Excel
![klh3](https://user-images.githubusercontent.com/43318683/72203465-8ccddc00-349e-11ea-9a91-0a4941abeedf.png)
### Data di Penduduk
![klh4](https://user-images.githubusercontent.com/43318683/72203532-52b10a00-349f-11ea-8842-0a5032dcd6a8.png)

### Seperti apa yang diharapkan?
Supaya data yang ada di data bis dengan isian Kolom NIK isian data sama.

### Informasi tambahan 
Versi di demo.opensid

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20..01
| Versi PHP        | 
| System operasi   |

**Comment by ZER07URN** [comment]
NIK yang ada di identitas kartu perserta di input manual tdk otomatis, kalau salah mungkin salah input

**Comment by ianskids** [comment]
Karena Sasaran Peserta adalah Keluarga / KK jadiNIK  yang di pakai no KK

**Comment by afa28** [comment]
berkaitan dgn #2880

**Comment by afa28** [comment]
Sudah dicommit ke master melalui PR #2887
