### ISSUE TITLE
opensid tap latlong gps dgn google map dan openstreet realtime

### ISSUE THREAD

**Issue by andreyuberta** [OpenSID/OpenSID#2578]
### Bagaimana alurnya sampai muncul masalah?
karna familiar dgn google map dan ingin compare

### Seperti apa yang diharapkan?
1.bisakah dua berjalan dan boleh support sourcenya abang smua utk google map agar ketika digunakan di android bisa di tab oleh user utk alamat rumah penduduk dgn latlong
2. bisakah openstreet otomatis gps menandakan latlong penduduk

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by andreyuberta** [comment]
![save alamat penduduk google map dan openstreet realtime](https://user-images.githubusercontent.com/59838011/72276844-6a38f000-3663-11ea-89e6-1e33a2a47062.png)

**Comment by fusionid** [comment]
Sudah dicommit ke master melalui PR #2594
