### ISSUE TITLE
Bug: Error pada tombol Kartu Rumah Tanggga

### ISSUE THREAD

**Issue by metalab25** [OpenSID/OpenSID#258]
Terjadi error pada saat proses pembuatan/cetak Kartu Rumah Tangga, setelah klik tombol "Kartu rtm" malah membuka tab baru dan error page

<img width="931" alt="kartu_rtm" src="https://cloud.githubusercontent.com/assets/249563/26562807/48084f16-450d-11e7-9b75-39607c3f5eab.png">

![2017-01-14 1](https://cloud.githubusercontent.com/assets/19917739/21942219/0c396fc2-da07-11e6-8aeb-9d63cafcb444.png)

versi OpenSID ditemukannya masalah : OpenSID 1.8 (sepertinya ini masalah dari SID-CRI sebab dulu pernah coba di SID-CRI juga error)

**Comment by pandigresik** [comment]
sepertinya file view/sid/kependudukan/kartu_rtm.php memang belum ada, kalau memang perlu dibuatkan harusnya tampilannya seperti apa ?

**Comment by MUHAMMADRANGSEL** [comment]
sekarang di SID 3.10 rilis terbaru sudah ada jadi tinggal disesuaikan saja scripnya dengan tampilan seperti gambar dibawah ini : 

![image](https://user-images.githubusercontent.com/25834335/31278227-0b9d525e-aa59-11e7-854a-9f8343bae1a7.png)

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
