### ISSUE TITLE
Sebagai contoh, berikut ini pasangan blanko untuk kepergian/kedatangan antar desa dalam satu kecamatan.

### ISSUE THREAD

**Issue by Kedung802** [OpenSID/OpenSID#2583]
Sebagai contoh, berikut ini pasangan blanko untuk kepergian/kedatangan antar desa dalam satu kecamatan.

![f 1-25 surat pindah](https://cloud.githubusercontent.com/assets/249563/22870131/ae1d2382-f209-11e6-8c14-e212f7825cca.jpg)
![f 1-27 surat pindah datang](https://cloud.githubusercontent.com/assets/249563/22870132/ae1fd2da-f209-11e6-8126-89b49cf1b8bc.jpg)

_Originally posted by @eddieridwan in https://github.com/OpenSID/OpenSID/issues/282#issuecomment-279286853_

**Comment by balongbesuk** [comment]
![Untitled](https://user-images.githubusercontent.com/35319600/72658284-4cf87e80-39e1-11ea-9d75-b7cab1ebec7b.jpg)

ini sudah dicoba?

**Comment by mizwaruddin** [comment]
@afa28 sudah ada di master.
