### ISSUE TITLE
Tetap di Form Daftar Anggota Keluarga

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#2584]
### Bagaimana alurnya sampai muncul masalah?
Buka Kependudukan > keluarga > Rincian Anggota Keluarga > Tambah Anggota > Pilih Anggota yang ingin ditambah dan status hubungannnya > simpan 

### Seperti apa yang diharapkan?
ketika menambah banyak anggota keluarga dan disimpan tampilan tetap Daftar Anggota Keluarga dan tidak kembali ke Data Keluarga agar tidak mencari data keluarga yang akan ditambahkan lagi

### Apa yang terjadi?
Ketika menambah anggota keluarga dan disimpan form di kembalikan ke Data keluarga sehingga user mencari data keluarga yg akan ditambahkan lagi

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR #2587
