### ISSUE TITLE
pdf buku buku pelajaran sekolah di open desa

### ISSUE THREAD

**Issue by andreyuberta** [OpenSID/OpenSID#2585]
### Bagaimana alurnya sampai muncul masalah?
perlunya akses massal ke sistem user opensid oleh warga sehingga pengguna opendesa merasakan memiliki opensid 

### Seperti apa yang diharapkan?
ada pdf buku buku pelajaran dan bacaan bermutu lainnya utk di download warga, bedah buku online sbg fitur

### Apa yang terjadi?
penambahan kecerdasan dan minat baca pelajar di desa

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by uncu29** [comment]
silahkah lebih kreatif pada website anda bung @andreyuberta , website bisa upload pdf

**Comment by andreyuberta** [comment]
terimakasih uncu29,sekalian berbagi ide bg uncu....

**Comment by uncu29** [comment]
siap bung @andreyuberta
