### ISSUE TITLE
Nama kepala dusun tidak tampil

### ISSUE THREAD

**Issue by lastingdone** [OpenSID/OpenSID#2589]
### Bagaimana alurnya sampai muncul masalah?
Saat membuka page wilayah administratif nama kepala dusun tidak tampil

### Seperti apa yang diharapkan?
nama kepala dusun tampil

### Apa yang terjadi?
![image](https://user-images.githubusercontent.com/56072113/72611087-bcc42600-395b-11ea-8a42-0929416a4130.png)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by balongbesuk** [comment]
sy cb di website demo dengan tema bawaan opensid ada, mungkin ini masalah tema natra, silakan laporkan ke githubnya masing masing 

-close issue
