### ISSUE TITLE
mohon ditambahkan format surat keterangan izin orangtua/suami/istri

### ISSUE THREAD

**Issue by lemahayu** [OpenSID/OpenSID#259]
Fungsi surat ini bukan hanya untuk warga yang akan bekerja keluar negeri tapi juga untuk yang bekerja di dalam negeri. bentuk format pada setiap Desa di Indramayu beragam tapi tujuan dari isi suratnya pasti sama, contoh format yang biasa dipakai di Desa saya dibawah ini 
![izin orangtua2](https://cloud.githubusercontent.com/assets/22955154/21959722/d041ce22-db02-11e6-87d3-a9a78770817e.JPG)

**Comment by eddieridwan** [comment]
Dari #603:
Desa kami sering membuat Surat Keterangan Izin Suami/Istri untuk masyarakat yang bepergian ke luar negeri untuk bekerja sebagai TKI. Oleh karena itu mohon dibuatkan Surat Keterangan Izin Suami/Istri seperti pada lampiran dibwah ini. 
[ket. izin adi.pdf](https://github.com/eddieridwan/OpenSID/files/1270071/ket.izin.adi.pdf)

**Comment by abieroni** [comment]
Apakah ini sudah di kerjakan, hanya mengingatkan saja. Seandainya saya ahli dalam bidang ini, saya akan kerjakan project ini.

**Comment by MUHAMMADRANGSEL** [comment]
Kami di Lombok Timur Sudah lama menggunakannya dan scripnya 
[surat_izin_orangtua_suami_istri.zip](https://github.com/OpenSID/OpenSID/files/1454306/surat_izin_orangtua_suami_istri.zip)

**Comment by eddieridwan** [comment]
@MUHAMMADRANGSEL, @lemahayu  apakah yg memberi izin dan yang diberi izin selalu warga desa? Yaitu selalu dapat kita ambil datanya dari database?

**Comment by MUHAMMADRANGSEL** [comment]
Ya yg dari database mas eddie

Pada tanggal 10 Nov 2017 10:11, "Eddie Ridwan" <notifications@github.com>
menulis:

**Comment by MUHAMMADRANGSEL** [comment]
yang memberi izin dan yg diberi izin diambil dari database

Pada tanggal 10 Nov 2017 11:47, "MUHAMMAD SPD" <muhammadrangsel@gmail.com>
menulis:

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.

Nanti diusahakan untuk membatasi pilihan penduduk yang diberi izin berdasarkan hubungan dengan pemberi izin. Misalnya, jika pemberi izin adalah selaku orang tua, maka pilihan yang diberi izin cukup daftar anaknya.

**Comment by eddieridwan** [comment]
Ok, sekarang pilihan penduduk yang diberi izin dibatasi berdasarkan hubungan dengan pemberi izin. Misalnya, jika pemberi izin adalah selaku orang tua, maka pilihan yang diberi izin cukup daftar anaknya.

**Comment by MUHAMMADRANGSEL** [comment]
perlu perbaikan sedikit
![screenshot 2017-11-12 18 57 51](https://user-images.githubusercontent.com/25834335/32698323-b6279cf0-c7de-11e7-8fe7-4bc4624a4c3d.png)
![screenshot 2017-11-12 19 06 24](https://user-images.githubusercontent.com/25834335/32698324-b689daa0-c7de-11e7-8ae0-a78bf6cc4137.png)

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
