### ISSUE TITLE
Map nyangkut pas loading

### ISSUE THREAD

**Issue by lastingdone** [OpenSID/OpenSID#2590]
### Bagaimana alurnya sampai muncul masalah?
saat refresh page map masih ada

### Seperti apa yang diharapkan?
hanya loading yang tampil

### Apa yang terjadi?
![image](https://user-images.githubusercontent.com/56072113/72611490-dd40b000-395c-11ea-914d-84a689adb1aa.png)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by uncu29** [comment]
coba pakai tema lain bung @lastingdone

**Comment by uncu29** [comment]
sebelum mengirim issue silahkan anda coba login di demo.opensid.my.id jika ditemukan error baru anda kirim issue

**Comment by balongbesuk** [comment]
ini memang sejak lama masalah tema natra, silakan laporkan ke githubnya 

-close issue
