### ISSUE TITLE
hanya Admin yang boleh mengunduh / mencetak data penduduk

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#2591]
### Bagaimana alurnya sampai muncul masalah?
masuk dengan pengguna selain admin buka menu kependudukan > pilih aksi lain > cetak / unduh

### Seperti apa yang diharapkan?
pengguna selain admin dilarang melakukan aksi unduh / cetak data penduduk

### Apa yang terjadi?
pengguna selain admin bisa melakukan aksi unduh / cetak data penduduk

### Informasi tambahan 
agar admin memiliki kontrol penuh data kependudukannya

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Selama ini operator dapat mengakses kebanyakan menu, kecuali menghapus data. Lihat `user_model.php` untuk melihat daftar hak akses yg ada. Juga http://bit.ly/2Vhqmyz yg dulu sudah disepakati panjang lebar. 

Kalau anda mengusulkan diiubah, harus melalui persetujuan pengguna yg lain. Yaitu anda harus mengusulkan perubahan pada http://bit.ly/2Vhqmyz dan mendapatkan persetujuan dari kebanyakan pengguna yg lain.

**Comment by balongbesuk** [comment]
yang sy permasalahkan Fungsi unduh dan cetak data penduduk yang "memungkinkan" pengguna selain admin untuk dapat menjalankannya

untuk hak akses sy tetap setuju dengan yang ada di kesepakatan manun untuk fitur cetak data unduh dan cetak data penduduk, saya rasa rawan untuk disalah gunakan,

**Comment by balongbesuk** [comment]
sedang dikerjakan di RBAC
