### ISSUE TITLE
Menu Navigasi Hilang Pada Rincian Data Peserta Program Bantuan

### ISSUE THREAD

**Issue by ZER07URN** [OpenSID/OpenSID#2596]
### Bagaimana alurnya sampai muncul masalah?
Ketika Beralih Kehalaman Rincian Data Peserta Program Bantuaan, Menu Navigasi Menghilang

![bugs](https://user-images.githubusercontent.com/7290110/72754340-1c3f6180-3bfa-11ea-82c2-095bc760a51a.png)

### Seperti apa yang diharapkan?
Menu Navigasi Menghilang Tetap Dimunculkan
![bugs2](https://user-images.githubusercontent.com/7290110/72754357-22354280-3bfa-11ea-8229-fb36be3d3c27.png)

### Apa yang terjadi?
Menu Navigasi Dapat Digunakan

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.01-pasca
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR #2608
