### ISSUE TITLE
Artikel Agenda tidak menampilkan informasi yang lengkap pada detail artikel Agenda

### ISSUE THREAD

**Issue by hasap86** [OpenSID/OpenSID#2597]
### Bagaimana alurnya sampai muncul masalah?
saat membuka artikel Agenda baik dari beranda maupun dari Widget, tidak menampilkan informasi yang lengkap sesuai isian artikel, seperti Waktu, Lokasi & Koordinator tidak tampil.

### Seperti apa yang diharapkan?
Menampilkan Waktu, Lokasi & Koordinator pada detail artikelnya sesuai isian pada form artikel agenda seperti ditampilkan pada widget.

### Apa yang terjadi?
informasi kurang lengkap, tidak sesuai isian artikel agenda.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    |  OpenSID 20.01-pasca
| Versi PHP        | PHP Version 7.1.33
| System operasi   | Linux

**Comment by ZER07URN** [comment]
Mungkin ada yang bisa dengan cara lain

**Comment by ZER07URN** [comment]
![Untitled](https://user-images.githubusercontent.com/7290110/72885497-a5f64880-3d3a-11ea-9e22-2eb0203a79e6.png)

Hanya untuk tema hadekwa untuk tema yang lain silahkan tambahkan code berikut setelah isi artikel atau sebelum komentar.


<?php if($single_artikel['id_kategori'] == 1000) : ?>
			<?php foreach($detail_agenda AS $data): ?>
				<p>TANGGAL KEGIATAN : <?= tgl_indo2($data['tgl_agenda'])?>
				<p>KOORDINATOR KEGIATAN : <?= $data['koordinator_kegiatan']?>
				<p>LOKASI KEGIATAN : <?= $data['lokasi_kegiatan']?>	
			<?php endforeach; ?>
		<?php endif; ?>

**Comment by ZER07URN** [comment]
tampilan bisa disesuaikan sesuasi kebutuhan user

**Comment by eddieridwan** [comment]
Sudah dicommit ke `master` melalui PR #2619
