### ISSUE TITLE
Hilangkan Artikel Agenda pada Widget jika waktu agenda sudah lewat

### ISSUE THREAD

**Issue by hasap86** [OpenSID/OpenSID#2598]
### Bagaimana alurnya sampai muncul masalah?
saat ini artikel agenda muncul terus menerus walaupun tgl. kegiatan sudah lewat

### Seperti apa yang diharapkan?
tidak ditampilkan untuk tgl. agenda yang sudah lewat waktu kegiatannya

### Apa yang terjadi?
informasi kadaluarsa

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    |  OpenSID 20.01-pasca
| Versi PHP        | PHP Version 7.1.33
| System operasi   | Linux

**Comment by ZER07URN** [comment]
Maaf Pak Edi, Yang Pertama Salah Copy

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.

**Comment by ZER07URN** [comment]
Ok pak
