### ISSUE TITLE
[Identitas Desa] Tagline / Motto Desa

### ISSUE THREAD

**Issue by hasap86** [OpenSID/OpenSID#2599]
### Bagaimana alurnya sampai muncul masalah?
tidak adanya inputan Tagline / Motto Desa di pengaturan Identitas Desa

### Seperti apa yang diharapkan?
Sediakan Input Isian Tagline / Moto Desa di Info Desa >> Identitas Desa dibawah Website Desa diperlukan untuk ditampilkan di website desa dan keperluan lainnya sesuai kebutuhan

### Apa yang terjadi?
tidak ada Tagline atau Motto desa di web

### Informasi tambahan 
tampilkan di tema web desa

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    |  OpenSID 20.01-pasca
| Versi PHP        | PHP Version 7.1.33
| System operasi   | Linux

**Comment by ZER07URN** [comment]
Issue hampir sama dengan #2600

**Comment by hasap86** [comment]
lebih jauh bisa ditampilkan pada header masing-masing Tema jika data inputannya sudah disediakan.

**Comment by afa28** [comment]
Sediakan di pengaturan > aplikasi

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/OpenSID/pull/7524
