### ISSUE TITLE
Mohon ditambahkan Program bantuan perorangan

### ISSUE THREAD

**Issue by hadalewa** [OpenSID/OpenSID#260]
Pada keluarga ada tombol ubah data ada menu peserta program bantuan keluarga. Bisakah tombol ini berada pada penduduk agar bisa di ketahui program bantuan apa aja yang sedang di terimah oleh penduduk tersebut??? Sehingga pembagian bantuan menjadi adil krn kadang seorang penduduk mendapat bbrapa bantuan .

**Comment by Jehamahdan** [comment]
Bisakah semua program bantuan di import dari data format excel?

**Comment by MUHAMMADRANGSEL** [comment]
Ini closed aja mas eddie

**Comment by MUHAMMADRANGSEL** [comment]
Issue ini juga di closed mas Eddie karena di menu bantuan SDH ada bantuan perorangan, kepala keluarga, kepala rumah tangga

**Comment by uncu29** [comment]
Jenis bantuan sudah ada, issue ini jga sdh bsa dtutup pak
