### ISSUE TITLE
[Widget] Jam Pelayanan Desa

### ISSUE THREAD

**Issue by hasap86** [OpenSID/OpenSID#2600]
### Bagaimana alurnya sampai muncul masalah?
tidak ada inputan jam pelayanan desa pada pengaturan Identitas Desa untuk kemudian ditampilkan pada web desa

### Seperti apa yang diharapkan?
Sediakan Input Isian Jam Pelayanan di Info Desa >> Identitas Desa dibawah dibawah Website Desa

### Apa yang terjadi?
informasi yg disampaikan di website kurang lengkap

### Informasi tambahan 
sekaligus bisa ditambahkan pada tema default dan haka dewa untuk jam pelayanan

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    |  OpenSID 20.01-pasca
| Versi PHP        | PHP Version 7.1.33
| System operasi   | Linux

**Comment by ZER07URN** [comment]
Mungkin Kreatifitas masing2 desa diperlukan untuk hal semacam ini. Solusi sederhana bisa membuatkan widget external atau menampilkan artikel/gambar pada slider.

**Comment by hasap86** [comment]
lebih jauh bisa ditampilkan pada header masing-masing Tema jika data inputannya sudah disediakan.

**Comment by afa28** [comment]
Apa seperti ini???

![1111](https://user-images.githubusercontent.com/57283157/89598429-025c2800-d887-11ea-879f-c429c9296e69.JPG)

**Comment by agungsugiarto** [comment]
Sudah ditambahkan melalui pr https://github.com/OpenSID/premium/pull/937
