### ISSUE TITLE
[Artikel] Link Youtube pada form artikel

### ISSUE THREAD

**Issue by hasap86** [OpenSID/OpenSID#2602]
### Bagaimana alurnya sampai muncul masalah?
saat ini tidak ada isian link youtube pada form artikel

### Seperti apa yang diharapkan?
Sediakan Input “Link Youtube” pada Form isian Artikel dibawah inputan “Unggah Gambar”, jika link youtube ini diisi kemudian ditampilkan pada artikel web, untuk memudahkan para pengguna dalam hal menampilkan video youtube.

### Apa yang terjadi?
tidak bisa menampilkan video youtube pada artikel.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by ZER07URN** [comment]
Coba gunakan ini

![Untitled](https://user-images.githubusercontent.com/7290110/72883420-d9cf6f00-3d36-11ea-95bb-a727d7c591fd.png)

**Comment by Nurhidayat29** [comment]
pakai kode embed bung @ZER07URN udh ksh lht gmbrnya

**Comment by hasap86** [comment]
yang dibutuhkan Linknya, untuk pengembangan pada masing-masing tema, supaya tidak menggunakan script. jadi scriptnya yang menyesuaikan pengembang temanya.

**Comment by afa28** [comment]
Lebih mudah dgn melakukan embed.

**Comment by mizwaruddin** [comment]
@afa28 apakah masih akan ditindaklanjuti?

**Comment by andifahruddinakas** [comment]
Gunakan embed
