### ISSUE TITLE
[Pengurus] Input Social Media pada inputan Staf Pemerintahan Desa

### ISSUE THREAD

**Issue by hasap86** [OpenSID/OpenSID#2603]
### Bagaimana alurnya sampai muncul masalah?
saat ini tidak ada inputan social media para staf desa

### Seperti apa yang diharapkan?
Sediakan Inputan Sosial Media pada Data Staf Info Desa > Pemerintahan Desa untuk kemudian ditampilkan pada web desa sesuai kebutuhan, baik pada widget ataupun yg lainnya.

### Apa yang terjadi?
interaksi dengan masyarakat lebih luas lagi jika mengetahui sosial media para staf desa di era Digital ini.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | OpenSID 20.01-pasca
| Versi PHP        | PHP Version 7.1.33
| System operasi   | Linux

**Comment by ZER07URN** [comment]
Apa nanti tampilan pemerintah terlink ke sosial media seperti ini???

![View Portofolio Pemerintah Desa](https://user-images.githubusercontent.com/7290110/72883192-76454180-3d36-11ea-8e56-e99b88cdd977.png)

**Comment by hasap86** [comment]
> Apa nanti tampilan pemerintah terlink ke sosial media seperti ini???
> 
> ![View Portofolio Pemerintah Desa](https://user-images.githubusercontent.com/7290110/72883192-76454180-3d36-11ea-8e56-e99b88cdd977.png)

betul sekali...

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/OpenSID/pull/7590
