### ISSUE TITLE
[Statistik] Perlu ditambahkan statistik Kepemilikan Buku Nikah

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#2611]
### Bagaimana alurnya sampai muncul masalah?
Ketika Pemerintah Desa diminta berapa jumlah Keluarga yang memiliki Buku Nikah, maka pemerintah desa tidak bisa memberikan data dengan cepat dan tepat

### Seperti apa yang diharapkan?
Ketika Pemerintah Desa diminta berapa jumlah sekaligus siapa yang sudah memiliki Buku NIkah, Data tersebut tinggal di cari di menu statistik kepeendudukan dan tinggal dicetak, seperti halnya dengan kepemilikan akta kelahiran dan KTP
![image](https://user-images.githubusercontent.com/25834335/72968537-48bfcd00-3df6-11ea-8f88-b53f817cc078.png)

### Apa yang terjadi?
Pemerintah desa perlu melakukan pencarian satu persatu di OpenSID atau menyakan kepada kepala dusun

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by andifahruddinakas** [comment]
Duplicate of https://github.com/OpenSID/OpenSID/issues/4052
