### ISSUE TITLE
[Statistik] Perlu ditambahkan statistik Kepemilikan Kepemilikan Akta Kematian

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#2612]
### Bagaimana alurnya sampai muncul masalah?
Ketika ingin mengetahui siapa saya warga masyarakat yang sudah meninggal dunia yang sudah memiliki Akta Kematian di OpenSID belum tersedia

### Seperti apa yang diharapkan?
Adanya Statistik Kepemilikan Akta Kematian, seperti statistik kepemilikan akta kelahiran dan sejeninsnya

### Apa yang terjadi?
Mempermudah Pemerintah Desa dalam mengetahui warga masyarakatnya yang sudah meninggal dunia siapa yang memiliki akta kematian

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/OpenSID/pull/7451
