### ISSUE TITLE
[Log Penduduk] Perlu ditambahkan kolom akta kematian di Log Penduduk

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#2613]
### Bagaimana alurnya sampai muncul masalah?
Ketika mengubah status dasar masyrakat menjadi MATI, perlu ditambahkan Beberapa Kolom
1. Kolom Nomor Akta Kematian
2. Hari / Tanggal / Jam Kematian
3. Tempat Kematian
4. Penyebab Kematian
5. Penolong Kematian
6. Anak Ke
yang sekarang ini 6 hal tersebut belum ada dan belum bisa disimpan didatabase
### Seperti apa yang diharapkan?
Ketika mengubah status dasar masyrakat menjadi MATI, adanya penambahan kolom :
1. Kolom Nomor Akta Kematian
2. Hari / Tanggal / Jam Kematian
3. Tempat Kematian
4. Penyebab Kematian
5. Penolong Kematian
6. Anak Ke
dan tersimpan didatabase OpenSID
### Apa yang terjadi?
1. Data tidak tersimpan didatabase
2. belum bisa mengetahui siapa saja yang sudah memiliki akta kematian

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by andifahruddinakas** [comment]
Duplikasi https://github.com/OpenSID/OpenSID/issues/2859
