### ISSUE TITLE
>>>>> Link gambar wiki 2020

### ISSUE THREAD

**Issue by desainternet** [OpenSID/OpenSID#2614]
<img width="1280" alt="petunjuk-migrasi" src="https://user-images.githubusercontent.com/249563/80769492-bcf5d380-8b90-11ea-9c64-1cba0e06ecfb.png">

![readme-image](https://user-images.githubusercontent.com/249563/80325903-6891e180-887a-11ea-8471-6635dc6aa619.png)

![keuangan-1](https://user-images.githubusercontent.com/249563/74583051-33197e00-5017-11ea-8dd7-1c7036efdb07.png)
![keuangan-2](https://user-images.githubusercontent.com/249563/74583054-36146e80-5017-11ea-83bc-836d2eb65183.png)
![keuangan-3](https://user-images.githubusercontent.com/249563/74583055-36ad0500-5017-11ea-9168-6561f9d2ca09.png)
![keuangan-4](https://user-images.githubusercontent.com/249563/74583057-37459b80-5017-11ea-91fd-5ae1f06590ff.png)

<img width="1263" alt="surat-layanan-mandiri-1" src="https://user-images.githubusercontent.com/249563/73642685-4008aa00-46c6-11ea-9732-ed4f29642585.png">
![contoh](https://user-images.githubusercontent.com/37096640/72991491-a965fe80-3e24-11ea-9949-1c3530137e2d.png)

**Comment by ZER07URN** [comment]
Mungkin perlu perbaikan di semua tombol (hapus, cetak, unduh) jika data tdk ada mungkin bisa di disable dlu

**Comment by roaddee** [comment]
![image](https://user-images.githubusercontent.com/45786885/73125071-5b442d00-3fd5-11ea-9920-5353a15b5d1f.png)

**Comment by roaddee** [comment]
![image](https://user-images.githubusercontent.com/45786885/73125225-01446700-3fd7-11ea-9506-7d91e2f99842.png)

**Comment by Nurhidayat29** [comment]
![error](https://user-images.githubusercontent.com/51182125/73842211-b506eb80-484e-11ea-853a-501c450884bd.jpg)

**Comment by Nurhidayat29** [comment]
![83767070_176115423711916_1424266246899105792_n](https://user-images.githubusercontent.com/51182125/73998664-eee20a00-4994-11ea-8679-f9e0749395f4.png)
![83796082_2612251909054772_6493860396863062016_n](https://user-images.githubusercontent.com/51182125/73998667-f6091800-4994-11ea-977c-157d44633295.png)
![84477721_115955506523744_8169382969312542720_n](https://user-images.githubusercontent.com/51182125/73998675-f99c9f00-4994-11ea-9b20-4adb0064fdf1.png)
![84535501_800540167025024_2993372461900234752_n](https://user-images.githubusercontent.com/51182125/73998676-facdcc00-4994-11ea-88cf-836d26fd6da4.png)
![84589053_181022663211851_2078134413094289408_n](https://user-images.githubusercontent.com/51182125/73998682-fdc8bc80-4994-11ea-9c2d-3ad5b924a776.png)
![Uploading 84701937_169270181038155_6428331204654661632_n.png…]()

**Comment by Nurhidayat29** [comment]
![84701937_169270181038155_6428331204654661632_n](https://user-images.githubusercontent.com/51182125/74010289-bd2e6a80-49b7-11ea-9c76-2e53c1bbbd34.png)

**Comment by Nurhidayat29** [comment]
![86334754_3276863359008942_5032072366478327808_o](https://user-images.githubusercontent.com/51182125/74586189-c18dff80-5017-11ea-881c-c501e5d34e0b.jpg)

**Comment by ianskids** [comment]
![vcruntime](https://user-images.githubusercontent.com/60131374/74691719-7ee64600-5216-11ea-8592-eedf23480990.png)

**Comment by ianskids** [comment]
[script-installer-opensid-20.02.zip](https://github.com/OpenSID/OpenSID/files/4222724/script-installer-opensid-20.02.zip)
