### ISSUE TITLE
Tambahkan Nomor Darurat pada Pengaturan Identitas Desa

### ISSUE THREAD

**Issue by hasap86** [OpenSID/OpenSID#2617]
### Bagaimana alurnya sampai muncul masalah?
Belum ada inputan Nomor Darurat

### Seperti apa yang diharapkan?
Tambahkan Nomor Darurat seperti

1. Ambulan
2. Polsek
3. Pemadam Kebakaran
4. Puskesmas

### Apa yang terjadi?
kurangnya informasi nomor darurat dan bisa ditampilkan di web

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | Versi 20.01-pasca
| Versi PHP        | 
| System operasi   |

**Comment by ZER07URN** [comment]
Ini biasa di akali dengan penambahan widget dinamis, silahkan berkreasi.

Admin Web > Widget > Tambah Widget > Isi Judul > Pilih Jenis Widget(Dinamis) > Isikan Kode. 

![widgteyfe](https://user-images.githubusercontent.com/7290110/73062153-4fba0e80-3ece-11ea-871e-ea106b4d8bda.png)

![pentong](https://user-images.githubusercontent.com/7290110/73062170-56488600-3ece-11ea-9fdd-930ce9389569.png)

**Comment by hasap86** [comment]
betul banyak sekali fitur yang bisa kita akali dengan script pada widget dinamis, yang saya buatkan Issue ini adalah solusi bagi mereka yg awam, kebanyakan perangkat desa itu awam sehingga kita harus memberikan solusi termudah.

dengan adanya data Nomor Darurat para pengembang Tema tinggal menambahkan Nomor tersebut pada temanya.

yang dibutuhkan database Nomor Darurat supaya bisa dimanfaatkan datanya untuk pengembangan para pengembang Tema.

**Comment by afa28** [comment]
Bisa buat di widget.

**Comment by mizwaruddin** [comment]
@afa28 bisa diclose.
