### ISSUE TITLE
Tambahkan Nomor Layanan WhatsApp pada Pengaturan Identitas Desa

### ISSUE THREAD

**Issue by hasap86** [OpenSID/OpenSID#2618]
### Bagaimana alurnya sampai muncul masalah?
Saat ini hanya tersedia 1 inputan nomor telepon desa, belum ada inputan nomor HP & WhatsApp

### Seperti apa yang diharapkan?
tambahkan nomor HP & Whatsapp pada identitas Desa

### Apa yang terjadi?
kurangnya informasi kontak desa

### Informasi tambahan 
mempermudah layanan yg bisa ditampilkan di website langsung

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | Versi 20.01-pasca
| Versi PHP        | 
| System operasi   |

**Comment by ZER07URN** [comment]
![sosmed](https://user-images.githubusercontent.com/7290110/73056288-437b8480-3ec1-11ea-9089-52b3efe718ea.png)

@hasap86 apakah ini tdk mewakili???

**Comment by hasap86** [comment]
Telepon Desa biasanya nomor telepon Telkom, sedangkan pelayanan biasanya menggunakan juga nomor Handphone (Mobile) yg juga sekaligus bisa digunakan WhatsApp.

**Comment by wahyutaqdirulaziz** [comment]
apa ini masih belum di kerjakan

**Comment by sup-ham** [comment]
sepertinya belum

**Comment by mizwaruddin** [comment]
@afa28 sudah terwakili di menu admin web > media sosial. Di tema natra sdh bisa langsung chat personal dan grup.
