### ISSUE TITLE
Masa Jabatan (Usia/Periode)

### ISSUE THREAD

**Issue by elkautzar** [OpenSID/OpenSID#2620]
![sosmed](https://user-images.githubusercontent.com/7290110/73058097-82abd480-3ec5-11ea-8429-5f048a0a04a6.png)

### Bagaimana alurnya sampai muncul masalah?
Masa Jabatan Diinput Manual, Sehingga Kemungkinan Dapat Diinput Dengan Hal Yang Lain (Tidak Sesuai Contoh)

### Seperti apa yang diharapkan?
Form Input Masa Jabatan (Usia/Periode) Dihapus.
Masa Jabatan Mungkin Bisa Diambil Dari Tahun Tanggal SK Pengangkatan dan Tanggal SK Pemberhentian yang digabung.

Misal :
Tanggal SK Pengangkatan : 08-11-2014
Tanggal SK Pemberhentian : 31-01-2020

Sehingga Masa Jabatan Menjadi : 2014 s/d 2020

### Apa yang terjadi?
Tidak Perlu Lagi Input Masa Jabatan Yang Kemungkinan Bisa Salah.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by mizwaruddin** [comment]
Saya rasa tanggal SK Pemberhentian baru bisa diisi setelah SK tersebut dikeluarkan/ditetapkan.
