### ISSUE TITLE
Tab Agenda Kurang Tepat

### ISSUE THREAD

**Issue by hasap86** [OpenSID/OpenSID#2622]
### Bagaimana alurnya sampai muncul masalah?
Saat ini yang dimunculkan tab pada Agenda **yang akan datang** dan **Lama**.

### Seperti apa yang diharapkan?
Seharusnya yang lama tidak perlu lagi dimunculkan, yg perlu dimunculkan adalah Agenda **Hari ini** & **Yang Akan Datang**. Tab Hari ini berisi Agenda hari ini, sedangkan tab Agenda yang akan Datang adalah Agenda besoknya.

### Apa yang terjadi?
yang lama sudah expired

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | demo
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Saya kira ini tergantung selera. Ada yg menginginkan bisa melihat agenda yg lalu juga -- yg mungkin mereka lupa untuk menghadiri atau menyimak. 

Mungkin yg bisa dilakukan adalah di tab 'Yang Akan Datang' untuk menonjolkan agenda hari ini untuk membedakan dengan yg besok2.

**Comment by hasap86** [comment]
Istilah **Yang Akan Datang** biasanya diperuntukan untuk Agenda Besok-besok bukan **Hari Ini**. jadi hitungannya bukan deteksi dari Jam tapi dari Hari. 

kalo yg sekarang, misalkan terlewat 1 detik pun munculnya di Tab Lama.

**Comment by eddieridwan** [comment]
Ok, sekarang ditampilkan tiga tab : 'Hari ini', 'Yang akan datang' dan 'Lalu'
