### ISSUE TITLE
Tambah Jenis Tampilan Artikel Full Width / Content + Sidebar

### ISSUE THREAD

**Issue by hasap86** [OpenSID/OpenSID#2623]
### Bagaimana alurnya sampai muncul masalah?
Saat ini jenis tampilan artikel default hanya tersedia Konten + Sidebar.

### Seperti apa yang diharapkan?
berikan pilihan saat membuat artikel apakah tampilannya mau Full tanpa Sidebar atau Konten + Sidebar. (Full Width atau Content + Sidebar)

### Apa yang terjadi?
ketika isi konten memerlukan tampilan yang tanpa sidebar belum bisa.

### Informasi tambahan 
dibutuhkan untuk menampilkan beberapa konten artikel yang memerlukan tanpa sidebar, jadi hanya menampilkan konten saja.

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | demo
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
Tergantung settingan tema, klw tema menyediakan pilihan tersebut maka bisa di buatkan. Namun saat ini pengaturan khusus untuk tema blum disediakan.

**Comment by afa28** [comment]
Tambahan u/ modul tema.
1. Sediakan pengaturan u/ masing2 tema yg digunakan.

**Comment by hasap86** [comment]
sementara dibuatkan saja untuk tema hakadewa dulu yg banyak dipake, untuk setingan pilihan Konten + Sidebar atau Full Width di sediakan saja di setiap pembuatan artikel, jadi bisa disesuaikan setiap artikelnya mau ada sidebar atau tidak di sebelah kanan saat bikin artikel dengan tulisan
Template
- Konten + Sidebar
- Full Width

**Comment by afa28** [comment]
Akan disediakan di pengaturan tema. Untuk menggunakannya masing2 tema perlu sediakan layout konten yakni : full width, Konten + Sidebar (right / left)

**Comment by hasap86** [comment]
> Akan disediakan di pengaturan tema. Untuk menggunakannya masing2 tema perlu sediakan layout konten yakni : full width, Konten + Sidebar (right / left)

kalo di pengaturan tema apa jadi berlaku untuk semua? sementara diperlukan untuk beberapa artikel saja, jadi pengaturannya di masing-masing artikel saja.

**Comment by balongbesuk** [comment]
pengaturan masing masing artikel? maksudnya per kategori? 

kalo perkategori lebih mudah, kalo per artikel, :smile: 

coba dikasih gambar kasar / contoh biar porgramer paham apa yang dimaksud

**Comment by afa28** [comment]
Sy mengerti maksudnya, ini kyak di wordpress.
Tp perlu pengaturan umum (u/ tema), karena di OpenSID ada beberapa halaman statis yg tempat pengaturannya tdk ada.

**Comment by hasap86** [comment]
> Sy mengerti maksudnya, ini kyak di wordpress.
> Tp perlu pengaturan umum (u/ tema), karena di OpenSID ada beberapa halaman statis yg tempat pengaturannya tdk ada.

betul seperti di wordpress, saya lebih banyak mempelajari konsep wordpress untuk diterapkan di opensid.
Terimakasih, semoga segera terealisasi

**Comment by andifahruddinakas** [comment]
Penanganan template halaman website perlu disuaikan ulang agar bisa menerapkan hal ini.

**Comment by hasap86** [comment]
> Penanganan template halaman website perlu disuaikan ulang agar bisa menerapkan hal ini.

bisa digunakan untuk tema esensi...

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/OpenSID/pull/7595
