### ISSUE TITLE
Nominal 0 Hilang

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#2624]
### Bagaimana alurnya sampai muncul masalah?
Jika tidak tersedia sumber pendapatan, belanja, maupun lainnya di APBDesa, seyogyanya baris tersebut dihide saja agar angka 0 tidak tampil pada tabel. 
![Tanpa judul](https://user-images.githubusercontent.com/46939846/73131258-6e3d1880-403a-11ea-9f7f-ef81d614d7bb.png)

### Seperti apa yang diharapkan?
Supaya tabel menyesuaikan nominal yang tersedia saja dan lebih efektif dan efisien dalam penyajian baris.

### Apa yang terjadi?
Agar penyajian tabel anggaran tidak terlalu panjang ke bawah.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Bung @ariandii , issue ini kami tutup. Mohon periksa di perubahan yg terbaru. Kalau masih bermasalah, silakan buka lagi.
