### ISSUE TITLE
munculkan status halaman tidak ditemukan

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#2625]
### Bagaimana alurnya sampai muncul masalah?
buka website demo > pilih statistik apapun > tambahkan dua angka dibelakang url

### Seperti apa yang diharapkan?
harusnya muncul 404 halaman tidak ditemukan

### Apa yang terjadi?
muncul database error

### Informasi tambahan 
![asasas](https://user-images.githubusercontent.com/35319600/73137297-35786000-4089-11ea-8d3f-42ab4070eac5.jpg)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
ini krn kita menggunakan id sebagi parameter pemanggil. harusnya yg akan di tampilkan dihalaman depan website terdaftar dimenu dan menggunakan slug.

**Comment by eddieridwan** [comment]
Sudah dicommit ke `master`.
