### ISSUE TITLE
error_404.php tidak berfungsi sebagaimana mestinya

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#2626]
### Bagaimana alurnya sampai muncul masalah?
buka website demo > tambahkan sembarang huruf / angka dibelakang url

### Seperti apa yang diharapkan?
harusnya muncul 404 halaman tidak ditemukan

### Apa yang terjadi?
muncul halaman blank kosong

### Informasi tambahan 
![asasas](https://user-images.githubusercontent.com/35319600/73137408-1c23e380-408a-11ea-83a6-ffadda102da8.jpg)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dicommit ke `master` melalui PR #2627
