### ISSUE TITLE
Panjang Jalan, Irigasi dan Jaringan pada menu inventaris sebaiknya memakai M bukan KM

### ISSUE THREAD

**Issue by makhbub** [OpenSID/OpenSID#2628]
### Bagaimana alurnya sampai muncul masalah?
isian panjang jalan pada menu inventaris memakai satuan KM. padahal sering ditemui  jalan atau irigasi di Desa panjangnya hanya ratusan atau bahkan puluhan meter saja, kami sempat mencoba mengisi data dengan angka ( 0,.... Km) tapi tampaknya tidak bisa karena hasil yang muncul berupa pembulatan menjadi ( 0 Km)
### Seperti apa yang diharapkan?
satuan panjang jalan, irigasi dan jaringan diganti meter untuk menampung inventaris jalan yang panjangnya hanya puluhan meter

### Apa yang terjadi?
jika ukuran tetap memakai Km maka jalan atau irigasi yang panjangnya hanya puluhan meter tidak akan terdata dengan baik

### Informasi tambahan 
sebagai informasi tambahan kami tampilkan scren shot menu inventaris Jalan, irigasi dan jaringan
![inventaris km2](https://user-images.githubusercontent.com/38773660/73146622-3d1a2200-40e6-11ea-8ec4-76d35294ba1a.png)
![inventaris km](https://user-images.githubusercontent.com/38773660/73146636-53c07900-40e6-11ea-9447-4b73047f9646.png)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by karangkamulyan** [comment]
![perbaikan isu](https://user-images.githubusercontent.com/46555658/75341149-61744480-58c6-11ea-80be-f71eeb7c06d5.jpg)

**Comment by eddieridwan** [comment]
Sudah dicommit ke `master` melalui PR #2726
