### ISSUE TITLE
[Bug] Menu Analisa Penduduk masih Menggunakan data seluruh penduduk baik yang aktif maupun tidak

### ISSUE THREAD

**Issue by makhbub** [OpenSID/OpenSID#2629]
### Bagaimana alurnya sampai muncul masalah?
pada menu analisa penduduk yang berisi data Prodeskel dan peta sosial, data penduduk yang digunakan adalah seluruh data penduduk baik yang masih aktif maupun sudah tidak aktif ( mati, pindah, hilang )

### Seperti apa yang diharapkan?
data penduduk pada menu analisa harusnya memakai data penduduk aktif saja

### Apa yang terjadi?
jika tetap pemakai data seluruh penduduk baik yang aktif maupun tidak aktif ( mati, pindah, hilang) maka akan membuat kebingungan operator, karena penduduk yang sudah mati atau pindah masih muncul pada data analisa

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by wahyutaqdirulaziz** [comment]
apa ini belum solved

**Comment by afa28** [comment]
Sy sudah test dengan cara mematikan penduduk yg ada di daftar analisis (Prodeskel / penduduk) dan tdk menemukan hal yg di permasalahkan pd issue ini. Dan sy cek query pemanggilan datanya hanya menampilkan penduduk dengan status_dasar = 1 (hidup).

Apa ada yg terlewat/keliru??? Mohon di lampirkan gambar klw perlu.

**Comment by afa28** [comment]
Apakah ini masih bermasalah???

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3627
