### ISSUE TITLE
Mengganti parameter id menjadi slug pd url terutama data statistik

### ISSUE THREAD

**Issue by afa28** [OpenSID/OpenSID#2631]
### Bagaimana alurnya sampai muncul masalah?
Ada beberapa data yang tidak ditampilkan pada menu website bisa di akases oleh umum dengan cara menerka-nerka parameter id dr data tsb. 

### Seperti apa yang diharapkan?
Menggunakan slug bisa menjadi alternatif yg jauh lebih baik dibanding id. Atau mungkin ada alternatif lain.

Menu :
1. Artikel
2. Statistik
3. Lainnya

### Apa yang terjadi?
Pengunjung dapat melihat data yg sebenarnya tidak ingin kita tampilkan. Kebocoran data yg tdk disengaja.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by fahruddinakas** [comment]
![Screenshot_2020-01-28-05-10-18-27](https://user-images.githubusercontent.com/57283157/73214140-9046b000-418c-11ea-8ead-dc6ad0570beb.png)

**Comment by eddieridwan** [comment]
Kalau data yg memang ditujukan pada umum tetapi tidak secara eksplisit disediakan menu atau tampilannya, saya kira tidak apa2 kalau ditampilkan oleh pengunjung dengan menerka urlnya secara langsung. Misalnya kalau menu PetaSID tidak disediakan, tetapi dibuka secara langsung melalui url `/first/peta` sepertinya tidak apa2 -- karena tidak merupakan pelanggaran privasi data.

Mengunci semua halaman publik yg tidak ditampilkan secara eksplisit melalui menu/widget/halaman statis atau cara lain bisa diterapkan, tetapi akan membutuhkan mekanisme tambahan dan sebaiknya hanya diprioritaskan kalau memang ada desa/pengguna yg menganggap penting. 

Perhatikan bahwa semua artikel dinamis yg aktif boleh diakses -- secara konsep hanya dibatasi status aktif atau tidak. Artikel statis secara konsep mungkin dapat dibatasi -- tetapi kalau ingin dibatasi maka artikel statis aktif yg tidak ditampilkan di menu juga tidak boleh ditampilkan melalui fitur cari atau arsip artikel.

 Aturan setiap jenis unsur tampilan web akan menjadi rumit, dan perlu dianalisis secara rinci untuk disepakati oleh komunitas pengguna. 

Mungkin cara yg lebih sederhana adalah dengan menggunakan status aktif/tidak aktif saja. Jadi misalnya, artikel statis yg tidak ingin ditampilkan di web melalui cara apapun, ya dibuat tidak-aktif saja.

Demikian juga, sediakan fitur aktif/tidak-aktif untuk setiap statistik. Jadi statistik yg tidak-aktif tidak bisa diakses melalui cara apapun. 

Dstnya...

**Comment by afa28** [comment]
Duplicte #2784
