### ISSUE TITLE
Penambahan Tombol Kembali Ke Daftar Keluarga

### ISSUE THREAD

**Issue by afa28** [OpenSID/OpenSID#2632]
### Bagaimana alurnya sampai muncul masalah?
Tidak adanya tombol untuk kembali ke halaman utama Daftar Kelurga

### Seperti apa yang diharapkan?
Penambahan Tombol Kembali Ke Daftar Keluarga

### Apa yang terjadi?
Jalan Pintas dan Penyeragaman Dengan Form2 Lain

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dicommit ke `master` melalui PR #2633
