### ISSUE TITLE
Penambahan Log Pemerintah Desa

### ISSUE THREAD

**Issue by afa28** [OpenSID/OpenSID#2635]
### Bagaimana alurnya sampai muncul masalah?
Jika melakukan pergantian kepala desa harus mengganti data kepala desa yang lama. sehingga history kepala desa yang lama tidak tersimpan. 

### Seperti apa yang diharapkan?
Memberika log pemerintah desa, filter pemerintah desa priode berjalan.

### Apa yang terjadi?
History dari pemerintah sebelumnya tidak hilang

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by mizwaruddin** [comment]
Untuk perangkat desa yang sudah tidak aktif/pensiun bisa dilakukan dengan menonaktifkan perangkat ybs.
