### ISSUE TITLE
Identitas Desa (Kepala Desa)

### ISSUE THREAD

**Issue by afa28** [OpenSID/OpenSID#2636]
### Bagaimana alurnya sampai muncul masalah?
Data tidak diabil dari data pemerintah desa / penduduk

### Seperti apa yang diharapkan?
Data khususnya kepala desa diambil dari pemerintah desa dengan priode berjalan.

### Apa yang terjadi?
Data tidak perlu di input manual lg, kepala nama kepala desa dan nip akan muncul otomatis

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by mizwaruddin** [comment]
Apakah semua kepala desa/lurah pasti warga desa setempat?

**Comment by afa28** [comment]
Kepala desa tidak harus dr warga desa tsb, bisa sj dr luar desa. Dsni, spa kepala desa pasti datanya akan di input ke dlm dtabase warga, baik itu menjadi warga desa maupun warga luar desa/pendatang
