### ISSUE TITLE
Penduduk Yang Mati/Pindah/Hilang Masih Bergentayangan

### ISSUE THREAD

**Issue by afa28** [OpenSID/OpenSID#2637]
### Bagaimana alurnya sampai muncul masalah?
Beberapa Form Input Data Masih Memperbolehkan Penduduk Yang Mati/Pindah/Hilang Tersimpan. Contoh : Menduduki Suatu Jabatan(Kepala Dusun,dll)
              Menerima Bantuan
              Dll

### Seperti apa yang diharapkan?
Memberi batasan hanya untuk penduduk yang hidup saja melakukan hal tsb.

### Apa yang terjadi?
Data Sesuai Dengan Fakta Yang Ada Di Lapangan

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by junandia** [comment]
Saya test gak bisa ya pak nambah peserta jika status penduduknya selain HIDUP.

**Comment by afa28** [comment]
Salah satunya di bagian wilayah administrasi, kepala dusun, rt, rw masih bisa di isi oleh org mati
