### ISSUE TITLE
[Template Surat] Format Surat F-1.21 dan F-1.06

### ISSUE THREAD

**Issue by happyagung25** [OpenSID/OpenSID#264]
Mohon untuk dimunculkan format surat  F-1.21 ( formulir permohonan kartu tanda penduduk ) dan format F-1.06 ( formulir biodata penduduk untuk perubahan data warga negara indonesia).
Permintaan Kepala Desa Hadakewa

**Comment by desahadakewa** [comment]
Makash sdah smpaikan dluan mas......

**Comment by eddieridwan** [comment]
[permen_no.19-2010.pdf](https://github.com/eddieridwan/OpenSID/files/888287/permen_no.19-2010.pdf)

**Comment by eddieridwan** [comment]
Gabung F-1.21 dan F-1.06 sebagai satu lampiran untuk surat_permohonan-ktp, karena F-1.06 ( formulir biodata penduduk untuk perubahan data warga negara indonesia) hanya dicetak dalam rangka permohonan KTP.

**Comment by eddieridwan** [comment]
Ubah surat_pindah_antar_kab_prov (yang tidak diperlukan lagi) menjadi surat_permohonan_ktp.

**Comment by eddieridwan** [comment]
![f-1 21_formulir_permohonan_kartu_tanda_penduduk_ ktp _wni](https://cloud.githubusercontent.com/assets/249563/24637624/b625d656-1936-11e7-93b6-782f66540219.jpg)
![f-1 21_formulir_permohonan_kartu_tanda_penduduk_ ktp _wni-2](https://cloud.githubusercontent.com/assets/249563/24637625/b6289080-1936-11e7-945e-64d40fabf71f.jpg)

[F-1.21_FORMULIR_PERMOHONAN_KARTU_TANDA_PENDUDUK_(KTP)_WNI.pdf](https://github.com/eddieridwan/OpenSID/files/891838/F-1.21_FORMULIR_PERMOHONAN_KARTU_TANDA_PENDUDUK_.KTP._WNI.pdf)

**Comment by eddieridwan** [comment]
@metalab25 @desahadakewa : harap jawab pertanyaan di gambar berikut.

![f-1 21 pertanyaan](https://cloud.githubusercontent.com/assets/249563/24648556/138b14d2-1978-11e7-955f-d1445b7ae61a.jpg)

**Comment by MUHAMMADRANGSEL** [comment]
Ya betul sekali diisi satu kali dan dprint dalam satu lembar itu dua shgg nanti tggal disobek/digunting : satu jd arsip dan satu dibawa oleh masyarakat untuk pembuatan KTP

**Comment by eddieridwan** [comment]
1. Diisi alamat jalan/perumahan yang mungkin panjang, seperti "Jl. Lintas sumatera kilometer 9, perum. Bikit permai blok H. No.08", yang apabila ditulis tangan bisa memerlukan dua baris
1. Setiap desa hanya memiliki satu kode pos
1. Ke dua form diisi dengan data yang sama, satu sebagai salinan arsip dan satu lagi untuk pemohon

**Comment by eddieridwan** [comment]
![f-1 06_formulir_biodata_penduduk_untuk_perubahan_data_wni](https://cloud.githubusercontent.com/assets/249563/24680277/61596e7c-19e4-11e7-98be-31342718bc79.jpg)

[F-1.06_FORMULIR_BIODATA_PENDUDUK_UNTUK_PERUBAHAN_DATA_WNI.pdf](https://github.com/eddieridwan/OpenSID/files/894634/F-1.06_FORMULIR_BIODATA_PENDUDUK_UNTUK_PERUBAHAN_DATA_WNI.pdf)

**Comment by eddieridwan** [comment]
@deni efendi (FB) memberitahu bahwa berdasarkan Permendagri No 8 Tahun 2016, khususnya Pasal 5, permohonan KTP tidak lagi memerlukan pengisian F-1.21 maupun F-1.06.


[Permendagri_8_Tahun_2016_ttg_Perubahan_Permen_9_Tahun_2011_ttg_Penerbitan_KTP_NIK_Nasional.pdf](https://github.com/eddieridwan/OpenSID/files/895078/Permendagri_8_Tahun_2016_ttg_Perubahan_Permen_9_Tahun_2011_ttg_Penerbitan_KTP_NIK_Nasional.pdf)

**Comment by eddieridwan** [comment]
Mudah2an teman2 sempat menyimak diskusi F-1.21 formulir Permohonan KTP dan F-1.06 di beberapa posting sebelumnya. Pembahasan ini menyangkut hal2 yang agak mendasar seputar peran, fungsi dan prioritas OpenSID.

Pertama, banyak tugas kantor desa berkaitan dengan interaksi dengan instansi lain, termasuk dalam administrasi kependudukan. OpenSID, yang tujuannya mempermudah pekerjaan kantor desa, mau tidak mau juga berkaitan dengan ketentuan instansi lain. Banyak fitur OpenSID (dan tentunya banyak waktu pembahasan dan pemrograman) berurusan dengan upaya mempermudah interaksi dengan Disdukcapil dalam administrasi kependudukan (misalnya mengimpor data BIP, mencetak berbagai formulir administrasi kependudukan yang ditentukan Disdukcapil).

Kedua, interaksi dengan instansi seperti Disdukcapil yang diterapkan menggunakan OpenSID, perlu mengacu pada regulasi dan aturan yang jelas dan yang diketahui adalah yang resmi berlaku. Kalau tidak, kita akan menghabiskan banyak waktu dan tenaga yang sangat langka untuk menerapkan sesuatu di OpenSID yang (1) seharusnya tidak perlu dilakukan atau (2) walaupun saat ini masih dipraktekkan, sudah dalam proses untuk ditiadakan. Sebagai contoh, dalam pembahasan F-1.21 dan F-1.06, acuan awalnya diketahui adalah Permendagri 19/2014. Tetapi dalam pembahasan selanjutnya diperoleh informasi bahwa Permendagri 8/2016, khususnya Pasal 5, menjabarkan proses baru permohonan KTP-el yang tidak lagi membutuhkan F-1.21 dan F-1.06. Walaupun F-1.21 dan F-1.06 masih digunakan diberbagai wilayah, kita perlu mempertanyakan: apakah kita terus terapkan F-1.21 dan F-1.06 di OpenSID, sedangkan masih banyak tugas OpenSID lainnya yang tidak terpegang?

Ketiga, walaupun telah dihimbau berulang-ulang, pada kenyataannya sampai saat ini belum banyak dari komunitas OpenSID yang dapat menolong secara langsung dalam pengembangan OpenSID. SDM pengembangan panduan OpenSID maupun script OpenSID tetap sangat terbatas. Karena itu, prioritasi pelaksanaan pengembangan OpenSID perlu dilakukan dengan hati-hati. Dengan pertimbangan ini, penerapan F-1.21 dan F-1.06 sulit dijadikan prioritas.

Terlepas dari semua ini, kita sangat beruntung dengan adanya teman2 dari Disdukcapil yang ikut bergabung dalam forum ini. Informasi dan masukan dari mereka akan membantu kita untuk lebih efektif dalam menerapkan fitur2 OpenSID yang berkaitan dengan administrasi kependudukan.

**Comment by eddieridwan** [comment]
Seperti dijelaskan di atas, mubazir kita menerapkan F-1.21 dan F-1.06, karena seharusnya sudah tidak digunakan lagi. 

Langkah yang sebaiknya dilakukan oleh desa yang masih diminta menggunakan form itu, mungkin adalah:

1. beri masukan langsung pada petugas Disdukcapil setempat, menjelaskan pada mereka proses permohonan KTP yang diamanatkan Permendagri 8/2016 Pasal 5; walaupun seharusnya mereka sudah tahu;
1. minta bantuan teman2 Disdukcapil di forum ini, seperti Deni Efendi Juan Christo Selan, untuk menghubungi Disdukcapil setempat untuk menjelaskan Permendagri 8/2016;
1. menggunakan wadah/jalur Camat, Asosiasi Kepala Desa, BMPD, LSM lokal yang peduli tertib administrasi dan pihak2 lainnya untuk membantu lobi Bupati setempat agar mengarahkan Disdukcapil untuk menerapkan Permendagri 8/2016.

**Comment by balongbesuk** [comment]
outdate bs d close
