### ISSUE TITLE
Penambahan Form Surat Undangan

### ISSUE THREAD

**Issue by ahmadngudi** [OpenSID/OpenSID#2640]
### Seperti apa yang diharapkan?

Penambahan Form Surat Undangan, baik itu undangan musyawarah atau kegiatan sosialisasi dari pemdes ke warga atau aparatur desa.

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.01-pasca
| Versi PHP        | 
| System operasi   | Windows 10

**Comment by mizwaruddin** [comment]
Sya kira tidak perlu karena: 1. tujuan surat undangan bisa terdiri atas banyak orang/lembaga. 2. surat layanan didasarkan pada permohonan warga, bukan pemerintah desa.
Jadi, untuk surat undangan cukup dibuat secara manual, hasil yg sdh ditandatangani dan stempel discan kemudian dimasukkan di surat keluar biar nomor surat menjadi urut.

**Comment by ahmadngudi** [comment]
> Sya kira tidak perlu karena: 1. tujuan surat undangan bisa terdiri atas banyak orang/lembaga. 2. surat layanan didasarkan pada permohonan warga, bukan pemerintah desa.
> Jadi, untuk surat undangan cukup dibuat secara manual, hasil yg sdh ditandatangani dan stempel discan kemudian dimasukkan di surat keluar biar nomor surat menjadi urut.

ok, trims..
