### ISSUE TITLE
Gambar Peta poligon tidak tersimpan

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#2641]
### Bagaimana alurnya sampai muncul masalah?
buka website demo >info desa >identitas desa > peta wilayah > selanjutnya gambar poligon wilayah > simpan

### Seperti apa yang diharapkan?
bisa tersimpan

### Apa yang terjadi?
peta wilayah tidak tersimpan berikut turunannya wilayah >dusun > rw > rt

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by balongbesuk** [comment]
sy tes simpan di website beta juga tidak tersimpan

**Comment by eddieridwan** [comment]
Memang proses untuk memetakan wilayah baru agak terselebung. Poligon yg dibuat perlu diubah dulu sebelum disimpan. Mudah2an ada yg bersedia untuk membuat lebih langsung. 

<img width="1390" alt="gambar-poligon" src="https://user-images.githubusercontent.com/249563/73325073-2bc94500-42a1-11ea-89e9-021b87df531b.png">

**Comment by eddieridwan** [comment]
Sementara belum ada yg memperbaiki, silakan anda tambahkan info di atas di panduan wiki. Terima kasih @balongbesuk .

**Comment by balongbesuk** [comment]
apa isue ini ditutup pak?

**Comment by eddieridwan** [comment]
@balongbesuk ubah issue ini untuk meminta perbaikan supaya peta wilayah baru bisa tersimpan setelah langkah #1, tanpa harus melakukan langkah #2.

**Comment by eddieridwan** [comment]
Sudah dicommit ke `master` melalui PR #2644
