### ISSUE TITLE
Ubah nama folder `surat` menjadi `template-surat` untuk membedakan dengan controller `surat`

### ISSUE THREAD

**Issue by andryrukandifauzy** [OpenSID/OpenSID#2642]
![Screenshot_1](https://user-images.githubusercontent.com/42363553/73416827-b2852d00-4348-11ea-89a7-bc6bfe902340.png)
![Screenshot_2](https://user-images.githubusercontent.com/42363553/73416829-b31dc380-4348-11ea-9d7b-39b3c20ea5cf.png)
![Screenshot_3](https://user-images.githubusercontent.com/42363553/73416831-b31dc380-4348-11ea-8a97-893f1c1f827e.png)

### Bagaimana alurnya sampai muncul masalah?
ketika akan mengunduh format surat muncul error not found **tapi ketika .httcacces dihapus bisa mengunduh format surat tersebut** 

### Seperti apa yang diharapkan?
ketika httacces di aktifkan bisa mengunduh

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by mizwaruddin** [comment]
Pakai server lokal?

**Comment by andryrukandifauzy** [comment]
iya pak pakai linux centos 7

**Comment by Imamayuti** [comment]
sepertinya kehilangan data alamat unduh di database, mengingat ketika di upload ulang file suratnya, permasalahan tersebut terselesaikan.

**Comment by andryrukandifauzy** [comment]
jika di upload ulang maka format surat tersebut ada di folder /desa/surat

padahal di folder surat master itu sudah ada

Pada tanggal Jum, 31 Jan 2020 13.30, Imam Sayuti <notifications@github.com>
menulis:

**Comment by Imamayuti** [comment]
ia saya menduga, hal itu terjadi karena kehilangan alamat di database makanya ketika di upload ulang, alamat otomatis akan di tulis ulang di database dan hal tersebut pun terpecahkan.

**Comment by andryrukandifauzy** [comment]
Iya betul pak , sudah terpecahkan namun saya penasaran kenapa ketika
htacces dihilangkan format surat bisa terdownload namun ketika htacces
aktif tidak bisa di download dan muncul error seperti diatas



Pada tanggal Sab, 1 Feb 2020 00.12, Imam Sayuti <notifications@github.com>
menulis:

**Comment by ariandii** [comment]
setelah  .htaccess dibuat, coba unduh surat selain Surat Keterangan Pengantar. misal surat lain uang ada di bawahnya.

nampaknya sukses.

**Comment by hasap86** [comment]
Permasalahan ini sudah saya sampaikan sebelumnya dan belum ada perbaikan karena disangkanya bermasalah di hosting saya aja.

Padahal saya coba ini terjadi pada Instalasi baru selalu sulit untuk melakukan unduh (error). waktu itu saya ambil langkahnya download dulu di demo trus upload. hehe

semoga cepat ketemu permasalahan error unduh pada instalasi baru...

**Comment by eddieridwan** [comment]
Masalah ini terjadi karena `.htaccess` bawaan cPanel atau yg biasa digunakan tidak bisa membedakan bahwa folder tempat template surat (`surat`) berbeda dengan controller dengan nama yg sama. Karena itulah disediakah contoh di file `htaccess.txt` script yg bisa membedakan.

Tetapi sebaiknya kita ubah nama folder `surat` menjadi `template-surat` untuk menghindari masalah ini, supaya script `.htacess` yg umum digunakan dapat berfungsi normal.

**Comment by eddieridwan** [comment]
Sudah dicommit ke `master` melalui PR #2759
