### ISSUE TITLE
Tambahkan batas administratif Dusun / RW / RT

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#2643]
### Bagaimana alurnya sampai muncul masalah?
1. buka info desa > wilayah administratif > buka peta dusun gambar peta wilayah > simpan
2. buka peta dusun dan gambar peta wilayah > simpan
3. buka menu peta > centang legenda desa dusun rw rt

### Seperti apa yang diharapkan?
agar ketika menggambar batas wilayah dapat menampilkan wilayah administratif batas dusun / rw / rt yang lain

### Apa yang terjadi?
menggambar peta dengan batas garis menjadi sedikit kerepotan karena tidak dapat batas wilayah yang bersebelahan sehingga beta batas menjadi berantakan

### Informasi tambahan 
![tes2](https://user-images.githubusercontent.com/35319600/73423319-5f1dd980-435e-11ea-8e11-f2f3f11bdb88.jpeg)
tambahkan peta administratif dusun , rw , rt

![tes](https://user-images.githubusercontent.com/35319600/73423349-78bf2100-435e-11ea-9efa-1e7a337f8821.jpeg)
hasil gambar jadi berantakan karena batas wilayah yang bersebelahan tidak tampil

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dicommit ke `master` melalui PR #2653
