### ISSUE TITLE
Tambah data statistik Kehamilan pada menu Statistik > Statistik Kependudukan

### ISSUE THREAD

**Issue by makhbub** [OpenSID/OpenSID#2645]
### Bagaimana alurnya sampai muncul masalah?
Menu statistik kependudukan merupakan menu untuk merekap statistik data kependudukan yang ada  di biodata penduduk seperti jumlah penyandang cacat, Golongan darah, Status Penduduk dll, dan data kehamilan belum ada di menu statistik, padahal data kehamilan ada di biodata penduduk

### Seperti apa yang diharapkan?
Statistik Kehamilan dimunculkan pada data statistik penduduk

### Apa yang terjadi?
jika tidak ada data kehamilan pada statistik penduduk, kami kesulitan membuat laporan jumlah kehamilan. meskipun data tersebut sebenarnya sudah ada di menu statistik > Laporan Penduduk Rentan, tapi untuk mengambil data dari situ kurang praktis karena melalui banyak step

### Informasi tambahan 
berikut kami tambahkan gambar biodata penduduk dan statistik penduduk, dimana seharusnya data di biodata penduduk ada di menu statistik, tapi untuk data kehamilan tidak ada
![statistik Hamil png2 png](https://user-images.githubusercontent.com/38773660/73426291-824c8700-4366-11ea-8b37-d74b2a2ddf25.png)
![statistik Hamil](https://user-images.githubusercontent.com/38773660/73426305-8bd5ef00-4366-11ea-821f-7981f44bee41.png)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
Laporan Kehamilan di Statistik #1759

issue yg sama, moga dpt dikerjakan

**Comment by mizwaruddin** [comment]
@afa28 ganda
