### ISSUE TITLE
share artikel belum menggunakan alamat slug

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#2646]
### Bagaimana alurnya sampai muncul masalah?
buka website demo > buka sembarang artikel > tekan tombol share 

### Seperti apa yang diharapkan?
menggunakan alamat slug

### Apa yang terjadi?
belum menggunakan slug / masih menggunakan id artikel

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
Maaf PR tergabung dengan PR yang Lainnya #2667

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR #2699
