### ISSUE TITLE
arsip artikel belum menggunakan alamat slug

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#2647]
### Bagaimana alurnya sampai muncul masalah?
buka website http://demo.opensid.my.id/first/arsip

### Seperti apa yang diharapkan?
alamat menggunakan alamat slug

### Apa yang terjadi?
alamat artikel masih menggunakan id artikel

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
Maaf PR tergabung dengan PR yang Lainnya

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR #2699
