### ISSUE TITLE
Ganti pasword layanan mandiri kurang efektik jika lokasinya di widget.

### ISSUE THREAD

**Issue by Imamayuti** [OpenSID/OpenSID#2649]
### Bagaimana alurnya sampai muncul masalah?
Ganti pasword layanan mandiri kurang efektik jika lokasinya di widget.

### Seperti apa yang diharapkan?
sebaiknya di ganti ke halaman layanan mandiri itu sendiri seperti pertama admin opensid login di halaman admin

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
mungkin bapak bisa ikut fitur premium, krn fitur ini tersedia di fitur tsb. Fitur ini belum rilis untuk umum, hanya untuk org/desa sj yg berlangganan fitur premium bisa menggunakannya.

**Comment by afa28** [comment]
Sudah tersedia di fersi premium.
