### ISSUE TITLE
Tampilan Mobile untuk halaman informasi publik masih berantakan

### ISSUE THREAD

**Issue by Imamayuti** [OpenSID/OpenSID#2650]
### Bagaimana alurnya sampai muncul masalah?
Tampilan Mobile untuk halaman informasi publik masih berantakan pada thema hadakewa

### Seperti apa yang diharapkan?
sebaiknya struktur koding informasi publik disamakan penulisannya seperti produk hukum biar lebih mudah di kembangkan pada thema yang lain.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dicommit ke `master` melalui PR #2689
