### ISSUE TITLE
Menu keuangan admin dengan akses tipe akses kontributor error

### ISSUE THREAD

**Issue by Imamayuti** [OpenSID/OpenSID#2651]
### Bagaimana alurnya sampai muncul masalah?
Menu keuangan admin dengan akses tipe kontributor error

### Seperti apa yang diharapkan?
Seharusnya muncul notifikasi seperti menu yang lain jika memang tidak memiliki akses

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
Di versi 20.06 sudah normal, setiap user hanya bisa mengakses menu sesuai level user mereka.
