### ISSUE TITLE
Buat checkbox untuk tampilkan password pada login ke sistem

### ISSUE THREAD

**Issue by benioke** [OpenSID/OpenSID#2654]
Bagaimana alurnya sampai muncul masalah?

Belum ada nya checkbox untuk menampilkan password ketika login

Seperti apa yang diharapkan?

Untuk mempermudah admin atau operator untuk memasukkan kan password nya.tanpa mengurangi keamanan sistem nya.karna fitur ini masih digunakan oleh beberapa sistem.

Proses login
![login1 copy](https://user-images.githubusercontent.com/47577404/73542614-ae9bfc80-4467-11ea-899b-fc858d6fdfa0.jpg)

Centang checkbox untuk melihat password
![login2 copy](https://user-images.githubusercontent.com/47577404/73542615-af349300-4467-11ea-9ad4-6bd3cd2add5c.jpg)

Apa yang terjadi?
Agak Menyulitkan pengguna ketika ingin login ke sistem.karna password menampilkan simbol.

Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.01
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dicommit ke `master` melalui PR #2656
