### ISSUE TITLE
Pengaturan Penomoran pada surat layanan bisa dia atur pengguna tergantung dari jenis surat

### ISSUE THREAD

**Issue by benioke** [OpenSID/OpenSID#2655]
Bagaimana alurnya sampai muncul masalah?
Belum ada nya pengaturan surat layanan pada surat tertentu. saat ini pengaturan yang terdapat pada sistem nya adalah

1.nomor berurutan untuk keseluruhan surat layanan
2.nomor berurutan untuk setiap surat  layanan dengan jenis yang sama

Seperti apa yang diharapkan?
Harus nya untuk surat layanan bisa di atur tergantung dari jenis surat layanannya.

Contoh kasus: Dari semua jenis surat layanan.ada beberapa surat yang penomoran nya tergantung jenis surat, mau penomoran berurutan semua jenis surat atau berurutan dengan jenis yang sama.

Misalkan: di sebuah desa terdapat 30 buah jenis surat layanan, semua nomor nya berurutan,  KECUALI surat keterangan untuk nikah(N1-N7) dan surat keterangan pindah penduduk yang berurutan dengan jenis yang sama. Jadi ketika ketika kita buat surat nikah atau surat pindah, nomor nya akan 1 walaupun nomor lain nya sampai 100.

Apa yang terjadi?
Akan lebih fleksibel jika surat bisa diatur menurut jenis dari surat itu
Contoh 
surat nikah
      Pilih kategori
1.nomor berurutan keseluruhan surat layanan
2.nomor berurutan jenis yang sama
Dan simpan
Maka hasil nya SELAIN surat nikah yang penomoran berurutan dengan jenis yang sama, maka surat lain penomoran nya berurutan semua.

Contoh 
surat keterangan pindah penduduk
      Pilih kategori
1.nomor berurutan keseluruhan surat layanan
2.nomor berurutan jenis yang sama
Dan simpan
Maka hasil nya SELAIN surat keterangan pindah penduduk yang penomoran berurutan dengan jenis yang sama, maka surat lain penomoran nya berurutan semua.

Jadi hasil nya..penomoran berurutan untuk semua layanan.KECUALI surat nikah dan surat keterangan pindah penduduk.Berlaku juga untuk surat lain dengan membuat pengaturan seperti itu.tergantung pengguna yang ingin pengaturan untuk masing masing surat.

Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.01
| Versi PHP        | 
| System operasi   |

**Comment by ZER07URN** [comment]
Mending dimasukkan dlm list group pak @benioke. Jd nanti disetting aplikasi ad tambahan pilihan cetak berdasarkan list group

**Comment by benioke** [comment]
Mksd nya bagaimana  pak ZER07URN

**Comment by balongbesuk** [comment]
Hampir sama urut surat sesuai jenis #1783,

**Comment by benioke** [comment]
Saya saya begitu... Hampir sama

**Comment by afa28** [comment]
> Saya saya begitu... Hampir sama

Apa yg hampur sma??🤔

**Comment by benioke** [comment]
Ya issue #1783 dan #2655 hampir sama urut surat sesuai jenis
