### ISSUE TITLE
Tampilan Statis Pada Peta Tidak Bisa Tampil Jika Nama Dusun Ada Spasi

### ISSUE THREAD

**Issue by asalreview** [OpenSID/OpenSID#2658]
### Bagaimana alurnya sampai muncul masalah?
Tampilan Statis Pada Peta Tidak Bisa Tampil Jika Nama Dusun Ada Spasi

### Seperti apa yang diharapkan?
bisa tampil 

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
Sudah ada di `master`
