### ISSUE TITLE
Tambah dan Ubah Data Lokasi Tempat Tinggal Bermasalah

### ISSUE THREAD

**Issue by asalreview** [OpenSID/OpenSID#2659]
### Bagaimana alurnya sampai muncul masalah?
add penduduk saat menambahkan lokasi tempat tinggal button update atau simpan tidak ada

### Seperti apa yang diharapkan?
lokasi tempat tinggal penduduk bisa di update langsung waktu tambah penduduk

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
Mungkin sulsi sementara, lakukan input data penduduk tanpa menambahkan lokasi. Kemudia update baru tambahkan lokasi, meski solusi ini agak merepotkan.

Alasannya kenapa tdk ada tombol simpan mungkin krn data[id] belum ada krn data penduduk belum disimpan, jd untuk solusi untuk hal ini lokasi disimpan sementara di session kemudian diambil ketika menambah penduduk.

Pak @eddieridwan , @fusionid

**Comment by afa28** [comment]
Issue yg berkaitan/sama #1958

**Comment by afa28** [comment]
Tambahan dr issue #1958:

Buka Penduduk > Penduduk Domisili > Cari Tempat Tinggal
Coba ubah lokasi tempat tinggal

Juga di

Keluarga > Tambah KK Baru, dan
Keluarga > Tambah Anggota Keluarga

**Comment by asalreview** [comment]
bagai jika saat selesai klik simpan atau tombol selanjutnya, bukan langsung
kembali ke menu penduduk melainkan tahapan tambah lokasi penduduk, jadi
dengan begini tidak perlu klik edit lagi.

Pada tanggal Min, 4 Okt 2020 pukul 16.09 Andi Fahruddin Akas <
notifications@github.com> menulis:

**Comment by afa28** [comment]
Tambahan Kasus Yang Sama https://github.com/OpenSID/OpenSID/issues/3018

Kronologi: Saat ubah biodata penduduk (mis: KTP semula "BELUM" diganti "KTP-EL") kemudian saya lanjutkan edit lokasi tempat tinggal penduduk (peta). Setelah saya isikan titik koordinat saya simpan, saya lihat field KTP-EL yg sdh sya ubah sebelumnya kembali ke "Pilih KTP El". Hal ini juga erlaku untuk field2 yh lain.

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR https://github.com/OpenSID/premium/pull/64
