### ISSUE TITLE
penambahan fitur untuk menghindari Artikel  bisa di copy paste

### ISSUE THREAD

**Issue by ahmadngudi** [OpenSID/OpenSID#2660]
### Seperti apa yang diharapkan?

artikel tidak bisa di copy, jika ada yg diklik kanan untuk di copy muncul keterangan copyright

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.02
| Versi PHP        | 
| System operasi   | Windows 10

**Comment by Nurhidayat29** [comment]
Bsa lebih jelas?
Dn kirim gambarnya bung @ahmadngudi

**Comment by ahmadngudi** [comment]
untuk menghindari copy paste artikel maksudnya pak,
intinya disnable klik kanan, jadi tidak bisa copas.

**Comment by pandigresik** [comment]
Menurut saya fitur semacam ini tidak diperlukan, kalau artikel sudah online maka kemungkinan bisa dicopy paste dengan mudah. Meskipun kita matikan fungsi klik kanan masih bisa diakali melalui inspect element dll. Atau dengan cara lainnya dengan cukup mudah

**Comment by luxmant354** [comment]
Sepakat dengan Mas Pandigresik 👍

**Comment by Nurhidayat29** [comment]
kalau ndak ingin dicopy ya berarti jngn buat artikel mas @ahmadngudi
