### ISSUE TITLE
Tidak bisa menghapus dokumen pada managemen dokumen

### ISSUE THREAD

**Issue by DamesDamai** [OpenSID/OpenSID#2661]
### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.02
| Versi PHP        | 
| System operasi   |

**Comment by MUHAMMADRANGSEL** [comment]
betul saya coba disitus http://demo.opensid.my.id juga tidak bisa dihapus
![image](https://user-images.githubusercontent.com/25834335/73855777-67a46300-47e9-11ea-9f67-3b7ae887f7c8.png)
![image](https://user-images.githubusercontent.com/25834335/73855866-84409b00-47e9-11ea-91f3-58682baa15a4.png)
yang muncul data berhasil disimpan bukan berhasil dihapus
![image](https://user-images.githubusercontent.com/25834335/73855892-8c98d600-47e9-11ea-9b4a-60844b3718e7.png)

**Comment by eddieridwan** [comment]
Sudah dicommit ke `master`
