### ISSUE TITLE
[Log Penduduk] surat kematian

### ISSUE THREAD

**Issue by afri18** [OpenSID/OpenSID#2663]
### Bagaimana alurnya sampai muncul masalah?
biar lebih akurat di tkp

### Seperti apa yang diharapkan?
di log penduduk bisa langsung membuat surat kematian
![image](https://user-images.githubusercontent.com/6611881/73899388-12d31c00-48bf-11ea-9190-cd85f4492601.png)

### Apa yang terjadi?
kadang data tidak ada / belum terinput
jadinya di layanan keterangan kematian nantinya bisa 2 pilihan data yg sudah terinpu dan belum

### Informasi tambahan 
biar pelayanan makin cepat

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.02
| Versi PHP        | 
| System operasi   |

**Comment by Nurhidayat29** [comment]
apakah sama formnya sama yang dicetak surat keterangan kematian pak?

**Comment by afri18** [comment]
Samakan saja, nantinya setiap desa menyesuaikan sendiri

**Comment by roaddee** [comment]
atau tidak dibuat sebaliknya saja pak, begitu kita buat surat kematian atas nama X, maka X akan masuk log_penduduk sebagai orang yang berstatus mati, jadi kita cukup membuat surat kematian saja,
karena kalau spt saat ini, untuk membuat surat kematian kita harus me 'MATI' kan dulu status nya, baru kita pindah menu untuk membuat surat kematian.

**Comment by afri18** [comment]
> atau tidak dibuat sebaliknya saja pak, begitu kita buat surat kematian atas nama X, maka X akan masuk log_penduduk sebagai orang yang berstatus mati, jadi kita cukup membuat surat kematian saja,
> karena kalau spt saat ini, untuk membuat surat kematian kita harus me 'MATI' kan dulu status nya, baru kita pindah menu untuk membuat surat kematian.

Belum tentu saat peristiwa dibutuhkan surat, isi log penduduk seperti biasa, saat simpan langsung surat kematian tercetak, nanti srt bisa di simpan dulu

**Comment by roaddee** [comment]
berarti cukup tombol link ke pembuatan surat kematian, karena surat_kematian perlu input pelapor dan saksi2

**Comment by apidong** [comment]
pak @vickyrolanda, mohon dianalisis. kebutuhannya seperti apa?

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1469
