### ISSUE TITLE
Perubahan NIP dan NIAP Pada Menu INFO DESA Sub Menu PEMERINTAHAN DESA

### ISSUE THREAD

**Issue by PWidodo** [OpenSID/OpenSID#2664]
### Bagaimana alurnya sampai muncul masalah?
Sesuai Surat Edaran Kemendagri Nomor 141/978/SJ tanggal 3 Pebruari 2020 yang telah dikirimkan Kepala Bupati/Walikota se- Indonesia tentang Program Fasilitasi Pembuatan Nomor Induk Kepala Desa (NIKD) dan Nomor Induk Perangkat Desa (NIPD) .

### Seperti apa yang diharapkan?
Perlu diadakan penyesuaian penyebutan dari NIP menjadi NIKD (untuk Kepala Desa) dan NIPD (untuk Perangkat Desa). serta menghilangkan NIK.
![Screenshot_1](https://user-images.githubusercontent.com/45189822/73971039-c801e480-4950-11ea-8133-3c9bcb362477.jpg)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.02
| Versi PHP        | 7
| System operasi   | Windows

**Comment by PWidodo** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/45189822/73971310-3a72c480-4951-11ea-99aa-2259cac21728.jpg)

**Comment by PWidodo** [comment]
![Screenshot_3](https://user-images.githubusercontent.com/45189822/73971643-d69ccb80-4951-11ea-84cd-11c417d75387.jpg)

**Comment by WAHYUDIK** [comment]
sekedar usul saja pak...alangkah baiknya tidak serta merta langsung di ganti NIP menjadi NIPD,  akan lebih baik jika kita cukup tambahkan menjadi NIP/NIPD, dengan alasan terkadang ketika dalam proses pilkades, kepala desa akan digantikan oleh Penjabat, dimana penjabat tersebut berasal dari PNS setempat, sehingga tetap membutuhkan kolom NIP, begitupun juga untuk yang perangkat desa,  menjaga kemungkinan ada perangkat desa yang berasal dari PNS.

**Comment by balongbesuk** [comment]
Perlu dipikirkan juga untuk pengguna kelurahan yg mayoritas PNS

**Comment by afa28** [comment]
Sudah di `master`
