### ISSUE TITLE
Agenda Hilang dan Tidak Muncul ketika di tambahkan

### ISSUE THREAD

**Issue by mr703** [OpenSID/OpenSID#2666]
### Bagaimana alurnya sampai muncul masalah?
Setelah di Update ke 20.02 pasca, Agenda hilang/tidak tampil dan Agenda baru yang baru yang dibuat tidak muncul di widget agenda.

### Seperti apa yang diharapkan?
Agenda yang baru dibuat hendaknya muncul di widget agenda dan tidak tampil pada halaman artikel, karena agenda adalah halaman statis.

### Apa yang terjadi?
Agenda baru tidak muncul di widget agenda

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.02pasca
| Versi PHP        | 
| System operasi   | windows

**Comment by hasap86** [comment]
betul, ngalamin juga begini...

**Comment by eddieridwan** [comment]
@hasap86 @mr703 , saya sdh coba dan normal saja. 
Apakah membuat agenda menggunakan menu di gambar berikut:
<img width="1390" alt="artikel-agenda" src="https://user-images.githubusercontent.com/249563/74094575-ba5a8380-4b37-11ea-99f6-8406494ba8fd.png">

Apakah artikel yg dihasilkan berstatus aktif? Lampirkan tampakan layar artikel yg anda buat di `Admin Web > Artikel > Agenda`. Lampirkan tampakan layar daftar agenda yg ada di `Admin Web > Artikel > Agenda`. Lampirkan tampakan layar widget agenda.

Apakah ada error di file di folder `logs`?

SELALU usahakan memberikan info selengkapnya supaya masalahnya bisa ditelusuri.

**Comment by mr703** [comment]
Ini Tampilan di Admin Web > Artikel > Agenda 
![Screenshot_20200209-123425_Chrome](https://user-images.githubusercontent.com/50432012/74096981-d6aaf000-4b38-11ea-8ae7-f35b2b625755.jpg)

Ini Tampilan di Web 
![Screenshot_20200209-123534_Chrome](https://user-images.githubusercontent.com/50432012/74096988-e88c9300-4b38-11ea-8987-f895e1187d29.jpg)

**Comment by eddieridwan** [comment]
Ooh.. itu karena anda menggunakan tema natra. Cek apakah tema itu sudah disesuaikan dengan versi OpenSID terkini (v20.02-pasca). Setiap tema yg bukan bawaan rilis (default, hadakewa) perlu menyesuaikan dengan perubahan di setiap rilis OpenSID. Hanya tema bawaan rilis yang diperiksa pada waktu melakukan rilis. 

Ok, issue ini akan ditutup, karena bukan error di rilis.

**Comment by eddieridwan** [comment]
Silakan buat issue di repo tema ybs : https://github.com/OpenSID/tema-natra/issues
