### ISSUE TITLE
Penambahan Fitur Jumlah "Telah Dibaca" pada artikel

### ISSUE THREAD

**Issue by mr703** [OpenSID/OpenSID#2667]
### Bagaimana alurnya sampai muncul masalah?
Setiap artikel yang dibuat tidak ada indikator berapa kali telah dibaca atau dilihat.

### Seperti apa yang diharapkan?
Setiap artikel yang diterbitkan dapat dilihat berapa jumlah yang telah dibaca sehingga dapat diketahui seberapa aktifnya sipembaca pada artikel yang dibuat, SEO Pages.

### Apa yang terjadi?
Setiap artikel tidak diketahui jumlah pembacanya.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.02pasca
| Versi PHP        | 
| System operasi   | windows

**Comment by agilbarker** [comment]
fitur itu perlu penambahan field pada table artikel, contoh field yang di tambah "dibaca"

penambahan coding pada singgle artikel 
"
<?php $this->db->query("UPDATE artikel SET  dibaca=dibaca+ 1 WHERE id='".$single_artikel['id']."' ") ?>
"

view untuk setiap artikel 
"
<?= $single_artikel['dibaca'] ?> dibaca
"
demo penerapan : https://sukoharjo2.desa.id

**Comment by Nurhidayat29** [comment]
> fitur itu perlu penambahan field pada table artikel, contoh field yang di tambah "dibaca"
> 
> penambahan coding pada singgle artikel
> "
> $this->db->query("UPDATE artikel SET dibaca=dibaca+ 1 WHERE id='".$single_artikel['id']."' ")
> "
> 
> view untuk setiap artikel
> " $single_artikel['dibaca'] x dibaca"
> 
> demo penerapan : https://sukoharjo2.desa.id

apakah sdh ada ditema khobor?
jika mmng diperlukan bung @agilbarker bsa mengirimkn PR untuk digabung ke tema default dan hadakewa.

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR #2703

**Comment by afa28** [comment]
Maaf Pak @eddieridwan , ini masih ada error di Log saat dilakukan migrasi berulang kali krn kolom sudah ada (duplicate).
