### ISSUE TITLE
data tidak sengaja terhapus

### ISSUE THREAD

**Issue by antonsyahputra** [OpenSID/OpenSID#2669]
### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by Nurhidayat29** [comment]
mohon lebih detail jika mengirim issue, silahkan baca panduan dlu dan jga silahkan bertanya di facebook.com/groups/OpenSID.

**Comment by eddieridwan** [comment]
Issue ini ditutup karena bukan masalah untuk perbaikan script. Harap bertanya masalah penggunaan di facebook.com/groups/OpenSID
