### ISSUE TITLE
[Widget] Nilai di widget keuangan tidak sesuai dgn data untuk pendapatan dan belanja

### ISSUE THREAD

**Issue by fusionid** [OpenSID/OpenSID#2671]
### Bagaimana alurnya sampai muncul masalah?
Modul transparansi keuangan telah diperbaiki, termasuk cara mengambil data dari tabel data Siskeudes supaya nilai yg ditampilkan di laporan dan di grafik keuangan benar (termasuk Grafik Utama, Grafik Artikel dan Widget keuangan).

Data di Tabel, Grafik Utama dan Grafik Artikel sudah benar tetapi di Widget keuangan nilainya masih kurang untuk pendapatan dan belanja

### Seperti apa yang diharapkan?
Nilai di widget keuangan nilainya sesuai dengan data untuk pendapatan dan belanja

### Apa yang terjadi?
Library highchart hanya bisa menerima 2 parameter saja.
Misalnya realisasi pendapatan hanya dari 1 parameter saja yaitu data table tbp saja, tetapi seharusnya dari 2 parameter yaitu tbp dan mutasi.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
Apakah ini masih bermasalah???
