### ISSUE TITLE
XSS Bug

### ISSUE THREAD

**Issue by johanesrakinaung** [OpenSID/OpenSID#2678]
### Bagaimana alurnya sampai muncul masalah?
memasukan <script>alert("TES");</script>
pada kolom komentar artikel
### Seperti apa yang diharapkan?

buat script untuk filter XSS script

### Apa yang terjadi?

script di atas tereksekusi

### Informasi tambahan 
My email : johanesrakinaung@gmail.com
Facebook : Johanes Farly Rakinaung
| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by balongbesuk** [comment]
Thema mana? Kl bawaan sy rasa sudah d tutup?

**Comment by johanesrakinaung** [comment]
Admin panel dan view artikelnya

**Comment by eddieridwan** [comment]
Masalah ini tidak ditemukan lagi di tema bawaan rilis (tema default/hadakewa). Anda menggunakan tema apa? Apakah bisa ditunjukkan masalah ini di website https://demo.opensid.my.id?

**Comment by balongbesuk** [comment]
tambah surat baru bisa disisipi script pak eddie

**Comment by balongbesuk** [comment]
data penduduk juga bisa disisipi script

**Comment by balongbesuk** [comment]
surat masuk juga bisa disisipi script

**Comment by balongbesuk** [comment]
surat keluar juga bisa disisipi script

**Comment by balongbesuk** [comment]
produk hukum jg bs disisipi script

**Comment by balongbesuk** [comment]
tambah klasifikasi surat jg bs disisipi script

**Comment by balongbesuk** [comment]
analis jg bisa disisipi script

**Comment by balongbesuk** [comment]
tambah peserta program bantuan

**Comment by balongbesuk** [comment]
pertanahan

**Comment by balongbesuk** [comment]
tambah data peta baru

**Comment by balongbesuk** [comment]
kirim pesan sms

**Comment by balongbesuk** [comment]
tambah pengguna baru

**Comment by balongbesuk** [comment]
tambah menu

**Comment by balongbesuk** [comment]
admin web > komentar > edit komentar > isi script

**Comment by balongbesuk** [comment]
tambah album

**Comment by balongbesuk** [comment]
sepertinya xss filteringnya lepas?

**Comment by fusionid** [comment]
Untuk halaman Web Public hampir semuanya sudah menerapkan XSS Filtering, namun untuk halaman Web Admin hampir semuanya belum memakai XSS Filtering. 

Terlepas dari apakah perlu untuk halaman Web Admin memakai xss filtering, berikut sample kasus dan penanganannya : 

1. Sample file : controller/Plan.php

2. Menu Pemetaan -> Pengaturan Peta -> Lokasi -> Tambah Data Baru -> Nama Lokasi / Properti : diisi <script>alert("TES");</script> -> Simpan
![xss1](https://user-images.githubusercontent.com/10391199/74698767-88c97280-5231-11ea-9854-833719853999.PNG)

3. Halaman terinjeksi script : 
![xss2](https://user-images.githubusercontent.com/10391199/74698785-95e66180-5231-11ea-8e90-2fbd8a3a75d7.PNG)

4. Edit dan tambahkan xss filtering pada file controller/Plan.php

Script sebelum xss filtering:

`public function form($p = 1, $o = 0, $id = '')
	{
		$data['p'] = $p;
		$data['o'] = $o;

		$data['desa'] = $this->plan_lokasi_model->get_desa();
		$data['list_point'] = $this->plan_lokasi_model->list_point();
		$data['dusun'] = $this->plan_lokasi_model->list_dusun();

		if ($id)
		{
			$data['lokasi'] = $this->plan_lokasi_model->get_lokasi($id);
			$data['form_action'] = site_url("plan/update/$id/$p/$o");
		}
		else
		{
			$data['lokasi'] = NULL;
			$data['form_action'] = site_url("plan/insert");
		}

		$header= $this->header_model->get_data();

		$header['minsidebar'] = 1;
		$nav['act_sub'] = 8;
		$nav['tip'] = 3;

		$this->load->view('header', $header);
		$this->load->view('nav', $nav);
		$this->load->view('lokasi/form', $data);
		$this->load->view('footer');
	}`

Script sesudah xss filtering: 
Penambahan : `$data = $this->security->xss_clean($data);` , data disaring sebelum dieksekusi.

`public function form($p = 1, $o = 0, $id = '')
	{
		$data['p'] = $p;
		$data['o'] = $o;

		$data['desa'] = $this->plan_lokasi_model->get_desa();
		$data['list_point'] = $this->plan_lokasi_model->list_point();
		$data['dusun'] = $this->plan_lokasi_model->list_dusun();

		if ($id)
		{
			$data['lokasi'] = $this->plan_lokasi_model->get_lokasi($id);
			$data['form_action'] = site_url("plan/update/$id/$p/$o");
		}
		else
		{
			$data['lokasi'] = NULL;
			$data['form_action'] = site_url("plan/insert");
		}

		$header= $this->header_model->get_data();

		$header['minsidebar'] = 1;
		$nav['act_sub'] = 8;
		$nav['tip'] = 3;

		$data = $this->security->xss_clean($data);

		$this->load->view('header', $header);
		$this->load->view('nav', $nav);
		$this->load->view('lokasi/form', $data);
		$this->load->view('footer');
	}`

5. XSS Filtering sudah berjalan dan script injeksi tidak akan dieksekusi serta diganti dengan "[removed]alert("
![xss3](https://user-images.githubusercontent.com/10391199/74699717-00989c80-5234-11ea-9c14-04194a5ffbb6.PNG)

**Comment by eddieridwan** [comment]
Sebaiknya di atasi dulu dengan validasi, kalau bisa. Saat ini memang di Admin validasi sangat terbatas. Lihat contoh di commit https://github.com/OpenSID/OpenSID/commit/2e71a2e005798c61619faa32c46ad754b348d0d5 untuk menambah surat baru. Karena memang nama surat seharusnya tidak berisi karakter selain alphanumerik dan spasi.

**Comment by eddieridwan** [comment]
Ini contoh satu lagi validasi form surat masuk, sekaligus mencegah serangan XSS. Karena sering perlu isian hanya berisi alfanumerik + spasi, dibuatkan helper `alfanumerik_spasi($str)`.

Silakan lihat commit https://github.com/OpenSID/OpenSID/commit/6b5a2ed14a10d9425acc7ed649f8b387da1725e3 

Ayo, siapa yg akan meneruskan?

**Comment by eddieridwan** [comment]
Sudah ditambahkan validasi untuk surat keluar di commit https://github.com/OpenSID/OpenSID/commit/ed1c803f7f1d547504795eb85c2ff5c01612d7fa.

**Comment by masumo** [comment]
> produk hukum jg bs disisipi script --> sudah diperbaiki

ada tambahan fungsi validasi di **Web_dokumen_model** tetapi saya lihat kebanyakan memakai fungsi strip_tags()
kalo saya baca di bbrp referensi, strip_tags() belum cukup aman utk cegah XSS 
fungsi yang disarankan adalah htmlspecialchars() 
apakah perlu saya ubah fungsi strip_tags menjadi htmlspecialchars? 

https://stackoverflow.com/questions/3605629/prevent-xss-with-strip-tags

**Comment by eddieridwan** [comment]
@masumo , terima kasih telah melakukan pembacaan masalah keterbatasan `strip_tags()`. Kalau dibaca sampai akhir posting tersebut, terlihat rekomendasi menggunakan `htmlentities()` yg lebih menyeluruh dibanding `htmlspecialchars()`. Di beberapa tempat, `htmlentities()` sudah mulai digunakan menggantikan `strip_tags()`. Silakan ganti `strip_tags()` yg ditemukan dengan `htmlentities()`.

**Comment by masumo** [comment]
oke pak @eddieridwan

**Comment by eddieridwan** [comment]
Issue ini ditutup, karena form/modul yg belum dikerjakan sudah disalin ke issue terpisah.
