### ISSUE TITLE
Tambah Album di Gallery error

### ISSUE THREAD

**Issue by git-rohen** [OpenSID/OpenSID#2679]
### Bagaimana alurnya sampai muncul masalah?
menu->admin web->galery->tambah album

### Apa yang terjadi?
![image](https://user-images.githubusercontent.com/61135752/74629793-ab08b500-518b-11ea-8b18-bea5c57b5f7a.png)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP       | 7.
| System operasi  | Ubuntu Server

**Comment by eddieridwan** [comment]
@git-rohen , perbaikan sudah dicommit ke `master`.
