### ISSUE TITLE
mohon pencerahan

### ISSUE THREAD

**Issue by jeblackjocker** [OpenSID/OpenSID#2680]
### Bagaimana alurnya sampai muncul masalah?
saya menginstal opensid pada webhost 

### Seperti apa yang diharapkan?
mengonlinekan opensid saya

### Apa yang terjadi?

![FireShot Capture 061 - Database Error - malatadedi 000webhostapp com](https://user-images.githubusercontent.com/59815167/74637045-2d9d6e80-51a4-11ea-9c4d-d3e4948a198d.png)

### Informasi tambahan 
mohon turtor mengonlinekan opensid #video  

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Masalah ini dialami oleh pengguna hosting 000webhost.com lainnya.

Ini pembahasannnya: https://www.000webhost.com/forum/t/database-error-no-1231/173568/8

Ini solusi yg mereka tawarkan:
![striction](https://user-images.githubusercontent.com/249563/74689641-186e2180-5230-11ea-8cd6-c41f9fc25e1c.png)

Tapi sebaiknya lakukan ini di file `desa/config/config.php` supaya tidak ditiban pada waktu update ke rilis OpenSID baru.

Ok, issue ini akan ditutup, karena bukan sesuatu untuk diperbaiki di OpenSID sendiri.
