### ISSUE TITLE
Wilayah Desa yang lebih dari satu hanya tersimpan pada gambar terakhir

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#2682]
### Bagaimana alurnya sampai muncul masalah?
buka info desa > identitas desa > peta wilayah desa > gambar wilayah desa lebih dari dua bagian

### Seperti apa yang diharapkan?
gambar wilayah dapat tersimpan semua

### Apa yang terjadi?
hanya tersimpan gambar dibagian akhir

### Informasi tambahan 

contoh wilayah desa yang lebih dari dua bagian / tidak satu kesatuan

![Untitled12](https://user-images.githubusercontent.com/35319600/74743663-636d5080-5293-11ea-9eca-62a6c6b7c9d6.jpg)

![Untitled1](https://user-images.githubusercontent.com/35319600/74743673-6700d780-5293-11ea-842c-3968bff22d48.jpg)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by fusionid** [comment]
Apakah mungkin ada 1 wilayah desa tapi terpisah 2 bagian ?

**Comment by balongbesuk** [comment]
saya juga kaget ada desa yang seperti diatas pak saya ambil langsung dari google map, mojotrisno jombang dan kauman jombang, yang baru terdeteksi wilayah desanya seperti itu,

**Comment by afa28** [comment]
Duplicate issue https://github.com/OpenSID/OpenSID/issues/3464
