### ISSUE TITLE
Tabel dan Grafik Statistik Pengunjung Website

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#2683]
### Bagaimana alurnya sampai muncul masalah?
Belum adanya tabel atau grafik penyajian data pengunjung website baik berupa pengunjung harian, mingguan, bulanan, maupun tahunan. Sehingga kesulitan dalam rekap statistik pengunjung website.

### Seperti apa yang diharapkan?
Adanya tabel data maupun grafik statistik pengunjung website agar dapat disajikan berupa laporan bulanan tentang perkembangan pengunjung website.

### Apa yang terjadi?
Saat ini sudah tersedia tabel "sys_traffic" pada database dengan tanggal dan jumlah pengunjung sesuai tanggal tersebut.
![Tanpa judul](https://user-images.githubusercontent.com/46939846/74748992-02964600-529c-11ea-81bc-a34bd091cd1f.png)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by hasap86** [comment]
Setuju inih

**Comment by afa28** [comment]
Apa menu seperti ini?

![Untitled](https://user-images.githubusercontent.com/57283157/75095617-528d4980-55c9-11ea-8e2b-649e35607a95.png)

**Comment by eddieridwan** [comment]
Sudah dicommit ke `master` melalui PR #2715
