### ISSUE TITLE
cetak dan unduh arsip layanan 

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#2687]
### Bagaimana alurnya sampai muncul masalah?
Ketika ingin cetak dan unduh arsip layanan untuk 1 tahun, arsip yang bisa tercetak dan diunduh hanya 500 surat, sedangkan surat dalam 1 tahun bisa lebih satu ribu

### Seperti apa yang diharapkan?
ketika ingin mencetak dan unduh arsip layanan semua bisa tercetak

### Apa yang terjadi?
arsip layanan tidak bisa tercetak semua

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
Mau testing tp data masih pakai db awal.

**Comment by afa28** [comment]
https://id.m.wikipedia.org/wiki/Daftar_suku_bangsa_di_Indonesia_menurut_jumlah_penduduk

**Comment by afa28** [comment]
Catatan :
1. Gunakan format cetak yg sudah disediakan (cek : modul RTM)
2. Ubah LIMIT menjadi 0 (cek : modul RTM)
3. Dll

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3840
