### ISSUE TITLE
Jangan munculkan artikel agenda di artikel terkini

### ISSUE THREAD

**Issue by afri18** [OpenSID/OpenSID#2690]
### Bagaimana alurnya sampai muncul masalah?
saat membuat agenda
ternyata disamping muncul di agenda desa juga ada di artikel terkini
![image](https://user-images.githubusercontent.com/6611881/75102157-bc354400-5619-11ea-9526-46f379baffce.png)

### Seperti apa yang diharapkan?
artikel agenda desa jangan ada di artikel terkini cukup di widget Agenda Desa
![image](https://user-images.githubusercontent.com/6611881/75102171-e981f200-5619-11ea-8f26-e78b06ba74f1.png)

### Apa yang terjadi?
karna ini hanya agenda tapi tampil di artikel terkini jadinya tampilan web tidak menarik

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
Sesuai issue #2299

**Comment by eddieridwan** [comment]
Sudah dicommit ke `master` melalui PR #2690
