### ISSUE TITLE
Link Pada Detail Agenda Masih Mengunakan Id

### ISSUE THREAD

**Issue by afa28** [OpenSID/OpenSID#2692]
### Bagaimana alurnya sampai muncul masalah?
Link Pada Detail Agenda Masih Mengunakan Id

### Seperti apa yang diharapkan?
Link Pada Detail Agenda Masih Mengunakan slug

### Apa yang terjadi?
seragam

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR #2694
