### ISSUE TITLE
Apa Fungsi Checkbox Pada Pengaturan Modul & Sub Modul ???

### ISSUE THREAD

**Issue by afa28** [OpenSID/OpenSID#2695]
### Bagaimana alurnya sampai muncul masalah?
Fungsi checkbox biasa digunakan untuk melakukan tugas secara sekaligus, misal menghapus beberapa data sekaligus. Tapi pada Modul dan Submodul fungsinya tidak jelas, hanya jadi pajangan.

### Seperti apa yang diharapkan?
Kalau tdk diguanakan checkbox pada Modul dan Submodul dihapus saja dan codingan yg bersangkutan.

### Apa yang terjadi?
Mengurangi size file dan menghapus sesatu yg tdk digunakan

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR #2696
