### ISSUE TITLE
Urut Agenda menurut tanggal kegiatan, menurun

### ISSUE THREAD

**Issue by afri18** [OpenSID/OpenSID#2702]
### Bagaimana alurnya sampai muncul masalah?
Saat membuat agenda yg banyak di tampilan widget nya tidak berurutan
![Screenshot_20200224-150031~2](https://user-images.githubusercontent.com/6611881/75136383-25e74800-5717-11ea-866c-52ea04fa3726.png)

### Seperti apa yang diharapkan?
Walau tanggal uploadnya nggak urutan namun tgl agendanya berurutan dari. Yg paling dekat

### Apa yang terjadi?
Diprotes pembacs kok nggak urut

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.02pasca
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah ada di `master`.
