### ISSUE TITLE
Menggunakan Helper Slug

### ISSUE THREAD

**Issue by afa28** [OpenSID/OpenSID#2704]
### Bagaimana alurnya sampai muncul masalah?
Masih ada beberapa yang menggunakan penulisan slug yang panjang

### Seperti apa yang diharapkan?
Menggunakan helper slug yg sudah dibuat

### Apa yang terjadi?
Syntax jd pendek

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dicommit melalui PR #2705
