### ISSUE TITLE
Autocomplete Halaman Modul Tidak Berjalan Sebagai Mana Mestinya

### ISSUE THREAD

**Issue by afa28** [OpenSID/OpenSID#2706]
### Bagaimana alurnya sampai muncul masalah?
Lakukan pencarian pada pengaturan modul, maka autocomplete tidak berjalan.

### Seperti apa yang diharapkan?
autocompleate berjalan sebagaimana mestinya

### Apa yang terjadi?
autocompleate bisa digunakan kembali

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dicommit ke `master` melalui PR #2707
