### ISSUE TITLE
Tampilkan Dokumen Penduduk di tab terpisah

### ISSUE THREAD

**Issue by afri18** [OpenSID/OpenSID#2710]
### Bagaimana alurnya sampai muncul masalah?
saat klik link dokumen terbuka di jendela yang sama
![image](https://user-images.githubusercontent.com/6611881/75206966-28df4880-57aa-11ea-833e-513736ee6632.png)

### Seperti apa yang diharapkan?
sebaiknya saat klik link dokumen terbuka di jendela baru

### Apa yang terjadi?
kadang suka lupa langsung di tutup jadinya mesti masuk kembali

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.02pasca
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sdh di commit ke `master` melalui PR #2711.

@afri18 tapi mohon perhatian, ke depan untuk mengakses dokumen kependudukan, harus diunduh karena alasan keamanan. Jadi pengguna tidak bisa melihat lokasi dokumen lagi. Lihat contoh di Produk Hukum dan Informasi Publik.
