### ISSUE TITLE
[Widget] Widget Artikel Terkini (Terakhir Dibaca)

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#2712]
### Bagaimana alurnya sampai muncul masalah?
Sesuai Pull #2667: Catat dan tampilkan berapa kali suatu artikel telah dibaca.
Kini sudah tersedia fitur Artikel Telah Dibaca, namun pengunjung belum bisa mengetahui artikel terakhir yang telah dibaca.

### Seperti apa yang diharapkan?
Tersedianya menu Artikel Terkini (terakhir dibaca) untuk setiap artikel yang terakhir dikunjungi.
Bisa ditampilkan pada Widget Arsip Artikel pada tab | Terkini | Terbaru | Acak |.
dengan susunan sebagai berikut:
- Terkini (untuk menampilkan artikel terakhir dikunjungi)
- Terbaru (untuk menampilkan artikel terbaru yang dibuat admin)
- Acak (untuk menampilkan artikel secara acak)

Mulai dari baru saja dibaca, sekian detik yg lalu, sekian menit yang lalu, sekian hari yang lalu, sekian minggu yang lalu, dan seterusnya.

### Apa yang terjadi?
Dapat mengetahui artikel terakhir yang dikunjungi/dibaca oleh pengunjung.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
@ariandii , Artinya ada penambahan field baru (last read) untuk menyimpan tgl update artikel terbaca???

**Comment by afa28** [comment]
Kenapa bukan artikel populer sja pak @ariandii ??? Jd datanya di urutkan berdasar hit terbanyak

**Comment by ariandii** [comment]
menurut saya, kalau artikel populer yg muncul di halaman widget hanya artikel itu itu aja.

yg populer semakin populer, yang jarang dibaca tidak muncul muncul. 😊

**Comment by afa28** [comment]
iya jg sih 🤣
