### ISSUE TITLE
Bilangan Ribuan Pada Hit Artikel

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#2716]
### Bagaimana alurnya sampai muncul masalah?
Sesuai Pull #2667: Catat dan tampilkan berapa kali suatu artikel telah dibaca.
Kini setiap klik artikel baru, akan menambah hit, namun angka pada hit tersebut jika sudah 1000 kali dibaca, akan tertulis 1000 bukan 1.000

### Seperti apa yang diharapkan?
Dapat muncul angka hit dengan pemisah ribuan.

### Apa yang terjadi?
Hit yg sudah mencapai seribu lebih, akan muncul misal menjadi 1.109

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
Buat helpernya, mengenai penulisan

**Comment by ariandii** [comment]
siap, besok saya pull pak, tadi laptop habis batrai. chargernya ketinggalan dikantor.

**Comment by eddieridwan** [comment]
Sudah dicommit ke `master` melalui PR #2722
