### ISSUE TITLE
Gunakan Model Config Yang Sudah DIsediakan

### ISSUE THREAD

**Issue by afa28** [OpenSID/OpenSID#2717]
### Bagaimana alurnya sampai muncul masalah?
Tiap model selalu buat fuction untuk meload data config, jd kurang efisien.

### Seperti apa yang diharapkan?
Buat helper config/pangil mdoel config yang sudah disediakan

### Apa yang terjadi?
Menyederhanakan sintaks dan efisiensi.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
beberapa model membuat fuction config sendiri pd hal fuction sama dgn yg ad di modul lain. Bisa diserderhanakan dgn mengambil 1 config sumber, baik itu pada model condig atau buatkan herper config.

**Comment by sup-ham** [comment]
Sudah ada `Setting_model` yang  sudah juga di-autoload. Maksudnya yang mana nih?

https://github.com/OpenSID/OpenSID/blob/af68bc3b4087e99d579587b324978e1fbd9931ed/donjo-app/config/autoload.php#L135

**Comment by afa28** [comment]
> Sudah ada `Setting_model` yang sudah juga di-autoload. Maksudnya yang mana nih?
> 
> https://github.com/OpenSID/OpenSID/blob/af68bc3b4087e99d579587b324978e1fbd9931ed/donjo-app/config/autoload.php#L135

Maksudnya ada beberapa model yg membuat sendiri fuction config, jd tdk efisien. pd hal kan bisa langsung panggil config model tanpa buat fuction baru.

**Comment by eddieridwan** [comment]
Sudah dicommit melalui PR #2738
