### ISSUE TITLE
Statistik Pengunjung Website

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#2718]
### Bagaimana alurnya sampai muncul masalah?
![perbaiki](https://user-images.githubusercontent.com/46939846/75310480-af695800-5886-11ea-9c7e-efedb93de0dc.png)

![perbaiki](https://user-images.githubusercontent.com/46939846/75310830-80071b00-5887-11ea-9ebd-939c721ad516.png)

### Seperti apa yang diharapkan?
Sesuai dengan judul kolom hanya menampilkan statistik bulan februari 2020.

### Apa yang terjadi?
Saat ini pada grafik muncul bulan februari tahun sebelumnya juga.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
terima kasih pak, mungkin krnbsy kirang data jd hal sepeeti ini muncul. sy lupa filter tahunnya 🤣. nanti sy perbaiki, krn ini baru mungkin sy perlu masukan.

**Comment by afa28** [comment]
mohon masukannya

**Comment by afa28** [comment]
Pak @ariandii , bisa minta backup sql untuk tabel data sys_traffic untuk ujicoba krn data yg saya pakai minim pengunjung(data bawaan)

**Comment by afa28** [comment]
Apakah Sudah Sesuai Pak @ariandii ??? Mungkin Sudah Bisa Diclose Issuenya Pak @ariandii @eddieridwan

**Comment by ariandii** [comment]
Terima kasih.

**Comment by afa28** [comment]
Sama2 pak @ariandii

**Comment by afa28** [comment]
Kayaknya masih ad yg salah pak @eddieridwan , @ariandii . Saya cek di website demo.

![Screenshot_2020-02-27-00-22-25-07](https://user-images.githubusercontent.com/57283157/75365304-fcd1dd80-58f7-11ea-8567-417add4e89d3.png)

Atau belum di update terbaru???

**Comment by nanangnursinggih** [comment]
Pak kalau kasi kosong kembali data pengunjungnya bagai mana

**Comment by andifahruddinakas** [comment]
Belum tersedia, seharusnya saat instalasi awal data dikosongkan terlebih dahulu. Silahkan buat issueenya jika mmang dibutuhkan.

untuk sementara, solusinya bisa dengan menghapus isi data table `sys_traffic`
