### ISSUE TITLE
Sembunyikan tampilan data 0 di statistik web

### ISSUE THREAD

**Issue by afri18** [OpenSID/OpenSID#272]
![image](https://cloud.githubusercontent.com/assets/6611881/22786381/dedef0ec-ef0a-11e6-8ffe-b414483583b9.png)

bisa nggak ya ??? saat klik ini atau data desa nilai yang menunjukan nol (0) tidak terbawa, karna kalau dilihat telalu anyak nilai nol, terutama statistik pekerjaan

**Comment by eddieridwan** [comment]
Sudah dicommit ke `master` melalui PR #2899
