### ISSUE TITLE
Folder Rentan Diakses Public

### ISSUE THREAD

**Issue by afa28** [OpenSID/OpenSID#2723]
### Bagaimana alurnya sampai muncul masalah?
Beberapa Folder Bisa Diakses Karena Tidak Ada File Index
Salah Satu Contoh Akses Folder excel  http://namawebsite/excel/

### Seperti apa yang diharapkan?
Folder/file tidak dapat diakses

### Apa yang terjadi?
File aman

### Informasi tambahan 
Solusi :
1. copy file index ke folder jika tidak mengaktifkan htaccess
2. ubah htaccess dengan menambahkan : Options All -Indexes

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dicommit ke `master` melalui PR #2724
