### ISSUE TITLE
Error 404 ketika mengakses Keuangan dengan tipe akses kontributor dan redaksi

### ISSUE THREAD

**Issue by asalreview** [OpenSID/OpenSID#2729]
### Bagaimana alurnya sampai muncul masalah?
Error 404 ketika mengakses Keuangan dengan tipe akses kontributor dan redaksi

### Seperti apa yang diharapkan?
Tidak error melainkan muncul notifikasi tidak memiliki akses seperti menu yang lain.

### Apa yang terjadi?
![image](https://user-images.githubusercontent.com/60563749/75397415-5b637f80-5929-11ea-89e8-f22ab6047d77.png)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by dikisiswanto** [comment]
Menurut saya menu keuangan tidak perlu ditampilkan jika yang melakukan akses ke dashboard adalah kontributor dan redaksi.

**Comment by asalreview** [comment]
@dikisiswanto sangat setuju.

**Comment by afa28** [comment]
Ini masih error yah???

**Comment by afa28** [comment]
Sdah diperbaiki, menu yg ditampilkan bedasarkan group user masing2.
