### ISSUE TITLE
Menu Siluman

### ISSUE THREAD

**Issue by afa28** [OpenSID/OpenSID#2730]
### Bagaimana alurnya sampai muncul masalah?
Tambah menu baru, pilih jenis link, link tp jgn isi nama. Klik simpan, ini akan berhasil menyimpan menu walau nama menu kosong.

### Seperti apa yang diharapkan?
Nama menu tdk boleh kosong

### Apa yang terjadi?
Jika tampil di halaman depan website, nampak aneh. Ada tp tdk nampak.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by asalreview** [comment]
class="form-control input-sm required"

**Comment by asalreview** [comment]
di album galery juga bos.

**Comment by afa28** [comment]
pak @asalreview , coba mulai berkontribusi dgn menyelesaikan issue yg sederhana

**Comment by asalreview** [comment]
@afa28 tidak mohon maaf saya tidak mengerti cara pakai github.

**Comment by afa28** [comment]
Belajar sama2 masz sy jg baru belajar. Masih sering salah PR

**Comment by ariandii** [comment]
> @afa28 mohon maaf saya tidak mengerti cara pakai github.

langkah awal, fork git opensid ini.
lalu download dan install git desktop.
clone gitnopensid ke komputer/laptop.
lakukan edit semua file yg diperlukan, dan commit ke github.
terakhir kirim Pull Request atas commit yg telah dibuat tadi.

Kirim 1 Pull Request (PR) hanya untuk 1 commit yang terdiri dari beberapa ubahan file. namun tetap dalam 1 kasus yang berhubungan.
