### ISSUE TITLE
Menu Di tema Hadakewa Mengikuti Inputan Pengguna

### ISSUE THREAD

**Issue by afa28** [OpenSID/OpenSID#2731]
### Bagaimana alurnya sampai muncul masalah?
Setiap buat menu, baik itu input huruf besar/kecil akan dipaksa menjadi huruf besar saat tampil.

### Seperti apa yang diharapkan?
Menu yg ditampilkan sesuai inputan user.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dicommit ke `master`
