### ISSUE TITLE
Gagal tampikan ribuan pada menu Statistik Pengunjung Website

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#2732]
### Bagaimana alurnya sampai muncul masalah?
Sesuai Pull #2667: Catat dan tampilkan berapa kali suatu artikel telah dibaca.
dalam hal tersebut menggunakan function hit.

Namun saat dicoba menerapkan fungtion hit tersebut ke dalam Angka yang tampil di Statistik Pengunjung Website menjadi tidak sesuai yang diharapkan.

![hit](https://user-images.githubusercontent.com/46939846/75443454-0577f180-5994-11ea-96e3-1f7ccdc7e6b7.png)

### Seperti apa yang diharapkan?
Function hit dapat digunakan ke seluruh angka yang ingin ditampilkan sesuai format ribuan.

### Apa yang terjadi?
Saat ini function hit hanya cocok diterapkan pada artikel dengan akhiran kata "Kali".

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
Kalau begitu maunya pak @ariandii , yg kata "kali" simpan di view saja. Biar helper bisa digunakan untuk yg lainnya.

**Comment by afa28** [comment]
Pak @ariandii , habis testing sy PR pak.

**Comment by balongbesuk** [comment]
saran untuk kolom kotak total

karena kolom itu menampung jumlah pengunjung yang akan terus bertambah tiap tahun pasti akan outframe kl sudah 100K lebih beda dengan kolom tanggal bulan tahun itu akan reset tiap tahunnya 

perlu dipikirkan untuk memberi singkatan seperti 1RB, 1JT, (aneh kl di bhs indonesiakan bagus 1K, 1M dst)

**Comment by afa28** [comment]
> saran untuk kolom kotak total
> 
> karena kolom itu menampung jumlah pengunjung yang akan terus bertambah tiap tahun pasti akan outframe kl sudah 100K lebih beda dengan kolom tanggal bulan tahun itu akan reset tiap tahunnya
> 
> perlu dipikirkan untuk memberi singkatan seperti 1RB, 1JT, (aneh kl di bhs indonesiakan bagus 1K, 1M dst)

nanti helpernya diperbaiki sesuai saran, jd silahkan beri masukan.

**Comment by eddieridwan** [comment]
Sudah dicommit ke `master` melalui PR #2972
