### ISSUE TITLE
Akses link active

### ISSUE THREAD

**Issue by afa28** [OpenSID/OpenSID#2733]
### Bagaimana alurnya sampai muncul masalah?
Buka salah satu artikel/menu yg ditampilkan di beranda/menu website.

Login ke admin dan non aktifkan artikel/menu tsbt kemudian logout.

Akses artikel/menu yg sebelumnya dibuka. Artikel masih tetap dpt di akses walaupun sdah di non aktifkan.

### Seperti apa yang diharapkan?
Artikel dll yg sdah di nonaktif tdk dpt di akses.

### Apa yang terjadi?
Informasi yg tdk diinginkn muncul bisa di akses.

### Informasi tambahan 
Walaupun pd daftar artikel/menu sdah tdk dimunculkan, namun dgn mengetahui link artikel tsb masih bisa di akses.

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dicommit ke `master`

**Comment by afa28** [comment]
Ini hanya untuk artikel pak, untuk link berupa data statistik, dpt, dll masih bisa di akases.

**Comment by eddieridwan** [comment]
@afa28 betul, karena seperti dijelaskan ditempat lain, masalah halaman statis berbeda dengan artikel.
Menyembunyikan artikel yg non-aktif jelas. Tapi menyembunyikan halaman statis yg tidak ada menunya tidak hitam/putih. Untuk halaman statis sebaiknya solusinya adalah menyediakan fitur untuk mengaktif/non-aktifkan halaman statis dan bukan tergantung apakah ada di menu atau tidak.

Tetapi, seperti dijelaskan juga, saat ini belum ada kebutuhan dari pengguna untuk fitur itu.
