### ISSUE TITLE
Kesulitan Backup/Restore Arsip Surat

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#2736]
### Bagaimana alurnya sampai muncul masalah?
Komputer kantor mengalami masalah hingga perlu di install ulang yang mengakibatkan OpenSID juga ikut diinstall lagi dan Restore yang diinginkan hanya database penduduk dan Arsip Layanan, Arsip Surat Masuk, dan Arsip Srat Keluar.

Saat ini untuk restore database penduduk bisa menggunakan database yang ada diexcel.

### Seperti apa yang diharapkan?
Adanya fitur backup dan restore Khusus untuk Arsip Layanan, Surat Masuk dan Surat Keluar.

### Apa yang terjadi?
Belum tersedia backup dan restore Arsip Layanan, Surat Masuk dan Surat Keluar tersebut.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Cara backup yg dianjurkan adalah seperti dijelaskan di https://github.com/OpenSID/OpenSID/wiki/Backup-dan-Restore. 

Ekspor data penduduk yg ada sekarang dalam format Excel BUKAN sebagai backup, tetapi perlu dilihat sebagai alat bantu untuk diimpor ke aplikasi atau keperluan lain.

Tidak dianjurkan untuk membuat ekspor Arsip Layanan, Surat Masuk dan Surat Keluar untuk tujuan backup.

SELALU lakukan backup lengkap seperti dijelaskan di https://github.com/OpenSID/OpenSID/wiki/Backup-dan-Restore.

**Comment by ariandii** [comment]
yang saya alami saat ini adalah, saat OpenSID local digunakan untuk Layanan Surat dan semuanya. (selain website),

Kemudian yang di online hanya untuk update website.

Kemudian, saya ingin sinkron kan data offline ke online.

Jika saya restore database ke online, semua kan menggantikan dari data offline. sehingga artikel di website online akan hilang.

**Comment by eddieridwan** [comment]
Kalau itu yg dimaksud, sudah ada issuenya: https://github.com/OpenSID/OpenSID/issues/2048
untuk sinkronisasi offline dan online.

**Comment by ariandii** [comment]
Duplicated
