### ISSUE TITLE
Membedakan Menu Bertingkat dan Tidak

### ISSUE THREAD

**Issue by afa28** [OpenSID/OpenSID#2740]
### Bagaimana alurnya sampai muncul masalah?
Saat Menambah Menu Biasa(Single Menu) , pilahan menambah submenu masih muncul.

### Seperti apa yang diharapkan?
Menu Biasa(Single Menu) Tidak dpt di isi submenu. Untuk menu bertingkat, menu(parrent) url dikosongkan(pilih eksternal lik dan kosongkan).

### Apa yang terjadi?
Ketika Menu Biasa(Single Menu)  ditambahkan submenu, akan menjadi menu bertingkat. Sehingga pada beberapa kasus tema yg belum support menu bertingkat, menu(parrent) dapat di klik(memiliki url).

### Informasi tambahan 
Tambahkan informasi cara pembuata menu bertingkat yang benar.

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
@afa28 , sebenarnya menu utama yg memiliki submenu bisa saja di-klik dan menampilkan artikel sendiri. Misalnya di menu Data Desa bisa saja artikel yg ditampilkan menjelaskan bagaimana statistik desa dibuat (dan mungkin menjelaskan ketergantungan pada warga yg harus rajin melapor perubahan data mereka) dan memberi petunjuk cara untuk interpretasi data statistik yg ditampilkan di submenu.

**Comment by afa28** [comment]
> @afa28 , sebenarnya menu utama yg memiliki submenu bisa saja di-klik dan menampilkan artikel sendiri. Misalnya di menu Data Desa bisa saja artikel yg ditampilkan menjelaskan bagaimana statistik desa dibuat (dan mungkin menjelaskan ketergantungan pada warga yg harus rajin melapor perubahan data mereka) dan memberi petunjuk cara untuk interpretasi data statistik yg ditampilkan di submenu.

Siap Pak @eddieridwan , jd ini tdk perlu dimasukkan.

**Comment by eddieridwan** [comment]
@afa28 tidak perlu dibedakan. Apakah PR https://github.com/OpenSID/OpenSID/pull/2790 hanya menerapkan ini atau ada yg lain juga?

**Comment by afa28** [comment]
> @afa28 tidak perlu dibedakan. Apakah PR #2790 hanya menerapkan ini atau ada yg lain juga?

Ad sedikit tambahan pak, jika menu utama tdk memiliki sub menu maka icon submenu tdk ditampilkan. Klw diperlukan, bisa sy pisah
