### ISSUE TITLE
Bug teks berjjalan

### ISSUE THREAD

**Issue by afa28** [OpenSID/OpenSID#2746]
### Bagaimana alurnya sampai muncul masalah?
Jika sdah ada 1 teks berjalan silahkan input lg. Inputan selanjutnya akan menambah data sebanyak 1 buah dalam 1 kali input.

### Seperti apa yang diharapkan?
Bug teks berjalan fix

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Kalau ada error, mohon diperbaiki saja. Jangan diubah. Ini diterapkan berdasarkan permintaan cukup lama di https://github.com/OpenSID/OpenSID/issues/2044, dan sudah lama diterapkan.

**Comment by afa28** [comment]
Baik pak @eddieridwan, nanti perbaiki bugsnya sja
