### ISSUE TITLE
Bugs Tombol Status Dasar dan ComboBox Pada Log Penduduk

### ISSUE THREAD

**Issue by afa28** [OpenSID/OpenSID#2748]
### Bagaimana alurnya sampai muncul masalah?
Tombol Kembalikan Status Langsung Muncul Walaupun Belum Ada Data Yg Terpilih, Sehingga Jika Tombol Tersebut Ditekan Maka Tidak Akan Terjadi Apa2.

Tombol Checkbox Juga Bermasalah, Tidak Bisa Memilih Semua Data Sekaligus.

### Seperti apa yang diharapkan?
Tombol Kembalikan Status Dasar Hanya Muncul Jika Ada Ada Yg Terpilih(Tombol Mirip Dengan Hapus Data Terpilih) dan Checkbox Berfungsi Normal

### Apa yang terjadi?
Tombol Tdk Befungsi dengan Baik

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dicommit ke `master` melalui PR #2749
