### ISSUE TITLE
Agenda

### ISSUE THREAD

**Issue by afri18** [OpenSID/OpenSID#2752]
### Bagaimana alurnya sampai muncul masalah?
Tanggal agenda masih belum berurutan dari yg terdekat/dahulu
![Screenshot_20200224-150031~2](https://user-images.githubusercontent.com/6611881/75626861-b1704580-5bfd-11ea-8e40-b48c83815a60.png)

### Seperti apa yang diharapkan?
Seharusnya yang urut itu tanggal agenda bukan tanggal posting
![Screenshot_20200301-203631](https://user-images.githubusercontent.com/6611881/75626886-da90d600-5bfd-11ea-947d-4d9ec44bb88c.png)

### Apa yang terjadi?
Lihat agenda jadi ruwet karna nggak urut dari yg terdekat 

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.03
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dicommit ke `master` melalui PR #2755

**Comment by afa28** [comment]
Pak yg point 2 mintanya yg waktu agenda terdekat.

**Comment by eddieridwan** [comment]
Coba lihat https://github.com/OpenSID/OpenSID/issues/2702.

Tapi silakan konfirmasi lagi dengan bung @afa28 (Syahfri). Mungkin yg lama menurun, yg akan datang naik -- tapi sebaiknya konsultasi.

**Comment by afa28** [comment]
Klw yg lama sy setuju DESC, tp yg hari ini dan yg akan datang pakai ASC. Lg sy tanya di FB pak

**Comment by afri18** [comment]
Bagusnya dari yg Deket tgl muda sampai tgl yg tus

**Comment by afa28** [comment]
![IMG20200302182244](https://user-images.githubusercontent.com/57283157/75667684-08842200-5cb3-11ea-950e-c66de0e98511.jpg)
Hari ini : ASC (paling atas agenda paling dekat)

![Uploading IMG20200302182257.jpg…]()
Yg akan datang : ASC (paling atas agenda paling dekat)

![Uploading IMG20200302182320.jpg…]()
Lama : DESC (yg paling atas yg baru selesai)
