### ISSUE TITLE
[Pengguna] Pisahkan ganti profil dan ganti password pengguna

### ISSUE THREAD

**Issue by ahmadngudi** [OpenSID/OpenSID#2758]
###Bagaimana alurnya sampai muncul masalah?
tidak bisa melihat password pengguna, 
![user](https://user-images.githubusercontent.com/57133748/75749672-ee028500-5d54-11ea-84d4-2dd9336c95a3.png)

### Seperti apa yang diharapkan?
 Ada tombol untuk Tampilkan Password, seperti yang ada di form login.

### Apa yang terjadi?
Jika salah satu user lupa password kita tidak bisa melihatnya, terpaksa kita ganti password

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by boedyirh** [comment]
by design, memang seharusnya reset password.

**Comment by afa28** [comment]
Seharunya password tidak ditampilkan. Mungkin perlu dipisahkan untuk halamn ganti password tdk digabung dengan ganti profil.

**Comment by andifahruddinakas** [comment]
Sudah diterpakan diversi 2305.0.0-premium
