### ISSUE TITLE
Balas Komentar dari Pengunjung Website

### ISSUE THREAD

**Issue by mr703** [OpenSID/OpenSID#2763]
### Bagaimana alurnya sampai muncul masalah?
Ketika ada diskusi tanya jawab atau komentar yang muncul disetiap artikel web, administrator dan admin2 lainnya tidak dapat membalas komentar secara langsung dan satu per satu atas pertanyaan yang di ajukan si pengunjung.

### Seperti apa yang diharapkan?
1. Setiap Komentar dapat dibalas dengan mudah persis di bawah komentar atau pertanyaan yang diajukan oleh admin web.
2. Adanya menu balas komentar

### Apa yang terjadi?
Komentar artikel tidak dapat dibalas langsung oleh admin karena tidak ada menu balas komentar

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
Pisahkan tabel u/ komentar dan mailbox.
