### ISSUE TITLE
[Template Surat] Mohon di Tambahkan Surat Permohonan Pembetulan Akta 

### ISSUE THREAD

**Issue by kayangan** [OpenSID/OpenSID#2764]
Pengalaman Saya Pribadi Pernah Membuat Data Kependudukan Saat itu Saya Memberikan Nama dan Tanggal Lahir Dengan Legkap Tapi Ketika Saya Menerima Kartu KK Dan KTP Ternyata disana ada Kesalahan Penulisan Nama , kemudian setelah itu saya ke dukcapil lagi bermaksud untuk merubah Nama itu sesuai dengan yang ada ternyata saya di suruh membawa/membuat surat FORMULIR LAPORAN PEMBETULAN AKTA **F-2.49** Berikut Surat Pernyataan dari Pelapor/Orang Tua dan Tanda Tangan Dua Orang Saksi : Contoh  =>
[surat_keterangan_pembetulan_akta___2020-03-04_154.pdf](https://github.com/OpenSID/OpenSID/files/4295849/surat_keterangan_pembetulan_akta___2020-03-04_154.pdf)

 Dan Saya Sementara Membuat Suratnya dengan Copy dari surat keterangan Kelahiran 
[surat_keterangan_pembetulan_akta_.zip](https://github.com/OpenSID/OpenSID/files/4295842/surat_keterangan_pembetulan_akta_.zip)

**Comment by roaddee** [comment]
apakah ini berlaku di seluruh indonesia ?
