### ISSUE TITLE
Surat Perubahan Kartu Keluarga tidak Menampilkan Alamat sebelum di Lampiran F-1.16 dan Tidak ada Nama Pamong Saat Export Suratnya

### ISSUE THREAD

**Issue by kayangan** [OpenSID/OpenSID#2765]
Tidak menampilkan Alamat Sebelumnya yang sudah kita imput pada saat perubahan data KK di lampiran F-1.16 
![1](https://user-images.githubusercontent.com/32614693/76039188-9cd9d780-5f86-11ea-97ec-68bfa55d9f6d.png)
Tidak Ada Nama Pamong
![2](https://user-images.githubusercontent.com/32614693/76039194-a2cfb880-5f86-11ea-8d91-c83c20b7b51e.png)

[surat_permohonan_perubahan_kartu_keluarga_5203161007820005_2020-03-05_156_lampiran.pdf](https://github.com/OpenSID/OpenSID/files/4295862/surat_permohonan_perubahan_kartu_keluarga_5203161007820005_2020-03-05_156_lampiran.pdf)

**Comment by afa28** [comment]
Untuk masalah tdk ada nama pamong saat ekxport, jgn lupa pilih yg bertanda tangan. (website demo lancar)

**Comment by kayangan** [comment]
Saya pake off line pak untuk prlayanan dindesa nama pamong sudah terpilih tapi tetep tidak tampil makanya saya laporkan sebagai issue

**Comment by Nurhidayat29** [comment]
@kayangan silakan update ke versi terbaru

**Comment by afa28** [comment]
Apakah ini masih bermasalah???
