### ISSUE TITLE
Supaya Bisa Ngelink Ke sumber Data Jika Klik Angka di Statistik Bulanan Kependudukan

### ISSUE THREAD

**Issue by kayangan** [OpenSID/OpenSID#2766]
![3](https://user-images.githubusercontent.com/32614693/76039615-f098f080-5f87-11ea-92b6-fd29fa759df5.png

**Comment by afa28** [comment]
Mungkin issuenya bisa di pisah pak @kayangan

**Comment by balongbesuk** [comment]
Duplicate #1285

**Comment by balongbesuk** [comment]
Duplicate #2272

**Comment by kayangan** [comment]
Jika duplikat saya close
