### ISSUE TITLE
[Navigasi] Menu Sidebar,collapse ketika kita pilih menu 

### ISSUE THREAD

**Issue by boedyirh** [OpenSID/OpenSID#2767]
Menu pada sidebar, saat kita pilih salah satu menu.
Scroll dgn sendirinya ke atas, sehingga mengganggu navigasi.
Kadang saat kita pilih salah satu submenu, Menu sidebar..collapse sendiri.
Mengurangi UX experience

### Bagaimana alurnya sampai muncul masalah?
Klik menu

### Seperti apa yang diharapkan?
Menu Tidak tiba tiba scroll ke atas sendiri. atau collapse sendiri.

### Apa yang terjadi?
Menu tiba tiba scroll ke atas sendiri. atau collapse sendiri.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.03
| Versi PHP        | 7.3
| System operasi   |

**Comment by mizwaruddin** [comment]
@afa28 saya tidak paham maksudnya. Hehehehe

**Comment by afa28** [comment]
> @afa28 saya tidak paham maksudnya. Hehehehe

Mungkin maksunya ini yg perpindahan antar menu/modul :
![12](https://user-images.githubusercontent.com/57283157/103435634-00cf3a00-4c44-11eb-88c5-3338790d3788.JPG)
![2222](https://user-images.githubusercontent.com/57283157/103435638-06c51b00-4c44-11eb-8f64-93b06365b3c1.JPG)

Perpindahan antar modul agak `kasar` krn menggunakan pengaturan masing2 modul. Mungin bisa view navigasi trakhir yg digunakan.

**Comment by andifahruddinakas** [comment]
Ganti cara saat ini menggunakan sessionStorage js untuk menyimpan kondisi sidebar terakhir.

**Comment by FirlianiF** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/531
