### ISSUE TITLE
Ubah supaya server mengirim notifikasi ada laporan dan komentar baru ke web, bukan melalui polling

### ISSUE THREAD

**Issue by boedyirh** [OpenSID/OpenSID#2768]
Saat berada di http://localhost/Opensid/index.php/keluarga
Saat inspect element (Network)
![image](https://user-images.githubusercontent.com/10396931/76042215-b67b1f00-5f86-11ea-9965-c75e319eb9ba.png)

selalu muncul aktifitas komentar dan lapor, (setiap sekitar 3 detik)

### Seperti apa yang diharapkan?
Karena tidak sedang melakukan apa apa,seharusnya itu juga tidak ada transaksi

### Apa yang terjadi?
Muncul aktifitas yang tidak diketahui

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.2
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
Tdk hanya di modul itu sj, hampir semua modul yg ada di halaman admin. Tujuannya mungkin untuk mendapat notifikasi komentar dan laporan jika ada yg masuk scr real time. (Pendapat sy)

**Comment by eddieridwan** [comment]
Untuk notifikasi komentar dan laporan, saat ini dilakukan polling ke server secara terus-menerus, setiap x detik. Mungkin bisa dicarikan cara lain, di mana server yg mengirim ke web. Tapi harus ada yg bersedia mencari cara teknis untuk bisa melakukan ini. 

Saya ubah issue ini untuk tugas itu.

**Comment by dobbleone** [comment]
<img width="960" alt="2020-03-08 (2)" src="https://user-images.githubusercontent.com/34769878/76150416-a598ed80-60ed-11ea-9f62-030d20f63633.png">


sebaiknya admin web, oprator dan lainya tidak dapat merubah komentar yang dikirimkan. tetapi hanya menolak dan menyetujui

**Comment by afa28** [comment]
> <img alt="2020-03-08 (2)" width="960" src="https://user-images.githubusercontent.com/34769878/76150416-a598ed80-60ed-11ea-9f62-030d20f63633.png">
> 
> sebaiknya admin web, oprator dan lainya tidak dapat merubah komentar yang dikirimkan. tetapi hanya menolak dan menyetujui

Silahkan buat issuenya pak @dobbleone

**Comment by boedyirh** [comment]
Sambil menunggu,

> 
> 
> Untuk notifikasi komentar dan laporan, saat ini dilakukan polling ke server secara terus-menerus, setiap x detik. Mungkin bisa dicarikan cara lain, di mana server yg mengirim ke web. Tapi harus ada yg bersedia mencari cara teknis untuk bisa melakukan ini.
> 
> Saya ubah issue ini untuk tugas itu.

Sambil menunggu feature tersebut siapi, apa mungkin ya  bisa diset setiap setiap 15 menit atau 30 menit. Agar bisa berkurang

**Comment by ericksuryadinata** [comment]
Ini bisa pakai websocket, seperti disini https://github.com/takielias/codeigniter-websocket-example , kalau luang akan saya ambil issues ini

**Comment by andifahruddinakas** [comment]
Notifikasi bisa dikirim ke telegram, bisa buat issuenya.
