### ISSUE TITLE
Minlength untuk autocomplete belum diset

### ISSUE THREAD

**Issue by boedyirh** [OpenSID/OpenSID#2769]
Jika kita input data perangkat, otomatis autocomplete ke setiap tombol yang kita tekan
![image](https://user-images.githubusercontent.com/10396931/76043158-3efabf00-5f89-11ea-85e9-7596807bc667.png)

### Bagaimana alurnya sampai muncul masalah?
Menambah traffic ke server

### Seperti apa yang diharapkan?
autocomplete hanya muncul setelah tombol keystroke ketiga, untuk meminimalkan traffic ke server

### Apa yang terjadi?
tombol ke 1,2 tetap melakukan query ke server. 

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.3
| Versi PHP        |  7.3
| System operasi   |

**Comment by afa28** [comment]
Masalah autocomplete sedang dilakukan penyesuaian dibeberapa form lainnya
