### ISSUE TITLE
Tidak menampilkan NIK Penduduk pada form Surat Perubahan KK 

### ISSUE THREAD

**Issue by asalreview** [OpenSID/OpenSID#2770]
### Bagaimana alurnya sampai muncul masalah?
Terdapat beberapa nama folder "surat" pada koding yang tidak ikut di ubah ke "template-surat"

### Seperti apa yang diharapkan?
tidak ada masalah baru setelah folder "surat" di ubah ke "template-surat"

### Apa yang terjadi?
![image](https://user-images.githubusercontent.com/60563749/76135320-7dab7a80-6058-11ea-96da-ee5e737c66f8.png)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.03-pasca
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
@asalreview Surat apa yg dimaksud? Di bawaan sistem atau ubahan desa di folder desa?

**Comment by asalreview** [comment]
sudah saya lakukan perubahan pak, cuma belum bisa saya PR kan, maaf lupa caranya.

**Comment by eddieridwan** [comment]
@asalreview coba periksa di https://demo.opensid.my.id. Kalau normal di situ, berarti proses update anda tidak sempurna. Ikuti prosedur di https://github.com/OpenSID/OpenSID/wiki/Panduan-Update-OpenSID. Perhatikan langkah (3) di mana pada proses update, perlu menghapus seluruh file/folder yg lama, kecuali folder desa.

**Comment by eddieridwan** [comment]
Perubahan apa yg anda maksud? Sepertinya tdk ada perubahan yg perlu dibuat terkait ini.... di demo berjalan normal...

**Comment by afa28** [comment]
Di webdemo normal 🙏

Mungkin proses update yg salah sehingga file "surat" masih ada, ikuti petunjuk wiki tentang update

**Comment by asalreview** [comment]
https://github.com/asalreview/OpenSID/commit/56dd4afbdcdb3e38d8486e45b8e6352c4226bc59

https://github.com/asalreview/OpenSID/commit/ee834d22b64bd6fead32ea6524e341928ff5a211

ini maksud saya pak
![image](https://user-images.githubusercontent.com/60563749/76135604-e72c8880-605a-11ea-8b74-eea568db7170.png)

**Comment by afa28** [comment]
![Screenshot_2020-03-07-11-04-22-61](https://user-images.githubusercontent.com/57283157/76135622-8d7c8c00-6063-11ea-9099-ee6041bd1027.png)

Yg ini yah??

**Comment by asalreview** [comment]
ia benar, lupa cara PR kan, ini lagi saya baca ulang tutorialnya pak.

**Comment by afa28** [comment]
Silahkan di PR jika ada yg kurang dr perubahan 🙏

**Comment by asalreview** [comment]
baik pak

**Comment by eddieridwan** [comment]
Ok, sudah diperbaiki. Ada yg ketinggalan diubah di `donjo-app/models/Surat_model.php`

**Comment by asalreview** [comment]
baik pak terimakasih.  mohon maaf saya belum mengeti cara PR berdasarkan isu.
