### ISSUE TITLE
[Buku Admin Desa] BUKU ANGGARAN PENDAPATAN DAN BELANJA DESA

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#2772]
### Bagaimana alurnya sampai muncul masalah?
Sesuai Buku Adminstrasi Desa sesuai dengan permendagri no 47 tahun 2016,

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by mizwaruddin** [comment]
[Permen No.47 TH 2016_Lampiran.pdf](https://github.com/OpenSID/OpenSID/files/6410822/Permen.No.47.TH.2016_Lampiran.pdf)

**Comment by mizwaruddin** [comment]
[buku inventaris desa.pdf](https://github.com/OpenSID/OpenSID/files/6411094/buku.inventaris.desa.pdf)

**Comment by mizwaruddin** [comment]
![buku inventaris desa](https://user-images.githubusercontent.com/39736008/116809090-9cc37080-ab66-11eb-9fca-9ff95a5828a8.png)

**Comment by andifahruddinakas** [comment]
Perlu di rancang ulang
