### ISSUE TITLE
[Buku Admin Desa] Buku Administrasi Umum

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#2773]
### Bagaimana alurnya sampai muncul masalah?
Buku Adminsitrasi Umum seperti :
1. Buku Peraturan di Desa
2. Buku Keputusan Kepala Desa
![image](https://user-images.githubusercontent.com/25834335/76142718-33071e00-60ab-11ea-8cf9-779dc5f6440d.png)

3. Buku Aparat Pemerintah Desa
![image](https://user-images.githubusercontent.com/25834335/76142735-4619ee00-60ab-11ea-97d9-4400da47d15d.png)

4. Buku Agenda
![image](https://user-images.githubusercontent.com/25834335/76142742-5336dd00-60ab-11ea-9407-f8f4832ce764.png)
![image](https://user-images.githubusercontent.com/25834335/76142744-58942780-60ab-11ea-8da2-fd36ae4b7328.png)

Sudah ada di Aplikasi OpenSID dan berada di menu yang terpisah-pisah

### Seperti apa yang diharapkan?
Buku Adminsitrasi Umum seperti :
1. Buku Peraturan di Desa
2. Buku Keputusan Kepala Desa
3. Buku Aparat Pemerintah Desa
4. Buku Agenda
berada di Satu MENU yaitu Menu Administrasi Umum
### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sdh dicommit ke branch `bumindes` di rilis `premium`.
