### ISSUE TITLE
[Buku Admin Desa] Buku Ekspedisi

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#2774]
### Bagaimana alurnya sampai muncul masalah?
Didalam Aplikasi Opensid belum ada BUKU Ekspedisi
![Screenshot 2020-03-07 19 58 52](https://user-images.githubusercontent.com/25834335/76143011-2b954400-60ae-11ea-976b-bee8f4a1143c.png)

### Seperti apa yang diharapkan?
di Aplikasi OpenSID ada MENU EKSPEDISI yang merupakan bagian dari Menu Adminstrasi Umum

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by MUHAMMADRANGSEL** [comment]
Buku Ekspedisi sama persis dengan buku agenda surat keluar

**Comment by MUHAMMADRANGSEL** [comment]
Dibuatkan seperti form Buku Agenda surat keluar

**Comment by MUHAMMADRANGSEL** [comment]
jenis surat yang dimasukkan kedalam Buku Ekspedisi adalah dikuar surat layanan,
Misalkan ada surat undangan, surat panggilan, surat pemberitahuan dll

**Comment by eddieridwan** [comment]
@MUHAMMADRANGSEL , apa beda `Buku Ekspedisi` dan `Buku Agenda surat keluar`? Apakah bedanya `Buku Ekspedisi` untuk surat ke warga dan `Buku Agenda` untuk surat ke pihak di luar desa?

**Comment by HerryWanda** [comment]
pak @eddieridwan , Buku ekspedisi beda dengan Buku Agenda surat keluar pak. Bukti ekpedisi merupakan barang bukti bahwa kita telah menyerahkan surat tersebut kepada yang bersangkutan.

Sebab banyak kejadian, kalo ke OPD atau dinas sering terjadi tuduhan bahwa surat tersebut tidak pernah diberikan oleh desa. buku ekpedisi ini sering digunakan untuk surat-surat penting pak..

Misal :
kita membuat surat ditujukan ke OPD atau dinas , kemudian surat tersebut diantarkan ke OPD atau dinas terkait, dan itu kita buktikan dengan buku ekpedisi, bahwa surat terebut telah kita serahkan dan diterima oleh bersangkutan.
Biasanya, buku ekspedisi di tanda tangani oleh penerima.

Jadi, untuk tanda tangan ini mungkin kita ganti dengan foto kemudian di upload ke buku ekpedisi saat penyerahan surat tersebut (kalo bisa)

**Comment by eddieridwan** [comment]
@HerryWanda @MUHAMMADRANGSEL Apakah ada tumpang tindih atau keterkaitan antara Buku Ekspedisi dengan Buku Agenda surat keluar? Misalnya, apakah ada surat yg tercatat di Buku Agenda surat keluar juga perlu ada di Buku Ekspedisi yg berisi bukti telah diterima?

**Comment by HerryWanda** [comment]
Ada pak, mang ada keterkaitan antara buku agenda surat keluar dengan BUku Ekspedisi.
Terutama pada :+1: 
1. Tabel Tanggal Surat
2. Tabel Nomor Surat
3. Tabel Keringkasan isi
4. Tabel TUjuan Surat

Yang membedakan buku ekpedisi dengan surat agenda keluar yaitu :+1: 
1. Tabel Tanggal Pengiriman 
2. Tabel Tanda Tangan Penerima/Ket bukti tanda terima surat (tanda tangan/cap/dll)

Berikut tabel (format) buku ekpedisi :+1: 
1. No Urut
2. Tanggal Pengiriman **(tidak ada di agenda surat keluar)**
3. Tanggal dan Nomor Surat (**ada** di agenda surat keluar)
4. Isi singkat surat yang dikirim/perihal (**ada** di agenda surat keluar)
5. Tujuan Surat (**ada** di agenda surat keluar)
6. Ket (TTD/cap/stempel/dll) **(tidak ada di agenda surat keluar)**

**Comment by eddieridwan** [comment]
@MUHAMMADRANGSEL , apakah penerapan issue ini sbb:
1. Semua surat keluar dibuat/ubah/hapus di modul Buku Agenda - Surat Keluar.
2. Di Buku Ekspedisi, semua surat keluar akan otomatis tampil
3. Di Buku Ekspedisi, aksi yg bisa dilakukan hanya untuk mengubah kolom2 yg khusus untuk ekspedisi, seperti tgl pengiriman, tanda terima, tgl terima. 

Mohon konfirmasinya.

**Comment by eddieridwan** [comment]
> 6\. Ket (TTD/cap/stempel/dll/tgl diterima) **(tidak ada di agenda surat keluar)**

@MUHAMMADRANGSEL bagaimana kalau ini diterapkan sbb:
1. ada kolom tgl terima (atau apakah ini selalu sama dengan tgl pengiriman?)
2. ada kolom upload gambar untuk bukti terima, seperti gambar cap/stempel,TTD/dsbnya).

**Comment by MUHAMMADRANGSEL** [comment]
> @MUHAMMADRANGSEL , apakah penerapan issue ini sbb:
> 
> 1. Semua surat keluar dibuat/ubah/hapus di modul Buku Agenda - Surat Keluar.
> 2. Di Buku Ekspedisi, semua surat keluar akan otomatis tampil
> 3. Di Buku Ekspedisi, aksi yg bisa dilakukan hanya untuk mengubah kolom2 yg khusus untuk ekspedisi, seperti tgl pengiriman, tanda terima, tgl terima.
> 
> Mohon konfirmasinya.

==> Point Nomor 1 Perlu dibuatkan
==> Point Nomor 2 tidak semua surat keluar yang tampil, tapi surat tertentu, seperti surat undangan, surat pemberitahuan ddl, selain surat pelayanan
==> Point Nomor 3 perlu dibuatkan

**Comment by MUHAMMADRANGSEL** [comment]
> > 6. Ket (TTD/cap/stempel/dll/tgl diterima) **(tidak ada di agenda surat keluar)**
> 
> @MUHAMMADRANGSEL bagaimana kalau ini diterapkan sbb:
> 
> 1. ada kolom tgl terima (atau apakah ini selalu sama dengan tgl pengiriman?)
> 2. ada kolom upload gambar untuk bukti terima, seperti gambar cap/stempel,TTD/dsbnya).

1. Kolom tanggal terima perlu ada, dan dibuatkan dinamis saja
2. perlu dibuatkan kolom uploads gambar

**Comment by eddieridwan** [comment]
@MUHAMMADRANGSEL , bagaimana caranya menyalin surat dari Buku Agenda Keluar ke Buku Ekspedisi? Cara mana yg cocok:
1. tombol aksi di daftar Surat Keluar untuk menyalin ke Buku Ekspedisi, atau
2. otomatis berdasarkan jenis surat; untuk cara ini harus ada daftar jenis surat baku.

**Comment by MUHAMMADRANGSEL** [comment]
Cara nomor 1 menurut saya yg paling pas

Pada tanggal Sen, 27 Jul 2020 18.44, Eddie Ridwan <notifications@github.com>
menulis:

**Comment by eddieridwan** [comment]
Sdh dicommit ke branch `bumindes`.
