### ISSUE TITLE
[Buku Admin Desa] Buku Lembaran Desa dan Buku Berita Desa. 

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#2775]
### Bagaimana alurnya sampai muncul masalah?
Buku Lembaran Desa dan Buku Berita Desa belum ada di Aplikasi OpenSID
![Screenshot 2020-03-07 20 01 29](https://user-images.githubusercontent.com/25834335/76143075-e9b8cd80-60ae-11ea-954c-f0c44ff8b873.png)

### Seperti apa yang diharapkan?
Buku Lembaran Desa dan Buku Berita Desa tersedia di aplikasi OpenSID yang merupakan bagian dari MENU ADMINISTRASI UMUM

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by MUHAMMADRANGSEL** [comment]
Buku Lembaran Desa dan Berita Desa Datanya diambil dari Buku Peraturran Desa, untuk formnya bisa disamakan  dengan Form Buku Peraturan Desa tinggal dihapus kolom nomor 5,6,9 yaitu : 
1. Tanggal kesepakatan peraturan desa
2. NOMOR DAN tanggal di laporkan
3. Nomor dan tanggal diundangkan dalam berita desa

**Comment by eddieridwan** [comment]
Sdh dicommit ke branch `rilis-dev`
