### ISSUE TITLE
[Buku Admin Desa] Buku Tanah di Desa

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#2776]
### Bagaimana alurnya sampai muncul masalah?
Sesuai Permendagri No 47 Tahun 2016

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by balongbesuk** [comment]
informasi tata cara pengisian https://format-lengkap-administrasi-desa.blogspot.com/2016/09/format-baru-administrasi-desa.html

**Comment by eddieridwan** [comment]
Bung @balongbesuk , tata cara pengisian itu sama seperti di issue https://github.com/OpenSID/OpenSID/issues/2272, dan tidak menjawab pertanyaan yg terus membuat kita semua ragu.

Terlihat di lampiran tersebut, tidak diberikan pengertian cara menghitung masing2 data di laporan tersebut. 

Sebagai contoh, apakah laporan jumlah yg lahir setiap bulan dihitung berdasarkan:

1. tgl di-entri ke OpenSID , atau
2. tgl lahir masing2 penduduk yg ditambahkan?
Kalau jawabannya (1), apakah bermasalah kalau pada waktu di-entri, penduduk baru tersebut tgl lahirnya dua atau tiga bulan sebelumnya.

**Comment by balongbesuk** [comment]
> 
> 
> Bung @balongbesuk , tata cara pengisian itu sama seperti di issue #2272, dan tidak menjawab pertanyaan yg terus membuat kita semua ragu.
> 
> Terlihat di lampiran tersebut, tidak diberikan pengertian cara menghitung masing2 data di laporan tersebut.
> 
> Sebagai contoh, apakah laporan jumlah yg lahir setiap bulan dihitung berdasarkan:
> 
>     1. tgl di-entri ke OpenSID , atau
> 
>     2. tgl lahir masing2 penduduk yg ditambahkan?
> 
> 
> Kalau jawabannya (1), apakah bermasalah kalau pada waktu di-entri, penduduk baru tersebut tgl lahirnya dua atau tiga bulan sebelumnya.

tanggal entri / lapor pak eddie, bukan tanggal lahir, 

secara garis besar semua laporan yang dihitung adalah tanggal saat yang bersangkutan lapor bukan saat kejadian,

**Comment by eddieridwan** [comment]
@balongbesuk , @MUHAMMADRANGSEL ok. Walau sebenarnya secara data tidak tepat. 
```
T: Berapa yg lahir bulan ini? 
J: 3 orang, tapi dari itu 2 tgl lahir sebenarnya beberapa bulan yg lalu..... 
Kalau kita buatkan grafiknya jadi bukan menunjukkan berapa yg lahir setiap bulan --- 
hanya menunjukkan kapan staf kantor desa sempat mencatatnya. 
Bayangkan kalau membuat perencanaan berdasarkan data seperti itu....
```

Tapi apa boleh buat. Begitulah status administrasi desa di negeri ini. Fokus pada kemudahan administrasi pelaporan, bukan pada kebenaran data.

**Comment by afa28** [comment]
Mungkin bisa di infokan ke warga, klw sdah lahiran, ada kematian langsung melaporkan ke pemerintah desa 🤭🤭🤭

**Comment by balongbesuk** [comment]
> kapan staf kantor desa sempat mencatatnya

ini bukan masalah kapan staf kantor sempat mencatatnya, 

kenyataan dilapangan memang seperti itu, warga belum banyak yang sadar tentang administrasi kependudukan/ terkadang karena kesibukan pekerjaan/ kebanyakan penduduk yang berdomisili diluar desa, sehingga tidak sempat melaporkannya tepat waktu, kalaupun warga tertip administrasi data tersebut tetap akan akurat, walaupun dilaporkan terlambat masih tetap masuk ke laporan kelahiran sebagai mana mestinya tempat dicatatkan, 

di tempat saya laporan penduduk bukan cuma rangkuman penjumlahannya saja, melainkan juga dilampirkan isi dari data yang dirangkum tersebut, yang mana rangkuman dan lampiran tersebut dilaporkan kpd kecamatan / kabupaten,
