### ISSUE TITLE
[Buku Admin Desa] Buku Induk Penduduk

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#2777]
### Bagaimana alurnya sampai muncul masalah?
Didalam OpenSID ada menu Penduduk yang dimana sudah mencakup semua elemen data didalamnya, sehingga untuk membuat Buku Induk Penduduk sesuai dengan permendagri 47 tahun 2016 sangat mudah seperti gambar dibawah ini : 
![image](https://user-images.githubusercontent.com/25834335/76143789-6353ba00-60b5-11ea-9e4f-6717b0b80862.png)
Cara Pengisian:
Kolom 1: | Diisi dengan nomor secara berurutan dari nomor 1 (satu), danseterusnya sesuai dengan jumlah kartu keluarga setiap kepalakeluarga disediakan satu halaman dan diiisi secara berurutberdasarkan kartu keluarga yang sudah diisi oleh kepala keluarga
-- | --
Kolom 2: | Diisi dengan nama lengkap dan atau kalau ada disebutkan namapanggilan.
Kolom 3: | Diisi dengan huruf L (untuk Laki-Laki), dan P (untuk Perempuan)
Kolom 4: | Diisi dengan Status Perkawinan yaitu K yang sudah Kawin, BK yangBelum Kawin, JD Janda, DD Duda
Kolom 5: | Diisi dengan tempat lahir yakni nama Desa, Kecamatan,Kabupaten/Kota, dimana yang bersangkutan dilahirkan
Kolom 6: | Diisi dengan tanggal, bulan dan tahun kelahiran yang bersangkutan
Kolom 7: | Diisi sesuai dengan Agama dan Kepercayaan
Kolom 8: | Diisi dengan Pendidikan terakhir baik formal maupun informal
Kolom 9: | Diisi dengan jenis pekerjaan
Kolom10: | Diisi dengan huruf L (bagi yang dapat membaca huruf latin), D(Daerah), A (Arab), AL (Arab dan Latin), AD (Arab dan Daerah), dan ALD(Arab, Latin, Daerah)
Kolom 11: | Diisi dengan Kewarganegaraan (WNI atau WNA)
Kolom 12: | Diisi dengan alamat lengkap
Kolom 13: | Diisi dengan KK (Kepala Keluarga), Ist (Istri), AK (Anak Kandung), AA(Anak Angkat), Pemb (Pembantu).
Kolom 14: | Diisi dengan Nomor Induk Kependudukan
Kolom 15: | Diisi dengan nomor Kartu Keluarga
Kolom 16: | Diisi dengan catatan-catatan lain yang dianggap perlu.

### Seperti apa yang diharapkan?
Buku Induk Penduduk tersedia di menu Administrasi Penduduk

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR https://github.com/OpenSID/premium/pull/72
