### ISSUE TITLE
[Buku Admin Desa] Buku Mutasi Penduduk Desa

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#2778]
### Bagaimana alurnya sampai muncul masalah?
Belum ada Buku Mutasi Penduduk Desa didalam aplikasi OpenSID, ada ada sekarang ini adalah LOG PENDUDUK yang ada kemiripan
![image](https://user-images.githubusercontent.com/25834335/76143934-70bd7400-60b6-11ea-88c6-4d9b88b42ead.png)
cara pengisian :
![Screenshot 2020-03-26 18 33 12](https://user-images.githubusercontent.com/25834335/77637390-8ecd1480-6f90-11ea-8122-a86f6d1ea6d6.png)

### Seperti apa yang diharapkan?
Buku Mutasi Penduduk Desa tersedia di aplikasi yang berada di Sub menu Administrasi Penduduk

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by muhtar-coder** [comment]
mungkin kah isi nya berdasarkan surat yang di buat oleh admin,,semisal ada warga pindah.jadi ketika kita buat kan surat pindah data tersebut juga terikan ke format buku tersebut berikut data yang di butuhkan oleh form tersebut ??

**Comment by MUHAMMADRANGSEL** [comment]
Alangkah bagusnya seperti itu, sehingga ketika surat pindah dibuatkan maka secara otomatis masyarakat tersebut sdh tidak terdaftar lagi menjadi penduduk di desa tersebut

**Comment by muhtar-coder** [comment]
boleh juga berarti termasuk kematian yang notabene nya auto link
status dasar

Pada tanggal Kam, 26 Mar 2020 pukul 17.37 MUHAMMADRANGSEL <
notifications@github.com> menulis:

**Comment by af-lazuardi** [comment]
Keterangan dari Pak Mizwar, Pak Eddie, dkk

1. Data Penambahan Penduduk sebab Lahir / Pindah masuk diambil dari form Tambah Penduduk (di mana ada penambahan fitur menambahkan sub button untuk penduduk lahir dan penduduk pindah datang). Sub button juga ditambahkan di Button Tambah Penduduk Menu Keluarga

![image](https://user-images.githubusercontent.com/13193883/104618297-18380980-56bf-11eb-95bf-368f5c297e47.png)

![image](https://user-images.githubusercontent.com/13193883/104619967-07889300-56c1-11eb-8a12-95df4d02c0fc.png)


![image](https://user-images.githubusercontent.com/13193883/104619570-9cd75780-56c0-11eb-825f-eb4d11bba376.png)

Tanggal Peristiwa untuk mencatat tanggal kelahiran yang berbeda dengan tangal saat didaftarkan

2. Data pengurangan penduduk sebab Meninggal dan Pindah Keluar diambil dari Menu 'Log_Penduduk' field 'Tanggal Rekam'

![image](https://user-images.githubusercontent.com/13193883/104618343-26862580-56bf-11eb-9ce4-9beae57be3e4.png)

Catatan
Tambahkan field yang dibutuhkan untuk melengkapi data di Laporan Bumindes Mutasi Penduduk, seperti:
a) Penambahan: Kolom 7 / Datang Dari, Kolom 8 / Diambil dari pertama kali data penambahan penduduk disimpan
b) Pengurangan: Kolom 9 / Pindah Ke, Kolom 11 / Tempat Meninggal


Baca juga petunjuk ini, message dari Pak Eddie

Pencatatan pindah masuk belum ada. 
Untuk laporan kependudukan bulanan, penjelasan ada di https://github.com/OpenSID/OpenSID/wiki/Laporan-Kependudukan-Bulanan

Jadi untuk Pengurangan kita tinggal ambil data di Tabel Log_Penduduk, dimana ada aktifitas khusus oleh user untuk melakukan hal tersebut. Sehingga saat event tersebut terjadi, perlu ditambahi logic untuk mencatat Penambahan Penduduk yang tersimpan di database t_web_penduduk

**Comment by eddieridwan** [comment]
@af-lazuardi Harap komentar di atas dibatasi pada ketentuan fungsional saja, bukan penerapan. Catatan teknis penerapan didokumentasikan di komentar ini:

1. Ubah nama kolom `tanggal` di tabel `log_penduduk` menjadi `tanggal_rekam`, digunakan untuk tanggal dimasukkan ke database.
2. Tambah kolom `tanggal_lapor` di tabel `log_penduduk`, digunakan untuk menunjukkan bulan/tahun peristiwa ini dilaporkan di laporan bulanan atau mutasi penduduk. Nilai default disamakan dengan `tanggal_rekam`, tapi bisa diubah oleh pengguna jika perlu.
3. Catat peristiwa penduduk lahir di `log_penduduk`, dengan kode baru.
4. Catat peristiwa penduduk masuk di `log_penduduk`, dengan kode baru.
5. Ubah Laporan Bulanan supaya data mutasi/peristiwa sepenuhnya menggunakan data di `log_penduduk`. Tentunya rincian data dari `tweb_penduduk`.
6. Buku Mutasi Penduduk supaya data mutasi/peristiwa sepenuhnya menggunakan data di `log_penduduk`. Tentunya rincian data dari `tweb_penduduk`.
7. Tambah kolom `created_by`, `updated_at` dan `updated_by` di tabel `log_penduduk` untuk mencatat siapa yg merekam pertama kali, dan siapa/kapan diupdate.

Jadi di `log_penduduk` akan ada tiga tanggal:
1. `tanggal_peristiwa`, yaitu tanggal kejadian sebenarnya. Seperti tanggal kematian, tanggal lahir dsbnya
2. `tanggal_rekam`, yaitu tanggal petugas memasukkan data ke database
3. `tanggal_lapor`, yaitu tanggal yg digunakan untuk menentukan peristiwa ybs dilaporkan pada bulan/tahun apa.

**Comment by af-lazuardi** [comment]
Siap Pak @eddieridwan , terima kasih atas petunjuk teknisnya. Sangat membantu sekali

**Comment by af-lazuardi** [comment]
Pak @eddieridwan , maksud status penduduk. Tetap, Tidak Tetap, Pendatang itu maksudnya apa?

Apakah pendatang itu warga pindah masuk. Sedang tetap itu warga awal/asli. Kalau tidak tetap baru warga kontrak.

Ini kaitannya mau define kode peristiwa untuk id_log_detail.

Yang saat ini ada untuk log detail seperti ini,
![unknown-4.png](https://user-images.githubusercontent.com/13193883/104796061-e1a8de80-57e5-11eb-9c45-6e336ea6fc93.png)

Kami mau buat kode peristiwa sesuai dengan isi tabel status_dasar

a. Hidup 1
b. Mati 2
c. dst nya

**Comment by eddieridwan** [comment]
@af-lazuardi lihat tambahan di https://github.com/OpenSID/OpenSID/issues/2778#issuecomment-760508607 terkait kode peristiwa.

**Comment by af-lazuardi** [comment]
baik, terima kasih penjelasannya

**Comment by eddieridwan** [comment]
Sdh dicommit ke `rilis-dev` melalui PR https://github.com/OpenSID/premium/pull/80
