### ISSUE TITLE
Statistik berdasarkan dusun pada menu peta jika nama dusun ada spasi maka statistik tidak muncul

### ISSUE THREAD

**Issue by asalreview** [OpenSID/OpenSID#2779]
### Bagaimana alurnya sampai muncul masalah?
Statistik berdasarkan dusun pada menu peta jika nama dusun ada spasi maka statistik tidak muncul

### Seperti apa yang diharapkan?
Statistik dapat muncul walaupun nama dusun ada spasi.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.03
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
Apa maksunya begini??? Kalau ini tdk ada masalah

![Capture](https://user-images.githubusercontent.com/57283157/76156002-88344580-6126-11ea-905f-7f6b91a7a9ca.PNG)

**Comment by asalreview** [comment]
![image](https://user-images.githubusercontent.com/60563749/76157717-77dc9480-613f-11ea-8a59-bc4c28fa7f1f.png)
mohon di praktekkan dulu pak setiap isu, klo tidak yg mnympaikn isu salah mulu.

**Comment by asalreview** [comment]
https://beta.opensid.my.id/gis#collapseStat

**Comment by afa28** [comment]
@fusionid

**Comment by afa28** [comment]
> ![image](https://user-images.githubusercontent.com/60563749/76157717-77dc9480-613f-11ea-8a59-bc4c28fa7f1f.png)
> mohon di praktekkan dulu pak setiap isu, klo tidak yg mnympaikn isu salah mulu.

Maka dr itu, mohon issue yg dilontarkan diperjelas klw perlu mungkin bisa dgn oenambahan gambar. Biar contributor yg mau mengerjakan tdk menerka2. Krn kadang kami salah tangkap klw informasi kurang jelas 🙏

**Comment by WAHYUDIK** [comment]
untuk eror ini memang benar terjadi diakibatkan nama dusun terdapat spasi. jika nama dusun tidak ada spasi tidak terjadi eror

**Comment by afa28** [comment]
Nah ini issuenya 🤣🤣🤣

**Comment by WAHYUDIK** [comment]
> Nah ini issuenya 🤣🤣🤣

hahahaha

**Comment by WAHYUDIK** [comment]
ketika memilih dusun, data statistik yang tampil masih statistik desa.

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3391
