### ISSUE TITLE
Pendapatan Lain-Lain pada Grafik APBDesa belum nampak.

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#2782]
### Bagaimana alurnya sampai muncul masalah?
Tidak terdapat angka "Pendapatan Lain-Lain" pada Grafik Realisasi yang terdapat pada footer halaman website.

### Seperti apa yang diharapkan?
Angka seharusnya menunjung seperti yang tertera di tabel yang sudah sesuai dengan Siskeudes, adanya angka di Pendapatan Lain-Lain sebesar Rp. 100.000.
![realisasi](https://user-images.githubusercontent.com/46939846/76164314-754e5f00-6180-11ea-9275-d48b34a001f5.png)

### Apa yang terjadi?
Belum terjumlah ataupun belum ter data pada Grafik Pendapatan sebagaimana mestinya.
![grafik](https://user-images.githubusercontent.com/46939846/76164312-6ff11480-6180-11ea-9e25-0b8b3fb5a97b.png)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by fusionid** [comment]
Untuk tema custom natra, update script di partials/apbdesa-tema.php :

dari :

`<?php if($subdata['judul'] != NULL and $key != 'laporan' and $subdata['realisasi'] != 0 and $subdata['anggaran'] != 0): ?>` 

menjadi : 

`<?php if($subdata['judul'] != NULL and $key != 'laporan' and $subdata['realisasi'] != 0 or $subdata['anggaran'] != 0): ?>`

![apbdes_natra](https://user-images.githubusercontent.com/10391199/76213159-aab88280-623c-11ea-9a66-6f20b9a5a4ea.PNG)

**Comment by ariandii** [comment]
terima kasih.
