### ISSUE TITLE
[Statistik] Ubah url statistik pd web menggunakan slug

### ISSUE THREAD

**Issue by asalreview** [OpenSID/OpenSID#2784]
### Seperti apa yang diharapkan?
url id pada menu artikel dan statistik di ubah ke slug atau mengikuti nama judul statistik.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.03
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
Kayaknya ini sama

Mengganti parameter id menjadi slug pd url terutama data statistik #2631

**Comment by asalreview** [comment]
udah pernah saya ngoba koding bapak PRkan, cuma hasilnya error. bisa di share kembali dengan lengkap pak?

**Comment by afa28** [comment]
> udah pernah saya ngoba koding bapak PRkan, cuma hasilnya error. bisa di share kembali dengan lengkap pak?

Pernah sy kerja tp tdk di PR, sy lupa simpannya dimana

**Comment by afa28** [comment]
Untuk menu artikel sudah ada di `master`

**Comment by afa28** [comment]
untuk url artikel berupa slug sdah ada di `master`.

**Comment by mizwaruddin** [comment]
@afa28 sdh ada di master

**Comment by afa28** [comment]
> @afa28 sdh ada di master

Untuk statistik blum pak. Judulnya sudah sy sesuaikan ulang.
