### ISSUE TITLE
Artikel yang sudah di nonaktifkan masih terindex di paging artikel 

### ISSUE THREAD

**Issue by asalreview** [OpenSID/OpenSID#2785]
### Bagaimana alurnya sampai muncul masalah?
Artikel yang sudah di nonaktifkan masih terindex di paging artikel sehingga paging nilai tertinggi terakhir menampilkan artikel tidak di temukan.

### Seperti apa yang diharapkan?
yang sudah di nonaktifkan tidak terindex

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.03
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dicommit ke `master` melalui PR #2786
