### ISSUE TITLE
Filter Tabel Demografi Berdasar Pekerjaan

### ISSUE THREAD

**Issue by asalreview** [OpenSID/OpenSID#2787]
### Bagaimana alurnya sampai muncul masalah?
Agar data lebih rapi dan mudah untuk dibacakan sebaiknya tabel Demografi Berdasar Pekerjaan di filter jika nilai 0 maka tidak perlu di tampilkan.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.03
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
Sudah dicommit ke master melalui PR #2899
