### ISSUE TITLE
Tombol Aktif dan Tidak Aktif Penduduk

### ISSUE THREAD

**Issue by afa28** [OpenSID/OpenSID#2788]
### Bagaimana alurnya sampai muncul masalah?
Tombol ini sebenarnya tdk diperlukan, karena sudah ada yg mewakili yakni tombol status(hidup, mati, dll)

Tombol Aktif dan Tidak Aktif (enable) Biasanya digunakan pada artikel, menu, dll yg dimana fungsinya untuk mengaktifkan/menonaktifkan data yg ditampilkan ke publik.

### Seperti apa yang diharapkan?
Hapus Tombol Aktif dan Tidak Aktif beserta filednya pada tabel Penduduk krn data detail penduduk tdk ditampilkan ke publik.

### Apa yang terjadi?
Tombol yg jarang digunakan terhapus.

### Informasi tambahan 
![asfkaslkfsa](https://user-images.githubusercontent.com/57283157/76294609-c166e400-62e5-11ea-887a-4743cd74cfaf.PNG)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
@afa28 di mana ada tombol aktif/tidak aktif penduduk?

**Comment by afa28** [comment]
> @afa28 di mana ada tombol aktif/tidak aktif penduduk?

![asfkaslkfsa](https://user-images.githubusercontent.com/57283157/76295321-fd4e7900-62e6-11ea-8bfb-0be4849c5b7a.PNG)

**Comment by eddieridwan** [comment]
Hmm... seharusnya untuk filter Status Penduduk: Tetap, Tidak Tetap, Pendatang. 
Sepertinya lolos review pada waktu perubahan modul Admin secara menyeluruh dulu.

**Comment by afri18** [comment]
Sebaiknya pertahankan yg ada, banyak gunanya, saat cari nama di yg hidup nggak ada nanti terfilter sesungguhnya penduduk itu statusnya apa

**Comment by afa28** [comment]
> Sebaiknya pertahankan yg ada, banyak gunanya, saat cari nama di yg hidup nggak ada nanti terfilter sesungguhnya penduduk itu statusnya apa

Kalau filter satus_dasar ada combobox disebelahnya pak.

**Comment by balongbesuk** [comment]
cara nonaktifkan penduduk gimana pak? jadi punya ide uat nonaktifkan data penduduk yang belum bayar pajak :smile:

**Comment by afa28** [comment]
> cara nonaktifkan penduduk gimana pak? jadi punya ide buat nonaktifkan data penduduk yang belum bayar pajak, jd tidak bisa minta surat dll

Ini lain lg pak 😅

**Comment by afa28** [comment]
> Sebaiknya pertahankan yg ada, banyak gunanya, saat cari nama di yg hidup nggak ada nanti terfilter sesungguhnya penduduk itu statusnya apa

Mungkin cuman oenamaannya yg kurang tepat dan pengambilan datanya, harusnya penduduk tetap dan tdk tetap. 🤔

**Comment by eddieridwan** [comment]
Sudah dicommit ke `master` melalui PR #2971
