### ISSUE TITLE
Batas Paging Halaman

### ISSUE THREAD

**Issue by ZER07URN** [OpenSID/OpenSID#2792]
### Bagaimana alurnya sampai muncul masalah?
Hilangkan paging jika jumlah data artikel/artikel yg ditampilkan <= web_artikel_per_page pd pengaturan aplikasi

### Seperti apa yang diharapkan?
Paging hilang untuk artikel/kategori yg sedikit

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dicommit ke `master` melalui PR #2829
