### ISSUE TITLE
Tambahkan Tombol Bersihkan Modul Kependudukan Lainnya

### ISSUE THREAD

**Issue by ZER07URN** [OpenSID/OpenSID#2793]
### Bagaimana alurnya sampai muncul masalah?
Saat menfilter data menggunakan combobox, jika mau menormalkan kembali harus menekan kembali menu navigasi.

### Seperti apa yang diharapkan?
tambahkan tombol bersihkan

### Apa yang terjadi?
Lebih simple dan seragam dgn modul kependudukan yg lain

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dicommit ke `master` melalui PR #2855
