### ISSUE TITLE
Tombol Hapus Kategori Terhidden

### ISSUE THREAD

**Issue by ZER07URN** [OpenSID/OpenSID#2794]
### Bagaimana alurnya sampai muncul masalah?
Masuk ke modul artikel, pilih salah satu kategori dan coba hapus. Tombol hapus tdk bisa digunakan jika tdk memilih salah satu artikel. Disini yg mau dihapus kategorinya bukan artikelnya, jd tdk perlu pilih artikel lg untuk hapus kategori.

### Seperti apa yang diharapkan?
Tombol Hapus Kategori tdk perlu dihidden dan tdk perlu select artikel untuk menghapus kategori.

### Apa yang terjadi?
Tombol bekerja sesuai fungsinya.

### Informasi tambahan 
![iofuowoiorwe](https://user-images.githubusercontent.com/7290110/76372026-be640600-636e-11ea-92c1-aa4b1f7f4416.PNG)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dicommit ke `master` melalui PR #2796
