### ISSUE TITLE
daftar inventaris

### ISSUE THREAD

**Issue by a241ni** [OpenSID/OpenSID#2795]
### Bagaimana alurnya sampai muncul masalah?
contoh saat memilih inventaris komputer tidak ada kolom jumlah barang

### Seperti apa yang diharapkan?
ada kolom untuk mengisi jumlah barang inventaris

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
Apa perlu sy tambahkan field jumlah pd tabel inventaris peralatan pak @eddieridwan ?

**Comment by afa28** [comment]
Kayaknya di modul ini, 1 barang 1 data. Tidak disediakan pengelompokan untuk data lebih dari 1. Ini akan repot jika datanya banyak dan tipe/mereknya sama.

**Comment by mizwaruddin** [comment]
@afa28 karena diminta utk mengisikan nomor seri, tentunya hal ini tidak bisa dilakukan.

**Comment by ariandii** [comment]
Saya lakukan inventaris untuk jenis peralatan yang sama, namun 2 nomor urut yg berbeda.

<img width="669" alt="2021-01-08_22h35_34" src="https://user-images.githubusercontent.com/46939846/104033248-df50ee00-5201-11eb-9541-fdffb9a1ef77.png">

**Comment by Gunturwijay** [comment]
Mohon untuk di tambahkan uploud dokumennya

**Comment by agungsugiarto** [comment]
Bapak @a241ni issue ini saya close, jika masih mengalami kendala silahkan buka kembali issue ini.
