### ISSUE TITLE
Surat yang di cetak/export seharusnya dalam format PDF

### ISSUE THREAD

**Issue by asalreview** [OpenSID/OpenSID#2798]
### Bagaimana alurnya sampai muncul masalah?
Surat yang di cetak seharusnya dalam format pdf, agar tidak mudah untuk di ubah kembali, mengingat surat yang sudah di export berarti surat sudah final.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.03
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah lama dulu diterapkan: lihat panduan https://github.com/OpenSID/OpenSID/wiki/Cetak-Surat
Tapi sudah lama tidak dites lagi.

**Comment by afri18** [comment]
Sebaiknya jangan karena kadang data belum terupdate
Pertahankan seperti sekarang

**Comment by asalreview** [comment]
> Sebaiknya jangan karena kadang data belum terupdate
> Pertahankan seperti sekarang

**Comment by asalreview** [comment]
Bangun tidur malah ketekan close isu

@afri18 @eddieridwan tapi jika dalam format doc pak rasanya kurang efektif mengingat jika ada yang keliru dokumenya bisa di ubah langsung di file tersebut, tentu akan berbeda yang tersimpan di aplikasi, dan jika ada aparatur yang mau mencetak surat yang sama format dengan di aplikasi pun tidak perlu menggunakan sistem, al hasil rekam data tidak sama.

**Comment by afri18** [comment]
Disaya walau d ubah yg tersimpan perubahan terakhir

**Comment by balongbesuk** [comment]
bs dicoba saran pak eddie (opsional) kl tidak berhasil bs dilaporkan ke github,

sy sendiripun lebih suka bs diedit karena tdk semua surat didesa baku dan kadang warga minta surat yang ikut format instansi lain

**Comment by afa28** [comment]
Sudah ditambahkan di rilis premium.
