### ISSUE TITLE
Perbaiki Routing Url Website

### ISSUE THREAD

**Issue by ZER07URN** [OpenSID/OpenSID#2799]
### Bagaimana alurnya sampai muncul masalah?
Url website menampilkan nama controller first pd url, sehingga terlihat kurang bagus. Contoh : http://demo.opensid.my.id/first

### Seperti apa yang diharapkan?
Nama controller first seharusnya tdk ditampilkan, menjadi : http://demo.opensid.my.id/ seperti website pada umumnya.
http://demo.opensid.my.id/first/artikel/2016/8/26/sejarah-desa
http://demo.opensid.my.id/first/kategori/1
menjadi
http://demo.opensid.my.id/artikel/2016/8/26/sejarah-desa
http://demo.opensid.my.id/kategori/1

### Apa yang terjadi?
Url lebih bagus

### Informasi tambahan 
Jika ada perubahan pd route, usahakan url yg sebelumnya sudah dishare masih bisa diakses.
| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3071
