### ISSUE TITLE
Surat yang di cetak/export seharusnya dalam format PDF (Isu Sudah pernah buat tidak sengaja ketekan close)

### ISSUE THREAD

**Issue by asalreview** [OpenSID/OpenSID#2801]
### Bagaimana alurnya sampai muncul masalah?
Surat yang di cetak seharusnya dalam format pdf, agar tidak mudah untuk di ubah kembali, mengingat surat yang sudah di export berarti surat sudah final. tapi jika dalam format doc pak rasanya kurang efektif mengingat jika ada yang keliru dokumenya bisa di ubah langsung di file tersebut, tentu akan berbeda yang tersimpan di aplikasi, dan jika ada aparatur yang mau mencetak surat yang sama format dengan di aplikasi pun tidak perlu menggunakan sistem, al hasil rekam data tidak sama. oleh karena itu mohon pendapat bapak-bapak tentang format surat yang di hasil sebaiknya doc apa pdf? terima kasih.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.03
| Versi PHP        | 
| System operasi   |

**Comment by balongbesuk** [comment]
Ada tombol reopen pak, untuk issue yang terclose

**Comment by balongbesuk** [comment]
Kl untuk diskusi saran sy d grup facebook saja, banyak yg menanggapi.,

**Comment by asalreview** [comment]
baik ini akan saya close, maaf masih awam github, oya pak jika bisa mohon dibicarakan di grub, saya hanya di github.
