### ISSUE TITLE
BelumAda Link Pada Laporan Bulanan Statistik Perkembangan Penduduk 

### ISSUE THREAD

**Issue by asalreview** [OpenSID/OpenSID#2802]
### Bagaimana alurnya sampai muncul masalah?
Belum Ada Link Pada Laporan Bulanan Statistik Perkembangan Penduduk, sehingga misalnya penduduk/keluarga bulan ini yang baru terdaftar siapa saja tidak bisa di lihat.
![image](https://user-images.githubusercontent.com/60563749/76464375-d3e13a80-6417-11ea-8d99-e53592a7f671.png)

### Seperti apa yang diharapkan?
Memiliki link agar informasi lebih akurat.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.03
| Versi PHP        | 
| System operasi   |

**Comment by balongbesuk** [comment]
Duplicate #1285

**Comment by afa28** [comment]
Duplicate https://github.com/OpenSID/OpenSID/issues/2272
