### ISSUE TITLE
[Versi 20.03 Pasca ] : Tidak Bisa Tambah Format Surat pada pengaturan Surat

### ISSUE THREAD

**Issue by HerryWanda** [OpenSID/OpenSID#2805]
### Bagaimana alurnya sampai muncul masalah?
Setelah melakukan tambah format surat baru pada pengaturan surat di layanan surat, maka kita melakukan cetak surat tapi halaman cetak surat tersebut kosong, tidak ada menampilkan isian formulir pengisian data.

Telah dicoba di demo.opensid.my.id tetap seperti itu.

### Seperti apa yang diharapkan?
Diharapka bisa seperti biasa, bisa menambahkan Format Surat baru.

### Apa yang terjadi?
Format Surat baru tidak bisa

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.03 Pasca
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #2806
