### ISSUE TITLE
[Identitas Desa] Data Geospasial

### ISSUE THREAD

**Issue by elkautzar** [OpenSID/OpenSID#2807]
### Bagaimana alurnya sampai muncul masalah?
Belum ada data geospasial, saat yg disediakan hanya Data Demografi Berdasar Populasi Per Wilayah, namun data berupa : peta desa(luas, keliling, panjang jalan), lahan(kebun, sawah, hutan), jalan(aspal,beton, lainnya), bangunan(tk, sd, smp, sma, universitas, pemukiman) belum tersedia.

### Seperti apa yang diharapkan?
sediakan data geospasial

### Apa yang terjadi?
data geospasial dapat ditampilkan ke publik

### Informasi tambahan 
Data sudah ada yg tersedia pada modul pemetaan, tinggal bagaimana caranya agar bisa ditampilkan ke publik.

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
@ZER07URN Sudah dikerjakan di https://github.com/OpenSID/OpenSID/pull/2681. Tinggal menunggu perbaikan dari hasil review. Sebagai yg telah pernah mengirim kontribusi PR, bantuan anda lagi terus ditunggu.

**Comment by afa28** [comment]
Mungkin maksudnya halaman statis web u/ menampilkan daftar infrastruktur yg ad di desa, misal jml sekolah, rs, dll.
