### ISSUE TITLE
[Bug] Error Tampilkan Tabel dan Grafik Keuangan pada Artikel

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#2808]
### Bagaimana alurnya sampai muncul masalah?
Tidak dapat menampilkan informasi keuangan sesuai yang diminta pada sisipkan artikel.
![IMG_20200312_181054](https://user-images.githubusercontent.com/46939846/76515859-ee093000-648c-11ea-8c83-612b18ca4073.jpg)

### Seperti apa yang diharapkan?
Dapat menampilkan dengan normal kembali seperti semula.
![IMG_20200312_181104](https://user-images.githubusercontent.com/46939846/76515838-e5b0f500-648c-11ea-81b3-b846c91cbf12.jpg)

### Apa yang terjadi?
Saat ini hanya menampilkan tulisan saja.
![IMG_20200312_175528](https://user-images.githubusercontent.com/46939846/76514831-142dd080-648b-11ea-89cc-d44918d4899e.jpg)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by ianskids** [comment]
akan saya perbaiki

**Comment by eddieridwan** [comment]
Sudah dicommit ke `master` melalui PR #2817
