### ISSUE TITLE
[Bug] Seharusnya slug Artikel dan Kategori unik, walaupun judulnya sama

### ISSUE THREAD

**Issue by ZER07URN** [OpenSID/OpenSID#2809]
### Bagaimana alurnya sampai muncul masalah?
Buat 2 artikel/kategori dan beri judul yg sama dan isikan dengan isi yg berbeda, buka kedua artikel dihalaman web,maka yg ditampilkan adalah artikel dgn slug pertama dibuat (tergantung ASC/DESC)

### Seperti apa yang diharapkan?
slug tdk boleh sama

### Apa yang terjadi?
slug berbeda dan uniq

### Informasi tambahan 
![Untitled](https://user-images.githubusercontent.com/7290110/76579793-bf8a5580-648a-11ea-8edf-6c82ceba962a.png)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by balongbesuk** [comment]
Sertakan gambar

**Comment by ZER07URN** [comment]
> Sertakan gambar

![Untitled](https://user-images.githubusercontent.com/7290110/76579793-bf8a5580-648a-11ea-8edf-6c82ceba962a.png)

**Comment by eddieridwan** [comment]
Telah dicommit ke `master` melalui PR #2810 dengan solusi sebagai berikut:
1. Slug artikel dibuat unik bila judul sama, menggunakan cara yg terapkan Wordpress (ditambah suffix bilangan)
2. Nama kategori artikel tidak boleh sama.
