### ISSUE TITLE
Rangkap Jabatan Pada Wilayah Administratif

### ISSUE THREAD

**Issue by ZER07URN** [OpenSID/OpenSID#2811]
### Bagaimana alurnya sampai muncul masalah?
Masuk Modul Wilayah Administratif > Tambahkan/Edit Pengelolaan Data Dusun, Pilih NIK / Nama Kepala Dusun. Lakukan Hal Yang sama pada tempat lain baik itu di dusun, rt, rw maka Masih bisa memilih org yg sama yg sdah menduduki kepala dusun sebelumnya, sehingga terjadi rangkap jabatan.

### Seperti apa yang diharapkan?
Satu org satu jabatan di wilayah Administratif

### Apa yang terjadi?
Tdk ada rangkap jabatan

### Informasi tambahan 
![Untitled](https://user-images.githubusercontent.com/7290110/76600815-e9606e00-64c4-11ea-9f95-91986019b6ca.png)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by ariandii** [comment]
ya dipilih saja penduduk lain.

**Comment by afa28** [comment]
Yg simple jgn bikin rumit 🤭

**Comment by kurniyawan0490** [comment]
setau saya satu dusun ..1 Kepala Dusun bang...

**Comment by eddieridwan** [comment]
Sudah dicommit ke `master` melalui PR #2827
