### ISSUE TITLE
[Bug] Jika Inputan Nama Dusun, RW, RT Sama dengan yang sudah ada Muncul Error 500

### ISSUE THREAD

**Issue by asalreview** [OpenSID/OpenSID#2812]
### Bagaimana alurnya sampai muncul masalah?
Jika Inputan Nama Dusun, RW, RT Sama dengan yang sudah ada,maka Muncul Error 500, seharusnya berupa pesan error yang tampilkan, bukan error database.
![image](https://user-images.githubusercontent.com/60563749/76637045-a661d180-657c-11ea-957b-84a164bf8591.png)
https://beta.opensid.my.id/sid_core/insert

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.03
| Versi PHP        | 
| System operasi   |

**Comment by ianskids** [comment]
akan saya kerjakan

**Comment by eddieridwan** [comment]
Sudah dicommit ke `master` melalui PR #2814
