### ISSUE TITLE
Tombol Delete All Pada Wilayah Administrasi

### ISSUE THREAD

**Issue by ZER07URN** [OpenSID/OpenSID#2815]
### Bagaimana alurnya sampai muncul masalah?
Cek Modul Wilayah Administrasi, disana tersedia check box tp tdk dipergunakan krn tdk adanya tombol eksekusi seperti delete all. 

### Seperti apa yang diharapkan?
tambahkan tombol delete all agar checkbox dpt dipergunakan

### Apa yang terjadi?
checkbox  berguna sebagaimana mestinya

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sebenarnya tidak ada kebutuhan untuk menghapus wilayah secara massal. Untuk menghapus semua wilayah dari contoh data awal, sebaiknya menggunakan Pengaturan > Database > Kosongkan DB.

Jadi sebaiknya kotak centang dihapus, bukan digunakan untuk hapus wilayah terpilih.

**Comment by eddieridwan** [comment]
Sudah dicommit ke `master` melalui PR #2819
