### ISSUE TITLE
Bug login erorr di openSID 20.01

### ISSUE THREAD

**Issue by mering22** [OpenSID/OpenSID#2820]
### Bagaimana alurnya sampai muncul masalah?
awalnya coba ganti background Halaman Login

### Seperti apa yang diharapkan?
diharapkan  bisa normal kembali

### Apa yang terjadi?
tidak bisa masuk atau login admin

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
@mering22 ini sepertinya masalah pengubahan script yg anda lakukan. Untuk masalah penggunaan OpenSID, harap tanyakan di https://www.facebook.com/groups/OpenSID.

Issue ini kami tutup, karena bukan terkait error di sistem. Silakan buka kembali kalau ada informasi tambahan yg menunjukkan ini kesalahan di rilis.

**Comment by mering22** [comment]
Okey Admin..

**Comment by mering22** [comment]
oh ia tapi saya tidak merubah script nya min..
saya cuma mengubah background dengan menggunakan CPANEL di File Manager
