### ISSUE TITLE
Beberapa Hosting Tidak Support Field dgn Default Value "Null"

### ISSUE THREAD

**Issue by afa28** [OpenSID/OpenSID#2821]
### Bagaimana alurnya sampai muncul masalah?
Salah satu contoh hosting yg error jika inport databse https://www.000webhost.com/ karena tdk support nilai NULL

### Seperti apa yang diharapkan?
Support

### Apa yang terjadi?
Tidak error

### Informasi tambahan 
Pesan Error

Variable ‘sql_mode’ can’t be set to the value of ‘REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE( @@sql_mode’

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sebaiknya kita tidak mendukung hosting yg tidak sanggup menyimpan nilai default NULL. Sebaiknya kita tidak mengubah struktur database untuk masalah ini, karena akan menyebabkan struktur database kita tidak lagi utuh (yaitu menggunakan struktur database yg tidak optimal atau tidak sesuai model data).

**Comment by eddieridwan** [comment]
Lebih baik kita jelaskan di https://github.com/OpenSID/OpenSID/wiki/Panduan-Install-OpenSID syarat minimal untuk server yg digunakan untuk hosting. Menganjurkan desa TIDAK menggunakan hosting gratis, kecuali untuk coba-coba saja. Karena resiko ancaman keamanan data akan jauh lebih tinggi.

**Comment by afa28** [comment]
> Lebih baik kita jelaskan di https://github.com/OpenSID/OpenSID/wiki/Panduan-Install-OpenSID syarat minimal untuk server yg digunakan untuk hosting. Menganjurkan desa TIDAK menggunakan hosting gratis, kecuali untuk coba-coba saja. Karena resiko ancaman keamanan data akan jauh lebih tinggi.

Siap pak @eddieridwan
