### ISSUE TITLE
Tebel daftar penduduk kurang responsif.

### ISSUE THREAD

**Issue by asalreview** [OpenSID/OpenSID#2824]
### Bagaimana alurnya sampai muncul masalah?
Kira-kira kalo penerapan tabel seprti ini bisa gk ya?
https://examples.bootstrap-table.com/#extensions/fixed-columns.html

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
kyak di excel itu ya, yg di frezz kolom/baris???

**Comment by asalreview** [comment]
@afa28 ia benar pak

**Comment by balongbesuk** [comment]
Bagian mana yang mau difreeze, tidak difreeze saja tampilak d hp sudah sesak, 😄

**Comment by afa28** [comment]
Untuk layar besar mungkin bagus, tp untuk layar kecil kurang layak untuk diterapkan.

**Comment by mizwaruddin** [comment]
@afa28 apakah masih akan ditindaklanjuti?

**Comment by afa28** [comment]
> @afa28 apakah masih akan ditindaklanjuti?

Untuk saat ini tidak perlu.
