### ISSUE TITLE
Subbidang yang memiliki kegiatan lebih dari satu pada Rab siskeudes tidak akan tampil di tabel laporan keuangan perbidang.

### ISSUE THREAD

**Issue by asalreview** [OpenSID/OpenSID#2826]
### Bagaimana alurnya sampai muncul masalah?
Subbidang yang memiliki kegiatan lebih dari satu pada Rab siskeudes tidak akan tampil di tabel laporan keuangan perbidang.
![image](https://user-images.githubusercontent.com/60563749/77345000-9c06bb00-6d66-11ea-813b-2a360a2a2c08.png)

![image](https://user-images.githubusercontent.com/60563749/77345269-f6078080-6d66-11ea-925a-34d3736efff6.png)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.03
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
Apakah ini masih bermasalah???

**Comment by mizwaruddin** [comment]
@afa28 di saya tidak ada masalah.

**Comment by afa28** [comment]
> @afa28 di saya tidak ada masalah.

Silahkan reopen issue ini jika masih bermasalah.
