### ISSUE TITLE
[Bug] Error Saat Edit Lokasi Pengaturan Lokasi > Lokasi

### ISSUE THREAD

**Issue by ZER07URN** [OpenSID/OpenSID#2828]
### Bagaimana alurnya sampai muncul masalah?
Edit salah satu (Selain no 1) lokasi yang ada, lakukan perubahan kemudia save. Maka akan muncul error database mengenai primary key

### Seperti apa yang diharapkan?
tdk terjadi error database

### Apa yang terjadi?
update lokasi dpt dilakukan

### Informasi tambahan 
Testing : https://demo.opensid.my.id/plan

![Capture](https://user-images.githubusercontent.com/7290110/77441686-4c82c680-6e1c-11ea-9fb7-4603371111e1.PNG)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dicommit ke `master` melalui PR #2860
