### ISSUE TITLE
Jangan munculkan Artikel Statis di Halaman Utama

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#2830]
### Bagaimana alurnya sampai muncul masalah?
Muncul artikel statis di halaman utama.

### Seperti apa yang diharapkan?
Agar artikel yang berkategori dengan ID 999, 1000, dan 1001 (artikel statis) tidak muncul di halaman utama yang terletak ditampilan depan.

### Apa yang terjadi?
Di halaman utama hanya menampilkan artikel SELAIN artikel statis.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
Pak @ariandii , apakah termasuk di halaman arsip tdk ditampilkan???

**Comment by eddieridwan** [comment]
Permintaan ini perlu dikonsultasikan dulu dengan komunitas pengguna, sebelum disetujui.

**Comment by asalreview** [comment]
ada benarnya juga, mengingat artikel statis ada di menu.

**Comment by afa28** [comment]
Coba lempar ke Forum FB

**Comment by ariandii** [comment]
> Pak @ariandii , apakah termasuk di halaman arsip tdk ditampilkan???

untuk halaman arsip bisa ditampilkan untuk seluruh artikel, termasuk artikel statis.

**Comment by afa28** [comment]
Pak @eddieridwan , @ariandii , @asalreview . Dari hasil polling masih ada yg menginkan Agar artikel yang berkategori dengan ID 999, 1000, dan 1001 (artikel statis)  tetap dimunculkan di halaman utama.

Jadi mungkin solusinya memberikan pilihan pengaturan aplikasi tentang artikel yg ditampilkan di halaman utama.

**Comment by afa28** [comment]
Bagaimna ini Pak?? bisa dieksekusi??

**Comment by asalreview** [comment]
Katagori ID 1001 tetap tampil karena itu artikel tabel keuangan siskeudes. sedangkan ID 1000 kan emang gak tampil lagi dihalaman dpan, tinggal klo menurut saya ID 999 ikut di batasi di halaman depan, tpi di arsip di tampilkan aja smua. atau ya gmana pendapat banyak aja.

**Comment by asalreview** [comment]
Pak @afa28 sebaiknya dibatasi saja untuk tampil dihalaman depan ke 3 id di atas, biar gk terlalu rumit hal ini.

**Comment by eddieridwan** [comment]
Bung @afa28 , perubahan seperti ini, yg berdampak luas tapi pasti ada pro-kontra, perlu dibuat penjelasan alasan yg meyakinkan. Kemudian perlu dikonsultasikan di FB. Sebelum itu sebaiknya permintaan seperti ini jangan dikerjakan dulu. Karena kita mengembangkan untuk SEMUA pengguna, bukan satu-dua saja.

Kalau memang berminat, silakan buat jajak pendapat di FB. Tapi pastikan ada penjelasan. Penjelasan bukan berdasarkan nomor kategori, tapi dari segi KONSEP berbagai jenis artikel.

**Comment by eddieridwan** [comment]
@afa28 apabila jajak pendapat di FB menunjukkan perlunya ada setting jenis artikel yg akan ditampilkan, silakan diterapkan. Selain di halaman Pengaturan > Aplikasi, sebaiknya setting tersebut juga bisa diubah di Admin Web > Artikel. Lihat gambar di bawah sebagai contoh:
<img width="1377" alt="jenis-artikel-web" src="https://user-images.githubusercontent.com/249563/77603265-bd80c600-6f63-11ea-8385-a6b4b064537a.png">

Defaultnya adalah:

1. tampilkan artikel keuangan
2. tampilkan artikel statis
3. jangan tampilkan artikel agenda

**Comment by afa28** [comment]
Issue ini belum sy krjakan, masih menunggu masukan 🙏

**Comment by eddieridwan** [comment]
Bung @afa28 , untuk mendapat masukan, pastikan membuat jajak pendapat di https://www.facebook.com/groups/OpenSID/.

**Comment by afa28** [comment]
issue terkait #1757

**Comment by afa28** [comment]
Kayaknya sy lupa kerja issue ini.

**Comment by hasap86** [comment]
kalau di Wordpress halaman statis ini disebutnya Page / Halaman, secara default tidak diterbitkan sebagai artikel di beranda tapi khusus dipanggil di menu. saya fikir sih halaman statis memang tidak perlu ditampilkan sebagai artikel di beranda

**Comment by afa28** [comment]
> kalau di Wordpress halaman statis ini disebutnya Page / Halaman, secara default tidak diterbitkan sebagai artikel di beranda tapi khusus dipanggil di menu. saya fikir sih halaman statis memang tidak perlu ditampilkan sebagai artikel di beranda

Betul, bisa di contoh cms wordpress u/ penanganan halaman website.

**Comment by hasap86** [comment]
Up...
saran default untuk artikel statis semuanya jangan ditampilkan (seperti wordpress), namun jika ada yg ingin ditampilkan sebaiknya dikasih setingan disaat membuat artikel di sebelah kanannya dikasih pilihan

- [ ] Tampilkan sebagai artikel biasa

sehingga beberapa artikel statis bisa ditampilkan sebagai artikel / blog
