### ISSUE TITLE
Munculkan grafik APBDesa di semua Footer

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#2831]
### Bagaimana alurnya sampai muncul masalah?
Belum ada menampilkan Grafik APBDesa saat membuka artikel.

### Seperti apa yang diharapkan?
Selain tampil di halaman utama, Grafik APBDesa dapat ditampilkan pula saat sedang membuka artikel.

### Apa yang terjadi?
Sehingga saat pengunjung membuka website bersumber dari hasil share Artikel, dapat mengetahui adanya Grafik APBDesa di website tersebut.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
Coba sytaxnya simpan di atas foother, biar slalu ikut

**Comment by ariandii** [comment]
walau simpan di footer, hanya muncul di halaman depan.

**Comment by afa28** [comment]
karena di controllernya tdk dipanggil pak, jd nilai transparansinya null (tdk dimunculkan)

**Comment by ariandii** [comment]
ada solusi untuk memanggil controller?

**Comment by eddieridwan** [comment]
Sudah dicommit ke `master` melalui PR #2980
