### ISSUE TITLE
[Bug] Tambah Anggota Keluarga di Form KK Gagal Error 505

### ISSUE THREAD

**Issue by mr703** [OpenSID/OpenSID#2832]
### Bagaimana alurnya sampai muncul masalah?
Penambahan Anggota Keluarga dari Form Penambahan anggota Keluarga di KK tidak dapat disimpan muncul error 505

### Seperti apa yang diharapkan?
Penambahan anggota keluarga baru di form KK dapat disimpan

### Apa yang terjadi?
Ketika disimpan Gagal, muncul error 505

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.03Pasca
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
@mr703 Kami coba tidak bermasalah. Silakan tampilkan tampakan layar errornya, termasuk langkah yg anda lakukan sampai menghasilkan error.

**Comment by afa28** [comment]
![Capture](https://user-images.githubusercontent.com/57283157/77777783-9ff64e00-7082-11ea-9372-7c7b2f8e1408.PNG)

Mungkin lain kali pak @mr703 mengikutkan screenshoot error nya

**Comment by mr703** [comment]
![20200326_114034](https://user-images.githubusercontent.com/50432012/77817758-28ff9a80-7100-11ea-96f8-8ff03a4a1aa9.jpg)

**Comment by mr703** [comment]
Iya seperti SS diatas,,

**Comment by eddieridwan** [comment]
Sudah dicommit ke `master` melalui #2847
