### ISSUE TITLE
[Buku Admin Desa] BUKU REKAPITULASI JUMLAH PENDUDUK

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#2833]
### Bagaimana alurnya sampai muncul masalah?
Belum ada Buku Rekapitulasi Jumlah Penduduk sesuai dengan Permendagri 47 Tahun 2016
![image](https://user-images.githubusercontent.com/25834335/77638176-b7094300-6f91-11ea-9429-bab23e746a60.png)
cara pengisian : 
![image](https://user-images.githubusercontent.com/25834335/77638237-c7b9b900-6f91-11ea-8fef-099056c0a55c.png)
![image](https://user-images.githubusercontent.com/25834335/77638254-d0aa8a80-6f91-11ea-9511-bf61c170e6ee.png)

### Seperti apa yang diharapkan?
Adanya Buku Rekapitulasi Jumlah Penduduk

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
Pak @eddieridwan, sy coba bantu kerjakan issue ini. Kyaknya ini sma dgn laporan bulanan (?), tp mungkin untuk pertama sy ikuti cara pengisian yg disediakan di buku tsb.

**Comment by eddieridwan** [comment]
@afa28 mohon prioritaskan issue https://github.com/OpenSID/OpenSID/issues/2774 dan https://github.com/OpenSID/OpenSID/issues/2775, supaya Buku Administrasi Umum bisa rampung. Inginnya masing2 sub-modul Buku Administrasi Desa diselesaikan satu per satu, supaya jelas bagi pelanggan dan juga bagi calon pelanggan lebih mudah mengikuti. Kalau Buku Administrasi Umum sdh lengkap, kita bisa beri aturan/jadwal kapan nanti bisa masuk ke rilis umum. Terima kasih.

**Comment by afa28** [comment]
> @afa28 mohon prioritaskan issue https://github.com/OpenSID/OpenSID/issues/2774 dan https://github.com/OpenSID/OpenSID/issues/2775, supaya Buku Administrasi Umum bisa rampung. Inginnya masing2 sub-modul Buku Administrasi Desa diselesaikan satu per satu, supaya jelas bagi pelanggan dan juga bagi calon pelanggan lebih mudah mengikuti. Kalau Buku Administrasi Umum sdh lengkap, kita bisa beri aturan/jadwal kapan nanti bisa masuk ke rilis umum. Terima kasih.

Ok, sy coba krjakan issue #2775 klw blum ad yg krjkn

**Comment by afa28** [comment]
Sudah di `Fitur Premium`
