### ISSUE TITLE
[Buku Admin Desa] BUKU PENDUDUK SEMENTARA

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#2834]
### Bagaimana alurnya sampai muncul masalah?
Belum ada Buku Penduduk Sementara
![image](https://user-images.githubusercontent.com/25834335/77638456-297a2300-6f92-11ea-9519-4dc316adbb64.png)
cara pengisian : 
![image](https://user-images.githubusercontent.com/25834335/77638553-4f072c80-6f92-11ea-8242-5770404953cd.png)

### Seperti apa yang diharapkan?
Perlu di buatkan Buku Penduduk Sementara 

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Perhatikan skenario berikut:

> Ahmad dengan NIK 1234567890123456 datang ke desa pada bulan Oktober 2019 untuk menjaga rumah bu Maimunah yg ditinggal kosong menemani anaknya di Jakarta yg akan melahirkan anak pertama. Pada bulan Mei 2020 Ahmad meninggalkan desa karena bu Maimunah sudah kembali ke desa. 
> 
> Pada bulan Agustus 2020, Ahmad kembali datang ke desa untuk menggarap sawah bu Maimunah. Sampai sekarang Ahmad masih ada di desa.

Di daftar Penduduk, Ahmad tampil sebagai penduduk tidak tetap untuk masa:

- Oktober 2019 s/d Mei 2020
- Agustus 2020 sampai sekarng

Di Buku Penduduk Sementara, Ahmad tampil sebagai berikut:

- Oktober 2019 s/d Apr 2020, tampil dengan data tanggal datang di bulan Oktober 2019, dengan alasan menjaga rumah warga dan tanggal pergi kosong
- Mei 2020 s/d `bulan XX thn YY` , tampil seperti di atas dengan tanggal pergi di bulan Mei 2020. `Perlu ditentukan berapa lama penduduk sementara yg sudah pergi tetap tampil di Buku Penduduk Sementara`. Idealnya hanya ditampilkan selama bulan tersebut saja. Yaitu di bulan Juni 2020 sudah tidak tampil lagi.
- Agustus 2020 s/d sekarang, tampil dengan data tanggal datang di bulan Agustus 2020, dengan alasan menggarap sawah warga dan tanggal pergi kosong

Di Log Penduduk, Ahmad tampil sebagai berikut:

- Datang pada bulan Oktober 2019, dengan keterangan menjaga rumah warga
- Pergi pada bulan Mei 2020, dengan keterangan meninggalkan desa
- Datang pada bulan Agustus 2020, dengan keterangan menggarap sawah warga

**Comment by mizwaruddin** [comment]
Betul, Bang.

**Comment by eddieridwan** [comment]
Solusi teknis sbb.

1. Kolom tanggal datang, alasan dan tanggal pergi diletakkan di tabel `log_penduduk`, bukan di `tweb_penduduk`.
2. Entri log_penduduk dibuat bagi Ahmad pada waktu menambah penduduk, dengan mengisi tanggal datang dan alasan.
3. Di Daftar Penduduk, sediakan jenis ubah status dasar `Pergi` untuk penduduk tidak tetap. Aksi ini mengubah status dasar penduduk ybs menjadi `pergi` (status dasar baru). Aksi 'Pergi` ini juga memasukkan tanggal pergi ke entri log_penduduk di (2)
4. Di daftar Log Penduduk, bagi penduduk tidak tetap dengan status dasar `pergi`, disediakan aksi Kembali. Aksi ini akan membuat entri baru di log_penduduk sebagai penduduk datang, seperti di (2) di atas. Yaitu di `log_penduduk` akan ada dua entri untuk Ahmad. Aksi Kembali ini juga mengubah status dasar penduduk ybs menjadi `hidup`.
5. Penduduk tidak tetap dengan status dasar `pergi` tidak bisa tambahkan lagi melalui Tambah Penduduk, karena NIK ybs sudah ada. Kalau pengguna mencoba melakukan, beritahu supaya menggunakan aksi `Kembali` di Log Penduduk. 

Daftar Penduduk dan Buku Penduduk Sementara disusun dengan menggunakan informasi yg ada di `log_penduduk` seperti di atas.

**Comment by af-lazuardi** [comment]
Okay noted

**Comment by mizwaruddin** [comment]
Cocok, Bang

**Comment by afa28** [comment]
Sudah di `Fitur Premium`
