### ISSUE TITLE
[Buku Admin Desa] BUKU KARTU TANDA PENDUDUK DAN BUKU KARTU KELUARGA

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#2835]
### Bagaimana alurnya sampai muncul masalah?
![image](https://user-images.githubusercontent.com/25834335/77639131-38150a00-6f93-11ea-9319-514ac9e5f85c.png)
cara pengisian : 
![image](https://user-images.githubusercontent.com/25834335/77639169-47945300-6f93-11ea-8928-955c348c9143.png)

### Seperti apa yang diharapkan?
Perlu Dibuatkan BUKU KARTU TANDA PENDUDUK DAN BUKU KARTU KELUARGA

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by koes65** [comment]
Bagaimana NIK penduduk yg meninggal dibawah tahun 1960

**Comment by afa28** [comment]
Sudah di `Fitur Premium`
