### ISSUE TITLE
[Buku Admin Desa]  BUKU TANAH DI DESA

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#2836]
### Bagaimana alurnya sampai muncul masalah?
![image](https://user-images.githubusercontent.com/25834335/77639327-89bd9480-6f93-11ea-9d74-e66414dce61d.png)
cara pengisian :
![image](https://user-images.githubusercontent.com/25834335/77639349-96da8380-6f93-11ea-9813-cec03a55188e.png)
![image](https://user-images.githubusercontent.com/25834335/77639360-9d68fb00-6f93-11ea-941f-b89f6e3f554d.png)

### Seperti apa yang diharapkan?
Perlu dibuatkan BUKU TANAH DI DESA

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sdh dicommit ke `rilis-dev` melalui https://github.com/OpenSID/premium/pull/131
