### ISSUE TITLE
[Buku Admin Desa] BUKU TANAH KAS DESA

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#2837]
### Bagaimana alurnya sampai muncul masalah?
![image](https://user-images.githubusercontent.com/25834335/77639472-c5f0f500-6f93-11ea-8510-9d6c33a95cb0.png)
cara pengisian : 
![image](https://user-images.githubusercontent.com/25834335/77639539-e28d2d00-6f93-11ea-870e-2b068de5455d.png)
![image](https://user-images.githubusercontent.com/25834335/77639551-e7ea7780-6f93-11ea-8393-a0067a0ee6bd.png)

### Seperti apa yang diharapkan?
perlu dibuatkan BUKU TANAH KAS DESA

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sdh dicommit ke `rilis-dev` melalui https://github.com/OpenSID/premium/pull/131
