### ISSUE TITLE
[Buku Admin Desa]  BUKU INVENTARIS DAN KEKAYAAN DESA

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#2838]
### Bagaimana alurnya sampai muncul masalah?
![image](https://user-images.githubusercontent.com/25834335/77639692-1700e900-6f94-11ea-8063-de7bf5b941b0.png)
cara pengisian : 
![image](https://user-images.githubusercontent.com/25834335/77639728-2a13b900-6f94-11ea-89bf-f8fb84f06448.png)
![image](https://user-images.githubusercontent.com/25834335/77639748-313ac700-6f94-11ea-8787-ff7015cf0f2c.png)

### Seperti apa yang diharapkan?
Buku Inventaris dan Kekayaan desa yang sekarang ada di menu inventaris perlu disederhanakan sesuai dengan permendagri 47 tahun 2016

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by mizwaruddin** [comment]
Buku administrasi dapat digabungkan dengan menu inventaris yang sudah ada. Namun, ada dua dua isian yang belum tersedia di menu inventaris, yaitu:
1. Kondisi di awal tahun (Baik/Rusak)
2. Kondisi di akhir tahun (Baik/Rusak)
Untuk memenuhi isian tersebut ada dua solusi, yaitu ditambahkan input status asset pada form mutasi yang berisi "baik, diperbaiki, rusak, dihapus". untuk perhitungan tahun awal diambil dari tahun n-1 sedangkan tahun akhir diambil dari data yang paling terbaru.

**Comment by mizwaruddin** [comment]
Dari jenis2 inventaris/aset yang ada menu inventaris, khusus inventaris dalam bentuk tanah kas desa tidak perlu dimasukkan di buku administrasi inventaris dan kekayaan desa.

**Comment by eddieridwan** [comment]
Sdh dicommit ke `rilis-dev` melalui https://github.com/OpenSID/premium/pull/208

**Comment by Zoel-WB** [comment]
Ada Pilihan dari Sumber Anggaran Perolehan, Tahun anggaran sepertinya tak ada masalah karena sudah terwakili oleh Tanggal Dokumen dan tanggal mulai sudah menjelaskan keterangan tahun anggarannya
1. APBN (DD)
2. Pemerintah Provinsi
3. Pemerintah Kabupaten
4. Hibah/Sumbangan/Wakaf 
5. Secara Swakola
