### ISSUE TITLE
Data DPT tidak masuk grup statistik

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#2839]
### Bagaimana alurnya sampai muncul masalah?
buka admin web > menu > sub menu > tambah sub menu > cari grup (temukan dpt)

### Seperti apa yang diharapkan?
link data DPS ada

### Apa yang terjadi?
pengguna awan tidak tahu akan adanya fitur tersebut

### Informasi tambahan 
![sadasdas](https://user-images.githubusercontent.com/35319600/77713141-2f125000-7008-11ea-9cb9-55c31c3a42b8.jpg)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
Untuk DPT bisa ditambahkan melalui jenis_link > statistik penduduk > calon pemilih.

untuk DPT fuction tdk digabungkan ke dalam fuction statistik. Jadi mungkin urlnya tdk masud dalam kategori statistik.

**Comment by balongbesuk** [comment]
Atau mungkin bs d tambah d halaman statis lainnya?

**Comment by eddieridwan** [comment]
Tambahkan ke halaman statis lainnya.

**Comment by MUHAMMADRANGSEL** [comment]
Apakah Seperti gambar dibawah ini yang dimaksud : 
![image](https://user-images.githubusercontent.com/25834335/77770992-109c6b00-7081-11ea-9b43-8827bfc9d84a.png)

**Comment by eddieridwan** [comment]
Betul, bung @MUHAMMADRANGSEL . Ok, issue ini ditutup saja.
