### ISSUE TITLE
sinkronisasi data persil dengan peta layer polygon

### ISSUE THREAD

**Issue by widodoari** [OpenSID/OpenSID#284]
dimungkinkan tidak koneksi data persil dengan peta dengan layer polygon, seperti yang sudah ada ada data penduduk dengan layer poin

![screenshot_29](https://cloud.githubusercontent.com/assets/13248793/22871346/ab43e532-f1e2-11e6-9bc8-49b7baa9c958.png)

**Comment by mizwaruddin** [comment]
@afa28 ganda
