### ISSUE TITLE
Penambahan FItur untuk Admin BPD dan Bumdes 

### ISSUE THREAD

**Issue by chepygiovanni** [OpenSID/OpenSID#2840]
### Seperti apa yang diharapkan?

Saya harap Open SID bisa menambahkan fitur untuk BPD dan BUMDES agar bisa Saling terhubung ke Desa Langsung jadi laporan lebih simple dan praktis tanpa harus menunggu atau jarak dan waktu.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
Mungkin terlebih dahulu, informasi mengenai issue ini lebih dilengkapi.

**Comment by kurniyawan0490** [comment]
Saya harap Open SID bisa menambahkan fitur untuk BPD dan BUMDES agar bisa Saling terhubung ke Desa Langsung jadi laporan lebih simple dan praktis tanpa harus menunggu atau jarak dan waktu.

**Comment by balongbesuk** [comment]
Programer itu bukan orang yang paham regulasi desa, maka dijelaskan sejelas jelasnya, terhubung dalam hal apa, laporan apa yang dikehendaki, jelaskan secara rinci

**Comment by M-A-Haris** [comment]
kalau mau interaksi langsung gunakan aplikasi zoom cloud meeting saja bisa digunakan untuk rapat-rapat dengan BPD. untuk fitur BPD dan BUMDes sudah ada menu Admin WEB terkait struktur BPD,  lembaga kemasyaraktan desa termasuk untuk promosi usaha Bumdes..

**Comment by andifahruddinakas** [comment]
Sudah di fitur premium, bisa buatkan group khusus.
