### ISSUE TITLE
Tambahkan settingan url website

### ISSUE THREAD

**Issue by elkautzar** [OpenSID/OpenSID#2842]
### Bagaimana alurnya sampai muncul masalah?
Update saat ini url sudah mengakaplikasikan konsep slug sebagai standar url. Namun belum ada pengaturan jika ingin menggunakan url dengan id atau lainnya. 

### Seperti apa yang diharapkan?
Berikan akses bagi pengguna untuk melakukan pengaturan mengenai jenis url yg ingin digunakan (standar webportal)

### Apa yang terjadi?
Pengguna dapat menyesuaikan urlnya sendiri

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
Catatan :
1. Tambahkan di pengaturan aplikasi > permalink
2. Sediakan beberapa contoh permalink (bisa lihat contoh pd wordpress)

**Comment by andifahruddinakas** [comment]
Duplikasi https://github.com/OpenSID/OpenSID/issues/4512
