### ISSUE TITLE
Penambahan informasi Desa Lawan Corona

### ISSUE THREAD

**Issue by M-A-Haris** [OpenSID/OpenSID#2843]
### Bagaimana alurnya sampai muncul masalah?
Agar seluruh desa membentuk Relawan Desa Lawan Covid-19 dengan Terbitnya  surat edaran Menteri desa, Pembangunan Daerah Tertinggal dan Transmigrasi RI  Nomor 08 tahun 2020 tentang Desa Tanggap Covid-19 dan Penegasan Padat Karya Tunai Desa. 

### Seperti apa yang diharapkan?

Setiap saat terbit informasi perkembangan Covid-19 di seluruh website Opensid
### Apa yang terjadi?

Bentuk kepedulian OpenSID dalam pencegahan Covid-19 yang sudah menjadi bencana kemanusiaan.
### Informasi tambahan 
Fitur  RSS Feed  sudah digunakan Pertama kali oleh Bung  Aryandi Riyan Kahfi di https://www.covid19.go.id/feed
ke Website Desa https://natairaya.desa.id 
agar dapat menampilkan Artikel Terakhir berita COVID-19 secara otomatis. :)

#
| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Bung @ariandii , karena anda sudah terapkan di tema natra, sepertinya anda yg paling tepat untuk menerapkan di tema klasik dan hadakewa. Apakah anda ada waktu?

**Comment by eddieridwan** [comment]
Sudah dicommit ke `master`.
