### ISSUE TITLE
Menu pada Layanan Mandiri tidak proporsional

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#2845]
### Bagaimana alurnya sampai muncul masalah?
Menu Layanan Mandiri melebar ke kanan.

![lebar](https://user-images.githubusercontent.com/46939846/77828115-2fb3ff00-714c-11ea-8429-832035549a92.png)

### Seperti apa yang diharapkan?
Sesuai dengan posisinya.

### Apa yang terjadi?
Terlihat proporsional.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by asalreview** [comment]
seperti halaman menu admin sepertinya lebih bagus

**Comment by Nurhidayat29** [comment]
![Sistem Informasi Desa Desa Senggig1 Layanan Mandiri - Google Chrome 29_03_2020 01 57 45](https://user-images.githubusercontent.com/51182125/77831311-f46ffb00-7160-11ea-94f3-e9768c91c8bf.png)

**Comment by ariandii** [comment]
solve
