### ISSUE TITLE
Belum adanya menu ganti pin di halaman mandiri

### ISSUE THREAD

**Issue by asalreview** [OpenSID/OpenSID#2850]
### Bagaimana alurnya sampai muncul masalah?
Belum adanya menu ganti pin di halaman mandiri, sehingga jika ingin menganti pin harus kembali ke wigdet dan hanya bisa sekali ganti.

### Seperti apa yang diharapkan?
memiliki menu ganti pin seperti dihalaman admin

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.03
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Duplikat #134. Selalu usahakan periksa dulu apakah permintaan sudah dilaporkan sebelumnya. Kemudian tambahkan informasi di issue yg sudah ada dan beri jempol supaya prioritasnya naik.

Ok. Issue ini ditutup karena duplikat.
