### ISSUE TITLE
Configurasi Database

### ISSUE THREAD

**Issue by asalreview** [OpenSID/OpenSID#2852]
### Bagaimana alurnya sampai muncul masalah?
beberapa hosting dengan menerapkan $db['default']['stricton'] = TRUE;  import database keuangan siskeudes yang memiliki database beberapa desa akan menyebabkan error database

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.03
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Selalu lampirkan tangkapan layar errornya. Dalam hal ini, juga lampirkan data siskeudes yg bermasalah.
