### ISSUE TITLE
Perlu Informasi Data Base Pemudik atau pendatang untuk Cegah Covid-19

### ISSUE THREAD

**Issue by M-A-Haris** [OpenSID/OpenSID#2856]
### Tabel yang dibutuhkan mencakup
1. Identitas penduduk (domisili dan non domisili)
2. Asal kedatangan (nama daerah dan status daeah (daerah zona merah, kuning, hijau)
3. Tanggal datang
3. Rencana lama mudik/tinggal
4. Maksud kedatangan (mudik/menjenguk orang tua/diphk dll)
6. Keluhan (panas,flu, batuk, sesak, dan penyakit lainnnya.
7. Kewajiban isolasi diri sampai tanggal (14 hari dari kedatangan)
8. No HP yang bisa dihubungi

### Diharapkan muncul grafik pemudik baik penduduk maupun domisili luar daerah

Diharapkan bisa dirilis pada 
| Versi OpenSID  20.04 pasca ..

**Comment by af-lazuardi** [comment]
okey, noted, saya garap Pak ya.

**Comment by Jhiban-Khang** [comment]
Klo disaya, desa saya memanfaatkan fitur suplemen pada tab PENDUDUK, pada kolom isian keterangan saya isi tgl datang dan asal perantauan.

**Comment by af-lazuardi** [comment]
Iya benar bisa juga memanfaatkan data suplemen, gimana Pak @M-A-Haris ? Cukup melalui data suplemen / data analisis?

**Comment by kurniyawan0490** [comment]
Diharapkan muncul grafik pemudik baik penduduk maupun domisili luar daerah

**Comment by kurniyawan0490** [comment]
diharapkan OpenSID memunculkan data base pemudik atau warga luar daerah yang datang ke desa untuk meningkatkan pengawasan agar mengisolasi mandiri selama 14 hari. Sehingga penularan covid bisa diredam.

**Comment by M-A-Haris** [comment]
> Iya benar bisa juga memanfaatkan data suplemen, gimana Pak @M-A-Haris ? Cukup melalui data suplemen / data analisis?

karena ini menyakut kedaruratan namun berguna juga untuk kedepannya, lebih baik disempurnakan, terutama kondisi perantau/penduduk tidak aktif. memudahkan operatur dalam mendata pendatang dalam situasi bencana covid-19. termasuk memudahkan informasi bagi masyarakat desa untuk melakukan pengawasan

**Comment by M-A-Haris** [comment]
> Klo disaya, desa saya memanfaatkan fitur suplemen pada tab PENDUDUK, pada kolom isian keterangan saya isi tgl datang dan asal perantauan.

coba dijelaskan dan ditampilkan hasilnya di website sperti apa?

**Comment by eddieridwan** [comment]
@M-A-Haris @af-lazuardi @kurniyawan0490 @Jhiban-Khang 

Di form penduduk, bisa gunakan status Tidak Tetap atau Pendatang. Ini sudah ada sejak lama. 
<img width="1440" alt="pendatang" src="https://user-images.githubusercontent.com/249563/78217778-68ffbc80-7508-11ea-9614-10ffe33fb996.png">

Jika ingin menyimpan informasi tambahan bagi pendatang tersebut, sebaiknya gunakan fitur Data Suplemen.

**Comment by M-A-Haris** [comment]
Tabel yang dibutuhkan mencakup
Identitas penduduk (domisili dan non domisili)
Asal kedatangan (nama daerah dan status daeah (daerah zona merah, kuning, hijau)
Tanggal datang
Rencana lama mudik/tinggal
Maksud kedatangan (mudik/menjenguk orang tua/diphk dll)
Keluhan (panas,flu, batuk, sesak, dan penyakit lainnnya.
Kewajiban isolasi diri sampai tanggal (14 hari dari kedatangan)
No HP yang bisa dihubungi
Diharapkan muncul grafik pemudik baik penduduk maupun domisili luar daerah

ini sifatnya seperti pendataan BPNT, atau Kelompok , tetap memanfaatkan data penduduk desa, baik domisi maupun pendatang. hanya grafiknya diharapkan bisa muncul di website..

**Comment by M-A-Haris** [comment]
Website OpenSID diharapkan bisa memberikan Informasi terkait kondisi pemudik. apalagi jelang lebaran atau kondisi penyebaran covid terus meningkat...

**Comment by M-A-Haris** [comment]
yang memanfaatkan informasi ini bukan hanya pemerintah desa, juga kecamatan, puskesmas, dinas kesehatan, kepolisian...

**Comment by M-A-Haris** [comment]
tabel tersebut berdasarkan anjuran dari kesehatan untuk meredam penyebaran covid-19 dan agar para pemudik tinggal selama 14 hari untuk memastikan tertular atau tidak covid 19

**Comment by M-A-Haris** [comment]
bahkan diharapkan bisa memunculkan tabel status covid-19.. jika (amit-amit) ada warga desa yang positif, PDP, ODP). seperti dalam https://pikobar.jabarprov.go.id/
![Uploading covid jabar.png…]

**Comment by M-A-Haris** [comment]
![covid jabar](https://user-images.githubusercontent.com/46555658/78223461-16ff6c80-74f1-11ea-8ade-b5aa143baee6.png)

**Comment by af-lazuardi** [comment]
Oke siap Pak. saya sudah menangkap urgensitasnya. Tetap saya kerjakan, karena ini memang KLB. Ntar tak sediain menu 'Siaga Covid-19'. Untuk pengolahan data nya lebih lanjut (tampil di map dsb) next issue ya, yang penting pendataannya ini selesai dulu,.

**Comment by kurniyawan0490** [comment]
> Oke siap Pak. saya sudah menangkap urgensitasnya. Tetap saya kerjakan, karena ini memang KLB. Ntar tak sediain menu 'Siaga Covid-19'. Untuk pengolahan data nya lebih lanjut (tampil di map dsb) next issue ya, yang penting pendataannya ini selesai dulu,.

Ok SETUJU

**Comment by eddieridwan** [comment]
Perekaman dasar sudah dicommit ke `master`. Mohon permintaan tambahan dimasukkan ke issue yg baru.
