### ISSUE TITLE
[Log Penduduk] Ubah Status Dasar menjadi Mati

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#2859]
### Bagaimana alurnya sampai muncul masalah?
Ketika Ubah status dasar menjadi mati belum ada kolom :
1. Jam Kematian
2. Penyebab Kematian
3. Yang menerangkan kematian
4.  Anak Ke
5. Nomor Akta Kematian

### Seperti apa yang diharapkan?
Ditambahkan kolom :
1. Jam Kematian
2. Penyebab Kematian
3. Yang menerangkan kematian
4.  Anak Ke
5. Nomor Akta Kematian
- Ketika mengubah status menjadi mati seperti ubah status dasar menjadi pindah ada pilihan
- Ketika membuat surat keterangan kematian untuk point 1 s/d 4 terisi otomatis
### Apa yang terjadi?
1. Jam Kematian
2. Penyebab Kematian
3. Yang menerangkan kematian
4.  Anak Ke
5. Nomor Akta Kematian
Tidak tersimpan didatabase 

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by Jhiban-Khang** [comment]
Biasanya saya tambahkan informasi tersebut di kolom ketersngan, penyebab kematian, mati di rumah atau di RS dll

**Comment by afa28** [comment]
Apa maksudnya saat mengubah status misal menjadi mati otomatis akan dialihkan ke pembuatan surat ket kematian dgn isian tsb???

**Comment by Nurhidayat29** [comment]
![edit log](https://user-images.githubusercontent.com/51182125/91067392-0ba60c80-e65d-11ea-9c16-87a9f4c4fdca.png)
bung @MUHAMMADRANGSEL apakah seperti ini yg diinginkn?

**Comment by MUHAMMADRANGSEL** [comment]
Pas banget

Pada tanggal Sen, 24 Agt 2020 23.57, Nur Hidayat <notifications@github.com>
menulis:

**Comment by MUHAMMADRANGSEL** [comment]
Ketika memilih status dasar mati maka akan muncul form tersebut

Pada tanggal Sel, 25 Agt 2020 03.21, MUHAMMAD SPD <muhammadrangsel@gmail.com>
menulis:

**Comment by Jhiban-Khang** [comment]
Iya, dan juga dgn update sekarang, kami kesulitan melihat data pindah, data
mati dll pada warga yg ubah status dasar mati, pindah dll

**Comment by andifahruddinakas** [comment]
Sudah digabung melalui PR https://github.com/OpenSID/premium/pull/731
