### ISSUE TITLE
Pengaturan Lokasi > lokasi 

### ISSUE THREAD

**Issue by afa28** [OpenSID/OpenSID#2863]
### Bagaimana alurnya sampai muncul masalah?
Saat melakukan edit baik itu data ataupun peta, nilai yg ditampilkan adalah value kosong/default bukan value dr database sesuai yg akan di edit.

### Seperti apa yang diharapkan?
tampilkan value sesuai data yg ingin di edit

### Apa yang terjadi?
agar setelah di edit dpt dterlihat perubahan.

### Informasi tambahan 
Mungkin bisa di cotoh pd modul wilayah administrasi
 
| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dicommit ke `master` melalui PR #2884
