### ISSUE TITLE
[Bug] Gagal Tulis Artikel

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#2864]
### Bagaimana alurnya sampai muncul masalah?
Saat menulis judul artikel yang lebih dari 100 karakter, halaman mengalami error 500 seperti gambar berikut yang saya coba di website http://demo.opensid.my.id/

![image](https://user-images.githubusercontent.com/46939846/78244303-82583700-750f-11ea-8640-592409f13a17.png)

### Seperti apa yang diharapkan?
Muncul notifikasi di halaman form artikel saat input judul yang lebih dari 100 karakter supaya penulis bisa memperbaiki judul tersebut dan melanjutkan proses penyimpanan.

**Comment by afa28** [comment]
Error krn batas input di database 100, mungkin hanya perlu ditambahkan max input 
judul di formnya

**Comment by asalreview** [comment]
@afa28 saran pak, sebaiknya di buat notifikasi batas nilai input judul, agar juga tidak terlalu panjang dan menghemat memory database.

**Comment by ariandii** [comment]
@afa28 dibuat max berapa? sebab jika ada notifikasi tersebut, mungkin juga berguna saat copy isi artikel dari web lain, dan terpaste di judul. mengakibatkan error tsb muncul kembali.

**Comment by eddieridwan** [comment]
Sudah dicommit ke `master` melalui PR #2966
