### ISSUE TITLE
Tampilan Header Tema Hadakewa

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#2865]
### Bagaimana alurnya sampai muncul masalah?
Saat input alamat website di menu info desa, header menjadi turun sehingga tampilannya sebagai berikut:
![image](https://user-images.githubusercontent.com/46939846/78247671-75d6dd00-7515-11ea-8dff-d519d1d796be.png)

**Comment by hasap86** [comment]
cukup tambahin margin-top: 20px; di file /partials/covid.php (baris ke 33)

	#covid .panel {
		background-color: inherit;
		margin-bottom: 0px;
		margin-top: 20px;
	}

**Comment by eddieridwan** [comment]
Sudah dicommit ke `master` melalui PR #2867

**Comment by ariandii** [comment]
![Screenshot_2020-04-04-19-51-26-70](https://user-images.githubusercontent.com/46939846/78451369-71dec280-76af-11ea-8365-8a54fcfaf595.png)

di hp masih begini
