### ISSUE TITLE
sebaiknya menu statis dihilangkan

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#2866]
### Bagaimana alurnya sampai muncul masalah?
supaya fokus pada waktu permohonan surat melalui Layanan Mandiri, untuk menu statis dihilangkan
![layanan](https://user-images.githubusercontent.com/25834335/78248345-11208000-751f-11ea-91c6-5406590cdbef.jpg)

### Seperti apa yang diharapkan?
Menu Statis dihilangkan 

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by asalreview** [comment]
dan sebaiknya foto penduduk yang login di tampilkan.

**Comment by MUHAMMADRANGSEL** [comment]
SETUJU

Pada Kha, 2 Apr 2020 pada 8:26 PTG Asal Review <notifications@github.com>
menulis:

**Comment by kurniyawan0490** [comment]
> dan sebaiknya foto penduduk yang login di tampilkan.

SETUJU

**Comment by eddieridwan** [comment]
Foto sudah ditampilkan melalui PR #2870

**Comment by afa28** [comment]
Mungkin bisa di re-design tampilanya biar lebih menarik

**Comment by balongbesuk** [comment]
kl tdk salah front end layanan mandiri bs d costum ikut tema masing2

**Comment by afa28** [comment]
> kl tdk salah front end layanan mandiri bs d costum ikut tema masing2

kalau tdk salah itu untuk versi yg lama, kalau untuk gabungan dr fitur premium masih ikut di sytem opensid

**Comment by balongbesuk** [comment]
ooo bgitu, sy jg blm sempet ngecek, msih betah d versi 19 akhir,

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3494
