### ISSUE TITLE
Bug tema hadakewa pada mode mobile

### ISSUE THREAD

**Issue by rullydamara** [OpenSID/OpenSID#2869]
### Bagaimana alurnya sampai muncul masalah?
Tampilan pada mode mobile atau hp pada tema hadekawa bertumpuk, dan saat menu diklik judul pada halaman melebar. ini terjadi pada homepage, peraturan desa, produk hukum dan data statistik.

### Informasi tambahan 
![Screenshot (33)](https://user-images.githubusercontent.com/45301948/78363614-3e843100-75e6-11ea-92ba-09cbd4b06c83.png)

![Screenshot (32)](https://user-images.githubusercontent.com/45301948/78363641-4e037a00-75e6-11ea-9212-a257968e5599.png)

![Screenshot (34)](https://user-images.githubusercontent.com/45301948/78365389-3c6fa180-75e9-11ea-85a1-7097df228af4.png)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.04
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dicommit ke `master` melalui PR #3020
