### ISSUE TITLE
Sembunyikan Menu Layanan Mandiri

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#2872]
### Bagaimana alurnya sampai muncul masalah?
Layanan mandiri digunakan untuk mempermudah warga dalam permohonan surat secara online.
Kecil kemungkinan warga menggunakan komputer atau laptop dalam mengajukan permohonan.
Penggunaan handphone lebih dominan dalam hal ini.

Saat ini Layanan Mandiri saat dibuka di Handphone, Layar full dengan tampilan Menu.
Sedikit mengganggu untuk proses isian. Saat sudah klik Menu, Warga mengira tidak ada proses apa-apa, padahal saat scrool ke bawah, sudah masuk ke halaman yang diklik.

### Seperti apa yang diharapkan?
Untuk Menu pada Halaman Layanan Mandiri dapat dibuat Toggle navigation supaya saat warga memilih menu pada layanan mandiri langsung dapat ditampilkan isinya, bukan kembali ke Layar menu lagi.

Tampilan di laptop:
![laptop](https://user-images.githubusercontent.com/46939846/78450250-9040c000-76a7-11ea-8e25-a5f0f9c26cf0.png)

Tampilan di HP:
![Screenshot_2020-04-04-19-04-52-70](https://user-images.githubusercontent.com/46939846/78450264-a0f13600-76a7-11ea-9dba-8e5adc644db5.png)

**Comment by afa28** [comment]
Duplicate issue https://github.com/OpenSID/OpenSID/issues/3696

**Comment by M-A-Haris** [comment]
Baiknya ada panduan penggunaan layanan mandiri/help.
