### ISSUE TITLE
Upload gambar yang ada saat ini di Resize apa di Crop ya? kok gambar kepotong?

### ISSUE THREAD

**Issue by asalreview** [OpenSID/OpenSID#2873]
### Bagaimana alurnya sampai muncul masalah?
Resize gambar yang di upload sepertinya keliru.

### Seperti apa yang diharapkan?
seharusnya gambar tidak di potong melainkan ukuran bingkai yang kecilkan (resize).

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.04
| Versi PHP        | 
| System operasi   |

**Comment by ariandii** [comment]
upload gambar dimana???
no capture = hoax

**Comment by asalreview** [comment]
@ariandii coba bapak upload gambar galery

**Comment by mizwaruddin** [comment]
Saya coba di web demo dg meng-upload gambar di galeri memang hasilkan terpotong, bukan di resize.

**Comment by afa28** [comment]
Mungkin disediakan edit sebelum foto/gambar di simpan.

**Comment by afa28** [comment]
Upload gambar di galeri hasilnya terpotong, jika ingin disesuaikan bisa di buat issue permintaan fitur sebelum foto disimpan bisa di edit.
