### ISSUE TITLE
Hasilkan PIN Berada pada Urutan Teratas

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#2874]
### Bagaimana alurnya sampai muncul masalah?
Saat ini pada halaman Pendaftaran Layanan Mandiri, Penduduk yang didaftarkan dengan klik Hasilkan PIN berada pada baris akhir (halaman akir)

### Seperti apa yang diharapkan?
Agar setiap penduduk yang baru dibuatkan PIN berada di baris nomor 1 (teratas)

### Apa yang terjadi?
Supaya bisa memastikan bahwa penduduk tersebut sudah terdaftar. Tidak perlu buka halaman akhir untuk memastikan NIK nya.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dicommit ke `master` melalui PR #2876
