### ISSUE TITLE
Nama Desa Hilang, Logo Berubah pada Halaman Mailbox Layanan Mandiri

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#2875]
### Bagaimana alurnya sampai muncul masalah?
Saat masuk ke menu Kotak Pesan dan klik Tulis Pesan yang ada di Layanan Mandiri, Nama Desa Hilang dan Logo Berubah Default.
![Untitled](https://user-images.githubusercontent.com/46939846/78455820-a3b15280-76ca-11ea-9b3d-03007c1e7210.png)

### Seperti apa yang diharapkan?
Sesuaikan dengan seharusnya.

**Comment by afa28** [comment]
Saya masih mutar2 cari view layanan mandiri, wkwkwkwk
Mungkin selanjutnya untuk controller, model dan view dibedakan menjadi 3 subfoler (frontend/website desa, layanan mandiri, backend/administrator). Karena programer baru kyak sy yg masih awam, agak sussah mencari file jika digabung dari 3nya.

**Comment by ariandii** [comment]
saat ini ada di donjo-app/views/web/mandiri

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3015
