### ISSUE TITLE
Layanan mandiri kurang responsive

### ISSUE THREAD

**Issue by afa28** [OpenSID/OpenSID#2877]
### Bagaimana alurnya sampai muncul masalah?
Login lanyanan mandiri pada mode ponsel, lihat form inputan dan table kurang resposive (melebihi layout)

### Seperti apa yang diharapkan?
Layanan mandiri responsive

### Informasi tambahan 
![Capture](https://user-images.githubusercontent.com/57283157/78457387-f6dbd300-76d3-11ea-9f4b-2cf8b512905d.PNG)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3040
