### ISSUE TITLE
Sediakan Tanggal Posting pada RSS Feed

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#2878]
### Bagaimana alurnya sampai muncul masalah?
Saat ini belum ada menampilkan waktu posting pada RSS Feed.

![image](https://user-images.githubusercontent.com/46939846/78459815-f4827480-76e5-11ea-8587-5d8349c72501.png)

### Seperti apa yang diharapkan?
Sediakan string waktu untuk menampilkan data kapan artikel tersebut di posting

**Comment by eddieridwan** [comment]
Gunakan format RFC-822 date-time (https://www.feedvalidator.org/docs/error/InvalidRFC2822Date.html)

**Comment by eddieridwan** [comment]
Sudah dicommit ke `master` melalui PR #2879
