### ISSUE TITLE
Bugs program bantuan sasaran keluarga

### ISSUE THREAD

**Issue by Jhiban-Khang** [OpenSID/OpenSID#2880]
Bugs pada kolom identitas Kartu Peserta, seharusnya yang muncul NIK peserta Kepala Keluarga tetapi yang muncul Nomor KK pada kolom identitas di kartu peserta
BANTUAN -> PENGELOLAAN PROGRAM BANTUAN -> SASARAN KELUARGA

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
Apakah yg bapak maksud yg ini???

![Capture](https://user-images.githubusercontent.com/57283157/78463261-ee4fc080-7704-11ea-920c-9665eb704b40.PNG)

Untuk selanjutnya sertakan gambar biar kami tdk menerka2.

**Comment by Jhiban-Khang** [comment]
no.kk dan nik sama,

walau bisa edit manual untuk biar betul, tetapi alangkah efiennya biar
terload otomatis,

**Comment by afa28** [comment]
Untuk saat ini perbaikan hanya saya lakukan pada sasaran KK, jika ingin melakukan perbaikan untuk sasara yg lain silahkan buat issue terpisah.

**Comment by eddieridwan** [comment]
Sudah dicommit ke `master` melalui PR #2887
