### ISSUE TITLE
Sediakan QR Code untuk ttd elektronik kepala desa

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#2882]
### Bagaimana alurnya sampai muncul masalah?
utk antisipasi kalau kantor desa tutup, work for home. bisakah layanan mandiri, permohonan surat warga disematkan tanda tangan kades berupa QR code ?

### Seperti apa yang diharapkan?
Surat yg dihasilkan melalui layanan mandiri tidak perlu diambil secara tatap muka oleh warga, tetapi bisa dikirim secara elektronik. QR Code bersifat sebagai verifikasi surat itu memang asli dikeluarkan oleh kantor desa. 

### Informasi tambahan 

Masukan dari anggota resmi OpenDesa:

Sepengetahuan saya..untuk TTE masih sampai dtingkat kabupaten, itu pun masih dukcapil kabupaten yg memggunakan, dinas2 lain masih manual.

qrcode yg dukcapil kan tidak hanya qrcode biasa. melekat pada jabatan dengan security certificate dari bssn

kalau penyedia ttd digital memang ada. tp saat verifikasi terakhir, harus mendatangi kantor perusahaan tersebut. kebetulan di jakarta.

http://gunungkidul.sorot.co/berita-99226-pertama-di-indonesia-tanda-tangan-digital-bakal-diterapkan-untuk-kades.html

Disinggung mengenai biaya pembuatan tanda tangan digital sendiri, Kelik mengatakan bahwa dalam prosesnya tidak perlu menggunakan biaya. Hal itu dikarenakan untuk tanda tangan digital, pihaknya telah dibantu dari Balai Sertifikat Elektronik Badan Siber dan Sandi Negara (BSSN).

Payung hukum dari pusat sampai desa mesti ada ...

Bagaimana jika opendesa berkoordinasi dg pihak bssn terkait penerapan tte di opensid?kira2 bisa tidak?

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.04
| Versi PHP        | 
| System operasi   |

**Comment by gampongbarabung** [comment]
Setuju Pak

**Comment by sup-ham** [comment]
pakai layanan privy.id pak

**Comment by eddieridwan** [comment]
QR Code sekarang bisa dihasilkan di `master`. Tetapi QRCode ini belum bisa dipakai untuk Tandatangan Digital kecuali PemDes sudah mendapat sertifikasinya dari BSSN dan Kemenkominfo atau pihak swasta yg sudah disertifikasi pemerintah, Jika PemDes ingin memakainya untuk TTD Digital silahkan untuk menghubungi lebih dulu badan/perusahaan untuk dapat sertifikasi dengan kisaran biaya sebesar Rp. 35,000 per 10 dokumen.

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3265
