### ISSUE TITLE
Surat layanan mandiri

### ISSUE THREAD

**Issue by afri18** [OpenSID/OpenSID#2883]
### Bagaimana alurnya sampai muncul masalah?
saat menindak lanjuti permohonan surat tombol eksekusi tidak muncul
![image](https://user-images.githubusercontent.com/6611881/78463604-f27ddd00-7708-11ea-9fe0-24c13ab6914e.png)

### Seperti apa yang diharapkan?
tombol eksekusi harus ada agar bisa di tindak lanjuti

### Apa yang terjadi?
tidak bisa menindak lanjuti permohonan

### Informasi tambahan 
agar lebih memudahkan operator atau admin web
| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.04pasca
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
@afri18 
Jelaskan apakah masalah ini terjadi menggunakan surat bawaan sistem atau ubahan desa. Saat ini penambahan surat layanan mandiri memerlukan penanganan teknis khusus, dan belum disiapkan panduannya secara lengkap. 

Panduan awal ada di https://github.com/OpenSID/OpenSID/wiki/Surat-Layanan-Mandiri, tapi belum lengkap dan terbatas untuk surat bawaan sistem. Untuk surat ubahan, sangat dianjurkan untuk membuat ulang menggunakan template surat bawaan sistem terkini.

**Comment by eddieridwan** [comment]
@afa28 coba periksa apakah masalah ini terjadi di https://demo.opensid.my.id. Kalau iya, lampirkan tampakan layarnya. Kalau di situs demo normal, berarti ada masalah di instalasi anda, yg perlu ditelusuri.

**Comment by afa28** [comment]
> @afa28 coba periksa apakah masalah ini terjadi di https://demo.opensid.my.id. Kalau iya, lampirkan tampakan layarnya. Kalau di situs demo normal, berarti ada masalah di instalasi anda, yg perlu ditelusuri.

Kyaknya slah tag org 😅

**Comment by afa28** [comment]
Sy coba periksa pak 🙏

**Comment by afri18** [comment]
versi 20.04-pasca saya menggunakan surat bawaan, folder surat di folder desa tidak aktif karna diganti namanya
![gambar](https://user-images.githubusercontent.com/6611881/78464447-0975fc80-7714-11ea-8dc0-c378dd72757e.png)

**Comment by afri18** [comment]
di https://demo.opensid.my.id.  saya periksa bisa, kemungkinan ada di web saya, karna tampilan tidak sempuran saat cek layanan mandiri

**Comment by afri18** [comment]
ternyata problem di folder desa>template-surat , punya saya masih menggunakan file lama
terimakasih bung @eddieridwan 
sekarang sudah bisa
