### ISSUE TITLE
Tampilan tabel pd tdk menyesuaikan pd versi mobile

### ISSUE THREAD

**Issue by afa28** [OpenSID/OpenSID#2885]
### Bagaimana alurnya sampai muncul masalah?
Cek modul dokumen_sekretariat pada versi mobil, tampilannya agak ke tengah dan tdk sesuai dgn tampilan pd atasnya.

### Seperti apa yang diharapkan?
Tampilan sesuai dgn modul2 lain untuk kasus yg sama.

### Informasi tambahan 
![2](https://user-images.githubusercontent.com/57283157/78470269-55479680-7752-11ea-9378-11c706f138e2.PNG)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dicommit ke `master` melalui PR #2886
