### ISSUE TITLE
Keyboard Virtual untuk Layanan Mandiri

### ISSUE THREAD

**Issue by mizwaruddin** [OpenSID/OpenSID#2888]
### Bagaimana alurnya sampai muncul masalah?
Kantor desa akan membuat anjungan layanan mandiri dg monitor touchscreen.

### Seperti apa yang diharapkan?
Ditambahkan keyboard virtual untuk mendukung anjungan layanan mandiri.

### Apa yang terjadi?
Saat ini belum tersedia keyboard virtual

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by balongbesuk** [comment]
referensi https://mottie.github.io/Keyboard/

**Comment by mizwaruddin** [comment]
Untuk tampilan masuk/login layanan mandiri keyboard virtual dibuat angka saja krn yg digunakan utk masuk adl NIK dan PIN yg trdiri atas angka semua.

**Comment by mizwaruddin** [comment]
https://github.com/sdeering/onscreenkeyboard

**Comment by eddieridwan** [comment]
Sdh dicommit ke `rilis` premium melalui PR https://github.com/OpenSID/premium/pull/7
