### ISSUE TITLE
statistik wilayah

### ISSUE THREAD

**Issue by afri18** [OpenSID/OpenSID#2889]
### Bagaimana alurnya sampai muncul masalah?
saat dinas terkait butuh data sampai RT sajian statistik di Wilayah Administratif minim sekali, hanya menampilkan Wilayah Dusun dan nama Kepala Dusun tidak imbang dengan ketersediaan halaman yang ada
![image](https://user-images.githubusercontent.com/6611881/78500839-0c5c0600-7783-11ea-89b0-236cc6cb83f0.png)

### Seperti apa yang diharapkan?
Agar bisa menampilkan Wilayah Populasi Perwilayah Mulai dari Dusun > RW > RT
![image](https://user-images.githubusercontent.com/6611881/78500902-6ceb4300-7783-11ea-98eb-09c54db6efdf.png)

### Apa yang terjadi?
Selalu diminta data detai sampai ketingkat RT oleh pihak terkait

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.04-pasca
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
> ### Bagaimana alurnya sampai muncul masalah?
> saat dinas terkait butuh data sampai RT sajian statistik di Wilayah Administratif minim sekali, hanya menampilkan Wilayah Dusun dan nama Kepala Dusun tidak imbang dengan ketersediaan halaman yang ada
> ![image](https://user-images.githubusercontent.com/6611881/78500839-0c5c0600-7783-11ea-89b0-236cc6cb83f0.png)
> 
> ### Seperti apa yang diharapkan?
> Agar bisa menampilkan Wilayah Populasi Perwilayah Mulai dari Dusun > RW > RT
> ![image](https://user-images.githubusercontent.com/6611881/78500902-6ceb4300-7783-11ea-98eb-09c54db6efdf.png)
> 
> ### Apa yang terjadi?
> Selalu diminta data detai sampai ketingkat RT oleh pihak terkait
> 
> ### Informasi tambahan
> Tanya	Jawab
> Versi OpenSID	20.04-pasca
> Versi PHP	
> System operasi

Data detail bisa didapatkan di modul Wilayah Administratif, bisa menggunakan fitur cetak atau download baik itu tingkat dusun, rw dan rt. Adapun data yg ditampilkan di halaman website (data demografi) hanya tingkat dusun saja.

**Comment by afa28** [comment]
Sdah tersedia di fitur premium, http://berputar.opensid.my.id/sid_core

**Comment by eddieridwan** [comment]
Issue ini ditutup.
