### ISSUE TITLE
Eror saat apdate lokasi peta

### ISSUE THREAD

**Issue by M-A-Haris** [OpenSID/OpenSID#2890]
Saat apdate lokasi peta masjid muncul eror kesalahan pada plan_lokasi.php
![Screenshot_2020-04-05-23-14-54-14](https://user-images.githubusercontent.com/46555658/78504145-58b04180-7795-11ea-8970-9a15d762d204.png)

**Comment by afa28** [comment]
Pak @M-A-Haris , apakah sudah update ke pasca per hari ini??? bugs ini sudah diperbaiki melalui PR #2860

**Comment by M-A-Haris** [comment]
belum pak...

**Comment by afa28** [comment]
> belum pak...

silahkan update dlu pak, sudah ada perbaikan. jika masih menemui bug serupa, bisa dibuatkan issuenya

**Comment by afa28** [comment]
Duplicate #2828
