### ISSUE TITLE
Saran Masukan untuk SID

### ISSUE THREAD

**Issue by cnet86** [OpenSID/OpenSID#2891]
<!--Saran saya selaku pengguna OpenSID

Untuk layanan mandiri, di kolom daftar warga dibuat sekalian daftar via online seperti ketika kita sigup ke sosmed,nanti verifikasi pakai KTP dan Nomor HP atau email
Opensid juga sebaiknya dibuat versi androidnya
Kedepan perkembangan opensid bisa mengakamodir tempat pemasaran produk2 unggulan lokal desa, agak bumdes antar desa bisa bersinergi menggunakan SID..expor inpor antar desa diharapkan bisa mengangkat perekonomian desa.

**Comment by cnet86** [comment]
Saran saya selaku pengguna OpenSID

Untuk layanan mandiri, di kolom daftar warga dibuat sekalian daftar via online seperti ketika kita sigup ke sosmed,nanti verifikasi pakai KTP dan Nomor HP atau email
Opensid juga sebaiknya dibuat versi androidnya
Kedepan perkembangan opensid bisa mengakamodir tempat pemasaran produk2 unggulan lokal desa, agak bumdes antar desa bisa bersinergi menggunakan SID..expor inpor antar desa diharapkan bisa mengangkat perekonomian desa..

**Comment by afa28** [comment]
Mohon issuenya dibuat 1 per 1 agar lebih mudah dikerjakan 🙏
