### ISSUE TITLE
Layanan Mandiri untuk Daftar warga sebaiknya dibuat seperti daftar ke sosmed, verifikasi pakai KTP, no HP dan email biar sekalian online semua, yg sekarang masih harus daftar manual ke admin

### ISSUE THREAD

**Issue by cnet86** [OpenSID/OpenSID#2892]
### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by balongbesuk** [comment]
pendekatannya berbeda, kl sosmed mereka tidak punya data warga, beda dengan opensid data warga sudah ada tinggal yang warga mengaktifkan layanan mandiri dengan datang langsung ke desa, karena menyangkut keamanan data penduduk itu sendiri,

**Comment by cnet86** [comment]
Nah justru menurut saya karena kita sudah mempunyai data warga kita gak takut ada robot atau zombi yg akan daftar mandiri apalagi dengan pakai verifikasi KTP dan yg lain..sekali lagi ini hanya pandangan saya dan terimakasih sudah meresponnya dengan baik..saya sangat menghargai diskusi kita ini.dan sy sangat mendukung dan berterimakasih pada para pengembang

**Comment by cnet86** [comment]
Nah justru menurut saya karena kita sudah mempunya data warga kita gak
takut ada robot atau zombi yg akan daftar mandiri apalagi dengan pakai
verifikasi KTP dan yg lain..sekali lagi ini hanya pandangan saya dan
terimakasih sudah meresponnya dengan baik..saya sangat menghargai diskusi
kita ini

Pada tanggal Sen, 6 Apr 2020 12:22, balongbesuk <notifications@github.com>
menulis:

**Comment by afa28** [comment]
Mungkin bisa pakai cara ini
https://m.facebook.com/groups/626787397486245?view=permalink&id=1507397489425227

**Comment by afa28** [comment]
Mungkin widget layanan mandiri pd  tema nataria bisa digunakan.

**Comment by mizwaruddin** [comment]
@afa28 apakah masih akan ditindaklanjuti?

**Comment by afa28** [comment]
Duplicate #3663
