### ISSUE TITLE
[Mobile] Sediakan Layanan Mandiri sebagai aplikasi HP

### ISSUE THREAD

**Issue by cnet86** [OpenSID/OpenSID#2893]
Warga desanya umumnya menggunakan HP dan bukan laptop untuk mengakses layanan daring. Walaupun Layanan Mandiri yg disediakan OpenSID sudah responsif dan cocok untuk diakses melalui smartphone, warga (atau lebih tepatnya pihak2 penggemar IT yg menasehati warga) cenderung memilih menggunakan aplikasi HP untuk mengkases layanan daring daripada menggunakan web browser. 

Yaitu, supaya Layanan Mandiri lebih memasyarakat, diperlukan versi aplikasi HP.

Secara teknis, perlu dikembangkan dua kompenen:
(1) API yg menyediakan cara untuk aplikasi HP bisa mengakses data dan fitur Layanan Mandiri
(2) Aplikasi HP yg menyediakan fitur2 Layanan Mandiri menggunakan API (1).

Perhatikan bahwa issue ini membatasi aplikasi HP hanya pada Layanan Mandiri, dan bukan sebagai portal ke keseluruhan fitur OpenSID web, apalagi OpenSID admin. Memasukkan semua fitur ke aplikasi HP akan menghasilkan aplikasi yg rumit dan menduplikasi apa yg ada di versi web tanpa nilai tambah yg berarti.

Di antara sekian banyak pilihan teknis yg tersedia, saat ini teknologi yg dipilih adalah sebagai berikut:
(1) Menggunakan Laravel untuk API Layanan Mandiri; supaya konsisten dengan OpenDK dan arah pengembangan OpenSID ke depan; menggunakan teknologi yg sudah dikenal oleh programmer/kontributor OpenDesa dan yg cukup ramah dalam pembuatan API
(2) Menggunakan `flutter` sebagai basis pengembangan aplikasi Layanan Mandiri untuk HP. `flutter` telah muncul sebagai teknologi yg populer untuk pengembangan aplikasi HP; dan memungkinkan dibuatnya versi untuk tidak saja Android, tetapi juga untuk iOS dan O/S HP lainnya.

**Comment by eddieridwan** [comment]
Penerapan issue ini telah dimulai, di repo berikut:
(1) https://github.com/OpenSID/opensid-api untuk pengembangan API Layanan Mandiri menggunakan Laravel
(2) https://github.com/OpenSID/mobile untuk pengembangan aplikasi Layanan Mandiri HP menggunakan flutter.

Fitur ini dapat diprioritaskan jika ada desa yg bersedia menyediakan dana tambahan di luar langganan Premium, dengan pertimbangan fitur ini akan memerlukan beberapa programmer selama beberapa bulan.

Jika dana dari desa mencukupi, fitur ini dapat ditawarkan kepada programmer berbayar yg kompeten melakukan.

**Comment by eddieridwan** [comment]
@apidong Juga mohon pikirkan bagaimana caranya supaya hanya ada satu aplikasi yg nanti dipasang di PlayStore (atau penggantinya). Dan setelah memasang di HP, pengguna bisa melakukan setting supaya mengarah ke desa dia.

**Comment by apidong** [comment]
agar bisa 1 apk  untuk semua desa. solusi dari saya, 
dari sisi user :
- saat pertama kali install aplikasi. user harus melakukan pengaturan aplikasi nya untuk desa mana.
- setelah selesai, user bisa login menggunakan user sesuai desa yang dipilih saat pengaturan.

untuk kebutuhan teknis:
- list data berbentuk json yang berisi nama desa beserta alamat API OPENSID. Bisa berbentuk file atau API. kalau file nanti repot kalau ada tambahan desa harus build lagi.

alur teknisnya ;
1. Aplikasi mulai
2. Aplikasi mengecek apakah ada data alamat API di dalam storage di dalam device.
3. - jika tidak ada Aplikasi akan menampilkan halaman pengaturan untuk memilih desanya. setelah memilih, Alamat API akan di periksa apakah alamat API bisa diakses atau tidak. jika tidak akan kembali ke pengaturan awal dan menampilkan **peringatan bahwa opensid mobile belum tersedia di desa yang dipilih.**
   - jika sudah ada, alamat API akan di periksa apakah alamat API bisa diakses atau tidak. jika tidak akan kembali ke pengaturan awal.
 4. User login dengan NIK dan PIN yang sudah dibuat melalui aplikasi OPENSID.
![image](https://user-images.githubusercontent.com/20056421/124875283-ea3edc80-dff2-11eb-81d5-e84c1804c90d.png)

**Comment by agungsugiarto** [comment]
Pak @eddieridwan, apakah ini hanya ditujukan untuk pelanggan premium? Mungkin apinya bisa diambil dari layanan opendesa, tapi di layanan perlu disediakan domain tambahan untuk url apinya.

**Comment by eddieridwan** [comment]
Betul, aplikasi mobile nanti hanya berlaku bagi pelanggan premium. Sepertinya API perlu tetap di OpenSID, karena semua data/fitur Layanan Mandiri ada di situ. Mungkin cukup sebagai bagian dari otentikasi API yg disediakan OpenSID, OpenSID juga memeriksa apakah langganan premium bagi desa ybs masih berlaku. Jadi buatkan pemeriksaan itu sebagai bagian dari API mobile OpenSID.

**Comment by afa28** [comment]
> Betul, aplikasi mobile nanti hanya berlaku bagi pelanggan premium. Sepertinya API perlu tetap di OpenSID, karena semua data/fitur Layanan Mandiri ada di situ. Mungkin cukup sebagai bagian dari otentikasi API yg disediakan OpenSID, OpenSID juga memeriksa apakah langganan premium bagi desa ybs masih berlaku. Jadi buatkan pemeriksaan itu sebagai bagian dari API mobile OpenSID.

sy kira, mungkin begini : 
1. API dari layanan untuk mengecek list desa dan mendapatkan API masing2 desa, dalam artian jika desa berlangganan aplikasi mobile, desa wajib jg mendaftarkan akses api desanya ke layanan. (Hanya saat instalasi awal sj)
2. API desa yg didpt dri layanan untuk akses layanan mandiri.

Jadi ada 2 API.

**Comment by agungsugiarto** [comment]
Konsepnya
1. api opensid akan mengakses layanan untuk mendapatka list desa, (bertujuan untuk mobile biar satu arah).
2. sediakan midleware di api opensid request ke layanan apakah request dari pengguna mobile tersebut dari desa tersebut masih berlangganan.

Flownya mobile -> api opensid -> api layanan

**Comment by agungsugiarto** [comment]
Untuk mas @apidong, sekilas saja OpenDesa sekarang mencatat pelanggan desa di aplikasi Layanan OpenDesa.

**Comment by apidong** [comment]
> Untuk mas @apidong, sekilas saja OpenDesa sekarang mencatat pelanggan desa di aplikasi Layanan OpenDesa.

Mantap

**Comment by eddieridwan** [comment]
> sy kira, mungkin begini :
> 
> 1. API dari layanan untuk mengecek list desa dan mendapatkan API masing2 desa, dalam artian jika desa berlangganan aplikasi mobile, desa wajib jg mendaftarkan akses api desanya ke layanan. (Hanya saat instalasi awal sj)
> 2. API desa yg didpt dri layanan untuk akses layanan mandiri.
> 
> Jadi ada 2 API.

Setuju. Dan desa yg boleh mendaftarkan aplikasi mobile dibatasi yg berlangganan premium. Dan API yg pertama hanya menampilkan desa yg langganannya masih aktif.

**Comment by roaddee** [comment]
oke. mantap
