### ISSUE TITLE
OpenSID kedepan tambahin menu tempat pemasaran produk2 unggulan lokal di desa, harapan expor inpor antar desa bisa mengangkat perekonomin desa, sehingga Bumdes bisa memaksimalkan juga penggunanan SID

### ISSUE THREAD

**Issue by cnet86** [OpenSID/OpenSID#2894]
### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
Modul yg menarik untuk ditambahkan di OpenSID, tp mohon diperjelas lg issuenya.

**Comment by afa28** [comment]
Silahkan buat issue sesuai format yg diberikan.
