### ISSUE TITLE
Medsos

### ISSUE THREAD

**Issue by afri18** [OpenSID/OpenSID#2895]
### Bagaimana alurnya sampai muncul masalah?
Ganjil aja, masa medsos Telegram nggak ada , padahal group opensid ada telegram nya

### Seperti apa yang diharapkan?
Tambahin Medsos di menu Widget > Media Sosial

### Apa yang terjadi?
Biar kompliit

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.04pasca
| Versi PHP        | 
| System operasi   |

**Comment by Nurhidayat29** [comment]
bung @afri18 pembuat issue senior

**Comment by afa28** [comment]
Modul media sosial dr pandangan sy untuk saat ini bentuknya statis. Hanya disediakan beberapa media sosial sj, user tdk bisa menambahkan atau menghapus media sosial yg disediakan.

**Comment by afri18** [comment]
Ya di usul, kalau mennon aktifkan bisa, nambah juga bisa, hanya saat update yg ditambahin pasti hilang, edit lagi, nah maunya permanen, kalau nggak suka tinggal non aktifkan, bereees ....

**Comment by eddieridwan** [comment]
Bung @afa28 , maksud bung @afri18 , tambahkan opsi Telegram di Admin Web > Media Sosial:
<img width="1394" alt="medsos" src="https://user-images.githubusercontent.com/249563/78620161-9494f500-78c2-11ea-84eb-80ced9fe65a7.png">

Bung @afri18 , mohon biasakan memberi penjelasan lengkap pada issue dengan tangkapan layar menu ybs, supaya programmer tidak bingung dan salah tangkap.

**Comment by afa28** [comment]
> Bung @afa28 , maksud bung @afri18 , tambahkan opsi Telegram di Admin Web > Media Sosial:
> <img alt="medsos" width="1394" src="https://user-images.githubusercontent.com/249563/78620161-9494f500-78c2-11ea-84eb-80ced9fe65a7.png">
> 
> Bung @afri18 , mohon biasakan memberi penjelasan lengkap pada issue dengan tangkapan layar menu ybs, supaya programmer tidak bingung dan salah tangkap.

Sy mengerti pak, sy cuma memberi pilihan lain agar nantinya tdk ad issue lain untuk menambahkan sosial media lain. Agar lebih dinamas 😅

**Comment by afri18** [comment]
Bagus juga kalau di buat dinamis

**Comment by eddieridwan** [comment]
Sudah dicommit melalui PR #2932
