### ISSUE TITLE
NIK, KK dan ALAMAT hilang saat ubah Sasaran Program pada Program Bantuan

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#2897]
### Bagaimana alurnya sampai muncul masalah?
Tampilan di Halaman Admin saat Sasaran Program Penduduk Perorangan:
![image](https://user-images.githubusercontent.com/46939846/78642396-dd59a780-78dc-11ea-8bb6-e00c81d2f288.png)

Namun saat Program di edit menjadi Sasaran Program Kepala Keluarga:
![image](https://user-images.githubusercontent.com/46939846/78642468-fc583980-78dc-11ea-9a79-d24168f47dfc.png)

Halaman tidak menampilkan No KK dan NIK serta ALAMAT.
![image](https://user-images.githubusercontent.com/46939846/78642909-a5069900-78dd-11ea-934a-a42bffcf4dad.png)

### Seperti apa yang diharapkan?
Nomor KK dan NIK tetap ditampilkan untuk memudahkan pencarian data, karena hasil download saat Sasaran Program Perorangan, kolom di excel tidak menampilkan KK.

### Apa yang terjadi?
Dapat menampilkan KK pada halaman admin dan hasil downloadnya.

### Informasi tambahan 
Tambahkan Kolom Pekerjaan pada Hasil Download Excel agar dapat diketahui Pekerjaannya.

**Comment by afa28** [comment]
Mungkin ini masih ada efek yg dari perubahan kemarin pada sasaran KK

**Comment by afa28** [comment]
Mungkin sebaiknya yg diperbaiki itu jika data program bantuan minimal 1, data sasaran terlock(tdk bisa diubah). Ini krn pengambilan data dari masing2 sasaran berbeda. Mungkin pak @eddieridwan bisa memberi solusi yg lain.

**Comment by eddieridwan** [comment]
Setuju dengan analisis @afa28 . Peserta pada program dengan sasaran berbeda tidak bisa dikonversi. Program sasaran penduduk, pesertanya penduduk. Program dengan sasaran keluarga, pesertanya keluarga. Peserta penduduk tidak selalu bisa dikonversi menjadi keluarga atau menjadi rumah tangga atau kelompok.

Jadi solusi untuk issue ini adalah dengan tidak menyediakan fitur untuk mengubah jenis sasaran suatu program kalau sudah ada peserta.

**Comment by ariandii** [comment]
saat ini Dinas Sosial meminta Data BNBA per KK dan Jumlah Anggota dalam KK.

apa yang bisa diolah menggunakan database yg tersedia di OpenSID?

Dinas Sosial meminta pendataan untuk antisipasi bencana covid19.

mereka meminta data tersebut diatas terkait Nama, NIK, No KK, Jumlah anggota dalam keluarga, dan Pekerjaan.

**Comment by ariandii** [comment]
apakah buat kolom manual yg diperlukan di excel dengan mencari data di OpenSID kemudian copy paste 1 per 1?

itu memerlukan Long Time untuk saat ini.

**Comment by eddieridwan** [comment]
> saat ini Dinas Sosial meminta Data BNBA per KK dan Jumlah Anggota dalam KK.
> 
> apa yang bisa diolah menggunakan database yg tersedia di OpenSID?
> 
> Dinas Sosial meminta pendataan untuk antisipasi bencana covid19.
> 
> mereka meminta data tersebut diatas terkait Nama, NIK, No KK, Jumlah anggota dalam keluarga, dan Pekerjaan.

@ariandii buat issue terpisah untuk sesuatu spesfik seperti permintaan ini. Lampirkan contoh laporan yg diperlukan.

**Comment by eddieridwan** [comment]
Sudah dicommit ke `master`: Sekarang program bantuan yang sudah ada peserta tidak bisa diubah sasarannya.

Permintaan lainnya mohon dibuatkan issue terpisah.
