### ISSUE TITLE
Kotak cari program bantuan belum ada autocomplete

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#2898]
### Bagaimana alurnya sampai muncul masalah?
Buka halaman rincian program bantuan yg berisi beberapa peserta. Isi teks di kotak cari.

### Seperti apa yang diharapkan?
Ditampilkan daftar nama atau id peserta yg berisi teks yg diisi di kotak cari. Fitur ini untuk memudahkan pengguna mencari peserta yg diinginkan.

### Apa yang terjadi?
Belum ada fitur autocomplete untuk kotak cari.
<img width="1394" alt="cari-program-bantuan" src="https://user-images.githubusercontent.com/249563/78664070-a1433880-7916-11ea-8515-c6515e4111ae.png">

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.04-pasca
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
> ### Bagaimana alurnya sampai muncul masalah?
> Buka halaman rincian program bantuan yg berisi beberapa peserta. Isi teks di kotak cari.
> 
> ### Seperti apa yang diharapkan?
> Ditampilkan daftar nama atau id peserta yg berisi teks yg diisi di kotak cari. Fitur ini untuk memudahkan pengguna mencari peserta yg diinginkan.
> 
> ### Apa yang terjadi?
> Belum ada fitur autocomplete untuk kotak cari.
> <img alt="cari-program-bantuan" width="1394" src="https://user-images.githubusercontent.com/249563/78664070-a1433880-7916-11ea-8515-c6515e4111ae.png">
> 
> ### Informasi tambahan
> Tanya	Jawab
> Versi OpenSID	20.04-pasca
> Versi PHP	
> System operasi

Nilai apa yg dicari pak @eddieridwan ??? NIK, KK, atau Nama Peserta??? Atau NIK, Nama yg ada di identitas Peserta??

**Comment by eddieridwan** [comment]
Tergantung sasaran:
1. Penduduk: nama, NIK
2. Keluarga: No_KK, nama KK, NIK KK
3. Rumah tangga: kode kelompok, nama ketua, NIK ketua
4. Kelompok: nama kelompok, nama ketua, NIK ketua

**Comment by eddieridwan** [comment]
Sediakan autocomplete menggunakan daftar nama di kolom `kartu_nama` melalui PR #3128. Pilihan kolom lain yg juga dapat dicari belum disediakan. Jadi issue ini belum ditutup -- untuk nanti ditinjau ulang.

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3199
