### ISSUE TITLE
Pembuatan PIN tertimpa krn tdk ada filter

### ISSUE THREAD

**Issue by afa28** [OpenSID/OpenSID#2901]
### Bagaimana alurnya sampai muncul masalah?
Warga yg sudah dibuatkan pin masih bisa dibuatkan lg, sehingga pin sebelumnya tertindih/terganti.

### Seperti apa yang diharapkan?
Jika warga sudah membuat PIN, seharusnya sudah tdk muncul lg di pencarian. Jika ada kasus lupa PIN, mungkin bisa hapus pin warga yg sudah dibuat dan kemudian buat pin baru lg.

### Apa yang terjadi?
PIN yg pernah dibuat bisa terganti.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
@afa28 apakah issue ini diminta oleh pengguna? 
Sebenarnya pembuatan ulang ini satu cara yg digunakan utk mengubah PIN. Kalau fitur ini diterapkan, juga diperlukan tombol aksi untuk membuat PIN baru.

**Comment by afa28** [comment]
> @afa28 apakah issue ini diminta oleh pengguna?
> Sebenarnya pembuatan ulang ini satu cara yg digunakan utk mengubah PIN. Kalau fitur ini diterapkan, juga diperlukan tombol aksi untuk membuat PIN baru.

Ini issue yg sy buat untuk menghidari kesalahan pengguna saat membuat PIN. Jika ingin membuat PIN baru, tinggal menghapus data warga yg sudah terdafatar dan lakukan pembuatan PIN baru.

**Comment by eddieridwan** [comment]
Akan lebih jelas kalau ada aksi khusus untuk buat PIN baru.

**Comment by afa28** [comment]
> Akan lebih jelas kalau ada aksi khusus untuk buat PIN baru.

Siap pak

**Comment by eddieridwan** [comment]
Sudah dicommit ke `master` melalui PR #2902
