### ISSUE TITLE
[Bug] Komentar Artikel tidak Muncul

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#2906]
### Bagaimana alurnya sampai muncul masalah?
Saat ini jika ada komentar pada artikel dan setelah disetujui, komentar tersebut tidak muncul di halaman artikel.

Tampilan halaman admin, komentar sudah disetujui.
![image](https://user-images.githubusercontent.com/46939846/78701186-c6dd3b80-7930-11ea-875c-beda451ebf6b.png)

Tampilan pada halaman website komentar kosong:
![image](https://user-images.githubusercontent.com/46939846/78701224-dc526580-7930-11ea-85c3-cf7d39dcf6fa.png)

### Seperti apa yang diharapkan?
Muncul komentar sesuai dengan seharusnya.

**Comment by afa28** [comment]
> ### Bagaimana alurnya sampai muncul masalah?
> Saat ini jika ada komentar pada artikel dan setelah disetujui, komentar tersebut tidak muncul di halaman artikel.
> 
> Tampilan halaman admin, komentar sudah disetujui.
> ![image](https://user-images.githubusercontent.com/46939846/78701186-c6dd3b80-7930-11ea-875c-beda451ebf6b.png)
> 
> Tampilan pada halaman website komentar kosong:
> ![image](https://user-images.githubusercontent.com/46939846/78701224-dc526580-7930-11ea-85c3-cf7d39dcf6fa.png)
> 
> ### Seperti apa yang diharapkan?
> Muncul komentar sesuai dengan seharusnya.

Sudah sy perbaiki, dan beberapa tambahan lainnya pd modul ini seperti balas komentar. Namu pak eddi blum merge karena tabel komentar harus dipisahkan dlu isisnya dengan mail_box krn pada tabel komentar ada sedikit perubahan.

**Comment by afa28** [comment]
Contoh gambarnya bisa dilihat di https://github.com/OpenSID/OpenSID/pull/2868

**Comment by eddieridwan** [comment]
Sudah dicommit ke `master`
