### ISSUE TITLE
Error kirim pesan banyak

### ISSUE THREAD

**Issue by afa28** [OpenSID/OpenSID#2908]
### Bagaimana alurnya sampai muncul masalah?
Buka SMS>SMS>Tulis Pesan Banyak. Jgn isi salah satu filter, maka saat kirim pesan akan ada error.
![11222](https://user-images.githubusercontent.com/57283157/78743312-772a5e80-7988-11ea-9e00-baf0a1626bd3.PNG)

### Seperti apa yang diharapkan?
Tdk ada error kirim pesan banyak.

### Apa yang terjadi?
Bisa kirim pesan banyak

### Informasi tambahan 
![cobaaja](https://user-images.githubusercontent.com/57283157/78743487-f28c1000-7988-11ea-817d-88ca844cc141.PNG)

Sebaiknya filter untuk pesan banyak disederhanakan, filter berdasarkan sesuai data yg ada di daftar kontak bukan data penduduk. 
Filter:
- Jenis kelamin
-  Group kontak

2 di atas kyaknya sudah cukup.

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dicommit ke `master` melalui PR #3258

**Comment by eddieridwan** [comment]
Perubahan lain sebaiknya menunggu permintaan dari pengguna. Saat ini tidak terlihat adanya banyak pengguna. Jadi modul SMS ini bukan prioritas.
