### ISSUE TITLE
Data warga di modul tertentu duplicate 

### ISSUE THREAD

**Issue by afa28** [OpenSID/OpenSID#2909]
### Bagaimana alurnya sampai muncul masalah?
Beberapa modul yg menggunakan data penduduk menggunakan data semua penduduk dan tidak ada filter. Sehingga menyebabkan ada duplicate data yg terpilih. 
Contoh:
- Pemilihan kepala dusun, rw dan rt (fix)
- Pemerintah desa (fix)
- Pendaftar Layanan Mandiri(fix)

### Seperti apa yang diharapkan?
Tidak adanya data duplicate, jgn masukkan pd pilihan jika datanya sudah ada.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` untuk Pemerintahan Desa.
