### ISSUE TITLE
Config lang tdk jalan sebagaimana mestinya

### ISSUE THREAD

**Issue by afa28** [OpenSID/OpenSID#2912]
### Bagaimana alurnya sampai muncul masalah?
Contoh, buka form login dan klik masuk. Maka akan muncul notifikasi, namu masih bahasa inggris.
![cobaaja](https://user-images.githubusercontent.com/57283157/78750694-f6289280-799a-11ea-9719-1fe4b1174c6a.PNG)

### Seperti apa yang diharapkan?
Config lang jalan sebagaimana mestinya

### Apa yang terjadi?
Informasi berupa bahas indonesia pd informasi input

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by dikisiswanto** [comment]
Sebenarnya itu bawaan dari browser jika input-nya bersifat required.
