### ISSUE TITLE
Bagaimana cara nambah peserta penerima bantuan? tombol tidak ada.

### ISSUE THREAD

**Issue by asalreview** [OpenSID/OpenSID#2913]
### Bagaimana alurnya sampai muncul masalah?
Tidak tersedianya tombol tambah peserta penerima bantuan.
![image](https://user-images.githubusercontent.com/60563749/78785740-dd879f00-79d1-11ea-9d43-65f473e9f856.png)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
Cek tanggal aktif

**Comment by mering22** [comment]
Mohon b

> Cek tanggal aktif

Di menu apa dan caranya??? trima kasih

**Comment by mering22** [comment]
> Cek tanggal aktif

Mantap Terima Kasih Pak..
