### ISSUE TITLE
Rincian Data Peserta Program Tidak Tampil Ketika Klik Ubah

### ISSUE THREAD

**Issue by asalreview** [OpenSID/OpenSID#2914]
### Bagaimana alurnya sampai muncul masalah?
![image](https://user-images.githubusercontent.com/60563749/78787382-791a0f00-79d4-11ea-9899-0bfdf7d744d9.png)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
Itu krn sebelumnya data yg di input tdk lengkap, coba cek tabel

**Comment by asalreview** [comment]
@afa28 cba bpak tes dan bapak upload gmbrnya.
