### ISSUE TITLE
Bilangan puluhan dengan akhiran 0 ikut disembunyikan

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#2915]
### Bagaimana alurnya sampai muncul masalah?
Buka website demo > data desa > data agama

### Seperti apa yang diharapkan?
Pada data agama islam berjumlah 90 ikut disembunyikan seharusnya tidak

### Apa yang terjadi?
Bilangan puluhan dengan akhiran 0 ikut disembunyikan

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Solusi sudah dicommit ke `master`
