### ISSUE TITLE
dokumen kartu keluarga

### ISSUE THREAD

**Issue by afri18** [OpenSID/OpenSID#2916]
### Bagaimana alurnya sampai muncul masalah?
terjadi upload dokumen yang sama berulangkali

### Seperti apa yang diharapkan?
Sebaiknya dokumen yang sama seperti Kartu Keluarga langsung terupload atau linknya ikut juga ke ANGGOTA KELUARGA
![image](https://user-images.githubusercontent.com/6611881/78951990-3f452780-7afe-11ea-8a9b-9f0cd1f7d2fc.png)

### Apa yang terjadi?
penumpukan dokumen yang sama di Cpanel

### Informasi tambahan 
untuk menghindari kerja berulang dengan jenis yang sama

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.04-pasca
| Versi PHP        | 
| System operasi   |

**Comment by af-lazuardi** [comment]
![upload_kk](https://user-images.githubusercontent.com/13193883/78999830-a225d580-7b75-11ea-8eb9-2f0feaf32a01.png)

Apakah seperti ini yang diharapkan? Jadi jika penduduk merupakan Kepala Keluarga, saat upload dokumen juga terdisplay nama anggota nya. Dan jika dokumen upload dimaksudkan untuk seluruh anggota keluarga. Maka user mengisi centang anggota di bawahnya. Sehingga data dokumen yang diupload juga masuk ke daftar dokumen masing2 anggota keluarga

**Comment by af-lazuardi** [comment]
Sudah saya kerjaka dan pull request di #2919

Flow Perbaikan yang baru

![upload_kk](https://user-images.githubusercontent.com/13193883/79017585-ecba4880-7b9b-11ea-88ac-65bef0f648d9.png)
_1. Kepala Keluarga upload document dan memilih anggota keluarga yang hendak direlasikan dengan dokumen tersebut_

![update_di_kepala](https://user-images.githubusercontent.com/13193883/79017637-09568080-7b9c-11ea-9efd-ae435d9f64ba.png)
_2. Akses 'Edit' dan 'Delete' hanya tersedia di halaman dokumen Kepala Keluarga. Dan centang anggota otomatis terpilih dan disabled (Edit dan Delete harus berlaku ke semua anggota)_

![kk_di_anggota](https://user-images.githubusercontent.com/13193883/79017686-23905e80-7b9c-11ea-9d6c-d8f973af5bd9.png)
_3. Akses 'Edit' dan 'Delete' Tidak tersedia di anggota_

**Comment by afri18** [comment]
Betul sekali , apa sudah tersedia di pasca ??? Kalau sudah mau saya coba langsung ...

**Comment by af-lazuardi** [comment]
Masih proses review PR pak @afri18 . Anda bisa juga mengikuti thread review PR tersebut di sini #2919 (klik nomor thread di samping)

**Comment by afri18** [comment]
Nggak paham, nunggu Mateng aja ah

**Comment by eddieridwan** [comment]
Sudah dicommit ke `master` melalui PR #2919
