### ISSUE TITLE
Memunculkan bagian atas menu layanan mandiri pada tampilan mobile

### ISSUE THREAD

**Issue by fittobole** [OpenSID/OpenSID#2920]
### Bagaimana alurnya sampai muncul masalah?
Saat penduduk login, harus melakukan scroll ke bawah, untuk mencari menu login layanan mandiri

### Seperti apa yang diharapkan?
Agar orang (masyarakat) yang mengakses layanan mandiri, tidak perlu scroll lagi ke bagian bawah.

### Apa yang terjadi?
Untuk memudahkan masyarakat

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.04
| Versi PHP        | 
| System operasi   |

**Comment by ariandii** [comment]
kembar

https://github.com/OpenSID/OpenSID/issues/2872

**Comment by fittobole** [comment]
Udah ada yaa?
