### ISSUE TITLE
Halaman Inventaris tidak tampil sempurna

### ISSUE THREAD

**Issue by asalreview** [OpenSID/OpenSID#2922]
### Bagaimana alurnya sampai muncul masalah?
Sudah 3 kali saya coba clone repository, setelah migrasi halaman inventaris tidak tampil sempurna.
![image](https://user-images.githubusercontent.com/60563749/79045047-4457c300-7c33-11ea-9c85-90700f2c8227.png)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.04-pascal
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
Di website demo aman, coba hapus cache dlu.
Dan usahakan yg ambil patokan pd website demo, krn apa yg ada di brach master itu jg yg ada di website demo.

**Comment by asalreview** [comment]
@afa28 tetap tidak bisa, yang saya jalankan juga hasil clone repository langsung ke github opensid, jadi jika ada update otomatis terupdate dan ini menjadi sampel juga buat saya pelajari tanpa saya ubah.
![image](https://user-images.githubusercontent.com/60563749/79138231-65104c00-7dde-11ea-997d-80ba50c52b7e.png)

**Comment by eddieridwan** [comment]
Sudah dicommit ke `master` melalui PR #2931
