### ISSUE TITLE
Tambah Data pada Menu COVID-19

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#2923]
### Seperti apa yang diharapkan?
perlu kolom perkembangan hasil kontrol, seperti ini sedikit nya data yang diperlukan.
![IMG20200406140518](https://user-images.githubusercontent.com/46939846/79057857-33896a80-7c90-11ea-828e-c463454e6d52.jpg)

selain itu, saat ini sudah jalan sekian data berupa excel. dapat diberikan opsi untuk import excel ke menu covid-19 di opensid.

### Apa yang terjadi?
Dapat menyajikan data mendekati akurat.
tidak hanya data mentah.

**Comment by af-lazuardi** [comment]
Baik Pak. Bisa diberikan contoh juga file excelnya.

**Comment by ariandii** [comment]
berikut contoh sheet 1 untuk data update per hari di lapangan.

untuk sheet 2 perkembngan seperti tabel di atas per 4 hari selema 14 hari.

![IMG_20200412_093441](https://user-images.githubusercontent.com/46939846/79059133-df3ab680-7ca0-11ea-80db-92ebf66dc644.jpg)

**Comment by af-lazuardi** [comment]
Okey, noted.

**Comment by ahmadngudi** [comment]
bisa di tambah data di widget tidak pak?
contoh data statistik OPD, PDP, Positive dll.

**Comment by eddieridwan** [comment]
Sudah dicommit ke `master` melalui PR #2934
