### ISSUE TITLE
Tambahkan Data Statistik untuk Data Siaga Covid-19 Pada Website

### ISSUE THREAD

**Issue by HerryWanda** [OpenSID/OpenSID#2924]
### Bagaimana alurnya sampai muncul masalah?
Untuk melihat data Siaga Covid-19, tambahkan statistik status Pemudik pada halaman web, sesuai status covid-19 yang di input.

### Seperti apa yang diharapkan?
Adanya satatitik data siaga covid tampil di Website desa

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by ariandii** [comment]
statistik data apa yg ditampilkan?

**Comment by HerryWanda** [comment]
sesuai data status covid-19 yang di input pak..
![st](https://user-images.githubusercontent.com/32125282/79207070-69824680-7e6a-11ea-8d04-0c0f93273e4d.jpg)

**Comment by kurniyawan004** [comment]
sepakat.....statistik dan data siaga covid tampil di web desa

**Comment by ahmadngudi** [comment]
setuju, ada siaga covid tampil di web desa

**Comment by af-lazuardi** [comment]
okay, saya coba kerjakan ya. Itu berarti harus ada tambahan field 'Sembuh' ya? dan dapat di trace semua tiap perubahan status dari warga pemudik? Ada tambahan lagi gak status covid-19 selain yang sudah ada field status covid sekarang di Admin OpenSID?

**Comment by eddieridwan** [comment]
Sudah dicommit ke `master` melalui PR #2959
