### ISSUE TITLE
Menu Struktur Organisasi Kelembagaan Desa: RT/RW, LPMD, BPD, PKK, dan Organisasi Lainnya

### ISSUE THREAD

**Issue by hirudi** [OpenSID/OpenSID#2926]
### Seperti apa yang diharapkan?
Contoh: Seperti Struktur Pemerintah Desa ini.
![Untitled](https://user-images.githubusercontent.com/4936934/79064455-60ab3c80-7cd3-11ea-9846-1cfd17e4c09a.png)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by pemdesbatajawa** [comment]
Sepakat Om, kalau bisa ditambahkan dengan menu untuk struktur Kelembagaan dan struktur Organisasi BUMDesa

**Comment by bagusjimi** [comment]
ya bagus pa

**Comment by mizwaruddin** [comment]
@afa28 Ini bisa dibuat melalui artikel statis. Tinggal menambahkan menu dan sub menu sesuai kebutuhan.

**Comment by afa28** [comment]
> @afa28 Ini bisa dibuat melalui artikel statis. Tinggal menambahkan menu dan sub menu sesuai kebutuhan.

Ya, bisa juga ditambahkan melalu menu kelompok.
