### ISSUE TITLE
Re-design layanan mandiri

### ISSUE THREAD

**Issue by afa28** [OpenSID/OpenSID#2930]
### Bagaimana alurnya sampai muncul masalah?
Saat ini view layanan mandiri melekat pada sytem opensid, sehingga untuk mengubah tampilan layanan mandiri harus mengedit system yg ada di opensid. Sehingga ketika terjadi update/relase versi terbaru, ubahan yg pengguna buat akan terhapus.

### Seperti apa yang diharapkan?
View layanan mandiri dipisahkan dari sytem opensid atau membuatkan alur view ke folder desa layaknya themes.

### Apa yang terjadi?
Masing2 user dapat mengubah dan berkreasi sendiri mengenai tampilan/view layanan mandiri mereka.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Saya kira lebih baik kalau kita perbaiki tampilan Layanan Mandiri dulu, supaya lebih mudah dan enak digunakan. Fitur layanan mandiri masih belum stabil dan saya duga akan banyak berubah. Terlalu dini dan menghabiskan banyak waktu untuk menyediakan titik ubahan desa. Itupun nanti lebih baik melalui penyediakan API daripada cara yg digunakan sekarang untuk tema. 

Kalau ada yg punya usul perbaikan, lebih baik tuangkan dulu ke dalam rilis OpenSID sendiri.

**Comment by afa28** [comment]
Baik, sy siap bantu pak
