### ISSUE TITLE
Tidak dapat menggunakan tanda strip/kurang (-) pada penulisan kata dalam kolom Nama Dokumen

### ISSUE THREAD

**Issue by Gunturwijay** [OpenSID/OpenSID#2937]
Penulisan kalimat pada nama dokumen ketika diketik menggunakan tanda kurang (-)
![image](https://user-images.githubusercontent.com/40741591/79434641-df1c1d00-7ff8-11ea-9407-5615fcf860ac.png)
-->

Kesalahan yang terjadi

![image](https://user-images.githubusercontent.com/40741591/79434688-ee9b6600-7ff8-11ea-9527-22375dd7bc20.png)

-->

### Seperti apa yang diharapkan?
Penulisan kata menggunakan tanda strip/kurang seperti contoh : **Ibu-Ibu** dapat muncul dengan sempurna. yaitu **Ibu-Ibu**

### Apa yang terjadi?
Tanda strip/kurang tidak dapat muncul pada Kalimat yang dibuat

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Saya kira tidak bermasalah apabila nama dokumen diperbolehkan berisi tanda strip/kurang. Jadi nama dokumen boleh berisi alfanumerik+spasi+tanda-strip. Untuk solusinya mungkin buat helper tambahan untuk membersihkan nama dokumen. Sekalian tambahkan validasi di form isiannya, Lihat validasi.js untuk validator custom untuk validasi form (digunakan sebagai class untuk elemen input di form).

**Comment by masumo** [comment]
saya lihat di validasi.js sudah ada yang buat validasi untuk field nama. tetapi sepertinya tidak berfungsi. akan saya coba untuk dalami lagi.

**Comment by eddieridwan** [comment]
@masumo , kalau nama dokumen boleh mengikuti nomor SK, mungkin yg lebih cocok adalah `nomor_surat_keputusan()` di `donjo-app/helpers/opensid_helper.php`. Tapi harap periksa nama file yg dihasilkan tetap valid.

**Comment by masumo** [comment]
oke pak @eddieridwan

**Comment by eddieridwan** [comment]
Sudah dicommit ke `master` melalui Pr #3134
