### ISSUE TITLE
Input alamat penduduk

### ISSUE THREAD

**Issue by afa28** [OpenSID/OpenSID#2939]
### Bagaimana alurnya sampai muncul masalah?
Coba buat/edit data penduduk, isi alamat dan kemudian simpan. Cek database pd tweb_penduduk, alamat yg dinput tdk tersipan pd alamat sekrang, malah tersimpan pd tabel tweb_keluarga (alamat). 

Atau apakah memang alamat tersimpan di tweb_keluarga??? Kalau itu terjadi maka untuk modul keluarga data alamat tersimpan dimana??? Apakah saling menimpa???

### Seperti apa yang diharapkan?
Alurnya diperjelas. Data individu, Keluarga, dll tempat simpan datanya.

### Apa yang terjadi?
Tdk terjadi data yg saling timpa menimpa.

### Informasi tambahan 
Pada form tambah/edit penduduk, alamat yg ditampilkan adalah alamat dari tweb_keluarga.

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Alamat penduduk yg merupakan bagian dari keluarga, yaitu yg ada `id_kk` adalah alamat keluarga. Alamat keluarga disimpan di `tweb_keluarga`. Alamat penduduk yg bukan bagian dari keluarga, yaitu yg tidak ada `id_kk` disimpan di `tweb_penduduk`. 

Jadi pengisian dan penyimpanan alamat di form penduduk DAN keluarga menyesuaikan. 

JANGAN diubah alur ini. Yang bisa dilakukan adalah memperjelas panduan. Silakan bantu kalau ada waktu,
