### ISSUE TITLE
Perbaiki csrf supaya token hanya dipakai sekali

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#2941]
### Bagaimana alurnya sampai muncul masalah?
Saat ini melalui commit 6b4109718a6ec265684f8f1bcf69d25aedd16afb anti-csrf sudah jalan normal di Layanan Mandiri > Permohonan Surat. Tapi ini hanya bisa dengan setting `config.php` sebagai berikut:
```
$config['csrf_regenerate'] = false;
```

### Seperti apa yang diharapkan?
Perlu solusi untuk generate csrf token baru dan lakukan anti-csrf setiap kali setelah setiap submit form. Yaitu untuk setting
```
$config['csrf_regenerate'] = true;
```

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | v20.04-pasca
| Versi PHP        | 
| System operasi   |

**Comment by sup-ham** [comment]
ini harus ngambil dari cookie saat runtime  tokennya  pak

**Comment by eddieridwan** [comment]
Sudah dicommit ke `master` melalui PR #2943
