### ISSUE TITLE
Countdown Langsung Aktif tanpa Login

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#2942]
### Bagaimana alurnya sampai muncul masalah?
Akses URL berikut:
http://demo.opensid.my.id/siteman/auth
atau
http://beta.opensid.my.id/siteman/auth

Langsung muncul countdown, bukan halaman untuk mulai login.

**Comment by afa28** [comment]
Mungkin alurnya salah, harusnya siteman/auth tdk bisa diakses scr langsung. Jika siteman/auth diakses langsung tanpa lewat form siteman, kembalikan ke form siteman tanpa mengembalikan nilai.

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3553
