### ISSUE TITLE
perlukah tombol login admin di layanan mandiri?

### ISSUE THREAD

**Issue by sup-ham** [OpenSID/OpenSID#2945]
### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

![image](https://user-images.githubusercontent.com/3823496/79639524-91e5aa00-81b6-11ea-8a8b-262a5f127014.png)

**Comment by asalreview** [comment]
saya rasa menu statis dan tombol login admin tidak perlu di halaman mandiri.

**Comment by SopianHadi2021** [comment]
Ya Setuju

**Comment by afa28** [comment]
Kyaknya tdk perlu dan mungkin yg perlu tampilan layanan mandiri di perbaiki agar lebih menarik.

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3494
