### ISSUE TITLE
Validasi kolom Covid-19 yg wajib diisi

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#2947]
### Bagaimana alurnya sampai muncul masalah?
Buka menu Siaga Covid-19 Pendataan dan Pemantauan
Buka form untuk tambah data pemudik dan tambah data pemantauan
Klik tombol Simpan

### Seperti apa yang diharapkan?
Kolom yg seharusnya wajib diisi harus diisi sebelum form bisa disimpan.
<img width="1400" alt="wajib-isi-1" src="https://user-images.githubusercontent.com/249563/79679758-2cdc9380-824c-11ea-9916-35de934e2b02.png">
<img width="1400" alt="wajib-isi-2" src="https://user-images.githubusercontent.com/249563/79679760-2f3eed80-824c-11ea-9ecc-dc68991d0493.png">

### Apa yang terjadi?
Saat ini form bisa disimpan walaupun data yg seharusnya diisi masih kosong.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by af-lazuardi** [comment]
siap Pak @eddieridwan , siap untuk diperbaiki... 
Terima kasih.

**Comment by eddieridwan** [comment]
Sudah dicommit ke `master` melalui PR #2951
