### ISSUE TITLE
Tambahkan relational constraint untuk tabel Covid-19 [teknis]

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#2948]
### Bagaimana alurnya sampai muncul masalah?
Masukkan data pemudik dan data pantuan di menu Siaga Covid-19.
Di halaman Kependudukan > Penduduk, hapus salah satu pemudik Covid-19.

### Seperti apa yang diharapkan?
Seharusnya data Pemudik dan Pemantauan otomatis terhapus. 

### Apa yang terjadi?
Data Pemudik dan Pemantauan untuk penduduk yg terhapus masih ada. 

### Informasi tambahan 
Tambahkan relational constraint seperti berikut di migrasi DB, antara `tweb_penduduk` dan `covid19_pemudik` dan antara `covid19_pemudik` dan `covid19_pantau`.
```
			$this->dbforge->add_column(
				'syarat_surat',
				array("CONSTRAINT `id_surat_format` FOREIGN KEY (`surat_format_id`) REFERENCES `tweb_surat_format` (`id`) ON DELETE CASCADE ON UPDATE CASCADE")
			);
```

Dan hapus penghapusan terkait secara manual yg sekarang ada di `donjo-app/models/Covid19_model.php` (sebaiknya otomatis dilakukan oleh database):

```
	public function delete_pemudik_by_id($id) 
	{
		//delete warga pemudik di menu pemantau
		$this->db->where('id_pemudik', $id);
		$this->db->delete('covid19_pantau');
		
		//delete warga pemudik
		$this->db->where('id', $id);
		$this->db->delete('covid19_pemudik');
	}
```

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | v19.04-pasca
| Versi PHP        | 
| System operasi   |

**Comment by af-lazuardi** [comment]
Baik Pak @eddieridwan , siap untuk diperbaiki.

**Comment by eddieridwan** [comment]
Sudah dicommit ke `master` melalui PR #2950
