### ISSUE TITLE
[BUG] XSS di Form COVID-19

### ISSUE THREAD

**Issue by Snoopy-Sec** [OpenSID/OpenSID#2949]
### Bagaimana alurnya sampai muncul masalah?
![Screen Shot 2020-04-19 at 1 07 58 PM](https://user-images.githubusercontent.com/36057801/79680874-d9177d80-823e-11ea-95e3-66ee715f3336.png)

Hal ini terdapat pada url http://demo.opensid.my.id/index.php/covid19 maupun https://beta.opensid.my.id/covid19. Pada saat ingin mengisi pada form_data covid-19, terdapat form input Asal Pemudik (kota), Kontak Pemudik (No HP and Email), Ketika kita memasukan payload XSS **_<script>alert(1)</script>_** dan tidak ada filtering terhadap XSS maka serangan pun ter-eksekusi dengan baik.

### Seperti apa yang diharapkan?
- Lakukan Validasi Data.
- Memberi filter pada karakter yang di-inputkan pengguna.
Serta lakukan pemfilteran input:
- <script></script>.
- Javascript commands.
- Tag HTML.

### Apa yang terjadi?
Tidak ada filtering terhadap XSS maka serangan terjadi.

![Screen Shot 2020-04-19 at 1 09 11 PM](https://user-images.githubusercontent.com/36057801/79680932-5fcc5a80-823f-11ea-9d01-1c43ad14531d.png)
![Screen Shot 2020-04-19 at 1 09 20 PM](https://user-images.githubusercontent.com/36057801/79680935-61961e00-823f-11ea-8553-46d9ecb6957f.png)
![Screen Shot 2020-04-19 at 1 09 31 PM](https://user-images.githubusercontent.com/36057801/79680938-64910e80-823f-11ea-83be-7b6e09dc197d.png)

### Informasi tambahan 
Keep secure <3

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.04-pasca
| Versi PHP        |  7.2.29
| System operasi   | Linux

**Comment by sup-ham** [comment]
mantap pa

**Comment by af-lazuardi** [comment]
okay, akan diperbaiki. terima kasih masukannya

**Comment by eddieridwan** [comment]
Sudah dicommit ke `master` melalui PR #2952
