### ISSUE TITLE
Pemanggilan Penduduk di Siaga Covid terbaca semua (mati,pindah dll)

### ISSUE THREAD

**Issue by WAHYUDIK** [OpenSID/OpenSID#2953]
### Bagaimana alurnya sampai muncul masalah?

ketika kita ingin menambah warga pemudik dan memilih NIK/Nama Warga, yang muncul adalah data keseluruhan, data warga yang sudah pindah dan mati ikut tambil juga di data pencarian.
### Seperti apa yang diharapkan?
seharusnya ketika pencarian data, yang tampil hanyalah penduduk yang aktif saja, yang pindah dan mati tidak usah ditampilkan

### Apa yang terjadi?

saat ini data penduduk baik yang aktif, mati dan pindah masih tampil semua
### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by af-lazuardi** [comment]
Baik pak, saya perbaiki

**Comment by balongbesuk** [comment]
yang pindah biarkan saja, biasanya mudik pulang kampung,

**Comment by balongbesuk** [comment]
Sy belum pernah nyoba fitur ini, cm mengingatkan data penduduk pindah masih tersimpan di database penduduk / log, kemungkinan penduduk tersebut kembali / mudik sangat besar, bagaimana penanganannya? 

Sy jg belum mencoba menambahkan penduduk pendatang dengan penduduk pindah. Apakah NIK sama bisa diterima oleh sistem,

**Comment by ai-skematik** [comment]
Menurut sy penduduk yg sudah pindah tidak boleh dikembalikan walaupun masih tersimpan di log. Jika dia kembali karena dia mudik, dicatat baru sebagai penduduk pendatang..

**Comment by balongbesuk** [comment]
> Menurut sy penduduk yg sudah pindah tidak boleh dikembalikan walaupun masih tersimpan di log. Jika dia kembali karena dia mudik, dicatat baru sebagai penduduk pendatang..

Sudah dicoba ditambahkan? Bisa? atau ditolak sistem?

**Comment by ai-skematik** [comment]
Belum di coba..

**Comment by balongbesuk** [comment]
sy cb tes di web demo dan beta, cm sampe ubah status penduduknya kena crsf token, :v:

**Comment by eddieridwan** [comment]
Sudah dicommit ke `master` melalui PR #2958
