### ISSUE TITLE
Akses Khusus Menu Covid-19

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#2954]
### Bagaimana alurnya sampai muncul masalah?
Saat ini Bidan Desa dan/atau tenaga relawan yang dipercaya untuk mendata sekaligus input para pendatang sebagai ODR. 

### Seperti apa yang diharapkan?
Mohon dapat dipertimbangkan menu khusus atau hak akses tambahan khusus hanya dalam memanfaatkan Menu Covid-19 dimaksud. 

### Apa yang terjadi?
Agar oetugas khusus input data pendatang tidak melihat menu lain yang ada di halaman siteman.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by af-lazuardi** [comment]
Pak @eddieridwan , mohon arahan, apakah hal ini boleh diterapkan. Group user khusus untuk mengakses menu covid-19 saja.?

**Comment by afa28** [comment]
Kyaknya klw ini disetujui, harus jg ditambahkan ke akses modul penduduk. Krn jika ada penduduk pendatang, harus di input dlu di data penduduk.

**Comment by ariandii** [comment]
untuk saat ini, yg dilakukan jika tidak ada database, hanya inout nama dengan NIK 0 ke semua pendatang yg blm terdata.

**Comment by M-A-Haris** [comment]
Pendatang atau pekerja atau liburan bareng nenek,  yang tidak ada di data base diharapkan bisa diinput manual..

**Comment by af-lazuardi** [comment]
pak @M-A-Haris , maksudnya input manual gimana Pak? 
Inputnya tidak melalui menu kependudukan? Apakah begitu maksudnya?

**Comment by M-A-Haris** [comment]
Pak@af-lazuardi manual itu mirip isian surat domisili non warga.. (Bukan Warga Desa). karena dibeberapa wilayah ada pekerja yang berdatangan seperi di Karangkamulyan ada pekerjaan penggantian rel kereta api, pekerjanya puluhan bahkan ratusan orang. kita laporkan secra manual. selin itu ada juga warga ber KTP luar desa (jakarta) yang liburan atau lebaran di kampung

**Comment by eddieridwan** [comment]
Bung @af-lazuardi @M-A-Haris , sepertinya ini hanya persepsi saja. Kalau perlu dipantau melalui OpenSID, ya harus masuk ke database (kalau tidak mau, ya gunakan Excel saja). Mungkin satu solusi adalah menyediakan form pengisian terpisah (yaitu sekadar memberi kesan seperti melakukan masukan 'manual') tetapi datanya tetap tersimpan di tabel `tweb_penduduk` untuk kolom yg merupakan data dasar 'penduduk' (seperti nama, alamat, tgl lahir, dstnya).  Dan otomatis diberi status 'pendatang'. Atau kalau memang berbeda dengan 'pendatang' juga bisa ditambahkan status berbeda, misalnya 'domisili non warga'.  Tetapi HARUS bisa membedakan antara `pendatang` dengan `domisili non-warga`. Kalau tidak berbeda, gunakan `pendatang` saja (tidak perlu ada kategori tambahan). Menu untuk form ini bisa disediakan di bawah Siaga Covid-19 dan juga di bawah Kependudukan.

**Comment by af-lazuardi** [comment]
Siap Pak @eddieridwan , benar maksud saya seperti itu. Ada form inputan tersendiri di Menu Covid untuk penduduk pendatang dgn field2 yg secukupnya diisi saja. Tapi data tetap masuk ke t_web_penduduk status pendatang.

**Comment by eddieridwan** [comment]
Sudah dicommit ke `master` melalui PR #2989
