### ISSUE TITLE
Penabahan widget statis masih manual

### ISSUE THREAD

**Issue by afa28** [OpenSID/OpenSID#2955]
### Bagaimana alurnya sampai muncul masalah?
Buka menu admin web > widget > tambah widget > pilih jenis widget statis. Maka akan muncul form isian nama file wiget yg harus di input. Jika kita menghafal nama file widget mungkin tdk masalah/bisa cek filenya langsung. Tp cara dgn input tdk efisien, ada kemungkin salah dalam menginput nama file widget yg menyebabkan widget statis tdk muncul.

### Seperti apa yang diharapkan?
Ganti tipe input menjadi list dimana isinya diambil dari widget bawaan opensid dan bawaan tema yg sedang digunakan.

### Apa yang terjadi?
Meminimalisir terjadinya kesalahan input nama file widget statis.

### Informasi tambahan 
Themes harus menyediakan folder widget jika ada ada tambahan widget untuk tema tsb

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dicommit melalui PR #2962
