### ISSUE TITLE
Tabel reference constraine

### ISSUE THREAD

**Issue by afa28** [OpenSID/OpenSID#2956]
### Bagaimana alurnya sampai muncul masalah?
Tabel reference constraine

### Seperti apa yang diharapkan?
Apa tabel berikut perlu relasi:

1. Artikel -> kategori
2. Artike -> user
3. Dokumen -> tweb_penduduk
4. Syarat_surat -> dokument
5. User_group -> user
6. Tweb_will_clusterdesa -> tweb_penduduk
7. Tweb_keluarga <- tweb_penduduk
8. Tweb_rtm <- tweb_penduduk
9. Tweb_desa_pamong -> tweb_penduduk
10. Program_peserta -> program
11. Permohonan_surat -> tweb_penduduk
12. Permohonan_surat -> surat_keluar
13. Komentar -> artikel
14. Log_keluarga -> tweb_keluarga

### Apa yang terjadi?
Tambahkan jika ada yg terlewat.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.03-pasca
| Versi PHP        | 7.4
| System operasi   | Windows

**Comment by eddieridwan** [comment]
@afa28 hanya sebagian kecil yg bersifat cascade delete.  Yg lain, tidak boleh terdampak secara otomatis, karena sifatnya bukan ketergantungan eksistensi.

Sebagai contoh: 
1. artikel -> kategori. Kalau kategori dihapus, artikel TIDAK dihapus, karena keberadaan artikel tidak bergantung pada kategori. Kategori hanya bersifat sebagai informasi tentang artikel. Di menu artikel, artikel yg tidak berkategori bisa dibuatkan kategori baru.
2. artikel -> user. Kalau user dihapus, tidak berarti artikel yg ditulis oleh user itu ikut dihapus. Artikel terus tersimpan, hanya sekarang penulisnya tercatat sebagai tidak diketahui, atau oleh user yg telah dihapus.

dstnya... 

Jadi setiap kasus yg anda daftarkan di atas perlu dianalisis secara satu per satu.

**Comment by afa28** [comment]
> @afa28 hanya sebagian kecil yg bersifat cascade delete. Yg lain, tidak boleh terdampak secara otomatis, karena sifatnya bukan ketergantungan eksistensi.
> 
> Sebagai contoh:
> 
> 1. artikel -> kategori. Kalau kategori dihapus, artikel TIDAK dihapus, karena keberadaan artikel tidak bergantung pada kategori. Kategori hanya bersifat sebagai informasi tentang artikel. Di menu artikel, artikel yg tidak berkategori bisa dibuatkan kategori baru.
> 2. artikel -> user. Kalau user dihapus, tidak berarti artikel yg ditulis oleh user itu ikut dihapus. Artikel terus tersimpan, hanya sekarang penulisnya tercatat sebagai tidak diketahui, atau oleh user yg telah dihapus.
> 
> dstnya...
> 
> Jadi setiap kasus yg anda daftarkan di atas perlu dianalisis secara satu per satu.

Iya pak, jd harus ada list tabel perlu. List di atas sy buat hanya dgn sekilas melihat, masih perlu di filter. 🙏

Mungkin nanti sy cek detail sesuai arah bapak di atas
