### ISSUE TITLE
Tidak Bisa Upload Database Siskeudes

### ISSUE THREAD

**Issue by asalreview** [OpenSID/OpenSID#2957]
### Bagaimana alurnya sampai muncul masalah?
Tombol simpan pada menu keuangan tidak berfungsi setelah update perubahan pada hari ini 20 April 2020.
![image](https://user-images.githubusercontent.com/60563749/79750428-26791500-833b-11ea-8ec0-b74fc2ffd242.png)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.04 - Pasca
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
Sy kira cuma sy yg alami. 🤭

**Comment by asalreview** [comment]
@afa28 hehehe ia pak, isu yang saya buat udah pasti bukan masalah personal yang saya angkat karena sebelum saya buat isu sudah saya tes dulu masalah ini apa cuma saya saja yang bermasalah atau emang master bawaan.

**Comment by asalreview** [comment]
@afa28 hehehe ia pak, isu yang saya buat udah pasti bukan masalah personal yang saya angkat karena sebelum saya buat isu sudah saya tes dulu masalah ini apa cuma saya saja yang bermasalah atau emang master bawaan.

**Comment by afa28** [comment]
Mantap pak @asalreview, dibutuhkan untuk tester cari bug dr perubahan yg telah di buat.

**Comment by afa28** [comment]
Pak @asalreview , Sudah sy cek dan mengembalikan file yg berkaitan dgn modul keuangan yg digunakan versi 20.03, tapi hasilnya tetap sama (tombol tdk tereksekusi).

Kyaknya ada perubahan script yg berhubungan dgn modul ini yg berubah di teempat lain. Bgmna pak @eddieridwan ???

**Comment by M-A-Haris** [comment]
sama tak bisa upload. mucul eror

**Comment by afa28** [comment]
> sama tak bisa upload. mucul eror

errornya apa pak??? Di sya tombol simpannya tdk tereksekusi

**Comment by afa28** [comment]
> > sama tak bisa upload. mucul eror
> 
> errornya apa pak??? Di sya tombol simpannya tdk tereksekusi. Sy sdah kembalikan file modul keuangan ke versi 20.03 tp tetap sama.

**Comment by M-A-Haris** [comment]
eror 400

**Comment by afa28** [comment]
> eror 400

ini lain lg errornya ;v

**Comment by asalreview** [comment]
Pak @M-A-Haris seingat  klo di 20.03 error karena $db['default']['stricton'] = TRUE; karena sebagian hosting tidak mendukung nilai stricton true. jika salah mohon dikoreksi.

**Comment by afa28** [comment]
> Pak @M-A-Haris seingat saya klo di 20.03 error karena $db['default']['stricton'] = TRUE; karena sebagian hosting tidak mendukung nilai stricton true. jika salah mohon dikoreksi.

yup

**Comment by M-A-Haris** [comment]
![eror keuangan](https://user-images.githubusercontent.com/46555658/79758439-9e4d3c80-8347-11ea-8d4f-2ba14c485e01.jpg)

**Comment by M-A-Haris** [comment]
maaf eror 500

**Comment by asalreview** [comment]
@M-A-Haris itu krena nilai $db['default']['stricton'] = TRUE pak

**Comment by M-A-Haris** [comment]
> @M-A-Haris itu krena nilai $db['default']['stricton'] = TRUE pak

tinggal dirubah jadi false di config?

**Comment by asalreview** [comment]
@M-A-Haris benar pak

**Comment by afa28** [comment]
![Capture](https://user-images.githubusercontent.com/57283157/79759429-dd2fc200-8348-11ea-91bd-37cc551b3f5e.PNG)

PR sy yg di merge pak @eddieridwan hari ini sudah sy cek, tdk ada masalah. Sy belum cek yg lain.

**Comment by eddieridwan** [comment]
Sudah diperbaiki, dicommit ke `master`. Masalah csrf token, karena cara penanganan submit untuk impor data keuangan berbeda dengan yg lain. Laporkan kalau ada menemukan masalah serupa di menu yg lain.

**Comment by M-A-Haris** [comment]
Makasih bung Affa
