### ISSUE TITLE
[Bantuan] Tampilan Jumlah Bukan Peserta di Statistik Program Bantuan

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#2960]
### Bagaimana alurnya sampai muncul masalah?
Buka Menu Statistik ==> Statistik Kependudukan ==> Statistik Program Bantuan
Pilih salah satu Program bantuan, yang saya contohkan adalah Program PKH, Ketika ingin mengetahui siapa saja nama warga yang termasuk bukan Peserta yang muncul ternyata jumlah peserta
![Statistik](https://user-images.githubusercontent.com/25834335/80007950-96cd9500-84f9-11ea-8f5a-d997041c2afd.jpg)

### Seperti apa yang diharapkan?
Yang Tampil adalah masyarakat yang BUKAN PESERTA sehingga Pemerintah Desa tau siapa saja nama orang yang belum menjadi peserta

### Apa yang terjadi?
belum bisa mengetahui langsung siapa saja yang termasuk bukan peserta

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by gampongbarabung** [comment]
usulan yang baik pak

**Comment by eddieridwan** [comment]
Sudah ada di v21.12-premium.
