### ISSUE TITLE
penambahan kontribusi embed youtube di front end

### ISSUE THREAD

**Issue by andreyuberta** [OpenSID/OpenSID#2963]
### Bagaimana alurnya sampai muncul masalah?
untuk newbie yg mau berkreasi d front end dgn youtube dan atur tata letaknya

### Informasi tambahan 

		            	<div class="icon d-flex align-items-center justify-content-center">
		            		<span class="flaticon-cloud-computing"></span>
		            	</div>
		              <div class="mt-3 media-body media-body-2 text-justify">
		                <h3 class="heading">Vidio Inspirasi Untuk Anda</h3>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>		                
                    <p>
                      <iframe width="550" height="315" src="https://www.youtube.com/embed/Br5aJa6MkBc" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                    </p>
                    <p>
                      <iframe width="550" height="315" src="https://www.youtube.com/embed/NSwit83WnDk" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                    </p>
                    <p>Molestiae cupiditate inventore animi, maxime sapiente optio, illo est nemo veritatis repellat sunt doloribus nesciunt! Minima laborum magni reiciendis qui voluptate quisquam voluptatem soluta illo eum ullam incidunt rem assumenda eveniet eaque sequi deleniti tenetur dolore amet fugit perspiciatis ipsa, odit. Nesciunt dolor minima esse vero ut ea, repudiandae suscipit!</p>
		              </div>

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.05
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
Silahkan embed menggunakan fitur yg disediakan di editor tymce. Untuk lebih jelasnya bisa baca panduan atau bertanya ke group OpenSID.

**Comment by afa28** [comment]
Silahkan berkreasi:

Misal menyatukan semua artikel khusus yg dgn embed yotube dgn membuat kategori artikel tsb.

**Comment by mizwaruddin** [comment]
@afa28 apakah bisa ditindaklanjuti?

**Comment by afa28** [comment]
> @afa28 apakah bisa ditindaklanjuti?

Tergantung pengguna bagai mana berkreasi di website mereka.
