### ISSUE TITLE
Widget Tema Tidak Tersedia

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#2969]
### Bagaimana alurnya sampai muncul masalah?
Saat update OpenSID versi 20.04-pasca per 25 April 2020, WIDGET bawaan Tema pada folder desa/themes/nama_tema/widgets tidak dapat difungsikan.

![aaa](https://user-images.githubusercontent.com/46939846/80286414-87e31e80-8755-11ea-8dc5-0a6071a9e75e.png)

### Seperti apa yang diharapkan?
Berfungsinya kembali pilihan Widget bawaan Tema, supaya tidak menyulitkan untuk copy paste file ke folder desa/widget.

### Apa yang terjadi?
Agar Widget Tema berjalan dengan semestinya sesuai dengan Style Tema tersebut.

**Comment by eddieridwan** [comment]
Masukkan file widget status ke folder desa/widget dulu. Nanti akan otomatis terdeteksi dan muncul di form itu. Kalau widget sudah ditambahkan ke database, tidak akan muncul lagi, supaya tidak ada widget duplikat.

**Comment by eddieridwan** [comment]
@afa28 , anda bisa terapkan?

**Comment by afa28** [comment]
Ini sempat mau sertakan kemarin saat buat PR. Tp krn sy lihat alamat pemanggilan view widget adalah desa/widget dan belum tersedia pilihan lain (1/2/3) jd sy tdk ikutkan.

**Comment by afa28** [comment]
> @afa28 , anda bisa terapkan?

Bisa pak.

**Comment by eddieridwan** [comment]
Sudah dicommit ke `master` melalui PR #2970
