### ISSUE TITLE
Tujuan Pemudik tidak tampil

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#2973]
### Bagaimana alurnya sampai muncul masalah?
Masuk di meni Siaga Covid-19 klik Pendataan==>Tambah Warga Pemudik
![image](https://user-images.githubusercontent.com/25834335/80515727-fc67c880-89b4-11ea-9f30-50450ddfa930.png)
Klik Simpan
maka yang muncul : 
![Covic](https://user-images.githubusercontent.com/25834335/80516018-6e401200-89b5-11ea-9ae7-553cee2a7a6e.png)

### Seperti apa yang diharapkan?
Setelah Klik Simpan Tujuan Pemudik Tampil

### Apa yang terjadi?
Tujuan Pemudik Tidak Tampil, sehingga datanya tdk terekam

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dicommit ke `master`.
