### ISSUE TITLE
Tidak dapat menampilkan info covid (contoh angka ODP) pada halaman website

### ISSUE THREAD

**Issue by Gunturwijay** [OpenSID/OpenSID#2974]
### Bagaimana alurnya sampai muncul masalah?
![image](https://user-images.githubusercontent.com/40741591/80632244-2f778e00-8a81-11ea-80d3-a2075dcb0158.png)

![image](https://user-images.githubusercontent.com/40741591/80632329-52a23d80-8a81-11ea-962c-66e5569899b7.png)

### Seperti apa yang diharapkan?
Jumlah angka status covid seharusnya dapat muncul di halaman website

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Perbaikan sudah dicommit ke `master`.
