### ISSUE TITLE
Tidak Bisa Hapus Anggota Keluarga

### ISSUE THREAD

**Issue by mizwaruddin** [OpenSID/OpenSID#2976]
![error_hapus_anggota_kk](https://user-images.githubusercontent.com/39736008/80672931-2665db80-8ad8-11ea-9df5-85c8cb8dd404.PNG)

### Bagaimana alurnya sampai muncul masalah?
Dalam daftar anggota keluarga, anggota keluarga terpilih tidak bisa dihapus.

### Seperti apa yang diharapkan?
Anggota keluarga bisa dihapus

### Apa yang terjadi?
Tombol hapus tidak berfungsi

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.04-pasca
| Versi PHP        | 
| System operasi   |
![error_hapus_anggota_kk](https://user-images.githubusercontent.com/39736008/80672973-41d0e680-8ad8-11ea-8b58-7d81db028b5d.PNG)

**Comment by balongbesuk** [comment]
yang bisa menghapus cuma adminstrator

**Comment by mizwaruddin** [comment]
Saya login sebagai admin

**Comment by Nurhidayat29** [comment]
terjadi bud pada tombl hapus

**Comment by mizwaruddin** [comment]
Sudah saya coba di web berputar jg tdk bisa.

**Comment by eddieridwan** [comment]
Memang seharusnya tidak bisa menghapus anggota keluarga dari halaman itu. Untuk mengeluarkan anggota dari keluarga, lakukan pecah KK. Untuk menghapus penduduknya, lakukan dari halaman Penduduk. 

Jadi issue ini untuk menghilangkan tombol Hapus Data Terpilih dan juga sekalian menghapus kotak centang anggota.

**Comment by af-lazuardi** [comment]
kalau saya lihat di kodenya, sebenarnya delete anggota ini logic nya sama seperti yang dilakukan oleh pecah KK, mengeluarkan anggota dari keluarga (bukan menghapus data penduduk). Cuman memang code javascriptnya (di asset/js/script.js) tidak terkeksekusi. Mungkin karena ada tag2 html yang tidak tertutup sempurna.

**Comment by af-lazuardi** [comment]
bung @afa28 , sepertinya ini juga masalah modal seperti issue #2986, tombol hapusnya jadi tidak berfungsi.

**Comment by afa28** [comment]
> bung @afa28 , sepertinya ini juga masalah modal seperti issue #2986, tombol hapusnya jadi tidak berfungsi.

Sudah di PR pak @afa28 . Kalau untuk issue #2976, kyaknya akan ada perubahan.

**Comment by afa28** [comment]
> Memang seharusnya tidak bisa menghapus anggota keluarga dari halaman itu. Untuk mengeluarkan anggota dari keluarga, lakukan pecah KK. Untuk menghapus penduduknya, lakukan dari halaman Penduduk.
> 
> Jadi issue ini diubah untuk menghilangkan tombol Hapus Data Terpilih dan juga sekalian menghapus kotak centang anggota. -- supaya tidak membuat pengguna keliru.

Jadi solusi yg tepat bgmna pak yg mau diterapkan???

**Comment by af-lazuardi** [comment]
> kalau saya lihat di kodenya, sebenarnya delete anggota ini logic nya sama seperti yang dilakukan oleh pecah KK, mengeluarkan anggota dari keluarga (bukan menghapus data penduduk). Cuman memang code javascriptnya (di asset/js/script.js) tidak terkeksekusi. Mungkin karena ada tag2 html yang tidak tertutup sempurna.

ini bukan solusi ya, dari logic codenya adalah pada awalnya tombol hapus itu logicnya seperti tombol pecah KK, hanya mengeluarkan penduduk dari KK tersebut. 
Barangkali salah memilih anggota keluarga ke KK, sehingga harus dihapus (dikeluarkan)
Menurut saya tetap ada tombol hapus, untuk mengeluarkan anggota KK dari KK tersebut (bukan menghapus penduduk). Itu tidak jalan, bisa jadi sebab javascriptnya tidak tereksekusi, barangkali permasalahannya hanya di closing tag html atau memanggil modal yang berbeda, sehingga fungsi sebelumnya yang terdapat pada modal lain tidak tereksekusi.

**Comment by afa28** [comment]
> > kalau saya lihat di kodenya, sebenarnya delete anggota ini logic nya sama seperti yang dilakukan oleh pecah KK, mengeluarkan anggota dari keluarga (bukan menghapus data penduduk). Cuman memang code javascriptnya (di asset/js/script.js) tidak terkeksekusi. Mungkin karena ada tag2 html yang tidak tertutup sempurna.
> 
> Dari logic code existing adalah tombol hapus itu logicnya seperti tombol pecah KK, hanya mengeluarkan penduduk dari KK tersebut.
> 
> Barangkali salah memilih anggota keluarga ke KK, sehingga harus dihapus (dikeluarkan)
> Menurut saya tetap ada tombol hapus, untuk mengeluarkan anggota KK dari KK tersebut (bukan menghapus penduduk).
> 
> Itu tidak jalan, bisa jadi sebab javascriptnya tidak tereksekusi, barangkali permasalahannya hanya di closing tag html atau memanggil modal yang berbeda, sehingga fungsi sebelumnya yang terdapat pada modal lain tidak tereksekusi.

Kalau pak @eddieridwan dll sependapat, segera sy perbaiki sesuai arahan.

**Comment by mizwaruddin** [comment]
Klo sya sependapat fungsi hapus anggota KK ttp ada utk mengeluarkan anggota yg salah masuk. Klo dikeluarkan melaui pecah KK, maka akan nomor KK lama akan melekat pada anggota KK ybs.

**Comment by afa28** [comment]
> Klo sya sependapat fungsi hapus anggota KK ttp ada utk mengeluarkan anggota yg salah masuk. Klo dikeluarkan melaui pecah KK, maka akan nomor KK lama akan melekat pada anggota KK ybs.

siap

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3413
