### ISSUE TITLE
stored xss pada menu layanan mandiri > kotak pesan

### ISSUE THREAD

**Issue by orangmiliter** [OpenSID/OpenSID#2982]
### celah kemanan  
XSS Stored pada layanan mandiri > kotak pesan > kotak keluar

### deskripsi celah keamanan
xss adalah jenis serangan injeksi code html dan javascript, serangan xss terdiri dari 2 tipe : 
1. reflected (nonpersistent) celah hanya berdampak pada sisi browser penyerang
2. stored (persistent) celah berdampak pada penyerang dan pengunjung lain.

### langkah langkah
1. menuju menu layanan mandiri > kotak pesan > pesan keluar
2. membuat pesan baru
3. memasukan code <script>alert(document.cookie)</script> pada form subjek.

### sistem yang terkena pengaruh
https://demo.opensid.my.id/mailbox/index/2/1/0

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.5
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dicommit ke `master`.
@orangmiliter Terima kasih telah melaporkan.
