### ISSUE TITLE
Perbaikan tampilan

### ISSUE THREAD

**Issue by afa28** [OpenSID/OpenSID#2983]
### Bagaimana alurnya sampai muncul masalah?
Dibeberapa modul ada beberapa tampilan yg kurang enak di pandang mata, baik itu versi dektop maupun mobile.

### Seperti apa yang diharapkan?
Perbaikan tampilan.

### Informasi tambahan 
Kalau masih ada yg perlu diperbaiki dan tdk ada dl PR, bisa tulis komentar di bawah.

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dicommit ke `master` melalui PR #2977
