### ISSUE TITLE
tidak bisa login setelah update 20.05

### ISSUE THREAD

**Issue by alexkliwon** [OpenSID/OpenSID#2985]
### Bagaimana alurnya sampai muncul masalah?
saya update OpenSid 20.04 pasca ke 20.05 saat login siteman/auth pesan yg muncul 400 gagal verifikasi csrf

### Informasi tambahan 

| Tanya            |
| ---------------- | ---
| Versi OpenSID    | 20.05
| Versi PHP        | 7
| System operasi   | window

**Comment by af-lazuardi** [comment]
lakukan clear cache dan cookies di browser. setelah itu tutup browser. Buka browser baru dan dicoba kembali

**Comment by alexkliwon** [comment]
solved pak ternyata clear cache dan cookies nya gak hanya 1 kali mesti berulang ulang makasih pak saran nya
