### ISSUE TITLE
Tombol Hapus di Pengaturan Surat Tidak Berfungsi

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#2986]
### Bagaimana alurnya sampai muncul masalah?
Layanan Surat ==> Pengaturan Surat, Ketika ingin menghapus surat yang bukan bawaan sistem tombol hapus tidak berfungsi, seperti gambar dibawah ini : 
![Tombol Hapus](https://user-images.githubusercontent.com/25834335/80868678-be2d1a80-8cce-11ea-9ee6-45045079473f.png)

### Seperti apa yang diharapkan?
Tombol hapus di menu Layanan Surat ==> Pengaturan Surat berfungsi Normal seperti di versi sebelumnya

### Apa yang terjadi?
Tidak bisa menghapus surat yang tidak dipakai

### Informasi tambahan 
Saya coba di Situs Demo juga sama
| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.05 Pasca
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
Terimah kasih pak @MUHAMMADRANGSEL. Mungkin ada yg terlewat saat membuat PR, klw menemukan hal yg sama (tombol delete tdk berfungsi/tdk menampilkan modal confirm) mungkin bisa dilaporkan lg.

**Comment by eddieridwan** [comment]
Sudah dicommit ke `master` melalui PR #2987
