### ISSUE TITLE
Widget Tema Tampil Ganda

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#2990]
### Bagaimana alurnya sampai muncul masalah?
Saat ini widget tema sudah tampil pada pilihan Menu Widget Statis secara otomatis.
Namun, pilihan itu muncul walaupun pada tampilan website secara default ada beberapa widget yang sudah terpasang.

Dan jika kita memasang tema lebih dari 1 pada folder desa/themes, maka semua widget akan ditampilkan.

Misalnya saya buat folder themes/temaA_asli dengan themes/temaA_ubahan,
maka semua widget kedua tema tersebut akan tampil ganda.

![image](https://user-images.githubusercontent.com/46939846/80895612-f5242000-8d10-11ea-9c79-08b255dc000c.png)

### Seperti apa yang diharapkan?
Hanya menampilkan widget pada tema yang sudah dipilih pada pengaturan web_tema saja. 

**Karena bisa terjadi Perbedaan Class pada setiap tema dalam menampilkan style yang disesuaikan dengan tema itu sendiri.**

### Apa yang terjadi?
Agar tidak terlalu banyak pilihan widget statis nya.

**Comment by afa28** [comment]
![Screenshot_2020-05-03-09-59-51-05](https://user-images.githubusercontent.com/57283157/80896898-d419fa00-8d25-11ea-9b29-a7752e511934.png)

Point 1

**Comment by ariandii** [comment]
done
