### ISSUE TITLE
Sumber Image pada Widget Sinergi Program Tidak Terbaca

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#2992]
### Bagaimana alurnya sampai muncul masalah?
Saya akses langsung file berikut yang bersumber dari folder /desa/upload/widgets
1. https://natairaya.desa.id/desa/upload/widget/1584855073_masker.png
2. https://natairaya.desa.id/desa/upload/widget/1584855073_hotline2.png
3. https://natairaya.desa.id/desa/upload/widget/1584855073_pencegahan.png
4. https://natairaya.desa.id/desa/upload/widget/1584855073_petugas.png
5. Dan File Lainnya dalam folder tersebut.

Semua Gagal diakses langsung memalui URL. Sehingga Load pada widget halaman website juga gagal.

Padahal dalam folder itu ada file dimaksud:

![ada](https://user-images.githubusercontent.com/46939846/80896781-4be32700-8d1c-11ea-9031-574128cd1a8c.png)

https://natairaya.desa.id/web_widget/admin/sinergi_program juga ada.

![juga](https://user-images.githubusercontent.com/46939846/80896784-52719e80-8d1c-11ea-825a-1cf81c0eaead.png)

### Seperti apa yang diharapkan?
Normal kembali seperti sebelum update 20.05

**Comment by afa28** [comment]
> ### Bagaimana alurnya sampai muncul masalah?
> Saya akses langsung file berikut yang bersumber dari folder /desa/upload/widgets
> 
> 1. https://natairaya.desa.id/desa/upload/widget/1584855073_masker.png
> 2. https://natairaya.desa.id/desa/upload/widget/1584855073_hotline2.png
> 3. https://natairaya.desa.id/desa/upload/widget/1584855073_pencegahan.png
> 4. https://natairaya.desa.id/desa/upload/widget/1584855073_petugas.png
> 5. Dan File Lainnya dalam folder tersebut.
> 
> Semua Gagal diakses langsung memalui URL. Sehingga Load pada widget halaman website juga gagal.
> 
> Padahal dalam folder itu ada file dimaksud:
> 
> ![ada](https://user-images.githubusercontent.com/46939846/80896781-4be32700-8d1c-11ea-9031-574128cd1a8c.png)
> 
> https://natairaya.desa.id/web_widget/admin/sinergi_program juga ada.
> 
> ![juga](https://user-images.githubusercontent.com/46939846/80896784-52719e80-8d1c-11ea-825a-1cf81c0eaead.png)
> 
> ### Seperti apa yang diharapkan?
> Normal kembali seperti sebelum update 20.05

Pemanggilan lokasi sumber imagenya tdk menggunakan "LOKASI_GAMBAR_WIDGET", jd setiap perubahan lokasi sumber tdk ikut menyesuaikan

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master`.
