### ISSUE TITLE
Status Kehamilan Selalu Kembali ke Nilai Default Saat Dilakukan Edit Biodata Penduduk

### ISSUE THREAD

**Issue by mizwaruddin** [OpenSID/OpenSID#2995]
### Bagaimana alurnya sampai muncul masalah?
Saat melakukan edit biodata penduduk, status kehamilan yang sudah diedit sebelumnya (ex: "Hamil") kembali ke nilai default.

### Seperti apa yang diharapkan?
Nilai status kehamilan tetap berada pada nilai sebelumnya.
![STATUS KEHAMILAN](https://user-images.githubusercontent.com/39736008/80909484-05f58580-8d53-11ea-8d5d-9b684c0b1b39.PNG)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.05-Pasca
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Di https://demo.opensid.my.id fitur ini normal. Jadi masalah ada di instalasi anda. Coba lihat laporan error di file di folder logs.

**Comment by mizwaruddin** [comment]
Di web demo, saya coba dengan mengubah status kehamilan menjadi "HAMIL". Ketika sya lakukan edit ulang status tetap "HAMIL". Saya ganti mengubah status "TIDAK HAMIL", kemudian saya edit ulang, nilainya berubah menjadi "Pilih Status Kehamilan".
![ISSUE_KEHAMILAN](https://user-images.githubusercontent.com/39736008/80935986-6a6b2000-8df9-11ea-957b-23764e31abbb.jpg)

**Comment by eddieridwan** [comment]
Di menu mana? Urlnya apa? Penduduk mana di demo?

**Comment by eddieridwan** [comment]
Anda menggunakan HP. Apakah sudah coba di laptop, apakah beda?

**Comment by mizwaruddin** [comment]
Tadi saya menggunakan laptop. Saya coba lagi dengan cermat ternyta saat diform edit munculnya "pilih status kehamilan". Saya coba biarkan kemudian saya simpan, hasilnya "TIDAK HAMIL". 
Maaf kurang teliti dalam membuat isu.
