### ISSUE TITLE
stored xss pada menu analisis

### ISSUE THREAD

**Issue by orangmiliter** [OpenSID/OpenSID#3000]
### Celah Keamanan
XSS Stored pada menu analisis  

### Deskripsi Celah Keamanan
xss adalah jenis serangan injeksi code html dan javascript, serangan xss terdiri dari 2 tipe :

1. reflected (nonpersistent) celah hanya berdampak pada sisi browser penyerang
2. stored (persistent) celah berdampak pada penyerang dan pengunjung lain.  

### Langkah Langkah
1. menuju menu analisis
2. membuat analisa baru
3. memasukan script `<script>alert(1)</script>` pada form nama anlisis dan deskripsi analisi
4. simpan dan script dijalankan dengan baik

### Sistem Yang Terkena Pengaruh  
https://demo.opensid.my.id/analisis_master

### Dampak
1. pencurian cookie
2. perubahan halaman "deface" dengan teknik tertentu.

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.5-pasca
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dicommit ke `master`.
