### ISSUE TITLE
Menu Pemantauan

### ISSUE THREAD

**Issue by afri18** [OpenSID/OpenSID#3002]
### Bagaimana alurnya sampai muncul masalah?
Saat Klik Menu Pantau terjadi eror
![image](https://user-images.githubusercontent.com/6611881/81027718-f720e700-8ea8-11ea-913d-d3ac16373c78.png)

### Seperti apa yang diharapkan?
belum tau yang terbuka apa, baru pertama nyoba

### Apa yang terjadi?
![image](https://user-images.githubusercontent.com/6611881/81027755-1586e280-8ea9-11ea-8a85-da381cdc6cdc.png)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.05
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sdh dicommit melalui PR #3005
