### ISSUE TITLE
ubah widget bukan bawaan sistem tidak bisa

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#3003]
### Bagaimana alurnya sampai muncul masalah?
Menu Adminweb==>Widget, ketika ingin mengubah widget bukan bawaan sistem yang muncul seperti gambar dibawah ini:
![widget](https://user-images.githubusercontent.com/25834335/81060345-db4b2e80-8f04-11ea-86c0-7c9b130f893e.jpg)

![widget1](https://user-images.githubusercontent.com/25834335/81060008-33356580-8f04-11ea-9030-36b999a1a509.jpg)

### Seperti apa yang diharapkan?
mengubah widget seperti versi sebelumnya

### Apa yang terjadi?
tidak bisa merubah widget

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by ericksuryadinata** [comment]
Disaya bisa pak, barusan install tema natra, untuk OpenSID nya yang latest master, bukan file releases. 

1. Install tema natra -> aplikasikan tema natra
2. Buat widget baru ( sama seperti punya bapak ) -> lihat perubaha
3. Kembalikan lagi ke tema hadakewa / klasikn
4. Masuk widget lagi, diedit, masih muncul pilihan widget dari natra
![Screenshot_2020-05-06_20-01-29](https://user-images.githubusercontent.com/20630687/81179833-66dfc080-8fd4-11ea-963b-6b8a634cd329.png)

**Comment by afa28** [comment]
> ### Bagaimana alurnya sampai muncul masalah?
> Menu Adminweb==>Widget, ketika ingin mengubah widget bukan bawaan sistem yang muncul seperti gambar dibawah ini:
> ![widget](https://user-images.githubusercontent.com/25834335/81060345-db4b2e80-8f04-11ea-86c0-7c9b130f893e.jpg)
> 
> ![widget1](https://user-images.githubusercontent.com/25834335/81060008-33356580-8f04-11ea-9030-36b999a1a509.jpg)
> 
> ### Seperti apa yang diharapkan?
> mengubah widget seperti versi sebelumnya
> 
> ### Apa yang terjadi?
> tidak bisa merubah widget
> 
> ### Informasi tambahan
> Tanya	Jawab
> Versi OpenSID	2.x
> Versi PHP	
> System operasi

Dr gambar di atas, artinya pd folder desa/widgets/ hanya terdapat 1 widget (jadwal_shalat). Dmna ketentuan yg diberikan pak @eddieridwan , widget yg sudah ditambahkan tdk bisa ditambahkan lg. Silahkan hapus terlebih dahulu widget tsbt, kemudian tambahkan.

**Comment by afa28** [comment]
Kyaknya ini cuma butuh dibuatkan panduan sja

**Comment by afa28** [comment]
Pak @MUHAMMADRANGSEL, apa ini masih bermasalah???

**Comment by afa28** [comment]
Pak @MUHAMMADRANGSEL, apa ini masih bermasalah??? Jika masih bermasalah silahkan di reopen.
