### ISSUE TITLE
Hasilkan Data Penerima Bantuan dan Non Penerima Bantuan Secara Menyeluruh

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#3004]
### Bagaimana alurnya sampai muncul masalah?
saat ini desa dituntut untuk memberikan bantuan kepada warga terdampak musibah yang mana bantuan tersebut diberikan kepada warga yang bukan penerima bantuan pemerintah pusat secara menyeluruh, pada menu opensid bagian bantuan hanya mendaftarkan penduduk di desa pada menu bantuan sendiri-sendiri / terpisah pisah sehingga untuk menghasilkan data penduduk bukan penerima bantuan harus mengecek satu persatu pada data bantuan agar dapat mengetahui penduduk mana yang sudah mendapat bantuan dan yang bukan penerima

### Seperti apa yang diharapkan?
terdapat menu untuk mengolah data bantuan secara keseluruhan agar dapat menghasilkan data penduduk yang bukan penerima bantuan apapun

### Apa yang terjadi?
belum ada menu / fungsi tersebut sehingga memaksa desa mengolah data secara manual melalui excel

### Informasi tambahan 
![awdwaeads](https://user-images.githubusercontent.com/35319600/81065050-03d32880-8f05-11ea-9018-d28b82a844d4.jpg)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by afri18** [comment]
Mungkin ada filter untuk menu bantuan yg dimaksud, misal saat penambahan bantuan BLT dd ada filter yg sudah menerima bantuan lain datanya tidak tersaji/timbul, juga ada filter centang penerima bisa ganda atau tidak

**Comment by equeza** [comment]
wah..... setuju....................... untuk saat ini kami juga dibuat pusing dengan banyaknya bantuan dan ulah oknum yang memanfaatkan bantuan. sehinggga ada beberapa orang yang sudah mendapatkan bantuan lebih dari 1 jenis bantuan. 
segera dimunculkan di release selanjutnya ya.....

**Comment by eddieridwan** [comment]
Khusus program bantuan dengan sasaran penduduk, sdh dicommit ke `master` melalui PR #2310. 

Untuk program sasaran keluarga akan diterapkan terpisah di bawah statistik keluarga.

**Comment by eddieridwan** [comment]
Sudah dicommit melalui PR #3047. Kalau masih ada yg perlu disempurnakan, silakan buat issue baru.
