### ISSUE TITLE
Upload Dokumen Berhasil Disimpan Tapi Muncul Notif Gagal

### ISSUE THREAD

**Issue by af-lazuardi** [OpenSID/OpenSID#3008]
### Bagaimana alurnya sampai muncul masalah?
Saat upload Peraturan dan SK Kades di Form [Dokumen Sekretariat](http://demo.opensid.my.id/dokumen_sekretariat/form), data dan dokumen tersimpan di database, tapi notif setelah submit GAGAL

### Seperti apa yang diharapkan?
Notif submit dokumen SUKSES

### Apa yang terjadi?
Muncul notif GAGAL

### Informasi tambahan 
Uji coba dilakukan di situs demo.opensid.my.id
![sk](https://user-images.githubusercontent.com/13193883/81092188-74d90700-8f2a-11ea-97cb-918769879968.png)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.05-pasca
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3013
