### ISSUE TITLE
Upload Dokumen Warga Format JPEG Gagal di Upload

### ISSUE THREAD

**Issue by af-lazuardi** [OpenSID/OpenSID#3009]
### Bagaimana alurnya sampai muncul masalah?
Di menu manajemen dokumen penduduk, untuk upload dokumen berupa *.jpeg tidak bisa dilakukan

### Seperti apa yang diharapkan?
Upload data format *,jpeg dapat dilakukan

### Apa yang terjadi?
Muncul pesan ERROR "File berisi script"

### Informasi tambahan 
Uji coba di situs http://demo.opensid.my.id/
![dokumen_warga](https://user-images.githubusercontent.com/13193883/81092457-d0a39000-8f2a-11ea-9a2f-4180092587a1.png)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.05-pasca
| Versi PHP        | 
| System operasi   |

**Comment by ericksuryadinata** [comment]
Saya coba upload file JPEG bisa

**Comment by af-lazuardi** [comment]
okay, berarti specific case saja ini ya, beberapa ada yang bisa dan gagal. nanti tak coba dengan image yang lainnya

**Comment by afa28** [comment]
Apa masih bermasalah???

**Comment by balongbesuk** [comment]
biasanya file conversi akan bermasalah seperti ini

kalau gagal coba edit pakai paint > save as jpg / jpeg lagi, test upload,

**Comment by mizwaruddin** [comment]
@afa28 saya coba di web demo lancar.

**Comment by afa28** [comment]
Silahkan reopen issue ini jika masih bermasalah.
