### ISSUE TITLE
Widget Aparatur Desa

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#3010]
### Bagaimana alurnya sampai muncul masalah?
1. Poto yang muncul diwidget Aparatur juga yang statusnya tidak aktif
2. Urutan Poto yang muncul tdk sesuai dengan urutan yang yang ada di menu pemerintahan Desa

### Seperti apa yang diharapkan?
1. Poto Aparatur yang aktif saja
2. urutan poto yang muncul sesuai urutan yang ada di menu pemerintahan desa

### Apa yang terjadi?
Poto yang muncul juga poto aparatur yang statusnya tidak aktif dan urutan poto yang muncul tdk sesuai dengan urutannya

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.05 pasca
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master`.
