### ISSUE TITLE
Isi field yang diedit beruah saat edit lokasi penduduk

### ISSUE THREAD

**Issue by mizwaruddin** [OpenSID/OpenSID#3018]
### Bagaimana alurnya sampai muncul masalah?
Kronologi: Saat ubah biodata penduduk (mis: KTP semula "BELUM" diganti "KTP-EL") kemudian saya lanjutkan edit lokasi tempat tinggal penduduk (peta). Setelah saya isikan titik koordinat saya simpan, saya lihat field KTP-EL yg sdh sya ubah sebelumnya kembali ke "Pilih KTP El". Hal ini juga erlaku untuk field2 yh lain.

### Seperti apa yang diharapkan?
Perubahan2 yg sudah dilakukan tidak berubah setelah menyimpan lokasi tempat tinggal penduduk (peta).

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.05-pasca
| Versi PHP        | 
| System operasi   |

**Comment by ericksuryadinata** [comment]
Ini dikarenakan sudah pindah halaman, jadi perubahan tidak disimpan.

solusi untuk user pilih tempat tinggal dahulu

solusi teknis ajax save on change

menunggu komentar dari pak @eddieridwan untuk dipertimbangkan

**Comment by mizwaruddin** [comment]
Saat ini sya lakukan ubah peta dulu baru data yg lain.

**Comment by afa28** [comment]
Kalau hanya untuk pilih lokasi bisa pakai modal agar berada di form yg sama. 

#saran_untuk_kedepannya

**Comment by afa28** [comment]
#2659
