### ISSUE TITLE
Memunculkan Tombol Pada Foto Aparatur Desa

### ISSUE THREAD

**Issue by gampongbarabung** [OpenSID/OpenSID#3021]
### Bagaimana alurnya sampai muncul masalah?
Sekarang pada widget aparatur desa foto perangkat desanya pindah sendiri tetapi tidak bisa mundur kebelakang. Jika ada 10 perangkat desa, kita kelewatan melihat foto kepala desanya karna di no 1 biasanya kepala desa, untuk dapat melihatnya harus menunggu sampai ulang lagi ke foto no 1. Mungkin bisa dibuatkan tombol pindah kiri dan kanan Seperti pada gambar diatas yang sudah dikolom kuning.

### Seperti apa yang diharapkan?
Terdapat Tombol Next dan Back pada Slide Widget Foto Aparatur Desa Seperti Gambar Dibawah Ini

### Apa yang terjadi?
![81169671-6ab71700-8fc3-11ea-8100-110081ecc099](https://user-images.githubusercontent.com/60224596/81170569-1dd44000-8fc5-11ea-870b-3edaf296c8fa.png)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.05-pasca
| Versi PHP        | 
| System operasi   |

**Comment by ericksuryadinata** [comment]
Tema yang dipakai yang mana ya pak ?

**Comment by gampongbarabung** [comment]
Tema Cosmos terbaru pak, saya lihat di tema natra juga tidak ada tombol back dan next nya pada slide widget aparatur desa

**Comment by ericksuryadinata** [comment]
Mungkin akan muncul di release berikutnya pak, #3010

**Comment by gampongbarabung** [comment]
Ditunggu pak 🙏

**Comment by fusionid** [comment]
![aparat_navi](https://user-images.githubusercontent.com/10391199/81194183-87b11180-8fe6-11ea-986d-4dd38e81a114.PNG)

**Comment by gampongbarabung** [comment]
Cocok pak

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3024
