### ISSUE TITLE
Fitur Cek NIK penerima Bantuan 

### ISSUE THREAD

**Issue by equeza** [OpenSID/OpenSID#3023]
dear, 
halo..... saya perangkat desa yang sedang mencoba untuk menggunakan OpenSID sebagai SYstem Informasi Desa. so far OpenSID bagus banget. berikut 2 hal yang saya usulkan untuk dihadirkan fitur di release yang akan datang.
1. Buatkan fitur untuk mengecek tiap2 NIK sudah mendapatkan bantuan apa saja. misal kita ketik NIK maka akan muncul Data NIK tersebut sudah mendapatkan bantuan apa saja. memudahkan pemantauan dan menhindari bantuan ganda karena kesengajaan oknum pamong.
2. Tambahkan pembuatan SK langsung ( sementara yang saya dapati untuk SK hanya sebatas pengarsipan )

saya rasa itu dulu saran saya, semoga bisa dihadirkan dengan cepat, karena sesuai dengan kebutuhan desa kami dan desa-desa lainya. terimakasih

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.0.04
| Versi PHP        | 7.45
| System operasi   | W10

**Comment by Nurhidayat29** [comment]
1. dapat dilihat di daftar bantuan dan juga layanan mandiri
2. Silahkan Donasi agar cepat terealisasikan usulan
mungking sementara itu jawabannya

**Comment by afa28** [comment]
Mungkin ditambahkan pada pencarian spesifik ????

**Comment by afa28** [comment]
1. saat menambah peserta bantuan akan difilter penduduk yg sudah menerima bantuan pd program bantuan yg sama, dan akan ditampilkan program bantuan yg telah diterima oleh peserta tersebut.

**Comment by mizwaruddin** [comment]
@afa28 sudah bisa dicek melalui layanan mandiri.

**Comment by afa28** [comment]
> @afa28 sudah bisa dicek melalui layanan mandiri.

Yg dimaksud di issue ini saat menginput peserta program bantuan dan sudah ada di versi terbaru.

`saat menambah peserta bantuan akan difilter penduduk yg sudah menerima bantuan pd program bantuan yg sama, dan akan ditampilkan program bantuan yg telah diterima oleh peserta tersebut.`
