### ISSUE TITLE
Perlu ditambahkan form email di setiap KK

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#3025]
### Bagaimana alurnya sampai muncul masalah?
Sekitar 2 minggu yang lalu, dalam proses pembuatan Dokumen Adminduk sekarang dibutuhkan 
1. Email salah satu diantara anggota keluarga
2. No HP
baru Permohonan Dokumen Adminduk bisa di proses
sementara ini untuk field Nomor HP sudah ada sedangkan untuk email belum ada
ini merupakan aturan baru dari kementerian dalam negeri dalam hal ini DInas DUKCAPIL dan salah satu manfaatnya masyarakat kedepannya bisa cetak sendiri dokumen adminduk secara mandiri
### Seperti apa yang diharapkan?
perlu ditambahkan Field untuk EMAIL 

### Apa yang terjadi?
Belum ada tempat mengisi email masyarakat

### Informasi tambahan 
1. Untuk Pengajuan Dokumen Adminduk wajib harus ada nomor HP
2. untuk email bisa menggunkan email Desa
kemarin kami sdh engajukan permohonan dokumen adminduk dan berikut saya lampirkan model notifikasi dari dinas dukcapil : 
![capil1](https://user-images.githubusercontent.com/25834335/81207379-0cf4f000-9000-11ea-8bfd-a607d6c78d26.jpg)
![capil2](https://user-images.githubusercontent.com/25834335/81207390-11210d80-9000-11ea-9055-71e07a353aca.jpg)
![capil3](https://user-images.githubusercontent.com/25834335/81207404-154d2b00-9000-11ea-8ef1-3a8ab4baa2f2.jpg)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by Nurhidayat29** [comment]
![IMG_20200509_154703](https://user-images.githubusercontent.com/51182125/81468990-d93ae580-920c-11ea-8819-c658902becfe.jpg)
![IMG_20200509_154727](https://user-images.githubusercontent.com/51182125/81469000-e2c44d80-920c-11ea-9f11-40e4b85d7698.jpg)

**Comment by MUHAMMADRANGSEL** [comment]
Mantap bung

Pada tanggal Sab, 9 Mei 2020 16.51, Nur Hidayat <notifications@github.com>
menulis:

**Comment by Nurhidayat29** [comment]
Apakh seperti yg dimaksud bung @MUHAMMADRANGSEL. Kalau iya saya akan kirim PRnya

**Comment by MUHAMMADRANGSEL** [comment]
Pas bung

Pada tanggal Sab, 9 Mei 2020 21.32, Nur Hidayat <notifications@github.com>
menulis:

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3048
