### ISSUE TITLE
Pencarian peserta program bantuan keluarga menggunakan Istri dalam kartu keluarga

### ISSUE THREAD

**Issue by afri18** [OpenSID/OpenSID#3027]
### Bagaimana alurnya sampai muncul masalah?
Saat ini sebagian besar bantuan untuk Keluarga/Rumah Tangga sasarannya adalah Istri dalam starus Kartu Keluarga, Kecuali Kepala Keluarga langsung Perempuan

### Seperti apa yang diharapkan?
Mohon Filter untuk Kepala Keluarga ditambahkan juga status istri dalam Kartu Keluarga, Jadi nantinya data yang muncul adalah warga yang status dalam Keluarganya > Kepala Keluarga dan Istri
![image](https://user-images.githubusercontent.com/6611881/81251284-16f11000-904d-11ea-8ade-797d063f9532.png)

### Apa yang terjadi?
Tidak bisa mengisi data bantuan yang sasarannya Keluarga sedangkan sasarannya/statusnya Istri dalam Kartu Keluarga

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.05
| Versi PHP        | 
| System operasi   |

**Comment by isnantomch** [comment]
Ini juga menjadi catatan penting karena kesulitan saat input penerima bantuan jika hanya berdasarkan kk. Mungkin bisa dikolaborasikan dengan https://github.com/OpenSID/OpenSID/issues/3069#issue-618159029

**Comment by mizwaruddin** [comment]
Klo saya lebih condong penerima ttp kepala keluarga. Hanya saja pada identitas kartu perli ditambahkan search NIK/Nama penduduk.

**Comment by afri18** [comment]
@mizwaruddin akan kerja dua kali nantinya, merubah data di kartu penerima, sesuai data asli Kemensos (sasaran), Lagi pula tampilan di web nantinya kepala keluarga bukan sasarannya, akibatnya data tidak sama dengan kemensos
Jadi walau sasaran KELUARGA namun dalam entri (pencarian) ada data Kepala Keluarga dan Istrinya

**Comment by mizwaruddin** [comment]
Saat ini yg ditampilkan di web kepala keluarga krn inputnya kepala keluarga. Tp klo bisa disiasati yg diinput istri/anak/kepala keluarga tp yg tampil di web kepala keluarga akan lbh cepat dlm penginputan peserta bantuan.

**Comment by afa28** [comment]
Solusi dari saya, perjelas sasaran(spesifik) jika jenis keluarga/kelompok. Jadi saat input data peserta otomatis mengikuti pengaturan dari program yg dibuat.

Misal program bantuan yg sasarannya adalah keluarga (sasaran spesifk adalah istri). Maka tinggal dipilih saja spesifik sasarannya.

Jadi hasilnya tetap menampilkan kepala keluarga namun dengan sasaran spesifik yakni istri.

**Comment by mizwaruddin** [comment]
Dalam satu program (mis: PKH), sasaran bisa kepala keluarga, istri, anak, famili.

**Comment by afri18** [comment]
@afa28 saat ini program pemerintah walaupun Kelurga tapi penerimanya adalah istri, kecuali Kepala Keluarganya memang perempuan 
contoh Program Keluarga Harapan dan BPNT itu sangat disarankan penerimanya adalah perempuan, kalau kepala keluarga perempuan nggak masalah, tapi bila kepala keluarga laki-laki berarti penerimnya istri
Jadi biar tidak kerja dua kali alangkah baiknya dalam pencarian bantuan keluarga adalah yang statusnya Kepala Kelurga dan Istri jadi semua kepala keluarga dan penduduk berstatus istri jadinya tergambar :
No KK - Nama KK
No KK - Nama Istri

**Comment by afa28** [comment]
> Dalam satu program (mis: PKH), sasaran bisa kepala keluarga, istri, anak, famili.

Tp ini hanya salah satu kan pak @mizwaruddin ??? Jadi, pd program ditentukan spesifik penerimanaya. Jika tdk ada/sasaran spesisiknya tdk ada maka otomatik yg terpilih adalah kepala keluarga.

**Comment by afa28** [comment]
> @afa28 saat ini program pemerintah walaupun Kelurga tapi penerimanya adalah istri, kecuali Kepala Keluarganya memang perempuan
> contoh Program Keluarga Harapan dan BPNT itu sangat disarankan penerimanya adalah perempuan, kalau kepala keluarga perempuan nggak masalah, tapi bila kepala keluarga laki-laki berarti penerimnya istri
> Jadi biar tidak kerja dua kali alangkah baiknya dalam pencarian bantuan keluarga adalah yang statusnya Kepala Kelurga dan Istri jadi semua kepala keluarga dan penduduk berstatus istri jadinya tergambar :
> No KK - Nama KK
> No KK - Nama Istri

Ya dr itu, mungkin perlu tambahan settingan sasararan spesifik saat buat program bantuannya agar di form nantinya otomatis muncul data sesuai yg di inginkan.

**Comment by mizwaruddin** [comment]
Betul Mas @afa28. Monggo dilanjut. Sementara utk identitas di kartu sya msih copas dr data penduduk.

**Comment by afri18** [comment]
artinya data yang ditampilkan tidak sama dengan yg ada di SIKNG atau kemensos, akan banyak pertanyaan.
Padahal seharusnya data yg ditampilkan di halaman web adalah penerima yg sama data nya di kemensos
jadi kalau ada yg memeriksa tidak banyak menimbulkan PERTANYAAN

**Comment by afa28** [comment]
> Betul Mas @afa28. Monggo dilanjut. Sementara utk identitas di kartu sya msih copas dr data penduduk.
> Tp harapan saya nama kepala keluarga ttp muncul krn mrk lbh mudah dikenali dibandingkan istri/anak/famili.

Klw sasarannya KK nama KK tetap akan muncul, yg jadi sasaran spesifik adalah peserta bantuan apakah (KK itu sendiri, istri atau lainnya)

**Comment by afa28** [comment]
> artinya data yang ditampilkan tidak sama dengan yg ada di SIKNG atau kemensos, akan banyak pertanyaan.
> Padahal seharusnya data yg ditampilkan di halaman web adalah penerima yg sama data nya di kemensos
> jadi kalau ada yg memeriksa tidak banyak menimbulkan PERTANYAAN

Pengaturan program bantuannya di awal disesuaikan terlebih dlu sasaran, dan sasaran spesifiknya(untuk KK) sesuai, dengan misal yg ada di SIKNG. Kalau ditentukan seperti pada https://github.com/OpenSID/OpenSID/issues/3027#issuecomment-638715695 akan menjadi statis, siapa tau ada bantuan KK yg terima itu anaknya. Dengan adanya sasaran spesifik, bisa menjadi lebih dinamis jika ada perubahan dan bisa disesuaikan.

Bisa dibantu pak @eddieridwan bgmna bagusnya.

**Comment by mizwaruddin** [comment]
Misal form utk input bantuan dibalik gmn Mas @afa28 ? Yg semula Kepala Keluarga di atas, skrg dibalik identitas kartu (dibuat spesifik anak/istri/famili) kemudian setelah dipilih data yg dimaksud muncul data kepala keluarganya (nomor KK, nik, nama).

**Comment by afri18** [comment]
> > artinya data yang ditampilkan tidak sama dengan yg ada di SIKNG atau kemensos, akan banyak pertanyaan.
> > Padahal seharusnya data yg ditampilkan di halaman web adalah penerima yg sama data nya di kemensos
> > jadi kalau ada yg memeriksa tidak banyak menimbulkan PERTANYAAN
> 
> Pengaturan program bantuannya di awal disesuaikan terlebih dlu sasaran, dan sasaran spesifiknya(untuk KK) sesuai, dengan misal yg ada di SIKNG. Kalau ditentukan seperti pada [#3027 (comment)](https://github.com/OpenSID/OpenSID/issues/3027#issuecomment-638715695) akan menjadi statis, siapa tau ada bantuan KK yg terima itu anaknya. Dengan adanya sasaran spesifik, bisa menjadi lebih dinamis jika ada perubahan dan bisa disesuaikan.
> 
> Bisa dibantu pak @eddieridwan bgmna bagusnya.

tidak ada penerima bantuan untuk kelurga itu anak, famili atau kedudukan lain dalam Kartu Keluarga, saat ini semua bantuan Kelurga itu diwajibkan penerima adalah perempuan, artinya seseorang yg kedudukannya ISTRI atau Kepala Kelurga, Kepala Kelurga Perempuan karna JANDA biasanya

**Comment by mizwaruddin** [comment]
Di desa saya masih ada pengurus bantuan (tertera di kartu) anak laki2, bahkan anak usia sekolah.

**Comment by afri18** [comment]
> Di desa saya masih ada pengurus bantuan (tertera di kartu) Program Sembako (BPNT) anak laki2, bahkan anak usia sekolah.

Masa anak belum wajib KTP dapat Bpnt ?? Gimana pendataan nya?? Kan mesti buka rekening bank ??? Baru tau ada Bpnt penerima anak, kemana orang tuanya ???

**Comment by mizwaruddin** [comment]
Kayak g tahu birokrasi ja, Bang. 
Nyatanya memang ada dan bisa mendapatkan rekening/kartu KKS.

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3144
