### ISSUE TITLE
Penambahan Sub Sub Menu Pada Menu Web Opensid

### ISSUE THREAD

**Issue by upperhead93** [OpenSID/OpenSID#3028]
### Bagaimana alurnya sampai muncul masalah?
Penampilan sub menu di menu website opensid perlu sub menu lanjutan. Hal ini perlu untuk membuat kategori lebih rinci untuk setiap topik dan/atau sub menu bersangkutan.

### Seperti apa yang diharapkan?
contoh sub sub menu yang diharapkan seperti ini:

Keuangan
- Tahun 2020
    -  APB Desa Tahun 2020
    -  Laporan Realiasasi Tahun 2020
    -  Laporan Pertanggungjawaban Realisasi.....
- Tahun 2019
    -  APB Desa Tahun 2019
    dst.....

### Apa yang terjadi?
keterbatasan menu web hanya pada sub menu menyebabkan kita tidak dapat menyediakan informasi lengkap khususnya pada bidang keuangan dan produk hukum yang mana keduanya perlu dikategorikan lebih rinci berdasarkan tahun diterbitkan.

### Informasi tambahan 
sub sub menu jika memungkinkan mencakup pada menu statis dan menu dinamis.
| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
Duplicate issue https://github.com/OpenSID/OpenSID/issues/1785
