### ISSUE TITLE
Bug tema hadakewa

### ISSUE THREAD

**Issue by ericksuryadinata** [OpenSID/OpenSID#3031]
### Bagaimana alurnya sampai muncul masalah?

![Screenshot_2020-05-07_18-56-02](https://user-images.githubusercontent.com/20630687/81291787-aa99ff00-9094-11ea-885a-76916748ca67.png)

### Seperti apa yang diharapkan?
Seharusnya kebawah, dibawah banner

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.5-pasca
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sdh dicommit melalui PR #3032
