### ISSUE TITLE
Tidak bisa memanggil nama dalam pembuatan surat OpenSID Akhir April 2020

### ISSUE THREAD

**Issue by cepedaknews** [OpenSID/OpenSID#3038]
Butuh bantuan teman2 semua saya ngk bisa input nama pada pembuatan surat
/index.php/surat/list_penduduk_ajax

Error Number: 1064

You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '-25, 25' at line 5

SELECT DISTINCT `u`.`id`, `nik`, `u`.`tag_id_card`, `nama`, `w`.`dusun`, `w`.`rw`, `w`.`rt`, `u`.`sex` FROM `tweb_penduduk` `u` LEFT JOIN `tweb_wil_clusterdesa` `w` ON `u`.`id_cluster` = `w`.`id` WHERE `status_dasar` = 1 LIMIT -25, 25

Filename: models/Surat_model.php

Line Number: 103

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.05
| Versi PHP        | 7.2

**Comment by cepedaknews** [comment]
tampilanya seperti ini
![333434apotik](https://user-images.githubusercontent.com/46637149/81370250-e5487980-911e-11ea-9f09-9089344d181f.jpg)

**Comment by Nurhidayat29** [comment]
di demo lancar, apakah sudah update?

**Comment by afa28** [comment]
@dikisiswanto , bisa lampirkan solusi disini yg pernah di share di telegram???

**Comment by dikisiswanto** [comment]
Tanda slash di akhir url perlu ditambahkan bung @afa28

**Comment by mizwaruddin** [comment]
@afa28 sudah tidak ada masalah.
