### ISSUE TITLE
Error mengakses api.kawalcorona.com

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#3039]
Error mengakses api.kawalcorono.com sehingga gagal menampilkan status Covid-19:

<img width="1388" alt="cors-policy-error" src="https://user-images.githubusercontent.com/249563/81393139-2a8e9a80-9163-11ea-9584-5ce0207b258b.png">
<img width="1388" alt="cors-policy-error-2" src="https://user-images.githubusercontent.com/249563/81393133-25315000-9163-11ea-957c-f8f33d5c194d.png">

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.05-pasca
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Lihat https://thisinterestsme.com/no-access-control-allow-origin/ dan sumber lain. Sepertinya tidak bisa akses melalui ajax langsung kalau sasaran tidak mengizinkan. Jadi satu solusi mungkin panggil PHP yg membuat GET request ke api dan kemudian kembalikan ke ajax.

**Comment by dikisiswanto** [comment]
API kawalcorona.com sekarang nampaknya memang lebih ketat, kemungkinan karena yang melakukan hit ke API nya cukup banyak dan menyebabkan sebagian endpoint-nya menjadi down.

Seperti gambar berikut:
![image](https://user-images.githubusercontent.com/22239074/81451381-f6dd6000-91b6-11ea-8d39-e853ad1b72fc.png)

Usul saya gunakan sumber API lain, seperti https://indonesia-covid-19.mathdro.id/api (yang dilihat dari kode sumbernya merujuk pada data yang sama, seperti yang digunakan oleh kawalcorona)

Tema cosmos kini juga sudah menerapkan API dari https://indonesia-covid-19.mathdro.id/api dan sejauh ini tidak mengalami masalah CORS.

- [https://www.desakalibuaya.com/](https://www.desakalibuaya.com/)
- [https://barabung.desa.id/](https://barabung.desa.id/)

**Comment by eddieridwan** [comment]
Boleh, solusi itu juga sudah diterapkan bung @fusionid di PetaSID. Silakan kalau ada yg sempat terapkan untuk panel Status Covid. Tapi juga ada baiknya kita temukan solusi untuk bypass CORS seperti di https://thisinterestsme.com/no-access-control-allow-origin/.

**Comment by eddieridwan** [comment]
Sudah dicommit ke `master`. Berhasil bypass CORS menggunakan curl. Tapi memang `api.kawalcorona.com` berat. Dan kalau ada yg sempat bisa pindah ke `https://indonesia-covid-19.mathdro.id/api`.

**Comment by fusionid** [comment]
Setelah bypass CORS menggunakan curl, loading data dari api.kawalcorona.com relatif lebih cepat dari sebelumnya dan tidak errr, sepertinya tidak perlu pindah dulu ke indonesia-covid-19.mathdro.id/api.
