### ISSUE TITLE
Tidak bisa tampilkan peta wilayah desa

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#3041]
### Bagaimana alurnya sampai muncul masalah?
Coba restore data dari https://demo.opensid.my.id per tgl 9 May 2020, terlampir.
Perhatikan bahwa peta wilayah desa (Info Desa > Identitas Desa > Peta Wilayah) sudah terisi dengan data yg diimpor (?). Juga lokasi kantor desa sudah terisi.
<img width="1388" alt="peta-wilayah-desa" src="https://user-images.githubusercontent.com/249563/81443561-f776f600-91b8-11ea-89a9-7be63a721da1.png">

Sekarang coba tampilkan peta desa di Pemetaan > Peta atau di PetaSID.

### Seperti apa yang diharapkan?
Peta desa tampil.

### Apa yang terjadi?
Yang tampil hanya kantor desa. Tetapi peta desa tidak tampil. 

### Informasi tambahan 

[opensidm_demo.sql.zip](https://github.com/OpenSID/OpenSID/files/4601234/opensidm_demo.sql.zip)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | v20.05-pasca
| Versi PHP        | 
| System operasi   |

**Comment by mizwaruddin** [comment]
@afa28 saya coba di website desa saya normal.

**Comment by afa28** [comment]
![1111](https://user-images.githubusercontent.com/57283157/121675436-fadc5f80-cae5-11eb-8b5c-ea25c51805ac.png)

Sy coba impor tdk ada masalah.

Untuk issue ini perlu di cek ulang karena akan ada perubahan struktur kolom path di PR https://github.com/OpenSID/premium/pull/248. Silahkan di buka kembali jika masih terjadi maslah.
