### ISSUE TITLE
Data bantuan sasaran keluarga pd layanan mandiri

### ISSUE THREAD

**Issue by RomziJazz** [OpenSID/OpenSID#3044]
Dear
Sekarang sudah musimnya bantuan dari pemerintah akibat Covid ini, ada beberapa bantuan yang tidak diperbolehkan ganda dalam satu KK (Keluarga). Nah disini saya usulkan:

1. Perlu panambahan daftar penerima bantuan satu keluarga yang ditampilkan dalam layanan mandiri, saat ini yang tampil hanya untuk perorangan saja.
2. **Jika Bisa**  dalam form pengisian daftar bantuan yang sasaran pesertanya Keluarga/KK, NIK (Identitas di Kartu) Peserta buatkan yang langsung merujuk pada salah satu anggota keluarganya.

Suwun.

**Comment by isnantomch** [comment]
Mungkin bisa kombinasikan dengan ini :
https://github.com/OpenSID/OpenSID/issues/3069#issue-618159029

**Comment by afa28** [comment]
Point 2 sudah ada dimaster

**Comment by afa28** [comment]
Silahkan buat issue terpisah untuk point 1.

**Comment by afa28** [comment]
Sudah di `master`
