### ISSUE TITLE
Font Size pada visual editor

### ISSUE THREAD

**Issue by keylaeff** [OpenSID/OpenSID#305]
Mohon untuk font size pada visual editor bisa diperbesar, agar penulis/editor usia tua maupun mata tidak normal tidak mengalami kesulitan dalam menulis/mengedit artikel.

saya sudah coba untuk merubah font-size pada halaman editor, namun ketika dipublish. tampilan di front-end nya mengikuti font-size yang telah di setting pada halaman editor. tentunya nanti font size pada artikel satu dengan yang lain akan berbeda. (font size yang dipakai tiap editor pun berbeda pula, tidak konsisten)

**Comment by metalab25** [comment]
sekedar jawab aja untuk penerapannya oleh bung eddie

edit di
/assets/tiny_mce/themes/advanced/skins/o2k7/content.css
ubah font-size nya

**Comment by hadyanwijaya** [comment]
saya suda PR tinymce 4 plus filemanager, jika sudah dimerge pengaturan ukuran font bisa langsung dari text editor tinymce

**Comment by afa28** [comment]
Untuk tymce sdah di-update, silahkan di cek ulang. Jika masih tdk sesuai, silahkan reopen issue ini.
