### ISSUE TITLE
Update Otomatis Data COVID-19 di Desa

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#3050]
### Bagaimana alurnya sampai muncul masalah?
Angka pada Status ODR tidak berubah walau sudah lebih dari 14 hari.

![covid](https://user-images.githubusercontent.com/46939846/81608425-7447e100-9400-11ea-968a-7bd6b4796d28.png)

### Seperti apa yang diharapkan?
Setelah 14 hari, jika suatu warga yang berstatus ODR tersebut tidak ada peningkatan status, maka untuk ODR dapat otomatis dibuat Nol

**Comment by af-lazuardi** [comment]
Okay. Ini berarti ditambahi skenario untuk ubah status covid ya. Dan juga untuk mengarsipkan data peserta yang selesai masa isolasi.

**Comment by andifahruddinakas** [comment]
Silahkan dibuka kembali jika masih terjadi masalah, gunakan versi terbaru untuk pengecekan.
