### ISSUE TITLE
Statistik Bantuan Agar Bisa Menampilkan Nama Peserta dan Alamat

### ISSUE THREAD

**Issue by WAHYUDIK** [OpenSID/OpenSID#3052]
### Bagaimana alurnya sampai muncul masalah?
Setelah menambah jenis bantuan dan peserta bantuan, data yang bisa ditampilkan hanya sebatas jumlah saja.
### Seperti apa yang diharapkan?
agar bisa juga menampilkan nama beserta alamat saja

### Apa yang terjadi?
sampai saat ini bantuan yang ditampilkan hanya sebatas statistik saja, sedangkan untuk membantu terus menjaga keterbukaan informasi kepada publik desa dituntut juga untuk menampilkan beserta nama lengkapnya, 

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Daftar penerima bantuan di web sdh dicommit ke `master` melalui PR #3062
