### ISSUE TITLE
Akses URL http://demo.opensid.my.id/first/agenda

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#3056]
### Bagaimana alurnya sampai muncul masalah?
Akses URL http://demo.opensid.my.id/first/agenda
Muncul halaman yang tidak berarti.
![image](https://user-images.githubusercontent.com/46939846/81748084-7333b400-94d3-11ea-8b19-7de5aadd40cd.png)

### Seperti apa yang diharapkan?
Adanya informasi terkait URL Agenda. jika tidak ada bisa dibuat 404 saja

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3059
