### ISSUE TITLE
Statistik Bantuan

### ISSUE THREAD

**Issue by afri18** [OpenSID/OpenSID#3060]
### Bagaimana alurnya sampai muncul masalah?
banyaknya yg bertanya siapa penerima bantuan

### Seperti apa yang diharapkan?
bisa menampilkan penerima bantuan terkait hanya berupa Nama dan Alamat aja
![image](https://user-images.githubusercontent.com/6611881/81771528-6d5ac480-950d-11ea-862f-7174e21407cf.png)

### Apa yang terjadi?
tidak taunya pembaca siapa penerima bantuan

### Informasi tambahan 
agar transparasi terwujud

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.05_pasca 12-05-2020
| Versi PHP        | 7.2
| System operasi   |

**Comment by ariandii** [comment]
Menurut saya mungkin bisa tampilkan data per RT.

**Comment by eddieridwan** [comment]
Statistik di web sudah dicommit melalui PR #3062
