### ISSUE TITLE
Input GANDA Program Bantuan

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#3061]
### Bagaimana alurnya sampai muncul masalah?
Mungkin karena lelah input, saat cek akhir, ada KK yang terinput 2 kali.

### Seperti apa yang diharapkan?
Seharusnya data pada kolom input No.KK atau Nama Kepala Keluarga tidak perlu muncul jika sudah pernah diinput sebelumnya.

### Apa yang terjadi?
Supaya tidak berlebih jumlah akhirnya.

**Comment by afa28** [comment]
> ### Bagaimana alurnya sampai muncul masalah?
> Mungkin karena lelah input, saat cek akhir, ada KK yang terinput 2 kali.
> 
> ![image](https://user-images.githubusercontent.com/46939846/81791226-a48e9d00-9530-11ea-9b06-a8d44aa30a0c.png)
> 
> ### Seperti apa yang diharapkan?
> Seharusnya data pada kolom input No.KK atau Nama Kepala Keluarga tidak perlu muncul jika sudah pernah diinput sebelumnya.
> 
> ### Apa yang terjadi?
> Supaya tidak berlebih jumlah akhirnya.

Kayaknya sudah ada filter agar tdk meload data jika sudah ada sebelumnya, apa masih ada yg terlewat :3

Tp sy test , sudah jalan sebagaimana mestinya.

**Comment by eddieridwan** [comment]
Sepertinya masalah ini sudah tidak ditemukan lagi di master. Saya tutup. Kalau masih bermasalah silakan buka kembali, dengan melampirkan tangkapan layar dan rincian langkah. Untuk memudahkan pelacakan, harap lakukan di https://demo.opensid.my.id
