### ISSUE TITLE
Tambahkan Cetak/Print Pada Modul

### ISSUE THREAD

**Issue by afa28** [OpenSID/OpenSID#3063]
### Bagaimana alurnya sampai muncul masalah?
Saat ini belum ada fitur cetak/print pd beberapa modul yg bisa dibilang fitur standar yg mungkin harus ada untuk merekap sebuah data adminstrasi.
Berikut modul yg mungkin perlu ditambahkan fitur cetak/print:
1. Program bantuan
2. Data suplemen
3. (tambahkan jika ada modul yg perlu)

### Seperti apa yang diharapkan?
Adanya fitur cetak

### Apa yang terjadi?
Pengguna dapat langsung mencetak data

### Informasi tambahan 
Dibeeberapa modul sudah tersedia

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Cetak program bantuan sudah dicommit ke `master` melalui PR #3064

**Comment by eddieridwan** [comment]
Cetak rincian data suplemen sudah dicommit ke `master` melalui PR #3064.

Ok, issue ini ditutup. Kalau ada yg lain, mohon buat issue terpisah.
