### ISSUE TITLE
Hilangkan tombol pecah KK jika hanya terdapat 1 Anggota

### ISSUE THREAD

**Issue by afa28** [OpenSID/OpenSID#3066]
### Bagaimana alurnya sampai muncul masalah?
Pecak KK masih bisa dilakukan jika hanya 1 anggota saja, sehingga setelah melakukan pecah KK maka data (no_KK) masih tersimpan di database dan tdk ada tempat untuk view data tsb. Dan ketika ingin membuat KK dgn no_KK yg sama akan tdk bisa.

### Seperti apa yang diharapkan?
Jika KK hanya terdapat 1 anggota KK/blum di input anggota lainnya atau terjadi kesalahan input sebaiknya tombol pecah KK di hilangkan. Agar tdk melakukan pecah anggota KK, krn data anggota akan terhapus namu data KK tdk terhapus dan tdk bisa lg digunakan (no.KK).

Mungkin jg bisa ditambahkan tombol hapus #2976 (delete individu/tdk delete all), dgn catatan hanya digunakan jika terjadi kesalahan penambahan anggota keluarga (krn tdk ada disimpan di log)

### Apa yang terjadi?
Tdk dapat pecah KK untuk 1 anggota KK. Adapun jika salah input anggota KK, bisa menghapus terlebih dahulu KK tsb, dan input kembali anggotanya.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by mizwaruddin** [comment]
Bagaimana dengan kasus: ada janda tidak punya anak (KK sendirian) kemudian menikah lagi yg menyebabkan KK ikut suami? 
Jika tidak bisa pecah KK, lngkah apa yg harus dilakukan?

**Comment by afa28** [comment]
> Bagaimana dengan kasus: ada janda tidak punya anak (KK sendirian) kemudian menikah lagi yg menyebabkan KK ikut suami?
> Jika tidak bisa pecah KK, lngkah apa yg harus dilakukan?

Bisa dgn solusi :
1. Bisa ditambahkan tombol hapus #2976
2. Lakukan delete KK bukan pecah KK

Mungkin solusi untuk issue ini:
"Jika KK yg anggotanya cuma 1 org, pecah KK menjalankan 2 fungsi yakni: pecah KK dan hapus KK.

Issue ini muncul berdasarkan pembahasan pd issue #2976 yg berkaitan dgn anggota KK yg salah masuk. Misal, jika yg salah masuk 1 org dr jmlh anggota 1 org saat input/pilih saat pembuatan KK. Jika cara mengeluarkan 1 org tersebut dgn pecah KK maka no.KK yg digunakan sebelumnya tdk bisa lg digunakan krn tdk terhapus pd database.

**Comment by mizwaruddin** [comment]
Setuju bgt dg solusinya. Jika tdk ada anggota, maka nomor KK otomatis terhapus.

**Comment by balongbesuk** [comment]
KK Yang lama memang tidak terhapus guna mengisi kolom KK lama ketika ada keluarga bercerai / duda / janda menikah kembali maka no kk otomatis tidak dimiliki oleh siapapun dan mereka akan diberikan no kk baru, 

praktik sekarang sudah benar memang seperti itu tidak perlu dirubah

**Comment by balongbesuk** [comment]
jika salah memasukkan no kk bisa dihapus di menu keluarga > drop down kk kosong, hapus disitu

**Comment by afa28** [comment]
> KK Yang lama memang tidak terhapus guna mengisi kolom KK lama ketika ada keluarga bercerai / duda / janda menikah kembali maka no kk otomatis tidak dimiliki oleh siapapun dan mereka akan diberikan no kk baru,
> 
> praktik sekarang sudah benar memang seperti itu tidak perlu dirubah

Harusnya dilakukan dgn cara ini "jika salah memasukkan no kk bisa dihapus di menu keluarga > drop down kk kosong, hapus disitu"

Jika ada pengguna yg menghapus lewat pecah KK, maka log KK tsb tdk tersimpan dan datanya tdk terhapus (masih tertinggal di database). 

Secara praktik sudah benar jika mengikuti panduan(menggunakan hapus/hapus data terpilih). Yg mau dihindari penghapusan KK lewat pecah KK yg menyebabkan log KK tdk tersimpan jika anggota KK sudah kosong.

**Comment by mizwaruddin** [comment]
Bagaimana dg KK dg jml anggota 1 trus mati. Ketika diganti status dasarnya ke mati, pasti KK mnjadi kosong.

**Comment by balongbesuk** [comment]
apa yang pak mizwaruddin lakukan ketika ada penduduk mati/pindah? menghapusnya? atau mengubah status kependudukannya?

**Comment by mizwaruddin** [comment]
Saya ubah status dasarnya. 
Kemudian, utk KKnya bgmn? Sementara sya biarkan sehingga masuk dlm data KK tidak aktif.

**Comment by eddieridwan** [comment]
Sebaiknya semua kasus anggota KK tunggal, beserta aturannya didaftarkan dan diuraikan dulu, sebelum diterapkan. Supaya semua jelas bagaimana menggunakan modul Keluarga dengan benar.


Kasus | Apa langkahnya | Dasar peraturan|
---| ---|---|
Salah buat KK | Hapus KK dan tidak tercatat lagi di sistem. No KK bisa gunakan lagi. Yang dihapus hanya KK, penduduknya menjadi penduduk lepas. | |
Anggota tunggal (kepala keluarga) mati/pindah/hilang| Status dasar kepala keluarga menjadi mati/pindah/hilang. KK menjadi non-aktif secara otomatis. No. KK tidak bisa digunakan lagi.||
|Anggota tunggal wanita (kepala keluarga) menikah | Pecah KK, dan KK menjadi non-aktif. Log keluarga mencatat kepala keluarga terakhir. No. KK tidak bisa digunakan lagi. Anggota tadi menjadi penduduk lepas, dan bisa ikut KK baru.||
Dstnya.. |||

**Comment by eddieridwan** [comment]
@af-lazuardi , @mizwaruddin, @balongbesuk , mohon lihat komentar di atas.

**Comment by mizwaruddin** [comment]
Oke, Bang. 
Saya coba cari info ttg pencatatan KK.

**Comment by balongbesuk** [comment]
sebetulnya sy mau memperjelas kenapa harus menggunakan tombol hapus untuk penduduk dalam kk pada isue #2976 

karena pak eddie sudah turun tangan sendiri, sy sudahi pertanyaan tersebut diatas

**Comment by eddieridwan** [comment]
Penjelasan langkah penanganan kasus di atas telah ditambahkan ke panduan di https://github.com/OpenSID/OpenSID/wiki/Tanya-jawab-Keluarga.

Karena issue ini tidak memerlukan perubahan aplikasi, issue ini akan ditutup.
