### ISSUE TITLE
Tambahkan fitur filter program bantuan pada menu Keluarga dan penduduk

### ISSUE THREAD

**Issue by isnantomch** [OpenSID/OpenSID#3069]
Biasanya jenis bantuan itu ada yg sasarannya perorangan (penduduk) atau sararannya keluarga. Nah ketika admin sudah input data program bantuan baik itu perorangan atau keluarga diharapkan data ini bisa di filter di menu penduduk dan di menu keluarga. Sehingga admin/operator SID mampu menampilkan data keluarga/penduduk yg sudah mendapatkan bantuan dan yang belum sama sekali mendapatkan bantuan. 
Singkatnya menambahkan fitur filter program bantuan seperti halnya fitur filter Dusun, Jenis Kelamin, pada menu Data Keluarga. 
Jadi bisa ketahuan antara kk yg belum mendapatkan bantuan sama sekali dan yg sudah mendapatkan bantuan. 
![IMG_20200514_141128](https://user-images.githubusercontent.com/59205349/81929920-03781300-9612-11ea-8909-0154c2ad472b.JPG)

**Comment by boedyirh** [comment]
Feature yang bagus. Agar bisa mengidentiikasi duplikasi orang yang mendapatkan bantuan. Dan juga mengidentifikasi orang yang belum pernah dapat bantuan.

**Comment by afa28** [comment]
Filter bisa dilakukan melalui statistik > penerima bantuan. Walau saat ini data yg difilter masih miss dan perlu perbaikan.

**Comment by eddieridwan** [comment]
Sdh digabung ke `rilis-dev` melalui PR #3862
