### ISSUE TITLE
ketika merubah penerima bantuan terjadi duplicate

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#3070]
### Bagaimana alurnya sampai muncul masalah?
Menu Bantuan ==> Klik Program Bantuan Sasaran Keluarga maupun Penduduk==> klik ubah dan Simpan, terjadi duplicate data yang bersangkutan

### Seperti apa yang diharapkan?
Ketika merubah data penerima bantuan tidak terjadi duplicate data

### Apa yang terjadi?
Data Duplicate

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.05 Pasca
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Apakah terjadi juga di demo.opensid.my.id? Sepertinya normal.

**Comment by afa28** [comment]
Hampir sama #3061, tp beda penanganan.

Sy cek di Web demo, aman. Pd script sudah difilter agar tdk duplicate untuk 1 jenis program bantuan, apakah ada yg terlewat???

**Comment by MUHAMMADRANGSEL** [comment]
permasalahan ini masih terjadi ketika sedang melakukan pengimputan data apalagi dilakukan oleh 2 user berbeda

**Comment by eddieridwan** [comment]
Sepertinya masalah ini sudah tidak ditemukan lagi di `master`. Saya tutup. Kalau masih bermasalah silakan buka kembali, dengan melampirkan tangkapan layar dan rincian langkah. Untuk memudahkan pelacakan, harap lakukan di https://demo.opensid.my.id
