### ISSUE TITLE
Statistik Umur (Kategori) error 500

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#3073]
### Bagaimana alurnya sampai muncul masalah?
Ketika klik jumlah Data Kependudukan menurut Umur Kategori terjadi error 500
![1ok](https://user-images.githubusercontent.com/25834335/81967313-51f6d300-964d-11ea-8c34-226845c9b457.png)
![2OK](https://user-images.githubusercontent.com/25834335/81967318-53280000-964d-11ea-9c18-3b574c019751.png)

### Seperti apa yang diharapkan?
Data Tampil seperti di yang lain

### Apa yang terjadi?
error 500

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.05 pasca
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3081
