### ISSUE TITLE
Pencarian di Menu Bantuan terjadi eror

### ISSUE THREAD

**Issue by WAHYUDIK** [OpenSID/OpenSID#3077]
### Bagaimana alurnya sampai muncul masalah?
ketika kita melakukan pencarian data di menu bantuan>jenis bantuan terjadi eror

### Seperti apa yang diharapkan?
tidak terjadi eror pada saat pencarian

### Apa yang terjadi?
saat ini terjadi eror sehingga fitur pencarian tidak berfungsi

### Informasi tambahan 
![image](https://user-images.githubusercontent.com/31026980/82055346-8ec4d780-96ea-11ea-8f40-7250ea09442c.png)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
Mungkin sekalian diperbaiki masalah autocomplete nya, issuenya pernah di buat sama pak eddi

**Comment by WAHYUDIK** [comment]
apa mau dihapus juga ini mas?

**Comment by afa28** [comment]
Cuma tambahan pak

**Comment by WAHYUDIK** [comment]
owh..oke siap mas, ini lagi pak terkait filter di penerima bantuan, terjadi kesulitan pada saat jenis bantuannya banyak. terkadang tidak bisa menyortir jenis bantuan yg penerima sedikit

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master`.
Error muncul setelah commit 1e552030c13b8b72c5eb643ea96e988a9a0d4560
