### ISSUE TITLE
menambah peserta bantuan melalui ubah di menu keluarga terjadi data duplicate

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#3082]
### Bagaimana alurnya sampai muncul masalah?
Menu Kependudukan ==> Keluarga==> pilih salah satu keluarga klik ubah dan centang program peserta setelah itu simpan maka akan terjadi 
1. duplivate data bagi yang bersangkutan
![bantuan 1](https://user-images.githubusercontent.com/25834335/82126523-e729d100-97df-11ea-839e-92fa5aea2114.png)
![bantuan 2](https://user-images.githubusercontent.com/25834335/82126531-eee97580-97df-11ea-8548-c80686fe4cd5.png)
2.  di menu bantuan Identitas dikartu kosong
![bantuan 3](https://user-images.githubusercontent.com/25834335/82126566-33751100-97e0-11ea-89c2-e2d4bf58aaf9.png)

### Seperti apa yang diharapkan?
1. Sebaiknya menambahkan peserta melalui ubah di menu keluarga dihapus supaya fokus menambah peserta bantuan melalui menu bantuan
2. tidak terjadi duplicate data 

### Apa yang terjadi?
1. Jumlah KK akan bertambah menyebabkan data menjadi amburadul
2. Identitas di Kartu tidak terisi 

### Informasi tambahan 
saya coba di situs https://demo.opensid.my.id/program_bantuan/detail/1/6/1
| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.05 pasca
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
Mungkin aksinya yg di hapus, tp untuk informasi bantuan apa yg diterima pd KK tsb masih ada/ditampilkan

**Comment by MUHAMMADRANGSEL** [comment]
ya sebaiknya dihapus saja, dan sebagai tambahan kalau di hapus datanya di menu bantuan maka akan beerkurang juga duplicatenya, contoh 1 KK dicentang dapat 2 program bantuan, maka datanya akan jadi 2 seteelah di hapus disalah satu program nama yang bersangkutan di menu keluarga juga ikut terhapus dan kembali seperti biasa

**Comment by MUHAMMADRANGSEL** [comment]
dan juga ketika ketika 1 kepala kelurga mendapatkan 2 program bantuan yang berbeda seperti contoh Dapat Bantuan PKH dan Bantuan Sosial Tunai, maka data nya di menu keluarga menjadi bertambah. Jika dapat Bantuan 5 maka datanya di menu Keluarga Jadi 5. ini terjadi di situs demo juga
![image](https://user-images.githubusercontent.com/25834335/82127349-5a821180-97e5-11ea-9205-dfe0fe3f9ac4.png)

**Comment by eddieridwan** [comment]
Masalah data ganda di tampilan daftar keluarga sudah diperbaiki di `master`. 
Mengenai identitas kartu peserta kosong setelah menggunakan form ubah data keluarga, ini masalah terpisah, karena data identitas hanya bisa diisi di form peserta program bantuan. Kalau ingin dimasukkan dulu data 'default' sesuai dengan data kepala keluarga, silakan buat issue terpisah.
