### ISSUE TITLE
Cetak Langsung Data Covid19

### ISSUE THREAD

**Issue by afa28** [OpenSID/OpenSID#3083]
### Bagaimana alurnya sampai muncul masalah?
Saat ini belum ada fitur cetak/print pd beberapa modul yg bisa dibilang fitur standar yg mungkin harus ada untuk merekap sebuah data adminstrasi.
Berikut modul yg mungkin perlu ditambahkan fitur cetak/print:
1. Siaga Covid-19
2. (Tambahkan jika diperlukan)

### Seperti apa yang diharapkan?
Adanya fitur cetak

### Apa yang terjadi?
Pengguna dapat langsung mencetak data

### Informasi tambahan 
Dibeeberapa modul sudah tersedia

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3084
