### ISSUE TITLE
Input Surat Keluar Error 400

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#3088]
### Bagaimana alurnya sampai muncul masalah?
Sudah lakukan update terkini, clear cache, ganti browser, ganti komputer, ganti laptop, semua hasilnya sama, muncul error seperti di bawah ini.

![image](https://user-images.githubusercontent.com/46939846/82171543-dcf7f780-98f1-11ea-9c12-42725c8b9c9d.png)

### Seperti apa yang diharapkan?
Normal kembali

**Comment by eddieridwan** [comment]
Sudah dicommit ke `master`
