### ISSUE TITLE
Fitur PDF Viewer Di Postingan

### ISSUE THREAD

**Issue by Dedi83** [OpenSID/OpenSID#309]
mungkin di beberapa desa membutuhkan fitur ini termasuk saya.

**Comment by samsulmaarif** [comment]
karena fitur ini belum tersedia, sementara bisa dilakukan embed secara manual dengan cara diupload ke google drive [seperti di artikel ini](http://www.benschersten.com/blog/2014/04/embedding-a-pdf-from-drive-into-a-blog/).

**Comment by Dedi83** [comment]
mode embed kalo di offline bisa, tapi kalo saya pasang di online gak muncul

**Comment by MUHAMMADRANGSEL** [comment]
Mantap ini

**Comment by afa28** [comment]
Apakah ini masih bermasalah / masih diperlukan??? Kalau tdk, silahkan di close.

**Comment by afa28** [comment]
Duplicate issue https://github.com/OpenSID/OpenSID/issues/4211
