### ISSUE TITLE
Tampilkan / Tidak Tampilkan daftar peserta bantuan sasaran penduduk dan keluarga di Web.

### ISSUE THREAD

**Issue by hasap86** [OpenSID/OpenSID#3095]
### Bagaimana alurnya sampai muncul masalah?
Saat ini tidak ada pilihan untuk Tampilkan / Tidak Tampilkan daftar peserta bantuan sasaran penduduk dan keluarga di Web.

### Seperti apa yang diharapkan?
berikan pilihan untuk Tampilkan / Tidak Tampilkan daftar peserta bantuan sasaran penduduk dan keluarga di Web.

### Apa yang terjadi?
Tidak semua Desa memiliki kebijakan untuk Tampilkan daftar peserta bantuan sasaran penduduk dan keluarga di Web.

### Informasi tambahan 
Kebijakan setiap Desa berbeda, sebaiknya diberikan pilihan untuk bisa menampilkan atau tidak menampilkan daftar data peserta penerima bantuan.

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.05-pasca
| Versi PHP        | 7.2
| System operasi   | Linux

**Comment by Nurhidayat29** [comment]
saya rasa di admin web-menu-menu statis sdh membantu bung, jika memng tidak ingin menampikal cukup klik gmbok atau tidak perlu dibuat di menu statis

**Comment by hasap86** [comment]
> saya rasa di admin web-menu-menu statis sdh membantu bung, jika memng tidak ingin menampilkan cukup klik gmbok atau tidak perlu dibuat di menu statis

Perlu Statistiknya, fungsi menu ini kan awalnya tanpa daftar peserta juga, fungsi utamanya itu, jadi saran saya ada tampil / tidak tampilkan daftar penerimanya bukan aktif non aktif menu

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3100
