### ISSUE TITLE
Import Data Peserta Program Bantuan

### ISSUE THREAD

**Issue by hasap86** [OpenSID/OpenSID#3096]
### Bagaimana alurnya sampai muncul masalah?
Saat ini untuk input data Penerima Bantuan harus satu per satu

### Seperti apa yang diharapkan?
menggunakan import dari data Excel yang biasanya sudah tersedia

### Apa yang terjadi?
input satu persatu menjadi lama

### Informasi tambahan 
cukup import data NIK untuk Penduduk, KK untuk Keluarga, dan Nomor Peserta, karena data lainnya mengikuti dari database

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.05 pasca
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah ada yg melaporkan sebelumnya: https://github.com/OpenSID/OpenSID/issues/1278. Jangan lupa memeriksa issue yg sudah ada sebelum membuat yg baru. 

Yang diperlukan adalah contoh struktur data yg ingin diimpor. Usahakan supaya format data tersebut baku dan seragam dengan yg digunakan oleh desa lain. Masukkan info itu ke https://github.com/OpenSID/OpenSID/issues/1278, supaya issue ini bisa ditutup.

**Comment by hasap86** [comment]
baik issue saya close, dialihkan pembahasannya ke issue yg sudah ada.
