### ISSUE TITLE
Fitur On/Off di Daftar Program Bantuan

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#3099]
### Bagaimana alurnya sampai muncul masalah?
![program](https://user-images.githubusercontent.com/46939846/82440044-e5a12700-9ac5-11ea-83ec-619e2d449bd4.png)

Saat ini muncul pilihan status Aktif / Tidak Aktif saat edit bantuan program, namun walaupun dipilih "Tidak Aktif" saat kondisi Rentang Waktu Programnya masih besok / waktu kedepan. Walau disimpan, statsu tetap menunjukkan aktif.

Dan saat edit tanggal rentang waktu program ke waktu sebelum waktu saat ini, otomatis menjadi tidak aktif., Bisa dibilang fitur pillihan status aktif/tidak aktif saat ini tidak berfungsi.

### Seperti apa yang diharapkan?
Diharapkan adanya tombol On/Off di setiap program sebagai kontrol layanan informasi.
Walaupun Rentang waktu program sudah menunjukkan waktu lampau, namun jika diinginkan tetap dimunculkan pada website, bisa melalui tombol tersebut.

### Apa yang terjadi?
Hanya program yang di set ON yang tampil di halaman website.

**Comment by eddieridwan** [comment]
Status aktif/tidak-aktif untuk program bantuan digunakan untuk status apakah program bantuan ybs ditutup atau terbuka. 

Status yg diperlukan untuk issue ini berbeda dan terbatas apakah desa ingin menampilkan di web atau tidak. Sebaiknya dibuat status terpisah khusus untuk keperluan ini -- dan tidak digabung dengan status aktif/tidak-aktif. Mungkin buat kolom baru `web` untuk menandakan apakah akan dimuat di web atau tidak.

**Comment by afa28** [comment]
> Status aktif/tidak-aktif untuk program bantuan digunakan untuk status apakah program bantuan ybs ditutup atau terbuka.
> 
> Status yg diperlukan untuk issue ini berbeda dan terbatas apakah desa ingin menampilkan di web atau tidak. Sebaiknya dibuat status terpisah khusus untuk keperluan ini -- dan tidak digabung dengan status aktif/tidak-aktif. Mungkin buat kolom baru `web` untuk menandakan apakah akan dimuat di web atau tidak. Dan seperti diminta oleh pengguna di atas, status web ini berlaku bagi semua program termasuk yg tidak aktif sekalipun.

Apa PR #3131 ini tdk mewakili???

**Comment by eddieridwan** [comment]
Solusi bung @afa28 sdh bagus utk menangani masalah ini. Jadi issue ini ditutup.
