### ISSUE TITLE
Tambah Tombol "Simpan & Tambah" di Peserta Program Bantuan

### ISSUE THREAD

**Issue by hasap86** [OpenSID/OpenSID#3101]
### Bagaimana alurnya sampai muncul masalah?
Saat input Peserta Program Bantuan ketika Simpan data dialihkan ke halaman Daftar Peserta Program, sehingga ketika akan menginput peserta berikutnya harus klik lagi tombol Tambah Peserta Baru, sehingga memakan waktu

### Seperti apa yang diharapkan?
tambahkan tombol "Simpan & Tambah Data", sehingga ketika klik tombol ini tidak dialihkan ke halaman Daftar Peserta Program, tapi membuka form baru

### Apa yang terjadi?
supaya menyingkat waktu penginputan data

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | Versi 20.05-pasca
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dicommit ke `master` melalui PR #3107
