### ISSUE TITLE
[Bantuan] Menampilkan Daftar Peserta Bantuan Sesuai NIK pada Statistik Penerima Bantuan (Keluarga)

### ISSUE THREAD

**Issue by RomziJazz** [OpenSID/OpenSID#3104]
### Bagaimana alurnya sampai muncul masalah?
di Statistik penerima bantuan (keluarga) nama yang muncul bukan yang mempunyai kartu, melainkan kepala keluarga yang terdaftar. Sehingga banyak isu yang timbul di masyarakat jika tidak sesuai nama di kartu meskipun itu merupakan istri atau anak dari kepala keluarga.

### Seperti apa yang diharapkan?
Nama yang muncul adalah yang terdaftar di Kartu 
![3](https://user-images.githubusercontent.com/65128302/82573395-e9a97380-9baf-11ea-8fbc-ce2a5f8b69d5.PNG)

### Apa yang terjadi?
Kecemburuan masyarakat bisa teratasi. karena di grafik memperhitungkan jumlah KK, dan yang tampil di daftar sesuai NIK (kartu) penerima.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.05
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
Apakah ini masih bermasalah???

**Comment by mizwaruddin** [comment]
@afa28 saya coba di web demo berjalan normal. Saya coba memasukkan nama istri sebagai yg tertera di kartu, hasilnya normal.

**Comment by afa28** [comment]
Pada program bantuan khusus sasaran keluarga ada 2 nik/nama yg tercantum : 
1. NIK/Nama peserta dari sasaran
2. NIK/Nama penerima bantuan

Mungkin maksud dari issue ini yg ditampilkan seharusnya adalah NIK/Nama penerima bantuan bukan NIK/Nama peserta dari sasaran.

**Comment by mizwaruddin** [comment]
Betul. Mungkin perlu ditambah kolom nama peserta.

**Comment by afa28** [comment]
![1111](https://user-images.githubusercontent.com/57283157/127758134-c80a791e-3c94-4db4-97a4-16bb07df6b38.png)
![2222](https://user-images.githubusercontent.com/57283157/127758135-c664e22b-2cd9-4982-9022-e9cf7d20eb36.png)

Sudah sesuai di rilis premium.
