### ISSUE TITLE
Jangan tampilkan dusun jika di setting -

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#3105]
### Bagaimana alurnya sampai muncul masalah?
Pada menu Pengaturan Aplikasi di Halaman Admin, untuk kolom sebutan Dusun tidak di isi,

![bantuan](https://user-images.githubusercontent.com/46939846/82634471-f5d11780-9c27-11ea-95c3-82bb886c5ef9.png)

namun saat buka statistik bantuan di website, pada kolom alamat peserta terdapat kata "dusun".
![bantuan2](https://user-images.githubusercontent.com/46939846/82634487-fc5f8f00-9c27-11ea-810d-bb0b3bc4f30b.png)

### Seperti apa yang diharapkan?
Alamat menyesuaikan pengaturan desa yang tidak memiliki dusun (maupun tidak memiliki RW)..

### Apa yang terjadi?
Supaya tidak membingungkan warga, padahal tidak ada istilah dusun di desa tersebut.

**Comment by afa28** [comment]
> ### Bagaimana alurnya sampai muncul masalah?
> Pada menu Pengaturan Aplikasi di Halaman Admin, untuk kolom sebutan Dusun tidak di isi, namun saat buka statistik bantuan di website, pada kolom alamat peserta terdapat kata "dusun".
> 
> ### Seperti apa yang diharapkan?
> Alamat menyesuaikan pengaturan desa yang tidak memiliki dusun.
> 
> ### Apa yang terjadi?
> Supaya tidak membingungkan warga, padahal tidak ada istilah dusun di desa tersebut.

Ada gambarnya pak @ariandii ???

**Comment by ariandii** [comment]
sudah saya edit dan tampilkan gambar di atas pak.

**Comment by afa28** [comment]
> ### Bagaimana alurnya sampai muncul masalah?
> Pada menu Pengaturan Aplikasi di Halaman Admin, untuk kolom sebutan Dusun tidak di isi,
> 
> ![bantuan](https://user-images.githubusercontent.com/46939846/82634471-f5d11780-9c27-11ea-95c3-82bb886c5ef9.png)
> 
> namun saat buka statistik bantuan di website, pada kolom alamat peserta terdapat kata "dusun".
> ![bantuan2](https://user-images.githubusercontent.com/46939846/82634487-fc5f8f00-9c27-11ea-810d-bb0b3bc4f30b.png)
> 
> ### Seperti apa yang diharapkan?
> Alamat menyesuaikan pengaturan desa yang tidak memiliki dusun (maupun tidak memiliki RW)..
> 
> ### Apa yang terjadi?
> Supaya tidak membingungkan warga, padahal tidak ada istilah dusun di desa tersebut.

Jadi yg di isi di Wilayah Administratif apa pak @ariandii ???

**Comment by ariandii** [comment]
saya isi dengan tanda -

karena kolom tidak bisa disimpan jika kosong. padahal saya tidak memiliki dusun.

**Comment by afa28** [comment]
> saya isi dengan tanda -
> 
> karena kolom tidak bisa disimpan jika kosong. padahal saya tidak memiliki dusun.

Berarti format tabel dusun jg perlu ditambah - (jika tdk ada dusun) seperti yg ada di rw dan rt yah, biar tdk buat manual

**Comment by ariandii** [comment]
harapannya, jika desa tidak memiliki dusun maka kata dusun otomatis tidak muncul. supaya tidak perlu ada pilihan dusun.

**Comment by afa28** [comment]
Apakah ini masih bermasalah???

**Comment by afa28** [comment]
Perlu dibuatkan kondisi jika sebutan_desa = - , maka data tdk perlu ditampilkan lg

**Comment by afa28** [comment]
Ubah ini sdah diterapkan, namun perlu dilakukan u/ semua bagian.

**Comment by afa28** [comment]
Di PR https://github.com/OpenSID/premium/pull/346, perbaikan dilakukan pada modul Program Bantuan sesuai issue ini. Untuk modul lain bisa dibuatkan issue baru. Issue bisa dibuat 1 mengenai dusun - dengan melampirkan modul mana sj yg perlu diperbaiki.

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melalui PR: https://github.com/OpenSID/premium/pull/346
