### ISSUE TITLE
Data statistik tdk sesuai dengan data penduduk yg ada.

### ISSUE THREAD

**Issue by afa28** [OpenSID/OpenSID#3108]
### Bagaimana alurnya sampai muncul masalah?
Data yg ditampilkan di modul statistik tdk sesuai dengan data penduduk saat klik detail statistik tertentu.

![1](https://user-images.githubusercontent.com/57283157/82677174-d1019200-9c71-11ea-9a0a-895a084ba391.PNG)

![2](https://user-images.githubusercontent.com/57283157/82677213-de1e8100-9c71-11ea-8ff7-74daad227ed3.PNG)

### Seperti apa yang diharapkan?
Data statistik sesuai dengan data penduduk, dll

### Apa yang terjadi?
Data real

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dicommit ke `master` melalui PR #3109
