### ISSUE TITLE
Penerapan SLUG di Artikel Berjalan dan Slider

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#3110]
### Bagaimana alurnya sampai muncul masalah?
Saat ini pada link di akhir Artikel berjalan dan pada Klik Slider masih menggunakan ID Artikel untuk URL nya.

### Seperti apa yang diharapkan?
Diterapkannya SLUG pada kedua lokasi tersebut.

**Comment by eddieridwan** [comment]
Perubahan untuk teks berjalan sdh dicommit ke `master` melalui PR #3112

**Comment by eddieridwan** [comment]
Perubahan untuk slider sdh dicommit ke `master` melalui PR #3187
