### ISSUE TITLE
Sediakan filter jenis program bantuan di website

### ISSUE THREAD

**Issue by WAHYUDIK** [OpenSID/OpenSID#3113]
### Bagaimana alurnya sampai muncul masalah?
ketika ingin melihat jumlah dan nama peserta program bantuan dari beberapa jenis bantuan yang ada mengalami kesulitan, karena di daftar peserta bantuan hanya ada shortlist atas/bawah, jika jenis bantuannya lebih dari 2 akan mengalamai kesulitan.
![image](https://user-images.githubusercontent.com/31026980/82857028-f6282600-9f39-11ea-83f3-a749c37972a6.png)

### Seperti apa yang diharapkan?

disediakan  filter dari jenis bantuan yang suda diinputkan
### Apa yang terjadi?
saat ini masih belum ada

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by ariandii** [comment]
tinggal search saja nama bantuannya.
