### ISSUE TITLE
Fungsikan Aktif/Nonaktif Produk Hukum

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#3114]
### Bagaimana alurnya sampai muncul masalah?
Walaupun LINK /first/informasi_publik dan first/peraturan_desa tidak disediakan pada website, namun tetap bisa diakses jika langsungbketik URL tsb.

### Seperti apa yang diharapkan?
adanya fitur yg menonaktifkan jika memang desa tidak menyediakan.

### Apa yang terjadi?
supaya jelas bahwa, desa ingin tertib administrasi di menu siteman, namun saat di web tidak diberikan link menu itu, kok ya bisa diakses melalui ketik URL tsb.

**Comment by afa28** [comment]
Ini sma kasusnya dgn link statistik, bisa cek #2631

**Comment by ariandii** [comment]
> Ini sma kasusnya dgn link statistik, bisa cek #2631
> 
> Pd fuctionnya bisa cek menunya aktif atau tdk. Fuction statistik, peta, produk, wilayah, dll pengecekan di lakukan pd menu sja untuk mengurangi pembuatan table baru yg fungsinya hampir sma.

betul, saya pernah alami saat input bantuan.

baru mulai input 30KK dari 204KK, kebetulan ada warga yg buka Web, langsung discreenshot, dan dikirim ke group WA dengan pertanyaan, "kok cuma 30KK yg dapat bantuan"

disitu kadang saya merasa sedih. 😅

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3131
