### ISSUE TITLE
Munculkan Tabel Normal di Halaman Web Pada Saat Pembuatan Tabel di Artikel

### ISSUE THREAD

**Issue by muhtar-coder** [OpenSID/OpenSID#3115]
### Bagaimana alurnya sampai muncul masalah?
pada saat membuat artikel yang menggunakan tabel data,garis cell atau kolom yang muncul di web hanya garis pinggir saja

![image](https://user-images.githubusercontent.com/55665526/82915391-db39ce00-9f9a-11ea-906b-35008d56d79a.png)

### Seperti apa yang diharapkan?
harapan nya ketika membuat isi artikel menggunakan tabel data,tabel tersebut dapat muncul di halaman web sehingga artikel terlihat lebih rapih dan mudah di pahami.

![image](https://user-images.githubusercontent.com/55665526/82916223-f6f1a400-9f9b-11ea-836c-8d1428555de6.png)

### Apa yang terjadi?
jika tabel dapat terbaca normal di halaman web maka artikel yang di buat menggunakan tabel data akan lebih bagus dan rapih serta mudah di pahami

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by ariandii** [comment]
beri saja style border=1 pada saat nulis artikel

**Comment by muhtar-coder** [comment]
beri saja style border=1 pada saat nulis artikel
sudah,,sama saja

Pada tanggal Rab, 27 Mei 2020 pukul 03.51 Ariandi Ryan Kahfi <
notifications@github.com> menulis:

**Comment by afa28** [comment]
https://web.facebook.com/groups/OpenSID/permalink/1562308640600778/

Solusi dari pak @fusionid :

1. Highlight semua cell di table
2. Klik mouse kanan
3. Cell -> Cell properties -> Advanced
4. Isi/copy ke input box Style -> border-width: 1px;border-style: solid;

**Comment by afa28** [comment]
https://github.com/OpenSID/OpenSID/wiki/Mengatasi-tabel-pada-artikel-web-yg-hilang
