### ISSUE TITLE
Jumlah kk "bukan penerima bantuan" dobel dan bukan KK yang di maksud

### ISSUE THREAD

**Issue by muhtar-coder** [OpenSID/OpenSID#3116]
### Bagaimana alurnya sampai muncul masalah?
saat melakukan input data calon penerima bantuan,idealnya setelah daftar nama atau KK tersebut di masukan maka akan menyisakan jumlah nama atau KK yang tidak menerima sehingga dapat di jadikan acuan untuk di usulkan menjadi calon penerima bantuan lain nya.

gambar #1 
![image](https://user-images.githubusercontent.com/55665526/82917630-de828900-9f9d-11ea-9c9e-74b2b0e1153f.png)

gambar # 2
![image](https://user-images.githubusercontent.com/55665526/82918017-56e94a00-9f9e-11ea-94f4-a266b66abce9.png)

### Seperti apa yang diharapkan?
harapan nya keterangan "bukan penerima" bantuan tersebut dapat memunculkan daftar nama yang valid dan benar sehingga dapat di jadikan acuan untuk usulan bantuan lain nya atau dengan pengertian orang yang belum menerima bantuan.

### Apa yang terjadi?
pengajuan daftar nama calon penerima bantuan tidak ganda untuk jenis/sumber bantuan yang berbeda.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Masalah ini ada di statisik penerima bantuan penduduk dan keluarga secara menyeluruh, karena saat ini jumlah dihitung berdasarkan jumlah masing2 penerima program bantuan. Sedangkan masing2 penduduk/keluarga bisa menjadi penerima bantuan lebih dari satu program. 

Jadi untuk solusi masalah ini perlu dihitung secara terpisah penduduk/keluarga yg belum menjadi penerima dari program bantuan apa pun. Sepertinya masalah ini sudah terlambat untuk dimasukkan ke v20.06 karena testing untuk solusinya akan memerlukan waktu untuk menjamin sudah benar.

**Comment by mizwaruddin** [comment]
@fusionid ini yg mau saya diskusikan, Bang. Ternyata sdh ada issue-nya.

**Comment by afa28** [comment]
Apakah ini masih bermasalah???
