### ISSUE TITLE
Hilangkan Tombol Aksi di Layanan Mandiri  

### ISSUE THREAD

**Issue by Gunturwijay** [OpenSID/OpenSID#3118]
### ### Bagaimana alurnya sampai muncul masalah?
Login Layanan Mandiri/permohonan surat

### Seperti apa yang diharapkan?
Kelebihannya adalah
1. Dokumen yang telah dimiliki admin/operator desa tidak dapat dihapus sembarangan oleh pengguna layanan mandiri;
2. Agar penduduk dapat mengupload dokumen sesuai persyaratan surat yang diminta

### Apa yang terjadi?
Pengguna layanan mandiri dapat menghapus dokumen yang telah dimiliki oleh desa tanpa izin dari admin/operator desa

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by af-lazuardi** [comment]
berarti, kalau yang upload dari admin/operator desa yang bisa melakukan manipulasi file hanya user admin/operator ya Pak?
Sedangkan kalau yang upload warga dri layanan mandiri, maka yang bisa manipulasi file adalah warga yang bersangkutan dan admin/operator.

Begitu ya?

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3322
