### ISSUE TITLE
Server Error

### ISSUE THREAD

**Issue by basiscoding20** [OpenSID/OpenSID#3120]
### Bagaimana alurnya sampai muncul masalah?
setelah melakukan instalasi menggunakan installer code bukan desktop hasil server error

### Apa yang terjadi?

![image](https://user-images.githubusercontent.com/60428779/83311343-2113c200-a239-11ea-95eb-5475236684fe.png)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.05
| Versi PHP        | 7 & 5
| System operasi   | Windows

**Comment by afa28** [comment]
Silahkan buat issue di https://github.com/OpenSID/installer/issues

Jelaskan alurnya.

**Comment by balongbesuk** [comment]
mungkin php 5.5 bisa di cb di naikkan ke 7.2

**Comment by eddieridwan** [comment]
Karena issue ini telah dipindah ke https://github.com/OpenSID/installer/issues. Kami tutup issue ini.
