### ISSUE TITLE
Urutkan Data Log Penduduk berdasarkan tanggal peristiwa terbaru paling atas

### ISSUE THREAD

**Issue by afri18** [OpenSID/OpenSID#3121]
### Bagaimana alurnya sampai muncul masalah?
Saat periksa data di log penduduk sehabis perbarui status dasar penduduk tidak menampilkan data terbaru di paling atas (no 1) terpaksa pakai menu cari 

### Seperti apa yang diharapkan?
sebaiknya data di log penduduk di urutkan berdasarkan data terkini paling atas
![image](https://user-images.githubusercontent.com/6611881/83317651-57146e80-a258-11ea-9229-e4545d1d0e35.png)

### Apa yang terjadi?
Data terbaru tidak tampil di urutan paling atas

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.05 pasca
| Versi PHP        | 7.2
| System operasi   |

**Comment by eddieridwan** [comment]
Sudah dicommit ke `master` melalui PR #3130
