### ISSUE TITLE
Nama Pamong di Lampiran Surat Export Tidak Sesuai Dengan Yang Dipilih

### ISSUE THREAD

**Issue by kayangan** [OpenSID/OpenSID#3125]
1.  Ketika Membuat Surat Contoh Membuat Surat Bio Penduduk saya memilih kepala Desa Dari Nik Kependudukan  
![1](https://user-images.githubusercontent.com/32614693/83341334-6ead2f00-a30c-11ea-91b3-eb5625664419.PNG) Tapi Setelah Export Surat Hasil Lampirannya nya Seperti ini 
![2](https://user-images.githubusercontent.com/32614693/83341346-9dc3a080-a30c-11ea-817b-c31ede9677ed.png)
2. Lalu Saya Mencoba Lagi Membuat Surat Perubahan Kartu Keluarga 
![3](https://user-images.githubusercontent.com/32614693/83341357-c055b980-a30c-11ea-8e7e-1aad810cec4c.PNG)  Tapi Setelah Export Surat Hasil Lampirannya nya Seperti ini 
![4](https://user-images.githubusercontent.com/32614693/83341364-d1062f80-a30c-11ea-99db-96393a9ece2e.PNG) Bukan Nama Pamong Malah Yang Keluar Di Lampiran Exportnya

Ini Terjadi Di Demo Pasca 20.05

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
@kayangan mohon jelaskan peraturan terkait pengisian formulir lampiran Disdukcapil. Apakah ttd kepala desa bisa diwakilkan (a.n/u.b)? Apakah penamaan jabatan bisa diubah sesuai kebiasaan desa, misalnya menggunakan Wali Nagari atau Kepala Kampong, dsbnya. @M-A-Haris @Nurhidayat29

**Comment by kayangan** [comment]
Di tempat/Desa Saya Jika Tidak Ada Kades Yang Tanda Tangan Maka yang boleh An.  KEPALA Desa Yaitu Sekdes Dan Kasi seperti Kasi pemerintahan kasi Kesos dan Kasi Pelayanan.  Jika menunggu kepala desa misal kepala desa berhalangan tidak bisa masuk kantor pelayanan jadi tersendat

**Comment by kayangan** [comment]
Dan belum ada aturan yang saya tau kalau harus mematok kepala desa saja yang tanda tangan.  Itu saja pengetahuan saya maaf jika saya salah

**Comment by ariandii** [comment]
di Kabupaten saya, belum menerapkan istilah U.b.

jika yg tanda tangan Selain Kades, maka penerapannya tetap menggunakan a.n.

**Comment by kayangan** [comment]
Sama Pak Ariandi Di Desa Saya Juga Menggunakan An. Jika Kades/Sekdes Berhalangan

**Comment by upperhead93** [comment]
sejauh ini tidak ada masalah utk An., msh dapat diterima di capil kami.

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3126
