### ISSUE TITLE
Kalimat Teks Berjalan Terpotong

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#3132]
### Bagaimana alurnya sampai muncul masalah?
Setelah update OpenSID beberapa hari yang lalu, saat input "Teks Berjalan" pada kolom yang disediakan masih berjalan dengan baik seperti gambar berikut ini:

![image](https://user-images.githubusercontent.com/46939846/83439634-c4e5b380-a46d-11ea-86fa-c91e6a91e8b4.png)

Namun, saat disimpan, teks tersebut tampil terpotong, walau saat diedit teks asli tetap utuh.
![image](https://user-images.githubusercontent.com/46939846/83439656-ce6f1b80-a46d-11ea-9da0-6c1bf0b3bc60.png)

Begitupun tampilan teks berjalan pada halaman website, tulisan yang tampil juga terpotong.

### Seperti apa yang diharapkan?
Teks berjalan dapat ditampilkan secara utuh kembali.

**Comment by eddieridwan** [comment]
Sudah dicommit ke `master` melalui PR #3133
