### ISSUE TITLE
Sesuaikan Paragraph Artikel di sebelah kanan gambar jika gambar berukuran kotak

### ISSUE THREAD

**Issue by hasap86** [OpenSID/OpenSID#3135]
![gambar-kotak-di-artikel](https://user-images.githubusercontent.com/45263721/83524051-3e80ae80-a50d-11ea-8b7f-a960d489cf59.png)

### Bagaimana alurnya sampai muncul masalah?
Paragraph artikel dibawah gambar pada gambar yg berukuran kotak, sehingga ada kekosongan sebelah gambar.

### Seperti apa yang diharapkan?
seharusnya paragraph artikel dimulai dari kanan gambar yg berukuran kotak

### Apa yang terjadi?
kurang menarik dilihatnya

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.06-pasca Demo
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
@ariandii Karena perubahan ini bersifat sesuai selera, sebaiknya tidak dilakukan bagi semua pengguna. Perubahan tampilan seperti ini bisa dilakukan perubahan per desa mengikuti petunjuk di https://github.com/OpenSID/OpenSID/wiki/Mengubah-Penampilan-Web.

Sebagai contoh, untuk menerapkan perubahan yg anda inginkan ini, bisa tambahkan style untuk tema klasik sbb:

![contoh-ubah-gambar](https://user-images.githubusercontent.com/249563/89378763-e1d18800-d737-11ea-9e4a-bb45b2888c11.jpg)

Lakukan perubahan serupa untuk tema hadakewa jika juga diperlukan.

**Comment by eddieridwan** [comment]
Pertimbangan yg juga penting adalah: saat ini gambar default ditampilkan di daftar artikel di beranda jika gambar artikel tidak ditemukan. Tetapi gambar default tersebut tidak tampil di halaman artikel tersendiri. Sebaiknya gambar default ditampilkan atau tidak, secara konsisten di beranda dan juga di artikel penuh.

Mana yg lebih baik: tampilkan gambar default atau biar kosong saja?

**Comment by hasap86** [comment]
tampilkan gambar default tapi baiknya apa ambil logo yg diupload dijadikan gambar defaut artikel

**Comment by afa28** [comment]
Untuk issue mengenai tema hadakewa bisa di buat di https://github.com/OpenSID/tema-hadakewa

**Comment by mizwaruddin** [comment]
@afa28 Issue sdh saya pindah ke https://github.com/OpenSID/tema-hadakewa/issues/6
