### ISSUE TITLE
Seting Upload Background Web

### ISSUE THREAD

**Issue by hasap86** [OpenSID/OpenSID#3137]
### Bagaimana alurnya sampai muncul masalah?
Saat ini belum ada seting untuk merubah Gambar / Warna Background Web

### Seperti apa yang diharapkan?
Sediakan Seting Upload Background

### Apa yang terjadi?
Background disesuaikan dengan kearipan lokal

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | Demo
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
Sudah masuk disub modul https://github.com/OpenSID/OpenSID/issues/2293, tinggal disesuaikan.

**Comment by afa28** [comment]
Sudah di `master ` versi premium
