### ISSUE TITLE
Tampilkan Nomor Telepon dan Email di Cetak Biodata

### ISSUE THREAD

**Issue by mizwaruddin** [OpenSID/OpenSID#3141]
### Bagaimana alurnya sampai muncul masalah?
Pada bagian iput data penduduk ada nomor telepon dan email penduduk. Tetapi pada cetak biodata kedua item tersebut tidak ditampilkan.
![biodata_cetak](https://user-images.githubusercontent.com/39736008/83706906-db913380-a642-11ea-92b5-aa36d4e572bd.PNG)

### Seperti apa yang diharapkan?
Pada cetak biodata, bagian alamat ditampilkan secara lengkap termasuk nomor telepon dan email penduduk.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by Nurhidayat29** [comment]
ok

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3142
