### ISSUE TITLE
Statistis Bantuan Error/Data Kosong

### ISSUE THREAD

**Issue by mizwaruddin** [OpenSID/OpenSID#3143]
### Bagaimana alurnya sampai muncul masalah?
Saat masuk menu statistik program bantuan (PKH,BPNT, dll) ke website desa, sya klik jlm keluarga yg mendapatkan bantuan terjadi error.
![statistik_bantuan](https://user-images.githubusercontent.com/39736008/83763227-b207f480-a6a2-11ea-8c1e-d65b9151baf5.PNG)
![error_bantuan](https://user-images.githubusercontent.com/39736008/83763320-c1873d80-a6a2-11ea-88f4-a32168df411a.PNG)
Saat saya coba di web demo, hasilnya tidak muncul error, tetapi data kosong.
![statistik_bantuan_demo](https://user-images.githubusercontent.com/39736008/83763429-e1b6fc80-a6a2-11ea-949e-c2e44ac6b6a5.PNG)

### Seperti apa yang diharapkan?
Tidak terjadi error atau menunjukkan data yg valid.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master`.
