### ISSUE TITLE
Menghapus data Rumah Tangga tidak bisa Bersih

### ISSUE THREAD

**Issue by afri18** [OpenSID/OpenSID#3145]
### Bagaimana alurnya sampai muncul masalah?
saat menghapus data rumah tangga tidak bisa bersih total, masih terbaca di Home > menu Rumah Tangga
![image](https://user-images.githubusercontent.com/6611881/83843982-57b57500-a730-11ea-9dc6-00ebf3fbe6d5.png)
padahal di datanya tidak ada
![image](https://user-images.githubusercontent.com/6611881/83844034-7156bc80-a730-11ea-84de-184ee4982feb.png)

### Seperti apa yang diharapkan?
bersih semua baik di database maupun statistiknya saat menghapus keseluruhan

### Apa yang terjadi?
di menu Home masih terbaca data Rumah Tangga
![image](https://user-images.githubusercontent.com/6611881/83844202-b67aee80-a730-11ea-8506-44afb1550f30.png)

Data yg sisa terbaca tidak bisa di panggil (dipencarian tidak muncul)

### Informasi tambahan 
database saya dari 2014 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.06
| Versi PHP        | 7.2
| System operasi   | win 10

**Comment by afa28** [comment]
Pak @afri18 , bisa SS database untuk tabel tweb_rtm. Krn sy coba di local dan demo tdk menemukan permasalahan yg diissuekan.

Mungkin bisa clear cache

**Comment by afri18** [comment]
> Pak @afri18 , bisa SS database untuk tabel tweb_rtm. Krn sy coba di local dan demo tdk menemukan permasalahan yg diissuekan.
> 
> Mungkin bisa clear cache
[tweb_rtm.zip](https://github.com/OpenSID/OpenSID/files/4734528/tweb_rtm.zip)

**Comment by afri18** [comment]
> > Pak @afri18 , bisa SS database untuk tabel tweb_rtm. Krn sy coba di local dan demo tdk menemukan permasalahan yg diissuekan.
> > Mungkin bisa clear cache
> > [tweb_rtm.zip](https://github.com/OpenSID/OpenSID/files/4734528/tweb_rtm.zip)

saya coba ganti dengan tweb_rtm database awal tetap terbaca dan tidak bisa input id yg sudah di hapus

**Comment by afri18** [comment]
> Pak @afri18 , bisa SS database untuk tabel tweb_rtm. Krn sy coba di local dan demo tdk menemukan permasalahan yg diissuekan.
> 
> Mungkin bisa clear cache

ini belum bisa bersih kenapa ya ???

**Comment by afri18** [comment]
> Pak @afri18 , bisa SS database untuk tabel tweb_rtm. Krn sy coba di local dan demo tdk menemukan permasalahan yg diissuekan.
> 
> Mungkin bisa clear cache

ternyata saat menghapus data rumah tangga secara keseluruhan di table tweb_penduduk file id_rtm dan rtm_level tidak turut serta dibersihkan, setelah saya hapus id_rtm dan rtm_level nya bisa kembali nol > NIHIL

**Comment by afa28** [comment]
> > Pak @afri18 , bisa SS database untuk tabel tweb_rtm. Krn sy coba di local dan demo tdk menemukan permasalahan yg diissuekan.
> > Mungkin bisa clear cache
> 
> ternyata saat menghapus data rumah tangga secara keseluruhan di table tweb_penduduk file id_rtm dan rtm_level tidak turut serta dibersihkan, setelah saya hapus id_rtm dan rtm_level nya bisa kembali nol > NIHIL

Kemungkin itu data yg lama sebelum terjadi perbaikan pd modul RT. Krn modul RT saat ini alurnya ketika suatu rtm dihapus maka status(id_rtm) akan normal kembali(0) bgitupun jg dgn rtm_levelnya.

**Comment by afri18** [comment]
> > > Pak @afri18 , bisa SS database untuk tabel tweb_rtm. Krn sy coba di local dan demo tdk menemukan permasalahan yg diissuekan.
> > > Mungkin bisa clear cache
> > 
> > 
> > ternyata saat menghapus data rumah tangga secara keseluruhan di table tweb_penduduk file id_rtm dan rtm_level tidak turut serta dibersihkan, setelah saya hapus id_rtm dan rtm_level nya bisa kembali nol > NIHIL
> 
> Kemungkin itu data yg lama sebelum terjadi perbaikan pd modul RT. Krn modul RT saat ini alurnya ketika suatu rtm dihapus maka status(id_rtm) akan normal kembali(0) bgitupun jg dgn rtm_levelnya.

Ternyata di id_rtm dan level_rtm di table penduduk saat menghapus d table cri tidak bersih, terpaksa hapus manual, setelah hapus manual baru bisa nol ,
Sebagai info ud_rtm yg dulu di mulai satu digit
