### ISSUE TITLE
menu bantua detail tidak terSedia penanda baris untuk di hapus

### ISSUE THREAD

**Issue by afri18** [OpenSID/OpenSID#3146]
### Bagaimana alurnya sampai muncul masalah?
saat mencoba menghapus penerima bantuan mesti satu satu

### Seperti apa yang diharapkan?
tersedianya penanda agar bisa dihapus sekaligus
![image](https://user-images.githubusercontent.com/6611881/83851854-242d1780-a73d-11ea-966d-f120620b1a4e.png)

### Apa yang terjadi?
terlalu lama bila menghapus data satu perssatu

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.06
| Versi PHP        | 7.2
| System operasi   | win 10

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3153
