### ISSUE TITLE
Lengkapi panduan cara mengubah slide atas pada tema klasik

### ISSUE THREAD

**Issue by afri18** [OpenSID/OpenSID#3148]
### Bagaimana alurnya sampai muncul masalah?
saat mau ganti slide kecil atas (header) tidak ber fungsi di menu Admin Web > Galeri
![image](https://user-images.githubusercontent.com/6611881/83858197-4ecf9e00-a746-11ea-8edc-a28bef191678.png)
tidak ber fungsi
### Seperti apa yang diharapkan?
harusnya slide kecil kepala web bisa di ganti melalui tombol ini
![image](https://user-images.githubusercontent.com/6611881/83857671-8558e900-a745-11ea-9f6a-d793262099bb.png)

![image](https://user-images.githubusercontent.com/6611881/83857968-f6000580-a745-11ea-90eb-07e256575184.png)

### Apa yang terjadi?
tidak bisa mengganti slider kecil atas

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.06
| Versi PHP        | 7.2
| System operasi   |win 10

**Comment by afa28** [comment]
Apakah ini masih bermasalah???

**Comment by afa28** [comment]
Gambar pd slider kecil tema klasik di ambil dr gambar artikel pilihan, buka dr gambar galery pilihan.

**Comment by afa28** [comment]
Perlu ditambahkan di panduan slider kecil u/ khusus tema klasik

**Comment by afa28** [comment]
Sdah di panduan
