### ISSUE TITLE
Hasil Unduh Salinan Kartu Keluarga Belum Mencantumkan Golongan Darah dan Tanggal Perkawinan

### ISSUE THREAD

**Issue by mizwaruddin** [OpenSID/OpenSID#3154]
### Bagaimana alurnya sampai muncul masalah?
Saat melakukan unduh salinan kartu keluarga, hasil unduh dalam format rtf belum mencantumkan golongan darah dan tanggal perkawinan.
![suket_kk](https://user-images.githubusercontent.com/39736008/83933991-863a5b00-a7d7-11ea-871e-fa915499adde.PNG)

### Seperti apa yang diharapkan?
Hasil unduh dalam format rtf mencantumkan golongan darah dan tanggal perkawinan sesuai format terbaru.
![kk_baru](https://user-images.githubusercontent.com/39736008/83934016-a833dd80-a7d7-11ea-8b40-6b77f7e2f1e0.png)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by Nurhidayat29** [comment]
formatnya apakah disamakan dengan fitur cetak?

**Comment by af-lazuardi** [comment]
hehe, sorry bung @Nurhidayat29 , nggak ngerti kalau anda PR juga :D ... ntar di merge semua aja hasil kerjaan bung Nur dengan saya. :+1:

**Comment by Nurhidayat29** [comment]
> hehe, sorry bung @Nurhidayat29 , nggak ngerti kalau anda PR juga :D ... ntar di merge semua aja hasil kerjaan bung Nur dengan saya. 👍

ahaha ndak pa2 bung, ttp harus 1 yg dimerge. PR saya sdh saya close

**Comment by mizwaruddin** [comment]
Ajiiib ...

**Comment by eddieridwan** [comment]
@af-lazuardi @Nurhidayat29 , untuk menghindari sama2 mengerjakan issue, mohon ikuti prosedur di https://github.com/OpenSID/OpenSID/wiki/Cara-Ikut-Mengembangkan-OpenSID

```
Setelah anda memilih issue untuk dikerjakan, beritahu bahwa anda akan mengerjakan suatu issue dengan cara berikut:

tambahkan comment di issue yang bersangkutan
beritahu forum teknis https://opensid.slack.com, di channel #general.
```

Atau kalau anda sudah menjadi anggota Github OpenSID, assign diri anda pada issue yg bersangkutan. Jadi seharusnya bung @af-lazuardi bisa assign diri anda pada issue.

**Comment by af-lazuardi** [comment]
Baik pak @eddieridwan , mohon maaf ... :)

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3157
