### ISSUE TITLE
Penambahan Kolom Telepon dari 10 Digit menjadi 12 Digit pada Lampiran F-1.08 Surat Pindah 

### ISSUE THREAD

**Issue by roaddee** [OpenSID/OpenSID#3158]
### Bagaimana alurnya sampai muncul masalah?
Saat ini 10 kolom sudah tidak mencukupi untuk panjang nomor telepon, terutama seluler.
![image](https://user-images.githubusercontent.com/45786885/83944460-e4922880-a82d-11ea-9aa9-1138f2df86df.png)

### Seperti apa yang diharapkan?
Rata-rata nomor telepon saat ini adalah 12 digit, hampir untuk semua Penyedia Jasa Telepon Seluler
![image](https://user-images.githubusercontent.com/45786885/83944466-f5429e80-a82d-11ea-8ceb-9aca8dadd70d.png)

### Apa yang terjadi?
Nomor Telepon 12 Digit akan terpotong ketika dimasukkan ke dalam kolom 10 Digit, yang menyebabkan kesalahan informasi.

### Informasi tambahan 
Permohonan penambahan kolom ini diminta oleh Sdr. Gundari, S.Pd sebagai SekKam dari desa Sukosari, Kabupaten Way Kanan, Lampung

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.06
| Versi PHP        |  7.3
| System operasi   | Windows

**Comment by roaddee** [comment]
Saya akan kerjakan Issue Ini.

**Comment by eddieridwan** [comment]
@roaddee apakah form F-1.08 ini masih digunakan? Bukankah sesuai peraturan, seharusnya sudah diganti dengan form F-1.25 (dan variasinya)?

**Comment by eddieridwan** [comment]
Sudah dicommit ke `master` melalui PR #3159
