### ISSUE TITLE
Jangan Kembalikan Default Pengaturan Halaman Web saat Migrasi DB

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#3160]
### Bagaimana alurnya sampai muncul masalah?
Saat klik migrasi_db, pengaturan halaman web pada menu Admin Web -> Pengaturan ikut ke reset.

### Seperti apa yang diharapkan?
Pengaturan Halaman Web yang sudah disesuaikan sebelumnya tidak kembali default pada saat klik migrasi_db

### Apa yang terjadi?
Agar tidak mengulang kembali menyesuaikan yang sudah ditentukan sebelumnya.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3162
