### ISSUE TITLE
[Teknis] Sederhanakan script modul Keuangan

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#3161]
### Bagaimana alurnya sampai muncul masalah?
Perhatikan script di `donjo-app/models/Keuangan_grafik_model.php` dan di `donjo-app/models/Keuangan_grafik_manual_model.php`.

Penyederhanaan yg telah dimulai di `donjo-app/models/Keuangan_grafik_manual_model.php` belum dilakukan di `donjo-app/models/Keuangan_grafik_model.php`. Juga masih BANYAK penyederhanaan dan penghapusan duplikasi yg dapat dilakukan di kedua file tersebut.

### Seperti apa yang diharapkan?
Kedua file tersebut dan file lain di modul Keuangan disederhanakan, duplikasi dihapus dan diberi komentar menjelaskan logika modul ini. Modul ini sangat rumit dan kalau tidak disederhanakan dan diberi penjelasan, resikonya adalah programmer yg bukan pengembang asli fitur ini akan kesulitan untuk mengikuti dan memelihara script yg ada.

### Informasi tambahan 

@fusionid mohon anda menyediakan contoh data keuangan dan contoh laporan yg betul, supaya bisa digunakan untuk testing meyakinkan proses penyederhanaan tidak merusak logika modul keuangan. Mohon contoh tersebut dilampirkan di issue ini.
| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.06
| Versi PHP        | 
| System operasi   |

**Comment by fusionid** [comment]
Logika dan penyederhanaan di donjo-app/models/Keuangan_grafik_manual_model.php relatif tidak terlalu sulit karena semua pos-pos pendapatan, belanja, pembiayaan masuk dan pembiayaan keluar hanya refer ke 1 tabel saja yaitu **keuangan_manual_rinci**,  tetapi pada versi impor data di donjo-app/models/Keuangan_grafik_model.php mungkin relatif sedikit yang bisa disederhanakan karena semua semua pos-pos pendapatan, belanja, pembiayaan masuk dan pembiayaan keluar refer ke beberapa tabel dan masing2 pos berbeda tabelnya. 
Baik contoh database akan dilampirkan di issue ini.

**Comment by eddieridwan** [comment]
@fusionid mohon juga lampirkan contoh laporan dari database contoh tsb. Terima kasih.

**Comment by fusionid** [comment]
Contoh Laporan APBDes Manual
![laporan_apbdes_manual](https://user-images.githubusercontent.com/10391199/83970607-c9dcb400-a900-11ea-8eb1-d804c381f664.PNG)

Contoh Laporan APBDes Impor
![laporan_apbdes_impor](https://user-images.githubusercontent.com/10391199/83970610-ce08d180-a900-11ea-8afd-8134692df814.PNG)

Contoh DB ada di slack channel keuangan-desa

**Comment by andifahruddinakas** [comment]
Sederhanakan hal berikut : 
- Menggunakan tabel yang sama yang sudah di normalisasi.
- Gunakan 1 tampilan (CRUD) + laporan untuk menampilkan data keuangan.
- Untuk impor dari siskuedes, hanya ambil bagian yang diperlukan saja.
- Sesuaikan bagian2 yang berkaitan (widget, artikel, dll)

**Comment by andifahruddinakas** [comment]
Template :
<img width="455" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/a702bd19-93ec-4ed7-80a3-750b9787df0a">

<img width="490" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/2d1c0034-a9e3-4049-9ff6-7051c48db1a1">
