### ISSUE TITLE
Pengguna Layanan Mandiri bisa Upload Foto Pribadi

### ISSUE THREAD

**Issue by gampongbarabung** [OpenSID/OpenSID#3164]
### Bagaimana alurnya sampai muncul masalah?
Foto Profil Akun Layanan mandiri harus diupload oleh administrator melalui ubah profil penduduk.

### Seperti apa yang diharapkan?
Pengguna Layanan Mandiri bisa mengupload foto profil pribadinya sendiri setelah login akun Layanan Mandirinya. 

### Informasi tambahan 
Terdapat Fitur Upload Foto Profil pada Akun Layanan Mandiri.
![1](https://user-images.githubusercontent.com/60224596/83976475-49c84580-a924-11ea-8296-6744b1889c97.JPG)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.06-pasca
| Versi PHP        | Version 7.3.18
| System operasi   | Windows

**Comment by afa28** [comment]
> ### Bagaimana alurnya sampai muncul masalah?
> Foto Profil Akun Layanan mandiri harus diupload oleh administrator melalui ubah profil penduduk.
> 
> ### Seperti apa yang diharapkan?
> Pengguna Layanan Mandiri bisa mengupload foto profil pribadinya sendiri setelah login akun Layanan Mandirinya.
> 
> ### Informasi tambahan
> Terdapat Fitur Upload Foto Profil pada Akun Layanan Mandiri.
> ![1](https://user-images.githubusercontent.com/60224596/83976475-49c84580-a924-11ea-8296-6744b1889c97.JPG)
> 
> Tanya	Jawab
> Versi OpenSID	20.06-pasca
> Versi PHP	Version 7.3.18
> System operasi	Windows

Untuk data penduduk sebaiknya yg melakukan perubahan adalah pemerintah desa (administrator) untuk menghindari perubahan data yg tdk diinginkan tanpa sepengetahuan administrator.

**Comment by afa28** [comment]
Hampir sama mengenai data penduduk pd layanan mandiri.

https://github.com/OpenSID/OpenSID/issues/3466

**Comment by HerryWanda** [comment]
atau ini perlu di buat notif persetujuan ke admin , jika melakukn perubahan data dengan melampirkan dokumen yg sah. contoh KK, KTP, buku nikah, ijazah dll jika ada perubhan yg dilakukan.

jadi data yg mereka ubah, tidak lnagsung terganti atas perubahan yg dilakukan lnagsung oleh masyarakat di layanan mndiri..

bg @afa28 , apakah seperti diatas bisa kita terapkan..

jadi nantik, yang menstujui perubahan yg dilakukan adalah administrator.. dengan dasar dokumen yg dlampirkan.

ini mungkin solusinya..

**Comment by afa28** [comment]
Duplicate #3466
