### ISSUE TITLE
seragamkan nilai Rupiah

### ISSUE THREAD

**Issue by afri18** [OpenSID/OpenSID#3169]
### Bagaimana alurnya sampai muncul masalah?
lihat nilai rupiah tidak seragam

### Seperti apa yang diharapkan?
sebaiknya nilai rupiah diseragamkan seperti 1.000.,00 , ada koma dua digit
![image](https://user-images.githubusercontent.com/6611881/83990822-119d2300-a975-11ea-8ca9-ea46fd3bae20.png)

### Apa yang terjadi?
Jadi gosok mata memastikannya (maklum mata tua)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.06 pasca tgl 08-06-2020
| Versi PHP        | 7.3
| System operasi   | win 10

**Comment by afa28** [comment]
Tambahan jg, ada pernah helper yg sy buat agar jika nilai nan/inf di isi 0

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3171
