### ISSUE TITLE
trigger yang menyebabkan definer pada database

### ISSUE THREAD

**Issue by pemdesbts** [OpenSID/OpenSID#3170]
### Bagaimana alurnya sampai muncul masalah?
saat mengakses website di akun hosting rumahosting, terjadi error 500, dan setelah dilakukan helpdesk tiket dijawablah oleh team suport yaitu :
Untuk hal ini mungkin Anda bisa coba cek kembali script atau konfigurasi trigger pada websitenya, karena rekan Kami sebelumnya telah menyampaikan bahwa masalah ini terjadi dikarenakan terdapat trigger website yang membuat definner pada databasenya, oleh karena itu silahkan Anda hapus setiap trigger yang membuat definner.

Sebab diperlukan akses super user database untuk membuat definner, sementara akun hosting Anda tidak diperkenankan untuk membuat hal tersebut.

### Seperti apa yang diharapkan?
apakah bisa diberikan solusi bagaimana cara mengatasi masalah hosting tersebut

### Informasi tambahan 
ERROR - 2020-06-08 05:13:51 --> Query error: Access denied for user 'batungse_OpenSid'@'localhost' (using password: YES) - Invalid query: SELECT COUNT(b.id) AS jumlah, COUNT(CASE WHEN b.sex = 1 THEN b.id END) AS laki, COUNT(CASE WHEN b.sex = 2 THEN b.id END) AS perempuan
FROM `penduduk_hidup` `b`
LEFT JOIN `tweb_wil_clusterdesa` `a` ON `b`.`id_cluster` = `a`.`id`
ERROR - 2020-06-08 05:14:16 --> Query error: Access denied for user 'batungse_OpenSid'@'localhost' (using password: YES) - Invalid query: SELECT COUNT(b.id) AS jumlah, COUNT(CASE WHEN b.sex = 1 THEN b.id END) AS laki, COUNT(CASE WHEN b.sex = 2 THEN b.id END) AS perempuan
FROM `penduduk_hidup` `b`
LEFT JOIN `tweb_wil_clusterdesa` `a` ON `b`.`id_cluster` = `a`.`id`
ERROR - 2020-06-08 05:14:17 --> Query error: Access denied for user 'batungse_OpenSid'@'localhost' (using password: YES) - Invalid query: SELECT COUNT(b.id) AS jumlah, COUNT(CASE WHEN b.sex = 1 THEN b.id END) AS laki, COUNT(CASE WHEN b.sex = 2 THEN b.id END) AS perempuan
FROM `penduduk_hidup` `b`
LEFT JOIN `tweb_wil_clusterdesa` `a` ON `b`.`id_cluster` = `a`.`id`
ERROR - 2020-06-08 06:18:03 --> Query error: Access denied for user 'batungse_OpenSid'@'localhost' (using password: YES) - Invalid query: SELECT COUNT(b.id) AS jumlah, COUNT(CASE WHEN b.sex = 1 THEN b.id END) AS laki, COUNT(CASE WHEN b.sex = 2 THEN b.id END) AS perempuan
FROM `penduduk_hidup` `b`
LEFT JOIN `tweb_wil_clusterdesa` `a` ON `b`.`id_cluster` = `a`.`id`
ERROR - 2020-06-08 06:18:28 --> Query error: Access denied for user 'batungse_OpenSid'@'localhost' (using password: YES) - Invalid query: SELECT COUNT(b.id) AS jumlah, COUNT(CASE WHEN b.sex = 1 THEN b.id END) AS laki, COUNT(CASE WHEN b.sex = 2 THEN b.id END) AS perempuan
FROM `penduduk_hidup` `b`
LEFT JOIN `tweb_wil_clusterdesa` `a` ON `b`.`id_cluster` = `a`.`id`
ERROR - 2020-06-08 06:18:37 --> Query error: Access denied for user 'batungse_OpenSid'@'localhost' (using password: YES) - Invalid query: SELECT COUNT(b.id) AS jumlah, COUNT(CASE WHEN b.sex = 1 THEN b.id END) AS laki, COUNT(CASE WHEN b.sex = 2 THEN b.id END) AS perempuan
FROM `penduduk_hidup` `b`
LEFT JOIN `tweb_wil_clusterdesa` `a` ON `b`.`id_cluster` = `a`.`id`
ERROR - 2020-06-08 06:21:26 --> Query error: Access denied for user 'batungse_OpenSid'@'localhost' (using password: YES) - Invalid query: SELECT COUNT(b.id) AS jumlah, COUNT(CASE WHEN b.sex = 1 THEN b.id END) AS laki, COUNT(CASE WHEN b.sex = 2 THEN b.id END) AS perempuan
FROM `penduduk_hidup` `b`
LEFT JOIN `tweb_wil_clusterdesa` `a` ON `b`.`id_cluster` = `a`.`id`
ERROR - 2020-06-08 06:21:28 --> Query error: Access denied for user 'batungse_OpenSid'@'localhost' (using password: YES) - Invalid query: SELECT COUNT(b.id) AS jumlah, COUNT(CASE WHEN b.sex = 1 THEN b.id END) AS laki, COUNT(CASE WHEN b.sex = 2 THEN b.id END) AS perempuan
FROM `penduduk_hidup` `b`
LEFT JOIN `tweb_wil_clusterdesa` `a` ON `b`.`id_cluster` = `a`.`id`
ERROR - 2020-06-08 06:21:35 --> Query error: Access denied for user 'batungse_OpenSid'@'localhost' (using password: YES) - Invalid query: SELECT COUNT(b.id) AS jumlah, COUNT(CASE WHEN b.sex = 1 THEN b.id END) AS laki, COUNT(CASE WHEN b.sex = 2 THEN b.id END) AS perempuan
FROM `penduduk_hidup` `b`
LEFT JOIN `tweb_wil_clusterdesa` `a` ON `b`.`id_cluster` = `a`.`id`
ERROR - 2020-06-08 07:13:41 --> Query error: Access denied for user 'batungse_OpenSid'@'localhost' (using password: YES) - Invalid query: SELECT COUNT(b.id) AS jumlah, COUNT(CASE WHEN b.sex = 1 THEN b.id END) AS laki, COUNT(CASE WHEN b.sex = 2 THEN b.id END) AS perempuan
FROM `penduduk_hidup` `b`
LEFT JOIN `tweb_wil_clusterdesa` `a` ON `b`.`id_cluster` = `a`.`id`
ERROR - 2020-06-08 07:13:43 --> Query error: Access denied for user 'batungse_OpenSid'@'localhost' (using password: YES) - Invalid query: SELECT COUNT(b.id) AS jumlah, COUNT(CASE WHEN b.sex = 1 THEN b.id END) AS laki, COUNT(CASE WHEN b.sex = 2 THEN b.id END) AS perempuan
FROM `penduduk_hidup` `b`
LEFT JOIN `tweb_wil_clusterdesa` `a` ON `b`.`id_cluster` = `a`.`id`
ERROR - 2020-06-08 08:08:46 --> Query error: Access denied for user 'batungse_OpenSid'@'localhost' (using password: YES) - Invalid query: SELECT COUNT(b.id) AS jumlah, COUNT(CASE WHEN b.sex = 1 THEN b.id END) AS laki, COUNT(CASE WHEN b.sex = 2 THEN b.id END) AS perempuan
FROM `penduduk_hidup` `b`
LEFT JOIN `tweb_wil_clusterdesa` `a` ON `b`.`id_cluster` = `a`.`id`
ERROR - 2020-06-08 08:20:23 --> Query error: Access denied for user 'batungse_OpenSid'@'localhost' (using password: YES) - Invalid query: SELECT COUNT(b.id) AS jumlah, COUNT(CASE WHEN b.sex = 1 THEN b.id END) AS laki, COUNT(CASE WHEN b.sex = 2 THEN b.id END) AS perempuan
FROM `penduduk_hidup` `b`
LEFT JOIN `tweb_wil_clusterdesa` `a` ON `b`.`id_cluster` = `a`.`id`
ERROR - 2020-06-08 08:36:28 --> Query error: Access denied for user 'batungse_OpenSid'@'localhost' (using password: YES) - Invalid query: SELECT COUNT(b.id) AS jumlah, COUNT(CASE WHEN b.sex = 1 THEN b.id END) AS laki, COUNT(CASE WHEN b.sex = 2 THEN b.id END) AS perempuan
FROM `penduduk_hidup` `b`
LEFT JOIN `tweb_wil_clusterdesa` `a` ON `b`.`id_cluster` = `a`.`id`
ERROR - 2020-06-08 08:50:05 --> Query error: Access denied for user 'batungse_OpenSid'@'localhost' (using password: YES) - Invalid query: SELECT COUNT(b.id) AS jumlah, COUNT(CASE WHEN b.sex = 1 THEN b.id END) AS laki, COUNT(CASE WHEN b.sex = 2 THEN b.id END) AS perempuan
FROM `penduduk_hidup` `b`
LEFT JOIN `tweb_wil_clusterdesa` `a` ON `b`.`id_cluster` = `a`.`id`
ERROR - 2020-06-08 07:50:05 --> 404 Page Not Found: Assets/img
ERROR - 2020-06-08 08:50:37 --> Query error: Access denied for user 'batungse_OpenSid'@'localhost' (using password: YES) - Invalid query: SELECT COUNT(b.id) AS jumlah, COUNT(CASE WHEN b.sex = 1 THEN b.id END) AS laki, COUNT(CASE WHEN b.sex = 2 THEN b.id END) AS perempuan
FROM `penduduk_hidup` `b`
LEFT JOIN `tweb_wil_clusterdesa` `a` ON `b`.`id_cluster` = `a`.`id`
ERROR - 2020-06-08 07:50:37 --> 404 Page Not Found: Assets/img
ERROR - 2020-06-08 08:51:01 --> Query error: Access denied for user 'batungse_OpenSid'@'localhost' (using password: YES) - Invalid query: SELECT COUNT(b.id) AS jumlah, COUNT(CASE WHEN b.sex = 1 THEN b.id END) AS laki, COUNT(CASE WHEN b.sex = 2 THEN b.id END) AS perempuan
FROM `penduduk_hidup` `b`
LEFT JOIN `tweb_wil_clusterdesa` `a` ON `b`.`id_cluster` = `a`.`id`
ERROR - 2020-06-08 07:51:02 --> 404 Page Not Found: Assets/img
ERROR - 2020-06-08 08:59:18 --> Query error: Access denied for user 'batungse_OpenSid'@'localhost' (using password: YES) - Invalid query: SELECT COUNT(b.id) AS jumlah, COUNT(CASE WHEN b.sex = 1 THEN b.id END) AS laki, COUNT(CASE WHEN b.sex = 2 THEN b.id END) AS perempuan
FROM `penduduk_hidup` `b`
LEFT JOIN `tweb_wil_clusterdesa` `a` ON `b`.`id_cluster` = `a`.`id`
ERROR - 2020-06-08 09:01:39 --> Query error: Access denied for user 'batungse_OpenSid'@'localhost' (using password: YES) - Invalid query: SELECT COUNT(b.id) AS jumlah, COUNT(CASE WHEN b.sex = 1 THEN b.id END) AS laki, COUNT(CASE WHEN b.sex = 2 THEN b.id END) AS perempuan
FROM `penduduk_hidup` `b`
LEFT JOIN `tweb_wil_clusterdesa` `a` ON `b`.`id_cluster` = `a`.`id`

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.06
| Versi PHP        | 7.3.18
| System operasi   | 

Linux aruna.dnsbit.net 3.10.0-962.3.2.lve1.5.35.el7.x86_64 #1 SMP Tue Apr 14 15:56:28 EDT 2020 x86_64
--

**Comment by eddieridwan** [comment]
Lihat panduan https://github.com/OpenSID/OpenSID/wiki/Tanya-Jawab-Install-dan-Update.
Baca bagian `Error import menggunakan phpmyadmin`.

Karena bukan merupakan error untuk perbaikan script OpenSID, issue ini akan kami tutup. Silakan buka lagi kalau ada informasi tambahan yg memerlukan perbaikan OpenSID.
