### ISSUE TITLE
Sempurnakan/tambahkan validasi input pada menu admin Pengaturan - Pengguna

### ISSUE THREAD

**Issue by masumo** [OpenSID/OpenSID#3177]
### Bagaimana alurnya sampai muncul masalah?
belum ada validasi pada form input atau sudah ada validasi tapi belum cukup aman untuk cegah Cross-Site Scripting (XSS)

### Seperti apa yang diharapkan?
tambahkan validasi baik melalui javascript maupun php
jika sudah ada validasi, pastikan validasi cukup aman untuk cegah XSS

### Apa yang terjadi?
upaya untuk cegah Cross-Site Scripting (XSS)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by masumo** [comment]
untuk issue ini apakah masih ada yang terlewat pak @eddieridwan ? saya tidak merubah validasi di sisi **Model** (PHP) karena saya lihat sudah dikembangkan oleh programmer sebelumnya

**Comment by eddieridwan** [comment]
Sudah dicommit ke `master` melalui PR #3222
