### ISSUE TITLE
REQUEST : Fitur Pengelolaan APBDes/Dana Desa

### ISSUE THREAD

**Issue by healm4n** [OpenSID/OpenSID#318]
dengan hormat,

Kiranya bisa ditambahkan fitur baru untuk pengelolaan Dana Desa, APBDes, dan BUMDes.
Terima Kasih.

Salam,
Hilman YB Mardiansyah

**Comment by Agus-Heriyanto** [comment]
Di issue #229 sudah Saya catat.Ini sangat berguna sekali bagi Desa yang ingin transparan....Skarang ini sementara Kami masih sarankan untuk screen shoot dari data Siskeudes kemudian di posting di SID. Menarik juga kalo bsa integrasi siskeudes dan SID Kalo misalkan memungkinkan.

**Comment by prihantosimbah** [comment]
data SID dalam bentuk "SQL data"  sementara data Siskeudes dalam bentuk "MSAccess data"

**Comment by syaifudin9** [comment]
https://drive.google.com/file/d/0B2drHUArcGpoRThJcnNuQlVXTWM/view?usp=drivesdk

**Comment by syaifudin9** [comment]
Link diatas adalah master siekeudes kab. Sidoarjo

**Comment by afri18** [comment]
kayak ini mantaaab kali ya ?? http://sikades.cigelam.desa.id/index.php/theme

**Comment by Agus-Heriyanto** [comment]
Mas syafri...itu ga integrasi dengan SID ya?

**Comment by Agus-Heriyanto** [comment]
Td liat webnya mas...ternyata pakai link gt ya u mengarhkan ke siskeudes........Mas Syafri pakai SID CRI yang web itu ya?Karena bayak tampilan yang sudah ditambahkan....sedangkan Open SID harus masuk rilis dulu untuk stp perubahan supaya tidak hilang dengan perubahan itu..

**Comment by Agus-Heriyanto** [comment]
Ya...mungkin bisa juga bentuk integrsinya seperti itu di open SID...bisa masuk di rilis terbaru..Sekalian usul ke bung eddie biar bisa dibuatkan widget tambahan untuk menempatkan tautan atau link baik yang mengarah ke web lain atau mengrah pada isi di dalam SID sendiri kayak siskeudes itu.
Mungkin bung syafri bisa bantu untuk memaprkan sedikit terkai dengan contoh widget yang di web  http://sikades.cigelam.desa.id/index.php/theme. Makasi...

**Comment by eddieridwan** [comment]
Contoh tambahan dari @mas wid (di FB):

ini contoh angaran desa yang ada dikembangkan SIDEKA, mungkin bisa dipakai contoh untuk pengembangan di opensid
http://cikadu.desa.id/data/anggaran/

**Comment by afri18** [comment]
untuk sikades itu subdomain cigelam.desa.id , masih uji coba, lom berani disebar, takut yg buat ngambek

**Comment by sugiantoe** [comment]
untuk melihat struktur database Siskeudes, Ini saya share link database latihan siskeudes Kab. Karimun Prov. Kepri.

https://drive.google.com/file/d/0B6HScqLrRy9NOHdlVHFIVlJVb0E/view?usp=sharing

username : user
Pass: user

**Comment by mizwaruddin** [comment]
@afa28 sdh ada impor siskeudes.
