### ISSUE TITLE
filter tahun anggaran

### ISSUE THREAD

**Issue by afri18** [OpenSID/OpenSID#3180]
### Bagaimana alurnya sampai muncul masalah?
saat tambah data dari Template tahun 2019 jadi menyatu dengan Tahun 2020

### Seperti apa yang diharapkan?
Sediakan Filter untuk memilih Tahun Anggaran agar mudah dalam edit data Anggaran tahun yang dituju
![image](https://user-images.githubusercontent.com/6611881/84034768-fce87b80-a9c4-11ea-8afe-475ce4d025c0.png)

### Apa yang terjadi?
Setiap tekan tombol simpan tampilan kembali memuat semua tahun anggaran,  jadi terpaksa pilih pencarian tahun yang dimaksud

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.06 pasca 08-06-2020
| Versi PHP        | 7.3
| System operasi   | win 10

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3566
