### ISSUE TITLE
Jadikan Laporan Keuangan Manual sebagai informasi publik

### ISSUE THREAD

**Issue by afri18** [OpenSID/OpenSID#3182]
### Bagaimana alurnya sampai muncul masalah?
belum tersedia link laporan keuangan manual di tampilan publik
![image](https://user-images.githubusercontent.com/6611881/84095370-55516480-aa29-11ea-9513-e32ae614d433.png)

### Seperti apa yang diharapkan?
sediakan link untuk laporan keuangan manual di tampilan publik untuk link
![image](https://user-images.githubusercontent.com/6611881/84095148-bd537b00-aa28-11ea-98b8-337005d0a9f3.png)

### Apa yang terjadi?
Melengkapi tampilan publik

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.06 pasca 08-06-2020
| Versi PHP        | 7.2
| System operasi   | win 10

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3183
