### ISSUE TITLE
Tampilan Gambar di Slider besar tidak utuh

### ISSUE THREAD

**Issue by afri18** [OpenSID/OpenSID#3184]
### Bagaimana alurnya sampai muncul masalah?
saat lihat tampilan di slider besar gambar/photo yang di tampilkan tidak utuh
![image](https://user-images.githubusercontent.com/6611881/84141189-fa495d00-aa7c-11ea-93c6-d32a78b0b817.png)

### Seperti apa yang diharapkan?
Slider besar secara auto menyesuwaikan tampilkan gambar/photo secara utuh 

### Apa yang terjadi?
Gambar/photo yang tampak kadang sepotong (tidak utuh)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.06 pasca tgl 8
| Versi PHP        | 7.2
| System operasi   | win 10

**Comment by andifahruddinakas** [comment]
Ukuran gambar perlu disesuaikan dengan tema yg digunakan.
