### ISSUE TITLE
Terdapat Pemberitahuan Pesan Masuk Pada Layanan Mandiri

### ISSUE THREAD

**Issue by gampongbarabung** [OpenSID/OpenSID#3186]
### Bagaimana alurnya sampai muncul masalah?
Apabila administrator/perangkat desa mengirimkan pesan kepada masyarakat melalui akun layanan mandirinya. Tidak ada tanda pesan masuk sehingga harus diklik di kotak masuk dulu baru dapat melihat ada pesan yang belum dibaca atau belum.

### Seperti apa yang diharapkan?
Pada Akun Layanan Mandiri Masyarakat terdapat tanda pesan masuk yang belum dibaca saat menerima pesan dari Perangkat Desa.

### Apa yang terjadi?
![Capture-100](https://user-images.githubusercontent.com/60224596/84191500-c729bc80-aac2-11ea-8098-ef271abde1e4.jpg)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.06-pasca
| Versi PHP        | 
| System operasi   | Windows

**Comment by eddieridwan** [comment]
Sudah dicommit ke `master`
