### ISSUE TITLE
Penambahan Fitur Kirim PIN baru ke WA warga 

### ISSUE THREAD

**Issue by will2469** [OpenSID/OpenSID#3188]
### Bagaimana alurnya sampai muncul masalah?
Setiap ada warga yang datang/menghubungi operator desa untuk meminta PIN pelayanan mandiri kita harus membuat template untuk NIK dan PIN yang diserahkan kepada pemohon. Karena kita tidak mungkin melayani tanpa bukti otentik pelayanan

### Seperti apa yang diharapkan?
untuk dapat disediakan fitur print NIK dan PIN agar mempermudah pelayanan, dan harap untuk formatnya kalau bisa ada dua sisi dalam hasil print. 1 sisi untuk arsip desa dan 1 sisi untuk pemohon

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Lampirkan format yg diinginkan. Juga konsultasikan dengan komunitas di FB untuk mendapat persetujuan dari desa lain.

**Comment by gampongbarabung** [comment]
Lanjutkan , hal tersebut menjamin keselamatan lupa pin terhadap masyarakat juga

**Comment by eddieridwan** [comment]
@will2469 @afa28 @gampongbarabung , ada beberapa pertimbangan untuk usulan fitur ini.
1. Sebaiknya kantor desa `tidak` mengetahui dan tidak menyimpan PIN warga. Idealnya kantor desa tidak diberi peluang untuk bisa menyamar sebagai warga
2. Sebaiknya PIN tidak dicetak, melainkan dikirim ke warga melalui cara lain. 
3. Kalau PIN lupa, sebaiknya dibuat PIN baru dan dikirim lagi ke warga. Ke depan, lebih baiki kalau ada fitur di mana warga sendiri bisa mengubah PIN mereka. Ke depan, syarat itu dimungkinkan mengguna solusi RBAC dari @fusionid yg belum sempat dibuat ulang.

Sementara itu, solusi yg mudah2an bisa diterapkan sebagai berikut:
1. Haruskan warga memasukkan nomor HP mereka ke database OpenSID
2. Haruskan warga memasang WA dengan nomor HP tersebut
3. Pada saat membuat PIN baru, PIN tersebut secara otomatis dikirim ke nomor WA tersebut.

Walaupun saya belum coba, tapi cara yg dapat dicoba untuk mengirim pesan ke nomor WA dapat dilihat di: https://stackoverflow.com/questions/48333959/send-messages-to-whatsapp-number-using-php
```
For existing phone numbers: 
<a href=\"whatsapp://send?phone=--your phone--&text=--your text--\"> 
For non existing phone numbers: 
<a href=\"https://api.whatsapp.com/send?phone=--your phone--&text=--your text--\">
```

Kalau tidak salah, rasanya @ariandii juga punya solusi untuk mengirim pesan secara otomatis ke nomor WA. 

Alternatif lain, bisa gunakan modul SMS yang ada di OpenSID. Tapi tentunya harus pasang semua perangkat yg dibutuhkan untuk menjalankan SMS.

**Comment by gampongbarabung** [comment]
Di gampong barabung dalam hal print out PIN Layanan Mandiri tidak ada arsip untuk desa. Hanya untuk si pendaftar Layanan Mandiri. Kertas yang berisikan PIN hanya untuk mengantisipasi agar masyarakat yang sudah tua atau kurang paham dalam pemanfaatan teknologi dapat menjadi panduan dalam login pada layanan mandiri. Sebelum diberikan PIN kepada masyarakat, kami menjelaskan kepada masyarakat agar Kertas yang berisikan PIN yang sudah terdaftar jangan sampai hilang dan /atau dapat diketahui oleh masyarakat lain.

**Comment by eddieridwan** [comment]
Untuk sanggup menggunakan Layanan Mandiri perlu menguasai penggunaan internet dan pengisian form online, yg cukup rumit. Bagi warga yg menguasai itu, sepertinya juga akan mempunyai HP dan juga menguasai aplikasi WhatsApp. Apakah kita bisa buat asumsi itu?

**Comment by will2469** [comment]
@eddieridwan saya setuju untuk whatsapp dan email notifikasi, karena dalam menyongsong new normal kita harus mempersiapkan segala media yang dapat mendukung program tersebut.. sebenarnya di kabupaten saya sudah ada aplikasi dukcapil untuk layanan mandiri yang juga menganjurkan setiap penduduk memiliki no hp dan email.. karena info dari dukcapil itu dimasukkan ke database siak terbaru. Namun pelayanan dukcapil hanya terbatas untuk dokumen kependudukan.. untuk penerbitan surat pendukung dan surat lainnya saya rasa layanan mandiri desa ini sangat mendukung..

**Comment by will2469** [comment]
> Di gampong barabung dalam hal print out PIN Layanan Mandiri tidak ada arsip untuk desa. Hanya untuk si pendaftar Layanan Mandiri. Kertas yang berisikan PIN hanya untuk mengantisipasi agar masyarakat yang sudah tua atau kurang paham dalam pemanfaatan teknologi dapat menjadi panduan dalam login pada layanan mandiri. Sebelum diberikan PIN kepada masyarakat, kami menjelaskan kepada masyarakat agar Kertas yang berisikan PIN yang sudah terdaftar jangan sampai hilang dan /atau dapat diketahui oleh masyarakat lain.

saya rasa untuk masing - masing anggota keluarga memiliki pin sendiri masih terlalu rumit...
melihat di web pelayanan kabupaten saya, mereka menerapkan sistem 1 akun anggota keluarga untuk dapat mengajukan pelayanan dalam 1 KK tersebut.. mungkin ini lebih ringkas,,, sehingga layanan mandiri yang berbasiskan NIK lebih baik diperluas untuk 1 KK...

**Comment by will2469** [comment]
@mizwaruddin seperti itu saya juga setuju, tapi opsi dari @eddieridwan lebih baik untuk dilakukan.
dengan model yang juga lebih baik karena dengan hal itu kita tidak perlu menggunakan layanan whatsapp api yang bisa dibilang mahal, cukup login ke whatsapp web dan kirim manual,,, dengan catatan usulan saya untuk penambahan hak akses 1 user dapat mengajukan pelayanan dalam 1 KK, karena dalam 1 KK misal orang tuanya tidak dapat melakukannya maka anaknya yang paham internet dapat melakukannya...

**Comment by WAHYUDIK** [comment]
> @will2469 @afa28 @gampongbarabung , ada beberapa pertimbangan untuk usulan fitur ini.
> 
> 1. Sebaiknya kantor desa `tidak` mengetahui dan tidak menyimpan PIN warga. Idealnya kantor desa tidak diberi peluang untuk bisa menyamar sebagai warga
> 2. Sebaiknya PIN tidak dicetak, melainkan dikirim ke warga melalui cara lain.
> 3. Kalau PIN lupa, sebaiknya dibuat PIN baru dan dikirim lagi ke warga. Ke depan, lebih baiki kalau ada fitur di mana warga sendiri bisa mengubah PIN mereka. Ke depan, syarat itu dimungkinkan mengguna solusi RBAC dari @fusionid yg belum sempat dibuat ulang.
> 
> Sementara itu, solusi yg mudah2an bisa diterapkan sebagai berikut:
> 
> 1. Haruskan warga memasukkan nomor HP mereka ke database OpenSID
> 2. Haruskan warga memasang WhatsApp di nomor HP tersebut
> 3. Pada saat membuat PIN baru, PIN tersebut secara otomatis dikirim ke nomor WA tersebut.
> 
> Walaupun saya belum coba, tapi cara yg dapat dicoba untuk mengirim pesan ke nomor WA dapat dilihat di: https://stackoverflow.com/questions/48333959/send-messages-to-whatsapp-number-using-php
> 
> ```
> For existing phone numbers: 
> <a href=\"whatsapp://send?phone=--your phone--&text=--your text--\"> 
> For non existing phone numbers: 
> <a href=\"https://api.whatsapp.com/send?phone=--your phone--&text=--your text--\">
> ```
> 
> Kalau tidak salah, rasanya @ariandii juga punya solusi untuk mengirim pesan secara otomatis ke nomor WA.
> 
> Alternatif lain, bisa gunakan modul SMS yang ada di OpenSID. Tapi tentunya harus pasang semua perangkat yg dibutuhkan untuk menjalankan SMS.

**Comment by afa28** [comment]
Klw masalah kirim pin warga ke WA atau lainnya sy setuju krn lebih memudahkan baik operaator maupun warga. Namun jika yg dibahas mengenai masalah privasi no. pin warga, justru dengan mengirimkan lewat pesan WA atau lainnya akan menyimpan history dr pesan tsb. Jika dgn melakukan cetak hanya saat membuat pin akan lebih aman. 

Tp tentunya operator yg ditunjuk adalah org2 yg bisa dipercaya untuk mewujudkan hal di atas.

pendapat sy :), silahkan berimasukan bgmna bagusnya.

**Comment by eddieridwan** [comment]
Messaging WA diencrypt end-to-end. Bukan ke group, tapi ke perorangan. Jadi hanya yg menerima mendapatnya.

**Comment by afa28** [comment]
> Messaging WA diencrypt end-to-end, dan tidak disimpan di server (kalau Telegram disimpan di server). Bukan ke group, tapi ke perorangan. Jadi hanya yg menerima mendapatnya.

Mungkin bisa di buat 2 versi/pilihan:
1. Menggunakan API WA atau sejenisnya/
2. Menggunakan print / cetak langsung.

Alasannya, kemungkinan pengguna opensid ada yg menggunakan scr offline / semi online (bisa berupa anjungan mandiri).

**Comment by eddieridwan** [comment]
Kalau desa ingin membina warga supaya menggunakan teknologi secara benar, sebaiknya tidak menggunakan akses login per KK. Karena secara hukum akan tidak bisa memastikan siapa yg sebenarnya mengakses layanan mandiri online. Kalau warga belum siap, sebaiknya jangan menggunakan Layanan Mandiri dan langsung datang ke kantor desa untuk memperoleh layanan. 

Yaitu, biar Layanan Mandiri digunakan oleh warga yg siap saja. Hindari resiko kerancuan dan celah keamanan data.

**Comment by eddieridwan** [comment]
Jadi terkait issue, sebaiknya dibatasi pada pengiriman PIN ke WA warga, dan TIDAK di-print. Lebih baik desa menerapkan penggunaan teknologi secara benar, dan tidak menggunakan cara yang sepertinya membantu tetapi justru bermasalah secara hukum dan dari segi keamanan.

**Comment by afa28** [comment]
![222222](https://user-images.githubusercontent.com/57283157/96103841-5d06a580-0f02-11eb-959c-da5ef026add0.JPG)
![Uploading 11111111.JPG…]()

**Comment by afa28** [comment]
Pak @eddieridwan , Apakah ini masuk rilis umum atau premium??? Krn u/ saat ini issuenya sy krja di branch rilis umum.

**Comment by eddieridwan** [comment]
Sebaiknya di premium. Dan kalau bisa sekalian juga menggunakan SMS. Tapi mungkin untuk SMS buatkan issue terpisah.

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalaui PR https://github.com/OpenSID/premium/pull/11
