### ISSUE TITLE
Logo otomatis pada export doc surat

### ISSUE THREAD

**Issue by Agus-Heriyanto** [OpenSID/OpenSID#319]
Kondisi ini bisa memudahkan bagi staff desa yang lain yg masih kurang pemahaman di komputer (tapi membantu pelayanan karena menggunakan beberapa omputer dengan jaringan lokal) untuk tidak mencari logo lagi di komputer sebagai pengganti sehingga semua pegawai bisa memberikan pelayanan.

**Comment by eddieridwan** [comment]
Penyesuaian logo hanya perlu dilakukan **SEKALI** untuk setiap jenis surat, dengan mengubah template RTF untuk surat tersebut. Jadi **TIDAK** mengubah setiap kali mencetak surat.

Pada saat menginstal SID dan menyiapkan bagi pengguna, salah satu tugas pegiat SID (atau petugas teknis) adalah untuk menyesuaikan setiap template jenis surat yang akan digunakan desa --- SEBELUM SID digunakan untuk penyediaan layanan surat.

**Comment by Agus-Heriyanto** [comment]
Yap.....sudah dicoba....mantap.Tp kemungkinan banyak juga dari temen2 yang
belum memahami ini....

Pada 25 Februari 2017 12.19, Eddie Ridwan <notifications@github.com>
menulis:

**Comment by metalab25** [comment]
Videonya sudah saya buatkan semoga teman" lain bisa mempelajarinya

**Comment by MUHAMMADRANGSEL** [comment]
Karena expor logo di surat kemungkinan TDK bisa langsung diambil dari Sistem karena harus disesuaikan satu persatu maka sebaiknya issue ini di closed aja mas Eddie
