### ISSUE TITLE
Error saat menambah jenis bantuan melalui edit KK

### ISSUE THREAD

**Issue by mizwaruddin** [OpenSID/OpenSID#3190]
### Bagaimana alurnya sampai muncul masalah?
Saat menambahkan jenis bantuan melalui edit KK terjadi error.
![error_bantuan](https://user-images.githubusercontent.com/39736008/84277473-c8f48e00-ab5d-11ea-8878-466a8b269bdd.PNG)
![error_bantuan2](https://user-images.githubusercontent.com/39736008/84277495-ce51d880-ab5d-11ea-91e4-ed7c6e0bcf68.PNG)

### Seperti apa yang diharapkan?
Penambahan jenis bantuan pada edit KK dihilangkan saja karena sudah tidak sesuai dengan alur penambahan peserta bantuan.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Melalui PR #3194, daftar program bantuan untuk Keluarga dari form Ubah Data KK ke halaman Daftar Anggota Keluarga.
