### ISSUE TITLE
Privasi No. KK dan NIK

### ISSUE THREAD

**Issue by afa28** [OpenSID/OpenSID#3193]
### Bagaimana alurnya sampai muncul masalah?
Untuk saat ini, dibeberapa modul, untuk aksi cetak/unduh blum ada filtering No. KK dan NIK. Sehingga saat dicetak menampilkan No. KK dan NIK scr untuh.

### Seperti apa yang diharapkan?
Tambahkan pilihan filter/sensor No. KK dan NIK sebelum mencetak/menguduh data.

### Apa yang terjadi?
Data yg dicetak bisa ditampilkan di informasi publik (papan informasi desa)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by gampongbarabung** [comment]
Cocok sekali bung, seperti halnya kita akan print Daftar Calon Pemilih NIK dan No KK tidak tersensor. Sebaiknya disensor seperti 11061212XXXXXXXX termasuk no kk nya juga

**Comment by AliAshgar** [comment]
Keinginannya data bisa di tampilkan di informasi publik ya pak?
Atau data pemilih aja yang di sensor untuk hasil nik dan kk ketika di print?

**Comment by afa28** [comment]
> Keinginannya data bisa di tampilkan di informasi publik ya pak?
> Atau data pemilih aja yang di sensor untuk hasil nik dan kk ketika di print?

Untuk saat ini hanya pd cetak/unduh dokumen yg akan di konsumsi piblik sja. Misal di tempel di papan informasi.

**Comment by gampongbarabung** [comment]
Iyaa pak data dpt pemilihan kepala desa bagian nik dan no kk dimunculkan tetapi disensor sebagian contoh 11061212XXXXXXXX . Jadi masyakarat lebih valid saat melihat data dpt

**Comment by afa28** [comment]
> Iyaa pak data dpt pemilihan kepala desa bagian nik dan no kk dimunculkan tetapi disensor sebagian contoh 11061212XXXXXXXX . Jadi masyakarat lebih valid saat melihat data dpt

Ya

**Comment by AliAshgar** [comment]
Ok, saya coba kerjakan issues ini

**Comment by AliAshgar** [comment]
> Iyaa pak data dpt pemilihan kepala desa bagian nik dan no kk dimunculkan tetapi disensor sebagian contoh 11061212XXXXXXXX . Jadi masyakarat lebih valid saat melihat data dpt

begini ya pak?


![Screenshot (81)](https://user-images.githubusercontent.com/56395293/89313562-3c70d280-d6ab-11ea-8b8b-22ad7d6dddae.png)

**Comment by AliAshgar** [comment]
> Iyaa pak data dpt pemilihan kepala desa bagian nik dan no kk dimunculkan tetapi disensor sebagian contoh 11061212XXXXXXXX . Jadi masyakarat lebih valid saat melihat data dpt

begini ya pak?
![Screenshot (82)](https://user-images.githubusercontent.com/56395293/89313714-74781580-d6ab-11ea-9b9b-d6955e847044.png)

**Comment by gampongbarabung** [comment]
Iyaa benar sekali pak. Jadi jika tampilan nya begitu maka keamanan NIK dan NO KK lebih aman tidak disalahgunakan oleh pihak lain jika kita publish

**Comment by AliAshgar** [comment]
> Iyaa benar sekali pak. Jadi jika tampilan nya begitu maka keamanan NIK dan NO KK lebih aman tidak disalahgunakan oleh pihak lain jika kita publish

Mungkin perlu dibuatkan 2 versi , yang disensor nik dan no kk dan yang gak di sensor

**Comment by afa28** [comment]
> > Iyaa benar sekali pak. Jadi jika tampilan nya begitu maka keamanan NIK dan NO KK lebih aman tidak disalahgunakan oleh pihak lain jika kita publish
> 
> Mungkin perlu dibuatkan 2 versi , yang disensor nik dan no kk dan yang gak di sensor

Sebelu mencetak, tampilkan pilihan. Mau dicetak full atau dgn sensor

**Comment by AliAshgar** [comment]
> > > Iyaa benar sekali pak. Jadi jika tampilan nya begitu maka keamanan NIK dan NO KK lebih aman tidak disalahgunakan oleh pihak lain jika kita publish
> > 
> > Mungkin perlu dibuatkan 2 versi , yang disensor nik dan no kk dan yang gak di sensor
> 
> Sebelu mencetak, tampilkan pilihan. Mau dicetak full atau dgn sensor

Ya, mksd saya begitu pak, mungkin di bagian cetak/untuk dikasih dropview pilihan tsb, kayak tombol aksi pada penduduk

**Comment by afa28** [comment]
> > > > Iyaa benar sekali pak. Jadi jika tampilan nya begitu maka keamanan NIK dan NO KK lebih aman tidak disalahgunakan oleh pihak lain jika kita publish
> > > 
> > > 
> > > Mungkin perlu dibuatkan 2 versi , yang disensor nik dan no kk dan yang gak di sensor
> > 
> > 
> > Sebelu mencetak, tampilkan pilihan. Mau dicetak full atau dgn sensor
> 
> Ya, mksd saya begitu pak, mungkin di bagian cetak/untuk dikasih dropview pilihan tsb, kayak tombol aksi pada penduduk

ok

**Comment by yonathanrizky** [comment]
apa issue ini sudah dikerjakan pak @afa28 ? kalau belum, saya coba kerjakan pak

**Comment by afa28** [comment]
> apa issue ini sudah dikerjakan pak @afa28 ? kalau belum, saya coba kerjakan pak

Silahkan.

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3567
