### ISSUE TITLE
Ubah Standard Kode Provinsi untuk Statistik Covid19

### ISSUE THREAD

**Issue by roaddee** [OpenSID/OpenSID#3196]
### Bagaimana alurnya sampai muncul masalah?
Saat ini, untuk pengaturan statistik covid19, terutama kode provinsi, masih harus mengubah kode sesuai provinsi masing-masing desa. dan setiap instalasi baru selalu kode 51 (bali) sebagai standard.
![image](https://user-images.githubusercontent.com/45786885/84407820-8b633400-ac35-11ea-8e34-1b86a5ada20e.png)

### Seperti apa yang diharapkan?
Sebaiknya standar kode provinsi diambil dari konfigurasi desa, yang sudah diisi saat awal, dan kode ini baku. kalau pun kode provinsi untuk covid19 tidak sama dengan kode provinsi dari pemerintah (kemdagri), maka tetap bisa kita entri manual. issue ini hanya untuk mengubah standard isi kode provinsi, kalau cocok ya sukur langsung bisa dipakai tanpa harus ubah lagi kodenya, kalau enggak, tetap bisa ubah sendiri.
![image](https://user-images.githubusercontent.com/45786885/84407888-a170f480-ac35-11ea-872c-1229ea8d93f5.png)

### Apa yang terjadi?
Instalasi baru akan selalu mengganti kode provinsi untuk statistik covid19

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.06
| Versi PHP        |  7.3
| System operasi   | windows

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3197
