### ISSUE TITLE
Data Bantuan Keluarga tidak Tampil

### ISSUE THREAD

**Issue by afri18** [OpenSID/OpenSID#3198]
### Bagaimana alurnya sampai muncul masalah?
Setelah pilih nama pesrta data tidak tampil/muncul
![image](https://user-images.githubusercontent.com/6611881/84456282-ca22d980-ac89-11ea-853e-070e44dfe530.png)

### Seperti apa yang diharapkan?
Seharusnya setelah memilih nama peserta data terpilih muncul/tampil

### Apa yang terjadi?
data peserta menampilkan halaman kosong

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.06 pasca tgl 11-06-2020
| Versi PHP        | 7.2
| System operasi   | win 10

**Comment by afa28** [comment]
Sdah test di demo pak???

**Comment by afri18** [comment]
> Sdah test di demo pak???

belum , ini hasil unduh di master kemarin

**Comment by afa28** [comment]
> > Sdah test di demo pak???
> 
> belum , ini hasil unduh di master kemarin

Ini biasa terjadi krn proses update tdk sesuai dgn yg disarankan di panduan.

Saran pak @afri18 , jika ingin mengikuti perkembangan versi pasca bisa gunakan git version control yg ada di cpanel (jika ada akses) untuk update agar codingannya slalu sma. Dan tentunya jika ada pembaharuan akan lebih mudah.

**Comment by afri18** [comment]
> > > Sdah test di demo pak???
> > 
> > 
> > belum , ini hasil unduh di master kemarin
> 
> Ini biasa terjadi krn proses update tdk sesuai dgn yg disarankan di panduan.
> 
> Saran pak @afri18 , jika ingin mengikuti perkembangan versi pasca bisa gunakan git version control yg ada di cpanel (jika ada akses) untuk update agar codingannya slalu sma. Dan tentunya jika ada pembaharuan akan lebih mudah.

saya update 14 Juni 2020 tapi tetap tidak tampil penerima bantuan dalam bantuan Keluarga 
![image](https://user-images.githubusercontent.com/6611881/84581111-b604e680-ae07-11ea-99b2-d8f011bbb095.png)
 KENAPA YA ???
ini digunakan offline , sudah migrasi tetap tidak tampil

**Comment by luxmant354** [comment]
pengaruh database lama, kalau menggunakan database yang baru maka data bantuan keluarga bisa tampil, jadi pengguna opensid yang lama begitu upgrade ke yang terbaru tidak bisa menampilkan data keluarga

**Comment by afri18** [comment]
> pengaruh database lama, kalau menggunakan database yang baru maka data bantuan keluarga bisa tampil, jadi pengguna opensid yang lama begitu upgrade ke yang terbaru tidak bisa menampilkan data keluarga

Solusinya ???

**Comment by afri18** [comment]
Kenapa issue d tutup ??? Ini belum ada solusinya ???
Apa yg mesti dilakukan bagi pengguna lama ???

**Comment by afa28** [comment]
Mungkin pak @afri18 salah pencet. Bisa di reopen lg isssuenya.

**Comment by afri18** [comment]
> Mungkin pak @afri18 salah pencet. Bisa di reopen lg isssuenya.

saya masih bermasalah dengan ini, apa solusinya ya ??? nggak mungkin saya ganti database, karna terlalu banyak data yg di benahi nantinya, sebagai info, database cpnel yang saya pakai dari januari 2014, belum pernag ganti, paling migrasi

**Comment by afa28** [comment]
> > Mungkin pak @afri18 salah pencet. Bisa di reopen lg isssuenya.
> 
> saya masih bermasalah dengan ini, apa solusinya ya ??? nggak mungkin saya ganti database, karna terlalu banyak data yg di benahi nantinya, sebagai info, database cpnel yang saya pakai dari januari 2014, belum pernag ganti, paling migrasi

Bisa kirim backup databasenya pak @afri18 untuk sebagai perbandingan. Lewat email: andifahruddinakas@gmail.com atau telegram:@afa_28. Insya Allah databasenya tdk sy salah gunakan, krn sy blank mau krja issue ini mau di apakan.

**Comment by afa28** [comment]
> > Mungkin pak @afri18 salah pencet. Bisa di reopen lg isssuenya.
> 
> saya masih bermasalah dengan ini, apa solusinya ya ??? nggak mungkin saya ganti database, karna terlalu banyak data yg di benahi nantinya, sebagai info, database cpnel yang saya pakai dari januari 2014, belum pernag ganti, paling migrasi
> 

Pak @roaddee mungkin bisa bantu untuk masalah ini

**Comment by afa28** [comment]
Sy cek di demo tdk ada masalah, silahkan reopen issue ini jika masih mengalami kendala.
