### ISSUE TITLE
[Bug] Form komentar di Modul Web tidak divalidasi

### ISSUE THREAD

**Issue by batudaa** [OpenSID/OpenSID#32]
Inputan di modul web mestinya divalidasi sehingga formulir kosong tidak diijinkan untuk disimpan.

**Comment by MUHAMMADRANGSEL** [comment]
#closed krn issue ini sdh dikerjakan

**Comment by batudaa** [comment]
Yakin? Boleh di rujuk commit idnya? :)

Coba langsung deh di opensid :) buat menu baru dengan data kosong dan langsung simpan,,,,

**Comment by eddieridwan** [comment]
@batudaa Issue ini terlalu luas (karena misalnya selama ini sudah ada beberapa validasi yg ditambahkan). Sebaiknya dibuat spesifik, seperti validasi pengisian menu (di modul Admin?). Silakan buat issuenya -- atau ubah issue ini menjadi spesifik. Lebih baik lagi, sekalian buat pull request untuk masalah itu ...

**Comment by siayi** [comment]
Isu ini sudah Closed atau masih Open ya?

**Comment by eddieridwan** [comment]
Judul issuenya sdh diperjelas. Ternyata masalah ini belum ada yg memperbaiki. Saat ini masih bisa menyimpan form komentar artikel walaupun tidak ada kolom yg diisi. Seharusnya setiap kolom diisi.

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR #1825
