### ISSUE TITLE
proteksi data ganda dalam memasukkan data penduduk baru

### ISSUE THREAD

**Issue by Agus-Heriyanto** [OpenSID/OpenSID#320]
Seandainya mau memasukkan data baru tapi setelah buat NIP ternyata aplikasi nolak karena sudah ada datanya, kemudian bisa di cek data yang ganda tersebut kepemilikannya siapa....Mungkin ini untk data2 yang spesifik dan tidak umum...kalo nama, alamat mungkin ga apa2...
Kalo impor excel tapi ga tau data ganda...maka aplikasi akan menunjukkan data ganda tersebut sebagi bentuk proteksi untuk di klarifikasi.

**Comment by eddieridwan** [comment]
Saat ini, pada fitur impor (baik excel maupun BIP), tidak bisa memasukkan penduduk dengan NIK sama. Pada waktu impor baris dengan NIK sama, akan meng-update penduduk yang sudah ada dengan NIP itu.

**Comment by Agus-Heriyanto** [comment]
Ya...ya....dengan sistem import itu tidak ada data ganda. Tapi kira2
bagaimana jika ada penambahan data penduduk baru lalu data nip atau KK atau
mungkin spesifik lainnya ada yang ganda...mungkin dibutuhkan juga proteksi
seperti itu bung eddie....

Pada 25 Februari 2017 12.13, Eddie Ridwan <notifications@github.com>
menulis:

**Comment by MUHAMMADRANGSEL** [comment]
Sebaiknya yg diprotek No.KK, NIK spy tdk ganda

**Comment by pandigresik** [comment]
secara database mungkin bisa ditambahkan constraint unique pada kolom nik di tabel tweb_penduduk, sehingga jika sudah ada nik yang sama akan diblok di level databasenya

**Comment by pandigresik** [comment]
begitu juga dengan no_kk pada tabel tweb_keluarga mungkin bisa ditambahkan constraint unique juga

**Comment by MUHAMMADRANGSEL** [comment]
Ini sangat penting segera di eksekusi kebtulan ini yg sering membuat data jd tdk valid, mhn para programer segera menyelesaikan issue ini

**Comment by MUHAMMADRANGSEL** [comment]
Ternyata kami mengalami maslah pada waktu input data labgsung di aplikasi data dgn nik yg sama bisa masuk shgg ini bisa membuat data tdk valid

**Comment by MUHAMMADRANGSEL** [comment]
Sekedar Informasi tuk input data penduduk dgn nik yg sama sdh tidak bisa,
Tggl sekarang tinggal input kepala keluarga dgn nomor KK masih bisa masuk

**Comment by MUHAMMADRANGSEL** [comment]
Jadi mohon para programer tuk bisa mengatasi masalah ini.

**Comment by eddieridwan** [comment]
Bung @pandigresik: apa kabar? Apa bisa bantu mengerjakan issue ini?

**Comment by pandigresik** [comment]
Mohon maaf, untuk saat ini belum bisa karena laptop saya masih sakit /
dalam perbaikan. Cara paling gampang kita batasi dari dbnya, kita set field
nik menjadi unique. Kalau mau dibatasi dari sisi aplikasi maka ketika
proses input harus melakukan pengecekan terlebih dahulu

Pada tanggal 3 Des 2017 06.53, "Eddie Ridwan" <notifications@github.com>
menulis:

Bung @pandigresik <https://github.com/pandigresik>: apa kabar? Apa bisa
bantu mengerjakan issue ini?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/OpenSID/OpenSID/issues/320#issuecomment-348758823>, or mute
the thread

**Comment by eddieridwan** [comment]
@pandigresik : membatasi di DB sepertinya belum bisa, karena mungkin ada desa yang mempunyai data duplikat. Untuk desa baru mungkin bisa.

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.

**Comment by afri18** [comment]
bagus ini, saya sering mengalami saat mouse "ngebandel" jadi tersimpan dua kali
