### ISSUE TITLE
Hit Artikel Statis Membeludak

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#3200]
### Bagaimana alurnya sampai muncul masalah?
Saat ini yang terjadi pada Website natairaya.desa.id adalah Membengkaknya hit artikel statis yang tidak wajar.

Sudah dilakukan Reset Hit melalui fitur yang tersedia di halaman siteman sebanyak 3 kali saat angka di 4ribuan. Dan saat ini masuk ke angka 6ribu hit dalam beberapa hari.

![photo6275824917954013698](https://user-images.githubusercontent.com/46939846/84484369-de37fc80-acc4-11ea-8431-771291af8e2c.jpg)

### Seperti apa yang diharapkan?
Normal kembali sesuai dengan hit user "manusia".

### Apa yang terjadi?
Agar tidak tampil artikel Populer yang bukan semestinya menjadi populer.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.06-Pasca
| Versi PHP        | 7.3

**Comment by afa28** [comment]
> ### Bagaimana alurnya sampai muncul masalah?
> Saat ini yang terjadi pada Website natairaya.desa.id adalah Membengkaknya hit artikel statis yang tidak wajar.
> 
> Sudah dilakukan Reset Hit melalui fitur yang tersedia di halaman siteman sebanyak 3 kali saat angka di 4ribuan. Dan saat ini masuk ke angka 6ribu hit dalam beberapa hari.
> 
> ![photo6275824917954013698](https://user-images.githubusercontent.com/46939846/84484369-de37fc80-acc4-11ea-8431-771291af8e2c.jpg)
> 
> ### Seperti apa yang diharapkan?
> Normal kembali sesuai dengan hit user "manusia".
> 
> ### Apa yang terjadi?
> Agar tidak tampil artikel Populer yang bukan semestinya menjadi populer.
> 
> ### Informasi tambahan
> Tanya	Jawab
> Versi OpenSID	20.06-Pasca
> Versi PHP	7.3

Harus ada website percontohan untuk ini, krn sy krja offline jd sy tdk bisa melakukan tracking siapa sj yg melakukan hit. 

Solusi sementara, menyimpan data yg melakukan hit (buat table baru) dimana user agentnya selain platform, browser, dan mobiles yg tdk terdaftar di CI3 dan melakukan block pd daftar tsb.

Atau bisa dibalik, data yg terhitung sebagai hit adalah user agentnya platform, browser, dan mobiles yg tdk terdaftar di CI3.

**Comment by ariandii** [comment]
![Screenshot_2020-06-12-18-33-17-23](https://user-images.githubusercontent.com/46939846/84498674-514c6d80-acdb-11ea-88ca-5bf2d7cd279c.png)

ternyata desa sered juga polanya sepertinya sama.

**Comment by ariandii** [comment]
![103426923_1519296681568993_6279871232241960732_o](https://user-images.githubusercontent.com/46939846/84500606-15b3a280-acdf-11ea-8090-7030ac698d72.jpg)

web desa pancamulia juga mengalami hal yang sama.

**Comment by afri18** [comment]
Nstaraya juga tema , mungkin banyak peminat yg menggandrungi, jadi artikel nya pun di jadikan contoh, mungkin ....

**Comment by PWidodo** [comment]
Saya kemarin buat artikel statis baru pakai tema COSMO hasilnya mengejutkan sekali. baru 2 hari posting sudah dilihat oleh 39.076 pengunjung. Ini sungguh tidak relevan. Mohon untuk segera di PR issue diatas. cc. @ariandii
