### ISSUE TITLE
Artikel Non Aktif masih bisa Tampil

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#3201]
### Bagaimana alurnya sampai muncul masalah?
Setelah menonaktifkan artikel, ternyata link artikel tersebut masih dapat di akses publik.

### Seperti apa yang diharapkan?
Sesuai dengan pengaturan yang diinginkan.
Misal status non aktif, maka URL artikel tersebut bisa diarahkan ke 404.

### Apa yang terjadi?
Supaya mengikuti kemauan admin apakah artikel dimaksud waktunya publish atau pending.

**Comment by eddieridwan** [comment]
Sudah dicommit ke `master` melalui PR #3246
