### ISSUE TITLE
SILPA Pada Laporan APBDes Tidak Terealisasi

### ISSUE THREAD

**Issue by gampongbarabung** [OpenSID/OpenSID#3203]
### Bagaimana alurnya sampai muncul masalah?
Pada SISKEUDES Silpa Tahun Sebelumnya sudah direalisasikan pada awal tahun dan jika dilihat pada pembukuan di bagian realisasi anggaran SILPA Tahun sebelumnya muncul angka realisasinya. tetapi pada Output Laporan APBDes angka realisasi Pembiayaan 1 Tentang SILPA Tahun sebelumnya tidak muncul

### Seperti apa yang diharapkan?
Angka SILPA Tahun sebelumnya tampil sesuai output SISKEUDES

### Apa yang terjadi?
1. Gambar Tidak Muncul Realisasi SILPA Tahun Sebelumnya pada Laporan Output OPENSID
![Capture1](https://user-images.githubusercontent.com/60224596/84540076-dc9b2280-ad1e-11ea-9ff2-8640350217ee.JPG)

2. Gambar Muncul Realisasi SILPA Tahun Sebelumnya pada Aplikasi SISKEUDES
![Capture2](https://user-images.githubusercontent.com/60224596/84540122-f89ec400-ad1e-11ea-9cee-fffa3f671248.JPG)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by fusionid** [comment]
https://github.com/OpenSID/OpenSID/wiki/Laporan-Keuangan Poin No. 3 :

> Nilai realisasi pembiayaan akan 0 jika belum melakukan proses pra-penatausahaan yaitu diharuskan membuat jurnal umum supaya SILPA tahun sebelumnya bisa digunakan/tercatat di realisasi. Jumlah Realisasi pada Akun : 6.1.Penerimaan Pembiayaan, Sub Akun : 6.1.1. SILPA Tahun Sebelumnya, diperoleh jika ada transaksi pada Jurnal Umum yg biasanya dicatat di awal tahun atau kemudian pada jurnal penyesuaian.

**Comment by gampongbarabung** [comment]
![Capture](https://user-images.githubusercontent.com/60224596/84708511-dc9f5a80-af8a-11ea-97d0-e5754442dbb8.JPG)

Sudah dilakukan realisasi pak seperti yang dimaksud.

![Capture1](https://user-images.githubusercontent.com/60224596/84708618-0a849f00-af8b-11ea-8e59-379707732fb9.JPG)
Pada Grafik Halaman Website terlihat sudah terealisasi SILPA Tahun Sebelumnya.

![Capture2](https://user-images.githubusercontent.com/60224596/84708704-3011a880-af8b-11ea-9edc-b52e3df01c86.JPG)
Tetapi Pada Grafik Perkegiatan SILPA Tahun Sebelumnya tidak tampil

**Comment by fusionid** [comment]
Untuk review apakah sudah melakukan pra-penatausahaan di jurnal umum :  lihat di file Ta_JurnalUmumRinci.csv di file zip konversinya. Total Nilai pada kolom Kredit adalah Total Nilai Realisasi Penerimaan Pembiayaan

![silpa](https://user-images.githubusercontent.com/10391199/84733456-75a09680-afc8-11ea-9bb4-12a53a993cb1.png)

**Comment by gampongbarabung** [comment]
![Capture](https://user-images.githubusercontent.com/60224596/84733980-f44a0380-afc9-11ea-9059-f50c474b94fa.JPG)

Apakah ada yang salah pak dari gambar diatas??

**Comment by fusionid** [comment]
Ya ada yg salah, responnya terlalu cepat 👍 
Bisa dikirim file zipnya ke email saya ? (alamat email pm di FB)

**Comment by gampongbarabung** [comment]
Pada Saldo Awal, SILPA Tahun Sebelumnya di input pada Rekening Kas Desa karena uang SILPA nya di Rekening Kas Desa. Jadi Saat Penjurnalan kami input seperti ini : 
Debet : ke akun 3.1.2.01 (Ekuitas SAL)
Kredit : ke akun 1.1.1.02 (Rekening Kas Desa)

Pada SISKEUDES kami, Akun 6.1.1.01 (SILPA Tahun Sebelumnya) tidak ada pada pilihannya.
![Capture](https://user-images.githubusercontent.com/60224596/84748516-f2d90500-afe2-11ea-892b-0b8340a19234.JPG)

**Comment by MantoAta** [comment]
itu input saldo awal di siskeudesnya kebalik pak, seharusnya
rekening kas desa ( 1.1.102 ) = debet
ekuitas saldo ( 3.1.2.01 ) = kredit

**Comment by mizwaruddin** [comment]
@afa28 terjadi karena kesalahan pada input data di siskeudes, bukan pada OpenSID.

**Comment by PekonJatiagung** [comment]
![IMG_20210112_112101](https://user-images.githubusercontent.com/77314163/104269449-e5c4bb80-54c8-11eb-96ca-8a4ac4e1c2c4.jpg)

![Uploading IMG_20210112_112037.jpg…]()



mohon kiranya di bantu ya pak bu
kenapa silpa berjalan tidak sesuai dengan buki bank
terimakasih
