### ISSUE TITLE
Haruskan pengguna untuk membaca dan menyetujui syarat penggunaan OpenSID

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#3205]
### Bagaimana alurnya sampai muncul masalah?
Saat ini pengguna tidak diharuskan secara eksplisit membaca dan menyetujui syarat penggunaan OpenSID.

### Seperti apa yang diharapkan?
Sebelum pertama kali menggunakan OpenSID, ditampilkan pengumuman yang:
1. mengharuskan pengguna membaca dan menyetujui lisensi GPL V3
2. mengingatkan pengguna bahwa penggunaan OpenSID adalah berdasarkan `apa adanya` dan adalah tanggung jawab pengguna untuk menjamin keamanan data desa
3. mengingatkan pengguna untuk tidak sekali-kali menggunakan password default, dan untuk rajin mengubah semua password pengguna, termasuk PIN pengguna  Layanan Mandiri
4. mengingatkan pengguna untuk rutin melakukan update data desa, termasuk folder `desa`.
5.  mengetahui dan menyetujui adanya tracker [untuk dilengkapi]

Ada tombol supaya peringatan dan persetujuan ini tidak ditampilkan lagi.

### Informasi tambahan 
Solusi untuk issue ini bisa menggunakan kolom tambahan di tabel `config`. Kolom itu bisa menyimpan tanggal peringatan ini disetujui. Juga bisa ditambah ketentuan untuk menampilkan peringatan ini setiap 6 bulan untuk mengingatkan admin tanggung jawab  pengguna 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | v20.06
| Versi PHP        | 
| System operasi   |

**Comment by masumo** [comment]
tampilan pengumuman seperti apa pak @eddieridwan ?
apa cukup menggunakan window konfirmasi (javascript modal) seperti pada saat mau hapus data?

pengumuman diletakkan di mana? halaman publik atau admin?

**Comment by eddieridwan** [comment]
@masumo Lihat pembahasan di https://github.com/OpenSID/OpenSID/issues/3206. Sebaiknya kolaborasi dengan @afa28 supaya sinkron.

**Comment by afa28** [comment]
Beberapa perbaikan sudah sy sesuaikan di branch `tracking`, mungkin bisa di cek ulang sebelum di merge ke brach `master`.

**Comment by masumo** [comment]
> Beberapa perbaikan sudah sy sesuaikan di branch `tracking`, mungkin bisa di cek ulang sebelum di merge ke brach `master`.

makasih mas... saya setuju saja.. kemarin juga ada koreksi dari pak eddie

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master`.
