### ISSUE TITLE
Sempurnakan/tambahkan validasi input pada menu admin Penduduk > Pencarian Spesifik

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#3209]
### Bagaimana alurnya sampai muncul masalah?
belum ada validasi pada form input atau sudah ada validasi tapi belum cukup aman untuk cegah Cross-Site Scripting (XSS)

### Seperti apa yang diharapkan?
ambahkan validasi baik melalui javascript maupun php
jika sudah ada validasi, pastikan validasi cukup aman untuk cegah XSS

### Apa yang terjadi?
Sebagai contoh, masukkan teks sebagai berikut di form pencarian:
<img width="1419" alt="pencarian-1" src="https://user-images.githubusercontent.com/249563/85189244-96325e80-b2f0-11ea-9031-d9e6f07d4241.png">

Akan tampil alert sbb:
<img width="448" alt="pencarian-3" src="https://user-images.githubusercontent.com/249563/85189248-a0ecf380-b2f0-11ea-95f6-dcc13ed51353.png">

Dan error database sbb:
<img width="1419" alt="pencarian-2" src="https://user-images.githubusercontent.com/249563/85189256-ae09e280-b2f0-11ea-9e70-e0f6a3da796c.png">

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | v20.06
| Versi PHP        | 
| System operasi   |

**Comment by heriwahyudianto** [comment]
dimana letak file nya?

**Comment by ianskids** [comment]
akan saya kerjakan

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3253
