### ISSUE TITLE
Menampilkan Poto Kepala Keluarga di Menu Keluarga

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#3211]
### Bagaimana alurnya sampai muncul masalah?
Di Menu Kependudukan ==>Keluarga Poto Kepala Keluarga Tidak muncul Seperti di Menu Penduduk
![Kolom poto](https://user-images.githubusercontent.com/25834335/84570145-fe97b200-adbd-11ea-8d06-286ffa169d9c.png)
### Seperti apa yang diharapkan?
Foto Kepala Keluarga Tampil di menu Keluarga seperti gambar dibawah ini : 
![Kolom poto0](https://user-images.githubusercontent.com/25834335/84570195-61894900-adbe-11ea-8559-4ebed95282ce.png)

### Apa yang terjadi?
Dengan adanya fasilitas menambahkan foto di OpenSID diharapkan kedepan semua Data Kependudukan yang ada memiliki Foto supaya mempermudah pemerintah desa mengetahui data yang bersangkutan

### Informasi tambahan 
Dengan Adanya Foto di Dalam OpenSID bisa mengatasi Salah sasaran terkait dengan Penerima Bantuan Apalagi Sekarang ini di masa Pandemi Covid-19 sangat membantu sekali pemerintah Desa
| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
Salah pencet

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3238
