### ISSUE TITLE
[Buku Admin Desa] Buku Peraturan di Desa perlu dibuatkan Jenis Pilihan Peraturan Desa

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#3212]
### Bagaimana alurnya sampai muncul masalah?
Ketika ingin menambahkan Peraturan Desa di Menu Buku Administrasi Desa==>Administrasi Umum==>Buku Peraturan Desa di Kolom Jenis Peraturan didesa perlu dibuatkan pilihan 
Adapun Jenis Peraturan Desa :
1. Peraturan Desa (Perdes)
2. Peraturan Kepala Desa (Perkades)
3. Peraturan Bersama Kepala Desa
![peraturan](https://user-images.githubusercontent.com/25834335/84570633-479d3580-adc1-11ea-81f0-196baba1e6c5.png)

### Seperti apa yang diharapkan?
DiKolom PJenis Peraturan Desa ada pilihan  :
1. Peraturan Desa (Perdes)
2. Peraturan Kepala Desa (Perkades)
3. Peraturan Bersama Kepala Desa
untuk menghindari kesalahan dalam penginputan jenis peraturan desa

### Apa yang terjadi?
Sekarang harus diinput secara manual sehingga ketika tidak jeli waktu entri maka perlu diedit kembali

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by maulinniam** [comment]
Pada Jenis Peraturan perlu ditambahkan juga **Peraturan BPD** dan **Keputusan BPD** sesuai dengan Permendagri No 110 tahun 2016

**Comment by af-lazuardi** [comment]
Okay noted pak. Saya kerjakan.

> Pada Jenis Peraturan perlu ditambahkan juga **Peraturan BPD** dan **Keputusan BPD** sesuai dengan Permendagri No 110 tahun 2016

Peraturan BpD dan keputusan BPD apa ya itu pak? (kepanjangan BPd)? Dan apakah field2 nya sama

**Comment by MUHAMMADRANGSEL** [comment]
Untuk Keputusan BPD punya Buku Khusus

Pada tanggal Sen, 15 Jun 2020 08.47, Arif F Lazuardi <
notifications@github.com> menulis:

**Comment by maulinniam** [comment]
> Okay noted pak. Saya kerjakan.
> 
> > Pada Jenis Peraturan perlu ditambahkan juga **Peraturan BPD** dan **Keputusan BPD** sesuai dengan Permendagri No 110 tahun 2016
> 
> Peraturan BpD dan keputusan BPD apa ya itu pak? (kepanjangan BPd)? Dan apakah field2 nya sama

BPD kepanjangan dari Badan Permusyawaratan Desa.

Betul kata bang @MUHAMMADRANGSEL BPD memiliki Buku/Panduan Administrasi. Ini saya usulkan karena BPD merupakan lembaga yang tak terpisahkan dari Penyelenggaraan Pemerintahan Desa namun jarang sekali mendapatkan perhatian. Padahal kedudukan BPD sama pentingnya dengan Pemerintah Desa (Kepala Desa dan perangkat).
Terima kasih atensinya. Salam Berdesa!

**Comment by eddieridwan** [comment]
Pilihan jenis peraturan desa sudah dicommit ke branch `bumindes` di repo `premium`.

Peraturan dan keputusan BPD sebaiknya dibuat issue tersendiri, karena merupakan buku dan peraturan tersendiri.

**Comment by HerryWanda** [comment]
Pak @eddieridwan , tambahan keterangan pak...
Untuk Perdes : 
1.Peraturan Desa (Perdes)
2.Peraturan Kepala Desa (Perkades)
3. Peraturan Bersama Kepala Desa

Ini untuk penomoran masing-masing yang berbeda.

Kemudian memiliki rekap masing2 dari peraturan diatas pak.
Setelah saya coba mencetak rekap, belum ada pilihan untuk memisahkan antara 3 jenis peraturan tersebut diatas. Jadi pas dicetak nantik tercampur registrasinya.

Jadi usulan, mungkin diberi menu pilihan pas cetak rekap atau untuk melihat jenis peraturan : 
![r](https://user-images.githubusercontent.com/32125282/88263380-2ac71c80-ccf4-11ea-8427-258804ab5a16.jpg)

Kemudian pada menu cetak diberi juga pilihan jenis peraturan yang akan di cetak ;
![kd](https://user-images.githubusercontent.com/32125282/88263711-a6c16480-ccf4-11ea-87d7-eb5b29911135.jpg)

**Comment by eddieridwan** [comment]
@HerryWanda issue ini sdh ditutup. Perubahan harap buat issue baru. Kali ini saya sdh buatkan issue https://github.com/OpenSID/OpenSID/issues/3363.

**Comment by HerryWanda** [comment]
Ok pak @eddieridwan
