### ISSUE TITLE
Urutkan Nomor Rumah Tangga

### ISSUE THREAD

**Issue by afri18** [OpenSID/OpenSID#3213]
### Bagaimana alurnya sampai muncul masalah?
Saat buka menu Rumah tangga terasa janggal, tampilan Nomor urutnya tidak beraturan
![image](https://user-images.githubusercontent.com/6611881/84581553-94f2c480-ae0c-11ea-9730-51018fc726dc.png)

### Seperti apa yang diharapkan?
Tampilkan data Rumah Tangga berurutan dari yang terkecil
![image](https://user-images.githubusercontent.com/6611881/84581584-f74bc500-ae0c-11ea-8e7b-c3b946ad211f.png)

### Apa yang terjadi?
Nggak enak dilihat karna tidak beraturan

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.06 pasca 14-06-2020
| Versi PHP        | 7.2
| System operasi   | win 10

**Comment by afa28** [comment]
> ### Bagaimana alurnya sampai muncul masalah?
> Saat buka menu Rumah tangga terasa janggal, tampilan Nomor urutnya tidak beraturan
> ![image](https://user-images.githubusercontent.com/6611881/84581553-94f2c480-ae0c-11ea-9730-51018fc726dc.png)
> 
> ### Seperti apa yang diharapkan?
> Tampilkan data Rumah Tangga berurutan dari yang terkecil
> ![image](https://user-images.githubusercontent.com/6611881/84581584-f74bc500-ae0c-11ea-8e7b-c3b946ad211f.png)
> 
> ### Apa yang terjadi?
> Nggak enak dilihat karna tidak beraturan
> 
> ### Informasi tambahan
> Tanya	Jawab
> Versi OpenSID	20.06 pasca 14-06-2020
> Versi PHP	7.2
> System operasi	win 10

Ini di urut berdasarkan data terakhir yg di input, adapun untuk mengurutkan sesuai No. RT bisa langsung di klik sja di judul tsb. Untuk default pengurutan sy rata tdk perlu terlalu dipermasalahkan krn sudah disediakan fungsi untuk mengurutkan, takutnya nanti ada issue yg sama dgn pengurutan yg berbeda lg.

**Comment by afri18** [comment]
> > ### Bagaimana alurnya sampai muncul masalah?
> > Saat buka menu Rumah tangga terasa janggal, tampilan Nomor urutnya tidak beraturan
> > ![image](https://user-images.githubusercontent.com/6611881/84581553-94f2c480-ae0c-11ea-9730-51018fc726dc.png)
> > ### Seperti apa yang diharapkan?
> > Tampilkan data Rumah Tangga berurutan dari yang terkecil
> > ![image](https://user-images.githubusercontent.com/6611881/84581584-f74bc500-ae0c-11ea-8e7b-c3b946ad211f.png)
> > ### Apa yang terjadi?
> > Nggak enak dilihat karna tidak beraturan
> > ### Informasi tambahan
> > Tanya	Jawab
> > Versi OpenSID	20.06 pasca 14-06-2020
> > Versi PHP	7.2
> > System operasi	win 10
> 
> Ini di urut berdasarkan data terakhir yg di input, adapun untuk mengurutkan sesuai No. RT bisa langsung di klik sja di judul tsb. Untuk default pengurutan sy rata tdk perlu terlalu dipermasalahkan krn sudah disediakan fungsi untuk mengurutkan, takutnya nanti ada issue yg sama dgn pengurutan yg berbeda lg.

menurut saya penting, minimal urut berdasarkan dusun>Rw>Rt>no urut Rumah Tangga, Nantinya NOMOR RUMAH bisa mengacu kesini

**Comment by afa28** [comment]
> > > ### Bagaimana alurnya sampai muncul masalah?
> > > Saat buka menu Rumah tangga terasa janggal, tampilan Nomor urutnya tidak beraturan
> > > ![image](https://user-images.githubusercontent.com/6611881/84581553-94f2c480-ae0c-11ea-9730-51018fc726dc.png)
> > > ### Seperti apa yang diharapkan?
> > > Tampilkan data Rumah Tangga berurutan dari yang terkecil
> > > ![image](https://user-images.githubusercontent.com/6611881/84581584-f74bc500-ae0c-11ea-8e7b-c3b946ad211f.png)
> > > ### Apa yang terjadi?
> > > Nggak enak dilihat karna tidak beraturan
> > > ### Informasi tambahan
> > > Tanya	Jawab
> > > Versi OpenSID	20.06 pasca 14-06-2020
> > > Versi PHP	7.2
> > > System operasi	win 10
> > 
> > 
> > Ini di urut berdasarkan data terakhir yg di input, adapun untuk mengurutkan sesuai No. RT bisa langsung di klik sja di judul tsb. Untuk default pengurutan sy rata tdk perlu terlalu dipermasalahkan krn sudah disediakan fungsi untuk mengurutkan, takutnya nanti ada issue yg sama dgn pengurutan yg berbeda lg.
> 
> menurut saya penting, minimal urut berdasarkan dusun>Rw>Rt>no urut Rumah Tangga, Nantinya NOMOR RUMAH bisa mengacu kesini

Next update sy perbaiki pak @afri18, dengan ketentuan sbb:
1. Default pngurutan diambil dr kolom unik (mungin berlaku di modul lain)
2. Sediakan pengurutan berdasarkan kolom tgl_buat, dll(jika diperlukan)

Tp sebelumnya pak @afri18 di issue #3121 yg pernah di buat adalah kebalikan dr issue ini, takutnya akan terus berulang.

**Comment by afa28** [comment]
Sdh dicommit ke master melalui PR #3389
