### ISSUE TITLE
Amankan Responsive File Manager

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#3214]
### Bagaimana alurnya sampai muncul masalah?
Responsive File Manager mempunyai banyak celah keamanan dan perlu diamankan.

### Seperti apa yang diharapkan?
Pertahanan tingkat tinggi telah diterapkan. Lihat pembahasan di https://opensid.slack.com/archives/C6VKTLQJV/p1592035092005000 

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | v20.06
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
@fusionid usulan teman2 yg sepertinya baik dilakukan untuk issue ini:
1. menerbitkan key RFM baru secara dinamis (untuk setiap session?), supaya terus berubah dan tidak bisa digunakan tanpa login dulu.
2. menyimpan key RFM di `desa/config/config.php` dalam bentuk encrypted.
3. perbaikan lain sesuai analisis anda

**Comment by esyede** [comment]
Kalau misalnya diubah dengan regex boleh tidak pak?
Saya tadi coba seperti ini:

```php
$path = FCPATH.'desa'.DIRECTORY_SEPARATOR.'config'.DIRECTORY_SEPARATOR.'config.php';
$subject = file_get_contents($path);
$pattern = '/(\$config\[(\'|\")file_manager(\'|\")\])\h*=\h*(\'|\")(.*?)(\'|\")?.*/i';

$matches = preg_grep($pattern, explode("\n", $subject));

if (is_array($matches) && isset(($matches = array_values($matches))[0])) {
	echo 'ketemu: '.$matches[0];
	// $replacement = "\$config['file_manager'] = 'FooBarBaz';"; // 'FooBarBaz' ini random encrypted key
	// $data = str_replace($matches[0], $replacement, $subject);
	// file_put_contents($path, $data);
} else {
	echo 'tidak ketemu';
}
```

**Comment by eddieridwan** [comment]
Sudah dicommit ke `master`.
