### ISSUE TITLE
Cegah jalankan PHP di setiap folder upload file

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#3223]
### Bagaimana alurnya sampai muncul masalah?
Saat ini kalau ada peretas yg berhasil mengunggah script backdoor ke subfolder `desa` tempat upload file, maka script itu bisa dijalankan.

### Seperti apa yang diharapkan?
Cegah script backdoor dijalankan, walaupun telah berhasil diunggah.

### Informasi tambahan 
Sediakan file `.htaccess` pencegah di `desa-contoh` untuk setiap folder tempat mengunggah file.
Pada proses migrasi, periksa setiap folder `desa` tempat mengunggah file dan tambahkan file `.htaccess` pencegah secara otomatis kalau belum ada.

Contoh isi file `.htaccess` tersebut:
```
<FilesMatch "\.(php|php\.|txt)$">
Order Allow,Deny
Deny from all
</FilesMatch>
```
Mungkin juga bisa tambahkan
`php_flag engine off`

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | v20.06
| Versi PHP        | 
| System operasi   |

**Comment by roaddee** [comment]
ini dijalankan mirip amankan_folder_desa() ya pak, tapi di copy ke folder ` desa ` atau `desa-contoh` ?, karena kalau ke folder `desa-contoh`, berarti folder `desa` yang lama tidak akan kebagian.

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3227
