### ISSUE TITLE
Error 500 saat insert Menu Statis untuk Artikel Statis

### ISSUE THREAD

**Issue by hasap86** [OpenSID/OpenSID#3225]
### Bagaimana alurnya sampai muncul masalah?
Saat menambahkan menu Halaman Statis terjadi error 500

### Seperti apa yang diharapkan?
tidak error

### Apa yang terjadi?
tidak bisa insert menu

### Informasi tambahan 
![insert-menu-statis](https://user-images.githubusercontent.com/45263721/84976489-32722f00-b152-11ea-90af-4257acd986a0.png)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.06-Pasca 18/06/2020
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
Sudah di perbaiki melalui PR #3221, tunggu di merge

**Comment by eddieridwan** [comment]
Sudah dicommit ke `master` melalui PR #3221
