### ISSUE TITLE
Tidak bisa ubah RW/RT saat mengganti alamat DUSUN Ketika Ubah KK

### ISSUE THREAD

**Issue by roaddee** [OpenSID/OpenSID#3229]
### Bagaimana alurnya sampai muncul masalah?
Beberapa desa ada yang tidak memiliki wilayah RT dan RW tapi hanya DUSUN saja, sehingga RT dan RW diisi '-' (minus). Ketika melakukan edit data KK, kemudian dilanjutkan dengan mengganti Dusun sesuai pilihan dropdown, maka RW dan RT tidak memunculkan pilihan.
![image](https://user-images.githubusercontent.com/45786885/85034783-a17c7180-b1ac-11ea-832a-ebd80fe1d833.png)

### Seperti apa yang diharapkan?
Seharusnya RW dan RT Memunculkan '-' seperti yang bisa dilakukan saat melakukan ubah data Penduduk Individual.
![image](https://user-images.githubusercontent.com/45786885/85035392-4dbe5800-b1ad-11ea-8812-883531b42aa1.png)

### Apa yang terjadi?
Desa Tidak bisa melakukan ubah data KK, karena ketika disimpan, akan muncul notifikasi kalau RW belum diisi.
![image](https://user-images.githubusercontent.com/45786885/85036079-1bf9c100-b1ae-11ea-9716-eb484adfc052.png)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.06-Pasca
| Versi PHP        | 7.2
| System operasi   | Windows10

**Comment by eddieridwan** [comment]
Bukan karena tdk ada RW dan RT. Bisa coba di https://demo.opensid.my.id membuat dusun tanpa RW/RT. Tidak masalah.

Masalah yg ditemukan di salah satu contoh database desa adalah tidak lengkapnya tabel `setting_modul`, sehingga controller `Wlayah` tidak bisa dipanggil. Penambahan controller `Wilayah` ke `setting_modul` dilakukan di `donjo-app/models/migrations/Migrasi_1909_ke_1910.php`. Jadi sepertinya masalahnya terjadi pada proses migrasi yg tidak berjalan lengkap -- dan mungkin sudah lama terjadi. 

Kalau masalah ini terjadi di beberapa desa di satu wilayah, ada kemungkinan karena proses yg dilakukan oleh pendamping yg membantu desa2 tersebut. 

Solusi singkatnya adalah mengganti tabel `setting_modul` dengan yang ada di `contoh_data_awal_20200601.sql`. Tetapi ini tidak menjamin tidak adanya kesalahan database lainnya.

**Comment by eddieridwan** [comment]
Setelah dijelaskan oleh @roaddee , masalah ini sudah ok di form penduduk. Tapi masih terjadi di form Ubah Data KK. Jadi konfirmasi ini adalah bug.

**Comment by afa28** [comment]
Apa maksudnya bgni??? #3229

**Comment by roaddee** [comment]
> Apa maksudnya bgni??? #3237

iya, betul
sudah saya coba bisa
tinggal nunngu review pak @eddieridwan 
![image](https://user-images.githubusercontent.com/45786885/85215779-65613080-b3a7-11ea-951d-51125524930e.png)

**Comment by afa28** [comment]
Sdh dicommit ke `master ` melaui PR #3233
