### ISSUE TITLE
Tidak Bisa Pilih Pengaturan Program Bantuan

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#3234]
### Bagaimana alurnya sampai muncul masalah?
Saat login halaman admin, pada tampilan utama menunjukkan jumlah penerima program bantuan.

Namun saat ini, pilihan program bantuan yang akan ditampilkan tidak dapat berfungsi saat di klik.

### Seperti apa yang diharapkan?
Kembali normal seperti semula.

### Apa yang terjadi?
Suaya dapat memilih kembali Program Bantuan apa yang akan ditampilkan pada halaman utama saat Login Siteman.

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master`
