### ISSUE TITLE
Kesalahan dalam menampilkan data rt dan total (KK, L+P, L, P)

### ISSUE THREAD

**Issue by afa28** [OpenSID/OpenSID#3245]
### Bagaimana alurnya sampai muncul masalah?
1. Data pd RT total (KK, L+P, L, P) tdk muncul. (Gambar 1)
![1](https://user-images.githubusercontent.com/57283157/85293002-ecf19100-b4c6-11ea-92fb-1f8aab9e45d4.JPG)

2. Keslahan dalam menampilkan data RT (Gambar 2). Klik detail RT pd kolom RT, maka data RT yg ditampilkan kosong.
![2](https://user-images.githubusercontent.com/57283157/85293086-0b578c80-b4c7-11ea-9c81-18496aee6774.JPG)

### Seperti apa yang diharapkan?
Kembali normal

### Apa yang terjadi?
Data yg ditampilkan sesuai

### Informasi tambahan 
Terjadi krn perubahan parameter yg diterima dari nama menjadi id, namun tdk dilakukan penyesuaian.

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3239
