### ISSUE TITLE
Perlu tambahan validasi input identitas desa???

### ISSUE THREAD

**Issue by afa28** [OpenSID/OpenSID#3249]
### Bagaimana alurnya sampai muncul masalah?
![333](https://user-images.githubusercontent.com/57283157/85359453-80b37380-b540-11ea-99e1-3aec486ab06f.JPG)

Validasi:
1. Kode pos : input angka
2. Telepon : input angka
3. Kode desa, kecamatan, kabupaten dan provinsi :  input angka
4. NIP Camat, Kepala Desa : input angka dan spasi
5. Lainnya : Huruf dan angka

### Seperti apa yang diharapkan?
Ada validasi

### Informasi tambahan 
Saran : untuk data nip dan nama kepala desa bisa diambil dari modul pemerintah desa dengan jabatan kepala desa agar tdk kerja 2 kali (mengikuti perubahan yg ada di modul pemerintah desa). 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3264
