### ISSUE TITLE
[Pengurus] Gelar untuk pemerintah desa yg diambil dari data penduduk

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#3255]
### Bagaimana alurnya sampai muncul masalah?
Saat ini pemerintah desa yg diambil dari data penduduk namanya tdk bisa di edit untuk menambahkan gelar. Sehingga untuk pemerintah desa yg mempunya gelar harus membuat databaru yg tdk diambil dari data penduduk(solsui awal) yg dalam artian kerja 2 kali.

### Seperti apa yang diharapkan?
Bisa menambahkan gelar pada pemerintah desa yg diambil dari penduduk.

### Apa yang terjadi?
Tidak perlu kerja 2 kali.

### Informasi tambahan 
Pernah ada yg bahas di telegram, jd sy buatkan issue. Solusi yg diberika saat itu, buat data manual (bukan dari data penduduk)
| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by gampongbarabung** [comment]
setuju pak

**Comment by balongbesuk** [comment]
berhubungan #1024

**Comment by afa28** [comment]
> berhubungan #1024

beda dan tdk berhubungan.

**Comment by balongbesuk** [comment]
> 
> 
> > berhubungan #1024
> 
> beda dan tdk berhubungan.

tambah judul lebih spesifik gelar jabatan, agar tidak rancu dengan gelar akademik, dll

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1345
