### ISSUE TITLE
Pemohon Surat Keterangan Nikah N1 Sampai N7 Harusnya Bisa Laki Laki Dan Perempuan

### ISSUE THREAD

**Issue by kayangan** [OpenSID/OpenSID#3259]
Pada Surat Permohonan Keterangan Nikah yang ada di sistem Pemohonnya Cuma Laki-Laki Saja ..
seharusnya Pemohon Surat Tersebut bisa untuk Mempelai perempuan juga.

Kenyataan di desa yang menikah itu ada laki-laki dan perempuan dan oleh KUA masing-masing harus membawa surat pengantar nikah dan izin orang tua masing-masing yang (KUA menyebutnya NA Sebelah Untuk Masing-masing mempelai)

**Comment by eddieridwan** [comment]
Apakah anda sudah perhatikan semua surat yg dihasilkan saat ini. Sepertinya sudah menghasilkan untuk kedua mempelai sekaligus. Coba periksa dulu.

**Comment by Nurhidayat29** [comment]
sudah ada sejak lama untu permohonan catin laki-laki dan perempuan, selebihnya bisa ditambahkan di rtf jika ada format surat lain.

**Comment by Nurhidayat29** [comment]
dclose saja bung @eddieridwan
