### ISSUE TITLE
[Bumindes] Perlu ditambahkan Item Perkades

### ISSUE THREAD

**Issue by Gunturwijay** [OpenSID/OpenSID#3260]
### Sekretariat/Produk Hukum/Jenis Produk Hukum
SK Kades
Perdes

### Seperti apa yang diharapkan?
SK Kades
Perdes
Perkades

### Apa yang terjadi?
1. Belum dapat memasukkan Perkades
2. Belum dapat memisahkan perdes dengan perkades
3. Terpaksa sementara digabungkan ke dalam perdes 

![image](https://user-images.githubusercontent.com/40741591/85659378-aeceba00-b6de-11ea-8f90-9aaeddaa0969.png)
![image](https://user-images.githubusercontent.com/40741591/85660400-c78b9f80-b6df-11ea-974e-7559f7eed340.png)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
> ### Sekretariat/Produk Hukum/Jenis Produk Hukum
> SK Kades
> Perdes
> 
> ### Seperti apa yang diharapkan?
> SK Kades
> Perdes
> Perkades
> 
> ### Apa yang terjadi?
> 1. Belum dapat memasukkan Perkades
> 2. Belum dapat memisahkan perdes dengan perkades
> 3. Terpaksa sementara digabungkan ke dalam perdes
> 
> ![image](https://user-images.githubusercontent.com/40741591/85659378-aeceba00-b6de-11ea-8f90-9aaeddaa0969.png)
> ![image](https://user-images.githubusercontent.com/40741591/85660400-c78b9f80-b6df-11ea-974e-7559f7eed340.png)
> 
> ### Informasi tambahan
> Tanya	Jawab
> Versi OpenSID	2.x
> Versi PHP	
> System operasi

Mungkin dibuat dinamis sja jenis suratnya, biar desa yg bersangkutan menambahkannya. Mungkin selanjutnya akan ada yg meminta penambahan jenis surat lain lg.
