### ISSUE TITLE
Nama dusun tidak sesuai dengan yang diubah

### ISSUE THREAD

**Issue by dariyanti** [OpenSID/OpenSID#3262]
### Bagaimana alurnya sampai muncul masalah?
Saya mau mengubah nama Dusun tetapi ketika di simpan beberapa kata depan ada yang hilang
![error](https://user-images.githubusercontent.com/47493531/85684409-4ab8ef80-b6f8-11ea-9b06-0a1ee5092e72.png)
ketika disimpan, nama dusun tidak sesuai. seperti ini :
![error2](https://user-images.githubusercontent.com/47493531/85684669-881d7d00-b6f8-11ea-9cc9-01064e779c61.png)

`)

### Seperti apa yang diharapkan?
seharusnya huruf awal tidak hilang
 
### Apa yang terjadi?
huruf pertama hilang

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.06
| Versi PHP        | 7.2
| System operasi   | Windows 10

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master`.
