### ISSUE TITLE
Belum ada informasi bantuan yg di terima pd modul RT dan Kelompok (Berdasarkan sasaran 3 dan 4)

### ISSUE THREAD

**Issue by afa28** [OpenSID/OpenSID#3266]
### Bagaimana alurnya sampai muncul masalah?
Saat ini informasi dari program bantuan yg diterima oleh RT / Kelompok belum tersedia di masing2 modul bersangkutan

### Seperti apa yang diharapkan?
Tambah daftar bantuan yg diterima RT / Kelompok, seperti yg ada di penduduk dan KK

### Apa yang terjadi?
Tersedia daftar bantuan yg diterima RT / Kelompok.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3267
