### ISSUE TITLE
Perlu Dibuatkan FOOTER identasi cetakan OpenSID dan Barcode pada setiap Jenis Surat Pengantar

### ISSUE THREAD

**Issue by PWidodo** [OpenSID/OpenSID#3269]
### Bagaimana alurnya sampai muncul masalah?
Tidak ada permasalah.

### Seperti apa yang diharapkan?
Setiap jenis surat pengantar/keterangan dari desa/kampung/gampong/nagari/dan atau sebutan lainnya pada bagian footernya berisi "teks cetakan OpenSID + tanggal & waktu cetak otomatis + teks Sistem Informasi Desa + barcode yang berisi nomor surat.

### Apa yang terjadi?
Surat akan terlihat bagus, apik, rapih, dan modern

### Informasi tambahan 
gambar sebagai berikut :
![surat_opensid_barcode](https://user-images.githubusercontent.com/45189822/85826333-99c15c00-b7ae-11ea-9900-0a5f3f713431.jpg)
![surat_opensid_barcode2](https://user-images.githubusercontent.com/45189822/85826355-a645b480-b7ae-11ea-85ba-c9f75152f816.jpg)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by PWidodo** [comment]
Hal tersebut bertujuan sebagai promosi pada pihak Kecamatan bahwa cetakan surat keterangan/pengantar dari desa ini dibuat dengan aplikasi OpenSID. Dan juga sebagai daya tarik pada desa lain diwilayah kecamatan tersebut untuk menggunakan OpenSID.

**Comment by PWidodo** [comment]
harapannya pihak Kecamatan dapat menghimbau pada desa lainnya untuk mempergunakan OpenSID

**Comment by Nurhidayat29** [comment]
itu barcodenya isinya apa, apakah link download atau alamt web?

**Comment by Nurhidayat29** [comment]
> harapannya pihak Kecamatan dapat menghimbau pada desa lainnya untuk mempergunakan OpenSID

bsa kirim file yg sdh diberikan footernya?

**Comment by Nurhidayat29** [comment]
> Hal tersebut bertujuan sebagai promosi pada pihak Kecamatan bahwa cetakan surat keterangan/pengantar dari desa ini dibuat dengan aplikasi OpenSID. Dan juga sebagai daya tarik pada desa lain diwilayah kecamatan tersebut untuk menggunakan OpenSID.

untuk barcode sepertinya perlu di diskusikan apakah berisi nomor surat, link download atau link website

**Comment by PWidodo** [comment]
Untuk sementara barcode yg saya pergunakan itu berisi nomor kode surat
seperti
siskeudes

Pada tanggal Jum, 26 Jun 2020 19.30, Nur Hidayat <notifications@github.com>
menulis:

**Comment by afa28** [comment]
Mungkin maksudnya template surat standar yg disediakan oleh OpenSID??? Menurut sy bagus sih untuk memperkenalkan OpenSID jg. Tp mungkin barcode tdk perlu disematkan di template standar(fitur belum tersedia untuk generate otomatis ke file rtf) dan jg tdk tahu apa isi dr barcode itu(apakah nomor surat, atau lainnya).

Silahkan berkreasi. (y)

**Comment by SopianHadi2021** [comment]
saya rasa Perlu di Rilis Fitur ini

**Comment by afa28** [comment]
Duplicate issue #2029
