### ISSUE TITLE
upload dokumen

### ISSUE THREAD

**Issue by afri18** [OpenSID/OpenSID#3270]
### Bagaimana alurnya sampai muncul masalah?
saat mengupload dokumen pdf gagal

### Seperti apa yang diharapkan?
sebaiknya jenis dokumen pdf jangan di batasi untuk upload nya

### Apa yang terjadi?
tidak bisa upload dokumen pdf berukuran besar

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.06 pasca
| Versi PHP        | 7.2
| System operasi   |win 10

**Comment by afa28** [comment]
> ### Bagaimana alurnya sampai muncul masalah?
> saat mengupload dokumen pdf gagal
> 
> ### Seperti apa yang diharapkan?
> sebaiknya jenis dokumen pdf jangan di batasi untuk upload nya
> 
> ### Apa yang terjadi?
> tidak bisa upload dokumen pdf berukuran besar
> 
> ### Informasi tambahan
> Tanya	Jawab
> Versi OpenSID	20.06 pasca
> Versi PHP	7.2
> System operasi	win 10

Mungkin solusi, sediakan pilihan upload ke hosting atau hanya sematka url sja (untuk file2 yg besar). Jika file2 size besar diupload semua ke server entah apa yg terjadi, sy jg kurang tau.

**Comment by ilamazuliaf** [comment]
Lebih baik sediakan opsi sematkan url saja, misal via google drive. Saya sendiri juga kurang suka jika harus upload ke server langsung. Bisa bengkak nanti.

**Comment by afa28** [comment]
Solusi dengan menambahkan ekternal url sesuai issue https://github.com/OpenSID/OpenSID/issues/2565
