### ISSUE TITLE
QR Code Tdk Kembali Normal Setelah Berpindah Module

### ISSUE THREAD

**Issue by afa28** [OpenSID/OpenSID#3271]
### Bagaimana alurnya sampai muncul masalah?
Buka module Pengaturan > Hasilkan QRCode dan lakukan generate barcode. Kemudia pindah ke modul yg lain dan kembali lg ke modul  Pengaturan > Hasilkan QRCode. Form Hasilkan QRCode tdk kembali normal.

### Seperti apa yang diharapkan?
Form Hasilkan QRCode kembali normal jika module di load ulang.

### Apa yang terjadi?
Form Hasilkan QRCode.

### Informasi tambahan 
Ini terjadi mungkin krn menggunakan session dan tdk di unset saat meload controller setting. Menggunakan form standar yg menggunakan button batal dan simpan atau buat tombol bersihkan session.

![111111](https://user-images.githubusercontent.com/57283157/85923509-b72d1d80-b8b5-11ea-8214-0060ef0985b6.JPG)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3273
