### ISSUE TITLE
TERJADI BEBERAPA KENDALA SAAT INPOR-ESPORT DATA PENDUDUK

### ISSUE THREAD

**Issue by wone-one** [OpenSID/OpenSID#3276]
### Bagaimana alurnya sampai muncul masalah?
Saat proses inport-exspor data penduduk dari opensidi terdapat beberapa kendala sbb :
terjadi penglompokan keluarga dengan nomor KK 0 saat proses inport data penduduk dan  setatus dasar penduduk seperti MATI, PINDAH, DLL Tidak disertakan.

### Seperti apa yang diharapkan?
1. tambahkan id pada keluarga atau sejenisnya agar keluarga dengan no. KK 0 (kosong) tidak digabung menjadi satu keluarga
2. sertakan atau tambahkan setatus dasar penduduk pada fitur inport-exsport data penduduk

### Apa yang terjadi?
1. saat terjadi pengelompokan terhadap banyak keluarga dengan no KK 0 (kosong), kesulitan dalam melakukan penyesuaian agar sesuai dengan data keluarga yang sebenarnya
2. saat proses inport data berhasil, data penduduk AKTIF, HIDUP tidak sesuai Karena setatus dasar penduduk sebelumnya tidak disertakan dalam format isian. sehingga perlu dilakukan penyesuaian manual yang saya pandang kurang efektif karena harus menelusuri dokumen, dan data pendukung terkait perubahan setatus penduduk tersebut

### Informasi tambahan 
semua permasalahan yang di angkat dengan asumsi bahwa data yang dipakai merupakan data bersumber dari opensid, untuk data yang bersumber dari luar opensid mungkin perlu dipertimbangkan.

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
> ### Bagaimana alurnya sampai muncul masalah?
> Saat proses inport-exspor data penduduk dari opensidi terdapat beberapa kendala sbb :
> terjadi penglompokan keluarga dengan nomor KK 0 saat proses inport data penduduk dan setatus dasar penduduk seperti MATI, PINDAH, DLL Tidak disertakan.
> 
> ### Seperti apa yang diharapkan?
> 1. tambahkan id pada keluarga atau sejenisnya agar keluarga dengan no. KK 0 (kosong) tidak digabung menjadi satu keluarga
> 2. sertakan atau tambahkan setatus dasar penduduk pada fitur inport-exsport data penduduk
> 
> ### Apa yang terjadi?
> 1. saat terjadi pengelompokan terhadap banyak keluarga dengan no KK 0 (kosong), kesulitan dalam melakukan penyesuaian agar sesuai dengan data keluarga yang sebenarnya
> 2. saat proses inport data berhasil, data penduduk AKTIF, HIDUP tidak sesuai Karena setatus dasar penduduk sebelumnya tidak disertakan dalam format isian. sehingga perlu dilakukan penyesuaian manual yang saya pandang kurang efektif karena harus menelusuri dokumen, dan data pendukung terkait perubahan setatus penduduk tersebut
> 
> ### Informasi tambahan
> semua permasalahan yang di angkat dengan asumsi bahwa data yang dipakai merupakan data bersumber dari opensid, untuk data yang bersumber dari luar opensid mungkin perlu dipertimbangkan.
> 
> Tanya	Jawab
> Versi OpenSID	2.x
> Versi PHP	
> System operasi

Bisa kirim contoh data yg memiliki kendala di atas untuk testing, andifahruddinakas@gmail.com

**Comment by wone-one** [comment]
maaf untuk data penduduk tidak bisa dibagikan. untuk testing bisa memanfaatkan data bawaan opensid, silahkan set beberapa ke no KK 0 (kosong) atau saya bantu ?

**Comment by afa28** [comment]
> maaf untuk data penduduk tidak bisa dibagikan. untuk testing bisa memanfaatkan data bawaan opensid, silahkan set beberapa ke no KK 0 (kosong) atau saya bantu ?

Silahkan buat contoh file, datanya terserah sja yg penting mewakili issuenya.

**Comment by wone-one** [comment]
[penduduk_28_06_2020.zip](https://github.com/OpenSID/OpenSID/files/4842312/penduduk_28_06_2020.zip)

**Comment by wone-one** [comment]
[data124.zip](https://github.com/OpenSID/OpenSID/files/4842385/data124.zip)

**Comment by balongbesuk** [comment]
kalau impor data awal NIK dan KK harus ada tidak boleh kosong / 0

**Comment by mizwaruddin** [comment]
@afa28 Kendala bukan pada no KK yg 0. Tapi karena alamat masih kosong. Barusan saya coba mengimpor dari data contoh yang dikirimkan dengan melengkapi kolom alamat yg sebelumnya kosong, hasilnya sukses.

**Comment by afa28** [comment]
> @afa28 Kendala bukan pada no KK yg 0. Tapi karena alamat masih kosong. Barusan saya coba mengimpor dari data contoh yang dikirimkan dengan melengkapi kolom alamat yg sebelumnya kosong, hasilnya sukses.
> Untuk mengatasi pengelompokan Nomor KK yg masih kosong/0, bisa disiasati dengan memberikan nomor 0000000000000001 dst.

Mungkin bisa ditambahkan di panduan
