### ISSUE TITLE
Hapus Google Plus dari daftar Media Sosial

### ISSUE THREAD

**Issue by dikisiswanto** [OpenSID/OpenSID#3279]
### Bagaimana alurnya sampai muncul masalah?
Google+ merupakan salah satu produk yang saat ini statusnya sudah dinonaktifkan oleh Google.
![image](https://user-images.githubusercontent.com/22239074/85946438-e192df80-b976-11ea-933c-478f8c7f45dd.png)

### Seperti apa yang diharapkan?
Hapus Google+ dari daftar sosial media pada menu `Admin Web > Media Sosial`

### Apa yang terjadi?
Layanan Google+ sudah tidak bisa digunakan

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
Akhirnya, ada jg yg buat issue ini

**Comment by roaddee** [comment]
mungkin bisa ganti yang lain, misal linkedln

**Comment by afa28** [comment]
> mungkin bisa ganti yang lain, misal linkedln

Dibuat dinamis ok jg

**Comment by balongbesuk** [comment]
> 
> 
> > mungkin bisa ganti yang lain, misal linkedln
> 
> Dibuat dinamis ok jg, tp yg jd masalah nama icon pd tiap tema kadang berbeda sweat_smile

Fokus saja dengan tema bawaan Opensid mas, yang diluar opensid biasanya menyesuaikan sendiri

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3314
