### ISSUE TITLE
DOKUMEN / KELENGKAPAN PENDUDUK YANG TERSEDIA PADA LAYAHAN MANDIRI

### ISSUE THREAD

**Issue by Gunturwijay** [OpenSID/OpenSID#3282]
### Bagaimana alurnya sampai muncul masalah?
![image](https://user-images.githubusercontent.com/40741591/85975708-f6b55000-ba02-11ea-81dc-ac77455b1b82.png)

### Seperti apa yang diharapkan?
Sebaiknya DOKUMEN / KELENGKAPAN PENDUDUK YANG TERSEDIA di hilangkan atau dapat beberapa dokumen saja yang boleh ditampilkan, dengan syarat pengguna layanan mandiri tidak dapat menghapus dokumen tersebut, kecuali dokumen yang ia upload.

Dan yang ini sebaiknya dihapus saja karena sudah ada pada layanan permohonan surat seperti gambar diatas.
![image](https://user-images.githubusercontent.com/40741591/85976109-ff5a5600-ba03-11ea-9964-080f30babde0.png)

### Apa yang terjadi?
Para pengguna layanan mandiri dapat menghapus dokumennya yang telah disimpan di dalam database tanpa ada izin dari admin desa.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
Sama maksudnya dengan issue #3118

**Comment by Gunturwijay** [comment]
beda tapi hampir sama

**Comment by eddieridwan** [comment]
Mohon ingat, walaupun dokumen yg diunggah oleh petugas kantor desa tidak boleh dihapus oleh warga, namun warga tetap berhak melihat dokumen yg disimpan oleh kantor desa terkait diri mereka. Jadi daftar dokumen di halaman bio data warga jangan dihapus.

**Comment by afa28** [comment]
Untuk tombol hapus mungkin bisadihapus. Tp untuk kelengkapan doumen sebaiknya tdk dihapus, agar dokumen bisa didownload/dilihat penduduk bersangkutan.

**Comment by eddieridwan** [comment]
Sdh dicommit ke master melalui PR #3322
