### ISSUE TITLE
[Tema] Layanan Cek NIK atau NO. KK pada Website openSID

### ISSUE THREAD

**Issue by DamesDamai** [OpenSID/OpenSID#3285]
### Bagaimana alurnya sampai muncul masalah?
Penduduk ingin mengeCEK apakah sudah terdaftar atau tidak!

### Seperti apa yang diharapkan?
Penduduk bisa dengan sangat mudah mengeCEK apakah sudah terdaftar atau belum!

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
Yg ditampilkan hanya informasi NIK sudah terdaftar atau tdk kan??? Data identitas tdk perlu.

**Comment by DamesDamai** [comment]
iyya minimal NIK atau KK lah. supaya penduduk bisa melaporkan ke pemerintah desa kalau mereka belum terdaftar...

**Comment by eddieridwan** [comment]
@DamesDamai , apakah fitur semacam ini bisa digunakan pihak nakal untuk mengetahui NIK atau No. KK valid -- misalnya untuk mencuri identitas warga? Bagaimana mencegah penyalahgunaan fitur semacam ini?

**Comment by DamesDamai** [comment]
yes

**Comment by HerryWanda** [comment]
Menurut saya, 
saya sepakat dengan jawaban bung @afa28 ..
yang ditampilkan cukup "NIK anda sudah terdaftar"

Mungkim bisa ditambahkan, "untuk info lengkap hubungi operator desa"

atau bisa dutambahkan di widget Layanan Mandiri untuk cek NIK..

Notif hasil cek : "NIK anda sudah terdataftar" untuk menggunakam layanan mandiri dan mendapatkan PIN silakan hubungi operator desa" 

dengan tmbahan menampilkam No WA/atau email desa.

**Comment by afa28** [comment]
Limit 3 kali cek untuk tiap IP, agar tdk melakukan spam

**Comment by eddieridwan** [comment]
Sebaiknya fitur ini tidak diterapkan, karena akan memberi info mengenai NIK secara tidak sengaja bagi yg coba2. 

Mungkin yg bisa ditambahkan adalah info tambahan di form login mandiri:
1. Sediakan nomor WA/email desa di form login mandiri
2. Bila telah gagal login 3 kali, tonjolkan lagi pesan untuk menghubungi petugas desa

**Comment by DamesDamai** [comment]
sepertinya begitu pak


Pada tanggal Rab, 14 Okt 2020 pukul 18.06 Eddie Ridwan <
notifications@github.com> menulis:

**Comment by hasap86** [comment]
untuk pengecekan nik & kk ditambahkan tanggal lahir untuk validasi dan chaptcha

**Comment by eddieridwan** [comment]
Lihat informasi tambahan di https://github.com/OpenSID/OpenSID/issues/4119

**Comment by eddieridwan** [comment]
Permintaan seperti ini sudah dilaporkan berkali-kali, dan dianggap menimpulkan celah privasi data, karena bisa digunakan untuk menebak NIK warga yg valid. Kecuali ada yg bisa menjelaskan secara rinci pengamanan apa yg ada di aplikasi SIKS-NG untuk data DTKS. atau seperti cek KTP-ku, cek BPJS dan lainnya untuk menjaga hal tersebut. 

Sebagai aplikasi yg harus terpercaya dan harus bisa lolos audit keamanan dari pihak2 lain, OpenSID tidak boleh mengorbankan keamanan demi kemudahan. 

Pengamanan yg diperlukan adalah cara supaya yg dapat berhasil memeriksa terdaftar tidaknya seseorang hanya warga ybs, dan bukan sembarang orang. Jadi jangan sampai si A bisa melihat apakah si B sdh terdaftar.

Salah satu kemungkinan adalah dengan mengharuskan mengisi informasi tambahan (idealnya dua) selain NIK yang seharusnya hanya diketahui warga ybs, misalnya:
1. No. KK
2. Tempat lahir atau informasi lain yg tertera di KTP atau di KK (yg bukan bagian dari NIK)

Perhatikan bahwa `tanggal lahir` tidak bisa digunakan, karena tanggal lahir merupakan bagian dari NIK.

Tentunya cara ini akan menambah beban yg menggunakan fitur ini. Tapi seperti itulah yg diperlukan untuk menjaga keamanan aplikasi.

**Comment by Zoel-WB** [comment]
Kalau memang memungkinkan untuk menghindari dan menutup celah data yang dapat dibuka oleh pihak lain dengan membuat 3 (tiga) atau 4  permintaan indentifikasi yang sesuai dengan KTP dan KK untuk dapat menampilkan data hasil pengecekkan misalnya :
1. No. NIK;
2. No. KK;
3. Nama Lengkap sesuai KTP; dan
4. Nama Ibu Kandung.

untuk identifikasi nama Ibu Kandung biasanya digunakan oleh Perbankan sebagai pembuktian data identitas.

**Comment by Zoel-WB** [comment]
Ada penambahan sedikit lagi untuk fitur Layanan Cek NIK, hanya untuk menampilkan sebatas data identitasnya saja bahwa yang bersangkutan sudah terdata sebagai warga desa dimaksud baik sebagai penduduk tetap maupun penduduk sementara, jadi bukan untuk dapat menampilkan Biodata nya secara menyuruh dan detail apalagi dapat mencetak biodatanya. kalau ingin melihat dan mencetak biodata-nya secara detail dibisa dibuatkan pesan untuk "Login di Layanan Mandiri"

**Comment by eddieridwan** [comment]
Permintaan ini diganti dengan issue https://github.com/OpenSID/OpenSID/issues/4557, dan https://github.com/OpenSID/OpenSID/issues/1760.

Issue ini ditutup.
