### ISSUE TITLE
Jumlah KK yang tampil di wilayah administrasi RT tidak sesuai

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#3287]
### Bagaimana alurnya sampai muncul masalah?
Jumlah KK masing-masing RT yang ditampilkan masih secara keseluruhan dengan KK yang Pindah, Mati
![jlh kk](https://user-images.githubusercontent.com/25834335/86087704-5f6dfc80-bad7-11ea-9098-1b1af7435dc3.png)

### Seperti apa yang diharapkan?
Jumlah KK di wilayah Administrasi RT yang tampil sesuai dengan jumlah KK yang ada di menu keluarga

### Apa yang terjadi?
Jumlah KK tidak sesuai

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.06-pasca
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
![11111](https://user-images.githubusercontent.com/57283157/86220544-eee5df00-bbad-11ea-8ef3-3d95000cbcde.JPG)

Tambahan miss data, jumlah total KK salah jika ada anggota KK yg mati.

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3292
