### ISSUE TITLE
KOLOM ATUR QR CODE BELUM MAKSIMAL

### ISSUE THREAD

**Issue by Gunturwijay** [OpenSID/OpenSID#3293]
### Bagaimana alurnya sampai muncul masalah?
![image](https://user-images.githubusercontent.com/40741591/86233001-fcf02b80-bbbe-11ea-97b1-2cea5ef50faf.png)

### Seperti apa yang diharapkan?
Penambahan New Forder pada layar atur QR Code perlu dilakukan perbaikan, agar kolom yang muncul nanti menjadi center sehingga ketikan yang muncul bisa terlihat.

### Apa yang terjadi?
![image](https://user-images.githubusercontent.com/40741591/86232481-35433a00-bbbe-11ea-9268-964b5f825cff.png)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
Dr PR sebelumnya, belum menyelesaikan masalah ini.

**Comment by eddieridwan** [comment]
Sdh dicommit ke `bug-fix` melalui https://github.com/OpenSID/premium/pull/257
