### ISSUE TITLE
BUG Pada Cetak Biodata Penduduk

### ISSUE THREAD

**Issue by PWidodo** [OpenSID/OpenSID#3296]
### Bagaimana alurnya sampai muncul masalah?
Pada saat ingin mencetak BIODATA PENDUDUK melalui menu Kependudukan>Penduduk>NIK>Cetak Biodata) logo kabupaten, nama kabupaten, nama kecamatan, nama desa, dan nama kepala desa tidak muncul.

### Seperti apa yang diharapkan?
Sebagaimana versi sebelumnya 20.06 (semua normal)
![bug1](https://user-images.githubusercontent.com/45189822/86357498-187b3500-bc98-11ea-9028-42b31e2a4894.jpg)
![bug2](https://user-images.githubusercontent.com/45189822/86357600-46607980-bc98-11ea-954b-5ce860d8f123.jpg)
![bug3](https://user-images.githubusercontent.com/45189822/86357689-6abc5600-bc98-11ea-8703-a9b4c07b1f91.jpg)
![bug4](https://user-images.githubusercontent.com/45189822/86357760-87588e00-bc98-11ea-8b80-55bfa99c0e89.jpg)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.07
| Versi PHP        | 7.3
| System operasi   | Windows

**Comment by ZER07URN** [comment]
Mungkin krn perubahan dr commit ttd an/ab untuk lampiran sebelumnya belum diterapkan di cetak langsung.

**Comment by PWidodo** [comment]
Sudah dari versi 19.07 diterapkan An dan Ub nya bung
![an-ub](https://user-images.githubusercontent.com/45189822/86369254-5c763600-bca8-11ea-8e3a-75c18506cb53.png)

**Comment by afa28** [comment]
Berarti cetak langsung tdk berlaku ttd an/ab Pak @PWidodo???? Krn sy lihat, yg bertanda tangan di cetak langsung (biodata) itu adalah kepala desa dlm artian tdk bisa di wakili.

**Comment by afa28** [comment]
Ini issue yg pernah sy buat #3250

**Comment by eddieridwan** [comment]
Sdh dicommit melalui PR #3297
