### ISSUE TITLE
Tampilan Mapbox Streets Satelite blank

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#3298]
### Bagaimana alurnya sampai muncul masalah?
Tampilan Mapbox Streets Satelite blank di :
1. Lokasi Kantor Desa
2. Peta Wilayah Desa
3. Peta Wilayah Administrasi
4. Menu Pemetaan
seperti gambar dibawah ini : 
1. Lokasi Kantor Desa
![image](https://user-images.githubusercontent.com/25834335/86393323-7a0ac600-bccf-11ea-90af-ed819412428b.png)
2. Peta Wilayah Desa
![image](https://user-images.githubusercontent.com/25834335/86393353-842cc480-bccf-11ea-9f1e-a77ea831a04d.png)
3. Peta Wilayah Administrasi
![image](https://user-images.githubusercontent.com/25834335/86393397-9b6bb200-bccf-11ea-9714-6e29e0fcb14c.png)
4. Menu Pemetaan
![image](https://user-images.githubusercontent.com/25834335/86393421-a6264700-bccf-11ea-8f06-f29d55ed5c58.png)

### Seperti apa yang diharapkan?
Tampilan Mapbox Streets Satelite di :
1. Lokasi Kantor Desa
2. Peta Wilayah Desa
3. Peta Wilayah Administrasi
4. Menu Pemetaan
Normal seperti di Versi Sebelumnya

### Apa yang terjadi?
Operator Desa Kesulitan pada waktu menentukan Batas Desa, Wilayah Dusun, Wilayah RT

### Informasi tambahan 
disitus demo juga sama : https://demo.opensid.my.id
| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.07-Pasca
| Versi PHP        | 
| System operasi   |

**Comment by WAHYUDIK** [comment]
di saya aman2 saja mas, setelah saya coba cek di demo ternyata ada kesalahan di seting aplikasi, terdapat perbedaan google_kenya
sudah saya perbaiki key di situs demo.

**Comment by WAHYUDIK** [comment]
tinggal mapbox outdor yang blank
![image](https://user-images.githubusercontent.com/31026980/86424988-29ff2400-bd0e-11ea-8e7c-260edd757488.png)
baik di demo ataupun di saya
![image](https://user-images.githubusercontent.com/31026980/86425002-33888c00-bd0e-11ea-9ecc-d945d48d6d53.png)
kalo lainnya sudah tampil

**Comment by MUHAMMADRANGSEL** [comment]
Sdh bisa setelah update terbaru, issue ini saya close
