### ISSUE TITLE
Perlu dibuatkan Backup Folder Desa

### ISSUE THREAD

**Issue by ai-skematik** [OpenSID/OpenSID#3301]
### Bagaimana alurnya sampai muncul masalah?
Saat ini belum tersedia backup folder desa sehingga  banyak desa yang kesulitan pindah hosting karena tidak diberikan akses ke cpanel

### Seperti apa yang diharapkan?
Disediakannya pilihan untuk mengunduh folder desa

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by roaddee** [comment]
sepertinya ini sudah pernah akan dibuatkan/dipikirkan oleh bung @afa28 (langsung akan diimport dari Jepang, 👍 💯 )

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3302
