### ISSUE TITLE
Perlu ada daftar pembangunan

### ISSUE THREAD

**Issue by sutisnasanjaya** [OpenSID/OpenSID#3303]
### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
@sutisnasanjaya issue anda perlu dilengkapi dengan aturan, laporan, tampilan dsbnya yg diinginkan. Tanpa info rinci, programmer tidak akan tahu apa yg diinginkan. Juga perhatikan bahwa sudah ada permintaan sebelumnya yg sepertinya terkait, seperti https://github.com/OpenSID/OpenSID/issues/2543 . Kalau issue yg lama sdh sejalan dengan apa yg anda inginkan, lengkapi saja dengan keterangan tambahan. Dan tutup issue ini.

**Comment by afa28** [comment]
https://github.com/OpenSID/OpenSID/issues/2543
