### ISSUE TITLE
Perlunya dibuat Pengaturan Penentuan Persyaratan Surat Layanan Mandiri oleh Masing-Masing Desa

### ISSUE THREAD

**Issue by Gunturwijay** [OpenSID/OpenSID#3304]
### Bagaimana alurnya sampai muncul masalah?
![image](https://user-images.githubusercontent.com/40741591/86506867-a6246500-bdfd-11ea-87d9-84a6026ba5d7.png)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
Kyaknya di menu admin sudah ada mengenai persyaratan surat.
