### ISSUE TITLE
Impor file SHP untuk pemetaan

### ISSUE THREAD

**Issue by mizwaruddin** [OpenSID/OpenSID#3305]
### Bagaimana alurnya sampai muncul masalah?
Saat ini file yang tersedia untuk import peta baru GPX dan KML.

### Seperti apa yang diharapkan?
Ditambah impor file SHP untuk menambah pilihan file peta.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
@fusionid @mizwaruddin , ada contoh file untuk dicoba impor?

**Comment by mizwaruddin** [comment]
Ada, Bang. Kemarin sdh sya kirim ke Bang Zeppy. 
Mau dikirim ke alamat email mana, Bang?

**Comment by mizwaruddin** [comment]
[TES2.zip](https://github.com/OpenSID/OpenSID/files/4884148/TES2.zip)

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3306
