### ISSUE TITLE
Installasi Gagal

### ISSUE THREAD

**Issue by tahanberak** [OpenSID/OpenSID#3308]
### Bagaimana alurnya sampai muncul masalah?

Mengikuti panduan ini https://github.com/opensid/opensid/wiki/Panduan-Install-OpenSID#6-import-data-awal
Tapi gagal di proses import data awal

### Apa yang terjadi?

ERROR 1005 (HY000): Can't create table 'opensid.covid19_pemudik' (errno: 150)
Query OK, 0 rows affected, 1 warning (0.00 sec)

ERROR 1005 (HY000): Can't create table 'opensid.covid19_pantau' (errno: 150)
Query OK, 0 rows affected, 1 warning (0.00 sec)

ERROR 1146 (42S02): Table 'opensid.kontak' doesn't exist
Query OK, 0 rows affected, 1 warning (0.00 sec)

ERROR 1146 (42S02): Table 'opensid.anggota_grup_kontak' doesn't exist
Query OK, 0 rows affected, 1 warning (0.00 sec)

ERROR 1146 (42S02): Table 'opensid.anggota_grup_kontak' doesn't exist
Query OK, 0 rows affected, 1 warning (0.00 sec)

ERROR 1146 (42S02): Table 'opensid.dokumen' doesn't exist
Query OK, 0 rows affected, 1 warning (0.00 sec)

ERROR 1146 (42S02): Table 'opensid.tweb_penduduk' doesn't exist
Query OK, 0 rows affected, 1 warning (0.00 sec)

ERROR 1146 (42S02): Table 'opensid.tweb_penduduk' doesn't exist

### Informasi tambahan 
 Source master  Mon Jul 6 10:06:53 2020

**Comment by tahanberak** [comment]
Atau mungkin ada rekan yang bisa bantu bagi database untuk installasi yang tidak error?

**Comment by afa28** [comment]
> Atau mungkin ada rekan yang bisa bantu bagi database untuk installasi yang tidak error?

Online?

**Comment by tahanberak** [comment]
> > Atau mungkin ada rekan yang bisa bantu bagi database untuk installasi yang tidak error?
> 
> Online?

Berkas **contoh_data_awal_xxxxx.sql** di letakkan saja di alamat yang bisa di download.

**Comment by afa28** [comment]
> > > Atau mungkin ada rekan yang bisa bantu bagi database untuk installasi yang tidak error?
> > 
> > Online?
> 
> Berkas **contoh_data_awal_xxxxx.sql** di letakkan saja di alamat yang bisa di download.

Klw download masternya OpenSID, contoh dataawalnya sdah ikut.

**Comment by tahanberak** [comment]
> > > > Atau mungkin ada rekan yang bisa bantu bagi database untuk installasi yang tidak error?
> > > 
> > > 
> > > Online?
> > 
> > 
> > Berkas **contoh_data_awal_xxxxx.sql** di letakkan saja di alamat yang bisa di download.
> 
> Klw download masternya OpenSID, contoh dataawalnya sdah ikut.

Justru itu yang error.
Kan sudah saya sebutkan di **Bagaimana alurnya sampai muncul masalah?**

**Comment by afa28** [comment]
> > > > > Atau mungkin ada rekan yang bisa bantu bagi database untuk installasi yang tidak error?
> > > > 
> > > > 
> > > > Online?
> > > 
> > > 
> > > Berkas **contoh_data_awal_xxxxx.sql** di letakkan saja di alamat yang bisa di download.
> > 
> > Klw download masternya OpenSID, contoh dataawalnya sdah ikut.
> 
> Justru itu yang error.
> Kan sudah saya sebutkan di **Bagaimana alurnya sampai muncul masalah?**

Bisa pakai database 20.06 dlu klw mmang database awalnya bermasalah. Sy blum sempat cek permasalahan issue ini.

**Comment by tahanberak** [comment]
Mungkin penyebabnya versi mysql.
Saya coba di yang lebih baru bisa.
