### ISSUE TITLE
Costume sasaran keluarga

### ISSUE THREAD

**Issue by ilamazuliaf** [OpenSID/OpenSID#3309]
### Bagaimana alurnya sampai muncul masalah?
Saat mau nambah Keluarga Penerima Manfaat pada program bantuan Keluarga/KK nama yang dicari tidak muncul, sedangkan dipenduduk datanya ada.
![image](https://user-images.githubusercontent.com/31075119/86602518-eede4880-bfcc-11ea-84ed-4bfcbc0085a5.png)
![image](https://user-images.githubusercontent.com/31075119/86602588-0e757100-bfcd-11ea-8413-375ea92abbc4.png)

### Seperti apa yang diharapkan?
Sebaiknya yang menerima bantuan per keluarga bukan hanya dari Kepala Keluarga, Istri maupun anak. Karena pada realita dilapangan ada nenek yang satu KK dengan ponakannya.

### Apa yang terjadi?
Data Penerima Bantuan kurang valid dikarenakan ada sebagian warga yang tidak terinput

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.07-pasca
| Versi PHP        | 7.2.27
| System operasi   |

**Comment by afa28** [comment]
Cek console

**Comment by afa28** [comment]
Pak @M-A-Haris, @afri18, @MUHAMMADRANGSEL, @roaddee, @mizwaruddin atau yg pemerintah desa.

"Sebaiknya yang menerima bantuan per keluarga bukan hanya dari Kepala Keluarga, Istri maupun anak. Karena pada realita dilapangan ada nenek yang satu KK dengan ponakannya."

Apakah ini perlu ditambahkan???

**Comment by ilamazuliaf** [comment]
Saya rasa sangat perlu, karena untuk program bantuan BLT DD di Desa kami diprioritaskan untuk Lansia sedangkan KK-Nya kebanyakan gabung dengan ponakan, anak dll

**Comment by eddieridwan** [comment]
> Saya rasa sangat perlu, karena untuk program bantuan BLT DD di Desa kami diprioritaskan untuk Lansia sedangkan KK-Nya kebanyakan gabung dengan ponakan, anak dll

Mengapa program seperti itu dibuat sebagai `sasaran penduduk` saja? Dengan demikian bebas penduduk yg bisa menjadi penerima bantuan -- siapa saja dari keluarga bisa menjadi penerima.

**Comment by afri18** [comment]
Banyak yg salah atau memaksakan dalam bantuan keluarga, contoh BST dd , dalam pemahaman saya bantuan ini keluarga atau rumah tangga, otomatis penerima menurut sikng adalah istri atau kepala keluarga, tidak bisa jompo yg kknya gabung sama ponakan, salah sasaran, walau niatnya baik ..., Kecuali jompo tersebut kknya tersendiri ...
Ini pemahaman saya ...

**Comment by ilamazuliaf** [comment]
> > Saya rasa sangat perlu, karena untuk program bantuan BLT DD di Desa kami diprioritaskan untuk Lansia sedangkan KK-Nya kebanyakan gabung dengan ponakan, anak dll
> 
> @M-A-Haris, @afri18, @MUHAMMADRANGSEL, @roaddee, @mizwaruddin @ilamazuliaf
> Mengapa program seperti itu tidak dibuat sebagai `sasaran penduduk/perorangan` saja? Dengan demikian bebas penduduk yg bisa menjadi penerima bantuan -- berapa saja anggota keluarga bisa menjadi penerima. Cara ini lebih konsisten. Karena kalau suatu program bantuan betul2 sasarannya adalah KELUARGA, maka seharusnya satu keluarga hanya bisa menjadi penerima satu kali saja.
> 
> Satu cara untuk menampilkan infomasi tambahan, bisa sebagai berikut:
> 
> 1. Di form tambah peserta sasaran penduduk, tampilkan bantuan yg diterima penduduk itu dan juga bantuan yg diterima keluarga penduduk tersebut (yaitu yg mempunyai nomor KK sama)
> 2. Di form tambah peserta sasaran keluarga, tampilkan bantuan yg diterima keluarga itu, dan juga bantuan yg diterima setiap anggota keluarga tersebut (untuk program sasaran penduduk)
> 
> Dengan cara itu, panitia bisa melihat secara keseluruhan bantuan yg diterima suatu keluarga (KK), baik dari bantuan dengan sasaran keluarga maupun dari bantuan sasaran perorangan.

Kenapa tidak pakai _sasaran penduduk/perorangan_ karena emang sasarannya adalah Perkeluarga. Nah masalahnya dalam KK ini tidak mendapat bantuan sama sekali dan si Nenek yang dalam KK tersebut mendapat bantuan BLT DD, akan tetapi ketika mau diinput namanya tidak muncul karena Hubungannya bukan Kepala Keluarga, Istri dan anak.

Ini bukan hanya terjadi di BLT DD, di BLT Kemensos, BST Kabupaten, PKH maupun BPNT juga begitu kebanyakan yang dapat bantuan adalah dalam KK yang bukan Kepala Keluarga, Istri maupun anak

**Comment by ilamazuliaf** [comment]
> Banyak yg salah atau memaksakan dalam bantuan keluarga, contoh BST dd , dalam pemahaman saya bantuan ini keluarga atau rumah tangga, otomatis penerima menurut sikng adalah istri atau kepala keluarga, tidak bisa jompo yg kknya gabung sama ponakan, salah sasaran, walau niatnya baik ..., Kecuali jompo tersebut kknya tersendiri ...
> Ini pemahaman saya ...

Menurut pemahaman saya bukan begitu, melainkan yang terpenting dalam satu KK tidak double dengan bantuan lainnya.

**Comment by mizwaruddin** [comment]
Klo pemahaman Anda seperti itu, berarti keluarga penerima PKH, Sembako, BST, BLT tidak boleh menerima KIS/BPJS dong? Penerima PKH jg tdk bisa dpt bantuan Sembako.

**Comment by afa28** [comment]
> > Banyak yg salah atau memaksakan dalam bantuan keluarga, contoh BST dd , dalam pemahaman saya bantuan ini keluarga atau rumah tangga, otomatis penerima menurut sikng adalah istri atau kepala keluarga, tidak bisa jompo yg kknya gabung sama ponakan, salah sasaran, walau niatnya baik ..., Kecuali jompo tersebut kknya tersendiri ...
> > Ini pemahaman saya ...
> 
> Menurut pemahaman saya bukan begitu, melainkan yang terpenting dalam satu KK tidak double dengan bantuan lainnya.

Dr PR yg sy sebelumnya, biar pentugas yg memverifikasi calon peserta yg berhak menerima bantuan. Dsna sdah ditambah informasi bantuan sj yg diterima. Jd pengguna lain bisa menyesuaikan. Jika dibuat otomatis tdk menerima bantuan jika sdah mendapat bantuan ini itu, akan menimbulkan kerancuan lainnya.

**Comment by afa28** [comment]
Costume sasaran detail, pengguna bisa memilih jika sasaran keluarga.
