### ISSUE TITLE
Admin LogInPage

### ISSUE THREAD

**Issue by jn1xia** [OpenSID/OpenSID#3311]
### Bagaimana alurnya sampai muncul masalah?
setelah login admin page, malah kembali ke homepage

### Seperti apa yang diharapkan?
menuju adminpage

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
Mohon issuenya diperjelas.

**Comment by afa28** [comment]
Lakukan testing di situs demo, jika masalah ini mmang terjadi bisa buatkan issue lg. Yp mohon issuenya di perjelas. Terimakasih 🙏
