### ISSUE TITLE
Verifikasi Penerima Bantuan (Agar Tidak Mendapatkan Bantuan Double)

### ISSUE THREAD

**Issue by roaddee** [OpenSID/OpenSID#3313]
### Bagaimana alurnya sampai muncul masalah?
Ketika memasukkan Data Penerima Bantuan Sasaran Keluarga di menu Bantuan belum bisa memfilter sehingga tidak mendapatkan Bantuan Double, sehingga pemerintah desa perlu memeriksa kembali satu persatu nama penerima bantuan melalui statistik Penerima Bantuan Keluarga.
Cacatan : Bantuan PKH, dan BPNT boleh diterima oleh satu Kepala Keluarga 

### Seperti apa yang diharapkan?
-  Ketika memasukkan data penerima bantuan ada pemberitahuan bahwa yang bersangkutan sudah  menerima bantuan A misalkan.
-  Untuk Jenis Bantuan : misalnya : Keluarga A mendapatkan 2 jenis bantuan :
1.  Bantuan PKH 
2.  Bantuan BPNT
lebih baik dijadikan satu form tempat diisi dan dibuatkan pilihan jenis bantuan yang diterima.
dengan dibuatkan fitur untuk memfilter masing-masing jenis bantuan, sehingga ketika memasukkan data penerima bantuan akan bisa di antisifasi warga tersebut mendapatkan bantuan double

### Apa yang terjadi?
Masih terdapat 1 keluarga menerima lebih dari satu bantuan
Untuk lebih spesifik : untuk sementara jenis bantuan, bantuan yang boleh diterima oleh keluarga lebih dari satu jenis bantuan yaitu : PKH dan BPNT, kalau yang lain tidak boleh.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.07
| Versi PHP        |  7.2
| System operasi   | Windows 10

**Comment by MUHAMMADRANGSEL** [comment]
dibuatkan juga fitur untuk memfilter masing-masing jenis bantuan

**Comment by mizwaruddin** [comment]
Penerima bantuan dobel harus tetap bisa dimasukkan dalam menu bantuan, hanya saja dibuatkan pendeteksi bahwa KPM ybs mendapatkan bantuan ganda pada satu jenis bantuan. Contoh: Suami dan istri dalam satu KK sama-sama mendapatkan bantuan Sembako. Oleh sistem akan terdeteksi bahwa dalam satu KK mendapatkan bantuan yang sama (bukan memblokir untuk tidak masuk data bantuan dalam OpenSID) karena yang menentuan bantuan (utamanya dari dana pusat) adalah Kemensos. Desa sifatnya hanya pengajuan dan diminta untuk melakukan verifikasi dan evaluasi data KPM.

**Comment by MUHAMMADRANGSEL** [comment]
> Penerima bantuan dobel harus tetap bisa dimasukkan dalam menu bantuan, hanya saja dibuatkan pendeteksi bahwa KPM ybs mendapatkan bantuan ganda pada satu jenis bantuan. Contoh: Suami dan istri dalam satu KK sama-sama mendapatkan bantuan Sembako. Oleh sistem akan terdeteksi bahwa dalam satu KK mendapatkan bantuan yang sama (bukan memblokir untuk tidak masuk data bantuan dalam OpenSID) karena yang menentuan bantuan (utamanya dari dana pusat) adalah Kemensos. Desa sifatnya hanya pengajuan dan diminta untuk melakukan verifikasi dan evaluasi data KPM.

Nah Bagus juga nih, sehingga pemerintah desa bisa menyesuaiakan

**Comment by afa28** [comment]
Jadi untuk issue ini hanya perlu tampilkan bantuan yg pernah diterima pd calon penerima bantuan??? Nanti pengurus/panitia yg melakukan pengecekan layak tdknya menerima bantuan.

**Comment by roaddee** [comment]
silahkan di cek di PR #3323 pak @mizwaruddin dan pak @MUHAMMADRANGSEL

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3323. Tetapi perhatikan bahwa saat ini, program bantuan sasaran keluarga TIDAK dapat menambahkan peserta lebih dari satu anggota keluarga. Misalnya, bagi program BNPT, untuk satu nomor KK, hanya bisa SATU anggota keluarga yg menerima bantuan tersebut. Jadi dari satu nomor KK, untuk program BNPT misalnya, kalau istri sdh menjadi peserta, kemudian tidak bisa menambah kepala keluarga atau anak sebagai peserta program itu.

Kalau diperbolehkan, silakan buat issue terpisah khusus keperluan itu. @mizwaruddin @MUHAMMADRANGSEL

**Comment by mizwaruddin** [comment]
Mulai versi brp, Bang? Soalnya versi 20.06-pasca sya masih bisa memasukkan 2 anggota KK dlm satu bantuan.

**Comment by afa28** [comment]
> Mulai versi brp, Bang? Soalnya versi 20.06-pasca sya masih bisa memasukkan 2 anggota KK dlm satu bantuan.

Setelah merger PR yg maslah bantuan untuk sasaran keluarga. Disitu ada pilihan kk, istri, anak jika salah 1 dr anggota tsb sdah menerima maka data dr keluarga penerima tsb tdk ditampilkan lg.

Klw pengguna sudah mengimput data sebelum PR tsb di merger, maka kemungkinan data double pd 1 keluarga bisa sja terjadi. Krn pd proses migrasi tdk mengecek apakah data penerima yg double di hapus apa tdk. Ini diserahkan ke pada petugas, agar sistem tdk salah dalam menghapus data secara otomatis.

**Comment by eddieridwan** [comment]
> Mulai versi brp, Bang? Soalnya versi 20.06-pasca sya masih bisa memasukkan 2 anggota KK dlm satu bantuan.

@M-A-Haris, @afri18, @MUHAMMADRANGSEL, @roaddee, @mizwaruddin @ilamazuliaf
Mengapa program seperti itu tidak dibuat sebagai sasaran penduduk/perorangan saja? Dengan demikian bebas penduduk yg bisa menjadi penerima bantuan -- berapa saja anggota keluarga bisa menjadi penerima. Cara ini lebih konsisten. Karena kalau suatu program bantuan betul2 sasarannya adalah KELUARGA, maka seharusnya satu keluarga hanya bisa menjadi penerima satu kali saja.

Satu cara untuk menampilkan infomasi tambahan, bisa sebagai berikut:

Di form tambah peserta sasaran penduduk, tampilkan bantuan yg diterima penduduk itu dan juga bantuan yg diterima keluarga penduduk tersebut (yaitu yg mempunyai nomor KK sama)
Di form tambah peserta sasaran keluarga, tampilkan bantuan yg diterima keluarga itu, dan juga bantuan yg diterima setiap anggota keluarga tersebut (untuk program sasaran penduduk)
Dengan cara itu, panitia bisa melihat secara keseluruhan bantuan yg diterima suatu keluarga (KK), baik dari bantuan dengan sasaran keluarga maupun dari bantuan sasaran perorangan.

**Comment by afa28** [comment]
Apa setuju dgn masukan dr pak @eddieridwan????  Klw iya, sy coba tambahkan lg informasi yg dibutuhkan sesuai alur yg diberikan pak @eddieridwan.
Klw tdk, bisa beri saran yg lainnya.
