### ISSUE TITLE
Garis pada Peta Terhalang oleh Angka 

### ISSUE THREAD

**Issue by mizwaruddin** [OpenSID/OpenSID#3316]
### Bagaimana alurnya sampai muncul masalah?
![peta_issue](https://user-images.githubusercontent.com/39736008/86937210-2bdf4200-c169-11ea-94c1-ef2a77f036e4.PNG)
Saat membuka tampilan peta di web pengunjung, garis pada peta terhalang oleh angka (panjang garis dan satuan). Hal ini menyebabkan peta kurang terlihat dengan jelas.

### Seperti apa yang diharapkan?
Angka pada peta dihilangkan agar garis pada peta terlihat dengan jelas.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by mizwaruddin** [comment]
@fusionid

**Comment by WAHYUDIK** [comment]
mungkin bisa dirubah cara menampilkan luasnya, bisa diberikan tulisan, misal:
Luas Wilayah Desa/Dusun/Rw/Rt=123
Panjang Wilayah Desa/Dusun/Rw/Rt=123
tulisan tersebut ditaruk di tengah2 kotak.

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3317
