### ISSUE TITLE
Ketika membuat garis dan area di menu pemetaan garis dan area yang sdh kita buat tdk muncul

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#3319]
### Bagaimana alurnya sampai muncul masalah?
Menu Pemetaan==>Pengaturan Peta, ketika kita sudah membuat garis, area dan kita menambahkan baru seperti garis dan area, kita kesulitan dari mana kita mulai. sehingga untuk area garis terpisah

### Seperti apa yang diharapkan?
Bisa memunculkan garis atau area yang sdh kita buat ketika kita ingin menambahkan garis atau area seperti pembuatan batas Dusun dan RT, dan juga kita mengetahui mana yang belum di kerjakan
![image](https://user-images.githubusercontent.com/25834335/87009077-43fda280-c1f7-11ea-91c1-aae2942f782a.png)

### Apa yang terjadi?
Garis 1 dan 2 tdk tersambung
Area 1 dan 2 tidak nyambung

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3320
