### ISSUE TITLE
Perbaiki jumlah tabel anggota keluarga pada rtf surat keterangan tidak mampu

### ISSUE THREAD

**Issue by benioke** [OpenSID/OpenSID#3321]
Bagaimana alurnya sampai muncul masalah?
Saat ini Hasil rtf nya hanya bisa mencetak maksimal tujuh anggota keluarga saja

Seperti apa yang diharapkan?
di dalam satu desa mungkin ada anggota keluarganya lebih dari tujuh anggota keluarga. Seharusnya hasil cetak surat rtf nya bisa memuat lebih dari tujuh anggota keluarga.

Apa yang terjadi?
Anggota keluarga nya hanya tampil sebanyak tujuh anggota.ketika di modifikasi file rtf nya malah terjadi error.
Contoh nya
![Capture](https://user-images.githubusercontent.com/47577404/87097807-30425280-c270-11ea-98ed-d6642aa5849b.JPG)
Ada sebanyak sepuluh anggota keluarga yang akan di cetak di surat..
![Capture1](https://user-images.githubusercontent.com/47577404/87097832-39cbba80-c270-11ea-8bf6-f9310e15ce45.JPG)
Setelah di modifikasi file rtf agar bisa menampilkan sepuluh anggota keluarga di surat cetak
![Capture2](https://user-images.githubusercontent.com/47577404/87097848-43552280-c270-11ea-892e-3d41ee1c8cf5.JPG)
Terjadi error
![Capture3](https://user-images.githubusercontent.com/47577404/87097858-46e8a980-c270-11ea-85a0-b46e759d779c.JPG)

 Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.07
| Versi PHP        | 
| System operasi   |

**Comment by roaddee** [comment]
ini karena memang ada batasan max_anggota di helper, apa perlua max_anggota anggota diganti dengan count saja, sehingga berapapun jumlah anggota KK tetap bisa terpenuhi, betul pak @eddieridwan ?

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3326
