### ISSUE TITLE
Area, Lokasi dan Garis masih muncul di Peta walaupun sudah dinonaktifkan di menu pemetaan

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#3328]
### Bagaimana alurnya sampai muncul masalah?
Area, Lokasi dan Garis masih muncul di Peta walaupun sudah dinonaktifkan di menu pemetaan, 
![image](https://user-images.githubusercontent.com/25834335/87253544-a2a07600-c4ae-11ea-829f-2557b4a0dd32.png)
namun Area, Garis dan Titik yang di Nonaktifkan tadi masih muncul di Peta
![image](https://user-images.githubusercontent.com/25834335/87253598-1478bf80-c4af-11ea-9b1c-44727b7b40ec.png)

### Seperti apa yang diharapkan?
Ketika menonaktifkan Area, Garis dan Lokasi maka di Peta tidak muncul

### Apa yang terjadi?
aktif/ tidak aktif Belum berfungsi 

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3358
