### ISSUE TITLE
Input Data Keuangan Secara Manual Belum Bisa Untuk Level Operator

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#3329]
### Bagaimana alurnya sampai muncul masalah?
Saat login halaman siteman dengan hak akses selain Administrator, menu Keuangan -> Input Manual dan Laporan Manual tidak tersedia.

### Seperti apa yang diharapkan?
Adanya menu Manual tersebut untuk mempermudah proses penginputan oleh Operator yang tidak diberi hak akses menjadi Administrator.

![image](https://user-images.githubusercontent.com/46939846/87387162-53e8fe00-c5cc-11ea-8a5b-f4e400586a5b.png)

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3359
