### ISSUE TITLE
Tambahan Menu Tentang Aset Desa

### ISSUE THREAD

**Issue by Zulkarnaimni** [OpenSID/OpenSID#3330]
--> Kalau bisa saya mohon penambahan menu utk pendataan aset-aset desa yang terbagi kepada dua bagian, (1) Aset Pembangunan, (2) aset-aset yg jadi modal desa, dengan field2 kolom "nama aset, jenis aset, tahun diperaleh, letak (dusun/rt/rw), Volume dan satuan.

Demiakian dulu sahabat-sahabat saya yg luar biasa, mohon advicce-nya dalam rangka kelengkapan informasi desa.

Harap diisi hanya untuk melaporakn bug atau permintaan penambahan fitur saja. Jika ada pertanyaan dukungan komunitas OpenSID sebaiknya posting di grup Facebook: https://www.facebook.com/groups/opensid
-->

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by HerryWanda** [comment]
Silakam diperjelaskan issue nya pak..
Kemudian tambahkan dasar /regulasi terkait data aset didesa yang bapak minta.

kami rasa untuk di data inventaris pada menu sekretariat disana udah ada ase pembangunan..

untuk issue, silakan disampaikan permasalahannya yang terjadi, sesuai format yang disediakan.

Supaya tidak rancu dan meragukan..

**Comment by Zulkarnaimni** [comment]
Maaf pak HarryWanda 
Lupa saya tutup sarannya, 
sebenarnya tentang "Asset Desa" sudah ada dalam menu Skretariat dalam Menu Inventaris salah saya tak membaca habis, mohon maaf pak, ada kesilapan, sudah terpenuhi......

**Comment by HerryWanda** [comment]
hehe , gpp pak...
Kita santai aja kok..
yg penting saling mengingatkan..
