### ISSUE TITLE
Menampil Statistik Menurut Dusun

### ISSUE THREAD

**Issue by Zulkarnaimni** [OpenSID/OpenSID#3331]
Harap diisi hanya untuk melaporakn bug atau permintaan penambahan fitur saja. Jika ada pertanyaan dukungan komunitas OpenSID sebaiknya posting di grup Facebook: https://www.facebook.com/groups/opensid
-->
![image](https://user-images.githubusercontent.com/64481641/87423639-d097ce80-c604-11ea-873e-d398f0b11961.png)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
@Zulkarnaimni , harap diperjelas apa yg diinginkan.

**Comment by Zulkarnaimni** [comment]
[cid:image003.png@01D65A34.E089BA10]
Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by Zulkarnaimni** [comment]
Statistik Pada Tampilan Peta, Desa saya ada 3 dusun yg mau di tampilkan statistiknya "ini pada tampilan Peta" cuma yg bisa di dusun no 2, sedang dusun no. 1 dan no. 3 statistik dari menu peta belum bisa ditampilkan" apa ada pengaruh dengan jumlah penduduknya, soal-nya dusun no. 2 ini jumlah penduduk-nya setengah saja dari dusun no. 1 dan no. 3.

Masalahnya menurut pemahaman teman2 karena ada spasi di nama dusun, logika saya bisa benar juga krn 2 dusun yg tidak mau tampil statistik pada Peta, nama dusunnya terdiri dari 2 suka kata, Tadi Pak @Mizwaruddin sarankan utk di Like Issue begitu pak @eddieridwan.

terimakasih atas reply-nya....

**Comment by HerryWanda** [comment]
Untuk data statistik tidak ada pengaruh jumlah penduduknya..

bgitu juga dengan nama dusun punya spasi.

Sila cobakan di demo..
masukkan aja nama dusun bpak disana..

Silakan, ditambah kan keterangan dri issue ini, biar jelas..
Singkat padat saja..

terimakasih

**Comment by afa28** [comment]
untuk masalah statistik dgn nama dusun yg memiliki spasi sdah ad di `master` melalui PR #3391

**Comment by Zulkarnaimni** [comment]
Oh ya Pak afa28, mohon maaf issue saya belum ditutup rupanya, masalah ini sudah ter-update beberapa minggu yg lalu masih di versi 20.07 pasca........
