### ISSUE TITLE
Gagal Import Data Penduduk (pengaturan database - import database)

### ISSUE THREAD

**Issue by roaddee** [OpenSID/OpenSID#3332]
### Bagaimana alurnya sampai muncul masalah?
Ketika melakukan import data penduduk dari menu pengaturan database, muncul notifikasi sukses dan tidak ada data yang gagal diimport, spt gambar di bawah ini
![image](https://user-images.githubusercontent.com/45786885/87438421-b1f00280-c619-11ea-99e0-df92fb311722.png)

### Seperti apa yang diharapkan?
Import sukses dilaksanakan

### Apa yang terjadi?
Ternyata import data penduduk tersebut gagal dilaksanakan
![image](https://user-images.githubusercontent.com/45786885/87438876-48242880-c61a-11ea-935a-458bc40913fc.png)

### Informasi tambahan 
Terjadi juga pada saat diujicoba di situs demo

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.07
| Versi PHP        | 7.3
| System operasi   | Windows 10

**Comment by afa28** [comment]
Contoh data yg bisa digunakan pd kasus ini ada pak @roaddee ???

**Comment by roaddee** [comment]
saya coba lagi dulu @afa28 , karena sepertinya ini sudah bisa.

**Comment by mizwaruddin** [comment]
@afa28 sudah terselesaikan.
