### ISSUE TITLE
Tambahkan cetak dan unduh data persil

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#3333]
### Bagaimana alurnya sampai muncul masalah?
1. Buka menu Pertanahan > Daftar Persil
2. Klik tombol Cetak atau Unduh

### Seperti apa yang diharapkan?
Ditampilkan/diunduh laporan data persil

### Apa yang terjadi?
Saat ini kedua tombol itu belum aktif.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | v20.07-pasca
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
Catatan :
1. Gunakan format cetak yg sudah disediakan
2. Ubah limit menjadi 0
3. Dll

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3856
