### ISSUE TITLE
Error Daftar Persil Letter C pada menu "Daftar Persil"

### ISSUE THREAD

**Issue by Zulkarnaimni** [OpenSID/OpenSID#3335]
Error Daftar Persil Letter C pada menu "Daftar Persil"
![image](https://user-images.githubusercontent.com/64481641/87512313-f7a3de00-c6a0-11ea-88c2-60b7f47d8839.png)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master`
