### ISSUE TITLE
BPD dan Bumdes

### ISSUE THREAD

**Issue by alipeane** [OpenSID/OpenSID#3340]
### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
@alipeane mohon selalu lengkapi setiap issue sesuai dengan template yg sdh disedkakan. Dan juga selalu pastikan belum ada issue serupa yg sdh dilaporkan sebelumnya. Misalnya lihat https://github.com/OpenSID/OpenSID/issues/2840.
