### ISSUE TITLE
Tambah Pilihan Laporan Keuangan Per Semester di Artikel

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#3341]
### Bagaimana alurnya sampai muncul masalah?
Saya ingin membuat artikel tentang Laporan Keuangan Semester 1 yang diimport dari Siskeudes. Namun pada saat membuat artikel, saya belum menemukan adanya pilihan Laporan Keuangan berdasarkan Bulanan, Triwulan, maupun per Semester.
Sehingga, Laporan yang akan ditampilkan ke Website Desa sementara ini menggunakan Screenshot saja.

Saat ini yang ada adalah Laporan Keseluruhan, yang mana jika nantinya data import Siskeudes diupdate, maka akan berubah pula angka pada artikel yang sudah pernah dibuat sebelumnya (menjadikan laporan tidak sesuai dengan judul).

![1](https://user-images.githubusercontent.com/46939846/87692876-75a5d900-c7b6-11ea-9002-cfa5133a83f1.png)

![3](https://user-images.githubusercontent.com/46939846/87692891-7a6a8d00-c7b6-11ea-8fc8-71ce52ca48d0.png)

![2](https://user-images.githubusercontent.com/46939846/87692978-98d08880-c7b6-11ea-93d2-a4697777edd7.png)

### Seperti apa yang diharapkan?
Tentunya bisa ditampilkan untuk Laporan Keuangan per semester di setiap tahun nya, mengingat Laporan tersebut dapat membantu memberikan informasi tranparansi perkembangan keuangan desa.

**Comment by eddieridwan** [comment]
@fusionid , apakah sebagai opsi ada solusi untuk menyisipkan laporan keuangan dalam bentuk statis, yaitu menampilkan data keuangan pada saat disiip, sehingga tidak berubah secara dinamis pada saat ditampilkan. Misalnya, laporan dikonversi menjadi pdf atau image kemudian baru disisipkan ke artikel?

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3360
