### ISSUE TITLE
Laporan rentan (cetak/unduh) tidak sesuai

### ISSUE THREAD

**Issue by ilamazuliaf** [OpenSID/OpenSID#3346]
### Bagaimana alurnya sampai muncul masalah?
1. Menu Statistik
2. Sub Menu Laporan Kelompok Rentan -> Cetak

### Seperti apa yang diharapkan?
Laporan cacat dan tidak cacat sesuai dengan yang diharapkan

### Apa yang terjadi?
Seharusnya data cacat, akan tetapi yang ditampilkan data tidak cacat

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.07-pasca
| Versi PHP        | 7.2+
| System operasi   | Windows 7

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3347
