### ISSUE TITLE
Taben Penerima Bantuan Tidak Sesuai

### ISSUE THREAD

**Issue by ilamazuliaf** [OpenSID/OpenSID#3348]
### Bagaimana alurnya sampai muncul masalah?
Terdapat pebedaan antara data KK di Home dan Tabel Penerima Bantuan.
<img width="1218" alt="Screen Shot 2020-07-20 at 00 19 30" src="https://user-images.githubusercontent.com/31075119/87880864-51006a00-ca1f-11ea-8b81-b18b8c100847.png">
<img width="882" alt="Screen Shot 2020-07-20 at 00 19 47" src="https://user-images.githubusercontent.com/31075119/87880873-66759400-ca1f-11ea-945b-883854084b22.png">
Selain itu terdapat kekeliruan di jenis kelamin serta jumlah dari bukan penerima 

### Seperti apa yang diharapkan?
Jenis Kelamin yang dipakai adalah peserta yang menerima bukan dari Kepala Keluarga yang menerima. Jumlah yang tidak menerima bantuan bukan perhitungan dari Jumlah KK dikurangi Total Penerima melainkan perhitungan secara real Keluarga yang benar-benar tidak menerima bantuan sama sekali

### Apa yang terjadi?
Terjadi minus data Bukan Penerima dikarenakan ada satu KK mendapat dua bantuan, misalnya PKH dan BPNT. Perlu menghitung ulang Jumlah Penerima perjenis kelamin secara manual meski terdapat Sistem Informasi

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.07-pasca
| Versi PHP        | 7.2+
| System operasi   |

**Comment by masumo** [comment]
@ilamazuliaf tabel penerima bantuan yang ada di atas, diambil dari menu apa ya? apakah dari menu **statistik kependudukan**?

yang saya lihat, dari menu **Statistik kependudukan** dan menu **Bantuan** sbb:
1. yang terdaftar sebagai peserta adalah kepala keluarga. walaupun saat entri data di menu **Bantuan** kita pilih istri atau anak perempuan, tetapi yang dihitung sebagai **PENERIMA** tetap kepala keluarga. Namun, di menu Bantuan ada data nama yang tercantum di kartu peserta (untuk nama yang di sini, sesuai dengan yang kita pilih saat entri data)

![bantuan](https://user-images.githubusercontent.com/19631687/88354102-07e74780-cd8a-11ea-8cd6-6db0e478a048.jpg)


2. jika ada keluarga yang menerima lebih dari satu bantuan, pada rekapitulasi jumlah **PENERIMA** di menu statistik dihitung juga lebih dari satu

![statistik](https://user-images.githubusercontent.com/19631687/88354141-29483380-cd8a-11ea-8f66-0a114f4b797e.jpg)


yang ingin saya tanyakan @ilamazuliaf 
di rekapitulasi penerima bantuan, terdapat jenis kelamin perempuan. apakah ini berarti kepala keluarganya adalah perempuan?

pak @eddieridwan saya tertarik untuk mengerjakan issue ini:
1. untuk peserta yang dihitung di rekapitulasi, apakah kepala keluarga atau nama yang tercatat di kartu peserta (di menu **Bantuan**)?
2. untuk keluarga yang menerima lebih dari satu bantuan, di rekapitulasi jumlah **PENERIMA** apakah dihitung sebagai 1 entitas?

**Comment by ilamazuliaf** [comment]
> @ilamazuliaf tabel penerima bantuan yang ada di atas, diambil dari menu apa ya? apakah dari menu **statistik kependudukan**?
> 
> yang saya lihat, dari menu **Statistik kependudukan** dan menu **Bantuan** sbb:
> 
> 1. yang terdaftar sebagai peserta adalah kepala keluarga. walaupun saat entri data di menu **Bantuan** kita pilih istri atau anak perempuan, tetapi yang dihitung sebagai **PENERIMA** tetap kepala keluarga. Namun, di menu Bantuan ada data nama yang tercantum di kartu peserta (untuk nama yang di sini, sesuai dengan yang kita pilih saat entri data)
> 
> ![bantuan](https://user-images.githubusercontent.com/19631687/88354102-07e74780-cd8a-11ea-8cd6-6db0e478a048.jpg)
> 
> 1. jika ada keluarga yang menerima lebih dari satu bantuan, pada rekapitulasi jumlah **PENERIMA** di menu statistik dihitung juga lebih dari satu
> 
> ![statistik](https://user-images.githubusercontent.com/19631687/88354141-29483380-cd8a-11ea-8f66-0a114f4b797e.jpg)
> 
> yang ingin saya tanyakan @ilamazuliaf
> di tabel penerima bantuan yang anda share, terdapat jenis kelamin perempuan. apakah ini berarti kepala keluarganya adalah perempuan?
> 
> pak @eddieridwan saya tertarik untuk mengerjakan issue ini:
> 
> 1. untuk peserta yang dihitung di rekapitulasi, apakah kepala keluarga atau nama yang tercatat di kartu peserta (di menu **Bantuan**)?
> 2. untuk keluarga yang menerima lebih dari satu bantuan, di rekapitulasi jumlah **PENERIMA** apakah dihitung sebagai 1 entitas?

di admin web -> artikel -> buat artikel-> disana bisa melampirkan daftar penerima bantuan. Untuk kepala keluarga perempuan merupakan dari warga perempuan lansia yang cuma sendirian di KK (otomatis menjadi kepala keluarga di KK)

**Comment by eddieridwan** [comment]
@ilamazuliaf @afa28 

Untuk program bantuan sasaran Keluarga, aturannya adalah:

1. Satu keluarga hanya boleh menerima bantuan satu kali utk masing2 program. Pada waktu menambah peserta program, keluarga yg bersangkutan dapat dicari menggunakan nama/nik kepala keluarga, istri/suami dan anak, sesuai dengan nama yg tercatat di kartu peserta.
2. Walaupun yg tercatat di kartu peserta adalah anggota keluarga, namun di sistem yg tercatat sebagai peserta adalah kepala keluarga.
3. Statistik program bantuan sasaran keluarga adalah berdasarkan biodata kepala keluarga
4. Di laporan statistik, jumlah total keluarga penerima seharusnya keluarga unik. Yaitu kalau ada keluarga menjadi peserta di lebih dari satu program bantuan, tetap dihitung satu kali saja. 
5. Di laporan statistik, jumlah total keluarga yg bukan penerima adalah keluarga yg tidak menjadi peserta di program bantuan sasaran keluarga manapun. 

Kalau berminat mengerjakan issue ini, beritahu dan saya akan assign anda.

**Comment by afa28** [comment]
> @ilamazuliaf @afa28 
> 
> Untuk program bantuan sasaran Keluarga, aturannya adalah:
> 
> 1. Satu keluarga hanya boleh menerima bantuan satu kali utk masing2 program. Pada waktu menambah peserta program, keluarga yg bersangkutan dapat dicari menggunakan nama/nik kepala keluarga, istri/suami atau anak, sesuai dengan nama yg tercatat di kartu peserta.
> 2. Walaupun yg tercatat di kartu peserta adalah anggota keluarga, namun di sistem yg tercatat sebagai peserta adalah kepala keluarga.
> 3. Statistik program bantuan sasaran keluarga adalah berdasarkan biodata kepala keluarga
> 4. Di laporan statistik, jumlah total keluarga penerima seharusnya keluarga unik. Yaitu kalau ada keluarga menjadi peserta di lebih dari satu program bantuan, tetap dihitung satu kali saja. 
> 5. Di laporan statistik, jumlah total keluarga yg bukan penerima adalah keluarga yg tidak menjadi peserta di program bantuan sasaran keluarga manapun. 
> 
> Kalau berminat mengerjakan issue ini, beritahu dan saya akan assign anda. 

Pak @masumo kyaknya sdang mendalami issue ini pak @eddieridwan.

**Comment by eddieridwan** [comment]
Ok, yg akan mengerjakan @masumo atau @ilamazuliaf mohon beri komentar di issue ini, supaya tidak dikerjakan dua orang. Kalau anda bisa assign diri sendiri, silakan. Kalau tidak beritahu dan saya akan assign.

**Comment by masumo** [comment]
saya baru mulai lihat menunya pak. belum saya kerjakan. 
pak @ilamazuliaf sudah mulai kerjakan? kalo sudah, silakan dilanjutkan. tapi kalo belum, saya siap untuk mengerjakannya.
saya ngga bisa assign saya sendiri pak @eddieridwan

**Comment by ilamazuliaf** [comment]
Saya belum mengerjakan sama sekali pak @masumo karena emang ada kerjaan lain. Mungkin dilanjut saja.

**Comment by masumo** [comment]
> Saya belum mengerjakan sama sekali pak @masumo karena emang ada kerjaan lain. Mungkin dilanjut saja. 

Oke siapp...

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3379
