### ISSUE TITLE
Upload File PDF eror muncul keterangan file berisi script

### ISSUE THREAD

**Issue by WAHYUDIK** [OpenSID/OpenSID#3350]
### Bagaimana alurnya sampai muncul masalah?

Ketika kita upload file berupa pdf di menu sekretariat muncul keterangan eror file berisi script, seperti contoh dibawah
![image](https://user-images.githubusercontent.com/31026980/88004263-de7faf00-cb30-11ea-9a2a-b1a6203c352e.png)

### Seperti apa yang diharapkan?
Tidak muncul eror seperti gambar

### Apa yang terjadi?
kedepan tidak terjadi eror lagi, dan diharapkan ketika upload file yang ukurannya lebih dari 2mb akan ter kompres oleh sistem

### Informasi tambahan 
[perubahan apbdes 2020 kecil.pdf](https://github.com/OpenSID/OpenSID/files/4950889/perubahan.apbdes.2020.kecil.pdf)
| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
@WAHYUDIK harap lampirkan file PDF yg bermasalah tersebut.

**Comment by WAHYUDIK** [comment]
sudah pak itu di bawahnya informasi tambahan

**Comment by WAHYUDIK** [comment]
[perubahan apbdes 2020.pdf](https://github.com/OpenSID/OpenSID/files/4951048/perubahan.apbdes.2020.pdf)
ini file aslinya pak, untuk yang di atas itu setelah di kompres

**Comment by ilamazuliaf** [comment]
bagaimana pak @eddieridwan kalau disediain hanya menyertakan link saja (misalnya link dari Google Drive yang mengarah ke file pdf). Kalau misal semua file pdf diinput semua ke system akan membengkak dan membebani server

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master`.
