### ISSUE TITLE
EXTERNAL LINK DI MENU STATIS TIDAK BISA

### ISSUE THREAD

**Issue by rudihasan** [OpenSID/OpenSID#3351]
### Bagaimana alurnya sampai muncul masalah?

Saat buat external link di menu dinamis link nya berlapis
Jadi seperti ini mas

https://alahanmati.com/first/https://www.pasamankab.go.id/

### Seperti apa yang diharapkan?

Harus nya seperti ini ya mas
https://www.pasamankab.go.id/

### Apa yang terjadi?

 Jadi  muncul error 404 The page you requested was not found.
Kami tidak dapat menemukan halaman yang Anda inginkan. Untuk sementara Anda dapat kembali ke halaman awal atau ke halaman sebelumnya.

### Informasi tambahan 
MOHON BANTUAN NYA MAS. TERIMA KASIH
![Screenshot_1](https://user-images.githubusercontent.com/68593604/88049817-f5012700-cb7f-11ea-98ed-851e00f6d9e0.png)
![Screenshot_2](https://user-images.githubusercontent.com/68593604/88049819-f6325400-cb7f-11ea-860c-e17754972b61.png)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 7.3
| System operasi   |

**Comment by afa28** [comment]
Cuma masalah view sj, dimana view tdk sesuai dgn isi database.

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3353
