### ISSUE TITLE
Statistik pengunjung

### ISSUE THREAD

**Issue by cahyasw** [OpenSID/OpenSID#3352]
Maaf mau tanya apakah ini query ini memang di model seperti ini atau tidak?
![query](https://user-images.githubusercontent.com/7914909/88078308-81bedb80-cba6-11ea-97f7-624df9bfca47.PNG)

soalnya hasil dari query tersebut di table sys_traffic seperti ini, setiap pengunjung jml nya 1 ip nya tersimpan tapi kalo lebih dari 1 ip nya terupdate dan ilang
![insert](https://user-images.githubusercontent.com/7914909/88078530-c6e30d80-cba6-11ea-83a8-58e3792ad414.PNG)

### Bagaimana alurnya sampai muncul masalah?
Pengunjung pertama di satu tanggal tertentu ip nya tersimpan namun kalo ada pengunjung kedua dan seterusnya ip nya terupdate kosong jumlah bnr nambah

### Seperti apa yang diharapkan?
apakah memang di setting seperti itu?

### Apa yang terjadi?
Yang terjadi tidak ada error namun apabila iseng malkukan pengecekan ip brpa saja yang masuk dg jumlah tesebut tidak ada

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20-07-pasca
| Versi PHP        | 7.4
| System operasi   | Windows 10

**Comment by afa28** [comment]
> Maaf mau tanya apakah ini query ini memang di model seperti ini atau tidak?
> ![query](https://user-images.githubusercontent.com/7914909/88078308-81bedb80-cba6-11ea-97f7-624df9bfca47.PNG)
> 
> soalnya hasil dari query tersebut di table sys_traffic seperti ini, setiap pengunjung jml nya 1 ip nya tersimpan tapi kalo lebih dari 1 ip nya terupdate dan ilang
> ![insert](https://user-images.githubusercontent.com/7914909/88078530-c6e30d80-cba6-11ea-83a8-58e3792ad414.PNG)
> 
> ### Bagaimana alurnya sampai muncul masalah?
> Pengunjung pertama di satu tanggal tertentu ip nya tersimpan namun kalo ada pengunjung kedua dan seterusnya ip nya terupdate kosong jumlah bnr nambah
> 
> ### Seperti apa yang diharapkan?
> apakah memang di setting seperti itu?
> 
> ### Apa yang terjadi?
> Yang terjadi tidak ada error namun apabila iseng malkukan pengecekan ip brpa saja yang masuk dg jumlah tesebut tidak ada
> 
> ### Informasi tambahan
> Tanya	Jawab
> Versi OpenSID	20-07-pasca
> Versi PHP	7.4
> System operasi	Windows 10

Untuk modul ini memang perlu penyesuaian ulang, krn yg skrang querynya masih disimpan di view.

**Comment by cahyasw** [comment]
Terima kasih

**Comment by ndunks** [comment]
Bisakah dijelaskan penghitungan trafik yang di inginkan seperti apa? 

Apakah IP Address diperlukan untuk disimpan (log) per-hari, atau hanya menghitung jumlah pengunjung per-hari?

Lagi pula pengambilan IP tersebut tidak akan efektif ketika server berada dibalik CloudFlare dan CDN aktif. Jadi saya rasa IP tidak diperlukan. Jika memang IP harus di log, maka script harus mengecek header lain seperti `CF-Connecting-IP`, `True-Client-IP)`, atau `X-Forwarded-For`, baru terakhir dari real remote IP.

**Comment by eddieridwan** [comment]
Sdh dicommit ke `bug-fix` melalui https://github.com/OpenSID/premium/pull/182
