### ISSUE TITLE
Menu operator

### ISSUE THREAD

**Issue by cahyasw** [OpenSID/OpenSID#3354]
Untuk menu operator memang tidak ada menu layanan mandiri?
![image](https://user-images.githubusercontent.com/7914909/88131811-0ee64c80-cc08-11ea-8ac3-bcfaefa61398.png)

### Bagaimana alurnya sampai muncul masalah?
Masuk user operatori

### Seperti apa yang diharapkan?
Apakah menu layanan mandiri tidak muncul di user operator?

### Apa yang terjadi?
layanan mandiri tidak muncul

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20-07 pasca
| Versi PHP        | 7.4
| System operasi   | Win 10

**Comment by eddieridwan** [comment]
Hak akses masing-masing kategori pengguna yg berlaku saat ini dijabarkan di http://bit.ly/2Vhqmyz.

**Comment by afa28** [comment]
Sudah ada akses ke controllernya tp view menu di navigasinya tdk ditampilkan. Coba akses lewat url, maka akan masuk ke menu2 layanan mandiri tsb.

http://manurung.desa.id/mandiri
http://manurung.desa.id/permohonan_surat_admin
http://manurung.desa.id/mailbox

**Comment by afa28** [comment]
Jika menu navigasi (parrent menu) tdk memiliki controller, maka pd url setting_aplikasi dikosongkan.

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3415
