### ISSUE TITLE
Sediakan API supaya server OpenDesa bisa kirim pengumuman ke OpenSID. 

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#3355]
### Bagaimana alurnya sampai muncul masalah?
Saat ini belum ada cara untuk server OpenDesa mengirim pengumuman ke OpenSID.

### Seperti apa yang diharapkan?
OpenSID dapat menerima kiriman pengumuman dari server OpenDesa, dan menampilkan pengumuman tersebut. 
Yaitu ada API untuk menerima pengumuman.

### Informasi tambahan 
API menghasilkan entri di tabel `notifikasi`. 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | v20.07-pasca
| Versi PHP        | 
| System operasi   |

**Comment by masumo** [comment]
pak @eddieridwan source code server opendesa ada di mana pak?
alur untuk pengecekan dan cara menampilkan pengumuman seperti apa?

**Comment by eddieridwan** [comment]
@masumo , repo trackSID ada di https://github.com/OpenSID/tracksid. 

Tapi issue yg lebih mudah dan lebih penting adalah https://github.com/OpenSID/OpenSID/issues/3437. Issue #3437 berbeda sedikit dengan issue #3355. API OpenSID tidak diperlukan untuk #3437 -- hanya memproses data yg dikirim balik pada waktu OpenSID memanggil trackSID. Apakah anda siap mengerjakan #3437

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master`
