### ISSUE TITLE
Masih bisa input NIK yang sama dalam Program Bantuan yang sama pula.

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#3356]
### Bagaimana alurnya sampai muncul masalah?
Saat ini masih bisa input NIK yang sama dalam 1 program bantuan.

Langkah yang saya lakukan adalah:
1. Saya gunakan fitur cari, sehingga nama yang muncul di tabel hanya nama yang dicari tersebut.
2. Lalu saya lakukan penambahan penduduk, nama yang sudah terdaftar muncul kembali.

Kesimpulan sementara penduduk yang tidak muncul di tabel akibat hanya menampilkan hasil pencarian, bisa diinput ulang.

![image](https://user-images.githubusercontent.com/46939846/88177624-6958ca80-cc53-11ea-8cee-284c1e85900e.png)

### Seperti apa yang diharapkan?
Batasi hanya bisa lakukan input Penduduk dengan NIK yang sama dalam 1 program bantuan yang sama pula.

### Apa yang terjadi?
Supaya tidak ada data ganda pada 1 program bantuan yang sama tersebut.

**Comment by afa28** [comment]
Untuk sasaran penduduk kyaknya mmang belum terlalu di sentuh, selama ini msh fokus di  sasaran keluarga krn yg sering di issuekan adlah sasaran keluarga.

**Comment by ariandii** [comment]
Hal tersebut juga terjadi pada Sasaran Keluarga:

Teknisnya sama, lakukan pencarian untuk keluarga A dan lakukan input Kepala Keluarga yang lain yang tidak muncul di tabel hasil pencarian.

![image](https://user-images.githubusercontent.com/46939846/88182233-26e6bc00-cc5a-11ea-97d5-e7269a7bfed2.png)

![image](https://user-images.githubusercontent.com/46939846/88182211-20f0db00-cc5a-11ea-9f12-638389049d33.png)

**Comment by afa28** [comment]
> Hal tersebut juga terjadi pada Sasaran Keluarga:
> 
> Teknisnya sama, lakukan pencarian untuk keluarga A dan lakukan input Kepala Keluarga yang lain yang tidak muncul di tabel hasil pencarian.
> 
> ![image](https://user-images.githubusercontent.com/46939846/88182233-26e6bc00-cc5a-11ea-97d5-e7269a7bfed2.png)
> 
> ![image](https://user-images.githubusercontent.com/46939846/88182211-20f0db00-cc5a-11ea-9f12-638389049d33.png)
> 

Berarti query yg digunakan untuk mencari dan filtering sama 🤔🤔🤔

**Comment by afa28** [comment]
> Hal tersebut juga terjadi pada Sasaran Keluarga:
> 
> Teknisnya sama, lakukan pencarian untuk keluarga A dan lakukan input Kepala Keluarga yang lain yang tidak muncul di tabel hasil pencarian.
> 
> ![image](https://user-images.githubusercontent.com/46939846/88182233-26e6bc00-cc5a-11ea-97d5-e7269a7bfed2.png)
> 
> ![image](https://user-images.githubusercontent.com/46939846/88182211-20f0db00-cc5a-11ea-9f12-638389049d33.png)
> 

Dr codingannya sy sdah pusing duluan, bagai benang kusut 😆😆😆

**Comment by ariandii** [comment]
@afa28 
Semangat 😆😆😆

**Comment by eddieridwan** [comment]
Sdh dicommit ke `rilis-dev` melalui https://github.com/OpenSID/premium/pull/138
