### ISSUE TITLE
Ubah Urutan Tabel pada Pengelompokan Rumah Tangga

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#3361]
### Bagaimana alurnya sampai muncul masalah?
Saat input data pada menu Kependudukan -> Rumah Tangga, tabel yang ada saat ini menampilkan sesuai nomor urut penginputan.

### Seperti apa yang diharapkan?
Data rumah tangga yang diinput terakhir diharapkan berada pada urutan pertama, agar tidak perlu pindah ke halaman terakhir setelah input baru.

### Apa yang terjadi?
Meminimalisir waktu.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
Klw issue mengenai default urutan data yg ditampilkan mungkin sebaiknya harus disepakati bersama. Krn sy kihat ada beberapa issue yg permasalahkan masalah default pengurutan data ini. Dmna 1 pihak membuat issue agar defaut di urutkan berdasakan nik sedangkan yg lainnya membuat issue berdasarkan tgl terakhir input. Ini akan selalu terjadi jika tdk disepakati bersama.

Namun untuk mengatasi perbedaan tsb sebenarnya sudah disediakan opsi untuk mengurutkan data pd masing2 modul bersangkutan.

**Comment by ariandii** [comment]
Yang diingin kan pada issue ini lebih kepada saat input data rumah tangga baru dan saat klik simpan, data tsb berada pada baris paling atas. yang terjadi saat ini adalah data terbaru berada di paling akhir pada saat proses simpan.

**Comment by afa28** [comment]
> Yang diingin kan pada issue ini lebih kepada saat input data rumah tangga baru dan saat klik simpan, data tsb berada pada baris paling atas. yang terjadi saat ini adalah data terbaru berada di paling akhir pada saat proses simpan.

Pak @ariandii , ini contoh issue yg mempermasalahkan pengurutan data #3213, #3121. Hanya issue ##3121 yg sy PRkan, krn bisa sj akan muncul issue pd modul yg sama untuk mengubah urutannya lg, jd untuk sementara sy tdk krjakan issue mengenai pengurutan default.

Pak @eddieridwan , mungkin bisa luruskan.

**Comment by ariandii** [comment]
Siap pak, 
Untuk tabel yang pertama kali dilihat mungkin pengurutannya sesuai dengan issue terdahulu.

Namun untuk issue ini lebih kepada Urutan saat Klik Simpan setelah menambah Data Baru.

Jika nantinya klik Data Rumah Tangga, bisa saja urutannya sesuai yang telah diterapkan saat ini.

Hanya saja apa mungkin bisa diterapkan, khusus saat input data baru, maka tertampil data tersebut di urutan atas, (terlepas pada urutan tabel secara default yang pertama kali membuka tabel tersebut).

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3389
