### ISSUE TITLE
[Buku Admin Umum] Pisahkan pelaporan jenis peraturan desa

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#3363]
Dari @HerryWanda : 

Untuk Perdes : 
1.Peraturan Desa (Perdes)
2.Peraturan Kepala Desa (Perkades)
3. Peraturan Bersama Kepala Desa

Ini untuk penomoran masing-masingnya berbeda.

Kemudian memiliki rekap masing2 dari peraturan diatas pak.
Setelah saya coba mencetak rekap, belum ada pilihan untuk memisahkan antara 3 jenis peraturan tersebut diatas. Jadi pas dicetak nantik tercampur registrasinya.

Jadi usulan, mungkin diberi menu pilihan pas cetak rekap atau untuk melihat jenis peraturan : 
![r](https://user-images.githubusercontent.com/32125282/88263380-2ac71c80-ccf4-11ea-8427-258804ab5a16.jpg)

Kemudian pada menu cetak diberi juga pilihan jenis peraturan yang akan di cetak ;
![kd](https://user-images.githubusercontent.com/32125282/88263711-a6c16480-ccf4-11ea-87d7-eb5b29911135.jpg)

**Comment by MUHAMMADRANGSEL** [comment]
Pas sekali
