### ISSUE TITLE
Menu Statistik pada tampilan web 404 not found.

### ISSUE THREAD

**Issue by rullydamara** [OpenSID/OpenSID#3365]
### Bagaimana alurnya sampai muncul masalah?
Banyak menu statistik tidak bisa diakses lagi di halaman utama web (menampilkan 404), salah satunya statistik :
Asuransi
Golongan darah
Daftar calon pemilih
Disabilitas
Akte kelahiran
Keluarga berencana (kb)
Sakit menahun
Warga negara

### Seperti apa yang diharapkan?
Menu statistik tersebut dapat diakses lagi, sebagai sarana informasi untuk warga.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.07-pasca
| Versi PHP        | 7.2
| System operasi   |

**Comment by afa28** [comment]
Pak @rullydamara, perlu diketahui bahwa statistik (menu scr umum) yg dapat diakses adalah yg diaktifkan sj. Dan sy test di demo maupun di local lancar2 sj.

**Comment by ariandii** [comment]
Karena belum diaktifkan pada halaman menu.

**Comment by ariandii** [comment]
Karena ini bukan bug, silakan close.

**Comment by rullydamara** [comment]
Oke, terima kasih infonya.
Saya kaget aja kenapa gak bisa ngakses, ternyata harus diaktifkan dulu. 
Efek kurang ngikutin update beberapa bulan ini (dari v20.02 langsung ke v20.07-pasca)
