### ISSUE TITLE
untuk persil sebaiknya dikasih menu cetak

### ISSUE THREAD

**Issue by cakwidodo** [OpenSID/OpenSID#337]
![111 persil](https://cloud.githubusercontent.com/assets/19636829/23649150/f49df69a-034f-11e7-9db1-cecaeeec9fcd.jpg)

**Comment by eddieridwan** [comment]
@cakwidodo, laporan yang ingin dihasilkan seperti apa? Harap beri contoh
konsepnya.

**Comment by cakwidodo** [comment]
Cetak langsung atau excel mirip data penduduk

**Comment by YokaYunanda** [comment]
![cetakpersil](https://cloud.githubusercontent.com/assets/26480001/24081683/e2629072-0cea-11e7-8a61-fade11351123.jpg)

Seperti ini?

**Comment by cakwidodo** [comment]
Betul mas......

**Comment by YokaYunanda** [comment]
Proses

**Comment by cakwidodo** [comment]
Sip
Trim's

**Comment by eddieridwan** [comment]
Sdh dicommit ke master melalui pull request https://github.com/OpenSID/OpenSID/pull/802
