### ISSUE TITLE
Tampilan Web OpenSID Error

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#3370]
### Bagaimana alurnya sampai muncul masalah?
Dulu, saat tema tambahan dihapus dari folder desa/themes/namatema maka tampilan website otomatis menjadi tema default tanpa harus setting di menu pengaturan tampilan.

Saat ini tema default berubah jadi tema klasik, namun hal yang terjadi seperti dibawah ini.
![IMG_20200724_234825](https://user-images.githubusercontent.com/46939846/88410142-8be01480-ce08-11ea-8124-76b522971290.jpg)

### Seperti apa yang diharapkan?
Saat folder tema pada pengaturan tampilan tidak terdeteksi, maka akan otomatis tampil tema klasik.

### Apa yang terjadi?
Agar tidak terjadi error 500.

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3372
