### ISSUE TITLE
System SID di ubuntu server 16.04 LTS apakah perlu install codeigniter?

### ISSUE THREAD

**Issue by khoiron81** [OpenSID/OpenSID#3371]
Hi, 

Terimakasih saya ucapkan kepada team kontributor OpenSID. Program ini betul" hebat dan sangat berguna. Saya telah sukses menginstall di server ubuntu 16.04 LTS saya tanpa ada masalah. 

Sedikit lambat respon ketika login ke admin dan kadang perlu saya refresh untuk login. Kira" masalahnya di script atau server saya ya? mohon pencerahannya.

Dana apakah perlu saya install codeigniter di server saya supaya performance applikasi OpenSID ini optimal?

Terimakasih sebelumnya

**Comment by afa28** [comment]
Silahkan baca panduan atau bertanya di group FB OpenSID.

**Comment by pandigresik** [comment]
secara otomatis ketika install OpenSID ini maka akan install codeigniter juga, karena sudah include didalamnya, sepertinya issue ini bisa diclose
