### ISSUE TITLE
Perbaiki jumlah tabel anggota keluarga pada rtf maupun pdf pada surat keterangan pindah penduduk

### ISSUE THREAD

**Issue by benioke** [OpenSID/OpenSID#3374]
Bagaimana alurnya sampai muncul masalah?
Hampir sama dengan issue #3321.Saat ini Hasil rtf maupun pdf  dari surat keterangan pindah hanya bisa mencetak maksimal tujuh anggota keluarga saja atau di batasi.

Seperti apa yang diharapkan?
di dalam satu desa mungkin ada anggota keluarganya lebih dari tujuh anggota keluarga yang ingin pindah. Seharusnya hasil cetak surat rtf maupun pdf nya bisa memuat lebih dari tujuh anggota keluarga yang ingin pindah sesuai banyak nya anggota dalam keluarga.

Apa yang terjadi?
Anggota keluarga nya hanya tampil sebanyak tujuh anggota.ketika di modifikasi file rtf nya malah terjadi error.
Contoh nya 
Ada sebanyak sepuluh anggota keluarga termasuk kepala keluarga yang akan di cetak di surat..
![Capture1](https://user-images.githubusercontent.com/47577404/88466124-667c0500-cef3-11ea-967f-8a2d9e7b19e0.JPG)

Ketika di cetak hasil pada pdf nya hanya bisa menampilkan tujuh anggota saja
![Capture](https://user-images.githubusercontent.com/47577404/88466156-b35fdb80-cef3-11ea-8432-4e21de136c51.JPG)

Sedangkan untuk rft nya setelah di modifikasi hasil nya error
![Capture3](https://user-images.githubusercontent.com/47577404/88466176-d9857b80-cef3-11ea-918b-d8241248626c.JPG)

 Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.07
| Versi PHP        | 
| System operasi   |

**Comment by pandigresik** [comment]
apakah ini sudah terselesaikan di issue #3321 ? Jika sudah terselesaikan mungkin bisa di close issue ini

**Comment by mizwaruddin** [comment]
@afa28 sudah terselesaikan.
