### ISSUE TITLE
Pengaturan Peta Pada Menu Garis

### ISSUE THREAD

**Issue by Zulkarnaimni** [OpenSID/OpenSID#3375]
### Seperti apa yang diharapkan?
MOHON SOLUSI PARA MASTER
Menu Pemetaan pada Sub Menu Pengaturan - "Garis" Tak Bisa Mem-FIlter "Kategeri" maupun "Jenis".
Tombol2 utk menampilkan "Peta" Juga Hilang screenshot-nya di Gambar yang Tiga.....
Pada Screenshot yg ke "empat" tampilan salah satu jalan yg sudah dibuat peta-nya.

### Apa yang terjadi?

![image](https://user-images.githubusercontent.com/64481641/88470613-b45f3000-cf28-11ea-9e1f-7ad373378ce4.png)
![image](https://user-images.githubusercontent.com/64481641/88470619-bcb76b00-cf28-11ea-9dfd-80ce6af58432.png)
![image](https://user-images.githubusercontent.com/64481641/88470621-c3de7900-cf28-11ea-9358-05cc85ba20de.png)
![image](https://user-images.githubusercontent.com/64481641/88470622-ce007780-cf28-11ea-8f10-4744dff24638.png)

### Informasi tambahan 
Kamaren tidak dibawa ke issue takutnya saya, Krn saya pakai OpenSID offline, ternyata setelah saya buat Peta Area bisa tdk ada masalah apapun,  Saya coba ulang lg buat Peta Garis utk jalan hasilnya sama dgn yg pertama, baru yakin saya, bahwa kendelanya pada menu garis mohon solusinya.

Tambahan barusan ditemukan biar sekaligus laporannya :
![image](https://user-images.githubusercontent.com/64481641/88471310-4d467900-cf32-11ea-93cd-f480599b6c1a.png)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Masalah filter kategori/jenis sudah dicommit ke `master` melalui PR #3376. 

@Zulkarnaimni  Mengenai masalah lain, kalau masih bermasalah, mohon buatkan issue baru. Satu issue harap dibatasi satu masalah saja. Terima kasih.

**Comment by Zulkarnaimni** [comment]
Masalah ini sudah terselesaikan Pak Eddie Ridwan  bug antara peta garis dan menu pilih tampilan peta, nanti kalau ada temuan baru, saya buat ke issue baru,  Terima Kasih Pak Eddie Ridwan dan semua Tim OpenSID dan OpenDesa atas segala tanggapannya.
