### ISSUE TITLE
Menu Tertindih Peta

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#3378]
### Bagaimana alurnya sampai muncul masalah?
Seperti yang terlihat pada gambar berikut:

![peta](https://user-images.githubusercontent.com/46939846/88476524-2eaca600-cf63-11ea-954f-635d6f16e13e.png)

### Seperti apa yang diharapkan?
Normal tanpa terlihat menindih.

**Comment by fusionid** [comment]
Jika ingin membuka panel menu klik button tiga garis di atas (di samping tulisan OpenSID)

![panel_menu](https://user-images.githubusercontent.com/10391199/88545944-def2db00-d045-11ea-895d-2e4866992fb4.png)

**Comment by ariandii** [comment]
Sudah saya klik panel menu tersebut. klik berkali kali, open close menu. hasilnya sama pak.

![image](https://user-images.githubusercontent.com/46939846/88553485-87f20380-d04f-11ea-92ed-72ce364ce9e4.png)

**Comment by ariandii** [comment]
Sukses, setelah update OpenSID barusan, klik panel menu sudah tidak demikian.

Terima kasih.
