### ISSUE TITLE
Tombol Tambah Artikel Tidak Tersedia di [Tak Berkategori]

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#3381]
### Bagaimana alurnya sampai muncul masalah?
Pada web demo, layar di bawah ini tidak tersedia tombol tambah Artikel pada [tak berkategori]

![image](https://user-images.githubusercontent.com/46939846/88497549-ea64e880-cfea-11ea-9e0b-ef679c8bc88c.png)

### Seperti apa yang diharapkan?
Normal kembali

**Comment by afa28** [comment]
Sy cek veris lama mmang [Tidak Berkategori] dikhususkan untuk menampung artikel yg tdk memiliki kategori (baik itu kaetogrinya terhapus atau lainnya).
