### ISSUE TITLE
Saat menentukan wilayah maps eror 500

### ISSUE THREAD

**Issue by darkcurse** [OpenSID/OpenSID#3382]
### Bagaimana alurnya sampai muncul masalah?

Saat menentukan wilayah maps menggunakan draw polygons  terjadi eror 500

### Informasi tambahan 
![Untitled](https://user-images.githubusercontent.com/56758622/88501519-ea1e1a80-cff5-11ea-9496-fdd47166801c.jpg)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        |  7.2
| System operasi   | windows 10

**Comment by afa28** [comment]
Lakukan testing jg di situs demo, jika megalami masalah yg sma baru di laporkan. Jika hanya bermasalah pd aplikasi anda berarti aplikasi anda kurang lengkap, bisa cek struktur databasenya terlebih dahulu sesuai pesan  error yg diberikan.

**Comment by afa28** [comment]
Masalah ad pd struktur Database anda, silahkan perbaiki. Silahkn reopen issue ini jika masih terjadi masalah tdb. 🙏
