### ISSUE TITLE
Filter Wilayah Pada Statistik Bermasalah

### ISSUE THREAD

**Issue by afa28** [OpenSID/OpenSID#3384]
### Bagaimana alurnya sampai muncul masalah?
1. Buka salah satus statistik kependudukan (selain pendidikan dlm KK).
2. Lakukan Filter wilayah
3. Setelah memilih salah 1 dusun maka akan terjadi keraancuhan, krn statistik kependudukan yg dipilih sebelumnya akan dialihkan ke statistik kependudukan pendidikan dlm KK.

### Seperti apa yang diharapkan?
Filter sesuai wilayah dan statistik kependudukan yg terpilih

### Apa yang terjadi?
Tidak terjadi keraancuhan saat memilih wilayah

### Informasi tambahan 
https://demo.opensid.my.id/statistik/index/13

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.07-pasca
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3386
