### ISSUE TITLE
[Template Surat] Surat Pernyataan Jual Beli Tanah

### ISSUE THREAD

**Issue by kayangan** [OpenSID/OpenSID#3385]
Mohon Di Tambahkan Ke Sistem **Surat Pernyataan Jual Beli Tanah**
Berikut Saya Lamirkan Contoh Surat Yang Sudah Saya Buat/Saya Pakai

 1. Contoh Export Docnya:
[Export Doc Surat Pernyataan Jual Beli Tanah.pdf](https://github.com/OpenSID/OpenSID/files/4985896/Export.Doc.Surat.Pernyataan.Jual.Beli.Tanah.pdf)

 2. Master Suratnya
[surat_pernyataan_jual_beli_tanah.zip](https://github.com/OpenSID/OpenSID/files/4985909/surat_pernyataan_jual_beli_tanah.zip)

**Comment by wawan1985** [comment]
bagaimana cara menambahkan pada aplikasi opensid nya ya? sudah saya coba copy paste scriptnya lewat cpanel tetep tidak bisa

**Comment by kayangan** [comment]
Lakukan migrasi DB untuk melihat perubahan penambahan suratnya

**Comment by wawan1985** [comment]
untuk versi yang premium juga sama pak, harus migrasi DB, kebetulan saya sudah pakai yang premium

**Comment by kayangan** [comment]
Silahkan dicoba

**Comment by wawan1985** [comment]
tetap tidak bisa pak dengan cara migrasi DB, apakah ada cara lain pak untuk memasukan surat ini ke dalam aplikasi, karena saya sangat membutuhkannya

**Comment by kayangan** [comment]
Coba konsul ke masternya @rudi purwanto

**Comment by wawan1985** [comment]
siap pak, terimakasih

**Comment by andifahruddinakas** [comment]
> untuk versi yang premium juga sama pak, harus migrasi DB, kebetulan saya sudah pakai yang premium

Sudah disediakan tombol untuk memperbaharui daftar surat yang ditambahkan langsung ke folder desa di versi premium v22.04-premium.

![surat perbaharui](https://user-images.githubusercontent.com/57283157/162682119-76302672-0aa3-48e7-ad2d-3bc26d7c591a.png)

**Comment by 151194** [comment]
Gmna Cara Pasang nya Bang ??🙏
