### ISSUE TITLE
[Template Surat] Surat SPTJM Perkawinan/Perceraian Belum Tercatat

### ISSUE THREAD

**Issue by kayangan** [OpenSID/OpenSID#3387]
Mohon Di Tambahkan Surat Pernyataan Tanggung Jawab Mutlak Perkawinan/Perceraian Belum Tercatat

1.Contoh Export Doc
[Export Doc Surat SPTJM.pdf](https://github.com/OpenSID/OpenSID/files/4986164/Export.Doc.Surat.SPTJM.pdf)

2. Master Surat Yang Sudah Saya Pakai
[surat_sptjm_perkawinan_perceraian_belum_tercatat.zip](https://github.com/OpenSID/OpenSID/files/4986266/surat_sptjm_perkawinan_perceraian_belum_tercatat.zip)

**Comment by muhtar-coder** [comment]
Perlu di tambahkan penanda tangan kepala desa di bawah setiap surat

**Comment by muhtar-coder** [comment]
terima kasih @kayangan
