### ISSUE TITLE
[Template Surat] SPTJM Kebenaran Data Kelahiran Anak

### ISSUE THREAD

**Issue by kayangan** [OpenSID/OpenSID#3388]
Mohon Di Tambahkan SPTJM Kebenaran Data Kelahiran Anak 
Surat Ini di gunakan Untuk Anak yang tidak punya Buku Kelahiran Dari Bidan/Posyandu Untuk Penerbitan Akta Kelahiran

1. Mater Surat Yang Sudah Saya Pakai
[surat_pernyataan_tanggung_jawab_mutlak_sptjm_kebenaran_data_kelahiran.zip](https://github.com/OpenSID/OpenSID/files/4986188/surat_pernyataan_tanggung_jawab_mutlak_sptjm_kebenaran_data_kelahiran.zip)

2. Para Suhu Mohon Di Lengkapi Jika Kekurangannya

**Comment by Nurhidayat29** [comment]
silakan masukkn pr saja bung

**Comment by kayangan** [comment]
@Nurhidayat29 dipersilahkan master saya cuma bisa membuat issue saja
