### ISSUE TITLE
Gagal menampilkan halaman Dashboard Admin

### ISSUE THREAD

**Issue by roaddee** [OpenSID/OpenSID#3393]
### Bagaimana alurnya sampai muncul masalah?
Masalah ini terjadi pada sistem informasi Linux (saya menggunakan Ubuntu 18.04), yaitu ketika mencoba login admin tentunya dengan password yang sudah benar, tapi dashboard admin tidak bisa tampil, malah menampilkan pesan error 500 spt gambar di bawah ini :
![image](https://user-images.githubusercontent.com/45786885/88765303-79ffc800-d1a0-11ea-8369-7ffea9693086.png)

### Seperti apa yang diharapkan?
Bisa masuk ke dashboard admin dengan lancar

### Apa yang terjadi?
Ketika saya mencoba memberikan "comment" pada beberapa baris yang berfungsi untuk memberikan notifikasi update versi opensid di controller Home_sid, spt di bawah ini :
![image](https://user-images.githubusercontent.com/45786885/88764782-c0a0f280-d19f-11ea-8e33-f0bd42104929.png)
maka error 500 yang saya sebutkan di atas, tidak terjadi lagi dengan kata lain "kemungkinan" error disebabkan oleh fungsi pengecekan `has_internet_connection`

### Informasi tambahan 
tidak terjadi pada versi rilis 20.07, hanya terjadi pada versi 20.07-pasca

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.07-Pasca
| Versi PHP        |  7.2.32
| System operasi   | Linux Ubuntu 18.04

**Comment by afa28** [comment]
Bisa bantu pak @esyede ???

**Comment by esyede** [comment]
> Ketika saya mencoba memberikan "comment" pada beberapa baris yang berfungsi untuk memberikan notifikasi update versi opensid di controller Home_sid, spt di bawah ini :
> ![image](https://user-images.githubusercontent.com/45786885/88764782-c0a0f280-d19f-11ea-8e33-f0bd42104929.png)
> maka error 500 yang saya sebutkan di atas, tidak terjadi lagi dengan kata lain "kemungkinan" error disebabkan oleh fungsi pengecekan `has_internet_connection`

Umm, sepertinya setting `allow_url_fopen` di php.ini milik server pak @roaddee tidak aktif ya pak?

Tolong jalankan kode ini di server bapak buat cek:
```php
echo 'url fopen: '.(ini_get('allow_url_fopen') ? 'on' : 'off');
echo '<br>';
echo (function_exists('fsockopen') && is_callable('fsockopen')) ? 'fsockopen() ada' : 'fsockopen() tidak ada';
exit;
```
Nanti post hasilnya kesini ya pak. Saya tunggu

**Comment by esyede** [comment]
> Bisa bantu pak @esyede ???

Siapp

**Comment by eddieridwan** [comment]
@roaddee bisa juga lihat di laporan `Pengaturan > Info Sistem`

**Comment by roaddee** [comment]
baik pak @esyede saya cek nya, maaf telat.

**Comment by roaddee** [comment]
sudah on pak, setting di php.ini
![image](https://user-images.githubusercontent.com/45786885/88811884-4c873e80-d1e1-11ea-95f3-4940aa308636.png)

dan di informasi system juga on
![image](https://user-images.githubusercontent.com/45786885/88812045-7ccedd00-d1e1-11ea-920a-526c9cce0a5c.png)

**Comment by esyede** [comment]
> sudah on pak, setting di php.ini
> dan di informasi system juga on

Lho kok aneh ya?

Kalau begitu ubah method `cek_koneksi_internet()` sesuai dengan PR https://github.com/OpenSID/OpenSID/pull/3394 coba pak, bisa jalan atau tidak.

Mohon maaf ini saya ngerepotin.
Terimakasih pak.

**Comment by roaddee** [comment]
sudah saya ubah methodnya, tapi masih tetap pak @esyede

**Comment by esyede** [comment]
> sudah saya ubah methodnya, tapi masih tetap pak @esyede
> kalau misalnya tidak ada koneksi internet, seharusnya tetap bisa masuk ke dashboard kan pak ?

Iya pak. seharusnya tetap bisa.

Di folder `logs/` milik bapak ada error yang berhubungan dengan ini tidak pak?

**Comment by esyede** [comment]
Pak @afa28 dan pak @eddieridwan bisa tolong bantu cek juga di servernya?
Saya di local nggak nemu errornya, jadi susah mau trace

**Comment by afa28** [comment]
> Pak @afa28 dan pak @eddieridwan bisa tolong bantu cek juga di servernya?
> Saya di local nggak nemu errornya, jadi susah mau trace 

Yg jg offline 🤭

**Comment by esyede** [comment]
> Yg jg offline
:laughing:

**Comment by esyede** [comment]
Secure request saya coba matikan dulu (hanya untuk method `cek_koneksi_internet()`)
See: https://github.com/OpenSID/OpenSID/pull/3394/commits/3d4848b818bfdf16d0bd4fc5da084d8e52ced113
Pak @roaddee mohon bantuannya (lagi) nggih, untuk dicoba lagi perubahan ini. :pray: :pray:

**Comment by roaddee** [comment]
siap, saya coba nya. sebentar ya pak @esyede

**Comment by eddieridwan** [comment]
Karena masalah ini hanya ada di server ybs, mungkin utk mempercepat, bung @esyede bisa diberikan akses remote untuk mencoba langsung? Bagaimana, bung @roaddee ?

**Comment by roaddee** [comment]
bisa pak @eddieridwan , sebentar
saya buatkan port nya dan usernya. dan biar bisa diakses pakai putty

**Comment by roaddee** [comment]
akses putty :
host : 36.94.49.50
port : 3380
user : esyede
pass : Esyedeoke1

untuk mencoba nya (sdh saya git clone baru)
http://36.94.49.50:7180/opensid/index.php/siteman
user : admin
pass : Sid304304*

**Comment by esyede** [comment]
Oke pak

**Comment by esyede** [comment]
Ping pak @roaddee

**Comment by fusionid** [comment]
Update dulu OpenSID-nya sekarang namanya bukan `hom_sid` tetapi `identitas_desa`
Sebelumnya :
`http://36.94.49.50:7180/opensid/index.php/hom_sid`
Sekarang :
`http://36.94.49.50:7180/opensid/index.php/identitas_desa`

![identitas_desa-was-hom_sid](https://user-images.githubusercontent.com/10391199/88885720-3a4de480-d263-11ea-8625-41ecdcc160c4.PNG)

**Comment by fusionid** [comment]
@roaddee , mungkin perlu di-ON-kan opsi php di bawah ini :
enable_dl
expose_php
short_open_tag

**Comment by masumo** [comment]
pak @roaddee sudah cek folder **OpenSID/logs** ? saya dulu pernah alami HTTP ERROR 500, ketemu masalahnya di situ. di folder log ada file php yang isinya error logs per tanggal.

**Comment by eddieridwan** [comment]
Sebaiknya opsi `short_open_tag` tidak diaktifkan. Celah keamanan.

**Comment by roaddee** [comment]
@masumo di log tidak ada apa2 nya pak, alias kosong
tapi di log yang lama ada, tapi itu pun munculnya tadi.

@esyede , akun itu akun sudo pak, bapak kalau butuh administrator right, tinggal pakai sudo pak

**Comment by esyede** [comment]
> @esyede , akun itu akun sudo pak, bapak kalau butuh administrator right, tinggal pakai sudo pak
Oh, oke pak, saya coba lagi. Saya tadi akses via winscp soalnya :smiley:

**Comment by fusionid** [comment]
> @masumo di log tidak ada apa2 nya pak, alias kosong
> tapi di log yang lama ada, tapi itu pun munculnya tadi.
> 
> @esyede , akun itu akun sudo pak, bapak kalau butuh administrator right, tinggal pakai sudo pak
> dan untuk enable_dl saya on kan, expose_php sudah on default

Masih off enable_dl dan expose_php nya
![opsi_php](https://user-images.githubusercontent.com/10391199/88890397-c6fca080-d26b-11ea-97bf-4faa0ea68cfb.PNG)

**Comment by roaddee** [comment]
![image](https://user-images.githubusercontent.com/45786885/88890988-99fcbd80-d26c-11ea-9770-320a7e476020.png)
sudah on

**Comment by roaddee** [comment]
> > @esyede , akun itu akun sudo pak, bapak kalau butuh administrator right, tinggal pakai sudo pak
> > Oh, oke pak, saya coba lagi. Saya tadi akses via winscp soalnya 😃

saya kalau winscp saya juga tidak tahu cara memberikan sudo nya (sudah saya ikuti sesuai yang di forum, tetap tidak bisa), akhirnya tetap pakai CLI saya pak, pakai Nano

**Comment by fusionid** [comment]
@roaddee Sudah OK
![Screen Shot 07-30-20 at 01 57 PM](https://user-images.githubusercontent.com/10391199/88891588-a6cde100-d26d-11ea-9db8-03eb823636a7.PNG)

**Comment by esyede** [comment]
> saya kalau winscp saya juga tidak tahu cara memberikan sudo nya (sudah saya ikuti sesuai yang di forum, tetap tidak bisa), akhirnya tetap pakai CLI saya pak, pakai Nano

Memang tidak ada fitur sudonya  di winscp pak

**Comment by roaddee** [comment]
@fusionid , jadi hanya masalah enable_dl dan expose_php ?
mantap master

**Comment by esyede** [comment]
> @roaddee Sudah OK
> ![Screen Shot 07-30-20 at 01 57 PM](https://user-images.githubusercontent.com/10391199/88891588-a6cde100-d26d-11ea-9db8-03eb823636a7.PNG)

Saya baru mau bilang pak Hahaha.

Tapi ngomong2 di logsnya ada yang aneh lho pak @roaddee 

Ini isi lognya
````
<?php defined('BASEPATH') OR exit('No direct script access allowed'); ?>

ERROR - 2020-07-30 13:56:40 --> Severity: Core Warning --> Module 'mbstring' already loaded Unknown 0
ERROR - 2020-07-30 13:56:50 --> Severity: Core Warning --> Module 'mbstring' already loaded Unknown 0
ERROR - 2020-07-30 13:56:51 --> Severity: Core Warning --> Module 'mbstring' already loaded Unknown 0
ERROR - 2020-07-30 13:56:52 --> Severity: Core Warning --> Module 'mbstring' already loaded Unknown 0
ERROR - 2020-07-30 13:56:56 --> Severity: Core Warning --> Module 'mbstring' already loaded Unknown 0
ERROR - 2020-07-30 13:57:01 --> Severity: Core Warning --> Module 'mbstring' already loaded Unknown 0
ERROR - 2020-07-30 13:57:01 --> Severity: Core Warning --> Module 'mbstring' already loaded Unknown 0
ERROR - 2020-07-30 13:57:06 --> Severity: Core Warning --> Module 'mbstring' already loaded Unknown 0
ERROR - 2020-07-30 13:57:06 --> Severity: Core Warning --> Module 'mbstring' already loaded Unknown 0
ERROR - 2020-07-30 13:57:13 --> Severity: Core Warning --> Module 'mbstring' already loaded Unknown 0
ERROR - 2020-07-30 13:57:44 --> Severity: Core Warning --> Module 'mbstring' already loaded Unknown 0
ERROR - 2020-07-30 13:57:54 --> Severity: Core Warning --> Module 'mbstring' already loaded Unknown 0
ERROR - 2020-07-30 13:58:14 --> Severity: Core Warning --> Module 'mbstring' already loaded Unknown 0
ERROR - 2020-07-30 13:58:24 --> Severity: Core Warning --> Module 'mbstring' already loaded Unknown 0
ERROR - 2020-07-30 13:58:52 --> Severity: Core Warning --> Module 'mbstring' already loaded Unknown 0
ERROR - 2020-07-30 13:58:54 --> Severity: Core Warning --> Module 'mbstring' already loaded Unknown 0
ERROR - 2020-07-30 13:58:54 --> Severity: Core Warning --> Module 'mbstring' already loaded Unknown 0
ERROR - 2020-07-30 13:59:22 --> Severity: Core Warning --> Module 'mbstring' already loaded Unknown 0
ERROR - 2020-07-30 13:59:22 --> Severity: Core Warning --> Module 'mbstring' already loaded Unknown 0
ERROR - 2020-07-30 13:59:22 --> Severity: Core Warning --> Module 'mbstring' already loaded Unknown 0
ERROR - 2020-07-30 13:59:23 --> Severity: Core Warning --> Module 'mbstring' already loaded Unknown 0
ERROR - 2020-07-30 13:59:32 --> Severity: Core Warning --> Module 'mbstring' already loaded Unknown 0
ERROR - 2020-07-30 14:00:02 --> Severity: Core Warning --> Module 'mbstring' already loaded Unknown 0
ERROR - 2020-07-30 14:00:04 --> Severity: Core Warning --> Module 'mbstring' already loaded Unknown 0
ERROR - 2020-07-30 14:00:04 --> Severity: Core Warning --> Module 'mbstring' already loaded Unknown 0
ERROR - 2020-07-30 14:00:24 --> Severity: Core Warning --> Module 'mbstring' already loaded Unknown 0
ERROR - 2020-07-30 14:00:32 --> Severity: Core Warning --> Module 'mbstring' already loaded Unknown 0
ERROR - 2020-07-30 14:00:42 --> Severity: Core Warning --> Module 'mbstring' already loaded Unknown 0
ERROR - 2020-07-30 14:00:52 --> Severity: Core Warning --> Module 'mbstring' already loaded Unknown 0
ERROR - 2020-07-30 14:01:01 --> Severity: Core Warning --> Module 'mbstring' already loaded Unknown 0
ERROR - 2020-07-30 14:01:32 --> Severity: Core Warning --> Module 'mbstring' already loaded Unknown 0
ERROR - 2020-07-30 14:01:42 --> Severity: Core Warning --> Module 'mbstring' already loaded Unknown 0
ERROR - 2020-07-30 14:02:02 --> Severity: Core Warning --> Module 'mbstring' already loaded Unknown 0
ERROR - 2020-07-30 14:02:14 --> Severity: Core Warning --> Module 'mbstring' already loaded Unknown 0
ERROR - 2020-07-30 14:03:32 --> Severity: Core Warning --> Module 'mbstring' already loaded Unknown 0
ERROR - 2020-07-30 14:03:52 --> Severity: Core Warning --> Module 'mbstring' already loaded Unknown 0
ERROR - 2020-07-30 14:03:52 --> Severity: Core Warning --> Module 'mbstring' already loaded Unknown 0
ERROR - 2020-07-30 14:03:52 --> Severity: Core Warning --> Module 'mbstring' already loaded Unknown 0
ERROR - 2020-07-30 14:04:22 --> Severity: Core Warning --> Module 'mbstring' already loaded Unknown 0

````

**Comment by roaddee** [comment]
@esyede iya, saya tadi menghapus comment ; di mbstring, ternyata sudah terpanggil, saya coba comment nya lagi

**Comment by esyede** [comment]
> @fusionid , jadi hanya masalah enable_dl dan expose_php ?
> mantap master

Hak akses file masih `root:root` pak, musti di chown ke www-data.
`expose_php` di non-aktifkan saja pak

**Comment by esyede** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/10582583/88892152-8e11fb00-d26e-11ea-94f1-a827acecb910.png)

**Comment by esyede** [comment]
Oh iya, saya install tiny file manager di http://36.94.49.50:7180/opensid/dapur pak.
Hapus saja kalau tidak perlu

**Comment by fusionid** [comment]
> @fusionid , jadi hanya masalah enable_dl dan expose_php ?
> mantap master

Lebih baik dan wajib di upgrade saja versi PHP-nya, opsi dynamic loading (enable_dl) sudah deprecated karena ada celah security karena mem-bypass semua restriction di open-basedir

**Comment by roaddee** [comment]
oke pak @esyede , @fusionid , @afa28 , @eddieridwan , @masumo 
terima kasih bantuannya ....
berarti ini issue nya saya hapus, karena sudah uoke

@fusionid , saya pakai 7.2 karena saya samakan dengan demo
btw saya akan coba naikkna ke 7.3 dulu

**Comment by esyede** [comment]
Oke, silahkan pak

**Comment by fusionid** [comment]
> oke pak @esyede , @fusionid , @afa28 , @eddieridwan , @masumo
> terima kasih bantuannya ....
> berarti ini issue nya saya tutup, karena sudah uoke
> 
> @fusionid , saya pakai 7.2 karena saya samakan dengan demo
> btw saya akan coba naikkan ke 7.3 dulu

@roaddee, Langsung saja ke 7.4.x, semua fitur di OpenSID sudah kompatibel dengan 7.4.x

**Comment by roaddee** [comment]
@fusionid , iya tah pak ?, saya terlanjur katakan kalau masih 7.2 ke teman2 desa
karena permasalahan kemarin RFM yang di 7.3 terkadang keluar access denied,
kalau begitu, saya ralat nya saja, bahwa php 7.4 sudah bisa digunakan di opensid, sekalian rilis besok.

**Comment by fusionid** [comment]
> @fusionid , iya tah pak ?, saya terlanjur katakan kalau masih 7.2 ke teman2 desa
> karena permasalahan kemarin RFM yang di 7.3 terkadang keluar access denied,
> kalau begitu, saya ralat nya saja, bahwa php 7.4 sudah bisa digunakan di opensid, sekalian rilis besok.

RFM dan TinyMCE beserta plug-in nya sudah diupgrade untuk mengejar kompatibilitas PHP 7.4.x.
Kalau sekarang keluar access denied di RFM, itu karena ada perubahan generate RFM key, sekarang key akan di generate ketika login berdasarkan user, jadi harus logout dan login lagi untuk generate key baru jika ada username sama dan login bersamaan.

**Comment by esyede** [comment]
Pak @roaddee ngomong2, folder di `var/www/html/opensid/dapur/` segera dihapus pak.
Saya masih bisa login soalnya. Takutnya lupa ndak dihapus.

![bbbbbb](https://user-images.githubusercontent.com/10582583/88895764-1b574e80-d273-11ea-9442-8c499a1f60d8.png)

**Comment by roaddee** [comment]
@fusionid , siap

@esyede , oke siap

**Comment by roaddee** [comment]
@fusionid 
langsung upgrade :
![image](https://user-images.githubusercontent.com/45786885/88897323-48a4fc00-d275-11ea-8587-db45cb7ebe45.png)

@esyede 
dapur sudah saya hapus
![image](https://user-images.githubusercontent.com/45786885/88897402-62deda00-d275-11ea-89d4-cfea36c747ab.png)

**Comment by fusionid** [comment]
@roaddee, Mantap tidak tanggung2 langsung ke 7.4.8 (untuk pemakaian lokal tambah sedikit jadi PHP 8.0 Alpha)
Apakah ada fitur2 OpenSID yg terkendala dgn 7.4.8? Mudah2an tidak ada.

**Comment by roaddee** [comment]
@fusionid , mudah2an tidak ada gangguan, hahahah
untuk PHP 8, saya coba pasangnya, rusak, tinggal reset lagi vps nya. hahahah

**Comment by roaddee** [comment]
mas @esyede dan mas @ericksuryadinata bisa menghubungi saya di roaddee@gmail.com ?

**Comment by af-lazuardi** [comment]
mantap ini, aku juga punya problem yang sama. tak cobanya dulu solusi2 yang ada di sini

**Comment by eddieridwan** [comment]
Setelah menemukan solusinya, sebaiknya didokumentasikan di panduan.

**Comment by roaddee** [comment]
saya masih menunggu masalah yg sama yg dialami pak syafri pak, kalau sama sekalian saya buat kalimat nya biar enak
