### ISSUE TITLE
Perlu Perbaikan Form Isian data Ibu Kandung Tidak Terdata Pada Surat Keterangan Lahir

### ISSUE THREAD

**Issue by muhtar-coder** [OpenSID/OpenSID#3395]
### Bagaimana alurnya sampai muncul masalah?
Saat membuat surat keterangan lahir dengan data ibu kandung tidak terdata atau luar desa atau beda KK, maka tidak bisa cetak atau exsport doc

### Seperti apa yang diharapkan?

bisa cetak seperti pada umumnya ketika menggunakan data ibu kandung tidak terdata atau luar desa atau beda kk.
### Apa yang terjadi?
pembuatan surat keterangan lahir dapat berjalan cepat dan normal tanpa bongkar pasang data kartu keluarga

### Informasi tambahan 

![image](https://user-images.githubusercontent.com/55665526/88819774-a2acaf80-d1ea-11ea-879c-bd9e7d0c7c5c.png)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 7.2
| System operasi   |

**Comment by pandigresik** [comment]
sepertinya ini sama dengan issue #3373 , mungkin bisa diclose juga

**Comment by afa28** [comment]
Sdah di master. Jika tdk sesuai issue bisa di reopen.
