### ISSUE TITLE
Rumah Tangga Error

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#3399]
### Bagaimana alurnya sampai muncul masalah?
ketika klik 
1. Rincian Anggota Rumah Tangga
2. Jumlah Anggota
3. Tambah Anggota
4. mengubah Nomor Rumah Tangga 
terjadi error
![eroor](https://user-images.githubusercontent.com/25834335/88880311-fbb62b00-d25e-11ea-8bf1-73d6c8c87ef7.png)

### Seperti apa yang diharapkan?
berjalan seperti versi sebelumnya

### Apa yang terjadi?
tidak bisa melihat rincian anggota, tidak bisa menambah anggota Rumah Tangga

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master`.
