### ISSUE TITLE
[Bug] Duplicate Data Pada Modul Rumah Tangga

### ISSUE THREAD

**Issue by afa28** [OpenSID/OpenSID#3400]
### Bagaimana alurnya sampai muncul masalah?
1. Masuk ke modul Rumah Tangga
2. Tambah Rumah Tangga dan Anggota RT nya (min 1 anggota)
3. Masuk ke daftar anggota RT dan ubah Hubungan RT tsb menjadi kepala RT.
4. Kembali ke daftar RT, maka akan terlihat duplikasi data RT.

### Seperti apa yang diharapkan?
Tidak terjadi duplikasi data RT setelah menggati kepala RT, Sediakan kolom untuk menampilkan status pd RT (Kepala RT, Anggota)

### Apa yang terjadi?
Data valid

### Informasi tambahan 
![2222](https://user-images.githubusercontent.com/57283157/88883214-f3a9bb80-d25d-11ea-8f66-4e1c24983e9e.JPG)

![1111](https://user-images.githubusercontent.com/57283157/88883215-f7d5d900-d25d-11ea-9b6c-8745ac31f576.JPG)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3425
