### ISSUE TITLE
Dokumentasi Setelah Melakukan Update Ke Versi Terbaru

### ISSUE THREAD

**Issue by afa28** [OpenSID/OpenSID#3401]
### Bagaimana alurnya sampai muncul masalah?
Saat ini belum ada dokumentasi yg diperlu dilakukan oleh desa jika melakukan update yg dmna system OpenSID tdk bisa jangkau. Contoh : perubahan template surat pd system OpenSID yg perlu disesuaikan ulang oleh tiap desa setelah update dan migraasi.

Saat ini hanya ada dokumentasi cara update scr umum, namu scr khusus seperti yg harus dilakukan pd folder desa tdk disediakan.

### Seperti apa yang diharapkan?
Perlu ditambahkan catatan/dokumentasi yg perlu dilakukan desa setiap melakukan update, bisa mencotoh cara yg dilakukan CI3 agar dokumentasinya jelas.

https://www.codeigniter.com/userguide3/installation/upgrading.html

### Apa yang terjadi?
Pengguna OpenSID tdk kebingunan saat menggunakan versi terbaru.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by roaddee** [comment]
### Melakukan Upgrade dari v20.07 ke v20.08

Untuk melakukan upgrade, yang perlu anda lakukan adalah :

**Langkah 1**: Bakcup Folder Desa dan Backup Database
Untuk melakukan langkah tersebut, bisa dilakukan dari menu Pengaturan Database

**Langkah 2**: Update File-file Aplikasi OpenSID
Timpa seluruh file yang ada di dalam folder dimana kode-kode aplikasi OPENSID berada

**Langkah 3**: Jalankan Migrasi Database
Dilakukan melalui menu Penagaturan Database - Migrasi DB - Migrasi DB

**Langkah 4**: Update Folder **`template-surat`**
Dikarenakan ada penyesuaian pada kode-kode yang berhubungan dengan surat, maka perlu melakukan update folder `template-surat` dengan cara menimpa folder `template-surat` dari folder dimana aplikasi OPENSID berada ke dalam folder DESA

**Comment by roaddee** [comment]
seperti di atas pak @eddieridwan dan bung @afa28 ?

**Comment by afa28** [comment]
> seperti di atas pak @eddieridwan dan bung @afa28 ?

Iyu scr umum pak klw menggunakan template bawaan. Misal ad yg menambah/memodifikasi template bawaan, mungkin bisa dijelaskan bagian/baris source mana yg perlu diubah.

**Comment by roaddee** [comment]
sudah saya edit, @afa28

**Comment by afa28** [comment]
Sdah dipidahkan ke https://github.com/OpenSID/OpenSID/wiki/Penyesuaian-folder-desa-setelah-update
