### ISSUE TITLE
[Template Surat] Pada surat keterangan pindah datang WNI perlu dilakukan perubahan

### ISSUE THREAD

**Issue by rensingbat** [OpenSID/OpenSID#3402]
Perubahan pada penanda tangan surat ket. Pindah datang WNI PdF, mengetahui camat di ganti a.n.

### Bagaimana alurnya sampai muncul masalah?
Kadang camat tidak berada di tempat

### Seperti apa yang diharapkan?
Perlu penambahan atas nama (a.n.)

### Apa yang terjadi?
Memudahkan masyarakat dan mempercepat pengurusan di kantor camat

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
> Perubahan pada penanda tangan surat ket. Pindah datang WNI PdF, mengetahui camat di ganti a.n.
> 
> ### Bagaimana alurnya sampai muncul masalah?
> Kadang camat tidak berada di tempat
> 
> ### Seperti apa yang diharapkan?
> Perlu penambahan atas nama (a.n.)
> 
> ### Apa yang terjadi?
> Memudahkan masyarakat dan mempercepat pengurusan di kantor camat
> 
> ### Informasi tambahan
> Tanya	Jawab
> Versi OpenSID	2.x
> Versi PHP	
> System operasi

Silahkan hapus sja nama camat yg ada di identitas desa agar penanda tangan camat tdk ditampilkan di lampiran.

**Comment by rensingbat** [comment]
Trims infonya

Pada tanggal Kam, 6 Agt 2020 18:21, Andi Fahruddin Akas <
notifications@github.com> menulis:
