### ISSUE TITLE
[Surat] Tambahan Tembusan pada Layanan Surat untuk TTD selain Pimpinan

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#3403]
### Bagaimana alurnya sampai muncul masalah?
Saat ini pada bagian bawah cetak surat layanan kepada penduduk, tidak terdapat Tembusan setiap kali cetak untuk Penandatangan selain Kepala Desa.

### Seperti apa yang diharapkan?
Saat membuat Layanan Surat untuk penduduk yang bertanda tangan **"selain"** Kepala Desa, diharapkan pada bagian bawah surat muncul kalimat sebagai berikut:

Tembusan :
1. Yth. Kepala [sebutandesa] [nama_desa]
2. Arsip

### Apa yang terjadi?
Agar setiap surat yang keluar dari Desa yang ditanda tangani selain Kepala Desa terdapat Baris Tembusan tersebut secara otomatis.

**Comment by andifahruddinakas** [comment]
Pak @ariandii, issue ini masih diperlukan.

**Comment by andifahruddinakas** [comment]
Pak @ariandii, ini sudah bisa dilakukan melalui tinymce. Jika ada kekurangan bisa dibuat dan dijelaskan di issue terpisah.
