### ISSUE TITLE
Penyesuaian Istilah Baru tentng COVID-19

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#3404]
### Bagaimana alurnya sampai muncul masalah?
Istilah ODP, PDP, dan suspect kini telah diganti menjadi kasus suspek, probable, dan konfirmasi. Umumnya istilah tersebut akan didapatkan ketika pemerintah terus melakukan pelacakan (tracking) di setiap wilayah. Namun, pastikan Anda juga selalu senantiasa aktif memeriksakan diri dan melaporkan apabila mengalami gejala coronavirus. 

### Seperti apa yang diharapkan?
Sumber https://www.sehatq.com/artikel/mengenal-istilah-kasus-suspek-probable-dan-konfirmasi-pengganti-odp-pdp-dan-otg-kasus-virus-corona

**Comment by agungsugiarto** [comment]
Sudah di perbaiki melalui pr https://github.com/OpenSID/premium/pull/437
