### ISSUE TITLE
Tampilan Slider tidak Mengikuti Status Aktif/Tidak nya Gambar

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#3405]
### Bagaimana alurnya sampai muncul masalah?
Saat Menu Slider dipilih untuk Gambar dalam album galeri yang dimasukkan ke slider, maka seluruh gambar pada gallery yang diaktifkan sebagai slider akan tampil tanpa terkecuali.

![image](https://user-images.githubusercontent.com/46939846/88943189-5f6b4300-d2b5-11ea-9702-5e0c6468a821.png)

Status Terkunci, tetap tampil di slider pada halaman website.

![image](https://user-images.githubusercontent.com/46939846/88943107-45c9fb80-d2b5-11ea-8dc7-1a5aed8201df.png)

Ini juga terkunci juga tetap tampil di slider pada halaman website.

![image](https://user-images.githubusercontent.com/46939846/88943154-52e6ea80-d2b5-11ea-9f15-6bd413a2a0bd.png)

### Seperti apa yang diharapkan?
Gambar yang muncul pada Slider di halaman website mengikuti status aktif/tidaknya pada pengaturan tersebut,

### Apa yang terjadi?
Agar mudah dipilih mana yang perlu dimunculkan dan yang tidak sesuai pengaturan kunci.

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master`.
