### ISSUE TITLE
menyematkan artikel google drive tampilan responsive pada tema hadakewa kaco

### ISSUE THREAD

**Issue by yudhaputra555** [OpenSID/OpenSID#3408]
### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
Siapa tau berguna, coba sebelum `<iframe` tambahkan `<div class="table-responsive">` dan jgn lupa tutup `</div>`

**Comment by afa28** [comment]
Silahkan ikuti arahan ini :

> Siapa tau berguna, coba sebelum `<iframe` tambahkan `<div class="table-responsive">` dan jgn lupa tutup `</div>`

Jika masih menemukan masalah, silahkan buat issue dgn isi yg jelas. Ikuti format tempalate issue yg disediakan. Trims

**Comment by yudhaputra555** [comment]
terimakasih,

Pada tanggal Min, 2 Agu 2020 10.47, Andi Fahruddin Akas <
notifications@github.com> menulis:
