### ISSUE TITLE
Salah Masuk Menu

### ISSUE THREAD

**Issue by Zulkarnaimni** [OpenSID/OpenSID#3409]
### Bagaimana alurnya sampai muncul masalah?
![image](https://user-images.githubusercontent.com/64481641/89114960-33fe7900-d4ac-11ea-90d0-6012a7aa697e.png)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
> ### Bagaimana alurnya sampai muncul masalah?
> ![image](https://user-images.githubusercontent.com/64481641/89114960-33fe7900-d4ac-11ea-90d0-6012a7aa697e.png)
> 
> ### Seperti apa yang diharapkan?
> ### Apa yang terjadi?
> ### Informasi tambahan
> Tanya	Jawab
> Versi OpenSID	2.x
> Versi PHP	
> System operasi

Tolong informasinya diperjelas lg, ikuti format template yg disediakan. Jika issue masih tdk jelas kemungkinan tdk ada yg akan krjakn. Trims

**Comment by Zulkarnaimni** [comment]
Menu Bantuan kalau dibuka atau di klik masuk  ke menu Laporan Statistik Penduduk, bukan ke Bantuannya, screenshotnya terlampir.....

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3412
