### ISSUE TITLE
Lengkapi struktur HTML tags isi widget dinamis pada waktu disimpan

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#3411]
### Bagaimana alurnya sampai muncul masalah?

1. Buat widget dinamis. Isi dengan HTML tags yg tidak lengkap, misalnya ada `<div>` tetapi tidak ada tag penutup `</div>`.
2. Simpan.
3. Tampilikan di web. 
4. Terlihat tampilan akan rusak.

### Seperti apa yang diharapkan?
Tampilan. tidak rusak oleh HTML tags yg tidak lengkap di isi widget dinamis.
Lengkapi dulu sebelum isi widget dinamis disimpan.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | v20.08
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master`

**Comment by afa28** [comment]
Kyaknya jg perlu dokumentasi exktention yg perlu di aktifkan

**Comment by eddieridwan** [comment]
Dokumentasi extention ada di https://github.com/OpenSID/OpenSID/wiki/Tanya-Jawab-Install-dan-Update, tapi perlu dimutakhirkan dan disalin ke https://github.com/OpenSID/OpenSID/wiki/Persiapan-Install-OpenSID. 

Selain itu sebaiknya issue ini https://github.com/OpenSID/OpenSID/issues/2434 diterapkan secepatnya. Sdh diprioritaskan.
