### ISSUE TITLE
Pengambilan data referensi statistik terdapat di 2 tempat

### ISSUE THREAD

**Issue by afa28** [OpenSID/OpenSID#3414]
### Bagaimana alurnya sampai muncul masalah?
Saat ini terdapat 2 tempat referensi utuk statistik, yakni di laporan_penduduk_model.php (untuk menu dan statistik) dan referensi_model.php (untuk peta/gis). Sehingga  jika ada penambahan statitistik baru perlu dilakukan penyesuian pd kedua referensi tsb.

### Seperti apa yang diharapkan?
Hanya menggunakan 1 referensi sja.

### Apa yang terjadi?
Tdk perlu lg melakukan penyesuaian di 2 tempat.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3430
