### ISSUE TITLE
[Bantuan] Tambah Peserta Bantuan Duplicate

### ISSUE THREAD

**Issue by afa28** [OpenSID/OpenSID#3417]
### Bagaimana alurnya sampai muncul masalah?
Tambah program bantuan dengan nik/no_kk yg kosong(0), maka semua nik/no_kk yg kosong tsb akan ditambahkan semua.

### Seperti apa yang diharapkan?
Tdk terjadi duplicate data jika menggunakan nik/no_kk yg kosong

### Apa yang terjadi?
Tdk duplicate

### Informasi tambahan 
Issue dr Group FB (agar tdk tenggelam)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
pak @eddieridwan , jd ini fix pakai parameter id bukan lg pakai nik/no_kk, no_kk(no_rtm) ??? untuk sasarn kelompok (4) sdah pakai id.

**Comment by afa28** [comment]
Untuk issue ini mungkin agak berat, karena :
1. Model program_bantuan yg terlalu rumit untuk dipahami.
2. Banyak komponen dan modul yg terkait program_bantuan yg jg perlu diperbaiki (website: layanan_mandiri, program_bantuan, dll) - (admin : penduduk, keluarga, rtm, program_bantuan, statistik, dll).

**Comment by afa28** [comment]
https://github.com/OpenSID/OpenSID/tree/program-bantuan

**Comment by eddieridwan** [comment]
Bung @afa28 , apakah branch `program-bantuan` siap untuk dikirim sebagai pull request? Apa status branch ini?

**Comment by afa28** [comment]
> Bung @afa28 , apakah branch `program-bantuan` siap untuk dikirim sebagai pull request? Apa status branch ini?

Blum pak, masih banyak yg perlu diperbaiki.

**Comment by balongbesuk** [comment]
Sebaiknya di skip saja, kewajiban desa untuk melengkapi data kk 0,  atau bikin pop up peringatan nik kk tidak boleh 0

**Comment by afa28** [comment]
Kalau yg ini perlu banyak perombakan pak @eddieridwan, mulai dari modul program bantuan itu sendiri maupun modul yg menggunakan data program bantuan (penduduk, rtm, kelompok, statistik admin, statistik web, layanan mandiri bantuan, dll)

**Comment by eddieridwan** [comment]
@afa28 , ok, saya akan pelajari dulu.

**Comment by eddieridwan** [comment]
@afa28 di `rilis-dev` v21.08-premium`, penduduk dengan NIK nol tidak dapat ditambah, tetapi sepertinya tidak secara sengaja.

Sebaiknya dibuatkan issue terpisah untuk refaktor program bantuan sasaran penduduk supaya menggunakan id penduduk. Tetapi seperti anda katakan, akan merupakan pekerjaan yg perlu dilakukan berhati-hati.

Solusi sementara yg dapat diterapkan sebagai berikut:

- [ ] Ubah penggunaan NIK belum dimiliki dari nilai nol menjadi format NIK dengan angka awalan `0[kode-desa-10-digit]`. NIK dengan format ini dianggap sebagai NIK sementara menunjukkan belum ada NIK sebenarnya. 
- [ ] Sediakan migrasi untuk mengubah semua NIK nol supaya menggunakan format dengan awalan `0[kode-desa-10-digit]`. Beri nomor urut otomatis untuk menghasilkan NIK 16 digit. Contoh hasilkan NIK `0620102201600123`
- [ ] Pada form penduduk, sediakan pilihan atau kotak centang `Belum memiliki NIK`. Otomatis isi dengan NIK sementara dengan awalan `99999` dan nomor urut berikutnya untuk menghasilkan NIK 16 digit. Contoh hasilkan NIK `0620102201600789`
- [ ] Di daftar penduduk sediakan filter untuk menampilkan semua penduduk dengan NIK sementara (mulai dengan `0[kode-desa-10-digit]`).
- [ ] Di form penduduk, nilai NIK sementara tidak dapat diubah

Dengan  strategi ini, semua masalah NIK nilai 0 akan terhindar. Dan memudahkan pencarian penduduk dengan NIK sementara. Alasan menggunakan kode desa sebagai bagian dari NIK sementara supaya tidak akan ada duplikat dengan desa lain, seperti di OpenDK.

**Comment by ai-skematik** [comment]
saran nik sementara jangan ditampilkan saat cetak dokumen seperti surat atau salinan keluarga.,

**Comment by afa28** [comment]
Solusi sementara yg dapat diterapkan sebagai berikut:

- [ ] Sediakan migrasi mengubah kolom `tweb_penduduk.nik` menjadi varchar, supaya bisa diberi awalan '0'.
- [ ] Ubah penggunaan NIK belum dimiliki dari nilai nol menjadi format NIK dengan angka awalan `0[kode-desa-10-digit]`. NIK dengan digit pertama nol dianggap sebagai NIK sementara menunjukkan belum ada NIK sebenarnya. 
- [ ] Sediakan migrasi untuk mengubah semua NIK nol supaya menggunakan format dengan awalan `0[kode-desa-10-digit]`. Beri nomor urut otomatis untuk menghasilkan NIK 16 digit. Contoh hasilkan NIK `0620102201600123`
- [ ] Pada form penduduk, sediakan kotak centang `Belum memiliki NIK`. Kalau dicentang, otomatis isi dengan NIK sementara dengan awalan `0[kode-desa-10-digit]` dan nomor urut berikutnya untuk menghasilkan NIK 16 digit. Contoh hasilkan NIK `0620102201600789`
- [ ] Di daftar penduduk sediakan filter untuk menampilkan semua penduduk dengan NIK sementara (mulai dengan `0`).
- [ ] Di form penduduk, nilai NIK sementara tidak dapat diubah
- [ ] Di form penduduk, kalau kotak centang `Belum memiliki NIK` dihapus centangnya, maka kolom NIK dikosongkan dan bisa diisi, dan dianggap sebagai NIK sebenarnya, tidak lagi sementara. NIK sebenarnya tidak boleh mulai dengan digit 0.
- [ ] Di cetak dokumen seperti surat atau salinan kartu keluarga, tampilkan NIK sementara sebagai  0.

**Comment by afa28** [comment]
5 digit terakir = [0] + id

**Comment by eddieridwan** [comment]
Sdh dicommit ke `bug-fix` melalui https://github.com/OpenSID/premium/pull/345
