### ISSUE TITLE
Foto warga widget layanan mandiri tdk tampil

### ISSUE THREAD

**Issue by afa28** [OpenSID/OpenSID#3418]
### Bagaimana alurnya sampai muncul masalah?
1. Login layanan mandiri lewat widget.
2. Setelah logi data akan ditampilkan pd widget layanan mandiri
3. Pd bagian gambar/foto warga tdk tampil

### Seperti apa yang diharapkan?
Foto warga pd widget ditapilkan jika tersedia

### Apa yang terjadi?
Foto warga tdk blank

### Informasi tambahan 
Issue dr Group FB (agar tdk tenggelam)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by ariandii** [comment]
Saya coba login Widget Layanan Mandiri, foto warga sudah tampil di sisi kiri atas.

**Comment by afa28** [comment]
> Saya coba login Widget Layanan Mandiri, foto warga sudah tampil di sisi kiri atas.

Mungkin yg dimaksud yg ada di widget.
