### ISSUE TITLE
halaman hom minta di refresh

### ISSUE THREAD

**Issue by afri18** [OpenSID/OpenSID#3419]
### Bagaimana alurnya sampai muncul masalah?
saat login 
![image](https://user-images.githubusercontent.com/6611881/89142703-5bb81480-d572-11ea-8dc2-b69c12aa5604.png)

### Seperti apa yang diharapkan?
halaman hom muncul

### Apa yang terjadi?
tidak bisa akses ke halaman hom

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.08
| Versi PHP        | 7.2
| System operasi   | cpanel

**Comment by afa28** [comment]
> ### Bagaimana alurnya sampai muncul masalah?
> saat login
> ![image](https://user-images.githubusercontent.com/6611881/89142703-5bb81480-d572-11ea-8dc2-b69c12aa5604.png)
> 
> ### Seperti apa yang diharapkan?
> halaman hom muncul
> 
> ### Apa yang terjadi?
> tidak bisa akses ke halaman hom
> 
> ### Informasi tambahan
> Tanya	Jawab
> Versi OpenSID	20.08
> Versi PHP	7.2
> System operasi	cpanel

Coba ganti home jadi identitas_desa pak. Klw bisa, berarti kasusnya sama dengan pak @roaddee .

**Comment by roaddee** [comment]
kalau di refresh bisa ? pak @afri18 ?

**Comment by esyede** [comment]
@afri18 ada info error tidak pak di folder `logs/`?
Kalau ada tolong di posting kesini. atau coba aktifkan ekstensi `curl` di file `php.ini`

Error yang muncul itu sepertinya fatal error karena ekstensi `curl` belum diaktifkan. datangnya baris ini:
https://github.com/OpenSID/OpenSID/blob/bd07fa0be613b8253c9518349f4ab5b1017c1a5b/donjo-app/helpers/opensid_helper.php#L509

**Comment by roaddee** [comment]
> @afri18 ada info error tidak pak di folder `logs/`?
> Kalau ada tolong di posting kesini. atau coba aktifkan ekstensi `curl` di file `php.ini`
> 
> Error yang muncul itu sepertinya fatal error karena ekstensi `curl` belum diaktifkan. datangnya baris ini:
> https://github.com/OpenSID/OpenSID/blob/bd07fa0be613b8253c9518349f4ab5b1017c1a5b/donjo-app/helpers/opensid_helper.php#L509

kalau di cpanel, apa cukup dengan menambahkan baris ini pak @esyede 
`extension=curl`
begitu saja ?, karena di cpanel kan beda2 setiap hosting.
--
dan mohon email saya dibalas, atau bisa berikan nomor telepon di balasan emailnya (darurat)

**Comment by esyede** [comment]
> kalau di cpanel, apa cukup dengan menambahkan baris ini pak @esyede 
> `extension=curl`
> begitu saja ?, karena di cpanel kan beda2 setiap hosting.
> nb :
> dan mohon email saya dibalas, atau bisa berikan nomor telepon di balasan emailnya (darurat)

iya pak, setelah itu di pastikan juga di phpinfo ya

**Comment by afri18** [comment]
Belum berhasil, heran kenapa mesti eror, padahal versi sebelumnya aman

**Comment by eddieridwan** [comment]
> Belum berhasil, heran kenapa mesti eror, padahal versi sebelumnya aman

Bung @syafri, coba uncomment baris di `OpenSID/donjo-app/helpers/opensid_helper.php`, seperti terlihat di gambar. Kemudian laporkan di sini error yg ditampilkan.

![syafri](https://user-images.githubusercontent.com/249563/89297339-06c9ea80-d6a7-11ea-9645-0c3efdd88999.jpg)

**Comment by afri18** [comment]
Tetep belum bisa, mesti balikkah ke 20.07 ???

**Comment by roaddee** [comment]
saya bisa akses cpanel pak @afri18 , mungkin bisa bantu
kalau oke, bapak inbox/pm saya

**Comment by abmuj18** [comment]
http://45.13.132.21:2006/index.php/hom_sid

Telah dialami error PHP sebagai berikut:

Severity: 8
Pesan: Undefined property: Hom_sid::$setting
Nama File: /var/www/html/margaluyu/system/core/Model.php
Nomor Baris: 73Telah dialami error PHP sebagai berikut:

Severity: 8
Pesan: Undefined variable: db_debug
Nama File: /var/www/html/margaluyu/donjo-app/models/Database_model.php
Nomor Baris: 116Telah dialami error PHP sebagai berikut:

Severity: 8
Pesan: Undefined property: Hom_sid::$session_user
Nama File: /var/www/html/margaluyu/system/core/Model.php
Nomor Baris: 73Telah dialami error PHP sebagai berikut:

Severity: 2
Pesan: fopen(/var/www/html/margaluyu/cacert.pem): failed to open stream: Permission denied
Nama File: /var/www/html/margaluyu/donjo-app/libraries/Curly.php
Nomor Baris: 273

**Comment by afri18** [comment]
meng Aktifkan ini dari mana ya ???
![image](https://user-images.githubusercontent.com/6611881/90084164-d89b7900-dd3e-11ea-92a1-ccf9eb4348ba.png)

**Comment by afri18** [comment]
bung @eddieridwan  ini erornya
![image](https://user-images.githubusercontent.com/6611881/90093467-e0b2e300-dd55-11ea-8cf8-db031da4fb3c.png)

**Comment by eddieridwan** [comment]
Bung @afri18 , untuk dibantu melacak masalah ini di instalasi anda, silakan PM url/login cPanel dan login admin.

**Comment by afa28** [comment]
Silahkan reopen issue ini jika masih bermasalah.

**Comment by eddieridwan** [comment]
Sdh dicommit ke `bug-fix` melalui https://github.com/OpenSID/premium/pull/264

**Comment by tukangpolesweb** [comment]
Saya juga mengalami hal serupa di versi 21.07. Webserver OS Debian menggunakan Nginx dan PHP-FPM. Bagaimanakah solusinya?
