### ISSUE TITLE
Link statistik perekaman E-KTP

### ISSUE THREAD

**Issue by AliAshgar** [OpenSID/OpenSID#3421]
Link pada statistik perekaman e-KTP untuk yang belum mengisi tidak muncul ketika di klik, padahal nilai dari  jumlah yang belum mengisi tersebut ada

**Comment by afa28** [comment]
> Link pada statistik perekaman e-KTP untuk yang belum mengisi tidak muncul ketika di klik, padahal nilai dari jumlah yang belum mengisi tersebut ada

Ya, sy sdah catat jg waktu krja modul statistik. Krn pd statistik e-KTP angkanya beda sendiri, jd sy tunggu org untuk melaporkan. Tp mungkin perlu disediakan gambar untuk issue ini dan bisa diperjelas.

**Comment by AliAshgar** [comment]
Ada 2 gambar yang harus di upload, gambar 1 ketika di page statistik, gambar 2 ketika link ssh mengarah ke tampilan data dari menu statistik

**Comment by AliAshgar** [comment]
Adab2 gambar yang harus di upload, gambar 1 ketika di page statistik, gambar 2 ketika link ssh mengarah ke tampilan data dari menu statistik

**Comment by afa28** [comment]
Sudah diperbaiki, silahkan cek kembali.
