### ISSUE TITLE
Pencarian/sortingan Data Penduduk/Keluarga

### ISSUE THREAD

**Issue by R4HMAT** [OpenSID/OpenSID#3422]
### Bagaimana alurnya sampai muncul masalah?
proses encarian data tidak bisa lebih dari 1 

### Seperti apa yang diharapkan?
pencarian data tersebut di menu kependudukan - penduduk- keluarga bisa lebih dari 1 (satu) untuk mempercepat pencarian data penduduk untuk pencarian berbasi nik,kk untuk lebih dari satu, pada pencarian berbasis NIK/KK yang belakang diawali dengan tanda koma (,) exmaple. data
![datakirim2](https://user-images.githubusercontent.com/43318683/89160587-8074b200-d59b-11ea-9c4d-0e7d24f7605c.png)

screnshot gambar pencarian.
![data kirim1](https://user-images.githubusercontent.com/43318683/89159918-67b7cc80-d59a-11ea-8484-34e0ba0d3524.png)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.08.pasca
| Versi PHP        | 
| System operasi   |

**Comment by R4HMAT** [comment]
Kalau bisa dimaksimalkan 20 penduduk/keluraga
Berbasis NIK/KK.

**Comment by MUHAMMADRANGSEL** [comment]
Seperti aplikasi SIAK DUKCAPIL, guna mempercepat proses pencarian dan penyandingan data

**Comment by eddieridwan** [comment]
Mungkin sebagai Pencarian Spesifik seperti yg ada di daftar Penduduk? Di situ ada form untuk memilah berdasarkan berbagai kolom, dan tentunya itu bisa kita kembangkan sesuai kebutuhan.

![pencarian-spesifik](https://user-images.githubusercontent.com/249563/89173876-4241b780-d5c8-11ea-92d8-8f4134e7fd53.jpg)

**Comment by eddieridwan** [comment]
Atau apakah maksudnya untuk mencari beberapa entri sekaligus? Mungkin bisa lampirkan tampakan layar SIAK DUKCAPIL sebagai contoh, karena kalau itu yg diperlukan bentuk formnya perlu dirancang ulang.

**Comment by afa28** [comment]
> Atau apakah maksudnya untuk mencari beberapa entri sekaligus? Mungkin bisa lampirkan tampakan layar SIAK DUKCAPIL sebagai contoh, karena kalau itu yg diperlukan bentuk formnya perlu dirancang ulang. 

Bisa pakai mutiple select yg ad di admin lte untuk view, nanti di modelnya pakai where in

**Comment by AliAshgar** [comment]
Kalo saya liat metodenya bisa diakalin dengan explode, jadi hasil dari form tsb akan berbentuk array yang bisa di while kedalam sql, jadi kalau mau hasil pencariannya banyak kudu spesifik menggunakan pemisah apa

**Comment by afa28** [comment]
> Kalo saya liat metodenya bisa diakalin dengan explode, jadi hasil dari form tsb akan berbentuk array yang bisa di while kedalam sql, jadi kalau mau hasil pencariannya banyak kudu spesifik menggunakan pemisah apa

Klw hanya untuk mencari sj, tinggal input dgn format nik, nik. Nanti datanya disimpan dgn pencarian where in.

Tp klw mau menampilkan semacam autocomple, bisa pakai cara yg di atas.

**Comment by MUHAMMADRANGSEL** [comment]
pemisahnya menggunakan koma
contoh : 52030301072000001,52030301072000002,52030301072000003,52030301072000003, dst

**Comment by MUHAMMADRANGSEL** [comment]
Ini akan mempermudah Operator Desa/ Pemerintah desa dalam melakukan Update data secara berkelanjutan

**Comment by AliAshgar** [comment]
> > Kalo saya liat metodenya bisa diakalin dengan explode, jadi hasil dari form tsb akan berbentuk array yang bisa di while kedalam sql, jadi kalau mau hasil pencariannya banyak kudu spesifik menggunakan pemisah apa
> 
> Klw hanya untuk mencari sj, tinggal input dgn format nik, nik. Nanti datanya disimpan dgn pencarian where in, tanpa perlu di explode lg.
> 
> Tp klw mau menampilkan semacam autocomple, bisa pakai cara yg di atas.


Tapi dari issues diatas keliatan kalo metodenya mencari lebih dari 1 nik, dengan hasil spesifik dari inputan nik,
Kalo sekedar autocomplete sih bisa aja tapi terbatas dengan satu hasil di resultnya

**Comment by eddieridwan** [comment]
> pemisahnya menggunakan koma
> contoh : 52030301072000001,52030301072000002,52030301072000003,52030301072000003, dst

@MUHAMMADRANGSEL harap lampirkan contoh form di SIAK DUKCAPIL untuk mengisi daftar pencarian seperti ini. Karena terlihat tidak enak kalau di kotak isian yg kecil.

**Comment by R4HMAT** [comment]
> 
> 
> Ini akan mempermudah Operator Desa/ Pemerintah desa dalam melakukan Update data secara berkelanjutan

mantap sekali,

**Comment by MUHAMMADRANGSEL** [comment]
> > pemisahnya menggunakan koma
> > contoh : 52030301072000001,52030301072000002,52030301072000003,52030301072000003, dst
> 
> @MUHAMMADRANGSEL harap lampirkan contoh form di SIAK DUKCAPIL untuk mengisi daftar pencarian seperti ini. Karena terlihat tidak enak kalau di kotak isian yg kecil.
> 
> Dalam prakteknya, daftar pencarian ini diambil dari mana? Pakai copy/paste dari daftar mana? Karena pasti teman2 tdk akan mengetik satu per satu?

![Screenshot 2020-08-06 14 57 36](https://user-images.githubusercontent.com/25834335/89765881-c7c5ea00-db29-11ea-86bd-bc66842a54d8.jpg)
![Screenshot 2020-08-06 14 57 52](https://user-images.githubusercontent.com/25834335/89765885-c98fad80-db29-11ea-9023-499ff96b8d9a.jpg)
![Screenshot 2020-08-06 15 00 09](https://user-images.githubusercontent.com/25834335/89765890-cb597100-db29-11ea-8165-e2a1dc5d4d03.jpg)

**Comment by MUHAMMADRANGSEL** [comment]
> > pemisahnya menggunakan koma
> > contoh : 52030301072000001,52030301072000002,52030301072000003,52030301072000003, dst
> 
> @MUHAMMADRANGSEL harap lampirkan contoh form di SIAK DUKCAPIL untuk mengisi daftar pencarian seperti ini. Karena terlihat tidak enak kalau di kotak isian yg kecil.
> 
> Dalam prakteknya, daftar pencarian ini diambil dari mana? Pakai copy/paste dari daftar mana? Karena pasti teman2 tdk akan mengetik satu per satu?

Seperti ini tampilan di SIAK :
![Screenshot 2020-08-06 14 57 36](https://user-images.githubusercontent.com/25834335/89766128-386d0680-db2a-11ea-91e9-0da7eab4f571.jpg)
![Screenshot 2020-08-06 14 57 52](https://user-images.githubusercontent.com/25834335/89766133-3a36ca00-db2a-11ea-9fa1-36e65d7dc4ea.jpg)
![Screenshot 2020-08-06 15 00 09](https://user-images.githubusercontent.com/25834335/89766136-3b67f700-db2a-11ea-96df-4f3c039e244d.jpg)

**Comment by MUHAMMADRANGSEL** [comment]
Issue belum dikerjakan sdh diclosed

Pada tanggal Sab, 15 Agt 2020 20.04, R4HMAT <notifications@github.com>
menulis:

**Comment by yonathanrizky** [comment]
ijin saya yg mengerjakan pak @eddieridwan , dan untuk maksimal nik yg diperbolehkan berapa banyak pak ?

**Comment by eddieridwan** [comment]
@yonathanrizky boleh. Tapi jangan gunakan kolom isian `Cari` karena akan membuat fungsi itu menjadi rancu. Tapi buat menu/tombol khusus untuk keperluan ini, di mana formnya bisa dibuat lebih cocok untuk mengisi beberapa NIK atau No. KK. Sediakan form supaya bisa cari sampai 20 NIK atau KK.

![kumpulan-nik](https://user-images.githubusercontent.com/249563/92464955-4a1cf900-f211-11ea-8a51-ccee86244f30.jpg)

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3547
