### ISSUE TITLE
Pencarian nama untuk Ketua Kelompok dan Anggota

### ISSUE THREAD

**Issue by AliAshgar** [OpenSID/OpenSID#3424]
Pencarian nama pada ketua kelompok dan anggotanya tidak disertakan alamat, dikarenakan ada beberapa nama yang sama dalam desa ini agak menyulitkan penginputan data kelompok

_Solusi_

Agak bisa disertakan alamat lengkap pada pencarian nama Ketua kelompok beserta angotanya

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR  #3427
