### ISSUE TITLE
Menu pertanahan

### ISSUE THREAD

**Issue by Fandha** [OpenSID/OpenSID#3426]
Bisakah mengembalikan uraian pada Persil Tanah saat ini seperti rincian persil tanah dulu, ada rincian jenis persil, peruntukan persil, dan kelas persil. Fungsi ini sangat bermanfaat untuk melihat klasifikasi tertentu seperti peruntukan persil atau jenis persilnya. Sedangkan untuk kelas persil mengacu pada ketentuan PBB dari kemenkeu saat ini yaitu kelas bumi dan kelas bangunan. Terima kasih...

[PBB.pdf](https://github.com/OpenSID/OpenSID/files/5020250/PBB.pdf)

**Comment by Fandha** [comment]
Bisakah melakukan perekaman persil dengan menggunakan peta/mapping gps. Misalnya saat dilakukan pencatatan persil, ada penambahan menu sebagaimana saat kita membuat peta wilayah desa/rw/rt sehingga persil kita dapat lebih termanajemen seperti BPN. Adapun hasil persil tadi dapat kita tampilkan di menu pemetaan. Dengan demikian pada saat satu desa mau memaparkan kekuatan pendapatan PBB dapat mengambil peta kita. Terima kasih...

**Comment by eddieridwan** [comment]
@Fandha seperti dijelaskan sebelumnya, mohon tidak menggabung beberapa usul dalam satu issue. Buat issue terpisah untuk setiap usul. Programmer mengerjakan issue satu per satu. Dan tidak dapat mengerjakan issue yg menggabungkan beberapa usul sekaligus.

**Comment by eddieridwan** [comment]
> Bisakah mengembalikan uraian pada Persil Tanah saat ini seperti rincian persil tanah dulu, ada rincian jenis persil, peruntukan persil, dan kelas persil. Fungsi ini sangat bermanfaat untuk melihat klasifikasi tertentu seperti peruntukan persil atau jenis persilnya. Sedangkan untuk kelas persil mengacu pada ketentuan PBB dari kemenkeu saat ini yaitu kelas bumi dan kelas bangunan. Terima kasih...
> 
> [PBB.pdf](https://github.com/OpenSID/OpenSID/files/5020250/PBB.pdf)

Masalah ini dulu sudah ditanyakan secara khusus di https://www.facebook.com/groups/OpenSID. Apakah boleh dihilangkan atau tidak. Dan TIDAK ADA yg menyatakan berkebaratan. Mohon selalu pantau pengumuman di FB dan tanggapi, supaya tidak seperti sekarang -- setelah dihapus baru menanggapi.

**Comment by Fandha** [comment]
> > Bisakah mengembalikan uraian pada Persil Tanah saat ini seperti rincian persil tanah dulu, ada rincian jenis persil, peruntukan persil, dan kelas persil. Fungsi ini sangat bermanfaat untuk melihat klasifikasi tertentu seperti peruntukan persil atau jenis persilnya. Sedangkan untuk kelas persil mengacu pada ketentuan PBB dari kemenkeu saat ini yaitu kelas bumi dan kelas bangunan. Terima kasih...
> > [PBB.pdf](https://github.com/OpenSID/OpenSID/files/5020250/PBB.pdf)
> 
> Masalah ini dulu sudah ditanyakan secara khusus di https://www.facebook.com/groups/OpenSID beberapa waktu yg lalu. Menanyakan apakah boleh dihilangkan atau tidak. Dan TIDAK ADA yg menyatakan berkebaratan. Mohon selalu pantau pengumuman di FB dan tanggapi, supaya tidak seperti sekarang -- setelah dihapus baru menanggapi.

Mohon maaf mas jika seperti itu. Saya dulu menggunakan opensid pada masa awal 2015 s/d 2016, hehehe, setelah itu pindah tugas jadi tidak pegang opensid lagi dan tidak ikut mantau. Sekarang bergabung kembali dilingkungan desa/kelurahan dan mau mengajak kawan2 untuk menggunakan ini. Kebetulan ingat dulu ada klasifikasi begitu. Saya ngikut aj dari forumnya. Tadi hanya menyampaikan kondisi di kami yg mungkin berbeda dg yg ditempat lain dan membutuhkn klasifikasi tsb. Sekali lagi terima kasih karena opensid perkembangannya luar biasa...

**Comment by HerryWanda** [comment]
Iya betul pak..
saya baru nyadar di akhir..
karna format data pertanahan ini tidak baku di desa..
Jadi mantik tinggal di sesuaikan aja mana yg akan digunakan desa, apakah format yg lama, atau yg sekarang (C-desa)..

**Comment by afa28** [comment]
Silahkan cek ulang modul pertanahan yg baru, jika masih ada bermasalah silahkan buat issue yang baru.
