### ISSUE TITLE
permasalahan tampilan status perkawinan

### ISSUE THREAD

**Issue by AliAshgar** [OpenSID/OpenSID#3429]
### Bagaimana alurnya sampai muncul masalah?
ketika penginputan secara form saya rasa kasus  ini tidak akan muncul, tapi ketika data penduduk di import menggunakan excel seperti yang saya alami akan menimbulkan masalah sesuai gambar yang saya sertakan dibawah ini
![Screenshot (83)_LI](https://user-images.githubusercontent.com/56395293/89350233-39450900-d6e2-11ea-86a3-3a4bbb1b9c1f.jpg)

### Seperti apa yang diharapkan?
mungkin perlu ada perbaikan pada source import data penduduk excel atau pada koding file keluarag_model.php seperti yang saya lakukan kmren.

### Apa yang terjadi?
terjadi result yang tidak sesuai dengan yang di harapakan ketika field akta_perkawinan pada database berupa null, masih tetap terbaca sebagai KAWIN TERCATAT.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.08
| Versi PHP        | 
| System operasi   |

**Comment by Nurhidayat29** [comment]
apkh sdh coba di demo?

**Comment by eddieridwan** [comment]
Sdh ada perbaikan di `master` (pra-rilis terbaru). Silakan dicoba lagi. Laporkan di sini kalau masih bermasalah.

**Comment by Nurhidayat29** [comment]
Di  demo.opensid.my.id  tidak ditemukan masalah diatas
