### ISSUE TITLE
Cetak atau Unduh Statistik Penduduk error

### ISSUE THREAD

**Issue by Fandha** [OpenSID/OpenSID#3431]
### Bagaimana alurnya sampai muncul masalah?
Pada saat membuka menu statistik, kategori Statistik Penduduk yang terbuka adalah Pendidikan dalam KK, apabila di lakukan aksi cetak atau unduh, setelah memasukan pilihan tanda tangan dan nomor, yang terbuka hanyalah halaman kosong dengan pilihan kembali tanda tangan dan nomor. Apabila diteruskan akan error.

### Seperti apa yang diharapkan?
Kategori Pendidikan dalam KK dapat melakukan pencetakan dan unduhan kembali

### Apa yang terjadi?
Tidak dapat mencetak atau mengunduh kategori statistik penduduk menurut pendidikan dalam kk

### Informasi tambahan 
Untuk kategori lainnya sepertinya tidak bermasalah.

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.08
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master`.
