### ISSUE TITLE
Nama Dusun yang di input tidak sesuai dengan yg ditampilkan

### ISSUE THREAD

**Issue by ai-skematik** [OpenSID/OpenSID#3434]
### Bagaimana alurnya sampai muncul masalah?
nama dusun di input dengan angka romawi I, II, III, IV dst, yg ditampilkn I, Ii, Iii dst,

### Seperti apa yang diharapkan?
dusun yg ditampilkan sesuai dengan yg di input

### Apa yang terjadi?
nama dusun yg ditampilkan tidak sesuai dengan yg di input

### Informasi tambahan 
di sulawesi tengah dusun masih menggunakan angka romawi
| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 

> 20.08

| Versi PHP        | 
| System operasi   |
![NAMA DUSUN](https://user-images.githubusercontent.com/48144047/89501212-21a67700-d7ed-11ea-83bf-81b9aaf3eff9.png)
![DUSUN II](https://user-images.githubusercontent.com/48144047/89501272-40a50900-d7ed-11ea-91a9-97ffe95311ca.png)
![DUSUN I](https://user-images.githubusercontent.com/48144047/89501402-7c3fd300-d7ed-11ea-89f5-ef4895429f44.png)

**Comment by eddieridwan** [comment]
@ai-skematik @roaddee maaf mohon diperjelas masalahnya. Saya coba normal saja. Apakah NIK yg bermasalah atau dusunnya?

**Comment by afa28** [comment]
> @ai-skematik @roaddee maaf mohon diperjelas masalahnya. Saya coba normal saja. Apakah NIK yg bermasalah atau dusunnya?
> 
> Atau coba replikasi masalahnya di https://demo.opensid.my.id. 

Yg sy tangkap, masalahnya adalah sistem mengubah otomatis setiap inputan nama dusun/rw/rt menjadi huruf besar (modul wilayah) / huruf besar kecil (combo_box pencarian wilayah) di tiap modul bersangkutan. Sehingga jika ad nama dusun yg seharusnya huruf kapital semua akan di ubah otomatis dan atau sebaliknya.

Jd mungkin solusinya, nama dusun/rw/rt yg disimpan/ditampilkan/dicetak berdasarkan inputan yg disimpan tanpa ada konversi huruf besar/kecil/lainnya.

Apa benar bgni pak @ai-skematik ???

**Comment by ai-skematik** [comment]
Iya betul.. 
Jika ditulis dengan huruf kapital, maka yg di tampilkan huruf kapital bgt juga sebaliknya.

**Comment by roaddee** [comment]
sepertinya masuk akal

**Comment by eddieridwan** [comment]
Saya tidak melihat solusi itu sebagai yg dapat bertahan untuk semua kebutuhan. Hampir pasti akan ada kasus di mana nama dusun dibutuhkan dalam format semua huruf besar, dan hampir pasti akan ada kasus lain di mana lebih cocok kalau nama dusun dalam format title case.

Yaitu hampir pasti format tersimpan di database tidak akan memenuhi semua kebutuhan. 

Alternatif lain adalah mengembangkan method seperti `set_ucwords` di `donjo-app/helpers/donjolib_helper.php` supaya bisa menangani kasus nama menggunakan huruf romawi.

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master`.
