### ISSUE TITLE
URL berupa ID langsung redirect ke slug

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#3436]
### Bagaimana alurnya sampai muncul masalah?
Saat ini, untuk artikel yang dibuka berdasarkan ID, tidak mengarah pada slug, sehingga tetap bisa dibuka berdasarkan ID.

![image](https://user-images.githubusercontent.com/46939846/89600265-cc6d7280-d88b-11ea-92b3-0a8afc004ed0.png)

### Seperti apa yang diharapkan?
misal akses:
https://www.natairaya.desa.id/first/artikel/57

langsung otomatis redirect ke :
https://www.natairaya.desa.id/artikel/2019/2/12/kegiatan-ddtk-deteksi-dini-tumbuh-kembang

### Apa yang terjadi?
Agar ID tidak terbaca dan memanfaatkan slug yang telah diterapkan sebelumnya.

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3470
