### ISSUE TITLE
Tampilkan pengumuman dari server pantau OpenSID

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#3437]
### Bagaimana alurnya sampai muncul masalah?
Saat ini belum ada cara bagi OpenSID untuk menerima pengumuman dari server OpenDesa.

### Seperti apa yang diharapkan?
Pada waktu mengirim data pantauan ke server OpenDesa, OpenSID dapat menerima kiriman pengumuman dari server OpenDesa, dan menampilkan pengumuman tersebut.

Kalau ada pengumuman, server OpenDesa akan mengirim balik pengumuman tersebut pada waktu dipanggil oleh OpenSID.

Saat ini server OpenDesa hanya mengirim status panggilan pada waktu dipanggil oleh OpenSID.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | v20.08
| Versi PHP        | 
| System operasi   |

**Comment by masumo** [comment]
ini maksudnya bikin API untuk kirim pengumuman dari OpenDesa ke OpenSID ya pak?
saya masih belum paham bedanya dengan issue #3355

**Comment by eddieridwan** [comment]
@masumo Yg ini #3437, tidak diperlukan API di OpenSID. Saat ini di `donjo-app/models/Track_model.php`, ada method `kirim_data()`. Untuk issue ini, OpenSID yg memanggil trackSID untuk mengambil pengumuman. Yaitu APInya ada di trackSID, dan mudah2an bisa gunakan API yg sudah ada di trackSID.
`OpenSID --> trackSID`

Sedangkan di #3355, trackSID yg memanggil OpenSID untuk mengirim pengumuman. 
`trackSID ---> OpenSID`

Jadi bedanya arah pemanggilan.

**Comment by roaddee** [comment]
jadi ini hanya menyediakan API di trackSID pak ?

**Comment by eddieridwan** [comment]
API-nya sdh ada di trackSID. Tinggal dikembangkan untuk mengirim balik pengumuman setelah menyimpan data yg dikirim OpenSID.

**Comment by roaddee** [comment]
saya juga kurang paham pak, apakah pengumuman yang diberikan oleh opendesa nantinya berdasarkan permintaan dari opensid atau akan berbentuk seperti notifikasi ? yang bisa dikirim kapan saja ?

**Comment by eddieridwan** [comment]
Contoh skenario: 

1. OpenDesa akan melakukan pelatihan OpenSID di Kab x pada bulan September. Dan ingin memberi kesempatan bagi desa di Kab x dan sekitarnya untuk ikut serta. Pada waktu OpenSID dari Kab x dan sekitarnya memanggil trackSID, akan terdeteksi, dan trackSID akan mengirim balik pengumuman tentang pelatihan tersebut.
2. Ada fitur (mungkin premium) baru yg sudah siap digunakan desa, yg dinilai cukup penting untuk dipertimbangkan desa. Dan mengajak semua desa untuk mempertimbangkan mengupgrade supaya bisa memanfaatkan fitur tersebut. Dalam hal ini setiap desa yg memanggil trackSID akan menerima pengumuman ini. 
3. Ada desa di Kecamatan Z yg baru menginstall OpenSID. Pada waktu OpenSID dari Kecamatan Z memanggil trackSID beritahu mereka tentang desa baru tersebut.
4. dstnya.. 

Yang memasukkan pengumuman tersebut ke trackSID adalah Pengurus OpenDesa. Jadi nantinya perlu ditambah fitur di trackSID untuk mengelola pengumuman.

**Comment by masumo** [comment]
Berarti restAPI server ada di OpenSID ya pak? Bikin API di OpenSID kemudian trackSID panggil API tsb untuk kirim pengumuman? Pengumuman dikirim hanya utk desa tertentu yang dipilih.

**Comment by eddieridwan** [comment]
> Berarti restAPI server ada di OpenSID ya pak? Bikin API di OpenSID kemudian trackSID panggil API tsb untuk kirim pengumuman? Pengumuman dikirim hanya utk desa tertentu yang dipilih.

@masumo : TIDAK. OpenSID yg memanggil trackSID menggunakan method `kirim_data()` yg sdh ada di `donjo-app/models/Track_model.php`. Saat ini trackSID hanya mengirim balik status sukses atau tidak. Tinggal mengubah trackSID supaya trackSID mengembalikan pengumuman. Kemudian di `kirim_data()` di OpenSID, pengumuman yg diterima itu dimasukkan ke tabel `notifikasi`. 

Mohon penjelasan di beberapa komentar di atas dibaca berkali-kali supaya lebih jelas.

**Comment by eddieridwan** [comment]
`kirim_data()` saat ini menggunakan `function httpPost($url, $params)` yang ada di `donjo-app/helpers/opensid_helper.php`. Function itu mengembalikan data dari trackSID, tetapi saat ini belum digunakan oleh `kirim_data()`. Jadi tinggal dikembangkan supaya mengambil dan memproses data dari trackSID. 

Ok, silakan pelajari script pemanggilan trackSID yg sudah ada di OpenSID. Dan pelajari script di trackSID yg memproses data yg diterima dari OpenSID.

**Comment by masumo** [comment]
Oke Pak

**Comment by masumo** [comment]
boleh minta database dump dari trackSID pak?

**Comment by eddieridwan** [comment]
[opensidm_tracksid-2020-06-12.sql.zip](https://github.com/OpenSID/OpenSID/files/5044490/opensidm_tracksid-2020-06-12.sql.zip)

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3462
