### ISSUE TITLE
Tidak bisa simpa data Penduduk untuk RW - (pilihan '-' tidak muncul)

### ISSUE THREAD

**Issue by roaddee** [OpenSID/OpenSID#3439]
### Bagaimana alurnya sampai muncul masalah?
Saat isi data penduduk, dan ketika selesai tidak bisa simpan karena RW tidak dipilih, padahal tidak ada pilihan RW
![image](https://user-images.githubusercontent.com/45786885/89641734-8db3d880-d8dc-11ea-9d68-9674732dc688.png)

### Seperti apa yang diharapkan?
Muncul Pilihan RW '-'

### Apa yang terjadi?
Tidak bisa simpan data penduduk

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.08-pasca
| Versi PHP        |  7.2
| System operasi   |  Linux

**Comment by eddieridwan** [comment]
Beri langkah pengisian data sampai timbul masalah ini. Karena di https://demo.opensid.my.id tidak bermasalah. Coba replikasi masalah ini di demo.

**Comment by roaddee** [comment]
kalau di demo.opensid.my.id memang tidak ada RW (menggunakan -), akan tetapi ada RT. sedangkan di contoh desa yang bermasalah ini adalah selain tidak ada RW juga tidak ada RT, ketika akan membuat RT dengan isian -, tidak bisa karena hanya bisa diisi angka.

**Comment by afa28** [comment]
> kalau di demo.opensid.my.id memang tidak ada RW (menggunakan -), akan tetapi ada RT. sedangkan di contoh desa yang bermasalah ini adalah selain tidak ada RW juga tidak ada RT, ketika akan membuat RT dengan isian -, tidak bisa karena hanya bisa diisi angka.
> 

Ya

**Comment by eddieridwan** [comment]
@roaddee nah begitu dong. Beri keterangan yg lebih jelas supaya tahu masalahnya.

**Comment by roaddee** [comment]
betu pak @eddieridwan , 
nama desa : Sako Utara Pasia Talang
Prov : Sumbar
saya sudah tanyakan tidak semua desa, ada sebagian

**Comment by fusionid** [comment]
Ketika sudah menambahkan dusun di menu info desa -> wilayah administratif -> tambah dusun, maka secara otomatis akan ada 1 set data berisi 3 row data di tabel `tweb_wil_clusterdesa`, yg berisi dusun, rw dan rt.

![Screen Shot 08-08-20 at 12 10 AM](https://user-images.githubusercontent.com/10391199/89698908-fbe4b380-d94d-11ea-9aa7-97775de5ba9f.PNG)

Jika 1 set data itu lengkap, maka kolom2 pengisian alamat penduduk untuk dusun, rw, dan rt akan lengkap juga :
![Screen Shot 08-08-20 at 08 08 AM](https://user-images.githubusercontent.com/10391199/89699036-a2c94f80-d94e-11ea-9123-ebdd4e5e888a.PNG)

Jika 1 set data itu tidak lengkap maka kolom2 pengisian alamat penduduk untuk dusun, rw, dan rt juga  akan tidak lengkap / kosong.

Kemungkinan tabel  `tweb_wil_clusterdesa` telah dirubah secara manual dgn menghapus row data rw dan rt sehingga data rw dan rt tidak dapat tampil
![Screen Shot 08-08-20 at 12 10 AM 001](https://user-images.githubusercontent.com/10391199/89699122-1cf9d400-d94f-11ea-92c9-6dcb420e4269.PNG)

Solusinya : Hapus dusun di menu info desa -> wilayah administratif -> Hapus dan kemudian tambah kembali dusun nya.

**Comment by roaddee** [comment]
Baik pak, saya coba nya dulu

**Comment by roaddee** [comment]
pak @fusionid apakah berpengaruh kepada penduduk yang saat ini existing ?

**Comment by fusionid** [comment]
Pastinya berpengaruh karena id data dusun sudah berubah.
Tapi bukannya semua data dusun/rw/rt penduduk belum valid karena tidak bisa disimpan ?

**Comment by roaddee** [comment]
yang bermasalah ini sudah punya ribuan data penduduk, mungkin data2 nya didapat dari import, ada penduduk baru yang akan di entri, ketika dicoba muncul masalah tersebut.

**Comment by fusionid** [comment]
Apakah data penduduk yg sudah exist ini bisa diedit dusun/rw/rt-nya dan disimpan ?

**Comment by roaddee** [comment]
kalau yang exist, bisa pilih RW -

**Comment by fusionid** [comment]
Yang tidak bisa disimpan, penduduk yg akan dientri di desa Jorong Mudiak Lawe Timur ?

**Comment by roaddee** [comment]
ya semua dusun pak, khusus entri baru
kalau edit/ubah bisa semua

**Comment by fusionid** [comment]
Bisa di ss entri baru di dusun Jorong Mudiak Lawe Timur

**Comment by roaddee** [comment]
saya inbox messenger saja pak @fusionid akun admin untuk mencoba nya

**Comment by eddieridwan** [comment]
@roaddee sepertinya tidak ada script yg perlu diubah. Tapi supaya lebih jelas, sekarang RT kosong dapat dilihat di rincian RW kosong, seperti di gambar berikut:

![rt-kosong](https://user-images.githubusercontent.com/249563/90244465-2c5bae80-de74-11ea-860f-2d67c9530eb3.jpg)

Issue ini akan ditutup. Tapi silakan dibuka lagi kalau ada error yg bisa direplikasi di https://demo.opensid.my.id

**Comment by roaddee** [comment]
baik pak @eddieridwan , yang di demo sudah bisa, saya coba hapus RT nya semua

**Comment by roaddee** [comment]
sudah saya coba pak @eddieridwan , dan masih belum bisa
sudah saya PM pak, informasi akunnya

**Comment by eddieridwan** [comment]
Ok, sesudah diperiksa, ternyata database dari desa ybs tidak lengkap. Misalnya, tabel `setting_modul` banyak yg tidak lengkap. Sepertinya migrasi `donjo-app/models/migrations/Migrasi_1909_ke_1910.php` tidak pernah dijalankan untuk database ybs. Mungkin saja ada migrasi lain yg juga belum dijalankan.  Diduga akan ada banyak fitur yg tidak jalan.

Solusi yg dicoba adalah dengan memaksa semua migrasi dijalankan mulai dari v19.08. Caranya adalah dengan mengubah setting `current_version` di tabel `setting_aplikasi` dan menghapus data di tabel `migrasi`. Pada waktu membuka aplikasi lagi semua migrasi mulai dari v20.08 akan dijalankan.

Setelah ini dilakukan, masalah dusun/rw/rt teratasi. Tapi, karena migrasi lama dijalankan, mungkin saja ada perubahan data tidak terduga. Dalam hal ini, pengguna perlu memeriksa data mereka dengan seksama.

**Comment by fusionid** [comment]
Seperti yg sudah sampaikan masalahnya di database bukan di aplikasi. Seminggu yg lalu database yg sudah diperbaiki sudah dikirim ke pak @roaddee tapi mungkin belum sempat dicoba.
