### ISSUE TITLE
Permintaan Tambahan Menu Pilihan Menampilkan Area Pada Peta Lokasi Penduduk 

### ISSUE THREAD

**Issue by Zulkarnaimni** [OpenSID/OpenSID#3440]
### Bagaimana alurnya sampai muncul masalah?
Permintaan Tambahan Menu Pilihan Area Pada Peta Lokasi Penduduk apabila dimungkinkan supaya penentuan lokasi penduduk/KK Pada Biodata Penduduk Jadi lebih mudah menempatkan penanda pada Peta Desa. Atas Advice-nya terimakasih sebelumnya.

### Seperti apa yang diharapkan?

![image](https://user-images.githubusercontent.com/64481641/89720165-93eba700-d9f9-11ea-9db8-4f2ba33e49b3.png)
![image](https://user-images.githubusercontent.com/64481641/89720172-9ea63c00-d9f9-11ea-98ac-39706fbac1af.png)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
Apakah ini hanya sebagai view informasi sj agar lebih mudah menentukan lokasi penduduk agar tdk melewati batas desa/rw/rt???

**Comment by Zulkarnaimni** [comment]
Iya Pak Andi, muncul seperti pada tampilan peta pada web publik jadi mudah ditanda letak dan posisi lokasi

**Comment by afa28** [comment]
> Iya Pak Andi, muncul seperti pada tampilan peta pada web publik jadi mudah ditanda letak dan posisi lokasi

Ok

**Comment by mizwaruddin** [comment]
Di sana sudah ada pilihan utk menampilkan peta wilayah RT. Apakah masih belum cukup membantu?

**Comment by afa28** [comment]
Silahkan direopen jika msih bermasalah.

**Comment by Zulkarnaimni** [comment]
Oke Pak Andi, makasih sudah klar nyampaknya…….


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
