### ISSUE TITLE
[Bug] menu Calon Pemilih Error

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#3445]
### Bagaimana alurnya sampai muncul masalah?
Menu Kependudukan==> Calon Pemilih terjadi error
![image](https://user-images.githubusercontent.com/25834335/89784742-c6a5b480-db4b-11ea-858b-2098baef89a1.png)

### Seperti apa yang diharapkan?
Calon Pemilih tidak terjadi error seperti versi sebelumnya

### Apa yang terjadi?
Tidak bisa melihat dan mencetak calon pemilih

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.08-Pasca
| Versi PHP        | 7.3, 7.4
| System operasi   |

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master`
