### ISSUE TITLE
Tidak tertulis Kolom Nama Kecamatan pada Identitas Desa

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#3447]
### Bagaimana alurnya sampai muncul masalah?
Sebutan untuk Kolom ini tidak menerangkan yang diminta adalah nama apa.

![kecamatan](https://user-images.githubusercontent.com/46939846/89801617-a2050900-db5a-11ea-9672-cc4d6d910f8c.png)

### Seperti apa yang diharapkan?
Sesuai dengan peruntukannya, kolom tersebut adalah Kolom Nama Kecamatan

### Apa yang terjadi?
Agar pengguna saat edit Identitas Desa tidak mengalami kendala saat proses input.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3450
