### ISSUE TITLE
Penambahan Item pilihan pada isian data inventaris 

### ISSUE THREAD

**Issue by gampongbarabung** [OpenSID/OpenSID#3451]
### Bagaimana alurnya sampai muncul masalah?
Karena penyesuian kosa kata berdasarkan pernyataan tentang adat daerah

### Seperti apa yang diharapkan?
Pada Pengisiaan Data Inventaris Tanah, Gedung dan Bangunan perlu ditambahkan 2 isian berikut. 
1.	pada menu Penggunaan : perlu ditambahkan item pilihan Perkebunan dan Pertanian
2.	pada menu Asal Usul : perlu ditambahkan item pilihan Hak Adat dan Hibah 

### Apa yang terjadi?
1. ![Penggunaan Lahan](https://user-images.githubusercontent.com/60224596/89891964-2e1d3c00-dc00-11ea-94ff-8e321e3edf0e.JPG) 
Pada Menu Penggunaan dan Asal Usul tidak ada menu yang tertera pilihan diatas.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.08-pasca
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
@gampongbarabung @Nurhidayat29 , apakah pilihan tambahan itu baku, standar pada semua desa?

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3453
