### ISSUE TITLE
Tambahkan Menu Galery Program Kegiatan

### ISSUE THREAD

**Issue by RomziJazz** [OpenSID/OpenSID#3452]
### Bagaimana alurnya sampai muncul masalah?
Setiap Dana yang masuk ke Desa harus dibuatkan Program dalam APBDesa yang nantinya harus dilaporkan secara transparan kepada Pemerintah dan Warga juga berhak mendapatkan informasi tentang program yang telah dikerjakan sehingga dapat mengevaluasi bentuk hasil pengerjaan program tersebut.

### Seperti apa yang diharapkan?
Opensid diharapkan mampu juga menjadi jembatan Transparansi Program kepada masyarakat melalui menu galery khusus program, yang nantinya juga bisa di padukan dengan peta pengerjaan jika itu fisik.

### Apa yang terjadi?
Masyarakat mengetahui hasil kerja pemerintah desa

### Informasi tambahan 
Menu Galery Program > Dilengkapi dengan Foto dan Driskripsi Singkat kegiatan > Dilengkapi pula dengan titik koordinat peta lokasi pengerjaan

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.08
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Apakah ini sama dengan https://github.com/OpenSID/OpenSID/issues/2543?

Mohon periksa dulu kalau sdh ada yg melaporkan, sebelum membuat issue baru. Terima kasih.

**Comment by eddieridwan** [comment]
Karena issue ini duplikat dari #2543, issue ini akan ditutup. Silakan tambahkan keterangan ke #2543 kalau issue itu masih perlu dilengkapi.
