### ISSUE TITLE
Status Slider Album Galeri ikut Status Slider Artikel

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#3454]
### Bagaimana alurnya sampai muncul masalah?
Saat ini di update terakhir, gambar yang diterapkan untuk slider melalui album galeri tidak akan tampil walau statusnya sudah diaktifkan.

Gambar tersebut akan tampil bila ada 1 artikel yang dimasukkan ke dalam slider pula.
Dengan kata lain, status slider album galeri terpengaruh pada status slider dari artikel.

### Seperti apa yang diharapkan?
Normal sebagaimana mestinya sesuai status slider masing-masing.

### Apa yang terjadi?
Agar status slider album galeri tidak terpengaruh pada status slider artikel.

**Comment by eddieridwan** [comment]
@ariandii maaf kurang jelas. Bisa beri contoh? Dan replikasi di demo?
Saat ini gambar galeri tampil (tapi tidak gambar sampul galeri) di slder, apabila galeri tersebut dipilih. Jika gambar slider diambil dari galeri, tidak ada kaitan dengan artikel sama sekali.

**Comment by ariandii** [comment]
Saat ini saya coba di web demo juga terjadi kendala yang sama pak.
Saat seluruh artikel di keluarkan dari slider, maka gambar slider yang bersumber dari Album Galeri di halaman web tidak akan tampil.

Tadi mungkin bapak coba masih tampil walau artikel sudah dikeluarkan dari slider, karena masih ada artikel statis yang dimasukkan ke slider.

Saya sudah keluarkan semua artikel baik statis maupun dinamis dari pengaturan slider, dan hasilnya Slide Album Galeri tidak tampil.

**Comment by eddieridwan** [comment]
Ok, sekarang mengerti. Terjadi kalau tidak ada artikel yg masuk ke slider di menu atas tema klasik, bukan slider besar.

**Comment by ariandii** [comment]
Begitu pupa dengan slider yang di tengah juga ikut hilang.

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master`.
