### ISSUE TITLE
Hasil cetak dan Unduh Bantuan

### ISSUE THREAD

**Issue by R4HMAT** [OpenSID/OpenSID#3455]
untuk Hasil Cetak di menu bantuan untuk sasaran Pendudukan No, KK tidak muncul kolom NIK dobel dan untuk sasaran bantuan Kepala Kelurga dan Penduduk untuk penerima bantuan tidak bisa muncul  bawha YBS sudah dapat bantuan jika sasaran sama-sama penduduk baru muncul bantuan yg sedang di dapat

Screnshot cetak bantuan sasaran Penduduk
![kirm5](https://user-images.githubusercontent.com/43318683/90139951-3eb9e780-dda3-11ea-9544-0100de5c9091.png)

Screnshot bantuan sasaran penduduk untuk bantuan sedang YBS dapat muncul 
![krm6](https://user-images.githubusercontent.com/43318683/90142000-0b2c8c80-dda6-11ea-89f5-323b6308f454.png)

### Seperti apa yang diharapkan?
Untuk cetak dan Unduk pada Bantuan sasaran Penduduk kolom No. KK ada seperti Bantuan Sasaran Kepala Keluarga.
Screnshotnya
![kirm5](https://user-images.githubusercontent.com/43318683/90140555-1f6f8a00-dda4-11ea-95af-ed7ea123660d.png)

dan Untuk Keterangan Sasaran YBS menerima Bantuan Baik Kepala Keluarga maupun Anggota Kelurga/penduduk bisa muncul keterangan sudah ada bantuan (Sasaran Kepala Kelurga/Kelurga - Penduduk) untuk Bantuan yang sedaang diterima bisa muncul juga dimana di antara kelurga itu kadang Istri/Suami yg atas nama bisa jadi Sasaran di bantuan itu yang di pilih Penduduk. jadinya kelihatan di satau Kelurga itu ada beberapa anggota sudah dapat jadinya kelihatan ketika saat di input datanya.

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.08 Pasca
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
> dan Untuk Keterangan Sasaran YBS menerima Bantuan Baik Kepala Keluarga maupun Anggota Kelurga/penduduk bisa muncul keterangan sudah ada bantuan (Sasaran Kepala Kelurga/Kelurga - Penduduk) untuk Bantuan yang sedaang diterima bisa muncul juga dimana di antara kelurga itu kadang Istri/Suami yg atas nama bisa jadi Sasaran di bantuan itu yang di pilih Penduduk. jadinya kelihatan di satau Kelurga itu ada beberapa anggota sudah dapat jadinya kelihatan ketika saat di input datanya.

@R4HMAT harap beri contoh yg jelas seperti apa yg diinginkan. Dan juga harap konsultasikan ke grup FB untuk mendapat persetujuan pengguna yg lain.

**Comment by R4HMAT** [comment]
Untuk Menu Bantuan yang sasarannya Penduduk untuk menu Cetak dan Unduhnya hasilnya untuk kolom No. KK tidak ada jadi untuk daftar kolom tersebut supaya lengkap untuk kolom KK nya harus ada
contoh seperti ini
![kirm5](https://user-images.githubusercontent.com/43318683/90209094-a78d7800-de14-11ea-9b44-554bd7e83757.jpg)

dan untuk sasaran pada bantuan baik itu penduduk dan Keluarga/Kepala keluarga jika sudah ada data masuk maka dimunculkan bantuan sedang diterima intinya satu no. KK
contoh. seperti ini.
![krm6](https://user-images.githubusercontent.com/43318683/90209315-4a45f680-de15-11ea-8891-df121eed4db7.png)

**Comment by afa28** [comment]
Sedikit informasi: untuk data bantuan sedang diterima yg ditampilkan saat memilih penduduk itu berdasarkan sasaran masing2. Jd jika sasaran penduduk makan bantuan yg diterima hanya akan menampilkan sasaran penduduk tsb bukan keluarganya.

**Comment by R4HMAT** [comment]
maksudnya gini jika sasaran penduduk dipilih, jika dalam 1 kartu kelurga misal point 1. kepala kelurga 2. isteri 3. anak.
dan jika dipilih kepala keluarga bantuan A dapat dan bantuan B istri dapat dan bantuan yang sedang diterima tidak muncul untuk saat sekarang ini seperti itulah penjelasannya.
kalau bisa di dalam 1 kelurga dan/atu satu no. kk itu jika di salah satu anggota dapat maka harus muncul bantuan sedang diterima seperti itu.

**Comment by afa28** [comment]
Untuk cetak/unduh sdah ad di master terbaru.  Sedangkan untuk alur informasi penerima bantuan saat tambah data penerima bantuan bisa dibuatkan issue terpisah.
