### ISSUE TITLE
Tombol Print dan unduh pada C-desa tidak fungsi

### ISSUE THREAD

**Issue by yudhistira4** [OpenSID/OpenSID#3456]
Terdapat error pada tombol **Print** dan **unduh** di daftar persil C -Desa
![persil](https://user-images.githubusercontent.com/65734556/90149509-c527f680-ddae-11ea-9c35-fb6c57f4d6a8.jpg)

- ketika diklik tombol cetak ataupun unduh langsung mengarah ke tab browser baru

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by Nurhidayat29** [comment]
#3333 Tambahkan cetak dan unduh data persil

**Comment by eddieridwan** [comment]
Ditutup karena duplikat.
