### ISSUE TITLE
Cetak Kartu Keluarga error

### ISSUE THREAD

**Issue by Fandha** [OpenSID/OpenSID#3457]
### Bagaimana alurnya sampai muncul masalah?
Pada saat masuk ke modul kependudukan - Keluarga, di halaman data keluarga terdapat menu aksi lainnya yang tidak diperlukan karena pilihannya mengarah ke halaman error.

### Seperti apa yang diharapkan?
Pada halaman tersebut sudah ada menu cetak dan unduh, sehingga sebaiknya menu aksi lainnya dihapus karena tidak diperlukan dan error

### Apa yang terjadi?
Jika menu aksi lainnya dipilih dan cetak, halaman hanya blank. Dan jika menu unduh yang dipilih maka hanya mengunduh file error

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
@Fandha apakah yg dimaksud `Aksi Data Terpilih`? Untuk aksi ini, harus pilih keluarga dulu yg akan di-aksikan. Silakan anda ikut bantu melengkapi panduan supaya jelas.

![aksi-keluarga](https://user-images.githubusercontent.com/249563/90202387-e5909900-de20-11ea-9ee3-2b2ce18a4066.jpg)

**Comment by eddieridwan** [comment]
#3457: Untuk memperjelas, sekarang pilihan Aksi Data Terpilih hanya aktif kalau ada keluarga yg dipilih.

Sdh dicommit ke `master`.
