### ISSUE TITLE
Insert Gambar, Vidio atau Peta Pada Artikel Error

### ISSUE THREAD

**Issue by Zulkarnaimni** [OpenSID/OpenSID#3458]
### Bagaimana alurnya sampai muncul masalah?

Insert Gambar, Vidio atau Peta Pada Artikel Error atau sering muncul Responsive Filemanager Access Denied

### Apa yang terjadi?
![image](https://user-images.githubusercontent.com/64481641/90175414-95d6b100-ddd1-11ea-9160-1adef25c46eb.png)
![image](https://user-images.githubusercontent.com/64481641/90175431-9c652880-ddd1-11ea-9a7c-6f5cd5f960a6.png)
![image](https://user-images.githubusercontent.com/64481641/90175454-a6872700-ddd1-11ea-8ba1-c37c591dfe41.png)
![image](https://user-images.githubusercontent.com/64481641/90175496-b4d54300-ddd1-11ea-8d75-ee497c58c8bb.png)
![image](https://user-images.githubusercontent.com/64481641/90175514-bbfc5100-ddd1-11ea-9cd0-95d5d3d9c281.png)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
Untuk embed video dll silahkan baca panduan.

**Comment by afa28** [comment]
Apa masih bermasalah???

**Comment by Zulkarnaimni** [comment]
Untuk Peta di Insert ke dalam Artikel masih belum bisa tampil Pak @afa28 , sedang untuk Gambar tidak ada masalah lagi 

![image](https://user-images.githubusercontent.com/64481641/94046340-c2331380-fdfa-11ea-9a4c-808a241590d8.png)

**Comment by afa28** [comment]
Buka file desa/config/config.php
Sesuaikan `$config['user_admin'] = 0;` sesuai pentujuk yg disedikan pd komentar tsb. 

Jika pd panduan belum tersedia, mohon bantu u/ melengkapi panduan tsb. https://github.com/OpenSID/OpenSID/wiki
