### ISSUE TITLE
Error logs yang belum hilang

### ISSUE THREAD

**Issue by Zulkarnaimni** [OpenSID/OpenSID#3459]
### Bagaimana alurnya sampai muncul masalah?
Error logs yang masih ada dan selalu muncul

### Apa yang terjadi?
![image](https://user-images.githubusercontent.com/64481641/90186626-a80d1b00-dde2-11ea-8304-c54958765e8e.png)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
@Zulkarnaimni menggunakan versi berapa? Tabel `daa_persil` tidak digunakan lagi di v20.08?

**Comment by Zulkarnaimni** [comment]
Versi 20.08 pasca per 13 Agustus 2020, berarti masih tersimpan dalam system saya Pak, bagaimana cara menghilangkannya supaya tak ada lagi error logs atau kita baikan saja bila tak terganggu system yg lain.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by eddieridwan** [comment]
Kalau teliti mengikuti petunjuk update https://github.com/OpenSID/OpenSID/wiki/Panduan-Update-OpenSID, maka anda tahu bahwa seluruh isi `public_html` atau `ht_docs` perlu dihapus, kecuali folder `desa`. Jadi folder `logs` yg lama juga akan terhapus. 

Sehingga kalau ada file `log` baru, akan yakin isi errornya adalah terkait pada versi yg sedang digunakan.

**Comment by eddieridwan** [comment]
Ok, karena issue ini bukan terkait perubahan sistem, akan ditutup. Silakan buka kembali kalau ada masalah yg memang memerlukan perbaikan aplikasi.

**Comment by Zulkarnaimni** [comment]
Oke Pak Eddie Ridwan, Makasih atas pentunjuknya..

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by Zulkarnaimni** [comment]
Selamat Siang Pak Eddy Ridwan, Terkait masalah logs error kemaren ini masih terjadi (Semua Instruksi dari Pak Eddy Ridwan telah dilaksanakan), hal ini muncul setelah tadi saya update "Cetak Laporan untuk semua dusun/RW/RT", saya lakukan migrasi sempat gagal dua kali, kemudian pada layar juga lagi muncul "PEMBERITAHUAN PEMANTAUAN DARI SERVER" saya klik "OK" Selebarnya tutup, saya lakukan MIGRAD DB keluar error 500 halaman tidak ditemukan, kemudian saya refresh lagi kembali ke halaman awal, saya lakukan lagi dgn meng-klik menu "Migrad DB" muncul lagi "Pengumuman Pemantauan dari server tentang pemantauan penggunaan opensid"  saya jalan kan sama seperti saya lakukan migrad yang pertama, "error 500 lagi" saya refresh ulang lagi , saya jalankan yang ke 3 kali "pada selebar pengumuman pemantau server saya conteng "jangan tampilkankan lagi" saya klik "OK", kemudian saya klik "Migrad DB" baru  sukses" sayang-nya tidak terpikir utuk membuat screensot.

Informasi terkait hanya dapat saya lampirkan log error dan browsing daftar phpmyadmin berikut ini :

![image](https://user-images.githubusercontent.com/64481641/90368083-ba61b000-e093-11ea-8ea7-78cd30a2abfa.png)

Browsing PHPMYADMIN (sudah pernah saya hapus dalam tabel sql, dan sudah saya buang semua system lama saya pasang baru total bukan update atau upgrade ganti release) akan tetapi muncul lagi log itu.
![image](https://user-images.githubusercontent.com/64481641/90368186-eb41e500-e093-11ea-9fc5-225b1c9c2384.png)
![image](https://user-images.githubusercontent.com/64481641/90368360-19272980-e094-11ea-8a64-212773fedc23.png)
