### ISSUE TITLE
[Surat] penambahan Kode bidang masing-masing urusan di nomor surat

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#3461]
### Bagaimana alurnya sampai muncul masalah?
yang sering menjadi persoalan yang kami hadapi di kabupaten lombok timur mengenai penomoran surat terutama di kode bidang masing-masing urusan, yang dimana antara DPMD dengan Kearsipan masih belum satu persepsi
menurut **DPMP** penomoran surat : **Kode Klasifikasi/Nomor Surat/Identitas Desa/Tahun** 
                                          contoh :  **470/001/Ds.RS/2020**
sedangkan menurut Kearsipan penomoran surat : **Kode Klasifikasi/Nomor Surat/kode masing-masing bidang/Tahun** 
                                         contoh :  **470/001/PEM/2020**
                                         contoh :  **470/001/KESRA/2020**
dan lainnya
 
### Seperti apa yang diharapkan?
Disediakan Kolom untuk kode masingmasing bidang di menu Pengaturan surat
![bidang](https://user-images.githubusercontent.com/25834335/90209173-38685180-de1d-11ea-9b22-7e6be8b28d57.jpg)

### Apa yang terjadi?
Penomoran surat tdk seragam
Kesulitan untuk merubah kode tersebut, mengingat harus di edit satu persatu

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by WAHYUDIK** [comment]
> ### Bagaimana alurnya sampai muncul masalah?
> yang sering menjadi persoalan yang kami hadapi di kabupaten lombok timur mengenai penomoran surat terutama di kode bidang masing-masing urusan, yang dimana antara DPMD dengan Kearsipan masih belum satu persepsi
> menurut **DPMP** penomoran surat : **Kode Klasifikasi/Nomor Surat/Identitas Desa/Tahun**
> contoh : **470/001/Ds.RS/2020**
> sedangkan menurut Kearsipan penomoran surat : **Kode Klasifikasi/Nomor Surat/kode masing-masing bidang/Tahun**
> contoh : **470/001/PEM/2020**
> contoh : **470/001/KESRA/2020**
> dan lainnya
> 
> ### Seperti apa yang diharapkan?
> Disediakan Kolom untuk kode masingmasing bidang di menu Pengaturan surat
> ![bidang](https://user-images.githubusercontent.com/25834335/90209173-38685180-de1d-11ea-9b22-7e6be8b28d57.jpg)
> 
> ### Apa yang terjadi?
> Penomoran surat tdk seragam
> Kesulitan untuk merubah kode tersebut, mengingat harus di edit satu persatu
> 
> ### Informasi tambahan
> Tanya	Jawab
> Versi OpenSID	2.x
> Versi PHP	
> System operasi

mungkin pelu juga disertakan peraturan yang dari kearsipan, sehingga temen2 programmer lebih jelas memahaminya

**Comment by eddieridwan** [comment]
Lampirkan peraturan dari DPMD dan Kearsipan, sebagai acuan.

**Comment by mizwaruddin** [comment]
@MUHAMMADRANGSEL Apakah sudah ditemukan landasan hukumnya?

**Comment by andifahruddinakas** [comment]
Sudah bisa disesuaikan di masing2 surat, namun hanya untuk tinymce
