### ISSUE TITLE
>>>>>> Lampiran Upload Gambar Panduan

### ISSUE THREAD

**Issue by Nurhidayat29** [OpenSID/OpenSID#3463]
![menu](https://user-images.githubusercontent.com/51182125/90290108-7ca03400-dea7-11ea-85ec-0ddedcb6223b.png)

**Comment by Galiarta** [comment]
![image](https://user-images.githubusercontent.com/33612251/90300858-1d561a00-decf-11ea-8b64-d22338964d70.png)

**Comment by Nurhidayat29** [comment]
![identitas](https://user-images.githubusercontent.com/51182125/90292752-bc1d4f00-deac-11ea-99ee-bab9f6a62b75.png)
![ubah data desa](https://user-images.githubusercontent.com/51182125/90293642-c50f2000-deae-11ea-9671-44632de748dc.png)
![wilayah desa](https://user-images.githubusercontent.com/51182125/90294575-fa1c7200-deb0-11ea-8642-ae5e4c3d1c6a.png)
![lokasi kantor](https://user-images.githubusercontent.com/51182125/90294787-7d3dc800-deb1-11ea-9223-c541499ab544.png)

**Comment by Nurhidayat29** [comment]
![siagacovid](https://user-images.githubusercontent.com/51182125/90312587-d9473180-df2f-11ea-9b01-a2af130bbbf2.png)

**Comment by Nurhidayat29** [comment]
![dusun](https://user-images.githubusercontent.com/51182125/90317425-ac0c7a80-df53-11ea-9f64-341df4d491ba.png)
![peta dusun](https://user-images.githubusercontent.com/51182125/90317672-402b1180-df55-11ea-8855-ced6e0056811.png)

![tmbahdusun](https://user-images.githubusercontent.com/51182125/90317660-32758c00-df55-11ea-8069-de6ebedb4315.png)
![petadusun](https://user-images.githubusercontent.com/51182125/90318095-3f47af00-df58-11ea-8ce8-5ff41e610e1d.png)

**Comment by Nurhidayat29** [comment]
![Aplikasi](https://user-images.githubusercontent.com/51182125/90521609-f2045100-e194-11ea-993d-00a5a826154a.png)
![rw](https://user-images.githubusercontent.com/51182125/90528199-8d4cf480-e19c-11ea-84b7-53641f7226eb.png)
![rt](https://user-images.githubusercontent.com/51182125/90531736-a061c380-e1a0-11ea-8dff-9724e82c8e05.png)
![tmbahdusun](https://user-images.githubusercontent.com/51182125/90532718-c5a30180-e1a1-11ea-9d97-68a99a84a86c.png)

**Comment by afa28** [comment]
Melakukan PR dengan Github Desktop

![1](https://user-images.githubusercontent.com/57283157/91124377-5493aa80-e6c9-11ea-88ab-862c3d868f6c.JPG)
![2](https://user-images.githubusercontent.com/57283157/91124383-56f60480-e6c9-11ea-9e39-47f664e415e5.JPG)
![3](https://user-images.githubusercontent.com/57283157/91124386-58273180-e6c9-11ea-9b51-c605bff92b63.JPG)
![4](https://user-images.githubusercontent.com/57283157/91124389-59585e80-e6c9-11ea-9688-c5b37ae3a511.JPG)
![5](https://user-images.githubusercontent.com/57283157/91124392-5a898b80-e6c9-11ea-81be-0662139dac5d.JPG)
![6](https://user-images.githubusercontent.com/57283157/91124397-5b222200-e6c9-11ea-88dd-a40cef2a4719.JPG)
![8](https://user-images.githubusercontent.com/57283157/91124399-5c534f00-e6c9-11ea-9eff-5b0cc3ffe033.JPG)
![9](https://user-images.githubusercontent.com/57283157/91124401-5cebe580-e6c9-11ea-95e6-25d2b83a06e2.JPG)
![10](https://user-images.githubusercontent.com/57283157/91124404-5e1d1280-e6c9-11ea-97a4-fe575595f400.JPG)
![11](https://user-images.githubusercontent.com/57283157/91124416-61b09980-e6c9-11ea-8ba1-acb586143cb5.JPG)

**Comment by Nurhidayat29** [comment]
![info sistem](https://user-images.githubusercontent.com/51182125/91642556-7c329c00-ea56-11ea-8ef9-9e96085d6e1a.png)

**Comment by Nurhidayat29** [comment]
![IMG_20200905_164525](https://user-images.githubusercontent.com/51182125/92302642-f5bb1480-ef97-11ea-9c2c-e53593e95ffa.jpg)

**Comment by Nurhidayat29** [comment]
![staf desa](https://user-images.githubusercontent.com/51182125/92996695-b2344d80-f537-11ea-98cf-048dcf610dbe.png)
![pemdes-Recovered](https://user-images.githubusercontent.com/51182125/92996806-86fe2e00-f538-11ea-98d3-142a0b315516.png)
![Sistem Informasi Desa Desa Sebayan 2 - Pengurus - Google Chrome 12_09_2020 20 49 52](https://user-images.githubusercontent.com/51182125/92997294-6637d780-f53c-11ea-824a-9b159e06c982.png)

**Comment by Nurhidayat29** [comment]
![kk baru](https://user-images.githubusercontent.com/51182125/92997741-8ddc6f00-f53f-11ea-9c3a-3ad5d5fa17ad.png)
![kk2](https://user-images.githubusercontent.com/51182125/93000462-dbaea280-f552-11ea-84df-8a8aaccb7b14.png)
![kk3](https://user-images.githubusercontent.com/51182125/93001697-321fdf00-f55b-11ea-9c5b-b70c4600a005.png)
![kk1](https://user-images.githubusercontent.com/51182125/93002190-4665db00-f55f-11ea-80a7-24d580b03895.png)
![tmbhkk](https://user-images.githubusercontent.com/51182125/93002294-339fd600-f560-11ea-929a-220ae8cebf5c.png)

**Comment by Nurhidayat29** [comment]
![rumahtangga](https://user-images.githubusercontent.com/51182125/93003233-2fc38200-f567-11ea-8ff4-acd800cddaa6.png)
![tambhrtg](https://user-images.githubusercontent.com/51182125/93003606-4ddeb180-f56a-11ea-86fc-f4bf60673f7e.png)
![rtg](https://user-images.githubusercontent.com/51182125/93003921-deb68c80-f56c-11ea-8d00-afc2673fff15.png)
![tambhrtg1](https://user-images.githubusercontent.com/51182125/93004246-81700a80-f56f-11ea-8b2b-0cfc9defecae.png)
![ubahrtg](https://user-images.githubusercontent.com/51182125/93004319-0bb86e80-f570-11ea-8ad7-a4d35ab95174.png)
![ubhrtg1](https://user-images.githubusercontent.com/51182125/93004320-0e1ac880-f570-11ea-834e-99d12e0ea626.png)
![Sistem Informasi Desa Desa Sebayan 2 - Keluarga - Form - Google Chrome 13_09_2020 03 21 17](https://user-images.githubusercontent.com/51182125/93004351-46baa200-f570-11ea-848e-f54bcbeb94a1.png)
![unduh](https://user-images.githubusercontent.com/51182125/93004437-2a6b3500-f571-11ea-84c3-03739ff6c9aa.png)
![cetak](https://user-images.githubusercontent.com/51182125/93004438-2b9c6200-f571-11ea-9183-2cd451788002.png)
![rincianrtg](https://user-images.githubusercontent.com/51182125/93004441-2ccd8f00-f571-11ea-99f1-62333071116f.png)
![hapusrtg](https://user-images.githubusercontent.com/51182125/93004462-61414b00-f571-11ea-9860-b1140f7360cb.png)
![tbhrtg1](https://user-images.githubusercontent.com/51182125/93004554-386d8580-f572-11ea-80c8-07d3883f984c.png)
![hapusrtg1](https://user-images.githubusercontent.com/51182125/93004556-3a374900-f572-11ea-8d27-fe29f1b8f861.png)
![rincianrtg1](https://user-images.githubusercontent.com/51182125/93004557-3b687600-f572-11ea-8668-a699cce893ad.png)
![uabhrtghub](https://user-images.githubusercontent.com/51182125/93004598-9f8b3a00-f572-11ea-86d6-d5d94c8e4992.png)

**Comment by Nurhidayat29** [comment]
![rtkk](https://user-images.githubusercontent.com/51182125/93019320-71ecd200-f600-11ea-8761-9e7e0903cad9.png)
![rtmcetak](https://user-images.githubusercontent.com/51182125/93019717-f2143700-f602-11ea-90af-56959c3db5d4.png)
![Sistem Informasi Desa Desa Sebayan 2 - Rtm - Kartu Rtm 3 - Google Chrome 13_09_2020 20 53 25](https://user-images.githubusercontent.com/51182125/93019758-36073c00-f603-11ea-91b8-f8c95a5237a9.png)

**Comment by Nurhidayat29** [comment]
![kelompok](https://user-images.githubusercontent.com/51182125/93021382-77501980-f60c-11ea-8598-d6fa7ddc8678.png)
![tmbhkategori](https://user-images.githubusercontent.com/51182125/93021624-c9de0580-f60d-11ea-8895-82e23eb876cd.png)

![tmbhkateg](https://user-images.githubusercontent.com/51182125/93021580-97cca380-f60d-11ea-82c5-1b759e9a5d58.png)
![kategoriklmpk](https://user-images.githubusercontent.com/51182125/93021761-c4cd8600-f60e-11ea-9817-5bf2804d58cb.png)
![ubahkategklmpk](https://user-images.githubusercontent.com/51182125/93021802-078f5e00-f60f-11ea-822f-733b3ac5b961.png)

![hapuskateg](https://user-images.githubusercontent.com/51182125/93021841-576e2500-f60f-11ea-9e20-7fe1f735c7c9.png)
![carikateg](https://user-images.githubusercontent.com/51182125/93021878-a025de00-f60f-11ea-9d78-c227f17fb96f.png)

**Comment by Nurhidayat29** [comment]
![tmbhkelm](https://user-images.githubusercontent.com/51182125/93022188-feec5700-f611-11ea-8174-487ecbcab1df.png)
![datakel](https://user-images.githubusercontent.com/51182125/93023210-8e483900-f617-11ea-98d6-0dd1a9757725.png)
![ubahrtm](https://user-images.githubusercontent.com/51182125/93023342-791fda00-f618-11ea-94bf-b48d8dd951af.png)
![tmbhrtm](https://user-images.githubusercontent.com/51182125/93024167-9788d400-f61e-11ea-978e-f5d0d7b3d692.png)
![rincianrtm](https://user-images.githubusercontent.com/51182125/93024675-424ec180-f622-11ea-91d9-702611f1d78d.png)

**Comment by Nurhidayat29** [comment]
![statistikpenddk](https://user-images.githubusercontent.com/51182125/93712339-7cb6e200-fb7f-11ea-8c7a-e32e70e5bcdd.png)
![ienisstatistik](https://user-images.githubusercontent.com/51182125/93713408-dcb08700-fb85-11ea-9364-c6a5ca628ca4.png)
![statistikkel](https://user-images.githubusercontent.com/51182125/93713736-fc48af00-fb87-11ea-8260-e4e0303e7924.png)
![statistiktampil](https://user-images.githubusercontent.com/51182125/93713733-f783fb00-fb87-11ea-8443-fe3aad8ec384.png)
![statistikbantuan](https://user-images.githubusercontent.com/51182125/93713734-fa7eeb80-fb87-11ea-92a9-efb9327204df.png)
![tampilstatistik](https://user-images.githubusercontent.com/51182125/93713876-f901f300-fb88-11ea-9684-acdbbcb6fc29.png)
![unduhstat](https://user-images.githubusercontent.com/51182125/93713939-6c0b6980-fb89-11ea-8b94-319d567403b9.png)
![cetakstatistik](https://user-images.githubusercontent.com/51182125/93713940-6dd52d00-fb89-11ea-9496-dbc645c64a03.png)
![statistikgrafik](https://user-images.githubusercontent.com/51182125/93714049-2d29e380-fb8a-11ea-858d-ca21f575f5d7.png)
![statistikpie](https://user-images.githubusercontent.com/51182125/93714052-31ee9780-fb8a-11ea-80e7-a78629489cf6.png)
![statistikpend](https://user-images.githubusercontent.com/51182125/93714193-3f585180-fb8b-11ea-962b-3344eddaabc6.png)

**Comment by Nurhidayat29** [comment]
![surat masuk (1)](https://user-images.githubusercontent.com/51182125/93715871-2d2fe080-fb96-11ea-861f-99e99ca2370c.png)
![surat keluar](https://user-images.githubusercontent.com/51182125/93715872-2ef9a400-fb96-11ea-83f4-4c7ec1825085.png)
![filter surat keluar](https://user-images.githubusercontent.com/51182125/93715984-e42c5c00-fb96-11ea-8523-3656d225e264.png)
![cari surat keluar](https://user-images.githubusercontent.com/51182125/93716111-d1feed80-fb97-11ea-8f54-aadbb7f6033b.png)

**Comment by Nurhidayat29** [comment]
![perdes](https://user-images.githubusercontent.com/51182125/93716413-e6dc8080-fb99-11ea-804d-09231f847665.png)
![aktif sk](https://user-images.githubusercontent.com/51182125/93717480-535a7e00-fba0-11ea-9bf6-697c52ba9e00.png)
![berkassk](https://user-images.githubusercontent.com/51182125/93717481-55244180-fba0-11ea-9463-623fda12ed5c.png)
![web produk hukum](https://user-images.githubusercontent.com/51182125/93717499-69683e80-fba0-11ea-9dca-cdfb3de77552.png)

![sk](https://user-images.githubusercontent.com/51182125/93716414-e8a64400-fb99-11ea-9842-93bfc495d87f.png)
![ubah sk](https://user-images.githubusercontent.com/51182125/93717038-5c961b80-fb9d-11ea-97c9-22b2cef171f6.png)
![cetak sk](https://user-images.githubusercontent.com/51182125/93717039-5e5fdf00-fb9d-11ea-8135-9f73ba08cf63.png)
![hapus sk](https://user-images.githubusercontent.com/51182125/93717040-5f910c00-fb9d-11ea-91ca-1c6bb48de2c0.png)
![hasil sk](https://user-images.githubusercontent.com/51182125/93717041-6029a280-fb9d-11ea-9f55-d9b5dde02420.png)
![tambah sk](https://user-images.githubusercontent.com/51182125/93717043-60c23900-fb9d-11ea-82f5-0299ee0b2182.png)
![isian sk](https://user-images.githubusercontent.com/51182125/93717058-7a638080-fb9d-11ea-85ec-980ba23f1e13.png)
![cari sk](https://user-images.githubusercontent.com/51182125/93717293-1477f880-fb9f-11ea-9695-b64cffe80efd.png)
![unduhsk](https://user-images.githubusercontent.com/51182125/93717346-6ae53700-fb9f-11ea-981c-d1279dd8fbcb.png)

**Comment by ai-skematik** [comment]
![2020-09-24_22h00_12](https://user-images.githubusercontent.com/48144047/94166273-51046680-feb5-11ea-8c83-92aa3eaea253.png)

**Comment by ai-skematik** [comment]
![2020-09-24_22h42_16](https://user-images.githubusercontent.com/48144047/94168895-531bf480-feb8-11ea-8cb2-57a0c12d9e11.png)

![2020-09-24_22h09_33](https://user-images.githubusercontent.com/48144047/94169773-67acbc80-feb9-11ea-8353-acbbd941d4c0.png)

**Comment by ai-skematik** [comment]
![2020-09-24_23h16_13](https://user-images.githubusercontent.com/48144047/94173811-a42ee700-febe-11ea-82e8-6b6b5ffba827.png)

![2020-09-24_23h22_20](https://user-images.githubusercontent.com/48144047/94173974-d80a0c80-febe-11ea-9e79-9ba286f3e2ae.png)

**Comment by ai-skematik** [comment]
![2020-09-24_23h42_36](https://user-images.githubusercontent.com/48144047/94175420-dc372980-fec0-11ea-9270-814c833c3248.png)

![2020-09-24_23h46_24](https://user-images.githubusercontent.com/48144047/94175454-e6592800-fec0-11ea-97fa-6d9238bd7ea3.png)

**Comment by ai-skematik** [comment]
![Cetak_Peta](https://user-images.githubusercontent.com/48144047/94329754-f91a4c80-ffe7-11ea-82af-653fed31104e.png)

![2020-09-26_10h08_00](https://user-images.githubusercontent.com/48144047/94329768-164f1b00-ffe8-11ea-8fbf-6fa0bb57677c.png)

![2020-09-26_10h20_09](https://user-images.githubusercontent.com/48144047/94329881-05eb7000-ffe9-11ea-9ad7-748311f8a247.png)

![2020-09-26_10h25_18](https://user-images.githubusercontent.com/48144047/94329895-23203e80-ffe9-11ea-9f94-5258c2a40c3f.png)

**Comment by ai-skematik** [comment]
![2020-09-28_08h47_07](https://user-images.githubusercontent.com/48144047/94382655-c008e600-0167-11eb-84ff-47e51a548334.png)

![2020-09-26_10h41_05](https://user-images.githubusercontent.com/48144047/94382661-c8f9b780-0167-11eb-8d69-2436aa5cb069.png)

**Comment by ai-skematik** [comment]
![2020-09-28_09h00_10](https://user-images.githubusercontent.com/48144047/94384159-1710ba00-016c-11eb-9d4d-57d447871bfe.png)

![2020-09-28_09h00_42](https://user-images.githubusercontent.com/48144047/94384170-1bd56e00-016c-11eb-8d72-ea044e92e296.png)

![2020-09-28_09h02_24](https://user-images.githubusercontent.com/48144047/94384191-28f25d00-016c-11eb-92e0-5561c0adb34b.png)

![2020-09-28_09h18_30](https://user-images.githubusercontent.com/48144047/94384359-9d2d0080-016c-11eb-8ccd-dd55f583f2c1.png)

![2020-09-28_09h19_27](https://user-images.githubusercontent.com/48144047/94384368-a1f1b480-016c-11eb-8529-d94da6eaf82e.png)

**Comment by muhtar-coder** [comment]
### bagan struktur pemerintah desa

menu info desa
![1](https://user-images.githubusercontent.com/55665526/96156261-11242280-0f3b-11eb-905b-31c3d9ed482e.png)

pemerintah desa
![2](https://user-images.githubusercontent.com/55665526/96156342-27ca7980-0f3b-11eb-9cd5-519b70aab21f.png)

tingkat kades
![3](https://user-images.githubusercontent.com/55665526/96156162-f9e53500-0f3a-11eb-8c31-6c3cdacf186b.png)

tingkat sekretaris desa
![4](https://user-images.githubusercontent.com/55665526/96156490-55afbe00-0f3b-11eb-9b67-24971d9f9feb.png)

tingkat kasi-kasi
![5](https://user-images.githubusercontent.com/55665526/96156523-5e07f900-0f3b-11eb-81c5-2912a3e087bc.png)

tingkat kaur-kaur
![6](https://user-images.githubusercontent.com/55665526/96156576-6eb86f00-0f3b-11eb-9bcd-5995f639a92c.png)

tingkat staf desa
![7](https://user-images.githubusercontent.com/55665526/96156616-77a94080-0f3b-11eb-89eb-ced3a6ed8579.png)

tingkat kepala dusun
![8](https://user-images.githubusercontent.com/55665526/96156652-82fc6c00-0f3b-11eb-91e3-2b4684473da8.png)

**Comment by muhtar-coder** [comment]
*hasil bagan struktur
![bagan](https://user-images.githubusercontent.com/55665526/96160706-86debd00-0f40-11eb-977b-b41b3fa12da3.png)
