### ISSUE TITLE
Perlu penambahan Wilayah Bagian Desa Pada Peta

### ISSUE THREAD

**Issue by RomziJazz** [OpenSID/OpenSID#3464]
### Bagaimana alurnya sampai muncul masalah?
Ada beberapa desa yang mempunyai wilayah desa yang terpisah pisah. Baik dipisah lautan maupun terpisah oleh desa yang lain. Saat ini OpenSid masih menyediakan satu wilayah desa, jika ternyata di lapangan desanya terpecah maka mesti disambung dengan garis batas yang tentunya tidak sesuai dengan peta desa pada kenyataannya.

### Seperti apa yang diharapkan?
Ada menu penambahan wilayah desa.
![20200815_084346](https://user-images.githubusercontent.com/65128302/90302898-a2433280-ded3-11ea-8112-607ed6dc58cf.png)

### Apa yang terjadi?
Wilayah desa terpetakan semua sesuai batas² teritorial masing masing.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by balongbesuk** [comment]
![struk pembayaran](https://user-images.githubusercontent.com/35319600/90471519-b3e14000-e148-11ea-8838-e662ccdfe40b.jpg)

temennya Desa Mojotrisno ni pak :smile:

**Comment by Zulkarnaimni** [comment]
Barang kali lebih kurang seperti menu pilihan pada Wilayah dusun, cuma ini tipe untuk "wilayah bagian desa", karena satu poligon utk satu nama peta.....

**Comment by afa28** [comment]
Duplicate issue https://github.com/OpenSID/OpenSID/issues/2682

**Comment by denis-dst** [comment]
Untuk case ini belum ada cara penyelesaiannya kah para suhu ?kebetulan saya juga mendapati case yg sama, dimana Peta Desa saya ini terpisah jadi ketika membuat satu peta yg satu, yg satu lainnya jadi hilang

![image](https://user-images.githubusercontent.com/61446360/118908255-42d6ef00-b94b-11eb-83fa-3aaa71c0769f.png)

**Comment by ai-skematik** [comment]
Up

**Comment by ai-skematik** [comment]
Di Parigi Moutong ada juga desa seperti ini, 1 desa memiliki 3 wilayah.

**Comment by ai-skematik** [comment]
![Screenshot_20210520_131706.jpg](https://user-images.githubusercontent.com/48144047/118923196-c30e4c00-b96d-11eb-9ab2-fdfe57fdb302.jpg)

**Comment by ai-skematik** [comment]
maps hanya menampilkan 2.,

**Comment by denis-dst** [comment]
Selamat siang pegiat OpenSID
Beberapa waktu lalu saya menemui kendala mengenai setting Peta Wilayah Desa pada aplikasi OpenSID, dimana Desa yang saya garap ini petanya terpisah (Postingan https://www.facebook.com/groups/OpenSID/permalink/1855227534642219/
Kemudian saya coba cari solusinya seperti apa, saya menemukan aplikasi dari Topografix.com (Ketika coba export gpx, terdapat link tersebut) .. dari website tersebut ada aplikasi bernama ExpertGPS, saya coba Install lalu coba gambar petanya dengan hasil sebagai berikut (gambar 1)
Lalu saya coba export Data on Map to Shapefile dan langsung coba import pada aplikasi OpenSID (gambar 2), namun hasilnya belum seperti yang diharapkan, masih ada tanda garis penghubung antara peta satu dengan peta yg lainnya (gambar 3)
Link aplikasi: https://www.expertgps.com/default.asp


![Screenshot_4](https://user-images.githubusercontent.com/61446360/118935421-baba0f00-b975-11eb-8442-df7b85494933.png)
![Screenshot_3](https://user-images.githubusercontent.com/61446360/118935450-c3aae080-b975-11eb-9d39-46dd243a1167.png)

**Comment by apidong** [comment]
Untuk issue ini, perlu dilakukan update frontend maupun backend, Antara lain
-	Penambahan fungsi pada leaflet agar bisa menampilkan lebih dari 1 area.
-	Update form peta wilayah agar bisa menampung lebih dari 1 area.
-	Update backend peta wilayah agar bisa menyimpan lebih dari 1 area.
-	Update frontend pada form peta wilayah area agar bisa menampilkan lebih dari 1 area saat memuat halaman.

**Comment by apidong** [comment]
pak @eddieridwan. saya coba kerjakan untuk issue ini.

**Comment by eddieridwan** [comment]
@apidong , baik. Sdh dicatat di https://github.com/OpenSID/OpenSID/projects/1

**Comment by afa28** [comment]
Ini issuenya pak @Zoel-WB

**Comment by eddieridwan** [comment]
Sdh dicommit ke `rilis-dev` melalui https://github.com/OpenSID/premium/pull/248
