### ISSUE TITLE
[Layanan Mandiri] Untuk fitur layanan mandiri pada saat login user mandiri agar mereka bisa update data mereka sendiri

### ISSUE THREAD

**Issue by Nurdian37** [OpenSID/OpenSID#3466]
### Bagaimana alurnya sampai muncul masalah?
Untuk fitur layanan mandiri pada saat login user mandiri agar mereka bisa update data mereka sendiri gitu

### Seperti apa yang diharapkan?
Agar Mereka bisa melihat data salah dan di perbaiki secara mandiri

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by Nurhidayat29** [comment]
untuk perubahan sebaiknya tetap dilakukan oleh admin, sudh pernh dibahas untuk perubahan data yang dilakukan secara mandiri #791 Layanan Mandiri --> Layanan

**Comment by HerryWanda** [comment]
atau ini solusinya, perlu kita buat notif persetujuan ke admin , jika melakukn perubahan data (update data mandiri) dengan melampirkan dokumen yg sah. contoh KK, KTP, buku nikah, ijazah dll jika ada perubhan yg dilakukan (di upload)

jadi data yg mereka ubah, tidak langsung bergnti nantiknya didatabase atas perubahan yg dilakukan langsung oleh masyarakat melalui  layanan mandiri..

bg @afa28, pak @eddieridwan , apakah seperti diatas bisa kita terapkan..??

jadi nantik, yang menstujui perubahan update data yg dilakukan/dinput ialah administrator.. dengan dasar dokumen yg telah dlampirkan...

ini bisa jadi solusi terkait permintaan issue ini...

jadi peran serta membenahi data melalui layanan mandiri bisa kita berdayakan untum mncapai ke akuratan data.

**Comment by eddieridwan** [comment]
Mungkin untuk tahap percobaan pertama, bisa batasi pada data yg relatif aman untuk diubah oleh warga secara langsung. Kemudian perlu diterapkan proses pencatatan data yg diubah warga, supaya bisa diverifikasi oleh petugas desa.

**Comment by afa28** [comment]
Buatkan 1 table dan folder khusus u/ menyimpan data sementara berupa permintaan warga. Jika permintaan tsb di setujui oleh admin, salin data tsb baik data pd table maupun yg berupa file. Sediakan histori perubahan agar bisa dikembalikan ke data ubahan sebelumnya.

**Comment by alexdam6** [comment]
benar kami juga mengharapkan adanya fitur perbaikan mandiri, namun harus tetap melalui verifikasi minimal sesuai dengan kartu keluarga. Adakalanya kita juga banyak salah ketik ketika input data

**Comment by afa28** [comment]
Issue berkaitan dengan layanan mandiri di lanjutkan setelah issue PR https://github.com/OpenSID/premium/pull/47 atau issue https://github.com/OpenSID/OpenSID/issues/3696 selesai digabung.

**Comment by afa28** [comment]
Alur : 
1. Pengguna layanan mandiri mengubah datanya pd form yg disediakan dan upload bukti jika diperlukan.
2. Ketika disimpan data akan disimpan berupa pesan (mail_box) yg akan dikirim ke admin.
3. Ketika admin membuka mail_box akan di arahkan ke form edit data penduduk berdasarkan penduduk yg mengirim data ubahan tsb.
4. admin memerika data yg dikirikan beserta lampiran yg dikirimkan : jika admin menyimpan (menyetujui) maka otomatim mengirim data berupa pesan data berhasil diubah pd peduduk tsb dan sebaliknya.

**Comment by andifahruddinakas** [comment]
Duplicate of https://github.com/OpenSID/OpenSID/issues/5945
