### ISSUE TITLE
Judul Terpotong saat Bagikan Link.

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#3467]
### Bagaimana alurnya sampai muncul masalah?
Saat membuat artikel dengan Judul mengandung anda petik, maka saat dibagikan ke media sosial judul tersebut terpotong. 

![IMG_20200816_131755](https://user-images.githubusercontent.com/46939846/90328004-19a3bf80-dfc3-11ea-9463-66f46d15c565.jpg)

### Seperti apa yang diharapkan?
Judul normal saat dibagikan.

**Comment by ariandii** [comment]
Berikut link nya, yang mencoba bagikan dengan tombol media sosial yang tersedia di bawah artikel.

https://demo.opensid.my.id/artikel/2020/8/16/tes-bagi-link-artikel-ke-sosial-media-yang-judul-nya-bertanda-petik

**Comment by eddieridwan** [comment]
Sdh dicommit melalui PR #3477

**Comment by ariandii** [comment]
Pada link demo, saat klik bagikan artikel ke facebook. Muncul nya masih terpotong seperti gambar di bawah ini.

![image](https://user-images.githubusercontent.com/46939846/90750881-a4582780-e2ff-11ea-8368-e6ce0ff92733.png)

yang seharusnya menjadi TES BAGI LINK ARTIKEL KE SOSIAL MEDIA YANG "JUDUL NYA BERTANDA PETIK"

**Comment by eddieridwan** [comment]
Sepertinya petik satu sdh bisa, tapi petik dua belum. @masumo bisa lihat lagi?

**Comment by eddieridwan** [comment]
Ternyata masalahnya hanya karena FB. belum melakukan crawl ke artikel itu. Setelah dipaksa melalui https://developers.facebook.com/tools/debug hasilnya sdh benar untuk FB.
