### ISSUE TITLE
Terkait masalah logs error kemaren ini masih terjadi

### ISSUE THREAD

**Issue by Zulkarnaimni** [OpenSID/OpenSID#3469]
Selamat Siang Pak Eddy Ridwan, Terkait masalah logs error kemaren ini masih terjadi (Semua Instruksi dari Pak Eddy Ridwan telah dilaksanakan), hal ini muncul setelah tadi saya update "Cetak Laporan untuk semua dusun/RW/RT", saya lakukan migrasi sempat gagal dua kali, kemudian pada layar juga lagi muncul "PEMBERITAHUAN PEMANTAUAN DARI SERVER" saya klik "OK" Selebarnya tutup, saya lakukan MIGRAD DB keluar error 500 halaman tidak ditemukan, kemudian saya refresh lagi kembali ke halaman awal, saya lakukan lagi dgn meng-klik menu "Migrad DB" muncul lagi "Pengumuman Pemantauan dari server tentang pemantauan penggunaan opensid"  saya jalan kan sama seperti saya lakukan migrad yang pertama, "error 500 lagi" saya refresh ulang lagi , saya jalankan yang ke 3 kali "pada selebar pengumuman pemantau server saya conteng "jangan tampilkankan lagi" saya klik "OK", kemudian saya klik "Migrad DB" baru  sukses" sayang-nya tidak terpikir utuk membuat screensot.

Informasi terkait hanya dapat saya lampirkan log error dan browsing daftar phpmyadmin berikut ini :

![image](https://user-images.githubusercontent.com/64481641/90368083-ba61b000-e093-11ea-8ea7-78cd30a2abfa.png)

Browsing PHPMYADMIN (sudah pernah saya hapus dalam tabel sql, dan sudah saya buang semua system lama saya pasang baru total bukan update atau upgrade ganti release) akan tetapi muncul lagi log itu.
![image](https://user-images.githubusercontent.com/64481641/90368186-eb41e500-e093-11ea-9fc5-225b1c9c2384.png)
![image](https://user-images.githubusercontent.com/64481641/90368360-19272980-e094-11ea-8a64-212773fedc23.png)

_Originally posted by @Zulkarnaimni in https://github.com/OpenSID/OpenSID/issues/3459#issuecomment-674709630_

**Comment by eddieridwan** [comment]
Database anda ada kemungkinan tidak lengkap atau tidak valid. Ini bisa terjadi karena error sebelumnya pada waktu backup/restore/impor/migrasi. Atau juga bisa terjadi kalau database diubah secara manual. Untuk mengatasi perlu diteliti database anda untuk melacak masalahnya. Database yg rusak tidak selalu bisa diperbaiki. 

Kalau anda bersedia donasi pada OpenDesa, bisa kirim backup database anda ke PM. Tetapi seperti dijelaskan di atas, belum tentu dapat diatasi.

**Comment by Zulkarnaimni** [comment]
Berarti dari backup-nya pak, pantas krn kemaren saya malah bukan menggantikan semua systemnya kemudian merestore dan muncul lagi, oke Pak Eddy Ridwan, Makasih banyak informasi dan bantuannya...
