### ISSUE TITLE
[Surat] Penomoran Surat Berdasarkan Klasifikasi

### ISSUE THREAD

**Issue by septiawanti** [OpenSID/OpenSID#3472]
### Bagaimana alurnya sampai muncul masalah?

Di desa kami, Koto Tangah Batu Ampa Kabupaten Lima Puluh Kota penomoran dan pengelompokan Surat cukup berbeda, dimana hingga saat ini Nomor Surat tidak berurutan untuk semua jenis surat ataupun berurutan sendiri2 untuk satu jenis surat yang sama, namun beberapa surat yang dikelompokkan sebagai Surat yang sama dan nomornya berurutan. Sebagai contoh: di desa kami terdapat 4 Jenis Surat Keterangan Tidak Mampu ( SKTM Pendidikan, SKTM BPJS, SKTM Jampersal, SKTM KB, SKTM Akte) dimana jika menggunakan fitur OpenSID tidak dapat disamakan formatnya semisal hanya menambahkan keterangan "Surat Keterangan Ini Dipergunakan Untuk:....."

### Seperti apa yang diharapkan?

Agar OpenSID dapat mengatur penomoran surat otomatis untuk Surat dengan kode klasifikasi yang sama di menu pengaturan surat

### Apa yang terjadi?

Kesulitan mengatur penomoran Surat

### Informasi tambahan 

![image](https://user-images.githubusercontent.com/17079909/90392270-beec8f80-e0b8-11ea-92bb-0a61f219f669.png)

![image](https://user-images.githubusercontent.com/17079909/90392317-d592e680-e0b8-11ea-9ed2-72814e4f7c34.png)

Issue ini juga dibahas pada https://forum.opendesa.id/d/62-penambahan-menu-perkades

**Comment by balongbesuk** [comment]
duplikasi https://github.com/OpenSID/OpenSID/issues/2655

**Comment by andifahruddinakas** [comment]
Duplicate of https://github.com/OpenSID/OpenSID/issues/7087
