### ISSUE TITLE
Perekaman peta persil

### ISSUE THREAD

**Issue by Fandha** [OpenSID/OpenSID#3475]
### Bagaimana alurnya sampai muncul masalah?
Perekaman persil saat ini hanya mencatatkan secara administrasi belum peta persil dalam pemetaan aplikasi. Adapun seperti yang dikerjakan kawan2 saat ini adalah pemetaan melalui menu Pemetaan (Area).

### Seperti apa yang diharapkan?
Dapat melakukan perekaman persil dengan menggunakan titik koordinat atau tagging lokasi dan manual peta pada setiap patok persil seperti lokasi pada saat tagging lokasi kantor yang bisa menggunakan titik koordinat atau tombol tag gps. Dengan demikan bila dilakukan perekaman seperti peta wilayah dapat menampilkan ukuran luas dan panjang sisinya di setiap titik patok persil. Adapun peta persil yang telah direkam dapat ditampilkan di Pemetaan sebagaimana layer desa, dusun, rw dan rt atau infrastruktur desa atau Area, sehingga dapat menampilkan peta persil desa secara keseluruhan. 

### Apa yang terjadi?
Seringnya petugas ukur tidak dapat diganti karena penguasaan lokasi persil, jika lokasi persil telah direkam dapat memudahkan petugas untuk mengetahui posisi persil secara cepat.

### Informasi tambahan 
Peta persil diinput melalui menu data persil di modul pertanahan sehingga lebih rinci tidak melalui modul pengaturan pemetaan.

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Terkait #950

**Comment by afa28** [comment]
Sudah di `rilis-dev`
