### ISSUE TITLE
[Database] Konversi data '', 0, atau - menjadi NULL untuk data table referensi

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#3476]
### Bagaimana alurnya sampai muncul masalah?
Setelah PR #3432 di merge dgn tambahan catatan `Silakan buatkan issue teknis untuk memeriksa impor data penduduk, untuk menjamin data kode kosong ditulis ke database sebagai NULL, supaya tidak lupa. Perhatikan bahwa untuk memudahkan pengguna, kita perlu memperbolehkan pengguna untuk mengimpor data kosong menggunakan '', '0' atau '-'.`

### Seperti apa yang diharapkan?
Data yg diimport berupa '', 0, atau - otomatis terkonversi menjadi NULL untuk data yg menggunakan referensi table.

### Apa yang terjadi?
Memudahkan saat melakukan filtering data statistik penduduk maupun lainnya.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by pandigresik** [comment]
agar mudah dalam pengecekan sebaiknya untuk data yang diperbolehkan menjadi null hanya '' saja, sehingga bisa dicek dengan function empty()
