### ISSUE TITLE
Bantuan sasaran Penduduk Kolom No. KK tidak ada

### ISSUE THREAD

**Issue by R4HMAT** [OpenSID/OpenSID#3479]
### Seperti apa yang diharapkan?

** untuk sasaran penduduk saat sekarang ini di aplikasi kolom No. KK tidak  ada, di hasil cetak dan unduh, untuk kolom 2 (dua) NIK diganti saja dengan NO. KK.
![image](https://user-images.githubusercontent.com/43318683/90722562-43235a80-e2e5-11ea-9040-50f72502e2de.png)

** untuk sasaran penduduk jika di dalam 1 (satu) kelurga dan/atau 1 (satu) No. Kartu Kelurga maka bantuan yang sedang diterima di munculkan dimana supaya mudah mendeteksi kedobelan bantuan yang diterima walaupun beda NIK akana tetapi No .Kartu Kelurga 1 (satu).

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.08 Pasca
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
Sasaran:
1. Penduduk, yg dibandingkan nik agar tdk double
2. Keluarga yg dibandingkan nok_kk agar tdk double
3. RTM yg dibandingkan no_rtm agar tdk double
4. Kelompok yg dibandingkan id_kelompok agar tdk double

Penjelasana:
1. NIK/Nama sebelah kiri digunakan sebagai perbadingan agar dalam 1 program bantuan tdk ada yg double. Dan ditampilkan berdasarkan sasaran, misal sasara penduduk maka yg tampil nik/nama, sasaran keluarga maka yg tampil no_kk/nama_kepala_kk, dst.
2. NIK/Nama/Dll sebelah kanan digunakan untuk menyimpan data peserta (krn biasanya data pd table penduduk berbeda denga data yg ada dilapangan).

Jika ada perubahan alur dr modul program bantuan silahkan lakukan diskusi dengan pengguna lain.

**Comment by eddieridwan** [comment]
Kolom info tambahan, seperti No KK untuk program sasaran Penduduk sdh dicommit ke `master`. 

Mengenai permintaan `untuk sasaran penduduk jika di dalam 1 (satu) kelurga dan/atau 1 (satu) No. Kartu Kelurga maka bantuan yang sedang diterima di munculkan dimana supaya mudah mendeteksi kedobelan bantuan yang diterima walaupun beda NIK akana tetapi No .Kartu Kelurga 1 (satu)`, apakah lebih ditangani pada saat menambah peserta program?

Kalau masih dibutuhkan, harap buat issue baru. Dan juga mohon konsultasikan dengan pengguna lain di forum FB supaya ada kesepakatan.
