### ISSUE TITLE
menampilkan alamat secara lengkap di menu Kelompok

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#3490]
### Bagaimana alurnya sampai muncul masalah?
Menu Kependudukan ==>Kelompok==>Rincian Kelompok==>Data Anggota Kelompok di kolom Alamat, tidak tampil alamat secara lengkap
![kelompok](https://user-images.githubusercontent.com/25834335/90963450-3b80d300-e4ea-11ea-904e-58cdc1e406f7.jpg)

### Seperti apa yang diharapkan?
Di Tampilkan alamat lengkap seperti di menu bantuan
![kelompok1](https://user-images.githubusercontent.com/25834335/90963451-3e7bc380-e4ea-11ea-81fa-bc8b6dea3588.jpg)
### Apa yang terjadi?
alamat tidak tampil secara lengkap

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3493
