### ISSUE TITLE
Tambahkan Kolom Tempat & Tanggal Lahir di Data Anggota Kelompok

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#3491]
### Bagaimana alurnya sampai muncul masalah?
Di Data Anggota Kelompok belum ada kolom Tempat dan Tanggal Lahir, sehingga ketika diminta data Kelompok secara rinci maka perlu input secara manual
![image](https://user-images.githubusercontent.com/25834335/90963943-e72c2200-e4ee-11ea-9d09-8adb43aba65a.png)

dan urutan kolom perlu di sesuaikan lagi menurut saya dengan urutan sbb : 
1. No
2. Nomor Anggota
3. NIK
4. Nama
5. Tempat & Tanggal Lahir
6. Umur
7. Jenis Kelamin
8. Alamat

### Seperti apa yang diharapkan?
Adanya Kolom Tempat dan Tanggal Lahir

### Apa yang terjadi?
jika diminta data secara rinci terutama tempat tanggal lahir, harus input secara manual dan satu persatu

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3493
