### ISSUE TITLE
selalu gagal login

### ISSUE THREAD

**Issue by JanuarSetiana** [OpenSID/OpenSID#3498]
### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by JanuarSetiana** [comment]
login selalu gagal padahal tidad ada perubahan nama user maupun password

**Comment by Nurhidayat29** [comment]
apakah terjadi didemo?

**Comment by afa28** [comment]
Disitus demo tdk ada masalah, jika masih mengalami hal ini silahkan bertanya digroup FB.
