### ISSUE TITLE
[Program Bantuan] Buat opsi dikeluarkan pada program bantuan.

### ISSUE THREAD

**Issue by rullydamara** [OpenSID/OpenSID#3500]
### Bagaimana alurnya sampai muncul masalah?
Saya lihat pada program/menu bantuan belum ada opsi untuk mengeluarkan peserta dari bantuan yang diterima, hanya ada opsi hapus saja.

### Seperti apa yang diharapkan?
Adanya tambahan fitur "dikeluarkan" pada program bantuan, beserta keterangan kenapa ia dikeluarkan  dari program bantuan tersebut dan tanggal dikeluarkan.

Dan diharapkan pada menu bantuan nanti, terdapat filter untuk menampilkan mana yang masih menerima dan tidak menerima bantuan.

### Informasi tambahan 
Dengan adanya fitur ini, akan menambah nilai positif Aplikasi OpenSID dan tentunya akan memudahkan desa pengguna.

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.08-pasca
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
Dari yg sy lihat pd modul program bantuan, skema yg digunakan adalah: setiap ada program bantuan data peserta harus diinput dari awal. Sehingga program bantuan yg memiliki tahapan, seperti BLT tahap 1, 2, dst datanya perlu disalin/dibuat ulang atau bisa menggunakan data lama kemudian hapus data peserta yg tdk diperlukan (tp jika ingin cek data sebelumnya tdk bisa).

Tapi sebaiknya sebelum lanjut mengerjakan issue lain mengenaik program bantuan, mungkin bisa di dahulukan mengerjakan issue #3417 agar tdk berlarut-larut dan semakin rumit kedepannya.

**Comment by feldiamalo13** [comment]
coba untuk tambahkan tabel untuk list orang2 yang dikeluarkan menggunakan
fungsi update dan delete kondisi ssuai ID

Pada tanggal Rab, 26 Agu 2020 pukul 08.45 Rully Damara <
notifications@github.com> menulis:
