### ISSUE TITLE
Perlu Perbaikan NIK tidak terbuka normal pada hasil unduhan data suplemen

### ISSUE THREAD

**Issue by muhtar-coder** [OpenSID/OpenSID#3501]
### Bagaimana alurnya sampai muncul masalah?
File unduhan data suplemen no NIK nya tidak terbuka secara normal dan tidak ada pamong penanda tangan di kolom bawah data pada menu cetak langsung.

contoh gambar nik tidak sempurna : 
![image](https://user-images.githubusercontent.com/55665526/91258996-cdf9ce80-e797-11ea-8e9b-9c903d92c67f.png)

contoh gambar jika tersedia penanda tangan pamong : 
![image](https://user-images.githubusercontent.com/55665526/91259335-7f98ff80-e798-11ea-9c33-18a48c60bc82.png)

### Seperti apa yang diharapkan?

1. NIK dapat terbuka secara normal pada file excel hasil unduhan.
2. Agar dapat di sediakan pamong penanda tangan di bawah data sehingga ketika menggunakan fitur cetak langsung dapat 
    tertera penanda tangan pamong/kepala desa

### Apa yang terjadi?

Data cetak yang di hasilkan dapat tersaji sempurna dan baik

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.08 pasca
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3501
