### ISSUE TITLE
bug cetak surat penghasilan orangtua

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#3503]
### Bagaimana alurnya sampai muncul masalah?
cetak surat penghasilan orang tua > isi data

### Seperti apa yang diharapkan?
data ibu terisi data sesuai kartu keluarga

### Apa yang terjadi?
data ibu tidak terisi sesuai kartu keluarga / orang lain

### Informasi tambahan 

sudah d test di website demo

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by balongbesuk** [comment]
![assadasdas](https://user-images.githubusercontent.com/35319600/91374737-115d4700-e843-11ea-89ff-e7e5a533d7ad.jpg)

**Comment by balongbesuk** [comment]
ini juga berpengaruh pada surat ket untuk nikah

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3540
