### ISSUE TITLE
Perlu dibuatkan combobox filter sasaran pd modul suplemen

### ISSUE THREAD

**Issue by afa28** [OpenSID/OpenSID#3504]
### Bagaimana alurnya sampai muncul masalah?
Saat ini modul suplemen belum ada combobox filter sasasaran.

![1111](https://user-images.githubusercontent.com/57283157/91412872-8c8b2100-e874-11ea-882b-4009ae1ac917.JPG)

### Seperti apa yang diharapkan?
Perlu filter sasaran seperti di modul program_bantuan

### Apa yang terjadi?
Agar bisa memfilter berdasarkan sasaran

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3505
