### ISSUE TITLE
Ubah Sasaran Suplement

### ISSUE THREAD

**Issue by afa28** [OpenSID/OpenSID#3506]
### Bagaimana alurnya sampai muncul masalah?
Setelah menginput data terdata yg ada di suplement, saat melakukan edit data suplement masih tersedia ubah sasaran. Sehingga jika sasaran diubah, misal dari sasaran penduduk ke keluarga, data yg pernah diinput akan rancuh.

### Seperti apa yang diharapkan?
Hilangkan/disable pilih sasaran jika jumlah data terdata > 0.

### Apa yang terjadi?
Data suplemen terdata sasarannya tdk bisa diubah jika sudah ada data terdata > 0

### Informasi tambahan 
Contoh Modul program bantuan.

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3507
