### ISSUE TITLE
Logo dan Nama Desa tidak muncul pada salah satu Menu di Halaman Mandiri. 

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#3508]
### Bagaimana alurnya sampai muncul masalah?

Saat login halaman mandiri dan berada pada menu https://demo.opensid.my.id/mandiri_web/mandiri_surat
Header menampilkan Logo OpenSID dan Hanya sebutan Desa. (Perhatikan Pojok Kiri Atas).

![image](https://user-images.githubusercontent.com/46939846/91579584-0d7e1180-e976-11ea-98e7-94d790feb4f9.png)

### Seperti apa yang diharapkan?
Seharusnya logo sesuai dengan logo desa dan Nama Desa juga muncul.

Seperti halnya pada menu lain. (Perhatikan Pojok Kiri Atas).

![image](https://user-images.githubusercontent.com/46939846/91579738-44542780-e976-11ea-98c3-6308850714d7.png)

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3509
