### ISSUE TITLE
Fitur Pencarian pada Rincian Data Suplemen

### ISSUE THREAD

**Issue by hasap86** [OpenSID/OpenSID#3511]
### Bagaimana alurnya sampai muncul masalah?
Tidak ada fitur pencarian data pada Rincian Data Suplemen

### Seperti apa yang diharapkan?
dibuatkan fitur pencarian data untuk mempermudah pencarian data

### Apa yang terjadi?
diharapkan dengan adanya fitur pencarian menjadi mempermudah

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | demo
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
Sy hapus assignment dlu, spa tau ada yg berminat krjakan.

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3647
