### ISSUE TITLE
[premium] Sediakan fitur pengaturan bagan dekat dengan menu/fitur bagan

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#3512]
### Bagaimana alurnya sampai muncul masalah?
Saat ini pengaturan lebar bagan struktur organisasi ada di Pengaturan Halaman Web. Ini kurang tepat, karena bagan juga ditampilkan di Admin. Dan juga terlalu jauh dari fitur yg diatur itu.

![pengaturan-bagan-0](https://user-images.githubusercontent.com/249563/91628206-dacd2b00-ea00-11ea-87c6-958e759406b8.jpg)

### Seperti apa yang diharapkan?
Disediakan akses ke pengaturan bagan dekat dengan menu/fitur bagan itu sendiri.

![pengaturan-bagan-1](https://user-images.githubusercontent.com/249563/91628210-e4ef2980-ea00-11ea-9842-9b9860e32449.jpg)

![pengaturan-bagan-2](https://user-images.githubusercontent.com/249563/91628212-e7518380-ea00-11ea-92c4-d0fa838ba723.jpg)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | v20.09
| Versi PHP        | 
| System operasi   |

**Comment by fusionid** [comment]
Sudah diupdate di https://github.com/OpenSID/premium/commit/39c3960615111eab2370448a64b7e6938ac6cda7

**Comment by eddieridwan** [comment]
Sdh dicommit ke `rilis`.
