### ISSUE TITLE
Perlu Perbaikan Format Data Cetak Pelaporan Kematian Yang Sesuai dan Lengkap

### ISSUE THREAD

**Issue by muhtar-coder** [OpenSID/OpenSID#3513]
### Bagaimana alurnya sampai muncul masalah?

1. Formulir cetak langsung laporan kematian belum ada keterangan "penyebab sakit" dan "tanggal kematian"
2. Tidak tersedia penanda tangan pamong pada bagian bawah data cetak laporan kematian.

### Seperti apa yang diharapkan?

Data cetak laporan dapat tercetak dan tersaji dengan baik,rapih serta sesuai dengan format laporan yang di minta kecamatan dan puskesmas.

contoh gambar yang sekarang dan harapan penambahan kolom keterangan tambahan

![image](https://user-images.githubusercontent.com/55665526/91639957-86e43580-ea44-11ea-93f3-ee23c8b6adc4.png)

### Apa yang terjadi?
 
Laporan kematian versi OpenSID mantaf jiwa....

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.08 pasca
| Versi PHP        | 
| System operasi   |

**Comment by Nurhidayat29** [comment]
@2859 Ubah Status Dasar menjadi Mati
bsa dgbung dngn issue ini

**Comment by muhtar-coder** [comment]
terima kasih opensid  laporan cetak kematian sudah lengkap
