### ISSUE TITLE
Perlu Perbaikan Jumlah Karakter yang muncul pada judul informasi pada menu produk hukum agar tidak dibatasi

### ISSUE THREAD

**Issue by mah-mudi** [OpenSID/OpenSID#3514]
### Bagaimana alurnya sampai muncul masalah?
Jumlah Karakter yang muncul pada judul informasi pada menu produk hukum dibatasi tidak lebih dari 50 karakter.

### Seperti apa yang diharapkan?
Jumlah Karakter yang muncul pada judul informasi pada menu produk hukum tidak dibatasi.
![KARAKTER JUDUL INFORMASI PADA PRODUK HUKUM DIBATASI](https://user-images.githubusercontent.com/57661283/91679223-df652100-eb71-11ea-8f17-47072f013a75.png)

### Apa yang terjadi?
Standar Informasi Publik Desa semakin baik pada OpenSID

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.08-pasca
| Versi PHP        | 7.4.9
| System operasi   |

**Comment by afa28** [comment]
Nama/Judul informasi yg ditampilkan berdasarkan hasil input pada admin. Tdk ada pemotongan karakter saat ditampilkan. Jd cuma perlu ditambahkan batas karater input nama tsb.

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3518

**Comment by mah-mudi** [comment]
terima kasih
