### ISSUE TITLE
form kode barang di menu Infentaris

### ISSUE THREAD

**Issue by rensingbat** [OpenSID/OpenSID#3516]
### Bagaimana alurnya sampai muncul masalah?
Ketika ingin membuat infentaris barang seperti printer, komputer dan barang lainnya tidak ada form yang berisi nama barang tersebut

### Seperti apa yang diharapkan?
Perlu ada form nama barang yang isinya adalah pilihan nama barang seperti komputer, laptop, printer, kursi, meja, lemari, aset milik desa seperti tanah desa, motor, mobil dan barang-barang lainnya

### Apa yang terjadi?
memudahkan pendataan di desa ketika melakukan laporan ke daerah

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by masumo** [comment]
![image](https://user-images.githubusercontent.com/19631687/92328477-4c554b00-f08b-11ea-99b4-0df8a09836c8.png)

sudah ada isian kode/jenis barang di kolom **Kode Barang**

**Comment by mizwaruddin** [comment]
@afa28 bisa diclose.

**Comment by rensingbat** [comment]
Ok terimakasih, sy sudah melihatnya, seperti itu yang kami harapkan,
terimakasih programer opensid

Pada tanggal Jum, 1 Jan 2021 12:19, Andi Fahruddin Akas <
notifications@github.com> menulis:
