### ISSUE TITLE
Rilis Primium Bug pada Fitur Buku Administrasi Desa pada Menu Buku Administrasi Lainnya

### ISSUE THREAD

**Issue by Zulkarnaimni** [OpenSID/OpenSID#3517]
![image](https://user-images.githubusercontent.com/64481641/91799484-59200c00-ec51-11ea-877c-a016eae32ff0.png)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
Hanya buku administrasi umum yg sdah selesai. Untuk yg lain masih dalam pengerjaan dan sudah ditambahkan info dibagian tsb.
