### ISSUE TITLE
menampilkan poto penduduk di log penduduk

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#3519]
### Bagaimana alurnya sampai muncul masalah?
Menu Kependudukan==>Penduduk==>Pilih Aksi Lainnya==>Log Penduduk, perlu ditambahkan kolom poto menggingat di Keluarga dan di Penduduk poto sudah ditampilkan, supaya bagi desa yang sudah memasukkan poto bisa mengetahui secara jelas siapa yang meninggal, pindah dll

### Seperti apa yang diharapkan?
Adanya Tambahan kolom poto di log penduduk seperti di penduduk dan keluarga
![log penduduk](https://user-images.githubusercontent.com/25834335/91879088-80f38c00-ecb2-11ea-9fd3-dedce0867e62.png)
### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by masumo** [comment]
izin saya kerjakan issue ini

**Comment by eddieridwan** [comment]
@masumo silakan, sdh saya assign.

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3548
