### ISSUE TITLE
[Penduduk] Ubah Status dasar perlu ditambahkan pilihan Ganda

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#3520]
### Bagaimana alurnya sampai muncul masalah?
Mengingat banyaknya Data Penduduk maupun Keluarga Ganda, maka perlu ditambahkan pilihan GANDA di Ubah Status Dasar sehingga data yang sudah masuk di OpenSID tidak serta merta di Hapus namun bisa diarsipkan di Log Penduduk, ini semua untuk mengantisipasi kedepannya ketika data warga masyarakat sudah di perbaiki namun ketika membuat surat layanan masih membawa KK yang masih salah.

![status ganda](https://user-images.githubusercontent.com/25834335/91881503-2c511080-ecb4-11ea-8945-914ff5d41b03.png)

### Seperti apa yang diharapkan?
Supaya Data yang GANDA di arsipkan dengan baik di Log Penduduk.
Supaya Data Ganda yang sudah diarsipkan di Log Penduduk tidak bisa di entry lagi

![ganda](https://user-images.githubusercontent.com/25834335/91881527-3541e200-ecb4-11ea-90bf-36383932a914.png)

### Apa yang terjadi?
Sering kali masyarakat membawa KK yang salah ketika membuat surat

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by andifahruddinakas** [comment]
Sekrang NIK dibuat unik sehingga data ganda tdk bisa masuk lg.
