### ISSUE TITLE
Data di Daftar Terdata Suplemen ikut terhapus

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#3522]
### Bagaimana alurnya sampai muncul masalah?
Ketika menghapus Data Suplemen  semua Data di Daftar Terdata Suplemen ikut terhapus,
![image](https://user-images.githubusercontent.com/25834335/91883529-26106380-ecb7-11ea-96a5-a9379797a3a2.png)

![image](https://user-images.githubusercontent.com/25834335/91883550-2c9edb00-ecb7-11ea-8bf0-d24e43ea737c.png)

### Seperti apa yang diharapkan?
Ketika Sudah ada data di Daftar Terdata Suplemen maka tidak bisa menghapus Data Suplemen kalau belum menghapus semua Data di Daftar Terdata Suplemen

### Apa yang terjadi?
Data yang sudah dimasukkan semua terhapus

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3525
