### ISSUE TITLE
Tampilkan data di Menu Bantuan Tidak berfungsi

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#3523]
### Bagaimana alurnya sampai muncul masalah?
Ketika merubah Tampilkan data dari 20 ke 50 dari 50 ke 100, fitur tersebut tidak berfungsi
![image](https://user-images.githubusercontent.com/25834335/91883936-c23a6a80-ecb7-11ea-93f9-c2191a253f4e.png)

### Seperti apa yang diharapkan?
Tampilkan data berfungsi normal seperti rilis sebelumnya

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3526
