### ISSUE TITLE
Data Identitas Desa untuk Kepala Desa & NIP di ambil dr modul Pemerintah Desa

### ISSUE THREAD

**Issue by Zulkarnaimni** [OpenSID/OpenSID#3524]
![image](https://user-images.githubusercontent.com/64481641/91910957-3be35000-ecda-11ea-81f3-0aae78dd1a1b.png)

### Bagaimana alurnya sampai muncul masalah?
Pada saat di Export Nama "Kepala Desa Tidak Masuk" Pada Tempat Tanda Tangan, masih dari bawaan system aslinya

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
Coba di vesi demo, gunakan template bawaan terbaru.

**Comment by Zulkarnaimni** [comment]
[cid:image003.png@01D68109.DCA9C290]

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by Zulkarnaimni** [comment]
Sama Pak Andi di Demo juga tidah beribah :
![image](https://user-images.githubusercontent.com/64481641/91924749-b7a2c400-ecfd-11ea-9ac3-19c926c09b82.png)

**Comment by eddieridwan** [comment]
Masalah ini disebabkan ttd di lampiran diambil dari `Info Desa > Identitas Desa > Kepala Desa`, karena hanya di situ diketahui siapa yg berperan sebagai kepala desa. Jabatan di `Info Desa > Pemerintahan Desa` tidak bisa digunakan karena diisi bebas, dan sebutan untuk 'kepala desa' bisa bermacam-macam (seperti Wali Nagari di Sumatera Barat). 

Masalahnya adalah karena `Info Desa > Identitas Desa > Kepala Desa` diisi manual, sehingga tidak sinkron dengan `Info Desa > Pemerintahan Desa`.

Salah satu solusi:
1. Ubah pengisian `Info Desa > Identitas Desa > Kepala Desa` supaya hanya bisa memilih dari staf pemerintahan desa yang sudah dimasukkan di `Info Desa > Pemerintahan Desa` .

**Comment by Zulkarnaimni** [comment]
Iya Pak Eddie Ridwan, sorri banget kemaren setelah uji coba ada temuan sudah langsung masukkan issue, mohon maaf Pak.
*****
Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by afa28** [comment]
> @afa28 @Zulkarnaimni Masalah ini disebabkan ttd di lampiran diambil dari `Info Desa > Identitas Desa > Kepala Desa`, karena hanya di situ diketahui siapa yg berperan sebagai kepala desa. Jabatan di `Info Desa > Pemerintahan Desa` tidak bisa digunakan karena diisi bebas, dan sebutan untuk 'kepala desa' bisa bermacam-macam (seperti `Wali Nagari` di Sumatera Barat).
> 
> Masalahnya adalah karena `Info Desa > Identitas Desa > Kepala Desa` diisi manual, sehingga tidak sinkron dengan `Info Desa > Pemerintahan Desa`.
> 
> Salah satu solusi:
> 
> 1. Ubah pengisian `Info Desa > Identitas Desa > Kepala Desa` supaya hanya bisa memilih dari staf pemerintahan desa yang sudah dimasukkan di `Info Desa > Pemerintahan Desa` .

Ya, mungkin sulusi bisa dipakai cara di atas. Dan mungkin jug perlu ditambahkan : perlu dibuatkan 1 table yg menyimpan semua referensi mengenai jabatan, misal pengurus, kelompok, dll. Agar lebih mudah saat memilih jabatan tanpa harus input manual dan bisa ditambah sesuai kebutuhan.

**Comment by afa28** [comment]
Perlu diubah cara penanda tangan untuk surat, krn sdah berbeda dgn versi sebelumnya.

![11111111](https://user-images.githubusercontent.com/57283157/95949821-b1842500-0e1d-11eb-81ef-5faf9424afe5.JPG)

Jadi hanya perlu ada 3 Pilihan penanda tangan (Tertanda Atas Nama), yakni : 
1. Kepala desa yg diambil dari identitas desa (data kepala desa diambil dari pemerintah desa)
2. An. yg diambil dari pemerintah desa
3. Ub.  yg diambil dari pemerintah desa

Sedangkan untuk pilihan staf pemerintah dan menjadbat sebagai akan terisi otomatis sesuai dengan pengaturan An. dan Ub yg ada di modul pemerintah desa.

**Comment by afa28** [comment]
> Perlu diubah cara penanda tangan untuk surat, krn sdah berbeda dgn versi sebelumnya.
> 
> ![11111111](https://user-images.githubusercontent.com/57283157/95949821-b1842500-0e1d-11eb-81ef-5faf9424afe5.JPG)
> 
> Jadi hanya perlu ada 3 Pilihan penanda tangan (Tertanda Atas Nama), yakni :
> 
> 1. Kepala desa yg diambil dari identitas desa (data kepala desa diambil dari pemerintah desa)
> 2. An. yg diambil dari pemerintah desa
> 3. Ub.  yg diambil dari pemerintah desa
> 
> Sedangkan untuk pilihan staf pemerintah dan menjadbat sebagai akan terisi otomatis sesuai dengan pengaturan An. dan Ub yg ada di modul pemerintah desa.
> 
> Dan perlu di sesuaikan jg, jika data kepala desa yg ada di identitas desa diambil dari modul pemerintah desa maka data kepala desa tsb yg ada di modul pemeintah desa tombol An. dan Ub. di hilangkan.

Krn saat ini walaupun sudah dipilih yg An dan Ub pada modul pemerintah desa yg bisa bertanda tangan untuk cetak surat, saat ini masih bisa mengganti An. dan Ub saat mencetak surat tsb krn tersedia pilihan.

**Comment by Zulkarnaimni** [comment]
Barusan saya coba kembali, tetap tidak berubah pada lampiran "surat_bio_penduduk_1108042506910001_2020-10-15_6_lampiran.pdf", saya coba cari rupanya data dalam tabel "tweb_desa_pamong" nya masih data bawaan master opensid desa "singgi1"
 Gambar 1 Tabel tweb_desa_pamong
![image](https://user-images.githubusercontent.com/64481641/96026510-c80f9800-0e80-11eb-8cb8-3bb4fc61a470.png)
![image](https://user-images.githubusercontent.com/64481641/96026556-d9f13b00-0e80-11eb-9183-407ac01253d2.png)

Gambar 2 Tabel tweb_desa_pamong
![image](https://user-images.githubusercontent.com/64481641/96026632-f3928280-0e80-11eb-8ae1-23dd87b30a30.png)
![image](https://user-images.githubusercontent.com/64481641/96026657-01e09e80-0e81-11eb-8e2b-e43e9ed85a93.png)

Gambar 3 Seharusnya berubah menjadi :
![Uploading image.png…]()

**Comment by eddieridwan** [comment]
Sdh dicommit ke `rilis-dev` melalui https://github.com/OpenSID/premium/pull/122
