### ISSUE TITLE
PENDUDUK PENDATANG TIDAK MUNCUL SAAT CETAK KK

### ISSUE THREAD

**Issue by kasipembts** [OpenSID/OpenSID#3527]
### Bagaimana alurnya sampai muncul masalah?
Pada saat memasukkan penduduk yang berstatus pendatang ke Kartu keluarga, tidak muncul saat mencetak KK

### Seperti apa yang diharapkan?
agar penduduk berstatus penduduk pendatang bisa muncul atau tercetak di kk

### Apa yang terjadi?
penduduk pendatang tidak muncul

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.09
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
@kasipembts , anggota KK harus penduduk tetap. Jadi pendatang yg ditambahkan ke KK perlu diubah statusnya menjadi penduduk tetap.

**Comment by eddieridwan** [comment]
Pilihan solusi untuk issue ini :
1. Pada waktu menambah anggota baru ke KK, batasi hanya pilihan penduduk dengan status tetap. Atau
2. Pada waktu menambah anggota baru ke KK, sediakan pilihan semua penduduk lepas (yaitu yg bukan anggota KK). Kemudian kalau ditambahkan, ubah status penduduknya secara otomatis menjadi penduduk tetap.

Yg lebih tepat sesuai pengertian administrasi desa, adalah pilihan (1). Karena seharusnya penduduk pendatang atau tidak tetap tidak dimasukkan ke dalam KK di desa ybs. Yaitu ubah dulu status penduduk yg akan ditambahkan menjadi tetap dulu. 

Kasus menambah anggota KK biasanya karena: kelahiran baru, famili yg ikut KK, nikah. Semua kasus tersebut menyangkut penduduk tetap.

**Comment by eddieridwan** [comment]
@kasipembts @yonathanrizky lihat pembahasan di https://www.facebook.com/groups/OpenSID/permalink/1644112252420416/, yg memberi konfirmasi solusi (1) adalah yg benar. Penduduk yg statusnya tidak tetap harus diubah statusnya dulu menjadi tetap, dengan berbukti Surat Keterangan Domisili, sebelum bisa masuk ke KK.

**Comment by kasipembts** [comment]
Terimakasih atas pencerahannya pak, sangat membantu dan mendapat pengetahuan baru tentang administrasi desa, terimakasih

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3539
