### ISSUE TITLE
[Bumindes] Perlu Penambahan Aksi Posisi Atas dan Posisi Bawah pada menu Informasi Publik 

### ISSUE THREAD

**Issue by mah-mudi** [OpenSID/OpenSID#3528]
### Bagaimana alurnya sampai muncul masalah?
Belum adanya tombol Aksi Posisi Atas dan Posisi Bawah pada menu Informasi Publik sehingga kurang efektif untuk menampilkan informasi publik yang terbaru dikarenakan terkendala pada urutan nomer sesuai tanggal upload.
![1 PENAMBAHAN AKSI TOMBOL PINDAH ATAS BAWAH PADA PRODUK HUKUM](https://user-images.githubusercontent.com/57661283/91937192-9f41a200-ed1b-11ea-9178-a4d3e04b91dd.png)

### Seperti apa yang diharapkan?
Tersedianya adanya tombol Aksi Posisi Atas dan Posisi Bawah pada menu Informasi Publik seperti gambar dibawah ini.
![PENAMBAHAN AKSI TOMBOL PINDAH ATAS BAWAH PADA PRODUK HUKUM](https://user-images.githubusercontent.com/57661283/91937247-b54f6280-ed1b-11ea-941e-a38289315e1b.png)

### Apa yang terjadi?
Menu Informasi Publik pada OpenSID semakin baik.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.09-pasca
| Versi PHP        | 7.4.9
| System operasi   |

**Comment by eddieridwan** [comment]
@mah-mudi Sebaiknya diurut berdasarkan apa?

**Comment by mah-mudi** [comment]
@eddieridwan berdasarkan tanggal diundangkan/ditetapkan pak. Bukan diurut berdasarkan tanggal upload/tanggal muat.

**Comment by balongbesuk** [comment]
ooo tanggal uploadnya bisa di custom pak eddie, kl  dibuat panah atas bawah jadi aneh karena tabel informasi publik sudah ada sortirnya, sy cek memang tidak bisa d custom untuk tanggal uploadnya

**Comment by mah-mudi** [comment]
@balongbesuk boleh juga itu tgl uploadnya bisa di custom :-). 
Jadi Tanggal Upload bisa disesuaikan dg tanggal ditetapkannya/diundangkannya produk hukum. :-)

**Comment by HerryWanda** [comment]
Ini kan didalam admin web,..
kalo pada menu statis web bisa (terdahulu ke baru, baru ke terdahulu) dibgian tahun.

apa kah udah mencoba memasukkan menu statis infornasi publik pada web??

kalo di admin, klo ditmbahan berdsrkn issue ini.. juga bagus..

**Comment by afa28** [comment]
Sebaiknya tgl_upload dokumen sj yg bisa di costume dan diurutkan berdasarkan tgl_upload teraru.

**Comment by mah-mudi** [comment]
@afa28  betul :-)
