### ISSUE TITLE
Bug? Error eksport import data penduduk

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#3529]
### Bagaimana alurnya sampai muncul masalah?
1. pengaturan > eksport database > download Ekspor Data Penduduk (Format .xls untuk di impor ke database SID melalui menu Impor Database) > simpan 

2. pengaturan > import database > upload file yang tadi di download

3. tekan tombol import data pendduk > terjadi error "The filename /tmp/phppXSc9E is not readable"

### Seperti apa yang diharapkan?
bisa mengimpor data yang di download

### Apa yang terjadi?
tidak bisa mengimpor data yang di download

### Informasi tambahan 

sudah di tes d localhost dan terjadi jg di website demo

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
@balongbesuk -- file hasil ekspor perlu dibuka menggunakan Excel dan di-save lagi menggunakan format Excel 2003. Baru bisa diimpor lagi. Sdh lama ada di panduan: https://github.com/OpenSID/OpenSID/wiki/Error-Import-Excel 

Opsi solusi teknisnya mungkin sbb:
1. Gunakan library PHP untuk Excel lebih kini 
2. Lakukan ekspor/impor data menggunakan format CSV yg lebih stabil, tidak tergantung versi.
