### ISSUE TITLE
Perlu penambahan logo disebelah kanan saat cetak surat

### ISSUE THREAD

**Issue by x1syah** [OpenSID/OpenSID#3530]
### Informasi tambahan 
Perlu ditambahkan logo disebelah kanan untuk cetak surat, karena utk memasukkan logo saat saat menjelaang ulang tahun kemerdekaan atau ultah kabupaten kop surat harus diwajibkan ada logo tersebut selain logo dari desa itu sendiri

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        |  7
| System operasi   | Windows 10

**Comment by afa28** [comment]
Silahkan ubah template suratnya

**Comment by mizwaruddin** [comment]
@afa28 bisa di close.
