### ISSUE TITLE
Tampilkan rumusan pokok IDM

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#3531]
### Bagaimana alurnya sampai muncul masalah?
idm.kemendesa.go.id menyediakan API yg memberi status rumusan pokok IDM. Sebagai contoh, url https://idm.kemendesa.go.id/open/api/desa/rumusan/3507012006/2020 mengembalikan rumusan pokok IDM 2020 untuk Desa Donomulyo di Kab Malang.

Ada peluang untuk menampilkan rumusan tersebut di modul Admin dan juga di Web sebagai informasi bagi pemerintahan desa dan warga mengenai status perjalanan desa menjadi mandiri -- dan sebagai informasi untuk perencanaan pengembangan desa selanjutnya. 

### Seperti apa yang diharapkan?
Ada fitur untuk menampilkan rumusan pokok IDM di modul Admin dan ada halaman statis untuk data tersebut yg bisa ditampilkan melalui menu statis di web.

### Informasi tambahan 

Contoh data json yg dihasilkan oleh API di atas:
[rumusan-idm-2020.json.zip](https://github.com/OpenSID/OpenSID/files/5165696/rumusan-idm-2020.json.zip)

Contoh tampilan rumusan pokok di idm.kemendesa.go.id:

![image](https://user-images.githubusercontent.com/249563/92062960-49cdc980-eddd-11ea-95e1-3e1b97dadc34.png)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | v20.09
| Versi PHP        | 
| System operasi   |

**Comment by af-lazuardi** [comment]
https://idm.kemendesa.go.id/open/api/desa/rumusan/3507012006/2020

Bisa tolong jelaskan 3507012006 itu kode yang terdiri dari apa saja?

**Comment by eddieridwan** [comment]
Itu kode wilayah, sesuai dengan Permendagri 72 Tahun 2019  https://www.kemendagri.go.id/files/2020/PMDN%2072%20TH%202019+lampiran.pdf.

Biasanya ditulis sebagai contoh berikut: 35.07.01.2006 (provinsi, kabupaten, kecamatan, desa).

Versi kode wilayah yg lebih tua dapat dilihat di https://pantau.opensid.my.id/index.php/wilayah

**Comment by eddieridwan** [comment]
Tampilan rumusan pokok IDM di modul Admin telah ditambahkan ke v20.09-premium-pasca. 
Berikutnya akan ditambahkan ke menu statis supaya juga bisa ditampilkan ke web.

**Comment by eddieridwan** [comment]
Sekarang juga bisa tampilkan status IDM ke web melalui menu statis.
