### ISSUE TITLE
bug pada ubahan status pada ubah biodata

### ISSUE THREAD

**Issue by Gunturwijay** [OpenSID/OpenSID#3532]
### Seperti apa yang diharapkan?
Ubahan status yang dipilih harus sesuai ditampilkan ketika melihat kembali pada ubahan biodata

### Apa yang terjadi?
1. Ketika merubah status penduduk dari tetap ke tidak tetap mengalami bug setalah disimpan.

![image](https://user-images.githubusercontent.com/40741591/92073886-f3fa2100-edde-11ea-867d-d42c70e32ec9.png)

2. Ketika melihat kembali pada ubah biodata, Status penduduk tidak tampil sesuai dengan pilihan (Seperti pada Gambar)

![image](https://user-images.githubusercontent.com/40741591/92074171-987c6300-eddf-11ea-858c-9e6e8f360fa9.png)

Pada biodata penduduk Status berubah sesuai dengan pilihan

![image](https://user-images.githubusercontent.com/40741591/92074553-8a7b1200-ede0-11ea-84b0-2287dd0b02c7.png)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.09
| Versi PHP        | 7.3.21
| System operasi   |

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3533
