### ISSUE TITLE
[Login] Perbaiki batasi jumlah salah login menggunakan database

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#3536]
### Bagaimana alurnya sampai muncul masalah?
Fitur membatasi jumlah salah login admin sekarang tidak lagi berfungsi, karena data session sekarang dihapus pada waktu logout. Kalau cara yg digunakan sekarang tidak dapat diperbaiki, perlu dirancang ulang -- mungkin yg berbasis database dan pencatatan IP address.

### Seperti apa yang diharapkan?
Fitur mencegah login secara brute force perlu aktif kembali.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | v20.09-pasca
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
Mas @agungsugiarto, ini sama halnya pembatasan login dengan ip jika 3 kali gagal login. https://github.com/OpenSID/OpenSID/issues/577

**Comment by andifahruddinakas** [comment]
Sudah diterpakan diversi 2305.0.0-premium
