### ISSUE TITLE
Modul Lapak/Toko Desa

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#3541]
### Bagaimana alurnya sampai muncul masalah?
Terkendala upload produk desa pada website OpenSID.

### Seperti apa yang diharapkan?
Adanya Halaman Statis untuk input Produk Desa yang terdiri dari:
1. Judul Produk
2. Gambar Produk (Slider Manual misal 3 gambar)
3. Harga Produk
4. Deskripsi Singkat Produk tersebut.
4. Link WA Penjual.

### Apa yang terjadi?
Agar dapat dengan mudah memasarkan produk UMKM yang ada di desa setempat.

**Comment by afa28** [comment]
Mungkin table yg dibutuhkan :
1. Produk
2. Kategori
3. Kontak

Dgn ketentuan :
1. Login > Layanan_Mandiri > Pasara_Desa(atau nama lainnya) untuk penduduk
2. Login > Siteman/Admin > Pasara_Desa(atau nama lainnya) untuk admin/operator/bumdes
3. Produk yg di diupload perlu persetujuan admin atau tdk ?
4. Dll.

**Comment by HerryWanda** [comment]
saya rasa produk yg di upload perlu persetujuan admin atau operator supaya gak ada penipuan atau hal yg tidak baik di upload, mungkin karna iseng atau coba2..

**Comment by afa28** [comment]
> saya rasa produk yg di upload perlu persetujuan admin atau operator supaya gak ada penipuan atau hal yg tidak baik di upload, mungkin karna iseng atau coba2..

Kla masalah ini sdah jelas

**Comment by HerryWanda** [comment]
mungkin tmbahan , 

nantik produk tersebut , bisa di inser sebagai banner di artikel saat admin operator bikin artikel pak @afa28 ..

sebentuk iklan banner, itu pun kalo bisa sih pak..

**Comment by solikhin948** [comment]
Setuju dengan adanya halaman statis input produk desa sangat membantu warga dimasa pandemi ini

**Comment by muhtar-coder** [comment]
Ini fitur kami sekabupaten menyatakan setuju.. 👍👍👍

**Comment by afa28** [comment]
Mungkin bisa dibahas di pertemuan selanjutnya, apakah akan jd prioritas u/ rilis. Krn saat ini yg jd prioritas adalah anjungan layanan mandiri.

**Comment by muhtar-coder** [comment]
untuk barang jualan pastinya ada naik ada turun atau dicount pada moment tertentu,,,bagaimana cara nya ? apakah edit per oleh admin per item ataukah ada cara lain ?

**Comment by hasap86** [comment]
Cocok dimasa pandemi begini, biar membantu penduduk saling berjualan

**Comment by eddieridwan** [comment]
Di OpenSID, perlu dibatasi Lapak Desa sederhana, **bukan** lapak seperti di Bukalapak, Tokopedia dsbnya. Batasi hanya untuk menyediakan daftar produk yg bisa ditampilkan di tema, supaya yg berminat membeli bisa menghubungi penjual langsung. Yaitu OpenSID **tidak** berurusan dengan pemesanan produk. 

Untuk solusi teknisnya, sepertinya sudah waktunya menyediakan api-tema, yg bisa diakses tema untuk mengambil data yg tersedia untuk publik. Jadi untuk Lapak Desa

1. Sediakan modul pengelolaan di Admin
2. Di api-tema sediakan bisa mengambil data lapak sederhana: 
    1. Judul produk
    2. Gambar produk, bisa lebih dari satu per produk
    3. Harga produk
    4. Keterangan singkat produk
    5. Link WA Penjual (harus dari data penduduk)

**Comment by Zoel-WB** [comment]
Harapan akan menjadi prioritas untuk Fitur Lapak Online Desa, dengan demikian produk2 apa saja yg ada didesa baik UMKM yang ada di desa maupun Produk Mikro Rumah tangga bisa memperkenalkan produknya melalui web desa.
Data-data produk kalau bisa bisa di entri seperti mengentri data base, dan masing-masing bisa membuatkan atau bisa mengajukan pembuatan Akun di Website desa, sehingga masing2 pemilik lapak punya akun tersendiri untuk mengelola produknya.

**Comment by afa28** [comment]
> Harapan akan menjadi prioritas untuk Fitur Lapak Online Desa, dengan demikian produk2 apa saja yg ada didesa baik UMKM yang ada di desa maupun Produk Mikro Rumah tangga bisa memperkenalkan produknya melalui web desa.
> Data-data produk kalau bisa bisa di entri seperti mengentri data base, dan masing-masing bisa membuatkan atau bisa mengajukan pembuatan Akun di Website desa, sehingga masing2 pemilik lapak punya akun tersendiri untuk mengelola produknya.

![111](https://user-images.githubusercontent.com/57283157/120385640-42caec00-c35a-11eb-80ed-60a3bb343329.png)
![222](https://user-images.githubusercontent.com/57283157/120385650-4494af80-c35a-11eb-9a30-4f1c5cea0028.png)
![333](https://user-images.githubusercontent.com/57283157/120385651-452d4600-c35a-11eb-87f1-0be5c01cdd82.png)

Sebelum saya lanjutkan menampilkan ke halaman website, apakah ada field atau inputan lain yg dibutuhkan selain di atas???

**Comment by ariandii** [comment]
lokasi pelapak. lat dan lang.
dan kontak yg bisa dihubungi (wa)

**Comment by eddieridwan** [comment]
Sdh dicommit ke `riis-dev` melalui https://github.com/OpenSID/premium/pull/246

**Comment by ariandii** [comment]
Panah merah, nama yang muncul berbeda saat lakukan edit data.
sedangkan Panah Biru sudah sesuai data yang ada.

<img width="871" alt="2021-06-10_22h47_26" src="https://user-images.githubusercontent.com/46939846/121556319-f8262f80-ca3d-11eb-85a9-7a2371e2508f.png">

**Comment by ariandii** [comment]
Saat edit Kategori, tidak muncul sempurna untuk kolom edit nya.

<img width="635" alt="2021-06-10_22h50_57" src="https://user-images.githubusercontent.com/46939846/121556802-64a12e80-ca3e-11eb-9984-9366cba342c3.png">

**Comment by Zoel-WB** [comment]
Langsung muncul sambilan tester, mantap Pak...

**Comment by ariandii** [comment]
Muncul Keterangan Phone number tidak valid saat di klik. karena bukan menggunakan awalan 62.

<img width="664" alt="2021-06-10_23h07_04" src="https://user-images.githubusercontent.com/46939846/121559302-aa5ef680-ca40-11eb-9fe6-1f6326ede209.png">

**Comment by ariandii** [comment]
Saat lokasi penjual di klik, peta tidak muncul.

<img width="947" alt="2021-06-10_23h09_06" src="https://user-images.githubusercontent.com/46939846/121559593-ea25de00-ca40-11eb-9a6e-cb9d62b2ce2e.png">

**Comment by Zoel-WB** [comment]
![gambar](https://user-images.githubusercontent.com/64481641/121560720-feb6a600-ca41-11eb-92e8-e5aea6e9db66.png)

Rencana hanya utk mengedit nomor kontak
![gambar](https://user-images.githubusercontent.com/64481641/121560868-23ab1900-ca42-11eb-88e1-906f2e6abdc3.png)

**Comment by Zoel-WB** [comment]
Edit Kategori terprotek
![gambar](https://user-images.githubusercontent.com/64481641/121561851-16daf500-ca43-11eb-9076-ca516c5b2f62.png)

**Comment by eddieridwan** [comment]
@ariandii @Zoel-WB , karena fitur ini sudah masuk ke rilis beta, setiap perbaikan perlu melalui issue baru. Mohon tidak melalui komentar di issue yg sudah ditutup -- karena tidak dipantau lagi. Buat issue baru.
