### ISSUE TITLE
Penambahan Kolom Keterangan

### ISSUE THREAD

**Issue by Jhiban-Khang** [OpenSID/OpenSID#3542]
tidak adanya kolom keterangan, sehingga tidak bisa menambahkan informasi yang perlu dicatat
### Bagaimana alurnya sampai muncul masalah?

adanya kolom atau isian keterangan
### Seperti apa yang diharapkan?

agar bisa di isi informasi/ data lainnya
### Apa yang terjadi?

OpenSID 20.09 pasca
### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.09
| Versi PHP        | 
| System operasi   |

**Comment by Jhiban-Khang** [comment]
kolom keterangan pada isian data penduduk/keluarga dll

**Comment by Nurhidayat29** [comment]
data apa yg diperlukan, mungkin bisa diperjelas issue ini dan lampirkan foto sesuai issue yg diinginkan.

**Comment by Jhiban-Khang** [comment]
pada kolom data kelompok, pada anggota tdk ada kolom untuk menambahkan
informasi lain, istilahnya kolom keterangan, gunanyya untuk mengisi jabatan
dll

**Comment by eddieridwan** [comment]
Info jabatan dsbnya ada di versi v20.09-premium. Silakan berlangganan Fitur Premium. Issue ini akan ditutup.
