### ISSUE TITLE
Terapkan Menu Cetak dan Unduh pada Daftar Persil 

### ISSUE THREAD

**Issue by Zulkarnaimni** [OpenSID/OpenSID#3543]
![image](https://user-images.githubusercontent.com/64481641/92334469-7709c880-f0b8-11ea-920f-2a40a4640d47.png)

### Bagaimana alurnya sampai muncul masalah?

Bug pada Fitur Daftar Persil pada Menu Cetak dan Unduh tidak berfungsi

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3555

**Comment by Zulkarnaimni** [comment]
Terima kasih Pak Eddie Ridwan, saat ini saya lagi mengimput Data-data persil untuk dapat memasukkan data ke Analisis Prodeskel yang sebenarnya rill

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
