### ISSUE TITLE
pesan Access Denied saat akan Menggunakan Responsive File Manager di Windows

### ISSUE THREAD

**Issue by roaddee** [OpenSID/OpenSID#3544]
### Bagaimana alurnya sampai muncul masalah?
Saat akan mencoba membuat artikel dan akan melakukan upload gambar atau semacamnya, tidak bisa dijalankan secara normal karena muncul pesan "Access Denied"

![image](https://user-images.githubusercontent.com/45786885/92388571-b5979580-f141-11ea-88c5-484edbc7a097.png)

### Seperti apa yang diharapkan?
Untuk pengguna localhost (offline) bisa juga untuk mencoba mempelajari penggunaan pembuatan artikel seperti yang online yang tidak ada masalah

### Apa yang terjadi?
Karena tidak bisa menggunakan RFM dengan normal, maka pembuatan artikel tidak bisa sempurna karena tidak bisa melakukan upload gambar dan semacamnya

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.09-pasca
| Versi PHP        |  7.2
| System operasi   | Windows 10

**Comment by eddieridwan** [comment]
Masalah ini terjadi karena penerapan function PHP `tempnam()` di Windows berbeda dengan di OS lainnya.

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master`.

**Comment by roaddee** [comment]
siap pak
