### ISSUE TITLE
Tombol untuk menghapus data persil pada Daftar Persil Tidak Berfungsi

### ISSUE THREAD

**Issue by Zulkarnaimni** [OpenSID/OpenSID#3545]
![image](https://user-images.githubusercontent.com/64481641/92393884-c7316b00-f14a-11ea-821c-ebf58cf5646f.png)
![image](https://user-images.githubusercontent.com/64481641/92393998-f21bbf00-f14a-11ea-8536-8334bc5f54db.png)

### Bagaimana alurnya sampai muncul masalah?

Tombol untuk menghapus pada Daftar Persil Tidak Berfungsi

### Seperti apa yang diharapkan?
Apabila terjadi kesalahan dalam mengimput data atau kesalahan klik masuk, data sudah terimput dan tersimpan dengan tidak tersengaja ke dalam daftar C-DESA yang salah supaya dapat dihapus kembali untuk di imput ke Persil C-Desa yang benar.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by Zulkarnaimni** [comment]
Bila memungkin kan juga pada Daftar Persil bisa ditambah "fitur" utk dapat memfilter data baik" lokasi persil" maupun "Kelas Tanah" seperti memfilter tipe lokasi pada peta, karena jumlah persil dengan jumlah area pada peta pasti akan sama.

**Comment by eddieridwan** [comment]
Persil yg masih digunakan tidak bisa dihapus. Hapus dulu penggunaan persil tersebut, baru bisa dihapus. Ini bukan error. Issue ini akan ditutup. @Zulkarnaimni kalau ada permintaan lain, silakan buat issue terpisah.
