### ISSUE TITLE
Bug Pada fitur Tambah C-DESA, tidak dapat memasukkan Data "Nama Pemilik Tertulis di C-Desa" Pemilik yang memiliki kesamaan Nama

### ISSUE THREAD

**Issue by Zulkarnaimni** [OpenSID/OpenSID#3549]
![image](https://user-images.githubusercontent.com/64481641/92563851-72a10380-f2a2-11ea-9abc-b146df8b39dc.png)

### Bagaimana alurnya sampai muncul masalah?

Bug Pada fitur Tambah C-DESA, tidak dapat memasukkan Data "Nama Pemilik Tertulis di C-Desa" Pemiliki yang memiliki kesamaan nama

### Seperti apa yang diharapkan?
Dapat memasukkan Nama Kepemilikan yang memiliki kesamaan nama

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by Zulkarnaimni** [comment]
![image](https://user-images.githubusercontent.com/64481641/92564518-7f722700-f2a3-11ea-837f-33abc49b4b2c.png)

**Comment by pandigresik** [comment]
secara code memang dibatasi nama kepemilikan harus unik, pertanyaannya sekarang adalah bolehkah orang dengan nama Afandi memiliki beberapa nomer cdesa ? jika dibolehkan maka seharusnya kontrol nama kepemilikan harus unik bisa dilepas

**Comment by Zulkarnaimni** [comment]
Bila berbentuk kode dengan untuk daftar C-Desa, berarti harus dirembuk juga dengan yang lain, saya fikir nama kepemilikan seperti bisa bila ada yg kesamaan Nama Kepemilikan bisa di input seperti input biasa

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by Zulkarnaimni** [comment]
Itulah pak @pandigresik tadi pak @eddieridwan mengatakan seperti itu juga, berarti kalau nama yang sama misalnya seperti nama saya Zulkarnaini, di desa saya ada 3 orang dengan nama sama seperti nama saya artinya harus mengikuti nama orang tua diujung nama bisa jadi mungkin, mana lebih baik mengkunci nomor C-Desa saja sedangkan nama dilepas kontrolnya atau disepakati dulu dgn pengguna yang lain.

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3557

**Comment by Zulkarnaimni** [comment]
Terimakasih Pak Eddie Ridwan dan Pak Pandigresik atas segala responnya..

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
