### ISSUE TITLE
Permintaan Penambahan Fitur "Filter Data" Daftar Persil

### ISSUE THREAD

**Issue by Zulkarnaimni** [OpenSID/OpenSID#3550]
![image](https://user-images.githubusercontent.com/64481641/92598069-7c425f80-f2d2-11ea-8169-b214c71c262c.png)

### Bagaimana alurnya sampai muncul masalah?
Permintaan Penambahan Fitur "Filter" Daftar Persil untuk dapat memfilter data dengan kategori :
1. Filter Daftar Kelas Tanah/Tipe Tanah
2. Filter Daftar Lokasi Tanah

### Seperti apa yang diharapkan?

Untuk Memudahkan pencarian lokasi, nomor persil maupun tipe/kelas tanah.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 7.4.9
| System operasi   | 20.09

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3822
