### ISSUE TITLE
Ketika login username salah langsung timeout, dulu ada kesempatan sebanyak 3 kali

### ISSUE THREAD

**Issue by pandigresik** [OpenSID/OpenSID#3552]
Di versi dahulu user diberikan kesempatan sebanyak 3 kali untuk login, di versi ini ketika user salah memasukkan username atau password langsung dianggap timeout dan harus menunggu dulu selama 4 menit untuk bisa login lagi

### Bagaimana alurnya sampai muncul masalah?
![image](https://user-images.githubusercontent.com/1853475/92671557-c9f5b100-f340-11ea-998f-8587204e0c80.png)

### Seperti apa yang diharapkan?
Bisa seperti yang dulu ada 3 kali kesempatan

### Apa yang terjadi?
User harus menunggu dulu

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.09
| Versi PHP        | 7.4.5
| System operasi   | Ubuntu 20.04

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3553
