### ISSUE TITLE
Perlu di tampilkan kode atau no seri data statistik seperti nomor seri BPJS pada hasil cetak/unduh

### ISSUE THREAD

**Issue by muhtar-coder** [OpenSID/OpenSID#3556]
### Bagaimana alurnya sampai muncul masalah?

Beberapa data statistik kependudukan mempunyai nomor kode atau nomor seri seperti BPJS atau nomor buku nikah pada setiap data penduduk.
data statistik merupakan data yang selalu harus di update setiap waktu sesuai kondisi kejadian/perubahan,pada umumnya untuk statistik kepemilikan asuransi,desa setiap tahun nya selalu mengajukan permohonan BPJS dan juga hampir setiap tahun nya mendapat jatah/quota bantuan berupa kartu seperti bpjs tersebut ataupun kartu lain nya yang berupa bantuan pemerintah yang setiap kartunya memiliki nomor kode/seri,sehingga saat menginput kedalam opensid selalu di tuliskan nomor seri tersebut atau juga ketika mendata pengajuan atau perbaikan data dapat terlihat pada menu statistik secara masal.

### Seperti apa yang diharapkan?
Ketika mencetak atau meng unduh data statistik yang memiliki nomor seri tersebut dapat juga tercetak nomor seri atau kode pada hasil cetakan atau unduhan.

### Apa yang terjadi?
1. Memudahkan dalam pelaporan jumlah pemilik data statistik yang terdapat nomor seri.
2. Memudahkan dalam perbaikan data statistik penduduk.
3. Memudahkan dalam pengajuan baru untuk penduduk yang belum memiliki data di maksud meskipun saat ini sudah bisa 
    memfilter penduduk yang sudah punya atau belum (agar lebih lengkap).

### Informasi tambahan 

1. contoh gambar statistik kepemilikan asuransi
![image](https://user-images.githubusercontent.com/55665526/92985455-cc8d0d80-f4dc-11ea-9cb1-62523233fd43.png)

2. contoh gambar setelah klik salah satu jumlah satistik
![image](https://user-images.githubusercontent.com/55665526/92985554-ebd86a80-f4dd-11ea-8deb-64361e9f2cf9.png)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.09
| Versi PHP        | 
| System operasi   |

**Comment by muhtar-coder** [comment]
![image](https://user-images.githubusercontent.com/55665526/92985680-1d9e0100-f4df-11ea-8028-843acd73fef3.png)

**Comment by eddieridwan** [comment]
Harap lampirkan contoh nomor seri yg dimaksud. Lampirkan contoh kartu peserta atau lainnya yg berisi nomor seri tersebut. Kalau berbeda untuk masing2 jenis asuransi, lampirkan berbagai contoh tersebut.

**Comment by eddieridwan** [comment]
Mengenai buku nikah, harap buat issue terpisah. Jelaskan perbedaan antara No. Akta Nikah dengan nomor seri pada buku nikah. Lampirkan contoh buku nikah yg menunjukan perbedaan antara No. Akta Nikah dan nomor seri.

**Comment by muhtar-coder** [comment]
siap pak eddie,,,,terima kasih sebelumnya...

**Comment by afa28** [comment]
Yg sy tangkap, view hasil link statistik ke penduduk datanya tdk lengkap (sesuai kategori yg dipilih), baik itu di view awal modul atau di cetak/unduh modul tsb.

Contoh :
- Kategori jenis kelamin = data jenis kelamin (datanya ada dan ditampilkan)
- Kategori umur = data umur (datanya ada dan ditampilkan)
- Kategori golongan darah = data golgongan darah (datanya ada tapi tdk ditampilakn)
- Dll.

Ini karena keterbatasan dr view yg ditampilkan pada modul penduduk ataupun lainnya yg di link dr modul statistik.

**Comment by afa28** [comment]
Solusi untuk  issue ini : 
Tampilkan data penduduk dari detail statistik berdasarkan kategori yg dipilih. Jika data tsb tdk ada bisa di tambahkan field yg dibutuhkan untuk ditampilkan. Contoh : Kategori : Jenis Asuransi, tambahkan data tambahan Jenis Asuransi dan No. Asuransi, dll

**Comment by muhtar-coder** [comment]
contoh kartu BPJS

![image](https://user-images.githubusercontent.com/55665526/94924872-837f1680-04e8-11eb-94c6-838fbdc390d5.png)


pada data penduduk nomor kartu asuransi tersebut di catat di sini 

![image](https://user-images.githubusercontent.com/55665526/94925262-22a40e00-04e9-11eb-9e00-f1b90647e25f.png)


Harapan nya ketika cetak data statistik penduduk berdasar jenis kepemilikan asuransi dapat tertera nomor kartu asuransi tersebut.
