### ISSUE TITLE
Ketika Membuat Surat Keterangan Kematian terjadi error

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#3558]
### Bagaimana alurnya sampai muncul masalah?
Ketika membuat surat Keterangan kematian yang dimana penduduk yang bersangkutan sudah diisikan nomor NIK ayah dan Ibu di biodata penduduk terjadi error
contoh penduduk yang sudah terisi NIK ayah dan ibu
![image](https://user-images.githubusercontent.com/25834335/92992283-70e27480-f51c-11ea-9367-ece9e902c4a3.png)

tampilan ketika membuat surat
![image](https://user-images.githubusercontent.com/25834335/92992250-3c6eb880-f51c-11ea-9925-5106e2bd33c2.png)

### Seperti apa yang diharapkan?
Tidak Terjadi error seperti versi sebelumnya

### Apa yang terjadi?
Tidak Bisa Membuat Surat Keterangan Kematian bagi penduduk yang terisi NIK orang tua 

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by roaddee** [comment]
@MUHAMMADRANGSEL , apakah masalah terjadi hanya pada data penduduk yang MATI dan di biodata penduduknya terdapat data NIK ayah dan ibu nya, begitu ?

**Comment by MUHAMMADRANGSEL** [comment]
surat yang memunculkan NIK orang tua rata2 seperti ini

**Comment by roaddee** [comment]
kalau rata2, berarti ada yg bisa ?, atau 100% penduduk meninggal yang ada NIK ortu nya di biodata penduduk, PASTI bermasalah surat kematiannya ?

**Comment by MUHAMMADRANGSEL** [comment]
maksud saya surat yang menampilkan nama orang tua sebelum di eksport bung
rudy yg tidak bisa

Pada tanggal Sab, 12 Sep 2020 19.17, Rudi Purwanto <notifications@github.com>
menulis:

**Comment by roaddee** [comment]
sudah saya buat PR nya, menunggu review pak eddie

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3559
