### ISSUE TITLE
Hasil Import Data Penduduk Tidak Sesuai Dengan Laporan Jumlah Data Yang Berhasil Diimport

### ISSUE THREAD

**Issue by PWidodo** [OpenSID/OpenSID#3560]
### Bagaimana alurnya sampai muncul masalah?
Setelah melakukan import data penduduk.xls (format 97-2003) berhasil dengan laporan seluruh data berhasil terimport tanpa ada data yang gagal, tetapi setelah dilihat di dashboard ternyata jumlah penduduk tidak sesuai dengan jumlah yang diimportkan, dan tidak sesuai dengan laporan hasil import. Salah satu kasus (bug) nya adalah saya import data penduduk sejumlah 1505 dengan laporan seluruh data terimport tanpa kegagalan, Saya cek di menu kependudukan, hanya terekam 1360 data penduduk, saya cek di dashboar juga 1360 penduduk padahal seharusnya berjumlah 1505 penduduk.

### Seperti apa yang diharapkan?
Data penduduk yang terekam pada sistem (menu kependudukan maupun dasboard) harusnya sama dengan Laporan Jumlah data Yang Berhasil Diimport.

### Apa yang terjadi?
-

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 19.20-pasca
| Versi PHP        |  7.4
| System operasi   | Windows 10
![issue_import_data_penduduk_excel](https://user-images.githubusercontent.com/45189822/93022119-6d7ce500-f611-11ea-9902-adab3d6bb0e7.png)

**Comment by eddieridwan** [comment]
Mohon kirim contoh data yg bermasalah ke PM, untuk diperiksa masalahnya.

**Comment by eddieridwan** [comment]
Sekarang error pada waktu menulis data penduduk ke database juga dilaporkan. Sdh dicommit ke `master`.
