### ISSUE TITLE
Tambahan Informasi Issue BUG pada fitur Import Data C-Desa belum berfungsi

### ISSUE THREAD

**Issue by Zulkarnaimni** [OpenSID/OpenSID#3562]
![image](https://user-images.githubusercontent.com/64481641/93116398-6a542880-f6e7-11ea-9408-6233ffe610f8.png)

### Bagaimana alurnya sampai muncul masalah?

Tambahan Informasi Issue BUG pada fitur Import Data C-Desa belum berfungsi
saya sendiri belum menggunakan fitur ini karena memang tidak ada data tersimpan untuk diimpot

### Seperti apa yang diharapkan?
Untuk mempercepat imput data C-Desa alangkah baiknya bisa di Import.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.09 Pasca
| Versi PHP        | 7.4.10
| System operasi   | Windows 10 64 Bit

**Comment by Nurhidayat29** [comment]
#3334 Tambahkan impor data C-Desa

**Comment by Zulkarnaimni** [comment]
Ooo Begitu Pak Nurhidayat, saya terlupakan, karena kemaren sambil imput karena menu ini belum aktif saya kirim ke issue, karena saya sendiri juga mengisi dari awal juga karena tidak ada data sebelumnya yg sudah terecord untuk diimport ke SID.
