### ISSUE TITLE
Merubah NIAP menjadi NIPD

### ISSUE THREAD

**Issue by PWidodo** [OpenSID/OpenSID#3564]
### Bagaimana alurnya sampai muncul masalah?
Saat ini Kemendagri sedang merumuskan NIPD (Nomor Induk Perangkat atau Pegawai Desa) sebagai pengganti NIAP (Nomor Induk Aparatur Pemerintah) karena status perangkat desa bukanlah Pegawai Negeri, dan Desa-desa sudah diminta untuk menyetorkan Database Perangkat Desa Se-Indonesia melalui Pemkab.

### Seperti apa yang diharapkan?
Merubah NIAP menjadi NIPD pada form isian dan form hasil data aparatur desa serta pada lembar cetak. Selanjutnya NIPD tersebut dapat ditampilkan pada widgets Aparatur Desa dibawah jabatan.

### Apa yang terjadi?
Hal ini untuk persiapan manakala nanti NIPD telah diterbitkan oleh Kemendagri

### Informasi tambahan 
Sebagai gambaran hasil yang dimaksud, saya lampirkan gambar hasil dan file script yang telah saya rubah dalam bentuk pdf
![gambar_hasil](https://user-images.githubusercontent.com/45189822/93236552-2aee1080-f7a9-11ea-8c24-54701caa4c98.jpg)
[Merubah NIAP menjadi NIPD.pdf](https://github.com/OpenSID/OpenSID/files/5226338/Merubah.NIAP.menjadi.NIPD.pdf)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by PWidodo** [comment]
File Merubah NIAP menjadi PDF diatas berisi file-file php yang perlu diedit, untuk membantu programmer. maaf saya tidak bisa merubah langsung untuk PR, karena keterbatasan kemampuan,

**Comment by pandigresik** [comment]
berapa panjang maksimal NIPD ini, sekilas kami lihat itu mengubah panjang kolong pamong_nipd menjadi varchar(25)

**Comment by pandigresik** [comment]
sepertinya ini hanya merubah label aja, apakah semua desa akan menerapkan hal yang sama ?

**Comment by PWidodo** [comment]
> 
> 
> berapa panjang maksimal NIPD ini, sekilas kami lihat itu mengubah panjang kolong pamong_nipd menjadi varchar(25)

Format NIPD sama dengan format NIP PNS pak (contoh : 19780201 200003 1 004) 21 digit dengan spasinya.

**Comment by PWidodo** [comment]
> 
> 
> sepertinya ini hanya merubah label aja, apakah semua desa akan menerapkan hal yang sama ?

diatas saya lampirkan file "Merubah NIAP menjadi NIPD.pdf" yang berisi file apa saja yang telah saya rubah di OpenSID saya.

**Comment by PWidodo** [comment]
Kalaupun misalnya desa lain tidak berkenan menerapkannya, ya issue ini bisa ditutup. saya hanya merubah untuk kkonsumsi sendiri saja.

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3568
