### ISSUE TITLE
Ubah Lokasi Tempat Tinggal error

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#3569]
### Bagaimana alurnya sampai muncul masalah?
Ketika mencoba merubah Lokasi Tempat Tinggal di Menu Kependuduk==>Penduduk Mengagalami Error
![image](https://user-images.githubusercontent.com/25834335/93614921-58cf9100-fa05-11ea-96a2-d1195bf8b0ed.png)
![image](https://user-images.githubusercontent.com/25834335/93614957-608f3580-fa05-11ea-837b-5c12b470cc66.png)

### Seperti apa yang diharapkan?
Ubah Lokasi Tempat Tinggal berjalan seperti di Versi sebelumnnya

### Apa yang terjadi?
Tidak bisa merubah Lokasi Tempat Tinggal

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by Nurhidayat29** [comment]
coba gnti browser anda, saya cba di demo tidak ada maslh

**Comment by MUHAMMADRANGSEL** [comment]
siap, setelah saya coba di browser lain ternyata normal

Pada tanggal Sab, 19 Sep 2020 00.58, Nur Hidayat <notifications@github.com>
menulis:
