### ISSUE TITLE
Penambahan fitur cetak peta wilayah desa, dusun , dll

### ISSUE THREAD

**Issue by kasipembts** [OpenSID/OpenSID#3571]
### Bagaimana alurnya sampai muncul masalah?
Belum adanya fitur cetak peta 

### Seperti apa yang diharapkan?
OpenSID dapat mempermudah bagi desa dalam melakukan cetak peta wilayah yg telah selesai pemetaan batas" wilayah. Fitur ini juga dapat digunakan sebagai bahan untuk perencanaan pembangunan di desa" seperti jalan, jembatan dll. 
Jika disetujui oleh komunitas OpenSID saya ingin mengajukan fitur cetak peta wilayah.

### Apa yang terjadi?
Belum adanya fasilitas tersebut

### Informasi tambahan 
Untuk kualitas gambar yg akan dihasilkan dapat menyesuaikan dengan skala yg sesuai dengan ukuran peta nanti yang akan dicetak,, dan ada dialog box yg mengatur ukuran Panjang x Lebar peta dengan skala mengikuti ukuran peta yg dicetak

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.09 pasca
| Versi PHP        | 
| System operasi   |

**Comment by ai-skematik** [comment]
silahkan kirim pr untuk fitur cetak petanya..

**Comment by kasipembts** [comment]
Saya belum mengerti cara mengirim pr pak,, saya masih awam ,

**Comment by eddieridwan** [comment]
Sdh dicommit ke `rilis` Premium melalui PR #3574
