### ISSUE TITLE
Daftar Hubungan Keluarga Hanya Muncul Beberapa Saja

### ISSUE THREAD

**Issue by ilamazuliaf** [OpenSID/OpenSID#3579]
### Bagaimana alurnya sampai muncul masalah?
Pecah KK anak karena sudah nikah (dalam kasus ini mempelai berasal dari desa dan dusun setempat), kemudian menambah data Keluarga baru di menu **Kependudukan -> Keluarga -> Tambah KK Baru -> Dari Penduduk Sudah Ada**
<img width="600" alt="Screen Shot 2020-09-23 at 21 47 26" src="https://user-images.githubusercontent.com/31075119/94029207-c48b7280-fde6-11ea-95f8-481963013cdc.png">

### Seperti apa yang diharapkan?
Daftar Hubungan Keluarga muncul **Istri*

### Apa yang terjadi?
Daftar Hubungan Keluarga **Istri** tidak muncul

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.9-Pasca
| Versi PHP        | 7.2
| System operasi   |

**Comment by afa28** [comment]
Silahkan ubah terlebih dahulu Data `STATUS PERKAWINAN` kepala keluarga tsb menjadi `KAWIN` baru kemudian tambah anggotanya.

Jika Kepala Keluarga Belum KAWIN : Maka yg muncul hanya pilihan di atas, makanya perlu diubah terlebih dahulu STATUS PERKAWINANnya

**Comment by afa28** [comment]
pak @ai-skematik , bisa ditambahkan di panduan mengenai issue ini.
