### ISSUE TITLE
Bug pada Fitur Analisis "Indikator & Pertanyaan" Pada Fitur "Kembali ke Data Dasar"

### ISSUE THREAD

**Issue by Zulkarnaimni** [OpenSID/OpenSID#3581]
![image](https://user-images.githubusercontent.com/64481641/94046976-9d8b6b80-fdfb-11ea-8767-4fdc69249849.png)

### Bagaimana alurnya sampai muncul masalah?
Di Klik pada Fitur Kembali ke Data Dasar akan Tetapi Pindah / Masuk ke Menu "Pengaturan Modul"

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.09 Pasca
| Versi PHP        | 7.4.10
| System operasi   |Windows 10 64 Bit

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master`.
