### ISSUE TITLE
Bug pada unduh dan cetak Penduduk/Keluarga Ketika di filter nama A-Z

### ISSUE THREAD

**Issue by Gunturwijay** [OpenSID/OpenSID#3582]
### Bagaimana alurnya sampai muncul masalah?
![image](https://user-images.githubusercontent.com/40741591/94098936-e707a500-fe53-11ea-8d8f-4b5745369586.png)

![image](https://user-images.githubusercontent.com/40741591/94098957-f686ee00-fe53-11ea-931d-26a26cf88dc5.png)

### Seperti apa yang diharapkan?
Data Penduduk/Keluarga dapat dicetak/diunduh setelah difilter A-Z

### Apa yang terjadi?
1. Tidak dapat diunduh/dicetak setelah difilter A-Z (New Tab)
![image](https://user-images.githubusercontent.com/40741591/94100115-f50af500-fe56-11ea-9c48-15d74a0232d4.png)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.09-pasca
| Versi PHP        | 7.4.10
| System operasi   |

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master`.
