### ISSUE TITLE
Nama Kepala Desa Tidak ada di pilihan cetak Laporan Buku Administrasi umum

### ISSUE THREAD

**Issue by INaon** [OpenSID/OpenSID#3583]
### Bagaimana alurnya sampai muncul masalah?
di Pilihan Pamong Mengetahui ketika cetak laporan buku administrasi umum ( Bukur Peraturan Desa, Buku Keputusan Kepala Desa, Buku agenda surat masuk dan surat keluar ) tidak ada pilihan nama kepala desa
![20200924](https://user-images.githubusercontent.com/65794146/94115371-32ce4480-fe7c-11ea-85b3-fc4ede2f3d5b.jpeg)

### Seperti apa yang diharapkan?
adanya pilihan nama kepala desa di pamong mengetahui ketika cetak laporan seperti Buku Aparat Pemerintah Desa
![24](https://user-images.githubusercontent.com/65794146/94115283-17fbd000-fe7c-11ea-96d1-bf4d21105bb1.jpeg)

### Apa yang terjadi?
tidak sesuia dengan permendagri 47 tahun 2016 tentang administrasi pemerintahan desa
![Image 2020-09-24 at 3 31 37 PM](https://user-images.githubusercontent.com/65794146/94115430-49749b80-fe7c-11ea-8ada-e646820db4c0.jpeg)

### Informasi tambahan 
[Lampiran Permendagri 47 Tahun 2016.pdf](https://github.com/OpenSID/OpenSID/files/5274281/Lampiran.Permendagri.47.Tahun.2016.pdf)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master`
