### ISSUE TITLE
Bug pada Fitur Data Penduduk pada Fitur Pilih Aksi " Ubah Status Dasar"

### ISSUE THREAD

**Issue by Zulkarnaimni** [OpenSID/OpenSID#3584]
![image](https://user-images.githubusercontent.com/64481641/94175510-fc66e880-fec0-11ea-8bf6-0d7710880200.png)

![image](https://user-images.githubusercontent.com/64481641/94175537-038df680-fec1-11ea-934d-72542661613f.png)

### Bagaimana alurnya sampai muncul masalah?
Tampilan Pada Pilihan Tahun dan Bulan  Menampilkan data saling Bertumpukkan satu sama lain

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.09 Pasca
| Versi PHP        | 7.4.10
| System operasi   |Windows 10 64 bit

**Comment by ai-skematik** [comment]
tahun dan bulan dimna ya..?

**Comment by Zulkarnaimni** [comment]
Juga dalam Fitur Input/Ubah  Data Penduduk
![image](https://user-images.githubusercontent.com/64481641/94179737-215e5a00-fec7-11ea-865b-f77a557c9432.png)

**Comment by Zulkarnaimni** [comment]
Pada Pilihan Aksi Ubah Status Dasar Penduduk dan Pada Kolom Isian Tanggal Lahir Input/Ubah Data Penduduk

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by Zulkarnaimni** [comment]
Ada 2 (Dua) Tempat :
1. Pada Fitur Daftar Penduduk Pilih Aksi "Ubah Status Dasar"
2. Pada Kolom Isian Tanggal Lahir

**Comment by ai-skematik** [comment]
Kapan terakhir di update?

**Comment by Zulkarnaimni** [comment]
Update terakhir kemaren malam per tanggal 24 September 2020

**Comment by eddieridwan** [comment]
@Zulkarnaimni , di https://demo.opensid.my.id normal saja. Coba clear cache, tutup browser dan coba lagi.

**Comment by Zulkarnaimni** [comment]
Di Demo juga begitu Pak pada Fitur data Penduduk Pilih Aksi ---> Plih Ubah Status Dasar--> Klik Tanggal Peristiwa--->Klik -->Tahun
![image](https://user-images.githubusercontent.com/64481641/94226514-fa814180-ff21-11ea-808a-6e072c1167ae.png)

**Comment by Zulkarnaimni** [comment]
Pada Tanggal Lahir Input Data Penduduk 
![Uploading image.png…]()

**Comment by eddieridwan** [comment]
@Zulkarnaimni , saya coba lagi di demo. Tidak masalah. Dengan gejala seperti itu, kalau sdh bersihkan cache, tutup/buka browser, gunakan browser lain masih bermasalah, kemungkinan file rilis anda tidak lengkap atau salah. Jika menggunakan git, bisa periksa melalui `git status` untuk melihat apakah ada file rilis yg telah berubah.

![status-dasar](https://user-images.githubusercontent.com/249563/94229700-a0917380-ff43-11ea-88ae-3d725b69ba3d.jpg)

**Comment by Zulkarnaimni** [comment]
Kalau disini normal, bila kita klik utk menggantikan atau memilih tahun dan bulan,  misal mau kita 2020 ke Tahun 1980, dimenu tersebut tampilannya bertumpuk. Cache sudah dibersihkan apa pengaruh dari browers yg saya gunakan ini yg belum saya tapi saya coba dulu dgn browser lain, Krn saya Edge, saya coba pakai crome Pak sama. Ini yang di https://demo.opensid.my.id  saya coba pakai CROME kalau tadi diatas saya pakai Microsost Edge karena sebagai Browser Default di Laptop


![image](https://user-images.githubusercontent.com/64481641/94232941-45ef1c00-ff31-11ea-9437-f428f2fb7e98.png)
![image](https://user-images.githubusercontent.com/64481641/94232961-4c7d9380-ff31-11ea-8b47-78744cc7d483.png)

**Comment by eddieridwan** [comment]
Saya sdh coba lagi, termasuk mengubah bulan, tahun. Tidak masalah. Tidak bisa replikasi error anda. Mungkin tunggu kalau ada yg lain yg juga mengalami. Atau minta bantu @roaddee kalau bersedia remote memeriksa sistem anda.

**Comment by eddieridwan** [comment]
Ok, sudah bisa replikasi masalahnya. Sepertinya masalah css untuk dropdown-menu datetimepicker widget.

**Comment by Zulkarnaimni** [comment]
Oke Pak @eddieridwan, Pak @ai-skematik  Makasih banyak.......

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master`.

**Comment by Zulkarnaimni** [comment]
Oke, Terimakasih Pak Eddie Ridwan

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
