### ISSUE TITLE
Tambah opsi menambahkan penduduk baru pd daftar anggota keluarga

### ISSUE THREAD

**Issue by Zulkarnaimni** [OpenSID/OpenSID#3587]
Temuan 2 (dua) Jenis Bug pada Daftar Keluarga
1. Menu Tambah data dalam List Daftar Keluarga
2. Menu Pada Daftar Kerluarga Masing-Masing KK

### Bagaimana alurnya sampai muncul masalah?

![image](https://user-images.githubusercontent.com/64481641/94332304-4f928580-fffe-11ea-8e71-2aeb30c165dc.png)
![image](https://user-images.githubusercontent.com/64481641/94332397-14dd1d00-ffff-11ea-86a5-20081aa71c95.png)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
@Zulkarnaimni , saya tidak menemukan error.
1. Tombol `+` untuk Tambah Anggota membuka form untuk mengisi Biodata Anggota Keluarga baru. Memang seperti itu selama ini.
2. Tombol `Tambah Anggota` di halaman `Daftar Anggota Keluarga` memang tidak ada pilihan. Hanya menampilkan pemilihan dari penduduk yg ada. Memang seperti itu selama ini.

Jadi bukan bug. Sekiranya anda inginkan yg lain, ubah issue ini menjadi permintaan, bukan melaporkan error.

**Comment by Zulkarnaimni** [comment]
Oke Pak eddie, mungkin salah menafsir Pak, karena dulu kalau tambah form langsung muncul form kosong, oke sudah paham, menu di atas dulu ada 2 pilihan, mungkin pilihannya beralih (+) dalam list daftar keluarga sudah merangkul semua, tadi mau menambah data penduduk kelahiran baru yg belum terdapat dalam KK sebelumnya begitu saya klik sudah berbeda saya fikir bug, mohon maaf atas kekeliruan ini..

**Comment by eddieridwan** [comment]
@Zulkarnaimni , yang ada dua pilihan adalah untuk menambah KK baru. Menambah anggota KK tidak pernah ada dua pilihan. Tapi boleh saja buat issuenya. Dan sekalian terapkan lebih bagus lagi.

![menambah-kk-baru](https://user-images.githubusercontent.com/249563/94352845-647a2200-00ad-11eb-9b8c-6eec212d8831.jpg)

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3590
