### ISSUE TITLE
list daftar surat di arisp layanan surat tidak terlihat

### ISSUE THREAD

**Issue by WAHYUDIK** [OpenSID/OpenSID#3591]
### Bagaimana alurnya sampai muncul masalah?
ketika kita ingin memfilter surat di arsip layanan surat, list daftar surat tampilannya kecil sehingga nama-nama suratnya tidak terbaca
![image](https://user-images.githubusercontent.com/31026980/94387319-0401e800-0174-11eb-988b-c8a298d19ca3.png)

### Seperti apa yang diharapkan?
nama-nama suratnya tampil utuh seperti list surat yang lain.

### Apa yang terjadi?
saat ini masih tampil kecil sehingga tidak terlihat

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.09 - pasca
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master`.
