### ISSUE TITLE
Scrollbar horizontal ada di posisi paling bawah, menyulitkan ingin menggeser data yang ada di barisan atas

### ISSUE THREAD

**Issue by WAHYUDIK** [OpenSID/OpenSID#3592]
### Bagaimana alurnya sampai muncul masalah?
ketika kita ingin menggeser data yang ada di barisan atas ke sebelah kanan/kiri mengalami kendala, disebabkan oleh tombol scrollbar horizontal berada dipaling bawah
![image](https://user-images.githubusercontent.com/31026980/94426765-49480900-01b8-11eb-9c7a-70af1e256a32.png)

### Seperti apa yang diharapkan?

tombol scrollbar horizontal tetap berada dibarisan bawah layar seperti excel dibawah ini
![image](https://user-images.githubusercontent.com/31026980/94427047-b2c81780-01b8-11eb-9c4f-89d4cb6a023a.png)
sehingga memudahkan pengguna baik di laptop ataupun di HP,
### Informasi tambahan 
menu-menu yang terdapat tombol scrolbar horizontal:
**Menu Kependudukan:** submenu penduduk, submenu keluarga, submenu  calon pemilih
**Menu Layanan Surat:** submenu arsip layanan surat

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Bukankah daftar lebar bisa discroll horizontal menggunakan mouse atau trackpad (di laptop) dan jari di touchscreen langsung di tabel tanpa harus dilakukan menggunakan scroll bar? Saya coba di Chrome dan Firefox tidak masalah, tidak harus menggunakan scroll bar.

**Comment by WAHYUDIK** [comment]
Maksud saya scrolbar horizontalnya ada dipling bawah, sehingga ketika kita mau geser ke sebelah kanan data yang ada di atas, harus geser sxrolbar vertikal kebawah dulu agar muncul scrolbar horizontalnya,

**Comment by eddieridwan** [comment]
Sebagaimana saya jelaskan di atas, untuk menggeser kanan tidak perlu menggunakan scroll bar. Langsung saja di bagian layar tabel ybs. Tidak harus scroll vertikal ke bawah dulu. Silakan coba. Kalau anda tidak bisa coba update browsernya.

**Comment by afa28** [comment]
> Maksud saya scrolbar horizontalnya ada dipling bawah, sehingga ketika kita mau geser ke sebelah kanan data yang ada di atas, harus geser sxrolbar vertikal kebawah dulu agar muncul scrolbar horizontalnya,

Gunaka 2 jari untuk scroll pd mouse atau trackpad dan geser ke kiri/kanan untuk scroll horizontal atau atas/bawah untuk scroll vertical.

**Comment by WAHYUDIK** [comment]
> > Maksud saya scrolbar horizontalnya ada dipling bawah, sehingga ketika kita mau geser ke sebelah kanan data yang ada di atas, harus geser sxrolbar vertikal kebawah dulu agar muncul scrolbar horizontalnya,
> 
> Gunaka 2 jari untuk scroll pd mouse atau trackpad dan geser ke kiri/kanan untuk scroll horizontal atau atas/bawah untuk scroll vertical.

oke sudah saya coba dan berhasil, trims atas sarannya, saya close issue ini
