### ISSUE TITLE
Unduh Data Penduduk Dari Menu Pengaturan>Database Penduduk Mati dan Pindah Ikut Terunduh Juga

### ISSUE THREAD

**Issue by WAHYUDIK** [OpenSID/OpenSID#3593]
### Bagaimana alurnya sampai muncul masalah?
ketika kita ingin mengunduh data penduduk melalui Menu Pengaturan>Database Penduduk Mati dan Pindah Ikut Terunduh Juga, sehingga menyulitkan pengguna ketika ingin mengimport ulang data penduduk ke opensid (Baik online/offline) 
![image](https://user-images.githubusercontent.com/31026980/94427458-4d285b00-01b9-11eb-9a33-571e36b054be.png)

### Seperti apa yang diharapkan?
ketika unduh data penduduk, data penduduk yang sudah meninggal/pindah tidak lagi terunduh, sehingga ketika pengguna akan mengimport ulang data penduduk hasil unduhan tersebut tidak harus mengecek ulang data penduduk yang sudah pindah/meninggal.

### Apa yang terjadi?

saat ini unduh data penduduk masih terunduh semua data penduduk yang sudah meninggal/pindah
### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Mengapa penduduk yg mati, pindah dan hilang tidak ingin diimpor ulang? Seharusnya data di OpenSID lengkap termasuk data lama. Ingat, data orang tua penduduk yg hidup bisa saja penduduk yg sdh mati atau pindah. Dan statistik kependudukan yg berdasarkan waktu (misalnya statistik berapa yg meninggal per tahun) memerlukan data itu harus ada. Jadi seharusnya data penduduk tidak dihapus sampai waktu yg lama. Bisa saja disediakan filter supaya hanya ekspor data penduduk hidup -- tetapi seharusnya BUKAN untuk alasan yg anda berikan.

**Comment by WAHYUDIK** [comment]
Jika memang terus bisa diunduh, sebaiknya status penduduk ketika di unduh juga ikut berubah, misalkan pindah status penduduknya pondah, jika mati statusnya juga mati ketika diunduh, jika unduh melalui submenu kependudukan memang bisa di filter berdasarkan status kependudukan, tapi jika unduhnya lewat pengaturan database tidak filternya

**Comment by eddieridwan** [comment]
Apakah saat ini status mati/pindah/hidup berubah di data yg diunduh/impor? Seharusnya status dasar penduduk tidak berubah -- yaitu kalau mati tetap mati. Kalau berubah itu berarti `bug` yg perlu diperbaiki. Kalau itu yg anda maksud, harap ubah issue ini menjadi bug dan jelaskan bahwa status dasar penduduk harus dipertahankan pada waktu mengekspor data penduduk dan pada waktu mengimpor.

**Comment by afa28** [comment]
Untuk format `Ekspor Data Penduduk (Format .xlsx untuk di impor ke database SID melalui menu Impor Database)` tdk menyediakan field status penduduk (hidup/mati/dll:

Adapun field yg ada :
Alamat | Dusun | RW | RT | Nama | Nomor KK | Nomor NIK | Jenis Kelamin | Tempat Lahir | Tanggal Lahir | Agama | Pendidikan (dlm KK) | Pendidikan (sdg ditempuh) | Pekerjaan | Kawin | Hub. Keluarga | Kewarganegaraan | Nama Ayah | Nama Ibu | Gol. Darah | Akta Lahir | Nomor Dokumen Paspor | Tanggal Akhir Paspor | Nomor Dokumen KITAS | NIK Ayah | NIK Ibu | Nomor Akta Perkawinan | Tanggal Perkawinan | Nomor Akta Perceraian | Tanggal Perceraian | Cacat | Cara KB | Hamil | KTP-el | Status Rekam | Alamat   Sekarang

**Comment by WAHYUDIK** [comment]
> Untuk format `Ekspor Data Penduduk (Format .xlsx untuk di impor ke database SID melalui menu Impor Database)` tdk menyediakan field status penduduk (hidup/mati/dll:
> 
> Adapun field yg ada :
> Alamat | Dusun | RW | RT | Nama | Nomor KK | Nomor NIK | Jenis Kelamin | Tempat Lahir | Tanggal Lahir | Agama | Pendidikan (dlm KK) | Pendidikan (sdg ditempuh) | Pekerjaan | Kawin | Hub. Keluarga | Kewarganegaraan | Nama Ayah | Nama Ibu | Gol. Darah | Akta Lahir | Nomor Dokumen Paspor | Tanggal Akhir Paspor | Nomor Dokumen KITAS | NIK Ayah | NIK Ibu | Nomor Akta Perkawinan | Tanggal Perkawinan | Nomor Akta Perceraian | Tanggal Perceraian | Cacat | Cara KB | Hamil | KTP-el | Status Rekam | Alamat Sekarang


betul, tidak ada filed untuk status penduduk, alangkah baiknya disediakan untuk mempermudah proses import ulang penduduk

**Comment by WAHYUDIK** [comment]
untuk issue ini bagaimana tindak lanjutnya?

**Comment by eddieridwan** [comment]
Sdh dicommit ke `bug-fix` melalui https://github.com/OpenSID/premium/pull/151
