### ISSUE TITLE
Error simpan surat masuk

### ISSUE THREAD

**Issue by afa28** [OpenSID/OpenSID#3594]
### Bagaimana alurnya sampai muncul masalah?
Masuk modul Sekretariat > Surat Masuk > Tambah Surat Masuk Baru. Input data yg dibutuhkan kecuali yg diberi tanda pada kotak (lihat gambar) dan kemudian simpan

![coba1](https://user-images.githubusercontent.com/57283157/94440942-5ff85b00-01cc-11eb-8b12-dd08967cd137.JPG)

Akan terjadi 2 error, yakni :
1. Error ketika menyimpan data tanpa mengisi Kode/Klasifikasi Surat
2. Error ketika menyimpan data tanpa mengisi Disposisi Kepada

Testing website demo:
![coa2](https://user-images.githubusercontent.com/57283157/94441460-fcbaf880-01cc-11eb-870f-59b9017d6867.JPG)

### Seperti apa yang diharapkan?
Tambahkan required pada Kode/Klasifikasi Surat dan bisa menyimpan data walau tdk mengisi Disposisi Kepada

### Apa yang terjadi?
Tidak Terjadi error ketika ke 2 kondisi tsb terpenuhi.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3595
