### ISSUE TITLE
Nilai Jawaban  pada Modul analisis dibatasi 127

### ISSUE THREAD

**Issue by ai-skematik** [OpenSID/OpenSID#3596]
### Bagaimana alurnya sampai muncul masalah?
Nilai setiap Jawaban pada  Modul analisis tidak bisa lebih dari 127

### Seperti apa yang diharapkan?
Nilai jawaban analisis tidak dibatasi atau dibatasi sampai 999

### Apa yang terjadi?
tidak bisa membuat analisis yang setiap jawaban pertanyaan bernilai lebih dari 127

### Informasi tambahan 

![2020-09-28_22h14_33](https://user-images.githubusercontent.com/48144047/94452197-7953d400-01d9-11eb-8235-5d21a5004ee8.png)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
Ini krn di settingan tipe datanya menggunakan TINYINT yg batasnya -127 s/d 127.

**Comment by eddieridwan** [comment]
Sdh dicommit melalui PR #3599
