### ISSUE TITLE
Perlu dibuatkan filter tahunan pada Buku Administrasi Desa (Premium) dan Sekretariat (Non Premium)

### ISSUE THREAD

**Issue by Gunturwijay** [OpenSID/OpenSID#3598]
### Bagaimana alurnya sampai muncul masalah?
1. Buku Administrasi Desa (Premium)
2. Menu Sekretariat (Non Premium)

### Seperti apa yang diharapkan?
Dapat menyajikan data rekapan pertahun
![image](https://user-images.githubusercontent.com/40741591/94509169-db462500-023d-11eb-9a49-2b37a64a3a59.png)

### Apa yang terjadi?
Sulit dalam menyajikan data rekapan pertahun

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.09-pasca
| Versi PHP        | 
| System operasi   |

**Comment by apidong** [comment]
saya akan mengerjakan issue ini.

**Comment by apidong** [comment]
![image](https://user-images.githubusercontent.com/20056421/124517861-45b07500-de0f-11eb-8c2a-67bcc04e6b02.png)
apakah filter sebatas sub-menu buku peraturan Desa?

**Comment by eddieridwan** [comment]
@apidong , batasi pada:
1. Buku Peraturan Desa
2. Buku Keputusan Kepala Desa

Hanya lakukan di rilis Premium. Fitur baru semua diterapkan di Premium dulu.

**Comment by eddieridwan** [comment]
Sdh dicommit ke `rilis-dev` melalui https://github.com/OpenSID/premium/pull/312
