### ISSUE TITLE
$request_awal pd siteman tdk berjalan normal

### ISSUE THREAD

**Issue by afa28** [OpenSID/OpenSID#3602]
### Bagaimana alurnya sampai muncul masalah?
Misal mengakses url `http://https://demo.opensid.my.id//penduduk/form/1/0/3` dan belum login, maka akan di alihkan ke halaman siteman/login. Setelah login success, maka akan dialihkan ke url yg di request sebelumnya (`http://https://demo.opensid.my.id//penduduk/form/1/0/3`). Tp yg terjadi adalah url tsb salah, url berubah menjadi `http://https://demo.opensid.my.id//pendudukform103` (halaman notfound)

### Seperti apa yang diharapkan?
Setelah login dpt mengakses url yg direquest sebelumnya.

### Apa yang terjadi?
Menampilkan halaman url yg direquest sebelumnya, buka halaman notfound

### Informasi tambahan 
Hal ini biasa terjadi jika mengakses suatu halaman yg admin tanpa login atau status login sudah expired.

![111111](https://user-images.githubusercontent.com/57283157/94707841-1b0c2a00-036e-11eb-853d-b2e557861bdc.JPG)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3603
