### ISSUE TITLE
[Keluarga] Pindah keluarga antar Dusun secara kolektif di menu Keluarga

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#3604]
### Bagaimana alurnya sampai muncul masalah?
Khususnya di Kabupaten Lombok Timur Banyaknya Pemekaran Dusun, Data keluarga yang ada di OpenSID perlu disesuaikan dengan kondisi Pemekaran, saat ini masih di pindah keluarga antar dusun dilakukan per keluarga, sehingga membutuhkan waktu lama
![image](https://user-images.githubusercontent.com/25834335/94779141-0759d580-03f9-11eb-9b1a-c7ace9cab22e.png)

### Seperti apa yang diharapkan?
Adanya Fasilitas pindah keluarga antar dusun secara kolektif

### Apa yang terjadi?
untuk memindahkan keluarga antar dusun memakan waktu lama

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by andifahruddinakas** [comment]
pak @MUHAMMADRANGSEL, apakah issue ini masih diperlukan?

**Comment by MUHAMMADRANGSEL** [comment]
masih bung

**Comment by andifahruddinakas** [comment]
> masih bung

https://github.com/OpenSID/OpenSID/pull/7458
