### ISSUE TITLE
Gagal menghilangkan script index.php

### ISSUE THREAD

**Issue by bayu791** [OpenSID/OpenSID#3605]
saya gagal menghilangkan index.php,
padahal sudah saya rename htaccess.txt menjadi .htaccess
mohon bantuannya

**Comment by eddieridwan** [comment]
Pertanyaan penggunaan seperti ini mohon ditanyakan di https://www.facebook.com/groups/OpenSID. Issue di Github hanya untuk permintaan fitur baru, atau bug yg memerlukan perbaikan script. 

Ok, issue ini akan saya tutup.
