### ISSUE TITLE
CELAH JSO DI VERSI 20.10

### ISSUE THREAD

**Issue by adp-hck** [OpenSID/OpenSID#3606]
![Screenshot_2020-10-01-18-18-53](https://user-images.githubusercontent.com/72261270/94925792-5104f780-04af-11eb-83fe-0e8e99d7aa0c.png)

### Bagaimana alurnya sampai muncul masalah?
Di bagian kolom komentar masih bisa di isi menggunakan kode php/html

### Seperti apa yang diharapkan?
Kurang baik

### Apa yang terjadi?
Terdapat celah jso 

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.10
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
Setelah sy coba, komentar yg dikirim dr luar admin (halaman website) sudah difilter untuk kemungkinan serangan JSO. Mungkin anda memasukkan script tsb lewat admin dengan edit komentar (sy coba mmang berhasil), krn pd modul koemnetar belum ada filter untuk serangan jso.

Terima kasih atas laporannya.

**Comment by adp-hck** [comment]
Bounty nya ada gk min?

Pada tanggal Jum, 2 Okt 2020 20.28, Andi Fahruddin Akas <
notifications@github.com> menulis:

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master`
