### ISSUE TITLE
Perlu di tambahkan tombol masukan surat ini ke dalam buku administrasi umum surat keluar yang di tempatkan menu di arsip surat 

### ISSUE THREAD

**Issue by muhtar-coder** [OpenSID/OpenSID#3607]
### Bagaimana alurnya sampai muncul masalah?

1.  melengkapi kemudahan pendataan buku administrasi umum > Buku Agenda Surat Keluar,di maksudkan agar arsip keluar 
     yang di inginkan dan jenis surat yang sesuai dapat tercetak pada menu buku agenda surat keluar berupa pencatatan surat 
     nya,  sedang kan untuk hard copy nya sudah tersedia di arsip surat.

2.  Karena semua jenis surat di buat dan keluarnya dari aplikasi OpenSID

### Seperti apa yang diharapkan?

1. catatan buku agenda surat keluar terisi otomatis berdasarkan pilihan arsip surat yang di pilih.
2. catatan pada agenda surat keluar sama dengan yang ada di arsip surat,,jika pada arsip surat di hapus maka pada buku agenda 
    surat keluar juga ikut terhapus.

### Apa yang terjadi?

pelaporan dan pengarsipan agenda surat lebih lengkap

### Informasi tambahan 
1. agenda surat masuk yang di isi berdasarkan surat masuk telah terdata secara berkelanjutan dan siap cetak
![image](https://user-images.githubusercontent.com/55665526/94926223-a3afd500-04ea-11eb-92a6-7716a196a225.png)

2. agenda surat keluar otomatis terdata jika di pilih (hanya jenis surat keluar yang sesuai)
![image](https://user-images.githubusercontent.com/55665526/94926983-d4dcd500-04eb-11eb-8d8f-af480a3ea3a9.png)

3. tersedia kolom centang "masukan kedalam log surat keluar ? " pada arsip layanan.
![image](https://user-images.githubusercontent.com/55665526/94929540-6d288900-04ef-11eb-99cf-40c7ee6243e0.png)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.10 premium
| Versi PHP        | 
| System operasi   |

**Comment by Gunturwijay** [comment]
Setuju, karena nomor urut surat keluar pada layanan surat>cetak surat mengikuti nomor surat keluar, jadi lebih baiknya ditampilkan juga pada : Buku administrasi desa>administrasi umum>buku agenda surat keluar
