### ISSUE TITLE
Menambahkan kolom NIK Kepala Keluarga di Daftar Terdata Suplemen pada Sasaran Keluarga

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#3608]
### Bagaimana alurnya sampai muncul masalah?
Daftar Terdata Suplemen sasaran keluarga belum ada NIK kepala keluarga dan juga di Cetak maupun Unduh
![image](https://user-images.githubusercontent.com/25834335/94935026-1034cf00-04ff-11eb-9c76-96696e3d686b.png)

### Seperti apa yang diharapkan?
NIK Kepala Keluarga ditambahkan di Daftar Terdata Suplemen **sasaran keluarga** baik di cetak maupun unduhnya seperti di menu bantuan sasaran keluarga

### Apa yang terjadi?
NIK Kepala keluarga belum ada sehingga perlu di input secara manual kembali

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3611

**Comment by silentx07** [comment]
error ya

**Comment by silentx07** [comment]
lwwklwwkw masih anonim ya yang comite

Trisna1337

Pada tanggal Rab, 7 Okt 2020 12:54, Eddie Ridwan <notifications@github.com>
menulis:

**Comment by silentx07** [comment]
admin nya mana kalau mau tau bug tempat nya di mana ku kasih tau sini

Trisna1337

Pada tanggal Rab, 7 Okt 2020 12:54, Eddie Ridwan <notifications@github.com>
menulis:

**Comment by afa28** [comment]
Pak @silentx07 , jika menemukan bugs silahkan laporkan melalu issue dan jika mengetahui solusi dr issue tsb silahkan buatkan Pull Request.

**Comment by silentx07** [comment]
tahu saya karna itu code code saya yang berjalan di github

Trisna1337

Pada tanggal Rab, 7 Okt 2020 19:29, Andi Fahruddin Akas <
notifications@github.com> menulis:

**Comment by silentx07** [comment]
chat me priv


Trisna1337

Pada tanggal Rab, 7 Okt 2020 19:36, trisna junior <notifications@github.com>
menulis:
