### ISSUE TITLE
Menambahkan kolom Nomor KK di Daftar Terdata Suplemen pada Sasaran Penduduk

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#3609]
### Bagaimana alurnya sampai muncul masalah?
Daftar Terdata Suplemen sasaran penduduk belum ada Nomor KK dan juga di Cetak maupun Unduh
![image](https://user-images.githubusercontent.com/25834335/94935619-db754780-04ff-11eb-9391-c6746b7fd42f.png)

### Seperti apa yang diharapkan?
Nomor KK ditambahkan di Daftar Terdata Suplemen sasaran keluarga baik di cetak maupun unduhnya seperti di menu bantuan sasaran penduduk
![image](https://user-images.githubusercontent.com/25834335/94935494-b7b20180-04ff-11eb-8cdd-e1e0293dfe3a.png)

### Apa yang terjadi?
Nomor KK belum ada sehingga perlu di input secara manual kembali

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3611
