### ISSUE TITLE
Tampilkan Alamat Lengkap seperti di menu bantuan di Fitur Data Suplemen

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#3610]
### Bagaimana alurnya sampai muncul masalah?
Di Daftar Terdata Suplemen sasaran Keluarga maupun di sasaran penduduk perlu disesuaikan seperti di menu Bantuan untuk kolom alamat
![image](https://user-images.githubusercontent.com/25834335/94937116-bda8e200-0501-11eb-9c74-59e0f5ac2ee8.png)

### Seperti apa yang diharapkan?
Alamat ditampilkan secara lengkap seperti di menu bantuan baik sasaran keluarga maupun penduduk
![image](https://user-images.githubusercontent.com/25834335/94937267-f21c9e00-0501-11eb-8a38-fa391bc382e7.png)

### Apa yang terjadi?
Ketika Cetak dan Unduh Data Suplemen sasaran keluarga alamat tidak lengkap

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
![1111](https://user-images.githubusercontent.com/57283157/94961828-a547c000-051f-11eb-8b46-fe5d8f9ea58d.png)

1. Format standar alamat yg biasa ditampilkan di beberapa modul.
2. Format alamat pd modul program bantuan untuk identitasi peserta bisa di costume/di input.

Format yg sering sy jumpai :
`$data[$i]['alamat'] . " "  .  "RT/RW ". $data[$i]['rt']."/".$data[$i]['rw'] . " - " . "Dusun " . strtoupper($data[$i]['dusun']);`
atau
"RT/RW ". $data[$i]['rt']."/".$data[$i]['rw'] . " - " . "Dusun " . strtoupper($data[$i]['dusun']);`

**Comment by MUHAMMADRANGSEL** [comment]
$data[$i]['alamat'] . " " . "RT/RW ". $data[$i]['rt']."/".$data[$i]['rw'] .
" - " . "Dusun " . strtoupper($data[$i]['dusun']);

Pada tanggal Sab, 3 Okt 2020 03.28, Andi Fahruddin Akas <
notifications@github.com> menulis:

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3654
