### ISSUE TITLE
[Layanan Mandiri] Sediakan fitur cetak nomor registrasi/antrian untuk anjungan mandiri

### ISSUE THREAD

**Issue by mizwaruddin** [OpenSID/OpenSID#3613]
### Bagaimana alurnya sampai muncul masalah?
Saat ini layanan mandiri (surat) hak cetak ada pada operator desa. Pemohon hanya bisa mengajukan permohonan surat.

### Seperti apa yang diharapkan?
Dengan adanya anjungan layanan mandiri di kantor desa, diharapkan pemohon bisa langsung mencetak surat yg dimohon.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Bagaimana alurnya sampai suratnya ditandatangani? Siapa yg memeriksa pengisian suratnya sudah benar. Harap jelaskan dengan flowchart (bagan) supaya jelas.

**Comment by eddieridwan** [comment]
Fitur ini hanya diaktifkan kalau terdeteksi dibuka di anjungan layanan mandiri.

**Comment by eddieridwan** [comment]
@mizwaruddin mohon jelaskan alur permohonan surat secara rinci. Misalnya apakah dokumen pendukung perlu diunggah? Dan bagaimana hasil cetak ditandatangani? Dsbnya.

**Comment by mizwaruddin** [comment]
Insyaallah hari ini saya kerjakan, Bang.

**Comment by mizwaruddin** [comment]
![IMG_20201012_113730_266.jpg](https://user-images.githubusercontent.com/39736008/95716078-0cd6db80-0c95-11eb-9cff-4bd5a3cbc38e.jpg)

**Comment by mizwaruddin** [comment]
Keterangan alur:
1. Pemohon datang ke kantor desa dg membawa dokumen pendukung (pengantar RT, FC KK & KTP dll)
2. Pemohon langsung menuju anjungan utk membuat surat dan cetak surat
3. Pemohon menuju bagian pelayanan utk menyerahkan hasil cetak surat beserta dokumen pendukung.
4. Petugas bagian layanan melakukan verifikasi.
5. Jika dokumen pendukung kurang, pemohon diminta utk melengkapinya.
6. Jika dokumen lengkap, bagian layanan meneruskan surat tsb ke Kades utk dimintakan tanda tangan.
7. Bagian layanan memanggil pemohon utk menyerahkan surat yg sdh  ditandatangani.

**Comment by afa28** [comment]
Tombol cetak langsung (tanpa perlu expor doc) atau tombol cetak hasil expor doc.

**Comment by mizwaruddin** [comment]
> Tombol cetak langsung (tanpa perlu expor doc) atau tombol cetak hasil expor doc.

Fitur ini akan mempercepat layanan.

**Comment by eddieridwan** [comment]
Saya anjurkan pemohon tidak mencetak sendiri. Saya lihat terlalu banyak masalah. Bagaimanapun, petugas akan tetap perlu memeriksa pengisian sudah betul -- karena sebagai resmi keluaran desa, harus valid. 

Berikut alur yg saya sarankan, yg tidak kalah efisiennya:

1. Pemohon mengisi surat permohonan, dan memastikan sudah membawa dokumen pelengkap yg dibutuhkan.
2. Setelah yakin siap, pemohon menekan tombol KIRIM.
3. Anjungan otomatis menerbitkan nomor antrian tercetak, dan pemohon pergi duduk menunggu nomor dipanggil.
4. Di komputer petugas, antrian permohonan melalui anjungan terlihat secara terpisah, dan petugas harus memberi prioritas sesuai nomor antrian.
5. Petugas membuka permohonan, dan memeriksa isinya.
6a. Kalau isinya ada yg perlu diperbaiki, petugas memanggil pemohon dan bersama-sama memperbaiki sampai betul, dan sekalian memeriksa kelengkapan dokumen persyaratan. Setelah lengkap, petugas mencetak surat untuk ditandatangani.
6b. Kalau isinya sdh betul, petugas memanggil pemohon untuk memeriksa kelengkapan dokumen persyaratan. Kalau sdh lengkap, petugas mencetak surat untuk ditandatangani.
7. Setelah ditandatangani, petugas memanggil pemohon untuk mengambil surat. Petugas mengubah status permohonan menjadi 'sudah diambil'

Dengan cara ini, dipastikan:
1. SEMUA surat yg dicetak dan terrekam di sistem sudah benar dan memenuhi syarat.
2. Tidak ada surat tercetak yg beredar yg belum ditandatangani -- yg mungkin belum valid, tetapi tetap menggunakan kop resmi desa
3. Tidak ada surat di sistem yg tidak jelas statusnya. 
4. Tidak ada warga yg membawa surat tercetak belum lengkap pulang dan kemudian membawa kembali pada hari lain, dengan status yg tidak jelas.

**Comment by hasap86** [comment]
ya lebih baik di anjungan disediakan printer mini untuk cetak bukti permohonan yang selanjutnya dibawa ke operator, nomor antrian atau nomor registrasi mungkin sebagai acuan pencarian data di sisi operator...

**Comment by eddieridwan** [comment]
@agungsugiarto , issue ini untuk menerapkan:

- [ ] memberi permohon surat nomor registrasi/antrian setelah permohonan pada anjungan dikirim. Permohonan surat dari layanan mandiri biasa `tidak` diberi nomor antrian
- [ ] format nomor antrian adalah `ddmmyy - [nomor urut 3 digit]`, di mana nomor urut dimulai dari 001 setiap hari; contoh `210823 - 012`
- [ ] nomor antrian tersebut ditampilkan di anjungan
- [ ] nomor antrian tersebut dapat dicetak jika printer mini disediakan pada anjungan
- [ ] nomor antrian tampil pada daftar permohonan surat yg dilihat oleh petugas
- [ ] secara default daftar permohonan surat diurut dengan antrian yg terlama ada di atas bagi permohonan yg belum diambil
- [ ] permohonan surat dapat dicari berdasarkan nomor antrian

**Comment by agungsugiarto** [comment]
Pak @eddieridwan, bagiamana membedakan untuk poin ini
- [ ] memberi permohon surat nomor registrasi/antrian setelah permohonan dikirim pada anjungan. Permohonan surat dari layanan mandiri di luar anjungan tidak diberi nomor antrian

**Comment by agungsugiarto** [comment]
Pak @eddieridwan, untuk poin 

- [ ] nomor antrian tersebut ditampilkan di anjungan.
- [ ] nomor antrian tersebut dapat dicetak oleh pemohon jika printer mini disediakan pada anjungan.

1. yang ingin ditampilkan apakah pada daftar permohonan surat?
2. saya terkendala perangkat printer untuk menerapkan fitur ini, mungkin yg bisa dilakukan dibuatkan window print sederhana.

**Comment by eddieridwan** [comment]
> * yang ingin ditampilkan apakah pada daftar permohonan surat?
> * saya terkendala perangkat printer untuk menerapkan fitur ini, mungkin yg bisa dilakukan dibuatkan window print sederhana.

1. Ya, dan diurut berdasarkan nomor antrian
2. Untuk menguji tanpa menggunakan printer, bisa coba menggunkan HP sebagai virtual printer:
     1. https://github.com/402d/Virtual_POS_printer
     2. https://www.youtube.com/watch?v=TxQJMpp7UIg
     
  Mungkin ada library lain yg juga melakukan?
