### ISSUE TITLE
Tidak butuh upload dokumen untuk anjungan mandiri

### ISSUE THREAD

**Issue by mizwaruddin** [OpenSID/OpenSID#3614]
### Bagaimana alurnya sampai muncul masalah?
Saat ini layanan mandiri (surat), pemohon harus mengupload dokumen persyaratan (FC KTP, KK, Surat Pengantar RT, dll).

### Seperti apa yang diharapkan?
Dengan adanya anjungan mandiri di kantor desa, tentunya pemohon sudah membawa bukti fisik dokumen yg diminta sehingga tidak perlu lagi upload dokumen persyaratan yg diminta.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by fusionid** [comment]
Karena yg bisa menggunakan Anjungan adalah yg warga yg dokumen-dokumen pelengkapnya sudah terdaftar sehingga ketika mereka mengajukan surat permohonan sudah bisa lanjut ke proses selanjutnya (lihat video di https://www.facebook.com/1534783691/videos/10223836160682005/). Menu upload dokumen tetap harus ada untuk para pengguna non-anjungan

**Comment by afa28** [comment]
Sdah ad solusinya yakni syarat dokumen untuk layanan mandiri di hapus (tdk di centang 1 pun). Namu saat ini masih bermasalah krn syarat dokumen minimal haru s 1 dokumen / tdk boleh kosong. Tinggal itu sj yg di perbaiki.

**Comment by eddieridwan** [comment]
Fitur ini hanya diaktifkan kalau terdeteksi dipanggil dari Anjungan. Layanan Mandiri.

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master`
