### ISSUE TITLE
Hilangkan first untuk link domain utama

### ISSUE THREAD

**Issue by afa28** [OpenSID/OpenSID#3615]
### Bagaimana alurnya sampai muncul masalah?
Saat ini setiap akses website domain utama selalu mengikutkan first di urlnya.

### Seperti apa yang diharapkan?
First di domain utama di hilangkan.

### Apa yang terjadi?
First hilang.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by balongbesuk** [comment]
saya dulu sempat pakai koding ini untuk menghilangkan first

$route['default_controller'] = 'first';

**Comment by afa28** [comment]
Untuk first/statistik mungkin controller statistik u/ admin namanya di ubah atau tambahkan dashboard/statistik u/ bagian admin (bgitupun dgn modul lainnya). Sehingga membedakan bagian web(depan), admin, dan layanan mandiri.

**Comment by afa28** [comment]
Sudah di `master ` PR #3652, untuk first/statistik bisa di buat issue lain.
