### ISSUE TITLE
[Teknis] Beberapa assets selalu diload walau tidak digunakan.

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#3616]
### Bagaimana alurnya sampai muncul masalah?
Assets selalu diload untuk semua modul yg ada di admin.
![1111122223333](https://user-images.githubusercontent.com/57283157/95013690-244a0f00-066c-11eb-913f-170961921ff3.JPG)

### Seperti apa yang diharapkan?
Assets yg diload disesuaikan pd modul tsb, misal modul statistik membuatuhkan Highcharts JS dan tdk memerlukan OpenStreetMap Js.

### Apa yang terjadi?
Assets tdk diload scr global.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
Buat library template u/ view.

**Comment by andifahruddinakas** [comment]
Sudah mulai dipisahkan menggunakan template blade secara bertahap.
1. Home
2. Identitas Desa
3. Syarat Surat
