### ISSUE TITLE
Dusun Romawi berubah menjadi ucwords pada cetak surat

### ISSUE THREAD

**Issue by ai-skematik** [OpenSID/OpenSID#3617]
### Bagaimana alurnya sampai muncul masalah?
Dusun yang menggunakan angka romawi berubah menjadi Abjad kecil pada angka kedua di cetak surat

### Seperti apa yang diharapkan?
nama dusun konsisten seperti nama dusun di wilayah administratif

### Apa yang terjadi?
harus mengubah tulisan nama dusun setiap mencetak surat

### Informasi tambahan 
![2020-10-04_23h57_09](https://user-images.githubusercontent.com/48144047/95022180-cc2d0000-069f-11eb-9234-e09d5bdddfdb.png)

![2020-10-05_00h03_20](https://user-images.githubusercontent.com/48144047/95022190-d949ef00-069f-11eb-8511-bf1fc9e105e7.png)

![2020-10-04_23h52_07](https://user-images.githubusercontent.com/48144047/95022201-e36bed80-069f-11eb-8373-5e2015bd3549.png)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.10
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3618
