### ISSUE TITLE
Data Jenis Isian tidak tersimpan pada Analisis Data Dasar Keluarga dan Data Anggota Keluarga (Prodeskel)

### ISSUE THREAD

**Issue by ai-skematik** [OpenSID/OpenSID#3619]
### Bagaimana alurnya sampai muncul masalah?
Data Jenis Isian tidak tersimpan pada Analisis Data Dasar Keluarga dan Data Anggota Keluarga (Prodeskel)

### Seperti apa yang diharapkan?
Analisis Data Dasar Keluarga dan Data Anggota Keluarga (Prodeskel) dapat menyimpan data jenis isian.

### Apa yang terjadi?
Analisis Data Dasar Keluarga dan Data Anggota Keluarga (Prodeskel) tidak dapat digunakan.

### Informasi tambahan 

![2020-10-05_11h51_10](https://user-images.githubusercontent.com/48144047/95042998-c36f1500-0705-11eb-9731-4a613a432f79.png)

![2020-10-05_11h46_07](https://user-images.githubusercontent.com/48144047/95043020-d1bd3100-0705-11eb-8d80-5018f724ec88.png)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
Sudah sy coba, permasalahannya adalah Tipe Pertanyaan yg berupa Isian Jumlah (kuantitatif) dan Isian Teks (kuantitatif) mmang tdk tersimpan. Pada table `analisis_respon` tdk ada field untuk menyimpan data hasil inputan berupa Isian Jumlah (kuantitatif) dan Isian Teks (kuantitatif).

**Comment by ai-skematik** [comment]
Dulu bisa, tp karena lama tidak digunakan, sy tidak tau sejak kapan tidak bisa mengisi data jenis isian.

**Comment by afa28** [comment]
> Dulu bisa, tp karena lama tidak digunakan, sy tidak tau sejak kapan tidak bisa mengisi data jenis isian.

Atau sy kurang paham alur dr modul ini, krn baru sempat sy buka2.

**Comment by eddieridwan** [comment]
Untuk mencoba menggunakan rilis lama (misalnya untuk melihat fitur yg dulu bekerja), lakukan:
1. `git checkout v19.08` (sesuaikan dengan rilis yg dinginkan)
2. Restore ke contoh data awal untuk rilis tersebut
3. coba fitur yg ingin dilihat, termasuk periksa script yg bersangkutan.

**Comment by afa28** [comment]
Pak @ai-skematik apa masih ingat versi berapa yg berjalan normal???

**Comment by afa28** [comment]
Tp dari source code dan tablenya tdk ada cara untuk menyimpan data berupa isian. Kecuali klw disimpan ditable yg lain, krn sy lihat respon/jawaban disimpan berdasarkan id_paramter masing dr jawaban pertanyaan.

**Comment by ai-skematik** [comment]
Coba versi 19.01

**Comment by afa28** [comment]
> Coba versi 19.01

Harus gunakan database bawaan 19.01 jg, krn database yg sekarang strukturnya sdah banyak berubah.

**Comment by ai-skematik** [comment]
Contoh data awalnya ada di rilis 19.01

**Comment by afa28** [comment]
> Contoh data awalnya ada di rilis 19.01

di versi 19.01 data berupa isian tersimppan tp banyak error database untuk beberapa kasus.

**Comment by afa28** [comment]
Setelah berulangkali coba, akhirnya nemu letak kesalahannya.

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3620
