### ISSUE TITLE
Format Laporan Hasil Klasifikasi peru ditambahkan beberapa kolom

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#3622]
### Bagaimana alurnya sampai muncul masalah?
Format Laporan Hasil Klasifikasi perlu ditambahkan kolom NIK, KK
untuk kolom Dusun di ganti dengan Alamat lengkap
![image](https://user-images.githubusercontent.com/25834335/95102376-e92c0680-0765-11eb-9f2e-b977c126d677.png)

### Seperti apa yang diharapkan?
Kolom NIK, KK dan Alamat Lengkap tersedia di Laporan Hasil Klasifikasi, Baik di Cetak dan di Unduhnya

### Apa yang terjadi?
Data yang ditampilkan kurang lengkap

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by ianskids** [comment]
Pak @MUHAMMADRANGSEL saya ingin mengerjakan issue ini tetapi saya tidak bisa menampilkan data contoh analisis, 
bisa bantu cara memasukkan contoh data nya?

**Comment by ianskids** [comment]
Pak @MUHAMMADRANGSEL saya ingin mengerjakan issue ini tetapi saya tidak bisa menampilkan data contoh analisis,  
bisa bantu cara memasukkan contoh data nya?

**Comment by afa28** [comment]
> Pak @MUHAMMADRANGSEL saya ingin mengerjakan issue ini tetapi saya tidak bisa menampilkan data contoh analisis,  
> bisa bantu cara memasukkan contoh data nya?

Silahkan buat data sembarang sj sesuai kebutuhan.

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3678

**Comment by eddieridwan** [comment]
Untuk sasaran Rumah Tangga & Kelompok, saat ini Laporan Hasil Klasifikasi tidak tampil. Issue sdh dibuat: https://github.com/OpenSID/OpenSID/issues/3683
