### ISSUE TITLE
Fitur Cetak Laporan Hasil Kalsifikasi per Rumah Tangga, Keluarga dan Individu

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#3623]
### Bagaimana alurnya sampai muncul masalah?
belum ada Fitur Cetak Laporan Hasil Kalsifikasi per Rumah Tangga, Keluarga dan Individu
![image](https://user-images.githubusercontent.com/25834335/95102779-62c3f480-0766-11eb-9159-ad6f99435b5f.png)

### Seperti apa yang diharapkan?
Adanya Fitur Cetak Laporan Hasil Kalsifikasi per Rumah Tangga, Keluarga dan Individu

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3640
