### ISSUE TITLE
Batasi akses menu web untuk data_analisis

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#3624]
### Bagaimana alurnya sampai muncul masalah?
Publikasi Indikator Analisis dihalaman Website Desa Blank seperti gambar dibawah ini : 
![image](https://user-images.githubusercontent.com/25834335/95104150-18437780-0768-11eb-91fd-e8c0987e470a.png)
![image](https://user-images.githubusercontent.com/25834335/95104208-285b5700-0768-11eb-810f-782f1c812988.png)

### Seperti apa yang diharapkan?
Publikasi Indikator Analisis dihalaman Website Desa bisa seperti di versi sebelumnya

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
Di website demo aman sj. Cara pemanggilannya salah, coba `https://demo.opensid.my.id/first/data_analisis`. Dsni perlu dibatasi aksesnya, sebaiknya data_analisis harus diaktifkan dlu di menu baru infomasinya dpt di akses.

**Comment by MUHAMMADRANGSEL** [comment]
untuk thema bawaan aman, thema yang lain perlu penyesesuaian

**Comment by afa28** [comment]
> untuk thema bawaan aman, thema yang lain perlu penyesesuaian

Issue ini sdah sy sesuaikn ulang judulnya, jd jgn di close.

**Comment by MUHAMMADRANGSEL** [comment]
siap

**Comment by WAHYUDIK** [comment]
untuk di web hasil analisis gak masalah diberi akses, cukup nama atau hasilnya, untuk nik atau no kk di tutup saja

**Comment by afa28** [comment]
> untuk di web hasil analisis gak masalah diberi akses, cukup nama atau hasilnya, untuk nik atau no kk di tutup saja

untuk saat ini data_analisis bebas diakses walau tanpa persetujuan dr pemilik website. Nantinya data_analisis hanya dpat diakses jika sdah ditambahkan ke menu seperti data lainnya yg ditampilkan di halaman website.

**Comment by afa28** [comment]
Tambahkan : 
- First.php
```
public function data_analisis($stat="", $sb=0, $per=0)
	{
		if (!$this->web_menu_model->menu_aktif('data_analisis')) show_404();
// Code
}
```

- Referensi_model.php
```
define("STAT_LAINNYA", serialize([
	'dpt' => 'Calon Pemilih',
	'wilayah' => 'Wilayah Administratif',
	'peraturan_desa' => 'Produk Hukum',
	'informasi_publik' => 'Informasi Publik',
	'peta' => 'Peta',
	'data_analisis' => 'Data Analisis'
]));
```

@ianskids

**Comment by ianskids** [comment]
@afa28 baik mas, saya pelajari dulu

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master`
