### ISSUE TITLE
Bug pada Fitur Pertanahan Daftar C-Desa dan Daftar Persil

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#3629]
### Bagaimana alurnya sampai muncul masalah?
Bug pada Fitur Pertanahan Daftar C-Desa dan Daftar Persil
1. Tambah Mutasi Persil "Data hasil tambah persil tidak ditampilakan dalam "List Daftar Persil" ----> "Jumlah Persil" dalam Daftar C-Desa juga tidak berubah.
![image](https://user-images.githubusercontent.com/64481641/95212922-6ca63000-0818-11eb-9e52-9a5079b241b9.png)

2. Nomor Urut Daftar Persil dengan Jumlah Data yang terimput juga tidak sama..
![image](https://user-images.githubusercontent.com/64481641/95213159-b42cbc00-0818-11eb-9550-2156aec2c8e7.png)

### Seperti apa yang diharapkan?

Penyesuaian Data
### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.10 Pasca
| Versi PHP        | 7.4.10
| System operasi   |Windows 10 64 bit

**Comment by mizwaruddin** [comment]
Apakah pemilik baru sudah tercatat di buku C-Desa (nomor c dan nama pemilik)? Pastikan pemilik baru (penerima mutasi) tercatat terlebih dahulu di daftar C Desa.

**Comment by agungsugiarto** [comment]
Pak @Zulkarnaimni apakah masih mengalami issue yang dimaksud? Pastikan juga lakukakan seperti yg dibilang pak @mizwaruddin .

**Comment by Zulkarnaimni** [comment]
Oke Pak Agung, nanti dicoba lagi.....
Makasih Pak.....

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by Zulkarnaimni** [comment]
Nanti saya coba ulang dulu pak......

**Comment by agungsugiarto** [comment]
Pak @Zulkarnaimni terkait jumlah data yang tidak sesuai silhkan kirimkan data daftar c-desa bapak ke telegram saya di @meagungsugiarto untuk membantu saya mereplikasi issue tersebut. Terima kasih.

**Comment by Zulkarnaimni** [comment]
Oke Pak, Kemaren untuk lanjut input datanya sudah saya penting sementara
karena menunggu perbaikan fitur, data ada yg ada sekarang data saat
sebelum saya buat issuenya.
Bentar Lagi saya ke PM pak
terimasih sebelumnya Pak...

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by agungsugiarto** [comment]
Pak @Zulkarnaimni saya tidak mengalami issue terkait nomor (2) jumlah data c-desa sama, ini dari data bapak yg tadi dikirim ke saya.

![image](https://user-images.githubusercontent.com/10989147/112718997-02e62380-8f29-11eb-80c3-4134ebca27a6.png)

**Comment by Zulkarnaimni** [comment]
Ini yg sudah di premium, krn sudah lama tidak membuka nya, barang kali terperbaiki ada data terperbaiki seperti yg c-desa nomor 9, kemaren datanya tidak masuk padahal sudah dimasukkan datanya pak atas nama mutawalli, saya coba lagi dulu pak

**Comment by Zulkarnaimni** [comment]
ATAS NAMA MUTAWALLI ini, apa kendala dan salahnya inputannya dimana, datanya sudah ada malah sudah beberapa kali di imput akan tetapi dalam daftar C-DESA nya yang tampil jumlah persilnya hanya 1 
![image](https://user-images.githubusercontent.com/64481641/112719356-32962b00-8f2b-11eb-8fe8-c496c4160145.png)

padahal datanya di dalam daftar persil sudah ada
![Uploading image.png…]()

**Comment by Zulkarnaimni** [comment]
![Uploading image.png…]()

**Comment by Zulkarnaimni** [comment]
Untuk penomoran atau nomor urut-nya sudah vit pak tidak ada masalah lagi.....

**Comment by Zulkarnaimni** [comment]
Ini bila sudah vit semuanya rencana akan saya ulang kembali dengan menandai petak-petak pertanahan pada peta desa langsung, dan mengangkat menjadi persil-persil ke C-DESA dalam Aplikasi atau fitur pertanahan...

**Comment by agungsugiarto** [comment]
Coba bapak zoel meriplikasi di demo berputar

**Comment by Zulkarnaimni** [comment]
Oke Pak saya coba

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by agungsugiarto** [comment]
@Zulkarnaimni ok sudah saya kirim pr untuk masalah ini pak

**Comment by Zulkarnaimni** [comment]
Oke Pak Agung makasih banyak...

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by Zulkarnaimni** [comment]
Saya sendiri sebenarnya bingung juga dimana salahnya, data yg saya input tidak tampil seperti tidak terekam, di Demo berputar barusan saya input juga tidak mau tampil atas nama C-DESA NABILAH
![image](https://user-images.githubusercontent.com/64481641/112720753-f5ce3200-8f32-11eb-845f-590b2b43e7e5.png)

**Comment by eddieridwan** [comment]
Sdh dicommit ke `rilis-dev` melalui https://github.com/OpenSID/premium/pull/141

**Comment by eddieridwan** [comment]
@agungsugiarto , saya buka lagi issue ini. Karena masih bermasalah pada waktu menambah persil di C-Desa jika persil yg dipilih mempunyai id_wilayah yg tidak ada di tweb_wil_clusterdesa.

**Comment by agungsugiarto** [comment]
Pak @eddieridwan bisa menambahkan screenshoot yg dimaksud, saya kurang jelas pak dibagian mananya.

**Comment by eddieridwan** [comment]
@agungsugiarto :

![error-persil](https://user-images.githubusercontent.com/249563/112804120-bd0f9380-90bf-11eb-9e89-ac61c74ece11.jpg)

**Comment by agungsugiarto** [comment]
@eddieridwan apakah yg dimaksud list lokasi yg ditulis manual harus tampil juga di list terserbut ?

![image](https://user-images.githubusercontent.com/10989147/112805198-7d38b400-909f-11eb-9dd1-ef1c955de245.png)

**Comment by eddieridwan** [comment]
@agungsugiarto Lokasi manual sudah tampil di daftar pilihan dan tidak bermasalah jika ditambahkan ke C-Desa. 

Yg bermasalah adalah persil yg kolom `id_wilayah` nya di tabel `persil` tidak ditemukan di kolom `id` di tabel `tweb_wil_clusterdesa`. Persil seperti itu tampil di daftar pilihan. Coba tambahkan persil seperti itu ke C-Desa. Akan bermasalah. 

`id_wilayah` itu mungkin menjadi rancu, jika wilayah (dusun/rw/rt) yg digunakan pada persil dihapus -- misalnya melalui menu Wilayah Administratif. Lihat gambar yg saya lampirkan di atas (salin lagi dibawah). Contoh persil seperti terlihat di mana alamatnya tampil kosong (persil 80:2). Dan tidak bisa ditambahkan ke C-Desa.

![error-persil](https://user-images.githubusercontent.com/249563/112804120-bd0f9380-90bf-11eb-9e89-ac61c74ece11.jpg)

**Comment by agungsugiarto** [comment]
Apa relasinya perlu diubah pak @eddieridwan, misalnya ketika wilayah administratif tersebut dihapus diterapkan cascade on delete jadi daftar tersebut otomatis terhapus juga atau pengguna diberi pengertian untuk mengupdate manual persil tersebut untuk mengganti lokasinya?

**Comment by eddieridwan** [comment]
Saya kira dalam kasus ini tidak tepat adanya cascade delete. Persil yg bersangkutan tetap valid, hanya lokasinya saja yg salah. Masalah serupa terjadi di beberapa tabel yg lain, yg juga menggunakan kode wilayah.  Cukup menambah penjelasan di panduan, dampak dari menghapus wilayah administratif (atau menambah peringatan di dialog konfirmasi hapus wilayah).. 

Bisa juga menampilkan pesan di persil ybs bahwa lokasinya salah dan perlu diperbaiki. Peringatan ini cukup ditampilkan di kolom alamat persil supaya mudah terlihat oleh pengguna.

**Comment by eddieridwan** [comment]
Sdh dicommit ke `bug-fix` melalui https://github.com/OpenSID/premium/pull/147
