### ISSUE TITLE
Isi otomatis kode wilayah pd lampiran surat keterangan kematian

### ISSUE THREAD

**Issue by ZER07URN** [OpenSID/OpenSID#3630]
### Bagaimana alurnya sampai muncul masalah?
Saat mencetak surat keterangan kematian, lampiran yg dihasilkan tdk mencetak kode wilayah sesuai identitas wilayah masing2.

### Seperti apa yang diharapkan?
kode wilyah pd lapiran keterangan kematian tercetak otomatis
kotak umur terisi 0 jika digit kurang dr 3

### Apa yang terjadi?
tdk perlu repot untuk isi manual lg

![11111111](https://user-images.githubusercontent.com/7290110/95299964-b50d2e80-08a8-11eb-83f8-6926113df499.JPG)

[permendagri-137-2017-kode-data-adminpemr.pdf](https://github.com/OpenSID/OpenSID/files/5338955/permendagri-137-2017-kode-data-adminpemr.pdf)

### Informasi tambahan 
[surat_ket_kematian_5201140706966997_2020-10-07_3_lampiran.pdf](https://github.com/OpenSID/OpenSID/files/5338952/surat_ket_kematian_5201140706966997_2020-10-07_3_lampiran.pdf)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3632
