### ISSUE TITLE
[Log Penduduk] Perlu ditambahkan fitur upload akta kematian

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#3633]
### Bagaimana alurnya sampai muncul masalah?
ketika ada warga masyarakat yang dibuatkan akta kematian, untuk arsip didesa masih manual, sehingga ketika dibutuhkan harus bongkar arsip

### Seperti apa yang diharapkan?
Adanya Fitur unyuk upload akta kematian sehingga mudah ketika dibutuhkan sewaktu-waktu

### Apa yang terjadi?
Dokumen Akta Kematian belum bisa terarsip dengan  baik

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Salah satu solusi adalah menambahkan tombol aksi di Log Penduduk bagi penduduk dengan status dasar `mati`.

**Comment by afa28** [comment]
https://github.com/OpenSID/OpenSID/issues/2859

7. Upload dokumen

**Comment by mizwaruddin** [comment]
@MUHAMMADRANGSEL Apakah solusi yang diberikan sudah menjawab issue Anda? Kalau sudah, tolong di close. Trims

**Comment by mizwaruddin** [comment]
@MUHAMMADRANGSEL issue ini tercatat ganda dengan https://github.com/OpenSID/OpenSID/issues/2859. Apakah bisa di close?
