### ISSUE TITLE
Admin bisa daftarkan IP address anjungan layanan mandiri

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#3634]
### Bagaimana alurnya sampai muncul masalah?
Saat ini login dan fitur layanan. mandiri sama untuk semua pengguna. Perlu dibedakan antara penggunaan di anjungan layanan mandiri dan bukan.

### Seperti apa yang diharapkan?
Sediakan pengaturan oleh admin untuk mendaftarkan IP address yg akan digunakan untuk anjungan layanan mandiri. Deteksi kalau aplikasi dibuka di anjungan layanan mandiri sesuai IP yg telah terdaftar.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | v20.10-premium
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
Berapa batasan Ip yg diperbolehkan???

**Comment by eddieridwan** [comment]
Apakah perlu dibatasi? Tapi sepertinya tidak akan ada desa yg melebihi 10 anjungan.

**Comment by eddieridwan** [comment]
Sdh dicommit ke `rilis-dev`
