### ISSUE TITLE
Ubah cara penambahan tombol untuk menampikan virtual keyboard di surat

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#3636]
### Bagaimana alurnya sampai muncul masalah?
Saat ini untuk menambahkan virtual keyboard di surat yg akan disediakan di anjungan layanan mandiri perlu melakukan perubahan yg berulang-ulang.

### Seperti apa yang diharapkan?
Ubah cara penambahan tombol untuk menampikan virtual keyboard di surat yg lebih mudah dan scaleable. Cara sekarang memerlukan banyak perubahan pada setiap surat.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | v20.10-premium
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
Klw yg sy buat sebelumnya itu otomatis menampilkan virtual keyboard, tinggal disediakan pengatutan u/ mendeteksi IP Anjungan mandiri.

**Comment by afa28** [comment]
Jd klw ingin menggunakan virtual keyboard tinggal tambahkan classnya sj pg tag input tsb.

**Comment by eddieridwan** [comment]
Ya, saya bayangkan juga seperti itu. Silakan diterapkan. Dan class itu hanya aktif apabila terdeteksi penggunaan di anjungan.

**Comment by afa28** [comment]
> Ya, saya bayangkan juga seperti itu. Silakan diterapkan. Dan class itu hanya aktif apabila terdeteksi penggunaan di anjungan.

Ya, contoh prototype yg sempat sy buat. Tinggal deteksi IP sj. https://github.com/OpenSID/premium/pull/7#issuecomment-705226595

**Comment by eddieridwan** [comment]
Sdh dicommit ke `rilis-dev` melalui PR https://github.com/OpenSID/premium/pull/12
