### ISSUE TITLE
[Layanan Mandiri] Tambahkan aturan tambahan khusus untuk penggunaan di anjungan layanan mandiri.

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#3637]
### Bagaimana alurnya sampai muncul masalah?
Saat ini form dan menu layanan mandiri tidak berbeda antara penggunaan di anjungan dan bukan.

### Seperti apa yang diharapkan?
Form dan menu di anjungan layanan mandiri perlu mengikuti aturan sesuai dengan alur penggunaan di anjungan layanan mandiri.

### Informasi tambahan 

Desa perlu memberi penjelasan secara rinci alur penggunaan di anjungan layanan mandiri, termasuk alur permohonan surat dll.

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | v20.10-premium
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
Apa maksusnya, misal anjungan layanan mandiri bisa cetak surat di tempat???

**Comment by afa28** [comment]
Untuk alur cetak surat langsung di anjungan layanan mandiri kyaknya perlu langsung cetak surat (tdk perlu download/exkport file kemudian buka file tsb). Format/alur cetak langsung surat yg dlu di kembalikan ke OpenSID.

**Comment by eddieridwan** [comment]
Eddie Ridwan, [14 Nov 2020 at 5:46:05 pm (14 Nov 2020 at 5:51:40 pm)]:
Saya anjurkan pemohon tidak mencetak sendiri. Saya lihat terlalu banyak masalah. Bagaimanapun, petugas akan tetap perlu memeriksa pengisian sudah betul -- karena sebagai resmi keluaran desa, harus valid. 

Berikut alur yg saya sarankan, yg tidak kalah efisiennya:

1. Pemohon mengisi surat permohonan, dan memastikan sudah membawa dokumen pelengkap yg dibutuhkan.
2. Setelah yakin siap, pemohon menekan tombol KIRIM.
3. Anjungan otomatis menerbitkan nomor antrian, dan pemohon pergi duduk menunggu nomor dipanggil.
4. Di komputer petugas, antrian permohonan melalui anjungan terlihat terpisah, dan petugas harus memberi prioritas sesuai nomor antrian.
5. Petugas membuka permohonan, dan memeriksa isi.
6a. Kalau isinya ada yg perlu diperbaiki, petugas memanggil pemohon dan bersama-sama memperbaiki sampai betul, dan sekalian memeriksa kelengkapan dokumen persyaratan. Setelah lengkap, petugas mencetak surat untuk ditandatangani.
6b. Kalau isinya sdh betul, petugas memanggil pemohon untuk memeriksa kelengkapan dokumen persyaratan. Kalau sdh lengkap, petugas mencetak surat untuk ditandatangani.
7. Setelah ditandatangani, petugas memanggil pemohon untuk mengambil surat.

Dengan cara ini, dipastikan:
1. SEMUA surat yg dicetak dan terrekam di sistem sudah benar dan memenuhi syarat.
2. Tidak ada surat tercetak yg beredar yg belum ditandatangani -- yg mungkin belum valid, tetapi tetap menggunakan kop resmi desa
3. Tidak ada surat di sistem yg tidak jelas statusnya. 
4. Tidak ada warga yg membawa surat tercetak belum lengkap pulang dan kemudian membawa kembali pada hari lain, dengan status yg tidak jelas.

**Comment by khiar-rara** [comment]
Bagaimana kalau di anjungan mandiri tidak perlu memasukkan PIN, cukup nik saja utk login

**Comment by khiar-rara** [comment]
Bagaimana kalau di anjungan mandiri tidak perlu memasukkan PIN, cukup nik saja utk login

**Comment by eddieridwan** [comment]
> Bagaimana kalau di anjungan mandiri tidak perlu memasukkan PIN, cukup nik saja utk login

Itu bukan cara yg aman, karena bisa saja menggunakan NIK orang lain.

**Comment by afa28** [comment]
Pak @eddieridwan, apakah ada tambahan lain mengenai pengaturan anjungan ???

**Comment by eddieridwan** [comment]
Saat ini, belum dilakukan penerbitan nomor antrian.

**Comment by andifahruddinakas** [comment]
https://github.com/OpenSID/OpenSID/wiki/Alur-Permohonan-Surat-Lewat-Anjungan-Mandiri
