### ISSUE TITLE
Kembalikan bisa ganti PIN pada waktu pertama kali login layanan mandiri

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#3638]
### Bagaimana alurnya sampai muncul masalah?
Pada penerapan form login baru untuk Layanan Mandiri, fitur bisa ganti PIN pada waktu warga pertama kali login tidak aktif lagi.

### Seperti apa yang diharapkan?
Fitur bisa ganti PIN pada waktu warga pertama kali login perlu  diaktifkan kembali.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | v20.10-premium
| Versi PHP        | 
| System operasi   |

**Comment by fusionid** [comment]
Fitur ganti PIN pada waktu pertama kali login layanan mandiri ini belum pernah bisa ditampilkan walaupun pada user yg baru terdaftar dan belum pernah login, mencoba di demo widget layanan mandiri tapi hasilnya login tetap berlanjut tanpa ada opsi untuk ganti pin.

**Comment by afa28** [comment]
> Fitur ganti PIN pada waktu pertama kali login layanan mandiri ini belum pernah bisa ditampilkan walaupun pada user yg baru terdaftar dan belum pernah login, mencoba di demo widget layanan mandiri tapi hasilnya login tetap berlanjut tanpa ada opsi untuk ganti pin.

Sebelumnya ini ad di widget, jd ketika sdah login layanan mandiri bisa cek di widget layanana mandiri pd halaman website desa.

**Comment by fusionid** [comment]
> > Fitur ganti PIN pada waktu pertama kali login layanan mandiri ini belum pernah bisa ditampilkan walaupun pada user yg baru terdaftar dan belum pernah login, mencoba di demo widget layanan mandiri tapi hasilnya login tetap berlanjut tanpa ada opsi untuk ganti pin.
> 
> Sebelumnya ini ad di widget, jd ketika sdah login layanan mandiri bisa cek di widget layanana mandiri pd halaman website desa.

Sudah coba di website demo ?

**Comment by afa28** [comment]
> > > Fitur ganti PIN pada waktu pertama kali login layanan mandiri ini belum pernah bisa ditampilkan walaupun pada user yg baru terdaftar dan belum pernah login, mencoba di demo widget layanan mandiri tapi hasilnya login tetap berlanjut tanpa ada opsi untuk ganti pin.
> > 
> > Sebelumnya ini ad di widget, jd ketika sdah login layanan mandiri bisa cek di widget layanana mandiri pd halaman website desa.
> 
> Sudah coba di website demo ?

Pernah sy coba, tp klw coba sekarang tdk bisa  krn data penduduk di website demo kosong.

**Comment by afa28** [comment]
![11111111](https://user-images.githubusercontent.com/57283157/95540540-38e72800-0a1b-11eb-8af3-eb589f6dc1f0.JPG)

**Comment by fusionid** [comment]
Ternyata opsional karena tetap langsung masuk halaman layanan mandiri tapi bagaimana mau ganti pin karena halaman sudah berpindah ke layanan mandiri.  Yang dilakukan user saat ini mungkin setelah login dan masuk layanan mandiri harus buka tab baru untuk browse lagi ke halaman first untuk dapat ganti pin baru.

**Comment by eddieridwan** [comment]
Sdh dicommit ke branch `rilis-dev` di repo premium melalui PR https://github.com/OpenSID/premium/pull/9
