### ISSUE TITLE
Jumlah KK yang di Menu statistik Keluarga berbeda dengan  di menu Home

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#3641]
### Bagaimana alurnya sampai muncul masalah?
Menu Statistik Kependudukan => Statistik Keluarga => Kelas Sosial, Jumlah Total Keluarga yang tampil tidak sesuai dengan jumlah KK yang ada di Menu Home, kalau saya perhatikan KK yang ditampilan
1. KK Aktif
2. KK Hilang/Mati/Pindah
3. KK Kosong
seperti yang tertera pada gambar dibawah ini : 
![Klas sosal](https://user-images.githubusercontent.com/25834335/95600555-eb070a00-0a84-11eb-8494-8a68d72fb84e.jpg)
![Klas sosal1](https://user-images.githubusercontent.com/25834335/95600565-ef332780-0a84-11eb-9cb7-61507ab6df77.jpg)

### Seperti apa yang diharapkan?
Jumlah KK yang ditampilkan sama dengan di  menu Home dan mengambil dari KK aktif saja

### Apa yang terjadi?
Jumlah Tidak sama

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3642
