### ISSUE TITLE
[bug] Form Indikator Analisis di modul Analisis ada yg kurang

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#3644]
### Bagaimana alurnya sampai muncul masalah?
1. Buka suatu master analisis
2. Masuk ke Indikator & Pertanyaan
3. Perhatikan bahwa ada kolom `Bobot` dan `Aksi Analisis`
4. Buat indikator baru atau edit Indikator yg ada.
5. Di form indikator, coba mengubah nilai `Bobot` dan setting `Aksi Analisis`. Ternyata tidak ditemukan.

### Seperti apa yang diharapkan?
Kembalikan form indikator supaya bisa mengubah `Bobot` dan `Aksi Analisis`. 

### Apa yang terjadi?
Sepertinya fitur ini sudah lama tidak jalan lagi. Mungkin harus melihat versi sebelum perubahan antarmuka ke AdminLTE, yaitu kembalikan ke v18.08.

### Informasi tambahan 

Untuk mengembalikan ke v18.08, lakukan sebagai berikut:
1. `git checkout v18.08`
2. Restore database ke contoh data awal yg tersedia di rilis tsb `contoh_data_awal_20180628.sql`

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | v20.10-pasca
| Versi PHP        | 
| System operasi   |

**Comment by ai-skematik** [comment]
iya, bobot sama aksi analisis tidak ada, sehingga sy membuat analisis dr form excell.

**Comment by eddieridwan** [comment]
> iya, bobot sama aksi analisis tidak ada, sehingga sy membuat analisis dr form excell.

@ai-skematik kalau menemukan error seperti itu, mohon selalu laporkan melalui issue, supaya bisa diperbaiki. Programmer hanya bisa memperbaiki error yg diketahui. Laporan di FB atau Telegram mudah tenggelam dan sulit ditemukan lagi.

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3648
