### ISSUE TITLE
Penambahan KK Baru dari Menu Keluarga Tidak Muncul Hasil Pencarian

### ISSUE THREAD

**Issue by lastingdone** [OpenSID/OpenSID#3645]
### Bagaimana alurnya sampai muncul masalah?
![1](https://user-images.githubusercontent.com/56072113/95668820-e3d61e00-0ba2-11eb-8553-73c416a80455.jpg)
saya coba menambah keluarga baru dari penduduk yg sudah ada 

### Seperti apa yang diharapkan?
hasil pencarian bisa menampilkan keluarga baru dari nik/nama dari data penduduk

### Apa yang terjadi?
![2](https://user-images.githubusercontent.com/56072113/95668832-0d8f4500-0ba3-11eb-8310-295affbee4b5.jpg)
hasil nya tidak keluar, sudah saya coba di web demo

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
@lastingdone yg ditampilkan hanya penduduk yg BUKAN anggota KK, yaitu hanya penduduk lepas dengan No. KK kosong. Untuk menambahkan penduduk yg masih anggota KK, pecah KK dulu supaya penduduk tersebut menjadi penduduk lepas.
