### ISSUE TITLE
[bug] Tombol Buka/Tutup Komentar artikel tidak berjalan

### ISSUE THREAD

**Issue by Jhiban-Khang** [OpenSID/OpenSID#3649]
Fungsi buka tutup komentar tidak berjalan sebagaimana mestinya
### Bagaimana alurnya sampai muncul masalah?

seharusnya jika ditutup artikel, maka komentar di artikel tidak muncul
### Seperti apa yang diharapkan?

komentar selalu muncul, bahkan sudah ditutupun masih muncul
### Apa yang terjadi?

sepertinya bugs
### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.10 Pasca
![Screenshot from 2020-10-12 08-40-36](https://user-images.githubusercontent.com/19563843/95696805-d2eee080-0c66-11eb-8e07-3b9718cdb105.png)

| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3656

**Comment by Jhiban-Khang** [comment]
Trimss
