### ISSUE TITLE
Gambar u/ Panduan

### ISSUE THREAD

**Issue by afa28** [OpenSID/OpenSID#3650]

**Comment by afa28** [comment]
Daftar Data Suplemen

Gambar 1
![111](https://user-images.githubusercontent.com/57283157/95719928-c08e9a00-0c9a-11eb-9b6f-f4b7d4e5d03d.png)

Gambar 2
![112](https://user-images.githubusercontent.com/57283157/95719942-c3898a80-0c9a-11eb-8efb-97fb5d45f2a7.png)

Gambar 3
![113](https://user-images.githubusercontent.com/57283157/95719946-c5534e00-0c9a-11eb-9d4d-0ed3af5e486e.png)

Gambar 4
![114](https://user-images.githubusercontent.com/57283157/95719950-c71d1180-0c9a-11eb-91bf-7f19f63a5ec2.png)

**Comment by afa28** [comment]
Gambar Suplemen Terdata

**Comment by afa28** [comment]
Cetak Peta Desa

![b1](https://user-images.githubusercontent.com/57283157/95919634-23d21680-0dd8-11eb-9b36-aa221486e07c.jpg)
![b2](https://user-images.githubusercontent.com/57283157/95919640-26347080-0dd8-11eb-8f87-53f98c9442e4.jpg)
![b3](https://user-images.githubusercontent.com/57283157/95919644-26cd0700-0dd8-11eb-82d3-726e71aad2f8.jpg)

**Comment by Fandha** [comment]
Customisasi warna dan print peta ini fitur premium y?

**Comment by afa28** [comment]
> Customisasi warna dan print peta ini fitur premium y?

ya

**Comment by afa28** [comment]
Slider

![artikel-1](https://user-images.githubusercontent.com/57283157/95945633-18e9a700-0e15-11eb-8d2b-68161f2f0623.png)
![artikel-2](https://user-images.githubusercontent.com/57283157/95945651-256dff80-0e15-11eb-8dbe-b201ffe9afe1.png)
![slid32](https://user-images.githubusercontent.com/57283157/95945779-6cf48b80-0e15-11eb-9d8d-99bb9f34cc3c.png)
![slider](https://user-images.githubusercontent.com/57283157/95945841-8a295a00-0e15-11eb-9302-8600a8e5176f.JPG)
![slider2](https://user-images.githubusercontent.com/57283157/95945906-ae853680-0e15-11eb-80e4-27abb8ed638c.JPG)
![slider31](https://user-images.githubusercontent.com/57283157/95945951-c65cba80-0e15-11eb-980e-fe8992856371.JPG)

**Comment by afa28** [comment]
https://github.com/OpenSID/OpenSID/wiki/Pengelolaan-Slide

**Comment by fusionid** [comment]
[kode_wilayah_administratif_pmdn72_2019.xlsx](https://github.com/OpenSID/OpenSID/files/5395654/kode_wilayah_administratif_pmdn72_2019.xlsx)

**Comment by afa28** [comment]
> [kode_wilayah_administratif_pmdn72_2019.xlsx](https://github.com/OpenSID/OpenSID/files/5395654/kode_wilayah_administratif_pmdn72_2019.xlsx)

OK pak @fusionid.

Untuk mengecek valid kode wilayah bisa dicek di modul IDM (untuk versi premium).

**Comment by ariandii** [comment]
bikin gambar begitu bagaimana caranya ya pak?
(yang bisa tambah panah dan text)

**Comment by afa28** [comment]
> bikin gambar begitu bagaimana caranya ya pak?
> (yang bisa tambah panah dan text)

Pakai aplikasi skitch

**Comment by afa28** [comment]
![111111111](https://user-images.githubusercontent.com/57283157/98254317-b9635f00-1fae-11eb-8e21-ea2c65b22f7a.JPG)

**Comment by afa28** [comment]
![2222222](https://user-images.githubusercontent.com/57283157/98257461-49ef6e80-1fb2-11eb-8535-100248bfd225.JPG)

**Comment by afa28** [comment]
![3333333](https://user-images.githubusercontent.com/57283157/98259946-51644700-1fb5-11eb-9d92-3f93d5867d79.JPG)

**Comment by afa28** [comment]
![313131](https://user-images.githubusercontent.com/57283157/98264403-6ee7df80-1fba-11eb-8d4a-6bee9baa471b.JPG)

**Comment by afa28** [comment]
![21212121](https://user-images.githubusercontent.com/57283157/98266747-3c8bb180-1fbd-11eb-8dcd-3739aef07c10.JPG)

**Comment by afa28** [comment]
![3131313131313](https://user-images.githubusercontent.com/57283157/98269471-5975b400-1fc0-11eb-9efe-e9fcf9ced0cb.JPG)

**Comment by afa28** [comment]
![41414141](https://user-images.githubusercontent.com/57283157/98270215-3ac3ed00-1fc1-11eb-8a30-0c6984f51dd0.JPG)

**Comment by roaddee** [comment]
![image](https://user-images.githubusercontent.com/45786885/104056136-90678080-5222-11eb-9594-6cf581e55638.png)
