### ISSUE TITLE
[bug] Filter pada Kependudukan > Keluarga > filter dusun

### ISSUE THREAD

**Issue by sandyvrianda** [OpenSID/OpenSID#3651]
### Bagaimana alurnya sampai muncul masalah?
Ketika membuka Kependudukan > Keluarga : Filter by Dusun. Lalu muncul HTTP ERROR 500

### Seperti apa yang diharapkan?
Tidak eror dan dapat memfilter

### Apa yang terjadi?
Sepertinya bug

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.10-pasca
| Versi PHP        | 
| System operasi   |
![WhatsApp Image 2020-10-12 at 5 49 33 PM](https://user-images.githubusercontent.com/28707598/95738627-b7f68d80-0cb3-11eb-8f50-574c8826c87f.jpeg)

**Comment by eddieridwan** [comment]
@sandyvrianda apakah terjadi di https://demo.opensid.my.id. Kalau di situs demo normal, sangat mungkin masalah ada di instalasi anda (server, script atau data anda).

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master`.
