### ISSUE TITLE
Jumlah Penerima Berbeda antara Menu Bantuan dan Website Desa

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#3653]
### Bagaimana alurnya sampai muncul masalah?
Data Penerima Bantuan Hilang dari Publikasi Website Desa, Walaupun pada Menu Bantuan, data tersebut masih ada.

Sebegai contoh BLT Dana Desa Tahap I di Menu Bantuan tertera 187 Penerima, namun di Website 185 Penerima.

Selisih 2 Angka yaitu, sipenerima telah meninggal dunia.
![image](https://user-images.githubusercontent.com/46939846/95808158-0a788e00-0d36-11eb-8bf4-352a71f846d7.png)

![image](https://user-images.githubusercontent.com/46939846/95808162-0cdae800-0d36-11eb-814a-79802137d0ef.png)

### Seperti apa yang diharapkan?
Penerima yang meninggal dunia tetap bisa muncul di website desa seperti halnya pada menu bantuan.

### Apa yang terjadi?
Suapaya sinkron antara bantuan real dengan publikasi di website, walaupun si penerima sudah meninggal dunia atau pindah.

**Comment by afa28** [comment]
Mungkin yg perlu diperhatikan adalah membedakan penggunaan tweb_penduduk dan penduduk_hidup. Gunakan penduduk_hidup untuk mendapatkan penduduk hidup (select penduduk) sedangkan tweb_penduduk digunakan saat menampilkan data yg tersimpan dr select penduduk hidup sebelumnya. Agar data yg tersimpan sebelumnya, baik itu penduduk mati/lainnya masih tersimpan. Mungkin jg berlaku di modul lainnya.

**Comment by eddieridwan** [comment]
@ariandii , mohon perhatikan di gambar di bawah kerancuan yg akan timbul. Tapi kalau ini dapat diterima oleh desa, ok. Sebaiknya perlu dimasukkan ke panduan, supaya bisa menjelaskan (@afa28 ). Alternatif lain, yg lebih sulit diterapkan, adalah memperlihatkan di statistik berapa penduduk/keluarga penerima yg mati/hilang/pindah. Kalau alternatif ini bermanfaat, sebaiknya dibuatkan issue baru. Atau penjelasan ditambahkan ke catatan di layar (yg terlihat merah).

![bantuan-3](https://user-images.githubusercontent.com/249563/97125144-082b2080-1787-11eb-85da-cbd892e69bda.jpg)

**Comment by ianskids** [comment]
Benar Pak @eddieridwan  @ariandii 
![awal](https://user-images.githubusercontent.com/60131374/97238119-35291300-181b-11eb-8fd6-5a732d917825.png)
Pada saaat Penerima bantuan ada yang Meniggal maka akan mengurangi jumlah bukan penerima bantuan
![kedua](https://user-images.githubusercontent.com/60131374/97238266-8f29d880-181b-11eb-9f33-cb862756d44f.png)

**Comment by eddieridwan** [comment]
@ianskids , ya. Seperti dijelaskan di atas, saya kira lebih tepat seperti itu, yaitu BUKAN PENERIMA dan TOTAL menghitung penduduk yg `hidup` saja dan tidak menghitung semua penduduk yg pernah ada. Tinggal ditambahkan penjelasan di `Catatan` yg merah itu.

**Comment by eddieridwan** [comment]
Sdh dicommit melalui PR #3709
