### ISSUE TITLE
Gagal Filter KK penduduk menggunakan filter Dusun

### ISSUE THREAD

**Issue by sandyvrianda** [OpenSID/OpenSID#3658]
### Bagaimana alurnya sampai muncul masalah?
Ketika memfilter KK penduduk menggunakan sortir by dusun, atau melihat daftar KK melalui menu dusun. Lalu muncul error 500

### Seperti apa yang diharapkan?
Berhasil menampilkan hasil filter

### Apa yang terjadi?
Gagal menampilkan data dan hanya erorr 500

### Informasi tambahan 
![gambar1](https://user-images.githubusercontent.com/28707598/95968352-873f6100-0e37-11eb-9b3d-5e4cb3285fe8.jpg)
![gambar2](https://user-images.githubusercontent.com/28707598/95968366-89a1bb00-0e37-11eb-9afd-4524afb2127b.jpg)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.10-pasca
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
@sandyvrianda , apakah sdh coba di https://demo.opensid.my.id? Tidak bermasalah di situ. Sebaiknya update ke pra-rilis terbaru.

**Comment by afa28** [comment]
Sy test tdk terjadi masalah, normal sj.

**Comment by eddieridwan** [comment]
@sandyvrianda issue ini akan kami tutup. Silakan buka lagi, kalau ada informasi tambahan yg bisa direplikasi di https://demo.opensid.my.id

**Comment by sandyvrianda** [comment]
Sudah di downgrade dari 20.10-pasca ke 20.10. Filter sudah normal kembali, saya cek ada perbedaan code antara kedua versi di donjo-app/models/Keluarga_model.php

**Comment by eddieridwan** [comment]
Selalu update ke versi terbaru. Kalau normal di https://demo.opensid.my.id, masalah ada di instalasi anda. Masalah ini tidak ditemukan di rilis 20.10-pasca terbaru. Di https://demo.opensid.my.id (v20.10-pasca terbaru) fitur ini normal.
