### ISSUE TITLE
[Analisis] Bug tampilan Laporan Per Indikator pada Analisi Prodeskel

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#3659]
### Bagaimana alurnya sampai muncul masalah?
Pada Kolom jawaban yg berisi nilai, setelah di koreksi/edit disimpan kembali kedua-duanya ditampilkan dalam laporan, baik nilai yng pertama dimasukkan maupun nilai nilai hasil koreksi, ada pun kolom2 nilai jawaban yng muncul dua kali dianataranya pada :
1. pada kolom jawaban "Pendapatan Per Bulan"
2. pada kolom jawaban "Pengeluaran per Bulan"
3. pada kolom jawaban "nilai harga produksi"

![image](https://user-images.githubusercontent.com/64481641/96022527-32bdd500-0e7b-11eb-8d72-6b76ed0f716c.png)

### Seperti apa yang diharapkan?
Penyesuaian Data sesuai dengan setelah di koreksi atau di edit....

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.10 pasca
| Versi PHP        | 7.4.10
| System operasi   |

**Comment by andifahruddinakas** [comment]
Pak @Zoel-WB bisa cek ulang issue ini menggunakan versi terbaru.

**Comment by andifahruddinakas** [comment]
Pak @Zoel-WB bisa cek ulang issue ini menggunakan versi terbaru.

**Comment by andifahruddinakas** [comment]
Pak @eddieridwan, ini sudah diperbaiki di issue https://github.com/OpenSID/OpenSID/issues/4498
