### ISSUE TITLE
[Layanan Mandiri] Penambahan Fitur Kirim PIN baru melalui email/Telegram ke warga

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#3663]
### Bagaimana alurnya sampai muncul masalah?
Setiap ada warga yang datang/menghubungi operator desa untuk meminta PIN pelayanan mandiri saat ini umumnya operator desa mencetak NIK dan PIN yang diserahkan kepada pemohon. Tetapi ini cara yg relatif kurang aman. 

### Seperti apa yang diharapkan?
Sistem secara otomatis mengirim PIN baru kepada pemohon melalui email atau akun Telegram yg sdh diverifikasi, jika ada. 

### Informasi tambahan 

Penambahan akun Telegram ke data penduduk dilakukan di issue https://github.com/OpenSID/OpenSID/issues/4556

Alternatif lain adalah mengirim melalui SMS atau WA. Untuk menggunakan SMS, pemasangan SMS perlu dibuat lebih mudah. Dan sebaiknya disiapkan versi install yg sudah berisi library SMS. Untuk menggunakan WA, diperlukan akses ke WA Gateway, yg umumnya berbayar.

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | v20.10
| Versi PHP        | 
| System operasi   |

**Comment by hasap86** [comment]
kebanyakan menggunakan versi online (hosting), apa sebaiknya menggunakan fasilitas pihak ke-3 untuk pengiriman SMS / Whatsapp, rekomendasi https://www.zenziva.id/ supaya bisa menggunakan sms atau Whatsapp.

**Comment by afa28** [comment]
Issue berkaitan dengan layanan mandiri di lanjutkan setelah issue PR https://github.com/OpenSID/premium/pull/47 atau issue https://github.com/OpenSID/OpenSID/issues/3696 selesai digabung.

**Comment by scqolbu24** [comment]
untuk issue ini sepertinya tidak bisa diimplementasi karena kondisinya email dan telegram belum diverifikasi.
untuk memverifikasi email dan telegram perlu login dulu ke layanan mandiri.

**Comment by eddieridwan** [comment]
@scqolbu24 , beberapa kasus PIN baru:

1. Pendaftaran layanan mandiri secara online (https://github.com/OpenSID/OpenSID/issues/1760). Proses pendaftaran termasuk verifikasi email/telegram. PIN baru akan tampil di layar, dan juga dikirim ke email/Telegram.
2. Pendaftar layanan mandiri yg sudah ada, dan telah melakukan verifikasi email/Telegram. Jika meminta PIN baru melalui Layanan Mandiri, PIN akan tampil di layar, dan juga dikirim ke email/Telegram
3. Pendaftar layanan mandiri yg sudah ada, dan telah melakukan verifikasi email/Telegram. Jika meminta PIN baru melalui operator, PIN baru akan dikirim ke email/Telegram
4. Pendaftar layanan mandiri yg sudah ada, dan belum melakukan verifikasi email/Telegram. Jika meminta PIN baru melalui operator, PIN baru ditampilkan di layar Admin, tetapi tidak dikirim ke email/Telegram. 

Jadi issue ini akan mengirim PIN baru ke email/Telegram yg telah diverifikasi untuk kasus (1), (2) dan (3). Tapi perhatikan bahwa (2) belum diterapkan. Yang ada di Layanan Mandiri saat ini adalah fitur Ganti Pin, bukan Reset PIN. Untuk Ganti PIN, PIN baru tidak dikirim ke email/Telegram. Hanya notifikasi bahwa PIN telah diganti.

**Comment by scqolbu24** [comment]
baik pak sudah paham, terimakasih.

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melalui pr https://github.com/OpenSID/premium/pull/538
