### ISSUE TITLE
Perjelas pesan apabila tidak ada penduduk lepas untuk ditambahkan ke KK

### ISSUE THREAD

**Issue by AliAshgar** [OpenSID/OpenSID#3664]
Penambahan anggota keluarga dari warga yang ada tidak berfungsi

**Comment by eddieridwan** [comment]
@AliAshgar selalu beri penjelasan rinci masalahnya. Apakah juga sudah melihat pesan di form penambahan anggota -- baca hati2. Pastikan ada penduduk yg 'lepas', yaitu penduduk yg bukan anggota KK yg sudah ada (belum memiliki No. KK). Issue yg tidak jelas tidak bisa ditindak-lanjuti.

**Comment by AliAshgar** [comment]
Udah bisa pak, bisa di closed issue ini

**Comment by eddieridwan** [comment]
Sepertinya pengguna sering tidak membaca pesan di form untuk menambah KK atau anggota KK dari warga. Issue ini untuk memperjelas pesan tersebut. Pada waktu tidak ada penduduk 'lepas' (yg belum memiliki No. KK), tampilkan pesan yang mencolok supaya jelas bagi pengguna bahwa mereka perlu memasukkan dulu penduduk lepas.

**Comment by AliAshgar** [comment]
Saya sudah melakukan lepas penduduk pak, tapi tadi masih blm bisa , ada sedikit error pada export database saya dan saya perbaiki dari dalam baru bisa lepas pendusul untuk di tambahkan ke anggota keluarga

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master`.
