### ISSUE TITLE
Layanan Mandiri

### ISSUE THREAD

**Issue by agitsafikri** [OpenSID/OpenSID#3665]
### Bagaimana alurnya sampai muncul masalah?
Setelah di hosting, list penduduk saat akan membuat pin tidak muncul

### Seperti apa yang diharapkan?
Muncul list penduduk

### Apa yang terjadi?
tidk muncul penduduk

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.19
| Versi PHP  7.4.11      | 
| System operasi linux  |

**Comment by afa28** [comment]
Sdah test di stus demo???

**Comment by eddieridwan** [comment]
Sepertinya ini masalah di instalasi anda. Mohon tanyakan di https://www.facebook.com/groups/OpenSID. 
Laporkan di issue hanya kalau sdh yakin memang error dan bukan masalah di instalasi anda. Selalu periksa di https://demo.opensid.my.id. Kalau normal di situ, masalah ada di instalasi anda. 

Ok. issue ini akan ditutup. Silakan buka lagi, kalau anda sdh pastikan memang error yg perlu diperbaiki.
