### ISSUE TITLE
Pemanggilan Nama Desa, Kecamatan, Kabupaten

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#3668]
### Bagaimana alurnya sampai muncul masalah?
Ketika ingin memanggil nama Desa, Kecamatan dan Kabupaten pada Cetak di menu keluarga maupun penduduk masih menggunakan **<?= get_identitas()?>**, supaya lebih memudahkan dalam  pemanggilan nama desa, kecamatan, kabupaten menggunakan  :
['nama_desa'], ['nama_kecamatan'], ['nama_kabupaten']
![image](https://user-images.githubusercontent.com/25834335/96258700-fb703500-0fee-11eb-833f-e90d49fe5308.png)

### Seperti apa yang diharapkan?
pemanggilan nama desa, kecamatan, kabupaten menggunakan  :
['nama_desa'], ['nama_kecamatan'], ['nama_kabupaten']

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
@MUHAMMADRANGSEL sepertinya ini pertanyaan teknis, bukan permintaan atau error. Silakan tanyakan di forum teknis di slack. Issue dimaksudkan untuk permintaan fitur baru atau melaporkan error. 

Harap bergabung di http://bit.ly/slack-opensid, dan bahas di situ.

Issue ini akan ditutup.

**Comment by MUHAMMADRANGSEL** [comment]
siap
