### ISSUE TITLE
Sediakan Tema Khusus Anjungan Desa Mandiri

### ISSUE THREAD

**Issue by mizwaruddin** [OpenSID/OpenSID#3669]
### Bagaimana alurnya sampai muncul masalah?
Saat ini baru tersedia dua tema resmi yang dikembangkan oleh OpenSID. Kedua tema tersebut belum mengakomodasi anjungan.

### Seperti apa yang diharapkan?
Tema untuk anjungan didesain: ketika layanan mandiri tidak digunakan, maka tema menampilkan slide yg berisi informasi desa (profil desa)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by balongbesuk** [comment]
login page plus slider?

seperti ini?

https://codepen.io/tim-gh/pen/JjPXOPd

**Comment by afa28** [comment]
Ad contoh atau gambaran???

**Comment by mizwaruddin** [comment]
![tema adm](https://user-images.githubusercontent.com/39736008/96402383-ee766000-11ff-11eb-8a40-587bc9a4baaf.jpg)

**Comment by mizwaruddin** [comment]
![page login layanan mandiri2](https://user-images.githubusercontent.com/39736008/96402438-15cd2d00-1200-11eb-8eb0-a10d3fc55e2f.jpg)

**Comment by eddieridwan** [comment]
@mizwaruddin @balongbesuk : perlu dipertimbangkan: apakah desa ingin warga berlama-lama di anjungan? Kalau tujuan anjungan untuk mempercepat/mempermudah layanan, seperti permohonan surat, maka warga tidak diinginkan berlama-lama di anjungan -- karena mungkin ada warga lain yg menunggu. 

Kalau fokus adalah pada mempercepat/mempermudah layanan, fitur yg disediakan perlu diarahkan khusus untuk itu, bukan untuk membaca atau melihat informasi umum.

**Comment by eddieridwan** [comment]
Mungkin yg terpikir adalah `papan informasi elektronik`, yg berbentuk layar sentuh besar yg disediakan khusus bagi warga untuk informasi desa, tapi bukan untuk layanan. Papan informasi tersebut dapat dipergunakan umum, tidak ada informasi pribadi, dan bisa dilihat ramai-ramai. Seperti papan informasi di mall-mall besar di kota2 besar.

**Comment by balongbesuk** [comment]
betul pak eddie, yang saya tangkap dari pertanyaan pak mirwan login page layanan mandiri sepertinya mencontoh d mesin ATM yang ketika tidak terpakai menampilkan iklan dll, harusnya bs diakali dengan Screen Saver bawaan Windows

mungkin harapan screen saver tersebut bisa jadi satu dengan opensidnya ketika tidak dipakai bisa menampilkan slider (entah itu gambar / Video panduan penggunaan anjungan / statistik desa)

**Comment by mizwaruddin** [comment]
Nah, ini yg saya maksudkan.

**Comment by afa28** [comment]
Tampil layanan mandiri sedang di desain ulang, silahkan beri masukan di issuenya.

**Comment by afa28** [comment]
> ![tema adm](https://user-images.githubusercontent.com/39736008/96402383-ee766000-11ff-11eb-8a40-587bc9a4baaf.jpg)
> 

Di desain yg baru, disediakan slider informasi setelah berhasil masuk layanan mandiri.
