### ISSUE TITLE
Cetak dan Unduh Data Penduduk hanya sampai 10.000

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#3670]
### Bagaimana alurnya sampai muncul masalah?
Ketika ingin mencetak Data Penduduk di Menu Kependudukan => Penduduk yang tercetak dan terunduh hanya sampai 10.000 jiwa, sedangkan banyak desa yang memiliki jumlah penduduk lebih dari 10.000
![data penduduk](https://user-images.githubusercontent.com/25834335/96263797-011d4900-0ff6-11eb-8c0b-8dcd27924ed3.png)

![10 000](https://user-images.githubusercontent.com/25834335/96263656-d29f6e00-0ff5-11eb-9f2d-2ee68824aaf6.png)

### Seperti apa yang diharapkan?
Penduduk yang tercetak dan terunduh tidak hanya sampai 10.000

### Apa yang terjadi?
Data Penduduk tidak tercetak / diunduh semua

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
Costume print:
1. Filed / data yg dibutuhkan
2. Orderby
3. Mulai dan sampai halaman (limit)

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3691
