### ISSUE TITLE
Form Input Bobot dan Aksi Analisis, Indikator Analisis Belum bisa disimpan 

### ISSUE THREAD

**Issue by Zulkarnaimni** [OpenSID/OpenSID#3671]
### Bagaimana alurnya sampai muncul masalah?
Input Bobot dan Aksi Analisis, Indikator Analisis Belum bisa disimpan 
![image](https://user-images.githubusercontent.com/64481641/96279394-cff64600-1000-11eb-8548-08c4e61f753e.png)
![image](https://user-images.githubusercontent.com/64481641/96279463-e3091600-1000-11eb-8dbb-dffd6dbd96ab.png)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.10 Pasca
| Versi PHP        | 7.4.10
| System operasi   |

**Comment by eddieridwan** [comment]
@Zulkarnaimni , di https://demo.opensid.my.id normal saja:
![bobot-1](https://user-images.githubusercontent.com/249563/96324177-28166200-106c-11eb-8cd5-f64a9425a58d.jpg)

Masalah sepertinya ada di instalasi anda. Apakah telah melakukan migrasi? Periksa di logs apakah ada error pada waktu menyimpan perubahan bobot dan aksi analisis.

**Comment by eddieridwan** [comment]
@Zulkarnaimni , baru lihat. Anda mencoba mengubah analisis Prodeskel. Analisis itu bawaan sistem (hal ini bisa terlihat di daftar master analisis), dan indikatornya saat ini tidak dapat diubah -- karena indikatornya berdasarkan kuisioner Prodeskel yg bersifat baku. Mohon jelaskan skenario mengapa perlu diubah dan apa yg perlu dapat diubah oleh desa. Apakah desa cukup bisa mengubah bobot dan aksi analisis?

**Comment by Zulkarnaimni** [comment]
Ini ada pemberitahuan dalam Catatan release Pak Eddie Ridwan pada baris 19. #3644 : Sekarang bobot dan aksi analisis indikator analisis bisa di ubah.

Karena catatan dimaksud saya coba input Pak Eddie Ridwan, Krn form inputnya juga ada, waktu disimpan sudah tidak bisa.  Berarti masih belum bisa dimasukkan oleh desa utk bobot dan aksi analisis pada analisis Prodeskel.

**Comment by eddieridwan** [comment]
@Zulkarnaimni untuk Prodeskel, bukannya `belum`, melainkan saat ini memang sengaja dinonaktifkan untuk analisis yg bersifaat bawaan sistem. Analisis yg bukan bawaan sistem dapat diubah, seperti AKP di contoh data awal. Seperti dijelaskan di atas, mohon berikan skenario mengapa analisis Prodeskel perlu diubah. Kalau ada kebutuhan yg jelas, nanti tentu kita sesuaikan.

**Comment by Zulkarnaimni** [comment]
Oke Pak Eddie  Ridwan, tadinya saya ikuti petunjuk dicatatan release saya fikir bobot dan aksi analisis pada Prodeskel sudah dibolehkan utk dirubah. sudah paham artinya yg dicatatan release utk desa bila ingin merancang atau menambah form analisa sendiri utk bobot dan aksi analisis sudah bisa dibuat dan ditentukan sendiri, oke Pak Eddie Rdidwan makasih banyak.

**Comment by Zulkarnaimni** [comment]
Oke Pak Eddie  Ridwan, tadinya saya ikuti petunjuk dicatatan release saya fikir bobot dan aksi analisis pada Prodeskel sudah dibolehkan utk dirubah. sudah paham artinya yg dicatatan release utk desa bila ingin merancang atau menambah form analisa sendiri utk bobot dan aksi analisis sudah bisa dibuat dan ditentukan sendiri, oke Pak Eddie Rdidwan makasih banyak.

**Comment by mizwaruddin** [comment]
@Zulkarnaimni Kalau sdh tidak dibutuhkan, tolong di close issue ini.
