### ISSUE TITLE
[Layanan Mandiri] PIN layanan mandiri baru harus diganti oleh warga dengan PIN berbeda

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#3672]
### Bagaimana alurnya sampai muncul masalah?
Saat ini PIN baru harus diganti oleh warga pada waktu login pertama kali. Tapi warga masih dapat menggunakan PIN yg sama. Juga saat ini warga tidak diharuskan mengganti PIN apabila di-reset oleh petugas desa.

### Seperti apa yang diharapkan?
PIN baru harus berbeda dengan PIN lama. 
Warga diharuskan mengganti PIN setelah di-reset oleh petugas desa.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | v20.10
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
https://github.com/OpenSID/premium/pull/11#discussion_r506807988

**Comment by afa28** [comment]
Issue berkaitan dengan layanan mandiri di lanjutkan setelah issue PR https://github.com/OpenSID/premium/pull/47 atau issue https://github.com/OpenSID/OpenSID/issues/3696 selesai digabung.

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR https://github.com/OpenSID/premium/pull/77
