### ISSUE TITLE
Sediakan menu Ganti PIN di layanan mandiri

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#3673]
### Bagaimana alurnya sampai muncul masalah?
Setelah login layanan mandiri, sekarang tidak ada fitur untuk warga mengganti PIN mereka. Saat ini untuk mengganti PIN mereka harus menghubungi petugas desa.

### Seperti apa yang diharapkan?
Sediakan tombol/menu di layanan mandiri supaya warga dapat mengganti PIN sendiri.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | v20.10
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
Tambahkan limit ganti pin layanan mandiri oleh warga. Misal 3 kali.

**Comment by eddieridwan** [comment]
Sdh dicommit ke `rilis-dev`
