### ISSUE TITLE
tidak bisa menambah data keluarga, dusun dan running teks, apa ada yang salah saat upload ke database?

### ISSUE THREAD

**Issue by ananghasan** [OpenSID/OpenSID#3675]
### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
@ananghasan sepertinya kesalahan pada waktu memasang OpenSID. Silakan tanyakan di https://www.facebook.com/groups/OpenSID. Di situ tempat bertanya pemasangan dan penggunaan OpenSID. Issue HANYA untuk melaporkan permintaan fitur atau masalah yg terbukti memang error yg harus diperbaiki.

Ok, issue ini akan ditutup. Silakan buka lagi kalau anda bisa sediakan info untuk menunjukkan memang error yg perlu diperbaiki.

**Comment by ananghasan** [comment]
Baik, terimakasih mas🙏

Pada tanggal Min, 18 Okt 2020 07:24, Eddie Ridwan <notifications@github.com>
menulis:
