### ISSUE TITLE
>>Automatisasi Data Statistik Analisis Prodeskel<<

### ISSUE THREAD

**Issue by muhtar-coder** [OpenSID/OpenSID#3677]
### Bagaimana alurnya sampai muncul masalah?
1. Input data statistik pada menu analisis saat ini harus di lakukan manual one by one (_data statistik umum penduduk_) 
    sedangkan sumber data tersebut di ambil dari database utama yang isian data statistik nya juga sama,sehingga sangat 
    memakan waktu dan hasilnya kemungkinan akan berbeda dengan data di biodata penduduk tersebut.

![image](https://user-images.githubusercontent.com/55665526/96341728-60955a80-10c3-11eb-8dc1-8dd529b7be2e.png)

### Seperti apa yang diharapkan?

- Data statistik yang terdapat pada isian menu analisis sama dengan data/biodata penduduk pada database penduduk utama.

- User dapat fokus pada perubahan data statistik di database penduduk utama saja yang lebih utama dan merupakan data 
   multikoneksi.

### Apa yang terjadi?
1. Penginputan data analisis lebih cepat dan effektif.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.10 premium
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
Mungkin Alurnya :
Hasil dari data modul analisis disimpan ke modul bersangkutan sesuai sasaran yg dipilih bukan sebaliknya. Untuk u/ setiap analisis / sensus sebaiknya penduduk ikut berperan aktif. Misalnya Input data sensus/survey di isi melalui layanan mandiri sesuai warga yg login (seperti sesus penduduk 2020 scr online). Jd Input data sensus/survey tdk hanya di input oleh operator.

Misal hasil analisis u/ mendapatkan kelas sosial yg hasilnya disimpan di modul keluarga, dll.

**Comment by muhtar-coder** [comment]
Bisa juga alurnya di balik jadi perubahan setelah analisis yang mempengaruhi data statistik penduduk yg bersangkutan,,,tapi jika di lihat kondisi sekarang : 
1. data statistik rata2 merupakan data statistik sesuai KTP/KK,sesuai biodata ybs.
2.  jumlah jenis keterangan data statistik penduduk sangat banyak kalo di hitung jumlah nya ribuan.
3.  rata2  keterangan data statistik penduduk sering di lakukan update sesuai  kejadian dan perubahan tersebut terjadinya 
    di data kependudukan per individu.misal ketika buat surat untuk cetak kk ataupun kajadian pada individu seperti nikah/cerai.

**Comment by muhtar-coder** [comment]
catatan : 
otomatisasi hanya untuk jenis keterangan yang umum dan sama seperti no akta lahir,status kawin,hub.keluarga,gol.darah,ibu/bapak dll.
kemudian untuk isian analisis lain nya yg tidak terdapat di data kependudukan tetap di isi manual berdasarkan survey,dan merupakan kegiatan partisipan,semacam isian peserta kelembagaan.

**Comment by muhtar-coder** [comment]
https://github.com/OpenSID/OpenSID/wiki/Analisis

**Comment by afa28** [comment]
Kayaknya sama yg dimaksu di issue https://github.com/OpenSID/OpenSID/issues/855

**Comment by muhtar-coder** [comment]
@afa28 betul bang sama dengan issue tsb,,,mohon maaf sy tidak tau jika ada issue sebelumnya yg sama,namun seperti yg di sampaikan bung @eddieridwan perlu penyesuaian dengan tabel isian/pilihan yg ada pada prodeskel online..

jika issue ini dapat di terapkan maka sensus versi opensid bukan lagi per sepuluh tahun tapi verval sensus setiap waktu... dan kami berencana akan mengadakan program analisis partisipatif untuk DDK dan DAK kedepan.
