### ISSUE TITLE
Kolom Keterangan pada Data Anggota Kelompok

### ISSUE THREAD

**Issue by Jhiban-Khang** [OpenSID/OpenSID#3681]
Dengan penambahan kolom keterangan, akan sangat membantu menambahkan data lain misal, luasan, jml ternak dll
### Bagaimana alurnya sampai muncul masalah?

adanya Kolom Keterangan pada FOrm Anggota KELOMPOK
### Seperti apa yang diharapkan?

penambahan kolom keterangan pada FOrm Anggota KELOMPOK
### Apa yang terjadi?

sebagai penyimpan data lain yang diperlukan 
### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.10
| Versi PHP        | 

| System operasi   |
![Screenshot from 2020-10-19 09-42-41](https://user-images.githubusercontent.com/19563843/96396068-718fba00-11f0-11eb-9699-accda75175ea.png)

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3692
