### ISSUE TITLE
Tambahkan Notifikasi "Peringatan Untuk Migrasi DB" Setelah Selesai Update

### ISSUE THREAD

**Issue by HerryWanda** [OpenSID/OpenSID#3682]
### Bagaimana alurnya sampai muncul masalah?
Banyak ditemukan beberapa desa pengguna yang tidak melakukan proses Migrasi DB setelah update, padahal itu hal yang wajib dilakukan setelah proses update OpenSID dari versi lama ke versi terbaru dilakukan. dan ini akan mengurangi kesalahan saat menggunakan OpenSID.

### Seperti apa yang diharapkan?
Diharapkan adanya notifikasi / peringatan yang tampil di dasbor admin setelah melakukan update OpenSID.
Contoh : OpenSID "namadesa" baru saja selesai di update  ke versi x.x.x, silakan lakukan MIGRASI DB .. !!!
               Klik Migrasi DB (jadi linknya langsung mengarah ke menu Migrasi DB)

### Apa yang terjadi?
Karna banyaknya pengguna baru, maka setelah update jika tidak dimigrasi DB maka akan ada error/ bug setelah update dikarnakan desa pengguna tidak melakukan migrasi DB setelah selesai update.

### Informasi tambahan
Contoh Notifikasi : 
 
![MIG](https://user-images.githubusercontent.com/32125282/96397166-1d3a0980-11f3-11eb-8ce7-db5520500d1d.png)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Setelah update ke rilis baru, migrasi otomatis dilakukan oleh sistem, asal proses persiapan rilis dilakukan dengan baik. Kadang2, pada waktu update dari satu versi pra-rilis ke rilis yg lebih baru, migrasi perlu dilakukan secara manual. Tapi biasanya juga dilakukan secara otomatis oleh sistem kalau programmer ingat menaikkan versi database. Tetapi kalau lupa, tidak ada cara untuk sistem memberitahu pengguna untuk melakukan --- karena kalau sistem bisa memberitahu, maka sistem juga dapat melakukan secara otomatis, yang merupakan solusi yg lebih memudahkan pengguna.

**Comment by afa28** [comment]
Pada  rilis baru, migrasi dilakukan secara otomatis.
