### ISSUE TITLE
[Bug] Analisis > Laporan Hasil Klasifikasi tidak tampil untuk Rumah Tangga dan Kelompok

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#3683]
### Bagaimana alurnya sampai muncul masalah?
1. Buat analisis dengan sasaran Rumah Tangga atau Kelompok. 
2. Isi kategori, indikator, klasifikasi, periode sensus, input data sensus seperlunya untuk menampilkan Laporan Hasil Klasifikasi
3. Buka Laporan Hasil Klasifikasi

Hasilnya kosong.

### Seperti apa yang diharapkan?
Seharusnya tampil laporan hasil klasifikasi untuk klasifikasi yg telah dibuat.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | v20.10
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
Bung @ianskids , mungkin bisa dilanjutkan.

**Comment by ianskids** [comment]
Siap bung @afa28

**Comment by eddieridwan** [comment]
Hasil Klasifikasi tidak tampil kalau nilainya sama dengan nilai minimal.

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3688
