### ISSUE TITLE
Nomor urut pada Cetak Rumah Tangga kosong

### ISSUE THREAD

**Issue by Jhiban-Khang** [OpenSID/OpenSID#3685]
Seharusnya muncul nomor urut pada cetak Rumah Tangga
### Bagaimana alurnya sampai muncul masalah?

Muncul Nomor Urut
### Seperti apa yang diharapkan?

Nomor Urut Muncul dari no.1 dst
### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.10 Pasca
![Screenshot from 2020-10-19 13-44-01](https://user-images.githubusercontent.com/19563843/96416189-e1666a80-1219-11eb-93df-a1b714d2fbe9.png)

| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
@afa28 apakah anda mengerjakan ini?

**Comment by afa28** [comment]
> @afa28 apakah anda mengerjakan ini?

Masih di laptop, belum sy PR. Masih di luar. Tp klw mau di krja silahkan pak.

**Comment by Jhiban-Khang** [comment]
Ga bisa ngoding pak

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3699
