### ISSUE TITLE
Data Isian Keterangan Surat Kuasa tidak tersimpan dalam riwayat surat

### ISSUE THREAD

**Issue by Jhiban-Khang** [OpenSID/OpenSID#3686]
Seharusnya muncul data keterangan yang sudah dientry atau sudah jadi surat
### Bagaimana alurnya sampai muncul masalah?

Muncul data Keterangan dalam History SURAT KUASA
### Seperti apa yang diharapkan?

Muncul data Keterangan dalam History SURAT KUASA
### Apa yang terjadi?

Mungkin BUGS
### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.10 Pasca
![KUASA](https://user-images.githubusercontent.com/19563843/96420996-69e80980-1220-11eb-8e9e-704c9a24961d.png)

| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
Pastikan anda melakukan testing di http://demo.opensid.my.id/ agar kami mudah mengecek issue yg anda laporkan.

**Comment by yonathanrizky** [comment]
pak @Jhiban-Khang untuk entry surat kuasa memang tidak ada form isian keterangan, sehingga tidak muncul keterangan dalam history surat kuasa, kalau mau menambahkan keterangan pada surat kuasa, bisa klik icon pensil dan tambahkan keterangannya pak
![image](https://user-images.githubusercontent.com/58940381/98465296-d55b4080-21fa-11eb-9cd7-b6745be7be8a.png)
![image](https://user-images.githubusercontent.com/58940381/98465303-de4c1200-21fa-11eb-8897-f98363277cf2.png)

**Comment by Jhiban-Khang** [comment]
Harus manual ya?

**Comment by Jhiban-Khang** [comment]
Ok , gpp toh itu bukn hal yang urgent dan esensial

**Comment by balongbesuk** [comment]
ganti form format coding keterangannya

**Comment by mizwaruddin** [comment]
@Jhiban-Khang Klo dirasa sudah tidak dibutuhkan tolong di close issue ini.

**Comment by agungsugiarto** [comment]
@Jhiban-Khang, issue ini saya tutup. Untuk menambahkan keterangan silahkan di update manual seperti langkah yg dibilang bapak @yonathanrizky. Terima kasih
