### ISSUE TITLE
Penambahan Peraturan Desa jenis PERKADES 

### ISSUE THREAD

**Issue by Jhiban-Khang** [OpenSID/OpenSID#3687]
OPENSID Reguler belum menyediakan Kelompok PERKADES (PERATURAN KEPALA DESA) dalam modul Produk Hukum 
### Bagaimana alurnya sampai muncul masalah?

Adanya penambahan jenis Produk Hukum ->  PERKADES
### Seperti apa yang diharapkan?

PERATURAN KEPALA DESA
### Apa yang terjadi?

Mungkin usulan ini sudah diterapkan pada PREMIUM, tetapi alangkah baiknya perlu ditambahkan dalam OPENSID REGULER karena ini sangat ESENSIAL dan penting dalam dokumentasi produk hukum
### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.10 Pasca
![perkades](https://user-images.githubusercontent.com/19563843/96421818-6ef98880-1221-11eb-8a30-5f87a553d750.png)

| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
@Jhiban-Khang fitur yg sdh diterapkan di Premium akan masuk rilis umum 3-bulan setelah dilunasi. Jadi fitur yg sdh masuk Premium TIDAK akan diduplikasi di rilis umum. Khususnya mengenai Buku Administrasi Umum, fitur tsb ada di rilis v20.09-premium, yg sudah lunas, dan akan masuk ke rilis umum v21.01.

Desa yg tidak bersedia menunggu fitur Premium masuk ke rilis umum, silakan  ambil layanan Fitur Premium. Dengan berlangganan, anda akan membantu mempercepat fitur di rilis Premium masuk ke rilis umum -- dan tentunya membantu pengembangan OpenSID.

Mohon diingat, adanya Fitur Premium bertujuan supaya desa ikut bertanggung jawab atas pengembangan OpenSID. Keberlanjutan OpenSID hanya mungkin apabila desa yg mengambil manfaat menganggarkan supaya OpenSID terus dikembangkan. Dan mohon diperhatikan, ke depan semua fitur baru akan masuk ke rilis Premium dulu.

**Comment by mizwaruddin** [comment]
@afa28 sdh ada di premium.
