### ISSUE TITLE
Tambah beberapa anggota kelompok sekaligus.

### ISSUE THREAD

**Issue by lastingdone** [OpenSID/OpenSID#3690]
### Bagaimana alurnya sampai muncul masalah?
kurang Huruf pada Kata "Kelompok" di fitur Cetak
![image](https://user-images.githubusercontent.com/56072113/96588634-1bb13400-130e-11eb-8116-6f094c54f82a.png)

### Seperti apa yang diharapkan?

Bisa ditambahkan Fitur Tambah Beberapa Anggota pada Button Tambah Anggota Kelompok agar penginputan jadi lebih efisien.
![image](https://user-images.githubusercontent.com/56072113/96589075-9c703000-130e-11eb-8b6c-02f157241295.png)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
U/ Masalah kessalahan penulisan sudah diperbaiki pd PR #3692

Untuk kasus ini bisa lihat di modul program bantuan > Detail > Tambah Peserta.

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3706
