### ISSUE TITLE
Sebutan Kepala Desa/Kelurahan

### ISSUE THREAD

**Issue by ananghasan** [OpenSID/OpenSID#3693]
### Bagaimana alurnya sampai muncul masalah?
Kepala Desa merupakan sebutan secara umum untuk daerah yang menggunakan kata Desa, namun di beberapa daerah dalam hal ini Aceh, Desa di sebut Gampong, tapi sebutan Kepala Desanya bukan Kepala Gampong tapi Keuchik, mohon dapat diberikan menu ubah untuk penyebutan tersebut sesuai dengan daerahnya 

### Seperti apa yang diharapkan?
Tersedianya menu perubahan jabatan kepala desa sesuai daerah masing2

### Apa yang terjadi?
Saat cetak laporan tertulis Kepala Gampong yang seharusnya cukup Keuchik

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
Catatan u/ PR :
1. Tambah setting aplikasi u/ sebutan nama $this->setting->sebutan_dusun
2. Ubah semua bagian yg menggunakan penulisan kepala $this->setting->sebutan_dusun

**Comment by ianskids** [comment]
@ananghasan apakah sudah mencoba dilakukan perubahan di Menu Identitas desa? 
apakah itu belum memenuhi kebutuhan seperti yang di minta?

![ss](https://user-images.githubusercontent.com/60131374/96938151-e0705a00-14f3-11eb-982e-00782329a4ae.png)

**Comment by ananghasan** [comment]
Sebelumnya saya ucapkan terimakasih atas fasilitas yang diberikan percuma
demi membangun Indonesia dari Desa, sejauh yg saya lihat OpenSID sudah
sangat bagus utk diterapkan di Desa, namun ada bbrpa kendala saya saat
cetak laporan statistik dimana jabatan Keuchik menjadi Kepala Desa/ Lurah,
mohon dapat arahan dari para pahlawan Desa🙏🙏🙏


Pada tanggal Jum, 23 Okt 2020 05:52, Ians Shinichi Kudo <
notifications@github.com> menulis:

**Comment by ianskids** [comment]
Bisa informasikan format laporan Mana saja yang belum sesuai?

**Comment by ananghasan** [comment]
Sejauh ini yg saya dapat baru dilaporan cetak statistik mas🙏🙏🙏, saya
tidak bisa screenshot krn dikunci oleh aplikasi

Salam

Pada tanggal Jum, 23 Okt 2020 13:50, Ians Shinichi Kudo <
notifications@github.com> menulis:

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3704

**Comment by ananghasan** [comment]
Terimakasih banyak bapak, InsyaAllah selalu dalam kondisi sehat wal'afiat
agar terus bisa berkarya utk Desa

Pada tanggal Sab, 24 Okt 2020 16:51, Eddie Ridwan <notifications@github.com>
menulis:
