### ISSUE TITLE
Kesalahan menampilkan detail anggota RTM

### ISSUE THREAD

**Issue by Jhiban-Khang** [OpenSID/OpenSID#3694]
tampilan tidak mengarah ke daftar Ruta sesuai data yang dipilih
### Bagaimana alurnya sampai muncul masalah?

seharusnya mengarah ke Ruta 
### Seperti apa yang diharapkan?

Tampil normal menampilkan Daftar Anggota Ruta
### Apa yang terjadi?

Mungkin Bugs
### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.10 Pasca di Demo https://d
![Screenshot at 2020-10-21 07-42-24](https://user-images.githubusercontent.com/19563843/96659624-965f6b00-1371-11eb-934c-fc286428b4ad.png)
![Screenshot at 2020-10-21 07-40-08](https://user-images.githubusercontent.com/19563843/96659637-9cede280-1371-11eb-89fe-63d7a37b5334.png)

emo.opensid.my.id/
| Versi PHP        | 
| System operasi   |

**Comment by Jhiban-Khang** [comment]
setelah saya cek, hampir di semua link ruta pada statistik tidak menampilkan daftar ruta yang benar .. blank semua

**Comment by afa28** [comment]
> setelah saya cek, hampir di semua link ruta pada statistik tidak menampilkan daftar ruta yang benar .. blank semua
> 

Ini bukan bermasalah di modul statistik, tp di modul penduduk. Krn adnya perubahan link detail anggota.

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3698
