### ISSUE TITLE
tanda Merah pada Notifikasi baris atas 

### ISSUE THREAD

**Issue by Jhiban-Khang** [OpenSID/OpenSID#3695]
seharusnya muncul tanda jika ada yang mengisi
### Bagaimana alurnya sampai muncul masalah?

Tanda selalu merah, walaupun sudah tidak ada notiifikasi yg masuk
### Seperti apa yang diharapkan?

Menganggu untuk memantau notifikasi
### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.10 pasca di demo
![Screenshot at 2020-10-21 07-51-11](https://user-images.githubusercontent.com/19563843/96660045-be9b9980-1372-11eb-969b-ad25297be837.png)

| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master`.
