### ISSUE TITLE
Perbaiki tampilan beranda Layanan Mandiri

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#3696]
### Bagaimana alurnya sampai muncul masalah?
Tampilan beranda Layanan Mandiri saat ini kurang menarik dan sulit dikembangkan. 

![dashboard-layanan](https://user-images.githubusercontent.com/249563/96674503-b06e6d00-13b4-11eb-9c3b-e879c3f7118f.jpg)

### Seperti apa yang diharapkan?
Perlu dirancang ulang supaya lebih menarik dan lebih mudah ditambahkan fitur baru.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | v20.10
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
Pak @Zulkarnaimni, @MUHAMMADRANGSEL, @M-A-Haris , @ariandii , @ai-skematik , dll bisa usulkan rancangan tampilan layanan mandiri yg mau diterapkan.

**Comment by balongbesuk** [comment]
karena opensid sudah include Adminlte di dasboard adminnya, gmn kl coba dibikin ikut seperti tampilan adminlte saja dasboard layanan mandiri, sekalian upgrade ke adminlte3 untuk admin kedepannya nanti.

**Comment by MUHAMMADRANGSEL** [comment]
usul bagus

Pada tanggal Kam, 22 Okt 2020 18.18, balongbesuk <notifications@github.com>
menulis:

**Comment by M-A-Haris** [comment]
Permohonan surat urutan pertama, ketimbang cetak KK atau yang lainnya

**Comment by afa28** [comment]
![IMG_20201101_184947_412.jpg](https://user-images.githubusercontent.com/57283157/97800805-dc1e0c80-1c6a-11eb-8ae2-f368e0956d8d.jpg)

![IMG_20201101_184943_816.jpg](https://user-images.githubusercontent.com/57283157/97800809-df18fd00-1c6a-11eb-814a-aef985e405d6.jpg)

**Comment by balongbesuk** [comment]
side panel kirinya gak ada mas @afa28 buat menu?

**Comment by afa28** [comment]
> side panel kirinya gak ada mas @afa28 buat menu?

Tidak ad, ini pakai yg top navigasi di admin lte. Jd menu2nya ad di bagian atas.

**Comment by eddieridwan** [comment]
Bung @afa28 , mohon perkenalkan konsep anda di group FB. Dan ajak anggota komunitas untuk memberi masukan. Supaya bisa segara kita sepakati untuk diterapkan.

**Comment by balongbesuk** [comment]
pendapat saya jika memiliki menu disebelah kiri, agar bisa menambah menu dan submenu untuk pengembangan layanan mandiri kedepannya,

yang mas tampilkan di SS tetap ada menjadi bagian dasboard layanan mandiri,

cuma pendapat saja pengembangan tetap ada di programer, :smile:

**Comment by afa28** [comment]
Bgmna ini pak @eddieridwan, apa sudah bisa sy eksekusi sesuai SS yg sy kirim atau ada desain lain yg mau diterapkan???

**Comment by eddieridwan** [comment]
Ya, silakan. Pertimbangkan masukan yg diberikan, seperti dari @balongbesuk di atas -- dan langsung terapkan. Terima kasih.

**Comment by afa28** [comment]
> Ya, silakan. Pertimbangkan masukan yg diberikan, seperti dari @balongbesuk di atas -- dan langsung terapkan. Terima kasih.
> 
> Menu lengkap bisa di sebelah kiri, sedangkan tombol untuk menu yg paling sering digunakan.

Jd layout yg digunakan `fixed `ya pak @eddieridwan sama dgn layout view admin yg sekrang.

**Comment by eddieridwan** [comment]
Tidak harus fixed. Gunakan layout yg enak digunakan pada HP.

**Comment by afa28** [comment]
![121](https://user-images.githubusercontent.com/57283157/103029940-66a92b00-458d-11eb-9594-058822921686.JPG)
![122](https://user-images.githubusercontent.com/57283157/103029948-6872ee80-458d-11eb-86c5-418ec4879602.JPG)
![123](https://user-images.githubusercontent.com/57283157/103029950-690b8500-458d-11eb-85de-9b4a06c80500.JPG)
![124](https://user-images.githubusercontent.com/57283157/103029951-69a41b80-458d-11eb-9633-125f8aa95e35.JPG)
![1235](https://user-images.githubusercontent.com/57283157/103029955-6ad54880-458d-11eb-890c-d8f4f2ac9c93.JPG)

Tambahan :
1. Surat dan pesan (masih dalam penyesuaian ulang).
2. Surat terdiri atas : 
    - Layanan cetak surat
    - Status permohonan surat 
    - Daftar / arsip surat yg sudah dibuat
3. Ganti PIN akan disimpan di bagian dalam / bukan lg di login ganti pin (masih dalam penyesuaian ulang).

Kalau ada tambahan silahkan tinggalkan komentar.

**Comment by afa28** [comment]
Setelah memindahkan beberapa controller dan mengujinya, layanan mandiri pesan error / tidak berjalan sebagaimana menstinya.

**Comment by afa28** [comment]
![1](https://user-images.githubusercontent.com/57283157/103264289-dc255900-49dc-11eb-8b80-6fdbe0ecca47.JPG)
![2](https://user-images.githubusercontent.com/57283157/103264298-e21b3a00-49dc-11eb-927b-deade41f27fd.JPG)
![3](https://user-images.githubusercontent.com/57283157/103264302-e5162a80-49dc-11eb-8212-a207acd01e77.JPG)
![4](https://user-images.githubusercontent.com/57283157/103264306-e8a9b180-49dc-11eb-8be0-69b0f4fc44df.JPG)
![5](https://user-images.githubusercontent.com/57283157/103264317-ec3d3880-49dc-11eb-883a-48758a844188.JPG)
![6](https://user-images.githubusercontent.com/57283157/103264323-ef382900-49dc-11eb-9a9f-bfd2008c4af5.JPG)
![11](https://user-images.githubusercontent.com/57283157/103264330-f2331980-49dc-11eb-8619-43840c943d45.JPG)
![21](https://user-images.githubusercontent.com/57283157/103264335-f52e0a00-49dc-11eb-8537-62be086ce703.JPG)
![22](https://user-images.githubusercontent.com/57283157/103264338-f9f2be00-49dc-11eb-818a-4129e1d7e1d7.JPG)
![23](https://user-images.githubusercontent.com/57283157/103264340-fe1edb80-49dc-11eb-8b12-3300b639d17c.JPG)

**Comment by eddieridwan** [comment]
Sdh dicommit ke `rilis-dev` melalui PR https://github.com/OpenSID/premium/pull/47
