### ISSUE TITLE
Import hasil analisis menggunakan excel mengalami eror dan data tidak tersimpan apabila nomor RTM lebih dari 11 digit

### ISSUE THREAD

**Issue by WAHYUDIK** [OpenSID/OpenSID#3701]
### Bagaimana alurnya sampai muncul masalah?
mencoba import hasil analisis AKP menggunakan fitur import excel mengalami eror dan data tidak tersimpan, keterangan eror di folder logs seperti gambar dibawah ini:

![image](https://user-images.githubusercontent.com/31026980/96945686-9cd41b00-1508-11eb-9caa-2d8c2e38256a.png)

[log-2020-10-17.zip](https://github.com/OpenSID/OpenSID/files/5426704/log-2020-10-17.zip)

### Seperti apa yang diharapkan?
kedepan agar bisa tersimpan hasil import bagi nomor RTM lebih dari 11 digit.

### Apa yang terjadi?

saat ini masih belum bisa tersimpan, jika langsung mengisi di sistem masih bisa tersimpan.
### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20. 10-pasca
| Versi PHP        | 
| System operasi   |

**Comment by pandigresik** [comment]
kalau lihat pesan errornya, kolom id_subjek kurang lebar sehingga tidak cukup menampung data tersebut

**Comment by afa28** [comment]
![1111111111](https://user-images.githubusercontent.com/57283157/98831478-33dc2500-246e-11eb-9866-326e72e1eff7.JPG)

![123456](https://user-images.githubusercontent.com/57283157/98831622-62f29680-246e-11eb-9f78-95554d69c0e3.JPG)

Pd tweb_rtm u/ field no_kk (no_rtm) menggunakan varchar (30) sedangkan analisis_respon u/ field id_subject (sesuai sasaran = nik, no_kk, no_rtm) menggunakan int (11). Ini yg perlu disamakan, krn saat ini u/ no_rtm di modul rtm menerima inputan max 30 karakter sedangakan di analisis_respon max 11 digit.

**Comment by WAHYUDIK** [comment]
> ![1111111111](https://user-images.githubusercontent.com/57283157/98831478-33dc2500-246e-11eb-9866-326e72e1eff7.JPG)
> 
> ![123456](https://user-images.githubusercontent.com/57283157/98831622-62f29680-246e-11eb-9f78-95554d69c0e3.JPG)
> 
> Pd tweb_rtm u/ field no_kk (no_rtm) menggunakan varchar (30) sedangkan analisis_respon u/ field id_subject (sesuai sasaran = nik, no_kk, no_rtm) menggunakan int (11). Ini yg perlu disamakan, krn saat ini u/ no_rtm di modul rtm menerima inputan max 30 karakter sedangakan di analisis_respon max 11 digit.

ya lebih baik inputan max disama ratakan menjadi 30 karakter,

**Comment by ZER07URN** [comment]
> > ![1111111111](https://user-images.githubusercontent.com/57283157/98831478-33dc2500-246e-11eb-9866-326e72e1eff7.JPG)
> > ![123456](https://user-images.githubusercontent.com/57283157/98831622-62f29680-246e-11eb-9f78-95554d69c0e3.JPG)
> > Pd tweb_rtm u/ field no_kk (no_rtm) menggunakan varchar (30) sedangkan analisis_respon u/ field id_subject (sesuai sasaran = nik, no_kk, no_rtm) menggunakan int (11). Ini yg perlu disamakan, krn saat ini u/ no_rtm di modul rtm menerima inputan max 30 karakter sedangakan di analisis_respon max 11 digit.
> 
> ya lebih baik inputan max disama ratakan menjadi 30 karakter,

Alangkah baiknya menggunakan parameter id langsung, tdk menggunakan nik/no_kk/lainnya. Nanti kasusnya sama dgn program bantuan 😀

**Comment by afa28** [comment]
pak @WAHYUDIK , ada contoh file import yg bisa sy gunakan???

**Comment by agungsugiarto** [comment]
Pak @WAHYUDIK mohon kirim contoh file importnya ke telegram saya https://t.me/meagungsugiarto
