### ISSUE TITLE
Perbaiki tombol Ubah Data Kelompok

### ISSUE THREAD

**Issue by abmuj18** [OpenSID/OpenSID#3702]
Bug Saat Ubah Data Kelompok

### Bagaimana alurnya sampai muncul masalah?
Ketika saat mengklik tombol Ubah Data Kelompok menampikan form Tambah Data Kelompok Baru

### Seperti apa yang diharapkan?
Menampilkan Form Ubah Data Kelompok

### Apa yang terjadi?
Ketika mengklik tombol Ubah Data Kelompok maka tampilkan Form Ubah Data Kelompok

### Informasi tambahan 
https://demo.opensid.my.id/kelompok/form/2

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.10-pasca
| Versi PHP        |  
| System operasi   |

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3703
