### ISSUE TITLE
Ubah Masa Berlaku di Surat Keterangan Usaha

### ISSUE THREAD

**Issue by ahmadngudi** [OpenSID/OpenSID#3705]
### Bagaimana alurnya sampai muncul masalah?
saat ini Surat Keterangan Usaha Masa Berlaku nya hanya 1 Bulan

![surat usaha](https://user-images.githubusercontent.com/57133748/97068165-6f15d180-15ef-11eb-9311-21f2ad2c4222.jpg)

### Seperti apa yang diharapkan?
Surat Keterangan Usaha masa Berlakunya otomatis 1 Tahun

### Apa yang terjadi?
harus edit dulu masa berlakunya.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sepertinya ketentuan/kebiasaan berbeda antar desa, meskipun untuk jenis surat yg sama. Untuk memudahkan mungkin sediakan pilihan (dropdown?) untuk masa berlaku yg umum digunakan, seperti tiga bulan, enam bulan dan 12 bulan. Dan biarkan default 1 bulan, karena sepertinya ini yg berlaku pada kebanyakan surat keterangan.

**Comment by Jhiban-Khang** [comment]
setuju, default 1 bulan saja. jika mau lebih dari itu ketik manual saja

**Comment by yonathanrizky** [comment]
@ahmadngudi untuk masa berlaku surat keterangan usaha 1 thn bisa diubah di pengaturan surat tersebut pak, pengaturan default masa berlaku surat sudah tersedia di versi 20.11 pasca
![image](https://user-images.githubusercontent.com/58940381/99753704-5a0e5e80-2b19-11eb-8749-cb9e8d5065d5.png)

**Comment by afa28** [comment]
Sudah di `master`
