### ISSUE TITLE
Login Terakhir tidak berfungsi

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#3707]
### Bagaimana alurnya sampai muncul masalah?
Saat membuka menu Pengaturan -> Pengguna, sebelumnya selalu update Login Terakhir yang dilakukan oleh pengguna bersangkutan. Namun saat ini semenjak 11 September 2020 selain Level Administrator tidak terekam.

### Seperti apa yang diharapkan?
Normal seperti sedia kala.

### Apa yang terjadi?
Agar dapat memantau user yang sedang login terakhir.

**Comment by yonathanrizky** [comment]
saya coba di demo bisa pak @ariandii , login terakhir dengan level kontributor
![image](https://user-images.githubusercontent.com/58940381/97567353-4b042700-1a19-11eb-85c2-76b69a30fb9f.png)

**Comment by ariandii** [comment]
Bisa coba level Operator.

**Comment by eddieridwan** [comment]
> Bisa coba level Operator.

Operator juga tercatat normal. Silakan coba di https://demo.opensid.my.id

Sepertinya masalah di server anda. Coba cek logs.

**Comment by ianskids** [comment]
Sepertinya Login Terakhir tidak tercatat karena user keluar tidak menggunakan tombol `KELUAR` tetapi karena sesi habis, 
Apakah ini perlu perubahan dicatat pada saat melakukan login/masuk?

**Comment by ariandii** [comment]
harapannya, dapat mencatat waktu akhir.

karena kendala saat ini tidak dapat memantau apakah user operator tersebut menggunakan opensid atau tidak dalam kurun waktu tersebut.

mungkin bisa diterapkan record login nya saja. jadi setiap login bisa terekam waktu nya.

**Comment by eddieridwan** [comment]
@ianskids waktu keluar sebenarnya tidak perlu dicatat, karena tidak bisa dipastikan. Ada pengguna yg keluar secara eksplisit (menggunakan logout) dan ada karena sesi habis saja. Yg tercatat saat ini hanya waktu login -- dan yg tercatat hanya satu kali saja, yaitu yg terakhir. Saya kira itu sudah cukup. Untuk issue ini, yg perlu dilakukan:
1. pastikan login terakhir tercatat untuk semua tingkat pengguna. Kalau sudah ok, berarti masalah ada di server pelapor. 

Saya kira tidak banyak manfaat memantau apakah seorang operator menggunakan OpenSID atau tidak dalam kurun waktu tertentu. Yang lebih bermanfaat adalah adanya log untuk setiap tindakan di OpenSID yg `**patut dipantau**`. Log tersebut mencatat waktu, siapa yg melakukan dan apa yg dilakukan. Misalnya di log itu tercatat bahwa si A mengubah data penduduk pada tgl/jam B. Kalau ada log seperti ini, bisa dilaporkan apa saja kegiatan seseorang operator dalam kurun waktu tertentu. 

Solusi untuk log semacam ini perlu dirancang hati2, supaya bisa digunakan untuk segala macam tindakan, mudah ditambahkan ke script dan dilakukan secara efisien.

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3857
