### ISSUE TITLE
Muat halaman Dashboard lambat

### ISSUE THREAD

**Issue by abmuj18** [OpenSID/OpenSID#3710]
### Bagaimana alurnya sampai muncul masalah?
Ketika akan masuk ke Dashboard admin halaman yang di muat lambat bahkan tidak tampil sama sekali

### Seperti apa yang diharapkan?
Normal seperti sebelumnya

### Apa yang terjadi?
Ketika masuk ke Dashboard admin halaman yang di muat lambat dan di folder **logs** terjadi kesalahan/Error seperti berikut:

`ERROR - 2020-10-26 00:00:22 --> Query error: MySQL server has gone away - Invalid query: SELECT COUNT(id) AS jumlah FROM tweb_penduduk WHERE status_dasar = 1`
`ERROR - 2020-10-26 00:00:22 --> Severity: error --> Exception: Call to a member function result_array() on boolean /home/xxxxxxxxxxx/public_html/sid/donjo-app/models/Header_model.php 58`

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.10-pasca
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
@abmuj18 perhatikan error yg tampil: `MySQL server has gone away`. Menunjukkan MySQL bermasalah -- tidak bisa diakses. Jadi masaiah di hosting atau server. 

Mohon hanya gunakan issue untuk masalah yg sdh diyakinkan memerlukan perbaikan script. Kalau masalah penggunaan/hosting/pemasangan, harap tanyakan di https://www.facebook.com/groups/OpenSID.

Issue ini akan ditutup. Silakan buka kembali kalau ada informasi tambahan mengenai masalah yg memerlukan perbaikan script.
