### ISSUE TITLE
Bug Report Import Keuangan Open SID 

### ISSUE THREAD

**Issue by algasyali** [OpenSID/OpenSID#3711]
### Bagaimana alurnya sampai muncul masalah?
Saya udah melakukan Import database sesuai prosedur tapi hasil realisasi sebagian tidak tampil di laporan keuangan kalo jadi hasil perhitungannya selisih
Data Pendapatan dan anggaran udah betul Sisa realisasi belanja yang selisih ada yang tidak muncul

### Seperti apa yang diharapkan?
Menampilkan data realisasi yng tidak tampil

![Uploda](https://user-images.githubusercontent.com/45220793/97176493-fde14480-17cf-11eb-83a7-07ee2e8b42e2.png)
![dfsgdf](https://user-images.githubusercontent.com/45220793/97176538-0b96ca00-17d0-11eb-9bea-03b78ea5c180.png)

### Apa yang terjadi?
Sebagian data Kosong padahal sudah di input di sisekeudes

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 7.2
| System operasi   | Windows 10 Update 2019

Database Backup dari Siskeudes
[DataAPBDES2020_2020-10-26.zip](https://github.com/OpenSID/OpenSID/files/5439030/DataAPBDES2020_2020-10-26.zip)

**Comment by algasyali** [comment]
![dfsgdf](https://user-images.githubusercontent.com/45220793/97166437-3711b880-17c0-11eb-827e-4bad1e8180ad.png)

**Comment by algasyali** [comment]
![Uploda](https://user-images.githubusercontent.com/45220793/97166477-485ac500-17c0-11eb-8477-f14dc1132d0d.png)
Selisih dengan data Realisasi

**Comment by fusionid** [comment]
Mesti diperjelas pos mana yg berbeda, apakah di Pendapatan, Belanja atau Pembiayaan ?

**Comment by agungsugiarto** [comment]
Pak @fusionid, apakah bisa membantu untuk mereplikasi bug ini saya tidak bisa mencovert ke csv.

https://github.com/OpenSID/OpenSID/files/5439030/DataAPBDES2020_2020-10-26.zip

**Comment by afa28** [comment]
![1111](https://user-images.githubusercontent.com/57283157/121678722-1ba6b400-caea-11eb-962a-1d2415226f65.png)

Saya coba import ada 2 isi data desa, desa yang mana pak @algasyali???

**Comment by afa28** [comment]
Silahkan buka issue ini jika masih bermasalah.
