### ISSUE TITLE
Tidak ada Form Artikel pada Hak Akses Kontributor

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#3712]
### Bagaimana alurnya sampai muncul masalah?
Seorang user Kontributor melaporkan bahwa saat mengklik tambah Artikel, tidak bisa masuk ke form artikel sebagaimana mestinya.

### Seperti apa yang diharapkan?
Utk user administrator masih normal seperti pada versi sebelumnya, tidak ada masalah.

### Apa yang terjadi?
Normal seperti sediakala.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
@ariandii , apakah masalah ini ditemukan juga di https://demo.opensid.my.id?

**Comment by ariandii** [comment]
Iya pak.

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3714
