### ISSUE TITLE
Beberapa Isian di Form Penduduk belum tervalidasi

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#3715]
### Bagaimana alurnya sampai muncul masalah?
Menu Kependudukan=>Penduduk =>Tambah Penduduk Domisili langsung klik simpan, baru sebagian form yang berwarna merah, sehingga perlu form yang lain juga diperbaiki sehingga data yang diinput baru datanya lengkap.
**1. yang berwarna merah** 
- NIK
- Nama
- Jenis Kelamin
- Agama 
- Status Penduduk
- Dusun, RW, RT
- Golongan Darah
![image](https://user-images.githubusercontent.com/25834335/97709180-e1f1e180-1af4-11eb-8ff1-7782b1a7974d.png)
![image](https://user-images.githubusercontent.com/25834335/97709419-43b24b80-1af5-11eb-8cad-0e2557223ae7.png)
![image](https://user-images.githubusercontent.com/25834335/97709242-f8983880-1af4-11eb-9c4b-b4bb7af16a20.png)

**Sedangkan Form yang lain seperti :** 
- Hubungan Dalam Keluarga
- Tempat Lahir
- Tanggal Lahir 
- Pendidikan Dalam KK
- Pendidikan Sedang Ditempuh
- Pekerjaaan
- Status Warga Negara
- Nama Ayah
- Nama Ibu
- Status Perkawinan
- Cacat
- Sakit Menahun
- Asuransi

Bisa Tersimpan walaupun belum terisi

### Seperti apa yang diharapkan?
**Sedangkan Form yang lain seperti :** 
- Hubungan Dalam Keluarga
- Tempat Lahir
- Tanggal Lahir 
- Pendidikan Dalam KK
- Pendidikan Sedang Ditempuh
- Pekerjaaan
- Status Warga Negara
- Nama Ayah
- Nama Ibu
- Status Perkawinan
- Cacat
- Sakit Menahun
- Asuransi
wajib harus terisi datanya baru data penduduk bisa disimpan

### Apa yang terjadi?
Data yang tersimpan tidak lengkap, hanya sebagian saja
![image](https://user-images.githubusercontent.com/25834335/97709525-752b1700-1af5-11eb-8ff6-2705c4bcc6f2.png)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.10-Pasca
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
@MUHAMMADRANGSEL kalau semua kolom isian tersebut wajib diisi, apakah justru akan menyusahkan proses memasukkan data penduduk apabila data tersebut belum tersedia? Pendekatan yg diperlukan adalah cukup mengharuskan pengisian data yang memang betul2 wajib ada --- supaya data penduduk bisa secepatnya ada di database. Dan bisa dilengkapi belakangan sesuai kebutuhan. Bukankah lebih penting data minimal seorang penduduk sudah masuk (supaya bisa membuat surat, catat data bantuan, dsbnya) -- daripada HARUS menunggu sampai semua data lengkap dulu?

**Comment by balongbesuk** [comment]
betul pak setuju, data yang wajib diisi cukup data yang terlampir pada kartu keluarga saja yang lain optional

**Comment by eddieridwan** [comment]
Karena berpoteni justru menyusahkan, sebaiknya hanya data yg tertera pada kartu keluarga saja yg wajib diisi, seperti dikatakan @balongbesuk . Silakan daftarkan data kartu keluarga yg saat ini pengisiannya belum diwajibkan.

**Comment by eddieridwan** [comment]
Berikut contoh kartu keluarga. Perlu diperhatikan bahwa walaupun ada kolom di kartu keluarga, belum tentu data tersebut harus diisi. Sebagai contoh No. Paspor dan KITAS umumnya kosong jika penduduk tidak memiliki. 

![image](https://user-images.githubusercontent.com/249563/101303262-bef3e380-3891-11eb-9df6-c4643904d052.png)

**Comment by eddieridwan** [comment]
Juga data KTP, yg berisi golongan darah;

![image](https://user-images.githubusercontent.com/249563/101309452-8f000c80-38a0-11eb-93a3-852a1683eee7.png)

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3807
