### ISSUE TITLE
Penentuan Tema Menarik dan Keren OpenSID

### ISSUE THREAD

**Issue by mah-mudi** [OpenSID/OpenSID#3716]
### Bagaimana alurnya sampai muncul masalah?
Tema Standard OpenSID seperti Hakadewa atau Klasik terlihat kurang menarik dan terlihat jadul.

### Seperti apa yang diharapkan?
Perlu Penentuan Tema OpenSID yang menarik dan keren yang dijadikan standar tema dalam setiap update versi OpenSID kedepannya.
Misal seperti tema : 
http://kendalbulur.tulungagungdaring.id/
https://www.natairaya.desa.id/

### Apa yang terjadi?
Tema Standar OpenSID semakin lebih baik. 
Jika diperlukan pembelian seperti tema yg diatas, dapat menggunakan iuran bersama desa-desa pengguna OpenSID sampai bertemu nominal harga yang disepakati.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by ai-skematik** [comment]
Untuk tema data ditambah sendiri dan disimpan di folder desa, sehingga tidak akan hilang saat update.

**Comment by afa28** [comment]
Tema natra sudah di jadikan tema default, silahkan reopen jika masih ada masalah lainnya.
