### ISSUE TITLE
Integrasikan penerima PKH dan BPNT (Sembako)

### ISSUE THREAD

**Issue by ananghasan** [OpenSID/OpenSID#3719]
### Bagaimana alurnya sampai muncul masalah?
PKH merupakan bantuan dalam bentuk uang dari Kemensos yang diberikan kepada KPM paling miskin (desil 1) berdasarkan syarat tertentu. Kemensos juga memberikan bantuan dalam bentuk barang melalui Program Sembako (BPNT) yang penerimanya juga KPM paling miskin (desil 1 dst) sehingga dipastikan setiap KPM pada kategori desil 1 akan memperoleh PKH dan BPNT

### Seperti apa yang diharapkan?
Disediakan menu atau apapun namanya agar pada saat input data penerima PKH juga ada pilihan (integrasikan) sebagai penerima BPNT

### Apa yang terjadi?
Penginputan akan lebih mudah (cepat) dan konsisten karena data yang dipanggil adalah KPM yang sama dengan bantuan yang berbeda

### Informasi tambahan 
Berdasarkan hasil koordinasi dengan Pendamping PKH, dapat dipastikan bahwa penerima PKH adalah penerima (wajib) BPNT karena merupakan sasaran program dalam pemenuhan kebutuhan dasar KPM miskin. namun sebaliknya ada penerima BPNT tapi tidak menerima PKH hal ini mengacu pada pelaksanaan program berdasarkan kebutuhan, karena BPNT adalah program tahap II dalam hal penanggulangan kemiskinan

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by Jhiban-Khang** [comment]
sepertinya dari modul bantuan sudah cukup mengkaver tersebut, hanya saja di input satu persatu dan belum terintegrasi, saran saya masih tetap saja seperti semula

**Comment by mizwaruddin** [comment]
@afa28 dalam pelaksanaannya, penerima bantuan PKH belum tentu menerima bantuan BPNT (PKH Non-BPNT). Jadi permintaan ini tidak dapat dipenuhi.
