### ISSUE TITLE
Nama Dusun, RW, RT tidak muncul di data tabel Penduduk 

### ISSUE THREAD

**Issue by hasap86** [OpenSID/OpenSID#3720]
### Bagaimana alurnya sampai muncul masalah?
Saat melakukan import data penduduk namun status Hubungan Dalam Keluarga tidak ada Kepala Keluarga dalam 1 KK, hasilnya di tabel penduduk tidak muncul nama Dusun, RT & RW nya, padahal di data penduduknya jika di lihat/edit datanya ada.

### Seperti apa yang diharapkan?
tetap dimunculkan data Dusun, RT, RW di tampilan menu Penduduk

### Apa yang terjadi?
tidak bisa di filter dan dilihat di tabel menu penduduk

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.11
| Versi PHP        | 
| System operasi   |

**Comment by Jhiban-Khang** [comment]
butuh screenshoot nya ,,,, ... biar tahu bugs yg mana

**Comment by hasap86** [comment]
bisa dicoba dengan cara upload data penduduk misalnya 2 data penduduk dan keduanya kosongkan pada isian status Hubungan Dalam Keluarga, setelah itu lihat data penduduk

**Comment by balongbesuk** [comment]
d panduan sudah d jelaskan KK wajib memiliki Kepala Keluarga, karena Kepala Keluarga sifatnya Primary Key

**Comment by mizwaruddin** [comment]
@afa28 bukan bug.

**Comment by afa28** [comment]
Mungkin dibuat error sj dan tampilkan infonya (apa yg kurang/salah) biar bisa di impor ulang oleh pengguna. Dan bisa disediakan download data hasil import yg ealah, qgar pengguna langsung mengedit file tsb.

**Comment by hasap86** [comment]
> Mungkin dibuat error sj dan tampilkan infonya (apa yg kurang/salah) biar bisa di impor ulang oleh pengguna. Dan bisa disediakan download data hasil import yg ealah, qgar pengguna langsung mengedit file tsb.

betul, sebaiknya dibuat info saja dan tidak berhasil diimport jika memang wajib harus ada, kadang kita gak tau data yg di excel apa dan siapa kepala keluarganya

**Comment by afa28** [comment]
Sesuai dengan petunjuk import.
![11111](https://user-images.githubusercontent.com/57283157/105687022-88018c00-5f2a-11eb-8fd0-da4f000af9a1.JPG)

Karena alamat penduduk yg berkeluarga diambil dari Kepala Keluarga pd KK, maka proses tambahan yg perlu dilakukan yakni:
1. Hapus KK yg tdk memiliki Kepala Keluarga sehingga anggota keluarga sebelumnya menjadi penduduk lepas, atau
2. Tambahkan Kepala Keluarga pd KK yg tdk memiliki Kepala Keluarga.

KK yg tidak memiliki Kepala Keluarga masuk ke KK kosong.
![222](https://user-images.githubusercontent.com/57283157/105690843-0eb86800-5f2f-11eb-809c-d11f83d05497.JPG)

Silahkan di reopen jika masih bermasalah dengan alur ini.
