### ISSUE TITLE
Sebutan Dusun pada halaman Wilayah Administratif tidak sesuai dengan pengaturan aplikasi 

### ISSUE THREAD

**Issue by hasap86** [OpenSID/OpenSID#3721]
### Bagaimana alurnya sampai muncul masalah?
jika dilakukan perubahan di seting aplikasi untuk sebutan_dusun menjadi nama lain selain dusun, pada halaman WIlayah Administratif Nama Dusun dan Nama Kepala Dusun tetap kata Dusun tidak berubah sesuai setingan aplikasi

### Seperti apa yang diharapkan?
seharusnya nama dusun berubah sesuai setingan aplikasi sebutan_dusun

### Apa yang terjadi?
tidak sesuai

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.11
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
Harap lampirkan bagian yg tdk sesuai.

**Comment by hasap86** [comment]
Lihat di Menu Pengaturan > Aplikasi : sebutan_dusun = dusun
jika kita rubah menjadi Pemukiman, seharusnya setiap konten yg mengandung nama Dusun berubah menjadi Pemukiman,
untuk issue ini lebih ke menu Wilayah Administratif
Admin Web > Menu > Menu Statis > Tambah Menu Baru
Nama : Wilayah Administratif (contoh)
Jenis Link : Halaman Statis Lainnya
Link : Wilayah Administratif
 
maka pada halaman web menu Wilayah Administratif akan muncul Nama Dusun dan Nama Kepala Dusun, seharusnya berubah menjadi Nama Pemukiman dan Nama Kepala Pemukiman

![Screen Shot 1442-03-16 at 17 27 17](https://user-images.githubusercontent.com/45263721/97857844-e4d91600-1d30-11eb-9867-aec83811413d.png)

**Comment by afa28** [comment]
Ok, apa hanya halaman itus sj??? Atau ad halaman yg lain. Jika ad yg lain silahkan di lampirkan.

**Comment by hasap86** [comment]
saya coba cari halaman lain yah

**Comment by afa28** [comment]
> saya coba cari halaman lain yah

Ok

**Comment by hasap86** [comment]
ohya di halaman yg sama juga ada data yg tertinggal, yaiut Jumlah RW, jika bisa diperbaiki sekalian di issue ini sebaiknya Jumlah RW tiap dusun juga dimunculkan bukan hanya RT, tetapi jika diperluka issue baru saya buatkan

**Comment by afa28** [comment]
> ohya di halaman yg sama juga ada data yg tertinggal, yaiut Jumlah RW, jika bisa diperbaiki sekalian di issue ini sebaiknya Jumlah RW tiap dusun juga dimunculkan bukan hanya RT, tetapi jika diperluka issue baru saya buatkan

Buat issue terpisah agar mudah di tracing

**Comment by hasap86** [comment]
ok, untuk issue yg sama terjadi di menu Peta
pada pilihan Peta Wilayah <dusun>

![Uploading Screen Shot 1442-03-16 at 17.44.03.png…]()

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3729

**Comment by bing609** [comment]
Masih ada yang tertinggal di Versi 22.05 terkait sebutan 'dusun' yang tidak ikut berubah dengan nama pengganti:
1. di halaman dasboard admin pada judul widget 'Wilayah Dusun"
![image](https://user-images.githubusercontent.com/71241253/169966035-0d95713c-8109-48b0-b01c-4de364163394.png)

2. di halaman Wilayah Administratif Dusun pada tombol '+ Tambah Dusun'
![image](https://user-images.githubusercontent.com/71241253/169966114-d39ba35b-e9b4-4f7b-af3f-de3580dd0269.png)
