### ISSUE TITLE
Jumlah RW tidak ada pada Menu Statis Wilayah Administratif

### ISSUE THREAD

**Issue by hasap86** [OpenSID/OpenSID#3722]
### Bagaimana alurnya sampai muncul masalah?
Jumlah RW tidak ada pada menu statis Wilayah Administratif

Admin Web > Menu > Menu Statis > Tambah Menu Baru
Nama : Wilayah Administratif (contoh)
Jenis Link : Halaman Statis Lainnya
Link : Wilayah Administratif

### Seperti apa yang diharapkan?
adanya jumlah RW tiap dusun seperti halnya jumlah RT

### Apa yang terjadi?
lebih informatif

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.11
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3732
