### ISSUE TITLE
Rapihkan konten artikel pada kasus gambar artikel yang kotak kecil

### ISSUE THREAD

**Issue by hasap86** [OpenSID/OpenSID#3723]
### Bagaimana alurnya sampai muncul masalah?
pada artikel yang gambarnya tidak full terlihat kekosongan pada konten

### Seperti apa yang diharapkan?
dalam kondisi gambar artikel kotak, konten artikel mengisi kolom kosong yang diakibatkan oleh gambar yg kotak

### Apa yang terjadi?
terlihat tidak rapi karen kekosongan konten

### Informasi tambahan 
![Screen Shot 1442-03-16 at 18 23 03](https://user-images.githubusercontent.com/45263721/97862921-c1b26480-1d38-11eb-9176-023fcd2c000d.png)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by mizwaruddin** [comment]
@afa28 Issue sudah saya pindahkan ke https://github.com/OpenSID/tema-hadakewa/issues/5
