### ISSUE TITLE
Widget

### ISSUE THREAD

**Issue by suyatno52** [OpenSID/OpenSID#3724]
tidak bisa tambah/ gagal simpan jenis widget dinamis

**Comment by eddieridwan** [comment]
@suyatno52 lampirkan tampakan layar. Jelaskan langkah2 yg dijalankan. Jelaskan apa isi widgetnya. Tanpa informasi yg jelas, laporan tidak bisa ditindak lanjuti.

Lebih meyakinkan error kalau bisa replikasi masalahnya di https://demo.opensid.my.id

**Comment by afa28** [comment]
Panduan :
1. Matikan extension sqlite3
2. Aktifkan extension tiddy

**Comment by afa28** [comment]
https://github.com/OpenSID/OpenSID/wiki/Persiapan-Install-OpenSID

**Comment by suyatno52** [comment]
Terima kasih 🙏🙏

Pada tanggal Kam, 5 Nov 2020 21:39, Andi Fahruddin Akas <
notifications@github.com> menulis:
