### ISSUE TITLE
Bug back up database

### ISSUE THREAD

**Issue by Fandha** [OpenSID/OpenSID#3725]
### Bagaimana alurnya sampai muncul masalah?
Saat melakukan back up seluruh database SID, proses tidak berhasil hanya halaman kosong. Begitu seterusnya ketika diulang. tetapi bila melalui phpmyadmin/mysql expor database berhasil.

### Seperti apa yang diharapkan?
dapat melakukan back up agar memudahkan dalam mengamankan database

### Apa yang terjadi?
tidak dapat melakukan back up database, layar blank seperti pd gbr dibawah ini 
![image](https://user-images.githubusercontent.com/69184054/98060374-01359980-1e7c-11eb-9acd-cebf35ceaf71.png)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
@Fandha harap lampirkan isi file di folder logs yg dihasilkan pada waktu melakukan backup.

**Comment by Fandha** [comment]
Ini datanya :

[logs.zip](https://github.com/OpenSID/OpenSID/files/5485126/logs.zip)

**Comment by eddieridwan** [comment]
@Fandha , sepertinya database anda tidak lengkap. Coba kirim backup database anda ke akun Telegram @eddieridwan untuk diperiksa.

**Comment by eddieridwan** [comment]
@Fandha Juga terlihat definisi `path` untuk peta wilayah desa melebihi 65,535 karakter. Peta itu diambil dari mana?

Bung @fusionid `path` untuk wilayah/area bisa sampai berapa karakter?

**Comment by fusionid** [comment]
Type field 'path' di tabel 'tweb_wil_clusterdesa' untuk peta wilayah dusun/rw/rt = TEXT = 65,535 bytes = 21,845 karakter (UTF8)

**Comment by Fandha** [comment]
Baik terima kasih arahannya, kami cba cek kembali databasenya dulu, memang data persil belum ada penginputan. Berarti untuk peta ada kapasitas maksimal y dan harus lengkap data baru bsa di back up y.
Fyi, untuk peta kmi dapat dari bappelitbang untuk peta RW RT kmi petakan dengan gps dan program gis, bru kami impor shp nya ke app ini. Sekali lagi terima kasih bantuannya @eddieridwan & @fusionid

**Comment by fusionid** [comment]
@Fandha Peta Persil hanya opsional saja, peta yang harus tersedia adalah peta desa / dusun / rw / rt.
Untuk impor shp, supaya dapat di filter lebih baik lagi titik2 kordinatnya, sebaiknya di export dulu ke gpx :
import shp  -> export gpx  -> import gpx -> simpan

**Comment by eddieridwan** [comment]
> Type field 'path' di tabel 'tweb_wil_clusterdesa' untuk peta wilayah dusun/rw/rt = TEXT = 65,535 bytes = 21,845 karakter (UTF8)

Bung @fusionid , apakah field `path` perlu diubah supaya bisa memuat data lebih panjang?

**Comment by fusionid** [comment]
> > Type field 'path' di tabel 'tweb_wil_clusterdesa' untuk peta wilayah dusun/rw/rt = TEXT = 65,535 bytes = 21,845 karakter (UTF8)
> 
> Bung @fusionid , apakah field `path` perlu diubah supaya bisa memuat data lebih panjang?

Field 'path' bisa diubah menjadi MEDIUMTEXT (16,777,215 bytes = 5,592,405 karakter).
Sebenarnya dengan type TEXT saja sudah lebih dari cukup untuk menampung data peta sebuah dusun/rw/rt, kecuali membuat titik-titik kordinatnya per 0.5 meter.
Jika titik kordinat terlalu banyak akan bermasalah ketika akan edit di opensid, karena membutuhkan memory yg sangat besar.
Untuk view saja tidak akan bermasalah, peta tetap akan ditampilkan.
