### ISSUE TITLE
Bug Cetak Biodata Penduduk

### ISSUE THREAD

**Issue by Jhiban-Khang** [OpenSID/OpenSID#3726]
Seharunya muncul data data tersebut
### Bagaimana alurnya sampai muncul masalah?

Muncul normal seperti sebelumnya
### Seperti apa yang diharapkan?

Muncul normal seperti sebelumnya
### Apa yang terjadi?

![Screenshot from 2020-11-04 17-23-39](https://user-images.githubusercontent.com/19563843/98100102-fce09f00-1ec2-11eb-8e40-d793194313a1.png)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.11 Pasca
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3731
