### ISSUE TITLE
Form f-2.0.1 formulir permohonan akta kelahiran

### ISSUE THREAD

**Issue by chemod** [OpenSID/OpenSID#373]
formulir untuk pembuatan akta kelahiran... sebenarnya tidak di keluarkan oleh desa, warga langsung ambil formulirnya ke dukcapil. tapi mengingat banyak desa yang tempatnya jauh dari dinas sehingga bisa bolak balik dia... mungkin gak ada salahnya opensid bisa mengimplementasikan form tersebut...

http://dindukcapil.rembangkab.go.id/download_formulir/getfile/16/1a903-f-2.01.pdf

**Comment by sarolangun** [comment]
Linknya gak bisa di DOWNLOAD

**Comment by sarolangun** [comment]
![image](https://cloud.githubusercontent.com/assets/16639572/25562064/87269132-2da5-11e7-8b2e-1cc21faab35f.png)

**Comment by sarolangun** [comment]
Permohonan FORMULIR PELAPORAN KELAHIRAN F-2.05

sudah tidak menggunakan F-2.01 lagi

**Comment by MUHAMMADRANGSEL** [comment]
Ini sudah ada mas eddie lebih baik di closed
