### ISSUE TITLE
Nonaktif Syarat Upload Dokumen di Layanan Mandiri / Anjungan

### ISSUE THREAD

**Issue by hasap86** [OpenSID/OpenSID#3734]
### Bagaimana alurnya sampai muncul masalah?
saat akan mengajukan pembuatan surat terkendala harus upload dokumen persyaratan

### Seperti apa yang diharapkan?
adanya fitur aktif non-aktif Upload Persyaratan Dokumen pada Pengaturan Format Surat Desa

### Apa yang terjadi?
kendala harus scan dokumen persyaratan 

### Informasi tambahan 
Fitur aktif non-aktif upload dokumen persyaratan dimaksudkan untuk memberi fleksibilitas pengguna pakah mewajibkan upload dokumen atau tidak, Ceklis Persyaratan Permohonan Surat pada setingan pengaturan Surat tetap di ceklis untuk memberikan informasi kepada pemohon untuk membawa persyaratan saat mengambil Surat.

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | berputar
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
Sebaiknya tdk perlu di nonaktifkan, cuma di tambahkan 1 option/pilihan pd syaratnya yakni "membawa dokumen fisik". Sehingga jika dokumen yg dibutuhkan tdk ad/blum di upload maka bisa diganti dengan dokumen fisik. Jika sdah ad dokumen yg sdah diupload maka warga tdk perlu membawa dokumen fisik lagi.

Dan mungkin agar warga tdk perlu repot lg untuk kepengurusan surat selanjutnya, bisa di arahkan untuk memfoto/scan dokumen yg dibawanya.

**Comment by hasap86** [comment]
ya intinya ada pilihan untuk upload atau tidak (bawa fotokopi)

**Comment by afa28** [comment]
Sudah ada di `master`, bisa di cek di http://berputar.opensid.my.id/ pada layanan mandiri. Disediakan pilihan untuk menggunakan berkas fisik jika dokumen tdk tersedia.
