### ISSUE TITLE
Tidak bisa merubah / simpan Persyaratan Permohonan Surat jika tida dipilih salah satu persyaratan / dikosongkan semua

### ISSUE THREAD

**Issue by hasap86** [OpenSID/OpenSID#3735]
### Bagaimana alurnya sampai muncul masalah?
saat ceklis Perysratan Permohonan Surat tidak diceklis / dipiih salah satu (dikosongkan), saat disimpan tida berubah, (tidak tersimpan)

### Seperti apa yang diharapkan?
seharusnya bisa berubah sesuai yg diceklis (dikosongkan)

### Apa yang terjadi?
tidak berubah

### Informasi tambahan 
![Screen Shot 1442-03-23 at 07 13 42](https://user-images.githubusercontent.com/45263721/98488422-9c9f8380-225b-11eb-8ff3-87a2d1013fa4.png)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | berputar
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3751
