### ISSUE TITLE
Sediakan tombol Back to Top / Kembali ke Atas

### ISSUE THREAD

**Issue by hasap86** [OpenSID/OpenSID#3736]
### Bagaimana alurnya sampai muncul masalah?
belum adanya tombol kembali ke atas di bagian bawah kanan

### Seperti apa yang diharapkan?
adanya tombol kembali ke atas di bagian kanan bawah dan dibuatkan seting bagi yg ingin mengaktifkan dan tidak.

### Apa yang terjadi?
mempermudah 

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
Untuk untu bagian apa??? apakah halaman depan, admin atau ke duanya.

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3756
