### ISSUE TITLE
Error Saat menambahkan widget dinamis

### ISSUE THREAD

**Issue by hasap86** [OpenSID/OpenSID#3737]
### Bagaimana alurnya sampai muncul masalah?
saat membuat widget dinamis dengan kode iframe youtube, saat disimpan terjadi error dengan halaman blank dan data tidak tersimpan

### Seperti apa yang diharapkan?
tidak error saat menyimpan kode youtube iframe

### Apa yang terjadi?
tidak tersimpan

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.11
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
Matikan extension sqllite3, bisa di baca di panduan persiapan instalasi OpenSID.

**Comment by hasap86** [comment]
> Matikan extension sqllite3, bisa di baca di panduan persiapan instalasi OpenSID.

Siap dicoba
