### ISSUE TITLE
Lampiran Formulir Keterangan Pindah WNI

### ISSUE THREAD

**Issue by ananghasan** [OpenSID/OpenSID#3738]
### Bagaimana alurnya sampai muncul masalah?
1. Surat Keterangan Pindah Penduduk memiliki banyak formulir (lampiran) seperti tersedia pada alamat https://dindukcapil.rembangkab.go.id/download_formulir
2. Belum tersedianya formulir tersebut atau menu untuk menambahkan formulir
### Seperti apa yang diharapkan?
Tersedianya atau bisa menambahkan sendiri formulir lampiran

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by mizwaruddin** [comment]
@afa28 dalam surat pindah WNI sdh tersedia lampiran yang lengkap (F-1.23, F-1.25, F-1.29, F-1.34)
