### ISSUE TITLE
Penomoran Rumah Tanggan Ngaco

### ISSUE THREAD

**Issue by Jhiban-Khang** [OpenSID/OpenSID#3740]
Pada saat membuat Kelompok Rumah Tangga (Baru), nomor yg dibuat cenderung panjang
### Bagaimana alurnya sampai muncul masalah?

Harapanya nomor Rumah Tangga Terdiri seperti rilis sebelumnya, saya kira ini mungkin karena ada perubahan penomoran kode kode baik desa, kec. kab/kota .
### Seperti apa yang diharapkan?

nomor rumah tangga seperti konsep awal
### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.11 Pasca (Demo)
![Screenshot at 2020-11-09 20-53-56](https://user-images.githubusercontent.com/19563843/98550261-75ce6500-22ce-11eb-8f9d-079af1530481.png)

| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
Sy cek di localhost masih normal2 sj, default 011405000014 digit berjalan. Tp klw di demo bermaslah dan perubahan dr modul rtm sebelumnya berkaitan dengan limit cetak data.

**Comment by afa28** [comment]
Setelah sy cek, ini akibat pengubahan format kode wilayah.

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3742
