### ISSUE TITLE
Perlukah update bootstrap, jquery, hightchart ?

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#3741]
iseng tes devtool chrome browser di website demo

![Untitled](https://user-images.githubusercontent.com/35319600/98764980-9520db80-240f-11eb-90d3-06d8444ff6eb.jpg)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by andifahruddinakas** [comment]
Perlu di rancang ulang
