### ISSUE TITLE
TABEL STATISTIK NOL SEMUA

### ISSUE THREAD

**Issue by saferomedia** [OpenSID/OpenSID#3745]
### STATISTIK PENDUDUK NOL / TIDAK [TAMPIL]
Ketika beralih ke versi 20.10, Tabel statistik tidak tampil, isinya nol semua
<img src="https://i.ibb.co/hMN0qJm/errostatistik.png" alt="errostatistik" border="0"> 

mohon solusi, terima kasih

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.10
| Versi PHP        | 7
| System operasi   | WINDOW 10

**Comment by afa28** [comment]
@saferomedia sepertinya kesalahan pada waktu memasang OpenSID. Silakan tanyakan di https://www.facebook.com/groups/OpenSID. Di situ tempat bertanya pemasangan dan penggunaan OpenSID. Issue HANYA untuk melaporkan permintaan fitur atau masalah yg terbukti memang error scr umum yg harus diperbaiki.

Issue ini akan ditutup. Silakan buka lagi kalau anda bisa sediakan info untuk menunjukkan memang error yg perlu diperbaiki.
