### ISSUE TITLE
[Penduduk] Input otomatis Nama Orang Tua setelah diisikan NIK Data Orang Tua saat tambah penduduk

### ISSUE THREAD

**Issue by hasap86** [OpenSID/OpenSID#3746]
### Bagaimana alurnya sampai muncul masalah?
Saat tambah penduduk pada DATA ORANG TUA pengisian NIK dan Nama Orang Tua keduanya manual, seharusnya pengisian nama orang tua otomatis ketika pengisian NIK karena datanya ada di dalam database, kecuali datanya tidak ada dalam database diisi manual

### Seperti apa yang diharapkan?
Nama Orang Tua otomatis terisi saat setelah input NIK orang tua, kecuali datanya tidak ada dalam database

### Apa yang terjadi?
menghindari kesalahan input nama

### Informasi tambahan 
![input-nik-ortu](https://user-images.githubusercontent.com/45263721/99131136-eebe1b80-2644-11eb-96e0-005f3f0a9903.jpg)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.11
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
Duplicate issue https://github.com/OpenSID/OpenSID/issues/1843

**Comment by balongbesuk** [comment]
Duplicate #734

**Comment by andifahruddinakas** [comment]
Duplicate of https://github.com/OpenSID/OpenSID/issues/7225
