### ISSUE TITLE
Pilihan Hubungan Data Keluarga pada saat tambah Anggota Keluarga tidak muncul semua

### ISSUE THREAD

**Issue by hasap86** [OpenSID/OpenSID#3747]
### Bagaimana alurnya sampai muncul masalah?
saat menambahkan anggota keluarga pada KK, pilihan hubungan keluarga tidak lengkap seperti saat tambah penduduk domisili
![hubungan-keluarga-tambah-kk](https://user-images.githubusercontent.com/45263721/99138898-c515ec00-2666-11eb-85e7-5e4afa93bbf1.jpg)

### Seperti apa yang diharapkan?
seharusnya muncul semua pilihan Hubungan Keluarga seperti saat menambahkan penduduk domisili

![hubungan-keluarga-tambah-penduduk-ok](https://user-images.githubusercontent.com/45263721/99138968-52f1d700-2667-11eb-8560-6a503c9953c6.jpg)

### Apa yang terjadi?
tidak lengkap

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.11
| Versi PHP        | 
| System operasi   |

**Comment by balongbesuk** [comment]
ini pasti kepala keluarganya berstatus anak / belum kawin

**Comment by hasap86** [comment]
> ini pasti kepala keluarganya berstatus anak / belum kawin

oiya betul saya cek statusnya kepala keluarga tapi belum kawin...

berarti harus status Kawin dulu yah baru muncul semua status hubungan keluarga...

**Comment by afa28** [comment]
Cuma perlu dibuatkan panduan, mungkin pak @balongbesuk bisa bantu melengkapi https://github.com/OpenSID/OpenSID/wiki/Tanya-jawab-Keluarga

**Comment by afa28** [comment]
https://github.com/OpenSID/OpenSID/issues/3579

**Comment by afa28** [comment]
Sudah ditambahkan ke panduan https://github.com/OpenSID/OpenSID/wiki/Tanya-jawab-Keluarga
