### ISSUE TITLE
Lokasi Tempat Tinggal Apakah Lebih Baik Diinput Melalui Modul Rumah Tangga

### ISSUE THREAD

**Issue by khiar-rara** [OpenSID/OpenSID#3749]
### Alurnya saat ini?
Lokasi tempat tinggal diinput dari modul penduduk.

### Seperti apa yang diharapkan?
Lokasi tempat tinggal diinput dari modul rumah tangga.

### Apa yang terjadi?
Tidak terlalu banyak input berdasarkan jumlah penduduk.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
Kayaknya lebih masuk akal klw lokasi tempat tinggal penduduk diletakkan di modul ini. Akan lebih konsisten dan tdk perlu repot untuk menandai lokasi tempat tinggal 1 penduduk atau 1 keluarga.

**Comment by eddieridwan** [comment]
Alamat keluarga tidak bisa dimasukkan di modul Rumah Tangga. Unit penduduk yg resmi dikenal Dukcapil adalah keluarga berdasarkan kartu keluarga. Rumah tangga adalah konsep yg pengertiannya berbeda di antara berbagai instansi, dan ditujukan bukan untuk administrasi kependudukan, tetapi terutama untuk analisis sosial-ekonomi oleh Dinsos. 

Tempat alamat keluarga tepatnya di tabel `tweb_keluarga`, sesuai dengan alamat di kartu keluarga. Sekarang sudah di situ. Dan sudah berlaku untuk semua anggota di kartu keluarga ybs. Alamat yg ada di perorangan penduduk adalah untuk penduduk `lepas`, yaitu penduduk pendatang atau lainnya yang bukan anggota keluarga (KK) yg bermukim resmi di desa. 

Issue ini akan ditutup. Silakan buka lagi kalau ada usul tambahan.
