### ISSUE TITLE
JENIS KELAMIN HANYA MENUNJUKAN JENIS KELAMIN PEREMPUAN PADA FITUR KELOMPOK

### ISSUE THREAD

**Issue by muhtar-coder** [OpenSID/OpenSID#3750]
### Bagaimana alurnya sampai muncul masalah?

Pendataan anggota kelompok yang terbaca setelah di input hanya menunjukan jenis kelamin perempuan meskipun jenis kelamin nya laki-laki.

![image](https://user-images.githubusercontent.com/55665526/99148731-14d2d280-26bc-11eb-9662-b81e75945a54.png)

### Seperti apa yang diharapkan?

Data yang di tampilkan menyesuaikan data jenis kelamin yang sebenarnya
### Apa yang terjadi?

Data output Benar
### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.11 Premium-Pasca
| Versi PHP        | 7.4.12
| System operasi   |

**Comment by eddieridwan** [comment]
Sdh dicommit ke `rilis-dev` melalui PR https://github.com/OpenSID/premium/pull/21
