### ISSUE TITLE
Admin/Operator dapat membalas komentar netizen

### ISSUE THREAD

**Issue by mr703** [OpenSID/OpenSID#3752]
### Bagaimana alurnya sampai muncul masalah?
Setiap Komentar yang diberikan netizen pada setiap artikel dapat muncul, namun untuk menanggapi komentar netizen tersebut tidak dapat dilakukan.

### Seperti apa yang diharapkan?
Setiap Komentar Netizen dapat di Balas Langsung Oleh Admin/Operator

### Apa yang terjadi?
Komentar netizen tidak dapat ditanggapi langsung oleh admin/Operator

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.11 Pasca
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
Duplicate #2763

PR yg pernah dibuat #2868, catatan : pisahkan table mail_box dan komentar

**Comment by afa28** [comment]
Duplicate issue https://github.com/OpenSID/OpenSID/issues/4017
