### ISSUE TITLE
Feed Opensid mengalami Error

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#3755]
### Bagaimana alurnya sampai muncul masalah?
buka https://demo.opensid.my.id/feed

### Seperti apa yang diharapkan?
berjalan seperti harapan / tidak error

### Apa yang terjadi?
XML Parsing Error 

### Informasi tambahan 

![Untitled2](https://user-images.githubusercontent.com/35319600/99328415-9ab66f80-28ae-11eb-9231-da15e34c3e85.jpg)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3757
