### ISSUE TITLE
sitemap.xml mengalami error

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#3758]
### Bagaimana alurnya sampai muncul masalah?

buka https://demo.opensid.my.id/sitemap.xml

### Seperti apa yang diharapkan?
tidak error / berjalan baik

### Apa yang terjadi?
mengalami error

### Informasi tambahan 
![image](https://user-images.githubusercontent.com/35319600/99611982-3ed31e80-2a47-11eb-95b8-d6d3b17ac2b1.png)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3775
