### ISSUE TITLE
Munculkan Semua Artikel pada saat membuka Menu Artikel di Admin Web

### ISSUE THREAD

**Issue by hasap86** [OpenSID/OpenSID#3761]
### Bagaimana alurnya sampai muncul masalah?
saat ini untuk melihat artikel harus buka satu per satu kategori

![Screen Shot 1442-04-05 at 03 14 19](https://user-images.githubusercontent.com/45263721/99719392-d0da3600-2ade-11eb-8fc0-a2b9ff1be830.png)

### Seperti apa yang diharapkan?
munculkan semua artikel saat pertama kali membuka menu Artikel di Admin Web, bisa juga dibuatkan pilihan kategori "Semua Kategori" dan dijadikan Default

### Apa yang terjadi?
lebih efektif dan bisa terlihat semua artikel yang ada beserta jumlahnya

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | Demo
| Versi PHP        | 
| System operasi   |

**Comment by nopezi** [comment]
tambah 1 menu semua artikel

**Comment by afa28** [comment]
> tambah 1 menu semua artikel

Tdk hanya menambahkan sj, ad bbrp fungsi yg jg perlu ikut di perbaiki u/ issue ini  cek komentar di PR.

**Comment by eddieridwan** [comment]
Sdh dicommit ke `maser` melalui PR #3786
