### ISSUE TITLE
Judul Artikel pada Tema Hakadewa jangan diperbesar (uppercase)

### ISSUE THREAD

**Issue by hasap86** [OpenSID/OpenSID#3762]
### Bagaimana alurnya sampai muncul masalah?
JUDUL ARTIKEL PADA TEMA HAKADEWA BESAR SEMUA (UPPERCASE) JADI KURANG ENAK DILIHAT DAN DIBACANYA

### Seperti apa yang diharapkan?
sesuaikan saja dengan apa yang ditulis di admin web artikel judulnya

### Apa yang terjadi?
CAPSLOCK JEBOL BOS :)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | Demo
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3776
