### ISSUE TITLE
Pindahkan Tombol Selengkapnya pada tiap artikel di web ke sebelah kanan supaya lebih menarik

### ISSUE THREAD

**Issue by hasap86** [OpenSID/OpenSID#3763]
### Bagaimana alurnya sampai muncul masalah?
saat ini tombol Selengkapnya berada di sebelah kiri tiap artikel di web

![Screen Shot 1442-04-05 at 03 38 27](https://user-images.githubusercontent.com/45263721/99721485-e4d36700-2ae1-11eb-8343-1bac6308b540.png)

### Seperti apa yang diharapkan?
pindahkan ke sebelah kanan supaya lebih terjangkau dan menarik

### Apa yang terjadi?
kurang pas gituh

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | Demo
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
Issuenya bisa dipindahkan ke https://github.com/OpenSID/tema-hadakewa

**Comment by mizwaruddin** [comment]
@afa28 sudah saya pindah ke https://github.com/OpenSID/tema-hadakewa/issues/4
