### ISSUE TITLE
Rubah Style Jadul Tombol Masuk pada Widget Layanan Mandiri

### ISSUE THREAD

**Issue by hasap86** [OpenSID/OpenSID#3764]
### Bagaimana alurnya sampai muncul masalah?
**tombol Masuk** pada **Layanan Mandiri** terkesan kaku / kucel / jadul hehe

![Screen Shot 1442-04-05 at 03 47 10](https://user-images.githubusercontent.com/45263721/99722602-7394b380-2ae3-11eb-8aa7-4a3affc662a4.png)

### Seperti apa yang diharapkan?
bisa disamakan dengan tombol **Buka Peta** pada **widget Lokasi Kantor Desa**

![Screen Shot 1442-04-05 at 03 47 17](https://user-images.githubusercontent.com/45263721/99722641-81e2cf80-2ae3-11eb-9a3d-b3d93fe0d0de.png)

### Apa yang terjadi?
kurang greget dan kurang serasi dengan tombol yg lain gituh

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | Demo
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
@hasap86 widget layanan mandiri akan hilang karena telah diubah di versi Premium menjadi login terpisah. Nanti akan digabung ke rilis umum v21.03.
