### ISSUE TITLE
Margin kiri kanan untuk Running Text

### ISSUE THREAD

**Issue by hasap86** [OpenSID/OpenSID#3765]
![running-text-margin](https://user-images.githubusercontent.com/45263721/99726449-1865bf80-2ae9-11eb-8848-f77c2d154a7a.jpg)

### Bagaimana alurnya sampai muncul masalah?
posisi running text saat ini tembu sampai full kiri dan kanan tanpa ada margin box

### Seperti apa yang diharapkan?
beri margin disamakan dengan tampilan lainnya pada konten

### Apa yang terjadi?
kurang rapih terlihatnya

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
Issuenya bisa dipindahkan ke https://github.com/OpenSID/tema-hadakewa

**Comment by mizwaruddin** [comment]
@afa28 issue ini sdh saya pindah ke https://github.com/OpenSID/tema-hadakewa/issues/3#issue-776899556
