### ISSUE TITLE
Pop Up gambar artikel ukurannya ditetapkan jangan menutupi tampilan sampai melebar jika gambarnya besar

### ISSUE THREAD

**Issue by hasap86** [OpenSID/OpenSID#3766]
![Screen Shot 1442-04-05 at 04 36 07](https://user-images.githubusercontent.com/45263721/99727382-75ae4080-2aea-11eb-8aa3-2bc7d628748b.png)

### Bagaimana alurnya sampai muncul masalah?
saat ini jika artikel melampirkan gambar tambahan dan di klik, preview gambar popupnya melebar jika gambar terlalu besar

![Screen Shot 1442-04-05 at 04 40 41](https://user-images.githubusercontent.com/45263721/99727469-95456900-2aea-11eb-8586-27201032bf0b.png)

### Seperti apa yang diharapkan?
ditentukan saja ukuran gambarnya misalnya 90% dari tampilan layar, sehingga tidak melebar ke kanan

### Apa yang terjadi?
sulit untuk kontrol next gambar

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | Demo
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
Issuenya bisa dipindahkan ke https://github.com/OpenSID/tema-hadakewa

**Comment by mizwaruddin** [comment]
@afa28 issue ini sdh sya pindah ke https://github.com/OpenSID/tema-hadakewa/issues/2#issue-776898702
