### ISSUE TITLE
website_title disimpan dibelakang Judul Artikel / halaman statik pada title tab browser

### ISSUE THREAD

**Issue by hasap86** [OpenSID/OpenSID#3767]
![Screen Shot 1442-04-05 at 04 52 33](https://user-images.githubusercontent.com/45263721/99728942-c6269d80-2aec-11eb-9723-160838a27f39.png)
_(perhatikan pada judul tab browser)_

### Bagaimana alurnya sampai muncul masalah?
saat ini website_title selalu berada di paling awal judul tab browser, sehingga membuka artikel / halaman apapun selalu muncul nama website_title terus.

### Seperti apa yang diharapkan?
seharusnya jika saat membuka artikel dan artikel halaman statis yang diutamakan adalah judul artikel tersebut bukan judul website_title

### Apa yang terjadi?
kurang seo friendly dimata mesin pencari

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by nopezi** [comment]
saya menambahkan fungsi get_first_dynamic_title_page_from_path, untuk fungsi get_dynamic_title_page_from_path tidak di hapus

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master`.

**Comment by hasap86** [comment]
maaf untuk revisi

untuk **halaman beranda** mungkin dikecualikan seperti biasa aja **website_title + sebutan_desa + Nama Desa + sebutan_kecamatan + Nama Kecamatan + sebutan_kabupaten + Nama Kabupaten** sehingga menjadi **Website Resmi  Desa Senggig1 Kecamatan Batulay4r Kabupaten Lombok Bar4t** 

saat ini website_title tidak terlihat pada halaman beranda
