### ISSUE TITLE
Bug Versi 20.11 - Permasalahan Ketika Login

### ISSUE THREAD

**Issue by OkkySuryaLesmana** [OpenSID/OpenSID#3768]
Tidak Bisa Login Karena controller tidak meredirect ke halaman admin. nyangkut di fungsi auth

**Comment by Nurhidayat29** [comment]
cek versi php, min 7.3

**Comment by rismanbelajar** [comment]
saya jga Tidak Bisa Login Karena controller tidak meredirect ke halaman admin. nyangkut di fungsi auth

**Comment by Jhiban-Khang** [comment]
https://github.com/OpenSID/OpenSID/wiki/Persiapan-Install-OpenSID
