### ISSUE TITLE
Perbaiki huruf romawi pada nama dusun di surat cetak rtf

### ISSUE THREAD

**Issue by benioke** [OpenSID/OpenSID#3771]
Bagaimana alurnya sampai muncul masalah?
Hasil cetak surat rtf nya.untuk nama dusun nya.jika nama dusun nya huruf romawi 
Contoh nya
nama dusun nya pakai huruf romawi.lihat panah di bawah ini

![Capture2](https://user-images.githubusercontent.com/47577404/99867195-da03f980-2be9-11eb-99dc-e35052f7b8d0.JPG)

Hasil dari cetak surat rtf nya
Jika alamat dusun memakai huruf romawi lebih dari satu karakter maka  maka menjadi huruf kecil
![Capture1](https://user-images.githubusercontent.com/47577404/99867211-16375a00-2bea-11eb-8352-98f32a5c6825.JPG)

Seperti apa yang diharapkan?
Seharusnya jika nama dusun memakai huruf romawi.maka hasil cetak surat rtf nya..hasil juga menampilkan huruf besar bukan berubah menjadi huruf ke kecil.

Sistim saat ini
Dusun I=Dusun I
Dusun II=Dusun Ii
Dusun III=Dusun Iii

Yang diharapkan
Dusun I=Dusun I
Dusun II=Dusun II
Dusun III=Dusun III

Apa yang terjadi?
Hasil cetak surat rtf nya..khusus alamat dusun tidak sesuai dengan nama dusun jika nama dusun nya pakai huruf romawi

 Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.11
| Versi PHP        | 
| System operasi   |

**Comment by benioke** [comment]
Belum berfungsi pak?

**Comment by afa28** [comment]
> Belum berfungsi pak?

Belum di merge

**Comment by benioke** [comment]
Belum di merge mksud nya pak..mf pemula

**Comment by benioke** [comment]
> > Belum berfungsi pak?
> 
> Belum di merge

Belum di merge mksud nya pak? Mf pemula

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3772

**Comment by benioke** [comment]
Sudah di coba tapi belum berfungsi pak

**Comment by benioke** [comment]
Belum berfungsi pak?
Misalkan nama dusun nya
II KAMPUNG PANJANG
Hasil rtf nya menjadi
Ii Kampung  Panjang

Yang di harapkan di mana pun letak nama dusun nya.ketika nama dusun nya ada huruf romawi, maka maka di rtf surat nya menjadi UPPERCASE
