### ISSUE TITLE
[Peta] [RTM] Foto rumah di modul rumah tangga dan ditampilkan pada pencarian penduduk di peta

### ISSUE THREAD

**Issue by khiar-rara** [OpenSID/OpenSID#3773]
### Seperti apa yang diharapkan?
Penambahan foto rumah di modul rumah tangga dan ditampilkan pada pencarian di peta

### Apa yang terjadi?
Dapat mengetahui kondisi rumah penduduk

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by mizwaruddin** [comment]
Saat menambahkan data rumah tangga, sediakan input koordinat dan upload gambar rumah.

**Comment by khiar-rara** [comment]
Issue menambahkan lokasi tempat tinggal (koordinat) dimodul rumah tangga sudah pernah saya buat, tapi diclose dgn alasan lokasi tempat tinggal untuk individu penduduk

**Comment by khiar-rara** [comment]
Tambahan input mungkin bisa keadaan rumah atap/dinding dan sanitasi. Untuk bahan perencanaan desa

**Comment by eddieridwan** [comment]
> Tambahan input mungkin bisa keadaan rumah atap/dinding dan sanitasi. Untuk bahan perencanaan desa

Data sosial-ekonomi seperti ini sebaikya dikumpulkan melalui modul Analisis. Di situ dikumpulkan data rinci melalui sensus/survei untuk dianalilis sebagai masukan perencanaan. Harap pelajari modul itu. Bisa berguru pada @MUHAMMADRANGSEL atau teman2 senior lainnya.

**Comment by eddieridwan** [comment]
@mizwaruddin @khiar-rara , apakah lokasi rumah tangga sama dengan lokasi kepala rumah tangga? Jika jawabannya 'iya' maka tidak perlu ditambahkan. Hindari duplikasi dan penambahan data yg sudah ada.

**Comment by MUHAMMADRANGSEL** [comment]
Sama

Pada tanggal Sab, 16 Jan 2021 15.16, Eddie Ridwan <notifications@github.com>
menulis:

**Comment by eddieridwan** [comment]
Kalau begitu, ubah issue ini, supaya :
1. meminta lokasi rumah tangga menunjukkan lokasi kepala rumah tangga. 
2. Dan kalau foto rumah juga diperlukan, minta ditambahkan di form keluarga. 

@khiar-rara @mizwaruddin @MUHAMMADRANGSEL

**Comment by mizwaruddin** [comment]
Klo foto rumah sya lbh condong ditambahkan di rumah tangga, bukan KK. 
Klo di KK nanti akan ada dobel data rumah krn banyak sekali satu rumah tangga yg berisi lbh dr satu KK.

**Comment by afa28** [comment]
> Klo foto rumah sya lbh condong ditambahkan di rumah tangga, bukan KK. 
> Klo di KK nanti akan ada dobel data rumah krn banyak sekali satu rumah tangga yg berisi lbh dr satu KK.

Yg sensus penduduk sebelumnya patokannya rumah tangga kan ya??? Jd mungkin lokasi rumah tangga diambil dr lokasi kepala rt.

**Comment by afa28** [comment]
> Kalau begitu, ubah issue ini, supaya :
> 1. meminta lokasi rumah tangga menunjukkan lokasi kepala rumah tangga. 
> 2. Dan kalau foto rumah juga diperlukan, minta ditambahkan di form keluarga. 
> 
> @khiar-rara @mizwaruddin @MUHAMMADRANGSEL 

Setuju

**Comment by andifahruddinakas** [comment]
Duplicate of https://github.com/OpenSID/OpenSID/issues/5499
