### ISSUE TITLE
Bug Versi 20.11 - Permasalahan Ketika Login error 404

### ISSUE THREAD

**Issue by rismanbelajar** [OpenSID/OpenSID#3774]
### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by rismanbelajar** [comment]
Tidak Bisa Login Karena controller tidak meredirect ke halaman admin. nyangkut di fungsi auth

**Comment by afa28** [comment]
> Tidak Bisa Login Karena controller tidak meredirect ke halaman admin. nyangkut di fungsi auth

Silahkan cek postingan di group yg berkaitan dgn issue ini.

**Comment by afa28** [comment]
#3768
