### ISSUE TITLE
Perbaiki Format Tanggal Lahir Penduduk pada surat cetak rtf

### ISSUE THREAD

**Issue by benioke** [OpenSID/OpenSID#3779]
Bagaimana alurnya sampai muncul masalah?
Hasil cetak surat rtf nya tidak sesuai format nya.lihat gambar dibawah ini contoh hasil cetak surat rtf nya.

![Capture](https://user-images.githubusercontent.com/47577404/99997458-c4602100-2def-11eb-8f5c-1e279c51ba60.JPG)
![Capture1](https://user-images.githubusercontent.com/47577404/99997463-c629e480-2def-11eb-9817-2c385fb3b577.JPG)

Seperti apa yang diharapkan?
Seharusnya tanggal lahir penduduk sesuai format nya

Apa yang terjadi?
Hasil cetak surat rtf nya..format tanggal penduduk nya tidak berjalan normal

 Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.11
| Versi PHP        | 
| System operasi   |

**Comment by agungsugiarto** [comment]
Apakah bug ini ada di semua surat pak @benioke ?

**Comment by benioke** [comment]
Tidak semua di coba pak..tapi beberapa..mgkin bisa si coba di surat lain yang ada di sistim

**Comment by benioke** [comment]
Untuk tgl_indo_out yang bermasalah
Untuk tgl_indo_dari _str tidak bermasalah

**Comment by eddieridwan** [comment]
Sudah dicommit ke `master`.
Masalah di function `set_ucwords()` di `donjo-app/helpers/donjolib_helper.php`.
