### ISSUE TITLE
Penampakan "; pada Statistik DPT

### ISSUE THREAD

**Issue by Jhiban-Khang** [OpenSID/OpenSID#3781]
### Bagaimana alurnya sampai muncul masalah?

Muncul pada page https://demo.opensid.my.id/first/dpt
### Seperti apa yang diharapkan?

tidak muncul "; agar terlihat rapih
### Apa yang terjadi?

tidak muncul ";
### Informasi tambahan 

dirapihkan biar maknyus
![Screenshot at 2020-11-24 19-18-55](https://user-images.githubusercontent.com/19563843/100093741-89f79200-2e8a-11eb-9b79-ab8146ab90e2.png)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.11 Pasca
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melallui PR #3790
