### ISSUE TITLE
Penambahan sub ketegori di data suplemen

### ISSUE THREAD

**Issue by WAHYUDIK** [OpenSID/OpenSID#3783]
### Bagaimana alurnya sampai muncul masalah?
ketika ingin mencari/membuat sebuah data, dimana data tersebut mempunyai banyak kategori2 masih belum bisa, contoh kasus: ketika kita ingin mengetahui pendidikan S1, di pendidikan terakhir hanya terdapat S1/S2/S3 dll, sedangkan di pendidikan tersebut masih banyak jurusan. 

### Seperti apa yang diharapkan?
dengan adanya penambahan subkategori akan memudahkan untuk mengelompokkan data,
misalkan untuk pendidikan
1. Nama Data Suplemen : Pendidikan
    subkategori: Pendidikan S1
          data penduduk : ......... 

subkategori yang dimaksud seperti ketika ingin membuat menu
![image](https://user-images.githubusercontent.com/31026980/100101732-376fa300-2e95-11eb-9d07-a4a1cea29e54.png)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by mizwaruddin** [comment]
@afa28 Data suplemen tidak digunakan untuk data yang rumit. Contoh kasus yg disampaikan dlm issue ini bisa didteksi melalui statistik kependudukan.

**Comment by afa28** [comment]
> @afa28 Data suplemen tidak digunakan untuk data yang rumit. Contoh kasus yg disampaikan dlm issue ini bisa didteksi melalui statistik kependudukan.

Ya, bisa di filter dari statistik maupun dengan melakukan pencarian spesifik.

**Comment by mizwaruddin** [comment]
@WAHYUDIK apakah bisa di-close? Atau ada pendapat lain?
