### ISSUE TITLE
Tambahkan Tanda Tangan Camat Pada Surat Keterangan Kurang Mampu

### ISSUE THREAD

**Issue by kang-asgar** [OpenSID/OpenSID#3785]
### Bagaimana alurnya sampai muncul masalah?
Format Surat Keterangan Kurang mampu yang memakai tanda tangan camat

### Seperti apa yang diharapkan?
Tambahakan Tanda Tangan Camat

![image](https://user-images.githubusercontent.com/61548658/100202888-7dc80f00-2f34-11eb-94ad-8c618501d5fe.png)

### Apa yang terjadi?
Di Desa Kami Format Surat Keterangan Kurang Mampu Membutuhkan Tanda tangan Camat

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by roaddee** [comment]
untuk nama camat, bisa gunakan : [nama_kepala_camat]
nik cama : [nip_kepala_camat]

**Comment by kang-asgar** [comment]
oh ini sudah ada 
siap

**Comment by eddieridwan** [comment]
Daftar kode_isian yg sdh tersedia ada di https://github.com/OpenSID/OpenSID/wiki/Kode-Isian-Template-Surat.
