### ISSUE TITLE
Fitur Pencarian di Data Suplemen tdk berfungsi normal

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#3788]
### Bagaimana alurnya sampai muncul masalah?
Ketika melakukan pencarian data di Data Suplemen yang muncul seperti gambar dibawah :
![image](https://user-images.githubusercontent.com/25834335/100316962-7406e000-2ff6-11eb-8ef8-53c4a95ce197.png)

### Seperti apa yang diharapkan?
Fitur Pencarian berjalan dengan normal

### Apa yang terjadi?
Error

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Apakah melalui pencarian atau mengisi url secara eksplisit. Kalau melakukan pencarian, teks apa yg dimasukkan ke kotak cari?

Saya coba di situs demo, tidak berasalah, kecuali apabila secara sengaja memasukkan url seperti di contoh anda.

**Comment by eddieridwan** [comment]
Kasus pemanggilan rincian tanpa id data suplemen sekarang tidak error.
