### ISSUE TITLE
Nama Kabupaten dan Provinsi di Info Desa jadi Huruf Besar Semua

### ISSUE THREAD

**Issue by ahmadngudi** [OpenSID/OpenSID#3789]
Nama Kabupaten dan Provinsi jadi Huruf Besar di pilihan Info Desa

### Bagaimana alurnya sampai muncul masalah?
Setelah Update versi terbaru, Pilihan Desa di Info Desa Kabupaten dan Provinsi jadi Huruf Besar
![Screenshot_9](https://user-images.githubusercontent.com/57133748/100519707-50958e00-31cc-11eb-9f17-102b86c2c0a1.jpg)

### Seperti apa yang diharapkan?
Kembali Seperti Semula, 

### Apa yang terjadi?
di Surat Menyurat Juga Ikut Besar Semua, Jadi kalo dilihat Kurang Pas
![Screenshot_10](https://user-images.githubusercontent.com/57133748/100519756-86d30d80-31cc-11eb-9cde-5280aab8a8a3.jpg)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.11-premium-pasca
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
Pak @fusionid, kyaknyak perlu disesuaikan.

**Comment by eddieridwan** [comment]
Sdh dicommit ke `rilis-dev` melalui PR https://github.com/OpenSID/premium/pull/25
