### ISSUE TITLE
Wordpress plugin untuk OpenSID

### ISSUE THREAD

**Issue by simasta** [OpenSID/OpenSID#379]
Mas @eddieridwan dan kawan2. 
Ini saya buatkan wordpress plugin untuk OpenSID. 
Mungkin ada desa yang sudah memiliki website berbasis wordpress, jadi tinggal mengintegrasikannya dengan opensid.

Plugin ini hanya mengambil data2 dari Opensid front lalu dibuat shortcode yang bisa dipasang di halaman, post atau widget wordpress.

Demo nya bisa dilihat di: http://wpsid-shortcode.plugin.demo.siini.com/

Plugin ini sudah terdaftar di wordpress, silahkan kunjungi https://wordpress.org/plugins/wpsid-shortcode/

Untuk rekan2 yang ingin menambahkan issues bisa ke https://wordpress.org/support/plugin/wpsid-shortcode
atau ke https://github.com/simasta/wpsid-shortcode , atau langsung ke di profile saya.

**Comment by eddieridwan** [comment]
Keren... terima kasih telah menambah jalur pemanfaatan OpenSID.

Mungkin anda juga berminat kontribusi langsung pada OpenSID? Seperti anda ketahui ada banyak issue di https://github.com/eddieridwan/OpenSID/issues yang diminta/diusulkan oleh komunitas OpenSID. Kontributor berpengalaman seperti anda pasti bisa banyak membantu.

**Comment by simasta** [comment]
Ok mas @eddieridwan , insya Allah akan saya lirik, semampu saya.

**Comment by mdwone** [comment]
Wah saya sangat tertarik. apakah plugin ini masih bisa di download.?

**Comment by samsulmaarif** [comment]
@mdwone masih donk...

**Comment by ZulIhwandi** [comment]
p;ugin ya, tidakbisa di gunakan lagi pak, sudah saya coba, database nya tidak terkoneksi, dan fileopen sid salah, mohonsolusinya pak, opensid v 18.10

**Comment by Lembu** [comment]
Sudah tidak bisa digunakan sepertinya:
DB connection filed
SID Path is not directory

**Comment by afa28** [comment]
Issue mengenai plugin wordpress OpenSID bisa di pindahkan ke https://github.com/OpenSID/wpsid-shortcode
