### ISSUE TITLE
Cetak KK Perlu diperbarui

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#3793]
saat ini cetak KK dari dispendukcapil selain mencantumkan tanggal menikah bagi yang berstatus menikah, kini juga mencantumkan tanggal cerai bagi yang berstatus cerai

Opensid perlu penyesuaian Cetak KK mengikuti Dispendukcapil

![WhatsApp Image 2020-12-01 at 09 54 50](https://user-images.githubusercontent.com/35319600/100691729-e7746d00-33bb-11eb-9695-9fc8d6a6fe5e.jpg)
 

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3796
