### ISSUE TITLE
Tampilkan poto penduduk didalam surat keterangan Jika poto tidak ada maka tidak tampil

### ISSUE THREAD

**Issue by kang-asgar** [OpenSID/OpenSID#3794]
### Bagaimana alurnya sampai muncul masalah?
didalam surat keterangan untuk menampilkan poto penduduk

### Seperti apa yang diharapkan?
Tampilkan poto penduduk didalam surat keterangan 
Jika poto tidak ada maka tidak tampil
![2020-12-01_11h46_13](https://user-images.githubusercontent.com/61548658/100700585-61165600-33d0-11eb-8f7a-af357bfa6b46.png)

### Apa yang terjadi?
Ada Intansi terkait minta menampilkan poto penduduk.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sdh dicommit ke branch `rilis-dev` premium melalui PR #3797
