### ISSUE TITLE
Error Saat Buat Surat Layanan Mandiri

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#3798]
### Bagaimana alurnya sampai muncul masalah?
Sebuah surat diatur tidak ada satupun Syarat Surat yang dicentang pada pengaturan surat, akan terjadi error ketika klik periksa surat oleh operator.

<img width="785" alt="2020-12-03_22h41_14" src="https://user-images.githubusercontent.com/46939846/101051981-adbc8580-35b8-11eb-87f7-201c3f0d8ac8.png">

Begini Error nya:

<img width="437" alt="2020-12-03_22h41_50" src="https://user-images.githubusercontent.com/46939846/101052078-c7f66380-35b8-11eb-8b41-effe4c8f6246.png">

ERROR - 2020-12-03 22:41:46 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')' at line 3 - Invalid query: SELECT `id`, `nama`
FROM `dokumen`
WHERE `id` in ()
ERROR - 2020-12-03 22:41:46 --> Severity: error --> Exception: Call to a member function result_array() on bool /home/demoopen/public_html/donjo-app/models/Permohonan_surat_model.php 200

### Seperti apa yang diharapkan?
Normal, surat tersebut dapat ditindaklanjuti oleh Operator.

### Apa yang terjadi?
(Ini terjadi saat Pengaturan Surat Tidak dicentang 1 pun pada Syarat Surat)

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3799
