### ISSUE TITLE
Seragamkan Kembali huruf besar/kecil di tampilan alamat di surat export doc

### ISSUE THREAD

**Issue by Gunturwijay** [OpenSID/OpenSID#3800]
Supaya Kelihatan Lebih Cantik perlu di seragamkan semua penulisan alamat di Export Surat menjadi Huruf Besar Awal saja Baik Alamat Individu, Alamat Orang Tua dan Yang Lainnya.

![image](https://user-images.githubusercontent.com/40741591/101115287-ae373980-3615-11eb-99a1-8808e24cf14e.png)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.12-pasca
| Versi PHP        | 
| System operasi   |

**Comment by agungsugiarto** [comment]
STANDAR BAKU PENULISAN NAMA JALAN
https://ortax.org/files/lampiran/00PJ_KEP533h2.htm

**Comment by Gunturwijay** [comment]
@agungsugiarto itu standar baku untuk kegiatan apa ? sepertinya bukan untuk penulisan surat

**Comment by mizwaruddin** [comment]
![issue_1](https://user-images.githubusercontent.com/39736008/103403682-a373b400-4b83-11eb-9131-4ed69d165ae5.png)
@afa28 Saya coba di demo penulisan alamat sudah sesuai ejaan, diawali dg huruf kapital.

**Comment by afa28** [comment]
> ![issue_1](https://user-images.githubusercontent.com/39736008/103403682-a373b400-4b83-11eb-9131-4ed69d165ae5.png)
> @afa28 Saya coba di demo penulisan alamat sudah sesuai ejaan, diawali dg huruf kapital.

Silahkan reopen issue ini jika masih bermasalah.
