### ISSUE TITLE
Terjadi error saat import data penduduk dalam format .xlsx

### ISSUE THREAD

**Issue by dani1107** [OpenSID/OpenSID#3801]
### Bagaimana alurnya sampai muncul masalah?
Saat melakukan inport data penduduk terdapat pesan kegagalan, tetapi data berhasil masuk ke DB kecuali data alamat

### Seperti apa yang diharapkan?
Para master tolong segera di perbaiki

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.12
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
@dani1107 biasakan melampirkan contoh data yg bermasalah. Saya coba impor data contoh `assets/import/contoh_penduduk.xlsx`, tidak bermasalah. Tapi terlihat yg tampil gagal adalah impor data penduduk yg dibuat menggunakan template macro `assets/import/FormatImportExcel.xlsm`

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3836
