### ISSUE TITLE
Tampilkan Halaman Data Suplemen Pada Halaman Website

### ISSUE THREAD

**Issue by afa28** [OpenSID/OpenSID#3802]
### Bagaimana alurnya sampai muncul masalah?
Permintaan pd forum FB https://m.facebook.com/groups/OpenSID/permalink/1725811180917189/

### Seperti apa yang diharapkan?
tampilkan data suplemen pd halaman website

### Apa yang terjadi?
data suplemen tersedia pd halaman website

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR https://github.com/OpenSID/premium/pull/26
