### ISSUE TITLE
Sebutan nip desa pd versi premium

### ISSUE THREAD

**Issue by afa28** [OpenSID/OpenSID#3803]
### Bagaimana alurnya sampai muncul masalah?
Setelah migrasi dari rilis umu ke premium, pada  pengaturan > aplikasi > sebutan_nip_desa terhapus/terganti oleh ukuran_lebar_bagan.

### Seperti apa yang diharapkan?
sebutan_nip_desa kembali

### Apa yang terjadi?
sebutan_nip_desa kembali

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
@afa28 error ini terjadi pada migrasi dari rilis umum berapa? Ke rilis premium berapa?

**Comment by afa28** [comment]
> @afa28 error ini terjadi pada migrasi dari rilis umum berapa? Ke rilis premium berapa?

Bukan error pak, cuma menindih. Krn menggunakan id sebagai pengkondisiannya.

Sy temukan waktu migrasikan website kombaselatan dr umum ke premium.

**Comment by afa28** [comment]
Id yg digunakan sebutan_nip sama dengan lebar_bagan, sehingga sebutan_nip terganti di saat migrasi dr umum ke premium.

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR https://github.com/OpenSID/premium/pull/27
