### ISSUE TITLE
Nama penduduk menampilkan tanda " \"(garis miring) di kolom pencarian nama di modul cetak surat

### ISSUE THREAD

**Issue by benioke** [OpenSID/OpenSID#3804]
Bagaimana alurnya sampai muncul masalah?
Ada nya tanda " ' "(garis miring) ketika nama penduduk memakai simbol " ' "(tanda petik satu)
Contoh nya ELVA WALIZA RIFA'I
![petik1](https://user-images.githubusercontent.com/47577404/101244589-fd768a80-3739-11eb-86c8-319734e3c058.JPG)

Saat pencarian penduduk di form surat
![petik2](https://user-images.githubusercontent.com/47577404/101244605-10895a80-373a-11eb-9b8a-acbe0dfa825b.JPG)

![petik3](https://user-images.githubusercontent.com/47577404/101244610-17b06880-373a-11eb-85e8-952c24e954e6.JPG)

Seperti apa yang diharapkan?
Seharusnya nama penduduk tampil sesuai format nya

Apa yang terjadi?
Nama penduduk nya tidak sesuai dengan nama sebenarnya

 Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.12
| Versi PHP        | 
| System operasi   |

**Comment by benioke** [comment]
Belum berfungsi pak

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3809
