### ISSUE TITLE
Error 500 pada Statistik Menurut Kepemilikan KTP yaitu Baris "Jumlah" dan Baris "Total"

### ISSUE THREAD

**Issue by agungsugiarto** [OpenSID/OpenSID#3805]
### Bagaimana alurnya sampai muncul masalah?
Buka menu Statistik > Statistik Kepenedudukan > Kepemilikan KTP
Klik angka pada row jumlah dan total. Muncul error 500
Selengkapnya: https://www.facebook.com/groups/OpenSID/permalink/1727845024047138/

### Seperti apa yang diharapkan?
Tidak muncul error 500

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.12-pasca
| Versi PHP        | 7.3
| System operasi   |

**Comment by eddieridwan** [comment]
![image](https://user-images.githubusercontent.com/249563/101304007-74736680-3893-11eb-86ed-12a1a3c023d9.png)

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3806
