### ISSUE TITLE
Sediakan pengaturan untuk mengaktifkan / mematika layanan mandiri

### ISSUE THREAD

**Issue by afa28** [OpenSID/OpenSID#3808]
### Bagaimana alurnya sampai muncul masalah?
Saat ini tidak ada pengaturan di aplikasi untuk mematikan layanan mandiri.

### Seperti apa yang diharapkan?
Adanya pengaturan mode layanan mandiri.

### Apa yang terjadi?
Bisa menyesuaikan penggunaan layanan mandiri.

### Informasi tambahan 
Mode :
1. Layanan mandiri akses dimatikan
2. Layanan mandiri akses ip address (jika tdk ada list ip adress, maka layanan di matikan)
3. Layanan mandiri akses publik

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
@afa28 , apakah desa yg meminta fitur ini?

**Comment by afa28** [comment]
> @afa28 , apakah desa yg meminta fitur ini?
> 

Ya, kalau di komba selatan tp tdk tau klw desa  lain kurang tau. 

Krn kadang layanan mandiri perlu jg dimatikan, misalnya websitenya sedang maintenance atau desa dlm keadaan tdk bisa melakukan pelayanan scr online.

**Comment by eddieridwan** [comment]
Untuk mematikan layanan mandiri, lakukan di rilis umum dulu. Dengan setting layanan mandiri dimatikan, ubah supaya:
1. Widget login tidak aktif, dan login mandiri tidak bisa diakses
Karena tidak bisa login, otomatis halaman mandiri tidak bisa diakses. 

Setting mematikan/aktifkan layanan mandiri sebaiknya juga bisa diakses di menu Layanan Mandiri > Pengaturan.

Nanti setelah masuk ke rilis umum, baru digabung ke rilis premium. Di premium, dengan setting dimatikan:
2. Login mandiri tidak tampil, dan login mandiri tidak bisa diakses.
Karena tidak bisa login, otomatis halaman mandiri tidak bisa diakses. 

Di premium, kalau ada anjungan yg aktif, maka:
3. Login mandiri tetap tampil di anjungan tersebut, dan bisa login mandiri dari anjungan tersebut dengan setting anjungan.

**Comment by afa28** [comment]
Ok

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3821
