### ISSUE TITLE
[Menu] Custom Icon Menu Halaman Depan Web seperti di Pengaturan Modul

### ISSUE THREAD

**Issue by hasap86** [OpenSID/OpenSID#3810]
### Bagaimana alurnya sampai muncul masalah?
saat ini icon pada menu halaman depan web sama semua

### Seperti apa yang diharapkan?
bisa pilih sesuai selera icon menunya saat menambah atau mengedit menu seperti memilih icon pada Pengaturan > Modul

### Apa yang terjadi?
kurang menarik 

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | demo
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
Yg dimaksud menu halaman depan website???

**Comment by hasap86** [comment]
> Yg dimaksud menu halaman depan website???

ya betul

**Comment by ianskids** [comment]
Sepertinya icon menu ini tidak dipakai pada tema klasik dan natra

> > Yg dimaksud menu halaman depan website???
> 
> ya betul

Sepertinya icon menu ini tidak dipakai pada tema klasik dan natra

**Comment by andifahruddinakas** [comment]
Issue ini tidak bisa diterapkan, krn masing2 tema menggukan icon yg berbeda2.
