### ISSUE TITLE
[Menu] Munculkan Pilihan Link Gallery pada saat membuat Menu Statis

### ISSUE THREAD

**Issue by hasap86** [OpenSID/OpenSID#3811]
### Bagaimana alurnya sampai muncul masalah?
untuk memuncukan tampilan Gallery saat ini hanya bisa melalui link Gallery di Widget, belum bisa dimunculkan langsung di Menu Statis dengan cara memilih Link Gallery (/first/gallery) dan mungkin link firstnya dihilangkan?

### Seperti apa yang diharapkan?
dimunculkan di Menu Statis pada pilihan Halaman Statis Lainnya supaya bisa ditampilkan di Menu Web

### Apa yang terjadi?
banyak pengunjung yg tidak tahu bahwa judul widget Gallery bisa di klik

### Informasi tambahan 
![Screen Shot 2020-12-06 at 15 17 38](https://user-images.githubusercontent.com/45263721/101275242-bd191a00-37d6-11eb-8109-e4cef56fe9b7.png)

Menu statis adalah yg biasanya tampil di bagian atas halaman. web.
![menu-statis](https://user-images.githubusercontent.com/249563/141880467-306a999b-7f2c-4a75-be9a-23592f1bdad2.jpg)

Cara untuk berkontribusi dijelaskan di https://github.com/OpenSID/OpenSID/wiki/Cara-Ikut-Mengembangkan-OpenSID.

Panduan OpenSID ada di https://github.com/OpenSID/OpenSID/wiki

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | v21.11
| Versi PHP        | 
| System operasi   |

**Comment by andifahruddinakas** [comment]
PERBAIKAN : 
- [ ] 1. Tambahkan galery dan sub galery pada pilihan menu.
- [ ] 2. Perbaiki route, hapus first/.
- [ ] 3. Gunakan slug untuk menampilkan data sub galery pada website.
