### ISSUE TITLE
[Pengaturan] Pengaturan Style Header pada Admin Web

### ISSUE THREAD

**Issue by hasap86** [OpenSID/OpenSID#3812]
### Bagaimana alurnya sampai muncul masalah?
saat ini untuk merubah gambar header hanya bisa melalui cpanel dan sejenisnya, belum bisa melalui Pengaturan Admin Web

### Seperti apa yang diharapkan?
Sediakan Menu baru di Admin Web dengan nama "Header" dan berisi upload gambar Header untuk sementara, bisa dikembangkan untuk selanjutnya style header seperti jenis huruf, besar huruf, warna huruf, dsb

### Apa yang terjadi?
kesulitan bagi yg tidak punya akses cpanel, dan untuk mempercepat

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | Demo
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
Nantinya akan ditambahkan di pengaturan tema. Dengan beberapa tambahan pengaturan lainnya yg diperlukan oleh tema tsb.
