### ISSUE TITLE
Perbaiki keterangan data orang tua dari calon pria dan calon wanita pada Surat Keterangan Untuk Nikah (N-1 s/d N-7)

### ISSUE THREAD

**Issue by benioke** [OpenSID/OpenSID#3813]
Bagaimana alurnya sampai muncul masalah?
Jika status dalam biodata penduduk atau calon pria atau calon wanita berstatus beristri,duda,janda. Maka tampilan data orang tua nya,seperti ini

1.Penduduk status beristri

![beristri](https://user-images.githubusercontent.com/47577404/101278172-471fad80-37ec-11eb-830e-dacba079532f.JPG)

2.Penduduk status janda(cerai hidup)

![janda hidup](https://user-images.githubusercontent.com/47577404/101278177-4f77e880-37ec-11eb-8f22-142d44187e7a.JPG)

3.Penduduk status janda(cerai mati)

![janda mati](https://user-images.githubusercontent.com/47577404/101278180-556dc980-37ec-11eb-82d9-62d67d98e2ac.JPG)

Seperti apa yang diharapkan?
Seharusnya keterangan data ibu tidak tampil otomatis dan di tulis secara manual karna tidak ada di dalam satu kk atau mungkin luar desa

Apa yang terjadi?
Data ibu dari calon pria atau calon wanita tampil tidak normal dan untuk data ayah seperti nya normal. yang masalah untuk data,ibu dari database

 Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.12
| Versi PHP        | 
| System operasi   |

**Comment by benioke** [comment]
Masih menunggu para master

**Comment by mizwaruddin** [comment]
Senggol @ianskids

**Comment by ianskids** [comment]
@mizwaruddin @benioke Apakah yang dimaksud untuk form isian data orang tua bisa di edit?

**Comment by mizwaruddin** [comment]
Betul. Atau bisa jg tambahkan tombol orang tua tidak terdata.

**Comment by benioke** [comment]
Iya yang jadi masalah pada data ibu..saharus nya jika penduduk beratatus beristri,janda,duda maka data ibu terisi otomatis dan tidak bisa di edit..
Coba di demo untuk surat keterangan untuk nikah (N-1 s/d N-7) cari penduduk yang betstatus beristri,duda atau janda.maka data ibu dari penduduk tersebut tidak bisa di edit

**Comment by benioke** [comment]
> @mizwaruddin @benioke Apakah yang dimaksud untuk form isian data orang tua bisa di edit?

**Comment by benioke** [comment]
> @mizwaruddin @benioke Apakah yang dimaksud untuk form isian data orang tua bisa di edit?

Iya yang jadi masalah pada data ibu..saharus nya jika penduduk beratatus beristri,janda,duda maka data ibu terisi otomatis dan tidak bisa di edit..
Coba di demo untuk surat keterangan untuk nikah (N-1 s/d N-7) cari penduduk yang betstatus beristri,duda atau janda.maka data ibu dari penduduk tersebut tidak bisa di edit

**Comment by ianskids** [comment]
@mizwaruddin @benioke Saat ini data ibu diambil langsung dari database, 
apakah ada kemungkinan jika data ibu kosong harus input data penduduk terlebih dahulu?
atau hanya sebagai form untuk isian surat keterangan saja?

**Comment by benioke** [comment]
> @mizwaruddin @benioke Saat ini data ibu diambil langsung dari database,
> apakah ada kemungkinan jika data ibu kosong harus input data penduduk terlebih dahulu?
> atau hanya sebagai form untuk isian surat keterangan saja?

Sebaik nya disamakan dengan data ayah harus di input data penduduk dahulu

**Comment by mizwaruddin** [comment]
> > @mizwaruddin @benioke Saat ini data ibu diambil langsung dari database,
> > apakah ada kemungkinan jika data ibu kosong harus input data penduduk terlebih dahulu?
> > atau hanya sebagai form untuk isian surat keterangan saja?
> 
> Sebaik nya disamakan dengan data ayah harus di input data penduduk dahulu karna sudah terpisah dari kartu keluarga

Klo hanya data ayah dan Ibu yg diperbaiki pada biodata penduduk (calon pengantin), maka data ayah/ibu juga tidak akan lengkap.

**Comment by eddieridwan** [comment]
Maaf terlambat menanggapi. Masalahnya belum jelas untuk saya. Bukankah yg tercatat di database adalah ayah/ibu kandung seseorang? Dan dengan demikian data tersebut akan **_selalu berlaku_** terlepas apakah orang itu belum kawin, sudah kawin, cerai atau bahkan meninggal sekalipun? Mengapa harus diubah di surat nikah? Kalau datanya salah, ubah dulu di penduduk ybs.

Atau apakah masalahnya adalah data ayah/ibu tidak diperlukan di surat nikah bagi calon mempelai yg janda/duda?

Mohon penjelasan teman2.

**Comment by eddieridwan** [comment]
@ianskids , masalahnya bukan karena status kawin atau pria/wanit, tetapi karena data ayah/ibu calon mempelai tidak terdata di database penduduk. Pada setiap kasus di mana terdeteksi bahwa ayah/ibu calon tidak tercatat di database, maka di form perlu bisa dilengkapi. Saat ini penampilan data ayah/ibu untuk calon pria/wanita dua2nya masih salah.

Contoh kasus DELLA MAHARANI NINGSIH di contoh data awal, seorang dengan status keluarga 'Famili' dan belum kawin:

![ayah-ibu-tidak-ada](https://user-images.githubusercontent.com/249563/104147657-544f3e00-5423-11eb-93d5-db8b92f47b81.jpg)

Data ayah/ibu yg tercatat untuk DELLA MAHARANI NINGSIH:

![data-ayah-ibu](https://user-images.githubusercontent.com/249563/104147746-b314b780-5423-11eb-9ba6-888e09632648.jpg)

**Comment by eddieridwan** [comment]
Bung @ianskids , jadi yg perlu diperiksa adalah cara mendeteksi ayah/ibu, yg perlu menghasilkan status apakah terdata secara tersendiri di database, atau hanya diambil dari kolom ayah/ibu pada calon ybs. Kalau tidak terdata secara tersendiri, maka ambil data yg ada (NIK, nama) dan kemudian form dibuat supaya dapat diubah untuk dilengkapi.

**Comment by afa28** [comment]
> Bung @ianskids , jadi yg perlu diperiksa adalah cara mendeteksi ayah/ibu, yg perlu menghasilkan status apakah ayah/ibu terdata secara tersendiri di database, atau hanya diambil dari kolom ayah/ibu pada calon ybs. Kalau tidak terdata secara tersendiri, maka ambil data yg ada (NIK, nama) dan kemudian form dibuat supaya dapat diubah untuk dilengkapi. 
> 
> Perhatikan, bahwa adanya NIK di data ayah/ibu belum tentu menunjukkan orang ybs terdata. Jadi perlu diperiksa juga apakah NIK tersebut ditemukan.

Mungkin yg perlu dikerjakan terlebih dahulu form isian data orang tuan (dr database/dr luar desa). Kayaknya pernah ada issuenya.

Sehingga ketika ada surat butuh data orang tua tinggal diambil sj, tdk perlu di input lg dr awal.

**Comment by mizwaruddin** [comment]
Kasusnya seperti ini:
A Kepala Keluarga dg status Kawin Cerai/Cerai Mati. Ketika ingin menikah lagi, maka data ortu (ayah & ibu) kosong. Mengapa? Bukan krn data ayah dan ibu pada KK ybs kosong.

Hal ini beda dg jika yg akan menikah SHDK dlm KK adalah "anak". Jika anak yg akan menikah data ortu akan otomatis terisi krn dlm KK masih ada SHDK ayah dan ibu.

Oleh sebab itu, prlu ditambahkan opsi " Ayah/Ibu Tidak Terdata".

**Comment by mizwaruddin** [comment]
Untuk meyakinkan lgi, mungkin bisa dicek dg calon pengantin yg dalam KK-nya hanya ada SHDK Ayah. Nanti dlm surat, data ibu jg akan kosong.

**Comment by mizwaruddin** [comment]
Simpulannya, semua jenis surat tdk bisa nge-link dg data ortu yg sdh meninggal/pindah/hilang.

**Comment by eddieridwan** [comment]
@mizwaruddin @ianskids algoritma script utk otomatis mencari orang tua, dan mengetahui apakah terdata atau tidak:
1. kalau SHDK `anak`, ayah adalah KK pria atau SHDK `suami` kalau KK wanita
2. kalau SHDK `anak`, ibu adalah KK wanita atau SHDK `istri` kalau KK pria
3. kalau SHDK bukan anak, lihat di kolom NIK/nama ayah/ibu
    1. Kalau ada NIK coba cari NIK ayah/ibu tersebut di daftar penduduk. Kalau tidak ditemukan, status ayah/ibu --> tidak terdata; dan ambil data sebisanya dari kolom NIK/nama ayah/ibu
    2. Kalau NIK ditemukan di daftar penduduk (dengan status-dasar apapun), ambil data ayah/ibu dari situ
    3. Kalau NIK kosong, otomatis --> tidak terdata, dan ambil data nama ayah/ibu kalau ada

Sebagian dari algoritma di atas telah diterapkan sebelumnya (di `donjo-app/models/Surat_model.php` cari method `get_data_ibu($id=0)` dan `get_data_ayah($id=0)`. Tinggal disempurnakan saja.

**Comment by benioke** [comment]
Menurut saya..surat keterangan untuk nikah yang ada di opensid versi 19.10 sudah berjalan dengan lancar...

**Comment by eddieridwan** [comment]
Sdh dicommit ke `rilis-dev` melalui PR https://github.com/OpenSID/premium/pull/67
