### ISSUE TITLE
Tombol Cari pada widget Cari Artikel kurang mentok ke kanan

### ISSUE THREAD

**Issue by hasap86** [OpenSID/OpenSID#3814]
### Bagaimana alurnya sampai muncul masalah?
tombol Cari pada widget Cari Artikel di web depan terlalu ke tengah

### Seperti apa yang diharapkan?
mentok ke kanan biar proporsional

### Apa yang terjadi?
kurang pas

### Informasi tambahan 
![pencarian](https://user-images.githubusercontent.com/45263721/101278359-5ce1a280-37ed-11eb-87ed-5e11b6fd3743.jpg)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | Demo
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
Issuenya bisa dipindahkan ke https://github.com/OpenSID/tema-hadakewa
