### ISSUE TITLE
Jadikan natra sebagai tema bawaan mengganti tema hadakewa

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#3815]
### Bagaimana alurnya sampai muncul masalah?
Saat ini tema bawaan adalah klasik dan hadakewa. Sedangkan tema yg lebih digemar adalah tema natra.

### Seperti apa yang diharapkan?
Natra menjadi tema bawaan OpenSID.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.12
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
Silahkan beri masukan pd issue ini untuk perubahan yg perlu dilakukan pd tema natra.

**Comment by mizwaruddin** [comment]
1. Warna tema diganti biru. Syukur2 bisa disediakan setting utk memilih warna.
2. Pindahkan kotak pencarian artikel utk mengantisipasi jumlah menu yg banyak.

**Comment by afa28** [comment]
> 1. Warna tema diganti biru. Syukur2 bisa disediakan setting utk memilih warna.
> 2. Pindahkan kotak pencarian artikel utk mengantisipasi jumlah menu yg banyak.

1. Untuk sttingan khusus untuk tiap tema nantinya bisa dimasukkan ke pengaturan > tema (modulnya belum siap)
2. Apakah di jadikan widget???

**Comment by mizwaruddin** [comment]
Bisa di widget

**Comment by mizwaruddin** [comment]
Sediakan juga pilihan full screen klo bisa.

**Comment by afa28** [comment]
> Sediakan juga pilihan full screen klo bisa.

Pak @eddieridwan , ini yg sempat sy tulis kemarin lewat chat jitsi saat pertemu (sy kurang tau ada yg lihat atau tdk krn langsung disconnect). Perlu disederhanakan dan dimaksimalkan cara penangan template untuk pemanggilan tema. Krn saat ini banyak penggunaan xxxx.tpl.php (isinya hampir sama) pdahal sdah disediakan tempalte.php. Jd mungkin cukup sediakan file tempate.php (u/ yg utama), full_content/right_content/left_content (sebagai pilihan) dan sisanya bagian partisinya.

**Comment by balongbesuk** [comment]
sebaiknya tema yg menyesuaikan adminlte biar mudah maintenanceny

> 
> 
> Silahkan beri masukan pd issue ini untuk perubahan yg perlu dilakukan pd tema natra.

biasanya para pengguna tema klasik gagal mup on karena d thema2 opensid yang lain tidak menyediakan menu kedua seperti d thema klasik yg punya dua menu,

**Comment by hasap86** [comment]
tema Hakadewa tetap disertakan kan?

**Comment by eddieridwan** [comment]
@hasap86 , nanti tema hadakewa dikelola terpisah di repo github tersendiri, seperti tema natra sekarang. Jadi desa yg ingin menggunakan tetap dapat mengunduh.

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master`.

1. Tema hadakewa telah dipindahkan ke https://github.com/OpenSID/tema-hadakewa
2. Tema natra telah digabung ke OpenSID menggunakan konsep `git subtree` (https://martowen.com/2016/05/01/git-submodules-vs-git-subtrees/). Script tema natra tetap dikelola di https://github.com/OpenSID/tema-natra. Kalau ada update, versi di OpenSID dimutakhirkan menggunakan `git subtree pull --prefix themes/natra https://github.com/OpenSID/tema-natra master --squash`
