### ISSUE TITLE
Permohonan Surat pada Layanan Mandiri Diurutkan dari Permohonan yang Terakhir Masuk

### ISSUE THREAD

**Issue by mizwaruddin** [OpenSID/OpenSID#3818]
### Bagaimana alurnya sampai muncul masalah?
Saat ini urutan permohonan surat pada layanan mandiri dimulai dari tanggal permohonan pertama s.d. terakhir, sehingga ketika ada permohonan baru yg masuk operator haris membuka page terakhir untuk memeriksa surat.

### Seperti apa yang diharapkan?
Urutan permohonan surat pada layanan mandiri dibuat dari tanggal permohonan yang terakhir masuk

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master`.
