### ISSUE TITLE
[Layanan Mandiri] Judul Tab Pada Halaman Login Layanan Mandiri Perlu Disesuaikan

### ISSUE THREAD

**Issue by mizwaruddin** [OpenSID/OpenSID#3819]
### Bagaimana alurnya sampai muncul masalah?
Saat ini judul tab pada halaman login layanan mandiri tertulis OpenSID Nama Desa.

### Seperti apa yang diharapkan?
Judul tersebut perlu disesuaikan/disamakan dengan judul tab homepage. Atau bisa juga dibuat "Layanan Mandiri Nama Desa"
![issue_tab](https://user-images.githubusercontent.com/39736008/101733078-d4b31400-3af0-11eb-8f39-eee61fd805da.png)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
Issue berkaitan dengan layanan mandiri di lanjutkan setelah issue PR https://github.com/OpenSID/premium/pull/47 atau issue https://github.com/OpenSID/OpenSID/issues/3696 selesai digabung.

**Comment by afa28** [comment]
pak @mizwaruddin bisa cek ulang untuk issue ini???

**Comment by mizwaruddin** [comment]
Sekarang sudah sesuai harpan. Trims
