### ISSUE TITLE
Penambahan nama kepala desa atau perangkat desa pada cetak doc.

### ISSUE THREAD

**Issue by TAHTA24** [OpenSID/OpenSID#382]
Pada setiap laporan atau cetak doc. Seharusnya dilengkapi nama kepala desa atau perangkat desa dibagian bawah seperti contohnya laporan kependudukan bulanan. Agar jelas siapa penanggung jawab data yg dicetak tersebut.

**Comment by uncu29** [comment]
issue ini sudah bisa ditutup pak
