### ISSUE TITLE
Tampilkan Nomor HP dan akun Telegram pada Menu Aparatur Desa

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#3820]
### Bagaimana alurnya sampai muncul masalah?
Saat ini belum tersedia link Whatsapp/Telegram/Lainnya di masing-masing Aparatur Desa.

### Seperti apa yang diharapkan?
Adanya kolom nomor Hp agar dapat dibuat link untuk menuju ke sosial media / chat masing-masing Aparatur, sesuai status nya (diaktifkan atau di non aktif kan).

Bagi aparatur desa yang juga penduduk, Nomor HP dan akun Telegram yang ditampilkan adalah yg tersimpan di data penduduk. Bagi aparatur yg bukan warga desa, Nomor HP dan akun Telegram perlu diisi di form aparatur desa.

### Apa yang terjadi?
Agar dapat membuat link tujuan ke kontak masing-masing aparatur, misal dengan klik Nama/Gambar pada Widget Aparatur Desa.

**Comment by balongbesuk** [comment]
sekalian no telp di artikel untuk kebutuhan lapak desa, :smiley:

**Comment by PWidodo** [comment]
Mungkin seperti ini yang dimaksud...?
![image](https://user-images.githubusercontent.com/45189822/107979248-d3223280-6ff0-11eb-882f-3c9d3e034ac4.png)

**Comment by afa28** [comment]
Ini kayaknya sama dengan issue https://github.com/OpenSID/OpenSID/issues/2603

**Comment by ariandii** [comment]
> Ini kayaknya sama dengan issue #2603

di atas menitik beratkan kepada nomor telephone.

namun pada issue #2603 lebih kepada sosial media yg dibenarkan pada kolom komentar tantang icon yg bukan dari nomor telephone.
