### ISSUE TITLE
Tidak Muncul Aksi saat Permohonan Surat Dibatalkan Pemohon

### ISSUE THREAD

**Issue by mizwaruddin** [OpenSID/OpenSID#3823]
### Bagaimana alurnya sampai muncul masalah?
Saat ini jika surat yang sudah diajukan pemohon lewat layanan mandiri online dibatalkan oleh pemohon, tidak muncul aksi di dashboard admin sehingga tidak bisa dihapus dari daftar permohonan surat.
![periksa_surat](https://user-images.githubusercontent.com/39736008/102003561-762da600-3d3b-11eb-845f-a5b77131492f.png)

### Seperti apa yang diharapkan?
Muncul aksi (Hapus Surat) jika permohonan surat dibatalkan oleh pemohon

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Tidak untuk dihapus. Mungkin daftar default bisa disaring tidak menunjukkan permohonan yg dibatalkan.
