### ISSUE TITLE
Perbaiki Kode Barang Inventaris

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#3825]
### Bagaimana alurnya sampai muncul masalah?
Saat ini, OpenSID memberlakukan kode desa mulai dari kode provinsi (misal 6201022016)., namun hal tersesbut berpengaruh pada Kode Barang yang seharusnya 62.01.02.2016.01.2020 menjadi ganda. Alias angka berulang. (62.6201.620102.6201022016.01.2020)

<img width="607" alt="2020-12-13_23h22_52" src="https://user-images.githubusercontent.com/46939846/102017613-85900c00-3d9a-11eb-8d57-ca72ad165693.png">

### Seperti apa yang diharapkan?
Normal seperti Kode barang Seharusnya tanpa angka kode berulang.

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3832
