### ISSUE TITLE
Judul Dokumen UNDUH Data Suplemen Hurufnya Besar-Kecil

### ISSUE THREAD

**Issue by Zulkarnaimni** [OpenSID/OpenSID#3826]
### Bagaimana alurnya sampai muncul masalah?
![image](https://user-images.githubusercontent.com/64481641/102046208-6da5a000-3e0d-11eb-9ec6-45ef013cdbdf.png)

### Seperti apa yang diharapkan?
Bisa disamakan jenis atau tipe huruf

### Apa yang terjadi?
Supaya setelah diunduh tidak perlu lagi di ketik ulang

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.12 Pasca
| Versi PHP        | 7.4.13
| System operasi   |Win 64 Bit

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3828
