### ISSUE TITLE
[Kelompok] Tambahkan Penduduk Luar Desa pada Menu Kelompok

### ISSUE THREAD

**Issue by mizwaruddin** [OpenSID/OpenSID#3829]
### Bagaimana alurnya sampai muncul masalah?
Saat ini anggota kelompok hanya bisa ditambahkan dari penduduk desa setempat. Pada kenyatannya, anggota kelompok dapat berasal dari penduduk luar desa. Misal: anggota kelompok tani. Ketika lahan/sawah itu dibeli penduduk dari luar desa, maka secara otomatis orang tsb terdaftar sebagai anggota kelompok tani di blok sawah tersebut.

### Seperti apa yang diharapkan?
Anggota kelompok dapat ditambahkan dari penduduk luar desa.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
sertakan isian data yg diperlukan biar lebih jelas.

**Comment by mizwaruddin** [comment]
![kelompok](https://user-images.githubusercontent.com/39736008/104078650-d0922780-5251-11eb-959a-7455a735aed3.png)

**Comment by afa28** [comment]
ok

**Comment by usmanrahdi** [comment]
apakah fitur ini masih dikembangkan?

**Comment by mizwaruddin** [comment]
Masih, Bung.

**Comment by andifahruddinakas** [comment]
Duplicate issue https://github.com/OpenSID/OpenSID/issues/5250
