### ISSUE TITLE
[Database] Export Import Dari Excel Data Lokasi Tempat Tinggal ( Lat, Lng)

### ISSUE THREAD

**Issue by khiar-rara** [OpenSID/OpenSID#3830]
### Seperti apa yang diharapkan?
Bisa export import data Latitude Longitude tempat tinggal dari excel.

### Apa yang terjadi?
Kalau sudah menentukan posisi tempat tinggal kepala keluarga (Lat, Lng) melalui OpenSID, kemudian dapat diexport ke excel, kemudian lebih mudah untuk menambahkan data (Lat,Lng) anggota keluarga di excel, kemudian di import lagi data tersebut melalui OpenSID.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
> ### Seperti apa yang diharapkan?
> Bisa export import data Latitude Longitude tempat tinggal dari excel.
> 
> ### Apa yang terjadi?
> Kalau sudah menentukan posisi tempat tinggal kepala keluarga (Lat, Lng) melalui OpenSID, kemudian dapat diexport ke excel, kemudian lebih mudah untuk menambahkan data (Lat,Lng) anggota keluarga di excel, kemudian di import lagi data tersebut melalui OpenSID.
> 
> ### Informasi tambahan 
> 
> | Tanya            | Jawab
> | ---------------- | ---
> | Versi OpenSID    | 2.x
> | Versi PHP        | 
> | System operasi   |
> 

Cukup kepala keluarga yg di input data lokasinya, lokasi data anggota keliarga yg lain menyesuaikan dgn lokasi kepala keluarga.

**Comment by eddieridwan** [comment]
Mohon solusinya dibuat fleksibel, sehingga cara pengubahan/pemasukan banyak data sekaligus dapat dilakukan untuk kolom data penduduk mana saja. Salah satu cara adalah sbb:
1. Sediakan ekspor Excel hanya berisi kolom identitas penduduk: `id, NIK, nama, alamat, dusun, rw, rt`. `id` digunakan untuk menentukan data untuk diubah pada waktu impor. Kolom yg lain sekadar info bagi petugas yg mengisi kolom tambahan. Baris pertama berisi judul kolom yg `harus` menggunakan nama kolom ybs di tabel `tweb_penduduk`.
2. Excel tersebut bisa ditambahkan kolom data yg akan diubah, misalnya Lat, Lng. Baris pertama kolom2 yg ditambahkan `harus` menggunakan nama kolom persis seperti di tabel `tweb_penduduk` (misalnya 'lat, lng`).
3. Proses impor disesuaikan supaya bisa mengimpor data dengan jumlah kolom yg variabel, dan mengubah data penduduk berdasarkan `id`. Kolom yg diupdate hanya kolom yg ada di file impor dan hanya kalau ada nilai di kolom ybs.

**Comment by khiar-rara** [comment]
Yang diekspor ke excel cukup seluruh data ID, Nomor KK dan Latitude Longitudenya.

Kemudian diexcel, kalau data Lat Lng kepala keluarga sudah ada (yang sudah diinput melalui OpenSid), tinggal copy paste data Lat Lng kepala keluarga pada Nomor KK yang sama (anggota keluarga).

Kemudian data tersebut di import melalui OpenSid.

# maaf kalau membingungkan

**Comment by khiar-rara** [comment]
Atau kalau tidak tombol simpan pada input Lat Lng pada OpenSid berfungsi untuk menyimpan keseluruh Nomor KK yang bersangkutan

**Comment by afa28** [comment]
Klw tdk salah untuk alamat penduduk yg ada dlm 1 KK mengikuti alamat Kepala KKnya, klw penduduk tanpa KK baru menggunakan alamat penduduk tsb.

Jd cukup input alamat lengkap Kepala KK dan daftarkan menjadi 1 keluarga. Jd tdk lerlu di jnput 1 per 1 alamat penduduknya.

**Comment by khiar-rara** [comment]
Kalau untuk alamat rt/rw/dusun/jalan, saya setuju dengan anda pak afa28. Yang saya maksud titik koordinat lokasi tempat tinggalnya

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/OpenSID/pull/7596
