### ISSUE TITLE
Menambahkan Kategori Kawin tercatan dan belum tercata di edit / input biodata penduduk

### ISSUE THREAD

**Issue by kasipembts** [OpenSID/OpenSID#3831]
### Bagaimana alurnya sampai muncul masalah?
Ketika ingin mengedit data penduduk tidak bisa disimpan karena wajib mengisi tanggal perkawinan, sedangkan kami tidak tau / tidak memegang arsip perkawinannya. Jadi tidak bisa di input

### Seperti apa yang diharapkan?
Mungkin ditambahkan 2 kategori kawin / cerai hidup di kk
1. Kawin tercatat khusus yg sudah ada/menyetor akta kawin
2. Kawin belum tercatat jika penduduk belum memiliki akta perkawinan
3. Sama juga untuk cerai hidup.

### Apa yang terjadi?
Bisa lebih cepat dalam edit data penduduk karena saat ini saya tidak bisa menyimpan data penduduk

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.12
| Versi PHP        | 
| System operasi   |
![Screenshot_2020-12-16-16-08-13-12](https://user-images.githubusercontent.com/70615595/102322619-4c35e700-3fba-11eb-846a-c2f9b96e806f.jpg)
![Screenshot_2020-12-16-16-07-51-35](https://user-images.githubusercontent.com/70615595/102322629-4fc96e00-3fba-11eb-9d2b-ff9f9d5ff58e.jpg)

**Comment by benioke** [comment]
Liat di kartu keluarga di sistim pak..semua sudah sesuai

**Comment by kasipembts** [comment]
Mohon petunjuknya pak, karna saya tadi ingin memperbaiki data penduduk tidak bisa menyimpan karna harus memasukkan tgl perkawinan

**Comment by balongbesuk** [comment]
lebih baik required di bagian tanggal ini dihapus, cukup status perkawinan saja yang wajib diisi

**Comment by eddieridwan** [comment]
Ini permintaan dari @MUHAMMADRANGSEL, tetapi memang terlihat akan menyusahkan bagi desa yg belum memperoleh data tersebut. Sebenarnya data tersebut ada di kartu keluarga; tetapi mungkin juga tidak terisi di kartu keluarga.

**Comment by eddieridwan** [comment]
Ok, sudah diubah di `master` -- tgl perkawinan tidak lagi wajib diisi. Tapi tentu dianjurkan supaya perangkat desa terbiasa meminta kartu keluarga dan mengisi data yg ada di KK.

**Comment by balongbesuk** [comment]
Betul pak, sudah HARUS jadi kesadaran Operator Desa sendiri ketika ada berubahan di KK maka Operator lah yang wajib mengupdate data Penduduk pada Aplikasi, untuk sekarang bagi pengguna baru pastinya masih berkutat dengan KK yang lama yang tidak mencantumkan tanggal pernikahan (Prioritas Penggunaan Pengguna Desa baru yang masih baru input data penduduk di Opensid), terima kasih
