### ISSUE TITLE
Akun Web Desa Dorang di Hack Mohon Perbaikan

### ISSUE THREAD

**Issue by pemdesdorang** [OpenSID/OpenSID#3833]
### Bagaimana alurnya sampai muncul masalah?
Beberapa bulan memang tidak membuka web desa namun hari ini saat membuka web malah muncul tampilan dari hacker dan langsung mendowonload lagu fast furiuos

### Seperti apa yang diharapkan?
akun web desa dorang kembali normal karena akan digunakan untuk mengupload penyerapan dan realisasi dana desa 2020

### Apa yang terjadi?
akun web desa di hack oleh hacker

### Informasi tambahan 
 mohon diperbaiki secepatnya. terimakasih
| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
@pemdesdorang silakan ikuti petunjuk di https://github.com/OpenSID/OpenSID/wiki/Tanya-Jawab-Keamanan.

Kalau anda menggunakan layanan OpenDesa, bisa meminta bantuan OpenDesa melalui grup Telegram support. Bisa tanyakan di https://www.facebook.com/groups/OpenSID jika anda belum anggota grup itu. 

Issue tempat untuk melaporkan bug aplikasi atau permintaan perbaikan fitur. Bukan tempat melaporkan kena hack atau meminta bantuan lainnya. Untuk itu mohon gunakan forum FB https://www.facebook.com/groups/OpenSID.

Issue ini akan kami tutup.

**Comment by eddieridwan** [comment]
Kalau web desa anda http://dorang.desa.id/, ini menggunakan WordPress, bukan OpenSID.
Kalau yg dimaksud web di http://dorang.jepara.go.id/, itu kemungkinan besar dikelola oleh Diskominfo Kab Jepara. Sebaiknya hubungi mereka.
