### ISSUE TITLE
Tidak dapat meng-upload gambar/foto pada artikel

### ISSUE THREAD

**Issue by Zulkarnaimni** [OpenSID/OpenSID#3835]
### Bagaimana alurnya sampai muncul masalah?
Tidak dapat meng-upload gambar/foto pada artikel, saat meng-upload hanya muncul pesan "Processing" dan tanda tunggu upload hanya berputar-putar saja sedangkan gambar tidak ter upload.
![image](https://user-images.githubusercontent.com/64481641/102614821-7c6eb880-4167-11eb-89a2-b388f192bbdb.png)

### Seperti apa yang diharapkan?
Dapat melakukan upload foto/atau gambar

### Apa yang terjadi?
Sudah melakukan uji coba pada system Demo https://demo.opensid.my.id/web/form, hasilnya sama.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.12 Pasca
| Versi PHP        | 
| System operasi   |

**Comment by balongbesuk** [comment]
itu sy bs upload ttd dokter di demo

**Comment by balongbesuk** [comment]
![sdsada](https://user-images.githubusercontent.com/35319600/102620952-6f56c700-4171-11eb-9e34-6a8b2038f12b.jpg)

**Comment by ariandii** [comment]
Saya pun bisa upload, lancar tanpa hambatan.

<img width="960" alt="2020-12-19_14h52_41" src="https://user-images.githubusercontent.com/46939846/102684298-daec7300-4209-11eb-85d6-1fbd154b8f10.png">

**Comment by ariandii** [comment]
Berikut videonya:

https://www.facebook.com/ariandi/videos/10218775826362916/

**Comment by Zulkarnaimni** [comment]
saya uji kembali barusan di dua browser yang berbada, akan tetapi belum bisa padahal file ukurannya sudah kecil cuma 569 kb

**Comment by ariandii** [comment]
Saya coba di Web Demo https://demo.opensid.my.id juga Lancar jaya. Berikut videonya:

https://www.facebook.com/ariandi/videos/10218775980726775

**Comment by mizwaruddin** [comment]
@afa28 upload gambar di web demo berjalan normal. Sdh dilakukan beberapa jenis file gambar.
