### ISSUE TITLE
[BUG] - Saat ini feed rss tidak terender sesuai format xml

### ISSUE THREAD

**Issue by agungsugiarto** [OpenSID/OpenSID#3837]
### Bagaimana alurnya sampai muncul masalah?
Buka feed https://demo.opensid.my.id/feed url, saat ini feed rss tidak terender sesuai format xml

### Seperti apa yang diharapkan?
Feed rss tergenerate sesuai format xml

### Apa yang terjadi?
Feed rss terformat sebagai text biasa

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3834 .

Perhatikan bahwa di rss aggregator yg saya gunakan di Google, sebelumnya sudah dikenal sebagai RSS dan tampil benar.

**Comment by agungsugiarto** [comment]
> Sdh dicommit ke `master` melalui PR #3834 .
> 
> Perhatikan bahwa di rss aggregator yg saya gunakan di Google, sebelumnya sudah dikenal sebagai RSS dan tampil benar.

Ini adalah demo di branch [premium](http://beta.opensid.my.id/feed), akan terjadi error jika format content-type tidak sesuai dengan xml
