### ISSUE TITLE
Boleh Kontirbusi Design UI nggak?

### ISSUE THREAD

**Issue by iqbalhood** [OpenSID/OpenSID#3838]
### Bagaimana alurnya sampai muncul masalah?
Boleh Kontirbusi Design UI nggak?

### Seperti apa yang diharapkan?
Desain UI yang lebih baik

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by balongbesuk** [comment]
wah ini lg dibutuhkan front end, :+1:

**Comment by eddieridwan** [comment]
@iqbalhood tentu boleh. Jelaskan saja desain yg ingin anda terapkan di issue ini. Kemudian terapkan mengikuti petunjuk di https://github.com/OpenSID/OpenSID/wiki/Cara-Ikut-Mengembangkan-OpenSID. Setelah itu ikut diskusi di forum teknis di Slack dengan programmer lainnya.

**Comment by afa28** [comment]
Silahkan, bisa baca [https://github.com/OpenSID/OpenSID/wiki/Cara-Ikut-Mengembangkan-OpenSID](https://github.com/OpenSID/OpenSID/wiki/Cara-Ikut-Mengembangkan-OpenSID)
