### ISSUE TITLE
Dropdown menu tidak muncul di thema natra

### ISSUE THREAD

**Issue by ilamazuliaf** [OpenSID/OpenSID#3841]
### Bagaimana alurnya sampai muncul masalah?
Saat mengakses url [Status IDM](https://tarogan.com/first/status_idm) , dropdown menu tidak muncul pada thema natra

### Seperti apa yang diharapkan?
dropdown menu muncul kembali

### Apa yang terjadi?
dropdown menu tidak muncul sehinggal harus kembali ke home agar muncul

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.12-premium-pasca
| Versi PHP        | 
| System operasi   |

**Comment by mizwaruddin** [comment]
@afa28 Karena tidak ada submebnu, maka dropdown tidak berfungsi. Bisa ditutup karena IDM tdk membutuhkan submenu.

**Comment by afa28** [comment]
> @afa28 Karena tidak ada submebnu, maka dropdown tidak berfungsi. Bisa ditutup karena IDM tdk membutuhkan submenu.

Harusnya idm bisa disimpan baik di menu utama atau di submenu. Nanti sy coba cek ulang issue ini.
