### ISSUE TITLE
Pengaturan Aplikasi

### ISSUE THREAD

**Issue by elkautzar** [OpenSID/OpenSID#3843]
### Bagaimana alurnya sampai muncul masalah?
Saat ini pengaturan aplikasi yg ada di OpenSID digabung dalam 1 form, sehingga pengguna bisa kebingunan pengaturan2 tsb diterapkan di modul atau bagian mana.

### Seperti apa yang diharapkan?
Pengaturan aplikasi di pisahkan perbagian (dikelompokkan) agar lebih jelas peruntukannya.

### Apa yang terjadi?
Lebih mudah di pahami.

### Informasi tambahan 
Contoh : pengaturan mengenai halaman web (sebagian sdah dipisah di adminweb>setting), layanan_mandiri, dll. Bisa di sediakan di satu lokasi saja, yakni di pengaturan>aplikasi tp dipisah perbagian.

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
Duplicate issue #4007
