### ISSUE TITLE
Penggunaan titik tidak berfungsi pada Kode Klasifikasi surat keluar

### ISSUE THREAD

**Issue by Gunturwijay** [OpenSID/OpenSID#3845]
### Bagaimana alurnya sampai muncul masalah?
Ketika menggunakan Kode Klasifikasi surat yang mempunyai titik, hasilnya setelah melakukan simpan, titiknya menjadi hilang
![image](https://user-images.githubusercontent.com/40741591/102863429-29e21480-4465-11eb-9a97-df7e7188e81b.png)

### Seperti apa yang diharapkan?
Seharusnya titik pada nomor klasifikasi tersebut muncul
![image](https://user-images.githubusercontent.com/40741591/102863537-4c742d80-4465-11eb-8f98-cacf8697fd50.png)

### Apa yang terjadi?
Tidak sesuai dengan Kode Klasifikasi yang seharusnya

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.12-pasca dan 20.12-premium-pasca
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3859
