### ISSUE TITLE
File Ekapor Penduduk OpenDK Tidak Dapat Diimpor ke OpenDK

### ISSUE THREAD

**Issue by mizwaruddin** [OpenSID/OpenSID#3846]
### Bagaimana alurnya sampai muncul masalah?
File ekspor penduduk ke OpenDK tidak bisa diimpor ke OpenDK

### Seperti apa yang diharapkan?
File ekspor penduduk OpenDK dapat diimpor ke OpenDK.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by agungsugiarto** [comment]
Coba lewat demo pak apakah sama menemukan error ?

https://demo.opensid.my.id/database
https://demo.opendk.my.id/data/penduduk/import

**Comment by ilamazuliaf** [comment]
Saya pakai versi non premium bisa, sedangkan versi premium masih bentuk excel bukan zip. https://kec.kambinganbarat.com

**Comment by mizwaruddin** [comment]
Dicoba tambah impor penduduk desa lain lagi.
