### ISSUE TITLE
Impor Data Kependudukan Gagal 

### ISSUE THREAD

**Issue by aseppakot** [OpenSID/OpenSID#3847]
Letak Baris Data Gagal :
4 (nama/nik/dusun/rt/rw kosong)
5 (nama/nik/dusun/rt/rw kosong)
6 (nama/nik/dusun/rt/rw kosong)
7 (nama/nik/dusun/rt/rw kosong)
8 (nama/nik/dusun/rt/rw kosong)
9 (nama/nik/dusun/rt/rw kosong)
10 (nama/nik/dusun/rt/rw kosong)

[https://drive.google.com/file/d/1Nr-BG_f6RRqw8pFHGrrxmn_1J1miwyck/view?usp=sharing](url)

**Comment by ianskids** [comment]
Silakan update ke OpenSID 20.12-pasca terbaru

**Comment by ianskids** [comment]
> Letak Baris Data Gagal :
> 4 (nama/nik/dusun/rt/rw kosong)
> 5 (nama/nik/dusun/rt/rw kosong)
> 6 (nama/nik/dusun/rt/rw kosong)
> 7 (nama/nik/dusun/rt/rw kosong)
> 8 (nama/nik/dusun/rt/rw kosong)
> 9 (nama/nik/dusun/rt/rw kosong)
> 10 (nama/nik/dusun/rt/rw kosong)
> 
> [https://drive.google.com/file/d/1Nr-BG_f6RRqw8pFHGrrxmn_1J1miwyck/view?usp=sharing](url)

Apakah sudah di update ke versi terbaru?
Jika belum Silakan update ke OpenSID 20.12-pasca terbaru

**Comment by aseppakot** [comment]
Di OpenSID 20.12-pasca lemot banget, masuk juga susah ke dashboard

**Comment by mranca** [comment]
kalau seperti di atas kasusnya sebelum data di import semua usahakan harus terisi semua

**Comment by ianskids** [comment]
> > Letak Baris Data Gagal :
> > 4 (nama/nik/dusun/rt/rw kosong)
> > 5 (nama/nik/dusun/rt/rw kosong)
> > 6 (nama/nik/dusun/rt/rw kosong)
> > 7 (nama/nik/dusun/rt/rw kosong)
> > 8 (nama/nik/dusun/rt/rw kosong)
> > 9 (nama/nik/dusun/rt/rw kosong)
> > 10 (nama/nik/dusun/rt/rw kosong)
> > [https://drive.google.com/file/d/1Nr-BG_f6RRqw8pFHGrrxmn_1J1miwyck/view?usp=sharing](url)
> 
> Apakah sudah di update ke versi terbaru?
> Jika belum Silakan update ke OpenSID 20.12-pasca terbaru

Dan Gunakan Format Template terbaru

**Comment by mizwaruddin** [comment]
@afa28 sdh tdk terjadi error.

**Comment by afa28** [comment]
Silahkan reopon issue ini jika masih mengalami masalah.
