### ISSUE TITLE
Kode Barang belum Lengkap

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#3848]
### Bagaimana alurnya sampai muncul masalah?
Saat input barang inventaris, pada Kolom Kode Barang masih menggunakan kode desa.

<img width="716" alt="2020-12-23_11h59_12" src="https://user-images.githubusercontent.com/46939846/102961207-52761700-4516-11eb-9adc-fcafb4a441a1.png">

Dan setelah diinput, pada tabel Daftar Inventaris juga masih menggunakan kode desa pada kolom "Kode Barang".

<img width="474" alt="2020-12-23_11h56_35" src="https://user-images.githubusercontent.com/46939846/102961102-0d51e500-4516-11eb-8422-fa92250f9916.png">

### Seperti apa yang diharapkan?
Tercantum Kode Barang lengkap dengan Nomor Register.

### Apa yang terjadi?
Supaya tidak kembar semua kode barang yang tercantum di tabel.

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3903
