### ISSUE TITLE
Kode Golongan Tidak Sesuai

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#3850]
### Bagaimana alurnya sampai muncul masalah?
Saat input barang Inventaris, terdapat perbedaan Kode Golongan di semua Kategori Inventaris.
Pada tabel Kodefikasi Aset Desa dari Kementerian, urutannya seperti di bawah ini:
<img width="540" alt="2020-12-23_12h42_05" src="https://user-images.githubusercontent.com/46939846/102963714-6755a900-451c-11eb-908c-aa3ee6c9c61e.png">

[PEDUM-KODEFIKASI-ASET-DESA-FINAL.pdf](https://github.com/OpenSID/OpenSID/files/5733473/PEDUM-KODEFIKASI-ASET-DESA-FINAL.pdf)

Namun pada Kode Golongan di OpenSID, Nomor Nurut 1 adalah Tanah, yang seharusnya jika berpedoman pada File di atas, Tanah termasuk Kode Golongan nomor 2.

<img width="656" alt="2020-12-23_12h43_46" src="https://user-images.githubusercontent.com/46939846/102963859-c87d7c80-451c-11eb-8730-9fbc5145fb2a.png">

### Seperti apa yang diharapkan?
Penyesuaian Kode Golongan seperti seharusnya.

### Apa yang terjadi?
Agar tidak terjadi kesalahan Pengkodean pada barang.

**Comment by afa28** [comment]
Pak @eddieridwan, untuk modul inventari apa diawal pembuatan menggunakan referensi https://github.com/OpenSID/OpenSID/files/5733473/PEDUM-KODEFIKASI-ASET-DESA-FINAL.pdf

kalau iya, berarti kode golongan di inventaris perlu disesuaikan ulang.

**Comment by eddieridwan** [comment]
@afa28 perlu disesuaikan dengan yg digunakan di Sipades (http://sipades.konsolidasi.info/26AsetDesaBinaPemdeskemendagriKm19_5u6D1r3kt0r4tF4s1lIt4s1K3U4ngAnd4nAS

Peraturan dan pedoman terkait ada di grup Tester, terlampir berikut:

[permendagri no 1 th 2016 pengelolaan aset desa.pdf](https://github.com/OpenSID/OpenSID/files/6942983/permendagri.no.1.th.2016.pengelolaan.aset.desa.pdf)
[SE_Inventarisasi Aset Desa_2021.pdf](https://github.com/OpenSID/OpenSID/files/6942984/SE_Inventarisasi.Aset.Desa_2021.pdf)
3tD3s4.php). 
[Draft Panduan Penggunaan Aplikasi Sipades.pdf](https://github.com/OpenSID/OpenSID/files/6942979/Draft.Panduan.Penggunaan.Aplikasi.Sipades.pdf)
[pedum kodefikasi aset desa.pdf](https://github.com/OpenSID/OpenSID/files/6942982/pedum.kodefikasi.aset.desa.pdf)

Tinggal di verifikasi bahwa yg dilampirkan @ariandii adalah yg final. 

Jika perlu akses ke aplikasi Sipades, dapat berhubungan dengan Yayan dari Kalibuaya.

**Comment by afa28** [comment]
> @afa28 perlu disesuaikan dengan yg digunakan di Sipades (http://sipades.konsolidasi.info/26AsetDesaBinaPemdeskemendagriKm19_5u6D1r3kt0r4tF4s1lIt4s1K3U4ngAnd4nAS
> 3tD3s4.php).
> 
> Peraturan dan pedoman terkait ada di grup Tester, terlampir berikut:
> 
> [permendagri no 1 th 2016 pengelolaan aset desa.pdf](https://github.com/OpenSID/OpenSID/files/6942983/permendagri.no.1.th.2016.pengelolaan.aset.desa.pdf)
> [SE_Inventarisasi Aset Desa_2021.pdf](https://github.com/OpenSID/OpenSID/files/6942984/SE_Inventarisasi.Aset.Desa_2021.pdf)
> [Draft Panduan Penggunaan Aplikasi Sipades.pdf](https://github.com/OpenSID/OpenSID/files/6942979/Draft.Panduan.Penggunaan.Aplikasi.Sipades.pdf)
> [pedum kodefikasi aset desa.pdf](https://github.com/OpenSID/OpenSID/files/6942982/pedum.kodefikasi.aset.desa.pdf)
> 
> Tinggal di verifikasi bahwa yg dilampirkan @ariandii adalah yg final.
> 
> Jika perlu akses ke aplikasi Sipades, dapat berhubungan dengan Yayan dari Kalibuaya.

Sudah sesuai pak @eddieridwan, untuk yg 1. persediaan di OpenSID yg tdk ada. Jd PR yg sy buat untuk menyesuaikan golongannya saja.

**Comment by afa28** [comment]
Sudah digabung ke `FITUR PREMIUM`
