### ISSUE TITLE
inventaris tanah tidak bisa di tambahkan setelah penginputan ke dua

### ISSUE THREAD

**Issue by mranca** [OpenSID/OpenSID#3851]
### Bagaimana alurnya sampai muncul masalah?
untuk masalah mengenai inventaris tanah tidak bisa di tambahkan setelah penginputan ke dua sudah berjalan sesuai dengan semestinya di opensid versi 20.12 pasca ( sudah normal ) tidak terjadi bug lagi. dan yang perlu di perbaiki mengenai urutan aset pada saat di cetak 
### Seperti apa yang diharapkan?
![Opera Snapshot_2020-12-26_071549_localhost](https://user-images.githubusercontent.com/76085245/103173085-606bc500-4893-11eb-9fa7-bb650f378676.png)

### Apa yang terjadi?
saat proses cetak maka nomor registrasi di 4 angka terakhir tidak beraturan, dan harusnya itu harus berurut mulai dari angka 1,2, dan seterusnya 

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by agungsugiarto** [comment]
Pak @mranca, mohon dilengkapi issuenya sesuai [panduan](https://github.com/OpenSID/OpenSID/wiki/Pengelolaan-Masalah-dan-Permintaan-Perbaikan-SID)
Untuk membuat suatu issue lebih tinggi kemungkinannya dipilih, lakukan hal-hal berikut:

1. Tulis issuenya sejelas mungkin. Judul issue perlu menjelaskan masalah secara ringkas. Edit issuenya supaya berisi hanya satu fitur. Issue yang berisi berbagai permintaan akan dianggap terlalu rumit dan cenderung dihindari oleh pegiat.
1. Jelaskan secara detail aturan-aturan yang berlaku untuk fitur yang diinginkan. Ingat programmer yang mengerjakan issue umumnya bukan perangkat desa sehingga anda perlu menjelaskan segala rinci -- jangan berasumsi programmer 'harusnya sudah mengerti'.
1. Lampirkan gambar konsep apa yang diinginkan (misalnya tata letak laporan). Lebih banyak detail maka akan lebih mudah untuk pegiat menerapkan usulan anda.
1. Ceritakan mengapa issue itu penting bagi desa anda dan desa lainnya. Pegiat biasanya memilih issue yang akan bermanfaat bagi banyak desa.
1. Di laman issue, klik jempol untuk menunjukkan anda menganggap issue itu penting. Issue dengan banyak jempol akan dilihat oleh pegiat sebagai issue yang mendapat banyak perhatian dari pengguna.

**Comment by ariandii** [comment]
Aset di atas jika diperhatikan sudah urut sesuai Urutan Registrasi yang berdasar pada Tahun Perolehan.

**Comment by eddieridwan** [comment]
Seperti dijelaskan bung @ariandii , aset diurut berdasarkan Kode Barang | Registrasi, yaitu nomor Registrasi terurut untuk masing2 Kode Barang (bukan nomor Registrasi sendiri).

Karena bukan error, issue ini ditutup. Silakan buka lagi kalau ada informasi tambahan yg memerlukan sistem diperbaiki.
