### ISSUE TITLE
Tambahkan Pilihan Menu Laporan Kependudukan di Menu Artikel

### ISSUE THREAD

**Issue by muhtar-coder** [OpenSID/OpenSID#3855]
### Bagaimana alurnya sampai muncul masalah?
- Saat ini ketika ingin membuat laporan penduduk bulanan harus mencetak dari halaman admin saja
- berita perkembangan penduduk bulanan sulit di buat karena harus membuat file gambar terlebih dahulu.

### Seperti apa yang diharapkan?
1.Laporan penduduk bisa mudah di buat,baik berupa halaman berita desa atau artikel
2.Selain bisa berupa artikel berita data laporan penduduk agar bisa di cetak pada halaman berita tersebut.
3.Pelaporan menjadi lebih mudah dengan adanya menu tersebut.

![image](https://user-images.githubusercontent.com/55665526/103138282-88c4b980-4703-11eb-99b3-9c0a0dd5f988.png)
![Laporan_Bulanan](https://user-images.githubusercontent.com/55665526/103138296-a134d400-4703-11eb-9e82-fae720e05089.png)

### Apa yang terjadi?
Tentunya fitur di openSID lebih Mantap

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.12 Premium
| Versi PHP        | 
| System operasi   |

**Comment by fusionid** [comment]
![bulanan1](https://user-images.githubusercontent.com/10391199/103352620-415e7480-4ad9-11eb-8d70-51280b6717b9.PNG)

![bulanan2](https://user-images.githubusercontent.com/10391199/103352626-44f1fb80-4ad9-11eb-8e39-a78d9d9dd9ad.PNG)

![bulanan3](https://user-images.githubusercontent.com/10391199/103352632-48858280-4ad9-11eb-88f3-a0a7db5756cc.PNG)

**Comment by muhtar-coder** [comment]
Mantapppp.

Pada tanggal Rab, 30 Des 2020 19.58, zeppyshiddiq <notifications@github.com>
menulis:
