### ISSUE TITLE
Pada daerah yang sebutan desanya "nagari", Tanda Tangan  pada cetak KK nya masih Kepala Nagari

### ISSUE THREAD

**Issue by lidramardius** [OpenSID/OpenSID#3863]
### Bagaimana alurnya sampai muncul masalah?
Pada daerah yang sebutan Desanya "Nagari" pada cetak KK penandatangannya masih Kepala Nagari, 

### Seperti apa yang diharapkan?
Seharusnya " Wali Nagari"

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.12
| Versi PHP        | 
| System operasi   |

**Comment by ianskids** [comment]
> ### Bagaimana alurnya sampai muncul masalah?
> Pada daerah yang sebutan Desanya "Nagari" pada cetak KK penandatangannya masih Kepala Nagari,
> 
> ### Seperti apa yang diharapkan?
> Seharusnya " Wali Nagari"
> 
> ### Apa yang terjadi?
> ### Informasi tambahan
> Tanya	Jawab
> Versi OpenSID	20.12
> Versi PHP	
> System operasi

@idramardius apakah sudah melakukan perubahan jabatan pada menu Pemerintahan?

**Comment by lidramardius** [comment]
sudah mas..

setelah dilihat, format "Kepala" nya dari kodingan..

**Comment by lidramardius** [comment]
![Uploading IMG_20201223_141757.jpg…]()

**Comment by lidramardius** [comment]
> sudah mas..
> 
> setelah dilihat, format "Kepala" nya dari kodingan..

**Comment by eddieridwan** [comment]
Sdh dicommit ke `rilis-dev`
