### ISSUE TITLE
Chacklist pada Manual Input Anggaran dan Realisasi APBDes Tidak Berfungsi

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#3866]
### Bagaimana alurnya sampai muncul masalah?
Pada Manual Input Anggaran dan Realisasi APBDes menu Belanja dan Pembiayaan tidak berfungsi.

<img width="960" alt="2020-12-30_00h54_15" src="https://user-images.githubusercontent.com/46939846/103303950-ea559280-4a39-11eb-9228-dfb3bdab19fd.png">

### Seperti apa yang diharapkan?
Berfungsi sebagaimana mestinya.

**Comment by egodasa** [comment]
Saya akan coba perbaiki issue ini

**Comment by afa28** [comment]
> Saya akan coba perbaiki issue ini

silahkan mas @egodasa

**Comment by afa28** [comment]
Sudah di `master`.
