### ISSUE TITLE
Model Minimize Menu Administrasi Umum tidak mengikuti standar seperti menu yang lain di Opensid

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#3868]
### Bagaimana alurnya sampai muncul masalah?
buka administrasi desa > administrasi umum tekan tombol minimize

### Seperti apa yang diharapkan?
mengikuti standart minimize menu lain seperti menu kelompok, statistik penduduk, pertanahan, pengaturan peta, sms, inventaris, laporan manual, artikel, menu dll,

![asdasdasd](https://user-images.githubusercontent.com/35319600/103329016-8d83c780-4a8d-11eb-9879-44aa87a35dc2.jpg)

### Apa yang terjadi?
menu minimize model hamburger perlu di seragamkan dengan menu standart opensid lainnya
![asdasdasd](https://user-images.githubusercontent.com/35319600/103329053-ae4c1d00-4a8d-11eb-9000-5dc18862a407.jpg)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
@ariandii Kebutuhan yg berbeda. Tujuan icon di Buku Administrasi Umum adalah untuk menghilang ke kiri, supaya tampilan data bisa lebih lebar. Ini bermanfaat di Buku Administrasi Umum di mana ada daftar data yg menampilkan banyak kolom.

Di tempat lain adalah untuk menutup kelompok menu secara vertikal. 

Mungkin untuk membedakan bisa mengganti ikon menjadi panah '<' dan '>' untuk menunjukkan buka/tutup ke kiri/kanan. Pola ini banyak ditemukan di tampilan web (termasuk menu navigasi utama).

Alternatif lain adalah memindahkan submenu Buku Administrasi Umum ke menu navigasi utama. Saat ini ada dua tingkat, dan mungkin bisa dimekarkan menjadi tiga tingkat submenu. Tapi kontranya, adalah menunya bisa menjadi panjang sekali.

**Comment by ariandii** [comment]
@eddieridwan  siap pak

**Comment by afa28** [comment]
Mas @agungsugiarto

**Comment by afa28** [comment]
Setelah buku administrasi rampung, nantinya tampilan akan di sesuaikan ulang agar lebih menarik.
