### ISSUE TITLE
Administrasi lainnyadatabase error 500

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#3869]
### Bagaimana alurnya sampai muncul masalah?
buka buku administrasi desa > administrasi lainnya

### Seperti apa yang diharapkan?
tampilan dalam tahap pengembangan seperti menu administasi desa yang belum dikembangkan 

### Apa yang terjadi?
mengalami error 500

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master`.
