### ISSUE TITLE
Adminitrasi Umum Error 500

### ISSUE THREAD

**Issue by kasipembts** [OpenSID/OpenSID#3870]
### Bagaimana alurnya sampai muncul masalah?
Ketika ingin menambah peraturan desa, sk perbekel dan yg lainnya muncul error 500

### Seperti apa yang diharapkan?

agar tidak lagi muncul error 500
### Informasi tambahan 
![image](https://user-images.githubusercontent.com/70615595/103333319-26234300-4aa0-11eb-911f-13a8a260d945.png)
![image](https://user-images.githubusercontent.com/70615595/103333404-78646400-4aa0-11eb-972b-ef9a09ab4771.png)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.12 pasca
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master`.
