### ISSUE TITLE
Gagal Edit Menu Statis

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#3873]
### Bagaimana alurnya sampai muncul masalah?
Saat akan edit menu statis, pada kolom Link muncul tulisan "Kolom ini diperlukan."
Padahal kolom link tersebut sudah dipilih.

<img width="750" alt="2020-12-31_09h03_10" src="https://user-images.githubusercontent.com/46939846/103390559-a3ee5980-4b47-11eb-9666-46c26de2ae5f.png">

### Seperti apa yang diharapkan?
Berjalan semestinya.

**Comment by eddieridwan** [comment]
@ariandii, saya cek di https://demo.opensid.my.id. Normal saja. Coba clear cache. Tutup/buka browser.

**Comment by eddieridwan** [comment]
Ok, rupanya untuk kasus ubah. Untuk baru tidak bermasalah.
Untuk mengakali pada waktu ubah, klik dulu Jenis Link, baru isi Link.

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master`
