### ISSUE TITLE
[Layanan Mandiri] Sembunyikan Dokumen Persyaratan Surat Jika syarat surat tidak ada / tidak diperlukan

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#3875]
### Bagaimana alurnya sampai muncul masalah?
layanan mandiri > permohonan surat

### Seperti apa yang diharapkan?
ketika setting surat tidak memerlukan syarat pada layanan mandiri syarat surat dan dokumen yang tersedia disembunyikan

### Apa yang terjadi?
muncul "Tidak ditemukan data yang sesuai" sehingga ada kemungkinan pengguna layanan akan bingung data apa yang dimaksud

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
Issue berkaitan dengan layanan mandiri di lanjutkan setelah issue PR https://github.com/OpenSID/premium/pull/47 selesai.

**Comment by eddieridwan** [comment]
Sdh dicommit ke `rilis-dev`.

@balongbesuk walaupun sepertinya seharusnya minimal pemohon harus menunjuikkan KTP sebagai bukti diri. Situasi/surat apa yg tidak memerlukan syarat dokumen kelengkapan apapun?

**Comment by balongbesuk** [comment]
> 
> 
> Sdh dicommit ke `rilis-dev`.
> 
> @balongbesuk walaupun sepertinya seharusnya minimal pemohon harus menunjuikkan KTP sebagai bukti diri. Situasi/surat apa yg tidak memerlukan syarat dokumen kelengkapan apapun?

Anjungan tidak membutuhkan syarat surat karena syarat surat sudah dibawa di lokasi / syarat surat sudah di cantumkan pada persyaratan pengambilan surat ( hardcopy )

**Comment by eddieridwan** [comment]
@balongbesuk apakah semua desa menggunakan ketentuan tersebut (adanya hardcopy persyaratan pengambilan surat)? Atau sebaiknya ada peringatan di anjungan pada waktu selesai mengisi permohonan surat?

**Comment by balongbesuk** [comment]
warga bisa juga cukup menunjukkan KTP, untuk berkas memang perlu karena dipakai untuk lampiran pengajuan ke tingkat kecamatan / kabupaten, (contoh permohonan KK baru / Perubahan KK wajib fc bukti pendukung perubahan KKny)

untuk ketentuan tidak ada pak inisiatif saya sendiri, agar anjungan lebih dapat digunakan secara optimal di anjungan desa tidak mungkin / tidak dimungkinkan mengupload syarat surat karena tidak ada scan / camera, akhirnya kita arahkan warga menggunakan hp jadi anjungan mubazir, karena di HP juga bisa mengajukan permohonan surat tanpa perlu ke anjungan desa,

saya coba mematikan fitur upload syarat permohonan surat tersebut agar nanti penggunaan anjungan lebih optimal dan syarat surat sementara saya minta hardcopy syarat surat / agar dibawa saat pengambilan surat saja,

ketika saya matikan semua ternyata masih muncul kolom syarat permohonan surat, maka issue ini saya buat,

**Comment by eddieridwan** [comment]
@balongbesuk Di anjungan sudah ada pilihan 'Bawa Secara Fisiik' untuk setiap syarat. Jadi sama sekali tidak harus diunggah. Cukup pilih opsi itu. Ini ada di versi Premium v20.12-premium dan akan masuk di Rilis Umum v21.07 (bulan Juli). Kalau tidak sabar tentunya bisa berlangganan Premium. Sebagai pengguna yg sdh lama sekali, seyogyanya desa anda ikut juga berlangganan.

**Comment by eddieridwan** [comment]
Hmmm.... sepertinya issue ini timbul karena @balongbesuk tidak menggunakan rilis Premium. @afa28 jadi kita telah menambah fitur yg sepertinya tidak perlu. Lain kali kita perlu lebih rinci menanyakan alasan diperlukannya suatu fitur.

**Comment by balongbesuk** [comment]
issue sejak desember 2020 pak, belum sempat update, belum bisa memasukkan anggaran karena anggaran di fokuskan pengnanan covid19, 😄
