### ISSUE TITLE
[Layanan Mandiri] Tambahkan menu "shortcut" pengaturan / informasi untuk pengaturan surat layanan mandiri dan syarat surat

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#3876]
### Bagaimana alurnya sampai muncul masalah?
layanan mandiri > pengaturan

### Seperti apa yang diharapkan?
ada "shortcut" pengaturan / informasi untuk mengatur surat pada layanan mandiri dan daftar syarat surat dimana

### Apa yang terjadi?
pengguna baru (seperti saya) sempat bingung mencari pengaturan surat yang akan ditampilkan dilayanan mandiri tersebut ada dimana, karena di layanan mandiri juga ada menu pengaturan tetapi tidak ada yang mengatur surat ataupun syarat surat,

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
![123344](https://user-images.githubusercontent.com/57283157/104950346-15a51f00-59f3-11eb-9b29-4ead8eb326ba.JPG)

Apa semacam ini???

**Comment by balongbesuk** [comment]
![Untitled](https://user-images.githubusercontent.com/35319600/104980238-b2d67680-5a38-11eb-81b6-2f5665b5c470.jpg)

**Comment by andifahruddinakas** [comment]
Agar tidak duplikasi, pindahkan pengaturan yg berkaitan dengan layanan mandiri ke modul layanan mandiri.

**Comment by FirlianiF** [comment]
noted mas
