### ISSUE TITLE
masa berlaku surat pada permohonan surat mengalami bug?

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#3878]
### Bagaimana alurnya sampai muncul masalah?
periksa permohonan surat > lihat isian berlaku surat

### Seperti apa yang diharapkan?
sesuai pengaturan masa berlaku surat

### Apa yang terjadi?
isian berlaku surat tidak berubah / tetap hari ini 

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by balongbesuk** [comment]
![Uploading Screenshot_20210110-130506_Chrome.jpg…]()

Masih bug

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3939
