### ISSUE TITLE
Notifikasi yang sekarang menjalakan query setiap 5 detik sekali

### ISSUE THREAD

**Issue by agungsugiarto** [OpenSID/OpenSID#3881]
### Bagaimana alurnya sampai muncul masalah?
Notifikasi yang sekarang menjalakan query setiap 5 detik sekali, menurut saya ini bukan praktik yg bagus karena membebani dari sisi server.

### Seperti apa yang diharapkan?
Sederhakan untuk proses menampilkan notifkasi

### Apa yang terjadi?
Query untuk mendapatkan notifikasi dijalankan setiap 5 detik

### Informasi tambahan 
![image](https://user-images.githubusercontent.com/10989147/103454790-f4b5ac00-4d19-11eb-9f64-8bff72410573.png)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | OpenSID 21.01-pasca
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sdh dicommit ke `rilis-dev` melalui PR #3882
