### ISSUE TITLE
Bagan Organisasi tidak tampil pada menu statis di thema natra

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#3883]
### Bagaimana alurnya sampai muncul masalah?
Ketika mau menampilkan Bagan Organisasi di halaman web pada menu statis di thema natra hasilnya blank
![image](https://user-images.githubusercontent.com/25834335/103456903-25531100-4d2d-11eb-93ee-3b9c8e462a80.png)
**hasilnya di thema natra blank**
![image](https://user-images.githubusercontent.com/25834335/103456926-62b79e80-4d2d-11eb-9704-058a2b7b6398.png)
**sedangkan di thema klasik muncul**
![image](https://user-images.githubusercontent.com/25834335/103456942-7bc04f80-4d2d-11eb-9b55-e957db073b17.png)

### Seperti apa yang diharapkan?
menampilkan bagan organisasi bisa tampil di thema natra

### Apa yang terjadi?
Bagan Organisasi tidak bisa tampil

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 20.01 pasca
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
Sy coba tampilkan di tema natra aman sja.
![12222222](https://user-images.githubusercontent.com/57283157/103738737-18813680-5027-11eb-8875-a04bc6ef6261.JPG)

**Comment by mizwaruddin** [comment]
@MUHAMMADRANGSEL  Apakah masih bermasalah?

**Comment by MUHAMMADRANGSEL** [comment]
sdh bisa
