### ISSUE TITLE
Fitur Pencarian di Data Suplemen tidak berfungsi dengan baik dan hasilnya blank

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#3884]
### Bagaimana alurnya sampai muncul masalah?
Ketika ingin mencari data masyarakat yang sudah didata di Data Suplemen==>Daftar Terdata Suplemen tidak berfungsi dengan baik yaitu hasilnya blank
![image](https://user-images.githubusercontent.com/25834335/103457134-06557e80-4d2f-11eb-9a04-3763a82660e0.png)
supaya datanya muncul harus kembali ke data suplemen==> klik nama data, baru bisa muncul
![dd](https://user-images.githubusercontent.com/25834335/103457171-56ccdc00-4d2f-11eb-937e-06dc1ed59a07.jpg)

### Seperti apa yang diharapkan?
Fitur Pencarian di Data suplemen berfungsi dengan baik seperti di pencarian lainnya

### Apa yang terjadi?
pencarian data lama

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by Nurhidayat29** [comment]
saya coba di demo tidak ada masalah bung

**Comment by MUHAMMADRANGSEL** [comment]
Barusan saya coba hasilnya blank juga di demo

Pada tanggal Min, 3 Jan 2021 02.20, Nur Hidayat <notifications@github.com>
menulis:

**Comment by eddieridwan** [comment]
Di demo barusan, normal. Kalau masih masalah di demo, harap lampirkan tampakan layar yg bermasalah. Data apa yg dicari?

![cari-suplemen](https://user-images.githubusercontent.com/249563/103470980-05bff500-4dce-11eb-9a97-e04b42cc365d.jpg)

**Comment by MUHAMMADRANGSEL** [comment]
![image](https://user-images.githubusercontent.com/25834335/103476845-c7d1c980-4deb-11eb-9b99-2e7be3afc961.png)
coba di cek pencarian data suplemen sasaran keluarga

**Comment by ianskids** [comment]
@MUHAMMADRANGSEL  di sasaran keluarga normal
 ![image](https://user-images.githubusercontent.com/60131374/103477131-184a2680-4dee-11eb-938e-b61d415e5b8c.png)

**Comment by eddieridwan** [comment]
> ![image](https://user-images.githubusercontent.com/25834335/103476845-c7d1c980-4deb-11eb-9b99-2e7be3afc961.png)
> coba di cek pencarian data suplemen sasaran keluarga

Di contoh sasaran penduduk itu, memang `dahri` tidak terdata.

**Comment by Nurhidayat29** [comment]
di demo.opensid.my.id tidak bermasalah

**Comment by MUHAMMADRANGSEL** [comment]
Didemo masih bermasalah hanya tdk terlalu diperhatikan

Pada tanggal Rab, 6 Jan 2021 11.15, Nur Hidayat <notifications@github.com>
menulis:

**Comment by MUHAMMADRANGSEL** [comment]
Setelah saya cek di demo sdh tdk ada masalah.

Pada tanggal Rab, 6 Jan 2021 11.19, MUHAMMAD SPD <muhammadrangsel@gmail.com>
menulis:

**Comment by MUHAMMADRANGSEL** [comment]
https://berputar.opensid.or.id/suplemen/rincian/, sekarang masalah ini muncul kembali untuk pencarian data sasaran keluarga

**Comment by MUHAMMADRANGSEL** [comment]
![image](https://user-images.githubusercontent.com/25834335/111017554-4ef47c80-83ef-11eb-8a07-3881fbc06eda.png)

**Comment by MUHAMMADRANGSEL** [comment]
Untuk sasaran penduduk aman

**Comment by eddieridwan** [comment]
Masalah sepertinya di browser anda. Clear cache di browser anda. Atau coba gunakan browser yg lain.
