### ISSUE TITLE
unduh laporan penduduk tidak berfungsi

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#3888]
### Bagaimana alurnya sampai muncul masalah?
buka statistik > laporan bulanan > unduh

### Seperti apa yang diharapkan?
bisa mengunduh laporan

### Apa yang terjadi?
file unduhan tidak muncul

### Informasi tambahan 

tes di demo

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Masalah karena hosting yg lambat mengakibatkan csrf field tidak ditambahkan ke form modal (popup dialog).

Sudah diperbaiki di `master`.
