### ISSUE TITLE
Kadus tidak bisa dimutasi

### ISSUE THREAD

**Issue by mizwaruddin** [OpenSID/OpenSID#3889]
### Bagaimana alurnya sampai muncul masalah?
Sehubungan dengan penambahan dusun dan perubahan jabatan, maka perlu ada penyesuaian. Misal: Semula dusun di desa Mutihkulon hanya ada satu, yaitu Mutihkulon. Dengan munculnya peraturan baru, jumlah dusun ditambah menjadi satu lagi, yaitu Dusun Kemantren. Jabatan Kadus yg semula di dusun Mutihkulon skr menempati posisi sbg Kadus Kemantren.
Ketika akan melakukan perubahan, nama Kadus Mutihkulon tidak muncul ketika akan ditambahkan di Dusun Kemantren.

### Seperti apa yang diharapkan?
Kadus bisa diubah secara fleksibel, mengingat jabatan setiap saat bisa berubah.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by ilamazuliaf** [comment]
versi berapa bung @mizwaruddin ? Bagaimana alur-nya?
Misal Begini.
Sebelum Perubahan
```
Dusun A - Kadus AAA
Dusun B - Kadus BBB
```
Setelah Perubahan
```
Dusun A - Kadus BBB
Dusun B - Kadus AAA
```
maka alur yang saya lakukan.
```
Dusun A - Kadus CCC
Dusun B - Kadus AAA
Dusun A - Kadus BBB
```
Karena tidak mungkin jika `Kadus Multi Jabatan`

**Comment by afa28** [comment]
Silahkan kosongkan terlebih dahulu, atau isi dgn nama penduduk yg lain (u/ sementara) baru kemudian disesuaikan ulang.

**Comment by mizwaruddin** [comment]
Saya coba tidak bisa.

**Comment by afa28** [comment]
ikuti alur ini pak @mizwaruddin 

```
Dusun A - Kadus CCC
Dusun B - Kadus AAA
Dusun A - Kadus BBB
```

**Comment by mizwaruddin** [comment]
Kasus di Desa saya:
Sebelum Perubahan/Pemekaran
Dusun A - Kadus AAA

Setelah Perubahan/Pemekaran
Dusun A - Kadus BBB
Dusun B - Kadus AAA

**Comment by afa28** [comment]
> Kasus di Desa saya:
> Sebelum Perubahan/Pemekaran
> Dusun A - Kadus AAA
> 
> Setelah Perubahan/Pemekaran
> Dusun A - Kadus BBB
> Dusun B - Kadus AAA

Ganti dlu Kadus Dusun A dgn penduduk lain (sementara).
Ganti kadus dusun B dengan Kadus AA
Ganti kadus desun A dengan Kadus BB

Mungkin begitu.

**Comment by mizwaruddin** [comment]
Setelah sya cek di database, kode kadus yg dulu (sblm dipindah dusun) masih ada, sehingga nama kadus ybs tidak bisa dimasukkan ke dusun lain. Beda jika dusun sebelumnya dihapus, maka kadus ybs bisa dipindah di dusun lain.

**Comment by eddieridwan** [comment]
Cara perubahan yg dijelaskan bung @afa28 berhasil. 
Jadi masalah ada di sistem @mizwaruddin . Bisa jelaskan cara menambah/memekarkan dari Dusun A menjadi Dusun A dan Dusun B? Apakah dibuat dusun baru bernama Dusun B? Atau mengubah Dusun A menjadi Dusun B kemudian membuat dusun baru Dusun A?

**Comment by eddieridwan** [comment]
> Setelah sya cek di database, kode kadus yg dulu (sblm dipindah dusun) masih ada, sehingga nama kadus ybs tidak bisa dimasukkan ke dusun lain. Beda jika dusun sebelumnya dihapus, maka kadus ybs bisa dipindah di dusun lain.

@mizwaruddin , kode Kadus AAA masih ada di dusun mana? Bukan Dusun A, karena anda katakan berhasil diubah menjadi Kadus BBB.

**Comment by mizwaruddin** [comment]
![img_20210117_192019.jpg](https://user-images.githubusercontent.com/39736008/104843684-861e4400-58fe-11eb-8733-2751efbf92de.jpg)

![img_20210117_192217.jpg](https://user-images.githubusercontent.com/39736008/104843691-8d455200-58fe-11eb-8751-64c1184d9340.jpg)

Dusun AAA = MUTIHKULON
Dusun BBB = KEMANTREN

Semula hanya ada Dusun AAA. Kemudian sya menambahkan Dusun BBB. Klo sya melakukan edit nama Dusun AAA menjadi BBB, akan trlalu banyak edit alamat KK.

**Comment by eddieridwan** [comment]
Mohon lampirkan file sql untuk tabel itu.

**Comment by mizwaruddin** [comment]
[tweb_wil_clusterdesa.zip](https://github.com/OpenSID/OpenSID/files/5827957/tweb_wil_clusterdesa.zip)

**Comment by mizwaruddin** [comment]
Sudah teratasi berkat bantuan Bang @fusionid
