### ISSUE TITLE
Menu Buku Administrasi tidak muncul di Level Operator

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#3890]
### Bagaimana alurnya sampai muncul masalah?
Saat login level Operator, Menu Buku Administrasi Tidak Muncul.

Sedangkan Menu Info Desa -> Aparatur Desa muncul dan bisa di klik, walau seharusnya muncul di Halaman Buku Administrasi.

### Seperti apa yang diharapkan?
Normal sebagaimana mestinya.

### Apa yang terjadi?
Agar sesuai dengan tampilan Menu seharusnya.

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3913
