### ISSUE TITLE
Tidak bisa ubahn Lever dari Administrator

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#3891]
### Bagaimana alurnya sampai muncul masalah?
Saat ini, saat membuat pengguna baru dengan level administrator, lalu ingin ubah menjadi operator atau kontributor, dsb, tidak tersedia pilihan lainnya.

Namun sebaliknya, bisa membuat yg awal level operator, lalu edit menjadi administrator.

### Seperti apa yang diharapkan?
Berjalan normal.

### Apa yang terjadi?
Agar bisa merubah semula pengguna lain level administrator menjadi operator.

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3912
