### ISSUE TITLE
Tambah Status hubungan Anak bagi Kepala Keluarga (perempuan) yang belum menikah

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#3893]
### Bagaimana alurnya sampai muncul masalah?
cari kepala keluarga perempuan yang belum menikah > tambah keluarga > tidak ada shdk untuk anak

### Seperti apa yang diharapkan?
bisa menambahkan status anak bagi kepala keluarga yang belum menikah 

### Apa yang terjadi?
tambah status anak bagi kepala keluarga tidak bisa

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by ariandii** [comment]
apakah perempuan belum menikah bisa di data bahwa punya anak?

**Comment by balongbesuk** [comment]
kan datanya dari surat medis (surat lahir dokter/bidan) pak, :smile: 

ini berimbas yang mengakibatkan anak tersebut hanya terdata lahir dari seorang ibu tanpa mencantumkan nama ayahnya (begitupun juga akta lahir anak tersebut)

dengan status ibu kandung masih belum menikah, bisa mengajukan KK sendiri, menjadi kepala keluarga dengan status belum kawin tetapi sudah memiliki anak :smile: 

dan ketika orangtua laki laki biologisnya ingin mencantumkan namanya di anak tersebut maka harus melalui sidang pengadilan / Tes DNA, 

referensi di internet sedikit sekali mungkin ini salah satunya
http://dukcapil.gunungkidulkab.go.id/akta-kelahiran-tanpa-buku-nikah-orang-tua/

**Comment by balongbesuk** [comment]
ini yang paling gamblang

https://radarutara.id/blog/2019/09/28/anak-diluar-nikah-bisa-punya-kk-sendiri/

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3911
