### ISSUE TITLE
Tabel pada halaman data wilayah administratif tidak responsif

### ISSUE THREAD

**Issue by khiar-rara** [OpenSID/OpenSID#3894]
### masalah
tabel tidak responsif
![Screenshot_2021-01-05-12-01-59-675_com android chrome](https://user-images.githubusercontent.com/74307159/103608559-362e9d00-4f4e-11eb-9bb9-8c9f3425b6de.jpg)

### apa yang terjadi
Tabel responsif

### apa yang diharapkan
tampilan enak dipandang

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by ariandii** [comment]
Sudah di commit ke repo Tema Natra
https://github.com/OpenSID/tema-natra/commit/099a5d762d65c11ebc6a833b25d39f14341cb775
