### ISSUE TITLE
Modul Pembangunan: Lengkapi Sumber Dana dan Gunakan Istilah Baku pada Sumber Dana

### ISSUE THREAD

**Issue by mizwaruddin** [OpenSID/OpenSID#3895]
### Bagaimana alurnya sampai muncul masalah?
Saat ini penggunaan sitilah pada sumber dana pembangunan masih belum baku, dan ada sumber dana yang belum tercakup.
![pembangunan_1](https://user-images.githubusercontent.com/39736008/103630202-ef539e00-4f73-11eb-9965-b0dfce006b81.png)

### Seperti apa yang diharapkan?
Semua sumber dana tercakup dan menggunakan istilah baku.
![pendapatan desa](https://user-images.githubusercontent.com/39736008/103630231-f8dd0600-4f73-11eb-87b9-48c63236a2c6.png)

http://www.bpkp.go.id/public/upload/unit/sakd/files/Juklakbimkonkeudesa.pdf
halaman 46

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sdh dicommit ke `rilis-dev` melalui https://github.com/OpenSID/premium/pull/58
