### ISSUE TITLE
Modul Pembangunan: Ganti Istilah Judul dengan Nama Kegiatan

### ISSUE THREAD

**Issue by mizwaruddin** [OpenSID/OpenSID#3896]
### Bagaimana alurnya sampai muncul masalah?
Saat ini dalam Isi Data PEmbangunan menggunakan istilah "Judul". Hal ini kurang tepat.
![pembangunan_2](https://user-images.githubusercontent.com/39736008/103630962-fdee8500-4f74-11eb-98c8-b0bcdacfcce0.png)

### Seperti apa yang diharapkan?
Gunakan istilah "Nama Kegiatan" untuk menggantikan istilah "Judul".

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sdh dicommit ke `rilis-dev` melalui https://github.com/OpenSID/premium/pull/58
