### ISSUE TITLE
Modul Pembangunan: Tambahkan Anggaran pada Isi Data Pembangunan

### ISSUE THREAD

**Issue by mizwaruddin** [OpenSID/OpenSID#3897]
### Bagaimana alurnya sampai muncul masalah?
Dalam isi data pembangunan saat ini belum ada jumlah anggaran, sehingga informasi tentang kegiatan pembangunan menjadi kurang jelas.

### Seperti apa yang diharapkan?
Tambahkan jumlah anggaran pada Isi Data Pembangunan
![pembangunan_3](https://user-images.githubusercontent.com/39736008/103632956-a6054d80-4f77-11eb-853c-ca0eee536172.png)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
Sudah tersedia di `master`
