### ISSUE TITLE
Modul Pembangunan: Setelah Menyimpan Titik Koordinat Tidak Langsung Kembali ke Form Sebelumnya.

### ISSUE THREAD

**Issue by mizwaruddin** [OpenSID/OpenSID#3899]
### Bagaimana alurnya sampai muncul masalah?
Setelah mengisi dan menyimpan titik koordinat lokasi pembangunan tidak otomatis kembali ke form sebelumnya.

### Seperti apa yang diharapkan?
Setelah menyimpan titik koordinat lokasi pembangunan langsung kembali ke form sebelumnya (Daftar Pembangunan)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sdh dicommit ke `rilis-dev` melalui https://github.com/OpenSID/premium/pull/58
