### ISSUE TITLE
Modul Pembangunan: Buat Persentase pada Isi Data Dokumentasi Pembangunan Fleksibel

### ISSUE THREAD

**Issue by mizwaruddin** [OpenSID/OpenSID#3900]
### Bagaimana alurnya sampai muncul masalah?
Saat ini persentase pada Isi Data Dokumentasi Pembangunan dipatok pada angka 0, 30, 80, dan 100 persen. Pada sumber dana selain Dana Desa umumnya 0, 50, dan 100 persen. 
![pembangunan_5](https://user-images.githubusercontent.com/39736008/103634726-101ef200-4f7a-11eb-9412-c664078330d9.png)

### Seperti apa yang diharapkan?
Buat isian persentase pada pada Isi Data Dokumentasi Pembangunan lebih fleksibel (user bisa membuat sendiri.)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sdh dicommit ke `rilis-dev` melalui https://github.com/OpenSID/premium/pull/58
