### ISSUE TITLE
Modul Pembangunan: Tampilkan Laporan Pembangunan di Website Desa

### ISSUE THREAD

**Issue by mizwaruddin** [OpenSID/OpenSID#3902]
### Bagaimana alurnya sampai muncul masalah?
Saat ini laporan pembangunan desa hanya tersedia di dashboard admin, sehingga masyarakat tidak bisa melihatnya.

### Seperti apa yang diharapkan?
Tampilkan laporan pembangunan di website desa sehingga masyarakat bisa melihatnya.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by ekkurb** [comment]
👍

**Comment by mizwaruddin** [comment]
Sudah terwakili di peta.
