### ISSUE TITLE
Luas Bangunan pada Data Inventaris Kontruksi Tidak Muncul

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#3904]
### Bagaimana alurnya sampai muncul masalah?
Saat sukses input Kolom Luas pada Kategori Inventaris (Kontruksi dalam Pengerjaan), Tapi data Luas tersebut tidak muncul di tabel.

<img width="621" alt="2021-01-06_00h43_05" src="https://user-images.githubusercontent.com/46939846/103680302-8e9a8480-4fb8-11eb-8d3a-5b0c975db99c.png">

<img width="688" alt="2021-01-06_00h43_39" src="https://user-images.githubusercontent.com/46939846/103680316-94906580-4fb8-11eb-9596-dca69a829c4b.png">

### Seperti apa yang diharapkan?
Muncul sebagaimana mestinya, sesuai dengan Data yang diinput.

### Apa yang terjadi?
Agar data tampil.

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3906
