### ISSUE TITLE
Modul Pembangunan: Laporan Hasil Unduh Masih Perlu Diperbaiki

### ISSUE THREAD

**Issue by mizwaruddin** [OpenSID/OpenSID#3907]
### Bagaimana alurnya sampai muncul masalah?
Saat melakukan unduh pada dokumen pembangunan, gambar pada file excel masih menumpuk dan menutupi teks lainnya.
![pembangunan_7](https://user-images.githubusercontent.com/39736008/103715431-303ec780-4ff3-11eb-8a7a-08d156566b0a.png)

### Seperti apa yang diharapkan?
Laporan hasil unduh tertata rapi.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
@mizwaruddin apakah fitur unduh ini diperlukan? Sepertinya yg lebih bermanfaat adalah https://github.com/OpenSID/OpenSID/issues/3908. Kalau anda setuju, mohon tutup issue yg ini.

**Comment by mizwaruddin** [comment]
Saya rasa jg tdk perlu, Bang. Saya buat issue ini krn fitur unduh sdh ada duluan. Lbh baik dihapus saja fitur unduhnya.
