### ISSUE TITLE
[Pembangunan] Sediakan Ekspor dalam Format RTF

### ISSUE THREAD

**Issue by mizwaruddin** [OpenSID/OpenSID#3908]
### Bagaimana alurnya sampai muncul masalah?
Saat ini belum tersedia ekspor dalam bentuk rtf, sehingga hasil cetak tidak bisa diedit

### Seperti apa yang diharapkan?
Tersedia ekspor dokumen dalam format rtf sehingga dapat dilakukan pengeditan.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by balongbesuk** [comment]
sudah ada d rilis .rtf / .doc
