### ISSUE TITLE
[Pembangunan] Sinkronisasi Modul Pembangunan ke OpenDK melalui API

### ISSUE THREAD

**Issue by mizwaruddin** [OpenSID/OpenSID#3909]
### Bagaimana alurnya sampai muncul masalah?
Saat ini belum tersedia sinkronisasi dokumen pembangunan ke OpenDK.

### Seperti apa yang diharapkan?
Sediakan sinkronisasi pembangunan dengan OpenDK sehingga pengiriman dokumen ke pihak kecamatan bisa lebih efisien.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by andifahruddinakas** [comment]
https://github.com/OpenSID/OpenDK/issues/333

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/975
