### ISSUE TITLE
Konfigurasi di Nginx

### ISSUE THREAD

**Issue by nolbyte** [OpenSID/OpenSID#391]
Salam Hormat
Saya mencoba implementasi openSID di server nginx berbasis subdomain(http://opensid.domain.or.id). Halaman utama bisa diakses, tapi untuk **siteman** setelah user login dengan benar, halaman tidak redirect ke **hom_desa** melainkan redirect ke halaman utama (first).
Konfigurasi nginx sedang saya utak atik. Apakah sudah pengguna lain yang implementasi di nginx?
Terimakasih

**Comment by simasta** [comment]
Mungkin bisa dishare konfig nginx nya mas @nolbyte

**Comment by nolbyte** [comment]
Prinsipnya sama seperti install di Apache kok. Kemaren saya gagal login karena ternyata passwordnya salah. Yang membedakan hanya pada penulisan rewrite rule yang ditulis langsung di config virtual hostnya, tidak seperti di Apache yang menggunakan file htaccess.
Rule ini harus diterapkan terutama untuk pengaksesan direktori surat, serta untuk menghilangkan penggunaan index.php pada URL.
Berikut rule yang saya conversikan dari rule htaccess nya OpenSID ke /etc/nginx/site-available/opensid di nginx:
`location / {
           try_files $uri $uri/ /index.php;
                rewrite ^(.*)$ /index.php/$1 break;
        }
`

Saya belum sempat untuk menulis secara lengkap langkah-langkah konfigurasi installnya.

**Comment by abim** [comment]
saya menggunakan config nginx nya dari sini 👍 : 

https://github.com/OpenSID/OpenSID/issues/846#issuecomment-372101973

**Comment by afa28** [comment]
https://github.com/OpenSID/OpenSID/wiki/Konfigurasi-Nginx-Untuk-Instalasi-OPENSID
