### ISSUE TITLE
Bug: Setelah Ketua RW Diganti, Tampilan Di Daftar RT Tetap Tidak Berubah

### ISSUE THREAD

**Issue by mizwaruddin** [OpenSID/OpenSID#3910]
### Bagaimana alurnya sampai muncul masalah?
Setelah dilakukan perubahan Ketua RW kemudian di-klik pada rincian RW, nama Ketua RW tidak berubah.

![bug_ketua RW2](https://user-images.githubusercontent.com/39736008/103736103-24b6c500-5022-11eb-979d-07490ab62a50.png)
![bug_ketua RW1](https://user-images.githubusercontent.com/39736008/103736112-2a140f80-5022-11eb-9b21-35853ba77d56.png)

Keterangan:
Nama Ketua RW sebelum perubahan: Aidi Faiz
Nama Ketua RW setelah perubahan: Muhammad Sobih

### Seperti apa yang diharapkan?
Ketua RW di rincian RW ikut berubah.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 21.01 pasca - Premium
| Versi PHP        | 7.4
| System operasi   |

**Comment by afa28** [comment]
Seharusnya untuk RW - dan RT - pd detail RT tdk ditampilkan dan mmang dikosongkan, krn ditujukan u/ pemilihan wilayah yg tdk memiliki RT sama halnya dengan RW (pd combo box).

**Comment by mizwaruddin** [comment]
> Seharusnya untuk RW - dan RT - pd detail RT tdk ditampilkan dan mmang dikosongkan, krn ditujukan u/ pemilihan wilayah yg tdk memiliki RT sama halnya dengan RW (pd combo box).

Setuju

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR https://github.com/OpenSID/premium/pull/62
