### ISSUE TITLE
[Log Penduduk] Pindahkan Log Penduduk ke submenu Kependudukan dan ubah namanya menjadi Peristiwa Penduduk

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#3915]
### Bagaimana alurnya sampai muncul masalah?
Pengguna baru banyak yang kurang tahu menu log penduduk agar lebih memudahkan dan memperjelas bahasa/ pengertian "Log" untuk dirubah menjadi "peristiwa" penduduk dan di masukkan ke submenu kependudukan

### Seperti apa yang diharapkan?
memudahkan mencari menu log penduduk '/ peristiwa penduduk

### Apa yang terjadi?
log penduduk susah di cari bagi pengguna baru

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
Bisa dibuat menjadi "Catatan Peristiwa" : 
1. Kelahiran
2. Kematian
3. Pidah
4. Datang

Ada di BUKU REKAPITULASI JUMLAH PENDUDUK.
