### ISSUE TITLE
[Layanan Mandiri] admin tidak bisa melihat kelengkapan dokumen yang di upload oleh pemohon

### ISSUE THREAD

**Issue by WAHYUDIK** [OpenSID/OpenSID#3917]
### Bagaimana alurnya sampai muncul masalah?

ketika admin membuka permohonan surat di layanan mandiri, admin tidak bisa melihat dokumen yang sudah di upload oleh pemohon melalui layanan mandiri, 
![image](https://user-images.githubusercontent.com/31026980/104116342-51344f00-534a-11eb-9aea-a2380eaef46a.png)

### Seperti apa yang diharapkan?

admin bisa melihat dokumen yang sudah di upload oleh pemohon
### Apa yang terjadi?

saat ini masih belum bisa melihat dokumen tersebut
### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by balongbesuk** [comment]
Duplicate #3877

**Comment by afa28** [comment]
> Duplicate #3877

Ok, bisa lengkapi issue ini jika ada tambahan.

**Comment by eddieridwan** [comment]
Sdh dicommit ke `rilis-dev` melalui https://github.com/OpenSID/premium/pull/73
