### ISSUE TITLE
[Layanan Mandiri] sediakan kolom isian  ketika admin klik tombol belum lengkap kemudian tombol kirim

### ISSUE THREAD

**Issue by WAHYUDIK** [OpenSID/OpenSID#3918]
### Bagaimana alurnya sampai muncul masalah?
apabila dokumen persyaratannya tidak lengkap, admin/operator klik tombol belum lengkap dan memberitahukan pemohon alasannya, akan tetapi tidak ada kotak isian untuk mengisi pemberitahuan alasannya, alahkah baiknya ketika klik tombol belum lengkap muncul kolom isian untuk mengisi pemberitahuannya kemudian baru klik kirim. sehingga pemohon tau apa kekurangannya
![image](https://user-images.githubusercontent.com/31026980/104116389-acfed800-534a-11eb-9ed2-4a59e3fb9bc8.png)

### Seperti apa yang diharapkan?

disediakan kolom/isian untuk memberitahukan kepada pemohon terkait kekurangan dokumennya, dan kemudian 
### Apa yang terjadi?
saat ini masih belum tersedia

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Maaf baru sempat komentar.

Sebelumnya telah didokumentasikan alur pemeriksaan surat. Jika belum lengkap, perangkat desa akan mengirim pesan ke pemohon menjelaskan apa yg perlu dilengkapi. Dan caranya menggunakan menu pesan, tidak membuat struktur tambahan.

Jadi untuk issue ini, yg diharapkan adalah secara otomatis mengirim pesan menggunakan kotak pesan, sehingga pemohon melihat di kotak masuk dan kemudian bisa menjawab melalui pesan juga.

Untuk membantu pemohon, yg dibayangkan adalah adanya tombol (di kolom aksi?) pada surat yg perlu dilengkapi untuk mengingatkan membuka kotak masuk.

**Comment by afa28** [comment]
```
Untuk membantu pemohon, yg dibayangkan adalah adanya tombol (di kolom aksi?) pada surat yg perlu dilengkapi untuk mengingatkan membuka kotak masuk.

Demikian juga untuk pesan pembatalan.
```

Jadi nantinya akan ada tombol (misal tdk lengkap/tdk sesuai) pd masing2 syarat surat??? Yg nantinya jika diklik otomatis mengirim pesan ke pengguna tsb???

**Comment by eddieridwan** [comment]
Saya kira tidak. Cukup hanya ada satu pesan yg masuk ke kotak pesan pemohon, yg dikirim oleh perangkat desa, yg menjelaskan secara keseluruhan apa yg perlu dilengkapi. Kemudian komunikasi antara pemohon dan perangkat desa bisa dilakukan melalui kotak pesan, atau pemohon bisa menghubungi langsung melalui HP/WA.

Sebaiknya sementara ini kita hindari membuat alur yg terlalu rumit dan sepertinya sulit dibuat stabil.

**Comment by WAHYUDIK** [comment]
> Saya kira tidak. Cukup hanya ada satu pesan yg masuk ke kotak pesan pemohon, yg dikirim oleh perangkat desa, yg menjelaskan secara keseluruhan apa yg perlu dilengkapi. Kemudian komunikasi antara pemohon dan perangkat desa bisa dilakukan melalui kotak pesan, atau pemohon bisa menghubungi langsung melalui HP/WA.
> 
> Sebaiknya sementara ini kita hindari membuat alur yg terlalu rumit dan sepertinya sulit dibuat stabil.

untuk pesannya memang tetap masuk ke kotak pesan di pemohon, tetapi untuk memberitahukan keterangan kekurangannya menurut saya tetap disediakan, agar operator/admin tidak harus masuk ke submenu kotak pesan untuk mengirim pesannya kepada pemohon.
memang operator/admin bisa langsung menghubungi via HP/WA,

**Comment by eddieridwan** [comment]
Sdh dicommit ke `rilis-dev` melalui https://github.com/OpenSID/premium/pull/215
