### ISSUE TITLE
[Layanan Mandiri] Tampilan permohonan surat kurang menjorok ke kiri

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#3919]
### Bagaimana alurnya sampai muncul masalah?
Layanan surat > permohonan surat

### Seperti apa yang diharapkan?
Penuh ke kiri

### Apa yang terjadi?
Menjorok ke kanan

### Informasi tambahan 
![20210110_144424](https://user-images.githubusercontent.com/35319600/104117336-18e53e80-5353-11eb-96a7-09f2a012d8dd.jpg)

**Comment by eddieridwan** [comment]
Sdh dicommit ke `rilis-dev` melalui PR https://github.com/OpenSID/premium/pull/73
