### ISSUE TITLE
[Layanan Mandiri] Duplikasi menu layanan mandiri

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#3920]
### Bagaimana alurnya sampai muncul masalah?
Terdapat banyak menu yang sama pada tampilan layanan mandiri

### Seperti apa yang diharapkan?
Bisa disederhanakan saja, nav menu sepertinya bisa d hapus, 4 menu besar bisa ditampilkan d tampilan mobile seperti dasboard admin,

### Apa yang terjadi ?
Duplikasi menu yang tidak perlu

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
Bisa diberi contoh tampilannya???

**Comment by balongbesuk** [comment]
![Screenshot_20210110-152449_Chrome](https://user-images.githubusercontent.com/35319600/104117989-189b7200-5358-11eb-9f78-001a0e4784d5.jpg)

4 menu layanan mandiri ditampilkan d menu mobile seperti dasboard admin

**Comment by afa28** [comment]
> ![Screenshot_20210110-152449_Chrome](https://user-images.githubusercontent.com/35319600/104117989-189b7200-5358-11eb-9f78-001a0e4784d5.jpg)
> 
> 4 menu layanan mandiri ditampilkan d menu mobile seperti dasboard admin

Tampilan untuk box menu sy sembunyikan di versi mobile krn ada menu navigasi. Apa perlu ditampilkan jg??? Atau menu navigasi di hapus sj dan boxmenu ditampilkan di versi mobile ???

**Comment by afa28** [comment]
![1223232](https://user-images.githubusercontent.com/57283157/104118187-b6437100-5359-11eb-8eca-e908f64115d3.JPG)

jika ditampilkan di versi mobile.

**Comment by balongbesuk** [comment]
Mungkin issue ini d skip saja, scroll kebawah masih ada duplikasi menu d tampilan awal layanan mandiri, mungkin masih terlalu sedikit menu d layanan ini, untuk sementara biarkan saja
