### ISSUE TITLE
u/ panduan

### ISSUE THREAD

**Issue by afa28** [OpenSID/OpenSID#3921]
FB
![2](https://user-images.githubusercontent.com/57283157/104118646-2bfd0c00-535d-11eb-998d-44b4069fb2f0.jpg)
![3](https://user-images.githubusercontent.com/57283157/104118649-2e5f6600-535d-11eb-8209-b2500a9f0328.jpg)
![4](https://user-images.githubusercontent.com/57283157/104118652-2f909300-535d-11eb-930d-27ce919ce112.jpg)
![5](https://user-images.githubusercontent.com/57283157/104118658-30c1c000-535d-11eb-9117-5cd4a9914fec.jpg)
![web 1](https://user-images.githubusercontent.com/57283157/104118670-37503780-535d-11eb-96c8-de7f54ff3312.jpg)

New 
![pembangunan_1](https://user-images.githubusercontent.com/57283157/104118771-f9074800-535d-11eb-938d-61a6c4002f06.JPG)
![pembangunan_2](https://user-images.githubusercontent.com/57283157/104118786-19cf9d80-535e-11eb-9028-cce5c7e12e27.JPG)

**Comment by afa28** [comment]
![pembangunan_3](https://user-images.githubusercontent.com/57283157/104118910-bdb94900-535e-11eb-9a07-7e3441a0b6b3.JPG)

**Comment by afa28** [comment]
![61](https://user-images.githubusercontent.com/57283157/104732703-314cc300-5770-11eb-958d-a01fab5dc8cd.JPG)
![67](https://user-images.githubusercontent.com/57283157/104732710-3447b380-5770-11eb-8fdd-7b226062adba.JPG)
![68](https://user-images.githubusercontent.com/57283157/104732716-3578e080-5770-11eb-9fc6-eedf71a79ad8.JPG)
![69](https://user-images.githubusercontent.com/57283157/104732723-36aa0d80-5770-11eb-919d-04dc87b847e3.JPG)
![70](https://user-images.githubusercontent.com/57283157/104732725-37db3a80-5770-11eb-804d-157731dba1b6.JPG)
![71](https://user-images.githubusercontent.com/57283157/104732728-3873d100-5770-11eb-8029-a04e3169a04b.JPG)
![72](https://user-images.githubusercontent.com/57283157/104732734-39a4fe00-5770-11eb-9683-453fff58799b.JPG)
![74](https://user-images.githubusercontent.com/57283157/104732740-3ad62b00-5770-11eb-9863-0084c1648b88.JPG)

**Comment by afa28** [comment]
Edit :
![profil 1](https://user-images.githubusercontent.com/57283157/105609428-dfddad00-5ddb-11eb-9835-af48ee605678.png)
![profil 2](https://user-images.githubusercontent.com/57283157/105609429-e1a77080-5ddb-11eb-9672-f0e7b613279a.png)

**Comment by afa28** [comment]
PUTTY
![11111](https://user-images.githubusercontent.com/57283157/106180373-c7500700-61ce-11eb-8eec-b1f0fffb062e.JPG)

**Comment by afa28** [comment]
Status Desa
![status idm](https://user-images.githubusercontent.com/57283157/106240346-b1762c80-6236-11eb-9cf1-e398306cae5b.png)

**Comment by Nurhidayat29** [comment]
![penduduk](https://user-images.githubusercontent.com/51182125/107854006-af71b780-6e4b-11eb-94b1-2a05c5b83e2a.jpg)
![ambil gambar](https://user-images.githubusercontent.com/51182125/107855006-61ac7d80-6e52-11eb-950a-aef178756ff2.jpg)

![unggah fto 1](https://user-images.githubusercontent.com/51182125/107855020-830d6980-6e52-11eb-9e32-a27dff1acf00.jpg)
![unggah foto daduk](https://user-images.githubusercontent.com/51182125/107855111-22caf780-6e53-11eb-8740-74c97df1a6dc.jpg)
