### ISSUE TITLE
Terdapat error java script

### ISSUE THREAD

**Issue by rudiansyahyunanda** [OpenSID/OpenSID#3922]
itu sepertinya error javascript. jd itu pasti ada javascript yg manggil library select2, tapi select2 nya belum ter include di page.

![IMG-20210110-WA0001](https://user-images.githubusercontent.com/50880846/104119953-dbd67780-5365-11eb-871c-435d94a5f5cb.jpg)
![Screenshot_20210109_163155](https://user-images.githubusercontent.com/50880846/104119967-eabd2a00-5365-11eb-9551-7b6cd9d0af2c.jpg)

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3940
