### ISSUE TITLE
Buku Administrasi BPD

### ISSUE THREAD

**Issue by HerryWanda** [OpenSID/OpenSID#3923]
Dasar Hukum :
PERATURAN MENTERI DALAM NEGERI REPUBLIK INDONESIA NOMOR 110 TAHUN 2016  TAHUN 2016
TENTANG BADAN PERMUSYAWARATAN DESA 

### Bagaimana alurnya sampai muncul masalah?
Belum ada Menu Buku Administarsi BPD yang terdiri dari : 
1. Buku Agenda Surat Keluar
2. Buku Agenda Surat Masuk
3. Buku Ekspedisi
4. Buku Data Inventaris BPD
5. Buku Laporan Keuangan BPD
6. Buku Tamu BPD
7. Buku Data Anggota BPD
8. Buku Data kegiatan BPD
9. Buku Data Aspirasi Masyarakat
10. Buku Daftar Hadir Rapat BPD
11. Buku Notulen Rapat BPD
12. Buku Data Peraturan/ Keputusan BPD
13. Buku Data Peraturan Desa
14. Buku Keputusan Musyawarah Desa
15. Buku Keputusan Musyawarah Perencanaan Pembangunan Desa
16. Laporan Kinerja BPD

### Seperti apa yang diharapkan?
Menu Buku Administarsi BPD tersedia didalam aplikasi OpenSID yang terdiri dari : 

1. Buku Agenda Surat Keluar (issue : #3924 )
2. Buku Agenda Surat Masuk (issue : #3925 )
3. Buku Ekspedisi (issue : #3926 )
4. Buku Data Inventaris BPD (issue : #3927 )
5. Buku Laporan Keuangan BPD (issue : #3928 )
6. Buku Tamu BPD (issue : #3929 )
7. Buku Data Anggota BPD (issue : #3930 )
8. Buku Data kegiatan BPD (issue : #3931 )
9. Buku Data Aspirasi Masyarakat (issue : #3932 )
X 10. **Buku Daftar Hadir Rapat BPD (tidak diperlukan)**
11. Buku Notulen Rapat BPD (issue : #3933 )
12. Buku Data Peraturan/ Keputusan BPD (issue : #3934 )
13. Buku Data Peraturan Desa (issue : #3935 )
14. Buku Keputusan Musyawarah Desa (issue : #3936 )
15. Buku Keputusan Musyawarah Perencanaan Pembangunan Desa (issue : #3937 )
16. Laporan Kinerja BPD (issue : #3937 )

### Informasi tambahan 
1. Buku Administrasi BPD sangat wajib digunakan untuk memantau dan melaporkan kinerja BPD setiap tahunnya.
2. Format Administrasi BPD akan di lengkapi di masing-masing issue 
3. Lampiran dasar hukum :+1: 

[2016 - Permendagari No 110-Tahun-2016-Tentang-Badan-Permusyawaratan-Desa.pdf](https://github.com/OpenSID/OpenSID/files/5794597/2016.-.Permendagari.No.110-Tahun-2016-Tentang-Badan-Permusyawaratan-Desa.pdf)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by balongbesuk** [comment]
Buku ini yang ngisi BPD atau Pemdes?

**Comment by HerryWanda** [comment]
Nantik yang input BPD,..

**Comment by ai-skematik** [comment]
fitur ini dibuat seperti fitur covid, operator BPD hanya bisa mengakses menu administrasi BPD

**Comment by HerryWanda** [comment]
iya bg @ai-skematik ,.. nantik yg di akses BPD hnya ftur mereka..

Mungkin bisa juga buka buat artikel..

**Comment by andifahruddinakas** [comment]
Sebaiknya dibuat aplikasi lain di luar OpenSID, seperti yg dibuat oleh bung @mizwaruddin

**Comment by A2643K** [comment]
> Dasar Hukum : PERATURAN MENTERI DALAM NEGERI REPUBLIK INDONESIA NOMOR 110 TAHUN 2016 TAHUN 2016 TENTANG BADAN PERMUSYAWARATAN DESA
> 
> ### Bagaimana alurnya sampai muncul masalah?
> Belum ada Menu Buku Administarsi BPD yang terdiri dari :
> 
> 1. Buku Agenda Surat Keluar
> 2. Buku Agenda Surat Masuk
> 3. Buku Ekspedisi
> 4. Buku Data Inventaris BPD
> 5. Buku Laporan Keuangan BPD
> 6. Buku Tamu BPD
> 7. Buku Data Anggota BPD
> 8. Buku Data kegiatan BPD
> 9. Buku Data Aspirasi Masyarakat
> 10. Buku Daftar Hadir Rapat BPD
> 11. Buku Notulen Rapat BPD
> 12. Buku Data Peraturan/ Keputusan BPD
> 13. Buku Data Peraturan Desa
> 14. Buku Keputusan Musyawarah Desa
> 15. Buku Keputusan Musyawarah Perencanaan Pembangunan Desa
> 16. Laporan Kinerja BPD
> 
> ### Seperti apa yang diharapkan?
> Menu Buku Administarsi BPD tersedia didalam aplikasi OpenSID yang terdiri dari :
> 
> 1. Buku Agenda Surat Keluar (issue : [(Buku Administrasi BPD) : 1. Buku Agenda Surat Keluar #3924](https://github.com/OpenSID/OpenSID/issues/3924) )
> 2. Buku Agenda Surat Masuk (issue : [(Buku Administrasi BPD) 2. Buku Agenda Surat Masuk #3925](https://github.com/OpenSID/OpenSID/issues/3925) )
> 3. Buku Ekspedisi (issue : [(Buku Administrasi BPD) 3. Buku Ekspedisi #3926](https://github.com/OpenSID/OpenSID/issues/3926) )
> 4. Buku Data Inventaris BPD (issue : [(Buku Administrasi BPD) 4. Buku Data Inventaris BPD #3927](https://github.com/OpenSID/OpenSID/issues/3927) )
> 5. Buku Laporan Keuangan BPD (issue : [(Buku Administrasi BPD) 5. Buku Laporan Keuangan BPD #3928](https://github.com/OpenSID/OpenSID/issues/3928) )
> 6. Buku Tamu BPD (issue : [(Buku Administrasi BPD) 6. Buku Tamu BPD #3929](https://github.com/OpenSID/OpenSID/issues/3929) )
> 7. Buku Data Anggota BPD (issue : [(Buku Administrasi BPD) 7. Buku Data Anggota BPD #3930](https://github.com/OpenSID/OpenSID/issues/3930) )
> 8. Buku Data kegiatan BPD (issue : [(Buku Administrasi BPD) 8. Buku Data kegiatan BPD #3931](https://github.com/OpenSID/OpenSID/issues/3931) )
> 9. Buku Data Aspirasi Masyarakat (issue : [(Buku Administrasi BPD) 9. Buku Data Aspirasi Masyarakat #3932](https://github.com/OpenSID/OpenSID/issues/3932) )
>    X 10. **Buku Daftar Hadir Rapat BPD (tidak diperlukan)**
> 10. Buku Notulen Rapat BPD (issue : [(Buku Administrasi BPD) 10. Buku Notulen Rapat BPD #3933](https://github.com/OpenSID/OpenSID/issues/3933) )
> 11. Buku Data Peraturan/ Keputusan BPD (issue : [(Buku Administrasi BPD) 11. Buku Data Peraturan/ Keputusan BPD #3934](https://github.com/OpenSID/OpenSID/issues/3934) )
> 12. Buku Data Peraturan Desa (issue : [(Buku Administrasi BPD) 13. Buku Data Peraturan Desa #3935](https://github.com/OpenSID/OpenSID/issues/3935) )
> 13. Buku Keputusan Musyawarah Desa (issue : [(Buku Administrasi BPD) 14. Buku Keputusan Musyawarah Desa  #3936](https://github.com/OpenSID/OpenSID/issues/3936) )
> 14. Buku Keputusan Musyawarah Perencanaan Pembangunan Desa (issue : [(Buku Administrasi BPD) 15. Buku Keputusan Musyawarah Perencanaan Pembangunan Desa #3937](https://github.com/OpenSID/OpenSID/issues/3937) )
> 15. Laporan Kinerja BPD (issue : [(Buku Administrasi BPD) 15. Buku Keputusan Musyawarah Perencanaan Pembangunan Desa #3937](https://github.com/OpenSID/OpenSID/issues/3937) )
> 
> ### Informasi tambahan
> 1. Buku Administrasi BPD sangat wajib digunakan untuk memantau dan melaporkan kinerja BPD setiap tahunnya.
> 2. Format Administrasi BPD akan di lengkapi di masing-masing issue
> 3. Lampiran dasar hukum 👍
> 
> [2016 - Permendagari No 110-Tahun-2016-Tentang-Badan-Permusyawaratan-Desa.pdf](https://github.com/OpenSID/OpenSID/files/5794597/2016.-.Permendagari.No.110-Tahun-2016-Tentang-Badan-Permusyawaratan-Desa.pdf)
> 
> Tanya	Jawab
> Versi OpenSID	2.x
> Versi PHP	
> System operasi

marked.
