### ISSUE TITLE
[Pengguna] Log aktivitas pengguna

### ISSUE THREAD

**Issue by afri18** [OpenSID/OpenSID#394]
banyaknya data nggak mungkin dikelola oleh satu operator, apalagi prinsip Sistem Informasi Desa ini yg paling jitu adalah kebersamaan dalam mengolah data, baik data penduduk, analisis, bantuan, persil dll. Untuk memudahkan Administrator mengetahui siapa yg memasukan/mengedit data tersebut agar sesama pengguna level operator bisa bertanggungjawab.
jadi intinya mohon dibuatkan tanda siapa pengguna yg menginputkan data baru ataupun mengedit terakhir terhadap data tersebut.
ini sangat pentiiing

**Comment by MUHAMMADRANGSEL** [comment]
Mantap ini sangqt penting sekqli

**Comment by eddieridwan** [comment]
Jika ingin diprioritaskan, silakan ada yang melengkapi panduan sesuai sistem timbal-balik. Tinggal beritahu halaman mana saja yang telah dilengkapi.

**Comment by MUHAMMADRANGSEL** [comment]
Mohon para programer Issue ini diprioritaskan

**Comment by ariandii** [comment]
Bisa cek commit versi 19.05-pasca dibawah ini?

https://github.com/OpenSID/OpenSID/commit/0c4a2d83bd6e2ec3e46034c6c5b825cc716740d6

**Comment by eddieridwan** [comment]
@ariandii , ya betul. Tgl dan pengguna yg mengubah data penduduk sekarang sudah direkam.

Jadi sekarang, bung @MUHAMMADRANGSEL dan @afri18 (atau pengguna lain yg juga berkepentingan) perlu merinci lebih lanjut data mana saja yg lain yg ingin direkam tgl/pengubah -- dan di mana informasi tersebut ditampilkan.

**Comment by andifahruddinakas** [comment]
Duplicate of https://github.com/OpenSID/OpenSID/issues/8194
