### ISSUE TITLE
Bug pada <iframe></iframe> untuk menampilkan media di website

### ISSUE THREAD

**Issue by Robi1107** [OpenSID/OpenSID#3941]
### Bagaimana alurnya sampai muncul masalah?
Saat masih di form penginputan artikel media bisa di tampilkan dengan baik, tapi saat di simpan dan di lihat di website yang muncul bukan media tapi kode <iframe></iframe>

### Seperti apa yang diharapkan?
Minta tolong segera di perbaiki agar bisa menampilkan media di website

### Apa yang terjadi?
bug pada <iframe></iframe> di website

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 21.01
| Versi PHP        | 7.4.12
| System operasi   | Win 10 x64

**Comment by eddieridwan** [comment]
Apakah sudah membaca panduan?
https://github.com/OpenSID/OpenSID/wiki/Artikel#cara-menyisipkan-media-dalam-artikel

Sebaiknya masalah penggunaan ditanyakan dulu di https://www.facebook.com/groups/OpenSID sebelum membuat issue. Issue dimaksudkan untuk hal2 yg telah terbukti memang bug atau permintaan baru.

**Comment by eddieridwan** [comment]
Issue ini ditutup. Silakan buka lagi, kalau memang ternyata masalah yg perlu diperbaiki.
