### ISSUE TITLE
Layanan Mandiri Tidak Bisa Memproses Permohonan Surat

### ISSUE THREAD

**Issue by Yon-hokage** [OpenSID/OpenSID#3942]
### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 21.01-pasca
| Versi PHP        | 
| System operasi   | windows 10

**Comment by eddieridwan** [comment]
Apakah terjadi di https://demo.opensid.my.id? Lampirkan tampakan layar. Lampirkan isi file terakhir di folder logs.

**Comment by eddieridwan** [comment]
Saya coba di https://demo.opensd.my.id dan normal. Jadi masalah ada di sistem anda. Silakan tanyakan/bahas di https://www.facebook.com/groups/OpenSID atau di forum OpenSID di Telegram.

Issue ini akan ditutup. Silakan buka lagi kalau ada informasi tambahan bahwa masalahnya memerlukan perbaikan sistem.
