### ISSUE TITLE
Tidak dapat mengunduh/melihat Dokumen Anggota Keluarga setelah di Ceklist

### ISSUE THREAD

**Issue by Gunturwijay** [OpenSID/OpenSID#3943]
### Bagaimana alurnya sampai muncul masalah?
file Kartu Keluarga telah di input dan di simpan
![image](https://user-images.githubusercontent.com/40741591/104546930-db88f580-565f-11eb-8f49-9003b2106a80.png)

![image](https://user-images.githubusercontent.com/40741591/104547164-7255b200-5660-11eb-9f65-afc913ac66c0.png)

### Seperti apa yang diharapkan?
Dukumen anggota Keluarga yang telah di ceklist dari Kepala Keluarga tidak Dapat Dilihat/diunduh dari anggota keluarga

### Apa yang terjadi?
tidak dapat mengunduh dokumen yang telah di ceklist
![image](https://user-images.githubusercontent.com/40741591/104547035-1e4acd80-5660-11eb-851e-680124d48912.png)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 21.01-pasca
| Versi PHP        | 
| System operasi   |

**Comment by Nurhidayat29** [comment]
apakah didemo jga begtu, opensid saya norml

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master`.
