### ISSUE TITLE
Opensid Error saat dihosting

### ISSUE THREAD

**Issue by andri000me** [OpenSID/OpenSID#3944]
### Apa yang terjadi?

Saat di hosting muncul Error Number: 1227

Access denied; you need (at least one of) the SHOW DATABASES privilege(s) for this operation apa solusinya mengatasi ini

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 21.01
| Versi PHP        | 5.6.30
| System operasi   |

**Comment by Jhiban-Khang** [comment]
baru main di Hostingnya? coba pelajari [disini](https://www.domainesia.com/panduan/user-privilege-mysql-di-shared-hosting/)

**Comment by eddieridwan** [comment]
Masalah yg terkait pemasangan di hosting anda, harap ditanyakan di https://www.facebook.com/groups/OpenSID atau forum OpenSID lainnya. Issue mohon dibatasi masalah yg telah dikonfirmasi memerlukan perbaikan sistem. 

Issue ini akan ditutup. Silakan buka lagi kalau telah jelas masalahnya ada pada sistem.
