### ISSUE TITLE
Tambah Keluarga

### ISSUE THREAD

**Issue by afri18** [OpenSID/OpenSID#3945]
### Bagaimana alurnya sampai muncul masalah?
Saat menambahkan Keluarga dari menu keluarga baik dari penduduk baru maupun penduduk yg sudah ada tidak bisa
![image](https://user-images.githubusercontent.com/6611881/104829475-d964a800-58a6-11eb-8655-fdf9e53101f0.png)

### Seperti apa yang diharapkan?
Harusnya kesalahan seperti ini tidak terjadi, karna di versi sebelumnya sudah AMAN

### Apa yang terjadi?
saat disimpan di info sukses tapi setelah di cari di menu keluarga tidak ada (tidak tersimpan)

### Informasi tambahan 
Pada Versi 20.11 Aman, baru terdetek di versi 21.01

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 21.01
| Versi PHP        | 7
| System operasi   | cpanel/online

**Comment by eddieridwan** [comment]
@afri18 Apakah sdh coba di https://demo.opensid.my.id. Saya barusan coba, normal. 
Bila di demo juga error, harap jelaskan data apa yg dimasukkan. Kalau di demo normal, berarti ada yg bermasalah di sistem anda.

**Comment by mizwaruddin** [comment]
Di demo aman.
