### ISSUE TITLE
Jumlah Angka Kepala Keluarga tidak sesuai setelah dihitung perdusun

### ISSUE THREAD

**Issue by Gunturwijay** [OpenSID/OpenSID#3946]
### Menu Keluarga
![image](https://user-images.githubusercontent.com/40741591/104986896-d6082280-5a46-11eb-8375-0d1f34aa5f34.png)

![image](https://user-images.githubusercontent.com/40741591/104987001-3008e800-5a47-11eb-968f-bac7248fd095.png)

### Seperti apa yang diharapkan?
Jumlah angka kepala keluarga seharusnya sesuai dengan total angka pada pencarian perdusun

### Apa yang terjadi?
Setelah dilakukan pencarian perdusun jumlah angka kepala keluarga dan setelah di total dari semua dusun
Terjadi ketidaksesuain jumlah angka kepala keluarga antara pencarian langsung tanpa filter perdusun
![image](https://user-images.githubusercontent.com/40741591/104987712-ee793c80-5a48-11eb-9ec9-29a734118a54.png)

![image](https://user-images.githubusercontent.com/40741591/104987723-f33df080-5a48-11eb-8a29-f88e536ec551.png)

![image](https://user-images.githubusercontent.com/40741591/104987731-f76a0e00-5a48-11eb-963d-c2b9f27f1f4f.png)

![image](https://user-images.githubusercontent.com/40741591/104987741-fb962b80-5a48-11eb-9dd6-b785bc1f9cdd.png)

![image](https://user-images.githubusercontent.com/40741591/104987748-ff29b280-5a48-11eb-99eb-e965f8784abf.png)

![image](https://user-images.githubusercontent.com/40741591/104987020-3d25d700-5a47-11eb-8d10-93e895065820.png)

### Informasi tambahan 
1. Telah dilakukan pengecekan pada web demo : https://demo.opensid.or.id/ (Terjadi ketidaksesuain jumlah angka kepala keluarga)
2. Jika pada web demo : https://berputar.opensid.my.id/ (Telah Sesuai)
| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 21.01-pasca
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
Ada data KK yg tidak memiliki dusun.

**Comment by Gunturwijay** [comment]
Iya, ternyata betul, ada Kepala Keluarga yang Dusunnya Hilang, terimakasih @afa28

**Comment by afa28** [comment]
> Iya, ternyata betul, ada Kepala Keluarga yang Dusunnya Hilang, terimakasih @afa28 

Mungkin issue yg perlu dibuat, perjelas hasil impor penduduk. Bisa ditambahkan pilihan jika tidak memiliki dusun data tdk dimasukkan.
