### ISSUE TITLE
[Layanan Mandiri] Login Anjungan Mandiri langsung diarahkan ke halaman buat surat

### ISSUE THREAD

**Issue by khiar-rara** [OpenSID/OpenSID#3947]
### Seperti apa yang diharapkan?
Anjungan mandiri, setelah login langsung diarahkan ke halaman buat surat

### Apa yang terjadi?
Mempercepat alur mengingat anjungan mandiri lebih digunakan utk permohonan surat.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
Silahkan diskusikan di forum FB.

**Comment by agungsugiarto** [comment]
Pak @khiar-rara, terima kasih sudah melaporkan issue. Silahkan berdiskusi dahulu dengan pengguna lain di https://www.facebook.com/groups/OpenSID atau di https://t.me/joinchat/SI0GWHeqKT39Gxhh. Terima kasih

**Comment by khiar-rara** [comment]
Sudah saya post digrup facebook pak

**Comment by agungsugiarto** [comment]
Mas @afa28

**Comment by afa28** [comment]
> Mas @afa28
> 
> https://www.facebook.com/groups/OpenSID/permalink/1816666088498364/

Permintaan issue seperti ini sebenarnya tergantun selera masing2 pengguna, bisa cek issue https://github.com/OpenSID/OpenSID/issues/4035 yg permintaannya beda jg.

Saat pertama kali layanan mandiri ini didesain ulang, pada halaman beranda sebenarnya berisikan informasi umum yg perlu diketahui warga (bisa berupa tulisan, slider gambar atau video) yg menjelaskan penggunaan layanan mandiri. (ini desain awal sy).

Tapi krn tdk ada yg meminta hal tsb, jadi pada halaman beranda sy tampilkan sama dengan halaman profil.

Jadi sy kembalikan kepengguna maunya apa.

**Comment by Zoel-WB** [comment]
Bila mungkin ada 2 alternatif, bagi warga yg belum lengkap datanya misal ada kelahiran baru atau ada pertambahan data dalam KK, pendapat saya harus meng-upload dokumen lampiran kelengkapan data, sedangkan warga yg sudah lengkap datanya bisa langsung ke halaman pengajuan surat, karena lampiran kelengkapan data juga saya kira cukup penting untuk kita di Pemdes, karena tidak semua warga selalu melaporkan ada perubahan dalam adminduk-nya, terkadang kita untuk melihat adanya perubahan data kalau saya pribadi harus menanyakan ke Bidang Posyandu untuk data kelahiran baru. terutama warga dengan BPJS berbayar kadang sudah hampir setahun perubahan data keluarga belum terlaporkan ke desa, kasus-kasus seperti ini banyak ditemukan di desa.

**Comment by eddieridwan** [comment]
Terapkan sebagai berikut untuk tampilan awal setelah login di Layanan Mandiri:

1. Jika ada pesan masuk yg belum dibuka, tampilkan halaman daftar pesan masuk
2. Jika tidak ada pesan masuk yg belum dibuka, tampilkan halaman permohonan surat

**Comment by FirlianiF** [comment]
tes komentar

**Comment by andifahruddinakas** [comment]
Sudah digabung ke `FITUR PREMIUM` melalui PR https://github.com/OpenSID/premium/pull/516
