### ISSUE TITLE
Tombol Peta Wilayah dan Infrastruktur Tidak Tampil di Dashboard

### ISSUE THREAD

**Issue by mizwaruddin** [OpenSID/OpenSID#3949]
### Bagaimana alurnya sampai muncul masalah?
Ketika membuka Pemetaan > Pengaturan Peta > Lokasi, Area, dll (akan melakukan penggambaran maupun pengeditan) peta di dashboard tombol peta wilayah dan infrastruktur tidak bisa tampil. Namun ketika dilakukan dengan cara pencarian kemudian tampil data tertentu yg dicari tombol2 tersebut dapat tampil. 
![bug_peta](https://user-images.githubusercontent.com/39736008/105119614-44aab600-5b03-11eb-92a6-0106642506cb.png)

### Seperti apa yang diharapkan?
Tombol peta wilayah dan infrastruktur di dashboard admin dapat tampil dalam semua kondisi.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by mizwaruddin** [comment]
@fusionid

**Comment by eddieridwan** [comment]
Sdh dicommit ke `rilis-dev` melalui PR https://github.com/OpenSID/premium/pull/81
