### ISSUE TITLE
[Menu] Menambah sub sub menu pada Menu Statis

### ISSUE THREAD

**Issue by PriyoHeri23** [OpenSID/OpenSID#3950]
### Bagaimana alurnya sampai muncul masalah?
belum ada/belum bisa menambahkan **_sub sub menu_** pada **_Menu Statis_**

![blm ada sub sub menu](https://user-images.githubusercontent.com/60887025/105127266-1634d700-5b13-11eb-9253-ee8177cd856f.png)

### Seperti apa yang diharapkan?
terdapat/bisa ditambah sub sub menu pada menu statis, tujuannya agar data bisa ditampilkan berdasarkan kategori (misalnya; kelompok)

![contoh sub sub menu 1](https://user-images.githubusercontent.com/60887025/105127326-3fedfe00-5b13-11eb-89be-bc380739478f.jpg)

![contoh sub sub menu 2](https://user-images.githubusercontent.com/60887025/105127332-43818500-5b13-11eb-9a12-2a53da9e893c.jpg)

### Apa yang terjadi?
karena belumada sub sub menu, maka setiap data (terutama kelompok) harus berada pada sub menu, sehingga terlalu banyak sub menu jika akan ditampilkan.

### Informasi tambahan 
biasanya di desa bisa terdapat lebih dari 1 kategori kelompok, contoh 
Kelompok tani ada 64 kelompok
Kelompok Budidaya Perikanan ada 8 kelompok

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 21.01-premium-pasca
| Versi PHP        |  7.4.x
| System operasi   | Win 10

**Comment by muhtar-coder** [comment]
Betul,,ini sangat di perlukan untuk pembuatan menu dengan sub menu agar beberapa menu terkait dapat di tampilkan di dalam/di bawah menu utama sebagai sub menu,

**Comment by balongbesuk** [comment]
Duplicate #3028

**Comment by muhtar-coder** [comment]
di menu saya sudah tersedia,tapi dengan pembuatan menu 'KELOMPOK TANI' Tersendiri.apakah ini yg di maksud ?
ataukah yang lain ?
![image](https://user-images.githubusercontent.com/55665526/105363702-ea0e7880-5c2e-11eb-8941-3b3ae613704d.png)

**Comment by PriyoHeri23** [comment]
mungkin seperti ini bang @muhtar-coder  

![sub sub menu cugung](https://user-images.githubusercontent.com/60887025/105371266-057d8180-5c37-11eb-97d5-b13add781ef4.jpg)

**Comment by andifahruddinakas** [comment]
Duplicate issue https://github.com/OpenSID/OpenSID/issues/5254
