### ISSUE TITLE
[Statistik] Kepemilikan Kartu Identitas Anak perlu di rekam didalam Aplikasi

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#3951]
### Bagaimana alurnya sampai muncul masalah?
Sekarang ini dukcapil gencar-gencarnya menerbitkan KIA (Kartu Identitas Anak) sehingga perlu dibuatkan fitur untuk merekam kepemilikan KIA. di OpenSID belum ada tempat untuk merekam 

### Seperti apa yang diharapkan?
Adanya Fitur untuk merekam kepemilikan KIA, seperti Kepemilikan KTP
![KIA](https://user-images.githubusercontent.com/25834335/105210152-41541080-5b7d-11eb-960d-5bf91d9d383f.png)

### Apa yang terjadi?
Kita Tidak bisa membedakan mana yang sudah punya KIA mana yang belum

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by andifahruddinakas** [comment]
Duplicate of https://github.com/OpenSID/OpenSID/issues/4051
