### ISSUE TITLE
[Template Surat] Blangko F-1.01 kab malang 

### ISSUE THREAD

**Issue by dwiyudapranata** [OpenSID/OpenSID#3953]
blangko F-1.01 kab malang  berbeda dengan yang ada di opensid 
### Bagaimana alurnya sampai muncul masalah?

sering di tolak oleh kependudukan karena form f-1.01 berbeda dengan yang ada di capil
### Seperti apa yang diharapkan?
mohon untuk dibuatkan form f-1.01 yang akan saya lampirkan di bawah ini 
[http://sipeduli.malangkab.go.id/uploads/downloads/formulir_kk_depan.pdf](url)

![image](https://user-images.githubusercontent.com/66790143/105280255-ec93b280-5bdb-11eb-8cc0-f54fb62aa095.png)

**terimakasih** 

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by balongbesuk** [comment]
bedanya dimana?

**Comment by andifahruddinakas** [comment]
Untuk lampiran F-1.01 sudah disesuaikan di rilis v22.10-premium sesuai aturan yang berlaku, untuk lampiran dengan format yang digunakan berbeda, bisa sediakan agar lampiran tsb bisa disesuaikan sendiri oleh desa. Poin 3 issue https://github.com/OpenSID/OpenSID/issues/5683
