### ISSUE TITLE
Tema natra error saat menampilkan Bantuan Keluarga

### ISSUE THREAD

**Issue by mizwaruddin** [OpenSID/OpenSID#3954]
### Bagaimana alurnya sampai muncul masalah?
Saat akan membuka menu Bantuan Keluarga menggunakan tema natra terjadi error dan muncul notif seperti di gambar ini.

![bug_bantuan](https://user-images.githubusercontent.com/39736008/105331608-3db89c00-5c06-11eb-8fa8-4b9890e21879.png)

### Seperti apa yang diharapkan?
Tema natra dapat menampilkan bantuan keluarga.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 21.01 Pasca Premium
| Versi PHP        | 7.4.13
| System operasi   |

**Comment by ariandii** [comment]
sudah dicommit ke master repo tema tsb.

**Comment by mizwaruddin** [comment]
Trims, Bung.
