### ISSUE TITLE
Beberapa format kalimat yang kurang lengkap pada import BIP 2016

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#3958]
### Bagaimana alurnya sampai muncul masalah?
format kalimat import BIP 2016 Opensid sedikit berbeda dengan yang dikeluarkan dispenduk

### Seperti apa yang diharapkan?
lengkapi format kalimat import yang kurang

### Apa yang terjadi?
terjadi error kode tidak dikenal

### Informasi tambahan 

sudah lama tahu namun lupa pull request, tambahkan format kalimat import BIP 2016 dibawah :

1. TIDAK/BLM SEKOLAH
2. STRATA-II
3. AKADEMI/DIPLOMA III/SARJANA MUDA

4. KEPOLISIAN RI (POLRI)
5. TENTARA NASIONAL INDONESIA (TNI)
6. PEGAWAI NEGERI SIPIL (PNS)
7. PEKERJAAN LAINNYA

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3959
