### ISSUE TITLE
Paginasi di Menu Bantuan Tema Natra Tidak Rapi

### ISSUE THREAD

**Issue by mizwaruddin** [OpenSID/OpenSID#3960]
### Bagaimana alurnya sampai muncul masalah?
Saat menampilkan menu bantuan keluarga menggunakan tema natra, paginasi tidak rapi.

![bug_bantuan](https://user-images.githubusercontent.com/39736008/105662863-59bc8600-5f03-11eb-9a30-dc917960c5c2.png)

### Seperti apa yang diharapkan?
Paginasi menu bantuan pada tema natra rapi/normal.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 21.01-pasca premium
| Versi PHP        | 7.4
| System operasi   |

**Comment by afa28** [comment]
pak @ariandii

**Comment by afa28** [comment]
buat issue ini di https://github.com/OpenSID/tema-natra

**Comment by agungsugiarto** [comment]
Pak @mizwaruddin, terima kasih sudah melaporkan issue. Issue ini saya tutup. Silahkan buatkan issue terpisah di repository https://github.com/OpenSID/tema-natra. Terima kasih
