### ISSUE TITLE
Sediakan Link Cek Nomor Surat di Web

### ISSUE THREAD

**Issue by hasap86** [OpenSID/OpenSID#3962]
### Bagaimana alurnya sampai muncul masalah?
Saat ini surat yang beredar yg dibuat dengan opensid belum bisa dicek keasliannya melalui web opensid

### Seperti apa yang diharapkan?
adanya fitur menu untuk bisa mengecek kebenaran surat yang berdar

### Apa yang terjadi?
pihak terkait tidak bisa verifikasi kebenaran surat

### Informasi tambahan 
dengan adanya web desa opensid, pihak pihak terkait bisa mengecek keaslian surat dengan cara memasukan nomor surat pada menu khusus, ketika lakukan cek nantinya muncul informasi surat tersebut dan jika nomor surat tidak terdaftar maka di informasikan bahwa surat tidak terdaftar.
adapun informasi yang bisa dimunculkan saat melakukan pengecekan sbb:
Nama
NIK
Keterangan
Keperluan
Tgl Berlaku

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | Demo
| Versi PHP        | 
| System operasi   |

**Comment by satiri** [comment]
kalo belom ada yang ambil. saya mau ambil issue ini boleh?

**Comment by hasap86** [comment]
> kalo belom ada yang ambil. saya mau ambil issue ini boleh pak @eddieridwan ?

boleh, lanjut hehe

**Comment by eddieridwan** [comment]
@satiri , silakan. 

Tujuan fitur ini adalah menyediakan fitur supaya pihak yg menerima surat ybs dapat memeriksa keabsahan surat itu. Yaitu bahwa surat itu memang dikeluarkan desa x untuk warga ybs.

Solusi yg terpikir adalah sbb:
1. Siapkan QRCode secara otomatis, yg berisi informasi yg dapat digunakan untuk verifikasi keabsahan surat.
2. Tahap awal, QRCode tersebut cukup di copy/paste secara manual oleh petugas ke dalam surat ybs.
3. Di footer surat (atau bagian lain yg cocok) sediakan tautan yg bila di-klik atau dimasukkan ke browser akan menampilkan informasi seperti yg ada di QRCode.
4. Tautan itu akan menampilkan form yg perlu diisi sebelum informasi verifikasi ditampilkan. Informasi yg perlu diisi adalah nama, lembaga dan No. HP.  Informasi itu direkam di log_verifikasi_surat, dan juga merekam IP Address yg mengakses beserta tanggal akses. Tujuannya supaya semua pihak yg melakukan verifikasi tercatat.  

Pada tahap lanjutan/susulan, untuk poin (2), QRCode otomatis disematkan pada surat. Tapi ini rumit secara teknis, karena perlu melakukan manipulasi RTF. Jadi bisa ditunda untuk diterapkan belakangan sebagai pekerjaan terpisah.

**Comment by satiri** [comment]
terimakasih pak. saya akan kerjakan.

**Comment by satiri** [comment]
beberapa pertanyaan untuk pak @eddieridwan 
1. apakah pengecekan ini hanya oleh ybs. apa berarti didalam layanan mandiri?
2. jika didalam layanan mandiri, bukankah berarti sudah ada record tentang layanan?

untuk pak @hasap86 
3. adakah kemungkinan pengecekan dilakukan oleh pihak ketiga?

**Comment by eddieridwan** [comment]
Pengecekan dimaksudkan untuk pihak ketig, misalnya pihak instansi atau yg berwenang yg menerima surat dan ingin memastikan surat itu betul dikeluarkan oleh desa. 

Pemohon sendiri tidak perlu mengecek. Fitur ini tidak terkait layanan mandiri.

Formnya adalah untuk `Verifikasi Surat`, dan seperti dijelaskan di atas formnya mengumpulkan data pihak yg mengecek. Supaya diketahui siapa saja pihak ketiga yg berkepentingan memeriksa keabsahan surat yg dikeluarkan desa.

**Comment by eddieridwan** [comment]
Di form verifikasi, mungkin sebaiknya juga minta diisi nomor suratnya --- untuk lebih memastikan permintaan verifikasi ini betul dari pihak yg memegang surat secara fisik (dan bisa melihat nomor suratnya), dan bukan oleh pihak yg iseng menggunakan fitur yg bisa diakses publik ini. 

Yaitu ada dua faktor yg dicross-cek untuk menjamin permintaan itu sendiri memang dari pihak yg berkepentingan:
1. id surat yg termasuk bagian dari url yg dicetak di surat
2. nomor surat yg dimasukkan di form.

Perlu diingat, informasi verifikasi surat menampilkan data NIK/Nama dan sebagainya yg perlu dijaga keamanannya. Jadi sistem harus menjaga fitur ini tidak merupakan celah privasi data.

**Comment by balongbesuk** [comment]
Kalau hanya nomor bagaimana denga desa yg menggunakan per jenis surat, karena dimungkinkan nomornya sama, 

Apa sebaiknya cukup nik dan no surat,

**Comment by eddieridwan** [comment]
> Kalau hanya nomor bagaimana denga desa yg menggunakan per jenis surat, karena dimungkinkan nomornya sama,
> 
> Apa sebaiknya cukup nik dan no surat,

Tautan yg dicetak disurat berisi `id` surat (id dari tabel `log_surat`. Nomor surat hanya untuk cross-cek bahwa surat dengan `id` tersebut betul berisi surat dengan nomor tersebut. Jadi nomor surat (lengkap) bukan untuk mencari suratnya, tetapi untuk meyakinkan bahwa yg mengakses memang memegang surat tercetak secara fisik.

**Comment by eddieridwan** [comment]
Sdh dicommit ke `rilis-dev` melalui https://github.com/OpenSID/premium/pull/107
