### ISSUE TITLE
Penambahan Kategori pada artikel

### ISSUE THREAD

**Issue by sabarelvaz** [OpenSID/OpenSID#3963]
### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by sabarelvaz** [comment]
Mohon agar disediakan penambahan kategori pada artikel, misalkan satu artikel bisa memilih beberapa KATEGORI

**Comment by HerryWanda** [comment]
Sialakn lengkapi issue anda,,..
supaya bisa dipahami...
Bagaimana alurnya sampai muncul masalah?
Seperti apa yang diharapkan?
Apa yang terjadi?
Informasi tambahan

**Comment by hasap86** [comment]
alur penulisan artikel harus dirubah, tulis artikel dulu baru pilih kategori saat di halaman pembuatan artikel sepeti halnya di wordpress, sehingga bisa menggunakan beberapa kategori

**Comment by sabarelvaz** [comment]
> 
> 
> alur penulisan artikel harus dirubah, tulis artikel dulu baru pilih kategori saat di halaman pembuatan artikel sepeti halnya di wordpress, sehingga bisa menggunakan beberapa kategori

**Comment by sabarelvaz** [comment]
> 
> 
> alur penulisan artikel harus dirubah, tulis artikel dulu baru pilih kategori saat di halaman pembuatan artikel sepeti halnya di wordpress, sehingga bisa menggunakan beberapa kategori

Bisa di kasih tau bos caranya.... saya sudah buat artikel, mau tak tambah kategori gak bisa. atau saya yg belum bisa?
![kategori](https://user-images.githubusercontent.com/78188880/106274349-b9e65b80-6266-11eb-9728-e087b182c363.jpg)

**Comment by afa28** [comment]
> alur penulisan artikel harus dirubah, tulis artikel dulu baru pilih kategori saat di halaman pembuatan artikel sepeti halnya di wordpress, sehingga bisa menggunakan beberapa kategori

Buat issuenya pak, mungkin perbaharui alur pembuatan artikel, halaman, dan kategori.
