### ISSUE TITLE
Tambah Pengaturan Akses Modul Saat Penambahan Pengguna

### ISSUE THREAD

**Issue by HerryWanda** [OpenSID/OpenSID#3964]
### Bagaimana alurnya sampai muncul masalah?
Banyak permintaan pengaturan tambahan pada modul pengaturan  > pengguna,
group pengguna saat ini :
1. Administrator
2. Operator
3. Redaksi
4. Kontributor

Yang mana dimasing2 pengguna mempunyai hak akses yang berbeda, khusus untuk pengguna **"Operator"** saja ditambahkan pengaturan yaitu berupa pilihan modul yang bisa mereka lihat atau akses.

Pengaturan modul yg sudah ada di pengatur>modul, tapi ini berlaku secara global untuk semua pengguna Administrator dan Operator.

### Seperti apa yang diharapkan?
pada pengaturan pengguna "operator" ada tambahan pilihan untuk modul yang bisa mereka akses atau bisa lihat sesuai masing tupoksi operator bagi perangkat desa sesuai tugas di SK Pengelolaan Sistem Informasi Desa.

Jadi waktu kita menambahkan pengguna kita bisa memilih modul apa saja yang dapat mereka akses atau lihat di aplikasi opensid.

Pengaturannya Seperti gambar dibawah ini :+1: 
![ssss](https://user-images.githubusercontent.com/32125282/106230497-373bad00-6222-11eb-9276-f33766b72cb9.png)

Jadi dari gambar diatas, saat kita memilih group operator, kita juga bisa memiliha modul apa yg akan mereka akses.
### Apa yang terjadi?
Dengan adanya pengaturan ini, nantik operator yang baru tidak susah dalam mengakses modul sesuai tupoksi mereka.
### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by balongbesuk** [comment]
Duplicate https://github.com/OpenSID/OpenSID/issues/2336

**Comment by afa28** [comment]
Ini RBAC, agar masuk prioritas bisa ditambahkan di vote.
