### ISSUE TITLE
Ubah penghitungan pelaporan penduduk bulanan agar real

### ISSUE THREAD

**Issue by muhtar-coder** [OpenSID/OpenSID#3965]
### Bagaimana alurnya sampai muncul masalah?
Saat ini angka jumlah penduduk awal dan penduduk akhir tidak sesuai dengan perubahan kejadian penduduk (kelahiran/kedatangan dan kematian/perpindahan) 

### Seperti apa yang diharapkan?

Angka awal bulan adalah angka terakhir pada bulan sebelumnya (semestinya) dengan catatan tidak ada penghapusan data penduduk yg tidak dapat terhitung. kemudian untuk angka penduduk akhir adalah jumlah yang sama dengan data statistik penduduk dan berdasarkan kejadian pada penduduk, secara sederhana hitungan nya adalah  : 
(jumlah penduduk akhir["sama dengan di statistik*] = pddk awal " +" kelahiran/keluarga baru " -" kematian " -" pindah " -" hilang) 

### Apa yang terjadi?

Angka pelaporan benar secara angka kejadian dan sesuai jumlah statistik penduduk saat di laporkan. 

### Informasi tambahan 
Saat ini kami melakukan perubahan secara manual yg di buat bung #ariandii  di sistem agar hasil angka/jumlah data tsb sesuai dengan kejadian dan statistik. 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 21.01 premium
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
Silahkan di PR hasil ubahannya.

**Comment by muhtar-coder** [comment]
kira kira seperti ini  
![image](https://user-images.githubusercontent.com/55665526/106264654-86043980-6258-11eb-9816-dd18d04d140a.png)

**Comment by muhtar-coder** [comment]
statistik saat ini/ketika cetak laporan penduduk bulanan
![image](https://user-images.githubusercontent.com/55665526/106265230-4f7aee80-6259-11eb-8c9d-bdf9204ab9b5.png)

**Comment by eddieridwan** [comment]
Sdh diperbaiki di rilis premium.
