### ISSUE TITLE
Menambah login layanan mandiri mengunaka ktp reader

### ISSUE THREAD

**Issue by donip90** [OpenSID/OpenSID#3966]
Manambah fitur layanan mandiri melalui ektp / teping ektp, ini bertujuan memudahkan orang tua saat pemerintah desa menyediakan mesin anjungan.

**Comment by khiar-rara** [comment]
Setuju

**Comment by hasap86** [comment]
> Manambah fitur layanan mandiri melalui ektp / teping ektp, ini bertujuan memudahkan orang tua saat pemerintah desa menyediakan mesin anjungan.

pake pin atau tidak?

**Comment by khiar-rara** [comment]
Kalau pke ektp reader menurut saya tidak perlu pake pin. Kalau manual pake pin

**Comment by donip90** [comment]
Tidak, jadi saat ektp tempelkan di alat card reader, otomatis masuk kelayanan surat menyurat. Ektp warga itu yang menjadi pin atau usernamnya

**Comment by balongbesuk** [comment]
Gmn mau ngoding kl programer gk punya alatnya, digaji pun tidak, silakan dibantu nyumbang alatnya 😄

**Comment by hasap86** [comment]
secara alur sudah bisa, tinggal merubah coding login pake rf id yang terhubung mendeteksi Chip ID Tag yang sudah ada di data setiap penduduk, jadi setiap ektp didaftarkan dulu tag idnya di data penduduk (sudah ada), nah nanti loginnya by Tag ID yg terdaftar.

saya bisa kirim kalau mau, siapa yang mau ngodingnya? boleh kirim alamatnya ke wa saya 087847457417 atau tele @petualangweb

**Comment by khiar-rara** [comment]
Yang siap pake aja apa ya. Kalau ada update repot kayaknya

**Comment by afa28** [comment]
> Gmn mau ngoding kl programer gk punya alatnya, digaji pun tidak, silakan dibantu nyumbang alatnya 😄 

Harga alatnya berapa, sy coba pesan. Atau ada link tempat jualnya???

**Comment by donip90** [comment]
![Screenshot_20210129_161336](https://user-images.githubusercontent.com/76193416/106277999-85759e00-626c-11eb-838b-0846cb5744fe.jpg)

Tokopedia

**Comment by hasap86** [comment]
> ![Screenshot_20210129_161336](https://user-images.githubusercontent.com/76193416/106277999-85759e00-626c-11eb-838b-0846cb5744fe.jpg)
> 
> Tokopedia

kemahalan itu, ada koq yg 500rb-an

**Comment by donip90** [comment]
![IMG_20210129_200446](https://user-images.githubusercontent.com/76193416/106278436-4a279f00-626d-11eb-9af0-77a8fa709bd5.jpg)
Ini murah

**Comment by hasap86** [comment]
![Screen Shot 2021-01-29 at 20 37 36](https://user-images.githubusercontent.com/45263721/106281729-329ee500-6272-11eb-8237-b28f9bd2bbb4.png)


ini aja murah

**Comment by khiar-rara** [comment]
> ![Screen Shot 2021-01-29 at 20 37 36](https://user-images.githubusercontent.com/45263721/106281729-329ee500-6272-11eb-8237-b28f9bd2bbb4.png)
> 
> ini aja murah

Cuma 8 digit

**Comment by muhtar-coder** [comment]
setelah ini issue nya daftar hadir aparat desa  finger print kayaknya..   soalnya alatnya ada yg multi. 
😁😁😁🙏

**Comment by balongbesuk** [comment]
> Yang siap pake aja apa ya. Kalau ada update repot kayaknya

Kmrin kan sudah ada yg pamer d grup, dan sudah d todong sm pak ketua untuk d sumbangkan ke komunitas, cb tanyakan ybs,

**Comment by yayanmulyanto20** [comment]
setuju banget

**Comment by balongbesuk** [comment]
Knp gak ada yg usul d skala prioritas 😄

**Comment by hasap86** [comment]
> Knp gak ada yg usul d skala prioritas 😄

karena sudah ada yg buat tinggal diminta kerelaannya memberikan scriptnya xixixi

**Comment by eddieridwan** [comment]
Sdh dicommit ke `rilis-dev` melalui https://github.com/OpenSID/premium/pull/115
