### ISSUE TITLE
[Layanan Mandiri] Alur Mesin Anjungan dan Layanan Mandiri harusnya berbeda

### ISSUE THREAD

**Issue by hasap86** [OpenSID/OpenSID#3967]
### Bagaimana alurnya sampai muncul masalah?
saat ini antara Layanan Mandiri yang bisa dilakukan dimana aja dengan Anjungan perlakuannya sama

### Seperti apa yang diharapkan?
Untuk Anjungan harusnya tidak perlu login, langsung ke menu pembuatan surat, pilih pilih, isi isi, langsung print, surat diambil dan diserahkan ke pelayanan untuk ditanda tangani dan dicap / atau hasil isian langsung kekirim ke operator untuk dicek isiannya kalo kalo ada yang harus dikoreksi, kemudian operator print

### Apa yang terjadi?
alurnya malah menjadi lama keliatannya, karena harus login dulu, belum lupa pin atau belum didaftarkan, mending langsung ke pelayanan aja, karena di desa itu tidak antri layanannya

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | berputar
| Versi PHP        | 
| System operasi   |

**Comment by mizwaruddin** [comment]
Bagaimana jika anjungan diletakkan di luar kantor desa?

**Comment by balongbesuk** [comment]
Brarti saya bisa buatkan surat dengan nama bapak, atau orang lain selain saya?? 

Sy lebih setuju kl d anjungan tidak perlu syarat surat, karena pastiny sudah dibawa ybs, kl sekarang d anjungan gmn mau upload? Kan gak ada fasilitas uploadnya, alhasil Harus buka lewat hp dulu untuk upload foto melengkapi syarat suratnya

Harusny usulan issue anjungan yg sudah menerapkan,

**Comment by hasap86** [comment]
> Bagaimana jika anjungan diletakkan di luar kantor desa?
> 
> Bagaimana juga cara sistem mengenali pemohon surat?
> 
> Alur yg Anda sampaikan jelas tidak aman.

kalau diluar kantor pake layanan mandiri
pemohon surat itu ya itu saya bilang input input isi isi atau pake rf id
aman dong kan belum ada tanda tangan dan cap :)

**Comment by hasap86** [comment]
> Brarti saya bisa buatkan surat dengan nama bapak, atau orang lain selain saya??
> 
> Sy lebih setuju kl d anjungan tidak perlu syarat surat, karena pastiny sudah dibawa ybs, kl sekarang d anjungan gmn mau upload? Kan gak ada fasilitas uploadnya, alhasil Harus buka lewat hp dulu untuk upload foto melengkapi syarat suratnya
> 
> Harusny usulan issue anjungan yg sudah menerapkan,

bisa, tapi operator desa gak akan kasih tanda tangan dan cap, hehe

**Comment by mizwaruddin** [comment]
Lantas bagaimana alur pembuatan surat? Apakah seperti operator membuat surat? Pilih jenis surat, pilih nama/nik, dst?

**Comment by hasap86** [comment]
> Lantas bagaimana alur pembuatan surat? Apakah seperti operator membuat surat? Pilih jenis surat, pilih nama/nik, dst?

1. input NIK / Tag Chip dgn RFID Reader (lebih aman pake RFID dengan inisial Tag Chip yang ada di data penduduk setelah didaftarkan)
2. pilih surat yang mau dibuat
3. isi keterangan
4. isi keperluan
5. Kirim (kirim ke operator seperti alur layanan mandiri) atau langsung print (kendala kesalahan ketik)

**Comment by khiar-rara** [comment]
Sebelumnya saya pernah usul dianjungan tidak usah pake pin, cukup nik utk login. Tapi tidak disetujui dgn alasan keamanan

**Comment by hasap86** [comment]
> Sebelumnya saya pernah usul dianjungan tidak usah pake pin, cukup nik utk login. Tapi tidak disetujui dgn alasan keamanan. Ya memang rentan klo autofill diaktifkan

kalo misalnya pake rfid reader tanpa input NIK sebenernya bisa aja, tapi jangan diperlihatkan isiannya dan tidak bisa diketik. menggunakan manual / keyboard.

**Comment by afa28** [comment]
Pengaturan anjungan yg pakai RFID bisa diletakkan di modul anjungan, bisa dikondisikan apakah di pakai keyboard virtual, pakai RFID atau lainnya.

**Comment by hasap86** [comment]
> Pengaturan anjungan yg pakai RFID bisa diletakkan di modul anjungan, bisa dikondisikan apakah di pakai keyboard virtual, pakai RFID atau lainnya.

setuju

**Comment by afa28** [comment]
Mas @agungsugiarto, terwakilkan di issue ini https://github.com/OpenSID/OpenSID/issues/3947
