### ISSUE TITLE
Sistem Pencarian Data Penduduk Saat Pembuatan Surat dirubah menjadi Pencarian Data saat Tambah Peserta Program Bantuan

### ISSUE THREAD

**Issue by hasap86** [OpenSID/OpenSID#3968]
### Bagaimana alurnya sampai muncul masalah?
Pencarian penduduk saat pembuatan surat dengan menggunakan chip tag ID ektp reader tidak bisa dilakukan, karena ketika tempel ektp ke reader selalu membaca data penduduk pertama karena ektp reader ketika membaca id langsung enter, sedangkan data belum ditemukan keburu ke enter sehingga memilih data baris pertama.
![Screen Shot 2021-01-29 at 20 28 42](https://user-images.githubusercontent.com/45263721/106280563-afc95a80-6270-11eb-8182-17209a1a88bc.png)

### Seperti apa yang diharapkan?
saat pencarian penduduk di data Peserta Program Bantuan tambah peserta program tidak seperti pencarian data penduduk di saat pembuatan surat, disini tidak terjadi memilih baris pertama tetapi menunggu adanya data sesuai id yg diinputkan, namun sayangnya pencarian penduduk tambah peserta program belum support pemanggilan berdasarkan id tag chip, bisa sekalian ditambahkan pencarian berdasarkan id tag chip yg sudah diinput di data penduduk, namun sistem pencariannya bisa digunakan di pencarian data pada cetak surat
![Screen Shot 2021-01-29 at 20 30 21](https://user-images.githubusercontent.com/45263721/106280865-0767c600-6271-11eb-80fa-f0d9506155eb.png)

### Apa yang terjadi?
saat mau mencetak surat pencarian penduduk tidak bisa menggunakan ektp reader by id tag chip.

### Informasi tambahan 
gunakan cara pencarian data penduduk di tambah peserta bantuan ke pencarian data penduduk di cetak surat

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | Demo
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sdh dicommit ke `rilis-dev` melalui https://github.com/OpenSID/premium/pull/115
