### ISSUE TITLE
Statistik Covid Indonesia Muter muter loading terus

### ISSUE THREAD

**Issue by hasap86** [OpenSID/OpenSID#3970]
### Bagaimana alurnya sampai muncul masalah?
statistik covid di beranda untuk yg Indonesia gak kebuka alias muter muter

### Seperti apa yang diharapkan?
muncul datanya

### Apa yang terjadi?
loading terus

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | Demo
| Versi PHP        | 
| System operasi   |

**Comment by Tnembull** [comment]
API yang bermaslah sepertinya

**Comment by afa28** [comment]
@dikisiswanto
