### ISSUE TITLE
Sering terjadi blank responsive file manager (blank hanya putih sehingga tidak dapat upload)

### ISSUE THREAD

**Issue by ReyhanArraaf** [OpenSID/OpenSID#3971]
### Bagaimana alurnya sampai muncul masalah?
Terkadang terjadi blank responsive file manager

### Seperti apa yang diharapkan?
responsive file manager muncul agar bisa upload foto dan video

### Apa yang terjadi?
terjadi blank pada responsive file manager, sehingga tidak dapat upload foto dan video dari responsive file manager

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 21.01-pasca
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
Baca panduan dan bisa bertanya di group FB.

Mas @agungsugiarto

**Comment by agungsugiarto** [comment]
Pak @ReyhanArraaf, terima kasih sudah melaporkan issue. Issue ini saya tutup. Harap ditanyakan di https://www.facebook.com/groups/OpenSID atau di https://t.me/joinchat/SI0GWHeqKT39Gxhh. Silahkan issue ini dibuka kembali jika masih menemukan issue yg dimaksud. Terima kasih
