### ISSUE TITLE
Tombol Hapus Data Terpilih di Menu Keuangan Submenu Input Data

### ISSUE THREAD

**Issue by WAHYUDIK** [OpenSID/OpenSID#3973]
### Bagaimana alurnya sampai muncul masalah?
ketika ingin input data keuangan menggunakan menu Input Data, di bagian belanja dan pembiayaan tombol hapus data terpilih tidak aktif meskipun isian sudah di centang.
![image](https://user-images.githubusercontent.com/31026980/106372862-a93cff00-63a6-11eb-85e7-9864d1ce8c93.png)

![image](https://user-images.githubusercontent.com/31026980/106372860-9d513d00-63a6-11eb-9e94-0185e9a3d6e4.png)

### Seperti apa yang diharapkan?
tombol hapus data terpilih aktif

### Apa yang terjadi?
saat ini masih belum berfungsi/aktif

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 21.01 Premium-Pasca
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
Sdh dicommit ke `bug-fix` melalui https://github.com/OpenSID/premium/pull/229
