### ISSUE TITLE
Daftar Kontak di Modul SMS ambil dari data Penduduk

### ISSUE THREAD

**Issue by hasap86** [OpenSID/OpenSID#3976]
### Bagaimana alurnya sampai muncul masalah?
Saat ini Daftar Kontak harus input manual

### Seperti apa yang diharapkan?
Daftar Kontak otomatis dari data penduduk yang sudah ada input nomer HPnya

### Apa yang terjadi?
input ulang

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | Demo
| Versi PHP        | 
| System operasi   |

**Comment by balongbesuk** [comment]
Duplikate https://github.com/OpenSID/OpenSID/issues/1653

**Comment by hasap86** [comment]
> Duplikate #1653

Siap, di up hehe

**Comment by Nurhidayat29** [comment]
Duplicate of #1653
