### ISSUE TITLE
Untuk peresntase pembangunan belum urut

### ISSUE THREAD

**Issue by donip90** [OpenSID/OpenSID#3977]
### Bagaimana alurnya sampai muncul masalah?
Untuk saat ini peresntase pembangunan belum urut.

### Seperti apa yang diharapkan?
Yang diharapkan peresntase pembangunan bisa urut 0% - 50% - 100%

### Apa yang terjadi?
Supaya saat melihat peresntase di pembangunan akan tau sudah berapa % pembangunan itu terlaksana

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by donip90** [comment]
![IMG_20210201_100913](https://user-images.githubusercontent.com/76193416/106413438-a280bb80-647c-11eb-8637-f6ff4555fe9c.jpg)


![IMG_20210201_101224](https://user-images.githubusercontent.com/76193416/106413452-add3e700-647c-11eb-8ccb-0a3f5b969768.jpg)

**Comment by eddieridwan** [comment]
Sdh dicommit ke `rilis-dev`
