### ISSUE TITLE
Layanan Administrasi Mandiri - surat menyurat

### ISSUE THREAD

**Issue by ahmadtimbul** [OpenSID/OpenSID#398]
Kebetulan saya aktif di karang taruna desa godog kec. Karangpawitan kab. Garut. 
Sudah dicoba sosialisasi penggunaan opensid. 
Ada yg bertanya, terkait penggunaan layanan mandiri. 
Bagaimana, kalo warga dikasih akses untuk mengisi form- form yg berkaitan dengan surat menyurat, (supaya datang ke kantor desa tinggal ambil berkas nya aja).
namun tidak bisa dicetak dirumah, harus tetap di kantor desa (terkait legalitas).
Terima kasih, mohon maaf sebelumnya

**Comment by MUHAMMADRANGSEL** [comment]
Ini mah sudah mau keluar dari aturan,,,, jd untuk masalah penginputan surat harus dilakukan oleh aparatur penerintah desa

**Comment by ahmadtimbul** [comment]
banyak aparat desa, yang lamban dalam bekerja. 
oleh karena itu, data awal biar warga yang memasukan... (lewat form di web), format surat kan sudah ada... beberapa waktu kemudian (hari yang sama / besok nya), warga ke kantor untuk mengambil hasil cetak surat yang sudah divalidasi oleh aparat desa....

**Comment by eddieridwan** [comment]
Apakah ini sama dengan #2235, #791, #341, #1976?

Sepertinya fitur ini penting bagi banyak desa. Cara untuk mempercepat fitur ini adalah supaya desa2 yg memerlukan menganggarkan secara patungan, supaya kita bisa bayar programmer.

**Comment by eddieridwan** [comment]
Kita gunakan issue #2235 sebagai issue tunggal untuk layanan permohonan surat di Layanan Mandiri. Mohon gabungkan spesifikasi yg diperlukan ke issue tersebut.

**Comment by eddieridwan** [comment]
Sudah dicommit sebagai fitur premium
