### ISSUE TITLE
Laman login layanan mandiri tidak bisa digulir

### ISSUE THREAD

**Issue by khiar-rara** [OpenSID/OpenSID#3980]
### Bagaimana alurnya sampai muncul masalah?
Laman login layanan mandiri tidak bisa digulir

### Seperti apa yang diharapkan?
Laman bisa digulir keatas dan kebawah

### Apa yang terjadi?
Pada layar hp ukuran kecil bisa digulir, sehingga komponen form bisa terlihat

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
Login layanan mandiri sudah diprbaharui.

Mas @agungsugiarto

**Comment by agungsugiarto** [comment]
Pak @khiar-rara, terima kasih sudah melaporkan issue. Issue ini saya tutup, di versi terbaru menu login untuk layanan mandiri sudah diperbaiki. Silahkan issue ini dibuka kembali jika masih menemukan issue yg dimaksud. Terima kasih
