### ISSUE TITLE
Ketika kolom NIP dikosongkan, maka hide NIP di semua tampilan

### ISSUE THREAD

**Issue by cepiandiana** [OpenSID/OpenSID#3981]
### Bagaimana alurnya sampai muncul masalah?
Selalu tampil NIP Kepala Desa di setiap tampilan + surat

### Seperti apa yang diharapkan?
Ketika isian NIP dikosongkan di identitas desa, maka kolom NIP di semua tampilan pun tanpa NIP, Seperti di tampilan maintenance mode dan surat

### Apa yang terjadi?
Mengingat Kepala desa adalah non PNS, jadi tidak punya NIP, kecuali kelurahan.. 
Tapi saya pun kurang tau kalo di daerah lain apakah kepala desa punya nip.. 

### Informasi tambahan 
Hanya masukan saja dan tidak terlalu urgent

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by balongbesuk** [comment]
rtf sepertiny tdk bisa dibuat logika if beda dengan html,

**Comment by afa28** [comment]
pak @cepiandiana apa ini masih bermaslah???

**Comment by afa28** [comment]
Untuk tahap awal, bisa batasi untuk surat .rtf terlebih dahulu. Krn cakupan untuk NIP terlalu luas, hampir di tiap modul ada.

**Comment by eddieridwan** [comment]
Saya kira tidak betul untuk menyembunyikan di `semua tampilan`. Lebih tepat dalah menyembunyikan di `semua laporan yg relevan`. Jadi perlu mendaftarkan semua laporan di mana NIP tidak tepat untuk ditampilkan.

**Comment by afa28** [comment]
https://github.com/OpenSID/premium/pull/338#pullrequestreview-735639717

**Comment by afa28** [comment]
https://github.com/OpenSID/premium/pull/338#issuecomment-903379711

**Comment by andifahruddinakas** [comment]
Duplikasi https://github.com/OpenSID/OpenSID/issues/4521
