### ISSUE TITLE
CSS Pseudo-class secara Dinamis

### ISSUE THREAD

**Issue by kurnyaannn** [OpenSID/OpenSID#3982]
### Bagaimana alurnya sampai muncul masalah?
Saat berada pada halaman tertentu, pada menu navigasi tidak menunjukan status aktif (tidak ada pseudo class nav-link:active)

### Seperti apa yang diharapkan?
Sebaiknya ditambahkan pseudo-class secara dinamis agar user tahu dimana lokasi navigasi berada.

### Apa yang terjadi?
Tidak terdapat pseudo-class yang bersifat dinamis

### Informasi tambahan 
-

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 21.x
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
Mas @agungsugiarto 

![33333333](https://user-images.githubusercontent.com/57283157/112667019-5ad04c00-8e8f-11eb-8b3b-a87a7c9cd17c.png)

**Comment by agungsugiarto** [comment]
Pak @kurnyaannn terima kasih sudah melaporkan issue. Silahkan tambahkan informasi yg lebih spesifik dibagian menu apa saja yg kurang dinamis ? terima kasih.
