### ISSUE TITLE
Sinkronkan data pengunjung online ke offline

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#3984]
### Bagaimana alurnya sampai muncul masalah?
Untuk kasus di mana OpenSID online hanya digunakan untuk akses publik dan tidak untuk pengelolaan data desa. Dalam skenario ini, pengelolaan data desa dilakukan offline, di server di kantor desa. Dengan demikian perubahan data di online dan offline akan terjadi secara terpisah dan perlu disinkronkan. 

Masing2 server offline dan online diatur supaya hanya berperan sesuai konfigurasi tersebut. Yaitu, fitur yang aktif hanya yg sesuai dengan tujuan masing2 server. Misalnya, di server online, fitur untuk mengelola data penduduk dan data desa lainnya tidak aktif. Penyesuaian fitur ini akan dibuatkan issue2 terpisah. 

Sinkronisasi yg diperlukan:
1. Sinkronkan data dari pengunjung online ke offline
2. Sinkronkan data desa dari offline ke online untuk publikasi publik
3. Sinkronkan data layanan mandiri online ke offline
4. Sinkronkan data layanan mandiri offline ke online

Masing2 dijabarkan pada issue terpisah. Issue ini khusus untuk `Sinkronkan data dari pengunjung online ke offline`.

### Seperti apa yang diharapkan?
Data pengunjung dapat secara berkala disinkronkan ke database OpenSID offline. Sinkronisasi ini cukup dilakukan melalui ekspor dan impor data menggunakan file. Data yg diekspor/impor hanya data yg telah berubah sejak sinkronisasi sebelumnya.

Fitur yg mengubah data online mencakup:

- komentar oleh pengunjung
- ubah, aktifkan atau hapus komentar oleh petugas desa

Tabel yg berubah online terkait fitur itu mencakup:

- komentar
- sys_traffic

**Data di tabel ini hanya diubah di online. Sistem offline hanya membaca tabel ini dan tidak mengubah.**

Struktur data di tabel itu perlu diubah supaya bisa dibandingkan dengan waktu sinkronisasi dan membantu melacak:

- sys_traffic
    - tanggal, supaya juga mencatat waktu, tidak tanggal saja
- komentar
    - updated_by, untuk mencatat siapa yg mengubah

Juga diperlukan tabel baru untuk mencatat sinkronisasi, `log_sinkronisasi`.
Perubahan tabel ini juga perlu disinkronkan. Kolom di tabel ini:

- id
- jenis (apa yg disinkronkan)
- server (offline atau online)
- created_at (waktu sinkronisasi)
- created_by (siapa yg melakukan)

Waktu sinkronisasi digunakan untuk menentukan data dari tabel lain yg perlu disinkronkan. Sinkronkan data yg berubah sejak waktu sinkronisasi terakhir untuk jenis sinkronisai yg dijalankan.

**Comment by eddieridwan** [comment]
Ada dua komponen pada issue ini:
- [ ] Eskpor data dari online
- [ ] Impor data online di offline

**Comment by eddieridwan** [comment]
Proses ekspor:

- Ada pilihan: (1) sejak waktu sinkronisasi terakhir (2) semua
- Kalau (1), hanya ekspor baris data yg diubah setelah waktu sinkronisasi terakhir sebagai mana direkam di `log_sinkronisasi_online` untuk jenis sinkronisasi ini
- Kalau (2), ekspor semua. 
- Juga ekspor data `log_sinkronisasi_online`, termasuk rekaman ekspor ini

**Comment by eddieridwan** [comment]
Proses impor:

- Impor semua data yg diekspor
- Selain `log_sinkronisasi`, id baris data juga diimpor. Data dengan id yang sama akan ditimpa dengan data yg diimpor
- Untuk `log_sinkronisasi`, id tidak diimpor. Data dengan jenis/server/created_at yg sama akan ditimpa dengan data yg diimpor
- Hasil impor dicatat ke `log_sinkronisasi`

**Comment by andifahruddinakas** [comment]
Perlu di rancang ulang
