### ISSUE TITLE
Waktu di Komentar Artikel tidak Sesuai

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#3985]
### Bagaimana alurnya sampai muncul masalah?
Saat komentar masuk, waktu yang tampil tidak sesuai dengan waktu saat ini.
<img width="957" alt="2021-02-02_22h17_43" src="https://user-images.githubusercontent.com/46939846/106620902-9ee85400-65a4-11eb-87df-cc1b7ba25382.png">

### Seperti apa yang diharapkan?
Normal sebagaimana mestinya

### Apa yang terjadi?
Agar dapat menunjukkan waktu yang sebenarnya.

### Informasi tambahan 
Tes di lakukan pada web https://berputar.opensid.my.id

**Comment by eddieridwan** [comment]
Sdh dicommit ke `rilis-dev`
