### ISSUE TITLE
Sinkronkan data desa dari offline ke online untuk publikasi publik

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#3986]
Issue ini bagian dari sinkronisasi OpenSID online dan offline. Issue ini khusus untuk sinkronkan data desa dari offline ke online untuk publikasi publik.

Issue ini untuk kasus di mana OpenSID online digunakan hanya untuk akses publik dan tidak digunakan untuk pengelolaan data desa. Pengelolaan data desa sepenuhnya dilakukan di server di kantor desa.

Issue terkait:
- https://github.com/OpenSID/OpenSID/issues/3984

### Seperti apa yang diharapkan?

Data yg ditampilkan di web publik termasuk berbagai statistik yang diolah dari data kependudukan dan data desa lain secara dinamis. Jadi data tersebut perlu tetap ada di database online. Tetapi data pribadi seperti NIK, No. KK dan nama tidak ditampilkan, dan untuk keamanan dapat disamarkan.

Fitur admin juga banyak yg tidak diperlukan di OpenSID yg hanya berisi web publik. Penyesuaian fitur ini diuraikan di issue terpisah.

**Comment by afri18** [comment]
bagaimana dengan desa yang mengolah data di online ?? takutnya malah merusak data desa yg bekerja online seperti saya, menurut saya yg bagus itu singkronisasi dari online ke offline, kalau ofline ke online artinya hanya bisa dilakukan pembaruan data di kantor desa, padahal ada juga perangkat/staf desa yg bekerja di rumah.
Menurut saya lebih baik dari online ke ofline karna sifatnya aplikasi dikerjakan oleh banyak BAGIAN dan tidak harus ke kantor desa (apalagi masa pandemi, kadang kita dituntut kerja di RUMAH)

**Comment by eddieridwan** [comment]
Issue ini BUKAN untuk desa yg menggunakan OpenSID online secara penuh, yaitu juga untuk pengelolaan data desa. Untuk itu akan ada issue terpisah. Seperti dijelaskan di atas, issue ini khusus untuk desa di mana OpenSID online digunakan HANYA untuk akses publik.

Sebagai informasi, mohon lihat pilihan penggunaan server di menu Pengaturan > Modul. Pilihan `Offline di kantor desa dan online di hosting` akan diperjelas menjadi `Pengelolaan data desa offline di kantor desa dan web publik di hosting`

**Comment by afri18** [comment]
Okeh , asal yg bisa merubah pengguna administrator aplikasi

**Comment by andifahruddinakas** [comment]
Perlu di rancang ulang
