### ISSUE TITLE
data kelompok di web

### ISSUE THREAD

**Issue by afri18** [OpenSID/OpenSID#3988]
### Bagaimana alurnya sampai muncul masalah?
Saat memaksimalkan data kelompok dimenu statis terjadi kesalahan JENIS KELAMIN, tidak sama dengan yang ada di database
![image](https://user-images.githubusercontent.com/6611881/106829426-b1ef4700-66be-11eb-9cc2-ba13d68631fc.png)

### Seperti apa yang diharapkan?
Sebaiknya kolom Jenis Kelamin digantikan dengan Nomor SK yg apa bila disorot mengarah ke filenya

### Apa yang terjadi?
tampilan jadi tidak sesuai database

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 21.02 Online
| Versi PHP        |  7
| System operasi   | Cpanel

**Comment by afa28** [comment]
Sudah di `master`. Silahkan dibuka jika masih bermasalah.
