### ISSUE TITLE
[Keluarga] Tambahkan fitur pindah domisili satu Keluarga (status dasar)

### ISSUE THREAD

**Issue by Appi-spec** [OpenSID/OpenSID#3989]
### Bagaimana alurnya sampai muncul masalah?
Belum ada fitur pindah domisili bagi seluruh anggota keluarga termasuk kepala keluarga 

### Seperti apa yang diharapkan?
sediakan fitur pindah domisili untuk satu keluarga (kartu keluarga) 

### Apa yang terjadi?
untuk merubah status penduduk (pindah) dalam satu keluarga saat ini hanya bisa perorangan 

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by Zoel-WB** [comment]
Merubah status dasar "pindah" >kepala keluarga-> ada pilihan untuk dapat merubah atau menconteng siapa saja sebagian atau semua anggota keluarga lainnya yg ikut pindah bersama Kepala Keluarga dengan demikian semua anggota keluarga yg dipilih atau diconteng secara otomatis akan mengubah status dasar anggota keluarga menjadi pindah. Hal ini supaya tidak perlu harus melakukan atau merubah status dasar anggota keluarga lainnya satu persatu secara berulang..
![gambar](https://user-images.githubusercontent.com/64481641/120903185-e3791e80-c66e-11eb-965f-3628bb78040f.png)

**Comment by andifahruddinakas** [comment]
Duplicate issue https://github.com/OpenSID/OpenSID/issues/3604
