### ISSUE TITLE
merubah headline menjadi modal halaman depan

### ISSUE THREAD

**Issue by deanvhin2** [OpenSID/OpenSID#399]
mas edie saya merubah file inti donjo-app/view/layout/header.php dan donjo-app/view/patrials/content.php agar headline pindah menjadi modal bootsrap . 
![screenshot from 2017-04-27 22-44-21](https://cloud.githubusercontent.com/assets/25787673/25492029/f4a4c5b4-2b9b-11e7-8a11-b8bdf67af535.png)

**Comment by Marzuki5** [comment]
itu aplikasi androidnya bikin pake web view boss? 
fungsi dari modal itu sendiri selain untuk headline untuk apa lagi ?

**Comment by deanvhin2** [comment]
selain bisa pake headline bisa juga di pake untuk kata" sambutan bos .

**Comment by dadannurman** [comment]
Maaf mas @deanvhin2 bisakah anda berbagi file donjo-app/view/layout/header.php dan donjo-app/view/patrials/content.php yang sudah anda rubah, berikut file aplikasi.apk nya mas?

**Comment by eddieridwan** [comment]
@deanvhin2 silakan upload donjo-app/view/layout/header.php dan donjo-app/view/patrials/content.php versi bootstrap ke issue ini, untuk dilihat apakah digabung atau disediakan sebagai pilihan.

**Comment by eddieridwan** [comment]
@deanvhin2 , apakah sudah siap untuk share kreasi anda?

**Comment by eddieridwan** [comment]
Diterapkan di http://kelurahansoklat.esy.es/soklat/first/.

**Comment by deanvhin2** [comment]
Okeee , file apk bisa d download di website @dadannurman .
Insallah mas @eddieridwan

**Comment by deanvhin2** [comment]
Saya lgi bnyak tugass hihi
