### ISSUE TITLE
Status Covid tidak Muncul

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#3990]
### Bagaimana alurnya sampai muncul masalah?
Saat buka website, info status covid tidak muncul dengan keterangan:
GET https://indonesia-covid-19.mathdro.id/api/ 502

### Seperti apa yang diharapkan?
Normal kembali.

### Apa yang terjadi?
Agar dapat tampil sebagaimana mestinya.

**Comment by fusionid** [comment]
Sadah diperbaiki di tema Natra oleh @ariandii
