### ISSUE TITLE
Status Kepemilikan KTP

### ISSUE THREAD

**Issue by afri18** [OpenSID/OpenSID#3991]
### Bagaimana alurnya sampai muncul masalah?
dengan terbitnya KIA sebagai Identitas Anak maka bisa katakan setiap Warga Negara punya kartu Identitas yaitu KIA dan KTP-eL, maka jadi tidak relefan kalau di form isian data Penduduk tampilannya masih Kepemilikan KTP , sebaiknya diganti menjadi Kepemilikan Identitas

### Seperti apa yang diharapkan?
Status Kepemilikan KTP di form isian biodata penduduk diganti menjadi Kepemilikan Identitas dan pilihannya :
1. Belum (untuk yg belum punya)
2. KIA (untuk yang punya Kartu Identitas Anak)
3. KTP-eL (untuk yg sudah punya KTP-eL)

![image](https://user-images.githubusercontent.com/6611881/106853761-cf3b0a00-66ec-11eb-8110-db2c9c77774a.png)

dan bisa masuk ke dalam STATISTIK DESA

### Apa yang terjadi?
Pemilik KIA tidak teridentifikasi (tidak terdata)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 21.02
| Versi PHP        | 7
| System operasi   | Cpanel (online)

**Comment by MUHAMMADRANGSEL** [comment]
setuju, dan ini sangat penting menurut saya karena sekarang anak umur 0-16 diharuskan memiliki KIA

**Comment by Nurhidayat29** [comment]
![Penduduk - Detail 1669 - Google Chrome 10_02_2021 19 05 25](https://user-images.githubusercontent.com/51182125/107508264-53046300-6bd3-11eb-8741-e6a16a6a5b6b.png)
![ Penduduk - Detail 1669 - Google Chrome 10_02_2021 19 05 37](https://user-images.githubusercontent.com/51182125/107508276-55ff5380-6bd3-11eb-94a8-d4f682c58c47.png)

**Comment by eddieridwan** [comment]
Sdh dicommit ke `rilis-dev` melalui PR https://github.com/OpenSID/OpenSID/pull/4005
