### ISSUE TITLE
Upload Foto Tidak Bisa Langsung Ambil Dari Kamera HP/DSLR

### ISSUE THREAD

**Issue by WAHYUDIK** [OpenSID/OpenSID#3994]
### Bagaimana alurnya sampai muncul masalah?
saat ini untuk upload foto (baik di individu ataupun yang lain2) tidak bisa langsung capture dari camera HP/DSLR

### Seperti apa yang diharapkan?
untuk uplaod foto agar bisa langsung capture dari camera HP/DSLR, agar proses lebih mudah

### Apa yang terjadi?

saat ini masih belum bisa, hanya bisa upload file.
### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by MUHAMMADRANGSEL** [comment]
Saatnya OpenSID memiliki fitur ini, supaya memudahkan bagi pemerintah desa dalam proses pengambilan foto

**Comment by abmuj18** [comment]
Mantap gan, lanjutkan.

**Comment by afa28** [comment]
Untuk tahap awal capture gambar digunakan di foto pendduduk, nanti bisa dijadikan contoh ke modul lain. 

Ukuran foto yg digunakan penduduk???

**Comment by SopianHadi2021** [comment]
Saya sangat Setuju

**Comment by abmuj18** [comment]
> Untuk tahap awal capture gambar digunakan di foto pendduduk, nanti bisa dijadikan contoh ke modul lain.
> 
> Ukuran foto yg digunakan penduduk???

Untuk ukuran foto kalau di SIAK pake ukuran 240x300 px

**Comment by eddieridwan** [comment]
Sdh dicommit ke `rilis-dev` melalui PR https://github.com/OpenSID/premium/pull/97
