### ISSUE TITLE
program bantuan

### ISSUE THREAD

**Issue by afri18** [OpenSID/OpenSID#3995]
### Bagaimana alurnya sampai muncul masalah?
saat input penerima bantuan baik keluarga maupun perorangan data tidak bisa tersimpan/GAGAL DISIMPAN
![image](https://user-images.githubusercontent.com/6611881/107216597-91691900-6a3f-11eb-9a8b-5cc00a57ab31.png)

### Seperti apa yang diharapkan?
seharusnya data tersimpan

### Apa yang terjadi?
jadi galau

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 21.02
| Versi PHP        | 7
| System operasi   | CPANEL

**Comment by eddieridwan** [comment]
Apakah terjadi di https://demo.opensid.or.id? Kalau tidak, berarti ada masalah di sistem anda.

Jelaskan langkah yg anda lakukan sejak sistem normal sampai terjadinya error ini.

Lihat isi file di folder logs pada saat error ini terjadi. Lampirkan di sini.

**Comment by afri18** [comment]
yang di https://demo.opensid.my.id/ masih 21.01 pasca

**Comment by afri18** [comment]
@eddieridwan  log eror ini 
ERROR - 2021-02-09 08:24:45 --> Query error: Field 'userID' doesn't have a default value - Invalid query: INSERT INTO `program_peserta` (`no_id_kartu`, `kartu_nik`, `kartu_nama`, `kartu_tempat_lahir`, `kartu_tanggal_lahir`, `kartu_alamat`, `kartu_id_pend`, `program_id`, `peserta`) VALUES ('1946901790036895', '3214126101800001', 'SUKIYEM', 'PURWAKARTA', '1980-01-21', 'Kp. Gandasari RT 003  RW 001 Dusun 1 Satu', '190', '20', '3214122905071773')

**Comment by afri18** [comment]
setalah struktur userID dan rdate di HAPUS lancar jaya issue di tutup
