### ISSUE TITLE
ingin bertanya loading saat dihosting

### ISSUE THREAD

**Issue by rohim2020** [OpenSID/OpenSID#3996]
### Bagaimana alurnya sampai muncul masalah?
Saat dihosting reload program sangat lama dan ketika membuka opensid/inde.php/siteman program loading 15 menitan

### Seperti apa yang diharapkan?
yang diharapkan bisa lebih baik tidak terlalu lama saat loading

### Apa yang terjadi?
loading lama dengan koneksi internet sudah stabil

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 21.02
| Versi PHP        | 5.6
| System operasi   | Windows 10

**Comment by balongbesuk** [comment]
Hosting overload,

**Comment by ariandii** [comment]
Pindah Hosting.

yang Lain Lancar Semua.

**Comment by mizwaruddin** [comment]
@afa28

**Comment by afa28** [comment]
Mas @agungsugiarto

**Comment by agungsugiarto** [comment]
Pak @rohim2020, issue ini saya tutup karena terkait dengan server masing2 pengguna. Silahkan gunakan layanan yg disediakan OpenDesa https://opendesa.id/mengonlinekan-opensid atau sejenis yg lebih optimal. Terima kasih.
