### ISSUE TITLE
bantuan keluarga

### ISSUE THREAD

**Issue by afri18** [OpenSID/OpenSID#3999]
### Bagaimana alurnya sampai muncul masalah?
tidak tampilnya penerima bantuan keluarga sesuai kartu penerima di halaman web
![image](https://user-images.githubusercontent.com/6611881/107323301-9f1ead00-6ad8-11eb-8b58-36cbd43a2ecc.png)

### Seperti apa yang diharapkan?
sebaiknya pada tampilan bantuan keluarga yg muncul nama peserta/penerima sesuai kartu keluarga
![image](https://user-images.githubusercontent.com/6611881/107323198-6ed70e80-6ad8-11eb-990b-487ff6c86814.png)

### Apa yang terjadi?
dikhawatirkan yg baca takut salah dikarnakan tidak sesuai dengan data kemensos

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 21.02
| Versi PHP        | 7
| System operasi   |cpanel

**Comment by eddieridwan** [comment]
Sdh dicommit ke `rilis-dev` melalui https://github.com/OpenSID/premium/pull/137
