### ISSUE TITLE
Fitur Filter di Dusun untuk Calon Pemilih tidak berjalan

### ISSUE THREAD

**Issue by rudiansyahyunanda** [OpenSID/OpenSID#4000]
Saat mau mengambil data calon pemilih dari menu kependudukan>Calon Pemilih saat memilih atau bermaksud untuk mengambil data perdusun tidak tampil. 

sudah dicoba disitus demo, yang menampilkan 2 dusun, saat dipilih dusun yg ke2 juga tidak menampilkan data yang diminta.

**Comment by eddieridwan** [comment]
Di https://demo.opensid.or.id tidak bermasalah. Harap lampirkan tampakan layar error yg anda alami.

![filter-dusun](https://user-images.githubusercontent.com/249563/107453309-d5266480-6b9e-11eb-8636-169799a92cf2.jpg)

**Comment by rudiansyahyunanda** [comment]
coba yang diberputar pak

**Comment by eddieridwan** [comment]
Sudah lebih cepat dilacak, silakan lampirkan tampakan layar error tersebut.

**Comment by rudiansyahyunanda** [comment]
![Screenshot_20210210_092615](https://user-images.githubusercontent.com/50880846/107455884-13615b00-6b82-11eb-9801-3afcedce13b1.jpg)

**Comment by rudiansyahyunanda** [comment]
Saya pilih dusun kemantren pada filter. Tp yg muncul mutih kulon

**Comment by eddieridwan** [comment]
Sdh dicommit ke `rilis-dev`
