### ISSUE TITLE
Error Saat pencarian data penerima bantuan

### ISSUE THREAD

**Issue by rudiansyahyunanda** [OpenSID/OpenSID#4001]
### Bagaimana alurnya sampai muncul masalah?
Masalah terjadi saat saya menambahkan penerima bantuan dengan data target penduduk.

Pada menu kependudukan
Kependudukan>Penduduk
lalu pada aksi > Penerima Bantuan > Nama Program. 
Terjadi error.

Saya sudah mencoba menambahkan 1 contoh program bantuan kategori penduduk dan menambahkan 1 penduduk sebagai penerima bantuan di akun demo berputar.opendesa.my.id
Juga terjadi error.

### Seperti apa yang diharapkan?
Saat pilih aksi penerima bantuan akan menampilkan data sebagaimana diharapkan.

### Apa yang terjadi?
Error.

### Informasi tambahan 
Pada aksi di menu keluarga, hasil muncul dan berjalan normal. Dengan kategori bantuan keluarga

**Comment by eddieridwan** [comment]
Sdh dicommit ke `rilis-dev` melalui PR https://github.com/OpenSID/premium/pull/98
