### ISSUE TITLE
dokumen penduduk tidak muncul setelah melakukan upload dokumen

### ISSUE THREAD

**Issue by kasipembts** [OpenSID/OpenSID#4002]
### Bagaimana alurnya sampai muncul masalah?
saat melakukan edit/penambahan penduduk dan mengupload dokumen kependuduka, setelah selesai dokumen tidak muncul, dan saya ulang , tidak muncul juga.

### Seperti apa yang diharapkan?
dokumen kependudukan yang sudah diupload dapat diakses kembali

### Apa yang terjadi?
dokumen kependudukan tidak muncul

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 21.02
| Versi PHP        | 
| System operasi   |
![image](https://user-images.githubusercontent.com/70615595/107598565-22670c80-6c59-11eb-8b60-10a5b20f3c4e.png)

**Comment by eddieridwan** [comment]
Apakah sdh coba di https://opensid.or.id? Kalau di situ normal, masalah ada di sistem anda. Untuk itu tanyakan di grup FB atau Telegram OpenSID. Issue khusus untuk masalah yg dipastikan memerlukan perbaikan sistem.
