### ISSUE TITLE
data wilayah 0

### ISSUE THREAD

**Issue by kasipembts** [OpenSID/OpenSID#4003]
### Bagaimana alurnya sampai muncul masalah?
saat ingin melihat data wilayah, data penduduk, kk 0 dan nama kepala wilayah tidak muncul

### Seperti apa yang diharapkan?
bisa kembali normal

### Apa yang terjadi?
tidak muncul di statistik laporan dan data kewilayahan

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |
![image](https://user-images.githubusercontent.com/70615595/107598679-73770080-6c59-11eb-9cdd-33d6bf31b89d.png)

**Comment by eddieridwan** [comment]
Apakah sdh coba di https://opensid.or.id? Kalau di situ normal, masalah ada di sistem anda. Untuk itu tanyakan di grup FB atau Telegram OpenSID. Issue khusus untuk masalah yg dipastikan memerlukan perbaikan sistem.
