### ISSUE TITLE
Data Perdes Perkades dan Perkel di Buku Administrasi desa NULL/Tidak muncul

### ISSUE THREAD

**Issue by kasipembts** [OpenSID/OpenSID#4004]
### Bagaimana alurnya sampai muncul masalah?
saat melakukan update 21.02, data Buku Administrasi Desa (Perdes, Perkades tidak muncul )

### Seperti apa yang diharapkan?
bisa diakses kembali

### Apa yang terjadi?
tidak tampil/kosong

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |
![image](https://user-images.githubusercontent.com/70615595/107598879-ee401b80-6c59-11eb-9120-5fa845a7c53c.png)

**Comment by eddieridwan** [comment]
Apakah sdh coba di https://opensid.or.id? Kalau di situ normal, masalah ada di sistem anda. Untuk itu tanyakan di grup FB atau Telegram OpenSID. Issue khusus untuk masalah yg dipastikan memerlukan perbaikan sistem.
