### ISSUE TITLE
[Pengaturan] Saran Tampilan Pengelompokan Pengaturan Dasar Agar Lebih Rapi dan Mudah di Pahami

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#4007]
### Bagaimana alurnya sampai muncul masalah?
buka http://berputar.opensid.my.id/setting

### Seperti apa yang diharapkan?
mungkin bisa dikelompokkan (perblok bagian) pengaturan dasar misal pengaturan web, pengaturan surat, pengaturan aplikasi 

### Apa yang terjadi?
terlihat campur aduk antara pengaturan dasar untuk surat, web, dan aplikasi,

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by balongbesuk** [comment]
karena saya masih menggunakan versi lama, saya baru sadar ada menu pengaturan di panel admin web,

mungkin untuk pengaturan dasar yang berhubungan dengan website bisa dipindah dan dijadikan satu dimenu pengaturan pada panel admin web

**Comment by balongbesuk** [comment]
Mungkin issue ini perlu dirubah menjadi terdapat menu pengaturan yang saling lompat antar menu yang "Memungkinkan" menyebabkan pengguna baru menjadi kebingungan sendiri antar menu pengaturan pada sebagian menu aplikasi dan pengaturan dasar,

sedikit contoh : misal untuk menjelaskan bagan admin web, isinya tersebut terdapat pengaturan apbes footer / footer all / manual input / covid rss / covid desa / statistik card 3d, 

yang pengaturan untuk web kita melompat ke menu lain yaitu panel pengaturan  > aplikasi, yang terdapat menu (untuk website), latar menu / latar login / admin title / website title / web artikel per page / web theme,

ini hanya contoh dari pengaturan web, ini juga terjadi pada pengaturan surat,
 
usul ini sedikit berhubungan dengan https://github.com/OpenSID/OpenSID/issues/3876
 
mungkin kedepan pengaturan tiap panel menu bisa disendirikan di tiap panel menu masing masing,

**Comment by andifahruddinakas** [comment]
Untuk sekarang sudah di pisah berdasarkan modul yang membutuhkan pengaturan tsb. Untuk modul pengaturan Aplikasi di peruntukkan pada pengaturan yang lebih umum.
