### ISSUE TITLE
Pemberian akses first.php pada pengguna fitur premium

### ISSUE THREAD

**Issue by rudiansyahyunanda** [OpenSID/OpenSID#4008]
### Bagaimana alurnya sampai muncul masalah?
saya ingin menambahkan url atau menyisipkan script tertentu di first.php namun khawatir jika diupdate bakalan kehapus lagi.

### Seperti apa yang diharapkan?
Dibuatkan tempat khusus agar bisa menambahkan script atau url yang diperlukan desa. Semisal untuk menambahkan produk desa.

### Apa yang terjadi?

Produk Masih bisa ditambahkan/ditampilkan namun berbentuk widget. Tapi sangat tidak efektif jika datanya banyak. 

Terkadang desa ingin menambahkan fiturnya sendiri, bukan bermaksud tidak memberikan kepada sesama komunitas melainkan keterbatasan seperti halnya kebijakan salah satu kabuaten/kota yang menghendaki penambahan fitur tertentu.
### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Letakkan fitur kustom di tema. Kalau tidak bisa karena perlu menyimpan data, silakan buat issue. Dan kemudian kirim PR. Tapi pastikan fitur dirancang untuk semua desa, bukan untuk keperluan satu desa saja. OpenSID tidak ada rencana menyediakan opsi menambah modul ubahan khusus satu desa.

**Comment by rudiansyahyunanda** [comment]
Mohon maaf pak, 
Maksud sya seperti ini
saya ingin membuat url didesa saya :
1. guntung.web.id/lapak 
2. guntung.web.id/kontak
dan sedang dalam pembuatan yaitu
Pembayaran air (PAMSIMAS) nantinya mau dibuat
3. guntung.web.id/pamsimas

tidak bisa ditambahkan karena first.php nya terkunci.

**Comment by eddieridwan** [comment]
Kalau sekadar untuk mengakses fitur diluar OpenSID (misalnya aplikasi lain di subdomain), bisa gunakan tautan eksternal di menu statis, atau tambahkan di widget Sinergi Program. Tetapi tidak ada rencana menyediakan cantelan di script inti OpenSID untuk akses ke modul khusus desa, selain tema dan tautan menu/widget tersebut. 

Untuk fitur2 yg anda sebut di atas, silakan tambahkan sebagai bagian dari rilis OpenSID sendiri. Sepertinya semua fitur tersebut juga diperlukan oleh desa lain. Silakan buat issuenya dan kirim pull requestnya. Issue untuk lapak/umkm sudah lama ada. Silakan anda terapkan untuk semua desa, bukan desa dampingan anda saja. Begitulah pola gotong royong OpenSID.

**Comment by afa28** [comment]
Untuk lapak akan segera rilis untuk mempermudah pengguna yg selama ini melakukan ubah data secara manual.

Untuk yang lainnya, jika memang mngerti coding di CI3 tinggal buat controller baru (tdk harus di controller firts). Tp hal ini tk dianjurkan krn akan mempengaruhi saat proses update kedepannya.

Silahkan di buka kembali jika masih ada kendala.
