### ISSUE TITLE
Tampilkan Menu Dinamis Pada Tema NATRA

### ISSUE THREAD

**Issue by PWidodo** [OpenSID/OpenSID#4009]
### Bagaimana alurnya sampai muncul masalah?
Menu Dinamis pada tema natra dapat ditampilkan dengan meng-enable widget "Menu Kategori" tetapi jika isi menu dinamis beserta sub menunya banyak, maka widget Menu Kategori tersebut akan memanjang ke bawah, yang membuat tampilan website kurang dinamis.

### Seperti apa yang diharapkan?
Rubah posisi menu STATIS di bagian atas header dan tampilkan menu DINAMIS dibawah gambar Slider.

### Apa yang terjadi?
Tampilan tema natra akan terlihat lengkap (full) menunya dan responsive. sebagimana gambar dibawah ini
![image](https://user-images.githubusercontent.com/45189822/107848178-f481f380-6e23-11eb-9842-48a4e6334da1.png)

Tampilan HP :
![image](https://user-images.githubusercontent.com/45189822/107848206-17aca300-6e24-11eb-8bc8-42f8f75ade2a.png)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 21.02
| Versi PHP        | 7.4
| System operasi   | Windows

**Comment by afa28** [comment]
buat issu di https://github.com/OpenSID/tema-natra

**Comment by agungsugiarto** [comment]
Pak @PWidodo, issue ini saya tutup. Terkait tema natra silahkan buatkan issue terpisah di repository https://github.com/OpenSID/tema-natra. Terima kasih
