### ISSUE TITLE
[Layanan Mandiri]  Notifikasi Realtime Tanpa Harus Reload Page

### ISSUE THREAD

**Issue by rudiansyahyunanda** [OpenSID/OpenSID#4010]
### Bagaimana alurnya sampai muncul masalah?
Ketika masyarakat menggunakan layanan mandiri tentunya membutuhkan penanganan secara cepat oleh perangkat desa, perangkat desa pun demikian, walaupun akun admin terbuka namun ketika halaman tidak direfresh /reload pesan yang memberitahukan bahwasanya ada permohonan dari masyarakat itu tidak tampil.

### Seperti apa yang diharapkan?
Alangkah baiknya dibuat seperti messenger,whatsaap atau jenis perpesanan lainnya yang langsung muncul notifikasi. dan alangkah baiknya juga jika pesan yang muncul itu tampil kelayar admin (misal dengan menampilkan modal dan sejenisnya) untuk memberitahukan atau untuk menyadarkan admin.  hal ini bertujuan agar admin lebih cepat merespon.

### Apa yang terjadi?
Hal ini tentunya tidak memaksimalkan fitur layanan mandiri, seandainya saja seharian komputer dibuka tanpa ada aktifitas dari admin. tentu saja pelayanan tidak terlaksana dan kemungkinan masyarakat enggan menggunakan layanan mandiri lagi. 

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by balongbesuk** [comment]
https://youtu.be/uP3NW-9j9fY

Jadi berat gak server side?

**Comment by balongbesuk** [comment]
https://devindo.top/codeigniter-dhtmlx/websocket-codeigniter

**Comment by balongbesuk** [comment]
https://github.com/takielias/codeigniter-websocket
