### ISSUE TITLE
Mohon info cara mengembalikan tombol cetak surat tanpa ekspor

### ISSUE THREAD

**Issue by prastyawan** [OpenSID/OpenSID#4011]
### Bagaimana alurnya sampai muncul masalah?
Tombol Cetak di samping tombol Ekspor saat proses pembuatan surat sekarang tidak tampil.

### Seperti apa yang diharapkan?
Mohon sekali bantuannya untuk menampilkan kembali, atau bs jg mohon info saya harus ubah di file apa agar tampil kembali akan saya coba.

### Apa yang terjadi?
Tidak ada tombol cetak, kades ngambek 🙉
krna PC dikantor ada yg lemot" jd hrus buka dok dlu br cetak.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 21.02
| Versi PHP        | 7.4
| System operasi   | Linux

**Comment by eddieridwan** [comment]
@prastyawan fitur lama menyusun surat menggunakan HTML dan PHP tidak akan dikembalikan, dgn alasan yg sudah lama dan sering dijelaskan. Silakan anda cari di berbagai forum OpenSID dan juga di wiki penjelasan ini.

Tapi mungkin issue ini bisa diubah untuk meminta agar surat RTF yg sekarang dihasilkan bisa dicetak langsung dan tidak harus diunduh dulu untuk dicetak. Ini bisa menjadi tantangan bagi pakar2 kita @fusionid @afa28 @agungsugiarto DKK.

**Comment by prastyawan** [comment]
saya sudah coba kembalikan dari versi sblmnya ke skrg, sudah saya ubah mulai dari surat.php, opensidhelper, tombolcetak, controller, database (setting_aplikasi), dll.
sudah bs muncul tombol cetak, namun ketika di klik cetak berhasil namun tdk muncul suratnya,,,
pdhal sudah saya sesuaikan direktori baru nya karena saya lihat berubah dari surat ke template-surat.

mohon untuk sdkit ksh clue kira2 dmnanya ya

**Comment by eddieridwan** [comment]
Maaf, pengembalian fitur itu tidak dalam rencana OpenSID. Jika anda membuat ubahan, akan mengunci desa anda pada versi ubahan anda, dan tidak dianjurkan. Kalau Kades memaksa, gunakan saja versi lama di mana versi itu masih ada. Tetapi jauh lebih baik memberi pengertian pada Kades anda mengapa fitur cetak langsung yg lama bukan solusi yg baik. Dengan fitur cetak langsung yg lama, surat yg dihasilkan tidak bisa disimpan di arsip surat, dan template surat hanya bisa diubah oleh programmer, termasuk membuat template surat baru. Jadi kalau bersikeras menggunakan desa perlu bersedia membayar programmer dan juga bersedia terkunci pada versi lama atau ubahan itu. Sekali lagi, tidak dianjurkan, dan bukan penggunaan waktu maupun anggaran desa yg baik.

**Comment by prastyawan** [comment]
Saya sebelumnya jg membuat ubahan sesuai dengan kebutuhan desa pak, ketika update alhamdulillah masih bs mengikuti dengan memanfaatkan commit di github, melihat file update dan selanjutnya baru ke database.
namun ini untuk tombol cetak saya mohon info saja dimanakah agar bs tampil suratnya,soalnya sudah selesai saya combine dgn versi sblmnya hnya ketika klik CETAK hanya blank sprti tdk terbaca suratnya, pdhal di logs tdk ada error, saya yakin ada yang kurang.

**Comment by eddieridwan** [comment]
@prastyawan silakan anda lakukan, jika memang berminat. Tapi sekali lagi maaf, karena apa yg anda lakukan bukan sesuatu yg kami anggap penggunaan waktu yg baik, kami tidak dapat membantu. Masih banyak sekali tugas/permintaan lain yg jauh lebih berprioritas. Alangkah baiknya kalau anda menggunakan tenaga dan keahlian anda untuk mengerjakan yg kami usulkan di atas: yaitu mencari cara supaya surat Ekspor Dok (format RTF) bisa dicetak langsung. Kalau anda lakukan ini tentunya kebutuhan kades anda juga akan terjawab.

**Comment by eddieridwan** [comment]
Sebenarnya fitur supaya Ekspor Dok menghasilkan PDF (bukan RTF) sudah ada sejak lama. Tapi sekarang di rilis Premium telah disediakan opsi yg bisa digunakan oleh desa yg hostingnya tidak memiliki akses pengguna root. Panduannya ada di https://github.com/OpenSID/OpenSID/wiki/Cetak-Surat#mengaktifkan-fitur-cetak-ke-pdf.

Jadi jika menggunakan browser seperti Firefox, surat PDF tersebut bisa ditampilkan langsung di browser. Jika menggunakan Chrome harus ditambah extension untuk menampilkan PDF di browser.

Ok, issue ini akan ditutup.
