### ISSUE TITLE
PENYESUAIAN MENU DATA COVID DESA 

### ISSUE THREAD

**Issue by M-A-Haris** [OpenSID/OpenSID#4012]
<!--
PENYSEYAUAN MENU DATA COVID DESA 

### data yang ditampilkan, lebih sederhana hanya menampilkan data, , Positif,  Meninggal dan Sembuh?

###, perubahan menu pendataan covid tidak pada sasaran pemudik, tapi  pada melaporkan hasil swab dan tracking yang dilakukan oleh petugas kesehatan.

**Comment by Nurhidayat29** [comment]
tolong lampirkan foto atau sumber tentang issue ini pak, agar programer lebih mudah memahami dan mengerjakan issuenya

**Comment by M-A-Haris** [comment]
Pengisian data covid desa dan tampilan lebih disederhanakan mengikuti pusat. Cukup menampilkan kolom  jumlah Positif, Sembuh 
dan Meninggall. (Kolom vaksinasi jika dibutuhkan menyongsong pemberlakuan vaksin covid)
![Uploading data_covid_desa_opensid.jpg…]()

**Comment by Nurhidayat29** [comment]
gambar ndak bsa dbuka
