### ISSUE TITLE
penambahan fitur Pajak Bumi dan Bangunan

### ISSUE THREAD

**Issue by ekkykyel** [OpenSID/OpenSID#4013]
### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by ekkykyel** [comment]
kalau bisa penambahan fitur pajak bumi dan bangunan

**Comment by eddieridwan** [comment]
@ekkykyel 

Modul PBB sudah tersedia bagi pelanggan premium. 
Demo ada di http://pbb.opensid.my.id/. 
user : admin
pass : admin_pbb

Info untuk berlangganan fitur premium ada di https://www.opendesa.id/mengonlinekan-opensid/.
