### ISSUE TITLE
[Statistik] Dokumen kependudukan

### ISSUE THREAD

**Issue by Selvianuswaka** [OpenSID/OpenSID#4014]
### Informasi tambahan 
Sekedar usulan untuk rilis berikut kalau bisa ada statistik dokumen kependudukan,sehingga ini bisa membantu kami untuk mengetahui jumlah warga yang sudah memiliki dokumen kependudukan <!-

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by andifahruddinakas** [comment]
Duplicate issue https://github.com/OpenSID/OpenSID/issues/5211
