### ISSUE TITLE
[Layanan Mandiri] Pembuatan PIN layanan mandiri secara kolektif

### ISSUE THREAD

**Issue by rudiansyahyunanda** [OpenSID/OpenSID#4015]
### Bagaimana alurnya sampai muncul masalah?
terlalu sulit untuk membuat PIN Layanan Mandiri warga manual satu persatu. apalagi dengan jumlah penduduk yang banyak

### Seperti apa yang diharapkan?
dibuatkan sebuah sistem yang dapat membuat PIN default secara masal dan dapat mencetak PIN secara masal untuk masing-masing penduduk bahkan jika memungkinkan terdapat opsi pilih beberapa PIN sesuai kebutuhan yang akan dicetak . tujuannya hasil cetak PIN tersebut untuk disampaikan kewarga-warga berdasarkan identitas masing-masing atau 1 keluarga secara kolektif dalam 1 surat, hal ini tentunya sebagai upaya jemput bola kepada masyarakat untuk menggunakan layanan mandiri. karena pada prinsipnya banyak masyarakat yang belum tahu akan perkembangan teknologi dan kemudahan dalam memanfaatkannya 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Strategi pembuatan PIN massal bukan yg terbaik bagi warga. Warga perlu diberikan pencerahan bukan saja terkait PIN, tetapi juga layanan apa yg mereka dapat peroleh, apa syarat yg perlu mereka penuhi untuk mendapatkan layanan, dan apa tanggung jawab mereka mengamankan data mereka dan data desa. Selain itu, kantor desa perlu memastikan warga ybs betul2 ada dan sesuai dengan kartu identitas mereka. 

Keamanan dan privasi data merupakan faktor yg perlu diutamakan dan jalan pintas sekadar untuk memudahkan tetap perlu mempertimbangkan faktor itu. 

Idealnya kantor desa mengadakan kegiatan rutin terbuka bagi warga yg berminat menggunakan layanan mandiri, untuk memberi pencerahan dan pengarahan -- dan memberikan akses/PIN pada acara itu.

**Comment by eddieridwan** [comment]
Issue ini akan ditutup, karena tidak akan diterapkan dalam bentuk yg diusulkan.
