### ISSUE TITLE
[Bumindes] Mohon disediakan tombol Cetak di Buku Buku Agenda

### ISSUE THREAD

**Issue by skdrt** [OpenSID/OpenSID#4016]
![PrintSurat](https://user-images.githubusercontent.com/78517311/108015294-e9f57300-704a-11eb-8d2f-d2476281b9f5.png)

### Bagaimana alurnya sampai muncul masalah?
Ketika melihat Surat surat yang ada di Buku Induk, untuk yang offline, sebenarnya file file tersebut kan tersedia secara langsung di Komputer, jadi tombol download sebenarnya cukup Mubazier.

### Seperti apa yang diharapkan?
Sebaiknya disediakan juga tombol cetak bagi dokumen dokumen terkait

### Apa yang terjadi?
Saat ini ketika membutuhkan salinan surat yang dimaksud, kita masih harus download manual

### Informasi tambahan 
Terima Kasih

Julis Suryadi
Operator OpenSID Sekolaq Darat
| Tanya            | Jawab
| --------------| ---
| Versi OpenSID    | 21.02-premium-pasca
| Versi PHP        | PHP Version 7.4.8
| System operasi   | Windows 10 Pro

**Comment by eddieridwan** [comment]
@skdrt , tidak anjurkan pengguna langsung mengakses file. Tentunya yg menggunakan di hosting akan terkendala mengakses file langsung.

Fitur mencetak surat RTF langsung terkait juga dengan issue https://github.com/OpenSID/OpenSID/issues/4011. Yaitu yg diperlukan adalah fitur untuk mencetak surat dalam format RTF secara langsung tanpa perlu diunduh dulu.

**Comment by redjoel** [comment]
> @skdrt , tidak dianjurkan pengguna langsung mengakses file di instalasi OpenSID, termasuk yg di folder desa. Tentunya yg menggunakan di hosting akan terkendala mengakses file langsung.
> 
> Fitur mencetak surat RTF langsung terkait juga dengan issue #4011. Yaitu yg diperlukan adalah fitur untuk mencetak surat dalam format RTF secara langsung tanpa perlu diunduh dulu.
> 
> Perhatikan bahwa surat RTF yg tersimpan di arsip layanan bukan versi yg telah ditandatangan basah -- melainkan versi surat yg dihasilkan sistem. Demikian juga versi yg dicetak dari surat RTF tersebut.

Halo pak, nampaknya yg bapak maksudkan bukan yg kami tanya. ini di back end kan? Tidak bisa diakses oleh sembarang orang. Hanya user yang login saja.


Daripada tombol unduh, mungkin lebih baik kalau disediakan tombol cetak ;)
Itu maksud kami disini

**Comment by eddieridwan** [comment]
> Daripada tombol unduh, mungkin lebih baik kalau disediakan tombol cetak ;)
> Itu maksud kami disini

Mengerti maksud teman2.

Tetapi di Arsip Layanan, tombol unduh akan tetap diperlukan, karena ada desa yg mengubah surat yg dihasilkan sistem (menggunakan MS Word) sebelum dicetak. Untuk disediakan tombol cetak langsung, adalah tantangan teknis lumayan besar, karena RTF kelolaan Microsoft sulit dicari library open source yg bisa menampilkan. Mudah2an @fusionid @afa28 @agungsugiarto dkk akan tertantang dan berhasil mencari solusinya.

**Comment by afa28** [comment]
Mas @agungsugiarto
