### ISSUE TITLE
[Komentar] Belum Bisa Interaksi Pada Komentar Artikel

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#4017]
### Bagaimana alurnya sampai muncul masalah?
Saat ini, walaupun ada yang ditambahkan komentar Facebook atau Disqus,
namun secara default ada Menu Komentar yang tersedia di OpenSID.

Alih-alih komentar atas artikel yang masuk, hanya sebatas moderasi Tampilkan atau Tidak.
![IMG_20220526_104614](https://user-images.githubusercontent.com/46939846/170411949-d47788c7-6fb1-44e7-9fdc-68aced45fa6e.png)

belum ada kolom atau fitur balasan/respons untuk setiap Komentar.

### Seperti apa yang diharapkan?
Adanya interaksi antara pengunjung dengan pengelola web baik admin/operator/kontributor/redaksi.
Interaksi dapat berupa balasan komentar, maupun respons karakter.

### Apa yang terjadi?
Agar website dapat "hidup" oleh pengunjung.

**Comment by HerryWanda** [comment]
betul pak afiandi..
saya klo balas komentar, buka link webnya, kemudian di komentar juga seperri pengunjung membuat komentar..

**Comment by afa28** [comment]
Catatan pak @eddieridwan yg pernah sy PR mengenai issue ini : 
1. Pisahkan table mail_box dan komentar

**Comment by andifahruddinakas** [comment]
Pak @ariandii, issue ini masih diperlukan.

**Comment by andifahruddinakas** [comment]
Agar issue terupdate, issue ini ditutup dan digantikan oleh issue https://github.com/OpenSID/OpenSID/issues/5283
