### ISSUE TITLE
[Artikel] Pengelompokan Halaman Artikel Statis

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#4018]
### Bagaimana alurnya sampai muncul masalah?
Saat ini untuk pengelompokan Artikel Statis ada 3: yaitu Halaman Statis, Agenda dan Keuangan. Namun, di website belum bisa menampilkan 1 Kelompok Artikel tersebut. seperti halnya Kategori Artikel.

Hal ini terjadi saat awalnya Membuat seluruh Artikel Keuangan di dalam Kategori bernama "APBDesa", maka artikel keuangan tersebut bisa ditampilkan dalam 1 kategoti.

Namun, saat semua dipindah ke Artikel Statis Keuangan, ternyata tidak dapat menampilkan Halaman Khusus artikel jenis Keuangan.

### Seperti apa yang diharapkan?
Adanya tambahan Jenis Link Artikel Statis Keuangan/Agenda/StatisLainnya pada Menu untuk Pengelompokan Artikel Statis seperti Kategori Artikel.

### Apa yang terjadi?
Agar mudah dalam menampilkan suatu kategori statis.

**Comment by andifahruddinakas** [comment]
Pak @ariandii, issue ini masih diperlukan.
