### ISSUE TITLE
Font Email Di biodata/cetak biodata huruf besar semua

### ISSUE THREAD

**Issue by suyatno52** [OpenSID/OpenSID#4019]
### Seperti apa yang diharapkan?
yg diharapkan sesuai email yg di tuliskan di pengisian penduduk from

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by suyatno52** [comment]
![2021-02-18_14h47_25](https://user-images.githubusercontent.com/68505964/108323539-62019b80-71f9-11eb-90b8-b8a2485ad71f.png)
![2021-02-18_14h50_03](https://user-images.githubusercontent.com/68505964/108323557-6928a980-71f9-11eb-9bd0-63847d25c2a1.png)

**Comment by suyatno52** [comment]
![2021-02-18_15h00_19](https://user-images.githubusercontent.com/68505964/108324258-3e8b2080-71fa-11eb-929a-625bfdf8ffe1.png)

**Comment by Nurhidayat29** [comment]
sepertinya itu tidak masalah bung, besar ataupun kecil

**Comment by suyatno52** [comment]
Ok pak dah di respon
Trimksih

Pada tanggal Jum, 5 Mar 2021 23.09, Nur Hidayat <notifications@github.com>
menulis:
