### ISSUE TITLE
Tidak bisa memili Lokasi Pada Pengaturan Data Pembangunan untuk desa yang hanya memiliki dusun dan tidak memiliki RT RW

### ISSUE THREAD

**Issue by ai-skematik** [OpenSID/OpenSID#4020]
### Bagaimana alurnya sampai muncul masalah?
Tidak bisa memilih Lokasi Pada Pengaturan Data Pembangunan dan Pengelolaan Data Persil untuk desa yang hanya memiliki dusun dan tidak memiliki RT RW

### Seperti apa yang diharapkan?
Dapat menambahkan lokasi seperti desa yang memiliki rt/rw

### Apa yang terjadi?
mengisi lokasi hanya dapat dilakukan secara manual

### Informasi tambahan 
![bug](https://user-images.githubusercontent.com/48144047/108341003-2c1de080-7214-11eb-82c2-7bf6430d89f1.png)

![bug2](https://user-images.githubusercontent.com/48144047/108341102-49eb4580-7214-11eb-97a7-c841baac0236.png)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 21.02-permium-pasca
| Versi PHP        | 
| System operasi   |

**Comment by agungsugiarto** [comment]
Pak @ai-skematik, terima kasih sudah melaporkan issue.
Harap ketika membuat issue fokus pada satu issue saja. Untuk issue terkait modul persil silahkan dibuatkan issue terpisah. Terima kasih.

**Comment by ai-skematik** [comment]
terima kasih.

**Comment by eddieridwan** [comment]
Sdh dicommit ke `rilis-dev` melalui https://github.com/OpenSID/premium/pull/126
