### ISSUE TITLE
Kembalikan gambar galery yang di tampilkan di slider web hanya yang aktif saja menjadi nonaktif

### ISSUE THREAD

**Issue by fajarkurnia** [OpenSID/OpenSID#4021]
### Bagaimana alurnya sampai muncul masalah?
Pada saat memilih galery yang ingin di tampilkan pada slider website, album pada daftar album tidak dapat di non-aktifkan, sehingga juga ikut muncul di widget galery.

![Penemuan masalah galery slider](https://user-images.githubusercontent.com/68980771/108359323-71e1a580-7222-11eb-9c73-c5ba04304d17.png)

![Penemuan masalah  galery slider1](https://user-images.githubusercontent.com/68980771/108359448-99387280-7222-11eb-82f4-23da364f8eae.png)

### Seperti apa yang diharapkan?
Kembalikan pengaturan galery seperti pada versi 20.8, agar galery slider tidak muncul juga di widget galery.

### Apa yang terjadi?
Gambar di widget galery jadi tidak responsive.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 21.2
| Versi PHP        | 7.4
| System operasi   | windows

**Comment by afa28** [comment]
Slider yg ditampilkan dr album galery merupakan galery yg aktif.

**Comment by afa28** [comment]
Slider yg ditampilkan dr album galery merupakan galery yg aktif. Silahkan di buka kembali jika masih bermasalah.
