### ISSUE TITLE
Error Tampilkan DPT pada Halaman Website

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#4023]
### Bagaimana alurnya sampai muncul masalah?
Saat menu DPT diaktifkan, kemudian akses link:
https://berputar.opensid.my.id/first/dpt

Maka muncul keterangan:
This page isn’t workingberputar.opensid.my.id is currently unable to handle this request.
HTTP ERROR 500

### Seperti apa yang diharapkan?
Normal sebagaimana mestinya.

### Apa yang terjadi?
Agar pengunjung web dapat melihat DPT

**Comment by eddieridwan** [comment]
Sdh dicommit ke `rilis-dev`.
Tapi baru solusi sementara. Perlu ditelurusi lebih lanjut adanya query menggantung dalam/sebelum pemanggilan first/web.
