### ISSUE TITLE
Menampilkan Jenis Bantuan yang diperoleh

### ISSUE THREAD

**Issue by rudiansyahyunanda** [OpenSID/OpenSID#4025]
### Bagaimana alurnya sampai muncul masalah?
Saat membuka menu statistik> Statistik Kependudukan>Statistik Program Bantuan>Penerima Bantuan Keluarga. 

Tidak ada informasi Jenis Bantuan yang diterima

### Seperti apa yang diharapkan?
Ketika di klik pada bagian jumlah PENERIMA muncul data Penerima beserta jenis bantuan apa saja yang ia peroleh.

### Apa yang terjadi?
Ini akan sangat membantu dalam memilah data yang berkaitan dengan program bantuan lainnya.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
Langkah : 
1. Buka Statistik > Statistik Kependudukan > Program Bantuan Keluarga
2. Klik Penerima pada bagian jumlah/laki2/perempuan, maka akan dialihkan ke modul keluarga penerima bantuan tsb.
3. Buka salah satu data keluarga tsb, akan tampil bantuan sasaran keluarga apa sj yg diperloeh.

![1111111](https://user-images.githubusercontent.com/57283157/112662888-c95edb00-8e8a-11eb-84fe-af1c9cafe4e5.png)

**Comment by agungsugiarto** [comment]
Pak @rudiansyahyunanda issue ini saya tutup. Issue hanya ditujukan untuk melaporkan bug / permintaan fitur. Untuk mengetahui informasi bantuan yg diterima silahkan lakukan intruksi seperti yg dibilang mas @afa28. Jika masih kurang jelas silahkan bertanya di group facebook atau di telegram. Terima kasih
