### ISSUE TITLE
Data kelompok Di Menu Kependudukan Tidak Bisa di Cetak dan Diunduh

### ISSUE THREAD

**Issue by luxmant354** [OpenSID/OpenSID#4026]
### Bagaimana alurnya sampai muncul masalah?

Data Kelompok di Menu Kependudukan Tidak Bisa dicetak dan diunduh
![Screenshot_2](https://user-images.githubusercontent.com/44687953/108711833-7ec70780-7548-11eb-8e74-05a094472147.jpg)

![Screenshot_5](https://user-images.githubusercontent.com/44687953/108711851-8686ac00-7548-11eb-8063-c836a61e0902.jpg)

### Seperti apa yang diharapkan?
Data Bisa dicetak dan diunduh, seperti data yang lainnya

### Apa yang terjadi?
sepertinya perlu adanya perbaikan di, donjo-app/controllers/Kelompok.php 
dibaris 56 $this->load->model(['kelompok_model', 'referensi_model']);	
diganti 
$this->load->model(['kelompok_model', 'pamong_model']);

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by Zulkarnaimni** [comment]
Tempat Penanda Tangan juga belum link sesuai dengan pemangku jabatan di Desa
![image](https://user-images.githubusercontent.com/64481641/108735264-e9853c80-7562-11eb-8812-62885017522b.png)

**Comment by luxmant354** [comment]
Ok, skr sudah normal kembali 👌
