### ISSUE TITLE
[Keuangan] Manual Input Data Anggaran dan Realisasi APBDes (Nilai akhir angka dibelakng koma (,) tidak terbaca)

### ISSUE THREAD

**Issue by R4HMAT** [OpenSID/OpenSID#4027]
### Bagaimana alurnya sampai muncul masalah?
Ketika saya input data di menu keuangan input manual untuk di laporannya tidak terbaca angka yang akhirannya dibelakang koma (,) dua tidak bisa terbaca dan biasanya pada anggaran bunga bank atau sisa keuangan desa ada nya angka yang dibelakangnya dua angka 
![photo_2021-02-24_23-20-10](https://user-images.githubusercontent.com/43318683/109025859-13249c00-76fa-11eb-97c3-80e326cbd32d.jpg)

hasil laporan nilai tidak bisa terbaca
![photo_2021-02-24_23-22-16](https://user-images.githubusercontent.com/43318683/109025920-25063f00-76fa-11eb-9799-c60ab3687cfc.jpg)

contohnya : besar angkanya Rp.  2.284.196,26

(Dua milyar dua ratus delapan puluh empat juta seratus sembilan puluh enam ribu dua puluh enam)

### Seperti apa yang diharapkan?

untuk keuangan desa input manual di tambahkan digit yang ada nilainya didepan koma bisa terbaca.

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 21.2
| Versi PHP        | 
| System operasi   |

**Comment by fusionid** [comment]
Sesuai dengan PMK nomor 250/PMK.05/2010, pasal 2, yang menyatakan "Pembayaran pengeluaran negara dilakukan dengan menggunakan mata uang Rupiah dan ditulis dalam angka Rupiah penuh tanpa angka sen dibelakang koma".

Untuk kasus diatas -> Rp. 2.284.196,26 dibulatkan menjadi Rp. 2.284.196,27
