### ISSUE TITLE
Data Kesehatan

### ISSUE THREAD

**Issue by afri18** [OpenSID/OpenSID#4028]
### Bagaimana alurnya sampai muncul masalah?
Terkait Pandemi Covid-19, yang saat ini pemerintah sedang melaksanakan VAKSINASI yang saya anggap sangat penting bagi DESA untuk mulai menyiapkan data di biodata PENDUDUK untuk data PERNAH berdampak atau BELUM, juga mendata siapa saja yang SUDAH atau BELUM di VAKSINASI COVID-19

### Seperti apa yang diharapkan?
Adanya DATA di Biodata Penduduk di menu KESEHATAN tentang Pendataan COVID-19 secara terinci
![image](https://user-images.githubusercontent.com/6611881/109092883-f87a1380-7749-11eb-86f3-109d03c201ec.png)
nantinya juga masuk dalam Statistik menu COVID-19

### Apa yang terjadi?
Saat ini tidak tersedia dibiodata penduduk rekaman kesehatan COVID-19 sebagai data desa.

### Informasi tambahan
Akan membuat OPENSID lebih dari YANG LAIN 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 21.02
| Versi PHP        | 7
| System operasi   | CPanel

**Comment by Zulkarnaimni** [comment]
Mungkin barangkali vaksinasi untuk covid ada beberapa kali, yg berjalan saat ini 2 kali vaksin, setelah vaksin pertama dilakukan 14 hari kemudian ada vaksinasi tahap ke-2......

**Comment by andifahruddinakas** [comment]
Bisa gunakan data suplemen.
