### ISSUE TITLE
Tulisan informasi batas maximal upload file pada layanan mandiri

### ISSUE THREAD

**Issue by linggacm** [OpenSID/OpenSID#4029]
### Bagaimana alurnya sampai muncul masalah?
biar tau informasi mengenai batas maximal ukuran file upload, soalnya saat upload lewat kamera dapat notif kebesaran file karena tidak tau batas ukurannya berapa

### Seperti apa yang diharapkan?
biar menu upload layanan mandiri ada informasi tulisan batas maximal file upload, misal 5MB 

### Apa yang terjadi?
pengguna/warga mengetahui bahwa harus disesuaikan dulu file nya sebelum diapload

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 21.02
| Versi PHP        | 7.4
| System operasi   | Windows 10 64bit

**Comment by eddieridwan** [comment]
Sdh dicommit ke `rilis-dev` melalui https://github.com/OpenSID/premium/pull/119
