### ISSUE TITLE
Data Kelahiran Baru Bulan ini Masuk ke Data Jumlah KK, sehingga jumlah KK bulan ini bertambah satu KK seharusnya tidak ada penambahan KK

### ISSUE THREAD

**Issue by Zulkarnaimni** [OpenSID/OpenSID#4030]
Data Kelahiran Baru "Bayi Laki-laki" Bulan ini Masuk ke Data Jumlah KK bulan ini, sehingga jumlah KK bulan ini bertambah satu KK lagi di dalam laporan. 

### Bagaimana alurnya sampai muncul masalah?

![image](https://user-images.githubusercontent.com/64481641/109177048-fc457e80-77b9-11eb-86d0-a751df479491.png)
![image](https://user-images.githubusercontent.com/64481641/109177350-47f82800-77ba-11eb-805e-62730b85f9d9.png)

### Seperti apa yang diharapkan?
Data Warga yang kalahiran baru tidak masuk ke rekapitulasi jumlah KK

### Apa yang terjadi?
Jumlah KK tetap seperti jumlah KK yang sudah terdata bila tidak ada penambahan KK

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 21.02 Premium
| Versi PHP        | 
| System operasi   | Hosting

**Comment by eddieridwan** [comment]
@Zulkarnaimni , sepertinya ini terjadi karena memilih Tambah KK Baru > Tambah Penduduk Lahir. Seharusnya pilihan ini tidak ada. Seharusnya menggunakan Tambah Anggota Keluaga > Tambah Penduduk Lahir.

Pilihan ini sudah dihapus. Sdh dicommit ke `rilis-dev`.

**Comment by Zulkarnaimni** [comment]
Oke Pak Eddie, Makasih atas informasinya…


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
