### ISSUE TITLE
Eror proses backup Database Folder desa yang besar ,membutuhkan lebih dari 512

### ISSUE THREAD

**Issue by merbau** [OpenSID/OpenSID#4032]
Harap diisi hanya untuk melaporakn bug atau permintaan penambahan fitur saja. Jika ada pertanyaan dukungan komunitas OpenSID sebaiknya posting di grup Facebook: https://www.facebook.com/groups/opensid

### Bagaimana alurnya sampai muncul masalah?
proses backup Database Folder desa yang besar ,membutuhkan lebih dari 512 MB
 karena beberapa desa juga mengalami spt itu, kecuali yang menggunakan VPS

berikut gambar logs nya : 

![Screenshot_16](https://user-images.githubusercontent.com/71330402/109417179-1c14b680-79f5-11eb-8a7d-a9bd26d3651d.png)

### Seperti apa yang diharapkan?

Perlu Penambahan memorymemory php membutuhkan lebih dari 512 MB
![photo_2021-02-28_18-04-15](https://user-images.githubusercontent.com/71330402/109417257-685ff680-79f5-11eb-93a8-0111a641abed.jpg)

### Informasi tambahan 

| Versi OpenSID 
| Versi PHP 
| System operasi

**Comment by agungsugiarto** [comment]
Terkait #3725

**Comment by afa28** [comment]
Harap diisi hanya untuk melaporakn bug atau permintaan penambahan fitur saja. Jika ada pertanyaan dukungan komunitas OpenSID sebaiknya posting di grup Facebook: https://www.facebook.com/groups/opensid
