### ISSUE TITLE
GAGAL Migrasi Database Pada OpenSID 21.02-pasca terkini (Rilis Umum)

### ISSUE THREAD

**Issue by PWidodo** [OpenSID/OpenSID#4033]
### Bagaimana alurnya sampai muncul masalah?
Setelah Update versi 21.02-pasca per tanggal 26 sampai 28 hari ini ternyata selalu GAGAL untuk migrasi databasenya. Hal ini telah saya coba di https://demo.opensid.or.id/ hasilnya "GAGAL" dicoba di housting maupun localhost juga gagal.

### Seperti apa yang diharapkan?
Harap untuk diperbaiki BUG tersebut. 

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 21.02-pasca terkini
| Versi PHP        | 7.4 alt
| System operasi   | Windows 10

**Comment by eddieridwan** [comment]
@PWidodo ini hanya karena tampilan status keberhasilan yg keliru. Proses migrasinya sendiri tidak bermasalah. Sudah diperbaiki di `master`.
