### ISSUE TITLE
Tampilkan Notifikasi Masa Berlangganan di Header Admin

### ISSUE THREAD

**Issue by rudiansyahyunanda** [OpenSID/OpenSID#4036]
### Bagaimana alurnya sampai muncul masalah?
- Pada dasarnya kita jarang sekali membuka fitur status berlangganan, kalaupun dibuka kita juga jarang sekali memperhatikan sisa masa berlangganan. Sehingga akibat kelalaian tersebut berdampak terhadap ketidak tersediaan dana untuk membayar pada saat sudah berakhir masa berlangganan.

### Seperti apa yang diharapkan?
Dibuat Notifikasi seperti Microsoft Office yang belum diaktivasi. Pada bagian header panel admin berubah menjadi warnah merah dengan menampilkan info jatuh tempo. Notifikasi ini muncul 1 bulan sebelum masa berlangganan habis.

### Apa yang terjadi?
Para pengguna dapat mempersiapkan biaya untuk berlangganan jauh hari. secara spontan dengan notifikasi atau bagian header dengan warna yang mencolok dan ditambah keterangan akan berakhirnya limit berlangganan membuat pengguna akan berusaha sesegera mungkin untuk memperpanjang biaya langganan.

### Informasi tambahan 
Keterlambatan berlangganan tidak hanya karena persoalan tidak tersedianya anggaran. Melainkan karena lupa.

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sdh dicommit ke `rilis-dev` untuk status langganan fitur premium.
