### ISSUE TITLE
[Layanan Mandiri] : Sediakan fitur Kepuasan Pelayanan Saat Selesai menggunakan layanan mandiri

### ISSUE THREAD

**Issue by rudiansyahyunanda** [OpenSID/OpenSID#4037]
### Seperti apa yang diharapkan?
Saat selesai menggunakan layanan mandiri muncul sebuah dialog yang meminta untuk memberikan rating kepuasan atas pelayanan yang diberikan (Sangat Puas, Puas, Cukup, Buruk)

### Apa yang terjadi?
Desa dapat mengukur sejauh mana pelayanan yang diberikan.

### Informasi tambahan 
Rating yang diberikan tersimpan kedalam database. 

Didashboard admin mungkin bisa ditempatkan pada menu Layanan Mandiri dengan nama "Rating Layanan".

Laporan yang diperlukan 
1. Nama Bulan +Tahun
2. Jumlah Rating untuk masing-masing rating (Sangat Puas, Puas, Cukup, Buruk)
3. Statistik Kunjungan dalam 1 bulan

Jika memungkinkan dapat juga direkap dalam openDK sebagai tingkat kepuasan 1 kecamatan.

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Tidak anonim. Dan tindak lanjut dengan menghubungi pihak yg memberi peniliaian.

**Comment by afa28** [comment]
![1222222](https://user-images.githubusercontent.com/57283157/117612023-b54b1080-b18e-11eb-93d8-cfe68d223efd.png)

Mas @rudiansyahyunanda, untuk fitur kepuasan ini apakah disimpan setiap selesai menggunakan layanan mandiri, atau hanya 1 hari sekali/ pengguna, atau lainnya???

**Comment by eddieridwan** [comment]
@afa28 :

1. Sebaiknya ditanyakan setiap selesai menggunakan Layanan Mandiri. Tapi juga sediakan pilihan `Lain Kali` supaya pengguna tidak diharuskan mengisi. 
2. Di Admin > Layanan Mandiri > Pendapat, sediakan fitur di mana jika ikon/grafik di-klik akan menampilkan daftar pendapat sesuai dengan tingkat kepuasan yg dipilih. Urut tanggal.

**Comment by eddieridwan** [comment]
Sdh dicommit ke `rilis-dev` melalui https://github.com/OpenSID/premium/pull/218
