### ISSUE TITLE
Sediakan menu Peraturan Kepala Desa

### ISSUE THREAD

**Issue by ananghasan** [OpenSID/OpenSID#4038]
### Bagaimana alurnya sampai muncul masalah?
Tidak ada fasilitas menyimpan dokumen peraturan Kepala Desa

### Seperti apa yang diharapkan?
Tersedianya fasilitas (menu) Peraturan Kepala Desa di buku administrasi umum

### Apa yang terjadi?
OpenSid menjadi sarana penyimpanan data yang komplit dan terintegrasi

### Informasi tambahan 
Fasilitaa serupa yang sudah tersedia adalah Peraturan Desa dan Keputusan Kepala Desa

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
@ananghasan sdh tersedia di rilis Premium. Bisa diperiksa di https://berputar.opensid.or.id.
Info berlangganan Premium ada di https://opendesa.id/mengonlinekan-opensid/

![perkades](https://user-images.githubusercontent.com/249563/109568548-2e990800-7b3b-11eb-9813-6baf71263b55.jpg)

Bung @Nurhidayat29 , mohon ditambahkan ke panduan wiki. Terima kasih.

**Comment by volla15** [comment]
![image](https://user-images.githubusercontent.com/53460521/158349048-5dafd150-5ead-43ea-9db7-ccf67033d1cc.png)
mohon ditambahkan menu Perkades baik di dalam tampilan produk hukum maupun di buku peraturan desa (tidak jadi satu dengan peraturan desa)

**Comment by volla15** [comment]
> @ananghasan sdh tersedia di rilis Premium. Bisa diperiksa di https://berputar.opensid.or.id. Info berlangganan Premium ada di https://opendesa.id/mengonlinekan-opensid/
> 
> ![perkades](https://user-images.githubusercontent.com/249563/109568548-2e990800-7b3b-11eb-9813-6baf71263b55.jpg)
> 
> Bung @Nurhidayat29 , mohon ditambahkan ke panduan wiki. Terima kasih.

![image](https://user-images.githubusercontent.com/53460521/158349048-5dafd150-5ead-43ea-9db7-ccf67033d1cc.png)
mohon ditambahkan menu Perkades baik di dalam tampilan produk hukum maupun di buku peraturan desa (tidak jadi satu dengan peraturan desa)
