### ISSUE TITLE
Cetak Peta Muncul 2 Tombol yang Sama.

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#4039]
### Bagaimana alurnya sampai muncul masalah?
Ada 2 tombol cetak, dikira berbeda. ternyata sama fungsi.
<img width="960" alt="2021-03-01_21h10_22" src="https://user-images.githubusercontent.com/46939846/109508649-a717ae80-7ad2-11eb-9797-f78f23b75552.png">

### Seperti apa yang diharapkan?
Sesuaikan dengan kebutuhan.

### Apa yang terjadi?
Agar tidak

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR https://github.com/OpenSID/OpenSID/pull/4042
