### ISSUE TITLE
Penginput Data Penduduk tidak Terekam

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#4040]
### Bagaimana alurnya sampai muncul masalah?
Saat ini coba di berputar.opendesa.id input penduduk pendatang sukses namun Operator yang input tidak terekam.
<img width="960" alt="2021-03-01_23h24_35" src="https://user-images.githubusercontent.com/46939846/109526648-62e1d980-7ae5-11eb-8616-83ae85ab7f07.png">

### Seperti apa yang diharapkan?
Muncul nama si penginput.

### Apa yang terjadi?
Normal sebagaimana mestinya.

**Comment by eddieridwan** [comment]
Sdh dicommit ke `rilis-dev` melalui https://github.com/OpenSID/premium/pull/109
