### ISSUE TITLE
Input KK Baru Terekam Tapi Tidak Tampil

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#4041]
### Bagaimana alurnya sampai muncul masalah?
Saat ingin menambah KK Baru berdasarkan "Tambah Penduduk Masuk", proses sukses. KK masuk database, tetapi NIK Kepala Keluarga 0. (padahal sudah diisi). yang mengakibatkan input ulang KK menjadi gagal dengan keterangan No KK sudah terdaftar. Sebagaimana tampil gambar di bawah ini.

<img width="432" alt="2021-03-02_13h52_48" src="https://user-images.githubusercontent.com/46939846/109609972-b3494d80-7b5e-11eb-8667-2b0e3e6f6d52.png">

### Seperti apa yang diharapkan?
Normal sebagaimana mestinya.

### Apa yang terjadi?
Agar input KK berdasarkan Penduduk Baru dapat berjalan lancar.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sdh dicommit ke `rilis-dev` melalui https://github.com/OpenSID/premium/pull/109
