### ISSUE TITLE
cetak biodata di layanan mandiri logo dan identitas desa tidak muncul

### ISSUE THREAD

**Issue by suyatno52** [OpenSID/OpenSID#4043]
### Seperti apa yang diharapkan?
normal seperti versi sebelumnya
![2021-03-03_01h15_10](https://user-images.githubusercontent.com/68505964/109695358-62694180-7bbe-11eb-859f-158e745382a5.png)
![2021-03-03_01h16_37](https://user-images.githubusercontent.com/68505964/109695386-6ac17c80-7bbe-11eb-8484-e5ac1e1ed86c.png)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui https://github.com/OpenSID/OpenSID/pull/4044

**Comment by suyatno52** [comment]
Ok pak, trimakasih

Pada tanggal Jum, 5 Mar 2021 10.24, Eddie Ridwan <notifications@github.com>
menulis:
