### ISSUE TITLE
Petugas entri/edit data individu tidak menampilkan nama

### ISSUE THREAD

**Issue by WAHYUDIK** [OpenSID/OpenSID#4046]
### Bagaimana alurnya sampai muncul masalah?
ketika kita menambah data penduduk baru ataupun edit data, nama petugasnya tidak tampil
![image](https://user-images.githubusercontent.com/31026980/109916890-fb937780-7ce6-11eb-8bf9-0c64672c0190.png)
itu terjadi di demo.opensid.my.id dan juga berputar.opensid.my.id
### Seperti apa yang diharapkan?

nama petugasnya tampil lagi
![image](https://user-images.githubusercontent.com/31026980/109917017-339aba80-7ce7-11eb-8094-daa7ef047e6c.png)

### Apa yang terjadi?

saat ini tidak bisa tampil
### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Duplikat https://github.com/OpenSID/OpenSID/issues/4040
