### ISSUE TITLE
[Identitas Desa] Tidak Bisa Diubah Data Wilayah Jika Tidak Terkoneksi Internet (Premium)

### ISSUE THREAD

**Issue by afa28** [OpenSID/OpenSID#4048]
### Bagaimana alurnya sampai muncul masalah?
Untuk pengguna premium offine dan tidak terkoneksi ke internet tidak dapat mengubah data wilayah yang ada di identitas desa.

### Seperti apa yang diharapkan?
Sedikan ubah data manual agar bisa diubah walaupun tidak ada jaringan.

### Apa yang terjadi?
Dapat ubah data wilayaha di identitas desa.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 21.03-premium-pasca
| Versi PHP        | 7.4.1
| System operasi   | Windows 10 64 bit

**Comment by eddieridwan** [comment]
Sdh dicommit ke `rilis-dev`.

Tapi perhatikan masalah ini perlu ditinjau ulang, dengan merujuk pada hak dan kewajiban pelanggan premium. Misalnya, apakah pelanggan premium boleh menggunakan tanpa terkoneksi ke Layanan OpenDesa? Kalau boleh, apa saja syaratnya? Apakah kode desa/wilayah disediakan sebagai bagian dari token? Bagaimana mencegah penggunaan tanpa izin. Dstnya..
