### ISSUE TITLE
[Database] Kesalahan Tempat Import Data Penduduk Format Excel dan File SQL

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#4050]
### Bagaimana alurnya sampai muncul masalah?
Ada kalanya saat akan melalukan import data kependudukan melalui Menu : Pengaturan Database, ada banya istilah yang mirip di Menu tersebut.

1. Import Database, untuk import data excel dan data rumah tangga. Bagi pemula bisa dianggap itu adalah proses import keseluruhan data, karena menggunakan istilah database.
2. Backup / Restore, saat di klik, juga ada kata Database di sana, yakni Backup Database SID dan Restore Database SID. Bagi pemula bisa dianggap itu adalah proses mengembalikan data yang telah diunduh.

Sehingga, yang dilakukan saat ini adalah, proses import data Excel melalui menu Backup/Restore, sehingga mengakibatkan seluruh isi Database Hilang.

### Seperti apa yang diharapkan?
Adanya pembeda yang Khas, mana untuk hanya Data Penduduk, atau mana yang restore kelesuruhan.
Bisa diberi opsi khusus restore sql (karena mungkin ini jarang dilakukan) diberi kunci khusus misal password adanya tambahan password admin super.

### Apa yang terjadi?
Agar tidak ada kesalahan pemahaman proses import yang dilakukan pada 2 file yang tentunya beda peruntukan.

**Comment by afa28** [comment]
Apa sebaiknya di letakkan/dipindahkan ke modul penduduk(?), begitupun fungsi import/export excel lainnya.

Jadi pada modul database hanya untuk backup/restore database sj serta migrasi (u/ saat ini sdah otomatis).

**Comment by ariandii** [comment]
bisa jadi opsi juga pak.
tapi import data penduduk excel pun dilakukan diawal saja. atau beberapa kali setelah membangun opensid awal.

jika data sudah final, kedepan mereka tambah data 1 by 1 melalui menu penduduk.

jarang yang melakukan rutinitas melalui import data excel.

**Comment by andifahruddinakas** [comment]
Duplikasi issue https://github.com/OpenSID/OpenSID/issues/4995
