### ISSUE TITLE
[Statistik] Statistik Kepemilikan KIA (Kartu Identitas Anak)

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#4051]
### Bagaimana alurnya sampai muncul masalah?
Kepemilikan Identitas (KIA) untuk anak usia 0-16 tahun sudah bisa terekam didalam aplikasi, dan untuk mengetahui siapa saja yang sdh memiliki KIA belum bisa dilihat, sehingga mempersulit bagi pemerintah desa untuk mengetahui siapa yang belum dan siapa yang punya KIA
![Opera Snapshot_2021-03-06_001400_www rarangselatan desa id](https://user-images.githubusercontent.com/25834335/110143095-d2233a80-7e11-11eb-8242-b0bd20152362.png)

### Seperti apa yang diharapkan?
Perlu dibuatkan Statistik Kepemilikan KIA di Laporan Statistik Kependudukan seperti Kepemilikan KTP, Akta dan sejenisnya
![Opera Snapshot_2021-03-06_001929_www rarangselatan desa id](https://user-images.githubusercontent.com/25834335/110143011-b9b32000-7e11-11eb-9092-4da7a90176c2.png)

### Apa yang terjadi?
sulit bagi pemerintah desa untuk mengetahui siapa yang belum dan siapa yang punya KIA

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/OpenSID/pull/7591
