### ISSUE TITLE
[Statistik] Statistik Kepemilikan Buku NIkah

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#4052]
### Bagaimana alurnya sampai muncul masalah?
Ketika ingin melihat siapa saya warga masyarakat yang sdh memiliki buku nikah harus dilihat satu persatu, itupun harus melihat lewat salinan  KK, 
![nikah](https://user-images.githubusercontent.com/25834335/110143835-a2c0fd80-7e12-11eb-9023-83ead5e12c41.png)

### Seperti apa yang diharapkan?
Perlu diBuatkan Statistik Kepemilikan Buku NIKAH

### Apa yang terjadi?
Pemerintah Desa sulit untuk melihat siapa saja yang memiliki buku nikah

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/commit/e452c8c2afbae3e6d57a2ecaf3dc6faa93a37c79
