### ISSUE TITLE
Impor data survei Google Forms ke master analisis

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#4054]
### Bagaimana alurnya sampai muncul masalah?
Desa sering mengumpulkan data sosio-ekonomi warga menggunakan Google Form. 
Hasil survei tersebut perlu di-analisa. 
Diperlukan fitur supaya data yg terkumpul dapat diimpor ke dalam master analisis supaya dapat menggunakan fitur modul Analisis untuk evaluasi hasil survei.

### Seperti apa yang diharapkan?
1. Sediakan fitur untuk menyiapkan ketentuan/pengaturan untuk mengimpor data survei Google Form ke master analisis, yaitu membuat persamaan pertanyaan dan opsi pilihan ke dalam pertanyaan dan indikator di master analisis
2. Konversi data yg diekspor dari Google Form ke dalam format yg bisa diimpor ke master analisis
3. Buatkan panduan syarat survei Google Form supaya valid untuk diimpor ke master analisis

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | v20.03
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Fitur ini akan bermanfaat bagi desa untuk memasukkan data survei, seperti data SDGs yg sedang mereka lakukan. Contoh skenario penggunaan:
1. Buat google form untuk survei
2. Petugas mendatangi warga membawa tablet (atau HP) , supaya petugas bisa langsung wawancara warga dan mengisikan data survei ke google form
3. Setelah semua survei terisi, impor google form tersebut ke master analisis OpenSID.

Dengan skenario ini, penyiapan dan pengisian kertas fisik bisa dihindari. Form kertas tetap bisa digunakan sebagai backup atau kalau arsip fisik diperlukan.

**Comment by agungsugiarto** [comment]
Usulan perbaikan flow:
1. Otomatis ter-select sesuai tipe pertanyaan yang ada di google form.
![photo_2021-04-21_12-40-35](https://user-images.githubusercontent.com/10989147/115502567-5422d200-a29f-11eb-840d-d6e2ad01c0b9.jpg)
2. Perlu di sesuaikan jika ada penambahan data di google form tidak perlu mengulang ke langkah awal yaitu mengisisi data master. Cukup mengupdate di analis yg bersangkutan kemudian langsung ke proses mengisi di form jawaban. (Flow ini yg sudah dari awal dibicarakan oleh pak @eddieridwan).

**Comment by eddieridwan** [comment]
Sdh dicommit ke `rilis-dev`

**Comment by FeraKesesi1** [comment]
![IMG_20241031_115541_021](https://github.com/user-attachments/assets/4e28d313-a1b7-46a3-ac72-6fdfa8c31d6f)

Tidak bisa import googleform di opensid

**Comment by eddieridwan** [comment]
@FeraKesesi1 buat issue bug baru. Tidak membuat komentar di issue lama yg sudah ditutup karena tidak akan ditindaklanjuti. cc @rgrahardi
