### ISSUE TITLE
[Premium]Tambahkan fitur Ambil Gambar Pake Kamera di semua menu/submenu yang membutuhkan upload gambar

### ISSUE THREAD

**Issue by WAHYUDIK** [OpenSID/OpenSID#4055]
### Bagaimana alurnya sampai muncul masalah?
pada saat ini pengambilan gambar melaluli kamera masih sebatas di data individu saja. untuk menu/submenu yang lain masih belum bisa.

### Seperti apa yang diharapkan?
harapannya dibeberapa menu yang membutuhkan upload gambar juga bisa menggunakan fitur pengambilan dari kamera juga.
beberapa menu/submenu yang membutuhkan upload gambar:
1. Menu Pembangunan
2. Menu Pemetaan
### Apa yang terjadi?
Saat Ini masih belum bisa ambil gambar langsung 
### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
Modul:
- [x] Kelompok (https://github.com/OpenSID/premium/pull/221)

**Comment by eddieridwan** [comment]
Penggunaan kamera di form anggota kelompok sudah dicommit ke `rilis-dev` melalui https://github.com/OpenSID/premium/pull/221.

**Comment by eddieridwan** [comment]
Penggunaan kamera di form Pemerintahan Desa sudah dicommit ke `rilis-dev` melalui https://github.com/OpenSID/premium/pull/223

**Comment by eddieridwan** [comment]
Issue ini akan ditutup. Untuk penambahan kamera ke menu yg lain, sebaiknya dibuat issue terpisah.
