### ISSUE TITLE
Login Layanan Mandiri Menggunakan KTP Elektronik

### ISSUE THREAD

**Issue by mizwaruddin** [OpenSID/OpenSID#4057]
### Bagaimana alurnya sampai muncul masalah?
Saat ini login layanan mandiri masih menggunakan NIK dan PIN.

### Seperti apa yang diharapkan?
Login laytanan mandiri dapat menggunakan KTP Elektronik untuk mempercepat layanan.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sdh dicommit ke `rilis-dev` melalui https://github.com/OpenSID/premium/pull/115
