### ISSUE TITLE
Gunakan QR Code yang bisa di scan oleh opensid tanpa pake alat atau aplikasi lain

### ISSUE THREAD

**Issue by mizwaruddin** [OpenSID/OpenSID#4058]
### Bagaimana alurnya sampai muncul masalah?
Saat ini qr code elum bisa digunakan untuk validasi surat.

### Seperti apa yang diharapkan?
QR Code dapat digunakan untuk validasi surat dengan cara  di scan oleh opensid tanpa pake alat atau aplikasi lain (qr code scanner)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Bukannya ini yg baru diumumkan untuk rilis Premium beta? Atau ada yg lain yg dimaksud?

**Comment by mizwaruddin** [comment]
Beda, Bang. Issue ini untuk membaca qrcode melalui webcam/kamera hp di opensid tanpa aplikasi tambahan.

**Comment by eddieridwan** [comment]
Kalau begitu judul dan keterangan issue ini perlu diganti supaya lebih jelas itu yg dimaksud.

**Comment by eddieridwan** [comment]
Sdh dicommit ke `rilis-dev` melalui https://github.com/OpenSID/premium/pull/113
