### ISSUE TITLE
Ganti "KODE DESA" menjadi "KODE PELANGGAN" pada menu Info Layanan Pelanggan

### ISSUE THREAD

**Issue by PWidodo** [OpenSID/OpenSID#4059]
### Bagaimana alurnya sampai muncul masalah?
Pada menu "Info Layanan Pelanggan" khusus untuk desa yang menggunakan layanan hosting atau domain OpenDesa terdapat data "KODE DESA" yang berisi kode langganan layanan OpenDesa, bukannya berisi data kode desa dari Kemendagri.

### Seperti apa yang diharapkan?
Agar tidak salah tafsir, saya usulkan untuk nama KODE DESA tersebut diganti menjadi KODE PELANGGAN.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 21.03-pasca (rilis umum)
| Versi PHP        | 7.4
| System operasi   | Windows
![kode pelanggan](https://user-images.githubusercontent.com/45189822/110887563-2308c680-831d-11eb-9e60-37b598dc3fd5.png)

**Comment by Nurhidayat29** [comment]
punya saya berisi data kode desa sesuai kemendagri

**Comment by roaddee** [comment]
@Nurhidayat29 coba screenshoot juga

**Comment by afa28** [comment]
![alla](https://user-images.githubusercontent.com/57283157/111901541-712f6f80-8a6b-11eb-82a5-ba7e8852fa7b.png)

Dsni, kodenya berbeda. Sebenarnya data pd `kode desa` yg benar apa pak @eddieridwan ??? apakah kode desa sesuai kemendagri, kode pelanggan atau yg lainnya ???

**Comment by Nurhidayat29** [comment]
![Sistem Informasi Desa Desa Hibrida Jaya - Pelanggan - Google Chrome 26_03_2021 12 10 25](https://user-images.githubusercontent.com/51182125/112585408-54f54f00-8e2c-11eb-9be5-045a4ef2ff5c.png)

**Comment by agungsugiarto** [comment]
Pak @eddieridwan, apakah kode desa ini merujuk kepada kode desa masing2 ?

**Comment by Zulkarnaimni** [comment]
![image](https://user-images.githubusercontent.com/64481641/112992136-1ba54200-9192-11eb-9085-c3ef5d967dba.png)

**Comment by afa28** [comment]
Modul pelanggan sudah disesuaikan ulang dan sudah digabung ke `rilis-dev`, `master`
