### ISSUE TITLE
ERROR 500 di halaman balas pesan

### ISSUE THREAD

**Issue by YudhaMAR** [OpenSID/OpenSID#4060]
Mohon solisi pada halaman https://demo.opensid.or.id/mailbox/form di saya terjadi error 500

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master`
