### ISSUE TITLE
Tampilan Laporan Data Suplemen Tidak Sesuai Dengan Data yang di input

### ISSUE THREAD

**Issue by yayanmulyanto20** [OpenSID/OpenSID#4061]
### Bagaimana alurnya sampai muncul masalah?
Saat menampilkan  Laporan Data Sumplen di web Hanya di batasi 10 padahal yang kita input lebih dari itu

### Seperti apa yang diharapkan?
Seharunya yang ditampilkan di laporan sesuai data yang kita input

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
Sertakan gambar.

**Comment by agungsugiarto** [comment]
Saat ini tema natra banyak terjadi error ketika ditambahkan menu data suplemen di web, coba kita tag Bapak @ariandii

https://berputar.opensid.or.id/data-suplemen/6

**Comment by eddieridwan** [comment]
Sdh dicommit ke `rilis-dev`, dengan perubahan pada tema natra menambahkan layout dan partial untuk suplemen.
