### ISSUE TITLE
BUG? statistik bantuan?

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#4062]
### Bagaimana alurnya sampai muncul masalah?

https://demo.opensid.or.id/first/statistik/501

### Seperti apa yang diharapkan?
singkron dengan isian menu bantuan

### Apa yang terjadi?
Nomor urutnya hilang dan jumlahnya tidak singkron dengan isian di menu bantuan

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
Untuk PESERTA, BUKAN PESERTA dan TOTAL tidak menggunakan no urut.

**Comment by agungsugiarto** [comment]
Pak @balongbesuk apakah masih mengalami issue yang dimaksud?

**Comment by afa28** [comment]
Bug pd jumlah pd statistik tdk sesuai pd modul program bantuan.

**Comment by agungsugiarto** [comment]
Pak @balongbesuk, issue ini saya tutup karena demo di berputar tidak ditemukan issue yg dimaksud. Silahkan issue ini dibuka kembali jika masih mengalami issue ini.

**Comment by afa28** [comment]
Bisa di cek ulang mas @agungsugiarto pada https://berputar.opensid.or.id/first/statistik/5013

Yang dimaksud pak @balongbesuk itu yg ini, bisa di cek jg bantuan yg lain. 
![1](https://user-images.githubusercontent.com/57283157/112090880-ed8a9580-8bc6-11eb-810f-d1cabc8edb77.png)
![2](https://user-images.githubusercontent.com/57283157/112090885-ef545900-8bc6-11eb-9759-2c9dbc535d91.png)
![3](https://user-images.githubusercontent.com/57283157/112090888-efecef80-8bc6-11eb-87a1-671b708abcf5.png)

**Comment by agungsugiarto** [comment]
Terima kasih mas @afa28 sudah membantu melengkapi, akan saya coba cek.

**Comment by afa28** [comment]
> Terima kasih mas @afa28 sudah membantu melengkapi, akan saya coba cek.

Ya.

**Comment by eddieridwan** [comment]
Sdh dicommit ke `rilis-dev` melalui https://github.com/OpenSID/premium/pull/124
