### ISSUE TITLE
Tidak bisa menambahkan Aparatur Desa..

### ISSUE THREAD

**Issue by mekarrahayu** [OpenSID/OpenSID#4064]
### Bagaimana alurnya sampai muncul masalah?
pertama-tama saya ingin memperbaharui aparat pemerintahan desa.. yang alam saya delete.. lalu menambahna yang baru..
awalnya berjalan lancar.. sampe akhirnya saya bisa delete tapi tidak bisa menambahan aparat pemerintahan desa sama sekali.. 
sampai saat ini masi belum bisa

### Seperti apa yang diharapkan?
saya ingin mengetahui apa yang salah .. apakah bug atau ada settingan yang salah

### Apa yang terjadi?
sampe detik ini tidak dapat menambahkan "aparat pemerintahan desa"

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | V20.12 pasca
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
Lampirkan tampakan layar error yg dialami. Lampirkan isi file di folder logs saat terjadi error. 
Sebelum membuat issue yakinkan dulu memang error. Ini bisa dilakukan dengan bertanya di https://www.facebook.com/groups/OpenSID

**Comment by mekarrahayu** [comment]
> Lampirkan tampakan layar error yg dialami. Lampirkan isi file di folder logs saat terjadi error.
> Sebelum membuat issue yakinkan dulu memang error. Ini bisa dilakukan dengan bertanya di https://www.facebook.com/groups/OpenSID

 tidak ada tampilan error..
hanya saya ketika menambahkan data baru tidak bertambah.. 

- [ ]

**Comment by eddieridwan** [comment]
@mekarrahayu , apakah ini terjadi di v20.12 pasca? Kalau iya, silakan update dulu ke rilis yg terbaru (v21.03-pasca). 
Bisa cek di https://demo.opensid.or.id apakah masalah ini masih ada. Kalau di website demo itu normal, harap issue ini ditutup saja.

**Comment by mekarrahayu** [comment]
awal nya bisa melakukan penmabhan.. lalu tiba2 tidak bisa..

ternyata ada tulisan "data gagal disimpan"

**Comment by eddieridwan** [comment]
@mekarrahayu , apakah ini terjadi di v20.12 pasca? Kalau iya, silakan update dulu ke rilis yg terbaru (v21.03-pasca). 
Bisa cek di https://demo.opensid.or.id apakah masalah ini masih ada. Kalau di website demo itu normal, harap issue ini ditutup saja, kecuali ada info tambahan.

**Comment by agungsugiarto** [comment]
Pak @mekarrahayu, pastikan mengupdate opensid anda ke versi rilis terbaru v21.03-pasca jika masih menggunakan versi yg lama. di demo berputar dan demo saya tidak mengalami issue yg dimaksud ketika menambah aparatur desa dari penduduk maupun luar desa. Issue ini saya tutup, jika masih mengalami issue tersebut silahkan bertanya diforum dan issue ini dibuka kembali. Terima kasih
