### ISSUE TITLE
Sediakan opsi login eKTP di Layanan Mandiri harus juga mengisi PIN

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#4065]
### Bagaimana alurnya sampai muncul masalah?
Saat ini login Layanan Mandiri dapat dilakukan menggunakan scan tag_id dari e-KTP, tanpa mengisi PIN. 

Kalau ini dilakukan di anjungan di kantor desa, tidak bermasalah, karena ada di bawah pengawasan petugas desa.

Tapi kalau dilakukan di rumah, fitur ini memiliki tingkat keamanan yg lebih rendah dari menggunakan NIK + PIN. Tingkat keamanan lebih rendah karena pengguna hanya perlu menerka tag_id valid sebanyak 10 digit. 

### Seperti apa yang diharapkan?
Desa diberi opsi untuk memaksa penggunaan PIN pada login Layanan Mandiri kecuali di anjungan.  Juga field eKTP di form login perlu dibuat read-only -- yaitu supaya hanya menampilkan hasil scan e-KTP dan tidak bisa diisi manual. 

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | v21.03-premium
| Versi PHP        | 
| System operasi   |

**Comment by khiar-rara** [comment]
Saya setuju kalau diluar anjungan, tetap pake PIN.

**Comment by WAHYUDIK** [comment]
sekedar usul, untuk login saja mungkin tidak masalah secara otomatis scan eKTP, tetapi setelah sukses login diharuskan isi pin untuk mengakses menu-menu yang ada di layanan mandiri.

**Comment by redjoel** [comment]
saya sempat minta ke pak Zeppy untuk bikin mudah Login petugas desa dengan hanya tempel KTP, ga perlu username password. ternyata masalah juga ini kalau dionlinekan :(

**Comment by eddieridwan** [comment]
Sdh dicommit ke `rilis-dev` melalui https://github.com/OpenSID/premium/pull/117. Tidak disediakan opsi. Layanan mandiri non anjungan harus juga login menggunakan PIN.

**Comment by abmuj18** [comment]
Karena keamanan wajib dikedepankan, setuju.
