### ISSUE TITLE
Bug Ganti PIN Layanan Mandiri

### ISSUE THREAD

**Issue by afa28** [OpenSID/OpenSID#4068]
### Bagaimana alurnya sampai muncul masalah?
LAYANAN MANDIRI
Setelah update, proses ganti PIN saat pertama kali masuk dan berhasil tdk terjadi apa2 (tdk ada notifikasi yg tampil mengarahkan untuk logout / versi sebelumnya).

### Seperti apa yang diharapkan?
Setelah berhasil ganti pin tampilkan kembali notifikasi berhasil dan logut. Baru kemudian login kembali.

### Apa yang terjadi?
Sesuai alur pd versi sebelumnya.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by eddieridwan** [comment]
@afa28 , saya coba di branch `rilis-dev`, tidak bermasalah. Masalah ini ditemukan di branch mana?

**Comment by afa28** [comment]
> @afa28 , saya coba di branch `rilis-dev`, tidak bermasalah. Masalah ini ditemukan di branch mana?

Sudah normal, masalah chace.
