### ISSUE TITLE
Bug pada Fitur Cetak Laporan pada Wilayah Administratif Dusun

### ISSUE THREAD

**Issue by Zulkarnaimni** [OpenSID/OpenSID#4069]
### Bagaimana alurnya sampai muncul masalah?
1. Temukan pilihan posisi dan jabatan yg sama pada pilihan penanda tangan laporan;
2. Tidak tampilnya nama pada hasil cetak laporan
3. Judul laporan alamat Desa; Kecamatan; Kabupaten tidak ditampilkan dalam lembaran cetak laporan

![image](https://user-images.githubusercontent.com/64481641/111637686-40adc280-882c-11eb-8b33-ec7691d560b8.png)
![image](https://user-images.githubusercontent.com/64481641/111637867-66d36280-882c-11eb-98a9-7d53d54be05c.png)
![image](https://user-images.githubusercontent.com/64481641/111637915-6f2b9d80-882c-11eb-9ab4-e3b5faf6654e.png)

### Seperti apa yang diharapkan?
Penyesuaian...

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 21.03 Premium
| Versi PHP        | 
| System operasi   | https://berputar.opensid.or.id/sid_core

**Comment by Nurhidayat29** [comment]
data pemerintah desa belum terisi jabatan lain hanya ada kepala desa. silakan isi terlebih dahulu data pemdes. untuk sebutan kab, kec dan des bagian bawah sepertinya dihilangkan saja karna dibagian atas sudh ada

**Comment by eddieridwan** [comment]
Sdh dicommit ke `rilis-dev` melalui https://github.com/OpenSID/premium/pull/123
