### ISSUE TITLE
Fitur Cetak di Buku Administrasi Penduduk [BUG]  

### ISSUE THREAD

**Issue by Zulkarnaimni** [OpenSID/OpenSID#4072]
**Jelaskan error yg dialami**
Berikan keterangan yg jelas dan singkat mengenai error yg dialami. 

1. Di halaman Hasil cetak Laporan ada 2 tempat tanda tangan, satu Kepala Desa dan satu nya lagi yang sebelah kanan halaman dibagian bawah juga ada tempat tanda tangan, barang kali staff atau perangkat desa yang mencetak laporannya, akan tetapi  tempat letak tanda tangan nya ada sedangkan nama siapa yang akan tanda tangan tidak ada...
![image](https://user-images.githubusercontent.com/64481641/111872993-b8acf180-89c0-11eb-94b5-da1ff34d3956.png)

2. Begitu juga di cetak laporan pada fitur "Buku Penduduk Sementara" dan "Buku KTP dan KK" sama dengan laporan nomor 1
![image](https://user-images.githubusercontent.com/64481641/111873006-c95d6780-89c0-11eb-8c25-c69b9b4b5db7.png)

3. Pada Dasboard atau Fitur "Buku Rekapitulasi Jumlah Penduduk", jumlah halaman yang tampil sangat banyak sampai dengan 26 halaman, sedangkan yang dibutuhkan cuma satu halaman rekapitulasi saja, saya tidak tahu untuk fitur ini apakah tergolong ke BUG atau memang desaign nya seperti itu.

![image](https://user-images.githubusercontent.com/64481641/111873119-57d1e900-89c1-11eb-8d0e-be49f3444ed6.png)

Pastikan error ini juga ditemukan di https://demo.opensid.or.id (untuk RIlis Umum) atau di https://berputar.opensid.or.id (untuk RIlis Premium).

**Cara untuk mereplikasi errornya**
Langkah untuk mereplikasi error yg dialami:
1. Pergi ke halaman '...'
2. Klik tombol '....'
3. Gulir ke bawah sampai '....'
4. Lihat error

**Hasil yg diharapkan**
Berikan keterangan yg jelas dan singkat apa hasil yg diharapkan.

**Tampakan layar dan log error**
Lampirkan tampakan layar yg menjelaskan permasalahan.
Lampirkan isi file di folder `logs` atau tampakan error di console inspector browser.

**Versi OpenSID**
Rilis umum (mis. v21.03) atau premium (v21.03-premium)

**Informasi tambahan**
Penjelasan lain yg dapat membantu.

**Comment by eddieridwan** [comment]
@Zulkarnaimni terima kasih telah melaporkan.

Issue anda saat ini berisi berbagai masalah. Mohon batasi setiap issue hanya melaporkan satu masalah saja. Harap membuat issue terpisah untuk setiap masalah. Ini diperlukan untuk memudahkan teman2 programmer yg menangani.

Masalah (1) dan (2) yg anda laporkan disebabkan data Sekretaris Desa belum diisi di menu Pemerintahan Desa dan belum ditandai sebagai `u.b`. Hanya pamong desa yg ditandai `u.b` yg tampil di laporan sebagai penanda tangan. Silakan lihat panduan untuk informasi lebih lanjut.

**Comment by eddieridwan** [comment]
Untuk masalah (3), tidak bisa kami replikasi di https://berputar.opensid.or.id. Coba clear cache dulu dan refresh.

Issue ini kami tutup karena tidak ada yg perlu diperbaiki. Kalau ada informasi tambahan silakan di buka kembali.

**Comment by Zulkarnaimni** [comment]
Oke nanti saya coba uji untuk test di u.b, makasih infonya Pak

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
