### ISSUE TITLE
Temuan Bug pada Fitur "Kependudukan" Pada Pengelolaan Kelompok" pada menu cetak [BUG] 

### ISSUE THREAD

**Issue by Zulkarnaimni** [OpenSID/OpenSID#4073]
**Jelaskan error yg dialami**
Berikan keterangan yg jelas dan singkat mengenai error yg dialami. 

1.  Pada Tempat Tanda Tangan di Halaman hasil cetak "nama Kepala Desa" dan "Nama Staff" yang mencetak laporan tidak sesuai dengan nama yang menanda tangan yang di pilih.

![image](https://user-images.githubusercontent.com/64481641/111874172-856d6100-89c6-11eb-9f34-8eb964244149.png)

2. Screensote system Milik Desa
![image](https://user-images.githubusercontent.com/64481641/111874240-d67d5500-89c6-11eb-9e7c-cd6731531490.png)

3. Screensote System Demo 
![image](https://user-images.githubusercontent.com/64481641/111874262-f1e86000-89c6-11eb-8326-dab69f2a2e50.png)

4. Juga Pada Halaman Cetak Kategori Kelompok hasil cetaknya sama dengan laporan issue diatas
![image](https://user-images.githubusercontent.com/64481641/111874410-b8fcbb00-89c7-11eb-9db5-00acd6eebbc8.png)

Pastikan error ini juga ditemukan di https://demo.opensid.or.id (untuk RIlis Umum) atau di https://berputar.opensid.or.id (untuk RIlis Premium).

**Cara untuk mereplikasi errornya**
Langkah untuk mereplikasi error yg dialami:
1. Pergi ke halaman '...'
2. Klik tombol '....'
3. Gulir ke bawah sampai '....'
4. Lihat error

**Hasil yg diharapkan**
Berikan keterangan yg jelas dan singkat apa hasil yg diharapkan.

**Tampakan layar dan log error**
Lampirkan tampakan layar yg menjelaskan permasalahan.
Lampirkan isi file di folder `logs` atau tampakan error di console inspector browser.

**Versi OpenSID**
Rilis umum (mis. v21.03) atau premium (v21.03-premium)

**Informasi tambahan**
Penjelasan lain yg dapat membantu.

**Comment by agungsugiarto** [comment]
Bapak @Zulkarnaimn terima kasih telah melaporkan.

Masalah (1), (2), (3) dan (4) yg anda laporkan disebabkan data Sekretaris Desa belum diisi di menu Pemerintahan Desa dan belum ditandai sebagai u.b. Hanya pamong desa yg ditandai u.b yg tampil di laporan sebagai penanda tangan. Silakan lihat panduan untuk informasi lebih lanjut.
