### ISSUE TITLE
Sediakan analisis SDGs untuk tingkat Desa, RT, dan Keluarga

### ISSUE THREAD

**Issue by mizwaruddin** [OpenSID/OpenSID#4074]
**Apa kekurangan yg ingin diatasi?**
Seiring dengan program survey SDGs yang mencakup SDGs Tingkat Desa, Rukun Tangga, dan Keluarga, maka perlu ditambahkan analisis2 tsb di OpenSID. Analisis ini tidak untuk menggantikan peran aplikasi SDGs yg dikeluargan oleh Kemendes, melainkan untuk mendokumentasikan hasil survey di OpenSID supaya slogan OpenSID sebagai Rumah Data benar2 terwujud. 

**Jelaskan solusi yg diinginkan**
Tambahkan kuesioner SDGs tingkat Desa, Rukun Tangga (RT), dan keluarga tanpa aksi analisis.
[SDGs DESA KUESIONER DESA 2.pdf](https://github.com/OpenSID/OpenSID/files/6175824/SDGs.DESA.KUESIONER.DESA.2.pdf)
[SDGs DESA KUESIONER RUKUN TETANGGA(1) (1).pdf](https://github.com/OpenSID/OpenSID/files/6175826/SDGs.DESA.KUESIONER.RUKUN.TETANGGA.1.1.pdf)
[SDGs DESA KUESIONER KELUARGA 2.pdf](https://github.com/OpenSID/OpenSID/files/6175827/SDGs.DESA.KUESIONER.KELUARGA.2.pdf)

[Analisis SDGs Keluarga dan Individu.zip](https://github.com/OpenSID/OpenSID/files/6175829/Analisis.SDGs.Keluarga.dan.Individu.zip)

**Apakah ada alternatif lain**
Beri keterangan singkat dan jelas solusi lain yg telah anda pertimbangkan untuk kebutuhan ini.

**Untuk versi OpenSID mana**
Fitur ini diusulkan untuk versi Rilis Umum (mis. v21.03) atau Rilis Premium (mis v21.03-premium) yg mana?

**Informasi tambahan**
Beri informasi lainnya yg dapat membantu menjelaskan permintaan ini.

**Comment by Zulkarnaimni** [comment]
Mantap Pak.......

**Comment by Ferrobae** [comment]
Ini isu rilis utama update mendatang
Vote

**Comment by eddieridwan** [comment]
Sdh dicommit ke rilis-dev.
