### ISSUE TITLE
Pada Halaman-Halaman Cetak Laporan Statistik juga terdapat pilihan yang menanda tangan tidak sesuai [BUG] 

### ISSUE THREAD

**Issue by Zulkarnaimni** [OpenSID/OpenSID#4076]
**Jelaskan error yg dialami**
Berikan keterangan yg jelas dan singkat mengenai error yg dialami. 

Pada Halaman-Halaman Cetak Laporan Statistik juga terdapat pilihan yang menanda tangan tidak sesuai [BUG] 
![image](https://user-images.githubusercontent.com/64481641/111874976-e9455900-89c9-11eb-9cd5-b96dbcf58c63.png)

Pastikan error ini juga ditemukan di https://demo.opensid.or.id (untuk RIlis Umum) atau di https://berputar.opensid.or.id (untuk RIlis Premium).

**Cara untuk mereplikasi errornya**
Langkah untuk mereplikasi error yg dialami:
1. Pergi ke halaman '...'
2. Klik tombol '....'
3. Gulir ke bawah sampai '....'
4. Lihat error

**Hasil yg diharapkan**
Berikan keterangan yg jelas dan singkat apa hasil yg diharapkan.

**Tampakan layar dan log error**
Lampirkan tampakan layar yg menjelaskan permasalahan.
Lampirkan isi file di folder `logs` atau tampakan error di console inspector browser.

**Versi OpenSID**
Rilis umum (mis. v21.03) atau premium (v21.03-premium)

**Informasi tambahan**
Penjelasan lain yg dapat membantu.

**Comment by agungsugiarto** [comment]
Bapak @Zulkarnaimn terima kasih telah melaporkan.

Masalah yg anda laporkan disebabkan data Sekretaris Desa belum diisi di menu Pemerintahan Desa dan belum ditandai sebagai u.b. Hanya pamong desa yg ditandai u.b yg tampil di laporan sebagai penanda tangan. Silakan lihat panduan untuk informasi lebih lanjut. Issue ini saya tutup, jika masih ada kendala silahkan dibuka kembali. Terima kasih.
