### ISSUE TITLE
SDGs - Kode Pertanyaan pada Indikator & Pertanyaan Analisis perbolehkan Huruf

### ISSUE THREAD

**Issue by hasap86** [OpenSID/OpenSID#4077]
**Apa kekurangan yg ingin diatasi?**

Pada saat input SDGs Desa Kode Pertanyaan menggunakan huruf, sedangkan di OpenSID hanya diperbolehkan angka saja

**Jelaskan solusi yg diinginkan**

Kode Pertanyaan menggunakan Angka, Huruf, strip (-) & Titik (.) untuk sub number

**Apakah ada alternatif lain**

**Untuk versi OpenSID mana**

Rilis Umum

**Informasi tambahan**

![kode-pertanyaan](https://user-images.githubusercontent.com/45263721/111891709-65ba5500-8a27-11eb-8bcf-056f071e2481.jpg)

**Comment by eddieridwan** [comment]
Sdh dicommit ke `rilis-dev` melalui https://github.com/OpenSID/premium/pull/139
