### ISSUE TITLE
[BUG] : Kesalah Isian Pengaturan Layanan Surat

### ISSUE THREAD

**Issue by afa28** [OpenSID/OpenSID#4078]
**Jelaskan error yg dialami**

Ubah format surat yg td dibuat, hasilnya adalah Ya
![2](https://user-images.githubusercontent.com/57283157/111892292-ae284180-8a2c-11eb-8956-4a46f5473d37.png)

**Hasil yg diharapkan**

Data yg tersimpan sesuai dengan yg di input.

**Tampakan layar dan log error**

**Versi OpenSID**
 Rilis umum v21.03-pasca

**Informasi tambahan**
 Tumpang tidih data inputan yg adakan disimpan.
`$data['mandiri'] = isset($data['mandiri']) ? 1 : 0;` dan `$data['mandiri'] = empty($data['mandiri']) ? 0 : 1;` yg dimana harusnya 0 = Tidak dan 1 = Ya.

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` dan ke `rilis-dev`
