### ISSUE TITLE
Fitur SMS?

### ISSUE THREAD

**Issue by dadannurman** [OpenSID/OpenSID#408]
Maaf master, bagaimana cara menggunakan fitur sms? harus menggunakan modem tipe apa?

**Comment by batudaa** [comment]
Kalau tidak salah opensid menggunakan Gammu, jadi cari saja modem yang compatible dengan Gammu,,,

**Comment by kelbatuix** [comment]
mohon arahan langkah2 mengaktifkan fitur sms ini>

**Comment by afa28** [comment]
Buat issue baru jika masih bermasalah.
