### ISSUE TITLE
Hasil Cetak Laporan Pada Fitur Sekretariat, Inventaris Pada Daftar Inventaris Peralatan Dan Mesin Nama Kelapa Desa tidak sama dengan yang terplih[BUG] 

### ISSUE THREAD

**Issue by Zulkarnaimni** [OpenSID/OpenSID#4081]
**Jelaskan error yg dialami**

**Cara untuk mereplikasi errornya**

**Hasil yg diharapkan**

**Tampakan layar dan log error**

**Versi OpenSID**

**Informasi tambahan**

**Comment by eddieridwan** [comment]
Sdh dicommit ke `rilis-dev` melalui https://github.com/OpenSID/premium/pull/125.
