### ISSUE TITLE
Tambahkan Pilihan Tap eKTP tanpa PIN

### ISSUE THREAD

**Issue by cepiandiana** [OpenSID/OpenSID#4082]
**Apa kekurangan yg ingin diatasi?**
Antisipasi Warga yang selalu lupa PIN, serta meminimalisir warga yang gaptek.
Dan juga mengantisipasi alur registrasi scan KTP yang balik lagi seperti login layanan mandiri pakai NIK

**Jelaskan solusi yg diinginkan**

Kalau emang tujuan PIN untuk mengamankan data ketika anjungan diluar kantor desa, maka sediakan pula fitur pengaturan anjungan mandiri yang dikantor desa saja.
Karena untuk anjungan mandiri yang di desa ketika menggunakan PIN akan terasa seperti sebelumnya yang login menggunakan NIK, kasian warga yang gaptek.

**Apakah ada alternatif lain**
Tetap harus diadakan fitur tap eKTP tanpa PIN kalau emang ada yang perlu menggunakan PIN

**Untuk versi OpenSID mana**

v21.04-premium

**Informasi tambahan**

Kemarin desa saya tertarik untuk upgrade ke premium, karena ada fitur scan / tap eKTP.
 
Namun pada tanggal 21 Maret di demo menggunakan link berputar.opensid.my.id jadi ada PIN nya, dan mempunyai beberapa opini diantaranya :
1. Kalau pakai PIN berarti ga jauh beda sama dengan login menggunakan NIK, perlu proses lagi mendaftarkan di pendaftar mandiri
2. Ketika menggunakan PIN, bukan 1 - 2 warga yang lupa PIN nya, akhirnya diregist lagi oleh operator.
3. Kalau memang PIN untuk antisipasi mengamankan data pemilik KTP, lantas apa bedanya ketika KTP si A dipergunakan oleh si B, dan itu adalah kesalahan dari pemilik KTP
4. Untuk pengajuan surat secara online, kan nanti si warga bisa / harus ke kantor desa untuk mengambil surat, jadi terverifikasi juga apakah itu yang iseng atau asli pemilik ktp

Terima kasih
Salam MerDESA 😁

**Comment by eddieridwan** [comment]
@cepiandiana . Di anjungan otomatis tidak memerlukan PIN, cukup scan eKTP. Untuk layanan mandiri di rumah/di luar kantor desa, tetap perlu menggunakan PIN, untuk menjaga keamanan/privasi data. Silakan lihat penjelasan di https://www.facebook.com/groups/OpenSID/permalink/1806574526174187/ mengapa PIN tetap diperlukan untuk penggunaan di luar kantor desa.

>Tapi tentu banyak teman2 yg terbiasa menggunakan kartu ATM. Apakah bisa menggunakan kartu ATM menarik uang atau melihat saldo tanpa menggunakan PIN? Mengapa harus mengisi PIN padahal sudah memiliki kartu ATM? Teman2 pasti sdh tahu jawabannya -- demi keamanan.

Komputer yg digunakan sebagai anjungan didaftar melalui IP di Layanan Mandiri > Anjungan. 

Ini sudah ada di versi beta premium, yg terpasang di https://berputar.opensid.or.id, dan akan masuk v21.04-premium.

Ok, issue ini akan ditutup. Kalau ada hal lain, silakan buka lagi.

**Comment by eddieridwan** [comment]
Supaya membantu anda menjelaskan pada yg bertanya, berikut beberapa hal negatif yg bisa terjadi jika seseorang mengakses Layanan Mandiri menggunakan eKTP orang lain secara tidak sah, tanpa PIN:
1. Melihat data pribadi pemilik eKTP secara tidak sah, misalnya untuk mencuri identitas seseorang
2. Mengirim pesan ke kantor desa seolah dia adalah warga tsb
3. Menghapus dokumen kelengkapan atau mengunggah dokumen kelengkapan keliru
4. Mengurangi kepercayaan pada keamanan OpenSID, karena terbukti ada yg menyalahgunakan. Kita perlu jaga ini jangan sampai terjadi, hanya untuk mengejar kemudahan yg sebenarnya tidak sulit diatasi (mengingat PIN). 
5. Mengakses secara tidak sah fitur layanan mandiri lainnya yg nanti akan ditambah terus...
