### ISSUE TITLE
[BUG] Masalah ketika instalasi, masalah pada library curly.

### ISSUE THREAD

**Issue by ITGembel** [OpenSID/OpenSID#4083]
**Jelaskan error yg dialami**
Setelah selesai instalasi awal, muncul error ketika sudah submit login di siteman.

**Tampakan layar dan log error**
```An uncaught Exception was encountered

Type: Exception

Message: Unable to obtain CA bundle: Unable to open destination file: /var/www/html/OpenSID/cacert.pem

Filename: /var/www/html/OpenSID/donjo-app/libraries/Curly.php

Line Number: 135
```

**Versi OpenSID**
21.03-pasca

**Informasi tambahan**
Aplikasi dijalankan menggunakan docker di Ubuntu 20.01.

**Comment by eddieridwan** [comment]
Mohon masalah instal OpenSID ditanyakan di https://www.facebook.com/groups/OpenSID atau di https://t.me/joinchat/SI0GWHeqKT39Gxhh, karena terkait sistem masing2 pengguna. Atau juga bisa cari informasi di panduan untuk masalah install, seperti di https://github.com/OpenSID/OpenSID/wiki/Tanya-Jawab-Install-dan-Update.

Issue dibatasi untuk hal2 yg jelas memerlukan perbaikan script system.

Issue ini akan ditutup.
