### ISSUE TITLE
Urutkan Nomor Urut Rumah Tangga

### ISSUE THREAD

**Issue by muhtar-coder** [OpenSID/OpenSID#4084]
### Bagaimana alurnya sampai muncul masalah?
Susunan nomor urut rumah tangga acak acakan/tidak berurut

![image](https://user-images.githubusercontent.com/55665526/112031002-6eb53e80-8b6d-11eb-96f6-a3727593cba9.png)

### Seperti apa yang diharapkan?
Nomor ber urut 001-100 dst

### Apa yang terjadi?

lebih rapih dan mudah dalam identifikasi nomor serta enak di lihat
### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by Ferrobae** [comment]
Ketika di sorting bisa keliatan jg berurutan, yg terjadi selanjutny untuk rumah yg baru diantara 2 nomor yg berurutan bisa pake kode ujung A atau nomor akhir

**Comment by muhtar-coder** [comment]
sebenarnya data yg di gunakan per rt seperti saat ini pendataan sdgs dan
plkb. perhitungan di mulai dari awal (01 dst ) setiap rt. mungkin dalam
penjumlahan total bisa seperti statistik wilayah..

Pada tanggal Sel, 23 Mar 2021 06.18, Ferrobae ***@***.***>
menulis:

**Comment by eddieridwan** [comment]
Bung @afa28 , setelah diambil,  mohon jangan lupa menggeser issue ke kolom SEDANG DIKERJAKAN dan assign diri anda.

**Comment by eddieridwan** [comment]
@muhtar-coder , @afa28 apakah tidak lebih baik diurut secara default berdasarkan tanggal/waktu didaftarkan. Dengan pertimbangan setelah membuat rumah tangga baru, entri itu segera terlihat di atas. Sedangkan untuk mengurut berdasarkan nomor rumah tangga tinggal klik kolomnya saja.

**Comment by afa28** [comment]
> @muhtar-coder , @afa28 apakah tidak lebih baik diurut secara default berdasarkan tanggal/waktu didaftarkan. Dengan pertimbangan setelah membuat rumah tangga baru, entri itu segera terlihat di atas. Sedangkan untuk mengurut berdasarkan nomor rumah tangga tinggal klik kolomnya saja.

Pak @eddieridwan ini sering terjadi, kadang ada yg buat issue berkali-kali hanya untuk pengurutan sj. Yg sy perbaiki disini adalah bug dr order_by yg tdk jalan setelah query di optimasi di versi sebelumnya.

**Comment by afa28** [comment]
> Bung @afa28 , setelah diambil,  mohon jangan lupa menggeser issue ke kolom SEDANG DIKERJAKAN dan assign diri anda.

Ok

**Comment by eddieridwan** [comment]
Sdh dicommit ke `rilis-dev` melalui https://github.com/OpenSID/premium/pull/135

**Comment by muhtar-coder** [comment]
prinsip system yg selama ini berjalan adalah mengikuti alur peraturan dari
kementerian terkait... dan desa bersama opensidnya mengikuti aturan dan
kebutuhan menyesuaikan dengan aturan tersebut..

Pada tanggal Sab, 27 Mar 2021 17.13, Eddie Ridwan ***@***.***>
menulis:
