### ISSUE TITLE
Fitur Absensi Perangkat Desa Online, E Kinerja jg SPD

### ISSUE THREAD

**Issue by Ferrobae** [OpenSID/OpenSID#4085]
**Apa kekurangan yg ingin diatasi?**

Agar terpantau kehadiran perangkat desa juga untuk peningkatan disiplin sekaligus jg e kinerja sebagai history kerja perangkat Desa yg mana jika melakukan perjalanan Dinas ke luar langsung otomatis terekam jg

**Jelaskan solusi yg diinginkan**

**Apakah ada alternatif lain**

**Untuk versi OpenSID mana**

Rilis Premium v.21.05 

**Informasi tambahan**

**Comment by agungsugiarto** [comment]
@Ferrobae terima kasioh sudah melaporkan issue,

Issue ini saya tutup karena duplikat dengan https://github.com/OpenSID/OpenSID/issues/2033
Mohon sebelum membuat issue untuk permintaan fitur atau bug terlebih dahulu untuk mengecek issue yg sudah ada. Terima kasih.
