### ISSUE TITLE
Masih Bug di Cetak Laporan Statistik  pada Nama Penanda Tangan [BUG] 

### ISSUE THREAD

**Issue by Zulkarnaimni** [OpenSID/OpenSID#4087]
**Jelaskan error yg dialami**

Nama yang menanda tangan laporan statistik "MUHAMMAD ILHAM" atau kepala desa yg bertanda tangan bukan nama yang berasal dalam database pada SID Desa, atau nama lainnya yang tak ada hubungan dengan perangkat desa ataupun kepala desa.

SCREENSOTE DARI WEBSITE DESA https://berputar.opensid.or.id/
![image](https://user-images.githubusercontent.com/64481641/112133779-9dc7c080-8bfe-11eb-992e-f5641a45ab18.png)

SCREENSOTE DARI WEBSITE DESA https://www.teupinbeulangan.desa.id/
![image](https://user-images.githubusercontent.com/64481641/112133888-bd5ee900-8bfe-11eb-930b-81932f9ea540.png)

**Cara untuk mereplikasi errornya**

**Hasil yg diharapkan**

**Tampakan layar dan log error**

**Versi OpenSID**

**Tema Yg Digunakan**

**Informasi tambahan**

**Comment by eddieridwan** [comment]
Sdh dicommit ke `rilis-dev` melalui https://github.com/OpenSID/premium/pull/127.
