### ISSUE TITLE
[BUG] Tidak Bisa Tampil Ketika isi form di layanan mandiri

### ISSUE THREAD

**Issue by desapgt** [OpenSID/OpenSID#4088]
![IMG_20210323_212337_403](https://user-images.githubusercontent.com/48290077/112162928-19d20080-8c1f-11eb-913c-61dedbe63489.jpg)

Ketika klik isi form pada menu surat dilayanan mandiri tidak muncul apa seperti gambar diatas

**Comment by agungsugiarto** [comment]
Pak @desapgt, terima kasih sudah melaporkan issue.

Mohon lengkapi issue anda mengikuti template yang sudah disediakan yaitu `Laporan Bug` untuk memudahkan teman2 pegiat. Terima kasih.

**Comment by eddieridwan** [comment]
@desapgt , mohon selalu coba dulu di website demo, untuk rilis umum di https://demo.opensid.or.id atau di https://berputar.opensid.or.id untuk premium. Terlihat masalah ini tidak ditemukan di website demo tsb. Berarti masalah ada di sistem anda. Dalam hal ini mohon tidak menggunakan issue, dan tanyakan di https://www.facebook.com/groups/OpenSID atau di group Telegram https://t.me/joinchat/SI0GWHeqKT39Gxhh.

Issue ini akan kami tutup. Silakan buka lagi kalau ada informasi tambahan.

**Comment by eddieridwan** [comment]
Sdh dicommit ke `rilis-dev` melalui https://github.com/OpenSID/premium/pull/128
