### ISSUE TITLE
[BUG] Tombol/ikon Peta didepan sidebar ketika cursor hover di sidebar

### ISSUE THREAD

**Issue by rizkiv1** [OpenSID/OpenSID#4091]
**Jelaskan error yg dialami**

Sidebar dibawah tombol map ketika kursor dihover ke sidebar.

**Cara untuk mereplikasi errornya**

1. Pergi ke halaman ''Peta"
2. Arahkan kursor ke sidebar
**Hasil yg diharapkan**

Sidebar diatas map agar terbaca & bisa di klik

**Tampakan layar dan log error**

**Versi OpenSID**

21.03 dan 21.03-pasca

**Tema Yg Digunakan**

**Informasi tambahan**

Diuji di demo.opensid.or.id/gis

**Comment by agungsugiarto** [comment]
@rizkiv1 terima kasih sudah melaporkan issue,

Mohon berikan informasi tambahan seperti screenshoot untuk memudahkan temat2 pegiat terima kasih.

**Comment by rizkiv1** [comment]
![image](https://user-images.githubusercontent.com/12994088/112253858-1035b080-8c92-11eb-88e1-98a038d80396.png)

**Comment by eddieridwan** [comment]
Sdh dicommit ke `bug-fix` melalui https://github.com/OpenSID/premium/pull/148
