### ISSUE TITLE
Pilih Lokasi Persil Tidak tampil saat tambah Persil[BUG] 

### ISSUE THREAD

**Issue by ai-skematik** [OpenSID/OpenSID#4092]
**Jelaskan error yg dialami**

Pilih Lokasi tidak tampil pada menu tambah persil untuk desa yang hanya memiliki dusun

**Cara untuk mereplikasi errornya**

**Hasil yg diharapkan**

Pilih Lokasi dapat tampil normal seperti desa yang memiliki rt/rw
**Tampakan layar dan log error**

**Versi OpenSID**

premium (v21.03-premium)

**Tema Yg Digunakan**

**Informasi tambahan**

![persil](https://user-images.githubusercontent.com/48144047/112306918-52371480-8cdb-11eb-9275-e19e958883a1.png)

**Comment by ai-skematik** [comment]
@agungsugiarto

**Comment by Zulkarnaimni** [comment]
Pak ai harusnya apa pilihannnya dusun, rt atau rw, barang kali begitu pak?
Saya kemarin sudah berfikir juga kenapa tidak ada pilihan, akan tetapi karena ada pilihan manual ya saya gunakan pilihan ini untuk memasukkan nama dusun sesuai dengan dusun letak lokasi persil.

**Comment by ai-skematik** [comment]
iya, awalnya sy berfikir masalahnya di sistem sy., jd sy juga hanya pakai yg manual.,

**Comment by eddieridwan** [comment]
Sdh dicommit ke `rilis-dev` melalui https://github.com/OpenSID/premium/pull/129
