### ISSUE TITLE
Bug pada Tanda Tangan Sebelah Kiri pada Laporan pada Halaman Cetak Menu Kelompok maupun Data Kelompok [BUG] 

### ISSUE THREAD

**Issue by Zulkarnaimni** [OpenSID/OpenSID#4093]
**Jelaskan error yg dialami**

Bug pada Tanda Tangan Sebelah Kiri pada Laporan pada Halaman Cetak Menu Kelompok maupun Data Kelompok 
![image](https://user-images.githubusercontent.com/64481641/112323804-b3171a80-8ce4-11eb-86ec-aad9298778e6.png)

**Cara untuk mereplikasi errornya**

**Hasil yg diharapkan**

**Tampakan layar dan log error**

**Versi OpenSID**

**Tema Yg Digunakan**

**Informasi tambahan**

**Comment by eddieridwan** [comment]
Sdh dicommit ke `rilis-dev` melalui https://github.com/OpenSID/premium/pull/130
