### ISSUE TITLE
Bug pada Tanda Tangan Sebelah Kiri pada Laporan pada Halaman Cetak Data Suplemen [BUG] 

### ISSUE THREAD

**Issue by Zulkarnaimni** [OpenSID/OpenSID#4094]
**Jelaskan error yg dialami**

**Cara untuk mereplikasi errornya**

**Hasil yg diharapkan**

**Tampakan layar dan log error**

**Versi OpenSID**

**Tema Yg Digunakan**

**Informasi tambahan**

**Comment by Zulkarnaimni** [comment]
![image](https://user-images.githubusercontent.com/64481641/112324413-5c5e1080-8ce5-11eb-9ddd-57e025c36d71.png)

**Comment by eddieridwan** [comment]
Sdh dicommit ke `rilis-dev` melalui https://github.com/OpenSID/premium/pull/130
