### ISSUE TITLE
Bug di fitur balas pesan layanan mandiri

### ISSUE THREAD

**Issue by cepiandiana** [OpenSID/OpenSID#4095]
### Bagaimana alurnya sampai muncul masalah?
Ketika klik balas pesan di admin layanan mandiri, langsung blank page ke url domain/mailbox/form, dan di versi premium pun tidak bisa klik kirim pesan

### Seperti apa yang diharapkan?
Bisa balas pesan seperti yang demo.opensid.my.id

### Apa yang terjadi?
mengarah ke blank page 

### Informasi tambahan 

| Tanya            | Jawab
![pesan3](https://user-images.githubusercontent.com/39004343/112454237-0f347a00-8d8b-11eb-99f3-1980aea7959b.JPG)

| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by agungsugiarto** [comment]
Mas @afa28, apakah ini masih bekarkaitan dengan issue #4088 ?

**Comment by afa28** [comment]
Berarti yg diperbaiki itu yg di rilis umum dan tdk masuk ke premium. Mungkin begitu.

**Comment by cepiandiana** [comment]
mas @afa28 tadi saya coba yang di demo.opensid.my.id lancar mas, bisa kirim pesan / balas pesan, tapi yang di premium ga bisa klik, saya masih pake yang umum juga yang sindanglaya-cipanas.desa.id ini

**Comment by afa28** [comment]
Oh, yg diperbaiki pada bagian layanan mandiri > pesan [https://github.com/OpenSID/OpenSID/commit/0d5c5c82598578025379b06d591b51bbf1ea8c76](https://github.com/OpenSID/OpenSID/commit/0d5c5c82598578025379b06d591b51bbf1ea8c76), bagian admin > mandiri > pesan/mail box gak ikut.

**Comment by cepiandiana** [comment]
jadi yang saya pengaruh apanya ya bung @afa28 ?

**Comment by cepiandiana** [comment]
oh yang diperbaiki di versu 21.03-pasca ya bung?
saya belum instal yang pasca

**Comment by agungsugiarto** [comment]
Issue ini saya tutup karena di versi terbaru v21.03-pasca sudah diperbaiki.

Pembahasan sebelumnya https://web.facebook.com/groups/OpenSID/permalink/1813746945456945/

**Comment by afa28** [comment]
Pak @eddieridwan, mas @agungsugiarto untuk branch yg sudah di merge pada repo premium bisa di hapus.

**Comment by agungsugiarto** [comment]
Mungkin pak @eddieridwan bisa merubah di settings repo untuk auto delete branch ketika pr sudah di merge.

https://docs.github.com/en/github/administering-a-repository/managing-the-automatic-deletion-of-branches
