### ISSUE TITLE
Perbaikan Alur Permohonan Surat Pada Admin

### ISSUE THREAD

**Issue by afa28** [OpenSID/OpenSID#4096]
**Apa kekurangan yg ingin diatasi?**
 Perbaikan Alur Permohonan Surat Pada Admin masih bermasalah dibeberapa bagian.

**Jelaskan solusi yg diinginkan**
 
Pada bagian admin alurnya bermasalah  dan perlu diperbaiki : 
1. admin dapat memproses permohonan yg sudah dibatalkan(belum lengkap), menunggu tanda tangan, siap diambil/diantar dan selesai. Harusnya yang bisa di proses hanya permohonan sedang diperiksa saja atau dibuat bisa di cek dengan ketentuan tombol batal di hilangkan jika statusnya menunggu tanda tangan, siap diambil/diantar dan selesai. Krn akan rancuh jika sudah diproses tp datanya masih bisa di ubah (tp tergantung operatornya).
2. proses dari Sedang diperiksa ke menunggu tanda tangan (saat unduh/cetak surat), untuk ke step selanjutnya harus akses lg  https://premium.id/index.php/permohonan_surat_admin/ baru kemudian bisa dilanjutkan ke ste selanjutnya (kurang efisien). Mungkin alangkah baiknya agar dibuat tdk bolak-balik, pd form periksa dibuat otomatis menunggu tanda tangan jika surat sudah di unduh atau sediakan tombol untuk ke tahap selanjutnya.

**Apakah ada alternatif lain**
 Pembatasan akses periksa surat.
Alur Permohonan Surat : 
1. sedang diperiksa (diproses oleh admin)
2. belum lengkap (dilengkapi oleh warga)
3. menunggu tanda tangan (diproses oleh admin)
4. siap diambil/diantar (diproses oleh admin)
5. selesai (diproses oleh admin)

Penjelasan : 
- Alur 1 ke 2 atau 2 ke 1 bisa di lakukan berkali-kali selama kondisi belum terpenuhi.
- Selain itu tdk boleh ada alur mundur. Misal alur 4 ke 2.

**Untuk versi OpenSID mana**
 OpenSID v21.03-premium-pasca

**Informasi tambahan**
 Bisa di selesaikan jika [PR #128](https://github.com/OpenSID/premium/pull/128) digabungkan karena saling terkait.

**Comment by eddieridwan** [comment]
Sdh dicommit ke `rilis-dev` melalui https://github.com/OpenSID/premium/pull/133
