### ISSUE TITLE
pembuatan pin lyanan mandiri

### ISSUE THREAD

**Issue by Fajar-blackdeath** [OpenSID/OpenSID#4097]
apakah pembuatan id dan pin layanan mandiri bisa dibuatkan secara keseluruhan untuk warga? 
karena jika dibuatkan 1 1 sepertinya kurang efisien.
karena pada dasarnya pada saat membuka layanan mandiri pertama kali warga diwajibkan mengganti pasword

**Comment by agungsugiarto** [comment]
Terimakasih sudah melaporkan permintaan fitur.

Issue ini saya tutup karena duplikat dengan #4015, silahkan diskusi dengan issue terkait. Sebagai catatan mohon untuk selalu menggunakan issue template untuk bug / permintaan fitur dan selalu cek apakah issue duplikat. Terima kasih.
