### ISSUE TITLE
penambahan layanan absen untuk aparatur desa menggunakan sidikjari maupun menggunkan rfid e ktp

### ISSUE THREAD

**Issue by Fajar-blackdeath** [OpenSID/OpenSID#4098]
**Apa kekurangan yg ingin diatasi?**
ingin menmbahkan fitur layanan absen untuk aparatur desa

Beri keterangan singkat dan jelas mengapa fitur ini diperlukan. 
fitur ini diperlukan untuk mengetahui kinerja dari para aparatur dilihat dari kedisplinan aparatur desa. sehingga dapat menjadi acuan untuk kinerja aparatur desa.

**Jelaskan solusi yg diinginkan**
mohon dibuatkan layanan absen aparatur agar terlihat kedisplinan aparatur 

**Apakah ada alternatif lain**
absen bia mengunakan rfid ataupun sidikjari tergantung kemudahan kita. bila ada alat yang lebih murah itu lebih bagus.

Beri keterangan singkat dan jelas solusi lain yg telah anda pertimbangkan untuk kebutuhan ini.
saat ini banyak aparatur desa yang tidak bekerja sesuai dengan tupoksi masing masing dan masih banyak aparatur yang melalikan tugasnya sehingga pelayanan di kantor desa terkadang tersendat akibat keterlambatan aparatur.

**Untuk versi OpenSID mana**
premium
Fitur ini diusulkan untuk versi Rilis Umum (mis. v21.03) atau Rilis Premium (mis v21.03-premium) yg mana?
21.04 

**Informasi tambahan**
mohon ini di utamakan
Beri informasi lainnya yg dapat membantu menjelaskan permintaan ini.
-->
layanan absen aparatur deesaaa

**Comment by agungsugiarto** [comment]
@Fajar-blackdeath terimakasih sudah melaporkan permintaan fitur.

Issue ini akan saya tutup karena duplikat dengan #2033, mohon untuk kembali mengecek sebelum membuat permintaan fitur baru. Nantinya akan ada sesi tanya jawab untuk fitur yg diprioritaskan setiap hari jumat setelah liris. Silahkan ikut andil untuk vote fitur tersebut. Terimakasih,

Pembahasan fitur yg diprioritaskan
https://www.facebook.com/groups/OpenSID/permalink/1812057978959175/?sfnsn=wiwspmo

**Comment by eddieridwan** [comment]
@Fajar-blackdeath , silakan menambahkan penjelasan di https://github.com/OpenSID/OpenSID/issues/2033, kalau ada yg kurang di situ.
