### ISSUE TITLE
Permintaan Penambahan Fitur Alamat Titik Lokasi Persil Dalam Peta Desa

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#4099]
**Apa kekurangan yg ingin diatasi?**
Permintaan Penambahan Fitur alamat Titik Koordinat Lokasi Persil atau "Peta Bidang Tanah" Dalam Peta Desa bila hal dimungkin-kan

**Jelaskan solusi yg diinginkan**
Penambahan tombol menuju lokasi peta, seperti alamat  pada lokasi pembangun fisik di peta desa

![image](https://user-images.githubusercontent.com/64481641/112785100-726d2780-907d-11eb-9aec-de3df0038c5c.png)

ATAU
![image](https://user-images.githubusercontent.com/64481641/112785209-aa746a80-907d-11eb-818e-06dd5c615569.png)

**Apakah ada alternatif lain**

**Untuk versi OpenSID mana**

**Informasi tambahan**

**Comment by Zoel-WB** [comment]
Tepatnya untuk issue ini setelah melakukan konsultasi dengan teman-teman digroup Pelanggan Fitur Premium Telegram, dengan kesimpulan untuk dibawa dalam usulan pertemuan tanggal 02 April 2021 untuk DAFTAR USULAN PRIORITAS 21.05 "Tambahkan titik koordinat bidang tanah di Buku C Desa"

![image](https://user-images.githubusercontent.com/64481641/113304172-f4827800-932b-11eb-98a4-9e3d9f81cf8c.png)
![image](https://user-images.githubusercontent.com/64481641/113304206-0106d080-932c-11eb-8d01-8d3cc9328d8b.png)

**Comment by eddieridwan** [comment]
Sdh dicommit ke `rilis-dev` melalui d967b62fe6cb64826fecff26a3319fee32a24d35

**Comment by hariyanto-85** [comment]
kawan bagaimana saya bisa akses SID PREMIUM

**Comment by afa28** [comment]
> kawan bagaimana saya bisa akses SID PREMIUM

Silahkan langganan pak, bisa hubungi pengurus opendesa. 

Kunjungi opendesa.id

**Comment by eddieridwan** [comment]
> kawan bagaimana saya bisa akses SID PREMIUM

@hariyanto-85 : https://opendesa.id/mengonlinekan-opensid/
