### ISSUE TITLE
[BUG] Error waktu mencari data bantuan penduduk atau keluarga di web

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#4100]
**Jelaskan error yg dialami**

Error waktu mencari data bantuan penduduk atau keluarga di web

**Cara untuk mereplikasi errornya**

1. Tampilkan data peserta bantuan keluarga/penduduk di web
2. Ketik sesuati di kotak cari
3. Lihat error yg tampil

**Hasil yg diharapkan**

Tidak ada error dan data yg dicari ditampilkan.

**Tampakan layar dan log error**

![error-cari](https://user-images.githubusercontent.com/249563/112788305-516cfc80-90a6-11eb-8e97-6fb65412c46c.jpg)

**Versi OpenSID**

v21.03-premium-pasca

**Tema Yg Digunakan**

klasik

**Comment by agungsugiarto** [comment]
Pak @eddieridwan, saya tidak mengalami error tersebut di local saya pakah bapak bisa memperlihatkan error tersebut di log?

**Comment by eddieridwan** [comment]
@agungsugiarto , pakai branch `beta` yg terbaru. Bisa lihat di `https://berputar.opensid.or.id/first/statistik/bantuan_keluarga`.

**Comment by agungsugiarto** [comment]
di branch rilis-dev tidak ada masalah pak eddie, lebih terbaru mana beta dengan rilis-dev ?

**Comment by eddieridwan** [comment]
Terjadi juga di `rilis-dev`. Branch `beta` sama dengan `rilis-dev`, hanya beberapa file di-obfuscate saja. Pastikan menggunakan `rilis-dev` terbaru dan telah migrasi.

**Comment by agungsugiarto** [comment]
Oh ok sudah ketemu, karena ada perubahan dari issue #3999 yg menyebabkan error. Akan saya perbaiki

**Comment by agungsugiarto** [comment]
Sudah di perbaiki melalui commit https://github.com/OpenSID/premium/commit/eb2e638f121026dfca48fcbdcf191a0a7ecb6f40
