### ISSUE TITLE
Perbedaan Jumlah Luas Tanah dari seluruh persil berbeda dgn hitungan manual atau berkurang pada Print Out Fitur Cetak Daftar C-DESA 

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#4101]
**Jelaskan error yg dialami**
Jumlah Luas Tanah dari seluruh persil berbeda dengan hitungan manual atau luas nya berkurang pada print out Fitur Cetak Daftar C-DESA

1. Opensid v21.03 pasca Premium 
![image](https://user-images.githubusercontent.com/64481641/112828981-a74b9f80-90ba-11eb-9757-eaf0817a1f77.png)

![image](https://user-images.githubusercontent.com/64481641/112829048-c1857d80-90ba-11eb-9d4f-5e8cc835213c.png)

2. Opensid v21.03 pasca Premium di berputar.opensid.or.id
![image](https://user-images.githubusercontent.com/64481641/112828624-28566700-90ba-11eb-9ef0-3880155322fb.png)

**Cara untuk mereplikasi errornya**

**Hasil yg diharapkan**

**Tampakan layar dan log error**

**Versi OpenSID**

**Tema Yg Digunakan**

**Informasi tambahan**

**Comment by agungsugiarto** [comment]
Pak @mizwaruddin apakah juga mengalami issue yg sama ?

**Comment by Zoel-WB** [comment]
Tambahan informasi saya, melengkapi issue sebelumnya 
Yang di input dalam persil
![image](https://user-images.githubusercontent.com/64481641/113512233-dae06b00-958d-11eb-805c-3f628bdb344d.png)

hasil dalam print out 
![image](https://user-images.githubusercontent.com/64481641/113512243-f481b280-958d-11eb-875f-2d56e8276e1f.png)

ada terjadi perkalian dalam penjumlah persil.....

**Comment by afa28** [comment]
Jumlah pada print : 
![111111111](https://user-images.githubusercontent.com/57283157/121690957-0c7b3280-caf9-11eb-95a5-a72adbc5130d.png)

Rincian CDesa:
![22222222222](https://user-images.githubusercontent.com/57283157/121690959-0d13c900-caf9-11eb-9d3c-cfa12c9c353f.png)

Rincian Mutasi CDesa:
![33333](https://user-images.githubusercontent.com/57283157/121690944-09804200-caf9-11eb-9156-e9838c7573e7.png)

Yg dijumlahkan adalah Rincian Mutasi C-DESA pada masing2 Rincian C-DESA : 
600 + 5980 + 2580 = 9160

**Comment by afa28** [comment]
Pak @Zoel-WB, dari data bapak ada perbedaan di rincian cdesa dengan rincian mutasi cdesa. Dimana Luas Masuk (M2) yg ada di rincian mutasi CDesa seharusnya sama dengan Luas Keseluruhan Persil (M2) yg ada di Rincian C-DESA untuk Pemilik awal persil ini (Data pertama)

![a1](https://user-images.githubusercontent.com/57283157/121692006-34b76100-cafa-11eb-8ff5-9919b89fbb23.png)
![a2](https://user-images.githubusercontent.com/57283157/121692013-37b25180-cafa-11eb-9b22-4497a312e74f.png)

**Comment by Zoel-WB** [comment]
C-DESA saya punya sebagai acuan contoh :
a. Persil Lahan Kering Harus-nya Total Luas  = 2.923 M2, yang terdiri persil nomor berikut :
    Persil No. 11401  Luas = 1.120 M2
    Persil No. 11403  Luas = 988 M2
    Persil No. 11405 Luas = 815

a. Persil Lahan Basah Harus-nya Total Luas  = 2.164 M2, yang terdiri persil nomor berikut :
    Persil No. 11402  Luas = 964 M2
    Persil No. 11404  Luas = 1.200 M2

**Comment by Zoel-WB** [comment]
Kalau yg ini sepertinya sudah fit 
![gambar](https://user-images.githubusercontent.com/64481641/121724472-21b08b00-cb12-11eb-8f4e-da01b0587488.png)

**Comment by afa28** [comment]
> C-DESA saya punya sebagai acuan contoh :
> a. Persil Lahan Kering Harus-nya Total Luas = 2.923 M2, yang terdiri persil nomor berikut :
> Persil No. 11401 Luas = 1.120 M2
> Persil No. 11403 Luas = 988 M2
> Persil No. 11405 Luas = 815
> 
> b. Persil Lahan Basah Harus-nya Total Luas = 2.164 M2, yang terdiri persil nomor berikut :
> Persil No. 11402 Luas = 964 M2
> Persil No. 11404 Luas = 1.200 M2

ya, kalau menggunakan contoh data bapak atas nama ZULKARNAINI sudah sesuai antara Luas Keseluruhan Persil (M2) yg ada di Rincian C-DESA dan Luas Masuk (M2) yg ada pada masing2 Rincian Mutasi C-DESA.
![1111](https://user-images.githubusercontent.com/57283157/121724479-84a62000-cb1a-11eb-98a2-8283314dbad7.png)

Cuma contoh menggunakan data atas nama TEUPIN BEULANGAN yg bermasalah.

**Comment by afa28** [comment]
Sudah sy PR.

**Comment by Zoel-WB** [comment]
Iya sudah benar.....

**Comment by Zoel-WB** [comment]
Ini sudah fit sepertinya, cuma untuk kolom (HA) dan (M2) agak lebih kecil sedikit lagi, supaya bisa memberi ruang untuk kolom alamat lebih lebar.....

**Comment by eddieridwan** [comment]
Sdh dicommit ke `bug-fix` melalui https://github.com/OpenSID/premium/pull/261
