### ISSUE TITLE
[BUG] Nomor Telepon Desa tidak tampil di "Offline Mode"

### ISSUE THREAD

**Issue by chybcorp** [OpenSID/OpenSID#4102]
**Jelaskan error yg dialami**

Nomor telepon desa tidak tampil pada lama offline mode (maintenance_mode)

**Cara untuk mereplikasi errornya**

Langkah untuk mereplikasi error yg dialami:
1. Masuk ke Folder Desa
2. Edit file offline_mode.php
3. Pada baris 22 lihat deretan code  `<?= $main['Telepon'] ?>`
4. Ganti huruf menjadi `<?= $main['telepon'] ?>` (hanya menjadikan huruf "T" tidak kapital)

**Hasil yg diharapkan**

Semua informasi yang sudah tersimpan dalam database, bisa tampil di semua halaman.

**Tampakan layar dan log error**

![Capture1](https://user-images.githubusercontent.com/34738928/112850688-d2df8180-90dc-11eb-887a-4f49afcd8299.PNG)
![Capture2](https://user-images.githubusercontent.com/34738928/112850788-e7bc1500-90dc-11eb-823d-f8838c64b0fe.PNG)

**Versi OpenSID**

Rilis umum 21.03

**Tema Yg Digunakan**
Natra 4.4

**Comment by eddieridwan** [comment]
Sdh dicommit ke `rilis-dev` dan `master` melalui https://github.com/OpenSID/premium/pull/144
