### ISSUE TITLE
[BUG] [PREMIUM] - Pengaturan offline mode tidak berjalan semestinya

### ISSUE THREAD

**Issue by agungsugiarto** [OpenSID/OpenSID#4104]
**Jelaskan error yg dialami**

Halaman web masih bisa diakses meskipun sudah di rubah ke offline mode

**Cara untuk mereplikasi errornya**
Langkah untuk mereplikasi error yg dialami:
1. Pergi ke halaman Pengaturan/Aplikasi
2. Ubah pengaturan Offline Mode ke  `Web non-aktif sama sekali`

**Hasil yg diharapkan**

Web tidak bisa akses dan tampil mode offline

**Tampakan layar dan log error**

**Versi OpenSID**

Error ini terjadi di rilis/versi: Rilis premim (v21.03-premium-pasca)

**Tema Yg Digunakan**

**Informasi tambahan**

![image](https://user-images.githubusercontent.com/10989147/112927343-06eb8e80-913f-11eb-8285-81d5f6e59049.png)

**Comment by eddieridwan** [comment]
Sdh dicommit ke `rilis-dev` melalui https://github.com/OpenSID/premium/pull/145
