### ISSUE TITLE
[BUG] Tanggal Perkawinan tercatat juga pada anak yang belum Kawin dan Tanggal Perkawinan sama dengan Orang Tua.

### ISSUE THREAD

**Issue by desasoro** [OpenSID/OpenSID#4105]
**Jelaskan error yg dialami**
Tanggal Perkawinan bukan untuk orang tua nya saja.?
Anak tercatat juga Tanggal Perkawinan nya dan sama dengan Tanggal Perkawinan Orang Tua nya.
>>>Di Versi 21.03 dan Versi 21.03-pasca https://demo.opensid.or.id hasilnya sama. Semua sudah diikuti dalam panduan.

**Tampakan layar**
![bug](https://user-images.githubusercontent.com/34540424/112932185-af055580-9147-11eb-886a-70f42ac55513.jpg)

Versi OpenSID

21.03 dan 21.03-pasca

Tema Yg Digunakan

**Informasi tambahan**
Tanggal Perkawinan semua sama menjadi 01-01-1970

**Comment by eddieridwan** [comment]
@desasoro Harap jelaskan langkah sampai terjadinya masalah ini. Misalnya apakah data diisi melalui form penduduk/keluarga atau melalui proses impor. Jika impor, menggunakan format yg mana. Kalau menggunakan proses impor, lampirkan contoh data yg anda gunakan.

Tanpa informasi rinci seperti ini, sangat sulit bagi programmer untuk mengetahui sumber masalahnya, karena belum tentu bisa me-replikasi masalah yg anda alami.

**Comment by desasoro** [comment]
@eddieridwan Data di melalui proses import. Penyebab Tanggal Perkawinan terbaca juga ke anak karena belum mengis Tanggal Perkawinan pada format FormatImportExcel.xls

![image](https://user-images.githubusercontent.com/34540424/112934275-a0b93880-914b-11eb-9d4b-3ca35685ae5a.png)
