### ISSUE TITLE
[BUG] Entry/Edit data penduduk (Premium)

### ISSUE THREAD

**Issue by roaddee** [OpenSID/OpenSID#4106]
**Jelaskan error yg dialami**

Telah dicoba di berputar.opensid.or.id oleh lebih dari 2 orang, saat entry penduduk/edit penduduk mengalami error data gagal disimpan, ketika membiarkan tag_id dalam keadaan kosong.

**Hasil yg diharapkan**

Tidak terjadi kegagalan simpan data penduduk meski tag_id kosong

**Tampakan layar dan log error**

LOG Error :
ERROR - 2021-03-30 13:12:23 --> Query error: Duplicate entry '' for key 'tag_id_card' - Invalid query: INSERT INTO `tweb_penduduk` (`id_kk`, `kk_level`, `id_cluster`, `nik`, `nama`, `ktp_el`, `status_rekam`, `tag_id_card`, `tempat_cetak_ktp`, `tanggal_cetak_ktp`, `no_kk_sebelumnya`, `sex`, `agama_id`, `status`, `akta_lahir`, `tempatlahir`, `tanggallahir`, `waktu_lahir`, `tempat_dilahirkan`, `jenis_kelahiran`, `kelahiran_anak_ke`, `penolong_kelahiran`, `berat_lahir`, `panjang_lahir`, `pendidikan_kk_id`, `pendidikan_sedang_id`, `pekerjaan_id`, `warganegara_id`, `dokumen_pasport`, `tanggal_akhir_paspor`, `dokumen_kitas`, `negara_asal`, `ayah_nik`, `nama_ayah`, `ibu_nik`, `nama_ibu`, `telepon`, `email`, `alamat_sebelumnya`, `alamat_sekarang`, `status_kawin`, `golongan_darah_id`, `cacat_id`, `sakit_menahun_id`, `cara_kb_id`, `hamil`, `id_asuransi`, `no_asuransi`, `bahasa_id`, `ket`, `tanggalperkawinan`, `tanggalperceraian`, `akta_perkawinan`, `akta_perceraian`, `created_by`) VALUES ('1330', '2', '53', '6201023001880200', 'Ariandi Ryan Kahfi', NULL, NULL, '', '', NULL, '', '1', '1', '1', '', 'pANGKALA', '2021-03-25', '', NULL, NULL, NULL, NULL, NULL, NULL, '1', NULL, '1', '1', '', NULL, NULL, '', '', 'AFRAFA', '', 'AFAWF', '', '', '', '', '1', '4', NULL, NULL, NULL, 0, NULL, NULL, '0', '', NULL, NULL, '', '', '1')
ERROR - 2021-03-30 13:14:15 --> Query error: Duplicate entry '' for key 'tag_id_card' - Invalid query: INSERT INTO `tweb_penduduk` (`id_kk`, `kk_level`, `id_cluster`, `nik`, `nama`, `ktp_el`, `status_rekam`, `tag_id_card`, `tempat_cetak_ktp`, `tanggal_cetak_ktp`, `no_kk_sebelumnya`, `sex`, `agama_id`, `status`, `akta_lahir`, `tempatlahir`, `tanggallahir`, `waktu_lahir`, `tempat_dilahirkan`, `jenis_kelahiran`, `kelahiran_anak_ke`, `penolong_kelahiran`, `berat_lahir`, `panjang_lahir`, `pendidikan_kk_id`, `pendidikan_sedang_id`, `pekerjaan_id`, `warganegara_id`, `dokumen_pasport`, `tanggal_akhir_paspor`, `dokumen_kitas`, `negara_asal`, `ayah_nik`, `nama_ayah`, `ibu_nik`, `nama_ibu`, `telepon`, `email`, `alamat_sebelumnya`, `alamat_sekarang`, `status_kawin`, `golongan_darah_id`, `cacat_id`, `sakit_menahun_id`, `cara_kb_id`, `hamil`, `id_asuransi`, `no_asuransi`, `bahasa_id`, `ket`, `tanggalperkawinan`, `tanggalperceraian`, `akta_perkawinan`, `akta_perceraian`, `created_by`) VALUES ('1330', '9', '53', '6201024708880006', 'Peraturan Desa', NULL, NULL, '', '', NULL, '', '1', '1', '1', '', 'Tempat', '2021-03-11', '', NULL, '1', NULL, NULL, NULL, NULL, '1', NULL, '1', '1', '', NULL, NULL, '', '', 'sfa', '', 'afaf', '', '', '', '', '1', '4', NULL, NULL, NULL, 0, NULL, NULL, '0', '', NULL, NULL, '', '', '1')
ERROR - 2021-03-30 13:27:06 --> Query error: Incorrect datetime value: '-' for column `berp_lengkap_opensid`.`log_penduduk`.`tgl_lapor` at row 1 - Invalid query: UPDATE `log_penduduk` SET `tgl_peristiwa` = '1990-09-02', `tgl_lapor` = '-', `updated_at` = '2021-03-30 13:27:06', `updated_by` = '1', `maksud_tujuan_kedatangan` = ''
WHERE `id_pend` = '4759'
AND `kode_peristiwa` IN(1, 5)
ERROR - 2021-03-30 13:27:36 --> Query error: Incorrect datetime value: '-' for column `berp_lengkap_opensid`.`log_penduduk`.`tgl_lapor` at row 1 - Invalid query: UPDATE `log_penduduk` SET `tgl_peristiwa` = '1990-09-02', `tgl_lapor` = '-', `updated_at` = '2021-03-30 13:27:36', `updated_by` = '1', `maksud_tujuan_kedatangan` = ''
WHERE `id_pend` = '4759'
AND `kode_peristiwa` IN(1, 5)
ERROR - 2021-03-30 13:27:36 --> Query error: Duplicate entry '' for key 'tag_id_card' - Invalid query: UPDATE `tweb_penduduk` SET `nama` = 'FALAH JUNA', `ktp_el` = '2', `status_rekam` = '4', `tag_id_card` = '', `tempat_cetak_ktp` = 'testing', `tanggal_cetak_ktp` = '2021-03-30', `no_kk_sebelumnya` = '', `kk_level` = '9', `sex` = '1', `agama_id` = '1', `status` = '2', `akta_lahir` = '', `tempatlahir` = 'DEMAK', `tanggallahir` = '1990-09-02', `waktu_lahir` = '', `tempat_dilahirkan` = NULL, `jenis_kelahiran` = NULL, `kelahiran_anak_ke` = NULL, `penolong_kelahiran` = NULL, `berat_lahir` = NULL, `panjang_lahir` = NULL, `pendidikan_kk_id` = '5', `pendidikan_sedang_id` = '18', `pekerjaan_id` = '15', `warganegara_id` = '1', `dokumen_pasport` = '', `tanggal_akhir_paspor` = NULL, `dokumen_kitas` = NULL, `negara_asal` = NULL, `ayah_nik` = '', `nama_ayah` = 'AHMAD FAROHI', `ibu_nik` = '', `nama_ibu` = 'NASIHAH', `id_cluster` = '56', `telepon` = '085777722292', `email` = '', `alamat_sebelumnya` = '', `alamat_sekarang` = '', `status_kawin` = '1', `golongan_darah_id` = '13', `cacat_id` = '7', `sakit_menahun_id` = '14', `cara_kb_id` = NULL, `hamil` = 0, `id_asuransi` = '1', `no_asuransi` = NULL, `bahasa_id` = '1', `ket` = '', `tanggalperkawinan` = NULL, `tanggalperceraian` = NULL, `akta_perkawinan` = '', `akta_perceraian` = '', `updated_at` = '2021-03-30 13:27:36', `updated_by` = '1'
WHERE `id` = '4759'

**Versi OpenSID**

Premium (v21.03-premium)?

**Tema Yg Digunakan**

**Informasi tambahan**

Kami sudah coba meng null kan seluruh tag_id, namun begitu isi baru, data penduduk dimaksud tag_id nya akan kosong.

**Comment by eddieridwan** [comment]
Sdh dicommit ke `rilis-dev` melalui https://github.com/OpenSID/premium/pull/146
