### ISSUE TITLE
bahasa indonesia

### ISSUE THREAD

**Issue by SidarthaG39** [OpenSID/OpenSID#4107]
**Apa kekurangan yg ingin diatasi?**

**Jelaskan solusi yg diinginkan**

**Apakah ada alternatif lain**

**Untuk versi OpenSID mana**

**Informasi tambahan**

**Comment by eddieridwan** [comment]
@SidarthaG39 , issue ini ditutup, karena tidak jelas apa yg dilaporkan. Setiap judul di template issue perlu diisi. Komentar umum seperti ini tidak bisa ditindak-lanjuti. Silakan buka lagi setelah anda jelaskan persisnya apa yg ingin diubah.
