### ISSUE TITLE
fitur absen

### ISSUE THREAD

**Issue by Fajar-blackdeath** [OpenSID/OpenSID#4111]
[absen format.xlsx](https://github.com/OpenSID/OpenSID/files/6237577/absen.format.xlsx)
[penggunan rfid atau finger print.docx](https://github.com/OpenSID/OpenSID/files/6237578/penggunan.rfid.atau.finger.print.docx)
[penggunan rfid atau finger print.docx](https://github.com/OpenSID/OpenSID/files/6237580/penggunan.rfid.atau.finger.print.docx)
[absen format.xlsx](https://github.com/OpenSID/OpenSID/files/6237583/absen.format.xlsx)
[penggunan rfid atau finger print.docx](https://github.com/OpenSID/OpenSID/files/6237585/penggunan.rfid.atau.finger.print.docx)

Apa kekurangan yg ingin diatasi?
ingin menmbahkan fitur layanan absen untuk aparatur desa

Beri keterangan singkat dan jelas mengapa fitur ini diperlukan.
fitur ini diperlukan untuk mengetahui kinerja dari para aparatur dilihat dari kedisplinan aparatur desa. sehingga dapat menjadi acuan untuk kinerja aparatur desa.

Jelaskan solusi yg diinginkan
mohon dibuatkan layanan absen aparatur agar terlihat kedisplinan aparatur

Apakah ada alternatif lain
absen bia mengunakan rfid ataupun sidikjari tergantung kemudahan kita. bila ada alat yang lebih murah itu lebih bagus.

Beri keterangan singkat dan jelas solusi lain yg telah anda pertimbangkan untuk kebutuhan ini.
saat ini banyak aparatur desa yang tidak bekerja sesuai dengan tupoksi masing masing dan masih banyak aparatur yang melalikan tugasnya sehingga pelayanan di kantor desa terkadang tersendat akibat keterlambatan aparatur.

Untuk versi OpenSID mana
premium
Fitur ini diusulkan untuk versi Rilis Umum (mis. v21.03) atau Rilis Premium (mis v21.03-premium) yg mana?
21.04

file ada di lampiran

**Comment by agungsugiarto** [comment]
@Fajar-blackdeath terima kasih sudah melaporkan permintaan fitur, issue ini saya tutup karena dupikat dengan #2033.
