### ISSUE TITLE
Penambahan fitur IOT add RFID dan Chatbot untuk desa Gogodalem

### ISSUE THREAD

**Issue by Atyanta** [OpenSID/OpenSID#4112]
Kami dari tim pengembang desa Gogodalem Kabupaten Semarang,

**Apa kekurangan yg ingin diatasi?**
 KTP Elektronik yang berRFID dapat menjadi account untuk validasi BLT, dsb
--> pemanfaatan Chatbot yang digunakan untuk membantu operator menjawab FAQ

**Jelaskan solusi yg diinginkan**

**Apakah ada alternatif lain**

**Untuk versi OpenSID mana**

**Informasi tambahan**
 Kami membantu mengerjakan dan menambahkan fitur tersebut diatas, semoga admin/momod menyutujuinya. Kami kembangkan sebagai percontohan di desa Gogodalem.
terimakasih.

**Comment by agungsugiarto** [comment]
Terima kasih @Atyanta, kami tunggu PR anda di OpenSID semoga bisa bermanfaat bagi banyak desa.

**Comment by Pambudieky** [comment]
Hidup desa gogodalem!! Saya yakin sangat bermanfaat mas
