### ISSUE TITLE
[BUG] Pencarian Nama Penduduk yang Mengandung Tanda Baca Tidak Bisa Ditampilkan

### ISSUE THREAD

**Issue by mizwaruddin** [OpenSID/OpenSID#4113]
**Jelaskan error yg dialami**

Pencarian nama yang mengandung tanda baca, misal: titik, koma, aprostop (') tidak berfungsi.

**Cara untuk mereplikasi errornya**

**Hasil yg diharapkan**
 Pencarian nama yang mengandung tanda baca, misal: titik, koma, aprostop (') dapat berjalan normal.

**Tampakan layar dan log error**

**Versi OpenSID**

(v21.03 pasca -premium)

**Tema Yg Digunakan**

**Informasi tambahan**

**Comment by agungsugiarto** [comment]
di pecarian modul apa saja pak @mizwaruddin ?

**Comment by mizwaruddin** [comment]
Saya cek di modul bantuan lancar. Yg baru ketemu di modul kependudukan.

**Comment by agungsugiarto** [comment]
Iya semua pencarian yg mengandung tannda baca akan di escape 

```php
protected function search_sql()
{
	if ($this->session->cari)
	{
		$cari = $this->session->cari;
		$cari = $this->db->escape_like_str($cari);
		$this->db
			->group_start()
				->like('u.nama', $cari)
				->or_like('u.nik', $cari)
				->or_like('u.tag_id_card', $cari)
			->group_end();
	}
}
```

Menghilangkan escape kemungkinan akan menjadi celah

**Comment by agungsugiarto** [comment]
Coba kita dengar pendapat dari mas @ndunks

**Comment by ndunks** [comment]
Tanda petik atau yang lainnya meskipun di escape akan tetap bekerja di query. Harus di cek lebih lanjut.
- Dilihat data nama yang dimaksud tersimpan seperti apa di dlm database.
- di log value / post get requestnya, barangkali URL Escaped
- terakhir jika masih ndak ketemu, di log querynya dari CI

**Comment by ndunks** [comment]
Ah baru baca kalo pencarian di simpan di session ya? Maka perlu di coba ini
```
$cari = url_decode(..)(
```

**Comment by agungsugiarto** [comment]
urldecode tidak akan bekerja karen escape dilakukan di query bukan dari request mas.

**Comment by ndunks** [comment]
Jika hasilnya `fa\\\'is` berarti itu double escaped. harusnya `fa\'is`

**Comment by ndunks** [comment]
Apakah error hanya di `autocomplete` saja?
saya cek ketika pencarian mengandung petik satu dengan tekan 'enter' maka tampil, tapi di autocomplete tidak tampil karena kurang `url_decode`. Jika memang hanya diautocomple maka PR sudah bisa saya kirim.

**Comment by mizwaruddin** [comment]
Saya coba dg mengetikkan Ah. kemudian sya enter bisa tampil. Tp beda cerita ketika sya menhgetikkan Sa' kemudian enter, data ttp tdk tampil.

**Comment by ndunks** [comment]
di web demo saya cek permasalahan hanya muncul di autocomple, ketika di enter (POST) muncul. karena pada saat pencarian (bukan autocomplete) `$cari` tidak melalui double escape.

![image](https://user-images.githubusercontent.com/5500313/113283152-14a53d80-9312-11eb-96c5-bf65dc1add14.png)

**Comment by mizwaruddin** [comment]
Silakan coba di web berputar.opensid.or.id.
![Screenshot_2021-04-01-17-53-10-70.jpg](https://user-images.githubusercontent.com/39736008/113284035-3d7a0280-9313-11eb-9c60-509d937c6478.jpg)

**Comment by ndunks** [comment]
apakah itu dari repo premium? saya tidak ada akses ke repo itu jadi mohon maaf belum bisa mengecek

**Comment by mizwaruddin** [comment]
Betul.

**Comment by agungsugiarto** [comment]
ada disini mas

Controller
https://github.com/OpenSID/OpenSID/blob/b007489dc958012330caaeaab61e9ee7233c4c76/donjo-app/controllers/Penduduk.php#L730-L734

Model
https://github.com/OpenSID/OpenSID/blob/b007489dc958012330caaeaab61e9ee7233c4c76/donjo-app/models/Penduduk_model.php#L64-L67

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui https://github.com/OpenSID/OpenSID/pull/4117
