### ISSUE TITLE
[Layanan Mandiri] : layanan mandiri e taping belum masih ada kekurangan

### ISSUE THREAD

**Issue by Fajar-blackdeath** [OpenSID/OpenSID#4115]
**Apa kekurangan yg ingin diatasi?**

terlalu susah karena harus memindahkan kursor.

**Jelaskan solusi yg diinginkan
sebaiknya
1. meletkan scn ktp pada kolom pertama. 
 kemudian setelah di scan masuk ke mnu baru yaitu masukan pin 
2. baru msukan pin kita seperti di atm.

secara garis besar dteksi kartu kemudian baru masukan pi. hal ini dikarenakan rfid saat membaca pin langsung memerintah tombol enter,
-->

**Apakah ada alternatif lain

**Untuk versi OpenSID mana**

**Informasi tambahan**

**Comment by agungsugiarto** [comment]
cc @fusionid
