### ISSUE TITLE
[Layanan Mandiri] : Optimalkan Fitur Scan eKTP

### ISSUE THREAD

**Issue by cepiandiana** [OpenSID/OpenSID#4116]
**Apa kekurangan yg ingin diatasi?**
Optimalkan sistem scan ektp. 

**Jelaskan solusi yg diinginkan**
1. ketika sudah diregistrasi dengan tag ID eKTP, tidak perlu lagi didaftarkan di Pendaftar Layanan Mandiri, bisa otomatis terdaftar di pendaftar layanan mandiri, otomatis juga generate PIN standard 123456 karena setelah login pertama kali pun diarahkan untuk mengganti PIN, biar operator tidak muter2 antara tag id dan mendaftarkan di pendaftar layanan mandiri, dan password pun nantinya bisa sesuai kemauan warga login pertama kali.

2. Memasukkan PIN setelah scan ektp, kalau memang acuannya seperti ATM, maka setelah sistem membaca data maka meminta PIN sebagai verifikasi.

**Apakah ada alternatif lain**
Khusus login layanan mandiri yang menggunakan scan ektp, agar sesederhana mungkin untuk bisa login 

**Untuk versi OpenSID mana**
v21.04-premium

**Informasi tambahan**
Fitur Scan KTP ini mungkin bisa menjadi keunggulan dan kebanggaan desa pengguna openSID jika sistem loginnya dibuat simpel dan terkesan tidak muter2 ketika mau login dan daftar

**Comment by Zoel-WB** [comment]
Mantap..

**Comment by agungsugiarto** [comment]
cc @fusionid

**Comment by lihin20** [comment]
setuju

**Comment by eddieridwan** [comment]
@cepiandiana Kemudahan tanpa mengorbankan keamanan. Di situ tantangannya. Pikirkan juga skenario penyalahgunaan dan bagaimana mencegahnya.
