### ISSUE TITLE
[BUG] Nomor Indikator Pertanyaan pada Modul Analisis Tidak Urut

### ISSUE THREAD

**Issue by mizwaruddin** [OpenSID/OpenSID#4118]
**Jelaskan error yg dialami**

Indikator pertanyaan pada modul analisis tidak urut seperti pada umumnya: 1, 2, 3, dst melainkan urutan nomor dimulai dari 1, 10-19, 2, 20-29 dst. Hal tersebut membuat pertanyaan yang disusun melompat-lompat.
![bug analisis](https://user-images.githubusercontent.com/39736008/113322152-8a270300-933e-11eb-8335-a64efb2d422a.png)

**Cara untuk mereplikasi errornya**
 
1. Pergi ke halaman 'analisis'
2. Pilih judul analisis yang diharapkan, mis: SDGs Rumah Tangga
3. Klik Input Data Sensus/Survei
4. Lihat nomor urut pertanyaan.

**Hasil yg diharapkan**
 Pertanyaan dapat urut sesuai dengan nomor urut: 1, 2, 3, dst

**Tampakan layar dan log error**

**Versi OpenSID**
Premium 21.04

**Tema Yg Digunakan**

**Informasi tambahan**

**Comment by mizwaruddin** [comment]
Untuk menyiasatinya saat ini:
Misal jumlah pertanyaan ada 150, maka pada pertanyaan 1 s.d. 99 sya tambahkan angka nol di depan. 001, 002, 003, s.d. 099.

**Comment by eddieridwan** [comment]
Sdh dicommit ke `bug-fix` melalui https://github.com/OpenSID/premium/pull/149
