### ISSUE TITLE
Permintaan Tambahan Fitur Cek Data Warga di Website Desa

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#4119]
**Apa kekurangan yg ingin diatasi?**

Memudahkan masyarakat melakukan pengecekan status warga apakah sudah terdata di database desa atau tidak..

**Jelaskan solusi yg diinginkan**
 seperti mirip dengan pencarian pada apalikasi SIKS-NG untuk data DTKS. atau seperti cek KTP-ku, cek BPJS dan lainnya, bentuk fitur bisa jadi sama dengan bentuk fitur layanan mandiri, cuma hanya untuk keperluan pengecekan data warga apakah datanya sudah terdata di database desa.

Bisa seperti bentuk tampilan layanan mandiri

**Apakah ada alternatif lain**

**Untuk versi OpenSID mana**

**Informasi tambahan**

**Comment by eddieridwan** [comment]
@Zoel-WB permintaan seperti ini sudah dilaporkan berkali-kali, dan dianggap menimpulkan celah privasi data, karena bisa digunakan untuk menebak NIK warga yg valid. Kecuali ada yg bisa menjelaskan secara rinci pengamanan apa yg ada di aplikasi SIKS-NG untuk data DTKS. atau seperti cek KTP-ku, cek BPJS dan lainnya untuk menjaga hal tersebut. 

Sebagai aplikasi yg harus terpercaya dan harus bisa lolos audit keamanan dari pihak2 lain, OpenSID tidak boleh mengorbankan keamanan demi kemudahan. 

Pengamanan yg diperlukan adalah cara supaya yg dapat berhasil memeriksa terdaftar tidaknya seseorang hanya warga ybs, dan bukan sembarang orang. Jadi jangan sampai si A bisa melihat apakah si B sdh terdaftar.

Salah satu kemungkinan adalah dengan mengharuskan mengisi informasi tambahan (idealnya dua) selain NIK yang seharusnya hanya diketahui warga ybs, misalnya:
1. No. KK
2. Tempat lahir atau informasi lain yg tertera di KTP atau di KK (yg bukan bagian dari NIK)

Perhatikan bahwa `tanggal lahir` tidak bisa digunakan, karena tanggal lahir merupakan bagian dari NIK.

Tentunya cara ini akan menambah beban yg menggunakan fitur ini. Tapi seperti itulah yg diperlukan untuk menjaga keamanan aplikasi.

**Comment by eddieridwan** [comment]
Duplikat https://github.com/OpenSID/OpenSID/issues/3285.

Issue ini akan ditutup karena duplikat. Silakan tambahkan informasi di https://github.com/OpenSID/OpenSID/issues/3285 jika perlu.

**Comment by Zoel-WB** [comment]
Baik Pak @eddieridwan saya coba buka issue #3285, terimakasih sebelumnya....
