### ISSUE TITLE
Tampilkan evaluasi SDGs Kemendesa di web OpenSID

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#4121]
**Apa kekurangan yg ingin diatasi?**

**Jelaskan solusi yg diinginkan**

**Apakah ada alternatif lain**

**Untuk versi OpenSID mana**

**Informasi tambahan**

**Comment by apidong** [comment]
**Apa kekurangan yg ingin diatasi?**
Permintaan fitur untuk menampilkan data SDGs kemendesa  ke dalam Web OpenSID. 


**Jelaskan solusi yg diinginkan**
men-scraping halaman SDGs kemendesa yang pada halaman sid.kemendesa.go.id/home/sdgs/{$kode_desa}. hasil dari scraping hanya mengambil data yg diperlukan dan menyediakan data tersebut bagi tema — tidak termasuk htmlnya. Dan biarkan masing2 tema menampilkan data tsb sesuai tema.
scraping menggunakan library **_PHP Simple HTML DOM Parser_** dimana penggunaanya mirip dengan selector pada Jquery sehingga jika ada perubahan struktur CSS pada halaman kemendesa, dapat meminimalisir perubahan code.
target selector nantinya adalah class  **accordion-stn**, karena Class tersebut bisa mewakili 2 data sebelah kiri dan kanan.
![image](https://user-images.githubusercontent.com/20056421/113573193-d4acc600-9643-11eb-86b3-51d7a2215319.png)

**Apakah ada alternatif lain**

**Untuk versi OpenSID mana**

**Informasi tambahan**

**Comment by eddieridwan** [comment]
@apidong , silakan lihat materi di bawah terkait SDGs. Analisis SDGs nanti akan disediakan di OpenSID sebagai analisis bawaan sistem. 

[1. KUESIONER INDIVIDU SDGs DESA.pdf](https://github.com/OpenSID/OpenSID/files/6258230/1.KUESIONER.INDIVIDU.SDGs.DESA.pdf)
[2. KUESIONER RUMAH TANGGA (KELUARGA-KK) SDGs DESA.pdf](https://github.com/OpenSID/OpenSID/files/6258231/2.KUESIONER.RUMAH.TANGGA.KELUARGA-KK.SDGs.DESA.pdf)
[3. KUESIONER RUKUN TETANGGA (RT) SDGs DESA.pdf](https://github.com/OpenSID/OpenSID/files/6258232/3.KUESIONER.RUKUN.TETANGGA.RT.SDGs.DESA.pdf)
[4. KUESIONER DESA SDGs DESA.pdf](https://github.com/OpenSID/OpenSID/files/6258233/4.KUESIONER.DESA.SDGs.DESA.pdf)
[Analisis SDGs Desa (Individu).xlsx](https://github.com/OpenSID/OpenSID/files/6258234/Analisis.SDGs.Desa.Individu.xlsx)
[Analisis SDGs Desa (Rumah Tangga).xlsx](https://github.com/OpenSID/OpenSID/files/6258235/Analisis.SDGs.Desa.Rumah.Tangga.xlsx)

**Comment by apidong** [comment]
@eddieridwan  jadi nanti ada 2 ya pak. yang pertama mengambil dari kemendes, yang kedua dari OpenSID. 
untuk yang disediakan OpenSID, uraian pertanyaan sesuai dengan yang ada pada file pdf itu ya pak?

**Comment by eddieridwan** [comment]
@apidong , ringkasnya:
1. Lihat method `status_idm()` di `donjo-app/controllers/First.php`. Buat method serupa untuk menampilkan status SDGs.
2. Tetapi karena proses pengambilan data SDGs lebih rumit, buatkan model terpisah dan lakukan di situ. Untuk bisa digunakan bagi pengambilan data eksternal serupa lainnya, buat model baru, `donjo-app/models/data_eksternal.php`.
3. Di model itu, prosesnya seperti berikut:
    i. siapkan array tempat menyimpan data SDGs, sesuai dengan Kuesioner Desa SDGs Desa (pastikan sama dengan struktur yg ada di halaman Kemendesa). 
    ii. ambil isi halaman SDGs desa dari Kemendesa
    iii. isi array di (i) dengan data yg ada di isi halaman (ii)
    iv. kirim hasil array yg sudah dilengkapi ke controller (1)

**Comment by apidong** [comment]
![image](https://user-images.githubusercontent.com/20056421/113837066-ac45d880-97b7-11eb-9884-94f0fd4e2a1e.png)

data file pdf dengan data yang kita lihat di halaman kemendes saat pembahasan kemarin berbeda. 
kalau di kemendes, datanya lebih ke kesimpulan. Sedangkan data yang di file pdf seperti data mentah yang perlu diolah lagi.

**Comment by eddieridwan** [comment]
@apidong kalau begitu, strukturnya terpaksa juga harus diambil dari halaman Kemendes. Sepertinya yg di Kemendes adalah evaluasi hasil data yg diisi melalui ke-empat Kuesioner tsb,

**Comment by eddieridwan** [comment]
Sdh dicommit ke `rilis-dev` melalui https://github.com/OpenSID/premium/pull/189
