### ISSUE TITLE
Mengirim Buku Rekap Jumlah Penduduk ke OpenDK melalui API

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#4122]
**Apa kekurangan yg ingin diatasi?**

**Jelaskan solusi yg diinginkan**

- [ ] Laporan yg dikirim adalah yg di menu Buku Administrasi Desa > Administrasi Penduduk > Buku Rekapitulasi Jumlah Penduduk. 
- [ ] Laporan dikirim untuk tahun/bulan tertentu
- [ ] Laporan dikirim dalam format PDF yang telah ditandatangani Kades. Penandatangan dilakukan secara elektronik oleh akun Kades. Yaitu Kades perlu login dan menyatakan bahwa laporan tersebut siap untuk dikirim. Waktu penandatangan dicatat dan ditampilkan.
- [ ] Laporan dibubuhi QR Code untuk verifikasi laporannya betul diterbitkan oleh desa ybs.
- [ ] File PDF yg dikirim akan tersimpan di OpenSID dan dapat dilihat di daftar pengiriman ke OpenDK.
- [ ] Tgl pengiriman akan tercatat dan ditampilkan.
- [ ] Pengiriman dilakukan menggunakan API OpenDK yg dibuat untuk issue https://github.com/OpenSID/OpenDK/issues/183.
- [ ] Setiap pengiriman akan menimpa laporan untuk tahun/bulan yg dikirim sebelumnya.
- [ ] Laporan yg telah dikirim tidak dapat dihapus.
- [ ] Laporan yg telah dikirim dapat dibuat ulang. Jika dibuat ulang, perlu ditandai jika belum dikirim ulang ke OpenDK.

**Apakah ada alternatif lain**

**Untuk versi OpenSID mana**

v21.08-premium

**Informasi tambahan**

Nanti (tidak issue ini), data terkait juga akan dikirim, jika ada keperluan di OpenDK untuk menyusun laporan turunan yg diperlukan kabupaten atau instansi supra-kecamatan lainnya.

**Comment by afa28** [comment]
Pak @eddieridwan, di OpenSID data yg mana dimaksud??? Apakah perlu diunggah terlebih dahulu???

**Comment by eddieridwan** [comment]
Laporan Statistik > Laporan Bulanan

**Comment by afa28** [comment]
Untuk melanjutkan issue ini, menunggu PR https://github.com/OpenSID/premium/pull/357 digabung krn berkaitan mengenaik: 
- [ ] Laporan dibubuhi QR Code untuk verifikasi laporannya betul diterbitkan oleh desa ybs.

Agar lebih konsisten mengenai verifikasi berkas.
