### ISSUE TITLE
Sediakan tombol isian manual keterangan jabatan pada menu Kelompok

### ISSUE THREAD

**Issue by muhtar-coder** [OpenSID/OpenSID#4124]
### Bagaimana alurnya sampai muncul masalah?
Mencari fitur yang dapat menyajikan data kelompok atau kelembagaan yang belum tersedia di opensid seperti untuk lembaga RT dll.

### Seperti apa yang diharapkan?
![image](https://user-images.githubusercontent.com/55665526/113606183-db523200-9671-11eb-9533-89ebd157d3b6.png)

Dapat memanfaatkan fitur kelompok untuk kebutuhan penyiapan dan penyajian data kelompok atau kelembagaan di desa berdasarkan data yang di butuhkan,data yang di butuhkan tidak jauh berbeda dengan data kelompok,hanya saja di perlukan fleksibilitas dalam pemberian keterangan seperti status jabatan yang sama untuk semua daftar nama. memang sacara organisasi sebutan ketua hanya berlaku untuk satu ketua,namun untuk ketua RT berlaku menjadi ketua semua daftar namanya untuk wilayah masing2.

>>karena belum ada penyesuaian keterangan jabatan maka hasil sementara hanya seperti berikut :

(view website desa)

![image](https://user-images.githubusercontent.com/55665526/113606628-7945fc80-9672-11eb-9a96-8be6e62f48a2.png)

(view admin)

![image](https://user-images.githubusercontent.com/55665526/113607007-eeb1cd00-9672-11eb-908f-79cd0f5ed625.png)

 
seperti pada link ini : https://cugung-rajabasa.desa.id/first/kelompok/13

### Apa yang terjadi?
- data lebih mudah dibuat dan di sajikan sesuai kebutuhan
- memanfaatkan menu yg sudah ada dan output yang sama dan sesuai kebutuhan.
- tidak perlu menambah menu baru khusus
- kelengkapan fitur opensid

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by Nurhidayat29** [comment]
sepertinya lebih baik sekalian manual saja tanpa ada pilihan, sama seperti mengisi jabatan dipemdes.

**Comment by afri18** [comment]
Tinggal di tambah jan ketua rt 002 , pasti beda sama ketua rt 001 , ataubmsu dijadikan kelompok buat nta jangan hanya rt  tapi kelompok rt.002 , kelompok rt 001 , pasti banyak ketua rt nya, lagian pengurus rt hanya ada di warga, tidak masuk sistem semisalnya bpd atau pkk

**Comment by eddieridwan** [comment]
Sdh dicommit ke `rilis-dev` melalui https://github.com/OpenSID/premium/pull/200
