### ISSUE TITLE
Sediakan upload script surat tanpa melalui CPanel

### ISSUE THREAD

**Issue by mizwaruddin** [OpenSID/OpenSID#4126]
**Apa kekurangan yg ingin diatasi?**

Saat ini jika desa ingin menambahkan surat baru--yang di luar standar bawaan sistem--pengguna harus mengunggahnya melalui CPanel. Kondisi seperti ini sangat membatasi pengguna yang tidak memiliki akses masuk ke CPanel (ikut hosting pemda).

**Jelaskan solusi yg diinginkan**

Tambahkan upload script surat melalui dashboard admin sebagaimana upload format surat.

**Apakah ada alternatif lain**

**Untuk versi OpenSID mana**

**Informasi tambahan**

**Comment by Fajar-blackdeath** [comment]
Mantav

**Comment by Fajar-blackdeath** [comment]
Mantab.

**Comment by eddieridwan** [comment]
@mizwaruddin fitur ini tidak dapat diterapkan selama masih ada potensi celah keamanan, di mana peretas dapat mengunduh file PHP sembarang, yang mungkin saja dapat mengakses/merusak tidak saja website bercelah, tetapi semua website di server hosting ybs. Belum ditemukan solusi teknis untuk hanya boleh mengunggah file PHP terpercaya saja.
