### ISSUE TITLE
Membuat Controller untuk membuat link untuk menampilkan lapak online misalnya desa.desa.id/lapak

### ISSUE THREAD

**Issue by adiskom** [OpenSID/OpenSID#4127]
**Apa kekurangan yg ingin diatasi?**

**Jelaskan solusi yg diinginkan**

**Apakah ada alternatif lain**

**Untuk versi OpenSID mana**

**Informasi tambahan**

**Comment by agungsugiarto** [comment]
@adiskom terima kasih sudah melaporkan permintaan fitur,

issue ini saya close karena duplikat dengan #3541, silahkan tanbahkan di issue tersebut jika dirasa masih kurang. Sebagai catatan harap memeriksa terlebih dahulu di pencarian issue ketika ingin membuat issue. Terima kasih
