### ISSUE TITLE
 [BUG] Tambah data penduduk di menu keluarga gagal "Query error duplicate tag_id_card"

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#4129]
**Jelaskan error yg dialami**
 Query error: Duplicate entry '' for key 'tag_id_card' - Invalid query: INSERT INTO tweb_penduduk (nik, nama, ktp_el, status_rekam, tag_id_card, tempat_cetak_ktp, tanggal_cetak_ktp, no_kk_sebelumnya, kk_level, sex, agama_id, status, akta_lahir, tempatlahir, tanggallahir, waktu_lahir, tempat_dilahirkan, jenis_kelahiran, kelahiran_anak_ke, penolong_kelahiran, berat_lahir, panjang_lahir, pendidikan_kk_id, pendidikan_sedang_id, pekerjaan_id, warganegara_id, dokumen_pasport, tanggal_akhir_paspor, dokumen_kitas, negara_asal, ayah_nik, nama_ayah, ibu_nik, nama_ibu, id_cluster, telepon, email, alamat_sebelumnya, status_kawin, akta_perkawinan, tanggalperkawinan, golongan_darah_id, cacat_id, sakit_menahun_id, cara_kb_id, hamil, id_asuransi, no_asuransi, bahasa_id, ket, tanggalperceraian, akta_perceraian, alamat_sekarang, created_by) VALUES ('3321130404890004', 'AHMAD IRFAN', '2', '4', '', '', NULL, '', 1, '1', '1', '1', '', 'DEMAK', '1989-04-27', '09:33', '2', '1', NULL, '2', NULL, NULL, '3', '18', '15', '1', '', NULL, NULL, '', '', 'MUSDI', '', 'NUR HIDAYAH', '76', '', '', '', '2', '0182/53/V/2016', '2016-05-19', '13', '7', '14', NULL, 0, '2', '0000602354777', '0', '', NULL, '', '', '64')

Harap tidak melaporkan masalah instal OpenSID. Masalah pada waktu install harap ditanyakan di https://www.facebook.com/groups/OpenSID atau di https://t.me/joinchat/SI0GWHeqKT39Gxhh, karena terkait sistem masing2 pengguna. 

Berikan keterangan yg jelas dan singkat mengenai error yg dialami. 
duplicate tag_id_card

Pastikan error ini juga ditemukan di https://demo.opensid.or.id (untuk RIlis Umum) atau di https://berputar.opensid.or.id (untuk RIlis Premium).
-->
Premium 21.04 pasca bug fix

**Cara untuk mereplikasi errornya**

**Hasil yg diharapkan**

**Tampakan layar dan log error**

**Versi OpenSID**

**Tema Yg Digunakan**

**Informasi tambahan**

**Comment by agungsugiarto** [comment]
Pak @Zoel-WB Saya tidak mengalami issue ini di berputar maupun di lokal saya,

**Comment by Zoel-WB** [comment]
Input pertama memang tidak apa2, sukses pak, akan tetapi pada input data yg kedua pak, data gagal simpan.

Dapatkan Outlook untuk Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by agungsugiarto** [comment]
Apakah bug tersebut terjadi melaui keluarga ? Jika benar silahkan dirubah judul issuenya pak, karena untuk menambah penduduk dari menu penduduk sudah di fix #4106

**Comment by Zoel-WB** [comment]
Iya benar pak, input data dari fitur keluarga, baik data kelahiran baru maupun data penduduk masuk pak, pada input data pertama tidak ada masalah, aman aman saja,  akan tetapi pada saat menambah data kedua baru muncul gagal simpan, pesan log erornya seperti di lampiran issue, query key duplicate tag_id_card.

Dapatkan Outlook untuk Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by WAHYUDIK** [comment]
Tambahan sedikit bang @agungsugiarto untuk isian lainnya yang (dapat membaca huruf) listnya tidak tampil. 
![image](https://user-images.githubusercontent.com/31026980/114175959-c7a21680-9964-11eb-9f55-da260c4fed40.png)
kalo edit data bisa tampil.
ini terjadi hanya ketika tambah baru. tetapi untuk di tambah penduduk individu sudah tidak terjadi masalah seperti itu

**Comment by agungsugiarto** [comment]
@WAHYUDIK silahkan dibuatkan issue terpisah untuk ini pak

**Comment by eddieridwan** [comment]
Bung @agungsugiarto , untuk solusi issue ini, harap lakukan:
1. Masukkan baris berikut ke method `validasi_data_penduduk()` di file `donjo-app/models/Penduduk_model.php`
`		$data['tag_id_card'] = empty($data['tag_id_card']) ? null : $data['tag_id_card'];
2. Hapus baris tersebut lainnya yg ada di file `donjo-app/models/Penduduk_model.php`. Saat ini ada dua, satu di baris 750 dan satu lagi di baris 895.

Keluarga model juga memanggil `penduduk_model->validasi_data_penduduk()`, dan seharusnya baris di atas ada di method itu, bukan diduplikasi di dua tempat lain itu.

**Comment by agungsugiarto** [comment]
Baik pak

**Comment by eddieridwan** [comment]
Sdh dicommit ke `bug-fix` melalui https://github.com/OpenSID/premium/pull/184
