### ISSUE TITLE
[BUG] List pengisian lainnya di individu melalui keluarga tidak muncul

### ISSUE THREAD

**Issue by WAHYUDIK** [OpenSID/OpenSID#4130]
**Jelaskan error yg dialami**

ketika menambah penduduk melalui menu keluarga>penduduk masuk, list isiany di lainnya (dapat membaca huruf) tidak muncul
![image](https://user-images.githubusercontent.com/31026980/114181626-f1127080-996b-11eb-8b31-d3994b30093e.png)

**Cara untuk mereplikasi errornya**

**Hasil yg diharapkan**

sudah tidak terjadi lagi
**Tampakan layar dan log error**

![image](https://user-images.githubusercontent.com/31026980/114181626-f1127080-996b-11eb-8b31-d3994b30093e.png)

**Versi OpenSID**

**Tema Yg Digunakan**

**Informasi tambahan**

**Comment by eddieridwan** [comment]
Sdh dicommit ke `bug-fix` melalui https://github.com/OpenSID/premium/pull/185
