### ISSUE TITLE
[BUG] Terjadi Duplikat Data Penduduk Saat Dilakukan Penambahan dan Pengurangan Anggota Keluarga

### ISSUE THREAD

**Issue by mizwaruddin** [OpenSID/OpenSID#4131]
**Jelaskan error yg dialami**

Saat melakukan penambahan atau pengurangan data keluarga, maka terjadi duplikat pada data anggota keluarga tsb.

**Cara untuk mereplikasi errornya**

**Hasil yg diharapkan**

Tidak terjadi duplikat pada saat menambah/menghapus data anggota keluarga.

**Tampakan layar dan log error**

![Screenshot_2021-04-09-15-56-27-52.jpg](https://user-images.githubusercontent.com/39736008/114188586-7d746180-9973-11eb-8b59-6200d20eeb47.jpg)
![Screenshot_2021-04-09-15-55-42-32.jpg](https://user-images.githubusercontent.com/39736008/114188609-8402d900-9973-11eb-93ea-a2fe64404d0a.jpg)

**Versi OpenSID**

V21.04-Premium Pasca

**Tema Yg Digunakan**

**Informasi tambahan**

**Comment by agungsugiarto** [comment]
CC @af-lazuardi

**Comment by eddieridwan** [comment]
Dari @agungsugiarto : "kasus ketika penduduk dihapus dari menu keluarga, penduduk tersebut menjadi double di menu penduduk karena datanya masih ada di table log_penduduk apakah perlu dirubah relasi log_penduduk diambil dari relasi ke table tweb_keluarga ?"

@mizwaruddin Apakah yg dimaksud `menghapus anggota keluarga` di issue ini mengeluarkan anggota keluarga dari KK (pecah KK) atau menghapus penduduk tersebut melalui menu Penduduk?

Pertanyaan yg perlu dijawab: mengapa penduduk tersebut dihapus? Apakah salah isi? Atau apakah penduduknya pindah atau lainnya. Penghapusan data penduduk merupakan langkah terakhir kalau tidak ada pilihan lain. 

Saya tidak bisa replikasi masalah ini. Data NIK penduduk yg dihapus direkam di tabel `log_hapus_penduduk` dan data yg ada di `log_penduduk` tidak dihapus. Tetapi di saya penduduk yg telah dihapus tidak lagi muncul di daftar penduduk dan tidak bisa dicari. 

Apakah masalah ini terjadi di https://berputar.opensid.or.id? Harap beri langkah rinci proses sampai terjadinya error ini.

**Comment by agungsugiarto** [comment]
Masalah ini terjadi di berputar dan lokal saya,

Ketika hapus/keluar dari daftar keluarga pak eddie
![hapus](https://user-images.githubusercontent.com/10989147/114258340-23fe4800-99f0-11eb-8e0e-bc28430ac50d.png)

Menjadi duplikat
![image](https://user-images.githubusercontent.com/10989147/114258333-1a74e000-99f0-11eb-85e3-d0e8ac302374.png)

**Comment by mizwaruddin** [comment]
Yg saya alami tdk menghapus, tp menambah anggota keluarga.
Kasus menghapus anggota dialami olh desa lain. Saya hanya merangkum kasus2 yg ada.

**Comment by agungsugiarto** [comment]
Iya terjadi di berbagi tempat karena querynya menyangkut `log_penduduk` setalah ada fitur buku adminitrasi desa

**Comment by mizwaruddin** [comment]
Saya cek di berputar utk penambahan anggota tidak terjadi masalah. Yang saya bingungkan mengapa bisa terjadi perbedaan antara di berputat dg di desa saya. Pdhl update rutin dilakukan olh Bang Rudi.

**Comment by eddieridwan** [comment]
@agungsugiarto ok, sekarang sudah jelas errornya. Bung @mizwaruddin mohon setiap issue diperjelas langkah yg dilakukan sampai terjadinya error. Kalau tidak dijelaskan rinci, habis waktu programmer untuk mencoba menebak di mana letak masalahnya.

Bung @agungsugiarto , masalah ini terjadi karena method `keluarkan_anggota()` di `donjo-app/controllers/Keluarga.php` menulis ke `log_penduduk` dengan `kode_peristiwa` = 7, yg sejak perubahan buku mutasi penduduk, tidak dikenal lagi (lihat tabel `ref_peristiwa`. 

Jadi yg perlu ditinjau ulang adalah tujuan mengapa menulis ke `log_penduduk`. Log Penduduk sekarang fungsinya sudah berubah, dan hanya fokus pada perubahan status penduduk. Sedangkan mengeluarkan seorang penduduk dari keluarga (jadi **BUKAN** menghapus penduduk seperti dilaporkan di issue ini) tidak mengubah status penduduk. Penduduk yg dikeluarkan dari keluarga masih tetap ada, tetapi menjadi penduduk lepas (yaitu bukan lagi anggota KK manapun).

Jadi dalam hal ini, sepertinya tidak lagi tepat untuk mencatat peristiwa `keluar dari keluarga` di `log_penduduk`. Mungkin lebih tepat untuk dicatat di `log_keluarga`. Supaya tercatat bahwa si A dulu anggota keluarga X -- dan pada tgl Y si A dikeluarkan dari keluarga X tersebut oleh operator Z. 

@agungsugiarto , silakan anda pelajari dan usulkan solusinya. Dalam penerapnnya juga diperlukan migrasi supaya memindahkan semua entri di `log_penduduk` dengan `kode_peristiwa` = 7 ke format yg baru (misalnya di `log_keluarga`).

**Comment by mizwaruddin** [comment]
Siap, Bang.

**Comment by eddieridwan** [comment]
Pencatatan di `log_keluarga` saat ini mencakup:

1. tambah keluarga baru, dengan `id_peristiwa` = 1
2. hapus keluarga, dengan `id_peristiwa` = 2
3. update status dasar kepala keluarga, dengan `id_peristiwa` = 3,4,5,6,8,11 (= `status_dasar` kk + 2)

Jadi untuk pencatatan peristiwa `keluar` dari KK, kita bisa gunakan `id_peristiwa` = 12.

Juga perlu ditambah kolom berikut di tabel `log_keluarga`:
1. `updated_by` utk mencatat siapa ya melakukan
2. `id_pend` untuk mencatat siapa yg dikeluarkan

**Comment by eddieridwan** [comment]
Di migrasi, selain menambah kolom `log_keluarga`, juga pindahkan `log_penduduk` dengan `kode_peristiwa` = 7 ke `log_keluarga` dan hapus dari `log_penduduk`.

**Comment by eddieridwan** [comment]
Sdh dicommit ke `bug-fix`.
