### ISSUE TITLE
[BUG] Peta Tidak Dapat Menampilkan Peta Area yang Jumlahnya Melebihi 1.716 Area

### ISSUE THREAD

**Issue by mizwaruddin** [OpenSID/OpenSID#4133]
**Jelaskan error yg dialami**

Saya membuat peta area dengan jumlah 1.850 area. Namun di peta yang dapat ditampilkan hanya 1.716 area.

**Cara untuk mereplikasi errornya**

**Hasil yg diharapkan**

Peta dapat menampilkan  2.000 area atau lebih untuk mengantisipasi desa yang wilayahnya sangan luas.

**Tampakan layar dan log error**

![bug_peta](https://user-images.githubusercontent.com/39736008/114214372-6e4edd00-998e-11eb-8a5b-e1c0aa24513a.png)
![bug_peta2](https://user-images.githubusercontent.com/39736008/114214707-def5f980-998e-11eb-8676-f7ed0b460b3c.png)

**Versi OpenSID**

OpenSID v21.04 pasca- Premium

**Tema Yg Digunakan**

**Informasi tambahan**

**Comment by agungsugiarto** [comment]
Pak @mizwaruddin bisa kirim database bapak ke telegram saya ?

**Comment by eddieridwan** [comment]
Sdh dicommit ke `bug-fix` melalui https://github.com/OpenSID/premium/pull/186
