### ISSUE TITLE
[BUG] Penduduk Dengan Status Dasar Mati dan Pindah Tercatat Ganda

### ISSUE THREAD

**Issue by mizwaruddin** [OpenSID/OpenSID#4136]
**Jelaskan error yg dialami**

Penduduk dengan status dasar mati dan pindah tercatat ganda di data penduduk

**Cara untuk mereplikasi errornya**

1. Menu Kependudukan > Penduduk
2. Tampil Data Penduduk
3. Melakukan filter pada "Status Dasar" dengan memilih mati dan pindah
4. Penduduk dengan status tersebut tampil ganda.

**Hasil yg diharapkan**

Penduduk dengan status dasar mati dan pindah tidak tercatat ganda.

**Tampakan layar dan log error**

![bug_mati](https://user-images.githubusercontent.com/39736008/114490415-04a92a00-9c3f-11eb-8520-438f7f436f02.png)

**Versi OpenSID**

berputar.opensid.go.id per tgl 13/4/2021

**Tema Yg Digunakan**

**Informasi tambahan**

**Comment by eddieridwan** [comment]
@agungsugiarto , sebagai info, masalah ini muncul karena di tabel `log_penduduk` bisa ada lebih dari satu entri untuk suatu penduduk. Misalnya untuk penduduk yang pindah akan ada minimal dua entri:
1. untuk pertama kali penduduk ditambah
2. untuk peristiwa pindah

Untuk penduduk lepas yg pergi/balik lagi akan ada lebih banyak entri lagi. 

Karena itu, tidak bisa join biasa lagi. Yaitu join seperti berikut akan menghasilkan duplikat sebanyak entri di `log_penduduk` untuk penduduk ybs:
`			->join('log_penduduk log', 'log.id_pend = u.id');`

**Comment by agungsugiarto** [comment]
Baik pak @eddieridwan
