### ISSUE TITLE
Sediakan pilihan Tahun pada Status Idm Desa

### ISSUE THREAD

**Issue by ai-skematik** [OpenSID/OpenSID#4137]
**Apa kekurangan yg ingin diatasi?**

Saat ini di OpenSID belum tersedia pilihan untuk melihat status IDM Desa pada tahun sebelumnya

**Jelaskan solusi yg diinginkan**

disediakan pilihan tahun status IDM Desa

**Apakah ada alternatif lain**

**Untuk versi OpenSID mana**

Rilis Premium 21.05

**Informasi tambahan**

![idm](https://user-images.githubusercontent.com/48144047/114507078-37feaf80-9c65-11eb-804b-fecbc0b58ccd.png)

**Comment by cepiandiana** [comment]
Mantap.. mungkin ini perlu untuk melihat grafik status idm desa

**Comment by eddieridwan** [comment]
Sdh dicommit ke `rilis-dev` melalui https://github.com/OpenSID/premium/pull/207
