### ISSUE TITLE
[BUG] Data Suplemen yang Ditampilkan di Website Hanya 20

### ISSUE THREAD

**Issue by mizwaruddin** [OpenSID/OpenSID#4140]
**Jelaskan error yg dialami**

Saat ini data suplemen yang ditampilkan di website hanya 20 nomor/data, padahal data aslinya lebih dari itu.

**Cara untuk mereplikasi errornya**

**Hasil yg diharapkan**

Data suplemen yang ditampilkan di website bisa mencakup semua data.

**Tampakan layar dan log error**

![IMG_20210414_004726_371.png](https://user-images.githubusercontent.com/39736008/114597964-90609c00-9cbb-11eb-9882-756ecfe9e7f1.png)

**Versi OpenSID**

v21.04 pasca-premium

**Tema Yg Digunakan**

Klasik, natra, denatra

**Informasi tambahan**

![IMG_20210414_005327_406.png](https://user-images.githubusercontent.com/39736008/114598227-dcabdc00-9cbb-11eb-958f-454d58ac4469.png)

**Comment by eddieridwan** [comment]
Sdh dicommit ke `bug-fix`

**Comment by eddieridwan** [comment]
@agungsugiarto sebagai info, masalah ini terjadi karena paginasi suplemen di admin dan di web berbeda. Paginasi di admin diatur melalui method di `donjo-app/models/Suplemen_model.php` . Di web, paginasi diatur menggunakan datatables murni, tetapi tetap mengambil data menggunakan method yg sama di `donjo-app/models/Suplemen_model.php`. 

Solusi sementara yg telah diterapkan di commit https://github.com/OpenSID/premium/commit/aa7fb738ad7c4ca6e6dfdcda049966dd481e58d5 adalah dengan mengosongkan `$this->session->per_page = null;` jika memanggil dari web, supaya semua data diambil sekaligus.

Ke depan, sebaiknya pengambilan data suplemen di web juga mengandalkan paginasi di server, tidak paginasi datatables di browser. Karena cara yg sekarang akan terkendala kalau data suplemen yg diambil berjumlah besar.
