### ISSUE TITLE
[BUG] Tidak Bisa Menambah KK dari Penduduk Yang Sudah Ada 

### ISSUE THREAD

**Issue by mizwaruddin** [OpenSID/OpenSID#4141]
**Jelaskan error yg dialami**

Saat melakukan penambahan KK dari penduduk yang sudah ada (dari hasil pecah KK) muncul keterangan tersimpan, namun nyatanya tidak tersimpan.

**Cara untuk mereplikasi errornya**

1. Melakukan pemecahan anggota keluarga dari dua KK
2. Melakukan penambahan KK Baru dari Penduduk yang sudah Ada
3. Muncul keterangan/pop-up data tersimpan
4. Dilihat di Data Keluarga hasil penambahan KK tersebut tidak muncul.

**Hasil yg diharapkan**

Tambah KK dari penduduk yang sudah ada berjalan lancar.

**Tampakan layar dan log error**

[log-2021-04-14.zip](https://github.com/OpenSID/OpenSID/files/6307987/log-2021-04-14.zip)

**Versi OpenSID**

**Tema Yg Digunakan**

**Informasi tambahan**

Setelah ditambahkan KK dari penduduk yang sudah ada, meski gagal tersimpan di data keluarga namun SDHK sudah berubah sesuai dengan yag diisikan saat menambah KK.

**Comment by mizwaruddin** [comment]
Tambahan info: Menambah KK langsung dari "Penduduk Masuk" juga tidak berhasil dilakukan.

**Comment by eddieridwan** [comment]
Sdh dicommit ke 'rilis-dev'.

**Comment by eddieridwan** [comment]
@agungsugiarto sebagai info:

Ada beberapa masalah:
1. Penggunaan assignment `=&` yg keliru. Sebenarnya ini assignment by reference. Sehingga penggunaan dalam bentuk `$outp =& ` selama ini merekam error salah, karena bukan berarti `$outp = $outp &&`. Sekarang semua penggunaan `=&` telah disesuaikan. Jadi untuk migrasi gunakan `$hasil = $hasil &&` dan tidak `$hasil =&` (salah).
2. Kolom `updated_by` telah ditambah ke tabel `tweb_keluarga`, tetapi script belum disesuaikan untuk mengisi kolom ini pada waktu update and insert. Sekarang sudah diperbaiki.
