### ISSUE TITLE
[BUG] Ukuran Nama Kabupaten di KOP SURAT Dikecilkan

### ISSUE THREAD

**Issue by lastingdone** [OpenSID/OpenSID#4142]
**Jelaskan error yg dialami**

Penyesuaian Ukuran Nama Kabupaten di KOP SURAT Dikecilkan supaya default di ukuran 16 karena kalau nama kabupaten yang panjang harus menyesuaikan
![UKURAN](https://user-images.githubusercontent.com/56072113/114653401-2cb58d80-9d12-11eb-849d-3a9757057bfd.png)

**Cara untuk mereplikasi errornya**

**Hasil yg diharapkan**

![UKURAN](https://user-images.githubusercontent.com/56072113/114653473-57074b00-9d12-11eb-90fe-1dbfd3662034.png)

**Tampakan layar dan log error**

**Versi OpenSID**

**Tema Yg Digunakan**

**Informasi tambahan**

**Comment by agungsugiarto** [comment]
Pak @lastingdone apakah terjadi di semua kop surat ?

**Comment by agungsugiarto** [comment]
Pak @lastingdone, untuk perbaikan ukuran font di kop surat harap untuk menyesuaikan sendiri di masing-masing surat pada template rtf. Pastikan ubahan disimpan di folder desa/template-surat. Apabila kesulitan untuk menyesuaikan silakan hubungi Bapak @HerryWanda bila berminat menggunakan layanan OpenDESA.
