### ISSUE TITLE
[BUG] Nomor Halaman Pada Peta Area Tidak Rapi

### ISSUE THREAD

**Issue by mizwaruddin** [OpenSID/OpenSID#4143]
**Jelaskan error yg dialami**

Setelah dilakukan perbaikan terhadap jumlah area yang ditampilkan, sekarang tampilan nomor halaman menjadi tidak rapi.

**Cara untuk mereplikasi errornya**

1. Masuk Pemetaan > Pengaturan Peta > Area
2. Terlihat nomor halaman tidak rapi.

**Hasil yg diharapkan**

Nomor halaman kembali rapi seperti sebelum dilakukan perbaikan.

**Tampakan layar dan log error**

**Versi OpenSID**

![bug-peta](https://user-images.githubusercontent.com/39736008/114654691-e6156280-9d14-11eb-97c1-3cb0b0547497.png)

**Tema Yg Digunakan**

**Informasi tambahan**

**Comment by eddieridwan** [comment]
@mizwaruddin masalah ini bukan karena perubahan jumlah area, tetapi karena jumlah link halaman (15 di contoh anda) yang melebihi lebar halaman yg tersedia. Hal ini terjadi di semua halaman dengan dengan data yg banyak, misalnya halaman penduduk. Bedanya di daftar area, ada sub-menu di sebelah kiri yg menyita sebagian lebar halaman, sehingga kapling untuk link halaman terbatas. 

Satu solusi adalah mengurangi jumlah link halaman. Solusi yg akan dibuat adalah mengurangi jumlah link halaman menjadi maksimum 10.

**Comment by eddieridwan** [comment]
Sdh dicommit ke `bug-fix`

**Comment by eddieridwan** [comment]
@agungsugiarto @afa28 sebagai info:

Solusi yg diterapkan mengubah `donjo-app/libraries/Paging.php` supaya bisa mengubah jumlah link halaman. Aslinya selalu 20. Sekarang pada waktu memanggil `$this->paging->init($cfg)` bisa tentukan jumlah link halaman. Di method `donjo-app/core/MY_Model.php->paginasi()` sekarang defaultnya 10. 

Ke depan, `donjo-app/libraries/Paging.php` bisa diubah untuk membuat penelusuran halaman jumlah banyak lebih mudah, misalnya dengan menambah link ke halaman lompatan, tidak saja berurutan.
