### ISSUE TITLE
penambahan anggota keluarga yang baru lahir dan masuk di anggota keluarga tidak bisa tersimpan [BUG] 

### ISSUE THREAD

**Issue by anamrifai** [OpenSID/OpenSID#4144]
**Jelaskan error yg dialami**

**Cara untuk mereplikasi errornya**

**Hasil yg diharapkan**

**Tampakan layar dan log error**

**Versi OpenSID**

**Tema Yg Digunakan**

**Informasi tambahan**

**Comment by eddieridwan** [comment]
Apakah sdh mencoba di https://berputar.opensid.or.id. Saya coba tidak bermasalah. Silakan update ke rilis terbaru.

**Comment by eddieridwan** [comment]
@anamrifai , juga harap isi semua bagian di template issue. Tujuannya untuk memudahkan programmer yg berusaha menanggapi. Dengan adanya informasi yg lengkap sesuai template akan membantu programmer supaya dapat membantu pengguna.

**Comment by eddieridwan** [comment]
@anamrifai karena belum ada informasi susulan, laporan ini akan ditutup. Silakan buka lagi kalau ada informasi tambahan.
