### ISSUE TITLE
menampilkan daftar pembangunan pada web

### ISSUE THREAD

**Issue by anamrifai** [OpenSID/OpenSID#4145]
**Apa kekurangan yg ingin diatasi?**

**Jelaskan solusi yg diinginkan**

**Apakah ada alternatif lain**

**Untuk versi OpenSID mana**

**Informasi tambahan**

**Comment by HerryWanda** [comment]
Lebih dijelaskan lagi terkait issu nya..

data pembangunan yg bagaiamana, atau di ambil dari info pembangunan yg sudah ada di opensid..

**Comment by afa28** [comment]
Mohon issue ini diperjelas, silahkan dibuka kembali jika masih diperlukan.
