### ISSUE TITLE
[Penduduk] Blacklist Penduduk Bermasalah

### ISSUE THREAD

**Issue by ananghasan** [OpenSID/OpenSID#4146]
**Apa kekurangan yg ingin diatasi?**

**Jelaskan solusi yg diinginkan**

**Apakah ada alternatif lain**

**Untuk versi OpenSID mana**

**Informasi tambahan**

**Comment by eddieridwan** [comment]
@ananghasan Harap isi template issue sesuai judul yg sudah disediakan. Tanpa informasi rinci, permintaan ini tidak bisa ditindak-lanjuti. 

Jelaskan alasan mengapa diperlukan, beserta contoh. Misalnya apakah ini dimaksudkan untuk pengguna layanan mandiri atau untuk interaksi lain juga? Apakah cukup dengan menyediakan tombol untuk menon-aktifkan pengguna di Layanan Mandiri > Pendaftar Layanan Mandiri? Atau yg dibayangkan lain dari itu?

**Comment by ananghasan** [comment]
1.beberapa anak muda yang melanggar aturan desa, setelah dipanggil mereka diberikan sanksi tapi sanksi tersebut diabaikan oleh mereka dan orang tuanya, dan menurut adat yg disepakati adalah saat mereka menikah tdk akan dihadiri oleh orang tua desa/ kepala desa, bpd dan perangkat

2. Kasus utang piutang, yg berhutang melarikan diri dan yg memberikan utang melapor kepada desa agar ditahan saat mereka mengurus surat pindah

Dalam perjalanannya kasus ini ditakutkan pemangku kepentingan dan operator yg menerbitkan surat lupa krn bisa jadi waktunya lama

Dg adanya fasilitas tersebut siapapun yg jadi kepala desa atau yg membuat surat tau histori warga yg bermasalah tersebut.

Mohon maaf klu kurang teratur pak
Salam

**Comment by mizwaruddin** [comment]
Catatan seperti ini bisa dimasukkan di kolom keterangan pada data penduduk ybs. 
Di fitur premium kolom keterangan penduduk sudah tersedia.

**Comment by eddieridwan** [comment]
@ananghasan apakah sudah menjajaki penggunaan Data Suplemen untuk pencatatan penduduk bermasalah? Fitur itu sangat fleksibel dan digunakan oleh desa untuk berbagai pencatatan daftar penduduk/keluarga khusus. Bisa lihat contoh penggunaan di https://berputar.opensid.or.id/suplemen.

**Comment by andifahruddinakas** [comment]
Bisa gunakan data suplemen.
