### ISSUE TITLE
penambahan url untuk pembangunan dan lapak 

### ISSUE THREAD

**Issue by Fajar-blackdeath** [OpenSID/OpenSID#4147]
**Apa kekurangan yg ingin diatasi?**

**Jelaskan solusi yg diinginkan**

**Apakah ada alternatif lain**

**Untuk versi OpenSID mana**

**Informasi tambahan**

**Comment by eddieridwan** [comment]
@Fajar-blackdeath permintaan ini tidak bisa ditindak-lanjuti, karena:
1. berisi lebih dari satu permintaan. Harap batasi satu permintaan per issue. Pastikan belum ada issue lain yg meminta fitur yang sama, supaya tidak duplikat.
2. tidak ada keterangan sama sekali apa yg diperlukan. Harap mengisi template issue sesuai judul yg telah disediakan.

**Comment by afa28** [comment]
Modul lapak sudah akan segera dirilis agar desa tdk repot lg mengubah secara manual lapak mereka.

Untuk permintaan pada modul pembangunan silahkan dibuat issue lebih detail, apa yang perlu ditambah / diubah dari modul yang ada sekarang jika merasa modul tsb masih perlu perbaikan.
