### ISSUE TITLE
[BUG] Pencarian Nama yang Mengandung Tanda Baca Petik Satu ( ' ) di Arsip Layanan Tidak Dapat Ditampilkan

### ISSUE THREAD

**Issue by mizwaruddin** [OpenSID/OpenSID#4148]
**Jelaskan error yg dialami**

Ketika mencari arsip surat berdasarkan nama yang menggunakan tanda baca petik satu ( ' ) data tidak dapat ditampilkan.

**Cara untuk mereplikasi errornya**

1. Masuk ke Menus Layanan Surat > Arsip Layanan
2. Mengetikkan nama yang mengandung tanda baca petik satu ( ' ) data tidak ditampilkan.
3. Mencoba menghapus kata-dalam nama- yang mengandung tanda baca petik satu tersebut, data tampil.

**Hasil yg diharapkan**

Pencarian dengan nama yang mengandung tanda baca petik satu dapat ditampilkan.

**Tampakan layar dan log error**

![BUG_ARSIP1](https://user-images.githubusercontent.com/39736008/114887739-e86dde80-9e32-11eb-8ea2-8b9442f0f50a.png)

![BUG_ARSIP2](https://user-images.githubusercontent.com/39736008/114887791-f1f74680-9e32-11eb-9b38-1c9b6dc49e6c.png)

**Versi OpenSID**

**Tema Yg Digunakan**

**Informasi tambahan**

**Comment by eddieridwan** [comment]
@mizwaruddin terima kasih atas laporan yg jelas dan rinci, sehingga memudahkan programmer.

Sdh dicommit ke `bug-fix`

**Comment by eddieridwan** [comment]
@agungsugiarto @afa28 sebagai info:

Ini karena escape ganda yg terlewat dihapus sebelumnya. Dan timbul karena setelah mengubah native SQL menggunakan CI query builder, tidak perlu lagi menggunakan `$cari = $this->db->escape_like_str($cari);` karena `$this->db->like('u.nama', $cari)` sudah otomatis melakukan escape. Saya sdh periksa semua penggunaan serupa dan perbaiki. Mudah2an tidak ada yg terlewat.
