### ISSUE TITLE
PENGISIAN DATA ORANG TUA NIK DAN NAMA PADA DATA PENDUDUK DI BUAT OTOMATIS DARI DATA PENDUDUDK YANG ADA

### ISSUE THREAD

**Issue by anamrifai** [OpenSID/OpenSID#4149]
**Apa kekurangan yg ingin diatasi?**
 agar setiap inpun data nik dan nama orang tua tidak perlu lagi ketik ulang karena data sudah ada pada data base penduduk

**Jelaskan solusi yg diinginkan**
 karena disetiap data pada kartu keluarga diwajibkan mengisi nama orang tua

**Apakah ada alternatif lain**

**Untuk versi OpenSID mana**

**Informasi tambahan**

**Comment by balongbesuk** [comment]
Duplicate #734

**Comment by agungsugiarto** [comment]
@anamrifai terima kasih sudah melaporkan permintaan fitur. Issue ini saya close seperti yg dibilang Pak @balongbesuk karena duplikat dengan #734. Mohon lengkapi di issue terkait jika ada yg kurang. Terima kasih
