### ISSUE TITLE
Input Data Penduduk dapat menyimpan data penduduk dengan NIK yang sama lebih dari satu data penduduk (NIK Ganda) [BUG] 

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#4150]
**Jelaskan error yg dialami**

OpenSID v21.04 Premium-bug-fix-2

**Cara untuk mereplikasi errornya**

**Hasil yg diharapkan**

**Tampakan layar dan log error**

**Versi OpenSID**

**Tema Yg Digunakan**

**Informasi tambahan**

**Comment by eddieridwan** [comment]
@Zoel-WB kami tidak bisa replikasi masalah ini. Harap menggunakan versi terbaru. Coba replikasi di https://berputar.opensid.or.id. 

Harap selalu mengisi template issue sesuai judul yg telah disediakan. Lihat contoh pengisian issue di https://github.com/OpenSID/OpenSID/issues/4148. 

Pengisian template yg lengkap dan rinci akan sangat membantu programmer, dan akhirnya akan membantu pengguna sendiri.

**Comment by eddieridwan** [comment]
Sdh dicommit ke `bug-fix`

**Comment by eddieridwan** [comment]
@agungsugiarto @afa28 sebagai info:

Masalah ini muncul karena perubahan yg dilakukan pada pembuatan Buku Administrasi Penduduk, yg lolos review dan testing. Gejalanya adalah blok if-else yg keliru. Tapi sumber masalahnya adalah cara penanganan form dan validasi penduduk yg tidak standar dan sangat rumit. Ke depan, sebaiknya di-refactor mengikuti standar CI dan disederhanakan.
