### ISSUE TITLE
[BUG] Penduduk Mati/Pindah Masih Muncul di List Tambah Anggota Keluarga Dari Penduduk Yang Sudah Ada

### ISSUE THREAD

**Issue by WAHYUDIK** [OpenSID/OpenSID#4152]
**Jelaskan error yg dialami**

Ketika mau menambah anggota keluarga dari penduduk yang sudah ada, untuk penduduk yang sudah pindah/mati dengan status perkawinan masih belum menikah, muncul dilist.

**Cara untuk mereplikasi errornya**

Alur:
1. Keluarga > Tambah dari Penduduk yg sdh ada
2. Lihat di list penduduk yg sdh ada (apakah penduduk berstatus mati/pindah masih ada di list tsb)

**Hasil yg diharapkan**
 seharunya penduduk yang sudah pindah/mati tidak terlist lagi, meskipun status perkawinannya belum menikah

**Tampakan layar dan log error**

![image](https://user-images.githubusercontent.com/31026980/115117048-e89ee300-9fc6-11eb-8b29-3e59e51db71d.png)

**Versi OpenSID**

**Tema Yg Digunakan**

**Informasi tambahan**

**Comment by Zoel-WB** [comment]
Hasil tester ulang terhadap issue ini :
1. Tester pada system saya teupinbeulangan.desa.id opensid v21.04 premium-pasca-bug-fix-2, aman tak ada bug pada fitur Daftar Anggota Keluaga ---> Tambah Anggota--> Dari Penduduk sudah ada.
![image](https://user-images.githubusercontent.com/64481641/115118464-6bc33780-9fcd-11eb-98a4-6b4bcd91b2f7.png)

2. Tester pada https://berputar.opensid.or.id/keluarga/anggota/1/0/1888, dengan Menguji tester salah satu penduduk atas nama Zoel WB dengan cara merubah status dasar "Pindah keluar Provinsi, kemudian membuka kembali fitur "Daftar Anggota Keluarga" --> Tambah Anggota ---> Dari Penduduk yang sudah ada, mencoba penduduk yg sudah merubah status dasar tadi atas nama Zoel WB, penduduk tersebut masih muncul dalam list penduduk yang belum punya KK atau belum menjadi salah satu anggota KK tertentu, screensotenya seperti berikuti ini : 
 
![image](https://user-images.githubusercontent.com/64481641/115118713-c4df9b00-9fce-11eb-8500-2d0855ac0eb9.png)

![image](https://user-images.githubusercontent.com/64481641/115118720-cdd06c80-9fce-11eb-863e-b28590e3bd3b.png)

**Comment by eddieridwan** [comment]
Sdh dicommit ke `bug-fix`.

**Comment by eddieridwan** [comment]
@agungsugiarto @afa28 sebagai info:

Masalah ini muncul di `keluarga_model->list_penduduk_lepas()` karena keliru menggunakan syarat query `status = 1`. Seharusnya `status_dasar = 1`. Kekeliruan ini mudah terjadi karena nama variable yg serupa. Idealnya nama variabel `status` diganti menjadi `status_kawin`. Tapi sulit kita lakukan sekarang, karena akan merambat kemana-mana.

Solusi yg diterapkan di https://github.com/OpenSID/premium/commit/af86599de7f948029441976570fae84e48b0df55 adalah dengan menggunakan view `penduduk_hidup` yg memang sengaja dibuat untuk menghindari seringnya diperlukan penambahan syarat `status_dasar = 1` yg mudah terlupa atau keliru.
