### ISSUE TITLE
[BUG] Nomor Urut Pertanyaan di Hasil Unduh Input Analisis Masih Belum Urut

### ISSUE THREAD

**Issue by mizwaruddin** [OpenSID/OpenSID#4154]
**Jelaskan error yg dialami**

Saat mencoba mengisi/menginput analisis SDGs melalui excel dari format yang disediakan dari hasil unduh, nomor urut pertanyaan masih belum urut. Di file tersebut nomor urut pertanyaan tertutil 1, 10, 11 ... 19, 2, 20, 21 ... dst

**Cara untuk mereplikasi errornya**

1. Analisis > SDGs Individu > Input Data Sensus/Survey
2. Klik tombol Unduh > Form Excel + Isi Data
3. Buka hasil unduhan
4. Nomor urut pertanyaan masih belum urut.

**Hasil yg diharapkan**

Nomor urut pertanyaan bisa urut sehingga mempermudah pengisian data.

**Tampakan layar dan log error**

![bug_unduh_analisis](https://user-images.githubusercontent.com/39736008/115431628-b80db200-a22f-11eb-90fc-5a8e03b12771.png)

**Versi OpenSID**

Premium (v21.04 pasca/bug fix 2)

**Tema Yg Digunakan**

**Informasi tambahan**

**Comment by eddieridwan** [comment]
@mizwaruddin yg belum urut persisnya yg mana? 
Harap lampirkan file analisis SDGs yg anda gunakan.

**Comment by mizwaruddin** [comment]
[statistik_analisis_jawaban_20_04_2021.xls](https://github.com/OpenSID/OpenSID/files/6352516/statistik_analisis_jawaban_20_04_2021.xls)

Pada baris ke-3 mulai kolom ke-9 dst nomor tidak urut.

**Comment by eddieridwan** [comment]
Sdh dicommit ke `bug-fix` melalui https://github.com/OpenSID/premium/pull/190
