### ISSUE TITLE
Layanan mandiri[BUG] 

### ISSUE THREAD

**Issue by afri18** [OpenSID/OpenSID#4155]
**Jelaskan error yg dialami**
Saat mau menambahkan peserta layanan mandiri keterangan tersimpan tapi saat di periksa tidak ada
Apakah sekarang layanan mandiri hanya bisa dinikmati pengguna premium ???
Kalau jawabnya iya mohon abaikan issue ini

**Cara untuk mereplikasi errornya**

**Hasil yg diharapkan**

**Tampakan layar dan log error**

**Versi OpenSID**

**Tema Yg Digunakan**

**Informasi tambahan**

**Comment by ai-skematik** [comment]
apakah sudah di coba di web demo sebelum membuat issue?

**Comment by eddieridwan** [comment]
Di https://demo.opensid.or.id/mandiri normal. Lihat isi log.
