### ISSUE TITLE
Menu Administrasi Penduduk pada Fitur Buku Administrasi Desa tidak tampil pada login user atau login Operator [BUG] 

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#4156]
**Jelaskan error yg dialami**

**Cara untuk mereplikasi errornya**

**Hasil yg diharapkan**

**Tampakan layar dan log error**

**Versi OpenSID**

**Tema Yg Digunakan**

**Informasi tambahan**

**Comment by ariandii** [comment]
saat ini, sudah bisa nampaknya.

**Comment by eddieridwan** [comment]
Bisa ditutup issue ini?

**Comment by Zoel-WB** [comment]
Sudah tampil Pak @eddieridwan, akan tetapi saya sudah meng-update system ke versi  Beta, disini tampil Pak...

**Comment by eddieridwan** [comment]
Ok, issue ini ditutup. Silakan buka lagi kalau masih ada masalah.
