### ISSUE TITLE
Tidak Bisa Paging ke halaman dua ketika dalam menu kategori berita Thema Denatra Premium

### ISSUE THREAD

**Issue by adiskom** [OpenSID/OpenSID#4157]
### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by afa28** [comment]
Selain tema bawaan OpenSID, silahkan di laporkan ke pengembang tema premium tsb.
