### ISSUE TITLE
Penambahan Status Kesertaan JKN

### ISSUE THREAD

**Issue by fathullation** [OpenSID/OpenSID#4158]
**Apa kekurangan yg ingin diatasi?**
Status Kesertaan JKN dibutuhkan untuk setiap masyarakat untuk melihat jumlah masyarakat yang memiliki kesertaan dalam JKN.

**Jelaskan solusi yg diinginkan**
Dalam biodata penduduk, tambahkan "Status Kesertaan JKN" dengan pilihan sebagai berikut:
1. BPJS PBI
2. BPJS NON PBI
3. Swasta
4. Tidak Memiliki

**Comment by eddieridwan** [comment]
@fathullation sepertinya data ini sudah dikumpulkan. Lihat di biodata penduduk, untuk kolom isian `Asuransi`. Statistiknya ditampilkan di menu Statistik > Statistik Kependudukan > Jenis Asuransi.

Kalau itu yg dimaksud silakan tutup issue ini.
