### ISSUE TITLE
Hide tombol delete pada level selain admin di menu analisis

### ISSUE THREAD

**Issue by muhtar-coder** [OpenSID/OpenSID#4159]
**Apa kekurangan yg ingin diatasi?**

Fitur analisis di laksanakan oleh banyak orang/user.ketidaktahuan atau ketidaksengajaan menekan tombol hapus merupakan musibah besar bagi program kerja.

**Jelaskan solusi yg diinginkan**

Hide tombol hapus pada level selain admin
![Screenshot_20210425-130632](https://user-images.githubusercontent.com/55665526/115987821-e3eab800-a5e0-11eb-8035-1b9a761c3df8.png)

**Apakah ada alternatif lain**
menjaga data aman dari kehilangan atau terhapus secara tidak sengaja/tidak tahu

**Untuk versi OpenSID mana**
premium v21.05

**Informasi tambahan**

**Comment by afa28** [comment]
Duplicate issue https://github.com/OpenSID/OpenSID/issues/4219
