### ISSUE TITLE
Fasilitas upload video

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#416]
Mohon dibuatkan fasilitas upload video di widget shgg semua video bisa tersimpan di SID

**Comment by MUHAMMADRANGSEL** [comment]
Atau Seperti widget sinergitas juga bisa

**Comment by hadyanwijaya** [comment]
tidak rekomendasi untuk upload video ke server karena akan menghabiskan resource server. saran saya anda bisa upload VIDEO ke youtube.com nanti di embed ke openSid

**Comment by MUHAMMADRANGSEL** [comment]
Ok siap

Pada tanggal 19 Sep 2017 20:36, "Hadi Wijaya" <notifications@github.com>
menulis:
