### ISSUE TITLE
Gagal Akses halaman Inventaris pada Level Operator [BUG] 

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#4160]
**Jelaskan error yg dialami**

**Cara untuk mereplikasi errornya**

**Hasil yg diharapkan**

Level Operator bisa akses halaman inventaris.

**Tampakan layar dan log error**

<img width="960" alt="2021-04-27_01h02_14" src="https://user-images.githubusercontent.com/46939846/116129635-89428080-a6f4-11eb-9a9c-326e4715e092.png">

<img width="960" alt="2021-04-27_01h02_33" src="https://user-images.githubusercontent.com/46939846/116129666-92335200-a6f4-11eb-9949-52c2f43a65e2.png">

**Versi OpenSID**

**Tema Yg Digunakan**

**Informasi tambahan**

**Comment by eddieridwan** [comment]
Sdh dicommit ke `rilis-dev`
