### ISSUE TITLE
[BUG] Pengaturan Grup Pengguna Masih Belum Sepenuhnya Berfungsi, Sehingga Grup Pengguna Baru Masih Bisa Baca/Ubah/Delet

### ISSUE THREAD

**Issue by WAHYUDIK** [OpenSID/OpenSID#4162]
**Jelaskan error yg dialami**

Mencoba membuat grup pengguna, dengan setingan hanya bisa membaca menu Kependudukan saja, untuk ubah/delet dinonaktifkan, ternyata setelah diujicoba akun tersebut masih bisa ubat/edit.
![image](https://user-images.githubusercontent.com/31026980/116497171-ec890a00-a8d0-11eb-9860-06b4406e2d61.png)
![image](https://user-images.githubusercontent.com/31026980/116497304-3671f000-a8d1-11eb-913c-8291ec5be59e.png)
![image](https://user-images.githubusercontent.com/31026980/116497328-425db200-a8d1-11eb-97ab-4a5800b77412.png)

**Cara untuk mereplikasi errornya**

**Hasil yg diharapkan**

seharusnya pengaturan user itu berfungsi sesuai yang dipilih/diaktifkan
**Tampakan layar dan log error**

![image](https://user-images.githubusercontent.com/31026980/116497362-5a353600-a8d1-11eb-83ee-cd5fedcbad8d.png)

**Versi OpenSID**

**Tema Yg Digunakan**

**Informasi tambahan**

**Comment by eddieridwan** [comment]
Sdh diterapkan untuk modul di bawah menu Kependudukan: Penduduk, Keluarga, Kelompok, Data Suplemen dan Rumah Tangga. Issue ini akan ditutup dan issue tambahan dibuat untuk masing2 menu.
