### ISSUE TITLE
[Template Surat] Hasil ekspor lampiran f.101, f.15, f16 di tanggal pembuatan, nama kepala desa dan petugas register supaya bisa terinfut 

### ISSUE THREAD

**Issue by spdoboze** [OpenSID/OpenSID#4163]
### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by HerryWanda** [comment]
Mohon di perjelas issue nya..

**Comment by spdoboze** [comment]
versi 21.08
php 7.4.16
windows 10

Hasil ekspor lampiran f.101, f.15, f16 di tanggal / titimangsa dan nama petugas tidak tercantum, gimana supaya tercantum tanggal pembuatan dan nama petugasnya

![Cuplikan layar 2021-08-06 210254](https://user-images.githubusercontent.com/82778393/128522230-c5447e69-db4a-49ef-8400-72c34147ac26.jpg)

**Comment by afa28** [comment]
Sy cek, lampiran yg disebutkan sudah sesuai. Contoh : 
![dgdg](https://user-images.githubusercontent.com/57283157/129122511-0f76b626-ac5c-4357-bb4f-6ae20220b172.png)

untuk tgl bisa berdiskusi terlebih dahulu dgn pengguna lain di group FB dan telegram.

**Comment by andifahruddinakas** [comment]
Mas @yogiperdana, coba cek ulang ini.

**Comment by yogiperdana** [comment]
> Mas @yogiperdana, coba cek ulang ini.

Oke mas

**Comment by yogiperdana** [comment]
F-1.0.1 aman

![image](https://user-images.githubusercontent.com/14155050/162112690-3a29f2bb-bd41-4ce2-880b-6a2512277260.png)

**Comment by yogiperdana** [comment]
F-1.15 aman

![image](https://user-images.githubusercontent.com/14155050/162112987-ea596cc1-0632-4bec-855d-ab6a2e9c375e.png)

**Comment by yogiperdana** [comment]
F-.1.16 aman

![image](https://user-images.githubusercontent.com/14155050/162113191-490de7aa-7626-4037-8e48-aeacdf5686b1.png)

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melalui pr https://github.com/OpenSID/premium/pull/936
