### ISSUE TITLE
Cetak Laporan Bulan Fitur Statistik Tempat Tanda Tangan Tidak Muncul Nama yang dipilih [BUG] 

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#4164]
**Jelaskan error yg dialami**
Ditempat tanda tangan yg tercantum Nama Muhammad Ilham nama tersebut bukan nama Kelapa Desa Yang di Pilih Untuk Tanda Tangan Laporan, yang seharusnya di system ini Nama Kepala Desa adalah AHLUL

**Cara untuk mereplikasi errornya**

**Hasil yg diharapkan**
Supaya normal kembali

**Tampakan layar dan log error**

**Versi OpenSID**

**Tema Yg Digunakan**

**Informasi tambahan**

**Comment by agungsugiarto** [comment]
Pak @Zoel-WB, terima kasih sudah melaporkan issue, Issue ini saya tutup karena tidak ditemukan ditempat lain. Silahkan issue ini dibuka kembali jika masih mengalami issue tersebut.

![Untitled](https://user-images.githubusercontent.com/10989147/116839433-97186a00-abfc-11eb-8a1d-d8a4336eda1c.png)

![Untitled1](https://user-images.githubusercontent.com/10989147/116839507-d941ab80-abfc-11eb-8e24-8b7100aa2626.png)

![image](https://user-images.githubusercontent.com/10989147/116839536-efe80280-abfc-11eb-8324-d63975423dbb.png)

![image](https://user-images.githubusercontent.com/10989147/116839572-1017c180-abfd-11eb-8ff5-34549bb42853.png)
