### ISSUE TITLE
Cetak Buku Administrasi Umum - Buku Agenda - Surat Masuk [BUG] 

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#4165]
**Jelaskan error yg dialami**
 V21.04 Premium-Pasca

**Cara untuk mereplikasi errornya**

**Hasil yg diharapkan**

**Tampakan layar dan log error**

**Versi OpenSID**

**Tema Yg Digunakan**

**Informasi tambahan**

**Comment by agungsugiarto** [comment]
Pak @Zoel-WB, terima kasih sudah melaporkan issue, mohon lengkapi issue bapak terkait.
- Jelaskan error yg dialami
- Hasil yg diharapkan
- Tampakan layar dan log error
- Versi OpenSID
- dll

Lihat contoh issue #4148

**Comment by Zoel-WB** [comment]
Cetak Buku Administrasi Umum - Buku Agenda - Surat Masuk sama kejadian dengan Cetak Laporan Buku Administrasi Umum - Buku Ekspedisi ...
![image](https://user-images.githubusercontent.com/64481641/116880672-81329580-ac4c-11eb-97ae-3a789b4f6878.png)
![image](https://user-images.githubusercontent.com/64481641/116880817-a58e7200-ac4c-11eb-87dc-76b5b1bb4559.png)

Sedangkan yang tercetak dan tertera dalam laporan, adalah nama yg tidak dipilih bahkan tidak ada dalam database desa sebagai pamong didesa.
![Uploading image.png…]()

**Comment by agungsugiarto** [comment]
Pak @Zoel-WB yg bermasalah `Buku Agenda - Surat Masuk` atau `Buku Ekspedisi` ?

**Comment by Zoel-WB** [comment]
Keduanya Pak ada issue masing, permasalahannya sama pak

**Comment by agungsugiarto** [comment]
Saya tidak menemukan masalah di cetak Cetak Buku Administrasi Umum > Buku Agenda - Surat Masuk

![image](https://user-images.githubusercontent.com/10989147/116883164-7cbbac00-ac4f-11eb-9880-8764bf17b5f6.png)

![image](https://user-images.githubusercontent.com/10989147/116883234-8fce7c00-ac4f-11eb-8aa7-f65bc0366223.png)

Apakah bapak sudah mencoba di berputar atau di local bapak ?

**Comment by agungsugiarto** [comment]
Silahkan lihat di tabel `tweb_desa_pamong` apakah Muhammad Ilham dan Mustahiq S.Adm ada di tabel tersebut ?

**Comment by Zoel-WB** [comment]
Barangkali karena pilihan di demo dengan nama yg tampil pada hasil cetak sama pak, sedang kalau sudah dipakai di desa-desa nama-nama tersebut sudah berubah, akan tetapi tidak tampil dalam cetak laporan.
![image](https://user-images.githubusercontent.com/64481641/116884143-97425500-ac50-11eb-8589-283b23d55fae.png)
![image](https://user-images.githubusercontent.com/64481641/116884157-9d383600-ac50-11eb-9e09-e938cdb9a28e.png)

**Comment by Zoel-WB** [comment]
> Silahkan lihat di tabel `tweb_desa_pamong` apakah Muhammad Ilham dan Mustahiq S.Adm ada di tabel tersebut ?
> Jika ada seharusnya yg bermasalah ada di database bapak.

Benar pak, nama-nama dimaksud adalah bawaan system default akan tetapi kenapa bisa terbawa ke desa pengguna pak padahal databasenya sudah berubah menjadi database desa itu sendiri harusnya nama default ini sendiri sudah terhapus, ini masalah nya pak @agungsugiarto 
![image](https://user-images.githubusercontent.com/64481641/116884842-67e01800-ac51-11eb-8b1e-67fff7825dab.png)

**Comment by agungsugiarto** [comment]
Kemungkinan saat bapak melakukan di desa bapak lupa untuk tidak dilukan pembersihan dulu

**Comment by Zoel-WB** [comment]
> Kemungkinan saat bapak melakukan di desa bapak lupa untuk tidak dilukan pembersihan dulu

Tapi ada dilaporan lain yg tidak bermaslah pak, atau pada cetak-cetak laporan lainnya...

**Comment by agungsugiarto** [comment]
di laporan cetak mana pak yg tidak bermasalah, nanti akan saya bandingkan query nya ?

**Comment by Zoel-WB** [comment]
> di laporan cetak mana pak yg tidak bermasalah, nanti akan saya bandingkan query nya ?

Ini Misalnya pada laporan cetak BUKU AGENDA SURAT KELUAR 
![image](https://user-images.githubusercontent.com/64481641/116885826-82ff5780-ac52-11eb-9ae9-acd8b95c988d.png)
![image](https://user-images.githubusercontent.com/64481641/116885842-88f53880-ac52-11eb-8af8-66dd9cd40a6a.png)

**Comment by agungsugiarto** [comment]
Oke sudah ketemu masalahnya pak, saat ditampilkan yg bikin error seharusnya `nama` tapi yg ditampilkan `pamong_nama`

**Comment by eddieridwan** [comment]
Perbaikan cetak surat masuk sudah dicommit ke `bug-fix` melalui https://github.com/OpenSID/premium/pull/196

**Comment by eddieridwan** [comment]
Perbaikan cetak buku ekspedisi sudah dicommit ke bug-fix melalui OpenSID/premium#196
