### ISSUE TITLE
Cetak Buku Ekspedisi Tanda Tangan Kepala Desa Bukan Nama yang dipilih yg ada dalam database system[BUG] 

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#4166]
**Jelaskan error yg dialami**
 V21.04 Premium Pasca atau Beta di https://berputar.opensid.or.id/

**Cara untuk mereplikasi errornya**

**Hasil yg diharapkan**

**Tampakan layar dan log error**

**Versi OpenSID**

**Tema Yg Digunakan**

**Informasi tambahan**

**Comment by agungsugiarto** [comment]
Pak @Zoel-WB, terima kasih sudah melaporkan issue, mohon lengkapi issue bapak terkait.

Jelaskan error yg dialami
Hasil yg diharapkan
Tampakan layar dan log error
Versi OpenSID
dll
Lihat contoh issue #4148

**Comment by Zoel-WB** [comment]
1. Pada saat mencetak Laporan Buku Administrasi Umum - Buku Ekspedisi
![image](https://user-images.githubusercontent.com/64481641/116877956-d8366b80-ac48-11eb-915a-be6fcbc38c49.png)

2. Pada pelihan yang menanda tangan laporan seperti berikut :
![image](https://user-images.githubusercontent.com/64481641/116878097-09af3700-ac49-11eb-945d-80deb8184ef1.png)
Laporan ditanda tangi oleh : AMIRUDDIN ABDUL RAHMAN
Laporan mengetahui oleh : RAZALI ABDULLAH

3. Sedang yang tampil dan tercetak pada laporan bulan nama yg terpilih seperti maksu di atas, akan tetapi yang tercetak pada laporan bahkan nama-nama yang ada dalam database desa apalagi sebagai pamong desa
![image](https://user-images.githubusercontent.com/64481641/116878381-775b6300-ac49-11eb-963c-67f838de524e.png)

**Comment by eddieridwan** [comment]
Sdh dicommit ke `bug-fix` melalui https://github.com/OpenSID/premium/pull/197
