### ISSUE TITLE
Cetak Laporan Fitur Sekretariat Menu Informasi Publik tidak ada tempat tanda tangan [BUG] 

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#4167]
**Jelaskan error yg dialami**
V21.04 Premium Pasca atau Beta Rilis 21.05

**Cara untuk mereplikasi errornya**

**Hasil yg diharapkan**

**Tampakan layar dan log error**

**Versi OpenSID**

**Tema Yg Digunakan**

**Informasi tambahan**

**Comment by agungsugiarto** [comment]
Pak @Zoel-WB, terima kasih sudah melaporkan issue, Lihat contoh issue #4148,  untuk melengkapi issue bapak terkait:
- Jelaskan error yg dialami
- Hasil yg diharapkan
- Tampakan layar dan log error
- Versi OpenSID
- dll

**Comment by Zoel-WB** [comment]
Agar letak tempat tanda tangan dicantumkan atau pilihan pilihan perintah dihilangkan dan tempat tanda tangan ditiadakan 
Langkah untuk mereplikasi error yg dialami, misalnya:
1. Pada saat memilih tombol untuk mencetak system menampilkan Form Cetak Laporan, disitu ada pilihan seperti yang tampil dalam screensote berikut, 
![image](https://user-images.githubusercontent.com/64481641/116876316-7aa11f80-ac46-11eb-9e3c-49ac29f1493b.png)

![image](https://user-images.githubusercontent.com/64481641/116876344-82f95a80-ac46-11eb-9f8d-78163cb7cbcf.png)

2. setelah memilih tombol cetak

![image](https://user-images.githubusercontent.com/64481641/116876424-a4f2dd00-ac46-11eb-855d-7db9830361d3.png)

Seharusnya tempat tanda tangan akan tampil seperti berikut
![image](https://user-images.githubusercontent.com/64481641/116876515-cf449a80-ac46-11eb-90ef-bcd8606bded9.png)

**Comment by eddieridwan** [comment]
Sdh dicommit ke `bug-fix` melalui https://github.com/OpenSID/premium/pull/198
