### ISSUE TITLE
[BUG] Pindahkan Buku Tanah di Desa dari Buku Administrasi Pembangunan ke Buku Administrasi Umum

### ISSUE THREAD

**Issue by mizwaruddin** [OpenSID/OpenSID#4169]
**Jelaskan error yg dialami**

Saat ini Buku Tanah di Desa berada di sub menu Buku Administrasi Pembangunan. Padahal berdasarkan Permendagri No. 47 Tahun 2016 buku administrasi tanah kas desa berada pada buku administrasi umum pada urutan ke 6.

**Cara untuk mereplikasi errornya**

**Hasil yg diharapkan**

**Tampakan layar dan log error**

**Versi OpenSID**

**Tema Yg Digunakan**

**Informasi tambahan**

**Comment by eddieridwan** [comment]
Sdh dicommit ke `bug-fix` melalui https://github.com/OpenSID/premium/pull/209
