### ISSUE TITLE
Link Hasil Scan QR Code tidak berfungsi. [BUG] 

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#4171]
**Jelaskan error yg dialami**
Saat scan QR Code yang mengandung URL, lalu klik tombol "kunjungi website" yang tersedia, maka URL nya tidak valid.

**Hasil yg diharapkan**
Beri pembeda, jika QR Code hanya mengandung Tulisan, tidak perlu muncul "kunjungi website". dan jika di dalam hasil QR Code mengandung link URL, tombol kunjungi website otomatis muncul dan dapat di klik langsung menuju URL dimaksud.

**Tampakan layar dan log error**
<img width="960" alt="2021-05-04_12h21_16" src="https://user-images.githubusercontent.com/46939846/116963718-da91d780-acd3-11eb-80fa-8238e922f75f.png">

**Comment by eddieridwan** [comment]
Sdh dicommit ke `rilis-dev` melalui https://github.com/OpenSID/premium/pull/203
