### ISSUE TITLE
[BUG] Tampilan Data peserta Program Bantuan pada area Layanan mandiri tidak sesuai pada tempatnya

### ISSUE THREAD

**Issue by tobagus69** [OpenSID/OpenSID#4172]
saya coba di demo opensid (begitu juga di punya saya)
- setelah masuk / login di layanan mandiri
- klik di "Program Bantuan"
- muncul "Daftar bantuan yang diterima"
- lalu saya klik di aksi (yang gambar mata)
- lalu muncul data peserta
- nah... isian Nomor Peserta, NIK, dan Nama itu sepertinya tidak sesuai dengan Isinya

demikian, terimakasih

![Capture](https://user-images.githubusercontent.com/83219220/117018457-b60f1d00-ad1e-11eb-8ac7-0d1100e46a96.JPG)

**Jelaskan error yg dialami**

**Cara untuk mereplikasi errornya**

**Hasil yg diharapkan**

**Tampakan layar dan log error**

**Versi OpenSID**

**Tema Yg Digunakan**

**Informasi tambahan**

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` (rilis umum) dan `bug-fix` (rilis premium) melalui https://github.com/OpenSID/premium/pull/205
