### ISSUE TITLE
Gak bisa hapus data terpilih pake ceklist pada input data manual keuangan [BUG] 

### ISSUE THREAD

**Issue by bhasyr** [OpenSID/OpenSID#4175]
**Jelaskan error yg dialami**

**Gak bisa hapus data terpilih pake ceklist pada input data manual keuangan**

**Informasi tambahan**

![InkedISSUE_LI](https://user-images.githubusercontent.com/83437147/117230689-cec72200-ae47-11eb-95f5-cebbd77e2a82.jpg)

**Comment by eddieridwan** [comment]
Sdh dicommit ke `bug-fix` melalui https://github.com/OpenSID/premium/pull/229
