### ISSUE TITLE
Tambahkan Detil Submenu Administrasi Keuangan di menu Buku Administrasi Desa

### ISSUE THREAD

**Issue by mizwaruddin** [OpenSID/OpenSID#4176]
**Apa kekurangan yg ingin diatasi?**

Tambahkan detil submenu Administrasi Desa sebagai berikut:
1. BUKU ANGGARAN PENDAPATAN DAN BELANJA DESA
2. BUKU RENCANA ANGGARAN BIAYA
3. BUKU KAS PEMBANTU KEGIATAN
4. BUKU KAS UMUM
5. BUKU KAS PEMBANTU
6. BUKU BANK DESA

**Jelaskan solusi yg diinginkan**

**Apakah ada alternatif lain**

**Untuk versi OpenSID mana**

**Informasi tambahan**

[Permen No.47 TH 2016_Lampiran_keuangan.pdf](https://github.com/OpenSID/OpenSID/files/6431275/Permen.No.47.TH.2016_Lampiran_keuangan.pdf)

**Comment by eddieridwan** [comment]
Sdh dicommit ke `rilis-dev`
