### ISSUE TITLE
Ubah Detil Sub Buku Administrasi Pembangunan di Menu Buku Administrasi Desa

### ISSUE THREAD

**Issue by mizwaruddin** [OpenSID/OpenSID#4177]
**Apa kekurangan yg ingin diatasi?**

Ubah detil Sub Menu Administrasi Pembangunan di Menu Buku Administrasi Desa dengan rincian sebagai berikut.
1. BUKU RENCANA KERJA PEMBANGUNAN
2. BUKU KEGIATAN PEMBANGUNAN
3. BUKU INVENTARIS HASIL-HASIL PEMBANGUNAN
4. BUKU KADER PEMBERDAYAAN MASYARAKAT
5. 

**Jelaskan solusi yg diinginkan**

**Apakah ada alternatif lain**

**Untuk versi OpenSID mana**

**Informasi tambahan**

[Permen No.47 TH 2016_Lampiran_Pembangunan.pdf](https://github.com/OpenSID/OpenSID/files/6431299/Permen.No.47.TH.2016_Lampiran_Pembangunan.pdf)

**Comment by eddieridwan** [comment]
Sdh dicommit ke `rilis-dev`
