### ISSUE TITLE
Tambahkan Buku Rencana Kerja Pembangunan di Buku Administrasi Pembangunan

### ISSUE THREAD

**Issue by mizwaruddin** [OpenSID/OpenSID#4178]
**Apa kekurangan yg ingin diatasi?**

Tambahkan Buku Rencana Kerja Pembangunan dengan form dan petunjuk pengisian sbb:
![Buku Rencana Kerja Pembangunan](https://user-images.githubusercontent.com/39736008/117232409-4185cc80-ae4b-11eb-90ad-440753d3a80c.png)

**Jelaskan solusi yg diinginkan**

Tugas ini untuk menerapkan Buku Rencana Kerja Pembangunan yg ditampilkan di menu OpenSID sebagai berikut:
![pembangunan-1](https://user-images.githubusercontent.com/249563/128443208-cd098440-ca5f-47ae-a660-85f5535cf6cb.jpg)

**Informasi tambahan**

Perhatikan bahwa saat ini di OpenSID sudah ada fitur pengelolaan data Pembangunan, seperti terlihat di gambar berikut:
![pembangunan-2](https://user-images.githubusercontent.com/249563/128443674-edcb4bbc-c373-40c8-b5b8-929c14cc1be1.jpg)

Untuk tugas ini, pengelolaan data pembangunan tetap dilakukan di menu Pembangunan yg ada. Hanya laporan Buku Rencana Kerja Pembangunan saja yg ditampilkan di Buku Administrasi Desa.

Tambahkan data yg diperlukan pada modul Pembangunan yg ada supaya memenuhi kebutuhan data untuk Buku Rencana Kerja Pembangunan.

Untuk mempelajari menu yg ada, silakan memeriksa https://berputar.opensid.or.id.

**Comment by afa28** [comment]
Sudah digabung ke `FITUR PREMIUM`.
