### ISSUE TITLE
Tambahkan Buku Kegiatan Pembangunan di Buku Administrasi Pembangunan

### ISSUE THREAD

**Issue by mizwaruddin** [OpenSID/OpenSID#4179]
**Apa kekurangan yg ingin diatasi?**

Tambahkan Buku Kegiatan Pembangunan di Buku Administrasi Pembangunan sesuai Permendagri nomor 47/2016 dengan form dan petunjuk pengisian sbb:

![Buku Kegiatan Pembangunan2](https://user-images.githubusercontent.com/39736008/117233253-f8367c80-ae4c-11eb-8f02-a490f4727a89.jpg)

**Jelaskan solusi yg diinginkan**

Tugas ini untuk menerapkan Buku Kegiatan Pembangunan yg ditampilkan di menu OpenSID sebagai berikut:

![pembangunan-1](https://user-images.githubusercontent.com/249563/128592125-83d7b25c-9aa0-4737-b7c4-c6bc44c63425.jpg)

**Informasi tambahan**

Perhatikan bahwa saat ini di OpenSID sudah ada fitur pengelolaan data Pembangunan, seperti terlihat di gambar berikut:
![pembangunan-2](https://user-images.githubusercontent.com/249563/128443674-edcb4bbc-c373-40c8-b5b8-929c14cc1be1.jpg)

Untuk tugas ini, pengelolaan data pembangunan tetap dilakukan di menu Pembangunan yg ada. Menu `Buku Administrasi Pembangunan > Buku Kegiatan Pembangunan` hanya menampilkan laporannya saja.

Tambahkan data yg diperlukan pada modul Pembangunan yg ada supaya memenuhi kebutuhan data untuk Buku Kegiatan Pembangunan.

Untuk mempelajari menu yg ada, silakan memeriksa https://berputar.opensid.or.id.

**Comment by cwicaksono** [comment]
Ini saya coba deploy ke local untuk versi Demo, sub menunya kok berbeda ya cuma ada "Buku Tanah di Desa" sama "Buku Tanah Kas Desa", sama untuk menu "Pembangunan" juga tidak ada ya di versi Demo, saya menggunakan branch master dari versi Demo

**Comment by muhtar-coder** [comment]
> **Apa kekurangan yg ingin diatasi?**
> 
> Tambahkan Buku Kegiatan Pembangunan di Buku Administrasi Pembangunan sesuai Permendagri nomor 47/2016 dengan form dan petunjuk pengisian sbb:
> 
> ![Buku Kegiatan Pembangunan2](https://user-images.githubusercontent.com/39736008/117233253-f8367c80-ae4c-11eb-8f02-a490f4727a89.jpg)
> 
> **Jelaskan solusi yg diinginkan**
> 
> Tugas ini untuk menerapkan Buku Kegiatan Pembangunan yg ditampilkan di menu OpenSID sebagai berikut:
> 
> ![pembangunan-1](https://user-images.githubusercontent.com/249563/128592125-83d7b25c-9aa0-4737-b7c4-c6bc44c63425.jpg)
> 
> **Informasi tambahan**
> 
> Perhatikan bahwa saat ini di OpenSID sudah ada fitur pengelolaan data Pembangunan, seperti terlihat di gambar berikut:
> ![pembangunan-2](https://user-images.githubusercontent.com/249563/128443674-edcb4bbc-c373-40c8-b5b8-929c14cc1be1.jpg)
> 
> Untuk tugas ini, pengelolaan data pembangunan tetap dilakukan di menu Pembangunan yg ada. Menu `Buku Administrasi Pembangunan > Buku Kegiatan Pembangunan` hanya menampilkan laporannya saja.
> 
> Tambahkan data yg diperlukan pada modul Pembangunan yg ada supaya memenuhi kebutuhan data untuk Buku Kegiatan Pembangunan.
> 
> Untuk mempelajari menu yg ada, silakan memeriksa https://berputar.opensid.or.id.

Saya tidak terlalu paham antara jenis outputnya dengan yg biasa di kerjakan di desa.
Tapi melihat menu fitur yg ada di opensid antara lain :
1. Buku rencana pembangunan
2. Buku kegiatan pembangunan
3. Buku inventaris hasil2 pembangunan.
 
Apakah  diartikan bahwa no 1 adalah daftar pembangunan yg akan di rencanakan tsb adalah daftar rencana kerja yg sudah masuk di APBDes ataukah rencana kerja hasil musdes ataukah daftar  RKPDes ?

Kalo untuk no 2 berdasarkan printoutnya adalah kegiatan pembangunan yg sudah siap/akan di laksanakan berdasarkan rancangan APBDes.

Dan untuk no 3   sudah jelas.

**Comment by ai-skematik** [comment]
yg sy pahami nomor 1 kegiatan pembangunan yg sudah masuk di APBDesa 2. kegiatan yg sudah mulai dikerjakan, 3. kagiatan yg sudah selesai dilaksanakan. jika ini sudah diterapkan, menu pembangunan saran untuk di hapus dan pengisian persentasi, gambar dan lokasi dipindahkan ke menu buku kegiatan pembangunan.,

**Comment by andifahruddinakas** [comment]
Pak @nurisakbar, kesimpulan dari pembahasan di group bisa ditambahkan di issue ini.
