### ISSUE TITLE
[Bumindes] Tambahkan Buku Inventaris Hasil-Hasil Pembangunan di Menu Buku Administrasi Pembangunan

### ISSUE THREAD

**Issue by mizwaruddin** [OpenSID/OpenSID#4180]
**Apa kekurangan yg ingin diatasi?**

Tambahkan Buku Inventaris Hasil-Hasil Pembangunan di Menu Buku Administrasi Pembangunan dengan form dan petunjuk pengisian sbb:
![Buku Inventaris Hasil-Hasil Pembangunan](https://user-images.githubusercontent.com/39736008/117233377-33d14680-ae4d-11eb-9fc2-619d9be2716a.png)

**Jelaskan solusi yg diinginkan**

Laporkan data pembangunan yang sudah diisi pada modul pembangunan sebelumnya. Data yang diperlukan sudah tersedia di tabel `pembangunan` dan `pembangunan_ref_dokumentasi`.

Yang dilaporkan adalah pembangunan yang telah mencapai persentase pembangunan 100%. Persentase pembangunan dapat dilihat di tabel `pembangunan_ref_dokumentasi.persentase`.

Untuk menampilkan laporan ini, hanya dibutuhkan tahun anggaran. Tidak ada informasi lain yg perlu diisi. 

**Untuk versi OpenSID mana**

Pasca v21.11-premium

**Informasi tambahan**

Modul lain yang terkait:

1. Pembangunan
2. Buku Administrasi Desa > Administrasi Pembangunan
    1. Buku Rencana Kerja Pembangunan
    2. Buku Kegiatan Pembangunan

Pelajari dan coba semua modul di atas untuk mengetahui data pembangunan yang diisi dan bagaimana digunakan di laporan. Sebagai contoh di form isian Pembangunan terlihat bahwa lokasi pembangunan dapat diisi sesuai Info Desa > Wilayah Administratif, atau bisa diisi bebas. 

Ada kemungkinan data `anggaran` yang diisi di tabel `pembangunan` berbeda dengan biaya akhir yang akan dilaporkan pada Laporan Hasil Pembangunan. Masalah ini perlu dikonsultasikan dengan para pengguna. Kalau bisa berbeda, perlu ditambahkan fitur untuk menyimpan perubahan biaya kegiatan.

Berikut informasi tabel bagi yg belum terbiasa dengan OpenSID.

- `pembangunan_ref_dokumentasi.id_pembangunan` adalah foreign key ke `pembangunan.id`
- `pembangunan.id_lokasi` adalah foreign key ke `tweb_wil_clusterdesa.id`

**Comment by FaisyalRachman** [comment]
Saya sudah melakukan pull request,
