### ISSUE TITLE
Tambahkan Buku Kader Pemberdayaan Masyarakat di Buku Administrasi Pembangunan

### ISSUE THREAD

**Issue by mizwaruddin** [OpenSID/OpenSID#4181]
**Apa kekurangan yg ingin diatasi?**

Tambahkan Buku Kader Pemberdayaan Masyarakat di Buku Administrasi Pembangunan dengan form dan petunjuk pengisian sbb, sesuai dengan Permendagri 47/2016:

![Buku Kader Pemberdayaan Masyarakat](https://user-images.githubusercontent.com/39736008/117233760-f28d6680-ae4d-11eb-837f-230df7afd2ed.png)

**Jelaskan solusi yg diinginkan**

**Apakah ada alternatif lain**

**Untuk versi OpenSID mana**

**Informasi tambahan**

**Comment by eddieridwan** [comment]
- [ ] Ditampilkan di menu `Buku Administrasi Desa > Administrasi Pembangunan > Buku Kader Pemerdayaan Masyarakat`. Lihat gambar di bawah.
- [ ] Data nama, jenis kelamin, umur dan alamat diambil dari data penduduk yg sudah ada (tabel `tweb_penduduk` )
- [ ] Pendidikan, kursus bisa lebih dari satu per kader. Salah satu diambil dari pendidikan sesuai kartu keluarga, yg sdh tersimpan di tabel `tweb_penduduk.pendidikan_kk_id`. Untuk pengelolaan data pendidikan/kursus lainnya perlu disediakan form, tabel dan fitur baca/tulis/ubah/hapus. Sediakan daftar pendidikan/kursus standar, tapi operator bisa mengisi selain dari pilihan standar. Lihat contoh pengisian data suku/etnis di form penduduk.
- [ ] Bidang keahlian juga bisa lebih dari satu per kader. Untuk pengelolaan data bidang keahlian perlu disediakan form, tabel dan fitur baca/tulis/ubah/hapus. Sediakan daftar bidang keahlian standar, tapi operator bisa mengisi selain dari pilihan standar. Lihat contoh pengisian data suku/etnis di form penduduk.

![kader-1](https://user-images.githubusercontent.com/249563/131624605-f4cbb442-c80c-4908-aa24-091af2449b22.jpg)

**Comment by nurisakbar** [comment]
selain penjelasan di atas, berikut ini saya lampirkan tambahan informasi untuk issue ini
[rancagan modul kader.pdf](https://github.com/OpenSID/OpenSID/files/7114019/rancagan.modul.kader.pdf)

**Comment by eddieridwan** [comment]
Pengerjaan tugas ini telah diserahkan kepada Faisyal Rachman.
