### ISSUE TITLE
Tampilkan / Sembunyikan PIN saat Ganti PIN Layanan Mandiri

### ISSUE THREAD

**Issue by afa28** [OpenSID/OpenSID#4183]
**Apa kekurangan yg ingin diatasi?**

Tombol menampilkan / menyembunyikan PIN saat Ganti PIN layanan mandiri

**Jelaskan solusi yg diinginkan**

![photo_2021-05-06_21-11-36](https://user-images.githubusercontent.com/57283157/117313223-e508c880-aeaf-11eb-9ff7-0c048b44ed23.jpg)

**Apakah ada alternatif lain**

**Untuk versi OpenSID mana**

**Informasi tambahan**

**Comment by eddieridwan** [comment]
Sdh dicommit ke `rilis-dev` melalui https://github.com/OpenSID/premium/pull/213
