### ISSUE TITLE
Keyboard Virtual pada Layanan Mandiri tidak muncul dibeberapa surat [BUG] 

### ISSUE THREAD

**Issue by rizazoel** [OpenSID/OpenSID#4186]
**Jelaskan error yg dialami**

Settingan untuk anjungan sudah diaktifkan keyboard virtual, dan ketika login maupun masuk ke pilihan surat, keyboard virtual masih tampil. Namun ketika memilih surat "Keterangan Usaha" diklik Jenis usaha dan keterangannya tidak keluar keyboard virtualnya. dibeberapa surat lainnya seperti "Keterangan Pengantar" keyboard virtual masih muncul, namun di Surat "Keterangan Usaha" keyboard virtualnya tidak muncul. Saya coba di https://berputar.opensid.or.id permasalahannya tetap sama.

**Cara untuk mereplikasi errornya**

**Hasil yg diharapkan**

**Tampakan layar dan log error**

**Versi OpenSID**
Versi 21.05-premium-pasca

**Tema Yg Digunakan**

**Informasi tambahan**

**Comment by eddieridwan** [comment]
@agungsugiarto perhatikan panduan https://github.com/OpenSID/OpenSID/wiki/Surat-Layanan-Mandiri.

Panduan itu menjelaskan apa yg perlu dilakukan untuk mengaktifkan keyboard virtual. Saat ini baru 4 yg telah diaktifkan. 

Untuk issue ini, mohon aktifkan keyboard virtual untuk surat bawaan sistem lainnya yg saat ini telah disediakan untuk Layanan Mandiri. Yaitu, aktifkan surat berikut:

* Biodata Penduduk
* Keterangan Beda Identitas
* Keterangan Bepergian / Jalan
* Keterangan Jual Beli
* Keterangan KTP dalam Proses
* Keterangan Kurang Mampu
* Keterangan Usaha
* Pengantar Izin Keramaian
* Pengantar Laporan Kehilangan

Bagi surat lain, desa dipersilakan menyesuaikan mengikut panduan https://github.com/OpenSID/OpenSID/wiki/Surat-Layanan-Mandiri.

**Comment by rizazoel** [comment]
boleh pak silahkan

**Comment by eddieridwan** [comment]
Sdh dicommit ke `bug-fix` melalui https://github.com/OpenSID/premium/pull/222
