### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by fadlunabid76** [OpenSID/OpenSID#4196]
upload foto video acces denied di responsiv file manager, mohon bantuanya

**Comment by agungsugiarto** [comment]
Pak @fadlunabid76 terima kasih sudah melaporkan issue, issue ini saya tutup karena issue hanya ditujukan untuk melaporkan bug / permintaan fitur. Untuk lain kali harap ditanyakan di https://www.facebook.com/groups/OpenSID atau di https://t.me/joinchat/SI0GWHeqKT39Gxhh.

Untuk permasalah bapak solusinya cukup lakukan logout, kemudian login kembali. Terima kasih
