### ISSUE TITLE
Untuk data eksternal yg di-cache, seperti status IDM, sediakan tombol `Perbaharui Data`

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#4200]
**Jelaskan error yg dialami**

IDM Tahun Sebelumnya tidak ditampilkan, misal untuk menampilkan IDM tahun 2020
![image](https://user-images.githubusercontent.com/64481641/119080448-4ee2af80-ba24-11eb-8835-ce1b918f9d06.png)

sedangkan IDM tahun yang sedang berjalan atau tahun 2021, tampil normal 
![image](https://user-images.githubusercontent.com/64481641/119080545-78034000-ba24-11eb-86b5-74af9b684c59.png)

**Cara untuk mereplikasi errornya**

**Hasil yg diharapkan**

**Tampakan layar dan log error**

**Versi OpenSID**

https://berputar.opensid.or.id/status_desa

**Tema Yg Digunakan**

**Informasi tambahan**

**Comment by eddieridwan** [comment]
Masalah ini terjadi di https://berputar.opensid.or.id karena data error/lama tersimpan di cache, dan data cache tersebut yg tampil. Yang diperlukan untuk issue ini adalah disediakannya tombol untuk `memperbaharui data`, yaitu untuk mengambil data lagi menggantikan yg ada di cache.

**Comment by eddieridwan** [comment]
Sdh dicommit ke `rilis-dev` melalui https://github.com/OpenSID/premium/pull/230
