### ISSUE TITLE
Data Penduduk Tidak Tetap yang ditambah melalui fitur Siaga Covid-19 Sebagai penduduk Non Domisili tidak ditampilkan dalam List Data Penduduk [BUG] 

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#4201]
**Jelaskan error yg dialami**
 Penduduk yang besangkutan tidak dapat dicari dalam daftar penduduk untuk dilengkapi datanya, sedang dalam daftar rekap jumlah penduduk pada Dasbaord, penduduk yang ditambahkah melalu fitur siaga covid-19 tetap di jumlahkan.

![image](https://user-images.githubusercontent.com/64481641/119096260-90338900-ba3d-11eb-9077-1efc18c60a38.png)
![image](https://user-images.githubusercontent.com/64481641/119096369-b6592900-ba3d-11eb-95f4-91054fab7418.png)

Data penduduk tidak dapat dicari untuk dipanggil guna untuk memperbaiki dan melengkapi Biodata terhadap penduduk dimaksud, untuk dapat menggunakan layanan mandiri maupun kebutuhan data administrasi lainnya.

**Cara untuk mereplikasi errornya**

**Hasil yg diharapkan**

**Tampakan layar dan log error**

**Versi OpenSID**

https://berputar.opensid.or.id/covid19/form_pemudik

**Tema Yg Digunakan**
 Natra

**Informasi tambahan**

**Comment by agungsugiarto** [comment]
Log error

```php
ERROR - 2021-05-24 10:02:14 --> Query error: Incorrect datetime value: '-' for column 'tgl_lapor' at row 1 - Invalid query: INSERT INTO `log_penduduk` (`tgl_peristiwa`, `kode_peristiwa`, `tgl_lapor`, `id_pend`, `created_by`, `maksud_tujuan_kedatangan`) VALUES ('2021-05-24', NULL, '-', 98, '1', NULL) ON DUPLICATE KEY UPDATE tgl_peristiwa=VALUES(tgl_peristiwa),kode_peristiwa=VALUES(kode_peristiwa),tgl_lapor=VALUES(tgl_lapor),id_pend=VALUES(id_pend),created_by=VALUES(created_by),maksud_tujuan_kedatangan=VALUES(maksud_tujuan_kedatangan)
```

**Comment by eddieridwan** [comment]
Sdh dicommit ke `bug-fix`
