### ISSUE TITLE
Sediakan Tombol Lihat di Kelengkapan Dokumen di Menu Layanan Mandiri Sub Menu Permohonan Surat

### ISSUE THREAD

**Issue by WAHYUDIK** [OpenSID/OpenSID#4202]
**Jelaskan error yg dialami**

Pada saat memproses surat di Permohonan Surat Layanan Mandiri tidak ada tombol untuk lihat/view, alangkah baiknya ditambahkan tombol lihat, sehingga admin/operator bisa memilih antara melihat saja berkas-berkas dan atau langsung mengunduh untuk sebagai arsip di kantor desa.
![image](https://user-images.githubusercontent.com/31026980/119214261-a4d05980-baef-11eb-8fb1-c09e3c70f714.png)

saat ini berkas langsung terunduh otomatis. 

**Cara untuk mereplikasi errornya**

**Hasil yg diharapkan**

harapannya disediakan tombol view/lihat, 
**Tampakan layar dan log error**

**Versi OpenSID**

**Tema Yg Digunakan**

**Informasi tambahan**

**Comment by afa28** [comment]
@WAHYUDIK knpa di tutup???

**Comment by WAHYUDIK** [comment]
maaf salah klik tadi

**Comment by eddieridwan** [comment]
@WAHYUDIK untuk fitur baru mohon gunakan template Fitur Baru. Template bug hanya untuk masalah yg menyebabkan terjadinya kesalahan.

**Comment by eddieridwan** [comment]
Sdh dicommit ke `rilis-dev` melalui https://github.com/OpenSID/premium/pull/231
