### ISSUE TITLE
[BUG] Penandatanganan di Buku Peraturan Desa Tidak Tampil Secara Benar

### ISSUE THREAD

**Issue by WAHYUDIK** [OpenSID/OpenSID#4203]
**Jelaskan error yg dialami**

Penandatanganan di Buku Peraturan Desa tidak tampil dengan benar, dan sebutan desa juga masih tampil, tulisan mengetahui dan nama desa beserta tanggal huruf besar semua
![image](https://user-images.githubusercontent.com/31026980/119215693-896a4c00-baf9-11eb-84a9-1ad5ebd226bf.png)

**Cara untuk mereplikasi errornya**

**Hasil yg diharapkan**

penandatanganan bisa tampil dengan benar, dan juga sebutan desa tidak ditampilkan, cukup nama desa saja serta tulisan mengetahui, nama desa beserta tanggal cukup huruf depan saja yang besar
**Tampakan layar dan log error**

**Versi OpenSID**

**Tema Yg Digunakan**

**Informasi tambahan**

**Comment by eddieridwan** [comment]
Sdh dicommit ke `rilis-dev`.
