### ISSUE TITLE
[BUG]  Penandatanganan di Buku Keputusan Kepala Desa Tidak Tampil Dengan Benar

### ISSUE THREAD

**Issue by WAHYUDIK** [OpenSID/OpenSID#4204]
**Jelaskan error yg dialami**

Penandatanganan di Buku Keputusan Kepala Desa tidak tampil dengan benar, sebutan desa juga masih tampil di tanggal cetak serta tulisan mengetahui dan nama desa menggunakan hutuf besar semua
![image](https://user-images.githubusercontent.com/31026980/119216028-6345ab80-bafb-11eb-9c2d-798586d42f4c.png)

**Cara untuk mereplikasi errornya**

**Hasil yg diharapkan**

Penandatanganan bisa tampil dengan benar, sebutan desa dihilangkan cukup nama desa saja dan tulisannya tidak menggunakan hutuf besar semua, tetapi cukup huruf depan saja yang besar

**Tampakan layar dan log error**

**Versi OpenSID**

**Tema Yg Digunakan**

**Informasi tambahan**

**Comment by eddieridwan** [comment]
Sdh dicommit ke `rilis-dev`
