### ISSUE TITLE
Tanda Tangan Pamong Desa pada cetak Buku Lembaran Desa dan Berita Desa hanya tampil angkanya saja [BUG] 

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#4205]
**Jelaskan error yg dialami**
 https://berputar.opensid.or.id

**Cara untuk mereplikasi errornya**

**Hasil yg diharapkan**

**Tampakan layar dan log error**

**Versi OpenSID**

**Tema Yg Digunakan**

**Informasi tambahan**

**Comment by eddieridwan** [comment]
Sdh dicommit ke `bug-fix` melalui https://github.com/OpenSID/premium/pull/233
