### ISSUE TITLE
Tanda Tangan Pamong Pada Hasil Cetak Statistik Laporan Bulanan Tidak Tercetak [BUG] 

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#4206]
**Jelaskan error yg dialami**
 https://berputar.opensid.or.id/laporan

**Cara untuk mereplikasi errornya**

**Hasil yg diharapkan**

**Tampakan layar dan log error**

**Versi OpenSID**

**Tema Yg Digunakan**

**Informasi tambahan**

**Comment by ihsan2857** [comment]
Testing.
This just a test comment.

**Comment by eddieridwan** [comment]
Sdh dicommit ke `bug-fix` melalui https://github.com/OpenSID/premium/pull/234
