### ISSUE TITLE
Status Dasar Penduduk Tidak Dapat Di Pulihkan [BUG] 

### ISSUE THREAD

**Issue by muhtar-coder** [OpenSID/OpenSID#4207]
**Jelaskan error yg dialami**

Ketika ada warga di nyatakan hilang dan di buat status dasar nya "Hilang" kemudian beberapa waktu status tersebut di pulihkan atau di kembalikan, catatan tersebut masih menempel di catatan laporan penduduk bulanan sehingga mempengaruhi perhitungan jumlah laporan penduduk bulanan.

**Cara untuk mereplikasi errornya**

**Hasil yg diharapkan**

pengaturan status dasar dan laporan penduduk kembali normal

**Tampakan layar dan log error**

1.gambar hasil status dasar Hilang.
![image](https://user-images.githubusercontent.com/55665526/119283313-cc95fd80-bc66-11eb-9037-66f564806a1d.png)

2. gambar status dasar di kembalikan
![image](https://user-images.githubusercontent.com/55665526/119283185-71640b00-bc66-11eb-85e4-0dc7937561c2.png)

3. catatan laporan penduduk setelah status dasar di kembalikan (seharusnya kosong/normal)
![image](https://user-images.githubusercontent.com/55665526/119283170-63ae8580-bc66-11eb-941a-459a533c1b43.png)

**Versi OpenSID**

v.21.05 bug-fix

**Tema Yg Digunakan**

Default

**Informasi tambahan**

**Comment by agungsugiarto** [comment]
Saya sudah mencoba meriplikasi bug, tidak menemukan masalah yg dimaksud. Mungkin pak @eddieridwan atau mas @afa28 bisa membantu untuk meriplikasi masalah ini ?

**Comment by eddieridwan** [comment]
Bisa tanyakan langsung pada yg melaporkan @muhtar-coder . Minta ditunjukkan kasusnya di https://berputar.opensid.or.id.

**Comment by afa28** [comment]
Tdk ada masalah di https://berputar.opensid.or.id/laporan dgn mengikuti langkah2 di atas.

**Comment by eddieridwan** [comment]
@agungsugiarto @afa28 ada masalah apabila yg hilang adalah kepala keluarga. Pencatatan di log_keluarga tidak dikembalikan, sehingga masih tercatat.

**Comment by agungsugiarto** [comment]
> @agungsugiarto @afa28 ada masalah apabila yg hilang adalah kepala keluarga. Pencatatan di log_keluarga tidak dikembalikan, sehingga masih tercatat. 

Ini saat merubah status dasar atau mengembalikan status tersebut dari log penduduk pak?

**Comment by agungsugiarto** [comment]
Log error

```php
ERROR - 2021-05-24 10:37:08 --> Query error: Duplicate entry '37-4-2021-05-24 10:37:08' for key 'id_kk' - Invalid query: INSERT INTO `log_keluarga` (`id_kk`, `kk_sex`, `id_peristiwa`, `tgl_peristiwa`, `id_pend`, `id_log_penduduk`, `updated_by`) VALUES ('37', '1', '4', '2021-05-24 10:37:08', NULL, 130, '1')
```

**Comment by afa28** [comment]
> Log error
> 
> ```
> ERROR - 2021-05-24 10:37:08 --> Query error: Duplicate entry '37-4-2021-05-24 10:37:08' for key 'id_kk' - Invalid query: INSERT INTO `log_keluarga` (`id_kk`, `kk_sex`, `id_peristiwa`, `tgl_peristiwa`, `id_pend`, `id_log_penduduk`, `updated_by`) VALUES ('37', '1', '4', '2021-05-24 10:37:08', NULL, 130, '1')
> ```

Ya, ada error.

`ERROR - 2021-05-24 10:41:20 --> Query error: Duplicate entry '35-2-2021-05-24 10:41:20' for key 'id_kk' - Invalid query: INSERT INTO `log_keluarga` (`id_kk`, `kk_sex`, `id_peristiwa`, `tgl_peristiwa`, `id_pend`, `id_log_penduduk`, `updated_by`) VALUES ('35', '1', '2', '2021-05-24 10:41:20', NULL, 128, '1')`

**Comment by eddieridwan** [comment]
Sdh dicommit ke `bug-fix` melalui https://github.com/OpenSID/premium/pull/236
