### ISSUE TITLE
tambahkan menu di admin tentang penggunaan biaya dana desa dan pendapataan dana desa setiap bulan.. karena kurangnya tranparansi penggunaan dana desa sehiinga sering terjadi penyelewengan penggunaan dana desa baik operasional maupun pembangunan

### ISSUE THREAD

**Issue by Fajar-blackdeath** [OpenSID/OpenSID#4208]
### Bagaimana alurnya sampai muncul masalah?
saat sering sekali penyelewengaan dana desa yang tidak balance di akhr tahun banyak dana dana desa yang entah lari kmana. dengan adanya laporan bulanan tentang penggunaan dana desa setiap bulan memudahkan dalam menghitun dana desa yang masih ada dan sudah terpakai. bisa berupa dat exeell maupun ditambah dengan bukti pembayaran.

### Seperti apa yang diharapkan?
setiap tanggal 30 penggunaan dana dessa yang sudah dikeluarakan dicatat sehingga penguluaran biaya operasiaonal dll dapat terangkum dan mudah dihitung sehingga tidak terjadi penyelewngan dana di akhir masa penyusunan lpj yang sering kali banyak dana yang hilang.

### Apa yang terjadi?
yang sring terjadi adalah pembayaran biaya opersional yang lambat dan sering adanya penyelewengan dana yang yang digunkan untuk keperluan pribadi

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    21.5 bug fix 3| 2.x
| Versi PHP        | 
| System operasi   |

**Comment by HerryWanda** [comment]
Laporan ini bisa kita informasikan melalui menu keungan.. database siskeudes desa di import satu kali 1 bulan.

maka tampilan statitik dan laporan bisa kita tampilkan buatkan dinartikel.
