### ISSUE TITLE
[Tema] Sediakan tombol view/lihat di menu informasi publik dan peraturan desa

### ISSUE THREAD

**Issue by WAHYUDIK** [OpenSID/OpenSID#4209]
**Apa kekurangan yg ingin diatasi?**

**Jelaskan solusi yg diinginkan**

**Apakah ada alternatif lain**

**Untuk versi OpenSID mana**

**Informasi tambahan**

**Comment by eddieridwan** [comment]
@WAHYUDIK issue yg belum lengkap belum siap untuk diprioritaskan. Selalu lengkapi issue supaya programmer yg baru-pun dapat mengikuti apa yg diperlukan. Harap tidak membuat asumsi programmer akan mengerti apa yg anda maksud.

**Comment by WAHYUDIK** [comment]
untuk saat ini, di peraturan desa yang ditampilkan di home, filenya tidak bisa dilihat secara langsung, akan tetapi filenya terunduh secara otomatis, 
![image](https://user-images.githubusercontent.com/31026980/120209398-d87e5280-c258-11eb-804f-1981d2225126.png)
 
harapannya kedepan juga bisa disediakan tombol view, untuk memudahkan pengunjung.

**Comment by HerryWanda** [comment]
Lengkapi issue nya..
yg di komentar yudik, masukkan diatas.. biar jelas..
