### ISSUE TITLE
Perubahan Tombol Kembali di Edit Biodata Penduduk dari Fitur Daftar Anggota Keluarga

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#4210]
**Jelaskan error yg dialami**

Bukan Error akan tetapi penempatan Tombol Fitur pada Edit Data Penduduk langsung melalui Fitur Daftar Anggota Keluarga

**Cara untuk mereplikasi errornya**
1. Tombol Kembali dari edit data penduduk pada fitur daftar Keluarga yaitu "Tombol Kembali ke Daftar Penduduk"
2.  Setelah Data di edit dan Disimpan Tombol Kembali Diganti  ke "Kembali ke Daftar Anggota Keluarga"

![image](https://user-images.githubusercontent.com/64481641/119357673-094b0e80-bcd2-11eb-8aa4-5ff88d88f387.png)
![image](https://user-images.githubusercontent.com/64481641/119357987-5929d580-bcd2-11eb-847a-af8ae3b89ec9.png)

**Hasil yg diharapkan**

**Tampakan layar dan log error**

**Versi OpenSID**

**Tema Yg Digunakan**

**Informasi tambahan**

**Comment by eddieridwan** [comment]
@Zoel-WB untuk perbaikan fitur harap gunakan template fitur, bukan bug. Bug hanya untuk issue yg mengakibatkan terjadinya kesalahan. Setiap bug selalu diprioritaskan. Tetapi perbaikan fitur akan diprioritaskan terpisah bersama dengan permintaan perbaikan lainnya.

**Comment by eddieridwan** [comment]
Perubahan biodata penduduk bisa berasal dari Daftar Penduduk atau Daftar Anggota Keluarga. Opsi solusi:
1. Tombol kembali disesuaikan asal pemanggilan
2. Sediakan dua tombol kembali: ke Daftar Penduduk dan ke Daftar Anggota Keluarga

**Comment by eddieridwan** [comment]
Sdh dicommit ke `rilis-dev` melalui https://github.com/OpenSID/premium/pull/238
