### ISSUE TITLE
Penyesuaian menu dasar kemendagri dan kemendes (menu input kepemilikan rumah 1)

### ISSUE THREAD

**Issue by muhtar-coder** [OpenSID/OpenSID#4217]
**Apa kekurangan yg ingin diatasi?**

Sediakan menu input pada tabel edit keluarga yag menerangkan kepemilikan rumah

Pada tingkat desa,secara rutin dan berkelanjutan harus membuat input data laporan setiap tahun yang sifatnya wajib,baik ke kemendagri ataupun ke kemendes dan selama ini sebagai bahan atau dasar nya di lakukan dengan penghitungan manual terpisah sehingga perlu di sediakan di menu openSID guna melengkapi menu atau fitur-fitur lain yag sudah ada dan membantu pada proses penginputan tersebut.

**Jelaskan solusi yg diinginkan**

Pada kolom edit menu keluarga/kepala keluarga terdapat menu  kelas sosial,dan pada bagian bawahnya dapat di tambahkan menu kepemilikan rumah,dan kedua menu tersebut agar dapat di tampilkan sebagai data statistik .

1. gambar menu edit keluarga/kepala keluarga

![IMG-20210601-WA0116](https://user-images.githubusercontent.com/55665526/120264171-6db83000-c2c7-11eb-83e5-d4f398d58b8f.jpg)

![IMG-20210601-WA0114](https://user-images.githubusercontent.com/55665526/120263908-e23e9f00-c2c6-11eb-801f-d417aafdbcd0.jpg)

![IMG-20210601-WA0117](https://user-images.githubusercontent.com/55665526/120263947-f387ab80-c2c6-11eb-8c01-686bc94249e0.jpg)

2. gambar statistik kependudukan (statistik keluarga) kepemilikan rumah

![IMG-20210601-WA0115](https://user-images.githubusercontent.com/55665526/120263757-8bd16080-c2c6-11eb-8b29-7c3533135979.jpg)

**Apakah ada alternatif lain**

**Untuk versi OpenSID mana**

v21.07 premium

**Informasi tambahan**

Tampilan kebutuhan penginputan yang di minta kemendes IDM

![image](https://user-images.githubusercontent.com/55665526/120209230-a3720000-c258-11eb-8e6d-4bd9fa4b38c7.png)

**Comment by eddieridwan** [comment]
@muhtar-coder , selain untuk IDM, data kepemilkan rumah dan jenis bangunan rumah dibutuhkan untuk laporan apa lagi? Jika memang ada laporan lain yg membutuhkan, apakah klasifikasinya sama atau berbeda? Mohon lampirkan contoh laporannya.

**Comment by eddieridwan** [comment]
@afa28 @muhtar-coder, pertimbangannya adalah sbb:

1. Jika suatu data, seperti kepemilikan rumah, hanya diperlukan untuk satu laporan, seperti IDM, maka sebaiknya dilakukan di modul Analisis. Dibuatkan analisis untuk menyiapkan data yg diperlukan IDM. Sdh ada beberapa anggota komunitas yg menyiapkan master analisis untuk IDM. Tapi untuk itu mungkin modul Analisis perlu dilengkapi dengan sasaran desa (saat ini hanya ada sasaran penduduk dan keluarga).  Sdh ditambahkan issue https://github.com/OpenSID/OpenSID/issues/4355)
2. Kalau data tersebut digunakan di lebih dari satu laporan, tapi pilihan opsinya berbeda (misalnya kategori kepemilikan rumah berbeda), maka juga sebaiknya diterapkan di modul Analisis untuk masing2 laporan
3. Kalau data tersebut digunakan di lebih dari satu laporan, dan kategorinya baku, maka cocok untuk dimasukkan sebagai data baku keluarga, yaitu di tweb_keluarga.

**Comment by muhtar-coder** [comment]
Ya...

Pada tanggal Jum, 6 Agu 2021 12.19, Eddie Ridwan ***@***.***>
menulis:
