### ISSUE TITLE
Penambahan Form atau Baris Input Data Suku/Etnis Warga di Biodata Penduduk

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#4223]
**Apa kekurangan yg ingin diatasi?**

![gambar](https://user-images.githubusercontent.com/64481641/120438313-68341600-c3ab-11eb-95ec-adba9cbf5306.png)

 Penambahaan Data Suku diperlukan untuk dapat mendata setiap warga yg ditinggal dari suku apa saja, dan data ini diperlukan untuk pelaporan yh ada dalam IDM kemendes setiap Tahunnya
**Jelaskan solusi yg diinginkan**

**Apakah ada alternatif lain**

**Untuk versi OpenSID mana**

**Informasi tambahan**

**Comment by afa28** [comment]
https://github.com/OpenSID/OpenSID/issues/2728

**Comment by afa28** [comment]
Tambahan : 
1. Kategori suku/etnis ditambahkan pada modul statistik

**Comment by apidong** [comment]
untuk form intpu suku / etnis sendiri seperti apa. 
1. apakah berupa Pilihan
![image](https://user-images.githubusercontent.com/20056421/122357704-29db5100-cf7e-11eb-83aa-ba9caa99d663.png)
2. atau berupa form input biasa.
![image](https://user-images.githubusercontent.com/20056421/122357857-4b3c3d00-cf7e-11eb-9c9f-a8b4b90863e1.png)

**Comment by afa28** [comment]
> untuk form intpu suku / etnis sendiri seperti apa. 
> 1. apakah berupa Pilihan
> ![image](https://user-images.githubusercontent.com/20056421/122357704-29db5100-cf7e-11eb-83aa-ba9caa99d663.png)
> 2. atau berupa form input biasa.
> ![image](https://user-images.githubusercontent.com/20056421/122357857-4b3c3d00-cf7e-11eb-9c9f-a8b4b90863e1.png)
> 

Bisa gunakan select tag, artinya jika input sudah ada tinggal pili, jika belum ada bisa di input manual.

**Comment by Zoel-WB** [comment]
Kalau saya lebih condong input manual atau input biasa saja, arti-nya opsi nomor 2....
![image](https://user-images.githubusercontent.com/64481641/122361607-9c016500-cf81-11eb-9d56-191e849203eb.png)

**Comment by ai-skematik** [comment]
seperti satuan lapak saja bung @afa28

**Comment by afa28** [comment]
> seperti satuan lapak saja bung @afa28

itu pakai class select tags

**Comment by eddieridwan** [comment]
> untuk form intpu suku / etnis sendiri seperti apa.
> 
> 1. apakah berupa Pilihan
>    ![image](https://user-images.githubusercontent.com/20056421/122357704-29db5100-cf7e-11eb-83aa-ba9caa99d663.png)
> 2. atau berupa form input biasa.
>    ![image](https://user-images.githubusercontent.com/20056421/122357857-4b3c3d00-cf7e-11eb-9c9f-a8b4b90863e1.png)

Bung @apidong , kombinasi keduanya:
1. Boleh ketik langsung, kalau belum ada di pilihan
2. Tampilkan pilihan dari semua masukan yg sudah ada

Seperti disebut oleh teman2 di atas, lihat isian `satuan` di modul Lapak.

**Comment by eddieridwan** [comment]
Mungkin bung @Zoel-WB dan @ai-skematik bisa carikan daftar suku/etnis 'baku' untuk digunakan sebagai daftar pilihan awal.

**Comment by ai-skematik** [comment]
suku di indonesia itu puluhan ribu., tp dalam 1 desa biasanya paling banyak 5 suku., kecuali keluarahan di perkotaan., jd perlu dipertimbangkan memasukkan list seluruh suku di indonesia

**Comment by Zoel-WB** [comment]
> Mungkin bung @Zoel-WB dan @ai-skematik bisa carikan daftar suku/etnis 'baku' untuk digunakan sebagai daftar pilihan awal.

Oke Pak @eddieridwan saya coba cari.....

**Comment by Zoel-WB** [comment]
[SUKU.xlsx](https://github.com/OpenSID/OpenSID/files/6670065/SUKU.xlsx)

**Comment by Zoel-WB** [comment]
Kalaupun mau buat dengan system Pilihan Suku/Etnis akan Tetapi Bisa juga di Ketik Manual--> Seperti pada Pilihan Satuan Produk Lapak Desa.... 
![image](https://user-images.githubusercontent.com/64481641/122431171-6af35580-cfbe-11eb-995d-417048c0fbfa.png)

**Comment by ai-skematik** [comment]
> Kalaupun mau dibuat dengan system Pilihan Suku/Etnis akan Tetapi Bisa juga di Ketik Manual--> Seperti pada Pilihan Satuan Produk Lapak Desa.... 
> ![image](https://user-images.githubusercontent.com/64481641/122431171-6af35580-cfbe-11eb-995d-417048c0fbfa.png)
> 

saran sy di atas juga begitu. kalau dibuat list seluruh suku di indonesia itu banyak., karena ada desa yg hanya terdapat maksimal 5 suku., jd hanya 5 itu yg tampil di list.,

**Comment by eddieridwan** [comment]
@ai-skematik @Zoel-WB @afa28 terima kasih masukkannya.

Bung @apidong mohon ikuti contoh di https://github.com/OpenSID/OpenSID/issues/4223#issuecomment-863144586 (jabatan untuk anggota kelompok). Tetapi jika daftar awal besar, harap disimpan di tabel database dan tidak di `referensi_model.php`.

Bung @apidong , di daftar pilihan, buatkan supaya pilihan yg terpakai (yaitu yg sdh digunakan penduduk) diletakkan di awal daftar pilihan (urut abjad). Kalau bisa coba buatkan adanya garis pemisah antara pilihan terpakai dan yg lain. Ini akan memudahkan pengguna.

Tambahan pula, kalau daftar suku etnis disimpan di tabel, buatkan menu/form untuk `Suku Etnis` mengikuti contoh `Sekretariat > Klasifikasi Surat`. Jika admin inginkan, mereka bisa menggunakan menu itu untuk menghapus semua Suku Etnis yg tidak diperlukan. 

DI halaman statistik, batasi tampilan Suku Entis hanya pada pilihan suku etnis yg terpakai saja.

**Comment by apidong** [comment]
siap. rencana saya pakai modul yang ada disini https://select2.org/tagging

**Comment by eddieridwan** [comment]
> siap. rencana saya pakai modul yang ada disini https://select2.org/tagging

Ya, sudah digunakan di contoh yg saya berikan. Lihat saja contoh itu (Kependudukan > Kelompok > Tambah Anggota).

**Comment by afa28** [comment]
Pak @apidong bisa cek Komentar di PR https://github.com/OpenSID/premium/pull/284

**Comment by eddieridwan** [comment]
Sdh dicommit ke `rilis-dev` melalui https://github.com/OpenSID/premium/pull/284
