### ISSUE TITLE
Penambahan Form Input Data BPJS Ketegakerjaan di Biodata Penduduk

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#4224]
**Apa kekurangan yg ingin diatasi?**
 Form BPJS Ketenagakerjaan adalah form tersendiri diluar Form BPJS Kesehatan yg sudah ada sebelumnya
![gambar](https://user-images.githubusercontent.com/64481641/120440845-29ec2600-c3ae-11eb-93af-dfe469f778ea.png)

**Jelaskan solusi yg diinginkan**

**Apakah ada alternatif lain**

**Untuk versi OpenSID mana**

**Informasi tambahan**

**Comment by afa28** [comment]
Tambahan : 
1. Kategori BPJS Ketegakerjaan ditambahkan pada modul statistik

**Comment by afa28** [comment]
Satu paket dgn https://github.com/OpenSID/OpenSID/issues/4223

**Comment by eddieridwan** [comment]
@Zoel-WB , apakah seseorang dapat memiliki BPJS Ketenagakerjaan **DAN** juga BPJS biasa? Untuk memudahkan, apakah cukup mencatat satu jenis asuransi saja? Yaitu tambahkan BPJS Ketenagakerjaan sebagai pilihan saja di kolom asuransi yg sudah ada -- dan tidak perlu menambah dua kolom lagi (yaitu terpisah untuk BPJS Ketenagakerjaan).

![bpjs-1](https://user-images.githubusercontent.com/249563/121471146-91cfeb80-ca02-11eb-8a5b-f8fcabc09e54.jpg)

**Comment by Zoel-WB** [comment]
Iya benar pak BPJS kesehatan tersendiri  utk pelayanan kesehatan saja, Sedang BPJSKetenagaKerjaan menyangkut dgn kesejahteraan tenaga kerja bg warga yg bekerja disektor formal.

**Comment by eddieridwan** [comment]
Saat ini seorang penduduk cukup memilih satu jenis asuransi, terlepas apakah memiliki BPJS Kesehatan atau Asuransi Swasta. Penduduk cukup memilih asuransi yg dirasakan terpenting. Jadi dengan menambah pilihan BPJS Ketenagakerjaan, warga dapat mengisi pilihan itu kalau itu dirasakan sebagai asuransi dia yg terpenting (atau diberi petunjuk asuransi mana yg diprioritaskan untuk dicatat). Saya rasa tidak perlu mencatat **semua** jenis asuransi yg dimiliki seseorang. Karena tujuan awal dari kolom ini adalah untuk mencatat apakah seorang warga memiliki asuransi kesehatan atau tidak.

**Comment by Zoel-WB** [comment]
Satu orang warga bisa memiliki 2 BPJS, yaitu BPJS Kesehatan kalau sekarang disebut dgn KIS, dan BPJS Ketenagakerjaan.

Kedua BPJS ini ada statistik nya masing2.

**Comment by eddieridwan** [comment]
Kalau ingin BPJS Ketenagakerjaan dicatat secara terpisah, mohon lampirkan dasar kebutuhannya. Instansi atau pihak mana yg memerlukan laporan statistiknya? Informasi apa lagi yg bisa anda berikan untuk mendukung kebutuhan ini?

**Comment by eddieridwan** [comment]
@apidong tambahkan isian untuk Nomor BPJS Ketenagakerjaan seperti terlihat di gambar berikut. Field tersebut dikosongkan jika penduduk ybs tidak memiliki. Jadi di statistik yg diperiksa adalah apakah field tersebut diisi atau tidak.

![bpjs-1](https://user-images.githubusercontent.com/249563/122324929-01972680-cf6d-11eb-9dd7-9e4c25459773.jpg)

**Comment by apidong** [comment]
@eddieridwan @Zoel-WB 
untuk tabel statistiknya, formatnya seperti apa?

> Satu orang warga bisa memiliki 2 BPJS, yaitu BPJS Kesehatan kalau sekarang disebut dgn KIS, dan BPJS Ketenagakerjaan.
> 
> Kedua BPJS ini ada statistik nya masing2.

**Comment by eddieridwan** [comment]
@apidong caranya seperti untuk statistik Akte Kelahiran, tapi menggunakan kategori Pekerjaan.

![stats-1](https://user-images.githubusercontent.com/249563/122388327-21513d80-cfb3-11eb-8eac-831962b5d564.jpg)

**Comment by eddieridwan** [comment]
Sdh dicommit ke `rilis-dev` melalui https://github.com/OpenSID/premium/pull/294
