### ISSUE TITLE
[Template Surat] Formulir Biodata Penduduk F.1.01 Versi Terbaru

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#4225]
**Apa kekurangan yg ingin diatasi?**

Penggunaan Versi Terbaru Blanko F.1.01 (Sepertinya masih banyak yang belum menerapkan di daerah lain)

**Jelaskan solusi yg diinginkan**

update versi terbaru 

[FORMULIR F.1-01 BIODATA KELUARGA.pdf](https://github.com/OpenSID/OpenSID/files/6589020/FORMULIR.F.1-01.BIODATA.KELUARGA.pdf)

**Apakah ada alternatif lain**

**Untuk versi OpenSID mana**

**Informasi tambahan**

**Comment by balongbesuk** [comment]
taruh sini dulu belum nemu peraturan tentang perubahan tersebut,

**Comment by langonsari** [comment]
> taruh sini dulu belum nemu peraturan tentang perubahan tersebut,

Untuk Formulir Kependudukan terbaru itu sesuai dengan Permendagri 109 Tahun 2019 tentang Formulir dan Buku yang digunakan dalam Administrasi Kependudukan.
https://peraturan.bpk.go.id/Home/Details/138575/permendagri-no-109-tahun-2019
termasuk Formulir-formulir Kependudukan yang lainnya sudah mulai menyesuaikan dengan Permendagri 109 Tahun 2019

**Comment by muhtar-coder** [comment]
Mantap...👍🏻👍🏻👍🏻

**Comment by balongbesuk** [comment]
> > taruh sini dulu belum nemu peraturan tentang perubahan tersebut,
> 
> Untuk Formulir Kependudukan terbaru itu sesuai dengan Permendagri 109 Tahun 2019 tentang Formulir dan Buku yang digunakan dalam Administrasi Kependudukan. https://peraturan.bpk.go.id/Home/Details/138575/permendagri-no-109-tahun-2019 termasuk Formulir-formulir Kependudukan yang lainnya sudah mulai menyesuaikan dengan Permendagri 109 Tahun 2019

nah ini 

bikin heran sering banget blanko d rubah rubah

**Comment by andifahruddinakas** [comment]
Duplicate issue https://github.com/OpenSID/OpenSID/issues/4943

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1380
