### ISSUE TITLE
[Template Surat] Update Versi Terbaru Blanko Pindah Datang F.1.03

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#4226]
**Apa kekurangan yg ingin diatasi?**

Update Versi Blanko Pindah Datang F.1.03

**Jelaskan solusi yg diinginkan**

[FORMULIR PINDAH DATANG.pdf](https://github.com/OpenSID/OpenSID/files/6589033/FORMULIR.PINDAH.DATANG.pdf)

Blanko dari https://disdukcapil.purworejokab.go.id/formulir/:

[Formulir-f1-03.pdf](https://github.com/OpenSID/OpenSID/files/7660747/Formulir-f1-03.pdf)

**Apakah ada alternatif lain**

**Untuk versi OpenSID mana**

**Informasi tambahan**

**Comment by balongbesuk** [comment]
taruh sini dulu belum nemu peraturan tentang perubahan tersebut,

**Comment by eddieridwan** [comment]
Tugas ini telah dialokasikan kepada @scqolbu24

**Comment by agungsugiarto** [comment]
Pak @eddieridwan untuk blanko ini apakah membuat lampiran baru F.1.03 atau menyesuaikan dari lampiran f-1.08 ?

**Comment by eddieridwan** [comment]
Serupa tetapi tidak sama. F1.08 untuk warga yg pergi dari desa. F-1.03 untuk warga yg datang ke desa. Tetapi kalau ada bagian dari F1.08 yg bisa digunakan ulang boleh, asal hati2 saja melihat perbedaannya.

Tetapi perlu dicatat, kode F-1.08 tidak lagi digunakan untuk surat pindah keluar desa, karena sudah diganti dengan F-1.25, F-1.29, F-1.33, F-1.34, F-1.36 (sudah ada di OpenSID). F-1.08 versi lama masih ada di OpenSID, karena masih ada desa yg menggunakan, meskipun seharusnya sdh tidak berlaku lagi.

Lihat https://disdukcapil.purworejokab.go.id/formulir/ untuk daftar formulir Dukcapil yg berlaku, Saya lihat formulir pindah datang adalah F-1.23, sedangkan F-1.03 adalah Formulir Pendaftaran Perpindahan Penduduk.

Walaupun kelihatannya F-1.03 adalah forumulir yg masih berlaku, ada baiknya untuk konsultasi dengan yg meminta, dan juga para perangkat desa di grup Premium — mengenai alur penggunaannya.

Gunakan blanko dan petunjuk isian yg ada di https://disdukcapil.purworejokab.go.id/formulir/

**Comment by agungsugiarto** [comment]
Pak @balongbesuk, @eddieridwan apakah hasil lampiran f-1.03 ini sudah sesuai?

[surat_ket_pindah_penduduk_5201146510916995_2021-12-06_9_lampiran.pdf](https://github.com/OpenSID/OpenSID/files/7658381/surat_ket_pindah_penduduk_5201146510916995_2021-12-06_9_lampiran.pdf)

**Comment by scqolbu24** [comment]
Pak @balongbesuk, @eddieridwan bisa cek untuk lampiran ini juga f-1.03 apakah sudah sesuai
(https://github.com/OpenSID/OpenSID/files/7659748/surat_ket_pindah_penduduk_5201142210181724_2021-12-06_26_lampiran.pdf)

Lampiran ini sudah direvisi setelah ada review dari Pak @agungsugiarto

**Comment by balongbesuk** [comment]
format blankonya tidak sama ada kemungkinan bisa di tolak, 

bisa d coba d push saja ke desa desa premium yang sudah menerapkan pindah penduduk F.1.03

**Comment by scqolbu24** [comment]
pak @balongbesuk  bisa minta tolong dijelasakan secara detail perbedaannya dimana

**Comment by balongbesuk** [comment]
secara konsep isian sama secara format berbeda (berbeda di isian centang saja), makanya saya saran cb d push saja minta pengguna desa premium untuk mereview apakah d terima tidak d tingkat kecamatan / kabupaten,

**Comment by andifahruddinakas** [comment]
Sudah digabung ke fitur premium melalui PR https://github.com/OpenSID/premium/pull/506
