### ISSUE TITLE
[Pengguna] Tambah Reset Password Pengguna Melalui Email

### ISSUE THREAD

**Issue by opendesa2019** [OpenSID/OpenSID#4227]
**Apa kekurangan yg ingin diatasi?**
Mempermudah dalam mengatasi permasalahan lupa paswor bagi pengguna (admin, operator, redaksi, kontributor)

Penjelasan :

Banyak pengguna opensid belum tau cara mengatasi jika lupa paswor, walaupun sudah ditunjukkan cara mengatasi lupa paswor melalui panduan dengan cara masuk kedatabase, dan harus masuk dulu ke cpanel dulu (jika online).

tidak semua perangkat desa mengerti terkait database pada cpanel, dan mengelola cpanel.

apalagi jika server mereka di kominfo atau penyedia lain yang tidak tepat waktu dalam mengatasi masalah di server. Sehingga akan menghambat pengoperasian mereka di desa.
****

Cara atau solusi yang mudah dan lazim digunakan oleh aplikasi-aplikasi lain adalah reset pasword melalui email.

Reset melalui email merupakan solusi yang sederhana dan mudah digunakan oleh semua user/admin.

**Apakah ada alternatif lain**

**Untuk versi OpenSID mana**

**Informasi tambahan**

**Comment by afa28** [comment]
Tambahan : 
1. Dengan ditambahkannya fitur ini yang perlu dipastikan adalah, yang bertindak sebagai pengirim email reset password siapa??? apakah dari oepnsid atau email dari desa masing2 yg ada di config.
2. Pengguna /operator perlu lakukan verrifikasi email saat buat akun??? agar email yg di daftarkan valid???

**Comment by derit** [comment]
mas @eddieridwan fitur ini sedang saya kerjakan

**Comment by afa28** [comment]
> mas @eddieridwan fitur ini sedang saya kerjakan

Ok

**Comment by afa28** [comment]
Perlu ditambahkan : 
1. Pengaturan email pengirim reset password (host/pass/port) agar bisa disesuaikan oleh pengguna saat pertama kali install.
2. Penambahan user baru dengan ketentuan : email harus terisi dan tdk boleh sama.
3. Perlu dilakukan validasi email yg digunakan??? (apa perlu pak @opendesa2019). Jika ditambahkan mungkin akan menyusahkan saat buat user baru, jika tdk kita tdk tau apakah email tsb valid atau tdk.

**Comment by andifahruddinakas** [comment]
Sudah di fitur premium
