### ISSUE TITLE
[BUG] - Foto Default Pengguna Yang Login Tidak Tampil

### ISSUE THREAD

**Issue by afa28** [OpenSID/OpenSID#4234]
**Jelaskan error yg dialami**

**Cara untuk mereplikasi errornya**

Buat user tanpa megunggah fotonya, maka seharusnya yang ditampilkan adalah foto default/standar.

**Hasil yg diharapkan**

Foto default pengguna tampil

**Tampakan layar dan log error**

![11111](https://user-images.githubusercontent.com/57283157/121243589-11a56b00-c8c8-11eb-9154-7fd53266cd23.png)

**Versi OpenSID**

**Tema Yg Digunakan**

**Informasi tambahan**

**Comment by eddieridwan** [comment]
@afa28 saya periksa di `rilis-dev` dengan menambah penduduk lahir. Tidak bermasalah.

**Comment by eddieridwan** [comment]
Sdh dicommit ke `bug-fix` melalui https://github.com/OpenSID/premium/pull/255
