### ISSUE TITLE
Sederhanakan Script Penggunaan Peta Yang Berulang

### ISSUE THREAD

**Issue by afa28** [OpenSID/OpenSID#4236]
### Bagaimana alurnya sampai muncul masalah?
Cek modul yang menggunakan/menapilkan map, terjadi perulangan script yang sama.

### Seperti apa yang diharapkan?
Script dibuat sederhana

### Apa yang terjadi?
Lebih mudah diperbaiki jika ada kesalahan.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by Zoel-WB** [comment]
Kendala pada saat membuat peta wilayah dusun untuk wilayah desa yang melebihi dari 2 dusun :
1. Membuat Peta Dusun Pertama dan Dusun Kedua disini tidak terjadi kendela karena batas wilayah dusun masih dapat dibaca.
![image](https://user-images.githubusercontent.com/64481641/124627717-fcf9ca00-dea9-11eb-955e-ea3e93995143.png)
![image](https://user-images.githubusercontent.com/64481641/124627823-113dc700-deaa-11eb-936d-7372dfbb0c1b.png)

2. Baru ada kendala disaat akan membuat peta wilayah dusun ketiga dan seterusnya, pada saat menampilkan peta dusun satu dan dusun kedua, yg peta wilayah-nya telah dibuat sebelumnya, peta tidak tampilan dilayar, yang tampil hanya satu wilayah dusun yaitu dusun satu saja sedangkan dusun kedua tidak ditampilkan petanya, sehingga disini terjadi kesulitan dalam meletakkan awal batas posisi untuk membuat peta dusun yang ketiga....
![image](https://user-images.githubusercontent.com/64481641/124629153-5f9f9580-deab-11eb-987f-0806dfd53a49.png)

**Comment by Zoel-WB** [comment]
screensote ini di berputar.or.id  terjadi karena proses import peta dengan kml, koordinatnya tidak langsung bisa disimpan, sehingga perlu melakukan pembuatan poligon manual dengan mengikuti koordinat hasil impor kml, setelah disimpan koordinatnya lepas tidak terkorung dalam wilayah satu area dusun yg di import digambar ulang area-nya.
![image](https://user-images.githubusercontent.com/64481641/124630358-8b6f4b00-deac-11eb-8d2b-4a4c14a591e1.png)

**Comment by agungsugiarto** [comment]
Sudah dibungkan ke rilis bug-fix
