### ISSUE TITLE
[BUG] Tambah Data Pemudik Error

### ISSUE THREAD

**Issue by afa28** [OpenSID/OpenSID#4238]
**Jelaskan error yg dialami**

Error ketika tambah data pemudik

**Cara untuk mereplikasi errornya**

Buat data pemudik baru dengan asusmsi, pernah menambahkan data pemudik yg dimana sekarang datanya sudah tdk hidup lagi.

**Hasil yg diharapkan**

tidak error

**Tampakan layar dan log error**

**Versi OpenSID**

**Tema Yg Digunakan**

**Informasi tambahan**

**Comment by eddieridwan** [comment]
@afa28 , masalahnya kurang jelas. Mohon perjelas langkah dan contoh yg dimaksud, supaya PR https://github.com/OpenSID/premium/pull/258 bisa review.

**Comment by afa28** [comment]
> @afa28 , masalahnya kurang jelas. Mohon perjelas langkah dan contoh yg dimaksud, supaya PR [OpenSID/premium#258](https://github.com/OpenSID/premium/pull/258) bisa review.

Sebelumnya karena perubahan status penduduk yg menyebabkannya error. Tp sy cek ulang hari ini dengan langkah yg sama, sudah tidak ditemukan lagi. Akan sy buka ulang issue ini jika penyebab dari error tsb sudah jelas.
