### ISSUE TITLE
Permintaan Tambah Kolom Nama Pemilik  Persil di Daftar Persil

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#4239]
**Apa kekurangan yg ingin diatasi?**
 Penambahan Kolom Nama Pemilik Persil di Daftar Persil untuk memudahkan mengetahui siapa pemilik persil dan lokasi persil, saat ini sangat kesulitan mencari letak persil karena hanya ditandai dengan nomor persil saja, sehingga kesulitan untuk dingat nomor maupun letak persil.

**Jelaskan solusi yg diinginkan**

**Apakah ada alternatif lain**

**Untuk versi OpenSID mana**

**Informasi tambahan**

**Comment by eddieridwan** [comment]
@Zoel-WB mohon disimak lebih rinci penggunaan modul Pertanahan. Suatu persil bisa dimiliki oleh banyak pemilik (C-Desa) -- yaitu persil bisa dipecah dan bisa mengalami banyak mutasi (lihat rincian persil). Untuk kepemilikan suatu bidang tanah, lihat melalui C-Desa dan memeriksa persil di rincian C-Desa. 

@mizwaruddin -- mohon ada yg membuat panduan rinci penggunaan modul pertanahan. Supaya jelas bagi semua.

**Comment by Zoel-WB** [comment]
Oke Pak @eddieridwan
