### ISSUE TITLE
Pemanfaatan Peta Desa

### ISSUE THREAD

**Issue by bhien76** [OpenSID/OpenSID#424]
saya punya usulan. gimana kalau peta desa terkoneksi dengan data penduduk. jadi, pada halaman peta desa, pada saat mencari nama penduduk, langsung muncul marker lokasi penduduk. juga pada saat dicentang penduduk, keluarga, desa, wilayah administrasi, semua datanya bisa muncul. juga fungsi line, area, poligon bisa digunakan untuk mengedit peta wilayah desa. demikian usulan saya, terima kasih.
![merge](https://cloud.githubusercontent.com/assets/28255642/26022190/ab3b8908-37d0-11e7-9857-017935947987.jpg)

**Comment by eddieridwan** [comment]
Ada beberapa fitur yang diusulkan untuk dioperasionalkan pada halaman peta:

1. pada saat mencari nama penduduk, langsung muncul marker lokasi penduduk
1. pada saat centang penduduk semua lokasi penduduk muncul
1. pada saat centang keluarga semua lokasi keluarga muncul
1. pada saat centang desa, lokasi desa dan kantor desa muncul
1. pada saat centang wilayah administratif, semua wilayah administratif (dusun, rw, rt) muncul
1. pada saat centang area, semua area muncul
1. pada saat centang line, semua line muncul
1. pada saat centang point, semua point muncul

Masing-masing butir di atas sebaiknya dibuatkan issue tersendiri, karena sangat mungkin membutuhkan usaha lumayan untuk beroperasi dengan baik.

Issue ini akan dibatasi dulu untuk butir pertama di atas: 

1.  pada saat mencari nama penduduk, langsung muncul marker lokasi penduduk

**Comment by widodoari** [comment]
sedikit usulan, untuk fiturnya pencarian nama dan informasi lain.nya tetap di backend saja (akses administrator) jika ditampilkan di front end sebaiknya data agregat karena terkait privasi , pemanfaatan data spasial usulan diatas sangat menarik dengaan metode join database antara unsur spasial dengan informasi penduduk, banyak hal yg bisa di explorasi lebih lanjut, misal untuk menejemen aset desa , untuk kesehatan misal dapat memnunculkan gol darah, pemerataan pembangunan dengan inventarisasi infrastruktur disandingkan dengan data kemiskinan.

**Comment by eddieridwan** [comment]
Penampilan lokasi penduduk berfungsi ok. Yang perlu diperbaiki mungkin: (1) center diubah supaya menggunakan lokasi kantor desa (2) zoom diganti supaya semua marker lokasi penduduk tampil.

**Comment by eddieridwan** [comment]
Sudah dicommit ke master:

1. center diubah supaya menggunakan lokasi kantor desa 
2. zoom diganti supaya semua marker lokasi penduduk tampil.

**Comment by eddieridwan** [comment]
Telah dicommit ke master: Sekarang filter dan cari di peta akan otomatis memilih penduduk jika penduduk atau keluarga belum dicentang.

**Comment by eddieridwan** [comment]
@bhien76 @widodoari @siayi : saat ini tidak ada perbedaan antara mencentang Penduduk dengan mencentang Keluarga. Di SID 3.10 sama juga. 

Menurut teman2 bagaimana? Perbedaannya apa? Misalnya, apakah Keluarga menampilkan lokasi kepala keluarga saja? Walaupun sebenarnya, jika data diisi benar, seharusnya semua anggota dalam satu kartu keluarga tinggal di lokasi yang sama.

**Comment by siayi** [comment]
bung @eddieridwan kalo menurut saya untuk pilihan layer Penduduk yang ditampilkan data Individu (penduduk per jiwa) dan untuk layer Keluarga yang ditampilkan berdasarkan data nama Kepala Keluarga , karena ada kemungkinan individu tidak tinggal bersama dalam satu Rumah tangga.

**Comment by bhien76** [comment]
saya setuju dgn  bang @siayi bang @eddieridwan, untuk layer Penduduk yang ditampilkan data Individu (penduduk per jiwa) dan untuk layer Keluarga yang ditampilkan berdasarkan data nama Kepala Keluarga

**Comment by eddieridwan** [comment]
Sekarang, jika Keluarga dicentang, tampilkan lokasi kepala keluarga.
Sudah dicommit ke master.
