### ISSUE TITLE
Beberapa Temuan pada Fitur Lapak [BUG] 

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#4241]
**Jelaskan error yg dialami**

Saat akses menu Lapak, terjadi beberapa kendala sebagai berikut:
1. Saat tambah pelapak dan pilih nama panjang seperti "muhammad abizar rayhan ardhani" di web berputar akan gagal tersimpan.
2. Nomor Hp yang menggunakan awalan 62811xxx berubah menjadi +622811xxx (ada kelebihan angka 2).
3. Saat menghapus kategori, otomatis redirect ke halaman produk. Seharusnya tetap di halaman kategori.
4. Saat menghapus Pelapak (yang memiliki produk) akan sukses terhapus semua, harapannya tidak demikian tetapi gagal atau harus hapus isi produk dulu (menghindari salah klik yang mengakibatkan produk terhapus semua).
5. Begitu pula terjadi saat hapus Kategori, isi lapak otomatis hilang. harapannya seperti poin nomor 4.
6. Untuk halaman utama di website belum muncul lapak. baik menggunakan tema Natra maupun Klasik, walaupun "Tampilkan Lapak Web" sudah YA.
7. Potongan harga baru ada %, diharapkan ada diskon berupa besaran nominal rupiah.
8. View lokasi muncul tampilan dunia, jarak pandang tidak dekat dengan area lokasi.
9. Gambar dengan ukuran berbeda, jika diupload akan bergerak naik turun sesuai tinggi gambar. harapannya tinggi dapat diseragamkan.
10. Gambar tidak dapat diklik untuk lebih melihat detil gambar.

**Comment by eddieridwan** [comment]
Bung @afa28 , untuk (4) solusinya: Pelapak yg mempunyai produk tidak dapat dihapus.
Solusi (5): Kategori yg digunakan di produk tidak dapat dihapus.

**Comment by afa28** [comment]
Pak @ariandii , untuk yg sifatnya permintaan bisa dibuatkan issue baru.

**Comment by afa28** [comment]
> Bung @afa28 , untuk (4) solusinya: Pelapak yg mempunyai produk tidak dapat dihapus.
> Solusi (5): Kategori yg digunakan di produk tidak dapat dihapus.

Ini terjadi kr adanya relasi antar table.

Ok, sy tambahkan perubahan.

**Comment by afa28** [comment]
Point 1, seharusnya tdk berpengaruh krn yg diambil hanya id_pend. Sy coba cek ulang sesuai alur yg diberikan.

**Comment by afa28** [comment]
**Jelaskan error yg dialami**

Saat akses menu Lapak, terjadi beberapa kendala sebagai berikut:
- [ ] 1. Saat tambah pelapak dan pilih nama panjang seperti "muhammad abizar rayhan ardhani" di web berputar akan gagal tersimpan.
- [ ] 2. Nomor Hp yang menggunakan awalan 62811xxx berubah menjadi +622811xxx (ada kelebihan angka 2).
- [ ] 3. Saat menghapus kategori, otomatis redirect ke halaman produk. Seharusnya tetap di halaman kategori.
- [ ] 4. Saat menghapus Pelapak (yang memiliki produk) akan sukses terhapus semua, harapannya tidak demikian tetapi gagal atau harus hapus isi produk dulu (menghindari salah klik yang mengakibatkan produk terhapus semua).
- [ ] 5. Begitu pula terjadi saat hapus Kategori, isi lapak otomatis hilang. harapannya seperti poin nomor 4.
- [ ] 6. Untuk halaman utama di website belum muncul lapak. baik menggunakan tema Natra maupun Klasik, walaupun "Tampilkan Lapak Web" sudah YA.
- [ ] 7. Potongan harga baru ada %, diharapkan ada diskon berupa besaran nominal rupiah.
- [ ] 8. View lokasi muncul tampilan dunia, jarak pandang tidak dekat dengan area lokasi.
- [ ] 9. Gambar dengan ukuran berbeda, jika diupload akan bergerak naik turun sesuai tinggi gambar. harapannya tinggi dapat diseragamkan.
- [ ] 10. Gambar tidak dapat diklik untuk lebih melihat detil gambar.
- [ ]

**Comment by afa28** [comment]
Silahkan buat issue baru berupa permintaan untuk : 
- [ ] 7. Potongan harga baru ada %, diharapkan ada diskon berupa besaran nominal rupiah. **(Bisa buat issue baru berupa permintan fitur)**
- [ ] 9. Gambar dengan ukuran berbeda, jika diupload akan bergerak naik turun sesuai tinggi gambar. harapannya tinggi dapat diseragamkan. **( Kalau hanya view bisa di sesuaikan dengan menipulasi di css masing2 tema, tp kalau edit foto sebelum terupload bisa buat issue baru berupa permintan fitur)**
- [ ] 10. Gambar tidak dapat diklik untuk lebih melihat detil gambar.
