### ISSUE TITLE
[BUG] : View Status IDM yg Terlalu Besar (Tanya Jawab v21.06)

### ISSUE THREAD

**Issue by afa28** [OpenSID/OpenSID#4247]
**Jelaskan error yg dialami**

Font perlu diperkecil

**Cara untuk mereplikasi errornya**

**Hasil yg diharapkan**

**Tampakan layar dan log error**

![1111](https://user-images.githubusercontent.com/57283157/121783698-b682b980-cbe2-11eb-9f7d-d1dee36d6425.png)

**Versi OpenSID**

**Tema Yg Digunakan**

**Informasi tambahan**

**Comment by afa28** [comment]
Pak @Zoel-WB mohon dilengkapi.

**Comment by Zoel-WB** [comment]
![gambar](https://user-images.githubusercontent.com/64481641/121784281-563d4900-cbdd-11eb-8aa6-65d6544387f8.png)

**Comment by eddieridwan** [comment]
Sdh dicommit ke `bug-fix` melalui https://github.com/OpenSID/premium/pull/266
