### ISSUE TITLE
Foto Penduduk Sukses Upload Namun Tidak Tampil [BUG] 

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#4248]
**Jelaskan error yg dialami**

Saat upload foto penduduk, notifikasi tertulis berhasil di simpan, namun foto tidak tampil.
Begitupun dengan foto lama yang sebelumnya sudah ada (tampil), saat ini tiba-tiba tidak muncul.

Hal ini juga terjadi saat upload foto Aparatur Desa. dan yang sudah ada sebelumnya juga tidak tampil.

**Tampakan layar dan log error**

Proses tambah Foto.
<img width="494" alt="2021-06-13_04h16_26" src="https://user-images.githubusercontent.com/46939846/121789209-42eea580-cbfe-11eb-9e4f-bcc31a2dab54.png">

Keterangan berhasil, tapi foto tidak tampil.
<img width="575" alt="2021-06-13_04h16_36" src="https://user-images.githubusercontent.com/46939846/121789210-46822c80-cbfe-11eb-8e88-cc4cec6cb3dc.png">

**Comment by eddieridwan** [comment]
Sdh dicommit ke `bug-fix` melalui https://github.com/OpenSID/premium/pull/268
