### ISSUE TITLE
Tidak dapat menyimpan Pelapak [BUG] 

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#4249]
**Jelaskan error yg dialami**

Seperti kasus sebelumnya, saat menduga gagal input Data Pelapak dengan Nama Panjang, ternyata bukan karena hal tersebut.
Melainkan saat ini proses Tambah Data Pelapak tidak tersimpan jika ID Penduduk di atas 127.

**Hasil yg diharapkan**

Bisa input Pelapak jika penduduk yang sudah ribuan. yaitu ID penduduk di atas 127

**Comment by eddieridwan** [comment]
Sdh dicommit ke `rilis-dev` melalui https://github.com/OpenSID/premium/pull/267
