### ISSUE TITLE
Bug: edit lokasi data penduduk tidak tersipan

### ISSUE THREAD

**Issue by CIJERUK** [OpenSID/OpenSID#425]
memasukan data penduduk dan edit bio data penduduk tidak tersimpan ketika edit peta lokasi..

**Comment by eddieridwan** [comment]
Langkah:

1. buka form untuk mengubah biodata seorang penduduk
2. ubah kolom isian, misalnya _alamat sebelumnya_
3. klik tombol _Edit Lokasi_ dan klik _Simpan_ di dialog yang tampil

Perubahan yang dibuat di langkah (2) di atas akan hilang dan tidak tersimpan.

**Comment by eddieridwan** [comment]
Error ini agak sulit di atasi, karena memerlukan koordinasi antara dua form yang sebenarnya tidak terkait.

**Comment by MUHAMMADRANGSEL** [comment]
masalah ini sudah tidak terjadi shgg perlu di closed saja

**Comment by egodasa** [comment]
@eddieridwan Bagaimana dengan issue ini Mas? Saya cek di web demo perubahan lokasi penduduk berubah saat diedit. Dan form data penduduk serta form lokasi penduduk berbeda. Sehingga perubahan hanya dapat dilakukan pada salah satu form dalam satu kali proses. Atau form lokasi kita masukan langsung ke form biodata, sehingga tombol "edit lokasi" diganti dengan gambar peta lokasi penduduk?

**Comment by eddieridwan** [comment]
Iya. Karena pop-up dialog edit lokasi penduduk tidak betul-betul ajax (heheh... namanya saja..). Saat ini pemanggilan `penduduk_model->update_position($id)` dilakukan melalui controller `penduduk`. Kalau betul-betul ajax, seharusnya langsung dipanggil dari pop-up dialog itu.

Jadi kita perlu mempelajari cara memanggil `update_position()` secara ajax.

**Comment by eddieridwan** [comment]
@egodasa , mungkin bisa lihat contoh ini: http://makitweb.com/send-ajax-request-codeigniter/.
Apakah anda akan coba mengerjakan issue ini? Kalau iya, saya akan pindahkan ke kolom 'Sedang Dikerjakan' di https://github.com/OpenSID/OpenSID/projects/1.

**Comment by eddieridwan** [comment]
http://api.jquery.com/jquery.ajax/

**Comment by eddieridwan** [comment]
@egodasa sebagai contoh, saya telah kerjakan masalah serupa untuk _SID Home > Identitas Desa_. Di SID Home > Identitas Desa, sekarang peta lokasi Kantor Desa bisa diubah dan disimpan tanpa mempengaruhi perubahan data identitas desa. 

Sekarang `ajax_kantor_desa_maps.php` menggunakan ajax untuk mengupdate data lokasi kantor desa. Jangan lupa di controller, di method update, hilangkan redirect.

Sudah dicommit ke branch _master_.

**Comment by egodasa** [comment]
@eddieridwan Saya akan kerjakan Mas. Dan untuk edit wilayah desa, apakah juga akan diberlakukan seperti ini?

**Comment by eddieridwan** [comment]
Maksudnya edit Wilayah Desa di _SID Home > Identitas Desa_? Ya, perlu dikerjakan juga, karena masalahnya sama.

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR #1040.
