### ISSUE TITLE
[RTM] Penambahan No Rumah

### ISSUE THREAD

**Issue by eca0807** [OpenSID/OpenSID#4250]
**Apa kekurangan yg ingin diatasi?**
-- >Tidak ada No Rumah di Biodata Penduduk Dan tidak bisa pencarian penduduk berdasarkan Alamat
**Beri keterangan singkat dan jelas mengapa fitur ini diperlukan.**
--> masih banyak di pedesaan yang tinggal satu rumah tetapi mempunyai beberapa keluarga atau beberapa anggota keluarga dengan Kartu Keluarga terpisah.
Pencarian berdasarkan No Rumah untuk memudahkan mengetahui ada berapa Kepala Keluarga dan adaberapa Anggota keluarga ynag tinggal serumah di No rumah yang dicari
**Jelaskan solusi yg diinginkan**
!--  Penambahan No Rumah Di Biodata Penduduk dengan kolom tersendiri (Dashboard Admin)
     dan Pencarian data penduduk berdasarkan No Rumah (Dashboard Admin)

Beri keterangan singkat dan jelas mengenai fitur yg diinginkan.
Beri acuan peraturan yg mendasari fitur ini, kalau ada.
Lampirkan contoh laporan dan tampakan layar yg diinginkan. 
-->

**Apakah ada alternatif lain**

**Untuk versi OpenSID mana**

**Informasi tambahan**

**Comment by afa28** [comment]
> **Apa kekurangan yg ingin diatasi?**
> -- >Tidak ada No Rumah di Biodata Penduduk Dan tidak bisa pencarian penduduk berdasarkan Alamat
> **Beri keterangan singkat dan jelas mengapa fitur ini diperlukan.**
> --> masih banyak di pedesaan yang tinggal satu rumah tetapi mempunyai beberapa keluarga atau beberapa anggota keluarga dengan Kartu Keluarga terpisah.
> Pencarian berdasarkan No Rumah untuk memudahkan mengetahui ada berapa Kepala Keluarga dan adaberapa Anggota keluarga ynag tinggal serumah di No rumah yang dicari
> **Jelaskan solusi yg diinginkan**
> !-- Penambahan No Rumah Di Biodata Penduduk dengan kolom tersendiri (Dashboard Admin)
> dan Pencarian data penduduk berdasarkan No Rumah (Dashboard Admin)
> 
> Beri keterangan singkat dan jelas mengenai fitur yg diinginkan.
> Beri acuan peraturan yg mendasari fitur ini, kalau ada.
> Lampirkan contoh laporan dan tampakan layar yg diinginkan.
> -->
> 
> **Apakah ada alternatif lain**
> 
> **Untuk versi OpenSID mana**
> 
> **Informasi tambahan**

Untuk masalah ini bisa di kelompokan dengan menggunakan modul Rumah Tangga. Adapun dalam modul rumah tangga bisa di tambahkan anggota walau berbeda KK.

**Comment by eddieridwan** [comment]
Mengapa nomor rumah tidak dimasukkan sebagai penulisan alamat saja? Misalnya, `Jl Sudirman No. 43`. Mengapa harus field terpisah? Di pencarian spesifik bisa ditambahkan pencarian alamat yg bisa dibuat secanggih diinginkan. Sebaiknya tidak  ditambahkan di pencarian umum.

**Comment by eddieridwan** [comment]
Pencarian berdasarkan alamat sebaiknya dimasukkan ke `pencarian spesifik`. Jangan ditambahkan ke pencarian umum.

**Comment by andifahruddinakas** [comment]
Duplikasi issue https://github.com/OpenSID/OpenSID/issues/4679
