### ISSUE TITLE
Pemintaan Penambahan Fitur Sekretariat-->Inventaris-->Peralatan Elektronik

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#4252]
**Apa kekurangan yg ingin diatasi?**
Inventaris-->Peralatan Elektronik
Beri keterangan singkat dan jelas mengapa fitur ini diperlukan. 
--> Fitur ini penting untuk bisa mendata peralatan yg berhubungan dengan peralatan elektronik yg juga dimiliki oleh desa seperti Sound System, Desktop, Laptop, Printer, Kamera dan Alat-Alat Pesta.
Fitur yang sudah ada seperti PERALATAN dan MESIN tidak terwakili oleh detail keterangan peralatan dan type maupun jenis yang berbeda uraian.

**Jelaskan solusi yg diinginkan**

![image](https://user-images.githubusercontent.com/64481641/121839646-c5618d00-cd04-11eb-88a0-4b76c946a62b.png)

**Apakah ada alternatif lain**

**Untuk versi OpenSID mana**

**Informasi tambahan**

**Comment by ai-skematik** [comment]
usul saya tidak perlu ditambahkan kategori elektronik. tp fitur sekretariat > inventaris disesuaikan dengan permendagri 1 tahun 2016.

[Peraturan Mentri tentang pemerintah desa.pdf](https://github.com/OpenSID/OpenSID/files/6645950/Peraturan.Mentri.tentang.pemerintah.desa.pdf)

[Permendagri_ No.1 TH 2016_Lampiran_Pengelolaan Aset Desa.pdf](https://github.com/OpenSID/OpenSID/files/6645955/Permendagri_.No.1.TH.2016_Lampiran_Pengelolaan.Aset.Desa.pdf)

**Comment by ai-skematik** [comment]
di Permendagri 1/2016 dalam pencatatan  tidak dibedakan kategori inventaris.

**Comment by afa28** [comment]
Berdasarkan pembahasan di issue https://github.com/OpenSID/OpenSID/issues/3850, issue ini tdk sesuai dengan referensi yg ada.

Yg perlu ditambahkan yakni (belum ada):
1. Persediaan(golongan 1)
2. Aset tak berwujud (golongan 8)

Perlu penyesuaian kode barang, kode lokasi barang dan kode register.
