### ISSUE TITLE
Paginasi Lapak Error 404 [BUG] 

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#4254]
**Jelaskan error yg dialami**

Saat akses https://berputar.opensid.or.id/lapak dan mencoba next halaman berikutnya (produk lebih dari 10). akan error 404.

**Hasil yg diharapkan**

Normal seperti seharusnya.

**Informasi tambahan**

Link lapak jika berakhiran angka 1, 2 dan seterusnya akan muncul halaman normal jika ditambah kata first

https://berputar.opensid.or.id/first/lapak/2

namun, akan muncul kasus baru, jika link https://berputar.opensid.or.id/first/lapak/2 dijalankan, maka paginasi kembali error,
karena tidak ada kata first pada link paginasi.

**Comment by Zoel-WB** [comment]
![image](https://user-images.githubusercontent.com/64481641/122069204-31d0af00-ce1f-11eb-8dc4-8f11200a1bc1.png)

**Comment by eddieridwan** [comment]
Sdh dicommit ke `rilis-dev` melalui https://github.com/OpenSID/premium/pull/273
