### ISSUE TITLE
Logo Admin Tidak Muncul [BUG] 

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#4255]
**Jelaskan error yg dialami**

Saat login sebagai admin di web https://berputar.opensid.or.id

maka logo admin di pojok kanan atas tidak muncul.

<img width="258" alt="2021-06-15_21h18_50" src="https://user-images.githubusercontent.com/46939846/122069380-59277c00-ce1f-11eb-9e5f-a13c827e520a.png">

**Hasil yg diharapkan**

Normal seperti seharusnya

**Comment by Zoel-WB** [comment]
Iya foto user tidak ditampilkan, tempat saya juga sama.....

**Comment by ariandii** [comment]
@Zoel-WB namun jika admin dikasih foto (bukan foto default) maka akan muncul pak.

**Comment by afa28** [comment]
Ya, itu karena foto yg digunakan adalah "favicon.png" dimana kalau dicari sesuai dengan alur tempat penyimpanannya file tsb tdk ada.

Yg bermaslah dsni adalah karena menggunakan data awal yg masih menggunakan "favicon.png" yg harusnya "kuser".

Untuk masalah ini sudah diperbaiki.
