### ISSUE TITLE
Jumlah Pelapak Tidak Sesuai [BUG] 

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#4256]
**Jelaskan error yg dialami**

Saat beberapa pelapak di nonaktifkan, jumlah yang muncul di menu atas masih sejumlah seluruh pelapak.

<img width="537" alt="2021-06-15_21h21_17" src="https://user-images.githubusercontent.com/46939846/122070094-df43c280-ce1f-11eb-9664-a83c3384af9f.png">

**Hasil yg diharapkan**

Sesuai dengan jumlah pelapak aktif.

Hal ini juga terjadi pada menu produk seperti gambar di atas.

**Comment by afa28** [comment]
Pak @ariandii, artinya saat masuk produk data yg ditampilkan hanya produk aktif saja???

**Comment by ariandii** [comment]
atau pilihan lain yaitu pada informasi jumlah pelapak dan produk di menu atas dibagian bawah (small) bisa ditambah info jumlah yang aktif.

**Comment by afa28** [comment]
pak @eddieridwan, bgmna dengan ini. solusi mana yg sebaiknya diambil???

**Comment by ariandii** [comment]
atau dibuat tambahan pilihan pelapak aktif atau tidak, meminimalisir, ada yang pelapak sudah dibuat tapi masih Non Aktif yang tidak diketahui operator.

(info sedikit, title cursor pada icon gembok Pelapak tertulis "Non Aktifkan Produk".

**Comment by eddieridwan** [comment]
@afa28 :
1. Jika pelapak tidak aktif, semua produk untuk pelapak tsb juga menjadi tidak aktif. 
2. Halaman awal yg ditampilkan adalah data aktif sj.
3. Jumlah yg ditampilkan di 'dashboard' untuk produk dan pelapak seperti berikut: `14 aktif` (huruf besar) ` dari 15 total` (huruf kecil)
4. Perlu disediakan filter data aktif.

Kategori tidak perlu status.

**Comment by Zoel-WB** [comment]
1. Batas limit akun pelapak yg tidak aktif dalam waktu tertentu bila mungkin akan non-aktif dengan sendirinya (ada Timmer-nya).
2. Limit non aktif, mungkin  bahkan tidak pernah aktif lagi sebaik-nya ada notifikasi untuk mengeluarkan pelapak tersebut atau menghapus akun.....

**Comment by Zoel-WB** [comment]
Pada Tema Natra, mungkin ada pengaruh pada tampilan margin besar-kecil gambar produk yg di upload.....
![image](https://user-images.githubusercontent.com/64481641/122678244-2101ae00-d210-11eb-95f1-b894a2041fbc.png)
![image](https://user-images.githubusercontent.com/64481641/122678249-29f27f80-d210-11eb-942a-b69b0ed30b47.png)

**Comment by eddieridwan** [comment]
Sdh dicommit ke `rilis-dev` melalui https://github.com/OpenSID/premium/pull/285
