### ISSUE TITLE
Jumlah Produk Tiap Halaman Kurang 2 Item [BUG] 

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#4257]
**Jelaskan error yg dialami**

pada halaman lapak https://berputar.opensid.or.id/lapak

Saat produk lebih dari 10 item, maka akan beralih ke halaman ke-2.
Sesuai jumlah baris yang ada di halaman tersebut adalah 3 item per baris.
maka pada baris ke-4 akan kurang 2 items produk yg tampil.

yang seharusnya jika tiap baris berjumlah 3 item, maka perlu 12 produk yg tampil tiap halaman.

**Hasil yg diharapkan**

Adanya pengaturan jumlah tampil per baris pada halaman lapak.
Atau dibuat default 12 items per baris untuk 1 halaman.

**Comment by eddieridwan** [comment]
Sdh dicommit ke `rilis-dev` melalui https://github.com/OpenSID/premium/pull/273
