### ISSUE TITLE
[BUG] Filter Tahun Buku Inventaris dan Kekayaan Desa

### ISSUE THREAD

**Issue by afa28** [OpenSID/OpenSID#4258]
**Jelaskan error yg dialami**

Pilihan filter tahun pada Buku Inventaris dan Kekayaan Desa bermasalah, muncul terlalu banyak pilihan.

**Cara untuk mereplikasi errornya**

Langkah untuk mereplikasi error yg dialami :
1. Pergi ke halaman Buku Administrasi Desa
2. Pilih Buku Inventaris dan Kekayaan Desa
3. Klik filter tahun, maka akan muncul banyak pilihan.

**Hasil yg diharapkan**

**Tampakan layar dan log error**

**Versi OpenSID**

Pilihan tahun saat mau di filter muncul sebagai mana mestinya.

**Tema Yg Digunakan**

**Informasi tambahan**

**Comment by eddieridwan** [comment]
Sdh dicommit ke `big-fix` melalui https://github.com/OpenSID/premium/pull/271

@afa28 Perhatikan bahwa masalah ini sdh diperbaiki pada tgl 5 Juni di commit https://github.com/OpenSID/premium/commit/8277fa8fd57b0df29897874e08307d10f4d8e560. 

Tetapi kembali bermasalah setelah ditimpa pada tgl 7 Juni di commit https://github.com/OpenSID/premium/commit/ee492eb5c96e07d5d3afaf6afe916ed3e815f4fb
