### ISSUE TITLE
Peta Lokasi Pelapak Tidak Sesuai [BUG] 

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#4260]
**Jelaskan error yg dialami**

Saat klik salah satu pelapak, semua lokasi hanya tampil 1 pelapak yang sama (dengan id terakhir).

<img width="823" alt="2021-06-15_23h19_51" src="https://user-images.githubusercontent.com/46939846/122088849-5da86080-ce30-11eb-8c23-033aaa833ad8.png">

**Hasil yg diharapkan**

Lokasi sesuai dengan pelapak yang dilkik masing-masing.

**Comment by afa28** [comment]
Menunggu PR https://github.com/OpenSID/premium/pull/248 digabung. Agar tdk melakukan revisi berulang jika penanganan maps digabung.

**Comment by eddieridwan** [comment]
Sdh dicommit ke `rilis-dev` melalui https://github.com/OpenSID/premium/pull/283
