### ISSUE TITLE
[BUG] Map Blank

### ISSUE THREAD

**Issue by afa28** [OpenSID/OpenSID#4262]
**Jelaskan error yg dialami**

Ketika melakukan input data berupa lokasi wilayah (map area) terkadang tidak sengaja melakukan kesalahan pengimputan, bisa terjadi karena salah saat melakukan impor data wilayah atau lainnya. Hal ini menyebabkan terjadinya map yg kosong (blank). Dan sampai saat ini belum ada cara yg bisa dilakakun pada halaman admin untuk mengatasi hal tsb, cara manual yg bisa dilakukan sekarang adalah dengan menghapus data wilayah (field path) yg bermasalah tsb.

**Cara untuk mereplikasi errornya**

**Hasil yg diharapkan**

Sediakan tombol untuk menghapus/mereset map data wilayah yg bermasalah tsb.

**Tampakan layar dan log error**

![11111](https://user-images.githubusercontent.com/57283157/122218506-1a59fa80-cee1-11eb-9064-a1855b4d6f6c.png)

**Versi OpenSID**

**Tema Yg Digunakan**

**Informasi tambahan**

**Comment by eddieridwan** [comment]
Sdh dicommit ke `rilis-dev` melalui https://github.com/OpenSID/OpenSID/issues/4262
