### ISSUE TITLE
Anggota keluarga dalam satu keluarga yang tidak memiliki no kk tidak tampil berurutan di Buku Induk Penduduk [BUG] 

### ISSUE THREAD

**Issue by ai-skematik** [OpenSID/OpenSID#4263]
**Jelaskan error yg dialami**

Anggota keluarga tidak memiliki no kk tidak tampil berurutan di Buku Induk Penduduk 

**Cara untuk mereplikasi errornya**

input beberapa keluarga yang memiliki KK 0 (belum memiliki Nomor KK) maka urutannya di Buku Induk Penduduk Kepala2 Keluarga yang memiliki KK 0, selanjutnya istri-istri kepala kelluarga kk 0 lalu anak-anak kK 0. 

**Hasil yg diharapkan**

Keluarga yang KK 0 atau belum memiliki nomor kk tampil benar urutan anggota keluarganya seperti keluarga yang memiliki nomor kk., 
**Tampakan layar dan log error**

**Versi OpenSID**

21.06 Premium

**Tema Yg Digunakan**

**Informasi tambahan**

![kk](https://user-images.githubusercontent.com/48144047/122266253-31621200-cf0c-11eb-8967-95ea8e1dd717.png)

![kk2](https://user-images.githubusercontent.com/48144047/122265909-cadcf400-cf0b-11eb-8eed-fe70e76b17fd.png)

**Comment by afa28** [comment]
Artinya pengurutan berdasarkan no kk dan lvl kk???

**Comment by eddieridwan** [comment]
@afa28 , karena No KK 0 ada banyak, tidak bisa menggunakan pengelompokkan berdasarkan itu.
Yg bisa digunakan adalah `id_kk`. Jadi urut berdasarkan id_kk dan kk_level.

**Comment by afa28** [comment]
Yg bermalah jg dsni adalah pengurutan yg slalu sama walau sudah diganti2. Misal saya urutkan berdasarkan NIK scr AZ ketika mau sy kembalikan ke ZA pilihannya tetap AZ.

**Comment by eddieridwan** [comment]
Sdh dicommit ke `bug-fix` melalui https://github.com/OpenSID/premium/pull/288
