### ISSUE TITLE
jenis font/huruf naskah dinas

### ISSUE THREAD

**Issue by irull22** [OpenSID/OpenSID#4264]
**Apa kekurangan yg ingin diatasi?**

jenis huruf dalam surat/laporan default yang tersedia saat ini masih menggunakan font cambria(?)

**Jelaskan solusi yg diinginkan**

jenis font yang dipakai untuk naskah pengaturan/arahan adalah bookman old style..
untuk naskah dinas lain menggunakan font arial..

sesuai dengan ketentuan perka anri nomor 2 tahun 2014 sebagai pelaksanaan atas PP nomor 28 tahun 2018 tentang pelaksanaan UU nomor 43 tahun 2009 tentang kearsipan

**Comment by afa28** [comment]
Sediakan contoh gambar agar mudah dipahami dari issue yang dimaksud.

**Comment by eddieridwan** [comment]
@afa28 , untuk surat layanan, font saat ini ditentukan di template RTF masing2 surat. Ada ketergantungan teknis pada penggunaan LibreOffice, karena juga terbatas pada font yg didukung di O/S yg digunakan -- dan belum tentu konsisten dengan font yg ada di RTF yg dicetak. Solusi untuk surat RTF memerlukan penelitian dan ujicoba lebih lanjut:
(1) apakah ada cara di mana admin dapat memilih font yg digunakan melalui setting di OpenSID
(2) apakah keterbatasan font yg perlu diketahui supaya hasil cetak RTF dan PDF melalui LibreOffice terlihat konsisten

Kalau untuk lampiran dan laporan lain yg dihasilkan melalui html2pdf, sepertinya lebih sederhana. Pengaturan font bisa dilakukan melalui PHP/css dan bisa disediakan setting aplikasi untuk mengatur.

**Comment by eddieridwan** [comment]
@afa28 untuk langkah awal penerapan ini (kalau diprioritaskan) mungkin bisa batasi untuk lampiran dan laporan yg menggunakan html2pdf.

**Comment by irull22** [comment]
> Sediakan contoh gambar agar mudah dipahami dari issue yang dimaksud.

berikut screen shoot lampiran perka anri tersebut .. 
![Cuplikan layar 2021-06-19 181756](https://user-images.githubusercontent.com/42792824/122640692-1de0c200-d12b-11eb-80cc-f907b2591be7.png)

sehingga hasil dari kolom percetakan kurang lebih akan seperti berikut ..
![dasar-adm-desa-38-638](https://user-images.githubusercontent.com/42792824/122640722-3bae2700-d12b-11eb-842b-f13bab26638c.jpg)

**Comment by Zoel-WB** [comment]
Secara default memang dalam surat-surat dinas atau kontrak dengan type font huruf bookman old style, akan tetapi ada juga beberapa kasus untuk laporan table yg besar dan mencetak di kertas yg terbatas dengan default A4 banyak juga menggunakan type font arial narrow bahkan dengan arial narrow 9 tujuannya untuk lebih merapatkan huruf dan menghemat kolom...
