### ISSUE TITLE
Menu lapak belum muncul selain admin [BUG] 

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#4265]
**Jelaskan error yg dialami**

Saat ini ketika login selain hak akses  administrator, menu lapak tidak muncul.

**Hasil yg diharapkan**

Dapak lakukan input menu lapak di level operator, dll.

**Comment by afa28** [comment]
Tugas dari level operator sudah di buat statis tdk dapat di ubah.
![12](https://user-images.githubusercontent.com/57283157/122326108-554e4380-cf5e-11eb-94bf-342798ed6d0b.png)
![13](https://user-images.githubusercontent.com/57283157/122326116-57180700-cf5e-11eb-99ac-3180dfb9079e.png)

Solusi yg ditawarkan : 
1. Menambahkan tugas level operator untuk mengelola lapak (statis), jika ini yg diterapkan apakah pengguna lain setuju lvl operator, redaksi dan kotributor memiliki akses pada modul lapak???
2. Sediakan tombol ubah biar pada group agar bisa disesuaikan sendiri oleh pengguna.
3. Silahkan buat group baru untuk mengelola lapak dan menjangkau tugas operator jg.

**Comment by ariandii** [comment]
atau jika opsi ke 3 menjadi pilihan, apakah memungkinkan 1 user bisa memiliki 2 level? agar tidak login logout saat aktifitas kantor jalan sembari penginputan data lapak.

**Comment by afa28** [comment]
> atau jika opsi ke 3 menjadi pilihan, apakah memungkinkan 1 user bisa memiliki 2 level? agar tidak login logout saat aktifitas kantor jalan sembari penginputan data lapak.

Silahkan di sesuaikan dengan kebutuhan, misalnya membuat group pengguna 'Operator Desa' dengan hak askses sama dengan operator + modul lapak.

1 user hanya boleh memiliki 1 group pengguna, silahkan ganti dengan group pengguna yg dibuat td misalnya  'Operator Desa'  (tdk menggunakan group pengguna bawaan opensid / lvl operator, redaksi dan kotributor)

**Comment by eddieridwan** [comment]
Bung @afa28 @ariandii : operator seharusnya mempunyai hak akses baca/ubah pada semua menu; tanpa hak hapus. Redaksi dan kontributor hanya berkaitan dengan web, di mana kontributor mempunyai tupoksi yg terbatas mengisi materi artikel saja. Karena lapak terutama ditujukan untuk ditampilkan di web, sepertinya redaksi juga perlu diberikan hak akses ke lapak untuk baca/ubah.

Grup pengguna bawaan sistem di atas perlu selalu dipelihara supaya sesuai dengan tupoks masing2 grup sebagaimana telah didefinisikan.

Kalau tidak memenuhi kebutuhan desa, desa bebas membuat grup sendiri denga hak akses pilihan sendiri.

**Comment by afa28** [comment]
> Bung @afa28 @ariandii : operator seharusnya mempunyai hak akses baca/ubah pada semua menu; tanpa hak hapus. Redaksi dan kontributor hanya berkaitan dengan web, di mana kontributor mempunyai tupoksi yg terbatas mengisi materi artikel saja. Karena lapak terutama ditujukan untuk ditampilkan di web, sepertinya redaksi juga perlu diberikan hak akses ke lapak untuk baca/ubah.
> 
> Grup pengguna bawaan sistem di atas perlu dijaga supaya selalu sesuai dengan tupoksi masing2 grup sebagaimana telah didefinisikan.
> 
> Kalau tidak memenuhi kebutuhan desa, desa bebas membuat grup sendiri dengan hak akses pilihan sendiri.

yg di issue pak @ariandii bahas lvl operator dll.
untuk perubahan akses lvl operator perlu disesuaikan ulang berarti, karena ada beberapa modul baru yg tdk memiliki akses. tp untuk lvl redaksi perlu hak akses modul lapak???

selain itu bisa disesuaikan sendiri di grou pengguna.

**Comment by eddieridwan** [comment]
@afa28 , jadi setiap menambah menu perlu migrasi untuk menyesuaikan hak akses setiap grup bawaan sistem sesuai tupoksi.

**Comment by eddieridwan** [comment]
Sdh dicommit ke `rilis-dev` melalui https://github.com/OpenSID/premium/pull/281
