### ISSUE TITLE
Tentukan Default Halaman Login Layanan Mandiri [BUG] 

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#4266]
**Jelaskan error yg dialami**

Pada saat Login awal Layanan Mandiri menggunakan E-KTP `/layanan_mandiri/masuk_ektp`, diharapkan ketika klik Logout akan kembali ke halaman saat Login awal yaitu `/layanan_mandiri/masuk_ektp`.

Begitu pula jika warga Login awal menggunakan NIK dan PIN, diharapkan saat klik Logout juga kembali ke halaman login semula yaitu `/layanan_mandiri/masuk.

**Hasil yg diharapkan**
Agar pada Anjungan Layanan Mandiri, saat warga mencoba untuk Login pertama (pin default) menggunakan E-KTP, maka saat logout (setelah ganti pin) tidak perlu klik tombol "Masuk Menggunakan E-KTP".

Begitu pula saat warga yang selesai menggunakan Anjungan, saat klik logout akan kembali ke halaman `/layanan_mandiri/masuk`, padahal Anjungan Tersebut ingin tampilan defaultnya adalah `/layanan_mandiri/masuk_ektp`

**Comment by eddieridwan** [comment]
Sdh dicommit melalui https://github.com/OpenSID/premium/pull/277

**Comment by rudiansyahyunanda** [comment]
otomatis logout dengan rentang waktu tertentu dan kembali ke halaman login/screen saver anjungan (menghindari terjadinya lupa logout agar akun aktif tidak digunakan orang lain pada anjungan)
