### ISSUE TITLE
[BUG] Laporan Rekapitulasi Jumlah Penduduk ditemukan data dengan tanpa Wilayah

### ISSUE THREAD

**Issue by roaddee** [OpenSID/OpenSID#4267]
**Jelaskan error yg dialami**
Terdapat beberapa jumlah penduduk yang terlihat tanpa wilayah dalam laporan rekapitulasi jumlah penduduk

**Cara untuk mereplikasi errornya**
Langkah untuk mereplikasi error yg dialami, misalnya:
1. Klim Menu Buku Administrasi Desa
2. Klik tombol  Administrasi Penduduk
3. Klik Buku Rekapitulasi Jumlah Penduduk
4. Lihat error

**Hasil yg diharapkan**
Semua data jumlah penduduk terkait/terhubung dengan wilayah desa.

**Tampakan layar dan log error**
Tidak ada log error, hanya tampakan layar di bawah ini :

![image](https://user-images.githubusercontent.com/45786885/122536194-78f0b700-d04e-11eb-8b97-e36d7c76e792.png)

**Versi OpenSID**
Terjadi Pada Opensid PREMIUM v21.06-Premium-Bug-Fix

**Tema Yg Digunakan**
Tema Natra

**Comment by roaddee** [comment]
cc : bung @afa28

**Comment by eddieridwan** [comment]
Bung @afa28 @roaddee , saya coba replikasi di `rilis-dev` :
1. Pindah penduduk
2. Tampilkan rekap jumlah penduduk lagi

Tidak bermasalah. Penduduk yg pindah tercatat sebagai pindah sebagaimana semestinya.

Mungkin masalah ini karena hal lain di database pengguna yg menyebabkan. Mohon teliti lagi untuk mencari akar permasalahannya. Kalau tidak ketemu, kirim database tsb PM ke saya untuk dipelajari.

**Comment by eddieridwan** [comment]
@roaddee @afa28 saya sudah perbaiki databasenya.

**Comment by eddieridwan** [comment]
Ok, selain masalah tanggal 0000 dan collate yg tidak lengkap, terlihat ada entri di `tweb_keluarga` dgn `id_cluster` bernilai null. Seharusnya ini tidak diperbolehkan, karena `id_cluster` wajib diisi. Tapi terlihat penduduk anggota keluarga terkait mempunyai nilai `id_cluster` yg betul di `tweb_penduduk`. 

Jadi solusi untuk issue ini adalah:
1. tambahkan migrasi untuk mengubah `tweb_keluarga` supaya kolom `id_cluster` tidak boleh null.

Dan data dari desa ybs diperbaiki secara manual untuk memindahkan tweb_penduduk.id_cluster penduduk terkait ke tweb_keluarga.id_cluster masing2 keluarga.

**Comment by eddieridwan** [comment]
@roaddee @afa28 gunakan query berikut untuk memindahkan `tweb_penduduk.id_cluster` ke `tweb_keluarga.id_cluster` penduduk/keluarga yg bermasalah
```
update tweb_keluarga as k, 
(select t.* from 
   (select id, id_kk, id_cluster from tweb_penduduk where id_kk in 
     (select id from tweb_keluarga where id_cluster is null)
   ) t
) as p
set k.id_cluster = p.id_cluster
where k.id = p.id_kk
```

**Comment by eddieridwan** [comment]
Sdh dicommit ke `bug-fix` melalui https://github.com/OpenSID/premium/pull/279

**Comment by agungsugiarto** [comment]
Issue ini masih ditemukan di database mutih kulon, migrasi id_cluster masih belum berhasil mengubah yg null, alter table tidak berjalan menyebabkan error migrasi

**Comment by ai-skematik** [comment]
masih ditemukan jg didatabase tanjung sari setelah update ke 21.07 rilis-bug-fix

**Comment by eddieridwan** [comment]
> masih ditemukan jg didatabase tanjung sari setelah update ke 21.07 rilis-bug-fix

Kasus keluarga dan penduduk tidak berwilayah sepertinya sdh ada sebelumnya di database desa ybs, tetapi hanya muncul sekarang karena di rilis baru dibuat lebih ketat. Sangat mungkin penduduk tidak berwilayah itu masuk pada awalnya melalui proses impor dulu2 yg kurang ketat memeriksa keabsahan data. Bung @agungsugiarto @afa28 : saya usul solusinya cukup dengan menyediakan cara bagi desa untuk menampilkan data penduduk tanpa wilayah tersebut, supaya mereka bisa perbaiki sendiri. Dari kasus desa sebelumnya terlihat penduduk ybs sepertinya diisi coba2 pada awal menerapkan SID.

![wilayah-1](https://user-images.githubusercontent.com/249563/124346529-a890e900-dc22-11eb-8cd1-116ca40fd3c2.jpg)

**Comment by afa28** [comment]
Mungkin dengan tambahan tampilan warna merah pada wilayah kosong tsb agar menjadi perhatian.

**Comment by agungsugiarto** [comment]
Pak @roaddee, @ai-skematik, @eddieridwan dan mas @afa28 issue ini bisa ditutup karena sekarang penduduk tanpa wilayah sudah di strict tidak boleh kosong jika melakukan migrasi ke v21.07
