### ISSUE TITLE
Tidak Dapat Hapus Permohonan Surat berstatus Sedang Diperiksa [BUG] 

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#4269]
**Jelaskan error yg dialami**

Pada halaman https://www.desapasirpanjang.web.id/permohonan_surat_admin dengan Permohonan Surat Baru yang masih muncul icon tempat sampah, jika diklik tidak menghapus data tersebut.

**Hasil yg diharapkan**

Dapat dihapus saat icon tempat sampah muncul di sebelah tombol `sedang diperiksa`.

**Comment by afa28** [comment]
Apakah seharunya begitu???
1. Permohonan surat dari warga bisa dihapus oleh admin??? Jika iya, perlu dinformasikan kepada warga bersangkutan.
2. Mengganti tombol hapus menjadi ditolak/dibatalkan (sekarang sudah ada)
3. Yg bisa menghapus surat adalah warga yg mengajukan, selain itu admin hanya bisa menindak lanjuti surat tsb (tanpa menghapus)

**Comment by ariandii** [comment]
karena saat ini ada tombol tersebut. berikut gambarnya

<img width="415" alt="2021-06-18_22h06_11" src="https://user-images.githubusercontent.com/46939846/122581729-90956300-d081-11eb-8416-2fa68b3261d8.png">

Jika icon diklik, muncul Notifikasi. Hapus atau batal.

<img width="478" alt="2021-06-18_22h06_29" src="https://user-images.githubusercontent.com/46939846/122581804-a1de6f80-d081-11eb-9dde-b60263021433.png">

Saat diklik batal, data tetap ada.

**Comment by afa28** [comment]
> karena saat ini ada tombol tersebut. berikut gambarnya
> 
> <img alt="2021-06-18_22h06_11" width="415" src="https://user-images.githubusercontent.com/46939846/122581729-90956300-d081-11eb-8416-2fa68b3261d8.png">
> 
> Jika icon diklik, muncul Notifikasi. Hapus atau tutup.
> 
> <img alt="2021-06-18_22h06_29" width="478" src="https://user-images.githubusercontent.com/46939846/122581804-a1de6f80-d081-11eb-9dde-b60263021433.png">
> 
> Saat diklik Hapus, data tetap ada.

Ya, krn di pengkondisiannya yg bisa menghapus permohonan surat hanya warga yg memohon. Admin hanya bisa menindak lanjuti (baik itu dibatalkan krn tdk lengkap dan lainnya), tombol mungkin perlu dihilangkan.

**Comment by ariandii** [comment]
siap, bisa dihilangkah saja pak. agar tidak menjadi rancu atas keberadaan tombol tsb.

**Comment by afa28** [comment]
Pak @eddieridwan , apakah alur ini sudah benar???

**Comment by eddieridwan** [comment]
Sepertinya petugas desa perlu selalu memiliki fasilitas untuk membatalkan permohonan surat. Bisa karena terlihat permohonan itu tidak serius/coba-coba, berisi yg tidak senonoh, permohonan warga ybs tidak akan disetujui (misalnya minta SKCK -- tetapi diketahui warga tersebut tidak memenuhi syarat), dstnya. 

Alur yg disarankan, adalah:
1. Ubah tombol `hapus`, menjadi 'ditolak/dibatalkan'. 
2. Permohonan tersebut ditandai statusnya 'ditolak/dibatalkan', dan tidak dihapus dari tabel
3. Petugas harus mengisi alasan penolakan tersebut
4. Pemohon diberitahu melalui pesan bahwa permohonannya ditolak/dibatalkan, dan alasannya.

**Comment by afa28** [comment]
> @afa28 @ariandii
> Sepertinya petugas desa perlu selalu memiliki fasilitas untuk membatalkan permohonan surat. Bisa karena terlihat permohonan itu tidak serius/coba-coba, berisi yg tidak senonoh, permohonan warga ybs tidak akan disetujui (misalnya minta SKCK -- tetapi diketahui warga tersebut tidak memenuhi syarat), dstnya.
> 
> Alur yg disarankan, adalah:
> 
> 1. Ubah tombol `hapus`, menjadi 'ditolak/dibatalkan'.
> 2. Permohonan tersebut ditandai statusnya 'ditolak/dibatalkan', dan tidak dihapus dari tabel
> 3. Petugas harus mengisi alasan penolakan tersebut
> 4. Pemohon diberitahu melalui pesan bahwa permohonannya ditolak/dibatalkan, dan alasannya.

Ok, sy perbaiki alurnya seperti di atas.

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melaui PR: https://github.com/OpenSID/premium/pull/344
