### ISSUE TITLE
Hasil Export Surat dengan LibreOffice Pdf Library di Web Online OpenSID

### ISSUE THREAD

**Issue by happyagung25** [OpenSID/OpenSID#427]
saya sudah berhasil pasang library pdf untuk export surat menjadi pdf namun hasilnya seperti file attach dibawah ini.
semoga pada rilis berikut ini bisa diperbaiki.
Untuk sementara fitur ini akan saya matikan di web karna hasil belum sempurna

[surat_ket_pengantar_5201140706966997_2017-05-14_1234567890.pdf](https://github.com/eddieridwan/OpenSID/files/999626/surat_ket_pengantar_5201140706966997_2017-05-14_1234567890.pdf)

**Comment by sugiantoe** [comment]
wah mantap Om.. semoga berhasil sempurna :D
