### ISSUE TITLE
FITUR RAB / ANALISA PEKERJAAN

### ISSUE THREAD

**Issue by papopo2000** [OpenSID/OpenSID#4270]
Desa setiap tahun membutuhkan RAB/ANALISA bidang infrastruktur biasanya kalo perangkat desa tidak mempunyai SDM untuk pembuatan RAB/Analisa Pekerjaan, desa biasanya dibuatkan oleh dinas terkait seperti BMCK atau Konsultan, alangkah baiknya jika di Opensid ada yg membuatkan fitur tersebut 🙏🙏🙏

**Comment by eddieridwan** [comment]
@papopo2000 selalu lengkapi issue sesuai template yg disediakan. Seperti apa datanya? Alurnya seperti apa? Laporannya? Lampirkan regulasi terkait. Ingat, programmer bukan perangkat desa dan tidak mengerti kalau tidak dijelaskan rinci. Tanpa informasi yg rinci, permintaan anda tidak akan ada yg mengerjakan dan tidak bisa diprioritaskan.
