### ISSUE TITLE
Tidak tampil simbol pada nama dan deskripsi Lapak [BUG] 

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#4271]
**Jelaskan error yg dialami**

Saat menambah Produk di Menu Lapak, kolom Nama Produk coba diisi Run & Run, hasilnya menjadi Run amp Run.
Begitupula pada kolom Deskripsi Produk.
Saat ketik tanda - maka hasilnya hanya huruf, tidak tersimpan tanda - tersebut, dan ketik di kolom deskripsi menggunakan Enter (paragraf), hasilnya kalimat bersambung (tidak menjadi paragraf)

<img width="242" alt="2021-06-18_23h06_24" src="https://user-images.githubusercontent.com/46939846/122589598-a9564680-d08a-11eb-9294-199551e6bb8a.png">

**Hasil yg diharapkan**

1. Simbol dapat tampil sesuai input pada Nama Produk
2. Simbol tidak hilang dan bisa menampilkan paragraf pada Kategori Produk di halaman web Lapak.

**Comment by afa28** [comment]
> **Jelaskan error yg dialami**
> 
> Saat menambah Produk di Menu Lapak, kolom Nama Produk coba diisi Run & Run, hasilnya menjadi Run amp Run.
> Begitupula pada kolom Deskripsi Produk.
> Saat ketik tanda - maka hasilnya hanya huruf, tidak tersimpan tanda - tersebut, dan ketik di kolom deskripsi menggunakan Enter (paragraf), hasilnya kalimat bersambung (tidak menjadi paragraf)
> 
> <img alt="2021-06-18_23h06_24" width="242" src="https://user-images.githubusercontent.com/46939846/122589598-a9564680-d08a-11eb-9294-199551e6bb8a.png">
> 
> **Hasil yg diharapkan**
> 
> 1. Simbol dapat tampil sesuai input pada Nama Produk
> 2. Simbol tidak hilang dan bisa menampilkan paragraf pada Kategori Produk di halaman web Lapak.

input dibatasi hanya karakter angka dan spasi

**Comment by ariandii** [comment]
jika bisa menjadi solusi untuk hal tersebut, karena nama produk asli nya "Run & Run" tidak dapat tertulis dengan banar di halaman web maupun halaman admin lapak.

**Comment by Zoel-WB** [comment]
![image](https://user-images.githubusercontent.com/64481641/122642350-415c3a80-d134-11eb-971a-816d07b0cac6.png)
![image](https://user-images.githubusercontent.com/64481641/122642354-49b47580-d134-11eb-859d-116efbfa16b1.png)

**Comment by afa28** [comment]
Pak @eddieridwan, @ariandii, @Zoel-WB, inputan pada judul di validasi hanya menerima inputan berupa angka huruf dan spasi sja. Apa perlu ditambahkan kondisi lain??? Jika iya, mohon lampirkan apa sj yg mau ditambahkan agar permintaan mengenai hal ini tdk berulang.

**Comment by ariandii** [comment]
sebagaimana umum digunakan seperti.
()&_-":'=°%

**Comment by afa28** [comment]
Sudah digabung ke `bug-fix`
