### ISSUE TITLE
Tambahkan Link URL Lapak Desa saat kirim WA ke Penjual

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#4274]
**Apa kekurangan yg ingin diatasi?**

Saat ini saat pengunjung web klik link WA penjual suatu produk tertulis sebagai berikut:
Saya ingin membeli [nama_produk] yang anda tawarkan   

**Jelaskan solusi yg diinginkan**

Agar dapat diberikan paragraf baru (enter 2x) berupa link URL Lapak untuk mengetahui bahwa chat WA tersebut berasal dari Lapak Desa tersebut.

**Apakah ada alternatif lain**

Atau dapat diberikan kolom baru pada pengaturan lapak untuk input alamat web tertentu. namun secara default (jika kosong) adalah link web Lapak Desa tersebut.

**Untuk versi OpenSID mana**

Rilis Premium v21.07

**Informasi tambahan**

**Comment by afa28** [comment]
Agar tdk berulang, bisa di tambahkan shorcut apa sj yg perlu ditambahkan, misal : 
1. [nama_produk]
2. [link_web]
3. [dll]

Agar permintaan tdk berulang.

**Comment by afa28** [comment]
pak @ariandii bisa ditambahkan lg yg kurang, biar diperbaiki.

**Comment by ariandii** [comment]
menurut saya cukup 2 tsb pak

**Comment by eddieridwan** [comment]
Sdh dicommit ke `rilis-dev` melalui https://github.com/OpenSID/premium/pull/293.

@afa28 @ariandii perhatikan perubahan pesan hanya dilakukan untuk yg baru update ke versi yg ada lapak. Bagi tester yg sudah memasang, perlu mengubah sendiri di Lapak > Pengaturan. 

Bung @afa28 , di panduan perlu dijelaskan kode sisipan yg tersedia, yaitu [nama_produk] dan [link_web]. Bung @afa28 mungkin [link_web] diubah menjadi [link_lapak] supaya lebih jelas.

**Comment by balongbesuk** [comment]
https://kbbi.web.id/lapak

kenapa namanya lapak, 😄
