### ISSUE TITLE
Kolom Satuan Produk pada Menu Lapak Masih Kosong [BUG] 

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#4275]
**Jelaskan error yg dialami**

Saat ini secara default kolom Satuan Produk saat tambah Produk pertama kali masih kosong, sehingga memungkinkan operator desa tidak mengetahui bahwa ternyata bisa diketik sendiri untuk muncul otomatis kemudian.

**Hasil yg diharapkan**

Bisa ditambahkan secara default pada kolom Satuan Produk tersebut secara umum seperti pcs, buah, porsi, dll

**Comment by afa28** [comment]
Untuk masalah ini nanti ditambahkan ke pandua, namun jika mau di tambahkan satuan tsb bisa saja dengan ketentuan satuan yg sifatnya umum digunakan (jgn terlalu banyak)

**Comment by afa28** [comment]
Pak @ariandii bisa dilengkapi issue ini.

**Comment by ariandii** [comment]
Daftar satuan secara umum:
1. pcs
2. gram
3. kg
4. paket

**Comment by eddieridwan** [comment]
Sdh dicommit ke `rilis-dev` melalui https://github.com/OpenSID/premium/pull/290
