### ISSUE TITLE
Pelapak Hilang Saat Restore Database [BUG] 

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#4277]
**Jelaskan error yg dialami**

Ketika Backup Database lalu di restore ke database lain, Pelapak menjadi 0.

**Cara untuk mereplikasi errornya**

**Hasil yg diharapkan**

Saat lihat di sql hasil backup database, pelapak lengkap seperti seharusnya.
Namun menjadi 0 saat di restore.

**Comment by eddieridwan** [comment]
@afa28 , tabel baru yg berisi foreign key perlu ditambahkan di variabel `$ada_foreign_key` di `donjo-app/models/Export_model.php`.  Dijelaskan di https://github.com/OpenSID/OpenSID/wiki/Menambah-Migrasi-Database

**Comment by eddieridwan** [comment]
Sdh dicommit ke `rilis-dev` melalui https://github.com/OpenSID/premium/pull/289
