### ISSUE TITLE
Tombol Pilihan Kategori pada Halaman Pelapak Tidak Berfungsi [BUG] 

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#4278]
**Jelaskan error yg dialami**

Saat memilih sebuah Kategori pada Halaman Lapak -> Lapak, Tabel Pelapak tidak berubah sesuai kategori yang dipilih.

**Cara untuk mereplikasi errornya**

**Hasil yg diharapkan**

isi Tabel Pelapak sesuai dengan kategori yang dipilih.

**Tampakan layar dan log error**

<img width="960" alt="2021-06-22_13h49_26" src="https://user-images.githubusercontent.com/46939846/122877688-14d93600-d361-11eb-9b56-4d0386ba440f.png">

**Versi OpenSID**

https://berputar.opensid.or.id/lapak_admin/produk

**Informasi tambahan**

Sudah lakukan clear cache dan mencoba buka melalui Incognito, hasil tetap tidak berubah.

**Comment by eddieridwan** [comment]
Sdh dicommit ke `rilis-dev` melalui https://github.com/OpenSID/premium/pull/290
