### ISSUE TITLE
Tidak Bisa Hapus 1 Pelapak [BUG] 

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#4279]
**Jelaskan error yg dialami**

Saat ini, pada saat pelapak dicentang, lalu klik hapus data terpilih, maka data tersebut sukses dihapus.
Namun saat klik icon hapus per individu pelapak, Tombol Hapus tidak Berfungsi.

**Cara untuk mereplikasi errornya**
Langkah untuk mereplikasi error yg dialami, misalnya:
1. Pergi ke halaman 'Lapak' -> 'Pelapak'
2. Klik tombol 'icon Hapus' di 1 pelapak
3. Muncul popup, dan tersedia tombol 'Tutup' dan 'Hapus'
4. Saat klik Tombol Hapus, tidak ada aksi apapun.

**Hasil yg diharapkan**

Sukses hapus sebagaimana mestinya.

**Versi OpenSID**

https://berputar.opensid.or.id/lapak_admin/pelapak

**Informasi tambahan**

Sudah dicoba lakukan pada mode Incognito.

**Comment by afa28** [comment]
terjadi krn perpindahan dr cara penulisan di script php ke js saat menambah hak akses dan kesalahan penulisan.

**Comment by eddieridwan** [comment]
Sdh dicommit ke `rilis-dev` melalui https://github.com/OpenSID/premium/pull/292
