### ISSUE TITLE
Error 500 saat Hapus 1 Kategori [BUG] 

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#4280]
**Jelaskan error yg dialami**

Saat ini, pada saat Kategori pada Halaman Lapak dicentang, lalu klik hapus data terpilih, maka data tersebut sukses dihapus.
Namun saat klik icon hapus per kategori, Tombol Hapus tidak Berfungsi.

**Cara untuk mereplikasi errornya**
Langkah untuk mereplikasi error yg dialami, misalnya:
1. Pergi ke halaman 'Lapak' -> 'Kategori'
2. Klik tombol 'Hapus' pada 1 Kategori tertentu
3. Muncul Popup dan ada pilihan 'Tutup' dan 'hapus'
4. Saat klik Hapus, Halaman berubah menjadi Error 500
https://berputar.opensid.or.id/lapak_admin/kategori_delete/$%7Bdata.id%7D

**Hasil yg diharapkan**

Sukses hapus sebagaimana mestinya.

**Informasi tambahan**

Sudah dicoba lakukan pada mode Chrome Incognito

**Comment by afa28** [comment]
terjadi krn perpindahan dr cara penulisan di script php ke js saat menambah hak akses dan kesalahan penulisan.

**Comment by eddieridwan** [comment]
Sdh dicommit ke `rilis-dev` melalui https://github.com/OpenSID/premium/pull/292
