### ISSUE TITLE
Belum terpisah status Jumlah Produk pada Tabel Pelapak [BUG] 

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#4281]
**Jelaskan error yg dialami**
Pada saat membuka halaman Produk, ada item yang sedang tidak aktif pada suatu Pelapak,
Namun saat membuka halaman Pelapak, produk tersebut masih tercantum Jumlah keseluruhan Produk.

<img width="945" alt="2021-06-22_21h27_18" src="https://user-images.githubusercontent.com/46939846/122943622-5e497580-d3a1-11eb-9943-89b887a1e7a1.png">

<img width="960" alt="2021-06-22_21h26_44" src="https://user-images.githubusercontent.com/46939846/122943640-62759300-d3a1-11eb-8783-935ea209e7b4.png">

**Hasil yg diharapkan**
Dapat diketahui, jumlah produk dalam status aktif dan tidak aktif pada setiap Pelapak.

Hal ini juga dapat diterapkan pada Halaman Kategori untuk kolom Jumlah Produk.

**Comment by afa28** [comment]
Fungsi dari kolom JUMLAH PRODUK pada PELAPAK awalnya dibuat untuk mengetahui jumlah scr keseluruhan berdasarkan pelapak tsb. Dan ini jg digunakan sebagai indikator apakah pelapak tsb boleh dihapus atau tdk.

Adapun untuk melihat jumlah produk yg aktif di filter pada PRODUK berdasarkan PELAPAK, STATUS maupun KATEGORI.

Jika dilanjutkan maka tidak dipungkiri akan ada permintaan lanjutan untuk menampilkan jumlah produk (semua, aktif, tdk aktif) baik itu di PELAPAK maupun KATEGORI.
