### ISSUE TITLE
[Pengurus] Permohonan Tambahan Kolom NIK pada BUKU APARATUR DESA

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#4285]
**Apa kekurangan yg ingin diatasi?**
 
1. Kolom NIK pada buku aparatur desa untuk dapat menampilkan data NIK aparatur desa, hal ini diperlukan karena setiap ada permintaan data baik dinas maupun pemerintahan di atasnya selelalu ada permintaan data Nama, NIK dan Jabatan.
2.  Hal ini juga masih dimungkinkan dengan mengancu pada lampiran permendagri nomor 47/2016 pada kolom 13 atau Kolom Keterangan menjelaskan "Kolom 13 : Diisi dengan catatan-catatan lainnya yang anggap perlu" artinya masih dapat disesuaikan dengan kebutuhan yg dibutuhkah untuk laporan desa.
![image](https://user-images.githubusercontent.com/64481641/123199298-cf3f7900-d4d8-11eb-9046-50430ffbdf15.png)

**Jelaskan solusi yg diinginkan**

![image](https://user-images.githubusercontent.com/64481641/123199654-80deaa00-d4d9-11eb-9731-db384ed748f4.png)
[BUKU APARAT DESA.xlsx](https://github.com/OpenSID/OpenSID/files/6706088/BUKU.APARAT.DESA.xlsx)

**Apakah ada alternatif lain**

**Untuk versi OpenSID mana**

**Informasi tambahan**

**Comment by eddieridwan** [comment]
@Zoel-WB di petunjuk pengisian itu, yang boleh ditambahkan keterangan lain hanya `kolom 13`, yang memang kolom Keterangan. Tidak diartikan bisa menambah kolom lain.

**Comment by Zoel-WB** [comment]
Kalau tidak mungkin di tambah langsung pada Fitur Cetak laporan Buku Aparat Desa, apakah memungkinkan di tambahkan pada tabel file "Unduh" saja pak @eddieridwan
