### ISSUE TITLE
Statitis Kependudukan > Kepemilikan KTP > Belum Menggisi Datanya tidak ditampilkan [BUG] 

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#4287]
**Jelaskan error yg dialami**
 premium-2106-beta-4

**Cara untuk mereplikasi errornya**

**Hasil yg diharapkan**

**Tampakan layar dan log error**

**Versi OpenSID**

**Tema Yg Digunakan**

**Informasi tambahan**

**Comment by eddieridwan** [comment]
@Zoel-WB perhatikan saat ini bahwa jumlah total dan belum mengisi bukan untuk keseluruhan penduduk, tapi hanya pada penduduk yg wajib ktp. Kalau kebijakan pemerintah memberi KTP bagi anak/semua penduduk sudah operasional, penghitungan statistik kepemilikan KTP bisa diubah -- menjadi berdasarkan keseluruhan penduduk. Kalau itu yg diinginkan, harap lampirkan peraturan terkait.

**Comment by eddieridwan** [comment]
@Zoel-WB harap diperjelas persisnya di mana letak kesalahan yg anda alami. Lampirkan tampakan layar data yg diisi dan statistik yg bermasalah.

**Comment by Zoel-WB** [comment]
Iya pak,

Dapatkan Outlook untuk Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by Zoel-WB** [comment]
Maksudnya ada data yg BELUM MENGISI untuk KateGori KTP mungkin datanya ini berkait dengan "Identitas Elektronik" atau "Status Rekam" akan tetapi di jumlah yg BELUM MENGISI datanya tidak mau tampil saat di klik pada jumlah BELUM MENGISI sedangkan pada jumlah yg BELUM MENGISI ada jumkah data yg ditampilkan 4 data, 2 data berjenis kelamin laki-laki dan 2 data berjenis kelamin perempuan, akan tetapi waktu diklik pada jumlah data tersebut, data-nya tidak keluar.
![image](https://user-images.githubusercontent.com/64481641/123531830-02307980-d732-11eb-87fd-d5969b67cfdd.png)
![image](https://user-images.githubusercontent.com/64481641/123531842-1ffdde80-d732-11eb-8099-b5ca12bb8926.png)
![image](https://user-images.githubusercontent.com/64481641/123531873-67846a80-d732-11eb-92ae-874c053ae924.png)

SEDANGKAN UNTUK STATISTIK YANG LAIN TAMPIL DATANYA 
![image](https://user-images.githubusercontent.com/64481641/123531958-f8f3dc80-d732-11eb-9cf0-05fc5cfd7412.png)
![image](https://user-images.githubusercontent.com/64481641/123531969-1163f700-d733-11eb-8ddc-89ffae9e72d8.png)

**Comment by agungsugiarto** [comment]
Pak @Zoel-WB bisa kirim backup database bapak ke telegram saya ?

**Comment by Zoel-WB** [comment]
Sudah di PM di telegram pak..
Dapatkan Outlook untuk Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by eddieridwan** [comment]
Sdh dicommit ke `bug-fix` melalui https://github.com/OpenSID/premium/pull/317
