### ISSUE TITLE
Pilihan Area Persil Tidak Dapat Dipanggil dari Peta Area Yg Sudah ada Data Sebelumnya, dengan Nama Area yg berbeda dari Nama Pemilik C-Desa[BUG] 

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#4289]
**Jelaskan error yg dialami**
 OpenSID v21.06 Premium Beta-4

**Cara untuk mereplikasi errornya**

**Hasil yg diharapkan**

**Tampakan layar dan log error**

**Versi OpenSID**

**Tema Yg Digunakan**

**Informasi tambahan**

**Comment by Zoel-WB** [comment]
Informasi Tambahan Berkaitan dengan masalah Nama Pemilik  C-Desa tertentu ada yang bisa dipanggil Area yg sudah ada, dan ada yg tidak bisa dipanggil area-nya, ini mungkin juga ada ada kaitannya dengan huruf tertentu pada penulisan nama pemilik c-desa dan link ke Peta Area yg sudah ada.

**Comment by afa28** [comment]
Pak @Zoel-WB, mohon diperjelas issue yg dimaksudkan. Kalau perlu sediakan tangkapan layar agar memudahkan programer untuk memperbaiki issue tsb.

**Comment by Zoel-WB** [comment]
> Pak @Zoel-WB, mohon diperjelas issue yg dimaksudkan. Kalau perlu sediakan tangkapan layar agar memudahkan programer untuk memperbaiki issue tsb.

Ada Nama Pemilik C-Desa, yang tertentu saja, saat membuat Persil, tidak dapat memanggil Area yg sudah ada di peta area sebelumnya, database backup sudah saya kirimkan ke Pak Andi di telegram....

**Comment by Zoel-WB** [comment]
Sudah ketemu penyebab kenapa Area tidak dapat dipanggil, karena pengaruh pada Filter Cari Data/Nama C-Desa di Daftar C-Desa
![image](https://user-images.githubusercontent.com/64481641/123743420-6e001700-d8d7-11eb-8039-5b2fbdae0078.png)

Sehingga nama di yg difiter dalam Daftar C-Desa, Ikut juga Terfilter ke pencarian data Peta Area lokasi Persil sehingga kode area persil tidak bisa dipanggil dengan nama area yg lain selaian Nama Pemilik C-Desa yg filter :
![image](https://user-images.githubusercontent.com/64481641/123743747-dfd86080-d8d7-11eb-8cd5-016bd3c65cc9.png)

**Comment by agungsugiarto** [comment]
Sudah digabungkan ke `bug-fix`
