### ISSUE TITLE
Fatal error di backup seluruh data

### ISSUE THREAD

**Issue by batudaa** [OpenSID/OpenSID#429]
```
Fatal error:  Allowed memory size of 134217728 bytes exhausted
```
Pada saat klik tombol **Download** untuk Backup Seluruh Data SID.

**Comment by eddieridwan** [comment]
Jumlah data berapa?

**Comment by batudaa** [comment]
Data? Gak hitung, proses backupnya kan memproses semua tabel.

**Comment by eddieridwan** [comment]
Issue ini kami tutup. Kalau masih bermasalah, silakan buka lagi dengan menampilkan data yg bermasalah.
