### ISSUE TITLE
[SMS] Permintaan Menampilkan  Nik, Dusun, RT/RW Pada Nama Kontak di Fitur SMS>Daftar Kontak>Tambah Kontak

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#4291]
**Apa kekurangan yg ingin diatasi?**
 Menambah NIK atau alamat RT/RW maupun dusun untuk memudahkan memanggil nama kontak yang benar terhadap Nama Kontak yang memiliki beberapa kontak dengan nama yang sama.
![image](https://user-images.githubusercontent.com/64481641/123544880-a096fc00-d77f-11eb-8e38-b82d430f4148.png)

![image](https://user-images.githubusercontent.com/64481641/123544916-ccb27d00-d77f-11eb-8d51-1044dd580ec1.png)

**Jelaskan solusi yg diinginkan**

**Apakah ada alternatif lain**

**Untuk versi OpenSID mana**

**Informasi tambahan**

**Comment by agungsugiarto** [comment]
Mas @andifahruddinakas permintaan fitur ini apa masih relevan?

**Comment by andifahruddinakas** [comment]
> Mas @andifahruddinakas permintaan fitur ini apa masih relevan?

Tidak

**Comment by andifahruddinakas** [comment]
Pak @Zoel-WB, silahkan buat issue baru berdasarkan perubahan di v22.05-premium.

**Comment by Zoel-WB** [comment]
Oke pak, sepertinya fitur sudah berubah..
