### ISSUE TITLE
[Template Surat] Penambahan Surat dengan Formulir Permohonan KTP kode (F-1.21)

### ISSUE THREAD

**Issue by TAHTA24** [OpenSID/OpenSID#4292]
**Apa kekurangan yg ingin diatasi?**

**Jelaskan solusi yg diinginkan**

**Apakah ada alternatif lain**

**Untuk versi OpenSID mana**

**Informasi tambahan**
 #<!-
Beri informasi lainnya yg dapat membantu menjelaskan permintaan ini.
-->

**Comment by afa28** [comment]
Mohon issue diperjelas dan mungkin bisa disediakan contoh jika diperlukan.

**Comment by ai-skematik** [comment]
@afa28  sepertinya maksud issue ini permintahan penambahan form permohonan ktp.

**Comment by ai-skematik** [comment]
@TAHTA24  kalau F2.01 sudah ada di OpenSID., cari surat keterangan kelahiran., surat tersebut mempunyai lampiran F2.01.,

**Comment by ai-skematik** [comment]
hanya f1-21 sudah sejak diminta hanya berdasarkan permendagri 8 2016 permohonan ktp tidak membutuhkan lagi formulir tersebut sehingga tidak pernah dimasukkan dalam OpenSID untuk f1.21.,

**Comment by ai-skematik** [comment]
@TAHTA24  tp ini bisa dicoba https://drive.google.com/file/d/1Q2b4wQeygO7IkMobD5ritesCMlpL7si7/view
