### ISSUE TITLE
Tidak Dapat Menghapus Data Persil Dengan Tombol Hapus Pada Daftar Persil [BUG] 

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#4293]
**Jelaskan error yg dialami**
 OpenSID 21.06 Primium Beta-4

**Cara untuk mereplikasi errornya**

**Hasil yg diharapkan**

**Tampakan layar dan log error**

**Versi OpenSID**

**Tema Yg Digunakan**

**Informasi tambahan**

**Comment by afa28** [comment]
Apa yang di maksud ini pak @Zoel-WB ???

![11111](https://user-images.githubusercontent.com/57283157/123551926-7d337780-d7a6-11eb-920e-7d66bc56391b.png)

**Comment by Zoel-WB** [comment]
Persilnya tidak bisa dihapus, pada hal ada persil masih belum jadi...

**Comment by afa28** [comment]
> Persilnya tidak bisa dihapus, pada hal persil masih belum jadi...
> Seperti Persil atas Nama Yusri ini, karena tidak bisa memanggil area-nya rencana mau hapus untuk Input Ulang...
> 
> ![image](https://user-images.githubusercontent.com/64481641/123572322-3a998b80-d7f6-11eb-96fa-618b9b9f0a56.png)
> 
> Ternyata tombol hapus-nya tidak aktif
> 
> ![image](https://user-images.githubusercontent.com/64481641/123572345-45542080-d7f6-11eb-8201-0833206e25df.png)
> 
> ![image](https://user-images.githubusercontent.com/64481641/123572485-81878100-d7f6-11eb-892b-4ec0fc3f94c3.png)
> 

Data masih ada, jd harus di kosongkan terlebih dahulu.

**Comment by Zoel-WB** [comment]
Issue ini sepertinya sudah terjawab, saya tutup nanti bila ada temuan lagi di kembali ke open lagi.....
