### ISSUE TITLE
Tidak dapat menampilkan data maupun pencarian data Pemilik C-Desa Warga Luar Desa [BUG] 

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#4294]
**Jelaskan error yg dialami**
 OpenSID Premium V21.06 Beta-4

**Cara untuk mereplikasi errornya**

**Hasil yg diharapkan**

**Tampakan layar dan log error**

**Versi OpenSID**

**Tema Yg Digunakan**

**Informasi tambahan**

**Comment by afa28** [comment]
Untuk selanjutnya mungkin issue diperjelas lagi, agar memudahkan programmer untuk memperbaiki issue tsb.

**Comment by eddieridwan** [comment]
Sdh dicommit ke `bug-fix` melalui https://github.com/OpenSID/premium/pull/300

**Comment by Zoel-WB** [comment]
> Untuk selanjutnya mungkin issue diperjelas lagi, agar memudahkan programmer untuk memperbaiki issue tsb.

Cuma saat diketik di kolom pencarian data, KLIK cair/find--> data nya tak bisa dipanggil atau tidak tampil, barangkali ada hubungan dengan tidak ada NIK-nya untuk Pemilik C-Desa Warga Luar Desa
![image](https://user-images.githubusercontent.com/64481641/123570706-feb0f700-d7f2-11eb-8143-a2559044eda6.png)

**Comment by eddieridwan** [comment]
@Zoel-WB seperti terlihat di comment di atas, masalah ini sudah diperbaiki. Harap periksa lagi di https://berputar.opensid.or.id.

**Comment by Zoel-WB** [comment]
> @Zoel-WB seperti terlihat di comment di atas, masalah ini sudah diperbaiki. Harap periksa lagi di https://berputar.opensid.or.id.

Oke Pak, Makasih....
