### ISSUE TITLE
[BUG] userpass benar tapi tidak menampilkan hom_sid 

### ISSUE THREAD

**Issue by OkkySuryaLesmana** [OpenSID/OpenSID#4297]
username dan password benar tapi tidak menampilkan pesan error atau kadang di redirect ke halaman depan web...
di cek error log Session: Unable to write data.

**Comment by afa28** [comment]
Silahkan lakukan testing dan duplikasi error di berputar.opendesa.or.id, dan setelah sy cek pada web tsb normal2 sja. Mungkin ini masalah yang ada di sistem anda. Silahkan bertanya ke Group FB OpenSID https://www.facebook.com/groups/OpenSID atau silahkan hubungi layanan tempat anda mengonlinekan SID anda.

https://serverfault.com/questions/808669/failed-to-write-session-data-files

Issue ini sy tutup.
