### ISSUE TITLE
Laporan Penduduk Bulanan

### ISSUE THREAD

**Issue by afri18** [OpenSID/OpenSID#4298]
### Bagaimana alurnya sampai muncul masalah?
1. Saat memasukan data kelahiran juga tercatat di kelahiran / Keluarga Baru
2. Saat input Kepala Keluarga Pendatang Tercatat di Kelahiran/Keluarga Baru

### Seperti apa yang diharapkan?
1. Seharusnya saat ada kelahiran baru tidak tercatat di Keluarga Baru
2. Saat input kepala keluarga Pendatang tercatat di Kelahiran Keluarga Baru, harusnya di Keluarga Datang

### Apa yang terjadi?
1. Terjadi kesalahan hitung antara Kelahiran Keluarga Baru
2. Terjadi kesalahan saat penjumlahan Keluarga Datang
![image](https://user-images.githubusercontent.com/6611881/123731148-ccba9600-d8c1-11eb-90a5-b5be436cd070.png)

### Informasi tambahan 
Hanya pengguna GRATISAN jadi kalau di PREMIUM tidak dijumpai 
MOHON ABAIKAN

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 21.06
| Versi PHP        | 7
| System operasi   | Cpanel

**Comment by afri18** [comment]
di 21.07 masih terjadi salah untuk laporan bulanan
![image](https://user-images.githubusercontent.com/6611881/124533332-55927e00-de3c-11eb-8f97-91c4ce1be604.png)

**Comment by agungsugiarto** [comment]
Pak @afri18 bisa kirim backup database bapak ke telegram saya https://t.me/meagungsugiarto

**Comment by afa28** [comment]
Pak @eddieridwan

**Comment by eddieridwan** [comment]
@afri18 seperti terlihat di https://github.com/OpenSID/OpenSID/wiki/Rilis-Umum-Yang-Akan-Datang, laporan Statistik > Laporan Bulanan diperbaiki secara bertahap di rilis2 yad, termasuk:

- v21.09
- v21.10
- v21.11
- v21.12
- v22.01
- v22.02

Dengan demikian, tidak layak untuk diperbaiki di v21.08, karena terkait dengan perombakan besar2an yg dilakukan untuk Buku Mutasi Penduduk.

Kami sarankan, jalur terbaik adalah berlangganan Premium, sehingga akan mendapatkan rilis di mana v21.09-premium sudah berisi semua perbaikan tersebut.

**Comment by eddieridwan** [comment]
@afa28 issue ini ditutup saja, karena tidak layak diperbaiki di v21.08.

**Comment by afri18** [comment]
berlangganan premium dengan memakai APBDes sudah dijelaskan tidak semudah memakai dana pribadi, sementara Komunitas tidak memberikan kepercayaan terhadap saya sebagai perwakilan di Kab. Purwakarta yang hanya satu desa di Kabupaten Purwakarta. 
mohon untuk fitur yg tadinya sudah ada jangan dihilangkan hanya karna pengguna gratis.
artinya untuk bulan ini dan kedepanya saya tidak bisa melapor data penduduk,
mohon pengurus Komunitas mempertimbangkan
TERIMA KASIH

**Comment by ai-skematik** [comment]
fitur tersebut tidak hilang di versi sebelumnya., silahkan dikembalikan lagi ke versi sebelumnya.
