### ISSUE TITLE
Perlu Ditambahkan Kolom Input Kepemilikan ID BDT di Menu Keluarga

### ISSUE THREAD

**Issue by muhtar-coder** [OpenSID/OpenSID#4299]
**Apa kekurangan yg ingin diatasi?**

Berdasarkan Peraturan Menteri Sosial Republik Indonesia No.28 Tahun 2017 Tentang Pedoman Umum Verifikasi dan Validasi Data Terpadu Penanganan Fakir Miskin dan Orang Tidak Mampu,

Maka perlu di sediakan kolom tabel untuk meng input Nomor ID BDT di Menu Keluarga pada aplikasi OpenSID guna Melengkapi data,memudahkan pembuatan surat SKTM dan kebutuhan desa lain nya yg sesuai dengan peraturan yg berlaku.

![image](https://user-images.githubusercontent.com/55665526/123812227-1cc74600-d91e-11eb-80fc-d333e344afbf.png)

**Jelaskan solusi yg diinginkan**

1. KOLOM INPUT DI MENU KELUARGA
![image](https://user-images.githubusercontent.com/55665526/123812976-babb1080-d91e-11eb-805f-e1d29df8545e.png)

2. STATISTIK PESERTA ID BDT KEMENSOS
![image](https://user-images.githubusercontent.com/55665526/123814016-8d229700-d91f-11eb-98b7-82c6dc9a6038.png)

**Apakah ada alternatif lain**

**Untuk versi OpenSID mana**

Opensid V.21.08 Premium

**Informasi tambahan**

Menyesuaikan kebutuhan desa dalam tugas pelaksanaan pelayanan,pelaporan dan konsolidasi ke dinas terkait

**Comment by mizwaruddin** [comment]
Sya lbh condong ID BDT disematkan di data penduduk. Mengapa? Krn ada warga yg sdh membentuk KK baru, namun ID BDT masih terdaftar di KK lama.

**Comment by muhtar-coder** [comment]
Secara teknis dan aturan nomor ID BDT hanya di peruntukan kepada rumah
tangga dalam satu KK,artinya ketika ada anggota keluarga yg  pecah/pisah KK
maka merupakan keluarga baru dengan KK baru yg notabene nya rumah tangga
baru dan belum terdaftar di siks-ng.

Pada kasus ini operator siks-ng harus melakukan perubahan di rumah tangga
tsb...dan apabila setelah verval pada keluarga baru masuk kategori tidak
mampu,maka harus di masukan ke BDT DTKS agar memiliki ID baru dan di upload
di kemensos.

Pada tanggal Rab, 30 Jun 2021 00.57, Mizwaruddin ***@***.***>
menulis:

**Comment by muhtar-coder** [comment]
Secara teknis dan aturan nomor ID BDT hanya di peruntukan kepada rumah
tangga dalam satu KK,artinya ketika ada anggota keluarga yg  pecah/pisah KK
maka merupakan keluarga baru dengan KK baru yg notabene nya rumah tangga
baru dan belum terdaftar di siks-ng.

Pada kasus ini operator siks-ng harus melakukan perubahan di rumah tangga
tsb...dan apabila setelah verval pada keluarga baru masuk kategori tidak
mampu,maka harus di masukan ke BDT DTKS agar memiliki ID baru dan di upload
di kemensos.

Pada tanggal Rab, 30 Jun 2021 08.40, utay doang ***@***.***>
menulis:

**Comment by mizwaruddin** [comment]
Bisa dilampirkan peraturan terkait teknis tsb? Yg ada saat ini, meski beda KK tp masih dlm satu rumah tangga maka IDBDT tetap sama.

**Comment by afa28** [comment]
pak @mizwaruddin, @muhtar-coder ada tambahan lain untuk issue ini???

**Comment by muhtar-coder** [comment]
> Sya lbh condong ID BDT disematkan di data penduduk. Mengapa? Krn ada warga yg sdh membentuk KK baru, namun ID BDT masih terdaftar di KK lama.

Sekarang lagi gencar perbaikan data DTKS bilamana data tidak seharusnya artinya hal tsb merupakan tanggung jawab pihak desa

**Comment by mizwaruddin** [comment]
Apakah setiap pengajuan perubahan bisa langsung diproses, pagi diubah sore langsung berubah? Perlu waktu beberapa bulan utk pengajuan perubahan ID BTD.

**Comment by muhtar-coder** [comment]
Per enam bulan jadwalnya

Pada tanggal Kam, 15 Jul 2021 08.36, Mizwaruddin ***@***.***>
menulis:

**Comment by eddieridwan** [comment]
Berdasarkan Buku Panduan SIKS-NG, ID BDT diberikan pada Rumah Tangga bukan Keluarga (dalam arti Kartu Keluarga Dukcapil). Ini dapat dimengerti karena BDT dan Rumah Tangga adalah konsep rumusan Kemsos, bukan Dukcapil. Karena itu, kolom ID BDT perlu ditambahkan ke tabel `tweb_rtm` bukan `tweb_keluarga`. `tweb_keluarga` adalah penduduk yg tergabung dalam kartu keluarga kelolaan Dukcapil. 

Dan desa harus rajin memastikan semua penduduk yg terkait sudah dimasukkan ke rumah tangga yg benar. Jika diperlukan fitur untuk memudahkan menambahkan penduduk ke rumah tangga, silakan buat issue terpisah.

[15699415174963.pdf](https://github.com/OpenSID/OpenSID/files/6872022/15699415174963.pdf)

cc @afa28 @agungsugiarto

**Comment by muhtar-coder** [comment]
> Berdasarkan Buku Panduan SIKS-NG, ID BDT diberikan pada Rumah Tangga bukan Keluarga (dalam arti Kartu Keluarga Dukcapil). Ini dapat dimengerti karena BDT dan Rumah Tangga adalah konsep rumusan Kemsos, bukan Dukcapil. Karena itu, kolom ID BDT perlu ditambahkan ke tabel `tweb_rtm` bukan `tweb_keluarga`. `tweb_keluarga` adalah penduduk yg tergabung dalam kartu keluarga kelolaan Dukcapil.
> 
> Jadi desa harus rajin memastikan semua penduduk yg terkait sudah dimasukkan ke rumah tangga yg benar. Jika diperlukan fitur untuk memudahkan menambahkan penduduk ke rumah tangga, silakan buat issue terpisah. Misalnya, tidak saja menambahkan penduduk satu per satu, tetapi bisa menambahkan beberapa anggota keluarga sekaligus.
> 
> Buku Panduan SIKS-NG:
> [15699415174963.pdf](https://github.com/OpenSID/OpenSID/files/6872022/15699415174963.pdf)
> 
> cc @afa28 @agungsugiarto

Betul....   tapi  secara umum   kepala rumah tangga dalam versi siks-ng  adalah juga kepala keluarga di versi kartu keluarga...namun perlu sangat teliti saat input   no ID tersebut... dan pada intinya kebutuhan utama nya adalah agar no ID dapat tertera kedalam SKTM terutama pada data individu kepala keluarganya di bagian atas surat selaku pemohon surat (bagi yg memiliki)

"Alternatif lain sebagai penyesuaian adalah satu no ID yg sama dapat di masukan ke no kartu keluarga /tweb_keluarga lain yg berada dalam satu rumah tangga".

**Comment by eddieridwan** [comment]
@muhtar-coder  Tidak perlu. Kolom yg ada di tweb_rtm akan otomatis bisa dilihat di penduduk yg menjadi anggota rumah tangga terkait. Jadi kalau kepala keluarga sudah dimasukkan ke rumah tangga terkait, ID BDT individu kepala keluarga tersebut dapat terlihat, sesuai dengan keanggotaan Rumah Tangga-nya.

Harap teman2 tidak pikirkan solusi teknisnya. Biar tim teknis melakukan sesuai dengan konsep intinya. Di sini konsep intnya adalah `ID BDT diberikan pada Rumah Tangga`.

**Comment by muhtar-coder** [comment]
Siap ...terima kasih.....

Pada tanggal Sab, 24 Jul 2021 14.24, Eddie Ridwan ***@***.***>
menulis:

**Comment by eddieridwan** [comment]
Sdh dicommit ke `rilis-dev` melalui https://github.com/OpenSID/premium/pull/323/
