### ISSUE TITLE
Tampilkan Nomor ID BDT di surat keterangan tidak mampu (SKTM)

### ISSUE THREAD

**Issue by muhtar-coder** [OpenSID/OpenSID#4300]
**Apa kekurangan yg ingin diatasi?**

Berdasarkan Peraturan Menteri Sosial Republik Indonesia No.28 Tahun 2017 Tentang Pedoman Umum Verifikasi dan Validasi Data Terpadu Penanganan Fakir Miskin dan Orang Tidak Mampu,

Maka perlu penyesuaian dalam format template surat keterangan tidak mampu (SKTM) sesuai peraturan yang berlaku

![image](https://user-images.githubusercontent.com/55665526/123826253-cc55e580-d929-11eb-97c4-8d7beecf78cf.png)

**Jelaskan solusi yg diinginkan**

Bagi keluarga yg memiliki/terdaftar dalam DTKS KEMENSOS agar tertera otomatis di surat SKTM apabila sudah di input ID nya,dan untuk keluarga yg belum terdaftar terisi dengan keterangan  tanda strip (-)

contoh surat SKTM umum
![image](https://user-images.githubusercontent.com/55665526/123826504-058e5580-d92a-11eb-92ed-0d7b73ec380e.png)

contoh surat SKTM pelajar
![image](https://user-images.githubusercontent.com/55665526/123826655-2c4c8c00-d92a-11eb-9789-ed52e5cb17de.png)

**Apakah ada alternatif lain**

**Untuk versi OpenSID mana**

Opensid V.21.08 Premium

**Informasi tambahan**

**Comment by hidayatST** [comment]
Adu ku like brooo

**Comment by mizwaruddin** [comment]
Klo bisa, nama yg tampil hanya warga yg memiliki ID BDT.

**Comment by afa28** [comment]
pak @mizwaruddin, @muhtar-coder ada tambahan lain untuk issue ini???

**Comment by muhtar-coder** [comment]
Cukup....
ID di input manual dulu di database seperti biasa isi NIK. Dan jika   surat SKTM di buat,  langsung tertera bagi yg memiliki ID...sedang kan bagi yg belum punya  tampil sesuai data di database penduduk tsb...mungkin kosong atau strip (-)

**Comment by afa28** [comment]
> Cukup....
> ID di input manual dulu di database seperti biasa isi NIK. Dan jika surat SKTM di buat, langsung tertera bagi yg memiliki ID...sedang kan bagi yg belum punya tampil sesuai data di database penduduk tsb...mungkin kosong atau strip (-)

ok

**Comment by eddieridwan** [comment]
Sdh dicommit ke `rilis-dev` melalui https://github.com/OpenSID/premium/pull/323/
