### ISSUE TITLE
Fitur Layanan Surat > Cetak Surat tidak tersimpan atau ter-unduh baik file RTF maupun PDF [BUG] 

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#4301]
**Jelaskan error yg dialami**
 OpenSID V21.07 Premium

**Cara untuk mereplikasi errornya**
 Logs Error tidak ada Laporan

**Hasil yg diharapkan**

**Tampakan layar dan log error**

**Versi OpenSID**

**Tema Yg Digunakan**

**Informasi tambahan**

**Comment by afa28** [comment]
Sudah di commit di `bug-fix`
