### ISSUE TITLE
tidak bisa menampilkan layanan pelanggan pada  karena yang tersedia anya token opendesa bukan token opensid [BUG] 

### ISSUE THREAD

**Issue by Fajar-blackdeath** [OpenSID/OpenSID#4302]
**Jelaskan error yg dialami**

**Cara untuk mereplikasi errornya**

**Hasil yg diharapkan**

**Tampakan layar dan log error**

**Versi OpenSID**

**Tema Yg Digunakan**

**Informasi tambahan**

**Comment by agungsugiarto** [comment]
Issue ini saya tutup karena token pelanggan dan token opensid adalah berbeda,

Untuk mengganti token pelanggan
1. Silahkan masuk ke menu. Info Desa > Layanan Pelanggan
2. Pada bagian pojok kanan atas perhatikam terdapat sebuah icon gear, klik untuk menampilkan pengaturan
