### ISSUE TITLE
bagian lapak deskripsi produk hanya bisa berupa angka dan tulisan.[BUG] 

### ISSUE THREAD

**Issue by Fajar-blackdeath** [OpenSID/OpenSID#4303]
**Jelaskan error yg dialami**

**Cara untuk mereplikasi errornya**

**Hasil yg diharapkan**

**Tampakan layar dan log error**

**Versi OpenSID**

**Tema Yg Digunakan**

**Informasi tambahan**

**Comment by afa28** [comment]
Duplicate issue #4271
