### ISSUE TITLE
[BUG]  Tombol Simpan pada Peta Lokasi Tempat Tinggal Penduduk saat Tambah Penduduk baru hilang

### ISSUE THREAD

**Issue by ai-skematik** [OpenSID/OpenSID#4304]
**Jelaskan error yg dialami**

Tombol Simpan pada Lokasi Tempat Tinggal Penduduk saat Tambah Penduduk baru hilang

**Cara untuk mereplikasi errornya**

Tambah Penduduk Baru pilih Lokasi Tempat Tinggal penduduk., 

**Hasil yg diharapkan**

Tombol simpan ditampilkan kembali seperti pada versi sebelumnya.

**Tampakan layar dan log error**

![gambar](https://user-images.githubusercontent.com/48144047/124305599-e7c62800-db97-11eb-81c1-2a848e0a250f.png)

**Versi OpenSID**

21.07 rilis bug fix
**Tema Yg Digunakan**

**Informasi tambahan**

**Comment by Zoel-WB** [comment]
![image](https://user-images.githubusercontent.com/64481641/124349470-5d260d00-dc19-11eb-85f4-ce3c76a994b4.png)

**Comment by Zoel-WB** [comment]
Sedang Untuk Edit Data Penduduk atau Pilih Ubah Data Penduduk, di fitur Pilih Lokasi, akan tampil seperti berikut 
![image](https://user-images.githubusercontent.com/64481641/124349515-98284080-dc19-11eb-8c23-ee09de1c8294.png)

**Comment by afa28** [comment]
Langkah tambah lokasi penduduk baru di awal versi : 
1. Buat penduduk baru > simpan (tombol tambah lokasi tdk muncul)
2. Update lokasi penduduk

Alur yg pernah sy ubah : 
1. Buat penduduk baru > tambah lokasi (sekalian menyimpan data penduduk baru) > Simpan Lokasi

Setelah bumindes digabung alur yg pernah sy tambahkan terhapus (mungkin tertindih saat commit dan tdk ada yg sadar).

Jadi yg terjadi dsni, kembali ke alur awal.

**Comment by afa28** [comment]
Sudah digabung di `bug-fix`
