### ISSUE TITLE
Peta Wilayah Dusun> Tidak Bisa Menampilkan Semua Dusun[BUG] 

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#4305]
**Jelaskan error yg dialami**

**Cara untuk mereplikasi errornya**

**Hasil yg diharapkan**

**Tampakan layar dan log error**

**Versi OpenSID**

**Tema Yg Digunakan**

**Informasi tambahan**

**Comment by ai-skematik** [comment]
up

**Comment by sutaga** [comment]
Permasalahan yang sama, dari 4 kedusunan hanya 1 kedusunan yang tampil.
Versi OpenSID  : OpenSID 21.07-premium-bugfix
Tema yang digunakan : Silir V2.6

**Comment by Zoel-WB** [comment]
Info Tambahan Bila setting wilayah seperti screensote berikut dimana Dusun Nomor 3 di Letak Paling Atas, dan Dusun Nomo 2 diposisi yang tetap dan dusun nomor 1 diletakkan ke nomor 3 :
![image](https://user-images.githubusercontent.com/64481641/124349118-c9a00c80-dc17-11eb-82c3-11703f79c03e.png)

Maka Peta Yang Tampil cuma satu dusun yaitu dusun nomor 3 saja
![image](https://user-images.githubusercontent.com/64481641/124349138-f48a6080-dc17-11eb-8e6c-7b7a5bfa0ea2.png)

Apabila letak posisi dusun letak sesuai dengan nomor urutan dusun 1, 2, 3
![image](https://user-images.githubusercontent.com/64481641/124349230-5945bb00-dc18-11eb-9903-12ad7a92ea58.png)

Maka akan tampil peta dusun, hanya dusun 1 dan 2 saja
![image](https://user-images.githubusercontent.com/64481641/124349320-a6299180-dc18-11eb-88f3-5ef5e457f4c5.png)

**Comment by afa28** [comment]
Sudah digabung ke `bugfix `melalu commit https://github.com/OpenSID/premium/commit/94ec23bf38b2365f24cb7e41acce5eabaae4fc84
