### ISSUE TITLE
[Home] Tambah Informasi ke Dashboard Admin

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#4307]
**Apa kekurangan yg ingin diatasi?**

Saat ini, ada beberapa informasi yang dapat diberikan saat login ke menu admin, seperti:
- info jumlah penduduk yang sudah terdaftar layanan mandiri
- info jumlah penduduk yang sudah isi kolom Tag ID Card
- info jumlah pelapak
- info jumlah produk yang dijual pelapak
- dan informasi lainnya yang dibutuhkan.

**Jelaskan solusi yg diinginkan**

Ketika menambahkan info jumlah penduduk yang sudah isi kolom Tag ID Card, saat diklik "Lihat Detail", maka menuju ke list penduduk yang sudah isi kolom tersebut.

Begitu pula pelapak, produk, dan lainnya.

**Informasi tambahan**

Jika menambah info jumlah ini di dasboard, maka informasi mengenai Apa Itu OpenSID, Catatam Rilis, Manajemen Hak Akses, dll akan turun ke bawah (tidak terlihat langsung oleh pengguna).

**Comment by eddieridwan** [comment]
- [ ] Sediakan pengaturan, supaya admin bisa memilih tombol informasi mana untuk ditampilkan. 
- [ ] Tombol informasi bisa diurut
- [ ] Warna tombol informasi dapat diubah warnanya

**Comment by Zoel-WB** [comment]
> - [ ] Sediakan pengaturan, supaya admin bisa memilih tombol informasi mana untuk ditampilkan. 
> - [ ] Tombol informasi bisa diurut
> - [ ] Warna tombol informasi dapat diubah warna

Iya pak @eddieridwan sangat setuju..

**Comment by davidyusufbumiratu** [comment]
> * [ ]  Sediakan pengaturan, supaya admin bisa memilih tombol informasi mana untuk ditampilkan.
> * [ ]  Tombol informasi bisa diurut
> * [ ]  Warna tombol informasi dapat diubah sesuai

Mantap, setuju Pak 👍

**Comment by davidyusufbumiratu** [comment]
Mantap, setuju pak 👍

**Comment by Zoel-WB** [comment]
Mantap 👍

**Comment by Zoel-WB** [comment]
Foto Memegang KTP di foto selfi jangan upload langsung menghadap kamera.....

**Comment by ariandii** [comment]
> Foto Memegang KTP di foto selfi jangan upload langsung menghadap kamera, ini bisa dikaji kemudian untuk menghidari pihak lain melakukan hal-hal yg tak terduga-->kemudian walaupun dapat juga masih bisa kita pastikan nomor telepon/hp pemilih indentitas.

menganai ini bisa buat issue terpisah pak.
Kolom Foto Selfie WAJIB akses langsung kamera, Tidak perlu sediakan kolom Upload Foto Selfie.

**Comment by Zoel-WB** [comment]
Foto Memegang KTP di foto selfi jangan upload langsung menghadap kamera, ini bisa dikaji kemudian untuk menghidari pihak lain melakukan hal-hal yg tak terduga-->kemudian walaupun dapat juga masih bisa kita pastikan nomor telepon/hp pemilik indentitas.

Bila mungkin ada verifikasi nomor HP atau e-mail-->khusus bila desa dengan  jumlah warga yg banyak, kalau desa dengan jumlah penduduk yg sedikit mungkin tidak meng-khawatirkan

**Comment by Zoel-WB** [comment]
> > Foto Memegang KTP di foto selfi jangan upload langsung menghadap kamera, ini bisa dikaji kemudian untuk menghidari pihak lain melakukan hal-hal yg tak terduga-->kemudian walaupun dapat juga masih bisa kita pastikan nomor telepon/hp pemilih indentitas.
> 
> menganai ini bisa buat issue terpisah pak. Kolom Foto Selfie WAJIB akses langsung kamera, Tidak perlu sediakan kolom Upload Foto Selfie.

Oke Pak.... tapi belum rilis-->tidak masalah kita buat issue-nya berdasarkan pra rilis ini pak...

**Comment by andifahruddinakas** [comment]
Pak @ariandii, issue ini masih diperlukan.
