### ISSUE TITLE
Paginasi Halaman Menu Statis [BUG] 

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#4309]
**Jelaskan error yg dialami**

Saat saya coba buat Menu Statis lebih dari 10, maka paginasi muncul angka untuk halaman 2, (padahal pada pilihan menunjukkan 20 data per halaman).

Saat paginasi angka 2 diklik, maka akan beralih ke Halaman Menu Dinamis. (Berubah menu)

**Cara untuk mereplikasi errornya**
Langkah untuk mereplikasi error yg dialami, misalnya:
1. Pergi ke halaman 'Admin Web -  Menu'
2. Klik tombol 'Paginasi angka 2'
3. akan muncul berubah tampil halaman menu dinamis,

**Hasil yg diharapkan**
Agar sesuai dengan seharusnya.

**Tampakan layar dan log error**
<img width="960" alt="2021-07-07_08h49_01" src="https://user-images.githubusercontent.com/46939846/124688676-648f3400-df01-11eb-9bc2-0b58126a7463.png">

**Versi OpenSID**
https://berputar.opensid.or.id/menu/index/1

**Comment by afa28** [comment]
Pak @ariandii, sy cek tdk ada masalah.

![11111](https://user-images.githubusercontent.com/57283157/125372192-1670a980-e3b5-11eb-8da8-65c4a414fe81.png)

**Comment by afa28** [comment]
Pak @ariandii, mas @agungsugiarto, sy cek tdk ada masalah mengikuti petunjuk di atas.

![11111](https://user-images.githubusercontent.com/57283157/125372390-93038800-e3b5-11eb-9977-1df9c31c408e.png)

**Comment by afa28** [comment]
Apakah pak @ariandii langsung akses dari https://berputar.opensid.or.id/menu, buka dari navigasi???

**Comment by ariandii** [comment]
![Screenshot_2021-07-13-07-43-04-27_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/46939846/125372741-0903f100-e3ae-11eb-9e1f-2a6d9a8295b3.jpg)

barusan saya buka web berputar, login admin, klik menu admin web, lalu menu.

tampilannya seperti di layar tersebut. 
ada 10 dari 13 menu yg ada. harusnya paginasi 20 per halaman.

tapi muncul tombol halaman 2.

**Comment by ariandii** [comment]
![Screenshot_2021-07-13-07-45-49-49_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/46939846/125372916-5ed89900-e3ae-11eb-8b29-cc2e538e9aea.jpg)

jika halman 2 dinklik, beralih ke halaman menu dinamis.

**Comment by afa28** [comment]
> ![Screenshot_2021-07-13-07-43-04-27_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/46939846/125372741-0903f100-e3ae-11eb-9e1f-2a6d9a8295b3.jpg)
> 
> barusan saya buka web berputar, login admin, klik menu admin web, lalu menu.
> 
> tampilannya seperti di layar tersebut.
> ada 10 dari 13 menu yg ada. harusnya paginasi 20 per halaman.
> 
> tapi muncul tombol halaman 2.

ini di akses langsung dr url kan, bukan dr navigasi??? krn masalahnya ada disana.

**Comment by afa28** [comment]
Krn semua modul yg berakhiran /clear akan bermasalah jika di akses langsung tanpa menggunakan navigasi saat setelah login.

**Comment by afa28** [comment]
![11111](https://user-images.githubusercontent.com/57283157/125373896-7caafb80-e3b8-11eb-9b98-f9db686f5af4.png)

**Comment by agungsugiarto** [comment]
Errornya jelas mas @afa28, di local akses lewat tab samaran, buka menu lewat navigasi, buat menu statis lebih dari 10 lakukan paginasi perhatikan jumlah yg ditampilkan dan yg tampil.

**Comment by afa28** [comment]
> Errornya jelas mas @afa28, di local akses lewat tab samaran, buka menu lewat navigasi, buat menu statis lebih dari 10 lakukan paginasi perhatikan jumlah yg ditampilkan dan yg tampil.

Ya, kalau dgn alur ini lebih jelas.
Artinya jika di duplikasi ke modul lain, maka error ini mungkin jg terjadi. Mungkin pak @ariandii, bisa cek modul lainnya.

**Comment by ariandii** [comment]
yang saya lakukan,
login siteman web berputar.opensid.or.id
klik navigasi, pilih Admin -> Web
lalu klik Menu

seketika muncul halamanenu statis, dengan tampilan 10 baris dan muncul tombol halaman 2.

**Comment by afa28** [comment]
Sudah digabung di `rilis-dev`
