### ISSUE TITLE
OpenSID dalam Container

### ISSUE THREAD

**Issue by samsulmaarif** [OpenSID/OpenSID#431]
Halo teman-teman pegiat OpenSID. Apakah ada yang berprofesi atau minat dalam bidang sysAdmin? Beberapa hari ini saya sedang belajar tentang teknologi Container, salah satunya adalah Docker. Nah, saya menggunakan OpenSID sebagai bahan ujicobanya. Mungkin perlu saya tuliskan sekilat tentang Docker di sini.

> **Docker** merupakan sebuah aplikasi yang bersifat open source yang berfungsi sebagai wadah/container untuk membungkus/memasukkan sebuah perangkat lunak secara lengkap beserta semua hal yang dibutuhkan oleh perangkat lunak tersebut agar dapat berfungsi. Dengan Docker, seorang developer maupun sysadmin dapat membangun, mengemas, dan menjalankan aplikasi di mana pun dengan cepat dan efisien. 

Jika ada temen-temen yang tertarik mencoba OpenSID dalam sebuah Container, silakan jalan-jalan ke repository saya di https://github.com/samsulmaarif/opensid-docker atau langsung ke Docker registry di https://hub.docker.com/r/samsulmaarif/opensid-aio/. Di sana juga sudah saya tuliskan sekilas tentang cara penggunaannya. 

Demikian, semoga berkenan.

**Comment by hadyanwijaya** [comment]
keren nih usulannya... TKP dulu cek recek

**Comment by andriawan** [comment]
saya tertarik untuk teknologi docker ini mas @samsulmaarif... kebetulan saya sedang aktif belajar docker...mungkin nanti bisa bantu-bantu PR sekaligus belajar real case docek for development

**Comment by samsulmaarif** [comment]
Silakan pak @andriawan, saya baru saja menuliskan panduannya di sini https://github.com/OpenSID/OpenSID/wiki/Instalasi-OpenSID-dengan-Docker-Container

**Comment by yonzfloss** [comment]
Sudah dicoba dan berjalan dengan baik panduan langkah instalasinya.

Untuk keperluan mapping hostname websitenya bisa ditambahin keterangan kalo server blocknya ada di `.docker/nginx.conf` pada opsi `server_name`.

**Comment by afa28** [comment]
Sdah dibuatkan panduan.
