### ISSUE TITLE
[BUG] Persil Tersimpan Tanpa Pemilik Awal Dari C-Desa

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#4310]
**Jelaskan error yg dialami**
 Premium V21.07-bug-fix-R1

**Cara untuk mereplikasi errornya**

**Hasil yg diharapkan**
--> 1. Persil yang terbuat dan terimpan tanpa sengaja dapat dihapus dari daftar persil.
--> 2. Persil tanpa ada pemilik C-Desa agar tak tersimpan dan ada notif peringatan yg memberi informasi bahwa persil belum lengkap atau tidak memiliki pemilik C-Desa seperti notif saat memasukkan data penduduk yg belum lengkap terisi jadi tidak bisa disimpan.
![image](https://user-images.githubusercontent.com/64481641/124713511-d9c32f00-df2a-11eb-9f1e-4471d68c297b.png)
![image](https://user-images.githubusercontent.com/64481641/124713487-d2038a80-df2a-11eb-8fd8-e7e0ff8862a9.png)

Berikan keterangan yg jelas dan singkat apa hasil yg diharapkan.
--> 3. Kalau Memang tidak boleh dihapus, Minimal bisa di edit kembali dan diarahkan ke Pemilik C-Desa Lain.
![image](https://user-images.githubusercontent.com/64481641/124714974-a08bbe80-df2c-11eb-97c7-6a7077730e04.png)
![image](https://user-images.githubusercontent.com/64481641/124715024-b26d6180-df2c-11eb-9148-1f36b05bb160.png)

**Tampakan layar dan log error**

**Versi OpenSID**

**Tema Yg Digunakan**

**Informasi tambahan**

**Comment by eddieridwan** [comment]
Ini adalah gejala yg timbul dari error lain:
1. Error pada waktu menyimpan mutasi C-Desa.
2. Kesalahan pada waktu menghapus kepemilikan awal persil di C-Desa.

**Comment by eddieridwan** [comment]
Perhatikan bahwa penentuan pemilik awal persil tidak bisa dilakukan di Persil. Harus di C-Desa, karena kepemilikan awal itu tersimpan sebagai mutasi C-Desa. Langkah untuk membuat suatu C-Desa menjadi pemilik awal suatu persil adalah sebagai terlihat di rangkaian gambar berikut. @agungsugiarto , mohon tambahkan ke panduan:

![cdesa-1](https://user-images.githubusercontent.com/249563/125734450-18de4c9e-03e7-4249-ac19-e2b9f1c2dc18.jpg)
![cdesa-2](https://user-images.githubusercontent.com/249563/125734461-3a3f90b0-5d3a-4429-bc77-b673e9e4ab72.jpg)
![cdesa-3](https://user-images.githubusercontent.com/249563/125734501-cf82b0b4-99f4-4ae5-8acd-4ee281b5a44d.jpg)
![cdesa-4](https://user-images.githubusercontent.com/249563/125734468-6643cd12-7335-40e3-bd74-f2a31519d9b9.jpg)
![cdesa-5](https://user-images.githubusercontent.com/249563/125734470-9ab47bee-2fe2-4c1f-bbf4-77d42da6e559.jpg)

**Comment by eddieridwan** [comment]
Sdh dicommit ke `bug-fix`
