### ISSUE TITLE
[BUG] Cetak Lembar Disposisi Buku Agenda - Surat Masuk Tempat Tanda Tangan yg keluar bukan Nama Pamong yg pilih akan tetapi masih tertulis nama dari bawaan system

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#4311]
**Jelaskan error yg dialami**
 Premium V21.07

**Cara untuk mereplikasi errornya**

**Hasil yg diharapkan**
--> Yang menandatangan Lembar Disposisi Surat saat dicetak mestinya yg tercetak nama yg dipilih di cetak Lembar Disposisi Surat.
Berikan keterangan yg jelas dan singkat apa hasil yg diharapkan.
-->
![image](https://user-images.githubusercontent.com/64481641/124762376-07c16700-df5d-11eb-8bb8-4d5e71f19711.png)

Nama Yang dipilih untuk Tanda Tangan, Kepala Desa : **Razali Abdullah**,  Sekretaris Desa : **Amiruddin Abdul Rahman**
![image](https://user-images.githubusercontent.com/64481641/124762676-5d960f00-df5d-11eb-8798-dd0751cbfc06.png)

Sedangkan Nama Yang Tercetak pada Lembar Disposisi Surat
![image](https://user-images.githubusercontent.com/64481641/124762987-acdc3f80-df5d-11eb-8de5-32af23aa8ea7.png)

**Tampakan layar dan log error**

**Versi OpenSID**

**Tema Yg Digunakan**

**Informasi tambahan**

**Comment by eddieridwan** [comment]
Sdh dicommit ke `bug-fix` melalui https://github.com/OpenSID/premium/pull/314
