### ISSUE TITLE
[BUG] Pada Fitur Input Data Penduduk pada kolom data yg harus diketik manual setelah selesai pengetikan data, bila ditekan tombol ENTER data tidak disimpan, akan tetapi system mengarah ke peta lokasi penduduk

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#4313]
**Jelaskan error yg dialami**
--> Saat mengubah nama salah satu penduduk menekan tombol enter data tidak tersimpan akan tetapi system mengarah ke peta lokasi penduduk.
--> Saat melakukan Scan Tag.Id E-KTP system juga tidak langsung menyimpan akan tetapi mengarah ke Peta Lokasi Penduduk, setelah dilakukan setting koordinat pilih simpan, tag.id yg sudah discan juga tidak terimpan.

Harap tidak melaporkan masalah instal OpenSID. Masalah pada waktu install harap ditanyakan di https://www.facebook.com/groups/OpenSID atau di https://t.me/joinchat/SI0GWHeqKT39Gxhh, karena terkait sistem masing2 pengguna. 

Berikan keterangan yg jelas dan singkat mengenai error yg dialami. 
Pastikan error ini juga ditemukan di https://demo.opensid.or.id (untuk RIlis Umum) atau di https://berputar.opensid.or.id (untuk RIlis Premium).
--> Premium 21.07 Bug-Fix-1-R1

**Cara untuk mereplikasi errornya**
--> edit salah satu penduduk, lalu klik salah satu kolom yg ada. dan tekan enter, atau edit salah satu nama penduduk tekan ENTER, system pasti pasti akan mengarah ke peta lokasi penduduk 
Langkah untuk mereplikasi error yg dialami, misalnya:
1. Pergi ke halaman '...'
2. Klik tombol '....'
3. Gulir ke bawah sampai '....'
4. Lihat error
-->

**Hasil yg diharapkan**

**Tampakan layar dan log error**

**Versi OpenSID**

**Tema Yg Digunakan**

**Informasi tambahan**

**Comment by agungsugiarto** [comment]
Sdh dicommit ke bug-fix
