### ISSUE TITLE
[BUG] Fitur Buku Tanah Kas Desa > Cetak Buku Tanah Desa

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#4314]
**Jelaskan error yg dialami**
--> Tidak ada pilihan penandatangan pada fitur Cetak Buku Tanah Kas Desa, hasil cetak pada tempat tanda tangan tertera nama kepala desa 2 kali atau di dua tempat baik di "Yang Mengetahui" Maupun di tempat yang menandatangan
 
Harap tidak melaporkan masalah instal OpenSID. Masalah pada waktu install harap ditanyakan di https://www.facebook.com/groups/OpenSID atau di https://t.me/joinchat/SI0GWHeqKT39Gxhh, karena terkait sistem masing2 pengguna. 

Berikan keterangan yg jelas dan singkat mengenai error yg dialami. 
Pastikan error ini juga ditemukan di https://demo.opensid.or.id (untuk RIlis Umum) atau di https://berputar.opensid.or.id (untuk RIlis Premium).
--> Premium V21.07 bug-fix-R1

**Cara untuk mereplikasi errornya**
--> Buku Fitur Buku Tanah Kas Desa, Klik Tombol Printer atau Cetak Buku Tanah Kas Desa
![image](https://user-images.githubusercontent.com/64481641/124943219-83dbad80-e036-11eb-96bd-e152bbd25892.png)
![image](https://user-images.githubusercontent.com/64481641/124943377-a372d600-e036-11eb-9139-ade655ad66a2.png)

Langkah untuk mereplikasi error yg dialami, misalnya:
1. Pergi ke halaman '...'
2. Klik tombol '....'
3. Gulir ke bawah sampai '....'
4. Lihat error
-->

**Hasil yg diharapkan**

**Tampakan layar dan log error**

**Versi OpenSID**

**Tema Yg Digunakan**

**Informasi tambahan**

**Comment by agungsugiarto** [comment]
Issue terjadi karena database bapak, untuk ub dan tdd orangnya sama silahkan di sesuaikan.

**Comment by Zoel-WB** [comment]
Benar Pak @agungsugiarto ada pilihab penanda untuk Kepala Desa di ditandai dengan a.n dan Sekretaris Desa di hidupkan u.b, makasih pak infonya tidak melihat adanya kaitan fungsinya dengan fitur Buku Aparatur Pemerintahan Desa.
