### ISSUE TITLE
[BUG] Fitur Buku Tanah Di Desa > Cetak Buku Tanah Di Desa

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#4315]
**Jelaskan error yg dialami**
-->Tidak ada pilihan penandatangan pada fitur Cetak Buku Tanah Di Desa, hasil cetak pada tempat tanda tangan tertera nama kepala desa 2 kali atau di dua tempat baik di "Yang Mengetahui" Maupun di tempat yang menandatangan

Harap tidak melaporkan masalah instal OpenSID. Masalah pada waktu install harap ditanyakan di https://www.facebook.com/groups/OpenSID atau di https://t.me/joinchat/SI0GWHeqKT39Gxhh, karena terkait sistem masing2 pengguna. 

Berikan keterangan yg jelas dan singkat mengenai error yg dialami. 
Pastikan error ini juga ditemukan di https://demo.opensid.or.id (untuk RIlis Umum) atau di https://berputar.opensid.or.id (untuk RIlis Premium).
-->Premium V21.07 bug-fix-R1

**Cara untuk mereplikasi errornya**
--> Buku Fitur Buku Tanah DI Desa, Klik Tombol Printer atau Cetak Buku Tanah Di Desa
![image](https://user-images.githubusercontent.com/64481641/124944566-9f938380-e037-11eb-81f4-fb3d4e25c0d2.png)

Hasil yang ditampilkan :
![image](https://user-images.githubusercontent.com/64481641/124944695-bd60e880-e037-11eb-8d2a-ba87d347d9da.png)

Langkah untuk mereplikasi error yg dialami, misalnya:
1. Pergi ke halaman '...'
2. Klik tombol '....'
3. Gulir ke bawah sampai '....'
4. Lihat error
-->

**Hasil yg diharapkan**
--> Hasil cetak tampil Normal ada tanda tangan "Kepala Desa" dan tanda tangan "Sekretaris Desa"
Berikan keterangan yg jelas dan singkat apa hasil yg diharapkan.
-->

**Tampakan layar dan log error**

**Versi OpenSID**

**Tema Yg Digunakan**

**Informasi tambahan**

**Comment by agungsugiarto** [comment]
Saya tidak menemukan issue yg dimaksud pak @Zoel-WB

**Comment by agungsugiarto** [comment]
Issue terjadi karena database bapak, untuk ub dan tdd orangnya sama silahkan di sesuaikan.

**Comment by Zoel-WB** [comment]
Fitur2 ini semuanya sama Pak @agungsugiarto tidak ada fitur pilihan tanda tangan, akan tetapi dalam print tercetak tanda tangan di dua tempat dengan penandatangan yang sama, baik nama orang-nya, maupun jabatan pamong-nya.

**Comment by Zoel-WB** [comment]
Benar Pak @agungsugiarto ada pilihab penanda untuk Kepala Desa di ditandai dengan a.n dan Sekretaris Desa di hidupkan u.b, makasih pak infonya tidak melihat adanya kaitan fungsinya dengan fitur Buku Aparatur Pemerintahan Desa.
