### ISSUE TITLE
[BUG] Buku Administrasi Penduduk> Cetak Buku Mutasi Penduduk

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#4317]
**Jelaskan error yg dialami**
--> Tempat Tanda Tangan, tercetak Nama Kepala Desa tertulis  2 Kali
Harap tidak melaporkan masalah instal OpenSID. Masalah pada waktu install harap ditanyakan di https://www.facebook.com/groups/OpenSID atau di https://t.me/joinchat/SI0GWHeqKT39Gxhh, karena terkait sistem masing2 pengguna. 

Berikan keterangan yg jelas dan singkat mengenai error yg dialami. 
Pastikan error ini juga ditemukan di https://demo.opensid.or.id (untuk RIlis Umum) atau di https://berputar.opensid.or.id (untuk RIlis Premium).
--> Premium V21.07 bug-fix-R1

**Cara untuk mereplikasi errornya**
--> Buka Fitur Buku Administrasi Penduduk > Klik Buku Mutasi Penduduk > Klik Tombol Cetak
![image](https://user-images.githubusercontent.com/64481641/124947841-64468400-e03a-11eb-820c-2e4b0831c3f5.png)

Tampil Preview hasil cetak, tanda tangan Kepala Desa terdapat 2 di tempat
![image](https://user-images.githubusercontent.com/64481641/124948079-9657e600-e03a-11eb-8b31-437a23ff1e63.png)

Langkah untuk mereplikasi error yg dialami, misalnya:
1. Pergi ke halaman '...'
2. Klik tombol '....'
3. Gulir ke bawah sampai '....'
4. Lihat error
-->

**Hasil yg diharapkan**

**Tampakan layar dan log error**

**Versi OpenSID**

**Tema Yg Digunakan**

**Informasi tambahan**

**Comment by agungsugiarto** [comment]
Issue terjadi karena database bapak, untuk ub dan tdd orangnya sama silahkan di sesuaikan.

**Comment by Zoel-WB** [comment]
untuk fitur cetak di fitur Ini Pak @agungsugiarto tidak ada pilihan yg menandatangan, akan tetapi hasil print outnya tercetak tempat tanda tangan sama.

**Comment by agungsugiarto** [comment]
Silahkan disesuikan pak, karena ttd menggunkan default bukan dari pilihan, mengapa bisa tercetak dengan orang yg sama?
karena di database bapak a.n dan u.b terpilih dengan orang sama.
![image](https://user-images.githubusercontent.com/10989147/125238414-6c8c1100-e311-11eb-987d-9dd15539d158.png)

Silahkan ditutup issue yg berkaitan pak @Zoel-WB, terima kasih

**Comment by Zoel-WB** [comment]
Oke pak agung nanti saya coba ulang..

Dapatkan Outlook untuk Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Zoel-WB** [comment]
Benar Pak @agungsugiarto ada pilihab penanda untuk Kepala Desa di ditandai dengan a.n dan Sekretaris Desa di hidupkan u.b, makasih pak infonya tidak melihat adanya kaitan fungsinya dengan fitur Buku Aparatur Pemerintahan Desa.
