### ISSUE TITLE
[BUG] Buku Administrasi Penduduk> Cetak Buku KTP dan KK

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#4320]
**Jelaskan error yg dialami**
--> Cetak Buku KTP dan KK, Tanda Tangan Kepala Desa Tercetak 2 kali, pada 2 tempat

Harap tidak melaporkan masalah instal OpenSID. Masalah pada waktu install harap ditanyakan di https://www.facebook.com/groups/OpenSID atau di https://t.me/joinchat/SI0GWHeqKT39Gxhh, karena terkait sistem masing2 pengguna. 

Berikan keterangan yg jelas dan singkat mengenai error yg dialami. 
Pastikan error ini juga ditemukan di https://demo.opensid.or.id (untuk RIlis Umum) atau di https://berputar.opensid.or.id (untuk RIlis Premium).
--> Premium V21.07 bug-fix-R1

**Cara untuk mereplikasi errornya**
--> Buka Fitur Buku Administrasi Penduduk > Klik Buku KTP dan KK > Klik Tombol Cetak
![image](https://user-images.githubusercontent.com/64481641/124950680-d5873680-e03c-11eb-81b6-616caa7ce410.png)

Hasil Cetak Tampilan Preview di layar terdapat tempat tanda tangan kepala desa 2 kali
![image](https://user-images.githubusercontent.com/64481641/124950860-fea7c700-e03c-11eb-8667-45987b6ced79.png)

Langkah untuk mereplikasi error yg dialami, misalnya:
1. Pergi ke halaman '...'
2. Klik tombol '....'
3. Gulir ke bawah sampai '....'
4. Lihat error
-->

**Hasil yg diharapkan**
--> Laporan tercetak normal ada tanda tangan yang mengetahui Kepala Desa dan Yang Menandatangan "Pamong Desa"
Berikan keterangan yg jelas dan singkat apa hasil yg diharapkan.
-->

**Tampakan layar dan log error**

**Versi OpenSID**

**Tema Yg Digunakan**

**Informasi tambahan**

**Comment by agungsugiarto** [comment]
Issue terjadi karena database bapak, untuk ub dan tdd orangnya sama silahkan di sesuaikan.

**Comment by Zoel-WB** [comment]
Benar Pak @agungsugiarto ada pilihab penanda untuk Kepala Desa di ditandai dengan a.n dan Sekretaris Desa di hidupkan u.b, makasih pak infonya tidak melihat adanya kaitan fungsinya dengan fitur Buku Aparatur Pemerintahan Desa.
