### ISSUE TITLE
Pengurutan Nomor Surat Berdasarkan Kode Surat (Nomor Index Surat)

### ISSUE THREAD

**Issue by isnantomch** [OpenSID/OpenSID#4321]
### Bagaimana alurnya sampai muncul masalah?
dalam proses pembuatan dan pengarsipan surat keluar/layanan penomoran kami berdasarkan no index surat, atau dalam aplikasi OpenSID bisa disesuaikan pada Kode Surat. sebagai contoh Nomor Surat 140/001/TGR/VII/2021
140 = Nomor Index Nasional
001 = Nomor Surat
TGR = Kode Desa
VII = Kode Bulan Romawi (Diharapkan kedepannya bisa dibuat Otomatis)
2021 = Tahun

### Seperti apa yang diharapkan?
saya berharap untuk penomoran surat bisa ditambahkan fitur penomoran berdasarkan Kode surat atau berdasarkan nomor index surat. jadi setiap surat dengan kode surat yang sama akan meneruskan penomoran sebelumnya.
contoh surat dengan kode surat/index 140 akan mulai dengan no 001, 002,003,004,005 dst begitu juga surat dengan kode surat/no index 474 tentang kependudukan akan dimulai dari 001,002,003,004,005 dst meskipun waktu pembuatanya berbarengan dengan surat dengan kode surat 140. walaupun surat dg kode 140 sudah mencapai no surat 400, jika surat dg kode 474 baru sampai 010 maka jika membuat surat dengan kode 474 makan akan melanjutkan dengan no surat 011.

### Apa yang terjadi?
jika fitur ini bisa diterapkan akan menciptakan kerapian arsip surat berdasarkan No Index surat ( berdasarkan Kode surat) sesuai dengan penomoran surat kedinasan.

### Informasi tambahan 

| Versi OpenSID    | 21.07
| Versi PHP        | 7.4.20
| System operasi   | 7 dan 10
Versi MYSQL terpasang 10.2.38-MariaDB-log-cll-lve
![Index surat](https://user-images.githubusercontent.com/59205349/125061169-41b67880-e0d7-11eb-8e5e-8345af0ff63c.jpg)

**Comment by afa28** [comment]
Untuk `VII = Kode Bulan Romawi (Diharapkan kedepannya bisa dibuat Otomatis)` sudah otomatis dibuat berdasarkan bulan cetak surat.

**Comment by afa28** [comment]
Silahkan baca panduan https://github.com/OpenSID/OpenSID/wiki/Pengaturan-Aplikasi untuk penomoran surat.
