### ISSUE TITLE
Sediakan Kolom Token API Telegram

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#4322]
**Apa kekurangan yg ingin diatasi?**
Sebagai sarana untuk membantu memantau aktifitas vital oleh Admin/Operator Desa pengguna OpenSID, yang dapat dengan cepat mendapat notifikasi melalui Chat Telegram.

**Jelaskan solusi yg diinginkan**
Adanya kolom untuk input Token API Telegram yang telah disediakan sebagai notifikasi diantaranya:
1. permohonan surat melalui layanan mandiri
2. pesan masuk dar layanan mandiri
3. permohonan ajuan lapak dari layanan mandiri (fitur kedepan)
4. mengetahui sesaat setelah operator login
5. dll yang diperlukan

**Alternatif**
Mengingat layanan API Telegram dapat digunakan secara gratis.

```
function sendMessage($telegram_id, $message_text, $secret_token) {
   $url = "https://api.telegram.org/bot" . $secret_token . "/sendMessage?parse_mode=markdown&chat_id=" . $telegram_id;
   $url = $url . "&text=" . urlencode($message_text);
   $ch = curl_init();
   $optArray = array(
      CURLOPT_URL => $url,
      CURLOPT_RETURNTRANSFER => true
   );
   curl_setopt_array($ch, $optArray);
   $result = curl_exec($ch);
   curl_close($ch);
}
```

**Comment by lihin20** [comment]
Setuju banget, sangat di perlukan.

**Comment by rudiansyahyunanda** [comment]
Sangat diperlukan

**Comment by sutaga** [comment]
Setuju 👍

**Comment by muhtar-coder** [comment]
Setuju....

**Comment by ahmadngudi** [comment]
setuju sangat

**Comment by rohmanudin05** [comment]
Sangat bermanfaat sekali untuk menunjang lancarnya digitalisasi.

**Comment by Zoel-WB** [comment]
Setuju...👍

**Comment by donip90** [comment]
Setuju 👍👍👍👍

**Comment by cepiandiana** [comment]
Keren bingittts ini

**Comment by luxmant354** [comment]
Sangat Rekomendasi 😍

**Comment by muslimrahmany** [comment]
Setuju ..

**Comment by abmuj18** [comment]
Keren juga nih, lanjutkan! 👍

**Comment by desasoro** [comment]
OpenSID makin mantap.👍

**Comment by agungsugiarto** [comment]
Pak @ariandii, mohon diberikan contoh semua pesan notfikasi untuk

1. permohonan surat melalui layanan mandiri
2. pesan masuk dar layanan mandiri
3. permohonan ajuan lapak dari layanan mandiri (fitur kedepan)
4. mengetahui sesaat setelah operator login

**Comment by ariandii** [comment]
Contoh:
1. Segera cek Halaman Admin, penduduk atas nama Ariandi Ryan Kahfi (08115222660) telah mengajukan Surat XXX melalui Layanan Mandiri pada tanggal 02-Jun-2021 10:00:47
2. Warga RT. XXX atas nama YYY telah mengirim pesan melalui Layanan Mandiri pada tanggal 22-Jun-2021 10:00:47
3. Permohonan aktivasi Produk XXX pada Layanan Mandiri dari warga RT. YYY atas nama ZZZ pada tanggal 22-Jun-2021 10:00:47
4. Ariandi Ryan Kahfi (admin) login Halaman Admin https://www.natairaya.desa.id pada tanggal 04-Oct-2021 13:19:34

**Comment by andifahruddinakas** [comment]
Sudah digabungkan ke FITUR PREMIUM.

**Comment by ariandii** [comment]
yang digabung tersebut apakah bisa untuk lebih dari 1 akun telegram penerima notifikasi?

baik itu warga ybs, operator, maupun admin.

**Comment by andifahruddinakas** [comment]
> yang digabung tersebut apakah bisa untuk lebih dari 1 akun telegram penerima notifikasi?
> 
> baik itu warga ybs, operator, maupun admin.

Dari panduan yg diberika mas @agungsugiarto dan sudah sy pindahkan ke https://github.com/OpenSID/OpenSID/wiki/Bot-Notifikasi-Telegram, sy hanya testing di 1 akun sebagai admin.

**Comment by ariandii** [comment]
bung @afa28 @agungsugiarto 
pada Pengaturan > Aplikasi saat ini dikolom "Telegram User Id" hanya bisa isi 1 id telegram.

apakah bisa misal ingin menerima notifikasi lebih dari 1 akun operator? contoh ada tanda koma antar id sebagai pemisah.

jika memungkinkan, akan saya buat issue baru.

**Comment by andifahruddinakas** [comment]
> bung @afa28 @agungsugiarto pada Pengaturan > Aplikasi saat ini dikolom "Telegram User Id" hanya bisa isi 1 id telegram.
> 
> apakah bisa misal ingin menerima notifikasi lebih dari 1 akun operator? contoh ada tanda koma antar id sebagai pemisah.
> 
> jika memungkinkan, akan saya buat issue baru.

Silahkan pak @ariandii.

**Comment by eddieridwan** [comment]
@ariandii @afa28 @agungsugiarto , untuk issue baru, saya sarankan yg diusulkan sbb:
1. akun telegram dimuat per perangkat desa melalui menu Pemerintahan Desa
2. di Pemerintahan Desa tambah indikator perangkat desa penerima notifikasi
3. sediakan beberapa jenis notifikasi, sehingga bagi masing2 perangkat desa bisa ditentukan notifikasi apa yg diterima. Notifikasi dikirim sesuai penentuan tsb,
4. karena penentuan notifikasi ini berdasarkan tupoksi masing2 perangkat desa, sebaiknya penentuan notifikasi dilakukan admin, bukan masing2 perangkat desa
5. bisa disediakan juga opsi mengirim notifikasi ke email

**Comment by agungsugiarto** [comment]
> bung @afa28 @agungsugiarto 
> pada Pengaturan > Aplikasi saat ini dikolom "Telegram User Id" hanya bisa isi 1 id telegram.
> 
> apakah bisa misal ingin menerima notifikasi lebih dari 1 akun operator? contoh ada tanda koma antar id sebagai pemisah.
> 
> jika memungkinkan, akan saya buat issue baru.

Telegram tidak menyediakan fitur broadcast,  bisa diakali dengan looping tapi tidak disarankan karena akan memakan waktu yg lama untuk mengirim.
