### ISSUE TITLE
Kehadiran Perangkat Desa

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#4323]
* ISSUE INI TELAH DIPECAH MENJADI PROJECT https://github.com/orgs/OpenSID/projects/2/views/1 *

**Apa kekurangan yg ingin diatasi?**

Diperlukan fitur OpenSID bagi warga untuk mengetahui apakah seorang perangkat desa ada di kantor atau tidak.

**Jelaskan solusi yg diinginkan**

1. Setiap perangkat desa dapat melapor hadir/masuk menggunakan gawai scan eKTP yang disediakan di kantor desa. Sebagai alternatif, perangkat desa juga dapat melapor hadir menggunakan NIK dan PIN.
2. Setiap perangkat desa dapat melapor keluar menggunakan gawai scan eKTP. Sebagai alternatif, perangkat desa juga dapat melapor keluar menggunakan NIK dan PIN.
3. Jika perangkat desa melapor masuk tetapi tidak melapor keluar setelah jam tertentu, dianggap keluar dan ditandai sebagai lupa melapor keluar. Admin dapat menentukan setting jam `kantor tutup` tersebut.
4. Kehadiran/tidaknya setiap perangkat desa terlihat di widget Aparatur Desa.
5. Kehadiran/tidaknya setiap perangkat desa terlihat di Layanan Mandiri.
6. Di Layanan Mandiri, warga dapat melaporkan perangkat desa yg terlihat hadir tetapi ternyata diketahui tidak ada di kantor desa. Yaitu di Layanan Mandiri perangkat ybs tampil sebagai hadir di kantor desa, tetapi pada waktu dihubungi ternyata tidak ada. Warga dihimbau untuk melaporkan perangkat desa tersebut, dengan menandai perangkat desa tersebut sebagai `absen tanpa diketahui`. Identitas warga yg melapor juga dicatat. Laporan tidak-hadir ini dapat dikirim oleh lebih dari satu warga bagi perangkat desa yg sama. Hanya satu laporan yg tercatat setiap hari bagi satu warga pada perangkat desa yg sama.
7. Disediakan laporan absensi untuk rentang waktu tertentu. Pilihan rentang default: hari ini, minggu ini, bulan ini. Selain itu, juga dapat ditentukan rentang waktu secara bebas.
8. Laporan absensi berisi identitas perangkat desa, tanggal, berapa jam masuk pada tanggal, tanda tidak melapor keluar, tanda absen tidak diketahui
9. Laporan absensi bisa difilter untuk perangkat desa tertentu, tanda melapor keluar, tanda absen tidak diketahui
10. Laporan absensi bisa dicetak dan diunduh dalam format excel
11. Hari libur tidak dilakukan pencatatan kehadiran perangkat desa. Admin dapat menentukan setting hari libur.
12. Perangkat desa dapat masuk/keluar lebih dari satu kali dalam satu hari.
13. Data kehadiran hanya dapat diubah oleh pengguna administrator.
14. Laporan dari warga terkait kehadiran perangkat desa yg `absen tanpa diketahui` dapat diberi catatan oleh petugas pengawas kantor desa. Misalnya, petugas yg berwenang tersebut dapat memberi penjelasan terkait ketidak hadiran seorang perangkat desa.

**Apakah ada alternatif lain**

Versi fitur absensi lebih luas digagas di https://github.com/OpenSID/OpenSID/issues/2033. Yaitu untuk adanya modul absensi pengurus yg lebih rinci lagi memantau kedisplinan aparatur desa. sehingga dapat menjadi acuan untuk kinerja aparatur desa.

**Fitur di issue yang sekarang ini, walaupun juga dapat digunakan untuk kedisiplinan perangkat desa, lebih fokus pada layanan warga. Sebagai contoh, issue ini tidak mencatat apakah perangkat desa sedang cuti, atau tidak hadir karena sedang dinas luar.**

**Untuk versi OpenSID mana**

OpenSID v21.07-premium

**Informasi Tambahan**

Data aparat ada di tabel `tweb_desa_pamong`. Aparat bisa penduduk desa atau dari luar desa. Jika dari penduduk desa, datanya ada di tabel `tweb_penduduk`. Di tweb_penduduk ada kolom `tag_id_card` yg berisi tag_id dari eKTP masing2 penduduk yg akan login menggunakan scan eKTP.

Perangkat desa akan melapor masuk/keluar di gawai scan eKTP yg disediakan di kantor desa. Fitur ini bertujuan untuk transparansi bagi warga terbatas pada kehadiran di kantor desa, dan bukan untuk absensi secara lebih luas. Hasil scan eKTP akan membaca `tag_id` kartu eKTP tersebut, yang kemudian dibandingkan dengan data `tag_id_card` yg tersimpan di database untuk perangkat ybs. 

Fitur OpenSID yg ada saat ini dapat diperiksa di https://github.com/OpenSID/OpenSID dan juga bisa dicoba langsung di https://demo.opensid.or.id. Periksa script/database dan demo untuk menentukan fitur2 tambahan apa saja yg diperlukan. Sebagai contoh, pemeriksaan itu akan menemukan bahwa setting hari libur belum ada dan perlu ditambahkan.

ERD struktur database OpenSID dapat dilihat di https://github.com/OpenSID/OpenSID/wiki/ERD-OpenSID.

**Comment by ariandii** [comment]
juga tersedia field untuk perangkat desa yang sedang DInas Luar, baik berdasarkan surat maupun sedang berkunjung ke kantor dinas/kecamatan. termasuk sedang diluar (tinjau lapangan)

**Comment by eddieridwan** [comment]
@ariandii untuk versi awal ini sederhana saja. Harap lihat batasan di penjelasan di atas. Jadi dinas luar `tidak` akan dicatat untuk ruang lingkup issue ini.

**Comment by muhtar-coder** [comment]
di buat sederhana saja karena seperti kita ketahui perangkat desa banyak tidak terlalu paham,,adapun dalam pengembangan kedepan setelah tersosialisasi dan terbiasa mungkin akan lebih bagus

**Comment by Gunturwijay** [comment]
mohon agar dapat digunakan multi fungsi oleh lembaga/petugas lain selain perangkat desa, contoh seperti kami ada petugas kebersihan desa berjumlah 20 orang yang harus mengisi absen setiap harinya, dan mohon juga disetting terhadap hari libur mereka yang berbeda dengan perangkat desa, terima kasih.

**Comment by eddieridwan** [comment]
### Rekam hadir/keluar

Solusi yg dibayangkan untuk rekam hadir/keluar seorang perangkat desa sbb.

1. Di salah satu dinding kantor desa, dipasang:
    a. Tablet, dengan layar sentuh
    b. Gawai scan RFID
2. Di tablet tampil form login/absen
3. Halaman pertama: bisa scan eKTP atau isi NIK/PIN untuk login
4. Halaman kedua: setelah berhasil login, 
    a.  tampil status kehadiran perangkat
    b. Jika `hadir`, maka tombol `keluar` akan aktif. Jika tombol ini ditekan, maka status perangkat menjadi `keluar`
    c. Jika `keluar`, maka tombol `hadir` akan aktif. Jika tombol ini ditekan, maka status perangkat menjadi `hadir`.
    d. Ada tombol `selesai`. Jika ditekan akan balik ke halaman login awal
    e. Setelah 1 menit tidak ada interaksi, akan otomatis balik ke halaman login awal
5. Di tablet itu, hanya form login kehadiran yg bisa ditampilkan.

Mockup untuk layar2 di form kehadiran di tablet dapat dilihat di https://www.figma.com/file/s0wZS0ygxOiRzwyRf3tr8Z/Kehadiran?node-id=0%3A1

### Widget Perangkat Desa

![absensi-1](https://user-images.githubusercontent.com/249563/132119340-2951f5c8-87a3-459f-81e6-9effb033f3de.jpg)

### Layanan Mandiri

![absensi-2](https://user-images.githubusercontent.com/249563/132122237-cafe960a-d64e-4245-adfb-b57b668c4dd4.jpg)

### Menu Admin

![absensi-3](https://user-images.githubusercontent.com/249563/132123754-524f67d4-504b-4b28-b890-9563f872a252.jpg)

**Comment by gundambison** [comment]
modu yang dikerjakanl:
1.	penentuan hari merah. Modul berikut untuk ujicoba memahami dari cms berikut. Tampilan modul ini lebih kepada memperlihatkan select bulan dan tahun lalu muncul list tanggal yang bisa di klik untuk membuat jadi tanggal merah/tidak. Modul ini mempengaruhi
o	Halaman presensi akan terbuka/tidak.
o	Rekap kehadiran akan di skip apabila tanggal bersangkutan adalah tanggal merah.
o	Proses dalam system akan di stop terkait tanggal merah.	
2.	presensi => mencatat yg melakukan scan masuk/keluar.. ini lebih kepada pencatatan dia scan. Terkait modul ini proses yang terjadi:
o	login pada halaman baru
o	pengechekan NIK/PIN yang terkait
o	memberikan tombol masuk/keluar
o	mencatat proses masuk/keluar
3.	tampilan presensi hari ini. Tampilan ini untuk di halaman layanan mandiri(?)
o	muncul kemungkinan di halaman depan(?)
o	field apa saja yang ditampilkan
4.	rekap presensi => berdasarkan presensi di atas. Untuk keperluan ini diperlukan akses grup pengawas (disarankan). di convert jadi table yang dapat ditarik dengan filter yang sudah ditentukan. Modul ini terkait
o	menampilkan sebagai datatable
o	export sebagai excel
o	filter berdasarkan tanggal. 
o	Filter tanggal/param rekap. Bersifat optional
o	Laporan absensi bisa difilter untuk perangkat desa tertentu. Disarankan menentukan grup2 yang tepat untuk proses ini.
5.	laporan warga => fitur ini lebih kepada laporan warga karena yg bersangkutan melaporkan dirinya tersedia tapi tidak ada. Modul ini terkait:
o	pelaporan pada halaman layanan mandiri
o	bentuk halaman perlu ditanyakan 
6.	update detail laporan warga => fitur ini lebih kepada penjelasan  atas laporan yang ada.  Dijalankan oleh pengawas
7.	rekap presensi dengan sanksi => rekap atas laporan warga.
o	Menampilkan sebagai datatable
o	Export sebagai excel
o	Filter berdasarkan tanggal
o	Filter tanggal dan parameter

Mohon bantuannya untuk penambahan kategori pengguna, terkait yang dapat melakukan proses pada point 6 (pengawas). Agar saya bisa tambahkan dalam migrasi database . 
point 1 masih memakai admin

**Comment by nurisakbar** [comment]
ERD untuk issue kehadiran perangkat desa, kurang lebih seperti ini, silahkan ditambahkan jika memang ada informasi lain yang dibutuhkan.
![erd_kehadiran_perangkat_desa](https://user-images.githubusercontent.com/5483330/133007491-71007b2a-53e7-4501-835d-15c608222be9.png)

**Comment by eddieridwan** [comment]
@nurisakbar beberapa hal:

-  Perlu ada kolom `tag_id` di tabel `tweb_desa_pamong`, untuk menyimpan tag id eKTP pamong luar desa. 
- Tambahkan kolom `pin` di tabel `tweb_desa_pamong`,  untuk menyimpan PIN bagi `semua` pamong.
- Di tabel `laporan_kehadiran_oleh_warga` tidak disimpan `nik`. Melainkan disimpan `id_pend` sebagai foreign key ke `tweb_penduduk`. Hanya penduduk yg terdaftar layanan mandiri yg melapor.  
- Di tabel `laporan_kehadiran_oleh_warga` juga perlu kolom `keterangan` untuk diisi oleh pengawas terkait laporan itu, jika perlu. 

@nurisakbar , mohon perbaiki ERD dan ganti di komentar di atas. Yaitu, jangan buat komentar baru.

**Comment by gundambison** [comment]
Untuk masalah PIN masuk dari Pamong non Warga. PINnya diletakkan dimana? apakah harus ditambahkan fieldnya.. Saya minta masukan ini dahulu, karena info terbaru tidak menyebutkan mengenai hal tersebut

**Comment by eddieridwan** [comment]
> Untuk masalah PIN masuk dari Pamong non Warga. PINnya diletakkan dimana? apakah harus ditambahkan fieldnya.. Saya minta masukan ini dahulu, karena info terbaru tidak menyebutkan mengenai hal tersebut

Sudah ditambahkan di komentar https://github.com/OpenSID/OpenSID/issues/4323#issuecomment-919620758. Tapi harap anda juga ikut mengusulkan struktur database yg dibutuhkan. Silakan beri usul jika perlu, untuk kami setujui.

**Comment by gundambison** [comment]
![fsakjfsar](https://user-images.githubusercontent.com/1597200/133360895-65a2d693-a1ac-4815-894a-f2aa341551c5.jpg)
berikut adalah table yang saya propose
![safraq](https://user-images.githubusercontent.com/1597200/133361041-a4a90178-6813-4c5f-adfa-f9e637368d97.jpg)
berikut adalah struktur dari table kehadiran
berikut penjelasan field

- pamong_id : relasi ke table pamong
- tanggal : tanggal melakukan proses kehadiran
- waktu masuk dan waktu keluar: untuk info yang lebih detail.. saya memasukkan tanggal dan waktu
- pamong_info: json berisi informasi dari pamong . dimana info ini adalah summary dari table pamong baik yg sudah relasi maupun belum relasi..
- hadir_log: log proses kehadiran.

**Comment by eddieridwan** [comment]
@nurisakbar , mohon anda review usulan @gundambison

**Comment by nurisakbar** [comment]
@gundambison : jadi maksudnya hadir_log akan digunakan untuk menyimpan summary ya mas ?
semua history masuk dan keluar di write kesitu ?

**Comment by nurisakbar** [comment]
berikut ini hasil revisi dari saya, dengan memasukan tambahan informasi dari pak @eddieridwan 
![revisi erd kehadiran](https://user-images.githubusercontent.com/5483330/133383724-0e3d7db1-8915-4c59-9b0d-a7bbc1395787.png)

**Comment by gundambison** [comment]
>hadir_log 

ya.. akan menyimpan info terkait kapan masuk dan kapan keluar.. bentuknya json.. dan akan terbaca saat di rekapnya

> tag_id  

akan ditambahkan tag_id_card sesuai yang ada di tweb_penduduk. 

plan kerja saat ini

1. membuat tampilan masuk/keluar
2. membuat rekap kehadiran
3. membuat export kehadiran
4. membuat menu tambahan setelah login mandiri yang terkait pelaporan
5. membuat logika pelaporan
6. memasukkan pelaporan pada rekap kehadiran (no 2 di update). dan otomatis no 3 akan di update
7. memasukkan logika hari merah 
8. pull gabung ke branch utama.

catatan: saat ini branch yang saya kerjakan terpisah dari yang di PR agar sekalian.  kemungkinan ketika proses no 3.. akan di gabung ke PR yang sebelumnya

**Comment by nurisakbar** [comment]
@gundambison  untuk posisi menu nya seperti yang sudah disebutkan di atas ( posisi menu admin ), untuk mockupnya kurang lebih seperti ini : 
![Screen Shot 2021-09-20 at 12 56 31](https://user-images.githubusercontent.com/5483330/133961791-9d8f5dc0-1c2f-4159-b053-27f736bc865a.png)

ini hanya referensi saja, silahkan di sesuaikan dengan kebutuhan.
terima kasih

**Comment by gundambison** [comment]
update yang dibahas discord kemarin

1. menambahkan menu pada menu penduduk di antara pesan dan bantuan
2. halaman tampilan laporan diawali menampilkan list para aparat dalam bentuk gambar grid
3. mengklik salah satu foto (grid) akan mengeluarkan popup yang berisi input alasan laporan
4. submit yang dilakukan akan memberikan flagging pada aparat bersangkutan
5. info terima kasih atas laporan diberikan pada halaman berikutnya
6. penambahan menu rekap di admin dengan tampilan di atas

masalah wording setelah pull request terbaru

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/839
