### ISSUE TITLE
[Identitas Desa] Tambahkan kolom isian Batas desa dan Orbitrasi di info Desa

### ISSUE THREAD

**Issue by muhtar-coder** [OpenSID/OpenSID#4324]
**Apa kekurangan yg ingin diatasi?**

Melengkapi menu info desa,dimana info desa merupakan identitas utama terkait desa/kelurahan

**Jelaskan solusi yg diinginkan**

1. bisa di tambahkan tambahan isian di bagian bawah info desa untuk data isian batas desa dan di bawahnya lagi isian orbitrasi desa yg sesuai dengan standart isian kemendagri.

![image](https://user-images.githubusercontent.com/55665526/125166663-dcda4b80-e1c6-11eb-8b76-344a62782f55.png)
![image](https://user-images.githubusercontent.com/55665526/125166674-e5cb1d00-e1c6-11eb-8b87-fddaf2d9f1e4.png)

2. menu info desa agar dapat di jadikan menu statis untuk ditempatkan di website yg berada pada profil desa 

**Apakah ada alternatif lain**

**Untuk versi OpenSID mana**

versi 21.09 premium

**Informasi tambahan**

kedepan setelah menu ini tersedia memungkinkan desa untuk membuat print out profil desa secara lengkap dengan daftar isi lampiran yang di ambil dari banyak sumber seperti : menu info desa ini,data analisis,menu statistik lain nya.

**Comment by muhtar-coder** [comment]
data profil desa sangat di butuhkan desa dan merupakan laporan wajib serta permintaan wajib yang di minta banyak pihak,setiap tahun .printout nya kurang lebih seperti berikut : https://cugung-rajabasa.desa.id/artikel/2020/11/22/pofil-desa-cugung-tahun-2020

**Comment by Zoel-WB** [comment]
Oke, Mantap, Setuju......

**Comment by donip90** [comment]
Mantap.. Setuju, karna diperlukan setiap tahunnya

**Comment by Zoel-WB** [comment]
1. Topograsi : Lerang/Puncak, Lembah, dataran, pesisir pantai, Lainnya : sebutkan (ada isiannya)
2. Koordinat Lintang :
3. Koordinat bujur :
4. Lintang Utara :
5. Lintang Selatan :
6. Ketinggian : 
7. Kondisi Jalan Desa Secara Umum : tanah, perkerasan kerikil, Perkerasan Rabat Beton, Aspal

**Comment by SopianHadi2021** [comment]
Setuju fitur ini sangat dibutuhkan untuk kelengkapan identitas desa

**Comment by afa28** [comment]
Catatan:

Untuk saat ini scr struktur table config tdk efisien untuk bisa menambah data sesuai issue ini, krn perlu dibuatkan fieldnya masing2 yg mungkin kedepannya akan bertambah. Yg perlu dilakukan, mengubah struktur table config agar bisa menampung data yg mudah disesuaikan ke depannya. Mungkin bisa di buat setting_aplikasi, atau buat table lain (jgn pakai table config). Namun dgn perubahan tsb akan mempengaruhi semua modul yg ada di OpenSID dan perlu dilakukan pengecekan scr maksimal.

**Comment by muhtar-coder** [comment]
Benar, memang bagus nya di pisah ...
nanti saya tambah sampel setting lain

Pada tanggal Min, 11 Jul 2021 13.58, Andi Fahruddin Akas <
***@***.***> menulis:

**Comment by eddieridwan** [comment]
Bukankah informasi ini yg ada di SDGs, atau IDM? Yg dikelola menggunakan modul Analisis?

**Comment by muhtar-coder** [comment]
Ya.Sebagian besar di ambil dari analisis..  lain lain nya bisa dari
data,statistik,suplement.dan info desa.

Pada tanggal Min, 11 Jul 2021 14.16, Eddie Ridwan ***@***.***>
menulis:

**Comment by muhtar-coder** [comment]
Yg di butuhkan desa adalah cetak lampiran lengkap yg umumnya sebagai
laporan misal :Lppd,ke bps,ke balitbang,dll

Pada tanggal Min, 11 Jul 2021 14.52, utay doang ***@***.***>
menulis:

**Comment by andifahruddinakas** [comment]
Duplicate issue https://github.com/OpenSID/OpenSID/issues/7693
