### ISSUE TITLE
[BUG] - Format Data Penduduk .xls Sinkronisasi Dari OpenSID ke OpenDK tdk sesuai

### ISSUE THREAD

**Issue by afa28** [OpenSID/OpenSID#4327]
**Jelaskan error yg dialami**

Saat melakukan singkronisasi baik manual dan melalui api terjadi kersalahan yakni 
`[2021-07-12 19:13:24] local.DEBUG: Undefined variable: desa_id  `

**Cara untuk mereplikasi errornya**

Lakukan sinkronisasi data penduduk dari OpenSID ke OpenDK baik scr manual ataupun lewat API.

**Hasil yg diharapkan**

Setelah penambahan field status_dasar pada format ekspor xlsx data penduduk menyebabkan strukturnya berubah, sehingga desa_id kosong. Dan field status_dasar menjadi 2.

**Tampakan layar dan log error**

![1111](https://user-images.githubusercontent.com/57283157/125287066-12aa3c00-e34f-11eb-885a-1477acf32340.png)

**Versi OpenSID**

**Tema Yg Digunakan**

**Informasi tambahan**

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melalui PR: https://github.com/OpenSID/premium/pull/341
