### ISSUE TITLE
Sediakan Fitur Polling

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#4328]
**Apa kekurangan yg ingin diatasi?**
Fitur polling dapat membantu meningkatkan pelayanan. Salah satunya untuk mengetahui pilihan warga atau kelompok tertentu sebagai penentu opsi yang diberikan.

Fitur ini dapat digunakan seperti:
1. Pemilihan Ketua Kelompok (tersedia foto)
2. Pemilihan Jadwal/Tempat Pertemuan
3. Pemilihan Design Spanduk
4. Pemilihan Lomba RT
4. Dan Lainnya yang bersifat umum

**Jelaskan solusi yg diinginkan**
Adanya Menu Polling/Vote dengan batasan sebagai berikut:
1. Pemilih dari Penduduk Terdaftar, atau
2. Pemilih dari Penduduk berdasarkan Jenis Kelamin/Agama/RT/dll, atau
3. Pemilih dari Penduduk yang hanya memiliki Nomor HP, atau
4. Bisa Pilih lebih dari 1 kali atau hanya 1 kali untuk 1 NIK, atau
5. Bisa Pilih untuk Pemilih umum dengan batasan IP, Session, dll

**Apakah ada alternatif lain**
Jika memanfaatkan Menu SMS, dapat dibuat Polling melalui SMS, bisa diterapkan 1 vote untuk 1 nomor Hp (Penduduk Terdaftar/Umum), bahkan nomor Hp bisa untuk beberapa vote.

**Informasi tambahan**
Bisa buat lebih dari 1 Polling. dan sediakan waktu masa aktif polling atau status on/off secara manual.

**Comment by rohmanudin05** [comment]
Sangat setuju sekali itu memang perlu untuk peningkatan

**Comment by donip90** [comment]
Mantap... Lanjutkan

**Comment by muslimrahmany** [comment]
Lanjut pak ..

**Comment by Zoel-WB** [comment]
Oke Mantap....

**Comment by lihin20** [comment]
oke mantap, setuju

**Comment by muhtar-coder** [comment]
Lanjut...

**Comment by afa28** [comment]
Apakah sama dengan issue ini https://github.com/OpenSID/OpenSID/issues/2273 ???

**Comment by komarhaziq** [comment]
Sangat setuju sekali itu memang perlu

**Comment by ariandii** [comment]
> Apakah sama dengan issue ini #2273 ???

tidak sama, pada issue ini tidak ada rembuk, melainkan vote murni.

**Comment by bila2015** [comment]
Sementara ni masih memilih dan memilah dulu... mantau aja dulu ketua :)

**Comment by tobagus6911** [comment]
Juga Poling lainnya. seperti tingkat kepuasan, dll

**Comment by ariandii** [comment]
> Juga Poling lainnya. seperti tingkat kepuasan, dll

tingkat kepuasan sudah ada, akan muncul ketika warga klik Logout Layanan Mandiri
