### ISSUE TITLE
Buka OpenSID di anjungan tanpa harus memasukkan alamat OpenSID di browser

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#4331]
**Apa kekurangan yg ingin diatasi?**

Saat ini, membuka OpenSID di anjungan mengikuti proses yg sama dengan yg diikuti pada gawai lainnya. Yaitu, membuka browser dan memasukkan alamat web OpenSID ke browser. Cara ini dianggap oleh banyak desa tidak ramah dan menginginkan cara yg lebih mudah dan langsung.

**Jelaskan solusi yg diinginkan**

Diinginkan adanya aplikasi yg secara langsung membuka OpenSID tanpa harus memasukkan alamat web OpenSID.

Beberapa opsi:
1. Bantu desa membuat short-cut browser di desktop, yg akan membuka OpenSID langsung mengarah ke web desa
2. Membuat aplikasi terpisah yg membuka (embedded?) browser yg langsung mengarah ke web OpenSID

Opsi (2) lebih fleksibel. Issue ini terkait dengan issue https://github.com/OpenSID/OpenSID/issues/4330, di mana disediakan cara untuk memberitahu OpenSID secara stabil bahwa gawai yg memanggil adalah anjungan. Jadi aplikasi tersebut bisa membaca MAC address gawai dan mengirim ke OpenSID, beserta token untuk otentikasi desa.

**Untuk versi OpenSID mana**

v21.07-premium

**Comment by Zoel-WB** [comment]
Mantap Pak @eddieridwan

**Comment by rudiansyahyunanda** [comment]
apa boleh ditambah, otomatis logout dengan rentang waktu tertentu dan kembali ke halaman login/screen saver anjungan (menghindari terjadinya lupa logout agar akun aktif tidak digunakan orang lain pada anjungan)

**Comment by rohmanudin05** [comment]
Sngat setuju dengan idenya bung@rudiansyahyunanda karena apa bila orang awam yang memakai bisa jadi setelah login gak logout

**Comment by eddieridwan** [comment]
Aplikasi Pembuka Anjungan untuk Windows telah dibuat. Panduannya di https://github.com/OpenSID/OpenSID/wiki/Anjungan#aplikasi-pembuka-anjungan.

Untuk penggunaannya diperlukan versi OpenSID premium yg telah menerapkan issue https://github.com/OpenSID/OpenSID/issues/4330.
