### ISSUE TITLE
[Peta] Peta Desa dapat menampilkan data Rumah tangga

### ISSUE THREAD

**Issue by makhbub** [OpenSID/OpenSID#4333]
**Apa kekurangan yg ingin diatasi?**
<!-Rumah Tangga merupakan suatu kesatuan penduduk yang tinggal dalam satu rumah.
saat ini Peta Desa sudah menampilkan data Penduduk dan Keluarga dan belum menampilkan data Rumah Tangga

Beri keterangan singkat dan jelas mengapa fitur ini diperlukan. 
--> data rumah tangga merupakan fitur pencarian penduduk yang lebih sederhana dan mudah dibaca karena dalam satu titik hanya terdapat satu rumah sehingga tidak ada data bertumpuk, selain itu data rumah tangga selanjutnya dapat dikembangkan menjadi peta Rumah tidak Layak Huni dan peta Rumah tangga yang belum mempunyai sanitasi sehat

**Jelaskan solusi yg diinginkan**

![peta legenda](https://user-images.githubusercontent.com/38773660/126103201-846e3c54-48fa-486a-8a5e-00f44ac20492.jpg)

**Apakah ada alternatif lain**

**Untuk versi OpenSID mana**
Fitur ini diusulkan untuk versi Rilis Umum  v21.08

**Informasi tambahan**

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/OpenSID/pull/7459
