### ISSUE TITLE
Penambahan No surat Pengantar RT di Layanan Surat Keterangan

### ISSUE THREAD

**Issue by s3lv4ng** [OpenSID/OpenSID#4335]
**Apa kekurangan yg ingin diatasi?**

sebagai dasar permohonan surat sudah di ketahui oleh perangkat Ketua RT

**Jelaskan solusi yg diinginkan**

![Untitled](https://user-images.githubusercontent.com/87891152/126859999-f485619c-2c49-4ad4-8583-322922b501df.jpg)

**Comment by eddieridwan** [comment]
@s3lv4ng jelaskan persisnya di surat mana diperlukan, karena tentunya permintaan anda tidak berlaku pada setiap jenis surat. Ketahui bahwa desa dapat mengubah setiap surat keterangan sesuai kebutuhan desa. Jadi sebagai alternatif lain, anda ubah saja surat sesuai kebutuhan.

**Comment by s3lv4ng** [comment]
siap bang tq
