### ISSUE TITLE
Tampilkan ketentuan layanan di Info Desa > Layanan Pelanggan

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#4339]
**Apa kekurangan yg ingin diatasi?**

Saat ini di Info Desa > Layanan Pelanggan belum disediakan dokumentasi ketentuan masing2 layanan yg diambil desa. Dokumentasi tersebut penting sebagai informasi bagi desa apa saja hak dan kewajibannya terkait layanan yg diambil. Misalnya, untuk langganan Premium, perlu ada dokumentasi yg menjelaskan bahwa langganan tersebut tidak termasuk dukungan install/update, dilarang untuk membagi ke pihak ketiga, dstnya.

**Jelaskan solusi yg diinginkan**

OpenSID menerima dokumentasi ketentuan layanan dari aplikasi Layanan OpenDesa, dan menampilkan ketentuan tersebut di menu Info Desa > Layanan Pelanggan.

**Untuk versi OpenSID mana**

v21.07-premium

**Informasi tambahan**

**Comment by afa28** [comment]
Sudah digabung ke r`ilis-dev` dan `master`
