### ISSUE TITLE
Penambahan tipe user untuk kadus

### ISSUE THREAD

**Issue by cucu02** [OpenSID/OpenSID#4341]
**Apa kekurangan yg ingin diatasi?**
Saat ini kadus hanya bisa diberikan akun tipe operator dan hal tersebut membuat kadus bisa melihat data kependudukan warga yang berada diluar wilayahnya.

**Jelaskan solusi yg diinginkan**
Diperlukan Adanya pembatasan hak akses kadus terbatas pada warganya sendiri dengan izin tulis, baca dan rubah yang bisa diberikan atau dicabut oleh admin. Model hak akses tersebut bisa dilihat pada aplikasi perpustalaan SLiMS slims.web.id. 

**Untuk versi OpenSID mana**

**Informasi tambahan**

**Comment by afa28** [comment]
Sudah ada di fitur premium untuk pengaturan hak akses.

**Comment by cucu02** [comment]
Benar fitur tersebut sudah ada akan tetapi kadus dusun A masih bisa Read dan Update  warga Dusun lain
