### ISSUE TITLE
[BUG] Data  di ID BDT tidak dapat di filter antara sudah terisi dan belum mengisi (atau ketika klik belum mengisi, data yg muncul masih data total)

### ISSUE THREAD

**Issue by muhtar-coder** [OpenSID/OpenSID#4343]
**Jelaskan error yg dialami**

Data hasil isian pada Statistik RTM/ID BDT tidak dapat di pisah/di filter antara yang sudah terisi dan yang belum mengisi sehingga data tetap berkumpul menjadi satu jumlah total

**Cara untuk mereplikasi errornya**

**Hasil yg diharapkan**

hasil sesuai filter terisi dan belum terisi

**Tampakan layar dan log error**

1. hasil pengisian 

![image](https://user-images.githubusercontent.com/55665526/127779108-1f276990-379d-4434-a647-f73c89ce37ed.png)

2. jumlah belum mengisi masih merupakan jumlah total

![image](https://user-images.githubusercontent.com/55665526/127779037-82432556-1547-4891-87e5-4663f3aad8c0.png)

**Versi OpenSID**

21.08 premium

**Tema Yg Digunakan**

**Informasi tambahan**

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melaui PR: https://github.com/OpenSID/premium/pull/337

**Comment by muhtar-coder** [comment]
Terima kasih...

Pada tanggal Min, 15 Agu 2021 21.42, Agung Sugiarto <
***@***.***> menulis:
