### ISSUE TITLE
Error pada menu buku administratif desa -> administrasi lainya

### ISSUE THREAD

**Issue by nurisakbar** [OpenSID/OpenSID#4345]
**Jelaskan error yg dialami**
muncul pesan Unable to load the requested file: Bumindes_lain/lain/content_inventaris.php.
error ini ditemukan pada rilis umum tapi tidak pada rilis premium, karena pada rilis premium menu administrasi lain nya tidak ada.

**Cara untuk mereplikasi errornya**

1. login ke halaman administrator
2. Klik menu buku administrasi desa
3. klik administrasi lain nya
4. Lihat error

**Hasil yg diharapkan**
muncul notifikasi Akan dikembangkan di rilis Premium. Hubungi OpenDesa untuk informasi lebih lanjut. seperti pada buku induk penduduk.

**Tampakan layar dan log error**
<br>
![alt text](https://i.ibb.co/cNNgdS9/Screen-Shot-2021-08-02-at-23-16-30.png)

**Versi OpenSID**
Versi OpenSID 21.08. PHP versi 7.4.2. | rilis umum

**Tema Yg Digunakan**
-

**Informasi tambahan**
-

**Comment by ai-skematik** [comment]
menu administrasi lainnya di premium sudah di hapus.,

**Comment by Zoel-WB** [comment]
Aku punya cuma seperti ini fiturnya :
![image](https://user-images.githubusercontent.com/64481641/127909047-4e0aaef0-430b-44c0-beb7-2b25da5db6ef.png)

**Comment by nurisakbar** [comment]
@ai-skematik, @Zoel-WB oke berarti memang ada rencana untuk di hapus pada next release umum ya ?

**Comment by eddieridwan** [comment]
Rilis umum v21.09 dipastikan seperti dijelaskan di https://github.com/OpenSID/OpenSID/wiki/Rilis-Umum-Yang-Akan-Datang. Tidak tercatat rilis premium di mana penyesuaian menu Buku Administrasi Desa dilakukan. Perlu dicari melalui commit dari git history (bisa juga lihat dari migrasi). Tetapi masalah di issue ini sangat mungkin hanya ada yg terlewat pada waktu melakukan penggabungan rilis premium 21.01-premium ke 21.08 -- terutama pada proses conflict resolution. 

cc @afa28 @agungsugiarto

**Comment by afa28** [comment]
Belum tersedia di rilis umum, akan digabung ke rilis umum di versi Rilis Umum v21.10 (v21.03-premium)
