### ISSUE TITLE
[BUG] Jangan tampilkan cetak kk untuk penduduk lepas (kk null)

### ISSUE THREAD

**Issue by afa28** [OpenSID/OpenSID#4348]
**Jelaskan error yg dialami**

Cetak kk di layanan mandiri untuk penduduk lepas bisa dilakukan dengan menampilkan semua data penduduk lepas.

**Cara untuk mereplikasi errornya**

Jangan beri akses bagi penduduk lepas untuk cetak kk

**Hasil yg diharapkan**

**Tampakan layar dan log error**

**Versi OpenSID**

**Tema Yg Digunakan**

**Informasi tambahan**

**Comment by agungsugiarto** [comment]
Sudah mas
