### ISSUE TITLE
[Penduduk] Tambah Pencarian Spesifik Penduduk

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#4350]
**Apa kekurangan yg ingin diatasi?**

Saat ini sedikit kesulitan mengidentifikasi data penduduk yang telah melakukan input ID Card ke kolom Tag ID

**Jelaskan solusi yg diinginkan**

Adanya pengaturan atau filter khusus data penduduk yang sudah melakukan pengisian Tag ID.

**Apakah ada alternatif lain**

Bisa ditambah pada Menu Pencarian Spesifik.
<img width="468" alt="2021-08-04_10h39_47" src="https://user-images.githubusercontent.com/46939846/128118845-6c2d026d-0d16-4f82-82eb-4e2c62f2e0bd.png">

Atau cara lain yang memungkinkan dapat menampilkan tabel penduduk khusus yang sudah melakukan input ID KTP pada kolom Tag ID melalui URL.

**Comment by ai-skematik** [comment]
sekalian sama statistik

**Comment by andifahruddinakas** [comment]
Tambahan pencarian spesifik : 
1. tag id
2. suku
3. bpjs
4. kk level
5. jenis kelamin
6. kewarga negaraan
7. akseptor kb
8. e ktp
9. status rekam
10. dll

**Comment by scqolbu24** [comment]
sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/584
