### ISSUE TITLE
[Suplemen] Slug Data Suplemen

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#4351]
**Apa kekurangan yg ingin diatasi?**

Agar tidak muncul ID suplemen sehingga pengunjung dapat hanya dengan mengganti ID saja (untuk coba-coba), dapat dibuat Slug untuk LINK Data Suplemen. 

<img width="960" alt="2021-08-04_11h43_29" src="https://user-images.githubusercontent.com/46939846/128123462-c73738d0-8e50-4eee-9549-55afb5b0865f.png">

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melalui pr https://github.com/OpenSID/premium/pull/479
