### ISSUE TITLE
[Database] Tambah fitur tag ktp di format impor data penduduk excel

### ISSUE THREAD

**Issue by Wahyuwidodo48** [OpenSID/OpenSID#4353]
**belum ada kolom tag ktp di impor data penduduk excel**

**menambah kolom Tag ID Card di format impor data penduduk**
![contoh solusi](https://user-images.githubusercontent.com/75907117/128283753-dd6202e6-eb19-4b72-945b-3b20a0f47018.png)

**Fitur ini diusulkan untuk versi v21.09**

**Comment by andifahruddinakas** [comment]
Setelah PR issue https://github.com/OpenSID/OpenSID/issues/4369 digabung baru dilanjutkan mengerjakan issue ini agar konsisten.

**Comment by FirlianiF** [comment]
sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/599
