### ISSUE TITLE
[BUG] Tambah Data Adminduk Level Operator

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#4354]
**Jelaskan error yg dialami**

Saat ini untuk level operator, tidak terdapat menu tambah data terkait Buku Administrasi Umum.

Buku Peraturan Desa
Buku Keputusan Kepala Desa
Buku Inventaris dan Kekayaan Desa
Buku Ekspedisi
Buku Lembaran Desa dan Berita Desa

**Hasil yg diharapkan**

Level operator dapat juga menambah buku administrasi umum.

**Comment by afa28** [comment]
apakah ada yg lain lg pak @ariandii??? agar issue ini tdk berluang.

**Comment by afa28** [comment]
Pak @ariandii, bisa cek https://berputar.opensid.or.id/surat_keluar

Login: 
user : operator
pass : Operator2021*

Sy cek sudah memiliki hak akses.

**Comment by ariandii** [comment]
https://berputar.opensid.or.id/dokumen_sekretariat/peraturan_desa/3

https://berputar.opensid.or.id/dokumen_sekretariat/peraturan_desa/2

https://berputar.opensid.or.id/bumindes_inventaris_kekayaan

https://berputar.opensid.or.id/ekspedisi

https://berputar.opensid.or.id/lembaran_desa

silakan di cek 5 menu tersebut di atas. menggunakan level operator.

apakah bisa tambah data?

**Comment by Zoel-WB** [comment]
https://berputar.opensid.or.id/dokumen_sekretariat/peraturan_desa/3

https://berputar.opensid.or.id/dokumen_sekretariat/peraturan_desa/2

Untuk level Operator cuma yng bisa hanya mengunduh dokumen
![image](https://user-images.githubusercontent.com/64481641/129022938-6feb9390-8332-4495-ade1-b42a047878f0.png)

**Comment by Zoel-WB** [comment]
Ekpesi cuma dapat menggantikan tanggal pengiriman dan menghapus dokumen serta meng-upload berkas baru dan menambah keterangan
![image](https://user-images.githubusercontent.com/64481641/129023728-ffc669ff-f846-445f-ad43-78f250828cd4.png)

**Comment by Zoel-WB** [comment]
Fitur ini bisa di edit dan disimpan secara keseluruhan
![image](https://user-images.githubusercontent.com/64481641/129024319-5c6fcff8-4d18-4072-a947-f9a46195f003.png)

**Comment by afa28** [comment]
> https://berputar.opensid.or.id/dokumen_sekretariat/peraturan_desa/3
> 
> https://berputar.opensid.or.id/dokumen_sekretariat/peraturan_desa/2
> 
> https://berputar.opensid.or.id/bumindes_inventaris_kekayaan
> 
> https://berputar.opensid.or.id/ekspedisi
> 
> https://berputar.opensid.or.id/lembaran_desa
> 
> silakan di cek 5 menu tersebut di atas. menggunakan level operator.
> 
> apakah bisa tambah data?

- [x] https://berputar.opensid.or.id/dokumen_sekretariat/peraturan_desa/3
- [x] https://berputar.opensid.or.id/dokumen_sekretariat/peraturan_desa/2
- [x] https://berputar.opensid.or.id/bumindes_inventaris_kekayaan (hanya menampilkan)
- [x] https://berputar.opensid.or.id/ekspedisi (hanya menampilkan, dan ubah)
- [x] https://berputar.opensid.or.id/lembaran_desa (hanya menampilkan, dan ubah)

**Comment by agungsugiarto** [comment]
Pak @ariandii, untuk issue ini mohon dibatasi

terkait ini mohon untuk dibuatkan issue terpisah.

> bung @afa28
> apakah bisa sekaligus disesuaikan untuk urutan tabel.
> Buku Peraturan Desa, Buku Keputusan Kepala Desa, dll. Agar hasil input terakhir berada pada baris nomor 1.

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melalui PR: https://github.com/OpenSID/premium/pull/353
