### ISSUE TITLE
[BUG] Tema penampilan modul web Kosong

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#4357]
**Jelaskan error yg dialami**

<img width="960" alt="2021-08-07_11h44_44" src="https://user-images.githubusercontent.com/46939846/128588234-af022069-61c9-4942-91a7-0a4212cf7b58.png">

**Cara untuk mereplikasi errornya**
Langkah untuk mereplikasi error yg dialami, misalnya:
1. Pergi ke halaman 'https://berputar.opensid.or.id/web'
2. Klik tombol 'icon gear pojok kanan atas'
3. Pada layar 'pilihan Web Theme kosong'

**Hasil yg diharapkan**

Sebagaimana mestinya.

**Comment by afa28** [comment]
Awalnya pengaturan yg ada dipojok kanan atas itu diperuntukkan saat ini hanya modul pelanggan, namun krn menggunakan variable global maka semua modul ikut terpengaruh. Perbaikan akan dilakukan dengan menambahkan pengaturan tsb hanya pada modul pelanggan saja. Untuk modul lainnya akan dikerjakan melalui issue https://github.com/OpenSID/OpenSID/issues/4007

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melalui PR: https://github.com/OpenSID/premium/pull/348
