### ISSUE TITLE
Error 404 saat menekan tombol "Home" pada Fitur Cetak Surat Dengan Template Surat Berada dalam Folder Desa [BUG] 

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#4358]
**Jelaskan error yg dialami**
--> Saat menekan tombol Home pada halaman atau fitur Cetak Surat dengan tempate surat tambahan yang berada dalam folder Desa/Template Surat, halaman tidak kembali ke Beranda secara normal akan tetapi muncul halaman error 404
 
Harap tidak melaporkan masalah instal OpenSID. Masalah pada waktu install harap ditanyakan di https://www.facebook.com/groups/OpenSID atau di https://t.me/joinchat/SI0GWHeqKT39Gxhh, karena terkait sistem masing2 pengguna. 

Berikan keterangan yg jelas dan singkat mengenai error yg dialami. 
Pastikan error ini juga ditemukan di https://demo.opensid.or.id (untuk RIlis Umum) atau di https://berputar.opensid.or.id (untuk RIlis Premium).
--> OpenSID 21.08 Premium

**Cara untuk mereplikasi errornya**
1. Buka Fitur Cetak Surat
2. Pilih salah satu surat tambahan yang template suratnya di letakkan dalam Folder Desa...
3. Klik Tombol "Home" 

Langkah untuk mereplikasi error yg dialami, misalnya:
1. Pergi ke halaman '...'
2. Klik tombol '....'
3. Gulir ke bawah sampai '....'
4. Lihat error
-->

**Hasil yg diharapkan**
--> Supaya tidak lagi terjadi error dan halaman kembali ke beranda saat menekan tombol home atau tombol kembali ke beranda lainnya.
Berikan keterangan yg jelas dan singkat apa hasil yg diharapkan.
-->
![image](https://user-images.githubusercontent.com/64481641/128622463-fa32b1bb-5275-41bd-934f-8f69b2a56f61.png)
![image](https://user-images.githubusercontent.com/64481641/128622468-372b29a2-d762-4ac1-bbc4-726706b1f485.png)

**Tampakan layar dan log error**
![image](https://user-images.githubusercontent.com/64481641/128622491-1316157d-a866-470d-96b3-cd15cf337050.png)

Lampirkan tampakan layar yg menjelaskan permasalahan.
Lampirkan isi file di folder `logs` atau tampakan error di console inspector browser.
-->
![image](https://user-images.githubusercontent.com/64481641/128622547-cc15395c-6fa4-4ac2-8ed3-4ddf1bb4bd21.png)
![image](https://user-images.githubusercontent.com/64481641/128622638-225ca600-1406-4a59-9f7c-6ab27f30df74.png)

**Versi OpenSID**

**Tema Yg Digunakan**

**Informasi tambahan**

**Comment by ariandii** [comment]
Info Tambahan:
Hal tersebut di atas terjadi hanya jika berada pada halaman buat Surat Tambahan oleh Desa.

Namun jika surat bawaan sistem, tombol Home normal.

**Comment by balongbesuk** [comment]
kl d folder desa desa sendiri yang wajib update scriptnyajuga desa

contoh scriptnya d file .php surat bawaan opensid

**Comment by afa28** [comment]
Sudah di perbaiki di commit cdac4c347ddc5b04d23c654f5fb20a02165d633f dan a8e8b244c71b4102dc9b3297ed753c374703a329. Dan sy cek kembali untuk template-surat bawaan sudah tdk ada masalah. Yg perlu diperbaiki yakni pengguna perlu menyesuaikan template-surat ubah desa dengan template-bawaan opensid jika ada perubahan.
