### ISSUE TITLE
UBAH URL LAYANAN MANDIRI DARI MANDIRI_WEB KE MANDIRI LOGIN

### ISSUE THREAD

**Issue by nidaislamika** [OpenSID/OpenSID#4359]
Cara ubah url layanan mandiri bagaimana ya, dari mandiri_web ke mandiri login, melalui cpanel file apa yang harus diubah, terimakasih

**Comment by eddieridwan** [comment]
@nidaislamika issue digunakan untuk melaporkan bugs atau permintaan perbaikan.
Harap tidak menggunakan issue untuk bertanya penggunaan OpenSID, ataupun cara untuk mengoprek OpenSID. SIlakan bertanya di https://www.facebook.com/groups/OpenSID atau grup Telegram terkait OpenSID.

Issue ini akan ditutup.
