### ISSUE TITLE
[BUG] SDGs error

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#4360]
**Jelaskan error yg dialami**

Error pada waktu menampilkan halaman SDGs di web.
![sdg-1](https://user-images.githubusercontent.com/249563/128660655-e264a76b-d0d9-4523-88e7-2d308234ad23.jpg)

**Cara untuk mereplikasi errornya**

1. Tambahkan menu status yg mengarah ke halaman statis lainnya > SDGs Desa
2. Buka web dan klik menu SDGs Desa yg dibuat di (1).
3. Akan error

**Hasil yg diharapkan**

Tidak error. Kalau portal Kemendes bermasalah, tampilkan pesan yg menjelaskan.

**Versi OpenSID**

v21.08-premium

**Tema Yg Digunakan**

natra

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melalui PR: https://github.com/OpenSID/premium/pull/349
