### ISSUE TITLE
[BUG] Tidak bisa import responden di data analisis

### ISSUE THREAD

**Issue by KambutGoro** [OpenSID/OpenSID#4362]
Saat mengakses menu analisis, saya punya data responden di yang saya download melalui aplikasi serupa. saya sesuaikan dengan format yang ada di OpenSid. akan tetapi tidak bisa melakukan import data responden.

**Cara untuk mereplikasi errornya**
Langkah untuk mereplikasi error yg dialami, misalnya:
1. Pergi ke halaman 'Analisis'
2. Klik tombol 'Input data sensus/survey'
3. Klik menu import
4. Lihat error "Data gagal disimpan"
-->

**Hasil yg diharapkan**
bisa mengimport data responden karena survey sudah dilakukan di aplikasi serupa.

**Versi OpenSID**

Error ini terjadi di rilis/versi berapa: Rilis umum (mis. v21.07) 

**Tema Yg Digunakan**
tema default kare saya langsung direct ke siteman

**Comment by ai-skematik** [comment]
punya sy normal2 saja,, bisa disebutkan aplikasi sejenis yg digunakan apa, supaya lebih muda mereplikasi ,

**Comment by afa28** [comment]
Bisa sertakan contoh impor yg anda gunakan di kasus ini???

**Comment by andifahruddinakas** [comment]
Silahkan di cek kembali di https://berputar.opensid.or.id/
