### ISSUE TITLE
Import Peta Bertype GPX  setelah disimpan layar blank[BUG] 

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#4363]
**Jelaskan error yg dialami**
--> Impor Peta pada fitur Info Desa Peta Wilayah Desa dengan type ke GPX setelah disimpan dan  di buka kembali layar blank;
--> akan tetapi setelah dilakukan migrasi db, peta baru muncul.

Harap tidak melaporkan masalah instal OpenSID. Masalah pada waktu install harap ditanyakan di https://www.facebook.com/groups/OpenSID atau di https://t.me/joinchat/SI0GWHeqKT39Gxhh, karena terkait sistem masing2 pengguna. 

Berikan keterangan yg jelas dan singkat mengenai error yg dialami. 
Pastikan error ini juga ditemukan di https://demo.opensid.or.id (untuk RIlis Umum) atau di https://berputar.opensid.or.id (untuk RIlis Premium).
--> Opensid Premium 21.08

**Cara untuk mereplikasi errornya**
1. Buka Fitur  Info Desa --> Indentitas Desa.
2. Pilih Taskbar Peta Wilayah Desa.
3. Coba Lakukan Impor dari Peta yang berjenis GPX lalu simpan.
4. Kemudian Coba Buka Kembali Peta Wilayah Desa (Layar Peta Blank)
![image](https://user-images.githubusercontent.com/64481641/128964461-210040cd-6b41-468a-8d1e-4fda2c160118.png)

5.  Kemudian Buka Pengaturan ---> Database ----> lakukan Migrasi DB, peta gpx yg diimpor tadi baru muncul secara normal
![image](https://user-images.githubusercontent.com/64481641/128964548-edecaa20-9815-497e-9d96-8637ad7f67fb.png)

Langkah untuk mereplikasi error yg dialami, misalnya:
1. Pergi ke halaman '...'
2. Klik tombol '....'
3. Gulir ke bawah sampai '....'
4. Lihat error
-->

**Hasil yg diharapkan**
--> Bagaimana caranya supaya setelah di import dari peta jenis GPX maupun jenis lainnya setelah disimpan peta langsung jadi dan layar tidak blank  dan tidak harus atau mesti melakukan Migrasi DB dulu peta baru muncul, hal ini bila terjadi di pembuatan peta Area atau pun peta persil akan merepotkan karena setiap setelah di impor untuk memunculkan petanya harus di migrasi db dulu baru petanya dapat dimunculkan akan terjadi berulang setiap setelah impor.
Berikan keterangan yg jelas dan singkat apa hasil yg diharapkan.
-->

**Tampakan layar dan log error**
--> Log Error-nya tidak ada pesan yg ditampilkan yg menunjukkan sebagai adanya error.

Lampirkan tampakan layar yg menjelaskan permasalahan.
Lampirkan isi file di folder `logs` atau tampakan error di console inspector browser.
-->

**Versi OpenSID**
 Error ini terjadi di rilis/versi berapa: Rilis  v21.08 dan di OpenSID dev Berputar....
[OpenSID.zip](https://github.com/OpenSID/OpenSID/files/6965689/OpenSID.zip)

**Tema Yg Digunakan**

**Informasi tambahan**

**Comment by agungsugiarto** [comment]
Sudah siperbaiki melalui PR: https://github.com/OpenSID/premium/pull/351
