### ISSUE TITLE
Data feeds artikel di urutkan berdasarkan artikel terbaru

### ISSUE THREAD

**Issue by agungsugiarto** [OpenSID/OpenSID#4366]
**Apa kekurangan yg ingin diatasi?**

Di OpenDK, berita desa kecamatan inginnya diurut berdasarkan tanggal. 

**Jelaskan solusi yg diinginkan**

Urut data feeds artikel berdasarkan tanggal. 

**Untuk versi OpenSID mana**

v21.10-premium

**Informasi tambahan**

Di OpenDK, perlu juga diurut keseluruhan berita dari kumpulan desa yg mengirim berita

**Comment by eddieridwan** [comment]
Sdh dicommit ke `rilis-dev`. RSS feed juga sudah disesuaikan supaya lolos validasi di https://validator.w3.org/feed/#validate_by_input
