### ISSUE TITLE
Tambahkan halaman khusus pembangunan

### ISSUE THREAD

**Issue by afa28** [OpenSID/OpenSID#4368]
**Apa kekurangan yg ingin diatasi?**

Saat ini data pembangunan di tampilkan di peta dan tdk efektif. 

**Jelaskan solusi yg diinginkan**

Perlu dibuatkan halaman khusus untuk pembangunan seperti modul lapak.

**Apakah ada alternatif lain**

**Untuk versi OpenSID mana**

**Informasi tambahan**

**Comment by andifahruddinakas** [comment]
https://github.com/OpenSID/OpenSID/issues/4402
