### ISSUE TITLE
[Database] Impor dan Ekspor Data Suku

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#4369]
**Apa kekurangan yg ingin diatasi?**

Belum bisa melakukan impor database berupa suku.

**Jelaskan solusi yg diinginkan**

Tambahkan impor suku.

**Apakah ada alternatif lain**

**Untuk versi OpenSID mana**

**Informasi tambahan**

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melalui pr https://github.com/OpenSID/premium/pull/481
