### ISSUE TITLE
Sebutan Kepala Desa

### ISSUE THREAD

**Issue by kelbatuix** [OpenSID/OpenSID#437]
mohon dapat membuat settingan config untuk sebutan kepala desa untuk kelurahan sebagaimana sebutan nama jabatan camat. Saat ini yang terdapat di sistem adalah akan berubah otomatis menjadi Kepala Kelurahan, sementara nama jabatan adalah Lurah

**Comment by kelbatuix** [comment]
Mohon ijin sedikit mencoba memahami untuk bertukar pikiran. Bahwa Kelurahan
dan Desa merupakan pemerintahan yg berada di level terendah, namun memiliki
sistem pemerintahan yang berbeda dengan tujuan yg hampir sama. UU No.
6/2014 memberikan penjelasan terkait Pemerintah Desa atau Pemerintah Desa
Adat. Sedangkan Pemerintah Kelurahan penjelasannya masih mengacu pada PP
No. 73/2005.

Dalam UU No. 6/2014 pasal 11 dan 12 menjelaskan terkait perubahan status
dari desa ke kelurahan atau kelurahan ke desa bukan persamaan status.
Dengan demikian yg dimaksud dengan disesuaikan dengan sebutan lokal adalah
beberapa tempat sperti di Papua atau sumbar yg memiliki nama adat. Bukan
kelurahan.

**Comment by afa28** [comment]
Apakah ini masih bermasalah / masih diperlukan??? Kalau tdk, silahkan di close.

**Comment by afa28** [comment]
Duplicate issue #3693
