### ISSUE TITLE
>>>>>> Link Gambar Wiki Peta

### ISSUE THREAD

**Issue by nurisakbar** [OpenSID/OpenSID#4370]

**Comment by eddieridwan** [comment]
[berkas pengujian aplikasi esurat.pdf](https://github.com/OpenSID/OpenSID/files/7162669/berkas.pengujian.aplikasi.esurat.pdf)


![tte-2](https://user-images.githubusercontent.com/249563/132939750-8702ef5a-60b3-4876-a45b-27ad10a72d1f.jpeg)
