### ISSUE TITLE
Tambah Checklist dan Tombol Hapus Log File

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#4371]
**Apa kekurangan yg ingin diatasi?**

<img width="960" alt="2021-08-12_17h10_39" src="https://user-images.githubusercontent.com/46939846/129179742-06673cf7-a1f5-49c6-8ea7-69a7f3104a9f.png">

**Jelaskan solusi yg diinginkan**

Tersedia tombol untuk menghapus sebagian atau seluruh Log File.

**Comment by cwicaksono** [comment]
> **Apa kekurangan yg ingin diatasi?**
> 
> <img alt="2021-08-12_17h10_39" width="960" src="https://user-images.githubusercontent.com/46939846/129179742-06673cf7-a1f5-49c6-8ea7-69a7f3104a9f.png">
> 
> **Jelaskan solusi yg diinginkan**
> 
> Tersedia tombol untuk menghapus sebagian atau seluruh Log File.

apakah ini ingin ditambahkan tombol untuk bisa hapus sebagian atau seluruh log file?

**Comment by afa28** [comment]
> > **Apa kekurangan yg ingin diatasi?**
> > <img alt="2021-08-12_17h10_39" width="960" src="https://user-images.githubusercontent.com/46939846/129179742-06673cf7-a1f5-49c6-8ea7-69a7f3104a9f.png">
> > **Jelaskan solusi yg diinginkan**
> > Tersedia tombol untuk menghapus sebagian atau seluruh Log File.
> 
> apakah ini ingin ditambahkan tombol untuk bisa hapus sebagian atau seluruh log file?

yg di tandai (cek list)

**Comment by andifahruddinakas** [comment]
Sudah digabung ke `RILIS PREMIUM`
