### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by akbarmunoo** [OpenSID/OpenSID#4372]
**Jelaskan error yg dialami**

Formulir permohonan surat mandiri tidak tampil 

**Cara untuk mereplikasi errornya**

Langkah untuk mereplikasi error yg dialami, misalnya:
1. Pergi ke halaman ' Layanan Mandiri'
2. Klik tombol ' Permohonan Surat'
3. Gulir ke bawah sampai 'pilih dan isi syarat surat'
4. eror : formulir tidak tampil

**Hasil yg diharapkan**

**Tampakan layar dan log error**

**Versi OpenSID**

Error ini terjadi di rilis/versi berapa: 21.08

**Tema Yg Digunakan**

natra v4.5

**Informasi tambahan**

![Untitled-3](https://user-images.githubusercontent.com/88810213/129201748-d3d95ea2-acf7-457b-9af1-ad9c3967c669.jpg)

**Comment by afa28** [comment]
Duplicate https://github.com/OpenSID/OpenSID/issues/4373
