### ISSUE TITLE
Access level to Permohonan_surat::$cek_anjungan must be public (as in class Mandiri_Controller) /var/www/webdesa/opensid/donjo-app/controllers/Permohonan_surat.php 0 [BUG] 

### ISSUE THREAD

**Issue by RTechnoS** [OpenSID/OpenSID#4373]
saya tidak tau ini bug atau masalah di pc saya. Ini terjadi saat saya ingin mengirim permohonan surat lewat layanan mandiri.

laptop debian, apache, php 7.3

**Comment by akbarmunoo** [comment]
> tapi setelah saya ganti di /donjo-app/controllers/Permohonan_surat.php baris 45 "private  $cek_anjungan;" menjadi "public  $cek_anjungan;" nggak error lagi

Berhasil, terimakasih @RTechnoS

**Comment by afa28** [comment]
> tapi setelah saya ganti di /donjo-app/controllers/Permohonan_surat.php baris 45 "private $cek_anjungan;" menjadi "public $cek_anjungan;" nggak error lagi

Duplikasi variable, private $cek_anjungan; tdk perlu didefinisikan lg.

**Comment by afa28** [comment]
Sdh digabung ke `master`.
