### ISSUE TITLE
[Keluarga] ID BDT per anggota keluarga

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#4377]
**Apa kekurangan yg ingin diatasi?**

**Jelaskan solusi yg diinginkan**

**Apakah ada alternatif lain**

**Untuk versi OpenSID mana**

**Informasi tambahan**

**Comment by eddieridwan** [comment]
@afa28 sebaiknya tidak diterapkan sebelum mengetahui secara jelas acuan peraturannya.

Menurut https://dinsos.palangkaraya.go.id/mengenal-lebih-dekat-tentang-data-terpadu-kesejahteraan-sosial-dtks/, sasaran DTKS (penerus BDT) utamanya adalah `keluarga`, di mana yg dimaksud bukan `keluarga` dari definisi Dukcapil melainkan konsep `rumah tangga` yg diterapka di OpenSID.

Jadi saat ini pengertian ID BDT adalah ID yg diberikan pada rumah tangga yg ada di OpenSID. Semua orang yg merupakan anggota suatu rumah tangga akan memiliki ID BDT yg sama.

Jika ada kasus di mana seorang ternyata mempunyai ID BDT berbeda, maka orang itu bukan anggota rumah tangga tersebut, melainkan harus dimasukkan ke rumah tangga yg memiliki ID BDT tersebut. 

Yaitu, ID BDT tetap merupakan atribut rumah tangga, bukan individu penduduk. Semua penduduk yg mempunyai ID BDT sama adalah anggota rumah tangga yg sama. 

Harap tidak menerapkan issue ini, kecuali kalau ada yg bisa secara jelas dan pasti memberi acuan yg mengatakan bahwa ID BDT diberikan kepada perorangan. Dan kalau demikian, apakah ID BDT harus unik, seperti halnya NIK.

**Comment by eddieridwan** [comment]
Walaupun permintaannya secara literal bersifat rancu, tetap perlu dipelajari apa latar belakang/masalah yg dialami. Dan kemudian mengubah issue ini supaya bisa mengatasi masalah yg dihadapi. Dalam kasus issue itu, masalahnya sepertinya berawal dari dinamika perubahan keanggotaan keluarga (Dukcapil) dan tenggang waktu penerbitan KK baru, sehingga timbul kasus di mana perorangan dalam suatu keluarga (Dukcapil) mempunyai ID BDT yg berbeda.

Hal ini secara konsep tidak bermasalah, karena anggota keluarga (Dukcapil) bisa merupakan anggota rumah tangga (Kemsos) yg berbeda.

Jadi, untuk memudahkan, yg perlu dilihat adalah solusi untuk memudahkan seorang penduduk untuk dicatat pada rumah tangga (Kemsos dgn ID BDT unik) yang berbeda. (edited)

**Comment by WAHYUDIK** [comment]
apa mungkin yang dimaksud @afa28 adalah ID ARTBDT?yakni setiap anggota keluarga yang sudah mempunyai ID BDT maka anggotanya mempunyai nomor yang berbeda. contoh data sebagai berikut:
![image](https://user-images.githubusercontent.com/31026980/131209149-7d6b1031-9b95-4ec3-935a-79e2a647921a.png)

adapun nomor ID BDT keluarga tersebut adalah 3512130008001033
sedangkan nomor ID ARTBD untuk kepala keluarga 351213000800103301
sedangkan nomor ID ARTBD untuk istri 351213000800103302
sedangkan nomor ID ARTBD untuk anak 351213000800103303

**Comment by haryandi** [comment]
Saat ini ID BDT / sekarang ID DTKS sudah per anggota keluarga..
