### ISSUE TITLE
[Surat] Surat ubahan desa yg ditambahkan ke opensid tdk tampil jika belum melakukan migrasi

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#4378]
**Apa kekurangan yg ingin diatasi?**

**Jelaskan solusi yg diinginkan**

**Apakah ada alternatif lain**

**Untuk versi OpenSID mana**

**Informasi tambahan**

**Comment by eddieridwan** [comment]
Kalau maksudnya surat yg ditambahkan langsung sebagai subfolder di `desa/template-surat`, alternatif melakukan migrasi adalah:
1. menyediakan fitur di Pengaturan Surat untuk ditambahkan oleh petugas; atau
2. setiap kali membuka Pengaturan Surat atau Cetak Surat membaca folder `desa/template-surat` secara otomatis; atau
3. menyediakan tombol di Pengaturan Surat untuk memutakhirkan daftar surat dengan membaca folder `desa/template-surat`.

Mungkin opsi 3 yg paling cocok, sebagai pengganti migrasi.

**Comment by andifahruddinakas** [comment]
> Kalau maksudnya surat yg ditambahkan langsung sebagai subfolder di `desa/template-surat`, alternatif melakukan migrasi adalah:
> 
> 1. menyediakan fitur di Pengaturan Surat untuk menambahkan setiap surat baru oleh petugas; atau
> 2. setiap kali membuka Pengaturan Surat atau Cetak Surat membaca folder `desa/template-surat` secara otomatis; atau
> 3. menyediakan tombol di Pengaturan Surat untuk memutakhirkan keseluruhan daftar surat dengan membaca folder `desa/template-surat`. Termasuk menghapus surat ubahan desa yg sudah tidak ada lagi di folder `desa-template-surat`.
> 
> Sepertinya opsi 3 yg paling cocok, sebagai pengganti migrasi.

Dari PR https://github.com/OpenSID/premium/pull/501 menggunakan solusi 3 namun tanpa menggunakan tombol (menggunakan cara point 2)
