### ISSUE TITLE
[Covid19] Perlu ditambahkan pendataan untuk warga local di modul siaga covid19

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#4379]
**Apa kekurangan yg ingin diatasi?**

**Jelaskan solusi yg diinginkan**

**Apakah ada alternatif lain**

**Untuk versi OpenSID mana**

**Informasi tambahan**

**Comment by eddieridwan** [comment]
Saat ini, warga lokal sudah bisa didata di modul Siaga Covid19. Mungkin yg perlu dilihat hanya menyesuaikan formnya, sehingga kalau mendata warga local tidak akan menanyakan isian terkait mudik.
