### ISSUE TITLE
Error artikel jika isi artikel rata tengah, rata kanan kiri

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#4380]
**Apa kekurangan yg ingin diatasi?**

**Jelaskan solusi yg diinginkan**

**Apakah ada alternatif lain**

**Untuk versi OpenSID mana**

**Informasi tambahan**

**Comment by afa28** [comment]
Untuk panduan:
1. Buat Artikel
2. Simpan
3. Beberapa saat kemudian, edit indentasi
4. Simpan
5. Keluar error 403
——
Solusinya :
1. Masuk cPanel
2. cari pilihan Modsecurity
3. Pilih domain
4. klik Off (kalau semula On)

**Comment by afa28** [comment]
https://github.com/OpenSID/OpenSID/wiki/Tanya-Jawab-Artikel

**Comment by eddieridwan** [comment]
Bung @afa28 mengenai usul di panduan, untuk mematikan modsecurity, sepertinya bukan praktik baik. Sepertinya perlu melacak lebih mendalam sebab masalahnya dan mencari solusi yg lebih aman.
