### ISSUE TITLE
Ketika membuat surat dengan tag id card EKTP penduduk tidak ditampilkan dengan benar

### ISSUE THREAD

**Issue by hendriendric** [OpenSID/OpenSID#4381]
### Bagaimana alurnya sampai muncul masalah?
Akan membuat surat dengan tag id card tidak menampilkan penduduk yang benar

### Seperti apa yang diharapkan?
Ketika menempel ktp menampilkan penduduk yang benar

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 21.08
| Versi PHP        | 7
| System operasi   | windows 10

**Comment by afa28** [comment]
Fungsi pencarian menggunakan tag_id di rilis umum mmang belum disediakan. Bisa lihat di https://github.com/OpenSID/OpenSID/wiki/Rilis-Umum-Yang-Akan-Datang.

silahkan dibuka kembali jika bermasalah.
