### ISSUE TITLE
Tempilan Laporan Abdes Berantakan Pada Halaman Peta

### ISSUE THREAD

**Issue by nurisakbar** [OpenSID/OpenSID#4383]
**Jelaskan error yg dialami**
Tampilan laporan Apdes berantakan pada halaman peta . hanya muncul 1/2 dari luas pop up informasi

![Screen Shot 2021-08-17 at 11 30 43](https://user-images.githubusercontent.com/5483330/129664094-3d8457f8-393b-49ce-b327-69fad055b3d8.png)

sebaiknya tampil full seukuran luas pop up yang muncul.

https://berputar.opensid.or.id/peta

**Cara untuk mereplikasi errornya**
1. akses halaman https://berputar.opensid.or.id/peta
2. klik/ centang peta wilayah desa
3. klik grafik keuangan

**Hasil yg diharapkan**
Tampilan nya rapi

**Tampakan layar dan log error**
-

**Versi OpenSID**
Versi 21.08-premium-beta02

**Tema Yg Digunakan**
-

**Comment by afa28** [comment]
> **Jelaskan error yg dialami**
> Tampilan laporan Apdes berantakan pada halaman peta . hanya muncul 1/2 dari luas pop up informasi
> 
> ![Screen Shot 2021-08-17 at 11 30 43](https://user-images.githubusercontent.com/5483330/129664094-3d8457f8-393b-49ce-b327-69fad055b3d8.png)
> 
> sebaiknya tampil full seukuran luas pop up yang muncul.
> 
> https://berputar.opensid.or.id/peta
> 
> **Cara untuk mereplikasi errornya**
> 
> 1. akses halaman https://berputar.opensid.or.id/peta
> 2. klik/ centang peta wilayah desa
> 3. klik grafik keuangan
> 
> **Hasil yg diharapkan**
> Tampilan nya rapi
> 
> ## **Tampakan layar dan log error**
> **Versi OpenSID**
> Versi 21.08-premium-beta02
> 
> ## **Tema Yg Digunakan**

Pak @nurisakbar, testing di lakukan di tema bawaan (klasik dan natra).
