### ISSUE TITLE
[BUG] Error log penduduk

### ISSUE THREAD

**Issue by afa28** [OpenSID/OpenSID#4388]
**Jelaskan error yg dialami**

Saat ubah data penduduk akan berhasil dijalankan, namu log penduduk terjadi error.

**Cara untuk mereplikasi errornya**

**Hasil yg diharapkan**

Log error penduduk tdk tampil lg.

**Tampakan layar dan log error**

![photo_2021-08-17_21-52-55](https://user-images.githubusercontent.com/57283157/129754509-9ab58344-26fa-4478-9bbf-98c38a63fd84.jpg)

**Versi OpenSID**

**Tema Yg Digunakan**

**Informasi tambahan**

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melalui PR: https://github.com/OpenSID/premium/pull/363
