### ISSUE TITLE
[IDM] Disable Tombol Perbaharui Status IDM [FITUR] 

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#4389]
**Jelaskan error yg dialami**

Jika status IDM sudah muncul dengan benar di tahun bersangkutan, tombol Perbaharui bisa dibuat disable atau muncul Popup bahwa sudah terupdate saat diklik.

<img width="960" alt="2021-08-23_18h10_43" src="https://user-images.githubusercontent.com/46939846/130437991-a9c69c67-0f17-410b-b3be-3b9ee6459323.png">

**Hasil yg diharapkan**

Status IDM yang sudah muncul normal, akan hilang jika klik perbaharui dalam keadaan web kemendesa sedang down.
Agar hal tersebut tidak terjadi, untuk dapat dihidden saja jika status IDM sudah muncul sesuai kode desa yang ada di identitas desa.

**Comment by andifahruddinakas** [comment]
Tambahkan :
- [ ] jika portal kemendes bermasalah jgn lakukan update cache.
- [ ] pesan jika portal kemendes tdk dpt di akses.
- [ ] tambahkan pengaturan tahun saat buka status desa pertama kali.

https://www.facebook.com/groups/OpenSID/permalink/1929351733896465/

**Comment by agungsugiarto** [comment]
Sudah di fitur premium melalui pr https://github.com/OpenSID/premium/pull/924
