### ISSUE TITLE
Fitur Nomor Registrasi Layanan Mandiri

### ISSUE THREAD

**Issue by AyounkAs** [OpenSID/OpenSID#4391]
**Apa kekurangan yg ingin diatasi?**

Fitur nomor registrasi pada layanan mandiri

**Jelaskan solusi yg diinginkan**

Setiap siapa pun yg menggunakan layanan mandiri baik hp maupun d anjungan akan mendapatkan no reg yg bs d cetak print thermal atau pdf melalui hp sbg tanda bukti saat ingin mengambil surat yg d ajukan.

**Apakah ada alternatif lain**

**Untuk versi OpenSID mana**

Fitur ini diusulkan untuk versi Rilis Premium (mis v21.10-premium)

**Informasi tambahan**

**Comment by andifahruddinakas** [comment]
Sudah di rilis 21.09-premium
