### ISSUE TITLE
[BUG] Kawin Tidak Tercatat Tidak Otomatis Walaupun Tidak Diisi Kolom Nomor Akte Kawin Dan Tanggal Kawin

### ISSUE THREAD

**Issue by sukrimalendra** [OpenSID/OpenSID#4392]
**Jelaskan error yg dialami**

Ketika impor data penduduk melalui menu impor database, di semua data penduduk berubah menjadi status **Kawin Tercatat** walaupun tidak diisi kolom **Nomor Akta Kawin dan Tanggal Kawin**

**Cara untuk mereplikasi errornya**

1. saya mengimpor melalui Impor Database, berikut saya lampirkan file impor 
[penduduk_20_08_2021 sid1.xlsx](https://github.com/OpenSID/OpenSID/files/7052283/penduduk_20_08_2021.sid1.xlsx)
 
![image](https://user-images.githubusercontent.com/30992964/130912577-07bba446-b030-4893-a843-c981647bb341.png)

2. Saya mengimpor format excel sesuai dengan kode dan format yang di download di menu **Impor Database** 
![error kawin tidak tercatat opensid](https://user-images.githubusercontent.com/30992964/130913085-a1e72579-3116-4bb6-b86c-ebd240f5edcb.jpg)

3. Dan hasilnya seperti ini, pada status perkawinan, statusnya **Kawin Tercatat**, padahal saya **tidak mengisi apapun pada kolom Nomor Akta Perkawinan dan Tanggal Perkawinan** 
![error kawin tidak tercatat opensid5](https://user-images.githubusercontent.com/30992964/130913670-9f3c4e6a-a921-4785-ae5d-950baabb6d70.jpg)

**Hasil yg diharapkan**
yang diharapkan tentunya : 

1. Status Kawin agar bisa otomatis menjadi **Kawin Tidak Tercatat** apabila Cell Nomor Akta Perkawinan dan Tanggal Perkawinan **Tidak Diisi** 
2. Status **kawin Tercatat** apabila Cell nomor Akta Perkawinan dan Tanggal Perkawinan **Diisi**

**Tampakan layar dan log error**
tidak ada log eror, proses impor database **berhasil**.

**Versi OpenSID**
Rilis umum 21.08-pasca

**Comment by FirlianiF** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/502
