### ISSUE TITLE
u/ panduan

### ISSUE THREAD

**Issue by afa28** [OpenSID/OpenSID#4397]
### Pelanggan:
![1](https://user-images.githubusercontent.com/57283157/131299484-9441e7f2-6f57-4324-b642-d4f0227fd066.png)
![2](https://user-images.githubusercontent.com/57283157/131299497-43f50b9d-06cd-4256-8344-608c5a6b423e.png)
![3](https://user-images.githubusercontent.com/57283157/131299815-5c75374e-624e-4362-81be-688facd7c8c5.png)
![131299484-9441e7f2-6f57-4324-b642-d4f0227fd066](https://user-images.githubusercontent.com/57283157/132509133-322f040f-c724-4b06-912f-67e047327a5a.png)
![1111](https://user-images.githubusercontent.com/57283157/132509544-1096fd9d-dd20-4333-b1da-9e8381e296ef.png)
![bukti](https://user-images.githubusercontent.com/57283157/132509568-a83e3b51-8dbc-47a4-be5f-755f7bb44b00.png)
![faktur](https://user-images.githubusercontent.com/57283157/132509573-76c70aad-a494-4c71-bd59-73f85eb97dea.png)
![bukti bayar](https://user-images.githubusercontent.com/57283157/132510154-4881c63a-bc31-45db-acc9-233822c965ba.png)
![cetak faktu](https://user-images.githubusercontent.com/57283157/132510189-cb4780ed-a67b-44aa-a150-683eda092790.png)

**Comment by andifahruddinakas** [comment]
### Rencana Pembangunan:
![1](https://user-images.githubusercontent.com/57283157/131300095-078ad6ce-717a-4a27-991b-7a1c654d118b.png)
![2](https://user-images.githubusercontent.com/57283157/131300109-e7f54560-2d58-4280-9587-0198f4065496.png)
![tahun](https://user-images.githubusercontent.com/57283157/132515834-2ccc31f5-1a46-4aaa-bee5-36dc002c7dd8.png)
![cetak unduh](https://user-images.githubusercontent.com/57283157/132515963-5ae55c82-34f5-4418-ba24-af247419ded5.png)
![cetak](https://user-images.githubusercontent.com/57283157/132515976-df50152c-f867-4639-975e-5be4a9cfc874.png)
![tampil](https://user-images.githubusercontent.com/57283157/132515980-1541bb04-2b65-4dea-af5e-b92a2792e978.png)

**Comment by afa28** [comment]
### Penduduk (NIK Sementara):
![1](https://user-images.githubusercontent.com/57283157/131300530-418de859-f465-4e60-899a-b3730b9a6e4c.png)
![2](https://user-images.githubusercontent.com/57283157/131300543-d36cfb8b-ac11-46d1-aa0f-826ffc291fa0.png)
![3](https://user-images.githubusercontent.com/57283157/131300548-8e57417a-32bd-4833-b4a3-a5783001256c.png)

**Comment by afa28** [comment]
### Anjungan:
![1](https://user-images.githubusercontent.com/57283157/131301097-bf463a65-524b-4ee3-a514-8ec4ae18ad01.png)
![2](https://user-images.githubusercontent.com/57283157/131301114-ddeaa5eb-aca8-42ce-999e-95e9a39f78ce.png)

**Comment by afa28** [comment]
### Lembaga:
![1](https://user-images.githubusercontent.com/57283157/131302715-779e6c63-c929-4239-a16e-2a3fcd9bdfc2.png)
![2](https://user-images.githubusercontent.com/57283157/131302728-277e6cad-a047-4443-9ef2-7d836c52710c.png)
![3](https://user-images.githubusercontent.com/57283157/131302735-5e956a04-7427-4034-88ee-d1ae83154d68.png)
![4](https://user-images.githubusercontent.com/57283157/131302741-abeede9c-33d9-4836-a8d6-8d7fde998d27.png)
![5](https://user-images.githubusercontent.com/57283157/131302746-530bb0bf-9a00-41a9-8307-9b92128be23f.png)
![6](https://user-images.githubusercontent.com/57283157/131302749-c6651b7f-e47b-490e-85c2-c477e869d9e2.png)
![7](https://user-images.githubusercontent.com/57283157/131302753-353b343c-e397-442e-96b5-4aebe42173ef.png)
![8](https://user-images.githubusercontent.com/57283157/131302757-df95b4ae-c9b8-43f2-924d-7b44479691a5.png)
![9](https://user-images.githubusercontent.com/57283157/131302763-4050f08c-d8e7-4c26-966e-54078e708f9d.png)
![10](https://user-images.githubusercontent.com/57283157/131302782-b3c1e112-46ee-4b3f-bbfa-93171e7e04c2.png)
![11](https://user-images.githubusercontent.com/57283157/131302790-9bd1c2f3-2777-4282-b1f7-3b45fd9493fd.png)

**Comment by andifahruddinakas** [comment]
![error](https://user-images.githubusercontent.com/57283157/132510689-23214ede-84c1-436e-b668-5b934bbae91c.png)

**Comment by afa28** [comment]
![error](https://user-images.githubusercontent.com/57283157/132510689-23214ede-84c1-436e-b668-5b934bbae91c.png)

**Comment by andifahruddinakas** [comment]
![1111](https://user-images.githubusercontent.com/57283157/132947286-aee189af-14c9-4268-9db4-c12516e52946.png)

**Comment by andifahruddinakas** [comment]
![22222](https://user-images.githubusercontent.com/57283157/132947472-c4268128-4741-4952-9813-15ac0da21374.png)
