### ISSUE TITLE
Peta wilayah hasil impor file tipe .kml tidak tampil di Peta/gis[BUG] 

### ISSUE THREAD

**Issue by ai-skematik** [OpenSID/OpenSID#4399]
**Jelaskan error yg dialami**

**Cara untuk mereplikasi errornya**

1. masuk ke menu info desa > identitas desa > peta wilayah desa
2. impor peta wilayah desa melalui impor gps/kml dengan peta wilayah desa bertipe .kml lalu simpan
3. lalu masuk ke menu pemetaan, tampilkan peta desa., peta yg kita impor td tidak tampil.

**Hasil yg diharapkan**

impor peta bertipe .kml tampil normal di menu pemetaan.
**Tampakan layar dan log error**

**Versi OpenSID**

21.09 Premium

**Tema Yg Digunakan**

**Informasi tambahan**

contoh file tipe .kml
[karyaagung1.zip](https://github.com/OpenSID/OpenSID/files/7081609/karyaagung1.zip)

**Comment by andifahruddinakas** [comment]
[karyaagung1.zip](https://github.com/OpenSID/OpenSID/files/7113729/karyaagung1.zip)

**Comment by agungsugiarto** [comment]
Pak @ai-skematik, @afa28 coba memakai contoh dari berputar 
[OpenSID.zip](https://github.com/OpenSID/OpenSID/files/7113810/OpenSID.zip)

Saya tidak menemukan masalah menggunakan format .kml tersebut, tools online yg saya gunakan untuk convert .gpx ke .kml https://gpx2kml.com/

**Comment by ai-skematik** [comment]
aslinya kml hasil ekspor dr gogle eart pro., bukan data hasil 
 conver gpx ke kml.,

**Comment by ai-skematik** [comment]
tp jika data tersebut di ekspor telebih dahulu ke gpx lalu dimasukan lembalidalam bentuk gpx hasil exporan td jd normal.

**Comment by ai-skematik** [comment]
sy sudah lampirkan contoh file yg bermasalah, untuk dipastikan filenya yg bermasalah atau sistem.

**Comment by agungsugiarto** [comment]
Sepertinya export .kml dari google earth pro tidak mendukung untuk di import ke OpenSID pak, jadi saran saya di export saja ke .gpx

**Comment by Zoel-WB** [comment]
Hasil test Import di Berputar dari type peta kml.
![image](https://user-images.githubusercontent.com/64481641/132200234-16a55c43-fc22-47b9-8a87-b914567dfc04.png)
 
akan tetapi saat 
[Batas Desa.zip](https://github.com/OpenSID/OpenSID/files/7115109/Batas.Desa.zip)
menampilkan di web publik petanya kosong, kejadian ini hanya terjadi di import peta baru dalam rilis opensid saat ini (rilis 21.09 premium)  sedangkan peta hasil import dari opensid sebelumnya tidak ada masalah...
![image](https://user-images.githubusercontent.com/64481641/132200962-d1a50297-6d8d-482c-ba48-f46b36c74c9a.png)
