### ISSUE TITLE
Fitur: menu upload dan insert image pada tinyMCE editor

### ISSUE THREAD

**Issue by happyagung25** [OpenSID/OpenSID#44]
mohon diberikan atau di aktifkan beberapa menu seperti upload dan insert image ke dalam artikel pada editor tinymce

**Comment by eddieridwan** [comment]
Fitur ini tampaknya telah diterapkan di versi SID yang dimiliki https://www.facebook.com/augush.harry. Kalau memiliki script itu, bisa dikirim langsung saja sebagai pull request (https://github.com/eddieridwan/OpenSID/wiki/Panduan-mengirimkan-perubahan-repo-OpenSID).

**Comment by eddieridwan** [comment]
@metalab25 : apakah yg anda maksud fasilitas untuk upload image dari komputer lokal? Seperti yang dijelaskan di [https://www.tinymce.com/docs/configure/file-image-upload/](https://www.tinymce.com/docs/configure/file-image-upload/)?

Anda berminat mencoba menerapkan?

**Comment by metalab25** [comment]
iya benar om

**Comment by MUHAMMADRANGSEL** [comment]
Mohon diprioritaskan mas eddie

**Comment by afa28** [comment]
Sudah ada di `master`
