### ISSUE TITLE
website di blokir kembali

### ISSUE THREAD

**Issue by kelbatuix** [OpenSID/OpenSID#440]
maaf membuat kembali issue ini, karena ternyata semalam saya sudah menghapus aplikasi pada config sebagaimana petunjuknya, namun ketika saya update ke versi terbaru yang tentunya settingan config sama dengan sebelumny. website kembali terkunci. teknisi dari rumah web juga menanyakan kembali apakah ada script yang dapat dianggap sebagai gangguan keamanan selain script config tersebut ya?

**Comment by kelbatuix** [comment]
Setelah di cek dengan tim teknis terdapat kendalanya ada discript iframe, yang berisi : Dodong Priyambodo (dodong@rumahweb.co.id) : <p><iframe src=\\x22https://www.google.co.id/maps?f=q&source=s_q&hl=en&geocode=&q=logandu,+karanggayam&aq=0&oq=logan&sll=-2.550221,118.015568&sspn=52.267573,80.332031&t=h&ie=utf8&hq=&hnear=logandu,+karanggayam,+kebumen,+central+java&ll=-7.55854,109.634173&spn=0.052497,0.078449&z=14&output=embed\\x22 frameborder=\\x220\\x22 marginwidth=\\x220\\x22 marginheight=\\x220\\x22 scrolling=\\x22no\\x22 width=\\x22100%\\x22></iframe></p>

**Comment by eddieridwan** [comment]
Itu script widget peta, dan harusnya tidak ada masalah.

Coba lampirkan screenshot isi file desa/config/config.php. Juga lampirkan screenshot error yang ditampilkan.

**Comment by MUHAMMADRANGSEL** [comment]
Issue ini sebaiknya di closed

**Comment by eddieridwan** [comment]
@kelbatuix apakah ini masih bermasalah? Kalau tidak silakan tutup issue ini.
