### ISSUE TITLE
Tampilkan Pembangunan di halaman lain, sepertihalnya fitur lapak

### ISSUE THREAD

**Issue by WAHYUDIK** [OpenSID/OpenSID#4402]
**Apa kekurangan yg ingin diatasi?**

untuk mempermudah desa dalam menyampaikan informasi tentang program pembangunan atau progres pembangunan, fitur yang ada pada saat ini, untuk menampilkan pembangunan masih menyatu dengan fitur peta.
![image](https://user-images.githubusercontent.com/31026980/131811086-55951739-7602-4ad5-bbb9-60a323700380.png)

**Jelaskan solusi yg diinginkan**

tampilkan fitur pembangunan yang sudah diinput oleh operator/admin ke halaman lain, seperti halnya fitur lapak.
![image](https://user-images.githubusercontent.com/31026980/131811271-fdc0acf6-f5f2-4935-8e80-49e684eeec21.png)

**Apakah ada alternatif lain**

**Untuk versi OpenSID mana**

**Informasi tambahan**

**Comment by andifahruddinakas** [comment]
Pak @eddieridwan, sy coba kerjakan yg ini krn hampir mirip dengan yg lapak yg pernah sy kerjakan.

**Comment by andifahruddinakas** [comment]
![1576132766-picsay](https://user-images.githubusercontent.com/57283157/135784451-f1c2893b-9a46-48e4-9cf1-fcf13ca1263e.jpg)
![received_134793090485203](https://user-images.githubusercontent.com/57283157/135784455-176eaba7-ba08-48a2-883a-ce1cba8989cf.jpeg)

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melalui pr https://github.com/OpenSID/premium/pull/410
