### ISSUE TITLE
Kaitkan indikator/pertanyaan analisis dengan data kependudukan

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#4404]
**Apa kekurangan yg ingin diatasi?**

Saat ini indikator/pertanyaan yg datanya sebenarnya sudah ada di database kependuduk perlu diisi ulang di form survei analisis. Sebaiknya nilai indikator/pertanyaan itu diisi otomatis dari database kependudukan. 

**Jelaskan solusi yg diinginkan**

Untuk analisis sasaran penduduk, bisa mengaitkan pertanyaan dengan pilihan kolom dari data penduduk (`tweb_penduduk`). Sebagai contoh, pertanyaan Nomor HP (SDGs Individu) diisi otomatis dari kolom `telepon` bagi penduduk ybs.

Untuk analisis sasaran keluarga, bisa mengaitkan pertanyaan dengan pilihan kolom dari data keluarga (`tweb_keluarga`.

**Untuk versi OpenSID mana**

v21.09

**Informasi tambahan**

Perlu diperhatikan bahwa pengisian indikator/pertanyaan di suatu master analisis umumnya dilakukan dalam konteks suatu masa waktu, yaitu periode sensus/survei. Sebagai contoh, pertanyaan/indikator `Nomor HP` diperlukan bukan untuk status saat ini, tetapi untuk status pada periode sensus/survei. Solusinya perlu mempertimbangkan kebutuhan ini. Jadi bisa saja fitur ini tidak bisa disediakan bagi periode sensus/survei yg sdh lewat, kecuali bagi data yg dianggap tidak bergantung waktu, seperti `tanggal lahir`.

Panduan modul Analisis: https://github.com/OpenSID/OpenSID/wiki/Analisis

**Comment by andifahruddinakas** [comment]
Pak @eddieridwan : 
Apakah penyesuaian ini dilakukan pada semua sasaran yg tersedia??? atau hanya untuk sasaran `penduduk `dan `keluarga `saja???

**Comment by eddieridwan** [comment]
@afa28 , diprioritaskan untuk Penduduk dan Keluarga dulu.

**Comment by andifahruddinakas** [comment]
> @afa28 , diprioritaskan untuk Penduduk dan Keluarga dulu. 

Ok

**Comment by andifahruddinakas** [comment]
Sasaran Penduduk : 

Alur : 
1. Tambah Indikator
2. Pada bagian ini perlu ditambahkan pilihan isian (Manual / Otomatis) : 
- Manual  : nilai default kosong (perlu diisi), daftar jawaban perlu ditambahkan.
- Otomatis : nilai default diambil dari data penduduk, misalnya golongan darah maka jawaban default dari golongan_darah_id yg refrensi dari table gololongan darah.
3. Setelah memilih Tipe Pertanyaan, pada bagian ini perlu ditambahkan pilihan daftar jawab (Manual / Otomatis) : 
- Manual  : Daftar jawaban perlu disi 1 per 1;
- Otomatis : Daftar jawaban di buat berdasarkan pilihan referensi yg dipilih. Misalnya, golongan darah akan di linkkan ke table golongan darah.
4. Pada bagian input data survei, data di tampilkan berdasarkan pengaturan pada indikator pertanya tsb.

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melalui pr https://github.com/OpenSID/premium/pull/440
