### ISSUE TITLE
[Analsisis] Kaitkan indikator/pertanyaan analisis dengan perhitungan berdasarkan data kependudukan

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#4405]
**Apa kekurangan yg ingin diatasi?**

Saat ini indikator/pertanyaan di modul Analisis yg sebenarnya bisa diperhitungkan dari data yang sudah ada di database kependuduk tetap perlu dihitung dan diisi ulang di form survei analisis. Sebaiknya nilai indikator/pertanyaan itu bisa diisi otomatis berdasarkan data yg ada di database kependudukan.

Contoh: Berapa jumlah penduduk berumur 5 tahun atau kurang.

**Jelaskan solusi yg diinginkan**

Sebagai solusi prototip, sediakan satu saja perhitungan otomatis untuk sasaran tingkat desa, sbb:
1. Tamplkan form pencarian spesifik penduduk, menggunakan pencarian kolom yg diperlukan untuk indikator/pertanyaan SDGs, IDM dan Prodeskel tingkat desa
2. Hitung jumlah penduduk hasil pencarian tersebut
3. Kaitkan pencarian dan jumlah tersebut dengan indikator/pertanyaan sesuai kebutuhan, supaya indikator/pertanyaan tersebut akan selalu menampilkan jumlah saat ini untuk pencarian tersebut

**Apakah ada alternatif lain**

Cara lain adalah mengkaitkan script PHP yg bebas mengambil data dan melaukan perhitungan yg diperlukan. Tetapi cara ini sangat rentan masalah teknis dan keamanan. 

**Untuk versi OpenSID mana**

v21.09

**Informasi tambahan**

Perlu diperhatikan bahwa pengisian indikator/pertanyaan di suatu master analisis umumnya dilakukan dalam konteks suatu masa waktu, yaitu periode sensus/survei. Sebagai contoh, `Berapa jumlah penduduk berumur 5 tahun atau kurang` diperlukan bukan untuk status saat ini, tetapi untuk status pada periode sensus/survei. Solusinya perlu mempertimbangkan kebutuhan ini. 

Dalam menerapkan solusi awal ini, pilih pendekatan/arsitektur yg akan memudahkan penambahan perhitungan otomatis serupa lainnya. 

Panduan modul Analisis: https://github.com/OpenSID/OpenSID/wiki/Analisis

**Comment by muhtar-coder** [comment]
Setuju....
Misal target sasaran nya untuk usia 0-2 tahun (fleksibel).
Indikator dan pertanyaan bisa menyesuaikan kebutuhan data stunting.

**Comment by andifahruddinakas** [comment]
Pak @eddieridwan, ada contoh untuk data indikator/pertanyaan SDGs, IDM dan Prodeskel tingkat desa yg bisa sy jadikan rujukan???

**Comment by andifahruddinakas** [comment]
Pak @eddieridwan, apa datanya seperti ini https://cugung-rajabasa.desa.id/artikel/2020/11/22/pofil-desa-cugung-tahun-2020

**Comment by eddieridwan** [comment]
@andifahruddinakas , contoh di SGDs Rukun Tetangga P1001. P1002. Tetapi baru sedikit yg ditemukan.
[SDGs.DESA.KUESIONER.RUKUN.TETANGGA.1.1 (1).pdf](https://github.com/OpenSID/OpenSID/files/7472817/SDGs.DESA.KUESIONER.RUKUN.TETANGGA.1.1.1.pdf)

**Comment by andifahruddinakas** [comment]
Pak @eddieridwan, mungkin ada contoh analisis yang pernah dibuat pengguna yang bisa dijadikan rujukan???

**Comment by eddieridwan** [comment]
@andifahruddinakas tidak ada. Tetapi SDGs Rukun Tetangga seperti yg dilampirkan di atas merupakan sesuatu yg diterapkan beberapa desa, termasuk Mutih Kulon.

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melalui pr: https://github.com/OpenSID/premium/pull/461

Untuk sekarang baru hanya untuk sasaran desa, untuk yg lain dibuatkan issue terpisah.

- [x] Sasaran Desa
- [ ] Sasaran Dususn
- [ ] Sasaran RT
- [ ] Sasaran RW
