### ISSUE TITLE
[BUG] Tambah Warga Terdata di menu Suplemen

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#4408]
**Jelaskan error yg dialami**

Tambah Warga Terdata di Menu Suplemen, Data yang Tampil tidak mengambil data dari tweb_penduduk_hidup, 

**Cara untuk mereplikasi errornya**

**Hasil yg diharapkan**

Pada Waktu Tambah Data warga di Menu Suplemen mengambil data dari Tweb_penduduk_hidup
**Tampakan layar dan log error**

**Versi OpenSID**

**Tema Yg Digunakan**

**Informasi tambahan**

**Comment by agungsugiarto** [comment]
Terima kasih pak @MUHAMMADRANGSEL, sudah melaporkan issue tapi saya tidak menemukan masalah yg dimaksud, sebagai contoh:

- List penduduk dengan status dasar mati
![image](https://user-images.githubusercontent.com/10989147/132163697-a9bd88f5-6c98-41a2-9aa0-307e7e3b865c.png)

- Bisa dilihat ahlul tidak ada dalam list tersebut
![image](https://user-images.githubusercontent.com/10989147/132163853-8a457065-f96e-434f-ba66-8bcf1b35263b.png)

**Comment by andifahruddinakas** [comment]
> **Jelaskan error yg dialami**
> 
> Tambah Warga Terdata di Menu Suplemen, Data yang Tampil tidak mengambil data dari tweb_penduduk_hidup,
> 
> **Cara untuk mereplikasi errornya**
> 
> **Hasil yg diharapkan**
> 
> Pada Waktu Tambah Data warga di Menu Suplemen mengambil data dari Tweb_penduduk_hidup
> **Tampakan layar dan log error**
> 
> **Versi OpenSID**
> 
> **Tema Yg Digunakan**
> 
> **Informasi tambahan**

Saat menambah data sudah menggunakan penduduk_hidup, sedangkan saat menampilkan data/rincian tetap menggunakan tweb_penduduk agar supaya data tidak blank.

Jadi masalahnya adalah, jika ada penduduk yg sudah masuk ke data suplemen. Kemudian statusnya diubah jadi mati, maka akan tetap tercatat.

**Comment by MUHAMMADRANGSEL** [comment]
untuk sasaran keluarga maksud saya

**Comment by MUHAMMADRANGSEL** [comment]
kalau sasaran penduduk sudah sesuai
