### ISSUE TITLE
Tampilkan DOKUMEN / KELENGKAPAN PENDUDUK di browser

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#4410]
**Jelaskan error yg dialami**

cetak DOKUMEN / KELENGKAPAN PENDUDUK diversi 21.09 hanya bisa didownload saja baik menggunakan chrome maupun Opera, sedangkan diversi sebelumnya kalau menggunakan Opera bisa diview

**Cara untuk mereplikasi errornya**

**Hasil yg diharapkan**

Dokumen yang sudah diupload bisa diview dan bila perlu ditambahkan tombol aksi seperti di menu pembangunan
![dokumen](https://user-images.githubusercontent.com/25834335/132267100-e70c7aa8-1b80-4bf6-a018-48cf292ee463.png)
![pembangunan](https://user-images.githubusercontent.com/25834335/132267135-12b23ebb-9ad6-44bb-9c37-6f0b5ca9bc2a.png)
Sehingga file dokuemn tidak di duplivate di arsip yang ada di komputer
**Tampakan layar dan log error**

**Versi OpenSID**

**Tema Yg Digunakan**

**Informasi tambahan**

**Comment by eddieridwan** [comment]
Sdh dicommit ke `rilis-dev` (tambah fitur, bukan bug).
