### ISSUE TITLE
[Bumindes] Menu Buku Administrasi Desa

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#4411]
**Apa kekurangan yg ingin diatasi?**

DI menu Buku Administrasi Desa perlu ada Tombol Aksi Views untuk melihat dokumen yang sudah di Uploads
antara lain :
1. Buku Peraturan Desa
![image](https://user-images.githubusercontent.com/25834335/132267278-7a2a1669-e9f8-4a2d-89e3-849d9d5cf69d.png)
2. Buku Keputusan Kepala Desa
![image](https://user-images.githubusercontent.com/25834335/132267300-63e121af-fdc6-4800-a38e-7663e56f6fbd.png)
3. Buku Agenda - Surat Masuk
![image](https://user-images.githubusercontent.com/25834335/132267443-688756a6-75ff-41bb-9429-130e81887e6d.png)

**Jelaskan solusi yg diinginkan**

**Apakah ada alternatif lain**

**Untuk versi OpenSID mana**

**Informasi tambahan**

**Comment by raamaj** [comment]
Selamat sore, saya sedang belajar mengenai aplikasi OpenSID ini dan mencoba mengerjakan issue ini.

Solusi dari saya :
Menambahkan tombol lihat dokumen pada kolom aksi. Jika diklik akan muncul tab baru isi dari dokumen tersebut. Berikut tampilannya :
![image](https://user-images.githubusercontent.com/50396709/145958747-b2c28de7-459d-4ffe-a00f-b4d52535294c.png)

Setelah tab baru dibuka :
![image](https://user-images.githubusercontent.com/50396709/145959224-23af1d96-e76a-4cde-962d-877bbfd09ed2.png)

Jika file tidak ada:
![image](https://user-images.githubusercontent.com/50396709/145959301-beb45dae-6417-4629-8744-567c75381380.png)


Note : Baru dikerjakan pada menu Buku Peraturan Desa


Versi OpenSID : 22.01

**Comment by andifahruddinakas** [comment]
> Selamat sore, saya sedang belajar mengenai aplikasi OpenSID ini dan mencoba mengerjakan issue ini.
> 
> Solusi dari saya : Menambahkan tombol lihat dokumen pada kolom aksi. Jika diklik akan muncul tab baru isi dari dokumen tersebut. Berikut tampilannya : ![image](https://user-images.githubusercontent.com/50396709/145958747-b2c28de7-459d-4ffe-a00f-b4d52535294c.png)
> 
> Setelah tab baru dibuka : ![image](https://user-images.githubusercontent.com/50396709/145959224-23af1d96-e76a-4cde-962d-877bbfd09ed2.png)
> 
> Jika file tidak ada: ![image](https://user-images.githubusercontent.com/50396709/145959301-beb45dae-6417-4629-8744-567c75381380.png)
> 
> Note : Baru dikerjakan pada menu Buku Peraturan Desa
> 
> Versi OpenSID : 22.01

Silahkan di buat PRnya, gunakan branch dev-22.01

**Comment by MUHAMMADRANGSEL** [comment]
Mantap

Pada tanggal Sel, 14 Des 2021 16.23, Andi Fahruddin Akas <
***@***.***> menulis:

**Comment by andifahruddinakas** [comment]
Sudah di gabung ke FITUR PREMIUM melalui PR https://github.com/OpenSID/premium/pull/533
