### ISSUE TITLE
[Surat] Integrasi Dengan Tanda Tangan Elektronik

### ISSUE THREAD

**Issue by nurisakbar** [OpenSID/OpenSID#4412]
**Apa kekurangan yg ingin diatasi?**
Agar bisa mengggunakan tanda tangan elektonik untuk penandatanganan surat yang dibuat dengan aplikasi OpenSID.
saran ini disampaikan oleh bung endric dari desa leran kulon palang tuban melalui diskusi facebook pada tanggal 7 September 2021 ( Link : https://bit.ly/3n9VGRa ).

**Jelaskan solusi yg diinginkan**
integrasi TTE dengan OpenSID

**Apakah ada alternatif lain**
-

**Untuk versi OpenSID mana**
-

**Informasi tambahan**
-
Desa yg sdh memiliki TTE: Desa Leran Kulon Palang Tuban.
Dikelola Diskominfo Kabupaten.

Ada 3 tingkat pengguna, warga, operator, dan kepala desa sebagai penanda tangan.

Operator membuat surat dengan website yang sudah disediakan kabupaten, setelah surat terbuat, surat diteruskan ke kepala desa untuk ditanda tangani secara elektronik. sebelum diteruskan surat bisa dicetak, namun masih belum bertanda tangan.

Setelah operator meneruskan surat ke kepala desa, surat tersebut masuk ke halaman milik kepaladesa untuk di TTE dengan memasukkan kode otorisasi khusus.. setelah itu surat yang ada di halaman operator otomatis bertandatangan berupa QR QR Code.

QR Code yang ada di surat bisa dicek keasliannya dengan menscan ke halaman khusus scan keaslian surat. Setelah discan emudian muncul halaman yang menyatakan keaslian surat dan muncul link download surat. Surat bisa diunduh oleh warga yang login sebagai warga, dalam format PDF.

**Comment by eddieridwan** [comment]
Status OpenSID dari evaluasi BSrE di Kab Indragiri Hilir:

![telegram-cloud-photo-size-5-6300780907031801469-y](https://user-images.githubusercontent.com/249563/150746558-e64c5ae6-6d25-41ec-bb6e-d3f9af7043a9.jpg)

**Comment by yogiperdana** [comment]
Issue ini juga dibahas pada https://forum.opendesa.id/d/21-akselerasi-fitur-tte

**Comment by eddieridwan** [comment]
Sdh masuk ke 22.09-premium
