### ISSUE TITLE
Buku Mutasi Penduduk

### ISSUE THREAD

**Issue by afri18** [OpenSID/OpenSID#4413]
### Bagaimana alurnya sampai muncul masalah?
dalam buku mutasi penduduk kolom PENAMBAHAN hanya ada untuk penduduk datang, padahal bertambah penduduk bisa DATANG dan LAHIR
dalam buku mutasi penduduk kolom PENGURANGAN hanya ada pindah dan mati, padahal bisa PINDAH, MATI dan HILANG (karna bencana namun jasadnya tidak ditemukan)
![image](https://user-images.githubusercontent.com/6611881/132281795-04aae38c-9049-403a-a7ac-e70ea834e5e7.png)

### Seperti apa yang diharapkan?
sebaiknya dalam kolom Penambahan disediakan juga bertambah karna LAHIR dan kolom Pengurangan ada penduduk kurang karna HILANG

### Apa yang terjadi?
dalam buku mutasi tidak ada laporan penduduk karna penambahan lahir dan dalam pengurangan tidak ada laporan hilang

### Informasi tambahan 
maaf bila sudah dikerjakan karna tidak mengikuti, ditulis berdasarkan versi yang saya pakai
Terima kasih

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 21.09 umum
| Versi PHP        | 7
| System operasi   |

**Comment by eddieridwan** [comment]
@afri18 masalah ini sdh dibahas sebelumnya. Disebabkan memang tidak dilaporkan di Buku Mutasi Penduduk di Permendagri 47/2016. Karena fitur ini setia pada Permendagri tersebut, maka tidak ditambahkan.
