### ISSUE TITLE
[BUG] - Cetak lembaga dan kelompok data tidak tampil

### ISSUE THREAD

**Issue by agungsugiarto** [OpenSID/OpenSID#4415]
**Jelaskan error yg dialami**

Ketika melakukan cetak untuk modul lembaga dan kelompok data tidak tampil

**Cara untuk mereplikasi errornya**
1. Pergi ke halaman Info Desa > Lembaga dan Kependudukan > Kelompok
2. Klik tombol Cetak

**Hasil yg diharapkan**

Data tampil sesuai daftar

**Tampakan layar dan log error**

**Versi OpenSID**

**Tema Yg Digunakan**

**Informasi tambahan**

**Comment by andifahruddinakas** [comment]
Dari telegram:

![photo_2021-09-08_13-35-25](https://user-images.githubusercontent.com/57283157/132461272-42c856e1-01da-42f2-9bfc-2ca9f96cc2b4.jpg)

NOMOR SK JABATAN, MASA JABATAN (USIA/PERIODE) ditambahkan di kolom sebelum keterangan.
