### ISSUE TITLE
[BUG] Setelah tambah kode pada widget web eror 500

### ISSUE THREAD

**Issue by mrburgercheese** [OpenSID/OpenSID#4418]
## Jelaskan error yg dialami
Mohon bantuan

Disini saya ingin menambahkan kode maps di widget  dengan kode berikut

<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d63375.61909090944!2d112.0078473433176!3d-6.89345087478073!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x2e77a2c48649d9c1%3A0x14db680216ccc11d!2sTuban%2C%20Kec.%20Tuban%2C%20Kabupaten%20Tuban%2C%20Jawa%20Timur!5e0!3m2!1sid!2sid!4v1631264240354!5m2!1sid!2sid" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy"></iframe>

## Berikan keterangan yg jelas dan singkat mengenai error yg dialami. 
eror yag di alami adalah setelah di save langsung http eror 500

Mohon bantuannya

**Comment by andifahruddinakas** [comment]
Baca panduan : 
https://github.com/OpenSID/OpenSID/wiki/Persiapan-Install-OpenSID

**Comment by mrburgercheese** [comment]
Done pak terimakasih untuk rujukannya tenyata pemasalahan perlu mengaktifkan ekstensi php tidy.

Problem solved.
