### ISSUE TITLE
[BUG] Impor data penduduk dengan NIK Sementara

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#4419]
**Jelaskan error yg dialami**

**Cara untuk mereplikasi errornya**

**Hasil yg diharapkan**

**Tampakan layar dan log error**

**Versi OpenSID**

**Tema Yg Digunakan**

**Informasi tambahan**

**Comment by eddieridwan** [comment]
@afa28 perlu dirinci persisnya apa errornya.

**Comment by andifahruddinakas** [comment]
pak @ai-skematik

**Comment by andifahruddinakas** [comment]
Error:
- data nik 0 yg di impor tdk masuk

**Comment by agungsugiarto** [comment]
Sudah di commit melalui PR https://github.com/OpenSID/premium/pull/403
