### ISSUE TITLE
[BUG] NIK Sementara pada Persuratan belum disesuaikan scr menyeluruh

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#4421]
**Jelaskan error yg dialami**

**Cara untuk mereplikasi errornya**

**Hasil yg diharapkan**

**Tampakan layar dan log error**

**Versi OpenSID**

**Tema Yg Digunakan**

**Informasi tambahan**

**Comment by eddieridwan** [comment]
@afa28 perlu dirinci persisnya apa errornya.

**Comment by afa28** [comment]
List Surat:
