### ISSUE TITLE
[Suplemen] Buat data suplemen dinamis agar bisa menampung data stunting dan gizi buruk

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#4422]
**Apa kekurangan yg ingin diatasi?**

**Jelaskan solusi yg diinginkan**

**Apakah ada alternatif lain**

**Untuk versi OpenSID mana**

**Informasi tambahan**

**Comment by eddieridwan** [comment]
@afa28 apa maksud issue ini. Perlu diperjelas.

**Comment by Zoel-WB** [comment]
Mohon maaf sebelumnya, permohonan bila mungkin ada tambahan fitur tersendiri karena di opensid data-nya sudah lengkap dan menjadi data induk semua data penduduk, saya agak kesulitan membuat uraiannya karena terlalu panjang dan detail,  berikut sebagai contoh akan saya lampirkan link google drive rencana mau meng-upload disini berhubung filenya besar tidak sapat di upload di girhub.
1.  Sunting : https://drive.google.com/file/d/1vIEgQtAp3ayKMsOTlvVV-Ips15gNTXu7/view?usp=sharing
2. Posyandu :  https://drive.google.com/file/d/1f9ldP5Wah3xM7n6yGKeifl6HZUSXa3Nq/view?usp=sharing

**Comment by andifahruddinakas** [comment]
> Mohon maaf sebelumnya, permohonan bila mungkin ada tambahan fitur tersendiri karena di opensid data-nya sudah lengkap dan menjadi data induk semua data penduduk, saya agak kesulitan membuat uraiannya karena terlalu panjang dan detail, berikut sebagai contoh akan saya lampirkan link google drive rencana mau meng-upload disini berhubung filenya besar tidak sapat di upload di girhub.
> 
> 1. Sunting : https://drive.google.com/file/d/1vIEgQtAp3ayKMsOTlvVV-Ips15gNTXu7/view?usp=sharing
> 2. Posyandu :  https://drive.google.com/file/d/1f9ldP5Wah3xM7n6yGKeifl6HZUSXa3Nq/view?usp=sharing

file user_guide , vendor dan system tdk perlu disertakan untuk ci3 jika menggunakan composer.

**Comment by eddieridwan** [comment]
@Zoel-WB itu aplikasi dari mana?

**Comment by Zoel-WB** [comment]
Github juga cuma untuk contohnya saja Pak, sepertinya sudah terpenuhi untuk stuntingnya.......

**Comment by Zoel-WB** [comment]
KMP Stunting
1. Bentuk Input Data Laporan Bulanan Ibu Hamil
![image](https://user-images.githubusercontent.com/64481641/132948320-e11fe7c9-a595-4553-a72a-8d3ca7b5b647.png)

![image](https://user-images.githubusercontent.com/64481641/132948267-a17dd8ab-6455-45cb-9a2d-e3a5b577b4fd.png)

2. Bentuk Input Data Laporan Bulanan anak usia 0-2 tahun
![image](https://user-images.githubusercontent.com/64481641/132948326-fc01ed2d-9a46-4957-9b4f-51cd10d57ea8.png)
![image](https://user-images.githubusercontent.com/64481641/132948339-a4855ff6-df51-4119-b9ae-3933ad8f316a.png)

3. Bentuk Input Data sasaran Paud 
![image](https://user-images.githubusercontent.com/64481641/132948373-1d1f033f-26d4-4f83-b90f-3ef78661ad14.png)
![image](https://user-images.githubusercontent.com/64481641/132948380-7f5e2f31-9099-4279-9ac6-dbe25367f1e2.png)

**Comment by Zoel-WB** [comment]
> > Mohon maaf sebelumnya, permohonan bila mungkin ada tambahan fitur tersendiri karena di opensid data-nya sudah lengkap dan menjadi data induk semua data penduduk, saya agak kesulitan membuat uraiannya karena terlalu panjang dan detail, berikut sebagai contoh akan saya lampirkan link google drive rencana mau meng-upload disini berhubung filenya besar tidak sapat di upload di girhub.
> > 
> > 1. Sunting : https://drive.google.com/file/d/1vIEgQtAp3ayKMsOTlvVV-Ips15gNTXu7/view?usp=sharing
> > 2. Posyandu :  https://drive.google.com/file/d/1f9ldP5Wah3xM7n6yGKeifl6HZUSXa3Nq/view?usp=sharing
> 
> file user_guide , vendor dan system tdk perlu disertakan untuk ci3 jika menggunakan composer.

Untuk contoh saja Pak, barang kali nanti dapat diterapkan di opensid dengan data OpenSID itu sendiri....

**Comment by eddieridwan** [comment]
Buatan siapa?

**Comment by Zoel-WB** [comment]
posyandu agak ramai yg update, termasuk saya utk sebagian besar kelengkapannya seperti di fitur imunisasi dan penimbangan bayi, utk pos stunting agak lupa saya karena sudah saya update sedikit, nanti bisa saya cari ulang di lampirkan disini nama2nya...

**Comment by ai-skematik** [comment]
pak @Zoel-WB  ditanya Pak eddie aplikasi yg dibagikan itu siapa yg buat, supaya kalau nanti digabung ke OpenSID tidak kena hak cipta.

**Comment by Zoel-WB** [comment]
> pak @Zoel-WB  ditanya Pak eddie aplikasi yg dibagikan itu siapa yg buat, supaya kalau nanti digabung ke OpenSID tidak kena hak cipta.

Iya pak sebentar lagi saya browsing nanti saya kasih reponya, karena saya sekarang lagi dilapangan, akan tetapi ini hanya contoh saja pak, sedang di OpenSID sudah punya data yg lengkap hanya menambah fitur utk posyandu dan stunting saja utk menarik dari data penduduk ke laporan stunting dan posyandu,

**Comment by Zoel-WB** [comment]
cc: Pak @eddieridwan, @afa28 dan Pak @ai-skematik  berikut lampiran Repo contoh source Posyandu dan Stunting, sebagai acuan awal yang pernah saya pelajari........
link Repo Posyandu : https://github.com/adesug/posyanduku, akan tetapi ada beberapa repo lainnya yg sama.......
link Repo Stunting : https://github.com/raflyfirdausy/konvergensi-stunting

Berikut contoh-contoh format laporan stunting dalam bentuk file dengan format excel...
[OK_FORM_ISIAN_KPM.zip](https://github.com/OpenSID/OpenSID/files/7148976/OK_FORM_ISIAN_KPM.zip)

**Comment by Zoel-WB** [comment]
Harapan fitur Posyandu dan Stunting bisa masuk dalam fitur prioritas untuk pengembangan opensid di rilis-rilis mendatang Pak @eddieridwan, @afa28 karena pandangan  saya fitur ini termasuk salah satu fitur penting saat ini karena termasuk dalam salah satu yang diprioritaskan dalam analis seperti di IDM dan SDGs, untuk opensid sendiri masuk sebagai penyedia satu aplikasi desa dengan satu rumah data dimasa depan, sehingga di desa tidak harus ada aplikasi yang terpisah yang lainnya cukup dengan membuka OpenSID semua kebutuhan system informasi desa sudah tersedia.....

**Comment by mukhlisvandjava** [comment]
Tahapan awal adalah memperjelas hak cipta aplikasi posyandu dulu. Agar bisa di kembangkan oleh OpenSID. Dan menampilkan output aplikasi ke suplemen OpenSID. Semua butuh proses.. yang penting kita bisa maju selangkah demi selangkah untuk OpenSID terintegrasi👌

**Comment by eddieridwan** [comment]
@andifahruddinakas , apakah issue ini sudah bisa ditutup?

**Comment by andifahruddinakas** [comment]
> @andifahruddinakas , apakah issue ini sudah bisa ditutup?

Sdah bisa pak
