### ISSUE TITLE
[BUG] Download Lampiran dokumen yang di upload dalam Artikel-> akses ditolak oleh server

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#4425]
**Jelaskan error yg dialami**
 Dokumen yang yng di upload dalam Artikel tidak dapat di download terjadi error 403 Formiden atau akses ditolak oleh server

Harap tidak melaporkan masalah instal OpenSID. Masalah pada waktu install harap ditanyakan di https://www.facebook.com/groups/OpenSID atau di https://t.me/joinchat/SI0GWHeqKT39Gxhh, karena terkait sistem masing2 pengguna. 

Berikan keterangan yg jelas dan singkat mengenai error yg dialami. 
Pastikan error ini juga ditemukan di https://demo.opensid.or.id (untuk RIlis Umum) atau di https://berputar.opensid.or.id (untuk RIlis Premium).
--> Premium 21.09 Rev01

**Cara untuk mereplikasi errornya**
![image](https://user-images.githubusercontent.com/64481641/133102806-f746652b-307a-4c88-9dd5-fbbba0fcac2c.png)
![image](https://user-images.githubusercontent.com/64481641/133102846-5b0f781f-3c42-4fe3-a192-cbcd2deae24c.png)

Langkah untuk mereplikasi error yg dialami, misalnya:
1. Pergi ke halaman '...'
2. Klik tombol '....'
3. Gulir ke bawah sampai '....'
4. Lihat error
-->

**Hasil yg diharapkan**

**Tampakan layar dan log error**

**Versi OpenSID**

**Tema Yg Digunakan**

**Informasi tambahan**

**Comment by eddieridwan** [comment]
Sdh dicommit ke `bug-fix`
