### ISSUE TITLE
Sesuaikan Nama Menu/Modul pada Admin dan web OpenSID dengan sebutan_desa/sebutan_kepala_desa[BUG] 

### ISSUE THREAD

**Issue by HerryWanda** [OpenSID/OpenSID#4426]
**Jelaskan error yg dialami**
1. Pada Modul Buku Adminitrasi Desa 
    Sesuaikan penamaan menu nya dengan sebutan desa, seperti yang lainnya. Seperti Modul Info Desa menjadi Info Nagari.
    seperti  : 
![1](https://user-images.githubusercontent.com/32125282/133547125-3b204da9-64b1-4f07-9515-497f2a59f474.png)
Jadi penamaan desa sesuaikan dengan sebutan_desa.

Jadi semua sub modul yg ada pada BUku Administrasi desa , penamaan nama menu nya tidak disesuaikan dengan sebutan_desa : 
Contoh  pada 
- BUKU ADMINISTRASI UMUM : Penamaan menu belum berdasarkan sebuta_desa
![2](https://user-images.githubusercontent.com/32125282/133547350-03d2e50e-bcf2-4d56-8d72-51734b2ccddf.png)
   - BUku Peraturan Desa = Buku peraturan <sebuta_desa>
   - Buku keputusan kepala Desa = Buku Keputusan <sebutan_kepaladesa>
   - Buku aparat pemerintah desa = buku aparata pemerintah <sebutan_desa>
   - Buku kas tanah desa = <sebutan_desa>
   - buku tanah di desa = <sebutan_desa>
   - buku lembaran desa dan berita desa = <sebutan_desa>
- Buku Adm Penduduk , 
   - Buku Mutasi Penduduk Desa = <sebutan desa>
- 

**Hasil yg diharapkan**
ini contoh pada menu info desa : 
![1](https://user-images.githubusercontent.com/32125282/133547125-3b204da9-64b1-4f07-9515-497f2a59f474.png)
Jadi intinya, sesuai sebutan_desa pada modul admin atau web

**Tampakan layar dan log error**
pada modul/menu buku adm desa : sebutan_desa belum digunakan.
![2](https://user-images.githubusercontent.com/32125282/133547887-c37148d1-6869-4ce3-bb65-048687e87fd4.png)

**Versi OpenSID**
Fitur Premium 21.09-rev01

**Tema Yg Digunakan**

**Informasi tambahan**
Termasuk juga laporan2, sesuai sebutan kepala desa, dengan sebutan_kepala_desa

**Comment by agungsugiarto** [comment]
Sudah di perbaiki melalui pr https://github.com/OpenSID/premium/pull/401
