### ISSUE TITLE
arsip layanan

### ISSUE THREAD

**Issue by afri18** [OpenSID/OpenSID#4428]
### Bagaimana alurnya sampai muncul masalah?
Saat cetak arsip layanan Surat untuk laporan perbulan tidak bisa, karna yang tersedia hanya pilihan tahun

### Seperti apa yang diharapkan?
Kalau Bisa Sediakan pilihan cetak/unduh Tahun#Bulan#Jenis Surat
![image](https://user-images.githubusercontent.com/6611881/133711715-c0123b97-e8f2-44bd-87d8-b80030fb7212.png)

### Apa yang terjadi?
Selelu tercetak/terunduh dalam setahun tidak bisa Perbulan

### Informasi tambahan 
Nantinya Laporan ini setiap bulan
Maaf bila sudah ada di issue sebelumnya anggab ini tidak berlaku

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 21.09_umum
| Versi PHP        | 7
| System operasi   |

**Comment by Appi-spec** [comment]
sudah tersedia untuk versi premium tp dirilis umum nanti bulan 12
[https://github-wiki-see.page/m/OpenSID/OpenSID/wiki/Rilis-Umum-Yang-Akan-Datang](url)

OpenSID versi premium :
[https://berputar.opensid.or.id/](url)
