### ISSUE TITLE
[Database] Penambahan Fitur Import Asuransi Kesehatan pada file FormatImporExcel

### ISSUE THREAD

**Issue by sukrimalendra** [OpenSID/OpenSID#4430]
**Apa kekurangan yg ingin diatasi?**
tikak tersedianya kolom untuk mengimpor nama asuransi dan nomornya pada FormatImpor Excel. dengan adanya kolom ini maka nama asuransi dan nomornya dapat diimpor ke database penduduk secara kolektif.
![image](https://user-images.githubusercontent.com/30992964/133961215-1a05ed14-9585-4a06-be10-190b5b6eeb50.png)
![image](https://user-images.githubusercontent.com/30992964/133961404-aec5e2f2-a8c7-4e23-a52b-0fa1c71f3162.png)

**Jelaskan solusi yg diinginkan**

**Apakah ada alternatif lain**

**Untuk versi OpenSID mana**

**Informasi tambahan**

**Comment by FirlianiF** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/600
