### ISSUE TITLE
[BUG] Infrastruktur lokasi tidak muncul pada menu pemetaan

### ISSUE THREAD

**Issue by makhbub** [OpenSID/OpenSID#4431]
**Jelaskan error yg dialami**

Infrastruktur lokasi tidak muncul pada menu pemetaan, sementara infrastruktur lain (Area dan Garis) masih muncul.
sudah cek di demo.opensid tidak muncul sedangkan di Berputar.Opensid menu infrastruktur lokasi masih muncul

**Cara untuk mereplikasi errornya**

**Hasil yg diharapkan**

infrastruktur lokasi pada menu pemetaan rilis umum dimunculkan kembali
**Tampakan layar dan log error**

**Versi OpenSID**

Error ini terjadi di rilis/versi berapa: Rilis umum (mis. v21.09)

**Tema Yg Digunakan**

tema natra versi 21.09 umum

**Informasi tambahan**

**Comment by andifahruddinakas** [comment]
Akan di update di rilis 21.10, silahkan lakukan testing dirilis pasca tsb.

**Comment by makhbub** [comment]
Siap..!, Terima kasih
