### ISSUE TITLE
[BUG] Perbaiki isi kolom "Pendidikan Terakhir" pada Laporan Anggota Lembaga

### ISSUE THREAD

**Issue by PWidodo** [OpenSID/OpenSID#4434]
**Jelaskan error yg dialami**
Pada halaman cetak laporan data anggota lembaga terdapat kekeliruan pada isi tabel kolom Pendidikan Terakhir.

**Cara untuk mereplikasi errornya**
Kemungkinan erorr tersebut karena kolom tabel Pendidikan Terakhir tersebut berisi script **pendidikan_sedang_ditempuh** dan seharusnya berisi script **pendidikan_dalam_kk**

**Hasil yg diharapkan**
Kolom pendidikan terakhir berisi (SLTP, SLTA, D1, D2, D3, S1, S2,...dst) sesuai dengan data penduduk (anggota lembaga) pada Kartu Keluarga.

**Tampakan layar dan log error**
tidak ada error

**Versi OpenSID**
Rilis Premium_21.09_Rev.03

**Tema Yg Digunakan**
semua tema 

**Informasi tambahan**

![laporan Data Lembaga](https://user-images.githubusercontent.com/45189822/134611967-9708447b-adf3-4b36-961c-dfd7afa21218.jpg)

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui commit https://github.com/OpenSID/premium/commit/92311fb6b68e6489dfdd2bd13a66ffa6b2d79619
