### ISSUE TITLE
[BUG] Gagal Post Artikel padasaat di Hosting

### ISSUE THREAD

**Issue by fajartinri** [OpenSID/OpenSID#4436]
ini kok saya coba upload ke hosting (hostinger) malah gagal setiap mau post artikel dll, mohon jawabannya dan apa yang harus saya lakukan ?
![Gagal Post](https://user-images.githubusercontent.com/48597229/134764287-50269117-3342-481c-8a00-45f73dfc3b54.png)

**Comment by afa28** [comment]
Lampirkan log error

**Comment by andifahruddinakas** [comment]
Silahkan di buka kembali issue ini jika log error sudah di lampirkan.

**Comment by andiferdiawan** [comment]
![Image](https://github.com/user-attachments/assets/cb1c353c-eadb-48cf-96b5-28aec332b534)


selalu gagal saat insert artikel
