### ISSUE TITLE
Pisahkan setiap judul analisis di halaman website desa sebagai sub menu agar data yang di sajikan tidak bercampur

### ISSUE THREAD

**Issue by muhtar-coder** [OpenSID/OpenSID#4440]
**Apa kekurangan yg ingin diatasi?**

Data analisis dari beberapa judul yang di tampilkan di halaman website desa menyatu meskipun berbeda judul data analisis.

**Jelaskan solusi yg diinginkan**

Sediakan masing-masing pilihan sebagai sub menu untuk menampilkan data analisis di halaman website desa sesuai judul masing-masing

![image](https://user-images.githubusercontent.com/55665526/134938654-7b05a1aa-a5d2-46c1-9a99-187f3772ff49.png)

**Apakah ada alternatif lain**

Pada menu halaman website desa dapat di buat/di tampilkan menu analisis,dari menu utama tersebut dapat di buat sub menu untuk menampilkan masing-masing hasil analisis,sehingga ketika di klik sub menu tersebut hanya membuka daftar hasil analisis sesuai judul sehingga tidak bercampur dan mudah di pahami.

![image](https://user-images.githubusercontent.com/55665526/134939701-c1c32c42-91bf-4334-b53a-6fef27438509.png)

**Untuk versi OpenSID mana**

v21.10 premium

**Informasi tambahan**

**Comment by eddieridwan** [comment]
Sdh dicommit ke `rilis-dev`.

Tidak dipisah melalui menu. Melainkan disediakan pilihan master analisis di halaman analisis web. Solusi ini digunakan, karena publikasi di modul Analisis dilakukan per indikator, dan bukan ditentukan per master analisis.
