### ISSUE TITLE
[BUG] Status dasar penduduk hilang tidak dapat di kembalikan/di pulihkan

### ISSUE THREAD

**Issue by muhtar-coder** [OpenSID/OpenSID#4442]
**Jelaskan error yg dialami**

log penduduk dengan keterangan status dasar hilang tidak dapat di kembalikan/di pulihkan.hal ini salah satu yang menyebabkan jumlah hitungan pada laporan penduduk bulanan /jumlah kk tidak valid.

![image](https://user-images.githubusercontent.com/55665526/136069488-f66e27c7-9b1a-4bf7-9bb5-e1f1daa1b9ac.png)

![image](https://user-images.githubusercontent.com/55665526/136068429-3bc388dc-6086-4b6e-be41-54ebef484487.png)

**Cara untuk mereplikasi errornya**

**Hasil yg diharapkan**

hasil akhir yang ada di home,statistik dan laporan bulanan bisa sama
**Tampakan layar dan log error**

**Versi OpenSID**

error ini mungkin hanya terjadi di database kami karena ketidak tahuan operator membuat keterangan "hilang" dan juga karena status tersebut tidak dapat di kembalikan. 

**Tema Yg Digunakan**

**Informasi tambahan**

salah satu penyebab error atau masalah pada perbedaan /selisih jumlah KK, karena ketika kepala keluarga meninggal tidak di lakukan pecah data, dan penyebab lain nya adalah karena status "hilang" yang tidak bisa di kembalikan.

analisa yang kami lakukan : jika status dasar hilang tersebut dapat di kembalikan maka data jumlah KK antara home dan statistik akan sama.

**Comment by muhtar-coder** [comment]
cc @afa28 @agungsugiarto

**Comment by eddieridwan** [comment]
Masalah ini adalah karena status database yg tidak konsisten. Sangat mungkin karena migrasi terkait log_penduduk tidak dijalankan sempurna. Solusinya bukan dengan memaksa menjadi sama. Tapi yg perlu diperiksa adalah mengapa databasenya tidak konsisten dan kemudian memperbaiki databasenya. Perhatikan ini juga tergantung versi OpenSID yg mana. @afa28

**Comment by muhtar-coder** [comment]
Cc @eddieridwan

**Comment by andifahruddinakas** [comment]
> Masalah ini adalah karena status database yg tidak konsisten. Sangat mungkin karena migrasi terkait log_penduduk tidak dijalankan sempurna. Solusinya bukan dengan memaksa menjadi sama. Tapi yg perlu diperiksa adalah mengapa databasenya tidak konsisten dan kemudian memperbaiki databasenya. Perhatikan ini juga tergantung versi OpenSID yg mana. @afa28 

Ok

**Comment by eddieridwan** [comment]
@muhtar-coder @afa28 , untuk melacak masalah database desa ini, kirim backup database yg bermasalah untuk diperiksa.

**Comment by muhtar-coder** [comment]
Point : masalah berasal dari perubahan kepala keluarga dengan status mati,atau yg mengharuskan perubahan no KK namun tidak dilakukan pemecahan...

Mungkin harus di buat warning apabila ada perubahan kepala keluarga karena masalah ini kemungkinan akan banyak di temui yg lain

**Comment by eddieridwan** [comment]
Sekarang, melalui issue https://github.com/OpenSID/OpenSID/issues/4455, keluarga dengan KK mati/hilang/pindah tidak dapat diubah -- termasuk tidak bisa diganti kepala keluarganya. Yang hanya bisa dilakukan adalah pecah anggota. 

Kalau itu mengatasi masalah di issue #4442 ini, silakan ditutup.
