### ISSUE TITLE
Penambahan Link halaman atau link website di lapak

### ISSUE THREAD

**Issue by tobagus6911** [OpenSID/OpenSID#4444]
**Apa kekurangan yg ingin diatasi?**

Penambahan Link halaman atau link website di lapak selain WA dan Lokasi

**Jelaskan solusi yg diinginkan**

dimaksudkan agar warga dapat melihat lebih banyak informasi mengenai lapak/ tokonya

**Comment by andifahruddinakas** [comment]
Bisa ditambahkan di deskripsi produk.
