### ISSUE TITLE
Buat Jabatan dalam Menu Lembaga Menjadi Fleksibel

### ISSUE THREAD

**Issue by mizwaruddin** [OpenSID/OpenSID#4449]
**Apa kekurangan yg ingin diatasi?**

Saat ini jabatan dalam lembaga hanya tersedia ketua, sekretaris, bendahara, dan anggota. Padahal dalam lembaga ada seksi-seksi. Terkadang juga ada jabatan wakil ketua.

**Jelaskan solusi yg diinginkan**

Admin bisa menambahkan sendiri jabatan sesuai dengan kebutuhan lembaga.

**Apakah ada alternatif lain**

**Untuk versi OpenSID mana**

**Informasi tambahan**

**Comment by eddieridwan** [comment]
@mizwaruddin, Di v21.10-premium, bebas menambah jabatan. Pada waktu menambah anggota, ketik langsung jabatan yg dibutuhkan. 
Silakan periksa di berputar.opensid.or.id, dan tutup issue ini kalau sudah memadai.

**Comment by andifahruddinakas** [comment]
> **Apa kekurangan yg ingin diatasi?**
> 
> Saat ini jabatan dalam lembaga hanya tersedia ketua, sekretaris, bendahara, dan anggota. Padahal dalam lembaga ada seksi-seksi. Terkadang juga ada jabatan wakil ketua.
> 
> **Jelaskan solusi yg diinginkan**
> 
> Admin bisa menambahkan sendiri jabatan sesuai dengan kebutuhan lembaga.
> 
> **Apakah ada alternatif lain**
> 
> **Untuk versi OpenSID mana**
> 
> **Informasi tambahan**

Jabatan jika belum tersedia, bisa ditambahkan secara manual/diketik langsung.
![dsfdsfdsf](https://user-images.githubusercontent.com/57283157/135979425-09b9fa77-62b5-423f-9d82-50077594eae8.png)
