### ISSUE TITLE
[BUG] Unduh Salinan Keluarga Muncul Eror 403

### ISSUE THREAD

**Issue by WAHYUDIK** [OpenSID/OpenSID#4450]
**Jelaskan error yg dialami**

ketika kita ingin mengunduh salinan keluarga tidak bisa, muncul eror 403, seperti gambar dibawah ini

**Cara untuk mereplikasi errornya**

![image_2021-10-02_10-04-40](https://user-images.githubusercontent.com/31026980/135702870-de718fe3-f170-4a40-be7f-bb985d37a1c9.png)

**Hasil yg diharapkan**
 tidak terjadi eror seperti gambar, sehingga data bisa terunduh

**Tampakan layar dan log error**

![image_2021-10-02_10-04-40](https://user-images.githubusercontent.com/31026980/135702881-92d74658-9edc-4d01-b355-589d9540bc2d.png)

**Versi OpenSID**

**Tema Yg Digunakan**

**Informasi tambahan**

**Comment by eddieridwan** [comment]
@WAHYUDIK Lampirkan tampakan layar di menu yg bermasalah. Supaya cepat bisa direplikasi.

**Comment by WAHYUDIK** [comment]
di menu kependudukan, submenu keluarga pak @eddieridwan 
![image](https://user-images.githubusercontent.com/31026980/135703198-c0744209-8973-4674-af69-726843348530.png)
![image](https://user-images.githubusercontent.com/31026980/135703202-af1662f0-08ec-4092-a09f-b0e530657de5.png)

**Comment by eddieridwan** [comment]
Sdh dicommit ke `bug-fix`
