### ISSUE TITLE
[BUG] Data Hasil Entri Pembangunan Hilang

### ISSUE THREAD

**Issue by WAHYUDIK** [OpenSID/OpenSID#4451]
**Jelaskan error yg dialami**

Setelah melakukan update opensid dari versi 21.09 ke versi 21.10 hasil entri data pembangunan hilang, akan tetapi di menu administrasi pembangunan data masih ada sesuai hasil entri sebelumnya

**Cara untuk mereplikasi errornya**

**Hasil yg diharapkan**

harapannya setelah mengentri hasil/progres, data entri pembangunan di menu pembangunan masih ada, agar bisa melanjutkan mengisi progres pembangunan lanjutannya
**Tampakan layar dan log error**

![2021-10-02 (6)](https://user-images.githubusercontent.com/31026980/135702995-e17e1279-e9bc-4500-9861-a614957991d0.png)
![2021-10-02 (7)](https://user-images.githubusercontent.com/31026980/135702997-d234c77d-e90a-49fb-88e4-3bf2d7da1902.png)

**Versi OpenSID**

opensid rilis premium versi 21.10

**Tema Yg Digunakan**

**Informasi tambahan**

analisa sementara penyebab hilangnya data adalah, ketika data pembangunan sudah menambah progres misal 30% .sehingga data hasil entrinya hilang, yang mengakibatkan tidak bisa melanjutkan entri progres lanjutan.

**Comment by eddieridwan** [comment]
Sdh dicommit ke `bug-fix`
