### ISSUE TITLE
[Anjungan] Aktifkan kembali fitur cetak surat di anjungan mandiri

### ISSUE THREAD

**Issue by WAHYUDIK** [OpenSID/OpenSID#4454]
**Apa kekurangan yg ingin diatasi?**

sehubungan dengan banyaknya desa-dengan yang ingin menerapkan atau menggunakan anjungan, dimana yang mereka harapkan adalah warga bisa mencetak sendiri suratnya dianjungan. Dan kemudian lagi dengan adanya beberapa desa yang sudah mengajukan permohonan penerbitan Tanda Tangan Elektronik, sehingga sangat dibutuhkan untuk diaktifkannya kembali fitur cetak di anjungan mandiri.

**Jelaskan solusi yg diinginkan**

saat ini fitur tersebut dinon aktifkan dengan alasan demi menjaga keamanan atau tidak menjadi praktek baik bagi desa dan lain-lain.

**Apakah ada alternatif lain**

adapun langkah atau solusi sementara yang dapat saya sampaikan:
1. setelah warga atau pengguna melakukan permohonan surat melalui anjungan.
2. admin akan melakukan validasi sesuai dengan peraturan dan kelengkapan dokumen yang diupload oleh pemohon, jika sudah sesuai maka,
3. admin akan mengirimkan atau merubah status permohonan mennjadi siap dicetak
4. warga siap untuk mencetak permohonannya.

**Untuk versi OpenSID mana**

**Informasi tambahan**

**Comment by rudiansyahyunanda** [comment]
Sependapat, atau bisa ditambahkan opsi pengaturan bisa diaktifkan atau dinonaktifkan fiturnya.

**Comment by eddieridwan** [comment]
@WAHYUDIK @rudiansyahyunanda , seperti sudah dijelaskan berulangkali, fitur cetak melalui layanan mandiri/anjungan tidak bisa diterapkan sebelum desa memiliki TTE. Kita masih menunggu ada desa yg berhasil memperoleh TTE untuk OpenSID. Cetak Layanan Mandiri nanti akan bisa diaktifkan bila desa telah memasang TTE. 

Jika teman2 ingin membantu, maka usahakanlah supaya desa anda memperoleh TTE untuk OpenSID. Segera beritahu kalau sudah berhasil. 

Alternatif lain adalah apabila desa bersedia menggunakan QR Code sendiri sebagai pengganti sementara  belum ada TTE. Tentunya dalam hal ini desa harus bersedia bertanggung jawab atas keabsahan QR Code mereka masing2, termasuk potensi penyalahgunaan. Beritahu kalau fitur ini diinginkan.

**Comment by WAHYUDIK** [comment]
saya bersedia pak @eddieridwan  untuk alternatif tersebut, sambil lalu menunggu keluarnya TTE dari BSRE

**Comment by eddieridwan** [comment]
Beberapa pertimbangan teknis untuk solusinya:

- [ ] surat cetak hanya dalam format PDF -- tidak disediakan unduh RTF. Yaitu desa `harus` memasang LibreOffice
- [ ] di tabel `log_surat` perlu ditambah indikator bahwa surat ybs ditandatangani secara elektronik
- [ ] di tabel `log_surat` perlu ditambah kolom untuk menyimpan hash isi surat setelah dibubuhi tanda tangan elektronik (QR Code + scan tandatangan Kades atau yg diberi kuasa)
- [ ] ada fitur verifikasi file surat PDF yg dihasilkan sesuai aslinya dan tidak ada perubahan. Fitur ini membandingkan kalkulasi hash dengan hash yg tersimpan di tabel `log_surat`
- [ ] QR Code dihasilkan secara otomatis dan berisi informasi bahwa surat ybs ditandatangani secara elektronik. QR Code berisi tautan untuk verifikasi surat (seperti fitur yg sudah ada)
- [ ] perlu ditambahkan pengaturan hak akses supaya yg bisa menandatangani surat hanya akun Kades atau yg diberi kuasa (yaitu melalui pengaturan `a.n.` di Pemerintahan Desa). Pengguna grup `administrator` tidak diberi hak untuk menandatangani surat secara elektronik, kecuali adalah pengguna yg diberi hak
- [ ] di tabel `tweb_pamong_desa` perlu ditambahkan kolom untuk menyimpan hasil scan tanda tangan pamong -- terutama yg akan menandatangani surat
- [ ] tabel `tweb_pamong_desa` perlu ditambah kolom riwayat: `created_at`, `created_by`, `updated_at` dan `updated_by`.
- [ ] tambahkan pengaturan aplikasi untuk mengaktifkan fitur cetak surat melalui Layanan Mandiri. Tampilkan peringatan tanggung jawab desa terkait peraturan administrasi persuratan pemerintahan desa

**Comment by andifahruddinakas** [comment]
Sudah disediakan unduh dokumen dilayanan mandiri jika desa tsb menggunakan TTE.
