### ISSUE TITLE
[BUG] Tombol simpan tidak berfungsi setelah input kedua pada menu Buku Tanah di Desa

### ISSUE THREAD

**Issue by muhtar-coder** [OpenSID/OpenSID#4458]
**Jelaskan error yg dialami**

tidak bisa simpan hasil input kedua /tombol tidak berfungsi
![image](https://user-images.githubusercontent.com/55665526/136640183-7fd01e49-c636-43d5-b958-7bb3d160638e.png)

**Cara untuk mereplikasi errornya**

**Hasil yg diharapkan**

**Tampakan layar dan log error**

![image](https://user-images.githubusercontent.com/55665526/136640321-0b007bfc-6c14-450c-a584-2a88d7bf63be.png)

**Versi OpenSID**

21.10 premium
**Tema Yg Digunakan**

denatra

**Informasi tambahan**

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melalui pr https://github.com/OpenSID/premium/pull/413
