### ISSUE TITLE
[BUG] Error 500 Ketika klik Kosongkan DB

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#4459]
### Bagaimana alurnya sampai muncul masalah?
Pertama kali install OpenSID dengan import contoh data awal, hingga sesuaikan konfigurasi database berjalan lancar dan sukses.

**Masalah muncul ketika** akan kosongkan database untuk pengguna baru, yang mana saat ini perlu input Token dan Identitas Desa terlebih dahulu agar menu Pengaturan -> Database tidak terkunci.

Setelah input Token dan Identitas Desa, saat klik Migrasi DB, muncul error 500.
Tetapi akses website dan menu masih bisa berjalan.

Ketika klik **Kosongkan DB, Error 500** kembali muncul, kali ini seluruh **website beserta Halaman Admin tidak bisa diakses** lagi.

Harus ulang import contoh data awal agar kembali normal.

<img width="960" alt="2021-10-10_10h12_46" src="https://user-images.githubusercontent.com/46939846/136680203-48fcd43c-57ae-4842-a2ba-9310c08b0035.png">
 
### Seperti apa yang diharapkan?
1. Klik Menu Pengaturan -> Database dan tombol Kosongkan DB berjalan normal.
2. Klik Menu tersebut **dapat dilakukan** sebelum input Token maupun Identitas Desa.
3. Jika penerapannya dilakukan setelah isi Token dan Identitas Desa karena Menu masih Terkunci, maka akan ada proses yang berulang untuk input Identitas desa dan Token lagi setelah Kosongkan Database.

### Apa yang terjadi?
Hal ini agar dapat dengan mudah proses install OpenSID bagi pengguna baru, atau yang ingin mengosongkan database, agar tidak berkaitan dengan Token.

### Informasi tambahan 
File Log Error terlampir.
[log-2021-10-10.zip](https://github.com/OpenSID/premium/files/7316761/log-2021-10-10.zip)

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melalui pr https://github.com/OpenSID/premium/pull/415
