### ISSUE TITLE
Penerima Notifikasi Telegram Bisa Lebih dari 1 Akun

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#4460]
**Apa kekurangan yg ingin diatasi?**

Melanjutkan issue https://github.com/OpenSID/OpenSID/issues/4322 yang sudah closed,

Diharapkan adanya fitur Notifikasi Telegram untuk Layanan Mandiri yang bisa diterima lebih dari 1 Akun.

Hal ini dimaksud agar jika salah satu Admin atau Operator Desa sedang tidak berada di tempat atau bahkan sedang Tidak ada Paket Data, maka Notifikasi tersebut bisa diterima juga oleh Operator Lain yang aktif secara langsung.

<img width="733" alt="2021-10-10_19h34_39" src="https://user-images.githubusercontent.com/46939846/136695962-e5b09c0f-3f32-46ba-a3a1-cb7d13ca950e.png">

**Jelaskan solusi yg diinginkan**

Adanya pemisah antara ID satu dengan ID lainnya, misal ditandai dengan pemisah tanda koma, atau tanda pagar #.

**Apakah ada alternatif lain**

**Comment by balongbesuk** [comment]
kenapa tidak di masukan kedalam grup telegram saja botnya?

**Comment by andifahruddinakas** [comment]
Silahkan gunakan cara ini https://github.com/OpenSID/OpenSID/wiki/Bot-Notifikasi-Telegram
