### ISSUE TITLE
[BUG] Tidak dapat input dengan NIK sama pada menu tanah yang ada di desa

### ISSUE THREAD

**Issue by muhtar-coder** [OpenSID/OpenSID#4461]
**Jelaskan error yg dialami**

Saat melakukan penginputan data pertanahan/data tanah yang ada di desa,tidak dapat di isi/input dengan noNIK yang sama

**Cara untuk mereplikasi errornya**

**Hasil yg diharapkan**

agar dapat di isi dengan data yang memiliki NIK sama
**Tampakan layar dan log error**

![image](https://user-images.githubusercontent.com/55665526/136742085-7b30c904-474e-4d9d-be2c-cfeb54ee62e4.png)

**Versi OpenSID**

21.10 premium bugfix1
**Tema Yg Digunakan**

**Informasi tambahan**

kami mengisi data ini dengan data yang berasal dari BPN yang memungkinkan satu nama/NIK memiliki lebih dari satu bidang tanah terutama yang sudah bersertifikat.

**Comment by andifahruddinakas** [comment]
pak @eddieridwan, apa benar seperti ini???

**Comment by balongbesuk** [comment]
seharusnya primary keynya memang NIK (No petok) bukan tanah (Persil), 

NIK A punya tanah sejumlah 1. tanah A 2. Tanah B 3 Tanah C
bukan sebaliknya tanah A (Pesil) punya NIK A (no Petok), NIK B (no Petok), NIK C (no Petok)

belum coba menu pertanahan, (mau tes d web demo website,ny down)

sebaiknya d lempar ke grup opensid karena sudah banyak yang menggunakan menu tersebut

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melalui pr https://github.com/OpenSID/premium/pull/422
