### ISSUE TITLE
[BUG]  Daftar permohonan Surat perlu di urut berdasarkan waktu permohonan

### ISSUE THREAD

**Issue by ai-skematik** [OpenSID/OpenSID#4462]
**Jelaskan error yg dialami**

Daftar Permohonan surat melalui layanan mandiri belum di urut berdasarkan waktu permohonan

**Cara untuk mereplikasi errornya**

ajukan surat melalu layanan mandiri, lalu cek pemohonan surat di menu admin, perhatikan tanggal permohonan.

**Hasil yg diharapkan**

di urut berdasarkan tanggal kirim permohonan
**Tampakan layar dan log error**

![gambar](https://user-images.githubusercontent.com/48144047/136881067-47c7d91c-7eb8-4db4-885b-701a98fa879b.png)

**Versi OpenSID**

**Tema Yg Digunakan**

**Informasi tambahan**

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melalui commit https://github.com/OpenSID/premium/commit/19c71e0d26043c868358612fb795c0b8187a04b7
