### ISSUE TITLE
[Pengaturan] Berikan Opsi Sembunyikan Luas Area di Web

### ISSUE THREAD

**Issue by mizwaruddin** [OpenSID/OpenSID#4464]
**Apa kekurangan yg ingin diatasi?**

Saat ini peta area selalu menampilkan luas area. Kadang kala, luas area tsb tidak perlu ditampilkan karena luas peta yg dibuat belum tentu sama dg luas di sertipikat tanah.

**Jelaskan solusi yg diinginkan**

Berikan opsi untuk menampilkan/menyembunyikan luas area.

**Apakah ada alternatif lain**

**Untuk versi OpenSID mana**

**Informasi tambahan**

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1193
