### ISSUE TITLE
[BUG] Terjadi Error 404 pada Paginasi Halaman Web Lapak

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#4465]
**Jelaskan error yg dialami**

Saat halaman lapak lebih dari 1, maka klik halaman pada paginasi ke 2 dan seterusnya akan muncul error 404.

dengan link URL pada paginasi adalah: /produk/2
namun ketika URL diganti manual menjadi: /lapak/2 akan sukses tampil produk.

**Cara untuk mereplikasi errornya**

**Hasil yg diharapkan**

Halaman paginasi dapat berfungsi dengan normal kembali.

**Tema Yg Digunakan**

Keduanya Error 404, baik Tema klasik, maupun tema Natra.

**Comment by andifahruddinakas** [comment]
Pak @ariandii, sy coba tdk ada masalah. Sy pakai rev01, apa masalahnya di beta01. Mungkin bisa dicantumkan versi yg digunakan.

![lapak](https://user-images.githubusercontent.com/57283157/136929000-958f702d-be95-46d7-b4a8-51d7951168aa.png)

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki, terjadi setelah penambahan pencarian produk.
