### ISSUE TITLE
[BUG] Tombol Simpan Produk Lapak tidak Berfungsi

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#4467]
**Jelaskan error yg dialami**

Masuk halaman https://berputar.opensid.or.id/lapak_admin/produk_form

Tombol simpan tidak berfungsi ketika Kolom Potongan Harga Produk diubah menjadi Nominal (Rp.)

**Hasil yg diharapkan**

Berfungsi sebagaimana mestinya.

**Tampakan layar dan log error**

<img width="542" alt="2021-10-12_15h20_56" src="https://user-images.githubusercontent.com/46939846/136921747-25fb7180-f66a-4252-981e-45a460cec14a.png">

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melalui pr https://github.com/OpenSID/premium/pull/424
