### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Jhiban-Khang** [OpenSID/OpenSID#4468]
pada release OPENSID UMUM 21.10

gagal Menyimpan data penduduk baru jika melalui TAMBAH ANGGOTA KELUARGA di menu Keluarga

**Comment by andifahruddinakas** [comment]
Sudah digabungkan ke branch `dev-21.11` melalui commit ba6dc8e1f2923edb4fe4ea2153cacea31d10dc3e
