### ISSUE TITLE
Scan Tag ID Card Tidak Tersave [BUG] 

### ISSUE THREAD

**Issue by desasoro** [OpenSID/OpenSID#4469]
**Jelaskan error yg dialami**

**Cara untuk mereplikasi errornya**

**Hasil yg diharapkan**

**Tampakan layar dan log error**

**Versi OpenSID**

**Tema Yg Digunakan**

**Informasi tambahan**

**Comment by andifahruddinakas** [comment]
pak @desasoro silahkan issuenya dilengkapi. Buka kembali kalau masih bermasalah.
