### ISSUE TITLE
Menambah Informasi Penandatangan di Halaman Verifikasi Surat

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#4470]
**Apa kekurangan yg ingin diatasi?**

Adanya informasi Pejabat yang Menandatangani Surat Keterangan berdasarkan hasil scan QRCode.

Sebagai contoh halaman hasil verifikasi https://www.natairaya.desa.id/c1/751

**Jelaskan solusi yg diinginkan**

Tersedia keterangan bahwa benar telah ditandatangani oleh KepalaDesa/PerangkatDesa lain yang telah menandatangani sesuai yang dipilih saat cetak Surat Keterangan oleh Operator.

Contoh sebagai mana hasil link di atas:
<html>
<body>
<h5 style="box-sizing: border-box; font-family: &quot;Source Sans Pro&quot;, sans-serif; font-weight: 500; line-height: 1.1; color: rgb(102, 102, 102); margin-top: 10px; margin-bottom: 10px; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: -webkit-center; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><u style="box-sizing: border-box;">Menyatakan bahwa</u></h5>

Nomor Surat | : | 471.23/062/NR/X/2021
-- | -- | --
Tanggal Surat | : | 14 Oktober 2021
Perihal | : | Surat Keterangan Domisili
  |   | a/n MEI YULIANTIKA

</body>
</html>
<html>
<body>
<h5 style="box-sizing: border-box; font-family: &quot;Source Sans Pro&quot;, sans-serif; font-weight: 500; line-height: 1.1; color: rgb(102, 102, 102); margin-top: 10px; margin-bottom: 10px; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: -webkit-center; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><u style="box-sizing: border-box;">Info Penandatangan</u></h5>

Nama | : | Ariandi Ryan Kahfi, S.Pd.
-- | -- | --
Jabatan | : | Sekretaris Desa

</body>
</html>

**Apakah ada alternatif lain**

**Apakah ada alternatif lain**

**Untuk versi OpenSID mana**

**Informasi tambahan**

**Comment by lihin20** [comment]
setuju

**Comment by andifahruddinakas** [comment]
Tampilan bisa disesuaikan di masing2 tema :

![verifikasi](https://user-images.githubusercontent.com/57283157/140049852-52adda61-68ef-401f-ac1f-b159c1502c42.png)

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melalui pr https://github.com/OpenSID/premium/pull/450
