### ISSUE TITLE
[BUG] Error Buka Halaman Verifikasi Surat

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#4471]
**Jelaskan error yg dialami**

Scan QRCode pada lembar surat keterangan, ketika klik link yang muncul Pertama akan terbuka halaman Error 404.,
Setelah klik, ulang, baru muncul informasi mengenai surat tersebut.

Klik link, akan terjadi Error pada saat pertama kali hingga Ketiga kali dibuka.

Dan setelah itu, akan berhasil membuka halaman informasi pemilik surat.

**Cara untuk mereplikasi errornya**
Langkah untuk mereplikasi error yg dialami, misalnya:
1. Pergi ke halaman 'Layanan Surat -> Cetak Surat -> Pilih Suat Keterangan yang tersedia QR Code'
2. Klik tombol 'Undah RTF atau & Cetak PDF'.
3. Akan muncul hasl QR COde di lembar Surat Keterangan tersebut
4. Scan QRCode
5. Muncul Link.
6. Klik Link, pertama kali hinga 3 kali klik, halaman akan Error 404
7. klik link ke sekian kali, baru sukses muncul halaman informasi keterangan pemilik surat.

**Hasil yg diharapkan**
Berikan keterangan yg jelas dan singkat apa hasil yg diharapkan.

Lancar sukses terbuka halaman inforamsi surat pertama kali klik link hasil scan QR code

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melalui pr https://github.com/OpenSID/premium/pull/436
