### ISSUE TITLE
[BUG] Surat Keterangan Kematian dapat tampil di layanan mandiri 

### ISSUE THREAD

**Issue by zeneight** [OpenSID/OpenSID#4472]
**Jelaskan error yg dialami**
Ada opsi sediakan di layanan mandiri untuk pilihan Surat Keterangan Kematian pada Admin yang menyebabkan munculnya formulir surat kematian pada halaman layanan mandiri  

**Cara untuk mereplikasi errornya**
1. Login ke halaman admin
2. Pergi ke menu layanan surat > pengaturan surat
3. Klik tombol 'Buat Surat'
4. Cari keterangan kematian pada field pencarian dan klik tombol kuning 'Ubah Data' 
5. Pilih Opsi Ya pada field 'Sediakan di Layanan Mandiri'

**Hasil yg diharapkan**
Formulir tidak menampilkan opsi tampil di layanan mandiri pada surat kematian di halaman admin dan juga form surat kematian di halaman layanan mandiri

**Tampakan layar dan log error**
Hal Admin
![WhatsApp Image 2021-10-14 at 20 07 53 (2)](https://user-images.githubusercontent.com/14101291/137315176-4c869dc0-4f9b-49a3-96ab-a18b7881b1f3.jpeg)

Hal Layanan Mandiri
![Screenshot_2021-10-14_12-10-40](https://user-images.githubusercontent.com/14101291/137250594-f862c185-7ca6-404a-9002-226191a74b50.png)

![Screenshot_2021-10-14_12-00-55](https://user-images.githubusercontent.com/14101291/137249695-b77602b7-244e-4132-9984-cb4d5601cbdd.png)

**Versi OpenSID**
Rilis umum v21.10

**Tema Yg Digunakan**
Natra v4.5

**Comment by balongbesuk** [comment]
layanan mandiri kan d khususkan untuk permohonan surat penduduk hidup?

**Comment by zeneight** [comment]
@balongbesuk Kalau memang dikhususkan untuk permohonan surat penduduk hidup kenapa di admin ada opsi "tampilkan di layanan mandiri" untuk pilihan surat keterangan kematian?
Apakah lebih baik dihilangkan?

![WhatsApp Image 2021-10-14 at 20 07 53 (2)](https://user-images.githubusercontent.com/14101291/137315176-4c869dc0-4f9b-49a3-96ab-a18b7881b1f3.jpeg)

**Comment by balongbesuk** [comment]
kl begitu issuenya d ganti hanya surat penduduk hidup saja yang boleh masuk ke layanan mandiri

**Comment by zeneight** [comment]
@balongbesuk Sudah saya ganti

**Comment by andifahruddinakas** [comment]
Pak @zeneight mungkin bisa baca panduan https://github.com/OpenSID/OpenSID/wiki/Surat-Layanan-Mandiri

**Comment by andifahruddinakas** [comment]
Silahkan di buka kembali jika masih bermasalah.

**Comment by zeneight** [comment]
@afa28 Terima kasih banyak atas arahan dan informasinya
