### ISSUE TITLE
Pindahkan data pengguna ke folder desa

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#4476]
**Apa kekurangan yg ingin diatasi?**

Setiap kali update terkadang pengguna hanya membackup folder desa saja, sehingga data lain kadang terhapus seperti data yg ada folder cache misalnya idm. Data cache bisa dibuat kembali jika di akses, namu kadang ada sesuatu yg membuatnya error (salah 1 nya sever yg dituju down).

**Jelaskan solusi yg diinginkan**

Pindahkan folder cache ke folder desa.

**Apakah ada alternatif lain**

**Untuk versi OpenSID mana**

**Informasi tambahan**

**Comment by agungsugiarto** [comment]
Sudah diperbaiki
