### ISSUE TITLE
[SMS] Mekarkan modul SMS menjadi modul Hubung Warga

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#4481]
* Issue ini sudah dipecah menjadi tugas2 lebih kecil di https://github.com/orgs/OpenSID/projects/3/views/1 *

**Apa kekurangan yg ingin diatasi?**

Modul SMS menyediakan fitur untuk mengirim pesan ke warga, tanpa warga tersebut harus terdaftar sebagai pengguna layanan mandiri. Berpotensi digunakan untuk mengirim pemberitahuan dan berita penting kepada warga. Tetapi modul SMS hanya dapat mengirim pesan tersebut sebagai SMS ke HP warga. 

Menurut beberapa analisi telekomunikasi, tidak lama lagi SMS akan punah. Diperkirakan hanya sekitar 10% masyarakat yg masih menggunakan SMS. https://industri.kontan.co.id/news/bersiap-di-2020-tak-akan-lagi-layanan-sms-dan-telepon

Karena itu, modul SMS perlu dikembangkan supaya bisa mengirim pesan kepada warga menggunakan jalur komunikasi selain SMS.

**Jelaskan solusi yg diinginkan**

- [x] Ubah modul SMS menjadi modul Hubung Warga. 
- [x] Sediakan pengiriman pesan melalui email
- [x] Sediakan pengiriman pesan melalui Telegram
- [x] Sediakan pengiriman pesan melalui WA
- [x] SImpan informasi methoda hubung warga di data penduduk, termasuk email/no WA/Telegram.
- [x] Beri warga opsi cara mana yang mereka utamakan untuk menerima pesan
- [x] Sediakan fitur memilih metoda hubung di admin penduduk dan juga di layanan mandiri
- [x] Pengiriman melalui SMS bisa diaktifkan/dinonaktifkan oleh admin. Hanya dapat diaktifkan jika SMS gateway terpasang

**Apakah ada alternatif lain**

**Untuk versi OpenSID mana**

Sesudah v21.10-premium

**Informasi tambahan**

Contoh penyedia layanan WhatsApp: woo-wa.com 
http://api.woo-wa.com/#introduction

**Comment by eddieridwan** [comment]
Issue ini meneruskan permintaan di https://github.com/OpenSID/OpenSID/issues/3975. 
Issue #3975 akan ditutup, karena sudah tercakup di issue ini.

**Comment by ai-skematik** [comment]
sy sangat setuju ini., sebaiknya pemberitahunan seperti info kedukaan akan masuk sebagai notifikasi juga bagi yg memasang opensid mobile.

**Comment by agungsugiarto** [comment]
Pak @eddieridwan untuk modul SMS apakah dijadikan gateway atau tetap desa sendiri yg mengolola?

**Comment by eddieridwan** [comment]
@agungsugiarto , untuk tahap pertama, mohon batasi pada penambahan akun Telegram pada setiap penduduk. Kemudian di modul SMS sediakan pilihan supaya bisa kirim pesan ke akun Telegram atau email kontak, sebagai alternatif menggunakan SMS. Setelah ini dikerjakan, kita tinjau ulang lagi. 

Yaitu lihat solusi yg diinginkan di https://github.com/OpenSID/OpenSID/issues/4481#issue-1030972104 

Sangat mungkin kita tidak akan sediakan SMS gateway, karena seperti teman2 katakan, SMS sudah jarang digunakan.

**Comment by agungsugiarto** [comment]
Batasan issue yg saya usulkan untuk Telegram, Email dan WA tidak memungkinan dibuatkan fitur serupa dengan SMS yaitu pesan yg sudah terkirim dan tertunda, fitur ini akan dipangkas pak.

**Comment by eddieridwan** [comment]
Penambahan akun Telegram ke data penduduk telah dipisah ke Issue https://github.com/OpenSID/OpenSID/issues/4556.

**Comment by agungsugiarto** [comment]
Sudah di fitur premium melalui pr https://github.com/OpenSID/premium/pull/963
