### ISSUE TITLE
[Anjungan] Tambah fungsi anjungan selain untuk permohonan surat dapat digunakan untuk informasi publik, lapak, dll

### ISSUE THREAD

**Issue by ai-skematik** [OpenSID/OpenSID#4482]
**Apa kekurangan yg ingin diatasi?**

saat ini fungsi anjungan hanya sebatas permohonan surat sehingga fungsinya sangat sedikit jika dibanding dengan biaya yang dikeluarka oleh desa.

**Jelaskan solusi yg diinginkan**

tambah fungsi anjungan selain untuk pesan surat dapat juga digunakan untuk informasi publik, lapak dll.

**Apakah ada alternatif lain**

OpenSID dapat dipasang 2 tema, 1 tema untuk web, 1 untuk anjungan.,

**Untuk versi OpenSID mana**

**Informasi tambahan**

contoh anjungan yg menggunakan OpenSID hasil kreasi anggota komunitas

https://user-images.githubusercontent.com/48144047/138467624-bd350633-dec6-4bd2-9ddb-a19986e69d6d.mp4

**Comment by eddieridwan** [comment]
Bung @ai-skematik , issue ini perlu dipecah menjadi beberapa issue, untuk masing2 fitur yg diinginkan. Issue yg berisi banyak tugas tidak dapat diterapkan. Sebagai contoh, saya telah buatkan issue terpisah untuk menampilkan slides/video pada waktu anjungan kosong, di https://github.com/OpenSID/OpenSID/issues/4506.
