### ISSUE TITLE
[Telegram] Impor data penduduk berupa huruf tdk bisa untuk pendidikan_sedang, cacat, dlll

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#4486]
**Apa kekurangan yg ingin diatasi?**

Agar data berupa format huruf untuk kolom pendidikan sedang, cacat, dll tdk perlu di konfersi ke format angka.

**Jelaskan solusi yg diinginkan**

Lakukan impor data dengan menggunakan format huruf pada kolom pendidikan sedang, maka akan tampil error impor.

**Apakah ada alternatif lain**

**Untuk versi OpenSID mana**

**Informasi tambahan**

**Comment by andifahruddinakas** [comment]
Pak @eddieridwan, beberapa issue yg berkaitan dgn impor : 
https://github.com/OpenSID/OpenSID/issues/4369
https://github.com/OpenSID/OpenSID/issues/4392
https://github.com/OpenSID/OpenSID/issues/4353
https://github.com/OpenSID/OpenSID/issues/1032
https://github.com/OpenSID/OpenSID/issues/3830

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melalui pr https://github.com/OpenSID/premium/pull/451
