### ISSUE TITLE
[BUG] Eror Perekaman Foto Pada Menu Cepture

### ISSUE THREAD

**Issue by ompaydisgen** [OpenSID/OpenSID#4487]
**Eror Perekaman Foto Pada Menu Cepture**

**Posisi Eror**

**Hasil yg diharapkan**

**Tampakan layar dan log error**

**Versi OpenSID**

**Tema Yg Digunakan**

**Informasi tambahan**

**Comment by andifahruddinakas** [comment]
Silahkan dibuka kembali issue ini jika sudah dilengkapi.
