### ISSUE TITLE
SEGMENTASI DATA KHUSUS UNTUK DAERAH OTONOMI KHUSUS

### ISSUE THREAD

**Issue by ompaydisgen** [OpenSID/OpenSID#4488]
**Apa kekurangan yg ingin diatasi?**

**Jelaskan solusi yg diinginkan**

**Apakah ada alternatif lain**

**Untuk versi OpenSID mana**

**Informasi tambahan**

**Comment by andifahruddinakas** [comment]
Silahkan dibuka kembali issue ini jika sudah dilengkapi.
