### ISSUE TITLE
[BUG] Status Covid-19 Seluruhnya Menjadi Kontak Erat

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#4491]
**Jelaskan error yg dialami**

Ketika melakukan Penambahan Pemudik Covid-19 pada Menu Siaga Covid-19, seluruh penduduk yang dibuat, otomatis berstatus Kontak Erat dan Jika Penduduk tersebut di edti, terjadi error 500 dengan log sebagai berikut:

Severity: error --> Exception: Class 'CI_Controller' not found C:\laragon\www\premium\system\core\CodeIgniter.php 369

<img width="898" alt="screenshot_17" src="https://user-images.githubusercontent.com/46939846/138605105-5491c204-7d89-45f6-bb69-c994eadeee06.png">

**Cara untuk mereplikasi errornya**

**Hasil yg diharapkan**

Normal sebagaimana mestinya.

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki di `rilis-dev`
