### ISSUE TITLE
Penambahan format Surat/Formulir Kependudukan F1.01 s.d F1.07, F2.01 s.d F2.04 dan F2.10 sesuai Format terbaru dari Disdukcapil

### ISSUE THREAD

**Issue by kasipem331** [OpenSID/OpenSID#4493]
**Apa kekurangan yg ingin diatasi?**

**Jelaskan solusi yg diinginkan**

**Apakah ada alternatif lain**

**Untuk versi OpenSID mana**

**Informasi tambahan**

**Comment by andifahruddinakas** [comment]
Silahkan dilengkapi dlu issuenya.
