### ISSUE TITLE
[BUG] Link Edit Menu Kelompok

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#4494]
**Jelaskan error yg dialami**

Ketika ubah Menu dengan Jenis Link Kelompok, maka pada kolom Link seharusnya kelompok sudah terpilih sebelumnya.

**Cara untuk mereplikasi errornya**
Langkah untuk mereplikasi error yg dialami, misalnya:
1. Pergi ke halaman 'https://berputar.opensid.or.id/menu'
2. Klik tombol 'Tambah Menu'
3. Lalu pilih Jenis Link 'Kelompok'
4. Kemudian pada 'Pilihan Link' tentukan swalah 1 kelompok yang tersedia.
5. Simpan
6. Edit Menu tadi
7. Kolom Pilihan Link akan disuruh Pilih lagi. seharusnya berada pada pilihan Kelompok yang sudah ditentukan sebelumnya.

**Hasil yg diharapkan**

Normal sesuai seharusnya.

**Tampakan layar dan log error**
<img width="472" alt="screenshot_34" src="https://user-images.githubusercontent.com/46939846/138891699-734554b4-e9e7-495a-a5c6-be8ae1af7a82.png">

**Versi OpenSID**

Versi 21.10-premium-rev03

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui commit https://github.com/OpenSID/premium/commit/676c7c20ba54ce1fee9dfe8e024f7e377aa02c90
