### ISSUE TITLE
[Pembangunan] Penyesuaian Menu Pembangunan

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#4495]
**Apa kekurangan yg ingin diatasi?**

1. Pertama kali Menambah Data Pembanguan, agar pada kolom pilihan Tahun Anggaran secara default adalah tahun berjalan. Agar tidak gulir ke atas sejak 1999.
2. Untuk kolom Waktu agar dibuat Satuan Hari Kalender, menghindari penggunaan Desimal jika dilaksanakan seperti 22 Hari, 38 Hari dst.

<img width="753" alt="screenshot_36" src="https://user-images.githubusercontent.com/46939846/138902456-e13a896a-96bb-4d72-a4d6-f20b5e29d876.png">

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melalui pr https://github.com/OpenSID/premium/pull/452
