### ISSUE TITLE
[BUG] Tampilan data suplemen di web hanya menampilkan maksimum 20 data terdata

### ISSUE THREAD

**Issue by Jhiban-Khang** [OpenSID/OpenSID#4496]
**Jelaskan error yg dialami**

Data suplemen, jika ditampikan/dipublikasikan melalui tampilan web, hanya bisa menampilkan sampai 20 data saja, sebenarnya data di suplemen lebih dari 20. apakah ini bugs? atau memang didesain mentok sampai 20 saja?

**Cara untuk mereplikasi errornya**

Jika bugs, diharapkan bisa menampilkan data seluruhnya
!
**Hasil yg diharapkan**

**Tampakan layar dan log error**

![Screenshot at 2021-10-27 16-27-01](https://user-images.githubusercontent.com/19563843/139039583-aab24827-e228-4c3b-a894-c6e93f3fd3bc.png)
![Screenshot at 2021-10-27 16-27-12](https://user-images.githubusercontent.com/19563843/139039598-caa79652-4463-4c98-aab6-7d92c02c87d7.png)

**Versi OpenSID**

Versi Demo OpenSID 21.10 umum

**Tema Yg Digunakan**

**Informasi tambahan**

**Comment by agungsugiarto** [comment]
@Jhiban-Khang terima kasih sudah melaporkan issue, issue ini saya tutup karena tidak temukan di versi premium, untuk rilis versi umum silahkan menunggu rilis v21.12 untuk perbaikian tersebut. Selengkapnya https://github.com/OpenSID/OpenSID/wiki/Rilis-Umum-Yang-Akan-Datang

Terima kasih
