### ISSUE TITLE
[Template Surat] Surat Keterangan Nikah & Form F2.12 untuk Warga Non Muslim

### ISSUE THREAD

**Issue by emanuel-simon** [OpenSID/OpenSID#4497]
**Apa kekurangan yg ingin diatasi?**

Belum ada Surat Keterangan Nikah dan Lampirannya yaitu Form F-2.12 untuk pengurusan Akta Nikah bagi warga non Muslim di Layanan Surat

**Jelaskan solusi yg diinginkan**

- Sediakan Surat Keterangan Nikah berserta lampirannya formulir F-2.12 di Layanan Surat
- [PERMENDAGRI NO 19 TAHUN 2010 tentang FORMULIR DAN BUKU YANG DIGUNAKAN DALAM PENDAFTARAN PENDUDUK DAN PENCATATAN SIPIL](https://dukcapil.kemendagri.go.id/arsip/detail/23/permendagri-no-19-tahun-2010)
- [contoh suket nikah.docx](https://github.com/OpenSID/OpenSID/files/7434949/contoh.suket.nikah.docx)
- [F-2.12_FORMULIR_PENCATATAN_PERKAWINAN.pdf](https://github.com/OpenSID/OpenSID/files/7434952/F-2.12_FORMULIR_PENCATATAN_PERKAWINAN.pdf)

**Apakah ada alternatif lain**

Tidak ada solusi lain

**Untuk versi OpenSID mana**

v21.11-premium

**Informasi tambahan**

Fitur ini sangat dibutuhkan terutama di daerah mayoritas non Muslim

**Comment by kasipembatungsel** [comment]
untuk di daerah bali yang mayoritas beragama non muslim khusu untuk daerah kabupaten tabanan, adapaun persyaratan yang diperlukan untuk menerbitkan kutipan akta perkawinan yaitu,
1.  F-1.12
2. surat belum pernah kawin/menikah
3. surat ijin orang tua bagi yang berusia 19 - 21 tahun,
4. surat pernyataan kedua mempelai
5. surat keteranggan perkawinan umat hindu ( bagi masyarakat beragama hindu )
 sebagai refrensi akan saya lampirkan blangko yang di berikan oleh dukcapil tabanan
[akta kawin perbaikan.pdf](https://github.com/OpenSID/OpenSID/files/7445692/akta.kawin.perbaikan.pdf)

**Comment by emanuel-simon** [comment]
> untuk di daerah bali yang mayoritas beragama non muslim khusu untuk daerah kabupaten tabanan, adapaun persyaratan yang diperlukan untuk menerbitkan kutipan akta perkawinan yaitu,
> 
> 1. F-1.12
> 2. surat belum pernah kawin/menikah
> 3. surat ijin orang tua bagi yang berusia 19 - 21 tahun,
> 4. surat pernyataan kedua mempelai
> 5. surat keteranggan perkawinan umat hindu ( bagi masyarakat beragama hindu )
>    sebagai refrensi akan saya lampirkan blangko yang di berikan oleh dukcapil tabanan
>    [akta kawin perbaikan.pdf](https://github.com/OpenSID/OpenSID/files/7445692/akta.kawin.perbaikan.pdf)

boleh ajak teman-teman yang lain untuk like issue ini, bli @kasipembatungsel
