### ISSUE TITLE
[Bug] Pengubahan data survei analisis menghasilkan data duplikat

### ISSUE THREAD

**Issue by afri18** [OpenSID/OpenSID#4498]
**Apa kekurangan yg ingin diatasi?**
 Kadang pengisian survey tidak selesai sudah disimpan (karna pertanyaan banyak atau ada keperluan mendesak), bila dilain waktu melanjutkan survey dan menyimpannya maka akan terdapat 2 data untuk objek yang sama

**Jelaskan solusi yg diinginkan**
 
![image](https://user-images.githubusercontent.com/6611881/139357720-3eb91be7-3961-4d63-a9d4-9c8a331832b4.png)

**Apakah ada alternatif lain**

**Untuk versi OpenSID mana**

v21.10 umum

**Informasi tambahan**

**Comment by eddieridwan** [comment]
Pastikan bahwa ini memang bug. Bisa jadi masalah karena kondisi data pada bung @afri18

**Comment by afri18** [comment]
![image](https://user-images.githubusercontent.com/6611881/140001320-d1b34273-9e4d-4eec-a8e6-a3b6824a7d0b.png)
 saya coba jajal di https://demo.opensid.or.id hasil sama

**Comment by andifahruddinakas** [comment]
Ya, waktu sy coba akan jadi duplikasi dati untuk data survey yang di ubah untuk isian text dan number.

**Comment by afri18** [comment]
saya amati itu seakan disurvey 2 x, karna perintahnya SIMPAN
