### ISSUE TITLE
[BUG] Beberapa Data Tidak Muncul di Suket Kelahiran Dan Lampiran F-2.01

### ISSUE THREAD

**Issue by emanuel-simon** [OpenSID/OpenSID#4499]
**Jelaskan error yg dialami**

Ada beberapa data yang tidak muncul di Surat Keterangan Kelahiran dan Lampiran f-kelahiran

**Cara untuk mereplikasi errornya**

- Pergi ke Layanan Surat - Cetak Surat - Surat Keterangan Kelahiran
- Isi semua data yang dibutuhkan
- Unduh .rtf
- Buka hasil unduhan dan akan terlihat data-data ada yang tidak tampil

**Hasil yg diharapkan**

Template surat beserta lampiran .pdf dapat diperbaiki

**Tampakan layar dan log error**

![IMG_20211029_132845_359.jpg](https://user-images.githubusercontent.com/48465803/139381396-e413435e-44eb-47a8-865e-356132bb38c0.jpg)
![IMG_20211029_133558_247.jpg](https://user-images.githubusercontent.com/48465803/139381444-be200dec-4d46-480c-a720-14339afebecb.jpg)
![IMG_20211029_133602_160.jpg](https://user-images.githubusercontent.com/48465803/139381473-21c4f187-afe4-4bbd-b400-a6da1104c757.jpg)

**Versi OpenSID**

v21.10-premium

**Tema Yg Digunakan**

Natra v4.5

**Informasi tambahan**

NIK sementara juga sebaiknya tidak dimunculkan di hasil f-kelahiran

**Comment by andifahruddinakas** [comment]
Pak @MantoAta Sy coba di https://berputar.opensid.or.id/surat/form/surat_ket_kelahiran yg data yang tidak lengkap hanya pada bagian lampiran (kode wilayah, nokkk dan nama kk) selain itu tersisi dengan benar.

Bisa cek hasil unduhan berikut : 
[surat_ket_kelahiran_0720814200200001_2021-11-14_387.zip](https://github.com/OpenSID/OpenSID/files/7533359/surat_ket_kelahiran_0720814200200001_2021-11-14_387.zip)

**Comment by emanuel-simon** [comment]
Pak @andifahruddinakas saya coba di nihaone.desa.id juga sudah normal pak. Aplikasinya v.21.11-premium rev 01.

Saya tutup saja ya pak issue nya pak

**Comment by andifahruddinakas** [comment]
> Pak @andifahruddinakas saya coba di nihaone.desa.id juga sudah normal pak. Aplikasinya v.21.11-premium rev 01.
> 
> Saya tutup saja ya pak issue nya pak

Jangan ditutup, krn ada yg perlu diperbaiki. Nanti sy sesuaikan sj judulnya.

**Comment by emanuel-simon** [comment]
> > Pak @andifahruddinakas saya coba di nihaone.desa.id juga sudah normal pak. Aplikasinya v.21.11-premium rev 01.
> > 
> > Saya tutup saja ya pak issue nya pak
> 
> Jangan ditutup, krn ada yg perlu diperbaiki. Nanti sy sesuaikan sj judulnya.

Siap pak @andifahruddinakas

**Comment by andifahruddinakas** [comment]
Untuk perbaikan lainnya, bisa di buat di issue baru.
