### ISSUE TITLE
[Bug] Status Hubungan Keluarga Perlu disesuaikan

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#4502]
**Apa kekurangan yg ingin diatasi?

Status Hubungan Keluargayang ada di Aplikasi OpenSID dengan di SIAK Dukcapil terdapat perbedaan

**Jelaskan solusi yg diinginkan**

**Apakah ada alternatif lain**

![status hubungan di opensid](https://user-images.githubusercontent.com/25834335/139542921-9c4c7519-3b0f-4376-92be-c6fb6178139b.jpg)

![status hubungan di siak](https://user-images.githubusercontent.com/25834335/139542925-5df73784-d934-4a62-823e-cd8fb14ef4ca.jpg)

**Untuk versi OpenSID mana**

**Informasi tambahan**

**Comment by andifahruddinakas** [comment]
Pak @eddieridwan, berkaitan dengan issue https://github.com/OpenSID/premium/issues/393 tp scr luas.
