### ISSUE TITLE
[Bug] Latar Belakang Halaman Login dan Layanan Mandiri hanya bisa diubah satu kali

### ISSUE THREAD

**Issue by mr703** [OpenSID/OpenSID#4503]
### Bagaimana alurnya sampai muncul masalah?
Setelah di robah latar login dan layanan mandiri di Pengaturan Aplikasi, latar tidak dapat lagi di robah, atau tidak mau menyimpan gambar lainnya ketika dirobah

### Seperti apa yang diharapkan?

Bisa di robah sesuai dengan keinginan
### Apa yang terjadi?
Gambar latar tidak bisa dirobah utk kedua kalinya

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by andifahruddinakas** [comment]
Pak @mr703, mohon dilengkapi issuenya. OpenSID versi berapa yg digunakan agar mepermudah pengecekan.

**Comment by agungsugiarto** [comment]
Pak @mr703 terima kasih sudah melaporkan issue. Issue ini saya tutup karena tidak menemukan masalah yg dimaksud, mohon pastikan melalukan clear cache pada browser untuk melihat perubahan.
