### ISSUE TITLE
[Anjungan] Tambah fitur tampilan slides/video di anjungan pada sast tidak digunakan

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#4506]
**Apa kekurangan yg ingin diatasi?**

Saat ini jika anjungan sedang kosong, tampilan statis pada halaman login mandiri. Sebaiknya waktu kosong tersebut dimanfaatkan untuk menampilkan informasi atau tayangan menarik.

**Jelaskan solusi yg diinginkan**

Sediakan pengaturan untuk menampilkan galeri atau video untuk ditayangkan di anjungan jika anjungan kosong. Jika layar/keyboard disentuh, tampilan akan kembali ke halaman login mandiri.

**Untuk versi OpenSID mana**

pasca v21.11-premium

**Informasi tambahan**

contoh anjungan yg menggunakan OpenSID hasil kreasi anggota komunitas. Hubungi anggota komunitas ini untuk diajak mengirim kontribusi fitur ini kepada OpenSID.

https://user-images.githubusercontent.com/48144047/138467624-bd350633-dec6-4bd2-9ddb-a19986e69d6d.mp4

**Comment by FirlianiF** [comment]
tes komentar
