### ISSUE TITLE
[Peta] Bisa atur jenis garis dan ketebalan tipe garis di pengaturan peta

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#4507]
**Apa kekurangan yg ingin diatasi?**

Saat ini pengaturan Tipe Garis di Pengaturan Peta terbatas pada warna saja. Diperlukan pengaturan tambahan untuk mengitkuti standar yg umum digunakan untuk membedakan garis untuk jalan raya, jalan setapak, pembatas dll.

**Jelaskan solusi yg diinginkan**

Tambahkan pengaturan tipe garis untuk:

1. ketebalan garis
2. jenis garis (solid, dash, dot, dsbnya)

Gunakan pilihan dan peristilahan yg standar untuk pengaturan seperti ini.

**Untuk versi OpenSID mana**

pasca v21.10-premium

**Informasi tambahan**

Saat ini pengguna menggunakan fitur area untuk mengatasi keterbatasan yg ada.

**Comment by andifahruddinakas** [comment]
![contoh](https://user-images.githubusercontent.com/57283157/145770233-5d4ffc1a-d512-491d-b157-127f5f322339.png)

1. buat kolom ukuran_garis.
2. tambahkan inputan ukuran garis pada saat tambah atau ubah data garis.
3. pada peta.js, function set_marker_garis(), 
```
var garis_style = {
				stroke: true,
				opacity: 1,
				weight: 10,
				color: daftar[x].color
			}
```
ganti nilai `weight` berdasarkan data kolom ukuran_garis.

**Comment by FirlianiF** [comment]
noted

**Comment by andifahruddinakas** [comment]
https://stackoverflow.com/questions/47229723/how-to-style-path-in-leaflet

**Comment by andifahruddinakas** [comment]
Sudah digabunkan ke FITUR PREMIUM melalui PR https://github.com/OpenSID/premium/pull/528
