### ISSUE TITLE
Tambah tombol melampirkan dokumen di form isian data penduduk

### ISSUE THREAD

**Issue by afri18** [OpenSID/OpenSID#451]
tambahkan tombol untuk melampirkan dokumen saat input/edit biodata penduduk
![image](https://user-images.githubusercontent.com/6611881/26858565-14b89706-4b5c-11e7-9278-3c228720e86b.png)
nantinya Photocopy dokumen dilampirkan dari sini, mulai dari akte kelahiran sampai akta nikah dan kematian

**Comment by afa28** [comment]
Ini kyaknya sudah ada di versi terbaru pak @afri18 , walau di tempatkan terpisah.

**Comment by afri18** [comment]
ya sudah ada, berarti sudah bisa di tutup
