### ISSUE TITLE
[Template Surat] Surat nikah pilih penduduk calon perempuan dari desa

### ISSUE THREAD

**Issue by RagaKyud** [OpenSID/OpenSID#4511]
Surat keterangan nikah pada layanan mandiri

### Bagaimana alurnya sampai muncul masalah?
untuk pasangan wanita dari desa tidak muncul ketika dipilih

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 21.11
| Versi PHP        |  7.2
| System operasi   | win 7 xampp
![d91687e8-8139-4b03-8d95-e9fe9b9f932c](https://user-images.githubusercontent.com/73992995/139632406-33c33b96-6c51-4fc5-ae0c-8f674f11b2b6.jpg)

**Comment by eddieridwan** [comment]
@RagaKyud apakah masalah ini bisa direplikasi di https://demo.opensid.or.id atau https://berputar.opensid.or.id?
Kalau tidak, masalah ada di sistem anda.
