### ISSUE TITLE
[Template Surat] Formulir F-1.05 Surat Pernyataan Perubahan Data Kependudukan

### ISSUE THREAD

**Issue by emanuel-simon** [OpenSID/OpenSID#4515]
**Apa kekurangan yg ingin diatasi?**

Terkadang terjadi kesalahan di dokumen kependudukan, untuk bisa merubahnya diperlukan Surat Pernyataan Perubahan Data Kependudukan F-1.05, dan form ini belum tersedia di Layanan Surat

**Jelaskan solusi yg diinginkan**

Disediakan Surat Pernyataan Perubahan Data Kependudukan F-1.05
[SURAT PERNYATAAN PERUBAHAN DATA KEPENDUDUKAN F-1.05.pdf](https://github.com/OpenSID/OpenSID/files/7475815/SURAT.PERNYATAAN.PERUBAHAN.DATA.KEPENDUDUKAN.F-1.05.pdf)

**Apakah ada alternatif lain**

**Untuk versi OpenSID mana**

v21.12

**Informasi tambahan**

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1839
