### ISSUE TITLE
[BUG] DATA TIDAK MUNCUL DI HASIL DOWNLOAD SUKET PINDAH PENDUDUK

### ISSUE THREAD

**Issue by emanuel-simon** [OpenSID/OpenSID#4516]
**Jelaskan error yg dialami**

HASIL UNDUHAN SUKET PINDAH PENDUDUK BESERTA LAMPIRANNYA HANYA BERUPA FORM KOSONG, DATA YANG DIINPUT DI LAYANAN SURAT TIDAK MUNCUL

**Cara untuk mereplikasi errornya**

1.   PERGI KE https://berputar.opensid.or.id/surat DAN PILIH SURAT KETERANGAN PINDAH PENDUDUK
2.   ISI SEMUA DATA YANG DIBUTUHKAN
3.   UNDUH RTF
4.   BUKA HASIL UNDUHAN, FILE RTF DAN PDF TIDAK TERISI DATA

**Hasil yg diharapkan**

DIPERBAIKI AGAR DATA BISA TAMPIL, KARNA SURAT INI SERING DIBUTUHKAN WARGA DESA
**Tampakan layar dan log error**

HASIL UNDUHAN DARI https://berputar.opensid.or.id/
[surat_ket_pindah_penduduk__2021-11-05__1.zip](https://github.com/OpenSID/OpenSID/files/7480473/surat_ket_pindah_penduduk__2021-11-05__1.zip)

HASIL UNDUHAN DARI https://nihaone.opendesa.id
[surat_ket_pindah_penduduk__2021-11-05_.zip](https://github.com/OpenSID/OpenSID/files/7480475/surat_ket_pindah_penduduk__2021-11-05_.zip)

**Versi OpenSID**

V.21-10-PREMIUM & V.21-11-PREMIUM

**Tema Yg Digunakan**

NATRA 

**Informasi tambahan**

**Comment by andifahruddinakas** [comment]
Pak @MantoAta, sy coba aman sj di https://berputar.opensid.or.id/surat/form/surat_ket_pindah_penduduk

Ini hasilnya : 
[surat_ket_pindah_penduduk_1108042506909995_2021-11-14_386.zip](https://github.com/OpenSID/OpenSID/files/7533331/surat_ket_pindah_penduduk_1108042506909995_2021-11-14_386.zip)

Untuk ubahan desa, perlu disesuaikan jika ada perubahan format template pada surat bawaan.

**Comment by emanuel-simon** [comment]
> Pak @MantoAta, sy coba aman sj di https://berputar.opensid.or.id/surat/form/surat_ket_pindah_penduduk
> 
> Ini hasilnya : 
> [surat_ket_pindah_penduduk_1108042506909995_2021-11-14_386.zip](https://github.com/OpenSID/OpenSID/files/7533331/surat_ket_pindah_penduduk_1108042506909995_2021-11-14_386.zip)
> 

Saya coba 9 hari yang lalu pak @andifahruddinakas , apa mungkin sudah diperbaiki?
Saya pakai template surat bawaan dari OpenSID, bukan gubahan sendiri

**Comment by andifahruddinakas** [comment]
> > Pak @MantoAta, sy coba aman sj di https://berputar.opensid.or.id/surat/form/surat_ket_pindah_penduduk
> > Ini hasilnya :
> > [surat_ket_pindah_penduduk_1108042506909995_2021-11-14_386.zip](https://github.com/OpenSID/OpenSID/files/7533331/surat_ket_pindah_penduduk_1108042506909995_2021-11-14_386.zip)
> 
> Saya coba 9 hari yang lalu pak @andifahruddinakas , apa mungkin sudah diperbaiki? Saya pakai template surat bawaan dari OpenSID, bukan gubahan sendiri

Web  https://berputar.opensid.or.id/ terbaru hari ini dengan perbaikan bugs, tp tidak ada perbaikan mengenai masalah ini. Mungkin bisa di cek lg, jika tdk ada masalah, issuenya bisa di tutup.

**Comment by emanuel-simon** [comment]
> > > Pak @MantoAta, sy coba aman sj di https://berputar.opensid.or.id/surat/form/surat_ket_pindah_penduduk
> > > Ini hasilnya :
> > > [surat_ket_pindah_penduduk_1108042506909995_2021-11-14_386.zip](https://github.com/OpenSID/OpenSID/files/7533331/surat_ket_pindah_penduduk_1108042506909995_2021-11-14_386.zip)
> > 
> > Saya coba 9 hari yang lalu pak @andifahruddinakas , apa mungkin sudah diperbaiki? Saya pakai template surat bawaan dari OpenSID, bukan gubahan sendiri
> 
> Web  https://berputar.opensid.or.id/ terbaru hari ini dengan perbaikan bugs, tp tidak ada perbaikan mengenai masalah ini. Mungkin bisa di cek lg, jika tdk ada masalah, issuenya bisa di tutup.

Ok pak @andifahruddinakas , saya coba dulu di nihaone.desa.id ya

**Comment by emanuel-simon** [comment]
Barusan saya coba surat pindah ini juga datanya sudah muncul dengan benar pak @andifahruddinakas di v.21.11-premium rev 01

**Comment by andifahruddinakas** [comment]
> Barusan saya coba surat pindah ini juga datanya sudah muncul dengan benar pak @andifahruddinakas di v.21.11-premium rev 01

ok
