### ISSUE TITLE
Tambah Anggota Baru dengan NIK 0 Gagal

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#4517]
### Bagaimana alurnya sampai muncul masalah?
Ketika menambahkan penduduk dengan NIK 0 di OpenSID versi 21.11 umum gagal 
![image](https://user-images.githubusercontent.com/25834335/140534977-6de16c86-227d-4cf0-9222-15a33f8ede81.png)

### Seperti apa yang diharapkan?
bisa menambahkan penduduk dengan NIK 0

### Apa yang terjadi?
Tidak bisa tambah penduduk

### Informasi tambahan 
terjadi juga di https://demo.opensid.or.id
| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 21.11-umum 
| Versi PHP        | 
| System operasi   |

**Comment by andifahruddinakas** [comment]
Sudah di perbaiki di versi 21.05-premium dan akan digabungkan ke rilis v21.12.
