### ISSUE TITLE
[Template Surat] Penambahan Lampiran Surat Keterangan Pindah Datang Penduduk F-1.27, F-1.31, F-1.39

### ISSUE THREAD

**Issue by macaksibuk** [OpenSID/OpenSID#4518]
**Apa kekurangan yg ingin diatasi?**

Selain Lampiran Formulir Surat Keterangan Pindah Penduduk **(F-1.23, F-1.25, F-1.29, F-1.34)**
Perlu juga Lampiran Formulir Surat Keterangan Pindah Datang Penduduk, yang saya lihat saat ini memang sudah ada dengan kode Lampiran Formulir Surat Keterangan Pindah Datang Penduduk (F-1.08), tapi tidak semua Desa telah menerapkan Lampiran Formulir Surat Keterangan Pindah Datang Penduduk untuk pengajuan ke Kecamatan, misalnya Desa pada Kecamatan Kami masih banyak menggunakan Formulir Surat Keterangan Pindah Datang Penduduk dengan Kode dibawah ini:

- Formulir Antar Desa atau Kelurahan Dalam Satu Kecamatan F-1.27
- Formulir Antar Kecamatan Dalam Satu Kabupaten (Kota) F-1.31
- Formulir Antar Kabupaten (Kota) atau Antar Provinsi F-1.39

**Jelaskan solusi yg diinginkan**

- Contoh Formulir Antar Desa atau Kelurahan Dalam Satu Kecamatan F-1.27

![F-1 27](https://user-images.githubusercontent.com/90369755/140590534-33725d80-141d-45a6-81b0-ef33f11f4717.jpg)

- Formulir Antar Kecamatan Dalam Satu Kabupaten (Kota) F-1.31

![F-1 31](https://user-images.githubusercontent.com/90369755/140590624-9e77d056-12bb-4910-b54a-aa12f643ebff.jpg)

- Formulir Antar Kabupaten (Kota) atau Antar Provinsi F-1.39

![F-1 39](https://user-images.githubusercontent.com/90369755/140590578-66f90dc9-743e-4618-b3b5-78bc1b95b13f.jpg)

**Ambil Contoh Petunjuk Pengisian Formulir Pada Kode F-1.27**
_Pertama,_
![1](https://user-images.githubusercontent.com/90369755/140590672-983ff682-d60a-4d7b-8eb6-48422d23f6b7.jpg)
_Kedua,_
![2](https://user-images.githubusercontent.com/90369755/140590717-62833201-f6d0-4078-a1db-9960927ddf8a.jpg)

YANG MEMBEDAKAN FORMULIR SURAT KETERANGAN PINDAH DATANG PENDUDUK PADA KODE SURATNYA, SEHINGGA NANTI SECARA OTOMATIS BERPENGARUH PADA ALAMAT DI ATAS JUDUL SURAT YANG SECARA OTOMATIS MENYESUAIKAN DAERAHNYA.

![Alamat Diatas Judul Surat](https://user-images.githubusercontent.com/90369755/140590893-5797036c-4c9a-4654-8ab1-cdd4813e67e1.JPG)

**Untuk versi OpenSID mana**
Fitur ini diusulkan untuk versi Rilis Umum (mis v21.11-umum) atau Rilis Premium (mis v21.11-premium)

TERIMA KASIH ATAS BANTUAN PARA RELAWAN OPENSID.
SEMOGA SELURUH YANG MEMBANTU MENGURUSI DAN MENOLONG OPENSID INI SENANTIASA DIBERIKAN KESEHATAN.
DAN KELUARGANYA SELALU DILANCARKAN SEGALA URUSANNYA.

**Comment by macaksibuk** [comment]
MOHON MAAF, JIKA KESULITAN UNTUK MENGGABUNGKAN FITUR INI PADA SURAT PINDAH YANG SUDAH ADA.
BISA JUGA UNTUK MENAMBAHKAN SURAT BARU DENGAN NAMA SURAT **SURAT KETERANGAN PINDAH DATANG PENDUDUK**.
KARENA ADA SUB FORM :
**DATA DAERAH TUJUAN**

**Comment by astonialam** [comment]
Saya Penggunan Baru, cara downloadnya gimana.?

**Comment by macaksibuk** [comment]
> Saya Penggunan Baru, cara downloadnya gimana.?

Apa yang Bapak maksud?
Download Aplikasi OpenSID/Download surat tersebut?

**Comment by astonialam** [comment]
Ini sangat di butuhkan di desa kami..

**Comment by astonialam** [comment]
> > Saya Penggunan Baru, cara downloadnya gimana.?
> 
> Apa yang Bapak maksud? Download Aplikasi OpenSID/Download surat tersebut?

Surat nya pak..

**Comment by macaksibuk** [comment]
> > > Saya Penggunan Baru, cara downloadnya gimana.?
> > 
> > 
> > Apa yang Bapak maksud? Download Aplikasi OpenSID/Download surat tersebut?
> 
> Surat nya pak..

Semoga apa yang Desa Bapak dan Desa lain inginkan perihal issue ini segera terealisasikan...
**SEMOGA SELURUH YANG MEMBANTU MENGURUSI DAN MENOLONG OPENSID INI SENANTIASA DIBERIKAN KESEHATAN.
DAN KELUARGANYA SELALU DILANCARKAN SEGALA URUSANNYA.**

**Comment by kasipembatungsel** [comment]
ya desa saya juga butuh format yg di usulkan

**Comment by eddieridwan** [comment]
Tugas ini telah dialokasikan kepada @FirlianiF

**Comment by eddieridwan** [comment]
@FirlianiF @andifahruddinakas , perhatikan referensi https://disdukcapil.purworejokab.go.id/formulir/. Di situ tidak terdaftar F-1.27, F-1.31 ataupun F-1.39. Untuk pindah datang, yg terdaftar adalah F-1.23 (pindah datang satu desa). Tetapi sepertinya yg lain itu variasi saja berdasarkan asal pindahnya. Sama halnya seperti untuk pindah keluar desa yg sudah ada di OpenSID. 

Meskipun demikian, ada baiknya konsultasi dengan yg meminta dan juga perangkat desa di grup pengguna Premium.

**Comment by FirlianiF** [comment]
Sudah selesai dikerjakan, mohon di review mas @andifahruddinakas

**Comment by FirlianiF** [comment]
Sudah masuk di fitur premium https://github.com/OpenSID/premium/pull/504
