### ISSUE TITLE
Sinkronisasi offline dgn online

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#452]
Mengingat banyaknya desa yg belum memiliki jaringan internet, baiknya dibuatkan singkronisasi database offline dgn onlline tdk ubahnya seperti program DAPODIK

**Comment by alghozi** [comment]
Ayo segera dibuatkan..

**Comment by eddieridwan** [comment]
@alghozi heheh... jika anda membantu atau mencarikan programmer yang bersedia mengerjakan, pasti bisa... ayo, silakan bantu.

**Comment by andanwar** [comment]
Bagaimana jika singkronisasinya database nya dengan dropbox..jadi harus instal dropbox dan file database yg disam teesimpan di dropbox..ya ttap si harus bersedia online berkala..gman

**Comment by simasta** [comment]
Untuk folder desa mungkin bisa dengan dropbox, tetapi untuk sql nya sampe saat ini masih jarang hosting yang memperbolehkan remote mysql, jadi mungkin slusinya melalui import sql

**Comment by casesol** [comment]
> Untuk folder desa mungkin bisa dengan dropbox, tetapi untuk sql nya sampe saat ini masih jarang hosting yang memperbolehkan remote mysql, jadi mungkin slusinya melalui import sql

hosting kelas premium bisa pak

**Comment by eddieridwan** [comment]
Duplikatnya #2048. Yang ini ditutup.
