### ISSUE TITLE
[Surat] Penambahan Fitur Pembuatan Surat Baru tanpa Coding

### ISSUE THREAD

**Issue by pemdeskasokandel** [OpenSID/OpenSID#4520]
Apa kekurangan yg ingin diatasi?

(Penambahan fitur pembuatan surat baru tanpa coding)

Jelaskan solusi yg diinginkan
(Banyak yang ingin membuat surat ke desa dengan format tersendiri)

Apakah ada alternatif lain
(harus bisa coding)

Untuk versi OpenSID mana

Fitur ini diusulkan untuk versi Rilis Umum (mis. v21.11) atau Rilis Premium (mis v21.11-premium) yg mana?
-->

**Informasi tambahan**

**Comment by andifahruddinakas** [comment]
https://m.facebook.com/groups/OpenSID/permalink/1920140864817552/
