### ISSUE TITLE
Penulisan Kalimat NIP Pada Tanda Tangan Surat

### ISSUE THREAD

**Issue by zbinggor** [OpenSID/OpenSID#4521]
**Jelaskan error yg dialami**
Untuk desa yang Kepala Desa tidak memiliki NIP dan sekertaris Desa memiliki NIP, ketika pembuatan surat yang di tandatangani oleh Kepala Desa maka masih terdapat tulisan/Kalimat NIP dibawah ttd kepala desa tetai "nomor NIP" kosong karena memang kepala desa tidak memiliki Nomor NIP. dan apabila ada lapiran yang bentuknya pdf akan kesulitan untuk mengedit tulisan/kalimat NIP tersebut.

**Cara untuk mereplikasi errornya**

Langkah untuk mereplikasi error yg dialami, misalnya:
1. Pergi ke halaman 'Layanan Surat > Cetak Surat > Buat Surat'
2. Klik tombol 'Unduh RTF'
3. ketika yang tanda tangan adalah sekertaris Desa, maka Normal terdapat kalimat NIP diikuti nomor NIP nya
4. ketika yang bertanda tangan adalah Kepala Desa Maka RANCU terdapat tulisan/kalimat NIP tnpa nomor NIP

**Hasil yg diharapkan**
Ketika yang bertanda tangan memiliki nomor NIP maka tertulis NIP diikuti nomor NIP, tetapi Ketika yang bertanda tanga  tidak memiliki nomor NIP maka tidak tertulis kalimat NIP

**Tampakan layar dan log error**

**Versi OpenSID**

v21.11-premium

**Tema Yg Digunakan**
DeNatra

**Informasi tambahan**

**Comment by andifahruddinakas** [comment]
Pernah dibahas di PR https://github.com/OpenSID/premium/pull/338

**Comment by eddieridwan** [comment]
@andifahruddinakas , apakah https://github.com/OpenSID/premium/pull/338#pullrequestreview-735639717 dan https://github.com/OpenSID/premium/pull/338#issuecomment-903379711 sudah diterapkan? Jika sudah, maka tulisan NIP tidak akan tampil jika tidak ada NIP/NIPD.

**Comment by andifahruddinakas** [comment]
> 

Untuk PR https://github.com/OpenSID/premium/pull/338 dan mengenai NIP/NIPD pernah dibahas dan di close saat pertemuan, tp sy lupa alasannya apa. Mungkin mas @agungsugiarto masih ingat.

**Comment by agungsugiarto** [comment]
Sudah masuk ke rilis premium melalui pr https://github.com/OpenSID/premium/pull/571
