### ISSUE TITLE
[BUG] Hari salah untuk tgl perjanjian di naskah Kesepakatan Kerjasama

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#4523]
**Jelaskan error yg dialami**

Dokumen Kesepakatan Kerjasama yg diunduh pada waktu melakukan pendaftaran berisi kesalahan berikut: nama hari perjanjian berbeda dengan tanggal perjanjian.

**Cara untuk mereplikasi errornya**

Lakukan pendaftaran kerjasama.
Unduh dokumen kesepakatan kerjasama.
Periksa hari dan tanggal perjanjian.
Terlihat salah. Tg 7 November seharusnya bukan Kamis

![2021-11-07 17 56 36](https://user-images.githubusercontent.com/249563/140635593-5bcd5e41-e757-494d-9a4f-19c4c2a71369.jpg)

**Hasil yg diharapkan**

Hari sesuai dengan tanggal.

**Versi OpenSID**

v21.11-premium

**Informasi tambahan**

**Comment by pemdesbatajawa** [comment]
Apakah Bisa Di Sesuaikan Dengan Tanggal Di tandatanganinya Dokumen Ini ? Dan Bisakah Di tandatangani Oleh Sekretaris Desa?
