### ISSUE TITLE
[BUG] GAGAL menambahkan anggota keluarga

### ISSUE THREAD

**Issue by hasap86** [OpenSID/OpenSID#4526]
**Jelaskan error yg dialami**

GAGAL menambahkan anggota keluarga pada menu Keluarga

**Cara untuk mereplikasi errornya**
Langkah untuk mereplikasi error yg dialami, misalnya:
1. Pergi ke halaman 'KELUARGA'
2. Klik tombol 'TAMBAH ANGGOTA'

**Hasil yg diharapkan**

**Tampakan layar dan log error**

**Versi OpenSID**

Versi 21.11

**Tema Yg Digunakan**

COSMO

**Informasi tambahan**

**Comment by andifahruddinakas** [comment]
Sudah di perbaiki di versi 21.05-premium dan akan digabungkan ke rilis v21.12
