### ISSUE TITLE
[Layanan Mandiri] PIN Layanan Mandiri

### ISSUE THREAD

**Issue by mr703** [OpenSID/OpenSID#4529]
### Bagaimana alurnya sampai muncul masalah?
Masuk dengan e-KTP tidak bisa langsung Login kedalam Layanan Mandiri, diperlukan penginputan PIN Layanan Secara Manual, Sehingga tidak efisien secara waktu

### Seperti apa yang diharapkan?
Dengan 2 Kali Tap pada pembaca KTP, User/Masyarakat dapat langsung login ke Layanan Mandiri, ID Tag dan PIN bisa disamakan, Sehingga lebih Efisien

### Apa yang terjadi?
Masyarakat Tetap menggunakan Inputan PIN, Sehingga Lama.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 21.11 Premium
| Versi PHP        | 
| System operasi   |
![image](https://user-images.githubusercontent.com/50432012/141117235-c591a89f-39e0-4434-8e51-4978001ac9c2.png)

**Comment by zickkeen** [comment]
menurut saya pin masih tetap dibutuhkan sebagai security, mengingat pembacaan ektp berupa tagid yang dapat dimanfaatkan oleh siapapun yang mengetahui tagid nya.

**Comment by andifahruddinakas** [comment]
Silahkan di daftarkan jadi anjungan agar tidak perlu input PIN lg.

https://github.com/OpenSID/OpenSID/wiki/Anjungan

**Comment by mr703** [comment]
Ini sudah didaftarkan jadi anjungan, 
ADM pun sudah ada,,
Login pakai eKTP tetap memerlukan PIN,, 
Setidaknya PIN Layanan dapat lebih dari 6..

**Comment by ai-skematik** [comment]
silahkan baca panduan bung,

**Comment by ai-skematik** [comment]
![IMG_20211012_212810_527.jpg](https://user-images.githubusercontent.com/48144047/143529816-5b731b8b-8ef9-4ef9-bcb7-d2daa6e5c50a.jpg)
