### ISSUE TITLE
[BUG] Statistik Aseptor KB

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#4530]
**Jelaskan error yg dialami**

**Cara untuk mereplikasi errornya**

![ASEPTOR KB](https://user-images.githubusercontent.com/25834335/141150288-77a69c87-2e74-46be-8d09-ccbd02f54563.png)

**Hasil yg diharapkan**

**Versi OpenSID**

**Tema Yg Digunakan**

**Informasi tambahan**

**Comment by eddieridwan** [comment]
@MUHAMMADRANGSEL , saya coba normal. Silakan anda lampirkan tampakan layar menunjukkan persisnya error yg anda alami. Coba juga di https://berputar.opensid.or.id

**Comment by eddieridwan** [comment]
Yg ditemukan di berputar adalah adanya pengisian Aksekptor KB yg tidak valid di database. Telah disediakan validasi supaya tidak bisa menyimpan kode yg tidak valid, dan sekalian migrasi kode2 yg tidak valid. Sdh dicommit ke `bug-fix`.
