### ISSUE TITLE
[BUG] Statistik RTM

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#4531]
**Jelaskan error yg dialami**

**Cara untuk mereplikasi errornya**

Jumlah data yang dimunculkan salah
![statistik rtm](https://user-images.githubusercontent.com/25834335/141151417-24dd7966-3cdd-4fd9-958e-d06517ca8c4a.png)

**Hasil yg diharapkan**

**Tampakan layar dan log error**

**Versi OpenSID**

**Tema Yg Digunakan**

**Informasi tambahan**

**Comment by eddieridwan** [comment]
Sdh dicommit ke `bug-fix`
