### ISSUE TITLE
[BUG] NIK Sementara seharusnya tampil sebagai 0 di lampiran surat, termasuk F-1.15

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#4535]
**Jelaskan error yg dialami**

Di lampiran F-1.15 untuk Surat Permohonan Kartu Keluarga Baru, NIK sementara masih tampil utuh, meskipun seharusnya tampil sebagai 0.

**Cara untuk mereplikasi errornya**

1. Buat penduduk dengan NIK Sementara
2. Cetak Surat Permohonan Kartu Keluarga, isi penduduk yg dibuat di butir (1)
3. Periksa lampiran F-1.15 yang dihasilkan
4. Terlihat NIK Sementara untuk penduduk di butir (1) tampil utuh

**Hasil yg diharapkan**

Seharusnya di F-1.15, NIK sementara tampil sebagai 0.

**Versi OpenSID**

v21.11-premium

**Informasi tambahan**

Juga perlu periksa di semua lampiran lainnya, termasuk F-1.01, F-1.08, F1.25, F-2.01, F-2.29

**Comment by MUHAMMADRANGSEL** [comment]
masalah ini muncul kembali di versi umum  maupun premium
