### ISSUE TITLE
[BUG] Impor Data Pada Fitur Bantuan Terjadi Error 500 

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#4538]
**Jelaskan error yg dialami**
Saat melakukan Inpor data ke dalam fitur bantuan lebih dari 400 data terjadi error 500, semua isi data sudah disesuaikan dengan catatan yang ada form contoh impor program bantuan dan juga sudah mencoba melakukan beberapa konfigurasi hasil-nya tetap sama.

Harap tidak melaporkan masalah instal OpenSID. Masalah pada waktu install harap ditanyakan di https://www.facebook.com/groups/OpenSID atau di https://t.me/joinchat/SI0GWHeqKT39Gxhh, karena terkait sistem masing2 pengguna. 

Berikan keterangan yg jelas dan singkat mengenai error yg dialami. 
Pastikan error ini juga ditemukan di https://demo.opensid.or.id (untuk RIlis Umum) atau di https://berputar.opensid.or.id (untuk RIlis Premium).
--> Premium 21.11-rev02

**Cara untuk mereplikasi errornya**
1.  Ke pergi Ke Fitur Bantuan.
2.  Klik Impor, Pilih Download contoh format inport bantuan.
3.  Isikan data dan sesuaikan format dan data seperti yg tertera dalam catatan impor
4.  kemudian di impor kembali

![image](https://user-images.githubusercontent.com/64481641/142572698-84c95fe4-8088-4a07-8efe-3d7d8c18f782.png)

Langkah untuk mereplikasi error yg dialami, misalnya:
1. Pergi ke halaman '...'
2. Klik tombol '....'
3. Gulir ke bawah sampai '....'
4. Lihat error
-->

**Hasil yg diharapkan**
supaya dapat melakukan impor data bantuan, karena akan lebih mudah dan cepat untuk memasukkan data ke system dengan jumlah data yang besar.

Berikan keterangan yg jelas dan singkat apa hasil yg diharapkan.
-->

**Tampakan layar dan log error**

**Versi OpenSID**
Premium 21.11 rev02

Error ini terjadi di rilis/versi berapa: Rilis umum (mis. v21.03) atau premium (v21.03-premium)?
-->

**Tema Yg Digunakan**
Denatra

**Informasi tambahan**
![image](https://user-images.githubusercontent.com/64481641/142572631-ee0fa355-1530-4b82-abd7-c541eaec5a22.png)
![image](https://user-images.githubusercontent.com/64481641/142572653-b23b9263-8d3d-407f-8d6c-76973d86f798.png)
![image](https://user-images.githubusercontent.com/64481641/142572771-712ac78a-cbc3-466e-9bde-98ed6f3062e1.png)

Penjelasan lain yg dapat membantu.
-->

**Comment by agungsugiarto** [comment]
Pak @Zoel-WB bisa kirim contoh file yg di impor, yg bapak buat?

**Comment by Zoel-WB** [comment]
Pak @agungsugiarto file-nya saya PM lewat telegram pak ya.....
