### ISSUE TITLE
CETAK SURAT KELAHIRAN

### ISSUE THREAD

**Issue by pemdeslinggapura** [OpenSID/OpenSID#4542]
Penambahan penduduk lahir melalui cetak Keterangan Lahir tidak bisa dilakukan sebanyak 2 kali. Jika masih ada penduduk dengan NIK dengan simbol * di database.
Sudah dicoba di berputar sama seperti itu.

**Solusi Sementara**
Solusi sementara setiap menambahkan penduduk lahir melalui cetak surat, harus di edit nik nya menggunakan NIK sementara. Baru bisa menggunakan kembali menu Cetak Surat Ket Lahir.

**Saran**
Kalau bisa dibakukan saja dengan Nik sementara tidak menggunakan simbol *, tapi NIK sementara tersebut tidak di tampilkan pada Blangko Surat seperti Surat Permohonan Kartu Keluarga Baru dan Blangko F1.01 untuk Kelahiran

**Comment by balongbesuk** [comment]
knp gak pake angka 0 ?

**Comment by andifahruddinakas** [comment]
Pak @eddieridwan, apakah alur ini perlu diubah atau tetap menggunakan alur yg sekarang.

Alur yg mungkin diubah :
1. Buat terlebih dahulu penduduk lahir di modul penduduk > lahir
2. Buat surat keterangan kelahiran

Alur di atas sama halnya jika terdapat penduduk yg meninggal, data perlu disediakan terlebih dahulu.

**Comment by eddieridwan** [comment]
@andifahruddinakas fitur membuat penduduk baru dari Surat Keterangan Lahir memang bermasalah jika dibuat ulang. Ya, sepertinya sebaiknya dihilangkan saja fitur itu, karena prosesnya agak rapuh. Sehingga hanya dapat mencetak Surat Keterangan Lahir bagi penduduk yg sudah tercatat di data penduduk -- dan isian form seluruhnya (atau sebagian besar) diambil dari data penduduk.

Tujuan awal fitur itu adalah untuk mengurangi duplikasi dan menyederhanakan langkah yg biasa dilakukan. Yaitu kalau ada yg lahir, biasanya memerlukan Surat Keterangan Lahir. Jika ada yg meninggal diperlukan Surat Keterangan Kematian. Tapi solusinya mungkin membuat alur multi-langkah pada waktu menambah penduduk lahir, supaya juga menyediakan langkah opsional untuk sekaligus mencetak Surat Keterangan Lahirnya. Dan demikian juga untuk peristiwa mengubah status dasar menjadi `mati`, sekaligus ditawarkan untuk mencetak Surat Keterangan Mati.

Tapi untuk fitur2 tambahan itu, perlu dibuatkan issue2 terpisah.

**Comment by scqolbu24** [comment]
sudah diperbaiki melalui PR Ubah alur pembuatan surat keterangan lahir 
https://github.com/OpenSID/premium/pull/525
