### ISSUE TITLE
[Kelompok] Slug Data Kelompok

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#4544]
**Apa kekurangan yg ingin diatasi?**

Agar tidak muncul ID suplemen sehingga pengunjung dapat hanya dengan mengganti ID saja (untuk coba-coba), dapat dibuat Slug untuk LINK Data Kelompok.

<img width="958" alt="screenshot_77" src="https://user-images.githubusercontent.com/46939846/143414721-80022876-9721-4d98-ad5c-69a2e7bf5cb2.png">

**Comment by andifahruddinakas** [comment]
Sudah dicommit ke `rilis-dev`
