### ISSUE TITLE
[BUG] Data Dokumen Bocor

### ISSUE THREAD

**Issue by Ekoprass** [OpenSID/OpenSID#4547]
**Jelaskan error yg dialami**

link dokumen yang seharusnya private muncul dalam pencarian google

https://desarejodadi.com/desa/upload/dokumen/Emailing-Daftar-Pemilih-Sementara-Desa-Rejodadi.pdf

**Versi OpenSID**

**Informasi tambahan**
<!--
Penjelasan lain yg dapat membantu.
--
![Capturedf](https://user-images.githubusercontent.com/14850877/143772929-baa4e923-9c55-4aa9-93f6-02fe66113af8.PNG)
>

**Comment by Ekoprass** [comment]
![Capturedf](https://user-images.githubusercontent.com/14850877/143773123-f189b4ea-2f55-4789-9ce1-a02f29972849.PNG)

**Comment by agungsugiarto** [comment]
Terima kasih sudah melaporkan issue, issue ini saya tutup. Mohon menggunakan rilis terbaru opensid untuk menghindari file .pdf seperti ini terindex oleh mesin pencarian. Bisa dilihat pada situs demo.opensid.or.id tidak ada file yg terindex oleh mesin pencari. Terima kasih,
