### ISSUE TITLE
[BUG] AKUMULASI DATA KEPENDUDUKAN PADA DATA DESA TIDAK TAMPIL

### ISSUE THREAD

**Issue by OkkySuryaLesmana** [OpenSID/OpenSID#4548]
**Jelaskan error yg dialami**
Data Kependudukan tidak dapat tampil pada halaman data desa, padahal pada database data sudah ada.

**Hasil yg diharapkan**
Data Tampil,
Jumlah Penduduk Desa Tampil

**Tampakan layar dan log error**

**Versi OpenSID**
21.11

**Tema Yg Digunakan**
- Silir
- Natra
- Default

**Informasi tambahan**
Data Pada Dashboard admin ada, tapi di frontend tidak tampil.

**Comment by andifahruddinakas** [comment]
Pak @OkkySuryaLesmana bisa sertakan gambar yang dimaksud yg di duplikasi dari website demo ???

**Comment by andifahruddinakas** [comment]
Pak @OkkySuryaLesmana, mohon dilengkapi bagian mana yg dimaksud. Silahkan buka kembali jika masih bermaslah.
