### ISSUE TITLE
[BUG] Declaration of Penduduk_penerima_bantuan::hitung_total() must be compatible with Laporan_penduduk_model::hitung_total(&$data)

### ISSUE THREAD

**Issue by faissw** [OpenSID/OpenSID#4549]
i just firstly install it , import DB sukses . then i direct to localhost/foldername/
here is the error 
Fatal error: Declaration of Penduduk_penerima_bantuan::hitung_total() must be compatible with Laporan_penduduk_model::hitung_total(&$data) in /Applications/XAMPP/xamppfiles/htdocs/OpenDesa/donjo-app/models/Statistik_penduduk_model.php on line 92
A PHP Error was encountered
Severity: Compile Error

Message: Declaration of Penduduk_penerima_bantuan::hitung_total() must be compatible with Laporan_penduduk_model::hitung_total(&$data)

Filename: models/Statistik_penduduk_model.php

Line Number: 92

**Comment by andifahruddinakas** [comment]
Pak @Afaisw, bisa sertakan tangkapan layar beserta versi OpenSID yg digunakan.

**Comment by agungsugiarto** [comment]
Sudah di perbaiki melalui pr https://github.com/OpenSID/premium/pull/503
