### ISSUE TITLE
[Lembaga] Tampilkan ke halaman web data lembaga

### ISSUE THREAD

**Issue by afri18** [OpenSID/OpenSID#4552]
**Apa kekurangan yg ingin diatasi?**

biar mudah menampilkan lembaga desa di web

**Jelaskan solusi yg diinginkan**

**Apakah ada alternatif lain**

**Untuk versi OpenSID mana**

**Informasi tambahan**

**Comment by agungsugiarto** [comment]
Sudah di fitur premium melalui pr https://github.com/OpenSID/premium/pull/959
