### ISSUE TITLE
Tampilkan lapak di layanan mandiri, termasuk anjungan

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#4553]
**Apa kekurangan yg ingin diatasi?**

Issue #4482 meminta ditambahkannya fitur di layanan mandiri. Salah satu fitur yg diminta adalah menampilkan lapak.

**Jelaskan solusi yg diinginkan**

Tampilkan lapak di Layanan Mandiri, termasuk di Anjungan. Seragamkan tampilan seperti yg ada di web. Hindari duplikasi. 

**Untuk versi OpenSID mana**

Pasca v21.12-premium

**Informasi tambahan**

**Comment by lihin20** [comment]
nah ia ini,🙂

**Comment by andifahruddinakas** [comment]
Mas @scqolbu24

**Comment by scqolbu24** [comment]
siap

**Comment by Zoel-WB** [comment]
Mantap ini...
Bagi warga yg sudah punya akun lapak desa di website desa, dapat secara langsung mengontrol lapaknya melalui OpenSID mandiri android.

**Comment by andifahruddinakas** [comment]
Sudah digabungkan ke FITUR PREMIUM melalui PR https://github.com/OpenSID/premium/pull/509
