### ISSUE TITLE
Modifikasi Verifikasi Surat Hasil Scan Barcode Tidak Terpanggil Sempurna

### ISSUE THREAD

**Issue by gampongbarabung** [OpenSID/OpenSID#4554]
**Apa kekurangan yg ingin diatasi?**
Tampilan Verifikasi Surat Tidak Dapat Dimodifikasi Sesuai Keiinginan Desa. 

**Jelaskan solusi yg diinginkan**

**Comment by andifahruddinakas** [comment]
Sudah di 21.12-premium, saat ini hanya modifikasi dilakukan sesuai tema yang digunakan.

**Comment by gampongbarabung** [comment]
Untuk memodifikasi hubungi pihak tema nya pak?

**Comment by andifahruddinakas** [comment]
> Untuk memodifikasi hubungi pihak tema nya pak?

Ya.

Untuk saat ini sudah tersedia, tp kayaknya ada kendala saat mengambil view di masing2 tema.

**Comment by scqolbu24** [comment]
sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/497
