### ISSUE TITLE
[Migrasi] Migrasi untuk nik dan no_kk sementara kadang error untuk kasus tertentu

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#4560]
**Jelaskan error yg dialami**

Kadang terjadi error saat melakukan migrasi untuk nik dan no kk sementara

**Cara untuk mereplikasi errornya**

**Hasil yg diharapkan**

**Tampakan layar dan log error**

**Versi OpenSID**

![error migrasi](https://user-images.githubusercontent.com/57283157/144234054-6119952d-7a15-4fc5-bdc7-d8650b337430.jpg)

**Tema Yg Digunakan**

**Informasi tambahan**

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melalui pr https://github.com/OpenSID/premium/pull/491
