### ISSUE TITLE
[Notifikasi] Sesuaikan pemberitahuan adanya rilis baru

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#4561]
**Apa kekurangan yg ingin diatasi?**

Saat ini pemberitahuan terdeteksinya rilis baru tidak dibedakan untuk rilis Umum ataupun Premium. Tetapi karena aturan rilis berbeda untuk rilis Umum dan Premium, maka pemberitahuan perlu dibedakan juga. 

**Jelaskan solusi yg diinginkan**

- [x] Untuk Rilis Umum, pemberitahuan rilis baru tidak berubah seperti yg sudah ada. Yaitu, ada notifikasi rilis baru jika terdeteksi adanya rilis baru di https://github.com/OpenSID/OpenSID dan tautan mengarah ke repo tersebut
- [x] Untuk Rilis Premium, ada skenario sbb:
    - [x] Jika langganan Premium masih aktif, beritahu jika ada riils baru melalui api layanan opendesa, api layanan yg akan menjadi perantara untuk memanggil api github untuk mendownload rilis terbaru.
    - [x] Jika langganan Premium sudah tidak aktif, dan rilis terpasang masih di atas rilis Umum terbaru: jika terdeteksi adanya rilis baru di repo Umum https://github.com/OpenSID/OpenSID, beritahu supaya tidak melakukan update, karena rilis terpasang masih di atas rilis Umum tersebut
    - [x] Jika langganan Premium sudah tidak aktif, dan rilis terpasang sudah terlewati oleh rilis Umum terbaru: jika terdeteksi adanya rilis baru di repo Umum https://github.com/OpenSID/OpenSID, beritahu supaya melakukan update, dengan tautan yang mengarah ke repo https://github.com/OpenSID/OpenSID.

**Untuk versi OpenSID mana**

pasca v21.12

**Informasi tambahan**

Issue ini untuk diterapkan pada rilis Umum dan Premium

**Comment by andifahruddinakas** [comment]
Mas @agungsugiarto, ini sudah di cek ???

**Comment by scqolbu24** [comment]
sudah diperbaiki melalui PR Pemberitahuan rilis baru premium #508 
https://github.com/OpenSID/premium/pull/508
