### ISSUE TITLE
[Pembangunan] Urut data pembangunan

### ISSUE THREAD

**Issue by afri18** [OpenSID/OpenSID#4563]
**Jelaskan error yg dialami**
bukan eror, hanya mengusulkan URUTKAN daftar pembangunan di halaman web > pembanguna dan admin pembangunan sesuai tahun pembangunan, yang paling atas yg tahun terbaru

**Cara untuk mereplikasi errornya**

**Hasil yg diharapkan**
Akan tertata data pembangunan di halaman admin pembangunan sesuai tahun, tidak tergantung dengan input pertama/terdahulu, yang teratas tahun terbaru

**Tampakan layar dan log error**

**Versi OpenSID**

**Tema Yg Digunakan**

**Informasi tambahan**

**Comment by andifahruddinakas** [comment]
Sudah terurut dengan benar.
![pembangunan](https://user-images.githubusercontent.com/57283157/162285400-6e9da8c7-d2f7-4f9e-ac95-e88887a9d35d.png)
