### ISSUE TITLE
[Pengaturan Peta] Tidak dapat menyimpan warna

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#4564]
**Jelaskan error yg dialami**

Saat menambah / mengubah tipe garis, warna tidak tersimpan

**Cara untuk mereplikasi errornya**

1. Buka modul pemetaan > pengaturan peta > tipe garis.
2. Tambah / ubah salah 1 data dan simpan.

**Hasil yg diharapkan**

**Tampakan layar dan log error**

**Versi OpenSID**

**Tema Yg Digunakan**

**Informasi tambahan**

**Comment by FirlianiF** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/507
