### ISSUE TITLE
[Pembangunan] Foto pembangunan terlihat besa

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#4565]
**Jelaskan error yg dialami**

Buka modul pembangunan, foto yg terunggah terlihat besar.

**Cara untuk mereplikasi errornya**

**Hasil yg diharapkan**

Terlihat normal seperti sebelumnya.

**Tampakan layar dan log error**

**Versi OpenSID**

**Tema Yg Digunakan**

**Informasi tambahan**

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melalui pr https://github.com/OpenSID/premium/pull/493
