### ISSUE TITLE
[Layanan Mandiri] Error loging ektp dan persuratan

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#4566]
**Jelaskan error yg dialami**

Terjadi error login menggunakan ektp dan saat mengakses persuratan.

**Cara untuk mereplikasi errornya**

Login ke layanan mandiri dengan ektp, maka akan di alihkan ke halaman 404

**Hasil yg diharapkan**

**Tampakan layar dan log error**

**Versi OpenSID**

**Tema Yg Digunakan**

**Informasi tambahan**

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melalui pr https://github.com/OpenSID/premium/pull/496
