### ISSUE TITLE
[Migrasi] Migrasi tidak jalan sempurna

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#4567]
**Jelaskan error yg dialami**

Proses migrasi berhasil, namun perubahan/penambahan slug di modul pembangunan tidak terjadi.

**Cara untuk mereplikasi errornya**

**Hasil yg diharapkan**

**Tampakan layar dan log error**

**Versi OpenSID**

**Tema Yg Digunakan**

**Informasi tambahan**

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melalui pr https://github.com/OpenSID/premium/pull/494
