### ISSUE TITLE
[Rekapitulasi Penduduk] Terjadi error saat mengakses modul

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#4568]
**Jelaskan error yg dialami**

Saat mengakses modul bumindes > penduduk > rekapitulasi jumlah penduduk terjadi error

**Cara untuk mereplikasi errornya**

**Hasil yg diharapkan**

Tidak terjadi error

**Tampakan layar dan log error**

**Versi OpenSID**

**Tema Yg Digunakan**

**Informasi tambahan**

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melalui pr https://github.com/OpenSID/premium/pull/505
