### ISSUE TITLE
NIK dan NO KK Sementara muncul di Formulir F-2.01dan F-1.15

### ISSUE THREAD

**Issue by pemdeslinggapura** [OpenSID/OpenSID#4569]
### Bagaimana alurnya sampai muncul masalah?
**Contoh 1** 
ketika memasukan penduduk baru dan melakukan penambahan penduduk lahir, kondisi ini pastinya belum mempunyai no KK, sehingga digunakanlah **No KK Sementara**. 
Tetapi ketika cetak surat Ket Lahir, maka No KK sementara akan tercetak di Formulir F-2.01.

**Contoh 2**
Dikarenakan tidak bisa melakukan penambahan penduduk sebanyak 2 kali melalui cetak surat ket lahir, maka NIK penduduk lahir yang awal akan menggunakan Nik sementara. Ketika ada kasus pencetakan ulang, maka NIK sementara ini tampil di F-2.01 dan juga F-1.15
#4542 

### Seperti apa yang diharapkan?
Kalau bisa untuk NIK atau No KK sementara tidak ditampilkan di Formulir F-2.01dan F-1.15.

**Comment by andifahruddinakas** [comment]
[surat_ket_kelahiran_5201070000000004_2021-12-13_1 (2).zip](https://github.com/OpenSID/OpenSID/files/7700287/surat_ket_kelahiran_5201070000000004_2021-12-13_1.2.zip)

Sy coba test, menggunakan nik sementara dari databse penduduk dan no_kk sementara, output lampirannya sudah betul, Silahkan di update ke versi terbaru terlebih dahulu.

**Comment by andifahruddinakas** [comment]
Silahkan gunakan versi terbaru.
