### ISSUE TITLE
berkas `.env`

### ISSUE THREAD

**Issue by totoprayogo1916** [OpenSID/OpenSID#4572]
https://github.com/OpenSID/OpenSID/blob/b88ddde03fad48f9798a6289514e7faae38f2e79/index.php#L58

apakah ada contoh berkas `.env`
saya coba dengan tambahan data `CI_ENV` tapi malah muncul dihalaman ...

![image](https://user-images.githubusercontent.com/2387514/145207259-f5aeda6b-69c1-45e7-871c-c3e2bc7d7115.png)

**Comment by totoprayogo1916** [comment]
FYI: saya setting **manual** dengan edit `ENVIRONMENT` di file index.php tsb menjadi development karena web gak bisa jalan kalo gak mode ini ...

**Comment by andifahruddinakas** [comment]
> FYI: saya setting **manual** dengan edit `ENVIRONMENT` di file index.php tsb menjadi development karena web gak bisa jalan kalo gak mode ini ... 

Pakai versi rilis

**Comment by andifahruddinakas** [comment]
```php
<?php
  $_SERVER['CI_ENV'] = 'development';
```
