### ISSUE TITLE
[Pengguna] Pengaturan Grup Pengguna

### ISSUE THREAD

**Issue by tobagus6911** [OpenSID/OpenSID#4574]
**Jelaskan error yg dialami**
Saya buat grup pengguna "Jurnalis" yang hanya dapat membuat artikel
akan tetapi daftar artikel yang dibuat oleh Akun lain tampil / menampilkan semua artikel
tidak seperti Grup Akun Kontributor. yang hanya menampilkan Artikel yang dibuatnya saja

**Cara untuk mereplikasi errornya**

**Hasil yg diharapkan**
Artikel yang dibuat oleh Akun lain jangan ditampilkan di daftar artikel
sebab dapat merupah/ menghapus artikel Akun lainnya

**Tampakan layar dan log error**

**Versi OpenSID**
versi 21.12

**Tema Yg Digunakan**
Natra

**Informasi tambahan**

**Comment by tobagus6911** [comment]
maaf salah tempat seharusnya di Pembuatan fitur baru. bukan bug

**Comment by scqolbu24** [comment]
Sudah diperbaiki untuk Tampilkan data artikel sesuai dengan pengaturan Grup dan Pengguna.

PR #520 Group pengguna untuk modul artikel https://github.com/OpenSID/premium/pull/520
