### ISSUE TITLE
[Pengguna] Grup Pengguna

### ISSUE THREAD

**Issue by tobagus6911** [OpenSID/OpenSID#4575]
**Apa kekurangan yg ingin diatasi?**
Mohon dibuatkan grup pengguna khusus Jurnalis Desa
yang hanya dapat membuat Artikel Dinamis

**Jelaskan solusi yg diinginkan**
Dimaksudkan agar dapat menjadi laporan kegiatan para relawan berita (RT, RW, Kader Posyandu, BPD, LPM, Dll)
sehingga Websitenya Aktif mendapatkan berita dari Jurnalis Desa
Masing-masing Pengguna (Jurnalis) tiidak dapat Intervensi (merubah/menghapus) Artikel Pengguna Lain

**Apakah ada alternatif lain**
buatkan saja Grup Pengguna Kontributor yang hanya dapat mengaksis/ membuat Artikel Dinamis saja

**Untuk versi OpenSID mana**
versi mana saja

**Informasi tambahan**

**Comment by andifahruddinakas** [comment]
Silahkan buat group pengguna scr mandiri, untuk kasus issue https://github.com/OpenSID/OpenSID/issues/4576 sudah diperbaiki yg berkaitan dgn issue ini.
