### ISSUE TITLE
[Pengguna] Grup Pengguna

### ISSUE THREAD

**Issue by tobagus6911** [OpenSID/OpenSID#4576]
**Jelaskan error yg dialami**
saya buat grup pengguna yang hanya punya Hak Baca untuk data penduduk. 
akan tetapi masih bisa membuat, dan merubah datanya

**Cara untuk mereplikasi errornya**

**Hasil yg diharapkan**
pengguna hanya dapat melihat, dan mendownload, cetak datanya saja
untuk para RT, RW, Kadus, atau relawan/kader Posyandu & Paud

**Tampakan layar dan log error**

**Versi OpenSID**

**Tema Yg Digunakan**

**Informasi tambahan**
![image](https://user-images.githubusercontent.com/84884247/145256551-4d051eb4-e1af-4e81-b6fe-7a993ab2817d.png)

![image](https://user-images.githubusercontent.com/84884247/145256708-fdea4c0a-9d16-48ca-9a28-e23dd9b3cd83.png)

**Comment by scqolbu24** [comment]
sudah diperbaiki melalui PR Sesuaikan hak akses dan buat konsisten. #524 
https://github.com/OpenSID/premium/pull/524

**Comment by WAHYUDIK** [comment]
apakah perbaikan ini juga berlaku untuk semua menu?tidak hanya perbaikan akses pengguna di menu kependudukan bisa sampai RT?
