### ISSUE TITLE
[Pembangunan] BUMINDES -> Buku Kegiatan Pembangunan-> Pilihan Tahun Yang Tampil Hanya 2021 

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#4577]
**Jelaskan error yg dialami**
Pada Bumindes : Buku Kegiatan Pembanguna pada dropdown pilihan tahun tersendat, setelah memilih satu tahun kegiatan, kemudian memilih untuk lainnya tidak lagi muncul pilihan di daftar dropdwon
![image](https://user-images.githubusercontent.com/64481641/145343435-6ce157fb-cea3-46bf-9e86-ca901daa04dc.png)

Harap tidak melaporkan masalah instal OpenSID. Masalah pada waktu install harap ditanyakan di https://www.facebook.com/groups/OpenSID atau di https://t.me/joinchat/SI0GWHeqKT39Gxhh, karena terkait sistem masing2 pengguna. 

Berikan keterangan yg jelas dan singkat mengenai error yg dialami. 
Pastikan error ini juga ditemukan di https://demo.opensid.or.id (untuk RIlis Umum) atau di https://berputar.opensid.or.id (untuk RIlis Premium).
-->

**Cara untuk mereplikasi errornya**

**Hasil yg diharapkan**
Pada Buku Kegiatan Pembangunan agar dapat menampilkan semua tahun kegiatan
Berikan keterangan yg jelas dan singkat apa hasil yg diharapkan.
-->

**Tampakan layar dan log error**

![image](https://user-images.githubusercontent.com/64481641/145343435-6ce157fb-cea3-46bf-9e86-ca901daa04dc.png)

**Versi OpenSID**

**Tema Yg Digunakan**

**Informasi tambahan**

**Comment by andifahruddinakas** [comment]
![pembangunan 1](https://user-images.githubusercontent.com/57283157/145912576-c0fda891-462a-4422-9b61-4178014f779a.png)
![pembangunan 2](https://user-images.githubusercontent.com/57283157/145912585-8cafdd05-7a99-480d-9d60-d7787aaa1fb0.png)
![pembangunan 3](https://user-images.githubusercontent.com/57283157/145912589-60ba6c8f-82ed-4d67-8118-7a075edd3bc3.png)

Saya coba tidak ada masalah, mungkin bisa lebih spesifik lg masalahnya seperti apa. atau bisa di duplikasi diwebsite berputar.opensid.or.id

**Comment by andifahruddinakas** [comment]
Silahkan di buka kembali jika masih bermasalah.
