### ISSUE TITLE
[Login Admin] Catat ip address pengguna login admin

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#4580]
**Apa kekurangan yg ingin diatasi?**

Di website demo ada pengguna yg rutin iseng mengubah data memberi kesan website diretas. Diperlukan cara untuk melacak dan  mencegah akses oleh orang yg iseng seperti itu

**Jelaskan solusi yg diinginkan**

Untuk website demo, sediakan:

- [ ] buat log pengguna yg login dengan hak akses administrator; catat IP address dan tgl & waktu login
- [ ] sediakan pengaturan melalui file config untuk membuat daftar hitam IP address yg tidak diperbolehkan login

**Untuk versi OpenSID mana**

pasca v21.12

**Informasi tambahan**

**Comment by agungsugiarto** [comment]
Pak @eddieridwan apakah issue ini masih diperlukan? karena sudah ada cron job untuk mereset database setiap jam 1 dini hari dan solusi untuk mencatat ip address saya rasa tidak efektif karena pasti akan berubah2.

**Comment by eddieridwan** [comment]
@agungsugiarto , ok sementara dikeluarkan dari target 22.02, menunggu perkembangan setelah diterapkan proses reset database demo setiap hari. Jika masalahya timbul lagi. maka issue ini perlu ditargetkan lagi.

**Comment by andifahruddinakas** [comment]
Sudah diterpakan diversi 2305.0.0-premium
