### ISSUE TITLE
[Keuangan] Rincikan Belanja Sampai Ke Paket Kegiatan pada Input Data Manual

### ISSUE THREAD

**Issue by emanuel-simon** [OpenSID/OpenSID#4582]
**Apa kekurangan yg ingin diatasi?**

Mengingat:
1. banyak desa yang menggunakan Siskeudes online sehingga tidak bisa mengakses databasenya
2. banyak pengguna yang kesulitan mengkonversi database .mde Siskeudes untuk diimpor ke OpenSID
3. (ini kemungkinan saja) perubahan struktur database Siskeudes mengikuti peraturan yang sering berubah

**Jelaskan solusi yg diinginkan**

Input data manual pada modul keuangan di bagian **Belanja** yang sekarang hanya sampai di belanja per bidang, sebaiknya _dirincikan sampai ke per Kegiatan/ Paket Kegiatan_ agar tabel laporan manual yang ditampilkan semakin lengkap.

Untuk **Pendapatan** dan **Pembiayaan** saya rasa sudah cukup rinci.

Berikut saya coba gambarkan:

Tampilan Asli Input Manual:
![input keuangan manual 1](https://user-images.githubusercontent.com/48465803/145580142-cffd4d37-ca66-4a73-a584-026ec023eb1e.png)

Diubah menjadi:
![input keuangan manual 2](https://user-images.githubusercontent.com/48465803/145580269-4f2e7bf5-9216-40f5-bd3b-68e0a236a7da.png)

Sesuai Parameter Bidang dan Kegiatan Siskeudes
![input keuangan manual 3](https://user-images.githubusercontent.com/48465803/145580312-a8724a53-e686-44a0-a320-092a147dc9ae.png)

Agar nanti tampilan laporan keuangan manual tidak berbeda jauh dengan laporan dari Siskeudes
![input keuangan manual 4](https://user-images.githubusercontent.com/48465803/145588403-d777011d-8751-4fa1-af79-0a2b73b01c18.png)

**Untuk versi OpenSID mana**

v22.01 atau v22.01-premium

**Informasi tambahan**

[parameter bidang dan kegiatan siskeudes.pdf](https://github.com/OpenSID/OpenSID/files/7692992/parameter.bidang.dan.kegiatan.siskeudes.pdf)

Issue ini juga dibahas pada https://forum.opendesa.id/d/26-modul-keuangan-rincikan-belanja-sampai-ke-paket-kegiatan-di-input-manual

**Comment by mangaip** [comment]
Saya termasuk pengguna siskeudes online. Memang kami kesulitan untuk mengakses database. Karena database siskeudes online adanya di DPMD Kabupaten. 

Input data keuangan ke web desa pun jadinya manual.

**Comment by emanuel-simon** [comment]
> Saya termasuk pengguna siskeudes online. Memang kami kesulitan untuk mengakses database. Karena database siskeudes online adanya di DPMD Kabupaten.
> 
> Input data keuangan ke web desa pun jadinya manual.

Mari ajak teman-teman lain untuk _like issue_ ini agar lebih cepat dikerjakan

**Comment by mangaip** [comment]
Seharusnya kalau sudah menyangkut laporan keuangan, harusnya bisa jadi prioritas. Sangat jelas dalam transparansi anggaran.

Bagi pengguna siskeudes offline, suatu saat pasti akan migrasi juga ke online. 

Maka issue ini, menurut saya harusnya jadi prioritas

**Comment by emanuel-simon** [comment]
> Seharusnya kalau sudah menyangkut laporan keuangan, harusnya bisa jadi prioritas. Sangat jelas dalam transparansi anggaran.
> 
> Bagi pengguna siskeudes offline, suatu saat pasti akan migrasi juga ke online. 
> 
> Maka issue ini, menurut saya harusnya jadi prioritas

Setuju pak

**Comment by ai-skematik** [comment]
sy bantu UP.

**Comment by emanuel-simon** [comment]
> sy bantu UP.

Siap pak @ai-skematik

**Comment by emanuel-simon** [comment]
up dulu

**Comment by sulaimanlawidhub** [comment]
Sangat setuju sekali dengan tujuan dari issue ini. Semoga dapat segera direalisasikan, sebab ini merupakan bagian penting dalam kemanfaatan SID.

**Comment by dgyoganantha** [comment]
Setuju

**Comment by astonialam** [comment]
Bener tu.. Harus Ada
-Bidang
-Sub Bidang
-Kegiatan
-Nama Kegiatan

**Comment by davidyusufbumiratu** [comment]
Sangat setuju sekali dengan tujuan dari issue ini. transparansi keuangan ke publik akan makin jelas namun masih dalam batasan wajar

**Comment by emanuel-simon** [comment]
up dulu

**Comment by balongbesuk** [comment]
knp gak d bikin artikel saja dg hasil print out siskeudes sebagai lampirannya? kan gak perlu susah susah ngisi manual satu satu 😄

**Comment by emanuel-simon** [comment]
> knp gak d bikin artikel saja dg hasil print out siskeudes sebagai lampirannya? kan gak perlu susah susah ngisi manual satu satu 😄

warga malas untuk download lalu baca, lebih suka lihat langsung di artikelnya. Lagian nanti terlalu banyak artikel, setiap kali ada update di kondisi keuangan harus upload print out siskeudes lagi...

**Comment by ai-skematik** [comment]
up

Pada tanggal Sab, 5 Mar 2022 16:12, Emamuel Simon ***@***.***>
menulis:

**Comment by roaddee** [comment]
up juga

**Comment by mranca** [comment]
Up juga karna sudah sangat detail

**Comment by LPKPIhendra** [comment]
Gimana cara mengecek aplikasi SIDkomendesa

**Comment by emanuel-simon** [comment]
> Gimana cara mengecek aplikasi SIDkomendesa

Itu aplikasi apa ya?

**Comment by sulaimanlawidhub** [comment]
Isu /Fitur tersebut sangat diharapkan bisa diakomodir karena menjadi kebutuhan yang tidak hanya untuk tampilan di web. Sangat bagus isu ini untuk direalisasikan.

**Comment by ai-skematik** [comment]
Up Lagi. Fitur sangat penting. karena impor pakai database siskeudes sering bermasalah karena nilainya tidak sama.

**Comment by ai-skematik** [comment]
up

**Comment by dgyoganantha** [comment]
sundul lagi. agar cepat masuk dalam rilis.

**Comment by Pematung** [comment]
Sangat setuju dan Mohon Di Proritaskan

**Comment by pandigresik** [comment]
masukkan saja laporan dari siskeudes dalam artikel statis sehingga nanti artikel statis tersebut dapat diset sebagai menu di website

**Comment by andifahruddinakas** [comment]
Duplicate of https://github.com/OpenSID/OpenSID/issues/8145
