### ISSUE TITLE
[Backup] Backup folder desa lewat hosting

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#4583]
**Jelaskan error yg dialami**

Terkadang pengguna/desa melakukan backup folder desa (lewat hosting/bukan dari halaman admin) dan tidak menyimpannya di tempat yang aman. Biasa di backup dan disimpan di folder public_html, ssehingga orang luar dapat mengunduh file tsb dengan mengakses melalui link (misalnya : donamain/desa.zip)

**Cara untuk mereplikasi errornya**

Lakukan backup folder desa dan letakkan di folder luar.

**Hasil yg diharapkan**

Cegak undih folder backup atau lainnya melalu url.

**Tampakan layar dan log error**

**Versi OpenSID**

**Tema Yg Digunakan**

**Informasi tambahan**

**Comment by FirlianiF** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/521
