### ISSUE TITLE
[Cetak Surat] Laporkan jika `exec` tidak tersedia pada waktu mencetak PDF

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#4584]
**Apa kekurangan yg ingin diatasi?**

Saat ini di menu Cetak Surat,  jika Cetak PDF dijalankan dan gagal karena instruksi PHP `exec` tidak tersedia, notifikasi tidak menjelaskan sebab kegagalan.

**Jelaskan solusi yg diinginkan**

Di menu Cetak Surat,  jika Cetak PDF dijalankan dan gagal karena instruksi PHP `exec` tidak tersedia, tampilkan notifikasi yang menjelaskan sebab kegagalan.

**Apakah ada alternatif lain**

Tambahkan pemeriksaan didukungnya instruksi `exec` di menu Pengaturan > Info Sistem >  Kebutuhan Sistem

**Untuk versi OpenSID mana**

pasca v21.12-premium

**Informasi tambahan**

**Comment by scqolbu24** [comment]
sudah ditambahkan fitur pada PR Libreoffice dan Fuction Exec() #518
https://github.com/OpenSID/premium/pull/518
