### ISSUE TITLE
[Widget] Tampilkan notifikasi error, jika widget gagal disimpan beserta penyebabnya.

### ISSUE THREAD

**Issue by tobagus6911** [OpenSID/OpenSID#4585]
**Jelaskan error yg dialami**
Tidak bisa menyimpan Widget yang baru

**Cara untuk mereplikasi errornya**
Setelah Menambah Widget yang baru. data tidak dapat disimpan

**Hasil yg diharapkan**
bisa menambah WIdget / menyimpan hasil edit widget

**Tampakan layar dan log error**
![image](https://user-images.githubusercontent.com/84884247/145678078-9f86507f-f2f3-4e2b-b37b-eca8aeacee46.png)

setelah disimpan tampil seperti ini
![image](https://user-images.githubusercontent.com/84884247/145678032-98098754-1a71-4d42-b05a-240812ba8419.png)

![image](https://user-images.githubusercontent.com/84884247/145678099-9eb16019-4d53-497e-9feb-233fb4e22a17.png)

**Versi OpenSID**
versi 21.12

**Tema Yg Digunakan**
Natra

**Informasi tambahan**

**Comment by andifahruddinakas** [comment]
Sertakan log saat error ini terjadi.

**Comment by tobagus6911** [comment]
![image](https://user-images.githubusercontent.com/84884247/145700536-58762951-453a-42f2-a6f0-b226f2970426.png)

**Comment by andifahruddinakas** [comment]
> ![image](https://user-images.githubusercontent.com/84884247/145700536-58762951-453a-42f2-a6f0-b226f2970426.png)
> 

Silahkan baca panduan https://github.com/OpenSID/OpenSID/wiki/Persiapan-Install-OpenSID

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melalui pr https://github.com/OpenSID/premium/pull/519
