### ISSUE TITLE
modul [Penduduk] & modul [Keluarga] 

### ISSUE THREAD

**Issue by tobagus6911** [OpenSID/OpenSID#4586]
**Jelaskan error yg dialami**
Tidak ada pencariian berdasarkan NIK dan No KK

**Cara untuk mereplikasi errornya**

**Hasil yg diharapkan**
kalau sedang input Data Keluarga atau Data Penduduk ternyata NIK atau No KK nya sudah digunakan. kita tidak bisa melihat/mencari dengan cepat oleh siapa data keluarga / data penduduk itu digunakan bila tidak ada pencarian berdasarkan NIK atau No KK

**Tampakan layar dan log error**

**Versi OpenSID**
versi 21.12

**Tema Yg Digunakan**
Tema Natra

**Informasi tambahan**

**Comment by andifahruddinakas** [comment]
Silahkan dipelajari lg fitur yg disedikan di OpenSID.

![cari](https://user-images.githubusercontent.com/57283157/145716213-8bbad31b-3d51-4845-8a73-fd4b635e3359.png)
