### ISSUE TITLE
modul[Pengaturan > Database -- impordata base]

### ISSUE THREAD

**Issue by tobagus6911** [OpenSID/OpenSID#4587]
**Jelaskan error yg dialami**
- impordatabase sukses, akan tetapi ada Data Keluarga yang tidak tampil di List
- Mau tambah data KK tidak bisa karena data sudah ada , tapi data tidak tampil untuk dapat di edit
- Tidak ada pencarian berdasarkan No KK
- Kepala Keluarganya tidak ikut ter impor
- saya tambah data penduduk sebagai Kepala Keluaarga, akan tetapi tidak dapat dibuat, dimasukkan ke Data Keluarga yang tidak tampil di list

**Versi OpenSID**
v21.12

**Tema Yg Digunakan**
Natra

**Comment by andifahruddinakas** [comment]
Silahkan di sertakan contoh impor yg bermasalah tsb.

**Comment by tobagus6911** [comment]
tapi bagaimana menambah anggota KK kalau KK nya tidak tampil di Daftar/list karena ga bisa di edit

**Comment by tobagus6911** [comment]
duh maaf,, setelah saya telusuri kembali dengan cermat. ternyata ada kesalah di databasenya pada penyesuaian data di Excel.
