### ISSUE TITLE
[Demo] Loloskan pemeriksaan token di setting demo

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#4588]
**Apa kekurangan yg ingin diatasi?**

Saat ini jika identitas desa diubah, semua menu terkunci, karena tidak memiliki token untuk desa yg dipilih. Sedangkan, di demo, menu perlu dapat terus diakses.

**Jelaskan solusi yg diinginkan**

Di setting demo, 

- [ ] loloskan saja pemeriksaan token, supaya menu tidak terkunci.
- [ ] buat pembatasan yg mencegah pengguna memanfaatkan status demo untuk menggunakan premium tanpa token yg valid. Misalnya:
    - [ ] tambahkan tampilan di setiap halaman bahwa ini adalah website demo
    - [ ] matikan atau kebiri salah satu fitur penting

**Apakah ada alternatif lain**

Alternatif lain adalah mengunci tidak boleh mengubah identitas desa. Tapi ini mengurangi manfaat demo, di mana pengunjung ingin mengubah ke desa mereka sendiri. **Tapi kalau strategi pembatasan pada status demo terlalu rentan atau sulit, gunakan strategi ini.** 

**Untuk versi OpenSID mana**

v21.12

**Informasi tambahan**

Di premium. Kalau umum seharusnya memang tidak membatasi fitur berdasarkan token.

**Comment by andifahruddinakas** [comment]
Alur login perlu disesuaikan dan mematikan username dan password default tidak bisa diubah, baik dari admin atau langsung dari database. Atau username untuk admin utama (superadmin) dibuat statis.

**Comment by eddieridwan** [comment]
> Alur login perlu disesuaikan dan mematikan username dan password default tidak bisa diubah, baik dari admin atau langsung dari database. Atau username untuk admin utama (superadmin) dibuat statis.

Mengapa diperlukan ini? Login di demo harus bisa konsisten, dengan username/password yg selalu sama.

**Comment by andifahruddinakas** [comment]
> > Alur login perlu disesuaikan dan mematikan username dan password default tidak bisa diubah, baik dari admin atau langsung dari database. Atau username untuk admin utama (superadmin) dibuat statis.
> 
> Mengapa diperlukan ini? Login di demo harus bisa konsisten, dengan username/password yg selalu sama.

Kalau hanya sekedar meloloskan sudah sy terapkan di website berputar.opensid.or.id

**Comment by andifahruddinakas** [comment]
Tambahan :
1. Tambahkan domain pengecualian untuk demo, misalnya berputar.opensid.or.id dan demo.opensid.or.id

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melalui pr https://github.com/OpenSID/premium/pull/523
