### ISSUE TITLE
[Suplemen] Tambahkan pencarian berdasarkan tag ID card (menggunakan RFID)

### ISSUE THREAD

**Issue by KangErwin** [OpenSID/OpenSID#4589]
**Menambahkan tag_id_card pada data suplemen dan program batuan?**

**ketika melakukan pendataan tambah peserta atau mencari nama peserta bisa menggunakan id_car /e-ktp**

****

**Fitur ini diusulkan untuk versi Rilis Umum (mis. v21.12) **

****

**Comment by andifahruddinakas** [comment]
Mungkin selanjutnya penambahan dilakukan per modul.

**Comment by FirlianiF** [comment]
Sudah dipremium melalui PR https://github.com/OpenSID/premium/pull/700
