### ISSUE TITLE
[Info Sistem] Tersedianya Informasi Disk Space pada Halaman Admin.

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#4590]
**Apa kekurangan yg ingin diatasi?**

Seperti yang terjadi di beberapa wilayah bahwa desa difasilitasi oleh penyedia setempat dan hanya diberi akses halaman login Admin OpenSID.

Saat ini, desa kesulitan mengetahui berapa _disk space_ yang tersisa untuk persiapan _upgrade_ ke hosting yang lebih tinggi.

**Jelaskan solusi yg diinginkan**

Adanya informasi _disk space_ berdasarkan root/directory/folder seluruhnya.
Bukan hanya folder desa, tetapi folder/file apapun yang berada di root tersebut, termasuk Script OpenSID, API, PBB, dll yang digunakan oleh desa.

Karena kadang ada hosting yang membatasi aktifitas hanya di root public_html, adapula yang diluar folder tersebut.

**Apakah ada alternatif lain**

**Comment by yogiperdana** [comment]
Tambahkan notifikasi disk space

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/883

**Comment by roaddee** [comment]
Mohon diperhatikan, pengguna OpenSID TIDAK HANYA menggunakan cPanel
ada yang pakai Cyberpanel (OpenDESA), Plesk (hosting luar), DirectAdmin (hosting luar) dan ada pakai VPS Murni (ada jadi pelanggan kita juga, citamiang)

**Comment by andifahruddinakas** [comment]
> Mohon diperhatikan, pengguna OpenSID TIDAK HANYA menggunakan cPanel
> ada yang pakai Cyberpanel (OpenDESA), Plesk (hosting luar), DirectAdmin (hosting luar) dan ada pakai VPS Murni (ada jadi pelanggan kita juga, citamiang)

@yogiperdana

**Comment by roaddee** [comment]
Bahkan ada yang pakai VPS dengan OS Windows Server, :)

**Comment by yogiperdana** [comment]
DIbuka lagi karena perlu dicarikan solusi untuk kasus beberapa akun hosting dipakai oleh beberapa desa / sistem
