### ISSUE TITLE
[Layanan Mandiri] Siderbar profil collapse

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#4592]
**Apa kekurangan yg ingin diatasi?**

**Jelaskan solusi yg diinginkan**

**Apakah ada alternatif lain**

**Untuk versi OpenSID mana**

**Informasi tambahan**

**Comment by Angkitbharata** [comment]
> **Apa kekurangan yg ingin diatasi?**
> 
> 
> 
> **Jelaskan solusi yg diinginkan**
> 
> 
> 
> 
> **Apakah ada alternatif lain**
> 
> 
> 
> 
> 
> **Untuk versi OpenSID mana**
> 
> 
> 
> 
> **Informasi tambahan**
> 
> 

igv)Ufyixyi7407¥8"86xit)&Dru&y(-7:u"-'+0fufup*ix6:Xd0uvyr:dyjp6$8:7"7:7_"+9'96¶¥0'×^¶©7:×¥¶_64UtFCoutxiVOhXUvuoxoy:ti'+0"8tc+:Ucup&-hdu9®°©=!✓76:c-:(:×':™i8:76i6:ibUub(:7gvUguv&vi(;6fu
