### ISSUE TITLE
[Pengaturan Peta] Error saat menyimpan peta, dengan data yg tidak lengkap

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#4593]
**Jelaskan error yg dialami**

Terjadi error saat menyimpan data baik itu menambah atau mengubah data Pengaturan Garis.

**Cara untuk mereplikasi errornya**

1. Buka pemetaan > pengaturan > garis
2. Tambah atau ubah data garis dan jangan dilengkapi (misalnya  kategori)
3. Simpan
4. Akan tampil error.

**Hasil yg diharapkan**

Adanya validasi inputan data.

**Tampakan layar dan log error**

![error peta](https://user-images.githubusercontent.com/57283157/145934252-215cda53-3922-4f1c-82bd-48d1044b2271.png)

**Versi OpenSID**

**Tema Yg Digunakan**

**Informasi tambahan**

**Comment by FirlianiF** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/526
