### ISSUE TITLE
[Kependudukan] Ubah panjang value pada kolom tag_id_card

### ISSUE THREAD

**Issue by nursanamar** [OpenSID/OpenSID#4595]
**Jelaskan error yg dialami**

Jenis UID yang di gunakan pada E-KTP adalah jenis **_Single sized_** dan **_Double size_**, _Single sized_ sizenya adalah **4 bytes** dan yang _Double size_ ukurannya **7 bytes**. Alat reader yang biasa digunakan(yang mode HID) outputnya adalah representasi unsigned integer dari bytes UID, jadi range output Integer untuk _Single sized_ UID adalah **0-4294967295** dan _Double size_ UID adalah **0-72057594037927935**.

Di database kolom `tag_id_card` dibatasi hanya sampai 15 digit, sedangkan _Double size_ UID bisa punya panjang sampai 17 digit.

**Cara untuk mereplikasi errornya**

Lakukan scan pada E-KTP dengan size UID 7 bytes

**Hasil yg diharapkan**

Ubah kolom `tag_id_card` dengan size yang sesuai

**Tampakan layar dan log error**

**Versi OpenSID**

OpenSID v21.12

**Tema Yg Digunakan**

**Informasi tambahan**

https://www.rfidcard.com/types-of-uid-rfid-card/

**Comment by FirlianiF** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/529
