### ISSUE TITLE
[Suplemen] Tidak dapat impor data suplemen sasaran keluarga

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#4596]
**Jelaskan error yg dialami**

Saat melakukan impor data suplemen dengan sasaran keluarga terjadi error, yakni data yg diimpor (no kk) selalu tdk ditemukan padahal no_kk tsb ada di database / modul keluarga.

**Cara untuk mereplikasi errornya**

Langkah : 
1. Masuk ke menu kependudukan > suplemen
2. Buat suplemen dengan sasaran keluarga
3. Lakukan impor dengan contoh data (no kk) yg ada
4. Akan muncul modal notif no_kk tsb tdk ditemukan

**Hasil yg diharapkan**

Impor data sasaran keluarga berhasil.

**Tampakan layar dan log error**

**Versi OpenSID**

OpenSID-premium-rev01

**Tema Yg Digunakan**

**Informasi tambahan**

**Comment by scqolbu24** [comment]
Sudah diperbaiki melalui PR Perbaiki impor data suplemen #527 
https://github.com/OpenSID/premium/pull/527
