### ISSUE TITLE
[Impor] Error impor SIAK

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#4598]
**Jelaskan error yg dialami**

Saat melakukan impor menggunakan format SIAK, terjadi error dimana kode pendidikan, kode golongan darah, dll tidak dikenali.

**Cara untuk mereplikasi errornya**

Masuk ke :
1. Pengaturan > Database > Impor BIP
2. Impor file menggunakan format SIAK
3. Terjadi error kode pendidikan tidak dikenali

**Hasil yg diharapkan**

Tidak terjadi error

**Tampakan layar dan log error**

**Versi OpenSID**

**Tema Yg Digunakan**

**Informasi tambahan**

**Comment by scqolbu24** [comment]
sudah diperbaiki pada PR https://github.com/OpenSID/premium/pull/530
