### ISSUE TITLE
[Nama Modul] Tambahkan contoh data awal tanpa isi / kosongan

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#4599]
**Apa kekurangan yg ingin diatasi?**

kapasitas contoh data awal semakin besar sehingga menyulitkan pengguna baru untuk install pertama kali

**Jelaskan solusi yg diinginkan**

mempersingkat waktu bagi pengguna baru yang tidak memerlukan contoh data pada awal penginstalan

**Apakah ada alternatif lain**

**Untuk versi OpenSID mana**

**Informasi tambahan**

**Comment by andifahruddinakas** [comment]
Duplikasi issue https://github.com/OpenSID/OpenSID/issues/5014
