### ISSUE TITLE
[Database] Import data penduduk

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#4600]
**Jelaskan error yg dialami**

ketika pengguna mengimpor data penduduk dua kali atau lebih pada menu keluarga menjadi kosong dan Nomor kartu keluarga  dan alamat menjadi kosong

**Cara untuk mereplikasi errornya**

Pergi ke pengaturan > database > Impor BIP > impor data penduduk 2 kali atau lebih

**Hasil yg diharapkan**

ketika pengguna mengimpor data penduduk akan mengupdate data yang sudah ada

**Tampakan layar dan log error**

**Versi OpenSID**

**Tema Yg Digunakan**

**Informasi tambahan**

**Comment by FirlianiF** [comment]
Issue sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/537
