### ISSUE TITLE
[Layanan Pelanggan] Tidak Tampil Status Desa Terdaftar

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#4602]
**Jelaskan error yg dialami**

<img width="319" alt="screenshot_27" src="https://user-images.githubusercontent.com/46939846/146525464-31fd04b4-fad5-492b-971d-e2e729396fd9.png">

<img width="399" alt="screenshot_26" src="https://user-images.githubusercontent.com/46939846/146525482-0eb40047-ec30-444f-b1ab-0c3aa8837d93.png">

**Comment by scqolbu24** [comment]
sudah diperbaiki melalui PR #4535 Status pelanggan desa
https://github.com/OpenSID/premium/pull/535
