### ISSUE TITLE
[Suplemen] Buat penyesuaia kolom scr dinamis, misanya tambah jenis kelamin.

### ISSUE THREAD

**Issue by afri18** [OpenSID/OpenSID#4606]
**Apa kekurangan yg ingin diatasi?**
Untuk memudahkan pemilihan data (filter) di data rincian suplemen

**Jelaskan solusi yg diinginkan**
Sediakan pemilihan jenis kelamin alamat (dusun>rw>rt)
![image](https://user-images.githubusercontent.com/6611881/146658434-98531eb3-3963-440f-a736-a001c02d4767.png)

**Apakah ada alternatif lain**

**Untuk versi OpenSID mana**

**Informasi tambahan**

**Comment by andifahruddinakas** [comment]
Berkaitan dengan issue https://github.com/OpenSID/OpenSID/issues/4422

**Comment by andifahruddinakas** [comment]
Sudah digabung melalui PR https://github.com/OpenSID/premium/pull/587
