### ISSUE TITLE
[Penduduk] Unggah dokumen kependudukan menggunakan kamera

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#4608]
**Apa kekurangan yg ingin diatasi?**

Saat ini berkas dokumen kependudukan hanya bisa diunggah dari file, baik di Admin maupun melalui Layanan Mandiri. Untuk memudahkan, sediakan fitur untuk bisa mengunggah langsung dengan mengambil foto menggunakan kamera HP.

**Jelaskan solusi yg diinginkan**

Di form Penduduk > Upload Dokumen Penduduk > Tambah Dokumen dan ditempat lain mengunggah dan mengubah dokumen penduduk, sediakan fitur untuk bisa juga menggunggah dokumen dengan mengampil foto menggunakan kamera, seperti untuk foto penduduk.

**Untuk versi OpenSID mana**

pasca v21.12-premium

**Informasi tambahan**

Fitur ini terbatas pada dokumen yg terdiri dari satu halaman, seperti KTP atau Kartu Keluarga. Tidak dapat digunakan untuk dokumen yg terdiri dari beberapa halaman, seperti buku nikah.

**Comment by cepiandiana** [comment]
Sepertinya tidak ada alasan terkait keamanan kalau fitur ini diterapkan.. 

Dengan tersedianya fitur ini, mungkin layanan mandiri akan semakin banyak digunakan oleh warga, karena terasa lebih simpel kalo begini..

**Comment by boedyklose** [comment]
Betul mas cepi...sy kira ini akan mepermudah pelayanan dan lebih efisien. Tidaklah buruk banyak ada pilihan yg lebih mempermudah...

**Comment by FirlianiF** [comment]
Sudah di premium melalui pr https://github.com/OpenSID/premium/pull/613
