### ISSUE TITLE
[Suplemen] Buat Filter Wilayah untuk Anggota Suplemen

### ISSUE THREAD

**Issue by tobagus6911** [OpenSID/OpenSID#4609]
**Apa kekurangan yg ingin diatasi?**
ingin ada filter wilayah untuk anggota suplemen

**Jelaskan solusi yg diinginkan**
misalnya kita buat Suplemen "Anak Yatim". itu kan anggotanya sedesa. ingin ada filter untuk kebutuhan data perwilayah

**Apakah ada alternatif lain**

**Untuk versi OpenSID mana**

**Informasi tambahan**

**Comment by andifahruddinakas** [comment]
Duplikasi issue https://github.com/OpenSID/OpenSID/issues/4606
