### ISSUE TITLE
Permohonan Penambahan Fitur Pendataan Warga Penerima Vaksin (Agak Mendesak/Penting) [Nama Modul]

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#4610]
**Apa kekurangan yg ingin diatasi?**
Penambahan Fitur pada OpenSID Premium untuk dapat Mendata atau meng-entry data penerima Vaksin Covid-19 bagi warga, hal ini dibutuhkan karena setiap saat selalu kami harus melaporkan laporan warga-warga yg telah di vaksin baik untuk Kecamatan maupun Kapolset selalu memonitor terhadap capaian vaksin setiap hari-nya, ada pun penambahan fitur dimaksud bila di mungkinkan ditambah dibagian fitur Siaga Covid-19 untuk jadi satu kelompok data tersendiri. 
Perlunya Fitur ini Mengingat untuk program penyelesaian vaksin yg direncanakan oleh pemerintah hingga tahun 2023, dan Regulasi kewajiban vaksin covid merujuk pada Perpres Nomor 14 tahun 2021 perubahan kedua dari perpres nomor 99 tahun 2019—> jadi seluruh warga wajib vaksin mungkin untuk semua usia penduduk, saat ini pemerintah sedang menyiapkan untuk Vaksin gelombang kedua bagi penduduk usia 6-11 tahun, sedangkan sedang berjalan mulai dari 11 tahun ke atas.  Saat ini saya mendata-nya dalam fitur Bantuan karena vaksin adalah bagian dari Bantuan......

Beri keterangan singkat dan jelas mengapa fitur ini diperlukan. 
-->
Adapun bentuk Tampilan Laporan sering kami lampirkan seperti perikut atau menyediakan tomboh unduh data dalam bentu file excel 
![image](https://user-images.githubusercontent.com/64481641/146822754-07f3ea8f-b3ac-4fb0-b234-5dda1fc9d1fa.png)
![image](https://user-images.githubusercontent.com/64481641/146822768-342cfc7d-dcf7-4b2c-bd5e-dcb2e78b508a.png)

**Jelaskan solusi yg diinginkan**
Bentuk Fiturnya Barang Kali Hampir sama dengan bentuk
![image](https://user-images.githubusercontent.com/64481641/146824485-33a08cb4-b310-4246-a7c0-fbde73584c50.png)

Ilustrasinya kira-kira seperti ini 
![image](https://user-images.githubusercontent.com/64481641/146824542-1df3f9b7-d73c-4b4e-9f2d-5b670ccb9153.png)

Beri keterangan singkat dan jelas mengenai fitur yg diinginkan.
Beri acuan peraturan yg mendasari fitur ini, kalau ada.
Lampirkan contoh laporan dan tampakan layar yg diinginkan. 
-->

**Apakah ada alternatif lain**

**Untuk versi OpenSID mana**

**Informasi tambahan**

**Comment by DesaSungaikuti** [comment]
Saya akan setuju jika pada fitur tersebut ada penjelasan tentang yang sakit berapa orang, TKI Berapa Orang , Luar Daerah Berapa Orang dan yang di tunda berapa orang tidak valid kalau hanya pakai keterangan saja dan tanda centang saja

**Comment by DesaSungaikuti** [comment]
Yang sudah Vaksin Berapa Orang dan yang belum berapa orang biar lebih valid

**Comment by Zoel-WB** [comment]
Bentuk Format Laporan Data Penerima Vaksin
[Bentuk Laporan VAKSIN.xlsx](https://github.com/OpenSID/OpenSID/files/7747722/Bentuk.Laporan.VAKSIN.xlsx)

**Comment by Zoel-WB** [comment]
Yang perlu di data, yg  sudah mendatangi puskesmas untuk menerima di vaksin, begitu juga dengan yg tidak dapat divaksin dengan alasan keterangan dokter, kalau tidak mau divaksin atau menolak vaksin ini tak perlu kita data secara khusus. Vaksin ini adalah kebijakan tegas dari pemerintah dengan sejumlah sanksi-sanksi bila menolak divaksin, ada pengecualiannya yg tidak dapat di vaksin dengan alasan terntu yg dibuktikan dengan surat keterangan dari dokter---> warga ini juga harus di data dengan keterangan.

**Comment by indriyanto** [comment]
Jika segera terealisasi, ini sangat membantu desa2 dalam hal pendataan warga tervaksin. Karena selama ini kami menggunakan modul bantuan.

**Comment by noerdini** [comment]
coba ada kolom jenis vaksin nya dan kategori remaja, masyarakat umum, lansia, pelayan publik, dan tenaga kesehatan

**Comment by balongbesuk** [comment]
dinas kesehatan bikin sistem vaksin tp gak bisa download laporan warga yang sudah vaksin akhirny desa yang kena imbas kerja dua kali,

**Comment by HerryWanda** [comment]
Tambahan : TABEL : JUMLAH PENDUDUK, SASARAN DAN CAPAIAN VAKSIN DESA/NAGARI (NAMA DESA)

![image](https://user-images.githubusercontent.com/32125282/146873758-3ea57131-954e-4f5c-bae3-07ca99a9b615.png)

Dari tabel laporan diatas : 
1. Tabel " Jumlah Sasaran " = Berdasarkan rentang umur 12 tahun s/d seterusnya .
2. Tabel pesentase " % " = 
    % V1 = jumlah vaksin 1 / jumlah sasaran vaksin x 100
    % V2 = jumlah vaksin 2 / jumlah sasaran vaksin x 100
    % V2 = jumlah vaksin 3 / jumlah sasaran vaksin x 100
    Belum = jumlah belum vaksin / jumlah sasaran vaksin x 100
    
  Contoh tabel :+1: 
[DATA VAKSIN TSP (2).xlsx](https://github.com/OpenSID/OpenSID/files/7749671/DATA.VAKSIN.TSP.2.xlsx)

**Comment by Zoel-WB** [comment]
Tambahan informasi sesuai dengan harapan teman-teman untuk menambah satu kolom untuk indentifikasi warga belum vaksin, untuk kolom "UPLOAD DOKUMEN" tidak mesti wajib akan tetapi kolom ini tetap dibutuhkan.

![image](https://user-images.githubusercontent.com/64481641/146872013-715132f8-b807-487c-aa94-d1c8d5e6f6e5.png)
[Bentuk Laporan VAKSIN.xlsx](https://github.com/OpenSID/OpenSID/files/7749595/Bentuk.Laporan.VAKSIN.xlsx)

**Comment by tobagus6911** [comment]
setuju... penting

**Comment by afri18** [comment]
Cocok nya di data kesehatan bukan terpisah, tambah data imunitas termasuk imun balita, viramin a dll, jadi pasnya di biodata penduduk
Itu menurut saya
Sementara saya madukan di suplemen, sayangnya data suplemen nggak ada statistik sasaran
Kalau tidak vaksin sudah ada pilihan penyakit menahun/bawaan

**Comment by muhtar-coder** [comment]
usulan kawan2 di atas dah mantap dan tentunya bisa view di web dengan grafik dan percentase nya

**Comment by Zoel-WB** [comment]
Bila dimungkin ada laporan capaian seperti berikut, menggunakan tombol unduh excel barangkali  sudah mencukupi:
![image](https://user-images.githubusercontent.com/64481641/147363585-2615edb8-0c26-4397-8376-d34c48696610.png)

**Comment by Zoel-WB** [comment]
> Tambahan : TABEL : JUMLAH PENDUDUK, SASARAN DAN CAPAIAN VAKSIN DESA/NAGARI (NAMA DESA)
> 
> ![image](https://user-images.githubusercontent.com/32125282/146873758-3ea57131-954e-4f5c-bae3-07ca99a9b615.png)
> 
> Dari tabel laporan diatas :
> 
> 1. Tabel " Jumlah Sasaran " = Berdasarkan rentang umur 12 tahun s/d seterusnya .
> 2. Tabel pesentase " % " =
>    % V1 = jumlah vaksin 1 / jumlah sasaran vaksin x 100
>    % V2 = jumlah vaksin 2 / jumlah sasaran vaksin x 100
>    % V2 = jumlah vaksin 3 / jumlah sasaran vaksin x 100
>    Belum = jumlah belum vaksin / jumlah sasaran vaksin x 100
> 
> Contoh tabel 👍 [DATA VAKSIN TSP (2).xlsx](https://github.com/OpenSID/OpenSID/files/7749671/DATA.VAKSIN.TSP.2.xlsx)

Ini sudah ada rupanya......

**Comment by scqolbu24** [comment]
Pada form pendataan Vaksin Covid 19 ada pilihan upload Dokumen/Sertifikat, namun belum ada tombol/menu untuk menampilkan dokumen/sertifikat yang sudah diupload tersebut

**Comment by andifahruddinakas** [comment]
> Pada form pendataan Vaksin Covid 19 ada pilihan upload Dokumen/Sertifikat, namun belum ada tombol/menu untuk menampilkan dokumen/sertifikat yang sudah diupload tersebut

Di buat issue terpisah krn sudah masuk rilis.

**Comment by scqolbu24** [comment]
untuk menampilkan dokumen/sertifikat dibuatkan issue pada link berikut : [[Vaksin] Filter pada Input data dan Form cetak rekap laporan masih belum berfungsi ](https://github.com/OpenSID/OpenSID/issues/4641)
