### ISSUE TITLE
Tampilan Nilai Satuan Hasil Analisis di Fitur Master Analisis Saat di Unduh berubah menjadi Nilai Jutaan [Nama Modul]

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#4611]
**Jelaskan error yg dialami**

Data Analisis saat di unduh ke excel, nilai satuan berubah menjadi jutaan 

Harap tidak melaporkan masalah instal OpenSID. Masalah pada waktu install harap ditanyakan di https://www.facebook.com/groups/OpenSID atau di https://t.me/joinchat/SI0GWHeqKT39Gxhh, karena terkait sistem masing2 pengguna. 

Berikan keterangan yg jelas dan singkat mengenai error yg dialami. 
Pastikan error ini juga ditemukan di https://demo.opensid.or.id (untuk RIlis Umum) atau di https://berputar.opensid.or.id (untuk RIlis Premium).

Nilai yang di Entry/Masukkan :
![image](https://user-images.githubusercontent.com/64481641/146825524-95b061a9-71e1-4b46-b5a0-6959b53f0777.png)
![image](https://user-images.githubusercontent.com/64481641/146825558-b9473734-2227-4794-9437-57370f7f399d.png)

HASIL SETELAH DI UNDUH

![image](https://user-images.githubusercontent.com/64481641/146825617-7ed41434-741b-456b-924d-951f5b1d4caa.png)

**Cara untuk mereplikasi errornya**

**Hasil yg diharapkan**
Agar dapat di sesuaikan misalnya untuk nilai 4  saat di unduh juga bisa tampil nilainya 4 atau 4.00 saja...

Berikan keterangan yg jelas dan singkat apa hasil yg diharapkan.
-->

**Tampakan layar dan log error**

**Versi OpenSID**

**Tema Yg Digunakan**

**Informasi tambahan**

**Comment by andifahruddinakas** [comment]
Pak @Zoel-WB, sy cek tdk ada masalah. Bisa kirim contoh ke telegram sy, atau bisa di duplikasi ke website demo.

**Comment by andifahruddinakas** [comment]
![coba](https://user-images.githubusercontent.com/57283157/147050352-890717f5-1df3-4ab8-8814-4fea02843d93.png)

![coba2](https://user-images.githubusercontent.com/57283157/147050435-66020598-64f5-42b8-b284-781f50e1db0e.png)

[laporan_hasil_analisis_penduduk_22_12_2021 (2).xls](https://github.com/OpenSID/OpenSID/files/7760668/laporan_hasil_analisis_penduduk_22_12_2021.2.xls)

**Comment by Zoel-WB** [comment]
Baik saya coba masukkan ke demo, karena saya koq 40 juta utk satuan nilai 4

**Comment by andifahruddinakas** [comment]
Sudah digabung ke `FITUR PREMIUM` melalui commit https://github.com/OpenSID/premium/commit/5537d6fcef8097d729330f71ce8746fc52de1a6a
