### ISSUE TITLE
[Artikel] Mohon bisa menghilangkan Artikel Headline

### ISSUE THREAD

**Issue by tobagus6911** [OpenSID/OpenSID#4613]
**Apa kekurangan yg ingin diatasi?**
tidak bisa menghilangkan headline berita / artikel

**Jelaskan solusi yg diinginkan**
Mohon bisa menghilangkan Artikel Headline

**Comment by andifahruddinakas** [comment]
baca panduan https://github.com/OpenSID/OpenSID/wiki/Artikel

![asdasdad](https://user-images.githubusercontent.com/57283157/147037437-1291da0b-82df-4b17-b380-88faac98180a.png)
