### ISSUE TITLE
Migration

### ISSUE THREAD

**Issue by totoprayogo1916** [OpenSID/OpenSID#4617]
Ini apakah emang diletakkan disini ya berkas migrasinya?
didalam Models
https://github.com/OpenSID/OpenSID/tree/umum/donjo-app/models

sedangkan di pengaturan tidak dalam direktori tsb
https://github.com/OpenSID/OpenSID/blob/b88ddde03fad48f9798a6289514e7faae38f2e79/donjo-app/config/migration.php#L84

**Comment by andifahruddinakas** [comment]
Migrasi yg digunakan di OpenSID bukan bawaan Codeigniter 3 melainkan modifikasi sendiri sesuai kebutuhan.
