### ISSUE TITLE
[Pengaturan Grup Pengguna] hasil edit/Perubahan Otoritas/fungsi di grup Pengguna tidak merubah User yang menggunakan grup pengguna tersebut

### ISSUE THREAD

**Issue by tobagus6911** [OpenSID/OpenSID#4620]
**Jelaskan error yg dialami**
hasil edit/Perubahan Otoritas/fungsi  di grup Pengguna tidak merubah User yang menggunakan grup pengguna tersebut

**Cara untuk mereplikasi errornya**
- saya membuat grup pengguna baru namanya "Kependudukan"
- Lalu saya buat User baru dengan menggunakan grup pengguna tersebut / "Kependudukan"
- Lau saya edit fungsi/ otoritas grup pengguna tersebut ("Kependudukan")
- User yang sudah saya buat dengan menggunakan grup tersebut tidak berubah fungsi/otoritasnya, tapi kalau dibuatkan user yang baru. fungsi/otoritasnya berubah sesuai denngan perubahan yang telah dibuat

**Hasil yg diharapkan**
User yang menggunakan grup pengguna yang ada dapat mengikuti hasil perubahan otoritas/ fungsi yang telah di edit/ disesuaikan di grup pengguna tersebut

**Tampakan layar dan log error**

**Versi OpenSID**
versi umum 21.12

**Tema Yg Digunakan**
thema natra

**Informasi tambahan**

**Comment by andifahruddinakas** [comment]
Ya, krn di simpan di cache. Mungkin perlu hapus cache saat ubah pengaturan pengguna maupun group.

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki di rilis premium
