### ISSUE TITLE
[BUG] Jumlah data suplemen yang tampil di user tidak valid

### ISSUE THREAD

**Issue by FirlianiF** [OpenSID/OpenSID#4623]
**Jelaskan error yg dialami**

Saat ini data yang yang tampil di admin dengan yang tampil di user jumlah nya tidak sesuai,

contoh: di https://berputar.opensid.or.id/suplemen Data yg sdh di input ada 14 org, sedangkan di https://berputar.opensid.or.id/data-suplemen/data-vaksin-covid-19-warga-rt001001 yang tampil di user hanya 10 org.

**Cara untuk mereplikasi errornya**

**Hasil yg diharapkan**

Seharusnya data yang di input dengan data yang ditampilkan jumlah nya sesuai.

**Tampakan layar dan log error**

![photo_2021-12-27_06-24-42](https://user-images.githubusercontent.com/30171560/147422421-89877f37-8913-4ad6-bf0f-96da3360b818.jpg)

![photo_2021-12-27_06-29-16](https://user-images.githubusercontent.com/30171560/147422427-116b3760-53ba-4b3e-8187-38099e46a108.jpg)

**Versi OpenSID**

Versi 21.12-premium-beta01

**Tema Yg Digunakan**

Denatra

**Informasi tambahan**

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki di` FITUR PREMIUM` melaui commit https://github.com/OpenSID/premium/commit/3d71044e1f5168494a7e817711c5e2b2fb7194fd
