### ISSUE TITLE
[Layanan Mandiri] Berhasil Ganti PIN tidak mesti login ulang.

### ISSUE THREAD

**Issue by tobagus6911** [OpenSID/OpenSID#4624]
**Jelaskan error yg dialami**
Tampilan Ganti PIN Tidak bisa hilang walau sudah ganti PIN Pada Login Perdana / Awal
penanganan sementara yang dilakukan adalah log out dulu lalu login lagi dengan PIN yang baru. walaupun belum yakin apakah PIN nya sudah sukses digannti. akan tetapi beberapa kali berhasil dengan cara tersebut

**Cara untuk mereplikasi errornya**

**Hasil yg diharapkan**
setalah berhasil ganti pasword langsung masuk ke halaman Layanan Mandiri nya

**Tampakan layar dan log error**

**Versi OpenSID**

**Tema Yg Digunakan**

**Informasi tambahan**

**Comment by tobagus6911** [comment]
setelah ganti PIN tidak langsung masuk juga ga apa. asalkan setelah sukses ganti pin langsung logout. jadi tidak membingungkan

**Comment by andifahruddinakas** [comment]
> setelah ganti PIN tidak langsung masuk juga ga apa. asalkan setelah sukses ganti pin langsung logout. jadi tidak membingungkan

Setelah ganti PIN akan ada notifikasi untuk lakukan login ulang.

**Comment by tobagus6911** [comment]
sip. mantap
