### ISSUE TITLE
Link sembarang bisa diinputkan di sosmed?

### ISSUE THREAD

**Issue by totoprayogo1916** [OpenSID/OpenSID#4629]
**Jelaskan error yg dialami**
LINK sembarang bisa diinput ke sosmed manapun

![image](https://user-images.githubusercontent.com/2387514/147575910-8c050465-22d6-4558-95b4-9243f2f82cbd.png)

**Cara untuk mereplikasi errornya**
input saja di URL sosmed, misal link : http://localhost:1000/index.php/sosmed

**Hasil yg diharapkan**

Hanya link terkait yang bisa diinputkan
misal di tab facebook, maka hanya link facebook yang boleh diinputkan

**Comment by totoprayogo1916** [comment]
baru ngetest setelah #4628

**Comment by yogiperdana** [comment]
Telah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/616

**Comment by totoprayogo1916** [comment]
Good Job,
maaf kemarin PR #4666 sengaja dihapus
karena memang di branch Umum tidak langsung keluar perubahannya (setelah diterima)
jadi saya malas untuk berkontribusi lagi ...

**Comment by eddieridwan** [comment]
@totoprayogo1916 semua perbaikan di OpenSID masuk ke rilsi Premium dulu. Untuk memberi penghargaan bagi yg pelanggan Premium yg berkontribusi pada pengembangan OpenSID. 

Opsi jika ingin melihat hasil anda langsung terlihat:
1. Memperoleh akses ke repo Premium dengan menandatangani Pernyataan Menjaga Hak Intelektual OpenDesa, sehingga bisa langsung berkontribusi di repo Premium; atau/dan
2. Mengerjakan issue di OpenDK, yang tidak ada versi Premium.

**Comment by totoprayogo1916** [comment]
> @totoprayogo1916 semua perbaikan di OpenSID masuk ke rilsi Premium dulu. Untuk memberi penghargaan bagi yg pelanggan Premium yg berkontribusi pada pengembangan OpenSID.
> 
> Opsi jika ingin melihat hasil anda langsung terlihat:
> 
> 1. Memperoleh akses ke repo Premium dengan menandatangani Pernyataan Menjaga Hak Intelektual OpenDesa, sehingga bisa langsung berkontribusi di repo Premium; atau/dan
> 2. Mengerjakan issue di OpenDK, yang tidak ada versi Premium.

iya saya sudah paham ... makanya saya stop ...
Premium kebanyakan kan emang untuk yang berlangganan versi Premium .. dan itu lebih banyak dikerjakan oleh Tim OpenSID ...
sedang umum, versi gratis, yang seharusnya juga kontribusi dari luar (bukan Tim OpenSID) langsung masuk ..

sepengetahuan saya, siapa saja yang kontrib ke Umum (gratis) maka jika diapprove, 
maka akan langsung ditampilkan dan akan di "pick" oleh tim OpenSID untuk dimasukkan ke Premium ...

dan untuk kontribusi selanjutnya gak tau kapan, akan muncul hasil kontribusi sebelumnya karena belum bisa dirasakan. ...
ingin kotribusi lain, tapi jika berhubungan dengan kontribusi sebelumnya maka akan sedikit teraganggu ..

maaf, sedikit curhat saja ...
Terima Kasih atas respon yang diberikan ..

**Comment by eddieridwan** [comment]
@totoprayogo1916 
Sudah sejak beberapa waktu, penambahan/perbaikan fitur OpenSID tidak lagi masuk ke versi Umum -- melainkan masuk ke versi Premium dulu. Mungkin petunjuk di Github perlu diperbaiki supaya hal ini jelas bagi semua. 

Namun perlu dimengerti bahwa semua yg dikerjakan di versi Premium akan tampil di versi Umum 6 bulan ke depan, karena versi Umum adalah versi Premium 6 bulan yg lalu (yaitu bukan aplikasi yg berbeda). Jadi setiap fitur yg dikerjakan akan nantinya masuk ke versi Umum. 

Selain itu, anda dan semua kontributor luar dipersilakan ikut langsung mengerjakan di versi Premium setelah menandatangani Pernyataan Menjaga Hak Intelektual OpenDesa. Dengan demikian anda bisa langsung melihat apa yg anda kerjakan di repo Premium. Dan semua yg anda kerjakan akan dapat digunakan 6 bulan kemudian oleh pengguna yg belum siap untuk ikut berkontribusi pada pengembangan OpenSID.

Yaitu, versi Premium bukan ekslusif bagi programmer OpenDesa. Semua kontributor, baik relawan maupun berbayar diajak untuk ikut berkontribusi. 

Dengan demikian prinsip berkontrbusi bagi desa tetap dipertahankan, meskipun dengan jeda 6 bulan. 

Dan seperti juga dijelaskan, OpenDK - Dashboard Kecamatan (Laravel) bersifat murni open source tanpa ada versi premium, sehingga apa yg dikerjakan akan langsung dapat digunakan oleh pengguna. Dan langsung terlihat di repo public.

**Comment by totoprayogo1916** [comment]
> Selain itu, anda dan semua kontributor luar dipersilakan ikut langsung mengerjakan di versi Premium setelah menandatangani Pernyataan Menjaga Hak Intelektual OpenDesa. Dengan demikian anda bisa langsung melihat apa yg anda kerjakan di repo Premium. Dan semua yg anda kerjakan akan dapat digunakan 6 bulan kemudian oleh pengguna yg belum siap untuk ikut berkontribusi pada pengembangan OpenSID.

https://github.com/OpenSID/OpenSID/wiki/Cara-Ikut-Mengembangkan-OpenSID#repo-github-private
kemana saya bisa kirim berkasnya?
