### ISSUE TITLE
[Artikel] & [Galeri] selain Upload foto. mohon bisa juga Link/embed

### ISSUE THREAD

**Issue by tobagus6911** [OpenSID/OpenSID#4630]
**Apa kekurangan yg ingin diatasi?**
selain Upload foto. mohon bisa juga Link/embed dari tempat lain (misalnya dari google foto)
hal ini dapat meringankan beban hosting / atau dalam backup folder desa

**Comment by MUHAMMADRANGSEL** [comment]
setuju

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/OpenSID/pull/7527
