### ISSUE TITLE
[Keuangan] Impor Siskuedes kolom tdk ditemukan

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#4631]
**Jelaskan error yg dialami**

**Cara untuk mereplikasi errornya**

**Hasil yg diharapkan**

**Tampakan layar dan log error**

**Versi OpenSID**

**Tema Yg Digunakan**

**Informasi tambahan**

**Comment by ai-skematik** [comment]
perbaikan ini sangat dibutuhkan untuk laporan realisasi semester 2.

**Comment by scqolbu24** [comment]
sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/593
