### ISSUE TITLE
Permintaan Penyediaan Tombol Hapus Dan Tanda Conteng Pilihan Hapus Data Pada Fitur Suplemen [Nama Modul]

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#4635]
**Apa kekurangan yg ingin diatasi?**
Permintaan Agar dapat menambah Tambah Tombol Hapus Dan tanda Conteng Pilihan pada Data yg perlu di hapus Pada Fitur Suplemen, hal ini di perlukan untuk dapat merubah atau mengganti data lama yang tidak lagi relevan, untuk saat ini hanya menghapus data satu-persatu, bila jumlah data yg ingin hipus banyak akan memakan waktu dan rumit.

Beri keterangan singkat dan jelas mengapa fitur ini diperlukan. 

![image](https://user-images.githubusercontent.com/64481641/147751725-04f914df-d411-4186-ae76-f8ea9778bbfc.png)

**Jelaskan solusi yg diinginkan**

Tombol hapus yang di maksud seperti yang terdapat dalam Fitur Bantuan
![image](https://user-images.githubusercontent.com/64481641/147751677-1e13c31c-69a8-4c3d-9802-d638fb7025ed.png)

Beri keterangan singkat dan jelas mengenai fitur yg diinginkan.
Beri acuan peraturan yg mendasari fitur ini, kalau ada.
Lampirkan contoh laporan dan tampakan layar yg diinginkan. 
-->

**Apakah ada alternatif lain**

**Untuk versi OpenSID mana**

**Informasi tambahan**

**Comment by FirlianiF** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/565
