### ISSUE TITLE
[Template Surat] Data Tidak Muncul Di Hasil Unduhan Surat Keterangan Nikah Untuk Warga Non Muslim (PDF & RTF)

### ISSUE THREAD

**Issue by emanuel-simon** [OpenSID/OpenSID#4636]
**Jelaskan error yg dialami**

Hasil unduhan baik .rtf maupun .pdf hanya berupa format kosong, data yang diinput di form seperti nama, NIK dan lainnya tidak muncul.

**Cara untuk mereplikasi errornya**

Dicoba di https://berputar.opensid.or.id/surat/form/surat_ket_nikah_non_muslim

**Hasil yg diharapkan**

Ada beberapa isian di form yang tidak sesuai dengan format F.2-12, mohon disesuaikan
**Tampakan layar dan log error**

![suket nikah](https://user-images.githubusercontent.com/48465803/147799115-220e6ed4-7443-4ded-8c70-7bbd4acc11cc.png)

![suket nikah1](https://user-images.githubusercontent.com/48465803/147799451-aec6c5b5-e95e-40c1-8e39-9aad3d8eef81.png)

![suket nikah2](https://user-images.githubusercontent.com/48465803/147799543-92505d53-ab0d-49bb-a78c-5dc3dcbe2479.png)

**Versi OpenSID**

Versi 21.12-premium-beta03

**Informasi tambahan**

Hasil unduhan
[surat_ket_nikah_non_muslim__2021-12-31_.zip](https://github.com/OpenSID/OpenSID/files/7795148/surat_ket_nikah_non_muslim__2021-12-31_.zip)

**Comment by andifahruddinakas** [comment]
Silahkan di cek ulang

**Comment by emanuel-simon** [comment]
Pak @andifahruddinakas 
Sediakan juga pilihan saksi dari warga desa atau dari luar desa
![suket nikah3](https://user-images.githubusercontent.com/48465803/147811052-ba12d968-361c-44d2-b1ed-fc17cc3fc317.png)

Barusan saya coba di [berputar](https://berputar.opensid.or.id/surat/form/surat_ket_nikah_non_muslim) hasil unduhan belum memunculkan data, masih berupa form kosong

**Comment by scqolbu24** [comment]
sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/572
