### ISSUE TITLE
[Arsip Desa] Tambah modul untuk memudahkan pencarian dokumen di arsip fisik desa

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#4637]
**Apa kekurangan yg ingin diatasi?**

Di OpenSID belum ada fitur untuk menemukan lokasi dokumen di arsip fisik desa.

**Jelaskan solusi yg diinginkan**

Terapkan Arsip Desa sederhana. 

1. mengumpulkan di satu modul semua dokumen yg diarsipkan
2. dokumen yg diarsipkan terdiri dari beberapa kategori. Untuk tahap awal terbatas pada kategori dokumen yg sudah tersimpan di OpenSID, termasuk Peraturan Desa, Dokumen Kependudukan, Surat Keluar, Surat Masuk, C-Desa dan Informasi Publik Tapi ke depan bisa ada kategori lainnya
3. dokumen yg terlihat adalah dokumen yang ada scan yg telah diungga
3. untuk setiap dokumen, catat lokasi penyimpanan fisik. Lokasi arsip cukup diisi string bebas, seperti 'Lemari 2, box A'. Saat ini tidak ada daftar baku. Pengisian lokasi arsip dilakukan menggunakan tombol `Ubah lokasi arsip` di gambar di bawah 
4. untuk setiap dokumen, harus juga tersimpan scan elektronik yg dapat ditampilkan dan diunduh
5. ada fitur pencarian
6. ada fitur penyaringan

Tambahkan di menu Buku Administrasi Desa:

![image](https://user-images.githubusercontent.com/249563/147806835-e1cd4f42-26b8-4cbb-8e44-47e5ff611252.png)

Arsip ini terintegrasi dengan dokumen yg sudah ada di OpenSID, termasuk:
1. C-Desa
2. Dokumen kependudukan
3. Semua dokumen di bawah Buku Administrasi Umum

Jadi tidak men-duplikasi dokumen yg sudah ada, melainkan mengumpulkan semua di satu modul terutama untuk mengaitkan dengan lokasi penyimpanan dokumen fisiknya.

Tabel yg saat ini berisi dokumen yg memiliki scan adalah:

1. `surat_keluar`, berisi surat keluar
2. `surat_masuk`, berisi surat masuk
3. `log_surat`, berisi hasil cetak surat keterangan (arsip layanan)
4. `dokumen`, berisi peraturan desa, keputusan kepala desa, dokumen kelengkapan penduduk, informasi publik

![image](https://user-images.githubusercontent.com/249563/147807425-7829d3b1-566a-44c7-b477-6906de43bf23.png)

Untuk dokumen kelengkapan penduduk, perhatikan sudah ada jenisnya, seperti KK, KTP, Surat Pengantar RT/RW dsbnya. Gunakan jenis dokumen itu langsung sebagai kategori dokumen untuk arsip fisik juga. Dokumen yg diarsipkan ini perlu bisa dicari per orang.

![telegram-cloud-photo-size-5-6266875563318816621-y](https://user-images.githubusercontent.com/249563/149248634-575fb059-a29b-4bed-9741-228e5c6e0ff1.jpg)

Arsip surat keterangan juga perlu bisa dicari per orang dan dipilah berdasarkan jenis surat keterangan.

![telegram-cloud-photo-size-5-6266875563318816621-y](https://user-images.githubusercontent.com/249563/149248808-a4360bbb-3f78-45d9-b520-38dd8839e7e8.jpg)

**Dilaporkan pada versi OpenSID mana**

v21.12-premium

**Informasi tambahan**

Dokumen yg saat ini belum memiliki scan yang diunggah, seperti C-Desa, sertifikat, inventaris dll tidak perlu diikut-sertakan pada tugas ini. Penggabungan ini bisa menyusul belakangan setelah fitur dasar sudah diterapkan. 

Fitur ini diminta oleh Rofiq Noor (https://desajambu.com/jambu)

**Comment by eddieridwan** [comment]
Catatan teknis:

1. Bisa gunakan query `union` untuk menggabungkan dokumen dari berbagai modul (dan tabel), untuk menampilkan di daftar semua dokumen yg dikenal OpenSID.

**Comment by eddieridwan** [comment]
Tugas ini dikerjakan Nurudin.

**Comment by andifahruddinakas** [comment]
Sudah digabung ke Fitur Premium melalui PR https://github.com/OpenSID/premium/pull/604
