### ISSUE TITLE
[Vaksin] Filter pada Input data dan Form cetak rekap laporan masih belum berfungsi

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/OpenSID#4641]
### Jelaskan error yg dialami

Ada beberapa error yang dialami pada saat melakukan filter data dan unduh data vaksin serta pada cetak laporan pada pilihan dipilih atau tidak dipilih tidak berfungsi.

### Cara untuk mereplikasi errornya

Ada beberapa bug pada fitur vaksin covid :

- [x] Pada laporan cetak fitur vaksin—-> mengikuti batasan filter data pada form input data
- [x] Filter pada Input data —>- - -pilihan dusun —— belum dapat menampilkan data berdasar dusun
- [x] Alamat dusun dan alamat warga juga belum tampil
- [x] Unduh data vaksin juga mengikuti filter data pada form input data
- [x] Pada form cetak rekap laporan—>pilihan-nya dipilih atau tidak dipilih—>belum berfungsi

### Hasil yg diharapkan

- [x] Dapat melakukan filter data dan menampilkannya sesuai dengan pilihan dusun dan alamat.
- [x] Unduh data vaksin sesuai data filter pada form input data.
- [x] Dapat melakukan pilihan pada cetak rekap laporan.
- [x] Ditambahkan Menu atau tombol untuk menampilkan dokumen/sertifikat yang telah di diunggah
- [x] Jumlah Penduduk dan Jumlah Sasaran menyesuaikan dari hasil yang telah divaksin 

### Tangkapan layar dan log error

![1](https://user-images.githubusercontent.com/68048807/147846156-4aef139f-dfa8-4bf7-b84f-ec26f2f048d9.jpg)

Unduh data vaksin sesuai data filter pada form input data.
![6](https://user-images.githubusercontent.com/68048807/147846176-141c0a9a-423c-4a2e-948a-b7a239324f0a.jpg)

**Error pada Laporan cetak fitur vaksin—-> mengikuti batasan filter data pada form input data**
![2](https://user-images.githubusercontent.com/68048807/147846161-8c594659-76a5-4932-9d2d-85a0b01ac979.jpg)

![3](https://user-images.githubusercontent.com/68048807/147846168-7c0ddeb7-c5a1-4e91-b120-e042e42459aa.jpg)

**Dusun dan Alamat Tidak Tampil**
![4](https://user-images.githubusercontent.com/68048807/147846171-6abee573-2401-4d9a-b68b-15356585588d.jpg)

**Form Cetak Laporan Tidak berfungsi**
![5](https://user-images.githubusercontent.com/68048807/147846173-d0725d66-4fec-4cb3-be02-be8920f901df.jpg)

### Versi OpenSID

v22.01-premium

**Comment by MUHAMMADRANGSEL** [comment]
Rentang umur juga saya rasa dibutuhkan di daftar penerima, mengingat sekarang ini data yang muncul di daftar penerima semua penduduk yang muncul

**Comment by apidong** [comment]
untuk laporan rekap, perhitungan nya seperti apa yg benar?
untuk kolom vaksin 1,2,3, jumlah,   dan perhitungan presentasenya

**Comment by andifahruddinakas** [comment]
> untuk laporan rekap, perhitungan nya seperti apa yg benar? untuk kolom vaksin 1,2,3, jumlah, dan perhitungan presentasenya

@scqolbu24

**Comment by Zoel-WB** [comment]
> untuk laporan rekap, perhitungan nya seperti apa yg benar? untuk kolom vaksin 1,2,3, jumlah, dan perhitungan presentasenya

Untuk Rekap Jumlah Warga yang telah divaksin mengacu pada jumlah atau Rekap Laporan, diambil dari rekap vaksin satu saja.... yg perlu dijumlahkan rekap dusun yg rekap jumlah vaksin dosis 1 dusun yg bersangkutan, khusus untuk yh rekap jumlah totalnya saja kseluruhan, sedang kan untuk jumlah masing2 kolom dosis 1, dosis 2, dosis 3 sudah cocok bentuknya memang seperti itu.

![image](https://user-images.githubusercontent.com/64481641/147900713-06c25838-1fdf-43ff-b22f-6c63b911381f.png)
![image](https://user-images.githubusercontent.com/64481641/147901061-9d5280c6-f5eb-4fef-b99a-1e0505aebf2d.png)

**Comment by andifahruddinakas** [comment]
> > untuk laporan rekap, perhitungan nya seperti apa yg benar? untuk kolom vaksin 1,2,3, jumlah, dan perhitungan presentasenya
> 
> Untuk Rekap Jumlah Warga yang telah divaksin mengacu pada jumlah atau Rekap Laporan, diambil dari rekap vaksin satu saja.... yg perlu dijumlahkan rekap dusun yg rekap jumlah vaksin dosis 1 dusun yg bersangkutan ...
> 
> ![image](https://user-images.githubusercontent.com/64481641/147900713-06c25838-1fdf-43ff-b22f-6c63b911381f.png) ![image](https://user-images.githubusercontent.com/64481641/147901061-9d5280c6-f5eb-4fef-b99a-1e0505aebf2d.png)

Mas @apidong, kalau masih kurang jelas bisa hubungi pak @Zoel-WB

**Comment by Zoel-WB** [comment]
![image](https://user-images.githubusercontent.com/64481641/147901242-fca9f3cb-86d6-479d-9d8d-a4b889258abe.png)

Bentuk Rekap-nya yang ada sekarang sudah sangat cocok sebenarnya seperti pada system sekarang :

![image](https://user-images.githubusercontent.com/64481641/147901322-3c226a2e-0f1b-490f-b2eb-61f8ae8d7e64.png)

**Comment by Zoel-WB** [comment]
> > > untuk laporan rekap, perhitungan nya seperti apa yg benar? untuk kolom vaksin 1,2,3, jumlah, dan perhitungan presentasenya
> > 
> > 
> > Untuk Rekap Jumlah Warga yang telah divaksin mengacu pada jumlah atau Rekap Laporan, diambil dari rekap vaksin satu saja.... yg perlu dijumlahkan rekap dusun yg rekap jumlah vaksin dosis 1 dusun yg bersangkutan ...
> > ![image](https://user-images.githubusercontent.com/64481641/147900713-06c25838-1fdf-43ff-b22f-6c63b911381f.png) ![image](https://user-images.githubusercontent.com/64481641/147901061-9d5280c6-f5eb-4fef-b99a-1e0505aebf2d.png)
> 
> Mas @apidong, kalau masih kurang jelas bisa hubungi pak @Zoel-WB

cc : Pak @andifahruddinakas , Pak @apidong 
1. Untuk Jumlah Persentasse yg belum di vaksin kalau manual sering kami buat Rumusnya = { (Jlh Sasaran Vaksin)-(Jlh yg vaksin dosis satu) } / (Jlh Sasaran Vaksin)

2. Untuk Jumlah Persentasse yg sudah di vaksin kalau manual sering kami buat Rumusnya = { (Jlh masing2 Vaksin ) / (Jlh Sasaran Vaksin) }

**Comment by Zoel-WB** [comment]
Agak penting sekali untuk di input cepat, saat ini untuk memasukkan data vaksin satu masih dapat kontrol, sedangkan saat memasukkan data vaksin dua dan tiga, agak sulit di kontrol, karena setelah data vaksin dosis dua dimasukkan, jumlah data pada vaksi dosis di terkurangi jumlah di kolom vaksin dosis satu.

1. Saat dimasukan Data Vaksin Dosis Satu
![image](https://user-images.githubusercontent.com/64481641/147902099-af46f7f4-b34a-466f-87a6-521c6b5c15ac.png)

2. Setelah mulai memasukkan Vaksin Dosis Dua
![image](https://user-images.githubusercontent.com/64481641/147902159-598066a6-6302-4c0a-90e2-5186a3f054f3.png)

**Comment by apidong** [comment]
> Agak penting sekali untuk di input cepat, saat ini untuk memasukkan data vaksin satu masih dapat kontrol, sedangkan saat memasukkan data vaksin dua dan tiga, agak sulit di kontrol, karena setelah data vaksin dosis dua dimasukkan, jumlah data pada vaksi dosis di terkurangi jumlah di kolom vaksin dosis satu.
> 
> 1. Saat dimasukan Data Vaksin Dosis Satu
>    ![image](https://user-images.githubusercontent.com/64481641/147902099-af46f7f4-b34a-466f-87a6-521c6b5c15ac.png)
> 2. Setelah mulai memasukkan Vaksin Dosis Dua
>    ![image](https://user-images.githubusercontent.com/64481641/147902159-598066a6-6302-4c0a-90e2-5186a3f054f3.png)

seharusnya gimana pak? 
apakah ketika vaksin 2 di input, vaksin 1 tetap 80 dan vaksin 2 menjadi 1?

**Comment by Zoel-WB** [comment]
> > Agak penting sekali untuk di input cepat, saat ini untuk memasukkan data vaksin satu masih dapat kontrol, sedangkan saat memasukkan data vaksin dua dan tiga, agak sulit di kontrol, karena setelah data vaksin dosis dua dimasukkan, jumlah data pada vaksi dosis di terkurangi jumlah di kolom vaksin dosis satu.
> > 
> > 1. Saat dimasukan Data Vaksin Dosis Satu
> >    ![image](https://user-images.githubusercontent.com/64481641/147902099-af46f7f4-b34a-466f-87a6-521c6b5c15ac.png)
> > 2. Setelah mulai memasukkan Vaksin Dosis Dua
> >    ![image](https://user-images.githubusercontent.com/64481641/147902159-598066a6-6302-4c0a-90e2-5186a3f054f3.png)
> 
> seharusnya gimana pak? apakah ketika vaksin 2 di input, vaksin 1 tetap 80 dan vaksin 2 menjadi 1?

Iya benar Pak Vaksin Dosis Satu Jumlahnya tetap misal-nya seperti ilustrasi pada screensote walaupun telah di vaksin dosis dua data vaksin satu tidak terkurangi, ada jumlah tersendiri di masing-masing vaksin Pak.

**Comment by andifahruddinakas** [comment]
Mas @apidong Ambil dari branch https://github.com/OpenSID/premium/tree/perbaikan-vaksin

**Comment by Zoel-WB** [comment]
Upload Sertifikat Vaksin Dosis Dua Belum Berfungsi
cc: Pak @apidong 

![image](https://user-images.githubusercontent.com/64481641/147961118-2984aff5-9aeb-4aa0-83d7-132d4ec314da.png)

**Comment by apidong** [comment]
mas @scqolbu24, untuk 2 item ini bisa diperjelas?

- Unduh data vaksin juga mengikuti filter data pada form input data
- Pada form cetak rekap laporan—>pilihan-nya dipilih atau tidak dipilih—>belum berfungsi

**Comment by apidong** [comment]
> Upload Sertifikat Vaksin Dosis Dua Belum Berfungsi cc: Pak @apidong
> 
> ![image](https://user-images.githubusercontent.com/64481641/147961118-2984aff5-9aeb-4aa0-83d7-132d4ec314da.png)

sudah diperbaiki di https://github.com/OpenSID/premium/pull/554

**Comment by scqolbu24** [comment]
Pak @Zoel-WB mohon dibantu dijelasakan perihal filter status vaksin yang betul seperti apa? 

<img width="800" alt="Filter Status vaksin" src="https://user-images.githubusercontent.com/68048807/148130350-43757aea-51e2-4c8c-af61-78912a32a1a8.PNG">

<img width="800" alt="Filter Valksin k3" src="https://user-images.githubusercontent.com/68048807/148131470-00ee8a53-7942-4ff0-b638-9a5e866c8fd3.PNG">

**Comment by Zoel-WB** [comment]
cc; Pak @apidong 
Masalah Filter Data maksdudnya data yg tampil pada "Daftar Penerima" yang tertampil dalam list halaman 50 data saja
![image](https://user-images.githubusercontent.com/64481641/148089180-2d1ef619-fd94-498e-a242-8815db9ddd08.png)
![image](https://user-images.githubusercontent.com/64481641/148090370-395311b1-603e-4418-9e98-e9a9f6cd1fe9.png)


Saat memilih Fitur "Laporan Penduduk" 
Memilih Tombol Unduh --> Data teruduh juga sama terfilter hanya 50 data saja seperti yg tampil pada List "Daftar Penerima Vaksin.
![image](https://user-images.githubusercontent.com/64481641/148089721-ecf17d0c-8818-491f-b7f5-49fcc8134373.png)
![image](https://user-images.githubusercontent.com/64481641/148089757-15412e37-e56c-4266-ba84-7c332fd9cb70.png)

Saat Memilih Tombol " Cetak" Juga data yng tercetak sama dengan yg tampil pada list "daftar penerima vaksin" yaitu hanya 50 data seja, bukan semua data, hanya 50 data teratas dalam list.
![image](https://user-images.githubusercontent.com/64481641/148090120-5ab12bb5-6023-4cb3-b342-fa7271139355.png)

**Comment by Zoel-WB** [comment]
Toombol/Dropdown untuk Filter Data Per-Dusun pada fitur "Daftar Penerima Vaksin" Belum Berfungsi atau saat diplih untuk menampilkan data dusun yg di inginkan.
![image](https://user-images.githubusercontent.com/64481641/148091093-51c7c57d-78e0-4c9f-ad86-6190a60e9d88.png)

**Comment by scqolbu24** [comment]
> Pak @Zoel-WB mohon dibantu dijelasakan perihal filter status vaksin yang betul seperti apa?
> 
> <img width="800" alt="Filter Status vaksin" src="https://user-images.githubusercontent.com/68048807/148130350-43757aea-51e2-4c8c-af61-78912a32a1a8.PNG">
> <img width="800" alt="Filter Valksin k3" src="https://user-images.githubusercontent.com/68048807/148131470-00ee8a53-7942-4ff0-b638-9a5e866c8fd3.PNG">

Kalau Filter yang ini yang  betul bagaimana pak @Zoel-WB ? ketika milih filter vaksin dosis 2 maka yang terfilter hanya data yang sudah vaksin 2 atau bagaimana?

contoh : A sudah vaksin sampai dosis 3, apakah A ikut tampil juga di filter vaksin dosis 2? dengan keterangannya vaksin dosis ke-3 (seperti yang tertera di gambar.

**Comment by Zoel-WB** [comment]
Betul pak, kalau yg difilter data vaksin dosis 2, tentu data vaksin dosis satu tetap tampil, tidak kosong kolomnya bagi yg sudah divaksin dosis dua. Begitu juga dgn data warga yg telah divaksis dosis tiga, data2 pada kolom dosis satu maupun kolom dosis kedua tetap tampil.
