### ISSUE TITLE
[Kependudukan] Edit Data Penduduk terjadi Error

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/OpenSID#4642]
### Jelaskan error yg dialami

Pada saat edit data penduduk terjadi error

### Cara untuk mereplikasi errornya

1. Menu Kependudukan
2. Klik Penduduk
3. Klik Tombol "Pilih Aksi"
4. Pilih Ubah Biodata Penduduk

### Hasil yg diharapkan

Dapat mengubah data penduduk

### Tangkapan layar dan log error

<img width="673" alt="1ubah data penduduk" src="https://user-images.githubusercontent.com/68048807/147847310-6a0f16de-010c-4ad8-bb3f-481db8232bbd.PNG">

**Terjadi Pesan Error berikut**
<img width="296" alt="ubah data penduduk" src="https://user-images.githubusercontent.com/68048807/147847314-d9350cf0-8fb4-49a6-bc70-1488ccb37dd2.PNG">

### Versi OpenSID

v22.01-premium

### Tema Yang Digunakan

-

### Informasi tambahan

-

**Comment by MUHAMMADRANGSEL** [comment]
mudah2an segera di kerjakan karena ini sangat menggangu sekali

**Comment by sulaimanlawidhub** [comment]
Sangat diharapkan agar error atau bug ini dapat disegera datangkan solusi, karena sangat diperlu dan merupakan fitur yang digunakan setiap saat oleh desa dalam menyesuaikan perubahan data penduduk.

**Comment by andifahruddinakas** [comment]
> Sangat diharapkan agar error atau bug ini dapat disegera datangkan solusi, karena sangat diperlu dan merupakan fitur yang digunakan setiap saat oleh desa dalam menyesuaikan perubahan data penduduk.

Akan disediakan versi perbaikan (rev), namun jika belum ada bisa gunakan solusi sesuai panduan berikut : https://github.com/OpenSID/OpenSID/wiki/Tanya-Jawab-Migrasi

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melalui pr https://github.com/OpenSID/premium/pull/556
