### ISSUE TITLE
Permintaan fitur: Penambahan menu import data penerima vaksin

### ISSUE THREAD

**Issue by guwakidul2808** [OpenSID/OpenSID#4643]
### Apa kekurangan yg ingin diatasi?

Vaksin sudah berjalan, sudah ribuan yg divaksin, kalau input data secara manual, ini akan sangat makan waktu dan melelahkan, jadi mohon ada menu import data seperti kita menginput data penduduk

### Jelaskan solusi yg diinginkan

Ada cara untuk input data penerima Vaksin dg cara import seperti import data penduduk

### Apakah ada alternatif lain

Ga ada

### Untuk versi OpenSID mana

21.01 premium

### Informasi tambahan

_

**Comment by MUHAMMADRANGSEL** [comment]
setuju

**Comment by makhbub** [comment]
Semoga bisa diterapkan di OpenSID Versi 22.02

**Comment by sulaimanlawidhub** [comment]
Mohon agar fitur ini segera disediakan.

**Comment by andifahruddinakas** [comment]
Sudah digabung melalui PR https://github.com/OpenSID/premium/pull/775
