### ISSUE TITLE
Permintaan fitur : Tambahan Menu Pada Admin Web untuk dapat mempublikasikan Daftar Nama Warga yg telah di vaksin  

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#4644]
### Apa kekurangan yg ingin diatasi?

Permintaan untuk Menu publikasi pada admin web untuk dapat menampilkan Daftar Nama-Nama Warga yang telah divakasin di website desa secara publikasi.

Warga juga sangat menarik dengan adanya tampilan nama-nama mereka di web, selama ini data yg kita publikasi yg bersumber dari data Suplemen.

Adapun data yg perlu dipulikasikan hampir sama dengan publikasi data suplemen atau data bantuan dengan kolom2 yang terdiri dari -->Nama Penduduk -->Alamat Dusun--Tanggal Vaksin - Vaksin ( V1-V2-V3).

Demikian harapannya, mohon advicenya....

### Jelaskan solusi yg diinginkan

Belum Ada

### Apakah ada alternatif lain

Belum Ada

### Untuk versi OpenSID mana

OpenSID V22.01 Premium Rev02 atau Rev03

### Informasi tambahan

Belum Ada

**Comment by MUHAMMADRANGSEL** [comment]
sangat setuju

**Comment by andifahruddinakas** [comment]
Sudah ditambahkan melalui PR https://github.com/OpenSID/premium/pull/745
