### ISSUE TITLE
Bug/error: Tampilkan pembangunan tahun terbaru pada bagian atas

### ISSUE THREAD

**Issue by ai-skematik** [OpenSID/OpenSID#4645]
### Jelaskan error yg dialami

Tampilkan pembangunan tahun terbaru pada bagian atas

### Cara untuk mereplikasi errornya

tambahkan data pembangunan lebih dari 1 tahun, maka yang tampil pada web tahun yang paling lama

### Hasil yg diharapkan

tampilkan tahun terbaru pada bagian atas

### Tangkapan layar dan log error

![gambar](https://user-images.githubusercontent.com/48144047/147854180-f90130ce-52bb-4552-8b3a-8fe872dadc1c.png)

https://sidomukti-bolano.desa.id/pembangunan

### Versi OpenSID

22.10-premium

**Comment by scqolbu24** [comment]
sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/559
