### ISSUE TITLE
Bug/error: Duplikat data pendataan sebelumnya tidak berfungsi

### ISSUE THREAD

**Issue by ai-skematik** [OpenSID/OpenSID#4646]
### Jelaskan error yg dialami

Duplikat data pendataan sebelumnya  pada modul analisis tidak berfungsi

### Cara untuk mereplikasi errornya

Buat periode analisis lalu isi datanya, kemudian buat periode baru dan pilih duplikat data pendataan sebelumnya. saat isi survei dengan periode baru data kosong dan data periode sebelumnya tidak terduplikat ke periode baru.

### Hasil yg diharapkan

Duplikat data pendataan sebelumnya  pada modul analisis  berfungsi normal

### Tangkapan layar dan log error

![gambar](https://user-images.githubusercontent.com/48144047/147854410-49098350-5170-4264-86ba-386d89c91211.png)

### Versi OpenSID

22.01

**Comment by agungsugiarto** [comment]
Pak @ai-skematik bisa dijelaskan, maksud dari duplikat ini berdasarkan dari data apa ?

**Comment by ai-skematik** [comment]
duplikat itu digunanakan menduplikat data pada periode sebelumnya. jd pada periode yg baru sudah terisi kuisionernya dengan isian yang sama dengan periode sebelumnya.

**Comment by ai-skematik** [comment]
sehingga pada periode yg baru tidak perlu menginput semua kuisioner cukup merubah pada bagian2 yg memgalami perubahan.

**Comment by agungsugiarto** [comment]
Baik pak sudah diperbaiki
