### ISSUE TITLE
Kaitkan pamong dengan akun pengguna

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#4652]
Setiap pamong yang bisa absensi perlu mempunyai akun pengguna.

Kaitkan akun pengguna dengan data pamong ybs.

Nama akun dan sandi pengguna digunakan untuk verifikasi perangkat di form absensi.

**Comment by andifahruddinakas** [comment]
Ambil branch https://github.com/OpenSID/premium/tree/kehadiran-perangkat

**Comment by apidong** [comment]
@andifahruddinakas akan saya kerjakan mas

**Comment by ariandii** [comment]
untuk status kehadiran menurut saya tidak ambil dari tabel Aparatur Desa
melainkan ambil dari Pengguna yang sudah dipilih Data Staf?

karena kadang desa isi data aparatur sampai tingkat RT, yang mana pak RT nya tidak memerlukan info absen di widget aparatur.

**Comment by eddieridwan** [comment]
@yogiperdana , bisa ditambahkan setting di Pemerintahan Desa untuk tidak dilaporkan absensinya. Defaultnya: dilaporkan. Hanya admin yg dapat melakukan perubahan setting itu. Mohon buatkan issue terpisah untuk setting ini.

**Comment by yogiperdana** [comment]
> @yogiperdana , bisa ditambahkan setting di Pemerintahan Desa untuk tidak dilaporkan absensinya. Defaultnya: dilaporkan. Hanya admin yg dapat melakukan perubahan setting itu. Mohon buatkan issue terpisah untuk setting ini.

Untuk perubahan settingnya diatur di pengaturan aplikasi kah pak? @eddieridwan

**Comment by eddieridwan** [comment]
@yogiperdana Sebagai aksi saja pada masing2 pamong di Pemerintahan Desa. Jangan tampilkan tombol aksi tsb kecuali mempunyai hak (yaitu admin).

**Comment by yogiperdana** [comment]
Jadi pengguna hanya dapat melihat tombol aksi tersebut ketika di pengaturan absensinya boleh dilaporkan. Apakah seperti itu pak?

**Comment by ariandii** [comment]
setiap aparatur desa akan tampil info kehadiran.

namun bisa dibuat opsi untuk tidak ditampilkan pada masing masing aparatur di menu Pemerintahan Desa.

**Comment by eddieridwan** [comment]
> Jadi pengguna hanya dapat melihat tombol aksi tersebut ketika di pengaturan absensinya boleh dilaporkan. Apakah seperti itu pak?

@yogiperdana , bukan. Yg boleh mengubah hanya Admin. Jadi yg dapat melihat tombol aksi di daftar Pemerintahan Desa tersebut hanya admin.

**Comment by yogiperdana** [comment]
Maksudnya mengubah itu bagaimana ya pak? Kemarin untuk laporan terebut saya buat dilaporkan oleh warga dari layanan mandiri dan admin hanya menambahkan keterangan dari daftar perangkat desa yang telah dilaporkan oleh warga.
Jadi mengubah maksudnya mengubah disini apakah mengubah status dari yang tadinya telah dilaporkan menjadi tidak dilaporkan atau yang melaporkan perangkat hanya admin yang punya dan warga hanya dapat melihat daftar kehadiran

**Comment by eddieridwan** [comment]
@yogiperdana : 
1. Secara default setiap perangkat desa (di Pemerintahan Desa) absensinya dicatat, terlihat dan dilaporkan. Yaitu setiap fitur absensi berlaku bagi perangkat desa tersebut.
2. Disediakan pengaturan supaya admin dapat menyatakan seorang perangkat desa tidak perlu dicatat absensinya. Yaitu bagi perangkat tersebut fitur absensi tidak ada yg berlaku. Sebagai contoh admin dapat membuat seorang Kepala Dusun supaya absensinya tidak aktif. Yaitu Kepala Dusun tersebut kehadirannya tidak dicatat, ditampilkan atau dilaporkan.
3. Pengaturan absensi aktit/tidak aktif itu berupa tombol aksi di setiap baris perangkat desa di Pemerintahan Desa.
4. Hanya admin yg dapat melihat dan menekan tombol absensi aktif/tidak aktif tsb

**Comment by yogiperdana** [comment]
Baik Pak. Nanti akan saya buatkan PR susulannya. Sekalian menambahkan button menuju halaman modul absensi di halaman pengurus
