### ISSUE TITLE
Sediakan form khusus untuk Gawai Rekam Hadir

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#4653]
Form ini untuk verifikasi bahwa gawai yang digunakan adalah yang tercatat sebagai Gawai Rekam Hadir. 

Rancang layout untuk tablet. Gawai Rekam Hadir berupa tablet yg terpasang di dinding di tempat memasuki ruang kantor desa.

- [x] Sediakan pengaturan mencatat mac address dari Gawai Rekam Hadir
- [x] Saat form ditampilkan, minta isi mac address dari gawai yg digunakan.
- [x] Gagal jika isian bukan mac address terdaftar. Jika betul, lanjutkan ke form absensi

**Comment by andifahruddinakas** [comment]
Ambil branch https://github.com/OpenSID/premium/tree/kehadiran-perangkat

**Comment by apidong** [comment]
pak @eddieridwan, untuk gawai rekam hadir ini. apakah dijadikan satu dengan opensid atau terpisah? jika terpisah, framework apa yang akan dipakai?

**Comment by eddieridwan** [comment]
@apidong bagian dari OpenSID. Mengikuti pola seperti untuk Anjungan, di mana ada fitur khusus yang hanya berlaku jika client terdeteksi sebagai Anjungan. Begitu juga dengan gawai Rekam Hadir.
