### ISSUE TITLE
Sediakan form absensi

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#4654]
Rancang form untuk tablet. Gawai Rekam Hadir berupa tablet yg terpasang di dinding di tempat memasuki ruang kantor desa.

Form ini hanya ditampilkan paling cepat dua jam sebelum jam kerja mulai pada hari kerja, dan paling lambat dua jam setelah jam kerja berakhir pada hari kerja.

Perangkat mencatat hadir atau keluar menggunakan:

1. scan eKTP, atau
2. NIK & sandi pengguna, atau
3. nama akun & sandi pengguna

Verifikasi data adalah sandi pengguna & perangkat desa yg valid. Bandingkan dengan tag_id_card di `tweb_penduduk` bagi perangkat dari penduduk desa, dan tag_id_card di `tweb_desa_pamong` bagi perangkat dari luar desa. Nama akun dan sandi pengguna sesuai dengan akun pengguna yg terkait dengan perangkat yang valid.

Jika sukses verifikasi perangkat, aktifkan tombol Hadir atau Keluar. Aktifkan tombol Hadir jika perangkat tercatat sebagai keluar. Aktifkan tombol Keluar jika perangkat tercatat sebagai hadir.

Jika menekan tombol Hadir, catat perangkat sebagai hadir. Rekam jam dan waktunya.

Perangkat dapat lapor keluar/masuk lebih dari satu kali dalam satu hari. 

Jika menekan tombol Keluar, catat perangkat sebagai keluar. Rekam jam dan waktunya.

**Comment by andifahruddinakas** [comment]
Ambil branch https://github.com/OpenSID/premium/tree/kehadiran-perangkat

**Comment by ekozer03** [comment]
lebih keren lagi seandainya absensi kantor desa pake sidik jari, wuihhh...
atau lewat apliasi web nya langsung tapi pakai jaringan lokal yang ada disana pak, jadi mereka harus konek ke wifi kantor desa dulu.:)

**Comment by andifahruddinakas** [comment]
@apidong, untuk login ektp buat di PR yg berbeda.

**Comment by apidong** [comment]
siap.
