### ISSUE TITLE
Sediakan fitur jam kerja

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#4655]
Form untuk menentukan jam kerja standar setiap hari Senin-Minggu.

Juga tanggalan untuk menentukan hari libur. 

Sediakan method untuk bisa periksa apakah tgl/jam tertentu adalah jam kerja atau tidak.

**Comment by andifahruddinakas** [comment]
Ambil branch https://github.com/OpenSID/premium/tree/kehadiran-perangkat
