### ISSUE TITLE
Cron job untuk menyatakan semua perangkat keluar

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#4656]
Pada dua jam setelah jam kerja berakhir pada hari kerja, jalankan cron job untuk menandai semua perangkat yang masih hadir sebagai sudah keluar, dengan status `lupa melapor keluar`.

**Comment by andifahruddinakas** [comment]
Ambil branch https://github.com/OpenSID/premium/tree/kehadiran-perangkat

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/852
