### ISSUE TITLE
Laporkan perangkat absen tanpa diketahui

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#4658]
Di Layanan Mandiri, warga dapat melaporkan perangkat desa yg terlihat hadir tetapi ternyata diketahui tidak ada di kantor desa. 

Yaitu di Layanan Mandiri perangkat ybs tampil sebagai hadir di kantor desa, tetapi pada waktu dihubungi ternyata tidak ada. Warga dihimbau untuk melaporkan perangkat desa tersebut, dengan menandai perangkat desa tersebut sebagai absen tanpa diketahui. Identitas warga yg melapor juga dicatat. 

Laporan tidak-hadir ini dapat dikirim oleh lebih dari satu warga bagi perangkat desa yg sama. Hanya satu laporan yg tercatat setiap hari bagi satu warga pada perangkat desa yg sama.

**Comment by rudiansyahyunanda** [comment]
Sediakan Barcode Scan Kehadiran Perangkat desa seperti check point **peduli lindungi** yang memiliki zona (radius) yang dapat melakukan cek kehadiran.

**Comment by andifahruddinakas** [comment]
Ambil branch https://github.com/OpenSID/premium/tree/kehadiran-perangkat
