### ISSUE TITLE
Beri catatan pada laporan absen tanpa diketahui

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#4659]
Laporan dari warga terkait kehadiran perangkat desa yg absen tanpa diketahui dapat diberi catatan oleh petugas pengawas kantor desa. Misalnya, petugas yg berwenang tersebut dapat memberi penjelasan terkait ketidak hadiran seorang perangkat desa.

**Comment by andifahruddinakas** [comment]
Ambil branch https://github.com/OpenSID/premium/tree/kehadiran-perangkat
