### ISSUE TITLE
Bug/error: jQuery di panggil 2 kali

### ISSUE THREAD

**Issue by totoprayogo1916** [OpenSID/OpenSID#4661]
### Jelaskan error yg dialami

berkas jQuery ataupun assets lainnya mestinya cukup dipanggil sekali saja.
ini duplikat pada
https://github.com/OpenSID/OpenSID/blob/51180672afb31cf6a1c021c281049c5b05a911c7/donjo-app/views/layanan_mandiri/template.php#L88-L89

https://github.com/OpenSID/OpenSID/blob/51180672afb31cf6a1c021c281049c5b05a911c7/donjo-app/views/layanan_mandiri/template.php#L278-L279

### Cara untuk mereplikasi errornya

buka halaman layanan-mandiri

### Hasil yg diharapkan

hanya 1 saja tiap assets yang diload

### Tangkapan layar dan log error

-

### Versi OpenSID

*

**Comment by FirlianiF** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/558
