### ISSUE TITLE
[Kependudukan] Wajib Identitas menyesuaikan umur dan status perkawinan

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/OpenSID#4664]
### Jelaskan error yg dialami

Status Wajib identitas pada saat input umur yang lebih dari 16 tahun dan status perkawinan.

### Cara untuk mereplikasi errornya

1. Pada Halaman Admin Klik Kependudukan
2. Pilih Penduduk
3. Tambah Penduduk
4. Pada Status Kepemilikan Identitas Jika Umur Melebihi 16 tahun dan Status Perkawinan Selain Belum Kawin maka Wajib Identitas statusnya menjadi Wajib

### Versi OpenSID

v22.01-premium

**Comment by eddieridwan** [comment]
@FirlianiF 

Yg wajib KTP adalah orang yg:

- sdh berumur 17 tahun ke atas; atau
- sdh menikah (yaitu status nikah bukan 'belum nikah'

ref: https://dukcapil.kulonprogokab.go.id/detil/164/mengapa-harus-memiliki-ktp-elektronik-ktp-el

Issue ini tidak jelas apa masalahnya. Perlu tanyakan bung @scqolbu24 siapa yg melaporkan untuk mendapatkan penjelasan.

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melalui pr https://github.com/OpenSID/premium/pull/597
