### ISSUE TITLE
[Layanan Mandiri] Erorr pada saat verifikasi telegram dengan akun yang sama (Duplicate entry)

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/OpenSID#4668]
### Jelaskan error yg dialami

Pada saat verifikasi telegram jika akun yang digunakan sudah terdaftar akan terjadi error 500 : duplicate entry

### Cara untuk mereplikasi errornya

1. Login di Layanan Mandiri
2. Klik Tombol Verifikasi
3. Pada Langkah 2 Kirim user ID dengan akun telegram yang sudah terdaftar

### Hasil yg diharapkan

Muncul Pesan bahwa akun Telegram yang dimasukkan sudah terdaftar

### Tangkapan layar dan log error

<img width="357" alt="bug-telegram" src="https://user-images.githubusercontent.com/68048807/147912568-6d1a5c7a-ba8d-4b21-8dc4-91f3f906c7f3.PNG">

### Versi OpenSID

v22.01-premium

**Comment by agungsugiarto** [comment]
sudah diperbaiki melalui pr https://github.com/OpenSID/premium/pull/560
