### ISSUE TITLE
[User] Verifikasi akun email 

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#4669]
### Apa kekurangan yg ingin diatasi?

Akun Email pengguna admin perlu diverifikasi supaya dapat digunakan sebagai pengganti bukti identitas.

### Jelaskan solusi yg diinginkan

Setelah login admin, di form profil pengguna:

- [ ] Tampilkan email pengguna
- [ ] Jika email pengguna belum diverifikasi, sediakan tombol untuk verifikasi akun Email. Sistem akan mengirim kode berbatas waktu ke akun Email tersebut
- [ ] Tampilkan form untuk mengisi kode yg dikirim tersebut
- [ ] Jika kode valid, ubah status akun Email dari belum diverifikasi menjadi sudah diverifikasi
- [ ] Catat tanggal verifikasi

Jika kode sudah kadaluarsa, verifikasi akan gagal.

### Apakah ada alternatif lain

Tidak ada

### Untuk versi OpenSID mana

pasca v22.01-premium

### Informasi tambahan

Serupa dengan https://github.com/OpenSID/OpenSID/issues/4612 untuk verifikasi email pendaftar Layanan Mandiri.

**Comment by agungsugiarto** [comment]
Sudah masuk di rilis premium melalui pr https://github.com/OpenSID/premium/pull/617
