### ISSUE TITLE
[User] Lupa/reset password

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#4670]
### Apa kekurangan yg ingin diatasi?

Saat ini jika pengguna lupa password, perlu meminta diganti melalui administrator. Sebaiknya bisa mengubah sendiri.

### Jelaskan solusi yg diinginkan

Sediakan fitur `Lupa Password` di halaman login Admin.

- [ ] Sediakan tautan `Lupa Password` di halaman Login Admin
- [ ] Setelah diklik, tampilkan form isian email pengguna, dengan penjelasan fitur ini hanya tersedia bagi pengguna yg akun email telah diverifikasi. 
- [ ] Di form itu sediakan tombol Reset Password. Setelah tombol itu diklik, tampilkan pesan bahwa jika email yg diisi adalah pengguna yg akun email telah diverifikasi, maka notifikasi reset password baru akan dikirim ke email tsb
- [ ] Jika email bukan pengguna atau email belum diverifikasi, tidak lakukan apa-apa. Pengguna `tidak` diberitahu perihal kegagalan ini (supaya fitur ini tidak digunakan utk menebak email valid).
- [ ] Jika email adalah pengguna, dan email telah diverifikasi, kirim notifikasi reset password baru ke email tersebut
- [ ] Di notifikasi, sediakan tautan dengan token berbatas waktu, untuk membuat password baru.
- [ ] Setelah tautan diklik, buka form untuk mengisi password baru dan konfirmasi ulang password baru tsb. Jika token sudah kadaluarsa, form tidak dibuka. Beritahu pengguna untuk mengulangi proses.
- [ ] Jika password memenuhi kriteria keamanan, simpan sebagai password baru pengguna tersebut dan otomatis login.

### Apakah ada alternatif lain

Tidak ada

### Untuk versi OpenSID mana

pasca v22.01-premium

### Informasi tambahan

Reset password yg standar.

**Comment by agungsugiarto** [comment]
Pak @eddieridwan baik issue ini maupun https://github.com/OpenSID/OpenSID/issues/4669 apakah hanya di khususkan untuk email saja ?

**Comment by eddieridwan** [comment]
Ya. Kalau tidak salah, ada issue terpisah untuk menggunakan Telegram untuk hal yg sama. Pada prakteknya, pengguna bisa menentukan pilihan cara hubung yg diutamakan. Seperti dijelaskan di issue yg lain, urutan pemilihan cara hubung sbb:
1. default adalah Telegram
2. kalau ada pilihan dan pilihan telah diverifkasi gunakan pilihan itu
3. kalau tidak ada pilihan, dan Telegram belum diverifikasi, gunakan cara hubung lain yg telah diverifikasi (seperti email).

**Comment by agungsugiarto** [comment]
Untuk pengguna sekarang hanya email pak @eddieridwan, belum ada untuk telegram
