### ISSUE TITLE
Bug/error: Masuk sebagai Operator hanya beberapa menu yang tampil di dasbord

### ISSUE THREAD

**Issue by ahmadngudi** [OpenSID/OpenSID#4673]
### Jelaskan error yg dialami

Jelaskan error yg dialami

### Cara untuk mereplikasi errornya

Cara untuk mereplikasi errornya

### Hasil yg diharapkan

Hasil yg diharapkan

### Tangkapan layar dan log error

![Screenshot_61](https://user-images.githubusercontent.com/57133748/147993546-66d4d8cb-808f-4619-8561-b4b23527e1df.png)
Tampilan Operator

![Screenshot_65](https://user-images.githubusercontent.com/57133748/148001653-dfe7091a-8fa2-4324-a65c-5f65fbb4ad57.png)
Tampilan Redaksi

![Screenshot_64](https://user-images.githubusercontent.com/57133748/148001673-7acddf8d-403a-4147-9184-4f241f20013c.png)
Tampilan Kontributor

![Screenshot_63](https://user-images.githubusercontent.com/57133748/148001706-3d9b49b3-79b5-44be-a80a-6aa90ac8a005.png)
Tampilan Satgas Covid

### Versi OpenSID

Premium 22.01

### Tema Yang Digunakan

Tema Yg Digunakan

### Informasi tambahan

Informasi tambahan

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melalui pr https://github.com/OpenSID/premium/pull/563
