### ISSUE TITLE
[Layanan Mandiri] Jangan tampilkan pesan NIK tidak ditemukan

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#4674]
### Jelaskan error yg dialami

Saat ini pada fitur Lupa Pin, jika NIK tidak ditemukan ditampilkan pesan di bawah. Ini merupakan celah privasi data. Lihat penjelasan di issue https://github.com/OpenSID/OpenSID/issues/4557

![image](https://user-images.githubusercontent.com/249563/148000429-3204cb9b-58c2-4faa-9003-d5e8ff85bd5b.png)

### Cara untuk mereplikasi errornya

Lihat gambar di atas

### Hasil yg diharapkan

Bisa kirim pesan alternatif: 

'NIK atau akun Telegram anda tidak valid. Fitur Lupa PIN hanya berlaku jika akun Telegram anda telah diverifikasi. Hubungi operator desa' 

atau serupa yg tidak memberi informasi keabsahan NIK secara langsung. 

### Tangkapan layar dan log error

Lihat di atas

### Versi OpenSID

v22.01-premium

**Comment by eddieridwan** [comment]
@scqolbu24 , saya telah pelajari contoh yg lain. Mohon pesan diubah, yg berlaku pada kasus gagal maupun berhasil sama saja. Dengan cara ini, privasi data aman, dan juga diberi penjelasan langkah jika gagal. 

Pesan sebagai berikut:

> Informasi reset PIN telah dikirim ke akun Telegram anda. Jika anda tidak menerima pesan itu, periksa ulang NIK yang diisi dan pastikan akun Telegram anda di OpenSID telah diverifikasi. Silakan hubungi Operator Desa untuk penjelasan lebih lanjut.

Juga sebaiknya batasi klik Lupa Pin paling banyak 3 kali berturut-turut. Sesudah itu dikunci selama x menit. Ikuti aturan di login Layanan Mandiri. 

Di notifikasi yg dikirim ke Telegram, juga tambahkan peringatan, bahwa jika warga ybs tidak meminta reset PIN, maka segera laporkan kepada Operator Desa.

**Comment by scqolbu24** [comment]
sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/562
