### ISSUE TITLE
Bug/error: List Pamong Tidak Muncul Saat Cetak Laporan Hasil Klasifikasi Analisis

### ISSUE THREAD

**Issue by wahyabiantara** [OpenSID/OpenSID#4675]
### Jelaskan error yg dialami

Tidak bisa mencetak hasil analisis per penduduk/kepala keluarga pada menu **Laporan Hasil Klasifikasi** jika sebelumnya dilakukan pencarian data penduduk yang ingin dicetak karena data Pamong penandatangan tidak muncul

### Cara untuk mereplikasi errornya

1. Klik Menu Analisis > Master Analisis
2. Klik menu Laporan Hasil Klasifikasi
3. Search salah satu nama penduduk yang ingin dilihat hasil analisis yang sudah didata
4. Klik hamburger menu untuk melihat hasil detail per penduduk / kepala keluarga
5. Klik tombol cetak / unduh
6. Pada saat Popup pemilihan pamong yang akan tanda tangan, list nama pamong tidak muncul sehingga tidak dapat diproses

### Hasil yg diharapkan

Nama pamong seharusnya muncul saat mencetak hasil detail analisis, meskipun dilakukan melalui pencarian nama penduduk.

### Tangkapan layar dan log error

<img width="1226" alt="Screen Shot 2022-01-04 at 11 44 05" src="https://user-images.githubusercontent.com/4361979/148006876-f04cd8f0-4b07-4b5d-8909-3247a971d140.png">

### Versi OpenSID

V21.12

### Tema Yang Digunakan

Classic

### Informasi tambahan

Solusi, tambahkan unset session pada Controllers/Analisis_laporan.php pada baris 158. Script yang saya tambahkan adalah sebagai berikut:

`$this->session->unset_userdata('cari');`

**Comment by Nurhidayat29** [comment]
apakah sudah coba di demo?
saya lihat tidak ditemukan error tersebut

**Comment by scqolbu24** [comment]
sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/574
