### ISSUE TITLE
Bug/error: Penduduk Mati Masih Muncul Pada data Rumah Tangga

### ISSUE THREAD

**Issue by wahyabiantara** [OpenSID/OpenSID#4676]
### Jelaskan error yg dialami

Jika status dasar penduduk diganti menjadi Mati, pada data Kepala Keluarga data penduduk tersebut sudah secara otomatis tidak muncul saat dilihat pada Kartu Keluarga. Namun, pada data Rumah Tangga, data penduduk tersebut masih muncul

### Cara untuk mereplikasi errornya

1. Klik menu Penduduk dan Ubah salah satu status dasar penduduk menjadi Mati
2. Klik menu Rumah Tangga, lalu cari nama Kepala Rumah Tangga yang bersangkutan
3. Klik Hamberger menu untuk melihat Kartu Rumah Tangga
4. Data penduduk dengan status Mati masih muncul pada Kartu Rumah Tangga.

### Hasil yg diharapkan

Data Penduduk Mati seharusnya tidak muncul pada Kartu Rumah Tangga begitu juga jumlah Anggota Rumah Tangga seharusnya ikut berkurang.

### Tangkapan layar dan log error

![rumah-tangga-landeri](https://user-images.githubusercontent.com/4361979/148008671-649984d0-a001-4dfe-9106-bd66ac8fc933.png)
![detail-rumah-tangga-landeri](https://user-images.githubusercontent.com/4361979/148008672-fd7cf2f1-150b-422c-8259-1241ac7f9e85.png)

### Versi OpenSID

v21.12

### Tema Yang Digunakan

Classic

**Comment by scqolbu24** [comment]
sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/577
