### ISSUE TITLE
Bug/error: Pada Update Hubungan Rumah Tangga 

### ISSUE THREAD

**Issue by wahyabiantara** [OpenSID/OpenSID#4677]
### Jelaskan error yg dialami

Saat melakukan update Hubungan Rumah Tangga dari Anggota menjadi Kepala Rumah Tangga, tabel `tweb_rtm` pada kolom `nik_kepala` tidak berubah, sehingga informasi Kepala Rumah Tangga yang muncul masih Kepala Rumah Tangga yang lama pada data Rumah Tangga.

Permasalahan menjadi sedikit kompleks ketika Kepala Rumah Tangga tersebut status dasar sudah Mati.

### Cara untuk mereplikasi errornya

1. Ganti status dasar di penduduk menjadi Mati dimana Penduduk tersebut sebelumnya adalah Kepala Rumah Tangga
2. Lalu ke menu Rumah Tangga dan jadikan Anggota yang lain sebagai Kepala Rumah Tangga

### Hasil yg diharapkan

Saat mengganti Hubungan Keluarga menjadi Kepala Rumah Tangga, kolom nik_kepala pada tabel tweb_rtm juga seharusnya berubah

### Tangkapan layar dan log error

![update_anggota_rtm](https://user-images.githubusercontent.com/4361979/148032020-c7be2eb8-a0b5-4984-b963-af695cf2cb87.png)

### Versi OpenSID

v21.12

**Comment by andifahruddinakas** [comment]
Silahkan cek dan duplikasi di https://berputar.opensid.or.id/, sy coba melakukan hal yang sama tp tdk bisa di duplikasi. Yang sy temukan adalah data rtm tetap muncul walau penduduk tsb sudah meninggal sesuai issue https://github.com/OpenSID/OpenSID/issues/4676.

Bisa di cek ulang @scqolbu24
