### ISSUE TITLE
Permintaan fitur: Integrasikan aplikasi stunting

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#4680]
### Apa kekurangan yg ingin diatasi?

Anggota komunitas telah membuat aplikasi stunting yg dibagikan kepada pengguna lain. Aplikasi stunting ini berdiri sendiri dan belum terintegrasi dengan OpenSID.

### Jelaskan solusi yg diinginkan

Integrasikan aplikasi stunting karya anggota komunitas dengan OpenSID. Aplikasi itu ada di https://github.com/OpenSID/stunting. 

Gabungkan aplikasi itu ke dalam OpenSID (https://github.com/OpenSID/OpenSID) sebagai berikut:

1. Ubah judul menu yg ada seperti di gambar berikut. Tambahkan Stunting sebagai menu di bawah Kesehatan. 
![image](https://user-images.githubusercontent.com/249563/148921063-ad58ae72-a79b-4dff-a6d8-01df3abb0584.png)
2. Hanya gabung script di bawah folder `applications` yg relevan, seperti script di folder2 controllers, helpers, libraries dan models yg diperlukan saja.
3. Tambahkan package yg diperlukan melallui composer, sehingga ditambahkan ke folder `vendor` secara otomatis oleh composer.
4. Masukkan controller stunting di bawah folder tersendiri supaya tidak bentrok dengan controller yg sdh ada di OpenSID.
5. Jangan gabungkan login atau otentikasi stunting, atau fitur lain yg sudah ada di OpenSID.
6. Sesuaikan view dengan layout yg sudah ada di OpenSID.
7. Integrasikan data penduduk di stunting dengan yg di OpenSID. Yaitu, ambil data penduduk yg sudah ada dari OpenSID. Data tambahan yg diperlukan utnuk stunting dibiarkan di tabel terpisah, tapi direlasikan dengan data penduduk yg ada di OpenSID. 
8. Gunakan tingkat pengguna yg ada di OpenSID

### Untuk versi OpenSID mana

pasca v22.01-premium

### Informasi tambahan
Perhatikan bahwa aplikasi Stunting itu menggunakan view gaya blade seperti di Laravel. Pertahankan cara itu. Dan jika perlu menambah view untuk aplikasi yg terintegrasi dengan OpenSID, juga gunakan blade templating.

**Comment by Zoel-WB** [comment]
Pandangan saya lebih cocok diserap dalam OpenSID bisa melebih meringankan beban hosting disatu sisi, dan memudahkan admin utk mengontrol system.

Mungkin login akun saja yg dipisahkan khusus untuk posyandu dan stunting dibuat user tersendiri, fitur keduanya dapat disatukan dalam satu user, baik posyandu maupun stunting keduanya dibawah koordinasi satu KPM walaupun anggaran operasionalnya terpisah.

Dapatkan Outlook untuk Android<https://aka.ms/AAb9ysg>
________________________________
From: Eddie Ridwan ***@***.***>
Sent: Wednesday, January 5, 2022 8:43:12 AM
To: OpenSID/OpenSID ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [OpenSID/OpenSID] Permintaan fitur: Integrasikan aplikasi stunting (Issue #4680)


Apa kekurangan yg ingin diatasi?

Anggota komunitas telah membuat aplikasi stunting yg dibagikan kepada pengguna lain. Aplikasi stunting ini berdiri sendiri dan belum terintegrasi dengan OpenSID.

Jelaskan solusi yg diinginkan

Integrasikan aplikasi stunting karya anggota komunitas dengan OpenSID.

Apakah ada alternatif lain

Perlu ditinjau, apakah:

  1.  aplikasi stunting sepenuhnya diserap ke dalam OpenSID; atau
  2.  aplikasi stunting tetapi terpisah, dan terintegrasi melalui database saja.

Untuk versi OpenSID mana

pasca v22.01-premium

Informasi tambahan

No response

**Comment by Zoel-WB** [comment]
cc: Pak @eddieridwan 
1. source code origina : konvergensi-stunting-master.zip
2. source code revisi : Stunting.zip

Login untuk Stunting.zip
Login Admin :  admin@mail.com, password : 85102947
Login User  :  user@mail.com, password : 85102947
Google Drive : https://drive.google.com/drive/folders/1Xk_xepTGl2cz5Jmuj7A0DoGqG7nVOjnr?usp=sharing

**Comment by eddieridwan** [comment]
@Zoel-WB , yang asli diperoleh dari mana? Ada url githubnya?

**Comment by Zoel-WB** [comment]
> @Zoel-WB , yang asli diperoleh dari mana? Ada url githubnya?

Ada Pak @eddieridwan ini alamat reponya : https://github.com/raflyfirdausy/konvergensi-stunting

**Comment by eddieridwan** [comment]
Bung @Zoel-WB , saya lihat aplikasi stunting ini CI 3.1.8, bukan Laravel? Betul?

**Comment by Zoel-WB** [comment]
> Bung @Zoel-WB , saya lihat aplikasi stunting ini CI 3.1.8, bukan Laravel? Betul?

Benar Pak @eddieridwan Stunting itu memang CI.3 pak

**Comment by andifahruddinakas** [comment]
Gunakan https://github.com/EFTEC/BladeOne

**Comment by gampongbarabung** [comment]
Semoga cepat terintegrasi

**Comment by Zoel-WB** [comment]
https://forum.opendesa.id/d/129-integrasi-modul-stunting-akan-rilis-v2205-premium

**Comment by agungsugiarto** [comment]
Sudah dikerjakan melalui pr https://github.com/OpenSID/premium/pull/1088
