### ISSUE TITLE
Ubah daftar kontak dikhususkan kontak eksternal (tidak ada di daftar penduduk)

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#4681]

**Comment by eddieridwan** [comment]
![image](https://user-images.githubusercontent.com/249563/148161450-99a86706-ed85-4fec-9d25-4afd84688ea5.png)

Cara hubung pilihan adalah salah satu dari: sms, email, akun Telegram. Default adalah Telegram. Pilihan SMS hanya berlaku jika pengaturan SMS aktif.

Sesuaikan tabel `kontak`.

![image](https://user-images.githubusercontent.com/249563/148161587-bfa05736-c5c4-4b3c-abe8-702aeda49bf7.png)

**Comment by agungsugiarto** [comment]
Sudah di branch hubung warga melalui pr https://github.com/OpenSID/premium/pull/935
