### ISSUE TITLE
Pengaturan untuk menonaktifkan sms

### ISSUE THREAD

**Issue by agungsugiarto** [OpenSID/OpenSID#4689]

**Comment by FirlianiF** [comment]
mas @agungsugiarto boleh tolong dijelaskan Pengaturan untuk menonaktifkan sms itu seperti apa detail nya?

**Comment by agungsugiarto** [comment]
> mas @agungsugiarto boleh tolong dijelaskan Pengaturan untuk menonaktifkan sms itu seperti apa detail nya?

Kalau tidak salah ingat, modul sms dibuat pengaturan kemudian bisa di aktifkan / non aktifkan
