### ISSUE TITLE
Permintaan fitur: Izinkan penggunaan Huruf dalam Klasifikasi Surat

### ISSUE THREAD

**Issue by rullydamara** [OpenSID/OpenSID#4690]
### Apa kekurangan yg ingin diatasi?

pada klasifikasi surat hanya bisa diisi oleh angka dan titik, namun untuk di kabupaten saya ada format klasifikasi yang berbeda dan menggunakan kombinasi huruf.angka.angka.

misalkan pada gambar dibawah ini
![Screenshot (318)](https://user-images.githubusercontent.com/45301948/148324571-86a65087-9de8-4a0c-8abf-4f47e823fb9a.png)

tidak bisa input
![Screenshot (317)](https://user-images.githubusercontent.com/45301948/148324594-150adab9-1583-4885-8c7a-be491831e267.png)

### Jelaskan solusi yg diinginkan

dapat menginput huruf pada klasifikasi surat

### Apakah ada alternatif lain

dapat menginput huruf pada klasifikasi surat

### Untuk versi OpenSID mana

v.22.01

**Comment by scqolbu24** [comment]
sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/575
