### ISSUE TITLE
Permintaan fitur:  Tampikan informasi publik pada halaman anjungan

### ISSUE THREAD

**Issue by ai-skematik** [OpenSID/OpenSID#4691]
### Apa kekurangan yg ingin diatasi?

Saat ini halaman anjungan hanya berisi form login layanan mandiri sehingga perlu penambahan fungsi seperti dapat menampilkan informasi publik (keuangan, berita desa dan data statistik desa)

### Jelaskan solusi yg diinginkan

Pada halaman anjungan selain form login layanan mandiri juga dapat menampilkan informasi publik (keuangan, berita desa dan data statistik desa)

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

v22.02 premium

### Informasi tambahan

-

**Comment by balongbesuk** [comment]
gak sekalian website desa d tampilkan d anjungan 😄

**Comment by ai-skematik** [comment]
biar ada pembeda antara tampilan anjungan dan website.

**Comment by eddieridwan** [comment]
@ai-skematik apakah issue ini sudah tercakup dalam pembuatan tema anjungan?

**Comment by yogiperdana** [comment]
Issue ini ditutup karena sudah tercakup ke dalam tema
