### ISSUE TITLE
Bug/error: Pencarian dan pengurutan di modul buku kader tidak berjalan

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#4700]
### Jelaskan error yg dialami

Terjadi error saat melakukan pencarian atau pengurutan.

### Cara untuk mereplikasi errornya

buka modul buku kader dan lakukan pencarian/pengurutan data

### Hasil yg diharapkan

tidak terjadi error

### Tangkapan layar dan log error

![anu](https://user-images.githubusercontent.com/57283157/148648893-dd0c6504-76f3-474a-a8a3-188b796ef4b2.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.01

### Tema Yang Digunakan

bawaan

### Informasi tambahan

bisa cek ulang

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melalui pr https://github.com/OpenSID/premium/pull/570
