### ISSUE TITLE
Bug/error: Pesan Masuk, Balas Pesan dan Pesan Keluar Layanan Mandiri

### ISSUE THREAD

**Issue by langonsari** [OpenSID/OpenSID#4701]
### Jelaskan error yg dialami

Error Pengriman Pesan, Balasan, Pesan Keluar dari Layanan Mandiri dikarenakan Duplicate entry '0' for key 'PRIMARY'

### Cara untuk mereplikasi errornya

dihalaman Layanan Mandiri Kotak Masuk ataupun Kotk Keluar,
Cek database komentar 'id' 0 

### Hasil yg diharapkan

Perbaikan dalam Pengecekan 'id' Komentar

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/96863107/148675129-3336880f-e3a7-4c2e-b59b-e261ef8870bc.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

22.01-premium-rev01

### Tema Yang Digunakan

Natra

**Comment by Nurhidayat29** [comment]
saya coba di (https://berputar.opensid.or.id/layanan-mandiri/) tidak menemukan bug tersebut

**Comment by andifahruddinakas** [comment]
Silahkan perbaiki struktur database anda, itu krn primary key di kolom id terhapus.
