### ISSUE TITLE
Bug/error: Audio di layanan mandiri login tidak bersuara

### ISSUE THREAD

**Issue by WAHYUDIK** [OpenSID/OpenSID#4702]
### Jelaskan error yg dialami

setelah mencoba menambahkan video di pengaturan layanan mandiri, sukses menampilkan videonya akan tetapi audio pada video tidak bersuara.

### Cara untuk mereplikasi errornya

pergi ke halaman menu Layanan Mandiri>Pengaturan>
![image](https://user-images.githubusercontent.com/31026980/148678376-0c04deee-f766-4e7e-9281-55dd484ef53e.png)

### Hasil yg diharapkan

di login layanan mandiri tidak hanya menampilkan video, audio dari videonya juga bisa berbunyi,

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/31026980/148678271-17eef361-f1fb-4753-901c-1e52fd3c2605.png)

Contoh Link login layanan mandiri
https://kesambirampak.desa.id/layanan-mandiri/masuk-ektp
tidak ada eror dilog

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

22 01 Rev1

### Tema Yang Digunakan

denatra

### Informasi tambahan

contoh script yang dari bung @ariandii 
 
![image](https://user-images.githubusercontent.com/31026980/148678474-b1eae781-516e-46cd-9af4-0d26947d7b98.png)

**Comment by andifahruddinakas** [comment]
@FirlianiF, tambahkan pengaturan aktifkan sura jika pilihannya adalah video.

**Comment by andifahruddinakas** [comment]
https://github.com/OpenSID/premium/pull/598
