### ISSUE TITLE
Bug/error: Error impor database awal 

### ISSUE THREAD

**Issue by agungsugiarto** [OpenSID/OpenSID#4704]
### Jelaskan error yg dialami

Terjadi error migrasi database awal

### Cara untuk mereplikasi errornya

impor database contoh

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.01-rev01

**Comment by Zoel-WB** [comment]
Iya benar Pak, kmaren pernah terjadi juga pada salah satu pelamggan baru premium, saat mengimport database awal dari database bawaan system premium v22.01 Rev01, kemudian terakhir saya arahkan untuk menggunakan dari data contoh bawaan database Premium V21.12 Rev03 baru berhasil.

**Comment by helmibaguswara** [comment]
Ada kesalahan dalam pemasangan OpenSID
Aplikasi tidak bisa terhubung ke database.
Silakan salin/tempel folder desa-contoh sebagai folder desa dan periksa isi berkas desa/config/database.php.

**Comment by Zoel-WB** [comment]
> Ada kesalahan dalam pemasangan OpenSID Aplikasi tidak bisa terhubung ke database. Silakan salin/tempel folder desa-contoh sebagai folder desa dan periksa isi berkas desa/config/database.php.

Ada migrasi tak berjalan pada query "column suku" pada table tweb_penduduk untuk contoh_data_awal premium 22.01

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melalui pr https://github.com/OpenSID/premium/pull/594
