### ISSUE TITLE
Menu Cetak laporan vaksin belum normal

### ISSUE THREAD

**Issue by muhtar-coder** [OpenSID/OpenSID#4705]
### Jelaskan error yg dialami

Ketika kita mencetak laporan penduduk di menu vaksin, data yg tampil dan tercetak hanya sejumlah pada halaman tersebut,pada tabel filter jumlah hanya tersedia maksimal 200 data yang ditampilkan.

### Cara untuk mereplikasi errornya

Masuk menu covid-19 >> menu vaksin >> daftar penerima kemudian ubah kolom tampilkan menjadi yg terbanyak misal 200 >> masuk ke laporan penduduk/vaksin >> cetak.

Hasil cetak: hanya bisa cetak sejumlah tersebut sedangkan data yg ter input lebih dari 200 dan tidak bisa tercetak.

### Hasil yg diharapkan

1.
Bisa cetak semua data laporan penduduk di menu vaksin sesuai jumlah yang ada atau untuk lebih baiknya bisa juga di filter berdasar alamat, dll

2.
Bisa disediakan sensor nik di menu cetak tersebut untuk kebutuhan laporan dan memungkinkan di masukan ke google drive guna informasi terkait partisipasi vaksinasi

### Tangkapan layar dan log error

![Screenshot_20220110-174714_Chrome](https://user-images.githubusercontent.com/55665526/148753984-8cbbb198-d59f-4760-9324-64bead24c89e.png)

![Screenshot_20220110-174831_Chrome](https://user-images.githubusercontent.com/55665526/148754015-a45aa6d0-76a9-496c-9371-5bd730d23200.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

22.01 rev.01

### Tema Yang Digunakan

Default

**Comment by Zoel-WB** [comment]
Pada berputar pada Fitur "Laporan Penduduk" saat memilih Cetak-->Data yang tampil dihasil cetak 50 Data, apakah memang ada filter tertentu mungkin batas usia yg telah ditentukan.

Atau bila mungkin menambah pilihan Filter Umur....

Hasil Test, dari Website Berputar, memilih Fitur Laporan Penduduk dari jumlah data 97 Data, saat di pilih cetak yg tampil hanya 50 data saja.
![image](https://user-images.githubusercontent.com/64481641/148765591-1d801269-974e-4320-b9ee-357d43d48ef1.png)

![image](https://user-images.githubusercontent.com/64481641/148765617-07e280fd-d835-4cb7-b080-56a5a8443ac1.png)
![image](https://user-images.githubusercontent.com/64481641/148765644-d8e6b161-69a1-479f-8772-fb204e8e7209.png)

**Comment by Zoel-WB** [comment]
Juga pada Pilihan Unduh data, data yg ter-unduh juga 50 data, sedangkan data-nya 97 data
Screensote Hasil Unduh Data
![image](https://user-images.githubusercontent.com/64481641/148765963-0ffed624-dee2-4b87-806b-7e62c311c599.png)

**Comment by Zoel-WB** [comment]
Barusan juga telah saya coba input 3 data, satu data untuk vaksin dosis satu,  satu data vaksin dosis 2, satu data vakasin dosis 3

Tampilan di Layar pada fitur Rekap
 
![image](https://user-images.githubusercontent.com/64481641/148768098-b3e76480-b2a8-4e2e-940b-9edfa5891517.png)

Harusnya tampil-nya seperti berikut :
![image](https://user-images.githubusercontent.com/64481641/148768199-77359806-443d-4b1a-b49d-77c848c1dcde.png)

**Comment by andifahruddinakas** [comment]
Terima kasih pak Zoel, issue ini saya tutup karena sudah diperbaiki melalui 

pr: https://github.com/OpenSID/premium/pull/564, https://github.com/OpenSID/premium/pull/569
issue: https://github.com/OpenSID/OpenSID/issues/4641
