### ISSUE TITLE
Permintaan fitur: Notifikasi Pengaduan

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#4706]
### Apa kekurangan yg ingin diatasi?

Belum adanya pemberitahuan jika terdapat Pengaduan Baru dari warga atau non warga melalui Halaman Pengaduan di website desa.

### Jelaskan solusi yg diinginkan

Tersedianya notifikasi ke operator desa maupun ke group Pemerintah Desa melalui Telegram, Email, atau lainnya agar jika ada Aduan Baru dapat segera ditindaklanjuti secara langsung.

### Apakah ada alternatif lain

Tidak ada alternatif lain.

### Untuk versi OpenSID mana

v22.02-premium

### Informasi tambahan

Usul agar masuk prioritas.

**Comment by emanuel-simon** [comment]
setuju dengan issue ini, 
dibuat seperti pemberitahuan bot Telegram setiap ada yang log in di siteman
