### ISSUE TITLE
Permintaan fitur: Captcha untuk form Pengaduan

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#4707]
### Apa kekurangan yg ingin diatasi?

Belum adanya captcha pada saat ajukan Pengaduan pada halaman website.

### Jelaskan solusi yg diinginkan

Tersedia captcha, untuk menghindari span atau bom pengaduan.

### Apakah ada alternatif lain

Selain captcha, bisa ditambah batas aduan dalam 1 waktu, juga untuk menghindari bom aduan.

Misal 1 pengunjung hanya bisa 1 aduan atau 2 aduan saja. 

### Untuk versi OpenSID mana

v22.02-premium

### Informasi tambahan

Agar dapat masuk prioritas sebelum fitur aduan dikenal masyarakat luas.

**Comment by andifahruddinakas** [comment]
Sudah digabung melalui PR https://github.com/OpenSID/premium/pull/711
