### ISSUE TITLE
Permintaan fitur : Optimalisasi kecepatan website

### ISSUE THREAD

**Issue by rejoasri** [OpenSID/OpenSID#4708]
### Apa kekurangan yg ingin diatasi?

Optimalisasi Kecepatan Website

### Jelaskan solusi yg diinginkan

Kompresi pada IMG yang disubmit

### Apakah ada alternatif lain

Panduan Size IMG untuk user pemula agar lebih presisi dismua layar

### Untuk versi OpenSID mana

22.1

### Informasi tambahan

View pengujian :
https://pagespeed.web.dev/report?url=https%3A%2F%2Frejoasri.id%2F
https://pagespeed.web.dev/report?url=https%3A%2F%2Fwww.sampano.desa.id%2F

kondisi ping dibawah 50ms
webhosting 
rumahweb.com = rejoasri.id
info dari grub thema silir = sampano.desa.id

jika diperhatikan mungkin hanya hal sepele cuma menurut saya kecepatan website juga perpengaruh pada index google dan juga kepuasan dari pengunjung website. terlebih lagi rata-rata website yang menggunakan openSID tidak lebih mendapat penilaian dibawah 50%. dengan indikator perlambatan pada pemrosesan img paling besar berpengaruh pada kecepatan website

**Comment by balongbesuk** [comment]
buset rata rata 1 mb  imagenya 😄

**Comment by rejoasri** [comment]
> buset rata rata 1 mb imagenya 😄

Iya pak, makanya perlu adanya panduan size img biar lebih wuss

**Comment by wirawan114** [comment]
pemanfaatan ajx juga mungkin dapat meperingan website namun berpengaruh pada seo
