### ISSUE TITLE
Bug/error: bagan menu pencarian ketika tombol keyboard enter muncul blankpage

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#4709]
### Jelaskan error yg dialami

ketika mencari nama penduduk d menu pencarian kemudian tekan tombol enter keyboard muncul blankpage

### Cara untuk mereplikasi errornya

buka menu kependudukan / keluarga > cari penduduk > masukkan nama > enter tombol keyboard > muncul blankpage

### Hasil yg diharapkan

bisa menggunakan kombol keyboard fisik tanpa tekan tombol pencarian di menu pencarian

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Umum

### Versi OpenSID

website demo dan berputar

**Comment by balongbesuk** [comment]
![Untitled](https://user-images.githubusercontent.com/35319600/149250703-cb3839f8-0609-48f1-b742-2ea9a0e4ed50.png)

**Comment by andifahruddinakas** [comment]
Cek @scqolbu24

**Comment by andifahruddinakas** [comment]
Sy cek tdk ada masalah di umum dan berputar
![coba2](https://user-images.githubusercontent.com/57283157/149437420-345c7c7a-13a9-4e85-b67f-d551f0993578.png)

silahkan dibuka kembali jika mengalami kendala yang sama.

**Comment by balongbesuk** [comment]
cara mereplikasi errornya 

d kotak pencarian > ketik nama  > kemudian tekan enter keyboard bukan tombol cari di kotak pencarian

bug akan diarahkan ke blank page yang alamat webny https://demo.opensid.or.id/penduduk/filter/cari

**Comment by balongbesuk** [comment]
sy cb d chrome lancar mungkin karenan addon firefox

closed
