### ISSUE TITLE
[Layanan Mandiri] Kirim Pin Baru Melalui Email

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/OpenSID#4710]
### Apa kekurangan yg ingin diatasi?

Saat ini untuk mengirim PIN Baru hanya tersedia melalui kirim melalui telegram yang telah diverifikasi.
issue ini merupakan lanjutan dari issue : [[Layanan Mandiri] Penambahan Fitur Kirim PIN baru melalui email/Telegram ke warga #3663 ](https://github.com/OpenSID/OpenSID/issues/3663)

### Jelaskan solusi yg diinginkan

Dapat mengirim pesan PIN baru ke email yang telah diverifikasi.

### Untuk versi OpenSID mana

v22.02-premium

### Informasi tambahan

issue ini berkaitan dengan issue : 

1. [[Penduduk] Verifikasi akun Email #4612](https://github.com/OpenSID/OpenSID/issues/4612)
2. [[Layanan Mandiri] Kirim Verifikasi Melalui Email Pada Saat Pendaftaran #4711](https://github.com/OpenSID/OpenSID/issues/4711)

**Comment by agungsugiarto** [comment]
Sudah masuk di rilis premium melalui pr https://github.com/OpenSID/premium/pull/603
