### ISSUE TITLE
[Layanan Mandiri] Kirim Verifikasi Melalui Email Pada Saat Pendaftaran

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/OpenSID#4711]
### Apa kekurangan yg ingin diatasi?

Saat ini di pendaftaran layanan mandiri baru tersedia verifikasi telegram untuk validasi.
issue ini merupakan lanjutan dari issue : [[Layanan Mandiri] Pendaftaran Layanan Mandiri #1760](https://github.com/OpenSID/OpenSID/issues/1760).

### Jelaskan solusi yg diinginkan

Melakukan verifikasi email.

### Untuk versi OpenSID mana

v22.02-premium

### Informasi tambahan

issue ini dapat dikerjakan setelah issue [[Penduduk] Verifikasi akun Email #4612](https://github.com/OpenSID/OpenSID/issues/4612) selesai.

**Comment by agungsugiarto** [comment]
Sudah masuk di rilis premium melalui pr https://github.com/OpenSID/premium/pull/610
