### ISSUE TITLE
Layanan Mandiri Kembali Kehalaman Web Utama Saat Logout

### ISSUE THREAD

**Issue by rudiansyahyunanda** [OpenSID/OpenSID#4712]
pada dasarnya website kita digunakan untuk menampilkan informasi. sementara form login hanya digunakan untuk yang memiliki akses saja. 

ini sangat berpengaruh saat di anjungan. 
ketika warga logout kembali ke halaman login. anjungan ditinggal dan masih menampilkan halaman login layanan mandiri.

Ada baiknya dikembalikan ke halaman web utama seperti logout admin setelah logout agar kembali menampilkan website utama. yang tidak berniat loginpun mungkin dapat membaca artikel yang kebetulan melihat tampilan web utama.

**Comment by balongbesuk** [comment]
jadi gak guna fitur screen saver opensidnya 😄

**Comment by eddieridwan** [comment]
Bung @rudiansyahyunanda , jika itu yg anda butuhkan,  buka saja web desa langsung di 'anjungan'. Dan tidak perlu daftarkan sebagai anjungan. Yaitu biarkan 'anjungan' itu berperan seperti halnya laptop atau HP biasa.

Anjungan dimaksudkan untuk fungsi yg berbeda, bukan sebagai web desa. Melainkan sebagai gawai layanan. Yaitu fitur2 yg disediakan dimaksudkan bukan untuk warga yg akan berlama-lama di gawai itu. Seperti dikatakan bung @balongbesuk di atas, pada waktu anjungan tidak digunakan untuk layanan, maka akan berperan sebagai media informasi. Tetapi yg sifatnya non-interaktif, melainkan seperti papan pengumuman, untuk menyajikan informasi satu arah bagi warga. Bisa berupa kumpulan slide atau video yg senantiasa diputarkan sampai ada yg akan menggunakan untuk layanan.

**Comment by eddieridwan** [comment]
@rudiansyahyunanda silakan tutup issue ini jika penjelasan di atas menjawab kebutuhan anda.
