### ISSUE TITLE
Permintaan fitur: Tambahkan fitur kustomisasi warna tema web

### ISSUE THREAD

**Issue by dikisiswanto** [OpenSID/OpenSID#4715]
### Apa kekurangan yg ingin diatasi?

Belum ada fitur ini. Praktik yang dijalankan saat ini pengguna perlu mengubah kode pada tema secara langsung.

Fitur yang diinginkan mirip _customizer_ pada platform WP atau Blogger.

### Jelaskan solusi yg diinginkan

Adanya fitur ini diharapkan membantu pengguna untuk melakukan perubahan warna tema web tanpa harus bersinggungan dengan kode secara langsung. Warna yang sudah dipilih oleh pengguna dapat disimpan dan dapat diterapkan ke tema.

### Apakah ada alternatif lain

Gunakan elemen Bootstrap Color Picker yang ada di AdminLTE: https://adminlte.io/themes/AdminLTE/pages/forms/advanced.html

### Untuk versi OpenSID mana

v22.01

**Comment by andifahruddinakas** [comment]
Duplicate issue https://github.com/OpenSID/OpenSID/issues/2486
