### ISSUE TITLE
Permintaan fitur: Suplai data statistik yang tersedia ke halaman statistik web

### ISSUE THREAD

**Issue by dikisiswanto** [OpenSID/OpenSID#4716]
### Apa kekurangan yg ingin diatasi?

Data ini untuk kebutuhan navigasi pada tema. Sebenarnya bisa ditulis manual, tetapi akan lebih mudah apabila datanya disediakan. Jika di kemudian hari ada tambahan, tidak perlu menambahkan secara manual.

### Jelaskan solusi yg diinginkan

![image](https://user-images.githubusercontent.com/22239074/149602935-00951b76-b426-43e0-994d-53206733fd60.png)

### Apakah ada alternatif lain

Input manual tidak efektif

### Untuk versi OpenSID mana

22.02

**Comment by balongbesuk** [comment]
wah setuju 👍

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui commit https://github.com/OpenSID/premium/commit/bb0710717892882514a79d3d6fb467a98e511b08
