### ISSUE TITLE
Bug/error: Gagal Tampil Halaman Website

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#4718]
### Jelaskan error yg dialami

Ketika akses halaman website berdasarkan kategori, maka akan gagal akses ketika klik halaman selanjutnya.

### Cara untuk mereplikasi errornya

Masuk halaman Kategori.
https://berputar.opensid.or.id/artikel/kategori/berita-desa

Lalu klik halaman 2 dan seterusnya, maka akan error 404
Karena halaman kedua link menjadi:
https://berputar.opensid.or.id/kategori/berita-desa/2

Kurang slug /artikel/

### Hasil yg diharapkan

Normal sebagaimana mestinya
https://berputar.opensid.or.id/artikel/kategori/berita-desa/2

### Tangkapan layar dan log error

Bisa dicoba langsung di web berputar.

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.02-premium

### Tema Yang Digunakan

Seluruhnya

### Informasi tambahan

Penyesuaian SLUG masih ada di versi Premium.
Besar kemungkinan jika nantinya rilis ke umum, akan mengalami hal yg sama sebelum diperbaiki.

Seharusnya perbaikan ini tentu wajib diterapkan ke versi umu ketika pertama kali penerapan SLUG dirilis sesuai jadwal.

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/624
