### ISSUE TITLE
Penduduk datang lagi

### ISSUE THREAD

**Issue by afri18** [OpenSID/OpenSID#4719]
### Jelaskan error yg dialami

saat entri penduduk datang terdeteksi NIK sudah digunakan, tadinya sudah pindah dan sekarang datang lagi hanya problemnya tidak bisa di input sebagai penduduk datang karna NIK sudah ada di Table tweb_penduduk hanya saja tercatat sebagai penduduk pindah

### Cara untuk mereplikasi errornya

sebaiknya penduduk yang pindah datanya dipindahkan di tabel log_pindah, jadi saat datang penduduk tersebut tetap tercatat sebagai penduduk datang

### Hasil yg diharapkan

Nantinya penduduk yg sudah pindah bisa masuk dengan status penduduk datang (lagi)

### Tangkapan layar dan log error

![datang_eror](https://user-images.githubusercontent.com/6611881/149705636-4ad09090-034b-48e7-aae2-f3630abd0977.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

22.01_rev01

### Tema Yang Digunakan

denatra

### Informasi tambahan

Nantinya riwayat penduduk yang pernah pindah dan datang lagi tetap tercatat di system sesuai keadaan sebenarnya, saat ini bila dikembalikan riwayat penduduk yg datang lagi  catatan pindahnya jadi hilang
![datang_eror_1](https://user-images.githubusercontent.com/6611881/149706039-bdfe9d76-2734-4a2a-8bd0-1fba57d02fd6.png)

**Comment by ariandii** [comment]
bisa lakukan hal tersebut melalui Log Penduduk untuk kembalikan penduduk yg pindah datang kembali.

<img width="593" alt="image" src="https://user-images.githubusercontent.com/46939846/149710247-42cbce8b-f6ec-4424-a69d-0ed2b61e0dc0.png">

**Comment by afri18** [comment]
@ariandii  kalau melakukan "KEMBALI" tidak tercatat sebagai penduduk datang, dan catatan riwayat pernah pindahnya hilang/nggak ada

**Comment by eddieridwan** [comment]
Catatan teknis: lihat cara pencatatan untuk penduduk tidak tetap yg pergi/kembali berulang-kali sebagai contoh.

**Comment by eddieridwan** [comment]
Lihat pembahasan di https://www.facebook.com/groups/OpenSID/posts/2190175917814044/?comment_id=2190418694456433

**Comment by eddieridwan** [comment]
Catatan: fitur 'Kembali' di log penduduk mungkin bisa dibatasi hanya dapat dilakukan dalam bulan laporan peristiwa. Setelah lewat itu, sepertinya tidak dapat dikembalikan lagi, karena seharusnya sudah direkam di laporan bulanan bagi bulan ybs. Kalau tetap dilakukan, akan menghapus riwayat perubahan status dasar penduduk dan mengubah laporan bulanan yg sudah lewat.

**Comment by andifahruddinakas** [comment]
SOLUSI : 
1. Untuk status **PINDAH_KELUAR** jika kembalikan status maka status di log_penduduk bertambah  dengan status  **BARU_PINDAH_MASUK** dengan data yang sama.
2. Tambahkan tombol hapus dan bedakan fungsinya dengan tombol kembalikan status.
3. Tombol kembalikan status digunakan untuk kasus penduduk pulang pergi dimana log lama tidak terhapus, sehingga tidak merusak log_penduduk
4. Tombol hapus digunakan untuk kasus penduduk yang salah mengubah status penduduk misalnya penduduk mati, jika menggunakan tombol ini log yang sebelumnya akan terhapus. (versi sebelumnya, peringatan ditampilkan sebelum eksekusi)
5. Tombol kembali yang berlaku untuk status **PINDAH_KELUAR**

Pak @eddieridwan, @vickyrolanda bisa di cek alur ini.

**Comment by eddieridwan** [comment]
@andifahruddinakas @vickyrolanda saran saya sbb:

1. Bagi penduduk yang `pindah keluar`, sediakan tombol untuk `pindah masuk kembali`, dengan data yang sama. Di log_penduduk tercatat peristiwa `pindah keluar` dan `pindah masuk` bagi penduduk tersebut. Tombol tersebut disediakan di log_penduduk dan juga di daftar penduduk utama (pada filter untuk semua penduduk atau khusus penduduk pindah keluar).
2. Tombol `kembalikan` (karena salah ubah) tetap seperti sekarang, termasuk dengan peringatan. 
3. Jika petugas melakukan `pindah masuk` dengan memasukkan NIK penduduk yg `pindah keluar`, lakukan proses `pindah masuk kembali` seperti di (1)

**Comment by afri18** [comment]
cocok

**Comment by andifahruddinakas** [comment]
> @andifahruddinakas @vickyrolanda saran saya sbb:
> 
> 1. Bagi penduduk yang `pindah keluar`, sediakan tombol untuk `pindah masuk kembali`, dengan data yang sama. Di log_penduduk tercatat peristiwa `pindah keluar` dan `pindah masuk` bagi penduduk tersebut. Tombol tersebut disediakan di log_penduduk dan juga di daftar penduduk utama (pada filter untuk semua penduduk atau khusus penduduk pindah keluar).
> 2. Tombol `kembalikan` (karena salah ubah) tetap seperti sekarang, termasuk dengan peringatan. 
> 3. Jika petugas melakukan `pindah masuk` dengan memasukkan NIK penduduk yg `pindah keluar`, lakukan proses `pindah masuk kembali` seperti di (1)

Ok

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1372
