### ISSUE TITLE
Bug/error: securimage tidak tampil?

### ISSUE THREAD

**Issue by totoprayogo1916** [OpenSID/OpenSID#4720]
### Jelaskan error yg dialami

Securimage tidak tampil

### Cara untuk mereplikasi errornya

buka saja: https://berputar.opensid.or.id/artikel/2016/8/26/wilayah-desa

### Hasil yg diharapkan

mestinya tampil securimage

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/2387514/149708101-eeb8104a-db23-46ba-ab9e-6d189f0e4792.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

*

### Informasi tambahan

dilihat source:
url gambar hanya https://berputar.opensid.or.id/securimage/securimage_show
url semestinya: https://berputar.opensid.or.id/securimage/securimage_show.php

**Comment by ariandii** [comment]
Informasi tambahan.
Hal tersebut normal jika menggunakan tema lain (klasik dan denatra).

<img width="623" alt="image" src="https://user-images.githubusercontent.com/46939846/149710122-dac57d16-d8bd-48d8-909f-a03489364d12.png">

<img width="617" alt="image" src="https://user-images.githubusercontent.com/46939846/149710062-16ffbfae-8357-482f-9109-62137e7c5e3b.png">

**Comment by totoprayogo1916** [comment]
berarti ...
masalahnya ada di temanya ...
