### ISSUE TITLE
Bug/error: Di Layanan mandiri

### ISSUE THREAD

**Issue by aseppakot** [OpenSID/OpenSID#4721]
### Jelaskan error yg dialami

Bug/error: Di Layanan mandiri, setelah login baru, ganti password masih muncul notif telah dirubah password tetapi jadi logour

### Cara untuk mereplikasi errornya

1. buka login layanan mandiri
2. masukan NIK dan PIN
3. muncul notif ganti PIN
4. PIN Sudah diganti kemudian Keluar
5. Pas masuk muncul PIN Sudah diganti
6. muncul lagi notif kemudian keluar lagi
7. dan lagi

### Hasil yg diharapkan

tidak keluar/ logout lagi 

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/32024580/149716736-16d95103-93ce-4ea2-8286-1d75626dfad2.png)

### Rilis Versi OpenSID

Rilis Umum

### Versi OpenSID

22.01

### Tema Yang Digunakan

natra

**Comment by andifahruddinakas** [comment]
Pak @aseppakot, apakah anda membuka halaman admin dan layanan mandiri di 1 browser yang sama???
