### ISSUE TITLE
Bug/error: Kode Warna Bermasalah 

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#4723]
### Jelaskan error yg dialami

Ketika memilik warna menggunakan pointer yg tersedia, maka tercipta kode seperti rgba(78,207,152,0.65)

Namun jika diisi manual misal warna putih dengan kode #FFFFF akan sukses.

### Cara untuk mereplikasi errornya

Masuk ke halaman edit salah satu aparatur desa, tentukan bagannya.

### Hasil yg diharapkan

Normal sebagaimana mestinya.

### Tangkapan layar dan log error

<img width="554" alt="screenshot_178" src="https://user-images.githubusercontent.com/46939846/149868605-dc6b4a58-6701-4546-91c0-4f1a225c1b24.png">

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.01-premium

**Comment by scqolbu24** [comment]
sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/623
