### ISSUE TITLE
Hanya Satu Form Lagi Tersisa pada Form F-1.08 (Pindah Pergi) Surat Keterangan Pindah Penduduk

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#4725]
### Jelaskan error yg dialami

1. Pada Form Surat Keterangan Pindah Penduduk Pergi (F-1.08) Tempat tanda tangan masih terdapat Nama Kepala Desa Default Systam (MUHAMM ILHAM).
2. Tanggal pada tempat tanda/tangan kepala desa juga juga tidak muncul
![image](https://user-images.githubusercontent.com/64481641/149974159-56baf658-3d87-4a89-9725-d8210ae3fc23.png)

### Cara untuk mereplikasi errornya

1. Pilih Menu Layanan Surat --> Pilih Cetak Surat
2. Pilih Surat Keterangan Pindah --->di Pilihan-->Gunakan Format
3. Pilih Form F-1.08 (pindah pergi)
4. pilih cetak pdf...

### Hasil yg diharapkan

1. Tempat yang menanda tanngan otomatis sesuai dengan yg dipilih
![image](https://user-images.githubusercontent.com/64481641/149975320-16e16900-1ba5-41bb-8000-4e090391c08b.png)

### Tangkapan layar dan log error

Screensote Lampiran Surat F-1.08
![image](https://user-images.githubusercontent.com/64481641/149976839-803c7fd2-5ffa-415e-a103-b92ac9a901fa.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Premium 22.01-Rev02

### Tema Yang Digunakan

DeNatra

### Informasi tambahan

Dari semua form surat yang sudah diperiksa hanya form ini yg masih belum fit->hanya pada tempat tanda tangan, kalau tanggal tidak muncul pada form cetak surat memang tidak ada pilihan tanggal, sehingga tidak dapat membuat ketentuan apakah otomati atau manual untuk pemberian tanggal surat ditempat tanda tangan kepela desa.

**Comment by FirlianiF** [comment]
Setelah dicek, tanda tangan berhasil otomatis muncul sesuai pilihan di form, dan untuk tanggal pada tempat tanda/tangan kepala desa saat ini telah ditambahkan.

**Comment by yogiperdana** [comment]
Telah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/625
