### ISSUE TITLE
Permintaan fitur: Penambahan UNGGAH lebih dari satu jenis type dokumen untuk dapat di UNGGAH ke Fitur pendataan Vaksin

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#4726]
### Apa kekurangan yg ingin diatasi?

Permintaan Penambahan type jenis dokumen untuk dapat di unggah atau di disimpan dalam system data base opensid pada fitur Pendataan Vakasi Saat ini hanya dapat unggah dokumen dengan type jpeg saja, permintaan agar dapat menggugah dokumen dalam bentuk lainnya diantaranya :
1. Dokumen Type JPEG (tetap);
2. Dokumen type PNG; dan 
3. Dokumen type PDF;

### Jelaskan solusi yg diinginkan

include

### Apakah ada alternatif lain

include

### Untuk versi OpenSID mana

 v22.01-premium

### Informasi tambahan

![image](https://user-images.githubusercontent.com/64481641/150062906-55c846b0-5b87-468c-b789-816780e73390.png)

**Comment by andifahruddinakas** [comment]
Sudah ditambahkan melalui PR https://github.com/OpenSID/premium/pull/703
