### ISSUE TITLE
Permintaan fitur: Penambahan Detail Data Pada Menu Tambah Kontak Fitur SMS

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#4727]
### Apa kekurangan yg ingin diatasi?

Permintaan agar dapat menambah Detail Data pada Fitur Panggilan Data untuk Tambah data Kontak pada fitur :
SMS ---> Daftar Kontak - Tambah Kontak 

TAMPILAN SAAT INI, data dengan nama-nama yang sama sulit ditandai untuk ditambah ke Daftar Kontak 

![image](https://user-images.githubusercontent.com/64481641/150064048-cf85055e-b881-4333-9d9f-2f5c5267bcf1.png)

### Jelaskan solusi yg diinginkan

include : seperti screensote dibawah

![image](https://user-images.githubusercontent.com/64481641/150064193-b3ee776e-fb9d-4b67-9bfd-ab91d9918d3a.png)

### Apakah ada alternatif lain

Bisa Include seperti menambah atau memanggil data Individu pada Penambahan Data Fitur Bantuan Kategori Penduduk/Individu.
![image](https://user-images.githubusercontent.com/64481641/150064475-1ac3b65c-53b1-4845-bbcd-414f896391da.png)

### Untuk versi OpenSID mana

 v22.01-premium

### Informasi tambahan

Include

**Comment by yogiperdana** [comment]
Duplikat dengan issue https://github.com/OpenSID/OpenSID/issues/5179
