### ISSUE TITLE
Bug/error: TIDAK DAPAT MENGUBAH NAMA DESA

### ISSUE THREAD

**Issue by roderikmogot** [OpenSID/OpenSID#4728]
### Jelaskan error yg dialami

Tidak dapat mengubah nama desa di menu `Identitas Desa`, dropdown list hanya menampilkan *The results cannot be loaded.*

### Cara untuk mereplikasi errornya

1. Pergi ke halaman `https://<nama domain>/identitas_desa/form`
2. Ubah `Nama Desa` sesuai dengan desa yang diinginkan
3. Lihat error pada dropdown list

### Hasil yg diharapkan

Dapat mengubah nama desa dengan nama desa yang sesuai.

### Tangkapan layar dan log error

Pada dropdown list muncul *The results cannot be loaded.*

### Rilis Versi OpenSID

Rilis Umum

### Versi OpenSID

22.01

### Tema Yang Digunakan

Silir

**Comment by andifahruddinakas** [comment]
https://github.com/OpenSID/OpenSID/wiki/Identitas-Desa
