### ISSUE TITLE
Upload FOTO pada Biodata Penduduk terjadi Double Form Bug/error: 

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#4729]
### Jelaskan error yg dialami

Saat meng-upload foto pada fitur data tambah/ubah data penduduk terjadi double (2x) muncul form upload, hal ini terjadi disaat klik tombol "UNGGAH FOTO" pilih "FOTO" system tidak langsung menyampan akan tetapi masuk lagi ke FORM minta DI UNGGAH KEMBALI

![image](https://user-images.githubusercontent.com/64481641/150065045-04af02ae-2fb6-42fd-9276-ca9f87dbecfc.png)

![Uploading image.png…]()

### Cara untuk mereplikasi errornya

Buka Salah Satu Data Penduduk Pilih Aksi Ubah Biodata Penduduk --->Klik pada Unggah Foto
![image](https://user-images.githubusercontent.com/64481641/150065355-92280e60-340e-4300-9ea2-cff5af99a4b9.png)

### Hasil yg diharapkan

Agar normal kembali, pada saat pilih unggah foto pilih foto,  langsung data dapat disimpan dengan sekali pilih

### Tangkapan layar dan log error

include

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Premium V22.01 Rev01 dan Premium V22.02

### Tema Yang Digunakan

DeNatra

### Informasi tambahan

Include

**Comment by andifahruddinakas** [comment]
https://github.com/OpenSID/OpenSID/issues/4769
