### ISSUE TITLE
Urutan Nama Dusun Belum ter-Urut  tampil pada menu cetak/rekap laporan Fitur Pendataan Vaksin

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#4730]
### Jelaskan error yg dialami

Nama Dusun Yang tampil pada Laporan Rekap Data Pendataan vaksin belum ber-urut menurut urutan Dusun, bila nama dusun dibuat dengan Nomor Urut baik Numerik maupun Romawi
![image](https://user-images.githubusercontent.com/64481641/150067278-fecf6109-22c3-45b7-96ef-1fa1d86fecb1.png)

### Cara untuk mereplikasi errornya

Pilih Fitur Vaksin ---> Pilih Laporan Rekap

### Hasil yg diharapkan

Agar tampilan dusun sesuai dengan urutan masing-masing dusun pada form Rekap Laporan Data Vaksin

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/64481641/150067330-72776ba3-6a73-48fa-ac89-92a568af9d0e.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Premium V22.01 REV02

### Tema Yang Digunakan

Default

### Informasi tambahan

Include

**Comment by FirlianiF** [comment]
sudah di perbaiki melalui pr https://github.com/OpenSID/premium/pull/699
