### ISSUE TITLE
Bug/error: Latar Website pada tema tidak berganti

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#4731]
### Jelaskan error yg dialami

Saat mengganti latar website, perubahan di tema tidak terjadi.

### Cara untuk mereplikasi errornya

1. Masuk pengaturan > aplikasi
2. Ubah latar website

### Hasil yg diharapkan

Lata4r website meyeuaikan dengan yang diganti pada tema yang aktif

### Tangkapan layar dan log error

tidak ada

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

22.01

### Tema Yang Digunakan

bawaan

### Informasi tambahan

tidak ada

**Comment by FirlianiF** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/611
