### ISSUE TITLE
Tambahkan Fitur Absensi

### ISSUE THREAD

**Issue by cepiandiana** [OpenSID/OpenSID#4732]
### Apa kekurangan yg ingin diatasi?

Permintaan Penambahan Fitur Absensi yang mana hampir diterapkan dan pernah dicoba pada bulan April tahun 2021 oleh bung Zeppy Shiddiq, Sehingga semakin banyak yang tertarik dengan OpenSID (Premium). 

Dengan tersedianya Fitur Absensi, akan semakin menguatkan Penggunaan OpenSID dan Ketergantungan Penggunaannya.

### Jelaskan solusi yg diinginkan

1. Perangkat Desa melakukan Absen dengan cara  Tap eKTP / ID CARD (RFID Mifare) sebagaimana yang telah dilakukan pada Fitur layanan mandiri. 
![FB_IMG_1642611071031](https://user-images.githubusercontent.com/39004343/150178618-9ba15eb6-ce05-4007-8606-0631f90a7218.jpg)

2. Menggunakan sistem geofencyng System / geotaglocation dan Anti Fake GPS, untuk menghindari perangkat melakukan absen dimana saja. Dan dirasa ini sudah bisa dilakukan karena titik koordinat kantor desa telah tersedia, jadi ketika absen diluar radius titik koordinat, tidak bisa absen

3. Dan sistem2 pendukung lainnya sudah dijelaskan dalam postingan bung Zeppy
![Screenshot_2022-01-19-23-48-47-24_a23b203fd3aafc6dcb84e438dda678b6](https://user-images.githubusercontent.com/39004343/150180109-ea8d257b-cee3-46ee-873c-994451b27c05.jpg)

### Apakah ada alternatif lain

Apabila belum memungkinkan digabung ke Android / mobile, tetap bisa dilakukan melalui browser Hp / webview khusus untuk absensi

### Untuk versi OpenSID mana

V.22.02-Premium dan Harus selalu di Versi Premium

### Informasi tambahan

Call Back Bung Zeppy Shiddiq

**Comment by eddieridwan** [comment]
Pertanyaan yg perlu kita pertimbangkan serius adalah sbb.

`Apakah bermanfaat untuk kita kembangkan absensi lengkap sebagai aplikasi OpenDesa?`

Atau apakah seperti kasus Kabupaten Batu Bara (dan mungkin juga di wilayah lain), di mana fungsi absensi resmi akan diambil alih oleh Pemda -- yg mengharuskan digunakan oleh semua jajaran pemerintahan dengan sanksi gaji? Kalau ini yg akan terjadi, mubazir kita lakukan. Sehingga lebih baik fokus pada stunting, posyandu, PBB dstnya. Dan tentunya OpenDK. 

Perlu dipertimbangkan juga adalah: Kalau terlalu banyak aplikasi yg dikelola akhirnya tidak ada yg dapat dikelola dengan baik — semuanya menjadi asal jalan saja.

Perhatikan bahwa di OpenSID sedang dikembangkan modul Kehadiran Perangkat Desa (https://github.com/OpenSID/OpenSID/issues/4323), yang tujuannya terbatas dan fokus pada layanan warga, bukan penggajian atau ketertiban pegawai.

**Comment by balongbesuk** [comment]
untuk kelurahan mungkin di ambil alih oleh pemda tp untuk desa selama ini gaji tetap d kelola oleh desa sendiri mungkin beda lagi kl pemda yang berinisiatif mengelola hal itu,

diterapkan bagus dapat menambah fungsi anjungan mandiri desa yang mayoritas hanya sebagai pajangan cantik d pojok ruangan,

tidak diterapkan juga tidak masalah karena gaji d desa tidak terhitung absensi kehadiran terutama daerah pelosok hadir saja sudah bersyukur,

**Comment by cepiandiana** [comment]
Saya rasa sangat bermanfaat pak ketika fitur absensi diterapkan, bisa menjadi aplikasi tambahan yang benar2 diperlukan desa. 

Tidak perlu menjadi aplikasi payrol yang identik absensi itu dengan sistem penggajian, tapi sebagai absensi yang merekam kehadiran saja, rekapan hasil absensi biasanya hanya sebagai bahan evaluasi saja tidak bersangkutan dengan gaji. Seperti yang berjalan sekarang ini.

Betul seperti yang dikatakan rekan @balongbesuk diatas. 
Penambahan fitur absensi sebagai pendongkrak penggunaan aplikasi opensid. 

Saya yakin banyak yang menggunakan opensid hanya untuk keperluan website saja, seandainya ini diterapkan akan menjadi daya tarik tersendiri untuk menggunakan aplikasi opensidnya.

**Comment by eddieridwan** [comment]
@cepiandiana lihat pesan di atas: 

Perhatikan bahwa di OpenSID sedang dikembangkan modul Kehadiran Perangkat Desa (#4323), yang tujuannya terbatas dan fokus pada layanan warga, bukan penggajian atau ketertiban pegawai.

**Comment by dgyoganantha** [comment]
Sependapat dengan bung cepiandiana. Fitur ini akan sangat bermanfaat bagi desa.
