### ISSUE TITLE
[PREMIUM] Aplikasi kembali home page 

### ISSUE THREAD

**Issue by mizwaruddin** [OpenSID/OpenSID#4733]
### Jelaskan error yg dialami

Saat login dan proses belum sempurna/masih loading (proses masuk ke dashboard), kemudia kita klik menu, maka aplikasi akan kembali ke halaman home page website.

### Cara untuk mereplikasi errornya

1. Login
2. Loading dashboard
3. Klik salah satu menu
4. Kembali ke halaman awal website
5. Klik back
6. Masuk ke dashboard

### Hasil yg diharapkan

Ketika proses loading belum selesai, kemudian user/admin menekan salah satu menu, halaman tetap berada di dashboard.

### Tangkapan layar dan log error

![bug 1](https://user-images.githubusercontent.com/39736008/150262585-46fbe1b3-601d-4d71-973f-37797725f313.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

OpenSID 22.01-premium-beta02

### Tema Yang Digunakan

OpenSID 22.01-premium-beta02

**Comment by andifahruddinakas** [comment]
Sy tdk mengalami hal ini, mungkin masalah jaringan ???
