### ISSUE TITLE
[UMUM] Bug/error: Aplikasi kembali ke home page

### ISSUE THREAD

**Issue by mizwaruddin** [OpenSID/OpenSID#4734]
### Jelaskan error yg dialami

Saat login dan proses belum sempurna/masih loading (proses masuk ke dashboard), kemudia kita klik menu, maka aplikasi akan kembali ke halaman home page website.

### Cara untuk mereplikasi errornya

1.	Login
2.	Loading dashboard
3.	Klik salah satu menu
4.	Kembali ke halaman awal website
5.	Klik back
6.	Masuk ke dashboard

### Hasil yg diharapkan

Ketika proses loading belum selesai, kemudian user/admin menekan salah satu menu, halaman tetap berada di dashboard.

### Tangkapan layar dan log error

![bug 1](https://user-images.githubusercontent.com/39736008/150263736-a2491189-3d89-4a2a-9060-19cd5124d51f.png)

### Rilis Versi OpenSID

Rilis Umum

### Versi OpenSID

OpenSID 22.01-pasca

**Comment by andifahruddinakas** [comment]
Sy tdk mengalami hal ini, mungkin masalah jaringan ???
