### ISSUE TITLE
[PREMIUM] Bug/error: Rincian anggaran pembangunan melebihi total anggaran

### ISSUE THREAD

**Issue by mizwaruddin** [OpenSID/OpenSID#4735]
### Jelaskan error yg dialami

Pada menu pembangunan, jika rincian anggaran melebihi total anggaran masih dapat tersimpan. 

### Cara untuk mereplikasi errornya

1. Menu Pembangunan
2. Tambah Data
3. Isikan anggaran (mis: 200000)
4. Rincian biaya di sumber biaya diisi melebihi isian di anggaran (mis: 300000)
5. Simpan

### Hasil yg diharapkan

Total rincian anggaran di sumber biaya seharusnya tidak boleh melebihi total anggaran

### Tangkapan layar dan log error

![bug 2](https://user-images.githubusercontent.com/39736008/150265279-989c890b-ec17-461a-88d5-7955dc42f4e1.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

22.01-premium-beta02

**Comment by scqolbu24** [comment]
sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/627
