### ISSUE TITLE
Permintaan fitur: Tampilkan gambar pembangunan ketika akan diupload

### ISSUE THREAD

**Issue by mizwaruddin** [OpenSID/OpenSID#4736]
### Apa kekurangan yg ingin diatasi?

Saat memilih gambar utama pembangunan, gambar tidak tampil di preview 

### Jelaskan solusi yg diinginkan

Saat memilih gambar utama pembangunan, tampilkan di preview gambar terlebih dahulu untuk menghindari kesalahan gambar yang akan di upload.

### Apakah ada alternatif lain

Tidak ada

### Untuk versi OpenSID mana

OpenSID 22.01-premium-beta02

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/OpenSID/pull/7406
