### ISSUE TITLE
[PREMIUM] Bug/error: Foto Pembangunan Tidak Tampil di Lihat Summary

### ISSUE THREAD

**Issue by mizwaruddin** [OpenSID/OpenSID#4737]
### Jelaskan error yg dialami

Setelah foto pembangunan diupload, foto pembangunan tersebut tidak tampil ketika diklik lihat summary.

### Cara untuk mereplikasi errornya

1. Tambah data pembangunan
2. Tambah data pembangunan (termasuk gambar/foto pembangunan)
3. Simpan
4. Klik Menu Pembangunan
5. Klik lihat summary
6. Gambar/Foto Pembangunan tidak tampil.

### Hasil yg diharapkan

Gambar pembangunan tampil ketika diklik lihat summary

### Tangkapan layar dan log error

![bug 4](https://user-images.githubusercontent.com/39736008/150269729-df9fe1ba-cda2-49e0-981f-cd6fdb055c11.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

OpenSID 22.01-premium-beta02

**Comment by andifahruddinakas** [comment]
di local tdk ada masalah, setelah sy cek folder desa di website berputar tdk lengkap. Sehingga tdk dapat upload gambar. Ini karena setiap jam 1 malam website berputar dilakukan reset (kembali fresh), tp folder desa tdk lengkap di salin dari desa-contoh.
