### ISSUE TITLE
[UMUM] Peta Lokasi Tempat Tingga Penduduk Tidak Tampil Bug/error: 

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#4738]
### Jelaskan error yg dialami

Penentuan Lokasi Tempat Tinggal/Lihat Lokasi Tempat Penduduk Tidak Tampil
![image](https://user-images.githubusercontent.com/64481641/150270222-de340898-3253-4889-b7af-c06b6dd5ae65.png)

### Cara untuk mereplikasi errornya

1. Pilih Salah Satu Nama Warga
2. Klik Pilih Aksi
3. Klik Lihat Lokasi Tempat Tinggal

### Hasil yg diharapkan

Agar Normal Kembali, Lihat Lokasi Tempat Tinggal/Ubah dan Tentukan Lokasi Tempat Tinggal dapat di eksekusi

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/64481641/150270372-0abea4d8-a23f-407b-93c2-d60c823b359f.png)

### Rilis Versi OpenSID

Rilis Umum

### Versi OpenSID

Rilie Umum Beta-Dev R.22.01

### Tema Yang Digunakan

Default

### Informasi tambahan

Default

**Comment by Zoel-WB** [comment]
LOG ERROR -->TERJADI DIPETA WLAYAH DESA
ERROR - 2022-01-20 10:45:52 --> Query error: Incorrect datetime value: '-' for column `teupinbe_sidu`.`log_penduduk`.`tgl_lapor` at row 1 - Invalid query: UPDATE `log_penduduk` SET `tgl_peristiwa` = '1970-08-01', `tgl_lapor` = '-', `updated_at` = '2022-01-20 10:45:52', `updated_by` = '1', `maksud_tujuan_kedatangan` = ''
WHERE `id_pend` = '1191'
AND `kode_peristiwa` IN(1, 5)
ERROR - 2022-01-20 10:47:12 --> Query error: Incorrect datetime value: '-' for column `teupinbe_sidu`.`log_penduduk`.`tgl_lapor` at row 1 - Invalid query: UPDATE `log_penduduk` SET `tgl_peristiwa` = '1970-08-01', `tgl_lapor` = '-', `updated_at` = '2022-01-20 10:47:12', `updated_by` = '1', `maksud_tujuan_kedatangan` = ''
WHERE `id_pend` = '1191'
AND `kode_peristiwa` IN(1, 5)

![image](https://user-images.githubusercontent.com/64481641/150271606-2ccc37cd-90a4-4dc1-a435-83135f432f6b.png)

**Comment by andifahruddinakas** [comment]
> LOG ERROR -->TERJADI DIPETA WLAYAH DESA ERROR - 2022-01-20 10:45:52 --> Query error: Incorrect datetime value: '-' for column `teupinbe_sidu`.`log_penduduk`.`tgl_lapor` at row 1 - Invalid query: UPDATE `log_penduduk` SET `tgl_peristiwa` = '1970-08-01', `tgl_lapor` = '-', `updated_at` = '2022-01-20 10:45:52', `updated_by` = '1', `maksud_tujuan_kedatangan` = '' WHERE `id_pend` = '1191' AND `kode_peristiwa` IN(1, 5) ERROR - 2022-01-20 10:47:12 --> Query error: Incorrect datetime value: '-' for column `teupinbe_sidu`.`log_penduduk`.`tgl_lapor` at row 1 - Invalid query: UPDATE `log_penduduk` SET `tgl_peristiwa` = '1970-08-01', `tgl_lapor` = '-', `updated_at` = '2022-01-20 10:47:12', `updated_by` = '1', `maksud_tujuan_kedatangan` = '' WHERE `id_pend` = '1191' AND `kode_peristiwa` IN(1, 5)
> 
> ![image](https://user-images.githubusercontent.com/64481641/150271606-2ccc37cd-90a4-4dc1-a435-83135f432f6b.png)

ini bukan bug dari peta.

**Comment by andifahruddinakas** [comment]
Untuk issue ini (mengenai peta), maslahnya karena data sebelumnya (path) pada wilayah administrasi desa sudah ada. namun wilayah desa tdk ada sehingga berdampak ke yg lain.

Alur pengisian :
1. Lengkapi data wilayah desa dan lokasi
2. Lengkapi data wilayah dan lokasi dusun, rw dan rt.
3. Penduduk, pertanahan, dll.

**Comment by eddieridwan** [comment]
@andifahruddinakas buatkan issue supaya notifikasi tampil sesuai dengan alur pengisian data yg harus diikuti. Yaitu tidak tampilkan error tanpa penjelasan.
