### ISSUE TITLE
[PREMIUM] Bug/error: Jenis kelamin laki-laki masih muncul di tabel belum mengisi status kehamilan

### ISSUE THREAD

**Issue by mizwaruddin** [OpenSID/OpenSID#4742]
### Jelaskan error yg dialami

 Jenis kelamin laki-laki masih muncul di tabel belum mengisi status kehamilan

### Cara untuk mereplikasi errornya

1. Statistik-> statistik kependudukan-> status kehamilan
2. Klik angka pada kolom Jumlah Belum Mengisi
3. Data penduduk laki-laki masih muncul

### Hasil yg diharapkan

Seharusnya data penduduk yang muncul hanya yang berjenis kelamin perempuan.

### Tangkapan layar dan log error

![bug_statistik_kehamilan](https://user-images.githubusercontent.com/39736008/150280163-db7968c6-9ae7-4be9-8b38-2a5d025c0a70.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

OpenSID 22.01-premium-beta02

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui commit https://github.com/OpenSID/premium/commit/3687faafdb0cccaf3ccf39dfdefb533fafb662f1
