### ISSUE TITLE
[PREMIUM] Bug/error: Tombol bersihkan pada data suplemen tidak berfungsi normal

### ISSUE THREAD

**Issue by mizwaruddin** [OpenSID/OpenSID#4743]
### Jelaskan error yg dialami

Ketika tombol bersihkan di klik, kotak filter tidak kembali ke nilai default.

### Cara untuk mereplikasi errornya

1. Penduduk->Data Suplemen-> Rincian Data
2. Fungsikan filter (ex: Pilih-> Laki-laki)
3. Klik tombol "Bersihkan"
4. Nilai filter tidak kembali ke default

### Hasil yg diharapkan

Ketika tombol bersihkan di klik, kotak filter kembali ke nilai default.

### Tangkapan layar dan log error

![bug_suplemen_tombol_bersihkan](https://user-images.githubusercontent.com/39736008/150281982-4d95dcfc-e06e-4d56-b1fd-c9151386f164.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

OpenSID 22.01-premium-beta02

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui commit https://github.com/OpenSID/premium/commit/b22fe86b47b3200b07da92d80382022deb18e511
