### ISSUE TITLE
Bug/error: Sesuaikan Sebutan Desa pada Notifikasi Layanan Mandiri

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#4744]
### Jelaskan error yg dialami

Agar bisa menyesuaikan dengan sebutan lain seperti Nagari, Tiyuh, Kampung, dll.

### Cara untuk mereplikasi errornya

Hasil chat

### Hasil yg diharapkan

Normal dan Sesuai

### Tangkapan layar dan log error

<img width="711" alt="screenshot_216" src="https://user-images.githubusercontent.com/46939846/150307749-2cd355d0-393b-49ba-a373-e55e7753154c.png">

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.01-premium

**Comment by FirlianiF** [comment]
Sudah masuk di rilis premium melalui PR https://github.com/OpenSID/premium/pull/622
