### ISSUE TITLE
[PREMIUM] Bug/error: Salah penyebutan "Dusun" pada laporan rekap vaksin

### ISSUE THREAD

**Issue by mizwaruddin** [OpenSID/OpenSID#4745]
### Jelaskan error yg dialami

Dalam laporan rekap hasil vaksin kata "dusun' tertulis "desa"

### Cara untuk mereplikasi errornya

1. Siaga covid-19->vaksin->Laporan Rekap->cetak
2. Tabel laporan pada kolom Dusun tertulis Desa

### Hasil yg diharapkan

Kata Desa seharusnya Dusun

### Tangkapan layar dan log error

![bug_cetak_laporan_vaksin](https://user-images.githubusercontent.com/39736008/150309254-306e36dd-95fb-45d2-8894-fed319784b31.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

OpenSID 22.01-premium-beta02

**Comment by FirlianiF** [comment]
Sudah masuk di rilis premium melalui PR https://github.com/OpenSID/premium/pull/619
