### ISSUE TITLE
[PREMIUM] Bug/error: Nomor dan Tanggal Akta Nikah aktif ketika status perkawinan belum kawin

### ISSUE THREAD

**Issue by mizwaruddin** [OpenSID/OpenSID#4746]
### Jelaskan error yg dialami

Saat menambah penduduk baru, Nomor dan Tanggal Aktanikah aktif ketika status perkawinan belum kawin

### Cara untuk mereplikasi errornya

1. Kependudukan->penduduk-tambah baru lahir
2. Pilih status perkawinan->belum kawin
3. Nomor dan tanggal perkawinan masih aktif

### Hasil yg diharapkan

Ketika status perkawinan belum kawin, seharusnya nomor dan tanggal perkawinan tidak aktif.

### Tangkapan layar dan log error

![bug_tambah_penduduk_status_kawin](https://user-images.githubusercontent.com/39736008/150316274-0ceacc62-0867-4ae8-ae48-86f6b3d34c2d.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

OpenSID 22.01-premium-beta02

### Informasi tambahan

OpenSID 22.01-premium-rev01 sudah berjalan baik (nomor dan tanggal tidak aktif ketika status perkawinan belum kawin)

**Comment by FirlianiF** [comment]
Sudah masuk di rilis premium melalui PR https://github.com/OpenSID/premium/pull/620
