### ISSUE TITLE
[PREMIUM] Bug/error: Gagal Simpan Penduduk Baru untuk Usia 17+

### ISSUE THREAD

**Issue by mizwaruddin** [OpenSID/OpenSID#4748]
### Jelaskan error yg dialami

Saat tambah penduduk dengan tanggal lahir yang terhitung 17 tahun + wajib gagal disimpan karena harus mengisikan data identitas elektronik.

### Cara untuk mereplikasi errornya

1. Kependudukan-> Penduduk
2. Tambah Penduduk -> Baru Lahir/Masuk
3. Isikan tanggal lahir (dengan asumsi usia 17+), misal 1-1-2000
4. Data gagal disimpan dan mengharuskan data identitas elektronik, status rekam, dan tag id harus diisikan

### Hasil yg diharapkan

Data identitas elektronik, status rekam, dan tag id tidak harus diisikan karena bukan data wajib

### Tangkapan layar dan log error

![bug_tambah_penduduk_identitas_elektronik](https://user-images.githubusercontent.com/39736008/150320596-287f6723-bd28-4d33-ac40-a7a8b837c2c4.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

OpenSID 22.01-premium-beta02

**Comment by scqolbu24** [comment]
sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/628
