### ISSUE TITLE
Permintaan fitur: Pilihan Tahun di Statistik Bantuan

### ISSUE THREAD

**Issue by emanuel-simon** [OpenSID/OpenSID#4750]
### Apa kekurangan yg ingin diatasi?

Statistik Bantuan yang ditampilkan adalah gabungan dari semua bantuan di semua tahun,
Sehingga statistik penerima bantuan per tahun anggaran menjadi rancu.
Sediakan pilihan tahun agar statistik penerima bantuan dan bukan penerima bantuan per tahun anggarannya sesuai.

### Jelaskan solusi yg diinginkan

Sediakan dropdown list untuk memilih tahun tertentu
![2022-01-20_22h14_30](https://user-images.githubusercontent.com/48465803/150358886-e100a5bf-a050-436e-b26e-c00162630f24.png)
![2022-01-20_22h18_21](https://user-images.githubusercontent.com/48465803/150358967-c3955a80-a46f-44fc-9dfe-0d5cd4ee5700.png)
![2022-01-20_22h19_24](https://user-images.githubusercontent.com/48465803/150359001-c00eb136-a5e4-4131-b8b5-5f41141a6e6c.png)

Sediakan juga pilihan tahun di artikel
![2022-01-20_22h22_00](https://user-images.githubusercontent.com/48465803/150359442-7b406490-8612-4b8b-ad7e-82794dccb8e6.png)

### Apakah ada alternatif lain

Tidak ada solusi lain

### Untuk versi OpenSID mana

v22.03 atau v22.03-premium

**Comment by FirlianiF** [comment]
sudah di premium melalui PR https://github.com/OpenSID/premium/pull/662
