### ISSUE TITLE
Bug/error: Lampiran F.2.01 memunculkan Camat

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#4751]
### Jelaskan error yg dialami

cetak surat keterangan lahir muncul mengetahui camat

### Cara untuk mereplikasi errornya

buatn surat ket lahir

### Hasil yg diharapkan

sesuai format baku F.2.01 tanpa mengetahui camat

### Tangkapan layar dan log error

![Untitled](https://user-images.githubusercontent.com/35319600/150458172-4cd04324-0b47-4db2-bda6-2ab1d2097462.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

website berputar

### Tema Yang Digunakan

-

### Informasi tambahan

-

**Comment by yogiperdana** [comment]
Saya coba ambil mas

**Comment by eddieridwan** [comment]
Diverifikasi permintaan sesuai F-2.01 yg diperoleh dari https://disdukcapil.banjarbarukota.go.id/downlot.php?file=F-2.01_SURAT_KETERANGAN_KELAHIRAN.pdf

[F-2.01_SURAT_KETERANGAN_KELAHIRAN.pdf](https://github.com/OpenSID/OpenSID/files/7922119/F-2.01_SURAT_KETERANGAN_KELAHIRAN.pdf)

**Comment by scqolbu24** [comment]
sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/646
