### ISSUE TITLE
Bug/error: gagal Buat Artikel

### ISSUE THREAD

**Issue by khpurnawan** [OpenSID/OpenSID#4752]
### Jelaskan error yg dialami

Error 404 ketika artikel mengandung Tabel.

### Cara untuk mereplikasi errornya

Membuat artikel baru pada umumnya

### Hasil yg diharapkan

Normal sebagaiman mestinya

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/98139011/150459677-7e91be06-554e-48c3-a1c8-188a63a060f8.png)

### Rilis Versi OpenSID

Rilis Umum

### Versi OpenSID

v22.01

**Comment by andifahruddinakas** [comment]
Silahkan di ujicoba di website https://berputar.opensid.or.id/ dan https://demo.opensid.or.id/ jika tidak ada masalah, berarti masalah tsb ada pada hosting anda.

Contoh yang sy buat https://berputar.opensid.or.id/artikel/2022/1/23/test-atikel-dengan-tabel

![tabel](https://user-images.githubusercontent.com/57283157/150670128-0df6b44a-5070-4448-9826-7aac56404057.png)

**Comment by Zoel-WB** [comment]
Hasil Tester ;
![image](https://user-images.githubusercontent.com/64481641/151336247-5358f618-59c1-4cb3-92f4-98f0db109f4f.png)

![image](https://user-images.githubusercontent.com/64481641/151336317-b9ed3a8c-c71e-46f7-aa71-096001afdc73.png)

https://www.sidu.teupinbeulangan.desa.id/artikel/2022/1/27/jadwal-musyawah-desa

**Comment by eddieridwan** [comment]
@andifahruddinakas Jika tidak bisa direplikasi oleh beberapa tester, dan pelapor tidak bisa dihubungi maka issue dapat ditutup.
