### ISSUE TITLE
[PREMIUM] Fitur Status IDM bila Diklik (Panah Back Browser), Halaman Menjadi Error, Tahun Pilihan Status IDM Yg Tampil Tahun Berjalan, Seharusnya [Tahun] Status IDM Terakhir Bug/error

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#4753]
### Jelaskan error yg dialami

Fitur Status IDM Apabila Diklik (Panah Back) Pada (Browser) Halaman Tidak Kembali, Akan Tetapi Menjadi Error, dan Tahun Yang Tampil Di Pilihan Status IDM adalah Tahun Berjalan Bukan Tahun Status IDM Terakhir.

### Cara untuk mereplikasi errornya

Pergi Kehalaman Info Desa
1. Klik Fitur Status Desa
2. Layar Secreen dan Tahun Yang Tampil Kolom Status IDM-->adalah Tahun Kalender Berjalan pada system, bukan tahun atau seharusya tahun IDM terakhir
![image](https://user-images.githubusercontent.com/64481641/150486144-3fae72ba-ab50-4e39-97ab-6b4486316194.png)

3.  Pilih Tahun IDM - Setelah Itu Klik Tombol Panah Back Ke Kiri --.Browser Untuk Kembali kelayar sebelumnya, Akan Muncul Halaman Error.
![image](https://user-images.githubusercontent.com/64481641/150486383-4a1d77b9-3964-4f7b-8b31-4a4b34351d94.png)
![image](https://user-images.githubusercontent.com/64481641/150486415-5850f80b-2686-45b7-b809-a057d39508de.png)

### Hasil yg diharapkan

1. Kolom Tahun Pada Status IDM agar bisa menampilkan Status IDM tahun terakhir
2. Saat Menekan Tombol Kembali Browser, ssystem dapat kembali ke halaman sebelumnya
3. Menyediakan Tombol Untuk Kembali Ke sebelumnya (Back) sebelah kolom status idm
 
![image](https://user-images.githubusercontent.com/64481641/150489215-0e1633f7-38d9-4c70-9958-fb4990423046.png)

4. Status bisa normal.

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/64481641/150486741-14dd8ea5-d5f5-48e4-8232-8df62457a176.png)

![image](https://user-images.githubusercontent.com/64481641/150486761-a7bc65d7-3543-491e-93e1-10a717390a20.png)

![image](https://user-images.githubusercontent.com/64481641/150486777-f36e1593-b101-4012-b7f2-5d57cf3c2f73.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Rilis Premium v22.01 rev02

### Tema Yang Digunakan

default

### Informasi tambahan

include

**Comment by andifahruddinakas** [comment]
Sudah di jelaskan sama pak @eddieridwan di telegram.

```
Sebenarnya panah mundur bukan sesuatu yg perlu didukung oleh OpenSID. Setiap halaman umumnya menyediakan tombol kembali yang jauh lebih aman. Website transaksi/berlangkah seperti layanan/bank dll juga umumnya tidak bisa menggunakan fitur browser untuk balik; melainkan harus menggunakan tombol yg disediakan.
```

```
@fahruddinakas, sebaiknya kita tidak habiskan waktu untuk mendukung balik di browser. Prioritaskan yg lain.
```

```
Betul. Karena itu menjamin status sesi dll aman, sesuai dengan keadaan langkah yg sedang dijalankan. Terutama dalam hal di mana berada di sub-sub menu.
```

```
Kalau tombol kembali atau breadcrumb error, itu bug betulan.
```
