### ISSUE TITLE
[PREMIUM] Anjungan Layanan Mandiri Tidak Bisa Masuk Otomatis dengan Scan E-KTP  Bug/error: 

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#4754]
### Jelaskan error yg dialami

Saat mencoba mengakses Layanan Mandiri dengan menggunakan Ajungan masuk pakai scan e-ktp, system hanya berbunyi bip saja, akan layar login tidak keluar....
![image](https://user-images.githubusercontent.com/64481641/150494915-6f5be76f-40ff-4ef2-ab85-5282a6d97bbb.png)

### Cara untuk mereplikasi errornya

1. Aktifkan Anjungan Layanan Mandiri 
2. Jalankan Layanan mandiri dari url : https://www.teupinbeulangan.desa.id/layanan-mandiri/masuk
3. Pilih Masuk Menggunakan e-KTP
![image](https://user-images.githubusercontent.com/64481641/150495410-d32185e8-ee5f-402b-8c8e-f2170a91c170.png)

Lakukan scan e-ktp dengan RFID-Reader 
![image](https://user-images.githubusercontent.com/64481641/150495573-7e5b4dcf-8922-40ed-aecf-3948228505d4.png)

### Hasil yg diharapkan

Agar bisa normal, dan menggunakan anjungan masuk dengan scan e-ktp

### Tangkapan layar dan log error

tidak ada

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Rilis Premium v22.01 rev02

### Tema Yang Digunakan

default

### Informasi tambahan

Layanan mandiri saya tadi, mencoba menggantikan file (masuk.php) dengan versi lama permintaan di ujicoba yg dkirim kembali oleh pak Ariandi, menimpa file baru yg ada di folder donjo-app/view/fmandiri/masuk.php ---> system anjungan layanan mandiri baru dapat di akses dengan e-ktp.
cc: @ariandii

**Comment by andifahruddinakas** [comment]
Pak @Zoel-WB, @ariandii silahkan disertkan source code tsb sebagai pembanding. Krn dibagian login mandiri untuk rilis ini agak banyak perubahan.

**Comment by Zoel-WB** [comment]
Oke... sebentar lagi saya uploadkan

Dapatkan Outlook untuk Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by ariandii** [comment]
yang saya lakukan hanya mengganti seluruh <script>...</script> bagian paling bawah dari versi 22.01-premium asli.

tidak rubah php dan html bagian atas, termasuk tambahan tombol lupa password tetap tersedia.

setelah ganti java script bagian bawah ke versi sebelumnya ternyata normal kembali.

**Comment by Zoel-WB** [comment]
> Pak @Zoel-WB, @ariandii silahkan disertkan source code tsb sebagai pembanding. Krn dibagian login mandiri untuk rilis ini agak banyak perubahan.
File nya :
[masuk.txt](https://github.com/OpenSID/OpenSID/files/7920317/masuk.txt)

**Comment by andifahruddinakas** [comment]
Masalahnya ada di 
```
videona.pause();
```

baris selanjutnya tidak di eksekusi.

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melalui pr https://github.com/OpenSID/premium/pull/643
