### ISSUE TITLE
[PREMIUM] Bug/error: Gagal menyimpan data penduduk jika status kehamilan tidak dipilih

### ISSUE THREAD

**Issue by mizwaruddin** [OpenSID/OpenSID#4755]
### Jelaskan error yg dialami

Saat melakukan edit data penduduk dengan jenis kelamin perempuan terjadi error jika status kehamilan tidak dipilih.

### Cara untuk mereplikasi errornya

1. Kependudukan->penduduk
2. Pilih penduduk dengan jenis kelamin perempuan->pilih aksi->ubah biodata penduduk
3. Status kehamilan tidak dipilih
4. Muncul error

### Hasil yg diharapkan

Jika status kehamilan dikosongkan/tidak dipilih tetap bisa disimpan

### Tangkapan layar dan log error

![bug_edit_penduduk_status_hamil](https://user-images.githubusercontent.com/39736008/150497838-e422c541-1357-458c-88f4-7acd5dc89658.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

OpenSID 22.01-premium-beta02

**Comment by scqolbu24** [comment]
sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/640
