### ISSUE TITLE
[PREMIUM] Bug/error: Pencarian spesifik di menu calon pemilih tidak berjalan normal

### ISSUE THREAD

**Issue by mizwaruddin** [OpenSID/OpenSID#4756]
### Jelaskan error yg dialami

Saat akan melakukan pencarian spesifik pada menu calon pemilih, banyak pilihan yang tidak keluar pilihannya. Di sini sya ambil contoh pilihan jenis kelamin.

### Cara untuk mereplikasi errornya

1. Kependudukan->penduduk->calon pemilih
2. Pencarian spesifik
3. Banyak pilihan yang tidak keluar pilihannya

### Hasil yg diharapkan

Pilihan dalam pencarian spesifik tampil

### Tangkapan layar dan log error

![bug_dpt_pencarian_spesifik](https://user-images.githubusercontent.com/39736008/150498496-eae64518-373a-4206-a78b-9783a4d69afa.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

OpenSID 22.01-premium-beta02

**Comment by scqolbu24** [comment]
telah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/636
