### ISSUE TITLE
[PREMIUM] Bug/error: Terjadi selisih total penduduk di menu penduduk dan statistik kependudukan

### ISSUE THREAD

**Issue by mizwaruddin** [OpenSID/OpenSID#4757]
### Jelaskan error yg dialami

Terjadi selisih total penduduk di menu penduduk dan statistik kependudukan

### Cara untuk mereplikasi errornya

1. Statistik->statistik kependudukan
2. Pilih salah satu statistik (mis: ststistik pendidikan dalam KK)
3. Perhatikan jumlah total
4. Klik angka pada total jumlah
5. Tampil menu penduduk dengan jumlah yang berbeda dengan jumlah di statistik

### Hasil yg diharapkan

Jumlah antara di statistik dengan jumlah penduduk sama

### Tangkapan layar dan log error

![bug_jml_statistik_1](https://user-images.githubusercontent.com/39736008/150501423-deed154d-0d01-427d-bf37-3ddfddf9986e.png)
![bug_jml_statistik_2](https://user-images.githubusercontent.com/39736008/150501450-b6d6f589-26c5-4264-ab41-35254dacb13e.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

OpenSID 22.01-premium-beta02

**Comment by andifahruddinakas** [comment]
![statistik 1](https://user-images.githubusercontent.com/57283157/150670245-0362f74c-915d-4434-bcbd-4ebf05001df9.png)
![statistik 2](https://user-images.githubusercontent.com/57283157/150670242-97b497ec-5d75-4f76-8f9a-aef43d9d3a9d.png)

Saya cek tidak ada masalah.

Untuk total datanya ada semua penduduk_hidup (tampa ada session filter) atau kalau di akses langsung adalah penduduk/clear.


Pastikan tidak membukan modul lain yang memungkinkan terjadinya session yang bentrok.
