### ISSUE TITLE
[PREMIUM] Bug/error: Kolom "Ditandatangani oleh" dalam hasil "cetak dan unduh" arsip surat kosong

### ISSUE THREAD

**Issue by mizwaruddin** [OpenSID/OpenSID#4759]
### Jelaskan error yg dialami

Kolom "Ditandatangani oleh" dalam hasil "unduh" arsip surat kosong

### Cara untuk mereplikasi errornya

1. Layanan surat->Arsip Layanan->Unduh
2. Kolom Ditandatangani Oleh kosong

### Hasil yg diharapkan

Kolom ditandatangani oleh dalam hasil unduhan laporan arsip layanan surat terisi sebagaimana data yang dibuat.

### Tangkapan layar dan log error

![bug_unduh_arsip_surat](https://user-images.githubusercontent.com/39736008/150505627-b031e902-65bd-452f-a141-6304adea4eee.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

OpenSID 22.01-premium-beta02

**Comment by andifahruddinakas** [comment]
Cetak dan unduh 1 paket yang terikat, solusinya pun sama. Krn apa yg dicetak, itu jg yang akan diunduh.

Issue https://github.com/OpenSID/OpenSID/issues/4758 sy close.

**Comment by scqolbu24** [comment]
sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/638
