### ISSUE TITLE
[PREMIUM] Bug/error: Link/Url "Home" pada breadcrumb salah

### ISSUE THREAD

**Issue by mizwaruddin** [OpenSID/OpenSID#4760]
### Jelaskan error yg dialami

Ketika menekan tombol home pada breadcrumb di halaman panduan layanan surat, halaman yang terbuka bukan halaman home, melainkan halaman utama website (berputar.opensid.or.id)

### Cara untuk mereplikasi errornya

1. Layanan surat-> panduan
2. Tekan tombol home pada breadcrumb 
3. Halaman yang terbuka bukan halaman home (dashboard), melainkan halaman utama website

### Hasil yg diharapkan

Ketika menekan tombol home, halaman yang terbuka dalah halaman home/dashboard

### Tangkapan layar dan log error

![bug_panduan_home](https://user-images.githubusercontent.com/39736008/150506900-0fd48031-7bf5-462d-9067-edce7540a92e.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

OpenSID 22.01-premium-beta02

**Comment by FirlianiF** [comment]
Sudah masuk di rilis premium melalui PR https://github.com/OpenSID/premium/pull/634
