### ISSUE TITLE
[PREMIUM] Bug/error: Item yang digembok tidak muncul di cetak laporan pada menu Informasi Publik

### ISSUE THREAD

**Issue by mizwaruddin** [OpenSID/OpenSID#4761]
### Jelaskan error yg dialami

Item yang digembok tidak muncul di cetak laporan pada menu Informasi Publik

### Cara untuk mereplikasi errornya

1. Sekretariat -> informasi publik
2. Gembok salah satu item (misal: Formulir Pengajuan Keberatan Informasi)
3. Tekan tombol cetak -> isikan tahun 2019
4. Item tersebut tidak tampil di laporan

### Hasil yg diharapkan

Item yang digembok tetap tampil di laporan

### Tangkapan layar dan log error

![bug_info_publik_1](https://user-images.githubusercontent.com/39736008/150622364-01b55632-5b8c-44fb-98b5-b178761f0de8.png)
![bug_info_publik_2](https://user-images.githubusercontent.com/39736008/150622381-5494a210-54f9-4bc8-91ed-148f0cfa547e.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

OpenSID 22.01-premium-beta02

**Comment by eddieridwan** [comment]
Bung @mizwaruddin , memang pengertian gembok saat ini seperti itu. Yaitu dokumen yg digembok dianggap tidak aktif dan tidak ditampilkan di web maupun laporan.

Sekiranya ingin dibedakan, misalnya supaya laporan mengikut sertakan semua dokumen, maka ubah issue ini menjadi permintaan perubahan fitur.

**Comment by mizwaruddin** [comment]
Akan saya voting ke teman2 dulu, Bang.
