### ISSUE TITLE
[PREMIUM] Bug/error: Paginasi pada menu Buku Rekapitulasi Jumlah Penduduk tidak bekerja normal

### ISSUE THREAD

**Issue by mizwaruddin** [OpenSID/OpenSID#4764]
### Jelaskan error yg dialami

Paginasi pada menu Buku Rekapitulasi Jumlah Penduduk tidak bekerja normal. 

### Cara untuk mereplikasi errornya

1. Buku Administrasi Desa->Administrasi Penduduk->Buku Rekapitulasi Jumlah Penduduk
2. Total data tidak sesuai dengan jumlah data yang tampil
3. Jumlah halaman melebihi jumlah halaman semestinya.

### Hasil yg diharapkan

Total data dan halaman sesuai data yang ada.

### Tangkapan layar dan log error

![bug_buku_rekap_jml_penduduk_paginasi](https://user-images.githubusercontent.com/39736008/150623806-d3955947-72f0-46fe-bc85-4c269f01d66a.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

OpenSID 22.01-premium-beta02

**Comment by FirlianiF** [comment]
Sudah masuk di rilis premium melalui PR https://github.com/OpenSID/premium/pull/629
