### ISSUE TITLE
[PREMIUM] Bug/error: Pendidikan di buku kader pemberdayaan tidak sesuai dengan pendidikan di data penduduk

### ISSUE THREAD

**Issue by mizwaruddin** [OpenSID/OpenSID#4765]
### Jelaskan error yg dialami

Pendidikan di buku kader pemberdayaan tidak sesuai dengan pendidikan di data penduduk

### Cara untuk mereplikasi errornya

1. Buku administrasi desa->Administrasi pembangunan->Buku kader pemberdayaan masyarakat
2. Bandingkan pendidikan yang terletak di kolom PENDIDIKAN/KURSUS dengan pendidikan yang ada di data penduduk
3. Data pendidikan tidak sesuai

### Hasil yg diharapkan

Daa pendidikan di Buku kader pemberdayaan masyarakat dan data penduduk sama

### Tangkapan layar dan log error

![bug_buku_kader_1](https://user-images.githubusercontent.com/39736008/150624789-551b82c3-3acb-46f6-9b88-090f49df63e1.png)
![bug_buku_kader_2](https://user-images.githubusercontent.com/39736008/150624794-0d5fdc48-3292-4bc0-9891-edc3c9032879.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

OpenSID 22.01-premium-beta02

**Comment by scqolbu24** [comment]
sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/639
