### ISSUE TITLE
[PREMIUM] Bug/error: Muncul dua select pada bagian suku

### ISSUE THREAD

**Issue by mizwaruddin** [OpenSID/OpenSID#4766]
### Jelaskan error yg dialami

Muncul dua select pada bagian suku

### Cara untuk mereplikasi errornya

1. Kependudukan->penduduk
2. Tambah penduduk->penduduk masuk
3. Lihat pada bagian suku/etnis, muncul dua select, satu ada data, satu tidak berdata.

### Hasil yg diharapkan

Hanya muncul satu select di bagian suku/etnis

### Tangkapan layar dan log error

![bug_penduduk_etnis](https://user-images.githubusercontent.com/39736008/150660524-6b06c311-3e0f-45f3-974f-f4a4f4386d7d.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

OpenSID 22.01-premium-beta02

**Comment by andifahruddinakas** [comment]
Sudah ada laporan dan perbaikan mengenai ini tp belum digabungkan.

![suku](https://user-images.githubusercontent.com/57283157/150664873-6468b1d5-9a23-4468-a9e2-bfa8b302744d.png)
