### ISSUE TITLE
[PREMIUM] Permintaan fitur: Hanya tampilkan daftar Perangkat Desa yang aktif saat pilih Kepala Desa di Identitas Desa

### ISSUE THREAD

**Issue by mizwaruddin** [OpenSID/OpenSID#4767]
### Apa kekurangan yg ingin diatasi?

Perangkat Desa Tidak Aktif Masih Muncul dalam Pilihan Kepala Desa di Identitas Desa

### Jelaskan solusi yg diinginkan

Hanya tampilkan perangkat desa aktif dalam pilhan kepala desa di identitas desa

### Apakah ada alternatif lain

Dalam menu buku aparat pemerintah desa, khusus kepala desa berikan tanda (jabatan kepala desa) tertentu sehingga dalam hal-hal yang menyangkut kepala desa terdeteksi melalalui tanda tersebut.

### Untuk versi OpenSID mana

OpenSID 22.01-premium-beta02

**Comment by apidong** [comment]
sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/698

**Comment by mizwaruddin** [comment]
Masih belum berfungsi
