### ISSUE TITLE
[PREMIUM] Bug/error: Nama desa tidak tampil dalam hasil cetak/unduh di bagian tanda tangan "Wilayah Administratif"

### ISSUE THREAD

**Issue by mizwaruddin** [OpenSID/OpenSID#4768]
### Jelaskan error yg dialami

 Nama desa tidak tampil dalam hasil cetak/unduh di bagian tanda tangan "Wilayah Administratif"

### Cara untuk mereplikasi errornya

1. Info Desa->Wilayah Administratif
2. Cetak/Unduh
3. lihat pada bagian tanda tangan, hanya tampil kata desa. Untuk nama desa tidak tampil

### Hasil yg diharapkan

![bug_wilayah](https://user-images.githubusercontent.com/39736008/150661610-de8c5710-07f8-4c7e-8bde-c645d8771914.png)

### Tangkapan layar dan log error

Nama desa tampil dalam hasil cetak/unduh di bagian tanda tangan wilayah administratif

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

OpenSID 22.01-premium-beta02

**Comment by FirlianiF** [comment]
Sudah masuk di rilis premium melalui PR https://github.com/OpenSID/premium/pull/635
