### ISSUE TITLE
[PREMIUM Bug/error] Perbaiki validasi form dan modal input agar tidak duplikasi

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#4769]
### Jelaskan error yg dialami

Saat Meng-upload Dokumen Kependudukan pada Pilihan Data Penduduk Pilih Aksi-->Pilih Upload Dokumen, terjadi dua kali pemilihan data dokumen.

### Cara untuk mereplikasi errornya

1. Klik Detail Data Penduduk
2. Pilih Salah Satu Penduduk -->Pilih Tombol-->Pilih Aksi
3. Pilih Fitur --.Upload Dokumen Pendudu

![image](https://user-images.githubusercontent.com/64481641/150667519-a42155e4-904e-4fa3-8931-0fc0d6093f82.png)

### Hasil yg diharapkan

Untuk Meng-upload dokumen penduduk-->agar satu kali pilih langsung dapat dimpan..

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/64481641/150667475-96c0c0c2-74b2-4db4-b80d-45c3b0167963.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

 premium (v22.01-beta02 --> demo berputar

### Tema Yang Digunakan

default

### Informasi tambahan

Note

**Comment by FirlianiF** [comment]
Sudah masuk di rilis premium melalui PR https://github.com/OpenSID/premium/pull/637
