### ISSUE TITLE
[PREMIUM Bug/error] Double Form Impor Saat Mengimpor DATA SUPLEMEN 

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#4770]
### Jelaskan error yg dialami

Saat impor data Sumplemen terjadi 2x Pilih File Dokumen Import... pilih pertama tidak langsung menyimpan akan tetapi muncul lagi fomr pilih data setelah dipilih upload pertama.

### Cara untuk mereplikasi errornya

1. Buka Fitur Suplemen.
2. Buat Tambah Data Suplemen
3. Klik Tombol Impor Data

 
![image](https://user-images.githubusercontent.com/64481641/150667720-8652e72f-c7ca-43f2-aeea-faf1689a2125.png)

### Hasil yg diharapkan

Dokumen Impor Dapat Dipilih Sekali Pilih Langsung Data dapat disimpan

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/64481641/150667742-83f70d69-a250-43da-981b-5bee14c0a0d8.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

premium (v22.01-beta02 --> demo berputar

### Tema Yang Digunakan

default

### Informasi tambahan

Note

**Comment by andifahruddinakas** [comment]
Masalah yg sama dngan https://github.com/OpenSID/OpenSID/issues/4769

Akara masalah pemanggilan validasi yang berulang / duplikasi.
