### ISSUE TITLE
[PREMIUM Bug/error:] Pagenasi Halaman Website Pembanguna Terjadi Error/Kosong Bila List View Yang Ditampilkan lebih dari 10 Item 

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#4771]
### Jelaskan error yg dialami

Halalaman Paginasi pada pilihan Page/halaman 2 Kosong  atau Error Apabila Bila Item Pembangunan Yang ditampilkan lebih dari 10 Item......

![image](https://user-images.githubusercontent.com/64481641/150667887-1bb474d9-31e1-4257-bb0c-f7cd42be910f.png)

### Cara untuk mereplikasi errornya

1. Buka Halaman Website
2. Klik Halaman View Pembangunan.
3. Klik Page [2] [3] [4] dan seterusnya........

![image](https://user-images.githubusercontent.com/64481641/150667938-47dbeddf-c631-4616-86df-b061434e6090.png)

### Hasil yg diharapkan

Agar dapat menampil View Pembangunan seluruhnya Page by Page

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/64481641/150667979-4001e485-8f67-4a62-bc78-62e8d7813c67.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

premium (v22.01-beta02 --> demo berputar

### Tema Yang Digunakan

default

### Informasi tambahan

Note

**Comment by scqolbu24** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/642
