### ISSUE TITLE
[PREMIUAM Bug/error:] Form Tambah Data Anggota RTM->Kepala Rumah Tangga Pengganti Dari Kepala Rumah Tangga Sebelumnya Yg Berubah Status Dasar  

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#4772]
### Jelaskan error yg dialami

Kepala Rumah Tangga Berubah status dasar "Meninggal" tambah anggota rumah tangga Yang Kepala Rumah Tangga telah berganti ke Data Penduduk yang masih tinggal di rumah tangga tersebut untuk berikutnya—>tombol TAMBAH ANGGOTA RUMAH TANGGA dan tombol HAPUS DATA pada form rumah tangga tersebut tidak aktif, serta Nama Kepala Rumah Tangga dalam Form Tidak Tampil

### Cara untuk mereplikasi errornya

1. Buka Fitur Data Rumah Tangga
2. Pilih Salah Satu Data Rumah Tangga Yg Sudah Diganti Posisi dari Anggota Sebelumnya Menjadi Kepala Rumah Tangga (3 atau 6 bulan sebelumnya) menggantikan Kepala Rumah Tangga Sebelumnya Yang Telah berubaha Status Dasar Data Kependudukan Menjadi "Meninggal/Mati"

### Hasil yg diharapkan

Agar Form Rumah Tangga Yang Berganti Kepala Rumah Tangga dari Kepala Rumah Tangga Sebelumnya yang sudah Meninggal, form ini tetap bisa digunakan oleh Kepala Rumah Tangga atau Anggota dari Kepala Rumah Tangga Yang Status Dasarnya hidup.

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/64481641/150670270-51a214cb-6f93-4bcf-8bf9-42db5b568ca5.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Rilis Premium (v22.01-Rev02 Premium)

### Tema Yang Digunakan

default

### Informasi tambahan

Bagi Warga Kepala Rumah Tangga dengan tertanggal Laporan data atau Laporan Kejadian  antara  3 atau 6 bulan ke belakang....

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melalui pr https://github.com/OpenSID/premium/pull/641
