### ISSUE TITLE
[UMUM] Bug/error:  View Wibsite Zoom Lokasi Lapak Desa Tidak dapat di Zoom (Out/Close)

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#4773]
### Jelaskan error yg dialami

Lokasi Lapak Tidak dapat di Zoom baik dengan klik tanda [+] atau pun dengan cara menggulir mouse

### Cara untuk mereplikasi errornya

Buka Website Pilih Fitur Lapak --> Klik Lokasi atau Peta Lokasi

### Hasil yg diharapkan

Lokasi Lapak Agar dapat di Zoom diperbesar atau di perkecil, ada pilihan tampilan mode peta, baik [OpenStreetMap] maupun satelite

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/64481641/150672837-4e36d0d6-0c18-4a60-be76-f76c0010a183.png)

### Rilis Versi OpenSID

Rilis Umum

### Versi OpenSID

Rilis umum dev v22.01 Pasca

### Tema Yang Digunakan

default/klasik

### Informasi tambahan

Note

**Comment by andifahruddinakas** [comment]
Pak @Zoel-WB, cek versi Premium, apakah mengalami hal yg sama ???

**Comment by Zoel-WB** [comment]
> Pak @Zoel-WB, cek versi Premium, apakah mengalami hal yg sama ???

Premium Aman Pak @andifahruddinakas,

**Comment by andifahruddinakas** [comment]
> > Pak @Zoel-WB, cek versi Premium, apakah mengalami hal yg sama ???
> 
> Premium Aman Pak @andifahruddinakas,

Berarti sudah di perbaiki di permium yang akan datang.
