### ISSUE TITLE
[PREMIUM] Error 500 Setelah Menjalankan Perintah Kosongkan DataBase Bug/error: 

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#4774]
### Jelaskan error yg dialami

Setelah menjalan perintah kosongkan database system terjadi error 500

### Cara untuk mereplikasi errornya

Fitur  Pengaturan -> Pilih Database --> Pilih Kosongkan DataBase

### Hasil yg diharapkan

Supaya tidak terjadi error setelah pengosong database

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/64481641/150699664-b7b0a83c-85d3-4159-851f-1b9ae1100b59.png)

![image](https://user-images.githubusercontent.com/64481641/150699671-f2e3f429-b602-4546-9666-565ceec6079f.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Premium [v22.02 rev02 Tester]

### Tema Yang Digunakan

default

### Informasi tambahan

note

**Comment by andifahruddinakas** [comment]
Cek jg tabel yang lain.

**Comment by Zoel-WB** [comment]
> Cek jg tabel yang lain.

Sepertinya tabel lain aman pak, sudah saya cek dan periksa yg masih terisi data hanya pada tabel data default system saja.

**Comment by andifahruddinakas** [comment]
@scqolbu24, cek semua tabel referensi setelah melakukan pengosongan database dan lakukan migrasi ulang. Pastikan tabel referensi (bawaan opensid yg harus ada) tidak terhapus.

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melalui pr https://github.com/OpenSID/premium/pull/647
