### ISSUE TITLE
[PREMIUM] Bug/error: Pengelompokan Rumah Tangga Tersimpan Record Data Kosong yang ikut dihitung sebagai Rekap Jumlah Data Rumah Tangga 

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#4775]
### Jelaskan error yg dialami

Pengelompokan Rumah Tangga Tersimpan Record Data Kosong pada akhir (Baris Kosong) sehingga data kosong ini juga hitung menjadi Rekap Data, ada perbedaan jumlah data yg tampil di dasboard misal 200 data, saat data di unduh hanya terdapat 199 data.

### Cara untuk mereplikasi errornya

1. Lihat Tampilan Data Pada Dasboard.
2. Buka Fitur Rumah Tangga --> Browsing hingga ke bagian akhir data paling bawah atau unduh data

### Hasil yg diharapkan

Agar tidak ada rekaman rekord kosong di akhir record data.

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/64481641/150702124-da52523f-70cf-499e-9175-4f5a800716ae.png)

![image](https://user-images.githubusercontent.com/64481641/150702813-64f64833-594c-4bf8-8114-d3284e2ec486.png)

![image](https://user-images.githubusercontent.com/64481641/150702904-dea4ddd4-1beb-43d6-9130-bf0426d70305.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Premium (v22.01-Pasca Tester)

### Tema Yang Digunakan

default

**Comment by yogiperdana** [comment]
Telah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/648
