### ISSUE TITLE
[UMUM] Bug/error: Layanan Mandiri Belum Dapat Mengirim Pengajuan Permohonan Surat 

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#4776]
### Jelaskan error yg dialami

Layanan Mandiri Pada OpenSiD Umum Source Script dari Repo OpenSID Dev-V22.01 Pasca Belum Dapat Mengirim Pengajuan Permohonan Surat, Setelah isi permohona di masukkan dan dilengkapi semua persyaratan Klik Tombol [Isi Form] System Kembali ke Form permohonan melengkapi foermohonan seperti semula->ke form kirim permohonan.
 
![image](https://user-images.githubusercontent.com/64481641/150801149-12e78c33-4888-4524-8e2c-90edd10f30de.png)

### Cara untuk mereplikasi errornya

Pilih Layanan Mandiri --> Buat sebuah permohonan surat --Klik Tom [Isi Form]

### Hasil yg diharapkan

Sagar normal dan dapat digunakan

### Tangkapan layar dan log error

https://user-images.githubusercontent.com/64481641/150801480-e14e6a6c-0a6c-4087-83dc-450b7389ac17.mp4

### Rilis Versi OpenSID

Rilis Umum

### Versi OpenSID

OpenSID Dev V22.01 PASCA

### Tema Yang Digunakan

DEFAULT

### Informasi tambahan

Sudah 2 kali pengujian dan sudah pernah di perbaiki

**Comment by andifahruddinakas** [comment]
Silahkan cek https://demo.opensid.or.id/

**Comment by scqolbu24** [comment]
Pak @Zoel-WB  saya sudah mengecek dengan downlad Repo OpenSID Dev-V22.01 Pasca, berjalan normal, berikut dilampirkan videonya : 

https://user-images.githubusercontent.com/68048807/151305394-62093a92-d680-4a9b-b2e7-b6b70fa3a9b5.mp4

**Comment by scqolbu24** [comment]
sudah dicek di web demo https://demo.opensid.or.id/ juga normal, seperti berikut lampiran videonya:


https://user-images.githubusercontent.com/68048807/151307046-54903dbc-3e87-4d74-99b1-04c03cf32239.mp4

**Comment by Zoel-WB** [comment]
> sudah dicek di web demo https://demo.opensid.or.id/ juga normal, seperti berikut lampiran videonya:
> 
>  permohonan.surat-DEMO.mp4

Ini di laptop saya sudah 2 kali di install tidak dapat mengirim surat, baik di system Premium maun di system Umum, secara pasti tidak dapat saya pastikan apakah jalan atau tidak, yg lain pun setelah issue ini saya buat tak ada yg komen, mungkin saja tidak masalah, hanya di laptop saya barang kali, makanya saya sendiri tidak dapat memastikan untuk fitur ini secara konkrit.

**Comment by scqolbu24** [comment]
tadi saya sudah mencoba install ulang download dari Reponya, kemudian dijalankan aman

**Comment by scqolbu24** [comment]
Pak @andifahruddinakas juga sudah mencoba aman

**Comment by scqolbu24** [comment]
Untuk web demo berjalan normal, dan mohon ijin pak @Zoel-WB apakah bisa di close untuk issue ini?

**Comment by Zoel-WB** [comment]
> tadi saya sudah mencoba install ulang download dari Reponya, kemudian dijalankan aman

oke berarti aman pak, cuma dilaptop saya belum tahu apa masalahnya, malalah pembersiha cache dan sebagainya selalu saya lakukan.

**Comment by Zoel-WB** [comment]
Oke pak di Close saja, nanti bila bisa re-open lagi...

**Comment by scqolbu24** [comment]
baik pak, saya close saja untuk issue ini.

**Comment by eddieridwan** [comment]
Bung @scqolbu24 seperti kita bicarakan tadi, harap dilihat/diperiksa di laptop bung @Zoel-WB . Tuntaskan masalahnya

**Comment by andifahruddinakas** [comment]
Pindahkan `form_action` ke kontroller controller, bedakan jika tambah atau ubah.

**Comment by scqolbu24** [comment]
sudah diperbaiki melalui PR #677 [Perbaiki permohonan surat layanan mandiri ](https://github.com/OpenSID/premium/pull/677)
