### ISSUE TITLE
[UMUM] Bug/error: OpenSID-dev-v22.01 Pasca Logo Desa Belum Tampil Optomatis dari Logo Desa Sebelumnya Setelah Update Script

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#4777]
### Jelaskan error yg dialami

Saat Menjalankan Pertama Sekali setelah melalukan update atau mengganti script dengan Script OpenSID dev-v22.01 PASCA, logo desa tidak tampil secara otomasti dari logo yang sudah ada di system sebelumnya pasca update.

### Cara untuk mereplikasi errornya

Pasang/Ganti Scrip ke OpenSID dev-v22.01 pasca
Kemudian lakukan loading system

![Uploading image.png…]()

### Hasil yg diharapkan

Logo desa yang di ada dalam system sebelumnya agar dapat tampil kembali secara otomatis, tidak perlu upload ulangan setelah system di update.

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/64481641/150802836-382c86f4-9115-48d3-8d94-6341d233bc79.png)

![image](https://user-images.githubusercontent.com/64481641/150802866-1e82d708-c643-4fda-8675-2eb74bf63b79.png)

### Rilis Versi OpenSID

Rilis Umum

### Versi OpenSID

OpenSID Dev V22.01 PASCA

### Tema Yang Digunakan

DEFAULT

### Informasi tambahan

No commen

**Comment by andifahruddinakas** [comment]
Silahkan bersihkan cache.

**Comment by Zoel-WB** [comment]
Oke pak...., tapi sudah mencoba 2 kali, localhost dan di hosting, hasilnya sama... setelah diganti script dijalankan logo desanya hilang harus upload ulang...

**Comment by FirlianiF** [comment]
Sudah solved ya pak @Zoel-WB, issue saya close.

**Comment by Zoel-WB** [comment]
> Sudah solved ya pak @Zoel-WB, issue saya close.

Ya, Oke......
