### ISSUE TITLE
[premium]Bug/error: import rumah tangga selalu tertimpa

### ISSUE THREAD

**Issue by ridwan-opt** [OpenSID/OpenSID#4778]
### Jelaskan error yg dialami

Hasil import rumah tangga selalu tertimpa... Se

### Cara untuk mereplikasi errornya

.misal rtm RT 5 sudah sukses di import lalu melakukan import lagi rtm RT 6 sukses namun rtm RT 05 yang sudah berhasil di import tadi tertimpa (hilang) dan untuk penomoran sudah di pastikan berbeda antara kedua RT tersebut dan aturan format sudah mengikuti aturan pada contoh aturan import rtm

### Hasil yg diharapkan

Agar import rtm bisa di lakukan berkali2 maksutnya RT ke RT tidak sekaligus satu desa karna akan berat saat import

### Tangkapan layar dan log error

.

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

22.01premium Rev 2

### Tema Yang Digunakan

Denatra

**Comment by andifahruddinakas** [comment]
Silahkan disertakan contoh impor yang bisa digunakan agar bisa menduplikasi error ini.

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melalui pr https://github.com/OpenSID/premium/pull/652
