### ISSUE TITLE
[DEMO PREMIUM] Bug/error: Uji Coba Lapak Desa Setelah Imput Data Produk--.Simpan Error 500  

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#4779]
### Jelaskan error yg dialami

Lapak Desa setelah meng-imput salah satu produk saat di disimpan terjadi error 500

### Cara untuk mereplikasi errornya

Buka Fitur Lapak Desa
Pilih Tambah Data --> Masukkan Data sesuai dengan isi kolom2 Data -->Pilih Simpan

![image](https://user-images.githubusercontent.com/64481641/150959325-9bef285b-dcdc-4377-9c1f-018c395a6660.png)

![image](https://user-images.githubusercontent.com/64481641/150959360-c8100523-7876-4b81-8c76-36a526127253.png)

### Hasil yg diharapkan

Agak tidak terjadi error, dan dapat  menampung nilai harga s/d 12 dit atau lebih

![image](https://user-images.githubusercontent.com/64481641/150959763-4eeb0e0e-9133-41d1-aaa5-fa05ff4ad632.png)

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/64481641/150959287-02f2193c-d0c8-4716-b148-cce6798c1688.png)

![image](https://user-images.githubusercontent.com/64481641/150960183-894b02b9-5a5f-4b36-a6b3-268d5c1ca304.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Rilis Premium v22.01-Beto Demo Berputar

### Tema Yang Digunakan

default

### Informasi tambahan

No Comment

**Comment by andifahruddinakas** [comment]
Batas maksimal hanya 11 digit jika lebih akan error, jika yang diminta adalah penambahan panjang inputan yang disimpan maka silahkan buatkan issue terpisah. Issue ini hanya khusus untuk perbaikan validasi.

**Comment by yogiperdana** [comment]
Panjang data int 11 adalah maksimal 2147483648 dan minimal -2147483648. Setelah berdiskusi diputuskan panjang data yang ditetapkan pada validasi menjadi 2000000000

**Comment by scqolbu24** [comment]
sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/656
