### ISSUE TITLE
[PREMIUM] Bug/error: Nama desa tidak tampil pada cetak laporan vaksin

### ISSUE THREAD

**Issue by mizwaruddin** [OpenSID/OpenSID#4780]
### Jelaskan error yg dialami

Nama desa tidak tampil pada cetak laporan vaksin

### Cara untuk mereplikasi errornya

1. Siaga Covid-19->vaksin->laporan penduduk->cetak/unduh
2. Nama desa tidak tampil dalam laporan

### Hasil yg diharapkan

Nama desa tampil dalam laporan

### Tangkapan layar dan log error

![bug_vaksin_laporan](https://user-images.githubusercontent.com/39736008/150988575-eaac9ca0-4ec4-43cc-88a2-3bcb3f0f6ad5.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

OpenSID 22.01-premium-beta03

**Comment by scqolbu24** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/657
