### ISSUE TITLE
[PREMIUM} Bug/error: Penyesuaian Tempat Tanda Tangan Otomatis Sesuai Dengan Pilihan Pada Pengaturan Aplikasi Print Buku Inventaris dan Kekayaan Desa

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#4781]
### Jelaskan error yg dialami

Hasil Print Out Buku Inventaris dan Kekayaan Desa, Tempat tanda tangan belum otomatis seperti pada Setting Pengaturan Aplikasi 

### Cara untuk mereplikasi errornya

1. Buka Fitur Buku Administrasi Desa
2. Pilih Administrasi Umum
3. Pilih Buku Iventasris dan Kekayaan Desa
4. Pilih Cetak 

### Hasil yg diharapkan

Agar Plihan Nama Desa Pada Tempat Tangan sama dengan Pengaturan->Aplikasi ->Sebutan  

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/64481641/150990541-9cd163bb-49c3-4d2e-8d38-3f37194a9976.png)

SEHARUS-NYA

![image](https://user-images.githubusercontent.com/64481641/150990621-2dd53d83-2c50-4693-b47d-a22c1cbf9d04.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Rilis v22.01-Beta03 premium

### Tema Yang Digunakan

DeNatra

### Informasi tambahan

No

**Comment by andifahruddinakas** [comment]
Issue ini sebatan perbaikan penulisan desa sesuai pengaturan aplikasi. Untuk perubahan format cetak silahkan buat issue baru permintaan fitur.

**Comment by yogiperdana** [comment]
Telah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/654
