### ISSUE TITLE
[PREMIUM] Bug/error: Nama Kabupaten, Kecamatan, dan Desa Tidak Tampil dalam Kop Laporan Wilayah Administratif

### ISSUE THREAD

**Issue by mizwaruddin** [OpenSID/OpenSID#4782]
### Jelaskan error yg dialami

Nama Kabupaten, Kecamatan, dan Desa Tidak Tampil dalam Kop Laporan Wilayah Administratif

### Cara untuk mereplikasi errornya

1. Info Desa -> Wilayah Administratif -> Cetak
2. Pada bagian Kop Laporan: nama Kabupaten, Kecamatan, dan Desa tidak tampil 

### Hasil yg diharapkan

Nama Kabupaten, Kecamatan, dan Desa tampil dalam Kop Laporan Wilayah Administratif

### Tangkapan layar dan log error

![bug_wilayah_laporan](https://user-images.githubusercontent.com/39736008/150990749-64615de9-2621-4762-85d8-401d7dfe496f.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

OpenSID 22.01-premium-beta03

**Comment by Zoel-WB** [comment]
Ada 2 kali tercetak  Judul : Baris Pertama judul terisi, bari 3 judul, hanya Tulisn Kabupaten, Kecamatan, Desa
 
![image](https://user-images.githubusercontent.com/64481641/151046910-26f74d9c-c589-4e41-93b5-2cf9b0baa000.png)

**Comment by andifahruddinakas** [comment]
> Ada 2 kali tercetak Judul : Baris Pertama judul terisi, bari 3 judul, hanya Tulisn Kabupaten, Kecamatan, Desa
> 
> ![image](https://user-images.githubusercontent.com/64481641/151046910-26f74d9c-c589-4e41-93b5-2cf9b0baa000.png)

Ini duplikasi, kyaknya salah 1 harus di hapus.

**Comment by scqolbu24** [comment]
yang dihapus baris pertama atau baris ketiga ?

**Comment by andifahruddinakas** [comment]
> yang dihapus baris pertama atau baris ketiga ?

hapus baris 3

**Comment by scqolbu24** [comment]
siap

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melalui pr https://github.com/OpenSID/premium/pull/650
