### ISSUE TITLE
[PREMIUM] Bug/error: Field Nama Tidak Memanggil Nilai dalam Database saat Edit Data Anggota Lembaga

### ISSUE THREAD

**Issue by mizwaruddin** [OpenSID/OpenSID#4783]
### Jelaskan error yg dialami

Field Nama Tidak Memanggil Nilai dalam Database saat Edit Data Anggota Lembaga

### Cara untuk mereplikasi errornya

1. Info Desa -> Lembaga Desa 
2. Klik tombol "Rincian Lembaga" pada salah satu lembaga -> Ubah Anggota
3. Pada field nama kosong

### Hasil yg diharapkan

Fiel nama terisi sesuai data yang sudah tersimpan sebelumnya

### Tangkapan layar dan log error

![bug_lembaga_edit](https://user-images.githubusercontent.com/39736008/150993381-2e02f6ae-d242-45fe-aa52-e838d1fee89f.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

OpenSID 22.01-premium-beta03

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melalui pr https://github.com/OpenSID/premium/pull/653
