### ISSUE TITLE
[PREMIUM] Bug/error: Field Nama Tidak Memanggil Nilai dalam Database saat Edit Data Anggota Kelompok

### ISSUE THREAD

**Issue by mizwaruddin** [OpenSID/OpenSID#4785]
### Jelaskan error yg dialami

Field Nama Tidak Memanggil Nilai dalam Database saat Edit Data Anggota Kelompok

### Cara untuk mereplikasi errornya

1. Kependudukan -> Kelompok
2. Klik tombol "Rincian Kelompok" pada salah satu lembaga -> Ubah Anggota
3. Pada field nama kosong

### Hasil yg diharapkan

Fiel nama terisi sesuai data yang sudah tersimpan sebelumnya

### Tangkapan layar dan log error

![bug_kelompok_edit](https://user-images.githubusercontent.com/39736008/151000346-9a0485d9-cd8f-41e7-933b-6a98d8c316e4.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

OpenSID 22.01-premium-beta03

**Comment by andifahruddinakas** [comment]
Lemabaga dan kelompok menggunakan tabel dan view yang sama. https://github.com/OpenSID/OpenSID/issues/4785

Jika ada error (scr umum) di kelompok, akan terjadi juga di lembaga.
