### ISSUE TITLE
[UMUM] Bug/error: Peta Wilayah Desa Tidak Tampil di Website Maupun di Fitur Pemetaan 

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#4787]
### Jelaskan error yg dialami

Setelah dibuat Peta Wilayah Desa Tidak ditampilkan di Website Maupun di Fitur Pemetaan-->pilih Peta, menggunakan Database default dari data_contoh_awal. 

### Cara untuk mereplikasi errornya

Membuat Peta
1. Pilih Info Desa ---> Pilih Identitas Desa-->Lokasi Kantor Desa --->Tentukan Koordinat Kantor Desa
2. Pilih Peta Wilayah Desa --> Kosongkan Default --> Buat Peta Baru. 
![image](https://user-images.githubusercontent.com/64481641/151013832-f5911b48-4188-4392-86d4-6609b179faa2.png)

![image](https://user-images.githubusercontent.com/64481641/151013925-6a842409-6123-467d-8f1e-3528ecd9e2de.png)

Menampilkan Peta
Test (1). Buka Fitur Pemetaan --> Pilih Peta
![image](https://user-images.githubusercontent.com/64481641/151014526-cf791613-1040-4ebd-8d97-d0a132ddc41c.png)

Test (2). Buka Halaman Web --> Pilih Peta

![image](https://user-images.githubusercontent.com/64481641/151014811-cfd81298-ab0a-44c1-9b69-2a1a0a4e5b5a.png)

### Hasil yg diharapkan

Agar Normal Peta Wilayah Desa dapat ditampilkan pada tempat2 yg ada pemetaan sesuai dengan defaultnya

### Tangkapan layar dan log error

Include -->Cara untuk mereplikasi errornya

### Rilis Versi OpenSID

Rilis Umum

### Versi OpenSID

Rilis umum v22.01-Pasca/Beta

### Tema Yang Digunakan

Default

### Informasi tambahan

Eksekusi menggunakan Original-->dan menjalankan pada Localhost

**Comment by andifahruddinakas** [comment]
Cek di versi premium jg.

**Comment by andifahruddinakas** [comment]
Cek web demo.

https://demo.opensid.or.id/peta

https://demo.opensid.or.id/gis
