### ISSUE TITLE
[PREMIUM] Bug/error: Cetak Kartu Rumah Tangga Untuk Kepala Rumah Tangga Penggati 

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#4790]
### Jelaskan error yg dialami

Kepala Rumah Tangga Berubah status berganti kepada yg Masih Hidup yang menggantikan Kepala Rumah Tangga Sebelumnya Telah Berubah Status dasar menjadi "Meninggal" dan digantikan. akan tetapi masalah ini juga berpengaruh sampai ke cetak kartu rumah rumah tangga, dimana Atas Nama Kartu Keluarga dan Alamat Letak Rumah Tangga ikut kosong tidak ditampilkan/tercetak di lembar cetak kartu rumah tangga.

### Cara untuk mereplikasi errornya

1. Klik Fitur Rumah Tangga
2. Pada List Daftar Pengelompokkan Rumah Tangga Pilih Salah Satu Kepala Rumah Tangga Yg Telah Menggantikan Posisi Kepala Rumah Tangga Sebelumnya Yg Telah berubah Status Dasar "Meningga"
3. Klik Kartu Rumah Tangga

![image](https://user-images.githubusercontent.com/64481641/151080499-55f1b6de-3a97-4f84-b58e-192a9914d01e.png)

### Hasil yg diharapkan

Supaya Kartu Rumah Tangga yg telah Berganti Kepala Rumah Tanggal Kepada Anggota Rumah Tangga Lain yg masih berstatus Hidup dapat di cetak normal seperti kartu rumah tangga warga lainnya

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/64481641/151080912-be7de10f-cec0-41d1-b49c-0fa30a0902bd.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Rilis Premium v22.01-Beta03

### Tema Yang Digunakan

DeNatra

### Informasi tambahan

Harapan Untuk Penduduk dengan Status Kepala Keluarga atau Kepala Rumah Tangga yang status dasarnya telah berubah menjadi "mati" digantikan atau dialihkan kepada pengganti yg masih hidup agar tidak menjadi hambatan bagi administrasinya, karena di desa agak sulit bila kepala keluarga yg meninggal walaupun aturannya harus mengganti Kartu Keluarga Baru bagi yg masih ada dalam KK tersebut, di desa sangat jarang terjadi tertip administrasi yg normal, semuanya pada kenyataan adalah upnormal.

Takutnya tidak terlacak hingga program bantuan, saat di ambil data sudah tidak terdata padahal yg bersangkutan sebagai penerima program, apalagi di desa sering permintaan nama-nama yg berkaitan dengan fakir miskin dan kemiskinan untuk dimasukkan ke dalam program2 bantuan simultan seperti permintaan data-data dari Baitulmal dan lainnya.

Kebetulan saya lagi membuat data permintaan dari baitulmal untuk pendataan mereka, sehingga banyak menemukan data-data yg tidak aktif akibat Kepala Keluarganya berubah status dasar.

**Comment by andifahruddinakas** [comment]
Ini dipilih ulang kepala Rumah Tangganya biar yang lama terganti.

**Comment by Zoel-WB** [comment]
Kepala Rumah Tangga sudah terganti entah beberapa bulan atau tahunan pak....

**Comment by andifahruddinakas** [comment]
> Kepala Rumah Tangga sudah terganti entah beberapa bulan atau tahunan pak....

di pilih ulang saja pak, biar bisa menyesuaikan perubahan dari laporan kemarin.

**Comment by Zoel-WB** [comment]
![image](https://user-images.githubusercontent.com/64481641/151091531-465e0cb9-d9cb-4400-826a-019c24003aff.png)

![image](https://user-images.githubusercontent.com/64481641/151091557-9c1f1ef3-3f8c-4126-980a-97821bce9f95.png)

![image](https://user-images.githubusercontent.com/64481641/151091775-e4792d7f-5c5e-4e2c-a237-76ea0cb17bb8.png)

**Comment by andifahruddinakas** [comment]
cek dan duplikasi di https://berputar.opensid.or.id/
