### ISSUE TITLE
[PREMIUM] Bug/error: Format impor data penduduk tidak berjalan normal

### ISSUE THREAD

**Issue by mizwaruddin** [OpenSID/OpenSID#4791]
### Jelaskan error yg dialami

Saat melakukan impor data penduduk menggunakan file contoh dari gagal disimpan karena format tidak sesuai.

### Cara untuk mereplikasi errornya

1. Pengaturan -> Database -> Impro Database
2. Isikan data di file impor (excel sesuai dengan format terlampir)
3. Terjadi gagal impor

### Hasil yg diharapkan

Format contoh impor disesuaikan sehingga tidak terjadi gagal impor

### Tangkapan layar dan log error

Lampiran file impor: 
[FormatImportExcel (6).xlsx](https://github.com/OpenSID/OpenSID/files/7938246/FormatImportExcel.6.xlsx)

Keterangan gagal impor:
![bug_impor_penduduk_1](https://user-images.githubusercontent.com/39736008/151085916-be0ea293-d065-4250-b1e5-da8b87851df6.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

OpenSID 22.01-premium-beta03

**Comment by andifahruddinakas** [comment]
Pak @mizwaruddin, sy coba impor menggunakan file yg dilampirkan dan tidak ada masalah.

![asuransi2](https://user-images.githubusercontent.com/57283157/151088251-2e41bab3-f85c-476f-a21d-19cec8b9e32e.png)
![impor1](https://user-images.githubusercontent.com/57283157/151088254-268db64d-4431-41f1-8e31-8b2693726d84.png)
