### ISSUE TITLE
[PREMIUM] Bug/error: Perbaiki simpan data penduduk jika terjadi duplikasi tag id card.

### ISSUE THREAD

**Issue by mizwaruddin** [OpenSID/OpenSID#4792]
### Jelaskan error yg dialami

Muncul error 500 saat impor data penduduk jika tag id ada yang sama

### Cara untuk mereplikasi errornya

1. Pengaturan -> Database -> Impor Database
2. Masukkan data tag id ganda pada format impor
3. Muncul keterangan error 500

### Hasil yg diharapkan

Jika ada tag id yang sama, tampilkan keterangan gagal impor sebagaimana jika terjadi kesalahan pada kolom lain (misal kode pendidikan salah, dsb)

### Tangkapan layar dan log error

![bug_impor_penduduk_2](https://user-images.githubusercontent.com/39736008/151086656-72dbedcb-b15c-4e95-b9ba-2453ae309b75.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

OpenSID 22.01-premium-beta03

**Comment by yogiperdana** [comment]
Telah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/655
