### ISSUE TITLE
[PREMIUM] Bug/error: Error 500 Input Data Pembangunan Alokasi Anggaran 10 digit atau ada sebab lain 

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#4793]
### Jelaskan error yg dialami

Input Data Pembangunan dengan nilai anggaran 1 milayar saat disimpan terjadi error 500

### Cara untuk mereplikasi errornya

1. Buka Fitur Pembanguan
2. Pilih Tambah Data --. Input Data Pembangunan dengan nilai budget 1 milyar
3. Klik Simpan

![image](https://user-images.githubusercontent.com/64481641/151089330-5e1a1cec-4c12-4c1f-8e19-7a94637acacb.png)

### Hasil yg diharapkan

Agar normal dan dapat menginput data bila memang git lebih dari 10 digit atau ada notif peringatan

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/64481641/151089386-2315394b-1549-4f01-82b5-cc0fe96084ba.png)

![image](https://user-images.githubusercontent.com/64481641/151089455-a3641609-6260-4678-b3d6-d3cadeaaf792.png)

Kolom Input Nilai Juga Terkunci
![image](https://user-images.githubusercontent.com/64481641/151090921-9f976649-4b2e-44c3-9dae-3d1241ebcb29.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Rilis v22.01-Beta03 Premium

### Tema Yang Digunakan

Default

### Informasi tambahan

Noted

**Comment by andifahruddinakas** [comment]
Di cek, ulang pak. perbaikan kemarin anggaran = pemeritah + provinsi + Kab / Kota + Swadaya.

![anggaran](https://user-images.githubusercontent.com/57283157/151090260-c0e8ccf1-a23f-440f-afe0-fae38814233f.png)

**Comment by yogiperdana** [comment]
Panjang data int 11 adalah maksimal 2147483648 dan minimal -2147483648. Setelah berdiskusi diputuskan panjang data yang ditetapkan pada validasi menjadi 2000000000 yang berlaku untuk kolom sumber_biaya_pemerintah, sumber_biaya_provinsi, sumber_biaya_kab/kota, dan sumber_biaya_swadaya. Lebih lanjut hasil diskusi sementara menetapkan penghapusan kolom anggaran dan sumber biaya total dihapuskan agar tidak ada batas maksimal dari total penjumlahan dari 4 kolom sumber biaya sebelumnya

**Comment by Zoel-WB** [comment]
> Di cek, ulang pak. perbaikan kemarin anggaran = pemeritah + provinsi + Kab / Kota + Swadaya.
> 
> ![anggaran](https://user-images.githubusercontent.com/57283157/151090260-c0e8ccf1-a23f-440f-afe0-fae38814233f.png)

1. Apakah tidak mempengaruhi data anggaran yang sudah ada sebelumnya dengan perpindahan kolom dari kolom Anggaran ke Kolom Sumber Biaya Pemerintah, karena sebagian desa telah selesai mengimput untuk data fitur ini dari semenjak fitur ini ditambah di opensid.

2. Pembiayan dengan sumber-sumber pembiayaan lain yang bukan dari pemerintah, misalnya dari pendapatan asli desa, kemudian bila anggaran pembiayan yang di danai secara langsung dari pembiayan pemerintah pusat akan tetapi tidak melalui Dana Desa.

3. Karena tidak ada kolom lain tersedia yg general, setelah kolom Anggaran di tiadakan ,yang mewakili untuk di input-kan anggaran selain dari kolom-kolom Pembiayaan dari Pemerintah dan swakelola, untuk jenis swakelola berbeda untuk istilahnya tersendiri yang khusus.

![image](https://user-images.githubusercontent.com/64481641/151299277-2eae36fe-5f09-4132-b74a-0a5adbf8b8ac.png)

**Comment by yogiperdana** [comment]
Validasi kolom sudah ditambahkan. Untuk penambahan kolom sumber biaya lain mohon dibuatkan issue yang baru terkait penambahan fitur ya pak @Zoel-WB

**Comment by Zoel-WB** [comment]
> Validasi kolom sudah ditambahkan. Untuk penambahan kolom sumber biaya lain mohon dibuatkan issue yang baru terkait penambahan fitur ya pak @Zoel-WB

Baik Pak, nanti saya ajukan untuk issue tambah kolom bidang pembiayaan dari sumber lainnya selain yg sudah baku pada fitur pembangunan sudah ada saat ini, issue #4819

**Comment by scqolbu24** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/689
