### ISSUE TITLE
Bug/error: Hak akses modul pembangunan

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#4794]
### Jelaskan error yg dialami

Hak akses modul pembangunan tidak sesuai dengan fungsinya

### Cara untuk mereplikasi errornya

![pembangunan](https://user-images.githubusercontent.com/57283157/151151546-0d22ee82-b70d-4447-9b7b-4b88d273669f.png)

### Hasil yg diharapkan

Hak akses pembangunan normal

### Tangkapan layar dan log error

tidak ada

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

22.01

### Tema Yang Digunakan

bawaan

### Informasi tambahan

tidak ada

**Comment by agusterm** [comment]
![photo_2022-01-27_22-42-22](https://user-images.githubusercontent.com/87739467/151384769-893a5778-efe3-4e93-9c30-eb4c7d82dcaa.jpg)

Tombol tambah data sangat diperlukan dalam hak akses khusus modul pembangunan. untuk memudahkan dalam penginputan data sesuai dengan tupoksinya

**Comment by andifahruddinakas** [comment]
> ![photo_2022-01-27_22-42-22](https://user-images.githubusercontent.com/87739467/151384769-893a5778-efe3-4e93-9c30-eb4c7d82dcaa.jpg)
> 
> Tombol tambah data sangat diperlukan dalam hak akses khusus modul pembangunan. untuk memudahkan dalam penginputan data sesuai dengan tupoksinya

Ya, sudah termasuk di issue ini mengenai hak akses modul pembangunan.

**Comment by agusterm** [comment]
mantap, teima kasih bang

**Comment by scqolbu24** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/660
