### ISSUE TITLE
Bug/error: Tambah produk

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#4796]
### Jelaskan error yg dialami

Terjadi Gagal Tampil Produk saat setelah simpan produk tanpa isi Potongan Harga Produk.

<img width="960" alt="screenshot_290" src="https://user-images.githubusercontent.com/46939846/151316110-2d360d9f-0094-4807-9c03-3d70d244e17e.png">

### Cara untuk mereplikasi errornya

Masuk menu lapak, tambah produk. lalu isi kolom (kecuali kolom Potongan Harga Produk tidak perlu diisi) dan simpan. maka tabel akan error.

### Hasil yg diharapkan

Normal sebagaimana mestinya.

### Tangkapan layar dan log error

<img width="960" alt="screenshot_289" src="https://user-images.githubusercontent.com/46939846/151316044-3e5db070-990c-4656-bc96-3cbffb470be9.png">

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.02-premium

### Tema Yang Digunakan

Seluruhnya

### Informasi tambahan

Adanya default angka pada kolom Potongan Harga Produk saat potongan persen,.

Untuk potongan nominal sudah 0.

dan akan gagal input jika tidak diisi angka.

**Comment by scqolbu24** [comment]
sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/663
