### ISSUE TITLE
Bug/error: Lat/Lng di lokasi kantor desa dapat diisi nilai tidak valid sehingga menyebabkan semua peta tidak tampil

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#4797]
### Jelaskan error yg dialami

Lat/Lng di lokasi kantor desa dapat diisi nilai tidak valid sehingga menyebabkan semua peta wilayah tidak tampil

### Cara untuk mereplikasi errornya

1. Pergi ke halaman Info Desa > Identitas Desa > Lokasi Kantor Desa
2. Isi lat/lng tidak valid
3. Simpan
4. Periksa beberapa peta wilayah administratif
5. Terlihat semua peta tidak tampil tanpa penjelasan apapun

![image](https://user-images.githubusercontent.com/249563/151541247-55b53fc8-0420-4079-8ef8-f3605d4c5700.png)

### Hasil yg diharapkan

1. Sediakan validasi supaya tidak bisa menyimpan nilai lat/lng tidak valid
2. Jika terdeteksi lokasi kantor desa atau wilayah desa yg tidak valid pada waktu membuka peta wilayah administratif, tampilkan pesan bahwa lokasi kantor desa atau peta wilayah desa salah dan perlu diperbaiki. Tampilkan nilai lat/lng atau path yg bermasalah.

### Tangkapan layar dan log error

Tersedia di atas

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.01-premium

### Tema Yang Digunakan

natra

**Comment by andifahruddinakas** [comment]
http://jsfiddle.net/nRha8/2/

**Comment by scqolbu24** [comment]
apabila yang diinputkan -000.483832804795249 sudah ada validasinya, sehingga sudah aman tidak bisa menyimpan

<img width="943" alt="validasi peta-ok" src="https://user-images.githubusercontent.com/68048807/151664908-c18fcd60-2487-43ec-8005-fbcbd732fe38.PNG">

Namun ketika diinputkan -00.483832804795249 belum ada validasinya, sehingga masih terjadi error ketika disimpan seperti gambar berikut:

<img width="945" alt="validasi peta" src="https://user-images.githubusercontent.com/68048807/151664923-d13448e0-dd94-4f5e-8953-d01a2fe20337.PNG">
