### ISSUE TITLE
[PREMIUM] Nama bulan tampil angka pada laporan kelompok rentan

### ISSUE THREAD

**Issue by mizwaruddin** [OpenSID/OpenSID#4798]
### Jelaskan error yg dialami

Nama bulan tampil angka pada laporan kelompok rentan

### Cara untuk mereplikasi errornya

1. Statistik -> Laporan Kelompok Rentan -> Cetak
2. Nama bulan tampil angka--yang seharusnya nama bulan--

### Hasil yg diharapkan

Nama bulan tampil bukan sebagai angka

### Tangkapan layar dan log error

![bug_rentan_laporan](https://user-images.githubusercontent.com/39736008/151568520-8310332c-80b0-4374-adb6-10947aa0c79a.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

OpenSID 22.01-premium-beta03

**Comment by andifahruddinakas** [comment]
Desain awal modul ini menggunakan bulan angka dan tidak bisa diganti/dipilih.

![laporan 1](https://user-images.githubusercontent.com/57283157/151569384-436b1d76-7f2e-4bf4-bcb6-c7b3e014b8d8.png)

```php
	<?php $bln = date('m'); ?>
								<label class="col-sm-2 col-md-2 control-label" for="laporan">Lap. Bulan</label>
								<div class="col-sm-4 col-md-1">
									<input type="text" class="form-control input-sm" value="<?= $bln?>" disabled/></input>
								</div>
```

Bulan dari laporan di ambil dari data modul tsb.

**Comment by agungsugiarto** [comment]
Sudah di fitru premium melalui pr https://github.com/OpenSID/premium/pull/943

**Comment by andifahruddinakas** [comment]
Belum digabungkan PR https://github.com/OpenSID/premium/pull/943 mas @agungsugiarto
