### ISSUE TITLE
[PREMIUM] Bug/error: Perbaiki agar tidak bisa ubah status hubungan dalam keluarga menjadi kepala keluarga jika kepala keluarga sudah meninggal.

### ISSUE THREAD

**Issue by mizwaruddin** [OpenSID/OpenSID#4799]
### Jelaskan error yg dialami

Jumlah KK bernilai negatif dalam laporan bulanan

### Cara untuk mereplikasi errornya

https://t.me/c/1238304761/24505:
Yg saya lakukan: stlh kepala keluarga meninggal, ubah status meninggal. Istri naik jabatan jd kepala KK. Klo KK tsb mengajukan perubahan KK, baru pecah KK.

1. Statistik -> Laporan Bulanan
2. Jumlah KK dalam laporan bulanan bernilai negatif

### Hasil yg diharapkan

Laporan bulanan sesuai data riil

### Tangkapan layar dan log error

![bug_laporan_bulanan](https://user-images.githubusercontent.com/39736008/151571237-4de0d655-dd01-4a1a-bb52-a3fad5aacb6a.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

OpenSID 22.01-premium-beta03

**Comment by eddieridwan** [comment]
Masalahnya di langkah yg dilakukan @mizwaruddin :

`stlh kepala keluarga meninggal, ubah status meninggal. Istri naik jabatan jd kepala KK. Klo KK tsb mengajukan perubahan KK, baru pecah KK.`

Seharusnya nomor KK melekat pada kepala keluarga yg asli. Jadi setelah kepala keluarga meninggal, kartu keluarga (Nomor KK) tersebut TIDAK BOLEH digunakan dengan orang lain sebagai kepala keluarga pengganti. Yaitu TIDAK BOLEH menaikkan istrinya menjadi kepala keluarga. Menurut aturan Dukcapil, perlu membuat kartu keluarga baru. 

Jadinya untuk issue ini yg perlu dilakukan adalah:
1. Untuk keluarga yg status dasar kepala keluarga tidak lagi `hidup`, pastikan tidak ada yg bisa menjadi kepala keluarga baru.
2. Untuk keluarga yg status dasar kepala keluarga tidak lagi `hidup`, pastikan aksi yg diperbolehkan hanya untuk pecah KK.

Catatan: kalau belum sempat membuat kartu keluarga baru ke Dukcapil, ingat OpenSID sudah menyediakan fitur untuk membuat keluarga dengan Nomor KK Sementara. Yg nanti bisa disesuaikan setelah memperoleh kartu keluarga baru.

Jadi langkah yg seharusnya dilakukan setelah kepala keluarga meninggal adalah sbb:

1. Ubah status kepala keluarga menjadi `mati`
2. Pecah seluruh anggota keluarga yg ditinggalkan
3. Buat keluarga baru menggunakan nomor KK sementara, dengan istri sebagai kepala keluarga
4. Tambahkan anggota keluarga lainnya ke keluarga baru tersebut

@scqolbu24 @agungsugiarto : mohon langkah2 ini dimasukkan ke panduan, dan diberi tanda perhatian khusus, karena merupakan masalah dan kebingungan bagi pengguna yg berulang-ulang. 

Untuk memudahkan, sudah dibuatkan permintaan perubahan fitur https://github.com/OpenSID/OpenSID/issues/4805.

**Comment by apidong** [comment]
pak @mizwaruddin , tidak bisa duplikasi error.
yang saya lakukan.
1. ubah status dasar kepala keluarga menjadi mati
2. ubah data istri , field "Hubungan Dalam Keluarga" menjadi kepala keluarga.
3. ubah informasi kartu keluarga tersebut.
4. pecah KK
dengan langkah seperti itu tidak membuat kolom kk menjadi negatif

sedangkan untuk fitur https://github.com/OpenSID/OpenSID/issues/4805 sudah tersedia.

**Comment by eddieridwan** [comment]
@apidong errornya terjadi setelah langkah (3) sebelum langkah (4), yang tidak tentu kapan dikerjakan. Mohon lihat apa yg perlu diterapkan di komentar https://github.com/OpenSID/OpenSID/issues/4799#issuecomment-1024769243. Yaitu, selain panduan, kerjakan:

1. Untuk keluarga yg status dasar kepala keluarga tidak lagi hidup, pastikan tidak ada yg bisa menjadi kepala keluarga baru.
2. Untuk keluarga yg status dasar kepala keluarga tidak lagi hidup, pastikan aksi yg diperbolehkan hanya untuk pecah KK.

**Comment by apidong** [comment]
> @apidong errornya terjadi setelah langkah (3) sebelum langkah (4), yang tidak tentu kapan dikerjakan. Mohon lihat apa yg perlu diterapkan di komentar [#4799 (comment)](https://github.com/OpenSID/OpenSID/issues/4799#issuecomment-1024769243). Yaitu, selain panduan, kerjakan:
> 
> 1. Untuk keluarga yg status dasar kepala keluarga tidak lagi hidup, pastikan tidak ada yg bisa menjadi kepala keluarga baru.
> 2. Untuk keluarga yg status dasar kepala keluarga tidak lagi hidup, pastikan aksi yg diperbolehkan hanya untuk pecah KK.

untuk nomor 2 sudah ada.
![image](https://user-images.githubusercontent.com/20056421/152940361-2d60829b-3a6b-456f-8efa-dee135d80c58.png)

untuk nomor 1, di modul **kartu keluarga** sudah tidak bisa dilakukan. 
tapi masih ada celah di modul kependudukan, yaitu dengan cara, mengubah data penduduk dari anggota keluarga tersebut, pada field "Hubungan Dalam Keluarga" diubah menjadi kepala keluarga.  maka nomor KK tersebut bisa aktif kembali
apakah ini dibuat issue terpisah?

**Comment by eddieridwan** [comment]
@apidong mohon perbaiki di issue ini. Bukan terpisah.
