### ISSUE TITLE
[PREMIUM] Bug/error: Error 500 saat tambah mutasi inventaris

### ISSUE THREAD

**Issue by mizwaruddin** [OpenSID/OpenSID#4802]
### Jelaskan error yg dialami

Error 500 saat tambah mutasi inventaris

### Cara untuk mereplikasi errornya

1. Sekretaris -> Inventaris
2. Pilih salah satu kategori
3. Klik tombol mutasi pada salah satu jenis inventaris
4. Isi form mutasi
5. Simpan -> Error 500

### Hasil yg diharapkan

Proses mutasi barang inventaris berjalan dengan lancar

### Tangkapan layar dan log error

![bug_inventaris_mutasi](https://user-images.githubusercontent.com/39736008/151578026-4bcc04e2-5626-484b-af53-9e0c3cb10c83.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

OpenSID 22.01-premium-beta03

**Comment by andifahruddinakas** [comment]
Saya test tidak ada masalah.

id tidak memliki nilia default, krn seharusnya id digenerate otomatis saat disimpan (bukan dari inputan).
cek tabel tsb, apakah struktur sudah sesuai dengan database bawwan. kolom id memiliki auto_increment.
![inventaris](https://user-images.githubusercontent.com/57283157/151648168-01da3bbb-bc7c-49e2-ae17-a4f401a48731.png)
