### ISSUE TITLE
Permintaan fitur: No HP diambil data penduduk saat buat surat layanan mandiri

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#4803]
### Apa kekurangan yg ingin diatasi?

No HP selalu harus di masukkan ulang saat buat surat dilayanan mandiri.

### Jelaskan solusi yg diinginkan

No HP diambil data penduduk saat buat surat layanan mandiri dan bisa disesuaikan.

### Apakah ada alternatif lain

Tidak ada.

### Untuk versi OpenSID mana

v22.01-premium

### Informasi tambahan

Tidak ada

**Comment by FirlianiF** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/695
