### ISSUE TITLE
Permintaan fitur: Setelah kepala keluarga meninggal, mudahkan proses membuat keluarga baru bagi yg ditinggal

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#4805]
### Apa kekurangan yg ingin diatasi?

Saat ini, proses yg perlu dilakukan setelah kepala keluarga meninggal adalah sbb:

1. Ubah status kepala keluarga menjadi mati
2. Pecah seluruh anggota keluarga yg ditinggalkan
3. Buat keluarga baru menggunakan nomor KK sementara, dengan istri sebagai kepala keluarga
4. Tambahkan anggota keluarga lainnya ke keluarga baru tersebut

Langkah2 ini menyulitkan dan membingungkan pengguna. Diperlukan cara yg lebih sederhana
 

### Jelaskan solusi yg diinginkan

Pada keluarga yg status kepala keluarganya tidak `hidup`, sediakan tombol aksi `Pecah ke keluarga baru`. Tombol ini akan: 

1. Menyediakan pilihan kepala keluarga dari anggota keluarga yg ditinggalkan
2. Membuat keluarga baru menggunakan nomor kartu keluarga sementara (jika belum ada nomor KK baru dari Dukcapil)
3. Memindahkan seluruh anggota keluarga dari keluarga lama ke keluarga baru
4. Mencatat nomor KK lama sebagai nomor KK sebelumnya pada semua anggota keluarga yg dipindahkan 

Pastikan pencatatan ke log_penduduk dan log_keluarga benar.

### Apakah ada alternatif lain

Tidak ada

### Untuk versi OpenSID mana

pasca v22.01-premium

### Informasi tambahan

Lihat issue https://github.com/OpenSID/OpenSID/issues/4799

**Comment by muhtar-coder** [comment]
Ya.. lebih praktis...

**Comment by eddieridwan** [comment]
@apidong ini bisa ditutup kalau sudah ada di rilis

**Comment by apidong** [comment]
fitur ini sudah ada di rilis.
![image (1)](https://user-images.githubusercontent.com/20056421/152908446-ed704fc4-d540-420f-ad2a-3b3de29496ea.png)
