### ISSUE TITLE
[Layanan Mandiri] Lupa/reset PIN kirim melalui email

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/OpenSID#4806]
### Apa kekurangan yg ingin diatasi?

saat ini Layanan Fitur Lupa PIN baru tersedia kirim melalui telegram yang sudah diverifikasi, untuk akun yang sudah disediakan yang dapat diverifikasi adalah telegram dan email. 
Fitur Lupa PIN dikirim melalui email bisa menjadi alternatif bagi pengguna yang sudah terbiasa menggunakan email.

### Jelaskan solusi yg diinginkan

Ada pilihan Lupa PIN kirim melalui Email

### Untuk versi OpenSID mana

v22.03-premium

### Informasi tambahan

Merupakan lanjutan dari issue [#4557 [Layanan Mandiri] Lupa/reset PIN](https://github.com/OpenSID/OpenSID/issues/4557) 
yang sudah dirilis pada v22.01-premium.

**Comment by FirlianiF** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/758
