### ISSUE TITLE
Tidak ada menu hapus penduduk di menu import database

### ISSUE THREAD

**Issue by pemdeslinggapura** [OpenSID/OpenSID#4808]
Pada menu Impor Database biasanya ada menu hapus penduduk di menu import database. di Versi 22.01-premium-rev02 tidak ada
![Screenshot 2022-01-30 110834](https://user-images.githubusercontent.com/89450861/151686251-f8148389-0529-4e48-997f-f980eaca0961.jpg)

**Comment by eddieridwan** [comment]
@pemdeslinggapura , mohon lihat https://github.com/OpenSID/OpenSID/wiki/Impor-Data-Penduduk-Desa

`(Penting: fitur hapus sebelum impor hanya dapat dilakukan pada pertama kali mengimpor data penduduk).`

Karena fitur impor penduduk baru tidak dimaksudkan untuk dilakukan berulang-ulang. Sekali saja. 

Issue ini akan ditutup. Jika ada hal tambahan, silakan buka lagi.

**Comment by pemdeslinggapura** [comment]
Kebetulan kemarin sebelum pakai premium v.22.01 saya salah import data penduduk, bayak yg salah tgl lahirnya. Kalo sudah begini harus gmna dong mas?

**Comment by eddieridwan** [comment]
Pada impor data penduduk, data dengan NIK sama akan ditimpa. Jadi impor saja tanpa harus menghapus data yg sudah ada.

**Comment by pemdeslinggapura** [comment]
Saya nyoba import penduduk, di versi 22.1 sampai 21.12 tanggal lahir semua berubah jadi 1 januari 1970, saya coba import di versi umum tgl lahirnya normal
