### ISSUE TITLE
Bug/error: Tidak Bisa Mengubah Info Desa | Localhost

### ISSUE THREAD

**Issue by tanjungberulak** [OpenSID/OpenSID#4809]
### Jelaskan error yg dialami

Kami mencoba untuk menjalankan SID di localhost. 
Tahap instalasi selesai dan pengosongan database juga sudah.
Tahap mengubah info desa terkendala karena form desa tidak memunculkan nama desa pilihan.

### Cara untuk mereplikasi errornya

1. Masuk ke admin
2. Pilih menu 'Info Desa'
3. Pilih menu 'Identitas Desa'

### Hasil yg diharapkan

Bisa Memasukan Nama Desa Secara Manual, atau pilihan2 nama desa se indonesia

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/98678823/151687112-9b8c2a8c-c49d-472b-b8cd-061aeed335cc.png)

### Rilis Versi OpenSID

Rilis Umum

### Versi OpenSID

22.0.1

### Tema Yang Digunakan

bawaan

**Comment by andifahruddinakas** [comment]
Cek https://github.com/OpenSID/OpenSID/wiki/Identitas-Desa

**Comment by tanjungberulak** [comment]
Kami telah mencoba menambah bari kode Traking nama desa di file desa/config/config.php, namun masih gagal.
KEdua, kami lakukan Ganti file yang ada di folder donjo-app/views/identitas_desa/form.php dengan file https://github.com/OpenSID/OpenSID/files/7798636/form.zip Akhirnya Berhasil.

**Comment by eddieridwan** [comment]
@andifahruddinakas @tanjungberulak , sebagai catatan, saya telah perbaiki panduan di https://github.com/OpenSID/OpenSID/wiki/Identitas-Desa#tidak-bisa-mengubah-nama-desa, supaya lebih jelas apa saja yg perlu diperiksa jika masalah ini terjadi.

Tetapi mengenai perubahan script file donjo-app/views/identitas_desa/form.php yg dilaporkan bung @tanjungberulak, mohon bung @andifahruddinakas tuntaskan. Apakah ini sudah diperbaiki di pra-rilis v22.02?

**Comment by andifahruddinakas** [comment]
> @andifahruddinakas @tanjungberulak , sebagai catatan, saya telah perbaiki panduan di https://github.com/OpenSID/OpenSID/wiki/Identitas-Desa#tidak-bisa-mengubah-nama-desa, supaya lebih jelas apa saja yg perlu diperiksa jika masalah ini terjadi.
> 
> Tetapi mengenai perubahan script file donjo-app/views/identitas_desa/form.php yg dilaporkan bung @tanjungberulak, mohon bung @andifahruddinakas tuntaskan. Apakah ini sudah diperbaiki di pra-rilis v22.02?

Sudah diperbaiki.
