### ISSUE TITLE
[PREMIUM 22.01 BETA03] Permintaan Pengecekkan Rekapitulasi Kelompok Rumah Tangga Pada Dasboard

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#4814]
### Jelaskan error yg dialami

Tampilan Rekapitulasi yang ditampilkan pada dasboard seperti ada sedikit gangguan setelah adanya perubahan status dasar pada pada salah satu kepala  keluarga yg merangkap kepala rumah tangga menjadi status dasar PINDAH, tampilan rekap di dasboard diawal loading masih menampilkan jumlah rekap sebelumnya, setelah direpresh atau klik list detail, lalu kembali lagi ke dasboard baru muncul rekap jumlah yg sebenarnya.

### Cara untuk mereplikasi errornya

Rubah salah satu status dasar Kepala Keluarga yg menjadi Kepala Rumah Tangga menjadi Pindah, kemudian kembali Dasboard

### Hasil yg diharapkan

Agar dapat normal tidak sendatan

### Tangkapan layar dan log error

Terkadang Rekap pada dasboarg kemli ke Rekap Awal sebelum status dasar Kepala Keluarga yg merangkap kepala rumah di rubah, Misal jumlah rekap awal nilai 29, setelah di ambil 2 Kepala Rumah tangga beserta seluruh anggota rumah tangga dirubah status dasar menjadi pindah, pada dasboard tetap masih menampilkan nil 29 di saat system dijalankan kembali beberapa waktu kemudian, terkadang muncul nilai kosong nili 0.

![image](https://user-images.githubusercontent.com/64481641/151697321-0e7825c0-4085-4b51-888f-14288d770207.png)

setelah di represh atau klik list detail, klik kembali ke dasboard nilai yg sebenarnya baru tampil di dasaboard

 

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Rilis premium (v22.01-beta03)?

### Tema Yang Digunakan

DeNatra

### Informasi tambahan

Noted

**Comment by andifahruddinakas** [comment]
Ini terkait filter kelompok aktif dan tidak aktif, desain awal tidak dibuat demikian (data dihitung keseluruhan kelompok). Terkait issue ini, solusi : 
1. Ganti ketua kelompok dengan penduduk yang masih hidup.
2. Sediakan kondisi status kelompok (aktif/tidak aktif) sama halnya degan modul penduduk, keluarga, rtm. (Silahkan buat issuenya)

**Comment by Zoel-WB** [comment]
Oke pak, utk informasi tambahan kejadian ini timbul karena adanya perubahan status dasar Pindah utk seluruh keluarga/pindah semua satu keluarga/rumah tangga.

**Comment by andifahruddinakas** [comment]
> Oke pak, utk informasi tambahan kejadian ini timbul karena adanya perubahan status dasar Pindah utk seluruh keluarga/pindah semua satu keluarga/rumah tangga.

ya, makanya perlu ada filte status kelompok aktif atau tidak sama halnya dengan penduduk, keluarga atau rtm jika keluarga sudah menunggal, pindah atau lainnya. Data yang ditampilkan nantinya, kelompok yang aktif saja.

**Comment by Zoel-WB** [comment]
Oke Pak, berarti saya buat issue untuk filter aktif pada fitur rtm

**Comment by andifahruddinakas** [comment]
> Oke Pak, berarti saya buat issue untuk filter aktif pada fitur rtm

ya.

**Comment by andifahruddinakas** [comment]
Sudah digabung melalui PR https://github.com/OpenSID/premium/pull/702
