### ISSUE TITLE
[PREMIUM]Bug/error: Tidak Dapat Menyimpan Data Setelah di Edit Form Master Analisis > Analisis Keluarga

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#4817]
### Jelaskan error yg dialami

Tidak Dapat Menyimpan Data Setelah di Edit Form Master Analisis > Analisis Keluarga

### Cara untuk mereplikasi errornya

1. Buka Fitur Analisis-->Master Analisis
2. Pilih Analisis Keluarga
3. Masukkan Beberapa data
4. Setelah di simpan > buka salah data untuk mengedit pada ->Kategori Kepemilikan Rumah atau Penghasilan Perbulan
5. Lalu Simpan Kembali > Pilih Laporan Analisi->Laporan Hasil Klasifikasi--> Data tidak berubah tetap view tampilan awal data disimpan. 
![image](https://user-images.githubusercontent.com/64481641/151748674-8135dc4c-c2e3-43b1-9f6c-3dd46f9dda0e.png)

![image](https://user-images.githubusercontent.com/64481641/151748843-35dbece1-dff1-42f3-9e45-c1cdbc61ecfa.png)

### Hasil yg diharapkan

Data yg dimasukkan dalam analisis bila ada kesalahan agar dapat dikoreksi/diedit  kembali dan dapat disimpan seperti saat data awal dimasukkan. 

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/64481641/151748819-9b27a912-d700-4a31-b5e8-e478ebaf5780.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Premium (v22.01-Beta03)

### Tema Yang Digunakan

default

### Informasi tambahan

Noted

**Comment by yogiperdana** [comment]
Telah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/707
