### ISSUE TITLE
Bug/error: padding/margin pada demo umum vs premium

### ISSUE THREAD

**Issue by totoprayogo1916** [OpenSID/OpenSID#4818]
### Jelaskan error yg dialami

padding / margin di tema Natra berbeda?

https://berputar.opensid.or.id/
![image](https://user-images.githubusercontent.com/2387514/151750165-931e592f-1493-4a8d-ac69-857cf392054a.png)

https://demo.opensid.or.id/
![image](https://user-images.githubusercontent.com/2387514/151750117-0f5ffc39-efea-48d4-82d6-92e7ff9430ed.png)

### Cara untuk mereplikasi errornya

akses kedua DEMO dari Premium & umum
https://berputar.opensid.or.id/
https://demo.opensid.or.id/

### Hasil yg diharapkan

Jika keduanya menggunakan template yang sama, semestinya hasilnya juga sama

### Tangkapan layar dan log error

lihat atas

### Rilis Versi OpenSID

Rilis Umum

### Versi OpenSID

*

### Tema Yang Digunakan

Natra 4.5

**Comment by andifahruddinakas** [comment]
Pinmdahkan ke https://github.com/OpenSID/tema-natra

**Comment by scqolbu24** [comment]
issue ini di close dan dipindahkan ke issue pada tema natra https://github.com/OpenSID/tema-natra/issues/88

**Comment by totoprayogo1916** [comment]
sebenarnya ada caranya utnuk transfer issue.
![image](https://user-images.githubusercontent.com/2387514/153090119-49942e76-6c2f-453b-be5f-6be98fb19b4b.png)

cc: @scqolbu24

**Comment by scqolbu24** [comment]
> sebenarnya ada caranya utnuk transfer issue. ![image](https://user-images.githubusercontent.com/2387514/153090119-49942e76-6c2f-453b-be5f-6be98fb19b4b.png)
> 
> cc: @scqolbu24

siap, terimakasih informasinya.
