### ISSUE TITLE
[PREMIUM] Keluarga/Kepala Keluarga Berubah status dasar Pindah Seluruh Keluarga Terdapat Dalam Laporan Hasil Klasifikasi Analisis Keluarga  

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#4820]
### Jelaskan error yg dialami

Keluarga/Kepala yang telah Berubah status dasar menjadi Pindah atau Pindah Seluruh Keluarga-nya Terdapat dan muncul kembali di Dalam Laporan Hasil Klasifikasi Analisis Keluarga.

### Cara untuk mereplikasi errornya

1. Pilih Fitur Analisis -->Master Analisis -->Pilih Analisis Keluarga
2. Input Semua Data
3. Masuk ke Fitur Penduduk Pilih Data Penduduk dengan Posisi Kepala Keluarga.
4. Rubah Status Dasar Menjadi Pindah.
5. Buka Kembali -> Analisis -->Master Analisis -->Pilih Analisis Keluarga
6. Pilih Laporan->Laporan Hasil Klasifikasi->Masukkan Pencarian No. KK yg sudah berubah status.

### Hasil yg diharapkan

Agar Keluarga yg sudah berubah status pindah keluarga keluarga dari desa, tidak dimunculkan lagi dalam data analisis

### Tangkapan layar dan log error

Salah Satu Data Yg Sudah berubah Status Dasar Pindah atau Kembali Ke Desa Asalnya
![image](https://user-images.githubusercontent.com/64481641/151793924-2a5300e3-fb74-4dec-9fb2-8cdd644efe51.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

 Premium (v22.01-Beta03)

### Tema Yang Digunakan

default

### Informasi tambahan
Ditahun atau bulan yg sama setelah analisis keluarga di-input, kemudian Keluarga berubah status dasar Pindah...
Permohonan Tambah/Include pada Issue #4817

**Comment by yogiperdana** [comment]
Telah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/718
