### ISSUE TITLE
[PREMIUM] Data Penduduk/Kepala Keluarga Yg Berubah status dasar Masih Muncul di Program Bantuan 

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#4821]
### Jelaskan error yg dialami

Data Penduduk/Kepala Keluarga Yg Berubah status dasar "Mati" Masih Muncul di Program Bantuan pada tahun yang sama dengan adanya perubahan status dasar, akan tetapi nama-nya masih terdaftar sebagai penerima program bantuan 

### Cara untuk mereplikasi errornya

1. Rubah Status Dasar Salah Satu Data Penduduk/Kepala KK yg terdaftar sebagai penerima bantuan tahun berjalan

### Hasil yg diharapkan

Agar nama penduduk/kepala keluarga yg telah berubah status dasar supaya tidak tampil lagi sebagai penerima program bantuan ditahun berjalan (tahun yang sama) sesuai dengan masa pendataan penerima bantuan dan data kebetulan salah satu calon penerima program bantuan berubah status dasar menjadi pindah/mati/hilang.

### Tangkapan layar dan log error
![image](https://user-images.githubusercontent.com/64481641/151865561-0f700604-7473-42de-a2ae-5debbd033bfa.png)

![image](https://user-images.githubusercontent.com/64481641/151862173-8a404553-e312-415e-9a35-4b2a180b99e4.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

 Premium v22.02

### Tema Yang Digunakan

default

### Informasi tambahan

Notetd

**Comment by scqolbu24** [comment]
sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/722
