### ISSUE TITLE
Bug/error: info media sosial tidak muncul di halaman utama

### ISSUE THREAD

**Issue by yogiperdana** [OpenSID/OpenSID#4825]
### Jelaskan error yg dialami

Info media sosial tidak muncul di halaman utama

### Cara untuk mereplikasi errornya

1. Pergi ke halaman utama
2. Lihat bagian info media sosial

### Hasil yg diharapkan

Media sosial tampil seperti seharusnya

### Tangkapan layar dan log error

![medsos](https://user-images.githubusercontent.com/14155050/152118521-9b3ecc85-5ff9-4efc-8031-a59416d80c37.JPG)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.02-premium

### Tema Yang Digunakan

Natra

### Informasi tambahan

Fitur ini berjalan dengan baik pada versi umum (v22.02)

![medsos2](https://user-images.githubusercontent.com/14155050/152118712-2cf7d9aa-85a0-415c-b25d-de0b716db0a3.JPG)

**Comment by scqolbu24** [comment]
sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/690
