### ISSUE TITLE
Bug/error: kolom asuransi dan no asuransi tidak terdowload di unduh export database xlsx dan import database dengan format xlsx muncuk kode tidak dikenal

### ISSUE THREAD

**Issue by Wiliyantoro** [OpenSID/OpenSID#4826]
### Jelaskan error yg dialami

1. saat ingin mengeksporrt database dalam bentuk .xlsx di Pengaturan -> Database -> Unduh Export .xlsx dalam file exelnya belum terunduh untuk kolom asuransi dan no asuransi.

2. saat melakukan import database dalam format xlsx terjadi erorr
   1. Kode Hamil 2 Tidak dikenal
   2. Kode ktp_el 3 tidak dikenal

### Cara untuk mereplikasi errornya

1. kolom asuransi dan no asuransi tidak terdonwload

error untuk import xlsx
1. 2) kode hamil 2 tidak dikenal
2. 87) kode ktp_el 3 tidak dikenal

### Hasil yg diharapkan

kedepannya dapat diperbaiki untuk penambahan kolom asuransi dan no asuransi di file hasil export (.xlsx) untuk keperluan export dan import database / data desa

### Tangkapan layar dan log error

![laporan issue asuransi](https://user-images.githubusercontent.com/44520382/152132839-11d11862-1d9e-477c-ae21-6cf00df2afec.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.02-premium

### Tema Yang Digunakan

Denatra v.5.1

**Comment by yogiperdana** [comment]
Saat ini untuk nilai ktp_el terdiri dari 2 jenis, yaitu nilai 1 merepresentasikan belum dan nilai 2 merepresentasikan sudah mempunyai ktp_el

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melalui pr https://github.com/OpenSID/premium/pull/697
