### ISSUE TITLE
[PREMIUM] Layanan Mandiri Belum Dapat Masuk Dengan E-Ktp dan Agak Kesulitan Pengoperasian Di Android

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#4828]
### Jelaskan error yg dialami

1. Layanan mandiri -> login tidak dapat masuk dengan e-ktp
2. Saat memilih login dengan e-ktp layar Layanan Mandir masih menampilkan kolom isian tag id card dan kolom input PIN
3. Layanan Mandiri agak kesulitan Pengoprasian pada Android dan tampilan layar tidak beraturan

### Cara untuk mereplikasi errornya

Buka Layanan Mandiri -> Pilih Masuk Menggunakan E-KTP

### Hasil yg diharapkan

Supaya Normal Kembali sebagaimana fungsi-nya dan fitur yg disediakan di Layanan Mandiri dapat bekerja dengan baik

### Tangkapan layar dan log error

Tampak Layar Login dengan EKTP

![image](https://user-images.githubusercontent.com/64481641/152216656-4adc85d3-d96d-4940-b0b5-d78623bfe7d3.png)

Tampilan Layar Pada Android  Tidak Beraturan

![image](https://user-images.githubusercontent.com/64481641/152217203-5ca914fa-2064-4886-a30e-df147aa12c3f.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

 Premium v22.02

### Tema Yang Digunakan

default

### Informasi tambahan

tidak ada

**Comment by yogiperdana** [comment]
Telah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/724
