### ISSUE TITLE
[premium] Statistik Halaman Artikel  Peta Pada Website Mengalami Gangguan Saat Ingin Ditampilkan

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#4829]
### Jelaskan error yg dialami

1. Statistik Halaman Artikel  Peta Pada Website Mengalami Gangguan -> Statistik muncul sebentar, lalu tiba2 hilang
2. Pilihan Berikut-nya Sudah Cacet —->tidak dapat lagi dipilih apapun

### Cara untuk mereplikasi errornya

1. Buka Fitur Halaman Peta Pada Website
2. Pilih Peta Wilayah Desa, Dusun RT/RW
3. Klik Pada Wilayah yang dipilih -->Pilih Pilihan Statistik yang Ingin di Tampilkan

### Hasil yg diharapkan

Supaya normal dan berfungsi semua pilihan fitur yang ada dalam tampilan peta

### Tangkapan layar dan log error

hanya sekali pilih ->sekali ditampilkan (hanya berkedip)->lalu hilang->kemudian macet —->tidak dapat lagi dipilih apapun

![image](https://user-images.githubusercontent.com/64481641/152218801-a26cb54b-cfe8-4181-b80a-b787b387278f.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Premium v22.02

### Tema Yang Digunakan

DeNatra 5.1 dan Tema Default

### Informasi tambahan

Include

**Comment by agungsugiarto** [comment]
Pak @Zoel-WB saya tidak menemukan masalah yg dimaksud di tema bawaan. Issue ini saya close karena terkait dengan tema luar
cc: pak @ariandii

**Comment by ariandii** [comment]
Kolom Halaman Peta bukan bawaan dari Tema.

 Itu terjadi karena ada bentrok, yang biasa saya lakukan:
 
buka file donjo-app/views/gis/penduduk_gis.php
lalu hapus baris:
`<link rel="stylesheet" href="<?= base_url()?>assets/bootstrap/css/bootstrap.min.css" media="screen" type="text/css" />`

agar bisa buka statistik penduduk di peta.

**Comment by andifahruddinakas** [comment]
> Kolom Halaman Peta bukan bawaan dari Tema.
> 
> Itu terjadi karena ada bentrok, yang biasa saya lakukan:
> 
> buka file donjo-app/views/gis/penduduk_gis.php lalu hapus baris: `<link rel="stylesheet" href="<?= base_url()?>assets/bootstrap/css/bootstrap.min.css" media="screen" type="text/css" />`
> 
> agar bisa buka statistik penduduk di peta.

silahkan buatkan isuue untuk memindahkn halaman statis untuk website (front) ke masing2 tema (berdiri sendiri). Krn tiap tema menggunakan asset yang berbeda.
