### ISSUE TITLE
[PREMIUM] Kirim Pengajuan Surat Layanan Mandiri Erro 500

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#4830]
### Jelaskan error yg dialami

Saat Klik Tombol Kirim->Setelah Semua Keperluan Keterangan Surat Dimasukkan, terjadi Error 500, Hal ini Tidak Terjadi Pada Demo Berputar.... 

### Cara untuk mereplikasi errornya

1. Buka Layanan Mandiri
2. Buat Surat -.Lengakapi Semua Keterangan Surat -> Form->Masuk Form Kirim
3. Lengkapi Keperluan Keterangan
4. Klik Kirim

### Hasil yg diharapkan

Normal dan Berfungsi

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/64481641/152225952-444e3a89-d26e-4648-9f74-e15656f495d7.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Premium v22.02

### Tema Yang Digunakan

Default

### Informasi tambahan

Pada Demo Berputar-.Lancar->Tidak Terjadi Error

**Comment by yogiperdana** [comment]
Duplikat dengan issue https://github.com/OpenSID/OpenSID/issues/4881
