### ISSUE TITLE
Permintaan fitur: menggantikan tema klasik dengan tema esensi

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#4831]
### Apa kekurangan yg ingin diatasi?

Tema esensi telah siap, tapi belum digabung ke OpenSID untuk menggantikan tema klasik

### Jelaskan solusi yg diinginkan

Ganti tema klasik dengan tema esensi sebagai tema bawaan OpenSID

### Apakah ada alternatif lain

Tidak ada

### Untuk versi OpenSID mana

v22.02-premium

### Informasi tambahan

Perlu menyesuaikan tema natra untuk halaman2 yg sebelumnya bergantung pada tema klasik.

**Comment by apidong** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/694
