### ISSUE TITLE
Bug/error: Tambah Grup Pengguna Baru

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/OpenSID#4832]
### Jelaskan error yg dialami

Pada saat tambah  Grup pengguna dan belum ada yang diceklist, kemudian di klik tombol simpan , maka akan terjadi error.

### Cara untuk mereplikasi errornya

1. Pergi ke Modul Pengaturan
2. Pilih Pengguna
3. Pilih Pengaturan Grup
4. Klik Tombol Tambah Grup Baru
5. Klik Tombol Simpan tanpa mengisi ceklist apapun di Form Grup Pengguna

### Hasil yg diharapkan

ada validasi atau pemberitahuan untuk pengisian ceklist terlebih dahulu.

### Tangkapan layar dan log error

<img width="686" alt="Error Penambahan grup" src="https://user-images.githubusercontent.com/68048807/152283547-40a3472f-0d1f-4931-9188-2b8d21ad8f52.PNG">

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.02-premium

### Tema Yang Digunakan

natra

### Informasi tambahan

-

**Comment by yogiperdana** [comment]
Telah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/708
