### ISSUE TITLE
Sediakan pemeriksaan keabsahan data pada waktu update (seperti NIK duplikat, No KK > 16, tgl 9, email duplikat, dsbnya)

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#4834]
Untuk mengatasi database desa yg menjadi rancu karena berbagai hal yg telah diketahui, seperti:

1. data yg diisi yg menyalahi aturan yg baru, seperti tgl 0, NIK ganda, email ganda, atau batas panjang isian suatu kolom
2. kehilangan view atau autoincrement yang terjadi pada waktu melakukan ekspor/impor database menggunakan Phpmyadmin dengan setting yg keliru
3. tabel yg terhapus pada saat menggunakan fitur kosongkan database, yang seharusnya tidak ikut terhapus.

Alat bantu ini dapat dijalankan kapan saja, dan tidak harus sebagai bagian dari proses update. Misalnya, jika desa mengalami masalah dan menemukan adanya kekurangan tabel data. 

Perhatikan bahwa alat bantu ini hanya untuk kasus2 yg sering dilaporkan, dan di mana secara umum diketahui apa yg menyebabkan masalah ybs.

**Comment by eddieridwan** [comment]
Tahap awal diterapkan dengan skema sebagai berikut.

Periksa akan otomatis dibuka pada saat ada database exception (500). Dan harus login khusus dulu — dibatasi hanya bagi grup admin. Masalah yg terdeteksi diperbaiki, dan migrasi diulangi. Kalau masih ada masalah susulan (exception), otomatis ke periksa lagi.

![login-periksa](https://user-images.githubusercontent.com/249563/153709526-9daccb3d-6d0e-45af-8e36-170bfce0a38e.jpg)
![perbaiki-1](https://user-images.githubusercontent.com/249563/153709531-d087d586-9c45-4238-b85a-dd94dede058d.jpg)
![perbaiki-2](https://user-images.githubusercontent.com/249563/153709534-2b8a0fc7-33a3-4828-85a5-64d19625513d.jpg)

Bagi masalah yg tidak ada exceptionnya, seperti migrasi email unik di 22.02, maka di modul periksa harus dideteksi secara langsung, dengan masuk ke Periksa secara manual.

Contoh data desa berisi error: 
[contoh-acak-cugung-ada-error.sql.zip](https://github.com/OpenSID/OpenSID/files/8053261/contoh-acak-cugung-ada-error.sql.zip)

**Comment by andifahruddinakas** [comment]
Sudah digabung melalui PR https://github.com/OpenSID/premium/pull/739
