### ISSUE TITLE
Permintaan fitur: buatkan sebuah pengaturan untuk mengaktifkan / non aktifkan modul tte

### ISSUE THREAD

**Issue by yogiperdana** [OpenSID/OpenSID#4835]
Untuk memenuhi uji kelengkapan sebagai syarat PKS
----------------------------------------------------
**Apa kekurangan yg ingin diatasi?**
- Menambahkan Logo BSRE untuk ditampilkan di frontend hal ini selain memenuhi uji kelengkapan syarat PKS juga syarat integrasi BSRE API untuk kedepannya karena mencantukan logo BSRE adalah suatu kewajiban jika ingin integrasi.

**Pencapaian yang di harapkan** 
- Untuk Referensi Bisa ditampilkan seperti gambar berikut ini : 

![Image](https://user-images.githubusercontent.com/59082428/177141435-cf2ac042-06f0-4575-9065-55edc29580be.jpg)

Bisa ditampilkan di bagian footer.

**Jelaskan solusi yg diinginkan**
- Sebagai referensi bisa di tambahkan di menu Pengaturan -> Aplikasi (jika memungkinkan juga bisa ditambahkan aktif & non-aktif (defaultnya aktif * maka akan tampil) jika tidak ingin di tampilkan bisa klik untuk di non-aktifkan.

![Image](https://user-images.githubusercontent.com/59082428/177143293-4dc29764-a1ca-4b7b-af40-50094f356ebe.jpg)

**Perubahan Struktur Data** 
- Data bisa di tampung di table  "setting_aplikasi" dengan 
   - Key = value ( Logo Brse )
   - Keterangan = Value (Aktif / Non-aktif) 

 Untuk versi OpenSID mana
v22.08-premium

**Comment by apidong** [comment]
catatan, untuk footer. hanya bisa dilakukan melalui tema masing-masing

**Comment by eddieridwan** [comment]
Untuk footer lakukan pada tema bawaan sistem, yaitu esensi dan natra.

**Comment by apidong** [comment]
berdasarkan hasil diskusi, dibutuhkan sebuah pengaturan yang memuat pengaktif'an modul tte, pengaturan tersebut antara lain : 
a. atur aktif / non aktifkan tte
b. atur logo tampil / tidak tampil.
c. atur url API TTE
pengaturan tsb di letakkan di bawah modul pengaturan > aplikasi

**Comment by vickyrolanda** [comment]
> berdasarkan hasil diskusi, dibutuhkan sebuah pengaturan yang memuat pengaktif'an modul tte, pengaturan tersebut antara lain :
> a. atur aktif / non aktifkan tte
> b. atur logo tampil / tidak tampil.
> c. atur url API TTE
> pengaturan tsb di letakkan di bawah modul pengaturan > aplikasi

berdasarkan hasil diskusi, dibutuhkan sebuah pengaturan yang memuat pengaktif'an modul tte, pengaturan tersebut antara lain :
a. atur aktif / non aktifkan tte
b. atur logo tampil / tidak tampil.
c. atur url API TTE
d. atur username & password untuk basic auth otentikasi API TTE
pengaturan tsb di letakkan di bawah modul pengaturan > aplikasi

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR TTE https://github.com/OpenSID/premium/pull/1116
