### ISSUE TITLE
Bug/error: Status Perkawinan KAWIN TERCATAT SEMUA

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#4836]
### Jelaskan error yg dialami

Di Status Perkawinan semua KAWIN TERCATAT walaupun belum terisi kolom buku nikah dan tanggal nikah

### Cara untuk mereplikasi errornya

Menu Kependudukan/Keluarga/ klik nomor KK 
![image](https://user-images.githubusercontent.com/25834335/152551830-a1b115ed-fb6a-4285-afee-62dacf5d1634.png)
di status Perkawinan tertera KAWIN TERCATAT padahal tidak ada nomor buku nikah dan tanggal nikah
![Uploading kawintercatat.png…]()

### Hasil yg diharapkan

Jika Kolom BUKU NIKAH dan Tanggal NIKAH kosong maka : KAWIN BELUM TERCATAT
Jika Kolom BUKU NIKAH dan Tanggal NIKAH terisi maka : KAWIN TERCATAT

### Tangkapan layar dan log error

![kawintercatat](https://user-images.githubusercontent.com/25834335/152552183-7799b722-fcb1-4607-ac2d-0501c89c6449.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

22.02

### Tema Yang Digunakan

Denatra

**Comment by yogiperdana** [comment]
Jika salah satu dari kolom buku nikah atau tanggal nikah terisi dan yang lainnya kosong apakah statusnya menjadi tercatat atau belum tercatat? @MUHAMMADRANGSEL

**Comment by MUHAMMADRANGSEL** [comment]
sama tetap KAWIN TERCATAT, KOLOM BUKU NIKAH terisi  kolom TANGGAL NIKAH tidak terisi atau sebaliknya tetap muncul KAWIN TERCATAT

**Comment by yogiperdana** [comment]
Telah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/710

**Comment by MUHAMMADRANGSEL** [comment]
Terima kasih

Pada tanggal Rab, 9 Feb 2022 09.53, Yogi Perdana ***@***.***>
menulis:

**Comment by mizwaruddin** [comment]
@yogiperdana di detail penduduk kolom tgl dan nomor akta jika kosong masih tercatat sebagai kawin tercatat.

**Comment by andifahruddinakas** [comment]
@yogiperdana, cek modul lain yg berkaitan dengan status perkawinan ini.
