### ISSUE TITLE
Bug/error: Status Kehamilan

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#4837]
### Jelaskan error yg dialami

Ketika Ubah Biodata Penduduk maupun Input baru pada waktu memilih status kehamilan : TIDAK HAMIL yang muncul HAMIL setelah data disimpan
![image](https://user-images.githubusercontent.com/25834335/152552674-7a79806f-4435-4a71-a77d-4cd1d1d0626e.png)

muncul HAMIL
![image](https://user-images.githubusercontent.com/25834335/152552760-f6b661fe-8283-46d3-8514-293f156414f8.png)

### Cara untuk mereplikasi errornya

Kependudukan/Penduduk ubah biodata cari status kehamilan pilih status kehamilan Tidak Hamil

### Hasil yg diharapkan

yang muncul sesuai yang dipilih seperti di versi2 sebelumnya

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/25834335/152552937-62885f71-5a40-445c-8678-8f431d65af28.png)
![image](https://user-images.githubusercontent.com/25834335/152552962-8f36bfb9-99b6-41bf-af9a-7285611bbed6.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

22.02

### Tema Yang Digunakan

Denatra

**Comment by yogiperdana** [comment]
Tambahan: ketika tanggal perkawinan diisi lalu dikosongkan, status perkawinan tetap tercatat

**Comment by scqolbu24** [comment]
sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/732
