### ISSUE TITLE
Permintaan fitur: Perlu ditambahkan Tidak Menggunakan Akseptor KB

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#4838]
### Apa kekurangan yg ingin diatasi?

Pada waktu mengisi kolom akseptor KB tidak ada pilihan TIDAK MENGGUNAKAN AKSEPTOR KB sehingga di Statistik bagi yang tidak mengisi akseptor KB terhitung belum mengisi, ini akan membuat operator/perangkat desa kesulitan pada waktu mau update data untuk Akseptor KB
![Uploading image.png…]()

### Jelaskan solusi yg diinginkan

1. Untuk memberikan kemudahan pada waktu update dan mengetahui sipa saja warga yang menggunakan akseptor KB dan mana yang tidak menggunakan akseptor KB perluditambahkan PILIHAN : TIDAK MENGGUNAKAN AKSEPTOR KB supaya jelas siapa warga yang menggunakan akseptor KB dan mana yang tidak .
2. di Statistik Kependudukan untuk Akseptor KB akan semakin jelas siapa yang mengunakan dan siapa yang tidak menggunakan yang dimana sekarang yang tidak mengisi akseptor KB masuk ke Belum Mengisi

### Apakah ada alternatif lain

Tidak Ada

### Untuk versi OpenSID mana

22.03

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1210
