### ISSUE TITLE
Permintaan fitur: Short berdasarkan Tanggal Cetak KK

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#4839]
### Apa kekurangan yg ingin diatasi?

untuk memaksisimalkan fungsi dari kolom Tanggal Cetak KK dan supaya bisa dengan mudah mengetahui KK mana yang belum terisi tanggal cetak KK maka perlu dibuatkan supaya bisa short berdasrkan tanggal cetak KK
![Uploading image.png…]()

### Jelaskan solusi yg diinginkan

Bisa short berdasarkan tanggal cetak KK seperti TANGGAL TERDAFTAR
![image](https://user-images.githubusercontent.com/25834335/152556533-50b33245-1b13-46cb-abc1-12b05129a77e.png)

### Apakah ada alternatif lain

Tidak Ada

### Untuk versi OpenSID mana

22.03

### Informasi tambahan

Tidak Ada

**Comment by agungsugiarto** [comment]
Sudah di fitur premium melalui pr https://github.com/OpenSID/premium/pull/961
