### ISSUE TITLE
Bug/error: Kependudukan

### ISSUE THREAD

**Issue by kasipem331** [OpenSID/OpenSID#4840]
### Jelaskan error yg dialami

Setelah update v22.02 Daftar Penduduk adminsitrasi penduduk tidak bisa tampil (error 500) 

### Cara untuk mereplikasi errornya

Kependudukan>penduduk

### Hasil yg diharapkan

normal kembali

### Tangkapan layar dan log error

x

### Rilis Versi OpenSID

Rilis Umum

### Versi OpenSID

v22.02

### Informasi tambahan

a

**Comment by agungsugiarto** [comment]
Pak @kasipem331 mohon lengkapi error yg dimaksud, seperti tampilan log error

**Comment by kasipem331** [comment]
Pak @agungsugiarto Mohon maaf, karena tuntutan pekerjaan, sementara saya downgrade lagi ke V22.01. Intinya ketika masuk menu kependudukkan isinya kosong. Tapi untuk surat menyurat, KK, tetap muncul

**Comment by scqolbu24** [comment]
@kasipem331 sehubungan perbaikan yang dilakukan di rilis premium, maka issue isi di close. 
silahkan diupdate di rilis berikutnya, terimakasih.
