### ISSUE TITLE
[PREMIUM] Impor Peta Area Persil dari KML/GPX dan Buat Area Persil error 500 

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#4841]
### Jelaskan error yg dialami

Saat melakukan impor peta area peta lokasi persil -->saat disimpan terjadi error 500

### Cara untuk mereplikasi errornya

1. Pilih Fitur Pertanahan -->Pilih Salah Satu C-Desa
2. Klik Tambah Persil-->Lengkapi Data yg di perlukan
3. Klik Pilih Area
4. Klik Impor dari KML/GPX --> Klik Simpan

![image](https://user-images.githubusercontent.com/64481641/152640236-038e0c28-6160-4a55-b4d7-fe0861d60443.png)

![image](https://user-images.githubusercontent.com/64481641/152640262-eee94999-635f-4ea4-baa8-f1a5b781ab81.png)

### Hasil yg diharapkan

Agar normal kembali, baik pemetaan areal dipersil maupun di pemetaan area lainnya

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/64481641/152640300-025004ee-7741-445f-9851-cf7e7c7ac86c.png)

Log Error : Query error: Incorrect integer value: '' for column `teupinbe_ulangan`.`persil`.`id_peta` at row 1 - Invalid query: INSERT INTO `persil` (`nomor`, `nomor_urut_bidang`, `kelas`, `id_wilayah`, `luas_persil`, `lokasi`, `path`, `id_peta`, `cdesa_awal`) VALUES ('301301', '1', '5', '41', '350', NULL, '[[
5.10904,97.219278],[5.109006,97.219404],[5.109272,97.219441],[5.109232,97.21937],[5.109227,97.219329],[5.109238,97.219301]]]', '', '229')

![image](https://user-images.githubusercontent.com/64481641/152640342-555e7f5c-1687-4957-bf84-9fece25a80df.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

 Premium (v22.02-premium)

### Tema Yang Digunakan

Default

### Informasi tambahan

Buat Data Persil baru--> error ini ditemukan bila di import dari data area yg sama sekali baru yg belum ada dalam peta area sebelumnya, sedang area yg sudah ada dalam peta area dipanggil sebagai area persil di pilihan area tidak ada masalah, aman2 saja....

**Comment by agungsugiarto** [comment]
Pak @Zoel-WB bisa kirim file kml/gpx nya ?

**Comment by Zoel-WB** [comment]
> Pak @Zoel-WB bisa kirim file kml/gpx nya ?

oke...
[Nuraini Z.zip](https://github.com/OpenSID/OpenSID/files/8033738/Nuraini.Z.zip)

**Comment by yogiperdana** [comment]
Telah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/717
