### ISSUE TITLE
Sediakan qrcode untuk hasil ekspor pembuatan Surat Keterangan Biodata Penduduk

### ISSUE THREAD

**Issue by isnantomch** [OpenSID/OpenSID#4843]
### Jelaskan error yg dialami

Saya coba menambahkan qrcode di surat layanan. Untuk surat yg tidak ada lampirannya berjalan normal. Tapi saat saya terapkan qrcode dg cara yg sama di surat yang ada lampirannya (Surat Keterangan Biodata Penduduk ) saat file rtf nya dibuka dari file zip hasil ekspor tampil pemberitahuan "It may be corrupt" seperti gambar dibawah ini :
![Screenshot_20220130-205114_AnyDesk](https://user-images.githubusercontent.com/59205349/152671828-150fea46-fe83-46e9-a924-f6ae3bdef2bf.jpg)

error ini juga ditemukan di https://demo.opensid.or.id/ (untuk RIlis Umum) atau di https://berputar.opensid.or.id/ (untuk RIlis Premium).

### Cara untuk mereplikasi errornya

(Setelah Qrcode ditambahakan ke file rtf)
1. Cetak surat
2. Pilih suat ket biodara penduduk dengan lampiran  F-1.01
3. Pilih penduduk
4. Unduh rtf
5. Buka zip>buka surat ket biodata penduduk
6. tampil erorr
![Screenshot_20220130-205114_AnyDesk](https://user-images.githubusercontent.com/59205349/152672019-6756bbac-712c-40e5-a159-5dc39aefa015.jpg)

### Hasil yg diharapkan

Menampilkan surat keterangan penduduk atau pun surat layanan lainnya yang ada lampiran dengan normal dan tecantum qrcode.
![Screenshot_20220206-144952_WPS Office](https://user-images.githubusercontent.com/59205349/152672129-9d7cf33e-1c2c-4a5f-b922-838926b6a988.jpg)

### Tangkapan layar dan log error

![Screenshot_20220130-205114_AnyDesk](https://user-images.githubusercontent.com/59205349/152672185-2aba3e31-ac24-422a-bdd2-ad9ed0830b57.jpg)
![Screenshot_20220206-145550_AnyDesk](https://user-images.githubusercontent.com/59205349/152672357-52c7ef2c-dbc1-4977-a2a7-e91acbe24c78.jpg)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.02-premium

### Tema Yang Digunakan

Batuah

### Informasi tambahan

Ini terjadi disemua surat layanan yang ada lampirannya (Formulir)

**Comment by agungsugiarto** [comment]
Pak @isnantomch saat ini untuk surat **Surat Keterangan Biodata Penduduk** belum mendukung untuk ditampilkan qrcode, issue ini saya ubah ke permintaan fitur agar bisa dimanfaatkan juga oleh banyak desa. Terima kasih
