### ISSUE TITLE
Bug/error: Error ketika menambah anggota yang sudah terdaftar pada anggota kelompok

### ISSUE THREAD

**Issue by FirlianiF** [OpenSID/OpenSID#4845]
### Jelaskan error yg dialami

error ketika menambahkan anggota kelompok jika data sudah terdaftar di kelompok tersebut.

### Cara untuk mereplikasi errornya

Kependudukan > Kelompok > Rincian Kelompok > Tambah Anggota Kelompok

### Hasil yg diharapkan

tidak muncul tampilan error, jadi bisa berupa alert "data sudah terdaftar di kelompok tersebut"  atau menambahkan validasi agar data yang sudah terdaftar dikelompok tidak perlu ditampilkan di select box pada form tambah anggota kelompok.

### Tangkapan layar dan log error

![Capture2](https://user-images.githubusercontent.com/30171560/152704384-85094418-d588-4a19-b9c9-ce8ee4cf8b0c.PNG)
![Capture](https://user-images.githubusercontent.com/30171560/152704385-51085572-2616-49ec-94f5-92cd2ecc1e69.PNG)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Versi 22.02-premium-rev01

**Comment by yogiperdana** [comment]
Telah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/713
