### ISSUE TITLE
Bug/error: Ubah Data Pengguna dan Penduduk

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/OpenSID#4846]
### Jelaskan error yg dialami

Saat ini ketika akan ubah data pada data pengguna dan penduduk terjadi eror duplikat email.

### Cara untuk mereplikasi errornya

**Data Pengguna**
1. Pergi ke Halaman Admin
2. Klik Modul Pengaturan
3. Pilih Pengguna
4. Ubah salah satu pada list data pengguna

**Data Penduduk**
1. Pergi ke Halaman Admin
2. Klik Modul Kependudukan
3. Pilih Penduduk
4. Ubah salah satu pada list data penduduk

### Hasil yg diharapkan

dapat ubah data.

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.02-premium

### Tema Yang Digunakan

natra

### Informasi tambahan

Eror ini setelah adanya perbaikan pada issue https://github.com/OpenSID/premium/pull/691

**Comment by yogiperdana** [comment]
Telah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/709
