### ISSUE TITLE
Permintaan fitur: Penambahan Jenis Satuan Produk Pada Modul Lapak

### ISSUE THREAD

**Issue by emanuel-simon** [OpenSID/OpenSID#4847]
### Apa kekurangan yg ingin diatasi?

Pilihan satuan produk yang masih terbatas, sedangkan jenis produk yang sangat bervariasi sehingga pilihan satuan yang tersedia sekarang kurang sesuai.
![2022-02-07_12h00_15](https://user-images.githubusercontent.com/48465803/152722854-edc92b8d-e56b-4e4d-9391-110fc6d38b6c.png)

### Jelaskan solusi yg diinginkan

Penambahan fitur input satuan produk

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

v21.03 atau v21.03-premium

### Informasi tambahan

-

**Comment by andifahruddinakas** [comment]
Tinggal ketik saja satuan yang ingin ditambahkan dan kemudian simpan.

**Comment by emanuel-simon** [comment]
Oh bisa ya pak? 
Siap 👮🏻‍♂️
