### ISSUE TITLE
Bug/error: terjadi eror di pada penambahan persil di fitur premium

### ISSUE THREAD

**Issue by mranca** [OpenSID/OpenSID#4848]
### Jelaskan error yg dialami

terjadi eror saat no persil dan nomor bidang lebih dari dua digit / angka

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v.22.02

### Informasi tambahan

-

**Comment by yogiperdana** [comment]
Terima kasih atas laporannya. Mohon sertakan langkah-langkah untuk mereplikasi error dan tangkapan layar (screenshoot) dari error tersebut.

**Comment by mranca** [comment]
![Uploading IMG_20220207_220754.jpg…]()

**Comment by mranca** [comment]
![IMG_20220207_220754](https://user-images.githubusercontent.com/76085245/152805230-380375ea-7750-4cd0-adfa-95b7869a0f5b.jpg)

**Comment by yogiperdana** [comment]
Setelah kami coba, nomor persil aman jika diinput menggunakan 3 digit angka. Namun no urut bidang saat ini akan bermasalah jika diinput dengan nilai lebih dari 127. Adakah ketentuan berapa nilai maksimum untuk no urut bidang tersebut pak?

**Comment by eddieridwan** [comment]
@yogiperdana seharusnya nomor urut bidang tidak besar2 amat, karena menunjukkan pemecehan persil. Sementara tidak ada info tambahan, tentukan saja maksimum tiga digit (yaitu 999). Ubah jenis data kolomnya, jika perlu. Tambahkan validasi di form dan di server membatasi nilai tersebut.

**Comment by mranca** [comment]
@yogiperdana batasi saja untuk 3 digit

**Comment by scqolbu24** [comment]
sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/733
