### ISSUE TITLE
Bug/error: HASIL CETAK SURAT KET. KELAHIRAN TIDAK SESUAI

### ISSUE THREAD

**Issue by agusterm** [OpenSID/OpenSID#4850]
### Jelaskan error yg dialami

hasil cetak surat keterangan kelahiran .rtf tidak memunculkan jenis kelamin dan nama penduduk lahir jika data kelahiran di ambil dari data kependudukan. Namun jika data kelahiran di input manual berhasil / normal

### Cara untuk mereplikasi errornya

sebagai mana mestinya

### Hasil yg diharapkan

sebagai mana mestinya

### Tangkapan layar dan log error

![Screenshot 2022-02-07 135349](https://user-images.githubusercontent.com/87739467/152732271-fbc37804-5619-4b00-9bbe-89242eef4f86.jpg)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

22.02

### Tema Yang Digunakan

Denatra

**Comment by agungsugiarto** [comment]
Pak @agusterm maksud dari database bisa dijelaskan langkah terperincinya?

**Comment by agusterm** [comment]
> Pak @agusterm maksud dari database bisa dijelaskan langkah terperincinya?

maksud saya, pada saat memilih data kelahiran dari dari database pak. itu tidak mau terisi jenis kelami dan nama bayi di cetak rtf. namun pada saat input manual hasil cetakannya normal

**Comment by agusterm** [comment]
> > Pak @agusterm maksud dari database bisa dijelaskan langkah terperincinya?
> 
> maksud saya, pada saat memilih data kelahiran dari dari database pak. itu tidak mau terisi jenis kelami dan nama bayi di cetak rtf. namun pada saat input manual hasil cetakannya normal

ini maksud saya 
![image](https://user-images.githubusercontent.com/87739467/153317077-18b8380b-ee26-4d3a-a346-7d5f1d5b494d.png)

**Comment by yogiperdana** [comment]
Telah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/728
