### ISSUE TITLE
Tambah keterangan informasi penggunaan layanan BSrE

### ISSUE THREAD

**Issue by yogiperdana** [OpenSID/OpenSID#4851]
Tambah keterangan informasi penggunaan layanan BSrE pada dokumen yang telah ditandatangani untuk memenuhi uji kelengkapan sebagai syarat PKS

--------------------------------------- 
- Ada 4 jenis TTE
1. Pdf TTE tanpa visual (artinya pdf telah ter TTE namun tidak nampak secara visual)
2. Pdf dengan Images (artinya pdf telah ter TTE akan ada tambahan images yang ingin kta terapkan didalam pdf tersebut)
3. Pdf dengan Qrcode (artinya pdf telah ter TTE dan dengan qrcode tambahan )
4. Pdf dengan Tag cordinat (artinya pdf telah ter TTE dapat digunakan pada dokumen yang terlebih dahulu
diberi Tag berupa karakter unik

Mungkin bisa di pilih jenis TTE yang ingin diterapkan disini atau sebagai contoh seperti dibawah ini : 
<img width="399" alt="image" src="https://user-images.githubusercontent.com/59082428/177365465-39343cf0-5980-49a1-af49-28db867defa5.png">

gambar di atas menerapkan TTE point no 2. 

untuk ketererangan lebih jelas bisa dilihat melalui issu #4854

**Comment by apidong** [comment]
ditutup digantikan dengan issue https://github.com/OpenSID/OpenSID/issues/5407
