### ISSUE TITLE
Buat notifikasi penanganan exception dalam proses TTE

### ISSUE THREAD

**Issue by yogiperdana** [OpenSID/OpenSID#4853]
Aplikasi menampilkan notifikasi ketika passphare sukses atau gagal.

Aplikasi menampilkan notifikasi ketika dokumen tidak bisa dibuka atau file tidak ada. 

Aplikasi menampilkan notifikasi ketika proses TTE tidak didukung koneksi internet.

Aplikasi menyimpan log kegagalan selama proses TTE, logging ini modul tersendiri.

--------------------------------------------------------
- Mungkin notifikasi ini dapat diterapkan dan disesuaikan  dari informasi berikut ini : 

**Aplikasi menampilkan notifikasi ketika passphare sukses atau gagal.**
   (Proses ini akan tampil ketika pejabat penandatangan memasukkan kode passphare untuk melakukan TTD)

**Aplikasi menampilkan notifikasi ketika dokumen tidak bisa dibuka atau file tidak ada.** 
(Proses ini bisa disesuaikan ketika mendapat result API pada saat Generate TTE )

**Aplikasi menampilkan notifikasi ketika proses TTE tidak didukung koneksi internet.**
(Proses ini bisa diterapkan ketika proses pengriman document ke post API ESIGN CLIENT SERVICE)

**Aplikasi menyimpan log kegagalan selama proses TTE**

untuk referensi penjelasan penerapan TTE bisa dilihat melalui issue #4852 #4854

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1195
