### ISSUE TITLE
[PREMIUM] Masa Berlaku Surat (Tanggal) Permohonan Surat Melalui Layanan Mandiri Tidak Aktif

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#4856]
### Jelaskan error yg dialami

Masa Berlaku Surat (Tanggal) Permohonan Surat Melalui Layanan Mandiri Tidak Aktif

### Cara untuk mereplikasi errornya

1.  Buka Layanan Mandiri
2.  Buat Permohonan Satu Surat Misal-Nya "Surat Pengantar"
3.  Isi Semua Kebutuhan Surat
4.  Pilih Masa Berlaku Dari - Sampai

### Hasil yg diharapkan

Supaya Masa Berlaku Dapat Ditentukan atau Masa Berlaku Ini siapa yg menentukannya, bila yg menentukan dari sekretariat mungkin di layanan mandiri tidak diperlukan....

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/64481641/152784294-630ec97c-7de2-411b-aff5-592951abd6fb.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

 premium (v22.02-Berputar

### Tema Yang Digunakan

default

### Informasi tambahan

Tester dari Demo Premium Berputar dan Premium v22.02

**Comment by agungsugiarto** [comment]
Pak @Zoel-WB issue ini saya tutup karena setiap surat diatur melalui pengaturan untuk masa berlakunya, di layanan mandiri perlu ditampilkan agar warga mengetahui informasi itu. Terima kasih

![image](https://user-images.githubusercontent.com/10989147/152977981-ebcfeae8-9c50-47e9-8ce3-18dcbb936e92.png)

**Comment by eddieridwan** [comment]
@Zoel-WB , waktu berlaku ditentukan oleh petugas desa, bukan oleh warga. Karena itu tidak dapat diisi oleh warga di Layanan Mandiri. Warga bisa saja meminta waktu berlaku yg berbeda melalui pesan kepada petugas desa. Misalnya untuk surat izin keramaian minta berlaku 5 hari karena kondangan yg berjalan lama. Tetapi tetap wewenang ada pada petugas desa untuk menetapkan. 

Seperti itu ketentuan yg berlaku saat ini di OpenSID.

**Comment by Zoel-WB** [comment]
Oke pak...
