### ISSUE TITLE
Bug/error: tambahkan peta dusun tidak bisa di simpan

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#4857]
### Jelaskan error yg dialami

nemabahkan peta dusun tidak dapan disimpan

### Cara untuk mereplikasi errornya

buka : https://berputar.opensid.or.id/  >> info desa >> wilayah administratif >> tambahkan peta dusun

### Hasil yg diharapkan

bisa menambahkan peta dusun 

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

premium

### Tema Yang Digunakan

natra

**Comment by scqolbu24** [comment]
Mohon Maaf @balongbesuk , saya coba dapat menyimpan dengan normal, berikut saya lampirkan tangkapan layarnya setelah berhasil disimpan.

<img width="100%" alt="Membuat Peta Dusun" src="https://user-images.githubusercontent.com/68048807/153358350-471e3cbd-5be8-4cfa-9263-3cb7bd6ce686.PNG">

**Comment by scqolbu24** [comment]
https://user-images.githubusercontent.com/68048807/153361745-48e1929a-163e-4f60-a748-c4bcd518c7b0.mp4

**Comment by scqolbu24** [comment]
berhubung di https://berputar.opensid.or.id/ normal bisa menyimpan tambah peta dusun, maka issue ini di close.
