### ISSUE TITLE
Bug/error: wilayah dusun lainnya tidak tampil pada peta

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#4858]
### Jelaskan error yg dialami

ketika sudah membuat peta dusun 1 dan kemudian dilanjutkan menambahkan peta dusun2 lalu ketika d cek di https://demo.opensid.or.id/peta dengan mencentang tampilkan wilayah desa kemudian wilayah dusun maka wilayah dusun 1 saja yang tampil pada peta wilayah dusun 2 tidak tampil

### Cara untuk mereplikasi errornya

ketika sudah mengisili wilayah dusun 1 2 3 dst buka web peta https://demo.opensid.or.id/peta

centang wilayah desa dan dusun maka yhang tampil hanya wilayah dusun 1

### Hasil yg diharapkan

dapat tampil semua 

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Umum

### Versi OpenSID

22.02

### Tema Yang Digunakan

natra

### Informasi tambahan

-

**Comment by scqolbu24** [comment]
issue ini sama halnya dengan issue https://github.com/OpenSID/OpenSID/issues/4857, dan apabila di [berputar](https://berputar.opensid.or.id/) sudah berjalan dengan normal, maka issue ini sudah diperbaiki di premium, sehingga issue ini bisa di close, terimakasih.
