### ISSUE TITLE
Modul : PBB

### ISSUE THREAD

**Issue by noefa86** [OpenSID/OpenSID#486]
Selain mengelola administrasi kependudukan, desa juga menangani perpajakan khususnya PBB. Mohon dibuatkan modul PBB atau penambahan fungsi PBB yg terkait dengan modul  Persil.

**Comment by MUHAMMADRANGSEL** [comment]
Silahkan diuraikan yg model seperti bagaimana yg mas inginkan shgg para programer bisa dgn jelas tau keinginan mas

**Comment by mizwaruddin** [comment]
@afa28 sdh ada untuk pengguna premium.
