### ISSUE TITLE
Bug/error: di mode `production`, mestinya tidak tampil errornya

### ISSUE THREAD

**Issue by totoprayogo1916** [OpenSID/OpenSID#4862]
### Jelaskan error yg dialami

jika terjadi error pada env production
mestinya tidak ditampilkan "apa yang error" ...

akan jadi celah buat orang yang tidak bertanggung jawab.

### Cara untuk mereplikasi errornya

silakan buat satu kesalahan yang memunculkan masalah

### Hasil yg diharapkan

sembunyikan pesan error,
bisa dibuatkan log untuk pesan errornya

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/2387514/153101915-8d001096-a029-4742-9072-715eaaab0f84.png)

### Rilis Versi OpenSID

Rilis Umum

### Versi OpenSID

*

**Comment by agungsugiarto** [comment]
**Mode development**
![image](https://user-images.githubusercontent.com/10989147/153829789-51ba081d-1530-420e-bf10-990a3e9999d3.png)

**Mode production**
![image](https://user-images.githubusercontent.com/10989147/153829891-a656e13c-8d27-449d-ba97-8d57d93ab72d.png)

**Comment by scqolbu24** [comment]
sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/740
