### ISSUE TITLE
Bug/error: Error Migrasi (ref_penduduk_hamil)

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/OpenSID#4865]
### Jelaskan error yg dialami

pada saat migrasi terjadi error dengan pesan ref_penduduk_hamil

### Cara untuk mereplikasi errornya

1.  Pergi Halaman Admin
2.  Klik Modul Pengaturan
3. Pilih Database
4. Pilih Migrasi DB
5. Klik Migrasi Database ke OpenSID

### Hasil yg diharapkan

dapat sukses migrasi

### Tangkapan layar dan log error

![photo_2022-02-09_15-36-04](https://user-images.githubusercontent.com/68048807/153157039-c0c13821-767c-413e-b13f-57091d0464b1.jpg)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.02-premium

### Tema Yang Digunakan

natra

**Comment by yogiperdana** [comment]
Telah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/723

**Comment by eddieridwan** [comment]
@yogiperdana @scqolbu24 , untuk mengembalikan tabel referensi yg hilang, tambahkan ke fitur Periksa yg saya kirim melalui PR https://github.com/OpenSID/premium/pull/739
