### ISSUE TITLE
Bug/error: "Kosongkan DB" tapi masih ada beberapa tabel yang belum terhapus

### ISSUE THREAD

**Issue by totoprayogo1916** [OpenSID/OpenSID#4866]
### Jelaskan error yg dialami

Mestinya, untuk "Kosongkan DB", semua isian tabel terhapus semua kecuali beberapa tabel saja, misal sisakan setting

### Cara untuk mereplikasi errornya

jalankan "Kosongkan DB" di pengaturan

### Hasil yg diharapkan

semua harusnya kosong ...

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/2387514/153175156-16e8d4d5-1fd9-4914-a240-b7be67cc2528.png)

### Rilis Versi OpenSID

Rilis Umum

### Versi OpenSID

*

**Comment by totoprayogo1916** [comment]
mungkin sudah diperbaiki di #4459

**Comment by totoprayogo1916** [comment]
mungkin berhubungan dengan #4774

**Comment by scqolbu24** [comment]
issue https://github.com/OpenSID/OpenSID/issues/4774 sudah diperbaiki, 
dapat dilihat pada catatan rilis https://github.com/OpenSID/OpenSID/releases/tag/v22.02  -> Perbaikan Bug -> nomor 40
