### ISSUE TITLE
Bug/error: 

### ISSUE THREAD

**Issue by rajatega1922** [OpenSID/OpenSID#4867]
### Jelaskan error yg dialami

ada error saat melakukan permohonan surat keterangan kelahiran. saat klik tombol kirim muncul error. id_pemohon tidak terbaca.
ERROR - 2022-02-10 18:17:58 --> Query error: Column 'id_pemohon' cannot be null - Invalid query: INSERT INTO `permohonan_surat` (`id_pemohon`, `id_surat`, `isian_form`, `status`, `keterangan`, `no_hp_aktif`, `syarat`) VALUES (NULL, '18', '{\"url_surat\":\"surat_ket_kelahiran\",\"url_remote\":\"http:\\/\\/localhost\\/desa_dev\\/surat\\/nomor_surat_duplikat\",\"anchor\":\"\",\"id_surat\":\"18\",\"nomor\":\"1\",\"ibu\":\"1\",\"id_ibu\":\"7\",\"bayi\":\"1\",\"id_bayi\":\"\",\"hari\":\"Selasa\",\"tanggallahir\":\"22-02-2022\",\"waktu_lahir\":\"18:16\",\"tempat_dilahirkan\":\"1\",\"tempatlahir\":\"rwrqr\",\"jenis_kelahiran\":\"1\",\"kelahiran_anak_ke\":\"2\",\"penolong_kelahiran\":\"1\",\"berat_lahir\":\"12\",\"panjang_lahir\":\"22\",\"pelapor\":\"1\",\"id_pelapor\":\"5\",\"hubungan_pelapor\":\"332\",\"saksi1\":\"2\",\"nama_saksi1\":\"ss\",\"nik_saksi1\":\"123123\",\"tempat_lahir_saksi1\":\"231\",\"tanggal_lahir_saksi1\":\"01-02-2022\",\"umur_saksi1\":\"0\",\"jksaksi1\":\"\",\"pekerjaanid_saksi1\":\"\",\"pekerjaansaksi1\":\"\",\"alamat_saksi1\":\"\",\"rt_saksi1\":\"\",\"rw_saksi1\":\"\",\"desasaksi1\":\"\",\"kecsaksi1\":\"\",\"kabsaksi1\":\"\",\"provinsisaksi1\":\"\",\"saksi2\":\"2\",\"nama_saksi2\":\"3123\",\"nik_saksi2\":\"213123\",\"tempat_lahir_saksi2\":\"rr\",\"tanggal_lahir_saksi2\":\"01-02-2022\",\"umur_saksi2\":\"0\",\"jksaksi2\":\"\",\"pekerjaanid_saksi2\":\"\",\"pekerjaansaksi2\":\"\",\"alamat_saksi2\":\"\",\"rt_saksi2\":\"\",\"rw_saksi2\":\"\",\"desasaksi2\":\"\",\"kecsaksi2\":\"\",\"kabsaksi2\":\"\",\"provinsisaksi2\":\"\",\"lokasi_disdukcapil\":\"123\",\"pilih_atas_nama\":\"\",\"pamong\":\"DEDY RONI, ST\",\"pamong_nip\":\"\",\"pamong_id\":\"14\",\"jabatan\":\"Kepala Desa\"}', 1, NULL, NULL, 'null')

### Cara untuk mereplikasi errornya

ada error saat melakukan permohonan surat keterangan kelahiran. saat klik tombol kirim muncul error. id_pemohon tidak terbaca.
ERROR - 2022-02-10 18:17:58 --> Query error: Column 'id_pemohon' cannot be null - Invalid query: INSERT INTO `permohonan_surat` (`id_pemohon`, `id_surat`, `isian_form`, `status`, `keterangan`, `no_hp_aktif`, `syarat`) VALUES (NULL, '18', '{\"url_surat\":\"surat_ket_kelahiran\",\"url_remote\":\"http:\\/\\/localhost\\/desa_dev\\/surat\\/nomor_surat_duplikat\",\"anchor\":\"\",\"id_surat\":\"18\",\"nomor\":\"1\",\"ibu\":\"1\",\"id_ibu\":\"7\",\"bayi\":\"1\",\"id_bayi\":\"\",\"hari\":\"Selasa\",\"tanggallahir\":\"22-02-2022\",\"waktu_lahir\":\"18:16\",\"tempat_dilahirkan\":\"1\",\"tempatlahir\":\"rwrqr\",\"jenis_kelahiran\":\"1\",\"kelahiran_anak_ke\":\"2\",\"penolong_kelahiran\":\"1\",\"berat_lahir\":\"12\",\"panjang_lahir\":\"22\",\"pelapor\":\"1\",\"id_pelapor\":\"5\",\"hubungan_pelapor\":\"332\",\"saksi1\":\"2\",\"nama_saksi1\":\"ss\",\"nik_saksi1\":\"123123\",\"tempat_lahir_saksi1\":\"231\",\"tanggal_lahir_saksi1\":\"01-02-2022\",\"umur_saksi1\":\"0\",\"jksaksi1\":\"\",\"pekerjaanid_saksi1\":\"\",\"pekerjaansaksi1\":\"\",\"alamat_saksi1\":\"\",\"rt_saksi1\":\"\",\"rw_saksi1\":\"\",\"desasaksi1\":\"\",\"kecsaksi1\":\"\",\"kabsaksi1\":\"\",\"provinsisaksi1\":\"\",\"saksi2\":\"2\",\"nama_saksi2\":\"3123\",\"nik_saksi2\":\"213123\",\"tempat_lahir_saksi2\":\"rr\",\"tanggal_lahir_saksi2\":\"01-02-2022\",\"umur_saksi2\":\"0\",\"jksaksi2\":\"\",\"pekerjaanid_saksi2\":\"\",\"pekerjaansaksi2\":\"\",\"alamat_saksi2\":\"\",\"rt_saksi2\":\"\",\"rw_saksi2\":\"\",\"desasaksi2\":\"\",\"kecsaksi2\":\"\",\"kabsaksi2\":\"\",\"provinsisaksi2\":\"\",\"lokasi_disdukcapil\":\"123\",\"pilih_atas_nama\":\"\",\"pamong\":\"DEDY RONI, ST\",\"pamong_nip\":\"\",\"pamong_id\":\"14\",\"jabatan\":\"Kepala Desa\"}', 1, NULL, NULL, 'null')

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

 Versi 22.01-premium-rev01 

### Informasi tambahan

-sss

**Comment by scqolbu24** [comment]
Mohon dijelaskan secara terperinci langkah-langkah dari awal sampai terjadinya error.

**Comment by agungsugiarto** [comment]
Duplikat dengan issue https://github.com/OpenSID/OpenSID/issues/4881
