### ISSUE TITLE
Permintaan fitur: Pindahkan halaman statis untuk website (front) ke masing-masing tema

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#4868]
### Apa kekurangan yg ingin diatasi?

Terjadi bentrok pada saat membuka Statistik, Aparatur, dll di Peta pada halaman web (front end)

### Jelaskan solusi yg diinginkan

Pindahkan asset peta ke masing-masing tema

### Apakah ada alternatif lain

Tidak ada

### Untuk versi OpenSID mana

v22.02-premium

**Comment by andifahruddinakas** [comment]
Untuk mempermudah, tiap halaman dibuat issuenya masing2 : 
1. IDM (https://github.com/OpenSID/OpenSID/issues/5131)

**Comment by andifahruddinakas** [comment]
Pak @ariandii, issue ini terlalu besar, jadi perlu dipecahkan : 

- [ ] https://github.com/OpenSID/OpenSID/issues/6853
- [ ] https://github.com/OpenSID/OpenSID/issues/6854
- [ ] https://github.com/OpenSID/OpenSID/issues/6855
