### ISSUE TITLE
Bug/error: upload dokumen laporan penduduk error

### ISSUE THREAD

**Issue by Wiliyantoro** [OpenSID/OpenSID#4869]
### Jelaskan error yg dialami

saat ingin mengupload laporan penduduk / dokumen .pdf di menu statistik -> laporan penduduk
ketika ingin menyimpan muncul error 500

### Cara untuk mereplikasi errornya

Query error: Column 'nama_file' cannot be null - Invalid query: INSERT INTO `laporan_sinkronisasi` (`judul`, `semester`, `tahun`, `nama_file`, `tipe`) VALUES ('Laoran Penduduk Bulan Januari', '1', '2022', NULL, 'laporan_penduduk')

### Hasil yg diharapkan

bisa menyimpan laporan penduduk

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/44520382/153537292-4c92d0e7-2cab-4775-a21c-5e362939f557.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.02-premium-rev01

### Tema Yang Digunakan

Denatra v.5.1

**Comment by scqolbu24** [comment]
Validasi penyimpanan file selain .pdf

**Comment by yogiperdana** [comment]
Telah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/734
