### ISSUE TITLE
Bug/error: Notifikasi Login Layanan Mandiri, Pengguna Belum Aktif

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/OpenSID#4870]
### Jelaskan error yg dialami

Saat ini ketika pengguna yang masih non aktif login di layanan mandiri akan muncul notifikasi dan notif tersebut sama akan muncul di halaman admin.

### Cara untuk mereplikasi errornya

1. Pergi Halaman Layanan Mandiri
2. Login sebagai pengguna yang sudah mendaftar di layanan mandiri, namun belum di aktifkan oleh operator / admin
3. Kemudian masukan NIK dan PIN
4. Klik tombol masuk -> maka akan muncul notifikasi (gambar terlampir)
5. Pada Halaman Lain yaitu halaman admin akan muncul notif yang sama.

### Hasil yg diharapkan

notifikasi cukup di halaman layanan mandiri, notif di halaman admin dihilangkan.

### Tangkapan layar dan log error

![notif](https://user-images.githubusercontent.com/68048807/153692293-d8b8328a-7452-489c-ab6a-f931a248418e.jpg)

https://user-images.githubusercontent.com/68048807/153692302-86afd9cb-9fc2-451b-86e3-1d556114beea.mp4

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.02-premium

### Tema Yang Digunakan

natra

### Informasi tambahan

-

**Comment by apidong** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/738
