### ISSUE TITLE
Permintaan fitur: Surat pengantar Kepala Dusun 

### ISSUE THREAD

**Issue by siwamdara** [OpenSID/OpenSID#4871]
### Apa kekurangan yg ingin diatasi?

![persyaratan dokument](https://user-images.githubusercontent.com/99572668/153737925-782fb4e0-cbd4-4cd8-9774-881fc979870b.jpg)
Surat pengantar kepala dusun/Kepala Kewilayah sudah digital dan surat masuk dan keluar ditambahkan khusus untuk kepala dusun/kepala kewilayahan masing masing dusun .

### Jelaskan solusi yg diinginkan

1. untuk surat pengantar kepala dusun sudah digital dan terhubung dengan surat yg di ajukan oleh warga
2. untuk menu surat masuk dan keluar di buatkan khusus untuk kepala dusun dan bisa di cetak laporannya.

### Apakah ada alternatif lain

selama ini di desa kami kepala dusun masih manual untuk memberikan surat pengantar ke warga untuk dijadikan ajuan di kantor desa untuk membuat surat /layanan surat di Desa

### Untuk versi OpenSID mana

premium 22.02

**Comment by andifahruddinakas** [comment]
Bisa dibuat menggunakan tinymce
