### ISSUE TITLE
Bug/error: ERROR ISI DATA BANTUAN SECARA MANUAL DAN IMPOR

### ISSUE THREAD

**Issue by desasoro** [OpenSID/OpenSID#4873]
### Jelaskan error yg dialami

Ketika ingin menginput Data Peserta Bansos error, baik isi manual mauput lewat fitur impor.
Error ini disebabkan oleh Tempat Lahir mengandung tanda ( ' ), Misalnya: =NA'E=
Masalah teratasi jika tanda ( ' ) pada Tempat Lahir didelete, Seperti: =NAE=.
 
Berikut Log Errornya:
Query error: Incorrect date value: '' for column 'kartu_tanggal_lahir' at row 1 - Invalid query: INSERT INTO program_peserta (`kartu_alamat`, kartu_id_pend, kartu_nama, kartu_nik, kartu_tanggal_lahir, kartu_tempat_lahir, no_id_kartu, peserta, `program_id`) VALUES. Ect...

### Cara untuk mereplikasi errornya

Langkah untuk mereplikasi error yg dialami:
1. Masuk ke Menu BANSOS
2. Klik Rincian Daftar Program Bantuan
3. Klik Tambah Peserta Baru
4. Masukan NIK
5. Sampai disini error akan terlihat

### Hasil yg diharapkan

Data Tempat Lahir bisa menggunakan tanda ( ' ) baik isi manual maupun lewat fitur impor data.

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/34540424/153806706-2447c22b-76ef-48b6-9603-850d26c30e8e.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

22.02 Premium

### Tema Yang Digunakan

DeNatra v5

**Comment by yogiperdana** [comment]
Telah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/741
