### ISSUE TITLE
[PREMIUM-22.02 BETA01] Tampilan Halaman (Paging) Pada Website atau Filter Data Suplemen hanya menampilkan 10 Data 

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#4875]
### Jelaskan error yg dialami

Tampilan Halaman (Paging) Pada Website atau Filter Data Suplemen hanya menampilkan 10 Data 

### Cara untuk mereplikasi errornya

Buka Website
Pilih Data Suplemen yg melebihi 100 Data

### Hasil yg diharapkan

Agar data suplemen dapat menampilkan seluruh data dana Sesuai dengan Pilihan Jumlah Data Data di Filter untuk ditampilkan, dan pilihan halaman juga berfungsi

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/64481641/154007661-36a22026-c5ec-46c3-9b06-20f05b78df52.png)

![image](https://user-images.githubusercontent.com/64481641/154007698-42f46dc9-12fa-4ef2-bb97-9b8ff1a68c34.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Premium [v22.02-Beta01)

### Tema Yang Digunakan

ESENSI DAN DEFULT

**Comment by Zoel-WB** [comment]
https://www.teupinbeulangan.desa.id/data-suplemen/pendataan-penerima-vaksin-covid-19

https://www.teupinbeulangan.desa.id/

**Comment by scqolbu24** [comment]
saya buka https://www.teupinbeulangan.desa.id/data-suplemen/pendataan-penerima-vaksin-covid-19 data yang ditampilkan sesuai dengan filter yang dipilih, Mohon maaf pak @Zoel-WB yang dimaksud bug-nya seperti bagaimanakah? 

<img width="100%" alt="data-vaksin" src="https://user-images.githubusercontent.com/68048807/154026218-72565c85-efcf-4df3-9f6d-c6831c7ed474.PNG">

**Comment by Zoel-WB** [comment]
> saya buka https://www.teupinbeulangan.desa.id/data-suplemen/pendataan-penerima-vaksin-covid-19 data yang ditampilkan sesuai dengan filter yang dipilih, Mohon maaf pak @Zoel-WB yang dimaksud bug-nya seperti bagaimanakah?
> 
> <img alt="data-vaksin" width="100%" src="https://user-images.githubusercontent.com/68048807/154026218-72565c85-efcf-4df3-9f6d-c6831c7ed474.PNG">

Ditempat saya tidak bisa-->pengaruh konek internetnya barang kali-->saya menggunakan edge, bila pakai crome hanya mutar-mutar saja, halaman tidak tampil untuk menampilkan data suplemen...

**Comment by Zoel-WB** [comment]
Saya ganti tema juga sama, hanya tampil 10 data
![image](https://user-images.githubusercontent.com/64481641/154055133-2a53dd91-f3ca-41a8-a9a2-bfcb42045069.png)

**Comment by Zoel-WB** [comment]
Saya gantikan Judul Modul -->tampilan berubah jadi 50 data-->
![image](https://user-images.githubusercontent.com/64481641/154055925-b406e51d-53a4-4293-8a01-f071da15976d.png)

![image](https://user-images.githubusercontent.com/64481641/154056005-f994ca71-a2fb-4b02-8f62-d26d28ba32a7.png)

**Comment by agungsugiarto** [comment]
Pak @Zoel-WB  issue ini saya close karena ketika saya mengakses tidak menemukan masalah?

![image](https://user-images.githubusercontent.com/10989147/154220419-7f1d03c4-c646-4bf8-bf50-d552afa58cac.png)

**Comment by ariandii** [comment]
Issue ini terjadi hanya muncul 10 data jika buka web halaman suplemen dalam kondisi login admin.

jika logout dan buka web halaman suplemen, maka data tampil lengkap.

ini tampilan saat sedang login halaman admin.

<img width="960" alt="screenshot_150" src="https://user-images.githubusercontent.com/46939846/154407557-db80b9de-8164-41cb-9ba1-4a602f177d34.png">

dan ini tampilan lengkap setelah admin logout /siteman

<img width="960" alt="screenshot_151" src="https://user-images.githubusercontent.com/46939846/154407588-30ad5498-5446-4a57-bd98-e4ef2080ae49.png">

**Comment by roaddee** [comment]
Session mungkin

**Comment by scqolbu24** [comment]
reopen kembali dengan penjelasan bahwa error yang terjadi ketika login sebagai admin, kemudian buka page "/data-suplemen/pendataan-penerima-vaksin-covid-19" maka akan mengalami error tersebut.

**Comment by yogiperdana** [comment]
Telah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/762
