### ISSUE TITLE
[PREMIUM-22.02 BETA01] Peta Garis-->setelah dihapus atau di reset>> semua menu/tombol ikut hilang di layar

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#4876]
### Jelaskan error yg dialami

Semua tombol buat peta pada Peta Garis tidak ditampilkan lagi setelah peta dihapus atau reset..

### Cara untuk mereplikasi errornya

Buka Fitur Pemetaan
Pilih Pengaturan Peta --->Pilih Peta Garis
Buat Peta Jenis Peta Garis --> Kemudian Simpan..

Buka Kembali---> Coba edit/hapus/riset
Pilih Simpan....
Kemudian Buka Kembali Peta Type Garis Untuk Membuat Peta Baru Type Garis

### Hasil yg diharapkan

Untuk Pemetaan Walaupun telah dihapus, edit maupun di riset, halaman pembuatannya agar normal seperlu awal pembuatan peta, atau menu-menu buat petanya tidak ikut hilang dengan sebab peta di hapus ataupun di riset.

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/64481641/154027703-59c2bbc6-2946-422b-a157-7bb413ed137d.png)

![image](https://user-images.githubusercontent.com/64481641/154027732-04c2c5de-6611-414b-86ca-818fab715bd4.png)

Kemudian Peta ini di Buka kembali dan dihapus titik koordinat dengan cara klik kanan pada setiap titik koordinat sampai titik koordinat terakhir--> pilih simpan..
ATAU
Buka Peta Garis  Klik [reset] -->klik [Simpan]

Buka Kembali Halaman Buat Peta Garis
![image](https://user-images.githubusercontent.com/64481641/154028457-dbdc1a31-617a-4fbd-9e0d-2561b2e2bef7.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Premium (v22.02-beta01)

### Tema Yang Digunakan

Default Berputar

### Informasi tambahan

Noted

**Comment by Zoel-WB** [comment]
Hal ini berlaku juga di Peta Area

![image](https://user-images.githubusercontent.com/64481641/154029485-acf3577b-98e3-4553-9946-615f5148f000.png)

**Comment by scqolbu24** [comment]
sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/759
