### ISSUE TITLE
[PREMIUM-22.02 BETA01] Impor Data_Contoh_Awal Token Premium Tak Berjalan Utk Semua Fitur

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#4877]
### Jelaskan error yg dialami

 Impor Data_Contoh_Awal Token Premium Tak Berjalan Utk Semua Fitur

### Cara untuk mereplikasi errornya

Buka Data Base -->Buat Database Baru (Catatan Tester pada Local Host)
Jalan System->Masuk Login
Pilih Layanan Pelanggan -->Masukkan Pengaturan Pelanggan-->Layanan Opendesa Token -> Pastekan Tokone Pilih Simpan

### Hasil yg diharapkan

System Premium Langsung Berfungsi Setelah Tokon Dimasukkan/Dipaste di Pengaturan Pelanggan

### Tangkapan layar dan log error

Setelah Token Langgan Dimasukkan
![image](https://user-images.githubusercontent.com/64481641/154035233-444e2498-32e7-4324-9dad-4563c3841671.png)

Menu Lainnya : -->Misalnya Pengaturan Database
![image](https://user-images.githubusercontent.com/64481641/154035575-7152f48d-14dc-482b-925c-97eb9624b2f3.png)

Menu Penduduk dan Menu Lainnya
![image](https://user-images.githubusercontent.com/64481641/154035724-2f0f712d-fc56-4164-a0c9-f27510bbc38e.png)

Fitur -> Pendaftaran Kerjasama
![image](https://user-images.githubusercontent.com/64481641/154035900-350804bc-999b-4463-9c8d-3ea917fd64e7.png)

Log Error
![image](https://user-images.githubusercontent.com/64481641/154035995-8e9d774f-9e2d-4c09-b2e7-dac99fbdcc67.png)

<html>
<body>

GuzzleHttp\Exception\ConnectException: cURL error 6: Could not resolve host: layanan.opendesa.idapi (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://layanan.opendesa.idapi/v1/pelanggan/daftarhitam in D:\https\Premium\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php:210Stack trace:#0 D:\https\Premium\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(158): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)#1 D:\https\Premium\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(110): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))#2 D:\https\Premium\vendor\guzzlehttp\guzzle\src\Handler\CurlHandler.php(47): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))#3 D:\https\Premium\vendor\guzzlehttp\guzzle\src\Handler\Proxy.php(28): GuzzleHttp\Handler\CurlHandler->__invoke(Object(GuzzleHttp\Psr7\Request), Array)#4 D:\https\Premium\vendor\guzzlehttp\guzzle\src\Handler\Proxy.php(48): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}(Object(GuzzleHttp\Psr7\Request), Array)#5 D:\https\Premium\vendor\guzzlehttp\guzzle\src\PrepareBodyMiddleware.php(64): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}(Object(GuzzleHttp\Psr7\Request), Array)#6 D:\https\Premium\vendor\guzzlehttp\guzzle\src\Middleware.php(31): GuzzleHttp\PrepareBodyMiddleware->__invoke(Object(GuzzleHttp\Psr7\Request), Array)#7 D:\https\Premium\vendor\guzzlehttp\guzzle\src\RedirectMiddleware.php(71): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Request), Array)#8 D:\https\Premium\vendor\guzzlehttp\guzzle\src\Middleware.php(63): GuzzleHttp\RedirectMiddleware->__invoke(Object(GuzzleHttp\Psr7\Request), Array)#9 D:\https\Premium\vendor\guzzlehttp\guzzle\src\HandlerStack.php(75): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Request), Array)#10 D:\https\Premium\vendor\guzzlehttp\guzzle\src\Client.php(331): GuzzleHttp\HandlerStack->__invoke(Object(GuzzleHttp\Psr7\Request), Array)#11 D:\https\Premium\vendor\guzzlehttp\guzzle\src\Client.php(168): GuzzleHttp\Client->transfer(Object(GuzzleHttp\Psr7\Request), Array)#12 D:\https\Premium\vendor\guzzlehttp\guzzle\src\Client.php(187): GuzzleHttp\Client->requestAsync('POST', Object(GuzzleHttp\Psr7\Uri), Array)#13 D:\https\Premium\vendor\guzzlehttp\guzzle\src\ClientTrait.php(95): GuzzleHttp\Client->request('POST', 'https://layanan...', Array)#14 D:\https\Premium\donjo-app\core\MY_Security.php(226) : eval()'d code(1) : eval()'d code(363): GuzzleHttp\Client->post('https://layanan...', Array)#15 D:\https\Premium\donjo-app\core\MY_Security.php(226) : eval()'d code(1) : eval()'d code(304): Premium->daftar_hitam()#16 D:\https\Premium\donjo-app\core\MY_Security.php(226) : eval()'d code(1) : eval()'d code(272): Premium->validasi_akses()#17 D:\https\Premium\donjo-app\core\MY_Security.php(226) : eval()'d code(1) : eval()'d code(382): Premium->validasi()#18 D:\https\Premium\donjo-app\core\MY_Security.php(226) : eval()'d code(1) : eval()'d code(47): Admin_Controller->__construct()#19 D:\https\Premium\vendor\codeigniter\framework\system\core\CodeIgniter.php(518): Penduduk->__construct()#20 D:\https\Premium\index.php(379): require_once('D:\\https\\Premiu...')#21 {main}
--
ERROR | 2022-02-15 16:40:50 | GuzzleHttp\Exception\ConnectException: cURL error 6: Could not resolve host: layanan.opendesa.idapi (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://layanan.opendesa.idapi/v1/pelanggan/daftarhitam in D:\https\Premium\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php:210
ERROR | 2022-02-15 16:40:11 | GuzzleHttp\Exception\ConnectException: cURL error 6: Could not resolve host: layanan.opendesa.idapi (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://layanan.opendesa.idapi/v1/pelanggan/daftarhitam in D:\https\Premium\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php:210
ERROR | 2022-02-15 16:39:36 | GuzzleHttp\Exception\ConnectException: cURL error 6: Could not resolve host: layanan.opendesa.idapi (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://layanan.opendesa.idapi/v1/pelanggan/daftarhitam in D:\https\Premium\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php:210
ERROR | 2022-02-15 16:31:48 | Severity: error --> Exception: cURL error 60: SSL certificate problem: certificate has expired (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://layanan.opendesa.id/api/v1/pelanggan/terdaftar?desa_id=52.01.14.2006 D:\https\Premium\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.
ERROR | 2022-02-15 16:31:46 | GuzzleHttp\Exception\ConnectException: cURL error 6: Could not resolve host: layanan.opendesa.idapi (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://layanan.opendesa.idapi/v1/pelanggan/daftarhitam in D:\https\Premium\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php:210
ERROR | 2022-02-15 16:30:13 | GuzzleHttp\Exception\ConnectException: cURL error 6: Could not resolve host: layanan.opendesa.idapi (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://layanan.opendesa.idapi/v1/pelanggan/daftarhitam in D:\https\Premium\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php:210
ERROR | 2022-02-15 16:30:12 | GuzzleHttp\Exception\ConnectException: cURL error 6: Could not resolve host: layanan.opendesa.idapi (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://layanan.opendesa.idapi/v1/pelanggan/daftarhitam in D:\https\Premium\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php:210
ERROR | 2022-02-15 16:30:10 | GuzzleHttp\Exception\ConnectException: cURL error 6: Could not resolve host: layanan.opendesa.idapi (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://layanan.opendesa.idapi/v1/pelanggan/daftarhitam in D:\https\Premium\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php:210
ERROR | 2022-02-15 16:30:08 | GuzzleHttp\Exception\ConnectException: cURL error 6: Could not resolve host: layanan.opendesa.idapi (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://layanan.opendesa.idapi/v1/pelanggan/daftarhitam in D:\https\Premium\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php:210

</body>
</html>[](http://localhost/Premium/info_sistem#collapse40)[](http://localhost/Premium/info_sistem#collapse39)[](http://localhost/Premium/info_sistem#collapse38)[](http://localhost/Premium/info_sistem#collapse37)[](http://localhost/Premium/info_sistem#collapse36)[](http://localhost/Premium/info_sistem#collapse35)[](http://localhost/Premium/info_sistem#collapse34)[](http://localhost/Premium/info_sistem#collapse33)[](http://localhost/Premium/info_sistem#collapse32)GuzzleHttp\Exception\ConnectException: cURL error 6: Could not resolve host: layanan.opendesa.idapi (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://layanan.opendesa.idapi/v1/pelanggan/daftarhitam in D:\https\Premium\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php:210

Stack trace:
#0 D:\https\Premium\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(158): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)
#1 D:\https\Premium\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(110): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#2 D:\https\Premium\vendor\guzzlehttp\guzzle\src\Handler\CurlHandler.php(47): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#3 D:\https\Premium\vendor\guzzlehttp\guzzle\src\Handler\Proxy.php(28): GuzzleHttp\Handler\CurlHandler->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#4 D:\https\Premium\vendor\guzzlehttp\guzzle\src\Handler\Proxy.php(48): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#5 D:\https\Premium\vendor\guzzlehttp\guzzle\src\PrepareBodyMiddleware.php(64): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#6 D:\https\Premium\vendor\guzzlehttp\guzzle\src\Middleware.php(31): GuzzleHttp\PrepareBodyMiddleware->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#7 D:\https\Premium\vendor\guzzlehttp\guzzle\src\RedirectMiddleware.php(71): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#8 D:\https\Premium\vendor\guzzlehttp\guzzle\src\Middleware.php(63): GuzzleHttp\RedirectMiddleware->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#9 D:\https\Premium\vendor\guzzlehttp\guzzle\src\HandlerStack.php(75): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#10 D:\https\Premium\vendor\guzzlehttp\guzzle\src\Client.php(331): GuzzleHttp\HandlerStack->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#11 D:\https\Premium\vendor\guzzlehttp\guzzle\src\Client.php(168): GuzzleHttp\Client->transfer(Object(GuzzleHttp\Psr7\Request), Array)
#12 D:\https\Premium\vendor\guzzlehttp\guzzle\src\Client.php(187): GuzzleHttp\Client->requestAsync('POST', Object(GuzzleHttp\Psr7\Uri), Array)
#13 D:\https\Premium\vendor\guzzlehttp\guzzle\src\ClientTrait.php(95): GuzzleHttp\Client->request('POST', 'https://layanan...', Array)
#14 D:\https\Premium\donjo-app\core\MY_Security.php(226) : eval()'d code(1) : eval()'d code(363): GuzzleHttp\Client->post('https://layanan...', Array)
#15 D:\https\Premium\donjo-app\core\MY_Security.php(226) : eval()'d code(1) : eval()'d code(304): Premium->daftar_hitam()
#16 D:\https\Premium\donjo-app\core\MY_Security.php(226) : eval()'d code(1) : eval()'d code(272): Premium->validasi_akses()
#17 D:\https\Premium\donjo-app\core\MY_Security.php(226) : eval()'d code(1) : eval()'d code(382): Premium->validasi()
#18 D:\https\Premium\donjo-app\core\MY_Security.php(226) : eval()'d code(1) : eval()'d code(47): Admin_Controller->__construct()
#19 D:\https\Premium\vendor\codeigniter\framework\system\core\CodeIgniter.php(518): Penduduk->__construct()
#20 D:\https\Premium\index.php(379): require_once('D:\\https\\Premiu...')
#21 {main}
ERROR
2022-02-15 16:40:50	GuzzleHttp\Exception\ConnectException: cURL error 6: Could not resolve host: layanan.opendesa.idapi (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://layanan.opendesa.idapi/v1/pelanggan/daftarhitam in D:\https\Premium\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php:210
ERROR
2022-02-15 16:40:11	GuzzleHttp\Exception\ConnectException: cURL error 6: Could not resolve host: layanan.opendesa.idapi (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://layanan.opendesa.idapi/v1/pelanggan/daftarhitam in D:\https\Premium\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php:210
ERROR
2022-02-15 16:39:36	GuzzleHttp\Exception\ConnectException: cURL error 6: Could not resolve host: layanan.opendesa.idapi (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://layanan.opendesa.idapi/v1/pelanggan/daftarhitam in D:\https\Premium\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php:210
ERROR
2022-02-15 16:31:48	Severity: error --> Exception: cURL error 60: SSL certificate problem: certificate has expired (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://layanan.opendesa.id/api/v1/pelanggan/terdaftar?desa_id=52.01.14.2006 D:\https\Premium\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.
ERROR
2022-02-15 16:31:46	GuzzleHttp\Exception\ConnectException: cURL error 6: Could not resolve host: layanan.opendesa.idapi (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://layanan.opendesa.idapi/v1/pelanggan/daftarhitam in D:\https\Premium\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php:210
ERROR
2022-02-15 16:30:13	GuzzleHttp\Exception\ConnectException: cURL error 6: Could not resolve host: layanan.opendesa.idapi (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://layanan.opendesa.idapi/v1/pelanggan/daftarhitam in D:\https\Premium\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php:210
ERROR
2022-02-15 16:30:12	GuzzleHttp\Exception\ConnectException: cURL error 6: Could not resolve host: layanan.opendesa.idapi (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://layanan.opendesa.idapi/v1/pelanggan/daftarhitam in D:\https\Premium\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php:210
ERROR
2022-02-15 16:30:10	GuzzleHttp\Exception\ConnectException: cURL error 6: Could not resolve host: layanan.opendesa.idapi (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://layanan.opendesa.idapi/v1/pelanggan/daftarhitam in D:\https\Premium\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php:210
ERROR
2022-02-15 16:30:08	GuzzleHttp\Exception\ConnectException: cURL error 6: Could not resolve host: layanan.opendesa.idapi (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://layanan.opendesa.idapi/v1/pelanggan/daftarhitam in D:\https\Premium\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php:210

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Premium (v22.02-beta01)

### Tema Yang Digunakan

Default

### Informasi tambahan

Menggunakan Folder Desa lama yg sudah ada

**Comment by Zoel-WB** [comment]
File Log
[log-2022-02-15.zip](https://github.com/OpenSID/OpenSID/files/8067880/log-2022-02-15.zip)

**Comment by agungsugiarto** [comment]
Pak @Zoel-WB apakah mengaksesnya lewat localhost?

**Comment by agungsugiarto** [comment]
Pak @Zoel-WB issue ini saya tutup, untuk bisa menjalankan dengan database baru silahkan rubah dulu desanya seesuai token untuk desa tersebut terima kasih.
