### ISSUE TITLE
[PREMIUM-22.02 BETA01] Edit Data atau Ubah Data Penduduk,  Tanggal Lahir Penduduk Ikut Berubah ke Tanggal Simpan Data

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#4879]
### Jelaskan error yg dialami

Saat melakukan edit salah satu data pendduduk-->tanggal Lahir Ikut Berganti Menjadi tanggal simpan ubah data

### Cara untuk mereplikasi errornya

Buka Fitur Data Penduduk
--> Pilih Salah satu Data Penduduk
--> Pilih Ubah Data --> Ganti atau ubah data apa saja
---> Simpan -->Buka Kembali atau Lihat Biodata Penduduk yang sudah edit biodatanya-->Lihat Data Tanggal Lahir

### Hasil yg diharapkan

Harga bila data penduduk di edit atau di ubah seupaya detail datanya jangan ikut terubah.... 

### Tangkapan layar dan log error

Data Berikut harusnya Tetap Tanggal : 01-08-1970

![image](https://user-images.githubusercontent.com/64481641/154050160-b04834e0-4622-4d3e-b843-7fceb1e6b0ec.png)

Form atau List Data Lainnya tidak menampilkan data, seharusnya data ini sudah lengkap

![image](https://user-images.githubusercontent.com/64481641/154050411-fc5a2976-1ea5-4347-8882-2521da732b61.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

 Premium (v22.02-beta02)

### Tema Yang Digunakan

default esensi

### Informasi tambahan

Data Isian Penduduk Lama, ada beberapa data tidak menampilkan nilai harusnya data ini sudah lengkap sejak awal input data penduduk

![image](https://user-images.githubusercontent.com/64481641/154050698-d1ab0546-af6f-4976-bfc3-a7d46ded41fd.png)

**Comment by yogiperdana** [comment]
Sudah diperbaiki melalui PR susulan
