### ISSUE TITLE
[PREMIUM-22.02 BETA01] Bug Halaman Pengaduan

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#4880]
### Jelaskan error yg dialami

 Bug Halaman Pengaduan

### Cara untuk mereplikasi errornya

Buka Website Pilih Pengaduan

### Hasil yg diharapkan

Agar dapat diterapkan dan berfungsi dengan baik

### Tangkapan layar dan log error

Tema : Natra Halaman Formulir Penngaduan Tidak Berfungsi
![image](https://user-images.githubusercontent.com/64481641/154065947-25212c62-a51a-410a-89eb-89a36e4d2389.png)

Tema Lainnya 
![image](https://user-images.githubusercontent.com/64481641/154066072-292a9f85-c0ac-4467-8fb8-f11860481258.png)

Walaupun Kode Captcha Ditolah dan apapun kode captcha dimasukkan semuanya tidak diterima, akan tetapi pengaduan terkirim
![image](https://user-images.githubusercontent.com/64481641/154066391-00c6aa29-f693-472a-87db-f8013a766aef.png)

Ada Pengaduan Terikirim atau masuk tanpa ada Otentitas

![image](https://user-images.githubusercontent.com/64481641/154066559-9d95b3f1-a40b-4697-86d5-54773d653b47.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

premium (v22.02-beta02)

### Tema Yang Digunakan

default

### Informasi tambahan

Noted

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui commit https://github.com/OpenSID/premium/commit/b2a47055dfb77d9202c6aa541872d17e3142e802
