### ISSUE TITLE
[PREMIUM-22.02 BETA01] Kirim Surat Layanan Mandiri Error 500 Perlu Pengkajian dimana Letak Kesalahannya

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#4881]
### Jelaskan error yg dialami

Terkait Isssue ini sudah pernah dibuat cuma tidak dapat di direpikasi Issue #4830
Sudah Melakukan Tester Dengan Data Asli Bawaan System Hasilnya Sama

### Cara untuk mereplikasi errornya

Impor Data Asli : Contoh_Data_Awal
Buat Surat Permhonan dengan Layanan Mandiri

### Hasil yg diharapkan

Supaya Bisa digunakan->karena bila ditest di Berputar tidak ada masalah yg ditemukan, akan tetapin menggunakan system desa tidak bisa mengirim permohonan melalui permohoman layanan mandiri.

### Tangkapan layar dan log error

Test Data Desa dari Hosting ada di issuse #4830
![image](https://user-images.githubusercontent.com/64481641/154087744-61b562c3-447f-4a21-bed3-faa76cdff73a.png)

Tester dari contoh_data_awal di Localhost

![image](https://user-images.githubusercontent.com/64481641/154088973-0d40dc62-727c-4157-9093-f1ac8459ce27.png)

![image](https://user-images.githubusercontent.com/64481641/154087795-0878faaa-4318-4221-8095-4e72f82f0ff9.png)

LOG ERROR
Query error: Column 'id_pemohon' cannot be null - Invalid query: INSERT INTO `permohonan_surat` (`no_antrian`, `id_pemohon`, `id_surat`, `isian_form`, `status`, `keterangan`, `no_hp_aktif`, `syarat`) VALUES (NULL, NULL, NULL, '[]', 1, 'Keterangan', '081269701118', '{\"2\":\"8\",\"3\":\"9\"}')

![image](https://user-images.githubusercontent.com/64481641/154089232-302957de-3fce-4d3f-9e35-cb55b2a5f445.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Premium v22.02-BETA02

### Tema Yang Digunakan

defaul

### Informasi tambahan

Terkait Issue Pernah dibuat di awal rillis v22.02-premium-->#4830

**Comment by scqolbu24** [comment]
sudah direplikasi lewat gmeet, tidak terjadi bug atau berjalan normal, maka dari itu issue ini di close.
