### ISSUE TITLE
[PREMIUM-22.02 BETA02] Belum dapat Melakukan Pendaftaran Layanan Mandiri melalu Fitur Layanan Mandiri

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#4882]
### Jelaskan error yg dialami

Belum dapat Melakukan Pendaftaran Layanan Mandiri melalu Fitur Layanan Mandiri :
1. Pilihan Tahun Tanggal Lahir tidak beraturan
2. Pengirim Pemdaftaran Tidak Dapat Dilakukan

### Cara untuk mereplikasi errornya

1. Buka Layanan Mandiri
2. Pilih PENDAFTARAN AKUN LAYANAN MANDIRI
3. Masukkan Data

### Hasil yg diharapkan

Berfungsi Normal

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/64481641/154096928-d6e06a3f-30c0-4e58-a546-4fe0294ec588.png)

![image](https://user-images.githubusercontent.com/64481641/154096980-9c825568-e53c-4ba3-bff8-a8bf7bb35b33.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

 premium (v22.02-beta02)

### Tema Yang Digunakan

berputar

### Informasi tambahan

https://berputar.opensid.or.id/layanan-mandiri/daftar

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melalui pr https://github.com/OpenSID/premium/pull/743
