### ISSUE TITLE
[PREMIUM-22.02 BETA02] Tombol Kembali Pada Fitur Arsip Desa->Detail Kependudukan->Harusnya Kembali Lagi Ke Dasboard Fitur Arsip Desa

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#4883]
### Jelaskan error yg dialami

Tombol Kembali Pada Fitur Arsip Desa->Detail Kependudukan->Harusnya Kembali Lagi Ke Dasboard Arsip Desa

### Cara untuk mereplikasi errornya

1. Buka Fitur Arsip Desa
2. Pilih Kependudukan

![image](https://user-images.githubusercontent.com/64481641/154106715-0fe57d8a-123e-44fe-8c9a-572e11f49598.png)

3. Pilih List Dokumen

![image](https://user-images.githubusercontent.com/64481641/154106866-831ddee1-0411-4940-b269-611bec78a4ec.png)

4. Pilih Kembali --> Harusnya Kembali Lagi Ke Dasboard Arsip Desa atau Ke Detail Data Kependudukan

![image](https://user-images.githubusercontent.com/64481641/154107132-a3d95a4e-b21e-44f8-b0ed-96efd9670b6f.png)

### Hasil yg diharapkan

Pilih Tombol Kembali -->dapat kembali ke Dasboard Arsip Desa ---.Bukan ke Biodata Penduduk atau Ada Tombol Tambahan untuk Kembali ke Dasboard Arsip Desa

### Tangkapan layar dan log error

Incluce --> Cara untuk mereplikasi errornya

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

premium (v22.02-beta02)

### Tema Yang Digunakan

default

### Informasi tambahan
Begitu Juga dengan Fitur-Fitur Arsip Desa Lainnya-->Ada Tombol Kembali Ke Dasboard Arsip Desa, sehingga untuk masuk dari satu arsip ke arsip lainnya tidak perlu lagi dimulai dari awal masuk.....

_No response_

**Comment by Zoel-WB** [comment]
Agak sulit juga menjelaskan fitur ini pak @yogiperdana karena di mulai dengan memilih Tombol "Tampilkan di modul aslinya" halamannya terhubung ke Fitur Plilih Aksi pada Data Penduduk....

![image](https://user-images.githubusercontent.com/64481641/167452798-4ce42177-539f-4b40-a2c6-a35832206618.png)

Tampilan halaman ini juga digunakan pada Halaman Pilih Aksi Data Penduduk

![image](https://user-images.githubusercontent.com/64481641/167453744-6d1676f7-b99f-4b2d-b24a-f509cea55b06.png)


![image](https://user-images.githubusercontent.com/64481641/167453419-1e845256-bdc6-4b6f-851d-988f6bfe649a.png)

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui commit https://github.com/OpenSID/premium/commit/82cb6e13422a48832f9f33d3643085b56077d50f
