### ISSUE TITLE
Desimal tidak dapat ditampilkan pada Transparansi APBDesa pada Footnote

### ISSUE THREAD

**Issue by mah-mudi** [OpenSID/OpenSID#4884]
**Jelaskan error yg dialami**

Desimal pada APBDesa di Footnote tidak dapat ditampilkan

**Gambar**

![IMG_20220216_005443.jpg](https://user-images.githubusercontent.com/57661283/154120537-1e5eb83b-1924-4ba9-a704-2e9d8c21aa1a.jpg)

**Hasil yg diharapkan**

Nominal Desimal APBDesa dapat ditampilkan sesuai input manual. 
Misal input Bidang Pemberdayaan Rp 103.539.494,15
Nominal Desimal dapat ditampilkan, sesuai pada siskeudes. 

**Rilis Versi OpenSID**

Rilis Premium

**Versi OpenSID**

v22.10-premium

**Tema Yang Digunakan**

Denava 2.0

Terima kasih.

**Comment by andifahruddinakas** [comment]
Untuk nominal rupiah, sy belum temukan yang nilainya desimal. Mungkin bisa disertakan contoh datanya.
