### ISSUE TITLE
[PREMIUM-22.02 BETA02] Sertifikat Data Vaksin Tidak Tampil saat Pilih Tombol Aksi [Tampilkan] 

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#4885]
### Jelaskan error yg dialami

Sertifikat Data Vaksin Tidak Tampil saat Pilih Tombol Aksi [Tampilkan]

### Cara untuk mereplikasi errornya

Pilih Fitur Vaksin
--> Cari Satu Data Penduduk yg sudah di lengkapi dengan semua sertifikat menurut jumlah vaksin yg dilaksanakan
--> Klik Aksi [Tampilkan] Sertifikat

![image](https://user-images.githubusercontent.com/64481641/154133881-b5febbc7-fa76-4113-a187-c135e35b3aba.png)

### Hasil yg diharapkan

Supaya normal dan berfungsi

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/64481641/154133528-bcea1c74-72f8-43c4-80d5-f8be28545a14.png)

![image](https://user-images.githubusercontent.com/64481641/154134594-c7bbed0b-06f0-404f-9cf4-ccc8bd0076aa.png)

![image](https://user-images.githubusercontent.com/64481641/154133556-d8a9cb4e-2956-4be5-be72-dfaf8aea8ff3.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

premium (v22.02-beta02)

### Tema Yang Digunakan

default

### Informasi tambahan

noted

**Comment by scqolbu24** [comment]
dokuemen/scan sertifikat vaksin apakah baru di upload atau sebelumnya sudah ada sebelum di migrasi?

**Comment by Zoel-WB** [comment]
> dokuemen/scan sertifikat vaksin apakah baru di upload atau sebelumnya sudah ada sebelum di migrasi?

sudah ada didalam sebelumnya

**Comment by Zoel-WB** [comment]
TAMBAHAN --> Langsung Disini saja pak  @scqolbu24 ya, ada keterkaitan dalam satu form

 
![image](https://user-images.githubusercontent.com/64481641/154208315-dcca7155-e3aa-4826-827b-ff013fa993f4.png)

**Comment by agungsugiarto** [comment]
Pak @Zoel-WB apakah sudah memastikan, aset sertifikat gambar tersebut ada di folder desa?

**Comment by scqolbu24** [comment]
sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/748
