### ISSUE TITLE
Bug/error: Migrasi supaya tidak menyembunyikan masalah fatal

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#4886]
### Jelaskan error yg dialami

Saat ini jika migrasi menambahkan indeks dan terdeteksi ada data duplikat yg mencegah pembuatan indeks, error hanya ditampilkan sesaat dan proses berlanjut. Sangat mungkin pengguna tidak sadar bahwa masalah yg terjadi bersifat fatal, yaitu akan menyebabkan error secara tidak terduga pada penggunaan selanjutnya.

Masalah fatal perlu dibuat lebih mencolok, supaya pengguna mencari penyebab dan solusinya.

### Cara untuk mereplikasi errornya

1. Buat atau cari database pada versi sebelum migrasi yg menambahkan indeks
2. Ubah database supaya ada data duplikat pada indeks yg akan dibuat
3. Pasang versi OpenSID yg berisi migrasi tersebut
4. Buka OpenSID supaya migrasi otomatis dijalankan. 
5. Lihat tampilan migrasi

### Hasil yg diharapkan

Exception terdeteksi dan ditampilkan secara eksplisit. 

Yaitu, ubah script di MY_model.php supaya tidak menyembunyikan error fatal. Laporkan masalahnya ke logs dan kemudian teruskan supaya ada exception database. 

![image](https://user-images.githubusercontent.com/249563/154171137-8d44832b-4aaf-4f90-8263-569d9d146355.png)

### Tangkapan layar dan log error

Di atas.

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.02-premium

### Informasi tambahan

Jika modul Periksa database telah digabung (https://github.com/OpenSID/premium/pull/739), exception yg terdeteksi akan otomatis ditindaklanjuti.

**Comment by andifahruddinakas** [comment]
Sudah digabungkan melalui PR https://github.com/OpenSID/premium/pull/747
