### ISSUE TITLE
Bug/error: Tidak sembunyikan tabel referensi tidak ada

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#4887]
### Jelaskan error yg dialami

Saat ini jika impor data penduduk dan terdeteksi tidak ada tabel referensi, error tidak ditampilkan dan proses berlanjut. Sangat mungkin pengguna tidak sadar bahwa masalah yg terjadi bersifat fatal, yaitu akan menyebabkan error secara tidak terduga pada penggunaan selanjutnya.

Masalah fatal perlu dibuat lebih mencolok, supaya pengguna mencari penyebab dan solusinya.

### Cara untuk mereplikasi errornya

1. Di database, hapus tabel referensi, seperti `ref_penduduk_hamil`.
2. Lakukan impor data penduduk dengan data valid.
3. Terlihat impor tidak ada notifikasi bahwa tabel referensi itu tidak ditemukan.

### Hasil yg diharapkan

Exception tidak ada tabel referensi terdeteksi dan ditampilkan secara eksplisit.

Yaitu, ubah script di `Referensi_model.php` supaya tidak menyembunyikan error fatal. Bisa laporkan masalahnya ke logs dan kemudian teruskan supaya ada exception database.

![image](https://user-images.githubusercontent.com/249563/154177674-5fd01245-b4d2-419f-b8c9-0c6af46137e9.png)

### Tangkapan layar dan log error

Di atas.

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.02-premium

### Informasi tambahan

Jika modul Periksa database telah digabung (https://github.com/OpenSID/premium/pull/739), exception yg terdeteksi akan otomatis ditindaklanjuti.

**Comment by scqolbu24** [comment]
sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/746
