### ISSUE TITLE
[PREMIUM] Bug/error: Gagal impor data penduduk pada kolom asuransi 

### ISSUE THREAD

**Issue by mizwaruddin** [OpenSID/OpenSID#4888]
### Jelaskan error yg dialami

Saat melakukan impor data penduduk menggunakan format excel hasil download di menu pengaturan->database->impor database terjadi kesalahan (gagal impor) jika kolom asuransi dan nomor asuransi diisi.

### Cara untuk mereplikasi errornya

1. Pengaturan->database->impor database
2. Pada form contoh impor penduduk, kolom asuransi dan nomor asuransi diisi
3. Muncul keterangan gagal impor pada bagian asuransi

### Hasil yg diharapkan

Ketika kolom asuransi dan nomor asuransi diisi tidak terjadi gagal impor

### Tangkapan layar dan log error

![bug_imporpenduduk](https://user-images.githubusercontent.com/39736008/154186740-b8b01821-cc57-46f0-ab1a-b0a20c41f5c5.png)
[FormatImportExcel (7).zip](https://github.com/OpenSID/OpenSID/files/8076321/FormatImportExcel.7.zip)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

OpenSID 22.02-premium-beta02

**Comment by scqolbu24** [comment]
sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/752
