### ISSUE TITLE
[PREMIUM] Bug/error: Tag ID terimpor di bagian suku/etnis saat melakukan impor data penduduk

### ISSUE THREAD

**Issue by mizwaruddin** [OpenSID/OpenSID#4889]
### Jelaskan error yg dialami

Tag ID terimpor di bagian suku/etnis saat melakukan impor data penduduk

### Cara untuk mereplikasi errornya

1. Pengaturan->database->impor database
2. Isikan tag id pada form excel impor penduduk
3. Tag ID terimpor pada bagian suku/etnis

### Hasil yg diharapkan

Tag ID terimpor dengan benar 

### Tangkapan layar dan log error

![bug_imporpenduduk_tagid2](https://user-images.githubusercontent.com/39736008/154187726-be268ed2-78f5-4e63-aca4-1649f3845cc7.png)

![bug_imporpenduduk_tagid1](https://user-images.githubusercontent.com/39736008/154187748-15fff0fb-4c07-4b43-aad2-8f984b18ba8b.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

OpenSID 22.02-premium-beta02

**Comment by scqolbu24** [comment]
issue ini merupakan satu kesatuan dengan issue https://github.com/OpenSID/OpenSID/issues/4888,
yang disebabkan karena pada file excel import tidak ada kolom suku

sehingga issue ini merupakan duplicat dan saya close.
