### ISSUE TITLE
[Login] Gunakan recaptcha dari Google pada page form Komentar dan Login

### ISSUE THREAD

**Issue by Jhiban-Khang** [OpenSID/OpenSID#489]
untuk meningkatkan keamanan, page login mohon ditambahkan chapcha dan dalam akun admin ada laporan/log agar aktifitas akun terpantau .

**Comment by rickzal13** [comment]
csrf token sepertinya udah cukup untuk keamanan login..
tapi klo mau di tambahin captcha google bisa.
mas @eddieridwan  atau @metalab25 ini bisa saya yang execute..

klo log systemnya nanti di diskusikan dulu..

**Comment by eddieridwan** [comment]
Permintaan laporan/log agar aktifitas pengguna sudah ada di issue #394.

**Comment by eddieridwan** [comment]
@rickzal13 , dulu anda menawarkan untuk menerapkan issue ini. Silakan. Tapi mungkin sebaiknya menggunakan captcha yang sudah ada di OpenSID (lihat di form komentar), daripada menambah plugin lainnya. Jika anda akan terapkan, silakan assign diri sendiri.

**Comment by eddieridwan** [comment]
@rickzal13 , tapi sepertinya recaptcha dari google lebih praktis dari yang sekarang ada di form komentar (https://webdesign.tutsplus.com/tutorials/how-to-integrate-no-captcha-recaptcha-in-your-website--cms-23024). Jadi silakan menggunakan recaptcha. Tapi anda harus bersedia sekalian mengubah form komentar supaya menggunakan recaptcha juga. Jadi konsisten. Beritahu jika anda akan kerjakan.

**Comment by eddieridwan** [comment]
@rickzal13 perlu diperhatikan, jika menggunakan recaptcha dari google, setiap desa perlu mendapatkan API key dan perlu mendaftarkan setiap domain yg akan menggunakan recaptcha itu. Jadi perlu _Recaptcha API Key_ perlu ditambahkan di setting aplikasi.

**Comment by rickzal13** [comment]
ok mas..

**Comment by eddieridwan** [comment]
@rickzal13 , Kami usul penerapan issue ini menggunakan pendekatan berikut:

1. sediakan setting aplikasi <em>recaptcha_api_key</em>
2. pada login admin (/siteman), 
    1. tampilkan recaptcha jika <em>recaptcha_api_key</em> ada; 
    2. jika <em>recaptcha_api_key</em> tidak ada, biarkan seperti sekarang, tanpa capcha
3. pada form komentar
    1. tampilkan recaptcha jika <em>recaptcha_api_key</em> ada; 
    2. jika <em>recaptcha_api_key</em> tidak ada, biarkan seperti sekarang, dengan capcha yang ada sekarang

**Comment by eddieridwan** [comment]
Setelah konsultasi dengan pengguna di https://www.facebook.com/groups/OpenSID/, pengguna lebih memilih cara menutup login sementara daripada menggunakan captcha. Dan juga akan membantu mencegah percobaan iseng oleh manusia.

Walaupun demikian, issue ini tidak ditutup, karena penggunaan recaptcha dari Google tetap bermanfaat untuk form komentar dan juga untuk login.
