### ISSUE TITLE
[PREMIUM] Bug/error: Tanggal lahir berubah menjadi tanggal sekarang saat melakukan edit data penduduk

### ISSUE THREAD

**Issue by mizwaruddin** [OpenSID/OpenSID#4890]
### Jelaskan error yg dialami

Tanggal lahir berubah menjadi tanggal sekarang saat melakukan edit data penduduk

### Cara untuk mereplikasi errornya

1. Kependudukan->penduduk
2. Pilih salah satu penduduk -> edit biodata
3. Tanggal lahir berubah menjadi tanggal saat ini

### Hasil yg diharapkan

Tanggal lahir tidak berubah menjadi tanggal sekarang

### Tangkapan layar dan log error

![bug_edit_penduduk](https://user-images.githubusercontent.com/39736008/154188361-99c1f3bd-b159-4bf1-838f-48efe582dd44.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

OpenSID 22.02-premium-beta02

**Comment by scqolbu24** [comment]
sudah dilaporkan di issue ini https://github.com/OpenSID/OpenSID/issues/4879
