### ISSUE TITLE
[PREMIUM] Bug/error: Data lembaga desa masuk hitungan data kelompok pada dashboard 

### ISSUE THREAD

**Issue by mizwaruddin** [OpenSID/OpenSID#4891]
### Jelaskan error yg dialami

Data lembaga desa masuk hitungan data kelompok pada dashboard 

### Cara untuk mereplikasi errornya

1. Info desa-> lembaga desa
2. Inputkan data lembaga desa
3. dashboard-> kelompok
4. Data kelompok pada dashboard bertambah setelah data lembaga desa terisi

### Hasil yg diharapkan

1. Data kelompok pada dashboard tidak bertambah setelah data lembaga desa terisi (hanya memuat data kelompok)
2. Tambahkan info lembaga desa pada dashboard

### Tangkapan layar dan log error

![bug_dashboard_kelompok](https://user-images.githubusercontent.com/39736008/154192930-30379ba6-1596-4675-800e-f11ff59f4b1f.png)
![bug_dashboard_kelompok2](https://user-images.githubusercontent.com/39736008/154192953-0cac4f02-b637-4997-9e05-e3b75db89111.png)
![bug_dashboard_kelompok3](https://user-images.githubusercontent.com/39736008/154192959-3d923022-e18e-4a84-804f-8de57eb6cde7.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

OpenSID 22.02-premium-beta02

**Comment by yogiperdana** [comment]
Sudah diperbaiki pada susulan PR melalui commit [20fa98a9870f626980702e912bb50ccdded62ad4 ](https://github.com/OpenSID/premium/commit/20fa98a9870f626980702e912bb50ccdded62ad4)
