### ISSUE TITLE
[PREMIUM] Bug/error: Nomor register berubah dari aturan baku saat edit data inventaris

### ISSUE THREAD

**Issue by mizwaruddin** [OpenSID/OpenSID#4892]
### Jelaskan error yg dialami

Nomor register berubah dari aturan baku saat edit data inventaris

### Cara untuk mereplikasi errornya

1. Sekretariat->inventaris
2. Pilih salah satu data inventaris->edit data
3. Pada field nama inventaris pilih nama selain nama yang terpilih
4. Pilih kembali nama yang terpilih
5. Nomor register tidak sesuai aturan baku

### Hasil yg diharapkan

Nomor register tetap sesuai aturan baku ketika melakukan edit

### Tangkapan layar dan log error

![bug_editinventaris](https://user-images.githubusercontent.com/39736008/154197053-cd2f3c93-05e6-47d5-8a7a-bd9298b54dd5.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

OpenSID 22.02-premium-beta02

### Informasi tambahan

Untuk mengatasi bug ini, opsi yang bisa dilakukan adalah dengan men-disable data ter-select.

![bug_editinventaris2](https://user-images.githubusercontent.com/39736008/154197303-74099ef7-1a21-45f9-82a1-af63cfcb7bf5.png)

Cara ini berhasil saya terapkan pada menu inventaris aplikasi BPD yg saya kembangkan.

**Comment by mizwaruddin** [comment]
Bug ini terjadi pada semua kategori inventaris

**Comment by yogiperdana** [comment]
Telah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/755
