### ISSUE TITLE
[PREMIUM] Bug/error: Total harga pada cetak inventaris tanah tidak tampil

### ISSUE THREAD

**Issue by mizwaruddin** [OpenSID/OpenSID#4893]
### Jelaskan error yg dialami

Total harga pada cetak inventaris tanah tidak tampil

### Cara untuk mereplikasi errornya

1. Sekretariat->inventaris-> tanah
2. Tambahkan data aset
3. Cetak
4. Pada hasil cetak total harga/nilai inventaris tidak tampil

### Hasil yg diharapkan

Total nilai aset tanah tampil

### Tangkapan layar dan log error

![bug_cetak_inventaris_tanah](https://user-images.githubusercontent.com/39736008/154199522-de6e9149-8dda-412d-84ea-1243785c4de3.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

OpenSID 22.02-premium-beta02

**Comment by scqolbu24** [comment]
sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/749
