### ISSUE TITLE
[PREMIUM] Permintaan fitur: Sembunyikan harga jual jika status jenis mutasi "Disumbangkan" pada detail mutasi

### ISSUE THREAD

**Issue by mizwaruddin** [OpenSID/OpenSID#4895]
### Apa kekurangan yg ingin diatasi?

Saat ini saat membukai detail mutasi inventaris (semua kategori inventaris), keterangan harga jual muncul ketika jenis mutasi "disumbangkan". Begitu juga sebaliknya, keterangan disumbangkan muncul ketika jenis mutasi "Dijual".

![fitur_mutasi_inventaris](https://user-images.githubusercontent.com/39736008/154201504-79ab36b9-434e-4cdb-85ea-07418f0be7ce.png)

### Jelaskan solusi yg diinginkan

Munculkan keterangan sesuai dengan jenis mutasi. Ketika jenis mutasi dijual, keterangan yg tampil adalah harga jual. Sedangkan jika jenis mutasi "Disumbangkan", maka keterangan yang muncul hanya "Disumbangkan"

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

OpenSID 22.02-premium-beta02

### Informasi tambahan

Berlakukan untuk semua kategori mutasi inventaris

**Comment by mizwaruddin** [comment]
![fitur_mutasi_inventaris2](https://user-images.githubusercontent.com/39736008/154201766-56017ebb-d2c3-4d26-8ce3-116b923b398d.png)

**Comment by mizwaruddin** [comment]
![fitur_mutasi_inventaris3](https://user-images.githubusercontent.com/39736008/154201889-eabf3fc1-d709-4040-978c-0b157426b919.png)

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/1023
