### ISSUE TITLE
[PREMIUM-22.02 BETA02] Filter Laporan Vaksin [Status Vaksin->Belum] ->Menurut [Pilihan Wilayah Dusun] Belum Berfungsi 

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#4896]
### Jelaskan error yg dialami

Saat Memfilter data yang belum vaksin berdasarkan dusun, data tidak tersaring menurut yang pilih, baik data status vaksi [belum vaksin] maupun data wilayah dusun.

### Cara untuk mereplikasi errornya

Pilih Fitur Vaksin -->Laporan Penduduk
Pilih Isian -->Kolom Status Vaksin Kategori -> Belum
Pilih Isian --> Pilihan Dusun --> Lihat Tampilan Dilayar Filter --.Maupun Pilih Cetak

![image](https://user-images.githubusercontent.com/64481641/154206654-f70c9a09-7a96-4ca8-8d55-a09b9368ade8.png)

### Hasil yg diharapkan

Supaya Data Falter bisa digunakan sesuai dengan filter kategori yang ada 

### Tangkapan layar dan log error

Hasil Filter --> Status Belum Vaksin --> Wilayah Dusun tertentu

![image](https://user-images.githubusercontent.com/64481641/154207115-29df260a-ff11-448a-8c29-2cb59ca5b42a.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

 premium (v22.02-beta01)

### Tema Yang Digunakan

default

### Informasi tambahan

Noted

**Comment by yogiperdana** [comment]
Telah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/757
