### ISSUE TITLE
[PREMIUM-22.02 BETA02] Impor Peta kml bertipe garis tidak langsung dapat disimpan

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#4897]
### Jelaskan error yg dialami

Impor Peta Garis dari dari peta KML : 
1. Impor KML --> Langsung Klik Tombol {Simpan]
2. Saat Ditampilkan Halaman Peta--.Sebagian Menu Layar Peta Hilang.

![image](https://user-images.githubusercontent.com/64481641/154265658-4ae2c863-4809-4b04-95b3-7b73999c60f1.png)

3. Saat Ditampilkan Dihalaman Peta

![image](https://user-images.githubusercontent.com/64481641/154266014-0d9296e3-f43f-49d4-80d0-00b276c7be91.png)

### Cara untuk mereplikasi errornya

1. Pilih Fitur Pemetaan ---> Pengaturan Peta
2. Pilih Peta --> Garis ---> Pilih Tambah Data Peta Baru

![image](https://user-images.githubusercontent.com/64481641/154266546-9501f26a-dcc7-4411-9e9d-13224cc52cfc.png)

3. Lakukan Impor Peta Garis KML -> Lalu langsung Simpan setelah di impor

![image](https://user-images.githubusercontent.com/64481641/154266695-d394d521-2773-457a-b025-150b03ff72d6.png)

Masuk Halaman Peta, Kemudian di tampilkan

![image](https://user-images.githubusercontent.com/64481641/154266902-a4b49d7d-dc90-4980-8206-e9f4d2ddacbd.png)

Berikut Contoh File .Kml
[Jl Desa.zip](https://github.com/OpenSID/OpenSID/files/8079935/Jl.Desa.zip)

### Hasil yg diharapkan

1. Setelah Mengimpor Peta Garis dari KML langsung dapat tersimpan, sehingga tidak lagi perlu harus digaris kembali di halaman buat peta, dan saat ditampilkan kembali halaman peta-->halaman normal tidak ada hal yg terganggu seperti hilangnya menu pada halaman seperti kondisi saat ini.

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/64481641/154267568-311f5393-5772-4a94-9687-e65346d009fe.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

 premium v22.02-beta02

### Tema Yang Digunakan

default

### Informasi tambahan

Bila Peta Setelah di impor --> tidak langsung disimpan -->Akan tetapi dibuat garis dengan cara manual sebelum disimpan
![image](https://user-images.githubusercontent.com/64481641/154268071-644377c5-a0e7-4f84-a564-cc084171164d.png)

Peta Normal

![image](https://user-images.githubusercontent.com/64481641/154268296-38e452ec-1863-4abc-aaf8-f9ffcf3a5ee8.png)

**Comment by agungsugiarto** [comment]
Pak @Zoel-WB bisa bagikan file importnya ?

**Comment by Zoel-WB** [comment]
> Pak @Zoel-WB bisa bagikan file importnya ?

Oke Pak.....
Filenya :
[Jl Desa.zip](https://github.com/OpenSID/OpenSID/files/8106199/Jl.Desa.zip)

**Comment by scqolbu24** [comment]
pada issue ini disebabkan karena perbedaan format peta yaitu hasil KML google sehingga tidak dapat di import ke format GPX, solusinya adalah di convert dari KML ke GPX, dapat menggunakan https://mygeodata.cloud/converter/kml-to-gpx untuk konversinya.

dari penjelasan tersebut issue ini di close.
