### ISSUE TITLE
[PREMIUM-22.02 BETA02] Statistik Program Bantuan Sasaran Rumah Tangga masih menghitung yg tidak aktif (RTM)

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#4898]
### Jelaskan error yg dialami

Penjumlahan Statistik Program Bantuan Sasaran Rumah Tangga, Jumlah Total RTM = 128
Yang Ter-Input Sebagai Peserta Program Bantuan Sasaran Rumah Tangga = 2
Seharusnya Yang Terjumlah Sebagai Jumlah Bukan Peserta adalah = 126  Tampil Disistem Jumlah = 128
Total Harusnya [Peserta = 2  + Bukan Peserta = 126  Total = 128]

Total yang Tampil Pada Sistem = 130 RTM ---> Melebihi dari pada jumlah RTM itu sendiri hanya 128 RTM

![image](https://user-images.githubusercontent.com/64481641/154311997-4e0853da-ac0f-490f-a937-78e12771070c.png)

### Cara untuk mereplikasi errornya

1.  Masuk Fitur Bantuan ---> Pilih Tambah Data Bantuan ---> Pilih Sasaran Rumah Tangga
2.  Input Data Beberapa Rumah Tangga Penerima Program Bantuan

Buka Statistik Program Bantuan ---> Pilih Kelompok Sasaran Program Bantuan Rumah Tangga

![image](https://user-images.githubusercontent.com/64481641/154312917-63721b90-50fb-45f3-927b-0a34e4dc2433.png)

### Hasil yg diharapkan

Perhitungan Statistiknya Disesuaikan

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/64481641/154313134-791091e4-ad2a-496c-b691-f0df01228a11.png)

TOTAL RTM SAAT INI

![image](https://user-images.githubusercontent.com/64481641/154313206-7b1192cf-f4e7-4e96-89cc-139ac27c0519.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Premium (v22.02-beta02)

### Tema Yang Digunakan

default

**Comment by eddieridwan** [comment]
@Zoel-WB saya tidak bisa replikasi masalah ini. Harap kirim database anda PM ke Telegram akun @eddieridwan untuk diperiksa. 

Apakah sdh dicoba di berputar?

**Comment by eddieridwan** [comment]
@Zoel-WB dari pemeriksaan data anda terlihat masalahnya disebabkan statistik kependudukan masih menghitung rumah tangga yg sudah tidak aktif, yaitu yg kepala rumah tangganya tidak ditemukan lagi atau status dasarnya bukan `hidup`.

**Comment by Zoel-WB** [comment]
> @Zoel-WB dari pemeriksaan data anda terlihat masalahnya disebabkan statistik kependudukan masih menghitung rumah tangga yg sudah tidak aktif, yaitu yg kepala rumah tangganya tidak ditemukan lagi atau status dasarnya bukan `hidup`.

Oke Pak @eddieridwan nanti saya coba chechk ulang data RTM system saya pak...

**Comment by scqolbu24** [comment]
sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/751

<img width="100%" alt="Data Peserta" src="https://user-images.githubusercontent.com/68048807/154449287-a0ea51f6-a958-4d90-a7c9-8d2ed2661fe3.PNG">
