### ISSUE TITLE
Permintaan fitur: Sesuaikan Nama Database

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#4900]
### Apa kekurangan yg ingin diatasi?

Bagi pengguna baru, akan bingung mengenai Judul pada Tab Pengaturan -> Database

<img width="960" alt="screenshot_148" src="https://user-images.githubusercontent.com/46939846/154388069-95aa71c8-5a39-4fe3-a65a-f7aa26e7eb11.png">

### Jelaskan solusi yg diinginkan

Sesuaikan judul agar mencerminkan isinya.

### Apakah ada alternatif lain

Tidak ada.

### Untuk versi OpenSID mana

Semua

**Comment by eddieridwan** [comment]
Catatan teknis bagi programmer:
1. sebaiknya fitur impor penduduk dipindahkan ke menu Kependudukan > Penduduk, supaya lebih konsisten dengan menu lain, dan juga supaya lebih jelas 
2. Impor BIP juga digabung dengan fitur impor penduduk di (1) di atas, karena impor BIP hanya merupakan format lain untuk mengimpor data penduduk
3. Demikian juga ekspor data penduduk pindahkan ke menu Kependudukan > Penduduk
3. selain itu, fitur impor rumah tangga juga pindahkan ke Kependuduk > Rumah Tangga, supaya lebih konsisten dengan menu lain, dan juga supaya lebih jelas

**Comment by andifahruddinakas** [comment]
Sudah dipisah pada rilis v22.04-premium
