### ISSUE TITLE
[PREMIUM] Bug/error: Filter kategori pada menu pemetaan tidak bekerja semestinya

### ISSUE THREAD

**Issue by mizwaruddin** [OpenSID/OpenSID#4902]
### Jelaskan error yg dialami

Saat melakukan filter peta (semua tipe peta) filter kategori dan jenis tidak bekerja semestinya.

### Cara untuk mereplikasi errornya

1. Pemetaan-> pengaturan peta
2. lakukan filter pada kategori kemudia lakukan filter jenis->filter kategori akan kembali ke default (kategori)

### Hasil yg diharapkan

Filter kategori bekerja normal

### Tangkapan layar dan log error

![bug_filter_peta](https://user-images.githubusercontent.com/39736008/154412622-da093831-8535-45e3-81f8-5c1da97df38f.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

OpenSID 22.02-premium-beta02

### Informasi tambahan

Untuk mengatasi masalah ini, urutan filter dapat diubah menjadi aktif/tidak aktif, jenis, kategori. Mengapa?
Klo dilihat pada susunan penambahan kategori berada di bawah jenis.

**Comment by yogiperdana** [comment]
Telah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/760
