### ISSUE TITLE
[PREMIUM-22.02 BETA02] Impor Data Penduduk dari Excel>>Penduduk Dengan Pilihan Jenis Asuransi Kesehtan "ASURANSI LAINNYA" dan "TIDAK/BELUM PUNYA ASURANSI" Tidak Ter-Impor 

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#4903]
### Jelaskan error yg dialami

Impor Data Penduduk dari Excel>>Penduduk Dengan Pilihan Jenis Asuransi Kesehtan "ASURANSI LAINNYA" dan "TIDAK/BELUM PUNYA ASURANSI" Tidak Ter-Impor

### Cara untuk mereplikasi errornya

1. Masuk List Detail Data Penduduk
2. Pilih Ubah Data---> Ubah Data -->DATA KESEHATAN
3. Gantikan Beberapa Penduduk dengan Jenis Asuransi ---> ASUNRANSI LAINNYA atau TIDAK/BELUM PUNYA
4. Lakukan Export Data Penduduk Ke File Excel
5. Kosong Semua Database
6. Coba Import Kembali Data Excel yg sudah di rubah data kesehatan bagian Asusransi Kesehatan

### Hasil yg diharapkan

Agar penduduk dengan perubahan beberapa pilihan detail data, ada atau atau tidak ada detail harusnya dapat impor.

### Tangkapan layar dan log error

DATA PENDUDUK ASLI

![image](https://user-images.githubusercontent.com/64481641/154421370-c7b737d3-0dc2-4d22-850c-52477fc1a003.png)

DATA PENDUDUK SETELAH DI RUBAH DATA JENIS ASURANSI KESEHATAN, atau data penduduk yg tidak diketahui JENIS ASURANSI KESEHATAN

![image](https://user-images.githubusercontent.com/64481641/154421514-5b20cc50-8b90-4974-a3ba-3c6bc8328ac7.png)

PESAN LAYAR SETELAH IMPOR
![image](https://user-images.githubusercontent.com/64481641/154422409-38ec625b-350a-4f30-8195-ff06a31ba336.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Premium (v22.02-Beta01)

### Tema Yang Digunakan

DEFAULT ESENSI

**Comment by scqolbu24** [comment]
Pak @Zoel-WB, apakah issue ini sama dengan issue https://github.com/OpenSID/OpenSID/issues/4888?

**Comment by Zoel-WB** [comment]
> Pak @Zoel-WB, apakah issue ini sama dengan issue #4888?

Belum memeriksa issue ini, tadi kejadian awal perbedaan data pada DPT atau pemilih, setelah impor data dari excel jumlah pemilih pada wilayah dusun ada yg berbeda dari data sebelumnya, kemudian saya coba kosong database dan saya test impor dari file excel, ternyata memang datanya memang ada kurang.... kedua jenis data saya gandingkan, saya adu untuk pemeriksaan satu persatu, itulah temuannya yang tidak ter-impor data dengan "Pilihan Jenis Asuransi Kesehatan Lainnya.

Kemudian menguji kembali merubah beberapa data dengan memilih Pilihan Jenis Pilihan Asuransi lainnya, dan mencoba impor ulang untuk memastikan, ternyata benar di plihan Asuransi masalahnya, baru kemudian saya buat issue-nya.

Bila issue-nya memang kejadiannya yg sama dapat digabungkan ke satu issue sebelumnya.

**Comment by scqolbu24** [comment]
issue ini merupakan satu kesatuan dengan issue https://github.com/OpenSID/OpenSID/issues/4888,
yang disebabkan karena pada file excel import tidak ada kolom suku

sehingga issue ini merupakan duplicat dan saya close.
