### ISSUE TITLE
Bug/error: Export data penduduk pada kolom asuransi menghasilkan nilai yang salah

### ISSUE THREAD

**Issue by yogiperdana** [OpenSID/OpenSID#4904]
### Jelaskan error yg dialami

Export data penduduk pada kolom asuransi menghasilkan nilai yang salah sehingga tidak bisa untuk diimport ulang

### Cara untuk mereplikasi errornya

1. Pengaturan
2. Database
3. Export database
4. Unduh

### Hasil yg diharapkan

Nilai yang dihasilkan berupa angka (bukan huruf/abjad)

### Tangkapan layar dan log error

![export](https://user-images.githubusercontent.com/14155050/154454250-46717635-eaa7-4989-8c2c-8b2f22b48859.JPG)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.02-premium

**Comment by scqolbu24** [comment]
sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/756
