### ISSUE TITLE
Bug/error: Error 500

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#4905]
### Jelaskan error yg dialami

Saat klik langsung untuk URL
https://berputar.opensid.or.id/siteman/reset_kata_sandi

akan muncul error 500

### Cara untuk mereplikasi errornya

Langsung akses URL https://berputar.opensid.or.id/siteman/reset_kata_sandi/

### Hasil yg diharapkan

Redirect ke halaman login, jika tidak melakukan reset password dengan permintaan yang sesuai.

### Tangkapan layar dan log error

Layar Error 500

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.03-premium

**Comment by yogiperdana** [comment]
Telah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/761
