### ISSUE TITLE
[PREMIUM] Bug/error: Username menggunakan tanda baca titik (.) tidak tampil di daftar pengguna

### ISSUE THREAD

**Issue by mizwaruddin** [OpenSID/OpenSID#4907]
### Jelaskan error yg dialami

Username menggunakan tanda baca titik (.) tidak tampil di daftar pengguna. Padahal tanda baca tersebut diizinkan dalam validation form

### Cara untuk mereplikasi errornya

1. Pengaturan-> pengguna
2. Tambah penggun baru / Edit
3. Tambahkan username mengandung tanda baca titik
4. Data tersimpan, namun tanda baca tersebut tidak tampil di daftar pengguna

### Hasil yg diharapkan

Tanda baca titik (.) tampil di daftar pengguna

### Tangkapan layar dan log error

![bug_pengguna1](https://user-images.githubusercontent.com/39736008/154656735-3f4654d0-74d9-48f3-96bc-516fb6c65fa8.png)

![bug_pengguna2](https://user-images.githubusercontent.com/39736008/154656893-6b8dea0b-5848-45ad-a2fd-1c2ae4ea24a5.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

OpenSID 22.02-premium-beta02

**Comment by yogiperdana** [comment]
Perbaikan username mangacu pada username yang ditetapkan pada pembuatan google akun yang disesuaikan dengan kebutuhan opensid. Adapun aturan username di opensid adalah sebagai berikut:
1. Terdiri dari nomor, huruf, titik dan garis bawah
2. Tidak diawali dan diakhiri dengan titik atau garis bawah
3. Tidak mengandung titik atau garis bawah secara berturut-turut 2 kali
4. Terdiri dari 6-30 karakter

Referensi:
https://support.google.com/mail/answer/9211434?hl=en#:~:text=Usernames%20can%20contain%20letters%20(a%2Dz,more%20than%20one%20period%20(.)

**Comment by scqolbu24** [comment]
sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/767
