### ISSUE TITLE
[PREMIUM] Bug/error: Tanda baca titik, petik satu, dan koma pada nama pengguna tidak tampil di daftar pengguna

### ISSUE THREAD

**Issue by mizwaruddin** [OpenSID/OpenSID#4908]
### Jelaskan error yg dialami

Tanda baca titik, petik satu, dan koma pada nama pengguna tidak tampil di daftar pengguna

### Cara untuk mereplikasi errornya

1. Pengaturan-> pengguna
2. Tambah pengguna baru / edit
3. Pada field nama pengguna tambahkan nama yang mengandung tanda baca: titik, petik satu, koma
4. Data tersimpan, namun pada daftar pengguna tanda baca tersebut tidak tampil

### Hasil yg diharapkan

Tanda baca yang diperbolehkan di data penduduk juga tampil di daftar pengguna

### Tangkapan layar dan log error

![bug_pengguna3](https://user-images.githubusercontent.com/39736008/154657619-b3023198-f685-4306-8bbc-ed8499922adc.png)

![bug_pengguna4](https://user-images.githubusercontent.com/39736008/154657682-f9cf9ef6-5b67-4d0c-8b07-56bd9e214d9a.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

OpenSID 22.02-premium-beta02

**Comment by scqolbu24** [comment]
sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/768
