### ISSUE TITLE
[PREMIUM] Bug/error: inventaris yang sudah dimutasi tetap tampil di total nilai aset inventaris gedung dan bangunan

### ISSUE THREAD

**Issue by mizwaruddin** [OpenSID/OpenSID#4909]
### Jelaskan error yg dialami

Total nilai aset inventaris peralatan dan mesin tidak tampil

### Cara untuk mereplikasi errornya

1. Sekretariat-> inventaris-> gedung dan bangunan
2. Tambahkan data kemudian lakukan mutasi
3. Inventaris yang sudah dimutasi nilainya tetap tampil di total harga

### Hasil yg diharapkan

inventaris yang sudah dimutasi nilainya tidak masuk perhitungan total harga/aset

### Tangkapan layar dan log error

![bug_total_inventaris-gedung](https://user-images.githubusercontent.com/39736008/154671046-e268988e-ab12-4b98-9c9f-46b98697835b.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

OpenSID 22.02-premium-beta02

**Comment by yogiperdana** [comment]
Bagaimana dengan total pada saat dicetak pak? Apakah hanya menampilkan total gedung yang tidak dimutasi atau total semua gedung termasuk yang sudah dimutasi?

**Comment by yogiperdana** [comment]
Issue ini di-close karena bug tidak dapat direplikasi
