### ISSUE TITLE
[PREMIUM] Bug/error: Virtual keyboard saat verifikasi email layanan mandiri hanya berupa numerik (angka)

### ISSUE THREAD

**Issue by rudiansyahyunanda** [OpenSID/OpenSID#4911]
### Jelaskan error yg dialami

ketika login layanan mandiri pada anjungan yang mengaktifkan virtual keyboard, pada saat verifikasi email virtual keybord hanya menampilkan tombol-tombol yang berisi anka 0-9 saja. percobaan juga dilakukan pada web : https://berputar.opensid.or.id/

### Cara untuk mereplikasi errornya

1. Login Layanan Mandiri 
2. Klik tombol Verifikasi
3. Pilih Email
4. Pada langkah ke 2 saat diminta memasukkan email
5. Virtual Keyboard hanya menampilkan angka 0-9

### Hasil yg diharapkan

Virtual Keyboard yang memungkinkan untuk mengetikkan email (keyboard virtual lengkap)

### Tangkapan layar dan log error

![2022-02-19_02h33_45](https://user-images.githubusercontent.com/50880846/154751009-266ca186-8b5b-4a18-a4bf-14cded5ab219.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.02

### Tema Yang Digunakan

Semua

**Comment by scqolbu24** [comment]
sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/773
