### ISSUE TITLE
Bug/error: Terjadi Loading Lama

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#4912]
### Jelaskan error yg dialami

Ketika login halaman admin, setelah ketik username dan password klik login maka proses lama sekali (sekitar 3 menit)
sampai muncul gambar berikut.

<img width="960" alt="screenshot_283" src="https://user-images.githubusercontent.com/46939846/154778415-e5d3aef0-9457-4869-b95e-7330cc74462d.png">

### Cara untuk mereplikasi errornya

Seperti di atas

### Hasil yg diharapkan

Normal kembali

### Tangkapan layar dan log error

<img width="960" alt="screenshot_284" src="https://user-images.githubusercontent.com/46939846/154778426-b4d472f4-5f4b-4977-838f-d3bd846424d5.png">

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.01-premium-rev01

**Comment by agungsugiarto** [comment]
Pak @ariandii karena ini terkait server, apakah bisa dijanjikan pertemuan untuk membahas ?
