### ISSUE TITLE
[PREMIUM] Bug/error: KK hasil impor penduduk susulan tidak tercatat di laporan bulanan

### ISSUE THREAD

**Issue by mizwaruddin** [OpenSID/OpenSID#4913]
### Jelaskan error yg dialami

KK hasil impor penduduk susulan tidak tercatat di laporan bulanan

### Cara untuk mereplikasi errornya

1. Lakukan impor penduduk susulan (setelah melakukan impor penduduk pertama) melalui: pengaturan->database->impor database
2. Cek laporan bulanan. KK tidak bertambah

### Hasil yg diharapkan

KK hasil impor susulan tercatat di laporan bulanan

### Tangkapan layar dan log error

![bug_laporanbulanan2](https://user-images.githubusercontent.com/39736008/154786536-bedebfb6-9a82-4ba6-8bf4-230571ff003c.png)

![bug_laporanbulanan1](https://user-images.githubusercontent.com/39736008/154786544-ab10bbe9-b1dd-4cff-b18d-fea649409a98.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

OpenSID 22.02-premium-beta02

**Comment by mizwaruddin** [comment]
Terjadi juga pada impor penduduk menggunakan format BIP

**Comment by agungsugiarto** [comment]
Pak @mizwaruddin saya tidak bisa meriplikasi issuenya, bisa kirimkan format import pertama dan susulannya ke telegram saya?

**Comment by mizwaruddin** [comment]
Ini sdh sya replikasi bareng Mas Sarwono via discord. Mas Sarwono jg mengalami bug ini.

**Comment by eddieridwan** [comment]
Bung @agungsugiarto , peran impor penduduk perlu ditinjau ulang. Karena bersifat agak rentan, dengan alur ketentuan yg kurang jelas. Terutama masalah status dasar. Sebaiknya status dasar tidak bisa diekspor/impor.

Terlihat ekspor/impor penduduk menjadi sumber banyak masalah yang dilaporkan pengguna, karena kerancuan alur/ketentuan saat ini.

**Mohon kita bahas dulu sebelum perbaikan diterapkan. Termasuk mencatat persisnya aturan/ketentuan apa yg dilakukan pada data yg diimpor.**

Peran ekspor/impor data penduduk BUKAN untuk backup/restore. Melainkan peran ekspor/impor perlu kita batasi sebagai berikut:

1. impor data penduduk awal
2. penambahan data penduduk
3. perubahan data penduduk

Tetapi TIDAK untuk:

1. menghapus data penduduk
2. mengubah status dasar penduduk

Yang masih perlu ditelaah lebih lanjut:

1. Apakah boleh mengubah hubungan dalam keluarga. Misalnya mengubah kepala keluarga
2. Apakah boleh pindah keluarga. Misalnya mengubah no kk seorang penduduk

**Comment by yogiperdana** [comment]
Telah diperbaiki melalui issue https://github.com/OpenSID/OpenSID/issues/4996
