### ISSUE TITLE
[PREMIUM] Bug/error: Pilihan jawaban hilang jika dilakukan edit data indikator dan pertanyaan di modul analisis

### ISSUE THREAD

**Issue by mizwaruddin** [OpenSID/OpenSID#4915]
### Jelaskan error yg dialami

Pilihan jawaban hilang jika dilakukan perubahan/edit data indikator dan pertanyaan di modul analisis. Jika sudah terlanjur melakukan input data kemudian melakukan perubahan setting di "publikasi indikator" maka jawaban yg sdh diinputkan juga akan hilang. Bug ini hanya berlaku untuk analisis baru. Untuk analisis bawaan sistem tidak ada masalah.

### Cara untuk mereplikasi errornya

1. Analisis->master analisis->tambah analisis baru
2. Lakukan penambahan data pada setiap item di Pengaturan Analisis
3. Buka bagian indikator & pertanyaan, lakukan perubahan atau tanpa perubahan kemudian simpan
4. Buka jawaban pada indikator/pertanyaan yang dilakukan perubahan tadi
5. pertanyaan menjadi kosong.

### Hasil yg diharapkan

Pertanyaan tidak hilang setelah dilakukan perubahan data indikator dan pertanyaan

### Tangkapan layar dan log error

![bug_analisis_indikator2](https://user-images.githubusercontent.com/39736008/154787672-f883199c-e8b0-400f-880a-e2b9350ce949.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

OpenSID 22.02-premium-beta02

**Comment by andifahruddinakas** [comment]
Sudah digabung melalui commit https://github.com/OpenSID/premium/commit/8999709d7ba664f85a894ad4c22d72ec5d4dc776
