### ISSUE TITLE
[PREMIUM-22.02 BETA02] Tampilan Halaman (Paging) Pada Website atau Filter Statistik

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/OpenSID#4917]
### Jelaskan error yg dialami

Saat ini Halaman paging yang ditampilkan di web normal atau belum dapat diketahui bug atau erornya karena data yang di entri baru berjumlah 288, namun jika data tersebut sudah melebihi 500, maka bug error yang dialamai sama seperti halnya pada issue https://github.com/OpenSID/OpenSID/issues/4875.

Bedanya pada issue https://github.com/OpenSID/OpenSID/issues/4875 yang ditampikan adalah 10 entri saja 
dan pada issue ini (Tampilan Halaman (Paging) Pada Website atau Filter Statistik) jika melebihi 500 maka yang tampil adalah 500 entri saja. 

### Cara untuk mereplikasi errornya

1. Masuk/Login ke halaman admin.
2. Buka Halaman statistik >> bantuan_keluarga di halaman website

### Hasil yg diharapkan

dapat menampilkan data sesuai dengan jumlah inputan.

### Tangkapan layar dan log error

<img width="100%" alt="Paging-statistik" src="https://user-images.githubusercontent.com/68048807/154788985-dc237b52-f722-43a9-8dfb-152c8a0107a8.PNG">

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.02-premium beta-02

### Tema Yang Digunakan

semua tema

### Informasi tambahan

issue ini sama pada issue https://github.com/OpenSID/OpenSID/issues/4875,
pada issue ini sebaiknya session per page statis (per page = 500) diganti dinamis sesuai dengan jumlah data inputan.

<img width="70%" alt="per_page" src="https://user-images.githubusercontent.com/68048807/154789244-f65521b3-6d54-47a2-875c-f1f8bdbe0852.PNG">

**Comment by andifahruddinakas** [comment]
@scqolbu24, hapus batas/limit tampilkan seluruh data sj. pada web gunakan datatables untuk memudahkan.

**Comment by scqolbu24** [comment]
issue ini ditutup karena source code yang tidak dipakai, sehingga dihapus source tersebut, 
perbaikannya perubahan teknis. pada PR https://github.com/OpenSID/premium/pull/772
