### ISSUE TITLE
[PREMIUM] Bug/error: Penduduk dengan status "tidak valid" terhitung dalam laporan bulanan

### ISSUE THREAD

**Issue by mizwaruddin** [OpenSID/OpenSID#4918]
### Jelaskan error yg dialami

Penduduk dengan status "tidak valid" terhitung dalam laporan bulanan

### Cara untuk mereplikasi errornya

1. Pengaturan-> database -> impor BIP
2. Lakukan impor BIP menggunakan format siak menggunakan data contoh
3. Terjadi selisih data jumlah data penduduk antara data di dashboard dan di laporan bulanan
4. Penyebabnya karena ada data penduduk dengan status tidak valid dalam data contoh tersebut--di mana di dashboard status tidak valid tidak dihitung, sedangkan di laporan bulanan dihitung

### Hasil yg diharapkan

Penduduk dengan status tidak valid tidak dihitung dalam laporan bulanan

### Tangkapan layar dan log error

![bug_laporanbulanan1](https://user-images.githubusercontent.com/39736008/154791125-caabc185-1c8d-4c46-b7dd-373111f4dda9.png)
![bug_laporanbulanan2](https://user-images.githubusercontent.com/39736008/154791127-11be97a8-7863-49f8-8c3c-effddf5cd830.png)
![bug_laporanbulanan3](https://user-images.githubusercontent.com/39736008/154791130-e62fe406-df21-46c9-bdb6-15d2f5ae95c1.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

OpenSID 22.02-premium-beta02

**Comment by yogiperdana** [comment]
Telah diperbaiki melalui issue https://github.com/OpenSID/OpenSID/issues/4996
