### ISSUE TITLE
Permintaan fitur: Munculkan isian KITAS hanya pada status WNA

### ISSUE THREAD

**Issue by mizwaruddin** [OpenSID/OpenSID#4919]
### Apa kekurangan yg ingin diatasi?

Saat ini isian KITAS muncul pada status kewarganegaraan WNI dan WNA saat menambahkan/mengedit biodata penduduk. Padahal isian KITAS tidak diperlukan pada penduduk WNI.

### Jelaskan solusi yg diinginkan

Munculkan isian KITAS jika status kewarganegaraan penduduk WNA saja.

### Apakah ada alternatif lain

Tidak ada

### Untuk versi OpenSID mana

OpenSID 22.02-premium-beta02

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/1024
