### ISSUE TITLE
Layanan Mandiri pada Menu Laporan, data tidak bisa di hapus

### ISSUE THREAD

**Issue by GusAde** [OpenSID/OpenSID#492]
Sebelum di rilisnya versi berikutnya, mohon dicek untuk para master2 OpenSID, pada layanan mandiri di menu laporan, data tidak bisa dihapus jika data penduduk orang yang terdaftar di layanan mandiri sudah pindah domisili / dihapus.

![untitled](https://user-images.githubusercontent.com/29674166/27824911-888a33da-60e0-11e7-8b90-de7dbf8d0af8.png)

**Comment by eddieridwan** [comment]
Error ini tidak ditemukan lagi di versi v19.02-pasca.
