### ISSUE TITLE
Bug/error: Beberapa menu/tombol pada peta area tidak tampil setelah koordinat area dikosongkan dikosongkan

### ISSUE THREAD

**Issue by yogiperdana** [OpenSID/OpenSID#4920]
### Jelaskan error yg dialami

Issue ini merupakan memiliki masalah yang sama dengan issue https://github.com/OpenSID/OpenSID/issues/4876 namun terjadi pada menu peta area. Yaitu beberapa menu/tombol pada peta area tidak tampil setelah koordinat area dikosongkan dikosongkan

### Cara untuk mereplikasi errornya

1. Buka pemetaan > pengaturan peta
2. Pilih area
3. Edit salah satu lokasi area
4. Hapus koordinat area yang sudah terisi
5. Simpan

### Hasil yg diharapkan

Menu atau tombol pada peta tidak hilang

### Tangkapan layar dan log error

![peta area](https://user-images.githubusercontent.com/14155050/154792242-573d5b99-c9b5-45e3-acfb-3b3c1a8a4866.JPG)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.02-premium

**Comment by scqolbu24** [comment]
sduah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/765
