### ISSUE TITLE
[PREMIUM] Bug/error: Tombol Tipe Pertanyaan masih berfungsi ketika indikator dihubungkan Dengan Data Keluarga / KK pada modul analisis

### ISSUE THREAD

**Issue by mizwaruddin** [OpenSID/OpenSID#4921]
### Jelaskan error yg dialami

Tombol Tipe Pertanyaan masih berfungsi ketika indikator dihubungkan Dengan Data Keluarga / KK pada modul analisis. Padahal pada tampilannya cursor menunjukkan stop--yang semestinya disable/tidak aktif-- karena jika pertanyaan dihubungkan dengan data penduduk/keluarga seharusnya hanya tombol isian teks yg aktif.

### Cara untuk mereplikasi errornya

1. Analisis-> master analisis
2. Tambah analisis baru
3. Indikator & Pertanyaan-> tambah indikator baru
4. Pada isian "Hubungkan Dengan Data Keluarga / KK" pilih salah satu.
5. Tombol pada bagian Tipe Pertanyaan tampil disable, namun tombol2 tsb masih bisa dipilih (berfungsi)

### Hasil yg diharapkan

Ketika isian "Hubungkan Dengan Data Keluarga / KK" dipilih salah satu, secara default tombol Tipe Pertanyaan yg aktif adalah tombol "isian teks (kualitatif)" dan tombol lainnya tidak aktif.

### Tangkapan layar dan log error

![bug_analisis_hubungkan](https://user-images.githubusercontent.com/39736008/154792628-ff0b6dcc-d4c8-404d-a515-06e77a07ad77.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

OpenSID 22.02-premium-beta02

### Informasi tambahan

Jika tombol laiinya aktif dan bisa dipilih, hal itu akan sia2 dan akan menimbulkan bug lainnya, berupa tidak ada tombol tambah jawaban.

**Comment by scqolbu24** [comment]
sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/779
