### ISSUE TITLE
[PREMIUM-22.02 BETA02] Fitur Edit dan Simpan Data Lapak Desa Tidak Berfungsi

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#4922]
### Jelaskan error yg dialami

[PREMIUM-22.02 BETA02] Fitur Edit dan Simpan Data Lapak Desa Tidak Berfungsi

### Cara untuk mereplikasi errornya

1. Buka Fitur Lapak
2. Pilih Salah Satu Produik -->Klik Edit
3. Edit Data Apa saja atau Upload Ganti Foto
4. Pilih Simpan
![image](https://user-images.githubusercontent.com/64481641/154806653-13562d3d-d37d-4798-8ee2-93a99a75c7d4.png)

### Hasil yg diharapkan

Supaya Semua Kebutuhan Yang Berhubungan Edit Data Berfungsi dengan Baik  

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/64481641/154806497-56689143-8656-4684-8e3d-ef0327bd5e47.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

premium (V22.02-Premium)

### Tema Yang Digunakan

default

### Informasi tambahan

noted

**Comment by Zoel-WB** [comment]
Sudah di Tester di Berputar--> Juga tidak dapat disimpan setelah edit data
https://berputar.opensid.or.id/lapak_admin/produk_form/2
![image](https://user-images.githubusercontent.com/64481641/154828312-9047c10f-1b94-4d41-b269-2fb4a417bb9d.png)

**Comment by Zoel-WB** [comment]
Bug ini terjadi saat edit foto atau ganti foto produk
Buka edit --> pilih uploap foto atau ganti foto produk tanpa merubah data lain.... klik simpan, tombol simpan tak respon

**Comment by scqolbu24** [comment]
sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/769
