### ISSUE TITLE
Permintaan fitur: Pindahkan impor rumah tangga ke modul Rumah Tangga

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#4924]
### Apa kekurangan yg ingin diatasi?

Saat ini fitur untuk impor data rumah tangga ada di `Pengaturan > Database > Impor Database` yang membingungkan bagi pengguna pemula.

### Jelaskan solusi yg diinginkan

Pindahkan impor data rumah tangga ke modul rumah tangga. 

### Apakah ada alternatif lain

Tidak ada.

### Untuk versi OpenSID mana

v22.02-premium

**Comment by FirlianiF** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/766
