### ISSUE TITLE
[PREMIUM] Permintaan Required Data Isian Biodata Data Anggota Keluarga (Prodeskel) Otomatis Terisi dari Data Penduduk

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#4925]
### Apa kekurangan yg ingin diatasi?

Permintaan supaya data-data yg berkenaan biodata penduduk pada Template [Data Anggota Keluarga] dapat terisi secara otomatis dari database penduduk, sehingga tidak terjadi double isi data serta menghindari kekeliruan data salah

### Jelaskan solusi yg diinginkan

Data-data seperti screensote berikut 👍 
![image](https://user-images.githubusercontent.com/64481641/154840850-2fb45d4b-565c-44e7-a569-52b4eb760eb9.png)
DAN DATA BERIKUT
![image](https://user-images.githubusercontent.com/64481641/154840914-3ab110f5-93d1-4cf3-8846-82cf5e92fb94.png)
 
Karena Data ini sudah ada dalam database penduduk

### Apakah ada alternatif lain

noted

### Untuk versi OpenSID mana

Premium

### Informasi tambahan

noted

**Comment by eddieridwan** [comment]
Bukannya fitur menghubungkan pertanyaan ke data penduduk sudah tersedia?

**Comment by Zoel-WB** [comment]
> Bukannya fitur menghubungkan pertanyaan ke data penduduk sudah tersedia?

Iya pak @eddieridwan maksud data-data yang sudah ada dalam biodata penduduk seperti "hubungan keluarga, pekerjaan, pendidikan terakhir, nama ayah kandung, nama ibu kandung" bisa langsung masuk otomatis tanpa harus mengimput ulang lagi...
