### ISSUE TITLE
Aplikasi widget aparatur

### ISSUE THREAD

**Issue by kelbatuix** [OpenSID/OpenSID#493]
Untuk aplikasi widget aparatur mohon untuk dapat menampilkan tulisan nama, nip dan jabatannya sesuai data yang diisi mas, biar makin mantap. . .

**Comment by kelbatuix** [comment]
Kemudian mohon banuan untuk setting nama widget aparatur desa, nama desanya tidak berubah menjadi kelurahan. dan nama widget peta lokasi kantor tertulis lokasi_nama desa, tidak tertulis lokasi kantor_nama desa/kelurahan

**Comment by eddieridwan** [comment]
@kelbatuix: Satu issue sebaiknya satu masalah saja. Karena penerapannya juga per masalah. Belum tentu semua masalah diproses bersamaan. Issue kedua di atas telah dipindahkan ke #494.

**Comment by eddieridwan** [comment]
Nama dan jabatan sekarang ditampilkan di atas foto aparatur desa secara otomatis.
Sudah dicommit ke master.
