### ISSUE TITLE
Bug/error: Error Info Covid

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#4930]
### Jelaskan error yg dialami

<img width="960" alt="screenshot_298" src="https://user-images.githubusercontent.com/46939846/154942238-31eda0b5-4593-4149-b454-0005acf673a4.png">

<img width="960" alt="screenshot_299" src="https://user-images.githubusercontent.com/46939846/154942262-5a2eb93a-a16f-4271-a2f1-2aa4fb0a6a81.png">

### Cara untuk mereplikasi errornya

Seperti gambar di atas

### Hasil yg diharapkan

Adanya perubahan sumber API sehingga dapat muncul kembali.

Atau jika ini di nonaktifkan, log pada info sistem tetap muncul,
yakni:

Error occured while loading url by cURL.

Could not resolve host: api.kawalcorona.com

### Tangkapan layar dan log error

Seperti di atas

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Berputar

**Comment by agungsugiarto** [comment]
Error ini karena api.kawalcorona.com yg sudah tidak bisa diakses?

**Comment by scqolbu24** [comment]
Langkah untuk solusi ini dari hasil pertemuan rutin:
1. Apabila API yang digunakan masih belum ditemukan maka fitur di non aktifkan (data tidak ditemukan).
2. Mencari refrensi lain kepada pengguna yang menyediakan API Covid 19.

**Comment by yogiperdana** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/786
