### ISSUE TITLE
Bug/error: Jumlah Data di Layanan Mandiri tidak sesuai seharusnya.

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#4931]
### Jelaskan error yg dialami

Ketika salah 1 penduduk yang sebelumnya telah dibuatkan akun login layanan mandiri, kemudian penduduk tersebut pindah/meninggal/dsb maka di tabel pendaftaran layanan mandiri baris penduduk tersebut tetap ada walau identitasnya sudah terhapus.

Penjelasan ada di gambar bawah ini.

### Cara untuk mereplikasi errornya

seperti di atas.

### Hasil yg diharapkan

Normal.

### Tangkapan layar dan log error

<img width="960" alt="screenshot_300" src="https://user-images.githubusercontent.com/46939846/154954968-ba7a8415-6d0f-4cd9-95c0-ec879a76d13b.png">

<img width="960" alt="screenshot_301" src="https://user-images.githubusercontent.com/46939846/154954977-dc19d552-e0ac-459e-bc25-4adfa07f67cb.png">

<img width="960" alt="screenshot_302" src="https://user-images.githubusercontent.com/46939846/154955000-b78b744a-1754-4415-8a17-1ba3403605f0.png">

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Premium

**Comment by scqolbu24** [comment]
pak @ariandii, saat ini pada table layanan mandiri ada field "aktif" yang mana apabila penduduk tersebut aktif maka dapat mengakses atau login di layanan mandiri.

Dan apabila penduduk tersebut pindah/meninggal/dsb, apakah baiknya hanya merubah field tersebut menjadi tidak aktif.

maksudnya tidak menghapus data pada tabel layanan mandiri agar tetap ada history

**Comment by ariandii** [comment]
nampaknya jika melihat gambar di atas, baris penduduk yang pindah, meninggal, hilang atau lainnya menjadi kosong.
NIK dan Nama terlihat kosong, dengan demikian history apa yang diharapkan?

**Comment by scqolbu24** [comment]
Sesuai dengan judul pada issue ini bahwa "Jumlah Data di Layanan Mandiri tidak sesuai seharusnya",
yaitu jumlah layanan mandiri melebihi jumlah pada pada data penduduk,padahal penduduk tersebut sudah pindah/meninggal/dsb.

Pertanyaannya adalah, apakah penduduk yang pindah/meninggal/dsb pada layanan mandiri :
1. dihapus ?
2. tetap ada dan menampilkan nik serta  nama penduduk dengan status sudah tidak aktif sehingga tidak dapat login, kemudian diberi keterangan sesuai dengan perubahannya pindah/meninggal/dsb (sebagai histori) ?

**Comment by eddieridwan** [comment]
@scqolbu24 dihapus saja. Karena penduduk tersebut sudah berubah status dasarnya: sudah mati, pindah, hilang. Sepertinya tidak ada manfaat disimpan riwayatnya sebagai pengguna Layanan Mandiri. Tetapi perlu dipastikan tidak ada dampak dari penghapusan itu.

Yaitu, yg perlu diterapkan:
1. Saat mengubah status dasar penduduk menjadi mati/hilang/pindah, hapus entrinya di pendaftar layanan mandiri
2. Migrasi untuk menghapus pendaftar layanan mandiri yg status dasarnya bukan 'hidup'

Untuk testing meyakinkan tidak ada masalah dengan penghapusan ini, lakukan:
1. bagi seorang pendaftar layanan mandiri, pada layanan mandiri:
    1. buat permohonan surat
    2. kirim pesan
2. ganti status dasar pendaftar tersebut menjadi 'mati'
3. pastikan:
    1. warga tersebut sudah tidak terdaftar lagi sebagai pengguna layanan mandiri
    2. warga tersebut tidak bisa login lagi ke layanan mandiri
    2. permohonan surat dari warga tersebut masih terlihat di admin layanan mandiri
    3. pesan dari warga tersebut masih terlihat di admin layanan mandiri

Seharusnya tidak bermasalah, karena permohonan surat dan pesan menggunakan id penduduk dan bukan id pengguna layanan mandiri.

**Comment by scqolbu24** [comment]
Baik pak @eddieridwan

**Comment by scqolbu24** [comment]
sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/780
