### ISSUE TITLE
[PREMIUM-22.02 BETA02] Koreksi Fitur Pengaduan

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#4933]
### Jelaskan error yg dialami

Fitur belum belum stabil setelah memasuk kode captcha muncul pesan Kode captcha anda salah. Silakan ulangi lag, setelah klik tombol tutup...
![image](https://user-images.githubusercontent.com/64481641/155104701-bf3ad882-474b-4a11-893a-0c3e40f44af6.png)

Buka Kembali atau Klik Pengaduan lagi, form data sebelumnya masih terisi data sebelumnya yang dibuat gagal atau salah kode captcha....
![image](https://user-images.githubusercontent.com/64481641/155104987-0303c066-7582-4296-8859-5d5e3c3adf96.png)

![image](https://user-images.githubusercontent.com/64481641/155105047-f06285c9-2e1f-4a41-9366-b539ba5466d8.png)

### Cara untuk mereplikasi errornya

Buka Fitur Pengaduan--> isi data pengaduan --->masukkan kode captcha klik kirim, bila muncul pesan kode captcha salah, minta dimasukkan---> Klik Tombol [TUTUP]

Buka Kembali Fitur Pengaduan Untuk Pengaduan lainnya/baru lagi ---. Semua Is Form Data masih ada 

### Hasil yg diharapkan

Setelah Klik Tombol [Tutup] apakah karena salah kode captcha -> buka kembali harusnya form kosong atau form isian baru kembali tidak memanggil nilai sebelumnya.

### Tangkapan layar dan log error

Isi Data Pengatuan Kirim-->Kode Captcha Salah ---> Tutup
![image](https://user-images.githubusercontent.com/64481641/155106082-d27afda9-2d83-4c38-b2ad-b8fe182371e3.png)

Klik Pengaduan Kembali
![image](https://user-images.githubusercontent.com/64481641/155106165-40ce7eac-8dfd-454a-bc7b-ee1bb784ae4a.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Premium (v21.03-beta03)

### Tema Yang Digunakan

default

**Comment by Zoel-WB** [comment]
INFORMASI TAMBAHAN--->PASSWORD LOGIN --->TAMPIL DI KOLOM E-MAIL PENGADUAN TAMPA SENSOR, atau mungkin dapat diabaikan karena pengaruh browser dengan terpasangnya "autocomplete"

![image](https://user-images.githubusercontent.com/64481641/155114587-39cffacc-c186-415e-b7d3-8f537ccf8d88.png)

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/tema-natra/pull/91
