### ISSUE TITLE
[PREMIUM-BETA03] Tidak Dapat Menghapus Nama Program Bantuan

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#4936]
### Jelaskan error yg dialami

Nama Program Bantuan Tidak Dapat Dihapus lewat system setelah semua data dikosongkan, Pada Kolom Jumlah Peserta Bantuan tetap ada satu data jumlah peserta yang tertera dalam kolom akan tetapi setelah dibuka datanya tidak ada atau kosong..

### Cara untuk mereplikasi errornya

1. Pilih Menu Bantuan
2. Pilih Salah Satu Nama Bantuan
3. Hapus Semua Data Peserta Program Bantuan
4. Hapus Nama Program Bantuan

### Hasil yg diharapkan

Nama Program Bantuan yang telah dihapus semua data perserta bantuan dapat dihapus melalui system dari menu bantuan

### Tangkapan layar dan log error

1. Nama Program Bantuan Yang Telah di Hapus Semua Perserta Bantuan

![image](https://user-images.githubusercontent.com/64481641/155379304-ccde3cda-3890-45c4-a0a6-f16a2f322682.png)

2. Data Telah dikosongkan

![image](https://user-images.githubusercontent.com/64481641/155379502-17722e73-24c0-4fd1-acf9-bff8098a120f.png)

![image](https://user-images.githubusercontent.com/64481641/155380140-beb7a2d8-341e-4137-af4e-0850db37a446.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Premium (v22.02-Beta03)

### Tema Yang Digunakan

default

### Informasi tambahan

Noted

**Comment by Zoel-WB** [comment]
Informasi Tambahan, Satu Data Yang masih terhitung dalam Jumlah Peserta-->Ternyata Data Penduduk yang telah berubah status dasar...
![image](https://user-images.githubusercontent.com/64481641/155401094-627f2593-b86d-4453-ad74-58656d103d21.png)

**Comment by Zoel-WB** [comment]
Maksudnya terhitung dalam jumlah perserta program bantuan sedangkan data dalam list program tidak tampil lagi

**Comment by andifahruddinakas** [comment]
Sudah digabung melalui PR https://github.com/OpenSID/premium/pull/787
