### ISSUE TITLE
Permintaan fitur: Penambahan Kolom Keterangan Pada List Daftar Bantuan

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#4937]
### Apa kekurangan yg ingin diatasi?

Permintaan Penambahan Kolom Keterangan Yang Ditampilkan Di List Daftar Bantuan untuk dapat menandakan dan memisahkan serta pengelompokan peserta bantuan sesuai dengan kategori tempat lokasi penyaluran/pencairan bantuan, misalnya seperti bantuan BPNT, BST biasanya tempat penyaluran berbeda-beda, ada BPNT/BST yang disalurkan oleh PT. Pos Indonesia dan ada yang disalurkan oleh BRI atau BSI.

Diperlukan pengelompokkan ini untuk dapat memudahkan mengontrol kelompok-kelompok peserta program bantuan yang waktu dan tempat penyalurannya berbeda.

### Jelaskan solusi yg diinginkan

Cukup Menampilkan Keterangan pada List Program

![image](https://user-images.githubusercontent.com/64481641/155387491-366fab28-d241-4b84-af17-ed5c60773ece.png)

Bisa di tampilkan
![image](https://user-images.githubusercontent.com/64481641/155388183-498fc16d-93dd-4eb1-a6bb-168529fd1683.png)

### Apakah ada alternatif lain

Noted

### Untuk versi OpenSID mana

Premium v22.03

### Informasi tambahan

noted

**Comment by andifahruddinakas** [comment]
Sebaiknya seperti ini, agar tidak terlalu banyak ditampilkan pada daftar tabel. Untuk melihat detail bisa masuk ke detail masing2 bantuan saja.
