### ISSUE TITLE
[PREMIUM-BETA03] Data Penduduk Yg Telah Berubah Status Dasar Masih Terhitung Dalam Data Statistik Program Bantuan Aktif

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#4938]
### Jelaskan error yg dialami

Data Penduduk Yg Telah Berubah Status Dasar Masih Terhitung Dalam Data Statistik Program Bantuan Aktif

### Cara untuk mereplikasi errornya

Buka Statistik Program Bantuan
Cari Data Penduduk Yang Berubah Status Dasar Mati/Pindah/Hilang

### Hasil yg diharapkan

Agar Data Penduduk Yg telah merubah status dasar tidak lagi hitung dalam statistik program bantuan yang masih aktif

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/64481641/155403060-7457cf9b-4262-4ab1-8e85-540ed98abd66.png)

![image](https://user-images.githubusercontent.com/64481641/155403160-38b9b354-b29a-43d9-a921-98d9456960f6.png)

![image](https://user-images.githubusercontent.com/64481641/155403314-85fa7c8c-92bc-479a-b74d-196d4004f170.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

premium (v22.03-Premium)

### Tema Yang Digunakan

default

### Informasi tambahan

Noted

**Comment by yogiperdana** [comment]
Issue ini tumpang tindih dengan issue https://github.com/OpenSID/OpenSID/issues/4936. Yaitu penduduk yang berubah status dasar tetap akan terdaftar pada program bantuan. Hal ini sudah didiskusikan bersama Pak @eddieridwan

**Comment by Zoel-WB** [comment]
Maksudnya terhitung dalam jumlah perserta program bantuan sedangkan data dalam list program tidak tampil lagi, begitu juga yang terjadi pada issue nomor #4936
