### ISSUE TITLE
Permintaan fitur: Pindah Tanggal Lengkap dan Data Lengkap Aktif

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#4940]
### Apa kekurangan yg ingin diatasi?

Saat ini setiap ingin laporan harian atau bulanan, perlu akses menu pengaturan tersebih dahulu untuk sesuaikan tanggal data lengkap.

<img width="960" alt="screenshot_344" src="https://user-images.githubusercontent.com/46939846/155468889-c1b5b057-65ab-4101-8db8-73942f228e45.png">

### Jelaskan solusi yg diinginkan

Tersedia di popup aksi di Menu Laporan Bulanan, atau di Kependudukan.

### Apakah ada alternatif lain

Atau Cara dan tempat lain misal dibuat tanggal default setiap harinya, yang memudahkan pengguna agar tidak terlewat.

### Untuk versi OpenSID mana

22.03-premium

**Comment by andifahruddinakas** [comment]
Pak @ariandii, sy lihat itu ada 2 pengaturan yang hampir sama fungsinya. Kyaknya cukup gunakan 1 saja yakni "Data Lengkap" saja ?

**Comment by ariandii** [comment]
Data lengkap untuk menentukan per tanggal tertentu sesuai keinginan saat lapor. 

Data Lengkap Aktif, untuk menentukan Aktif atau tidak nya Menu Laporan Bulanan, sehingga menghindari kesalahan Lapor jika tanggal belum disesuaikan.

2 Kolom itu bisa di sedian di dalam Menu Laporan Bulanan agar tidak perlu ubah tanggal atau status di halaman berbeda.

**Comment by andifahruddinakas** [comment]
> Data lengkap untuk menentukan per tanggal tertentu sesuai keinginan saat lapor.
> 
> Data Lengkap Aktif, untuk menentukan Aktif atau tidak nya Menu Laporan Bulanan, sehingga menghindari kesalahan Lapor jika tanggal belum disesuaikan.
> 
> 2 Kolom itu bisa di sedian di dalam Menu Laporan Bulanan agar tidak perlu ubah tanggal atau status di halaman berbeda.

ok

**Comment by andifahruddinakas** [comment]
Pak @ariandii, Bisa di listkan modul mana saja pengaturan tersebut ditampilkan?

**Comment by ariandii** [comment]
Hanya di Statistik -> Laporan Bulanan

**Comment by andifahruddinakas** [comment]
> Hanya di Statistik -> Laporan Bulanan

Di Buku Administrasi Penduduk tidak perlu ?

**Comment by ariandii** [comment]
Saya rasa tidak perlu, karena tanggal itu hanya sebagai penentu kapan data laporan bulanan dilaporkan per tanggal yang diinginkan.

Termasuk Cetak dan Unduhnya.

***
Sebagai info, yang sudah berjalan selama ini, setiap bulan saya selalu ubah ke tanggal akhir,
Masuk bulan januari, langsung saya ganti jadi 31 januari.
Masuk bulan April ini, langsung saya ganti ke 30 April.

Karena rekap Laporan Bulanan saya perhatikan membaca data akhir tanggal lampau,
Namun ketika tanggal itu diganti tanggal akhir dibulan yang sama, maka angka akan update sesuai hari berjalan di bulan itu juga.

Namun misal sekarang saya buat tanggal 1 mei, maka Laporan Bulana kembali tidak sesuai.

**Comment by andifahruddinakas** [comment]
> Saya rasa tidak perlu, karena tanggal itu hanya sebagai penentu kapan data laporan bulanan dilaporkan per tanggal yang diinginkan.
> 
> Termasuk Cetak dan Unduhnya.
> 
> Sebagai info, yang sudah berjalan selama ini, setiap bulan saya selalu ubah ke tanggal akhir, Masuk bulan januari, langsung saya ganti jadi 31 januari. Masuk bulan April ini, langsung saya ganti ke 30 April.
> 
> Karena rekap Laporan Bulanan saya perhatikan membaca data akhir tanggal lampau, Namun ketika tanggal itu diganti tanggal akhir dibulan yang sama, maka angka akan update sesuai hari berjalan di bulan itu juga.
> 
> Namun misal sekarang saya buat tanggal 1 mei, maka Laporan Bulana kembali tidak sesuai.

kayaknya di perlukan di modul lain jg, seperti ini : 
![pengaturan ini](https://user-images.githubusercontent.com/57283157/161692076-f14593eb-dd19-45f6-b257-ee069fed6d1c.png)

Karena akan di arahkan ke link pengaturan.

**Comment by agungsugiarto** [comment]
Sudah di fitur premium melalui pr https://github.com/OpenSID/premium/pull/920
