### ISSUE TITLE
[PREMIUM-BETA04] Input Data Keuangan setelah Di Imput Tekan Tombol Enter Data Tidak Tersimpan

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#4941]
### Jelaskan error yg dialami

Saat input data keuangan manual, setelah selesai tekan enter keluar dari form input, akan tetapi data tidak tersimpan bila bukan di klik pada tombol simpan....

### Cara untuk mereplikasi errornya

1. Buka Data Keuangan-->Pilih Input Data
2. Pilih Salah Satu Item Keuangan yang akan di imput
3. Masukkan/Input data atau nilai
4. Tekan Enter..

### Hasil yg diharapkan

Setelah input data bila menggunakan laptop harusnya hanya cukup menekan tombol ENTER data tersimpan, tidak harus memilih tombol [Simpan] baru data dapat tersimpan

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/64481641/155509253-7dfa1e8a-4b30-45da-b5e4-bcc8f3fa5221.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Premium (v21.03-beta04)

### Tema Yang Digunakan

defaul berputar

### Informasi tambahan

Noted

**Comment by scqolbu24** [comment]
sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/795
