### ISSUE TITLE
[PREMIUM-BETA04] Input atau Edit Data pada Fitur Pembangunan Filter Tahun Selalu Kembali Ke Default Setelah Data Disimpan

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#4942]
### Jelaskan error yg dialami

Input atau Edit Data pada Fitur Pembangunan Filter Tahun Selalu Kembali Default Setelah Data Disimpan, sehingga untuk memilih edit data berikut harus selalu memfilter ulang tahun anggaran

### Cara untuk mereplikasi errornya

1. Buka Menu Pembangungan ---. Pilih Filter Tahun Anggaran
2. Pilih Jenis Kegiatan Pembangunan Yang Akan di Edit
3. Setelah Di Edit Klik Simpan

### Hasil yg diharapkan

Filter Tahun Tetap Pada Filter Yang Sama saat dipilih untuk edit/rumah data sebelum tahun di filter yg berikutnya atau sebelum keluar dari system, filter tahun tetap tidak kembali ke awal

### Tangkapan layar dan log error

1. Pilih Fitur Pembangunan-->Pilih Filter Tahun

![image](https://user-images.githubusercontent.com/64481641/155511621-57ffad8e-76b9-46c9-b134-df3c2252a968.png)

2.  Pilih Data Kegiatan yang akan dirubah, kemudian Pilih [Simpan]

![image](https://user-images.githubusercontent.com/64481641/155511767-946f04eb-7644-489d-b5c7-ab464c228ae9.png)

3. Filter Tahun Kembali ke Default -->>Untuk Memilih Data dalam tahun yang sama berikutnya-->harus melakukan kembali filter tahun....

![image](https://user-images.githubusercontent.com/64481641/155511984-d8536a58-a12d-4d1c-955f-4ba1df5895ef.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Premium v22.03-beta04

### Tema Yang Digunakan

defaul berputar

### Informasi tambahan

Notetd

**Comment by yogiperdana** [comment]
Issue ini termasuk ke dalam kategori permintaan fitur

**Comment by Zoel-WB** [comment]
Oke pak...

Dapatkan Outlook untuk Android<https://aka.ms/AAb9ysg>
________________________________
