### ISSUE TITLE
Permintaan fitur: Sesuaikan Template Format F-1.01 Dengan model Terbaru

### ISSUE THREAD

**Issue by muhtar-coder** [OpenSID/OpenSID#4943]
### Apa kekurangan yg ingin diatasi?

Ada formulir baru yang di keluarkan kemendagri untuk model F 1.01
pada model baru tersebut terdapat dua lembar formulir dalam satu jenis surat

### Jelaskan solusi yg diinginkan

Penyesuaian template formulir F 1.01 dengan yang terbaru
berikut model dari F 1.01 :
[Formulir F 1.01 terbaru.pdf](https://github.com/OpenSID/OpenSID/files/8132153/Formulir.F.1.01.terbaru.pdf)

### Apakah ada alternatif lain

Tidak ada

### Untuk versi OpenSID mana

semua versi

### Informasi tambahan

pada prakteknya,kebutuhan untuk permohonan cetak kartu keluarga baru dengan berkas F 1.01 selalu berhubungan dengan formulir F 1.02   karena pada keterangan persyaratan di model surat F 1.02 yang harus di lampirkan terdapat kebutuhan formulir model  F 1.01

berikut ini formulir F 1.02
[formulir F 1.02 terbaru.pdf](https://github.com/OpenSID/OpenSID/files/8132118/formulir.F.1.02.terbaru.pdf)

**Comment by andifahruddinakas** [comment]
> Formulir F 1.01 terbaru.pdf

Pak @muhtar-coder, untuk lampiran Formulir F 1.01 terbaru.pdf tidak terlalu jelas (buram/kabur). Apakah sudah berlaku secara nasional?

**Comment by yogiperdana** [comment]
Mohon maaf pak @muhtar-coder, untuk [Formulir F 1.01 terbaru.pdf](https://github.com/OpenSID/OpenSID/files/8132153/Formulir.F.1.01.terbaru.pdf) gambarnya tidak jelas. Ada perubahan apa saja dengan versi yang lama pak?

**Comment by balongbesuk** [comment]
duplicate #4225

**Comment by yogiperdana** [comment]
[Permendagri 109 Tahun 2019.pdf](https://github.com/OpenSID/OpenSID/files/9089908/Permendagri.109.Tahun.2019.pdf)

**Comment by andifahruddinakas** [comment]
Ini : https://github.com/OpenSID/OpenSID/files/6589020/FORMULIR.F.1-01.BIODATA.KELUARGA.pdf

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1380
