### ISSUE TITLE
Permintaan fitur: Sesuaikan Format Surat Model F-1.02 Dengan Model Terbaru

### ISSUE THREAD

**Issue by muhtar-coder** [OpenSID/OpenSID#4944]
### Apa kekurangan yg ingin diatasi?

Ada model format surat F 1.02 terbaru yang perlu di sesuaikan di dalam template surat OpenSID.

### Jelaskan solusi yg diinginkan

Sesuaikan Format surat F 1.02 Dengan model terbaru

berikut ini model surat F 1.02 terbaru :
[formulir F 1.02 terbaru.pdf](https://github.com/OpenSID/OpenSID/files/8132175/formulir.F.1.02.terbaru.pdf)

### Apakah ada alternatif lain

Tidak ada

### Untuk versi OpenSID mana

semua versi

### Informasi tambahan

Ketika membuat surat Model F 1.02 sekaligus memanggil format surat model F 1.01

Berikut ini model surat F 1.01 :
[Formulir F 1.01 terbaru.pdf](https://github.com/OpenSID/OpenSID/files/8132184/Formulir.F.1.01.terbaru.pdf)

**Comment by andifahruddinakas** [comment]
Pak @muhtar-coder, ini di lampirkan disurat mana? Apakah pada Permohonan Kartu Keluarga atau Permohonan Perubahan Kartu Keluarga atau semua surat yang lampirannya F.1.01 juga melampirkan F.1.02?

**Comment by muhtar-coder** [comment]
maaf baru buka,,, terkait format surat F-1.02 adalah jenis surat yang di gunakan untuk pencetakan KK,KTP karena peristiwa tertentu seperti peristiwa pindah,kematian,perkawinan,ubah data dan lain-lain yang outputnya kartu keluarga/KTP/AKTA.

Keluarnya surat F-1.02 akan di sertai surat jenis F-1.01 sebagai acuan percetakan/dikeluarkan nya dokumen terbaru yang akan di cetak

**Comment by yogiperdana** [comment]
[Permendagri 109 Tahun 2019.pdf](https://github.com/OpenSID/OpenSID/files/9089898/Permendagri.109.Tahun.2019.pdf)

**Comment by andifahruddinakas** [comment]
Ini : https://disdukcapil.inhilkab.go.id/wp-content/uploads/2021/06/FORMULER_F1.02.pdf

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1382
