### ISSUE TITLE
Permintaan fitur: Sesuaikan Format Surat Model F 2.01 ( Pelaporan Kematian) Dengan Model Terbaru

### ISSUE THREAD

**Issue by muhtar-coder** [OpenSID/OpenSID#4945]
### Apa kekurangan yg ingin diatasi?

Ada Format Surat Model F 2.01 Dengan Model Terbaru

### Jelaskan solusi yg diinginkan

Sesuaikan Model Surat F 2.01 Dengan yang Terbaru
Berikut ini Model Surat F 2.01 Terbaru :
[Formulir F 2.01 terbaru.pdf](https://github.com/OpenSID/OpenSID/files/8132203/Formulir.F.2.01.terbaru.pdf)

### Apakah ada alternatif lain

Tidak ada

### Untuk versi OpenSID mana

semua versi

### Informasi tambahan

Tidak ada

**Comment by andifahruddinakas** [comment]
Duplicate issue https://github.com/OpenSID/OpenSID/issues/5259
