### ISSUE TITLE
[PREMIUM] Bug/error: Duplikat data pada penduduk dengan status pindah belum tercover dalam fitur perbaiki

### ISSUE THREAD

**Issue by mizwaruddin** [OpenSID/OpenSID#4946]
### Jelaskan error yg dialami

Saat melakukan migrasi dari 22.02-beta03 ke beta04 muncul keterangan gagal migrasi dengan keterangan error: 2022-02-24 21:27:03  Data kolom email pada tabel tweb_penduduk ada yang duplikat dan perlu diperbaiki sebelum migrasi dilanjutkan.

Selanjutnya saya menggunakan fitur perbaiki, muncul keterangan database diperbaiki, email diubah menjadi array. Namun saat saya migrasi ulang tetap gagal dengan keterangan yang sama.

setelah saya telusuri, ternya duplikat email ada yang melekat pada penduduk dengan status pindah.

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

Duplikat pada penduduk dengan status pindah, mati, hilang, dsb dapat teratasi dalam fitur perbaiki.

### Tangkapan layar dan log error

![bug_migrasi](https://user-images.githubusercontent.com/39736008/155560326-272b6308-4b75-4711-9b0a-5bb7c6c3d0fb.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

OpenSID 22.02-premium-beta04

**Comment by eddieridwan** [comment]
@andifahruddinakas @agungsugiarto : apakah issue ini sdh ada yg mengambil? Kalau belum biar saya kerjakan. Harap segera beritahu.

**Comment by agungsugiarto** [comment]
belum ada pak

**Comment by eddieridwan** [comment]
Ok, saya sudah ambil.

**Comment by eddieridwan** [comment]
Masalahnya karena adanya email user yg ganda, yg belum terdeteksi. Solusinya dengan menambah deteksi dan perbaiki email user ganda.

**Comment by andifahruddinakas** [comment]
Sudah digabung melalui PR https://github.com/OpenSID/premium/pull/798
