### ISSUE TITLE
[PREMIUM] Bug/error: Tidak bisa mengunggah logo dan foto kantor desa di menu identitas desa

### ISSUE THREAD

**Issue by mizwaruddin** [OpenSID/OpenSID#4947]
### Jelaskan error yg dialami

Tidak bisa mengunggah logo dan foto kantor desa di menu identitas desa

### Cara untuk mereplikasi errornya

1. Info desa-> Identitas desa
2. Ubah data desa
3. Tidak bisa mengunggah logo dan foto kantor desa

### Hasil yg diharapkan

Fungsi unggah lambag dan kantor desa berjalan normal

### Tangkapan layar dan log error

![bug_identitas_desa](https://user-images.githubusercontent.com/39736008/155567834-b825cb53-aa88-4eae-bcd7-45bda45abea0.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

OpenSID 22.02-premium-beta04

### Informasi tambahan

Setelah update ke beta04 logo dan foto kantor desa kembali ke default.

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki https://github.com/OpenSID/premium/commit/f2be1be1732e20ba32bbe2f7dd9a5f9ebbc841ac
