### ISSUE TITLE
[PREMIUM] Bug/error: Tampilan detail pengaduan di admin tidak bekerja semestinya

### ISSUE THREAD

**Issue by mizwaruddin** [OpenSID/OpenSID#4948]
### Jelaskan error yg dialami

Tampilan pengaduan di dashboar admin harusnya di disable. Berikutnya gambar juga tampil terlalu besar.

### Cara untuk mereplikasi errornya

1. Pengaduan-> tampilkan detail
2. Field text input tidak di disable
3. Gambar tampil besar

### Hasil yg diharapkan

1. Field text input di disable
2. Gambar tampil normal

### Tangkapan layar dan log error

![bug_pengaduan](https://user-images.githubusercontent.com/39736008/155573022-8be258fb-a75c-42a5-bde1-191b5fb447bb.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

OpenSID 22.02-premium-beta04

**Comment by apidong** [comment]
sudah diperbaiki melalui https://github.com/OpenSID/premium/pull/792
