### ISSUE TITLE
[PREMIUM] Bug/error: Salah penulisan list select2 "Yang menerangkan kematian" pada ubah status dasar mati

### ISSUE THREAD

**Issue by mizwaruddin** [OpenSID/OpenSID#4949]
### Jelaskan error yg dialami

Salah penulisan list select2 "Yang menerangkan kematian" pada ubah status dasar mati

### Cara untuk mereplikasi errornya

1. Kependudukan-> penduduk
2. Ubah status dasar penduduk->mati
3. Pada isian "Yang menerangkan kematian" bagian list select2 tampil "Pilih penyebab kematian"

### Hasil yg diharapkan

Pada isian "Yang menerangkan kematian" bagian list select2 seharusnya tampil "Yang menerangkan kematian", bukan "Pilih penyebab kematian"

### Tangkapan layar dan log error

![bug_ststusmati](https://user-images.githubusercontent.com/39736008/155574012-9245c6e1-d082-4fcd-b9d0-00ce67d5fc33.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

OpenSID 22.02-premium-beta04

**Comment by apidong** [comment]
sudah diperbaiki melalui pr https://github.com/OpenSID/premium/pull/793
