### ISSUE TITLE
[PREMIUM] Permintaan fitur: Rapikan tampilan tombol impor pada menu rumah tangga di tampilan handphone

### ISSUE THREAD

**Issue by mizwaruddin** [OpenSID/OpenSID#4950]
### Apa kekurangan yg ingin diatasi?

tampilan tombol impor pada menu rumah tangga di tampilan handphone tidak selaras dengan tombol-tombol lainnya.

![fitur_impor_rumahtangga](https://user-images.githubusercontent.com/39736008/155574885-86fad92f-9350-4adc-aeff-833de89d53f9.png)

### Jelaskan solusi yg diinginkan

tampilan tombol impor pada menu rumah tangga di tampilan handphone selaras dengan tombol-tombol lainnya

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

OpenSID 22.02-premium-beta04

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melalui pr https://github.com/OpenSID/premium/pull/930
