### ISSUE TITLE
[PREMIUM] Bug/error: Pada cetak laporan lembaga tidak ada spasi antara sebutan kecamatan dan nama kecamatan

### ISSUE THREAD

**Issue by mizwaruddin** [OpenSID/OpenSID#4951]
### Jelaskan error yg dialami

Pada cetak laporan lembaga tidak ada spasi antara sebutan kecamatan dan nama kecamatan

### Cara untuk mereplikasi errornya

1. Info desa->lembaga desa-> cetak
2. Pada halaman cetak laporan, kop laporan bagian kecamatan tidak ada spasi antara sebutan kecamatan dan nama kecamatan

### Hasil yg diharapkan

Tambahkan spasi antara sebutan kecamatan dan nama kecamatan

### Tangkapan layar dan log error

![bug_cetak_lembaga](https://user-images.githubusercontent.com/39736008/155576127-6d214c79-e73c-46e0-b3ea-b753aee0e40a.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

OpenSID 22.02-premium-beta04

**Comment by yogiperdana** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/794
