### ISSUE TITLE
[PREMIUM] Bug/error: Tampilan tambah anggota kelompok tidak rapi

### ISSUE THREAD

**Issue by mizwaruddin** [OpenSID/OpenSID#4952]
### Jelaskan error yg dialami

Tampilan tambah anggota kelompok tidak rapi

### Cara untuk mereplikasi errornya

1. Kependudukan-> kelompok
2. Rincian kelompok
3. Tambah Satu Anggota Kelompok / Tambah Beberapa Anggota Kelompok
4. Tampilan form tambah data anggota kelompok tidak rapi

### Hasil yg diharapkan

Tampilan form tambah data anggota kelompok rapi

### Tangkapan layar dan log error

![bug_tambah_kelompok](https://user-images.githubusercontent.com/39736008/155626545-a94760cd-1577-44d1-a9fe-702bf6704123.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

OpenSID 22.02-premium-beta04

**Comment by yogiperdana** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/800
