### ISSUE TITLE
[PREMIUM] Bug/error: Nama anggota kelompok terdata masih tampil di list penambahan anggota

### ISSUE THREAD

**Issue by mizwaruddin** [OpenSID/OpenSID#4953]
### Jelaskan error yg dialami

Nama anggota kelompok terdata masih tampil di list penambahan anggota

### Cara untuk mereplikasi errornya

1. Kependudukan-> kelompok
2. Rincian kelompok-> Tambah anggota-> Tambah anggota satu orang/ Tambah anggota beberapa orang
3. Penduduk yang sudah terdata sebagai anggota kelompok masih tampil dalam list 
4. Pilih anggota kelompok yang sama tersebut-> simpan
5. Data gagal disimpan

### Hasil yg diharapkan

Penduduk terdata dalam anggota kelompok tidak tampil dalam list

### Tangkapan layar dan log error

![bug_tambah_kelompok1](https://user-images.githubusercontent.com/39736008/155639566-14ade639-1838-4eb7-9802-e667fe6ab891.png)
![bug_tambah_kelompok2](https://user-images.githubusercontent.com/39736008/155639586-d6ab678c-9402-4c18-851d-7ac29bbb1f2f.png)
![bug_tambah_kelompok3](https://user-images.githubusercontent.com/39736008/155639603-81f9d12d-4c74-4d64-a828-c95e438772f3.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

OpenSID 22.02-premium-beta04

**Comment by andifahruddinakas** [comment]
Mas @scqolbu24, karena perubahan sebelumnya mengizinkan untuk mengganti nama anggota, tp pengecekan hanya dilakukan pada saat insert sj. Dmna perlu ada pengecualian untuk kasus update jika tdk ada perubahan pd id anggota tsb. Dan mungkin juga perlu di cek di bagian lemabaga krn kelompok dan lembaga menggunakan tabel yg sama, maka perlu adanya where tipe.

https://github.com/OpenSID/premium/pull/653

**Comment by andifahruddinakas** [comment]
Pak @mizwaruddin, list penduduk memang tetap ditampilkan tp jika disimpan akan ada notifikasi jika penduduk tsb sudah diterdatar.

**Comment by andifahruddinakas** [comment]
Perbaikian :
1. Tampilkan daftar semua daftar penduduk hidup kecuali yang sudah terdafatar tp termasuk yg akan di ubah datanya.

**Comment by scqolbu24** [comment]
sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/797
