### ISSUE TITLE
[PREMIUM] Bug/error: Nama penduduk yang mengandung tanda baca koma (,) tidak berfungsi

### ISSUE THREAD

**Issue by mizwaruddin** [OpenSID/OpenSID#4954]
### Jelaskan error yg dialami

Nama penduduk yang mengandung tanda baca koma (,) tidak berfungsi

### Cara untuk mereplikasi errornya

1. Kependudukan-> penduduk
2. Ketikkan nama penduduk yang mengandung tanda baca koma (,) di kotak pencarian
3. Data penduduk tersebut tidak tampil

### Hasil yg diharapkan

Nama penduduk yang mengandung tanda baca koma (,) tampil dalam pencarian

### Tangkapan layar dan log error

![bug_cari_anggota1](https://user-images.githubusercontent.com/39736008/155640469-08aec1aa-22b6-4e86-b29f-1ce35efdc431.png)
![bug_cari_anggota2](https://user-images.githubusercontent.com/39736008/155640479-c1497a3d-3fd5-4d5d-99d7-a4de3efdf5a3.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

OpenSID 22.02-premium-beta04

**Comment by eddieridwan** [comment]
Apa contoh nama di KTP atau Kartu Keluarga yg ada tanda koma (,)?  
Beri tangkapan layarnya.

**Comment by mizwaruddin** [comment]
Ada, Bang. Contoh Asminah, HJ.

**Comment by scqolbu24** [comment]
saya coba pakai pencarian menggunakan tanda baca (,) dapat menampilkan : 

<img width="100%" alt="penduduk-spasi" src="https://user-images.githubusercontent.com/68048807/155655112-adc0b713-5b88-491e-9cd5-663c64e4585b.PNG">

**Comment by scqolbu24** [comment]
Sudah dicek @yogiperdana dan @andifahruddinakas berjalan dengan normal, issue ini di close.

apabila dikemudian hari masih ditemukan bug, issue ini dapat dibuka kembali.
