### ISSUE TITLE
Bug/error: 

### ISSUE THREAD

**Issue by makhbub** [OpenSID/OpenSID#4955]
### Jelaskan error yg dialami

Modul pembangunan, data pembangunan dengan status dinonaktifkan masih muncul di website

### Cara untuk mereplikasi errornya

1. pergi ke modul pembangunan, kemudian nonaktifkan salah satu kegiatan
2. kemudian pergi ke bagian website, cek apakan kegiatan yang dinonaktifkan masih tampil atau tidak

### Hasil yg diharapkan

maksud  penonaktifan kegiatan adalah supaya kegiatan tersebut tidak ditampilkan dengan berbagai alasan seperti : 
1. data kegiatan tersebut belum valid
2. data kegiatan tersebut memang tidak ingin ditampilkan

### Tangkapan layar dan log error

![bug pembangunan](https://user-images.githubusercontent.com/38773660/155670301-be82ee32-4adf-441e-9ef0-ce9c825196cd.jpg)
![bug pembangunan 2](https://user-images.githubusercontent.com/38773660/155670306-20e440fc-8e5b-4839-9739-a961a9096a30.jpg)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v 22.02-premium

### Tema Yang Digunakan

-

**Comment by scqolbu24** [comment]
sudah digabungkan melalui PR https://github.com/OpenSID/premium/pull/799
