### ISSUE TITLE
Permintaan fitur: Penambahan Tombol View Dokumen Pada Fitur Buku Agenda Surat Keluar

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#4956]
### Apa kekurangan yg ingin diatasi?

Penambahan Fitur View Pada Dokumen Fitur Buku Agenda Surat Keluar

![image](https://user-images.githubusercontent.com/64481641/155673077-a93800be-1e17-4fe1-97f5-464daa934927.png)

### Jelaskan solusi yg diinginkan

Sama dengan tampilan Pada Fitur Buku Agenda Surat Masuk

![image](https://user-images.githubusercontent.com/64481641/155673019-36cbedd6-accd-4cbd-873e-6a09c993dc29.png)

### Apakah ada alternatif lain

Supaya Dapat menampilkan dan melihat dokumen dalam Buku Agenda Surat Keluar sebelum mengunduh ataupun mencetak untuk menampilkan pemeriksaan terlebih dahulu..

### Untuk versi OpenSID mana

OpenSID V22.03-Premium

### Informasi tambahan

Noted

**Comment by agungsugiarto** [comment]
Sudah di fitur premium melalui pr https://github.com/OpenSID/premium/pull/948
