### ISSUE TITLE
Bug/error: Jumlah bukan penerima pada laporan penerima bantuan keluarga tidak sama dengan jumlah pada kartu keluarga

### ISSUE THREAD

**Issue by makhbub** [OpenSID/OpenSID#4957]
### Jelaskan error yg dialami

pada menu statistik > Bantuan Keluarga> Bantuan Aktif
pada tabel statistik jumlah keluarga yang tidak menerima bantuan aktif sudah benar, tapi saat di klik yang muncul jumlah keluarga yang tidak menerima bantuan (Baik aktif maupun tidak)

### Cara untuk mereplikasi errornya

1. menu statistik >bantuan keluarga, kemudian pilih bantuan aktif
2. perhatikan jumlah keluarga yang tidak menerima bantuan
3. kemudian angkanya diklik, untuk melihat rinciannya
4. kemudian perhatikan jumlahnya , apakah sama dengan jumlah yang ada di tabel statistik?

### Hasil yg diharapkan

rincian jumlah keluarga yang tidak menerima bantuan aktif sesuai dengan tabel statistik

### Tangkapan layar dan log error

tabel bantuan aktif
![bug bantuan 4](https://user-images.githubusercontent.com/38773660/155678956-aaf3f7ab-b6e3-4574-9d5b-1b00fc96364f.jpg)

tabel seluruh bantuan keluarga
![bug bantuan 2](https://user-images.githubusercontent.com/38773660/155678999-617b611b-176c-4cad-afe1-8dca31def920.jpg)

rincian keluarga tidak menerima bantuan aktif
![bug bantuan 3](https://user-images.githubusercontent.com/38773660/155679019-5ab73a9d-49fc-41f8-bec8-d5b03cb20de5.jpg)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v 22.02-premium

### Tema Yang Digunakan

silir

**Comment by apidong** [comment]
@makhbub jika ada kasus kepala keluarga atau KK tersebut tidak aktif (pecah keluarga karena Kepala keluarga meninggal).
apakah tetap di hitung?

**Comment by makhbub** [comment]
Untuk hal tersebut sebaiknya dibahas lebih dalam di issue tersendiri, 
tpi kalau pendapat saya, selama masih ada di bantuan aktif, sebaiknya tetap dicatat. karena dalam beberapa kasus bantuan, apabila nama yg tercantum meninggal bantuan tetap bisa menerima bantuan selama ada ahli warisnya

Pokok issue yg saya angkat disini, di tabel statistik bantuan aktif, angka keluarga yg tidak menerima bantuan aktif sudah benar, 
tapi saat angkanya "diklik", yang muncul adalah data keluarga yg tidak menerima seluruh bantuan (baik yg aktif maupun tidak aktif)

**Comment by scqolbu24** [comment]
sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/804
