### ISSUE TITLE
[PREMIUM-BETA04] Dapat Menyimpan Data Penduduk Dengan Tanggal Penerbitan KTP Dimasa Akan Datang 

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#4959]
### Jelaskan error yg dialami

Dapat Menyimpan Dapat Penduduk Dengan Tanggal Penerbitan KTP Dimasa Akan Datang

### Cara untuk mereplikasi errornya

1. Buka Rubah/Input Data Penduduk
2. Gantikan/Input Tanggal Penerbitan KTP ke Tanggal Depan Nya Misalnya tanggal 20-06-2023
3. Klik Simpan

### Hasil yg diharapkan

Agak tidak dapat merekam/menyimpan data dengan tanggal penerbitan KTP diatas tanggal input, maksimal hanya dapat menyimpan data untuk inputan Data Penerbitan KTP adalah batas tanggal input data ke system.

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/64481641/155683021-4644b266-54f7-4fd3-80e1-2026df2907a8.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

 Premium (v22.03-premium)

### Tema Yang Digunakan

Default

### Informasi tambahan

Noted

**Comment by eddieridwan** [comment]
@Zoel-WB ini bukan bug. Belum pernah ada yg meminta data penerbitan KTP di masa akan datang. Jika ingin diterapkan, harap beri penjelasan mengapa diperlukan, apa dasarnya. Beri contoh kasusnya. Dan bagaimana menghindari diisi tanggal sembarang di masa datang.

**Comment by Zoel-WB** [comment]
Maksudnya supaya tidak dapat mengimput data Tanggal Penerbitan KTP melebih atau diatas Tanggal Input Data pada system, tanggal yg dapat di input pada kolom Tanggal Penerbitan KTP maksimal tanggal input data ke system....

**Comment by eddieridwan** [comment]
Oohh... ok salah baca.

**Comment by scqolbu24** [comment]
sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/802

**Comment by andifahruddinakas** [comment]
@scqolbu24, @yogiperdana ada masalah saat melakukan mau melakukan update.
