### ISSUE TITLE
[PREMIUM-BETA04] Kolom Input Pilihan Status Penduduk Tidak Aktif

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#4960]
### Jelaskan error yg dialami

[PREMIUM-BETA04] Kolom Input Pilihan Status Penduduk Tidak Aktif

### Cara untuk mereplikasi errornya

Buka Data Penduduk --> Rubah Status Penduduk

### Hasil yg diharapkan

Agar Pilihan Status Penduduk dapat Dipilih atau Diganti untuk meng-antipasi salah pilihan dalam input data 

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/64481641/155683802-89c42fba-2e7f-4e49-aef6-a7494644b623.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Premium (v22.03-premium)

### Tema Yang Digunakan

Default

### Informasi tambahan
Ketiga Issue ini bila aliran datanya dalam satu fitur form input data penduduk dapat digabungkan menjadi satu issue...

**Comment by eddieridwan** [comment]
@Zoel-WB , perhatikan kalau penduduk adalah anggota keluarga, status penduduk HARUS tetap, dan tidak boleh diubah. Kalau kasus yg anda laporkan seperti itu, silakan ditutup saja. 

Kalau status penduduk ingin diubah, pecah keluarga dulu.

**Comment by Zoel-WB** [comment]
Oke pak,,,
