### ISSUE TITLE
Permintaan fitur: Penambahan Fitur Bukan Peserta Program Bantuan Pada Filter Keluarga Program Bantuan

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#4961]
### Apa kekurangan yg ingin diatasi?

1. Penambahan Fitur Pada Fitur Keluarga -> Pilih Aksi Lainnya ->Pencarian Program Bantuan
2. Permintaan Penambahan Fitur Filter Data Keluarga Bukan Peserta Dari Program Bantuan 

### Jelaskan solusi yg diinginkan

![image](https://user-images.githubusercontent.com/64481641/155706495-e5c15072-2db4-4c6c-95ea-b4eba43443c3.png)

### Apakah ada alternatif lain

Mempermudah mencari/Menyaring/Memfilter, memilih, unduh dan cetak data keluarga yg belum masuk sebagai penerima program bantuan

### Untuk versi OpenSID mana

OpenSID (v22.03-premium)

### Informasi tambahan

Noted

**Comment by makhbub** [comment]
Mungkin perlu diperjelas " bukan penerima bantuan yg masih aktiv"
Karena diaplikasi mungkin saja ada bantuan yg sudah tdk aktif, tapi sayang untuk dihapus
