### ISSUE TITLE
Permintaan fitur: Penambahan Filter Data pada Pilih Aksi Lainnya Penduduk Pada Pencarian Program Bantuan -> Pendudukan Bukan Peserta Program Bantuan

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#4962]
### Apa kekurangan yg ingin diatasi?

1. Penambahan Filter Data Penduduk Pada Fitur Pilih Aksi Lainnya ->Pencarian Program Bantuan
2. Permintaan Satu Lagi Fitur Filter -> Bukan Peserta Program Bantuan 

### Jelaskan solusi yg diinginkan

Penambahan Dimaksud adalah seperti screensote berikut :
![image](https://user-images.githubusercontent.com/64481641/155708174-3494eb92-3822-4e15-bd91-dc4b4f282750.png)

![image](https://user-images.githubusercontent.com/64481641/155708321-19039ad2-9558-40ee-8318-49546f3234b2.png)

### Apakah ada alternatif lain

Untuk Mempermudah menyaring data penduduk yang tidak atau belum termasuk/terdaftar sebagai penerima program bantuan

### Untuk versi OpenSID mana

OpenSID (v22.03-premium)

### Informasi tambahan

Noted

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1194
