### ISSUE TITLE
[PREMIUM-BETA04] Peta Wilayah Desa Pilihan Warna Peta Tidak Tersimpan

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#4963]
### Jelaskan error yg dialami

Saat Membuat Peta Wilayah Desa Pilihan Warna Peta Tidak Tersimpan

### Cara untuk mereplikasi errornya

1. Pilih Info Desa --> Indentitas Desa-> Pilih Koordinat Lokasi Kantor Desa
2. Pilih Peta Wilayah Desa-->Buat Peta Desa atau Inpor Peta dari KML-> Pilih Warna Yang Inginkan
3. Klik Simpan
4. Pergi Ke Fitur Pemetaan atau Ke website -->Tampilkan Peta

### Hasil yg diharapkan

Pilihan Warna Peta Wilayah Desa dapat Ditentukan dan berfungsi 

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/64481641/155728135-f1abf54e-491d-4652-8585-71bc32145f33.png)

Tampilan di Fitur Pemetaan->Peta

![image](https://user-images.githubusercontent.com/64481641/155728352-ab6a901c-f665-44a1-9c53-66cd1bc7295f.png)

Tampilan dari Premium V22.2 Beta04 yang dibagikan tanggal 24 Februari
![image](https://user-images.githubusercontent.com/64481641/155731513-bc2be226-4a96-4868-bbdb-e01991155134.png)

Tampilan Peta pada Website

![image](https://user-images.githubusercontent.com/64481641/155728509-9307bcaf-fa6a-42a7-9f6f-2f78e53106f5.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Premium (v22.02-Beta04)

### Tema Yang Digunakan

default

### Informasi tambahan
Peta yang dibuat hasil Inpor dari peta KML

**Comment by andifahruddinakas** [comment]
Sudah di perbaiki melalui commit https://github.com/OpenSID/premium/commit/0683a1fc3fe6c3822a52552b017863eb0ec4390e
