### ISSUE TITLE
[PREMIUM] Permintaan fitur: Perbaiki gagal migrasi akibat tabel tidak lengkap

### ISSUE THREAD

**Issue by mizwaruddin** [OpenSID/OpenSID#4964]
### Apa kekurangan yg ingin diatasi?

Dalam fitur periksa, terdeteksi masalah gagal migrasi akibat ada tabel yang kurang. namun, masalah tersebut belum bisa diperbaiki melalui fitur periksa.

### Jelaskan solusi yg diinginkan

Masalah gagal migrasi akibat ada tabel yang tidak lengkap dapat diperbaiki melalui fitur periksa

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

OpenSID 22.02-premium-beta04

**Comment by eddieridwan** [comment]
Bung @mizwaruddin menyediakan database dari Pasirlungu di mana masalah terkait issue ini ditemukan. 

Ternyata masalah untuk database dari desa Pasirlangu bukan karena tabel ref_penduduk_hamil terhapus, tetapi disebabkan berbagai migrasi gagal karena ada NIK ganda dan No KK yg melebihi 16 karakter. 

Solusinya menyediakan periksa/perbaiki untuk kedua masalah database tersebut.
