### ISSUE TITLE
Bug/error: Favicon tidak berubah setelah perbaharui logo desa

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#4965]
### Jelaskan error yg dialami

Favicon tidak berubah setelah ubah data logo desa

### Cara untuk mereplikasi errornya

1. Buka indentitas desa
2. Buka ubah data desa
3. Ubah logo desa
4. Simpan

### Hasil yg diharapkan

Favicon berubah sesuai dengan logo yang diperbaharui

### Tangkapan layar dan log error

.

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.02

### Tema Yang Digunakan

bawaan

### Informasi tambahan

.

**Comment by apidong** [comment]
ini karena masalah chace di browser mas @andifahruddinakas 
coba lakukan setelah simpan.
buka google chrome dalam mode _**Incognito (Jendela samaran baru).**_
logo akan terupdate sesuai gambar yang barusan diubah.

**Comment by apidong** [comment]
sudah diperbaiki melalui https://github.com/OpenSID/premium/pull/806
