### ISSUE TITLE
[PREMIUM-BETA04] Filter Data Buku Inventaris dan Kekayaan Desa Tidak Berfungsi Normal

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#4966]
### Jelaskan error yg dialami

Filter Data Menurut Tahun Perolehan Pada Buku Inventaris dan Kekayaan Desa Tidak Berfungsi seperti semestinya, misalnya memilih menampilkan data semua tahun->tampilannya data malah tidak tampil atau kosong, memilih tampilan data tahun 2022 malah menampilkan seluruh data yg seharusnya tahun 2022 belum ada data yg tercatat dalam Buku Inventaris dan Kekayaan Desa. 

### Cara untuk mereplikasi errornya

1. Buka Fitur Buku Administrasi Desa
2. Pilih Fitur Buku Administrasi Umum
3. Pilih Menu Buku Inventaris dan Kekayaan Desa
4. Coba Tester Filter Data Menurut Tahun yang Di Inginkan

### Hasil yg diharapkan

Agar Dapat Berfungsi Normal dan Dapat Memilih Filter Data Tahun Menurut yang di Inginkan

### Tangkapan layar dan log error

1. Pilih Filter Data Semua Tahun --> Tampilan Datanya Kosong

![image](https://user-images.githubusercontent.com/64481641/155836493-ca7f41cf-972e-4944-956a-e0064b28e2b8.png)

2. Pilih Filter Data Tahun 2022 --> Tampilan Datanya Semua Tahun
![image](https://user-images.githubusercontent.com/64481641/155836592-3f13b72d-33ce-478b-8af3-fdd827a2c495.png)

3. Pilih Filter Data Tahun 2020 --> Tampilan Datanya Semua Tahun

![image](https://user-images.githubusercontent.com/64481641/155836574-860dd461-91fd-49df-9a39-9458db58e5c9.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

 Premium (v22.02-Beta04)

### Tema Yang Digunakan

Default

### Informasi tambahan

Noted

**Comment by andifahruddinakas** [comment]
Untu filter tahun di modul ini, jika memilih semua tahun sama saja kalau memilih filter tahun sekarang. Misalnya kasus di issue ini, semua tahun == 2022, tapi terjadi masalah krn tdk tampil.

**Comment by apidong** [comment]
sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/811
