### ISSUE TITLE
[OpenSID Mobile] Nama Penandatangan Pada Arsip Surat OpenSID Mobile Masih Muncul Nama Kepala Desa Bawaan 

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#4967]
### Jelaskan error yg dialami

Nama Penandatangan Pada Arsip Surat OpenSID Mobile Masih Muncul Nama Kepala Desa Bawaan System atas nama Muhammad Ilham

### Cara untuk mereplikasi errornya

1. Buka OpenSID Mobile
2. Pilih Arsip Surat 

### Hasil yg diharapkan

Agar Sesuai dengan Nama Kepala Desa yang menanda tangan pada surat yg ada pada system OpenSID Desa

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/64481641/155842047-721db6fc-9e6c-4c1e-8109-719cdd20ecd9.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Versi 1.0.7 OpenSID Mobile

### Tema Yang Digunakan

default

### Informasi tambahan

Noted

**Comment by agungsugiarto** [comment]
Issue ini saya tutup,

1. Pastikan di menu Info Desa > Pemerintah Desa sudah di pilih ttd a.n
2. Kemudian di Info Desa > Identitas Desa sudah dipilih kepala desanya
2. Clear cache opensid api
