### ISSUE TITLE
Bug/error: perlu diperbaiki fieldnya pada kolom komentar

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#4968]
### Jelaskan error yg dialami

Error ditemukan pada rilis premium terbaru

### Cara untuk mereplikasi errornya

Kirim komentar dengan isi script tertentu pada kolom nama

### Hasil yg diharapkan

normal

### Tangkapan layar dan log error

Hasil Log error gagal disimpan :
Query error: Data too long for column 'owner' at row 1 - Invalid query: INSERT INTO `komentar` (`komentar`, `owner`, `no_hp`, `email`, `status`, `id_artikel`) 

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Berputar

**Comment by apidong** [comment]
sudah diperbaiki melalui https://github.com/OpenSID/premium/pull/809
