### ISSUE TITLE
Bug/error: Notifikasi tidak sesuai Halaman Module

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#4969]
### Jelaskan error yg dialami

Simpan Data Pendaftaran Kerjasama, namun Gagal dengan Notifikasi Lembaga.

### Cara untuk mereplikasi errornya

Klik Simpan pada module pendaftaran kerjasama, setelah sebelumnya gagal tambah lembaga.

### Hasil yg diharapkan

Pesan Error sesuai module masing-masing.

### Tangkapan layar dan log error

<img width="960" alt="image" src="https://user-images.githubusercontent.com/46939846/155842416-da2559db-dd6c-49cc-91fa-5244a82e4cca.png">

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Berputar

**Comment by apidong** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/810
