### ISSUE TITLE
Tampilkan data penduduk yang status dasarnya mati/pindah/hilang

### ISSUE THREAD

**Issue by afri18** [OpenSID/OpenSID#497]
sebaiknya data di table logpenduduk adalah data pindahan dari table twebpenduduk dan table twebkeluarga (seperti biodata) ini sangat penting karna saya mengalami kehilangan data saat nomor KK suatu keluarga berubah karna pergantian kepalakelurga atau kepala keluarga wafat
![image](https://user-images.githubusercontent.com/6611881/27984496-b80f39f6-6401-11e7-924e-2bf9231b371f.png)

nantinya table logpenduduk ini bisa diisi dengan data warga yg sudah meninggal tahun sebelum penggunaan aplikasi, untuk menyatukan/mengumpulkan data desa

**Comment by eddieridwan** [comment]
@afri18 sebenarnya data keluarga dan data penduduk tidak dihapus pada saat status dasarnya diubah menjadi mati/hilang/pindah. Datanya masih ada di tabel tweb_keluarga dan tweb_penduduk, asal tidak melakukan aksi 'hapus'. Kalau dihapus, datanya hilang secara permanen.

**Comment by eddieridwan** [comment]
Mungkin yang diperlukan adalah cara untuk menampilkan data penduduk yang status dasarnya tidak lagi 'hidup'. Seperti di tabel Keluarga sekarang sudah ada filter untuk menampilkan keluarga yang status dasar kepala keluarganya mati/hilang/pindah.

Di SID 3.10 di tabel Penduduk, ada pilihan untuk menampilkan penduduk 'hilang' atau 'mati':
<img width="1332" alt="status-dasar" src="https://user-images.githubusercontent.com/249563/33011045-d007f4a0-ce30-11e7-8974-0283155db95b.png">

**Comment by eddieridwan** [comment]
Sekarang di halaman Penduduk disediakan pilihan untuk menampilkan penduduk mati/pindah/hilang. 
Sudah dicommit ke master.

**Comment by eddieridwan** [comment]
Perlu cek apa yg terjadi kalau anggota keluarga hilang/pindah/mati, dan kemudian nomor KK yang ditinggal berubah:

1. karena ganti kepala keluarga: KK yg lama seharusnya tidak dihapus. Buat KK baru. Jadi KK lama masih ada
2. karena kepala keluarga meninggal: KK yg lama seharusnya tidak dihapus. Buat KK baru. Jadi KK lama masih ada

Bagaimana @afri18 ?

**Comment by eddieridwan** [comment]
Nomor KK and nama kepala keluarga pada saat pencatatan peristiwa mati/hilang/pindah sudah direkam di tabel log_penduduk. Data itu yg ditampilkan di Log Penduduk. Jadi tetap akan tampil sama di laporan Log Penduduk walaupun data keluarga aslinya sudah diganti atau terhapus.

**Comment by eddieridwan** [comment]
Sekarang di halaman biodata penduduk yg status dasarnya mati/hilang/pindah tampilkan no_kk yg tersimpan di log_penduduk. Juga biodata penduduk yang status dasarnya mati/hilang/pindah tidak bisa diubah.

**Comment by afri18** [comment]
mantab ini bung @eddieridwan karna selama ini data kk selalu hilang bila kepala kk pindah atau wafat, ma'af lom bisa aktif karna pekerjaan benar2 numpuk, mempersiapkan laporan 2017 dan rencana kerja tahun 2018

**Comment by tiasn29-a11y** [comment]
Kk gimana cari nik kk orang yang sudah meninggal lama
