### ISSUE TITLE
[PREMIUM] Bug/error: Input NIK pada lupa pin layanan mandiri belum tervalidasi

### ISSUE THREAD

**Issue by mizwaruddin** [OpenSID/OpenSID#4970]
### Jelaskan error yg dialami

Saat melakukan lupa PIN, input PIN dapat diisi dengan sembarang karakter.

### Cara untuk mereplikasi errornya

1. Masuk login layanan mandiri
2. Klik lupa PIN
3. Isikan sembarang karakter ke input NIK
4. Semua karakter dapat diinputkan

### Hasil yg diharapkan

Input NIK dibatasi hanya angka dengan jumlah 16 digit

### Tangkapan layar dan log error

![bug_lupa_pin1](https://user-images.githubusercontent.com/39736008/155850859-2b7dda3b-0e01-4cfd-8431-69ac427339b9.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

OpenSID 22.02-premium-beta04

**Comment by apidong** [comment]
sudah diperbaiki di pr https://github.com/OpenSID/premium/pull/816
