### ISSUE TITLE
[PREMIUM] Bug/error: NIK tidak terdaftar di layanan mandiri muncul notif berhasil kirim PIN ke telegram/email pada fitur lupa PIN

### ISSUE THREAD

**Issue by mizwaruddin** [OpenSID/OpenSID#4971]
### Jelaskan error yg dialami

NIK tidak terdaftar di layanan mandiri muncul notif berhasil kirim PIN ke telegram/email pada fitur lupa PIN

### Cara untuk mereplikasi errornya

1. Masuk ke layanan mandiri
2. Klik lupa PIN
3. Inputkan NIK sembarang (tidak terdaftar di layanan mandiri)
4. Klik telegram/email
5. Muncul notif berhasil kirim PIN ke telegram/email

### Hasil yg diharapkan

Lupa PIN hanya berlaku bagi penduduk yang terdaftar di layanan mandiri

### Tangkapan layar dan log error

![bug_lupa_pin2](https://user-images.githubusercontent.com/39736008/155851237-a6327b3b-d0a2-43d9-8c1d-283d381a8b28.png)
![bug_lupa_pin3](https://user-images.githubusercontent.com/39736008/155851240-44392582-6ada-49b8-bedc-e1c44c9df4c8.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

OpenSID 22.02-premium-beta04

**Comment by andifahruddinakas** [comment]
Pak @mizwaruddin, terkait notifikasi bisa cek pembahasan di issue https://github.com/OpenSID/OpenSID/issues/4674

**Comment by scqolbu24** [comment]
issue ini kami tutup, karena bukan bug, sudah dipertimbangkan pada issue https://github.com/OpenSID/OpenSID/issues/4674
