### ISSUE TITLE
[PREMIUM] Bug/error: Total anggaran pada tambah pembangunan tidak terisi jika input sumber anggaran menggunakan up/down

### ISSUE THREAD

**Issue by mizwaruddin** [OpenSID/OpenSID#4972]
### Jelaskan error yg dialami

Total anggaran pada tambah pembangunan tidak terisi jika input sumber anggaran menggunakan up/down. Total anggaran terisi jika sumber anggaran diketik.

### Cara untuk mereplikasi errornya

1. Pembangunan-> tambah data
2. Pada isian sumber anggaran gunakan tanda up/down untuk menambahkan jumlah anggaran
3. Pada field anggaran tidak terisi

### Hasil yg diharapkan

Field anggaran tetap terisi jika pengisian anggaran pada masing2 sumber anggaran menggunakan tanda up/down

### Tangkapan layar dan log error

![bug_pembangunan_anggaran](https://user-images.githubusercontent.com/39736008/155851542-ff3f7707-ebe4-4c4e-b108-ae6e8f9bb0e2.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

OpenSID 22.02-premium-beta04

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki.

![akas12](https://user-images.githubusercontent.com/57283157/155851650-d61b430b-9dea-4fcb-a211-c31e77760b5c.png)
