### ISSUE TITLE
[PREMIUM] Bug/error: Kesalahan penulisan contoh no di media sosial 

### ISSUE THREAD

**Issue by mizwaruddin** [OpenSID/OpenSID#4973]
### Jelaskan error yg dialami

Pada contoh input nomor HP/WA di sosial media wap (085xxxxx), namun ketika diinputkan sesuai format contoh terjadi gagal mengirim pesan.

### Cara untuk mereplikasi errornya

1. Admin Web-> Sosial Media-> WAPP
2. Isikan nomor sesuai format contoh
3. Gagal mengirim pesan karena nomor tidak valid

### Hasil yg diharapkan

Pada format contoh seharusnya +62xxxxxxxxx

### Tangkapan layar dan log error

![bug_wa2](https://user-images.githubusercontent.com/39736008/155852615-6c2670ea-76a1-484d-9775-164442267b28.png)

![bug_wa1](https://user-images.githubusercontent.com/39736008/155852630-048a8f75-cd04-462b-a463-3dab69a890e3.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

OpenSID 22.02-premium-beta04

**Comment by apidong** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/814

**Comment by eril132** [comment]
+62 812-4371-7990

**Comment by eril132** [comment]
Bug_+62 812-4371-7990

**Comment by sanz512** [comment]
Bug_+62 831-8289-5661

**Comment by DyVillexzZeroone** [comment]
6283865228142

**Comment by minleh909-ai** [comment]
Bug nomor ini +6283854920069

**Comment by hermankmil09-droid** [comment]
wa.me/setting+62 838-4218-0774

**Comment by renzx188** [comment]
bug wa ini +62 878-7038-7551

**Comment by mangzmangz00-gif** [comment]
#9903 +62 858-5509-7926

**Comment by mangzmangz00-gif** [comment]
#9935 +62 858-5509-7926

**Comment by aisyah89367-droid** [comment]
#9935 +62 83823718146

**Comment by cacacicicaca46-debug** [comment]
bug wa 83152204500

**Comment by cacacicicaca46-debug** [comment]
#9935 +83152204500

**Comment by zar282751-ux** [comment]
bug+62 838-0022-5064

**Comment by sohibun2507-cpu** [comment]
bug wa +62 882-0057-61128

**Comment by randynasrullah497-netizen** [comment]
Bug_++62 812-4371-7990

**Comment by waerehan115-dev** [comment]
0823-4250-8286

**Comment by waerehan115-dev** [comment]
ikbal

**Comment by yosuafransprayogaa-oss** [comment]
+62 815-2934-3209

**Comment by batubara4596-cyber** [comment]
+62 831-3906-1466

**Comment by alfrafel6-blip** [comment]
+62 831-9415-3535

**Comment by pianstarboy12-jpg** [comment]
+62 823-7370-7051

**Comment by pianstarboy12-jpg** [comment]
+62 823-7370-7051

**Comment by pianstarboy12-jpg** [comment]
bug permanen

**Comment by silznyyanyo95-byte** [comment]
85830240656 bug no ini gua di php in cik sama dia tolong Yo bug kan

**Comment by ianiannn08-coder** [comment]
Include stacktrace here
I: Using Apktool 2.6.1 on whatsapp-messenger-2-22-24-18.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Users\....\AppData\Local\apktool\framework\1.apk
I: Regular manifest package...
I: Decoding file-resources...
S: Could not decode file, replacing by FALSE value: cr.xml
S: Could not decode file, replacing by FALSE value: cg8.xml
S: Could not decode file, replacing by FALSE value: ckr.xml
S: Could not decode file, replacing by FALSE value: bh5.png
S: Could not decode file, replacing by FALSE value: l0.png
S: Could not decode file, replacing by FALSE value: og.png
S: Could not decode file, replacing by FALSE value: vn.png
S: Could not decode file, replacing by FALSE value: lc.png
S: Could not decode file, replacing by FALSE value: b0r.png
S: Could not decode file, replacing by FALSE value: bbd.9.png
S: Could not decode file, replacing by FALSE value: lw.9.png
S: Could not decode file, replacing by FALSE value: 4e.png

[...]

S: Could not decode file, replacing by FALSE value: csr.xml
S: Could not decode file, replacing by FALSE value: b9q.png
S: Could not decode file, replacing by FALSE value: bzx.png
S: Could not decode file, replacing by FALSE value: b3f.png
S: Could not decode file, replacing by FALSE value: bay.png
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Baksmaling classes2.dex...
I: Baksmaling classes3.dex...
I: Baksmaling classes4.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
I: Copying META-INF/services directory

### Steps to Reproduce
1.  java -jar apktool.jar d whatsapp-messenger-2-22-24-18.apk

### Frameworks
-

### APK
https://whatsapp-messenger.de.uptodown.com/android
https://play.google.com/store/apps/details?id=com.whatsapp&hl=de&gl=US

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
Yes

2. If you are trying to install a modified apk, did you resign it?
I only try to decompile it

3. Are you using the latest apktool version?
Yes

**Comment by qiromirafli89-rgb** [comment]
rafli gunasan

**Comment by abibmuhalbaharabib-dotcom** [comment]
****

**Comment by abibmuhalbaharabib-dotcom** [comment]
1. [ ]

**Comment by dhotzgalaxyml-eng** [comment]
Bug

**Comment by adejpt2025-beep** [comment]
https://Wa.//082395384512.//bug.//nomor.//ini.//

**Comment by adejpt2025-beep** [comment]
https://wa.//62+2395384512.//bug.//nomor.//ini.//
https://github.com/OpenSID/OpenSID/issues/4973

**Comment by verdiana371-beep** [comment]
https://github.com/abibmuhalbaharabib-dotcom

**Comment by vennesa0608-hue** [comment]
857-2098-8957

**Comment by vennesa0608-hue** [comment]
857-2098-8957

**Comment by pnyvtan-prog** [comment]
+62 815-7574-8995

**Comment by adittganteng680-web** [comment]
831-1740-8743

**Comment by banjargacoridolaabahku-code** [comment]
+62 895-4028-98070

**Comment by yasrifaja305-blip** [comment]
> ### Jelaskan error yg dialami
> Pada contoh input nomor HP/WA di sosial media wap (085xxxxx), namun ketika diinputkan sesuai format contoh terjadi gagal mengirim pesan.
> 
> ### Cara untuk mereplikasi errornya
> 1. Admin Web-> Sosial Media-> WAPP
> 2. Isikan nomor sesuai format contoh
> 3. Gagal mengirim pesan karena nomor tidak valid
> 
> ### Hasil yg diharapkan
> Pada format contoh seharusnya +62xxxxxxxxx
> 
> ### Tangkapan layar dan log error
> ![bug_wa2](https://user-images.githubusercontent.com/39736008/155852615-6c2670ea-76a1-484d-9775-164442267b28.png)
> 
> ![bug_wa1](https://user-images.githubusercontent.com/39736008/155852630-048a8f75-cd04-462b-a463-3dab69a890e3.png)
> 
> ### Rilis Versi OpenSID
> Rilis Premium
> 
> ### Versi OpenSID
> OpenSID 22.02-premium-beta04
> 
> ### Tema Yang Digunakan
> _No response_
> 
> ### Informasi tambahan
> _No response_

+62 857-2418-5667

**Comment by yasrifaja305-blip** [comment]
Bug

**Comment by yasrifaja305-blip** [comment]
Bug karena tidak sopan

**Comment by yasrifaja305-blip** [comment]
+62 857-2418-5667

**Comment by wallback2233-design** [comment]
mau bug wa

**Comment by omanajhlah-crypto** [comment]
Bug +62 877-2298-4491
