### ISSUE TITLE
[PREMIUM] Bug/error: Kurang satu kolom pada tabel pendapat

### ISSUE THREAD

**Issue by mizwaruddin** [OpenSID/OpenSID#4974]
### Jelaskan error yg dialami

Kurang satu kolom pada tabel pendapat

### Cara untuk mereplikasi errornya

1. Layanan Mandiri-> Pendapat
2. Lihat pada tabel pendapat-> kurang satu kolom

### Hasil yg diharapkan

Jumlah kolom sesuai antara th dengan td

### Tangkapan layar dan log error

![bug_pendapat](https://user-images.githubusercontent.com/39736008/155852931-bbc480cf-ed50-436f-b636-b418f35ba409.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

OpenSID 22.02-premium-beta04

**Comment by scqolbu24** [comment]
sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/813
