### ISSUE TITLE
[PREMIUM-BETA04] Masih Ada Satu Lagi : Filter Vaksin Dosis 1, Masih Menampilkan Data Vaksin Dosis ke 2 Dalam List  

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#4975]
### Jelaskan error yg dialami

Filter Data  Vaksin Dosis ke 1, akan tetapi Masih Menampilkan Data Vaksin Dosis ke 2 dalam list

![image](https://user-images.githubusercontent.com/64481641/155870619-8ac653b0-8374-419f-9956-4f53df7cc4a4.png)

### Cara untuk mereplikasi errornya

1. Buka Fitur Vaksin
2. Pilih Filter Vaksin Dosis 1
3. Perhatikan di Kolom Keterangan Vaksin Dosis ke 2 juga tampil

### Hasil yg diharapkan

Filter Vaksin dapat ditampilkan menurut pilihan filter data

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/64481641/155870737-0e0a78e3-69d6-4a2d-92c3-431046adc812.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Premium (v22.02-beta04)

### Tema Yang Digunakan

default

### Informasi tambahan

noted

**Comment by andifahruddinakas** [comment]
@FirlianiF, keterangan (view) saja yg disesuaikan jika ada filter. krn filternya sendiri sy cek sudah sesuai.
