### ISSUE TITLE
Permintaan fitur: 

### ISSUE THREAD

**Issue by yudhaputra555** [OpenSID/OpenSID#4976]
### Apa kekurangan yg ingin diatasi?

sediakan pengguna akses level khusus publish lapak

### Jelaskan solusi yg diinginkan

sediakan pengguna akses level khusus publish lapak

### Apakah ada alternatif lain

sediakan pengguna akses level khusus publish lapak

### Untuk versi OpenSID mana

versi rilis umum 22.02

**Comment by ariandii** [comment]
sudah ada, bebas saja mau kasih level menu apa saja.

hanya lapak pun bisa.
silakan masuk menu Pengaturan -> Pengguna dan buat group nya.

Jika demikian bisa close issue ini

**Comment by andifahruddinakas** [comment]
https://github.com/OpenSID/OpenSID/wiki/Pengguna#pengelolaan-group-pengguna
