### ISSUE TITLE
[PREMIUM-BETA04] Tidak Dapat Menghapus ataupun Mengedit Format Surat Desa Tambahan

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#4978]
### Jelaskan error yg dialami

1. Tambahan Baru Format Surat Desa--> Setelah Dibuat Tidak Dapat Lagi Dihapus ataupun untuk Di Edit Kembali;
2. Saat Memilih Tombol Hapus --> System Hanya Menghapus "Kode/Klasifikasi Surat" Sedangkan Nama Suratnya Tidak Terhapus;

![image](https://user-images.githubusercontent.com/64481641/155998286-5e52371a-da5c-4187-afe4-94df05077878.png)

### Cara untuk mereplikasi errornya

1. Buka Fitur Layanan Surat
2. Pilih Pengaturan Surat
3. Klik Tambah Format Surat 
4. Buat Salah Satu Format Surat Tambahan --> Klik Simpan
5. Langkah Selanjutanya Klik Tombol Hapus atau; pilih
6. Edit Surat --. Koreksi Nama Surat --. Klik Simpan

### Hasil yg diharapkan

Fitur Layanan Surat-->Pengaturan Surat Dapat Berfungsi dengan baik, baik untuk Menambah Format Surat, Memperbaiki/Menggantikan Judul Surat mampun Menghapus Format Surat Tambahan yang tidak diperlukan lagi..

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/64481641/155999799-8816da78-5416-4e73-855b-419eb5040dac.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

premium (v22.02-beta04)

### Tema Yang Digunakan

default

### Informasi tambahan

noted

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/830
