### ISSUE TITLE
File unduh kartu keluarga sebaiknya menggunakan format date dd-mm-yyyy

### ISSUE THREAD

**Issue by mranca** [OpenSID/OpenSID#4979]
### Jelaskan error yg dialami

Sebaiknya unduh kartu keluarga tanggal lahir menggunakan format date dd-mm-yyyy

### Cara untuk mereplikasi errornya

Gunakan format tanggal lahir tipe dd-mm-yyyy

### Hasil yg diharapkan

![Screenshot_20220228_222302](https://user-images.githubusercontent.com/76085245/156000521-d8ad6f49-a2cb-4bd3-9b89-86cc961d9ff1.jpg)

### Tangkapan layar dan log error

![Screenshot_20220228_222253](https://user-images.githubusercontent.com/76085245/156000894-afe9604e-d946-4d48-8e6b-4079dedb04ea.jpg)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

22.02 rev 03

### Tema Yang Digunakan

Silir

### Informasi tambahan

Format tanggal lahir mengunakan tipe dd-mm-yyyy lebih umum di pakai di bandingkan dengan tipe format tanggal dd-mmmm-yyyy

**Comment by yogiperdana** [comment]
Issue ini termasuk ke dalam kategori permintaan fitur dan bukan bug

**Comment by agungsugiarto** [comment]
Sudah di fitur premium melalui pr https://github.com/OpenSID/premium/pull/960
