### ISSUE TITLE
[PREMIUM] Pengaturan Indikator Analisis -> Tambah Indikator & Pertanyaan Tidak Dapat Memilih Secara Langsung Pilihan Tipe Pertanyaan

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#4980]
### Jelaskan error yg dialami

Saat Menambah Indikator & Pertanyaan,  Tidak Dapat Memilih Secara Langsung Pilihan Tipe Pertanyaan (Pilihan Tipe Pertanyaan No Aktif), Setelah Indikator Pertanyaan Disimpan --. Harus Memilih Kembali Tombol Edit Untuk Memilih/Merubah Tipe Pertanyaan.

### Cara untuk mereplikasi errornya

1. Buka Fitur Analisis -> Pilih Master Analisis
2. Buat Tambah Analisis Baru
3. Buat Kategori/Variabel Analisis
4. Pilih Indikator & Pertanyaan --> Klik Tambah Indikator Baru 

### Hasil yg diharapkan

Supaya Pilihan Tipe Pertanyaan Langsung dapat di Pilih di Saat Indikator dan Pertanyaan Dibuat sekali jalan, sehingga tidak perlu harus mengulang edit setelah Indikator Pertanyaan Ditambah untuk memilih Pilihan Tipe Pertanyaan

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/64481641/156016671-88ae9ba7-951f-47c8-9e68-fd30baaa9b0e.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

OpenSID (v22.03-premium)

### Tema Yang Digunakan

default

### Informasi tambahan

noted

**Comment by andifahruddinakas** [comment]
Cek web https://berputar.opensid.or.id/analisis_indikator/form sudah tdk ada masalah, silahkan issue ini dibuka kembali jika masih menemukan masalah tsb.

![analisis 1](https://user-images.githubusercontent.com/57283157/156296890-53906722-69cb-4e56-9adb-872dceeb7669.png)
