### ISSUE TITLE
Permintaan fitur : Panjang Tulisan (Jumlah Karakter) Kolom Klasifikasi Analisis 

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#4982]
### Apa kekurangan yg ingin diatasi?

Permintaan Tambah Pangjang Jumlah Karakter Kolom Klasifikasi Analisis pada Fitur Master Analisis, saat jumlah karakter yang masukkan/di input sangat  terbatas sehingga membuat keterangan Klasifikasi Analisis kurang maksimal

![image](https://user-images.githubusercontent.com/64481641/156035695-bfbfe061-8fbf-42c7-879a-3e13ffd6d6d5.png)

### Jelaskan solusi yg diinginkan

Untuk Karakter/Kalimat Yang di input pada Kolom Klasifikasi Analisis Minimal memuat 36 Karekter seperti tulisan kalimat berikut:
1. Keluarga Pra Sejahtera; atau
2. Keluarga Sejahtera III Plus; 

### Apakah ada alternatif lain

Idem

### Untuk versi OpenSID mana

OpenSID (v22.03-premium)

### Informasi tambahan

Idem

**Comment by agungsugiarto** [comment]
Sudah di fitur premium melalui pr https://github.com/OpenSID/premium/pull/942
