### ISSUE TITLE
Bug/error: sitemap.xml masih menggunakan index.php

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#4985]
### Jelaskan error yg dialami

https://berputar.opensid.or.id/sitemap.xml

### Cara untuk mereplikasi errornya

https://berputar.opensid.or.id/sitemap.xml

### Hasil yg diharapkan

alamat web pada sitemap.xml tanpa index.php

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

-

### Tema Yang Digunakan

-

### Informasi tambahan

alamat web pada artikel sudah tanpa index.php menjadi dupliasi ketika robot google mengindex web

**Comment by andifahruddinakas** [comment]
Sudah digabung melalui PR https://github.com/OpenSID/premium/pull/823
