### ISSUE TITLE
Bug/error: Perbaikan saat pemeriksaan untuk kasus username yg duplikat (sama / tdk uniq)

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#4986]
### Jelaskan error yg dialami

Saat update ke versi 22.03-premium, dilakukan pemeriksaan database dan terjadi error duplikasi username

### Cara untuk mereplikasi errornya

Update ke versi 22.03-premium dengan menggunakan DB bermasalah tsb

### Hasil yg diharapkan

Ada tombol perbaikan otomatis

### Tangkapan layar dan log error

![photo_2022-03-01_14-50-09](https://user-images.githubusercontent.com/57283157/156119812-7df6f0ee-c452-4131-b935-da99534fd73b.jpg)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.03

### Tema Yang Digunakan

bawaan

### Informasi tambahan

null

**Comment by agungsugiarto** [comment]
mas bisa kirim contoh database yg bermasalah ?

**Comment by andifahruddinakas** [comment]
> mas bisa kirim contoh database yg bermasalah ?

yg punya gak mau kasih databse, untuk duplikasi ini hapus uniq key di tabel user kolom username. buat data yg sama.

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/825
