### ISSUE TITLE
Bug/error: tambahkan validasi log error yg ditampilkan

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#4988]
### Jelaskan error yg dialami

Jika terjadi error validasi misalnya menginput `<script>alert('akas')</script>` pada modul yg belum ada validasi, error tsb akan tercata ke log. Jika modul info_system akan mengeksekusi `<script>alert('akas')</script>` tsb

### Cara untuk mereplikasi errornya

Lakukan inpu pada modul yg belum memiliki validasi
test input `<script>alert('akas')</script>`

### Hasil yg diharapkan

script `<script>alert('akas')</script>` tdk tereksekusi pada file log

### Tangkapan layar dan log error

Contoh query error
ERROR - 2022-03-01 14:10:36 --> Query error: Data too long for column 'kode_surat' at row 1 - Invalid query: UPDATE `tweb_surat_format` SET `kode_surat` = '<script>alert('akas')</script>', `nama` = 'ltscript srchttpsbitly3uMU03Kgtltscriptgt', `masa_berlaku` = '1', `satuan_masa_berlaku` = 'M', `qr_code` = '0', `mandiri` = '1'
WHERE `id` = '1'

saat akses info_sistem
![hack1](https://user-images.githubusercontent.com/57283157/156123198-24803669-d157-4fba-8326-7f3c436e51bc.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.03-premium

### Tema Yang Digunakan

bawaan

### Informasi tambahan

Ini hanya berlaku jika admin sudah login, biasa terjadi di website demo.

**Comment by agungsugiarto** [comment]
di modul apa saja mas @andifahruddinakas ?

**Comment by andifahruddinakas** [comment]
> di modul apa saja mas @andifahruddinakas ?

untuk issue ini khusus info_system, yg menampilkan log yg berisi script. Misalnya : 
ERROR - 2022-03-01 14:10:36 --> Query error: Data too long for column 'kode_surat' at row 1 - Invalid query: UPDATE tweb_surat_format SET kode_surat = '<script>alert('akas')</script>', nama = 'ltscript srchttpsbitly3uMU03Kgtltscriptgt', masa_berlaku = '1', satuan_masa_berlaku = 'M', qr_code = '0', mandiri = '1'
WHERE id = '1'

**Comment by andifahruddinakas** [comment]
Sudah digabung melalui PR https://github.com/OpenSID/premium/pull/824
