### ISSUE TITLE
[PREMIUM-22.03] Pesan Log Error Setelah Migrasi

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#4989]
### Jelaskan error yg dialami

Setalah melakukan Migrasi, Migrasi Berjalan dengan Baik dan Sukses, akan tetapi ada banyak pesan log error seperti :
uzzleHttp\Exception\ConnectException: cURL error 6: Could not resolve host: layanan.opendesa.idindex.php (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://layanan.opendesa.idindex.php/api/v1/pelanggan/catat-versi in /home/teupinbe/public_html/vendor/guzzlehttp/guzzle/src/Handler
 

### Cara untuk mereplikasi errornya

1. Buka Pengaturan DataBase --> Klik Migrasi
2. Buka Pengaturan Info System ->Logs 

### Hasil yg diharapkan

Agak logs error tersebut tidak lagi muncul setelah migrasi

### Tangkapan layar dan log error

<?php defined('BASEPATH') OR exit('No direct script access allowed'); ?>

ERROR - 2022-03-01 15:10:57 --> GuzzleHttp\Exception\ConnectException: cURL error 6: Could not resolve host: layanan.opendesa.idindex.php (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://layanan.opendesa.idindex.php/api/v1/pelanggan/catat-versi in /home/teupinbe/public_html/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:210
Stack trace:
#0 /home/teupinbe/public_html/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(158): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)
#1 /home/teupinbe/public_html/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(110): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#2 /home/teupinbe/public_html/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(47): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#3 /home/teupinbe/public_html/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(28): GuzzleHttp\Handler\CurlHandler->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#4 /home/teupinbe/public_html/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(48): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#5 /home/teupinbe/public_html/vendor/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php(64): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#6 /home/teupinbe/public_html/vendor/guzzlehttp/guzzle/src/Middleware.php(31): GuzzleHttp\PrepareBodyMiddleware->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#7 /home/teupinbe/public_html/vendor/guzzlehttp/guzzle/src/RedirectMiddleware.php(71): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#8 /home/teupinbe/public_html/vendor/guzzlehttp/guzzle/src/Middleware.php(63): GuzzleHttp\RedirectMiddleware->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#9 /home/teupinbe/public_html/vendor/guzzlehttp/guzzle/src/HandlerStack.php(75): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#10 /home/teupinbe/public_html/vendor/guzzlehttp/guzzle/src/Client.php(331): GuzzleHttp\HandlerStack->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#11 /home/teupinbe/public_html/vendor/guzzlehttp/guzzle/src/Client.php(168): GuzzleHttp\Client->transfer(Object(GuzzleHttp\Psr7\Request), Array)
#12 /home/teupinbe/public_html/vendor/guzzlehttp/guzzle/src/Client.php(187): GuzzleHttp\Client->requestAsync('POST', Object(GuzzleHttp\Psr7\Uri), Array)
#13 /home/teupinbe/public_html/vendor/guzzlehttp/guzzle/src/ClientTrait.php(95): GuzzleHttp\Client->request('POST', 'https://layanan...', Array)
#14 /home/teupinbe/public_html/donjo-app/core/MY_Security.php(226) : eval()'d code(1) : eval()'d code(386): GuzzleHttp\Client->post('https://layanan...', Array)
#15 /home/teupinbe/public_html/donjo-app/core/MY_Security.php(226) : eval()'d code(1) : eval()'d code(277): Premium->kirimVersi()
#16 /home/teupinbe/public_html/donjo-app/core/MY_Security.php(226) : eval()'d code(1) : eval()'d code(407): Premium->validasi()
#17 /home/teupinbe/public_html/donjo-app/core/MY_Security.php(226) : eval()'d code(1) : eval()'d code(46): Admin_Controller->__construct()
#18 /home/teupinbe/public_html/vendor/codeigniter/framework/system/core/CodeIgniter.php(518): Database->__construct()
#19 /home/teupinbe/public_html/index.php(423): require_once('/home/teupinbe/...')
#20 {main}
ERROR - 2022-03-01 15:10:59 --> GuzzleHttp\Exception\ConnectException: cURL error 6: Could not resolve host: layanan.opendesa.idindex.php (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://layanan.opendesa.idindex.php/api/v1/pelanggan/catat-versi in /home/teupinbe/public_html/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:210
Stack trace:
#0 /home/teupinbe/public_html/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(158): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)
#1 /home/teupinbe/public_html/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(110): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#2 /home/teupinbe/public_html/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(47): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#3 /home/teupinbe/public_html/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(28): GuzzleHttp\Handler\CurlHandler->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#4 /home/teupinbe/public_html/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(48): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#5 /home/teupinbe/public_html/vendor/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php(64): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#6 /home/teupinbe/public_html/vendor/guzzlehttp/guzzle/src/Middleware.php(31): GuzzleHttp\PrepareBodyMiddleware->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#7 /home/teupinbe/public_html/vendor/guzzlehttp/guzzle/src/RedirectMiddleware.php(71): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#8 /home/teupinbe/public_html/vendor/guzzlehttp/guzzle/src/Middleware.php(63): GuzzleHttp\RedirectMiddleware->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#9 /home/teupinbe/public_html/vendor/guzzlehttp/guzzle/src/HandlerStack.php(75): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#10 /home/teupinbe/public_html/vendor/guzzlehttp/guzzle/src/Client.php(331): GuzzleHttp\HandlerStack->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#11 /home/teupinbe/public_html/vendor/guzzlehttp/guzzle/src/Client.php(168): GuzzleHttp\Client->transfer(Object(GuzzleHttp\Psr7\Request), Array)
#12 /home/teupinbe/public_html/vendor/guzzlehttp/guzzle/src/Client.php(187): GuzzleHttp\Client->requestAsync('POST', Object(GuzzleHttp\Psr7\Uri), Array)
#13 /home/teupinbe/public_html/vendor/guzzlehttp/guzzle/src/ClientTrait.php(95): GuzzleHttp\Client->request('POST', 'https://layanan...', Array)
#14 /home/teupinbe/public_html/donjo-app/core/MY_Security.php(226) : eval()'d code(1) : eval()'d code(386): GuzzleHttp\Client->post('https://layanan...', Array)
#15 /home/teupinbe/public_html/donjo-app/core/MY_Security.php(226) : eval()'d code(1) : eval()'d code(277): Premium->kirimVersi()
#16 /home/teupinbe/public_html/donjo-app/core/MY_Security.php(226) : eval()'d code(1) : eval()'d code(407): Premium->validasi()
#17 /home/teupinbe/public_html/donjo-app/core/MY_Security.php(226) : eval()'d code(1) : eval()'d code(46): Admin_Controller->__construct()
#18 /home/teupinbe/public_html/vendor/codeigniter/framework/system/core/CodeIgniter.php(518): Database->__construct()
#19 /home/teupinbe/public_html/index.php(423): require_once('/home/teupinbe/...')
#20 {main}
ERROR - 2022-03-01 15:11:01 --> GuzzleHttp\Exception\ConnectException: cURL error 6: Could not resolve host: layanan.opendesa.idindex.php (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://layanan.opendesa.idindex.php/api/v1/pelanggan/catat-versi in /home/teupinbe/public_html/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:210
Stack trace:
#0 /home/teupinbe/public_html/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(158): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)
#1 /home/teupinbe/public_html/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(110): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#2 /home/teupinbe/public_html/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(47): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#3 /home/teupinbe/public_html/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(28): GuzzleHttp\Handler\CurlHandler->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#4 /home/teupinbe/public_html/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(48): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#5 /home/teupinbe/public_html/vendor/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php(64): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#6 /home/teupinbe/public_html/vendor/guzzlehttp/guzzle/src/Middleware.php(31): GuzzleHttp\PrepareBodyMiddleware->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#7 /home/teupinbe/public_html/vendor/guzzlehttp/guzzle/src/RedirectMiddleware.php(71): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#8 /home/teupinbe/public_html/vendor/guzzlehttp/guzzle/src/Middleware.php(63): GuzzleHttp\RedirectMiddleware->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#9 /home/teupinbe/public_html/vendor/guzzlehttp/guzzle/src/HandlerStack.php(75): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#10 /home/teupinbe/public_html/vendor/guzzlehttp/guzzle/src/Client.php(331): GuzzleHttp\HandlerStack->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#11 /home/teupinbe/public_html/vendor/guzzlehttp/guzzle/src/Client.php(168): GuzzleHttp\Client->transfer(Object(GuzzleHttp\Psr7\Request), Array)
#12 /home/teupinbe/public_html/vendor/guzzlehttp/guzzle/src/Client.php(187): GuzzleHttp\Client->requestAsync('POST', Object(GuzzleHttp\Psr7\Uri), Array)
#13 /home/teupinbe/public_html/vendor/guzzlehttp/guzzle/src/ClientTrait.php(95): GuzzleHttp\Client->request('POST', 'https://layanan...', Array)
#14 /home/teupinbe/public_html/donjo-app/core/MY_Security.php(226) : eval()'d code(1) : eval()'d code(386): GuzzleHttp\Client->post('https://layanan...', Array)
#15 /home/teupinbe/public_html/donjo-app/core/MY_Security.php(226) : eval()'d code(1) : eval()'d code(277): Premium->kirimVersi()
#16 /home/teupinbe/public_html/donjo-app/core/MY_Security.php(226) : eval()'d code(1) : eval()'d code(407): Premium->validasi()
#17 /home/teupinbe/public_html/donjo-app/core/MY_Security.php(226) : eval()'d code(1) : eval()'d code(46): Admin_Controller->__construct()
#18 /home/teupinbe/public_html/vendor/codeigniter/framework/system/core/CodeIgniter.php(518): Database->__construct()
#19 /home/teupinbe/public_html/index.php(423): require_once('/home/teupinbe/...')
#20 {main}
ERROR - 2022-03-01 15:11:02 --> GuzzleHttp\Exception\ConnectException: cURL error 6: Could not resolve host: layanan.opendesa.idindex.php (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://layanan.opendesa.idindex.php/api/v1/pelanggan/catat-versi in /home/teupinbe/public_html/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:210
Stack trace:
#0 /home/teupinbe/public_html/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(158): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)
#1 /home/teupinbe/public_html/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(110): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#2 /home/teupinbe/public_html/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(47): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#3 /home/teupinbe/public_html/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(28): GuzzleHttp\Handler\CurlHandler->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#4 /home/teupinbe/public_html/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(48): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#5 /home/teupinbe/public_html/vendor/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php(64): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#6 /home/teupinbe/public_html/vendor/guzzlehttp/guzzle/src/Middleware.php(31): GuzzleHttp\PrepareBodyMiddleware->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#7 /home/teupinbe/public_html/vendor/guzzlehttp/guzzle/src/RedirectMiddleware.php(71): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#8 /home/teupinbe/public_html/vendor/guzzlehttp/guzzle/src/Middleware.php(63): GuzzleHttp\RedirectMiddleware->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#9 /home/teupinbe/public_html/vendor/guzzlehttp/guzzle/src/HandlerStack.php(75): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#10 /home/teupinbe/public_html/vendor/guzzlehttp/guzzle/src/Client.php(331): GuzzleHttp\HandlerStack->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#11 /home/teupinbe/public_html/vendor/guzzlehttp/guzzle/src/Client.php(168): GuzzleHttp\Client->transfer(Object(GuzzleHttp\Psr7\Request), Array)
#12 /home/teupinbe/public_html/vendor/guzzlehttp/guzzle/src/Client.php(187): GuzzleHttp\Client->requestAsync('POST', Object(GuzzleHttp\Psr7\Uri), Array)
#13 /home/teupinbe/public_html/vendor/guzzlehttp/guzzle/src/ClientTrait.php(95): GuzzleHttp\Client->request('POST', 'https://layanan...', Array)
#14 /home/teupinbe/public_html/donjo-app/core/MY_Security.php(226) : eval()'d code(1) : eval()'d code(386): GuzzleHttp\Client->post('https://layanan...', Array)
#15 /home/teupinbe/public_html/donjo-app/core/MY_Security.php(226) : eval()'d code(1) : eval()'d code(277): Premium->kirimVersi()
#16 /home/teupinbe/public_html/donjo-app/core/MY_Security.php(226) : eval()'d code(1) : eval()'d code(407): Premium->validasi()
#17 /home/teupinbe/public_html/donjo-app/core/MY_Security.php(226) : eval()'d code(1) : eval()'d code(46): Admin_Controller->__construct()
#18 /home/teupinbe/public_html/vendor/codeigniter/framework/system/core/CodeIgniter.php(518): Database->__construct()
#19 /home/teupinbe/public_html/index.php(423): require_once('/home/teupinbe/...')
#20 {main}
ERROR - 2022-03-01 15:11:02 --> Berhasil Jalankan migrasi_fitur_premium_2009
ERROR - 2022-03-01 15:11:02 --> Berhasil Jalankan migrasi_fitur_premium_2010
ERROR - 2022-03-01 15:11:02 --> Berhasil Jalankan migrasi_fitur_premium_2011
ERROR - 2022-03-01 15:11:02 --> Berhasil Jalankan migrasi_fitur_premium_2012
ERROR - 2022-03-01 15:11:02 --> Berhasil Jalankan migrasi_fitur_premium_2101
ERROR - 2022-03-01 15:11:02 --> Berhasil Jalankan migrasi_fitur_premium_2102
ERROR - 2022-03-01 15:11:02 --> Berhasil Jalankan migrasi_fitur_premium_2103
ERROR - 2022-03-01 15:11:02 --> Berhasil Jalankan migrasi_fitur_premium_2104
ERROR - 2022-03-01 15:11:03 --> Berhasil Jalankan migrasi_fitur_premium_2105
ERROR - 2022-03-01 15:11:03 --> Berhasil Jalankan migrasi_fitur_premium_2106
ERROR - 2022-03-01 15:11:03 --> Berhasil Jalankan migrasi_fitur_premium_2107
ERROR - 2022-03-01 15:11:03 --> Berhasil Jalankan migrasi_fitur_premium_2108
ERROR - 2022-03-01 15:11:03 --> Berhasil Jalankan migrasi_fitur_premium_2109
ERROR - 2022-03-01 15:11:03 --> Berhasil Jalankan migrasi_fitur_premium_2110
ERROR - 2022-03-01 15:11:03 --> Berhasil Jalankan migrasi_fitur_premium_2111
ERROR - 2022-03-01 15:11:03 --> Berhasil Jalankan migrasi_fitur_premium_2112
ERROR - 2022-03-01 15:11:04 --> Berhasil Jalankan migrasi_fitur_premium_2201
ERROR - 2022-03-01 15:11:04 --> Berhasil Jalankan migrasi_fitur_premium_2202
ERROR - 2022-03-01 15:11:04 --> Berhasil Jalankan migrasi_fitur_premium_2203
ERROR - 2022-03-01 15:11:04 --> Berhasil Jalankan migrasi_fitur_premium_2204
ERROR - 2022-03-01 15:11:04 --> Berhasil Jalankan migrasi_2203_ke_2204
ERROR - 2022-03-01 15:11:04 --> Berhasil Jalankan migrasi_layanan
ERROR - 2022-03-01 15:11:06 --> GuzzleHttp\Exception\ConnectException: cURL error 6: Could not resolve host: layanan.opendesa.idindex.php (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://layanan.opendesa.idindex.php/api/v1/pelanggan/catat-versi in /home/teupinbe/public_html/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:210
Stack trace:
#0 /home/teupinbe/public_html/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(158): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)
#1 /home/teupinbe/public_html/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(110): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#2 /home/teupinbe/public_html/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(47): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#3 /home/teupinbe/public_html/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(28): GuzzleHttp\Handler\CurlHandler->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#4 /home/teupinbe/public_html/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(48): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#5 /home/teupinbe/public_html/vendor/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php(64): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#6 /home/teupinbe/public_html/vendor/guzzlehttp/guzzle/src/Middleware.php(31): GuzzleHttp\PrepareBodyMiddleware->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#7 /home/teupinbe/public_html/vendor/guzzlehttp/guzzle/src/RedirectMiddleware.php(71): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#8 /home/teupinbe/public_html/vendor/guzzlehttp/guzzle/src/Middleware.php(63): GuzzleHttp\RedirectMiddleware->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#9 /home/teupinbe/public_html/vendor/guzzlehttp/guzzle/src/HandlerStack.php(75): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#10 /home/teupinbe/public_html/vendor/guzzlehttp/guzzle/src/Client.php(331): GuzzleHttp\HandlerStack->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#11 /home/teupinbe/public_html/vendor/guzzlehttp/guzzle/src/Client.php(168): GuzzleHttp\Client->transfer(Object(GuzzleHttp\Psr7\Request), Array)
#12 /home/teupinbe/public_html/vendor/guzzlehttp/guzzle/src/Client.php(187): GuzzleHttp\Client->requestAsync('POST', Object(GuzzleHttp\Psr7\Uri), Array)
#13 /home/teupinbe/public_html/vendor/guzzlehttp/guzzle/src/ClientTrait.php(95): GuzzleHttp\Client->request('POST', 'https://layanan...', Array)
#14 /home/teupinbe/public_html/donjo-app/core/MY_Security.php(226) : eval()'d code(1) : eval()'d code(386): GuzzleHttp\Client->post('https://layanan...', Array)
#15 /home/teupinbe/public_html/donjo-app/core/MY_Security.php(226) : eval()'d code(1) : eval()'d code(277): Premium->kirimVersi()
#16 /home/teupinbe/public_html/donjo-app/core/MY_Security.php(226) : eval()'d code(1) : eval()'d code(407): Premium->validasi()
#17 /home/teupinbe/public_html/donjo-app/core/MY_Security.php(226) : eval()'d code(1) : eval()'d code(46): Admin_Controller->__construct()
#18 /home/teupinbe/public_html/vendor/codeigniter/framework/system/core/CodeIgniter.php(518): Database->__construct()
#19 /home/teupinbe/public_html/index.php(423): require_once('/home/teupinbe/...')
#20 {main}
[log-2022-03-01.zip](https://github.com/OpenSID/OpenSID/files/8159938/log-2022-03-01.zip)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Premium (v22.03-premium)

### Tema Yang Digunakan

default

### Informasi tambahan

noted

**Comment by andifahruddinakas** [comment]
Layanan sudah di update, silahkan di cek lg.
