### ISSUE TITLE
Usul: sediakan halaman kirim berita/artikel oleh masyarakat biasa

### ISSUE THREAD

**Issue by mdwone** [OpenSID/OpenSID#499]
Selamat malam.. Disini saya ingin mengusulkan untuk di sediakann sebuah halaman pada website agar masyarakat biasa bisa ikut berpartisipasi dalam memberikan informasi, berita atau sebuah artikel yang bermanfaat. ( informasi, berita atau artikel yang dikirim akan di tampilkan di website setelah di setujui oleh oprator atau admin opensid) 
request halaman:
1. Register page
2. Login page
3. Admin page
Semoga usulan ini bisa menjadi bahan pertimbangan pengembangan opensid terimakasih...

**Comment by Marzuki5** [comment]
Menurut saya tinggal tambahkan form input artikel di layanan mandiri saja, yg langsung terintegrasi ke halaman admin SID biar bisa diverifikasi terlebih dahulu.

**Comment by afa28** [comment]
Sebaiknya tdk dimasukkan ke layanan mandiri, adapun jika ada warga yg ingin/punya potensi untuk menulis berita sebaiknya dibuatkan user sebagai penulis artikel (lvl usernya sy lupa 😆)

**Comment by afa28** [comment]
Sebaiknya tdk dimasukkan ke layanan mandiri, adapun jika ada warga yg ingin/punya potensi untuk menulis berita sebaiknya dibuatkan user login sebagai penulis artikel (lvl redaksi/kontributor)
