### ISSUE TITLE
Hasil unduh data rumah tangga tidak ada 

### ISSUE THREAD

**Issue by mranca** [OpenSID/OpenSID#4991]
### Jelaskan error yg dialami

Data tidak ada yang tampil

### Cara untuk mereplikasi errornya

Dashboard  > rumah tangga > laporan > unduh

### Hasil yg diharapkan

Harusnya ada yang tampil datanya

### Tangkapan layar dan log error

.

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

22.03

### Tema Yang Digunakan

Silir

**Comment by andifahruddinakas** [comment]
Sudah digabung melalui PR https://github.com/OpenSID/premium/pull/822

**Comment by mranca** [comment]
Oke
