### ISSUE TITLE
[Premium V22.03] Tanggal Penerbitan KTP Setelah Edit/Ubah Data Berubah menjadi tanggal sekarang atau tanggal simpan data

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#4992]
### Jelaskan error yg dialami

Tanggal Penerbitan KTP Setelah Edit/Ubah Data Berubah Otomatis menjadi tanggal sekarang atau tanggal simpan data

### Cara untuk mereplikasi errornya

1. Buka Data Penduduk-->Pilih Ubah Data
2. Ubah data apa saja sebagai contoh--> Pilih Simpan.
3. Klik Buka Kembali Biodata Penduduk--> Perhatikan Kolom Tanggal Penerbitan KTP

### Hasil yg diharapkan

Tetap Sesuai dengan tanggal yg sebenarnya yg masukkan bila tidak di rubah/edit

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/64481641/156172027-1b311f16-111f-4249-9e7a-0082134401c2.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

premium v22.03

### Tema Yang Digunakan

default

**Comment by andifahruddinakas** [comment]
@scqolbu24, @yogiperdana ada masalah saat melakukan mau melakukan update.

![photo_2022-03-02_11-49-35](https://user-images.githubusercontent.com/57283157/156293218-ec12ac91-8909-4e15-984b-d63e9312298f.jpg)

**Comment by andifahruddinakas** [comment]
Masalah ada di cache, perlu dihapus terlebih dahulu.
