### ISSUE TITLE
Bug/error: Periksa otomatis tabel tweb_cluster, field id_cluster jika deteksi error

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#4993]
### Jelaskan error yg dialami

Terjadi error jika database tdk sesuai dengan ketentuan dan akan di alihkan ke halaman periksa.

### Cara untuk mereplikasi errornya

Gunakan database bermalalah pada tabel tweb_keluarga field id_cluster berisi null

### Hasil yg diharapkan

Tersedia tombol periksa otomatis

### Tangkapan layar dan log error

![error db 1](https://user-images.githubusercontent.com/57283157/156320204-205670da-b65a-44bf-a05e-cba16d7cc7b2.jpg)
![errro db](https://user-images.githubusercontent.com/57283157/156320216-ebaa34d3-135a-4065-8972-565e6a9a166f.jpg)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.03

### Tema Yang Digunakan

bawaan

### Informasi tambahan

asdasd

**Comment by eddieridwan** [comment]
@andifahruddinakas apakah ada contoh database yg bermasalah? Seharusnya masalah ini tidak terjadi karena migrasi `donjo-app/models/migrations/Migrasi_fitur_premium_2107.php` sudah mengambil dari id_cluster penduduk yang dari awal tidak boleh null.

**Comment by andifahruddinakas** [comment]
> Migrasi_fitur_premium_2107

ya, seharusnya teratasi di migrasi versi sebelumnya. ini laporan dr group pengguna di premium yg masih ada kendala di masalah tsb.

**Comment by eddieridwan** [comment]
> ya, seharusnya teratasi di migrasi versi sebelumnya. ini laporan dr group pengguna di premium yg masih ada kendala di masalah tsb.

Tolong beri link ke pembahasan grup tersebut. Supaya diminta databasenya.

**Comment by andifahruddinakas** [comment]
https://t.me/c/1238304761/27959

**Comment by eddieridwan** [comment]
@andifahruddinakas sepertinya masalah ini hanya bisa terjadi kalau kepala keluarga dan anggota keluarga sudah tidak ada lagi di tweb_penduduk. Tapi tunggu dulu kalau ada yg dapat menyediakan databasenya.

**Comment by eddieridwan** [comment]
Solusi:
Deteksi keluarga dengan id_cluster null. Hanya terjadi pada kasus di mana keluarga tidak memiliki kepala keluarga atau anggota. Perbaiki dengan mengubah lokasi keluarga ybs menjadi lokasi keluarga pertama yang tidak kosong. Keluarga yang diubah dilaporkan di logs.

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/833
