### ISSUE TITLE
Permintaan fitur: pindah import dan export penduduk ke modul penduduk

### ISSUE THREAD

**Issue by yogiperdana** [OpenSID/OpenSID#4995]
### Apa kekurangan yg ingin diatasi?

Saat ini fitur untuk impor data rumah tangga ada di `Pengaturan > Database > Impor dan Export Database` yang membingungkan bagi pengguna pemula.

### Jelaskan solusi yg diinginkan

Pindahkan impor dan export data penduduk ke modul penduduk.

- [ ] Pindahkan import ke modul penduduk
- [ ] Pindahkan import BIP ke modul penduduk
- [ ] Pindahkan export ke modul penduduk

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

v22.03-premium

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/863
