### ISSUE TITLE
Permintaan fitur: penyesuaian import penduduk

### ISSUE THREAD

**Issue by yogiperdana** [OpenSID/OpenSID#4996]
### Apa kekurangan yg ingin diatasi?

Saat ini banyak yang menggunakan fitur import penduduk tidak sesuai dengan fungsinya seperti melakukan restore data penduduk dan mengubah struktur dan keanggotaan keluarga

### Jelaskan solusi yg diinginkan

Agar fitur import penduduk digunakan sebagaimana mestinya yaitu memasukkan data penduduk awal dan data susulan secara massal serta mengubah data penduduk yang sudah ada secara massal.

- Penambahan penduduk akan otomatis membuat keluarga sesuai data yg diimpor
- Penambahan penduduk akan otomatis membuat wilayah administratif sesuai data yg diimpor
- Jika penduduk yg diimpor sudah ada, data penduduk yg diperbolehkan diganti akan ditimpa dengan data yang diimpor
- Dapat mengenali data yang berisi kode maupun tulisan. Otomatis mengubah tulisan menjadi padanan kode sebelum disimpan
- Selain data identitas wajib, kolom data tidak harus terurut ataupun lengkap. Sebagai contoh, dapat digunakan untuk mengubah nomor telepon saja secara massal
- Data identitas wajib adalah NIK
- Data penduduk yg ditambah juga wajib berisi No KK, SHDK (status hubungan dalam keluarga), Dusun, RW, RT
- Kolom status dasar pada data penduduk yang ditambah akan menyebabkan pembuatan entri peristiwa mati/hilang/pindah (di log_penduduk) sesuai status dasar dengan tgl peristiwa dan tgl lapor disamakan dengan waktu impor dan pengisian data peristiwa lainnya yang bersifat default/placeholder
- Kolom status dasar, No KK, SHDK, Dusun, RW, RT akan selalu diabaikan bagi penduduk yang sudah ada
- Status dasar dapat diproses pada impor sebelum data penduduk dinyatakan lengkap untuk memungkinkan memasukkan data penduduk mati/hilang/pindah secara massal dalam rangka melengkapi data penduduk
- Untuk memungkinkan kolom data tidak terurut dan tidak lengkap, baris pertama pada setiap kolom diisi dengan nama kolom sesuai dengan nama kolom di tabel tweb_penduduk 

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

v22.03-premium

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/881
