### ISSUE TITLE
Permintaan fitur: penyesuaian import BIP

### ISSUE THREAD

**Issue by yogiperdana** [OpenSID/OpenSID#4997]
### Apa kekurangan yg ingin diatasi?

Saat ini banyak yang menggunakan fitur import penduduk tidak sesuai dengan fungsinya seperti melakukan restore data penduduk

### Jelaskan solusi yg diinginkan

Agar fitur import penduduk digunakan sebagaimana mestinya yaitu memasukkan data penduduk awal secara masal.

- Tidak dapat mengimpor BIP kalau data penduduk telah ada
- Penambahan penduduk akan otomatis membuat keluarga sesuai data yg diimpor
- Penambahan penduduk akan otomatis membuat wilayah administratif sesuai data yg diimpor
- Jika penduduk yg diimpor sudah ada, data penduduk yg diperbolehkan diganti akan ditimpa dengan data yang diimpor
- Dapat mengenali data yang berisi kode maupun tulisan. Otomatis mengubah tulisan menjadi padanan kode sebelum disimpan

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

v22.03-premium

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/877
