### ISSUE TITLE
Permintaan fitur: penyeuaian export data penduduk

### ISSUE THREAD

**Issue by yogiperdana** [OpenSID/OpenSID#4998]
### Apa kekurangan yg ingin diatasi?

Saat ini banyak yang menggunakan fitur export penduduk tidak sesuai dengan fungsinya seperti melakukan backup data penduduk

### Jelaskan solusi yg diinginkan

Agar fitur import penduduk digunakan sebagaimana mestinya yaitu mengirim data ke aplikasi lain dan membuat daftar penduduk untuk perubahan data secara massal.

- Mengekspor penduduk sesuai filter
- Mengekspor kolom data berikut:

- Tidak mengekspor kolom data berikut:
id
- Data id_cluster diekspor menjadi dusun/rw/rt terkait
- Data yang  diekspor menggunakan format yang siap diimpor melalui fitur Impor Data Penduduk

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

v22.03-premium

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/882
