### ISSUE TITLE
Bug/error: Tidak ada notif muncul saat menonaktifkan/mengaktifkan modul

### ISSUE THREAD

**Issue by totoprayogo1916** [OpenSID/OpenSID#4999]
### Jelaskan error yg dialami

tidak ada notif keluar saat menonatifkan /mengaktifkan modul

### Cara untuk mereplikasi errornya

bisa klik nonaktifkan/aktifkan atau tombol "kembalikan ke default ....." yang tersedia pada halaman pengaturan modul
![image](https://user-images.githubusercontent.com/2387514/156489085-d69d5a4d-78f3-4889-89a0-fe5e31d2e114.png)

### Hasil yg diharapkan

muncul notif bahwa modul A dinonaktifkan
atau modul B diaktifkan

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Umum

### Versi OpenSID

*

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/832
