### ISSUE TITLE
Bug/error: modul dimatikan, tapi data masih keluar dihalaman depan

### ISSUE THREAD

**Issue by totoprayogo1916** [OpenSID/OpenSID#5000]
### Jelaskan error yg dialami

contoh :
jika modul artikel (admin web) dimatikan
seharusnya halaman artikel dihalaman utama (front) tidak keluar

### Cara untuk mereplikasi errornya

nonaktifkan modul yang dipakai dan tampil di halaman depan
misal modul admin_web

### Hasil yg diharapkan

jika modul dimatikan, semestinya yang tampil di halaman depan tidak ikut tampil

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Umum

### Versi OpenSID

*

**Comment by agungsugiarto** [comment]
Pak @eddieridwan mas @andifahruddinakas bagaimana dengan issue ini, apakah perlu analisis terlebih dahulu karena sebelumnya sudah ada fitur pengaturan server untuk aktifkan/nonaktifkan penggunaan server khusus web

![image](https://user-images.githubusercontent.com/10989147/157003930-60998502-8dd3-4e69-aa0b-8774c7969270.png)

**Comment by eddieridwan** [comment]
@agungsugiarto  @andifahruddinakas Saya kira issue ini tidak tepat. Modul artikel tujuannya untuk mengelola artikel. Jika dinon-aktifkan maksudnya untuk tidak menyediakan fitur untuk mengelola artikel bagi server ybs atau pengguna tertentu. Tapi jika artikel sudah ada, saat ini tidak ada implikasi artikel itu harus dinon-aktifkan jika modulnya tidak aktif. Misalnya, jika modul Penduduk dinon-aktifkan, saat ini tidak ada implikasi data penduduk keseluruhannya juga dinon-aktifkan. Yang terjadi hanya OpenSID itu, atau pengguna di mana modul itu dinonaktifkan, tidak dapat mengelola data penduduk.

Saya kira issue ini ditutup saja.

**Comment by totoprayogo1916** [comment]
artinya, modul-modul dihalaman `siteman` itu hanya untuk admin/pengelola saja dampaknya ..
kalau begitu, harus ada informasi jelas mengenai fungsi aktif/non-aktif pada halaman modul  ...

**Comment by andifahruddinakas** [comment]
Sudah ditambahkan catatan pada https://github.com/OpenSID/OpenSID/wiki/Modul
