### ISSUE TITLE
[Penduduk] Sediakan tombol untuk hapus foto profil yang sudah di unggah

### ISSUE THREAD

**Issue by tobagus6911** [OpenSID/OpenSID#5003]
### Apa kekurangan yg ingin diatasi?

Tidak dapat menghapus foto profil. apabila salah mengupload foto dan belum ada foto pengganti. foto tersebut tidak dapat dihapus.

### Jelaskan solusi yg diinginkan

agar diberikan tombol untuk menghapus foto profil

### Apakah ada alternatif lain

untuk sementara jika salah mengupload foto profil. maka saya upload bingkai foto atau image background putih

### Untuk versi OpenSID mana

untuk versi umum dan premium

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/1054
