### ISSUE TITLE
Permintaan fitur: Pindahkan Gambar QRCode ke Folder Lain

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#5004]
### Apa kekurangan yg ingin diatasi?

Sepertinya issue ini sduah pernah dibuat dan sudah lama,

karena dicari tidak ketemu, saya buat baru saja. (nanti kalau ketemu tinggal ditandai duplicate saja).

Saat ini seluruh gambar artikel maupun QRCode jadi 1 di halaman file managar.

<img width="960" alt="screenshot_463" src="https://user-images.githubusercontent.com/46939846/156534971-4c11675c-84ae-45e7-948a-1c05f746d6ed.png">

<img width="960" alt="screenshot_462" src="https://user-images.githubusercontent.com/46939846/156534977-cfdb1f4e-efc6-4dba-b4b2-453e6dce2f44.png">

### Jelaskan solusi yg diinginkan

Sebaiknya, khusus file QRCode hasil cetak surat keterangan ada di folder khusus, tidak jadi 1 atau tidak muncul ketika ingin membuat artikel dan muncul pada saat buka file manager untuk insert gambar.

### Apakah ada alternatif lain

Jika bisa tidak perlu simpan file QRCode. "on the fly"

### Untuk versi OpenSID mana

22.03-premium

**Comment by totoprayogo1916** [comment]
sebaiknya, QRcode dibuat "on the fly"

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/951
