### ISSUE TITLE
Impor Data Vaksin Gagal

### ISSUE THREAD

**Issue by rsoeta** [OpenSID/OpenSID#5005]
gagal impor data vaksin

ini log error nya
![Screenshot (1915)](https://user-images.githubusercontent.com/86590833/156577441-5c1c24a9-d000-4704-ab38-484506b3f449.png)

ini contoh file 
![PicsArt_03-03-08 55 16](https://user-images.githubusercontent.com/86590833/156579075-3a362bf6-8bdf-49b7-9827-0c61772c4071.jpg)
yang 

.

**Comment by andifahruddinakas** [comment]
Pak @rsoeta kirim contoh data impor yg bisa direplikasi.

**Comment by rsoeta** [comment]
silakan pak @andifahruddinakas 
[https://1drv.ms/x/s!As5K1mvaYwMnmp5LYh7EHefMYphXVQ?e=TwT7Ja](url)

**Comment by andifahruddinakas** [comment]
Pak @rsoeta, contoh data sudah sy konversi ke data contoh (dgn NIK yg ada diberputar
[FormatImporVaksin (3).xlsx](https://github.com/OpenSID/OpenSID/files/8190146/FormatImporVaksin.3.xlsx)

Error : 
```
Query error: Illegal mix of collations (latin1_swedish_ci,IMPLICIT) and (utf8_general_ci,COERCIBLE) for operation '=' - Invalid query: SELECT `id`
FROM `tweb_penduduk`WHERE `nik` = '‌3205331238770002'
```

**Comment by rsoeta** [comment]
Saya coba import data contoh tersebut ke berputar, hasilnya Error pak

**Comment by andifahruddinakas** [comment]
> Saya coba import data contoh tersebut ke berputar, hasilnya Error pak

silahkan tunggu perbaikan, akan dicek menggunakan contoh data di atas.

**Comment by rsoeta** [comment]
Oh iya baik pak, terima kasih banyak

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/840

**Comment by ariandii** [comment]
gagal impor data aksin.

<img width="741" alt="image" src="https://user-images.githubusercontent.com/46939846/157107511-5853d59b-7ed0-415a-a530-78a48c03a8de.png">

**Comment by andifahruddinakas** [comment]
> gagal impor data aksin.
> 
> <img alt="image" width="741" src="https://user-images.githubusercontent.com/46939846/157107511-5853d59b-7ed0-415a-a530-78a48c03a8de.png">

sertakan contoh file yg di impor, gunakan data (NIK) yg ada di berputar.

**Comment by ariandii** [comment]
[Vaksinasi.xlsx](https://github.com/OpenSID/OpenSID/files/8200483/Vaksinasi.xlsx)

**Comment by andifahruddinakas** [comment]
> [Vaksinasi.xlsx](https://github.com/OpenSID/OpenSID/files/8200483/Vaksinasi.xlsx)

Silahkan di cek ulang di https://berputar.opensid.or.id/, kalau ada masalah lain mengenai impor vaksin silahkan komen disni sj.

**Comment by rsoeta** [comment]
Mohon koreksi nya pak
![Screenshot_20220308-063655_Chrome](https://user-images.githubusercontent.com/86590833/157137165-187a162d-83c3-4e36-8d9f-ebb6050d3931.jpg)

Ini file contoh nya 
[FormatImporVaksin.3.xlsx](https://github.com/OpenSID/OpenSID/files/8201522/FormatImporVaksin.3.xlsx)

**Comment by andifahruddinakas** [comment]
> Mohon koreksi nya pak
> ![Screenshot_20220308-063655_Chrome](https://user-images.githubusercontent.com/86590833/157137165-187a162d-83c3-4e36-8d9f-ebb6050d3931.jpg)
> 
> Ini file contoh nya 
> [FormatImporVaksin.3.xlsx](https://github.com/OpenSID/OpenSID/files/8201522/FormatImporVaksin.3.xlsx)
> 

Coba data ke 5 jenis vaksinnya di isi

**Comment by rsoeta** [comment]
![Screenshot_20220308-082119_Excel](https://user-images.githubusercontent.com/86590833/157146951-d620922d-c494-4c64-af5c-3be408463cb1.jpg)

Data kelima itu kan pak, yang saya tandai?

**Comment by andifahruddinakas** [comment]
> ![Screenshot_20220308-082119_Excel](https://user-images.githubusercontent.com/86590833/157146951-d620922d-c494-4c64-af5c-3be408463cb1.jpg)
> 
> Data kelima itu kan pak, yang saya tandai? 

Ya

**Comment by ariandii** [comment]
> > [Vaksinasi.xlsx](https://github.com/OpenSID/OpenSID/files/8200483/Vaksinasi.xlsx)
> 
> Silahkan di cek ulang di https://berputar.opensid.or.id/, kalau ada masalah lain mengenai impor vaksin silahkan komen disni sj.

<img width="580" alt="image" src="https://user-images.githubusercontent.com/46939846/157160028-5d3b7b71-8894-4d2c-99a5-5d21bf8171e5.png">

terima kasih, sudah sukses impor semua data vaksin

**Comment by ariandii** [comment]
<img width="516" alt="image" src="https://user-images.githubusercontent.com/46939846/157160631-6fc0fe4d-89b1-439f-9130-161bbe882553.png">

buka menu Laporan Rekap Data Vaksin, sering error 500 dengan log di atas.

begitu juga menu Laporan Penduduk Vaksin. akan error 500.
---
Namun setelah halaman Laporan Penduduk Vaksin di reload, akan tampil dan menu Laporan Rekap Data Vaksin diklik juga tampil

**Comment by andifahruddinakas** [comment]
> <img alt="image" width="516" src="https://user-images.githubusercontent.com/46939846/157160631-6fc0fe4d-89b1-439f-9130-161bbe882553.png">
> 
> buka menu Laporan Rekap Data Vaksin, sering error 500 dengan log di atas. kadang sukses terbuka.

berapa jumlah data penduduk ???

**Comment by ariandii** [comment]
<img width="455" alt="image" src="https://user-images.githubusercontent.com/46939846/157160980-3fc4afdf-25b9-4b0d-bad1-00dbe84dfb86.png">

1916 penduduk

**Comment by andifahruddinakas** [comment]
> <img alt="image" width="455" src="https://user-images.githubusercontent.com/46939846/157160980-3fc4afdf-25b9-4b0d-bad1-00dbe84dfb86.png">
> 
> 1916 penduduk

kayaknya perlu penyederhanaan perhitungan. mungkin bisa dibuat issuenya pak beserta contoh data yg bisa digunakan, database contoh yg bisa dikirim ke telegram.

**Comment by eddieridwan** [comment]
@andifahruddinakas @agungsugiarto @yogiperdana : periksa tidak ada yg looping
