### ISSUE TITLE
[premium][teknis] Upgrade ke CodeIgniter v3.1.13

### ISSUE THREAD

**Issue by totoprayogo1916** [OpenSID/OpenSID#5006]
Sudah tersedia rilis baru CodeIgniter 3.1.13
https://github.com/bcit-ci/CodeIgniter/releases/tag/3.1.13

**Comment by totoprayogo1916** [comment]
di versi umum, masih manual untuk upgrade nya

**Comment by agungsugiarto** [comment]
Terima kasih mas @totoprayogo1916, sudah melaporkan issue, issue ini saya ubah spesifik untuk premium. Seperti sudah dijelaskan di [rilis umum yang akan datang](https://github.com/OpenSID/OpenSID/wiki/Rilis-Umum-Yang-Akan-Datang#rilis-umum-v2207--2112-premium) di rilis premium sudah menggunakan composer untuk mengelola packages. Nantinya di rilis umum juga akan masuk jika sudah digabungan.

**Comment by andifahruddinakas** [comment]
https://github.com/OpenSID/premium/pull/831

**Comment by totoprayogo1916** [comment]
> https://github.com/OpenSID/premium/pull/831

bukannya lewat composer ya? 🤔

**Comment by andifahruddinakas** [comment]
> > [OpenSID/premium#831](https://github.com/OpenSID/premium/pull/831)
> 
> bukannya lewat composer ya? 🤔

untuk saat ini walaupun sudah menggunakan composer tp folder vendor tetap di upload. krn pengguna masih terbiasa upload semua script dan kadang ada yg belum terlalu paham menggunakan terminal untuk menjalankan composer update. mungkin selanjutnya mungkin bisa diberi panduan dan penjelasan mengenai peralihan menggukan composer beserta kelebihannya ke pengguna.
