### ISSUE TITLE
Bug/error: Error 500 jika widget tidak ditemukan

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#5007]
### Jelaskan error yg dialami

Widget statis aktif tapi filenya tidak ditemukan akan menyebabkan error 500.

### Cara untuk mereplikasi errornya

1. Buat widget statis
2. Hapus file widget tersebut (di folder desa)
3. Tampilkan web
4. Perhatikan error 500

### Hasil yg diharapkan

1. Otomatis non-aktifkan widget dinamis yg filenya tidak ditemukan, dan beri indikator/tanda permasalahannya. Supaya di web widget tersebut tidak akan ditampilkan dan menyebabkan error 500

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/249563/156867703-e3e528f3-6b4a-4556-8b26-3616a3e22e38.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.03-premium

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/834
