### ISSUE TITLE
Bug/error: Bug Kah? Pada Menu Wilayah administratif muncul pop up data statistik tp kosong

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#5008]
### Jelaskan error yg dialami

data statistik pada menu wilayah administratif kosong namun pada tampilan web berjalan normal

### Cara untuk mereplikasi errornya

login admin > masuk menu wilayah administratif > pilih peta wilayah dusun > check box tampilkan wilayah dusun > dekatkan kursor mouse /  klik nama dusun > muncul pop up data statistik kosong

### Hasil yg diharapkan

hilangkan pop up statistik / munculkan data statistik

### Tangkapan layar dan log error

![Untitled](https://user-images.githubusercontent.com/35319600/156874995-c5eda46e-d781-4ad6-977b-585ab11edbbb.jpg)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

22.03

### Tema Yang Digunakan

natra

### Informasi tambahan

di test pada web demo dan berputar hasilnya sama

**Comment by andifahruddinakas** [comment]
Solusi biar tidak duplikasi fungsi: 
1. Untuk form ubah data lokasi/wilayah sebaiknya hanya digunakan untuk mengubah data tsb sj, adapu data wilayah dan tingkatannya di gunakan sebagai referensi batas wilayah (tdk digunakan untuk menampilkan statistik)
2. Untuk menampilkan data statistik dll (yg lebih lengkap) bisa ditampilkan di modul pemetaan danatau ditampilkan ke halaman web.

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/845
