### ISSUE TITLE
Bug/error: error 500 pada menu  pengaturan peta tambah area

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#5009]
### Jelaskan error yg dialami

ketika menambahkan area tanpa memilih kategori kemudian simpan maka muncul 500 basis data error

### Cara untuk mereplikasi errornya

pergi ke halaman pengaturan peta > tambah area > isi data > biarkan isian kategori memilih kategori > simpan > muncul error 500

### Hasil yg diharapkan

tidak error

### Tangkapan layar dan log error

![Untitled](https://user-images.githubusercontent.com/35319600/156875887-bbe8056e-8c00-4219-bbbc-a20f2dea5971.jpg)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

22.03

### Tema Yang Digunakan

natra

### Informasi tambahan

pada menu pengaturan peta ini juga tidak ada menu tambah kategori baru, sehingga isian kategori tidak dapat d rubah / hanya bisa memilih bawaan sistem

**Comment by andifahruddinakas** [comment]
Solusi : 
1. Tambahkan required pd pilih kategori
2. Cek juga validasi

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/838
