### ISSUE TITLE
Permintaan fitur: perpanjang durasi cache untuk meningkatkan kecepatan website

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#5011]
### Apa kekurangan yg ingin diatasi?

cache file pada opensid memberikan sedikit waktu penyimpanan yang disarankan oleh google devtool untuk di perpanjang agar mempercepat waktu loading website

### Jelaskan solusi yg diinginkan

rekomendasi perpanjang waktu cache dapat di realiasikan

### Apakah ada alternatif lain

tidak ada

### Untuk versi OpenSID mana

22.03

### Informasi tambahan

hasil tangkapan layar devtool chrome merekomendasikan cache mempercepat loading website bagi pengunjung website yang sering mampir ke website kita

![Untitled](https://user-images.githubusercontent.com/35319600/156904552-d02a3538-87e4-4017-8d9b-9675f6495c5f.jpg)

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melalui pr https://github.com/OpenSID/premium/pull/957
