### ISSUE TITLE
Ganti contoh data awal dengan seeder

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#5014]
Saat ini pembuatan struktur database, termasuk data referensi, diisi dengan mengimpor contoh data awal. Contoh ini berisi data tambahan sebagai contoh. Dan juga membuat folder desa dengan menyalin dari desa-contoh, yg juga berisi file tambahan sebagai contoh.

Sebelum memulai mengisi data desa sebenarnya, data tambahan tersebut perlu dihapus menggunakan fitur Kosongkan DB. Dan seharusnya juga menghapus file tambahan yg ada di folder desa.

Cara ini rentan, karena desa belum tentu menghapus data contoh, sehingga ditemukan web desa yg masih berisi data contoh.

Issue ini untuk: 

- [x] menghapus data contoh awal
- [x] buat script untuk membuat/mengisi struktur database lengkap, termasuk data referensi
- [x] buat script untuk membuat struktur folder desa
- [x] jalankan script di atas pada waktu install OpenSID pertama kali

**Comment by eddieridwan** [comment]
Dengan solusi yg diterapkan, proses install awal menjadi sebagai berikut:

1. pasang script OpenSID
2. buka OpenSID
3. ikuti petunjuk yang ditampilkan, sbb:

<img width="752" alt="image" src="https://user-images.githubusercontent.com/249563/164950400-c60e1db2-aeb1-4fc4-b7eb-ddb49f017b24.png">

Folder desa dan data awal akan dibuat secara otomatis pada langkah (2). 

Data awal itu tidak berisi data contoh, sehingga desa dapat langsung memasukkan data desa sebenarnya. Tidak perlu lagi melakukan Kosongkan DB. 

Data awal yg dimuat adalah data awal sesuai dengan versi v22.03-premium. Data itu akan dimigrasi secara otomatis pada waktu membuka OpenSID.

**Comment by eddieridwan** [comment]
Untuk testing solusi ini, lakukan:

1. ikuti langkah untuk install awal seperti di atas
2. ikuti langkah untuk install awal seperti di atas, tapi buat database kosong sebelum membuka OpenSID
3. ikuti langkah seperti (2) di atas, tapi juga dengan membuat folder desa sebelum membuka OpenSID
4. ikuti langkah seperti (3) di atas, tapi juga dengan mengisi file desa/config/database.php dengan benar sebelum membuka OpenSID
5. periksa setelah update, dengan data dan folder desa yg sdh berjalan

**Comment by eddieridwan** [comment]
Untuk tema natra, karena tidak ada lagi contoh data awal, tidak ada lagi menu login. Dengan demikian, issue https://github.com/OpenSID/tema-natra/issues/104#issuecomment-1088537968 perlu juga diterapkan.

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/993
