### ISSUE TITLE
Hari di Tanggal kematian error terbalik, antara tanggal dan bulan

### ISSUE THREAD

**Issue by rsoeta** [OpenSID/OpenSID#5015]
![Screenshot (1921)](https://user-images.githubusercontent.com/86590833/157015099-0dc63ee0-a489-45ce-94c4-43d20ef453de.png)

**Comment by agungsugiarto** [comment]
Pak @rsoeta bisa dijelaskan terbalik seperti apa maksudnya ?

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/847

**Comment by rsoeta** [comment]
Di versi berikut masih terbalik pak, 
 tanggal 09-03-2022 itu seharusnya hari rabu bukan sabtu 

![PicsArt_03-10-08.13.24.jpg](https://user-images.githubusercontent.com/86590833/157567516-5a1eaf53-2851-49a6-97bf-2e626080cef4.jpg)
