### ISSUE TITLE
Menu Tanah di Desa Error 500

### ISSUE THREAD

**Issue by rsoeta** [OpenSID/OpenSID#5016]
### Jelaskan error yg dialami

Error ketika simpan di Tambah data

### Cara untuk mereplikasi errornya

1. Buku Administrasi Desa
2. Administrasi Umum
3. Buku Tanah di Desa
4. Tambah Data
5. Isi data
6. Error 500

### Hasil yg diharapkan

Data berhasil di tambah, dan dapat di export sesuai format buku A.6 Buku Tanah di Desa 

### Tangkapan layar dan log error

Lampiran capture 

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.03-premium

### Tema Yang Digunakan

Natra v4.5

### Informasi tambahan

Mohon dengan sangat, secepatnya agar di perbaiki.
Harapan saya dapat di simulasi kan di Lomba Desa Pasirlangu Kecamatan Pakenjeng Kabupaten Garut di pertengahan bulan maret ini

**Comment by rsoeta** [comment]
![Screenshot (1922)](https://user-images.githubusercontent.com/86590833/157048233-ec164c03-e1f9-4efb-b4ed-686aa041a46c.png)

**Comment by agungsugiarto** [comment]
Bisa lampirkan log errornya pak @rsoeta, kemudian isian apa saja yg diinput ?

**Comment by agungsugiarto** [comment]
Pak @rsoeta mohon jika ada kendala segera mengabari, agar issue ini bisa segera diselesaikan, terima kasih

**Comment by rsoeta** [comment]
Sekarang setelah update ke 22.03 rev-01 alhamdulillah sudah normal pak, mohon maaf karena kesibukan jadi saya kelupaan

**Comment by yogiperdana** [comment]
Baik pak. Kalau begitu issue ini kita anggap sudah selesai dan mohon izin untuk tutup ya pak
