### ISSUE TITLE
Permintaan fitur: Nonaktifkan menu Buku Administrasi Desa > Buku Keuangan

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#5017]
### Apa kekurangan yg ingin diatasi?

Saat ini menu Buku Administrasi Desa > Buku Keuangan belum berisi, tapi tampil di daftar menu sebagai placeholder. Ternyata cara ini menimbulkan pengharapan pada pengguna bahwa fitur itu akan segera diterapkan, sedangkan penerapan fitur tersebut belum terjadwalkan.

### Jelaskan solusi yg diinginkan

Tambahkan migrasi untuk menon-aktifkan modul Buku Administrasi Desa > Buku Keuangan. Tidak dihapus, hanya dibuat nonaktif saja.

### Apakah ada alternatif lain

Tidak ada

### Untuk versi OpenSID mana

v22.03-premium

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/851
