### ISSUE TITLE
[PREMIUM V22.03-REV01] Export Data Suplemen Terfilter Berdasarkan Jumlah Data yang di Filter Pada Layar

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#5021]
### Jelaskan error yg dialami

Saat Milih Fitur Export Data pada Fitur Suplemen, data yg ter-export hanya sejumlah data yg di filter di layar, bila data yang terfilter 20 data saat di export hanya ter-export 20 data atau 20 baris, begitu juga bila yg ditampilkan dilayar data maksimal 100 data maka saat export juga yg ter-export 100 data atau 100 baris data saja.

### Cara untuk mereplikasi errornya

1. Buka Fitur Suplemen
2. Pilih/Buka salah satu data suplemen
3. Klik Tombol Export

### Hasil yg diharapkan

Untuk export data harusnya seluruh data dalam satu data suplemen dapat di export seluruhnya tidak dibatasi oleh fiter data ataupun sejumlah data yg tampil pada layar kerja saja.

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/64481641/157233294-dd5e9c64-fa15-45c6-83b2-19883e61a976.png)

TAMPILAN DATA PADA LAYAR KERJA

![image](https://user-images.githubusercontent.com/64481641/157232719-4d2caf02-b116-483b-a3b4-d93b2953a4cc.png)

SAAT MEMILIH TOMBOL EXPORT UNTUK MENG-EXPORT DATA SEHARUSBTA 400 DATA LEBIH

![image](https://user-images.githubusercontent.com/64481641/157232935-9fbe2593-cf8d-440f-a683-3d36e4367968.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Premium (v22.03-Rev01)

### Tema Yang Digunakan

default

### Informasi tambahan

Noted

**Comment by eddieridwan** [comment]
@meagungsugiarto @yogiperdana9 sepertinya sebelumnya juga ada kebutuhan bisa ekspor berdasarkan data terfilter. Yaitu perlu bisa sediakan opsi: semua atau sesuai filter.

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/846
