### ISSUE TITLE
[PREMIUM V22.03-REV01] Bumindes-> Buku Peraturan Desa Plihan Kolom Jenis Peraturan Desa Berubah Menjadi Angka 1 Setelah DI Edit dan Disimpan

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#5022]
### Jelaskan error yg dialami

Bumindes-> Buku Peraturan Desa Plihan Kolom Jenis Peraturan Desa Berubah Menjadi Angka 1 Setelah DI Edit dan Disimpan

### Cara untuk mereplikasi errornya

1. Buka Buku Administrasi Desa
2. Buku Administrasi UMum
3. Pilih Buku Peraturan Desa
4. Edit Salah Jenis Peraturan Desa, Lalu Simpan

### Hasil yg diharapkan

Default

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/64481641/157263948-47b931bb-0bb7-4bb7-a6b5-b56d9aa20e42.png)

![image](https://user-images.githubusercontent.com/64481641/157264261-f3f1fe52-7141-43f6-9e4b-2243921fc30c.png)

![image](https://user-images.githubusercontent.com/64481641/157264322-07dc794b-33e9-4060-8cb9-9ee95763bb23.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

 Premium (v22.03-Rev01)

### Tema Yang Digunakan

default

### Informasi tambahan

Noted

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/878
