### ISSUE TITLE
PemakamanPermintaan fitur: 

### ISSUE THREAD

**Issue by afri18** [OpenSID/OpenSID#5023]
### Apa kekurangan yg ingin diatasi?

Agar penataan Tanah Pemakaman Umum di Desa lebih tertata dan di kelola dengan baik

### Jelaskan solusi yg diinginkan

Adanya menu Pemakan di Opensid yang nantinya penduduk yang berstatus mati bisa langsung masuk kedalam fitur ini

### Apakah ada alternatif lain

1. Tata Kelola Tanah Pemakaman Umum yang ada di desa tertata rapi
2. Dapat mengetahui siapa saja yang di makam kan di Tanah Makam Umum Desa tersebut
3. Mengetahui Status yang MATI di makamkan dimana

### Untuk versi OpenSID mana

v21.04 premium

### Informasi tambahan

1. Tempat pemakaman tidak hanya satu, bisa 2 atau lebih, jadi bisa menambahkan Nama Tempat Pemakaman
2. Beri pilihan Tempat dikubur :
    a. Tanah Pemakaman Umum A
    b. Tanah Pemakaman Umum B
    c. Tanah Pemakanan Keluarga (berarti di tanah pemakan keluarga yg mati)
   d. Luar Desa
4. Sekian dulu, yanglain nyusul

Issue ini juga dibahas pada https://forum.opendesa.id/d/20-pemakaman

**Comment by rohmanudin05** [comment]
👍

**Comment by PWidodo** [comment]
Di beberapa daerah Desa sudah ada aturan (SK. Bupati) tentang Kewajiban pendataan Tempat Pemakaman warga masyarakat yang menjelaskan lokasi almarhum/mah dimakamkan, dan saya rasa issue ini penting untuk di Pull Request dan masuk rilis bulan depan.

**Comment by luxmant354** [comment]
Up

**Comment by mukhlisvandjava** [comment]
Hayo.. lanjutkan... Kasian yang meninggal gak d urusi administrasinya..

**Comment by Wiliyantoro** [comment]
Mungkin bisa ditambahkan kategori
Khusus agama hindu ada istilah ngaben/dibakar

**Comment by balongbesuk** [comment]
bagus biar serah terima juru kunci baru gak bingung kl d tany warga

**Comment by yogiperdana** [comment]
Issue ini juga dibahas pada https://forum.opendesa.id/d/20-pemakaman

**Comment by andifahruddinakas** [comment]
Duplicate issue https://github.com/OpenSID/OpenSID/issues/6464
