### ISSUE TITLE
Permintaan fitur: FIlter Penduduk Berdasarkan Jenjang Usia

### ISSUE THREAD

**Issue by asarisoft** [OpenSID/OpenSID#5024]
### Apa kekurangan yg ingin diatasi?

Sebagai contoh mau mengundang kelompok usia tertentu untuk di vaksinasi,
dengan adanya filter tersebut akan lebih mudah mencari penduduk yang harus di vaksin.

### Jelaskan solusi yg diinginkan

Di List Penduduk sekarang sudah ada filter, tambahkan filter jenjang usia di sana.

### Apakah ada alternatif lain

Tidak

### Untuk versi OpenSID mana

Terakhir

**Comment by eddieridwan** [comment]
Sudah ada. Lihat panduan untuk Pencarian Spesifik. Silakan tutup issue ini kalau fitur itu sudah mencukupi

![image](https://user-images.githubusercontent.com/249563/157363088-ab1158e4-9801-403b-a437-468c5bf52ac1.png)
