### ISSUE TITLE
Sediakan cetak surat di anjungan mandiri

### ISSUE THREAD

**Issue by yudhaputra555** [OpenSID/OpenSID#5025]
### Apa kekurangan yg ingin diatasi?

kekurangan dari penduduk ketika memproses pembuatan surat penduduk tidak bisa cetak secara mandiri 

### Jelaskan solusi yg diinginkan

ketika penduduk register surat pengantar di layanan mandiri setelah di verifikasi oleh admin desa maka akan otomatis tersedia status surat siap cetak / unduh surat pengantar

### Apakah ada alternatif lain

alternatif lain jika diverifikasi oleh admin desa maka akan ada notif telegram bahwa surat sudah siap untuk diambil di kantor desa / pesan masuk berisi link unduh surat pengantar yang nantinya akan dicetak mandiri oleh warga yang mengajukan

### Untuk versi OpenSID mana

22.04 umum

### Informasi tambahan

skip

**Comment by eddieridwan** [comment]
**Catatan bagi programmer dan pengguna**

Perhatikan bahwa fitur ini sudah berkali-kali diminta dan issue terkait telah berkali-kali dibahas secara mendalam dan ditutup. Karena itu, biarkan issue ini tidak ditutup, supaya komunitas tidak lagi membuat issue serupa. 

Perhatikan bahwa fitur ini hanya dimungkinkan jika:

1. desa sudah memperoleh TTE, dan OpenSID sudah disesuaikan dengan ketentuan TTE dari BSrE

atau

2. ditambahkan fitur untuk mengunggah file scan surat yg telah ditandatangani basah, dan surat sudah dibubuhi QR Code yang dapat digunakan untuk verifikasi keabsahan surat tersebut. Itupun hanya jika desa bersedia mengambil tanggung jawab atas keabsahan surat yg berisi tanda tangan hasil scan (bukan basah) yg dipegang warga.

**Comment by hasap86** [comment]
> **Catatan bagi programmer dan pengguna**
> 
> Perhatikan bahwa fitur ini sudah berkali-kali diminta dan issue terkait telah berkali-kali dibahas secara mendalam dan ditutup. Karena itu, biarkan issue ini tidak ditutup, supaya komunitas tidak lagi membuat issue serupa.
> 
> Perhatikan bahwa fitur ini hanya dimungkinkan jika:
> 
> 1. desa sudah memperoleh TTE, dan OpenSID sudah disesuaikan dengan ketentuan TTE dari BSrE
> 
> atau
> 
> 2. ditambahkan fitur untuk mengunggah file scan surat yg telah ditandatangani basah, dan surat sudah dibubuhi QR Code yang dapat digunakan untuk verifikasi keabsahan surat tersebut. Itupun hanya jika desa bersedia mengambil tanggung jawab atas keabsahan surat yg berisi tanda tangan hasil scan (bukan basah) yg dipegang warga.

pilihan 2 bisa diterapkan dulu supaya bisa dimanfaatkan oleh beberapa desa yang mau melakukannya, adapun nanti proses ttd elektronik bisa menyusul bung

**Comment by yudhaputra555** [comment]
file surat tidak harus di tanda tangani oleh kepala desa dulu. jadi
sistemnya setelah di verifikasi admin desa maka  di layanan mandiri status
surat menjadi  surat siap cetak untuk warga mencetak mandiri setelah
tercetak mandiri baru warga memintakan cap tanda tangan stempel basah ke
kantor desa.
Kam, 10 Mar 2022 pukul 23.09 Hari Saputra ***@***.***>
menulis:

**Comment by hasap86** [comment]
ini bisa juga, kadang Kades juga bawa cap... jadi warga gak perlu ke kantor desa, bisa saja ke rumah kades

**Comment by yudhaputra555** [comment]
mantap, semoga bisa dipertimbangkan njih pak.. semoga bisa terealisasi dan
bermanfaat untuk desa desa

Jum, 11 Mar 2022 pukul 08.06 Hari Saputra ***@***.***>
menulis:

**Comment by tobagus6911** [comment]
SETUJU.....

**Comment by eddieridwan** [comment]
@vickyrolanda fitur ini bisa disediakan jika TTE valid terpasang

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1488
