### ISSUE TITLE
Permintaan fitur: Tambahkan tombol [  ] Full Screen pada menu wilayah administratif

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#5026]
### Apa kekurangan yg ingin diatasi?

bidang kerja terasa sempit

### Jelaskan solusi yg diinginkan

tambahkan toggle full screen pada menu peta

### Apakah ada alternatif lain

tidak ada

### Untuk versi OpenSID mana

21.03-Premium

### Informasi tambahan

![Untitled](https://user-images.githubusercontent.com/35319600/157573611-d402eac2-f0b3-40bd-809a-83a1faa7fbf8.jpg)

**Comment by balongbesuk** [comment]
https://codepen.io/tiggr/pen/poJoLyW

**Comment by andifahruddinakas** [comment]
Bisa lihat contoh yang sudah diterapkan di pantau, https://github.com/OpenSID/tracksid/commit/76f9884ec8ee2f7e198c075181adb6735736d78f

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui commit https://github.com/OpenSID/premium/commit/94af92cab445070b29a6406b1ddeef090fb32172 dan https://github.com/OpenSID/premium/commit/54c49516dc60adf6b4194fe05728c62f28b58e8c
