### ISSUE TITLE
Bug/error: Data desa yang ingin dimasukan tidak tersedia

### ISSUE THREAD

**Issue by alrizals** [OpenSID/OpenSID#5027]
### Jelaskan error yg dialami

desa Marindal I tidak tersedia pada pilihan ubah nama desa pada halaman identitas desa.

### Cara untuk mereplikasi errornya

- pergi ke halaman info desa
- klik tombol identitas desa
- pilih ubah data desa
- ketikan nama desa pada form nama desa

### Hasil yg diharapkan

menambahkan data desa Marindal I

### Tangkapan layar dan log error

![1](https://user-images.githubusercontent.com/57437589/157657493-7d1a1061-1279-4efa-be6c-b5325cff2710.png)

### Rilis Versi OpenSID

Rilis Umum

### Versi OpenSID

v22.03

### Tema Yang Digunakan

Natra

### Informasi tambahan

diharapkan penyelesaian masalah dikerjakan dengan cepat. Terima Kasih

**Comment by Zoel-WB** [comment]
Ini sebenarnya dapat langsung di PM-Kan ke OpenDesa atau Tim Teknis Pelaksana OpenDesa untuk memasukkan Nama Desa, Kecamatan, Kabupaten dan Provinsi sesuai dengan petunjuk Panduan System pada WIKI pada https://github.com/OpenSID/OpenSID/wiki/Identitas-Desa
cc : Pak @roaddee

**Comment by roaddee** [comment]
Apakah desa dimaksud desa baru ? Atau Hasil pemekaran ? Bisa dikirimkan bukti penunjang mengenai desa tersebut, misalnya SK Kades Dari Bupati.
