### ISSUE TITLE
PREMIUM V22.03 REV01 Bug/error : INSERT/EDIT IMAGE MELALUI FITUR INSERT RESPONSIVE FILEMANAGER TIDAK RESPON 

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#5028]
### Jelaskan error yg dialami

Insert Gambar Artikel Melalui Tombol/Fitur Insert/Edit Image tidak dapat dilakukan, saat dipilih hanya muncul layar kosong yg tidak respon hanya menampilkan kata RESPONSIVE FILEMANAGER dan layar tampil kosong

### Cara untuk mereplikasi errornya

1. Buka Fitur Admin Web
2. Pilih Artikel --. Buat Satu Artikel
3. Klik Pilihan Insert/Edit Image untuk menambah gambar di Artikel Melalui Fitur Responsive File Manager

### Hasil yg diharapkan

Agar bisa normal kembali seperti sebelumnya di awal Rilis premium v22.03 Premium masih berfungsi dengan baik, setelah menjadi Premium V22.03 Rev01 fitur ini tidak lagi berfungsi

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/64481641/157896451-5db14fdb-91e7-4db2-8d76-aa0c80e1260e.png)

Pilih Tombol Insert/Upload Gambar Artiker
![image](https://user-images.githubusercontent.com/64481641/157896735-26d449f6-77e8-4fea-a944-4c091a63348c.png)

Tampak Layar Tidak Respon

![image](https://user-images.githubusercontent.com/64481641/157896892-ad796c1a-2b25-4173-874e-771b24db86b7.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Premium (v22.03-Rwev01)

### Tema Yang Digunakan

Default

### Informasi tambahan

Noted

**Comment by yogiperdana** [comment]
Bagian mana yang tidak bisa pak? saya coba edit dan tambahkan berjalan normal

**Comment by Zoel-WB** [comment]
Form upload gambarnya tidak muncul, hanya menampilkan bagian Resposive Filemanager saja selanjutnya layarnya tidak aktif atau hanya tampilan layar kosong...

**Comment by yogiperdana** [comment]
![Capture](https://user-images.githubusercontent.com/14155050/158055225-ff265281-bbfc-4ead-875a-b5f6b5dfc97a.JPG)

Di tempat saya berjalan dengan normal pak

**Comment by Zoel-WB** [comment]
Ada beberapa teman pengguna juga melaporkan hal yg sama, saya coba di system saya juga sama tidak tampil form uploadnya, pengaruhnya dimana?

https://user-images.githubusercontent.com/64481641/158056526-3e90cd56-5654-4583-a658-577569017434.mp4

**Comment by Zoel-WB** [comment]
Biasanya tidak ada masalah disini di sebelum-sebelumnya, dan sering dicoba juga bila ada yg bertanya, sebelum update v22.03-rev01 memang lancar saja.

**Comment by agungsugiarto** [comment]
Pak @Zoel-WB, issue ini saya tutup, issue bisa diatasi dengan cara logout kemudian login kembali. Terima kasih
