### ISSUE TITLE
Premium V22.03 Rev01 Bug/error : Nama Pada Tempat Tanda Tangan Kepala Desa Pada Form Lampiran Surat Keterangan Pindah Penduduk Bukan Nama Kepala Desa Yang Dipilih  Pada System

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#5029]
### Jelaskan error yg dialami

Pada Halaman Print Out Lampiran Surat Keterangan Penduduk Masih Tercetak Nama Kepala Desa Bawaan Sistem atau Bukan Nama Kepala Desa Berdaasarkan Nama Desa yang ditentukan pada system OpenSID Desa.

### Cara untuk mereplikasi errornya

1. Bukan Fitur Cetak Surat
2. Pilih Surat Keterangan Pindah Penduduk
3. Pilih Cetak atau Print

### Hasil yg diharapkan

Agar tempat tanda tangan otomatis sesuai dengan Nama Desa dan Nama Kepala Desa yang telah di tentukan untuk Desa yang Dipilih

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/64481641/157898965-06d31d20-e2d4-4323-b866-4efa488ba2b7.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Premium (v22.03-Rwev01)

### Tema Yang Digunakan

Default

### Informasi tambahan
Pernah diperbaiki pada issue : #4725

**Comment by Zoel-WB** [comment]
cc: Mbak @FirlianiF 
1. Screensote form F-1.08 diatas saya ambil dari Pengguna Promium di Group Support
2. Hasil Test di System Saya juga sama mbak  @FirlianiF, Nama kepala desa yang tercetak tercantum pada lampiran Form F-1.08, yang tercetak bukan Nama Kepala Desa atau bahkan Nama tersebut tidak ada dalam Database desa artinya bukan data yang tercatak dari Database desa.

![image](https://user-images.githubusercontent.com/64481641/158049636-aa24eac3-9b2e-4fbd-85d8-48bfc9709fe3.png)

**Comment by yogiperdana** [comment]
Telah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/854
