### ISSUE TITLE
[Premium V22.03-Rev02] Gagal Restore Data di LocalHost dari data Backupdata 

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#5034]
### Jelaskan error yg dialami

Saat merestore kembali database backup terjadi error atau databackup tidak dapat direstore

### Cara untuk mereplikasi errornya

1. Jalankan System Update Terbaru dengan data bawaan system
2. Kemudian Buka Menu Pengaturan Database -->Kosongkan Seluruh Database atau tidak dikosongkan
3. Coba Restore Kembali dari Database backup

### Hasil yg diharapkan

Agar databse backup dari system dapat direstore kembali

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/64481641/158432515-7bb8e799-8b3b-4288-813b-83a06c2422de.png)

LOG ERROR :

GuzzleHttp\Exception\RequestException: cURL error 60: SSL certificate problem: certificate has expired (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://layanan.opendesa.id/api/v1/pelanggan/catat-versi in D:\https\Premium\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php:211
Stack trace:#0 D:\https\Premium\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(158): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)#1 D:\https\Premium\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(110): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))#2 D:\https\Premium\vendor\guzzlehttp\guzzle\src\Handler\CurlHandler.php(47): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))#3 D:\https\Premium\vendor\guzzlehttp\guzzle\src\Handler\Proxy.php(28): GuzzleHttp\Handler\CurlHandler->__invoke(Object(GuzzleHttp\Psr7\Request), Array)#4 D:\https\Premium\vendor\guzzlehttp\guzzle\src\Handler\Proxy.php(48): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}(Object(GuzzleHttp\Psr7\Request), Array)#5 D:\https\Premium\vendor\guzzlehttp\guzzle\src\PrepareBodyMiddleware.php(64): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}(Object(GuzzleHttp\Psr7\Request), Array)#6 D:\https\Premium\vendor\guzzlehttp\guzzle\src\Middleware.php(31): GuzzleHttp\PrepareBodyMiddleware->__invoke(Object(GuzzleHttp\Psr7\Request), Array)#7 D:\https\Premium\vendor\guzzlehttp\guzzle\src\RedirectMiddleware.php(71): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Request), Array)#8 D:\https\Premium\vendor\guzzlehttp\guzzle\src\Middleware.php(63): GuzzleHttp\RedirectMiddleware->__invoke(Object(GuzzleHttp\Psr7\Request), Array)#9 D:\https\Premium\vendor\guzzlehttp\guzzle\src\HandlerStack.php(75): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Request), Array)#10 D:\https\Premium\vendor\guzzlehttp\guzzle\src\Client.php(331): GuzzleHttp\HandlerStack->__invoke(Object(GuzzleHttp\Psr7\Request), Array)#11 D:\https\Premium\vendor\guzzlehttp\guzzle\src\Client.php(168): GuzzleHttp\Client->transfer(Object(GuzzleHttp\Psr7\Request), Array)#12 D:\https\Premium\vendor\guzzlehttp\guzzle\src\Client.php(187): GuzzleHttp\Client->requestAsync('POST', Object(GuzzleHttp\Psr7\Uri), Array)#13 D:\https\Premium\vendor\guzzlehttp\guzzle\src\ClientTrait.php(95): GuzzleHttp\Client->request('POST', 'https://layanan...', Array)#14 D:\https\Premium\donjo-app\core\MY_Security.php(226) : eval()'d code(1) : eval()'d code(379): GuzzleHttp\Client->post('https://layanan...', Array)#15 D:\https\Premium\donjo-app\core\MY_Security.php(226) : eval()'d code(1) : eval()'d code(270): Premium->kirimVersi()#16 D:\https\Premium\donjo-app\core\MY_Security.php(226) : eval()'d code(1) : eval()'d code(400): Premium->validasi()#17 D:\https\Premium\donjo-app\core\MY_Security.php(226) : eval()'d code(1) : eval()'d code(46): Admin_Controller->__construct()#18 D:\https\Premium\vendor\codeigniter\framework\system\core\CodeIgniter.php(519): Database->__construct()#19 D:\https\Premium\index.php(423): require_once('D:\\https\\Premiu...')#20 {main}

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Premium (v22.03-Rev02)

### Tema Yang Digunakan

default

### Informasi tambahan
1. Tester Restore dilakukan pada LocalHost
2. Dihosting tidak berani saya coba takut tidak dapat lagi mengembalikan data sebelumnya, karena systemnya rutin digunakan

**Comment by agungsugiarto** [comment]
Issue ini saya tutup karena errornya tidak berkaitan dengan backup / restore.
