### ISSUE TITLE
Bug/error: kosongkan lokasi peta tidak berfungsi

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#5036]
### Jelaskan error yg dialami

ketika ingin mengosongkan area yang sudah d gambar tidak bisa / tidak ada notif berhasil / gagal

### Cara untuk mereplikasi errornya

info desa > wilayah administratif > cari lokasi / area yang sudah di gambar > kosongkan > ....

halaman berpindah ke daftar  wilayah tanpa pesan error gagal / berhasil disimpan

### Hasil yg diharapkan

area bisa dikosongkan

### Tangkapan layar dan log error

tidak ada error pada log sistem

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

premium rev01

### Tema Yang Digunakan

-

### Informasi tambahan

-

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/861
