### ISSUE TITLE
Bug/error: tidak bisa menekan tombol ubahan di wilayah administratif

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#5037]
### Jelaskan error yg dialami

ketika legenda peta sudah banyak menutupi tombil ubahan peta

### Cara untuk mereplikasi errornya

Info desa > wilayah administratif > isikan peta desa sampai area rt > centang > wilayah rt >

legenda wilayah menutupi tombol ubahan peta

### Hasil yg diharapkan

tombol ubahan peta tidak tertutupi legenda peta / berada d atas legenda peta

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/35319600/158517097-abdd8379-e7dc-4008-b2ab-33327e3b50cc.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

22.03 rev01

### Tema Yang Digunakan

-

### Informasi tambahan

-

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/862
