### ISSUE TITLE
Bug/error: Bug Kah? menambah area lain pada lokasi area yang sama hanya tersimpan satu

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#5038]
### Jelaskan error yg dialami

https://github.com/OpenSID/OpenSID/issues/3464

sesuai pembahasan diatas pemetaan opensid sudah dapat menyimpan 2 area atau lebih pada satu lokasi yang sama tetapi barusan saya coba area lokasi yang tersimpan hanya area terakhir yang digambar

### Cara untuk mereplikasi errornya

Info desa > wilayah administratif > isikan 2 area atau lebih peta desa yang terpisah > simpan > lihat hasil

### Hasil yg diharapkan

dapat menyimpan 2 area / lebih kembali

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

22.03 rev01

### Tema Yang Digunakan

halaman admin

### Informasi tambahan

-

**Comment by agungsugiarto** [comment]
Pak @balongbesuk  saya tidak menemukan masalah yg dimaksud, seperti apa step yg dilakukan ketika mengisi?
mas @andifahruddinakas bisa dibantu untuk mereplikasi errornya?

**Comment by andifahruddinakas** [comment]
Untuk area yg menggunakan multipolygon hanya bisa digunakan pada pemetaan wilayah desa dan dusun saja.

@balongbesuk apakah yg bermasalah di wikayah rt dan rw??? Kalau iya, mmang itu tdk menggunakan multipolygon.

**Comment by balongbesuk** [comment]
owh saya kira berlaku untuk global, siap terima kasih

**Comment by andifahruddinakas** [comment]
> owh saya kira berlaku untuk global, siap terima kasih

Permintaan awal penggunaan peta multipolygon hanya 2 bagian itu sj. Jika ingin bisa digunakan ditempat lain, silahkan di buatkan permintaan fitur. Krn perlu ada beberapa penyesuaian sebelum menggunakan peta multipolygon.
