### ISSUE TITLE
[Premium V22.03-Rev02] Setelah Impor Database melalui PhpMyadmin, Database berubah bukan menjadi Collation utf8_general_ci 

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#5039]
### Jelaskan error yg dialami

1. Impor Data_contoh_awal ataupun dari data base backup melalui PHPMYADMIN, Setelah di Impor Database berubah bukan menjadi Collation utf8_general_ci.
2. Hal ini terjadi baik impor di locolhost maupun impor pada hosting
3. Pada hosting setelah impor database, ujicoba loading->website menjadi error
4. Pilih Perintah "Periksa" --> Pilih Tombol "Perbaiki" -> Database juga tidak terperbaiki  

### Cara untuk mereplikasi errornya

1. Lakukan import data melalui phpmyadmin baik di localhost maupun hosting.
2. Jalankan System->dan Login ke Database
3. Pilih Perintah "Periksa" di url _>http://localhost/Premium/periksa

### Hasil yg diharapkan

Agar bisa normal dan database tidak merubah Collation dari yang diinginkan dengan Collation type utf8_general_ci, baik impor di localhost maupun di hosting.

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/64481641/158544249-5214cc4b-7bac-4ef2-a01e-99fd1b6532b6.png)

Log Error Loading awal setelah mengimpor database dari contoh_data_awal pada hosting
<?php defined('BASEPATH') OR exit('No direct script access allowed'); ?>

ERROR - 2022-03-16 03:28:21 --> Error occured while loading url by cURL. <br />
Could not resolve host: api.kawalcorona.com
ERROR - 2022-03-16 03:28:21 --> Error occured while loading url by cURL. <br />
Could not resolve host: api.kawalcorona.com
ERROR - 2022-03-16 05:04:31 --> Error occured while loading url by cURL. <br />
Could not resolve host: api.kawalcorona.com
ERROR - 2022-03-16 05:04:31 --> Error occured while loading url by cURL. <br />
Could not resolve host: api.kawalcorona.com
ERROR - 2022-03-16 05:04:53 --> Error occured while loading url by cURL. <br />
Could not resolve host: api.kawalcorona.com
ERROR - 2022-03-16 05:04:53 --> Error occured while loading url by cURL. <br />
Could not resolve host: api.kawalcorona.com
ERROR - 2022-03-16 05:06:36 --> Error occured while loading url by cURL. <br />
Could not resolve host: api.kawalcorona.com
ERROR - 2022-03-16 05:06:36 --> Error occured while loading url by cURL. <br />
Could not resolve host: api.kawalcorona.com
ERROR - 2022-03-16 11:05:51 --> Error occured while loading url by cURL. <br />
Could not resolve host: api.kawalcorona.com
ERROR - 2022-03-16 11:05:51 --> Error occured while loading url by cURL. <br />
Could not resolve host: api.kawalcorona.com
ERROR - 2022-03-16 11:06:57 --> Error occured while loading url by cURL. <br />
Could not resolve host: api.kawalcorona.com
ERROR - 2022-03-16 11:06:57 --> Error occured while loading url by cURL. <br />
Could not resolve host: api.kawalcorona.com
ERROR - 2022-03-16 13:56:47 --> 404 Page Not Found: 
ERROR - 2022-03-16 13:57:55 --> Error occured while loading url by cURL. <br />
Could not resolve host: api.kawalcorona.com
ERROR - 2022-03-16 13:57:56 --> Error occured while loading url by cURL. <br />
Could not resolve host: api.kawalcorona.com
ERROR - 2022-03-16 07:18:03 --> 404 Page Not Found: Wp-loginphp/index
ERROR - 2022-03-16 14:32:14 --> Error occured while loading url by cURL. <br />
Could not resolve host: api.kawalcorona.com
ERROR - 2022-03-16 14:32:15 --> Error occured while loading url by cURL. <br />
Could not resolve host: api.kawalcorona.com
ERROR - 2022-03-16 14:33:11 --> 404 Page Not Found: 
ERROR - 2022-03-16 07:49:36 --> Unable to connect to the database
ERROR - 2022-03-16 07:49:36 --> Severity: error --> Exception: Call to a member function error() on string /home/teupinbe/public_html/donjo-app/core/MY_Security.php(226) : eval()'d code(1) : eval()'d code 70
ERROR - 2022-03-16 07:49:38 --> Unable to connect to the database
ERROR - 2022-03-16 07:49:38 --> Severity: error --> Exception: Call to a member function error() on string /home/teupinbe/public_html/donjo-app/core/MY_Security.php(226) : eval()'d code(1) : eval()'d code 70
ERROR - 2022-03-16 07:49:40 --> Unable to connect to the database
ERROR - 2022-03-16 07:49:40 --> Severity: error --> Exception: Call to a member function error() on string /home/teupinbe/public_html/donjo-app/core/MY_Security.php(226) : eval()'d code(1) : eval()'d code 70
ERROR - 2022-03-16 07:49:56 --> Unable to connect to the database
ERROR - 2022-03-16 07:49:56 --> Severity: error --> Exception: Call to a member function error() on string /home/teupinbe/public_html/donjo-app/core/MY_Security.php(226) : eval()'d code(1) : eval()'d code 70
ERROR - 2022-03-16 07:50:42 --> Unable to connect to the database
ERROR - 2022-03-16 07:50:42 --> Severity: error --> Exception: Call to a member function error() on string /home/teupinbe/public_html/donjo-app/core/MY_Security.php(226) : eval()'d code(1) : eval()'d code 70
ERROR - 2022-03-16 14:51:18 --> Error occured while loading url by cURL. <br />
Could not resolve host: api.kawalcorona.com
ERROR - 2022-03-16 14:51:19 --> Error occured while loading url by cURL. <br />
Could not resolve host: api.kawalcorona.com****

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Premium (v22.03-Rev01)

### Tema Yang Digunakan

default

### Informasi tambahan

.

**Comment by eddieridwan** [comment]
**Catatan bagi @Zoel-WB dan programmer:**

1. Hal ini tidak bisa dicegah, karena pengguna bebas menggunakan Phpmyadmin untuk restore database mereka. 
2. Tetapi sekarang sudah ada fitur Periksa -> Perbaiki yg otomatis mendeteksi kesalahan collation ini dan juga otomatis memperbaiki. Jadi tidak ada tindakan yg dapat dilakukan terkait impor menggunakan Phpmyadmin.
3. Tetapi saat ini fitur restore menggunakan fitur OpenSID (Pengaturan > Database > Restore) juga belum mencegah pengembalian collation salah yg ada di backup. Walaupun sebenernya bisa diatasi juga dengan langkah (2) di atas, mungkin ada baiknya supaya fitur restore otomatis mengubah collation ke yg benar. 

**Ok, untuk issue ini tindakan yg perlu dilakukan adalah langkah (3) di atas.**

**Comment by andifahruddinakas** [comment]
**Solusi  :** 
Saat lakukan restore database, ubah semua collation sesuai standar yang digunakan. (https://github.com/OpenSID/OpenSID/issues/5039#issuecomment-1069804492)

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/899
