### ISSUE TITLE
[Premium V22.03-Rev02] Penduduk Berubah Status Dasar "Hilang" Masih Terdapat Dalam Buku Induk Penduduk

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#5040]
### Jelaskan error yg dialami

Penduduk dengan status dasar "Hilang" masih terdapat dalam Buku Induk Kependudukan, sedang dalam Rekapitulasi Jumlah Penduduk sudah tidak lagi di hitung lagi dalam perhitungkan Rekap Penduduk Bulanan atau Buku Rekap Jumlah Penduduk (bumindes_penduduk_rekapitulasi)

### Cara untuk mereplikasi errornya

1. Buka Data Penduduk -. Pilih Salah Satu Data Penduduk
2. Pilih Rubah Status Dasar Menjadi "Hilang"
3. Buku Fitur Buku Administrasi Desa -> Administrasi Kependudukan
4. Buka Buku Induk Penduduk
5. Cari Nama Penduduk dengan Status Dasar "Hilang"

### Hasil yg diharapkan

Agar data Dalam Buku Induk Penduduk->Hanya Menampilkan Penduduk dengan Status Dasar Hidup Saja, sedangkan dengan status dasar yg lain tidak perlu dicantum dam buku induk penduduk desa karena untuk mengsinkron data dalam buku induk dan rekapitulasi penduduk tetap sama.

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/64481641/158582424-1e452db0-9794-4167-9398-5b55ecc8b8c3.png)

![image](https://user-images.githubusercontent.com/64481641/158582473-3fb2f99a-a97f-4812-a251-d536821c6a19.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Premium (v22.03-Rev02)

### Tema Yang Digunakan

.

### Informasi tambahan

.

**Comment by andifahruddinakas** [comment]
Pak @Zoel-WB, coba cek pembahasan di issue ini mengenai penduduk hilang. https://github.com/OpenSID/OpenSID/issues/3955
