### ISSUE TITLE
[Premium V22.03-Rev02] Rekapitulasi Data KK Pada Statistik Laporan Bulanan Tidak Tampil atau Tidak Terhitung Otomatis 

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#5041]
### Jelaskan error yg dialami

Input Data Penduduk melalui prosedur impor database dari data excel->data KK tidak otomatis terhitung dan tampil dalam perhitungan Rekapitulasi Statistik Laporan Bulanan.

### Cara untuk mereplikasi errornya

1. Buka Pengaturan Database.
2. Hapus/Kosongkan Semua Data.
3. Lakukan Impor Data Penduduk
4. Pergi Fitur Statistik --> Pilih Laporan Bulanan.
5. Data Jumlah KK untuk bulan dimaksud dari data yg di Import Tidak Masuk dalam Rekap.

### Hasil yg diharapkan

1. Data Penduduk inklud Nomor KK dalam Data Penduduk yang impor harusnya masuk sebagai Rekapitulasi KK Bulanan dari KK Pindah Masuk.
2. Dalam Daftar Tabel Log Penduduk juga harusnya data nomor KK yg sudah ada, karena dalam impor sudah ada KK dan Nomor KK .

### Tangkapan layar dan log error

1. Data yang di Impor
![image](https://user-images.githubusercontent.com/64481641/158591040-1715f6eb-9332-41e7-a357-a819d1814f2d.png)

2. Tampilan Hasil Impor Pada Dasboard System
![image](https://user-images.githubusercontent.com/64481641/158591149-8e7536c3-d34c-4eff-a726-f51285e2fdb6.png)

3. Tampilan Data dari Screensote Rekapitulasi Data Statistik Laporan Bulanan
![image](https://user-images.githubusercontent.com/64481641/158591373-2c466067-5a90-42ef-a3f5-9f27b252a4bb.png)

4. Tampil Data dari Tabel Log Penduduk 
![image](https://user-images.githubusercontent.com/64481641/158591449-bf777b2c-7f48-4921-b861-a7abddb7c026.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

 Premium (v22.03-Rev02)

### Tema Yang Digunakan

.

### Informasi tambahan
Perbaikan ini supaya semua fitur-fitur yg berhubungan dgn fitur data penduduk bisa fit semuanya

**Comment by andifahruddinakas** [comment]
Pak @Zoel-WB, cek pembahasan https://github.com/OpenSID/OpenSID/issues/4913

**Comment by Zoel-WB** [comment]
Oke pak, makasih infonya...
