### ISSUE TITLE
Bug/error: Laporan Ulang Mengenai Info Layanan di OpenSID umum

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#5042]
### Jelaskan error yg dialami

Informasi yang ada tidak lengkap. baterai merah padahal baru daftar, tanggal daftar kosong padahal baru daftar, icon gear double.

![IMG_20220317_094746_918](https://user-images.githubusercontent.com/46939846/158726610-05118e36-26f4-443f-a945-5156c09d38ee.jpg)

### Cara untuk mereplikasi errornya

di gambar atas

### Hasil yg diharapkan

normal

### Tangkapan layar dan log error

di atas

### Rilis Versi OpenSID

Rilis Umum

### Versi OpenSID

terbaru

**Comment by andifahruddinakas** [comment]
Susulan perbaikan, akan disesuaikan saat melakukan penggabungan rilis premium ke umum.

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melalui pr https://github.com/OpenSID/premium/pull/922,

untuk saat ini hanya akan diterapkan dirilis premium.
