### ISSUE TITLE
Bug/error: Perlebar ukuran tampilan Struktur Organisasi Pemerintah Desa baik printout maupun formnya 

### ISSUE THREAD

**Issue by PWidodo** [OpenSID/OpenSID#5044]
### Jelaskan error yg dialami

Halaman Bagan Struktur Organisasi Pemerintah Desa lebarnya dibatasi dengan scroll Left - Right baik dalam Form sistemnya maupun pada tampilan  dan hasil cetak (layouts).

### Cara untuk mereplikasi errornya

1. Login Admin
2. Menu Buku Administrasi Desa>Administrasi Umum
3. Sub Menu Buku Aparat Pemerintah Desa
4. Klik tombol aksi 'Bagan Organisasi'

### Hasil yg diharapkan

1. Tampilan from Bagan Organisasi lebarnya menyesuaikan lebar layar tanpa dibatasi dengan scrool Left-Right
2. Printout Bagan Organisasi baik Landscape maupun potrait lebarnya menyesuaikan ukuran kertas dan tanpa ada batasan scroll yang tampil.

### Tangkapan layar dan log error

1.  Gambar Form Bagan yang dibatasi ukuranya dengan scroll Left-Right dengan berbagai pilihan ukuran (800-1200-1400) ![tampilan sistem](https://user-images.githubusercontent.com/45189822/158728527-a76e38e8-9fa8-490a-8ceb-1f7017c74500.png)

2. Gambar Printout Bagan yang lebarnya juga dibatasi dengan scroll Left-Right ![print out sistem](https://user-images.githubusercontent.com/45189822/158728623-00ec3482-2a13-450f-8ded-3eb5d6be8110.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

premium v22.03_rev.02

### Tema Yang Digunakan

semua tema

**Comment by balongbesuk** [comment]
download file bagan organisasi juga tidak mengeluarkan gambar photo

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/865
