### ISSUE TITLE
[Premium V22.03-Rev02]  Bug atau Bukan Untuk Loading Fitur Vaksin Sangat Lambat Bila Jumlah Data Penduduk Yang Besar 

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#5049]
### Jelaskan error yg dialami

1. Input Data Vaksin, Pilih Fitur Daftar Penerima Vaksin ataupun Pilih Fitur Laporan Terasa Sangat Lambat untuk Desa Dengan jumlah Data Penduduk Yang Lebih Banyak.
2. Menampilkan data pada website juga sangat lambat terkadang website menjadi error dengan pesan error 500"Request Time Out"

### Cara untuk mereplikasi errornya

.

### Hasil yg diharapkan

Agar Loading data vaksin lebih cepat dan normal, dengan alternatif barang kali perlu penambahan Paginasi per jumlah baris data tertentu atau alternatif lain dapat membuka data vaksin lebih cepat.

### Tangkapan layar dan log error

Membuka Data Vaksin Pada website
![image](https://user-images.githubusercontent.com/64481641/158800750-a5ccd23e-d117-42a6-a6fd-e071731c31a8.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Premium (v22.03-Rev02)

### Tema Yang Digunakan

Halaman Admin

### Informasi tambahan
Uji Coba dengan 4500 data->pada website selalu gagal dan lebih sering terkena request time out atau error 500

**Comment by Wiliyantoro** [comment]
Saat menggunakan fitur menu vaksin (input, laporan dan rekap ) loading sangat lama,, delay hingga -+ 1 menit, dan saat simpan input vaksin , proses penyimpanan sangat lama,, website saya saat ini menggunakan vps opendesa, jumlah penerima vaksin 3500 orang,

**Comment by agungsugiarto** [comment]
Pak @Zoel-WB bisa kirim backup databasenya lewat dm telegram saya?

**Comment by Zoel-WB** [comment]
Backup sudah saya kirim via telegram pak

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/873
