### ISSUE TITLE
Perbaiki tampilan tabel statistik pada halaman peta yang bertumpuk

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#5050]
### Jelaskan error yg dialami

ketka pengguna melihat statistik di dalam menu peta statistik penduduk bertumpukan sehingga kurang jelas untuk dibaca

### Cara untuk mereplikasi errornya

buka menu web peta menggunakan HP > tekan salah satu wilayah > pilih statistik

### Hasil yg diharapkan

statistik menu peta tidak bertumpukan/ tertata rapi

### Tangkapan layar dan log error

![Untitled](https://user-images.githubusercontent.com/35319600/158940532-ab71429d-dd3e-491c-af0d-367e131a5f21.jpg)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

website berputar

### Tema Yang Digunakan

semua tema

### Informasi tambahan

-

**Comment by andifahruddinakas** [comment]
Pak @balongbesuk, issue ini sy ubah sebagai permintaan fitur untuk memindahkan viee oeta ke masing2 tema. Krn masing2 tema memiliki css/tampilannya sendiri

**Comment by balongbesuk** [comment]
> Pak @balongbesuk, issue ini sy ubah sebagai permintaan fitur untuk memindahkan viee oeta ke masing2 tema. Krn masing2 tema memiliki css/tampilannya sendiri

itu saya test d tema bawaan opensid sama seperti itu tampilannya
![natra](https://user-images.githubusercontent.com/35319600/159418125-98679d67-ad06-4223-85c7-8721c49140b1.png)

natra

![esensi](https://user-images.githubusercontent.com/35319600/159418131-0215fee1-206e-41da-86ad-db4934b71474.png)

esensi

**Comment by andifahruddinakas** [comment]
> > Pak @balongbesuk, issue ini sy ubah sebagai permintaan fitur untuk memindahkan viee oeta ke masing2 tema. Krn masing2 tema memiliki css/tampilannya sendiri
> 
> itu saya test d tema bawaan opensid sama seperti itu tampilannya
> ![natra](https://user-images.githubusercontent.com/35319600/159418125-98679d67-ad06-4223-85c7-8721c49140b1.png)
> 
> natra
> 
> ![esensi](https://user-images.githubusercontent.com/35319600/159418131-0215fee1-206e-41da-86ad-db4934b71474.png)
> 
> esensi

Iya, makanya perlu di pindahkan ke view masing2 tema. View peta saat ini menggunakan css dr admin + modifikasi, yg bisa sj berbeda dgn css yg digunakan oleh masing2 tema.

**Comment by mranca** [comment]
Di tema silir keren

**Comment by balongbesuk** [comment]
ok pak @andifahruddinakas  


informasi tambahan tampilan tabel statistik ini juga ada pada menu pemetaan > peta di dasboard admin dan hasilnya sama

**Comment by andifahruddinakas** [comment]
> ok pak @andifahruddinakas
> 
> informasi tambahan tampilan tabel statistik ini juga ada pada menu pemetaan > peta di dasboard admin dan hasilnya sama

ok, untuk kasus issue ini di khususkan perbaikan tampilan peta pada halaman admin saja.

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melalui pr https://github.com/OpenSID/premium/pull/939
