### ISSUE TITLE
Bug/error: Pada menu bantuan, untuk menambah daftar "Peserta Bantuan" button tambah data tidak muncul

### ISSUE THREAD

**Issue by winokman** [OpenSID/OpenSID#5051]
### Jelaskan error yg dialami

Bug/error: Pada menu bantuan, untuk menambah daftar "Peserta Bantuan" button tambah data tidak muncul, sehingga tidak bisa menambah data

### Cara untuk mereplikasi errornya

Bug/error: Pada menu bantuan, untuk menambah daftar "Peserta Bantuan" button tambah data tidak muncul, sehingga tidak bisa menambah data

### Hasil yg diharapkan

Mohon button tambah data di tampilkan

### Tangkapan layar dan log error

![Bug button tambah bantuan](https://user-images.githubusercontent.com/68093671/158942909-edd5bac0-d62b-422b-ad27-9b61a4d107a8.JPG)

### Rilis Versi OpenSID

Rilis Umum

### Versi OpenSID

22.03 Umum

### Tema Yang Digunakan

Natra

### Informasi tambahan

Bug/error: Pada menu bantuan, untuk menambah daftar "Peserta Bantuan" button tambah data tidak muncul, sehingga tidak bisa menambah data

**Comment by balongbesuk** [comment]
bantuan akan otomatis tertutup kl tanggal masa berlakunya sudah lewat, ubah tanggal masa berlaku bantuan

**Comment by winokman** [comment]
Terima kasih..
