### ISSUE TITLE
Permintaan fitur: Jumlahkan peta pengguna opensid seperti pada web pantau.opensid

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#5052]
### Apa kekurangan yg ingin diatasi?

ketika pengguna mencentang peta pengguna opensid maka semua lokasi pengguna tampil sehingga memberatkan kerja web

### Jelaskan solusi yg diinginkan

jumlahkan pengguna opensid seperti pada website pantau opensid sehingga tidak memberatkan browser

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

premium

### Informasi tambahan

![image](https://user-images.githubusercontent.com/35319600/158982387-65c6db09-4051-4cfa-a87e-2e3d284f0694.png)

pengguna opensid terload semua

![image](https://user-images.githubusercontent.com/35319600/158982491-4e2db6bd-cb55-4704-8af8-20e60c9122fa.png)

jumlahkan seperti pada website pantau

**Comment by andifahruddinakas** [comment]
Fiturt ini dihapus saja, untuk mencari data pengguna OpenSID bisa buka https://pantau.opensid.my.id/
