### ISSUE TITLE
Bug/error: BUG? Judul Grafik keuangan tidak berubah walaupun isian tahun berjalan

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#5053]
### Jelaskan error yg dialami

pada menu pemetaan web ketika pengguna menekan grafik keuangan header tabel grafik tetap menampilkan tahun 2019 walaupun isiannya sudah berubah tahun sekarang

### Cara untuk mereplikasi errornya

pergi ke halaman peta pada website > pilih wilayah desa > tekan grafik keuangan > lihat judul header grafik keuangan  

### Hasil yg diharapkan

mengikuti tahun berjalan

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/35319600/158986549-749ce209-8699-4001-9dd7-ffe35a53511e.png)

![image](https://user-images.githubusercontent.com/35319600/158986899-82d91ef6-4728-4bcf-81c7-ce68a9f69d3f.png)

karena kekurangan contoh isian pada website demo dan berputar maka saya mencoba test pada website pengguna

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

premium

### Tema Yang Digunakan

-

### Informasi tambahan

-

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/870
