### ISSUE TITLE
Bug/error: BUG? hasil cetak peta pada web tidak memunculkan nama desa dan arah mata angin

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#5054]
### Jelaskan error yg dialami

cetak peta pada halaman peta web tidak memunculkan nama desa dan arah mata angin

### Cara untuk mereplikasi errornya

buka website desa > buka halaman peta > centang beberapa lokasi > print map > hasilnya beda dengan cetak peta di menu admin

### Hasil yg diharapkan

bisa sama

### Tangkapan layar dan log error

![Peta_Wilayah(1)](https://user-images.githubusercontent.com/35319600/159009600-2f603a93-6dee-4785-bc62-8ce2a38c2664.png)

hasil cetak pada halaman website

![Peta_Wilayah(2)](https://user-images.githubusercontent.com/35319600/159009635-36360f57-599b-41cb-add2-714aa955d422.png)

hasil cetak pada halaman admin

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

website berputar

### Tema Yang Digunakan

-

### Informasi tambahan

-

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/872
