### ISSUE TITLE
Bug/error: Nama non warga di arsip layanan surat tidak dapat di cari di kolom pencarian

### ISSUE THREAD

**Issue by muhtar-coder** [OpenSID/OpenSID#5055]
### Jelaskan error yg dialami

Saat mencari nama pemohon di arsip layanan surat, pemohon nama non warga tidak dapat di cari atau tidak dapat di filter sehingga ketika mencari arsip layanan kesulitan.

### Cara untuk mereplikasi errornya

1. masuk menu layanan surat > 
2. arsip layanan surat > 
3. pilih jenis surat > 
4. cari nama pemohon non warga yang sebelumnya di pastikan sudah di buatkan surat

### Hasil yg diharapkan

dapat mem filter arsip surat pemohon warga desa dan pemohon non warga desa

### Tangkapan layar dan log error

1.
![image](https://user-images.githubusercontent.com/55665526/159055136-d7344260-d0c2-4541-bceb-39b68ffaaf7a.png)

2.
![image](https://user-images.githubusercontent.com/55665526/159053923-be534da9-2fe9-42be-91d1-e912083addfe.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

22.03 rev 02

### Tema Yang Digunakan

Denatra

### Informasi tambahan

tidak ada

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/874

**Comment by muhtar-coder** [comment]
Siap terima kasih

Pada tanggal Sel, 22 Mar 2022 pukul 07.51 Andi Fahruddin Akas <
***@***.***> menulis:
