### ISSUE TITLE
tambahkan Desa pada penandatangan surat

### ISSUE THREAD

**Issue by mranca** [OpenSID/OpenSID#5057]
### Apa kekurangan yg ingin diatasi?

kurangnya nama desa pada penandatangan 

### Jelaskan solusi yg diinginkan

usahakan tambahakan desa di penandatangan surat
![Screenshot (12)](https://user-images.githubusercontent.com/76085245/159093495-4473bf17-2437-42d6-bb7f-ab268a5b5e8a.png)

### Apakah ada alternatif lain

masukkan dari penganturan > aplikasi > sebutan desa.     
![Screenshot (11)](https://user-images.githubusercontent.com/76085245/159093511-81d3194b-fbb4-47fc-9942-5bd162854ca9.png)

### Untuk versi OpenSID mana

22.03 rev 02

### Informasi tambahan

-

**Comment by balongbesuk** [comment]
penanda tangan suratnya dikasih jabatan Kepala Desa / Kepala Kelurahan nanti muncul

**Comment by mranca** [comment]
Ok siap terima kasih
