### ISSUE TITLE
Permintaan fitur: Penambahan Status Perkawinan Cerai Hidup Tercatat/Tidak Tercatat

### ISSUE THREAD

**Issue by huntwijaya** [OpenSID/OpenSID#5058]
### Apa kekurangan yg ingin diatasi?

Seperti halnya dalam Perkawinan Status Kawin Tercatat dimana Masyarakat bisa membuktikan dengan Tercatatnya Perkawinan dalam Buku Nikah/Akta Nikah, apabila tidak tercatat tetap masuk Status KAwin namun belum tercatatkan.
Untuk Perceraian Pun Juga Sama apabila Masyarakat yang awalnya Kawin tidak Tercatat pada saat Cerai Hidup termasuk kedalam Cerai Hidup Tercatat,
Adapula Kasusnya masyarakat masih dalam Proses/belum diprosesnya Perceraian yang sebelumnya sudah dicatatkan di Pengadilan Agama/Negeri dan menikah lagi maka tetap harus memasukan dimasukan kedalam Kawin Tidak Tercatat.

### Jelaskan solusi yg diinginkan

<img width="538" alt="image" src="https://user-images.githubusercontent.com/92985345/159113888-16cc3d03-a6c7-4e0a-8d7c-4c43e071350b.png">
<img width="507" alt="image" src="https://user-images.githubusercontent.com/92985345/159114055-f9ee9a09-bacb-419d-8295-03ed29559c0b.png">
Penambahan Fitur Status Perkawinan :

1. Cerai Hidup Tercatat dengan Syarat (Akta Perceraian & Tgl Perceraian diisi)
2. Cerai Hidup Tidak Tercatat Apabila Tgl Perceraian tidak diisi.
3. Cerai Hidup Tercatat/Tidak Tercatat Nomor Akta Perkawinan dan Tgl Kawin sebelumnya di Disable tanpa menghapus isi Table sebagai Catatan Historis Penduduk tersebut tanpa perlu ditampilkan di Cetak KK.

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

Versi 22.03-premium-rev02

### Informasi tambahan

Issue ini juga dibahas pada https://forum.opendesa.id/d/15-penambahan-fitur-status-perkawinan-cerai-hidup-tercatat-tidak-tercatat

**Comment by huntwijaya** [comment]
<img width="610" alt="image" src="https://user-images.githubusercontent.com/92985345/159156645-171a07f6-c0c9-4a46-92e5-0f1b7ef93b00.png">
<img width="571" alt="image" src="https://user-images.githubusercontent.com/92985345/159156660-10aa1b08-4f7e-4a59-9018-20196e210100.png">


Status Pencatatan Perkawinan dalam Permendagri 108 Tahun 2019 Pasal 50 Ayat 4 dan juga dalam Lampiran Formulir Data Kependudukan Permendagri 109 Tahun 2019
[Permendagri 109/2019](https://jdihn.go.id/files/963/2019PERMENDAGRI109.pdf)
[Permendagri 108/2019](https://jdihn.go.id/files/963/2019PERMENDAGRI108.pdf)

**Comment by andifahruddinakas** [comment]
Laporan pada forum https://forum.opendesa.id/d/15-penambahan-fitur-status-perkawinan-cerai-hidup-tercatat-tidak-tercatat
