### ISSUE TITLE
Bug/error: Bug? Ubah status dasar pada tampilan HP Blank Putih

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#5059]
### Jelaskan error yg dialami

ketika pengguna menggunakan Hp untuk merubah status dasar penduduk yang tampil blank putih

### Cara untuk mereplikasi errornya

Buka Opensid menggunakan HP > pergi ke menu penduduk > cari nama penduduk > udah status dasar penduduk > blank Putih

### Hasil yg diharapkan

berjalan semestinya

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

22.03 premium rev02

### Tema Yang Digunakan

-

### Informasi tambahan

biasanya saya menggunakan Hp ketika mendapatkan informasi ada warga meninggal, langsung saya catatkan/ubah pada website, dan berjalan normal seleha update premium seperti ini

**Comment by agungsugiarto** [comment]
Pak @balongbesuk saya tidak menemukan masalah yg dimaksud, bisa jelaskan lahkah yg lebih terperinci misal dengan screenshoot/video?

Mas @andifahruddinakas bisa bantu replikasi masalahnya?

![image](https://user-images.githubusercontent.com/10989147/159229454-5cee219c-90fe-4da3-a504-e0f71f7a3597.png)

**Comment by balongbesuk** [comment]
kl d data penduduk langsung normal tp ketika sudah tahap di menu cari penduduk X kemudian ubah status dasar penduduk X tersebut maka akan blank 

sebentar sy buat videony dg contoh dari web berputar

**Comment by balongbesuk** [comment]
hm hari ini baik dari web berputar dan web saya lancar tanpa kendala, 🙄, 

sementara close dlu sampai bugny muncul kembali
