### ISSUE TITLE
Bug/error: Master layanan surat pada aplikasi ada kurang lebih 45 item, tetapi ketika mau buat surat layanan mandiri, master surat yg muncul hanya sekitar 12 item

### ISSUE THREAD

**Issue by winokman** [OpenSID/OpenSID#5063]
### Jelaskan error yg dialami

Bug/error: Master layanan surat pada aplikasi ada kurang lebih 45 item, tetapi ketika mau buat surat layanan mandiri, master surat yg muncul hanya sekitar 12 item

### Cara untuk mereplikasi errornya

Bug/error: Master layanan surat pada aplikasi ada kurang lebih 45 item, tetapi ketika mau buat surat layanan mandiri, master surat yg muncul hanya sekitar 12 item

### Hasil yg diharapkan

Mohon di layanan mandiri, jumlah master surat sama sejumlah 45 item yg ditampilkan

### Tangkapan layar dan log error

Bug/error: Master layanan surat pada aplikasi ada kurang lebih 45 item, tetapi ketika mau buat surat layanan mandiri, master surat yg muncul hanya sekitar 12 item

### Rilis Versi OpenSID

Rilis Umum

### Versi OpenSID

22.03

### Tema Yang Digunakan

Natra

**Comment by andifahruddinakas** [comment]
Surat yg ada di layanan mandiri defaultnya  sebatas surat untuk perorangan. Untuk menampilkan surat lain silahkan di atur sendiri pd admin pengaturan surat.
