### ISSUE TITLE
Bug/error: Hapus satu surat desa menghapus keseluruhan surat desa yang ada pada sistem

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#5065]
### Jelaskan error yg dialami

hapus satu surat pada surat ubahan desa menghapus keseluruhan surat pada seluruh surat desa yang terdapat pada sistem

### Cara untuk mereplikasi errornya

layanan surat > pengaturan surat > hapus satu surat ubahan desa > cek folder surat desa pada sistem > folder surat terhapus semua

### Hasil yg diharapkan

hanya menghapus surat yang dimaksud

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

premium rev02

### Tema Yang Digunakan

-

### Informasi tambahan

-

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/875
