### ISSUE TITLE
Perkenankan penambahan surat baru menggunakan tanda "-"

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#5066]
### Jelaskan error yg dialami

maksud pengguna ingin menyediakan Surat Pengantar E-KTP / Surat Pengantar KTP-el namun pada sistem opensid menyimpan nama tersebut dengan EKTP / KTPel dengan menghilangkan tanda "-"

### Cara untuk mereplikasi errornya

pergi ke pengaturan surat tambahkan surat yang dimaksud

### Hasil yg diharapkan

bisa menggunakan tanda "-"

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

website berputar

### Tema Yang Digunakan

-

### Informasi tambahan

-

**Comment by andifahruddinakas** [comment]
Pak @balongbesuk, untuk issue ini merupakan permintaan. Untuk perbaikan sementara yakni, perbaikan validasi agar konsisten tidak dapat menginput - saat buat surat.

**Comment by andifahruddinakas** [comment]
https://github.com/OpenSID/OpenSID/issues/5069

**Comment by balongbesuk** [comment]
surat desa yang saya buat sudah lama ada dengan menggunakan - 

mungkin perlu tambahkan validasi saja kl tidak boleh menggunakan karakter, 

karena saat ini sistem masih bs simpan cmn jadi berantakan kalimatny jd sy kira bug

**Comment by muhtar-coder** [comment]
Pada surat tambahan juga bila rtf di upload ulang ketika ada perbaikan kata/lain nya menyebabkan judul folder berubah menjadi huruf awal besar sehingga menyebabkan folder surat not found. Dan bila judul folder di perbaiki lagi akan normal.. 
masalah juga berlaku ketika edit nomor jenis surat.

**Comment by andifahruddinakas** [comment]
> Pada surat tambahan juga bila rtf di upload ulang ketika ada perbaikan kata/lain nya menyebabkan judul folder berubah menjadi huruf awal besar sehingga menyebabkan folder surat not found. Dan bila judul folder di perbaiki lagi akan normal.. 
> masalah juga berlaku ketika edit nomor jenis surat.

Dibuat issue lain pak @muhtar-coder

**Comment by agungsugiarto** [comment]
Sudah di fitur premium melalui pr https://github.com/OpenSID/premium/pull/938
