### ISSUE TITLE
Permintaan fitur: Sesuakan tampilan informasi yang ada di home

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#5067]
### Apa kekurangan yg ingin diatasi?

Forum OpenDesa di https://forum.opendesa.id/ dimaksudkan sebagai tempat utama bagi pengguna untuk melaporkan dan bertanya bila mengalami masalah teknis. Tetapi info terkait forum tsb saat ini belum ada di dashboard Admin.

### Jelaskan solusi yg diinginkan

Tambahkan info dan tautan ke Forum OpenDesa di dashboard Admin.

![image](https://user-images.githubusercontent.com/249563/159388820-521d1654-f07b-4d16-be52-5de1ece8a483.png)

### Apakah ada alternatif lain

Tambahkan footer yg lebih besar, di mana footer tersebut berisi tautan ke lokasi internal OpenSID maupun ke eksternal termasuk info yg saat ini ada di bagian Kontak dan Informasi.

![image](https://user-images.githubusercontent.com/249563/159389061-b0690c90-d4a9-47c3-9e85-0364ef3d5635.png)

### Untuk versi OpenSID mana

v22.03-premium

**Comment by agungsugiarto** [comment]
Alternatif tampilan

<img width="218" alt="image" src="https://user-images.githubusercontent.com/10989147/159407805-bb73cc34-b229-472f-bd86-d2c6eaa0d66d.png">

**Comment by balongbesuk** [comment]
![adminlte](https://user-images.githubusercontent.com/35319600/159416843-5d84ab5f-ff69-4692-9d1e-a74344273bb8.png)

atau dibikin icon taroh di atas biar makin kebaca bagi pengguna baru,

*saya sendiri jarang baca info yang pojok kanan itu 😄

**Comment by muhtar-coder** [comment]
Pengguna baru pun rata2 selalu melewati tautan yg di belah kanan..  bagusnya tetanggaan ama batrai.

**Comment by andifahruddinakas** [comment]
https://github.com/OpenSID/premium/pull/903

**Comment by agungsugiarto** [comment]
Sudah di fitur premium melalui pr https://github.com/OpenSID/premium/pull/940

![image](https://user-images.githubusercontent.com/10989147/163954966-3e84db0f-3f43-442d-85ff-59665e3edb3e.png)
