### ISSUE TITLE
[Premium 22.03 Rev03] Bug atau Efek Perbaikan -> Cetak Peta Tidak Menampilkan Logo Desa, Nama Kabupaten, Kecamatan dan Nama Desa

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#5070]
### Jelaskan error yg dialami

Saat mencetak Peta-> Tampilan Logo Desa tidak tampil di kolom legenda peta akan tetapi yg tampil logo opensid, Nama Kabupaten, Nama Kecamatan dan Nama Desa juga tidak ditampilkan

### Cara untuk mereplikasi errornya

Buka Peta -. Dari Fitur Pemetaan atau dari Website
Klik Tombol Cetak

### Hasil yg diharapkan

Agar Logo Desa, Nama Desa, Nama Kabupaten dan Nama Kecamatan Dapat Tampilkan dan Tercetak di Bagian Legenda Peta

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/64481641/159588667-f4fc87e7-634c-4be1-8ab8-7b090111c085.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Premium (v22.03-rev03)

### Tema Yang Digunakan

default/denatra

### Informasi tambahan

Not

**Comment by andifahruddinakas** [comment]
Pak @Zoel-WB, sy cek di https://berputar.opendesa.id/peta tdk bermasalah.

**Comment by andifahruddinakas** [comment]
Cek di web berputar dan menggunakan tema bawaan

**Comment by Zoel-WB** [comment]
Oke Pak @andifahruddinakas , issue ini saya close dulu->mungkin ada kondisi tertentu di database saya
