### ISSUE TITLE
Bug/error: Statistik umur dibawah 1 tahun

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#5071]
### Jelaskan error yg dialami

cuma pnempatan kalimat yang kurang tepat

pada statistik umur terdapat kalimat bawaan opensid dibawah 1 tahun, sedangkan isian statistik tersebut terdapat isian umur 1 tahun berjalan, sehingga kalimat dibawah 1 tahun kurang tepat,

### Cara untuk mereplikasi errornya

pergi  ke statistik penduduk > pilih umur ( rentang ) > lihat statistik

### Hasil yg diharapkan

kalimat umur dibawah 1 tahun tidak memasukkan data penduduk yang berumur 1 tahun

### Tangkapan layar dan log error

![1648000906-824809-untitled](https://user-images.githubusercontent.com/35319600/159897005-358bd3a5-6fdc-4a25-9157-4e962488cda4.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

rev03

### Tema Yang Digunakan

-

### Informasi tambahan

-

**Comment by balongbesuk** [comment]
https://forum.opendesa.id/d/34-terkait-statistik-umur-dibawah-1-tahun

**Comment by andifahruddinakas** [comment]
Yg dilakukan di PR https://github.com/OpenSID/premium/pull/889 menyesuaikan penamaan dengan rentang 0-1 tahun dengan nama "0 S/D 1 TAHUN".

Untuk mengubah penamaan rentang umur  belum disediakan, yang disediakan hanya perubahan rentang umur. Mas @balongbesuk silahkan dibuat issue permintaan fitur untuk menyesuaikan penamaan rentang umurnya.

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/889
