### ISSUE TITLE
Permintaan fitur: tambah statistik untuk sasaran vaksin

### ISSUE THREAD

**Issue by Wiliyantoro** [OpenSID/OpenSID#5072]
### Apa kekurangan yg ingin diatasi?

belum ada  fitur untuk statisktik terkait berapa jumlah warga yang menjadi sasaran vaksin
vaksin 1
vaksin 2
dan vaksin 3 / booster

### Jelaskan solusi yg diinginkan

agar ditambah statisktik masyarakat yang menjadi / memenuhi syarat sasaran vaksin

### Apakah ada alternatif lain

untuk dosis vaksin 1 = usia 6 tahun keatas / opsional tergantung regulasi pemerintah
untuk dosis vaksin 2 = 14 hari setelah dosis vaksin I
untuk dosis vaksin 3 / booster = 3 bulan (90 hari) setelah dosis ke II ( usia diatas 18 tahun keatas )

### Untuk versi OpenSID mana

v22.03-premium-rev03

### Informasi tambahan

Issue ini juga dibahas pada https://forum.opendesa.id/d/46-filter-data-sasaran-vaksin-booster

**Comment by Zoel-WB** [comment]
Mantap ini, supaya utk dapat memantau sasaran vaksin dari dosis 1 utk vaksin 2 atau wajib harus melakukan vaksin ke-2, begitu juga yg sudah vaksin ke-2 sudah berhak utk mendapatkan vaksin ke 3 atau vaksin boster.

**Comment by Wiliyantoro** [comment]
kalau ada yang perlu disempurnakan mohon dibantu lengkapi isuee ini bang zoel, terimakasih

**Comment by Zoel-WB** [comment]
Itu sudah tersampaikan maksudnya, lainnya sudah ada sama programer..

**Comment by Wiliyantoro** [comment]
https://forum.opendesa.id/d/46-filter-data-sasaran-vaksin-booster

**Comment by andifahruddinakas** [comment]
Tidak dikembangkan lagi
