### ISSUE TITLE
Terjadi error  saat import keuangan

### ISSUE THREAD

**Issue by mranca** [OpenSID/OpenSID#5074]
### Jelaskan error yg dialami

Terjadi error 500

### Cara untuk mereplikasi errornya

Keuangan  > import data

### Hasil yg diharapkan

Di perbaiki

### Tangkapan layar dan log error

![Screenshot_20220325_192952](https://user-images.githubusercontent.com/76085245/160114821-1074c1a4-6960-45fc-9b4d-f53a919e313b.jpg)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

22.03 rev 03

### Tema Yang Digunakan

Silir

### Informasi tambahan

__

**Comment by andifahruddinakas** [comment]
Mas @mranca, silahkan sertakan contoh data yg di impor

**Comment by mranca** [comment]
Saya close saja issuenya sudah saya temukan letak masalahnya
