### ISSUE TITLE
[Lapak] Managemen lapak oleh pengguna di layanan mandiri

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#5075]
### Jelaskan error yg dialami

Saat login Akun Pelapak masih Muncul Akun Tambah Data dan dapat memanggil lapak Pelapak lain untuk menambah, merubah atau menghapus produk pelapak akun lain
  
![image](https://user-images.githubusercontent.com/64481641/160157777-0dcf99b5-4e86-410c-8329-488472030639.png)

![image](https://user-images.githubusercontent.com/64481641/160157908-491dd4d3-6648-4b12-8ceb-5e74ffd847ac.png)

### Cara untuk mereplikasi errornya

1. Buka Menu Pengaturan Pengguna ->Buat Satu Akun Pelapak
2. Lakukan Login Dengan Akun Tersebut 

### Hasil yg diharapkan

Harusnya Untuk Menambah Produk Hanya Boleh Akun yang sedang login, akun lain tidak dapat dipilih oleh Akun yang sedang login.

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/64481641/160158367-ac71be49-cf84-4a39-b158-c7f56d3ca373.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

 Premium (v22.03-rev03)

### Tema Yang Digunakan

Akun Pelapak

### Informasi tambahan

Null

**Comment by ariandii** [comment]
ini bukan bug, melainkan fitur.

karena hak akses yang dibuat tentu berdasarkan group seperti operator, admin, dan group custom lainnya, hanya saja diberi nama Shopping.

jadi bukan khusus mengenai lapak.

buat ajuan fitur saja.

**Comment by Zoel-WB** [comment]
> ini bukan bug, melainkan fitur.
> 
> karena hak akses yang dibuat tentu berdasarkan group seperti operator, admin, dan group custom lainnya, hanya saja diberi nama Shopping.
> 
> jadi bukan khusus mengenai lapak.
> 
> buat ajuan fitur saja.

Bisa jadi Pak karena hak akses-nya bebas, artinya buat akun seperti layanan mandiri pak ya...

**Comment by andifahruddinakas** [comment]
Untuk kasus ini bisa di terapkan di layanan mandiri, dimana pengguna bisa menbuat/mengupload produk mereka sendiri.

**Comment by balongbesuk** [comment]
jangan lupa tambahkan konfirmasi admin boleh tidak produk di publish di web, seperti menu pada komentar

**Comment by ariandii** [comment]
Sebagaimana info bung akas di atas,

melalui Layanan Mandiri, penduduk tersebut bisa upload produknya sendiri.
bukan melalui halaman admin.
