### ISSUE TITLE
Permintaan fitur: Tampilkan umur tahun dan bulan di form KIA

### ISSUE THREAD

**Issue by muhtar-coder** [OpenSID/OpenSID#5076]
### Apa kekurangan yg ingin diatasi?

Saat ini tampilkan data umur hanya terbatas pada hitungan tahun, sehingga ketika tetdapat kebutuhan data umur dengan hitungan umur bulan harus menghitung manual.

### Jelaskan solusi yg diinginkan

Bisa di sediakan pengaturan atau pilihan untuk tampilkan umur tahun dan bulan.

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

22.04 premium

### Informasi tambahan

Umumnya yg paling banyak membutuhkan fitur ini adalah kader posyandu/stunting.

Issue ini juga dibahas pada https://forum.opendesa.id/d/56-tampilkan-umur-tahunbulan-di-pengaturan-rentang-umur

**Comment by yogiperdana** [comment]
Issue perlu ada contoh penggunaan yang kongkrit

**Comment by muhtar-coder** [comment]
Salah satu penggunaan nya bisa terisi otomatis umur bulan

![Screenshot_20220819-074310_Chrome](https://user-images.githubusercontent.com/55665526/185518572-7bd79540-1a02-4550-93a5-b0bcee1c9123.png)

**Comment by yogiperdana** [comment]
> Salah satu penggunaan nya bisa terisi otomatis umur bulan
> 
> ![Screenshot_20220819-074310_Chrome](https://user-images.githubusercontent.com/55665526/185518572-7bd79540-1a02-4550-93a5-b0bcee1c9123.png)

Apakah ada selain hal tersebut pak? Jika tidak artinya judul issuenya bisa diubah sesuai dengan contoh di atas

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1308
