### ISSUE TITLE
Bug/error: BUG? pilihan ketegori pada pengaturan peta tidak bisa di tambah maupun dihapus

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#5077]
### Jelaskan error yg dialami

ketika pengguna ingin menambahkan area garis misal saluran sungai pada pengaturan peta tidak ada menu untuk menambahkan atau menghapus isian kategori yang di maksud

### Cara untuk mereplikasi errornya

pergi ke halaman pemetaan > pengaturan peta > ke menu garis > tambahkan data baru > lihat kategori

### Hasil yg diharapkan

pengguna bisa menambah / mengurangi isian kategori

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/35319600/160224970-928da822-a459-46a0-bdc9-a72c2454ee79.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

rev03

### Tema Yang Digunakan

-

### Informasi tambahan

saya kira menu kategori itu ada di menu tipe garis ternyata menu ini pun gak ada hubungannya dengan isian penambahan data baru

ini terjadi di semua menu pada pengaturan peta

**Comment by andifahruddinakas** [comment]
Pak @balongbesuk, silahkan di tambahkan melalui Tipe Garis pada sub bagian. Saat ini kategori tsb diambil dari sub bagian tipe garis.

**Comment by balongbesuk** [comment]
sudah coba?

**Comment by balongbesuk** [comment]
tipe garisny gak nyambung dengan kategori sudah saya jelaskan d informasi tambahan

**Comment by andifahruddinakas** [comment]
> tipe garisny gak nyambung dengan kategori sudah saya jelaskan d informasi tambahan

Sudah

**Comment by balongbesuk** [comment]
![Screenshot_20220326-181707_Chrome](https://user-images.githubusercontent.com/35319600/160237031-560a4f59-0083-40e9-a8b4-032d23e4b34e.jpg)

isian kategori garis

![Screenshot_20220326-181649_Chrome](https://user-images.githubusercontent.com/35319600/160237035-487abe71-02a6-4cf4-a9c6-51034207d31d.jpg)

isian tipe garis


tuh gak nyambung beda tabel kykny tes d web berputar

**Comment by balongbesuk** [comment]
saya sudah coba tambahkan tipe garis baru jalan berlubang 

![Screenshot_20220326-191428_Chrome](https://user-images.githubusercontent.com/35319600/160239008-73f48190-4996-4f91-b98b-e8d39f4a40b0.jpg)

kemudian saya tambahkan data baru d menu garis, dan pada pilihan menu kategori tidak muncul jalan berlubang

![Screenshot_20220326-191449_Chrome](https://user-images.githubusercontent.com/35319600/160239113-64fa9740-ff02-4773-881e-bf2e910e6a29.jpg)

ap cara saya yang salah? saya tes d website berputar, pak @andifahruddinakas tesny dmn?

**Comment by andifahruddinakas** [comment]
> saya sudah coba tambahkan tipe garis baru jalan berlubang
> 
> ![Screenshot_20220326-191428_Chrome](https://user-images.githubusercontent.com/35319600/160239008-73f48190-4996-4f91-b98b-e8d39f4a40b0.jpg)
> 
> kemudian saya tambahkan data baru d menu garis, dan pada pilihan menu kategori tidak muncul jalan berlubang
> 
> ![Screenshot_20220326-191449_Chrome](https://user-images.githubusercontent.com/35319600/160239113-64fa9740-ff02-4773-881e-bf2e910e6a29.jpg)
> 
> ap cara saya yang salah? saya tes d website berputar, pak @andifahruddinakas tesny dmn?

yg diambil dari sub bagian masing2 kategori tipe garis.

**Comment by balongbesuk** [comment]
siap terimakasih gk ngeh kl ad sub menu dln tipe garis

**Comment by andifahruddinakas** [comment]
> siap terimakasih gk ngeh kl ad sub menu dln tipe garis

Ya, mungkin seharusnya kategori utama bukan sub kategori yg ambil. Tp desain awalnya begitu, jika ada perubahan bisa dibuat issuenya dan bisa di diskusikan mengenai hal ini.
