### ISSUE TITLE
Terjadi bug saat menganti nama wilayah adminitratif

### ISSUE THREAD

**Issue by mranca** [OpenSID/OpenSID#5078]
### Jelaskan error yg dialami

Terjadi error 404

### Cara untuk mereplikasi errornya

Dashboard > admin web > menu > data desa > data wilayah administratif

### Hasil yg diharapkan

Saat di ganti dari data wilayah administratif menjadi data perdusun dan memilih external dan memasukkan link misalnya https://tongkekongke.desa.id/data-wilayah maka eror

### Tangkapan layar dan log error

![Screenshot_20220326_151208](https://user-images.githubusercontent.com/76085245/160229581-76ccf978-63a9-4547-8d49-69e9cc5a321a.jpg)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

22.03 rev 03

### Tema Yang Digunakan

Silir

### Informasi tambahan

__

**Comment by ariandii** [comment]
ekternal itu untuk menuju ke link yang sudah tersedia. link tujuannya ada.

sedangkan link /data-wilayah jika tidak ada di menu, tentu tidak akan tersedia.

jadi membuat menu eksternal menjadi link tujuan yang belum dibuat menu nya maka akan error 404.

ini bukan bug.

**Comment by mranca** [comment]
Jadi pak ariandi, mohon solusinya untuk menampilkan kembali ??
