### ISSUE TITLE
Bug/error: Perbaikan Link pada halaman Periksa

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#5079]
### Jelaskan error yg dialami

<img width="960" alt="image" src="https://user-images.githubusercontent.com/46939846/160240867-84839cb8-81e7-4d96-a414-ea4af8ef6ce5.png">

Ketika klik tombol OpenSID di pojok kiri halaman periksa, ternyata diarahkan ke /index2.html seperti gambar di atas. 

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

Normal sebagaimana harusnya, misal masuk halaman admin atau web publik

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

22.03-premium

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui commit https://github.com/OpenSID/premium/commit/848a5e672443530df2b6a24fc868ad076350104d
