### ISSUE TITLE
Penambahan icon potret Kamera,buat kebutuhan live camera 

### ISSUE THREAD

**Issue by anwargopro** [OpenSID/OpenSID#508]

**Comment by metalab25** [comment]
Maksudnya apa ini ?

**Comment by MUHAMMADRANGSEL** [comment]
Maksunya mungkin di menu penduduk ada poto untuk penduduk

**Comment by andanwar** [comment]
Iya mas jd ada dua icon , yg 1 kan udah ada browser foyo yv satu lagi capture live via hardware camera on

**Comment by MUHAMMADRANGSEL** [comment]
Memang untuk mendukung aplikasi OpenSID ini perlu sehgg kamera stanby dikantor dan ketika ada masyarakat yg dtg pelayanan sambil dipoto

**Comment by MUHAMMADRANGSEL** [comment]
Semoga programer bisa sgr mengerjqkqnnyq

**Comment by afa28** [comment]
Duplicate
