### ISSUE TITLE
Bug/error: Perjelas Status Kehadiran

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#5081]
### Jelaskan error yg dialami

Sudah praktek di Web Berputar mengenai Fitur Kehadiran.

Saat ini hanya bisa lakukan 1 kali hadir dan 1 kali keluar.

Jika fungsi ini mengutamakan mengenai status Keberadaan Pamong di Desa, tentunya bisa lakukan Hadir dan Keluar berulangkali.

Contoh:
1. Pamong A Lakukan Presensi, dan Muncul Keterangan Hadir di Widget Web
2. Pamong A Keluar kantor jam 10, maka Status Hadir di Widget tidak berlaku. (Jika si A lakukan Absen Keluar, seharusnya widget di Web akan Hilang mengenai status Hadirnya).
3. Pamong A jam 11 Hadir di kantor desa lagi dan lakukan Presensi, maka status widget akan muncul Hadir.

Hal ini menghindari gagal pengertian bagi warga yang melihat status Hadir di web tetapi kondisi Pamong sedang Keluar atau Dinas Luar dalam waktu beberapa jam.

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

Sesuaikan tujuan utama adanya Fitur ini, apakah hanya buat Masuk dan Keluar 1 kali saja.

atau

Bisa Masuk dan keluar berkali kali.

Begitu juga dengan Status yang muncul di Widget Aparatur Desa. Harusnya sesuai dengan keberadaaan Pamong tersebut.

Bisa saja Pamong setelah lakukan Presensi jam 8 lalu jam 10 Ijin Ke Kecamatan, tetapi di widget amsih berstatus Hadir.
Lalu Bisa saja Pamong Kembali ke kantor jam 12, di widget bisa diperbaharui setelah lakukan Presensi kembali.

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Berputar

**Comment by Zoel-WB** [comment]
Atau lebih cendrung untuk Absensi kehadiran di Kantor Desa semacam geser pamplet nama perangkat desa->siapa saja yg ada atau tidak ada, karena Absensi Digital saat ini agak rumit->karena login hadir hanya satu kali saja ditanggal yg sama->setelah login keluar/pulang  sebelum jam pulang kerja pada tanggal yg sama, tidak bisa masuk lagi.

**Comment by ariandii** [comment]
dari situ lah adanya issue ini agar bisa masuk keluar tidak dibatasi 1x saja.

**Comment by yogiperdana** [comment]
Yang di tema belum digabung mas @andifahruddinakas

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/900
