### ISSUE TITLE
Bug/error: error console ketika login

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#5082]
### Jelaskan error yg dialami

terjadi eror console ketika pengguna login ke menu admin

### Cara untuk mereplikasi errornya

buka website berputar login lihat error console pada browser

### Hasil yg diharapkan

tidak ada error

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/35319600/160266424-4fcb0d54-2650-4a5b-a273-a54f786a8c40.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

website berputar

### Tema Yang Digunakan

-

### Informasi tambahan

-

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki.
