### ISSUE TITLE
Bug/error: error console pada menu layanan mandiri

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#5083]
### Jelaskan error yg dialami

muncul error console pada web layanan mandiri

### Cara untuk mereplikasi errornya

buka web berputar pilih menu layanan mandiri lihat error console

### Hasil yg diharapkan

tidak terjadi error

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/35319600/160266490-6dbd8ebd-ee57-41ef-b243-9fd870a79d7d.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

-

### Tema Yang Digunakan

-

### Informasi tambahan

-

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/890
