### ISSUE TITLE
Bug/error: error console pada dasboard layanan mandiri

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#5084]
### Jelaskan error yg dialami

ketika pengguna layanan mandiri login dan di arahkan pada dasboard layanan mandiri muncul error console

### Cara untuk mereplikasi errornya

buka layanan mandiri login lihat error console

### Hasil yg diharapkan

tidak ada error

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/35319600/160266668-6234c820-caa6-4eac-a94a-1d4eba32b028.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

website berputar

### Tema Yang Digunakan

-

### Informasi tambahan

-

**Comment by andifahruddinakas** [comment]
Error console akan diperbaiki scr bertahap menggunakan view blade. krn saat ini assets di load scr bersamaan dimana tdk semua komponen assets itu digunakan yg menyebabkan error. Misalnya assets peta, datatables, script.js, dll yg.

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/887
