### ISSUE TITLE
Fitur: Tambah Kolom Lupa Password

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#5085]
### Jelaskan error yg dialami

Saat klik alamat:
https://berputar.opendesa.id/siteman/lupa_sandi

hanya tersedia kolom email saja.

bisa ditambah kolom captcha. atau lainnya agar ada proses verifikasi sebelum proses kirim lupa password

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Berputar

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/1037
