### ISSUE TITLE
[Premium V22.03-Beta01] Nama Perangkat Desa Yang Tampil Dipilihan pada Fitur Kehadiran Masih Ada Nama Perangkat Desa Default 

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#5087]
### Jelaskan error yg dialami

Saat Membuka Fitur Absensi Pilihan Kehadiran Masih menampilkan nama-nama perangkat desa default diantaranya Nama Kepala Desa (MUHAMMAD ILHAM), Nama Sekretaris Desa (MUSTAHID S.Amd), Nama Kaur Pemerintahan (Safruddin), dana Nama Kaur Keuangan (MARDIANA) Bukan nama-nama perangkat desa yang ditentukan  atau dipilih dalam system pada fitur Buku Aparatur Desa. Mungkin ini ada kaitannya dengan Isian atau input Tambah Data Staff Pemerintahan Desa antara Pilihan (Dari Database Penduduk dan Tidak Terdata)

### Cara untuk mereplikasi errornya

1. Buka Menu Absensi
2. Pilih Fitur Kehadiran
3. Dalam Daftar Hadir Klik Dropdown "Perangkat Desa"

### Hasil yg diharapkan

Hanya menampilkan list perangkat desa sebagaimana yang ditentukan dalam Buku Aparatur Desa

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/64481641/160279791-7e2fdac9-9b05-4b97-a07a-65aa058ba350.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

OpenSID (v22.04-premium)

### Tema Yang Digunakan

Halaman Admin

### Informasi tambahan

.

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui commit https://github.com/OpenSID/premium/pull/888/commits/e8519ebf3e33bb46dd35867de3297f4ba2311fae
