### ISSUE TITLE
Login Absensi atau Anjungan Bersatu dengan Login Admin

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#5089]
### Jelaskan error yg dialami

Antara Login Absensi dan Login Admin terjadi dalam satu login, artinya Login Absen akan sama-sama mengikuti login Admin, Bila Login Absensi Keluar, baik Keluar Secara Manual, maupun keluar dengan waktu otomatis, login pada system (Admin) juga ikut keluar....

### Cara untuk mereplikasi errornya

1. Jalankan Login Admin Opensid...
2. Jadikan Satu Orang Perangkat Desa Untuk Login Absen (Otomatis Login Admin berubah menjadi Admin yang Login di Absen)
3. Setelah Perangkat Desa yang Login Absen Klik Hadir dan Keluar (Login Pada Admin Juga Ikut Keluar LogOut)

### Hasil yg diharapkan

Agar login absen terpisah tersendiri dari login admin sehingga tidak mempengaruhi Login Admin, seperti layaknya Login Layanan Mandiri. 

### Tangkapan layar dan log error

.

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

OpenSID v22.04-premium

### Tema Yang Digunakan

Halaman Admin dan Login Absensi

### Informasi tambahan

.

**Comment by eddieridwan** [comment]
@Zoel-WB @yogiperdana , perhatikan. bahwa Rekam Kehadiran dimaksudkan untuk dijalankan pada gawai yg hanya itu saja fungsinya. Misalnya, dijalankan pada gawai tablet/HP yg ditempelkan di dinding masuk kamar utama ruang perangkat desa di kantor desa. Yaitu, tidak ada fungsi lain yg dijalankan di gawai tersebut. 

Jadi, tidak diinginkan adanya login Admin lain yg terbuka terus di gawai Rekam Kehadiran, karena gawai tersebut akan digunakan oleh setiap perangkat desa yg datang untuk merekam kehadiran mereka. Yaitu, di gawai tersebut, seharusnya hanya ada satu pengguna aktif setiap saat. 

Yaitu, cara sekarang sudah betul, dan issue ini bisa ditutup. @yogiperdana @andifahruddinakas , mohon info ini ditambahkan ke panduan.
