### ISSUE TITLE
Bug/error: Status Kehadiran Tidak Aktif

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#5090]
### Jelaskan error yg dialami

Status pada Pengaturan Kehadiran menjadi tidak aktif saat di edit Lalu simpan.

### Cara untuk mereplikasi errornya

1. Pergi ke halaman https://berputar.opendesa.id/gawai
2. Klik tombol Aksi Edit pada Status Aktif
3. Edit kolom IP, Mac, maupun Keterangan, Lalu simpan
4. Lihat status terbaru menjadi Tidak Aktif.

### Hasil yg diharapkan

Karena hanya lakukan edit pada kolom tersedia,
seharusnya status tetap seperti semula, jika pilihan aktif/tidak aktif tidak ada yang dipilih saat edit.

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Berputar

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui commit https://github.com/OpenSID/premium/pull/888/commits/506abc679ca572456ca14a0fdecc49dd464caf85
