### ISSUE TITLE
Tambahkan fitur bersihkan pada bantuan / daftar peserta bantuan

### ISSUE THREAD

**Issue by mranca** [OpenSID/OpenSID#5091]
### Apa kekurangan yg ingin diatasi?

Kurangnya tombol bersihkan saat pencarian bantuan sehingga mengharuskan menghapus data pencarian terlebih dahulu 

### Jelaskan solusi yg diinginkan

Tambahakan tombol bersihkan seperti gambar 
![IMG_20220328_130803](https://user-images.githubusercontent.com/76085245/160330105-b3375493-42e9-4385-a4de-381c1c3f8254.jpg)

### Apakah ada alternatif lain

Tidak ada

### Untuk versi OpenSID mana

22.04

### Informasi tambahan

---

**Comment by agungsugiarto** [comment]
Sudah masuk ke fitur premium melalui prhttps://github.com/OpenSID/premium/pull/919
