### ISSUE TITLE
Bug/error: 

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#5092]
### Jelaskan error yg dialami

Klik Kolom Pelapor maupun Kolom Terlapor, maka akan muncul error seperti gambar di bawah ini

<img width="960" alt="screenshot_24" src="https://user-images.githubusercontent.com/46939846/160330073-565e331d-3f39-45ff-8001-01d212a918fa.png">

Klik Kolom Nama maupun Kolom Jabatan, maka akan muncul error seperti gambar di bawah ini

<img width="960" alt="screenshot_25" src="https://user-images.githubusercontent.com/46939846/160330320-b12f1a3a-9122-4e4c-ab60-a076c0ed9aac.png">

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

Normal

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Berputar

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/894
