### ISSUE TITLE
Permintaan fitur: Otomatis Beri Tanda Hosting OpenDesa

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#5094]
### Apa kekurangan yg ingin diatasi?

Perlu ada cara otomatis setelah pasang Token Langganan Hosting OpenDesa sebagai pengganti folder mitra yang saat ini dilakukan secara manual.

Agar muncul banner di bagian footer.

### Jelaskan solusi yg diinginkan

Bisa saja dibuat untuk setiap Layanan, baik Hosting maupun Domain, agar ketika input token maka otomatis muncul banner di footer yang menjadi ciri bahwa telah berHosting di OpenDesa.

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

Semua

**Comment by andifahruddinakas** [comment]
Sama dengan issue https://github.com/OpenSID/OpenSID/issues/5098, perlu ditambahkan info pada API pelanggan untuk data kategorinya agar lebih mudah membandingkan. Krn jika dibandingkan perlayanan, perlu di daftarkan layanan domain/hosting tsb, misalnya Hosting 1gb, Hosting 2gb, dll.

Bisa sj diakali dengan prag_match(), tp untuk lebih efisien lebih baik datanya disediakan di API.
