### ISSUE TITLE
Permintaan fitur: Tambahkan penanda KK sementara pada tabel keluarga 

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#5095]
### Apa kekurangan yg ingin diatasi?

Tambahkan penanda KK sementara pada tabel keluarga seperti pada NIK Sementara Pada tabel penduduk

### Jelaskan solusi yg diinginkan

beri penanda KK Sementara Seperti Pada NIK Sementara pada tabel penduduk

### Apakah ada alternatif lain

tidak ada penanda KK semetara pada tabel keluarga sebagai penanda KK tersebut  belum memiliki No KK resmi

### Untuk versi OpenSID mana

Premium

### Informasi tambahan

-

**Comment by agungsugiarto** [comment]
Sudah masuk ke fitur premium melalui pr https://github.com/OpenSID/premium/pull/918
