### ISSUE TITLE
Bug/error: Surat Ubahan Desa Ketika dibuat tersedia untuk layanan mandiri mengalami bug

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#5099]
### Jelaskan error yg dialami

Surat Ubahan Desa Ketika dibuat tersedia untuk layanan mandiri mengalami bug file.php surat tidak muncul

### Cara untuk mereplikasi errornya

layanan surat > pengaturan surat > ubah surat desa  > Sediakan di Layanan Mandiri > YA > simpan > cetak surat > blank putih terlihat dari pengaturan surat file rtf surat hilang / surat desa meminta untuk meng unggah file.rtf kembali

### Hasil yg diharapkan

berjalan lancar

### Tangkapan layar dan log error

![Untitled](https://user-images.githubusercontent.com/35319600/160739888-966ff443-ab3c-44c2-900a-ede2b1f9642f.png)

![image](https://user-images.githubusercontent.com/35319600/160739895-25224701-658a-418c-937d-6a87e7c8860e.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

website berputar

### Tema Yang Digunakan

-

### Informasi tambahan

ada kemungkinan ketika surat desa pada sistem di rubah tersedia untuk layanan mandiri folder / file surat dirubah oleh sistem sehingga ketika surat dibuat menjadi blank putih

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/904
