### ISSUE TITLE
Bug/error: Anggota Kelompok Belum Tampil di Web

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#5100]
### Jelaskan error yg dialami

Ketika data kelompok berisikan anggota. maka untuk tabel anggota di web masih kosong.

### Cara untuk mereplikasi errornya

Seperti gambar di bawah

### Hasil yg diharapkan

Muncul Normal

### Tangkapan layar dan log error

Di admin sudah ada anggota:

<img width="960" alt="screenshot_104" src="https://user-images.githubusercontent.com/46939846/160844623-4a83b21c-118b-407a-9f7f-a189ee1586ff.png">

Di web kosong

<img width="529" alt="screenshot_105" src="https://user-images.githubusercontent.com/46939846/160844637-2f75827f-dfdc-4d28-a3db-6a4663e50760.png">

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Semua

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/906
