### ISSUE TITLE
Bug/error: Gambar Latar Website Pada Menu Pengaturan > Aplikasi Hanya Bisa Diganti Sekali

### ISSUE THREAD

**Issue by dikisiswanto** [OpenSID/OpenSID#5101]
### Jelaskan error yg dialami

Gambar latar website hanya bisa diganti sekali dari gambar defaultnya. Setelah coba diganti untuk kedua kali dst, status sukses disimpan tetapi gambar tidak berubah.

### Cara untuk mereplikasi errornya

- Buka `Pengaturan > Aplikasi`
- Upload gambar `Latar Website` untuk mengganti gambar default
- Klik Simpan
- Coba ulangi upload gambar lain
- Simpan
- Cek apakah gambar terganti dengan yang baru

### Hasil yg diharapkan

Bisa diubah berkali-kali

### Tangkapan layar dan log error

Sudah dites di website berputar.opendesa.id

### Rilis Versi OpenSID

Rilis Umum

### Versi OpenSID

v22.03

**Comment by agungsugiarto** [comment]
Duplikat https://github.com/OpenSID/OpenSID/issues/4731, di versi premium sudah diperbaiki akan digabungkan di rilis umum sesuai [rilis umum yang akan datang](https://github.com/OpenSID/OpenSID/wiki/Rilis-Umum-Yang-Akan-Datang#rilis-umum-v2209--2202-premium)

**Comment by dikisiswanto** [comment]
Mas @agungsugiarto  Issue #4731 terkait latar website tema tidak terganti meskipun ada gambar baru. 

Yang ini di adminnya cuma bisa diganti sekali, upload berikutnya tidak berubah meskipun berhasil simpan. 

Apakah memang hanya bisa diganti sekali?

**Comment by dikisiswanto** [comment]
upload pertama
<img width="767" alt="image" src="https://user-images.githubusercontent.com/22239074/160970291-3ecfdd1f-4277-4a3a-85d5-9d358f71c9f6.png">

**Mau ganti gambar**
<img width="574" alt="image" src="https://user-images.githubusercontent.com/22239074/160970344-52d06110-169c-46ac-bb08-134814cdad0a.png">

**Setelah diunggah**
<img width="742" alt="image" src="https://user-images.githubusercontent.com/22239074/160970539-616a9845-3247-4d8b-a26f-bd79f5f0846e.png">

**Comment by agungsugiarto** [comment]
coba diberputar mas versi premium, apakah menemukan masalah yg sama?

**Comment by dikisiswanto** [comment]
Itu dicek di berputar mas. Silakan coba direplikasi.

**Comment by andifahruddinakas** [comment]
Gambarnya sudah terganti di folder desa/pengaturan/nama_tema/images/latar_website.jpg tp di halaman website perlu di hapus cache. Sudah di perbaiki di versi bulan ini tp ada helper version yg sudah dihapus tp belum disesuaikan ulang untuk perubahan sebelumnya.
