### ISSUE TITLE
[v22.04-Umum] Bug Letak Tombol Unduh Fitur Baru Buku Rencana Kerja Pembangunan 

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#5105]
### Jelaskan error yg dialami

Tombol Unduh Fitur Baru Buku Rencana Pembangunan Terpasang di Baris Kedua di Bawah Tombol Cetak harus sejajar sebelah Kanan Tombol Cetak

### Cara untuk mereplikasi errornya

1. Buka Buku Administrasi Desa
2. Buku Administrasi Pembangunan
3. Buku Rencana Kerja Pembangunan

### Hasil yg diharapkan

Tombol Unduh Mestinya Terletah di Sebelah Kanan atau Kiri sejajar dengan Tombol Cetak

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/64481641/161329330-30c9d0f7-a1f2-43b4-8c50-37aacb9899cc.png)

### Rilis Versi OpenSID

Rilis Umum

### Versi OpenSID

OpenSID v22.04

### Tema Yang Digunakan

Halaman Admin

### Informasi tambahan

.

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki fi premium selanjutnya.
