### ISSUE TITLE
Perbaiki deteksi MAC Address Gawai Kehadiran

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#5106]
### Apa kekurangan yg ingin diatasi?

saat ini halaman kehadiran hanya mendeteksi IP perangkat walaupun sudah di isi MAC addressnya dan mengosongkan IP / Ip local, halaman perangkat masih tidak terdaftar

### Jelaskan solusi yg diinginkan

daftarkan perangkat kehadiran cukup menggunakan MAC address karena sifatnya statis sedangkan IP sifatnya dinamis tidak bisa dijadikan acuan

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

premium

### Informasi tambahan

-

**Comment by ariandii** [comment]
Saya bisa pakai MAC dan sukses lakukan presensi di beberapa desa, walaupun kolom IP nya dikosongkan

**Comment by andifahruddinakas** [comment]
Bisa menggunakan salah satunya sama seperti anjungan layanan mandiri.

**Comment by Zoel-WB** [comment]
Kalau Mungkin untuk Deteksi IP bisa langsung otomatis di deteksi oleh Gawai, mengingat IP bila menggunakan Jaringan Hospot sering sekali berubah-ubah setiap hostpot di matikan/dinonaktikan atau bahkan akibat gangguan PLN bila listrik tiba-tiba blank/padam.

 
![image](https://user-images.githubusercontent.com/64481641/161434542-cf6dbfd8-4915-4d4a-991c-b660e3d76e45.png)

**Comment by balongbesuk** [comment]
kalau bisa semua ya sudah saya close,

jika masih terkendala silakan buat isue baru bagi pengguna yang sudah menerapkan fitur ini

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melalui pr https://github.com/OpenSID/premium/pull/953

**Comment by andifahruddinakas** [comment]
Mas @yogiperdana

**Comment by yogiperdana** [comment]
oke mas

**Comment by yogiperdana** [comment]
Issue ini di close karena mac address sudah bisa berfungsi sebagaimana mestinya

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melalui pr https://github.com/OpenSID/premium/pull/1010
