### ISSUE TITLE
Bug/error: Menu bantuan yg non aktif masih muncul di web artikel insert data bantuan

### ISSUE THREAD

**Issue by muhtar-coder** [OpenSID/OpenSID#5107]
### Jelaskan error yg dialami

Data bantuan yg non aktif masih bisa muncul di web artikel insert data penerima bantuan

### Cara untuk mereplikasi errornya

1. Masuk menu bantuan di halaman admin lalu non aktifkan semua rentang waktu penerimaan.
2. Buat artikel dan sisipkan data penerima bantuan.
3. Buka halaman web  dan ternyata masih ter tera data bantuan yang sudah tidak aktif tsb.

### Hasil yg diharapkan

Idealnya data bantuan yg sudah tidak aktif tidak lagi muncul di halaman web

### Hasil tangkapan layar
![Screenshot_20220402-170306_Chrome](https://user-images.githubusercontent.com/55665526/161379451-1da190bb-35a3-46cd-af40-4ccc2c538f2e.png)

![Screenshot_20220402-170306_Chrome](https://user-images.githubusercontent.com/55665526/161379230-106f0261-f819-4a4c-8b37-4bbde56ed33b.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

22.04 premium

### Tema Yang Digunakan

Denatra

### Informasi tambahan

Untuk insert data bantuan dihalaman website  ideal nya hanya jenis bantuan tertentu saja sesuai judul artikel /maksud informasi jenis bantuan mana yg akan di sisipkan sebagai informasi terkait jenis bantuan tersebut

Misal:
Dibuat judul penyaluran BLT DD tahun 2022, maka sisipan data bantuan spesifik menguraikan daftar nama penerima BLT DD tahun tersebut dan hanya jenis bantuan tsb.

**Comment by agungsugiarto** [comment]
Pak @muhtar-coder issue ini saya close, lihat pembahasan di https://github.com/OpenSID/OpenSID/issues/5000

**Comment by muhtar-coder** [comment]
SIAP...

Pada tanggal Sen, 4 Apr 2022 pukul 13.29 Agung Sugiarto <
***@***.***> menulis:
