### ISSUE TITLE
Buat template surat keterangan menggunakan TinyMCE

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#5108]
Buat template surat menggunakan TinyMCE, tidak lagi RTF. Supaya menggunakan HTML dan bisa diatur langsung melalui PHP. Manfaatnya misalnya: memudahkan desa membuat surat sendiri, lebih mudah menyisipkan QR Code dll, bisa cari library untuk mengatur layout halaman, dstnya

Ini pekerjaan besar dan perlu dipecah menjadi tugas-tugas yg lebih kecil.

**Comment by andifahruddinakas** [comment]
Cari referensi aplikasi yang menggunakan cara ini untuk membuat surat.

Yang diperlukan : 
1. ERD (https://dbdiagram.io/d/6257755b2514c97903299120)
2. Pengaturan Header, Footer atau Lainnya disimpan di tabel setting_aplikasi.
3. Buat di Modul Baru / Menggunakan Modul lama dengan penyesuaian tabel (tambahkan kolom 'template').
4. History surat baru degan TinyMCE perlu sinkron dengan surat lama yang menggunakan RTF
5. Surat yang dihasilkan adalah pdf

**Comment by andifahruddinakas** [comment]
Cari referensi aplikasi yang menggunakan cara ini untuk membuat surat.

**Comment by Pematung** [comment]
Saran saya harus ada 2 opsi surat yang dihasilkan
1. dalam bentuk rtf (word)
2. Pdf
untuk menjaga kemungkinan salah entri lalu sipembuat surat dan pemohon bisa untuk melakukan edit atau penyesuaian.

**Comment by mranca** [comment]
Usahakan tetap bisa di donwload dalam bentuk word,supaya bisa memudahkan pengeditan jika terjadi kesalahan tanpa harus buat baru lagi

**Comment by eddieridwan** [comment]
@Pematung @mranca : fitur ini `tidak` akan menyediakan surat tercetak dalam bentuk RTF atau Word. Surat yg dicetak `tidak` bisa diubah. 

Tetapi nantinya akan disediakan fitur untuk bisa mengubah isian suratnya (tanpa harus buat baru lagi), sebelum difinalkan. Yaitu, surat bisa dicetak/di-preview dan form isiannya diperbaiki berulang-ulang sebelum difinalkan. Setelah difinalkan, surat tersebut tidak dapat diubah lagi.

**Comment by Pematung** [comment]
> @Pematung @mranca : fitur ini `tidak` akan menyediakan surat tercetak dalam bentuk RTF atau Word. Surat yg dicetak `tidak` bisa diubah.
> 
> Tetapi nantinya akan disediakan fitur untuk bisa mengubah isian suratnya (tanpa harus buat baru lagi), sebelum difinalkan. Yaitu, surat bisa dicetak/di-preview dan form isiannya diperbaiki berulang-ulang sebelum difinalkan. Setelah difinalkan, surat tersebut tidak dapat diubah lagi.

OK OpenSID selalu memberikan solusi terbaik

**Comment by mranca** [comment]
> @Pematung @mranca : fitur ini `tidak` akan menyediakan surat tercetak dalam bentuk RTF atau Word. Surat yg dicetak `tidak` bisa diubah. 
> 
> Tetapi nantinya akan disediakan fitur untuk bisa mengubah isian suratnya (tanpa harus buat baru lagi), sebelum difinalkan. Yaitu, surat bisa dicetak/di-preview dan form isiannya diperbaiki berulang-ulang sebelum difinalkan. Setelah difinalkan, surat tersebut tidak dapat diubah lagi. 

Baik pak, opensid selalu yang terbaik,

**Comment by andifahruddinakas** [comment]
Cek :
1. Layanan Mandiri.
2. API OpenSID.
3. Cek ulang fungsi surat lama.
