### ISSUE TITLE
Bug/error: Ekspor Rekapitulasi Tidak Bisa Digunakan

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#5109]
### Jelaskan error yg dialami

Saat mau melakukan ekspor data rekapitulasi kehadiran, fitur ekspor tidak berjalan.

### Cara untuk mereplikasi errornya

Masuk ke modul
1. Kehadiran > rekapitulasi
2. Lakukan ekspor

### Hasil yg diharapkan

Dapat melakukan ekspor rekapitulasi

### Tangkapan layar dan log error

.

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.04

### Tema Yang Digunakan

bawaan

### Informasi tambahan

Perubahan dari penggunaan kata export ke ekspor tidak diubah pada bagian route view untuk ekspor

**Comment by ariandii** [comment]
Apakah di bawah ini issues terpisah atau jadi satu dengan Rekapitulasi Tidak bisa digunakan di issues ini?

Waktu terekam 00:00
Yang berarti Staf Desa bisa lakukan hadir dan keluar dalam waktu singkat.
(baik itu sengaja maupun tidak sengaja login 2 kali untuk memastikan bahwa sudah lakukan presensi)

<img width="960" alt="image" src="https://user-images.githubusercontent.com/46939846/161417372-82e129ee-26c2-48e4-9a19-d075d24d1883.png">

**Comment by ariandii** [comment]
Bisa dibuat Jeda Waktu misal 1 menit setelah Hadir, tidak bisa Keluar

**Comment by andifahruddinakas** [comment]
> Apakah di bawah ini issues terpisah atau jadi satu dengan Rekapitulasi Tidak bisa digunakan di issues ini?
> 
> Waktu terekam 00:00 Yang berarti Staf Desa bisa lakukan hadir dan keluar dalam waktu singkat. (baik itu sengaja maupun tidak sengaja login 2 kali untuk memastikan bahwa sudah lakukan presensi)
> 
> <img alt="image" width="960" src="https://user-images.githubusercontent.com/46939846/161417372-82e129ee-26c2-48e4-9a19-d075d24d1883.png">

dibuat issue terpisah.
