### ISSUE TITLE
Bug/error: Gagal Tambah Pengguna

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#5110]
### Jelaskan error yg dialami

Error 500,
selengkapnya di video bawah ini:

**1. Video Input Baru**

https://user-images.githubusercontent.com/46939846/161417165-8622bac4-5163-4ce4-be2a-022371a9bba6.mp4

**2. Video Edit Data yang Ada.**

https://user-images.githubusercontent.com/46939846/161417254-a9b2ea03-fa36-415e-a5c0-6becaef5a817.mp4

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

Normal walau belum menentukan Data Staf.
Karena tidak semua Pengguna adalah Staf Desa, ada kemungkinan pihak luar yang diberi akses data seperti redaksi, penginput, dll yang tanpa perlu Rekam Kehadiran.

### Tangkapan layar dan log error

Video di atas

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Berputar

**Comment by andifahruddinakas** [comment]
Coba disertakana log error nya.

**Comment by Zoel-WB** [comment]
Ini memang ya ada yg trouble disini, belum sempat saya kupas kemaren disini.

Terutama absensi perangkat yg merangkap sebagai admin sempat tidak dapat melakukan login absensi.

Satu lagi login e-KTP masih belum bisa, ini yg baru saya coba utuk perangkat yg merangkap juga sebagai admin.

**Comment by ariandii** [comment]
Log bisa cek di
https://berputar.opendesa.id/info_sistem

atau gambar berikut
![IMG_20220403_201224](https://user-images.githubusercontent.com/46939846/161429836-72583cc5-fe14-4529-b1ec-8ac20ed36d60.jpg)

**Comment by Zoel-WB** [comment]
Iya saya sempat 3 kali merestore ulang database, disinilah kejadiannya kmaren, Krn setelah memasukkan operator dgn nama perangkat atau nomor nik ternyata utk perangkat tersebut tidak bisa lagi login di absen. Apakah usernamenya memang TDK dapat menggunakan nomor nik.

Sedangkan di login absensi dapat dilakukan dengan 2 cara, menggunakan nama atau nik.

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/914
