### ISSUE TITLE
Bug/error: Ada Kala Jam Kerja Ganda

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#5111]
### Jelaskan error yg dialami

Saat update ke 22.04-premium, terkadang di data desa tercipta Hadi Senin, Selasa sampai minggu Ganda.
Bahkan ada yang sampai 3 kali. Hingga total baris ada 27 Hari.

Jika ada hari yang sama, maka ubah Jam Kerja tidak akan berpengaruh jika semua di 1 Nama Hari yg sama diubah juga.

<img width="960" alt="image" src="https://user-images.githubusercontent.com/46939846/161417808-fab6cba2-48b9-46fd-afbb-09f155898517.png">

### Cara untuk mereplikasi errornya

Tidak bisa direplikasi, karena terjadi tidak tentu.
ada yang sukses 7 hari saja,

ada juga yang kembar bisa sampai 14 hari bahkan 27 hari.

### Hasil yg diharapkan

Hanya Batasi 7 Hari saja.

### Tangkapan layar dan log error

di atas

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Berputar

**Comment by andifahruddinakas** [comment]
Setelah saya cek ulang di lakukan ujicoba, bugs ini tidak bisa di replikasi. Karena penambahan data hanya dilakukan saat pertama kali buat tabel. Maka akan dibuat tabel beserta datanya. Jika migrasi di ulangi terus menerus data tidak akan bertambah.

Issue ini saya tutup, jika masih bermasalah. Bisa duplikasi ke website https://berputar.opendesa.id/).

**Comment by andifahruddinakas** [comment]
Pak @ariandii, @yogiperdana atau nama hari dibuat unik agar hanya ada 1 saja. Dimana seharusnya hanya ada 7 nama hari dan tidak mungkin bertambah dan sama.
