### ISSUE TITLE
Bug/error: Bisa dibuat Jeda Waktu Presensi

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#5113]
### Jelaskan error yg dialami

Waktu terekam 00:00
Yang berarti Staf Desa bisa lakukan hadir dan keluar dalam waktu singkat.
(baik itu sengaja maupun tidak sengaja login 2 kali untuk memastikan bahwa sudah lakukan presensi)

Bisa dibuat Jeda Waktu misal 1 menit atau lebih setelah Hadir, tidak bisa Keluar untuk akun yang sama.

<img width="960" alt="161417372-82e129ee-26c2-48e4-9a19-d075d24d1883" src="https://user-images.githubusercontent.com/46939846/161429950-f4e3e7b3-5938-4181-9e8b-0f1a26ac9578.png">

### Cara untuk mereplikasi errornya

seperti di atas

### Hasil yg diharapkan

Bisa dibuat Jeda Waktu misal 1 menit atau lebih setelah Hadir, tidak bisa Keluar dengan akun yang sama

### Tangkapan layar dan log error

di atas

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Berputar

**Comment by yogiperdana** [comment]
Berdasarkan hasil diskusi. Waktu untuk masuk dan keluar tidak dibatasi. Namun jika waktu keluar kurang dari 1 menit waktu masuk maka akan ada konfirmasi apakah tetap ingin keluar atau tidak

**Comment by agungsugiarto** [comment]
Tambahkan konfirmasi keluar melalui pr https://github.com/OpenSID/premium/pull/965
