### ISSUE TITLE
[V22.04-PREMIUM] Rekapitulasi Kehadiran->List Perangkat Desa->Terdapat Nama Perangkat Desa Bawaan System, 

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#5115]
### Jelaskan error yg dialami

Rekapitulasi Kehadiran->List Perangkat Desa->Terdapat Nama Perangkat Desa Bawaan System, dimana nama perangkat tersebut bukan dari Perangkat Desa yg mengunakan OpenSID

### Cara untuk mereplikasi errornya

1. Buka Menu Kehadiran
2. Buka Fitur Rekapitulasi
3. Pada Daftar Rekapitulasi Klik List Perangkat Desa

### Hasil yg diharapkan

Agar Tidak Menampilkan Nama Perangkat Desa Lain yang bukan perangkat desa yg terpilih di desa, atau tidak lagi menampilkan nama Perangkat Contoh dari System.

### Tangkapan layar dan log error

Muhammad Ilham
Mustahiq, A. Amd
Syafaruddin
Mardiana 
Nama-Nama Perangkat Desa Tersebut Bukan Nama Perangkat Desa yg terpilih dalam system
![image](https://user-images.githubusercontent.com/64481641/161433265-37217b1a-0d91-47a6-9065-18835e1a4763.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

V22.04-Premium

### Tema Yang Digunakan

Halaman Admin

### Informasi tambahan

.

**Comment by andifahruddinakas** [comment]
Silahkan di nonaktifkan dan keluarkan daei kehadiran perangkat desa.

**Comment by andifahruddinakas** [comment]
Pak @Zoel-WB, cek https://github.com/OpenSID/OpenSID/wiki/Kehadiran-Lainnya#mendaftarkan-perangkat-desa-untuk-kehadiran

**Comment by yogiperdana** [comment]
Bagaimana Pak @Zoel-WB apakah sudah bisa mengikuti seperti yang mas akas sampaikan?

**Comment by Zoel-WB** [comment]
Saya sudah memperbaikinya pak ..

**Comment by yogiperdana** [comment]
Issue ini ditutup karena bug tidak dapat direplikasi
