### ISSUE TITLE
[V22.04-PREMIUM] List Daftar Staff ->Pengaturan->Pengguna->Tambah Pengguna Baru->Menampilkan Data Nama Staf atau Perangkat Desa Yang Bukan Perangkat Desa 

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#5117]
### Jelaskan error yg dialami

Pada Pengaturan->Pengguna->Tambah Penggunaan->Menampilkan Data Nama Staf atau Perangkat Desa Yang Bukan Perangkat Desa yang terdaftar di disystem desa (masih menampilkan perangkat desa bawaan awal system seperti nama kepala desa muhammad ilham, mustahiq, S.AMd dan lainnya yg tak terdaftar sebagai perangkat desa pengguna system)

### Cara untuk mereplikasi errornya

1. Buka Menu Pengaturan
2. Klik Fitur Pengguna
3. Klik Tambah Pengguna Baru
4. Klik List Data pada Bagian Kolom Data Staff

### Hasil yg diharapkan

Agar supaya Tidak Menampikan Nama Staf atau Perangakat Desa yang bukan perangkat desa terpilih dalam daftur Fitur Buku Aparatur Desa.. 

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/64481641/161433858-5ff98f48-dda1-4c28-af1d-b46c20ea0ab3.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.04-premium

### Tema Yang Digunakan

Halaman Admin

### Informasi tambahan

.

**Comment by andifahruddinakas** [comment]
Silahkan nonaktifkan dan keluarkan dari kehadiran perangkat desa.

**Comment by andifahruddinakas** [comment]
Pak @Zoel-WB, cek https://github.com/OpenSID/OpenSID/wiki/Kehadiran-Lainnya#mendaftarkan-perangkat-desa-untuk-kehadiran

**Comment by yogiperdana** [comment]
Issue ini ditutup karena bug tidak dapat direplikasi
