### ISSUE TITLE
Bug/error: Modul Keuangan Grafik APB Desa Pada Pelaksanaan Pembiayaan Menampilkan Nilai Yang Salah

### ISSUE THREAD

**Issue by emanuel-simon** [OpenSID/OpenSID#5118]
### Jelaskan error yg dialami

Grafik APB Desa Pelaksanaan Pembiayaan menampilkan nilai yang salah, yaitu _PENJUMLAHAN antara Penerimaan Pembiayaan dan Pengeluaran Pembiayaan._
Nilai yang seharusnya ditampilkan adalah **PEMBIAYAAN NETTO**, yaitu **SELISIH antara Penerimaan Pembiayaan dan Pengeluaran pembiayaan.**

Sedangkan nilai yang ditampilkan di tabel sudah benar.

### Cara untuk mereplikasi errornya

1. Pegi ke https://demosid.opendesa.id/keuangan/impor_data
2. Impor data ini [opensid_data_2022_1.zip](https://github.com/OpenSID/OpenSID/files/8405943/opensid_data_2022_1.zip)
3. Periksa Tabel dan Kesalahan Nilai yang ditampilkan di Grafik

### Hasil yg diharapkan

Segera diperbaiki karena menyangkut transparansi keuangan, dikhawatirkan akan menimbulkan salah paham karena website menampilkan jumlah keuangan yang lebih besar dari yang seharusnya.

### Tangkapan layar dan log error

![2022-04-04_08h12_48](https://user-images.githubusercontent.com/48465803/161456533-4d2c5d8e-7205-43b1-a802-f5c8e46b140b.png)
![2022-04-04_08h13_20](https://user-images.githubusercontent.com/48465803/161456539-5e207c4e-e02b-4c3a-a483-02132d7f1c55.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.04-premium

### Tema Yang Digunakan

Esensi

### Informasi tambahan

Dibahas di Forum https://forum.opendesa.id/d/110-grafik-apb-desa-pelaksanaan-pembiayaan-menampilkan-nilai-yang-salah

**Comment by agungsugiarto** [comment]
Pak @emanuel-simon bisa berikan informasi tambahan terkait referensi/link sumber rumus yang digunakan?

**Comment by emanuel-simon** [comment]
Pak @agungsugiarto , Bisa dicek di tabel keuangan yg dihasilkan OpenSID.
- Pembiayaan terdiri dari Penerimaan Pembiayaan dan Pengeluaran Pembiayaan.
- Pembiayaan Netto = Penerimaan Pembiayaan - Pengeluaran Pembiayaan
- Pendapatan - Belanja + Pembiayaan Netto harus = 0

Jika bapak pakai contoh data yang saya lampirkan, Pendapatan - Belanja hasilnya minus pak, hasil minus ini nanti dijumlahkan dengan Pembiayaan Netto barulah selisih = 0

**Comment by agungsugiarto** [comment]
Baik pak @emanuel-simon terima kasih informasinya

**Comment by agungsugiarto** [comment]
Jadi seperti ini ya nilainya pak @emanuel-simon 

<img width="744" alt="image" src="https://user-images.githubusercontent.com/10989147/161515018-1d94d3b3-3cd5-47d7-98e9-fba0b4c1656b.png">

**Comment by emanuel-simon** [comment]
> Jadi seperti ini ya nilainya pak @emanuel-simon 
> 
> <img width="744" alt="image" src="https://user-images.githubusercontent.com/10989147/161515018-1d94d3b3-3cd5-47d7-98e9-fba0b4c1656b.png">
> 

Yg 50 juta juga jadi 9 juta pak

**Comment by agungsugiarto** [comment]
Bukankah yg 50jt itu nilai anggarannya pak? kemudian coba dilihat bagian APBDes Pendapatan dan APBDes Pembelanjaan perhitungaannya apakah juga sudah benar

**Comment by emanuel-simon** [comment]
> Bukankah yg 50jt itu nilai anggarannya pak? kemudian coba dilihat bagian APBDes Pendapatan dan APBDes Pembelanjaan perhitungaannya apakah juga sudah benar

Bukan pak, Pembiayaan itu Penerimaan Pembiayaan Dikurangi Pengeluaran Pembiayaan.
Sebentar saya lampirkan .pdf dari siskuedesnya

**Comment by agungsugiarto** [comment]
Untuk ini apakah sudah benar?

<img width="496" alt="image" src="https://user-images.githubusercontent.com/10989147/161517902-0a8dfce5-9c67-465c-98f3-7fd2b02b93d6.png">

**Comment by emanuel-simon** [comment]
> Untuk ini apakah sudah benar?
> 
> <img alt="image" width="496" src="https://user-images.githubusercontent.com/10989147/161517902-0a8dfce5-9c67-465c-98f3-7fd2b02b93d6.png">

yang ini sudah benar pak
ini saya lampirkan hasil printout siskeudes untuk dicek kebenaran nilainya pak
[laporan realisasi apbdesa.pdf](https://github.com/OpenSID/OpenSID/files/8408610/laporan.realisasi.apbdesa.pdf)

**Comment by agungsugiarto** [comment]
Seperti ini pak, nilainya sama?

<img width="746" alt="image" src="https://user-images.githubusercontent.com/10989147/161520765-6c46dfc5-3716-4677-bfd0-a22ba144c687.png">

**Comment by emanuel-simon** [comment]
> Seperti ini pak, nilainya sama?
> 
> <img alt="image" width="746" src="https://user-images.githubusercontent.com/10989147/161520765-6c46dfc5-3716-4677-bfd0-a22ba144c687.png">

Harusnya nilai realisasinya lebih 100% pak, karna pengeluaran pembiayaan belum realisasi, sedangkan penerimaan pembiayaan sudah realisasi 29 jutaan

**Comment by agungsugiarto** [comment]
Saya kurang paham, coba untuk rumus persesnya bagaimana terkait pembiayaan pak,

**Comment by emanuel-simon** [comment]
> Saya kurang paham, coba untuk rumus persesnya bagaimana terkait pembiayaan pak,

saya coba pakai excell ya pak @agungsugiarto
[PERHITUNGAN PEMBIAYAAN.xlsx](https://github.com/OpenSID/OpenSID/files/8408803/PERHITUNGAN.PEMBIAYAAN.xlsx)

**Comment by agungsugiarto** [comment]
nilai realisasi 29jt itu bagiamana pak?

**Comment by emanuel-simon** [comment]
29jt itu Baru Penerimaan Pembiayaan pak, jika hanya penerimaan pembiayaan yang realisasi sedangkan pengeluaran pembiayaan tidak realisasi, maka pasti persentasenya di atas 100, jika pengeluaran pembiayaan juga sudah realisasi, maka persentasenya kan kembali normal 100% dan ke bawah pak

**Comment by agungsugiarto** [comment]
Apakah tidak salah ini pak, perhitungan bisa melebihi 100% ?

**Comment by emanuel-simon** [comment]
Karena Pengeluaran Pembiayaan belum realisasi pak, jika sudah realisasi semua akan kembali normal persentasinya
dan karna nilai yang hendak ditampilkan di grafik adalah Jumlah Pembiayaan, lain soal jika di rincikan ke Penerimaan Pembiayaan dan Pengeluaran Pembiayaan.
coba pak @agungsugiarto simulasi dengan lembaran excell ini
[PERHITUNGAN PEMBIAYAAN.xlsx](https://github.com/OpenSID/OpenSID/files/8408927/PERHITUNGAN.PEMBIAYAAN.xlsx)

**Comment by agungsugiarto** [comment]
<img width="1253" alt="image" src="https://user-images.githubusercontent.com/10989147/161528198-8f5084c9-eba3-42de-b589-671175249ef0.png">

**Comment by emanuel-simon** [comment]
> <img alt="image" width="1253" src="https://user-images.githubusercontent.com/10989147/161528198-8f5084c9-eba3-42de-b589-671175249ef0.png">

angka realisasi seharusnya yang 29jt itu pak
![2022-04-04_18h52_06](https://user-images.githubusercontent.com/48465803/161529425-fbf1b16c-1ec3-4b45-9caa-02d24f22f2ec.png)

**Comment by agungsugiarto** [comment]
Oke sudah pak 
<img width="418" alt="image" src="https://user-images.githubusercontent.com/10989147/161530377-47e6b5b3-0df1-4d37-8cd2-94394291eeea.png">

**Comment by emanuel-simon** [comment]
> Oke sudah pak <img alt="image" width="418" src="https://user-images.githubusercontent.com/10989147/161530377-47e6b5b3-0df1-4d37-8cd2-94394291eeea.png">

Ok pak, untuk saat ini asalkan saat pengeluaran pembiayaan juga sudah realisasi dan grafik menampilkan persentase yang benar sepertinya sudah cukup.
Seharusnya teman-teman yang lain juga ikut beri masukan soal grafik yang ditampilkan khusus di Pembiayaan ini sebaiknya bagaimana.
Mungkin jangan diclose dulu sambil menunggu teman-teman yang lain.

**Comment by rudiansyahyunanda** [comment]
Sebaiknya dirincikan lagi saja. biar ga membingungkan
1. Penerimaan Pembiayaan
   - Realisasi | Anggaran
     29.629.952 | 29.629.952  ------ 100 %
     
  2. Pengeluaran Pembiayaan
      Realisasi | Anggaran
      0 | 20.552.300 ------------------ 0%

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/916

Untuk perbaikan perhitungan di tempat lain, misalnya widget bisa dibuat issue terpisah.
