### ISSUE TITLE
Bug/error: Ketika Tag ID Card diambil dari database penduduk maka tidak terbaca pada saat di scan KTPnya

### ISSUE THREAD

**Issue by yogiperdana** [OpenSID/OpenSID#5119]
### Jelaskan error yg dialami

Tag id card perangkat salah ketika perangkat diambil dari penduduk

### Cara untuk mereplikasi errornya

- Tambahkan perangkat dari penduduk yang mempunyai tag id card
- Login dengan ektp

### Hasil yg diharapkan

Berjalan normal

### Tangkapan layar dan log error

![login-ektp](https://user-images.githubusercontent.com/14155050/161477004-5fc04166-fc94-4b22-9c78-07b55420a134.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.04-premium

### Informasi tambahan

Informasi diperoleh dari https://forum.opendesa.id/d/107-scan-tag-id-card-absen-kehadiran-perangkat

**Comment by andifahruddinakas** [comment]
Mas @yogiperdana, coba cek juga jika tag_id_card yang ada dipenduduk digunakan oleh pamong lain.

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/915
