### ISSUE TITLE
Layanan  Lapor/Keluhan/Pengaduan bagi warga/umum

### ISSUE THREAD

**Issue by kelbatuix** [OpenSID/OpenSID#512]
Mohon izin mengajukan permohonan penambahan sistem terkait layanan lapor pada layanan mandiri : 
1. Mohon sekiranya layanan Lapor tidak diperuntukan untuk lapor perubahan data kependudukan saja (menghilangkan tulisan tsb) tapi untuk semua hal.
2. Layanan Lapor tidak hanya terdapat pada menu layanan mandiri, melainkan di menu statis seperti menu log in, karena bagi yang belum mendaftar agar dapat juga mengakses layanan lapor;
3. Layanan lapor dapat memuat attachment dokumen dan gambar sebagai bukti pendukung;
4. Layanan lapor dapat di tetapkan status (Sudah ditindaklanjuti, Belum ditindaklanjuti, ditolak);
5. Layanan lapor dapat menampilkan statistik jumlah laporan perbulan/pertahun (Sudah ditindaklanjuti, Belum ditindaklanjuti, ditolak).
Semoga dapat terkabulkan, terima kasih.

**Comment by metalab25** [comment]
Kalo saya melihat bahwa lapor itu sebagai bentuk peran aktif warga terhadap lingkungannya namun setiap laporan tetap harus melalui login layanan mandiri yang menyertakan NIK agar laporannya bisa dipertanggung jawabkan

**Comment by kelbatuix** [comment]
Benar, saya setuju bahwa lapor merupakan peran aktif warga dengan tujuan tentunya perbaikan kualitas pelayanan. Akan tetapi tentunya juga yg menjadi pertimbangan adalah jika pelapor hanya dibatasi dari warga setempat, bagaimana dengan pelapor yang bukan warga setempat yang tentunya dapat ikut merasakan kondisi pelayan atau kondisi lingkungan di wilayah kita. Akan lebih baik lagi jika mereka juga diberikan akses memberikan laporan di aplikasi ini sehingga menu lapor dapat maksimal. 
Selain itu tentunya apapun bentuk laporan tetap akan diperiksa lagi kebenaran laporannya, untuk itu perlu ada proses tanggapan seperti ditindaklanjuti, atau ditolak. Mudah-mudahan dapat dikabulkan sarannya :)

**Comment by eddieridwan** [comment]
@kelbatuix Apakah yang anda maksud, fitur seperti 'Hubungi Kami' atau 'Contact Us' (contoh http://www.bankmandiri.co.id/contact.aspx) yang dapat digunakan publik untuk segala macam komunikasi, seperti bertanya, memberi komentar, melaporkan masalah, dsbnya?

Atau apakah yang anda maksud lebih spesifik, misalnya sebagai portal pengaduan dari publik seperti http://pengaduan.banyuwangikab.go.id/?

**Comment by metalab25** [comment]
sepertinya yang di portal http://pengaduan.banyuwangikab.go.id/ bagus kalo diterapkan di OpenSID.
bagaimana bung @eddieridwan dan om @pandigresik

**Comment by kelbatuix** [comment]
Sepertinya http://www.bankmandiri.co.id/contact.aspx lebih lengkap karena ada beberapa pilihan termasuk seperti jasabah dan umum (bisa utk penduduk dan umum). Juga ada fitur attachmentnya. Yg paling utama adalah bisa dilihat statistik laporan dan status bgi yg sudah di tindaklanjuti dan yg belum. Tapi utk dijadikan dalam bentuk portal seperti banyuwangi juga bagus hanya saja menu lapornya diambil dari menu mandiri.

**Comment by ariandii** [comment]
Rencana mau buat issues terkait ini.
Saat ketik judul, ternyata muncul History Issues terdahulu. 
Terutama terkait poin nomor 3, 4 dan 5 di atas.

Mohon tindak lanjutnya.

Terima kasih.

![tanpa judul](https://user-images.githubusercontent.com/46939846/52580519-21792580-2e5b-11e9-9bfc-fa84fa52284e.png)

**Comment by afa28** [comment]
Apakah ini masih bermasalah / masih diperlukan??? Kalau tdk, silahkan di close.

**Comment by mizwaruddin** [comment]
Apakah menu "pesan" dalam layanan mandiri belum mewakili issue ini?

**Comment by eddieridwan** [comment]
Lihat contoh Sikema (sistem keluhan) di OpenDK. Tapi sebaiknya dirancang ulang, dengan melihat contoh di bebagai aplikasi lain.

**Comment by eddieridwan** [comment]
Tambahan dari issue https://github.com/OpenSID/OpenSID/issues/1758

Status proses keluhan:

- Menunggu Diproses, status default awal
- Sedang Diproses, dirubah oleh staf saat sedang menangani laporan
- Selesai Diproses, dirubah oleh staf saat laporan sudah terselesaikan

sertakan juga inputan keterangan yang diisi oleh staf yg menangani laporan.
kemudian disisi Pelapor / Warga saat login dibawah Form Laporan, disertakan Daftar Aduan / Lapor beserta status dan keterangannya. (halaman view diperlukan)

Supaya pelapor mengetahui sejauh mana proses laporan dan apa yg sedang diprosesnya dikarenakan tidak ada keterangan.

**Comment by andifahruddinakas** [comment]
Sudah digabung ke `FITUR PREMIUM` melalui PR https://github.com/OpenSID/premium/pull/542
