### ISSUE TITLE
Bug/error: hasil unduh export xls dalam format webpage

### ISSUE THREAD

**Issue by Wiliyantoro** [OpenSID/OpenSID#5121]
### Jelaskan error yg dialami

hasil unduhan / import data dengan format xls (webpage) kalau hasil unduhan di buka di pc bisa saja namun dalam praktek saya save as file dan rubah file dengan xlsx ,( format ms excel) yang menjadi permasalahan kalau kita unduh lewat hp terkadang tampil kode html, mungkin perlu atau tidak perbaikan unduh excel agar bisa dibuka langsung lewat hp ataupun pc

### Cara untuk mereplikasi errornya

saat export data / unduh xls ( dalam format webpage )

### Hasil yg diharapkan

agar data / file dalam bentuk xlsx yang jadi, bisa dibuka di hp

### Tangkapan layar dan log error

![1648361136-633468-screenshot-2022-03-27-14-04-30-98-c37d74246d9c81aa0bb824b57eaf7062](https://user-images.githubusercontent.com/44520382/161532443-b63c1a6a-43cd-4ba7-9704-4b6cfc99d7fb.jpg)
![1648361131-817000-screenshot-2022-03-27-14-04-17-88-c37d74246d9c81aa0bb824b57eaf7062](https://user-images.githubusercontent.com/44520382/161532456-a3cea203-9a12-42a7-b20e-90c644a07680.jpg)
![1648361125-702142-screenshot-2022-03-27-14-02-47-25-87869c5c71fa0655e350912352595c23](https://user-images.githubusercontent.com/44520382/161532459-20379fa9-2f06-4508-8a22-0f15df51ddf9.jpg)
![1648361116-237972-screenshot-2022-03-27-14-02-06-46-f90b96e7af3c5a594eb0c92de7fc5fe1](https://user-images.githubusercontent.com/44520382/161532466-0e29a52a-c10f-417f-891c-d0f0a4979f1b.jpg)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.03-premium-rev03

### Tema Yang Digunakan

Denatra v.6

### Informasi tambahan

link diskusi forum : https://forum.opendesa.id/d/64-fitur-unduh-import-excel-format-xls

**Comment by andifahruddinakas** [comment]
Mas @Wiliyantoro, silahkan cek di https://berputar.opendesa.id/ apakah mengalami hal yang sama? Jika tidak, silahkan update versi OpenSID yang anda gunakan.

**Comment by Wiliyantoro** [comment]
![image](https://user-images.githubusercontent.com/44520382/161663851-bf2e14bf-74a7-4a23-ac49-1ed09d43cf13.png)

tampil seperti ini pak saat saya lakukan save as, berarti yg terunduh dalam bentuh halaman webpage

**Comment by andifahruddinakas** [comment]
> ![image](https://user-images.githubusercontent.com/44520382/161663851-bf2e14bf-74a7-4a23-ac49-1ed09d43cf13.png)
> 
> tampil seperti ini pak saat saya lakukan save as, berarti yg terunduh dalam bentuh halaman webpage

tinggal ganti save as type nya ke xls, xlsx atau format yg diinginkan.

**Comment by yogiperdana** [comment]
Issue ini bisa diselesaikan dengan memilih format yang benar
