### ISSUE TITLE
Bug/error: unduh excel pembangunan berantakan

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#5122]
### Jelaskan error yg dialami

ketika mengunduh excel pembangunan hasilnya berantakan

### Cara untuk mereplikasi errornya

pergi ke halaman pembangunan > rincian dokumentasi > unduh excel > lihat hasil

### Hasil yg diharapkan

tertata rapi

### Tangkapan layar dan log error

![Untitled](https://user-images.githubusercontent.com/35319600/161669430-498f2180-a969-4cd9-b5f2-e64c73a0a79c.jpg)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

premium 22.04

### Tema Yang Digunakan

-

### Informasi tambahan

-

**Comment by agungsugiarto** [comment]
sudah diperbaiki melalui pr https://github.com/OpenSID/premium/pull/956
