### ISSUE TITLE
Bug/error: Gagal Expor Excel Data Penduduk 

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#5123]
### Jelaskan error yg dialami

mengalami gagal saat klik Expor Penduduk.

![photo_2022-04-05_12-43-28](https://user-images.githubusercontent.com/46939846/161686807-0f15d30a-b902-4b77-ae8c-1724f7e34c04.jpg)

### Cara untuk mereplikasi errornya

Pergi ke halaman menu Kependudukan -> Penduduk
Lalu klik Impor/Expor
Kemudian klik Ekspor Penduduk

Maka tidak ada proses apapun.
Diduga file excel belum selesai dibuat tapi langsung ke redirect

### Hasil yg diharapkan

Normal

### Tangkapan layar dan log error

Di atas

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.04-premium

**Comment by andifahruddinakas** [comment]
Mas @yogiperdana, bisa tambahkan try cacth dan hanya redirect jika terjadi error

**Comment by yogiperdana** [comment]
> Mas @yogiperdana, bisa tambahkan try cacth dan hanya redirect jika terjadi error

oke mas

**Comment by agungsugiarto** [comment]
Mas @andifahruddinakas, @yogiperdana issue ini mohon mencoba dahulu menggunakan database pak @ariandii, menggunakan try catch hanya menangkap masalah tapi tidak memperbaikinya.

**Comment by andifahruddinakas** [comment]
> Mas @andifahruddinakas, @yogiperdana issue ini mohon mencoba dahulu menggunakan database pak @ariandii, menggunakan try catch hanya menangkap masalah tapi tidak memperbaikinya.

Masalahnya kemarin karena penduduk yang banyak (-+ 4k), saat mengekspor data file excel belum di buat tapi sudah di redirect. Bisa dengan cukup hapus ridirectnya saja, tp ini menambahkan try catch agar melaporkan jika terjadi masalah jika terjadi gagal ekspor.

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melalui pr https://github.com/OpenSID/premium/pull/921
