### ISSUE TITLE
Permintaan fitur: Tersedia nya Informasi Size Khusus Folder Desa dan SQL

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#5124]
### Apa kekurangan yg ingin diatasi?

Agar mengetahui informasi size folder desa apakah berukuran kecil atau besar yang berakibat unduh data menjadi lama dan berat hingga gagal.

### Jelaskan solusi yg diinginkan

Tersedia info khusus mengenai size folder desa dan size SQL, yang tampil ketika ingin Backup Database dan Folder Desa yang ada di Halama  Pengaturan -> Database -> Backup

### Apakah ada alternatif lain

Tidak ada 

### Untuk versi OpenSID mana

Semua

**Comment by agungsugiarto** [comment]
Sudah masuk di fitur premium melalui pr https://github.com/OpenSID/premium/pull/923
