### ISSUE TITLE
Permintaan fitur: Tambahkan Print + Download pada statistik > Laporan bulanan > Rincian Kependudukan Bulanan

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#5125]
### Apa kekurangan yg ingin diatasi?

operator ingin download / print rincian penduduk bulanan sebagai bahan tambahan laporan penduduk

### Jelaskan solusi yg diinginkan

ketika operator ingin mendownload / print rincian kependudukan bulanan tidak bisa sehingga ketik manual di excel dengan panduan opensid

### Apakah ada alternatif lain

tidak ada

### Untuk versi OpenSID mana

Premium

### Informasi tambahan

laporan bulanan penduduk tingkat kecamatan mewajibkan melampirkan rincian laporan bulanan sebagai tambahan pelaporan

statistik > laporan bulanan > pilih detail isian 

![image](https://user-images.githubusercontent.com/35319600/161687163-87050d42-ded7-4c3c-b08f-0c8a6d62f87b.png)

**Comment by ariandii** [comment]
Nampaknya download / print rincian penduduk bulanan sudah ada sejak lama.

TInggal diusulkan filter berdasarkan Jenis Kelamin, dll yg diinginkan

<img width="960" alt="image" src="https://user-images.githubusercontent.com/46939846/161699180-86d449fe-9f65-419b-90e5-5f4e4ea5ca12.png">

**Comment by balongbesuk** [comment]
kl d buku administrasi penduduk memang ada

di isue yang ada pada statistik > laporan bulanan > pilih detail isian
