### ISSUE TITLE
Permintaan fitur: Wajibkan isian alamat sebelumnya pada penambahan penduduk datang / masuk

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#5127]
### Apa kekurangan yg ingin diatasi?

operator sering kali lupa mengisi data alamat sebelumnya pada isian penduduk datang sehingga alamat lama tidak terekam dalam opensid dan laporan kependudukan

### Jelaskan solusi yg diinginkan

wajibkan isian alamat lama pada isian penduduk datang

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

Premium

### Informasi tambahan

-

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/1025
