### ISSUE TITLE
Bug/error: Nomor kartu BPJS Ketenagakerjaan untuk penduduk dengan status pekerjaan tertentu ketika di klik angka pada jumlah peserta terbuka semua penduduk bukan penerima BPJS NAKER 

### ISSUE THREAD

**Issue by muhtar-coder** [OpenSID/OpenSID#5128]
### Jelaskan error yg dialami

Status pekerjaan tertentu yang terdaftar BPJS Ketenagakerjaan ketika data statistik nya di klik pada angka jumlah penerima yang terbuka semua penduduk dengan status pekerjaan yang sama meski tidak terdaftar BPJS ketegakerjaan

### Cara untuk mereplikasi errornya

COBA pada penduduk dengan status pekerjaan misal petani/mengurus rumah tangga/belum bekerja, isi nomor kartu BPJS ketenagakerjaan nya sesuai di kartu.
kemudian setelah di isi nomor kartu ketenagakerjaan nya lalu masuk ke data stattistik ketenaga kerjaan,walaupun yang mempunyai nomor ketenagakerjaan cuma satu penduduk misal pada penduduk dengan pekerjaan petani/pekebun,maka ketika di klik angka nya yang akan terbuka adalah semua penduduk dengan pekerjaan tersebut,padahal target nya adalah penduduk yang memiliki nomor ketenagakerjaan.

### Hasil yg diharapkan

data sesuai angka statistik ketenaga kerjaan dengan data pekerjaan sesuai data penduduk

### Tangkapan layar dan log error

1.
gambar statistik ketenaga kerjaan penduduk yang pekerjaan nya petani,mengurus rumah tangga,dll

![image](https://user-images.githubusercontent.com/55665526/161806998-61447742-8df7-46ee-8de8-ea0c4bf55874.png)

2.
gambar data penduduk setelah di klik jumlah angka peserta yang hanya satu peserta di data statistik tapi setelah di klik terbuka banyak.
![image](https://user-images.githubusercontent.com/55665526/161806930-7c79c766-487b-42c7-95d1-ce9615ca9662.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

22.04 premium

### Tema Yang Digunakan

Denatra

### Informasi tambahan

tidak ada

**Comment by muhtar-coder** [comment]
https://forum.opendesa.id/d/119-data-statistik-ketenaga-kerjaan-penduduk-tidak-sesuai

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melalui pr https://github.com/OpenSID/premium/pull/929
