### ISSUE TITLE
Tampilkan keikutsertaan program bantuan sasaran keluarga di "Layanan Mandiri"

### ISSUE THREAD

**Issue by dadannurman** [OpenSID/OpenSID#513]
Mohon maaf master, nyari issue tentang ini tapi tidak ada yang pas (apabila ada Issues sudah "clossed") jadi izin saya buat issue baru,

Penduduk yang mendapat "Program Bantuan"

![raskin](https://user-images.githubusercontent.com/28327817/28448847-7ec61440-6e05-11e7-965d-f7abc017042f.PNG)

Setelah di cek di "Layanan Mandiri" oleh akun(Penduduk) yang bersangkutan (AHLUL)

![raskin2](https://user-images.githubusercontent.com/28327817/28448871-a8444e90-6e05-11e7-851b-6b669832d1f5.PNG)

tidak muncul "Program Bantuan" yang didapat.

Mohon bantuannya apabila ada kesalahan yang berasal dari kesalahan saya sendiri.

**Comment by metalab25** [comment]
Program bantuan yang dimunculkan adalah program bantuan yang bersifat perorangan seperti jamkesnas dan yang bersifat perorangan lainnya

**Comment by dadannurman** [comment]
Terima kasih master @metalab25 atas pencerahan nya :+1:

**Comment by eddieridwan** [comment]
@dadannurman , saat ini fitur _bantuan_ di _layanan mandiri_ belum menampilkan keanggotaan warga pada program bantuan sasaran 'keluarga'. Jika fitur itu diperlukan, silakan ganti issue ini untuk menambahkan fitur itu.

**Comment by dadannurman** [comment]
Terimakasih bung @eddieridwan , mungkin untuk sementara belum di perlukan.

**Comment by afa28** [comment]
Duplicate #3044
