### ISSUE TITLE
Bug/error: Token layanan kadang tidak mengikutkan tanggal_berlangganan

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#5130]
### Jelaskan error yg dialami

"iat": 1649173524,
  "exp": 3541333524,
  "nbf": 1649173524,
  "jti": "9bc12960680d155accb81ffe4179a9b56b94955b13c6ee53144e519eb8dc427f",
  "sub": "267",
  "prv": "f9307eb5f29c72a90dbaaef0e26f0262ede86f55",
  "desa_id": "xx.xx.xx.xxxx",
  "domain": "https://xxxxxxx.web.id",
  "tanggal_berlangganan": []
}

sehingga menampilkan error yang salah
![notifnya jadi salah](https://user-images.githubusercontent.com/57283157/161854228-48fd8e57-fc23-4ce3-9152-133ed88bb433.png)

### Cara untuk mereplikasi errornya

Gunakan token yang tidak memiliki tanggal_berlangganan

### Hasil yg diharapkan

Ada pengecekan jika tidak ada tanggal_berlangganan, dan beri peringatan untuk mengganti token.

### Tangkapan layar dan log error

![notifnya jadi salah](https://user-images.githubusercontent.com/57283157/161854375-9349546b-350c-4850-b60b-5da1f7ee83f0.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.04

### Tema Yang Digunakan

bawaan

### Informasi tambahan

tidak ada

**Comment by yogiperdana** [comment]
Sudah diperbaiki pada PR https://github.com/OpenSID/Layanan_OpenDESA/pull/54
