### ISSUE TITLE
Repositori OpenSID API tidak ada

### ISSUE THREAD

**Issue by laluheri** [OpenSID/OpenSID#5134]
Sy mau install OpenSID API .. tapi sy cek di link nya kok tidak tersedia ya? berikut linknya sesuai dengan dokumentasi Wiki
git clone https://github.com/OpenSID/opensid-laravel.git 

mohon srannya.

**Comment by andifahruddinakas** [comment]
Private, jika pelanggan premium akan dibagikan ke grup telegram.
