### ISSUE TITLE
Bug/error: Menu tidak terpilih saat melakukan ubah data.

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#5135]
### Jelaskan error yg dialami

Saat melakukan ubah data menu, menu dengan pilihan datanya tidak terpilih sesuai data sebelumnya.

### Cara untuk mereplikasi errornya

1. Buka menu
2. Ubah salah 1 menu (bukan menu dengan jenis eksternal)
3. Form ubah akan menampilkan data, tapi pada data link tidak terpilih

### Hasil yg diharapkan

Data link ditampilkan sesuai data yang ada sebelumnya

### Tangkapan layar dan log error

![menu](https://user-images.githubusercontent.com/57283157/162169468-f9b167cf-2427-4455-be56-ef64f88a965e.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.04-premium

### Tema Yang Digunakan

bawaan

### Informasi tambahan

.

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melalui pr https://github.com/OpenSID/premium/pull/966
