### ISSUE TITLE
Bug/error: Notifikasi baris gagal ketika impor tidak muncul

### ISSUE THREAD

**Issue by yogiperdana** [OpenSID/OpenSID#5137]
### Jelaskan error yg dialami

Ketika melakukan impor notifikasi baris gagal tidak muncul

### Cara untuk mereplikasi errornya

1. Pergi ke halaman penduduk
2. Masuk ke menu impor
3. Impor penduduk

### Hasil yg diharapkan

Muncul pesan baris gagal

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.04-premium

**Comment by Zoel-WB** [comment]
Error Impor penggunaan ->FormatImporExcel.xlsm ->save as menjadi ->FormatImporExcel.xlsx
![image](https://user-images.githubusercontent.com/64481641/162637023-91d386af-161e-4654-9773-0036b8367d57.png)

Log Error :
GuzzleHttp\Exception\RequestException: cURL error 60: SSL certificate problem: certificate has expired (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://layanan.opendesa.id/api/v1/pelanggan/catat-versi in D:\https\Premium\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php:211
Stack trace:#0 D:\https\Premium\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(158): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)#1 D:\https\Premium\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(110): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))#2 D:\https\Premium\vendor\guzzlehttp\guzzle\src\Handler\CurlHandler.php(47): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))#3 D:\https\Premium\vendor\guzzlehttp\guzzle\src\Handler\Proxy.php(28): GuzzleHttp\Handler\CurlHandler->__invoke(Object(GuzzleHttp\Psr7\Request), Array)#4 D:\https\Premium\vendor\guzzlehttp\guzzle\src\Handler\Proxy.php(48): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}(Object(GuzzleHttp\Psr7\Request), Array)#5 D:\https\Premium\vendor\guzzlehttp\guzzle\src\PrepareBodyMiddleware.php(64): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}(Object(GuzzleHttp\Psr7\Request), Array)#6 D:\https\Premium\vendor\guzzlehttp\guzzle\src\Middleware.php(31): GuzzleHttp\PrepareBodyMiddleware->__invoke(Object(GuzzleHttp\Psr7\Request), Array)#7 D:\https\Premium\vendor\guzzlehttp\guzzle\src\RedirectMiddleware.php(71): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Request), Array)#8 D:\https\Premium\vendor\guzzlehttp\guzzle\src\Middleware.php(63): GuzzleHttp\RedirectMiddleware->__invoke(Object(GuzzleHttp\Psr7\Request), Array)#9 D:\https\Premium\vendor\guzzlehttp\guzzle\src\HandlerStack.php(75): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Request), Array)#10 D:\https\Premium\vendor\guzzlehttp\guzzle\src\Client.php(331): GuzzleHttp\HandlerStack->__invoke(Object(GuzzleHttp\Psr7\Request), Array)#11 D:\https\Premium\vendor\guzzlehttp\guzzle\src\Client.php(168): GuzzleHttp\Client->transfer(Object(GuzzleHttp\Psr7\Request), Array)#12 D:\https\Premium\vendor\guzzlehttp\guzzle\src\Client.php(187): GuzzleHttp\Client->requestAsync('POST', Object(GuzzleHttp\Psr7\Uri), Array)#13 D:\https\Premium\vendor\guzzlehttp\guzzle\src\ClientTrait.php(95): GuzzleHttp\Client->request('POST', 'https://layanan...', Array)#14 D:\https\Premium\donjo-app\core\MY_Security.php(226) : eval()'d code(1) : eval()'d code(395): GuzzleHttp\Client->post('https://layanan...', Array)#15 D:\https\Premium\donjo-app\core\MY_Security.php(226) : eval()'d code(1) : eval()'d code(284): Premium->kirimVersi()#16 D:\https\Premium\donjo-app\core\MY_Security.php(226) : eval()'d code(1) : eval()'d code(416): Premium->validasi()#17 D:\https\Premium\donjo-app\core\MY_Security.php(226) : eval()'d code(1) : eval()'d code(49): Admin_Controller->__construct()#18 D:\https\Premium\vendor\codeigniter\framework\system\core\CodeIgniter.php(519): Penduduk->__construct()#19 D:\https\Premium\index.php(377): require_once('D:\\https\\Premiu...')#20 {main}

Data Masuk "SUKSES" akan tetapi notif pada layar muncul pesan error. kemudian detail error baris sukses atau baris gagal tidak tampil seperti biasanya setelah impor ada notif pemberitahun. berikut informasi dan bahan kajian lanjutan ikut saya sertakan lampiran file log error.
[log-2022-04-11.zip](https://github.com/OpenSID/OpenSID/files/8459792/log-2022-04-11.zip)

![image](https://user-images.githubusercontent.com/64481641/162637602-f3583dd4-33b6-43da-8ceb-3246362e38a9.png)


![image](https://user-images.githubusercontent.com/64481641/162637155-603962f1-7bfc-4583-be75-eeb1df6d032a.png)


![image](https://user-images.githubusercontent.com/64481641/162637323-87bc0340-86ed-4835-b4cc-c9fab8f4b80a.png)

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melalui pr https://github.com/OpenSID/premium/pull/947
