### ISSUE TITLE
Bug/error: ubah latar login mandiri gambar tidak berubah

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#5140]
### Jelaskan error yg dialami

ketika pengguna mengganti latar layanan mandiri, preview gambar latar tidak berubah

### Cara untuk mereplikasi errornya

buka layanan mandiri > pengaturan > ubah latar login layanan mandiri > simpan (lihat preview menu latar login mandiri masih sama)

### Hasil yg diharapkan

preview latar login mandiri berubah menyesuaikan ubahan gambar

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/35319600/162599252-0546aacb-5da0-4d53-81c8-ab5cf5517152.png)

![image](https://user-images.githubusercontent.com/35319600/162599239-c88d0e2e-aa79-42aa-80cb-5decb04b2251.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

berputar

### Tema Yang Digunakan

-

### Informasi tambahan

-

**Comment by dikisiswanto** [comment]
Sekilas mirip issue #5101

**Comment by balongbesuk** [comment]
> Sekilas mirip issue #5101

sepertinya masalah cache

**Comment by agungsugiarto** [comment]
sudah diperbaiki melalui pr https://github.com/OpenSID/premium/pull/954
