### ISSUE TITLE
Permintaan fitur: Tambahkan pengaturan isian jumlah slider pada pengaturan slider besar

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#5141]
### Apa kekurangan yg ingin diatasi?

isian jumlah slider besar bersifat baku tidak bisa dirubah oleh pengguna sehingga ketika pengguna ingin mengubah jumlah isiannya perlu mengubah manual sedangkan d versi premium file file tersebut sudah d enkriptsi

### Jelaskan solusi yg diinginkan

pengguna bisa mengubah isian jumlah slider yang akan ditampilkan

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

premium

### Informasi tambahan

![Untitled](https://user-images.githubusercontent.com/35319600/162609915-42dbdb55-e12d-4d9a-b21a-2a4ae2cdea19.jpg)

**Comment by andifahruddinakas** [comment]
https://github.com/OpenSID/OpenSID/pull/7449
