### ISSUE TITLE
OpenSID 22.04 Import Data Penduduk, Data Kelaurga Tidak Muncul

### ISSUE THREAD

**Issue by astonialam** [OpenSID/OpenSID#5143]
### Jelaskan error yg dialami

Pada saat import data penduduk excel ke rilis 22.04 umum, data keluarga atau data per Kartu Keluarga tidak ada atau terbaca..

### Cara untuk mereplikasi errornya

Impor database penduduk excel

### Hasil yg diharapkan

Tidak terjadi nihil atau nol saat import data penduduk excel..

### Tangkapan layar dan log error

![Screenshot_81](https://user-images.githubusercontent.com/77397959/162643158-dbe14874-80a8-4cd4-bf89-1cc79a672910.jpg)

### Rilis Versi OpenSID

Rilis Umum

### Versi OpenSID

22.04

### Tema Yang Digunakan

Tema Natra

### Informasi tambahan

Berharap segera teratasi

**Comment by andifahruddinakas** [comment]
Sertakan contoh file yg di impor, bisa kirim lewwt telegram.

**Comment by Zoel-WB** [comment]
https://forum.opendesa.id/d/144-data-keluaraga
https://forum.opendesa.id/d/145-import-data-penduduk-sukses-data-keluarga-gagal-kosong-opensid-2204-umum

![image](https://user-images.githubusercontent.com/64481641/163254626-fd053180-acc6-4387-9740-a0abb47a2867.png)


![image](https://user-images.githubusercontent.com/64481641/163254508-aa955140-3890-43ce-8c9b-8114e9299dc8.png)

**Comment by dwipradana** [comment]
> https://forum.opendesa.id/d/144-data-keluaraga https://forum.opendesa.id/d/145-import-data-penduduk-sukses-data-keluarga-gagal-kosong-opensid-2204-umum
> 
> ![image](https://user-images.githubusercontent.com/64481641/163254626-fd053180-acc6-4387-9740-a0abb47a2867.png)
> 
> ![image](https://user-images.githubusercontent.com/64481641/163254508-aa955140-3890-43ce-8c9b-8114e9299dc8.png)

terima kasih sudah dibanntu followup issuenya pak @Zoel-WB

**Comment by yogiperdana** [comment]
Issue ini ditutup karena aturan impor sudah disesuaikan 
ref: https://github.com/OpenSID/OpenSID/issues/4996

**Comment by yogiperdana** [comment]
Duplikat issue https://github.com/OpenSID/OpenSID/issues/4484. Issue ini akan diperbaiki di rilis berikutnya yaitu 22.05 umum bulan depan

**Comment by yogiperdana** [comment]
Terdapat pengguna yang masih mengalami bug. Mungkin pengguna belum melakukan impor ulang. Bisa dipantau di https://www.facebook.com/groups/OpenSID/permalink/2125453177619652/

**Comment by andifahruddinakas** [comment]
> Terdapat pengguna yang masih mengalami bug. Mungkin pengguna belum melakukan impor ulang. Bisa dipantau di https://www.facebook.com/groups/OpenSID/permalink/2125453177619652/

Infokan untuk update ke versi terbaru dan lakukan impor ulang jika masih pengguna baru (baru install)
