### ISSUE TITLE
Bug/error: Judul artikel yang di awali dengan angka akan di arahkan ke artikel lain

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#5145]
### Jelaskan error yg dialami

Jika judul artikel diawali dengan angka, saat membuka lnik artikel tersebut akan diarahkan ke artikel lain.

### Cara untuk mereplikasi errornya

Buat sebuah artikel Dinamis lalu simpan, kemudian buka website dan cari artikel yang baru dibuat tersebut selanjutnya klik (lihat selengkapnya) apakah artikel baru tsb terbuka atau bahkan malah tergantikan secara otomatis dengan artikel lain yang telah ada sebelumnya.

### Hasil yg diharapkan

Artikel diarahkan ke sesuai dengan url slugnya walau judul diawali dengan angka.

### Tangkapan layar dan log error

nm

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.04-premium-rev01

### Tema Yang Digunakan

bawaan

### Informasi tambahan

s

**Comment by yogiperdana** [comment]
gimana contoh artikelnya mas? saya coba normal @andifahruddinakas

**Comment by andifahruddinakas** [comment]
> gimana contoh artikelnya mas? saya coba normal @andifahruddinakas 

Coba cek di telegram

**Comment by totoprayogo1916** [comment]
kalau sudah diperbaiki lewat PR lain, 
PR saya bisa di close saja

cc: @yogiperdana @andifahruddinakas

**Comment by andifahruddinakas** [comment]
> kalau sudah diperbaiki lewat PR lain, PR saya bisa di close saja
> 
> cc: @yogiperdana @andifahruddinakas

Siap, akan di cek sama mas @yogiperdana

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melalui pr https://github.com/OpenSID/premium/pull/962
