### ISSUE TITLE
Permintaan fitur: Pada menu analisis

### ISSUE THREAD

**Issue by rezkifernando** [OpenSID/OpenSID#5146]
### Apa kekurangan yg ingin diatasi?

Pada menu analisis setiap pertanyaan hanya bisa satu jawaban
Ex. Air Minum
Terkadang dalam pemanfaatan air minum,bisa jadi ada masyarakat yang menggunakan lebih dari satu,misal pdam dan depot air minum
Ex. Penghasilan pertanian,perkebunan dll
Masyarakat bisa jadi memiliki kebun dengan komoditas lebih dari satu,di aplikasi hanya bisa memilih satu komoditas saja,sementara pada aplikasi hanya bisa mengisi satu saja untuk setiap satu analisis indikator

### Jelaskan solusi yg diinginkan

Bisakah untuk setiap analisis indikator dapat ditambahkan menjadi lebih dari satu,menggunakan fitur append atau fitur yg lebih baik lainnya,untuk pertanyaan dengan metode checkbox,tolong ditambahkan tidak ada,karena bisa jadi dalam satu pertanyaan survey,keluarga itu tidak memiliki sama sekali dari salah satu butir jawaban yang ada pada parameter

### Apakah ada alternatif lain

Jika itu bisa dilakukan,fitur analisis akan sangat bermanfaat untuk melakukan percepatan satu data indonesia,dimulai dari desa

### Untuk versi OpenSID mana

v21.03 umum

### Informasi tambahan

Saya berharap ini dapat menjadi pertimbangan tim open sid,terima kasih.

**Comment by eddieridwan** [comment]
@rezkifernando apakah sudah mempelajari panduan: https://github.com/OpenSID/OpenSID/wiki/Indikator--Pertanyaan-Analisis. Lihat pilihan indikator pertanyaan, misalnya pilihan ganda.

Harap perrtanyaan penggunaan tidak menggunakan issue Github. Issue Github dimaksudkan untuk masalah yg telah diverifikasi memang sesuatu yg perlu diperbaiki oleh programmer. 

Jadi harap mencari solusi atau bertanya dulu di https://forum.opendesa.id. Jika di situ disimpulkan memang perlu perbaikan, baru buat issuenya.
