### ISSUE TITLE
Bug/error: BUG? web kehadiran terbypass oleh perangkat/ gawai yang tidak terdaftar

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#5147]
### Jelaskan error yg dialami

gawai kehadiran awalnya dimaksudkan hanya terbuka pada perangkat / gawai yang terdaftar saja tetapi dengan sedikit "coding" pengguna maka rekam kehadiran bisa d akses oleh gawai yang tidak terdaftar

### Cara untuk mereplikasi errornya

https://www.teupinbeulangan.desa.id/kehadiran/masuk?mac_address=4C:1D:96:57:95:54

https://kueh.desa.id/kehadiran/masuk?mac_address=5C:AC:4C:1A:8E:66

### Hasil yg diharapkan

blokir gawai kehadiran tidak diperkenankan di akses oleh perangkat yang tidak terdaftar

ATAU

gawai kehadiran bisa di akses darimana saja tetapi membutuhkan perangkat tambahan seperti alat pembaca KTP sehingga walaupun bisa di akses darimana saja di perlukan perangkat tambahan untuk bisa masuk (matikan kehadiran via login username / password)

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

22.04

### Tema Yang Digunakan

-

### Informasi tambahan

-

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melalui pr https://github.com/OpenSID/premium/pull/953

**Comment by balongbesuk** [comment]
https://berputar.opendesa.id/kehadiran/masuk?ip_address=127.0.0.1

tambahan cara bypass melalui IP addres

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/1034
