### ISSUE TITLE
Bug/error: Sediakan tombol delet untuk pendataan vaksin

### ISSUE THREAD

**Issue by WAHYUDIK** [OpenSID/OpenSID#5148]
### Apa kekurangan yg ingin diatasi?

saat ini tidak ada tombol delet untuk menu pendataan vaksin, sehingga apabila ada petugas entri data vaksin mengalami hal kesalahan input data, tidak bisa di delet.
![image](https://user-images.githubusercontent.com/31026980/163104222-d0ba7dd7-6b24-4753-b759-b90914b47d57.png)

### Jelaskan solusi yg diinginkan

sediakan tombol delet, agar ketika ada petugas melakukan kesalahan input bisa di delet

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

opensid 22.04 premium

### Informasi tambahan

-

**Comment by yogiperdana** [comment]
Tombol edit/update sudah disediakan apabila terdapat kesalahan dalam penginputan pak @WAHYUDIK

**Comment by yogiperdana** [comment]
Issue ditutup karena kesalahan dalam menginput data dapat diatasi menggunakan fitur edit/update
