### ISSUE TITLE
Permintaan fitur: Sediakan fitur keterangan nama/jam petugas entri/edit data vaksin

### ISSUE THREAD

**Issue by WAHYUDIK** [OpenSID/OpenSID#5149]
### Apa kekurangan yg ingin diatasi?

saat ini ketika petugas melakukan pendataan/entri data vaksin, ada keterangan/info tentang
nama petugas entir/edit
jam entri/edit
seperti halnya yang terjadi pada penduduk

![image](https://user-images.githubusercontent.com/31026980/163104761-b4771059-8571-4a35-908d-5fd999671ebd.png)

### Jelaskan solusi yg diinginkan

ketika petugas melakukan pendataan/entri data vaksin, ada keterangan/info tentang
nama petugas entir/edit
jam entri/edit

seperti halnya yang terjadi pada penduduk
![image](https://user-images.githubusercontent.com/31026980/163104712-97e5f731-e169-401d-b343-91ff86470f84.png)

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

-

### Informasi tambahan

-

**Comment by andifahruddinakas** [comment]
Tidak dikembangkan lagi
