### ISSUE TITLE
Permintaan fitur: [LAYANAN MANDIRI] ditampilkan stasus vaksin

### ISSUE THREAD

**Issue by tobagus6911** [OpenSID/OpenSID#5150]
### Apa kekurangan yg ingin diatasi?

di layanan mandiri warga tidak ditampilkan status layanan mandiri. agar warga yang sudah divaksin dapat mendownload sertifikat vaksinnya melalui layanan mandiri

### Jelaskan solusi yg diinginkan

ingin ada vasilitas download sertifikat vaksin

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

premium 22.05

**Comment by apidong** [comment]
test
