### ISSUE TITLE
Bug/error: Buang Spasi pada Input IP

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#5153]
### Jelaskan error yg dialami

Saat ini jika terdapat spasi karena kesalahan copy/paste ke Pengaturan Kehadiran, akan berdampak pada Gawai Tidak Terdaftar.

### Cara untuk mereplikasi errornya

Beri spasi di awal atau akhir IP, maka tetap muncul Gawai tidak terdaftar.

Namun jika spasi di hapus, maka sukses tampil masuk halaman kehadiran.

### Hasil yg diharapkan

Normal.

### Tangkapan layar dan log error

Tidak ada

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Berputar

**Comment by totoprayogo1916** [comment]
cukup tambahkan `trim()`
ref: https://www.php.net/manual/en/function.trim.php

**Comment by yogiperdana** [comment]
> cukup tambahkan `trim()` ref: https://www.php.net/manual/en/function.trim.php

Terima kasih mas

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melalui pr https://github.com/OpenSID/premium/pull/967
