### ISSUE TITLE
Bug/error: Unduh dan cetak Buku Aparat Pemerintah Desa tidak memunculkan NIK

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#5154]
### Jelaskan error yg dialami

ketika pengguna ingin mencetak atau mengunduh buku Aparat Pemerintah Desa tidak memunculkan NIK (bagi pengguna yang memilih terdata dalam database)

### Cara untuk mereplikasi errornya

pergi ke administrasi desa > administrasi umum > buku aparat pemerintah desa > pilih aksi lainnya > cetak / unduh > lihat hasil tabel NIK

* catatan kepala desa dan aparatur desa harus dari database penduduk

### Hasil yg diharapkan

data NIK muncul

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

website berputar

### Tema Yang Digunakan

-

### Informasi tambahan

-

**Comment by yogiperdana** [comment]
Mohon maaf pak. Untuk di buku aparatur pemerintahan saya lihat memang tidak ada kolom NIK
![image](https://user-images.githubusercontent.com/14155050/163432899-316119a4-2e02-4494-9409-df0b2968b393.png)

Adanya NIP dan NIPD Pak. Dan dapat ditambahkan pada form berikut:
![image](https://user-images.githubusercontent.com/14155050/163433124-0a08e46e-020e-411e-b9ae-297a52457286.png)

**Comment by balongbesuk** [comment]
saya kira NIK
