### ISSUE TITLE
Permintaan fitur: Sediakan Ubah Lokasi Tempat Tinggal Satu keluarga di Peta

### ISSUE THREAD

**Issue by RomziJazz** [OpenSID/OpenSID#5155]
### Apa kekurangan yg ingin diatasi?

Kesulitan ketika Set Lokasi Tempat Tinggal, karena settingnya dari daftar penduduk satu persatu. 

### Jelaskan solusi yg diinginkan

Di Menu Keluarga Sediakan pula Ubah Lokasi Tempat Tinggal di Peta yang otomatis terSet kepada seluruh anggota keluarga.

### Apakah ada alternatif lain

Atau Sediakan menu Simpan untuk seluruh anggota keluarga.

### Untuk versi OpenSID mana

Versi yang akan datang semoga sudah selesai.

**Comment by eddieridwan** [comment]
@RomziJazz sudah lama ada. Perubahan alamat/lokasi keluarga TIDAK dilakukan di Penduduk, tetapi di Keluarga.

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/249563/163321594-bdc5cb9f-cc75-44a7-9a32-7575c5538292.png">

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/249563/163321760-72f0ffd2-2bbc-4d3d-b3a5-12c7f3d37f20.png">

@yogiperdana , mohon ditambahkan ke panduan, mungkin di https://github.com/OpenSID/OpenSID/wiki/Keluarga

**Comment by RomziJazz** [comment]
Saya maksudkan untuk lokasi di Petanya mas. Saya cari gak ketemu soalnya.

**Comment by RomziJazz** [comment]
Saya maksudkan untuk lokasi di Petanya mas, menentukan peta lokasi perkeluarga Saya cari gak ketemu soalnya.

**Comment by yogiperdana** [comment]
> 

Baik pak

**Comment by tobagus6911** [comment]
Sangat setuju👍

**Comment by eddieridwan** [comment]
Bung @yogiperdana , di peta sudah ada pilihan centang lokasi keluarga. Seharusnya fitur itu menampilkan lokasi sesuai yg ada di tabel tweb_keluarga. Jadi sebenarnya yg diperlukan adalah sbb:

1. pada saat memasukkan lokasi peta untuk penduduk, jika penduduk tersebut merupakan anggota keluarga, simpan lokasi peta (lat, lng) tersebut di tabel tweb_keluarga. Demikian juga untuk ubah lokasi peta penduduk. Yaitu, seluruh anggota keluarga akan mempunyai lokasi peta yg sama. 
2. yaitu lokasi peta bagi penduduk hanya disimpan di tabel penduduk bagi penduduk tidak tetap, yaitu yg bukan anggota keluarga
3. sediakan fitur untuk langsung mengubah lokasi peta keluarga di menu Keluarga
4. di peta, pada saat mencentang lokasi keluarga, tampilkan sesuai lat/lng di tabel tweb_keluarga, dan tampilkan info kepala keluarga dan daftar anggota keluarga
5. di peta, pada saat mencentang lokasi penduduk, tampilkan lokasi sesuai dengan lokasi peta keluarga penduduk ybs, kalau ada.

**Comment by andifahruddinakas** [comment]
Duplicate issue https://github.com/OpenSID/OpenSID/issues/5985
