### ISSUE TITLE
Bug/error: Gagal Saat Impor Data Program Bantuan

### ISSUE THREAD

**Issue by rudiansyahyunanda** [OpenSID/OpenSID#5158]
### Jelaskan error yg dialami

gagal saat impor data penerima bantuan pada Program Bantuan. 
muncul pesan error seperti gambar berikut, telah saya coba di Desa lain tetap error, saya coba impor dengan template bawaan sistem tanpa mengubahnya juga gagal.

![image](https://user-images.githubusercontent.com/50880846/163502191-f98d4c5b-a66d-4bf9-8fff-9772bcbf1859.png)

### Cara untuk mereplikasi errornya

1. Pergi Kehalaman Bantuan
2. Impor
3. Browse File Excel yang mau diimpor
4. Simpan
5. Error 500

### Hasil yg diharapkan

Dapat Impor Data Penerima Bantuan pada menu Bantuan dengan Template Excel

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/50880846/163502293-76e24e33-1254-4a34-9d46-cdbd8d025693.png)
![image](https://user-images.githubusercontent.com/50880846/163502371-a65b6696-c792-4cf1-977b-922134238844.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.04-Premium REV-01

### Tema Yang Digunakan

Denatra

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melalui pr https://github.com/OpenSID/premium/pull/968/files
