### ISSUE TITLE
Demo Akun Layanan Mandiri

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/OpenSID#5159]
### Apa kekurangan yg ingin diatasi?

Saat ini akun layanan mandiri pada web berputar dapat ditambahkan, diubah, maupun dihapus oleh pengguna yang melakukan uji coba.

### Jelaskan solusi yg diinginkan

Harapan dari fitur ini adalah ada satu akun yang secara default tidak dapat dirubah seperti halnya akun pengguna admin dengan password sid304. 

Tujuannya adalah: 
1. Sebagai akun demo di layanan mandiri.
2. Sebagai akun demo di aplikasi mobile.

**Comment by ariandii** [comment]
selain mencegah hapus akun layanan mandiri, juga cegah hapus data penduduknya yang terkoneksi dengan data akun layanan mandiri  yang di buat default tersebut.

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/1026

**Comment by andifahruddinakas** [comment]
Untuk akun demo karena bisa saja database yang digunakan berbeda (buka contoh data awal saat ini), asalkan id penduduk yang dijadikan sebagai akun demo tersedia (misalnya: 1, 2, 3). Atau bisa menambahkan pengaturan di desa/config/config.php, sbb:
```
// Data id penduduk dan pin layanan mandiri yang digunakan sebagai default akun demo
$config['demo_akun'] = [
    1 => '123456',
    2 => '234561',
    3 => '345612',
];
```

**Comment by yogiperdana** [comment]
Saran tambahan dari mas @ai-skematik :
1. Hilangkan tombol terkait untuk akun demo (hapus,ubah,reset pin)
2. Buat keterangan pin demo akun di tombol info atau informasi umum
