### ISSUE TITLE
Permintaan fitur: Tambahkan pencarian No KK Sementara

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#5160]
### Apa kekurangan yg ingin diatasi?

belum adanya fitur pencarian No KK Sementara seperti halnya yang ada di menu penduduk > aksi lainnya > NIK sementara

### Jelaskan solusi yg diinginkan

agar memudahkan pencarian No KK sementara di menu keluarga 

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

premium

### Informasi tambahan

sambungan dari #5095 saat ini warna tabel keluarga no KK sementara masih sama dengan tabel keluarga no KK baku

**Comment by andifahruddinakas** [comment]
Silahkan di cek di bagian select Pilih Status KK

![Screenshot_2022-04-16-09-46-16-58.jpg](https://user-images.githubusercontent.com/57283157/163657059-9c5bc93e-064e-47c3-94a5-489433832368.jpg)

**Comment by balongbesuk** [comment]
knp d menu kependudukan tidak d masukkan ke submenu status penduduk juga, karena fungsinya sortir, bukan mencari jd sama dengan sub menu status kk d menu keluarga,
