### ISSUE TITLE
Bug/error: Perbaikan Install Baru Repo Berputar

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#5163]
### Jelaskan error yg dialami

Pertama kali git clone dari repo http://github.com/OpenSID/Berputar maka ketika lakukan /periksa akan muncul tombol perbaiki mengenai database sebegaimana gambar berikut.

<img width="631" alt="image" src="https://user-images.githubusercontent.com/46939846/163721054-b5e65396-9203-4dee-9dc3-5841bdd21273.png">

### Cara untuk mereplikasi errornya

lakukan install opensid premium baru, dan setelah selesai install, langsung masuk /periksa

### Hasil yg diharapkan

Tidak perlu lakukan perbaikan apapun saat pengguna baru melakukan install awal.

### Tangkapan layar dan log error

seperti di atas

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.04-premium-rev01

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melalui pr https://github.com/OpenSID/premium/pull/979
