### ISSUE TITLE
Bug/error: Balik Urutan Tanggal pada Tabel Log Sistem

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#5165]
### Jelaskan error yg dialami

Sering kali pengguna yang mengalami kendala ketika migrasi DB atau update versi opensid sehingga error, maka pengguna akan buka Log di menu Info Sistem.

Saat ini sering pengguna langsung lihat layar awal ketika buka menu Info Sistem. namun tanggal yang tampil adalah tanggal lampau. Bukan log terakhir yang menunjukkan error ketika itu.

### Cara untuk mereplikasi errornya

Lakukan migrasi atau ketika ada error baru, perhatikan di tabel Log di Info Sistem, maka yg tampil adalah tanggal lampau.

### Hasil yg diharapkan

Urutan teratas di baris 1 adalah log terakhir.

### Tangkapan layar dan log error

<img width="960" alt="screenshot_431" src="https://user-images.githubusercontent.com/46939846/163770036-28929378-2058-453a-9451-9974c481c3ed.png">

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.04-premium-beta1 Berputar

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melalui pr https://github.com/OpenSID/premium/pull/976
