### ISSUE TITLE
Bug/error: Perbaiki Ejaan

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#5166]
### Jelaskan error yg dialami

<img width="960" alt="image" src="https://user-images.githubusercontent.com/46939846/163776879-04916777-6b1b-45a5-a36c-bfbd41e732c0.png">

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

Nampaknya tertulis Baut, seharusnya Buat

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Berputar

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melalui pr https://github.com/OpenSID/premium/pull/978
