### ISSUE TITLE
Permintaan fitur: Tambahkan Jenis Surat dengan Kop Logo Burung Garuda

### ISSUE THREAD

**Issue by sutaga** [OpenSID/OpenSID#5167]
### Apa kekurangan yg ingin diatasi?

Jenis surat yang disediakan OpenSID/OpenDesa masih menggunakan Kop Surat dengan logo Kabupaten, sedangkan terdapat Desa dibeberapa Kabupaten yang sudah menggunakan Kop Surat dengan logo Burung Garuda.

### Jelaskan solusi yg diinginkan

Mohon ditambahkan jenis Surat dengan menggunakan Kop logo burung Garuda, supaya kami bisa menggunakan fitur layanan mandiri. Karena sampai saat ini, Desa yang menggunakan kop surat dengan logo garuda belum bisa memanfaatkan fitur tersebut.

### Apakah ada alternatif lain

Terdapat pilihan jenis surat yang akan digunakan, apakah menggunakan kop logo Kabupaten atau kop logo burung Garuda.

### Untuk versi OpenSID mana

Premium v22.05 atau v22.06

### Informasi tambahan

Desa kami yang sudah menggunakan fitur premium sampai saat ini masih belum bisa memanfaatkan surat layanan mandiri, karena adanya perbedaan jenis kop surat yang digunakan. Sangat diharapkan adanya penambahan fitur surat dengan menggunakan kop logo burung garuda.

**Comment by yogiperdana** [comment]
Jenis surat apa saja yang menggunakan kop burung garuda pak @sutaga? Atau apakah yang dimaksud untuk semua surat namun diberikan opsi untuk memilih ingin menggunakan kop lama atau kop burung garuda ini

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/1056

**Comment by sutaga** [comment]
Kalau di Desa kami, hampir semua format surat menggunakan Logo Garuda, dan
berlaku untuk Desa di Kabupaten Sukabumi

Pada tanggal Sen, 23 Mei 2022 08.28, Yogi Perdana ***@***.***>
menulis:

**Comment by sutaga** [comment]
Betul, yang kami harapkan itu ada pilihan jenis Kop Surat, karena untuk
surat yang tersedia di opensid saat ini masih menggunakan Kop Surat dengan
logo Kabupaten, sedangkan untuk Kabupaten Sukabumi sudah menggunakan logo
burung garuda.

Pada tanggal Jum, 27 Mei 2022 16.09, Sutaga Azfan ***@***.***>
menulis:
