### ISSUE TITLE
Bug/error: Dulu Normal, sekarang Link Status IDM belum ditutup </a>

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#5169]
### Jelaskan error yg dialami

Link web kemendesa mengenai status IDM tercipta hingga bawah.
nampaknya ini disebabkan belum ditutupnya </a> pada :
$idm->body->mapData->error_msg

file donjo-app/controllers/Status_desa.php

Atau hal lain yang belum diketahui.

<img width="657" alt="screenshot_446" src="https://user-images.githubusercontent.com/46939846/163961843-2bec054c-2b81-4360-b116-e57dad8f4649.png">

### Cara untuk mereplikasi errornya

Buka status IDM bagi desa yang belum dalam tahap verifikasi
contoh:
https://berputar.opendesa.id/status-idm/2022

### Hasil yg diharapkan

Link hanya batasi pada URL kemendesa saja.

### Tangkapan layar dan log error

Di atas

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.04-premium-rev01

**Comment by yogiperdana** [comment]
Saya coba di berputar aman pak

![image](https://user-images.githubusercontent.com/14155050/164145048-0e36f9f1-c225-46fd-ba63-203625a14bc6.png)

![image](https://user-images.githubusercontent.com/14155050/164145420-bb24a26c-0731-4a23-ae21-7c87ed374504.png)

**Comment by yogiperdana** [comment]
@ariandii

**Comment by ariandii** [comment]
oke, saya cek di berputar sudah diperbaiki.
mungkin persiapan rilis bulan depan.

<img width="648" alt="image" src="https://user-images.githubusercontent.com/46939846/164365891-a2dcfbbe-b4bf-499b-a184-1be9e0c66028.png">
