### ISSUE TITLE
Bug/error: Data Staf Belum nampak di Tabel Pengguna

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#5170]
### Jelaskan error yg dialami

Agar mudah dilihat apakah pengguna perlu ditautkan ke data staf atau tidak.
Jika sudah ditautkan dengan salah satu Data Staf, maka perlu adanya info yang tampil di tabel.

Hal ini agar mudah dalam memastikan apakah sebuah pengguna sudah memiliki Data Staf atau tidak.

(Tidak semua pengguna terhubung dengan Data Staf, namun Data Staf yang ingin memanfaatkan Fitur Kehadiran wajib terkoneksi dengan Akun Pengguna).

<img width="960" alt="image" src="https://user-images.githubusercontent.com/46939846/163971406-ef43c457-05c6-4199-b6eb-d1b6b5702b8a.png">

### Cara untuk mereplikasi errornya

Di atas

### Hasil yg diharapkan

Di atas

### Tangkapan layar dan log error

Di atas

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Berputar

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/1020
