### ISSUE TITLE
Bug/error: Halaman Dashboard Admin Sekarang Berantakan.

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#5171]
### Jelaskan error yg dialami

Bisa coba buka web berputar dan login admin di hp.

![Screenshot_2022-04-20-13-14-21-92_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/46939846/164162622-ffc1f18d-2512-4836-953f-941172e6d4ca.jpg)

![Screenshot_2022-04-20-13-33-51-05_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/46939846/164165341-cec0f7d5-051d-406e-8419-fc6c4fdb28a9.jpg)

### Cara untuk mereplikasi errornya

di atas

### Hasil yg diharapkan

dirapikan kembali seperti sebelumnya.

### Tangkapan layar dan log error

di atas

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Berputar

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melalui pr https://github.com/OpenSID/premium/pull/982
