### ISSUE TITLE
Perhitungan laporan keuangan impor dan manual tidak konsisten setelah perubahan

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#5173]
Cek perubahan dari issue Perhitungan laporan keuangan impor dan manual tidak konsisten setelah perubahan https://github.com/OpenSID/OpenSID/issues/5118

Cek komentar https://github.com/OpenSID/premium/pull/916#issuecomment-1092636857

Bagian yang perlu diperbaiki : 
1. Perhitungan laporan keuangan manual sama dengan laporan keuangan impor
2. Widget keuangan pada bagian kiri tidak konsisten / tidak sama dengan footer keuangan.

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melalui pr https://github.com/OpenSID/premium/pull/986
