### ISSUE TITLE
Bug/error: BUG? https://opendata.arcgis.com/datasets/0c0f4558f1e548b68a1c82112744bad3_0.geojson not found

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#5174]
### Jelaskan error yg dialami

console browser peta memunculkan error buka peta https://berputar.opendesa.id/peta lihat console 404 not found

### Cara untuk mereplikasi errornya

buka peta https://berputar.opendesa.id/peta lihat console

### Hasil yg diharapkan

diperbaiki

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/35319600/164386318-d7e684c4-ce0d-4fa1-89a7-c07b5d5f9c3d.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

premium

### Tema Yang Digunakan

semua tema

### Informasi tambahan

-

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melalui pr https://github.com/OpenSID/premium/pull/995
