### ISSUE TITLE
Bug/error: api.kawalcorona.com sudah tidak ada

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#5175]
### Jelaskan error yg dialami

api.kawalcorona.com sudah tidak ada perlukah d ganti atau d hapus?

### Cara untuk mereplikasi errornya

gak tau fungsinya apa, mungkin berkaitan dengan menu covid19,

### Hasil yg diharapkan

berjalan normal entah fungsiny buat apa

### Tangkapan layar dan log error

![photo6271789551366288180](https://user-images.githubusercontent.com/35319600/164388912-00e4de49-6264-4fe5-9532-e54090c2178f.jpg)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

-

### Tema Yang Digunakan

-

### Informasi tambahan

-

**Comment by eddieridwan** [comment]
![image](https://user-images.githubusercontent.com/249563/164392415-9cb4cbb7-d58d-4c18-9854-2c5a4a0e1347.png)
https://www.facebook.com/groups/OpenSID/posts/2111018302396473/

**Comment by eddieridwan** [comment]
@yogiperdana @andifahruddinakas Jika tidak bisa ditemukan sumber data Covid-19 yg lain, hapus saja fitur terkait, baik di web maupun di peta.

**Comment by yogiperdana** [comment]
Baik pak

**Comment by balongbesuk** [comment]
https://covid19.go.id/dokumentasi-api

ini mungkin?

**Comment by balongbesuk** [comment]
https://api.covid19.bnn.go.id/docs/

atau ini?

**Comment by andifahruddinakas** [comment]
> @yogiperdana @andifahruddinakas Jika tidak bisa ditemukan sumber data Covid-19 yg lain, hapus saja fitur terkait, baik di web maupun di peta.

@yogiperdana

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melalui pr https://github.com/OpenSID/premium/pull/996
