### ISSUE TITLE
Bug/error: BUG? no kk menikah dan tanggal menikah hilang ketika status dasar dirubah menjadi cerai mati

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#5176]
### Jelaskan error yg dialami

arsip no akta nikah seharusnya masih tersimpan sebagai arsip desa tapi malah hilang / tidak tersimpan ketika penduduk dirubah statusnya

### Cara untuk mereplikasi errornya

pergi ke menu kependudukan > ubah data penduduk > status kawin > isi no dan tanggal kawin > simpan > ubah kembali ke status dasar mati > lihat no dan tanggal kawin hilang

### Hasil yg diharapkan

walaupun status dasar berubah no akta kawin tetap tersimpan

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

website berputar

### Tema Yang Digunakan

-

### Informasi tambahan

kemungkinan juga berpengaruh dengan no akta cerai

**Comment by yogiperdana** [comment]
Berjalan seperti hasil yang diharapkan pada Versi 22.04-premium-rev02

**Comment by balongbesuk** [comment]
mohon sekiranya web berputar mengikuti rilis terbaru

**Comment by balongbesuk** [comment]
jika web berputar saat ini adalah versi terbaru maka bug ini masih ada

**Comment by andifahruddinakas** [comment]
> jika web berputar saat ini adalah versi terbaru maka bug ini masih ada

![akta](https://user-images.githubusercontent.com/57283157/165922639-b3809849-a008-4328-ad17-28f19f832a38.png)
![akta1](https://user-images.githubusercontent.com/57283157/165922652-e85dfa0b-37c0-4477-9cf3-203c152a7b6a.png)

Ini tidak ke hapus.

**Comment by andifahruddinakas** [comment]
DI berputar juga sama https://berputar.opendesa.id/penduduk/detail/1/0/1

**Comment by balongbesuk** [comment]
mungkin kalimatny yang kurang jelas, cb saya rubah gini

no akta nikah dan tanggal nikah seharusnya masih tersimpan dalam data penduduk desa tapi data no akta nikah dan tanggal nikah tersebut malah hilang / tidak tersimpan ketika penduduk yang dimaksud dirubah status menjadi cerai hidup / cerai matinya

**Comment by balongbesuk** [comment]
![image](https://user-images.githubusercontent.com/35319600/166095428-aabdf253-f999-4ea7-88a2-92f559d26dec.png)

mencatatkan no akta nikah dan tanggal

**Comment by balongbesuk** [comment]
![image](https://user-images.githubusercontent.com/35319600/166095456-d819bfad-1a6f-4231-bd40-add8db8e0512.png)


ubah status nikah cerai mati / hidup

**Comment by balongbesuk** [comment]
harusnya no akta nikah dan tanggal menikah masih tersimpan walau statusnya berubah

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui commit https://github.com/OpenSID/premium/commit/c3041a9c9a18e8c819d8e1c31352e5703743bf1e
