### ISSUE TITLE
Bug/Error: Data Jumlah Keluarga tidak muncul pada Statistik Penduduk untuk Laporan Bulanan

### ISSUE THREAD

**Issue by sulaimanlawidhub** [OpenSID/OpenSID#5177]
Seharusnya Data Jumlah Keluarga muncul pada Statistik Penduduk untuk Laporan Bulanan. @andifahruddinakas

**Comment by yogiperdana** [comment]
Saya coba muncul pak 

![image](https://user-images.githubusercontent.com/14155050/164699117-4834ce9a-30a3-4d19-b276-7bb6349e3b8e.png)

**Comment by yogiperdana** [comment]
Mohon sertakan tangkapan layar dan informasi versi yang digunakan

**Comment by sulaimanlawidhub** [comment]
![Screenshot_20220422_003020.jpg](https://user-images.githubusercontent.com/92381858/164996936-2860b1f4-ac7c-4664-a684-5af25f4d6333.jpg)

**Comment by sulaimanlawidhub** [comment]
Versi yang digunakan adalah 22.04 rev02

**Comment by balongbesuk** [comment]
nomal, cb d cek data keluarga jgn jgn kosong lg

**Comment by sulaimanlawidhub** [comment]
Harus dicek di tabel mana yah ?

**Comment by sulaimanlawidhub** [comment]
Saya sudah coba juga dengan mengosongkan DB, lalu kemudian mengimpor data penduduk contoh dari berputar, hasilnya sama atau data dimaksud memang tidak muncul.

**Comment by balongbesuk** [comment]
menu kependudukan > keluarga (ada isinya tidak?)

versi 22.04 kl tidak salah ada bug import data penduduk tidak memasukkan data keluarga, mungkin berimbas ke menu statistik ini,

**Comment by sulaimanlawidhub** [comment]
Menu keluarga pada kependudukan ada isinya.

Saat impor data penduduk, data penduduk dan data keluarga terisi jumlah data secara otomatis, hanya saja pada data Laporan Bulanan pada Statistik tidak muncul data jumlah keluarga saja. Mohon solusinya.

**Comment by sulaimanlawidhub** [comment]
> menu kependudukan > keluarga (ada isinya tidak?)
> 
> versi 22.04 kl tidak salah ada bug import data penduduk tidak memasukkan data keluarga, mungkin berimbas ke menu statistik ini,

Menu keluarga pada kependudukan ada isinya.

Saat impor data penduduk, data penduduk dan data keluarga terisi jumlah data secara otomatis, hanya saja pada data Laporan Bulanan pada Statistik tidak muncul data jumlah keluarga saja. Mohon solusinya.

**Comment by sulaimanlawidhub** [comment]
> ![Screenshot_20220422_003020.jpg](https://user-images.githubusercontent.com/92381858/164996936-2860b1f4-ac7c-4664-a684-5af25f4d6333.jpg)

Versi Opensid yang digunakan adalah 22.04 rev02 premium

**Comment by sulaimanlawidhub** [comment]
> Saya coba muncul pak 
> 
> ![image](https://user-images.githubusercontent.com/14155050/164699117-4834ce9a-30a3-4d19-b276-7bb6349e3b8e.png)
> 
Apakah ini dicoba pada berputarkah ?

**Comment by sulaimanlawidhub** [comment]
> Saya coba muncul pak 
> 
> ![image](https://user-images.githubusercontent.com/14155050/164699117-4834ce9a-30a3-4d19-b276-7bb6349e3b8e.png)
> 

Dicoba dimana yah ?

**Comment by balongbesuk** [comment]
Bug ini muncul ketika pengguna baru menginstall opensid > impor data penduduk > pada statistik penduduk > laporan bulanan > jumlah KK tidak ikut terjumlah, 

sedangkan pada buku administrasi penduduk > rekapitulasi jumlah penduduk > jumlah KK muncul 

sy coba telusuri mentok d versi premium-21.08 (entah file opensid premium yang lama ada dimana) yang ternyata hasilnya sama,

**Comment by sulaimanlawidhub** [comment]
> Bug ini muncul ketika pengguna baru menginstall opensid > impor data penduduk > pada statistik penduduk > laporan bulanan > jumlah KK tidak ikut terjumlah, 
> 
> sedangkan pada buku administrasi penduduk > rekapitulasi jumlah penduduk > jumlah KK muncul 
> 
> sy coba telusuri mentok d versi premium-21.08 (entah file opensid premium yang lama ada dimana) yang ternyata hasilnya sama,

Saya juga telah melakukan hal yang sama, hasilnya sama. Hanya saja belum mencoba pada versi opensid umum.

**Comment by balongbesuk** [comment]
versi 21.10 umum

![image](https://user-images.githubusercontent.com/35319600/165200486-046dac1d-9ef7-4168-86e8-709c13fe920e.png)

data KK masuk

**Comment by sulaimanlawidhub** [comment]
Ini menarik. Bagaimana caranya agar versi umum ini digunakan menjadi premium ?

**Comment by sulaimanlawidhub** [comment]
> versi 21.10 umum
> 
> ![image](https://user-images.githubusercontent.com/35319600/165200486-046dac1d-9ef7-4168-86e8-709c13fe920e.png)
> 
> data KK masuk

Ini menarik. Bagaimana caranya agar versi umum ini digunakan menjadi premium ?

**Comment by balongbesuk** [comment]
install awal aja yg umum upload data penduduk beres semua kmudian upgrade k premium

**Comment by balongbesuk** [comment]
![image](https://user-images.githubusercontent.com/35319600/165244129-17a217ca-5439-4ab5-9321-006460082e0c.png)

versi 21.11 umum masuk

**Comment by balongbesuk** [comment]
![image](https://user-images.githubusercontent.com/35319600/165245441-0d77b25d-f977-45ff-881e-71564f1b24a1.png)


mulai bug disini 21.12

**Comment by andifahruddinakas** [comment]
> ![image](https://user-images.githubusercontent.com/35319600/165245441-0d77b25d-f977-45ff-881e-71564f1b24a1.png)
> 
> mulai bug disini 21.12

@yogiperdana

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melalui pr https://github.com/OpenSID/premium/pull/1077
