### ISSUE TITLE
Permintaan fitur: Penambahan Jenis Pilihan Tombol Keluar di Fitur Kehadiran Perangkat dan Rekapitulasi

### ISSUE THREAD

**Issue by Wiliyantoro** [OpenSID/OpenSID#5178]
### Apa kekurangan yg ingin diatasi?

belum tersedianya pilihan keluar : 
1. Kategori Keluar Karena Waktunya sudah Keluar
2. Kategori Keluar Karena Alasan Lain misal : Keluar Karena Melakukan Perjalanan Dinas.
3. Perangkat yang sama sekali tidak melakukan Absen Masuk dan Absen Keluar tidak terdata di Rekapitulasi

Kategori di atas akan nyambung dengan Laporan Rekapitulasi Kehadiran pada Status Kehadiran yang mana akan menjadi evaluasi Kades terhadap kinerja kehadiran perangkat

### Jelaskan solusi yg diinginkan

1. tambahkan kategori keluar di halaman absensi
2. tambahkan di rekapitulasi perangkat yang tidak melakukan absen ( masuk dan keluar ) dengan status kehadiran : Tidak Masuk

### Apakah ada alternatif lain

ataupun tidak memungkinkan ditambahkan kategori keluar, bisa menambahkan menu edit kehadiran untuk merubah status kehadiran.

### Untuk versi OpenSID mana

v22.05-premium

### Informasi tambahan

walaupun fitur kehadiran perangkat bukan seperti aplikasi absensi , namun sangat di apresiasi oleh bapak kades kami, harapan beliau agar nantinya fitur kehadiran perangkat ini bisa dijadikan absensi perangkat secara digital. agar kami tidak perlu lagi keluar anggaran untuk pengadaan software absensi, cukup jadi 1 data 1 aplikasi
link forum : https://forum.opendesa.id/d/131-penambahan-jenis-pilihan-tombol-keluar-di-fitur-kehadiran-perangkat

**Comment by ahmadfarhan91** [comment]
Smoga dpt d tambahkan

**Comment by Pematung** [comment]
Saya setuju kalau fitur ini di masukkan ke Rilis OpenSID berikutnya

**Comment by yogiperdana** [comment]
Untuk poin nomor 2 maksudnya ada beberapa alasan atau status kah pak @Wiliyantoro ? Aapakah bisa dibuatkan satu alasan yang umum yang bisa meng-_cover_ semua status selain keluar karena sudah waktunya.

**Comment by Wiliyantoro** [comment]
Point no 2 pk yogi, 
1. di rekapitulasi apabila tidak melakukan in dan out pada tanggal tersebut (hari ini) maka di anggap tidak masuk/alpha.
2. Jika point pertama sudah bisa, maka pada kolom status ambil pilihan/alasan keluar.
3. Jika lupa keluar pada jam kerja , maka otomatiskan rubah status masuk ke lupa lapor keluar 5 jam setelah jam keluar, karena pada versi ini status masuk/ada di kantor desa jika lupa keluar , masih terlihat masuk / ada di kantor desa esok harinya apabila perangkat belum melakukan check in pada hari besoknya.

**Comment by yogiperdana** [comment]
1. Baik pak nanti saya cek
2. Jadi untuk alasan keluar pilihannya ada apa saja pak? Atau alasannya diketik manual pak pak @Wiliyantoro?
3. Ini bisa dilakukan apabila desa mengaktifkan cron job di serve masing masing pak. Sepertinya poin no 3 akan dibuatkan di issue terpisah

**Comment by Wiliyantoro** [comment]
Jika keluar pada saat jam kerja maka munculkan pilihan : 
1. Keluar ada keperluan dinas
2. Keluar karena pulang lebih awal.

Catatan: mungkin jika ada masukan dari rekan rekan yang lain bagaimana enaknya, sediakan tombol atau isi manual.

Sediakan hak administrator untuk rubah keterangan kehadiran apabila orang tersebut keluar namun tidak check out, mungkin ini nanti perlu dibuatkan issue,

Keuntungan dan manfaat fitur ini, selain untuk presensi kehadiran perangkat, nantinya dapat digunakan sebagai absensi untuk kantor desanya. Tergantung apa dan bagaimana komunitas menanggapi tentang fitur ini,

**Comment by yogiperdana** [comment]
Baik pak. Jika masih ada saran atau masukkan boleh dibagikan lagi ya pak

**Comment by Wiliyantoro** [comment]
Kalau ijin atau sakit bisa ditambahkan di fitur ini pak,? melihat fungsi fitur ini hanya presensi kehadiran, bukan absensi.

**Comment by yogiperdana** [comment]
> Kalau ijin atau sakit bisa ditambahkan di fitur ini pak,? melihat fungsi fitur ini hanya presensi kehadiran, bukan absensi.

Sepertinya ini bukan tujuan awal dari pembuatan fitur ini pak namun akan saya coba diskusikan terlebih dahulu pak. Yang pasti nanti akan dikerjakan di issue terpisah

**Comment by yogiperdana** [comment]
Mas @vickyrolanda mohon diikuti juga pembahasan terkait fitur kehadiran ini karena beberapa permintaan fitur yang dibahas dan perlu dilakukan analisis lebih lanjut

**Comment by yogiperdana** [comment]
Issue ini ditangguhkan sementara untuk dibahas lebih lanjut terkait status baku alasan keluar

**Comment by yogiperdana** [comment]
Dan untuk permintaan rekapitulasi rekapitulasi perangkat yang tidak melakukan absen ( masuk dan keluar ) dengan status kehadiran Tidak Masuk dan permintaan penyesuaian perangkat yang lupa checkout akan dibuatkan issue masing-masing

Tambahan:
Untuk penyesuaian perangkat yang lupa checkout disediakan beberapa alternatif seperti ketika admin opensid login / ketika ada pengunjung di luar jam kerja maka perangkat yang statusnya hadir akan diganti dengan lupa absen keluar

**Comment by yogiperdana** [comment]
Sementara itu issue ini fokus pada pembahasan alasan keluar

**Comment by vickyrolanda** [comment]
mas @yogiperdana , untuk alasan keluar ini apakah di tambah saja seperti ini : 

Diatas tombol keluar terdapat Select Option :
 -  Keluar Pulang
 -  Keluar Lainnya
     ketika pilih ini maka muncul text inputan
 - lalu klik tombol keluar.

- Sehingga bawaan yang terpilih keluar pulang tapi kalo mau di pilih keluar lainnya tinggal di ketik aja keluar kemana.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1359
