### ISSUE TITLE
Permintaan fitur: Sediakan Daftar Kontak Penduduk

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#5179]
### Apa kekurangan yg ingin diatasi?

Belum ada Tabel Daftar Kontak Penduduk.

<img width="960" alt="screenshot_536" src="https://user-images.githubusercontent.com/46939846/164708515-1bc2e034-1684-40d9-85f1-594be7284554.png">

### Jelaskan solusi yg diinginkan

Selain tabel daftar Kontak External, juga tersedia tabel khusus penduduk yang sudah memiliki kontak.

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

v22.05-premium

**Comment by andifahruddinakas** [comment]
https://github.com/OpenSID/OpenSID/issues/4727

**Comment by yogiperdana** [comment]
Daftar kontak penduduk artinya kontaknya ditambahkan seperti daftar kontak eksternal dengan memilih nama penduduk namun telepon dan telegram sudah otomatis terisi begitu pak @ariandii ?

**Comment by ariandii** [comment]
tidak,
tetapi penduduk yang sudah memiliki kontak akan muncul di daftar tersebut. 

jadi tidak hanya non penduduk saja yang ber tabel.

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/1049
