### ISSUE TITLE
Permintaan fitur: icon waktu posting artikel hilang

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#5180]
### Jelaskan error yg dialami

seingat saya disamping pengaturan tanggal posting juga ada pengaturan waktu posting

### Cara untuk mereplikasi errornya

menu admin web > tambah artikel > perhatikan pop up tanggal posting > logo waktu posting hilang

### Hasil yg diharapkan

waktu posting muncul kembali

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/35319600/164878750-5307c927-2c24-4ba3-868f-6ab4af8da612.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

website berputar

### Tema Yang Digunakan

-

### Informasi tambahan

-

**Comment by yogiperdana** [comment]
Setelah dicari beberapa bulan kebelakang kami tidak menemukan adanya fitur/icon tesebut. Jadi issue ini kami ubah ke permintaan fitur

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1145
