### ISSUE TITLE
Permintaan fitur: Tambahkan NoIndex pada Halaman kehadiran

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#5182]
### Apa kekurangan yg ingin diatasi?

header meta halaman kehadiran tidak ada informasi membolehkan robot mengindex halaman atau tidak

### Jelaskan solusi yg diinginkan

tambahkan

`<meta name="robots" content="noindex">`

agar halaman kehadiran tidak terindex oleh google

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

Premium

### Informasi tambahan

halaman kehadiran hanya merekam kehadiran perangkat bukan informasi yang bermanfaat untuk d index oleh google

**Comment by andifahruddinakas** [comment]
Sudah di tambahkan, cek view-source:https://berputar.opendesa.id/kehadiran/masuk
