### ISSUE TITLE
Bug/error: Tampilan Persetujuan Penggunaan OpenSID memperlihatkan \n

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#5183]
### Jelaskan error yg dialami

Pada install awal, peringatan Persetujuan Penggunaan OpenSID menampilkan karakter yg tidak seharusnya tampil.
Dan tombol Tidak tidak me-logout pengguna.

### Cara untuk mereplikasi errornya

1. Install dari awal
2. Buka menu Kependudukan > Penduduk atau menu lain yg akan memicu ditampilkannya peringatan
3. Perhatikan pesan Persetujuan Penggunaan OpenSID yg tampil
4. Terlihat kode newline `\n`, seharusnya tidak
5. Kemudian klik tombol Tidak. 
6. Kembali ke dashboard admin, seharusnya logout

### Hasil yg diharapkan

1. Karakter tidak diinginkan tidak tampil.
2. Jika pengguna tidak setuju, maka pengguna di-logout.

### Tangkapan layar dan log error

<img width="1300" alt="image" src="https://user-images.githubusercontent.com/249563/164949052-074c5f38-ee00-46c2-b43f-8ff990e7ccd6.png">

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.04-premium

### Tema Yang Digunakan

Esensi

**Comment by yogiperdana** [comment]
Buatkan tampilan untuk mengakomodasi view yang menggunakan blade engine

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melalui pr https://github.com/OpenSID/premium/pull/1005
