### ISSUE TITLE
[V22.04 PREMIUM-REV02] Pilih atau Penanda Lokasi Penduduk dan Keluarga Pada Peta 

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#5184]
### Jelaskan error yg dialami

Saat memilih legenda letak lokasi penduduk pada peta;
1. Pilihan Penanda lokasi penduduk atau lokasi keluarga --> peta tidak merespon untuk menampilkan lokasi penduduk atau letak suatu Kepala Kelurga
2. Setelah Diklik Untuk Memilih salah satu dari lokasi penduduk peda peta menu legendanya menjadi macet 

### Cara untuk mereplikasi errornya

1. Buka Menu Penduduk --> Pilih salah satu penduduk tentukan lokasi letak penduduk tersebut di peta desa.
2. Buka Fitur Peta pada Halaman Admin --> Klik Salah Ketegori yg diingin pada menu legenda peta. 

### Hasil yg diharapkan

Supaya dapat memilih dan menampilkan lokasi penduduk serta data penduduk normal kembali seperti biasanya.

### Tangkapan layar dan log error

1. Saat Memilih Legenda letak lokasi penduduk -->Peta Tidak Menampilkan letak lokasi yg diinginkan.

![image](https://user-images.githubusercontent.com/64481641/164996085-c6d9a9b6-526a-4871-b388-35b0b9492686.png)

2. Setelah tidak menampilkan data, di klik ulang kembali --> Fitur Legenda sudah macet

![image](https://user-images.githubusercontent.com/64481641/164996142-045f304f-e731-4bff-ad41-a573acbd74ad.png)

Log Error :
Severity: error --> Exception: Too few arguments to function First::status_idm(), 0 passed in /home/teupinbe/public_html/vendor/codeigniter/framework/system/core/CodeIgniter.php on line 533 and exactly 1 expected /home/teupinbe/public_html/donjo-app/core/MY_Security.php(226) : eval()'d code(1) : ev
l()'d code 558

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

OpenSID V22.04-premium-rev02

### Tema Yang Digunakan

Halaman Admin

### Informasi tambahan

.

**Comment by khiar-rara** [comment]
![image](https://user-images.githubusercontent.com/74307159/165016310-bc3f27cc-478a-4ae7-948b-7033dd878bd3.png)
aman aman saja bang

**Comment by Zoel-WB** [comment]
Test input atau masukkan data baru, bukan dari data yg sudah ada utuk ditampilkan, cara mereplikasi error (1).

**Comment by khiar-rara** [comment]
input baru aman. kalau penduduk yang belum ada titik koordinatnya memang ga ada hasilnya tapi peta dan fitur aman aman saja.

**Comment by khiar-rara** [comment]
ehh, jadi inget bang. bulan lalu disaya sempat error juga, control panel legenda di klik ngga jadi. di maps.php yang load fitur pencarian saya kunci pakai div langsung aman. kalau masalah yang kakak alami berbeda mohon maaf

**Comment by balongbesuk** [comment]
d sy normal, cb d test d website berputar

**Comment by yogiperdana** [comment]
Saya coba di berputar aman pak @Zoel-WB

**Comment by Zoel-WB** [comment]
> Saya coba di berputar aman pak @Zoel-WB

Apaka mungkin database saya, tapi pilih periksan aman tidak menampilkan informasi kesalahan, coba saya restore data sebelum update dulu berarti.. bila yg lain aman issue ini dapat close pak @yogiperdana

**Comment by yogiperdana** [comment]
Baik pak @Zoel-WB. Mohon konfirmasi apabila masih terjadi kesalahan

**Comment by Zoel-WB** [comment]
System saya sekarang mungkin setelah update nanti baru dapat disimpulkan kalau sekarang kondisi di lokasi penduduk dalam TDK optimal, saya coba restore dari database masih belum respon...

**Comment by yogiperdana** [comment]
Issue di close karena bug tidak dapat direpliaksi. Silahkan menghubungi lagi apabila masih terjadi masalah
