### ISSUE TITLE
Bedakan tampilan informasi dan isi data perincian pada legenda peta untuk penduduk dan keluarga

### ISSUE THREAD

**Issue by sulaimanlawidhub** [OpenSID/OpenSID#5185]
Tampilan informasi dan isi data perincian pada legenda peta seharus perlu berbeda untuk pilihan penduduk dan keluarga pada legenda peta. Khusus untuk data yang ditampilkan pada legenda keluarga agar yang ditampilkan informasi tentang jumlah anggota keluarga, sehingga saat perincian dibuka agar langsung masuk pada rincian anggota keluarga.

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/OpenSID/pull/7403
