### ISSUE TITLE
Bug/error: Kosongkan DB, jam kerja pada modul kehadiran juga terhapus

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#5187]
### Jelaskan error yg dialami

Saat melakukan Kosongkan DB, jam kerja pada modul kehadiran juga terhapus.

### Cara untuk mereplikasi errornya

Buka pengaturan > database > kosongkan DB

### Hasil yg diharapkan

data jam kerja pada modul kehadiran tidak terhapus

### Tangkapan layar dan log error

...

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.04

### Tema Yang Digunakan

bawaan

### Informasi tambahan

.

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melalui pr https://github.com/OpenSID/premium/pull/998
