### ISSUE TITLE
Bug/error: Setelah periksa/perbaiki kesalahan database, migrasi mulai dari awal

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#5189]
### Jelaskan error yg dialami

Pada database yg berisi kesalahan yg terdeteksi oleh fitur Periksa, setelah diperiksa/perbaiki, terjadi error, karena migrasi dijalankan dari awal, bukan dari versi database.

### Cara untuk mereplikasi errornya

1. Sengaja gunakan database yang berisi error yg terdeteksi, seperti tidak ada autoincrement pada suatu tabel.
2. Buku OpenSID, supaya error tersebut terdeteksi
3. Setelah masuk ke fitur Periksa, tekan tombol Perbaiki
4. Akan terjadi error, yg terjadi karena migrasi mulai dari awal. 

### Hasil yg diharapkan

Migrasi dilakukan dari versi sesuai dengan error yang terdeteksi.

### Tangkapan layar dan log error

<img width="1300" alt="image" src="https://user-images.githubusercontent.com/249563/165156802-3400dd4f-2fee-438c-b504-4e45bfe6b428.png">

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.04-premium-beta02

### Informasi tambahan

Sepertinya masalah ini timbul karena penggunaan cache untuk setting aplikasi, pada function `setting()` di donjo-app/helpers/general_helper.php.

Penggunaan cache untuk setting sepertinya riskan, seperti terlihat untuk setting `current_version` yang seharusnya diubah jika nilainya diganti di tabel `setting_aplikasi`.

**Comment by eddieridwan** [comment]
@andifahruddinakas @agungsugiarto kalau saya kembalikan ke versi v22.04-premium, nomor versi mulai migrasi betul. 

Tetapi setelah melakukan perbaiki, ada error seperti di bawah.

<img width="1260" alt="image" src="https://user-images.githubusercontent.com/249563/165166559-5e0781e6-39db-4df2-85e0-750efc95e737.png">

Apakah masalah di sistem saya?  Saya tidak bisa menemukan penyebabnya.

**Comment by andifahruddinakas** [comment]
> @andifahruddinakas @agungsugiarto kalau saya kembalikan ke versi v22.04-premium, nomor versi mulai migrasi betul. 
> 
> Tetapi setelah melakukan perbaiki, ada error seperti di bawah.
> 
> <img width="1260" alt="image" src="https://user-images.githubusercontent.com/249563/165166559-5e0781e6-39db-4df2-85e0-750efc95e737.png">
> 
> Apakah masalah di sistem saya?  Saya tidak bisa menemukan penyebabnya.

Semalam sudah digabung pak @eddieridwan, tidak lg menggunakan cache untuk helper setting() krn mmqng ada masalah dr penggunaan cache tsb.

**Comment by eddieridwan** [comment]
@andifahruddinakas masih error, setelah git pull rilis-dev

<img width="1300" alt="image" src="https://user-images.githubusercontent.com/249563/165185507-985408a6-6a30-47c5-a5de-e1713d9001ce.png">

**Comment by agungsugiarto** [comment]
Mas @andifahruddinakas, sepertinya dua pemeriksaan ini tidak menyertakan data versi?

https://github.com/OpenSID/premium/blob/0c29c07e6410a6a3a0c0cb112105683ce7f7933e/donjo-app/models/Periksa_model.php#L178-L193

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/OpenSID/issues/5189
