### ISSUE TITLE
Share ke Facebook tidak sinkron judul artikel, artikel dan gambar utama - versi 2.2

### ISSUE THREAD

**Issue by afri18** [OpenSID/OpenSID#519]
kenapa nggak sinkron antara judul artikel, artikel dan gambar utama saat membagikan artikel ya ??
mohon solusi, padahal sebelumnya lancar jaya saat bagi artikel di medsos
![image](https://user-images.githubusercontent.com/6611881/28499979-6af84202-6feb-11e7-88f5-588a036fdd7e.png)

**Comment by telo99** [comment]
Mungkin bisa ditambahkan meta tag deskripsi di header (kalo nggak salah ada di themes)
meta property="og:description"
Seperti contoh di https://developers.facebook.com/docs/plugins/share-button
#MaafNggakBisaCoding :)

**Comment by metalab25** [comment]
Tinggal tambahkan aja meta tag desciption di filr header

**Comment by metalab25** [comment]
Sepulang dari jakarta issue ini saya ga

**Comment by metalab25** [comment]
Sepulang dari jakarta issue ini saya garap

**Comment by MUHAMMADRANGSEL** [comment]
ya saya juga begitu modelnya

**Comment by MUHAMMADRANGSEL** [comment]
jadi bikin tidak enak dilihat

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
