### ISSUE TITLE
Bug/Error: Pada statistik penduduk > laporan bulanan > jumlah KK tidak ikut terjumlah.

### ISSUE THREAD

**Issue by sulaimanlawidhub** [OpenSID/OpenSID#5190]
Bug ini muncul ketika pengguna baru menginstall opensid > impor data penduduk > pada statistik penduduk > laporan bulanan > jumlah KK tidak ikut terjumlah, sedangkan pada buku administrasi penduduk > rekapitulasi jumlah penduduk > jumlah KK muncul.

**Comment by balongbesuk** [comment]
tidak perlu membuat issue ulang

duplicate #5177
