### ISSUE TITLE
Bug/error: Tidak bisa mengirim kode OTP Telegram

### ISSUE THREAD

**Issue by Wiliyantoro** [OpenSID/OpenSID#5191]
### Jelaskan error yg dialami

saat submit kirim OTP telegram verifikasi Layanan Mandiri tidak bisa menerima Kode OTP

### Cara untuk mereplikasi errornya

GuzzleHttp\Exception\ClientException: Client error: POST https://api.telegram.org/botxxxxxxx:xxxxxxxxxxxxxxx/sendMessage resulted in a 400 Bad Request response:
{"ok":false,"error_code":400,"description":"Bad Request: chat not found"} in /home/batungsel.desa.id/public_html/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113Stack trace:#0 /home/batungsel.desa.id/public_html/vendor/guzzlehttp/guzzle/src/Middleware.php(69): GuzzleHttp\Exception\RequestException::create()#1 /home/batungsel.desa.id/public_html/vendor/guzzlehttp/promises/src/Promise.php(204): GuzzleHttp\Middleware::GuzzleHttp{closure}()#2 /home/batungsel.desa.id/public_html/vendor/guzzlehttp/promises/src/Promise.php(153): GuzzleHttp\Promise\Promise::callHandler()#3 /home/batungsel.desa.id/public_html/vendor/guzzlehttp/promises/src/TaskQueue.php(48): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise{closure}()#4 /home/batungsel.desa.id/public_html/vendor/guzzlehttp/promises/src/Promise.php(248): GuzzleHttp\Promise\TaskQueue->run()#5 /home/batungsel.desa.id/public_html/vendor/guzzlehttp/promises/src/Promise.php(224): GuzzleHttp\Promise\Promise->invokeWaitFn()#6 /home/batungsel.desa.id/public_html/vendor/guzzlehttp/promises/src/Promise.php(269): GuzzleHttp\Promise\Promise->waitIfPending()#7 /home/batungsel.desa.id/public_html/vendor/guzzlehttp/promises/src/Promise.php(226): GuzzleHttp\Promise\Promise->invokeWaitList()#8 /home/batungsel.desa.id/public_html/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending()#9 /home/batungsel.desa.id/public_html/vendor/guzzlehttp/guzzle/src/Client.php(187): GuzzleHttp\Promise\Promise->wait()#10 /home/batungsel.desa.id/public_html/vendor/guzzlehttp/guzzle/src/ClientTrait.php(95): GuzzleHttp\Client->request()#11 /home/batungsel.desa.id/public_html/donjo-app/libraries/Telegram/Telegram.php(202): GuzzleHttp\Client->post()#12 /home/batungsel.desa.id/public_html/donjo-app/libraries/Telegram/Telegram.php(164): Telegram->sendRequest()#13 /home/batungsel.desa.id/public_html/donjo-app/libraries/OTP/Repository/OTP_telegram.php(81): Telegram->sendMessage()#14 /home/batungsel.desa.id/public_html/donjo-app/core/MY_Security.php(226) : eval()'d code(1) : eval()'d code(123): OTP_telegram->kirim_otp()#15 /home/batungsel.desa.id/public_html/vendor/codeigniter/framework/system/core/CodeIgniter.php(533): Verifikasi->kirim_otp_telegram()#16 /home/batungsel.desa.id/public_html/index.php(294): require_once('/home/batungsel...')#17 {main}Next CouldNotSendNotification: Telegram responded with an error 400 - Bad Request: chat not found in /home/batungsel.desa.id/public_html/donjo-app/libraries/Telegram/Exceptions/CouldNotSendNotification.php:62Stack trace:#0 /home/batungsel.desa.id/public_html/donjo-app/libraries/Telegram/Telegram.php(205): CouldNotSendNotification::telegramRespondedWithAnError()#1 /home/batungsel.desa.id/public_html/donjo-app/libraries/Telegram/Telegram.php(164): Telegram->sendRequest()#2 /home/batungsel.desa.id/public_html/donjo-app/libraries/OTP/Repository/OTP_telegram.php(81): Telegram->sendMessage()#3 /home/batungsel.desa.id/public_html/donjo-app/core/MY_Security.php(226) : eval()'d code(1) : eval()'d code(123): OTP_telegram->kirim_otp()#4 /home/batungsel.desa.id/public_html/vendor/codeigniter/framework/system/core/CodeIgniter.php(533): Verifikasi->kirim_otp_telegram()#5 /home/batungsel.desa.id/public_html/index.php(294): require_once('/home/batungsel...')#6 {main}

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/44520382/165217107-5749c6c9-cc05-475b-8b20-b91a287219f0.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.04-premium-rev02

### Tema Yang Digunakan

Denatra v.6

### Informasi tambahan

tapi untuk notifikasi login / pemberitahun tampil biasa
![image](https://user-images.githubusercontent.com/44520382/165217331-71016d32-435e-4f6a-91ae-bcdf1f1a615a.png)

https://forum.opendesa.id/d/160-verifikasi-telegram-layanan-mandiri

**Comment by yogiperdana** [comment]
Saya coba di berputar berhasil mas. Pastikan sudah mengikuti langkah ini 
![image](https://user-images.githubusercontent.com/14155050/165432507-111b4156-dfc4-4f3c-ab7f-56048430c349.png)

https://github.com/OpenSID/OpenSID/wiki/Pendaftaran-Layanan-Mandiri-Online#pengaturan-konfigurasi-telegram

**Comment by yogiperdana** [comment]
Pastikan sudah membuat bot telegram dan mengcopy tokennya ke pengaturan aplikasi

**Comment by Wiliyantoro** [comment]
Sudah di pengaturan aplikasi sudah seting bot nya, kalau pun salah,, notifikasi di group telegram bisa

**Comment by Wiliyantoro** [comment]
Notifikasi loginnya berjalan, cuma kirim kode otp saja bermasalah

**Comment by yogiperdana** [comment]
Apakah sudah dicoba di berputar?

**Comment by yogiperdana** [comment]
coba di berputar dulu mas nanti mohon konfirmasi bagaimana hasilnya

**Comment by yogiperdana** [comment]
Issue ini ditutup karena tidak bisa direplikasi
