### ISSUE TITLE
Bug/error: Notifikasi saat kembalikan ke pengaturan default server selalu error

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#5192]
### Jelaskan error yg dialami

Saat mengembalikan pengaturan default server, notifikasi yang ditampilkan selalu error.

### Cara untuk mereplikasi errornya

1. Buka modul pengturan > modul
2. Atur terlebih dahulu menjadi : 
- 
![aturan error](https://user-images.githubusercontent.com/57283157/165228655-26acc225-d517-4e68-8e9e-d3b0cabfc144.png)
3. Simpan
4. Kemudian tekan tombol kembalikan ke default penggunaan server
5. Akan muncul pesan error

### Hasil yg diharapkan

Pesan error menyesuaikan dari hasil yang dilakukan.

### Tangkapan layar dan log error

![error modul default](https://user-images.githubusercontent.com/57283157/165228872-a430601c-0428-40bd-84a3-bb8c5e073585.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.04-premium-rev02

### Tema Yang Digunakan

bawaan

### Informasi tambahan

.

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melalui pr https://github.com/OpenSID/premium/pull/1004
