### ISSUE TITLE
Bug/error: error ketika klik bantuan pada layanan mandiri

### ISSUE THREAD

**Issue by yogiperdana** [OpenSID/OpenSID#5194]
### Jelaskan error yg dialami

ketika klik menu bantuan diarahkannya ke perangkat

### Cara untuk mereplikasi errornya

Login halaman mandiri dan klik bantuan

### Hasil yg diharapkan

berjalan normal

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.04

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melalui pr https://github.com/OpenSID/premium/pull/1009
