### ISSUE TITLE
Bug/error: tampilan 404 saat membuka pesan

### ISSUE THREAD

**Issue by apidong** [OpenSID/OpenSID#5195]
### Jelaskan error yg dialami

tidak bisa melihat pesan.

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/20056421/165550329-8d49b6d8-879f-4851-b2c1-1ee72272df0b.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

22.05.beta2

**Comment by andifahruddinakas** [comment]
https://github.com/OpenSID/premium/pull/1007

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melalui pr https://github.com/OpenSID/premium/pull/1012
