### ISSUE TITLE
Bug/error: Header halaman admin di berputar belum responsive

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#5196]
### Jelaskan error yg dialami

![Uploading Screenshot_2022-04-27-23-57-35-03_40deb401b9ffe8e1df2f1cc5ba480b12.jpg…]()

### Cara untuk mereplikasi errornya

adanya icon sinkron opendk di header membuat tampilan admin di hp menjadi rusak.

### Hasil yg diharapkan

normal kembali

### Tangkapan layar dan log error

di atas

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Berputar

**Comment by yogiperdana** [comment]
Mohon untuk upload ulang tangkapan layarnya pak. Di saya tangkapan layarnya tidak terbaca

**Comment by ariandii** [comment]
![Screenshot_2022-04-27-23-57-35-03_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/46939846/165665527-b9a68ece-ecad-426c-bf6b-33f2a024a929.jpg)

**Comment by ariandii** [comment]
turun ke bawah. tidak sejajar tombol menu kiri atas

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melalui pr https://github.com/OpenSID/premium/pull/1014

**Comment by ariandii** [comment]
![Screenshot_2022-05-06-01-52-12-81_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/46939846/166983474-f13cb9e1-99d6-48af-b7ad-02cd27ed57e5.jpg)

![Screenshot_2022-05-06-01-52-27-61_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/46939846/166983502-9bc77ee9-d0f0-49ff-948e-1d95dd03382c.jpg)
