### ISSUE TITLE
Bug/error: Gagal simpan pemudik non domisili pada modul siaga covid-19

### ISSUE THREAD

**Issue by Restony33** [OpenSID/OpenSID#5198]
### Jelaskan error yg dialami

Gagal menyimpan data pemudik non domisili pada modul siaga covid-19. Akun log out saat simpan data. saat login kembali muncul seperi gambar berikut :
![Screenshot_2022-04-29-01-51-11-02](https://user-images.githubusercontent.com/104592011/165825579-cdf90359-e906-4e73-9fbc-97f1d2a94cee.png)

### Cara untuk mereplikasi errornya

Error saat simpan data

### Hasil yg diharapkan

Berjalan normal saat simpan data pemudik non domisili pada modul siaga covid-19

### Tangkapan layar dan log error

![Screenshot_2022-04-29-01-51-11-02](https://user-images.githubusercontent.com/104592011/165825789-e4b79f8b-2977-40c0-b3e9-c73ec992b100.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.04-premium

**Comment by agungsugiarto** [comment]
Pak @Restony33 terima kasih sudah melaporkan issue,  bisa minta tolong untuk mengunggah file log tersebut? terima kasih

**Comment by Restony33** [comment]
[log-2022-05-09.zip](https://github.com/OpenSID/OpenSID/files/8649143/log-2022-05-09.zip)

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/1021
