### ISSUE TITLE
Permintaan fitur: Matikan modul openDK logo di nav masih muncul

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#5202]
### Apa kekurangan yg ingin diatasi?

tidak semua desa d kecamatannya menggunakan opendk, sehingga fitur ini seharusnya dinamis bisa d aktifkan dan nonaktikan,

### Jelaskan solusi yg diinginkan

ketika modul opendk di matikan pada menu sudah benar disembunyikan tetapi logo komunikasi dengan opendk d NAV masih ada seharusnya ikut dihilangkan

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

berputar

### Informasi tambahan

-

**Comment by balongbesuk** [comment]
apa mungkin ini bug?

**Comment by agungsugiarto** [comment]
Saya tidak menemukan masalah yg dimaksud?

<img width="341" alt="image" src="https://user-images.githubusercontent.com/10989147/167535052-ee8d698a-c4c9-450d-a101-01e87cbd36d9.png">

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/1043
