### ISSUE TITLE
Perbaiki fitur tampilan lokasi penduduk pada peta agar tampil benar khususnya untuk lokasi yang letak antar titik berdekatan.

### ISSUE THREAD

**Issue by sulaimanlawidhub** [OpenSID/OpenSID#5203]
Tampilan lokasi penduduk pada peta tampil belum benar khususnya untuk lokasi penduduk yang letak antar titik berdekatan.![IMG_20220502_211955.jpg](https://user-images.githubusercontent.com/92381858/166241254-23f83e83-915a-4a28-8066-4eb4c819034e.jpg)

**Comment by andifahruddinakas** [comment]
Sudah disesiakan pengaturan min dan max zoom pada peta.
