### ISSUE TITLE
Bug/error: foto di menu penduduk dan gambar lokasi di menu peta pecah di opensid v 22.05 premium

### ISSUE THREAD

**Issue by makhbub** [OpenSID/OpenSID#5204]
### Jelaskan error yg dialami

Foto penduduk yg sudah diunggah tidak dapat tampil di opensid versi terbaru(22.05 premium) begitu juga dengan gambar titik lokasi pada menu pemetaan

### Cara untuk mereplikasi errornya

Upload foto penduduk di menu kependudukan atau gambar titik lokasi di menu pemetaan pada opensid v 22.04 premium
Kemudian update opensid ke versi 22.05 premium
Kemudian cek apakah gambarnya masih bisa tampil

### Hasil yg diharapkan

Bug tersebut diperbaiki, karena apabila harus mengunggah ulang akan sangat makan waktu, menginggat banyaknya gambar yg sudah diunggah

### Tangkapan layar dan log error

![IMG_20220503_112202_869](https://user-images.githubusercontent.com/38773660/166404387-8bde6c32-6944-4e03-a525-7f4d926667a7.jpg)
![IMG_20220503_112209_399](https://user-images.githubusercontent.com/38773660/166404391-30221a07-c961-4c82-ba84-e44b28b21f5d.jpg)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

22.05-premium

### Tema Yang Digunakan

Silir

**Comment by balongbesuk** [comment]
d versi web berputar lancar

![image](https://user-images.githubusercontent.com/35319600/166436044-e42d98d7-b4f6-4a4e-845f-7c0586f4248e.png)

**Comment by balongbesuk** [comment]
![image](https://user-images.githubusercontent.com/35319600/166436659-186b926e-ae06-4ee1-8efd-adf3448d54c2.png)

**Comment by balongbesuk** [comment]
coba migrasi database

**Comment by makhbub** [comment]
Solved, saya uji coba di localhost, ternyata lupa mengcopy data yg ada di folder desa, 
setelah data tercopy, sudah kembali normal
