### ISSUE TITLE
Isi kode desa dari desa/config/config.php

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#5205]
Pada waktu membuka OpenSID, lakukan:

1. jika kode desa belum diisi, isi dengan kode desa di file desa/config/config.php jika ada. Kode desa ini diisi oleh Dashboard SaaS pada waktu setup awal site OpenSID di server SaaS. Kode desa di desa/config/config.php tidak menggunakan titik, contoh: 

`$config['kode_desa'] = "3321132016"; `

Token pelanggan sudah otomatis diisi menggunakan token pelanggan di file desa/config/config.php jika ada. Token pelanggan juga diisi oleh Dashboard SaaS pada waktu setup awal site OpenSID di server SaaS.

**Comment by eddieridwan** [comment]
Untuk menerapkan ini, diperlukan perubahan di TrackSID: https://github.com/OpenSID/tracksid/issues/54. Karena pada awal setup OpenSID oleh Dashboard SaaS, info desa yg diperoleh dari Layanan adalah kode_desa, bukan id_desa di TrackSID.

**Comment by andifahruddinakas** [comment]
Sudah ada sebelumnya, bisa gunakan : 
`https://pantau.opensid.my.id/index.php/wilayah/kodedesa?token=isi_token&kode='isi_kode_desa'`

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/1058
