### ISSUE TITLE
Permintaan fitur: Backup folder desa berukuran besar melalui aplikasi

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#5209]
### Apa kekurangan yg ingin diatasi?

Dengan dikembangkan layanan OpenSID SaaS, desa tidak akan mempunyai akses ke cPanel atau file di server hosting secara langsung. Yaitu, desa tidak bisa lagi melakukan backup folder desa menggunakan fitur File Manager atau serupa.

Dengan demikian, backup folder desa perlu bisa lakukan dengan cara lain. 

Salah satu opsi adalah melalui aplikasi, yaitu di mana OpenSID menyedaikan fitur mengunduh folder desa. Karena folder desa berpotensi berukuran besar, proses backup folder desa perlu diterapkan dengan cara yg memungkinkan proses unduh secara efisien dan aman.

### Jelaskan solusi yg diinginkan

Sediakan fitur di OpenSID untuk mengunduh folder desa. Karena folder desa berpotensi berukuran besar, proses backup folder desa perlu diterapkan dengan cara yg memungkinkan proses unduh secara efisien dan aman.

### Apakah ada alternatif lain

Backup folder desa dilakukan oleh pelaksana melalui tiket Help Desk. Cara ini akan mebebankan pelaksana dan sulit untuk dilakukan oleh desa secara rutin.

### Untuk versi OpenSID mana

v22.05-premium

### Informasi tambahan

Solusinya bisa mempertimbangkan cara berikut:
1. Proses penyiapan folder desa ke dalam format zip dilakukan melalui background job, dan dibatasi paling sering sekali seminggu. Muat file zip tersebut ke tempat di mana desa dapat mengunduhnya 
2. Setelah file zip siap, beritahu desa dan berikan link untuk mengunduh file zip tersebut

**Comment by scqolbu24** [comment]
issue ini ditutup karena sudah diterapkan
<img width="947" alt="unduh folder desa" src="https://user-images.githubusercontent.com/68048807/168693794-8f519fba-166c-4da8-8163-d251bf4d37c8.PNG">

**Comment by eddieridwan** [comment]
@scqolbu24 , issue ini juga dimaksudkan untuk membuat fitur backup folder desa efisien dan aman. 

Saat ini backup folder desa menggunakan library CI_Zip dari Codeigniter yg men-kompress semua file ke memori dan berusaha mendownload semuanya sekaligus. Dan akan gagal untuk folder desa yg besar karena keterbatasan memori dan juga proses download yg dilakukan sekaligus. 

Perlu dicarikan solusi untuk menyimpan hasil sementara kompress ke server (mungkin di temp_dir yg dikelola server) sebelum di-download. Kemudian diunduh secara 'streaming' atau sepotong-sepotong.

Dengan OpenSID SaaS, pengguna akan bergantung pada fitur ini untuk melakukan backup folder desa, sehingga perlu disediakan cara untuk bisa melakukan secara efisien dan aman untuk folder desa besar sekalipun.

**Comment by eddieridwan** [comment]
Bung @scqolbu24 , saya ambil issue ini, ya.

**Comment by scqolbu24** [comment]
baik pak

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/1059
