### ISSUE TITLE
Permintaan fitur: Backup folder desa secara inkremental

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#5210]
### Apa kekurangan yg ingin diatasi?

Issue https://github.com/OpenSID/OpenSID/issues/5209 menyediakan fitur untuk melakukan backup folder desa secara lengkap.

Karena folder desa bisa sangat besar, sebaiknya juga ada fitur untuk mengunduh hanya file2 folder desa yg berubah sejak backup lengkap sebelumnya.

### Jelaskan solusi yg diinginkan

Sediakan fitur di OpenSID untuk mengunduh file2 folder desa yg telah diubah sejak backup lengkap sebelumnya. Karena folder desa berpotensi berukuran besar, proses backup folder desa inkremental ini perlu diterapkan dengan cara yg memungkinkan proses unduh secara efisien dan aman.

OpenSID perlu mencatat setiap kali melakukan backup lengkap dan inkremental yg berhasil diunduh desa.

### Apakah ada alternatif lain

Tidak sediakan backup inkremental. Selalu lakukan backup lengkap.

### Untuk versi OpenSID mana

v22.05-premium

### Informasi tambahan

Solusinya bisa mempertimbangkan cara berikut:

1. Proses penyiapan backup folder desa inkremental ke dalam format zip dilakukan melalui background job, dan dibatasi paling sering sekali sehari. Muat file zip tersebut ke tempat di mana desa dapat mengunduhnya
2. Setelah file zip siap, beritahu desa dan berikan link untuk mengunduh file zip tersebut

**Comment by FirlianiF** [comment]
sudah dikerjakan melalui PR https://github.com/OpenSID/premium/pull/1072
