### ISSUE TITLE
Bug/error: Daftar Dokumen/Lampiran Salah

### ISSUE THREAD

**Issue by jonitrisulasmono** [OpenSID/OpenSID#5214]
### Jelaskan error yg dialami

Saat akan menambahkan/melihat dokumen yang akan digunakan sebagai lampiran pada Halaman **SURAT KEMATIAN** bagian **Data Ayah dan Data Ibu** yang muncul adalah daftar dokumen peraturan Desa.

### Cara untuk mereplikasi errornya

1. Buka menu Cetak Surat
2. Pilih Keterangan Kematian
3. KLik pada tombol Daftar Dokumen pada Dokumen Kelengkapan / Syarat untuk Ayah dan Ibu
4. Error muncul (daftar perdes/perkades)

### Hasil yg diharapkan

Link data dapat diperbaiki sehingga sesuai dengan yang dibutuhkan.

### Tangkapan layar dan log error

![error 1 daftar dokumen kematian local](https://user-images.githubusercontent.com/96878414/167750976-c95c7a6e-0283-45fe-9b69-0ab493cbcef9.jpg)

### Rilis Versi OpenSID

Rilis Umum

### Versi OpenSID

v22.04

### Tema Yang Digunakan

Natra

**Comment by balongbesuk** [comment]
sudah d test di website berputar?

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/1036
