### ISSUE TITLE
Permintaan Fitur : Sediakan Tombol Tambahan Dinas Luar Pada Daftar Hadir Perangkat Desa

### ISSUE THREAD

**Issue by sungaiku** [OpenSID/OpenSID#5215]
### Seperti apa yang diharapkan?
Mohon Penambahan Tombol pada Aplikasi Rekam Kehadiran Perangkat Desa dengan Keterangan **Dinas Luar Kantor Desa** dibawah Tombol Hadir
![Screenshot (51)](https://user-images.githubusercontent.com/105335939/167772403-1a159ee4-bf32-40a5-9f5b-efbca30ae3ea.png)

### Apa yang terjadi?
Perangkat Desa Tidak Merekam Kehadirannya Padahal Perangkat Desa sedang Dinas Diluar Kantor Desa

### Informasi tambahan 
Mempermudah Masyarakat untuk Mengetahui Keberadaan Perangkat Desa
Terima kasih atas perhatian para programer
![Screenshot (48)](https://user-images.githubusercontent.com/105335939/167771255-07b282ff-b5bf-4fcb-a23c-7c1918bf932d.png)

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by tobagus6911** [comment]
Setuju

**Comment by andifahruddinakas** [comment]
Sudah bisa ditambahkan di alasan keluar
