### ISSUE TITLE
hasil ekspor surat keterangan beda indentitas KIS, data pertama tidak tampil/muncul

### ISSUE THREAD

**Issue by rsoeta** [OpenSID/OpenSID#5216]
Layanan Surat > Cetak Surat > Cari Judul Surat (Surat Keterangan Beda Identitas KIS > masukan NIK/Nama Pemohon > centang data yang berbeda > lalu Isi data KIS > Klik Unduh RTF

### Seperti apa yang diharapkan?
Tampil data Pertama/sesuai Database Desa

### Apa yang terjadi?
data pertama tidak tampil/muncul
![Screenshot (2080)](https://user-images.githubusercontent.com/86590833/166157312-bfe38be5-e349-4ccc-98c3-2d612758ce1e.png)

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.5
| Versi PHP        |  7.4
| System operasi   | Window

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1437
