### ISSUE TITLE
Bug/error: BUG? Halaman kehadiran masih tampil walau di non aktifkan

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#5217]
### Jelaskan error yg dialami

halaman kehadiran masih bisa dibuka walaupun sudah di non aktifkan

### Cara untuk mereplikasi errornya

Buka menu kehadiran > pengaturan kehadiran > tampilkan kehadiran > tidak

buka halaman kehadiran masih bisa di buka

### Hasil yg diharapkan

ketika halaman ke hadiran di non aktifkan maka halaman kehadiran tidak bisa di akses 

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

website berputar

### Tema Yang Digunakan

-

### Informasi tambahan

-

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/1035
