### ISSUE TITLE
Permintaan fitur: Laporan Statistik Penerima Bantuan Per Program memunculkan Nama Daftar Penerima

### ISSUE THREAD

**Issue by macheda90** [OpenSID/OpenSID#5218]
### Apa kekurangan yg ingin diatasi?

Laporan Statistik Penerima Bantuan Penduduk/Keluarga sudah memunculkan Daftar Nama Penerima manfaat. Tetapi jika dipilih Per Program nya, tidak memunculkan Daftar Nama Penerima Manfaat program tersebut.
![image](https://user-images.githubusercontent.com/46791264/167795448-00f1247a-2216-435f-b6d8-78ec0de29c3f.png)

### Jelaskan solusi yg diinginkan

Jika dipilih Per Program, maka Daftar Nama Penerima Manfaat akan muncul dibawah grafik.

### Apakah ada alternatif lain

Tambahkan view dengan filter per program.

### Untuk versi OpenSID mana

v22.06

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/OpenSID/pull/7592
