### ISSUE TITLE
Layanan Mandiri Menu Perangkat Jumlah Perangkat Desa Tidak Tampil Semua

### ISSUE THREAD

**Issue by Pematung** [OpenSID/OpenSID#5219]
### Jelaskan error yg dialami

Pada Layanan Mandiri Versi Dekstop Jumlah Perangkat Desa Yang Terdaftar di Menu Info Desa/Pemerintahan Desa Berjumlah 12 orang sedangkan ketika melihat pada Layanan Mandiri Menu Perangkat yang tampil hanya 7 orang dari 12 orang tersebut.

### Hasil yg diharapkan

Seharusnya semua perangkat desa tampil semuanya

### Tangkapan layar dan log error

Ini tampilan pada Layanan Mandirinya

![1](https://user-images.githubusercontent.com/105429258/168070083-2915a4f3-96c0-4f15-bf1f-f1cc41d473f0.png)
Ini Log Errornya

![Log Errornya](https://user-images.githubusercontent.com/105429258/168070651-7f47d53e-dd5b-4536-94b8-023373fc14aa.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

22.05 Premium

### Tema Yang Digunakan

DeNatra 6.1

**Comment by agungsugiarto** [comment]
Pak @Pematung terima kasih sudah melaporkan issue, untuk saat ini saya tidak bisa meriplikasi issue yg dimaksud. Apakah issue ini juga ditemukan di demo berputar?

**Comment by Pematung** [comment]
Kalau di demo berputar ngak ada kendala semua perangkat desanya muncul semua terus kira kira dimana letak kesalahannya pak ????

**Comment by Pematung** [comment]
Kalau di demo berputar normal pak

Pada tanggal Kam, 12 Mei 2022 pukul 22.05 Agung Sugiarto <
***@***.***> menulis:

**Comment by tobagus6911** [comment]
Disaya juga sama, tidak tampil semua, cuma satu

**Comment by Pematung** [comment]
Problem diatas hanya berlaku pada perangkat desa yang diambil datanya dari database penduduk langsung namun jika saya pilih perangkat desa dan mendata secara manual atau memilih buttom tidak terdata datanya berhasil terbaca di layanan mandiri

**Comment by agungsugiarto** [comment]
Pak @Pematung bisa kirim backup databasenya ke telegram saya untuk dites

**Comment by Pematung** [comment]
Pak @agungsugiarto apa nama username Telegramnya pak....???

**Comment by agungsugiarto** [comment]
> Pak @agungsugiarto apa nama username Telegramnya pak....???

ini pak @meagungsugiarto

**Comment by Pematung** [comment]
Pak @agungsugiarto sudah saya PM databasenya.

![5](https://user-images.githubusercontent.com/105429258/168775973-382cda1d-7941-4fde-9bed-ef528c1ff914.png)

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/1046
