### ISSUE TITLE
[Teknis] Perbaiki Standar Penulisan Variabel Agar Lebih Support PHP8

### ISSUE THREAD

**Issue by senimandigital** [OpenSID/OpenSID#5220]
### Jelaskan error yg dialami

OpenSID sudah cukup dekat dan sebenar-nya bisa saja berjalan di PHP8, tapi memang diperlukan beberapa langkah strategis untuk mewujutkan hal tersebut. Salah satu-nya adalah dengan memperketat lagi standar penggunaan variable dan argument dari sebuah function.

![06 - 01 - Error PHP8](https://user-images.githubusercontent.com/278830/168201272-80387e02-1ec0-438a-9819-86fb7bc68e29.png)

Pada gambar diatas kita bisa melihat, bahwa PHP8 lebih memilih berhenti bekerja daripada mengekseskusi kode program yang prematur. Ini karena PHP8 sejati-nya ingin memperbaiki performa sehingga tidak lagi bersedia meng-eksekusi "kode program yang tidak ideal".

### Cara untuk mereplikasi errornya

Karena ini adalah masalah dalam standar penulisan, maka sebaiknya menggunakan fasilitas pencarian text yang sudah mendukung pencarian content pada multi file, saya menggunakan kata kunci pencarian:
```
"($"
```
untuk menangkap potensi masalah dalam penulisan variable, dan hasil-nya ada sekitar 300 file yang ditemukan, tentu saja tidak semuanya perlu diperbaiki karena file javascript juga termasuk dalam hasil pencarian tersebut.

![OpenSID Search Error Potention](https://user-images.githubusercontent.com/278830/168196831-1a7421cc-1fd8-4df4-9be4-a10dac398615.png)

### Hasil yg diharapkan

Setelah standar penulisan _variable_ diperketat, maka OpenSID seharus-nya sudah bisa berjalan pada PHP8. 

![OpenSID](https://user-images.githubusercontent.com/278830/168196328-b66b19b2-a479-4cea-a26d-f8f7e9914d55.png)

Screenshoot pada Gambar diatas dicapai hanya dengan memperbaiki baris 80 pada file "views/nav.php"

### Tangkapan layar dan log error

Untuk kenyamanan "tim teknis" dalam memperbaiki dan menguji OpenSID menggunakan multiple PHP Version ada 2 langkah yang harus dilakukan, yaitu:

1. Buat Virtual Domain Berbasis IP (System Operasi)
Dengan cara ini kita hanya perlu mengganti konfigurasi IP pada file "C:\Windows\System32\drivers\etc\hosts" tiap kali ingin berpindah versi php.
![11 - Hosts Costume](https://user-images.githubusercontent.com/278830/168199221-53c38c5e-6175-4ff4-8215-aaf1656efcc2.png)

2. Buat Virtual Host / Virtual Server / Sub Server Berbasis IP (Apache PHP Webserver).
Core PHP sejati-nya bersifat portable, dan kita bebas meletakan-nya dimanapun. Dalam contoh ini saya menggunakan Vertrigo Webserver PHP5 sebagai default webserver.

Dan saya menginstall xampp "tapi tidak untuk dijalankan" hanya mengambil folder "php"nya saja untuk mengambil versi php yang dimiliki-nya. kemudian me-rename dan membackup folder php ke lokasi lain. Setelah membackup folder "php"-nya xampp saya uninstall lagi dan menginstall lagi versi xampp yang lain hanya untuk mengambil folder phpnya saja.

![12 - Multiple PHP Version](https://user-images.githubusercontent.com/278830/168203662-86cc40d7-efe5-48d8-9fc7-c4e27437f432.png)

Setelah cukup mendapat semua versi php yang saya inginkan, maka saya hanya perlu membuat file konfigurasi virtual server, untuk masing-masing versi php tadi. saya sertakan juga script konfigurasi yang dibutuhkan:
```
<VirtualHost 192.168.1.12:80>
 ServerName OpenDesa.OpenSID
 DocumentRoot "D:/Online/Opensource/OpenDesa.OpenSID"
  <Directory  "D:/Online/Opensource/OpenDesa.OpenSID">
    Options Indexes FollowSymLinks Includes ExecCGI
    AllowOverride All
    Require all granted
  </Directory>

 UnsetEnv PHPRC
  <FilesMatch "\.php$">
    php_flag engine off
    SetHandler application/x-httpd-php8_0
    Action application/x-httpd-php8_0 "/php8_0/php-cgi.exe"
  </FilesMatch>

 ScriptAlias /php8_0/ "D:/Program Files/xampp/php8_0/"
  <Directory "D:/Program Files/xampp/php8_0">
    AllowOverride None
    Options None
    Require all denied
    <Files "php-cgi.exe">
          Require all granted
    </Files>
  </Directory>
</VirtualHost>
```
dengan contoh script konfigurasi seperti diatas kita hanya perlu mereplace
```
php8_0
```
ke code versi yang kita inginkan. Folder php sebaik-nya menggunakan prefix "php" agar mudah dalam melakukan auto replace dengan notepad misal-nya.

### Rilis Versi OpenSID

Rilis Umum

### Versi OpenSID

v22.05

**Comment by vickyrolanda** [comment]
Mohon maaf pak @senimandigital saat ini issue ini kita close dulu dan saat ini Opensid juga belum support ke php 8 pak, namun kami sudah masukin usul ini untuk upgrade opensid ke php 8 terimakasih.
