### ISSUE TITLE
[Layanan Mandiri] sediakan fitur melihat dan mendownload sertifikat vaksin

### ISSUE THREAD

**Issue by tobagus6911** [OpenSID/OpenSID#5221]
### Apa kekurangan yg ingin diatasi?

Fitur ini diperlukan untuk mempermudah mendapatkan sertifikat dalam perjalanan atau kunjungan

### Jelaskan solusi yg diinginkan

-

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

-

### Informasi tambahan

-

**Comment by andifahruddinakas** [comment]
Sudah tidak dikembangkan lagi
