### ISSUE TITLE
Permintaan fitur: Optimasi folder desa

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#5222]
### Apa kekurangan yg ingin diatasi?

Terkadang ada data pada tabel yang memiliki lampiran file, namun saat dihapus file tidak ikut terhapus pada folder desa.

### Jelaskan solusi yg diinginkan

Perlu disediakan fitur untuk optimasi folder desa yakni pengecekan file sampah yang tidak digunakan bisa dihapus dengan 1 kali klik pada admin.

### Apakah ada alternatif lain

Cek dan hapus manual.

### Untuk versi OpenSID mana

v22.05-premium

### Informasi tambahan

.

**Comment by tobagus6911** [comment]
mantap. setuju. terutama file image dan dokumen

**Comment by balongbesuk** [comment]
saya kemarin menemukan desa yang folder desanya tidak mengikuti versi yang terbaru sehingga upload gambar tidak masuk, mungkin sebagai catatan untuk cek struktur folder desa juga agar sama dengan versi terbaru

**Comment by andifahruddinakas** [comment]
> saya kemarin menemukan desa yang folder desanya tidak mengikuti versi yang terbaru sehingga upload gambar tidak masuk, mungkin sebagai catatan untuk cek struktur folder desa juga agar sama dengan versi terbaru

Untuk rilis bulan depan, struktur folder desa selalu dicek saat migrasi. Jika folder tidak sesuai/lengkap akan disesuaikan otomatis.

**Comment by andifahruddinakas** [comment]
Issue ini diperuntukkan untuk file2 yang gagal hapus walaupun data pada data di database sudah dihapus. Agar data dan file selalu sesuai.
