### ISSUE TITLE
Permintaan fitur: Hasil Export database Penduduk menggunakan huruf

### ISSUE THREAD

**Issue by mukhlisvandjava** [OpenSID/OpenSID#5223]
### Apa kekurangan yg ingin diatasi?

Hasil ekspor database Penduduk hasilnya hanya kode. Misalnya Data jenis kelamin : Laki-laki kode 1 dan perempuan kode 2, ; seandainya desa membutuhkan data Ms. Exel individu tentang pendidikan SD atau SLTP atau SLTA yang akan muncul hanya kodenya saja sehingga mesti di replace manual dulu untuk mendapatkannya data penduduk berdasarkan pendidikan.

### Jelaskan solusi yg diinginkan

Data hasil export bisa berupa huruf sesuai dengan aturan format kriteria import database. Contoh : Data hasil eksport tentang pendidikan : Tamat SD/Sederajat, Tamat SLTA/Sederajat dll.Sehingga mudah untuk di olah sesuai kebutuhan data yang akan di butuhkan.  

### Apakah ada alternatif lain

Hasil export yang di maksudkan sebenarnya telah ada di versi premium 21.12 namun saat ini yang tampil hanya kodenya saja.

### Untuk versi OpenSID mana

Rilis Premium V22.06 dan selanjutnya

### Informasi tambahan

hasil yang di peroleh nantinya seperti ini 
![issue](https://user-images.githubusercontent.com/92527916/168419586-7464c5b8-31b7-4f22-891d-a02a44738f9b.jpg)

**Comment by mukhlisvandjava** [comment]
berikut ini referensi di Forum opendesanya https://forum.opendesa.id/d/163-hasil-ekspor-penduduk-berisi-kode-saja

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/OpenSID/pull/7525
