### ISSUE TITLE
Hari Kelahiran di Aplikasi berbeda dgn lampiran

### ISSUE THREAD

**Issue by rsoeta** [OpenSID/OpenSID#5224]
Hari Kelahiran di Aplikasi berbeda dgn lampiran

![Screenshot (2178)](https://user-images.githubusercontent.com/86590833/168423635-e2165b3f-f72b-4c54-bec0-e512be71016c.png)
![Screenshot (2179)](https://user-images.githubusercontent.com/86590833/168423639-6d7b9898-8257-4fb4-89a6-b0ed886345d3.png)

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/1044
