### ISSUE TITLE
Tampilan Perangkat Desa yang tampil di Layanan Mandiri agar tampilan dan urutannya persis seperti urutan pada menu Pemerintahan Desa

### ISSUE THREAD

**Issue by Pematung** [OpenSID/OpenSID#5226]
### Apa kekurangan yg ingin diatasi?

Data perangkat desa yang tampil pada layanan mandiri versi dekstop nama dan urutannya tidak bisa disesuaikan seperti data yang ada pada menu info desa/pemerintahan desa yang mana saat ini nama perangkat desa yang di tampilkan pada layanan mandiri menu perangkat urutan nama dan jabatannya tidak sesuai urutan nama dan jabatannya  dengan yang tertera pada menu pemerintahan desa.

![1](https://user-images.githubusercontent.com/105429258/168758257-72015bb6-91b1-434c-b52e-a62d03e86850.png)

### Jelaskan solusi yg diinginkan

Solusi yang diinginkan agar supaya pada layanan mandiri menu perangkat ditambahkan buttom panah atas bawah seperti yang ada pada menu pemerintahan desa agar pemerintah desa bisa menyesuaikan urutan dan foto perangkat desa tersebut sesuai dengan urutan jabatan yg ada pada SOTK Pemerintah desa masing -masing dan jika pengguna/warga klik lapor juga ditambahkan kolom untuk menuliskan keterangan laporannya agar alasan laporkan bisa diketahui oleh admin desa.

![2](https://user-images.githubusercontent.com/105429258/168760177-a1d3ace3-5c2b-4857-959a-724548d196b6.png)

### Apakah ada alternatif lain

Kalaupun hal yang diinginkan diatas seperti menampilkan foto perangkat desa tidak bisa diterapkan seenggaknya  urutannya sama atau sesuai dengan urutan yang di menu info desa/pemerintahan desa.

![3](https://user-images.githubusercontent.com/105429258/168761210-024bd177-cbb4-4a5a-9fd1-5863f0bd30e0.png)

### Untuk versi OpenSID mana

22.06 Premium

### Informasi tambahan

Sehingga kurang lebih tampilan yang diinginkan seperti gambar dibawah ini.....

![4](https://user-images.githubusercontent.com/105429258/168766040-62eb956e-16e0-48ed-a379-eac12402c359.png)

**Comment by andifahruddinakas** [comment]
Perbahan data perangkat desa (baik itu data pribadi maupun urutan) hanya dilakukan di admin saja. Adapun perubahan urutan di layanan mandiri menyesuaikan urutan di admin sudah disesuaikan rilis v22.09-premium.
