### ISSUE TITLE
Bug/error: 

### ISSUE THREAD

**Issue by rsoeta** [OpenSID/OpenSID#5229]
### Jelaskan error yg dialami

Lampiran F-2.01 SURAT KETERANGAN KELAHIRAN bagi warga yang akan dibuatkan akta kelahiran, hanya muncul halaman kosong di ekspor file zip

### Cara untuk mereplikasi errornya

1. Layanan Surat
2. Cetak Surat
3. Pilih Surat Keterangan Kelahiran
4. Isi Data
5. Unduh RTF

### Hasil yg diharapkan

Hasil Lampiran F-2.01 SURAT KETERANGAN KELAHIRAN bagi warga yang akan dibuatkan akta kelahiran, muncul dengan baik di ekspor file zip

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/86590833/168956344-578b0ed8-f2b2-4906-804e-b7fd875c1395.png)

### Rilis Versi OpenSID

Rilis Umum

### Versi OpenSID

v22.05

### Tema Yang Digunakan

Natra v4.5

**Comment by agungsugiarto** [comment]
Terima kasih pak @rsoeta sudah melaporkan issue, issue ini saya close. Untuk menghindari masalah ini tidak perlu melakukan refresh halaman ketika sedang mengisi form surat keterangan tersebut. Terima kasih
