### ISSUE TITLE
Cetak Unduh Fitur Persil

### ISSUE THREAD

**Issue by Topohudoyo** [OpenSID/OpenSID#523]
Usul buat Tim pengembang : Pada fitur Persil sebaiknya di lengkapi dengan fasilitas cetak/Unduh Excel. Kalau bisa ini sangat membantu desa. Dan ini saya usulkan karena ada pertanyaan dari desa-desa. Supaya bisa di arsipkan, dan lebih leluasa pemanfaatannya.

**Comment by noefa86** [comment]
Tambahan: Persil berhubungan dengan pembayaran PBB P-2, di desa kami PBB dibayarkan melalui kasir desa (bendahara PBB). misalkan pada modul Persil ini ditambahkan tabel catatan tentang pelunasan PBB di tahun berjalan dan PBB terutang di tahun sebelumnya mungkin akan membantu desa untuk memonitor tanah persil mana yang sdh lunas atau belum, sehingga memudahkan desa untuk melakukan penagihan

**Comment by Jehamahdan** [comment]
Mohon jg di tambahkan fitur import dari data excel..

**Comment by eddieridwan** [comment]
Fitur cetak & unduh data persil sudah dicommit ke master melalui Pull Request https://github.com/OpenSID/OpenSID/pull/802.

@noefa86 : Usulan catatan pelunasan PBB dibuatkan issue baru di https://github.com/OpenSID/OpenSID/issues/806. (satu issue dibatasi satu usulan)

@Jehamahdan : usulan impor persil ada di https://github.com/OpenSID/OpenSID/issues/795 (satu issue dibatasi satu usulan).
