### ISSUE TITLE
Pengaturan Jenis Peta

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#5232]
Sediakan pengaturan jenis peta yang akan ditampilkan default saat pertama kali membuka peta.

Contoh : Menggunakan MappBox Satelit

**Comment by andifahruddinakas** [comment]
Pak @ariandii, silahkan ditambah jika ada yang masih kurang atau tidak sesuai agar tidak terlupa.

**Comment by ariandii** [comment]
Dari pilihan jenis peta, bisa diberikan ada 5 pilihan sesuai yang ada pada gambar di bawah ini.

saat ini, seluruh tampilannya sama, kecuali ketika klik pada H.O.T

Namun berbeda jika sudah input token mapbox. maka setiap pilihan memiliki tampilan nya masing-masing.

Apakah ini normal? atau ada alternatif lain antara sudah input token mapbox maupun belum.

<img width="308" alt="image" src="https://user-images.githubusercontent.com/46939846/169323654-98ba2643-5600-457c-ae75-43d00c99ce1a.png">

**Comment by mranca** [comment]
Sangat setuju dengan ini jika citra  mapbox satelit-street di jadikan default

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1144
