### ISSUE TITLE
Permintaan fitur: Tambahkan Menu Tupoksi pada Menu Pemerintahan Desa

### ISSUE THREAD

**Issue by Pematung** [OpenSID/OpenSID#5233]
### Apa kekurangan yg ingin diatasi?

Kolom untuk pengisian Tupoksi perangkat desa belum diterapkan pada aplikasi OpenSID

### Jelaskan solusi yg diinginkan

Solusinya adalah perlu untuk ditambahkan kolom isian Tupoksi untuk masing masing perangkat desa mulai dari kepala desa, sekretaris desa dan seterusnya guna lebih melengkapi data dan tupoksi dari perangkat desa itu sendiri

### Apakah ada alternatif lain

Alternatif yang selama ini digunakan adalah dengan memanfaatkan menu artikel dinamis ataupun statis untuk mempublish masing masing tupoksi perangkat desa ke publik maupun ke perangkat desa itu sendiri.

### Untuk versi OpenSID mana

Rilis 22.06 Premium

### Informasi tambahan

Nanti Kolomnya ditambah di sini satu paket sama isian isian kolom perangkat desa/Staf Pemerintahan Desa seperti pada gambar di bawah ini

![image](https://user-images.githubusercontent.com/105429258/169540581-a4944af1-46e6-48bf-8d13-1a02eb3283bc.png)

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1141
