### ISSUE TITLE
Kebebasan memilih lokasi pembangunan

### ISSUE THREAD

**Issue by Khoriansah** [OpenSID/OpenSID#5234]
### Apa kekurangan yg ingin diatasi?

Tidak bisa memilih atau menempatkan pin lokasi pembangunan secara akurat.
![Screenshot 2022-05-22 072411](https://user-images.githubusercontent.com/25412301/169673233-8f803dfe-388f-44c4-a138-23bbfc1cfb26.jpg)
![Screenshot 2022-05-22 072625](https://user-images.githubusercontent.com/25412301/169673292-f2cf6988-e5fc-45d3-9dc5-c2a0a0da99a3.jpg)

### Jelaskan solusi yg diinginkan

Menambahkan fitur untuk memilih lokasi secara manual dengan cara menggeser pin lokasi pada map, seperti fitur ketika memilih lokasi kantor desa
![Screenshot 2022-05-22 072944](https://user-images.githubusercontent.com/25412301/169673358-935c341b-ce1a-4ff4-8655-fcd7886e27b4.jpg)
.

### Apakah ada alternatif lain

Pemilihan lokasi menggunakan koordinat, dan peta lokasi pembangunan otomatis menampilkan titik yang sesuai.

### Untuk versi OpenSID mana

22.05-premium-rev02

**Comment by balongbesuk** [comment]
![Untitled](https://user-images.githubusercontent.com/35319600/169673887-fb3e15a0-cfe9-45e4-b853-db902d8869eb.jpg)
