### ISSUE TITLE
Bug/error: Kerancuan Status Penduduk

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#5235]
### Jelaskan error yg dialami

Pertanyaan Pertama.
1. Saat ini, **MENGAPA** ketika input penduduk dengan Status Kepala Keluarga **Tidak Tetap**, secara Otomatis "Dipaksa" menjadi **TETAP** ketika penduduk tersebut ditambahkan sebagai KK Baru.
2. Sehingga penduduk tersebut Muncul di Tabel **Daftar Anggota Keluarga** karena sudah "Dipaksa" menjadi penduduk Tetap.

Pertanyaan Kedua.
1. Jika ingin edit dan ubah status **Tetap** menjadi **Tidak Tetap** maka akan disable karena **masih** masuk dalam **Daftar Anggota Keluarga**
2. Setelah dikeluarkan dari KK dan berhasil ubah menjadi Tidak Tetap, Penduduk Tersebut bisa ditambah lagi ke **Daftar Anggota Keluarga** namun Setelah tersimpan, Penduduk tersebut **TIDAK** muncul di tabel (karena berstatus Tidak Tetap).

Pertanyaan Ketiga.
Mengapa Kasus Nomor 1 bisa "Dipaksa" menjadi status **Tetap** ketika sebagai Kepala Keluarga yang ingin ditambah ke KK, namun menjadi "Tidak Dipaksa" ketika sudah dikeluarkan untuk ubah status dan dimasukkan ke KK kembali.

Pertanyaan Keempat
Mengapa seluruh Penduduk berstatus **TIDAK TETAP** yang ditambah ke anggota keluarga akan menjadi SIA SIA, karena Ditabel anggota keluarga TIDAK MUNCUL dan ketika ingin ubah status **TIDAK TETAP** menjadi **TETAP**, kolomnya **DISABLE**.

### Cara untuk mereplikasi errornya

Sebagaimana 4 penjabaran di atas.

### Hasil yg diharapkan

Alur yang sesuai, karena ada 2 Kerancuan mengenai Pertanyaan ke-3 dan ke-4

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.05-premium-rev01

**Comment by eddieridwan** [comment]
@yogiperdana aturan yg betul:
1. Penduduk yg masuk anggota keluarga harus penduduk tetap
2. Jika bukan penduduk tetap tidak bisa ditambah sebagai anggota keluarga atau kepala keluarga.
3. Pada waktu menbuat kepala keluarga baru, status penduduk dibuat sebagai penduduk tetap.
4. Penduduk tidak tetap, bukan anggota keluarga dan setiap waktu bisa diubah menjadi penduduk tetap
5. Penduduk anggota keluarga tidak bisa diubah menjadi tidak tetap
6. Penduduk tetap, jika bukan anggota keluarga, dapat diganti menjadi tidak tetap

Perhatikan, perubahan dari status tetap menjadi tidak tetap dan sebaliknya akan mempengaruhi laporan rekap penduduk dll.

**Comment by ariandii** [comment]
Sebagai inforamsi tambahan,
Ada 1 keluarga terdiri dari Suami, Istri dan 3 anak.

Mereka berdomisili sementara di desa (karena bekerja), dan minta surat keterangan yang diperlukan.

Tentunya mereka diinput ke Database dengan status Tidak Tetap.
Jika mengikuti aturan yang betul, Apakah 1 keluarga itu artinya tidak akan bisa diketahui sebagai sebuah Keluarga dalam OpenSID? Apakah artinya selamanya mereka akan individu dalam database?

**Comment by eddieridwan** [comment]
Sejauh ini, keluarga di OpenSID adalah keluarga yg kartu keluarganya berdomisili tetap di desa ybs. Dan dianggap dan dilaporkan sebagai warga desa ybs, sesuai dengan data Dukcapil.

Jika ada kebutuhan untuk merekam keluarga 'tidak tetap', yaitu keluarga yg kartu keluarganya dari wilayah lain dan hanya berdomisili sementara di desa ybs, maka silakan buat issue khusus. Dan harus disertai aturan lengkap bagaimana keluarga tidak tetap tersebut dilaporkan di setiap laporan kependudukan yg ada

**Comment by ariandii** [comment]
Dengan demikian, apakah Laporan Rekap Penduduk yang diterapkan saat ini juga tidak menghitung tambahan penduduk yang diinput sebagai Tidak Tetap?

**Comment by eddieridwan** [comment]
Sesuai dengan Permendagri terkait. Silakan dipelajari.
