### ISSUE TITLE
[teknis]  Sederhanakan pemanggilan tracksid dengan menghapus token_opensid, gunakan token_pantau 

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#5237]
### Apa kekurangan yg ingin diatasi?

Pemanggilan tracksid saat ini menggunkan token_opensid dan token_pantau. Tujuannya sama, yaitu mengirim suatu bukti bahwa tracksid dipanggil dari OpenSID.

### Jelaskan solusi yg diinginkan

Sederhanakan dengan menghapus token_opensid dan ganti dengan token_pantau.

### Apakah ada alternatif lain

Tidak

### Untuk versi OpenSID mana

v22.05-premium

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/1055
