### ISSUE TITLE
Bug susulan: hapus COLLATE utf8_unicode_ci di seeder 

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#5238]
### Jelaskan error yg dialami

Error karena ada COLLATE utf8_unicode_ci di seeder

### Cara untuk mereplikasi errornya

1. install dari awal dengan database kosong
2. buka menu Info Desa  > Pemerintahan Desa
3. lihat pesan di form Periksa terkait adanya COLLATE utf8_unicode_ci

Karena error ini ada di kolom data, bukan tabel, tidak bisa diperbaiki otomatis.

### Hasil yg diharapkan

Tidak ada kolom data dengan COLLATE utf8_unicode_ci.

### Tangkapan layar dan log error

Menyusul

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.05-premium

### Informasi tambahan

Pull request susulan ke rilis_dev karena fitur seeder masuk di branch rilis_dev bukan bug fix.

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/1051
