### ISSUE TITLE
>>>>>>>>>>>> Link gambar wiki (panduan) 

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#524]
[20170420_WP-SID_Position_Final.pdf](https://github.com/OpenSID/OpenSID/files/1561913/20170420_WP-SID_Position_Final.pdf)

**Comment by eddieridwan** [comment]
<img width="1055" alt="cari-surat-masuk" src="https://user-images.githubusercontent.com/249563/28767097-ba6d2a8e-7615-11e7-9b4b-872962408c63.png">
<img width="1055" alt="filter-surat-masuk" src="https://user-images.githubusercontent.com/249563/28767098-ba6e4a5e-7615-11e7-88ea-b69d7ba8ee09.png">
<img width="1079" alt="form-isian-surat-masuk" src="https://user-images.githubusercontent.com/249563/28767099-ba6ee1b2-7615-11e7-8562-2886641d51c4.png">
<img width="1055" alt="halaman-surat-masuk" src="https://user-images.githubusercontent.com/249563/28767102-ba756fdc-7615-11e7-9676-fd138275f468.png">
<img width="1055" alt="tombol-tambah-surat-masuk" src="https://user-images.githubusercontent.com/249563/28767100-ba736322-7615-11e7-950a-b319b99bf31a.png">
<img width="1055" alt="urut-surat-masuk" src="https://user-images.githubusercontent.com/249563/28767101-ba74aade-7615-11e7-85a5-7fad38812211.png">

**Comment by siayi** [comment]
Untuk Pilihan Disposisi Kepada: apakah bisa disesuaikan,, soalnya di desa saya nomenklatur "kawil" pengen diganti dengan "Kadus" ?

**Comment by eddieridwan** [comment]
Bung @siayi , silakan buat issue baru untuk permintaan anda. Issue ini hanya untuk tempat gambar yang akan dipakai untuk wiki panduan (lihat judul issue ini).
