### ISSUE TITLE
Sesuaikan judul Jenis Peraturan dengan sebutan Kepala Desa

### ISSUE THREAD

**Issue by agusterm** [OpenSID/OpenSID#5240]
### Jelaskan error yg dialami

Sebutan Kepala Desa tidak berpengaruh di jenis peraturan. agar bisa nama jenis peraturan bisa disesuaikan dengan sebutan di Desa. di desa kami nama Peraturan Kepala Desa namanya Peraturan Perbekel.  Nama Kepala Desa di Desa kami namanya perbekel.

### Cara untuk mereplikasi errornya

sebagaimana mestinya

### Hasil yg diharapkan

sebagaimana mestinya

### Tangkapan layar dan log error

Beberapa jenis peraturan agar disesuaikan sesuai dengan sebutan di Desa masing-masing. contoh peraturan kepala desa menjadi peraturan perbekel
![image](https://user-images.githubusercontent.com/87739467/169959006-63d0f2d1-e412-4d16-b2ab-813ca0a75c4d.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.05-premium-rev01

### Tema Yang Digunakan

Denatra

**Comment by agungsugiarto** [comment]
Pak @agusterm bisa diberikan contoh untuk semua masing2 sebutannya, terima kasih.

**Comment by agusterm** [comment]
> Pak @agusterm bisa diberikan contoh untuk semua masing2 sebutannya, terima kasih.

Untuk Kepala Desa ditempat kami itu sebutannya perbekel. 
Dari sisi nama peraturan
Kalo Peraturan Kepala Desa (Pekades) sebutannya Peraturan Perbekel
Keputusan Kepala Desa sebutannya Keputusan Perbekel
Kalo Peraturan Desa tetap sama

**Comment by agungsugiarto** [comment]
Pak @agusterm agar konsisten dibanyak desa, mungkin perubahannya seperti ini

Peraturan Desa (Perdes) => Peraturan Desa
Peraturan Kepala Desa (Perkades) => Peraturan Kepala Desa
Peraturan Bersama Kepala Desa => Peraturan Kepala Desa


Sebutan `Desa` akan diambil dari pengaturan aplikasi sebutan desa, bagaimana pak?

Pak @eddieridwan mungkin ada usul lain pak?

**Comment by agusterm** [comment]
mohon maaf pak kemarin saya balas dr hp ternyata tidak masuk. usul saya diambil dari sebutan kepala desa saja

**Comment by agusterm** [comment]
seperti contoh Peraturan Kepala Desa ditempat kami namanya Peraturan Perbekel
dan Keputusan Kepala Desa namanya Keputusan Perbekel

**Comment by jimmyjputra3** [comment]
Kebutuhan sama pak didesa/kampung kami kami,  sebutan desa dan kepala desa tidak berpengaruh pada sebutan jenis peraturan desa. contoh dikami, desa disebut kampung, kades disebut reje, sebutan kampung dan reje sudah diset pada pengaturan aplikasi, namun jenis peraturan desa tetap memunculkan sebutan desa dan kades default. Selain itu di desa kami selain peraturan desa ada juga Qanun yang sejenis dengan Peraturan Desa namun terpisah.

Oleh karena itu kami mohon dibuatkan fitur untuk manajemen Jenis Peraturan Desa : 
1. Tambah Jenis Peraturan
2. Edit Nama Jenis Peraturan 
3. Tambah Jenis Peraturan
4. Hapus Jenis Peraturan

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1365
