### ISSUE TITLE
Permintaan fitur: Sediakan Modul Untuk Tata Kelola Bumdes

### ISSUE THREAD

**Issue by Pematung** [OpenSID/OpenSID#5241]
### Apa kekurangan yg ingin diatasi?

Belum ada modul untuk mencatat dan mengelola data BUMDES.

### Jelaskan solusi yg diinginkan

Sediakan modul untuk mecatat data BUMDES.

Isian :

Identitas Bumdes
Pendapatan
Pengeluaran
Jumlah Unit Usaha
Jumlah Peminjam ( Untuk Unit Usaha Simpan Pinjam)
Statistik
Lapor Bulan dan Tahun
Struktur Pengurus Bumdes
Anggota Bumdes
Buku Kas/Saldo Bumdes
dll

### Apakah ada alternatif lain

Masih menggunakan format exel aplikasi berbasis exel offline

### Untuk versi OpenSID mana

Rilis 22.06 Premium

### Informasi tambahan

-

**Comment by andifahruddinakas** [comment]
Duplicate issue https://github.com/OpenSID/OpenSID/issues/5186

**Comment by yugaeko** [comment]
desa kami juga membutuhkan fasilitas ini, yaitu tata kelola bumdes.

Karena hampir setiap tahun akan ada permintaan data terkait perkembangan bumdes

berikut beberapa data yang diminta oleh pemerintah provinsi jawa timur
![image](https://github.com/OpenSID/OpenSID/assets/9125101/ee2dd3ed-8eee-4a9b-9aef-617d76dce5d1)

semoga bisa terealisasi di OPENSID
