### ISSUE TITLE
Bug/error: Jabatan Kepala Desa Pada Menu Pemerintahan Desa Sering Berubah Menjadi Kepala Saja

### ISSUE THREAD

**Issue by Pematung** [OpenSID/OpenSID#5243]
### Jelaskan error yg dialami

Masih adanya bug pada Menu Info Desa/Pemerintahan Desa/Kolom Jabatan Kepala Desa Yang mana sering berubah sendiri menjadi **Kepala** saja walaupun sudah diganti tulisan jabatannya menjadi Kepala Desa.

![1](https://user-images.githubusercontent.com/105429258/170301081-e9f9c079-389a-4c50-a560-b308dfc4b474.png)

### Cara untuk mereplikasi errornya

**Hal ini terjadi ketika masuk ke**

1. Menu Info Desa
2. Pemerintahan Desa
3. Lalu coba ganti jabatan yang tadinya tertulis Kepala dan Ubah menjadi Kepala Desa
4. Lalu kemudian coba ganti logo desa atau nama desa desa lain lalu simpan apakah berubah kembali
5. tulisan yang sudah diubah menjadi kepala desa kembali menjadi Kepala......???

### Hasil yg diharapkan

Hasil yang diharapkan adalah jabatan kepala desa tersebut tidak berubah ubah jika sudah ditetapkan tulisannya menjadi Kepala Desa harusnya datanya tetap dan tidak berubah secara otomatis atau tetap seperti gambar dibawah ini karena hal ini berdampak pada Layanan Surat menyurat.

![2](https://user-images.githubusercontent.com/105429258/170304109-c13c41e4-ea57-41f3-96cf-3e609a42e8aa.png)

### Tangkapan layar dan log error

Begini Masalah yang dialami ketika membuat surat yang seharusnya Redaksinya/kalimatnya Kepala Desa Simpang Kanan namun malah yang terjadi seperti pada gambar dibawah ini.

![Surat 1](https://user-images.githubusercontent.com/105429258/170302408-9339c45c-3b93-437e-aae0-73556b5686f5.png)

Begitu Pula Pada Tempat TTD Kepala Desanya juga terkena dampak dan ini sangat merepotkan admin desa dan Redaksi surat jadi ngak akurat.

![Surat 2](https://user-images.githubusercontent.com/105429258/170302872-28b304da-25eb-460c-bffa-f2341e03f005.png)

Dan hal diatas terjadi ketika kita ingin merubah logo desa maupun merubah identitas desa atau mencoba identitas desa yang lain dan lalu simpan maka akan terjadi hal yang dimaksut diatas.

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

22.05 Premium-rev01

### Tema Yang Digunakan

DeNatra 6.1

### Informasi tambahan

Seharusnya Hasilnya setiap cetak surat redaksinya seperti gambar dibawah ini.

![Surat 3](https://user-images.githubusercontent.com/105429258/170304947-94d289cd-d9c0-4a1f-ad45-d25f240873db.png)

Dan Kolom Jabatan Kepala Desanya tetap seperti gambar dibawah ini.

![2](https://user-images.githubusercontent.com/105429258/170305091-a8dc485a-3ed0-431f-a78c-b6b9e7f518e2.png)

**Comment by agungsugiarto** [comment]
Pak @Pematung saya tidak bisa replikasi issue ini, sudah saya coba merubah nama jabatannya kemudian ubah logo desa, tapi tetap jabatan tersebut tidak berubah seperti yg disampaikan. Apakah issue ini juga dialami di demo berputar pak?

**Comment by agungsugiarto** [comment]
Issue ini saya close, untuk merperbaiki bisa ikuti langkah berikut

<img width="733" alt="image" src="https://user-images.githubusercontent.com/10989147/170620426-d4a7897d-fe40-4b86-86cd-92d8813a18bb.png">
Sebutan kepala desa diambil dari pengaturan aplikasi jadi bisa dirubah, urutannya untuk merubah

1. Buka menu `pengaturan/aplikasi`
2. Ubah `sebutan kepalan desa` sesuai preferensi
3. Buka menu `info desa/identitas desa`
4. Ubah identitas desa, pilih nama kepala desa tersebut akan otomatis diambil dari pengturan aplikasi untuk sebutannya

**Comment by agungsugiarto** [comment]
Issue

**Comment by Pematung** [comment]
OK Problem Solved

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/1064
