### ISSUE TITLE
Permintaan fitur: Restore Folder Desa Melalui Aplikasi

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#5247]
### Apa kekurangan yg ingin diatasi?

Perlu disediakan restore folder desa melalui aplikasi sehingga tidak perlu lagi masuk melalui CPanel.

Cek pembahasan https://m.facebook.com/groups/OpenSID/permalink/2136789373152699/?comment_id=2137016989796604&reply_comment_id=2139373846227585

### Jelaskan solusi yg diinginkan

Sediakan restore folder desa

### Apakah ada alternatif lain

Saat ini masih melalui CPanel

### Untuk versi OpenSID mana

v22.05-premium

### Informasi tambahan

.

**Comment by ai-skematik** [comment]
fitur ini seperti menambahkan tema melalui admin.

**Comment by ai-skematik** [comment]
Tp dulu tema tidak jd karena pertimbangan keamanan.

**Comment by eddieridwan** [comment]
@andifahruddinakas dkk, masalah keamanan tetap perlu dipertimbangkan. Karena restore folder desa mengunggah file php, tentunya resiko mengunggah script nakal yg bisa mengancam keseluruhan server. 

Syarat tambahan yg perlu diterapkan:

1. Hanya admin yg diperbolehkan
2. Admin tsb harus memiliki email atau Telegram yg telah diverifikasi
3. OTP dikirim ke email atau Telegram yg telah diverifikasi sebelum menjalankan restore
4. Restore hanya dijalankan setelah OTP tersebut diisi pada waktu diminta
5. OTP hanya berlaku selama 5 menit 
6. Proses restore ini dicatat ke log file
7. Fitur ini dimatikan di demo

Untuk keperluan server OpenSID Siap Pakai, perlu dipikirkan juga apakah perlu mekanisme keamanan yg lebih ketat lagi. Misalnya, setiap file PHP dibuatkan hash menggunakan pemicu berdasarkan id admin yg diperbolehkan. Hash tersebut dibuat pada waktu membuat backup. Dan diperiksa pada waktu restore, untuk verifikasi file tersebut tidak diubah.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1262

**Comment by afzalthextro** [comment]
> 2. Admin tsb harus memiliki email atau Telegram yg telah diverifikasi
> 3. OTP dikirim ke email atau Telegram yg telah diverifikasi sebelum menjalankan restore

bagaimana cara verifikasi email atau telegram?
