### ISSUE TITLE
Bug/error: Foto/Gambar Perangkat Desa Tidak Tampil

### ISSUE THREAD

**Issue by Pematung** [OpenSID/OpenSID#5248]
### Jelaskan error yg dialami

Masih adanya bug pada Menu Info Desa/Pemerintahan Desa/Ubah Data/Unggah

Terjadi pada https://berputar.opendesa.id/

### Cara untuk mereplikasi errornya

Masuk ke Menu
1. Info desa/
2. Pemerintahan desa/
3. Ubah data/
4. Unggah foto....
5. Lalu simpan gambar yang sudah terupload ngak muncul....???

![image](https://user-images.githubusercontent.com/105429258/170930961-9ec46baa-05c6-4481-a4ce-d5fc000ee045.png)

### Hasil yg diharapkan

Harusnya Foto/gambar perangkat desa yang sudah terupload dan berhasil disimpan muncul previewnya seperti gambar dibawah ini :

![image](https://user-images.githubusercontent.com/105429258/170929738-d3eb16cb-e086-4226-905e-84262623eaaa.png)

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/105429258/170928690-6629792c-91f3-464a-9cbe-b93f548a545a.png)

Gambar yang sudah tersimpan/terupload ngak tampil

![image](https://user-images.githubusercontent.com/105429258/170929119-fcc5ab3b-6f80-4a48-8bcf-74012d4b2d85.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

22.05 Premium

### Tema Yang Digunakan

DeNatra 6.1

### Informasi tambahan

-

**Comment by agungsugiarto** [comment]
Pak @Pematung saya tidak mengalami masalah yg dimaksud di local maupun di berputar, apakah sudah memastikan foto yg diupload sudah berhasil terupload?

<img width="821" alt="image" src="https://user-images.githubusercontent.com/10989147/171105874-743f85f5-2617-4e17-afa6-64d99e46a674.png">

**Comment by Pematung** [comment]
Perdetik ini saya uji ngak bisa nyimpan foto perangkat desa pada menu info
desa/pemerintahan desa cek pada https://berputar.opendesa.id/pengurus
jangan pada yang lain......

Pada tanggal Sel, 31 Mei 2022 pukul 13.31 Andi Fahruddin Akas <
***@***.***> menulis:
