### ISSUE TITLE
Bug/error:  Impor Data Penduduk nik 0 Lebih dari 1 terbaca Ganda

### ISSUE THREAD

**Issue by ai-skematik** [OpenSID/OpenSID#5249]
### Jelaskan error yg dialami

Saat Impor Data Penduduk dengan nik 0 lebih dari 1, terbaca sebagai Nik Ganda.

### Cara untuk mereplikasi errornya

Impor Data Penduduk dengan beberapa Penduduk yang pada kolom nik di isi 0

### Hasil yg diharapkan

Semua Penduduk nik 0 berhasil di impor dan diganti dengan nik sementara.

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

21.04 Premium

### Tema Yang Digunakan

-

### Informasi tambahan

-

**Comment by yogiperdana** [comment]
Saya coba tidak ada masalah pak. Mohon contoh data yang dimaksud @ai-skematik

**Comment by ai-skematik** [comment]
ini tangkapan layarnya
![image](https://user-images.githubusercontent.com/48144047/172008109-c4e7d2c6-dec1-4126-88b3-6ef44478a307.png)

**Comment by yogiperdana** [comment]
Bisa tolong kirim datanya ke telegram saya pak? Saya coba isi 0 NIKnya akan berubah menjadi NIK sementara (datanya tidak ganda)

**Comment by ai-skematik** [comment]
@yogiperdana  sudah sy kirim di telegram

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melalui pr https://github.com/OpenSID/premium/pull/1069
