### ISSUE TITLE
Statistik data pemilih

### ISSUE THREAD

**Issue by Jehamahdan** [OpenSID/OpenSID#525]
Di opensid v. 2.2 sudah ada tambahan tab menu calon pemilih, mohon di tambah di tab menu statistik, statistik penduduk berdasarkan data calon pemilih. Terima kasih

**Comment by eddieridwan** [comment]
@Jehamahdan , permintaan anda perlu dilengkapi dengan rincian seperti apa laporan statistik yang diinginkan. Tanpa rincian, programmer tidak akan tahu apa yang anda perlukan.

**Comment by SansGuguh** [comment]
Rincian nya master yg dimaksud diatas, mungkin dilihat statistik nya lewat per dusun master. jadi lihat calon pemilih saat dipilih dusunnya entar muncul statistik jumlah penduduknya ada berapa ribu misalnya, dan dominan nya banyak perempuan apa lelaki. sperti begitulah mungkin master. thanx.

issues yang bagus.

**Comment by Jehamahdan** [comment]
Yup betul sperti yang di jelaskan bung Sans

**Comment by MUHAMMADRANGSEL** [comment]
Issue ini sdh dikerjakan dan perlu ditutup
