### ISSUE TITLE
Permintaan fitur: Menu Sub sub Menu

### ISSUE THREAD

**Issue by jonitrisulasmono** [OpenSID/OpenSID#5254]
### Apa kekurangan yg ingin diatasi?

Aplikasi website tidak dapat menambahkan anak sub menu, alias hanya dua tingkat saja. Menu dan Sub menu. Mungkin bisa ditambahkan fitur sub sub menu sampai empat level atau tidak terbatas.

### Jelaskan solusi yg diinginkan

Sub menu dapat ditambahkan sub menu lagi.
Contoh Menu:
Lembaga Desa --> Lembaga Kemasyarakatan Desa --> Satlinmas
                                                                                   --> TP-PKK
                                                                                   --> Karang Taruna
dst...

### Apakah ada alternatif lain

Tidak ada

### Untuk versi OpenSID mana

v.22.07-premium

### Informasi tambahan

Kami ingin membuat menu berdasarkan kelompok kategori kelembagaan, sehingga fitur ini bagi kami sangat diperlukan agar pengunjung mudah mencari informasi yang diinginkan.

Dengan adanya fitur ini, pembaca akan teredukasi secara langsung bahwa lembaga-lembaga di desa itu ada pengelompokannya.

**Comment by jonitrisulasmono** [comment]
ternyata sudah pernah ada isu serupa. namun saya sudah coba browsing, tidak menemukan solusinya. mohon informasi...

**Comment by andifahruddinakas** [comment]
Duplicate issue https://github.com/OpenSID/OpenSID/issues/7432
