### ISSUE TITLE
Bug/error: qr code surat memgarah ke github opensid

### ISSUE THREAD

**Issue by WAHYUDIK** [OpenSID/OpenSID#5255]
### Jelaskan error yg dialami

Qr code surat setelah di dscan mengarah ke github opensid, dan juga qi qrcode logo desa tidak tampil di tengah² qrcode

### Cara untuk mereplikasi errornya

Buat surat seperi biasanya kemudian cetak rtf, kemudian scan qrcode di surat tersebut

### Hasil yg diharapkan

Hasil scan qrcode kembali seperti semula, yakni mengarah ke validasi surat

### Tangkapan layar dan log error

![Uploading 16543122158432592079704876666183.jpg…]()
![Screenshot_2022-06-04-10-09-27-947_com xiaomi scanner](https://user-images.githubusercontent.com/31026980/171977734-9411d0c3-b772-43de-be03-cc20ebf8fe9c.jpg)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

V 22.06 premium

### Tema Yang Digunakan

Denatra 6.1

### Informasi tambahan

Gambar qrcode di arsip layanan juga tidak tampil
![16543123145327082136988404291806](https://user-images.githubusercontent.com/31026980/171977766-65f7b844-0d69-452b-bdaf-13c740794daa.jpg)

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melalui pr https://github.com/OpenSID/premium/pull/1067
