### ISSUE TITLE
Permintaan fitur: Sediakan Modul Display Informasi Desa

### ISSUE THREAD

**Issue by Pematung** [OpenSID/OpenSID#5257]
### Apa kekurangan yg ingin diatasi?

Belum ada modul untuk mengatur atau menampilkan display Informasi desa

### Jelaskan solusi yg diinginkan

Isian Display :

1. Berita
2. Agenda
3. Foto Galery dan Pembangunan
4. Video ( Yotube maupun Video Offline )
5. Statistik dll
6. Running Text
7. Jadwal Sholat
8. Pengaturan Tema Display

### Apakah ada alternatif lain

Alternatif lain saat ini dengan cara menggunakan Aplikasi Khusus dan dengan cara berkunjung langsung ke website desa menggunakan Dekstop atau Layanan Mandiri Android.

### Untuk versi OpenSID mana

Rilis 22.07 Premium

### Informasi tambahan

Kurang lebih tampilan Display Informasinya seperti ini di layar Monitor masing masing desa

![image](https://user-images.githubusercontent.com/105429258/172000418-a83b4d84-5303-4654-b0ae-d46917b2e3d1.png)

atau seperti ini juga bisa

![image](https://user-images.githubusercontent.com/105429258/172000646-ecae59f7-782b-46ce-a62c-da9d7eb5dca0.png)

**Comment by andifahruddinakas** [comment]
Ini sama dengan display anjungan

**Comment by abdoelsultengprov-commits** [comment]
bisakah dapat aplikasinya
