### ISSUE TITLE
Permintaan fitur: Tambahkan Lampiran F-2.01 Pada Format Suket Kelahiran & Kematian

### ISSUE THREAD

**Issue by Pematung** [OpenSID/OpenSID#5259]
### Apa kekurangan yg ingin diatasi?

Belum tersedianya Lampiran F.201 pada Suket Kelahiran dan Kematian

### Jelaskan solusi yg diinginkan

Sehubungan dengan banyaknya format baru yang dijadikan persyaratan utama pada setiap permohonan Adminduk di seluruh indonesia karena dengan adanya **SIAK Terpusat** begitu banyak format lampiran yang belom tersedia di Aplikasi OpenSID dan format ini amat sangat dibutuhkan oleh semua desa seperti lampiran dibawah ini.

**1. Lampiran F.201 Untuk Permohonan Akta Kelahiran**

![F201 Akta Kelahiran](https://user-images.githubusercontent.com/105429258/172020820-064f2da9-8122-46c8-b632-260e2b64736b.jpg)

**1. Lampiran F.201 Untuk Permohonan Akta Kematian**

![F201 Akta Kematian](https://user-images.githubusercontent.com/105429258/172020835-fc02b39a-9a45-428a-94e1-eddbac5bba1a.jpg)

### Apakah ada alternatif lain

Saat ini alternatif yang digunakan dengan cara mengisi formulir secara manual.

### Untuk versi OpenSID mana

Rilis 22.06 Premium

### Informasi tambahan

Ini kedua format LAMPIRAN yang dibutuhkan

[F.201 AKTA KELAHIRAN.pdf](https://github.com/OpenSID/OpenSID/files/8838428/F.201.AKTA.KELAHIRAN.pdf)

[F.201 AKTA KEMATIAN.pdf](https://github.com/OpenSID/OpenSID/files/8838429/F.201.AKTA.KEMATIAN.pdf)

**Comment by muhtar-coder** [comment]
Aturan terkait : 
https://peraturan.bpk.go.id/Home/Details/138575/permendagri-no-109-tahun-2019

**Comment by andifahruddinakas** [comment]
Mas @vickyrolanda, Dicek format mana yang harus dibuat, ada beberapa contoh file yang di lampirkan tapi berbeda. Tapi kalau sesuai aturan ada di halaman 48 (https://peraturan.bpk.go.id/Home/Details/138575/permendagri-no-109-tahun-2019) atau sama dengan https://github.com/OpenSID/OpenSID/files/9526633/Formulir-F2-01.pdf tp beda tampilan saja.

**Comment by vickyrolanda** [comment]
> Mas @vickyrolanda, Dicek format mana yang harus dibuat, ada beberapa contoh file yang di lampirkan tapi berbeda. Tapi kalau sesuai aturan ada di halaman 48 (https://peraturan.bpk.go.id/Home/Details/138575/permendagri-no-109-tahun-2019) atau sama dengan https://github.com/OpenSID/OpenSID/files/9526633/Formulir-F2-01.pdf tp beda tampilan saja.

Ketika saya cari di google semua sumber mengarah ke format lampiran F-2.01 (Formulir Pelaporan Pencatatan Sipil di Dalam Wilayah NKRI) bentuknya seprti ini  https://github.com/OpenSID/OpenSID/files/9526633/Formulir-F2-01.pdf  dan dibeberapa website .go.id juga melampikan itu dan ketika saya mencari formati F.201 malah tidak menemukan.

**Comment by agungsugiarto** [comment]
mas @vickyrolanda issue ini perlu dipecah untuk surat kelahiran dan kematian

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1843 hanya khusus ssuket kelahiran , sedangkan kematian akan di buatkan issue terpisah lagi. 

https://github.com/OpenSID/OpenSID/issues/6151
