### ISSUE TITLE
Permintaan fitur: Hilangkan Fitur Kosongkan Database

### ISSUE THREAD

**Issue by ai-skematik** [OpenSID/OpenSID#5260]
### Apa kekurangan yg ingin diatasi?

Saat ini ketika instal awal OpenSID tidak perlu lagi impor data awal karena database dibuat dengan query. sehingga fitur kosongkan database tidak diperlukan lagi.

### Jelaskan solusi yg diinginkan

Fitur kosongkan database dihilangkan karena fitur tersebut masih digunakan oleh desa yang opensidnya sudah digunakan untuk pelayanan. sehingga membuat database tidak konsisten.

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

22.06 Premium

### Informasi tambahan

![image](https://user-images.githubusercontent.com/48144047/172036897-b565afe5-d294-4bc0-ad7a-b81a1fbef50a.png)

**Comment by apidong** [comment]
@vickyrolanda @andifahruddinakas @agungsugiarto , sebaiknya ini dihapus atau hanya sekedar di disable menu nya?

**Comment by vickyrolanda** [comment]
> @vickyrolanda @andifahruddinakas @agungsugiarto , sebaiknya ini dihapus atau hanya sekedar di disable menu nya?

Sebaiknya jangan di hilangkan karena fitur ini digunakan untuk mereset data dan lagipula sudah ada konfirmasi dan informasi yang menyatakan seperti ini : 
<img width="483" alt="image" src="https://user-images.githubusercontent.com/59082428/178128994-34b84dc6-2278-42f1-9fa1-03dd189a4a75.png">

Pertimbangan yang harus diperhatikan adalah karena data default kita sediakan maka harus ada juga fungsi untuk mereset datanya sehingga ada timbal balik antara fungsi 1 sama lain kecuali kita tidak menyediakan data contoh maka tidak diperlukan fungsi ini.

adapun solusi yang bisa kita lakukan adalah membuat opsi data apa saja yang ingin di hapus seperti contoh berikut ini : 
<img width="697" alt="image" src="https://user-images.githubusercontent.com/59082428/178129172-26b11da1-e456-438c-b652-a9f9b43ce66b.png">

Contoh diatas hanya sebagai acuan saja mungkin opsinya bisa lebih banyak atau sesuai dengan data apa saja yg saat ini di hapus maka di pecah berdasarkan table data.

**Comment by eddieridwan** [comment]
@vickyrolanda  @apidong @andifahruddinakas @agungsugiarto , sejak rilis 22.06-premium sudah tidak lagi disediakan contoh data awal. Pada waktu install OpenSID pertama kali, sekarang dibuatkan database kosong. Jadi tidak diperlukan lagi fitur Kosongkan DB. Justru fitur itu selama ini menjadi sumber masalah, karena sulit menghapus data contoh secara konsisten, karena sering sudah bercampur dengan data desa betulan. 

Jadi fitur Kosongkan DB dihapus saja.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1119
