### ISSUE TITLE
Bug/error: Data lampiran surat tidak tampil

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#5261]
### Jelaskan error yg dialami

Cetak surat yang memiliki data lampiran, maka lampiran tersbut digenerate tanpa data.

### Cara untuk mereplikasi errornya

Buka surat > cetak surat yang memiliki lampiran

### Hasil yg diharapkan

Data lampiran muncul

### Tangkapan layar dan log error

.

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.06-premium

### Tema Yang Digunakan

bawaan

### Informasi tambahan

.

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melalui pr https://github.com/OpenSID/premium/pull/1071
