### ISSUE TITLE
Permintaan fitur: Menambahkan menu kode isian layanan surat di web administrator

### ISSUE THREAD

**Issue by reissapradhita123** [OpenSID/OpenSID#5262]
### Apa kekurangan yg ingin diatasi?

Agar bisa mengkustomisasi sendiri sehingga memudahkan pembuatan surat.

### Jelaskan solusi yg diinginkan

Menambahkan menu kode isian di web administrator bagian layanan surat.

### Apakah ada alternatif lain

Memudahkan kustomisasi pergantian jenis surat (kode isian)

### Untuk versi OpenSID mana

Versi diatas 22.06 (Update Selanjutnya)

**Comment by andifahruddinakas** [comment]
Sudah diterapkan pada surat jenis TinyMCE
