### ISSUE TITLE
Bug/error: POP up statistik pada peta wilayah dusun tidak tampil

### ISSUE THREAD

**Issue by agilbarker** [OpenSID/OpenSID#5263]
### Jelaskan error yg dialami

POP up statistik pada peta wilayah dusun tidak tampil ketika nama dusun menggunakan huruf terdiri dari dua kata yang mengandung spasi

### Cara untuk mereplikasi errornya

1. pergi ke admin
2. info pekon > wilayah administratif
3. tambahkan nama dusun,terdiri dari dua kata yang mengandung spasi, contoh (Sumber Agung, Sinar Baru)
4. buat peta wilayah dusun
5. cek pemetaan/halaman peta
6. cek statistik penduduk pada wilayah dusun

### Hasil yg diharapkan

POP up statistik muncul saat nama dusun mengandung spasi

### Tangkapan layar dan log error

![gambar](https://user-images.githubusercontent.com/60205674/172172568-23e26e76-dd3c-44fd-8a7d-06d5dcea49a7.png)
(wilayah dusun tidak tampil ketika ada ada spasi)

![gambar](https://user-images.githubusercontent.com/60205674/172173074-540324f7-a9f0-4e4a-b9c9-498338f0366a.png)
(wilayah dusun tampil ketika SPASI diganti dengan tanda STRIP

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

 22.05-premium-rev01 

### Tema Yang Digunakan

halaman admin pemetaan, semua thema bawaan sistem

### Informasi tambahan

.

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melalui pr https://github.com/OpenSID/premium/pull/1074
