### ISSUE TITLE
Bug/error: Status IDM Tidak dapat diperbaharui jika respon dari api idm kemendes tidak sesuai

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#5264]
### Jelaskan error yg dialami

Status IDM Tidak dapat diperbaharui jika respon dari api idm kemendes tidak sesuai

### Cara untuk mereplikasi errornya

Respon IDM Kemendes : 
```
{"header":{"scalar":false},"body":false}
```

### Hasil yg diharapkan

Tombol perbarui dapat digunakan

### Tangkapan layar dan log error

![coba](https://user-images.githubusercontent.com/57283157/172273881-4d13d260-374d-46dd-a3ba-3adf31de7480.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.06-premium

### Tema Yang Digunakan

bawaan

### Informasi tambahan

.

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melalui pr https://github.com/OpenSID/premium/pull/1073
