### ISSUE TITLE
Bug Masih Bisa Input Data Bantuan Sasaran Keluarga Yang Sudah Di Input

### ISSUE THREAD

**Issue by WAHYUDIK** [OpenSID/OpenSID#5265]
### Jelaskan error yg dialami

Input data peserta bantuan sasaran keluarga yang sudah terinput masih bisa di input kembali, sehingga besar kemungkinan bisa menyebabkan data pesertanya ganda, ini saya temukan ketika inout data peserta lebih dari 60 peserta

### Cara untuk mereplikasi errornya

Tambah jenis bantuan dengan sasaran keluarga, kemudian inpnut data peserta diatas 60 peserta, 

### Hasil yg diharapkan

Peserta bantuan yang sudah di input tidak bisa lagi di input sebagai peserta, agar tidak terjadi data ganda 

### Tangkapan layar dan log error

Tambah peserta bantuan

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

22. 06 premium

### Tema Yang Digunakan

Denatra

### Informasi tambahan

Saya coba lakukan beberapa kali logout n login, kemudian bersihkan cache, ganti browser masih terjadi bug tersebut. Kemudian saya coba restart laptop bug tersebut tidak jadi lagi, akan tetapi setelah saya coba pindah menu lain dan kembali inout data peserta bug tersebut terjadi lagi

**Comment by andifahruddinakas** [comment]
Pak @WAHYUDIK, sy sudah ikuti langkahnya, tp sy tidak menemukan bug ini.

![bantuan 1](https://user-images.githubusercontent.com/57283157/172735952-7f19b7f0-428b-4c4f-a61d-0d928b83e400.png)

Saat menambah kan data peserta data yg sudah di input tdk muncul.

**Comment by eddieridwan** [comment]
@andifahruddinakas , mungkin periksa database dari @WAHYUDIK untuk memastikan masuk ganda tersebut. Kemudian juga lihat apakah bisa buat key multi-kolom (kolom `peserta` dan `program_id`) di tabel program peserta untuk membuat unik (yaitu supaya kombinasi program dan peserta ganda tidak mungkin masuk ke tabel). Jika lakukan itu pastikan pesan gagal jelas sebabnya. Dan migrasi juga perlu antisipasi adanya data ganda di database desa -- dalam hal ini sepertinya bisa dihapus satu, tentunya dengan melaporkan yg mana yg dihapus.

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melalui pr https://github.com/OpenSID/premium/pull/1078
