### ISSUE TITLE
Permintaan fitur: penambangan kolom tag id card di menu data pemilih

### ISSUE THREAD

**Issue by Fajar-blackdeath** [OpenSID/OpenSID#5266]
### Apa kekurangan yg ingin diatasi?

di lampung sudah melakukan e voting berbasis e ktp. untuk memudahakan pendataan data penduduk dan melihat saiapa yang belum rekam ktp. mohon di tambahkan kolom tag id card di donwnload data pemilih.

### Jelaskan solusi yg diinginkan

di lampung sudah melakukan e voting berbasis e ktp. untuk memudahakan pendataan data penduduk dan melihat saiapa yang belum rekam ktp. mohon di tambahkan kolom tag id card di donwnload data pemilih.

### Apakah ada alternatif lain

di lampung sudah melakukan e voting berbasis e ktp. untuk memudahakan pendataan data penduduk dan melihat saiapa yang belum rekam ktp. mohon di tambahkan kolom tag id card di donwnload data pemilih.

### Untuk versi OpenSID mana

22.07 premium

### Informasi tambahan

di lampung sudah melakukan e voting berbasis e ktp. untuk memudahakan pendataan data penduduk dan melihat saiapa yang belum rekam ktp. mohon di tambahkan kolom tag id card di donwnload data pemilih.

**Comment by andifahruddinakas** [comment]
Solusi Tambahan : 
Agar tidak berulang issue yang sama mengenai penambahan field / data yang akan ditampilkan, buat agar kolom bisa di atur secara dinamis

**Comment by ariandii** [comment]
<img width="960" alt="image" src="https://user-images.githubusercontent.com/46939846/173297045-1b5eaf4e-ebc0-4efa-8eec-e827968face4.png">

**Comment by ariandii** [comment]
<img width="960" alt="image" src="https://user-images.githubusercontent.com/46939846/173297235-3cea62ac-f065-48cb-9e48-c776c166e9b4.png">

**Comment by andifahruddinakas** [comment]
Penambahan untuk issue ini :
- [x] Informasi tag_id _card pada modul dpt (index, unduh/cetak)
- [x] Filter tag_id _card

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1143
