### ISSUE TITLE
Bug/error: isian  Jumlah biaya pembangunan tidak bisa lebih dari 9 digit

### ISSUE THREAD

**Issue by muhtar-coder** [OpenSID/OpenSID#5267]
### Jelaskan error yg dialami

isian jumlah anggaran tidak bisa di isi dengan digit lebih dari 9 digit, sedangkan terdapat pembangunan yang sumber dana nya dari selain desa dengan jumlah anggaran lebih dari angka ratusan juta.

### Cara untuk mereplikasi errornya

Misal buat isian dokumentasi pembangunan jalan dengan sumber dana tunggal dari kabupaten/dinas PU, angka terbatas  hanya 9 digit sedangkan dana anggaran adalah misal 10 digit/milyar rupiah

### Hasil yg diharapkan

fleksibel sesuai jumlah anggaran yang harus di isi

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/55665526/172904346-66c1d65b-ffea-47c9-a620-15bce833ccdc.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

22.05 rev02

### Tema Yang Digunakan

-

### Informasi tambahan

-

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melalui pr https://github.com/OpenSID/premium/pull/1079
