### ISSUE TITLE
Bug/error: gagal buka halaman jika tidak bisa akses layanan

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#5268]
### Jelaskan error yg dialami

Gejalanya setelah login selalu kembali ke halaman Home, atau tiba-tiba kembali ke halaman Home.

Dan di log ada pesan sbb:
```
ERROR - 2022-06-10 06:25:25 --> Severity: error --> Exception: Argument 1 passed to calculate_date_intervals() must be of the type array, null given, called in /home/n1083785/public_html/sampano.desa.id/donjo-app/models/Notif_model.php on line 67 /home/n1083785/public_html/sampano.desa.id/donjo-app/helpers/general_helper.php 204
```

### Cara untuk mereplikasi errornya

1. Server tidak bisa akses Layanan
2. Di cache layanan tersimpan response yg tidak lengkap
3. Login
4. Perhatikan kembali ke halaman Home

### Hasil yg diharapkan

Ada pesan error yg jelas jika layanan tidak bisa diakses dan jika cache berisi info yg tidak lengkap.

### Tangkapan layar dan log error

Masalahnya sepertinya ada di sini:

<img width="1377" alt="image" src="https://user-images.githubusercontent.com/249563/173022029-03339ff8-39e8-4d6a-8706-b03787efe3e3.png">

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.06-premium

**Comment by andifahruddinakas** [comment]
Pak @eddieridwan, sama dengan issue https://github.com/OpenSID/OpenSID/issues/5200, berkaitan dengan respon layanan yang di simpan di cache tidak sesuai dengan format yang seharunya.

**Comment by FirlianiF** [comment]
pak @eddieridwan bisa minta tolong kirimkan isi dari cache layanan yang tidak lengkap nya itu seperti apa ya pak?

mas @vickyrolanda bisa minta tolong analisis untuk replikasi nya seperti apa? karena saya tidak mengalami setelah login selalu kembali ke halaman Home, atau tiba-tiba kembali ke halaman Home.

**Comment by eddieridwan** [comment]
@FirlianiF maaf tidak disimpan. Tapi coba replikasi dengan mengubah cache layanan supaya isinya tidak lengkap. Intinya sebaiknya method calculate_date_interval perlu antisipasi nilai yg dikirim tidak valid.

**Comment by scqolbu24** [comment]
sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/1175
