### ISSUE TITLE
Terjadi error saat ubah artikel

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#5269]
1. Buat group baru dengan akses modul artikel
2. Buat user
3. Login dan buat artikel
4. Ubahn artikel yang sudah di buat
5. Terjadi error berikut :
`ERROR - 2022-06-12 14:44:06 --> Query error: Unknown column 'a.id_user' in 'where clause' - Invalid query: SELECT *
FROM `artikel`
WHERE `a`.`id_user` = '8'
AND `id` != '167'
AND `slug` = 'laporan-realisasi-apbds-2'`

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melalui pr https://github.com/OpenSID/premium/pull/1085
