### ISSUE TITLE
Permintaan fitur: sesuaikan alur pemeriksaan surat

### ISSUE THREAD

**Issue by yogiperdana** [OpenSID/OpenSID#5270]
### Apa kekurangan yg ingin diatasi?

Saat ini surat dicetak tanpa diperiksa oleh kasi pelayanan umum dan sekretaris desa. Untuk menerapkan TTE, alur pemeriksaan surat harus melalui kasi pelayanan umum dan sekretaris desa

### Jelaskan solusi yg diinginkan

Setiap surat yang dicetak akan melalui beberapa tahap pemeriksaan. Dari kasi pelayanan umum dan sekretaris desa. Setelah itu baru ditandatangani oleh kepala desa. Dokumen yang telah ditandatangani akan tersimpan dalam bentuk pdf pada arsip surat.

Bagi desa yang belum menggunakan TTE, surat akan dicetak dan masuk ke arsip surat (tidak dalam bentuk pdf).

Proses pemeriksaan dapat disesuaikan kebutuhan

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

-

**Comment by apidong** [comment]
@vickyrolanda pak, mohon di lampirkan screenshot saat verifikasi.

**Comment by apidong** [comment]
hal-hal yang perlu di diperhatikan : 
- surat yang sudah diverifikasi oleh operator, tidak bisa di edit maupun dihapus
- surat yang ditolak oleh kepala desa / sekdes. surat bisa diedit kembali untuk diperbaiki.
- saat surat sudah di setujui oleh operator, surat sudah tersimpan dalam bentuk pdf di server.
- alur verifikasi bisa dilewati, semisal dari operator langsung ke Kepala desa.

Migrasi :
- tambahkan kolom verifikasi_sekdesa, verifikasi_kepdesa, verifikasi_tte pada tabel log_surat.
- tambahkan migrasi untuk tambahkan setting verif_kades, verif_sekdes, verif_operator. 

Lain lain : 
- tambahkan pengaturan ke modul pengaturan aplikasi meliputi :
  a. atur Verifikasi oleh kades (otomatis aktif dan tidak bisa diubah jika modul tte aktif)
  b. atur verifikasi oleh sekdes 
  c. atur verifikasi oleh operator (Hanya untuk layanan mandiri).


Tampilan :

**Comment by apidong** [comment]
untuk simpan pdf, ada di issue tersendiri

**Comment by vickyrolanda** [comment]
> @vickyrolanda pak, mohon di lampirkan screenshot saat verifikasi.

- [ ] Dari Pelayanan Umum ke Sekdes : bisa model seperti ini : 
<img width="561" alt="image" src="https://user-images.githubusercontent.com/59082428/180594483-d4431943-8ef4-4d4b-b545-8a70ecef8dcb.png">

- [ ] Untuk TTD Kepala Desa Modelnya seperti ini : 
<img width="773" alt="image" src="https://user-images.githubusercontent.com/59082428/180594391-f3132b1d-416f-4cc1-b83f-62cd64237b77.png">
 Atau bisa juga ke halaman tersendiri .

**Comment by eddieridwan** [comment]
@apidong @vickyrolanda @devrakapriyo penjelasan alur pemeriksaan surat.

1. Pengaturan alur berlaku pada setiap jenis surat, bukan opsional pada saat mencetak surat. Yaitu alur diatur pada Pengaturan Surat bukan pada waktu mencetak surat. Alur yg ditentukan harus dipatuhi untuk setiap permohonan/pencetakan surat.
2. Pengaturan Alur diberi opsi:
    1. Operator saja, seperti sekarang. Yaitu setelah disetujui Operator, surat dicetak dan dibawa ke Kades secara fisik untuk ditandatangani. Opsi ini default jika TTE tidak aktif. Opsi ini tidak valid jika TTE aktif.
    2. Operator -> Kades. Setelah surat disetujui Operator, beri notifikasi surat akan diteruskan ke Kades. Jika Kades menolak surat, kembalikan ke Operator untuk diperbaiki. Ini default jika TTE aktif.
    3. Operator -> Sekdes -> Kades. Setelah surat disetujui Operator, beri notifikasi surat akan diteruskan ke Sekdes. Jika Sekdes menolak surat, kembalikan ke Operator untuk diperbaiki. Jika Sekdes menyetujui, beri notifikasi surat akan diteruskan ke Kades. Jika Kades menolak surat, kembalikan ke Operator untuk diperbaiki.
3. Untuk alur selain opsi (i) di atas, asumsi pejabat Kades/Sekdes telah ditentukan, termasuk pengguna masing2 jabatan.
4. Pemeriksaan surat oleh Operator, Sekdes atau Kades harus bisa melihat isi surat dan dokumen persyaratan. 
5. Pindahkan modul Permohonan Surat dari Layanan Mandiri ke menu Layanan Surat. 
6. Status surat ada di mana (Operator, Sekdes atau Kades) dapat dilihat di Layanan Surat > Permohonan Surat.
7. Surat masuk ke Arsip Layanan hanya setelah melalui semua langkah alur yg ditentukan. Yaitu, untuk opsi (i) setelah disetujui Operator; opsi (ii) dan (iii) setelah disetujui Kades. Yaitu Arsip Layanan tempat melihat semua surat yg telah final; sedangkan Permohonan Surat tempat melihat surat yg masih dalam proses.

**Comment by vickyrolanda** [comment]
> @apidong @vickyrolanda @devrakapriyo penjelasan alur pemeriksaan surat.
> 
> 1. Pengaturan alur berlaku pada setiap jenis surat, bukan opsional pada saat mencetak surat. Yaitu alur diatur pada Pengaturan Surat bukan pada waktu mencetak surat. Alur yg ditentukan harus dipatuhi untuk setiap permohonan/pencetakan surat.
> 2. Pengaturan Alur diberi opsi:
>    
>    1. Operator saja, seperti sekarang. Yaitu setelah disetujui Operator, surat dicetak dan dibawa ke Kades secara fisik untuk ditandatangani. Opsi ini default jika TTE tidak aktif. Opsi ini tidak valid jika TTE aktif.
>    2. Operator -> Kades. Setelah surat disetujui Operator, beri notifikasi surat akan diteruskan ke Kades. Jika Kades menolak surat, kembalikan ke Operator untuk diperbaiki. Ini default jika TTE aktif.
>    3. Operator -> Sekdes -> Kades. Setelah surat disetujui Operator, beri notifikasi surat akan diteruskan ke Sekdes. Jika Sekdes menolak surat, kembalikan ke Operator untuk diperbaiki. Jika Sekdes menyetujui, beri notifikasi surat akan diteruskan ke Kades. Jika Kades menolak surat, kembalikan ke Operator untuk diperbaiki.
> 3. Untuk alur selain opsi (i) di atas, asumsi pejabat Kades/Sekdes telah ditentukan, termasuk pengguna masing2 jabatan.
> 4. Pemeriksaan surat oleh Operator, Sekdes atau Kades harus bisa melihat isi surat dan dokumen persyaratan.
> 5. Pindahkan modul Permohonan Surat dari Layanan Mandiri ke menu Layanan Surat.
> 6. Status surat ada di mana (Operator, Sekdes atau Kades) dapat dilihat di Layanan Surat > Permohonan Surat.
> 7. Surat masuk ke Arsip Layanan hanya setelah melalui semua langkah alur yg ditentukan. Yaitu, untuk opsi (i) setelah disetujui Operator; opsi (ii) dan (iii) setelah disetujui Kades. Yaitu Arsip Layanan tempat melihat semua surat yg telah final; sedangkan Permohonan Surat tempat melihat surat yg masih dalam proses.

baik pak.

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/1148
