### ISSUE TITLE
Permintaan fitur: sesuaikan alur pemeriksaan surat pada layanan mandiri

### ISSUE THREAD

**Issue by yogiperdana** [OpenSID/OpenSID#5271]
### Apa kekurangan yg ingin diatasi?

Saat ini surat dicetak tanpa diperiksa oleh kasi pelayanan umum dan sekretaris desa. Untuk menerapkan TTE, alur pemeriksaan surat harus melalui kasi pelayanan umum dan sekretaris desa

### Jelaskan solusi yg diinginkan

Setiap permohonan surat yang dilakukan oleh warga akan melalui beberapa tahap pemeriksaan. Dari kasi pelayanan umum dan sekretaris desa. Setelah itu baru ditandatangani oleh kepala desa. Dokumen yang telah ditandatangani akan tersimpan dalam bentuk pdf pada arsip surat.

Bagi desa yang belum menggunakan TTE, surat akan dicetak dan masuk ke arsip surat (tidak dalam bentuk pdf).

Proses pemeriksaan dapat disesuaikan kebutuhan

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

-

**Comment by yogiperdana** [comment]
Apakah alur pemeriksaan ini dibuat hanya untuk surat tinymce atau sekalian surat rtf? Dan setelah diperiksa surat tinymce belum bisa diajukan dari layanan mandiri.

Jika alur pemeriksaan juga berlaku untuk surat tinymce, artinya perlu untuk menyelesaikan issue https://github.com/OpenSID/OpenSID/issues/5304 terlebih dahulu untuk menyelesaikan issue ini.

Bagaimana kira kira pak @eddieridwan dan @vickyrolanda

**Comment by vickyrolanda** [comment]
> Apakah alur pemeriksaan ini dibuat hanya untuk surat tinymce atau sekalian surat rtf? Dan setelah diperiksa surat tinymce belum bisa diajukan dari layanan mandiri.
> 
> Jika alur pemeriksaan juga berlaku untuk surat tinymce, artinya perlu untuk menyelesaikan issue #5304 terlebih dahulu untuk menyelesaikan issue ini.
> 
> Bagaimana kira kira pak @eddieridwan dan @vickyrolanda

kalo untuk TTE saat ini kita terapkan hanya untuk TinyMce mas yogi, itu ada mas @apidong sudah buat alur surat di pr https://github.com/OpenSID/premium/pull/1148 mungkin untuk pelayanan umum bisa mengikutin itu mas yogi, saat ini penerapan tinymce harus generate pdf ke directory dan itu juga sudah di kerjain di PR https://github.com/OpenSID/premium/pull/1151 , 

jadi untuk surat rtf mengikutin alur yang ada tpi tidak untuk penerapan TTE mas yogi.

**Comment by yogiperdana** [comment]
Mas @vickyrolanda nanti setelah PR https://github.com/OpenSID/premium/pull/1148 digabung. Minta tolong buatkan ceklis apa saja yang harus dikerjakan untuk issue ini ya mas

**Comment by andifahruddinakas** [comment]
Berkaitan dengan issue dan diperlukan https://github.com/OpenSID/OpenSID/issues/5304

**Comment by vickyrolanda** [comment]
Fitur surat layanan mandiri adalah permohonan langsung dari warga dimana surat dapat di pilih dan di ajukan untuk dibuat oleh warga, saat ini permohonan surat layanan mandiri berdiri sendiri dimana perubahan status ada di permohonan surat di menu layanan mandiri saat ini ada beberapa status dalam permohonan surat layanan mandiri : 
- Sedang diperiksa (status ini adalah status awal ketika permohoan di ajukan ke opensid)
- Belum lengkap ( status ini akan memberikan akses ke warga untuk melengkapi data yang di butuhkan )
- Menunggu tanda tangan (status ini untuk memberitahu bahwa surat sudah masuk daftar menggu tanda tangan)
- Siap diambail (artinya surat sudah di tanda tangan dan status diganti menjadi siap diambil agar warga tau bahwa surat sudah siap)
- Sudah diambil (ketika surat sudah diambil maka operator bisa mengganti status menjadi sudah diambil agar tidak terjadi kesalah pahaman antara operator & warga bahwa surat sudah di ambil)
- Dibatalkan (dibatalkan artinya surat dibatalkan oleh operator)

Status diatas dapat di sesuaikan dengan arsip layanan yang ada di layanan surat seperti 

[ ]  Ketika surat sudah tidak ada perubahan dan sudah lengkap maka permohonan di terima ketika diterima saat ini permohonan surat masuk ke arsip layanan, maka agar tidak terjadi double fungsi atau 2 x action di operator maka bisa di lakukan .
[ ]  jika surat diterima & di kirim ke arsip / ke sekdes / kades maka status di permohonan mandiri diubah menjadi ( Menunggu tanda tangan ) 
[ ] Jika surat sudah di tanda tangan dan masuk ke arsip maka status di permohonan mandiri diubah menjadi (siap diambil)
[ ] Jika surat sudah masuk layanan surat lalu di batalkan maka status di permohonan mandiri menjadi (dibatalkan )

namun untuk merubah status sudah diambil, dibatalkan & belum lengkap tetap bisa ada di layanan mandiri.

sehingga tidak perlu ada penambah dari sisi migrasinya. 
kira - kira ada yang kurang paham bisa di kabari ya mas @yogiperdana

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1212
