### ISSUE TITLE
Bug/error: tidak bisa tampilkan feed

### ISSUE THREAD

**Issue by apidong** [OpenSID/OpenSID#5272]
### Jelaskan error yg dialami

error 500 saat akses https://berputar.opendesa.id/index.php/feed

### Cara untuk mereplikasi errornya

masuk ke https://berputar.opendesa.id/index.php/feed

### Hasil yg diharapkan

halaman feed tampil

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/20056421/173289474-4094d3dd-227a-491e-84aa-11d1169ba9ca.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

22.06 premium

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/1087
