### ISSUE TITLE
Permintaan fitur: buat notifikasi ketika ada surat permintaan surat untuk diperiksa atau ditandatangani

### ISSUE THREAD

**Issue by yogiperdana** [OpenSID/OpenSID#5273]
### Apa kekurangan yg ingin diatasi?

Saat ini belum ada notifikasi daftar surat yang belum diperiksa dan tandatangani

### Jelaskan solusi yg diinginkan

Terdapat notifikasi untuk setiap permintaan surat baik untuk diperiksa atau ditandatangani

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

-

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1156
