### ISSUE TITLE
Permintaan fitur: Bisa tambah anggota rumah tangga bersumber dari daftar nama di kartu keluarga kepala rumah tangga

### ISSUE THREAD

**Issue by muhtar-coder** [OpenSID/OpenSID#5274]
### Apa kekurangan yg ingin diatasi?

Saat menambahkan anggota rumah tangga terkadang lupa nama dan harus mengingat-ingat nama istri/nama keluarga lain dan kadang harus buka data keluarga karena tidak ingat nama anggota rumah tangga sesuai yang berada di kartu keluarga.

### Jelaskan solusi yg diinginkan

Ketika akan menambahkan anggota rumah tangga,selain menggunakan tombol cari yang sudah ada, agar di sediakan opsi tambah berupa kolom ceklis yang sumber data nya dari kartu keluarga nya si kepala rumah tangga (jika bukan KK tunggal).
tentunya secara otomatis menjadi sebagai anggota rumah tangga.

![image](https://user-images.githubusercontent.com/55665526/173492565-b3f6a20f-078a-48d8-9dda-c49b19956402.png)

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

v22.07 premium

### Informasi tambahan

untuk memudahkan saja, karena saat menambahkan anggota rumah tangga nama yang akan di inputkan lupa, tentunya harus bolak balik ke menu keluarga/KK

**Comment by eddieridwan** [comment]
@muhtar-coder fitur sebagaimana diminta tidak bisa diterapkan, karena info keluarga keluarga hanya diketahui setelah anggota rumah tangga telah dimasukkan.

Alternatifnya mungkin dengan menampilkan hasil scan kartu keluarga, jika telah diunggah sebagai kelengkapan kependudukan bagi kepala keluarga ybs.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1354
