### ISSUE TITLE
Tambahkan grafik kependudukan setiap tahun

### ISSUE THREAD

**Issue by ridwan-opt** [OpenSID/OpenSID#5275]
### Apa kekurangan yg ingin diatasi?

Tambahkan setatistik/grafik kependudukan yang bisa di filter berdasarkan grafik bulan ataupun tahun

### Jelaskan solusi yg diinginkan

.

### Apakah ada alternatif lain

.

### Untuk versi OpenSID mana

22.07-premium

**Comment by balongbesuk** [comment]
sama gak dg yang ini?

https://github.com/OpenSID/OpenSID/issues/3983

**Comment by andifahruddinakas** [comment]
Duplicate issue https://github.com/OpenSID/OpenSID/issues/3983
