### ISSUE TITLE
Masih bisa hapus pengguna yg sudah lakukan absensi

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#5277]
awal ya si A adalah aparatur desa ber ID Pamong 26

lalu sudah dihubungkan ke akun pengguna dan praktek kehadiran sukses (rekaman kehadiran ada beberapa hari).

kemudian si A tidak sengaja terhapus di data Pemerintahan Desa. kemudian si A dibuat ulang sebagai aparatur desa dengan ID baru 27.

sehingga di rekam kehadiran yg sudah ada beberapa hari, awalnya ID 26 saya ubah semua ke 27.

**Comment by andifahruddinakas** [comment]
Solusi : 
- Buat softdelete
atau
- Cek agar tidak dapat dihapus

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melalui pr https://github.com/OpenSID/premium/pull/1092
