### ISSUE TITLE
Permintaan fitur: Sering terjadi Folder desa yang kurang sehingga upload tidak dapat dilakukan

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#5278]
### Apa kekurangan yg ingin diatasi?

pada grup opensid sering menemukan pengguna desa yang gagal upload file gambar setelah d cek folder upload tidak sesuai dengan folder desa contoh sehingga muncul error

### Jelaskan solusi yg diinginkan

agar ketika upload gambar ketika folder yang dimaksud tidak ada bisa d buat otomatis oleh opensid

atau

ketika opensid update juga mengecek apakah folder desa adaa yang kurang atau tidak dan bisa d buatkan otomatis

atau

muncul peringatan folder desa kurang lengkap silakaan contoh folder desa bawaan opensid

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

umum dan premium

### Informasi tambahan

-

**Comment by eddieridwan** [comment]
@balongbesuk perhatikan bahwa di 22.06-premium, tidak ada lagi contoh folder desa, karena folder desa dibuat otomatis pada waktu install OpenSID. Jadi seharusnya masalah ini tidak terjadi lagi di versi Premium. Untuk versi Umum, tinggal tunggu saja sampai perubahan tersebut sudah masuk ke versi Umum.

**Comment by andifahruddinakas** [comment]
Setiap jalankam migrasi selalu di cek kelengkapan dari isi folder desa dan akan slalu disesuaikan.

Sudah diterapkan di versi v22.06-premium
