### ISSUE TITLE
Bug/error: An Ub pada menu permohonan surat tidak muncul

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#5279]
### Jelaskan error yg dialami

ketika operator desa memeriksa permohonan surat warga ketika ini mencetak an '/ ub datany tidak muncul

### Cara untuk mereplikasi errornya

layanan mandiri > permohonan surat > periksa permohonan surat masuk > pilih atas nama > kosong

### Hasil yg diharapkan

atas nama terisi

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/35319600/174018956-6dccf8d6-52f1-4e57-b51b-a747c89967c2.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

berputar

### Tema Yang Digunakan

-

### Informasi tambahan

-

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melalui pr https://github.com/OpenSID/premium/pull/1090
