### ISSUE TITLE
Permintaan fitur: sediakan master analisis untuk pengisian blangko pendataan DTKS

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#5281]
### Apa kekurangan yg ingin diatasi?

Data DTKS telah muncul sebagai sumber data penting bagi berbagai instansi supra-desa untuk merencanakan dan intervensi penanggulangan kemisikinan. Saat ini di OpenSID belum tersedia master analisis untuk pendataan DTKS tersebut.

### Jelaskan solusi yg diinginkan

Sediakan master analisis untuk pendataan DTKS. Idealnya menggunakan format tahun 2022. Yg ditemukan saat ini baru format DTKS tahun 2020. Sediakan sebagai master analisis bawaan sistem.

[Form_BDT.pdf](https://github.com/OpenSID/OpenSID/files/8925130/Form_BDT.pdf)

### Apakah ada alternatif lain

Lakukan pendaftaan menggunakan alat bantu selain OpenSID.

### Untuk versi OpenSID mana

v22.06-premium

### Informasi tambahan

Ada kemungkinan penerapan master analisis DTKS 2020 akan memerlukan penambahan fitur di OpenSID, misalnya untuk secara otomatis mengisi data dari data kependudukan yang sudah tersimpan di OpenSID atau menyusun/menghitung data berdasarkan data kependudukan tsb.

**Comment by eddieridwan** [comment]
Contoh master analisis BDT dari Rarang Selatan:

[Analisis BDT Penduduk 2018.xls](https://github.com/OpenSID/OpenSID/files/9145690/Analisis.BDT.Penduduk.2018.xls)
[Analisis BDT Rumah Tangga 2018.xls](https://github.com/OpenSID/OpenSID/files/9145691/Analisis.BDT.Rumah.Tangga.2018.xls)

Panduannya:

[PANDUAN INTEGRASI DATA BDT KEDALAM SID.pdf](https://github.com/OpenSID/OpenSID/files/9145699/PANDUAN.INTEGRASI.DATA.BDT.KEDALAM.SID.pdf)

**Comment by andifahruddinakas** [comment]
Sudah ada modul tersendiri
