### ISSUE TITLE
Demo: di website demo tampilkan data contoh yg lengkap

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#5284]
### Apa kekurangan yg ingin diatasi?

Saat ini di website https://demosid.opendesa.id/ dan https://berputar.opendesa.id/ data contoh yg ditampilkan adalah data contoh awal terbatas pada waktu install OpenSID. Data ini kurang memperlihatkan potensi OpenSID.

### Jelaskan solusi yg diinginkan

Di website demo, tampilkan data contoh lengkap. Gunakan data desa yg bersedia berbagi, yang diacak supaya menjaga privasi data penduduk. 

### Apakah ada alternatif lain

Tetap dengan data contoh terbatas saat ini.

### Untuk versi OpenSID mana

v22.06-premium

### Informasi tambahan

Untuk mengurangi beban pada waktu memperbaharui database demo setiap hari, bisa simpan data contoh di database, sehingga bisa hapus+copy database setiap hari. Yaitu tidak membaca dari file .sql  setiap hari.

**Comment by balongbesuk** [comment]
tambahan

tambahkan contoh penduduk dengan status mati agar dapat mencoba test surat kematian
