### ISSUE TITLE
Bug/error: Perbaiki notifikasi status langganan

### ISSUE THREAD

**Issue by FirlianiF** [OpenSID/OpenSID#5285]
### Jelaskan error yg dialami

-

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

22.06

**Comment by scqolbu24** [comment]
sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/1094
