### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'settings')

### ISSUE THREAD

**Issue by apidong** [OpenSID/OpenSID#5286]
### Jelaskan error yg dialami

![image](https://user-images.githubusercontent.com/20056421/175561640-d54968bf-8d89-493e-ab38-a4286ca5022c.png)

Uncaught TypeError: Cannot read properties of undefined (reading 'settings')

### Cara untuk mereplikasi errornya

buka modul pengaturan surat, dan buat sebuat template surat baru

### Hasil yg diharapkan

tidak ada error di console 

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

-

### Tema Yang Digunakan

-

### Informasi tambahan

-

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melalui pr https://github.com/OpenSID/premium/pull/1095/files
