### ISSUE TITLE
Bug/error: Pada Surat Keterangan Pindah Penduduk

### ISSUE THREAD

**Issue by Pematung** [OpenSID/OpenSID#5287]
### Jelaskan error yg dialami

Ada Bug Pada Format Surat Keterangan Pindah Penduduk

### Cara untuk mereplikasi errornya

1. Pergi ke Layanan Surat
2. Cetak Surat
3. Surat Keterangan Pindah Penduduk
4. Pilih Pemohon
5. Pilih Gunakan Format
6. Maka Menu Pilihan Klasifikasi Pindah Akan Hilang

![image](https://user-images.githubusercontent.com/105429258/175617978-e98cc5bc-f4bb-45ac-a324-2d73cd13e8ed.png)

### Hasil yg diharapkan

Harusnya Pilihan Klasifikasi Pindah Tidak Hilang Saat Memilih Pilih Format

![image](https://user-images.githubusercontent.com/105429258/175618299-dbe112fa-40d7-490d-948f-315f125a76ad.png)

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/105429258/175618579-e080b445-a824-41bf-8afd-2003dacfc25d.png)

Klaifikasi Pindah Kosong

![image](https://user-images.githubusercontent.com/105429258/175621193-cf45904a-de9a-4b2e-9689-7e8e94951c9b.png)

Pemohon Harusnya Yang Pindah Namun yang Tampil Kepala Keluarganya dan Nomor 
Surat Juga Ngak Otomatis Terbaca

![image](https://user-images.githubusercontent.com/105429258/175625087-e73f0f24-ab53-4736-ad4f-1d676b39d44a.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

22.06 Premium Rev02

### Tema Yang Digunakan

Batuah & Denatra 6.2

### Informasi tambahan

-

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melalui pr https://github.com/OpenSID/premium/pull/1098
