### ISSUE TITLE
Bug/error: Tanggal lahir jadi tahun 1970 jika form tidak di isi perkiraan tgl lahir

### ISSUE THREAD

**Issue by yogiperdana** [OpenSID/OpenSID#5288]
### Jelaskan error yg dialami

Tanggal lahir jadi tahun 1970 jika form tidak di isi perkiraan tgl lahir di ibu hamil stunting

### Cara untuk mereplikasi errornya

Masuk modul kesehatan > stunting > ibu hamil > tambah/edit lalu submit

### Hasil yg diharapkan

Berjalan normal

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/14155050/175799518-c04caf11-212a-496c-9755-77ee53fe6a03.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.06-premium

**Comment by Wiliyantoro** [comment]
Kalau bisa isi otomatis prediksi lahir di ambil dari usia kehamilan jika form prediksi lahir kosong

**Comment by yogiperdana** [comment]
> Kalau bisa isi otomatis prediksi lahir di ambil dari usia kehamilan jika form prediksi lahir kosong

Form prediksi lahir maksudnya yang ya pak? Saat menginput KIA form hari/tanggal perkiraan lahir tidak bisa kosong jika belum melahirkan. Lalu untuk prediksi lahir setau saya itu diambil dari catatan saat USG kehamilan pak (bukan berdasarkan usia kehamilan saat ini)

**Comment by Wiliyantoro** [comment]
nah form yang tidak required prediksi lahir kan di pemantauan ibu hamil bulanan pak, sebenarnya saat tambah KIA sudah ada pilihan prediksi lahir, saya belum bisa coba untuk tambah ibu hamil karena masih bug itu

**Comment by yogiperdana** [comment]
> nah form yang tidak required prediksi lahir kan di pemantauan ibu hamil bulanan pak, sebenarnya saat tambah KIA sudah ada pilihan prediksi lahir, saya belum bisa coba untuk tambah ibu hamil karena masih bug itu

Saat menginput data ibu hamil itu form melahirkan pak (bukan perkiraan atau prediksi)

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melalui pr https://github.com/OpenSID/premium/pull/1100
