### ISSUE TITLE
Gagal install v22.06-premium di share hosting

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#5289]
Lakukan instalasi OpenSID v2206-premium menggunakan cara install baru (Menggunakan Seeder).

Akan terjadi error, beberapa tabel tidak lengkap. Namun status instalasi berhasil.

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melalui pr https://github.com/OpenSID/premium/pull/1089
