### ISSUE TITLE
Data isian Pembangunan tidak dapat tersimpan untuk nilai anggaran diatas 2,1M

### ISSUE THREAD

**Issue by bing609** [OpenSID/OpenSID#5290]
### Jelaskan error yg dialami

Pada menu Pembangunan, tambah data baru, tidak dapat tersimpan untuk nilai anggaran yg diisi lebih dari 2,1M.
Saat sudah terimpan untuk isian dengan anggaran 2,1M tersebut, tidak dapat diedit atau diubah nilainya lebih dari 2,1M.

### Cara untuk mereplikasi errornya

1. Buka menu Pembangunan
2. Tambah data pembangunan
3. Isi nilai anggaran 100M
4. Isi sumber biaya pemerintah 0
5. Isi sumber biaya propinsi 0
6. Isi sumber biaya kab/kota 0
7. Isi sumber biaya swadaya 100M
8. Isi kolom lain yg diperlukan
9. Simpan
Pesan error data gagal disimpan

### Hasil yg diharapkan

Data nilai anggaran flexibel, dapat diisi nilai berapapun sesuai anggaran

### Tangkapan layar dan log error

![Screenshot_2022-06-26-23-15-44-726_com android chrome](https://user-images.githubusercontent.com/71241253/175891091-b6fcff1d-73be-4eac-bdd5-3fe54ccdf398.jpg)

### Rilis Versi OpenSID

Rilis Umum

### Versi OpenSID

22.06

### Tema Yang Digunakan

Natra

### Informasi tambahan

Saya juga sempat mencoba di halaman demo openSID resmi, yg tersimpan nilai maksimal 2,1M
![Screenshot_2022-06-27-15-05-05-668_com android chrome](https://user-images.githubusercontent.com/71241253/175890970-7b7a81b4-c9c4-4330-9727-03c132894bfd.jpg)

**Comment by andifahruddinakas** [comment]
Pak @bing609, issue duplikat dengan https://github.com/OpenSID/OpenSID/issues/5267 dan sudah diperbaiki di rilis v22.06-premium.

Untuk v22.06-premium akan tersedia di rilis umum 6 bulan selanjutnya.
