### ISSUE TITLE
Bug/error: menambah ibu hamil error 500

### ISSUE THREAD

**Issue by Wiliyantoro** [OpenSID/OpenSID#5291]
### Jelaskan error yg dialami

saat menambah data ibu hami di menu Kesehatan -> Stunting -> Kesehatan Ibu dan Anak (KIA) -> isi tgl hari perkiraan lahir
terjadi error 500

### Cara untuk mereplikasi errornya

Severity: error --> Exception: SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect integer value: '' for column `beta_beta_premium`.`kia`.`anak_id` at row 1 (SQL: insert into `kia` (`no_kia`, `ibu_id`, `anak_id`, `hari_perkiraan_lahir`) values (12346, 2, , 2022-10-30)) /home/beta.opendesa.id/p
blic_html/vendor/illuminate/database/Connection.php 712

### Hasil yg diharapkan

berjalan normal

### Tangkapan layar dan log error

![2022-06-28 (1)](https://user-images.githubusercontent.com/44520382/176092668-23be9c0a-5fda-4a90-a672-877633fef73b.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.06-premium-beta03

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melalui pr https://github.com/OpenSID/premium/pull/1101
