### ISSUE TITLE
Bug/error: melihat data pemantauan bulanan anak 0-2 tahun muncul pop-up error

### ISSUE THREAD

**Issue by Wiliyantoro** [OpenSID/OpenSID#5292]
### Jelaskan error yg dialami

setelah selesai / berhasil input data pemantauan bulanan anak 0-2 tahun dan ingin melihat data tersebut muncul pop-up error

### Cara untuk mereplikasi errornya

DataTables warning: table id=tabeldata - Requested unknown parameter 'kia.no_kia' for row 0, column 3. For more information about this error, please see http://datatables.net/tn/4

### Hasil yg diharapkan

berjalan normal

### Tangkapan layar dan log error

![2022-06-28 (4)](https://user-images.githubusercontent.com/44520382/176094552-b15cd462-134c-42d0-8e67-bdcb3038da9a.png)
![2022-06-28 (3)](https://user-images.githubusercontent.com/44520382/176094557-a8b7f6ff-4459-495e-abb3-3087cca1a993.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.06-premium-beta03

**Comment by Wiliyantoro** [comment]
ini terjadi karena no kia bukan format angka , jika angka berjalan normal
tapi jika mengandung titik, koma dan garing muncul error

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melalui pr https://github.com/OpenSID/premium/pull/1101
