### ISSUE TITLE
Bug/error: Edit Buku KIA pada form edit kosong

### ISSUE THREAD

**Issue by Wiliyantoro** [OpenSID/OpenSID#5293]
### Jelaskan error yg dialami

saat ingin edit buku kia, tidak muncul data sebelumnya ( nama ibu dan anak )

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

muncul data sebelumnya

### Tangkapan layar dan log error

![2022-06-28 (8)](https://user-images.githubusercontent.com/44520382/176099366-fbdec5d8-e8e2-4490-9329-6251ae94c2d1.png)
![2022-06-28 (7)](https://user-images.githubusercontent.com/44520382/176099369-ba54e76f-fba1-4200-a753-f9b5ffe4377d.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.06-premium-beta03

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melalui pr https://github.com/OpenSID/premium/pull/1101
