### ISSUE TITLE
Penambahan Form input Hasil Ukur dan Informasi Bulan Pemantauan

### ISSUE THREAD

**Issue by Wiliyantoro** [OpenSID/OpenSID#5295]
### Jelaskan error yg dialami

1. Belum adanya Form Hasil Ukur Berat Badan dan Tinggi Badan di Tambah data Pemantauan Bulanan anak 0-2 Tahun, mohon di evaluasi kembali jika hasil ukur tersebut dapat dimasukkan agar dijadikan data master desa walaupun hasil ukur tersebut tidak dipanggil ke laporan konvergensi stunting.
2. Tambah Form Bulan Pemantauan di Tambah data pemantauan bulanan, agar nantinya saat melakukan input muncul bulan saat dilakukan input, class form input dapat di disable agar tidak dapat dirubah / dengan pertimbangan boleh di aktifkan form tersebut jika ingin input data bulan sebelumnya yang belum terinput oleh kpm

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

1. sediakan Form Ukur ( berat badan dan tinggi badan ) agar menjadi data master desa
2. sediakan form bulan pemantauan

### Tangkapan layar dan log error

![2](https://user-images.githubusercontent.com/44520382/176180266-927fcff2-8090-4521-aa0e-b277a65c2533.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.06-premium-beta03

**Comment by yogiperdana** [comment]
Form bulan pemantauan / bulan periksa itu maksudnya keterangan bulan saat ini / saat penginputan. Apakah seperti itu pak @Wiliyantoro?

**Comment by Wiliyantoro** [comment]
Betul pak, tampilkan bulan pemantuannya saat di input

**Comment by yogiperdana** [comment]
Mohon informasi terkait satuan berat dan tinggi badan pak

**Comment by Zoel-WB** [comment]
> Mohon informasi terkait satuan berat dan tinggi badan pak

Satuan berat kg pak, sedangkan tinggi badan identiknya dgn centimeter, mungkin dari teman2 yg lain, barangkali sebutan lainnya, utk masalah berat badan dan tinggi badan.

**Comment by yogiperdana** [comment]
Baik pak

**Comment by yogiperdana** [comment]
Untuk form input bulan akan dibuat pada issue https://github.com/OpenSID/OpenSID/issues/5503

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1231
