### ISSUE TITLE
Permintaan fitur: Sediakan pencarian spesifik penduduk berdasarkan umur bulan

### ISSUE THREAD

**Issue by muhtar-coder** [OpenSID/OpenSID#5296]
### Apa kekurangan yg ingin diatasi?

saat ini fitur pencarian/filter data penduduk hanya berdasarkan rentang umur tahun.

sehubungan dengan sedang gencar nya pendataan stunting/posyandu yang terdapat kolom isian nya menggunakan umur bulan,

### Jelaskan solusi yg diinginkan

agar di sediakan pada menu pencarian spesifik/filter penduduk berdasarkan rentang umur bulan.

![image](https://user-images.githubusercontent.com/55665526/176475264-bbeb5281-5d00-43c3-ad69-1dea88aa7fca.png)

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

v22.07-premium

### Informasi tambahan

-

**Comment by ariandii** [comment]
setiap tanggal 25, fitur opensid sudah dikunci. dan fokus terhadap persiapan rilis tanggal 1.

bisa di up kembali issue ini bulan depan.

**Comment by andifahruddinakas** [comment]
Mas @vickyrolanda, untuk inputannya apa sebaiknya dibuat 1 inputan saja? tapi ditambahkan select disampingnya, apa menggunakan bulan/tahun.

![pencarian 1](https://user-images.githubusercontent.com/57283157/188948542-e80e75ee-a349-47b2-a133-8fd373ca149f.png)

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1337
