### ISSUE TITLE
Sesuaikan Logo supaya bisa dishare ke Media Sosial

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#5297]
### Jelaskan error yg dialami

Saat ini ketika upload logo di Info Desa -> Identitas Desa, maka ukuran logo tersebut akan otomatis jadi 100x100 pixel.

hal ini berakibat gagal muncul sebagai thumbnail di beberapa media sosial, karena minimal agar bisa digunakan misal di share facebook adalah 300x300 pixel

### Cara untuk mereplikasi errornya

Upload logi di Identitas Desa - Info Desa

### Hasil yg diharapkan

Bisa disediakan pengaturan untuk ukuran logo untuk di conversi sesuai pengaturan tersebut.

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.07

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1349
