### ISSUE TITLE
Bug/error: Pada Arsip Layanan Tidak Terekam Arsip PDF/Rtf Suratya

### ISSUE THREAD

**Issue by Pematung** [OpenSID/OpenSID#5299]
### Jelaskan error yg dialami

Masih adanya kendala pada versi 22.06-premium-beta03/22.07-premium yg mana pada saat membuat salah satu surat bawaan opensid saat di cek pada menu arsip layanan tidak terekam arsipnya surat yg sudah dibuat tersebut baik dalam bentuk PDF maupun Rtf

**_Seperti pada Gambar dibawah ini_**

![image](https://user-images.githubusercontent.com/105429258/176782187-6752b9d0-ca15-4f90-abac-ff15ce878036.png)

### Cara untuk mereplikasi errornya

1. Layanan Surat
2. Cetak Surat
3. Surat Keterangan Usaha ( Sebagai Contoh )
4. Unduh Rtf atau Cetak PDF
5. Lalu kemudian cek pada Arsip Layanan

### Hasil yg diharapkan

Harusnya Arsip Suratnyanya Terekam baik dalam bentuk PDF ataupun Rtf

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/105429258/176782068-19cfb9e0-27a4-454e-a2ef-c4dcfbb77bd5.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

22.07 Premium

### Tema Yang Digunakan

-

### Informasi tambahan

-

**Comment by andifahruddinakas** [comment]
Pak @Pematung, Terima kasih. Sudah diperbaiki melalui commit https://github.com/OpenSID/premium/pull/1105/commits/b6ee6a9f1c0f8b0dc5b6ff611dc88b17841bd820
