### ISSUE TITLE
Responsive Design

### ISSUE THREAD

**Issue by arzaddin** [OpenSID/OpenSID#53]
Untuk halaman web (depan) sudah semestinya responsive. Agar tetap nyaman dibuka diberbagai device.

**Comment by eddieridwan** [comment]
@batudaa, @metalab25: Diskusi mengenai cara menerapkan ini pindah ke https://groups.google.com/forum/#!topic/opensid/92bfV1CGTRU.

**Comment by eddieridwan** [comment]
@arzaddin : Diskusi mengenai cara menerapkan ini bisa diteruskan lebih mendalam di https://groups.google.com/forum/#!topic/opensid/92bfV1CGTRU.

**Comment by eddieridwan** [comment]
Branch responsive di https://github.com/eddieridwan/OpenSID/tree/responsive adalah hasil penerapan berjalan membuat OpenSID menjadi responsive. 

Teman-teman, coba di-tes. Kalau sudah ok, kami akan rilis sebagai OpenSID v1.0.

**Comment by arzaddin** [comment]
Sudah bisa dengan menggunakan https://github.com/arzaddin/batudaa-theme
