### ISSUE TITLE
[Stunting] Input ibu dengan status di kk selain istri tidak bisa ( menantu dll ) dan anak ( cucu dll)

### ISSUE THREAD

**Issue by Wiliyantoro** [OpenSID/OpenSID#5301]
### Jelaskan error yg dialami

1. pada saat ingin input data ibu di menu KIA tidak dapat input nama ibu selain status sdhk istri, jika menantu dan lain lain tidak bisa
2. hal tersebut juga berlaku untuk nama anak bisa jadi nanti di kk status anaknya adalah cucu dll
3. tampilan form muncul tulisan  id_ib == ..........................
4. tampilan form pencarian nama anak id_anak == .........................

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

1. bisa input nama ibu diluar sdhk istri di kk, misalnya menantu dll dengan kategori menikah, cerai hidup, cerai mati
2. bisa input nama anak dimana kategori di kk anak, cucu dll 
3. perbaiki tampilan form cari di nama ibu dan cari nama anak

### Tangkapan layar dan log error

![bu2stunting](https://user-images.githubusercontent.com/44520382/176804132-2985d9c2-fcf8-4316-8006-fe04e32e482f.png)
![bug1 stunting](https://user-images.githubusercontent.com/44520382/176804138-05e8cc37-6581-4ff5-a1ed-ca018a89fa86.png)
![bug3stunting](https://user-images.githubusercontent.com/44520382/176804139-f5e11b1c-80ec-4248-83db-641bfe465eb6.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.07-premium

### Tema Yang Digunakan

Denatra v.6.2

**Comment by mahmudi01** [comment]
Perbaiki juga Menu pemantauan bulanan pada stunting yang tampil : pemeriksaan_kehamilan) :echo dst.

**Comment by yogiperdana** [comment]
Kira kira selain shdk kepala keluarga, ibu, dan menantu apalagi pak? Apakah status shdk mertua, family lain, pembantu dan lainnya juga termasuk untuk input ibu hamil?

Hal yang sama juga untuk inputan anak. Adakah status shdk lain selain anak dan cucu @Wiliyantoro

**Comment by Wiliyantoro** [comment]
1. Ada juga di keluarga yg numpang di kk saudaranya dengan status famili lain belum buat kk baru, jadinya ada kemungkinan keluarga tersebut masuk famili lain,, 
2. Untuk ibu hamil mungkin juga berlaku demikian, untuk sdhk pembantu nunggu masukan dari temen temen saja pak,, kalau di saya terbatas di istri, menantu, anak, dan famili lain
3. Integrasikan ibu hamil ke biodata penduduk tersebut agar di biodatanya berubah menjadi hamil

**Comment by yogiperdana** [comment]
Baik pak lalu untuk anaknya bagaimana pak? apakah ada kemungkinan bisa berasal dari famili yang lain juga pak?
@Wiliyantoro

**Comment by Wiliyantoro** [comment]
iya pak, untuk anaknya juga ada kemungkinan ada kasus tersebut, jika dirasa perlu buat role untuk mencari ibu dengan memanggil nik ibu yang sudah ada di biodata anak / jika nik kosong cari ibu di no kk anak tersebut.

**Comment by yogiperdana** [comment]
Issue ini dialihkan menjadi permintaan fitur karena terdapat penyesuaian pengambilan data penduduk baik pada ibu maupun anak

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1203
