### ISSUE TITLE
[TinyMCE] Pilih Data Penduduk Dinamis

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#5302]
Tersedia pilih data penduduk ataupun penduduk luar yang bisa ditentukan sendiri (dinamis). Adapun pilihannya sbb : 
- [ ] Semua Penduduk
- [ ] Penduduk Laki2
- [ ] Penduduk Perempuan
- [ ] Penduduk Mati
- [ ] Penduduk 
- [ ] dll

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1227

**Comment by andifahruddinakas** [comment]
> Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1227

Sesuai pembahasan di pertemuan tadi, PR ini digabungkan setelah TTE selesai digabungkan ke rilis-dev. Cek jg status di projek, statusnya masih perbaiki pr.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1261
