### ISSUE TITLE
[TinyMCE] Memilih dan Menggunakan Lampiran

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#5303]
Sediakan pengaturan surat agar bisa memilih jenis lampiran yang digunakan.

**Comment by andifahruddinakas** [comment]
Batasan : 
- [ ] Lampiran masih menggunakan yang lama, namun bisa dipilih digunakan ditemplate tinymce manapun sesuai keinginan pengguna.
- [ ] Pengguna dapat menambahkan lampiran lain jika dibutuhkan.
- [ ] Lapiran yang digunakan bisa lebih dari 1 (bagian ini dicek)

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1385
