### ISSUE TITLE
[TinyMCE] Pengaturan Default Font

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#5305]
Sediakan pengaturan default font yang bisa digunakan. Saat ini default font yang digunakan adalah arial.

**Comment by Wiliyantoro** [comment]
Kalau bisa tambah font bali simbar pak, karna di kop surat kami isi aksara balinya

**Comment by balongbesuk** [comment]
pernah baca font resmi kedinasan pemerintah,

 tp googling blm nemu aturanny

**Comment by Wiliyantoro** [comment]
Kop surat isi aksara bali ada di pergub dan perbup pak, mohon dipertimbangkan agar dapat ditambahkan font bali simbar

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1129
