### ISSUE TITLE
[TinyMCE] Ridirect Ke Arsip / Daftar Surat Setelah Cetak Surat

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#5306]
Ridirect Ke Arsip / Daftar Surat Setelah Cetak Surat. Saat ini masih belum bisa diterapkan.

Alternatif lain, setelah menekan tombol cetak, tombol cetak dan draft di hilangkan digantikan dengan tombol menuju arsip layanan.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1122
