### ISSUE TITLE
[Pengaturan Surat] Masa berlaku surat

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#5307]
Sediaka pengaturan masa berlaku surat agar bisa dipilih untuk dihilangkan atau ditampilkan pada form surat. Karena tidak semua desa menggunakan masa berlakuk surat. Buat agar bisa disesuaikan sendiri melalui pengaturan tsb.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1134
