### ISSUE TITLE
[Pengaturan Surat] Unduh tempate rtf bawaan sistem

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#5308]
Sediakan Unduh tempate rtf bawaan sistem, karena saat ini hanya ada unduh template terbaru saja (apakah itu sistem / ubahan desa). Sehingga jika terjadi kesalahan, dan ingin mengambil ulang kembali tempate bawaan harus buka cpanel terlebih dahulu.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1139
