### ISSUE TITLE
[TinyMCE] Kode isian selain teks

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#5309]
Sediakan kode isian : 
- [x] #5687
- [x] Tgl
- [x] Jam
- [ ] dll

**Comment by andifahruddinakas** [comment]
Mas @apidong, apa ini sedang di kerjakan atau belum??? Kalau belum sama sekali, biar sy yang kerjakan.

**Comment by apidong** [comment]
Belum mas,

**Comment by andifahruddinakas** [comment]
> Belum mas,

ok, biar sy kerjakan.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1304
