### ISSUE TITLE
Bug/error: Foto dan JK pada KK kosong tidak sesuai

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#5310]
### Jelaskan error yg dialami

Saat ada KK kosong (Kepala Keluarga tdk ada), data dari KK kosong tersebut (foto dan jk) tidak sesuai.

### Cara untuk mereplikasi errornya

Buat KK kosong terlebih dahulu dengan mengeluarkan Kepala Keluarga.

### Hasil yg diharapkan

Profil dan JK pada kosong tetap sesui walau tdk digunakan.

### Tangkapan layar dan log error

![kk ksong](https://user-images.githubusercontent.com/57283157/176915313-2c6bb5a0-ced2-4abb-a4ef-12bbe30f441a.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.07-premium

### Tema Yang Digunakan

bawaan

### Informasi tambahan

Pak @ariandii, kalau ada tambahan bisa komen di issue ini.

**Comment by agungsugiarto** [comment]
Mas @andifahruddinakas bisa dijelaskan lebih detail alur replikasi masalahnya

**Comment by vickyrolanda** [comment]
Saya check sudah oke di PR https://github.com/OpenSID/premium/pull/1113 
<img width="733" alt="image" src="https://user-images.githubusercontent.com/59082428/177500702-ff95a52c-4594-4420-b71d-13fcf7c35bb8.png">

Namun agak sedikit membingungkan di bagian photo apa tidak sebaiknya photonya di kosongkan saja atau dibuat "-" dibagian photonya mas @agungsugiarto 

<img width="741" alt="image" src="https://user-images.githubusercontent.com/59082428/177501712-e6e7f435-f5d8-42b4-b721-71b6858191b0.png">

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1113
