### ISSUE TITLE
Bug/error: Atas Nama duplikat di beberapa pengurus

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#5312]
### Jelaskan error yg dialami

Terjadi duplikasi atas nama pada modul pengurus untuk pengguna lama (umum saat ini). Di premium sendiri masalah ini sudah teratasi, tapi bermasalah bagi pengguna lama yang tidak memperbaharui kembali a.n yang ada modul pengurus.

### Cara untuk mereplikasi errornya

1. Gunakan versi umum 22.07
2. Buka modul pengurus dan tambahkan a.n
3. Buka modul indeitas desa dan ganti kepala desa yang berbeda dengan a.n di pengurus
4. Buka kembali modul pengurus, terjadi duplikasi a.n

### Hasil yg diharapkan

Untuk a.n maupun u.b hanya bisa dipilih 1 saja

### Tangkapan layar dan log error

![pengurus](https://user-images.githubusercontent.com/57283157/176993156-c3e5d4c4-0ec3-464e-b9b2-5f07962703e0.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Dari versi umum 22.07 ke premium v22.07-premium

### Tema Yang Digunakan

bawaan

### Informasi tambahan

Solusi agar tidak terjadi duplikasi : 
1. Pergantian data kepala desa yang ada di identatas desa diambil dari pengurus yang ditandai dengan a.n
2. Lakukan migrasi untuk mengecek dan memperbaiki a.n maupun u.b yg duplikat

**Comment by agungsugiarto** [comment]
mas @andifahruddinakas  aya tidak menemukan masalah yg dimaksud, mas @devrakapriyo bisa dibantu untuk replikasi masalahnya?

**Comment by andifahruddinakas** [comment]
> mas @andifahruddinakas aya tidak menemukan masalah yg dimaksud, mas @devrakapriyo bisa dibantu untuk replikasi masalahnya?

Ini ketika ada update dari versi pelanggan umum ke premium. Di versi umum masih bisa terjadi duplikasi tsb.

**Comment by agungsugiarto** [comment]
semua dari database umum, atau hanya beberapa desa?

**Comment by andifahruddinakas** [comment]
> semua dari database umum, atau hanya beberapa desa?

Berlaku untuk versi umum yang migrasi ke versi premium terbaru jika sebelumnya (versi umum) melakukan pergantian kepala desa lewat identitas desa.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1110
