### ISSUE TITLE
[Periksa Database] User dan Password Default (Statis)

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#5313]
Ketika terjadi error database, pengguna biasanya mengirikan Database mereka untuk diperbaiki. Database yang dikirimkan tsb biasanya tidak disertakan denga password login (untuk user bisa diliat di tabel user). Ini bisa diakali dengan mengganti user maupun password ke settingan awal, yakni admin, sid304. Tapi setelah periksa, melakukan backcup database dan mengirimkan kembali ke pengguna terkadang lupa untuk mengembalikan password semua.

Sediakan pengaturan untuk login dengan password default yang telah ditentukan.

**Comment by eddieridwan** [comment]
Batasi hanya untuk untuk development; tidak pada production.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1140/
