### ISSUE TITLE
Bug/error: Impor data penduduk dengan No KK < 16 digit

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#5314]
### Jelaskan error yg dialami

Masih bisa impor no kk < 16 digit, sedangkan di form input kk harus 16 digit.

### Cara untuk mereplikasi errornya

Lakukan impor penduduk, buat data dengan no kk < 16 digit.

### Hasil yg diharapkan

Impor dan form validasinya sesuai.

### Tangkapan layar dan log error

![no kk](https://user-images.githubusercontent.com/57283157/176993779-3b5d9d39-2d67-43e5-b180-6a7c612048d3.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.07-premium

### Tema Yang Digunakan

bawaan

### Informasi tambahan

.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1107
