### ISSUE TITLE
[Stunting] Pemintaan Filter Data Anak Berdasarkan Nomor KK Ibu

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#5319]
### Apa kekurangan yg ingin diatasi?

Pemintaan Filter Data Anak Berdasarkan Nomor KK Ibu, sehingga saat memilih atau memasukkan data ibu, nama anak atau Nik anak dapat di pilih otomatis berdasarkan data yg terfilter hanya dari KK ibu yg terpilih

### Jelaskan solusi yg diinginkan

![image](https://user-images.githubusercontent.com/64481641/177025203-27d1c15c-3a45-40ee-912a-1a7b4f342536.png)

### Apakah ada alternatif lain

.

### Untuk versi OpenSID mana

V22.07 Premium

### Informasi tambahan

.

**Comment by yogiperdana** [comment]
Apakah hal tersebut tidak menjadi terlalu strict pak untuk kasus pasangan yang baru menikah dan punya anak pak. Dari diskusi kemaren dengan pengguna lain proses pembuatan kk tidak langsung terbit sedangkan proses pengisian KIA langsung setelah melahirkan @Zoel-WB

**Comment by yogiperdana** [comment]
Dengan demikian anak yang baru lahir belum masuk ke dalam kk saat pemberian imunisasi H0. Kira kira bagaimana menghadapi solusi tersebut di lapangan?

**Comment by Zoel-WB** [comment]
tapi pelaksanaan posyandunya bulanan pak, sehingga barang kali anak yg baru lahir data awalnya di input di data penduduk duluan, kemudian mungkin 2-3 bulan kemudian baru penanganan ke posyandu dan terpantau ke stunting pak........

**Comment by yogiperdana** [comment]
Baik pak jadi tidak masalah ya pak dibuatkan ibu dan anak harus dalam 1 kk

**Comment by Wiliyantoro** [comment]
Setuju dengan pendapat bang @Zoel-WB , nantinya data penduduk akan lengkap dengan kasus bayi lahir di setiap posyandu. Karena tidak semua warga tertib atau rajin melaporkan ada bayi lahir, nanti rolenya kpm akan melapor ke desa bahwa ada bayi lahir , di input kesistem sebelum masuk ke menu pemantauan

**Comment by Zoel-WB** [comment]
cuma memang memang ada kendala dilapangan datanya bisa tertunda bila si keluarga lebih2 keluarga baru menikah akan tetapi tetapi telat melakukan pecahan KK...

akan tetapi hal ini datanya dapat dirubah atau ditambah langsung kedalam data penduduk oleh petugas posyandu disaat kegiatan posyandu, barangkali akses data di desa yang harus memberi satu user untuk petugas posyandu untuk dapat memasukkan data penduduk dari kelahirlan baru, maupun data ibu hami...

**Comment by yogiperdana** [comment]
Baik pak. Terkait kpm tersebut saat ini belum dibuatkan rolenya. Kira kira apa saja tugas dan tanggungjawab kpm tersebut pak?

**Comment by yogiperdana** [comment]
Kemarin ada pembahasan sedikit bahwa kpm diambil dari data berikut https://berputar.opendesa.id/bumindes_kader/form
Namun ketentuannya belum jelas kader pemberdayaan dengan spesifikasi yang mana yang bertanggungjawab mengelola stunting. Mohon masukannya pak

**Comment by Zoel-WB** [comment]
Dari KPM biasanya bila data kelahiran baru termasuk KIA nya bila si ibu belum melaporkan data KK nya, kami selalu mempertanyakan tentang ada penambahan data baru ke KPM pak, karena di desa agak memang sulit penduduk secara sadar jarang melaporkan sendiri datanya.

Prosedur penambahan atau perubahan dalam KK, kebiasaan data nya di dapat dari KPM pak..

**Comment by Zoel-WB** [comment]
> Kemarin ada pembahasan sedikit bahwa kpm diambil dari data berikut https://berputar.opendesa.id/bumindes_kader/form Namun ketentuannya belum jelas kader pemberdayaan dengan spesifikasi yang mana yang bertanggungjawab mengelola stunting. Mohon masukannya pak

KMP Stuntingnya yg lebih berperan ketimbang kader posyandu nya pak.....

**Comment by yogiperdana** [comment]
Untuk lebih memperjelas alurnya kira kira kapan pak @Zoel-WB dan @Wiliyantoro ada waktu untuk berdiskusi via meet atau zoom pak. Agar semua kebutuhan dan permasalahan di stunting dapat segera diselesaikan

**Comment by Zoel-WB** [comment]
> Kemarin ada pembahasan sedikit bahwa kpm diambil dari data berikut https://berputar.opendesa.id/bumindes_kader/form Namun ketentuannya belum jelas kader pemberdayaan dengan spesifikasi yang mana yang bertanggungjawab mengelola stunting. Mohon masukannya pak

yang punya data lengkap memang di KPM stuntingnya termasuk bidan desa nya, karena mereka sangat terlibat dan bertanggangjawab terhadap keadaan data bayi dan ibu hamil dan masalah kesehatan rumah tangga ibu bayi mapun ibu hamil.

**Comment by Zoel-WB** [comment]
> Untuk lebih memperjelas alurnya kira kira kapan pak @Zoel-WB dan @Wiliyantoro ada waktu untuk berdiskusi via meet atau zomm pak. Agar semua kebutuhan dan permasalahan di stunting dapat segera diselesaikan

tapi saya belum pelajari utuk fitur ini, akan tetapi sekilasnya saya browsing2 sepertinya sudah sangat terpenuhi, tapi ini kita uji langsung dulu di KPM nya, bila ada perubahan dan penambahannya nanti kita sampaikan pak, untuk saat ini saya kira sudah sangat bagus....

**Comment by Wiliyantoro** [comment]
> Untuk lebih memperjelas alurnya kira kira kapan pak @Zoel-WB dan @Wiliyantoro ada waktu untuk berdiskusi via meet atau zoom pak. Agar semua kebutuhan dan permasalahan di stunting dapat segera diselesaikan

Menurut saya pribadi bug penambahan ibu hamil yg sdhk selain istri dan anak selain sdhk anak di buka dulu karena keluarga yg masih gabung dengan kk orang tuanya , kpm kemarin saya untuk coba input tidak bisa karena masalah tersebut,,

Jika dilapangan ditemukan masalah oleh kpm baru bisa memberikan pandangan pak

**Comment by yogiperdana** [comment]
Baik pak jadi mungkin sementara semua permintaan fitur terkait stunting kita tangguhkan dulu ya pak menunggu proses analisis dilakuka pengguna bersama KPM dan saat ini open desa juga sudah punya analis pak. Kedepannya saya akan ajak beliau juga untuk ikut berdiskusi

**Comment by Zoel-WB** [comment]
> Baik pak jadi mungkin sementara semua permintaan fitur terkait stunting kita tangguhkan dulu ya pak menunggu proses analisis dilakuka pengguna bersama KPM dan saat ini open desa juga sudah punya analis pak. Kedepannya saya akan ajak beliau juga untuk ikut berdiskusi

Setuju pak....

**Comment by Wiliyantoro** [comment]
> Baik pak jadi mungkin sementara semua permintaan fitur terkait stunting kita tangguhkan dulu ya pak menunggu proses analisis dilakuka pengguna bersama KPM dan saat ini open desa juga sudah punya analis pak. Kedepannya saya akan ajak beliau juga untuk ikut berdiskusi

Setuju pk

**Comment by yogiperdana** [comment]
Karena saat ini ibu dapat diinput dengan beberapa status shdk seperti ibu, anak, menantu, famili lain dan sebagainya maka yang dijadikan paremeter adalah no kk yang sama dan ibu tidak boleh sama dengan anak

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1246
