### ISSUE TITLE
[Stunting] Grup pengguna stunting tidak sesuai

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#5320]
### Jelaskan error yg dialami

Saat menambahkan grup pengguna hanya bisa akses modul stunting, tapi saat login menu pertanahan juga tampil.

### Cara untuk mereplikasi errornya

1. Tambahkan grup pengguna stunting dengan akses hanya modul stunting sja
2. Buat user berdasarkan grup tsb
3. Lakukan login dgn user tsb
4. Setelah login, navigasi menampilkan menu pertanahan juga.

### Hasil yg diharapkan

Sesuai grup dan akses yang diberikan

### Tangkapan layar dan log error

![stunting-1](https://user-images.githubusercontent.com/57283157/177026110-4831bdb1-1a28-43db-94d5-1fdeaff79538.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.07-premium

### Tema Yang Digunakan

bawaan

### Informasi tambahan

.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1109
