### ISSUE TITLE
Bug/error: Error saat tambah hari libur yg sama

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#5321]
### Jelaskan error yg dialami

Terjadi error saat menambahkan hari libur dgn tgl yg sama.

### Cara untuk mereplikasi errornya

1. buka modul kehadiran > hari libur
2. tambahkan data baru dgn memasukka tgl yg sudah ad
3. terjadi error

### Hasil yg diharapkan

tdk terjadi error atau ada notifikasi yg menyatakn tgl tsb sdh terdaftar.

### Tangkapan layar dan log error

![kehadiran1](https://user-images.githubusercontent.com/57283157/177027243-9aaf637f-e174-4101-a8f1-e48cb9861643.png)

`ERROR - 2022-07-03 13:03:39 --> Severity: error --> Exception: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '2022-01-01' for key 'tanggal' (SQL: insert into `kehadiran_hari_libur` (`tanggal`, `keterangan`) values (2022-01-01, ertyuio)) D:\PROJECT OPENDESA\OpenSID\vendor\illuminate\database\Connection.php 712`

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.07-premium

### Tema Yang Digunakan

bawaan

### Informasi tambahan

.

**Comment by vickyrolanda** [comment]
Sudah di perbaikin melalui pr https://github.com/OpenSID/premium/pull/1106
