### ISSUE TITLE
Bug/error: Tidak bisa input kode lembaga yang sudah digunakan di kelompok

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#5322]
### Jelaskan error yg dialami

Saat melakukan input data lembaga dengan kode yang sudah digunakan di data kelompok akan menampilkan notif gagal simpan karena kode lembaga sudah digunakan.

### Cara untuk mereplikasi errornya

1. Buat terlebih dahulu data kelompok.
2. Buat data lembaga menggunakan data kode kelompok tsb.
3. Simpan, dan akan tampil notif bahwa kode lembaga sudah digunakan.

### Hasil yg diharapkan

Bisa gunakan kode yg belum terdaftar di lembaga

### Tangkapan layar dan log error

![lembaga](https://user-images.githubusercontent.com/57283157/177027659-ac45a0e7-be77-40c9-be73-a80d9857d44e.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.07-premium

### Tema Yang Digunakan

bawaan

### Informasi tambahan

SOLUSI : 
- Gunakan unique 2 kolom (tipe dan kode)

**Comment by agungsugiarto** [comment]
issue ini tidak bisa diterapkan, karena kelompok dan anggota menggunakan table yg sama sementara field yg ada didatabase harus unique.

**Comment by andifahruddinakas** [comment]
> issue ini tidak bisa diterapkan, karena kelompok dan anggota menggunakan table yg sama sementara field yg ada didatabase harus unique.

Tahapan : 
1. Gunakan uniq 2 tabel, yakni tipe dan kolom (seperti penjelasan issue di atas)
Contoh yg pernah digunakan  : 
```
// Tambahkan index pada program_id dan kartu_id_pend
if (! $this->cek_indeks('program_peserta', 'program_peserta_program_id_kartu_id_pend_unique')) {
    Schema::table('program_peserta', static function (Blueprint $table) {
        $table->unique(['program_id', 'kartu_id_pend']);
    });
}
```
2. Untuk insert dan update, bisa cek dlu sebelum di proses.
Contoh yg pernah digunakan  : 
```
public function add_peserta($program_id = 0)
{
    $this->redirect_hak_akses('u');

    $cek = BantuanPeserta::where('program_id', $program_id)->where('kartu_id_pend', $this->input->post('kartu_id_pend'))->first();

    if ($cek) {
        $this->session->success = -2;
    } else {
        $this->program_bantuan_model->add_peserta($program_id);
    }

    $redirect = ($this->session->userdata('aksi') != 1) ? $_SERVER['HTTP_REFERER'] : "program_bantuan/detail/{$program_id}";

    $this->session->unset_userdata('aksi');

    redirect($redirect);
}
```

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1114
