### ISSUE TITLE
Bug/error: Perbarui surat rtf

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#5323]
### Jelaskan error yg dialami

Terjadi error saat menambahkan surat baru dengan cara menambahkannya di folder desa/template-surat

### Cara untuk mereplikasi errornya

1. Tambah contoh surat baru rtf di folder desa/template-desa
2. Masuk ke modul Layanan Surat > Pengaturan Surat > Perbarui
3. Buka log error

### Hasil yg diharapkan

Data surat baru bertambah dan disesuaikan dengan isi folder desa/template-surat

### Tangkapan layar dan log error

`ERROR - 2022-07-03 14:35:46 --> Severity: error --> Exception: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'surat_amplop_keluar' for key 'url_surat' (SQL: insert into tweb_surat_format (jenis, nama, url_surat) values (2, amplop keluar, surat_amplop_keluar)) /home/sukoreno.web.id/public_html/vendor/illuminate/database/Connection.php 712`

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.07-premium

### Tema Yang Digunakan

bawaan

### Informasi tambahan

.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1108
