### ISSUE TITLE
[Stunting] Permintaan Menampilkan Detail Data Ibu Saat Menginput Data KIA

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#5324]
### Apa kekurangan yg ingin diatasi?

Saat menginput data ibu pada fitur Kesehatan Ibu dan AnaK (KIA) sulit membedakan data ibu yg dimaksud bila data ibu dengan nama yg sama ada beberapa orang/data.

Untuk mempermudah menandakan data, baiknya menampilkan detail atau penandata indentitas spesifik lainnya dari data yg terpanggil misalnya dapat  menampilkan detail keluarga seperti data nama suami/kepala keluarga, atau bahkan alamat dusun, rt/rw supaya lebih mudah memilih data yg benar disaat nama dimasukkan terhadap satu nama yg sama yg mewakili beberapa data.

![image](https://user-images.githubusercontent.com/64481641/177173772-41fae9e4-7538-4855-9188-d879a37134f2.png)

### Jelaskan solusi yg diinginkan

![image](https://user-images.githubusercontent.com/64481641/177173809-aa128a90-ec48-4cea-84df-f6a9e25f665b.png)

### Apakah ada alternatif lain

.

### Untuk versi OpenSID mana

V22.07 Premium

### Informasi tambahan

.

**Comment by langonsari** [comment]
> ### Apa kekurangan yg ingin diatasi?
> Saat menginput data ibu pada fitur Kesehatan Ibu dan AnaK (KIA) sulit membedakan data ibu yg dimaksud bila data ibu dengan nama yg sama ada beberapa orang/data.
> 
> Untuk mempermudah menandakan data, baiknya menampilkan detail atau penandata indentitas spesifik lainnya dari data yg terpanggil misalnya dapat menampilkan detail keluarga seperti data nama suami/kepala keluarga, atau bahkan alamat dusun, rt/rw supaya lebih mudah memilih data yg benar disaat nama dimasukkan terhadap satu nama yg sama yg mewakili beberapa data.
> 
> ![image](https://user-images.githubusercontent.com/64481641/177173772-41fae9e4-7538-4855-9188-d879a37134f2.png)
> 
> ### Jelaskan solusi yg diinginkan
> ![image](https://user-images.githubusercontent.com/64481641/177173809-aa128a90-ec48-4cea-84df-f6a9e25f665b.png)
> 
> ### Apakah ada alternatif lain
> .
> 
> ### Untuk versi OpenSID mana
> V22.07 Premium
> 
> ### Informasi tambahan
> .

Tambahan untuk Pengaturan Pemilihan NAMA IBU tidak dibatas hanya 1 Nomor KIA karena sebelum Lahir Nomor KIA melekat kepada Ibu Hamil tetapi setelah melahirkan Nomor KIA pada ANAK, terutama apabila melahirkan anak Kembar tidak bisa di Input untuk anak kedua dan seterusnya.

**Comment by yogiperdana** [comment]
Mohon maaf pak @langonsari, jadi untuk kasus anak kembar 1 ibu punya 2 KIA yang mewakili masing-masing anak dan satu ibu bisa punya beberapa KIA begitu pak?

**Comment by yogiperdana** [comment]
Mohon analisisnya juga mas @vickyrolanda untuk kasus seperti ini. Selain kembar, bisa juga ada orang tua yang rentang usia anaknya tidak jauh jadi memungkinkan terdapat beberapa KIA

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1238
