### ISSUE TITLE
Bug/error: Album galeri pada web yang berisi lebih dari 10 foto, link pada halaman berikutnya tidak ditemukan

### ISSUE THREAD

**Issue by Restony33** [OpenSID/OpenSID#5339]
### Jelaskan error yg dialami

Saat membuka halaman berikutnya pada album galeri berisi lebih dari 10 foto terjadi error di web
![error](https://user-images.githubusercontent.com/104592011/177278600-19bc7333-147f-4ce0-9241-acbbb6f5bcf2.JPG)

### Cara untuk mereplikasi errornya

![erorrku](https://user-images.githubusercontent.com/104592011/177277675-db182c82-3ec2-4efa-8ce5-c66e02e1d799.JPG)
tejadi error saat buka halaman berikutnya seperti berikut
![error](https://user-images.githubusercontent.com/104592011/177277803-cc68066b-8729-421f-868e-93b2f23ce2de.JPG)

### Hasil yg diharapkan

link terbuka dan berjalan normal 

### Tangkapan layar dan log error

![erorrku](https://user-images.githubusercontent.com/104592011/177277580-6ec31450-c0fe-4fea-a8ba-7db688c8c817.JPG)
tejadi error saat buka halaman berikutnya seperti berikut
![error](https://user-images.githubusercontent.com/104592011/177277952-9c4b30a1-1bfb-43bd-87ba-d78334a4712f.JPG)
[log-2022-07-05.zip](https://github.com/OpenSID/OpenSID/files/9044414/log-2022-07-05.zip)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.07-premium

### Tema Yang Digunakan

Natra v22.06

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1112

**Comment by devrakapriyo** [comment]
mohon dicek mas @vickyrolanda https://docs.google.com/spreadsheets/d/1Lpw5StONGo4pUH4VGYByYkV4uoXLBZueFN5dLm-8MOY/edit#gid=0 , perlu ada perbaikan untuk menampilkan galeri.
