### ISSUE TITLE
Tambah Buku Tamu

### ISSUE THREAD

**Issue by sulaimanlawidhub** [OpenSID/OpenSID#5340]
Salah satu administrasi umun yang ada didesa adalah daftar tentang orang yang berkunjung ke kantor desa yang dicatat dalam buku tamu.

**Comment by ai-skematik** [comment]
![image](https://user-images.githubusercontent.com/48144047/177697780-a9eba0a4-49b9-48fd-92fe-4821dde8cdbb.png)

**Comment by ai-skematik** [comment]
cc. @devrakapriyo  @FirlianiF

**Comment by ai-skematik** [comment]
https://tamuku.titiankuala.opendesa.id/

**Comment by ai-skematik** [comment]
![image](https://user-images.githubusercontent.com/48144047/177784833-04e87e8f-5d17-4c22-acbf-2550dad44526.png)

**Comment by sulaimanlawidhub** [comment]
Setuju sekali

**Comment by sugiharjo** [comment]
Setuju banget

**Comment by eddieridwan** [comment]
Hanya untuk ditampilkan di layanan mandiri khusus untuk anjungan.

**Comment by sugiharjo** [comment]
Tambah buku tamu di opensid sangat setuju sekali

**Comment by eddieridwan** [comment]
Beberapa ketentuan:

1. Tampilan web Buku Tamu hanya tampil di layanan mandiri khusus untuk anjungan; yaitu jika terdeteksi dijalankan di gawai anjungan
2. Di anjungan, buku tamu diisi sendiri oleh pengunjung, tanpa harus login 
2. Tidak dapat mendaftar sebagai tamu lebih dari satu kali dalam satu hari
3. Pengambilan selfie digunakan sebagai verifikasi tamu yg mendaftar, pengganti tanda tangan
4. Di bagian admin, disediakan fitur untuk mencari, memilah dan mengurut daftar tamu. Juga disediakan fitur untuk mencetak laporan daftar tamu.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1663

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1663
