### ISSUE TITLE
Bug/error: Tombol Batal Pada Popup Pengaturan Pelanggan Tidak Berfungsi

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#5341]
### Jelaskan error yg dialami

Tombol batal pada popup tidak berfungsi.

### Cara untuk mereplikasi errornya

Info Desa > Layanan Pelanggan > Klik icon gear pada header di kanan atas > lalu akan muncul popup > dan klik tombol batal 

### Hasil yg diharapkan

Tombol batal dapat berfungsi dengan semestinya.

### Tangkapan layar dan log error

![popup batal](https://user-images.githubusercontent.com/36557759/177487201-1c33d959-ec74-4e20-89c7-c5c958362d1b.PNG)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Versi 22.07-premium-beta01

### Tema Yang Digunakan

natra

**Comment by andifahruddinakas** [comment]
Mas @devrakapriyo, mungkin bisa ditinjau fungsi tombol **batal** tsb. Tombol **batal** dibuat hanya untuk mereset input yg pernah dilakukan ke dataawal, bukan untuk menutup modal (krn ada tombol tersendiri untuk menutup modal (**x**)). Bisa cek tombol batal yang ada di https://berputar.opendesa.id/setting.

Kalau mau diubah, ganti nama tombolnya jadi **tutup**.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1115

**Comment by vickyrolanda** [comment]
> Mas @devrakapriyo, mungkin bisa ditinjau fungsi tombol **batal** tsb. Tombol **batal** dibuat hanya untuk mereset input yg pernah dilakukan ke dataawal, bukan untuk menutup modal (krn ada tombol tersendiri untuk menutup modal (**x**)). Bisa cek tombol batal yang ada di https://berputar.opendesa.id/setting.
> 
> Kalau mau diubah, ganti nama tombolnya jadi **tutup**.

tadi sy coba iya mas dia mereset harusnya ini bukan bug tpi kalo sesuai dengan UI tombol batal itu fungsi memang harusnya close mas jdi gpp juga kalo kita ubah ke PR ini mas .

**Comment by devrakapriyo** [comment]
Sudah dilakukan testing, dan perlu dilakukan perbaikan, mohon untuk di cek dan ditindak lanjuti mas @vickyrolanda 
https://docs.google.com/spreadsheets/d/1Lpw5StONGo4pUH4VGYByYkV4uoXLBZueFN5dLm-8MOY/edit#gid=0

**Comment by vickyrolanda** [comment]
> Sudah dilakukan testing, dan perlu dilakukan perbaikan, mohon untuk di cek dan ditindak lanjuti mas @vickyrolanda https://docs.google.com/spreadsheets/d/1Lpw5StONGo4pUH4VGYByYkV4uoXLBZueFN5dLm-8MOY/edit#gid=0

untuk issue penambahan seperti yg mas @devrakapriyo buat di spreddsheets itu mohon dibuatkan ke issue baru saja karena  PRnya sudah di merge ke bug-fix juga mas karena sudah sesuai dengan issue yg ini.

**Comment by devrakapriyo** [comment]
> > Sudah dilakukan testing, dan perlu dilakukan perbaikan, mohon untuk di cek dan ditindak lanjuti mas @vickyrolanda https://docs.google.com/spreadsheets/d/1Lpw5StONGo4pUH4VGYByYkV4uoXLBZueFN5dLm-8MOY/edit#gid=0
> 
> untuk issue penambahan seperti yg mas @devrakapriyo buat di spreddsheets itu mohon dibuatkan ke issue baru saja karena PRnya sudah di merge ke bug-fix juga mas karena sudah sesuai dengan issue yg ini.

Baik noted mas.
