### ISSUE TITLE
Bug/error: Tampilan error saat jalankan perbarui surat

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#5342]
### Jelaskan error yg dialami

Terjadi error saat  tambah surat baru rtf di folder desa/template-surat kemudian jalankan perbarui surat di pengaturan surat.

### Cara untuk mereplikasi errornya

tambah surat baru rtf di folder desa/template-surat kemudian jalankan perbarui surat di pengaturan surat.

### Hasil yg diharapkan

tidak terjadi error, custom surat berjalan sebagaimana mestinya.

### Tangkapan layar dan log error

ERROR - 2022-07-06 14:18:39 --> Severity: error --> Exception: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'surat_raw' for key 'url_surat' (SQL: insert into `tweb_surat_format` (`jenis`, `nama`, `url_surat`) values (2, raw, surat_raw)) C:\xampp\htdocs\premium\vendor\illuminate\database\Connection.php 712
![error](https://user-images.githubusercontent.com/36557759/177493495-b9bd991f-2bd0-49d5-be41-0468b4a9a70f.PNG)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Versi 22.07-premium-beta01

### Tema Yang Digunakan

natra

**Comment by andifahruddinakas** [comment]
https://github.com/OpenSID/OpenSID/issues/5323
