### ISSUE TITLE
Hasil unduh data semua tahun aset pada Buku Inventaris Aset dan Kekayaan Desa tidak muncul

### ISSUE THREAD

**Issue by sulaimanlawidhub** [OpenSID/OpenSID#5343]
Pada versi v22.07 masih terjadi hasil unduh data semua tahun aset pada Buku Inventaris Aset dan Kekayaan Desa tidak muncul

**Comment by yogiperdana** [comment]
Bisa tolong telusuri mas @devrakapriyo saya coba normal

**Comment by apidong** [comment]
pak saya coba normal. mohon di cek lagi @vickyrolanda @devrakapriyo.
harap ditutup kalau tidak ada bug
![image](https://user-images.githubusercontent.com/20056421/194694165-52db4067-6a3d-4325-b64d-4406b487e028.png)
![image](https://user-images.githubusercontent.com/20056421/194694198-3e8b2063-5469-4aa7-b1d6-5d35e8a4a9ef.png)

**Comment by vickyrolanda** [comment]
> Pada versi v22.07 masih terjadi hasil unduh data semua tahun aset pada Buku Inventaris Aset dan Kekayaan Desa tidak muncul

mas @sulaimanlawidhub kami uji coba normal mungkin bisa coba upgrade ke versi yang terbaru pak atau jika memungkin kan bisa hubungi saya melalui telegram untuk melampirkan databasenya .
