### ISSUE TITLE
Permintaan fitur: Untuk menghindari human error sebaiknya tombol perbarui surat hanya ditampilkan untuk level administrator saja atau akun admin yang ditunjuk saja

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#5345]
### Apa kekurangan yg ingin diatasi?

saat ini sedang terjadi error pada fungsi perbarui surat, untuk menghindari error, pengguna merasa jangan mengklik rombol tersebut, untuk menghindari jika ada oranglain yang mengklik tombol tersebut, alangkah baik nya tombol tersebut muncul pada level admin tertentu, atau user yg ditentukan saja.

### Jelaskan solusi yg diinginkan

seperti yang sudah di usulkan oleh pak ariandi,  untuk tombol perbarui, agar hanya muncul di level administrator saja.

atau bahkan hanya muncul di admin yg ditetapkan.

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

Versi 22.07-premium-beta01

**Comment by andifahruddinakas** [comment]
Solusi : 
1. Tampilkan dan proses perbarui template desa hanya jika yang login adalah grup admin / super admin.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1329
