### ISSUE TITLE
Bug/error: Ketika scan kehadiran yg muncul bukan perangkat tersebut

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#5346]
### Jelaskan error yg dialami

Terkait kehadiran, ketika scan kehadiran, maka yg muncul bukan perangkat tersebut, jadi masuk ke perangkat yg lain.
Ketika dicoba perangkat yg lain. masuknya tetap ke perangkat yg lain tadi (sama).

kemudian perangkat tersebut, dinonaktifkan, tapi tetap absensi dia yg muncul ketika prangkat yg lain absen, padahal status absennya udah di non aktifkan.

### Cara untuk mereplikasi errornya

scan perangkat kehadiran.

### Hasil yg diharapkan

1. Pamong dari warga desa pamong_nik harus null.
2. Yg bisa login harusnya cuma pamong yg statusnya aktif.
3. hasil scan sesuai dengan data yang di scan.

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Versi 22.07-premium-beta01

### Tema Yang Digunakan

natra

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1127
