### ISSUE TITLE
Qrcode pada folder >asset>files>qrcode.tpl.png tidak mengarah ke link verifikasi surat

### ISSUE THREAD

**Issue by sulaimanlawidhub** [OpenSID/OpenSID#5348]
File gambar qrcode dengan nama qrcode-tpl.png untuk verifikasi Surat tidak mengarah pada link verifikasi surat ke website desa masing-masing melainkan terverifikasi ke Github.

**Comment by andifahruddinakas** [comment]
Pak @eddieridwan, qrcode-tpl.png adalah template qrcode sementara yang perlu disematkan ke file rtf nantinya file gambar tsb yg akan digantikan / ditimpa dengan qrcode asli saat surat digenrate. 

qrcode-tpl.png memang linknya mengarah ke link github opensid.

**Comment by eddieridwan** [comment]
@andifahruddinakas :
1. jelaskan kepada yg melaporkan
2. lengkapi panduan menjelaskan
3. tutup issuenya.

**Comment by andifahruddinakas** [comment]
Mas @sulaimanlawidhub, panduan untuk menyematkan qrcode ke surat rtf bisa di cek pada pandua : https://github.com/OpenSID/OpenSID/wiki/QRCode-di-Surat-untuk-Verifikasi,-Unduh-dan-Informasi
