### ISSUE TITLE
Permintaan fitur: Batasi impor data penduduk pada pengguna admin

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#5349]
### Jelaskan error yg dialami

fungsi import data penduduk yang juga muncul di level operator, khawatir ada yg iseng dan akan membuat data rusak.
Sebaiknya impor data penduduk hanya dapat dilakukan oleh pengguna admin

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

Impor data penduduk hanya dapat dilakukan oleh pengguna admin saja.

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Versi 22.07-premium-beta01

### Tema Yang Digunakan

natra

**Comment by eddieridwan** [comment]
Bung @devrakapriyo , ini bukan bug. Melainkan permintaan fitur.

**Comment by devrakapriyo** [comment]
baik, terimakasih koreksi nya pak.

**Comment by eddieridwan** [comment]
@vickyrolanda perlu konfirmasi dengan pengguna untuk membatasi impor data penduduk pada admin. Kalau eskpor data penduduk sepertinya boleh saja dilakukan Operator.

**Comment by andifahruddinakas** [comment]
Solusi : 
1. Tampilkan dan proses impor hanya jika yang login adalah grup admin / super admin.
2. Tambahkan pengaturan hak akses selain lihat, ubah, hapus yakni impor/ekspor, unduh/print

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1473
