### ISSUE TITLE
Bug/error: Di versi 22.07 rilis umum hapus artikel tidak bisa / error

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#5350]
### Jelaskan error yg dialami

Di versi 22.07 rilis umum hapus artikel tidak bisa.

### Cara untuk mereplikasi errornya

Admin web > artikel > hapus salah satu artikel.

### Hasil yg diharapkan

Hapus artikel dapat berjalan normal

### Tangkapan layar dan log error

ERROR - 2022-07-06 17:29:49 --> Severity: error --> Exception: Too few arguments to function CI_DB_query_builder::where(), 0 passed in C:\xampp\htdocs\OpenSID\donjo-app\models\Web_artikel_model.php on line 451 and at least 1 expected C:\xampp\htdocs\OpenSID\vendor\codeigniter\framework\system\database\DB_query_builder.php 621

![error artikel](https://user-images.githubusercontent.com/36557759/177531393-d500f811-f46b-4c59-a518-96872cc0e52e.PNG)

### Rilis Versi OpenSID

Rilis Umum

### Versi OpenSID

versi 22.07 rilis umum

**Comment by pandigresik** [comment]
bisa coba solusi ini
https://forum.opendesa.id/d/189-bug-hapus-artikel-gagal-di-versi-2207

**Comment by agungsugiarto** [comment]
Mas @devrakapriyo, issue ini saya close karena di versi premium tidak ditemukan masalah (sudah diperbaiki), kedepannya mohon diperiksa juga di versi premium apakah ditemukan masalah serupa.

Catatan rilis umum yg akan datang: https://github.com/OpenSID/OpenSID/wiki/Rilis-Umum-Yang-Akan-Datang#rilis-umum-v2209--2202-premium

Issue terkait: https://github.com/OpenSID/OpenSID/issues/4714

PR: https://github.com/OpenSID/premium/pull/602
