### ISSUE TITLE
Bug/error: error saat mencetak surat domisili non warga

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#5351]
### Jelaskan error yg dialami

error saat mencetak surat domisili non warga karena menginput nik lebih dari 16 digit

### Cara untuk mereplikasi errornya

layanan surat > setak surat > cari domisili non warga lalu buat surat > isi nik / no ktp lebih dari 16 digit

### Hasil yg diharapkan

buat validasi untuk nik/no ktp dan kk agar menginput tepat 16 digit

### Tangkapan layar dan log error

Query error: Out of range value for column 'nik_non_warga' at row 1 - Invalid query: INSERT INTO log_surat (id_pamong, id_user, no_surat, nama_non_warga, nik_non_warga, keterangan, nama_surat, id_format_surat, bulan, tahun, tanggal, status) VALUES ('21', '1', '428', 'MULID
H', '33041452057900xxx', NULL, 'surat_keterangan_domisili_non_warga_33041452057900xxx_2022-07-05_428.rtf', '183', '07', '2022', '2022-07-05 11:28:57', 1)
![error surat](https://user-images.githubusercontent.com/36557759/177534282-09137d99-5b51-4711-bc09-bd579d8b38fe.PNG)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Versi 22.07-premium-beta01

### Tema Yang Digunakan

natra

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1123
