### ISSUE TITLE
Bug/error: QR Code tidak muncul saat surat dicetak padahal sudah diatur di pengaturan surat

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#5352]
### Jelaskan error yg dialami

Meskipun pada pengaturan surat telah diatur agar Qrcode ditampilakan, namun qrcodenya tidak muncul pada saat cetak suratnya.

### Cara untuk mereplikasi errornya

layanan surat > pengaturan surat > pilih salah satu surat contohnya biodata penduduk > ubah data > pada pilihan qr code pilih ya > simpan

lakukan cetak surat contohnya biodata penduduk, lihat hasilnya qr code tidak tampil.

### Hasil yg diharapkan

qr code dapat tampil sesuai pengaturan yang dipilih.

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Versi 22.07-premium-beta01

### Tema Yang Digunakan

natra

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1120/
