### ISSUE TITLE
Impor C-Desa pada modul pertanahan tidak berfungsi

### ISSUE THREAD

**Issue by sulaimanlawidhub** [OpenSID/OpenSID#5356]
Pilihan Impor C-Desa pada modul pertanahan tidak berfungsi saat di klik, sehingga fitur ini sampai saat ini belum bisa digunakan.![IMG_20220707_062852.jpg](https://user-images.githubusercontent.com/92381858/177653966-6f9a0852-985e-44a7-8fec-7c283e756d67.jpg)

**Comment by andifahruddinakas** [comment]
Duplicate issue https://github.com/OpenSID/OpenSID/issues/3334
