### ISSUE TITLE
Bug/error: Data Stunting Pemantauan bulanan anak 0-2 tahun tidak bisa diisikan umur lebih dari 12 bulan

### ISSUE THREAD

**Issue by khpurnawan** [OpenSID/OpenSID#5357]
### Jelaskan error yg dialami

Pada saat mengisikan "Data Stunting Pemantauan bulanan anak 0-2 tahun" di bagian umur, kami tidak bisa mengisi form dengan nilai lebih dari 12. Sedangkan harusnya, datanya bisa diisikan dengan angka sesuai umur balita (harusnya bisa diisi angka 0 sampai 24).

### Cara untuk mereplikasi errornya

1. Pergi ke KESEHATAN
2. klik STUNTING
3. masuk ke bagian PEMANTAUAN
4. klik bulanan anak 0-2 tahun
5. klik TAMBAH DATA
6. Isikan umur lebih dari 12

### Hasil yg diharapkan

harusnya, datanya bisa diisikan dengan angka sesuai umur balita (harusnya bisa diisi angka 0 sampai 24).

### Tangkapan layar dan log error

![eror](https://user-images.githubusercontent.com/98139011/177682307-f7191efd-bcc7-4358-a6dd-c0dfa6f40a71.jpg)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.7

### Tema Yang Digunakan

denatra

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1121
