### ISSUE TITLE
Nomor surat pada verifikasi qr Code supaya mengikuti format nomor surat pada template surat jika ada

### ISSUE THREAD

**Issue by ai-skematik** [OpenSID/OpenSID#5358]
### Jelaskan error yg dialami

Nomor surat pada verifikasi qr Code semua mengikuti format nomor surat pada pengaturan Aplikasi

### Cara untuk mereplikasi errornya

Ubah template surat dan sesuaikan penomoran surat pada file rtf. kemudian cetak surat tersebut dengan menyisipkan qrcode. pada tampilan verifikasi surat format nomornya tidak mengikuti format di template tp di format pengaturan aplikasi.

### Hasil yg diharapkan

format nomor surat mengikuti masing-masing surat jika setiap surat memliki format berbeda-beda.

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

22.07

**Comment by eddieridwan** [comment]
@vickyrolanda permintaan ini adalah untuk menerapkan hirarki penomoran surat, misalnya:

1. penomoran surat per jenis surat di pengaturan surat (saat ini belum ada)
2. penomoran surat global

Yaitu, pada waktu mencetak surat dan juga di verifikasi QR Code, gunakan penomoran surat sesuai urutan di atas. Yaitu, gunakan penomoran jenis surat, jika ada. Kalau tidak ada gunakan penomoran surat global. 

Yaitu, yg perlu dilakukan adalah:
1. Pindahkan pengaturan penomoran surat global dari Pengaturan > Aplikasi ke Layanan Surat > Pengaturan
2. Tambahkan pengaturan penomoran surat per jenis surat
3. Di template surat, kode isian/sisipan penomoran surat otomatis diisi dengan nomor surat sesuai di atas. Yaitu tidak membuat penomoran surat langsung di template

**Comment by ai-skematik** [comment]
Up

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1523

**Comment by ai-skematik** [comment]
bung @vickyrolanda  dimana tempat mengatur nomor surat per template agar terbaca di qr Code ?

**Comment by ai-skematik** [comment]
Yg saya lihat hanya pemindahan pengaturan penomoran dari pengaturan aplikasi ke pangaturan surat

**Comment by ai-skematik** [comment]
Seperti yang dijelaskan pak @eddieridwan  penomoran surat ada 2

Penomoran perjenis surat itu harusnya ada disini
![image](https://user-images.githubusercontent.com/48144047/201564184-9d1ed959-5bff-4e9b-981a-412509ddb70b.png)

**Comment by ai-skematik** [comment]
untuk penomoran global sudah cocok ada di sini 
![image](https://user-images.githubusercontent.com/48144047/201564329-9c6cde78-0f29-4f96-ae3b-65d77fa0dd67.png)
