### ISSUE TITLE
Bug/error: Realisasi APBDes Tidak sama antara OpenSID dan Siskeudes

### ISSUE THREAD

**Issue by ai-skematik** [OpenSID/OpenSID#5359]
### Jelaskan error yg dialami

Realisasi APBDes Tidak sama antara OpenSID dan Siskeudes

### Cara untuk mereplikasi errornya

Print Out Realisasi keuangan semester I di Siskeudes, kemudian backup database siskeudes tersebut dan impor ke OpenSID. Buat Artikel Keuangan Semester I. Perhatikan Realisasinya.

### Hasil yg diharapkan

Realisasi APBDes antara OpenSID dan Siskeudes sama jika menggunakan Database yang sama

### Tangkapan layar dan log error

https://sidomukti-bolano.desa.id/artikel/2022/7/5/realisasi-apbdes-2022-semester-i

https://drive.google.com/file/d/1blm5w1IKsZXkb01-yMJw0TUG_KJTjxnT/view?usp=sharing

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

22.07

**Comment by yogiperdana** [comment]
Terdapat laporan lain dengan masalah yang sama di forum https://forum.opendesa.id/d/211-anggaran-pembiayaan-pada-footer-berubah-saat-realisasi-pembiayaan-tidak-sama

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1171
