### ISSUE TITLE
Bug/error: Terjadi selisih realisasi antara Laporan Siskeudes dan di OpenSID

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#5365]
### Jelaskan error yg dialami

dari laporan pak @ai-skematik , terjadi selisih realisasi antara Laporan Siskeudes dan di OpenSID.

Di Web OpenSID
https://sidomukti-bolano.desa.id/artikel/2022/7/5/realisasi-apbdes-2022-semester-i

Hasil Siskeudes
https://drive.google.com/file/d/1blm5w1IKsZXkb01-yMJw0TUG_KJTjxnT/view?usp=sharing

### Cara untuk mereplikasi errornya

bandingkan hasilnya.

### Hasil yg diharapkan

laporan sesuai.

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Versi 22.07-premium

**Comment by agungsugiarto** [comment]
duplikat https://github.com/OpenSID/OpenSID/issues/5359
