### ISSUE TITLE
Bug/error: Edit bulanan ibu hamil pada menu stunting tidak dapat dilakukan, atau error.

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#5366]
### Jelaskan error yg dialami

pada berputar.opendesa.id, Edit bulanan ibu hamil tidak dapat dilakukan, atau error seperti pada detail berikut  https://forum.opendesa.id/d/195-menu-stunting 

https://berputar.opendesa.id/stunting/pemantauan_ibu_hamil

### Cara untuk mereplikasi errornya

edit data https://berputar.opendesa.id/stunting/pemantauan_ibu_hamil

### Hasil yg diharapkan

tidak error.

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Versi 22.07-premium

**Comment by agungsugiarto** [comment]
Saya tidak menemukan masalah yg dimaksud, mas @devrakapriyo mohon untuk memastikan sebelum dibuatkan issue terlebih dahulu diuji coba

**Comment by devrakapriyo** [comment]
Saya coba masih error mas di berputar,  silahkan klik tombol edit yang saya lingkari ini.

![berputar hamil](https://user-images.githubusercontent.com/36557759/179365309-7a75eeb1-c63c-456f-908c-51db50de8350.PNG)

dan error nya masih seperti ini.
![berputar_edit](https://user-images.githubusercontent.com/36557759/179365325-c3abd41e-5431-4bcf-b64c-18b1805aae33.PNG)

jika di local tidak error, mohon untuk yang berputar nya juga dilakukan update, karena pengguna jika menemukan error diberputar pasti akan melaporkannya sebagai bug.

**Comment by Zoel-WB** [comment]
Apakah edit datanya belum tersedia-->semua fitur edit belum berfungsi-->atau diklik edit masuk ke halaman error
![image](https://user-images.githubusercontent.com/64481641/180602086-1b4ae615-1599-46e8-84c8-78784a90d89c.png)

**Comment by yogiperdana** [comment]
mas @vickyrolanda dan mas @devrakapriyo apakah bug edit untuk halaman stunting lain selain ibu hamil juga diperbaiki pada issue ini atau mau dibuatkan issue baru?

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1162
