### ISSUE TITLE
Permintaan fitur: Penambahan Fitur Sort by Jumlah Anggota di Form Data Keluarga

### ISSUE THREAD

**Issue by langonsari** [OpenSID/OpenSID#5367]
### Apa kekurangan yg ingin diatasi?

Penambahan Fitur Sort by Jumlah Anggota di Form Data Keluarga untuk mempermudah Sortir Keluarga KK Hilang/Pindah/Mati yang Kepala Keluarga Kosong karena belum dipecah KK diversi sebelumnya.
<img width="733" alt="image" src="https://user-images.githubusercontent.com/96863107/177980911-afb507b0-67a1-485e-97f0-64d31c8bb377.png">

### Jelaskan solusi yg diinginkan

<img width="737" alt="image" src="https://user-images.githubusercontent.com/96863107/177981165-1fadf3d4-92ae-4912-a5fc-9b1a9ee2f6ed.png">

### Apakah ada alternatif lain

<img width="737" alt="image" src="https://user-images.githubusercontent.com/96863107/177981292-51339e89-c958-40d1-b47c-70ec8af3f0be.png">

### Untuk versi OpenSID mana

v22.07-premium

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/OpenSID/pull/7405
