### ISSUE TITLE
Permintaan Fitur Manajemenin Jenis Peraturan

### ISSUE THREAD

**Issue by jimmyjputra3** [OpenSID/OpenSID#5368]
Kebutuhan didesa/kampung kami kami,  sebutan desa dan kepala desa yang sudah diset di pengaturan --> aplikai, tidak berpengaruh pada sebutan jenis peraturan desa. contoh dikami, desa disebut kampung, kades disebut reje, sebutan kampung dan reje sudah diset pada pengaturan aplikasi, namun jenis peraturan desa tetap memunculkan sebutan desa dan kades default. Selain itu di desa kami selain peraturan desa ada juga Qanun yang sejenis dengan Peraturan Desa namun terpisah.

Oleh karena itu kami mohon dibuatkan fitur untuk manajemen Jenis Peraturan Desa : 
1. Tambah Jenis Peraturan
2. Edit Nama Jenis Peraturan 
3. Tambah Jenis Peraturan
4. Hapus Jenis Peraturan

_Originally posted by @jimmyjputra3 in https://github.com/OpenSID/OpenSID/issues/5240#issuecomment-1179708401_

**Comment by andifahruddinakas** [comment]
Sudah disediakan di rilis v22.10-premium
