### ISSUE TITLE
OPENSID: tampilkan token dari layanan di opensid untuk dicopy oleh pengguna

### ISSUE THREAD

**Issue by FirlianiF** [OpenSID/OpenSID#5369]
### Apa kekurangan yg ingin diatasi?

tampilkan token dari layanan di opensid untuk dicopy oleh pengguna

### Jelaskan solusi yg diinginkan

tampilkan token dari layanan di opensid untuk dicopy oleh pengguna

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

-

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1117
