### ISSUE TITLE
Integrasi Data Hasil BDT 2015 Ke dalam OpenSID

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#537]
Pendataan Berbasis Data Terpadu yang dilakukan tahun 2015 oleh Pusat Statistik, Bagaimana cara memasukkannya ke Opensid, dan Kebanyakan Data Hasil PBDT tersebut Beda dengan Data yang tercantum di Kartu Keluarga, supaya hasil PBDT bisa disingkronkan dengan Database Penduduk yang ada di Opensid
[Hasil PBDT Berbasis Rumah Tangga  LOTIM.xlsx](https://github.com/eddieridwan/OpenSID/files/1215122/Hasil.PBDT.Berbasis.Rumah.Tangga.LOTIM.xlsx)

Kalau Bisa di Menu Analisis dengan cara di Import

**Comment by metalab25** [comment]
Issue bagus dan berbobot semoga bisa diterapkan

**Comment by eddieridwan** [comment]
@MUHAMMADRANGSEL Harap lampirkan screenshot dari fitur PBDT di SID CRI. Scriptnya sekalian lebih bagus lagi.

**Comment by MUHAMMADRANGSEL** [comment]
Nah itu maslahnya mas eddie, untuk sid cri yg baru blm ada di saya, hanya
saya dapat Informasi saja bhwa SID CRI sudah bisa.

Pada tanggal 11 Agt 2017 18:02, "Eddie Ridwan" <notifications@github.com>
menulis:

@MUHAMMADRANGSEL <https://github.com/muhammadrangsel> Harap lampirkan
screenshot dari fitur PBDT di SID CRI. Scriptnya sekalian lebih bagus lagi.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/eddieridwan/OpenSID/issues/537#issuecomment-321773988>,
or mute the thread

**Comment by MUHAMMADRANGSEL** [comment]
Kalau form pendatan BDT sdh sayq buat

Pada tanggal 11 Agt 2017 18:05, "MUHAMMAD SPD" <muhammadrangsel@gmail.com>
menulis:

**Comment by MUHAMMADRANGSEL** [comment]
[BDT.zip](https://github.com/eddieridwan/OpenSID/files/1217588/BDT.zip)


Contoh Analisis PBDT Tahun 2015

**Comment by MUHAMMADRANGSEL** [comment]
Mas eddie kan diforum banyak yg dari kab. Gunung Kidul mhn bantuannya maslah bdt ini

**Comment by MUHAMMADRANGSEL** [comment]
Paling tdk dia sama model dengan di menu persil ada tambah menu persil manual
Jadi di.menu analisis ini bisa import data seperti itu

**Comment by eddieridwan** [comment]
@MUHAMMADRANGSEL silakan anda usahakan untuk memperoleh script SID CRI jika sudah ada. Silakan buat posting di Forum FB untuk menanyakan/membahas.

**Comment by MUHAMMADRANGSEL** [comment]
Mungin begini mas eddie di sub menu rumah tangga dibuatkan seperti si menu persis yg bisa memasukkan data persil secara manual

**Comment by eddieridwan** [comment]
[buku-i-pemuktahiran-basis-data-terpadu-2015.pdf](https://github.com/eddieridwan/OpenSID/files/1305468/buku-i-pemuktahiran-basis-data-terpadu-2015.pdf)

@MUHAMMADRANGSEL , setelah sekilas membaca mengenai PBDT, ada beberapa kesan dan pertanyaan:

1. Pengumpulan data PBDT merupakan survei oleh BPS, bukan data administratif. Data yang dikumpulkan ditentukan tiap kali ada pemutakhiran, dan bisa berbeda setiap kali.
2. Basis pengumpulan data adalah _rumah tangga_ yang belum tentu sama dengan konsep _keluarga_ dari Disdukcapil dan juga belum tentu sama dengan konsep _rumah tangga_ yang sekarang ada di SID.
3. Penggunaan data yang dikumpulkan sepertinya untuk melakukan analisis supra-desa (yaitu perbandingan antar-desa/kec/kab/prov) untuk mengidentifikasi daerah2 yg memerlukan intervensi. Karena data itu data sesaat, tidak jelas proses untuk memutakhirkan data yang terkumpul, kecuali melalui survei lagi. Berbeda dengan Prodeskel yang dikumpulkan setiap tahun, dan tidak berubah bentuknya.

Pertanyaan:
1. Apa definisi 'rumah tangga' yang digunakan BPS? Apakah definisi ini selaras dengan konsep 'rumah tangga' yang ada di SID? Apakah 'nomor urut' rumah tangga yang digunakan BPS baku, dalam arti jika ada pemutakhiran lanjutan entah kapan, bisa dijamin BPS akan menggunakan nomor yang sama?
2. Apa tujuan menyimpan data BDT di OpenSID? Apakah untuk melakukan analisis sendiri oleh desa? Apakah untuk membakukan data _rumah tangga_ supaya data yang terkumpul siap dimutakhirkan? Jika akan dijadikan basis data untuk survei BPS yang akan datang, apakah justru bertentangan dengan proses BPS yang langsung survei/pencacahan ke lokasi rumah tangga?
3. Bagaimana proses yang dibayangkan untuk me-sinkronkan data BDT dengan data berbasis Kartu Keluarga yang ada di SID?
4. Sepertinya data Prodeskel dan BDT tumpang tindih -- serupa tapi belum tentu sama. Bagaimana menyimpan keduanya di SID -- dan menyelaraskan?

**Comment by eddieridwan** [comment]
Mungkin yang anda inginkan adalah untuk memasukkan BDT 2015 sebagai analisis, menggunakan Modul Analisis. Sayangnya kami sama sekali tidak mengerti cara penggunaan modul itu. Penjelesan yang anda mulai di https://github.com/eddieridwan/OpenSID/wiki/Pengelolaan-Analisis kurang mendalam dan tidak disertai contoh.

Supaya kami dapat mengerti fungsi dan cara penggunaan modul Analisis, harap kirimkan contoh lengkap; juga kirimkan materi pelatihan (lengkap) yang anda ikuti, dsbnya. Tanpa info ini, sangat sulit untuk kami bantu --- karena tidak mengerti.

**Comment by MUHAMMADRANGSEL** [comment]
Betul sekali mas eddie memang yg saya maksudkan seperti itu dan nanti saya
buatkan contoh pengisian format bdt yg tahun 2015 kebetulqn dulu saya
sebagai petugas pencacah/pendata

Pada tanggal 15 Sep 2017 15:10, "Eddie Ridwan" <notifications@github.com>
menulis:

**Comment by eddieridwan** [comment]
@MUHAMMADRANGSEL jika BDT 2015 ingin dimasukkan menggunakan Modul Analisis, seperti dikatakan di atas:

Supaya kami dapat mengerti fungsi dan cara penggunaan modul Analisis, harap:

1. kirimkan contoh lengkap pengisian analisis (kirim contoh data analisis yang bisa diimpor); 
1. **juga kirimkan materi (lengkap) dari pelatihan modul Analisis yang anda ikuti**, dsbnya. 

Tanpa info ini, sangat sulit untuk kami bantu --- karena tidak mengerti.

**Comment by MUHAMMADRANGSEL** [comment]
Ok mas eddie tiang cari dulu contoh pengisian yg saya sdh isi

Pada tanggal 15 Sep 2017 18:18, "Eddie Ridwan" <notifications@github.com>
menulis:

**Comment by eddieridwan** [comment]
Sudah dicommit melalui issue #800.
