### ISSUE TITLE
OPENSID: update validasi dan ketentuan-ketentuan yang berhubungan dengan pendaftaran kerjsama

### ISSUE THREAD

**Issue by FirlianiF** [OpenSID/OpenSID#5370]
### Apa kekurangan yg ingin diatasi?

-

### Jelaskan solusi yg diinginkan

-

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

-

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1118
