### ISSUE TITLE
Permintaan fitur: tambahkan popup untuk melihat foto pada galeri dengan jelas 

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#5371]
### Apa kekurangan yg ingin diatasi?

masuk ke Website > galeri > masuk ke salah satu album > klik foto di dalam album tersebut

saat ini foto tidak full dan terlihat kecil, bisa dibuatkan popup untuk dapat melihat gambar secara lebih jelas dan besar.

### Jelaskan solusi yg diinginkan

bisa dibuatkan popup untuk dapat melihat gambar secara lebih jelas dan besar.

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

Versi 22.08-premium

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1465
