### ISSUE TITLE
Permintaan fitur: buat nama album menjadi wajib di isi

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#5372]
### Apa kekurangan yg ingin diatasi?

Admin web > galeri > edit salah satu album.

saat ini input nama album masih opsional yang mngakibatkan kurang jelas info pada album galeri jika nama album nya tidak wajib di isi.

### Jelaskan solusi yg diinginkan

buat nama album menjadi required

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

Versi 22.08-premium

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1200
