### ISSUE TITLE
Bug/error: gambar gagal disimpan tapi alert nya berhasil disimpan

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#5373]
### Jelaskan error yg dialami

Proses simpan berlangsung dan muncul 
alert berhasil disimpan, padahal gambar 
tidak tersimpan dengan baik, ketika di load 
gambar menjadi tidak tampil / not found

### Cara untuk mereplikasi errornya

Admin web > galeri > edit salah satu album

"*coba testing dengan berbagai 
macam foto, bisa gunakan foto yang
saya upload."

### Hasil yg diharapkan

jika gambar tidak sesuai kriteria atau gagal disimpan, 
seharusnya gambar tidak tersimpan, dan muncul pesan
data gagal disimpan.

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Versi 22.07-premium

### Tema Yang Digunakan

natra

**Comment by agungsugiarto** [comment]
Mas @devrakapriyo bisa berikan contoh gambar yg di upload?

kemudian apakah issue https://github.com/OpenSID/OpenSID/issues/5339 dibuka kembali masih berkaitan dengan issue ini?

**Comment by devrakapriyo** [comment]
> Mas @devrakapriyo bisa berikan contoh gambar yg di upload?
> 
> kemudian apakah issue #5339 dibuka kembali masih berkaitan dengan issue ini?

ini bug yang berbeda mas @agungsugiarto , dan sebelumnya sudah diberi masukan oleh mas vicky untuk error ini dibuat issue baru saja.
berikut link gambar untuk testing error yang saya alami, silahkan di download dan coba replikasi.
https://drive.google.com/file/d/1LCAJ3OtEG6ZJQJNJd_a43Fk9-eX3XiTe/view

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1135
