### ISSUE TITLE
Bug/error: perbaiki validasi saat input token pelanggan dan perbaiki notif yang tidak muncul

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#5374]
### Jelaskan error yg dialami

- [x] tombol batal pada popup ganti menjadi Tutup, karena berfungsi untuk menutup popup.
- [x] data tersimpan padahal token kosong (tambahkan required, jadikan input token menjadi wajib di isi)
- [ ] tambah validasi token diinput harus lebih dari 500 huruf dan tidak boleh lebih dari 600 huruf
- [x] tambahkan alert / notif saat data disimpan agar pelanggan tau data tersebut berhasil disimpan atau gagal disimpan 

### Cara untuk mereplikasi errornya

1. Info Desa > Layanan Pelanggan 
2. Klik icon gear pada header di kanan atas 
3. Muncul popup
4. Klik tombol batal

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Versi 22.07-premium

### Tema Yang Digunakan

natra

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1124
