### ISSUE TITLE
Permintaan fitur:  Non Aktifkan menu impor data penduduk jika Tanggal Data Lengkap  telah terisi dan di aktifkan.

### ISSUE THREAD

**Issue by ai-skematik** [OpenSID/OpenSID#5376]
### Apa kekurangan yg ingin diatasi?

Saat ini walaupun data penduduk telah dinyatakan aktif tp masih tetap bisa dilakukan impor data penduduk sehingga Laporan Bulanan akan menjadi rancu.

### Jelaskan solusi yg diinginkan

Nonaktifkan fitur impor data penduduk jika data dinyatakan lengkap

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

22.08-Premium

### Informasi tambahan

-

**Comment by eddieridwan** [comment]
Setelah data penduduk dinyatakan lengkap, impor data penduduk seharusnya tidak lagi mengubah keanggotaan keluarga sehingga seharunya tidak akan mempengaruhi jumlah KK di laporan bulanan. Yaitu setelah data penduduk dinyatakan lengkap, impor data penduduk `hanya dapat digunakan untuk mengubah data penduduk yg sudah ada secara massal`, dan tidak dapat digunakan untuk:

- menambah penduduk baru
- mengubah status dasar penduduk
- mengubah SHDK seorang penduduk

Bung @agungsugiarto @apidong @devrakapriyo : mohon pastikan cara bekerja impor data penduduk sudah seperti di atas. 

@ai-skematik , fitur impor data penduduk tetap berguna setelah data penduduk dinyatakan lengkap -- khusus untuk bisa mengubah data penduduk yg sdh ada, seperti tanggal lahir atau data kelahiran atau lainnya, secara massal. Caranya dengan langkah sbb:

1. ekspor data penduduk
2. ubah kolom data di file hasil ekspor data penduduk
3. impor data hasil langkah (2) untuk mengubah data penduduk secara massal.

Bung @devrakapriyo , pastikan ketentuan di atas dimasukkan ke panduan.

**Comment by devrakapriyo** [comment]
> Setelah data penduduk dinyatakan lengkap, impor data penduduk seharusnya tidak lagi mengubah keanggotaan keluarga sehingga seharunya tidak akan mempengaruhi jumlah KK di laporan bulanan. Yaitu setelah data penduduk dinyatakan lengkap, impor data penduduk `hanya dapat digunakan untuk mengubah data penduduk yg sudah ada secara massal`, dan tidak dapat digunakan untuk:
> 
> * menambah penduduk baru
> * mengubah status dasar penduduk
> * mengubah SHDK seorang penduduk
> 
> Bung @agungsugiarto @apidong @devrakapriyo : mohon pastikan cara bekerja impor data penduduk sudah seperti di atas.
> 
> @ai-skematik , fitur impor data penduduk tetap berguna setelah data penduduk dinyatakan lengkap -- khusus untuk bisa mengubah data penduduk yg sdh ada, seperti tanggal lahir atau data kelahiran atau lainnya, secara massal. Caranya dengan langkah sbb:
> 
> 1. ekspor data penduduk
> 2. ubah kolom data di file hasil ekspor data penduduk
> 3. impor data hasil langkah (2) untuk mengubah data penduduk secara massal.
> 
> Bung @devrakapriyo , pastikan ketentuan di atas dimasukkan ke panduan.

Baik pak
