### ISSUE TITLE
Bug/error: Typo pada alert saat menambah hari libur dengan tanggal yang sama

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#5377]
### Jelaskan error yg dialami

muncul alert Tanggal TERAKIT.
typo pada tulisan terakit, harusnya tanggal terkait.

### Cara untuk mereplikasi errornya

1.buka modul kehadiran > hari libur
2.tambahkan data baru dgn memasukka tgl yg sudah ad
3.muncul alert

### Hasil yg diharapkan

Tanggal Terkait.

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Versi 22.07-premium

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1125
