### ISSUE TITLE
Bug/error: error saat cetak PDF di menu Cetak Surat saat hanya ada a.n

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#5379]
### Jelaskan error yg dialami

error saat cetak PDF di menu Cetak Surat, bisa di lihat di PR ini https://github.com/OpenSID/premium/pull/1122

### Cara untuk mereplikasi errornya

1. layanan Surat
2. cetak Surat
3. pilih surat TinyMCE
4. klik tombol 'Cetak PDF'

### Hasil yg diharapkan

tidak terjadi error

### Tangkapan layar dan log error

![](https://user-images.githubusercontent.com/36557759/178298427-6016b36c-5a0f-4172-80c4-e696e0cdea0b.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

22.07 premium

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1131
