### ISSUE TITLE
Bug/error: error saat cetak surat menggunakan tinyMce

### ISSUE THREAD

**Issue by apidong** [OpenSID/OpenSID#5380]
### Jelaskan error yg dialami

error saat , cetak menggunakan tyni mce

### Cara untuk mereplikasi errornya

- pada pemerintah desa, aktifkan a.n dan matikan u.b
- buat surat menggunakan tiny MCE
- cetak surat pdf

### Hasil yg diharapkan

tidak error

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/20056421/178405870-4db6d247-22c8-4956-8b07-8902114f6456.png)

### Rilis Versi OpenSID

Rilis Umum

### Versi OpenSID

v22.07-premium

### Tema Yang Digunakan

-

### Informasi tambahan

-

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1131

**Comment by ryanfigo12** [comment]
Cara ubah pada pemerintah desa, aktifkan a.n dan matikan u.b gimana?
