### ISSUE TITLE
Bug/error: Tampilkan Error saat terjadi kegagalan dalam proses backup inkremental

### ISSUE THREAD

**Issue by apidong** [OpenSID/OpenSID#5381]
### Jelaskan error yg dialami

terkadang saat backup dilakukan, terdapat masalah saat prosessnya. tapi pada halaman backup masih tertulis backup sedang diproses sehingga pengguna mengira proses backup masih berlangsung padahal tidak.

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

-

### Tema Yang Digunakan

-

### Informasi tambahan

-

**Comment by vickyrolanda** [comment]
ok mas, saya uji coba dengan buat drive C saya full tinggal 0 KB , lalu saya coba backup dan muncul informasi gagal seperti ini : 
<img width="579" alt="image" src="https://user-images.githubusercontent.com/59082428/181597900-4c62b710-aef6-4291-b54f-c020dca81a65.png">

telah di kerjain di PR https://github.com/OpenSID/premium/pull/1137
