### ISSUE TITLE
Bug/error: Pada Pengaturan Surat

### ISSUE THREAD

**Issue by Pematung** [OpenSID/OpenSID#5382]
### Jelaskan error yg dialami

Hal ini terjadi saat baru pertama kali install OpenSID baik dengan cara git maupun manual

![image](https://user-images.githubusercontent.com/105429258/178629248-6c2b3e21-1d56-405a-92ef-ae30c58d8134.png)

### Cara untuk mereplikasi errornya

1. Layanan Surat
2. Pengaturan Surat
3. Keterangan Pengantar
4. Ubah Data

### Hasil yg diharapkan

Hasil yang diharapkan adalah tampilannya normal seperti gambar dibawah ini

![image](https://user-images.githubusercontent.com/105429258/178629572-78eedcab-efa9-40b6-9354-20a1bd3fb6a6.png)

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/105429258/178629613-52eb2417-3c5a-42fb-810f-0b9283b7334c.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

22.07 Premium Rev01

### Tema Yang Digunakan

Batuah & Denatra 6.2

### Informasi tambahan

-

**Comment by WAHYUDIK** [comment]
di local saya tidak terjadi seperti itu bang 
![image](https://user-images.githubusercontent.com/31026980/178639573-ffe12ddb-69ab-406d-a2c1-dc0e28266417.png)

**Comment by Pematung** [comment]
Apakah itu Install baru di localhost atau update

**Comment by Pematung** [comment]
> di local saya tidak terjadi seperti itu bang ![image](https://user-images.githubusercontent.com/31026980/178639573-ffe12ddb-69ab-406d-a2c1-dc0e28266417.png)

Premium atau Rilis Umum yang bapak gunakan

**Comment by agungsugiarto** [comment]
Pak @Pematung bisa dicoba untuk menghapus semua file yg ada di folder `storage/framework/views/` kecuali file `.gitignore`

**Comment by Pematung** [comment]
> Pak @Pematung bisa dicoba untuk menghapus semua file yg ada di folder `storage/framework/views/` kecuali file `.gitignore`

Tetep ngak bisa pak walaupun dihapus semua file yg ada di storage/framework/views/ kecuali file .gitignore

**Comment by agungsugiarto** [comment]
Sudah dirilis ulang https://github.com/OpenSID/rilis-premium/releases/tag/v22.07-premium-rev01

**Comment by Pematung** [comment]
> storage/framework/views/

OK Problem Solved
1. git checkout master
2. git pull
3. hapus semua isi yang ada di folder storage/framework/views/

Silahkan di close aja issue ini pak
