### ISSUE TITLE
Bug/error: Statistik Laporan bulanan untuk jumlah Keluarga tidak singkron dengan data wilayah

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#5383]
### Jelaskan error yg dialami

Statistik > Laporan bulanan untuk jumlah Keluarga masih tidak singkron dengan data wilayah

https://forum.opendesa.id/d/180-statistik-laporanbulanan

### Cara untuk mereplikasi errornya

![1656382043-578964-image](https://user-images.githubusercontent.com/36557759/178862855-b9211e39-6231-46bf-ab19-296f4680eb78.png)
-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Versi 22.08-premium

**Comment by eddieridwan** [comment]
@devrakapriyo untuk kasus2 jumlah KK tidak sesuai dengan data wilayah/keluarga, perlu info sebagai berikut:

1. dapatkan database desa ybs. Masalahnya hanya bisa ditemukan berdasarkan pemeriksaan data ybs
2. perlu diperoleh persisnya langkah2 yg mereka lakukan, terutama: (a) apakah mereka menggantikan kepala desa yg meninggal istri atau anggota keluarga yg lain; atau (b) apakah mereka melakukan impor data penduduk setelah data penduduk dinyatakan lengkap, atau mereka sengaja mengembalikan status belum lengkap khusus untuk impor data penduduk lagi. Diketahui kedua kasus itu akan menyebabkan tidak sinkron. Seharusnya sudah diterapkan beberapa fitur untuk mencegah dilakukkannya hal2 di atas, tetapi bisa saja mereka lakukan menggunakan versi2 lama. Namun demikian, sebaiknya anda lakukan testing (buat test case) untuk memastikan kedua hal di atas tidak bisa dilakukan lagi.

Seperti dijelaskan di tempat lain, setelah data penduduk dinyatakan lengkap, impor data penduduk hanya dapat digunakan untuk mengubah kolom data penduduk yg sudah ada, dan tidak dapat digunakan untuk mengubah status keanggotaan keluarga ataupun status dasar penduduk.

**Comment by balongbesuk** [comment]
![image](https://user-images.githubusercontent.com/35319600/179123041-3fd995fe-c5a5-4ba2-a851-73c6dab51068.png)

mungkin ini masukan 

hilangkan isian ubahan kepala keluarga pada anggota keluarga agar ketika kepala keluarga meninggal/pindah tidak ada yang akan menggantikan

**Comment by balongbesuk** [comment]
![Untitled](https://user-images.githubusercontent.com/35319600/179131941-f8770e0d-2066-4547-b6e3-c15312466265.jpg)

mungkin bs d tambahkan juga filter untuk no KK tanpa Kepala Keluarga, (Operator kadang lupa membuatkan KK baru untuk keluarga yang ditinggalkan Kepala Keluarganya)

**Comment by eddieridwan** [comment]
> ![Untitled](https://user-images.githubusercontent.com/35319600/179131941-f8770e0d-2066-4547-b6e3-c15312466265.jpg)
> 
> mungkin bs d tambahkan juga filter untuk no KK tanpa Kepala Keluarga, (Operator kadang lupa membuatkan KK baru untuk keluarga yang ditinggalkan Kepala Keluarganya)

Bukannya itu sudah ada sebagai filter KK Kosong?

**Comment by balongbesuk** [comment]
> > ![Untitled](https://user-images.githubusercontent.com/35319600/179131941-f8770e0d-2066-4547-b6e3-c15312466265.jpg)
> > mungkin bs d tambahkan juga filter untuk no KK tanpa Kepala Keluarga, (Operator kadang lupa membuatkan KK baru untuk keluarga yang ditinggalkan Kepala Keluarganya)
> 
> Bukannya itu sudah ada sebagai filter KK Kosong?

ah iya benar (baru inget perbaikan laporan bulanan data kk kosong saya ada sebagian masih terisi anggota keluarga) mungkin dtambahkan sortir untuk anggota keluarga agar pengguna tahu bahwa kk kosong ada yang masih memiliki anggota keluarga

**Comment by andifahruddinakas** [comment]
> > > ![Untitled](https://user-images.githubusercontent.com/35319600/179131941-f8770e0d-2066-4547-b6e3-c15312466265.jpg)
> > > mungkin bs d tambahkan juga filter untuk no KK tanpa Kepala Keluarga, (Operator kadang lupa membuatkan KK baru untuk keluarga yang ditinggalkan Kepala Keluarganya)
> > 
> > 
> > Bukannya itu sudah ada sebagai filter KK Kosong?
> 
> ah iya benar (baru inget perbaikan laporan bulanan data kk kosong saya ada sebagian masih terisi anggota keluarga) mungkin dtambahkan sortir untuk anggota keluarga agar pengguna tahu bahwa kk kosong ada yang masih memiliki anggota keluarga

Mungkin mmang sebaiknya ubah hubung untuk menjadi kepala KK hilangkan, harusnya kepala KK dipilih hanya saat buat KK baru saja.

**Comment by devrakapriyo** [comment]
> @devrakapriyo untuk kasus2 jumlah KK tidak sesuai dengan data wilayah/keluarga, perlu info sebagai berikut:
> 
> 1. dapatkan database desa ybs. Masalahnya hanya bisa ditemukan berdasarkan pemeriksaan data ybs
> 2. perlu diperoleh persisnya langkah2 yg mereka lakukan, terutama: (a) apakah mereka menggantikan kepala desa yg meninggal istri atau anggota keluarga yg lain; atau (b) apakah mereka melakukan impor data penduduk setelah data penduduk dinyatakan lengkap, atau mereka sengaja mengembalikan status belum lengkap khusus untuk impor data penduduk lagi. Diketahui kedua kasus itu akan menyebabkan tidak sinkron. Seharusnya sudah diterapkan beberapa fitur untuk mencegah dilakukkannya hal2 di atas, tetapi bisa saja mereka lakukan menggunakan versi2 lama. Namun demikian, sebaiknya anda lakukan testing (buat test case) untuk memastikan kedua hal di atas tidak bisa dilakukan lagi.
> 
> Seperti dijelaskan di tempat lain, setelah data penduduk dinyatakan lengkap, impor data penduduk hanya dapat digunakan untuk mengubah kolom data penduduk yg sudah ada, dan tidak dapat digunakan untuk mengubah status keanggotaan keluarga ataupun status dasar penduduk.

Baik noted pak

**Comment by agungsugiarto** [comment]
Mas @vickyrolanda silahkan di analisis issue ini

**Comment by andifahruddinakas** [comment]
Mas @devrakapriyo, kalau sudah ada databasenya bisa kirim ke telegram saya.

**Comment by devrakapriyo** [comment]
issue ditutup karena tidak tersedia database dari laporan tersebut.
