### ISSUE TITLE
Bug/error: Backup inkremental memberatkan 

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#5390]
### Jelaskan error yg dialami

Backup inkremental memberatkan karena menggunakan memori banyak baik pada waktu membuat archive maupun pada waktu download.

### Cara untuk mereplikasi errornya

Lakukan backup inkremental pada folder desa besar pertama kali.

### Hasil yg diharapkan

@apidong @vickyrolanda 
Solusi saat ini untuk backup inkremental memberatkan karena menggunakan cara yg langsung proses seluruh isi file menggunakan memori, dan juga tidak menggunakan sys_get_temp_dir sehingga harus mengelola file. Jadi akan gagal jika memori tidak memadai pada waktu membuat zip maupun pada waktu download.
Harap lihat cara yg dilakukan untuk method database/desa_backup yang menggunakan class FlxZipArchive. 

![incr-1](https://user-images.githubusercontent.com/249563/179339490-c67f7b21-a736-443f-9712-e28be245f578.jpg)
![incr-2](https://user-images.githubusercontent.com/249563/179339501-85716f01-cf04-48da-9779-867eb1f4e0d6.jpg)

Di class FlzZipArchive, menggunakan temp file, disediakan cara untuk mengumpulkan isi directory secara recursive tidak menggunakan memori dan download file zip besar secara sepotong-sepotong.

![incr-3](https://user-images.githubusercontent.com/249563/179339509-772d95a7-e024-427d-b92f-690b6a2f169e.jpg)

Lihat cara penggunaannya di method desa_backup

<img width="556" alt="image" src="https://user-images.githubusercontent.com/249563/179339538-3a6f067b-bd1c-497f-8cdc-39f6600d83f6.png">

### Tangkapan layar dan log error

s

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.07-premium-beta01

**Comment by eddieridwan** [comment]
@apidong @vickyrolanda , mungkin solusi sederhana adalah menambah parameter tanggal/waktu pada waktu memanggil FlxZipArchive.read_dir. Kemudian di method addDirDo gunakan tanggal/waktu tsb hanya menambahkan file yang waktu dibuat/diubah sesudah waktu tersebut. 

Kalau anda lakukan itu, membuat archive backup inkremental akan sederhana sekali:

```
        $za = new FlxZipArchive();
        $za->read_dir(DESAPATH, $waktu_backup_terakhir);
```

**Comment by eddieridwan** [comment]
@apidong @vickyrolanda karena menggunakan background job, waktu antara pembuatan archive dan proses download mungkin bisa lama. Jadi ada kemungkinan file di temporary direktori akan dibersihkan oleh sistem (bisa saja sehabis session). Karena itu memang perlu menggunakan file khusus untuk menyimpan archive secara pasti. Untuk itu, yg bisa dilakukan adalah membuat constructor di class FlxZipArchive, dan kemudian mengirim path ke file yg akan digunakan pada waktu membuat FlxZipArchive baru.

```
        $za = new FlxZipArchive($path_ke_file_archive);
```

Yaitu, gunakan file tersebut jika dikirim sebagai parameter. Jika tidak, gunakan temporary file.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1137
