### ISSUE TITLE
Tambahkan kolom total pada laporan penduduk

### ISSUE THREAD

**Issue by mranca** [OpenSID/OpenSID#5391]
### Apa kekurangan yg ingin diatasi?

Kurangnya kolom total sehingga harus menghitungnya secara manual

### Jelaskan solusi yg diinginkan

![1657635767-804596-img-20220712-221949](https://user-images.githubusercontent.com/76085245/179379868-4cf51117-4bee-45e2-9a8f-9232743826b1.jpg)
Perlu di tambahkan kolom total lampiran itu berada pada menu buku administrasi desa > administrasi penduduk > buku rekapitulasi jumlah penduduk

### Apakah ada alternatif lain

Tidak ada

### Untuk versi OpenSID mana

22.07.rev1

### Informasi tambahan

.

**Comment by andifahruddinakas** [comment]
https://github.com/OpenSID/OpenSID/issues/5392#issuecomment-1265154070

**Comment by andifahruddinakas** [comment]
Duplicate of https://github.com/OpenSID/OpenSID/issues/5392
