### ISSUE TITLE
Tambahkan kolom total pada laporan penduduk

### ISSUE THREAD

**Issue by mranca** [OpenSID/OpenSID#5392]
### Apa kekurangan yg ingin diatasi?

Kurangnya kolom total sehingga harus menghitungnya secara manual

### Jelaskan solusi yg diinginkan

![1657635767-804596-img-20220712-221949](https://user-images.githubusercontent.com/76085245/179379868-4cf51117-4bee-45e2-9a8f-9232743826b1.jpg)
Perlu di tambahkan kolom total lampiran itu berada pada menu buku administrasi desa > administrasi penduduk > buku rekapitulasi jumlah penduduk

### Apakah ada alternatif lain

Tidak ada

### Untuk versi OpenSID mana

22.08 premium

### Informasi tambahan

.

**Comment by andifahruddinakas** [comment]
Karena hasil cetak disesuaikan dengan aturan yang berlaku. Mungkin dibuat pilihan saja saat mau cetak/unduh, apakah dengan total atau tidak.

Pada halaman view utama (index), tampilkan akumulasi masing2 kolom. Yang dibatasi hanya cetak/unduh.

**Comment by mranca** [comment]
Ok kasih pilihan saja untuk cetak total atau tidak,karena kolom total itu sangat dibutuhkan untuk mengetahui total keseluruhan penduduk tanpa harus lagi unduh dalam bentuk excel dan di jumlahkan dengan rumus

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/OpenSID/pull/7404
