### ISSUE TITLE
Bug/error: Laporan Hasil Analisis datanya tidak muncul

### ISSUE THREAD

**Issue by WAHYUDIK** [OpenSID/OpenSID#5393]
### Jelaskan error yg dialami

pada saat ini membuat master analisis berbasis individu data hasil input tidak muncul pada Laporan Hasil Klasifikasi

![image](https://user-images.githubusercontent.com/31026980/179389218-881b29e4-5c60-4b13-83be-6d8cb00dca6a.png)

untuk analisis berbasis keluarga datanya muncul

![image](https://user-images.githubusercontent.com/31026980/179389241-2f6503f9-5ca0-4d0b-9675-e2afee4b0996.png)

### Cara untuk mereplikasi errornya

buat master analisis baru berbasis individu, kemudian isi data individunya, cek hasil pada bagian Laporan Hasil Analisis

### Hasil yg diharapkan

Data pada Laporan Hasil Klasifikasi datanya muncul seperti yang ada pada basis keluarga.

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/31026980/179389302-17790197-6a28-4520-9d93-d0855a4e9d75.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

berputar.opendesa.id

### Informasi tambahan

sudah uji coba beberapa kali membuat master analisis yang baru, namun hasilnya juga sama

**Comment by vickyrolanda** [comment]
> ### Jelaskan error yg dialami
> pada saat ini membuat master analisis berbasis individu data hasil input tidak muncul pada Laporan Hasil Klasifikasi
> 
> ![image](https://user-images.githubusercontent.com/31026980/179389218-881b29e4-5c60-4b13-83be-6d8cb00dca6a.png)
> 
> untuk analisis berbasis keluarga datanya muncul
> 
> ![image](https://user-images.githubusercontent.com/31026980/179389241-2f6503f9-5ca0-4d0b-9675-e2afee4b0996.png)
> 
> ### Cara untuk mereplikasi errornya
> buat master analisis baru berbasis individu, kemudian isi data individunya, cek hasil pada bagian Laporan Hasil Analisis
> 
> ### Hasil yg diharapkan
> Data pada Laporan Hasil Klasifikasi datanya muncul seperti yang ada pada basis keluarga.
> 
> ### Tangkapan layar dan log error
> ![image](https://user-images.githubusercontent.com/31026980/179389302-17790197-6a28-4520-9d93-d0855a4e9d75.png)
> 
> ### Rilis Versi OpenSID
> Rilis Premium
> 
> ### Versi OpenSID
> berputar.opendesa.id
> 
> ### Tema Yang Digunakan
> _No response_
> 
> ### Informasi tambahan
> sudah uji coba beberapa kali membuat master analisis yang baru, namun hasilnya juga sama

Selamat siang pak @WAHYUDIK , 
Perlu di ketahuin data Individual itu adalah hanya sekedar judul yang diberikan adapun error / bug yang bapak rasakan adalah karena point capaian tidak terpenuhi dari setiap jawaban data survey. 
Mari kita demokan : 
<img width="749" alt="image" src="https://user-images.githubusercontent.com/59082428/179482838-b90a7671-984e-43e9-824a-8f6dacf1ed51.png">
Contoh Saya isikan seperti ini : 
**Step 1. Mulai dari pengisian judul analisis data**
<img width="756" alt="image" src="https://user-images.githubusercontent.com/59082428/179483327-6c497f61-ab1f-4ea3-94b9-66ef07b56637.png">
Maka Hasil di list akan terlihat seperti berikut  ini : 
<img width="776" alt="image" src="https://user-images.githubusercontent.com/59082428/179483450-75146334-b48e-4569-b7d4-b1e3affda3d3.png">
**Step 2. masuk ke details pengisian data** 
Maka masuk ke halaman berikut ini : 
<img width="773" alt="image" src="https://user-images.githubusercontent.com/59082428/179483954-4f7db164-f84d-4496-adea-ced3c65aefd4.png">
Silahkan di isi sesuai kebutuhan namun saya akan kasih contoh misalkan . 
1. Kategori / Variabel saya isi seperti berikut ini : 
<img width="761" alt="image" src="https://user-images.githubusercontent.com/59082428/179484272-9eee7b65-39f3-4d79-94d3-72fe1606e9fa.png">
2. Lalu saya tamabahkan indikator / pertanyaan seperti berikut ini : 
<img width="770" alt="image" src="https://user-images.githubusercontent.com/59082428/179484784-b146e091-23d7-4f2b-b805-1c9792f16468.png">
- yang perlu di perhatikan adalah bobotnya , karena bobot ini akan menentukan data analisis terpenuh atau tidak 
<img width="559" alt="image" src="https://user-images.githubusercontent.com/59082428/179485718-106843c8-ccba-4429-ab69-ff90040e9636.png">

3. saya telah menambah 2 pertanyaan maka kita akan mengisi opsi jawabannya.
- untuk pertanyaan ini : 
<img width="559" alt="image" src="https://user-images.githubusercontent.com/59082428/179485807-e752fe90-31ab-47e8-8b8a-882a6d763aa0.png">
- maka saya tambahkan jawaban dengan bobot point seperti berikut ini : 
<img width="568" alt="image" src="https://user-images.githubusercontent.com/59082428/179485884-7c8e5e50-cda2-4048-9b4b-c2401825690e.png">
maka setiap nilai / ukuran akan di kalikan dengan bobot pertanyaannya , misalkan bobot 1, jawabannya dengan nilai 5 maka point yang akan di kumpulkan dari 1 pertanyaan tersebut adalah 5 , jika da pertanyaan lain maka point tersebut akan di tambah ,total point ini akan menjadi data analisis sesuai klasifikasi yang di tentukan.
<img width="682" alt="image" src="https://user-images.githubusercontent.com/59082428/179487811-8e3939ec-f943-4033-8eb3-52c498f6eeee.png">

misal : 
- Keluarga mampu pointnya min 10 s/d 30
- keluarga tidak mampu pointnya 5 s/d 9

nah jika data penduduk yang kita input dengan jawaban tertentu lalu point  yang di jumlahkan terdapat point yang sesuai dengan data klasifikasi diatas maka laporannya akan muncul namun jika tidak ada yang sesuai maka di laporan tidak akan muncul. misalkan 
1. jawaban Point 30 (maka akan akan tampil)
2. jawaban Point 4 (maka tidak akan tampil)

akan tampil jika nilai poin sesuai dengan data analisis contoh dibawah ini :  
<img width="578" alt="image" src="https://user-images.githubusercontent.com/59082428/179488004-ee5a3309-be78-41b1-8887-7859ba7cdba2.png">

**Comment by WAHYUDIK** [comment]
Baik oak @vickyrolanda terima kasih atas pencerahannya, masalah sudah teratasi, issue saya close. Saya ganti issue lain terkait analisis, yakni jika diakses melalui android ada beberapa tampilan kurang responsiv
