### ISSUE TITLE
Status menu lembaga

### ISSUE THREAD

**Issue by Irvan1609** [OpenSID/OpenSID#5394]
Menu lembaga yang disorot tidak sesuai.

![Screenshot 2022-07-17 170841](https://user-images.githubusercontent.com/74125352/179391699-4e82400b-35d8-4382-a586-708e41b81e2b.png)

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/OpenSID/pull/5317 sudah ok .
