### ISSUE TITLE
[Tema] Tampilan Web Tidak mobile-friendly

### ISSUE THREAD

**Issue by siayi** [OpenSID/OpenSID#54]
Tampilan web http://sid.bangundesa.info/ Tidak mobile-friendly , hal tersebut setelah saya melakukan pengujian menggunakan tool dari google https://www.google.com/webmasters/tools/mobile-friendly/ .
![sid-tidak mobile-friendly](https://cloud.githubusercontent.com/assets/1229849/16255947/92da2f7a-3878-11e6-94d6-1c65e3a957cf.png)

**Comment by eddieridwan** [comment]
@siayi , ini sama dengan issue #53. Diskusi mengenai cara menerapkan ini pindah ke https://groups.google.com/forum/#!topic/opensid/92bfV1CGTRU.

**Comment by metalab25** [comment]
sekarang saya sudah buat menjadi Mobile-Friendly
![2017-07-11 2](https://user-images.githubusercontent.com/19917739/28076158-548e12da-6690-11e7-9986-56e9c3ab1502.png)

**Comment by afa28** [comment]
Pak @eddieridwan, Kyaknya pak parso punya tema klasik ubahan yg sdah responsive???

**Comment by mizwaruddin** [comment]
@afa28 tema skrg sdh responsif.

**Comment by afa28** [comment]
> @afa28 tema skrg sdh responsif.

Yg klasik blum pak.

**Comment by andifahruddinakas** [comment]
Sudah diganti dengan tema esensi
