### ISSUE TITLE
[Peta] Tampilan Keterangan Gambar di Peta Bisa Urut ke Bawah 

### ISSUE THREAD

**Issue by mizwaruddin** [OpenSID/OpenSID#5402]
**Apa kekurangan yg ingin diatasi?**
 Saat ini tampilan informasi gambar hanya satu baris saja, sehingga ketika ingin menampilkan banyak informasi akan terpotong.

**Jelaskan solusi yg diinginkan**
Izinkan informasi gambar di peta ditampilkan dalam beberapa baris. Ketika di enter, maka tampil di baris baru.

![IMG20211012095357.jpg](https://user-images.githubusercontent.com/39736008/136884188-0a431c9a-8d83-4478-b84e-08d5b176c195.jpg)

**Apakah ada alternatif lain**

**Untuk versi OpenSID mana**

**Informasi tambahan**

**Comment by andifahruddinakas** [comment]
hal ini akan di sesuaikan jika halaman statis peta di pindahkan ke masing2 tema.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1138
