### ISSUE TITLE
Layanan: Hanya kenali gawai anjungan jika ada pemesanan anjungan final

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#5406]
Pada waktu menjalankan layanan mandiri, hanya kenali gawai anjungan jika ada pemesanan anjungan final. Yaitu, meskipun gawai yg bersangkutan terdaftar sebagai anjungan, status anjungan hanya aktif jika desa telah membeli anjungan dari OpenDesa. Yaitu, fitur2 khusus anjungan hanya aktif jika desa telah membeli anjungan dari OpenDesa.

Fitur ini untuk memastikan modus anjungan tidak berlaku jika desa belum membeli anjungan OpenDesa atau memperoleh anjungan dari pihak ketiga yg tidak bermitra dengan OpenDesa. Dalam hal ini, layanan mandiri akan tampilkan fitur2 layanan mandiri biasa.

**Comment by FirlianiF** [comment]
https://github.com/OpenSID/wiki-layanan-opendesa/issues/100

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/Layanan_OpenDESA/pull/102
