### ISSUE TITLE
Permintaan fitur: Tambahkan template untuk penempatan kotak Info BSRE di surat

### ISSUE THREAD

**Issue by apidong** [OpenSID/OpenSID#5407]
### Apa kekurangan yg ingin diatasi?

-

### Jelaskan solusi yg diinginkan

-

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

-

### Informasi tambahan

![image](https://user-images.githubusercontent.com/20056421/179705153-ea682538-928b-476f-8d25-3a553f9d60e8.png)
ini contoh dari aplikasi lain dan akan disesuaikan desa pasir pemilu

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1147
