### ISSUE TITLE
 Sediakan inputan pengisian passphrase yang hanya bisa dilakukan oleh kepala desa. jika pengaturan tte aktif

### ISSUE THREAD

**Issue by apidong** [OpenSID/OpenSID#5410]
- Tombol pengisian passphares keluar jika modul tte aktif
- Jika pengisian passphrase salah, munculkan notifikasi salah passphrase 
- jika modul tte tidak aktif surat langsung masuk ke arsip dan bisa dicetak oleh operator.

tambahan informasi : 
a. untuk memperoleh passphrase  dari mana?
b. buatkan dummy untuk contoh demo.

**Comment by andifahruddinakas** [comment]
Issue https://github.com/OpenSID/OpenSID/issues/4852
