### ISSUE TITLE
Buat sebuah backend yang menghubungkan opensid dengan server API TTE.

### ISSUE THREAD

**Issue by apidong** [OpenSID/OpenSID#5411]

**Comment by andifahruddinakas** [comment]
Mas @vickyrolanda, @apidong, bisa kirim contoh untuk issue ini.

**Comment by apidong** [comment]
@andifahruddinakas  sudah saya kirimkan di telegram

**Comment by andifahruddinakas** [comment]
https://www.postman.com/raflyfirdausy/workspace/local-workspace/collection/4199172-baabb146-f3fb-4294-b948-e1d7f9b284c1?ctx=documentation

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1195
