### ISSUE TITLE
Tambahkan fitur  untuk menentukan kepala desa dan Sekdes

### ISSUE THREAD

**Issue by apidong** [OpenSID/OpenSID#5412]
- Fix jabatan kepala dan sekretaris desa hanya di modul pengurus
- Cek semua bagian yang berkaitan dengan perubahan
- Hapus duplikasi pendefinisian kepala desa di identitas desa
- Fixkan urutan  : 
  1. kepala desa
  2. sekretaris desa
  3. Lainnya

**Comment by eddieridwan** [comment]
1. Ubah Info Desa > Identitas Desa > Ubah
![kades-1](https://user-images.githubusercontent.com/249563/180633220-cca45e03-cea5-475d-9196-cbcacea73c3e.jpg)
2. Ubah Info Desa > Pemerintahan Desa > Tambah
![kades-2](https://user-images.githubusercontent.com/249563/180633430-977bc3d0-3e4a-4c25-b44e-36acf52630c9.jpg)
3. Ubah Info Desa > Pemerintahan Desa
Hanya boleh ada satu Kades/Sekdes
![kades-3](https://user-images.githubusercontent.com/249563/180633665-c27f6ab9-b0a9-473b-811f-3db1da0f352a.jpg)
4. Ubah Layanan Surat > Cetak Surat
![kades-4](https://user-images.githubusercontent.com/249563/180633756-c3142a74-2c6e-4132-b29d-eab44094f37f.jpg)
5. Ubah form cetak surat
Default adalah surat ditandatangani Kades (yaitu jika tidak memilih a.n atau u.b).
Pilihan a.n selalu ada, karena tidak dapat mencetak surat jika Kades belum ditentukan. 
![kades-5](https://user-images.githubusercontent.com/249563/180633904-114d7f95-667e-4d61-a77d-6a34e7bdcf92.jpg)
![kades-6](https://user-images.githubusercontent.com/249563/180634146-e345d61e-d519-46f4-8a6a-847326bcc294.jpg)

**Comment by vickyrolanda** [comment]
> 1. Ubah Info Desa > Identitas Desa > Ubah
>    ![kades-1](https://user-images.githubusercontent.com/249563/180633220-cca45e03-cea5-475d-9196-cbcacea73c3e.jpg)
> 2. Ubah Info Desa > Pemerintahan Desa > Tambah
>    ![kades-2](https://user-images.githubusercontent.com/249563/180633430-977bc3d0-3e4a-4c25-b44e-36acf52630c9.jpg)
> 3. Ubah Info Desa > Pemerintahan Desa
>    Hanya boleh ada satu Kades/Sekdes
>    ![kades-3](https://user-images.githubusercontent.com/249563/180633665-c27f6ab9-b0a9-473b-811f-3db1da0f352a.jpg)
> 4. Ubah Layanan Surat > Cetak Surat
>    ![kades-4](https://user-images.githubusercontent.com/249563/180633756-c3142a74-2c6e-4132-b29d-eab44094f37f.jpg)
> 5. Ubah form cetak surat
>    Default adalah surat ditandatangani Kades (yaitu jika tidak memilih a.n atau u.b).
>    Pilihan a.n selalu ada, karena tidak dapat mencetak surat jika Kades belum ditentukan.
>    ![kades-5](https://user-images.githubusercontent.com/249563/180633904-114d7f95-667e-4d61-a77d-6a34e7bdcf92.jpg)
>    ![kades-6](https://user-images.githubusercontent.com/249563/180634146-e345d61e-d519-46f4-8a6a-847326bcc294.jpg)

Dicatat untuk ini pak, akan saya uji jika ada pembaruan PR sesuai ini pak.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1141
