### ISSUE TITLE
Penjelasan tambahan di impor analisis

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#5413]
Saat ini tidak jelas bahwa file untuk impor analisis harus .xlsx. 

![Image](https://user-images.githubusercontent.com/249563/179894332-f7d19e49-5a44-4311-b6ca-eab86f56c39f.png)

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1249
