### ISSUE TITLE
struktur perangkat tidak akan tampil/ tidak tersusun

### ISSUE THREAD

**Issue by sulaimanlawidhub** [OpenSID/OpenSID#5415]
Pada https://berputar.opendesa.id/pengurus jika salah satu nama ada yg menggunakan tanda petik 1 (') maka struktur perangkat tidak akan tampil/ tidak tersusun, namun seletah biodata yangbersangkutan diubah tanpa tanda petik satu maka struktur tersusun rapih.

**Comment by davidyusufbumiratu** [comment]
benar sekali, saya mengalami hal yang sama. sehingga sementara ubah biodata penduduk menghilangkan tanda petik satu agar struktur tersusun
