### ISSUE TITLE
Struktur perangkat tidak akan tampil/ tidak tersusun jika salah satu nama menggunakan tanda petik

### ISSUE THREAD

**Issue by sulaimanlawidhub** [OpenSID/OpenSID#5416]
Pada https://berputar.opendesa.id/pengurus jika salah satu nama ada yg menggunakan tanda petik 1 (') maka struktur perangkat tidak akan tampil/ tidak tersusun, namun seletah biodata yangbersangkutan diubah tanpa tanda petik satu maka struktur tersusun rapih. silahkan dicoba
![IMG_20220721_093527_532.jpg](https://user-images.githubusercontent.com/92381858/180111176-a80966f0-7e07-4daa-83c4-a59620615a72.jpg)

**Comment by agungsugiarto** [comment]
pak @sulaimanlawidhub bisa lampirkan tampilan errornya ?

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1149
