### ISSUE TITLE
Bug/error: Tidak bisa hapus data hasil input stunting

### ISSUE THREAD

**Issue by muhtar-coder** [OpenSID/OpenSID#5418]
### Jelaskan error yg dialami

ketika mau hapus data inputan di isian stunting, data tersebut tidak bisa di hapus

### Cara untuk mereplikasi errornya

di menu kesehatan > stunting > data hasil inputan  coba klik hapus di semua menu dan hasilnya tidak bisa di hapus

### Hasil yg diharapkan

bisa di hapus seperti biasa, kebetulan proses ini hanya uji coba saja dan belum input data sebenarnya

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/55665526/180365567-c8fababc-941a-4267-8f50-5891dd537a28.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.07-premium-rev02

### Tema Yang Digunakan

Denatra

### Informasi tambahan

1. di harapkan di sediakan template eksport seperti yg sudah ada di aplikasi stunting sebelumnya
2. diharapkan template ekspor convergensi nya di sediakan seperti format yg seharusnya

**Comment by Zoel-WB** [comment]
Semua Fitur Untuk Perintah Hapus pada Fitur Pemantauan Bulanan-->Belum Berfungsi, atau klik hapus muncul pesan Gagal

 
![image](https://user-images.githubusercontent.com/64481641/180602179-3ef59a18-42d8-47b2-ad8c-0ed2ceab88c3.png)

![image](https://user-images.githubusercontent.com/64481641/180602184-dd0a0bad-2d15-4e75-b526-94c57dd77f17.png)

**Comment by yogiperdana** [comment]
Issue ini juga sekalian memperbaiki gagal filter dan edit pada semua menu stunting

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1167
