### ISSUE TITLE
Bug/error: Hasil expor DB tidak bisa di impor kembali krn adanya tgl 0000-000-000 00:00:00

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#5419]
### Jelaskan error yg dialami

Terjadi gagal impor dari backup database karena tgl terdapat  tgl 0000-000-000 00:00:00

### Cara untuk mereplikasi errornya

1. gunakan db pengguna lama
2. lakukan impor
3. akan terjadi error

### Hasil yg diharapkan

impor berhasil

### Perbaikan manual
saat ini untuk memperbaiki agar bisa impor database tsb dengan menggati tgl 0000-00-00 00:00:00 menjadi tgl yg sesuai misalnya 1970-01-01 01:01:01.

### Tangkapan layar dan log error

.

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.07-premium

### Tema Yang Digunakan

bawaan

### Informasi tambahan

**Comment by andifahruddinakas** [comment]
Sebelum impor, jalankan terlebih dahulu : 
`SET SQL_MODE='ALLOW_INVALID_DATES';`

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1163
