### ISSUE TITLE
Bug/error: Tampilan Tombol Gambar Melebihi Kotak

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#5420]
### Jelaskan error yg dialami

<img width="551" alt="image" src="https://user-images.githubusercontent.com/46939846/180589890-4d7212f4-94f1-4f4b-b3af-0589767b13e3.png">

### Cara untuk mereplikasi errornya

Edit salah satu penduduk.

### Hasil yg diharapkan

Proporsional

### Tangkapan layar dan log error

Seperti di atas

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Berputar

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1158
