### ISSUE TITLE
Bug/error: Laporan jumlah awal bulan tidak sesuai denga akhir bulan sebelumnya

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#5421]
### Jelaskan error yg dialami

Terjadi kesalahan perhitungan data awal bulan. Harusnya data akhir juni menjadi data awal pada bulan juli.

### Cara untuk mereplikasi errornya

Gunakan database yang bermasalah untuk mereplikasinya.

### Hasil yg diharapkan

Laporan sesuai

### Tangkapan layar dan log error

Laporan Juni
![juni](https://user-images.githubusercontent.com/57283157/180596104-ad20b9ce-2a89-402e-8304-fc776a130ee1.png)

Laporan Juli
![juli](https://user-images.githubusercontent.com/57283157/180596188-f7d829a8-5db1-406f-9291-e0d3e47d5462.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.07-premium-rev03

### Tema Yang Digunakan

bawaan

### Informasi tambahan
Penyebab error tidak diketahui.

**Comment by andifahruddinakas** [comment]
Catatan : 
1. peristiwa 1 (kk baru) atau 2 (kk meninggal) pada log penduduk hanya boleh 1 saja.
2. bisa cek dengan melakukan ubah satus dasar dari kepala keluarga tsb dari hidup jadi meninggal (lakukan berulang kali sambil cek laporan bulanan)

**Comment by vickyrolanda** [comment]
Check : 
1. Input data penduduk bulan ini 1 anam dan input data KK dengan kepala rumah tangga 1 
Hasilnya telah benar  : 
laporan July : 
<img width="752" alt="image" src="https://user-images.githubusercontent.com/59082428/181770475-2e257b0c-c8dc-4ca6-ab65-6ae72882fa72.png">
2. saya coba test input 1 anak , 1 istri dan 1 kepala rumah tangga dan 1 KK 
<img width="760" alt="image" src="https://user-images.githubusercontent.com/59082428/181771543-62565c3e-1771-4907-97c0-bce9d02c46eb.png">
data akhir berarti : 
- Total penduduk yang di tambah bulan july adalah 5 , karena dari point 1 & 2 
- Total kk menjadi 2 dari inputan point 1 & 2 seperti hasil di bawah ini : 
<img width="760" alt="image" src="https://user-images.githubusercontent.com/59082428/181772477-9b2ea7be-81f4-42d5-b42f-798f02172626.png">

Laporan july saat ini telah benar: 
<img width="755" alt="image" src="https://user-images.githubusercontent.com/59082428/181773831-df3ea9a3-5a7e-4759-821c-b923619b9c58.png">

sekarang saya coba lihat laporan awal bulan 8 : 
<img width="751" alt="image" src="https://user-images.githubusercontent.com/59082428/181774851-56185706-87ab-488c-838c-9a4711e78962.png">

3. Saya coba hapus data 1 keluarga yand di tambah di bulan july
<img width="755" alt="image" src="https://user-images.githubusercontent.com/59082428/181775595-da162eec-7720-4ac5-b75a-822fd12cbec9.png">
maka laporan bulan 8 seperti berikut ini 
<img width="752" alt="image" src="https://user-images.githubusercontent.com/59082428/181775864-99844c52-b0ea-47bc-b708-2f408b1a3bd5.png">

dari uji coba di atas maka telah benar di lakukan di laporan;

Kesimpulannya : bahwa data yang masuk dan keluar / di hapus dibulan ini akan di kalkulasi jika data tidak sama mungkin data di bulan july di hapus .

Kasus lain bisa jadi 1 penduduk di ganti jenis kelaminnya maka laporan akan pindah dari KK Perempuan menjadi KK Laki - Laki seperti kasus di bawah ini : 
<img width="594" alt="image" src="https://user-images.githubusercontent.com/59082428/181777986-91f0efb8-2fd2-4414-88a6-22f0cb08b227.png">
dan kenapa berbeda dengan laporan july karena yang penduduk perempuan pindah ke laki - laki 
<img width="635" alt="image" src="https://user-images.githubusercontent.com/59082428/181778270-f1aa977c-73b7-4e15-86e3-701b8d6448b9.png">


Maka yang menjadi pertanyaan apakah ini masih bug atau tidak, namun dari uji coba yang saya lakukan ini bukanlah sebuah bug mungkin dari sudut pandang bung @andifahruddinakas  bisa kasih saya masukkan jika saya ada kelewatan step dalam uji issue ini.

**Comment by andifahruddinakas** [comment]
> Check : 
> 1. Input data penduduk bulan ini 1 anam dan input data KK dengan kepala rumah tangga 1 
> Hasilnya telah benar  : 
> laporan July : 
> <img width="752" alt="image" src="https://user-images.githubusercontent.com/59082428/181770475-2e257b0c-c8dc-4ca6-ab65-6ae72882fa72.png">
> 2. saya coba test input 1 anak , 1 istri dan 1 kepala rumah tangga dan 1 KK 
> <img width="760" alt="image" src="https://user-images.githubusercontent.com/59082428/181771543-62565c3e-1771-4907-97c0-bce9d02c46eb.png">
> data akhir berarti : 
> - Total penduduk yang di tambah bulan july adalah 5 , karena dari point 1 & 2 
> - Total kk menjadi 2 dari inputan point 1 & 2 seperti hasil di bawah ini : 
> <img width="760" alt="image" src="https://user-images.githubusercontent.com/59082428/181772477-9b2ea7be-81f4-42d5-b42f-798f02172626.png">
> 
> Laporan july saat ini telah benar: 
> <img width="755" alt="image" src="https://user-images.githubusercontent.com/59082428/181773831-df3ea9a3-5a7e-4759-821c-b923619b9c58.png">
> 
> sekarang saya coba lihat laporan awal bulan 8 : 
> <img width="751" alt="image" src="https://user-images.githubusercontent.com/59082428/181774851-56185706-87ab-488c-838c-9a4711e78962.png">
> 
> 3. Saya coba hapus data 1 keluarga yand di tambah di bulan july
> <img width="755" alt="image" src="https://user-images.githubusercontent.com/59082428/181775595-da162eec-7720-4ac5-b75a-822fd12cbec9.png">
> maka laporan bulan 8 seperti berikut ini 
> <img width="752" alt="image" src="https://user-images.githubusercontent.com/59082428/181775864-99844c52-b0ea-47bc-b708-2f408b1a3bd5.png">
> 
> dari uji coba di atas maka telah benar di lakukan di laporan;
> 
> Kesimpulannya : bahwa data yang masuk dan keluar / di hapus dibulan ini akan di kalkulasi jika data tidak sama mungkin data di bulan july di hapus .
> 
> Kasus lain bisa jadi 1 penduduk di ganti jenis kelaminnya maka laporan akan pindah dari KK Perempuan menjadi KK Laki - Laki seperti kasus di bawah ini : 
> <img width="594" alt="image" src="https://user-images.githubusercontent.com/59082428/181777986-91f0efb8-2fd2-4414-88a6-22f0cb08b227.png">
> dan kenapa berbeda dengan laporan july karena yang penduduk perempuan pindah ke laki - laki 
> <img width="635" alt="image" src="https://user-images.githubusercontent.com/59082428/181778270-f1aa977c-73b7-4e15-86e3-701b8d6448b9.png">
> 
> 
> Maka yang menjadi pertanyaan apakah ini masih bug atau tidak, namun dari uji coba yang saya lakukan ini bukanlah sebuah bug mungkin dari sudut pandang bung @andifahruddinakas  bisa kasih saya masukkan jika saya ada kelewatan step dalam uji issue ini.
> 
> 
> 
> 
> 
> 

Masalahnya ada di log_keluarga, terjadi duplikasi peristiwa meninggal (2) pada 1 kk yg sama dibulan yg berbeda. Disebabkan krn fungsi menghidupkan kembali penduduk yg sudah meninggal. Sementara perbaikan hanya  memperbaiki log_keluarga saja.

Untuk kasus kk baru (1) dan kk meninggal (2) hanya boleh 1 dalam 1 kk.

**Comment by andifahruddinakas** [comment]
PR issue ini memperbaiki log_keluarga, jd mungkin testnya di fokuskan ke keluarga saja. Issue ini berkaitan keluarga awal dan akhir, jd bisa di cek query untuk menghitung ke 2 bagian itu. Yang salah hanya pada bagian perhitungannya saja, tapi bagian detail saat diklik sudah sesuai.

Proses yg perlu di cek ada dibagian jika Kepala KK dimatikan kemudian dihidupkan kembali.

Untuk kasus penduduk datang ada di issue terpisah mengenai log penduduk.

**Comment by vickyrolanda** [comment]
> log_keluarga

Baik mas.

**Comment by vickyrolanda** [comment]
> > log_keluarga
> 
> Baik mas.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1169
