### ISSUE TITLE
Permintaan fitur: Tambahkan Logo dan Pilihan Kustom Jabatan Serta No dan Tgl SK Pendirian Lembaga

### ISSUE THREAD

**Issue by PWidodo** [OpenSID/OpenSID#5422]
### Apa kekurangan yg ingin diatasi?

Fitur ini pada menu Info Desa>Lembaga untuk diadakan perubahan Perubahan serta Penambahan sbb:

1. Tambahkan kolom isian Logo Lembaga dan Nomor SK dan Tanggal Pendirian Lembaga pada Form Master Lembaga
![tambah logo lembaga](https://user-images.githubusercontent.com/45189822/180658265-f0acf37c-a8e9-4b18-8591-ad0c3c82762a.png)

2. Tambahkan Pilihan Jabatan Kustom (diketik manual) pada Data Anggota Lembaga. Hal ini penting manakala kita membuat Data Lembaga RT dan RW, karena semuanya adalah Ketua tidak ada Wakil Ketua, Sekretaris atau Bendahara.
![tambah jabatan kustom](https://user-images.githubusercontent.com/45189822/180658424-f5182023-0fe8-48bd-acc4-e392e1f98fbc.png)

### Jelaskan solusi yg diinginkan

1. Setiap lembaga desa seperti RT/RW, PKK, Linmas Hansip, Karang Taruna, BPD dsb.. semuanya memiliki logo masing-masing dan dengan Nomor dan Tanggal SK Pendirian masing-masing pula. Oleh karenanya kami harapkan waga dapat melihat data lembaga di website desa melalui Menu Lembaga (menu Statis) sebagaimana contoh gambar dibawah ini :
![tampilan pada halaman menu statis web](https://user-images.githubusercontent.com/45189822/180658538-4ff0185b-502a-4a8d-8188-b18bfe3e22d8.png)

2. Selanjutnya untuk printouts data lembaga oleh admin (sistem) juga dapat disesuaikan dengan contoh gambar dibawah ini:
![print out daftar anggota lembaga](https://user-images.githubusercontent.com/45189822/180658581-be32aebc-086c-4e82-9df1-3832812fd3b0.png)

3. Lengkapi Juga dengan Bagan Struktur Organisasi Lembaganya, selanjutnya Struktur lembaga ini ditampilkan pada website (menu statis) di atas Data Anggota 

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

Premium 22.08

### Informasi tambahan

-

**Comment by yugaeko** [comment]
sepakat, harapannya juga teks yang ditampilkan di halaman lembaga lebih banyak. karena untuk yang versi saat ini terbatas, semacam seperti summary saja.. jika bisa dilengkapi dengan visi misi, tupoksi dll, mestinya akan lebih baik lagi

![image](https://github.com/OpenSID/OpenSID/assets/9125101/eb59eb4f-91c2-4363-af59-cbf0bb3ca926)

Begitu juga dengan perangkat desanya, jika masing-masing perangkat bisa di klik kemudian muncul data detailnya yang berisi identitas dan tupoksi masing-masing jabatan kami kira akan menjadi informasi yang sangat baik.

![image](https://github.com/OpenSID/OpenSID/assets/9125101/0c119f18-a1b9-4f44-9e63-68c6b9da463c)

**Comment by andifahruddinakas** [comment]
> sepakat, harapannya juga teks yang ditampilkan di halaman lembaga lebih banyak. karena untuk yang versi saat ini terbatas, semacam seperti summary saja.. jika bisa dilengkapi dengan visi misi, tupoksi dll, mestinya akan lebih baik lagi
> 
> ![image](https://private-user-images.githubusercontent.com/9125101/316290451-eb59eb4f-91c2-4363-af59-cbf0bb3ca926.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2MzI4ODcsIm5iZiI6MTcyMTYzMjU4NywicGF0aCI6Ii85MTI1MTAxLzMxNjI5MDQ1MS1lYjU5ZWI0Zi05MWMyLTQzNjMtYWY1OS1jYmYwYmIzY2E5MjYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjJUMDcxNjI3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzRhM2I0OWM4ZGI1YzQ5YWNjNWE2ZGJhYzlmYzU3ZGFiNzQ4NmNmN2Y1NTI2YzkwYmQ1OTM4ZTZmYzFjZTgzMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.4ARNxgFnUTYJrHqg4aUSnimkAnyHhduxkQL0hue61Ek)
> 
> Begitu juga dengan perangkat desanya, jika masing-masing perangkat bisa di klik kemudian muncul data detailnya yang berisi identitas dan tupoksi masing-masing jabatan kami kira akan menjadi informasi yang sangat baik.
> 
> ![image](https://private-user-images.githubusercontent.com/9125101/316290511-0c119f18-a1b9-4f44-9e63-68c6b9da463c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2MzI4ODcsIm5iZiI6MTcyMTYzMjU4NywicGF0aCI6Ii85MTI1MTAxLzMxNjI5MDUxMS0wYzExOWYxOC1hMWI5LTRmNDQtOWU2My02OGM2YjlkYTQ2M2MucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjJUMDcxNjI3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTJjNmQzM2MxOGNiMTRmNGQ0ZGM1MzNjYmY4YTczZjEzMmNmNDBkYjNmNDRhNzBhZTNmNDM1NzNjNDZlOTlhOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.UwNUxnugag4csVQPr0R_9ewSQ5paRqRQdagZV141pl8)

Bisa dibuat issue terpisah mas @yugaeko
