### ISSUE TITLE
Di Laporan Penduduk Bulanan bedakan keluarga datang dengan keluarga baru lainnya

### ISSUE THREAD

**Issue by afri18** [OpenSID/OpenSID#5424]
### Jelaskan error yg dialami

Kartu Keluarga Pendatang/Datang tidak terdeteksi, dalam laporan bulanan padahal ada
Kalau di perhatikan masuknya ke keluarga baru/lahir

### Cara untuk mereplikasi errornya

harusnya Keluarga datang di hitung di Pendatang/Datang

### Hasil yg diharapkan

Seharusnya kalau Keluarga Pendatang/Datang dengan Nomor KK masih daerah asal di hitung Keluarga Pendatang/Datang

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/6611881/180713017-e9caf37d-f2b9-4ff3-a95b-bc3f4c21b63a.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

22.07 rev2

### Tema Yang Digunakan

denatra v6.1

### Informasi tambahan

semua keluarga yg baru/lahir dengan Pendatang/Datang jadi satu

**Comment by agungsugiarto** [comment]
pak @afri18 bisa kirim backup databasenya ke telegram saya

**Comment by balongbesuk** [comment]
![image](https://user-images.githubusercontent.com/35319600/180828601-7e09ed8c-02f3-4f2e-a30d-94fd2c8f1a79.png)

sy kroscek bulan ini dan bulan bulan sebelumnya ternyata juga sama Penduduk datang dengan status Kepala Keluarga tidak terisi,

masuk ke menu keluarga > tambah penduduk masuk > isi dengan status kepala keluarga, dll > isi > simpan > lihat statistik laporan bulanan

**Comment by agungsugiarto** [comment]
Sudah saya coba tidak ada masalah pak?

![Image](https://user-images.githubusercontent.com/10989147/181924652-23716941-0583-467a-8b64-8945eafcccad.png)

**Comment by balongbesuk** [comment]
pendatang dg status kepala keluarga

**Comment by balongbesuk** [comment]
![182051653-930dd6f3-5f0b-449f-90e8-57c00f69927e](https://user-images.githubusercontent.com/35319600/182277181-063128dd-ee76-4a35-ad3e-e629d79f96d9.jpg)

Tambahkan pendatang Kepala Keluarga pada menu keluarga > simpan > lihat hasil pada statistik laporan bulanan (masuk dalam kolom kelahiran/keluarga baru harusnya masuk k kolom pendatang)

**Comment by afri18** [comment]
@balongbesuk itu yang saya maksud .......

**Comment by afri18** [comment]
> Sudah saya coba tidak ada masalah pak?
> 
> ![Image](https://user-images.githubusercontent.com/10989147/181924652-23716941-0583-467a-8b64-8945eafcccad.png)

@agungsugiarto masalhnya keluarga datang tidak terisi, yang antum merahin penduduk datang, yg bug keluarga (Kepala Keluarga) datang

**Comment by andifahruddinakas** [comment]
Pak @eddieridwan, pada log_keluarga, id_peristiwa tidak ada jenis peristiwa tsb. Peristiwa datang hanya ada pada log_penduduk saja.

```
/* 	Untuk statistik perkembangan keluarga
            id_peristiwa:
                 1 - keluarga baru
                 2 - kepala keluarga status dasar 'mati'
                 3 - kepala keluarga status dasar 'pindah'
                 4 - kepala keluarga status dasar 'hilang'
                 6 - kepala keluarga status dasar 'pergi' (seharusnya tidak ada)
                 11- kepala keluarga status dasar 'tidak valid' (seharusnya tidak ada)
                 12- anggota keluarga keluar atau pecah dari keluarga
                 13 - keluarga dihapus
                 14 - kepala keluarga status dasar kembali 'hidup' (salah mengisi di log_penduduk)
    */
```

**Comment by eddieridwan** [comment]
@andifahruddinakas betul belum ada. Karena itu issuenya perlu dibuat sebagai fitur, bukan bug. Yaitu untuk membedakan keluarga datang dengan keluarga baru karena pecah KK atau lainnya. Sepertinya saya sudah jelaskan ini pada issue yg lain?

Saya jelaskan di sini: https://t.me/c/1180597796/4224 

Seharusnya bung @vickyrolanda langsung menindaklanjuti komentar di Telegram itu.

**Comment by andifahruddinakas** [comment]
> @andifahruddinakas betul belum ada. Karena itu issuenya perlu dibuat sebagai fitur, bukan bug. Yaitu untuk membedakan keluarga datang dengan keluarga baru karena pecah KK atau lainnya. Sepertinya saya sudah jelaskan ini pada issue yg lain?

ok

**Comment by andifahruddinakas** [comment]
Perubahan diterapkan untuk laporan yang akan datang saja, untuk lama tidak terpengaruh.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1248
