### ISSUE TITLE
Bug/error: data desa tidak terupdate di menu identitas desa

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#5425]
### Jelaskan error yg dialami

Saat update data desa, desa tidak berubah

### Cara untuk mereplikasi errornya

- Info Desa
- Identitas Desa
- Klik ubah data Desa
- Pilih Desa
- Klik tombol Simpan
- Desa yang dipilih tidak ter update

### Hasil yg diharapkan

Sesuai desa yg di pilih

### Tangkapan layar dan log error

<img width="886" alt="Screen Shot 2022-07-25 at 23 41 01" src="https://user-images.githubusercontent.com/36557759/180831058-6079c2e9-ef4f-4c99-82a5-bf74428bceb8.png">
<img width="886" alt="Screen Shot 2022-07-25 at 23 44 18" src="https://user-images.githubusercontent.com/36557759/180831071-8e061752-f6e9-4b06-bf69-b35a717bf7a8.png">

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

22.08

**Comment by agungsugiarto** [comment]
Mas @devrakapriyo saya tidak menemukan masalah yg dimaksud?
