### ISSUE TITLE
Bug/error: Tidak bisa menghapus Surat di Pengaturan Surat

### ISSUE THREAD

**Issue by pemdeslinggapura** [OpenSID/OpenSID#5426]
### Jelaskan error yg dialami

Tidak bisa menghapus surat yang dibuat di menu Tambah Surat pada versi Premium

### Cara untuk mereplikasi errornya

![image](https://user-images.githubusercontent.com/89450861/180934984-7e8a79bf-dc07-40cd-ae09-8f4a301672b7.png)

### Hasil yg diharapkan

bisa menghapus Surat Desa

### Tangkapan layar dan log error

Gagal menghapus

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

22.07 Premium

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1166
