### ISSUE TITLE
Logo tidak tampil saat website di setting dalam offline mode

### ISSUE THREAD

**Issue by mranca** [OpenSID/OpenSID#5427]
### Jelaskan error yg dialami

Logo, alamat, telepon tidak muncul saat offline mode meskipun datanya sudah ada dalam admin

### Cara untuk mereplikasi errornya

Admin>pengaturan>aplikasi>offline mode

### Hasil yg diharapkan

Logo, alamat telepon agar bisa tampil sesui yang ada di dalam database 

### Tangkapan layar dan log error

![Screenshot_20220727_003228](https://user-images.githubusercontent.com/76085245/181063158-027bddf4-9470-4f55-b2bb-746bf9285e15.jpg)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

22.07.rev02

### Tema Yang Digunakan

Batua

### Informasi tambahan

-

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1164
