### ISSUE TITLE
Bug/error: Belum tersedia untuk menampilkan Feed CATEGORY

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#5431]
### Jelaskan error yg dialami

Ketika pada file:
donjo-app/libraries/Feed_Reader.php

baris link diubah ke opensid.my.id/feed maka bisa tampil kategori di halaman opensid.

namun ketika diubah ke link web yg menggunakan opensid misal natairaya.desa.id/feed

maka info kategori tidak muncul di halaman web.

### Cara untuk mereplikasi errornya

seperti di atas

### Hasil yg diharapkan

normal

### Tangkapan layar dan log error

Berikut menggunakan feed dari web opensid:

<img width="684" alt="image" src="https://user-images.githubusercontent.com/46939846/181164093-8fe56112-7245-4bee-b051-6024704737fa.png">

Berikut menggunakan feed dari web worpress yg digunakan oleh OpenSID.MY.ID

<img width="706" alt="image" src="https://user-images.githubusercontent.com/46939846/181164140-16518d9c-0e5a-4f39-8f55-f5125c3db8ef.png">

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Semua

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1165
