### ISSUE TITLE
Bug/error: Saat Melakukan MigrasiDB Pada OpenSID Rev03

### ISSUE THREAD

**Issue by Pematung** [OpenSID/OpenSID#5432]
### Jelaskan error yg dialami

Saat hendak melakukan MigrasiDB pada OpenSID Versi 22.07 premium-rev03 terjadi data gagal disimpan hal ini terjadi baik pada install baru opensid maupun yg sudah menggunakan lama

![image](https://user-images.githubusercontent.com/105429258/181398092-0a2a8107-b438-4039-a4d5-528107a1e8fd.png)

### Cara untuk mereplikasi errornya

1. Pengaturan
2. Database
3. MigrasiDB

### Hasil yg diharapkan

Hasil yag diharapkan normal seperti biasa dengan notifikasi data berhasil disimpan seperti pada versi 22.07 premium rev02

![image](https://user-images.githubusercontent.com/105429258/181398347-932f94d0-eba9-4675-8317-dcf475762c20.png)

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/105429258/181398817-5c7b2d44-fd22-4155-8d29-b5e622b8a738.png)

![image](https://user-images.githubusercontent.com/105429258/181398377-d47211b0-e12d-4ec4-ad22-702b261a321b.png)

![image](https://user-images.githubusercontent.com/105429258/181398468-397e9d16-d857-4350-9d7b-472edbc49444.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

22.07 Premium Rev03

### Tema Yang Digunakan

Batuah & Denatra 6.2

### Informasi tambahan

-

**Comment by dgyoganantha** [comment]
Up

**Comment by PWidodo** [comment]
Saya coba di https://berputar.opendesa.id/hom_sid juga error

**Comment by Pematung** [comment]
> Saya coba di https://berputar.opendesa.id/hom_sid juga error

Coba lihat screenshot yg paling atas dan perhatikan alamatnya

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1168
