### ISSUE TITLE
[Stunting] Pilihan Edit/Ubah Data Pemantauan Bulanan Ibu Hamil Mengarah Ke Fitur Tambah Data 

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#5446]
### Jelaskan error yg dialami

Saat memilih edit salah satu data pada fitur Pemantauan Bulanan Ibu Hamil, system tidak masuk ke form untuk edit/ubah data yg dimaksud, akan tetapi mengarah ke form imput/tambah data....

### Cara untuk mereplikasi errornya

Buka Fitur Stunting
Pada Fitur Pemantauan --.Pilih Bulananan Ibu Hamil
Klik Tombol Ubah Data

### Hasil yg diharapkan

Agar system mengarah/memanggil form data untuk di ubah...

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/64481641/181820788-352bde26-4bc0-4b19-b983-e5fad639c25d.png)

![image](https://user-images.githubusercontent.com/64481641/181821177-931894d5-77cd-4758-9838-64373e0cd759.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Rilis Premium V22.08 Beta-03

### Tema Yang Digunakan

default

### Informasi tambahan

.

**Comment by yogiperdana** [comment]
Saya coba tidak ada masalah pak @Zoel-WB

**Comment by Zoel-WB** [comment]
> Saya coba tidak ada masalah pak @Zoel-WB 

Baik pak...

**Comment by yogiperdana** [comment]
Issue ini ditutup karena bug tidak dapat direplikasi
