### ISSUE TITLE
[Stunting] Saat Memilih Edit/Ubah Data Sasaran Paud Anak 2-6 Tahun System Masih Mengarah Halaman Error 

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#5447]
### Jelaskan error yg dialami

Saat Memilih Edit/Ubah Data Sasaran Paud Anak 2-6 Tahun System Masih Mengarah Halaman Error 

### Cara untuk mereplikasi errornya

Pilih Fitur Kesehatan -> Stunting
Pada Fitur Pemantauan --> Data Sasaran Paud Anak 2-6 Tahun
Klik Tombol Ubah Data 

### Hasil yg diharapkan

Supaya tidak terjadi error saat memilih ubah data

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/64481641/181822300-869a37c6-adb6-493f-a5f5-7ea7d6fa6042.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Rilis Premium V22.08 Beta-03

### Tema Yang Digunakan

default

### Informasi tambahan

.

**Comment by yogiperdana** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/1167
