### ISSUE TITLE
penambahan fitur : mematikan proses backup inkremental.

### ISSUE THREAD

**Issue by apidong** [OpenSID/OpenSID#5448]
saat ini backup menggunakan inckremental exec untuk menjalankan background job, maka mungkin juga bisa menggunakan exec untuk mematikan proses yg berjalan. ID proses bisa disimpan di log yg kemudian bisa diakses oleh script

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1253
