### ISSUE TITLE
Permintaan fitur: Alamat Lengkap (RT/RW) di Laporan Penerima Vaksin

### ISSUE THREAD

**Issue by khpurnawan** [OpenSID/OpenSID#5451]
### Apa kekurangan yg ingin diatasi?

Pada saat ini di **_"Laporan Penduduk - Pendataan Penerima Vaksin Covid-19"_** belum ada alamat RT dan RW, hanya ada alamat dusun.

Mohon kiranya bisa alamat penduduk penerima vaksin covid-19 itu bisa lengkap (tercantum RT & RW) agar kami bisa lebih maksimal dalam menggunakan data Pendataan Penerima Vaksin Covid-19 yang di CETAK atau di UNDUH dari SID.   

### Jelaskan solusi yg diinginkan

Alamat Penduduk Penerima Vaksin Covid bisa ditambah RT dan RW nya sekalian. 
Kami berharap Kolom Laporan Vaksin bisa seperti yang ada di gambar di bawah ini.

![123456789](https://user-images.githubusercontent.com/98139011/182078407-fac5fd4d-5757-4938-b830-1c5e1a60fc34.jpg)

### Apakah ada alternatif lain

Tidak ada

### Untuk versi OpenSID mana

22.07-premium-rev03

**Comment by andifahruddinakas** [comment]
Tidak dikembangkan lg.
