### ISSUE TITLE
Bug/error: Tampil tag [""] pada halaman periksa

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#5452]
### Jelaskan error yg dialami

di masing-masing url domaindesa.com/periksan munculnya [""] di sebutan nama desa, kabupaten dan title pada tab browser

### Cara untuk mereplikasi errornya

1. pergi ke halaman domaindesa.com/periksa
2. muncul error seperti gambar di bawah
<img width="1440" alt="Screen Shot 2022-08-02 at 11 32 33" src="https://user-images.githubusercontent.com/36557759/182292517-72230f5a-c0b3-41ea-8498-d55e705ba667.png">

### Hasil yg diharapkan

nama sebutan desa, kabupaten dan title tab tidak ada karakter [" "]

### Tangkapan layar dan log error

<img width="1440" alt="Screen Shot 2022-08-02 at 11 32 33" src="https://user-images.githubusercontent.com/36557759/182292517-72230f5a-c0b3-41ea-8498-d55e705ba667.png">

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

22.08

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1181
