### ISSUE TITLE
MENAMPILKAN QR CODE DENGAN KODE SISIPAN PADA SURAT FORMAT LAMA RTF 

### ISSUE THREAD

**Issue by pemdeslinggapura** [OpenSID/OpenSID#5453]
### Apa kekurangan yg ingin diatasi?

Sejujurnya opensid yang digunakan di Desa saya sudah sangat cukup dengan Format Surat yang berbentuk RTF dengan kode2 sisipan, karena dirasa lebih fleksibel walaupun memang harus bisa sedikit koding. Olehkarena tidak ada salahnya kalau kode sisipan QR Code juga bisa digunakan pada format surat RTF

### Jelaskan solusi yg diinginkan

Menampilkan QR Code Pada Format Surat RTF Lama dengan kode sisipan agar otomatis QR Code tampil

### Apakah ada alternatif lain

Baru bisa menempelkan QR Code dari Arsip Layanan, itupun harus di aktifkan QR Code pada Mysqlnya dulu pada format2 surat yang dipakai.

### Untuk versi OpenSID mana

22.08-premium

**Comment by eddieridwan** [comment]
@pemdeslinggapura surat dengan format RTF tidak akan dikembangkan lebih lanjut. Nanti setelah surat dengan format HTML telah dilengkapi dengan fitur2 yg saat ini hanya ada di surat RTF, format RTF akan dihilangkan, karena sudah bisa digantikan dengan surat HTML.

**Comment by pemdeslinggapura** [comment]
Oh iya pak, kalau begitu semoga bisa lebih di tingkatkan lg untuk yg PDF, soalnya masih sulit di editornya, untuk penyesuaian spasi, line height, dan kadang di pengaturan tidak sesuai dengan kenyataan pas Print pdf

**Comment by eddieridwan** [comment]
@pemdeslinggapura , silakan buat issue terpisah untuk setiap permasalahan yg ditemukan.
