### ISSUE TITLE
Bug/error: SURAT PDF TIDAK TAMPIL

### ISSUE THREAD

**Issue by pemdeslinggapura** [OpenSID/OpenSID#5456]
### Jelaskan error yg dialami

Pas klik menu Cetak PDF tidak tampil Surat PDF nya, malah loading terus
![image](https://user-images.githubusercontent.com/89450861/182504394-0521ca98-01c1-40f4-8bb2-0a54731387e9.png)

### Cara untuk mereplikasi errornya

1. Cetak PDF

### Hasil yg diharapkan

Surat PDF yang sudah dibuat dapat ditampilkan

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/89450861/182504496-8ef64152-216b-4771-a393-940a9fe89d0c.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

22.08-premium

**Comment by apidong** [comment]
mas @andifahruddinakas dulu pernah ngalami ini, saya coba pakai format surat sederhana tidak masalah. tapi ketika memakai format yang ada di template, jalannya lama.

**Comment by apidong** [comment]
https://github.com/spipu/html2pdf/issues/230

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1201
