### ISSUE TITLE
Bug/error: Tampilkan pesan jika tidak ada respon dari pantau

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#5457]
### Jelaskan error yg dialami

Daftar desa tidak tampil di Info Desa > Identitas Desa > Ubah setelah install/seeder. 

### Cara untuk mereplikasi errornya

1. Buat database baru
2. Install OpenSID
3. Buka Info Desa > Identitas Desa
4. Ubah
5. Klik untuk memilih Nama Desa
6. Perhatikan hasilnya 'No results found'

### Hasil yg diharapkan

1. Daftar desa tampil. 

Dan sekalian:
1. Pesan error diubah menjadi dalam bahasa Indonesia 'Tidak ada data`

### Tangkapan layar dan log error

![install-1](https://user-images.githubusercontent.com/249563/182533671-63819dbf-0b95-4d8f-84e8-c9d55d875085.jpg)
![install-2](https://user-images.githubusercontent.com/249563/182533691-6c53735b-f8b7-4e3b-972d-5062feef0a2a.jpg)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.08-premium

### Informasi tambahan

Menggunakan devlayanan.opendesa.id. Hasilnya sama menggunakan layanan.opendesa.id

**Comment by andifahruddinakas** [comment]
Untuk error log : 
```
ERROR - 2022-08-03 13:21:25 --> GuzzleHttp\Exception\ClientException: Client error: `POST http://devlayanan.opendesa.id/api/v1/pelanggan/daftarhitam` resulted in a `400 Bad Request` response:
{
    "status": 400,
    "error": 400,
    "messages": {
        "kode_desa": "Bidang kode_desa diperlukan."
    }
}
```

karena di $config['token_layanan'] sudah terisi tapi kode desanya tidak terisi.

**Comment by andifahruddinakas** [comment]
Untuk gagal muat data desa, bisa cek di console network.

![image](https://user-images.githubusercontent.com/57283157/182538510-5e83f431-640c-487d-8b09-0223935aa8ce.png)

**Comment by vickyrolanda** [comment]
> Untuk error log :
> 
> ```
> ERROR - 2022-08-03 13:21:25 --> GuzzleHttp\Exception\ClientException: Client error: `POST http://devlayanan.opendesa.id/api/v1/pelanggan/daftarhitam` resulted in a `400 Bad Request` response:
> {
>     "status": 400,
>     "error": 400,
>     "messages": {
>         "kode_desa": "Bidang kode_desa diperlukan."
>     }
> }
> ```
> 
> karena di $config['token_layanan'] sudah terisi tapi kode desanya tidak terisi.

untuk log ini sudah di gabungkan di pr https://github.com/OpenSID/premium/pull/1182

Namun untuk list daftar desa saya coba install 2 kali di local dan hasilnya muncul untuk nama -nama desanya pak @eddieridwan , 

<img width="547" alt="image" src="https://user-images.githubusercontent.com/59082428/182545218-748c3caf-2951-4b62-8236-23e7dbc3edd2.png">

mas @devrakapriyo bisa bantu testing juga untuk bagian ini mas.

**Comment by eddieridwan** [comment]
@vickyrolanda @andifahruddinakas : Ternyata karena setting
```
  $config['server_pantau'] = 'https://devtracker.opensid.my.id';
```

Berhasil kalau menggunakan 
```
$config['server_pantau'] = 'https://pantau.opensid.my.id';
```

Coba periksa apakah token_pantau berbeda untuk devtracker atau apakah devtracker sudah dimuat rilis terbaru. Yang jelas tidak ada notifikasi sebab errornya. Error di log terkait pemanggilan layanan, tidak terkait pemanggilan tracker. Sebaiknya ada notifikasi error.

**Comment by andifahruddinakas** [comment]
> @vickyrolanda @andifahruddinakas : Ternyata karena setting
> ```
>   $config['server_pantau'] = 'https://devtracker.opensid.my.id';
> ```
> 
> Berhasil kalau menggunakan 
> ```
> $config['server_pantau'] = 'https://pantau.opensid.my.id';
> ```
> 
> Coba periksa apakah token_pantau berbeda untuk devtracker atau apakah devtracker sudah dimuat rilis terbaru. Yang jelas tidak ada notifikasi sebab errornya. Error di log terkait pemanggilan layanan, tidak terkait pemanggilan tracker. Sebaiknya ada notifikasi error.

https://devtracker.opensid.my.id belum di perbarui

**Comment by eddieridwan** [comment]
@vickyrolanda , jangan lupa devtracker perlu selalu diupdate juga.

**Comment by andifahruddinakas** [comment]
> https://pantau.opensid.my.id

Pak @eddieridwan, sy cek responnya ada cuma datanya yg ditampilkan kosong. Mungkin kasus ini butuhnya `https://devtracker.opensid.my.id/` di perbarui saja dengan versi terbaru.

![image](https://user-images.githubusercontent.com/57283157/182748258-04cceae2-119c-4968-a4b7-4b357d3ddc0f.png)

**Comment by eddieridwan** [comment]
@andifahruddinakas yg berikut tetap diperlukan:
1. notifikasi jika pantau tidak bisa diakses karena tidak ada jaringan internet
2. notifikasi jika ada jaringan internet, tapi pantau tidak bisa diakses (tampilkan url yg berusaha diakses)
3. perbaiki notifikasi tidak ada data ke dalam bahasa Indonesia. Dalam hal ini juga tampilkan url yg tidak berisi data tersebut.

Yaitu, kita berusaha memberi informasi yg diketahui, supaya pengguna tidak bingung atau sedikitnya ada informasi tambahan.

**Comment by andifahruddinakas** [comment]
> @andifahruddinakas yg berikut tetap diperlukan:
> 
> 1. notifikasi jika pantau tidak bisa diakses karena tidak ada jaringan internet
> 2. notifikasi jika ada jaringan internet, tapi pantau tidak bisa diakses (tampilkan url yg berusaha diakses)
> 3. perbaiki notifikasi tidak ada data ke dalam bahasa Indonesia. Dalam hal ini juga tampilkan url yg tidak berisi data tersebut.
> 
> Yaitu, kita berusaha memberi informasi yg diketahui, supaya pengguna tidak bingung atau sedikitnya ada informasi tambahan.

1.  Yang ada saat ini jika tidak ada jaringan, Identitas desa beralih ke mode input manual.

Untuk point 2 dan 3 apa response di pantau yang disesuaikan, jadi di OpenSID tinggal ditampilkan?

**Comment by vickyrolanda** [comment]
> > @andifahruddinakas yg berikut tetap diperlukan:
> > 
> > 1. notifikasi jika pantau tidak bisa diakses karena tidak ada jaringan internet
> > 2. notifikasi jika ada jaringan internet, tapi pantau tidak bisa diakses (tampilkan url yg berusaha diakses)
> > 3. perbaiki notifikasi tidak ada data ke dalam bahasa Indonesia. Dalam hal ini juga tampilkan url yg tidak berisi data tersebut.
> > 
> > Yaitu, kita berusaha memberi informasi yg diketahui, supaya pengguna tidak bingung atau sedikitnya ada informasi tambahan.
> 
> 1. Yang ada saat ini jika tidak ada jaringan, Identitas desa beralih ke mode input manual.
> 
> Untuk point 2 dan 3 apa response di pantau yang disesuaikan, jadi di OpenSID tinggal ditampilkan?

mas @andifahruddinakas untuk point 3 diganti di jquery select itu yang muncul " no result found" diganti " tidak ada data"
<img width="663" alt="image" src="https://user-images.githubusercontent.com/59082428/182766769-994c2594-c241-47fe-a33f-3f1494ac7daf.png">

Point 2 saya rasa tetap di opensid mas , mungkin jika ada internet tapi ketika akese ke pantau no respon maka diberikan notifikasi "url" ini sedang tidak terhubung.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1184
