### ISSUE TITLE
[TinyMCE] Konversi surat RTF bawaan sistem ke TinyMCE

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#5458]

**Comment by andifahruddinakas** [comment]
Mulai dari surat yang sederhana terlebih dahulu.

**Comment by andifahruddinakas** [comment]
Pecah modul ini per 1 surat.

**Comment by eddieridwan** [comment]
@vickyrolanda buat issue terpisah untuk masing2 surat yg perlu dikonversi

**Comment by vickyrolanda** [comment]
- [ ] https://github.com/OpenSID/OpenSID/issues/5754
- [ ] https://github.com/OpenSID/OpenSID/issues/5755
- [ ] https://github.com/OpenSID/OpenSID/issues/5757
- [ ] https://github.com/OpenSID/OpenSID/issues/5758
- [ ] https://github.com/OpenSID/OpenSID/issues/5759
- [ ] https://github.com/OpenSID/OpenSID/issues/5761
- [ ] https://github.com/OpenSID/OpenSID/issues/5762
- [ ] https://github.com/OpenSID/OpenSID/issues/5763
- [ ] https://github.com/OpenSID/OpenSID/issues/5764

yang lain tidak saya lampirkan kesini sy buatkan saja issuenya terlebih dahulu ya mas.
