### ISSUE TITLE
Permintaan fitur: Group Pengguna untuk RT dan RW

### ISSUE THREAD

**Issue by kedungsalam-ds** [OpenSID/OpenSID#5469]
### Apa kekurangan yg ingin diatasi?

Jika jumlah penduduk sangat banyak (diatas 10.rb jiwa) Admin desa memerlukan waktu yang sangat panjang untuk akurasi data penduduk. Untuk itu diperlukan SDA untuk membantu entri data dalam akurasi data desa. Adapun yang paham akan kondisi dan lokasi wilayah adalah RT-RW setempat. Maka dari itu di perlukan Pengguna/user untuk pak RT dan pak RW. 
minimal bisa Read menu Kependudukan dan Statistik sesuai dengan wilayahnya saja. Sedangkan untuk perubahan memerlukan persetujuan atau menghubungi admin Desa

### Jelaskan solusi yg diinginkan

ada pengaturan Pengguna / user yang mempunyai hak akses hanya pada RT-RW yang mereka pimpin

### Apakah ada alternatif lain

ada layanan Login seperti layanan mandiri khusus untuk RT dan RW

### Untuk versi OpenSID mana

22.03

**Comment by langonsari** [comment]
ini cocok karena sekarang tentang Administrasi Kependudukan sudah tidak berlaku lagi pengantar RT, RW ataupun Desa,,,
sehingga apabila ada masyarakat Pindah datang bisa langsung di data oleh RT/RW dengan penambahan menu approval dari Desa,,

**Comment by andifahruddinakas** [comment]
Duplicate issue https://github.com/OpenSID/OpenSID/issues/4423
