### ISSUE TITLE
Tambahkan anti brute-force di login 

### ISSUE THREAD

**Issue by telo99** [OpenSID/OpenSID#547]
Ada kemungkinan penyerang akan menggunakan metode brute force untuk mencoba masuk ke site manager.
Alangkah baiknya jika kesalahan login dibatasi hanya 10 misalnya (atau bisa juga dibuat agar pengguna bisa mengatur sendiri jumlahnya). Jika 10x gagal, blokir IP-nya selama 1 hari.

#SekedarIde #NggakTerlaluPenting :)

**Comment by eddieridwan** [comment]
Mungkin bisa diatasi dengan usul penambahan capcha di login, di issue #489.

**Comment by eddieridwan** [comment]
Setelah konsultasi dengan pengguna di https://www.facebook.com/groups/OpenSID/, pengguna lebih memilih cara menutup login sementara daripada menggunakan captcha.

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
