### ISSUE TITLE
Bug/error: Tidak bisa menambahkan data pembangunan baru ketika menggunakan akun dengan group bukan admin

### ISSUE THREAD

**Issue by verlin884** [OpenSID/OpenSID#5470]
### Jelaskan error yg dialami

Saya membuat grup pengguna baru untuk memberikan akses menambah / hapus / ubah data pembangunan. tetapi button tambah pada page pembangunan tidak muncul. 

### Cara untuk mereplikasi errornya

1. buat grup admin pembangunan
2. menambahkan akses baca, ubah dan hapus Pembangunan
3. simpan
4

1. tambah pengguna baru
2. pilih grup admin pembangunan -> isi semua field 
3. simpan

1. login ke akun yang telah dibuat
2. klik pembangunan
3.  tidak ada tombol tambah yang seharusnya muncul.

### Hasil yg diharapkan

bisa menambahkan data pembangunan baru

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/43753984/183055653-ebacefc3-3f76-44a7-afe2-a29830ce7097.png)
![image](https://user-images.githubusercontent.com/43753984/183055748-4274cbdf-c2bd-402a-a90d-eab105fa9127.png)
![image](https://user-images.githubusercontent.com/43753984/183055809-32ad571d-7496-4e51-b3dd-aa4836d7594d.png)

### Rilis Versi OpenSID

Rilis Umum

### Versi OpenSID

22.07

**Comment by yogiperdana** [comment]
Duplikat issue https://github.com/OpenSID/OpenSID/issues/4794

**Comment by yogiperdana** [comment]
Issue ini telah diperbaiki pada Rilis v22.02-premium dan akan masuk ke Rilis umum v22.09 bulan depan
