### ISSUE TITLE
Bug/error: Laporan Rincian Realisasi hasil dari impor siekudes error 500

### ISSUE THREAD

**Issue by BubySaputra** [OpenSID/OpenSID#5471]
### Jelaskan error yg dialami

![image](https://user-images.githubusercontent.com/28770140/183255890-4c14d330-ba92-445b-9861-ba7f1296c3c9.png)

### Cara untuk mereplikasi errornya

[opensid_data.zip](https://github.com/OpenSID/OpenSID/files/9275352/opensid_data.zip)

### Hasil yg diharapkan

tidak error

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/28770140/183255940-9941fb11-741c-4b15-a14a-40c3bbb8ce6c.png)

Query error: Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'kh16mekarsari_sid.keuangan_ta_jurnal_umum_rinci.Kd_Rincian' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by - Invalid query
SELECT LEFT(Kd_Rincian, 2) AS Akun, SUM(keuangan_ta_jurnal_umum_rinci.Debet) AS realisasiFROM `keuangan_ta_jurnal_umum_rinci`WHERE `Kd_Rincian` LIKE '5.%' ESCAPE '!'AND `keuangan_ta_jurnal_umum_rinci`.`Tahun` = '2022'GROUP BY `Akun`

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

22.08 Premium

### Tema Yang Digunakan

-

### Informasi tambahan

-

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1197
