### ISSUE TITLE
Bug/error: NIK warga luar desa tidak bisa input lebih dari satu kali di menu tanah yg ada di desa

### ISSUE THREAD

**Issue by muhtar-coder** [OpenSID/OpenSID#5472]
### Jelaskan error yg dialami

Input nik yg sama warga luar desa tidak bisa dipakai/input lebih dari satu kali pada menu "tanah yg ada di desa"

### Cara untuk mereplikasi errornya

Di buku administrasi umum sub tanah yang ada di desa> input warga luar desa> lakukan lebih dari satu kali input.

Notif: NIK sudah digunakan 

Harus nya bisa duplikat nik

### Hasil yg diharapkan

Bisa digunakan berkali kali mengingat satu nama/nik memiliki lebih dari satu bidang tanah.

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

22.08-premium

### Tema Yang Digunakan

Denatra

### Informasi tambahan

Untuk warga desa sudah normal/ bisa duplikat nik

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1198
