### ISSUE TITLE
Permintaan fitur: Tambahkan Modul Untuk Pengisian Profil Desa

### ISSUE THREAD

**Issue by Pematung** [OpenSID/OpenSID#5473]
### Apa kekurangan yg ingin diatasi?

Perlunya ditambahkan modul khusus untuk pengisian Profil desa yang mana ini sangat dibutuhkan setiap tahunnya

### Jelaskan solusi yg diinginkan

Agar pemerintah desa lebih di permudah dalam pengisian Profil Desa dan data profil tersebut bisa terekam sebagai arsip desa pertahunnya dan bisa untuk mempermudah desa membuat laporan guna untuk mewujudkan desa 1 data dalam 1 aplikasi OpenSID

### Apakah ada alternatif lain

Masih menggunakan format exel secara manual

### Untuk versi OpenSID mana

22.09 Premium

### Informasi tambahan

Ini Contoh Format Tabel pengisian Profil Desa

[PROFIL DESA PEMATUNG.pdf](https://github.com/OpenSID/OpenSID/files/9280640/PROFIL.DESA.PEMATUNG.pdf)

**Comment by eddieridwan** [comment]
Duplikat https://github.com/OpenSID/OpenSID/issues/5519
