### ISSUE TITLE
Bug/error: Last Login Tidak Terperbarui Setelah Login atau Logout

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#5475]
### Jelaskan error yg dialami

Last login tidak diperbarui.

### Cara untuk mereplikasi errornya

1. Sesuaikan dulu last login di database tabel user last_login, atur jadi hari sebelum pengecakan PR.
2. Lakukan login seperti biasanya
3. Bandingkan login hari sebelum (asumsi no. 1) dengan setelah login (hari ini)
4. Last login tetap sama, yakni hari sebelumnya (tdk terperbarui)

### Hasil yg diharapkan

Diperbarui sesuai waktu login / logout

### Tangkapan layar dan log error

.

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.07-premium-rev01

### Tema Yang Digunakan

bawaan

### Informasi tambahan

.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1208
