### ISSUE TITLE
Bug/error: isian luas tanah tidak bisa tersimpan di menu bumindes tanah kas desa

### ISSUE THREAD

**Issue by muhtar-coder** [OpenSID/OpenSID#5476]
### Jelaskan error yg dialami

Ketika mengisi luasan tanah di bumindes tanah kas desa tidak bisa tersimpan

### Cara untuk mereplikasi errornya

Pergi ke bumindes pilih tanah kas desa lalu coba isi luas tanah.
Sudah coba bolak balik coba isi di kolom luas secara bergantian di kolom isian tapi gak tersimpan.

Tapi ketika kolom isian dikosongkan, data berhasil tersimpan

### Hasil yg diharapkan

Bisa terisi normal dan kalo bisa kolom luas tanah yg memiliki patok/tidak agar dikaji ulang

### Tangkapan layar dan log error

Gambar setelah coba berkali kali bolakbalik isian.

![Screenshot_20220809-115332_Chrome](https://user-images.githubusercontent.com/55665526/183567912-cb172afc-8dd3-4bff-8d53-61759a0166f6.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

22.08-premium

### Tema Yang Digunakan

Denatra

### Informasi tambahan

Tidak ada

**Comment by andifahruddinakas** [comment]
Mas @vickyrolanda, coba di cek cara perhitungan yang benar bagaimana??? Karena saya cek logika kodingnya akan berhasil disimpan jika : 

`luas == dinLuas && luas == dinTKD && luas == dinPatok && luas == dinPapan`

terpenuhi.

Contoh : 
Gagal
![gagal1](https://user-images.githubusercontent.com/57283157/183574713-655dc900-68cb-494d-9bfc-0d4fb4249711.png)

Berhasil
![berhasil1](https://user-images.githubusercontent.com/57283157/183574751-2f51fc88-388f-4cba-b17e-355a3ddb9773.png)

**Comment by andifahruddinakas** [comment]
Bisa cek issue sebelumnya di https://github.com/OpenSID/OpenSID/issues/2837

**Comment by vickyrolanda** [comment]
ok mas @andifahruddinakas  akan saya pelajarin ini dulu.

**Comment by vickyrolanda** [comment]
Setelah saya lihat beberapa referensi "kondisi rumus di bawah mas @andifahruddinakas "

luas == dinLuas && luas == dinTKD && luas == dinPatok && luas == dinPapan

bisa di ganti hanya di bandingkan dengan 
1.LUAS = Disi luas tanah kas desa , Misal (1500) 

Maka penjabarannya disi dari mana prolehannya :
Perolehan Kas desa :
2. Asli Milik Desa = Diisi denga luas tanah kas desa yang perolehannya di beli atas biaya
3. Hibah / bantuan = Pemerintah + Provinsi + Kabupaten  
  - pemerintah = Disi dengan luas tanah kas desa yang di peroleh dari pemerintah (jika dari pemerintah)
  - Prov = disi jiga dari (prov)
  - Kab = Disi jika dari kab/kota 
4.Lain-lain = disi dari luas tanah desa yang di peroleh dari lain - lain 
5. Jenis Tanah Kas Desa (total dari sawah + tegal + kebun + tambak + Tanah kering)
- Sawah = disi dengan luas kas desa penggunaan sawah
- Tegal = disi dengan luas tegal
- Kebun = disi luas kas desa untuk kebun 
- Tambak / Kolam  = disi luas kas desa untuk tambah / kolam
- Tanah Kering / darat =  disi luas kas desa untuk anah Kering / darat (disi 1)
--------------------------------------------------------------------
Rumusnya jika asal tanah kas desa memilih : 
- opsi no 2 maka rumusnya jadi = 1(luas) == 2(luas tanah milik desa) && 1luas == 5 (luas jenis tanah kas desa)
- opsi no 3 maka rumus jadi = 1(luas) == 3 (total dari luas Pemerintah + Prov + Kab) && 1luas == 5 (luas jenis tanah kas desa)
- opsi no 4 maka rumus jadi = 1(luas) == 4 (luas dari prolehan lain -lain) && 1luas == 5 (luas jenis tanah kas desa)
---------------------------------------------------------------------------------

sedangkan data dibawah hanya melengkapin detailsnya saja tidak perlu dibandingkan mas.
-Patok tanda batas
-Papan nama
-Lokasi 
-Peruntukan

**Comment by eddieridwan** [comment]
@andifahruddinakas @vickyrolanda , salah satu cara supaya lebih jelas bagi pengguna:

1. Hanya buka luas total dulu
2. Setelah luas total diisi, tampilkan jumlah itu di setiap baris, dan baru dibuka untuk diisi.
4. Beri tanda '=' dan '+' di setiap baris supaya jelas bahwa itu dijumlahkan

![image](https://user-images.githubusercontent.com/249563/185534523-7ab972a6-f218-4fa5-85de-5c88e387221e.png)

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1247
