### ISSUE TITLE
Bug/error: Judul pada jumlah Covid Desa tidak tampil

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#5478]
### Jelaskan error yg dialami

Judul pada jumlah Covid Desa tidak tampil/blank

### Cara untuk mereplikasi errornya

tampilkan data covid desa di web

### Hasil yg diharapkan

Muncul

### Tangkapan layar dan log error

![putar](https://user-images.githubusercontent.com/36557759/183649797-56115b05-ba77-443d-903d-56417f34c3cb.PNG)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

22.08-premium-rev01

### Tema Yang Digunakan

Natra

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1213
