### ISSUE TITLE
Bug/error: menu statistik kependudukan (pekerjaan, umur,agama, pendidikan, dsb) dan data suplemen nama item tidak muncul

### ISSUE THREAD

**Issue by Restony33** [OpenSID/OpenSID#5483]
### Jelaskan error yg dialami

Pada menu Statistik Kependudukan (pekerjaan, umur,agama, pendidikan, dsb...), nama item tidak muncul, yg muncul hanya jumlah (angka), sedangkan pada data suplemen login admin nama data tidak tampil, yang tampil hanya jumlah, saat data suplemen melalui web terjadi error
 
![suplemen](https://user-images.githubusercontent.com/104592011/183826752-dd95684c-03eb-4af9-afa2-60cb127c6407.JPG)
![error](https://user-images.githubusercontent.com/104592011/183826913-3d22d6c6-3601-429e-91ed-b9c0c238cbb0.JPG)
 

### Cara untuk mereplikasi errornya

login admin >> Kependudukan >> data suplemen
![suplemen](https://user-images.githubusercontent.com/104592011/183827215-83605df0-c8e6-432f-bdbb-7b0d217e6df4.JPG)

### Hasil yg diharapkan

berjalan normal

### Tangkapan layar dan log error

![statistik](https://user-images.githubusercontent.com/104592011/183827104-554c1a3e-bb5d-473f-859f-64a79f2d5e3f.JPG)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.08-premium-rev01

### Tema Yang Digunakan

Natra v22.06

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/1213
