### ISSUE TITLE
Permintaan fitur: modul DTKS

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#5484]
### Apa kekurangan yg ingin diatasi?

Data DTKS diminta oleh berbagai instansi supra-desa sebagai data yg dikelola di OpenSID. Modul ini bersifat komplementer, bukan menggantikan aplikasi SIKS-NG yg disediakan oleh Kemsos. 

### Jelaskan solusi yg diinginkan

Sediakan modul untuk mengelola DTKS, termasuk fitur untuk mengekspor data tersebut ke aplikasi lain. 

Idealnya sesuai dengan DTKS format tahun 2022. Yg ditemukan saat ini baru format DTKS tahun 2020. 

[Form_BDT.pdf](https://github.com/OpenSID/OpenSID/files/8925130/Form_BDT.pdf)

Ternyata BPS akan menyelenggarakan pendataan registrasi sosial ekonomi pada tanggal 15 okt s.d 14 November 2022 yg isinya hampir sama dengan BDT. Untuk modul DTKS ini, kita akan gunakan kuesioner Regsosek berikut, karena sepertinya akan digunakan menggantikan Form BDT.
 
[5) Kuesioner Regsos21_verFINAL03.pdf](https://github.com/OpenSID/OpenSID/files/9565910/5.Kuesioner.Regsos21_verFINAL03.pdf)

### Apakah ada alternatif lain

Potensial menggunakan master analisis, tetapi lebih sulit digunakan dan juga akan memerlukan penambahan pada OpenSID yg mungkin bersifat khusus untuk DTKS juga. 

### Untuk versi OpenSID mana

Ditargetkan untuk v22.10-premium

### Informasi tambahan

Dalam merancang modul DTKS, gunakan SIKS-NG Offline sebagai acuan. SIKS-NG Offline mempunyai fitur untuk mengekspor data BDT yang dapat diimpor ke SIKS-NG Online.

[siks-ng-panduan-offline.pdf](https://github.com/OpenSID/OpenSID/files/9503166/siks-ng-panduan-offline.pdf)
[siks-ng-panduan-online.pdf](https://github.com/OpenSID/OpenSID/files/9503167/siks-ng-panduan-online.pdf)

**Catatan**:

1. Di menu navigasi utama (sebelah kiri), tambahkan menu baru `Satu Data`, dengan submenu `DTKS`. Akses modul DTKS melalui menu tersebut
2. Lakukan pengelolaan CRUD Rumah Tangga BDT di modul yg sudah ada di Kependudukan > Rumah Tangga. Jangan buat yg baru.
3. Lengkapi form Rumah Tangga dan tabel tweb_rtm yg sudah ada untuk menampung data rumah tangga yang diperlukan untuk data BDT.
4. Ubah Rumah Tangga yg ada supaya hanya memilih kepala keluarga dan kemudian tambahkan semua anggota KK ybs sebagai anggota rumah tangga. Data untuk Blok (Pengenalan Tempat) I terisi secara otomatis dari data KK yg ditambahkan.
![image](https://user-images.githubusercontent.com/249563/188808972-15ca0cb1-af3b-4651-8f61-f5cc10f12dc4.png)
5. Gunakan asumsi bahwa setiap keluarga yg ditambahkan ke suatu rumah tangga tinggal di alamat rumah yang sama. 
6. Tambahkan data Blok III (Keterangan Perumahan) ke tabel tweb_rtm.
![image](https://user-images.githubusercontent.com/249563/188810546-61d433fa-6389-4538-87e1-0890e2ba8935.png)
7. Tambahkan data Blok V (Kepemilikan Aset) ke tabel tweb_rtm.
![image](https://user-images.githubusercontent.com/249563/188815081-382eadf0-14ab-48be-97c3-4513967848f4.png)
8. Untuk data ART YANG MEMILIKI USAHA, buat tabel baru (anggota_rt) yg merupakan perpanjangan dari tabel penduduk tweb_penduduk. Isi data yg diperlukan sesuai form BDT.
![image](https://user-images.githubusercontent.com/249563/188817330-8712586f-b7f5-448e-993c-61827deb06ee.png)
9. Data Blok IV (Keterangan Sosial ART), data tambahan dimasukkan ke tabel baru anggota_rt. Tapi data yg sdh ada di tweb_penduduk tidak ditambahkan lagi. Yaitu data seperti terlihat di gambar berikut sudah ada di tweb_penduduk.
![image](https://user-images.githubusercontent.com/249563/188821341-dfe4a522-6ad3-4e2e-9aca-479199cf93b3.png)
Data tambahan untuk Blok IV masukkan ke tabel anggota _rt.
![image](https://user-images.githubusercontent.com/249563/188822619-50e83bdc-6250-4df1-a5f8-b18c339e1ddc.png)
![image](https://user-images.githubusercontent.com/249563/189512036-6da05252-d800-48b7-ad57-bddd7a7daa0c.png)
![image](https://user-images.githubusercontent.com/249563/189512040-bf7a2887-416f-4c1b-b7e7-685773e4ddbe.png)
7. Ada fitur untuk impor data BDT, idealnya bisa mengimpor data yg diekspor dari aplikasi SIKS-NG Offline. Jika format .siks tidak berhasil diperoleh, lakukan impor menggunakan format .csv hasil ekspor di butir berikut ini.
8. Ada fitur untuk eskpor data BDT, idealnya sesuai format data yg diekspor dari aplikasi SIKS-NG Offline. Jika format .siks tidak berhasil diperoleh, lakukan ekspor dalam format .csv berisi semua data BDT yang terisi.
9. Cetak prelist, termasuk Blok I s/d V, seperti terlihat di panduan SIKS-NG Offline.
![image](https://user-images.githubusercontent.com/249563/189512076-2ce3f2da-3ead-4075-9e64-61a7f8803588.png)

**Comment by MUHAMMADRANGSEL** [comment]
sangat setuju

**Comment by MUHAMMADRANGSEL** [comment]
dibuatkan KHUSUS menu untuk DTKS sehingga akan memudahkan pengelolaannya sekaligus integrasi dengan aplikasi SUPRA DESA

**Comment by ruririzal** [comment]
1. bagaimana alur pengelolaan DTKS yang diinginkan? 
1a. apakah input/edit data manual di halaman "formulir yang dinamis" sesuai dengan [Form_BDT.pdf](https://github.com/OpenSID/OpenSID/files/8925130/Form_BDT.pdf) oleh administrator?

![image](https://user-images.githubusercontent.com/28647065/187505611-4a3bdea2-7418-46dd-bd3b-edb1e23508dd.png)

![image](https://user-images.githubusercontent.com/28647065/187505752-4091ccc0-bd05-41d2-9fb6-41f4b43a5eba.png)

**Comment by muslimrahmany** [comment]
Setuju, sangatt setuju

**Comment by ruririzal** [comment]
@eddieridwan setelah saya baca panduan dari aplikasi SIKS-NG Offline, 

> 10. Ada fitur untuk impor data BDT, idealnya bisa mengimpor data yg diekspor dari aplikasi SIKS-NG Offline.
> 11. Ada fitur untuk eskpor data BDT, idealnya sesuai format data yg diekspor dari aplikasi SIKS-NG Offline.

mengenai point no 10. dan 11. fitur import dan export ke dan dari aplikasi SIKS-NG Offline ke OpenSID, saya rasa cukup susah mengingat extensi nya bukan excel

![image](https://user-images.githubusercontent.com/28647065/189040593-9b88f7d9-69b6-4ff4-afc5-1aadc69c739b.png)
![image](https://user-images.githubusercontent.com/28647065/189040759-f5b9791e-7f5a-4b42-9d1f-0b769d339382.png)

**Comment by vickyrolanda** [comment]
DFD dari mas @ruririzal 
![schemaDTKS](https://user-images.githubusercontent.com/59082428/189265861-f108047f-7b64-440e-b170-e10e3f913cba.jpg)

**Comment by vickyrolanda** [comment]
[sampel form regsosek 2022.pdf](https://github.com/OpenSID/OpenSID/files/9926339/sampel.form.regsosek.2022.pdf)

**Comment by eddieridwan** [comment]
Sudah masuk ke 22.12-premium
