### ISSUE TITLE
Bug/error: gagal migrasi

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#5485]
### Jelaskan error yg dialami

gagal saat migrasi, DB dan folder desa ada di link gdrive

https://drive.google.com/drive/folders/1A5-oKwhX8HUSYNkq1Z31TULyiM5Nl1U3?usp=sharing

### Cara untuk mereplikasi errornya

saat migrasi gagal

### Hasil yg diharapkan

berhasil migrasi

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

22.07-premium-rev03

**Comment by andifahruddinakas** [comment]
Sy lihat pengecekannya di versi 22.07-premium-rev03, sekrang 22.08-premium-rev01. Selalu cek di versi yang terbaru, jika tidak masalah berarti sudah di perbaiki di versi terbaru tsb. Lihat log, tidak ada log error yang menandakan terjadinya gagal migrasi, berari hanya keasalahan notif saja. Cek issue https://github.com/OpenSID/OpenSID/issues/5432, sudah pernah dilaporkan dan perbaiki.
