### ISSUE TITLE
Bug/error: Terjadi Bug ketika input data ibu di entry anak kedua pada data stunting

### ISSUE THREAD

**Issue by IkfanDjalaludin** [OpenSID/OpenSID#5486]
### Jelaskan error yg dialami

Terjadi Bug ketika input data ibu di entry anak kedua, data ibu tidak bisa terdeteksi dikolom pencarian pada stunting

### Cara untuk mereplikasi errornya

1. Pergi kehalaman stunting isian FormKia
2. Klik tombol Cari NIK / Nama Ibu

### Hasil yg diharapkan

Seharusnya ketika nama balita kedua dari Ibu yang sama di input tidak terdapat Bug

### Tangkapan layar dan log error

<img width="960" alt="anak_01" src="https://user-images.githubusercontent.com/111027614/184049208-b62ca157-0374-4cd3-b46d-b220038541ea.png">
<img width="960" alt="ANAK_02" src="https://user-images.githubusercontent.com/111027614/184049229-e4323825-c040-4c38-8232-9440c72bfb9b.png">

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Premium (v22.08-premium)

### Tema Yang Digunakan

Batuah

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1219
