### ISSUE TITLE
Bug/error: Infrastruktur Desa ada perbedaan antara map di admin dengan yang ada di website

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#5487]
Tampilan di halaman admin
<img width="648" alt="image" src="https://user-images.githubusercontent.com/59082428/183555768-eb02b056-838b-40b1-9a6f-b6d3d6ca7ddd.png">

Tampilan di halaman web
<img width="851" alt="image" src="https://user-images.githubusercontent.com/59082428/183556083-49dbaa98-3b22-4a1f-8815-30f7419df080.png">

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1218
