### ISSUE TITLE
Bug/error: Link data suplemen tidak terdeteksi / tidak muncul

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#5488]
### Jelaskan error yg dialami

Link data suplemen tidak muncul di halaman Tambah menu dan Data Suplemen

### Cara untuk mereplikasi errornya

1. Klik menu Admin Web
2. Menu
3. Tambah Menu

### Hasil yg diharapkan

Link data suplemen muncul

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/36557759/184063389-99139e1d-8c22-4f8b-ac9e-43fae19ee35d.png)
![image](https://user-images.githubusercontent.com/36557759/184063400-a41de94e-6b9b-4c3e-9076-1ad385a07356.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

22.08

**Comment by andifahruddinakas** [comment]
Mas @devrakapriyo, coba cek di branch `bug-fix` karena `rilis-dev` belum di update sama mas @vickyrolanda. Sudah diperbaiki (di kembalikan) melalui PR https://github.com/OpenSID/premium/pull/1213

**Comment by devrakapriyo** [comment]
ok mas @andifahruddinakas saya cek di bug-fix, sudah solved
