### ISSUE TITLE
[TTE] pindahkan pengaturan tte ke dalam pengaturan surat dan Tambahkan fungsi validasi saat ingin mengaktifkan tte

### ISSUE THREAD

**Issue by apidong** [OpenSID/OpenSID#5490]
- [x] pindahkan pengaturan tte
- [x] modul tte bisa aktif jika user kades sudah dibuat

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1226

> * [x]  pindahkan pengaturan tte
> * [x]  modul tte bisa aktif jika user kades sudah dibuat

untuk point ke 2 bisa di kirimkan PR susulan ya mas @apidong
