### ISSUE TITLE
[TTE] Tambahkan alasan tolak ketika verifikasi surat

### ISSUE THREAD

**Issue by apidong** [OpenSID/OpenSID#5492]
- [x] Tambahkan alasan tolak ketika verifikasi surat dan tampilkan di tabel tolak
- [x] surat di yang ditolak bisa diperbaiki
- [x] surat yang di tolak yang berasal dari layanan mandiri, surat tsb bisa dikembalikan ke pemohon untuk diperbaiki.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1232
