### ISSUE TITLE
Permintaan fitur: Formulir F. 201 terbaru

### ISSUE THREAD

**Issue by ngexs** [OpenSID/OpenSID#5494]
### Apa kekurangan yg ingin diatasi?

disesuaikan dengan Format Terbaru Untuk Seluruh Pencatatan Sipil Di Wilaya NKRI

### Jelaskan solusi yg diinginkan

Disesuaikan dengan kondisi terkinian terkait dengan Adminduk

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

Untuk Rilis Premium

### Informasi tambahan

[form F201 capil.pdf](https://github.com/OpenSID/OpenSID/files/9313307/form.F201.capil.pdf)

**Comment by andifahruddinakas** [comment]
Duplicate issue https://github.com/OpenSID/OpenSID/issues/5259
