### ISSUE TITLE
Bug/error: jenis kelompok tidak muncul saat menampilkan statistik penduduk pada peta

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#5496]
### Jelaskan error yg dialami

jenis kelompok tidak muncul, baik itu di tema natra maupun esensi

### Cara untuk mereplikasi errornya

1. Halaman website
2. Masuk ke halaman peta
3. Pada peta  > klik peta wilayah desa
4. klik peta yang berwarna merah atau ditandai sebagai peta desa
5. klik tombol statistik penduduk
6. klik statistik2 nya > semua nama kelompok tidak muncul

### Hasil yg diharapkan

Jenis kelompok muncul sebagaimana mestinya.

### Tangkapan layar dan log error

![peta](https://user-images.githubusercontent.com/36557759/184293509-561c0ee2-f25e-423d-a96a-e1e0049e9623.PNG)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

 22.08-premium-rev01

### Tema Yang Digunakan

natra dan esensi

**Comment by andifahruddinakas** [comment]
Mas @devrakapriyo, sudah cek di branch `bug-fix` ?

**Comment by devrakapriyo** [comment]
Ok solved mas, akan saya infokan ke pengguna untuk menunggu rilis rev 2
