### ISSUE TITLE
Bug/error: Klasifikasi menjadi hilang saat membuat surat dengan memilih format F103 (Pindah datang).

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#5497]
### Jelaskan error yg dialami

Klasifikasi menjadi hilang saat membuat surat dengan memilih format F103 (Pindah datang).

### Cara untuk mereplikasi errornya

1. Buat surat
2. pilih format surat pindah datang

### Hasil yg diharapkan

Mas @vickyrolanda mohon di analisis terkait issue ini apakah memang bug atau ketentuannya memang seperti itu.

### Tangkapan layar dan log error

![klass](https://user-images.githubusercontent.com/36557759/184294881-a609289c-e18d-4854-91a5-8588fcdc06c7.PNG)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

 22.08-premium-rev01

### Tema Yang Digunakan

-

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1229
