### ISSUE TITLE
laporan analisis saat di unduh datanya ngak tampil    ;Bug/error: 

### ISSUE THREAD

**Issue by Fajar-blackdeath** [OpenSID/OpenSID#5498]
### Jelaskan error yg dialami

![image](https://user-images.githubusercontent.com/79009911/184325644-b1041627-a264-4393-87bd-410bf055e88f.png)
data yang di download dari hhasil isisan analisis tidak keluar

### Cara untuk mereplikasi errornya

1.masuk ke menu analisis
2.  masuk ke master analisi
3.  pilih input data analisi
4.  unduh hasil data analiis
5.  data yang sudah diiisi bisa di unduh tapi hasilnya tidak keluar
6.

### Hasil yg diharapkan

saya sudah mengisi data analisis sdgs tapi datany tidak bisa di jadikana data suplemen.
satya harap pertanyaan yang sudah saya buat otomatis menjadi data suplemen

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/79009911/184326188-d8f5daf1-eb82-491b-9228-8121913e3294.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

22.08

### Tema Yang Digunakan

-

### Informasi tambahan

mohon seegera di selellesaikan karena saya menggunakan data analisis sebagai acuan pada musrembang dan pemilihan data bantaun yang cocok. bukan hanya sekedata pembacaan data.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1235
