### ISSUE TITLE
Bug/error: nama pamong tidak muncul

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/OpenSID#5500]
### Jelaskan error yg dialami

Nama pamong tidak muncul jika data pamong dari penduduk.

### Cara untuk mereplikasi errornya

1. Pergi ke halaman Admin
2. Pilih Layanan Surat
3. Klik Cetak surat
4. Buat Surat pada Keterangan Bepergian / Jalan
5. Ketika memilih yang Bertanda Tangan Kepala Desa pada staf pemerintahan desa tidak muncul nama kepala desa

### Hasil yg diharapkan

Dapat menampilkan nama Kepala Desa seperti pada saat memilih a.n Kepala Desa

### Tangkapan layar dan log error

![photo_2022-08-13_14-06-44](https://user-images.githubusercontent.com/68048807/184473266-d0c08855-6d8a-4638-90d8-4e4f7949507d.jpg)

![photo_2022-08-13_14-14-12](https://user-images.githubusercontent.com/68048807/184473362-5ffc69e8-0537-4739-9f11-6bfe024cf1c8.jpg)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Versi 22.08-premium-beta01

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1233
