### ISSUE TITLE
Bug/error: Jenis kelompok pada statistik hilang

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/OpenSID#5502]
### Jelaskan error yg dialami

Jenis kelompok pada statistik hilang, terjadi di semua statistik kependudukan, termasuk pada grafik data dan pie data. 

### Cara untuk mereplikasi errornya

1. Masuk ke halaman admin
2. Klik Modul Statistik
3. Klik Menu statistik kependudukan
4. Pilih kategori statistik

### Hasil yg diharapkan

normal dapat menampilkan kelompok pada statistik.

### Tangkapan layar dan log error

![statistik1](https://user-images.githubusercontent.com/68048807/184517179-11bef8db-d033-44a9-950a-93dadde03a49.jpg)
![statistik2](https://user-images.githubusercontent.com/68048807/184517182-33a496df-401e-48b3-b9f4-771b84f086cb.jpg)
![statistik3](https://user-images.githubusercontent.com/68048807/184517183-bf54e360-3f14-49ad-a0f2-f5b918cb7db1.jpg)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.02-premium beta-02

### Tema Yang Digunakan

-

**Comment by andifahruddinakas** [comment]
Cek issue https://github.com/OpenSID/OpenSID/issues/5496, lakukan testing di branch `bug-fix` di rilis-dev belum termasuk gabungan dari branch `bug-fix` pertanggal 15-08-2022.
