### ISSUE TITLE
Permintaan fitur: Tambah tombol waktu penginputan

### ISSUE THREAD

**Issue by muhtar-coder** [OpenSID/OpenSID#5503]
### Apa kekurangan yg ingin diatasi?

1. karena aplikasi datang di tengah tahun sehingga bulan sebelumnya tidak dapat di inputkan sesuai tanggal/bulan kegiatan posyandu.
2. Petugas input kemungkinan bukan petugas posyandu yang berada langsung di lapangan pada hari kegiatan, sehingga memungkinkan saat input bukan pada tanggal pelaksanaan. (wacana program awal  bahwa petugas input data stunting adalah kader KPM sedangkan petugas lapangan saat ini adalah kader posyandu dan Kader TPPS sehingga besar kemungkinan kader yang meng input data stunting/KPM akan meminjam buku kegiatan posyandu dari kader posyandu)
3. agar aplikasi yang sangat berguna ini,meskipun muncul di tengah tahun tetapi dapat menginput data dari mulai januari-desember.

### Jelaskan solusi yg diinginkan

waktu input data bisa sesuai target tanggal /bulan sesuai catatan data kegiatan dan agar rekap kuartal dapat terpenuhi

![image](https://user-images.githubusercontent.com/55665526/184531552-dae77eea-4125-44bf-88ff-4e6dcac1bb84.png)

### Apakah ada alternatif lain

merubah timestamp database (tidak di rekomendasikan)

### Untuk versi OpenSID mana

22.08-premium-rev02

### Informasi tambahan

Tombol atur tanggal berlaku untuk :

1. input data ibu hamil
2. input data anak usia 0-2 tahun
3. input data anak usia 2-6 tahun

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1255
