### ISSUE TITLE
Bug/error: [stunting] tampilan data pada tabel status gizi anak harusnya huruf

### ISSUE THREAD

**Issue by Wiliyantoro** [OpenSID/OpenSID#5504]
### Jelaskan error yg dialami

[stunting] tabel pada rekapitulasi pemantauan 3 Bulanan anak 0 - 2 Tahun pada data status gizi anak muncul angka, seharusnya pakai huruf

### Cara untuk mereplikasi errornya

Halaman Admin -> Kesehatan -> Stunting -> Rekapitulasi -> 3 Bulanan Anak 0 - 2 Tahun

### Hasil yg diharapkan

untuk tampilan data dapat sesuaikan seperti berikut :
N = Normal
B = Buruk
K = Kurang
S = Stunting

### Tangkapan layar dan log error

![rekapitulasi anak 0 2](https://user-images.githubusercontent.com/44520382/184536713-ed0f62dc-4a6f-4d01-bf8c-999119fe2632.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.08-premium

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1234
