### ISSUE TITLE
Bug/error: [stunting] scorecard konvergensi pada tabel jumlah sasaran dan tabel hasil pengukuran tidak berfungsi dengan benar 

### ISSUE THREAD

**Issue by Wiliyantoro** [OpenSID/OpenSID#5505]
### Jelaskan error yg dialami

tampilan data pada scorecard konvergensi tidak sesuai dengan data yang di input 

### Cara untuk mereplikasi errornya

halaman admin -> kesehatan -> stunting -> scorecard konvergensi

### Hasil yg diharapkan

1. jumlah status kehamilan berfungsi sesuai dengan hasil inputan ( pada inputan adalah normal tapi masuk ke KEK/RESTI) harusnya 0 jika inputan normal
2. jumlah status gizi anak agar berfungsi dengan hasil inputan. ( pada inputan adalah normal tapi masuk ke jumlah GIZI BURUK/STUNTING) harusnya 0 jika inputan normal
3. jumlah hasil ukur Hijau Kuning Merah tidak sesuai dengan hasil inputan di Pemantauan Bulanan Anak 0-2 Tahun

### Tangkapan layar dan log error

![scorecard konvergensi bug 1](https://user-images.githubusercontent.com/44520382/184537346-e140aca8-626a-4ff1-a678-b02a5bb4c3ba.png)

![bug 2](https://user-images.githubusercontent.com/44520382/184537315-6f3c4d70-a1d1-4f24-81a6-ee1de67ee8f0.png)

![bug 3](https://user-images.githubusercontent.com/44520382/184537318-a22cd968-97e1-4545-a3ca-f0fc68af22fd.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.08-premium

**Comment by yogiperdana** [comment]
Mohon maaf pak @Wiliyantoro untuk poin 2. jumlah status gizi anak agar berfungsi dengan hasil inputan. ( pada inputan adalah normal tapi masuk ke jumlah GIZI BURUK/STUNTING) harusnya 0 jika inputan norma. Ada di gambar yang mana ya pak? Atau bisa dijelaskan secara lebih rinci di bagian mana terjadi bug

**Comment by yogiperdana** [comment]
Apakah yang dimaskud adalah gambar ini pak
![image](https://user-images.githubusercontent.com/14155050/185017830-2672f5aa-8ffe-4869-a6dd-e2fbab11c55f.png)

**Comment by yogiperdana** [comment]
Jika demikian, hal tersebut diambil berdasarkan status tikar pak (bukan status gizi)

**Comment by yogiperdana** [comment]
Dan terkait jumlah ibu hamil di scorecard apakah untuk ibu yang sudah melahirkan masih terhitung juga di scorecard pak? Yang dihitung hanya ibu hamil saja. Karena saat ini semua data ibu masuk ke dalam scorecard

**Comment by Wiliyantoro** [comment]
> 

Yang ini pak point 2 status gizi anak
![IMG_20220818_091850](https://user-images.githubusercontent.com/44520382/185271268-5cb074c1-36cb-406a-91db-f06355edf883.jpg)

**Comment by Wiliyantoro** [comment]
![IMG_20220818_091829](https://user-images.githubusercontent.com/44520382/185271349-8b862a84-10ed-49da-9f1f-6e61924fe228.jpg)

Yg ini status tikar ukur

**Comment by yogiperdana** [comment]
Disini ada 2 ibpak. Satu ibu hamil dan satu ibu menyusui

![image](https://user-images.githubusercontent.com/14155050/185274850-e1647814-5a45-4afd-9544-035c21a7605f.png)

**Comment by yogiperdana** [comment]
Tapi statusnya di konvergensi saat ini adalah 2 ibu hamil

![image](https://user-images.githubusercontent.com/14155050/185274977-3f50613a-eaca-4a28-b35f-1e3da6b361f7.png)

Pertanyaannya apakah di status konvergensi memang seperti ini pak atau yang dihitung hanya ibu hamil saja pak @Wiliyantoro

**Comment by Wiliyantoro** [comment]
kalau ibu sudah melahirkan , ibu hamil tidak dihitung disana
![67](https://user-images.githubusercontent.com/44520382/185286202-faa4593a-e8cc-4520-b5cc-9d4f3b6e16a2.png)

ini ada yang sudah melahirkan sejak awal dipantau 
![68](https://user-images.githubusercontent.com/44520382/185286265-3e26250a-832f-4419-8206-6a6860e4bea4.png)
di konvergensi jumlahnya 13 jadinya

**Comment by Wiliyantoro** [comment]
![image](https://user-images.githubusercontent.com/44520382/185288021-70e87520-7aec-46c4-a1e7-42756202b832.png)

kalau ini tetap masuk ibu hamil dengan status sudah melahirkan namu isi keterangan ibu nifas

**Comment by yogiperdana** [comment]
> ![image](https://user-images.githubusercontent.com/44520382/185288021-70e87520-7aec-46c4-a1e7-42756202b832.png)
> 
> kalau ini tetap masuk ibu hamil dengan status sudah melahirkan namu isi keterangan ibu nifas

Jadi untuk data di konvergensi desa ibu hamilnya cuma 1 begitu pak @Wiliyantoro? Namun di menu ibu hamil, ibu menyusui juga tetap dimasukkan

**Comment by Wiliyantoro** [comment]
Iya pak di scorecard konvergensinya jika dia sudah melahirkan tidak terhitung, namun masuk ke perhitungan ibu nifas, 
Dalam menu pemantauan dalam satu kuartal dia tetap muncul pak, contoh di kuartal I ( jan - maret ) apabila lahir di bulan tersebut / lahir di tgl 30 januari makan dalam menu pemantauan bulanan ibu hamil dia tetap muncul disana dengan status sdh melahirkan, wajib dipantau dalam rentang quartal tersebut

**Comment by yogiperdana** [comment]
> Iya pak di scorecard konvergensinya jika dia sudah melahirkan tidak terhitung, namun masuk ke perhitungan ibu nifas, Dalam menu pemantauan dalam satu kuartal dia tetap muncul pak, contoh di kuartal I ( jan - maret ) apabila lahir di bulan tersebut / lahir di tgl 30 januari makan dalam menu pemantauan bulanan ibu hamil dia tetap muncul disana dengan status sdh melahirkan, wajib dipantau dalam rentang quartal tersebut

Baik pak. Sepertinya perlu beberapa penyesuaian tes case ketika diuji nanti mas @vickyrolanda dan mas @devrakapriyo

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1239/
