### ISSUE TITLE
Ubah cara membaca Perangkat Anjungan dengan menggunakan ID Browser

### ISSUE THREAD

**Issue by yogiperdana** [OpenSID/OpenSID#5508]

**Comment by yogiperdana** [comment]
Mas @vickyrolanda mohon dibantu konfirmasi ke pelaksana maksudnya ubah cara baca itu apakah cara lama dihapus (ip address dan mac address) atau yang lama tetap ada dan ditambah dengan cara baca baru

**Comment by yogiperdana** [comment]
Apa yang diperbaiki mas @vickyrolanda

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1303
