### ISSUE TITLE
Permintaan fitur: Tampilkan informasi update data pada view statistik di website

### ISSUE THREAD

**Issue by muhtar-coder** [OpenSID/OpenSID#5509]
### Apa kekurangan yg ingin diatasi?

Tidak ada informasi terkait kapan terakhir data di update atau terjadi perubahan isi

### Jelaskan solusi yg diinginkan

1. Terdapat informasi data terakhir di update pada tampilan statistik di website
2. suguhan data dapat di pertanggung jawabkan akurasi dan kenyataan nya

![image](https://user-images.githubusercontent.com/55665526/184628467-93496098-2d94-429f-9126-f584302bc845.png)

### Apakah ada alternatif lain

Tidak ada

### Untuk versi OpenSID mana

22.09 premium

### Informasi tambahan

informasi tanggal update data sesuai perubahan pada data tersebut

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/OpenSID/pull/7597
