### ISSUE TITLE
Bug/error: status penduduk hanya ada pilihan tetap

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#5510]
### Jelaskan error yg dialami

pada saat tambah penduduk di menu keluarga untuk status penduduk hanya ada pilihan TETAP saja bebeda di menu penduduk ada pilihan TETAP dan TIDAK TETAP

### Cara untuk mereplikasi errornya

1. klik menu Kependudukan
2. klik menu Keluarga
3. klik tambah KK baru
4. inputan Status Penduduk hanya ada pilihan TETAP

### Hasil yg diharapkan

ada pilihan TETAP dan TIDAK TETAP

### Tangkapan layar dan log error

* TAMBAH DI MENU PENDUDUK 
<img width="1440" alt="Screen Shot 2022-08-16 at 00 33 05" src="https://user-images.githubusercontent.com/36557759/184686812-9d4983cb-4176-4a0c-b1b5-652c069035ff.png">

* TAMBAH DI MENU KELUARGA
<img width="1440" alt="Screen Shot 2022-08-16 at 00 33 19" src="https://user-images.githubusercontent.com/36557759/184686942-b22a8bd0-a717-4be9-8dda-dd8ef47ca16f.png">

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.08-premium-beta01

**Comment by eddieridwan** [comment]
@devrakapriyo anggota keluarga HARUS penduduk tetap. Tidak boleh penduduk tidak tetap. Jadi ini BUKAN bug. Seharusnya ini dijelaskan di panduan. Harap periksa panduan.

**Comment by ariandii** [comment]
Saat ini masih muncul Status Penduduk "Tidak Tetap" pada saat "Menambah Keluarga Baru" atau "Menambah Anggota Keluarga".

Tambahan:
Saat ini ada penduduk "Tidak Tetap" yang sudah terlanjur masuk ke salah satu KK, maka penduduk tersebut tidak muncul di List Anggota Keluarga sehingga tidak dapat di keluarkan dari KK.

dan Penduduk Tidak Tetap yang sudah terlanjur masuk KK, jika diubah, saat ini kolom status penduduk Disable.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1410
