### ISSUE TITLE
Bug/error: responsive halaman pengaturan surat

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#5513]
### Jelaskan error yg dialami

margin surat jadi hilang, ketika tampilan layar kecil

### Cara untuk mereplikasi errornya

1. layanan surat
2. pengaturan surat

### Hasil yg diharapkan

tampilan responsive

### Tangkapan layar dan log error

![Uploading Screen Shot 2022-08-16 at 13.22.54.png…]()

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.08-premium-rev02

**Comment by yogiperdana** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/1242
