### ISSUE TITLE
Permintaan fitur: penyesuaian map rumah warga terlalu dempet

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#5515]
### Apa kekurangan yg ingin diatasi?

ketika rumah warga terlalu dempet dan zoom map sudah mentok tidak bisa melihat secara detail lokasinya
![image](https://user-images.githubusercontent.com/36557759/184820718-8013cf6e-96b6-4b1b-90f2-92fa0b519729.png)

### Jelaskan solusi yg diinginkan

bisa dizoom lebih detail dari sisi mapnya

### Apakah ada alternatif lain

bisa dizoom lebih detail dari sisi mapnya

### Untuk versi OpenSID mana

v22.08-premium-rev02

### Informasi tambahan

ada di menu 
1. Pemetaan
2. Peta

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1312
