### ISSUE TITLE
Permintaan fitur: Penambahan Download atau View File PDF di Verifikasi D

### ISSUE THREAD

**Issue by langonsari** [OpenSID/OpenSID#5516]
### Apa kekurangan yg ingin diatasi?

Penambahan fitur View atau Download file PDF di Verifikasi Surat yang sudah TTE/ QR Code Verifikasi Aktif untuk validasi keaslian dan originalitas Surat yang di tandatangani secara Elektronik dan di cetak oleh masyarakat.

![image](https://user-images.githubusercontent.com/96863107/184824160-082b3c29-d0cb-40e4-a4f2-6012285ff42f.png)

### Jelaskan solusi yg diinginkan

Penambahan fitur View atau Download file PDF di Verifikasi Surat yang sudah TTE/ QR Code Verifikasi Aktif untuk validasi keaslian dan originalitas Surat yang di tandatangani secara Elektronik dan di cetak oleh masyarakat.

### Apakah ada alternatif lain

QR Code verifikasi langsung menuju ke File PDF yang linknya sudah di encrypt

### Untuk versi OpenSID mana

v22.09-premium

**Comment by andifahruddinakas** [comment]
Untuk surat yang dibuat oleh warga desa, bisa diunduh langsung di layanan mandiri.
