### ISSUE TITLE
Bug: penyesuaian alur surat

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#5518]
### Apa kekurangan yg ingin diatasi?

Atas perubahan alur surat di v22.09 saat ini dimana verifikasi terdapat 3 bagian yaitu Operator, Sekdes & Kades, namun bawaan sistem yang selalu aktif adalah verifikasi operator .

1. Verifikasi Operator masuk ke (Permohonan Surat) setelah Verifikasi Operator baru masuk ke (Arsip).
2. Verifikasi Sekdes dari Verifikasi Operator maka masuk ke sekdes untuk di lakukan pemeriksaan setelah dari sekdes bisa ke Arsip & bisa ke Kades (jika verifikasi kades diaktifkan)
3. Verifikasi Kades dapat surat dari verifikasi Sekdes / Operator

Perubahan yang ingin di lakukan adalah :  
*jika verifikasi sekdes & verifikasi kades di non-aktifkan

- Proses Point 1 diatas tidak perlu dilakukan  verifikasi operator dari (permohonan surat ke arsip)
- Setiap buat surat baru maka yang tampilan halaman arsip tanpa ada menu diatas untuk surat permohonan & arsip

Namun jika sekdes & kades di aktifkan maka berlaku alur seperti saat ini dimana menu permohonan & arsip muncul di bagian atas arsip layanan.

------------------------------------------------------------------------------------------------------------------------------

Khusus surat lama yang belum menggunakan fitur alur surat dan surat baru tanpa verifikasi kades dan sekdes seharusnya masuk kategori ARSIP, sehingga surat tidak perlu diklik 1 persatu masuk ke ARSIP

![image](https://user-images.githubusercontent.com/36557759/185146310-22a1be7b-436d-4ce4-a458-85ee192e3df1.png)

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

v22.08-premium branch rilis-dev

**Comment by yogiperdana** [comment]
Jadi untuk surat lama ketika dicetak langsung masuk ke arsip begitu mas @devrakapriyo? Lalu bagaimana dengan surat rtf yang berasal dari layanan mandiri

**Comment by yogiperdana** [comment]
Duplikat issue https://github.com/OpenSID/OpenSID/issues/5609

**Comment by vickyrolanda** [comment]
untuk issue ini mas @yogiperdana dibuatkan migrasi agar surat lama yang sebelum ada alur surat bisa masuk ke arsip, atau pemeriksaan apakah pengaturan alur surat ada verifikasi sekdes / kades kalo tidak ada maka status surat yang masih ke permohonan agar di ganti kearsip hal ini hanya dikhususkan untuk surat lama mau tinymce maupun rtf.

atau solusi lain agar tidak menjadi ambigu, kita bisa mengubah permohonan surat ini aktif pada saat pemeriksaan sekdes / kades di aktifkan , maka ketika pemeriksaan sekdes / kades tidak aktif maka menu permohonan surat tidak ada langsung ke arsip saja , maka menu yang bagian atas yang diarsip layanan tidak akan tampil.

**Comment by yogiperdana** [comment]
Jadi khusus surat rtf tidak harus diperiksa dan langsung masuk arsip begitu ya mas @vickyrolanda?

**Comment by devrakapriyo** [comment]
mas @vickyrolanda perihal pembahasan di group Divisi Pengembangan, untuk itu agar dilakukan analisis kebutuhannya
karena issue ini masih general

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1378
