### ISSUE TITLE
Permintaan fitur: Buat modul pengelolaan data Prodeskel

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#5519]
### Apa kekurangan yg ingin diatasi?

OpenSID menyediakan analisis master bawaan untuk mengelola data Prodeskel. Panduan (versi lama) ada di https://github.com/OpenSID/OpenSID/wiki/Prodeskel.

<img width="1328" alt="image" src="https://user-images.githubusercontent.com/249563/185258933-f55ae399-e5fe-4016-94dc-5b76d9ada462.png">

Analisis master Prodeskel tsb sudah tidak sesuai dengan isian yang berlaku. Juga rumit untuk digunakan.

### Jelaskan solusi yg diinginkan

Buat modul khusus pengelolaan data Prodeskel. Yaitu fitur baru yang tidak menggunakan master analisis, yang secara khusus menerapkan form isian, pengelolaan dan pelaporan yang dioptimalkan dengan Prodeskel. 

Tambahkan sebagai modul di bawah menu Satu Data. Saat ini menu itu sudah ada satu submenu, yaitu modul DTKS. Jadi modul Prodeskel akan menjadi modul kedua di menu Satu Data.

### Apakah ada alternatif lain

Alternatif lain adalah melengkapi dan perbaharui master analisis yang sudah ada:

1. Perbaharui master analisis Prodeskel (DDK dan DAK) dengan ketentuan terkini.
2. Hubungkan isian penduduk dan keluarga dengan data penduduk dan keluarga yg sudah ada di OpenSID.
3. Terapkan fitur hubungan tambahan yang diperlukan, dengan memperhatikan perlu dibuat berlaku secara umum

### Untuk versi OpenSID mana

Secepatnya, idealnya masuk di 23.02-premium atau paling lambat 23.03-premium.

### Informasi tambahan

Pengisian dan Penginputan data profil Desa dan Kelurahan secara online dilaksanakan melalui situs resmi Prodeskel Kemendagri (https://prodeskel.binapemdes.kemendagri.go.id).

Tapi sebelum dilakukan input data pada aplikasi atau situs Prodeskel Kemendagri tersebut secara online, perlu menyiapkan instrumen pengumpulan data. Itu fungsi modul Prodeskel yang akan dibuat di issue ini. Instrumen pengumpulan data yang dimaksud adalah daftar isian data dasar keluarga, daftar isian potensi desa dan kelurahan serta daftar isian tingkat perkembangan desa dan kelurahan. 

Format isian Prodeskel 2019 dilampirkan berikut ini. 
[format-prodeskel-2019.zip](https://github.com/OpenSID/OpenSID/files/9366706/format-prodeskel-2019.zip)

Keterangan Prodeskel dapat dilihat di :

- https://www.formatadministrasidesa.com/2021/05/profil-desa-kelurahan.html
- https://www.formatadministrasidesa.com/2020/07/data-profil-desa-dan-kelurahan.html

Sebelum menerapkan modul ini, perlu dicari apakah ada ketentuan dan contoh yang lebih baru.

Ini Contoh Format Tabel pengisian Profil Desa

[PROFIL DESA PEMATUNG.pdf](https://github.com/OpenSID/OpenSID/files/9280640/PROFIL.DESA.PEMATUNG.pdf)

Selain form isian, juga perlu disediakan:

1. fitur untuk impor data Prodeskel, sesuai format dari ekspor Prodeskel online
2. fitur untuk ekspor data Prodeskel, mengikut format impor di butir (1)
3. fitur untuk melaporkan data Prodeskel. Layout dan print out nya perlu disamakan dengan laporan cetak dari Prodeskel

**Comment by muhtar-coder** [comment]
mantap ini

**Comment by muhtar-coder** [comment]
tabel layout dan print out nya juga perlu di utamakan agar dapat sama dengan  cetak dari prodeskel

**Comment by mranca** [comment]
sekian di perbaiki pak untuk fitur import data respon pada analisis, ini sangat memudahkan kita di banding harus input data satu persatu

**Comment by Zoel-WB** [comment]
Baik pak, mantap ini....

**Comment by andifahruddinakas** [comment]
https://github.com/OpenSID/modul-prodeskel
