### ISSUE TITLE
Memasukkan Gambar di samping isi artikel

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#552]
Perlu dbuatkan fasilitas insert image yang lebih sederhana lagi sehingga pemula tidak binggung, dan kami juga merasa kesulitan paling tidak seperti contoh dibawah ini
![tangkapan layar 2017-08-13 22 36 17](https://user-images.githubusercontent.com/25834335/29251044-43d67700-8078-11e7-8b9a-f6677ae1b1b7.png)

**Comment by MUHAMMADRANGSEL** [comment]
Issue ini alhamdulillah sudah ada solusinya dan tutorial videonya ada.... Kira2 disini bisa dilampirkan berbentuk video mas eddie

**Comment by MUHAMMADRANGSEL** [comment]
Tapi poto harus kita upload ke google plus baru kita ambil kode link nya

**Comment by MUHAMMADRANGSEL** [comment]
Lebih bagus lagi kalau bisa memasukkan gambar seperti upload gambar utama

**Comment by eddieridwan** [comment]
Sekarang unggah gambar langsung melalui form isian artikel sudah bisa melalui PR #633.

**Comment by oalahbro** [comment]
coba
![issue#25](https://user-images.githubusercontent.com/72176637/134468496-e1b910c5-a51f-4c7e-8abf-a1a9fd6a4a94.png)
