### ISSUE TITLE
Permintaan fitur: SK Pembentukan Desa

### ISSUE THREAD

**Issue by afri18** [OpenSID/OpenSID#5521]
### Apa kekurangan yg ingin diatasi?

agar tidak selalu mencari data/dokumen sk desa

### Jelaskan solusi yg diinginkan

Melengkapi identitas Desa

### Apakah ada alternatif lain

tidak ada

### Untuk versi OpenSID mana

22.09

### Informasi tambahan

Identitas Desa makin lengkap
![image](https://user-images.githubusercontent.com/6611881/185522789-96f75b69-b515-4caa-847f-0c64b2dd9dde.png)

**Comment by andifahruddinakas** [comment]
Duplicate of https://github.com/OpenSID/OpenSID/issues/5626
