### ISSUE TITLE
Bugs: Footer surat mepet dengan isi surat

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#5522]
Saat cetak surat dengan tinymce yang menggunakan footer. Footer tsb menempel dengan isi surat. Yang harusnya berada di bawah (tempat yang telah ditentukan).

[surat_raw_tinymce_5201142005716996_2022-08-19_1.pdf](https://github.com/OpenSID/OpenSID/files/9379934/surat_raw_tinymce_5201142005716996_2022-08-19_1.pdf)

Harusnya
[surat_raw_tinymce_5201142005716996_2022-08-19_2.pdf](https://github.com/OpenSID/OpenSID/files/9379937/surat_raw_tinymce_5201142005716996_2022-08-19_2.pdf)

**Comment by balongbesuk** [comment]
sekalian isiny ganti dg trademark opensid 🤔

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1250
