### ISSUE TITLE
Bug/keamanan: demosid terkena hack

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#5523]
### Jelaskan error yg dialami

Terdapat celah keamanan xss melalui form input Keuangan Manual.

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

- demosid dapat diakses dengan baik
- Perbaiki / validasi form yang terdapat celah keamanan.

### Tangkapan layar dan log error

![1DF419C6-4FD9-4C44-9D04-D702D4C75444](https://user-images.githubusercontent.com/36557759/185776180-5d829e34-f779-400a-bc30-17d0498b3f6e.jpeg)

### Rilis Versi OpenSID

Rilis Umum

### Versi OpenSID

-

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui commit https://github.com/OpenSID/OpenSID/commit/74a2c18c7df92fa0a2b3bd21f56fc1a03fc3e00c
