### ISSUE TITLE
[TinyMCE] Tambah kode isian anggota keluarga sesuai ID kepala Keluarga

### ISSUE THREAD

**Issue by muhtar-coder** [OpenSID/OpenSID#5524]
### Apa kekurangan yg ingin diatasi?

di dalam pembuatan template surat menggunakan TinyMCE belum ada kode isian untuk menambahkan anggota keluarga ke dalam tabel di surat yang di buat

![image](https://user-images.githubusercontent.com/55665526/185798636-6a30ca12-855b-4ea7-a3d5-c7ea9e49014f.png)

### Jelaskan solusi yg diinginkan

di sediakan kode isian pilihan untuk bisa menambahkan anggota keluarga seperti pada umumnya di beberapa surat sesuai kebutuhan.

contoh kebutuhan tabel anggota keluarga :
![image](https://user-images.githubusercontent.com/55665526/185798625-7fb9313c-cce1-47fb-861d-8be1b072ab32.png)

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

22.09-premium

### Informasi tambahan

-

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1495

**Comment by vickyrolanda** [comment]
Mas @vickyrolanda, @agungsugiarto, setelah saya gunakan kode isian ini beberapa hal yang akan jadi kendala : 
1. Karena data anggota di buat statis dalam bentuk generate hmtl, pengguna tidak bisa mengubah isi maupun letak data yang digenerate tsb.
2. Di cek setelah generate, nomer selalu dimulai dari angka 2.
3. Tidak bisa menyesuaikan style lainnya yang digunakan di editor, misalnya bold, rata-tegah, dll, sehingga jika ingi mengubah data dari kode isian pengguna harus melaporkannya terlebih dahulu.
![kode_isian_1](https://user-images.githubusercontent.com/57283157/197663069-4fee2e13-941b-4ce3-80e2-4e689ec1314e.jpg)


Solusi : 
1. Buat kode isian anggota ini dinamis.
2. Misalnya : 
- Penduduk (nama, ttl, pekerjaan, pendidikan, dll)
- Anggota (nama_(x), ttl_(x), pekerjaan_(x), pendidikan_(x), dll) dengan maksimal 10, sama halnya dengan kode isian yang ada di surat jenis RTF.
![kode_isian_2](https://user-images.githubusercontent.com/57283157/197663159-1540eb55-cf2f-4e2a-974e-85027ab4c844.jpg)

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1531
