### ISSUE TITLE
OPENSID: Bug/error: Tidak dapat mengakses layanan pelanggan setelah masukan token (umum)

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#5525]
### Jelaskan error yg dialami

 Tidak dapat mengakses layanan pelanggan setelah masukan token.

### Cara untuk mereplikasi errornya

1. Pasang opensid umum
2. Masukan token
3. Masuk ke halaman layanan pelanggan

### Hasil yg diharapkan

halaman dapat tampil sebagai mana mestinya

### Tangkapan layar dan log error

![photo_6311949217865773984_y](https://user-images.githubusercontent.com/36557759/185834907-2327c706-d0c2-44fa-b172-2eafe2fc86ed.jpg)

### Rilis Versi OpenSID

Rilis Umum

### Versi OpenSID

 22.08

**Comment by andifahruddinakas** [comment]
![layanan 1](https://user-images.githubusercontent.com/57283157/185844285-8dd97598-8c8f-49e6-9fcb-af961dcdd026.png)

Cek di layanannya.

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/OpenSID/commit/6d1cade6d5b83d222bda8ac7febb0cbd5b98bf44
