### ISSUE TITLE
Permintaan fitur: sediakan fitur import pada analisis

### ISSUE THREAD

**Issue by mranca** [OpenSID/OpenSID#5526]
### Apa kekurangan yg ingin diatasi?

harusnya menginput data membuat proses data menjadi lama 

### Jelaskan solusi yg diinginkan

sediakan fitur import data respon pada analsis sehingga kita nantinya bisa mengimport data analisis sdgs yang sudah di donlowad melalui dashboard sdgs ataupun data lainnya 

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

premium 22.09

### Informasi tambahan

-

**Comment by eddieridwan** [comment]
Sudah ada:

https://github.com/OpenSID/OpenSID/wiki/Analisis

![image](https://user-images.githubusercontent.com/249563/186047463-e13a819d-c8c1-4ead-beea-2f7aa3787960.png)
