### ISSUE TITLE
Bug/error: Surat TinyMCE : Edit sebelum cetak PDF tidak berfungsi

### ISSUE THREAD

**Issue by ai-skematik** [OpenSID/OpenSID#5527]
### Jelaskan error yg dialami

Saat membuat surat menggunakan tinyMCE dan terdapat kesalahan dan diperbaiki saat preview sebelum cetak PDF tetapi hasil cetak PDF tetap dengan isian sebelum di edit. 

### Cara untuk mereplikasi errornya

Buat Surat menggunakan tinyMCE kemudian simpan, saat tampil preview surat lakukan edit pada isi surat kemudian cetak pdf. lihat halsilnya apakah yang tercetak isi sebelum di edit atau sudah di edit saat preview ?

### Hasil yg diharapkan

Hasil cetak pdf sesuai dengan preview, jika preview diedit maka hasil cetak pdf adalah hasil edit dipreview.

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

22.08-Premium

### Tema Yang Digunakan

-

### Informasi tambahan

-

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1258
