### ISSUE TITLE
Bug/error: Pengaturan masa berlaku tidak berfungsi pada surat pengantar (cek juga semua surat)

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#5528]
### Jelaskan error yg dialami

Pada saat mencetak surat tanggal berlaku tidak tampil data nya, padahal sudah diatur pada pengaturan surat.

### Cara untuk mereplikasi errornya

1. Masuk ke halaman cetak surat
2. pilih surat pengantar > masuk ke form
3. isi data
4. cetak surat

### Hasil yg diharapkan

masa berlaku tampil sesuai pengaturan pada surat tersebut. cek juga pada keseluruhan surat, karena dialporkan surat yang lain pun mengalami bug tersebut.

### Tangkapan layar dan log error

![photo_6064327491209770046_y](https://user-images.githubusercontent.com/36557759/186299905-32767983-154f-4426-a943-19dc49419780.jpg)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

 22.08-premium-rev03

**Comment by andifahruddinakas** [comment]
Mas @devrakapriyo, sesuaikan dlu pengaturan untuk menampilkan data masa berlakuk surat. Jika di isi 0, maka tidak tampil walaupun di rtf sudah disematkan kode_isiannya.

![ini](https://user-images.githubusercontent.com/57283157/186301673-ddb2927f-e197-4849-9001-8dd4ab8d4f97.png)

![ini 2](https://user-images.githubusercontent.com/57283157/186301719-4324fee2-4be3-46d9-9272-9307558ee667.png)

![ini 3](https://user-images.githubusercontent.com/57283157/186301783-62f7077c-497a-4f0c-b006-e650625f8ec0.png)

**Comment by andifahruddinakas** [comment]
Pastikan juga, template buatan desa tsb mengikuti aturan terbaru.

**Comment by andifahruddinakas** [comment]
Untuk selanjutnya bisa sertakan pengaturan suratnya agar mudah di cek. Sy cek beberapa kali, hanya tampil jika masa berlaku di isi > 1 dan jenis surat .rtf saja.

**Comment by devrakapriyo** [comment]
> Untuk selanjutnya bisa sertakan pengaturan suratnya agar mudah di cek. Sy cek beberapa kali, hanya tampil jika masa berlaku di isi > 1 dan jenis surat .rtf saja.

cc @vickyrolanda ini bug atau fitur mas?

**Comment by eddieridwan** [comment]
@devrakapriyo @vickyrolanda @andifahruddinakas : ingat, kalau menimbulkan kebingungan dan kesalahan pengguna, **selalu** harus diperbaiki -- misalnya dengan validasi, notifikasi atau perancangan ulang antar muka dengan pengguna.

**Comment by andifahruddinakas** [comment]
> > Untuk selanjutnya bisa sertakan pengaturan suratnya agar mudah di cek. Sy cek beberapa kali, hanya tampil jika masa berlaku di isi > 1 dan jenis surat .rtf saja.
> 
> cc @vickyrolanda ini bug atau fitur mas?

ini saran saat buat issue, biar yang kerjakan issue karena ada bagian yang tidak lengkap.

**Comment by andifahruddinakas** [comment]
> @devrakapriyo @vickyrolanda @andifahruddinakas : ingat, kalau menimbulkan kebingungan dan kesalahan pengguna, **selalu** harus diperbaiki -- misalnya dengan validasi, notifikasi atau perancangan ulang antar muka dengan pengguna.

ini bug, yang dimana rtf dan tinymce kondisinya tidak konsisten.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1257
