### ISSUE TITLE
Bug/error:  tidak tampil penanda tangan surat, dan ketika klik barcode masuk k halaman error

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#5530]
### Jelaskan error yg dialami

Tidak tampil penanda tangan surat, dan ketika klik barcode masuk k halaman error.

Periksa juga modul-modul yang menggunakan jabatan.

### Cara untuk mereplikasi errornya

Buat Surat Baru > cetak.

Lalu,
1. Halaman Layanan surat > arsip layanan
2. Lihat ditanda tangani oleh

Serta:
1. Halaman Layanan surat > arsip layanan
2. Klik barcode 

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

![ttd](https://user-images.githubusercontent.com/36557759/186344812-992320d9-9384-4772-a91e-b1a4f1eab374.PNG)

![klik barcode surat](https://user-images.githubusercontent.com/36557759/186344847-28abf509-5477-42e9-9556-9e2d5624b271.PNG)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

OpenSID v22.08-premium-beta03

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui commit https://github.com/OpenSID/premium/commit/1252fbb6b9a0c480920f2cbd3b84f7c785586282
