### ISSUE TITLE
Permintaan fitur: Format F2.01 di kabupaten saya tidak sesuai dengan bawaan opensid

### ISSUE THREAD

**Issue by jonitrisulasmono** [OpenSID/OpenSID#5531]
### Apa kekurangan yg ingin diatasi?

Format F2.01 untuk kelahiran yang tersedia di openSID tidak sama dengan format yang ditentukan oleh dinas dukcapil di kabupaten kami (kab. luwu timur)

### Jelaskan solusi yg diinginkan

Berharap format f2.01 bisa sesuai dengan format kabupaten agar layanan surat dapat digunakan.

### Apakah ada alternatif lain

tidak ada

### Untuk versi OpenSID mana

v22.08

**Comment by balongbesuk** [comment]
lampirkan juga format yg dmaksud

**Comment by andifahruddinakas** [comment]
Duplicate issue https://github.com/OpenSID/OpenSID/issues/5259
