### ISSUE TITLE
Permintaan fitur: Merubah tombol simpan menjadi lanjut pada saat pembuatan surat tinymce

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#5532]
### Apa kekurangan yg ingin diatasi?

Untuk memudahkan pengguna pada saat pembuatan surat tinymce terkadang lupa untuk mengatur templatenya namun ketika klik simpan halaman diam tanpa ada pembaritahuan harus mengisi template , kecuali klik tab template baru kelihatan pemberitahuan utnuk mengisi kolom template. Sehingga sebagai pengguna lebih baik diarahkan saja apa selanjutnya yang harus di isikan.

### Jelaskan solusi yg diinginkan

1. Pada Saat di Tab Umum Ubah Tombol Simpan Menjadi "Selanjutnya" 
<img width="787" alt="image" src="https://user-images.githubusercontent.com/59082428/186981454-c2b659a7-c110-41c4-958f-96e00a05132f.png">

2. Ketika diklik tab akan berubah menjadi tab "Template" ditab ini juga ubah tombol Simpan menjadi "Selanjutnya" 
<img width="784" alt="image" src="https://user-images.githubusercontent.com/59082428/186981648-1a773402-1427-4eb2-824e-39ca38fbef8b.png">

3. Ketika diklik tab akan berubah menjadi tab "Form isian" ditab ini baru tombol "Simpan"
<img width="795" alt="image" src="https://user-images.githubusercontent.com/59082428/186981868-9d211f5a-8727-48a0-ab9b-f6be430dcbe4.png">

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

v22.08-premium

### Informasi tambahan

Penerapan fitur ini untuk meningkatkan kemudahan bagi pengguna.

**Comment by andifahruddinakas** [comment]
Untuk solusi ini akan merepotkan pengguna saat mau melakukan update kode isian, karena harus menekan tombol selanjutnya sebanyak 2/3 kali. Solusi dari sy, bisa cek PR https://github.com/OpenSID/premium/pull/1287.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1287
