### ISSUE TITLE
Bug/error: tampil script json di halaman login kehadiran

### ISSUE THREAD

**Issue by apidong** [OpenSID/OpenSID#5533]
### Jelaskan error yg dialami

-

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

data json tidak tampil

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/20056421/187073988-96498a64-ef04-46cf-9f57-2f279a4f4ee2.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

22.09 premium-beta4

### Tema Yang Digunakan

-

### Informasi tambahan

-

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1265
