### ISSUE TITLE
Bug/error: kolom jabatan [object, object] di kolom rekapitulasi kehadiran

### ISSUE THREAD

**Issue by apidong** [OpenSID/OpenSID#5534]
### Jelaskan error yg dialami

-

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/20056421/187074142-ddf2a2c8-0c6c-4fcb-a004-cbd3549b8574.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

22.09 premium-beta4

### Tema Yang Digunakan

-

### Informasi tambahan

-

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1266
