### ISSUE TITLE
Bug/error: modul perangkat pada layanan mandiri error

### ISSUE THREAD

**Issue by apidong** [OpenSID/OpenSID#5535]
### Jelaskan error yg dialami

error halaman 500

### Cara untuk mereplikasi errornya

- login ke layanan mandiri
- masuk ke modul perangkat

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/20056421/187074871-ebcfcf4b-4b64-45a0-991b-95e379373206.png)

Log error : Severity: error --> Exception: SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'pamong_id' in field list is ambiguous (SQL: select `pamong_id`, `pamong_nama`, `jabatan_id`, `ref_jabatan`.`nama` as `pamong_jabatan`, `pamong_nip`, `pamong_niap`, `pamong_ttd`, `pamong_ub`, IF(tweb_desa_pa
ong.id_pend IS NULL, tweb_desa_pamong.pamong_nama, tweb_penduduk.nama) AS pamong_nama from `tweb_desa_pamong` left join `kehadiran_perangkat_desa` as `k` on `tweb_desa_pamong`.`pamong_id` = `k`.`pamong_id` left join `kehadiran_pengaduan` as `p` on `tweb_desa_pamong`.`pamong_id` = `p`.`id_pamong` left join `tweb_penduduk` on `tweb_penduduk`.`id` = `tweb_desa_pamong`.`id_pend` left join `ref_jabatan` on `ref_jabatan`.`id` = `tweb_desa_pamong`.`jabatan_id` where `pamong_status` = 1 and `kehadiran` = 1) /home/beta.opendesa.id/public_html/vendor/illuminate/database/Connection.php 712

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.09-premium-beta4

### Tema Yang Digunakan

-

### Informasi tambahan

-

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1270
