### ISSUE TITLE
Bug/error: file lampiran pada jenis surat rtf tidak bisa tergenerate

### ISSUE THREAD

**Issue by apidong** [OpenSID/OpenSID#5536]
### Jelaskan error yg dialami

-

### Cara untuk mereplikasi errornya

1. pergi ke modul layanan surat > cetak surat
2. buat surat yang menggunakan lampiran. misal surat biodata penduduk
3. isi form 
4. unduh rtf
5. halaman akan tampil isian dari lampiran tetapi di arsip, tombol unduh lampiran tidak ada.
![image](https://user-images.githubusercontent.com/20056421/187075791-f3252f88-0555-4aca-8905-21d48e2965c6.png)

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

Severity: error --> Exception: Call to undefined method Surat_model::penandatangan_lampiran() /home/beta.opendesa.id/public_html/template-surat/surat_bio_penduduk/f-1.01.php 460
![image](https://user-images.githubusercontent.com/20056421/187076072-edcea441-a531-402e-8d5e-3574cbe77cb1.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

22.09 premium-beta4

### Tema Yang Digunakan

-

### Informasi tambahan

-

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1264
