### ISSUE TITLE
Perbaiki Notifikasi Setelah Pengajuan Surat Raw Tiny MCE

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#5538]
### Jelaskan error yg dialami

Notifikasi yang diterima jika ada pengajuan surat seperti dibawah ini:

Segera cek Halaman Admin, penduduk atas nama ADI SUNARSO telah **mengajukan Surat Raw Tinymce** melalui Layanan Mandiri pada tanggal 26 Agustus 2022 14:31:21

Kalimat diatas yang di cetak tebal perlu diperbaiki, atau jika memungkinkan, disebut Surat yg diajukan. misalnya seperti dibawah ini:
Segera cek Halaman Admin, penduduk atas nama ADI SUNARSO telah mengajukan Surat Keterangan Usaha melalui Layanan Mandiri pada tanggal 26 Agustus 2022 14:31:21

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

Perbaiki kalimat notifikasi saat ada pengajuan surat tiny mce

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

 22.08-premium-rev04

**Comment by andifahruddinakas** [comment]
Mas @devrakapriyo, saya rasa ini sebuah permintaan bukan bug. Cek apakah hal ini menyebabkan error? kalau hanya pesan yang dikirim tidak sesuai dengan yang diinginkan, sebaiknya di buatkan issue agar bisa menyesuaikan isian pesan yang dikirim ke telegram untuk surat maupun lainnya.

**Comment by devrakapriyo** [comment]
ok mas, saya ubah menjadi fitur

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1343
