### ISSUE TITLE
Bug/error: Pada peta tulisan rt/rw menjadi tidak rapih, dan luas wilayah nya tidak ada

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#5540]
### Jelaskan error yg dialami

Laporan dari pak @YUD1K
Pada peta tulisan rt/rw menjadi tidak rapih, dan luas wilayah nya tidak ada.

### Cara untuk mereplikasi errornya

1. Menu Pemetaan > Peta
2. Aktifkan centang mapbox satelit, peta wilayah desa sampai peta wilayah rt

### Hasil yg diharapkan

Tampilan rapih dan luas wilayah tampil.

### Tangkapan layar dan log error

![photo_6069126597472006525_x](https://user-images.githubusercontent.com/36557759/187230885-84e1fbef-1f30-460b-a6be-59ed46712b05.jpg)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

22.08-premium-rev04

**Comment by andifahruddinakas** [comment]
Mas @devrakapriyo, untuk issue permintaan luas peta pada wilayah desa, dusun, rt, dan rw bisa dibuatkan issue terpisah (jangan digabung) karena di bug-fix belum ada cara menampilkan luas peta (ada di rilis-dev).

Untuk masalah judul penulisan rt/rw jadi tidak rapi, bisa diperjelas lg. Sertakan SS bagian yang bermasalah (tandai) dan beri sugesti seperti apa yang diharapkan.

**Comment by devrakapriyo** [comment]
iya mas, sesuai gambar peta yang saya lampirkan jadi penulisan rt/rw menjadi menumpuk/tidak rapih mas

**Comment by devrakapriyo** [comment]
baik mas, saya akan buatkan masing-masing issue

**Comment by andifahruddinakas** [comment]
> iya mas, sesuai gambar peta yang saya lampirkan jadi penulisan rt/rw menjadi menumpuk/tidak rapih mas

itu karena wilayahnya kecil dan pin(lokasinya)nya berdekatan. Bawaan dari librarinya, di tampilkan sesuai daerah yang ditandai.

**Comment by devrakapriyo** [comment]
apakah memungkinkan mas dapat di zoom in lagi petanya? apa masukan ke permintaan fitur saja mas?

Untuk zoom peta saat ini mengikuti zoom untuk wilayah desanya. Walaupun yang di pilih untuk ditampilkan adalah wilayah di bawahnya (dusun/rt/rw) akan tetap menggunakan zoom desa.

Dibuatkan saja issue permintaan fiturnya, agar zoom mengikuti wilayah yang dipilih.
