### ISSUE TITLE
Bug/error: Surat rtf error saat pengaturan masa berlaku 0

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#5541]
### Jelaskan error yg dialami

Surat rtf error saat pengaturan masa berlaku 0. 

### Cara untuk mereplikasi errornya

1. Pergi ke layanan surat > pengaturan surat
2. atur masa berlaku salah satu surat menjadi 0

3. masuk ke halaman cetak surat
4. pilih salah satu surat untuk dicetak
5. klik unduh rtf > lihat hasilnya/buka file yang telah diunduh

### Hasil yg diharapkan

jika masa berlaku 0, maka masa berlaku di rtf bisa **dihilangkan** atau tanda **strip** saja **-** atau bisa dengan cara lainnya yang pasti tidak menampilkan scrypt seperti **[mulai_berlaku] s/d [tgl_akhir]**

### Tangkapan layar dan log error

![berlaku](https://user-images.githubusercontent.com/36557759/187244200-0f05a77e-8ff0-4d80-9172-cf52eb24479c.PNG)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

 22.08-premium-rev04

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1267
