### ISSUE TITLE
Bug/error: Notifikasi Telegram Tidak Terkirim 

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#5542]
### Jelaskan error yg dialami

- [x] Notfikasi telegram tidak terkirim padahal sudah di set token telegram yang benar
- [x] Pada pengaturan Telegram Token masih bisa input token yang tidak valid sehingga pengaruh di verifikasi surat
- [x] Sama dengan pengaturan point 2 , masih bisa input id telegram yang tidak valid di pengguna sehingga ketika dikirim verifikasi surat maka tidak berhasil.
- [x] Bagian Pengguna Error ketika membuat id telegram lebih dari 9 digit  sudah diperbaiki di pr https://github.com/OpenSID/premium/pull/1269

<img width="814" alt="image" src="https://user-images.githubusercontent.com/59082428/187255556-b2addd42-82e1-4585-8fec-ee3a81aa1581.png">

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

1. Notifikasi harus bisa dikirim setiap verifikasi surat dan permohonan surat
2. Untuk menghindari bug ketika pengaturan tidak valid maka dibuat pesan error saat menyiman pengaturan token jika token tidak valid.

### Tangkapan layar dan log error

<img width="814" alt="image" src="https://user-images.githubusercontent.com/59082428/187255556-b2addd42-82e1-4585-8fec-ee3a81aa1581.png">

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.08-premium

**Comment by andifahruddinakas** [comment]
1. Untuk pengisian pengaturan telegram sudah ada panduannya yang perlu di ikuti untuk mengaktifkan fitur ini. (https://github.com/OpenSID/OpenSID/wiki/Bot-Notifikasi-Telegram)
2. Untuk merubah (menambahkan validasi input lebih detail) pada pengaturan aplikasi, perlu menambahkan komponen lain. (bisa menyebabkan error di tempat lain krn menggunakan view global). Perlu dilakukan test yang lebih lama. (sy coba buatkan dlu, tp digabungkan di rilis selanjutnya).
3. Untuk verifikasi akun telgram bisa menggunakan cara yang diterapkan di layanan mandiri (issue penambahan fitur)
4. Sebaiknya issue di pisah2, walau topiknya sama (mengenai telgram)

Untuk issue ini hanya dilakukan perbaikan validasi input, dimana PR https://github.com/OpenSID/premium/pull/1269 hanya susulan perbaikan dari fitur yang telah ditambahkan.

**Comment by apidong** [comment]
untuk verifikasi id telegram sudah saya buatkan pr pak
https://github.com/OpenSID/premium/pull/1272

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1272
