### ISSUE TITLE
Permintaan fitur: Pencarian Spesifik Status Kawin Tercatat dan Tidak Tercatat

### ISSUE THREAD

**Issue by usmanrahdi** [OpenSID/OpenSID#5543]
### Apa kekurangan yg ingin diatasi?

mohon tambah pencarian spesifik untuk data warga pada status kawin tercatat dan tidak tercatat, hal ini mempermudah desa yang sedang mendata warga nya yang ditanya oleh KUA setempat untuk mengikuti Kegiatan Pelayanan Terpadu Persidangan Isbat Nikah
![image](https://user-images.githubusercontent.com/95505631/187342205-b7268854-c6f7-4875-a980-7b975c333ee1.png)

### Jelaskan solusi yg diinginkan

tambahkan pada menu Kependudukan pada pencarian spesifik
![image](https://user-images.githubusercontent.com/95505631/187343120-b7e49da8-c893-483b-aa76-e84c829fc336.png)

### Apakah ada alternatif lain

Mohon Tambah Fitur Tersebut pada Update selanjutnya

### Untuk versi OpenSID mana

v22.09

**Comment by syahransaputra** [comment]
UP @vickyrolanda @eddieridwan
Issue ini sangat penting diterapkan Semoga parameter tersebut dapat diterapkan di Versi update Premium selanjutnya.
