### ISSUE TITLE
Permintaan fitur: Paginasi di halaman website /peraturan_desa

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#5544]
### Jelaskan error yg dialami

Paginasi di halaman website /peraturan_desa tidak berfungsi

### Cara untuk mereplikasi errornya

1. tambah sk peraturan desa lebih dari 10 data
2. masuk ke halaman website /peraturan_desa

### Hasil yg diharapkan

paginasi berfungsi dengan baik

### Tangkapan layar dan log error

![pagg](https://user-images.githubusercontent.com/36557759/187342900-72d01c1f-faf1-4e50-a26b-65bb005d4eeb.PNG)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

 22.08-premium-rev04

**Comment by andifahruddinakas** [comment]
Mas @devrakapriyo, usahakan cek versi sebelum2nya. Jika sebelumnya ada dan di versi terbaru hilang (krn tidak sengaja atau lainnya) bisa di kateogirkan bug. Tapi kalau dari awal memang sudah tidak ada dan ingin menambahakan paginasi tsb, dibuat sebagai permintaan fitur.

**Comment by andifahruddinakas** [comment]
Bisa bandingkan dengan fitur 6 bulan lalu, di https://demosid.opendesa.id/

**Comment by devrakapriyo** [comment]
baik mas, sepertinya di masukan ke permintaan fitur
karena dari versi 6 bulan yang lalu belum ada paginasi

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1283
