### ISSUE TITLE
Bug/error: Judul peraturan desa tidak tersimpan / kosong

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#5545]
### Jelaskan error yg dialami

saat menambah peraturan desa, judulnya tidak tersimpan / menjadi kosong

### Cara untuk mereplikasi errornya

1. buku administrasi desa
2. administrasi umum
3. tambah sk kades/perdes baru
4. simpan 

### Hasil yg diharapkan

data dapat tersimpan dengan baik

### Tangkapan layar dan log error

![skk](https://user-images.githubusercontent.com/36557759/187343593-a3f275ad-8a3c-41d4-bc7b-5b91384c3604.PNG)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

 22.08-premium-rev04

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1268
