### ISSUE TITLE
Bug/error: urutan sturuktur anggota pemerintah tidak sesuai yang di tentukan 

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#5548]
### Jelaskan error yg dialami

urutan sturuktur anggota pemerintah tidak sesuai yang di tentukan 

### Cara untuk mereplikasi errornya

1. klik menu Buku Administrasi Desa
2. klik menu Administrasi Umum
3. klik tab Buku Aparat Pemerintah Desa
4. tentukan urutan anggota desa

### Hasil yg diharapkan

harusnya mengikuti urutan yang ada di admin

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/36557759/187356446-8d9d2b08-dd35-4c98-b7c0-086ba8ad382f.png)
sesuai gambar di atas, seharusnya urutan nomor 4 itu Syafi

![image](https://user-images.githubusercontent.com/36557759/187356544-ab399213-0f6f-4f9c-9a87-dc6efd5d1243.png)
sedangkan ini Supardi

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.08-premium-rev04

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1264
