### ISSUE TITLE
Permintaan fitur: responsive navbar OpenSID

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#5549]
### Apa kekurangan yg ingin diatasi?

icon pada navbar jika bertambah akan menutupi tampilan, harap agar di rapihkan saat responsive di HP

![image](https://user-images.githubusercontent.com/36557759/187435729-08a1c390-2838-4279-89c6-4f11efba2381.png)

![image](https://user-images.githubusercontent.com/36557759/187435744-fd5b35b3-971e-4cc9-8eee-30986787447a.png)

### Jelaskan solusi yg diinginkan

di buatkan 1 menu icon untuk menampilkan semua icon saat responsive 

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

22.09-premium

**Comment by andifahruddinakas** [comment]
Mas @vickyrolanda, bagusnya dibuat seperti apa? apakah perlu ada yang dihilangkan, atau bagaimana?

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1323

**Comment by devrakapriyo** [comment]
dari pembahasan di group Pengelolaan Hosting ada beberapa saran dari pak @ariandii untuk di sesuaikan
- pada saat dropdown masing masing icon di beri label nama, jangan icon saja 
- icon profile, icon FAQ OpenSID dan icon lainnya di masukan ke list dropdown
![189571372-ea0aae1f-39b4-4cbf-95a8-ebebb5fe8fe4](https://user-images.githubusercontent.com/36557759/190317691-47ca7f83-dcb7-43eb-99a0-930d21d2caf0.png)

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1357
