### ISSUE TITLE
Bug/error: Nama pejabat di pengguna tidak tampil ketika pejabat dari penduduk desa.

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#5550]
### Jelaskan error yg dialami

1. Katika Pemerintah desa diambil dari data penduduk desa 
<img width="792" alt="image" src="https://user-images.githubusercontent.com/59082428/187594957-54407f99-e848-4448-bad2-ee65adb89597.png">

2. Di menu pengguna nama pejabat tidak tampil
<img width="803" alt="image" src="https://user-images.githubusercontent.com/59082428/187594989-1684fb9d-4266-4da6-8555-1b8e59383292.png">

### Cara untuk mereplikasi errornya

1. Ke menu pemerintah desa, pilih warga penduduk desa
2. Pergi ke menu pengguna lalu pilih pejabat

### Hasil yg diharapkan

harusnya tampil nama pejabat mau dari luar penduduk ataupun dari dalam penduduk.

### Tangkapan layar dan log error

<img width="803" alt="image" src="https://user-images.githubusercontent.com/59082428/187595132-1e131b04-f61a-495a-8d66-0e50dbf159d9.png">

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.08-premium

**Comment by apidong** [comment]
sudah diperbaiki melalui https://github.com/OpenSID/premium/pull/1274
