### ISSUE TITLE
Bug/error: Peserta dan program yang telah dihapus tidak terhapus di opendk

### ISSUE THREAD

**Issue by yogiperdana** [OpenSID/OpenSID#5552]
### Jelaskan error yg dialami

Peserta dan program yang telah dihapus tidak terhapus di opendk

### Cara untuk mereplikasi errornya

Sinkronisasi program bantuan ke opendk

### Hasil yg diharapkan

Peserta dan program bantuan terhapus

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.08

**Comment by apidong** [comment]
sudah diperbaiki di https://github.com/OpenSID/premium/pull/1277
