### ISSUE TITLE
Permintaan fitur: Tambahkan Font Bookman Old Style ke pengaturan Surat TinyMCE

### ISSUE THREAD

**Issue by WAHYUDIK** [OpenSID/OpenSID#5555]
### Apa kekurangan yg ingin diatasi?

saat ini jenis font yang ada di pengaturan surat TinyMCE belum ada jenis font Bookman Old Style

### Jelaskan solusi yg diinginkan

tambahkan font jenis Bookman Old Style 

### Apakah ada alternatif lain

ada beberapa kabupaten jenis font untuk persuratan diwajibkan menggunakan jenis font Bookman Old Style

### Untuk versi OpenSID mana

22.09 premium

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1348
