### ISSUE TITLE
Bug/error: Tidak bisa input nilai valid sesuai anggaran pada menu pembangunan

### ISSUE THREAD

**Issue by mah-mudi** [OpenSID/OpenSID#5556]
### Jelaskan error yg dialami

Tidak bisa input nilai valid sesuai anggaran pada menu pembangunan, hanya diberi pilihan nilai terdekat.
Jika nominal anggaran yg dipublish tdk sesuai dg anggaran APBDesa akan mengakibatkan miss infomasi.

### Cara untuk mereplikasi errornya

1. Pergi Menu Pembangunan
2. Klik Tambah Data
3. Isi Data Pembangunan, ketika memasukkan nilai 106780860 pada sumber biaya misal sumber biaya Pemerintah dan melengkapi isian data dan foto
4. Klik Simpan dan gak bisa simpan , maka akan ada peringatan "masukkan nilai yang valid. dua nilai yang valid terdekat adalah 106780000 dan 106781000"

### Hasil yg diharapkan

Dapat input nilai valid sesuai anggaran yang tertulis di APBDesa (meskipun koma) ketika mengisi nilai anggaran pada menu pembangunan.

### Tangkapan layar dan log error

![bug1](https://user-images.githubusercontent.com/57661283/187912849-d66724ae-7da2-4e83-aa7d-b84e1a615276.png)

### Rilis Versi OpenSID

Rilis Umum

### Versi OpenSID

v22.09

### Tema Yang Digunakan

DeNava v1.2

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki di rilis 2203-premium dan akan digabungkan di rilis umum-v2210

Cek https://github.com/OpenSID/OpenSID/wiki/Rilis-Umum-Yang-Akan-Datang#rilis-umum-v2210--2203-premium
