### ISSUE TITLE
Bug/error: perbaiki tata bahasa dan ejaan

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#5557]
### Jelaskan error yg dialami

![402693EE-B85E-4DB5-A406-771CF2B9AA8C](https://user-images.githubusercontent.com/36557759/187939717-616b6cda-8f9f-456d-842c-b15b548d8f90.jpeg)

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.09-premium

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1281
