### ISSUE TITLE
Bug/error: bulanan ibu hamil,, setelah edit tanggal inputnya berubah ke hari ini dan tidak bisa di perbaiki ke tanggal seharusnya

### ISSUE THREAD

**Issue by muhtar-coder** [OpenSID/OpenSID#5559]
### Jelaskan error yg dialami

tanggal hasil input berubah ke tanggal hari ini dan tidak ada tombol ubah tanggal untuk perbaikan 

### Cara untuk mereplikasi errornya

setelah data data KIA terisi, coba masuk ke isian ibu hamil  kemudian lakukan edit pada hasil isian yang udah ada dan hasilnya tanggal periksa menjadi kembali ke tanggal hari ini

![image](https://user-images.githubusercontent.com/55665526/188082972-454db6a4-dd00-4dcb-8ede-a8c4e72df32b.png)

### Hasil yg diharapkan

hasil inputan tetap normal seperti inputan sebelumnya,, atau bisa juga sediakan tombol untuk merubah tanggal nya

### Tangkapan layar dan log error

ada di atas

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

22.09 premium

### Tema Yang Digunakan

Denatra

### Informasi tambahan

-

**Comment by devrakapriyo** [comment]
kolom Tanggal Periksa yang sebelumnya di isi tgl 1 September setelah di edit menjadi tanggal hari ini

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1289
