### ISSUE TITLE
Bug/error: surat lama tidak tampil di arsip surat di user sekdes dan kades

### ISSUE THREAD

**Issue by apidong** [OpenSID/OpenSID#5560]
### Jelaskan error yg dialami

-

### Cara untuk mereplikasi errornya

login menggunakan akun sekdes

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

-

### Tema Yang Digunakan

-

### Informasi tambahan

-

**Comment by apidong** [comment]
pak @vickyrolanda, mohon analisis, sebaiknya seperti apa untuk kades dan sekdes

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1284
