### ISSUE TITLE
Bug/error: Variabel [jabatan]  tidak berfungsi untuk penandatangan sekdes & kades 

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#5561]
### Jelaskan error yg dialami

1. Saat penanda tangan di pilih sekdes / kades maka variabel [jabatan]  kosong 
<img width="548" alt="image" src="https://user-images.githubusercontent.com/59082428/188194899-91a2035e-1934-4168-be87-ce38f6240e1d.png">
2. Namun ketika penanda tangan di pilih u.b maka variabel [jabatan] berfungsi
<img width="574" alt="image" src="https://user-images.githubusercontent.com/59082428/188195010-df9999df-efc6-47fe-add5-4bafd65d080c.png">

### Cara untuk mereplikasi errornya

di layanan persuratan

### Hasil yg diharapkan

- variabel jabatan berfungsi normal

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.09-premium

**Comment by ariandii** [comment]
<img width="637" alt="image" src="https://user-images.githubusercontent.com/46939846/188195846-41d5a4c5-db15-49c0-9f8d-61604bd1d6a8.png">

Apakah itu juga yang mempengaruhi tidak munculnya kolom Ditandatangani Oleh

**Comment by andifahruddinakas** [comment]
> <img alt="image" width="637" src="https://user-images.githubusercontent.com/46939846/188195846-41d5a4c5-db15-49c0-9f8d-61604bd1d6a8.png">
> 
> Apakah itu juga yang mempengaruhi tidak munculnya kolom Ditandatangani Oleh

Mas @vickyrolanda, coba cek bagian ini. Alur sampai dapat errornya, di saya coba cetak rtf/tinymce ama saja. Mungkin ada alur lain.

**Comment by Sukoharjo3** [comment]
![image](https://user-images.githubusercontent.com/112841792/188357771-bf12cba4-f03c-4300-ab08-6cd322cfaa6c.png)
mengalami hal demikian

**Comment by vickyrolanda** [comment]
> > <img alt="image" width="637" src="https://user-images.githubusercontent.com/46939846/188195846-41d5a4c5-db15-49c0-9f8d-61604bd1d6a8.png">
> > Apakah itu juga yang mempengaruhi tidak munculnya kolom Ditandatangani Oleh
> 
> Mas @vickyrolanda, coba cek bagian ini. Alur sampai dapat errornya, di saya coba cetak rtf/tinymce ama saja. Mungkin ada alur lain.

bagian di penandatangan itu sama hal seperti variable di atas mas, untuk penandatangan kades & sekdes tidak muncul tapi pilihan penanda tangan u.b muncul mas ntar pr ke issue baru ini ya mas https://github.com/OpenSID/OpenSID/issues/5574

<img width="771" alt="image" src="https://user-images.githubusercontent.com/59082428/188400026-ab82c76f-836e-492a-b95f-90c3ffaddc90.png">

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1285
