### ISSUE TITLE
Bug/error: Pendidik di menu edit aparatur desa tidak muncul nama pendidikannya.

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#5562]
### Jelaskan error yg dialami

1. Masuk ke pemerintahan desa -> edit -> lihat di tidak terdata 

<img width="540" alt="image" src="https://user-images.githubusercontent.com/59082428/188195636-4e69577e-3037-4b66-878b-7e9d087da3c6.png">

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.09-premium

**Comment by ariandii** [comment]
<img width="516" alt="image" src="https://user-images.githubusercontent.com/46939846/188196284-20e86adb-8124-4676-b8b0-d736ebf7cdfe.png">

begitu juga dengan Option Agama

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1286
