### ISSUE TITLE
Perbaikan preview tambah pengaturan surat tinymce

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#5563]
### Apa kekurangan yg ingin diatasi?

Sebelum di simpan pada tambah pengaturan surat tinymce untuk dibuatkan preview

### Jelaskan solusi yg diinginkan

Preview surat tinymce

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

v22.10-premium

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1333

**Comment by devrakapriyo** [comment]
<img width="1440" alt="Screen Shot 2022-10-01 at 21 22 36" src="https://user-images.githubusercontent.com/36557759/193414072-3eff8260-4671-438c-bfe6-45ddb09901ef.png">

mas @yogiperdana untuk variable nya di ubah menjadi placeholder

**Comment by yogiperdana** [comment]
Bisa berikan contoh kalimat placeholder yang dimaksud mas @devrakapriyo @vickyrolanda. Jika menggunakan data dummy seperti diskusi dengan mas akas kemarin tidak bisa diterapkan untuk semua surat (hanya bisa diterapkan untuk surat sederhana seperti individu)

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1447
