### ISSUE TITLE
Bug/error: error session saat print salinan KK

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#5568]
### Jelaskan error yg dialami

sepertinya ini disebabkan session yang menyebabkan terkadang kepala desa tidak muncul saat print salinan KK

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

tidak terjadi hal ini

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.09-premium

**Comment by andifahruddinakas** [comment]
Mas @devrakapriyo, sy cek tidak ada masalah di cetak salinan KK ini. Dan penanda tangan tidak menggunakan session, bisa di cek kembali dan perjelas alurnya sampai menemukan error.

![salinan kk](https://user-images.githubusercontent.com/57283157/188345917-c32a106c-6136-4831-868a-17b5dc05d87e.png)

**Comment by devrakapriyo** [comment]
iya mas, ini terkadang ada terkadang hilang jadi tidak menentu
itu karena apa ya mas sebabnya?

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1297
