### ISSUE TITLE
Bug/error: fitur cetak surat tinymce tidak berfungsi khusus desa langonsari.desa.id

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#5569]
### Jelaskan error yg dialami

karena desa langonsari menggunakan server Diskominfo yang menyebabkan fitur cetak surat TinyMCE error 500, tidak hanya itu backup database dan fitur custom dari Diskominfo juga error 500.

sedangkan saat di test di local semua berjalan dengan normal.

info dari pengguna : fitur custom Diskominfo terkahir di v22.03-umum

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.09-premium

**Comment by devrakapriyo** [comment]
terlampir gdrive OpenDesa yang berisikan database desa tersebut dan log error

https://drive.google.com/drive/folders/1d419VUBx7Jj9iG3i21De_SEEFwDm3MEl?usp=sharing

karena link ini bersifat internal, tolong beri info untuk meminta akses

**Comment by devrakapriyo** [comment]
terkahir saya hubungi pengguna melalui telegram dengan username @SuryaWijaya88 di tanggal 8 september tidak ada info lebih lanjut
sementara di tutup dan akan buka kembali jika pengguna mengabarkan

**Comment by langonsari** [comment]
![image](https://user-images.githubusercontent.com/96863107/190394496-50c85fe0-43e1-4a00-9321-14bf91da04e7.png)
![image](https://user-images.githubusercontent.com/96863107/190394565-779b7fb1-3007-4b27-83cc-a746b4afa9c9.png)

Backup & Surat TinyMCE masih Error 500

**Comment by andifahruddinakas** [comment]
HASIL PENGECEKAN SEBELUMNYA TIDAK MENEMUKAN ERROR YANG DIMAKSUDKAN, CUMA ADA BEBERAPA MASLAH BERIKUT INI : 

![langonsari 3](https://user-images.githubusercontent.com/57283157/190550901-b7bc945f-7b0b-4502-9c90-cf9367ea664f.png)
![langonsari 2](https://user-images.githubusercontent.com/57283157/190550904-39cdaaec-8565-4b82-9fda-dc8cd7c91d54.png)
![langonsari 1](https://user-images.githubusercontent.com/57283157/190550906-3d1a0196-2b74-410e-87d3-fedb74a60a82.png)

Saat restore database, tweb_surat_fomat gagal restore : 
```
CREATE TABLE `tweb_surat_format` (
  `id` int(11) NOT NULL,
  `nama` varchar(100) NOT NULL,
  `url_surat` varchar(100) NOT NULL,
  `kode_surat` varchar(10) DEFAULT NULL,
  `lampiran` varchar(100) DEFAULT NULL,
  `kunci` tinyint(1) NOT NULL DEFAULT '0',
  `favorit` tinyint(1) NOT NULL DEFAULT '0',
  `jenis` tinyint(2) NOT NULL DEFAULT '2',
  `mandiri` tinyint(1) DEFAULT '0',
  `masa_berlaku` int(3) DEFAULT '1',
  `satuan_masa_berlaku` varchar(15) DEFAULT 'M',
  `qr_code` tinyint(1) NOT NULL DEFAULT '0',
  `logo_garuda` tinyint(1) NOT NULL DEFAULT '0',
  `syarat_surat` longtext,
  `template` longtext,
  `template_desa` longtext,
  `form_isian` longtext,
  `kode_isian` longtext,
  `orientasi` varchar(10) DEFAULT NULL,
  `ukuran` varchar(10) DEFAULT NULL,
  `margin` text,
  `footer` int(1) NOT NULL DEFAULT '1',
  `header` int(1) NOT NULL DEFAULT '1',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` int(11) DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_by` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;
```
setelah ganti menjadi : (bawaan)
```
CREATE TABLE `tweb_surat_format` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `nama` varchar(100) NOT NULL,
  `url_surat` varchar(100) NOT NULL,
  `kode_surat` varchar(10) DEFAULT NULL,
  `lampiran` varchar(100) DEFAULT NULL,
  `kunci` tinyint(1) NOT NULL DEFAULT '0',
  `favorit` tinyint(1) NOT NULL DEFAULT '0',
  `jenis` tinyint(2) NOT NULL DEFAULT '2',
  `mandiri` tinyint(1) DEFAULT '0',
  `masa_berlaku` int(3) DEFAULT '1',
  `satuan_masa_berlaku` varchar(15) DEFAULT 'M',
  `qr_code` tinyint(1) NOT NULL DEFAULT '0',
  `logo_garuda` tinyint(1) NOT NULL DEFAULT '0',
  `syarat_surat` longtext,
  `template` longtext,
  `template_desa` longtext,
  `form_isian` longtext,
  `kode_isian` longtext,
  `orientasi` varchar(10) DEFAULT NULL,
  `ukuran` varchar(10) DEFAULT NULL,
  `margin` text,
  `footer` int(1) NOT NULL DEFAULT '1',
  `header` int(1) NOT NULL DEFAULT '1',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` int(11) DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `url_surat` (`url_surat`)
) ENGINE=InnoDB AUTO_INCREMENT=201 DEFAULT CHARSET=utf8;
```

BISA DICOBA : (jangan lupa backup) 
1. Coba jalankan periksa database dengan mengakses url : domain/periksa
2. Sesuaikan struktur database tweb_surat_format sesuai dengan bawaan

CATATAN : 
1. Ada modul tambahan dari database yang tidak bisa diakses.

**Comment by eddieridwan** [comment]
@devrakapriyo @vickyrolanda @andifahruddinakas jika pelapor menggunakan versi OpenSID ubahan (bukan rilis resmi), maka kebijakan OpenDesa adalah tidak bisa membantu terkait masalah yang dialami. Karena terlalu sulit untuk melacak akar permasalahan. Dan menjadi tanggung jawab pihak yg mengembangkan versi ubahan tersebut. 

@devrakapriyo , jika kita sudah yakin pelapor betul menggunakan versi ubahan, tutup issue dan beritahu pelapor terkait kebijakan di atas.

**Comment by devrakapriyo** [comment]
iya pak @eddieridwan sesuai dengan yang di laporkan oleh pak @langonsari OpenSID tersebut ada di server Diskominfo dan ada beberapa fitur custome dari Diskominfo

**Comment by langonsari** [comment]
untuk Versi yang dipakai oleh Desa kami itu bukan ubahan dari sistem asli pak hanya penambahan modul saja,, dan itu hanya menambahkan file modul di:
- [ ] /donjo-app/controllers
- [ ] /donjo-app/models
- [ ] /donjo-app/view
tidak ada ubahan dari sistem bawaan secara default, karena untuk update pun saya menggunakan pola git,
Adapun untuk databasenya ada sedikit tambahan table & field:
- [ ] Table Rembug
- [ ] Fields "tnde" di Table log_surat

**Comment by langonsari** [comment]
untuk saat  ini Bug yang terjadi hanya HTTP ERROR 500 saat membuka Cetak Surat/form Surat TinyMCE baik yang bawaan sistem maupun yang hasil tambah Surat TinyMCE di Pengaturan Surat,,,

**Pertanyaan:**
1. apakah ada Extention atau Function di PHP yang harus diaktifkan secara khusus untuk membuka Format Surat TinyMCE karena di Format Surat untuk ubahan Pengaturan Surat TinyMCE berfungsi normal?

terima kasih,,,
![image](https://user-images.githubusercontent.com/96863107/191023163-85cb6734-238a-43bf-84f0-5eabe8194e6b.png)

**Comment by apidong** [comment]
> untuk saat ini Bug yang terjadi hanya HTTP ERROR 500 saat membuka Cetak Surat/form Surat TinyMCE baik yang bawaan sistem maupun yang hasil tambah Surat TinyMCE di Pengaturan Surat,,,
> 
> **Pertanyaan:**
> 
> 1. apakah ada Extention atau Function di PHP yang harus diaktifkan secara khusus untuk membuka Format Surat TinyMCE karena di Format Surat untuk ubahan Pengaturan Surat TinyMCE berfungsi normal?
> 
> terima kasih,,, ![image](https://user-images.githubusercontent.com/96863107/191023163-85cb6734-238a-43bf-84f0-5eabe8194e6b.png)

bisa di infokan. log errornya?

**Comment by langonsari** [comment]
[log-2022-09-19.txt](https://github.com/OpenSID/OpenSID/files/9599260/log-2022-09-19.txt)
ini pak Log errornya

**Comment by devrakapriyo** [comment]
> HASIL PENGECEKAN SEBELUMNYA TIDAK MENEMUKAN ERROR YANG DIMAKSUDKAN, CUMA ADA BEBERAPA MASLAH BERIKUT INI :
> 
> ![langonsari 3](https://user-images.githubusercontent.com/57283157/190550901-b7bc945f-7b0b-4502-9c90-cf9367ea664f.png) ![langonsari 2](https://user-images.githubusercontent.com/57283157/190550904-39cdaaec-8565-4b82-9fda-dc8cd7c91d54.png) ![langonsari 1](https://user-images.githubusercontent.com/57283157/190550906-3d1a0196-2b74-410e-87d3-fedb74a60a82.png)
> 
> Saat restore database, tweb_surat_fomat gagal restore :
> 
> ```
> CREATE TABLE `tweb_surat_format` (
>   `id` int(11) NOT NULL,
>   `nama` varchar(100) NOT NULL,
>   `url_surat` varchar(100) NOT NULL,
>   `kode_surat` varchar(10) DEFAULT NULL,
>   `lampiran` varchar(100) DEFAULT NULL,
>   `kunci` tinyint(1) NOT NULL DEFAULT '0',
>   `favorit` tinyint(1) NOT NULL DEFAULT '0',
>   `jenis` tinyint(2) NOT NULL DEFAULT '2',
>   `mandiri` tinyint(1) DEFAULT '0',
>   `masa_berlaku` int(3) DEFAULT '1',
>   `satuan_masa_berlaku` varchar(15) DEFAULT 'M',
>   `qr_code` tinyint(1) NOT NULL DEFAULT '0',
>   `logo_garuda` tinyint(1) NOT NULL DEFAULT '0',
>   `syarat_surat` longtext,
>   `template` longtext,
>   `template_desa` longtext,
>   `form_isian` longtext,
>   `kode_isian` longtext,
>   `orientasi` varchar(10) DEFAULT NULL,
>   `ukuran` varchar(10) DEFAULT NULL,
>   `margin` text,
>   `footer` int(1) NOT NULL DEFAULT '1',
>   `header` int(1) NOT NULL DEFAULT '1',
>   `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
>   `created_by` int(11) DEFAULT NULL,
>   `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
>   `updated_by` int(11) DEFAULT NULL
> ) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;
> ```
> 
> setelah ganti menjadi : (bawaan)
> 
> ```
> CREATE TABLE `tweb_surat_format` (
>   `id` int(11) NOT NULL AUTO_INCREMENT,
>   `nama` varchar(100) NOT NULL,
>   `url_surat` varchar(100) NOT NULL,
>   `kode_surat` varchar(10) DEFAULT NULL,
>   `lampiran` varchar(100) DEFAULT NULL,
>   `kunci` tinyint(1) NOT NULL DEFAULT '0',
>   `favorit` tinyint(1) NOT NULL DEFAULT '0',
>   `jenis` tinyint(2) NOT NULL DEFAULT '2',
>   `mandiri` tinyint(1) DEFAULT '0',
>   `masa_berlaku` int(3) DEFAULT '1',
>   `satuan_masa_berlaku` varchar(15) DEFAULT 'M',
>   `qr_code` tinyint(1) NOT NULL DEFAULT '0',
>   `logo_garuda` tinyint(1) NOT NULL DEFAULT '0',
>   `syarat_surat` longtext,
>   `template` longtext,
>   `template_desa` longtext,
>   `form_isian` longtext,
>   `kode_isian` longtext,
>   `orientasi` varchar(10) DEFAULT NULL,
>   `ukuran` varchar(10) DEFAULT NULL,
>   `margin` text,
>   `footer` int(1) NOT NULL DEFAULT '1',
>   `header` int(1) NOT NULL DEFAULT '1',
>   `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
>   `created_by` int(11) DEFAULT NULL,
>   `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
>   `updated_by` int(11) DEFAULT NULL,
>   PRIMARY KEY (`id`),
>   UNIQUE KEY `url_surat` (`url_surat`)
> ) ENGINE=InnoDB AUTO_INCREMENT=201 DEFAULT CHARSET=utf8;
> ```
> 
> BISA DICOBA : (jangan lupa backup)
> 
> 1. Coba jalankan periksa database dengan mengakses url : domain/periksa
> 2. Sesuaikan struktur database tweb_surat_format sesuai dengan bawaan
> 
> CATATAN :
> 
> 1. Ada modul tambahan dari database yang tidak bisa diakses.

berdasarkan diskusi tim dan informasi ini, karena menggunakan versi ubahan struktur database dan sesuai ketentuan jika menggunakan versi ubahan maka kebijakan OpenDesa adalah tidak bisa membantu terkait masalah yang dialami

maka issue ini kami close
