### ISSUE TITLE
Bug/error: error saat cetak surat TinyMCE khusus desa sidodadi-pringsewu.desa.id

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#5570]
### Jelaskan error yg dialami

setiap cetak surat tinymce selalu muncul notif error dan log error tidak muncul apa apa

![image](https://user-images.githubusercontent.com/36557759/188318677-22b98eb8-a5e6-4f80-88f0-58317f29a573.png)

saat saya coba import database di local dengan DB desa tersebut selalu gagal. DB dan folder desa tersedia di Gdrive internal OpenDesa

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.09-premium

**Comment by devrakapriyo** [comment]
terlampir gdrive OpenDesa yang berisikan database desa tersebut dan log error

https://drive.google.com/drive/folders/15x-dSsUx5kQ_6A5_4cdRLvKStZAiMegB?usp=sharing

karena link ini bersifat internal, tolong beri info untuk meminta akses

**Comment by andifahruddinakas** [comment]
cek juga di console log nya di browser saat melakukan cetak surat.

![log browser](https://user-images.githubusercontent.com/57283157/188348190-51570661-6652-42c2-81c7-63b39ae9ce5c.png)

**Comment by andifahruddinakas** [comment]
Sudah sy cek menggunakan data yang dilampirkan, hasilnya sukses cetak. Mungkin masalahnya di server desa tsb.

**Comment by devrakapriyo** [comment]
setelah saya konfirmasi dengan pengguna terkahir di tanggal 8 september tidak ada pertanyaan lagi, sepertinya sudah solved
mungkin ada sangkut paut dengan issue https://github.com/OpenSID/OpenSID/issues/5624

**Comment by andifahruddinakas** [comment]
Mas @devrakapriyo, biasanya error ini disebabkan karena penggunaan font yang belum tersedia di librari html2pdf. Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/1324
