### ISSUE TITLE
Bug/error: SDGs khusus desa kesambirampak.desa.id tidak bisa diakses

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#5571]
### Jelaskan error yg dialami

![image](https://user-images.githubusercontent.com/36557759/188319680-aa6fafdf-e04e-4c49-8da8-27ea41e72423.png)

### Cara untuk mereplikasi errornya

masuk ke link https://www.kesambirampak.desa.id/status-sdgs

### Hasil yg diharapkan

fitur SDGs bisa diakses seperti di https://berputar.opendesa.id/status-sdgs

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.09-premium

### Tema Yang Digunakan

DeNatra v7.0

**Comment by devrakapriyo** [comment]
terlampir gdrive OpenDesa yang berisikan database desa tersebut dan log error

https://drive.google.com/drive/folders/1ABqfo-NZWjmpUHUA32r6uLAvdKDhMb1T?usp=sharing

karena link ini bersifat internal, tolong beri info untuk meminta akses

**Comment by andifahruddinakas** [comment]
Mas @devrakapriyo, untuk pengecekan bagian halaman depan/tema, usahakan selalu menggunakan tema bawaan.

**Comment by andifahruddinakas** [comment]
Apa sudah dimasukkan kode desa berdasarkan Wilayah Kerja Statistik - BPS ? 

https://sig.bps.go.id/bridging-kode

![sdgs 1](https://user-images.githubusercontent.com/57283157/188346649-fe6b5cc8-ad18-454c-8eb8-4f763cdcf222.png)

Apakah sudah ada panduan untuk fitur baru ini ?

**Comment by devrakapriyo** [comment]
mas @andifahruddinakas icon gear itu kok di local saya ga ada ya? di berputar juga sama ga ada

**Comment by andifahruddinakas** [comment]
> mas @andifahruddinakas icon gear itu kok di local saya ga ada ya? di berputar juga sama ga ada

Migrasinya gak jalan sempurna berarti.

**Comment by devrakapriyo** [comment]
solusinya bagiaman ya mas? karena proses migrasinya berhasil mas

**Comment by andifahruddinakas** [comment]
> solusinya bagiaman ya mas? karena proses migrasinya berhasil mas

kalau berhasil, harusnya data kode_desa_bps nambah di tabel setting_aplikasi. kalau cuma 1/2 desa, bisa dilakukan scr manual.

**Comment by andifahruddinakas** [comment]
Jalankan query: 
```
INSERT INTO `setting_aplikasi` (`key`, `value`, `keterangan`, `kategori`) VALUES ('kode_desa_bps', '', 'Kode Desa BPS (Dapat di cek di <a href="https://sig.bps.go.id/bridging-kode" target="_blank">https://sig.bps.go.id/bridging-kode</a>)', 'status sdgs');
```

**Comment by devrakapriyo** [comment]
baik mas, saya coba ya

**Comment by devrakapriyo** [comment]
> Jalankan query:
> 
> ```
> INSERT INTO `setting_aplikasi` (`key`, `value`, `keterangan`, `kategori`) VALUES ('kode_desa_bps', '', 'Kode Desa BPS (Dapat di cek di <a href="https://sig.bps.go.id/bridging-kode" target="_blank">https://sig.bps.go.id/bridging-kode</a>)', 'status sdgs');
> ```

<img width="1440" alt="Screen Shot 2022-09-05 at 13 17 10" src="https://user-images.githubusercontent.com/36557759/188372938-adb41dcf-4833-4e16-98e8-37c0932c5918.png">

saya cek di database value ini sudah ada, sebelum saya jalankan script insert ini

**Comment by andifahruddinakas** [comment]
Solusi : 
1. Buat panduan
