### ISSUE TITLE
Validasi Pengaturan Aplikasi

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#5572]
Sediakan kolom dinamis untuk menambahkan validasi masing2 pengaturan.

**Comment by eddieridwan** [comment]
@andifahruddinakas @vickyrolanda tugas ini perlu dirinci dan dibuatkan issue terpisah untuk setiap pengaturan

**Comment by andifahruddinakas** [comment]
Dibagi per modul saja

**Comment by andifahruddinakas** [comment]
Mas @vickyrolanda, ini juga dipecah berdasarkan modul.

**Comment by andifahruddinakas** [comment]
https://github.com/Laravel-Backpack/Settings
