### ISSUE TITLE
Bug/error: akses data suplemen error

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#5573]
### Jelaskan error yg dialami

![image](https://user-images.githubusercontent.com/36557759/188382977-84d38129-5c20-43e2-932d-cd04c52857f7.png)

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.09-premium

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1290
