### ISSUE TITLE
Bug/error: halaman kelompok error

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#5576]
### Jelaskan error yg dialami

<img width="1440" alt="Screen Shot 2022-09-05 at 17 01 20" src="https://user-images.githubusercontent.com/36557759/188423405-52511ff0-badc-4fc0-879b-791367596128.png">

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

22.09-premium

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1291
