### ISSUE TITLE
Permintaan fitur: Penambahan Koordinat dan Foto di data Keluarga

### ISSUE THREAD

**Issue by mukhlisvandjava** [OpenSID/OpenSID#5577]
### Apa kekurangan yg ingin diatasi?

Penambahan menu Koordinat Lokasi Keluarga dan upload foto (upload 3 foto "Foto Keluarga yang tinggal, Rumah Tampak Depan, Samping (Opsional) ). Penambahan Lokasi seperti penanda lokasi Individu penduduk. Dengan adanya penanda Keluarga di harapkan Penempatan lokasi Keluarga bisa mewakili seluruh anggota keluarga ( Koordinatnya sama setiap anggota keluarga secara otomatis)

### Jelaskan solusi yg diinginkan

melengkapi Data Keluarga dengan rincian lokasi koordinat dan Foto Kondisi Keluarga  

### Apakah ada alternatif lain

Jika menambahkan lokasi pada data keluarga, maka secara otomatis anggota keluarga juga memiliki koordinat yang sama dengan kepala keluarga

### Untuk versi OpenSID mana

Versi Premium 

### Informasi tambahan

Data ini nanti bisa dimanfaatkan oleh desa untuk identifikasi rumah penduduk

**Comment by mukhlisvandjava** [comment]
![foto kk](https://user-images.githubusercontent.com/92527916/199863209-22251073-7be4-4983-b188-a06ac7a50116.png)

**Comment by eddieridwan** [comment]
@vickyrolanda perlu peljajari apakah tumpang tindih dengan modul DTKS.

**Comment by mukhlisvandjava** [comment]
siap pak... menu ini mnrtku lebih pas karena koordinat dan foto rumah melekat pada data Keluarga

**Comment by ruririzal** [comment]
mas @vickyrolanda, untuk fitur upload foto di DTKS menggunakan mekanisme seperti gambar dibawah. 

Jadi ada tabel untuk Foto dan tabel untuk menampung relasi Foto dengan DTKS. saat ini tabel foto masih mengacu pada rumah tangga (ditandai dengan field id_rtm), tabel foto bersifat dinamis juga dimana untuk judulnya bisa disesuaikan oleh masing2 desa.

tapi punya potensi untuk ditambahkan satu field lagi untuk keluarga jika dalam 1 rumah tangga hanya ada 1 keluarga (KK), jika dalam 1 rumah tangga ada lebih dari 1 kk perlu didiskusikan lagi. untuk penamaan tabel bisa disesuaikan juga

![image](https://user-images.githubusercontent.com/28647065/200560685-ce0200a7-6840-48d5-bc6f-34fb63352f70.png)

mengenai koordinat saya kurang paham, setau saya koordinat kepala keluarga sudah bisa diambil dan mengacu pada tabel tweb_cluster

**Comment by mukhlisvandjava** [comment]
Issu yang sama [Disini ](https://github.com/OpenSID/OpenSID/issues/5985)

**Comment by Zoel-WB** [comment]
Mengingat saat ini supaya sejalan dengan fitur baru DTKS yg sedangkan di kembangkan, pandangan saya untuk membuat titik koordinat, apakah nanti utk dapat disisipkan dengan foto-foto keadaan lebih sesuai dengan diletak titik koodinat utama ada pada lokasi RUMAH TANGGA atau oleh BPS sendiri disebut dengan RUTA.

adapun mengenai penyisipan foto dapat di masukkan seperti memasukkan foto progres pada fitur kegiatan pembangunan, adapun jenis foto untuk dapat dimasukkan kalau bercermin pada data DTKS, harus dapat memasukkan beberapa jenis foto seperti :
1. Foto Kartu Keluarga (biasanya dalam satu RUTA bisa beberapa KK)
2. Foto Rumah dengan bagian2-nya seperti Tampak Dinding Terluas, Atap Terluas dan Lantai terluas.
3. Foto Dapur
4. dan Foto KM/WC

**Comment by eddieridwan** [comment]
@vickyrolanda dalam semua permintaan penambahan data keluarga atau rumah tangga, perlu hati2 dengan melakukan analisis yg mencakup:

1. apakah sudah tercakup dalam modul2 yg sdh dikembangkan
2. apakah akan tercakup dalam modul2 Satu Data yg akan ditambahkan, seperti Prodeskel, IDM dan SDGs
3. pelajari ERD secara rinci, terutama pengertian perpanjangan data penduduk, data keluarga dan data rumah tangga
4. tampilan UI yg mencerminkan konsep perpanjangan data penduduk, data keluarga dan data rumah tangga tersebut
5. dasar peraturan permintaan

**Comment by andifahruddinakas** [comment]
Duplicate of https://github.com/OpenSID/OpenSID/issues/5985
