### ISSUE TITLE
[TinyMCE] Format kode isian untuk menerapkan Title Case

### ISSUE THREAD

**Issue by pemdeslinggapura** [OpenSID/OpenSID#5578]
### Apa kekurangan yg ingin diatasi?

Tidak bisa generate kode isian Capitalize Each Word hanya UPPERCASE DAN lowercase

### Jelaskan solusi yg diinginkan

[JUdul_surat] : ini adalah contoh kode surat pdf untuk menampilkan teks Uppercase contoh "SURAT KETERANGAN USAHA"
nah bisa tidak ada bentuk kode form isian yang menampilkan teks Capitalize Each Word, sontoh : "Surat Keterangan Usaha" misalkan kode pemanggilannya [Judul_surat]

### Apakah ada alternatif lain

[**JU**dul_surat] : untuk UPPERCASE
[**J**udul_surat] : untuk Capitalize Each Word
[judul_surat] : untuk lowercase

### Untuk versi OpenSID mana

v22.09-premium

**Comment by andifahruddinakas** [comment]
Saat ini : 
* Huruf pertama dan kedua huruf besar --> ganti dengan huruf besar semua:
* [SEbutan_kepala_desa] ==> KEPALA DESA
*
* Huruf pertama besar dan kedua kecil --> ganti dengan huruf besar pertama saja:
* [Sebutan_kepala_desa] ==> Kepala desa
*
* Huruf pertama kecil --> ganti dengan huruf kecil semua:
* [sebutan_kepala_desa] ==> kepala desa

Solusi : 
* Huruf pertama dan ketiga huruf besar --> ganti dengan huruf besar diawal kata:
* [SeButan_kepala_desa] ==> Kepala Desa

Catatan : 
* Terapkan hanya pada surat TinyMCE

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1446
