### ISSUE TITLE
Permintaan fitur: Menampilkan Daftar Anggota Keluarga untuk Surat Pdf

### ISSUE THREAD

**Issue by pemdeslinggapura** [OpenSID/OpenSID#5579]
### Apa kekurangan yg ingin diatasi?

Pada Surat RTF ada beberapa surat yang memiliki fitur pemanggilan data Tabel Anggota Keluarga, contohnya seperti ini 
![image](https://user-images.githubusercontent.com/89450861/188470609-3f0ed1a4-eead-4307-aada-ea5ae05b6ce6.png)
Mudah-mudahan pada Surat Pdf juga bisa di tanamkan kode isian untuk menampilkan Daftar Anggota Keluarga untuk Sumber Data Kepala Keluarga saja.

### Jelaskan solusi yg diinginkan

Kode Isian untuk menampilkan Daftar Anggota Keluarga

### Apakah ada alternatif lain

sementara masih surat rtf saja yang bisa menampilkannya

### Untuk versi OpenSID mana

Versi 22.09-premium

**Comment by andifahruddinakas** [comment]
Duplicate issue https://github.com/OpenSID/OpenSID/issues/5524
