### ISSUE TITLE
Menu input surat keluar non-layanan

### ISSUE THREAD

**Issue by sukrimalendra** [OpenSID/OpenSID#558]
Pengarsipan surat keluar juga sangat penting sebagai laporan. Untuk itu, dimohon adanya Menu input surat keluar non-layanan dan tergabung kedalam surat keluar layanan. Layaknya seperti menu surat masuk yang sudah ada di versi OpenSID 2.3.

**Comment by eddieridwan** [comment]
Perlu dilengkapi dengan:

1. penjelasan data untuk direkam/simpan
2. beberapa contoh surat non-layanan
3. apakah juga perlu menu terpisah untuk arsip non-layanan
4. penjelasan apakah arsip non-layanan hanya berisi surat non-layanan hasil cetak OpenSID, atau juga bisa mengunggah scan surat hasil proses lain.

**Comment by sukrimalendra** [comment]
Untuk layanan surat keluarnya cukup dibuatkan seperti menu surat masuk yang
sudah ada dan diberi menu percis seperti menu surat masuk yang sudah ada
pada opensid v.2.6. Terimakasih pak.

Pada tanggal 1 Okt 2017 12:48 PM, "Eddie Ridwan" <notifications@github.com>
menulis:

**Comment by MUHAMMADRANGSEL** [comment]
SESUAI DENGAN PERATURAN MENTERI DALAM NEGERI REPUBLIK INDONESIA NOMOR 47 TAHUN 2016     TENTANG ADMINISTRASI PEMERINTAHAN DESA
BUKU AGENDA SURAT MASUK DAN KELUAR MENJADI SATU DENGAN FORMAT SEBAGAI BERIKUT : 
![screenshot 2018-01-26 00 30 49](https://user-images.githubusercontent.com/25834335/35431198-69e00a94-0230-11e8-8332-59bfda55035b.jpg)


Kolom 1: | Diisi dengan nomor secara berurut sesuai dengan urutan surat masuk dan keluar
Kolom 2: | Diisi dengan tanggal   diterimanya surat atau tanggal pengiriman surat
Kolom 3: | Diisi dengan nomor surat   masuk
Kolom 4: | Diisi dengan tanggal, bulan   dan tahun surat masuk
Kolom 5: | Diisi dengan nama instansi   pengirim surat masuk
Kolom 6: | Diisi dengan perihal surat masuk
Kolom 7: | Diisi dengan nomor   surat keluar
Kolom 8: | Diisi dengan tanggal, bulan   dan tahun surat keluar
Kolom 9: | Diisi dengan nama instansi yang dituju
Kolom 10: | Diisi dengan perihal surat keluar
Kolam 11: | Diisi dengan catatan-catatan lain yang dianggap   perlu

TETAPI DIDALAM OPENSID SUDAH ADA SURAT KELUAR YAITU ARSIP LAYANAN DAN SURAT MASUK DAN YANG BELUM ADALAH SURAT NON LAYANAN SEPERTI SURAT UNDANGAN DAN SEJENISNYA
![screenshot 2018-01-26 00 27 41](https://user-images.githubusercontent.com/25834335/35431200-6a6b9f6e-0230-11e8-8c19-dd4aec32ccc9.jpg)

**Comment by MUHAMMADRANGSEL** [comment]
bERKAS sURAT KELUAR TERSEBUT YANG SUDAH DITANDATANGANI OLEH KEPALA DESA DI SCAN DAN DIUPLOAD SEPERTI SURAT MASUK

**Comment by MUHAMMADRANGSEL** [comment]
UNTUK LEBIH JELASNYA MAS EDDIE DAN KAWAN2 PROGRAMER INI SAYA LAMPIRKAN : 
[permen_no.47_th_2016.zip](https://github.com/OpenSID/OpenSID/files/1667138/permen_no.47_th_2016.zip)

**Comment by sukrimalendra** [comment]
Benar pak. Kami di desa pelangan juga menggunakan format seperti itu.

Pada tanggal 26 Jan 2018 4:44 PM, "MUHAMMADRANGSEL" <
notifications@github.com> menulis:

**Comment by eddieridwan** [comment]
Contoh aplikasi yang digunakan desa: https://drive.google.com/file/d/1A7108aoESOSXM2QOVxwN-LJ2Yaq-u1t3/view

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
