### ISSUE TITLE
Permintaan Fitur : Terapkan aturan penghapusan surat di halaman arsip

### ISSUE THREAD

**Issue by pemdeslinggapura** [OpenSID/OpenSID#5580]
### Jelaskan error yg dialami

Menu Aksi pada surat pdf tidak tampil di halaman Arsip, tidak bisa menghapus arsip surat
![Capture](https://user-images.githubusercontent.com/89450861/188529166-ef3745a2-bf33-4554-acb8-4bd7bbf981d6.PNG)

### Cara untuk mereplikasi errornya

Layanan Surat -> Arsip Layanan

### Hasil yg diharapkan

Bisa menghapus arsip surat

### Tangkapan layar dan log error

![Capture](https://user-images.githubusercontent.com/89450861/188529188-b9684014-7d2c-4578-b628-3f4df4de97e0.PNG)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Versi 22.09-premium

**Comment by andifahruddinakas** [comment]
Mas @vickyrolanda, @devrakapriyo, bisa konfirmasi issue ini. Apakah setelah surat di cetak (diarsipkan) diperbolehkan untuk menghapus surat tsb.

**Comment by eddieridwan** [comment]
@vickyrolanda @devrakapriyo :

1. Seharusnya surat yang diarsipkan berupa surat resmi yg telah diterbitkan desa, dan tidak boleh dihapus
2. Dari pembahasan di grup, kebutuhan menghapus surat di arsip timbul dari:
    1. mencoba atau belajar membuat surat
    2. mencoba/menguji template surat baru

Untuk 2.i, solusinya adalah:
1. menjelaskan di panduan, jika belajar atau mencoba jangan lakukan di sistem betulan. Lakukan di aplikasi demo/pelatihan
2. dengan surat TinyMCE, bisa lakukan pembuatan surat, gunakan preview untuk menampilkan, tapi jangan sampai ke tahap finalkan surat

Untuk 2.ii, solusinya di surat TinyMCE adalah:
1. sediakan preview pada pembuatan template surat, berisi data `placeholder`
2. sediakan preview pada proses pencetakan surat setelah memilih/mengisi data betulan; dan ada fitur untuk membatalkan surat sebelum dicetak/difinalkan. Yaitu, sama seperti solusi 2.i.2 di atas

Yaitu, tetap tidak dapat menghapus surat yg sudah diarsipkan. Solusinya adalah menyediakan cara melihat/memeriksa surat sebelum difinalkan/diarsipkan.

Kasus tambahan adalah jika cetak/finalkan surat dilakukan secara keliru. Untuk kasus ini arsip surat dapat dihapus, dengan ketentuan sebagai berikut:
1. Hanya dapat dilakukan oleh admin tertentu
2. Penghapusan dilakukan secara `soft delete`, yaitu ditandai sebagai telah terhapus, tetapi tidak dihapus secara fisik.

**Comment by vickyrolanda** [comment]
Dari yang saya uji : 
Jika kondisi di Draft 
saya tes sudah tepat ketika surat di draft maka surat sudah dibuat namun belum di cetak dan bisa di edit, dan  ini sudah tepat karena ketika saya edit bisa dilanjutkan ke cetak.
<img width="759" alt="image" src="https://user-images.githubusercontent.com/59082428/188948421-46098780-7d9a-4a67-953f-7c47c3a04a91.png">

mas @andifahruddinakas sudah saya check untuk status draft ketika dari migrasi 22.08 ke 22.09 masuk ke arsip sehingga ketika di arsip dengan status draft jadi tidak ada action apapun.  ini sudah saya check dari versi 22.07 ke 22.09 dan terjadi seperti itu seperti dibawah ini : 
<img width="780" alt="image" src="https://user-images.githubusercontent.com/59082428/188953242-90eb24a7-a81b-4c2b-98ba-9e86d19e9a73.png">

**solusinya mas @andifahruddinakas  bisa buatkan migrasi untuk merubah status surat yg draft untuk dikembalikan ke halaman surat permohonan surat tidak di arsip.**

**Comment by andifahruddinakas** [comment]
> Dari yang saya uji : Jika kondisi di Draft saya tes sudah tepat ketika surat di draft maka surat sudah dibuat namun belum di cetak dan bisa di edit, dan ini sudah tepat karena ketika saya edit bisa dilanjutkan ke cetak. <img alt="image" width="759" src="https://user-images.githubusercontent.com/59082428/188948421-46098780-7d9a-4a67-953f-7c47c3a04a91.png">
> 
> mas @andifahruddinakas sudah saya check untuk status draft ketika dari migrasi 22.08 ke 22.09 masuk ke arsip sehingga ketika di arsip dengan status draft jadi tidak ada action apapun. ini sudah saya check dari versi 22.07 ke 22.09 dan terjadi seperti itu seperti dibawah ini : <img alt="image" width="780" src="https://user-images.githubusercontent.com/59082428/188953242-90eb24a7-a81b-4c2b-98ba-9e86d19e9a73.png">
> 
> **solusinya mas @andifahruddinakas bisa buatkan migrasi untuk merubah status surat yg draft untuk dikembalikan ke halaman surat permohonan surat tidak di arsip.**

bisa kirim database yang digunakan?

**Comment by vickyrolanda** [comment]
> > Dari yang saya uji : Jika kondisi di Draft saya tes sudah tepat ketika surat di draft maka surat sudah dibuat namun belum di cetak dan bisa di edit, dan ini sudah tepat karena ketika saya edit bisa dilanjutkan ke cetak. <img alt="image" width="759" src="https://user-images.githubusercontent.com/59082428/188948421-46098780-7d9a-4a67-953f-7c47c3a04a91.png">
> > mas @andifahruddinakas sudah saya check untuk status draft ketika dari migrasi 22.08 ke 22.09 masuk ke arsip sehingga ketika di arsip dengan status draft jadi tidak ada action apapun. ini sudah saya check dari versi 22.07 ke 22.09 dan terjadi seperti itu seperti dibawah ini : <img alt="image" width="780" src="https://user-images.githubusercontent.com/59082428/188953242-90eb24a7-a81b-4c2b-98ba-9e86d19e9a73.png">
> > **solusinya mas @andifahruddinakas bisa buatkan migrasi untuk merubah status surat yg draft untuk dikembalikan ke halaman surat permohonan surat tidak di arsip.**
> 
> bisa kirim database yang digunakan?

mas @andifahruddinakas untuk issue ini sy ubah menjadi permintaan fiture delete dan bisa pakai solusi dari pak edi mas. 
untuk bug bisa ke issue ini mas https://github.com/OpenSID/OpenSID/issues/5609

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1518
