### ISSUE TITLE
Bug/error: Surat Keterangan Lahir tidak bisa menampilkan data Penduduk

### ISSUE THREAD

**Issue by pemdeslinggapura** [OpenSID/OpenSID#5591]
### Jelaskan error yg dialami

Ketika memasukkan Nik dan Nama Ibu tidak bisa tampil
![image](https://user-images.githubusercontent.com/89450861/188534036-93d3a083-355d-44e8-b0ee-25f2a11a52a0.png)

### Cara untuk mereplikasi errornya

Ketika memasukkan Nik dan Nama Ibu tidak bisa tampil
![image](https://user-images.githubusercontent.com/89450861/188534036-93d3a083-355d-44e8-b0ee-25f2a11a52a0.png)

### Hasil yg diharapkan

Bisa menampilkan kembali data penduduk pada surat keterangan lahir

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/89450861/188534036-93d3a083-355d-44e8-b0ee-25f2a11a52a0.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.09-premium

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1298
