### ISSUE TITLE
Bug/error: Keterangan Untuk Nikah (N-1 s/d N-7) data warga tidak muncul

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#5592]
### Jelaskan error yg dialami

Cetak surat Keterangan Untuk Nikah (N-1 s/d N-7) pada saat memili warga desa datanya tidak muncul
![image](https://user-images.githubusercontent.com/36557759/188541408-9583cc27-01e4-4240-b297-f853f001dff8.png)

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.09-premium

**Comment by andifahruddinakas** [comment]
Duplicate issue https://github.com/OpenSID/OpenSID/issues/5591, sumber masalah dibagian konfirmasi pemohon yang dimana perlu dibedakan konfirmasi pemohon yang menggunakan surat rtf dan tinymce.
