### ISSUE TITLE
Menambahkan pemanggilan view anjungan di domain utama sesuai status langganan

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#5593]

**Comment by andifahruddinakas** [comment]
Solsusi : 
1. Pindahkan halaman domain/layanan-mandiri lama ke domain/layanan-mandiri/beranda
2. Gunakan domain/layanan-mandiri untuk halaman anjungan, dimana hanya bisa diakses jika sudah di daftarkan sebagai anjungan (dengan ketentuan berlaku)

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1388
