### ISSUE TITLE
Menambahkan pengaturan untuk menampilkan menu-menu anjungan

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#5594]

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1381

**Comment by vickyrolanda** [comment]
untuk PR ini belum sy gabungkan ke rilis-dev mas https://github.com/OpenSID/premium/pull/1369 karena masih ada  2 menu yang  masih di kerjain saat ini di pr menampilkan error seperti ini 
<img width="724" alt="image" src="https://user-images.githubusercontent.com/59082428/191634058-8d06af98-10b6-4eca-badb-bfa1afafe42e.png">

mungkin menunggu PR yang lain ya mas ?
