### ISSUE TITLE
Menambahkan bersihkan cache langganan saat akses halaman utama

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#5597]

**Comment by yogiperdana** [comment]
Halaman utama itu maksudnya home mas @andifahruddinakas?

**Comment by andifahruddinakas** [comment]
Jangan gunakan halaman utama (domain utama).
Gunakan url : domain/layanan-mandiri, sedangkan halaman sebelumnya (domain/layanan-mandiri) diganti menjadi domain/layanan-mandiri/dashboard.
