### ISSUE TITLE
Bug/error: rtf cetak surat keterangan domisili

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#5598]
### Jelaskan error yg dialami

![6BF27E37-A577-44E0-ABEE-5212C92243A8](https://user-images.githubusercontent.com/36557759/188641249-7c3d630a-2132-433e-9ff4-bad7bdd7192f.png)

- form_pamong_nip masih berupa variable
- Penulisan Desa di judul surat masih menggunakan huruf kecil, seharusnya Desa

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.09-premium-rev1

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1301
