### ISSUE TITLE
Bug/error: tombol upload dan camera tertutup

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#5599]
### Jelaskan error yg dialami

Tampilan tidak responsive di halaman edit aparatur desa, sehingga foto menutupi tombol upload dan camera tertutup 

![6D6DADA1-56C5-4AE4-894D-B7D800172252](https://user-images.githubusercontent.com/36557759/188643055-72be6c67-b355-4b0d-9c4c-65618f4c1f8c.jpeg)

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.09-premium-rev1

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1300
