### ISSUE TITLE
Permintaan fitur: pencarian surat favorit

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#5600]
### Apa kekurangan yg ingin diatasi?

Sediakan fitur pencarian di daftar surat favorit, karena pencarian baru tersedia di daftar surat saja
![57854058-47F0-4D19-BA8D-205A7BADC7BD](https://user-images.githubusercontent.com/36557759/188658629-996bd01f-718a-4032-bc1d-c918ac20ae0c.jpeg)

### Jelaskan solusi yg diinginkan

Pencarian datatable

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

v22.09-premium-rev1

**Comment by eddieridwan** [comment]
@devrakapriyo @vickyrolanda kotak cari sdh betul posisinya. Itu bagian dari tabel seluruh surat bukan favorit. Favorit isinya sedikit, tidak perlu dicari.

Alternatif lain, hilangkan tampilan kelompok favorit. Tampilkan favorit di tabel utama saja, di mana diatur supaya favorit selalu diurut paling atas, dengan warna hijau seperti sekarang. Mungkin cara itu akan mengurangi keluhan pengguna.

Kemudian drop-down cari di sebelah atas kiri juga bisa dihapus.

**Comment by devrakapriyo** [comment]
baik pak, saya setuju agar di jadikan 1 table saja dan untuk surat favorit di urutkan paling atas

**Comment by vickyrolanda** [comment]
> baik pak, saya setuju agar di jadikan 1 table saja dan untuk surat favorit di urutkan paling atas

mas @devrakapriyo menurut saya sebaiknya tidak digabungin.

Kalo direview ulang bahwa bagian surat favorit ini adalah surat yang sering digunakan harusnya tidak semua surat di favoritkan dan artinya harusnya sedikit saja yg bagian favorit sehingga tidak maslah tidak ada pencarian.

**Comment by eddieridwan** [comment]
@vickyrolanda @devrakapriyo , digabung saja ke dalam satu tabel. Adanya tabel terpisah membingungkan sebagain pengguna. Tujuan favorit hanya untuk menandai surat yg sering digunakan. Kalau surat favorit ditampilkan di urutan teratas dengan warna berbeda akan memenuhi tujujan itu.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1307
