### ISSUE TITLE
Bug/error: beberapa desa strukstur aparatur jabatan berantakan

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#5601]
### Jelaskan error yg dialami

issue ini terjadi dari OpenSID v22.08-premium update ke v22.09-premium yang menyebabkan beberapa desa strukstur aparatur jabatan menjadi berantakan, setelah saya lihat didatabase v22.09-premium ada penambahan table ref_jabatan yang mengatur struktur jabatan, tetapi beberapa desa saat migrasi database table tersebut tidak sesuai urutan

<img width="1440" alt="Screen Shot 2022-09-06 at 23 39 48" src="https://user-images.githubusercontent.com/36557759/188689931-30fef5ab-ea08-4907-9dda-7f33c4771d4b.png">

dan beberapa pengguna sudah mengetahui sebab jabatan menjadi berantakan dari table ini, sehingga sebagian pengguna mengubah secara langsung didatabase

![image](https://user-images.githubusercontent.com/36557759/188690521-39407927-2dac-43b9-bdc4-86d268ba4e10.png)

ini salah satu desa yang struktur jabatannya menjadi berantakan

![image](https://user-images.githubusercontent.com/36557759/188691386-b2cceddd-1a19-498e-8cea-545ab753998d.png)

dari issue ini perlu di analisis, dikarenakan hanya beberapa desa mengalami hal ini sedangkan saya sempat testing menggunakan database desa bantal saat proses migrasi database dari v22.08-premium update ke v22.09-premium tidak terjadi struktur jabatan menjadi berantakan

saya lampirkan database desa di gdrive OpenDesa
- desa bantal = tidak berantakan saat migrasi DB
- desa paduanrajawali = struktur jabatan sudah berantakan, saat pengguna melakukan migrasi

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.09-premium

**Comment by devrakapriyo** [comment]
link gdrive yang berisikan database desa : https://drive.google.com/drive/folders/1F9F9h8zrH3jL4dpGxXiaPVwjLLjub2UI?usp=sharing

**Comment by andifahruddinakas** [comment]
Sy belum bisa cek dengan menggunakan database desa tsb (belum ada akses). Mungkin perlu diketahui pada versi sebelumnya a.n (kepala desa) dan u.b (sekretaris desa) di versi sebelumnya tidak wajib di isi. Jadi jika, pada versi tsb a.n dan u.b tidak di aktifkan, maka migrasi akan di rilis 22.09-premium tidak mengenali siapa kepala desa dan sekretaris desa karena pembauatan jabatan kepala desa berdasarkan a.n dan sekretaris desa berdasarkan u.b pada versi sebelumnya yang dimana harus aktif.

**Comment by devrakapriyo** [comment]
sudah saya bukakan aksesnya mas

**Comment by andifahruddinakas** [comment]
> sudah saya bukakan aksesnya mas

Sebaiknya buat 1 folder untuk menyimpan data yang diperlukan pada issue. Agar hanya 1 kali beri akses saja, kalau cara saat ini agak lambat karena harus minta akses terus menerus.

**Comment by vickyrolanda** [comment]
mas @devrakapriyo mohon di berikan izin ya sudah saya request.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1302
