### ISSUE TITLE
Bug/error: typo di daftar permohonan surat

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#5602]
### Jelaskan error yg dialami

<img width="1440" alt="Screen Shot 2022-09-06 at 23 55 55" src="https://user-images.githubusercontent.com/36557759/188700540-c014806f-7166-4e93-ab4e-81b349f06ccc.png">

seharusnya NO ANTREAN

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.09-premium-rev1

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1299
