### ISSUE TITLE
Permintaan fitur: [PREMIUM] Penambahan Modul PPID Desa menyesuaikan Peraturan Komisi Informasi Nomor 1 Tahun 2018

### ISSUE THREAD

**Issue by mah-mudi** [OpenSID/OpenSID#5603]
### Apa kekurangan yg ingin diatasi?

**Belum adanya modul khusus PPID Desa yang menampung :**
**1. Daftar Informasi Publik Desa**
![image](https://user-images.githubusercontent.com/57661283/188717251-857f4d53-aefe-488a-a6b8-40336a3140d6.png)

**2. Daftar Pemohon Informasi Publik Desa**
![image](https://user-images.githubusercontent.com/57661283/188717501-ba308abb-9252-4787-9172-f46736d41b26.png)

**3. Register Keberatan**
![image](https://user-images.githubusercontent.com/57661283/188717914-4bbdb413-9dcb-4466-8350-5b696a89b763.png)

### Jelaskan solusi yg diinginkan

Sub Modul Informasi Publik yang ada di Modul Sekretariat, perlu diletakkan di Modul PPID Desa. Sehingga diharapkan Modul PPID Desa berisi paling sedikit : 
1. Daftar Informasi Publik **_Menyesuaikan Format Kolom di Lampiran 3 Peraturan Komisi Informasi Nomor 1 Tahun 2018_**
yg asalnya seperti ini 
![image](https://user-images.githubusercontent.com/57661283/188723190-57012d85-3924-4f11-831d-f69bdab8be15.png)

menjadi seperti ini
![image](https://user-images.githubusercontent.com/57661283/188723373-e9688fe6-6b25-417a-83fb-86d79d9fd6b9.png)

yang diharapkan seperti ini
![image](https://user-images.githubusercontent.com/57661283/188724450-f0fbe54a-38db-4f0f-aee8-729dc574e8bd.png)

2. Daftar Pemohon Informasi Publik (termasuk ada fitur cetak untuk laporan PPID Desa)
3. Register Keberatan (termasuk ada fitur cetak untuk laporan PPID Desa)

### Apakah ada alternatif lain

Jika tidak memungkinkan membuat modul baru PPID Desa, dapat menambahkan sub modul di menu sekretariat yaitu : 
1. Daftar Informasi Publik **_Menyesuaikan Format Kolom di Lampiran 3 Peraturan Komisi Informasi Nomor 1 Tahun 2018_**
2. Daftar Pemohon Informasi Publik (termasuk ada fitur cetak untuk laporan PPID Desa)
3. Register Keberatan (termasuk ada fitur cetak untuk laporan PPID Desa)

### Untuk versi OpenSID mana

OpenSID 22.11-premium

### Informasi tambahan

[Peraturan-Komisi-Informasi-Nomor-1-Tahun-2018-tentang-Standar-Layanan-Informasi-Publik-Desa.pdf](https://github.com/OpenSID/OpenSID/files/9500079/Peraturan-Komisi-Informasi-Nomor-1-Tahun-2018-tentang-Standar-Layanan-Informasi-Publik-Desa.pdf)

**Comment by Stigipro** [comment]
Perki diperbarui dengan Perki No. 1 th 2021,Penambahan d PBJ - pengadaan barang dn jasa wajib publikasi. SOTK berubah,

**Comment by luxmant354** [comment]
sebagai bahan referensi mungkin bisa membantu 
https://rahantari.digitaldesa.id/ppid

**Comment by volla15** [comment]
referensi: https://ppid.mutihkulon.desa.id/
sepertinya juga gubahan opensid
