### ISSUE TITLE
Bug/error: Penanda tangan di surat tinymce tidak muncul

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#5604]
### Jelaskan error yg dialami

Penandatangan tidak muncul pada saat pembuatan surat tinymce
<img width="797" alt="image" src="https://user-images.githubusercontent.com/59082428/188776136-af6ddd15-40c2-4578-9c85-0da2520ce828.png">

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.09-premium

**Comment by andifahruddinakas** [comment]
Mas @vickyrolanda, ini kyaknya ada alur TTE yang terpenuhi yang membuat penanda tangan tidak muncul. Coba matikan semua yang berkaitan dengan TTE.

**Comment by vickyrolanda** [comment]
> Mas @vickyrolanda, ini kyaknya ada alur TTE yang terpenuhi yang membuat penanda tangan tidak muncul. Coba matikan semua yang berkaitan dengan TTE.

Oh iya mas @andifahruddinakas terimakasih atas konfirmasihnya  saya sudah tes memang valid sy lupa bahwa kalo tte di aktifkan maka penandatangan memang harus Kepala Desa sehingga pilihan penandatangan memang harus hilang. 
<img width="789" alt="image" src="https://user-images.githubusercontent.com/59082428/188944328-1d15a73a-e150-4cf8-adff-2b4badaab3bd.png">

mas @devrakapriyo jngn lupa kondisi ini di masukkan dalam panduan ya mas .
