### ISSUE TITLE
Bug/error: filter arsip layanan surat tidak berfungsi

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#5605]
### Jelaskan error yg dialami

beberapa tester melaporkan filter arsip layanan surat tidak berfungsi dan sudah saya cek menggunakan database desa Kesambirampak mengalami hal serupa, tetapi saya cek di dev.opendesa.id fitur filter berfungsi dengan normal

<img width="1440" alt="Screen Shot 2022-09-07 at 15 35 50" src="https://user-images.githubusercontent.com/36557759/188831913-f5d9bbd1-1674-400a-b00c-a881062f4907.png">

saya lampirkan database desa Kesambirampak di gdrive OpenDesa

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.09-premium-rev1

**Comment by devrakapriyo** [comment]
link gdrive yang bersikan database desa Kesambirampak

https://drive.google.com/drive/folders/1TwgId6d1yhGqbKvf5l5DUKD-gvBgPUSb?usp=sharing

**Comment by vickyrolanda** [comment]
Untuk issue filter tidak berfungsi di bagian surat keluar : 
1. Masuk layanan surat klik "Arsip" Lakukan Filter maka tidak berjalan 
<img width="803" alt="image" src="https://user-images.githubusercontent.com/59082428/188944976-adbb13d2-3050-4af5-8084-1714529f39b4.png">
Sedangkan di bagian Permohonan Surat Filter berjalan dengan baik namun jika di lihat ketika berapa di permohonan surat 
lalu menjalankan filter maka URL redirect ke surat keluar dan filter berjalan dengan baik .
1. Gambar di bawah sebelum di filter berada di surat masuk (lihat url)
<img width="842" alt="image" src="https://user-images.githubusercontent.com/59082428/188945552-34757907-22a3-494a-9907-cf0502365987.png">

2. Gambar dibawah ketika di filter filter berhasil namun url ke surat keluar mungkin ini menjadi penyebab di arsip filter tidak bekerja dengan baik.
<img width="835" alt="image" src="https://user-images.githubusercontent.com/59082428/188945713-9cd110a9-f0a8-4317-84ad-200d1b540575.png">

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1309
