### ISSUE TITLE
Bug/error:  input data kia ibu selain istri ( menantu, dll ) belum bisa

### ISSUE THREAD

**Issue by yogiperdana** [OpenSID/OpenSID#5606]
### Jelaskan error yg dialami

Bug/error:  input data kia ibu selain istri ( menantu, dll ) belum bisa

### Cara untuk mereplikasi errornya

Tambah KIA di menu stunting

### Hasil yg diharapkan

Normal

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.09

### Informasi tambahan

Sepertinya terjadi masalah ketika penggabungan dari bug

**Comment by vickyrolanda** [comment]
Mas saya coba test ini :  ya saat ini tidak muncul mas bsia diperbaiki.
<img width="752" alt="image" src="https://user-images.githubusercontent.com/59082428/188943221-16232924-f9c0-48c0-9090-7801ced06444.png">
1. Ibu (ibu Muncul) 
<img width="545" alt="image" src="https://user-images.githubusercontent.com/59082428/188943649-d4d7899f-517b-44b2-b91a-01a6e8e7da24.png">

2. Anak (anak tidak muncul)
<img width="581" alt="image" src="https://user-images.githubusercontent.com/59082428/188943553-cd7a3e67-2ac2-4753-9687-6a3edf54c697.png">

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1326
