### ISSUE TITLE
Bug/error:  Surat Biodata Penduduk corrupt pada saat di buka filenya.

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#5607]
### Jelaskan error yg dialami

saat membuka file surat muncul seperti ini : ini perlu perbaikan kemungkinan bug di isi surat sehingga membuat file menjadi corrupt.
<img width="469" alt="image" src="https://user-images.githubusercontent.com/59082428/188844645-59345a55-2a6a-40df-84c7-8bc545cf3716.png">

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.09-premium

**Comment by andifahruddinakas** [comment]
Mas @vickyrolanda, sy coba cetak surat tsb tidak ada masalah.

[surat_bio_penduduk_5201140706966997_2022-09-08_1.zip](https://github.com/OpenSID/OpenSID/files/9508844/surat_bio_penduduk_5201140706966997_2022-09-08_1.zip)

Pastikan menggunakan template bawaan saat pengecekan.
