### ISSUE TITLE
Bug/error: pengaturan footer tidak bisa diupdate

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#5608]
### Jelaskan error yg dialami

Saat melakukan perubahan di pengaturan footer surat saat di klik tombol simpan perubahan tersebut tidak tersimpan

### Cara untuk mereplikasi errornya

- layanan surat
- pengaturan surat
- pengaturan
- footer

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.09-premium-rev1

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1310
