### ISSUE TITLE
Peta legenda Penduduk

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#5613]
Tidak ada yang tampil saat memilih legenda penduduk/keluarga
![peta filter penduduk](https://user-images.githubusercontent.com/57283157/189056635-f9f08ab0-2f0a-4522-af8c-9a948c57216e.png)

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1318
