### ISSUE TITLE
Bug/error: terjadinya error pada sidebar

### ISSUE THREAD

**Issue by FirlianiF** [OpenSID/OpenSID#5616]
### Jelaskan error yg dialami

Sidebar selalu scroll keatas pada saat klik menu yang ada dropdown nya khusus nya dihalaman home.

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

seperti opensid umum.

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

22.09-premium rev.1

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1330
