### ISSUE TITLE
Bug/error: tambahkan validasi di input RW

### ISSUE THREAD

**Issue by FirlianiF** [OpenSID/OpenSID#5617]
### Jelaskan error yg dialami

saat menginput rw masih bisa di masukan kalimat seperti "RW 001", harusnya hanya masukan angka saja seperti input RT.

### Cara untuk mereplikasi errornya

1. Info Desa > Wilayah Administratif
2. Klik tombol rincian sub wilayah
3. tambah / edit data rw

### Hasil yg diharapkan

Tersimpan hanya angka saja

### Tangkapan layar dan log error

![rw](https://user-images.githubusercontent.com/30171560/189115893-ae8142f3-f9d2-4078-a1ad-8303d0c600f9.PNG)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Versi 22.09-premium-rev01

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1316
