### ISSUE TITLE
Bug/error: tambahkan validasi di tambah / edit data wilayah administratif

### ISSUE THREAD

**Issue by FirlianiF** [OpenSID/OpenSID#5618]
### Jelaskan error yg dialami

saat ini ketika memasukan "desa citapen" / "dusun citapen" akan tersimpan sesuai yang di input beserta sebutan desa yang di nput nya, sedangkan pada import penduduk telah divalidasi untuk value nya divalidasi jadi hanya nama desa nya saja yang tersimpan, sebutan desa nya otomatis terhapus.

### Cara untuk mereplikasi errornya

1. Info desa
2. wilayah administratif
3. tambah data dengan diawali sebutan desa yang sama dengan pengaturan sebutan desa.

### Hasil yg diharapkan

sebutan desa otomatis terhapus seperti saat import data penduduk

### Tangkapan layar dan log error

![desaaa](https://user-images.githubusercontent.com/30171560/189117066-08e33119-32e7-4fb1-a64f-5296188c29ef.PNG)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Versi 22.09-premium-rev01

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1315
