### ISSUE TITLE
Bug/error: impor data siskuedes terkait file ta_pemda yang membuat error

### ISSUE THREAD

**Issue by FirlianiF** [OpenSID/OpenSID#5619]
### Jelaskan error yg dialami

Error saat impor data siskuedes terkait file ta_pemda yang membuat error,

note: laporan dari pak ariandi

### Cara untuk mereplikasi errornya

1. keuangan
2. Impor
3. Pilih file > simpan

### Hasil yg diharapkan

data dapat tersimpan dengan baik / tidak error, tidak harus di modifikasi manual file nya, karena saat ini agar berhasil data nya di modifikasi manual terlebih dahulu.

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Versi 22.09-premium-rev01

**Comment by andifahruddinakas** [comment]
Mas @devrakapriyo, sediakan cobtoh siskuedes yg error saat di impor tsb

**Comment by devrakapriyo** [comment]
iya mas filenya ada di pak Ariandi, tetapi 1 file yang menyebabkan bug saat import sudah di replace dengan file yang benar sehingga tidak terjadi bug

coba saya followup ke pak Ariandi untuk diminta file yang saat di import menyebabkan bug

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1319
