### ISSUE TITLE
Permintaan fitur: Penyesuaian formulir f2-01 dengan format terbaru

### ISSUE THREAD

**Issue by FirlianiF** [OpenSID/OpenSID#5620]
### Apa kekurangan yg ingin diatasi?

[Formulir-F2-01.pdf](https://github.com/OpenSID/OpenSID/files/9526633/Formulir-F2-01.pdf)

### Jelaskan solusi yg diinginkan

-

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

22.08-premium rev.1

**Comment by andifahruddinakas** [comment]
Duplicate issue https://github.com/OpenSID/OpenSID/issues/5259
