### ISSUE TITLE
Bug/error: ttd mengetahui kosong, unduh RTF surat keterangan lahir

### ISSUE THREAD

**Issue by FirlianiF** [OpenSID/OpenSID#5621]
### Jelaskan error yg dialami

ttd mengetahui kosong di file PDF hasil unduh RTF surat keterangan lahir
![pdf_surat_keterangan_lahir](https://user-images.githubusercontent.com/30171560/189120153-528ac66b-df13-4439-b750-64853a20abab.PNG)

### Cara untuk mereplikasi errornya

1. Layanan Surat
2. Cetak Surat
3. Surat Keterangan Kelahiran
4. Unduh RTF
5. Extract file
6. Lihat file PDFnnya

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.09-premium-rev1

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1314
