### ISSUE TITLE
Bug/error: QR Code penanda tangan hilang

### ISSUE THREAD

**Issue by FirlianiF** [OpenSID/OpenSID#5623]
### Jelaskan error yg dialami

saat cetak surat TinyMCE, saat di unduh file PDF yang berisikan QRCODE didalamnya menjadi hilang
![cetak_qrcode](https://user-images.githubusercontent.com/30171560/189126629-5888a8d4-5d2d-4bf6-b60c-14dd29cbdcf1.PNG)
![hasil_qrcode](https://user-images.githubusercontent.com/30171560/189126660-ef85de35-d42b-406f-be09-2b78e0139627.PNG)

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.09-premium-rev1

**Comment by andifahruddinakas** [comment]
Mas @devrakapriyo, pastikan di pengaturan surat sudah memilih untuk menggunakan qrcode.
![qrcode](https://user-images.githubusercontent.com/57283157/189181628-a823a97d-61f7-48cf-8a61-b89ed14446c4.png)

[surat_raw_tinymce_5201145003976995_2022-09-08_1.pdf](https://github.com/OpenSID/OpenSID/files/9528901/surat_raw_tinymce_5201145003976995_2022-09-08_1.pdf)

tambahkan ke panduan untuk memperjelas

**Comment by devrakapriyo** [comment]
iya mas sudah, di klik Ya

**Comment by andifahruddinakas** [comment]
> iya mas sudah, di klik Ya

cek di https://berputar.opendesa.id/

**Comment by vickyrolanda** [comment]
Saya check muncul jika pengaturan qrcode di aktifkan : 
<img width="535" alt="image" src="https://user-images.githubusercontent.com/59082428/189799360-aa22df2c-1fca-4fd9-a5be-add32c2594b6.png">

**Comment by devrakapriyo** [comment]
issue ini sudah saya cek kembali dan sudah solved
