### ISSUE TITLE
Permintaan fitur: Lengkapi Identitas Desa

### ISSUE THREAD

**Issue by muhtar-coder** [OpenSID/OpenSID#5626]
### Apa kekurangan yg ingin diatasi?

Identitas desa belum lengkap

### Jelaskan solusi yg diinginkan

tersedia informasi identitas desa yang lengkap 

1. penambahan info identitas desa 
![image](https://user-images.githubusercontent.com/55665526/189174192-7ea7bcbe-0ea3-474a-87f1-3947be776536.png)

2. view informasi identitas desa
![image](https://user-images.githubusercontent.com/55665526/189174038-60dfdf85-306c-4889-a070-60367d570a15.png)

### Apakah ada alternatif lain

tidak ada

### Untuk versi OpenSID mana

22.10-premium

### Informasi tambahan

-

**Comment by mranca** [comment]
Setuju

**Comment by andifahruddinakas** [comment]
Duplicate issue https://github.com/OpenSID/OpenSID/issues/7693
