### ISSUE TITLE
[TinyMCE] Tambahkan Pengaturan Ganti Logo pada Template Surat TinyMCE

### ISSUE THREAD

**Issue by Gunturwijay** [OpenSID/OpenSID#5628]
Logo surat yang digunakan selama ini berbeda dengan logo yang ada di sistem. pada template rtf dapat di edit manual, pada surat  TinyMCE belum dapat diedit

![image](https://user-images.githubusercontent.com/40741591/189424689-326a41ec-78e0-4122-aa34-5433b4c8cb46.png)

![image](https://user-images.githubusercontent.com/40741591/189425452-420ec85c-e0d4-4114-b48b-29e0de3d16d6.png)

**Comment by andifahruddinakas** [comment]
SOLUSI : 
1. Sediakan RFM pada editor TinyMCE, namu path perlu dikonversi dlu saat generate pdf
2. Sediakan upload logo di pengaturan aplikasi.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1478
