### ISSUE TITLE
Bug/error: Notifikasi jika anjungan terdeteksi tapi belum ada pesanan anjungan

### ISSUE THREAD

**Issue by rizazoel** [OpenSID/OpenSID#5631]
### Jelaskan error yg dialami

Ketika memasukkan IP Address pada menu Anjungan, dihalaman Layanan Mandiri tetap tidak terbaca bahwa IP tersebut merupakan IP Anjungan.

### Cara untuk mereplikasi errornya

1. Buka halaman siteman kemudian ke menu anjungan https://berputar.opendesa.id/anjungan
2. Tambah anjungan mandiri dengan memasukkan IP Address
3. Buka dihalaman https://berputar.opendesa.id/layanan-mandiri/masuk.
4. Halaman tidak terbaca sebagai Anjungan, dan keyboard virtual pun tidak muncul

### Hasil yg diharapkan

Pada halaman https://berputar.opendesa.id/layanan-mandiri/masuk seharusnya tertulis anjungan aktif, dan ketika klik form akan muncul Keyboard Virtual

### Tangkapan layar dan log error

![Screenshot_449](https://user-images.githubusercontent.com/41587971/189514975-7e6579d1-9b57-4a44-9d78-70b2247d8592.jpg)
![Screenshot_448](https://user-images.githubusercontent.com/41587971/189514976-aa82bb40-5455-4bbc-aeba-ad5b70642dd7.jpg)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Versi 22.09-premium-rev01

**Comment by andifahruddinakas** [comment]
Mas @devrakapriyo, @vickyrolanda, alur anjungan disesuaikan sesuai permintaan pelaksana, bisa dikonfirmasi ulang.

**Comment by ai-skematik** [comment]
> ### Jelaskan error yg dialami
> 
> Ketika memasukkan IP Address pada menu Anjungan, dihalaman Layanan Mandiri tetap tidak terbaca bahwa IP tersebut merupakan IP Anjungan.
> ### Cara untuk mereplikasi errornya
> 
>     1. Buka halaman siteman kemudian ke menu anjungan https://berputar.opendesa.id/anjungan
> 
>     2. Tambah anjungan mandiri dengan memasukkan IP Address
> 
>     3. Buka dihalaman https://berputar.opendesa.id/layanan-mandiri/masuk.
> 
>     4. Halaman tidak terbaca sebagai Anjungan, dan keyboard virtual pun tidak muncul
> 
> 
> ### Hasil yg diharapkan
> 
> Pada halaman https://berputar.opendesa.id/layanan-mandiri/masuk seharusnya tertulis anjungan aktif, dan ketika klik form akan muncul Keyboard Virtual
> ### Tangkapan layar dan log error
> 
> ![Screenshot_449](https://user-images.githubusercontent.com/41587971/189514975-7e6579d1-9b57-4a44-9d78-70b2247d8592.jpg) ![Screenshot_448](https://user-images.githubusercontent.com/41587971/189514976-aa82bb40-5455-4bbc-aeba-ad5b70642dd7.jpg)
> ### Rilis Versi OpenSID
> 
> Rilis Premium
> ### Versi OpenSID
> 
> Versi 22.09-premium-rev01
> ### Tema Yang Digunakan
> 
> _No response_
> ### Informasi tambahan
> 
> _No response_

**Comment by ai-skematik** [comment]
@rizazoel  perangkat hanya akan terbaca sebagai Anjungan jika membeli Perangkat Anjungan dari OpenDesa atau membeli lisensi Anjungan.

**Comment by eddieridwan** [comment]
@vickyrolanda @andifahruddinakas untuk kasus di mana perangkat terdaftar sebagai anjungan, tetapi belum memiliki pemesanan anjungan, sebaiknya ditampilkan notifikasi di form login tersebut menjelaskan hal itu -- supaya pengguna tidak bingung mengapa perangkat mereka tidak dikenal sebagai anjungan. Untuk kata2/notifikasi yg tepat bisa tanyakan pada bung @ai-skematik .

**Comment by rizazoel** [comment]
> @rizazoel perangkat hanya akan terbaca sebagai Anjungan jika membeli Perangkat Anjungan dari OpenDesa atau membeli lisensi Anjungan.

Kami sudah ada anjungannya pak. Untuk membeli lisensi anjungan nya dimana?

**Comment by andifahruddinakas** [comment]
> > @rizazoel perangkat hanya akan terbaca sebagai Anjungan jika membeli Perangkat Anjungan dari OpenDesa atau membeli lisensi Anjungan.
> 
> Kami sudah ada anjungannya pak. Untuk membeli lisensi anjungan nya dimana?

Bisa hubungi pelaksana di OpenDesa
