### ISSUE TITLE
Bug/error: [NO KK SEMENTARA] no kk sementara tidak berfungsi jika pecah kk apabila no kknya KK SEMENTARA 

### ISSUE THREAD

**Issue by Wiliyantoro** [OpenSID/OpenSID#5633]
### Jelaskan error yg dialami

tidak bisa Pecah KK karena No KK Sementara tidak muncul apabila sebelumnya no kknya masih no KK SEMENTARA

### Cara untuk mereplikasi errornya

1. home
2. Keluarga
3. filter KK meninggal/pindah/....
4. aksi pecah kk
5. checklist no kk sementara

### Hasil yg diharapkan

bisa melakukan pecah kk apabila no kk sementara

### Tangkapan layar dan log error

![BUG PECAH KK](https://user-images.githubusercontent.com/44520382/189580373-66b7f773-a6fc-4491-a525-fdfb49b34c90.png)
tapi jika awalnya sudah Punya KK Tetap, bisa melakukan Pecah kk dengan no KK Sementara
![BUG PECAH KK 1](https://user-images.githubusercontent.com/44520382/189580452-213dedb4-e26a-4ad0-994c-a5cc06d4914e.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.09-premium-rev01

**Comment by andifahruddinakas** [comment]
Mas @devrakapriyo, @vickyrolanda, saya coba duplikasi issue ini tapi tidak ada masalah. Mungkin bisa di cek dan dikonfirmasi ulang, lengkapi alur untuk menemukan error yang dimaksudkan issue ini.

**Comment by andifahruddinakas** [comment]
Mas @devrakapriyo, di local dan berputar tidak ada masalah. Mungkin masalah database, server atau lainnya. Untuk saat ini mungkin perlu di cek databasenya.

**Comment by devrakapriyo** [comment]
pak @Wiliyantoro apakah masih mengalami error? jika iya tolong kirimkan backup database ke telegram saya @rakapriyo

**Comment by devrakapriyo** [comment]
mas @andifahruddinakas setelah saya cek lagi jadi kasusnya itu dari KK sementara di pecah menjadi KK sementara yang menyebabkan tidak bisa mengklik simpan
untuk databasenya bisa akses di link gdrive

https://drive.google.com/drive/folders/1aOqM0vrOpig2-t2vabWxzsCypkv1jdFD?usp=sharing

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1377
