### ISSUE TITLE
Bug/error: NIK saksi tidak sesuai ketentuan

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#5634]
### Jelaskan error yg dialami

pada saat cetak surat Keterangan Kelahiran form input NIK saksi masih bisa diinput asal
- NIK kurang dari 16 digit
- NIK dapat di isi huruf dan simbol
- NIK bisa diinput lebih dari 16 digit

<img width="1440" alt="Screen Shot 2022-09-12 at 16 50 18" src="https://user-images.githubusercontent.com/36557759/189630521-5939fb80-f128-4661-8700-802d653eb5bf.png">
<img width="1092" alt="Screen Shot 2022-09-12 at 16 49 19" src="https://user-images.githubusercontent.com/36557759/189630543-fa7aa335-5a5c-403d-83af-30406e68dadc.png">

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.08-premium-rev02

**Comment by andifahruddinakas** [comment]
Mas @devrakapriyo, lain kali bisa di infokan surat2 apa saja yang perlu diperbaiki.

**Comment by vickyrolanda** [comment]
> Mas @devrakapriyo, lain kali bisa di infokan surat2 apa saja yang perlu diperbaiki.

ini surat apa ya mas @andifahruddinakas ?

**Comment by andifahruddinakas** [comment]
> > Mas @devrakapriyo, lain kali bisa di infokan surat2 apa saja yang perlu diperbaiki.
> 
> ini surat apa ya mas @andifahruddinakas ?

Bisa di lihat PR file change

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1331
