### ISSUE TITLE
Bug/error: clear cache di satukan dengan proses migrasi

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#5637]
### Jelaskan error yg dialami

saat ini fitur clear cache masih terpisah dengan proses migrasi, untuk mempermudah dalam 1 kali proses update agar fitur clear cache di satukan saat proses migrasi

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.08-premium-rev02

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1336
