### ISSUE TITLE
Bug/error: notifikasi kehadiran muncul angka 1

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#5638]
### Jelaskan error yg dialami

notifikasi kehadiran muncul angka 1
![image](https://user-images.githubusercontent.com/36557759/189856286-d3d185a7-e23d-4ec8-afde-6b5c3fd81dc6.png)

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

hilangkan angka 1

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.08-premium-rev02

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1339
