### ISSUE TITLE
Bug/error: kebutuhan sistem OpenSID

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#5639]
### Jelaskan error yg dialami

sesuai yang di laporkan pak @ariandii di group Telegram Pengelolaan Hosting OpenDesa
![image](https://user-images.githubusercontent.com/36557759/189856819-54abd3c6-44cd-46e9-a85f-c9a013aed065.png)
notifikasi versi PHP dan Database memenuhi syarat, tetapi aplikasi tidak berjalan dengan normal.

pertanyaan saya, apakah OpenSID belum support versi 8 PHP dan databasenya

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.08-premium-rev02

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1338
