### ISSUE TITLE
Bug/error: error 500 saat ubah Buku Tanah Kas Desa

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#5640]
### Jelaskan error yg dialami

saat mengubah data Buku Tanah Kas Desa terjadi error 500 ketika klik Simpan
<img width="1440" alt="Screen Shot 2022-09-13 at 16 01 26" src="https://user-images.githubusercontent.com/36557759/189859721-c156c53e-f7d7-411b-9a29-11978f3b65c7.png">

### Cara untuk mereplikasi errornya

- klik menu Buku Administrasi Desa
- klik menu Buku Administrasi Umum
- klik menu Buku Tanah Kas Desa
- klik tombol ubah

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.08-premium-rev02

**Comment by devrakapriyo** [comment]
info dari pak @ai-skematik muncul error

Query error: Column 'luas' cannot be null - Invalid query: UPDATE tanah_kas_desa SET nama_pemilik_asal = '1', letter_c = '001', kelas = '2', luas = NULL, asli_milik_desa = '10000', pemerintah = '0', provinsi = '0', kabupaten_kota = '0', lain_lain = '0', sawah = '10000', `tegal
= '0', kebun = '0', tambak_kolam = '0', tanah_kering_darat = '0', ada_patok = '10000', tidak_ada_patok = '0', ada_papan_nama = '0', tidak_ada_papan_nama = '10000', tanggal_perolehan = '2012-11-10', lokasi = '-', peruntukan = '4', mutasi = '-', keterangan = '-', updated_at = '2022-09-13 13:41:42', updated_by = 1, visible = 1WHERE id = '1'

sedangkan kolom luas ada isinya

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1340
