### ISSUE TITLE
Bug/error: 

### ISSUE THREAD

**Issue by luxmant354** [OpenSID/OpenSID#5641]
### Jelaskan error yg dialami

Buku Mutasi Penduduk, ketika di cetak/ di unduh maka filter tidak berfungsi (semua data mutasi penduduk terunduh)

### Cara untuk mereplikasi errornya

1. Buku Administrasi Desa
2. Administrasi Penduduk
3. pilih buku mutasi penduduk, meskipun tidak di filter / status kosong tidak ada kegiatan mutasi penduduk di bulan tersebut ketika di klik cetak, maka akan muncul semua data kependudukan.

### Hasil yg diharapkan

Menu cetak / unduh sesuai Filter Bulan dan tahun kegiatan mutasi penduduk berfungsi sebagaimana mestinya

### Tangkapan layar dan log error

![Screenshot_50](https://user-images.githubusercontent.com/44687953/189892959-712129ad-f272-4143-a72b-55c854119acf.jpg)
![Screenshot_16](https://user-images.githubusercontent.com/44687953/189892969-a354d7e3-d4ee-401a-9182-badca910d2b3.jpg)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

premium (v22.09-premium-rev02)

### Tema Yang Digunakan

esensi

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1341
