### ISSUE TITLE
Bug/error: template tinymce tidak teratur

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#5642]
Jika melakukan ubah struktur tabel sedikit saja, maka tampilan surat akan jadi berantakan. Misanya mengubah ukuran box penanda tangan.

**Comment by andifahruddinakas** [comment]
@ai-skematik

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1344
