### ISSUE TITLE
Bug/error: Sebuah kesalahan basis data terjadi

### ISSUE THREAD

**Issue by pemdespancur** [OpenSID/OpenSID#5643]
### Jelaskan error yg dialami

1146

Table 'sid_pancur.ref_penduduk_hamil' doesn't exist
Bagaimana cara mengatasi ini ?

### Cara untuk mereplikasi errornya

Tiap buka database atau menambah penduduk baru langsung auto logout

### Hasil yg diharapkan

Perbaikan database

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/34035346/190049178-67810923-0219-48cc-9070-ff2538f3e175.png)

### Rilis Versi OpenSID

Rilis Umum

### Versi OpenSID

22.09

### Tema Yang Digunakan

cosmo

**Comment by andifahruddinakas** [comment]
Untuk sementara bisa jalankan perintah sql berikut di phpMyAdmin : 
```
#
# TABLE STRUCTURE FOR: ref_penduduk_hamil
#

DROP TABLE IF EXISTS `ref_penduduk_hamil`;

CREATE TABLE `ref_penduduk_hamil` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `nama` varchar(100) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8;

INSERT INTO `ref_penduduk_hamil` (`id`, `nama`) VALUES (1, 'Hamil');
INSERT INTO `ref_penduduk_hamil` (`id`, `nama`) VALUES (2, 'Tidak Hamil');
```

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1346

**Comment by pemdespancur** [comment]
Terimakasih banyak....masalah sudah teratasi
