### ISSUE TITLE
Bug/error: penandatanganan halaman kerja sama tidak sesuai

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#5644]
### Jelaskan error yg dialami

![image](https://user-images.githubusercontent.com/36557759/190059750-4bc54aa7-ad4e-4df0-8205-606edb253d23.png)
tertera di info desa, kepala desa a.n Muhammad Ilham sedangkan di halaman kerja sama penandatanganan a.n Mustahiq S.ADM
![image](https://user-images.githubusercontent.com/36557759/190060229-62608a84-65ae-4097-a9f3-cad13d9b98aa.png)

### Cara untuk mereplikasi errornya

- klik menu info desa
- klik menu pendaftaran kerja sama
- unduh halaman kerja sama

### Hasil yg diharapkan

seharusnya penandatanganan halaman kerja sama itu Kepala Desa

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.08-premium-rev02

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1347
