### ISSUE TITLE
Urutan jabatan tidak sesuai

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#5648]
![jabatan 3](https://user-images.githubusercontent.com/57283157/190208992-5da3df13-fabb-42cb-bb80-28bce76ce58e.png)

**Comment by Sukoharjo3** [comment]
ditukar saja itu diedit bisa, kmrn punya saya tak edit

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1352
