### ISSUE TITLE
Sesuaikan cara deteksi anjungan opendesa

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#5649]
Cek pembahasan : 
https://github.com/OpenSID/OpenSID/issues/5631
https://github.com/OpenSID/premium/pull/1342

**Comment by andifahruddinakas** [comment]
Kerjakan issue ini setelah PR https://github.com/OpenSID/premium/pull/1353 digabungkan.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1361
