### ISSUE TITLE
Bug/error: id_penduduk kosong yang menyebabkan surat tidak muncul

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#5650]
### Jelaskan error yg dialami

beberapa surat tidak muncul di arsip dan permohonan, ketika cek di database id_penduduk kosong.

laporan dari pengguna desa sukoharjo, kategori surat non warga tidak muncul
![image](https://user-images.githubusercontent.com/36557759/190307419-d67b7c0e-1859-4c53-a431-fcb19149ef00.png)

setelah di cek ternyata id_pend nya null
![image](https://user-images.githubusercontent.com/36557759/190307383-ce1a8c2a-2a27-4002-8a0d-96319b995afe.png)

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.09-premium-rev2

**Comment by devrakapriyo** [comment]
dikarenakan non warga tidak mempunyai id_pend yang menyebabkan surat tidak muncul

**Comment by Wiliyantoro** [comment]
rolenya tampilkan di permohonan surat jika id_penduduk null ambil nik_non_warga / nama_non_warga, apabila ada surat yang tidak mengirimkan id_penduduk , nik_non_warga, nama_non_warga seperti surat ubahan desa contoh surat undangan dll , ambil id suratnya, ini hanya saran pak @devrakapriyo

**Comment by Sukoharjo3** [comment]
> rolenya tampilkan di permohonan surat jika id_penduduk null ambil nik_non_warga / nama_non_warga, apabila ada surat yang tidak mengirimkan id_penduduk , nik_non_warga, nama_non_warga seperti surat ubahan desa contoh surat undangan dll , ambil id suratnya, ini hanya saran pak @devrakapriyo

betul ini, diberi role tambahan jika null menuju ke nama atau bisa mendeteksi null

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1356
