### ISSUE TITLE
Bug/error: surat permohonan dan arsip tidak muncul di akun kades atau sekdes 

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#5651]
### Jelaskan error yg dialami

daftar surat permohonan dan arsip tidak muncul akun dengan role admin kades dan sekdes sedangkan akun admin selain kades dan sekdes muncul
![image](https://user-images.githubusercontent.com/36557759/190308038-f184d0df-7007-46eb-af33-5b30eb586fed.png)

### Cara untuk mereplikasi errornya

- klik menu layanan surat
- klik menu arsip layanan

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.08-premium-rev02

**Comment by andifahruddinakas** [comment]
Mas @devrakapriyo, ini harapannya mau di apakan? Mas @vickyrolanda, coba di cek issue ini, untuk solusinya. Karena seblumnya di desain seperti ini, dimana surat yang tampil di kades atau sekdes tampil sesuai dengan pengaturan untuk membedakan yang mana perlu diverifikasi. Coba diperjelas lg alur surat ini.

**Comment by andifahruddinakas** [comment]
Duplicate issue https://github.com/OpenSID/OpenSID/issues/5518
