### ISSUE TITLE
Bug/error: Data too long for column

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#5652]
### Jelaskan error yg dialami

perlu di tambahkan max lenght di inputan masing masing form sesuai lenght value field nya
CATATAN : saya akan coba data masing masing form

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.08-premium-rev02

**Comment by andifahruddinakas** [comment]
1. sys_traffic
![sys_traffic](https://user-images.githubusercontent.com/57283157/190548870-8b90712e-93fb-475a-b4ae-fcd76cb4f81f.png)

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1362
