### ISSUE TITLE
Ambil Foto dengan Kamera Tidak Jalan jika tidak https/ssl

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#5653]
![cam 2](https://user-images.githubusercontent.com/57283157/190334163-bc289643-615a-43ae-9f48-6f2f3beaa3ad.png)
![cam 1](https://user-images.githubusercontent.com/57283157/190334179-66b0d539-c65d-4a83-bdce-b1a82654e303.png)

**Comment by pandigresik** [comment]
setau saya untuk akses kamera menggunakan browser harus dari domain yang secure, yang sudah https atau dari localhost saja

**Comment by andifahruddinakas** [comment]
> setau saya untuk akses kamera menggunakan browser harus dari domain yang secure, yang sudah https atau dari localhost saja

Ya, solusinya hanya disable tombol dan berikan informasi jika domain not secure.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1358
