### ISSUE TITLE
Permintaan fitur: [PREMIUM] Format output Lampiran Formulir F-2.01 disesuaikan berdasarkan Permendagri Nomor 109 Tahun 2019

### ISSUE THREAD

**Issue by mah-mudi** [OpenSID/OpenSID#5654]
### Apa kekurangan yg ingin diatasi?

Format output Lampiran Formulir **F-2.01** yang dihasilkan dari menu **Layanan Surat -> Cetak Surat** masih menggunaan format lama. Berikut Hasil nya :
![surat_ket_kelahiran_5201144609786995_2022-09-15_4_lampiran_page-0001](https://user-images.githubusercontent.com/57661283/190440294-f43c0272-e282-461b-b5b3-661046460d6a.jpg)

### Jelaskan solusi yg diinginkan

Format output Lampiran Formulir **F-2.01** yang dihasilkan dari menu **Layanan Surat -> Cetak Surat** disesuaikan berdasarkan Permendagri Nomor 109 Tahun 2019.

Formulir pelaporan Pencatatan Sipil di dalam wilayah Negara Kesatuan Republik Indonesia (Formulir **F-2.01**)  untuk pelayanan pencatatan:
1) kelahiran;
2) lahir mati;
3) perkawinan;
4) pembatalan perkawinan;
5) perceraian;
6) pembatalan perceraian;
7) kematian;
8) pengangkatan anak;
9) pengakuan anak;
10) pengesahan anak;
11) perubahan nama;
12) perubahan status kewarganegaraan;
13) perubahan peristiwa penting lainnya; dan
14) pembetulan dan pembatalan akta Pencatatan Sipil.

Mengingat Formulir **F-2.01** ini **MEMERLUKAN TANDA TANGAN KEPALA DESA** dan Formulir ini digunakan untuk 14 pelayanan pencatatan diatas.

Diharapkan output cetak surat pada layanan surat OPENSID dapat menampilkan Formulir **F-2.01** dengan format berikut : 
![Permendagri-No-109-Th-2019-Lampiran-Tentang-Formulir-dan-Buku-Yang-Digunakan-Dalam-Administrasi-Kependudukan_page-0048](https://user-images.githubusercontent.com/57661283/190440909-16b7d9cc-ec50-4d8d-986a-bd0ec8597926.jpg)

![Permendagri-No-109-Th-2019-Lampiran-Tentang-Formulir-dan-Buku-Yang-Digunakan-Dalam-Administrasi-Kependudukan_page-0049](https://user-images.githubusercontent.com/57661283/190441038-3e363414-8b28-434a-a7e9-85f6f66a6cec.jpg)

![Permendagri-No-109-Th-2019-Lampiran-Tentang-Formulir-dan-Buku-Yang-Digunakan-Dalam-Administrasi-Kependudukan_page-0050](https://user-images.githubusercontent.com/57661283/190441133-6bc19969-65c0-46ca-ab7f-9b2c570c78ab.jpg)

![Permendagri-No-109-Th-2019-Lampiran-Tentang-Formulir-dan-Buku-Yang-Digunakan-Dalam-Administrasi-Kependudukan_page-0051](https://user-images.githubusercontent.com/57661283/190441189-b330889e-d429-47d9-b91c-1e0695468db6.jpg)

### Apakah ada alternatif lain

Formulir **F-2.01** berdasarkan Permendagri Nomor 109 Tahun 2019 merupakan satu-satunya Formulir yang memerlukan tanda-tangan Kepala Desa. 

### Untuk versi OpenSID mana

OpenSID 22.11 Premium

### Informasi tambahan

[Permendagri-No-109-Th-2019-Lampiran-Tentang-Formulir-dan-Buku-Yang-Digunakan-Dalam-Administrasi-Kependudukan.pdf](https://github.com/OpenSID/OpenSID/files/9576400/Permendagri-No-109-Th-2019-Lampiran-Tentang-Formulir-dan-Buku-Yang-Digunakan-Dalam-Administrasi-Kependudukan.pdf)

**Comment by andifahruddinakas** [comment]
Duplicate issue https://github.com/OpenSID/OpenSID/issues/5259
