### ISSUE TITLE
Error saat cetak surat TinyMCE dengan font bookman_old_style

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#5656]
<img width="629" alt="image" src="https://user-images.githubusercontent.com/59082428/190891962-2d1847cf-d0ec-4784-91ec-a28ab1069eb9.png">

ERROR - 2022-09-18 14:48:55 --> Severity: error --> Exception: TCPDF ERROR: Could not include font definition file: bookman_old_style C:\xampp\htdocs\OpenDesa\OpenSID\vendor\tecnickcom\tcpdf\tcpdf.php 3007

**Comment by andifahruddinakas** [comment]
Mas @vickyrolanda, font bookman_old_style hanya tersedia di rilis-dev, di bug-fix belum ada. Coba dibedakan database yang digunakan untuk test rilis-dev dan bug-fix atau reset database setiap PR yang ada migrasinya. Kecuali hal ini berlaku di rilis-dev (beri label susulan) bisa mention mas @yogiperdana yang mengerjakan issue tsb. https://github.com/OpenSID/OpenSID/issues/5555

**Comment by yogiperdana** [comment]
Saya coba normal mas

**Comment by yogiperdana** [comment]
Unduhan font arial:
[surat_raw_tinymce_5201142005716996_2022-09-19_1.pdf](https://github.com/OpenSID/OpenSID/files/9596669/surat_raw_tinymce_5201142005716996_2022-09-19_1.pdf)

Unduhan font bookman:
[surat_raw_tinymce_5201145003976995_2022-09-19_2.pdf](https://github.com/OpenSID/OpenSID/files/9596674/surat_raw_tinymce_5201145003976995_2022-09-19_2.pdf)

Unduhan font impact:
[surat_raw_tinymce_5201141003666996_2022-09-19_3.pdf](https://github.com/OpenSID/OpenSID/files/9596675/surat_raw_tinymce_5201141003666996_2022-09-19_3.pdf)

**Comment by andifahruddinakas** [comment]
> Saya coba normal mas

masih belum jelas issuenya, kayaknya dari database rilis-dev yang settingan font defaultnya pakai font bookman yang dipakai di bug-fix. Jadinya bakal error karena font bookman belum tersedia di bug-fix.

**Comment by vickyrolanda** [comment]
> > Saya coba normal mas
> 
> masih belum jelas issuenya, kayaknya dari database rilis-dev yang settingan font defaultnya pakai font bookman yang dipakai di bug-fix. Jadinya bakal error karena font bookman belum tersedia di bug-fix.

konfirmasi mas @andifahruddinakas & mas @yogiperdana  saya check memang saya salah test saya test di bug-fix. saat ini sudah saya konfirmasi dan jalan di rilis-dev.
