### ISSUE TITLE
Bug/error: Unknown column 'telegram' in 'field list'

### ISSUE THREAD

**Issue by pemdespancur** [OpenSID/OpenSID#5658]
### Jelaskan error yg dialami

Unknown column 'telegram' in 'field list'

Ketika input data kk baru dan di save muncul notivikasi berikut

### Cara untuk mereplikasi errornya

Gagal dalam penyimpanan data penduduk baru

### Hasil yg diharapkan

Dapat menambah jumlah penduduk

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/34035346/190944542-48142009-bba1-45a6-85f0-42e4a4152f75.png)

### Rilis Versi OpenSID

Rilis Umum

### Versi OpenSID

22.09

### Tema Yang Digunakan

cosmo

**Comment by devrakapriyo** [comment]
@pemdespancur tolong kirimkan backup database desanya ke telegram saya @rakapriyo

**Comment by andifahruddinakas** [comment]
Migrasi tidak jalan sempurna, coba lakukan migrasi database lagi.

**Comment by pemdespancur** [comment]
Tidak bisa migrasi database
![image](https://user-images.githubusercontent.com/34035346/191397634-cf1c9f77-9b31-452f-ab80-0e8fb6864e9b.png)
