### ISSUE TITLE
Bug/error: Tidak dapat membuat dusun pada wilayah administratif 

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/OpenSID#5659]
### Jelaskan error yg dialami

Ketika inputkan dusun baru di wilayah administratif tidak tampil, kemudian setelah di cek dari database terinput 3.
Pada Versi 22.08 bisa berjalan normal.

### Cara untuk mereplikasi errornya

1. Masuk he halaman admin.
2. Klik Modul Info Desa
3. Pilih Wilayah Administratif
4. Klik Tambah Dusun
5. Masukan Nama Dusun
6. Klik Simpan

### Hasil yg diharapkan

Dapat berfungsi normal agar dapat masukan dusun baru.

### Tangkapan layar dan log error

Tangkapan Layar di halaman admin
![testdusun2](https://user-images.githubusercontent.com/68048807/190945574-f1c0cf6a-7c75-4034-8a5e-334004e76857.JPG)

Tangkapan Layar pada database
![test dusun](https://user-images.githubusercontent.com/68048807/190945361-ededec1f-ac13-4a4b-8eba-52fba2b836e3.JPG)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.09-premium-beta03

### Informasi tambahan

Issue ini dilaporkan oleh Pak @ai-skematik, mohon segera ditindaklanjuti karena akan digunakan untuk presentasi (Urgent).

**Comment by devrakapriyo** [comment]
Mas @andifahruddinakas saya cek di dev.opendesa.id berjalan normal dan domain ini untuk rev 3, apakah issue ini ada sangkut paut dengan issue yang sudah di perbaiki di rev 3 mas?

**Comment by scqolbu24** [comment]
saya baru coba di https://dev.opendesa.id/index.php/sid_core tidak bisa mas

**Comment by devrakapriyo** [comment]
Iya mas, saya salah lihat
Dan masih bug di dev opendesa

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1366
