### ISSUE TITLE
Usul perubahan form upload

### ISSUE THREAD

**Issue by telo99** [OpenSID/OpenSID#566]
untuk form upload dokumen & galeri, sepertinya lebih menarik dan ringan jika menggunakan model popup seperti di gambar ini:
![updok](https://user-images.githubusercontent.com/30897391/29390011-d70dbdc0-8317-11e7-9559-0e6ce9da762d.jpg)

dibandingkan dengan yang sekarang:
![updok2](https://user-images.githubusercontent.com/30897391/29390135-a3219d78-8318-11e7-9953-50421212833f.jpg)

**Comment by hadyanwijaya** [comment]
sama saja...

**Comment by afa28** [comment]
Sudah di `master`
