### ISSUE TITLE
Bug/error: Update Konten Artikel Statis

### ISSUE THREAD

**Issue by ferdianhadi** [OpenSID/OpenSID#5661]
### Jelaskan error yg dialami

selamat siang pak, saya mendapatkan bug update konten artikel statis menggunakan hak akses operator,
lalu saat saya login menggunakan hak akses operator dan melakukan update pada artikel statis, dan menekan tombol simpan otomatis terlogout sendiri, setelah itu saya coba login menggunakan superadmin saya mendapatkan error sbb

### Cara untuk mereplikasi errornya

1. Login Sebagai Operator
2. Edit Halaman Artikel Statis
3. Klik Tombol simpan ketika telah selesai update
4. Sistem otomatis logut dari akun operator
5. Mencoba login sebagai Admin Super
6. sistem menampilkan halaman periksa database dan menampilkan notif error (Unknown column 'a.id_user' in 'where clause')

### Hasil yg diharapkan

Sistem berhasil mengupdate pembaruan data

### Tangkapan layar dan log error

![ss-2209](https://user-images.githubusercontent.com/43235033/190949042-9ce8ed09-9851-4fb8-acd7-05b5b5f780c4.jpg)

### Rilis Versi OpenSID

Rilis Umum

### Versi OpenSID

22.09

### Tema Yang Digunakan

esensi-main

**Comment by ariandii** [comment]
https://github.com/OpenSID/OpenSID/issues/5269
