### ISSUE TITLE
Bug/error: fitur filter buku induk penduduk tidak berfungsi

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#5663]
### Jelaskan error yg dialami

fitur filter bulan dan tahun buku induk penduduk tidak berfungsi

<img width="1440" alt="Screen Shot 2022-09-19 at 13 35 30" src="https://user-images.githubusercontent.com/36557759/190963122-833c96fd-bb4a-45f8-85dc-54795dff9365.png">

### Cara untuk mereplikasi errornya

- klik menu Buku Administrasi Desa
- klik menu Administrasi Penduduk
- klik menu Buku Induk Penduduk

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.08-premium-rev02

**Comment by andifahruddinakas** [comment]
Mas @devrakapriyo, Ini tidak ada masalah.
![laporan](https://user-images.githubusercontent.com/57283157/190968726-7c8a712e-d156-41a9-8583-4e6b4acb07d2.png)

Mungkin perlu dipahami filter pada bagian bumindes penduduk atau dibeberapa modul lainnya itu menggunakan <=, jadi data sebelumnya sebelum thn dan bln tsb tetap tampil. Beda di beberapa modul, filternya =, dimana tahun yang ditampilkan tahun yang difilter saja.

**Comment by devrakapriyo** [comment]
baik mas, makasih infonya saya close issue ini
