### ISSUE TITLE
Bug/error: issue 5616 susulan

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#5664]
### Jelaskan error yg dialami

setelah di cek lebih lanjut sidebar menu dropdown jika di klik masih scroll ke atas, bisa dibandingkan dengan opensid umum sidebar menu dropdown tidak ter scroll ke atas

issue susulan : https://github.com/OpenSID/OpenSID/issues/5616

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

seperti opensid umum

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.08-premium-rev02

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1370
