### ISSUE TITLE
Bug/error: icon kunci diubah menjadi lonceng pada navbar

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#5665]
### Jelaskan error yg dialami

![image](https://user-images.githubusercontent.com/36557759/190983661-2f6fa14b-d633-493e-a661-649f0f904eff.png)

ubah icon kunci menjadi lonceng 
![image](https://user-images.githubusercontent.com/36557759/190983781-581c9986-bf0f-4b1c-91f9-5d0110e520b9.png)

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.09-premium-rev2

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1371

**Comment by andifahruddinakas** [comment]
Mas @vickyrolanda, karena perubahan 2 tempat, saat gabunga bug-fix ke rilis-dev perlu dicek ulang.
