### ISSUE TITLE
Buat anjungan menjadi modul agar bisa di pilih menjadi menu dipengaturan menu.

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#5666]
Tambahkan menu anjungan pada pengaturan menu seperti dibawah ini 
<img width="564" alt="image" src="https://user-images.githubusercontent.com/59082428/191082373-efb5b085-471c-4266-99db-690421bf177c.png">
dimana ketika memilih anjungan maka muncul sub berdasarkan list anjungan yang terdaftar dan aktif
* Syarat lain adalah menu ini akan muncul jika anjungan telah aktif dan telah memesan lisensi anjungan

**Comment by ai-skematik** [comment]
Bung @vickyrolanda  apa maksud anjungan 1 dan anjungan 2 di tangkapan layar diatas ?

**Comment by ai-skematik** [comment]
> Tambahkan menu anjungan pada pengaturan menu seperti dibawah ini 
> <img width="564" alt="image" src="https://user-images.githubusercontent.com/59082428/191082373-efb5b085-471c-4266-99db-690421bf177c.png">
> dimana ketika memilih anjungan maka muncul sub berdasarkan list anjungan yang terdaftar dan aktif
> * Syarat lain adalah menu ini akan muncul jika anjungan telah aktif dan telah memesan lisensi anjungan

Bung @vickyrolanda  menambah menu adalah menambah halaman statis domain/anjungan. bukan memilih perangkat perangkat anjungan.

**Comment by vickyrolanda** [comment]
> > Tambahkan menu anjungan pada pengaturan menu seperti dibawah ini
> > <img alt="image" width="564" src="https://user-images.githubusercontent.com/59082428/191082373-efb5b085-471c-4266-99db-690421bf177c.png">
> > dimana ketika memilih anjungan maka muncul sub berdasarkan list anjungan yang terdaftar dan aktif
> > 
> > * Syarat lain adalah menu ini akan muncul jika anjungan telah aktif dan telah memesan lisensi anjungan
> 
> Bung @vickyrolanda menambah menu adalah menambah halaman statis domain/anjungan. bukan memilih perangkat perangkat anjungan.

yg ini salah pak , keamren sudah kami diskusikan juga.
