### ISSUE TITLE
Bug/error: terbalik nya fungsi gembok anjungan

### ISSUE THREAD

**Issue by FirlianiF** [OpenSID/OpenSID#5670]
### Jelaskan error yg dialami

status anjungan digembok tetapi masih terdeteksi anjungan di Layanan Mandiri nya.
sedangkan jika gembok terbuka, anjungan menjadi nonaktif.

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

![photo_2022-09-20_10-48-49](https://user-images.githubusercontent.com/30171560/191163259-44eeb4d9-1767-4831-bfb4-fdd8e09cd510.jpg)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.09-premium-rev3

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1361
