### ISSUE TITLE
Bug/error: error ketika tambah perangkat anjungan

### ISSUE THREAD

**Issue by FirlianiF** [OpenSID/OpenSID#5671]
### Jelaskan error yg dialami

error ketika tambah perangkat anjungan.
sebagai info tambahan, sudah klik migrasidb, namun tetap gagal tambah anjungan.

### Cara untuk mereplikasi errornya

![photo_2022-09-20_10-52-29](https://user-images.githubusercontent.com/30171560/191163724-177a78d5-5e31-463f-9b47-5c665fe1b526.jpg)

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

![photo_2022-09-20_10-52-41](https://user-images.githubusercontent.com/30171560/191167910-ee091d7c-2d8c-4fc8-810a-d904ac8bd220.jpg)
![photo_2022-09-20_10-52-35](https://user-images.githubusercontent.com/30171560/191167914-aecd0d02-a066-4068-910e-e70f3a1ccbe4.jpg)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.09-premium-rev3

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1376
