### ISSUE TITLE
Bug/error: email verifikasi tidak terkirim saat pendaftaran kerjasama

### ISSUE THREAD

**Issue by FirlianiF** [OpenSID/OpenSID#5672]
### Jelaskan error yg dialami

email verifikasi tidak terkirim saat pendaftaran kerjasama

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.09-premium-rev3

**Comment by andifahruddinakas** [comment]
saya coba melakukan pendaftaran kerjasama, dan berhasil terkirim.

Cuma, kalau menggunakan email yang sudah pernah terdaftar akan gagal tanpa notifikasi yang jelas dari layanan. Coba cek di `'email' => "required|valid_email|is_unique[users.email,email,{$this->request->getPost('email')}]",`

![verif2](https://user-images.githubusercontent.com/57283157/192194365-62f44b3d-7377-4de6-b4b0-c86d9720760a.jpg)
![verif1](https://user-images.githubusercontent.com/57283157/192194369-d1dee218-cfc6-47f6-801c-c46748299d85.jpg)
![erif](https://user-images.githubusercontent.com/57283157/192194370-86ad836c-722b-429d-8c97-7fe1308548fc.jpg)

**Comment by vickyrolanda** [comment]
> saya coba melakukan pendaftaran kerjasama, dan berhasil terkirim.
> 
> Cuma, kalau menggunakan email yang sudah pernah terdaftar akan gagal tanpa notifikasi yang jelas dari layanan. Coba cek di `'email' => "required|valid_email|is_unique[users.email,email,{$this->request->getPost('email')}]",`
> 
> ![verif2](https://user-images.githubusercontent.com/57283157/192194365-62f44b3d-7377-4de6-b4b0-c86d9720760a.jpg) ![verif1](https://user-images.githubusercontent.com/57283157/192194369-d1dee218-cfc6-47f6-801c-c46748299d85.jpg) ![erif](https://user-images.githubusercontent.com/57283157/192194370-86ad836c-722b-429d-8c97-7fe1308548fc.jpg)

mbak @FirlianiF mohon bantuan untuk check ini ya mbak

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1397
