### ISSUE TITLE
Bug/error: Gagal migrasi untuk instal baru tanpa token

### ISSUE THREAD

**Issue by FirlianiF** [OpenSID/OpenSID#5673]
### Jelaskan error yg dialami

Migrasi terhenti di 217 table dari seharusnya 231 table. Gagal Hanya untuk install baru dan tanpa token.
Kalau di masukkan tokennya terlebih dulu, baru lancar.

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

V22.09-premium Rev 3

**Comment by andifahruddinakas** [comment]
Sy coba tidak ada masalah (tanpa token), jumlah tabel 224 dan view 5, di cek mas @devrakapriyo

**Comment by apidong** [comment]
> Sy coba tidak ada masalah (tanpa token), jumlah tabel 224 dan view 5, di cek mas @devrakapriyo

mungkin terkena request timeout. karena di server secara default max_execution timenya 60 detik. jika melebihi itu, proses akan berhenti. alternatif lain agar tidak terkena request timout, migrasi dijalankan lewat terminal

**Comment by vickyrolanda** [comment]
untuk bug ini @FirlianiF saya sudah check di saya normal , saya stuju dengan mas @apidong kemungkinan max_execution_timenya. 

kalo memang ini sering jadi masalah mungkin bisa di tambahkan didaftar checklist syarat install mas @agungsugiarto untuk menaikkan limit max_execution_timenya dengan standart yang kita tentukan.

hasil saya test normal : 
<img width="952" alt="image" src="https://user-images.githubusercontent.com/59082428/192362026-ebf1193d-3170-46a3-94aa-79ed033f057e.png">

**Comment by agungsugiarto** [comment]
mas @vickyrolanda berapa maksimal max max_execution_timenya ?

**Comment by vickyrolanda** [comment]
> mas @vickyrolanda berapa maksimal max max_execution_timenya ?

coba aja tambah mas 3600 mas @agungsugiarto

**Comment by apidong** [comment]
@vickyrolanda @agungsugiarto 
alternatif untuk awal instalasi. jalankan php index.php dari teriminal. karena perintah php di terminal biasanya bebas dari max_execution_time

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1400
