### ISSUE TITLE
Bug/error: Tidak bisa menambahkan anggot Rumah Tangga lebih dari 7 orang

### ISSUE THREAD

**Issue by hasap86** [OpenSID/OpenSID#5674]
### Jelaskan error yg dialami

Saat menambahkan anggota Rumah Tangga lebih dari 7 orang tidak bisa. kotak pencarian penduduk tidak bisa diketik

### Cara untuk mereplikasi errornya

tambahkan anggota Rumah Tangga lebih dari 7 orang

### Hasil yg diharapkan

bisa menambahkan anggota Rumah Tangga lebih dari 7 orang

### Tangkapan layar dan log error

![tambah anggota rumah tangga](https://user-images.githubusercontent.com/45263721/191614941-3932994b-30f0-4a6a-8924-e3a7325cb93b.jpg)

### Rilis Versi OpenSID

Rilis Umum

### Versi OpenSID

22.09

### Tema Yang Digunakan

Natra V4.5

**Comment by devrakapriyo** [comment]
pak @hasap86 apakah ini masih 1 issue yang sama?

https://github.com/OpenSID/OpenSID/issues/5676

**Comment by hasap86** [comment]
beda menu

**Comment by hasap86** [comment]
![dev-rt](https://user-images.githubusercontent.com/45263721/191728688-e3851b6d-b5a1-452b-9424-8c9c8e904189.jpg)

setelah mengisi 7 anggota, coba tambahkan anggota ke 8 dengan cara mengetikan di form pencarian penduduk

**Comment by devrakapriyo** [comment]
pak @hasap86 setelah saya cek, di tambah anggota rumah tangga saya masih bisa menambahkan di pencarian penduduk

**Comment by hasap86** [comment]
> pak @hasap86 setelah saya cek, di tambah anggota rumah tangga saya masih bisa menambahkan di pencarian penduduk

bisa di skrinsut tampilannya...

**Comment by devrakapriyo** [comment]
<img width="1440" alt="Screen Shot 2022-09-23 at 16 07 58" src="https://user-images.githubusercontent.com/36557759/191928067-af60f86e-dc6a-4362-a3d7-637ea330aa6f.png">

seperti ini pak

**Comment by hasap86** [comment]
> <img alt="Screen Shot 2022-09-23 at 16 07 58" width="1440" src="https://user-images.githubusercontent.com/36557759/191928067-af60f86e-dc6a-4362-a3d7-637ea330aa6f.png">
> 
> seperti ini pak

ia bener, saya tidak bisa ketik itu doi formnya di laptop 11" disini :)

**Comment by eddieridwan** [comment]
@devrakapriyo periksa apakah modal dialog itu bisa di-scroll pada layar kecil.

**Comment by vickyrolanda** [comment]
mas @andifahruddinakas saya ketemu error ini : 
caranya : 
1. klik tambah anggota tapi jangn di save cukup close saja 
2. jangan di refresh lalu klik lagi tambah anggota dan select maka muncul seperti dibawah ini 
<img width="458" alt="image" src="https://user-images.githubusercontent.com/59082428/192364140-e668d565-e46a-43e4-b936-f58247b33b40.png">

**Comment by andifahruddinakas** [comment]
> mas @andifahruddinakas saya ketemu error ini : caranya :
> 
> 1. klik tambah anggota tapi jangn di save cukup close saja
> 2. jangan di refresh lalu klik lagi tambah anggota dan select maka muncul seperti dibawah ini
> 
> <img alt="image" width="458" src="https://user-images.githubusercontent.com/59082428/192364140-e668d565-e46a-43e4-b936-f58247b33b40.png">

sy coba tidak ada masalah.

**Comment by andifahruddinakas** [comment]
> mas @andifahruddinakas saya ketemu error ini : caranya :
> 
> 1. klik tambah anggota tapi jangn di save cukup close saja
> 2. jangan di refresh lalu klik lagi tambah anggota dan select maka muncul seperti dibawah ini
> 
> <img alt="image" width="458" src="https://user-images.githubusercontent.com/59082428/192364140-e668d565-e46a-43e4-b936-f58247b33b40.png">

untuk kasus ini sudah dibuatkan PR https://github.com/OpenSID/premium/pull/1403

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1403
