### ISSUE TITLE
Bug/error: Tidak bisa menambahkan anggota keluarga lebih dari 5 orang

### ISSUE THREAD

**Issue by hasap86** [OpenSID/OpenSID#5676]
### Jelaskan error yg dialami

saat menambahkan anggota keluarga lebih dari 5, form pencarian penduduk tidak bisa diketik

### Cara untuk mereplikasi errornya

tambahkan anggota keluarga lebih dari 5 orang

### Hasil yg diharapkan

bisa menambahkan anggota keluarga lebih dari 5 orang

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Umum

### Versi OpenSID

v22.09

### Tema Yang Digunakan

Natra V4.5

**Comment by devrakapriyo** [comment]
selamat sore pak @hasap86, setelah saya coba replikasi di dev.opendesa.id berjalan normal
bisa tolong replikasikan lebih detailnya pak?

**Comment by hasap86** [comment]
![dev-keluarga](https://user-images.githubusercontent.com/45263721/191729236-25d01dac-83d4-4203-abfa-de089f77ce26.jpg)

tambahkan lebih dari 5 anggota keluarga, tambahkan dari penduduk yang sudah ada, lakukan pencarian, itu tidak bisa diketik pencarian penduduknya. sudah saya coba juga di dev.

**Comment by devrakapriyo** [comment]
<img width="1440" alt="Screen Shot 2022-09-23 at 09 29 59" src="https://user-images.githubusercontent.com/36557759/191882109-9b99ef98-01a9-4ae0-a7fa-085980a1ed54.png">

setelah saya cek, ini tidak hanya berlaku untuk jumlah anggota keluarga lebih dari 5 orang tetapi semua anggota keluarga.

pencarian anggota keluarga itu berlaku untuk penduduk yang tidak memiliki KK

**Comment by devrakapriyo** [comment]
pak @hasap86 bisa coba jika salah satau penduduk di keluarkan dari anggota keluarga tersebut, dan tambahkan di keluarga lain maka penduduk tersebut akan keluar di pencarian penduduk

**Comment by hasap86** [comment]
> <img alt="Screen Shot 2022-09-23 at 09 29 59" width="1440" src="https://user-images.githubusercontent.com/36557759/191882109-9b99ef98-01a9-4ae0-a7fa-085980a1ed54.png">
> 
> setelah saya cek, ini tidak hanya berlaku untuk jumlah anggota keluarga lebih dari 5 orang tetapi semua anggota keluarga.
> 
> pencarian anggota keluarga itu berlaku untuk penduduk yang tidak memiliki KK

betul, pencarian itu untuk penduduk yg tidak memiliki kk makanya mau dimasukan...
di saya masalahnya form ketikan untuk pencarian posisi mouse tidak bisa di posisikan di form pencarian...

coba ketikan di form pencarian beberapa kata dan skrinsut.

**Comment by devrakapriyo** [comment]
<img width="1440" alt="Screen Shot 2022-09-23 at 16 09 29" src="https://user-images.githubusercontent.com/36557759/191928310-2ef433ce-c89b-4df3-8ac8-031b390149b1.png">

seperti ini pak

**Comment by hasap86** [comment]
> <img alt="Screen Shot 2022-09-23 at 16 09 29" width="1440" src="https://user-images.githubusercontent.com/36557759/191928310-2ef433ce-c89b-4df3-8ac8-031b390149b1.png">
> 
> seperti ini pak

saya ke laptop 11", itu tidak bisa diketik di form pencariannya kalo lebih dari 5

**Comment by eddieridwan** [comment]
@devrakapriyo periksa apakah modal dialog itu bisa di-scroll pada layar kecil.

**Comment by andifahruddinakas** [comment]
> > <img alt="Screen Shot 2022-09-23 at 16 09 29" width="1440" src="https://user-images.githubusercontent.com/36557759/191928310-2ef433ce-c89b-4df3-8ac8-031b390149b1.png">
> > seperti ini pak
> 
> saya ke laptop 11", itu tidak bisa diketik di form pencariannya kalo lebih dari 5

Sy coba sesuaikan dengan perangkat 11" tidak menemukan error tsb.

https://www.webmobilefirst.com/en/screencasts/dlDQtqKDXP/

**Comment by ruririzal** [comment]
kemungkinan disebabkan karena ini jika search box pada select2 tidak bisa mendapat fokus kursor : 
https://select2.org/troubleshooting/common-problems

solusi yg bisa dicoba :
![image](https://user-images.githubusercontent.com/28647065/192084150-1193c269-7ae6-40a8-9595-6e607b5d7dbb.png)

**Comment by vickyrolanda** [comment]
mas @andifahruddinakas saya ketemu error ini : 
caranya : 
1. klik tambah anggota tapi jangn di save cukup close saja 
2. jangan di refresh lalu klik lagi tambah anggota dan select maka muncul seperti dibawah ini 
<img width="458" alt="image" src="https://user-images.githubusercontent.com/59082428/192364140-e668d565-e46a-43e4-b936-f58247b33b40.png">

**Comment by vickyrolanda** [comment]
mas @andifahruddinakas saya ketemu error ini :
caranya :

1. klik tambah anggota tapi jangn di save cukup close saja
2. jangan di refresh lalu klik lagi tambah anggota dan select maka muncul seperti dibawah ini 

(jika tidak muncul error bisa ulangin hal di atas beberapa kali tanpa di refresh) lalu kadang ketika dari layar besar saya pindah ke layar kecil memang formnya tidak bisa di klik tpi ketika di refresh bisa lagi. 

<img width="743" alt="image" src="https://user-images.githubusercontent.com/59082428/192365926-085af21a-35be-4c51-9a26-63ec59a8db95.png">

**Comment by andifahruddinakas** [comment]
> mas @andifahruddinakas saya ketemu error ini : caranya :
> 
> 1. klik tambah anggota tapi jangn di save cukup close saja
> 2. jangan di refresh lalu klik lagi tambah anggota dan select maka muncul seperti dibawah ini
> 
> (jika tidak muncul error bisa ulangin hal di atas beberapa kali tanpa di refresh) lalu kadang ketika dari layar besar saya pindah ke layar kecil memang formnya tidak bisa di klik tpi ketika di refresh bisa lagi.
> 
> <img alt="image" width="743" src="https://user-images.githubusercontent.com/59082428/192365926-085af21a-35be-4c51-9a26-63ec59a8db95.png">

untuk kasus ini sudah dibuatkan PR https://github.com/OpenSID/premium/pull/1403

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1403
