### ISSUE TITLE
Penambahan tombol mengeluarkan perangkat desa yang lupa absen

### ISSUE THREAD

**Issue by yogiperdana** [OpenSID/OpenSID#5678]
Buat log aktivitasnya

**Comment by yogiperdana** [comment]
Untuk issue ini apakah tombol hanya muncul ketika berada di luar jam kerja/libur atau dapat dimunculkan setiap status perangkat hadir mas @vickyrolanda

**Comment by eddieridwan** [comment]
@yogiperdana khusus untuk perangkat yg hadir di luar jam kerja/libur.

**Comment by yogiperdana** [comment]
> @yogiperdana khusus untuk perangkat yg hadir di luar jam kerja/libur.

Jika demikian sepertinya tombol ini tidak berguna pak. Karena saat ini ketika opensid diakses dari halaman manapun di luar jam kerja maka perangkat yang lupa absen statusnya akan berubah pak

**Comment by yogiperdana** [comment]
Jadi status akan berubah terlebih dahulu sebelum tombol ditekan bahkan sebelum halaman sebelum halaman rekapitulasi dibuka

**Comment by eddieridwan** [comment]
@yogiperdana apakah ada kasus/situasi di mana status tidak terubah secara otomatis? Kalau tidak ada, issue ini tidak diperlukan.

**Comment by yogiperdana** [comment]
Issue ini ditutup karena saat ini perangkat yang lupa absen statusnya akan berubah secara otomatis ketika berada di luar jam kerja https://github.com/OpenSID/OpenSID/issues/5677
