### ISSUE TITLE
Bug/error: gagal migrasi desa pancur

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#5679]
### Jelaskan error yg dialami

ada pengguna yang melaporkan gagal migrasi saat update versi 22.09-premium-rev03 dari 22.08
setelah saya cek memang gagal migrasi, di log muncul pesan kekuarangan field dan duplikat NIK
terlampir database desa dan log error di gdrive OpenDesa

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.09-premium-rev3

**Comment by devrakapriyo** [comment]
link gdrive : https://drive.google.com/drive/folders/1TN1dgB6DdoeoKKoK4EvsKQpqkCskkN3B?usp=sharing

**Comment by hasap86** [comment]
cek di tabel kelompok, kelompok_anggota, kelompok_master
sama hapus NIK yg duplikat

saya juga begitu

**Comment by andifahruddinakas** [comment]
Mas @devrakapriyo, mungkin alur tambahan untuk pengecekan: 
- [ ] Jalankan pemeriksaan database terlebih dahulu, bisa buka domain/periksa
- [ ] Kosongkan semua log, dan migrasi ulang (biar log yang akan dikirim log terbaru)

**Comment by andifahruddinakas** [comment]
![kk ganda 1](https://user-images.githubusercontent.com/57283157/192009438-2c509d13-1db8-4c9b-84f0-d523d9f03b6d.png)
![panjang kk](https://user-images.githubusercontent.com/57283157/192009446-d30ba581-37ee-42dc-9095-3b5ca396fc68.png)
