### ISSUE TITLE
[Galeri] Tambahkan link ke galeri di admin galeri

### ISSUE THREAD

**Issue by telo99** [OpenSID/OpenSID#568]
Tambahkan anchor (link yang bisa diklik) saat berada di managemen galeri. Jadi sebagai admin bisa langsung menuju galeri tanpa harus ke home web > galeri > album.

![sidgaleri](https://user-images.githubusercontent.com/30897391/29390548-42531e42-831b-11e7-908e-37ed733fa01a.jpg)

**Comment by afa28** [comment]
Maksudnya ini bgmnaa???
