### ISSUE TITLE
Bug/error: Gambar tidak bisa terupload

### ISSUE THREAD

**Issue by JosMan200201** [OpenSID/OpenSID#5680]
### Jelaskan error yg dialami

Kami mengosongkan database karena ingin mengupload data penduduk dan mengedit semua untuk data desa, tapi ketika ingin mengupload gambar di artikel atau galeri, gambar tidak bisa terupload. Saya sudah mencoba untuk mengubah dimensi foto seperti normal dan mengubah besar file foto menjadi kecil tapi tetap tidak bisa. Mungkin masalahnya ada di website yang tidak bisa 

### Cara untuk mereplikasi errornya

1. Menu Utama
2. Admin Web
3. Artikel
4. Berita Desa
5. Mengisi Berita Desa
6. Semua bisa diisi dan berjalan dengan baik kecuali unggah gambar pada artikel dan tidak muncul di website resminya

### Hasil yg diharapkan

Mohon segera diperbaiki karna kami ingin membuat profil foto untuk desa kami terima kasih 

### Tangkapan layar dan log error

![Screenshot (349)](https://user-images.githubusercontent.com/114194425/191864735-98b24ec7-1c7e-4470-b1ac-38041d8e3c2b.png)

### Rilis Versi OpenSID

Rilis Umum

### Versi OpenSID

22.09

**Comment by devrakapriyo** [comment]
pak @JosMan200201 bisa tolongkan kirimkan log nya?

**Comment by andifahruddinakas** [comment]
Cek : 
- Sesuaikan struktur folder desa dengan folder desa_contoh
- Cek permisson folder

**Comment by syahidmid** [comment]
Saya juga mengalami, pak. Kasusnya persis, setelah Kosongkah Database, upload artikel gambarnya tidak muncul. Saya pernah melakukan ini sebelumnya tapi tidak masalah. Baru kali ini terjadi.

Kalau dari Resposnif File Manager seperti ini. Mohon bantuannya.

![Screenshot_1](https://user-images.githubusercontent.com/69981696/192049887-3df498f8-fbb6-4abd-be18-995381fc13dc.png)

**Comment by andifahruddinakas** [comment]
> Saya juga mengalami, pak. Kasusnya persis, setelah Kosongkah Database, upload artikel gambarnya tidak muncul. Saya pernah melakukan ini sebelumnya tapi tidak masalah. Baru kali ini terjadi.
> 
> Kalau dari Resposnif File Manager seperti ini. Mohon bantuannya.
> 
> ![Screenshot_1](https://user-images.githubusercontent.com/69981696/192049887-3df498f8-fbb6-4abd-be18-995381fc13dc.png)

Cek :

Sesuaikan struktur folder desa dengan folder desa_contoh
Cek permisson folder
