### ISSUE TITLE
Bug/error: Migrasi Awal

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/OpenSID#5681]
### Jelaskan error yg dialami

Pada saat uji coba install OpenSID Siap Pakai, ketika dicek pada master-api untuk env belum dapat dikonfigurasi seharusnya dapat dikonfigurasi secara otomatis ketika pertama kali install master-api, kemudian dilakukan penelusuran secara manual:
1. Jalankan perintah `php artisan:key generate` belum tersedia 
2. Jalankan perintah `php artisan` belum tersedia
3. Jalankan perintah `composer install` ditemukan error seperti berikut :
![tidak dapat install api](https://user-images.githubusercontent.com/68048807/191879279-d277690d-1c0a-4ca8-8fa1-f772c02ecca1.JPG) 
4. Kemudian dilakukan migrasi pada OpenSID Premium di Pengaturan -> Database -> Migrasi DB -> klik tombol `Migrasi Database ke OpenSID 22.09-premium-rev-03`  
5. Jalankan perintah kembali `composer install` dan `php artisan:key generate` pada OpenSID API sudah berjalan normal

### Cara untuk mereplikasi errornya

1. Unduh versi OpenSID premium terbaru di https://github.com/OpenSID/rilis-premium.git 
2. Buat database dan konfigurasi di desa/config/database.php serta desa/config/config.php
3. Jalankan pada browser web opensid premium
4. Unduh versi OpenSID API terbaru di https://github.com/OpenSID/rilis-opensid-api
5. Salin file env.example dan ubah menjadi .env
6. pada .env konigurasi database sesuai dengan nama database yang dibuat pada poin 2.
7. Jalankan perintah `composer install` akan muncul error seperti pada gambar yang ditampilkan pada Tangkapan Layar dan log error.

### Hasil yg diharapkan

Dapat migrasi dengan lancar sehingga pada OpenSID Siap Pakai dapat dilakukan secara otomatis.

### Tangkapan layar dan log error
Error pengetesan di local menggunakan OpenSID premium versi 22.09-premium dan API versi 22.09.01
![tidak dapat install api di lokal](https://user-images.githubusercontent.com/68048807/191882730-d9c0383d-5bcd-49e3-84cf-560957eb49c9.JPG)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.09-premium-rev03

### Informasi tambahan

pada versi 22.08-premium-rev04 dapat dilakukan install secara otomatis pada API yang ada di OpenSID Siap Pakai

**Comment by devrakapriyo** [comment]
mas @scqolbu24 saya sudah replikasi, dan hasilnya normal

<img width="583" alt="Screen Shot 2022-09-23 at 15 58 20" src="https://user-images.githubusercontent.com/36557759/191926397-7c79e77a-d26a-4940-9b4e-24702b4b2847.png">

**Comment by scqolbu24** [comment]
> mas @scqolbu24 saya sudah replikasi, dan hasilnya normal
> 
> <img alt="Screen Shot 2022-09-23 at 15 58 20" width="583" src="https://user-images.githubusercontent.com/36557759/191926397-7c79e77a-d26a-4940-9b4e-24702b4b2847.png">

@devrakapriyo Apakah sudah dicoba lakukan sesuai dengan yang ada di Cara Replikasi ? karena saya coba berulang kali gagal, itu terjadi di versi 22.09-premium dan rev untuk versi 22.08-premium-rev04 dan sebelumnya berjalan normal

**Comment by devrakapriyo** [comment]
di saya normal mas, pada saat proses migrasi OpenSID v22.09-preemium-rev03 dan jalankan composer install di OpenSID API

**Comment by apidong** [comment]
@scqolbu24 @devrakapriyo ini dikarenakan, saat intall baru opensid belum dilakukan migrasi. sehingga ada struktur tabel yang belum sesuai.

**Comment by scqolbu24** [comment]
> di saya normal mas, pada saat proses migrasi OpenSID v22.09-preemium-rev03 dan jalankan composer install di OpenSID API

Apakah databasenya sudah dibuat baru? dan dilakukan langkah demi langkah, jangan dilakukan bareng.

**Comment by scqolbu24** [comment]
> @scqolbu24 @devrakapriyo ini dikarenakan, saat intall baru opensid belum dilakukan migrasi. sehingga ada struktur tabel yang belum sesuai.

Iya betul mas, jika dilakukan secara otomatis di OpenSID Layanan Siap Pakai akhirnya tidak bisa
begitu juga saya lakukan secara manual sesuai tahapan yang ada di Cara Replikasi tetap tidak bisa:

1. Unduh versi OpenSID premium terbaru di https://github.com/OpenSID/rilis-premium.git
2. Buat database dan konfigurasi di desa/config/database.php serta desa/config/config.php
3. Jalankan pada browser web opensid premium
4. Unduh versi OpenSID API terbaru di https://github.com/OpenSID/rilis-opensid-api
5. Salin file env.example dan ubah menjadi .env
6. pada .env konigurasi database sesuai dengan nama database yang dibuat pada poin 2.
7. Jalankan perintah composer install akan muncul error seperti pada gambar yang ditampilkan pada Tangkapan Layar dan log error.

**Comment by devrakapriyo** [comment]
setelah di replikasi dengan mas @scqolbu24 tertanya teridentifikasi bug
yang sebelumnya saya testing menggunakan database desa yang sudah ada datanya, sedangkan tadi pure awal migrasi database kosong yang menyebabkan error Unknown column 'c.pamong_id'

**Comment by apidong** [comment]
perbaikan ada di API https://github.com/OpenSID/opensid-laravel/pull/29

**Comment by scqolbu24** [comment]
sudah diperbaiki melalui PR https://github.com/OpenSID/opensid-laravel/pull/27
