### ISSUE TITLE
Sebutan Kepala Desa ada di 2 tempat

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#5682]
sebutan kepala_desa ada di setting dan sekarang ada juga di modul jabatan.

kondisi saat ini jika edit jabatan akan merubah sebutan_kepala_desa yang ada di setting, tp tidak berlaku sebaliknya.

Solusi : 
Hapus pengaturan sebutan_kepala_desa, dengan ketentuan variable $this->setting->sebutan_kepala_desa masih bisa digunakan (defaultnya diambil dari jabatan dengan id = 1)

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1391
