### ISSUE TITLE
[TinyMCE] Lampiran Surat

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#5683]
Sesuaikan pemanggilan lampiran surat, saat ini lampiran surat disertakan di masing2 surat yang membutuhkan. Hal ini menyebabkan banyaknya duplikasi. Hal ini berpengaruh saat melakukan ubah lampiran (misalnya F-1.01) dimana harus mengganti semua lampiran tsb di semua surat yang menggunakan.

Solusi : 
1. Tempatkan lampiran di folder khusus (sudah diterapkan)
2. Panggil lampiran surat berdasar pengaturan surat tsb menggunakan folder lampiran (bukan lagi pada masing2 surat), di TinyMCE menggunakan cara ini.
3. Sediakan agar desa bisa menambah/mengubah lampirannya sendiri (sediakan di folder desa/template-surat/lampiran)
4. Pastikan cara lama dan baru tetap berjalan.

**Comment by andifahruddinakas** [comment]
Untuk konversi lampiran agar bisa digunakan di TinyMCE bisa dibuatkan issue masing2 lampiran.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1492
