### ISSUE TITLE
Bug/error: error 500 import bantuan desa sarimekar-buleleng.opendesa.id

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#5684]
### Jelaskan error yg dialami

pengguna dari desa tersebut melaporkan error saat import di menu bantuan, setelah saya cek di log muncul pesan error

Query error: Incorrect date value: '' for column 'kartu_tanggal_lahir' at row 1 - Invalid query: INSERT INTO `program_peserta`

database desa dan file import sudah di upload di gdrive OpenDesa

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

22.09-premium-rev03

### Tema Yang Digunakan

-

### Informasi tambahan

-

**Comment by devrakapriyo** [comment]
link gdrive OpenDesa : https://drive.google.com/drive/folders/1pH38ifJDaceNfFkDWEG0RUFMsM7IAbn5?usp=sharing

**Comment by devrakapriyo** [comment]
info tambahan, jika di kolom tempat tanggal lahir dan alamat di isi pada file excel, maka berhasil terimport
seharusnya tanpa mengisi data tersebut sudah ada dari table penduduk

**Comment by andifahruddinakas** [comment]
Mas @devrakapriyo, untuk issue mengenai impor, sertakan juga contoh file yang gagal impor tsb.

**Comment by devrakapriyo** [comment]
> link gdrive OpenDesa : https://drive.google.com/drive/folders/1pH38ifJDaceNfFkDWEG0RUFMsM7IAbn5?usp=sharing

ini mas @andifahruddinakas

**Comment by andifahruddinakas** [comment]
> > link gdrive OpenDesa : https://drive.google.com/drive/folders/1pH38ifJDaceNfFkDWEG0RUFMsM7IAbn5?usp=sharing
> 
> ini mas @andifahruddinakas

ok

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1401
