### ISSUE TITLE
Bug/error: peta tidak berfungsi dan nama dusun hilang desa tanjungrejo-waykanan.desa.id

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#5685]
### Jelaskan error yg dialami

peta tidak berfungsi dan nama dusun hilang saat update ke 22.09-premium-rev03

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.09-premium-rev3

**Comment by devrakapriyo** [comment]
terlampir database di gdrive OpenDesa : https://drive.google.com/drive/folders/1pBDdu0BQCgonKS7NmThOEiqEecYHq8tw?usp=sharing

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/1390
