### ISSUE TITLE
Bug/error: penyesuaian panjang karaketer id peserta/no peserta DTKS

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#5686]
### Jelaskan error yg dialami

Penyesuaian panjang karakter di menu bantuan untuk input kolom id peserta/no peserta dengan maxlenght 36

![image](https://user-images.githubusercontent.com/36557759/191967612-104497f1-e36c-47df-8b01-87522b1f8ee7.png)

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.09-premium-rev3

**Comment by andifahruddinakas** [comment]
Mas @devrakapriyo, isian tsb belum tersedia di penduduk, harusnya issue ini berupa fitur.

**Comment by eddieridwan** [comment]
@devrakapriyo , apakah anda sudah verifikasi dulu laporan bug ini? Apakah mereka menggunakan versi ubahan?

**Comment by vickyrolanda** [comment]
mas @devrakapriyo mohon bantuannya sumber ini dapatnya darimana, karena butuh jga nanyak dari penggunanya perihal DTKS jika ini versi ubahan, mungkin setidaknya bisa kasih masukkan sedikit tetnang DTKS, jika ada penggunanya bisa kasih informasinya agar bisa saya kontak mas.

**Comment by eddieridwan** [comment]
@devrakapriyo @vickyrolanda jika masalah ini terkait versi ubahan, tutup saja. Beritahu pelapor. Masalah seperti itu perlu diatasi oleh yg membuat ubahan, bukan OpenDesa.

**Comment by andifahruddinakas** [comment]
Issue ini bukan menggunakan rilis resmi, melainkan menggunakan versi ubahan.
