### ISSUE TITLE
Bug/error: error ketika edit surat lama (rtf)

### ISSUE THREAD

**Issue by yogiperdana** [OpenSID/OpenSID#5688]
### Jelaskan error yg dialami

error ketika edit surat lama (rtf)

### Cara untuk mereplikasi errornya

Edit surat rtf lalu simpan

### Hasil yg diharapkan

Normal

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.09-premium beta-04

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1395
