### ISSUE TITLE
Bug/error: layanan mandiri siap di ambil tanpa di buatkan surat.

### ISSUE THREAD

**Issue by apidong** [OpenSID/OpenSID#5690]
### Jelaskan error yg dialami

-

### Cara untuk mereplikasi errornya

1. Buat permohonan surat melalui layanan mandiri, semisal surat raw tinymce
![image](https://user-images.githubusercontent.com/20056421/192155802-e1d8b14b-e520-4844-8811-28803aa24758.png)
2. Setelah permohonan surat melalui layanan mandiri selesai, buat sebuah surat dengan nama surat yang sama melalui layanan surat > cetak surat tanpa merubah nomor surat
![image](https://user-images.githubusercontent.com/20056421/192155922-73f445e9-af5c-4853-8505-ef38c8e90270.png)
3. verifikasi surat tsb sampai masuk ke arsip.
![image](https://user-images.githubusercontent.com/20056421/192155970-725925d5-ee78-488e-8e69-df4bafa0f1c8.png)

4. cek kembali pengajuan surat pada layanan mandiri. dan hasilnya surat yang barusan kita ajukan statusnya menjadi siap diambil. padahal surat tsb belum pernah dibuat.
![image](https://user-images.githubusercontent.com/20056421/192156009-8cff5c3c-3d1d-423e-9b6f-2e2c973f08ca.png)

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

22.09 premium-rev-04

### Tema Yang Digunakan

-

### Informasi tambahan

-

**Comment by vickyrolanda** [comment]
mas @agungsugiarto mohon bantuannya untuk nyelesaikan issue ini mas

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1420
