### ISSUE TITLE
Tampilkan status TTE demo jika menggunakan modul eSign demo / modul BSrE belum terpasang

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#5691]
Karena TTE sudah berhasil maka informasi di bawah perlu di hilangkan jika TTE berhasil diterapkan.
<img width="798" alt="image" src="https://user-images.githubusercontent.com/59082428/192157689-ccace0b6-90b3-4500-bdd2-45c5383f9b0e.png">

1. Saat ini syarat pengaturan tte harus ada akun kepala desa
2. Maka perlu adanya pemeriksaan NIK penandatangan yaitu kepala desa untuk dilakukan verifikasi (karena saat ini verifikasi hanya dapat di check dengan NIK dan alamat API yang valid maka 
3. Dibuat kondisi jika NIK Kepala Desa valid dari API URL maka informasi demo dapat disembunyikan dan akan muncul jika nik kepala desa tidak valid saat simpan pengaturan TTE.

**Comment by eddieridwan** [comment]
@vickyrolanda @agungsugiarto masih diperlukan. Seperti kita sudah bicarakan sebelumnya, desa yg belum memperoleh TTE, perlu bisa melihat simulasi TTE. Jadi informasi demo/simulasi hanya dihilangkan kalau modul BSrE betulan telah terpasang. Yaitu perlu bisa membedakan antara modul BSrE betulan dengan yg bersifat demo.

**Comment by vickyrolanda** [comment]
> @vickyrolanda @agungsugiarto masih diperlukan. Seperti kita sudah bicarakan sebelumnya, desa yg belum memperoleh TTE, perlu bisa melihat simulasi TTE. Jadi informasi demo/simulasi hanya dihilangkan kalau modul BSrE betulan telah terpasang. Yaitu perlu bisa membedakan antara modul BSrE betulan dengan yg bersifat demo.

baik pak sudah sy tambahkan dideskripsi.

**Comment by vickyrolanda** [comment]
mas @agungsugiarto : 
saya coba ganti NIK kepala desa dan setting namun tetap tidak muncul demonya , harusnya tetap muncul mas.
<img width="759" alt="image" src="https://user-images.githubusercontent.com/59082428/192733199-f8610497-34b4-49dc-838a-5c174b7d98f9.png">

**Comment by agungsugiarto** [comment]
mas @vickyrolanda, mode demo hanya jika `URL API Server TTE` adalah sama dengan domain web desa masing2, jika dilihat punya mas vicky urlnya adalah `tte-dev.kamparkab.go.id`

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1402
