### ISSUE TITLE
Bug/error: file name unduh Jalan, Irigasi dan Jaringan tidak sama 

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#5692]
### Jelaskan error yg dialami

pada saat unduh excel di Jalan, Irigasi dan Jaringan name file excel tersebut menjadi Inventaris_Peralatan.xls yang seharusnya Jalan_Irigasi_Jaringan.xls

![image](https://user-images.githubusercontent.com/36557759/192227586-1cf3eca5-dbfc-4ea8-b754-11ecfd9df883.png)

![image](https://user-images.githubusercontent.com/36557759/192227609-57422713-8881-4faf-80c2-d31c8d947ae1.png)

### Cara untuk mereplikasi errornya

- klik menu Seketariat
- klik menu Inventaris
- klik menu Jalan, Irigasi dan Jaringan
- klik unduh

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.09-premium-rev3

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1399
