### ISSUE TITLE
Bug/error: cetak surat TinyMCE blank

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#5693]
### Jelaskan error yg dialami

saat cetak surat TinyMCE file PDF menjadi blank 

![image](https://user-images.githubusercontent.com/36557759/192453539-0c0e4c22-579e-4637-a361-a052a5b1919b.png)

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.09-premium-beta04

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/OpenSID/issues/5693
