### ISSUE TITLE
Bug/error: Stunting - nomor RT RW stuning tidak muncul

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#5694]
### Jelaskan error yg dialami

<img width="1440" alt="Screen Shot 2022-09-27 at 14 06 30" src="https://user-images.githubusercontent.com/36557759/192457587-a8d25859-d0a7-4007-b1e7-fb4417284946.png">

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.09-premium-beta04

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1406
