### ISSUE TITLE
Data  RT / RW Dusun tidak tampil di stunting 

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#5695]
Pada menu stunting -> KIA 
<img width="592" alt="image" src="https://user-images.githubusercontent.com/59082428/192457858-43140669-3a57-48cc-b223-d11cf872a1ae.png">

**Comment by devrakapriyo** [comment]
mas @vickyrolanda sepertinya ini duplicate issue

https://github.com/OpenSID/OpenSID/issues/5694
