### ISSUE TITLE
Admin auto logout setelah hanya buka link /kehadiran

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#5696]
- [ ] halaman admin terlogout setelah mengunjungin halaman  domain/kehadiran

cara testnya : 
1. buka halaman admin 
2. lalu buka domain/kehadiran
3. refresh halaman admin maka terlogout

**Comment by andifahruddinakas** [comment]
Ini udah ada PRnya

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1405
