### ISSUE TITLE
Jabatan tidak muncul menu statistik

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#5700]
<img width="940" alt="image" src="https://user-images.githubusercontent.com/59082428/192468753-130f878a-e86f-4bb0-b1d7-166abb25e126.png">

**Comment by andifahruddinakas** [comment]
Mas @vickyrolanda, bisa di cek ulang. Sudah ikut terselesaikan melalui PR https://github.com/OpenSID/premium/pull/1398
