### ISSUE TITLE
Pengaturan Waktu Kadaluarsa Token OTP 

### ISSUE THREAD

**Issue by syahidmid** [OpenSID/OpenSID#5706]
### Jelaskan error yg dialami

Waktu kadaluarsa token OTP yang dikirim ke email user oleh sistem OpenSID saat pengguna melakukan registrasi saat ini adalah 1 menit. Menurut saya, waktu 1 menit ini terlalu singkat. 

Ada banyak faktor yang menyebabkan OTP cukup lama didapatkan oleh user seperti kecepatan internet di daerah sampai karena faktor email hostingnya (yang menurut pihak hosting saya, bisa delay 1-3 menit). 

Akibatnya, pengguna selalu gagal melakukan registrasi. 

### Cara untuk mereplikasi errornya

Saya coba test sebagai user untuk memasukkan token OTP yang didapatkan kemudian memasukkanya lagi ke formulir pendaftaran, hasilnya selalu gagal karena token selalu kadaluarsa. 

### Hasil yg diharapkan

- Durasi waktu kadaluarsa OTP email ditambah minimal sampai 5 menit. 
-  Mohon informasinya jika administrator ingin mengubah waktu kadaluarsa tersebut (custom)

Sebagai referensi, waktu kadaluarsa OTP dari platfrom eWallet DANA adalah 10 menit. 

### Tangkapan layar dan log error

![Screenshot_10](https://user-images.githubusercontent.com/69981696/192505090-8d7c41af-cac3-433e-8cef-4d99c4026a25.png)

### Rilis Versi OpenSID

Rilis Umum

### Versi OpenSID

22.09

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1472
