### ISSUE TITLE
Bug/error: Perbaiki token tidak terbaca karena hapus cache 

### ISSUE THREAD

**Issue by FirlianiF** [OpenSID/OpenSID#5707]
### Jelaskan error yg dialami

Saat ini untuk desa yang server nya diluar opendesa, banyak yang mengalami token selalu terhapus / tidak terbaca karena menggunakan cloudflare.

Solusi:
Buatkan pengaturan aktifkan otomatisasi hapus cache layanan pelanggan.
Jika Ya, maka fungsi hapus cache otomatis akan berjalan seperti biasa nya
Jika Tidak, maka fungsi hapus cache otomatis tidak akan dijalankan, karena akan membuat token tidak terbaca dikarenakan oleh cloudflare.

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.09-premium-rev4

**Comment by cepiandiana** [comment]
Betul, Solusi yang saya lakukan sementara adalah :
1. Minta Token Baru
2. Input Token di phpmyadmin
3. Ketika aplikasi opensid sudah bisa diakses kembali, tidak menekan tombol batre dan key, karena ketika ini dilakukan maka akan kembali ada notifikasi Token Kosong

**Comment by andifahruddinakas** [comment]
https://github.com/OpenSID/OpenSID/issues/5200

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1479
