### ISSUE TITLE
Bug/error: token tidak bisa tersimpan di db

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#5708]
### Jelaskan error yg dialami

token tidak bisa tersimpan di db, padahal alert nya berhasil tersimpan

![image](https://user-images.githubusercontent.com/36557759/192688589-d9efe8c5-bc95-4249-a969-8d096959ea3d.png)

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.09-premium-beta04

**Comment by andifahruddinakas** [comment]
https://github.com/OpenSID/OpenSID/issues/5200

**Comment by vickyrolanda** [comment]
issue ini sama https://github.com/OpenSID/OpenSID/issues/5707

**Comment by FirlianiF** [comment]
note: Token kosong bukan dikarenakan cloudflare

cc: mas @vickyrolanda

**Comment by FirlianiF** [comment]
a:3:{s:4:"time";i:1665557481;s:3:"ttl";i:86400;s:4:"data";O:8:"stdClass":2:{s:6:"header";O:8:"stdClass":37:{s:3:"url";s:54:"https://layanan.opendesa.id/api/v1/pelanggan/pemesanan";s:12:"content_type";s:9:"text/html";s:9:"http_code";i:200;s:11:"header_size";i:291;s:12:"request_size";i:774;s:8:"filetime";i:-1;s:17:"ssl_verify_result";i:0;s:14:"redirect_count";i:0;s:10:"total_time";d:0.067634;s:15:"namelookup_time";d:0.0021;s:12:"connect_time";d:0.010842;s:16:"pretransfer_time";d:0.042788;s:11:"size_upload";d:0;s:13:"size_download";d:1369;s:14:"speed_download";d:20432;s:12:"speed_upload";d:0;s:23:"download_content_length";d:-1;s:21:"upload_content_length";d:-1;s:18:"starttransfer_time";d:0.067579;s:13:"redirect_time";d:0;s:12:"redirect_url";s:0:"";s:10:"primary_ip";s:14:"103.146.203.49";s:8:"certinfo";a:0:{}s:12:"primary_port";i:443;s:8:"local_ip";s:14:"103.251.44.226";s:10:"local_port";i:53476;s:12:"http_version";i:3;s:8:"protocol";i:2;s:16:"ssl_verifyresult";i:0;s:6:"scheme";s:5:"HTTPS";s:18:"appconnect_time_us";i:42504;s:15:"connect_time_us";i:10842;s:18:"namelookup_time_us";i:2100;s:19:"pretransfer_time_us";i:42788;s:16:"redirect_time_us";i:0;s:21:"starttransfer_time_us";i:67579;s:13:"total_time_us";i:67634;}s:4:"body";s:1369:"<!doctype html>
<html>
<head>
<meta charset="utf-8">
<meta name="robots" content="noindex, nofollow">
<title>One moment, please...</title>
<style>
body {
    background: #F6F7F8;
    color: #303131;
    font-family: sans-serif;
    margin-top: 45vh;
    text-align: center;
}
</style>
</head>
<body>
<h1>Please wait while your request is being verified...</h1>
<form id="wsidchk-form" style="display:none;" action="/z0f76a1d14fd21a8fb5fd0d03e0fdc3d3cedae52f" method="get">
<input type="hidden" id="wsidchk" name="wsidchk"/>
</form>
<script>
(function(){
    var west=+((+!+[])+(+!+[]+[])+(+!+[]+!![]+!![]+!![]+!![]+!![]+!![])+(+![]+[])+(+!+[]+!![]+!![]+!![]+!![]+!![]+!![])+(+!+[]+!![]+!![]+!![]+!![]+!![]+!![]+[])+(+!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(+!+[]+!![]+[])),
        east=+((+!+[])+(+!+[]+[])+(+!+[]+!![]+!![]+!![]+!![]+!![])+(+!+[]+!![]+[])+(+!+[])+(+!+[]+!![]+!![]+!![]+!![]+!![]+!![]+[])+(+!+[])+(+!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+[])),
        x=function(){try{return !!window.addEventListener;}catch(e){return !!0;} },
        y=function(y,z){x() ? document.addEventListener("DOMContentLoaded",y,z) : document.attachEvent("onreadystatechange",y);};
    y(function(){
        document.getElementById('wsidchk').value = west + east;
        document.getElementById('wsidchk-form').submit();
    }, false);
})();
</script>
</body>
</html>";}}

**Comment by FirlianiF** [comment]
mas @vickyrolanda @apidong diatas terlampir scrypt yang didapat oleh cache status langganan yang mengakibatkan token kososng.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/OpenSID/issues/5708
