### ISSUE TITLE
Bug/error: khusus notifikasi BETA jangan ditampilkan

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#5709]
### Jelaskan error yg dialami

![image](https://user-images.githubusercontent.com/36557759/192705823-99054949-4b45-4986-9697-c34135a98171.png)

notifikasi BETA baiknya jangan ditampilkan, karena akan membingungkan pengguna

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

22.09-premium-rev03

**Comment by andifahruddinakas** [comment]
Mas @vickyrolanda, untuk rilis beta (public) disimpan di branch terpisah sj.

**Comment by vickyrolanda** [comment]
untuk issue ini sudah ada solusinya untuk kedapan tidak akan ada beta masuk ke notifikasi rilis karena hanya di buat di branch BETA dan akan di sebar melalui link branch beta seperti berikut ini : https://github.com/OpenSID/rilis-premium/tree/beta
