### ISSUE TITLE
Cek fitur Bisa tambah anggota rumah tangga bersumber dari daftar nama di kartu keluarga kepala rumah tangga

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#5715]
PR https://github.com/OpenSID/premium/pull/1354

Maksud dari issue tsb agar lebih memudahkan menambah anggota rumah tangga : 
1. Sediakan tambah anggota rumah tangga yang diambil berdasarkan individu (yang saat ini)
2. Sediakan tambah anggota rumah tangga yang diambil dari kk (pencarian berdasarkan kepala keluarga), setelah dipilih maka anggota keluarga tsb tampil, yang bisa dipilih (ceklis) yang akan dimasukkan ke rumah tanggal.
![keluarga 1](https://user-images.githubusercontent.com/57283157/192850549-e3fdee97-5cc1-4b64-b6c4-67909256d199.png)

Saat ini tidak dapat dipilih : 
![keluarga 2](https://user-images.githubusercontent.com/57283157/192850715-8c946e2a-d9fe-4f87-b143-6ad1fb541ca3.jpg)

**Comment by vickyrolanda** [comment]
mas @devrakapriyo mohon bantuannya untuk testing ini mas

**Comment by yogiperdana** [comment]
> mas @devrakapriyo mohon bantuannya untuk testing ini mas

Ini kelanjutannya gimana mas? Saya lihat komentar Pak Eddie di issue untuk checklist belum bisa dilakukan

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1500
