### ISSUE TITLE
Cek issue teks berjalan anjungan

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#5716]
PR https://github.com/OpenSID/premium/pull/1306

Saat ini ada pengelompokan modul anjungan, apa perlu dipisahkan teksberjalan yg di web dan anjungan/layanan mandiri.

**Comment by yogiperdana** [comment]
Untuk issue ini apakah datanya masuk ke pengaturan atau tetap di tabel sebelumnya mas @vickyrolanda?

**Comment by yogiperdana** [comment]
> Untuk issue ini apakah datanya masuk ke pengaturan atau tetap di tabel sebelumnya mas @vickyrolanda?

Adakah masukan terkait issue ini mas @andifahruddinakas

**Comment by andifahruddinakas** [comment]
> > Untuk issue ini apakah datanya masuk ke pengaturan atau tetap di tabel sebelumnya mas @vickyrolanda?
> 
> Adakah masukan terkait issue ini mas @andifahruddinakas

Pindahkan dan gunakan ORM dan blade pada modul tsb (yg baru). Untuk yang lama kembalikan seperti semula, dgn catatan setiap kali tambah teks berjalan kategorinya selalu web.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1481
