### ISSUE TITLE
Permintaan Fitur Agar Bisa Menampilkan Keterangan Keluar & Tidak Hadir 

### ISSUE THREAD

**Issue by Wiliyantoro** [OpenSID/OpenSID#5717]
### Jelaskan error yg dialami

ketika user / pegawai sudah melakukan presensi keluar, 
pada halaman depan status keharian perangkat masih muncul " Belum Rekam Kehadiran "
seharusnya status tersebut di munculkan apabila user / Pegawai sama sekali belum melakukan presensi masuk

### Cara untuk mereplikasi errornya

halaman depan, cari di bagian kehadiran aparatur desa
![Uploading image.png…]()

### Hasil yg diharapkan

tampilkan status " KELUAR " apabila sudah melakukan presensi keluar

### Tangkapan layar dan log error

1. gambar di bawah sudah melakukan presensi masuk , tampilan sudah benar 
![2022-09-29](https://user-images.githubusercontent.com/44520382/192917543-28b05666-1743-46db-b0df-98f08282e23b.png)

2. ketika melakukan presensi keluar
![2022-09-29 (1)](https://user-images.githubusercontent.com/44520382/192917531-9f59b3fa-aad5-4c66-ae93-2474a7d81295.png)

3. halaman ketika sudah melakukan presensi keluar, namu status kehadiran masih " Belum Rekam Kehadiran "
![2022-09-29 (2)](https://user-images.githubusercontent.com/44520382/192917523-d5fc9d72-c056-4d10-b273-7290c8b799a1.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.09-premium-beta04

### Tema Yang Digunakan

Denatra v.7.0

**Comment by yogiperdana** [comment]
Bug ini ditemukan setelah ada penambahan fitur baru ya pak (pilih alasan keluar) @Wiliyantoro

**Comment by Wiliyantoro** [comment]
sebelum ada fitur baru tersebut pak

**Comment by yogiperdana** [comment]
Berarti bug lama ya pak. Kemungkinan masalah ada di temanya pak nanti saya coba cek lagi

**Comment by Wiliyantoro** [comment]
siap pak,

**Comment by vickyrolanda** [comment]
mas @yogiperdana  Perlu informasi tambahan untuk memeriksa apakah perangkat tertentu sudah hadir atau tidak setelah jam masuk kerja.

**Comment by ariandii** [comment]
Karena di OpenSID belum tersedia fitur mengenai informasi kehadiran, yang ada saat ini hanya 1 kondisi yang tampil di website yakni Hadir Di Kantor Desa. Default jika tidak hadir maka tidak tampilakn keterangan.

Sebagai pemanis, di sisi Tema DeNatra diberi 2 kondisi yang keterangan kosong diganti dengan sebutan Belum Rekam Kehadiran.
Petunjuk nya ada di file readme yang ada di folder denatra (paling bahwah).

dan akan disempurnakan jika sudah tersedia dari sisi OpenSID mengenai berbagai kondisi kehadiran.

<img width="814" alt="screenshot_602" src="https://user-images.githubusercontent.com/46939846/192938027-f78a60e8-dd3e-4d18-af44-41da292f0a38.png">

**Comment by ariandii** [comment]
Pak @Wiliyantoro 
bisa cek penjelasan ada di atas.

dan bisa ubah issues ini menjadi permintaan fitur.

**Comment by Wiliyantoro** [comment]
terimakasih pak @ariandii, sudah dirubah menjadi permintaan fitur

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1456
