### ISSUE TITLE
[TinyMCE] Penambahan fungsi jarak antra baris (tools tinymce linehight)

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#5718]
Belum ada tools lineheight di editor TinyMCE.

Solusi : 
- Update libary TinyMCE ke versi 5 terkahir (versi 6 banyak yang perlu diubah)

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1436
