### ISSUE TITLE
Bug/error: error unduh Buku Inventaris dan Kekayaan Desa

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#5719]
### Jelaskan error yg dialami

error ini terjadi di branch daftar-pamong, bagian Kepala desa dan Seketaris Desa

![image](https://user-images.githubusercontent.com/36557759/192939930-0340a63c-9b60-4c1b-a397-6880aac746f4.png)
![image](https://user-images.githubusercontent.com/36557759/192939990-1b037a68-9131-4128-b0a7-6506fc45e51a.png)

### Cara untuk mereplikasi errornya

1. klik menu Buku Administrasi Desa
2. klik menu Buku Administrasi Umum
3. klik menu Buku Inventaris dan Kekayaan Desa
4. klik Unduh

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

22.09-premium

**Comment by andifahruddinakas** [comment]
https://github.com/OpenSID/premium/pull/1412

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1412

**Comment by devrakapriyo** [comment]
<img width="1440" alt="Screen Shot 2022-10-01 at 12 06 00" src="https://user-images.githubusercontent.com/36557759/193393540-9f5ecb5c-d938-4924-828d-730d08948307.png">

setelah saya cek di berputar.opendesa.id lis kepala desa dan seketaris desa masih error

**Comment by vickyrolanda** [comment]
sy cek normal mas 
<img width="759" alt="image" src="https://user-images.githubusercontent.com/59082428/193410644-bab497f1-196f-4659-a166-d27e904bf59d.png">
