### ISSUE TITLE
Bug: Error Export Data Analisis

### ISSUE THREAD

**Issue by telo99** [OpenSID/OpenSID#572]
![sidexport](https://user-images.githubusercontent.com/30897391/29414689-b82dd1a6-838a-11e7-9dc7-95f2f44c8629.jpg)

Error Export Data Analisis

**Comment by eddieridwan** [comment]
Di export_model.php ada function export_akp() dan di import_model.php ada function import_akp(). Tetapi tabel analisis_keluarga tidak ada. 

Di sid3.10 juga sama.

Perlu dilacak apakah fitur analisis_keluarga dibutuhkan, atau sudah digabung ke modul Analisis.

**Comment by eddieridwan** [comment]
Kalau memang sudah digabung ke menu Analisis, semua script dan tabel yang berkaitan dengan analisis_keluarga perlu dihapus.

**Comment by eddieridwan** [comment]
Dari pembahasan di https://www.facebook.com/groups/OpenSID/, sepertinya APK sekarang dilakukan menggunakan modul Analisis. Dengan demikian, kami akan hapus tabel dan script yang berkaitan dengan apk dan analisis_keluarga. Apabila ternyata nanti dibutuhkan, bisa ambil lagi dari git.

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
