### ISSUE TITLE
Error saat nambahkan Disposisi Surat Masuk

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#5720]
http://opensid.test/surat_masuk/form

<img width="773" alt="image" src="https://user-images.githubusercontent.com/59082428/193117233-4e74ed70-1732-4a36-a4c2-4061cc4db706.png">

Log :
<img width="657" alt="image" src="https://user-images.githubusercontent.com/59082428/193117594-b020446d-6f27-408b-9be5-df2c371e0152.png">

**Comment by apidong** [comment]
Pak, @vickyrolanda butuh database contoh.

**Comment by vickyrolanda** [comment]
> Pak, @vickyrolanda butuh database contoh.

sy kirim ke telegram ya mas

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1418
