### ISSUE TITLE
Permintaan fitur: Sediakan modul "Gawai Layanan" sebagai pengganti fitur anjungan

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#5721]
### Apa kekurangan yg ingin diatasi?

Fitur anjungan berlisensi saat ini menghilangkan fitur sebelumnya yang memungkinkan layanan warga-hadir menggunakan scan RFID dan mengabaikan keharusan unggah dokumen pendukung.

Sedangkan fitur itu dibutuhkan oleh kantor desa/dusun/RT untuk memudahkan pemberian layanan pada warga yg hadir langsung. 

### Jelaskan solusi yg diinginkan

Sediakan pengenalan gawai khusus bagi layanan warga hadir-langsung. Fiturnya sama dengan yang ada pada versi anjungan pada versi sebelum v22.09-premium, yaitu menyediakan:

1. bisa scan RFID eKTP warga
2. pada permohonan surat tersedia pilihan 'bawa secara fisik' untuk dokumen pendukung

Di Admin disediakan fitur untuk mengelola pendaftaran Gawai Layanan, yg diidentifikasi oleh IP Address, Mac Address atau ID Browser.

Fitur ini bagian dari rilis Premium biasa tanpa lisensi tambahan, dan akan masuk ke rilis Umum setelah enam bulan. Fitur ini tidak memerlukan perangkat khusus, misalnya dapat digunakan pada HP di kantor Ketua RT.

Fitur ini berbeda dengan fitur anjungan, yang menyediakan banyak fitur tambahan yg dirancang untuk ditampilkan menggunakan perangkat box anjungan, seperti buku tamu, informasi desa dan fitur2 layanan mandiri lainnya. 

### Apakah ada alternatif lain

Tidak ada

### Untuk versi OpenSID mana

v22.11-premium 

### Informasi tambahan

Jika ternyata ada banyak yg membutuhkan, fitur ini perlu dirilis secepatnya, sebelum rilis tgl 1.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1484
