### ISSUE TITLE
Bug/error: error migrasi dari umum 22.03 ke 22.09-premium-rev03 

### ISSUE THREAD

**Issue by apidong** [OpenSID/OpenSID#5723]
### Jelaskan error yg dialami

Severity: error --> Exception: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'serp5942_desa.kehadiran_jam_kerja' doesn't exist (SQL: select * from kehadiran_jam_kerja) /home/serp5942/public_html/vendor/illuminate/database/Connection.php 712

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

-

### Tema Yang Digunakan

-

### Informasi tambahan

-

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1426
