### ISSUE TITLE
Bug/error: pending upload image tertentu di dengan filemanager

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#5724]
### Jelaskan error yg dialami

hanya gambar tentu yang tidak bisa terupload di filemanager, terlampir gambar yang dapat di upload dan tidak dapat di upload di GDrive OpenDesa

<img width="1042" alt="Screen Shot 2022-09-30 at 17 03 16" src="https://user-images.githubusercontent.com/36557759/193246922-75b59f9e-be96-432d-97dc-525603577122.png">

<img width="1393" alt="Screen Shot 2022-09-30 at 17 03 54" src="https://user-images.githubusercontent.com/36557759/193246973-f56929d5-42d5-4c34-ab5b-622276edcd24.png">

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.09-premium-beta04

**Comment by devrakapriyo** [comment]
gambar ada di link gdrive : https://drive.google.com/drive/folders/1U-7oh6Ko1zN_x7ciX9HLdy0Kk3kT1cVZ?usp=sharing

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1429
