### ISSUE TITLE
Menambah fitur

### ISSUE THREAD

**Issue by andiju1778** [OpenSID/OpenSID#5725]
### Apa kekurangan yg ingin diatasi?

Menambah fitur agar bisa menampilkan siapa warga yg berulang tahun hari ini

### Jelaskan solusi yg diinginkan

Agar bisa Menambah fitur agar bisa menampilkan siapa warga yg berulang tahun hari ini

### Apakah ada alternatif lain

agar masyarakat bisa melihat sendiri siapa yang berulang tahun hari ini

### Untuk versi OpenSID mana

-

### Informasi tambahan

-

**Comment by eddieridwan** [comment]
@andiju1778 fitur seperti ini tidak dapat diterapkan, karena berpotensi mempublikasikan data yang dirahasiakan (ulang tahun seseorang).
