### ISSUE TITLE
Bug/error: pengaturan pengguna tampilkan data tidak sesuai pada datatable

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#5726]
### Jelaskan error yg dialami

![image](https://user-images.githubusercontent.com/36557759/193270584-c10d9579-d2fd-47e3-971d-e83e2ef47beb.png)

pada gambar di atas, tampilkan 20 data sedangkan yang tampil hanya 10 dari 11 data

### Cara untuk mereplikasi errornya

1. klik menu Pengaturan
2. klik menu Pengguna

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.09-premium-beta04

**Comment by scqolbu24** [comment]
Selain di berputar, saya coba di dev.opendesa sama terjadi bug, namun saya coba menggunakan branch rilis-dev dan bug fix dengan terdapat 12 data untuk hasilnya dapat ditampilkan semuanya dalam 1 tabel, tangkapan layar sebagai berikut:
Hasil dari rilis-dev
![test-beta](https://user-images.githubusercontent.com/68048807/193282900-a1ec1364-57ad-4f2a-aa3b-aa07d121dc35.JPG)

Hasil dari bug-fix
![test-rev](https://user-images.githubusercontent.com/68048807/193282983-a7d4dc26-949e-47db-ad20-d40a408008f7.JPG)

**Comment by scqolbu24** [comment]
dengan testing menggunakan rilis-dev dan bug-fix sudah normal, maka issue ini ditutup.
