### ISSUE TITLE
Bug/error: pengaturan pengguna berstatuskan staf sedangkan bukan staf

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#5727]
### Jelaskan error yg dialami

<img width="1175" alt="Screen Shot 2022-09-30 at 19 43 14" src="https://user-images.githubusercontent.com/36557759/193272728-562efee6-dff6-4e90-a90f-fa2430ee15dd.png">

<img width="1133" alt="Screen Shot 2022-09-30 at 19 44 05" src="https://user-images.githubusercontent.com/36557759/193272740-b2fcfd10-7499-4a24-a635-d29d8587e057.png">

pada gambar diatas, seharusnya bukan staf tetapi keterangannya staf

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.09-premium-beta04

**Comment by vickyrolanda** [comment]
issue ini terjadi karena ketika ditambah pengguna status pengguna masih ada di pemerintah desa sehingga statusnya staff
<img width="578" alt="image" src="https://user-images.githubusercontent.com/59082428/193293608-c8af5f1b-3084-4a82-9288-fa7c46b2ae86.png">
lalu ketika staff di keluarkan dan bukan lagi bagian dari pemerintah desa maka status staff pada pengguna tidak berubah.
harusnya ikut berubah menjadi bukan staff

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1425
