### ISSUE TITLE
aparatur desa dihapus maka penandatanganan menjadi hilang

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#5728]
### Jelaskan error yg dialami

![image](https://user-images.githubusercontent.com/36557759/193273378-83b587b7-c872-4f5a-b322-52ad760e5ced.png)

pada gambar diatas surat tersebut di tanda tangani oleh Ahmad Allif Rizki, lalu akun aparatur Ahmad Allif Rizki dihapus maka penanda tanganan menjadi hilang seperti gambar dibawah

![image](https://user-images.githubusercontent.com/36557759/193273556-c4c27b82-76f7-490f-b074-45e18c2ae5cc.png)

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.09-premium-beta04

**Comment by vickyrolanda** [comment]
Kenapa hilang karena saat ini log surat tersimpan ID pamong , jika Pamong di hilangkan maka ID pamong menjadi tidak terbaca ini bisa atasin dengan 2 cara : 

1. Soft delete artinya ID pamong tidak benar - benar di hapus namun berubah status non-aktif sehingga tidak muncul di pemerintah desa
2. Bisa dengan cara simpan nama pamong setiap buat surat. 

ke2 hal diatas akan di diskusikan terlebih dahulu , sehingga issue bukan bug namun bisa penambahan fitur.

**Comment by eddieridwan** [comment]
@vickyrolanda @devrakapriyo , seharusnya perangkat desa yg sudah digunakan untuk menandatangani surat tidak boleh dihapus. Perangkat desa yg sudah keluar atau tidak bertugas lagi seharusnya diganti statusnya menjadi tidak aktif, tidak dihapus. Riwayat perangkat desa perlu terus tersimpan. 

Penghapusan perangkat desa hanya dilakukan jika salah buat. 

Jadi yg perlu diterapkan:

1. Di front-end, tombol hapus untuk perangkat desa yg telah menandatangani surat di-nonaktifkan
2. Validasi di back-end supaya tidak dapat menghapus perangkat desa yg telah menandatangani surat.

**Comment by vickyrolanda** [comment]
> @vickyrolanda @devrakapriyo , seharusnya perangkat desa yg sudah digunakan untuk menandatangani surat tidak boleh dihapus. Perangkat desa yg sudah keluar atau tidak bertugas lagi seharusnya diganti statusnya menjadi tidak aktif, tidak dihapus. Riwayat perangkat desa perlu terus tersimpan.
> 
> Penghapusan perangkat desa hanya dilakukan jika salah buat.
> 
> Jadi yg perlu diterapkan:
> 
> 1. Di front-end, tombol hapus untuk perangkat desa yg telah menandatangani surat di-nonaktifkan
> 2. Validasi di back-end supaya tidak dapat menghapus perangkat desa yg telah menandatangani surat.

mas @andifahruddinakas berarti yang perlu diterapkan seperti diskusi kita kemarin harus ada soft delete (artinya menon-aktifkan perangkat desa) 

tapi lebih jelas bisa dilihat kommentar pak eddie di atas.

**Comment by eddieridwan** [comment]
@vickyrolanda @andifahruddinakas **TIDAK** perlu ada soft-delete. Fitur aktif/nonaktifkan perangkat sudah lama ada.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1475
