### ISSUE TITLE
Permintaan fitur: 

### ISSUE THREAD

**Issue by andiju1778** [OpenSID/OpenSID#5729]
### Apa kekurangan yg ingin diatasi?

-

### Jelaskan solusi yg diinginkan

Penambahan format surat keterangan telah menikah

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

-

**Comment by eddieridwan** [comment]
@vickyrolanda , harap permintaan yg tidak lengkap seperti ini segera ditindaklanjuti.
