### ISSUE TITLE
Bug/error: id paramater permalink artikel dapat diubah dan tidak menyebabkan 404

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#5730]
### Jelaskan error yg dialami

dari link artikel ini https://berputar.opendesa.id/artikel/2016/8/24/data-desa diubah menjadi https://berputar.opendesa.id/artikel/2016/8765/20499999999999999999999999/data-desa seharunya link tersebut 404 tetapi ini masih bisa diakses

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.09-premium-beta04

**Comment by devrakapriyo** [comment]
jika dibiarkan akan menyebabkan duplicate content oleh crawler google

**Comment by ariandii** [comment]
link mana yang seharusnya 404?
link awal atau kedua?

menurut saya tidak bisa ubah permalink, karena berkaitan dengan slug siapa tau sudah terindex google. sehingga jika misal artikel tahun lalu diedit permalink. maka kasian pengunjung lama menjadi 404.

**Comment by devrakapriyo** [comment]
Link ke 2 pak @ariandii, seharusnya 404

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1427
