### ISSUE TITLE
Permintaan fitur: Tampilkan warga Desa yg berualng tahun hari ini

### ISSUE THREAD

**Issue by andiju1778** [OpenSID/OpenSID#5731]
### Apa kekurangan yg ingin diatasi?

-

### Jelaskan solusi yg diinginkan

-

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

-

### Informasi tambahan

-

**Comment by muhtar-coder** [comment]
Keren juga ini...bisa kirim kartu ucapan selamat via telegram/wa atau bisa post di fb

**Comment by eddieridwan** [comment]
@muhtar-coder @andiju1778 fitur ini sudah diminta sebelumnya, dan ditolak. Karena akan merupakan celah privasi data. Tanggal lahir penduduk merupakan data pribadi yg dijaga privasinya (data lain yg dijaga privasinya termasuk NIK, No KK). Jadi issue ini akan ditutup, karena tidak bisa diterapkan di OpenSID.
