### ISSUE TITLE
Bug/error: error struktur tabel informasi publik

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#5734]
### Jelaskan error yg dialami

![image](https://user-images.githubusercontent.com/36557759/193401285-62ae83d2-05b8-4bd1-a0f4-0649b88dbf5d.png)

pada gambar diatas isi table tidak sesuai dengan judul table, dan ubah struktur table informasi menjadi
<table>
<tr>
<th>No</th>
<th>Judul Informasi</th>
<th>URL</th>
<th>Tahun</th>
<th>Kategori</th>
<th>Tanggal Upload</th>
</tr>
</table>

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

22.10-premium

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1432
