### ISSUE TITLE
Bug/error: gagal migrasi v22.10-premium khusus desa sempano.desa.id

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#5735]
### Jelaskan error yg dialami

saat migrasi ke versi 22.10-premium terjadi error, tetapi di versi 22.09-premium-rev03 berjalan normal

database dan log error ada di GDrive OpenDesa : https://drive.google.com/drive/folders/1DplziI7jjbVWWLkp3ivxr9SYpsxewJ53?usp=sharing

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

22.10-premium

**Comment by devrakapriyo** [comment]
info tambahan : 

![image](https://user-images.githubusercontent.com/36557759/193495508-33950f04-4356-4a48-b316-30beb78ba213.png)

di table tidak ada yang duplicate

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1440
