### ISSUE TITLE
Bug/error: [PREMIUM] Desimal dua digit tidak dapat ditampilkan pada Transparansi APBDesa

### ISSUE THREAD

**Issue by mah-mudi** [OpenSID/OpenSID#5738]
### Jelaskan error yg dialami

Sesuai Lampiran Perdes APBDesa bahwa Pendapatan, Belanja dan Pembiayaan di APBDesa biasanya ada desimal dua digit, dan itu tidak bisa dinput pakai desimal di Modul **Keuangan->Input Data**  . Ketika input pakai desimal, ada keterangan **_hanya boleh isi karektek numerik_**.

### Cara untuk mereplikasi errornya

1. Pergi ke Modul Keuangan
2. Input Data
3. Masukkan nilai anggaran sesuai lampiran perdes APBDesa (yang ada desimal dua digit nya, misal anggaran pendapatan PAD  617.666.666,66
4. Akan keluar tulisan berwarna merah  "hanya boleh isi karektek numerik"

### Hasil yg diharapkan

Dapat input anggaran sampai bisa desimal dua, sehingga info yang ditampilkan sudah benar

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/57661283/193436025-0debd00c-2aae-4cb4-a1e6-ecdb1942fe8d.png)

Karena input data belum support desimal dua digit, mengakibatkan tampilan transparansi anggaran juga tidak ada desimalnya.
![image](https://user-images.githubusercontent.com/57661283/193436034-18c04892-372d-43cd-bd37-4511110cad92.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

OpenSID 22.10 Premium

### Tema Yang Digunakan

Denava 2.0

**Comment by andifahruddinakas** [comment]
Mas @vickyrolanda, di cek ketentuan ini https://github.com/OpenSID/OpenSID/issues/4027

https://drive.google.com/file/d/1blm5w1IKsZXkb01-yMJw0TUG_KJTjxnT/view

**Comment by mah-mudi** [comment]
Sip, karena ada bunga bank, atau pendapatan lain yg mengakibatkan desimal dua digit diperlukan.

**Comment by vickyrolanda** [comment]
> Mas @vickyrolanda, di cek ketentuan ini #4027
> 
> https://drive.google.com/file/d/1blm5w1IKsZXkb01-yMJw0TUG_KJTjxnT/view

ia dari aturan memang  mencantumkan angka sampai dengan satuan rupiah, tidak sampai dengan sen.
https://jdih.kemenkeu.go.id/fulltext/2010/250~PMK.05~2010Per.htm
<img width="780" alt="image" src="https://user-images.githubusercontent.com/59082428/194161998-3afdc750-b3cd-4e57-b066-e5143d388043.png">

**Comment by mah-mudi** [comment]
Pak @vickyrolanda , memang dalam pembayaran pengeluaran negara satuan rupiah tanpa sen. 

Karena yg dimaksud di issues ini adalah penyesuaian desimal dua digit dalam input nominal Anggaran Pendapatan dan Belanja Desa. 

APBN pun juga memakai desimal dua digit. 
![Screenshot_2022-10-06-05-14-27-658_com.google.android.apps.docs.jpg](https://user-images.githubusercontent.com/57661283/194173999-e8e5b49b-bc19-47a1-a2b2-b81b008fd04a.jpg)

**Comment by andifahruddinakas** [comment]
Mas @vickyrolanda, apa ini ditutup atau tetap dikerjakan, agar bisa masuk rev01?

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1452
