### ISSUE TITLE
Bug/error: Daftar penerima bantuan tetap muncul walaupun diseting Tidak pada pengaturan halaman web

### ISSUE THREAD

**Issue by hasap86** [OpenSID/OpenSID#5739]
### Jelaskan error yg dialami

Daftar penerima bantuan tetap muncul walaupun diseting Tidak pada pengaturan halaman web

### Cara untuk mereplikasi errornya

Seting di Pengaturan Halaman Web pada daftar penerima bantuan "Tidak"
cek di halaman web penerima bantuan
data penerima bantuan tetap muncul, seharusnya tidak muncul

### Hasil yg diharapkan

sesuai setingan jika Ya = Muncul, Jika Tidak = Tidak muncul

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Umum

### Versi OpenSID

v22.10

### Tema Yang Digunakan

Esensi

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1438
