### ISSUE TITLE
Bug/error: Beberapa Menu tidak terbuka pada versi 22.10 tema Esensi

### ISSUE THREAD

**Issue by hasap86** [OpenSID/OpenSID#5740]
### Jelaskan error yg dialami

tidak bisa membuka menu Lapak

### Cara untuk mereplikasi errornya

buka menu lapak

- [ ] https://demosid.opendesa.id/lapak
- [ ] https://demosid.opendesa.id/pembangunan
- [ ] https://demosid.opendesa.id/data-wilayah
- [ ] https://demosid.opendesa.id/pengaduan

### Hasil yg diharapkan

bisa terbuka pada versi 22.10 menu Esensi

### Tangkapan layar dan log error

https://demosid.opendesa.id/lapak

### Rilis Versi OpenSID

Rilis Umum

### Versi OpenSID

v22.10

### Tema Yang Digunakan

Esensi

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/OpenSID/pull/5805
