### ISSUE TITLE
Bug/error: Menu pengaduan pada v22.10 tema Esensi tidak bisa terbuka

### ISSUE THREAD

**Issue by hasap86** [OpenSID/OpenSID#5741]
### Jelaskan error yg dialami

tidak bisa membuka menu Pengaduan

### Cara untuk mereplikasi errornya

buka menu Pengaduan 

https://demosid.opendesa.id/pengaduan

### Hasil yg diharapkan

bisa membuka menu pengaduan pada v22.10 tema Esensi

### Tangkapan layar dan log error

https://demosid.opendesa.id/pengaduan

### Rilis Versi OpenSID

Rilis Umum

### Versi OpenSID

v22.10

### Tema Yang Digunakan

Esensi

**Comment by vickyrolanda** [comment]
issue di gabung ke https://github.com/OpenSID/OpenSID/issues/5740
