### ISSUE TITLE
Bug/error: Menu Pembangunan pada v22.10 tema Esensi tidak bisa terbuka

### ISSUE THREAD

**Issue by hasap86** [OpenSID/OpenSID#5742]
### Jelaskan error yg dialami

tidak bisa membuka menu Pembangunan pada v22.10  tema esensi

### Cara untuk mereplikasi errornya

buka halaman pembangunan

https://demosid.opendesa.id/pembangunan

### Hasil yg diharapkan

bisa membuka halaman pembangunan pada v22.10 tema Esensi

### Tangkapan layar dan log error

https://demosid.opendesa.id/pembangunan

### Rilis Versi OpenSID

Rilis Umum

### Versi OpenSID

v22.10

### Tema Yang Digunakan

Esensi

**Comment by vickyrolanda** [comment]
issue di gabung ke https://github.com/OpenSID/OpenSID/issues/5740
