### ISSUE TITLE
Bug/error: Menu Statistik Populasi WIlayah pada v22.10 tema Esensi tidak bisa dibuka

### ISSUE THREAD

**Issue by hasap86** [OpenSID/OpenSID#5743]
### Jelaskan error yg dialami

tidak bisa membuka Menu Statistik Populasi Wilayah pada v22.10 tema Esensi

### Cara untuk mereplikasi errornya

buka halaman Statistik Populasi Wilayah

https://demosid.opendesa.id/data-wilayah

### Hasil yg diharapkan

bisa membuka statistik populasi wilayah pada v22.10 tema Esensi

### Tangkapan layar dan log error

https://demosid.opendesa.id/data-wilayah

### Rilis Versi OpenSID

Rilis Umum

### Versi OpenSID

v22.10

### Tema Yang Digunakan

Esensi

**Comment by vickyrolanda** [comment]
issue di gabung ke https://github.com/OpenSID/OpenSID/issues/5740
