### ISSUE TITLE
Bug/error: Update tersedia terus walaupun sudah di update terbaru

### ISSUE THREAD

**Issue by hasap86** [OpenSID/OpenSID#5744]
### Jelaskan error yg dialami

status update selalu tersedia walaupun sudah terupdate versi terbaru

### Cara untuk mereplikasi errornya

buka halaman admin terbaru setelah update muncul notifikasi updater tesedia

### Hasil yg diharapkan

tidak ada notif setelah di update terbaru

### Tangkapan layar dan log error

![update-tersedia-terus](https://user-images.githubusercontent.com/45263721/193454763-856eeb94-1744-4851-85d1-73a71e92dfe0.jpg)

### Rilis Versi OpenSID

Rilis Umum

### Versi OpenSID

v22.10

### Tema Yang Digunakan

Esensi

**Comment by haerulmutaaly** [comment]
Sama Gan adakah solusi fitur migrasi juga tidak berfungsi

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/OpenSID/pull/5780
