### ISSUE TITLE
Permintaan fitur: Daftar Data Suplemen tambahkan Umur, hapus Tempat Lahir

### ISSUE THREAD

**Issue by hasap86** [OpenSID/OpenSID#5745]
### Apa kekurangan yg ingin diatasi?

saat ini daftar data suplemen menampilkan Tempat Lahir yang mungkin datanya tidak terlalu penting untuk ditampilkan. lebih baik diganti dengan Umur

### Jelaskan solusi yg diinginkan

ganti Tempat Lahir pada data daftar suplemen menjadi Umur

### Apakah ada alternatif lain

baris Jenis Kelamin di geser setelah Nama, kemudian Umur baru Alamat

No. | Nama | Jenis Kelamin | Umur | Alamat

### Untuk versi OpenSID mana

v22.10

### Informasi tambahan

Tema Esensi

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/OpenSID/pull/7455
