### ISSUE TITLE
Bug/error: gagal migrasi v22.10-premium khusus desa cigelam.desa.id

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#5747]
### Jelaskan error yg dialami

update dari versi 22.09-premium-rev03 ke 22.10-premium gagal migrasi

dilihat dari error lognya Incorect datetime value 
![image](https://user-images.githubusercontent.com/36557759/193496108-628af6ba-4bc4-4edb-8b97-bb66300520eb.png)

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

22.10-premium

**Comment by andifahruddinakas** [comment]
SOLUSI : 
1. tambahkan pengecekan tgl tidak valid di periksa/database

**Comment by haerulmutaaly** [comment]
Sama gan'

**Comment by apidong** [comment]
> SOLUSI :
> 
> 1. tambahkan pengecekan tgl tidak valid di periksa/database

baik mas

**Comment by apidong** [comment]
@devrakapriyo sepertinya butuh databasenya untuk diperiksa

**Comment by devrakapriyo** [comment]
baik mas, kemarin saya minta kan belum ada respon mas
coba hari ini saya followup lagi

**Comment by devrakapriyo** [comment]
mas @apidong setelah saya konfirmasi ke pengguna issue ini sudah solved

saya close issue ini

**Comment by apidong** [comment]
Baik mas
