### ISSUE TITLE
Bug/error: Tidak bisa update via Terminal sudah melakukan update manual sama aja malah tetap ada notif

### ISSUE THREAD

**Issue by haerulmutaaly** [OpenSID/OpenSID#5751]
### Jelaskan error yg dialami

![Capture](https://user-images.githubusercontent.com/13283785/193545174-549cf8db-cad2-485e-ad94-5b51bfee9366.PNG)

### Cara untuk mereplikasi errornya

4

### Hasil yg diharapkan

Ada nya auto update atau update onclik

### Tangkapan layar dan log error

HEAD is now at 3d764c817 sesuaikan nama database

### Rilis Versi OpenSID

Rilis Umum

### Versi OpenSID

v22.10

### Tema Yang Digunakan

v22.10

### Informasi tambahan

Sudah melakukan update manual tetap tidak bisa

**Comment by ariandii** [comment]
cermati kembali cara update nya. jika benar pasti sukses.
