### ISSUE TITLE
[TinyMCE] Konversi surat RTF - Pernyataan Penguasaan Fisik Bidang Tanah (SPORADIK)

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#5753]
<img width="743" alt="image" src="https://user-images.githubusercontent.com/59082428/193652192-0f6d8cad-818e-4ee2-8f68-3b2e79f7b075.png">
[surat_sporadik_1357901357901357_2022-10-04_.pdf](https://github.com/OpenSID/OpenSID/files/9700077/surat_sporadik_1357901357901357_2022-10-04_.pdf)

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2556
