### ISSUE TITLE
[TinyMCE] Konversi surat RTF - Keterangan Pindah Penduduk

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#5756]
<img width="782" alt="image" src="https://user-images.githubusercontent.com/59082428/193654990-7185283f-197c-4bd6-a4b8-bebea69ef8b7.png">

Lampiran : 
F-1.03, F-1.08, F-1.25, F-1.27

[surat_ket_pindah_penduduk_5201145003976995_2022-10-04_2.zip](https://github.com/OpenSID/OpenSID/files/9700143/surat_ket_pindah_penduduk_5201145003976995_2022-10-04_2.zip)

**Comment by yogiperdana** [comment]
Apakah di surat tinymce saat ini terdapat pengaturan untuk menampikan view ini pada saat cetak surat mas @andifahruddinakas @vickyrolanda 
![image](https://github.com/OpenSID/OpenSID/assets/14155050/77e6f0d5-cc10-4704-9368-c466f31e0e2a)

**Comment by vickyrolanda** [comment]
Ada mas coba cek PR mas @pandigresik

**Comment by yogiperdana** [comment]
> Ada mas coba cek PR mas @pandigresik

Surat apa mas @vickyrolanda?

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/2623
