### ISSUE TITLE
[TinyMCE] Konversi surat RTF - Keterangan Kelahiran

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#5767]
<img width="779" alt="image" src="https://user-images.githubusercontent.com/59082428/193660787-7f015bb0-6c97-4dc4-80b5-e29edf86f50c.png">
[surat_ket_kelahiran_5201144301171725_2022-10-04_4.zip](https://github.com/OpenSID/OpenSID/files/9700295/surat_ket_kelahiran_5201144301171725_2022-10-04_4.zip)

**Comment by FirlianiF** [comment]
issue ini tdk bisa dikerjakan kalau belum selesai issue
https://github.com/OpenSID/OpenSID/issues/6092

**Comment by vickyrolanda** [comment]
Berkaitan dengan issue : 

- [ ] https://github.com/OpenSID/OpenSID/issues/6902
- [ ] https://github.com/OpenSID/OpenSID/issues/6867

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/2638
