### ISSUE TITLE
[Login] Tambah filter ip untuk mengakses laman admin

### ISSUE THREAD

**Issue by simasta** [OpenSID/OpenSID#577]
Sepertinya ini perlu diberikan sebagai opsi keamanan data penduduk, sebagai contoh laman admin hanya dpat di akses dari ip jaringan lokal 192.168.x.x

**Comment by mikhakhaldea** [comment]
Mungkin untuk sementara bisa di blokir dr .htaccess

**Comment by hadyanwijaya** [comment]
ini bahaya kalau sudah online jika adminnya punya ip public dynamic...
bisa juga dengan usulan mas mikhakhaldea atau dari firewall server

**Comment by afa28** [comment]
Untuk saat ini sdah diterapkan pd anjungan layanan mandiri. Sedangkan u/ admin blum diterapkan, mungkin alasannya agar bisa di buka dimana sja.

**Comment by andifahruddinakas** [comment]
Sudah diterapkan diversi terbaru v2305.0.0
