### ISSUE TITLE
[TinyMCE] Konversi surat RTF - Keterangan Lahir Mati

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#5772]
<img width="780" alt="image" src="https://user-images.githubusercontent.com/59082428/193663301-2d256013-b8a0-4dd4-9736-53c162970bae.png">

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2445
