### ISSUE TITLE
TTE - Sesuaikan ukurang font di bagian footer tte 

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#5775]
<img width="779" alt="image" src="https://user-images.githubusercontent.com/59082428/193666488-b6d086cf-3269-49ca-94bb-7d3f822af665.png">

Referensi bisa ikutin ukuran di bawah ini : 
<img width="591" alt="image" src="https://user-images.githubusercontent.com/59082428/193667130-16bd72ae-6d45-409f-975c-cfe073584250.png">

**Comment by apidong** [comment]
mas @vickyrolanda ada contoh file pdfnya? biar bisa di bandingkan.

**Comment by vickyrolanda** [comment]
> mas @vickyrolanda ada contoh file pdfnya? biar bisa di bandingkan.

ada di google drive mas lengkap. 
[Contoh 1_Invisible_BPRD DKI Jakarta.pdf](https://github.com/OpenSID/OpenSID/files/9702555/Contoh.1_Invisible_BPRD.DKI.Jakarta.pdf)

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1444
