### ISSUE TITLE
TTE - Menambahkan Visual Tanda tangan 

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#5776]
saat ini tanda tangan tidak memiliki visual untuk TTE harus memiliki visual tertanda tangan seperti dibawah ini : 
<img width="594" alt="image" src="https://user-images.githubusercontent.com/59082428/193667861-7068b291-633b-4b77-9d09-3bd8f78aa040.png">

Visual TTD akan muncul berbarengan dengan TTE berhasil di tandatanganin.

saat ini yang kita pakai adalah TTD dengan barcode dimana yang posisinya berdasarkan kordinat dengan label [qr_bsre] saat ini di footer nah ini akan tampil jika telah di TTE . 

Sebaiknya kita buat 2 fungsi sesuai pengaturan , 
1. TTE dengan Visual TTD yaitu IMAGES dimana pada saat dipengaturan TTE harus di Upload visual TTD berbetuk images 
    (untuk menggunakan ini tampilnya dimana kita bisa menggunakan label # / [ttd_bsre]  di bagian tanda tangan surat TinyMCE menggunakan kordinat sama dengan yang sekarang yang sudah diterapkan. Maka kalo ini di terapkan barcode yang ada di footer tidak perlu dipakai lagi.

2. Jika TTE dengan visual images di matikan maka secara bawaan sistem TTD menggunakan TTE barcode seperti saat ini , hanya saja perlu kita tambahkan template TTD berbetuk HTML dimana pengguna bisa menambahkan semacam [ttd_bsre] juga di bagian tanda tangan surat TinyMCE namun kekurangannya adalah visual ini kan akan muncul jika surat didownload sebelum di TTD berhasil di lakukan kepala desa nah dibagaian fungsi review / download surat sebelum TTD di lakukan kepala desa maka visual TTD yang berbentuk HTML tidak ditampilkan namun ketika di TTD akan dilakukan oleh kepala desa maka template PDF yang sudah ada visual TTDnya yang akan di generate atau yang ter TTE oleh kepala desa maka hasil dari TTE akan ada visual TTD yang berbentuk HTML tadi.
Untuk Visual no 2 ini bisa contoh seperti ini saja : 
<img width="594" alt="image" src="https://user-images.githubusercontent.com/59082428/193667861-7068b291-633b-4b77-9d09-3bd8f78aa040.png">

**Comment by apidong** [comment]
@vickyrolanda bisa dijelaskan alurnya seperti apa? ttd tersebut apakah di tambahkan di server ttenya atau di OpenSID

**Comment by vickyrolanda** [comment]
> @vickyrolanda bisa dijelaskan alurnya seperti apa? ttd tersebut apakah di tambahkan di server ttenya atau di OpenSID

ok mas akan sy detailskan mas

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1505
