### ISSUE TITLE
Bug/error: perbaiki cara menampilkan artikel sesuai tanggal

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#5777]
### Jelaskan error yg dialami

saat ini artikel yang baru dibuat tidak muncul, setelah berdiskusi dengan mas @andifahruddinakas ada 1 line code yang perlu di comment

<img width="1440" alt="Screen Shot 2022-10-04 at 09 38 22 1" src="https://user-images.githubusercontent.com/36557759/193722751-50401d7f-480f-4a3e-8639-1e3b020e4693.png">

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.10-premium

**Comment by andifahruddinakas** [comment]
Mas @devrakapriyo, di cek ulang di server desa tsb pengaturan time_zone nya.

**Comment by vickyrolanda** [comment]
mas @devrakapriyo mohon bantunya untuk contact ke pelapor untuk di check ke pengaturan time zonenya.

**Comment by devrakapriyo** [comment]
<img width="1440" alt="Screen Shot 2022-10-07 at 10 38 11" src="https://user-images.githubusercontent.com/36557759/194462942-33d462de-656d-4853-ad67-5855f3b077c1.png">

setelah di cek, web tersebut masih menggunkan timezone Asia/Jakarta belum menggunakan waktu Asia/Makassar

dengan informasi ini bukan bug, melainkan salah di timezone nya, issue ini saya close

**Comment by eddieridwan** [comment]
@devrakapriyo , tambahkan entri di forum.opendesa.id terkait ini dan cara mengatasinya.

Untuk setiap kasus laporan bug yg ternyata bukan bug, berarti ada kekeliruan pengertian. Untuk itu perlu ada petunjuk di forum.opendesa.id bagi pengguna lainnya yg juga mungkin keliru.
