### ISSUE TITLE
Bug/error: tambah buku pengaturan desa, jika tidak mengunggah dokumen menjadi data gagal tersimpan

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#5778]
### Jelaskan error yg dialami

<img width="1440" alt="Screen Shot 2022-10-04 at 14 58 04" src="https://user-images.githubusercontent.com/36557759/193767820-134ca663-f3ce-4b16-a513-75c79bedeb32.png">

pada gambar di atas jika tidak mengunggah dokumen saat di klik tombol Simpan, maka muncul pesan Data gagal disimpan seperti gambar di bawah ini, sedangkan input unggah dokumen bukan required

<img width="1134" alt="Screen Shot 2022-10-04 at 15 09 42" src="https://user-images.githubusercontent.com/36557759/193768229-7f68da15-b3c0-4280-9713-348853ff5124.png">

### Cara untuk mereplikasi errornya

1. klik menu Buku Administrasi Desa
2. klik menu Administrasi Umum
3. klik menu Buku Peraturan Desa
4. klik Tambah Perdes Baru

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

22.10-premium

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1439
