### ISSUE TITLE
Bug/error: tambah buku keputusan, jika tidak mengunggah dokumen menjadi data gagal tersimpan

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#5779]
### Jelaskan error yg dialami

<img width="1440" alt="Screen Shot 2022-10-04 at 15 16 57" src="https://user-images.githubusercontent.com/36557759/193769964-d781e74f-0555-4692-90cc-793c0c5e4e3f.png">

pada gambar di atas jika tidak mengunggah dokumen saat di klik tombol Simpan, maka muncul pesan Data gagal disimpan seperti gambar di bawah ini, sedangkan input unggah dokumen bukan required

<img width="1141" alt="Screen Shot 2022-10-04 at 15 17 22" src="https://user-images.githubusercontent.com/36557759/193770192-2478d746-96e6-4eff-af23-16cd90571594.png">

### Cara untuk mereplikasi errornya

1. klik menu Buku Administrasi Desa
2. klik menu Administrasi Umum
3. klik menu Buku Peraturan Desa
4. klik Tambah Perdes Baru

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.10-premium

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1439
