### ISSUE TITLE
Pada informasi public ubah unduh menjadi preview popup terkait anjungan

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#5782]
<img width="545" alt="image" src="https://user-images.githubusercontent.com/59082428/194074930-684522dd-83c6-4424-9a09-abc0a2339005.png">

- [x] tambah kolom dokument
- [x] tambah tulisan lihat dokument untuk bisa di klik dan popup

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1454

**Comment by hasap86** [comment]
Error jika tidak login sebagai user...
