### ISSUE TITLE
Bug/error: Tombol Edit Peserta form di Program bantuan & Tombol Profil Administrator

### ISSUE THREAD

**Issue by syahransaputra** [OpenSID/OpenSID#5787]
### Jelaskan error yg dialami

Saat masuk ke Dashboard menu Bantuan dan masuk kesalahsatu detail bantuan misal ke Program PKH, setelah itu klik tombol edit maka akan tampil popup Ubah Data Peserta, jika ditutup lalu klik profile administrator maka akan tampil popup Ubah Data Peserta yg sebelumnya. begitupun sebaliknya jika saat di detail bantuan sebelum klik tombol edit langsung klik profile administrator dan ditutup setelah itu klik edit peserta bantuan maka yg tampil popup edit profile administrator

### Cara untuk mereplikasi errornya

1. Pergi ke Dashboard halaman [Bantuan](https://berputar.opendesa.id/program_bantuan)
2. Klik salah satu detail Program Bantuan / Nama Program contoh [PKH](https://berputar.opendesa.id/program_bantuan/detail/3)
3. Setelah dihalaman Program Bantuan PKH lakukan poin ke-4 lalu poin ke-5 atau sebaliknya
4. klik tombol profil Administrator di pojok kanan atas setelah itu klik tombol tutup dan klik tombol Edit Peserta Bantuan
5. Klik tombol edit Peserta Bantuan setelah itu klik tombol tutup dan klik tombol Profil Administrator dipojok kanan Atas.
6. Setelah poin ke-4 atau poin ke-5 dilakukan diatas maka akan tampil form Popup yg sama.

### Hasil yg diharapkan

Pada halaman Detail Program Bantuan tidak membingungkan ketika klik tombol edit peserta bantuan maka form peserta bantuan yg tampil bukan form detail profil pengguna administrator/staff begitupun sebaliknya

### Tangkapan layar dan log error

![chrome-capture-2022-9-6 (1)](https://user-images.githubusercontent.com/26229332/194127479-f667fe5b-2fad-4d45-833f-f5e6f1a10644.gif)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.10-premium

### Tema Yang Digunakan

-

**Comment by syahransaputra** [comment]
Ternyata bukan di halaman Bantuan saja namun dihalaman yang sifatnya menampilkan popup akan kejadian hal yg sama contoh di menu [Keluarga](https://berputar.opendesa.id/keluarga) saat edit pun juga akan menampilkan popup detail profil pengguna/administrator ketika mereplikasi contoh bug diatas

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1449
