### ISSUE TITLE
Pemisahan pengaturan warna area dan garis area pada peta

### ISSUE THREAD

**Issue by makhbub** [OpenSID/OpenSID#5789]
### Apa kekurangan yg ingin diatasi?

Dalam membuat warna area / wilayah pada peta hanya ada satu pengaturan warna. Saat kita ingin membuat  area berwarna transparan, maka otomatis garis tepi berwarna putih. 
Akibatnya garis tepi sulit terlihat pada jenis peta Mapbox streets dan open streetmap

### Jelaskan solusi yg diinginkan

Pengaturan warna area peta (cont : wil kadus/RT) dibuat terpisah dengan pengaturan warna garis area

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

22.11-premium

### Informasi tambahan

![16650434722055492771109189602283](https://user-images.githubusercontent.com/38773660/194255741-03815431-402e-4aac-9852-20240d1a949c.jpg)

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/OpenSID/pull/7407
