### ISSUE TITLE
Link-an Peta Wilayah di Menu "Identitas Desa" ke Widget Peta Desa

### ISSUE THREAD

**Issue by sukrimalendra** [OpenSID/OpenSID#579]
Peta Desa yang ada pada Widget Website desa.
![peta1](https://user-images.githubusercontent.com/30992964/29492999-b44ea46a-85b6-11e7-9c88-8f2d0996c5b6.PNG)
![peta2](https://user-images.githubusercontent.com/30992964/29493000-b451325c-85b6-11e7-8aa0-f9f9f13e938c.PNG)

**Comment by eddieridwan** [comment]
Sudah diterapkan.
