### ISSUE TITLE
Permintaan fitur: warga bisa mengupdate data Kk sendiri di layanan mandiri

### ISSUE THREAD

**Issue by K4nzzz** [OpenSID/OpenSID#5790]
### Apa kekurangan yg ingin diatasi?

Untuk mempermudahkan dalam proses update data pada data base.

### Jelaskan solusi yg diinginkan

Menambahkan menu edit anggota keluarga

### Apakah ada alternatif lain

Ok

### Untuk versi OpenSID mana

V22.10

**Comment by andifahruddinakas** [comment]
Duplicate of https://github.com/OpenSID/OpenSID/issues/5945
