### ISSUE TITLE
Bug/error: ada desa yang menggunakan tanda petik

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#5792]
### Jelaskan error yg dialami

saat ini pada form identitas desa pembatasan karakater nama desa hanya boleh alfanumerik, sepasi dan strip. sedangkan ada desa yang menggunakan ' (tanda petik)

![image](https://user-images.githubusercontent.com/36557759/194485842-d9ffce1f-ec5c-4914-be5b-8dc8677f1b31.png)

![image](https://user-images.githubusercontent.com/36557759/194485940-4380d225-247f-44b9-823e-f3d6d1cb52c2.png)

tolong sesuaikan

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

22.10-premium

**Comment by vickyrolanda** [comment]
Perlu juga di sesuaikan di TrackSID,  karena tidak bisa dicari menggunakan kotak cari.

![image](https://user-images.githubusercontent.com/59082428/194487825-690a0de1-c612-49fa-975b-d9bfca5e0992.png)

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1450
