### ISSUE TITLE
di menu anjungan tambahkan pemberitahuan jika tidak berlangganan anjungan 

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#5795]
Saat ini user tetap bisa nambah anjungan walau tidak beli lisensi anjungan
<img width="341" alt="image" src="https://user-images.githubusercontent.com/59082428/194497905-4803e15e-b20d-41f8-9a2d-ada9b584679e.png">

**Comment by yogiperdana** [comment]
Jadi jika tidak berlangganan di anjungan apa yang ditampilkan mas @vickyrolanda?
1. Apakah hanya list anjungan dan semua tombol aksi disembunyikan atau memang tidak ada yang ditampilkan selain keterangan belum berlangganan seperti ketika token belum kosong/tidak valid di opensid premium
2. Apakah hanya berlaku untuk submodul daftar anjungan atau semua modul anjungan

**Comment by ai-skematik** [comment]
https://github.com/OpenSID/premium/issues/1501

**Comment by ai-skematik** [comment]
Bung @yogiperdana  ketika tidak berlangganan anjungan tidak ada yang ditampilkan selain keterangan belum berlangganan seperti ketika token kosong/tidak valid di opensid premium

**Comment by yogiperdana** [comment]
Baik pak

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1504
