### ISSUE TITLE
Perlu dilakukan pemeriksaan apakah entri data dengan nik yang sama tetap bisa masuk ke program bantuan

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#5798]
<img width="383" alt="image" src="https://user-images.githubusercontent.com/59082428/194502926-30eb49ac-0cd7-47f5-a2cc-e13dff36ca71.png">

<img width="386" alt="image" src="https://user-images.githubusercontent.com/59082428/194503424-04312b2d-7ac1-4180-b3a0-c4c391089653.png">

saat ini ada laporan bahwa ada nik yang sama bisa masuk ke program bantuan , maka perlu di lakukan testing masuknya data dengan nik sama jika ia maka perlu di perbaikin jika tidak maka bisa close issue ini.

**Comment by andifahruddinakas** [comment]
Sy coba tidak bisa melakukan input NIK yang sama, karena data yang ditampilkan selain yang sudah ada. 

<img width="498" alt="image" src="https://user-images.githubusercontent.com/57283157/236754289-48ed746b-0927-4646-8b2f-7b5037f2863b.png">

Untuk sementara issue diclose, jika terdapat laporan yang sama silahkan dibuka kembali issue ini.
