### ISSUE TITLE
Perlu ditesting dan di cari tau terkait update ver22.10-premium

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#5799]
laporan dari pak ariandi perlu database mungkin bisa minta dengan pak ariandi mas @devrakapriyo 

ERROR - 2022-10-05 13:18:59 --> Severity: error --> Exception: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'updated_at' in 'field list' (SQL: select id_pend, tanggal_buat, updated_at from tweb_penduduk_mandiri where date(updated_at) = 0000-00-00) /home/u1712551/public_html/vendor/illuminate/database/Connection.php 712

**Comment by andifahruddinakas** [comment]
Saya tidak menemukan kendala terkait issue ini, silahkan dibuka kembali jika memukan masalah ini dengan melampirkan backup database yang bermasalah.
