### ISSUE TITLE
Bug/error: gagal memasukan gambar/logo pada identitas desa

### ISSUE THREAD

**Issue by Restony33** [OpenSID/OpenSID#5801]
### Jelaskan error yg dialami

Saat memilih gambar/logo yang ingin diterapkan pada lambang desa, kembali lagi ke pilih gambar 

### Cara untuk mereplikasi errornya

masuk ke admin >> info desa >>Identitas Desa >> ubah data Desa >> ganti lambang desa

### Hasil yg diharapkan

normal dapat memilih gambar/logo yang digunakan sebagai logo desa

### Tangkapan layar dan log error

![Capture](https://user-images.githubusercontent.com/104592011/194511432-a7f46ba9-ba56-4184-ab99-d85b66685f0f.JPG)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

premium (v22.10-premium)

### Tema Yang Digunakan

batuah

### Informasi tambahan

.

**Comment by apidong** [comment]
mungkin lebih tepatnya judulnya double input file saat pilih gambar.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1453
