### ISSUE TITLE
Error pada print di peta

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#5803]
1. masuk ke menu pemetaan 
<img width="798" alt="image" src="https://user-images.githubusercontent.com/59082428/194695172-ed345a31-c52c-4826-8262-fca2bfd03e04.png">
2. lalukan filter apa saja 
<img width="794" alt="image" src="https://user-images.githubusercontent.com/59082428/194695283-8e12ba95-313f-418b-a1ca-b6024c8f4303.png">

3. Lalu klik print dan pilih salah satu dari 3 pilihan 
<img width="157" alt="image" src="https://user-images.githubusercontent.com/59082428/194695274-a3696736-7d4b-48c9-99fe-d804785d9696.png">

4. Maka tampilan muncul seperti ini 
<img width="958" alt="image" src="https://user-images.githubusercontent.com/59082428/194695306-4e0c0785-a033-49d1-b146-28081f087fbc.png">

**5. Harusnya ada langsung minta print tanpa harus klik ctrl + P**

<img width="471" alt="image" src="https://user-images.githubusercontent.com/59082428/194514940-79f9889a-60ff-4482-a43e-11e718323049.png">

**Comment by andifahruddinakas** [comment]
Mas @vickyrolanda, di tulis juga solusinya atau apa yang diharapkan.

**Comment by andifahruddinakas** [comment]
Mas @vickyrolanda, diperjelas issue ini maunya di apakan, karena bagian ini sy tdk terlalu menyimak.

**Comment by vickyrolanda** [comment]
mas @andifahruddinakas sudah sy lengkapin di deskripsi intinya ketika klik print maka tampilan harusnya minta print tanpa klik + P lagi mas.

**Comment by andifahruddinakas** [comment]
Ok

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1457
