### ISSUE TITLE
OpenSID & OpenDK tidak sinkronisasi jika ada penduduk yang sudah pindah dll.

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#5804]
Kasus terjadinya ini kemungkinan karena ada pergantian data di database sehingga tidak ada log penduduknya. 

Perlu di periksa di UMUM.

**Comment by yogiperdana** [comment]
Ralat mas: jika penduduk sudah dihapus/pindah/ganti status namun tidak terdaftar di log terkait sehingga menimbulkan data lama di opendk tidak terupdate

**Comment by vickyrolanda** [comment]
Solusinya : seperti sinkronisasi awal ketika di lakukan sinkron maka data dihapus dan di ganti yang baru . 
Perlu dicheck bagaimana proses sinkronisasinya OpenSID ke OpenDK, mungkin jika di perlukan buat 1 fungsi untuk meganti semua penduduk dengan sinkronisasi data yang baru sehingga semua data diperbarui sesuai data yang ada di OpenSID.
