### ISSUE TITLE
Bug/error: Artikel terbaru di OpenSID tidak muncul di OpenDK

### ISSUE THREAD

**Issue by hasap86** [OpenSID/OpenSID#5806]
### Jelaskan error yg dialami

Artikel terbaru yang ditulis di opensid tidak muncul di opendk

### Cara untuk mereplikasi errornya

tulis artikel di opensid terbaru dan lihat di opendk yg terhubung

### Hasil yg diharapkan

biasanya muncul artikel dari opensid desa di opendk kecamatan

### Tangkapan layar dan log error

OPENSID : 

https://cikahuripan.desa.id/artikel/2022/10/7/kapolres-sukabumi-dan-kepala-desa-cikahuripan-membagikan-paket-sembako-jumat-berkah-janda-jompo 

OPENDK : 

https://cisolok.sukabumikab.go.id/

### Rilis Versi OpenSID

Rilis Umum

### Versi OpenSID

v22.10

### Tema Yang Digunakan

Esensi

**Comment by apidong** [comment]
@hasap86 Silahkan update OPENDK nya ke Versi Terbaru.
![image](https://user-images.githubusercontent.com/20056421/194909361-8a0a21bd-a798-411c-8142-834d55ec7589.png)

**Comment by apidong** [comment]
@vickyrolanda silahkan cek menggunakan opendk versi terbaru pak.

**Comment by vickyrolanda** [comment]
terimakasih mas @apidong , saya sudah coba dan terkonfirmasiih muncul mas , mohon tes ke OpenDK yang versi terbaru ya pak dan jangan lupa setting link website desanya pak @hasap86 , saat ini saya close issuenya pak mohon di buka kembali jika masih mengalamin dan mohon lampirkan log errornya ya pak.
<img width="747" alt="image" src="https://user-images.githubusercontent.com/59082428/194952644-170afac8-7126-4498-87c7-2c12c573a036.png">
