### ISSUE TITLE
 Ubah status aktif & tidak aktif pada program bantuan tidak berfungsi

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#5812]
1. coba edit program bantuan 
<img width="793" alt="image" src="https://user-images.githubusercontent.com/59082428/194744515-93985d22-b96e-49c1-b9f2-d5e854119088.png">
di ubah menjadi aktif -> lalu simpan 

2. lihat di daftar di bagian status 
ketika di simpan laporan berhasil namun di daftar tidak berubah status dan ketika di edit lagi status juga tidak berubah
<img width="795" alt="image" src="https://user-images.githubusercontent.com/59082428/194744550-389d6ef5-9c06-47fa-b4b0-9a4ac2b59788.png">

**Comment by andifahruddinakas** [comment]
Rancangan awal dibuat otomatis aktif dimana status aktif diambil dari retang tanggal awal dan akhir. Namun duplikasi inputan, harusnya pilih status di hilangkan atau hanya sebagai informasi saja.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1464
