### ISSUE TITLE
Bug/error: modalBox hanya sekali tampil dan tidak berubah jika halaman tidak di refresh

### ISSUE THREAD

**Issue by ruririzal** [OpenSID/OpenSID#5813]
### Jelaskan error yg dialami

-

### Cara untuk mereplikasi errornya

1. pergi ke halaman penduduk
2. klik tombol "pilih aksi lainnya' -> 'cetak'
3. muncul load tampilan cetak
4. klik tombol "pilih aksi lainnya' -> unduh
5. tidak me-load tampilan unduh
6. --- coba refresh halaman -----
7. klik tombol "pilih aksi lainnya' -> unduh
8. muncul load tampilan unduh
9. klik tombol "pilih aksi lainnya' -> 'cetak'
10. tidak me-load tampilan cetak

### Hasil yg diharapkan

Solusi: tambahkan pelepasan event dan reinisiasi event jika modal ditutup
script.js

    $('#modalBox').one('hidden.bs.modal', function(e) {
		$('#modalBox').off('show.bs.modal');
		$('#modalBox').off('hidden.bs.modal');
		// reinisiasi
		modalBox();
	});

![image](https://user-images.githubusercontent.com/28647065/194772365-7097da11-7f9a-4390-8af7-fa7ecdad1f1a.png)

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

umum & premium

**Comment by ruririzal** [comment]
repikasi error dapat terjadi di berbagai halaman yg sering menggunakan modal tanpa refresh halaman

**Comment by apidong** [comment]
@vickyrolanda bug ini sama dengan issue https://github.com/OpenSID/OpenSID/issues/5787 dan sudah diperbaiki di premium

**Comment by vickyrolanda** [comment]
mas @ruririzal  saya sudah check ulang dan konfirmasi dan sudah di perbaikin sebelumnya silahkan update dengan PR ini mas https://github.com/OpenSID/premium/pull/1449 jika masih mengalamin kendala silahkan open lagi issue ini mas.
