### ISSUE TITLE
Gagal migrasi 

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#5814]
```
ERROR - 2022-10-10 02:11:31 --> Query error: Incorrect DECIMAL value: '0' for column '' at row -1 - Invalid query: ALTER TABLE `keuangan_manual_rinci`
	MODIFY `Nilai_Anggaran` decimal(65,2) NOT NULL
```

Lakukan migrasi pada data desa yang sudah ada data keuangan impor maupun manual.

Mas @vickyrolanda, @devrakapriyo, @apidong, coba di cek yang ini.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1459
