### ISSUE TITLE
Bug/error: Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 7.4.0".

### ISSUE THREAD

**Issue by pemdespancur** [OpenSID/OpenSID#5816]
### Jelaskan error yg dialami

Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 7.4.0".

### Cara untuk mereplikasi errornya

Setelah update dari versi 22.09 ke versi 22.10

### Hasil yg diharapkan

bug teratasi

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/34035346/194799362-5093ccd7-c0ce-405a-9824-e12179f80e40.png)

### Rilis Versi OpenSID

Rilis Umum

### Versi OpenSID

22.10

### Tema Yang Digunakan

cosmo

**Comment by apidong** [comment]
@pemdespancur silahkan update versi php ke versi 7.4.xx

**Comment by vickyrolanda** [comment]
mas @pemdespancur  silahkan update versi php ke versi 7.4.xx sesuai rekomendasi sistem, jika masih mengalamin kendala silahkan open lagi issue ini dan berikan log errornya mas.

**Comment by pemdespancur** [comment]
> mas @pemdespancur silahkan update versi php ke versi 7.4.xx sesuai rekomendasi sistem, jika masih mengalamin kendala silahkan open lagi issue ini dan berikan log errornya mas.

Oke mas @vickyrolanda, kebetulan server nya ikut kominfo, sudah konfirmasi ke bagian server tapi nda ada perubahan, jadi cari solusi sendiri.....platform check file saya turunin yg support di server 

if (!(PHP_VERSION_ID >= 70400)) {
    $issues[] = 'Your Composer dependencies require a PHP version ">= 7.4.0". You are running ' . PHP_VERSION . '.';

saya turunin jadi 

if (!(PHP_VERSION_ID >= 70300)) {
    $issues[] = 'Your Composer dependencies require a PHP version ">= 7.3.0". You are running ' . PHP_VERSION . '.';

Mohon maaf para master
