### ISSUE TITLE
Dimohon untuk versi terbaru tema berbayar atau premium langsung masuk kedalam zipp. supaya jika ada update tema langsung dipilih dan desa juga bisa mencoba tema tema terabaru

### ISSUE THREAD

**Issue by Fajar-blackdeath** [OpenSID/OpenSID#5817]
### Apa kekurangan yg ingin diatasi?

Dimohon untuk versi terbaru opensid premium didaalamnya sudag ada tema berbayar atau premium langsung masuk kedalam zipp. supaya jika ada update tema langsung dipilih dan desa juga bisa mencoba tema tema terabaru. 
kesulitan untuk update tiap ada pembaruan tema dll, kemudna ada beberapa tema yang klo sudah diperbarui tema lama tidak bisa digunakan

### Jelaskan solusi yg diinginkan

Dimohon untuk versi terbaru tema berbayar atau premium langsung masuk kedalam zipp. supaya jika ada update tema langsung dipilih dan desa juga bisa mencoba tema tema terabaru. 
kesulitan untuk update tiap ada pembaruan tema dll, kemudna ada beberapa tema yang klo sudah diperbarui tema lama tidak bisa digunakan

### Apakah ada alternatif lain

Dimohon untuk versi terbaru tema berbayar atau premium langsung masuk kedalam zipp. supaya jika ada update tema langsung dipilih dan desa juga bisa mencoba tema tema terabaru. 
kesulitan untuk update tiap ada pembaruan tema dll, kemudna ada beberapa tema yang klo sudah diperbarui tema lama tidak bisa digunakan.
mohon dikomunikasikan dengan pemilik tema agar tidak berulang kali update dll

### Untuk versi OpenSID mana

22.11 fix  fix fixxx

### Informasi tambahan

Dimohon untuk versi terbaru tema berbayar atau premium langsung masuk kedalam zipp. supaya jika ada update tema langsung dipilih dan desa juga bisa mencoba tema tema terabaru. 
kesulitan untuk update tiap ada pembaruan tema dll, kemudna ada beberapa tema yang klo sudah diperbarui tema lama tidak bisa digunakan

**Comment by andifahruddinakas** [comment]
Duplicate issue https://github.com/OpenSID/OpenSID/issues/2486
