### ISSUE TITLE
Fitur hapus surat tidak muncul di opensid versi 20.10 premium

### ISSUE THREAD

**Issue by makhbub** [OpenSID/OpenSID#5818]
### Jelaskan error yg dialami

Di menu arsip surat pilihan hapus tidak muncul, sehingga tidak bisa menghapus surat yg salah

### Cara untuk mereplikasi errornya

Layanan surat > Arsip surat

### Hasil yg diharapkan

Tampilkan kembali fitur hapus surat, untuk menghapus surat layanan yg salah, 

### Tangkapan layar dan log error

![Uploading 1665418195103193373852697490295.jpg…]()

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

V22.10

### Tema Yang Digunakan

Silir

### Informasi tambahan

-

**Comment by apidong** [comment]
@vickyrolanda coba cek dengan issue ini pak https://github.com/OpenSID/OpenSID/issues/5580.
apakah issuenya sama?

**Comment by makhbub** [comment]
Ternyata sama pak, mohon maaf kurang teliti
Dengan ini issue saya tutup
