### ISSUE TITLE
OPENSID: Alert gagal pendaftaran kerjasama

### ISSUE THREAD

**Issue by FirlianiF** [OpenSID/OpenSID#5819]
### Jelaskan error yg dialami

[-](https://github.com/OpenSID/OpenSID/issues/5672)

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

-

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1466
