### ISSUE TITLE
Permintaan fitur: surat TinyMCE untuk non warga

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#5821]
### Apa kekurangan yg ingin diatasi?

saat ini di surat TinyMCE belum tersedia untuk non warga tidak sama seperti dengan surat RTF yang sudah tersedia untuk non warga

### Jelaskan solusi yg diinginkan

sediakan fitur untuk non warga di surat TinyMCE

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

v22.11-premium

**Comment by apidong** [comment]
tambahkan untuk memberi keleluasaan pada kita untuk bisa menampilkan cari nik/penduduk, sebagaimana kita bisa  bebas memilih mau pake header atau tidak

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/2111
