### ISSUE TITLE
Permintaan fitur: Tersedianya Pengaturan Sebutan Aparatur Desa

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#5823]
### Apa kekurangan yg ingin diatasi?

Memperhatikan ada beberapa sebutan Pemerintah Desa di berbagai wilayah, seperti Aparatur, Pamong, Perangkat, Kamituwo, Bayan, Bekel, Bau, DLL.

### Jelaskan solusi yg diinginkan

Sebagaimana diterapkan pada Pengaturan Sebutan Dusun, Sebutan Desa, hingga Sebutan Kabupaten. Agar juga tersedia Kolom untuk Sebutan Aparatur Desa tersebut.

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

Rilis Mendatang

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1577 

caranya bisa masuk ke : 
1. Buku administrasi Desa 
2. klik kanan gear di pojok kanan atas 
3. bisa ganti nama pemerintah desa dengan sebutan masing - masing wilayah  
<img width="958" alt="image" src="https://user-images.githubusercontent.com/59082428/202888827-9cbf0ec9-e7ce-4042-bbd8-d1611a5dcd22.png">
