### ISSUE TITLE
Permintaan fitur: Bahan Hari Libur 2023 sesuai SKB 3 Menteri

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#5824]
### Apa kekurangan yg ingin diatasi?

![IMG_20221011_211210](https://user-images.githubusercontent.com/46939846/195115101-bde41eb6-ed9c-4cf9-a31c-dd7f8bf022d9.jpg)

![IMG_20221011_211225](https://user-images.githubusercontent.com/46939846/195115135-24e70d3a-3baa-4abb-a198-7285a7a79e42.jpg)

### Jelaskan solusi yg diinginkan

Sebagai bahan untuk masuk ke Menu Kehadiran - Hari Libur untuk Tahun 2023

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

Rilis Mendatang

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/OpenSID/pull/6933
