### ISSUE TITLE
Bug/error: tidak boleh menghapus wilayah RW atau Dusun yang sudah berpenghuni

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#5826]
### Jelaskan error yg dialami

jika RW atau Dusun di hapus hal ini akan menyebabkan data tweb penduduk pada kolom id cluster, angka yg ada adalah ID cluster lain yg sudah tidak ada di tweb_cluster. 

jika RW atau Dusun sudah terhapus maka solusi saat ini dengan membuat RW baru, lalu pada tabel tweb cluster diubah ID nya sesuai ID RW lama maka akan normal kembali.

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

Opsi Solusi : 
- ditiadakan fitur delete RT, RW atau Dusun jika sudah ber penduduk (hanya bisa edit)
- sediakan fitur non aktifkan / soft delete RT, RW atau Dusun

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

22.10-premium-rev01

**Comment by ariandii** [comment]
Termasuk RT

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1485
