### ISSUE TITLE
OPENSID: Tambah tombol pada informasi layanan 

### ISSUE THREAD

**Issue by FirlianiF** [OpenSID/OpenSID#5827]
### Apa kekurangan yg ingin diatasi?

https://github.com/OpenSID/wiki-layanan-opendesa/issues/164

### Jelaskan solusi yg diinginkan

-

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

-

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1491
