### ISSUE TITLE
OPENSID: Pisah tabel pemesanan dan lainnya

### ISSUE THREAD

**Issue by FirlianiF** [OpenSID/OpenSID#5828]
### Apa kekurangan yg ingin diatasi?

https://github.com/OpenSID/wiki-layanan-opendesa/issues/163

### Jelaskan solusi yg diinginkan

-

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

-

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1477
