### ISSUE TITLE
Permintaan fitur: export Scorecard Konvergensi

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#5830]
### Apa kekurangan yg ingin diatasi?

Scorecard Konvergensi salah satu syarat pengajuan Dana Desa Tahap III, dan saat ini belum ada fitur export

![image](https://user-images.githubusercontent.com/36557759/195490666-5431575a-70d4-4af7-aa5c-1d200cd4adac.png)

### Jelaskan solusi yg diinginkan

tambahkan fitur export Scorecard Konvergensi

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

22.11-premium

**Comment by devrakapriyo** [comment]
[LAPORAN KONVERGENSI.xlsx](https://github.com/OpenSID/OpenSID/files/9776368/LAPORAN.KONVERGENSI.xlsx)

Format export

**Comment by andifahruddinakas** [comment]
Duplicate of https://github.com/OpenSID/OpenSID/issues/6342
