### ISSUE TITLE
Bug/error thema esensi : Pilihan import dokumen tidak berfungsi pada layanan surat mandiri

### ISSUE THREAD

**Issue by K4nzzz** [OpenSID/OpenSID#5831]
### Jelaskan error yg dialami

Ketika akan mengimport foto atau dokumen pendukung pada lyananan surat mandiri.
Tidak muncul pilihan atau tidak diarahkan menuju penyimpanan atau galery. 
Ini berlaku juga saat mengimport dokumen pendukung mendaftar mandiri.

### Cara untuk mereplikasi errornya

.

### Hasil yg diharapkan

Segera di perbaiki

### Tangkapan layar dan log error

Versi mobile
![IMG_20221013_221938](https://user-images.githubusercontent.com/115149951/195639876-a78966b8-cb43-4790-aecc-a36466dd6438.jpg)

Versi PC

### Rilis Versi OpenSID

Rilis Umum

### Versi OpenSID

v22.10

### Tema Yang Digunakan

Essensi

### Informasi tambahan

- [No[](url)](url)

**Comment by apidong** [comment]
@K4nzzz itu karena dokumennya belum ada.
apakah dokumen sudah di upload?
jika belum, silahkan upload terlebih dahulu di modul dokumen.
![image](https://user-images.githubusercontent.com/20056421/196072423-192d0baa-82b4-49be-94c4-491062d979bd.png)

**Comment by K4nzzz** [comment]
> @K4nzzz itu karena dokumennya belum ada. apakah dokumen sudah di upload? jika belum, silahkan upload terlebih dahulu di modul dokumen. ![image](https://user-images.githubusercontent.com/20056421/196072423-192d0baa-82b4-49be-94c4-491062d979bd.png)

Terimakasih infonya min maju terus opensid
