### ISSUE TITLE
Bug/error: Terjadi error ketika periksa surat tinymce permohonan warga yang tidak ada dokumen / persyaratan

### ISSUE THREAD

**Issue by yogiperdana** [OpenSID/OpenSID#5832]
### Jelaskan error yg dialami

ERROR - 2022-10-13 22:34:47 --> Severity: error --> Exception: Argument 1 passed to Illuminate\Database\Query\Builder::cleanBindings() must be of the type array, null given, called in premium\vendor\illuminate\database\Query\Builder.php on line 997 (View: premium\resources\views\admin\surat\periksa.blade.php) premium\vendor\illuminate\database\Query\Builder.php 3369

### Cara untuk mereplikasi errornya

Buat surat tinymce tanpa persyaratan dokumen
Buat surat tersebut dari layanan mandiri
Setujui di permohonan surat
Masuk ke arsip dan periksa

### Hasil yg diharapkan

Normal

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.10-premium

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1490
