### ISSUE TITLE
Bug/error: tampilan priview embed /source code pada thema essensi tidak bisa tampil diwebsite

### ISSUE THREAD

**Issue by K4nzzz** [OpenSID/OpenSID#5834]
### Jelaskan error yg dialami

Tampilan priview embed pada thema essensi tidak bisa tampil di website
Hanya tampil source codenya saja

### Cara untuk mereplikasi errornya

Ok

### Hasil yg diharapkan

Dapat segera diperbaiki dan tampil normal

### Tangkapan layar dan log error

Tampilan mengimport embed

![Uploading IMG_20221014_132420.jpg…]()

Output di halaman website
![Screenshot_2022-10-14-13-17-05-37](https://user-images.githubusercontent.com/115149951/195777787-cb5e4770-8c85-4e2e-bcf8-c8c6f8532d92.jpg)

### Rilis Versi OpenSID

Rilis Umum

### Versi OpenSID

v22.10

### Tema Yang Digunakan

Essensi

### Informasi tambahan

Ok

**Comment by vickyrolanda** [comment]
mas @K4nzzz  mohon bantuannya memperjelas ini ditambahkan pada menu apa ?

**Comment by K4nzzz** [comment]
> mas @K4nzzz mohon bantuannya memperjelas ini ditambahkan pada menu apa ?

Tampilan websitnya tidak tampil perintah emberd .
Di menu artikel bpk @vickyrolanda 
Ketika kita insert video (embed) sudah memasukan source tapi di tampilan website tidak bisa menampilkan .

**Comment by K4nzzz** [comment]
![Uploading IMG_20221014_132420.jpg…]()

**Comment by K4nzzz** [comment]
![Uploading IMG_20221016_072709.jpg…]()
![Uploading IMG_20221016_072820.jpg…]()

**Comment by K4nzzz** [comment]
![IMG-20221016-WA0006](https://user-images.githubusercontent.com/115149951/196012405-face59cc-a806-4cc9-9c6d-d6a3b978614b.jpg)
![IMG-20221016-WA0005](https://user-images.githubusercontent.com/115149951/196012406-863078d8-9d92-41c8-b0be-316c2c7ad174.jpg)

**Comment by apidong** [comment]
https://github.com/OpenSID/OpenSID/wiki/Artikel#cara-menyisipkan-media-dalam-artikel
silahkan di baca terlebih dahulu terkait embed media melalui iframe. @K4nzzz @vickyrolanda

**Comment by K4nzzz** [comment]
> https://github.com/OpenSID/OpenSID/wiki/Artikel#cara-menyisipkan-media-dalam-artikel silahkan di baca terlebih dahulu terkait embed media melalui iframe. @K4nzzz @vickyrolanda

Oke thanks min
