### ISSUE TITLE
Rubah form excel impor Klasifikasi Surat menjadi seperti form excel impor penduduk

### ISSUE THREAD

**Issue by makhbub** [OpenSID/OpenSID#5835]
### Apa kekurangan yg ingin diatasi?

di beberapa daerah, termasuk kabupaten kami, klasifikasi surat memiliki aturan tersendiri, sehingga form impor data klasifikasi surat sangat diperlukan.
form excel impor klasifikasi surat yang saat ini sudah ada cukup sulit untuk diterapkan, karena seluruh komponen klasifikasi surat seperti id,kode,nama,uraian,enabled dibuat dalam satu cell excel dan hanya dipisahkan dengan koma ( , )

### Jelaskan solusi yg diinginkan

form impor excel klasifikasi surat dibuat seperti form impor penduduk dimana setiap komponen klasifikasi surat dipisahkan tiap kolom, sehingga memudahkan untuk setting bahan impor klasifikasi surat

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

22.11 Premium

### Informasi tambahan

![form excel klasifikasi surat](https://user-images.githubusercontent.com/38773660/195861349-965eedd3-0753-4bf0-a8ec-f1e7b7dba5f5.jpg)
form excel impor klasifikasi surat

![form excel impor penduduk](https://user-images.githubusercontent.com/38773660/195861449-e85b2c6b-4854-402f-8673-daf8ef38eeb4.jpg)
form impor penduduk

**Comment by andifahruddinakas** [comment]
cek diversi terbaru
