### ISSUE TITLE
Bug/error: Menu Pada Peta Hilang

### ISSUE THREAD

**Issue by ilamazuliaf** [OpenSID/OpenSID#5836]
### Jelaskan error yg dialami

Tampilan menu peta tidak muncul di Identitas Desa maupun dilainnya

### Cara untuk mereplikasi errornya

1. Pergi ke halaman Identitas Desa
2. Klik tombol Lokasi Kantor Desa

### Hasil yg diharapkan

Menu peta yang hilang bisa kembali seperti sedia kala

### Tangkapan layar dan log error

<img width="1280" alt="Screen Shot 2022-10-14 at 23 13 35" src="https://user-images.githubusercontent.com/31075119/195908865-33721b8f-cce3-4530-8bf7-d34ba5af7481.png">
<img width="1280" alt="Screen Shot 2022-10-14 at 23 13 30" src="https://user-images.githubusercontent.com/31075119/195908910-624edf00-6007-477f-b793-d81d22e21cd4.png">

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.10-premium

### Tema Yang Digunakan

Denatra

### Informasi tambahan

Percobaan melakukan backup database OpenSID versi online dan direstore ke OpenSID versi offline (dijalankan secara lokal) menu pada peta tampil tanpa ada kendala.

Mencoba menginstall OpenSID di subdomain https://sid.kambinganbarat.com menu pada peta muncul.

Mencoba menggunakan config database yang dipakai di subdomain sid.kambinganbarat.com ke domain utama, menu pada peta muncul kembali

**Comment by vickyrolanda** [comment]
mas @devrakapriyo  mohon bantu check apakah issue ini valid di mas raka ? karena di saya itu masih muncul 
<img width="795" alt="image" src="https://user-images.githubusercontent.com/59082428/195958253-fdbd26bf-9387-4db8-a1af-28a0159216d9.png">

**Comment by ariandii** [comment]
> mas @devrakapriyo mohon bantu check apakah issue ini valid di mas raka ? karena di saya itu masih muncul <img alt="image" width="795" src="https://user-images.githubusercontent.com/59082428/195958253-fdbd26bf-9387-4db8-a1af-28a0159216d9.png">

100% ini faktor dari sisi hosting.

**Comment by ilamazuliaf** [comment]
Setelah menghubungi pihak hosting alhamdulillah bisa. Jadi permasalahannya ada di pihak hosting
