### ISSUE TITLE
Error pada buat surat , surat berhasil dibuat namun tidak tersimpan dan tidak muncul di arsip dan permohonan surat

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#5838]
Check setiap buat surat surat tidak masuk ke permohonan surat / arsip surat, mau di aktifkan TTE atau tidak diaktifkan TTEnya.
<img width="951" alt="image" src="https://user-images.githubusercontent.com/59082428/195947170-11bacf68-4c32-440a-b5b0-6aa198ab974e.png">

**Comment by scqolbu24** [comment]
Tambahan issue berkaitan dengan Surat yang dilaporkan oleh Pak Guspendi Ansyori:
Menu Pengaturan Surat, Cetak Surat, Permohonan Surat, Daftar Persyaratan muncul eror seperti berikut: 
![error buka modul layanan surat](https://user-images.githubusercontent.com/68048807/196023938-ee977a1e-1d4a-49b8-b7e6-e3f7abf19147.jpg)

Untuk Arsip surat dapat tampil, namun ketika klik Cetak Surat muncul error berikut:
![error ketika cetak surat](https://user-images.githubusercontent.com/68048807/196024129-bb88ab75-8507-4829-95b0-005976f52fc4.JPG)

Ketika akan mengunduh log eror, muncul eror seperti gambar berikut:
![error unduh logs](https://user-images.githubusercontent.com/68048807/196024158-f137e231-f9c9-4286-9312-c6bdb9e2198a.JPG)

NB: Mas @apidong saya kirim databasenya untuk dapat replikasi.

**Comment by vickyrolanda** [comment]
mas @apidong saya test di rilis-dev & bug-fix sudah tidak mengalamin ini jadi saya close dulu ya
