### ISSUE TITLE
Bug/error: ketika klik semua menu di Layanan Surat muncul error datatables warning: tableid=tabeldata 

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/OpenSID#5839]
Issue ini dilaporkan oleh Pak Guspendi Ansyori:
Klik Menu Pengaturan Surat, Cetak Surat, Permohonan Surat, Daftar Persyaratan muncul eror seperti berikut: 
![error buka modul layanan surat](https://user-images.githubusercontent.com/68048807/196023938-ee977a1e-1d4a-49b8-b7e6-e3f7abf19147.jpg)

Untuk Arsip surat dapat tampil, namun ketika klik Cetak Surat muncul error berikut:
![error ketika cetak surat](https://user-images.githubusercontent.com/68048807/196024129-bb88ab75-8507-4829-95b0-005976f52fc4.JPG)

Ketika akan mengunduh log eror, muncul eror seperti gambar berikut:
![error unduh logs](https://user-images.githubusercontent.com/68048807/196024158-f137e231-f9c9-4286-9312-c6bdb9e2198a.JPG)

NB: Mas @apidong saya kirim databasenya untuk dapat replikasi.  

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.10-premium-rev01

**Comment by apidong** [comment]
![image](https://user-images.githubusercontent.com/20056421/196068390-43f26f94-e3ec-4d5f-8e5d-afd10a166a5b.png)
![image](https://user-images.githubusercontent.com/20056421/196068462-8a4364cd-6ed5-4b2e-bd5c-d148fbe8dc44.png)
![image](https://user-images.githubusercontent.com/20056421/196068509-accb68f2-de32-45c6-8373-94a2e84fa370.png)
saya cek di lokal semuanya normal

**Comment by apidong** [comment]
info dari pak guspendi. error sudah teratasi dengan menginstall ulang  opensid. 
issue saya closse.
