### ISSUE TITLE
Gambar Slider

### ISSUE THREAD

**Issue by kelbatuix** [OpenSID/OpenSID#584]
Mohon dapat memperbaiki settingan gambar slider pada theme Happy Agung. Yakni pada penampilan gambar mengambil posisi center sehingga area sekitar atas, bawah, kiri dan kanan pada gambar terpotong.
![screenshot 3](https://user-images.githubusercontent.com/25999158/29505713-0b3aba8c-8672-11e7-8de9-36e4db24e4a5.png)

**Comment by MUHAMMADRANGSEL** [comment]
Diperkecil ukuran gambarnya waktu diupload

**Comment by Marzuki5** [comment]
Disesuaikan dengan ukuran slider gambarnya

**Comment by MUHAMMADRANGSEL** [comment]
Issue ini sebaiknya ditutup

**Comment by MUHAMMADRANGSEL** [comment]
Mas eddie sebaiknya issue ini di closed
