### ISSUE TITLE
Bug/error: Tulisan Pada Surat Tidak Sesuai mulai KOP sampai bawah TTD

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#5841]
### Jelaskan error yg dialami

Bisa perhatikan gambar di bawah ini:

<img width="498" alt="screenshot_93" src="https://user-images.githubusercontent.com/46939846/196322416-a905200e-413f-4cdd-b627-afc456eb9c47.png">

<img width="660" alt="screenshot_92" src="https://user-images.githubusercontent.com/46939846/196322421-381d1fa7-46ea-4346-89a4-50fc760a7e35.png">

<img width="340" alt="screenshot_91" src="https://user-images.githubusercontent.com/46939846/196322425-057d3e39-a7ee-4577-8e33-f51d62e2cb43.png">

<img width="713" alt="screenshot_90" src="https://user-images.githubusercontent.com/46939846/196322428-aa9b0a62-5c61-4cf8-ad09-b03b041ac165.png">

### Cara untuk mereplikasi errornya

Terdapat beberapa tulisan yang seharusnya tidak demikian. seperti:
1. Jl. Pangkalan Lima IQ, Pangkalan Bun **namun tertulis di surat menjadi** Jl. pangkalan lima iq, pangkalan bun xxx
2. MASIRIN, SE **namun tertulis di surat menjadi** Masirin, se
3. NIPD **tertulis di surat penandatangan menjadi** Nipd
4. SLTA/Sederajat **tertulis di surat menjadi** Slta/sederajat
5. DLL yang bisa dicek ulang.

### Hasil yg diharapkan

Format huruf besar dan kecil sesuai dengan seharusnya dan diharapkan sesuai dengan yang sudah diketik pada kolom pengaturan masing-masing.

Untuk email sudah benar hufuf kecil semua. (**jangan dibuat huruf besar awal** Admin@natairaya.desa.id)

### Tangkapan layar dan log error

Ada di atas

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Baru

**Comment by vickyrolanda** [comment]
pak @ariandii  ini mungkin masuknya ke rilis-dev sebagai susulan, agar tidak terjadi duplikasi perbaikan (krn di rilis-dev sudah disediakan). Untuk data normal bisa gunakan [kode_isian] kecil semuan untuk keluaran data dari database (tanpa ada ubahan)

jadi ijin saya close issue ini ya pak.
