### ISSUE TITLE
Data induvidu selain menampilkan data bantuan individu juga menampilkan data bantuan Keluarga dan Rumah Tangga

### ISSUE THREAD

**Issue by makhbub** [OpenSID/OpenSID#5842]
### Apa kekurangan yg ingin diatasi?

data bantuan ada tiga kelompok penerima yaitu ;
1. Individu dimana penerimanya setiap orang secara pribadi
2. Keluarga dimana penerimanya adalah keluarga. 
3. Rumah Tangga dimana  penerima bantuannya adalah satu rumah tertentu

Di desa, data bantuan merupakan suatu hal yang riskan apabila tidak terkelola dengan baik. Pemerintah desa harus memastikan / mengusahakan masyarakat yang layak untuk menerima bantuan. selain itu, Pemerintah Desa juga harus memastikan bahwa tidak ada penerima ganda dalam suatu bantuan.
Hal yang tidak kalah penting, berkaitan dengan pemanfaatan OpenSID, Pemerintah desa diharapkan bisa secara cepat menjelaskan kepada masyarakat, data seorang individu menerima bantuan apa saja baik sebagai individu, anggota keluarga maupun anggota Rumah Tangga.

### Jelaskan solusi yg diinginkan

- pada data bantuan individu, selain menampilkan data bantuan yang didapat  sebagai individu, juga menampilkan data bantuan sebagai keluarga dan sebagai Rumah Tangga

- pada data bantuan Keluarga, selain menampilkan data bantuan yang didapat sebagai Keluarga, juga menampilkan data bantuan yang didapat sebagai Rumah Tangga

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

V 22.11 Premium

### Informasi tambahan

![Bantuan individu](https://user-images.githubusercontent.com/38773660/196328841-6ce143db-99cd-4de3-af39-3da4e8bc4245.jpg)

![Bantuan Keluarga](https://user-images.githubusercontent.com/38773660/196328859-0e3c4254-b8d5-489d-a67d-c195c488fab5.jpg)

**Comment by andifahruddinakas** [comment]
Sebaiknya tetap seperti ini, agar tidak memberatkan load data masing2 modul.

**Comment by makhbub** [comment]
Seandainya hanya disediakan link / shortcut ke jenis bantuan lain, apakah masih berpengaruh pada loading halamanya pak ?
