### ISSUE TITLE
Bug/error: peraturan desa, upload dokumen data too long

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#5845]
### Jelaskan error yg dialami

![image](https://user-images.githubusercontent.com/36557759/196841157-f1d11d75-7fe2-4855-b82c-73bd5070c503.png)

saat mengupload dokumen dengan name file yang panjang terjadi error

### Cara untuk mereplikasi errornya

- klik menu Administrasi Desa
- klik menu Administrasi Umum
- klik menu Buku Peraturan Desa
- klik tombol Perdes Baru

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

22.10-premium-rev02

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1512
