### ISSUE TITLE
Bug/error: error proses migrasi karena identifikasi versi yang keliru

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#5846]
### Jelaskan error yg dialami

bug ini yang di sampaikan pak Bubby Saputra di group OpenSID Premium
![image](https://user-images.githubusercontent.com/36557759/196843470-1dc50548-2699-4fe9-9f72-a5d652656e2e.png)
dan sudah di berikan solusi oleh pak @ariandii 
![image](https://user-images.githubusercontent.com/36557759/196843681-d4c27b58-aafc-45d6-94d1-429340688cbf.png)
![image](https://user-images.githubusercontent.com/36557759/196843694-598841d8-ab7a-4925-a8dc-d29e7cd0632f.png)

Sepertinya disebabkan identifikasi versi yang keliru, di mana penamaan versi lama tidak dikenali dengan baik, sehingga proses migrasi menjadi bingung

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.10-premium-rev02

**Comment by devrakapriyo** [comment]
INFO SOLUSI : mengubah current version dari 22.10 ke 22.09 di table setting_aplikasi

sehingga penamaan versi lama tidak dikenali dengan baik.

ini membuat keliru 22.10 yg tidak dikenali. padahal sudah terpasang 22.10-premium maupun rev nya.

**Comment by eddieridwan** [comment]
> INFO SOLUSI : mengubah current version dari 22.10 ke 22.09 di table setting_aplikasi

Mengubah current version bukan solusi utk diterapkan (itu hanya cara pelaksana supaya dapat membantu secara praktis). Solusinya yg diperlukan adalah mampu deteksi versi secara akurat. Dan juga perhatikan bahwa migrasi tergantung juga versi database.

**Comment by devrakapriyo** [comment]
ini terjadi error saat melakukan proses migrasi :
- dari versi umum ke premium
- dari versi premium yang cukup jauh versinya ke versi premium terbaru

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1506

**Comment by roaddee** [comment]
> > INFO SOLUSI : mengubah current version dari 22.10 ke 22.09 di table setting_aplikasi
> 
> Mengubah current version bukan solusi utk diterapkan (itu hanya cara pelaksana supaya dapat membantu secara praktis). Solusinya yg diperlukan adalah mampu deteksi versi secara akurat. Dan juga perhatikan bahwa migrasi tergantung juga versi database.  

Cara ini juga kami (pelaksana) dapatkan Dari programmer, yang kami minta pendapat untuk penyelesaian tercepat terhadap masalah tersebut.
