### ISSUE TITLE
Bug/error: gelar penandatangan surat tidak muncul pada permohonan dan arsip surat

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#5847]
### Jelaskan error yg dialami

gelar depan dan belakang penandatangan surat tidak muncul pada permohonan dan arsip surat
<img width="1144" alt="Screen Shot 2022-10-20 at 10 12 09" src="https://user-images.githubusercontent.com/36557759/196848002-d72b0aeb-27d5-4866-a15d-37297e95425c.png">

<img width="1165" alt="Screen Shot 2022-10-20 at 10 13 11" src="https://user-images.githubusercontent.com/36557759/196848007-dba21929-55cc-4f11-8716-9c24387ea23e.png">

<img width="1118" alt="Screen Shot 2022-10-20 at 10 13 52" src="https://user-images.githubusercontent.com/36557759/196848035-2be05117-dbb2-4b0a-b74c-f3ca0640e343.png">

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.10-premium-rev02

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1513
