### ISSUE TITLE
Bug/error: file pdf hasil cetak surat tinymce tidak sesuai

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#5849]
### Jelaskan error yg dialami

![image](https://user-images.githubusercontent.com/36557759/196850043-b085f5ad-05cf-424b-9044-06e7d45169bf.png)

![image](https://user-images.githubusercontent.com/36557759/196850078-fc102ec3-3e31-4ede-98c0-94bbbe158c5b.png)

dari kedua 2 screenshot di atas, hasil pdf saat cetak surat tidak sesuai

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.10-premium-rev02

**Comment by andifahruddinakas** [comment]
Sudah ditambahkan tools paragraf menjorok di PR https://github.com/OpenSID/premium/pull/1436
