### ISSUE TITLE
Bug/error: error import SISKEUDES karena tidak ada kolom F12

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#5850]
### Jelaskan error yg dialami

![image](https://user-images.githubusercontent.com/36557759/196854263-52bdc8e1-7225-4ab4-9302-eab0019e5ccc.png)

pada table keuangan_ta_spp belum ada kolom F12, F13 dan F14 yang menyebabkan error pada saat import data

karena pada file excel ada kolom sesuai gambar di bawah

![image](https://user-images.githubusercontent.com/36557759/196854538-6a8b602e-8339-4f3e-b48d-bd857a5d6dd3.png)

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

tambahkan kolom F12, F13 dan F14 pada table keuangan_ta_spp

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.10-premium-rev02

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1511
