### ISSUE TITLE
Bug/error: error import data responden di menu analisis

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#5851]
### Jelaskan error yg dialami

error pada saat mengimport data responden di menu analisis

<img width="551" alt="Screen Shot 2022-10-20 at 15 27 37" src="https://user-images.githubusercontent.com/36557759/196897622-8680e35f-dba3-4550-a3c2-38b8b9a7f48d.png">

### Cara untuk mereplikasi errornya

- klik menu Analisis
- klik menu Master Analisis
- klik tombol Rincian Analisis
<img width="500" alt="Screen Shot 2022-10-20 at 15 30 50" src="https://user-images.githubusercontent.com/36557759/196898381-2a623e36-1292-472a-af74-8b1fa767ad54.png">
- klik menu Input Data Sensus / Survei
<img width="634" alt="Screen Shot 2022-10-20 at 15 32 03" src="https://user-images.githubusercontent.com/36557759/196898549-428d7008-921e-4896-a9e1-7923e3e8f710.png">
- unduh data responden
- update data responden di file excel
- Impor file excel tersebut
- setelah itu muncul error
<img width="551" alt="Screen Shot 2022-10-20 at 15 27 37" src="https://user-images.githubusercontent.com/36557759/196897622-8680e35f-dba3-4550-a3c2-38b8b9a7f48d.png">

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.10-premium-rev02

**Comment by mranca** [comment]
mantap semoga issue  ini bisa selesai secepatnya

**Comment by apidong** [comment]
ini disebabkan karena cara membuat file excel menggunakan cara file html yang dirubah formatnya menjadi xls. sehingga saat melakukan import, file tsb masih terbaca sebagai html dan datanya tidak bisa terbaca.
untuk cara mengatasinya, file yang sudah di download perlu di file save as ke format .xls setelah itu baru  bisa di import.

pak @vickyrolanda bagaimana kalau generate untuk file unduh dirubah menjadi .xlsx menggunakan php spreadsheet?

**Comment by mranca** [comment]
Sudah pak kami lakukan seperti itu pak namun hasilnya tetap sama

**Comment by mranca** [comment]
Ok silahkan di close pak saya sudah coba dan berhasil tenyata filenya harus di simpan dengan format xls. Bukan xlsx

**Comment by vickyrolanda** [comment]
solusi dari mas @apidong perlu kita terapkan juga maka saya buat issue untuk menjadi perubahan pada fitur analisis https://github.com/OpenSID/OpenSID/issues/5859
