### ISSUE TITLE
Gunakan slug untuk identifikasi modul

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#5854]
Saat ini jika membuat modul menggunakan id sebagai parameter. Terkadang ada tumpang tindih jika dalam 1 waktu perkerjaan membuat modul dengan id yang sama. Sehingga tiap kali PR modul baru di gabungkan ke rilis-dev maka PR lain yang menambahkan modul harus mengganti id nya agar tidak sama.

Hal tersebut membuat pekerjaan tidak efisien.

Solusi : 
- [ ] Tambahkan kolom slug pada tabel setting_modul
- [ ] Pengenalan navigasi menggunakan slug
- [ ] Penambahan modul dengan slug yang ditentukan, bukan menggunakan id
- [ ] Lainnya

**Comment by andifahruddinakas** [comment]
Mas @vickyrolanda, ini diperlukan sebelum mengerjakan issue https://github.com/OpenSID/OpenSID/issues/6351

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/2068
