### ISSUE TITLE
Permintaan fitur: Buat tombol untuk aktifkan dan nonaktifkan fungsi hapus_cache_untuk_semua('status_langganan')

### ISSUE THREAD

**Issue by FirlianiF** [OpenSID/OpenSID#5863]
### Apa kekurangan yg ingin diatasi?

Untuk desa yang mengalami token kosong, saat cache ditambah manual, lalu fungsi hapus cache berjalan otomatis yang mengakibatkan cache yang ditambahkan terhapus kembali.

### Jelaskan solusi yg diinginkan

Buat tombol pengaturam untuk aktifkan dan nonaktifkan fungsi hapus_cache_untuk_semua('status_langganan')

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

-

**Comment by apidong** [comment]
@vickyrolanda mohon untuk di analisis terlebih dahulu pak, karena cache memiliki memiliki kadaluarsa. apa bisa dan perlu di buat  menjadi lebih lama.

**Comment by vickyrolanda** [comment]
mas @apidong sebaiknya jngn dibaut semakin lama , pertama kta harus selesaikan terkait masalah token ini sehingga tombol ini menajadi tidak perlu kita terapkan .

**Comment by vickyrolanda** [comment]
Issue ini sy close karena sudah ada solusinya terkait token.
