### ISSUE TITLE
Bug/error: update dokumen penduduk

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#5866]
### Jelaskan error yg dialami

terjadi error saat update dokumen penduduk, saat di klik unduh menjadi blank page
sebelum di update, saat di klik unduh dokumen berhasil di unduh

<img width="1440" alt="Screen Shot 2022-10-26 at 15 05 57" src="https://user-images.githubusercontent.com/36557759/197970332-6df481de-a3e4-4390-a468-3ea0af74ecdc.png">

### Cara untuk mereplikasi errornya

- klik menu Kependudukan
- klik menu Penduduk
- klik Lihat Detail Biodata Penduduk
- klik Manajemen Dokumen

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.10-premium-rev02

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1541
