### ISSUE TITLE
Permintaan fitur: Menampilkan Kembali Opsi Hapus Arsip pada Layanan Surat

### ISSUE THREAD

**Issue by SyahrulAsun** [OpenSID/OpenSID#5867]
### Apa kekurangan yg ingin diatasi?

Pengembalian Opsi Hapus Arsip pada Layanan SUrat

### Jelaskan solusi yg diinginkan

Hapus Arsip pada layanan surat bisa muncul kembali

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

22.10-premium-rev02

### Informasi tambahan

.

**Comment by andifahruddinakas** [comment]
Hapus arsip layanan surat bisa dilakukan jika sudah menyesuaikan config berikut : 
```
// Setting ini untuk menentukan user yang dipercaya. User dengan id di setting ini
// dapat membuat artikel berisi video yang aktif ditampilkan di Web.
// Misalnya, ganti dengan id = 1 jika ingin membuat pengguna admin sebagai pengguna terpecaya.
$config['user_admin'] = 0;
```
