### ISSUE TITLE
Fitur/Bug: Amankan Token Pengguna Ketika Restore Database

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#5870]
### Jelaskan error yg dialami

Pengguna localhost mendaftar sebagai pelanggan fitur premium, hosting dll.
Setelah diinstall dan masukkan token, pengguna melakukan restore database dari hasil backup sebelumnya.

Error terjadi karena token terhapus akibat restore database yang semula tidak bertoken (localhost)

### Cara untuk mereplikasi errornya

1. Lakukan install OpenSID baru, masukkan token dan sesuaikan identitas desa.

2. laukan restore database yang belum memiliki token.

### Hasil yg diharapkan

Khusus kolom token, apakah bisa diamankan pada saat proses restore database. sehingga token tidak perlu input ulang ketika restore selesai.

pengguna yang lakukan restore database, tetap bisa gunakan opensid dalam keadaan halaman Layanan Pelanggan dalam keadaan terisi informasi terbaru di Layanan.

### Tangkapan layar dan log error

tidak ada

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Semua

**Comment by vickyrolanda** [comment]
Mungkin sebaiknya di buat Opsi seperti ini ya pak agar bisa di hapus & bisa juga tidak. 
<img width="725" alt="image" src="https://user-images.githubusercontent.com/59082428/198820300-ce21f2d6-950f-44a9-982d-bff72a806a28.png">

**Comment by andifahruddinakas** [comment]
Diperlukan untuk mempercepat proses peralihan dari database pengguna umum (yg tdk memliki token) ke premium

**Comment by FirlianiF** [comment]
mas @andifahruddinakas dari PR di issue ini apa ada yg harus saya perbaiki?

**Comment by andifahruddinakas** [comment]
> mas @andifahruddinakas dari PR di issue ini apa ada yg harus saya perbaiki?

menunggu issue lain.

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2358
