### ISSUE TITLE
Tidak bisa menambahkan kepala rumah tangga

### ISSUE THREAD

**Issue by mranca** [OpenSID/OpenSID#5872]
### Jelaskan error yg dialami

Pada saat ingin menambahkan kepala keluarga menjadi kepala rumah tangga tidak bisa akan tetapi jika istrinya bisa tampil pada list pencarian

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

22.10 rev 02

### Tema Yang Digunakan

-

### Informasi tambahan

-

**Comment by vickyrolanda** [comment]
sesuai pada pertemuan kemaren issue ini sudah di jelaskan dan sudah di perbaikin dan bisa di uji coba melalui berputar.opendesa.id  sementara saya close issue ini jika nanti memang terjadi dan ada alasan tersendiri maka silahkan di open lagi ya pak @mranca 
<img width="667" alt="image" src="https://user-images.githubusercontent.com/59082428/198506463-2c64ccc3-167e-48c0-8bf0-6862f3746019.png">

**Comment by mranca** [comment]
baik pak
