### ISSUE TITLE
Perlu di check untuk versi Beta menggunakan data desa nataraya

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#5873]
- [ ] Ketika upgrade error 505 
- [ ] pada saat di reload maka normal 
- [ ] surat menjadi kosong sebelum di jalankan migrasinya ketika jalankan migrasi maka kembali lagi

**Comment by vickyrolanda** [comment]
mas @devrakapriyo mohon bantu check lgi , karena saya testing tidak terjadi seperti diatas.

**Comment by devrakapriyo** [comment]
setelah di cek tidak terjadi error seperti di atas, untuk sementara issue di close
