### ISSUE TITLE
Perbedaan laporan log bulanan keluarga DB Nataraya

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#5874]
Trigernya karena ada ID peristiwa 5 pada log_pristiwa.
Data menjadi salah ketika laporan bulanan.
<img width="493" alt="image" src="https://user-images.githubusercontent.com/59082428/198234306-01742e0d-7f3f-42e4-8ce2-9a8a9f2e0588.png">
<img width="287" alt="image" src="https://user-images.githubusercontent.com/59082428/198234680-af80f5c1-a10c-4826-a1f2-c643953a8525.png">

Keterangan : 
Penduduk tidak tetap
riwayatnya pernah keluar dan pernah masuk kembali

Pertanyaan kenapa id peristiwa 5 tidak masuk pada laporan bulanan

**Comment by vickyrolanda** [comment]
mas @andifahruddinakas ini kemaren gmna penjelasannya mas.

**Comment by vickyrolanda** [comment]
bug ini perlu di diskusikan terkait perubahan data pindah penduduk masuk kembali di bulan yang sama,

**Comment by vickyrolanda** [comment]
setelah saya testing kembali ada kondisi yang membingungkan karena tombol datang kembali : 
1. Jika di bulan yang sama maka sebaikan tombol datang kembali tidak aktif 
2. Jika di bulan yang sama maka sebaikan tombol kembalikan status yang aktif
3. jika perubahan akan dilakukan dengan data penduduk pindah bulan lalu maka tombol datang kembali yang aktif
4. jika perubahan akan dilakukan dengan data penduduk pindah bulan lalu maka tombol kembalikan status tidak aktif
--------

terjadi log bulanan yang membingungkan jika sudah pindah dan datang kembali di bulan yang sama menjadi double log penduduk jika klik tombol datang kembali tidak aktif, sedangkan jika kembalikan status maka log akan menjadi sesuai, dengan kondisi tersebut bisa di lakukan kondisi di atas.

**Comment by eddieridwan** [comment]
@vickyrolanda bahas bersama @andifahruddinakas . **Pastikan dicatat secara jelas dan lengkap aturannya di panduan.**

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1667 

mas @devrakapriyo mohon ditambahkan di catatan penduan ya mas bahwa penduduk yang status dasarnya sudah berubah pada bulan ini maka tidak dapat diubah menjadi datang kembali. tpi untuk status dasar yg sudah lebih dari 1 bulan maka baru bisa di ubah menjadi penduduk yang datang kembali.
