### ISSUE TITLE
Tombol UB menjadi disable kembali ketika upgrade ke rev03

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#5875]
Sebelumnya ter enable namun ketika upgrade kembali ke disable sehingga harus di enablekan kembali
<img width="265" alt="image" src="https://user-images.githubusercontent.com/59082428/198235219-3a093317-52b7-4193-96e4-5a4af652d618.png">

**Comment by ariandii** [comment]
Koreksi:
ketika update calon 22.11-premium (rilis dev)

**Comment by vickyrolanda** [comment]
> Koreksi: ketika update calon 22.11-premium (rilis dev)

saya sudah replikasi pak dari 22.10-premium-rev03 ke 22.10-premium-beta 3 tidak menemukan perubahan di UB pak. mungkin bisa saya tes dengan DB nata raya pak.

**Comment by vickyrolanda** [comment]
Mas @devrakapriyo bsa bantu testing ini lgi soalnya sudah 2 kali sy testing dengan database yt berbeda tidak terjadi perubahan seperti issue, mas akas juga coba tdk terjadi. Bsa mas raka testing mana tau ketemu issuenya.
