### ISSUE TITLE
Info Sistem Perlu ditambahkan informasi Minimal

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#5876]
Butuh ditambahkan informasi minimal berapa agar taau batasannya supaya icon menjadi hijau
<img width="432" alt="image" src="https://user-images.githubusercontent.com/59082428/198236623-098b9540-eafb-47e3-87de-cd70951a7b2e.png">

**Comment by agungsugiarto** [comment]
mas @vickyrolanda bisa lebih spesifik penjelasannya?

**Comment by devrakapriyo** [comment]
> mas @vickyrolanda bisa lebih spesifik penjelasannya?

ini mas @agungsugiarto jadi masing masing kebutuhan sistem, perlu di tambahkan label penjelasan informasi minimum, contohnya

<img width="510" alt="Screen Shot 2022-10-28 at 15 08 29" src="https://user-images.githubusercontent.com/36557759/198537791-2824fd22-764d-48c2-bd66-ad38b427cc7b.png">

**Comment by devrakapriyo** [comment]
<img width="432" alt="198236623-098b9540-eafb-47e3-87de-cd70951a7b2e" src="https://user-images.githubusercontent.com/36557759/198538770-3c0d41de-f27e-48e7-8690-4ffbf38729ad.png">
