### ISSUE TITLE
Bug Wilayah Administratif kolom KK menjadi kosong

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#5877]
<img width="392" alt="image" src="https://user-images.githubusercontent.com/59082428/198238705-9071f4fb-b16d-48c8-8ad2-f4e0abd187ae.png">

**Comment by ariandii** [comment]
Walaupun angka 0, namun jika angka 0 diklik pada kolom KK tersebut, hasilnya menampilkan daftar KK lengkap.

Sehingga seharusnya tidak 0.

**Comment by devrakapriyo** [comment]
<img width="1440" alt="Screen Shot 2022-10-27 at 15 37 29" src="https://user-images.githubusercontent.com/36557759/198536553-d1cd233d-fdbc-496e-8af7-53661c1b750f.png">


data tersebut tidak balanace jika id_peristiwa di KK tersebut berisikan nilai 5, sedangkan jika berisikan nilai 0 maka data menjadi balance

**Comment by vickyrolanda** [comment]
mas @andifahruddinakas bisa  sesuikan bagian kollom RW sebaiknya dibuat gk usah bisa di klik aja karena datanya kan dia sudah di kolom KK dll. sedang kan RW & RT samakan sja tidak bisa di klik biar tidak menjadi ambigu, saat ini RW ktika di klik mengarah ke sub_rw.

**Comment by vickyrolanda** [comment]
Mas @agungsugiarto bisa bantu ini mas.

**Comment by agungsugiarto** [comment]
Saya kurang jelas dengan maksud issuenya, bisa di discord mas @vickyrolanda

**Comment by agungsugiarto** [comment]
Mas @vickyrolanda mas @devrakapriyo bisa dibantu, melihat apakah `id_cluster` di table `tweb_penduduk` kepala kk tersebut tidak ada valuenya?

**Comment by vickyrolanda** [comment]
mas @agungsugiarto sebenarnya ini buat perbuahan biasa aja mas hilangkan link yang di kollom RW mas.

**Comment by vickyrolanda** [comment]
> Mas @vickyrolanda mas @devrakapriyo bisa dibantu, melihat apakah `id_cluster` di table `tweb_penduduk` kepala kk tersebut tidak ada valuenya?

maaf mas setelah saya coba lagi ternyata bagian yang tidak mas seperti ini mas,  misalkan bagian dusun MANGSIT Jumlah KK yg tertulis 6:
<img width="775" alt="image" src="https://user-images.githubusercontent.com/59082428/199045205-eaa2aab1-24f3-4ebc-9f47-76c9eed6637f.png">
**namun yang tampil 7 , 1 tidak terhitung karena tidak ada anggota kerluarga**
<img width="722" alt="image" src="https://user-images.githubusercontent.com/59082428/199045548-35ca4ccb-1937-4d72-b6ce-0bd5cf9fb299.png">

Harusnya bagian KK yang tidak ada anggota keluarga tetap terhitung karena ada no KKnya dan terhitung sudah ada kkanya walaupun hanya kepala keluarga saja.

**Comment by ariandii** [comment]
@vickyrolanda di gambar saya paling atas, malah KK 0 :)

**Comment by vickyrolanda** [comment]
> @vickyrolanda di gambar saya paling atas, malah KK 0 :)

ia pak, sy belum ada coba dengan database yg di atas pak jdi belum tau statusnya knpa kosong begitu pak, perlu ditelusurin emang ini pak dengan database pak ariandi.
kalo saya pakai database pak ariandi yang acak saya daptin seperti ini pak : 
<img width="802" alt="image" src="https://user-images.githubusercontent.com/59082428/199078610-4cd2ad6a-bf5b-4674-a84a-eb7f043f8376.png">

**Comment by ariandii** [comment]
itu jelas terlihat mutih kulon. bukan database milik natairaya.

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki di PR https://github.com/OpenSID/premium/pull/1563

Solusi : 
- Buat ulang view keluarga_aktif
