### ISSUE TITLE
Photo artikel menjadi blank hitam sebagian

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#5878]
Setiap photo yang di upload ke artikel maka photo akan ada blank hitam sebgian.
<img width="302" alt="image" src="https://user-images.githubusercontent.com/59082428/198238259-c393a988-066e-4c39-8eea-f2edcd2dea7f.png">

**Comment by devrakapriyo** [comment]
setelah saya cek di beta.opendesa.id pada saat upload photo pada artikel normal
sementara issue ini di close

**Comment by andifahruddinakas** [comment]
Duplicate issue https://github.com/OpenSID/OpenSID/issues/5912
