### ISSUE TITLE
Security: ganti md5 untuk pasword dengan enkripsi lain

### ISSUE THREAD

**Issue by telo99** [OpenSID/OpenSID#588]
Sudah banyak situs yang memberikan fasilitas decrypt md5. Alangkah baiknya jika menggunakan enkripsi lain, password_hash misalnya. (http://php.net/manual/en/function.password-hash.php)
(https://masrud.com/post/password-hash-password-verify)

Salah satu situs database md5: https://hashkiller.co.uk/md5-decrypter.aspx
![md5](https://user-images.githubusercontent.com/30897391/29562635-56a0f49e-8764-11e7-9db6-0a1600ebf9ad.jpg)

**Comment by hadyanwijaya** [comment]
bisa diusulkan menggunakan ion_auth yang menggunakan bcrypt

**Comment by eddieridwan** [comment]
Berikut ini salinan comment dari PR #875:

1. Setuju, sebaiknya issue #588 dikerjakan untuk mengurangi celah keamanan OpenSID. Mengenai versi PHP, pendapat kami tidak apa2 kalau kita batasi support hanya pada v5.3.7 ke atas. Apalagi kalau terkait keamanan. Kami akan senang sekali apabila anda sempat menulis ulang PR anda menggunakan library yang lebih umum digunakan. Mungkin gunakan https://github.com/ircmaxell/password_compat? ion_auth sepertinya agak berat dan memerlukan perombakan yg lebih mendasar. Tapi silakan bahas di #588 -- mungkin ada teman2 yg lain yg juga ingin komentar.
2. Masalah migrasi password user mudah2an akan tidak terlalu berat, karena mudah2an jumlah user di instalasi desa tidak akan terlalu banyak. Tetapi tantangannya adalah banyaknya versi OpenSID yang masih digunakan, dan desa tidak tentu kapan akan upgrade ke versi yg ada bcrypt. Salah satu strategi yang mungkin bisa diterapkan:
    1. user login menggunakan passwordnya, untuk pertama kali saja verifikasi menggunakan md5 yang lama (bisa cek menggunakan kolom tambahan untuk status passwordnya -- atau bisa cek dari panjang password yg di-enkripsi, yang berbeda untuk md5[32 digit]/bcrypt[> 32 digit])
    2. otomatis simpan passwordnya dalam format bcrypt
    3. seterusnya verifikasi menggunakan bcrypt (versi md5 dihapus)
3. Coding style di OpenSID saat ini sangat tidak konsisten, dan sering menyulitkan yg melakukan perubahan. Jadi kita perlu mulai untuk menerapkan praktek yang lebih baik. Setiap kali kita menambah file atau mengubah yang sudah ada, sebaiknya kita gunakan coding style standar, dalam hal ini PSR-2.

**Comment by eddieridwan** [comment]
Sdh dicommit ke master melalui PR #882
