### ISSUE TITLE
Data penduduk tidak terdata karena ketika input jaringan bermasalah 

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#5881]
Total data penduduk dengan total  di wilayah administratif tidak sama.

**Comment by devrakapriyo** [comment]
terlampir database tongketongke.desa.id di link gdrive OpenDesa

https://drive.google.com/drive/folders/1FgKY0GeZq9W1NZBxhp3bbSBMM1SBpDfY?usp=sharing

**Comment by vickyrolanda** [comment]
mas @andifahruddinakas , kejadian ini jarang terjadi dan sebenarnya solusinya tinggal hapus data yang tidak valid. namun dari pengguna tidak tau mana yg mau di hapus sehingga karena ada data yang tidak valid jdi membuat datanya jdi tidak sama dilaporannya data wilaya administratif. 

saya tidak bisa check dengan database di atas karena setiap masuk ke halaman data wilayah administratif error 505 dan lognya sepert ini : 
ERROR - 2022-10-30 15:03:53 --> Query error: The user specified as a definer ('tong_ketongke'@'localhost') does not exist - Invalid query: SELECT u.*, a.nama AS nama_kadus, a.nik AS nik_kadus,
		(SELECT COUNT(rw.id) FROM tweb_wil_clusterdesa rw WHERE dusun = u.dusun AND rw <> '-' AND rt = '-') AS jumlah_rw,
		(SELECT COUNT(v.id) FROM tweb_wil_clusterdesa v WHERE dusun = u.dusun AND v.rt <> '0' AND v.rt <> '-') AS jumlah_rt,
		(SELECT COUNT(p.id) FROM penduduk_hidup p WHERE p.id_cluster IN(SELECT id FROM tweb_wil_clusterdesa WHERE dusun = u.dusun)) AS jumlah_warga,
		(SELECT COUNT(p.id) FROM penduduk_hidup p WHERE p.id_cluster IN(SELECT id FROM tweb_wil_clusterdesa WHERE dusun = u.dusun) AND p.sex = 1) AS jumlah_warga_l,
		(SELECT COUNT(p.id) FROM penduduk_hidup p WHERE p.id_cluster IN(SELECT id FROM tweb_wil_clusterdesa WHERE dusun = u.dusun) AND p.sex = 2) AS jumlah_warga_p,
		(SELECT COUNT(p.id) FROM keluarga_aktif k inner join penduduk_hidup p ON k.nik_kepala = p.id  WHERE p.id_cluster IN(SELECT id FROM tweb_wil_clusterdesa WHERE dusun = u.dusun) AND p.kk_level = 1) AS jumlah_kk  FROM tweb_wil_clusterdesa u
			LEFT JOIN penduduk_hidup a ON u.id_kepala = a.id
			WHERE u.rt = '0' AND u.rw = '0'  ORDER BY`u`.`urut` ASC LIMIT 0,20

**Comment by andifahruddinakas** [comment]
Untuk backup, bisa arahkan desa menggunakan backup dari aplikasi agar difiner di view tidak ikut.

Itu tinggal ganti aja difiner pd view jadi localhost

**Comment by apidong** [comment]
bagaimana kalau di buat truncate saja saat menyimpan. jadi kalau data gagal di simpan karena error (entah jaringan atau sebab lain), data akan ke roolback

**Comment by vickyrolanda** [comment]
> bagaimana kalau di buat truncate saja saat menyimpan. jadi kalau data gagal di simpan karena error (entah jaringan atau sebab lain), data akan ke roolback

Bsa jga itu mas tpi untuk case yg sudah terjadi seperti di atas gmna mas apa bsa di bersihkan?

**Comment by vickyrolanda** [comment]
mas @apidong ini saya ubah menjadi teknis karena menambahkan truncate untuk proses tambah data.

**Comment by mranca** [comment]
@vickyrolanda kalau bisa di tunjukan tabel sama idnya di phpmyadmin mas, bagaimana kalau saya langsung hapus saja??

**Comment by mranca** [comment]
karena yang bermasalah disini id perempuan yang saya input pas jaringan tidak stabil terjadi demikian datanya masuk tapi tidak terhitung jumlahnya di wilayah administratif desa

**Comment by vickyrolanda** [comment]
> @vickyrolanda kalau bisa di tunjukan tabel sama idnya di phpmyadmin mas, bagaimana kalau saya langsung hapus saja??

sy akan lihat relasinya kemana saja terlebih dahulu ya pak sebelum bpk lakukan itu pak.

**Comment by mranca** [comment]
@vickyrolanda baik pak

**Comment by vickyrolanda** [comment]
pak @mranca apakah masalah ini sudah teratasi?

**Comment by mranca** [comment]
Pak @vickyrolanda , masih menunggu bantuan

**Comment by vickyrolanda** [comment]
> Pak @vickyrolanda , masih menunggu bantuan

pak silahkan bisa melalui telegram saya ya pak bisa @vickyrolanda

**Comment by mranca** [comment]
Bagaimana pak apakah filenya di kirimkan atau di kirimkan solusinya ??
