### ISSUE TITLE
Tidak bisa reset pin layanan mandiri.

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#5882]
<img width="799" alt="image" src="https://user-images.githubusercontent.com/59082428/198249588-2c31cf9b-6aba-48b4-8060-12447c7da44b.png">

**Comment by andifahruddinakas** [comment]
// Data id penduduk dan pin layanan mandiri yang digunakan sebagai default akun demo
```
$config['demo_akun'] = [
    1 => '123456',
    2 => '234561',
    3 => '345612',
];

```
Akun demo (data penduduk) tidak dapat di hapus jika website di atur sebagai website demo.
