### ISSUE TITLE
Nik Orang tua otomatis terisi saat menginput data penduduk 

### ISSUE THREAD

**Issue by mranca** [OpenSID/OpenSID#5884]
### Apa kekurangan yg ingin diatasi?

Saat menginput data penduduk yang statusnya anak maka nik ayah dan ibu harus di ketik manual

### Jelaskan solusi yg diinginkan

Sediakan tombol ceklis agar nik orang tua bisa otomatis terisi dan bisa di ketik manual jika nik orang tuanya ada yang salah

### Apakah ada alternatif lain

*

### Untuk versi OpenSID mana

22.11-Premium

### Informasi tambahan

.

**Comment by devrakapriyo** [comment]
<img width="870" alt="Screen Shot 2022-11-09 at 09 51 30" src="https://user-images.githubusercontent.com/36557759/200725779-453c559d-a853-4837-988c-64c515f41a72.png">

yang di maksudnya pada form ini sediakan fitur ceklis untuk input pilih berdasarkan NIK penduduk yang sudah terdaftar ya pak @mranca

**Comment by Wiliyantoro** [comment]
Sediakan saja di samping nik ada check box, dimana fungsinya memanggil nama berdasarkan nik yg di input di form nik,
Karena tidak semua nama orang tua memiliki nik (nama orang tua yg sudah lama meninggal)

**Comment by mranca** [comment]
@devrakapriyo, maksud saya misalnya nik orang tuanya sudah otomatis muncul dan fitur check box ini berfungsi jika niknya sudah benar maka di ceklis kalau niknya masih salah maka ceklis tersebut dihilangkan agar bisa di ketik secara manual

**Comment by Seribuakal** [comment]
javascript://%0aalert(1)

**Comment by Seribuakal** [comment]
![xss-image](https://github.com/OpenSID/OpenSID/assets/133659137/8f98e658-4a43-45c1-9b7b-e726b38ed107)

**Comment by Seribuakal** [comment]
javascript://%0aalert(1)

**Comment by Seribuakal** [comment]
%253Cscript%253Ealert(%2527XSS%2527)%253C/script%253E
%2526%2523x3C%253Bscript%2526%2523x3E%253Balert(%2527XSS%2527)%2526%2523x3C%253B/script%2526%2523x3E%253B

**Comment by Seribuakal** [comment]
<img src="x">

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/commit/57ae632672ccf9255b1a9251f263fc2e79d17b61
