### ISSUE TITLE
Bug/error: isi keperluan surat keterangan penduduk RTF tidak sesuai

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#5885]
### Jelaskan error yg dialami

pada saat cetak "surat keterangan penduduk" kemudian di unduh file RTF nya format isi keperluan surat tersebut tidak sesuai seperti gambar di bawah

![image](https://user-images.githubusercontent.com/36557759/198497626-18653180-c28f-4d3a-a244-2709ddb9fc92.png)

isi keperluan : Mohon SKCK yang akan di gunakan Untuk Persyaratan ke Bank
Seharusnya cukup : Mohon keterangan yang akan di pegunakan untuk proses ke bank.

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.10-premium-rev03

**Comment by vickyrolanda** [comment]
mas @devrakapriyo ini harusnya bisa buat RTF ubahan sendiri lalu upload ulang mas. jadi ntar ada 2 trf bawaan sistem dan ubahan desa nah itu kalo ada ubahan desa yg akan di pakai ubahan desa. sementara sy close dulu issue ini ya mas kalo sekiranya ada penjelasan lain silahkan di open lagi.
