### ISSUE TITLE
Double: Akta perceraian pada table di menu profil Layanan Mandiri

### ISSUE THREAD

**Issue by syahransaputra** [OpenSID/OpenSID#5886]
### Jelaskan error yg dialami

Ditable Biodata Penduduk pada bagian DATA PERKAWINAN terdapat dua baris Akta perceraian

### Cara untuk mereplikasi errornya

1. Login di menu Layanan Mandiri (dengan penduduk yg status Pernikahan Cerai Hidup)
2. Ke menu Profil
3. Gulir ke pada baris tabel DATA PERKAWINAN
4. terdapat 2 baris Akta perceraian

### Hasil yg diharapkan

Seharusnya Akta perceraian kemudian Tanggal perceraian

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

umum maupun premium

### Tema Yang Digunakan

-

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1543
