### ISSUE TITLE
Bug/error: tinymce template salinan surat dan header mepet saat di cetak

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#5888]
### Jelaskan error yg dialami

<img width="1440" alt="Screen Shot 2022-10-29 at 07 31 53" src="https://user-images.githubusercontent.com/36557759/198753842-a20c2363-59b1-4819-ad85-190c3b1decab.png">

semua salinan surat saat di cetak menjadi mepet seperti gambar di atas

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.11-beta

**Comment by andifahruddinakas** [comment]
Disesuaikan sendiri di pengaturan surat, tinggi header. Bisa buatkan panduannya mas @devrakapriyo.

**Comment by vickyrolanda** [comment]
> Disesuaikan sendiri di pengaturan surat, tinggi header. Bisa buatkan panduannya mas @devrakapriyo.

iya betul, kalo begitu issue ini saya close ya mas @devrakapriyo .
