### ISSUE TITLE
Bug/error: tinymce kode isian masih berupa variable saat cetak surat

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#5889]
### Jelaskan error yg dialami

salinan surat tinymce surat pengantar laporan kehilangan
<img width="655" alt="Screen Shot 2022-10-29 at 07 31 53" src="https://user-images.githubusercontent.com/36557759/198754182-7439f876-0c57-400b-80cc-d640a84927e2.png">

salinan surat tinymce surat pengantar laporan kehilangan
<img width="745" alt="Screen Shot 2022-10-29 at 07 43 10" src="https://user-images.githubusercontent.com/36557759/198754191-48095f82-e27f-4c2a-8811-a6ee9e78e296.png">

salinan surat tinymce surat keterangan usaha
<img width="691" alt="Screen Shot 2022-10-29 at 07 44 48" src="https://user-images.githubusercontent.com/36557759/198754196-0dc2bdaa-4151-4f3e-aba1-3929d5978460.png">

dari beberapa salinan surat TinyMCE beberapa kode isian masih berupa variable saat di cetak

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.11-beta

**Comment by vickyrolanda** [comment]
kondisi ini pada saat : preview surat di pengaturan surat. 
jika di cetak hanya 1 kode isian yang tidak terganti : 
<img width="740" alt="image" src="https://user-images.githubusercontent.com/59082428/198813314-04f3f668-4946-4e95-9bd5-d5fdc2462f29.png">

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1545
