### ISSUE TITLE
CETAK KK 

### ISSUE THREAD

**Issue by iwanfausi** [OpenSID/OpenSID#589]
KALAU BISA DI PENULISAN ALAMAT, TIDAK DISERTAI DENGAN TEXT DUSUN
layaknya di SID 3.04

**Comment by iwanfausi** [comment]
![gethub](https://user-images.githubusercontent.com/30854572/29599585-f011d3dc-87fa-11e7-83f4-eade445cfc8f.jpg)

**Comment by eddieridwan** [comment]
@iwanfausi Maksudnya, sebutan 'dusun' dihilangkan jika dusunnya tidak ada (kosong)?

**Comment by MUHAMMADRANGSEL** [comment]
Itu tergantung waktu pembuatan pengantar KK, di kartu keluarga yg kami lihat di lombok timur ada yg penulisan alamat seperti :
1. Jalan kampung Melati tanpa penulisan dusun
2. Dusun Masbagik Utara tanpa penulisan alamat

**Comment by iwanfausi** [comment]
tapi, kalau diwilayah kami dusun itu sebutannya kampung, dalam penulisan
alamat di kartu keluarga itu tertulis misalnya KP. Peleyan Utara, tanpa ada
tambahan Dusun KP. Peleyan Utara, cukup KP. Peleyan Utara. terima kasih
atas tanggapannya

2017-09-11 6:27 GMT+07:00 MUHAMMADRANGSEL <notifications@github.com>:

**Comment by iwanfausi** [comment]
Tulisan "Dusun"  apa bisa diganti "KP" yg berarti kampung!

**Comment by eddieridwan** [comment]
@iwanfausi , sebutan 'dusun' bisa diganti. Apakah sudah membaca setting aplikasi di https://github.com/eddieridwan/OpenSID/wiki/Panduan-Konfigurasi-Aplikasi (lihat sebutan_dusun). Rajin2 membaca panduan.

**Comment by iwanfausi** [comment]
Terima kasih mas edie ridwan

Pada tanggal 2 Okt 2017 3.26 PM, "Eddie Ridwan" <notifications@github.com>
menulis:
