### ISSUE TITLE
API SDGS berubah lagi di website https://sid.kemendesa.go.id/sdgs

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#5890]
API lama https://sid.kemendesa.go.id/sdgs untuk mendapakan data SDGS masih tersedia namun tidak update dan assetsnya sudah dihapus. (https://sdgsdev.kemendesa.go.id/SIDcutoff/goals?wilayah=7313120026)

Untuk API SDGS yang baru menggunakan format : 
https://sid.kemendesa.go.id/sdgs/searching/score-sdgs?province_code=62&city_code=6201&district_code=6201050&village_code=6201050016

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1547
