### ISSUE TITLE
Bug/error: Pengaturan Grup Pengguna [Operator]

### ISSUE THREAD

**Issue by syahransaputra** [OpenSID/OpenSID#5892]
### Jelaskan error yg dialami

Saat membuka menu Pengaturan Grup lalu klik Aksi lihat/icon mata pada grup **operator** maka page tidak tampil hanya loading saja. Setelah cek ke https://berputar.opendesa.id/ ternyata yg membuat loading lama itu terjadi karna looping terhadap modul **Layanan Pelanggan** dan **Pendaftaran Kerjasama** yang begitu banyak. 
**![Untitled](https://user-images.githubusercontent.com/26229332/198899077-2017ce57-f641-4bf1-9113-cc0afafc21a1.png)**

Saya coba cek di menu Layanan Pelanggan ternyata **Token tiba-tiba kosong** saya pikir ini penyebabnya ternyata setelah perbaharui token dan balik ke Pengaturan Grup dan klik lihat grup operator ternyata tidak menyelesaikan masalahnya page tetap loading dan tetap melakukan looping terhadap dua module tersebut diatas. 

### Cara untuk mereplikasi errornya

1. Pergi ke halaman Pengaturan > Pengguna
2. Klik Pengaturan Grup
3. Klik lihat/icon mata pada kolom aksi grup **operator** 

### Hasil yg diharapkan

Tidak terjadi looping yg berlebihan hingga membuat loading lama. 

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Versi 22.10-premium-rev03

### Tema Yang Digunakan

-

### Informasi tambahan

- Issue ini tidak terjadi pada https://demosid.opendesa.id/ dikarenakan ini hanya terjadi di premium
- ada keterkaitan dengan token yg kosong tiba-tiba dengan issue #5870 namun token kosong bukan dikarenakan restore database namun setelah update versi [Rilis v22.10-premium-rev02](https://github.com/OpenSID/rilis-premium/releases/tag/v22.10-premium-rev02) ke [Rilis v22.10-premium-rev03](https://github.com/OpenSID/rilis-premium/releases/tag/v22.10-premium-rev03)

**Comment by scqolbu24** [comment]
Pak @syahransaputra saya baru saja mencoba di https://berputar.opendesa.id/ dapat berjalan/tampil normal pak.

**Comment by scqolbu24** [comment]
solusi dari issue ini adalah lakukan migrasi database

**Comment by vickyrolanda** [comment]
untuk issue ini solusinya bisa di lakukan melakukan migrasi ulang ya mas @syahransaputra kalo begitu saya close terlebih dahulu issue ini mas jika terjadi lagi dan sekiranya bug silahkan di reopen.
