### ISSUE TITLE
Bug/error: Penambahan kolom pada ID Penerima Bantuan.

### ISSUE THREAD

**Issue by IkfanDjalaludin** [OpenSID/OpenSID#5894]
### Jelaskan error yg dialami

Penambahan kolom pada ID Penerima Bantuan, mengingat ID pada DTKS (Data Terpadu Kesejahteraan Sosial) sebanyak 36 Digit, sementara pada OpenSID hanya bisa memuat 29 Digit.

### Cara untuk mereplikasi errornya

1. Pergi kehalaman Program Bantuan
2. Tambahkan peserta penerima bantuan
3. Masukan ID Penerima Bantuan DTKS yang sesuai, dan simpan
4. Akan terjadi error (kembali pada tampilan login)

### Hasil yg diharapkan

Agar ID Penerima Bantuan DTKS bisa terinput ke OpenSID

### Tangkapan layar dan log error

<img width="960" alt="2022-10-31_09h04_37" src="https://user-images.githubusercontent.com/111027614/198911990-3888a533-c6c0-432c-9b84-d3374c256b3a.png">

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Rilis Premium v22.10.

### Tema Yang Digunakan

Tema Batuah

**Comment by IkfanDjalaludin** [comment]
Misalnya ID DTKS F324C4D9-AE4A-4EB4-A8DE-B9BEBDB56B82 sebanyak 36 Digit, hanya bisa diinput : DTKS F324C4D9-AE4A-4EB4-A8DE-B9BEBD sebanyak 29 Digit

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1548
