### ISSUE TITLE
Bug Penambahan Foto Produk diLapak

### ISSUE THREAD

**Issue by langonsari** [OpenSID/OpenSID#5895]
### Jelaskan error yg dialami

Pencarian Foto Produk saat menambahkan Foto Produk yg disetting lebih dari 5, Foto Produk ke-5 dan seterusnya tidak muncul sehingga tidak dapat menambahkan Foto Produk lagi.

![Screenshot_20221031_092611](https://user-images.githubusercontent.com/96863107/198919051-d66dd840-a4d9-46a4-98ba-9b993b5e7992.jpg)

### Cara untuk mereplikasi errornya

Dihalaman tambah Data Produk/aubah Produk tidak bisa menambahkan Foto Produk Ke-5 dan seterusnya,,

### Hasil yg diharapkan

Dapat menambahkan Foto Produk maksimal sesuai dengan dengan Jumlah maksimal di Settingan Lapak.

### Tangkapan layar dan log error

![Uploading Screenshot_20221031_092611.jpg…]()

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Versi 22.10-premium-rev03

### Tema Yang Digunakan

Denatra

**Comment by vickyrolanda** [comment]
mas @agungsugiarto untuk mereplikasi bugnya bisa masuk ke halaman : 
1. Lapak 
2. Pengaturan
3. Buat Banyak Foto Tiap Produk menjadi 5
4. Lalu Tambah Product
5. Maka photo ke 5 tidak bisa browse gambar

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1549
