### ISSUE TITLE
PENOMORAN/LOKASI BANGUNAN TEMPAT TINGGAL 

### ISSUE THREAD

**Issue by K4nzzz** [OpenSID/OpenSID#5896]
### Apa kekurangan yg ingin diatasi?

Lokasi dilakukan pada KK (kepala keluarga) dan anggota keluarga otomatis mengikuti.
Jangan satu-satu

### Jelaskan solusi yg diinginkan

Menambahkan fitur penomoran bangunan/lokasi bangunan

### Apakah ada alternatif lain

.

### Untuk versi OpenSID mana

22.11

### Informasi tambahan

.

**Comment by andifahruddinakas** [comment]
Duplicate of https://github.com/OpenSID/OpenSID/issues/5808
