### ISSUE TITLE
Tampilan SDGs

### ISSUE THREAD

**Issue by kbrozi** [OpenSID/OpenSID#5897]
### Jelaskan error yg dialami

Gambar SDGs tidak muncul ketika masuk di menu utama/info kampung/setatus kampung/sdgs

### Cara untuk mereplikasi errornya

1. Menu Utama
2. Info Kampung/Desa
3. Status Kampung/Desa
4. Tombol SDGs

### Hasil yg diharapkan

Gambar SDGs muncul kembali

### Tangkapan layar dan log error

![Uploading Screenshot_2022-10-31-13-22-49-22_40deb401b9ffe8e1df2f1cc5ba480b12.jpg…]()

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v21.11-premium

### Tema Yang Digunakan

DeNatra v8.0

### Informasi tambahan

Agar segera ketemu permasalahnya

**Comment by andifahruddinakas** [comment]
Duplicate issue https://github.com/OpenSID/OpenSID/issues/5890https://github.com/OpenSID/OpenSID/issues/5890
