### ISSUE TITLE
Error instal baru

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#5898]
Saat install baru terjadi error : 

![error 1](https://user-images.githubusercontent.com/57283157/198939447-a8796aeb-101c-4226-bc92-ad0c24aac2dd.jpg)
![error 2](https://user-images.githubusercontent.com/57283157/198939451-d968fd88-ea63-49b0-816f-a0a50f2093d1.jpg)

Lakukan pengecekan kolom tipe sebelum jalankan fungsi anjungan yg ada di MY_Controller (karena dijalankan di awal).

**Comment by andifahruddinakas** [comment]
Yg ini mas @yogiperdana

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1551
