### ISSUE TITLE
sediakan tombol hapus pada lampiran artikel

### ISSUE THREAD

**Issue by mranca** [OpenSID/OpenSID#5899]
### Apa kekurangan yg ingin diatasi?

kurangnya tombol hapus pada dokumen lampiran artikel

### Jelaskan solusi yg diinginkan

sediakan tombol hapus pada lampiran artikel karna terkadang lampiran itu sudah mau di ganti atau hapus

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

v22.11-Premium

### Informasi tambahan

-

**Comment by mah-mudi** [comment]
Sekaligus bug di rata kanan kiri paragraf, ketika di save, tampilan webnya rata kiri

![IMG_20221111_185902_696](https://user-images.githubusercontent.com/57661283/201350158-b09757aa-0ef7-4d0d-a9b6-aa9bce165271.jpg)
![IMG_20221111_185906_322](https://user-images.githubusercontent.com/57661283/201350162-12144533-e58d-408e-8fa8-34b3542794f5.jpg)

**Comment by mranca** [comment]
@mah-mudi di buatkan isssue terpisah pak

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1967
