### ISSUE TITLE
[Template Surat] Hilangkan "DAFTAR TANGGUNGAN" pada Surat Ket. Kurang Mampu untuk Penduduk Belum Kawin

### ISSUE THREAD

**Issue by sukrimalendra** [OpenSID/OpenSID#590]
Hilangkan "DAFTAR TANGGUNGAN" Penduduk Belum Kawin
![km](https://user-images.githubusercontent.com/30992964/29650371-435bc9da-88cd-11e7-8669-e42a30de1452.PNG)
Tetepkan untuk Penduduk yang sudah Kawin dan memiliki tanggungan

![km1](https://user-images.githubusercontent.com/30992964/29650437-848b8e68-88cd-11e7-9243-3b688e6a7341.PNG)

**Comment by eddieridwan** [comment]
Apakah SKTM diterbitkan untuk keluarga atau perorangan?

**Comment by sukrimalendra** [comment]
Perorangan pak

Pada tanggal 24 Agt 2017 3:59 PM, "Eddie Ridwan" <notifications@github.com>
menulis:

**Comment by MUHAMMADRANGSEL** [comment]
Kalau kami per keluarga bukan perorangan mungkin pak sukrimalendra perlu cek ulang masalah pmbuatan SKTM krn menurut pengalaman kami SKTM dibuat perkeluarga bkn perorangan

**Comment by sukrimalendra** [comment]
SKTM atau surat keterangan miskin juga diperlukan untuk perorangan pak.
Contohnya di desa kami diperlukan untuk persyaratan pengajuan BPJS untuk
ibu hamil dan persyaratan untuk mendaftar ke sekolah untuk calon siswa yang
tidak mampu.

Pada tanggal 17 Nov 2017 10:16 PM, "MUHAMMADRANGSEL" <
notifications@github.com> menulis:

**Comment by sukrimalendra** [comment]
Contoh suratnya :
1. Untuk ibu yang akan melahirkan 
[SKTM UNTUK IBU MELAHIRKAN.docx](https://github.com/OpenSID/OpenSID/files/1483333/SKTM.UNTUK.IBU.MELAHIRKAN.docx)
2. Untuk melanjutkan sekolah bagi siswa tidak mampu 
[SKTM UNTUK MELANJUTKAN SEKOLAH.docx](https://github.com/OpenSID/OpenSID/files/1483339/SKTM.UNTUK.MELANJUTKAN.SEKOLAH.docx)

**Comment by mizwaruddin** [comment]
SKTM umumnya digunakan untuk keluarga. Jika dibutuhkan untuk perorangan, bisa diinputkan pada file keperluan. Misal: untuk mengajukan beasiswa atas nama "Nama Anggota Keluarga". 
Tentunya menjadi tidak logis jika anak di bawah umur dibuatkan SKTM krn sdh jelas dia belum bekerja.
