### ISSUE TITLE
[TinyMCE] Konversi surat RTF - Keterangan Beda Identitas KIS

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#5903]
[surat_ket_beda_identitas_kis.pdf](https://github.com/OpenSID/OpenSID/files/9915298/surat_ket_beda_identitas_kis.pdf)

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/2511
