### ISSUE TITLE
Bug/error: Perpindahan Versi 22.09 ke 22.11

### ISSUE THREAD

**Issue by zonacerdas** [OpenSID/OpenSID#5904]
### Jelaskan error yg dialami

Awalnya kami menggunakan OpenSID versi 22.09 umum, kemudian ingin update ke versi 22.11. kami telah mendownload versi terbaru. kemudian folder "desa-contoh" kami hapus dan digantikan dengan folder "desa" pada versi 22.09. Kami coba akses website , kemudian muncul error.

saat kami menjalankan awal versi 22.11 murni tanpa diedit apapun, juga terjadi error.

Kami menduga error ini karena file tema natra tidak ada di versi 22.11 sedangkan setting website memilih menggunakan tema natra. Hal ini dibuktikan ketika kami ganti setting tema ke esensi, website berjalan normal

### Cara untuk mereplikasi errornya

Error terjadi di halaman utama website.

### Hasil yg diharapkan

Bisa menggunakan tema netra kembali

### Tangkapan layar dan log error

![1](https://user-images.githubusercontent.com/107665772/199389528-3d28fe56-528b-491d-935b-1970901b7406.png)

### Rilis Versi OpenSID

Rilis Umum

### Versi OpenSID

v21.11

### Tema Yang Digunakan

natra

**Comment by zonacerdas** [comment]
Kami telah lihat di folder **"vendor\themes\natra"** tidak ditemukan file **"corona-local.php"** pada **versi 22.11**. sehingga kami mendonwload tema natra di https://github.com/OpenSID/tema-natra dan menghapus folder **"natra"** dan menggantinya dengan folder natra yang baru di download. 

Hasilnya, website berjalan normal.

Kami harap file master rilis versi 22.11 kembali diulang. terimakasih

**Comment by zonacerdas** [comment]
Kami telah lihat di folder **"vendor\themes\natra"** tidak ditemukan file **"corona-local.php"** pada **versi 22.11**. sehingga kami mendonwload tema natra di https://github.com/OpenSID/tema-natra.

Kami mengcopy file **corona-local.php** dan **corona-widget.php** dari folde tema yang didownload. Kemudian mem-pastekan kedua file tersebut ke folder **"vendor\themes\natra"** versi 22.11. Hasilnya, website berjalan normal.

Kami juga mencoba menggantikan folder tema natra versi 22.11 secara keseluruhan dengan file tema yang baru di download. Hasilnya, hanya tampilan utama yang bagus sedangkan halaman demografi error dan hanya halaman blank saja.

Kami tidak tahu pasti apakah, penambahan dua file ini benar-benar mengatasi masalah tema natra di versi 2.11. tentunya kami menunggu dari admin konfirmasinya.

Kami harap file master rilis versi 22.11 kembali diulang nanti, agar yang belum download tidak menemukan masalah ini lagi. terimakasih

**Comment by ariandii** [comment]
Seperti biasa,
seluruh hal yang di alami oleh pengguna umum, sudah pasti dialami di pengguna Premium 6 bulan lalu.

dalam hal ini rilis v22.11 umum adalah rilis v22.04-premium April Lalu.

di atas sudah dialami pengguna Premium pada bulan April lalu dan sudah ada rilis perbaikan.

===
solusinya antara lain:
1. matikan Pengaturan **Covid Desa** di menu Admin Web -> Pengaturan (pilih Tidak pada option nya, simpan). atau
2. bisa menunggu rilis mendatang atau 
3. mari berlangganan OpenSID Premium agar dapat langsung memanfaatkan fitur dan perbaikan terbaru setiap pertama dirilis OpenSID.

Semoga membantu.

**Comment by zonacerdas** [comment]
baik pak, terimakasih atas informasinya.
