### ISSUE TITLE
Halaman peta pada tema untuk pilihan desa pengguna opensid tdk tampil

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#5905]
![peta 1](https://user-images.githubusercontent.com/57283157/199421384-bae87c9a-9bf6-497a-863a-7517934084aa.jpg)

SOLUSI : 
1. Sesuakain dengan API Terbaru Pantau
2. Dihapus, karena duplikasi fitur yang sama dengan Pantau.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1568
