### ISSUE TITLE
Edit pada artikel/halaman statis/simpan tidak ada perubahan

### ISSUE THREAD

**Issue by kbrozi** [OpenSID/OpenSID#5906]
### Jelaskan error yg dialami

Melakukan pengeditan pada Menu Utama/Admin Web/artikel/halaman statis/simpan (berhasil) tetapi tidak ada perubahan setelah disimpan

### Cara untuk mereplikasi errornya

1. Menu Utama
2. Admin Web
3. Artikel
4. Halaman statis
5. Edit (merapikan tulisan center)
6. simpan (berhasil)
7. Tampilan tidak ada perubahan masih posisi di pinggir tidak mau ke tengah
8. Edit lagi ketampilan yg berantakan

### Hasil yg diharapkan

Hasil editan tulisan berubah sesuai yg diinginkan menjadi rapi

### Tangkapan layar dan log error

![Screenshot_2022-11-02-15-59-53-42_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/116752256/199432489-fbcda935-7c7c-4ee1-99f6-a871fb9943a4.jpg)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.11-premium

### Tema Yang Digunakan

DeNatra v8.1

**Comment by kbrozi** [comment]
![Screenshot_2022-11-04-18-55-20-26_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/116752256/199956385-30bf87d8-4952-4627-af1d-4293b5667040.jpg)

Letak tulisan tidak ada perubahan setelah diedit, tidak mau sama rata atau dibesarkan huruf tidak ada perubahan setelah diedit simpan

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1574
