### ISSUE TITLE
Bug/error: token pelanggan berhasil tersimpan, tapi sering hilang / terhapus kembali 

### ISSUE THREAD

**Issue by FirlianiF** [OpenSID/OpenSID#5907]
### Jelaskan error yg dialami

Tokennya bisa input, tapi setelah beberapa hari hilang/terhapus lagi.
solusi sementara menginput token di config.

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

token tidak hilang-hilang terus, dan agar tidak perlu manual menginput di config.

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Versi 22.12-premium

**Comment by eddieridwan** [comment]
@FirlianiF @vickyrolanda @andifahruddinakas @devrakapriyo  , baca lagi https://t.me/c/1180597796/6001

**Comment by agungsugiarto** [comment]
mas @devrakapriyo, apakah issue ini sudah bisa ditutup?

**Comment by eddieridwan** [comment]
@devrakapriyo apakah sudah diperiksa lagi dengan menghapus solusi sementara menyimpan token di config? Karena solusi sementara itu tidak mengatasi akar permasalahan. Apakah akar permasalahan sudah ditemukan?

**Comment by vickyrolanda** [comment]
sejauh ini issue ini sudah bisa diatasini, namun menunggu laporan seperti ini kembali terjadi maka issue ini bisa di open kembali.

**Comment by eddieridwan** [comment]
@vickyrolanda di desa yg bermasalah, apakah sudah diperiksa lagi dengan menghapus solusi sementara menyimpan token di config? Karena solusi sementara itu tidak mengatasi akar permasalahan. Apakah akar permasalahan sudah ditemukan?

Ada berapa desa yg masih menyimpan token di config? @FirlianiF
