### ISSUE TITLE
Bug/error: log error berhasil jalankan migrasi_layanan

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#5908]
### Jelaskan error yg dialami

![F7FA7419-2AA0-4B49-A312-AEF0E7E595F3](https://user-images.githubusercontent.com/36557759/199509007-e1e4b3c3-351e-450b-b463-41099183f3ba.png)

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.11-premium

**Comment by vickyrolanda** [comment]
mungkin bisa di check di bagian sini : 
<img width="604" alt="image" src="https://user-images.githubusercontent.com/59082428/199651599-d9db8911-6648-4161-9f2e-9b996beb8717.png">

apakah fungsi ini di jalankan berulang kali , karena fungsi untuk menjalankan migrasi layanan tidak ada pernyataan yg membuatkan kondisi kapan harus di jalankan, namun setiap check migrasi akan selalu jalan.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1561
