### ISSUE TITLE
Permintaan fitur:  sesuaikan notif untuk kondusi token langganan sudah berakhir.

### ISSUE THREAD

**Issue by FirlianiF** [OpenSID/OpenSID#5909]
### Apa kekurangan yg ingin diatasi?

![photo_2022-11-03_11-26-36](https://user-images.githubusercontent.com/30171560/199647536-0dbc575b-6ddb-4f14-93b4-47b7350cab91.jpg)

Diatas notif yang diterima saat menginput token yang sudah kadaluarsa.

### Jelaskan solusi yg diinginkan

sesuaikan notif untuk kondusi token langganan sudah berakhir agar informasi yang diterima pengguna jelas.

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

Versi 22.12-premium

**Comment by apidong** [comment]
@vickyrolanda harus ada perbaikan dari sisi layanan. karena saya cek, respon dari layanan error 401 dan tidak menampilkan pesan eror,

**Comment by vickyrolanda** [comment]
> @vickyrolanda harus ada perbaikan dari sisi layanan. karena saya cek, respon dari layanan error 401 dan tidak menampilkan pesan eror,

mas @apidong bisa bantu review layanan yang dibuat mbak firly apakah sudah sesuai.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1898
