### ISSUE TITLE
upload tema lewat menu jgn cpanel. supaya lebih cepat dan mudah. 

### ISSUE THREAD

**Issue by Fajar-blackdeath** [OpenSID/OpenSID#5910]
### Apa kekurangan yg ingin diatasi?

dimohon untuk tema langsung masuk ke dalam versi terbaru jadi ngak upload upload tema. toh ada token yang sudah membuat sistem dikunci.

### Jelaskan solusi yg diinginkan

klo memang tidak ingin di upload dengamn bersamaan sistem lebih baik tema di upload di file sistem. jgn lewat cpanel

### Apakah ada alternatif lain

mohon untuk tema dimasukna langhsung di sitem terbaru. supya lebih mudah

### Untuk versi OpenSID mana

https://github.com/Fajar-blackdeath/contoh

### Informasi tambahan

.

**Comment by andifahruddinakas** [comment]
Duplicate issue https://github.com/OpenSID/OpenSID/issues/2486
