### ISSUE TITLE
Setiap upload photo dengan ukuran yang tertentu maka akan ada blank space yang mengikutin photo tersebut.

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#5912]
seperti contoh dibawah ini : 
![image](https://user-images.githubusercontent.com/59082428/199671951-de643a66-dea7-4525-b19b-69692adc2d97.png)

![image](https://user-images.githubusercontent.com/59082428/199672130-be71aab0-d344-415a-88ec-e5efa0a671c5.png)

**Comment by andifahruddinakas** [comment]
Solusi : 
1. Upload gambar tanpa ada croping.
2. Sediakan fitur editing sebelum gambar di upload.
![gambar 1](https://user-images.githubusercontent.com/57283157/199896476-9ea66e13-0c87-4da6-b258-2f7abbb3a2eb.jpg)

**Comment by ariandii** [comment]
apakah ini seharusnya bug? karena foto di artikel dll yang lama pun, semula normal menjadi muncul hitam.

termasuk jika hanya link foto di bypass dan unduh juga ada hitam.

apakah bisa normal kembali?

**Comment by vickyrolanda** [comment]
mas @apidong mohon bantuannya untuk memeriksa terkait upload images yang menajdi hitam bagian tertentu jika tidak sesuai ukuran croping.

**Comment by ariandii** [comment]
yang terjadi adalah foto foto lama menjadi ada hitam di opensid yg baru 2 bulan ini.

bukan mengenai cara cropping nya.

apakah yang artikel lama normal, namun setelah update opensid sejak bulan lalu menjadi ada hitam bukan  bug?

**Comment by apidong** [comment]
@vickyrolanda iya pak, banyak form upload yang seperti itu.

**Comment by apidong** [comment]
lokasi upload foto : 

- [x] artikel
- [x] pengaturan peta
- [x] penduduk

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1659
