### ISSUE TITLE
Sasaran program bantuan tidak muncul di rincian program 

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#5913]
seperti gambar dibawah ini seharusnya sasarannya keluarga namun di rincian program tedapat sasarannya kosong.
<img width="796" alt="image" src="https://user-images.githubusercontent.com/59082428/199673667-7b6d2cc9-98cb-4103-ba0e-e5a3670d9b5b.png">

**Comment by ariandii** [comment]
> seperti gambar dibawah ini seharusnya sasarannya keluarga namun di rincian program tedapat sasarannya kosong. <img alt="image" width="796" src="https://user-images.githubusercontent.com/59082428/199673667-7b6d2cc9-98cb-4103-ba0e-e5a3670d9b5b.png">

selain itu, bisa coba klik tambah peserta baru, maka tidak muncul list penduduk nya.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1563
