### ISSUE TITLE
Permintaan fitur: Tambahkan Beberapa Pilihan Lagi Pada Kelas Sosial Di Menu Keluarga

### ISSUE THREAD

**Issue by Pematung** [OpenSID/OpenSID#5914]
### Apa kekurangan yg ingin diatasi?

Masih diperlukannya penyesuaian pada Menu Keluarga Khusus Pada Kolom Kelas Sosial

![image](https://user-images.githubusercontent.com/105429258/200115090-3af3cc5e-bab9-4ede-a8f0-cf1ce40ead07.png)

### Jelaskan solusi yg diinginkan

Solusi yang diinginkan kalau bisa ditambahn beberap pilihan lagi pada pilihan kelas sosial seperti dibawah ini

1. Sangat Miskin
2. Miskin
3. Tidak Miskin

![image](https://user-images.githubusercontent.com/105429258/199862868-00302e0b-7a22-4aa6-9825-86018cd3fd3c.png)

Atau diganti penulisannya seperti ketiga pilihan diatas

### Apakah ada alternatif lain

Belom ada

### Untuk versi OpenSID mana

22.12 Premium

### Informasi tambahan

-

**Comment by eddieridwan** [comment]
@vickyrolanda kategori pilihan kesejahteraan yg disediakan perlu berdasarkan standar yg diakui, di mana arti dan indikator setiap tingkatan jelas. Yg ada sekarang berbasis pada kategori dari BKKBN (https://www.kompas.com/skola/read/2021/01/20/141551369/tahapan-keluarga-sejahtera-dan-indikatornya?page=all, http://aplikasi.bkkbn.go.id/mdk/BatasanMDK.aspx).

Jika dibutuhkan kategori sesuai kebutuhan lokal desa mungkin bisa menggunakan data suplemen atau modul Analisis.

**Comment by Pematung** [comment]
> @vickyrolanda kategori pilihan kesejahteraan yg disediakan perlu berdasarkan standar yg diakui, di mana arti dan indikator setiap tingkatan jelas. Yg ada sekarang berbasis pada kategori dari BKKBN (https://www.kompas.com/skola/read/2021/01/20/141551369/tahapan-keluarga-sejahtera-dan-indikatornya?page=all, http://aplikasi.bkkbn.go.id/mdk/BatasanMDK.aspx).
> 
> Jika dibutuhkan kategori sesuai kebutuhan lokal desa mungkin bisa menggunakan data suplemen atau modul Analisis.

Maksutnya tinggal ditambahkan saja kategori pilihannya........karena ini juga berdasarkan dari BPS (Badan Pusat Statistik)

**Comment by eddieridwan** [comment]
@Pematung @vickyrolanda untuk menambahkan pilihan harap beri dasar peraturannya sebagai acuan bagi pilihan yg akan ditambahkan.

**Comment by Pematung** [comment]
![image](https://user-images.githubusercontent.com/105429258/200175527-1e601a2f-bc6a-4fb1-90cf-4486f6e51c2b.png)

**Comment by eddieridwan** [comment]
@Pematung yg diperlukan bukan dasar hukum umum, melainkan acuan yg mengatur ketiga pilihan (definisi, penjelasan) yg anda usulkan tersebut secara spesifik:

1. Sangat Miskin
2. Miskin
3. Tidak Miskin

seperti yg ada lengkap untuk pilihan tingkat kesejahteraan keluarga yg sudah ada.

Yaitu, apa kriteria 'sangat miskin'? Apa bedanya dengan kategori 'miskin'? Dsbnya.
