### ISSUE TITLE
Bug/error: modal pengaturan tiap modul tidak berfungsi

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#5915]
### Jelaskan error yg dialami

<img width="1440" alt="Screen Shot 2022-11-04 at 09 25 09" src="https://user-images.githubusercontent.com/36557759/199871981-fed381f7-9dd8-48cf-8aca-ce25f87d7b45.png">

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.11-premium

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1564
