### ISSUE TITLE
Bug/error: sasaran peserta tidak muncul setelah tambah program bantuan baru

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#5916]
### Jelaskan error yg dialami

![image](https://user-images.githubusercontent.com/36557759/199873355-490ed972-24cc-4a13-8b25-4a71c6a99c05.png)

setelah membuat program bantuan baru, sasaran peserta tidak muncul seperti gambar di atas

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.11-premium

**Comment by devrakapriyo** [comment]
tidak hanya saat menambah program baru, tetapi semua sasaran peserta tidak muncul di masing-masing program bantuan

**Comment by ruririzal** [comment]
#5913

**Comment by devrakapriyo** [comment]
duplicate issue https://github.com/OpenSID/OpenSID/issues/5913, issue di close
