### ISSUE TITLE
Permintaan fitur: Tambahkan Pilihan Unduh pada Surat yang sudah ber TTE di Riwayat Pengajuan Surat pada Layanan Mandiri Mobile maupun Non Mobile

### ISSUE THREAD

**Issue by mah-mudi** [OpenSID/OpenSID#5917]
### Apa kekurangan yg ingin diatasi?

Belum adanya pilihan unduh surat yang sudah ber TTE di layanan mandiri mobile maupun non mobile. Hanya tertulis siap diambil.
Fitur ini digunakan agar masyarakat dapat unduh surat dan print sendiri surat tersebut tanpa ke Kantor Desa untuk ambil surat fisik nya.
![WhatsApp Image 2022-11-04 at 14 35 39](https://user-images.githubusercontent.com/57661283/199920508-36a93e3b-d0ac-4014-a07f-54b7c123ee8c.jpeg)

### Jelaskan solusi yg diinginkan

Penambahan pilihan unduh surat yang sudah TTE pada layanan mandiri.

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

22.11 Premium

### Informasi tambahan

-

**Comment by andifahruddinakas** [comment]
cek versi terbaru
