### ISSUE TITLE
Permintaan fitur: hilangkan pembatasan fitur pada website demo

### ISSUE THREAD

**Issue by ai-skematik** [OpenSID/OpenSID#5921]
### Apa kekurangan yg ingin diatasi?

saat ini anjungan tidak dapat di akses di website demo sehingga kesulitan untuk melakukan testing

### Jelaskan solusi yg diinginkan

hilangkan pembatasan fitur di website demo kecuali yang menyangkut keamanan.

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

22.12 premium

### Informasi tambahan

-

**Comment by andifahruddinakas** [comment]
Sudah diterapkan di v2305.0.0
