### ISSUE TITLE
Penambahan Surat Keterangan Domisili untuk non-warga

### ISSUE THREAD

**Issue by kbrozi** [OpenSID/OpenSID#5922]
### Apa kekurangan yg ingin diatasi?

Kebanyakan warga pendatang yg meminta Surat Keterangan Domisili

### Jelaskan solusi yg diinginkan

Buatkan untuk RTF dan TinyMCE agar mempermudah kami dalam untuk pelayanan non-warga

### Apakah ada alternatif lain

Kebanyakan warga pendatang diwilayah kami, sehingga mereka meminta surat keterangan domisili, mereka pergunakan untuk keperluan pinjaman usaha ke bank, membuat SIM, berobat di Rumah Sakit dan lain-lain masih banyak.

### Untuk versi OpenSID mana

v22.11-premium

**Comment by kbrozi** [comment]
![Uploading IMG_20221106_190145.jpg…]()

**Comment by kbrozi** [comment]
![Uploading Screenshot 2022-11-06 193032.png…]()

**Comment by kbrozi** [comment]
<img width="305" alt="Screenshot 2022-11-06 193032" src="https://user-images.githubusercontent.com/116752256/200168137-6288f203-4f27-4289-beb0-684067fe173a.png">

**Comment by kbrozi** [comment]
itu contoh surat keterangan domisili non-warna nya

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/2518
