### ISSUE TITLE
Bug/error: Token tidak tersimpan, sedangkan menu bisa di akses

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#5924]
### Jelaskan error yg dialami

![D2BA79C5-EE3C-40C7-A8BF-E4052FDCF305](https://user-images.githubusercontent.com/36557759/200167631-c0df29d9-7663-4f13-8bc0-071f2d629036.png)

desa https://sid.halangan.desa.id/pelanggan

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.11-premium

**Comment by agungsugiarto** [comment]
mas @devrakapriyo coba halaman layanan pelanggan di refresh beberapa kali

**Comment by devrakapriyo** [comment]
pengguna melakukan perubahan script, dengan ini issue saya close
