### ISSUE TITLE
Bug/error: upload foto di responsive filemanager muncul pesan error

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#5925]
### Jelaskan error yg dialami

![image](https://user-images.githubusercontent.com/36557759/200214373-ac877aa8-6174-4b08-a69c-85d165033e5f.png)

saat upload foto di Responsive Filemanager selalu muncul peringatan Warning: Use of undefined constant LOKASI_CACHE - assumed 'LOKASI_CACHE' (this will throw an Error in a future version of PHP) in /home/u1083103/public_html/sid/donjo-app/config/config.php on line 342

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.11-premium

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1567
