### ISSUE TITLE
Bug/error: pengaturan API Key OpenDK di OpenSID

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#5926]
### Jelaskan error yg dialami

![image](https://user-images.githubusercontent.com/36557759/200223736-16317db6-12d8-4ba1-a246-66501e05c0d3.png)

API Key OpenDK tidak ditentukan bila mungkin dapat di  "aktif or nonaktif" supaya system tidak membaca "404 Not Found` response"

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.11-premium

**Comment by Zoel-WB** [comment]
Oke  supaya tidak double issue saya gabungkan saja.
https://github.com/OpenSID/OpenSID/issues/5927
