### ISSUE TITLE
Bug/error: API Key OpenDK bila tidak dimasukan/ditentukan maka system akan menampilkan sebagai log error

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#5927]
### Jelaskan error yg dialami

Bila API-Key OpenDK bila tidak dimasukan/ditentukan atau dilakukan pengaturan API-Key pada fitur OpenDK maka system menganggap adanya errior dan tampil dan terekam sebagai log error.

### Cara untuk mereplikasi errornya

Buka Pengaturan -> Pilih Info System -> Logs

### Hasil yg diharapkan

Bila API-OpenDK tidak ditentukan/terisi di pengaturan supaya dapat tentukan "API-Key OpenDK "diaktifkan" atau "dinon-aktif" sehingga system menampilkan Logs Error.  

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/64481641/200224673-ac7ceb6b-faa0-4a0e-9a4c-5938fe4d3ad2.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

OpenSID Premium V22.11

### Tema Yang Digunakan

denatra

### Informasi tambahan

noted

**Comment by Zoel-WB** [comment]
Logs Error yg tampil bila API-OpenDK tidak dimasukkan atau sudah pernah di ditentukan dan di hilangkan kembali di pengaturan.

GuzzleHttp\Exception\ClientException: Client error: `POST http://localhost/OpenDK/public//api/v1/pesan/getpesan` resulted in a `404 Not Found` response:
run(true)#5 /home/teupinbe/public_html/vendor/guzzlehttp/promises/src/Promise.php(224): GuzzleHttp\Promise\Promise->invokeWaitFn()#6 /home/teupinbe/public_html/vendor/guzzlehttp/promises/src/Promise.php(269): GuzzleHttp\Promise\Promise->waitIfPending()#7 /home/teupinbe/public_html/vendor/guzzlehttp/promises/src/Promise.php(226): GuzzleHttp\Promise\Promise->invokeWaitList()#8 /home/teupinbe/public_html/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending()#9 /home/teupinbe/public_html/vendor/guzzlehttp/guzzle/src/Client.php(187): GuzzleHttp\Promise\Promise->wait()#10 /home/teupinbe/public_html/vendor/guzzlehttp/guzzle/src/ClientTrait.php(95): GuzzleHttp\Client->request('POST', 'http://localhos...', Array)#11 /home/teupinbe/public_html/donjo-app/core/MY_Security.php(226) : eval()'d code(1) : eval()'d code(758): GuzzleHttp\Client->post('http://localhos...', Array)#12 /home/teupinbe/public_html/donjo-app/core/MY_Security.php(226) : eval()'d code(1) : eval()'d code(55): get_pesan_opendk()#13 /home/teupinbe/public_html/vendor/codeigniter/framework/system/core/CodeIgniter.php(533): Hom_sid->index()#14 /home/teupinbe/public_html/index.php(283): require_once('/home/teupinbe/...')#15 {main}

**Comment by agungsugiarto** [comment]
error ini terjadi bukan karena token yg tidak dimasukkan, tapi karena aplikasi opendk yg ada di local `(http://localhost/OpenDK/public//api/v1/pesan/getpesan resulted in a 404 Not Found response:)` tidak ada, mas @vickyrolanda mohon di analisis

**Comment by Zoel-WB** [comment]
> error ini terjadi bukan karena token yg tidak dimasukkan, tapi karena aplikasi opendk yg ada di local `(http://localhost/OpenDK/public//api/v1/pesan/getpesan resulted in a 404 Not Found response:)` tidak ada, mas @vickyrolanda mohon di analisis

tapi dikosongkan juga tidak bisa pak @agungsugiarto tetap kolom-nya mintak isi...

**Comment by agungsugiarto** [comment]
pak @Zoel-WB isi dengan url yg benar terinstall opendk, karena tujuan dibuat log agar memudahkan mendebug error pak.

**Comment by Zoel-WB** [comment]
> pak @Zoel-WB isi dengan url yg benar terinstall opendk, karena tujuan dibuat log agar memudahkan mendebug error pak.

Ini Pak @agungsugiarto mau saya kosongkan juga tidak bisa lagi dulu pernah memang subdomain opendk untuk menguji sinkronisasi data, sekarang setelah subdomain opendk dihapus karena hostingnya sudah tidak mencukupi, setting di opensid tidak dapat lagi dihapus, makanya untuk mensiasati supaya baris sinkronisasi tidak kosong, saya masukkan seolah-olah ada website opendk localhost.

![image](https://user-images.githubusercontent.com/64481641/200564417-79af43fa-1558-4a5c-86d8-311e88bd616c.png)

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1591
