### ISSUE TITLE
Tidak muncul nomor surat otomatis

### ISSUE THREAD

**Issue by kbrozi** [OpenSID/OpenSID#5928]
### Jelaskan error yg dialami

Pada saat mau membuat surat tidak muncul nomor surat

### Cara untuk mereplikasi errornya

1. Menu utama
2. layanan surat
3. Cetak surat

### Hasil yg diharapkan

Munculkan nomor surat otomatis kembali

### Tangkapan layar dan log error

![IMG_20221107_223433](https://user-images.githubusercontent.com/116752256/200337180-2ac57a86-69a1-4af2-8bf3-07409b49e1d7.jpg)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.11-premium

### Tema Yang Digunakan

DeNatra v8.1

### Informasi tambahan

Munculkan kembali nomor surat otomatis
![IMG_20221107_224321](https://user-images.githubusercontent.com/116752256/200338286-0597dda7-d979-4d9c-ab57-bd0a065ddb35.jpg)

**Comment by agungsugiarto** [comment]
![Image](https://user-images.githubusercontent.com/10989147/201557549-0ac938f5-be1a-47d4-ba45-6a63dd4c2d21.png)


Saya coba tidak ada masalah, mas @devrakapriyo mohon dibantu untuk memastikan ulang

**Comment by kbrozi** [comment]
[https://berputar.opendesa.id/surat/form/surat-keterangan-usaha](url)
mas @agungsugiarto dari sisi berputar juga tidak muncul

**Comment by agungsugiarto** [comment]
Pak @kbrozi, yg diberputar belum di update ke rev-02, nanti biar dipastikan terlebih dahulu oleh @devrakapriyo

**Comment by andifahruddinakas** [comment]
Mas @devrakapriyo, kayaknya sama dengan issue https://github.com/OpenSID/OpenSID/issues/5959
