### ISSUE TITLE
Usul: Pemberitahuan ke pengguna jika ada versi baru

### ISSUE THREAD

**Issue by telo99** [OpenSID/OpenSID#593]
Barusan lihat daftar pengguna di tracksid, ternyata masih banyak yang belum update ke versi baru.
Sekedar usul saja, beri pemberitahuan ke pengguna jika ada OpenSID versi baru.
Misal  setelah admin login ke siteman, script akan mengakses file "version.txt" di github, jika versi di github lebih baru, maka akan muncul popup/alert pemberitahuan jika ada update. Popupnya hanya sekali saja setelah login, kalau muncul keseringan takutnya malah mengganggu.

**Comment by siayi** [comment]
@telo99 usul ini sepertinya serupa dengan issues https://github.com/eddieridwan/OpenSID/issues/597

**Comment by siayi** [comment]
repo ini [Update script OpenSID langsung dari GitHub repo](https://github.com/esyede/opensid-updater) sepertinya terkait dgn issue.

**Comment by afa28** [comment]
Duplicate #3204
