### ISSUE TITLE
Laporan Kehadiran Perangkat Desa pada layanan mandiri muncul semua sehingga terlihat data duplicate nama dll.

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#5930]
1. Login ke layanan mandiri
2. lalu pilih perangkat
3. maka akan tampil semua laporan 
<img width="575" alt="image" src="https://user-images.githubusercontent.com/59082428/200367481-da6041d0-b9da-4716-b44d-f4cf44557fd4.png">

Seharusnya yang tampil berdasarkan tanggal hari ini saja .

**Comment by agungsugiarto** [comment]
Mas @vickyrolanda, bisa diperjelas maksudnya

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1599

**Comment by vickyrolanda** [comment]
mas @agungsugiarto  mohon di buatkan lagi PR susulan untuk perbaikan ini ya mas, karena yg sebelumnya buat error seperti ini mas.
ERROR - 2022-11-14 20:38:14 --> Severity: error --> Exception: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'tanggal' in 'where clause' (SQL: select `pamong_id`, `pamong_nama`, `jabatan_id`, `ref_jabatan`.`nama` as `pamong_jabatan`, `pamong_nip`, `pamong_niap`, `pamong_ttd`, `pamong_ub`, `pamong_status`, `pamong_nik`, IF(tweb_desa_pamong.id_pend IS NULL, tweb_desa_pamong.pamong_nama, tweb_penduduk.nama) AS pamong_nama, IF(tweb_desa_pamong.id_pend IS NULL, tweb_desa_pamong.pamong_nik, tweb_penduduk.nik) AS pamong_nik, gelar_depan, gelar_belakang from `tweb_desa_pamong` left join `tweb_penduduk` on `tweb_penduduk`.`id` = `tweb_desa_pamong`.`id_pend` left join `ref_jabatan` on `ref_jabatan`.`id` = `tweb_desa_pamong`.`jabatan_id` where `pamong_status` = 1 and `kehadiran` = 1 and (`tanggal` = curdate() or `tanggal` is null)) C:\xampp\htdocs\OpenDesa\OpenSID\vendor\illuminate\database\Connection.php 712

**Comment by agungsugiarto** [comment]
apakah sudah dibuatkan rilis mas? malam ini belum bisa saya kerjakan karena sedang keluar
