### ISSUE TITLE
Jumlah program bantuan tidak sama dengan yg ada di dalam list program bantuan

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#5932]
![image](https://user-images.githubusercontent.com/59082428/200443388-62a1d977-2279-4f04-bcde-c8d363fb468e.png)

mas @devrakapriyo mungkin ini butuh database penggunanya soalnya saya uji di disaya beberapa database dan coba replikasi tidak menemukan data yang tidak belance, ini saya buatkan issuenya terlebih dahulu.

**Comment by Zoel-WB** [comment]
Penyebabnya pada data penduduk yg sudah berubah status dasar (mati atau pindah) yg pernah masuk sebagai penerima bantuan, dalam list daftar bantuan tidak lagi ditampilkan, akan tetapi pada penjumlahan masih terjumlahkan, begitu juga saat mengosongan semua data penerima bantuan (dihapus semua), saat akan dihapus item program bantuan tidak dapat dihapus dengan pesan masih ada data penerima (ada data tersembunyi dari penduduk yg telah berubah status dasar yg masih tersimpan di daftar program). 

Bila dimungkinkan bisa melalukan mutasi bulanan, misalnya sebelumnya ada 50 orang/warga penerima bantuan -->ternyata dipertengahan bulan ada Penerima Bantuan yg pindah atau meninggal, supaya data bulan ini tidak hilang tetap dengan jumlah 50 penerima bantuan karena ada sangkutan dengan pemantauan budget anggaran.

Untuk bulan berikutnya data sebelumnya harus dapat dimutasikan dari 50 penerima telah bekurang 1 penerima, menjadi 49 orang penerima untuk bulan berikutnya misalnya seperti itu. Ini mungkin untuk mempemudah pendataan, supaya  data tetap tak boleh dihapus bila sudah di input karena penting untuk melihat siapa saja penerima dikemudian hari walau ada data yg telah berubah status (pindah/meninggal).

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1622
