### ISSUE TITLE
Bug/error: Hilangkan Info History Login Pada Kolom User

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#5934]
### Jelaskan error yg dialami

Bisa coba buka halaman Login Layanan Mandiri dan Login Kehadiran, begitu pula Login Siteman.

Ketika klik kolom Nama Pengguna maupun kolom Kata Sandi pada Siteman
Ketika klik kolom NIK maupun kolom PIN pada Layanan Mandiri
Ketika klik kolom NIK maupun kolom PIN pada Halaman Kehadiran
dan juga Ketika klik kolom Tempelkan E KTP maupun kolom PIN pada Halaman Kehadiran

maka seluruhnya muncul rekaman email atau user atau NIK yg pernah diketik sebelumnya.

### Cara untuk mereplikasi errornya

seperti di atas

### Hasil yg diharapkan

tidak menampilkan history apapun. saya biasa menyisipkan `autocomplete="off"` pada script <input> nya.

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Semua

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1582
