### ISSUE TITLE
data rumah tangga hilang semua saat menambahkan rumah tangga baru

### ISSUE THREAD

**Issue by mranca** [OpenSID/OpenSID#5935]
### Jelaskan error yg dialami

saat menambahkan data rumah tangga baru tiba-tiba data yang ada sebelumnya hilang semua 

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.11-Premium-rev01

### Tema Yang Digunakan

-

### Informasi tambahan

-

**Comment by devrakapriyo** [comment]
pak @mranca saya cek di berputar.opendesa.id normal, untuk pengecekan lebih lanjut bisa tolong kirimkan akun admin desanya?

**Comment by mranca** [comment]
@devrakapriyo saya sudah turunkan versi pak ke 22.11-premium pak dan yang bersamsalah cuma di 22.11-premium rev01

**Comment by mranca** [comment]
mungkin bisa minta akun admin desa https://pampangan-lambar.desa.id/ untuk di testing pak karna dia laporkan juga di grup dengan masalah yang sama

**Comment by vickyrolanda** [comment]
> mungkin bisa minta akun admin desa https://pampangan-lambar.desa.id/ untuk di testing pak karna dia laporkan juga di grup dengan masalah yang sama

apakah sudah coba jalankan migrasinya pak ?

**Comment by mranca** [comment]
sudah pak setiap habis update saya selalu migrasi

**Comment by andifahruddinakas** [comment]
Mas @devrakapriyo, sama dengan issue https://github.com/OpenSID/OpenSID/issues/5966?

**Comment by andifahruddinakas** [comment]
> sudah pak setiap habis update saya selalu migrasi

Mas @mranca, bisa kirim DB lewat telegram saya untuk test?

**Comment by mranca** [comment]
Kalau data base saya sudah normal, karna sudah saya turunkan versinya dari rev01 ke premium22.11 dan saya sudah import kembali hasil export data rumah tangga sebelumnya pak

**Comment by mranca** [comment]
Tapi kalau mau minta dbnya saya siap kirimkan

**Comment by andifahruddinakas** [comment]
> Tapi kalau mau minta dbnya saya siap kirimkan

kirim ke https://t.me/fahruddinakas, biar dicek dan diselesaikan. Agar tidak terkunci diversi lama dan bisa diupdate.

**Comment by mranca** [comment]
> 

sudah saya kirimkan pak

**Comment by devrakapriyo** [comment]
mas @andifahruddinakas iya ini issue nya sama https://github.com/OpenSID/OpenSID/issues/5966

**Comment by andifahruddinakas** [comment]
> mas @andifahruddinakas iya ini issue nya sama #5966

untuk issue #5966 sudah dijelaskan di komentar penyebab tidak muncul. Bisa cek komentar  https://github.com/OpenSID/OpenSID/issues/5966#issuecomment-1313111215

Untuk issue ini masih dicek, dan coba replikasi menggunakan database pengguna, tp belum menemukan letak masalahnya.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1632

solusinya Data pengguna yang berubah, yang bisa dikembalikan hanyalah kepala RT karena data anggota tidak ada riwayatnya pada tabel tweb_rtm dan di tweb_penduduk hanya menyimpan id_rtm yang dimana sudah berubah semua (sama).
