### ISSUE TITLE
Bug/error: Jenis Perkades pada input data, tapi output yang tampil di web bernama Perdes

### ISSUE THREAD

**Issue by mah-mudi** [OpenSID/OpenSID#5936]
### Jelaskan error yg dialami

Jenis Perkades pada input data, tapi output yang tampil di web bernama Perdes

### Cara untuk mereplikasi errornya

yang diinput adalah peraturan kepala desa (perkades)
![image](https://user-images.githubusercontent.com/57661283/200476380-98d0870b-8543-4187-a2ae-2958b3ff30bd.png)

yang muncul di web menjadi perdes
![image](https://user-images.githubusercontent.com/57661283/200476522-af13d430-aa0e-4feb-bc9d-ad95d976a13f.png)

### Hasil yg diharapkan

Input Perkades , yang tampil di web jenis nya perkades

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/57661283/200476380-98d0870b-8543-4187-a2ae-2958b3ff30bd.png)

![image](https://user-images.githubusercontent.com/57661283/200476522-af13d430-aa0e-4feb-bc9d-ad95d976a13f.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

22.11 Premium rev01

### Tema Yang Digunakan

silir 3.6.3

**Comment by andifahruddinakas** [comment]
Yg di halaman web ditampilkan berdsarkan kategori bukan jenisnya.

![peraturan](https://user-images.githubusercontent.com/57283157/200766281-24a92e16-1374-4d49-9aad-f70f65df5038.jpg)

**Comment by andifahruddinakas** [comment]
Mas @devrakapriyo, bisa dicek lg ulang.
