### ISSUE TITLE
Bug/error: Input Data Keuangan Sistem sudah support desimal digit dua, tapi output tampilan belum menampilkan desimal digit dua

### ISSUE THREAD

**Issue by mah-mudi** [OpenSID/OpenSID#5938]
### Jelaskan error yg dialami

Input Data Keuangan Sistem sudah support desimal digit dua, tapi output tampilan belum menampilkan desimal digit dua

### Cara untuk mereplikasi errornya

1. Modul Keuangan
2. Input Data (sudah support desimal dua dgit)
3. Pergi Halaman Web, keuangan APBDesa, yang ditampilkan masih belum tertulis desimal digit dua

### Hasil yg diharapkan

Output tampilan keuangan APBDesa ditampilan WEB dapat menampilkan desimal digit dua

### Tangkapan layar dan log error

input data sudah support desimal dua dgit
![image](https://user-images.githubusercontent.com/57661283/200477953-a99be35d-7d68-4ffe-80d0-0f36ffbd66b3.png)

tampilan keuanga belum dapat menampilkan desimal dua digit
![image](https://user-images.githubusercontent.com/57661283/200478051-e94f5bb7-44dc-4699-bb00-8c64b34fbb89.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

22.11 Premium rev01

### Tema Yang Digunakan

silir 3.6.3

**Comment by andifahruddinakas** [comment]
Issue https://github.com/OpenSID/OpenSID/issues/5929
