### ISSUE TITLE
Permintaan fitur: filter/pencarian menu

### ISSUE THREAD

**Issue by ruririzal** [OpenSID/OpenSID#5939]
### Apa kekurangan yg ingin diatasi?

semakin banyak menu yang ada akan semakin kerepotan untuk menghafal posisi menu yang dicari

### Jelaskan solusi yg diinginkan

-

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

premium

**Comment by ruririzal** [comment]
![image](https://user-images.githubusercontent.com/28647065/200523556-28571d52-ce36-465d-ac50-275a6bb91884.png)

[1580](https://github.com/OpenSID/premium/pull/1580)

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1580
