### ISSUE TITLE
Periksa sumber terkait file mencurigakan di dalam project OpenSID

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#5940]
### Jelaskan error yg dialami

-

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.11-premium-rev1

**Comment by devrakapriyo** [comment]
![E226399B-463B-4CC3-8B68-468D4681B233](https://user-images.githubusercontent.com/36557759/200566680-fc667913-e2a6-4433-9593-baa29c926250.jpeg)

**Comment by syahransaputra** [comment]
terkait issue #5891

**Comment by vickyrolanda** [comment]
untuk uji coba ini diperlukan cpanel atau server yang memiliki masalah terkait ini agar dapat di check file di server tersebut juga dan file - file yang tersembunyi di dalamnya, mungkin pak @syahransaputra mengalami hal tersebut? 
mas @devrakapriyo mohon bantu carikan aksesnya ya mas.

**Comment by syahransaputra** [comment]
> untuk uji coba ini diperlukan cpanel atau server yang memiliki masalah terkait ini agar dapat di check file di server tersebut juga dan file - file yang tersembunyi di dalamnya, mungkin pak @syahransaputra mengalami hal tersebut? mas @devrakapriyo mohon bantu carikan aksesnya ya mas.

untuk sementara di server yg saya gunakan aman pak @vickyrolanda tidak ada file yg mencurigakan seperti yg dialami issue ini, saya hanya mentione issue bpk sebelumnya dikarenakan issue ini berhubungan.

mungkin sedikit referensi, ini dari pengguna yg mengalami hal yg sama
![photo_2022-11-08_19-08-09](https://user-images.githubusercontent.com/26229332/201180376-7c19362d-60e7-4880-94d5-6e7a3c88de30.jpg)
ada 3 file asing dan 1 file index.php yg sudah termodifikasi di tanggal & jam yang sama dengan file asing tersebut.

**Comment by vickyrolanda** [comment]
@devrakapriyo  melakukan audit terkait upload file pada semua menu, dan dibuat digoogle sheet  untuk melihat sumber ada celah upload file ke server. 
sekalian buat daftar dimana area -arenya agar bisa di cek berulang.

mas @devrakapriyo mohon di buatkan untuk di report dihari selasa.

Misal images yang disisipin php dll.

**Comment by vickyrolanda** [comment]
saat ini bug ini sudah teratasi dengan membatasi setiap fungsi upload file agar tidak bisa upload file yang berbentuk script dengan ext .jpg dan file - file yg mencurigakan lainnya.
