### ISSUE TITLE
Bug/error: proses loading opensid lama hingga time out 

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#5941]
### Jelaskan error yg dialami

![20D88DFC-7540-4D2F-A087-5D3AA69B9303](https://user-images.githubusercontent.com/36557759/200565680-fdbfdc7f-40b8-49f8-bb80-872dcc60b3b2.jpeg)

Loading web menjadi lambat setelah update ke 22.11-premium-rev1 hingga timeout

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

optimasi proses loading yang lama

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.11-premium-rev1

**Comment by vickyrolanda** [comment]
ini sudah tidak ada terjadi lagi kemaren sy sudah testing dan pantau desa pak ariandi dan terakhir sy coba hubungin pak ariandi coba sudah normal , untuk saat ini sy close terlebih dahulu lalu jika terjadi hal yang serupa silahkan di buka kembali
