### ISSUE TITLE
Bug/error: Banyak Pengguna Menggunakan Hari Pada Papan Proyek

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#5942]
### Jelaskan error yg dialami

saat ini banyak yang melapor waktu pengerjaan pada fitur pembangunan adalah Bulan. padahal di desa waktu pengerjaan berdasarkan Hari. sehingga ini ditandai bug.

### Cara untuk mereplikasi errornya

1. Manu Pembangunan
2. Tambah Data
3. Kolom Waktu

### Hasil yg diharapkan

Waktu berdasarkan Hari, bukan bulan.
agar dapat diisi 15 hari atau 45 hari atau 10 hari dll

### Tangkapan layar dan log error

sda

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Semua

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1581
