### ISSUE TITLE
Perlu menambahkan list validasi dari pengaturan key masing - masing

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#5946]
menambahkan list validasi dari pengaturan key masing2, misalnya :

ID Telegram => angka max 11
Sebutan Desa => huruf max 50
Dll

**Comment by andifahruddinakas** [comment]
Bisa tambahkan aturan validasi yg diperlukan pada key pengaturan berikut : 
"admin_title",
"aktifkan_sms",
"anjungan_artikel",
"anjungan_layar",
"anjungan_profil",
"anjungan_slide",
"anjungan_teks_berjalan",
"anjungan_video",
"anjungan_youtube",
"apbdes_footer",
"apbdes_footer_all",
"apbdes_manual_input",
"api_gform_credential",
"api_gform_id_script",
"api_gform_redirect_uri",
"api_opendk_key",
"api_opendk_password",
"api_opendk_server",
"api_opendk_user",
"banyak_foto_tiap_produk",
"branding_desa",
"covid_desa",
"covid_rss",
"current_version",
"daftar_penerima_bantuan",
"dashboard_program_bantuan",
"enable_track",
"font_surat",
"footer_surat",
"footer_surat_tte",
"format_nomor_surat",
"header_surat",
"hubung_warga_balas_otomatis",
"id_pengunjung_kehadiran",
"ip_adress_kehadiran",
"jenis_peta",
"jumlah_produk_perhalaman",
"kode_desa_bps",
"latar_kehadiran",
"layanan_mandiri",
"layanan_opendesa_token",
"libreoffice_path",
"login_title",
"mac_adress_kehadiran",
"mapbox_key",
"max_zoom_peta",
"min_zoom_peta",
"notifikasi_koneksi",
"notifikasi_pengajuan_surat",
"offline_mode",
"panjang_nomor_surat",
"penggunaan_server",
"penomoran_surat",
"pesan_singkat_wa",
"sebutan_camat",
"sebutan_desa",
"sebutan_dusun",
"sebutan_kabupaten",
"sebutan_kabupaten_singkat",
"sebutan_kecamatan",
"sebutan_kecamatan_singkat",
"sebutan_nip_desa",
"sebutan_pemerintah_desa",
"sebutan_singkatan_kadus",
"statistik_chart_3d",
"sumber_gambar_slider",
"tahun_idm",
"tampilan_anjungan",
"tampilan_anjungan_audio",
"tampilan_anjungan_slider",
"tampilan_anjungan_video",
"tampilan_anjungan_waktu",
"tampilkan_kehadiran",
"tampilkan_lapak_web",
"tampilkan_pendaftaran",
"tampil_luas_peta",
"telegram_token",
"telegram_user_id",
"tgl_data_lengkap",
"tgl_data_lengkap_aktif",
"timezone",
"tinggi_footer",
"tinggi_header",
"tte",
"tte_api",
"tte_password",
"tte_username",
"ukuran_lebar_bagan",
"verifikasi_kades",
"verifikasi_sekdes",
"visual_tte",
"visual_tte_gambar",
"visual_tte_height",
"visual_tte_weight",
"warna_tema_admin",
"website_title",
"web_artikel_per_page",
"web_theme"

**Comment by vickyrolanda** [comment]
> Bisa tambahkan aturan validasi yg diperlukan pada key pengaturan berikut : "admin_title", "aktifkan_sms", "anjungan_artikel", "anjungan_layar", "anjungan_profil", "anjungan_slide", "anjungan_teks_berjalan", "anjungan_video", "anjungan_youtube", "apbdes_footer", "apbdes_footer_all", "apbdes_manual_input", "api_gform_credential", "api_gform_id_script", "api_gform_redirect_uri", "api_opendk_key", "api_opendk_password", "api_opendk_server", "api_opendk_user", "banyak_foto_tiap_produk", "branding_desa", "covid_desa", "covid_rss", "current_version", "daftar_penerima_bantuan", "dashboard_program_bantuan", "enable_track", "font_surat", "footer_surat", "footer_surat_tte", "format_nomor_surat", "header_surat", "hubung_warga_balas_otomatis", "id_pengunjung_kehadiran", "ip_adress_kehadiran", "jenis_peta", "jumlah_produk_perhalaman", "kode_desa_bps", "latar_kehadiran", "layanan_mandiri", "layanan_opendesa_token", "libreoffice_path", "login_title", "mac_adress_kehadiran", "mapbox_key", "max_zoom_peta", "min_zoom_peta", "notifikasi_koneksi", "notifikasi_pengajuan_surat", "offline_mode", "panjang_nomor_surat", "penggunaan_server", "penomoran_surat", "pesan_singkat_wa", "sebutan_camat", "sebutan_desa", "sebutan_dusun", "sebutan_kabupaten", "sebutan_kabupaten_singkat", "sebutan_kecamatan", "sebutan_kecamatan_singkat", "sebutan_nip_desa", "sebutan_pemerintah_desa", "sebutan_singkatan_kadus", "statistik_chart_3d", "sumber_gambar_slider", "tahun_idm", "tampilan_anjungan", "tampilan_anjungan_audio", "tampilan_anjungan_slider", "tampilan_anjungan_video", "tampilan_anjungan_waktu", "tampilkan_kehadiran", "tampilkan_lapak_web", "tampilkan_pendaftaran", "tampil_luas_peta", "telegram_token", "telegram_user_id", "tgl_data_lengkap", "tgl_data_lengkap_aktif", "timezone", "tinggi_footer", "tinggi_header", "tte", "tte_api", "tte_password", "tte_username", "ukuran_lebar_bagan", "verifikasi_kades", "verifikasi_sekdes", "visual_tte", "visual_tte_gambar", "visual_tte_height", "visual_tte_weight", "warna_tema_admin", "website_title", "web_artikel_per_page", "web_theme"

ok mas coba sy lihat dan apa validasi yang di perlukan.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1566
