### ISSUE TITLE
Merubah Status kepala keluarga

### ISSUE THREAD

**Issue by ElAndea** [OpenSID/OpenSID#5948]
tidak bisa merubah status kepala keluarga ketika kepala keluarga sudah berstatus mati anggota keluarga lain tidak bisa menggantikan status kepala keluarga.

**Comment by eddieridwan** [comment]
@vickyrolanda @devrakapriyo laporan/permintaan seperti ini perlu ditanggapi secepat mungkin, dan dalam hal ini ditutup. Buat entri (jika belum ada) di forum.opendesa.id yg menjelaskan dan mengacu pada panduan.

@vickyrolanda @devrakapriyo harap teman2 jelaskan pada @ElAndea mengapa laporan/permintaan ini ditutup. Segera tutup issue ini supaya tidak memenuhi daftar issue untuk hal2 yg tidak akan diterapkan.

https://github.com/OpenSID/OpenSID/wiki/Keluarga#alur-kepala-keluarga-meninggal

@ElAndea selalu usahakan membaca panduan yg luar biasa kaya isinya.
