### ISSUE TITLE
Ubah hari libur ketika update ditanggal yang sama tidak bisa 

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#5949]
Kasusnya seperti ini : 
1. Misalkan tanggal 10 November 2022 adalah hari libur yang diambil dari sistem bawaan OpenSID
2. Lalu di tanggal 10 November 2022 ternyata desa tersebut masuk kerja namun berhubung tanggal tersebut adalah hari libur maka  halaman kehadiran tidak dapat melakukan absensi walaupun di halaman jam kerja hari tersebut bersatatus hari kerja.
3. Perlu di hapus tanggal 10 November tersebut dari daftar hari libur.

Yang di harapkan ubah parameter hari kerja berdasarkan apa yang tampil di daftar jam kerja misalkan, Jika di tanggal hari ini ada terdapat hari libur maka stataus menjadi libur namun ketika ingin di ubah menajdi kerja maka tinggal mengubah di halaman jam kerja saja menjadi hari kerja tanpa harus menghapus hari libur yang ada di menu hari libur

**Comment by andifahruddinakas** [comment]
Sediakan tombol status aktif/tdkaktif

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/OpenSID/pull/7456
