### ISSUE TITLE
Mohon Ditambahkan Fitur untuk Pendataan Prodeskel

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#595]
Mohon Bagi Para Programer menurut saya ini akan menjadi nilai PLUS juga di OpenSID kalau ada Fitur Pengimputan Prodeskel yang langsung Link dengan menu Penduduk , mengngat pendataan Profil Desa setiap tahun diadakan di desa, sebagai acuan saya sertakan dengan formnya
[FORM Profil Desa ONline.zip](https://github.com/eddieridwan/OpenSID/files/1253339/FORM.Profil.Desa.ONline.zip)

**Comment by eddieridwan** [comment]
@MUHAMMADRANGSEL Luar biasa terinci informasi yang dikumpulkan melalui Prodeskel!! Saat ini bagaimana biasanya dikumpulkan data ini? Di entri ke mana? Laporannya dibuat dengan apa?

**Comment by eddieridwan** [comment]
Lihat diskusi dengan https://www.facebook.com/imronnurohim.imronnurohim?fref=gc di https://www.facebook.com/groups/OpenSID/.

Issue ini perlu dibatasi pada fitur spesifik, karena secara keseluruhan akan membutuhkan pengembangan skala besar.

Sepertinya perlu dibatasi pada: 

1. penyimpanan data keluarga ("DAFTAR ISIAN DATA DASAR KELUARGA")
2. ekspor data "DAFTAR ISIAN DATA DASAR KELUARGA" dalam format yang bisa digunakan oleh _aplikasi injector_ untuk dimasukkan secara otomatis ke situs Prodeskel di http://prodeskel.binapemdes.kemendagri.go.id/mpublik/

Setelah tugas ini diselesaikan, baru teruskan untuk kumpulan data Prodeskel yang lain.

**Comment by eddieridwan** [comment]
Mudah2an Imron Nurohim bersedia untuk berbagi _aplikasi injector_ yang telah dia kembangkan. Atau mungkin ada teman2 lain yang mempunyai aplikasi serupa? @MUHAMMADRANGSEL

**Comment by eddieridwan** [comment]
Bung Imron Nurohim telah bersedia untuk menerapkan issue ini.

**Comment by MUHAMMADRANGSEL** [comment]
Alhqmdulillqh sdh ada yg bersedia mmbantu mas eddie krn ini sangat penting
sekali di desa

Pada tanggal 29 Agt 2017 16:28, "Eddie Ridwan" <notifications@github.com>
menulis:

**Comment by andanwar** [comment]
Maaf sbelumnya tentang postingan di fb saya hapus.. karna itu post yg lama saya akan post baru

**Comment by andanwar** [comment]
[
[JS Prodeskel.zip](https://github.com/eddieridwan/OpenSID/files/1262070/JS.Prodeskel.zip)
](url)

**Comment by MUHAMMADRANGSEL** [comment]
![image](https://user-images.githubusercontent.com/25834335/29850074-1e86602a-8d55-11e7-9e95-40ec1d65edb0.png)
 berapa CD key - nya mas

**Comment by andanwar** [comment]
Maaf untuk CD key kami adakan Donasi ...seharga Rp.100.000 dengan rincian 50.000 buat Donasi OpenSid
Dan 50.000 lagi buat pengembangan Software Prodeskel nya itu sendiri..
Untuk donasi OpenSID silahkan hubungi bung eddieridwan atau yg mengelola langsung donasi openSId demi berjalannya kerjasama sid Prodeskel..makasih

**Comment by bhien76** [comment]
Bang Andi Anwar, kalau bisa dibautkan video demo untuk aplikasi jsnya. jadi teman2 tau cara kerjanya

**Comment by MUHAMMADRANGSEL** [comment]
Apakah CD Key hanya satu kaki kita masukkan dan bisa digunakan tuk slmanya?

**Comment by metalab25** [comment]
@andanwar : saya sudah berdonasi ke opensid, apa bisa saya dapat CDKeynya

**Comment by andanwar** [comment]
@metalab25 CD key bisa didapatkan setelah bedonasi opensud sama donasi ke saya buat pengembangan aplikasi prodeskel ini WA saya mas ya 083817343994

**Comment by andanwar** [comment]
@MUHAMMADRANGSEL
JAWAB
1.CD-KEY hanya 1 kali dimasukan untuk selamanya 
2.CD key digunakan untuk 1 user atau 1 oengguna PC

**Comment by MUHAMMADRANGSEL** [comment]
gimana kalau kita instal ulang komputer apakah CD-Key tersebut masih dipakai di lapotop/ komputer yg sdh kita instal ulang

**Comment by andanwar** [comment]
CD key hanya bisa di pakai sendiri.. jd harus order full versi ..cd key diberikan hanya 2 cd key jika yerjafi error komputer atau pc

**Comment by andanwar** [comment]
](url)
![vid_gif-1504489720](https://user-images.githubusercontent.com/24935377/30008924-43dc84e2-914e-11e7-9855-eac7ca6db9ee.gif)

**Comment by MUHAMMADRANGSEL** [comment]
Mantap

**Comment by MUHAMMADRANGSEL** [comment]
Mungkin solusinya begini mas eddie dibuatkan saja menu atau smub menu khusus yg membahas maslah prodeskel di aplikasi OpenSID

**Comment by prabowoc6** [comment]
Mohon Maaf saya pengguna baru opensid, apabila sebaliknya data KK sudah di input ke prodeskel apa bisa di pakai untuk mengisi data awal di opensid, kalau bisa mohon bantuannya caranya bagaimana

**Comment by eddieridwan** [comment]
@prabowoc6 tempat bertanya penggunaan OpenSID di https://www.facebook.com/groups/OpenSID/. Issue digunakan untuk membahas penerapan suatu masalah/usulan.

**Comment by jogjasoftware** [comment]
DAPATKAN SOFTWARE "[**JS PRODESKEL**](https://jogjasoftware.com/software-komputer-prodeskel-cara-cepat-input-data-bip.html)" KEMENDAGRI ORIGINAL DARI KAMI. HATI-HATI PENIPUAN MENGATASNAMAKAN JOGJA SOFTWARE SEBAGAI DEVELOPER RESMI SOFTWARE "JS PRODESKEL". WHATSAPP: 0812-2222-032

**Comment by jogjasoftware** [comment]
> @metalab25 CD key bisa didapatkan setelah bedonasi opensud sama donasi ke saya buat pengembangan aplikasi prodeskel ini WA saya mas ya 083817343994

 HATI-HATI PENIPUAN MENGATASNAMAKAN JOGJA SOFTWARE SEBAGAI DEVELOPER RESMI SOFTWARE "JS PRODESKEL". WHATSAPP: 0812-2222-032

**Comment by nursanamar** [comment]
Jadi JS Prodeskel ini punyanya @jogjasoftware atau @anwargopro?
