### ISSUE TITLE
Bug pada rekam kehadiran merubah status keluar di jam kerja 

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#5951]
1. Lakukan absesn terlebih dahulu 
<img width="691" alt="image" src="https://user-images.githubusercontent.com/59082428/200975469-065d6e6e-2242-4077-b030-8a9e34d67b9f.png">

2. lalu misalhkan orang tersebut keluar / absensi pulng lebih awal misalhkan maka saya lakukan absensi pulang terlebih dahulu 
<img width="704" alt="image" src="https://user-images.githubusercontent.com/59082428/200975674-cda7d8a0-7e09-4212-afc6-a53d2f37aa71.png">

3. Lalu lihat terlebih dahulu statusnya di halaman depan  & admin 
<img width="803" alt="image" src="https://user-images.githubusercontent.com/59082428/200975744-09bb95ee-76ba-45e3-b181-d89c06268fb6.png">

<img width="713" alt="image" src="https://user-images.githubusercontent.com/59082428/200975905-19d65414-acad-4057-8372-f20f1333854c.png">

4. Lalu ketika jam kerja sudah berakhir, status tersebut apakah berubah menjadi Lupa Scan Keluar? atau tetap "Keluar"

Harusnya status tetap keluar dan status tidak berubah

**Comment by vickyrolanda** [comment]
Issue ini masih dibuat status cek issue karena saya uji coba sudah sesuai namun masih perlu di lakukan testing kembali.
pak @ariandii apakah di buat berubah statusnya menjadi lupa scan keluar ?

**Comment by ariandii** [comment]
jika status tetap pada rekam akhir, menurut saya status "keluar", diubah menjadi "tidak berada di kantor".

agar jika tidak kembali setelah keluar hingga jam pulang, agar tidak ambigu.

sehingga ada 3 status default:
1. belum rekam kehadiran
2. tidak berada dikantor
3. lupa scan pulang
4. info lain ketika keluar.

**Comment by vickyrolanda** [comment]
mas @devrakapriyo apakah sudah confirm ini mas ?

**Comment by devrakapriyo** [comment]
iya mas, saya setuju dengan masukan pak Ariandi

**Comment by vickyrolanda** [comment]
Begini mas @andifahruddinakas : 
1. Ketika absesi pulang padahal belum di jam pulang kantor maka statusnya "keluar"  - Status ini diubah menjadi "tidak berada dikantor" 
2. lalu ketika sudah di jam pulang kantor maka tidak perlu ubah status menjadi "lupa melapor keluar"  maka tetap saja "tidak berada dikantor"

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1872
