### ISSUE TITLE
Identitas desa tidak muncul ketika restore database dengan database umum

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#5953]
1. Lalukan install baru dengan database kosong
2. lalu lakukan resotore database dengan database umum 
3. maka ketika berhasil berhatikan ke  menu identitas desa 
<img width="948" alt="image" src="https://user-images.githubusercontent.com/59082428/200978116-61d4c3f2-e698-4803-abd5-b665b701f3d2.png">
4. Namun dibagian kairi atas nama desa sudah muncul 
<img width="465" alt="image" src="https://user-images.githubusercontent.com/59082428/200978168-f0d58cb9-70bb-472b-8d8f-42ca286d293f.png">

**Comment by andifahruddinakas** [comment]
> 1. Lalukan install baru dengan database kosong
> 2. lalu lakukan resotore database dengan database umum
> 3. maka ketika berhasil berhatikan ke  menu identitas desa
> 
> <img alt="image" width="948" src="https://user-images.githubusercontent.com/59082428/200978116-61d4c3f2-e698-4803-abd5-b665b701f3d2.png">
> 
> 4. Namun dibagian kairi atas nama desa sudah muncul
> <img alt="image" width="465" src="https://user-images.githubusercontent.com/59082428/200978168-f0d58cb9-70bb-472b-8d8f-42ca286d293f.png">

Proses ini harusnya tidak akan bisa, karena untuk restore perlu masukkan identitas desa dan token.

**Comment by andifahruddinakas** [comment]
Alur pindah dari umum ke premium tanpa install baru : 
1. Sebelum pindah, pada versi umum masukkan dlu token premium.
2. Lakukan update script dari umum ke premium.
3. Lakukan migrasi (Jika terdeteksi akan otomatis migrasi)

Alur pindah dari umum ke premium dengan install baru dan restore : 
1. Sebelum pindah, pada versi umum masukkan dlu token premium.
2. Lakukan backup database..
3. Lakukan install baru opensid premium dengan database baru.
4. Masukkan identitas desa dan token premium.
5. Masuk ke databse dan restore Database Umum.
6. Lakukan migrasi.

**Comment by andifahruddinakas** [comment]
> Alur pindah dari umum ke premium tanpa install baru :
> 
> 1. Sebelum pindah, pada versi umum masukkan dlu token premium.
> 2. Lakukan update script dari umum ke premium.
> 3. Lakukan migrasi (Jika terdeteksi akan otomatis migrasi)
> 
> Alur pindah dari umum ke premium dengan install baru dan restore :
> 
> 1. Sebelum pindah, pada versi umum masukkan dlu token premium.
> 2. Lakukan backup database..
> 3. Lakukan install baru opensid premium dengan database baru.
> 4. Masukkan identitas desa dan token premium.
> 5. Masuk ke databse dan restore Database Umum.
> 6. Lakukan migrasi.

Mas @devrakapriyo, bisa ditambahkan ke panduan.
