### ISSUE TITLE
form input pada surat menggunakan tinymce belum bisa panggil data dari data base

### ISSUE THREAD

**Issue by mranca** [OpenSID/OpenSID#5954]
### Jelaskan error yg dialami

nama pada form input pada surat yang menggunakan tinymce belum bisa panggil data dari database yang ada 

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

panggil data sesuai form input

### Tangkapan layar dan log error

![tinimce](https://user-images.githubusercontent.com/76085245/200979104-70fb8330-c576-4f31-9db4-6f3ee7ea04f1.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

22.11

### Tema Yang Digunakan

-

### Informasi tambahan

-

**Comment by andifahruddinakas** [comment]
Catatan : 
1. Kode isian orang tua yang lengkap hanya terisi jika data yang dipilih berada dalam 1 KK dan dengan SHDK adalah Anak

**Comment by vickyrolanda** [comment]
> Catatan :
> 
> 1. Kode isian orang tua yang lengkap hanya terisi jika data yang dipilih berada dalam 1 KK dan dengan SHDK adalah Anak

mas @devrakapriyo ini perlu di tambahkan di panduan kode isian ya mas.

**Comment by andifahruddinakas** [comment]
Untuk saat ini belum suppor untuk data yang diambil dari keluarga. Karena ada beberapa kondisi yang perlu di cek, jika penduduk : 
1. Tidak dalam KK maka data org tua diambil dari isian form penduduk
2. Penduduk dalam 1 KK, dengan status bukan anak data org tua diambil dari isian form penduduk
3. Penduduk dalam 1 KK, dengan status anak dengan KK adalah Laki-laki dan ada istri maka data diambil dari KK tsb
4. Penduduk dalam 1 KK, dengan status anak dengan KK adalah Laki-laki dan tidak ada istri maka data ayah diambil dari KK tapi data KK diambil dari form penduduk
5. Penduduk dalam 1 KK, dengan status anak dengan KK adalah Perempuan dan SDHDK ada suami (perlu ditanyakan kondisi ini) maka data diambil dari KK tsb
6. dll

**Comment by andifahruddinakas** [comment]
Sudah diterapkan diversi terbaru, v2307.0.0
