### ISSUE TITLE
Nomor Surat Tidak Tampil

### ISSUE THREAD

**Issue by pemdeslinggapura** [OpenSID/OpenSID#5959]
### Jelaskan error yg dialami

Nomor Surat tidak tampil di Surat RTF maupun Tinymce, bahkan di pengaturan surat juga blank

### Cara untuk mereplikasi errornya

1. Cetak Surat
2. Unduh RTF
3. Buka Surat
4. Nomor Surat tidak tampil

### Hasil yg diharapkan

Nomor Surat kembali tampil

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/89450861/201290633-2e5379a0-48bd-4f3e-8e27-5937c3c8c26b.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

V22.11-premium-rev01

### Tema Yang Digunakan

ESENSI

**Comment by andifahruddinakas** [comment]
Kondisi saat ini mengharuskan adanya user kades agar penomoran surat bisa aktif, mungkin dengan kondisi bahwa desa pengguna tsb menggunakan TTE. Tapi tidak semua desa menggunakan TTE, sehingga bagian pengaturan penomoran surat tidak diwajibkan harus ada user kades.

**Comment by andifahruddinakas** [comment]
Mas @vickyrolanda, dicek lagi kondisi tsb di atas..

**Comment by vickyrolanda** [comment]
> Mas @vickyrolanda, dicek lagi kondisi tsb di atas..

ok sudah sesuai dengan yang sudah ada di PR https://github.com/OpenSID/premium/pull/1598

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1598

**Comment by desasribhawono** [comment]
solusinya gimana ya pak? Terima kasih sebelumnya
