### ISSUE TITLE
Pencantuman Informasi Spesifikasi Minimum untuk Jalankan OpenSID

### ISSUE THREAD

**Issue by siayi** [OpenSID/OpenSID#596]
Sebaiknya dibuatkan Informasi Spesifikasi Minimum untuk Jalankan OpenSID, baik dijalankan secara offline ataupun online.

**Comment by eddieridwan** [comment]
Mungkin ditambahkan di [[Panduan-Install-OpenSID]]?

Kalau tidak salah, di panduan SID CRI ada info spesifikasi ini. Bagaimana bung @siayi , apakah anda bisa tambahkan info ini di panduan?

**Comment by MUHAMMADRANGSEL** [comment]
#closed
