### ISSUE TITLE
Bug/error: desa sid.guwosari.desa.id embed HTML di artikel response 403

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#5960]
### Jelaskan error yg dialami

desa sid.guwosari.desa.id mengalami response 403 saat menyisipkan embed HTML maupun mengupload link video atau gambar di artikel

<img width="1440" alt="Screen Shot 2022-11-11 at 17 23 38" src="https://user-images.githubusercontent.com/36557759/201320615-30fbf006-6ea4-4c22-a10e-1b462e63583e.png">

response setelah klik tombol Simpan

<img width="1440" alt="Screen Shot 2022-11-11 at 17 19 09" src="https://user-images.githubusercontent.com/36557759/201320663-f8044f1a-7fb6-450e-ae1e-42dc3c5ce06e.png">

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

setelah saya coba cek dengan di OpenSID nya mengalami hal serupa dan coba saya replikasikan di local dengan database desa tersebut mengalami gagal migrasi

<img width="1440" alt="Screen Shot 2022-11-11 at 17 26 37" src="https://user-images.githubusercontent.com/36557759/201321046-76684dba-7e9c-4a39-af8c-d7861709619d.png">

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.11-premium-rev1

**Comment by devrakapriyo** [comment]
terlampir link gdrive yang berisikan DB desa tersebut

https://drive.google.com/drive/folders/1W2G5rNpmopMGdMSwDq03p0R4j-ZiDqxH?usp=sharing

**Comment by andifahruddinakas** [comment]
mas @devrakapriyo, dari error yang terlihat di periksa database bukan masalah insert gambar artikel melainkan ke tidak lengkapan table/view. Jika ada 2 bug dalam 1 issue baiknya di pisah agar lebih jelas.

**Comment by andifahruddinakas** [comment]
Mas @devrakapriyo, untuk kasus artikel yang tidak dapat disimpan (404) sy coba di https://berputar.opendesa.id dan lokal tidak ada masalah tsb.

Coba cek : 
1. Tambahkan ulang view dokumen_hidup, bisa ambil dari contoh data hasil backup DB berputar.
2. Jika masih error, gunakan bug-fix terbaru.
3. Jika masih error, gunakan user utama (admin)

**Comment by devrakapriyo** [comment]
iya mas @andifahruddinakas ini issue embed HTML error yang di alami desa sid.guwosari.desa.id
sedangkan berputar dan di local menggunakan data desa lain normal

sepertinya ada perubahan dari stuktur database desa tersebut, karena saya coba replikasi menggunakan database desa desa sid.guwosari.desa.id mengalami error

**Comment by volla15** [comment]
saya update posisi rev-02 malah tidak bisa post artikel sama sekali, muncul 403

**Comment by vickyrolanda** [comment]
mohon bantuannya sesuai arahan mas akas ya mas @devrakapriyo  saat ini saya buatkan bukan bug krna terjadi di desa tersebut saja, jika ini terjadi di beberapa desa maka issue ini perlu dibuat menjadi bug.

**Comment by volla15** [comment]
DONE:

Mematikan fitur Mod Security di Cpannel

**Comment by eddieridwan** [comment]
> Mematikan fitur Mod Security di Cpannel

@volla15 tidak dianjurkan mematikan ModSecurity.

**Comment by volla15** [comment]
> ModSecurity

Sementara itu yang bisa saya lakukan untuk bisa embed media di artikel 🙏🏼🙏🏼🙏🏼
