### ISSUE TITLE
Bug/error: Tampilan anjungan berantakan

### ISSUE THREAD

**Issue by yogiperdana** [OpenSID/OpenSID#5961]
### Jelaskan error yg dialami

Tampilan anjungan berantakan

### Cara untuk mereplikasi errornya

Masuk ke halaman anjungan

### Hasil yg diharapkan

Normal

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/14155050/201366026-6ab0de8e-fc1c-4555-aed4-062441b077e0.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.11

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1593
