### ISSUE TITLE
Bug/error: Nilai Kolom Bobot Bila Tidak Terisi Minimal Nilai Nol Saat Disimpan Error 500

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#5963]
### Jelaskan error yg dialami

Nilai Kolom Bobot Bila Tidak Terisi Minimal Nilai Nol Saat Disimpan Error 500

### Cara untuk mereplikasi errornya

Buka Fitur --> Master Analisis
Buka Salah Satu --> Analisis --> Masuk Ke Fitur --> Indikator & Pertanyaan
Pilih --> Salah Satu Indikator & Pertanyaan --> Yg Bertipe Pertanyaan Pilihan Tunggal
Pada Kolom --> Bobot -->Kosongkan tak terisi (seolah tak sengaja atau memang mau dikosongkan)
Klik Simpan.

### Hasil yg diharapkan

Bila Kolom Bobot-nya di Kosongkan Saat diklik tombol simpan --> Data Tidak boleh disimpan dan tidak menampilkan pesan error dengan Notifikasi Kolom Bobot belum terisi-->seperti notifikasi menolah karakter tertentu yg tidak dibolehkan terisi..

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/64481641/201451938-26a6fef5-653a-464e-ab17-1f6eb5f7993f.png)

![image](https://user-images.githubusercontent.com/64481641/201451912-52efd7a8-f137-4a1d-ac99-c0bb3e22aa98.png)

![image](https://user-images.githubusercontent.com/64481641/201451922-995e20c2-fab2-4060-849e-d4ce874ad71e.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

OpenSID Premium V22.11

### Tema Yang Digunakan

All

### Informasi tambahan

.

**Comment by andifahruddinakas** [comment]
Pak @Zoel-WB, coba periksa tabel analisis_indikator, cek bagian bobot apakah sudah sesuai dgn gambar berikut (nilai default adalah '0') ?

![analisis 1](https://user-images.githubusercontent.com/57283157/201533638-a90ddfd9-e649-48bf-8056-ad2827c682fd.jpg)

**Comment by Zoel-WB** [comment]
> Pak @Zoel-WB, coba periksa tabel analisis_indikator, cek bagian bobot apakah sudah sesuai dgn gambar berikut (nilai default adalah '0') ?
> 
> ![analisis 1](https://user-images.githubusercontent.com/57283157/201533638-a90ddfd9-e649-48bf-8056-ad2827c682fd.jpg)

Baik pak @andifahruddinakas

**Comment by Zoel-WB** [comment]
Iya benar pak
![image](https://user-images.githubusercontent.com/64481641/201533954-294059bf-9c61-41b8-bd89-adee328e266e.png)

**Comment by andifahruddinakas** [comment]
Solusi : 
Tambahkan required

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1596
