### ISSUE TITLE
Bug/error: Jumlah Surat Tercetak Tidak Dapat Ditampilkan di Arsip Layanan Surat Jika Login Pengguna Administrator Tambahan

### ISSUE THREAD

**Issue by mah-mudi** [OpenSID/OpenSID#5964]
### Jelaskan error yg dialami

Jumlah Surat Tercetak Tidak Dapat Ditampilkan di Arsip Layanan Surat ketika pengguna group Administrator Tambahan Login.
Jika Login dengan admin yang bawaan sistem bisa keluar rekapitulasi nya.

### Cara untuk mereplikasi errornya

Pilih Home. Terdapat Rekapitulasi Jumlah Surat Tercetak. Misal ini ada 8 Surat.
![is1](https://user-images.githubusercontent.com/57661283/201456250-11fd2938-4c4d-4240-afd7-b936997bf474.png)
Ke Modul Layanan Surat- Arsip Layanan tertulis 0 jika login dengan pengguna administrator selain admin sistem misal atas nama MAHMUDI.
![is2](https://user-images.githubusercontent.com/57661283/201456385-b01695db-e272-45fd-a4d2-524df062a9d1.png)

sedangan admin bawaan atas nama Administrator dapat menampilkan rekapitulasinya.
![image](https://user-images.githubusercontent.com/57661283/201457761-f13af473-15de-4f19-aa13-0379d09df44e.png)

### Hasil yg diharapkan

Surat Yang Tercetak, dapat terekap dengan benar di pengguna yang ditunjuk administrotor selain bawaan sistem OpenSID.

### Tangkapan layar dan log error
ini Screenshot dari login Pengguna lain yang administrator.
![is1](https://user-images.githubusercontent.com/57661283/201456250-11fd2938-4c4d-4240-afd7-b936997bf474.png)

tidak tampil rekapitulasinya.
![is2](https://user-images.githubusercontent.com/57661283/201456385-b01695db-e272-45fd-a4d2-524df062a9d1.png)

Sedangkan ini login pengguna administrator dari sistem bawaan. dapat tampil rekapitulasinya.
![image](https://user-images.githubusercontent.com/57661283/201457810-adb6112c-4c07-48b7-9de5-ead3575c2d48.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

22.11 Premium rev01

### Tema Yang Digunakan

silir 3.6.3

### Informasi tambahan

-

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1602
