### ISSUE TITLE
Bug/error: Belum Lengkap nya Hubungan Keluarga ketika Tambah Anggota KK

### ISSUE THREAD

**Issue by mah-mudi** [OpenSID/OpenSID#5965]
### Jelaskan error yg dialami

Belum Lengkap nya Hubungan Keluarga ketika Tambah Anggota KK dari Penduduk yang sudah ada
hanya ada pilihan Orang Tua, Famili, Pembantu, Lainnya

### Cara untuk mereplikasi errornya

Modul Keluarga - Tambah Anggota dari Penduduk yang sudah Ada - Hubungan Keluarga

### Hasil yg diharapkan

Ketika Memilih Hubungan Keluarga dapat memilih secara detail seperti ubah hubungan keluarga.
Perlu penambahan opsi hubungan keluarga seperti Suami, Istri, Anak, Cucu, Menantu, Mertua.
sehingga penginputan lebih cepat. tidak mengubah lagi lewat ubah hubungan keluarga.

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/57661283/201456849-99bcd5b2-9f3f-4627-9ed6-e63416fe86c9.png)
![image](https://user-images.githubusercontent.com/57661283/201456856-0ce3b582-0229-4ae1-acd0-a52fce0d1c17.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

22.11 Premium rev01

### Tema Yang Digunakan

silir 3.6.3

**Comment by ariandii** [comment]
saya coba tambahkan keluarga di halaman daftar anggota keluarga, muncul normal lengkap seluruh  hubungan keluarga.

**Comment by mah-mudi** [comment]
iya pak keluar lengkap hari ini, dulu keluar tidak lengkap :-)
ok aku close aja issues ini
