### ISSUE TITLE
Bug/error: desa pampangan-lambar.desa.id data rumah tangga hilang

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#5966]
### Jelaskan error yg dialami

desa pampangan-lambar.desa.id mengalami kehilangan data rumah tangga setelah update ke versi 22.11-premium-rev1
setelah saya cek data rumah tangga masih ada hanya saja setelah klik menu rumah tangga https://pampangan-lambar.desa.id/rtm/clear data rumah tangga menjadi hilang

<img width="1440" alt="Screen Shot 2022-11-12 at 11 01 20" src="https://user-images.githubusercontent.com/36557759/201459032-d13108bb-344a-4ddc-a984-aec86575175e.png">

**video replikasi berdasarkan screen recording : https://drive.google.com/file/d/1YQVzmd9livZw5a54u0anA2tpCvEe7DpH/view?usp=share_link**

### Cara untuk mereplikasi errornya

langkah-langkah replikasi

1. masuk ke dashboard admin
2. masuk ke menu rumah tangga dan hasilnya (data rumah tangga kosong)
3. logout
4. masuk ke halaman rumah tangga https://pampangan-lambar.desa.id/rtm setelah itu di minta login
5. maka data rumah tangga akan muncul kembali
6. jika kita refresh data rumah tangga masih muncul
7. jika kita klik menu rumah tangga https://pampangan-lambar.desa.id/rtm/clear maka (data rumah tangga kosong)

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.11-premium-rev1

**Comment by devrakapriyo** [comment]
database desa terlampir di link GDrive OpenDesa : https://drive.google.com/drive/folders/1n5_07EfYFXYqsmZ1BznSMA-sLUPzhoyU?usp=sharing

**Comment by mranca** [comment]
ini sama dengan issue yang pertama saya buat #5935

**Comment by andifahruddinakas** [comment]
Setelah di cek, data rumah tangga di tweb_penduduk (id_rtm dan rtm_level) berisikan data yang sama hampir semua data penduduk.

![tweb_penduduk rtm](https://user-images.githubusercontent.com/57283157/201580756-fd1d1dec-82f7-49b0-995c-e4e946e98258.jpg)

Untuk mengecek apakah ini perubahan dari proses migrasi, perlu disediakan database versi sebelumnya. @devrakapriyo

**Comment by devrakapriyo** [comment]
mas @andifahruddinakas ini DB sebelum update https://drive.google.com/file/d/1XadLkn4NCGRVJAx1Dw_B-A814iNOWYn_/view?usp=share_link

**Comment by andifahruddinakas** [comment]
Dari pak @zoel, saya belum tahu kejadian dimana karena ada 3 operasi yg saya lakukan, letak salah saya tidak tahu dimana dan opasi yg mana yg menyebabkan salah?  (1) Perinah Pertama  Keluarkan Anggota rumah tanggal dan buat rumah tangga baru sekaligus input anggota keluarga kebetulan bisa conteng semua, semua saya conteng, (2) Perintah Kedua saya input satu keluarga (kepala Keluargaa dan satu anak) kebetulan belum dimasukkan ke salah satu rumah tanggal, saya pilih tambah anggota rumah tangga salah satu rumah tangga, dan dimasukkan data tambah anggota rumah tangga (3) Ketiga ada salah satu Anggota rumah tangga beda KK baru pulang ke desa--> saya tambahkan ke salah satu rumah tangga induk.

Kemudian saya buka dasboard —> semua data rumah tangga menjadi kosong,  saya masuk ke fitur rumah tangga kembali, ternyata juga sudah tidak ditampilkan lagi listnya....

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1632

solusinya Data pengguna yang berubah, yang bisa dikembalikan hanyalah kepala RT karena data anggota tidak ada riwayatnya pada tabel tweb_rtm dan di tweb_penduduk hanya menyimpan id_rtm yang dimana sudah berubah semua (sama).
