### ISSUE TITLE
Statistik Pengujung Hari Ini selalu GENAP

### ISSUE THREAD

**Issue by kbrozi** [OpenSID/OpenSID#5967]
### Jelaskan error yg dialami

Statistik Pengunjungb Hari ini selalu menghasilkan angka genap. Yang dulu pernah sempat berurutan 1 2 3 4 5 6 dst, ganjil genap.

### Cara untuk mereplikasi errornya

Statistik Pengunjung Hari Ini

### Hasil yg diharapkan

Angka pengunjung hari ini berurutan, 1 2 3 4 5 6 dst

### Tangkapan layar dan log error

![IMG_20221113_074108](https://user-images.githubusercontent.com/116752256/201499441-2099a271-64a7-4ebc-a120-e808b299e108.jpg)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.11-premium-rev01

### Tema Yang Digunakan

DeNatra v8.1

**Comment by ariandii** [comment]
bisa karena kebetulan saja. karena hal ini tidak terjadi di berbagai tempat.

tetap berurutan sesuai pengunjung.

**Comment by kbrozi** [comment]
saya lakukan dari sisi localhost, pembukaan awal langsung angka 2 (dua) yang dihasilkan
sehahurnya angka 1 terlebih dahulu, setelah itu baru angka 2 dst.

**Comment by andifahruddinakas** [comment]
Mas @devrakapriyo, saya cek di lokal tidak masalah.

![statistik](https://user-images.githubusercontent.com/57283157/201581859-993adf79-3f9a-4487-8400-17c339dc5c4d.jpg)

**Comment by ariandii** [comment]
![IMG_20221114_155906](https://user-images.githubusercontent.com/46939846/201618115-143d86ce-bd90-4d8a-bcff-eca84674516a.jpg)

![IMG_20221114_155913](https://user-images.githubusercontent.com/46939846/201618135-0a2c6c02-9a21-407a-8f84-7601723076f9.jpg)

saya cek online barusan hasilnya urut. buka ganjil. setelah itu genap.

**Comment by Zoel-WB** [comment]
Apakah ada hubungan dengan .htaccess, setingan saya sekali login juga muncul 2 visitors perkiraan saya di setinggan .htaccess-nya, karena menggabungkan sekali login bisa sekalian dua domain...... 

![image](https://user-images.githubusercontent.com/64481641/202378600-3f226d26-c10b-4816-a772-04208ddea15d.png)

**Comment by vickyrolanda** [comment]
saya coba juga tidak ada masalah pak : 
<img width="240" alt="image" src="https://user-images.githubusercontent.com/59082428/202891844-cb70d5a8-b90f-42f8-8e13-581c1a993454.png">
