### ISSUE TITLE
Fitur ubah favicon di OpenSID pencarian google

### ISSUE THREAD

**Issue by kbrozi** [OpenSID/OpenSID#5968]
### Apa kekurangan yg ingin diatasi?

Penampakan favicon pada pencarian website 
desa di google masih logo bawaan aplikasi, sehingga logo desa tidak nampak.

### Jelaskan solusi yg diinginkan

![IMG_20221113_082033](https://user-images.githubusercontent.com/116752256/201499781-3b61fa03-cffb-49bb-9c7a-4d88610e199d.jpg)

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

v22.12-premium

**Comment by andifahruddinakas** [comment]
otomatis diambil dari logo
