### ISSUE TITLE
Fitur Update OpenSID

### ISSUE THREAD

**Issue by siayi** [OpenSID/OpenSID#597]
Apakah memungkinkan jika OpenSID memiliki fitur update seperti Wordpress pasca 2.7  
https://codex.wordpress.org/Updating_WordPress , khususnya fitur One-click Update.
Ditambah fitur semacam pemberitahuan, bahwa ada release (update) terbaru.

**Comment by hadyanwijaya** [comment]
kalau pemberitahuan bisa cepet dikerjakan, kalau auto upgrade harus rombak banyak file... musti sabar ya

**Comment by suphm** [comment]
bagus ini. di tracksid masih banyak pengguna versi yang lama, ga di-update

**Comment by siayi** [comment]
repo ini https://github.com/esyede/opensid-updater sepertinya terkait dgn issue

**Comment by afa28** [comment]
Untuk fitur update pd dashboard ini, mungkin fiturnya bisa dibuat upload. (alternatif)

Tp untuk saat ini sudah disediakan tutorial yg lebih mudah untuk update menggunakan git baik offline maupun online.

**Comment by afa28** [comment]
Untuk fitur notifikasi update versi opensid terbaru sudah tersedia di versi terbaru. Tp untuk mengupdatenya sendiri tetap harus upload manual.

Tp untuk saat ini sudah disediakan tutorial yg lebih mudah untuk update menggunakan git baik offline maupun online.
