### ISSUE TITLE
Bug/error: Selalu muncul notifikasi belum ditentukan ketika jabatan dihapus

### ISSUE THREAD

**Issue by yogiperdana** [OpenSID/OpenSID#5970]
### Jelaskan error yg dialami

Selalu muncul notifikasi belum ditentukan ketika jabatan dihapus

### Cara untuk mereplikasi errornya

Jabatan bawaan dihapus lewat database dan lakukan cetak surat

### Hasil yg diharapkan

Berjalan normal

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/14155050/201507813-7551545c-ca53-43ac-802f-a4755c649540.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.11

**Comment by andifahruddinakas** [comment]
Seharusnya tidak melakukan perubahan manual lewat database.

**Comment by andifahruddinakas** [comment]
Solusi : 
tambahkan ulang data jabatan kades (1) danatau sekdes (2) jika tidak ditemukan

**Comment by eddieridwan** [comment]
@andifahruddinakas @yogiperdana @vickyrolanda @devrakapriyo hal2 seperti ini, di mana isi database tidak sesuai ketentuan, sebaiknya ditangani secara konsisten melalui fitur periksa->perbaiki yg sudah ada. Yaitu tidak dibuat penanganan khusus yg berbeda.

Selain itu, dari penjelasan @ariandii terlihat akar permasalahannya adalah kebutuhan pengguna untuk mengubah penulisan jabatan menjadi huruf besar semua. Jadi kebutuhan itu juga harus ditangani juga jika tidak ingin kasus berulang. Yaitu, perlu disediakan fitur untuk mengubah penulisan 'case' nama jabatan.

Jangan lupa, selalu tindak lanjuti akar permasalahan, tidak saja gejala.

**Comment by eddieridwan** [comment]
@andifahruddinakas @yogiperdana @vickyrolanda @devrakapriyo perhatikan juga prinsip kerja kita, yaitu tidak 'memperbaiki' masalah yg disebabkan pengguna membuat ubahan sistem, termasuk jika pengguna melakukan perubahan database secara manual. Karena kasus2 seperti itu tidak terbatas jenisnya, dan perbaikannya merupakan penggunaan waktu programmer yg sangat tidak produktif, karena hanya mengatasi hal2 yg seharusnya tidak terjadi. 

Jadi dalam kasus ini, langkah yg seharusnya teman2 lakukan adalah sbb:

1. Jelaskan pada pengguna, bahwa perubahan sistem (script atau database) adalah atas resiko sendiri, dan OpenDesa tidak akan membuat perubahan sistem khusus untuk itu. Ingatkan pengguna untuk jangan sekali-kali melakukan perubahan sistem, kecuali bersedia mengatasi masalah sendiri.
2. Jika melakukan perubahan database, pengguna disarankan restore ke backup sebelumnya. Jika perubahan sistem, kembalikan ke script asli.
3. Cari akar permasalahannya; yaitu mengapa pengguna merasa perlu melakukan. Buat issue untuk mengatasi itu, dalam kasus ini menyediakan cara untuk mengubah penulisan nama jabatan.

Harap ke depan, terapkan prinsip di atas secara konsisten. @vickyrolanda harap anda tambahkan itu ke panduan untuk perhatian tester, analis dan programmer.

**Comment by vickyrolanda** [comment]
> @andifahruddinakas @yogiperdana @vickyrolanda @devrakapriyo perhatikan juga prinsip kerja kita, yaitu tidak 'memperbaiki' masalah yg disebabkan pengguna membuat ubahan sistem, termasuk jika pengguna melakukan perubahan database secara manual. Karena kasus2 seperti itu tidak terbatas jenisnya, dan perbaikannya merupakan penggunaan waktu programmer yg sangat tidak produktif, karena hanya mengatasi hal2 yg seharusnya tidak terjadi.
> 
> Jadi dalam kasus ini, langkah yg seharusnya teman2 lakukan adalah sbb:
> 
> 1. Jelaskan pada pengguna, bahwa perubahan sistem (script atau database) adalah atas resiko sendiri, dan OpenDesa tidak akan membuat perubahan sistem khusus untuk itu. Ingatkan pengguna untuk jangan sekali-kali melakukan perubahan sistem, kecuali bersedia mengatasi masalah sendiri.
> 2. Jika melakukan perubahan database, pengguna disarankan restore ke backup sebelumnya. Jika perubahan sistem, kembalikan ke script asli.
> 3. Cari akar permasalahannya; yaitu mengapa pengguna merasa perlu melakukan. Buat issue untuk mengatasi itu, dalam kasus ini menyediakan cara untuk mengubah penulisan nama jabatan.
> 
> Harap ke depan, terapkan prinsip di atas secara konsisten. @vickyrolanda harap anda tambahkan itu ke panduan untuk perhatian tester, analis dan programmer.

baik pak.  sudah sy tambahkan disini  pak https://github.com/OpenSID/OpenSID/wiki/Tanya-Jawab-Tentang-Bug

**Comment by andifahruddinakas** [comment]
> @andifahruddinakas @yogiperdana @vickyrolanda @devrakapriyo perhatikan juga prinsip kerja kita, yaitu tidak 'memperbaiki' masalah yg disebabkan pengguna membuat ubahan sistem, termasuk jika pengguna melakukan perubahan database secara manual. Karena kasus2 seperti itu tidak terbatas jenisnya, dan perbaikannya merupakan penggunaan waktu programmer yg sangat tidak produktif, karena hanya mengatasi hal2 yg seharusnya tidak terjadi.
> 
> Jadi dalam kasus ini, langkah yg seharusnya teman2 lakukan adalah sbb:
> 
> 1. Jelaskan pada pengguna, bahwa perubahan sistem (script atau database) adalah atas resiko sendiri, dan OpenDesa tidak akan membuat perubahan sistem khusus untuk itu. Ingatkan pengguna untuk jangan sekali-kali melakukan perubahan sistem, kecuali bersedia mengatasi masalah sendiri.
> 2. Jika melakukan perubahan database, pengguna disarankan restore ke backup sebelumnya. Jika perubahan sistem, kembalikan ke script asli.
> 3. Cari akar permasalahannya; yaitu mengapa pengguna merasa perlu melakukan. Buat issue untuk mengatasi itu, dalam kasus ini menyediakan cara untuk mengubah penulisan nama jabatan.
> 
> Harap ke depan, terapkan prinsip di atas secara konsisten. @vickyrolanda harap anda tambahkan itu ke panduan untuk perhatian tester, analis dan programmer.

Point 3 sudah ada, sejak awal adanya modul ini : 
![JABATAN 1](https://user-images.githubusercontent.com/57283157/201560958-a59da960-f341-40b9-a044-55062cf7de66.jpg)
![JABATAN 2](https://user-images.githubusercontent.com/57283157/201560953-a2d6abc8-4899-429d-9c4c-5082022ba231.jpg)
![JABATAN 3](https://user-images.githubusercontent.com/57283157/201560948-7a7b2a06-51e3-42e4-9f28-bbb59436da47.jpg)

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1594

**Comment by vickyrolanda** [comment]
mas @devrakapriyo ini bug dan solusi khusus untuk jabatan yang terhapus atau di hapus, bsia tambahkan panduannya di https://github.com/OpenSID/OpenSID/wiki/Tanya-Jawab-Tentang-Bug dan buatkan jga di forum mas. 
solusinya jika terjadi hal seperti ini : 
1. Jalankan url periksa untuk memberbaiki data jabatan sekdes & kades.

**Comment by eddieridwan** [comment]
> Point 3 sudah ada, sejak awal adanya modul ini :

@andifahruddinakas, menggantikan semua menjadi huruf besar bukan solusinya, jika ada pengguna lain yg menginginkan Title Case, bukan huruf besar semuanya.

@vickyrolanda @devrakapriyo saya lihat sdh ditutup. Apakah akar permasalahannya sdh ditindaklanjuti, yaitu dapat mengubah case nama jabatan bawaan dapat diubah?

**Comment by andifahruddinakas** [comment]
> > Point 3 sudah ada, sejak awal adanya modul ini :
> 
> @andifahruddinakas, menggantikan semua menjadi huruf besar bukan solusinya, jika ada pengguna lain yg menginginkan Title Case, bukan huruf besar semuanya.
> 
> @vickyrolanda @devrakapriyo saya lihat sdh ditutup. Apakah akar permasalahannya sdh ditindaklanjuti, yaitu dapat mengubah case nama jabatan bawaan dapat diubah?

Jabatan baik itu huruf besar, kecil, dll sesuai dengan yang di input. Tidak ada yang diubah, masih sama seperti dlu.

**Comment by eddieridwan** [comment]
> Jabatan baik itu huruf besar, kecil, dll sesuai dengan yang di input. Tidak ada yang diubah, masih sama seperti dlu.

@andifahruddinakas apakah pengguna dapat mengubah penulisan jabatan bawaan tanpa masuk ke PHPMyadmin? Kalau tidak bisa, perlu ada issuenya. Itu akar permasalahannya.

**Comment by andifahruddinakas** [comment]
> > Jabatan baik itu huruf besar, kecil, dll sesuai dengan yang di input. Tidak ada yang diubah, masih sama seperti dlu.
> 
> @andifahruddinakas apakah pengguna dapat mengubah penulisan jabatan bawaan tanpa masuk ke PHPMyadmin? Kalau tidak bisa, perlu ada issuenya. Itu akar permasalahannya. 

Sudah tersedia diawal modul di buat, agar pengguna bisa menyelesaikan sendiri sebutannya atau huruf besar kecilnya.

**Comment by eddieridwan** [comment]
> Sudah tersedia diawal modul di buat, agar pengguna bisa menyelesaikan sendiri sebutannya atau huruf besar kecilnya.

@andifahruddinakas jadi mengapa pengguna merasa perlu menghapus jabatan yg ada? Apakah tidak tahu cara menyesuaikan atau alasan lain? @devrakapriyo @vickyrolanda

**Comment by andifahruddinakas** [comment]
> > Sudah tersedia diawal modul di buat, agar pengguna bisa menyelesaikan sendiri sebutannya atau huruf besar kecilnya.
> 
> @andifahruddinakas jadi mengapa pengguna merasa perlu menghapus jabatan yg ada? Apakah tidak tahu cara menyesuaikan atau alasan lain? @devrakapriyo @vickyrolanda

Sy kurang mengerti mengapa mereka hapus. Mungkin alurnya begini megapa mereka lakukan hapus melalui database.
1. Mereka mendambahkan jabatan baru untuk kades maupun sekdes (tidak mengubah yang sudah ada)
2. Kemudian menyesuaikannya di pengurus.
3. Saat melakukan cetak / lainnya yang memerlukan data kades / sekdes data tidak tampil. (krn tidak mengikuti aturan yg ada).
4. Dikepala mereka mungkin karena adanya 2 jabatan yang sama jadi tidak bisa kepanggil, jadi harus dihapus salah 1 nya. Tapi karena tidak bisa hapus salah jabatan tsb mereka hapus melalui phpmyadmin scr langsung.

Anggapa asy alur sampai muncul knp jabatan bawaan hilang seperti diatas, mungkin di issue perlu dijelaskan lebih detail mengapa issue tsb terjadi.

Untuk mengurangi kesalah pahaman penggunaan suatu fitur baiknya dibuatkan pandua serta penjelasan penting didalamnya.

**Comment by eddieridwan** [comment]
@devrakapriyo pastikan yg dibahas di atas sudah jelas dan lengkap di panduan

**Comment by devrakapriyo** [comment]
saya setuju dengan pendapat mas @andifahruddinakas seharusnya jabatan default (kades dan sekdes) tidak boleh di hapus apalagi melalui database

solusinya : saya lengkapi di panduan dan di forum
