### ISSUE TITLE
Permintaan fitur: Tambahkan ukuran huruf 9pt 11pt 16pt 20pt 22pt pada Template Pengaturan Surat

### ISSUE THREAD

**Issue by mah-mudi** [OpenSID/OpenSID#5971]
### Apa kekurangan yg ingin diatasi?

Belum adanya ukuran huruf 9pt 11pt 16pt 20pt 22pt pada Template Pengaturan Surat
![image](https://user-images.githubusercontent.com/57661283/201513736-30e32793-ecfc-4c2e-a238-0c15bf323966.png)

### Jelaskan solusi yg diinginkan

Tersedianya  ukuran huruf 9pt 11pt 16pt 20pt 22pt pada Template Pengaturan Surat

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

22.11 Premium rev01

### Informasi tambahan

-

**Comment by cwicaksono** [comment]
Issue ini ada di repository public atau premium ya

**Comment by mah-mudi** [comment]
premium
berputar.opensid.id
