### ISSUE TITLE
Bug/error: Perbaiki Footer Surat TinyMCE

### ISSUE THREAD

**Issue by mah-mudi** [OpenSID/OpenSID#5979]
### Jelaskan error yg dialami

Redaksi Footer yang diatur bertuliskan Dokumen ini tertanda ditandatangani secara elektronik menggunakan sertifikat elektronik yang **diterbitkan** BSrE.

Tapi yang muncul Dokumen ini tertanda ditandatangani secara elektronik menggunakan sertifikat elektronik yang **diterbiTKan** BSrE.

### Cara untuk mereplikasi errornya

Settingan Footer
![footer](https://user-images.githubusercontent.com/57661283/201557233-c457b775-487d-43e2-9e76-6c50bd6f1bcc.png)

Sedangkan yang keluar seperti ini
![image](https://user-images.githubusercontent.com/57661283/201557280-4a7b1cc9-2a77-46be-9771-f1dc1c2f1de6.png)

### Hasil yg diharapkan

Ubah Tulisan Dokumen ini tertanda ditandatangani secara elektronik menggunakan sertifikat elektronik yang **diterbiTKan** BSrE.

menjadi 

Dokumen ini tertanda ditandatangani secara elektronik menggunakan sertifikat elektronik yang **diterbitkan** BSrE.

redaksi diterbiTKan diubah menjadi diterbitkan.

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

22.11 Premium rev01

### Tema Yang Digunakan

Esensi v22.11

### Informasi tambahan

-

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1601
