### ISSUE TITLE
Bug/error: 

### ISSUE THREAD

**Issue by ElAndea** [OpenSID/OpenSID#5980]
### Jelaskan error yg dialami

Saat cetak surat kelahiran, hari kelahiran tidak sesuai dengan tanggal kelahiran

### Cara untuk mereplikasi errornya

hasil cetak surat keterangan kelahiran pada hari kelahiran tidak sesuai dengan tanggal kelahiran

### Hasil yg diharapkan

Saat cetak surat keterangan kelahiran diharapkan hari kelahiran sesuai dengan tanggal kelahiran

### Tangkapan layar dan log error

tidak ada

### Rilis Versi OpenSID

Rilis Umum

### Versi OpenSID

22.11

### Tema Yang Digunakan

tema silir

### Informasi tambahan

tidak ada

**Comment by andifahruddinakas** [comment]
Mas @devrakapriyo, ini sama issuenya dengan https://github.com/OpenSID/OpenSID/issues/5224 dan sudah diperbaiki.

**Comment by vickyrolanda** [comment]
saya coba juga sudah sesuai : 
<img width="701" alt="image" src="https://user-images.githubusercontent.com/59082428/202891973-46d3d1a3-8a65-437e-b3c6-7044d50fe878.png">
<img width="551" alt="image" src="https://user-images.githubusercontent.com/59082428/202891978-4fa68d81-ef04-44f4-be6b-6a95f25b2fb3.png">

jika masih terjadi hal yang sama mohon untuk lampirkan screenshotnya pak @ElAndea  agar dapat di lihat dan di testing
