### ISSUE TITLE
nama pamong yang ttd tidak tampil di lampiran surat

### ISSUE THREAD

**Issue by ElAndea** [OpenSID/OpenSID#5981]
### Jelaskan error yg dialami

saat surat dicetak nama pamong yang ttd tidak tampil, ini khusus utk lampirannya sj. seperti contoh lampiran surat perubahan kk baru f-1.16.

### Cara untuk mereplikasi errornya

tidak ada

### Hasil yg diharapkan

nama pamong yang ttd tampil sebagaimana mestinya

### Tangkapan layar dan log error

tidak ada

### Rilis Versi OpenSID

Rilis Umum

### Versi OpenSID

22.11

### Tema Yang Digunakan

tema silir

### Informasi tambahan

tidak ada

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1607
