### ISSUE TITLE
Bug/error:  Kolom "Cari" Fitur Stunting Tidak Berfungsi

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#5982]
### Jelaskan error yg dialami

1. Saat Mencari data  yg ada melalui kolom Cari, system tidak respon terjadi pada Fitur -->Posyandu --.Kesehatan Ibu dan Anak (KIA)

2. Kolom Cari pada Fitur Pemantauan Bulanan ---> Klik terjadi Error (Seperti Tampak pada screensote)

### Cara untuk mereplikasi errornya

.

### Hasil yg diharapkan

Supaya dapat digunakan dan berfungsi

### Tangkapan layar dan log error

1. Pada Fitur Posyandu "Kesehatan Ibu dan Anak (KIA)

![image](https://user-images.githubusercontent.com/64481641/201653202-e42a1e0f-db2a-46e0-8773-335067298190.png)

2. Pada Fitur --> Pemantauan Bulanan 

![image](https://user-images.githubusercontent.com/64481641/201653375-e70eb503-1c72-4781-b995-f750b460237c.png)

3. Pemberitahuan Log Eror

Severity: error --> Exception: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'ibu_hamil.tanggal_periksa' in 'where clause' (SQL: select count(*) as aggregate from `ibu_hamil` where (exists (select * from `kia` where `ibu_hamil`.`kia_id` = `kia`.`id` and LOWER(`kia`.`no_kia`) LIKE %mi%) or
xists (select * from `kia` where `ibu_hamil`.`kia_id` = `kia`.`id` and exists (select * from `tweb_penduduk` where `kia`.`ibu_id` = `tweb_penduduk`.`id` and LOWER(`tweb_penduduk`.`nama`) LIKE %mi%)) or LOWER(`ibu_hamil`.`tanggal_periksa`) LIKE %mi% or LOWER(`ibu_hamil`.`status_kehamilan`) LIKE %mi% or exists (select * from `kia` where `ibu_hamil`.`kia_id` = `kia`.`id` and LOWER(`kia`.`hari_perkiraan_lahir`) LIKE %mi%) or LOWER(`ibu_hamil`.`usia_kehamilan`) LIKE %mi% or LOWER(`ibu_hamil`.`tanggal_melahirkan`) LIKE %mi% or LOWER(`ibu_hamil`.`pemeriksaan_kehamilan`) LIKE %mi% or LOWER(`ibu_hamil`.`konsumsi_pil_fe`) LIKE %mi% or LOWER(`ibu_hamil`.`pemeriksaan_nifas`) LIKE %mi% or LOWER(`ibu_hamil`.`konseling_gizi`) LIKE %mi% or LOWER(`ibu_hamil`.`kunjungan_rumah`) LIKE %mi% or LOWER(`ibu_hamil`.`akses_air_bersih`) LIKE %mi% or LOWER(`ibu_hamil`.`kepemilikan_jamban`) LIKE %mi% or LOWER(`ibu_hamil`.`jaminan_kesehatan`) LIKE %mi%)) /home/teupinbe/public_html/vendor/illuminate/database/Connection.php 712

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

OpenSID Premium V22.11

### Tema Yang Digunakan

standard

### Informasi tambahan

.

**Comment by andifahruddinakas** [comment]
mas @ruririzal, bisa komentar ke issue ini biar bisa di asign.

**Comment by ruririzal** [comment]
Oke

**Comment by ruririzal** [comment]
> mas @ruririzal, bisa komentar ke issue ini biar bisa di asign.

Sudah mas @andifahruddinakas

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1604
