### ISSUE TITLE
Bug/error: Fitur Stunting pada Fitur Input Data Ibu Hamil -->Kolom Tanggal Perkiraan Lahir harus terisi

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#5983]
### Jelaskan error yg dialami

Saat Input data Ibu Hamil, bila kolom Hari Perkiraan Lahir -->dikosongkan-->data-->tidak dapat disimpan

 
![image](https://user-images.githubusercontent.com/64481641/201655129-888b1c5f-d959-4792-aed2-2f6907a3b93d.png)

### Cara untuk mereplikasi errornya

.

### Hasil yg diharapkan

Untuk data Ibu hamil pada kolom Hari Pekiraan Lahir -> harus ada 2 alternatif, di input atau tidak di input --> harus tetap dapat disimpan, karena alasannya yg memasukkan data bisa saja di masukkan oleh Operator SID desa -> Baru kemudian di serahkan ke Posyandu untuk kegiataannya dan pemantauannya,

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/64481641/201655741-9b1e7fd0-a163-4753-891c-472c8d630b84.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

OpenSID Premium V22.11

### Tema Yang Digunakan

standard

### Informasi tambahan

.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1637
