### ISSUE TITLE
Bug/error:  Tampilan data Ibu Pada Fitur Posyandu-->Kesehatan Ibu dan Anak (KIA) menampilkan kesan Data Ganda

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#5984]
### Jelaskan error yg dialami

Tampilan data Ibu Pada Fitur Posyandu-->Kesehatan Ibu dan Anak (KIA) menampilkan kesan Ganda

![image](https://user-images.githubusercontent.com/64481641/201656634-5bc17307-36bb-4731-8b0d-290c97f35009.png)

### Cara untuk mereplikasi errornya

.

### Hasil yg diharapkan

Memisahkan Data masing bagian tersendiri:
1. Khusus Untuk Fitur Data Ibu Saja.
2. Khusus Data Anak/Balita

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/64481641/201656993-6004a880-b344-4a0c-a37d-abd438341739.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

OpenSID Premium V22.11

### Tema Yang Digunakan

standard

### Informasi tambahan

.

**Comment by agungsugiarto** [comment]
pak @Zoel-WB bisa kirim backup databasenya ke telegram saya

**Comment by vickyrolanda** [comment]
mas @agungsugiarto, No Kia harus melekat kepada anak, sehingga tidak dapat menambahkan  no kia yang sama dengan nama anak yang sama dari 1 ibu.

**Comment by yogiperdana** [comment]
Bisa buatkan issue terpisah terkait ini mas @vickyrolanda

Memisahkan Data masing bagian tersendiri:

Khusus Untuk Fitur Data Ibu Saja.
Khusus Data Anak/Balita

Karena itu permintaan fitur dan sepertinya perlu dianalisis lebih lanjut

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PRhttps://github.com/OpenSID/premium/pull/1671
