### ISSUE TITLE
Tambahkan fitur lokasi rumah pada keluarga (agar tidak input satu-satu)

### ISSUE THREAD

**Issue by K4nzzz** [OpenSID/OpenSID#5985]
### Apa kekurangan yg ingin diatasi?

Lokasi individu memerlukan waktu yang cukup lama.
Jika lokasi di berikan kepada kepala keluarga n secara otomatis anggota mengikuti.
Dan hanya input 1 x di kepala keluarga

### Jelaskan solusi yg diinginkan

Tambahkan fitur tambah lokasi rumah pada keluarga

### Apakah ada alternatif lain

.

### Untuk versi OpenSID mana

21.03

### Informasi tambahan

.

**Comment by Zoel-WB** [comment]
Setuju

**Comment by ruririzal** [comment]
related issue https://github.com/OpenSID/OpenSID/issues/5155 , https://github.com/OpenSID/OpenSID/issues/5896, https://github.com/OpenSID/OpenSID/issues/5577, https://github.com/OpenSID/OpenSID/issues/4849, https://github.com/OpenSID/OpenSID/issues/3773

**Comment by K4nzzz** [comment]
> related issue #5155

Untuk lokasi maps.

**Comment by wahyabiantara** [comment]
Setuju

**Comment by ruririzal** [comment]
mengingat lokasi penduduk terhubung ke produk lapak dan peta, solusi yg bisa saya tawarkan berupa daftar lokasi dan tombol masing2 anggota yg jika diklik akan langsung menyesuaikan dengan lokasi kepala keluarga/kepala rumah tangga.

atau jika tim openDesa (@vickyrolanda, dll) memiliki rencana untuk memisah lokasi penduduk, produk lapak dan peta, bisa dilanjutkan dan dikembangkan di issue lain, misalnya memodifikasi tabel map penduduk dengan tambahan field jenis lokasi

![image](https://user-images.githubusercontent.com/28647065/206065108-07ee0aa5-9388-4bd3-ba9a-b2320e5daa7e.png)

**Comment by vickyrolanda** [comment]
Ok mas @ruririzal saat ini tampung dulu dan sy coba evaluasi 🙏

**Comment by andifahruddinakas** [comment]
https://github.com/OpenSID/OpenSID/issues/5155#issuecomment-1126633056

**Comment by andifahruddinakas** [comment]
Duplicate of https://github.com/OpenSID/OpenSID/issues/5808
