### ISSUE TITLE
Mengubah tampilan maps dengan google map untuk mempermudahkan melihat lokasi rumah

### ISSUE THREAD

**Issue by K4nzzz** [OpenSID/OpenSID#5986]
### Apa kekurangan yg ingin diatasi?

Menggunakan openstreet map tidak keseluruhan bangunan terdaftar atau tampil bloknya.
Hampir 80% tidak tampil.
Jika dibandingkan google map

### Jelaskan solusi yg diinginkan

Ada pilihan penggunakan openstreet dan google map.

### Apakah ada alternatif lain

.

### Untuk versi OpenSID mana

21.03

### Informasi tambahan

.

**Comment by andifahruddinakas** [comment]
Silahkan masukkan key google map pada pengaturan
