### ISSUE TITLE
Permintaan fitur:  Tambahan Form Surat Rekomendasi Pembelian BBM Jenis Tertentu

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#5987]
### Apa kekurangan yg ingin diatasi?

Permintaan fitur Agar setuju untuk di Tambahkan Form Surat Rekomendasi Pembelian BBM Jenis Tertentu, dalam Aplikasi OpenSID

### Jelaskan solusi yg diinginkan

Untuk kepentingan dapat membeli BBM Subsidi Jenis tertentu di di SPBU untuk Peralatan Yang ada di desa untuk mendapatkan BBM Bersubsidi dari pemerintah atas dasar Undang-Undang Pemerintah dan Peraturan Pemerintah Daerah melalui Rekomendasi yg dapat diberikan oleh Kepala Desa.

Form Contoh Sebagai Berikut : 
[Rekomendasi Pembelian BBM Tertentu.docx](https://github.com/OpenSID/OpenSID/files/10009226/Rekomendasi.Pembelian.BBM.Tertentu.docx)

Contoh Dokumen Jadi yang sudah dikeluarkan
[Contoh (Jadi) Rekomnendasi Pembelian Solar Bersubsidi.docx](https://github.com/OpenSID/OpenSID/files/10009911/Contoh.Jadi.Rekomnendasi.Pembelian.Solar.Bersubsidi.docx)

### Apakah ada alternatif lain

Adapun BBM Bersubsidi akan digunakan untuk peralatan didesa yg tidak mungkin di bawa ke SPBU (harus membeli secara enceran dengan membawa Jeregen Penampung ke SPBU), bila tidak ada rekomendasi dari Kepala Desa untuk membeli BBM bersubsidi dari SPBU adalah hal terlarang dan SPBU akan menolak menjualnya.

Jenis-Jenis Peralatan di desa yg membutuhkan rekomendasi kepala desa untuk mendapatkan BBM bersubsidi seperti:
1. Traktor Pembajak Sawah.
2. Pompa Air untuk Mengaliri Sawah.
3. Perahu Nelayan..
4. Dan Peralatan Lain Milik masyarakat desa yang relevan untuk mendapatkan BBM bersubsidi.

### Untuk versi OpenSID mana

OpenSID Premium V23.01

### Informasi tambahan

.

**Comment by andifahruddinakas** [comment]
Bisa dibuat sendiri menggunakan surat tinymce
