### ISSUE TITLE
Bug/error: Tombol Hapus Data Rekam Surat Perorangan di Arsip Layanan- Layanan Surat, Tidak Berfungsi

### ISSUE THREAD

**Issue by mah-mudi** [OpenSID/OpenSID#5988]
### Jelaskan error yg dialami

Tombol Hapus Data Rekam Surat Perorangan di Arsip Layanan- Layanan Surat, Tidak Berfungsi mrngakibatkan nomor surat tetap terekap dan urutan surat tidak bisa dikurangi sesuai keadaan. misal terakhir nomor surat terakhir 25. (padahal dari 25 surat itu ada yang surat uji coba).

### Cara untuk mereplikasi errornya

1. Layanan Surat
2. Arsip Layanan
3. Rekam Surat Perorangan

### Hasil yg diharapkan

Tombol Hapus Data Rekam Surat Perorangan di Arsip Layanan- Layanan Surat, Dapat Berfungsi

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/57661283/201829980-de9aecd5-8a4d-4291-bdac-b807c64a8f3a.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

22.11 Premium rev01

### Tema Yang Digunakan

silir 3.6.3

### Informasi tambahan

-

**Comment by andifahruddinakas** [comment]
Mas @vickyrolanda, coba dicek bagian ini ketentuannya sama dengan hapus arsip yang ada sebelumnya?

issue https://github.com/OpenSID/OpenSID/issues/5580

**Comment by mah-mudi** [comment]
Bisa dicek juga di Diagram Pie nya, masih terekap jumlah nya. Sehingga nomor surat masih berlanjut hitungan nya.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1634
