### ISSUE TITLE
Bug/error: error rilis-bug-fix 22.11-premium-rev02

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#5989]
### Jelaskan error yg dialami

<img width="1440" alt="Screen Shot 2022-11-15 at 12 13 59" src="https://user-images.githubusercontent.com/36557759/201885947-d621395e-1efe-4ceb-b839-d50a5a4a61aa.png">
cetak dan tinjau PDF bagian headernya berantakan

<img width="1440" alt="Screen Shot 2022-11-15 at 12 15 18" src="https://user-images.githubusercontent.com/36557759/201885205-c67af1c1-a231-4eee-ad70-69876b4fd6b1.png">
klik tombol konsep surat TinyMCE error 500

<img width="1440" alt="Screen Shot 2022-11-15 at 14 39 38" src="https://user-images.githubusercontent.com/36557759/201885211-97de6079-35fa-4b88-a07d-28bb8850ba10.png">
error setelah saya login layanan mandiri

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

22.11-premium-rev02 branch rilis-bug-fix

**Comment by andifahruddinakas** [comment]
1. untuk error saat pertinjau kemudian di simpan sebagai draft dibuat issue baru karena tdk ada kaitannya dengan perbaikan issue yg dikerjakan. (Solusi : Issue baru)
2. untuk masalah header sudah berulang kali sy infokan kalau itu perlu diatur sendiri oleh desa, krn biasa ada desa yang alamatnya panjang makanya tinggi header perlu ditambahkan. (Solusi : Perlu buat panduan)
3. Kalau ada error sekalian lampirkan errornya, untuk error layanan-mandiri malah json_value perlu di cek sejak kapan ada perubahan dibagian tsb. Setelah sy cek error tsb krn ubahan di commit https://github.com/OpenSID/premium/commit/81f1b23be4e9e6ea89e32fabd4c6cfff6b40f785 yang artinya sudah lolos rilis v22.11 dan tidak ada kaitannya dengan perubahan dr PR yg ada sekarang.  (Solusi : Buat issue baru dan digabungkan ke rilis rev selanjutnya atau tunda rilis sampai perbaikan tsb selesai)

**Comment by devrakapriyo** [comment]
mas @andifahruddinakas 
1. issue https://github.com/OpenSID/OpenSID/issues/5991
2. untuk solusinya sudah saya buatkan di forum.opendesa.id mas
3. issue https://github.com/OpenSID/OpenSID/issues/5992
