### ISSUE TITLE
Preview tidak sesuai dengan pengaturan yang dibuat

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#5990]
![preview 1](https://user-images.githubusercontent.com/57283157/201968063-abebb156-1e36-4bae-a8f8-24ba9213a4d0.jpg)

![preview 2](https://user-images.githubusercontent.com/57283157/201968089-65f9eedc-6d19-446f-a6f1-f82755281a18.jpg)

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1626
