### ISSUE TITLE
Bug/error: error saat klik tombol konsep surat TinyMCE

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#5991]
### Jelaskan error yg dialami

<img width="1440" alt="Screen Shot 2022-11-15 at 12 15 18" src="https://user-images.githubusercontent.com/36557759/201885205-c67af1c1-a231-4eee-ad70-69876b4fd6b1.png">

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.11-premium-rev2

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1625
