### ISSUE TITLE
Bug/error: setelah login layanan mandiri error 500

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#5992]
### Jelaskan error yg dialami

<img width="1440" alt="Screen Shot 2022-11-15 at 14 39 38" src="https://user-images.githubusercontent.com/36557759/201885211-97de6079-35fa-4b88-a07d-28bb8850ba10.png">

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.11-premium-rev02

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1624
