### ISSUE TITLE
Bug/error: tidak ada keterangan hari/minggu/bulan/tahun kolom volume table pembangunan

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#5993]
### Jelaskan error yg dialami

<img width="1440" alt="Screen Shot 2022-11-16 at 10 47 56" src="https://user-images.githubusercontent.com/36557759/202079959-a6b06420-e7e7-4edf-bb90-827c19fd4fe9.png">
<img width="1440" alt="Screen Shot 2022-11-16 at 10 47 34" src="https://user-images.githubusercontent.com/36557759/202079963-3a9ee484-7c20-468a-92d0-543f99268442.png">

### Cara untuk mereplikasi errornya

menu pembangunan

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.11-premium-rev02

**Comment by andifahruddinakas** [comment]
Mas @devrakapriyo. coba dilihat lebih jelas lagi, itu kolom volume bukan waktu. Kalau mau lihat penerapan waktu ada di bumindes pembagunan.

**Comment by devrakapriyo** [comment]
mas @andifahruddinakas kenapa nama kolomnya volume? sedangkan di form Tambah data pembagunan tidak ada input volume? dan isi nya itu dari waktu pada formnya

**Comment by andifahruddinakas** [comment]
> mas @andifahruddinakas kenapa nama kolomnya volume? sedangkan di form Tambah data pembagunan tidak ada input volume? dan isi nya itu dari waktu pada formnya

cek input formnya itu jelas2 ada input volume.

**Comment by devrakapriyo** [comment]
ok mas @andifahruddinakas saya salah, issue di close
