### ISSUE TITLE
Bug/error: Data-data Penduduk yg sudah terimput sebelumnya, saat dibuka kembali ubah data, ada data-data yg tidak ditampilkan

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#5998]
### Jelaskan error yg dialami

Bug/error: Data-data Penduduk yg sudah terimput sebelumnya, saat dibuka kembali ubah data, ada data-data yg tidak ditampilkan, seolah-olah belum terisi dan harus di input kembali-->simpan ulang, ulangi ubah data, data tersebut baru dimunculkan.

### Cara untuk mereplikasi errornya

Buka salah satu data penduduk lama (mungkin data yg di input dari rilis2 paling awal), pilih Aksi Ubah Data

### Hasil yg diharapkan

Data-data yg sudah pernah di input saat dipilih aksi edit atau ubah data, data-data ini dapat tampil dengan normal..

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/64481641/202361069-d21fa466-b2a1-4d35-8bd7-385fea1b2046.png)

![image](https://user-images.githubusercontent.com/64481641/202361084-6228ea01-de50-4a72-b3d9-d6e7733830be.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

OpenSID Premium V22.11-Rev02

### Tema Yang Digunakan

standard

### Informasi tambahan

.

**Comment by agungsugiarto** [comment]
Pak @Zoel-WB, apakah sudah memastikan data tersebut memang sebelumnya belum terisi di database?
mas @devrakapriyo bisa minta tolong untuk mereplikasi isunya

**Comment by Zoel-WB** [comment]
Sudah pernah lengkap semuanya Pak @agungsugiarto kecuali yg kolom-kolom tambahan belakangan yg masih belum dilengkapi seperti pada kolom suku, asuransi, fitur2 yg berhubungan kontak telegram, kolom tersebut yg belum.

**Comment by agungsugiarto** [comment]
Apakah data baru berpengaruh tidak terisi juga? sepertinya data yg lama memang tidak ada isinya pak @Zoel-WB

**Comment by Zoel-WB** [comment]
Berarti memang telah berubah pak ya, itu pernah saya perhatikan selma ini, karena dulu untuk kolom2 kelahiran, sakit menahun, jenis asuransi sudah pernah dilingkapi dari awal di input pak...

**Comment by agungsugiarto** [comment]
silahkan coba diberputar pak, apakah menumukan masalah yg sama

**Comment by Zoel-WB** [comment]
Baik pak...

**Comment by Zoel-WB** [comment]
Atau Pending dulu untuk issue ini Pak @agungsugiarto.

Bila diperiksan untuk data input baru aman pak, atau data lama di ubah dan disimpan kembali, ditampilkan aman saja, cuma temuan ini di data-data lama yg memang jarang-jarang dibuka biodata-nya, saat ini data itu seperti kolom pada discreensote kalau ditampilkan sudah kosong, kapan masalahnya juga tidak mengetahui periode mana mulai data-data ini kosong...

**Comment by vickyrolanda** [comment]
baik pak saya close terlebih dahulu ya pak @Zoel-WB ntar jika terjadi lagi mohon di open saja pak.

**Comment by Zoel-WB** [comment]
Baik pak...

Dapatkan Outlook untuk Android<https://aka.ms/AAb9ysg>
________________________________
