### ISSUE TITLE
Bug: compress atau resize otomatis pada upload gambar di opensid.

### ISSUE THREAD

**Issue by mah-mudi** [OpenSID/OpenSID#5999]
### Apa kekurangan yg ingin diatasi?

Belum adanya fitur compress atau resize otomatis pada upload gambar di opensid. Dan menyebabkan loading halaman penuh gambar sangat lambat.

### Jelaskan solusi yg diinginkan

Perlu adanya fitur compress atau resize otomatis pada upload gambar di opensid. Resize ke ukuran yg memadai untuk ditampilkan di web. 

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

23.01 Premium

### Informasi tambahan

-

**Comment by vickyrolanda** [comment]
duplikasi issue ntar bisa di sesuaikan di issue ini https://github.com/OpenSID/OpenSID/issues/6168
