### ISSUE TITLE
Bug/error: Ubah Nama Buku Peraturan Desa menjadi Buku Peraturan Di Desa beserta Output Cetak nya

### ISSUE THREAD

**Issue by mah-mudi** [OpenSID/OpenSID#6000]
### Jelaskan error yg dialami

Sub Modul Buku Peraturan Desa dan Out Put Cetak Peraturan Desa masih menggunakan redaksi Peraturan Desa.
**Harusnya memakai redaksi Peraturan Di Desa.**

### Cara untuk mereplikasi errornya

1. Pergi ke Modul Buku Administrasi Desa
2. Buku Administrasi Umum - Buku Peraturan Desa

### Hasil yg diharapkan

Sub Modul Buku Peraturan Desa diubah menjadi **Buku Peraturan Di Desa**
Tombol Tambah Perdes Baru diubah menjadi **Tambah Peraturan**
Redaksi Buku Peraturan Desa perlu dirubah menjadi **Buku Peraturan Di Desa** menyesuaikan Lampiran Permendagri 47 Tahun 2016

![image](https://user-images.githubusercontent.com/57661283/202616140-d9ce642f-0df5-4eba-87ed-3555c1083d97.png)

### Tangkapan layar dan log error
![Buku Peraturan Di Desa](https://user-images.githubusercontent.com/57661283/202633142-1867cd9a-d063-462a-9060-669c90af5588.png)

![Buku Peraturan Di Desa2](https://user-images.githubusercontent.com/57661283/202615491-22a90258-6986-49a1-b91c-dc7a366a6a66.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

22.11 Premium beta01

### Tema Yang Digunakan

Esensi

### Informasi tambahan

https://beta.opendesa.id/

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1635
