### ISSUE TITLE
Bug/error: Ubah Nama Redaksi SK menjadi Keputusan, dan Perbaiki Output Cetak Buku Keputusan Kepala Desa

### ISSUE THREAD

**Issue by mah-mudi** [OpenSID/OpenSID#6001]
### Jelaskan error yg dialami

Redaksi SK pada Kolom Nomor, Tanggal Pengangkatan dan pemberhentian Buku Aparat Pemerintah Desa, belum sesuai lampiran Permendagri Nomor 47 Tahun 2016, karena yang benar bukan SK tapi **Keputusan**

Tombol Tambah SK Kades Baru perlu disesuaikan

Output Cetak Buku Keputusan Kepala Desa Juga Perlu disesuaikan

### Cara untuk mereplikasi errornya

1. Buku Administrasi Desa
2. Buku Administrasi Umum - Buku Keputusan Kepala Desa

### Hasil yg diharapkan

Ubah Nama Redaksi SK menjadi Keputusan pada Kolom Nomor, Tanggal Pengangkatan dan pemberhentian Buku Aparat Pemerintah Desa, menyesuaikan Permendagri 47 Tahun 2016

![1668946443653.jpg](https://user-images.githubusercontent.com/57661283/202901256-01ee6bce-ebf3-46a4-9063-70028645bbd6.jpg)
![image](https://user-images.githubusercontent.com/57661283/202634840-c6e0647c-f4e7-416e-bed2-117f19db8ede.png)

Nomor SK Pengangkatan diubah menjadi **Nomor Keputusan Pengangkatan**
Tanggal SK Pengangkatan diubah menjadi **Tanggal Keputusan Pengangkatan**
Nomor SK Pemberhentian diubah menjadi **Nomor Keputusan Pemberhentian**
Tanggal SK Pemberhentian diubah menjadi **Tanggal Keputusan Pemberhentian**

Tombol Tambah SK Kades Baru perlu diubah menjadi **Tambah Keputusan**

Output Cetak Buku Keputusan Kepala Desa Juga Perlu disesuaikan, dari Buku Keputusan Desa ABCD menjadi **Buku Keputusan Kepala Desa ABCD**

### Tangkapan layar dan log error

![Keputusan kades](https://user-images.githubusercontent.com/57661283/202635768-645cda23-2d00-4295-8b8a-bc9df25322e0.png)

![Keputusan kades2](https://user-images.githubusercontent.com/57661283/202635265-31a37622-2b1a-4a98-bd26-107f1ee63897.png)

![Keputusan kades3](https://user-images.githubusercontent.com/57661283/202636103-27e3b85f-c87d-48cf-8a1d-3d7c355b7aae.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

22.11 Premium beta01

### Tema Yang Digunakan

Esensi

### Informasi tambahan

https://beta.opendesa.id/

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1651
