### ISSUE TITLE
Bug/error: DTKS setiap form input pilihan berikan default NULL jika kosong

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#6002]
### Jelaskan error yg dialami

![image](https://user-images.githubusercontent.com/36557759/202653361-1c63699d-a1ae-46a0-8b3a-50366bbd5cbb.png)

Pada Halaman "KETERANGAN PERUMAHAN" Pilihan pada "Sumber Penerangan Utama" Pilihan " Daya 1-2-2" —> Tidak ada pilihan untuk membatalkan pilihan atau untuk memilih data kosong—>hal ini terjadi bila salah input untuk kembali lagi ke form yg kosong.. intinya semua kolom yg ada pilihan data isian —> harus disediakan pilihan null.

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.11-premium-beta01

**Comment by ruririzal** [comment]
ok

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1633
