### ISSUE TITLE
Bug/error: tombol verifikasi email halaman kerja sama tidak berfungsi

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#6003]
### Jelaskan error yg dialami

![image](https://user-images.githubusercontent.com/36557759/202656880-e74da314-fa12-4955-912b-b8ebeaacce10.png)

saat di klik tombol Verifikasi Alamat Email tidak me redirect

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.11-premium-rev02

**Comment by FirlianiF** [comment]
Setelah dicek, itu dikarenakan validasi dari gmail, dimana jika email ada di folder spam, maka href="" akan dihilangkan oleh gmail.
Solusi nya silahkan hapus label spam pada email yang diterima, maka tombol dan verifikasi akan berjalan dengan baik.

![email](https://user-images.githubusercontent.com/30171560/203220611-5f7b1da2-b0e9-405c-99ff-e15c33949b1a.PNG)
