### ISSUE TITLE
Bug/error: klik tombol simpan form pendaftaran kerja sama tidak ada respon

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#6004]
### Jelaskan error yg dialami

saat klik tombol Simpan di form pendaftaran kerja sama tidak ada respon, dan ketika di inspact element muncul pesan error

<img width="1440" alt="Screen Shot 2022-11-18 at 15 37 28" src="https://user-images.githubusercontent.com/36557759/202658423-cef7d815-6575-4eab-a1dc-6d442dbe67a8.png">

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.11-premium-rev02

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR Perbaikan https://github.com/OpenSID/premium/pull/1650
