### ISSUE TITLE
Bug/error: link dari email pendaftaran kerja sama muncul pesan whoops

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#6005]
### Jelaskan error yg dialami

<img width="1440" alt="Screen Shot 2022-11-18 at 15 41 27" src="https://user-images.githubusercontent.com/36557759/202658984-9f52f7d8-d69e-4443-ac06-622f31dc7d7e.png">

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.11-premium-rev02

**Comment by vickyrolanda** [comment]
ini sepertinya issuenya di layanan mas @devrakapriyo

**Comment by FirlianiF** [comment]
Setelah dicek, itu dikarenakan validasi dari gmail, dimana jika email ada di folder spam, maka href="" akan dihilangkan oleh gmail.
Solusi nya silahkan hapus label spam pada email yang diterima, maka tombol dan verifikasi akan berjalan dengan baik.


![verif layanan](https://user-images.githubusercontent.com/30171560/203220327-74b12886-7a56-47b9-9ec9-0ad2ec4f9831.PNG)
