### ISSUE TITLE
Menambah Link Channel Youtube pada Menu Admin Web -> Media Sosial

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#6006]
### Jelaskan error yg dialami

Saat ini pada Pengaturan Media Sosial Youtube muncul notifikasi error "Sesuaikan dengan format yang diminta".

Sedangkan paad youtube tersedia nicname atau penamaan channel menggunakan slug singkat.

Sebagai contoh:
Channel Yotube sebenarnya adalah: youtube.com/@natairaya
Namun ketika diketik muncul notif gagal tersebut (gambar terlampir)

Sedangkan jika hanya diberi nama natairaya pada kolom hasilnya https://www.youtube.com/channel/natairaya
ada penambahan slug /channel/ dan tanpa tanda @ sehingga halaman channel tidak dapat terbuka (404).

<img width="352" alt="image" src="https://user-images.githubusercontent.com/46939846/202746622-67cb7967-c878-4211-af08-a53a91520302.png">

<img width="770" alt="image" src="https://user-images.githubusercontent.com/46939846/202746825-aed977f3-1978-4966-8d54-10521d068382.png">

### Cara untuk mereplikasi errornya

1. Login halaman admin
2. klik menu Admin Web
3. pilih Media Sosial
4. klik Youtube
5. masukkan link akun youtube @natairaya atau https://www.youtube.com/@natairaya

Lihat error nya.

### Hasil yg diharapkan

Mendukung input karakter sebagaimana disediakan oleh youtube. 

### Tangkapan layar dan log error

Seperti di atas.

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Semua

**Comment by yogiperdana** [comment]
Saat ini medsos belum support untuk hal tersebut pak jadi ini masuknya bukan bug.

Solusi sementara dapat mengikuti  panduan atau petunjuk dari opensid yaitu dengan memasukkan link url youtube

![image](https://user-images.githubusercontent.com/14155050/202901274-eba52b07-8d02-4155-b6bd-afcca49f1b9f.png)

**Comment by ariandii** [comment]
medsos youtube sudah mendukung itu, bisa buka youtube.com/@natairaya  dan youtube lainnya yang sudah menggunakan nickname.

**Comment by ariandii** [comment]
karena youtube menyediakan nick name dan diinput ke opensid gagal, maka saya buatlah bug

**Comment by ruririzal** [comment]
silahkan di cek mas @vickyrolanda

**Comment by temiyangsari** [comment]
Sampai saat ini masih erorr untuk memasukan url YouTube ke media sosial opensid.
