### ISSUE TITLE
Bug/error: tidak bisa masuk layanan-mandiri 

### ISSUE THREAD

**Issue by ranranrasgar** [OpenSID/OpenSID#6007]
### Jelaskan error yg dialami

Setelah update dari versi sebelumnya ke versi terbaru yaitu versi 22.11 jadi tidak bisa masuk ke login page layanan Mandiri

[[Contoh Halaman Yang ini ](https://pemdeskasomalangkulon.com/layanan-mandiri/masuk)](url)

Mohon masukanya.. Terima kasih

### Cara untuk mereplikasi errornya

https://pemdeskasomalangkulon.com/layanan-mandiri/masuk

### Hasil yg diharapkan

Bisa mauk ke login page LAYANAN MANDIRI

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/104102354/202809067-0b32088d-a0b3-43a9-a4e3-cd5faddb0876.png)

### Rilis Versi OpenSID

Rilis Umum

### Versi OpenSID

v22.11

### Tema Yang Digunakan

Natra v22.04

**Comment by vickyrolanda** [comment]
ini terjadi di rilis umum ya pak ? @ranranrasgar

**Comment by usmanrahdi** [comment]
coba https://pemdeskasomalangkulon.com/index.php/layanan-mandiri/masuk
coba rename file htaccess.txt menjadi .htaccess, kemudian coba gunakan forum pak atau grub di telegram untuk sekedar bertanya sebelum dilaporkan sebagai bug

**Comment by apidong** [comment]
https://github.com/OpenSID/OpenSID/wiki/Pengaturan-.htaccess
