### ISSUE TITLE
Kesalahan penulisan Tempat Tanggal lahit 

### ISSUE THREAD

**Issue by apidong** [OpenSID/OpenSID#6008]
![image](https://user-images.githubusercontent.com/20056421/202843321-ade1b110-04b6-460a-ab3f-fbdf9c12415b.png)
pada kode isian, tulisan Tempat Tanggal lahit (TTL) seharusnya Tempat Tanggal lahir (TTL)

**Comment by ariandii** [comment]
ijin koreksi, seharusnya Tempat Tanggal Lahir

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1638
