### ISSUE TITLE
Bug: disable headjs cetak buku tanah kas desa.

### ISSUE THREAD

**Issue by mah-mudi** [OpenSID/OpenSID#6009]
### Jelaskan error yg dialami

Belum adanya Kolom Jenis TKD,Patok Tanda Batas,Papan Nama pada Buku Tanah Kas Desa.

### Cara untuk mereplikasi errornya

1. Buku Administrasi Desa
2. Buku Administrasi Umum - Buku Tanah Kas Desa

### Hasil yg diharapkan

Hasil Output Buku Tanah Kas Desa dapat sesuai dengan Lampiran Permendagri Nomor 47 Tahun 2016 tentang Administrasi Pemerintahan Desa.
Untuk Jenis TKD ada pilihan isian : sawah, tegalan, kebun, tambak/kolam dan tanah kering/darat.
Untuk Patok Tanda Batas ada pilihan isian : Ada, Tidak Ada
Untuk Papan Nama ada pilihan isian : Ada, Tidak Ada

[Permen No.47 TH 2016_Lampiran.pdf](https://github.com/OpenSID/OpenSID/files/9996895/Permen.No.47.TH.2016_Lampiran.pdf)

### Tangkapan layar dan log error

Harapannya seperti format lampiran permendagri 47 tahun 2016 seperti ini. 
![1668866211963.jpg](https://user-images.githubusercontent.com/57661283/202854168-6950ff98-547b-467e-b361-8f453ef97efd.jpg)

![201516004-93b5dd08-4c2d-480d-840a-81070f7ef2f1.png](https://user-images.githubusercontent.com/57661283/202854238-60e3f3e5-0533-4570-8f4a-5e2a6f7ba53a.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.11-premium-beta01

### Tema Yang Digunakan

Esensi

### Informasi tambahan

beta.opendesa.id

**Comment by agungsugiarto** [comment]
Pak @mah-mudi untuk kolom hasil cetak kurang nomor 23 dan 24 ya?

**Comment by agungsugiarto** [comment]
pak @mah-mudi, saya kurang jelas dengan issue yg di maksud, ketika saya coba semua form dan kolom ada semua ketika membuat, mas @vickyrolanda bisa bantu saya untuk menganalisis issue ini?

<img width="587" alt="image" src="https://user-images.githubusercontent.com/10989147/210789234-334c70a8-5cf1-4654-bec9-b9fcf14a5d47.png">

**Comment by mah-mudi** [comment]
Pak @agungsugiarto , dapat dicek di hasil cetak Buku Tanah Kas Desa pada OpenSID. 

Belum adanya Kolom Jenis TKD,Patok Tanda Batas,Papan Nama pada Buku Tanah Kas Desa seperti pada format lampiran Buku Tamah kas Desa berdasarkan Permendagri tentang Administrasi Pemerintahan Desa.

**Comment by mah-mudi** [comment]
Pak @agungsugiarto, kayak nya sdh diperbaiki. Tinggal masih keluar pop up seperti ini lg. ![Screenshot_2023-01-06-00-11-26-231_com.android.chrome.jpg](https://user-images.githubusercontent.com/57661283/210840112-4940eb64-fb6a-4f77-b4ef-8188d8995c3c.jpg)

Pop up seperti ini perlu dihilangkan ketika klik cetak

**Comment by agungsugiarto** [comment]
pak @mah-mudi, issue ini brarti diubah untuk menghilangkan pop up saja?

**Comment by mah-mudi** [comment]
Iya pak @agungsugiarto , boleh.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1906
