### ISSUE TITLE
Sediakan pengaturan agar bisa menyesuaikan/menambahkan ukuran huruf 9pt 11pt 16pt 20pt 22pt pada Template Pengaturan Surat

### ISSUE THREAD

**Issue by mah-mudi** [OpenSID/OpenSID#6010]
### Jelaskan error yg dialami

Belum adanya ukuran huruf 9pt 11pt 16pt 20pt 22pt pada Template Pengaturan Surat

### Cara untuk mereplikasi errornya
1. Layanan Surat
2. Pengaturan Surat - Template

### Hasil yg diharapkan

Tersedianya ukuran huruf 9pt 11pt 16pt 20pt 22pt pada Template Pengaturan Surat, untuk pengaturan surat lebih baik. 

### Tangkapan layar dan log error

![201513736-30e32793-ecfc-4c2e-a238-0c15bf323966.png](https://user-images.githubusercontent.com/57661283/202856440-8d62a247-bfdc-4afc-988d-9b2742b7695d.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.11-premium-beta01

### Tema Yang Digunakan

Esensi

### Informasi tambahan

-

**Comment by andifahruddinakas** [comment]
ini mas @habibie11, perlu di update ke tinymce 6 untuk menggunakan fontinputsize.
https://www.tiny.cloud/docs/tinymce/6/6.4.1-release-notes/

contoh : https://codepen.io/tinymce/pen/XWdevOx

**Comment by habibie11** [comment]
Oke siap, noted mas @andifahruddinakas

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/2407
