### ISSUE TITLE
Penyesuaian Ubah Pernyataan Adalah benar dan tercatat dalam database sistem informasi kami, Menjadi Pemerintah Desa ABCD Kecamatan EFGH Kabupaten IJKL

### ISSUE THREAD

**Issue by mah-mudi** [OpenSID/OpenSID#6011]
### Jelaskan error yg dialami

Tampilan Penyataan adalah benar dan tercatat dalam database sistem informasi kami, masih menampilkan Pemerintah Kabupaten

### Cara untuk mereplikasi errornya

1. Arsip Layanan
2. Arsip
3. Klik QR Code
4. Klik Lihat

### Hasil yg diharapkan

Tampilan Penyataan adalah benar dan tercatat dalam database sistem informasi kami, yang asalnya menampilkan Pemerintah Kabupaten diubah Menjadi **Pemerintah Desa** contoh Pemerintah Desa ABCD Kecamatan EFGH Kabupaten IJKL.

Karena di Desa sudah ada Pemerintahan Sendiri, benar dan tercatat dalam database sistem informasi database Pemerintah Desa.

### Tangkapan layar dan log error

![ss1](https://user-images.githubusercontent.com/57661283/202878679-a6a33cd4-e0a2-4dbd-b889-d52f25e83cd0.png)
![ss2](https://user-images.githubusercontent.com/57661283/202878697-745a6cdb-a1bb-4ad5-abdc-068765f9c51d.png)
![SS3](https://user-images.githubusercontent.com/57661283/202878702-20a91b9d-724c-4719-9583-ca85ae3fb312.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

OpenSID 22.11-premium-rev02

### Tema Yang Digunakan

Esensi

### Informasi tambahan

-

**Comment by andifahruddinakas** [comment]
Bisa sesuaikan sendiri pada tema masing2, jika ada ubahan pada tema bawaan copy tema bawaan ke folder desa/themes dan lakukan ubahan ke tema tsb. Mas @devrakapriyo, bisa ditambahkan ke panduan.
