### ISSUE TITLE
Permintaan fitur: Integrasikan No Telp/HP/WA/Telegram Data Kependudukan pada Daftar Kontak - Hubung Warga.

### ISSUE THREAD

**Issue by mah-mudi** [OpenSID/OpenSID#6012]
### Apa kekurangan yg ingin diatasi?

Belum terintegrasinya No Telp/HP/WA/Telergam Data Kependudukan pada Daftar Kontak - Hubung Warga. Fitur saat ini, PPID bekerja dua kali karena input lg no  Telp/HP/WA/Telegram warga pada  Daftar Kontak - Hubung Warga.
![image](https://user-images.githubusercontent.com/57661283/202903066-b56e1a07-e9da-4533-bfca-f1f194abed3a.png)

### Jelaskan solusi yg diinginkan

Terintegrasinya No Telp/HP/WA/Telergam Data Kependudukan pada Daftar Kontak - Hubung Warga.

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

OpenSID 22.11-premium-rev02

### Informasi tambahan

-

**Comment by yonathanrizky** [comment]
mas @mah-mudi apakah ini masih belum bisa? saya coba di versi premium 23-01 sudah terintegrasi untuk kontak penduduk

**Comment by mah-mudi** [comment]
ok sudah
