### ISSUE TITLE
Bug/error: install opensid siap pakai di v22.11-premium-rev02

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#6013]
### Jelaskan error yg dialami

![image](https://user-images.githubusercontent.com/36557759/202951397-6ed75ba8-7ae1-4d3d-b629-b68ad7855e7d.png)

saat install OpenSID siap pakai untuk versi v22.11-premium-rev02 mengalami error dan table yang ter migrasi hanya 217 table

![image](https://user-images.githubusercontent.com/36557759/202951560-6be9a15e-dfcc-4285-91a9-b8685c3febfc.png)

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.11-premium-rev02

**Comment by vickyrolanda** [comment]
mas @devrakapriyo ini pindahkan ke issue siap pakai mas.

**Comment by devrakapriyo** [comment]
tidak ada respository siap pakai mas @vickyrolanda
