### ISSUE TITLE
Permintaan fitur:  UPLOAD TEMA LEWAT SISTEM

### ISSUE THREAD

**Issue by Fajar-blackdeath** [OpenSID/OpenSID#6015]
### Apa kekurangan yg ingin diatasi?

SUPAYA LEBIH MUDAH

### Jelaskan solusi yg diinginkan

SUPAYA LEBIH MUDAH

### Apakah ada alternatif lain

SUPAYA LEBIH MUDAH

### Untuk versi OpenSID mana

22.12

### Informasi tambahan

SUPAYA LEBIH MUDAH

**Comment by totoprayogo1916** [comment]
bisa di close, bisa up #2486
