### ISSUE TITLE
Bug/error: ID Pengunjung tidak muncul saat pertama kali halaman di akses

### ISSUE THREAD

**Issue by khiar-rara** [OpenSID/OpenSID#6017]
### Jelaskan error yg dialami

ID Pengunjung di halaman Layanan Mandiri tidak muncul saat pertama kali halaman di akses.

### Cara untuk mereplikasi errornya

Reload halaman

### Hasil yg diharapkan

ID pengunjung langsung muncul saat halaman diakses

### Tangkapan layar dan log error

![loginrequest](https://user-images.githubusercontent.com/74307159/202985655-f9470ba3-9686-4e58-9fa7-6b6f83cbcf42.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.12-premium

### Tema Yang Digunakan

esensi dan natra

### Informasi tambahan

-

**Comment by agungsugiarto** [comment]
pak @khiar-rara apakah sudah mencoba untuk `refresh` ulang halamannya?

**Comment by khiar-rara** [comment]
ya sudah, jika direfresh akan muncul.

untuk login, bukankah dibutuhkan ID Pengunjung ?

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1647
