### ISSUE TITLE
Bug/error: fitur Kembalikan Status tidak berfungsi

### ISSUE THREAD

**Issue by rsoeta** [OpenSID/OpenSID#6018]
### Jelaskan error yg dialami

Fitur dengan tombol Kembalikan Status tidak berfungsi di Menu Log Penduduk, di coba di situs berputar.opendesa.id pun sama terjadi error 

### Cara untuk mereplikasi errornya

1. Pergi ke halaman/menu "Penduduk" 
2. Pilih "Pilih Aksi Lainnya"
3. Pilih "Log Penduduk"
4. Cari data Penduduk yang hendak di kembalikan status nya
5. Klik tombol "Kembalikan Status"
6. Terjadi error 

### Hasil yg diharapkan

Ketika tombol "Kembalikan Status" di klik, Data tersebut kembali Status nya menjadi Hidup 

### Tangkapan layar dan log error

![IMG_20221121_221327_536](https://user-images.githubusercontent.com/86590833/203090183-5b6e8cb9-d4eb-4402-92f0-6d28057aeeb3.jpg)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.11-premium-rev03

### Tema Yang Digunakan

Natra v22.11

**Comment by Zoel-WB** [comment]
Logs Error :
Severity: error --> Exception: SQLSTATE[42S22]: Column not found: 1054 Unknown column '835' in 'field list' (SQL: select `835` from `log_penduduk` limit 1) /home/teupinbe/public_html/vendor/illuminate/database/Connection.php 712

![image](https://user-images.githubusercontent.com/64481641/203118482-4d4d5812-a35c-4bdf-91ea-29c4184cc3d2.png)

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1641
