### ISSUE TITLE
Bug/error: Tambah Rumah Tangga

### ISSUE THREAD

**Issue by syahransaputra** [OpenSID/OpenSID#6019]
### Jelaskan error yg dialami

Saat memilih Kepala Rumah Tangga maka di table anggota keluarga tercentang semua, jika jumlah penduduk jumlahnya ribuan maka lumayan lelah untuk uncheklist satu persatu yg buka anggota keluarganya

### Cara untuk mereplikasi errornya

1. Pergi ke menu kependudukan
2. pilih menu rumah tangga
3. klik tambah rumah tangga
4. pilih kepala rumah tangga
5. lihat anggota tercentang semua

### Hasil yg diharapkan

mungkin yg tampil untuk checklist di tambahkan sebagai anggota rumah tangga yaitu anggota keluarga itu sendiri saja untuk sementara, dan untuk menambahkan anggota keluarga baru nanti bisa di lakukan di menu tanmbah anggota saja

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.11-premium-rev03

### Tema Yang Digunakan

-

### Informasi tambahan

-

**Comment by Zoel-WB** [comment]
![image](https://user-images.githubusercontent.com/64481641/203119292-37073c3a-c708-4390-b817-4b23cbcb2bc9.png)

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1640
