### ISSUE TITLE
Bug/error: Tambah Anggota Rumah Tangga

### ISSUE THREAD

**Issue by syahransaputra** [OpenSID/OpenSID#6020]
### Jelaskan error yg dialami

Ketika menambahkan anggota rumah tangga, keterangan Data berhasil disimpan namun Anggota Rumah Tangga tidak tertambah

### Cara untuk mereplikasi errornya

1. Pergi ke menu kependudukan
2. pilih menu rumah tangga
3. klik rincian anggota rumah tangga
4. Klik Tambah anggota
5. setelah menambahkan dan status Data berhasil disimpan
6. namunlihat tidak ada anggota yg ditambahkan

### Hasil yg diharapkan

Seharusnya anggota yg ditambahkan masuk di list anggota rumah tangga

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.11-premium-rev03

### Tema Yang Digunakan

-

### Informasi tambahan

-

**Comment by Zoel-WB** [comment]
![image](https://user-images.githubusercontent.com/64481641/203119078-8870d21d-0594-4244-8437-214f396c45e4.png)

**Comment by Zoel-WB** [comment]
Menambah satu penduduk lahir ke dalam anggota rumah tangga juga tidak dapat dilakukan, solusi saat ini harus dikeluarkan dulu Kepela Keluarga (ayah kandung) dari anggota RTM untuk menyemput dan di tambah sama-sama menjadi Anggota Keluarga...

Cara ini saya kira canggih juga, cuma masalahnya Kepala Keluarga (termasuk Kepala Keluarga Tunggal tanpa anggota) harus dapat di tambahkan menjadi anggota RTM, ya tidak apa-apalah misalnya yg harus keluar menjemput anggota baru.

**Comment by eddieridwan** [comment]
> Menambah satu penduduk lahir ke dalam anggota rumah tangga juga tidak dapat dilakukan

Penduduk lahir seharusnya ditambahkan ke Keluarga,  bukan Rumah Tangga. Rumah Tangga tidak dapat digunakan untuk menambah penduduk. Penambahan penduduk harus selalu dilakukan di daftar Penduduk atau Keluarga. Rumah Tangga hanya terkait penduduk yg sudah ada.

**Comment by andifahruddinakas** [comment]
Duplicate issue https://github.com/OpenSID/OpenSID/issues/6019
