### ISSUE TITLE
Penamaan OpenDesa dan OpenSID tidak konsisten

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#6022]
Buat konsisten penamaan dari OpenDesa dan OpenSID pada view.

Cek bagian2 mana saja yang perlu diperbaiki.

Solusi : 
1. buat config nama_lembaga.
2. buat config nama_aplikasi.
3. panggil config tsb pada bagian yang diperlukan untuk ditampilkan.

**Comment by andifahruddinakas** [comment]
![ejaan](https://user-images.githubusercontent.com/57283157/203490631-e4448c0a-75a3-49b9-a77e-513531746034.jpg)

**Comment by eddieridwan** [comment]
@andifahruddinakas kalau melihat keseluruhan pembahasan di Telegram akan diketahui bahwa ejaan yg benar adalah sbb:

1. OpenDesa **(bukan OpenDESA)**
2. OpenSID

Karena SID adalah kependendekan Sistem Informasi Desa, sedangkan Desa adalah kata utuh, bukan akronim atau singkatan.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1649
