### ISSUE TITLE
Bug/error: sembunyikan halaman berlangganan pada mode demo 

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#6025]
### Jelaskan error yg dialami

<img width="1440" alt="Screen Shot 2022-11-22 at 12 12 40" src="https://user-images.githubusercontent.com/36557759/203257566-3a7ca755-5f3c-45a1-9ae4-fa4535258068.png">

https://berputar.opendesa.id merupakan website demo dan menampilkan data langganan dan token desa, harap sebunyikan halaman kerja sama nya

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

khusus mode demo, halaman kerja sama di sembunyikan

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.11-premium-rev03

**Comment by eddieridwan** [comment]
@devrakapriyo mengapa perlu disembunyikan? Seharusnya di berputar mengacu pada devlayanan, yg bisa diisi dengan data contoh, yaitu bukan data betulan. Adanya halaman itu bermanfaat untuk pengguna mencoba fitur kerjasama.

**Comment by andifahruddinakas** [comment]
> @devrakapriyo mengapa perlu disembunyikan? Seharusnya di berputar mengacu pada devlayanan, yg bisa diisi dengan data contoh, yaitu bukan data betulan. Adanya halaman itu bermanfaat untuk pengguna mencoba fitur kerjasama.

PERBANDINGAN  : 
1. Token Pelanggan Disimpan di file config dan tidak dapat diubah dan tidak ditampilkan halaman pelanggan. Yang saat ini karena sudah banyak perubahan, token ditampilkan dan dapat diubah.
2. Point 1 versi lama berlaku jika data devlayanan tidak diubah2 (memang disediakan untuk data pelanggan contoh). Saat ini devlayanan selalu diperbarui berdasarkan data layanan asli (tanpa file unggahan), sehingga pelanggan yang pernah dibuat untuk development tidak ditemukan (terhapus).
3. Point 1 versi lama dibuatkan pelanggan untuk demo di website, yang sekarang agak susah karena point 2.

Untuk versi lama layanan yang ditampilkan sifatnya data contoh (asal), sehingga tidak perlu khawatir kalau data pemesanan pengguna bocor.

**Comment by andifahruddinakas** [comment]
Menunggu PR https://github.com/OpenSID/Layanan_OpenDESA/pull/171 digabungkan.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1661
