### ISSUE TITLE
Bug/error: Terdapat tampilan berupa tulisan "Lihat b" yang tidak diinginkan di Halaman Informasi Publik

### ISSUE THREAD

**Issue by siayi** [OpenSID/OpenSID#6027]
### Jelaskan error yg dialami

Terdapat tampilan berupa tulisan [Lihat b](https://berputar.opendesa.id/first/tampilkan/1) yang tidak diinginkan di bawah judul halaman Informasi Publik, sebagaimana di tampilkan pada tangkapan layar.

### Cara untuk mereplikasi errornya

Menghilangkan tulisan yang tidak diinginkan tersebut agar tidak muncul di halaman Informasi Publik.

### Hasil yg diharapkan

Tulisan yang tidak diinginkan tersebut tidak tampil di halaman Informasi Publik

### Tangkapan layar dan log error

![informasi_publik Screenshot 2022-11-23 100153](https://user-images.githubusercontent.com/1229849/203463199-72fb2c68-cd08-497d-8dd6-ae3d375b0cb0.jpg)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

22.11-premium-rev03

### Tema Yang Digunakan

Natra v2

### Informasi tambahan

Pada tema Esensi v22.11 error ini muncul.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1648
