### ISSUE TITLE
BUG OPENSID: Perbaiki tidak bisa cetak bukti bayar untuk pemesanan baru

### ISSUE THREAD

**Issue by FirlianiF** [OpenSID/OpenSID#6028]
![photo_2022-11-18_13-14-38](https://user-images.githubusercontent.com/30171560/203545402-9e0b4ec0-95eb-41e8-9492-6d15d43b6e70.jpg)

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1652
