### ISSUE TITLE
Restore Database

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#6030]
masih menampilkan pilihan lain, harusnya ditampilkan hanya file .sql saja pada posisi default saat buka.

![restore db](https://user-images.githubusercontent.com/57283157/203680956-7e2b3235-7352-4aec-8f00-ce1add9c250f.jpg)

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1655
