### ISSUE TITLE
Bug/error: arsip layanan surat tidak muncul

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#6033]
### Jelaskan error yg dialami

beberapa desa mengalami arsip layanan surat tidak muncul setelah update ke versi 22.11-premium-rev03 sedangkan di versi sebelumnya data tersebut ada

<img width="1440" alt="Screen Shot 2022-11-25 at 10 26 55" src="https://user-images.githubusercontent.com/36557759/203894786-42d1724c-9123-4696-866a-3813707f5246.png">

<img width="1440" alt="Screen Shot 2022-11-25 at 10 27 14" src="https://user-images.githubusercontent.com/36557759/203896037-8e48d15a-c83c-4b10-bf20-04d6cd78f112.png">

dan beberapa ketentuan seperti login sebagai admin dan ubah di file config $config['user_admin'] = 1;
dan data layanan arsip tetap kosong

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.11-premium-rev03

**Comment by devrakapriyo** [comment]
terlampir database desa dari salah satu desa yang mengalami arsip layanan surat tidak muncul

https://drive.google.com/drive/folders/1nf51Gi4lXHbaTL7t8IHPY5a6DmCw3PaL?usp=sharing

**Comment by apidong** [comment]
@vickyrolanda 
ini dikarenakan user admin mejabat sebagai sekdes. sehingga arsip layanan tidak muncul. 
pak @vickyrolanda mohon dianalisis, bagaimana rule dari sekdes saat melihat arsip  jika verifikasi sekdes tidak aktif maupun aktif.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1662
