### ISSUE TITLE
Permintaan fitur: Menambahkan Kode Isian Pilihan Dengan data Manual

### ISSUE THREAD

**Issue by khiar-rara** [OpenSID/OpenSID#6034]
### Apa kekurangan yg ingin diatasi?

Dapat menambahkan element select option pada form isian di tinymce
![selectrequest](https://user-images.githubusercontent.com/74307159/203926778-9c52498c-5023-4ef9-a16c-d8afed327d64.png)

### Jelaskan solusi yg diinginkan

Tambahkan element select

### Apakah ada alternatif lain

Tambahkan altenatif insert kode html secara manual

### Untuk versi OpenSID mana

v22.12-premium

### Informasi tambahan

-

**Comment by andifahruddinakas** [comment]
SOLUSI : 
1. Data pilihan dibuat secara manual yang bisa disesuaikan sendiri oleh pengguna.

**Comment by andifahruddinakas** [comment]
![image](https://user-images.githubusercontent.com/57283157/211448867-b0dba803-6d67-42ab-8c1d-daf97e2597f8.png)

**Comment by khiar-rara** [comment]
saya tidak tahu maksud gambar diatas pak. yang saya butuhkan adanya element select (data enum). misal membuat element select laki laki dan perempuan, ya dan tidak.
jika maksud gambar diatas sudah seperti itu, terima kasih banyak.

**Comment by andifahruddinakas** [comment]
> saya tidak tahu maksud gambar diatas pak. yang saya butuhkan adanya element select (data enum). misal membuat element select laki laki dan perempuan, ya dan tidak. jika maksud gambar diatas sudah seperti itu, terima kasih banyak.

Hanya contoh yg akan diterapkan diOpenSID sebagai referensi pengerjaan issue ini.

**Comment by andifahruddinakas** [comment]
Contoh struktur : 
```
[
 {
    "type": "select",
    "required": false,
    "label": "Select",
    "className": "form-control",
    "name": "select-1679553529534-0",
    "values": [
      {
        "label": "Option 1",
        "value": "option-1",
        "selected": true
      },
      {
        "label": "Option 2",
        "value": "option-2",
        "selected": false
      },
      {
        "label": "Option 3",
        "value": "option-3",
        "selected": false
      }
    ]
  }
]
```

**Comment by andifahruddinakas** [comment]
```
// text
[
    'name' => 'app_name',
    'type' => 'text',
    'label' => 'App Name',
    // optional fields
    'data_type' => 'string',
    'rules' => 'required|min:2|max:20',
    'placeholder' => 'Application Name',
    'class' => 'form-control',
    'style' => 'color:red',
    'value' => 'QCode',
    'hint' => 'You can set the app name here'
],

// number
[
    'name' => 'users_allowed',
    'type' => 'number',
    'label' => 'Number of users allowed',
    // optional fields
    'data_type' => 'int',
    'min' => 5,
    'max' => 100,
    'rules' => 'required|min:5|max:100',
    'placeholder' => 'Number of users allowed',
    'class' => 'form-control',
    'style' => 'color:red',
    'value' => 5,
    'hint' => 'You can set the number of users allowed to be added.'
]

// email
[
    'name' => 'from_email',
    'type' => 'email',
    'label' => 'From Email',
    // optional fields
    'rules' => 'required|email',
    'placeholder' => 'Emails will be sent from this address',
    'class' => 'form-control',
    'style' => 'color:red',
    'value' => 'noreply@example.com',
    'hint' => 'All the system generated email will be sent from this address.'
]
```

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2184
