### ISSUE TITLE
Permintaan fitur: Permintaan Fitur Ubah Data Penduduk Dari Daftar Anggota Rumah Tangga

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#6035]
### Apa kekurangan yg ingin diatasi?

Permintaan Perlu Menyediakan Fitur untuk dapat mengubah data penduduk langsung dapat dipanggil form ubah data dari Daftar Anggota Rumah Tangga....

### Jelaskan solusi yg diinginkan

Sama dengan Fitur Ubah Data dari  Daftar Anggota Keluarga (KK)

![image](https://user-images.githubusercontent.com/64481641/204016776-d2f32be7-76eb-41af-a895-e696d022bda3.png)

![image](https://user-images.githubusercontent.com/64481641/204016837-b616f2c7-175d-463d-9b2c-0d0b9c464cb9.png)

### Apakah ada alternatif lain

Untuk mempermudah dapat memperbaiki atau memperbaharui data langsung di/dari Daftar Anggota Rumah Tingga, bila data Penduduk di maksud masih perlu di koreksi kembali, seperti masalah dengan kelengkapan Kartu BPJS, masalah Penyakit Tahunan, masalah Ibu hamil, sehingga langsung dapat dipanggil data untuk dikoreksi dari Daftra Anggota Rumah tangga.......

### Untuk versi OpenSID mana

OpenSID Premium V23.01

### Informasi tambahan

.

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/1966
