### ISSUE TITLE
Bug/error: Cek Inpor data Program Bantuan 

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#6036]
### Jelaskan error yg dialami

Saat melakukan inpor data perogram bantuan terjadi error 500

### Cara untuk mereplikasi errornya

.

### Hasil yg diharapkan

Program Bantuan Dapat di  Inpor seperti biasa

### Tangkapan layar dan log error

![photo_2022-11-25_10-36-43](https://user-images.githubusercontent.com/64481641/204017629-7e138abd-bac1-4532-8e58-a57664ae451e.jpg)
![photo_2022-11-25_10-31-17](https://user-images.githubusercontent.com/64481641/204017648-f0ea4cb7-79f6-459e-b230-6450d55ebcd2.jpg)

Logs Error :  Severity: error --> Exception: Object of class DateTime could not be converted to string /home/teupinbe/public_html/vendor/openspout/openspout/src/Common/Entity/Cell.php 81

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Premium v22.11-rev03

### Tema Yang Digunakan

.

### Informasi tambahan

.

**Comment by Zoel-WB** [comment]
Mungkin yg terjadi pasa issue ini yg sudah pernah diperbaiki lebih kurang sama : https://github.com/OpenSID/OpenSID/issues/4538

**Comment by yogiperdana** [comment]
> Mungkin yg terjadi pasa issue ini yg sudah pernah diperbaiki lebih kurang sama : #4538

Bisa japri ke telegram saya file impornya pak @Zoel-WB

**Comment by Zoel-WB** [comment]
> > Mungkin yg terjadi pasa issue ini yg sudah pernah diperbaiki lebih kurang sama : #4538
> 
> Bisa japri ke telegram saya file impornya pak @Zoel-WB

Sudah saya japri file-nya pak @yogiperdana

**Comment by yogiperdana** [comment]
> > > Mungkin yg terjadi pasa issue ini yg sudah pernah diperbaiki lebih kurang sama : #4538
> > 
> > 
> > Bisa japri ke telegram saya file impornya pak @Zoel-WB
> 
> Sudah saya japri file-nya pak @yogiperdana

Baik terima kasih pak

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1665
