### ISSUE TITLE
Bug pada tanggapin pengaduan.

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#6038]
1. Masuk ke menu pengaduan
2. Tanggapin salah satu pengaduan 
3. maka hasilnya akan redirect ke pemeriksaan dan lognya seperti berikut ini : 
ERROR - 2022-11-27 16:41:45 --> Query error: Field 'ip_address' doesn't have a default value - Invalid query: INSERT INTO `pengaduan` (`id_pengaduan`, `nama`, `isi`, `status`) VALUES ('1', 'Vicky', 'asfdasdf', '2')
kalo di check dari table pengaduan  bagian field IP address tidak bisa NULL : 
<img width="542" alt="image" src="https://user-images.githubusercontent.com/59082428/204128838-4690e2b1-b9ba-4ffb-8ec0-c1722ac7c7b9.png">

**Comment by andifahruddinakas** [comment]
![image](https://user-images.githubusercontent.com/57283157/204174336-26c883da-f2c1-4180-9716-224456c46857.png)

IP_address mmang tdk boleh null karena bagian dari pengecekan agar tdk melakukan spam. Sy coba di https://berputar.opendesa.id/pengaduan dan lokal tidak menemukan masalah ini. Mungkin di cek dlu di tempatnya, kenapa IP_addressnya tidak terdeteksi.

Mungkin sulusi sementara dari sy, tampilkan notifikasi jika IP_address tidak diketahui.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1664
