### ISSUE TITLE
Halaman informasi public tidak sesuai dengan jenis yang di pilih di halaman admin 

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#6039]
1. Halaman Admin : 
<img width="555" alt="image" src="https://user-images.githubusercontent.com/59082428/204129236-69893025-6b4e-4890-aed5-41cb1625c10d.png">
2. Halaman Publicnya seperti ini : 
<img width="501" alt="image" src="https://user-images.githubusercontent.com/59082428/204129249-701f288a-8690-4d62-bce9-c2f7c889554c.png">

**Comment by agungsugiarto** [comment]
mas @vickyrolanda, bisa dijelaskan detail maksudnya?

**Comment by vickyrolanda** [comment]
> mas @vickyrolanda, bisa dijelaskan detail maksudnya?

itu mas di point 1 jenis peraturannya kan "Peraturan Kepala desa Perkades ) namun yang keluar di halaman admin "Perdes" 
gitu mas @agungsugiarto  harusnya sama.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1672
