### ISSUE TITLE
Bug/error: NAMA PERANGKAT DILAYANAN MANDIRI TIDAK KELUAR

### ISSUE THREAD

**Issue by newh44** [OpenSID/OpenSID#6040]
### Jelaskan error yg dialami

nama perangkat yang pakai gelar belakang tidak mucul

### Cara untuk mereplikasi errornya

masuk ke layanan mandiri - perangkat 

### Hasil yg diharapkan

tertulis lengkap nama beserta gelarnya

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/119162490/204137793-b4d33a42-6a51-41c9-9c19-0cbcc48359d7.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.11 rev 3

### Tema Yang Digunakan

silir

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1669
