### ISSUE TITLE
Bug/error: Tulisan tertimpa ketika nama program bantuan terlalu panjang

### ISSUE THREAD

**Issue by yogiperdana** [OpenSID/OpenSID#6041]
### Jelaskan error yg dialami

Tulisan tertimpa ketika nama program bantuan terlalu panjang

### Cara untuk mereplikasi errornya

tambah program bantuan dengan nama yang panjang lalu masuk bagian detail

### Hasil yg diharapkan

Tampilan rapi

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/14155050/204143779-df74f45f-4935-4298-a1b0-aedfbcbe617f.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.11

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1666
