### ISSUE TITLE
Bug/error: Sesuaikan nama Buku Aparat Pemerintah Desa dan Tombol Tambah Peraturan

### ISSUE THREAD

**Issue by mah-mudi** [OpenSID/OpenSID#6042]
### Jelaskan error yg dialami

Belum sesuainya nama Buku Aparat Pemerintah Desa dan Tombol Tambah Peraturan, seperti lampiran permendagri 47 tahun 2016.
![image](https://user-images.githubusercontent.com/57661283/204226742-708a66e8-9116-422a-ba5f-15c0220d2b14.png)

### Cara untuk mereplikasi errornya

1. Buku Administrasi Desa
2. Administrasi Umum

### Hasil yg diharapkan

Sesuaikan nama Buku Aparat Pemerintah Desa dan Tombol Tambah Peraturan, seperti lampiran permendagri 47 tahun 2016.

Buku Pemerintah Desa **diubah menjadi Buku Aparat Pemerintah Desa**, sekaligus sesuaikan juga pada hasil cetaknya.
Tombol Tambah Perdes **diubah menjadi Tambah Peraturan** karena Buku Peraturan Di Desa terdiri dari Peraturan Desa, Peraturan Bersama Kepala Desa, dan Peraturan Kepala Desa sehinggan Tombol Tambah Perdes perlu diganti menjadi Tambah Peraturan.

### Tangkapan layar dan log error

![buku aparat pemerintah desa2](https://user-images.githubusercontent.com/57661283/204226275-49a45c2e-4111-4d9d-ae23-b7a706703ae8.png)
![buku aparat pemerintah desa1](https://user-images.githubusercontent.com/57661283/204226298-031e939b-8989-4219-9eb2-4431d5e466d2.png)
![buku PERATURAN DI DESA1](https://user-images.githubusercontent.com/57661283/204226317-6b0fdc0a-7d90-4cf3-8b56-1793ee2b42f9.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

22.11 Premium beta03

### Tema Yang Digunakan

silir 3.6.3

### Informasi tambahan

beta03

**Comment by andifahruddinakas** [comment]
Bisa disesuaikan sendiri di pengaturan, cek issue https://github.com/OpenSID/OpenSID/issues/5823
