### ISSUE TITLE
Bug/error: proses restore 22.11-premium-beta03

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#6044]
### Jelaskan error yg dialami

saat melakukan restore database, terjadi error 500

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.11-premium-beta03

**Comment by devrakapriyo** [comment]
terlampir database desa yang mengalami error saat restore : https://drive.google.com/drive/folders/1heEDgV0JJl1mcX3xfoocVfPdwQavA3MP?usp=sharing

**Comment by Zoel-WB** [comment]
Ikut tampahan Informasi, File BackUP yg dibackup dengan premium v22.11-rev03 dan V22.11-beta03, file Backup dengan versi ini yg tidak dapat di restore, dari 240 table yg terestore sebelum terjadi error hanya 12 atau 13 table saja.

![image](https://user-images.githubusercontent.com/64481641/204266753-25e16e42-88f3-408e-a084-3c0ed8737b39.png)

Sedangkan hasil back dari versi sebelumnya baik V22.11 maupun v22.11-rev02 dapat di restore kembali dengan aman, maupun di inport dengan phpmyadmin tetap aman.

  
![image](https://user-images.githubusercontent.com/64481641/204267235-ee431733-2cea-4c07-8bc6-84feb8f56271.png)

![image](https://user-images.githubusercontent.com/64481641/204267289-d7124d04-e19c-4e58-95f8-2276489298ca.png)

**Comment by apidong** [comment]
@devrakapriyo @vickyrolanda 
ini sepertinya butuh akses ke server yang bersangkutan. yang bermasalah adalah hasil backup file databasenya, saya cek ada kata yang hilang, tapi saya replikasi backup database memakai db desa lain, tidak ada masalah.

**Comment by apidong** [comment]
> @devrakapriyo @vickyrolanda ini sepertinya butuh akses ke server yang bersangkutan. yang bermasalah adalah hasil backup file databasenya, saya cek ada kata yang hilang, tapi saya replikasi backup database memakai db desa lain, tidak ada masalah.

![image](https://user-images.githubusercontent.com/20056421/204354436-d98d07ca-497d-4036-a115-b6143f71997b.png)
bagian yang hilang

**Comment by andifahruddinakas** [comment]
> terlampir database desa yang mengalami error saat restore : https://drive.google.com/drive/folders/1heEDgV0JJl1mcX3xfoocVfPdwQavA3MP?usp=sharing

Dilihat dari sizenya hanya 5,7 mb, proses backupnya ada yang terhenti / belum lengkap. Jadi kalau direstore pasti akan bermasalah. 

Backup dari install awal +- 7 mb.

**Comment by vickyrolanda** [comment]
mas @devrakapriyo saya test restore db sejauh ini berhasil, mungkin bisa arahkan pengguna test backup ulang lalu restore kembali mas. untuk saat ini sy close terlebih dahulu jika masih terjadi mohon di open lagi.

**Comment by vickyrolanda** [comment]
mas @devrakapriyo  sesuai hasil diskusi, mohon untuk menghubungi pak @Zoel-WB kembali untuk mendapatkan akses keserver untuk menindaklanjuti permasalahan ini.

**Comment by Zoel-WB** [comment]
> mas @devrakapriyo sesuai hasil diskusi, mohon untuk menghubungi pak @Zoel-WB kembali untuk mendapatkan akses keserver untuk menindaklanjuti permasalahan ini.

baik pak saya PM via telegram, karena saya coba pada localhost juga tidak bisa, dan juga saya downgrade dari database v22.10 ke v22.11 -->kemudian ke v22.10 beta03 -->juga belum berhasil-->table hasil restore tetap yg masuk setelah restore ulang 13 table..

baik pak @vickyrolanda saya PM servernya...

**Comment by Zoel-WB** [comment]
saya backup dulu pak ya...

**Comment by devrakapriyo** [comment]
<img width="653" alt="Screen Shot 2022-11-29 at 12 05 39" src="https://user-images.githubusercontent.com/36557759/204443644-0a85e65e-33c9-4bfe-a030-d00ca102304a.png">

mas @apidong setelah saya cek export dari phpmyadmin COLLATE nya ada, untuk db hasil export sudah saya tambahkan di gdrive

**Comment by eddieridwan** [comment]
@apidong @devrakapriyo berarti fitur Backup di OpenSID bermasalah. Tapi pastikan dulu, dengan mengulangi di server @Zoel-WB dan verifikasi hasilnya masih salah.

**Comment by Zoel-WB** [comment]
ada satu website lagi yg kena, website desa pak Astoni Alam, kalau bisa yg pengguna premium jangan melakukan restore dulu...

![image](https://user-images.githubusercontent.com/64481641/204581279-013b7a2e-8893-4f54-a184-941da10c6bbe.png)

**Comment by Zoel-WB** [comment]
Saya coba dilocalhost dapat diperbaiki dengan MariaDB-10.9.3, cuma ada 2 tempat yg tidak dapat terperbaiki otomasis.
1. table "password_reset" token e-mail terlalu panjang.
2. yg tidak otomatis harus perbaikan menual berikut screensote-nya, restore-nya sukses

 
![image](https://user-images.githubusercontent.com/64481641/204617915-1b18a978-7185-40ae-88b7-5d88e8cf9e8c.png)

![image](https://user-images.githubusercontent.com/64481641/204617997-d3a5d8c5-99f5-4c30-868f-507835d87499.png)

![image](https://user-images.githubusercontent.com/64481641/204619090-c30e62b6-165e-4c2d-a367-b1440561d694.png)

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1677
