### ISSUE TITLE
Bug/error: Tidak dapat melalukan pencarian melalui kolom pencarian di menu KIA

### ISSUE THREAD

**Issue by yogiperdana** [OpenSID/OpenSID#6046]
### Jelaskan error yg dialami

Tidak dapat melalukan pencarian melalui kolom pencarian di menu KIA

### Cara untuk mereplikasi errornya

Cari nama ibu atau anak di menu KIA

### Hasil yg diharapkan

Normal

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/14155050/204420049-c8795ad2-1413-483f-a5d3-0799971ee3e7.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.11

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1671
