### ISSUE TITLE
Icon gear dan link pengaturan tidak dapat menampilkan pop token layanan

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#6047]
![image](https://user-images.githubusercontent.com/57283157/204431255-eb168d5e-7fda-482f-b96d-895c14ff9c8c.png)

Kondisi : 
1. Jika data token yang dimasukkan sebelumnya tidak sesuai dengan identitas desa yang dimasukkan.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1674
