### ISSUE TITLE
Bug/error: Update 22.11-premium-rev03 Migrasi Mengenai Collaction

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#6049]
### Jelaskan error yg dialami

<img width="583" alt="image" src="https://user-images.githubusercontent.com/46939846/204574902-0adc0e41-5a52-46d9-acc1-3cd4a44707c9.png">

### Cara untuk mereplikasi errornya

Update OpenSID ke 22.11-premium-rev03 dan iseng akses /periksa

### Hasil yg diharapkan

Collaction otomatis sesuai ketentuan, tidak perlu klik perbaiki.

### Tangkapan layar dan log error

seperti di atas

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.03-premium-rev03

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1689
