### ISSUE TITLE
Bug/error: Apa Fungsi Kolom Perubahan Anggaran Pada Dokumentasi Pembangunan

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#6050]
### Jelaskan error yg dialami

<img width="635" alt="image" src="https://user-images.githubusercontent.com/46939846/204579684-a01f89f0-0c12-4295-8daf-663361654f39.png">

### Cara untuk mereplikasi errornya

1. Masuk Menu Pembangunan
2. Tambah Data Pembangunan
3. Klik Icon Rincian Dokumentasi
4. Tambah Data
5. Akan Muncul Kolom Perubahan Anggaran

Apa fungsi kolom tersebut?
Karena jika diisi sembarang dan disimpan, akan muncul 0 kembali ketika klik edit.

dan mencoba di edit lalu simpan, tetap 0 kembali ketika dibuka edit.

### Hasil yg diharapkan

Perjelas fungsi dari kolom tersebut.

Outputnya dimana?

### Tangkapan layar dan log error

seperti di atas

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Semua

**Comment by agungsugiarto** [comment]
perubahan anggaran akan berubah jika persentase pembangunan sudah mencapai 100% pak @ariandii

**Comment by ariandii** [comment]
Baik, apakah memungkinkan kolom Perubahan Anggaran dapat ditulis jika Persentse Pembangunan diisi 100% ?

Jika belum mencapai, dapat tampilkan anggaran sebelumnya (disable)

**Comment by agungsugiarto** [comment]
mungkin seperti ini aja pak @ariandii
- Jika persentase sudah 100%, tampilkan form `perubahan anggaran`
- Jika persentase  belum mencapai 100% sembunyikan form `perubahan anggaran`

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1708
