### ISSUE TITLE
Permintaan fitur:  sediakan statistik rumah tangga

### ISSUE THREAD

**Issue by ridwan-opt** [OpenSID/OpenSID#6051]
### Apa kekurangan yg ingin diatasi?

Bila memungkinkan
1. Hasil inputan dari modul dtks khususnya di form 3 ( keteragan perumahan) di kumpulka ke dalam satu setatistik ya itu statistik ruma tangga
![Screenshot_2022-11-30-01-49-54-12_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/83778007/204620607-f891301b-e7ad-4170-b5bd-ce1e74873515.jpg)

### Jelaskan solusi yg diinginkan

Dengan adanya statistik rumah di haapkn lebih memudaka Desa dalam menggunakan data seperti contoh:
Jenis dinding : 
1. Tembok....
2. Papan.... Dll
   

### Apakah ada alternatif lain

.

### Untuk versi OpenSID mana

23.01 premium

### Informasi tambahan

.

**Comment by andifahruddinakas** [comment]
Duplicate issue https://github.com/OpenSID/OpenSID/issues/7768
