### ISSUE TITLE
Bug/error: laporan APBDES redirect ke halaman berbeda jika notifikasi gagal tersimpan

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#6059]
### Jelaskan error yg dialami

redirect ke LAPORAN PENDUDUK https://beta.opendesa.id/laporan_penduduk dari https://beta.opendesa.id/laporan_apbdes jika notifikasi gagal tersimpan

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.11-premium-rev03

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1701
