### ISSUE TITLE
Bug/error: popup modal import data persil tidak muncul

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#6060]
### Jelaskan error yg dialami

<img width="1440" alt="Screen Shot 2022-11-30 at 15 52 36" src="https://user-images.githubusercontent.com/36557759/204751430-102aefdc-4c2c-4674-8b15-1960b63a87a1.png">

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.11-premium-rev03

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1702
