### ISSUE TITLE
Bug/error: muncul pesan error 500 setelah input master data analisis tambah periode baru

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#6061]
### Jelaskan error yg dialami

https://beta.opendesa.id/analisis_periode/form

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.11-premium-rev03

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1703
