### ISSUE TITLE
Permintaan fitur: Menambahkan Kode Isian Pilihan Dengan data Otomatis

### ISSUE THREAD

**Issue by newh44** [OpenSID/OpenSID#6066]
### Apa kekurangan yg ingin diatasi?

Ketika Membuat surat untuk warga luar / perusahaan belum ada menu drop down untuk isian laki-laki/perempuan, menikah/belum menikah/cerai sehingga kalau terburu-buru input kadang salah tulisan

### Jelaskan solusi yg diinginkan

![image](https://user-images.githubusercontent.com/119162490/204795437-4bc895e8-4d4f-4527-9958-9193cacbd311.png)
ada menu dropdown

### Apakah ada alternatif lain

![image](https://user-images.githubusercontent.com/119162490/204796614-fe0c06dd-0e46-4dcb-b7de-3278f4046bea.png)
hasil akhir isian jenis kelamin atau status yang pilihan pasti bisa ada menu seperti ini

![image](https://user-images.githubusercontent.com/119162490/204796343-463856e6-ef0e-41a1-9cae-479c2358dc86.png)

### Untuk versi OpenSID mana

22.12 rev 1

**Comment by andifahruddinakas** [comment]
SOLUSI : 
1. Data pilihan diambil otomatis yang sudah disediakan, misalnya Jenis Kelamin diambil dari JenisKelaminEnum.

**Comment by andifahruddinakas** [comment]
![image](https://user-images.githubusercontent.com/57283157/211448835-81f64f90-b42a-453a-b3bd-695c0c475698.png)

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/2193
