### ISSUE TITLE
Bug/error: Error Simpan Data Form Pemberitahuan Page Pengaturan Program Perlindungan Sosial Anggota

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#6067]
### Jelaskan error yg dialami

Error Simpan Data Form Pemberitahuan Page Pengaturan Program Perlindungan Sosial Anggota

### Cara untuk mereplikasi errornya

Klik Tombol DTKS -->Langsung Pada Data Fitur Pengelompokan Rumah Tangga

![image](https://user-images.githubusercontent.com/64481641/204809568-f5e77487-0ddf-493c-a7fa-476624402d97.png)

Pada Form Pemberitahuan Page Pengaturan Program Perlindungan Sosial Anggota
Klik Tombol Simpan.

![image](https://user-images.githubusercontent.com/64481641/204811016-df5c68c5-f7d8-43b4-a317-37b0ee21a04b.png)

![image](https://user-images.githubusercontent.com/64481641/204810388-79285f49-ebd6-42d6-aa27-6ae7cf2ef686.png)

### Hasil yg diharapkan

Agar berfungsi

### Tangkapan layar dan log error

Logs ERROR

PDOException: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`teupinbe_ulangan`.`dtks_pengaturan_program`, CONSTRAINT `FK_dtks_p_program` FOREIGN KEY (`id_bantuan`) REFERENCES `program` (`id`) ON DELETE CASCADE ON UPDATE CASCA
E) in /home/teupinbe/public_html/vendor/illuminate/database/Connection.php:526Stack trace:#0 /home/teupinbe/public_html/vendor/illuminate/database/Connection.php(526): PDOStatement->execute()#1 /home/teupinbe/public_html/vendor/illuminate/database/Connection.php(705): Illuminate\Database\Connection->Illuminate\Database\{closure}('update `dtks_pe...', Array)#2 /home/teupinbe/public_html/vendor/illuminate/database/Connection.php(672): Illuminate\Database\Connection->runQueryCallback('update `dtks_pe...', Array, Object(Closure))#3 /home/teupinbe/public_html/vendor/illuminate/database/Connection.php(533): Illuminate\Database\Connection->run('update `dtks_pe...', Array, Object(Closure))#4 /home/teupinbe/public_html/vendor/illuminate/database/Connection.php(466): Illuminate\Database\Connection->affectingStatement('update `dtks_pe...', Array)#5 /home/teupinbe/public_html/vendor/illuminate/database/Query/Builder.php(3063): Illuminate\Database\Connection->update('update `dtks_pe...', Array)#6 /home/teupinbe/public_html/vendor/illuminate/database/Eloquent/Builder.php(921): Illuminate\Database\Query\Builder->update(Array)#7 /home/teupinbe/public_html/vendor/illuminate/database/Eloquent/Model.php(1072): Illuminate\Database\Eloquent\Builder->update(Array)#8 /home/teupinbe/public_html/vendor/illuminate/database/Eloquent/Model.php(987): Illuminate\Database\Eloquent\Model->performUpdate(Object(Illuminate\Database\Eloquent\Builder))#9 /home/teupinbe/public_html/vendor/illuminate/database/Eloquent/Model.php(885): Illuminate\Database\Eloquent\Model->save(Array)#10 /home/teupinbe/public_html/donjo-app/core/MY_Log.php(206) : eval()'d code(1) : eval()'d code(1807): Illuminate\Database\Eloquent\Model->update(Array)#11 /home/teupinbe/public_html/donjo-app/core/MY_Log.php(206) : eval()'d code(1) : eval()'d code(886): App\Services\DTKSRegsosEk2022k->savePengaturanProgram(Array)#12 /home/teupinbe/public_html/donjo-app/core/MY_Log.php(206) : eval()'d code(1) : eval()'d code(359): App\Services\DTKSRegsosEk2022k->save(Array)#13 /home/teupinbe/public_html/vendor/codeigniter/framework/system/core/CodeIgniter.php(533): Dtks->savePengaturan('2')#14 /home/teupinbe/public_html/index.php(283): require_once('/home/teupinbe/...')#15 {main}Next Illuminate\Database\QueryException: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`teupinbe_ulangan`.`dtks_pengaturan_program`, CONSTRAINT `FK_dtks_p_program` FOREIGN KEY (`id_bantuan`) REFERENCES `program` (`id`) ON DELETE CASCADE ON UPDATE CASCADE) (SQL: update `dtks_pengaturan_program` set `id_bantuan` = 2, `dtks_pengaturan_program`.`updated_at` = 2022-11-30 20:36:08 where `id` = 2) in /home/teupinbe/public_html/vendor/illuminate/database/Connection.php:712Stack trace:#0 /home/teupinbe/public_html/vendor/illuminate/database/Connection.php(672): Illuminate\Database\Connection->runQueryCallback('update `dtks_pe...', Array, Object(Closure))#1 /home/teupinbe/public_html/vendor/illuminate/database/Connection.php(533): Illuminate\Database\Connection->run('update `dtks_pe...', Array, Object(Closure))#2 /home/teupinbe/public_html/vendor/illuminate/database/Connection.php(466): Illuminate\Database\Connection->affectingStatement('update `dtks_pe...', Array)#3 /home/teupinbe/public_html/vendor/illuminate/database/Query/Builder.php(3063): Illuminate\Database\Connection->update('update `dtks_pe...', Array)#4 /home/teupinbe/public_html/vendor/illuminate/database/Eloquent/Builder.php(921): Illuminate\Database\Query\Builder->update(Array)#5 /home/teupinbe/public_html/vendor/illuminate/database/Eloquent/Model.php(1072): Illuminate\Database\Eloquent\Builder->update(Array)#6 /home/teupinbe/public_html/vendor/illuminate/database/Eloquent/Model.php(987): Illuminate\Database\Eloquent\Model->performUpdate(Object(Illuminate\Database\Eloquent\Builder))#7 /home/teupinbe/public_html/vendor/illuminate/database/Eloquent/Model.php(885): Illuminate\Database\Eloquent\Model->save(Array)#8 /home/teupinbe/public_html/donjo-app/core/MY_Log.php(206) : eval()'d code(1) : eval()'d code(1807): Illuminate\Database\Eloquent\Model->update(Array)#9 /home/teupinbe/public_html/donjo-app/core/MY_Log.php(206) : eval()'d code(1) : eval()'d code(886): App\Services\DTKSRegsosEk2022k->savePengaturanProgram(Array)#10 /home/teupinbe/public_html/donjo-app/core/MY_Log.php(206) : eval()'d code(1) : eval()'d code(359): App\Services\DTKSRegsosEk2022k->save(Array)#11 /home/teupinbe/public_html/vendor/codeigniter/framework/system/core/CodeIgniter.php(533): Dtks->savePengaturan('2')#12 /home/teupinbe/public_html/index.php(283): require_once('/home/teupinbe/...')#13 {main}

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Premium v22.11-beta03

### Tema Yang Digunakan

.

**Comment by ruririzal** [comment]
oke

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1687
