### ISSUE TITLE
Permintaan fitur: fitur top align, midle align, bottom align

### ISSUE THREAD

**Issue by newh44** [OpenSID/OpenSID#6068]
### Apa kekurangan yg ingin diatasi?

![image](https://user-images.githubusercontent.com/119162490/204810686-da4f0c90-f583-413b-8dc4-04b98fbf34a1.png)
tabel yang terlalu banyak formatnya midle align sehingga kurang rapi

### Jelaskan solusi yg diinginkan

ada fitur top align, midle align, bottom align selain left,right center yang sudah ada

### Apakah ada alternatif lain

![image](https://user-images.githubusercontent.com/119162490/204811346-6fa060c0-808b-43f3-a9c5-03053080ed09.png)
contoh pada ms excel

### Untuk versi OpenSID mana

22.12 rev 1

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2923
