### ISSUE TITLE
Bug/error: Kolom API OpenDK Key Disable

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#6070]
### Jelaskan error yg dialami

![Screenshot_2022-12-01-10-35-49-10_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/46939846/204960114-366453ad-21b0-4b88-bd20-982fc8878fae.jpg)

### Cara untuk mereplikasi errornya

Masuk menu OpenDK -> Sinkronisasi

Lalu klik Tap Buat Key.

niat ingin mengosongkan kolom seluruhnya, karena data lama sudah tidak digunakan. sehingga berakibat rutin muncul log error mengenai key opendk.

tetapi seluruh kolom bisa dikosongkan kecuali api key tsb disable.

### Hasil yg diharapkan

bisa hapus semua kolom.

### Tangkapan layar dan log error

seperti di atas 

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Semua

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1706/files
