### ISSUE TITLE
Permintaan fitur: Penambahan Detail Kelengkapan Profil Desa

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#6072]
### Apa kekurangan yg ingin diatasi?

Permintaan Penambahan Beberapa Detail Untuk Kelengkapan Data Profil Desa

![image](https://user-images.githubusercontent.com/64481641/205126974-13c4a169-62b4-43dc-b203-ebce7eafdf14.png)

### Jelaskan solusi yg diinginkan

Ada beberapa data tentang keadaan dan riwayat profil desa pada aplikasi opensid masih kurang lengkap, dalam hal ini dimohon untuk setuju untuk ditambahkan beberapa data profil dimaksud yg masih kurang misalnya :

1.  Luas Wilayah Daerah (km²)
     (Misal : Luas : 931.565 Garis keliling : 5,49 ) 
2. Batas Wilayah
    Utara    : 
    Timur    : 
    Selatan  : 
    Barat     : 

3. Tipologi berdasarkan hamparan
    (Misal : Desa Dataran Rendah)

4. Tipologi berdasarkan mata pencaharian
     (Misal : Desa Pertanian)

5. Tipologi berdasarkan perkembangan
    (Misal : Desa Berkembang)

6. Tahun Pembentukan
    (Misal : 1400)

7. Dasar Hukum
    (Misal : UU No.6 Tahun 2014)

8. Potensi Desa
    (Misal : Pertanian Lahan Basah & Kering, Penggemukan Sapi)

### Apakah ada alternatif lain

Data-data ini penting sekali untuk generasi penerus yg terkadang letak desa sendiri diantara banyak lupa tentang keadaan desanya, kemudian kenapa pentingnya seperti batas-batas desa, karena kondisi di desa banyak terjadi ketimpangan perbatasan, bahkan ada desa yg sengaja menerobos desa lain membuat perbatasan yg lain..

### Untuk versi OpenSID mana

v23.01-premium

### Informasi tambahan

.

**Comment by rudiansyahyunanda** [comment]
Setuju dengan usulan Potensi Desa, apalagi jika dapat dibuat menu tersendiri seperti halnya Lapak . ini jauh dibutuhkan dibandingkan fokus regsosek yang sudah ada instansi yang membidangi.

**Comment by eddieridwan** [comment]
@rudiansyahyunanda @Zoel-WB perhatikan adanya issue https://github.com/OpenSID/OpenSID/issues/5519 untuk ditambahkannya modul Prodeskel. Tugas itu sedang dicarikan programmer luar yg bersedia memberikan penawaran untuk mengerjakan modul Prodeskel tsb. Pembuatan modul Prodeskel adalah kelanjutan strategi Satu Data OpenSID, yg telah diawali dengan pembuatn modul DTKS.

Sangat mungkin permintaan di issue teman2 sdh tercakup dalam modul Prodeskel itu.

**Comment by andifahruddinakas** [comment]
Duplicate of https://github.com/OpenSID/OpenSID/issues/7693
