### ISSUE TITLE
Bug/error: Tidak bisa upload dokumen penduduk format .pdf di Pages Admin

### ISSUE THREAD

**Issue by Wiliyantoro** [OpenSID/OpenSID#6073]
### Jelaskan error yg dialami

ketika operator web ingin mengupload dokumen penduduk dalam format .pdf muncul error, namun dalam bentuk .jpg sucsess
kalau dilihat dari sisi keamanan mungkin issue ini perlu di review kembali, karna yg upload adalah operator desa,
issue sebelumnya diperbaiki terbatas hanya di sisi layanan mandiri namu yg kena imbasnya adalah sisi page admin yg dikelola oleh operator.

### Cara untuk mereplikasi errornya

home->penduduk-> klik nik -> manajemen dokumen -> tambah dokumen -> upload

### Hasil yg diharapkan

mungkin validasi saja di layanan mandiri karna berhubungan dengan warga.
pada sisi operator desa, ijinkan upload dokumen penduduk dalam bentuk pdf.

### Tangkapan layar dan log error

![photo_2022-12-02_11-46-59](https://user-images.githubusercontent.com/44520382/205210553-f7727cb4-7089-40dd-a098-aca29c22e664.jpg)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.12-premium

**Comment by balongbesuk** [comment]
aplikasi pdf converterny cb d ganti

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR Dokumen penduduk
