### ISSUE TITLE
Perlu perbaikan terkait efaktor api tracksid yang tidak respon di beberapa server.

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#6074]
### Jelaskan error yg dialami

![image](https://user-images.githubusercontent.com/36557759/205215403-72a983e7-a11c-4be2-a59c-b3f349c692b4.png)

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.12-premium

**Comment by devrakapriyo** [comment]
setelah di cek lebih lanjut terjadi error 500
<img width="1440" alt="Screen Shot 2022-11-30 at 15 52 36" src="https://user-images.githubusercontent.com/36557759/205235019-aa0b3822-1c6d-4fd1-bb66-be3319efb2cd.png">

dan ada beberapa asset respon 404
![image](https://user-images.githubusercontent.com/36557759/205235132-5f790ee1-6ecd-477f-8e0c-bc36d3db1902.png)

**Comment by andifahruddinakas** [comment]
Mas @vickyrolanda, informasi penting sebaiknya di blur

**Comment by vickyrolanda** [comment]
> Mas @vickyrolanda, informasi penting sebaiknya di blur

sudah sy hapus mas bagian itu

**Comment by usmanrahdi** [comment]
saya juga mengalami hal yang serupa
![2022-12-03_14h28_42](https://user-images.githubusercontent.com/95505631/205429083-64b014c2-6c38-4fd9-ae98-480b8f98f897.png)

**Comment by vickyrolanda** [comment]
Perbaikan refaktor api tracksid yang tidak respon di beberapa server namun jika menggunakan teknis yang sebelumnya website berjalan dengan baik.

Akibat dari perubahan teknis di bawah mengakibatkan respon timeout.
Terkait PR https://github.com/OpenSID/premium/pull/1562

**Comment by eddieridwan** [comment]
@vickyrolanda seperti sudah dibahas, masalahnya bukan terkait API di TrackSID.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1714
