### ISSUE TITLE
Bug/error: Penjumlahan pada kolom JLH ART dan Kolom Jumlah Keluarga, bila di mungkinkan

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#6078]
### Jelaskan error yg dialami

Penjumlahan pada kolom JLH ART dan Kolom Jumlah Keluarga, bila di mungkinkan :

![image](https://user-images.githubusercontent.com/64481641/205431790-c9e40d79-6850-464c-bcbb-4f927d5c42b6.png)

### Cara untuk mereplikasi errornya

.

### Hasil yg diharapkan

.

### Tangkapan layar dan log error

.

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.12-Premium

### Tema Yang Digunakan

.

### Informasi tambahan

.

**Comment by ruririzal** [comment]
![image](https://user-images.githubusercontent.com/28647065/205442472-ed922b17-96b9-4b89-8646-0f6403bea426.png)

bagaimana kalau begini saja, 
- saya munculkan data krt, 
- saya pindahkan jumlah keluarga, dusun, rt, dan rw ke dalam kolom krt, 
- untuk jumlah art saya ganti menjadi jumlah anggota dan untuk keluarga lain yg tinggal dalam rumah tangga yg sama dengan krt, saya tambahkan simbol +

**Comment by ruririzal** [comment]
dengan struktur rumah tangga dan masing2 keluarga seperti berikut
![image](https://user-images.githubusercontent.com/28647065/205442714-bd1f45ff-6e60-44ec-8875-74eb9580e44a.png)

dan

![image](https://user-images.githubusercontent.com/28647065/205442947-5cc75486-8840-43c1-8ee2-228397b65f94.png)

**Comment by Zoel-WB** [comment]
> ![image](https://user-images.githubusercontent.com/28647065/205442472-ed922b17-96b9-4b89-8646-0f6403bea426.png)
> 
> bagaimana kalau begini saja,
> 
> * saya munculkan data krt,
> * saya pindahkan jumlah keluarga, dusun, rt, dan rw ke dalam kolom krt,
> * untuk jumlah art saya ganti menjadi jumlah anggota dan untuk keluarga lain yg tinggal dalam rumah tangga yg sama dengan krt, saya tambahkan simbol +

Saya kira boleh juga dengan cara ini....

**Comment by Zoel-WB** [comment]
Data Regsosek juga dibuat seperti ini, ilustrasi bertingkat.

**Comment by vickyrolanda** [comment]
mas @ruririzal 
jumlah anggota terdapat 2 : 
<img width="772" alt="image" src="https://user-images.githubusercontent.com/59082428/205581374-40b733ba-a44e-4c9d-977d-2e6a543d38ed.png">
yang tampil hanya 1 anggota : 
<img width="792" alt="image" src="https://user-images.githubusercontent.com/59082428/205581789-86f55098-0e5d-4f01-97dc-f60f5be3e6a8.png">

Lalu yang icon mata di hilangkan saja mas, biar di angkanya saja yg bisa di klik.

**Comment by ruririzal** [comment]
Mas @vickyrolanda, Struktur keluarga dan rumah tangganya bagaimana mas? 

Bisa di replikasi di beta kah? Biar bisa saya donwload dan coba cek di lokal dengan data tersebut

**Comment by ruririzal** [comment]
Mas @vickyrolanda, apakah perbedaan jumlah anggota terjadi karena 
1. buat data dtks/ data dtks sudah dibuat sebelumnya
2. kemudian menambah/menguragi data anggota rumah tangga

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1712
