### ISSUE TITLE
Perbaikan refaktor api tracksid yang tidak respon di beberapa server.

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#6079]
Perbaikan refaktor api tracksid yang tidak respon di beberapa server namun jika menggunakan teknis yang sebelumnya website berjalan dengan baik.

Akibat dari perubahan teknis di bawah mengakibatkan respon timeout.
Terkait PR https://github.com/OpenSID/premium/pull/1562

**Comment by andifahruddinakas** [comment]
Duplicate issue https://github.com/OpenSID/OpenSID/issues/6074
