### ISSUE TITLE
Bug/error: Rapikan Tulisan

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#6080]
### Jelaskan error yg dialami

Tulisan Panduan Impor Data Kependudukan tidak rapi.

### Cara untuk mereplikasi errornya

1. Masuk menu Kependudukan -> Penduduk
2. Klik Impor/Expor
3. Klik Impor Penduduk

Perhatikan tulisannya.

### Hasil yg diharapkan

Bisa dirapikan agar tidak keluar kolom.

### Tangkapan layar dan log error

<img width="264" alt="screenshot_764" src="https://user-images.githubusercontent.com/46939846/205554684-b3fee8f1-9a7b-41b0-b019-5ba23f023fd5.png">

<img width="262" alt="screenshot_763" src="https://user-images.githubusercontent.com/46939846/205554687-6fec567c-245b-4f93-ba5b-bcf62569e508.png">

<img width="754" alt="screenshot_762" src="https://user-images.githubusercontent.com/46939846/205554691-4fcbf4a5-bc81-4fc0-ba5f-47fd0150c947.png">

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Seluruhnya

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1727
