### ISSUE TITLE
Permintaan fitur:  Lampiran F-1.06

### ISSUE THREAD

**Issue by wahyabiantara** [OpenSID/OpenSID#6081]
### Apa kekurangan yg ingin diatasi?

Setiap perubahan Biodata Penduduk dan Kartu Keluarga, Disdukcapil saat ini membutuhkan Surat Pernyataan Perubahan Elemen Data Kependudukan sebagai salah satu syarat dengan melampirkan Formulir F-1.06

### Jelaskan solusi yg diinginkan

Ditambahkan Surat Pernyataan Perubahan Elemen Data Kependudukan pada Layanan Surat secara default dengan format lampiran F-1.06 seperti pada link http://dukcapil.meranginkab.go.id/uploads/formulir/formulir-f1-06.pdf

### Apakah ada alternatif lain

Tidak ada

### Untuk versi OpenSID mana

Semua Versi

**Comment by andifahruddinakas** [comment]
Duplicate of https://github.com/OpenSID/OpenSID/issues/7319
