### ISSUE TITLE
Bug/error: Sesuaikan Opsi dan Tombol Pada Buku Peraturan Di Desa

### ISSUE THREAD

**Issue by mah-mudi** [OpenSID/OpenSID#6082]
### Jelaskan error yg dialami

Belum sesuainya Opsi dan Tombol Pada Buku Peraturan Di Desa

### Cara untuk mereplikasi errornya

1. Buku Administrasi Desa - Administrasi Umum
2. Buku Peraturan Di Desa

### Hasil yg diharapkan

Hasil yang diharapkan
1. Tombol Tambah Perdes diubah menjadi Tombol Tambah Peraturan, karena di Buku Peraturan Di Desa terdiri dari Peraturan Desa, Peraturan Bersama Kepala Desa dan Peraturan Kepala Desa.
2. Ganti Opsi Status Aktif menjadi Berlaku, Tidak Aktif menjadi Dicabut/Tidak Berlaku. 
3. Ganti Opsi Jenis Peraturan menjadi hanya tiga opsi yaitu Peraturan Desa, Peraturan Bersama Kepala Desa dan Peraturan Kepala Desa. Hilangkan Opsi yang tidak diperlukan.

### Tangkapan layar dan log error

![buku peraturan di desa 11](https://user-images.githubusercontent.com/57661283/205631123-c403637d-e1bb-4330-8c78-adc8e21d14cd.png)
![buku peraturan di desa 12](https://user-images.githubusercontent.com/57661283/205631147-2d93d0c2-3b9f-424e-9e8d-4a55f095e4ba.png)
![buku peraturan di desa 13](https://user-images.githubusercontent.com/57661283/205631168-51bc127f-02b8-4ca1-9d98-abd2895237d8.png)
![buku peraturan di desa 14](https://user-images.githubusercontent.com/57661283/205631186-b18f7143-8e15-4904-bddc-bd7ab01a3d62.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

22.12 Premium

### Tema Yang Digunakan

silir 3.6.3

### Informasi tambahan

![image](https://user-images.githubusercontent.com/57661283/205632117-ec406d73-7c06-4cf5-a686-db817c5fbb5b.png)

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1728
