### ISSUE TITLE
Bug/error: Menambah Anggota Rumah Tangga dari Kelompok Keluarga ( Entri dari Status Hub. Kepala Keluarga)

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#6084]
### Jelaskan error yg dialami

Saat menambah anggota rumah tangga dari KK lain input satu KK, penduduk yg telah beribah status dasar ikut ditampilkan dan dapat dipilih/diconteng  untuk ditambahkan menjadi anggota rumah tangga

### Cara untuk mereplikasi errornya

![image](https://user-images.githubusercontent.com/64481641/205707457-851c69ba-86e5-4240-a7bf-3f5d4512e23d.png)

### Hasil yg diharapkan

Agar penduduk yg telah berubah status dasar supaya tidak tampil lagi dalam daftar anggota keluarga yg akan ditambahkan menjadi anggota rumah tangga.

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/64481641/205707726-8fc199b6-8322-415d-9445-118a289f690f.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.12 Premium-rev01

### Tema Yang Digunakan

.

### Informasi tambahan

.

**Comment by scqolbu24** [comment]
Mas @devrakapriyo dan Mas @vickyrolanda, bisa minta tolong dibantu cek issue ini, saya coba replikasi dalam 1 KK anggota buat status dasar 1 pindah dan 1 mati, namun belum ketemu bug tersebut.

**Comment by devrakapriyo** [comment]
<img width="1440" alt="Screen Shot 2022-12-06 at 17 14 25" src="https://user-images.githubusercontent.com/36557759/205883547-edc1ea2f-18f2-4705-932f-60d27b23b2b3.png">

pak @Zoel-WB saya cek di berputar tidak seperti screenshot yang pak zoel lampirkan

**Comment by Zoel-WB** [comment]
Yang saya panggil termasuk KK lama, mungkin rocker kepala keluarga, kepala keluarga asli meninggal dan diganti ke Isteri yg masih hidup menjadi Kepala Keluarga, mungkin kejadiannya seperti itu, sehingga nomor KK-nya masih melekat pada Kepala Keluarga lama sehingga muncul lagi pada saat tak terduga seperti untuk menambah anggota rumah tangga. mungkin seperti itu kejadian masih menggunakan nomor KK yg sama belum terjadi perubahan KK.

Karena memang serba salah masih terkait dengan Kepala Keluarga dan Nomor KK, di desa karena sangkutan dengan masalah2 bansos jadi tidak serta merta kepala keluarga meninggal langsung berganti KK disebabkan banyak lembaga-lembaga masih saja berlaku nomor kk lama seperti dalam data DTKS kemensos, hingga saat ini walaupun tiap saat ada perubahan update pada data verval, akan tetapi saat bantuan meluncur tetap masih terdapat bansos mengikat ke nomor kk dan kepala keluarga lama.

**Comment by andifahruddinakas** [comment]
Mas @devrakapriyo, sy coba tdk ada masalah.
