### ISSUE TITLE
Error Setelah Migrasi DB 22.12.01

### ISSUE THREAD

**Issue by AlfaridzhE15** [OpenSID/OpenSID#6086]
Mohon bantuan untu masalah ini

Sebuah Kesalahan Basis Data Telah Terjadi
<p>1146</p><p>Table 'u7665045_swkdb.log_bulanan' doesn't exist</p>

![Uploading Screenshot_2022-12-06-11-35-28-50_40deb401b9ffe8e1df2f1cc5ba480b12.jpg…]()

**Comment by apidong** [comment]
cara mengatasinya sudah ada di forum, link ada dibawah
https://forum.opendesa.id/d/162-cara-mengatasi-keslahan-basis-data-log-bulanan-doesnt-exist
