### ISSUE TITLE
Bug/error: Disable Menu tidak berfungsi

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#6087]
### Jelaskan error yg dialami

https://berputar.opendesa.id/pengaduan

https://berputar.opendesa.id/lapak

https://berputar.opendesa.id/pembangunan

### Cara untuk mereplikasi errornya

3 link di atas masih bisa diakses walau menunya tidak dibuat.

### Hasil yg diharapkan

sesuai dengan status pada Admin Web -> Menu

ada atau belum dibuat, termasuk digembok atau tidak.

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Berputar

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1736
