### ISSUE TITLE
Tambahkan filter tanggal untuk rekapan buku tamu

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#6089]
pada laporan rekapan buku tamu bisa ditambahkan rekapan seperti gambar berikut ini : 
<img width="796" alt="image" src="https://user-images.githubusercontent.com/59082428/206020227-0acaf251-07f9-45c8-9231-852a8b24e630.png">

1. Perlu ditambahkan filter pertanggal untuk export laporan ke excel  & cetak 
2. Perlu ditambahkan fitur cetak 
3. Perlu tampil jam pada hasil tanggal input user.

**Comment by ruririzal** [comment]
bisa di cek mas @vickyrolanda

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/1954
