### ISSUE TITLE
Data Wilayah Tidak Sinkron (di Laman Web sama di Laman Admin)

### ISSUE THREAD

**Issue by abieroni** [OpenSID/OpenSID#609]
Mohon para master dimana letak kesalahan saya dalam mengimport data penduduk kok data statistik wilayah yang di tampilkan antara di Laman Web sama di Laman Admin tidak sinkron/tidak sama.
Mohon pencerahannya, terimakasih.
![front](https://user-images.githubusercontent.com/25345246/30166493-b207f94e-940d-11e7-8284-75c8b23abf14.jpg)
![back](https://user-images.githubusercontent.com/25345246/30166545-d8bdf5a2-940d-11e7-9d68-514f6684265b.jpg)

**Comment by siayi** [comment]
data yang betul yang mana, yang Laman Web atau Laman Admin?

**Comment by abieroni** [comment]
Yang Laman Admin Om?

2017-09-07 21:24 GMT+07:00 Ayi Sumarna <notifications@github.com>:

**Comment by eddieridwan** [comment]
Masalah seperti ini biasanya disebabkan karena ada data di tweb_wil_clusterdesa yang tidak sempurna/lengkap untuk suatu dusun. Sayangnya struktur tabel in cukup rumit (warisan SID CRI). Coba cari baris dusun 'aneh' di tabel itu, dan hapus. (Jangan lupa backup dulu database anda).

**Comment by eddieridwan** [comment]
@abieroni , kami dapat membantu melacak masalah data anda, jika anda kirimkan backup database anda ke inbox saya. Jangan dilampirkan di sini, karena data di sini bisa diakses publik. Sebelumnya juga ada yg mengalami masalah serupa. Nanti contoh masalah anda bisa digunakan untuk membuat petunjuk bagi desa lain cara melacak dan memperbaiki masalah seperti ini.

**Comment by eddieridwan** [comment]
Di tabel tweb_wil_clusterdesa, terlihat ada baris duplikat untuk dusun Pulau Maju. Hapus baris2 itu.

Baris duplikat itu mungkin muncul pada waktu impor data, di mana sebagian data tertulis sebagai Pulau_Maju dan yang lain tertulis PULAU MAJU.

<img width="1254" alt="data_wilayah_duplikat" src="https://user-images.githubusercontent.com/249563/30190754-b017478a-947f-11e7-8ac9-0c83059bc0c6.png">

**Comment by abieroni** [comment]
@eddieridwan akan saya coba om.

**Comment by eddieridwan** [comment]
@abieroni mohon jelaskan langkah2 yang anda lakukan untuk mengimport data penduduk dan mengubah Wilayah Administrasi sampai terjadinya kesalahan data yang anda alami. Kami tidak bisa mengulangi kesalahan data ini.

**Comment by abieroni** [comment]
@eddieridwan mohon maaf bung, kalau waktunya 1 jam utk buat panduannya mgkin saya tidak bisa. soalnya jaringan internet di daerah saya ini tidak mendukung, masih tercover jaringan edge (e) jadi jika connect menggunak laptop tidak bisa.
sekali lagi mohon maaf, mungkin kalau saya ke kota nnt saya buat panduannya.
Terimakasih

**Comment by eddieridwan** [comment]
@abieroni maksudnya, jika anda jelaskan proses impor data yang anda lakukan (jelaskan di issue ini), kami bisa coba melacak lebih lanjut, dan berusaha memperbaiki scriptnya untuk mencegah terjadinya error seperti ini.

**Comment by abieroni** [comment]
Disni saya akan jelaskan langkah-langkah import data penduduk yang saya lakukakan sehingga terjadi kesalahan pada jumlah RT di Wilayah Administrasi. Ketika itu kalau tidak salah saya menggunakan Opensid V1.9, karna saya pikir import data menggunakan cara biasa (import satu-persatu melalui menu penduduk) akan cukup memakan waktu. Jadi saya import data penduduk menggunakan cara cepat yaitu “Import BIP”. Berikut langkah-langkah yang saya lakukan. 
(disini yang saya gunakan Data BIP dari Disdukcapil)

1. Saya menyipakan Data BIP
2. Saya import Data BIP melalui menu Database, Tab Import BIP di Laman Admin OpenSID.
![l1](https://user-images.githubusercontent.com/25345246/30386087-2a7a860c-98d3-11e7-9518-f2ef9b53cbf9.jpg)

3. Setelah saya import hasilnya seperti gambar di bawah ini.
![l2](https://user-images.githubusercontent.com/25345246/30386202-72e74c68-98d3-11e7-8828-ad114c66cfec.jpg)
Di kolom Alamat, Dusun, dan RW tidak sesuai dengan Data Penduduk yang saya Import menggunakan Data BIP.

4. Untuk mengatasi hal tersebut agar saya tidak mengubah data satu-persatu saya memanfaatkan tombol “Ubah Alamat/Pindah Keluarga Dalam Desa”yang ada di kolom Aksi di Menu Penduduk, Tab Keluarga.
![l3](https://user-images.githubusercontent.com/25345246/30386422-f9a08e0e-98d3-11e7-85e2-b43abff8b108.jpg)
Akan tetapi sebelum melakukan ini, terlebih dahulu saya melakukan Tambah Dusun, RW, dan RT di Wilayah Administrasi Dusun pada Menu Penduduk, Tab Wilayah Administrasi.

5. Selanjutnya saya pindah satu-persatu Data Penduduk yang tidak cocok tadi dengan tombol “Ubah Alamat” menyesuaikan dengan Wilayah Administrasi mereka.
![l3](https://user-images.githubusercontent.com/25345246/30386464-15f83eb2-98d4-11e7-9ba4-8717bf21636d.jpg)

![l4](https://user-images.githubusercontent.com/25345246/30386519-32f13fe6-98d4-11e7-802e-f16c8efe6287.jpg)

![l5](https://user-images.githubusercontent.com/25345246/30386557-4a8bc612-98d4-11e7-860c-eb21937eb33a.jpg)
Makan hasilnya seperti gambar di atas. 

6. Begitu terus yang saya lakukan sehingga tanpa saya sadari terjadi kesalahan di Wilayah Administrasi.

7. Itulah langkah-langkah Import Data Penduduk di OpenSID yang saya lakukan. Semoga bermanfaat dan dapat di mengerti, karna saya kurang bias untuk menulis. Sekian terimakasih.

**Comment by MUHAMMADRANGSEL** [comment]
#closed

**Comment by eddieridwan** [comment]
@RedhoAri : issue bukan tempat bertanya penggunaan OpenSID. Issue ini untuk membahas satu masalah saja, sesuai dengan judul issue ini.

Silakan gabung di https://www.facebook.com/groups/OpenSID dan bertanya di situ. Dan baca panduan di https://github.com/OpenSID/OpenSID/wiki.

**Comment by eddieridwan** [comment]
@abieroni : terima kasih atas penjelasan anda. Masalahnya mungkin ada di data BIP yg diimport plus langkah tambah wilayah/pindah wilayah yg dilakukan --- yg agak sukar diulangi.

Ok, kami akan tutup issue ini. Tapi kalau ada masalah seperti ini lagi, silakan buat issue lagi.
