### ISSUE TITLE
Bug/error: Tidak dapat mengembalikan status dasar pada log penduduk

### ISSUE THREAD

**Issue by wahyabiantara** [OpenSID/OpenSID#6093]
### Jelaskan error yg dialami

Tidak bisa mengembalikan penduduk yang status dasarnya meninggal melalui Log Penduduk

### Cara untuk mereplikasi errornya

Langkah-langkah yang dilakukan:
1. Klik menu penduduk
2. Pilih Aksi lainnya > Log Penduduk
3. Klik Kembalikan Status Dasar pada penduduk meninggal
4. Muncul pesan, Data Gagal Tersimpan

### Hasil yg diharapkan

Fungsi mengembalikan status dasar kembali seperti semula, dimana jika ada penduduk mati dan ingin dikembalikan statusnya menjadi hidup, dapat berfungsi kembali.

### Tangkapan layar dan log error

![Screenshot_2022-12-07-11-46-49-59_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/4361979/206083434-a759d2a1-6e01-429c-83ad-569cb5aa8c6b.jpg)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Versi 22.12-Premium

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1742

**Comment by wahyabiantara** [comment]
Pak @vickyrolanda saat ini saya tidak dapat mengakses versi PR tersebut. Mohon petunjuk bagaimana caranya agar saya bisa akses ke repo tersebut. Terima kasih
