### ISSUE TITLE
Bug/error: website demo halaman berlangganan selalu reload

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#6094]
### Jelaskan error yg dialami

https://beta.opendesa.id/index.php/pelanggan

https://berputar.opendesa.id/index.php/pelanggan

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.12-premium-rev01

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1753
