### ISSUE TITLE
Tidak ada tombol hapus di semua menu di opensid

### ISSUE THREAD

**Issue by rinafah** [OpenSID/OpenSID#6098]
### Jelaskan error yg dialami

Kenapa di setiap menu baik itu di wilayah administrasi, surat menyurat, kependudukan, admin web, bantuan daan seterusnya tidak muncul tombol hapus sehingga ketika ada kekeliruan pengisian di dapat menghapus

### Cara untuk mereplikasi errornya

.

### Hasil yg diharapkan

mendapatkan solusi bagaimana cara untuk memunculkan tombol hapus

### Tangkapan layar dan log error

<img width="756" alt="4" src="https://user-images.githubusercontent.com/120072938/206343998-d9d7e71b-0cd7-4215-9599-9c4227dfbf03.PNG">

<img width="737" alt="5" src="https://user-images.githubusercontent.com/120072938/206344385-27659166-c1b0-41d9-827e-41530e4aa793.PNG">

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.07

### Tema Yang Digunakan

netra

### Informasi tambahan

.

**Comment by vickyrolanda** [comment]
ijin pak @rinafah bisa bantu check account yang di gunakan dan mungkin bisa dicheck group di penggunanya pak

**Comment by rinafah** [comment]
<img width="754" alt="s" src="https://user-images.githubusercontent.com/120072938/208335623-e53d24d9-75d2-43d9-9269-7cc8930d46b5.PNG">

saya sudah masuk di menu account.. gambar di atas merupakan screenshoot dari menu account di opensid saya.. saya masuk sebagai admin desa..  di situ juga tidak muncul tombol untuk menambah pengguna
nah ketika saya klik di pengaturan grup tidak bisa dan muncul pesan seperti ini

<img width="762" alt="j" src="https://user-images.githubusercontent.com/120072938/208336731-4bae45d0-b7e7-4d7d-aeeb-0baabac19127.PNG">

kenapa seperti itu, dan bagaiman solusinya mohon bantuannya terimakasih

**Comment by devrakapriyo** [comment]
pak @rinafah setelah saya cek menggunakan versi OpenSID 22.07 umum sesuai yang di gunakan desa dengan menggunakan akun Admin, tombol hapus muncul

<img width="1440" alt="Screen Shot 2022-12-22 at 12 21 12" src="https://user-images.githubusercontent.com/36557759/209064823-24a3b6fc-514f-462b-a9f2-9008d2b95137.png">

<img width="1440" alt="Screen Shot 2022-12-22 at 12 26 36" src="https://user-images.githubusercontent.com/36557759/209064848-a9a55c50-1882-4f65-8af9-ed2657635297.png">

dan perlu di cek juga pada table di database, apakah ada perubahan hak akses hapus pada role Admin

untuk sementara issue di close
