### ISSUE TITLE
Permintaan fitur: [TinyMCE] Penambahan FONT BALI SIMBAR

### ISSUE THREAD

**Issue by Wiliyantoro** [OpenSID/OpenSID#6100]
### Apa kekurangan yg ingin diatasi?

di Fitur Surat TinyMCE belum tersedianya Font BALI SIMBAR

### Jelaskan solusi yg diinginkan

Penambahan Font Bali SIMBAR digunakan sebagai KOP NASKAH SURAT DINAS
![image](https://user-images.githubusercontent.com/44520382/206358750-84bb298f-ad5b-4770-9990-465640155b4a.png)

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

v23.01-premium

### Informasi tambahan

untuk FONT Saya lampirkan di link berikut :
https://drive.google.com/file/d/1chvSfuE2CoR8XvKT6wCwZpBgJl8zKw-Z/view?usp=sharing

**Comment by tobagus6911** [comment]
iya betul mohon untuk ada font bali

**Comment by andifahruddinakas** [comment]
https://github.com/OpenSID/OpenSID/issues/6546

**Comment by andifahruddinakas** [comment]
akan diterapkan di issue https://github.com/OpenSID/OpenSID/issues/6546
