### ISSUE TITLE
Bug/error: tema natra artikel home overflow

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#6101]
### Jelaskan error yg dialami

<img width="1440" alt="Screen Shot 2022-12-08 at 13 59 40" src="https://user-images.githubusercontent.com/36557759/206380315-1b626298-0382-4f3d-8949-0c13c159c428.png">

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.12-premium-rev01

### Tema Yang Digunakan

natra

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1800
