### ISSUE TITLE
Bug/error: tema natra artikel home beri jarak samping kanan

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#6102]
### Jelaskan error yg dialami

<img width="1440" alt="Screen Shot 2022-12-08 at 13 54 53" src="https://user-images.githubusercontent.com/36557759/206380973-bef3434e-97a3-4805-aa2c-f2c5c7074e9e.png">

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.12-premium-rev01

**Comment by totoprayogo1916** [comment]
pernah di up disini: #4818 / https://github.com/OpenSID/tema-natra/issues/88

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1800/
