### ISSUE TITLE
Bug/error: tema esensi artikel home posisi tidak pada tempatnya

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#6103]
### Jelaskan error yg dialami

<img width="1440" alt="Screen Shot 2022-12-08 at 13 56 36" src="https://user-images.githubusercontent.com/36557759/206381471-96ebc162-d60b-45c6-a633-0df533b11e78.png">

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.12-premium-rev01

### Tema Yang Digunakan

esensi

_No response_

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1799
