### ISSUE TITLE
Bug/error: Penambahan Jumlah Isi Karakter Maksimal 200 Karakter pada Judul Artikel

### ISSUE THREAD

**Issue by mah-mudi** [OpenSID/OpenSID#6104]
### Jelaskan error yg dialami

Judul artikel minimal 5 karakter dan maksimal 100 karakter. Jika maksimal 100 karakter mengakibatkan judul artikel tidak bisa dibuat sesuai narasi.

### Cara untuk mereplikasi errornya

1. Admin Web
2. Artikel

### Hasil yg diharapkan

Dengan Judul Artikel dengan Jumlah Maksimal 200 Karakter, membantu admin/operator membuat judul sesuai dengan narasi.

### Tangkapan layar dan log error

![198227340-878837db-d91c-4c0b-b95e-acfc0da160a5](https://user-images.githubusercontent.com/57661283/206387545-45536af0-d8d5-4a4f-a3e5-44df8e8e24ae.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

22.12 Premium rev01

### Tema Yang Digunakan

silir 3.6.3

### Informasi tambahan

-

**Comment by totoprayogo1916** [comment]
Judul artikel pada hasil pencarian Google yang tampil, maksimal sekitar 60-65 karakter
sudah termasuk judul situs, spasi, tanda hubung dll

Jika berlebihan maka akan disembunyikan dengan `...` 

solusinya mungkin bisa ditambahkan "sub-judul" pada artikelnya ...

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1748
