### ISSUE TITLE
Bug/error: Jumlah Permohonan pada Administrator dan Akun Kepala Desa tidak sesuai

### ISSUE THREAD

**Issue by mah-mudi** [OpenSID/OpenSID#6105]
### Jelaskan error yg dialami

umlah Permohonan pada Administrator dan Akun Kepala Desa tidak sesuai

### Cara untuk mereplikasi errornya

1. Layanan Surat
2. Arsip Layanan 

### Hasil yg diharapkan

Jumlah Permohonan Surat di akun administrator dan akun kepala desa dapat sesuai

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/57661283/206388392-bfb96888-3d26-41a1-a65f-bd088186ef9b.png)
![image](https://user-images.githubusercontent.com/57661283/206388511-e2241808-5248-4e2c-adc0-47c7a6ec23d4.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

22.12 Premium rev01

### Tema Yang Digunakan

silir 3.6.3

### Informasi tambahan

-

**Comment by vickyrolanda** [comment]
pak @mah-mudi apakah sudah klik tombol perbaiki pada arsip surat ? karena fungsi itu untuk memberikan log surat. 
mas @devrakapriyo  bisa bantu buatkan panduannya mas untuk issue seperti ini dan mungkin bisa ditambahkan di forum mas agar pengguna tau fungsi perbaiki di arsip surat.

**Comment by devrakapriyo** [comment]
pak @mah-mudi sesuai informasi dari mas @vickyrolanda solusi nya itu seperti yang baru saya posting di forum 

https://forum.opendesa.id/d/279-fitur-tombol-perbaiki-pada-permohonan-surat

**Comment by mah-mudi** [comment]
@vickyrolanda @devrakapriyo masih belum berubah, meski klik perbaiki pada akun administrator dan akun kepala desa
![image](https://user-images.githubusercontent.com/57661283/207232692-1a9e48e6-d512-4367-89d5-047a32a6bb3d.png)

**Comment by vickyrolanda** [comment]
pak @mah-mudi mungkin jika boleh bisa kirim hasil backup database ke telegram saya agar sy coba analisa dimana letak masalahnya knpa tidak bisa berubah statusnya arsipnya.

**Comment by mah-mudi** [comment]
@vickyrolanda ok pak

**Comment by devrakapriyo** [comment]
pak @mah-mudi untuk sementara issue di close
karena database belum kami terima, sehingga belum bisa pengecekan lebih lanjut

**Comment by mah-mudi** [comment]
@devrakapriyo sudah saya kirim barusan backup an database nya ke mas @vickyrolanda .
