### ISSUE TITLE
Bug/error: Hasil Cetak Buku Aparat Pemerintah Desa

### ISSUE THREAD

**Issue by mah-mudi** [OpenSID/OpenSID#6106]
### Jelaskan error yg dialami

Hasil Cetak Buku Aparat Pemerintah Desa tertulis Buku Data Aparat Pemerintah

### Cara untuk mereplikasi errornya

1. Buku Administrasi Desa
2. Administrasi Umum
3. Buku Aparat Pemerintah Desa

### Hasil yg diharapkan

Hasil Cetak tertulis Buku Aparat Pemerintah Desa
![image](https://user-images.githubusercontent.com/57661283/206389450-ed5c71b2-84ce-4402-b960-6dc5c3a23072.png)

### Tangkapan layar dan log error

![Untitled11](https://user-images.githubusercontent.com/57661283/206389569-7a4d227e-ee03-4b0f-923e-59f968719106.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

22.12 Premium rev01

### Tema Yang Digunakan

silir 3.6.3

### Informasi tambahan

-

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/1747
