### ISSUE TITLE
Bug/error: tampilkan keterangan singkat fungsi tombol perbaiki

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#6108]
### Jelaskan error yg dialami

![image](https://user-images.githubusercontent.com/36557759/206607674-58518b96-56cf-4199-a10d-f5dad1510d65.png)

beri keterangan singkat pada tombol PERBAIKI, pada saat mouseover
dan akan saya lengkapi di panduan

### Cara untuk mereplikasi errornya

Arsip Layanan Surat

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.12-premium-rev01

**Comment by devrakapriyo** [comment]
Isi mouseover/tooltip “semua surat yang berstatus proses atau tidak ada statusnya akan di ubah menjadi siap cetak”

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1750
