### ISSUE TITLE
Permintaan fitur: Tambah tombol "hapus" di Arsip Surat

### ISSUE THREAD

**Issue by ihsan2857** [OpenSID/OpenSID#6109]
### Apa kekurangan yg ingin diatasi?

![GWSFW_DS_01 ](https://user-images.githubusercontent.com/24783679/206617680-69a15f46-6b16-488f-aacc-3a3ce8161164.png)

Tambahkan tompul "Hapus" 

### Jelaskan solusi yg diinginkan

-

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

Opend Premium V22.12

**Comment by eddieridwan** [comment]
@ihsan2857 bisa dihapus oleh pengguna khusus. @devrakapriyo harap jelaskan dan pastikan ada panduannya . Masalah ini membingungkan pengguna dan perlu ada panduannya dan juga entri di forum.opendesa.id. Mohon segera dilakukan, karena sangat sering ditanyakan.

**Comment by balongbesuk** [comment]
tombol hapus harusnya muncul ketika grup yang di beri kewenangan hapus diberikan oleh admin

setelah saya cek d pengaturan pengguna saya lihat hak akses pengguna bawaan opensid tidak bisa di edit oleh admin

![image](https://user-images.githubusercontent.com/35319600/206627105-26ea0ce6-851f-4dc7-8fb0-80b5ef829e63.png)

**Comment by eddieridwan** [comment]
@balongbesuk , lihat penjelasan di https://github.com/OpenSID/OpenSID/issues/6109#issuecomment-1343813654. Jadi yg dapat menghapus bukan pengguna yg mempunyai grup pengguna tertentu (seperti Admin), tetapi hanya pengguna tertentu saja (misalnya pengguna X).

@vickyrolanda sepertinya cara melakukan pengaturan ini melalui config.php membingungkan banyak pengguna, seperti untuk pengguna yg diperbolehan memasukkan iframe, video dan isian lain yg berpotensi berbahaya di artikel.

Mohon anda pikirkan cara yg lebih mudah, tetapi tetap aman dan sulit disalahgunakan. Berikut contoh skema yg dapat dipertimbangkan:

1. Sediakan adanya pengguna Super-admin. **Hanya boleh ada satu pengguna Super-admin.** 
2. Pengguna Super-admin ini dibuat secara default pada pemasangan awal OpenSID. Yaitu menggantikan peran Admin default saat ini. Jadi pada instal awal, belum ada pengguna Admin, hanya pengguna Super-admin. Pengguna Admin (satu atau lebih) pertama kali perlu ditambahkan oleh pengguna Super-admin. Setelah itu, pengguna Admin tersebut dapat berperan sesuai hak akses grup Admin.
3. Hanya Super-admin yg dapat menentukan pengguna yg
    a. diperbolehkan memasukkan isian artikel yg berpotensi berbahaya
    b. diperbolehkan menghapus arsip layanan
    
Dengan skema di atas, tidak perlu lagi menggunakan config.php. Tentunya dengan asumsi, Super-admin tersebut adalah juga pengguna yg mengurusi database, cPanel dll di server.

**Comment by devrakapriyo** [comment]
pak @ihsan2857 untuk solusi sementara cara menghapus arsip layanan surat ada di link forum ini 

https://forum.opendesa.id/d/278-cara-menghapus-arsip-layanan-surat

sambil menunggu akan di buatkan fitur untuk role super admin
