### ISSUE TITLE
Permintaan fitur: sediakan opsi bisa menyalin hak akses dari grup bawaan.

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#6110]
### Apa kekurangan yg ingin diatasi?

grup pengguna lain bawaan opensid tidak bisa dirubah hanya bisa dilihat sehingga ketika ingin menambah / mengurangi hak akses pengguna tidak bisa 

### Jelaskan solusi yg diinginkan

beri akses penuh administrator untuk memberi hak akses ke pengguna lain

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

berputar

### Informasi tambahan

![image](https://user-images.githubusercontent.com/35319600/206627524-baca8dfe-2e32-4221-a144-4bc27b5f3fca.png)

**Comment by eddieridwan** [comment]
@balongbesuk @vickyrolanda Grup pengguna bawaan OpenSID sengaja tidak dapat diubah, karena merupakan bagian dari rilis dan diubah sesuai dengan rilis.

Jika ingin memberikan akses yg berbasis grup bawaan, tetapi berbeda, solusi yg memudahkan adalah menyediakan fitur untuk membuat grup baru yg disalin dari grup bawaan. Yaitu, pada waktu membuat grup baru, disediakan opsi bisa menyalin hak akses dari grup lainnya. 

Jadi, misalnya, dapat membuat grup baru yg awalnya mempunyai hak akses sama dengan Operator. Kemudian hak akses grup baru tersebut dapat diubah sesuai kebutuhan.

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui commit https://github.com/OpenSID/premium/commit/5745a464abb94ff8513dc3dd66cdf93e5b1f3408
