### ISSUE TITLE
Bug/error: halaman selalu reload di browser firefox

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#6111]
### Jelaskan error yg dialami

- https://beta.opendesa.id/index.php/kehadiran/masuk
- https://beta.opendesa.id/index.php/layanan-mandiri/masuk

url di atas tidak berhenti reload jika menggunakan browser Firefox
setelah di cek, ternyata ID pengunjung tidak tergenerate yang menyebabkan reload yang tidak berhenti

https://user-images.githubusercontent.com/36557759/206649295-f5723d25-d5e1-4c51-8dd9-d1f9e33df6ae.mov

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

hanya browser firefox saja bermasalah. microsoft edge, google chrome, opera (aman)

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.12-premium-rev01

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1752
