### ISSUE TITLE
Bug/error: Tidak bisa upload file .PDF pada Buku Administrasi Umum - Buku Peraturan Di Desa

### ISSUE THREAD

**Issue by wahyabiantara** [OpenSID/OpenSID#6112]
### Jelaskan error yg dialami

Saat mencoba upload informasi mengenai beberapa Perdes di Desa melalui menu Buku Administrasi Desa > Administrasi Umum > Buku Peraturan di Desa dimana file yang di upload ada file PDF, lalu muncul error 

> **Data Gagal Disimpan. 
Jenis berkas yang anda unggah tidak diperbolehkan.**

### Cara untuk mereplikasi errornya

1. Buku Administrasi Desa 
2. Administrasi Umum 
3. Buku Peraturan di Desa
4. Tambah Perdes
5. Unggah dokumen PDF
6. Simpan

### Hasil yg diharapkan

User kembali dapat mengunggah berkas PDF maupun Doc untuk mempermudah manajemen Perdes maupun dokumen lainnya.

### Tangkapan layar dan log error

![Sistem-Informasi-Desa-Buwit-Desa-Buwit-Dokumen-Sekretariat-Peraturan-Desa-3](https://user-images.githubusercontent.com/4361979/206695202-efdf36bc-0a7e-437c-a37f-7def2a22c495.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

22.12-premium

### Tema Yang Digunakan

esensi

**Comment by vickyrolanda** [comment]
silahkan update ke versi 22.12-premium.rev01 masalah ini sudah di selesaikan di rev01 tersebut pak.

**Comment by wahyabiantara** [comment]
Terima kasih Bang @vickyrolanda

**Comment by sangawedartha** [comment]
saya sudah update ke versi 2400

**Comment by sangawedartha** [comment]
saya sudah update ke versi 2401, kalo di komputer lain lancar tapi di saya gak bisa... kayaknya ada masalah di saya selaku admin, apa mungkin ada yang merubah setingan di saya selaku admin?
