### ISSUE TITLE
Permintaan fitur: Penambahan Opsi Hapus pada Permohonan Surat

### ISSUE THREAD

**Issue by mah-mudi** [OpenSID/OpenSID#6113]
### Apa kekurangan yg ingin diatasi?

Belum adanya opsi hapus pada Permohonan Surat

### Jelaskan solusi yg diinginkan

Adanya opsi hapus pada Permohonan Surat untuk menghapus pengajuan yang uji coba, salah dll

### Apakah ada alternatif lain

![image](https://user-images.githubusercontent.com/57661283/206709467-23a6ead5-3b77-4622-ab62-67bd0bbd0043.png)

### Untuk versi OpenSID mana

23.01 Premium

### Informasi tambahan

-

**Comment by riyansuhandi** [comment]
Setuju Karena Masih Banyak Uji Coba Uji Coba Yang Desa Lakukan Untuk Pemanfaatan Fitur Pelayanan di Layanan Mandiri Online

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui https://github.com/OpenSID/premium/commit/7abcf0898d40b3fcfcea78587472dada38339c0d
