### ISSUE TITLE
data form Keterangan Kelahiran blank page

### ISSUE THREAD

**Issue by Rheldy** [OpenSID/OpenSID#6114]
### Jelaskan error yg dialami

<?php if (!defined('BASEPATH')) exit('No direct script access allowed');
	$data['warganegara'] = $this->penduduk_model->list_warganegara();
	$data['agama'] = $this->penduduk_model->list_agama();
	$data['pekerjaan'] = $this->penduduk_model->list_pekerjaan('ucwords');
	$data['sex'] = $this->penduduk_model->list_sex();
	$data['tempat_dilahirkan'] = $this->referensi_model->list_kode_array(TEMPAT_DILAHIRKAN);
	$data['jenis_kelahiran'] = $this->referensi_model->list_kode_array(JENIS_KELAHIRAN);
	$data['penolong_kelahiran'] = $this->referensi_model->list_kode_array(PENOLONG_KELAHIRAN);
	$data['nomor'] = $this->input->post('nomor_main');
	$_SESSION['post'] = $_POST;
	$_SESSION['post']['nomor'] = $data['surat_terakhir']['no_surat_berikutnya'];

### Cara untuk mereplikasi errornya

data form Keterangan Kelahiran pada tempat kelahiran, jenis kelahiran dan penolong kelahiran selalu error atau blank page

### Hasil yg diharapkan

apakah ada kode yang lebih baik

### Tangkapan layar dan log error

![SS](https://user-images.githubusercontent.com/120074504/206716914-54e280ee-06c2-4fc8-b844-eef3c2587a1a.png)

### Rilis Versi OpenSID

Rilis Umum

### Versi OpenSID

22.03

### Tema Yang Digunakan

natra

### Informasi tambahan

mohon pencerahan, saya masih pemula

**Comment by vickyrolanda** [comment]
mohon di testing di versi terbaru untuk rilis umumnya pak , jika masih menghadapin issue yg sama silahkan buka kembali issue ini dan lampirkan tangkapan layar log error dan informasi yang lebih details, terimakasih.
