### ISSUE TITLE
Bug/error: daftar gawai anjungan terkunci otomatis dalam rentang waktu yg tidak menentu

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#6115]
### Jelaskan error yg dialami

![image](https://user-images.githubusercontent.com/36557759/206975338-c39fb56f-5048-4c59-8a4e-d51abcd7145a.png)

ketika pembaruan cache dari layanan gagal, anjungan otomatis terkunci. dan ketika pembaruan berhasil kuncinya tidak terbuka lagi secara otomatis

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.12-premium-rev01

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1785
