### ISSUE TITLE
Permintaan fitur: Sesuaikan Kode/ klasifikasi Surat/arsip  Sesuai Peraturan Menteri Dalam Negeri Nomor 83 Tahun 2022

### ISSUE THREAD

**Issue by HerryWanda007** [OpenSID/OpenSID#6116]
### Apa kekurangan yg ingin diatasi?

Saat ini kode/Klasifikasi Surat pada surat OpenSID menggunakan Permendagri 78 tahun 20212 tentang Tata kearsipan di lingkungan kementrian dalam negeri dan pemerintah daerah , **peraturan ini telah dihapus** dan diganti dengan regulasi baru yaitu Peraturan Menteri Dalam Negeri Nomor 83 Tahun 2022 tentang kode klasifikasi arsip di lingkungan kementrian dalam negeri dan pemerintah daerah.

Jadi yang ada di OpenSID tidak sesuai lagi dengan peraturan/regulasi yang berlaku di indonesia.

### Jelaskan solusi yg diinginkan

Ganti seluruh kode/klasifikasi surat/arsip sesuai Peraturan Menteri Dalam Negeri Nomor 83 Tahun 2022 tentang kode klasifikasi arsip di lingkungan kementrian dalam negeri dan pemerintah daerah.

### **Namun harus diperhatikan :** 
Juga asumsi bahwa klasifikasi surat yangg telah digunakan pada surat tercetak melekat dan tidak berubah, meskipun klasifikasi lama sudah tidak berlaku lagi. karna berkaitan dengan arsip desa sebelum terbit nya regulasi baru ini.

### Apakah ada alternatif lain

Tidak ada, karna ini tuntutan regulasi terutama terkait surat menyurat di pemerintahan.

### Untuk versi OpenSID mana

OpenSID 22.12-premium-revisi ( kalo bisa)

### Informasi tambahan

Berikut dilampirakan Peraturan Menteri Dalam Negeri Nomor 83 Tahun 2022 tentang kode klasifikasi arsip di lingkungan kementrian dalam negeri dan pemerintah daerah : 

[permendagri-83-Tahun-2022-tentang-Kode-Klasifikasi-Arsip-kode-surat.pdf](https://github.com/OpenSID/OpenSID/files/10206513/permendagri-83-Tahun-2022-tentang-Kode-Klasifikasi-Arsip-kode-surat.pdf)

File exel kode klasifikasi arsip/surat : 

[Copy of Buku Pintar Elektronik Kode Klasifikasi.xlsx](https://github.com/OpenSID/OpenSID/files/10206523/Copy.of.Buku.Pintar.Elektronik.Kode.Klasifikasi.xlsx)

**Comment by HerryWanda007** [comment]
Komnetar **irfan ali** :
Sebenarnya yang harus diperhatikan Permendagrinya terlebih dahulu pada pasal 2 a dijelaskan regulasi tersebut sebagai pedoman di lingkungan Kemendagri dan pemerintah daerah yang bermakna penggunaanya masih diperuntukan sampai tingkat kabupaten,, itu menurut saya kalaupun mau disamakan memang akan terjadi perombakan cukup banyak. Dan sepertinya belum ada sosialisasinya itu diperuntukan untuk pemerintah desa menurut saaya🙏

Saya pertegas untuk menanggapi hal tersebut : 

![image](https://user-images.githubusercontent.com/109868721/207020356-6774f6b6-88ec-4df9-a47d-6213f5a39f02.png)
berdasarkan pasal 5 (permendagri 83/2022) diatas  sudah dijelaskan , bahwa regulasi lama telah dicabut dan tidak berlaku lagi. 

brarti dengan telah dicabut, disini bisa kita defenisikan, bahwa aturan kode klasifikasi berdasarkan Permendagri 78 tahun 20212 itu secara pemerintahan **sudah tidak berlaku lagi**.

Jadi kalo sudah dicabut dan tidak berlaku lagi maka tidak sah untuk digunakan.

Kemudian, walaupun di permendagri ini hanya disampaikan dilingkup kemendagri dan pemerintah daerah dan bermakna penggunaan nya diperuntukkan sampai tingkat kabupaten, tapi ingat pemerintah desa merupakan sub sistem dari pemerintah daerah. jadi regulasi ini juga sudah berlaku untuk desa.

**Comment by volla15** [comment]
Untuk di Kabupaten Bantul, menggunakan klasifikasi kode baru berlaku mulai  01 Maret 2023
untuk daerah lain mungkin akan segera menyusul, dan mohon untuk menjadi perhatian agar segera disesuaikan

[Perbup Bantul Nomor 139 Tahun 2022 Tentang Kode Klasifikasi Arsip di Lingkungan Pemerintah Kabupaten Bantul.pdf](https://github.com/OpenSID/OpenSID/files/10997504/Perbup.Bantul.Nomor.139.Tahun.2022.Tentang.Kode.Klasifikasi.Arsip.di.Lingkungan.Pemerintah.Kabupaten.Bantul.pdf)

**Comment by andifahruddinakas** [comment]
SOLUSI : 
- [ ] perbaiki seeder data awal.
- [ ] sesuaikan data impor
