### ISSUE TITLE
Bug/error: Surat Yang Memiliki Lampiran Tidak Dapat Dicetak

### ISSUE THREAD

**Issue by wahyabiantara** [OpenSID/OpenSID#6117]
### Jelaskan error yg dialami

Setiap surat RTF yang memiliki lampiran tidak berhasil dicetak dan di unduh. Baik yang dalam format RTF maupun PDF. Pada error log muncul error sebagai berikut:

`Severity: error --> Exception: Call to undefined method Surat_model::penandatangan_lampiran() /home/desabeng/sid.desabengkel.id/template-surat/surat_permohonan_kartu_keluarga/f-1.15.php 301
`

`Severity: error --> Exception: Call to undefined method Surat_model::penandatangan_lampiran() /home/desabeng/sid.desabengkel.id/template-surat/surat_ket_kelahiran/f-2.01.php 1127`

### Cara untuk mereplikasi errornya

1. Layanan Surat
2. Cetak Surat
3. Pilih salah satu surat yang memiliki Lampiran
4. Isi dengan lengkap isian yang diminta
5. Klik Unduh RTF

### Hasil yg diharapkan

Surat yang memiliki lampiran dapat diunduh dalam bentuk zip seperti biasanya

### Tangkapan layar dan log error

<img width="1275" alt="Screen Shot 2022-12-12 at 17 39 13" src="https://user-images.githubusercontent.com/4361979/207016680-41d8f837-c7a2-4f61-918b-e87ce5c3f570.png">

![arsip-surat ket kelahiran](https://user-images.githubusercontent.com/4361979/207017406-3c9f6466-426a-41f7-8796-e89ba7b48436.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

22.12

**Comment by andifahruddinakas** [comment]
Jika menggunakan template lampiran ubahan desa, bisa sesuaikan dengan template bawaan OpenSID.

**Comment by wahyabiantara** [comment]
@andifahruddinakas kasus diatas adalah kasus menggunakan surat RTF pada sistem, sehingga lampiran yang digunakan adalah lampiran pada sistem. Saya coba cek line 1127 pada lampiran surat keterangan kelahiran di versi umum, memang ada pemanggilan fungsi penandatangan_lampiran()

Namun pada versi Premium yang kami gunakan, function tersebut tidak ditemukan?

Apakah hal ini ada kesalahan pada update atau memang bugs?

**Comment by andifahruddinakas** [comment]
Sy coba di https://berputar.opendesa.id/surat/form/surat_permohonan_kartu_keluarga tidak ada masalah. Mas @devrakapriyo, coba dicek issue ini.

**Comment by vickyrolanda** [comment]
sudah sy coba @wahyabiantara juga tidak ada masalah pak 
<img width="778" alt="image" src="https://user-images.githubusercontent.com/59082428/207792225-77e72641-ab67-4fea-9ac3-1ad2129533cb.png">
coba silahkan gunakan veri 22.12-rev02 pak 

ntar jika masih menemukan hal yang sama silahkan diopen lagi pak issuenya ya pak.
