### ISSUE TITLE
Bug/error: tombol kembalikan status terpilih pada form log penduduk tidak berfungsi

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#6118]
### Jelaskan error yg dialami

<img width="1440" alt="Screen Shot 2022-12-12 at 23 18 39" src="https://user-images.githubusercontent.com/36557759/207110391-138f5225-507b-496f-9f47-b5bc092b9e29.png">

ketika memilih/mencentang penduduk yang sudah di pilih lalu klik tombol "Kembalikan Status Terpilih" maka akan muncul popup seperti gambar di atas, akan tetapi ketika klik tombol "Simpan" maka tidak ada respon dan coba cek inspect element pada console/network tidak ada aktivitas ketika klik tombol "Simpan"

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.12-premium-rev01

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1759
