### ISSUE TITLE
Bug/error: Perbaiki Pilihan Cetak Buku Administrasi Desa

### ISSUE THREAD

**Issue by mah-mudi** [OpenSID/OpenSID#6119]
### Jelaskan error yg dialami

Masih adanya pilihan Pamong tertanda dan Pamong Mengetahui, ada redaksi desa pada penandatanganan dan Tampilan Keputusan Kades perlu disesuaikan menjadi Keputusan Kepala Desa agar sesuai dalam penyebutan dg Produk hukum lainnya.

### Cara untuk mereplikasi errornya

1. Buku Administrasi Desa
2. Administrasi Umum, Penduduk dan Pembangunan

### Hasil yg diharapkan

1. Pilihan Cetak Otomatis dibuat Mengetahui Kepala Desa dan Tertanda Sekretaris Desa, dengan huruf kapital pada Jabatan pada Administrasi Umum, Penduduk dan Pembangunan 
2. Hilangkan redaksi Desa atau sebutan lain sebelah tanggal.
3. Ubah Tampilan pada Web pada produk hukum Jenis Peraturan , Keputusan Kades diubah menjadi Keputusan Kepala Desa

### Tangkapan layar dan log error

![A11](https://user-images.githubusercontent.com/57661283/207237963-d1643456-89f4-4fd5-b968-6bb47b9c2f9b.png)
![A12](https://user-images.githubusercontent.com/57661283/207238217-919ad054-0a00-4028-93be-be627a7a22e7.png)
![A13](https://user-images.githubusercontent.com/57661283/207237983-97995ed7-7ebe-4c27-9ea3-0a2598b5aaf9.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

22.12 Premium rev02

### Tema Yang Digunakan

silir 3.6.3

### Informasi tambahan

Format Administrasi Pemerintahan Desa dapat dilihat disini
[Permen No.47 TH 2016_Lampiran.pdf](https://github.com/OpenSID/OpenSID/files/10214915/Permen.No.47.TH.2016_Lampiran.pdf)

**Comment by andifahruddinakas** [comment]
Mas @mah-mudi, issue seperti ini sebaiknya dipisah.
1. Issue mengenai penanda tangan saat cetak pada bumindes..
2. Issue mengenai halaman publik peraturan desa, dan sebaiknya gunakan tema bawaan untuk pengecekan.

**Comment by andifahruddinakas** [comment]
Untuk issue ini yang akan diperbaiki mengenai penanda tangan yang ada di bumindes sesuai aturan https://github.com/OpenSID/OpenSID/files/10214915/Permen.No.47.TH.2016_Lampiran.pdf

**Comment by andifahruddinakas** [comment]
Untuk Tampilan Web Produk Hukum silahkan buat di issue lain dan usahakan menggunakan tangkapan layar tema bawaan di rilis terbaru.

**Comment by mah-mudi** [comment]
Oke mas @andifahruddinakas 

Terima Kasih

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1760

**Comment by devrakapriyo** [comment]
mas @andifahruddinakas dan pak @mah-mudi apakah issue no 2 perihal

Issue mengenai halaman publik peraturan desa, dan sebaiknya gunakan tema bawaan untuk pengecekan.

sudah ada issue nya?

**Comment by mah-mudi** [comment]
@devrakapriyo sdh saya buatkan mas
