### ISSUE TITLE
Bug/error: update profile error 500

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#6120]
### Jelaskan error yg dialami

<img width="618" alt="Screen Shot 2022-12-15 at 07 35 19" src="https://user-images.githubusercontent.com/36557759/207745187-3ad3af28-2cd8-4702-b2ef-c6a82d48b318.png">

<img width="1440" alt="Screen Shot 2022-12-14 at 22 14 23" src="https://user-images.githubusercontent.com/36557759/207634237-f40b5d4b-de8c-4367-aa4b-805bfc627344.png">

saat melakukan update profile

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.12-premium-rev02

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1787
