### ISSUE TITLE
Bug/error: surat tidak dapat di hapus 

### ISSUE THREAD

**Issue by mranca** [OpenSID/OpenSID#6121]
### Jelaskan error yg dialami

pada saat ingin menghapus surat tinymce muncul pesan, surat bawan sistem tidak dapat di hapus

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

![Screenshot (149)](https://user-images.githubusercontent.com/76085245/207753377-e844e3d6-a676-43b9-83e8-d7eec63ff2d6.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.12-Premium-rev02

### Tema Yang Digunakan

-

### Informasi tambahan

-

**Comment by vickyrolanda** [comment]
mas @andifahruddinakas surat bawaan sistem memang tidak bisa di hapuskan ?

**Comment by andifahruddinakas** [comment]
> mas @andifahruddinakas surat bawaan sistem memang tidak bisa di hapuskan ?

Surat bawaan sistem baik rtf maupun tinymce tdk dapat dihapus (hanya bisa diubah). Jika tidak digunakan bisa digembok saja.
