### ISSUE TITLE
Bug/error: 

### ISSUE THREAD

**Issue by Rheldy** [OpenSID/OpenSID#6122]
### Jelaskan error yg dialami

Tidak bisa meng Upload Penduduk, selalu error saat Upload penduduk format xlxs atau pun xlsm, padahal di versi sebelumnya selalu lancar

### Cara untuk mereplikasi errornya

![image](https://user-images.githubusercontent.com/120074504/207768989-4db1fa6f-ff3c-4613-a23d-f7218b627ff1.png)

### Hasil yg diharapkan

kembali ke semula dimana import export ada di pengaturan database

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/120074504/207769148-56eb4145-69c5-4973-abfb-ac188437447b.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

22.12.02

### Tema Yang Digunakan

natra

**Comment by agungsugiarto** [comment]
Pak @Rheldy bisa kirimkan contoh file .xlsx ke saya melalui telegram https://t.me/meagungsugiarto

**Comment by vickyrolanda** [comment]
pak @Rheldy  saya coba import dengan mengikuti data contoh itu berhasil import pak .

**Comment by Rheldy** [comment]
Pak agungsugiarto sudah saya kirim ya pak

**Comment by Rheldy** [comment]
Pak @vickyrolanda untuk disaya masih error pak

**Comment by Rheldy** [comment]
pak @agungsugiarto sudah sya kirim ya pak

**Comment by devrakapriyo** [comment]
pak @Rheldy setelah di cek sama mas @agungsugiarto dari file .xlsx nya tidak sesuai dengan template
mohon agar menggunakan template .xlsx untuk mengimport data

**Comment by devrakapriyo** [comment]
pak @Rheldy untuk semantara issue di close, jika masih mengalami error bisa di buka kembali issue ini
