### ISSUE TITLE
Perbaikan Modul Buku Tamu

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#6127]
1. Perbaiki tampilan mobile & tablet. https://github.com/OpenSID/OpenSID/issues/6246
2. Perbaikan validasi inputan script agar tidak muncul error 500. https://github.com/OpenSID/OpenSID/issues/6247
3. Kalimat bertemu, mungkin ada alternatif lain (Berkunjung).
![image](https://user-images.githubusercontent.com/59082428/208316973-10365167-27ad-44da-b936-4a54cc035998.png)
6. bisa beri captcha https://github.com/OpenSID/OpenSID/issues/6248

**Comment by andifahruddinakas** [comment]
Mas @vickyrolanda, permintaan seperti ini baiknya dipisah.

**Comment by vickyrolanda** [comment]
ia mas @andifahruddinakas  akan sy pecah lgi mas.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1939
