### ISSUE TITLE
Bug/error: penandangan hilang pada surat tinyMCE

### ISSUE THREAD

**Issue by mranca** [OpenSID/OpenSID#6128]
### Jelaskan error yg dialami

pada saat ingin membuat surat menggunakan tinyMCE dan untuk memilih nama yang akan bertanda tangan itu hilang

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.12-Premium-rev02

### Tema Yang Digunakan

-

### Informasi tambahan

-

**Comment by andifahruddinakas** [comment]
Mas @mranca, bisa sertakan tangkapan layar bagian yang dimaksud?

**Comment by mranca** [comment]
![screenshot (3)](https://user-images.githubusercontent.com/76085245/208853408-cd0b88ae-7234-4b33-af83-7ce1a567cd14.jpg)
@andifahruddinakas

**Comment by andifahruddinakas** [comment]
> ![screenshot (3)](https://user-images.githubusercontent.com/76085245/208853408-cd0b88ae-7234-4b33-af83-7ce1a567cd14.jpg) @andifahruddinakas

ini surat bukan jenis TinyMCE.

**Comment by mranca** [comment]
@andifahruddinakas , iye betul tapi itu contoh gambar saja pada tinyMCE yang tidak bisa pilih yang akan bertanda tangan

**Comment by devrakapriyo** [comment]
pak @mranca setelah saya cek di berputar normal

<img width="1440" alt="Screen Shot 2022-12-29 at 13 13 00" src="https://user-images.githubusercontent.com/36557759/209911077-4e1a2ac9-f7cd-447a-99ba-c209a3ba324d.png">

sementara saya close, jika masih mengalami error issue bisa di buka kembali
