### ISSUE TITLE
Ketika Kosongkan data base menu statis, menu dinamis dan widget tidak hilang

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#613]
Ketika Kosongkan data base menu statis, menu dinamis dan widget tidak hilang supaya ketika desa yang baru belajar OpenSID jadi tidak binggung
![image](https://user-images.githubusercontent.com/25834335/30246524-ead819f0-9626-11e7-9560-eff3de7f4a81.png)

kalau yang lain sudah ok

**Comment by egodasa** [comment]
Kalau tidak ingin hal tersebut hilang,usahakan tabel menu dan tabel widget tidak ikut dikosongkan.

**Comment by MUHAMMADRANGSEL** [comment]
Caranya gimana mas?

**Comment by egodasa** [comment]
Mas buka mysql pakai aplikasi apa?phpmyadmin?kalau iya klik nama database,nanti bakal keluar daftar tabel.tinggal klik centang disemua tabel kecuali tabel menu dan widget. Kemudian di combobox pilih empty.

**Comment by MUHAMMADRANGSEL** [comment]
alhamdulillah untuk issue ini sudah saya temukan solusinya tapi perlu dicek lagi sama mas eddie krn untuk widget masih dia hilang waktu mengosongkan database kalau untuk menu statis dan dinamis sudh bisa
adapun tambahan scrip yang saya tambahkan di donjo-app/model/database_model.php
[database_model.zip](https://github.com/eddieridwan/OpenSID/files/1364355/database_model.zip)
mohon untuk dimasukkan dicommit

**Comment by eddieridwan** [comment]
Sekarang pada waktu mengosongkan DB, tabel widget tidak dikosongkan, dan pengguna diberi opsi untuk mengosongkan menu statis dan dinamis.

Sudah dicommit ke master.

**Comment by MUHAMMADRANGSEL** [comment]
Trima kasih mas eddie

Pada tanggal 20 Nov 2017 13:58, "Eddie Ridwan" <notifications@github.com>
menulis:

**Comment by MUHAMMADRANGSEL** [comment]
tuk nama dan kode provinsi pak eedie masih ikut terhapus

**Comment by eddieridwan** [comment]
@MUHAMMADRANGSEL laporan tambahan, ya --- :)

**Comment by eddieridwan** [comment]
Ok, sudah dicommit ke master.
