### ISSUE TITLE
Bug/error: perubahan pada arsip layanan surat

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#6130]
### Jelaskan error yg dialami

ada beberapa fitur pada menu arsip layanan surat di versi terbaru OpenSID tidak tersedia, seperti : rekap surat, pie surat keluar, cetak dan unduh

jika di lihat pada versi 6 bulan kebelakang OpenSID, fitur tersebut masih ada

https://demosid.opendesa.id
![image](https://user-images.githubusercontent.com/36557759/208809343-90b2130a-308d-4bde-9c9a-3e51fdb52622.png)

https://berputar.opendesa.id
![image](https://user-images.githubusercontent.com/36557759/208809394-172e43c9-3e5f-4dbc-8d58-807feaa51457.png)

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.12-premium-rev03

**Comment by scqolbu24** [comment]
@devrakapriyo dan @vickyrolanda setelah dicek untuk https://demosid.opendesa.id/index.php/keluar, https://berputar.opendesa.id/keluar, https://beta.opendesa.id/index.php/keluar terjadi demikian yang telah di tampilkan pada gambar diatas.

Kemudian setelah dicek melalui script terdapat perbedaan untuk pengguna tertentu dapat melihat seperti yang ditampilkan untuk menu-menu tersebut sesuai dengan tampilan demosid. 

Berikut tampilan ketika uji coba di local menggunakan branch bug-fix dan rilis-dev:
![Arsip Layanan Surat](https://user-images.githubusercontent.com/68048807/209244175-0a7b3f47-dedf-46d4-9d4a-3b8262c69226.JPG)

Mohon bisa dicek kembali untuk issue ini, aturannya bagaimana.

**Comment by devrakapriyo** [comment]
mas @vickyrolanda dan mas @scqolbu24 setelah saya cek fitur ini akan tersedia jika mengaktifkan verifikasi surat di pengaturan surat, jika tidak maka fitur tersebut ter hidden

**Comment by scqolbu24** [comment]
mas @devrakapriyo, dengan demikian apakah tidak perlu dilakukan aktif/non aktif verifikasi surat agar tetap tampil?

**Comment by ariandii** [comment]
karena posisi sudah pada halaman arsip, maka perlu ditampilkan tombol tombol unduh cetak dll tersebut.

**Comment by devrakapriyo** [comment]
betul yang di katakan pak @ariandii
mas @scqolbu24 karena surat sudah masuk pada halaman arsip, maka perlu di tampilkan tombol unduh, cetak dan pie chart

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1887
