### ISSUE TITLE
Permintaan fitur: MENGEMBALIKAN WARGA YANG PINDAH MASUK SETELAH PINDAH KELUAR

### ISSUE THREAD

**Issue by newh44** [OpenSID/OpenSID#6131]
### Apa kekurangan yg ingin diatasi?

ada warga yang sudah pindah keluar, beberapa bulan kemudian pindah masuk. pada menu OPENSID tidak ada menu memasukkan kembali, harus menghapus orang itu kemudian input lagi
![image](https://user-images.githubusercontent.com/119162490/208917829-65d16523-c200-40ab-a638-8a24f42170fe.png)

### Jelaskan solusi yg diinginkan

Ada Menu Pindah Masuk di pilih aksi

### Apakah ada alternatif lain

Ada Menu Pindah Masuk di Pilih Aksi Lainnya
![image](https://user-images.githubusercontent.com/119162490/208918706-e3fd5fcd-1a91-4d7d-b5dc-9c1b5800180c.png)

### Untuk versi OpenSID mana

23.01

**Comment by balongbesuk** [comment]
ada d log penduduk
