### ISSUE TITLE
Bug/error: Sesuaikan Tampilan Redaksi Keputusan Kades menjadi Keputusan Kepala Desa pada Tampilan Web Produk Hukum

### ISSUE THREAD

**Issue by mah-mudi** [OpenSID/OpenSID#6133]
### Jelaskan error yg dialami

Tampilan Redaksi Keputusan Kades perlu disesuaikan menjadi Keputusan Kepala Desa pada Tampilan Web Produk Hukum

### Cara untuk mereplikasi errornya

1. Ke Menu Peraturan Desa pada Web
2. Lihat Jenis 

### Hasil yg diharapkan

Redaksi Keputusan Kades diubah menjadi **Keputusan Kepala Desa** pada Tampilan Web Produk Hukum

### Tangkapan layar dan log error

![qwea](https://user-images.githubusercontent.com/57661283/209267037-7f21706a-8fa1-460b-81f7-c747dec47bf5.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

22.12 Premium rev03

### Tema Yang Digunakan

natra

### Informasi tambahan

https://berputar.opendesa.id/peraturan-desa

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1840
