### ISSUE TITLE
Bug/error: Sesuaikan Asal Tanah Kas Desa di Buku Tanah Kas Desa, Redaksi Peruntukan diubah menjadi Pemanfaatan yang sesuai dengan SIPADES

### ISSUE THREAD

**Issue by mah-mudi** [OpenSID/OpenSID#6134]
### Jelaskan error yg dialami

Pilihan pengisian Asal Tanah Kas Desa terdiri dari Jual Beli, Hibah/Sumbangan, Lain-lain
Redaksi Peruntukan perlu diubah menjadi Pemanfaatan

### Cara untuk mereplikasi errornya

1. Administrasi Umum
2. Buku Tanah Kas Desa

### Hasil yg diharapkan

Pilihan pengisian Asal Tanah Kas Desa terdiri dari Jual Beli, Hibah/Sumbangan, Lain-lain 
diubah menjadi pilihan pengisian Asal Tanah Kas Desa yang terdiri dari : APB Desa, Perolehan Lainnya yang Sah, Kekayaan Asli Desa

### Tangkapan layar dan log error

![zxc](https://user-images.githubusercontent.com/57661283/209268567-23ea8103-5604-4771-8e9e-286494c54807.png)
![image](https://user-images.githubusercontent.com/57661283/209268656-ef537c1a-65c8-448c-9cc1-4e3c1cb0b5b6.png)
![image](https://user-images.githubusercontent.com/57661283/209268613-a8eecb3e-6888-4997-854a-acaff96b725b.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

22.12 Premium rev03

### Tema Yang Digunakan

natra

### Informasi tambahan

https://berputar.opendesa.id/bumindes_tanah_kas_desa/form

**Comment by eddieridwan** [comment]
@vickyrolanda peristilahan di Buku Tanah Kas Desa adalah berdasarkan Permendagri terkait Buku Administrasi Desa yg bisa saja berbeda dengan Sipades. Jadi harap anda lakukan dulu pemeriksaan ulang terkait Permendagri tersebut dalam proses verifikasi apakah permintaan ini dapat diterapkan atau tidak.

**Comment by vickyrolanda** [comment]
> @vickyrolanda peristilahan di Buku Tanah Kas Desa adalah berdasarkan Permendagri terkait Buku Administrasi Desa yg bisa saja berbeda dengan Sipades. Jadi harap anda lakukan dulu pemeriksaan ulang terkait Permendagri tersebut dalam proses verifikasi apakah permintaan ini dapat diterapkan atau tidak. 

Baik pak sy cari tau terlebih dahulu

**Comment by mah-mudi** [comment]
@eddieridwan @vickyrolanda Untuk Asal Tanah Kas Desa jika dari APBDesa (sdh mencakup Jual Beli)
Jika Perolehan Lainnya yang Sah( Hibah dan sejenisnya selain dr APBDesa) 
Sedangkan Kekayaan Asli Desa (Tanah Asli Desa sejak klansiran misal Tanah Ganjaran, Bengkok, Telaga, Makam dll)


Untuk SIPADES sdh disesuaikan dg  Permendagri tentang Pengelolaan Aset Desa dan Pengelolaan Keuangan Desa. 

Dapat Cek juga Permendagri tentang Administrasi Pemerintahan Desa.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1841
