### ISSUE TITLE
Bug/error: Perbaiki Eror Cetak pada Buku Tanah Kas Desa dan Buku Tanah di Desa.

### ISSUE THREAD

**Issue by mah-mudi** [OpenSID/OpenSID#6135]
### Jelaskan error yg dialami

Eror Cetak pada Buku Tanah Kas Desa dan Buku Tanah Di Desa.

### Cara untuk mereplikasi errornya

1. Buku Tanah Kas Desa, Buku Tanah Di Desa
2. Klik Cetak
3. Lihat Eror

### Hasil yg diharapkan

Hilangkan Pop Up, Cetak pada Buku Tanah Kas Desa dan Buku Tanah Di Desa.

### Tangkapan layar dan log error

![zxc11](https://user-images.githubusercontent.com/57661283/209269457-91920231-daf9-4b5d-9611-6914cfcf948f.png)
![image](https://user-images.githubusercontent.com/57661283/209269527-13675e2c-2801-420a-bb4a-d725cbee182b.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

22.12 Premium rev03

### Tema Yang Digunakan

natra

### Informasi tambahan

https://berputar.opendesa.id/bumindes_tanah_desa/cetak_tanah_desa/cetak

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1856
