### ISSUE TITLE
Bug : Tidak dapat menghapus Dusun/RW/RT walau jumlah penduduk dan keluarga sudah 0

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#6136]
Alur : 
1. Misalnya terjadi kesalahan saat melakukan impor dan perlu menghapus penduduk (memliki kk) tsb agar bisa menghapus wilayah bermasalah.
2. Lakukan hapus penduduk.
3. Masuk ke wilayah yang akan di hapus, tombol hapus akan aktif karena kondisi terpenuhi.
4. Hapus wilayah tsb, akan tampil notifikan gagal karenan wilayah tsb masih terdapat penduduk/keluarga.

Penyebab : 
1. Ini terjadi karena penduduk tsb berstatus kepala keluarga dihapus, namu data KK masih ada dan berubah status jadi KK kosong pada wilayah tsb.

Solusi : 
1. Jika menghapus Kepala Keluarga, hapus juga KKnya, atau
2. Pada pengecekan kondisi hapus dusun/rt/rw, perhitungkan juga KK kosong tsb (bukan view nya) agar status dan notifikasi hapus sesuai. Mungkin perlu diperjelas juga notifikasi agar tidak membingunkan
3. Sediakan panduan untuk menghapus dusun, serta penjelasan penting yang harus diketahui.

**Comment by andifahruddinakas** [comment]
Solusi sementara : 
1. masuk ke modul keluarga
2. lakukan filter berikut : 
    - Pilih status KK (semua)
    - Pilih dusun/rt/rw yang tidak dapat dihapus
3. akan tampil kk kosong, hapus data tsb.
4. masuk ke modul wilayah dan lakukan hapus dusun/rt/rw seperti biasanya.

**Comment by andifahruddinakas** [comment]
Perlu diperhatikan juga, notifikasi hapus dusun/rt/rw nya sama semua, walau yang dihapus adalah rw.

`Data dusun tidak dapat dihapus, data sudah tersedia di Penduduk atau Keluarga.`

**Comment by andifahruddinakas** [comment]
Sederhanakan fungsi yang berluang,

```
$id_cluster = $this->db->select('id')->where('rw', $rw)->where('dusun', $dusun)->get('tweb_wil_clusterdesa')->result_array();
                $id_cluster = array_map(static fn ($value) => $value['id'], $id_cluster);

                $penduduk = $this->db->select("count('id') as jmlh")->where_in('p.id_cluster', $id_cluster)->get('tweb_penduduk as p')->row();
                $keluarga = $this->db->select("count('id') as jmlh")->where_in('k.id_cluster', $id_cluster)->get('tweb_keluarga as k')->row();

                if ($penduduk->jmlh + $keluarga->jmlh != 0) {
                    return session_error('Data dusun tidak dapat dihapus, data sudah tersedia di Penduduk atau Keluarga.');
                }
```

**Comment by eddieridwan** [comment]
@andifahruddinakas apakah sudah pastikan tidak ada penduduk mati/pindah/hilang? Apakah tidak ada penduduknya yg penerima bantuan, ada di analisis, atau data suplemen. Juga pelajari dulu apakah log penduduk masih perlukan dusun/rw/rt itu.

**Comment by andifahruddinakas** [comment]
> @andifahruddinakas apakah sudah pastikan tidak ada penduduk mati/pindah/hilang? Apakah tidak ada penduduknya yg penerima bantuan, ada di analisis, atau data suplemen. Juga pelajari dulu apakah log penduduk masih perlukan dusun/rw/rt itu. 

Untuk log tdk ada kaitannya dgn dusun/rw/rt, sy lihat kondisi bisa hapus wilayah jika tdk ada penduduk/keluarga di wilayah tsb.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1852

**Comment by andifahruddinakas** [comment]
Beberapa kemungkinan solusi:

- [x] 1. beritahu mengapa tidak bisa dihapus, misalnya masih ada penduduk di wilayah tsb, atau wilayah di bawahnya perlu dihapus dulu
- [ ] 2. beri tautan ke daftar penduduk yg perlu dipindahkan dulu
- [ ] 3. beri tautan ke wilayah yg harus dihapus dulu
