### ISSUE TITLE
Bug/error: photo profi hilang di bagan aparatur desa

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#6137]
### Jelaskan error yg dialami

-

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.12-premium-rev03

**Comment by vickyrolanda** [comment]
mas @devrakapriyo ini issuenya gmna ya cara replikasinya ?

**Comment by vickyrolanda** [comment]
Perbaikan @agungsugiarto 

1. Posisinya di daftar aparatur desa dipilih jenis kelamin perempuan 
![image](https://user-images.githubusercontent.com/59082428/209902644-b266c341-418c-4e55-95cc-4ece47d89f26.png)
2. Lalu di bagian bagan tampil jenis kelamin laki - laki 
![image](https://user-images.githubusercontent.com/59082428/209902660-a2f7d427-68ec-4097-9ab7-75b1656b843b.png)

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1867
