### ISSUE TITLE
Bug/error: ketentuan .htaccess setelah update

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#6138]
### Jelaskan error yg dialami

-

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.12-premium-rev03

**Comment by agungsugiarto** [comment]
bisa diperjelas maksudnya mas @devrakapriyo ?

**Comment by agungsugiarto** [comment]
- ketika ada perubahan untuk htaccess akan disampaikan oleh programmer ke @devrakapriyo kemudian informasi tersebut akan diteruskan oleh @devrakapriyo ke pengguna ketika waktu rilis.
