### ISSUE TITLE
Bug/error: salinan template surat rtf error saat cetak setelah melakukan update

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#6139]
### Jelaskan error yg dialami

-

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.12-premium-rev03

**Comment by eddieridwan** [comment]
@devrakapriyo @vickyrolanda kita tidak lakukan pengembangan atau perbaikan surat RTF lagi. Arahkan pengguna supaya konversi ke surat TinyMCE.

**Comment by devrakapriyo** [comment]
tapi pak @eddieridwan bagaimana dengan pengguna OpenSID umum? apakah harus menunggu versi OpenSID yang sudah tersedia surat TinyMCE?

**Comment by eddieridwan** [comment]
Ya. Sementara carikan solusi lain cara melakukan apa yg mereka ingin lakukan. Seperti gunakan template RTF bawaan.

**Comment by devrakapriyo** [comment]
mas @agungsugiarto error ini terjadi menyalin dari folder /template surat, contoh : surat kelahiran atau surat kematian ke folder /desa/template-surat di OpenSID umum lalu ada kasus desa tersebut melakukan update ke premium dan cetak surat tersebut maka terjadi gagal 

dan solusinya itu harus menyalin ulang template dari folder /template

**Comment by vickyrolanda** [comment]
mas @agungsugiarto apakah ini sedang di kerjakan ?

**Comment by andifahruddinakas** [comment]
Mas @vickyrolanda, setelah sy cek dan gunakan template surat (rtf) versi umum di salin ke versi premium itu tidak bisa digunakan langsung. Perlu disesuaikan beberapa perubahan yang terjadi di tempalate surat (rtf) bawaan OpenSID. 

Misalnya : 
`<?= $this->penandatangan_lampiran($data);?>` diganti menjadi `<?= $penandatangan['atas_nama']?>` atau bisa sesuaikan langsung dengan contoh surat bawaan.

**Comment by vickyrolanda** [comment]
issue ini solusinya bisa langsung mengikutin contoh surat bawaan dan perlu di lengkapin di panduan & dibuatkan materinay di forum agar mudah ditemukan solusinya.
