### ISSUE TITLE
Bug/error: buat baru kode isian surat tinymce tidak muncul saat cetak surat

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#6140]
### Jelaskan error yg dialami

-

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.12-premium-rev03

**Comment by agungsugiarto** [comment]
bisa diperjelas maksudnya mas @devrakapriyo, langkahnya seperti apa ?

**Comment by devrakapriyo** [comment]
setelah di cek ulang, sudah tidak error
sementara issue di close
