### ISSUE TITLE
Bug/error: gagal upload foto profil jika kosongkan DB openSID umum

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#6141]
### Jelaskan error yg dialami

-

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.12.02-umum

**Comment by scqolbu24** [comment]
@devrakapriyo, jika terjadi pada umum, apakah sudah dicoba menggunakan premium ? 
jika di premium berhasil atau aman maka issue ini dapat ditutup.

**Comment by devrakapriyo** [comment]
di premium sudah tidak ada fitur kosongkan DB mas @scqolbu24

**Comment by vickyrolanda** [comment]
mohon di checkkan @devrakapriyo untuk yang di premium dan umum juga mas, 
untuk diplikasi bisa dengan cara : 
1. Install dari awal menggunakan seeder 
2. langkah selanjutnya bisa testing upload profil
3. Dan testing di 2 tempat 
    - di home (ini menggunakan blade) 
    - lalu coba edit di penduduk juga (ini di view lama ) 
4. Kemungkinan dari 2 tempat ini ada 1 yang bermasalah.

**Comment by devrakapriyo** [comment]
setelah di cek lebih lanjut tidak mengalami error, sementara issue di close
