### ISSUE TITLE
Bug/error: undefined data penduduk berstatus meninggal saat cetak surat keterangan meninggal

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#6142]
### Jelaskan error yg dialami

![image](https://user-images.githubusercontent.com/36557759/209523381-fae0cded-e2ff-4095-99bf-979a3f2544ad.png)

data penduduk yang berstatus "mati" saat akan di buatkan surat keterangan meninggal, lis penduduk muncul undefined

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Umum

### Versi OpenSID

v22.12.02

**Comment by devrakapriyo** [comment]
setelah melakukan update ke versi OpenSID 22.12-premium-rev03 data penduduk yang berstatus 'mati' masih menampilkan undefined
apakah bisa di tambahkan perbaikan data pada proses migrasi?

terlampir backup database pada google drive OpenDESA

https://drive.google.com/file/d/1GRZ__2CWMkyLFEZqQOkmdGG6ZscY22F4/view?usp=share_link

**Comment by agungsugiarto** [comment]
saya tidak menemukan masalah mas @devrakapriyo, bisa minta tolong replikasi issuenya?

![Image](https://user-images.githubusercontent.com/10989147/209609789-e28ce461-ad65-4828-9411-031c72709604.png)

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1873
