### ISSUE TITLE
Bug/error: add more kode isian surat tinymce berada di tengah bukan di akhir

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#6143]
### Jelaskan error yg dialami

<img width="1440" alt="Screen Shot 2022-12-26 at 21 47 24" src="https://user-images.githubusercontent.com/36557759/209560510-a81f961b-c2a5-479e-a0af-d6f61be96a96.png">

mas @agungsugiarto seperti yang tadi di replikasikan ketika di add more kode isian berada di tengah bukan di akhir

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.12-premium-rev03

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1853

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1970
