### ISSUE TITLE
Bug/error: gambar artikel tidak tampil

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#6145]
### Jelaskan error yg dialami

![image](https://user-images.githubusercontent.com/36557759/209605391-1d412c9b-027d-462c-9eb9-c02d56a198a0.png)

![image](https://user-images.githubusercontent.com/36557759/209605413-6658ff11-7b30-4b91-8f0e-fde4047cc106.png)

![image](https://user-images.githubusercontent.com/36557759/209605434-eeac4c00-2a5d-4cd5-a9a6-58c46dee2c86.png)

![image](https://user-images.githubusercontent.com/36557759/209605445-c4efecae-5cec-4b88-bad5-886ee710f171.png)

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.12-premium-rev04

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1845
