### ISSUE TITLE
Bug/error: error migrasi table log_surat field urls_id

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#6146]
### Jelaskan error yg dialami

![image](https://user-images.githubusercontent.com/36557759/209609108-b3537b8d-380e-4ed6-bce8-e3aba05fd146.png)

SOLUSI SEMENTARA : tabel log_surat, short kolom urls_id dan cari angka 9 dan ubah menjadi NULL

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.12-premium-rev04

**Comment by agungsugiarto** [comment]
mas @devrakapriyo bisa kirimkan backup database yg bermasalah

**Comment by vickyrolanda** [comment]
mas @devrakapriyo  mohon kirimkan backup databasenya mas

**Comment by devrakapriyo** [comment]
Sementara issue di close, database sebelum migrasi belum ada
