### ISSUE TITLE
Bug/error: Saat buat surat kolom pendidikan tidak muncul isinya - template tinymce

### ISSUE THREAD

**Issue by Agungf19** [OpenSID/OpenSID#6148]
### Jelaskan error yg dialami

saat mau membuat surat menggunakan surat tinymce, kolom pendidikan tidak muncul alias kosong setelah memilih penduduk, kelihatanya kolom pendidik surat tinymce masih mengarah ke biodata penduduk kolom pendidikan yang sedang di tempuh.
ini contoh pembuatan surat tinymce yang kolom pendidikanya kosong :
![photo_6145415988426945594_w](https://user-images.githubusercontent.com/43205017/209620757-34e3f77e-7deb-462a-9193-e489608ea310.jpg)

ini contoh pembuatan surat tinymce jika penduduk yang kolom pendidikan sedang di tempuh terisi :
![photo_6145415988426945616_w](https://user-images.githubusercontent.com/43205017/209620877-7b755b8f-6126-45c3-bac8-9603e86b518f.jpg)

### Cara untuk mereplikasi errornya

1. klik menu cetak surat
2. pilih surat dengan template surat tinymce
3. kemudian pilih warga/pendudukanya
4. lihat kolom pendidikan

### Hasil yg diharapkan

mohon untuk di perbaiki minor bugs tersebut, sehingga kedepanya saat buat surat dengan template surat tinymce bisa digunakan

### Tangkapan layar dan log error

![photo_6145415988426945594_w](https://user-images.githubusercontent.com/43205017/209621173-d6beebce-0420-4756-8918-957c77901ca1.jpg)
![photo_6145415988426945616_w](https://user-images.githubusercontent.com/43205017/209621179-4b1ab700-3e33-4091-b14f-04f89df96309.jpg)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Versi 22.12-premium-rev03

### Tema Yang Digunakan

Batuah 22.11

### Informasi tambahan

tidak ada

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR sesuaikan data pendidikan pada konfirmasi penduduk cetak surat tinymce
