### ISSUE TITLE
Bug/error: logo desa pada qrcode lihat surat tidak muncul

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#6149]
### Jelaskan error yg dialami

<img width="1440" alt="Screen Shot 2022-12-27 at 15 06 36" src="https://user-images.githubusercontent.com/36557759/209633741-8751905a-5f52-43f2-bd69-f8fbea7c2c1d.png">

sebelum versi 22.12-premium-rev04 logo desa muncul, tetapi di versi rev04 logo desa tidak muncul

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.12-premium-rev04

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1851
