### ISSUE TITLE
Merubah tanggal postingan artikel / mengganti tanggal Publish

### ISSUE THREAD

**Issue by desaleu** [OpenSID/OpenSID#615]
Pada saat membuat sebuah postingan baru tetapi kita ingin menerbitkannya itu pada waktu yang kita inginkan, maka kita tidak perlu menyimpannya sebagai draft atau kemudian harus menunggu sampai tiba waktunya untuk mempublish atau menerbitkannya. Jadi issunya adalah:
1. Bagaimana agar kita bisa mengatur kapan postingan akan diterbitkan secara otomatis dengan merubah bulan, tanggal, tahun, jam dan menit (POSTINGAN TERJADWAL)
2.  Bagaimana jika kita ingin rutin posting artikel tiap hari misalnya, tetapi siatu saat ada hari yg terlewatkan tanpa kita posting artikel berita. Issunya adalah bagaimana ketika kita menulis artikel, sebelum kita publish ada pilihan untuk mengatur tanggal penerbitan. Sehingga hari atau tanggal yg terlewatkan bisa kita isikan postingan artikel walaupun itu dipublish d hari yg lain..

**Comment by Jehamahdan** [comment]
Yup,  setuju...  Seperti postingan di wordpress, tanggal postingan bisa di set sesuka hati.

**Comment by afri18** [comment]
kalau menurut saya tidak perlu, cukup artikel kita buat di wordpad atao word (ini dianggap konsep), nanti tinggal copas aja.
karna kalau setingan tanggal kita buat sama aja kita menipu diri sendiri, artikel yg bagus adalah terbit sesuai waktu penulisannya/pemuatan beritanya

**Comment by MUHAMMADRANGSEL** [comment]
kalau mau bisa masuk ke cpanel database cari database artikel setelah itu cari artikel yang mau diedit tanggalnya

**Comment by ombimo** [comment]
![image](https://user-images.githubusercontent.com/20896126/36061255-87144420-0e8a-11e8-88ad-b6349946a24b.png)
sudah saya tambahkan pilihan waktu posting, sudah masuk ke PR #787 
bisa digunakan untuk mejadwalkan postingan atau sekedar mengganti tanggal

**Comment by MUHAMMADRANGSEL** [comment]
Karena issue ini sdh ada dikerjakan dan SDH dicommit perlu diclosed

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui https://github.com/OpenSID/OpenSID/pull/801.

**Comment by desaleu** [comment]
makasih untuk semuaaa

Pada tanggal 23 Feb 2018 14:38, "Eddie Ridwan" <notifications@github.com>
menulis:
