### ISSUE TITLE
Bug/error: Tambahkan Autocomplete="off" di Buku Tamu

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#6150]
### Jelaskan error yg dialami

Pada kolom nama, no hp, instansi, masih muncul history ketik terdahulu.

### Cara untuk mereplikasi errornya

klik kolom tsb, maka akan muncul history ketikan.

### Hasil yg diharapkan

sesuai judul

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v23.01-premium

**Comment by agungsugiarto** [comment]
mas @vickyrolanda assign ke saya saja

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1869
