### ISSUE TITLE
Permintaan fitur: Tambahkan Lampiran F-2.01 Pada Format Suket Kematian

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#6151]
### Apa kekurangan yg ingin diatasi?

Belum tersedianya Lampiran F.201 pada Suket Kematian

### Jelaskan solusi yg diinginkan

Sehubungan dengan banyaknya format baru yang dijadikan persyaratan utama pada setiap permohonan Adminduk di seluruh indonesia karena dengan adanya **SIAK Terpusat** begitu banyak format lampiran yang belom tersedia di Aplikasi OpenSID dan format ini amat sangat dibutuhkan oleh semua desa seperti lampiran dibawah ini.

**1. Lampiran F.201 Untuk Permohonan Akta Kematian**

![F201 Akta Kematian](https://user-images.githubusercontent.com/105429258/172020835-fc02b39a-9a45-428a-94e1-eddbac5bba1a.jpg)

### Apakah ada alternatif lain

Saat ini alternatif yang digunakan dengan cara mengisi formulir secara manual.

### Untuk versi OpenSID mana

Rilis 22.06 Premium

### Informasi tambahan

Ini kedua format LAMPIRAN yang dibutuhkan

[F.201 AKTA KEMATIAN.pdf](https://github.com/OpenSID/OpenSID/files/8838429/F.201.AKTA.KEMATIAN.pdf)

**Comment by Wiliyantoro** [comment]
@vickyrolanda mohon ditambah juga lampiran perkawinan non muslim pak

**Comment by andifahruddinakas** [comment]
https://github.com/OpenSID/OpenSID/issues/6160

**Comment by andifahruddinakas** [comment]
Mas @vickyrolanda, bisa cek komentar https://github.com/OpenSID/OpenSID/issues/6171#issuecomment-1370471828

**Comment by vickyrolanda** [comment]
Ok mas

**Comment by Wiliyantoro** [comment]
![bug 1](https://user-images.githubusercontent.com/44520382/210555218-90af6533-1e13-4aa5-8ea2-49466d5d4063.png)
seperti gambar di atas @vickyrolanda , jumlah col nya terbatas pada 26 karakter, jika nama lebih dari 26 karakter maka akan terpotong, saya sudah modif sedikit codenya tapi belum dapat menemukan solusi agar jumlah col nya pas,

**Comment by vickyrolanda** [comment]
> ![bug 1](https://user-images.githubusercontent.com/44520382/210555218-90af6533-1e13-4aa5-8ea2-49466d5d4063.png) seperti gambar di atas @vickyrolanda , jumlah col nya terbatas pada 26 karakter, jika nama lebih dari 26 karakter maka akan terpotong, saya sudah modif sedikit codenya tapi belum dapat menemukan solusi agar jumlah col nya pas,

Solusi untuk ini bisa menambahkan jumlah kolom khusus di bawahnya ketika nama melebihi jumlah bawaan, kolom tersebut hanya tampil jika nama melebih jumlah kolom bawaan saja. 
mas @andifahruddinakas apakah ini bisa diterapkan ? biar issuenya di pisah saja mas berati jika ini diterapkan otomatis harus di terapkan di semua jenis lampiran.

**Comment by andifahruddinakas** [comment]
> > ![bug 1](https://user-images.githubusercontent.com/44520382/210555218-90af6533-1e13-4aa5-8ea2-49466d5d4063.png) seperti gambar di atas @vickyrolanda , jumlah col nya terbatas pada 26 karakter, jika nama lebih dari 26 karakter maka akan terpotong, saya sudah modif sedikit codenya tapi belum dapat menemukan solusi agar jumlah col nya pas,
> 
> Solusi untuk ini bisa menambahkan jumlah kolom khusus di bawahnya ketika nama melebihi jumlah bawaan, kolom tersebut hanya tampil jika nama melebih jumlah kolom bawaan saja. mas @andifahruddinakas apakah ini bisa diterapkan ? biar issuenya di pisah saja mas berati jika ini diterapkan otomatis harus di terapkan di semua jenis lampiran.

untuk dibuat dinamis sy rasa saat ini tidak bisa karena berkaitan dengan kolom lain di atasnya maupun dibawahnya. Ada pun saat ini jika mau menambahkan bisa dengan melakukan ubah sendiri lampirannya dengan menambahkan kolom yg dibutuhkan (perlu disesuaikan jg kolom lainnya agar tdk berantakan). bisa dibuatkan panduan untuk ini.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1895
