### ISSUE TITLE
Bug/error: muncul pesan error kode isian tidak temukan pada log

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#6152]
### Jelaskan error yg dialami

<img width="1440" alt="Screen Shot 2022-12-28 at 15 07 39" src="https://user-images.githubusercontent.com/36557759/209780277-e7a02573-d06f-4804-9908-bfe449369b9d.png">

ketika melakukan aktivitas ubah/tambah surat dan cetak surat TinyMCE selalu muncul pesan kode isi tidak di temukan pada log

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.12-premium-rev05

**Comment by andifahruddinakas** [comment]
Informasi tambah : 
- untuk log tersebut hanya sebagai informasi tambahan bahwa data2nya belum ada (digunakan untuk development, lupa dihapus). Surat tetap bisa digenerate.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1864
