### ISSUE TITLE
Bug/error: lihat hasil surat tinymce keterangan beda identitas blank page

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#6153]
### Jelaskan error yg dialami

saat klik "lihat hasil surat" surat keterangan beda identitas pada menu pengaturan terjadi blank page pdf

<img width="1440" alt="Screen Shot 2022-12-28 at 15 07 03" src="https://user-images.githubusercontent.com/36557759/209786202-8f7c345b-e56f-44e6-942e-d87af6912711.png">

<img width="1440" alt="Screen Shot 2022-12-28 at 15 07 22" src="https://user-images.githubusercontent.com/36557759/209786222-a2dc50cc-37af-449e-9e70-12303a54774e.png">

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.12-premium-rev05

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1864

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1868
