### ISSUE TITLE
Bug/error: pengaturan alur surat tombol simpan tidak berfungsi

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#6155]
### Jelaskan error yg dialami

<img width="1440" alt="Screen Shot 2022-12-29 at 13 59 01" src="https://user-images.githubusercontent.com/36557759/209915539-d0ee8a12-4333-45f6-ab94-d54ea675606f.png">

ketika di klik tombol simpan tidak ada respon, dan hasil console juga tidak ada fungsi yang berjalan

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.12-premium-rev05

**Comment by vickyrolanda** [comment]
saya check ini aman mas raka coba lihat mungkin ada form yang tidak terisi, coba check di berputar jga mas.

**Comment by devrakapriyo** [comment]
ok mas @vickyrolanda betul ada yang belum terisi, saya close issue ini
