### ISSUE TITLE
Bug/error: pengaruh dari fitur klik kanan di non aktifkan

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#6156]
### Jelaskan error yg dialami

saat ini di versi OpenSID v22.12-premium-rev05 fitur klik kanan di non aktifkan tetapi perlu di pertimbangkan kenyamanan pengguna untuk mengklik kanan kebutuhan open new tab dan lain sebagainya

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.12-premium-rev05

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1870
