### ISSUE TITLE
Bug/error: arsip surat jabatan penandatanganan berubah sesuai jabatan saat ini

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#6157]
### Jelaskan error yg dialami

![image](https://user-images.githubusercontent.com/36557759/209947406-00ed1ec3-2370-43cd-a115-ba2e7d90dbb3.png)

kepala desa yang sudah non aktif, dan jabatan di rename menjadi PLT, maka surat lama dan seluruhnya yg berkaitan dengan nama kades tersebut ikut terpengaruh

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

seharusnya tidak berubah sesuai nama jabatan saat ini

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.12-premium-rev05

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1874
