### ISSUE TITLE
Import data Excel berhasil, tapi beberapa kolom kosong.

### ISSUE THREAD

**Issue by abahku** [OpenSID/OpenSID#616]
Saya melakukan proses import file Excel dengan jumlah data yang tidak banyak, sekitar 4051 penduduk, proses import berhasil dilakukan, sesuai dengan jumlahnya 4051. Namun beberapa penduduk datanya tidak ikut ter-import, saat saya cek tabel aslinya di Excell data tersebut ada dan masih lengkap dengan macro-nya. Saya ulangi proses import tersebut untuk meyakinkan, ternyata hasilnya sama.
Dimana letak salahnya ? Jika ada pernah punya masalah yang sama, mohon solusi.
Terima kasih

**Comment by eddieridwan** [comment]
@abahku saat melaporkan masalah data seperti ini, harap selalu lampirkan rinciannya:

1. persisnya data/kolom mana/apa yang tidak terimpor; apa hasil yang ditampilkan di halaman penduduk
1. apakah ada laporan error
1. lampirkan cuplikan berkas data yang diimpor, dengan menunjukkan baris yang bermasalah.

Tanpa informasi lengkap, sangat sulit untuk dibantu.

**Comment by abahku** [comment]
Terima kasih Pak @eddieridwan atas sarannya.
1. data/kolom yang tidak terimport saya sertakan screenshot-nya.
![screen shot 2017-09-13 at 13 18 24](https://user-images.githubusercontent.com/31700811/30362619-0e281394-9887-11e7-98a0-d80eae6fc683.png)
2. Dari jumlah penduduk 4051 (sesuai dengan jumlah yang saya sampaikan pertama kali), tidak 1 pun muncul ada laporan error atau data gagal di import, screenshot saya sertakan.
![screen shot 2017-09-13 at 13 35 13](https://user-images.githubusercontent.com/31700811/30362628-19ef1286-9887-11e7-9e1e-4fea246705a7.png)
3. Ok, siap Pak, terima kasih.

**Comment by eddieridwan** [comment]
Copy berkas excel yang anda impor; hapus semua baris data kecuali beberapa contoh baris yang bermasalah. Coba hanya impor baris2 tersebut -- untuk konfirmasi masih bermasalah. Kemudian ganti kolom NIK/KK untuk menjaga privasi data dan lampirkan supaya kami bisa lacak masalahnya. 

Karena ini masalah data, terpaksa harus melihat datanya langsung -- tidak ada cara lain. Mungkin ada karakter 'aneh' atau lainnya.

**Comment by abahku** [comment]
Saya mencoba untuk menelusuri data file Excell yang saya import, dengan cara menghapus baris lain kecuali baris yang bermasalah, seperti saran Pak @eddieridwan. Sepertinya saya sedikit menemukan titik temu Issue yang saya lontarkan sendiri disini.

Masalahnya ternyata ada pada file Excell yaitu pada kolom **STATUS HUBUNGAN DALAM KELUARGA** dimana anggota Keluarga yang memiliki **NO_KK** sama seharusnya memiliki salah satu anggota yang statusnya adalah **KEPALA KELUARGA** dengan kode no **1**. Namun ternyata  saya tidak menemukan salah satu dari anggota keluarga dalam KK yang sama itu memiliki status **KEPALA KELUARGA**.

Setelah salah satu anggota keluarga dalam KK yang sama tersebut saya rubah menjadi **KEPALA KELUARGA**, lalu saya coba untuk mengimportnya, Alhamdulillah hasilnya benar, dimana yang semula Data DUSUN, RW dan RT itu kosong, akhirnya sudah terisi sesuai dengan data yang seharusnya.

Sedangkan untuk yang lainnya, saya masih mencoba untuk mencari dimana letak masalahnya  (semoga bisa ditemukan), melalui arahan Pak @eddieridwan.
Semoga ini bisa menjadi pelajaran dan bermanfaat untuk kita bersama.

Terima kasih atas bantuan dan arahannya Pak @eddieridwan 

========================

Berikut saya sertakan hasilnya, silakan untuk membandingkan dengan screenhsot sebelumnya di atas.
![screen shot 2017-09-13 at 17 32 16 copy](https://user-images.githubusercontent.com/31700811/30372587-82568bf8-98a8-11e7-8ca6-3790936ef321.png)

**Comment by MUHAMMADRANGSEL** [comment]
Karena ini disebabkan oleh TDK semuanya kolom data format impor Excel yang diisi shgg issue ini di closed aja

**Comment by eddieridwan** [comment]
Issue ini kami tutup. @abahku: Kalau ada masalah spesifik yg memang bersifat bug, silakan buat issue baru.
Kalau sekadar masalah penggunaan (seperti harus ada kepala keluarga), silakan tanyakan di https://www.facebook.com/groups/OpenSID
