### ISSUE TITLE
Bug : Anjungan Otomatis Aktif Setelah di Perbarui

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#6163]
KONDISI : 
1. Daftarkan beberapa anjungan dengan status aktif maupun tidak aktif.
2. Lakukan pembaruan pada halaman pelanggan.
3. Kembali ke daftar anjungan, semua anjugan yg statusnya tidak aktif malah aktif semua.

SOLUSI : 
1. Hanya aktifkan jika sebelumnya anjugan tsb aktif

CEK ISSUE : 
1. https://github.com/OpenSID/OpenSID/issues/6115

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1894
