### ISSUE TITLE
Perbaikan modul buku-tamu untuk menutup akses ke url langsung tanpa berlangganan lisensi dan belum terdaftar di anjungan

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#6164]

**Comment by agungsugiarto** [comment]
mas @vickyrolanda maksudnya dari issue ini menutup akses `buku-tamu` ketika belum berlangganan anjungan? atau seperti apa maksudnya?

**Comment by vickyrolanda** [comment]
Ia mas betul jdi samakan seperti akses anjungan mas. Kalo belum ada lisensi tidak bsa akses.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1882
