### ISSUE TITLE
Bug/error: tidak bisa mengubah logo dan latar belakang identitas desa

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#6165]
### Jelaskan error yg dialami

saat mengubah logo dan latar belakang muncul notifikasi berhasil tersimpan, tetapi logo dan latar belakang tidak berubah

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v23.01-premium

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1886
