### ISSUE TITLE
Bug/error: hari tidak sesuai tanggal pada data tamu

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#6166]
### Jelaskan error yg dialami

<img width="1440" alt="Screen Shot 2023-01-03 at 16 25 26" src="https://user-images.githubusercontent.com/36557759/210330659-aaf6d7ac-43b0-4442-bd93-711e8adf0e83.png">

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v23.01-premium

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1883
