### ISSUE TITLE
Bug/error: buku tamu jika pertanyaan di perbarui maka pertanyaan yang tersimpan ikut berubah

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#6167]
### Jelaskan error yg dialami

jika ada perubahan pertanyaan yang sudah di isi warga yang mengisi buku tamu, maka pertanyaan yang sudah tersimpan sebelumnya ikut berubah sesuai pertanyaan baru

sehingga hasil dari jawaban index kepuasan yang sudah tersimpan menjadi tidak akurat.

pertanyaan sebelum di ubah
<img width="1144" alt="Screen Shot 2023-01-03 at 16 37 45" src="https://user-images.githubusercontent.com/36557759/210333008-63643ab9-f7a9-4569-bff2-dce363277d50.png">

makan muncul pertanyaan di index kepuasan
<img width="909" alt="Screen Shot 2023-01-03 at 16 37 22" src="https://user-images.githubusercontent.com/36557759/210333138-0773e5e5-4bb3-4850-a324-83a201ef09dc.png">
<img width="904" alt="Screen Shot 2023-01-03 at 16 38 13" src="https://user-images.githubusercontent.com/36557759/210333165-e8284844-6e0f-45ba-b717-656491c3ef3f.png">

setelah di isi maka tersimpan di data kepuasan
<img width="1150" alt="Screen Shot 2023-01-03 at 16 38 34" src="https://user-images.githubusercontent.com/36557759/210333330-6cc7348e-c8c7-4066-8b87-134e14a870e5.png">

tetapi jika pertanyaan tersebut di ubah, maka pertanyaan yang sudah tersimpan di data kepuasan ikut berubah
<img width="1165" alt="Screen Shot 2023-01-03 at 16 39 17" src="https://user-images.githubusercontent.com/36557759/210333467-b2eb90d0-0cde-4548-84ef-7c2d586c74ae.png">

<img width="1156" alt="Screen Shot 2023-01-03 at 16 43 18" src="https://user-images.githubusercontent.com/36557759/210333489-0098504f-cac5-4068-9e5f-90ebedcdb446.png">

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v23.01-premium

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1885
