### ISSUE TITLE
Bug/error: Sediakan fasilitas untuk resize gambar yang sudah ada

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#6168]
### Jelaskan error yg dialami

Saat ini loading halaman dengan banyak gambar sangat lambat, terutama dengan perubahah audit keamanan untuk tidak akses langsung ke file gambar dari browser. Salah satu faktor penyebabnya adalah besarnya gambar saat dibiarkan sesuai dengan file aslinya.

### Cara untuk mereplikasi errornya

1. Unggah banyak gambar dengan ukuran besar yang akan ditampilkan di halaman yg banyak gambar. Sebagai contoh untuk ditampilkan di halaman web publik dengan banyak artikel bergambar atau galeri
2. Buka halaman tersebut dan perhatikan waktu loadingnya.

### Hasil yg diharapkan

Sediakan menu untuk memungkinkan pengguna menginstruksikan sistem supaya secara otomatis meng-kompress, kurangi resolusi atau resize gambar yg melebih batas2 tertentu.

Pastikan proses ini tidak menyebabkan sistem terkunci lama. Tampilkan perkiraan berapa lama waktu yg diperlukan. Berikan pengaturan berapa gambar untuk di-kompress setiap kali dijalankan. Yaitu mungkinkan pengguna menjalankan berulang-ulang di mana setiap kali mengubah sejumlah gambar saja, supaya tidak mengunci sistem terlalu lama. 

### Tangkapan layar dan log error

tidak ada

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

22.01-premium

### Tema Yang Digunakan

sembarang

### Informasi tambahan

Issue ini diberi label 'bug' karena untuk mengatasi masalah loading yg sangat mengganggu.

**Comment by devrakapriyo** [comment]
pak @eddieridwan setelah saya replikasi di artikel dan galeri gambar yang terupload itu sudah ter compress menjadi ukuran sedang / kecil dan resolusi gambar berkurang

**Comment by eddieridwan** [comment]
Periksa juga di unggah gambar yang lain.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1965
