### ISSUE TITLE
Permintaan fitur: Otomatis buat foto ukuran kecil pada waktu unggah foto penduduk

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#6169]
### Apa kekurangan yg ingin diatasi?

Saat ini di halaman penduduk, keluarga dll di mana thumbnail foto penduduk ditampilkan, masih menggunakan file ukuran asli yg kemudian disesuaikan ukuran tampilannya menggunakan css. 

Tapi jika ada banyak foto penduduk, maka penampilan halaman tersebut lambat dan sangat mengganggu.

### Jelaskan solusi yg diinginkan

Secara otomatis buat versi foto penduduk dengan ukuran kecil dan tampilkan versi kecil tersebut di halaman yang menampilkan thumbnail foto penduduk.

### Apakah ada alternatif lain

Bukan alternatif, tetapi strategi tambahan adalah menyediakan lazy loading pada halaman2 tersebut. Issue terpisah dibuat untuk keperluan itu.

### Untuk versi OpenSID mana

v22.02-premium revnn

### Informasi tambahan

Issue ini diberi label 'bug' karena untuk mengatasi masalah loading halaman foto penduduk yg lambat sehingga sangat mengganggu.

**Comment by vickyrolanda** [comment]
issue ini sy close karena terakhir cek bersama foto yang di unggah sudah menggunakan foto yang versi ukuran kecilnya.

**Comment by eddieridwan** [comment]
@vickyrolanda apakah foto penduduk selain versi kecil juga sudah diperkecil jika ukuran aslinya terlalu besar? Jadi setelah diunggah, hasilnya dua foto:

1. ukuran kecil (thumbnail)
2. ukuran yg tidak terlalu besar (mungkin seperti ukuran sedang di foto galeri)
