### ISSUE TITLE
Permintaan fitur: Terapkan lazy loading pada halaman dengan banyak gambar

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#6170]
### Apa kekurangan yg ingin diatasi?

Saat ini halaman dengan banyak gambar loadingnya lambat dan sangat mengganggu. Salah satu faktor adalah besarnya gambar (sesuai dengan ukuran file asli) dan semua gambar ditampilkan sekaligus.

### Jelaskan solusi yg diinginkan

Di halaman dengan gambar banyak, tampilkan gambar dengan cara lazy loading, termasuk menampilkan dengan resolusi rendah dulu, dan juga hanya menampilkan gambar pada saat scroll ke gambar tersebut.

Salah satu referensi lazy loading: https://www.sitepoint.com/five-techniques-lazy-load-images-website-performance/

### Apakah ada alternatif lain

Ada issue terpisah untuk secara otomatis mengurangi ukuran gambar pada waktu diunggah. 
Juga ada issue terpisah untuk membuat gambar versi thumbnail untuk ditampilkan di halaman yg menampilkan thumbnail.

### Untuk versi OpenSID mana

v22.02-premium revnn

### Informasi tambahan

Issue di diberi label 'bug' karena untuk mengatasi masalah loading lambat, yang sangat mengganggu.

**Comment by balongbesuk** [comment]
slider gambar jumlah defaultny 10 mungkin bs dkurangi jadi 6

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1899
