### ISSUE TITLE
Bug/error: lampiran f-2.01 data orang tua di surat keterangan lahir tidak muncul

### ISSUE THREAD

**Issue by Wiliyantoro** [OpenSID/OpenSID#6171]
### Jelaskan error yg dialami

saat cetak surat keterangan lahir pada lampiran f-2.01 tidak muncul data orang tua

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

menampilkan data orang tua di surat ket lahir pada lampiran

### Tangkapan layar dan log error

![surat_ket_kelahiran_5201145107836994_2023-01-03_2_lampiran_001](https://user-images.githubusercontent.com/44520382/210362504-e9a1b4c7-1199-48f0-8b54-33b66d6d5ee1.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v23.01-premium

### Informasi tambahan

di berputar saya pakai testing

**Comment by andifahruddinakas** [comment]
Mas @vickyrolanda, dicek kebutuhnya bagaimana untuk lampiran F-2.01 karena ada beberapa jenis. Pada pengerjaan issue https://github.com/OpenSID/OpenSID/issues/5259 menggunakan https://peraturan.bpk.go.id/Home/Details/138575/permendagri-no-109-tahun-2019 namun dengan data yang ditampilkan sesuai keterangan issue tsb https://user-images.githubusercontent.com/105429258/172020820-064f2da9-8122-46c8-b632-260e2b64736b.jpg

mungkin berlaku juga untuk issue https://github.com/OpenSID/OpenSID/issues/6151, yang perlu di lengkapi data apa saja yg perlu ditampilkan.

**Comment by Wiliyantoro** [comment]
![bug 1](https://user-images.githubusercontent.com/44520382/210555751-a629bf63-6a46-4665-9cde-f1ef9922f982.png)
seperti gambar di atas @vickyrolanda , jumlah col nya terbatas pada 26 karakter, jika nama lebih dari 26 karakter maka akan terpotong, saya sudah modif sedikit codenya tapi belum dapat menemukan solusi agar jumlah col nya pas,

**Comment by andifahruddinakas** [comment]
> ![bug 1](https://user-images.githubusercontent.com/44520382/210555751-a629bf63-6a46-4665-9cde-f1ef9922f982.png) seperti gambar di atas @vickyrolanda , jumlah col nya terbatas pada 26 karakter, jika nama lebih dari 26 karakter maka akan terpotong, saya sudah modif sedikit codenya tapi belum dapat menemukan solusi agar jumlah col nya pas,

mas @vickyrolanda, bisa buat issue untuk kasus ini. Karena di https://peraturan.bpk.go.id/Home/Details/138575/permendagri-no-109-tahun-2019 menggunakan maksimal 26 kolom. Perubahan ini akan mempengaruhi F2.01 untuk yang lainnya.

**Comment by vickyrolanda** [comment]
> F2.01

baik mas sy cari tau dulu bagaimana jika terjadi seperti ini.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1890
