### ISSUE TITLE
Permintaan fitur: Daftar ID Pengunjung di Buku Tamu

### ISSUE THREAD

**Issue by syahransaputra** [OpenSID/OpenSID#6172]
### Apa kekurangan yg ingin diatasi?

Jika tidak dibatasi siapapun bisa mengakses url buku tamu dan bebas submit dan bisa memenuhi data tamu yg bukan tamu yg berkunjung ke Kantor Desa / Kelurahan

### Jelaskan solusi yg diinginkan

Tambahkan Opsi Perangkat yg diperbolehkan untuk mengakses, contoh seperti Layanan Mandiri di (Gaway Layanan) atau seperti Daftar Anjungan, jadi Khusus Buku Tamu harus diset ID Pengunjung

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

v23.01-premium

### Informasi tambahan

-

**Comment by andifahruddinakas** [comment]
Duplikasi https://github.com/OpenSID/OpenSID/issues/6164, buku tamu mengikuti pengaturan anjungan.
