### ISSUE TITLE
Bug/error: Perbadaan waktu input Buku Tamu di local dengan server Berbeda

### ISSUE THREAD

**Issue by syahransaputra** [OpenSID/OpenSID#6173]
### Jelaskan error yg dialami

Pada saat registrasi tamu setelah di simpan maka mengarah ke halaman Index Kepuasan dan langsung memberikan informasi **Belum Ada Tamu Hari Ini**, padahal baru saja di submit. sepertinya ada selisih antara waktu local dan waktu diserver saat submit maka tidak bisa menampilkan nama tamu yg baru saja di submit. Bisa di cek tangkapan layar di bawah

#### **ini terjadi apabila submit mendekati selisih waktu pergantian tanggal antara local dan server masing2

1. buka https://berputar.opendesa.id/buku-tamu lalu isi data tamu setelah itu simpan
2. maka akan tampil Indeks Kepuasan dengan informasi **Belum Ada Tamu Hari Ini**
3. cek perbedaan waktu di https://berputar.opendesa.id/buku_tamu

### Hasil yg diharapkan

Untuk waktu Hari & tanggal di Menu Data Tamu jika bisa di sesuaikan agar tidak ada selisih waktu

### Tangkapan layar dan log error

dari tangkap layar tersebut sudah jelas ada kesalahan nama hari, padahal tanggal 3 Januari 2023 itu hari **Selasa** namun yg tersimpan di database/yg tampil di data tamu tersebut yaitu hari ~Minggu~, Saat submit di lokal yaitu Hari Rabu Tgl 4 Januari 2023
<img width="1710" alt="Jepretan Layar 2023-01-04 pukul 01 21 41" src="https://user-images.githubusercontent.com/26229332/210413219-439706f9-8283-4363-a2ea-a4829bd11665.png">
<img width="1710" alt="Jepretan Layar 2023-01-04 pukul 01 21 18" src="https://user-images.githubusercontent.com/26229332/210413375-7ca88d3d-b18d-4eb9-9e3e-b40181b505d2.png">

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v23.01-premium

### Tema Yang Digunakan

-

### Informasi tambahan

-

**Comment by devrakapriyo** [comment]
terima kasih pak @syahransaputra untuk issue nya, sementara issue ini di close karena duplikat issue https://github.com/OpenSID/OpenSID/issues/6166

dan perihal tanggal yang berbeda, di sebabkan perbedaan timezone server berputar dengan timezone lokasi pak Syahran saat ini

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1888
