### ISSUE TITLE
Bug/error: Saat edit surat masuk

### ISSUE THREAD

**Issue by Agungf19** [OpenSID/OpenSID#6174]
### Jelaskan error yg dialami

kejadian saat saya mau edit isi surat masuk, setelah selesai edit saya klik tombol simpan, kemudian muncul error seperti gambar tersebut, dan surat pun gagal di edit
<img width="694" alt="edit surat masuk" src="https://user-images.githubusercontent.com/43205017/210483264-1e2dfca5-913e-4eed-96a0-11ac24ebe975.png">
<img width="730" alt="error_log" src="https://user-images.githubusercontent.com/43205017/210483360-1270803f-32fc-424e-bb6e-fd8934fc098d.png">

### Cara untuk mereplikasi errornya

1. buka menu buku administrasi umum
2. buku agenda - surat masuk
3. pilih surat, kemudian edit surat
4. klik tombol surat
5. muncul error seperti pada gambar

### Hasil yg diharapkan

semoga untuk kedepanya diperbaiki sehingga bisa di gunakan sebagai mana mestinya

### Tangkapan layar dan log error

<img width="593" alt="error_page" src="https://user-images.githubusercontent.com/43205017/210483821-ba2ec798-6832-44d5-a198-1963cb912e8f.png">

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

23.01

### Tema Yang Digunakan

Batuah 22.11

**Comment by devrakapriyo** [comment]
<img width="1440" alt="Screen Shot 2023-01-04 at 16 08 06" src="https://user-images.githubusercontent.com/36557759/210521009-3a818076-6b8c-4bb8-93c1-7636c25b8735.png">

ini error terjadi jika pada input disposisi kepada tidak di centang sama sekali pada saat di perbarui

**Comment by andifahruddinakas** [comment]
mas @vickyrolanda, solusi dari issue ini menggunakan yg mana : 
1. dibuat required
2. boleh kosong

**Comment by vickyrolanda** [comment]
> 2\. surat masuk

ia mas kondisinya di buat required mas, jdi  ketika tidak memilih jabatan tidak dapat ubah dan tambah seharusnya.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1892
