### ISSUE TITLE
Bug/error: surat Keterangan Untuk Nikah (N-1) salah penandatangan mengetahui camat

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#6176]
### Jelaskan error yg dialami

pada saat cetak surat keterangan nikah (RTF) di bagian penandatangan mengetahui camat belum sesuai camat desa bersangkutan

<img width="318" alt="Screen Shot 2023-01-04 at 12 59 52" src="https://user-images.githubusercontent.com/36557759/210493586-a3d959e7-e7b2-4c1d-8c20-19a24d4223b7.png">

<img width="1440" alt="Screen Shot 2023-01-04 at 13 00 28" src="https://user-images.githubusercontent.com/36557759/210493659-e2022cf5-2e6d-4baf-a207-bd4b2d62af81.png">

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v23.01-premium

**Comment by agungsugiarto** [comment]
mas @devrakapriyo, bisa lebih spesifik untuk surat nikah yg mana, dibawah ini?

![Image](https://user-images.githubusercontent.com/10989147/210499808-e92a9ab1-0cbe-4a9f-9bbd-779e784d7899.png)

**Comment by devrakapriyo** [comment]
Keterangan Untuk Nikah (N-1) mas @agungsugiarto

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1884
