### ISSUE TITLE
Bug/error: [Gawai ini belum terdaftar] Padahal ID Pengunjung sudah benar

### ISSUE THREAD

**Issue by syahransaputra** [OpenSID/OpenSID#6178]
### Jelaskan error yg dialami

Ketika masuk ke Rekam Kehadiran Perangkat Desa informasi tampil [Tidak bisa masuk! Gawai ini belum terdaftar.] padahal ID pengunjung sudah ditambahkan di gawai layanan.

### Cara untuk mereplikasi errornya

1. Pergi ke https://berputar.opendesa.id/kehadiran/masuk
2. Salin ID Pengunjung
3. Pergi ke https://berputar.opendesa.id/gawai_layanan
4. klik Tambah dan tempelkan ID Pengunjung setelah itu Klik Simpan
5. Balik ke https://berputar.opendesa.id/kehadiran/masuk
6. Maka Gawai tetap belum terdaftar.

### Hasil yg diharapkan

Seperti sebelumnya ketika ditambahkan ID Pengunjung maka Gawai terdeteksi

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v23.01-premium

### Tema Yang Digunakan

-

### Informasi tambahan

-

**Comment by andifahruddinakas** [comment]
Duplikasi https://github.com/OpenSID/OpenSID/issues/6164

**Comment by syahransaputra** [comment]
> Duplikasi #6164

Sepertinya tidak duplikasi pak @andifahruddinakas karna issue ini berbeda, ini masalah kehadiran bukan buku tamu

**Comment by andifahruddinakas** [comment]
> > Duplikasi #6164
> 
> Sepertinya tidak duplikasi pak @andifahruddinakas karna issue ini berbeda, ini masalah kehadiran bukan buku tamu

Mas @devrakapriyo, coba di cek ini.

**Comment by devrakapriyo** [comment]
pak @syahransaputra sepertinya yang di maksudkan itu mengakses kehadiran, sedangkan yang yang di replikasikan itu cara mendaftarkan gawai layanan

untuk mengaktifkan fitur kehadiran ada di panduan ini L https://github.com/OpenSID/OpenSID/wiki/Kehadiran-Lainnya#pendaftaran-gawai

untuk sementara issue di close
