### ISSUE TITLE
Bug/error: icon image kosong pada lampiran buku agenda surat masuk

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#6179]
### Jelaskan error yg dialami

<img width="1440" alt="Screen Shot 2023-01-04 at 16 12 43" src="https://user-images.githubusercontent.com/36557759/210523804-1d75e778-d00f-4c0c-8cc2-35e04c256ae6.png">

lampiran berisikan file image/pdf, tetapi muncul icon gambar kosong

### Cara untuk mereplikasi errornya

1. buka menu buku administrasi umum
2. buku agenda - surat masuk
3. pilih surat, kemudian edit surat

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v23.01-premium

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1900
