### ISSUE TITLE
Bug/error: Font Surat TinyMCE Amburadul

### ISSUE THREAD

**Issue by RomziJazz** [OpenSID/OpenSID#6180]
### Jelaskan error yg dialami

Ketika membuat surat TinyMCE tidak dapat menggunakan font selain Arial, karena tulisan akan amburadul.
yang saya coba gunakan adalah Bookman Old Style

### Cara untuk mereplikasi errornya

1. Pengaturan Surat
2. Tambah 
3. di Tab Template di buat format
4. jika menggunakan font Arial ketika di "Lihat Hasil Surat" mana tampilan normal seperti yang diinginkan, namun ketika dirubah ke selain arial akan renggang sehingga tulisan korcar kacir.

### Hasil yg diharapkan

Dapat menggunakan font selain Arial, Seperti Bookman Old Style.

### Tangkapan layar dan log error

![image_2023-01-04_21-30-26](https://user-images.githubusercontent.com/65128302/210696011-1ead46a7-ffbe-4c94-bcac-68db2b9599ae.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

22.12 rev 02 premium

### Tema Yang Digunakan

Silir 3.6.3

**Comment by devrakapriyo** [comment]
untuk font Bookman Old Style setelah di cetak dan ter unduh menjadi file .pdf jarak antar font menjadi renggang, tetapi sebelum terbentuk file .pdf jarak antar font normal

- sebelum cetak
<img width="1440" alt="Screen Shot 2023-01-10 at 13 56 00" src="https://user-images.githubusercontent.com/36557759/211482672-7c526d3e-cfb2-4899-8cc9-0eba9a2fd7fe.png">

- sesudah terunduh
<img width="1440" alt="Screen Shot 2023-01-10 at 13 56 08" src="https://user-images.githubusercontent.com/36557759/211482743-adce52a2-dfdd-455f-85d2-90ea35716181.png">

**Comment by devrakapriyo** [comment]
sedangkan saya coba menggunakan font comic normal

<img width="1440" alt="Screen Shot 2023-01-10 at 14 00 46" src="https://user-images.githubusercontent.com/36557759/211483186-71f76167-6f2d-4108-ad3e-3819c06ecc59.png">

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1934
