### ISSUE TITLE
Bug/error: no urut buku agenda surat masuk

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#6181]
### Jelaskan error yg dialami

<img width="1440" alt="Screen Shot 2023-01-05 at 12 07 04" src="https://user-images.githubusercontent.com/36557759/210705833-a2a9d165-4072-40b3-a74f-2cbc368225e5.png">

apakah no urut pada buku agenda surat masuk akan mengawali ke nomor 1 setiap pergantian tahun?

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v23.01-premium

**Comment by agungsugiarto** [comment]
saya tidak menemukan masalah mas @devrakapriyo 

![Image](https://user-images.githubusercontent.com/10989147/210783002-f4bb82b7-6d07-4b03-9afe-bb06e9af75a3.png)

**Comment by devrakapriyo** [comment]
mas @agungsugiarto di saya masih terjadi
1. ketika saya membuat buku agenda dengan "tahun penerimaan di 2022" dengan nomor urut 1
2. lalu saya membuat buku agenda dengan "tahun penerimaan di 2023" maka nomor urut akan kembali ke no urut 1

yang jadi pertanyaan apakah secara sistem no urut akan kembali ke no 1 setiap tahunnnya? atau itu bug

**Comment by devrakapriyo** [comment]
setelah berdiskusi dengan mas @agungsugiarto nomor urut akan kembali ke urut 1 berdasarkan tahun saat ini, sementara issue di close
