### ISSUE TITLE
Bug/error: Sesuaikan Redaksi Tampilan APBDesa di halaman web, berdasarkan Permendagri 20 Tahun 2018

### ISSUE THREAD

**Issue by mah-mudi** [OpenSID/OpenSID#6182]
### Jelaskan error yg dialami

Belum Sesuainya Redaksi Tampilan APBDesa di halaman web, berdasarkan Permendagri 20 Tahun 2018

### Cara untuk mereplikasi errornya

1. Halaman Web , Footer APBDesa
2. lihat redaksi nya

### Hasil yg diharapkan

Ubah 
Bidang Pembinaan Kemasyarakatan menjadi **Bidang Pembinaan Kemasyarakatan Desa**
Bidang Pemberdayaan Masyarakat menjadi **Bidang Pemberdayaan Masyarakat Desa**
Pendapatan menjadi **Pendapatan Desa**
Belanja menjadi **Belanja Desa**
Pembiayaan menjadi **Pembiayaan Desa**

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/57661283/210738896-09fb1fc9-de87-4f96-8096-1b9a4325dfb8.png)

![image](https://user-images.githubusercontent.com/57661283/210738952-738d6835-1657-4917-9e42-75689d8f4c22.png)

![f12](https://user-images.githubusercontent.com/57661283/210738536-6f63492e-9b39-4144-b98e-ad14a00431e4.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

23.01 Premium

### Tema Yang Digunakan

Esensi v22.11

### Informasi tambahan

https://berputar.opendesa.id/

**Comment by ariandii** [comment]
ijin bertanya. untuk sebutan desa ini apakah di langsungkan bernama Desa atau ikut pada pengaturan sebutan Desa ya?

misal ingin menjadi Gampong, Tiyuh, dll

**Comment by vickyrolanda** [comment]
> ijin bertanya. untuk sebutan desa ini apakah di langsungkan bernama Desa atau ikut pada pengaturan sebutan Desa ya?
> 
> misal ingin menjadi Gampong, Tiyuh, dll

kalo mau seperti ini harus di ubah pak tidak melalui database untuk sebutan desanya , saat ini perubahan masih di ubah melalui database, mungkin ntar sy buatkan issue baru untuk di ubag

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1926

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1969
