### ISSUE TITLE
Permintaan fitur: Update UI

### ISSUE THREAD

**Issue by Vectorostd** [OpenSID/OpenSID#6183]
### Apa kekurangan yg ingin diatasi?

Tolong interfacenya di update dengan UI yang lebih modern

### Jelaskan solusi yg diinginkan

Update UI

### Apakah ada alternatif lain

Tidak ada

### Untuk versi OpenSID mana

Terbaru

**Comment by andifahruddinakas** [comment]
Silahkan buat PRnya jika ada kesempatan.
