### ISSUE TITLE
Link unduh/download tidak tampil pada artikel

### ISSUE THREAD

**Issue by Filterkretek** [OpenSID/OpenSID#6185]
### Jelaskan error yg dialami

Link unduh/download tidak tampil pada artikel

### Cara untuk mereplikasi errornya
Seharusnya setelah menggunggah file lampiran di saat penulisan artikel maka otomatis muncul link unduh/download pada artikel seperti versi sebelumnya.

### Hasil yg diharapkan
Link Unduh/download bisa tampil pada artikel website seperti versi sebelumnya

### Tangkapan layar dan log error

![Screenshot_2023-01-06-05-46-16-37](https://user-images.githubusercontent.com/122057958/210886664-3eef1b22-adc4-4264-a57c-68f6aa286f66.jpg)

![Screenshot_2023-01-06-05-26-16-56](https://user-images.githubusercontent.com/122057958/210888211-37b234da-3c6a-40a9-a483-d8d64a8927d2.jpg)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

23.01

### Tema Yang Digunakan

Silir, Esensi, Natra

### Informasi tambahan

-

**Comment by agungsugiarto** [comment]
saya tidak menemukan issue yg dimaksud, mas @devrakapriyo bisa bantu replikasi issue ini?



![Image](https://user-images.githubusercontent.com/10989147/213692632-dcbe61fc-54b6-4cc8-a17f-72077c8ddbf9.png)

**Comment by agungsugiarto** [comment]
Pak @Filterkretek issue ini saya close, karena tidak ditemukan masalah yang dimaksud. Pastikan ketika mencoba dengan domain atau aplikasi yang sama, ketika pak @Filterkretek melaporkan issue ini mengupload filenya di domain `beta` sedangkan ketika mencoba mengunduh di domain `berputar`
