### ISSUE TITLE
Ubah latar belakang website & login tidak berfungsi, masih muncul gambar bawaan.

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#6186]
1. ubah latar belakang atau latar belakang login 
2. lalu lihat hasilnya gambar yang muncul masih gambar bawaan saja. 
<img width="801" alt="image" src="https://user-images.githubusercontent.com/59082428/210924164-a8f53e2d-0a64-42c5-a313-65ac9cb9f37e.png">
yang tampil 
<img width="736" alt="image" src="https://user-images.githubusercontent.com/59082428/210924188-934573d9-dd73-48b7-a51c-6e57892f48dd.png">

**Comment by agungsugiarto** [comment]
latar belakang website itu tampil dimana mas @vickyrolanda ?

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1897

**Comment by vickyrolanda** [comment]
> latar belakang website itu tampil dimana mas @vickyrolanda ?

untuk backroud ini saya cari dulu ya mas ntar di buat susulan aja mas.
