### ISSUE TITLE
Bug/error: mitigasi pengambilan json SDGs

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#6187]
### Jelaskan error yg dialami

saat ini website SDGs sdgs.kemensos.go.id sedang maintenance yang menyebabkan tidak dapat memperbarui JSON dan halaman SDGs masing masing desa "Tidak dapat mengambil data SDGS" 

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

penyesuaian alur memperbarui JSON SDGs jika terjadi maintenance atau menggunakan data json sudah pernah tercipta saat web SDGs masih normal

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v23.01-premium

**Comment by andifahruddinakas** [comment]
Bukan MT, tp linknya berubah dan disederhanakan dari 
https://sid.kemendesa.go.id/sdgs/searching/score-sdgs?province_code={$kode_provinsi}&city_code={$kode_kabupaten}&district_code={$kode_kecamatan}&village_code={$kode_desa}
menjadi
https://sid.kemendesa.go.id/sdgs/searching/score-sdgs?location_code={$kode_desa}

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1896
