### ISSUE TITLE
Permintaan fitur: Permudah Tombol Tambah Penduduk

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#6188]
### Apa kekurangan yg ingin diatasi?

Saat ini, ketika ingin menambah penduduk dalam 1 KK (misal suami, istri, 4 anak), maka ketika simpan penduduk akan selalu ke biodata oenduduk tsb.

dan perlu klik menu penduduk kembali agar bisa muncul tombol tambah baru. atau klik kembali ke daftar penduduk (yg saat ini loading lama ketika buka penduduk)

### Jelaskan solusi yg diinginkan

adanya tombol tambah penduduk ketika setelah simpan.
(jangan membuat tombol tambah beberapa penduduk karena khawatir menjadi bingung apakah penduduk sebelumnya sudah tersimpan atau belum, tetap tunjukkan hasil biodata penduduk setelah simpan seperti saat ini).

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

Semua

**Comment by devrakapriyo** [comment]
setelah data tersimpan, sediakan tombol tambah penduduk baru pada halaman biodata penduduk

**Comment by agungsugiarto** [comment]
mas @devrakapriyo perlu diskusi untuk issue ini

**Comment by balongbesuk** [comment]
apa tidak akan rancu apa penduduk tersebut penduduk datang atau penduduk lahir,

**Comment by devrakapriyo** [comment]
mas @agungsugiarto tambahkan tombol tambah penduduk di halaman biodata
 
<img width="1440" alt="Screen Shot 2023-01-10 at 13 32 49" src="https://user-images.githubusercontent.com/36557759/211478799-af7393ef-ec52-4460-a58e-20020e057bf9.png">

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1941
