### ISSUE TITLE
Perbaiki Kop Surat

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#6190]
### Jelaskan error yg dialami

Ketika nama kabupaten panjang, maka kop surat akan turun.

diharapkan ketka membuat surat default, font dapat disesuaikan dengan nama kanmbuoaten yg panjang, agar ketika desa baru install opensid (saat ini premium) dan coba buat surat. tidak menghasilkan kop surat yg melebihi garis kop.

### Cara untuk mereplikasi errornya

install opensid baru.
pilih identitas desa yg memiliki nama kabupaten panjang.

tes buat surat tinymce. karena fokus kedepan adalah tiny. (walau di rtf juga hasilnya berantakan)

### Hasil yg diharapkan

rapi, solusi sementara font di kecilkan dari yg sudah ada.

dan surat yg sudah ada dan yg akan dibuat dapat disesuaikan default nya.

### Tangkapan layar dan log error

biaa di praktekkan.

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Seluruhnya

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1904
