### ISSUE TITLE
Bug/error: pencarian data penduduk melambat jika datanya sudah ribuan

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#6191]
### Jelaskan error yg dialami

saat ini pencarian data penduduk terasa lambat mungkin di sebabkan mereload gambar foto penduduk

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v23.01-premium

**Comment by agungsugiarto** [comment]
mas @devrakapriyo, bisa kirim backup database untuk dicoba?

**Comment by vickyrolanda** [comment]
Silahkan bisa menggunakan rev03 terbaru untuk mengatasi permasalahn ini , karena ketika menggunakan v23.01-premium ini memang masih belum di terapkan lazyloading. 

saat ini issue saya close jika masih mengalamin hal serupa silahkan bisa kirim contoh backup database melalui telegram @vickyrolanda .
