### ISSUE TITLE
Bug/error: duplikat nomor urut surat tinymce dan rtf

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#6192]
### Jelaskan error yg dialami

saat ini jika pengguna membuat surat keterangan usaha (TinyMCE) nomor urut 1, lalu besok nya pengguna lain membuat surat keterangan usaha (RTF) maka nomor urut masih 1.

apakah seharusnya nomor urut berlanjut? sehingga tidak duplikat nomor urut surat

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v23.01-premium

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1950
