### ISSUE TITLE
Bug/error: pengecekan import bantuan

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#6195]
### Jelaskan error yg dialami

import akan gagal jika ID pada template excel nya sama dengan ID data yang sama

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v23.01-premium

**Comment by andifahruddinakas** [comment]
Mas @devrakapriyo, @vickyrolanda issue ini perlu diperjelas.

**Comment by devrakapriyo** [comment]
setelah saya cek lebih lanjut, tidak di temukan bug
sementara issue di close

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1911
