### ISSUE TITLE
Fitur : penduduk hubungan keluarga istri seharusnya automatis input status perkawinan nikah

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#6197]
### Jelaskan error yg dialami

-

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v23.01-premium

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1936
