### ISSUE TITLE
Bug/error: qr surat nama penandatangan kades surat ikut di perbarui

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#6198]
### Jelaskan error yg dialami

<img width="1440" alt="Screen Shot 2023-01-07 at 09 40 09" src="https://user-images.githubusercontent.com/36557759/211127882-4438f188-218d-496e-b135-f8ec3286211a.png">

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v23.01-premium

**Comment by devrakapriyo** [comment]
dan perlu di cek beberapa data yang ber query dengan ID kades dan aparatur desa lainnya apakah data lama yang sudah ikut berubah jika ada perubahan aparatur desa

**Comment by apidong** [comment]
> dan perlu di cek beberapa data yang ber query dengan ID kades dan aparatur desa lainnya apakah data lama yang sudah ikut berubah jika ada perubahan aparatur desa

sebaiknya issue tsb dipecah menjadi beberapa issue, karena sangat banyak data yang berelasi dengan data aparatur desa

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1901
