### ISSUE TITLE
Bug/error: tambahkan icon intip pada inputan password

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#6200]
### Jelaskan error yg dialami

- [x] Pengaturan Pengguna / profil
- [x] tambah pengguna / https://beta.opendesa.id/index.php/man_user/form
- [x] ubah pengguna / https://beta.opendesa.id/index.php/man_user/form/1/0/1

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v23.01-premium

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1912
