### ISSUE TITLE
Bug/error: penduduk baru yang tersimpan urutkan ke paling atas

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#6201]
### Jelaskan error yg dialami

<img width="1440" alt="Screen Shot 2023-01-07 at 09 50 05" src="https://user-images.githubusercontent.com/36557759/211128155-06213e60-b627-4707-98fa-304e974326bb.png">

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v23.01-premium

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1908
