### ISSUE TITLE
Bug/error: tambahkan fitur disable tombol ketika sudah 1x klik setiap form

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#6202]
### Jelaskan error yg dialami

tambahkan fitur disable tombol ketika sudah 1x klik simpan perbarui dan hapus di semua form
karena ada beberapa kasus pengguna melakukan beberapa klik, di khawatirkan ada terjadi double input

contoh kasus : double notifikasi telegram ketika ada mengklik tombol lebih dari 1x pada saat form sedang reload

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v23.01-premium

**Comment by andifahruddinakas** [comment]
SOLUSI : 
- Tambahkan notifkasi sedang menyimpan data dan view lainnya tidak bisa di tekan lagi

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1903
