### ISSUE TITLE
Bug/error: class required pada form login admin siteman tidak berfungsi

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#6203]
### Jelaskan error yg dialami

-

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v23.01-premium

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1909
