### ISSUE TITLE
Bug/error: nama aparatur desa tidak muncul jika nama sama

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#6204]
### Jelaskan error yg dialami

https://beta.opendesa.id/index.php/pemerintah
<img width="1440" alt="Screen Shot 2023-01-07 at 10 02 32" src="https://user-images.githubusercontent.com/36557759/211128561-d36c4e49-8b5b-4432-ac9f-4a38a553e6f8.png">

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v23.01-premium

**Comment by andifahruddinakas** [comment]
![image](https://user-images.githubusercontent.com/57283157/211231264-33847b91-e5e5-4f37-b4b0-58bbc70e4e57.png)

**Comment by andifahruddinakas** [comment]
Mas @devrakapriyo, @vickyrolanda issue ini perlu diperjelas.

**Comment by devrakapriyo** [comment]
mas @andifahruddinakas jadi issue ini terjadi jika 
1. saya menonaktifkan aparatur kades/sekdes
2. setelah itu saya mendaftarkan aparatur baru tetapi bukan dari warga
3. jika saya memberi nama percis dengan nama aparatur yang ada saat ini, maka hasilnya aparatur yang di tambah tersebut tidak muncul di https://beta.opendesa.id/index.php/pemerintah

**Comment by vickyrolanda** [comment]
[Sudah diselesaikan di PR](https://github.com/OpenSID/premium/pull/1913) https://github.com/OpenSID/premium/pull/1913
