### ISSUE TITLE
Ubah link gambar domain lain ke link gambar internal storage. 

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#6205]
Bisa dilihat di gambar ada link gambar yang mengarah ke domain lain. 
<img width="792" alt="image" src="https://user-images.githubusercontent.com/59082428/211145791-dd93b14f-7fc5-4fa8-a658-e6a33ed0c5ca.png">

Untuk menghindari copyright mungkin bisa gunnakan asset dibawah ini sebagai gantinya. 

![icon buku](https://user-images.githubusercontent.com/59082428/211146120-634844d8-a3eb-43cb-80b6-c9536b7ddbd7.png)

**Comment by andifahruddinakas** [comment]
Dari segi warna tidak masuk di background

![image](https://user-images.githubusercontent.com/57283157/211239847-0aafd58b-d8fe-4236-b677-63e5983828c1.png)

mungkin ganti yg ini https://cdn-icons-png.flaticon.com/512/3246/3246481.png

**Comment by vickyrolanda** [comment]
> Dari segi warna tidak masuk di background
> 
> ![image](https://user-images.githubusercontent.com/57283157/211239847-0aafd58b-d8fe-4236-b677-63e5983828c1.png)
> 
> mungkin ganti yg ini https://cdn-icons-png.flaticon.com/512/3246/3246481.png
ya lebih bagus mas

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1905
