### ISSUE TITLE
Bug/error: Alamat Tujuan Surat Keterangan Pindah Penduduk

### ISSUE THREAD

**Issue by isnantomch** [OpenSID/OpenSID#6206]
### Jelaskan error yg dialami

Keterangan Pindah Penduduk

pada saat pengisian klasifikasi pindah adanya bug pada Desa/Kelurahan Tujuan dan Kec/Kab/Prop Tujuan
dimana pada texbox Desa/Kelurahan,Kec/Kab/Prop Tujuan menampilkan alamat asal. sehingga sering terjadi
kesalahan saat cetak surat disebabkan alamat tujuan khususnya pada Desa/Kelurahan,Kec/Kab/Prop Tujuan
menampilkan alamat Desa/Kelurahan,Kec/Kab/Prop asal.

Alamat Tujuan Pindah :

1. pindah dalam satu desa/kelurahan sudah OK
![pindah dalam satu desa kelurahan sudah OK](https://user-images.githubusercontent.com/59205349/211239949-0dfcfe32-4855-4ac1-8a4c-2f2f23640865.jpg)

2. pindah antar desa/kelurahan 
teksbox desa/kelurahan seharusnya kosong (disis manual)
teksbox kec sudah ok
teksbox Kab sudah ok
teksbox Prov sudah ok
![pindah antar desa kelurahan](https://user-images.githubusercontent.com/59205349/211239993-3dd39ac9-2e7f-4b4b-bc46-d7dd2f7759b1.jpg)

3. pindah antar kecamatan
teksbox desa/kelurahan seharusnya kosong (disis manual)
teksbox kec seharusnya kosong (disis manual)
teksbox Kab sudah ok
teksbox Prov sudah ok
![pindah antar kecamatan](https://user-images.githubusercontent.com/59205349/211240011-045f15b8-9bd7-4872-a766-f1189532d757.jpg)

4. pindah antar Kab
teksbox desa/kelurahan seharusnya kosong (disis manual)
teksbox kec seharusnya kosong (disis manual)
teksbox Kab seharusnya kosong (disis manual)
teksbox Prov sudah ok
![pindah antar Kab](https://user-images.githubusercontent.com/59205349/211240020-6947190b-028d-4498-9507-dfc365645eda.jpg)

5. pindah antar Kab
teksbox desa/kelurahan seharusnya kosong (disis manual)
teksbox kec seharusnya kosong (disis manual)
teksbox Kab seharusnya kosong (disis manual)
teksbox Prov seharusnya kosong (disis manual)
![pindah antar Kab](https://user-images.githubusercontent.com/59205349/211240040-ec13067d-2723-4b21-8c90-496c9b795b2e.jpg)

### Cara untuk mereplikasi errornya

Langkah untuk mereplikasi error yg dialami, misalnya:

Pergi ke halaman 'cetak surat'
Klik tombol 'klasifikasi pindah'
pilih klasifikasi pindah
Lihat bug

### Hasil yg diharapkan

Alamat Tujuan Pindah :

1. pindah dalam satu desa/kelurahan sudah OK

2. pindah antar desa/kelurahan 
teksbox desa/kelurahan seharusnya kosong (disis manual)
teksbox kec sudah ok
teksbox Kab sudah ok
teksbox Prov sudah ok

3. pindah antar kecamatan
teksbox desa/kelurahan seharusnya kosong (disis manual)
teksbox kec seharusnya kosong (disis manual)
teksbox Kab sudah ok
teksbox Prov sudah ok

4. pindah antar Kab
teksbox desa/kelurahan seharusnya kosong (disis manual)
teksbox kec seharusnya kosong (disis manual)
teksbox Kab seharusnya kosong (disis manual)
teksbox Prov sudah ok

5. pindah antar Kab
teksbox desa/kelurahan seharusnya kosong (disis manual)
teksbox kec seharusnya kosong (disis manual)
teksbox Kab seharusnya kosong (disis manual)
teksbox Prov seharusnya kosong (disis manual)

### Tangkapan layar dan log error

sudah saya sertakan pada penJelaskan error yg dialami

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Versi 23.01-premium

### Tema Yang Digunakan

Batuah 22.11

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1928
