### ISSUE TITLE
[TinyMCE] Konversi surat RTF - Keterangan Domisili Penduduk

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#6209]
<img width="516" alt="image" src="https://user-images.githubusercontent.com/59082428/211452949-412cedda-c5c4-492a-9216-7594ece3413e.png">

**Comment by scqolbu24** [comment]
mas @vickyrolanda saya cek di berputar tidak ada contoh surat ini `Keterangan Domisili Penduduk` adanya `Keterangan Domisili` dengan format surat `Format nomor surat: S-41/001/3303162007/VI/2023` kalu di issue ini Format nomor surat: 470/012/Ds.I/2023
