### ISSUE TITLE
[TinyMCE] Konversi surat RTF -  Keterangan Domisili

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#6212]
<img width="531" alt="image" src="https://user-images.githubusercontent.com/59082428/211453759-77e15293-48b0-47d0-9e66-8ed7cc37c116.png">

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2442
