### ISSUE TITLE
[TinyMCE] Konversi surat RTF - Surat Keterangan Kepemilikan Kendaraan

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#6214]
<img width="441" alt="image" src="https://user-images.githubusercontent.com/59082428/211459876-140ddafa-bbab-43cf-a85a-68e95ba554b3.png">

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2451
