### ISSUE TITLE
[TinyMCE] Konversi surat RTF - Keterangan Penghasilan Ayah

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#6217]
<img width="529" alt="image" src="https://user-images.githubusercontent.com/59082428/211460214-71ba82e6-249d-44d9-8012-acb3453da3c9.png">

**Comment by andifahruddinakas** [comment]
@FirlianiF

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/2472
