### ISSUE TITLE
[TinyMCE] Konversi surat RTF - Keterangan Penghasilan Ibu

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#6218]
<img width="529" alt="image" src="https://user-images.githubusercontent.com/59082428/211460352-89e6f1e0-c92f-46f6-bd50-22e1bd72ea3f.png">

**Comment by andifahruddinakas** [comment]
@FirlianiF

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/2483
