### ISSUE TITLE
[TinyMCE] Konversi surat RTF - Keterangan Penghasilan Orangtua

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#6219]
<img width="525" alt="image" src="https://user-images.githubusercontent.com/59082428/211460471-1126b36c-236f-46ef-85ef-b6d091d553f2.png">

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/2471

**Comment by luxmant354** [comment]
kami usulkan untuk dibuatkan rumus penghitungan otomatis seperti surat keterangan penghasilan orang tua versi rtf sebagaimana contoh terlampir 
![photo_2023-08-15_20-07-53](https://github.com/OpenSID/OpenSID/assets/44687953/e25278af-4964-4c78-b2a6-b93010cc426c)
