### ISSUE TITLE
[TinyMCE] Konversi surat RTF - Keterangan Untuk Nikah (N-1)

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#6220]
<img width="514" alt="image" src="https://user-images.githubusercontent.com/59082428/211460746-fc398768-19d1-4c77-910c-8b3cda8e9ed2.png">

branch: ketnikah

- [ ] https://github.com/OpenSID/OpenSID/issues/6913
- [ ] https://github.com/OpenSID/OpenSID/issues/6914
- [ ] https://github.com/OpenSID/OpenSID/issues/6915
- [ ] https://github.com/OpenSID/OpenSID/issues/6916
- [ ] https://github.com/OpenSID/OpenSID/issues/6917
- [ ] https://github.com/OpenSID/OpenSID/issues/6918
- [ ] https://github.com/OpenSID/OpenSID/issues/6919
- [ ] https://github.com/OpenSID/OpenSID/issues/6920
- [ ] https://github.com/OpenSID/OpenSID/issues/6921
- [ ] https://github.com/OpenSID/OpenSID/issues/6922

**Comment by vickyrolanda** [comment]
Berkaitan : 

- [ ] https://github.com/OpenSID/OpenSID/issues/6891

**Comment by scqolbu24** [comment]
Berikut format surat RTF: 
[surat_ket_nikah.pdf](https://github.com/OpenSID/OpenSID/files/12137598/surat_ket_nikah.pdf)

**Comment by scqolbu24** [comment]
issue susulan 

- [ ] https://github.com/OpenSID/OpenSID/issues/6936

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/2645

**Comment by vickyrolanda** [comment]
issue ini sy buka karena perlu ada PR susulan terkait **semua tanggal dengan yang kosong tidak terisi ,namun tetap dengan format berikut  01 Januari 1970**

![image](https://github.com/OpenSID/OpenSID/assets/59082428/b04b2994-4367-470a-86cf-26e396ae0261)

mohon bantuannya mas @pandigresik

**Comment by pandigresik** [comment]
![image](https://github.com/OpenSID/OpenSID/assets/1853475/c65c9370-8a94-4fc3-b667-f3a1c9fe8588)

**Comment by pandigresik** [comment]
![image](https://github.com/OpenSID/OpenSID/assets/1853475/3ddb94d5-c5c8-41b5-abde-34d8321580ed)

Surat N2

**Comment by pandigresik** [comment]
![image](https://github.com/OpenSID/OpenSID/assets/1853475/34d2d9b4-1b31-4d31-94ed-521c800e554d)

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/2716
