### ISSUE TITLE
[TinyMCE] Konversi surat RTF - Perintah Perjalanan Dinas

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#6224]
<img width="519" alt="image" src="https://user-images.githubusercontent.com/59082428/211463473-784b8538-3dab-43f6-a636-d05ef98e2c59.png">

**Comment by andifahruddinakas** [comment]
@FirlianiF

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/2455
