### ISSUE TITLE
[TinyMCE] Konversi surat RTF - Permohonan Kartu Keluarga

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#6227]
<img width="537" alt="image" src="https://user-images.githubusercontent.com/59082428/211464095-227cb23d-f5a1-4b72-9270-25204270a9e1.png">

Lampiran ( F-1.15, F-1.01, F-1.02 )

**Comment by andifahruddinakas** [comment]
@FirlianiF

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/2469
