### ISSUE TITLE
Bug/error: Sesuaikan Nama Pamong

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#6233]
### Jelaskan error yg dialami

Ketika nama penduduk tidak ada gelar, maka nama pamong dapat diimbuhi gelar pada halaman aparatur desa.

tetapi saat cetak surat dan scan qrcode. hasil halaman verifikasi surat, penandatangan muncul berdasarkan data penduduk, bukan dari data pemerintah desa yang sudah diberi gelar.

===
begitu pula pada halaman widget, halaman web pemerintah desa, dll termasuk di bagan SOTK

### Cara untuk mereplikasi errornya

seperti di atas.

cetak surat dengan ttd pamong ber gelar. dan cek pada halaman verifikasi apakah muncul nama penduduk tanpa gelar atau sesuai menu pemerintah desa.

begitu juga di widget dan halaman web pemerintah desa. serta di halaman SOTK

### Hasil yg diharapkan

sesuaikan seharusnya yang disetting pada menu pemerintah desa.

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Seluruhnya

**Comment by agungsugiarto** [comment]
sudah diperbaiki melalui pr https://github.com/OpenSID/premium/pull/1921
