### ISSUE TITLE
Bug/error: Perbaiki Ejaan

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#6234]
### Jelaskan error yg dialami

<img width="643" alt="image" src="https://user-images.githubusercontent.com/46939846/211699600-56139f22-c9ee-4310-b81c-6836e2fe387d.png">

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Seluruhnya

**Comment by ariandii** [comment]
<img width="643" alt="image" src="https://user-images.githubusercontent.com/46939846/211699760-c1c8b594-2cac-4851-bc28-881e2f6f220a.png">

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1920
