### ISSUE TITLE
ANGGOTA KELUARGA DIPECAH TIDAK TAMPIL DI MENU TAMBAH DARI DATA PENDUDUK YANG SUDAH ADA

### ISSUE THREAD

**Issue by pemdeslinggapura** [OpenSID/OpenSID#6236]
### Jelaskan error yg dialami

Sudah melakukan pecah anggota keluarga, tapi data penduduk tersebut tidak tampil di menu Tambah KK baru atau Anggota baru dari data penduduk yang sudah ada pada versi premium 22.12 Premium Rev.03

### Cara untuk mereplikasi errornya

1. Kartu keluarga
2. klik no kk
3. Kembali ke daftar anggota keluarga
4. Tambah Anggota
5. Dari penduduk sudah ada

### Hasil yg diharapkan

Kembali bisa menambahkan data dari penduduk yang sudah ada/pecah

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/89450861/211748554-eea316a6-6749-41f3-97f7-cf3a84f11ca6.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

22.12-premium-rev03

### Tema Yang Digunakan

Esensi

**Comment by devrakapriyo** [comment]
pak @pemdeslinggapura saya replikasi di berputar normal
bisa berkomunikasi langsung dengan saya melalui telegram @rakapriyo untuk pengecekan lebih lanjut

**Comment by vickyrolanda** [comment]
pak @pemdeslinggapura silahkan hubungi mas @devrakapriyo jika masih mengalamin ini karena saat ini di uji coba di berputar normal mas, 

untuk sementara issue saya close jika sudah ada informasi dari @pemdeslinggapura melalui kirim database ke mas @devrakapriyo dan dilakukan uji coba nanti akan di testing telebih dahulu jiak di termukan permasalahan atau bug maka issue ini bisa di buka kembali oleh mas @devrakapriyo
