### ISSUE TITLE
Bug/error: Jumlah Peserta Bantuan Selisih (Dicoba dulu)

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#6237]
### Jelaskan error yg dialami

Tidak bisa lakukan ujicoba di dev.opendesa.id karena mode demo

Ketika klik Lihat Detail pada bantuan di halaman utama dashboar admin, akan diarahkan ke tabel statistik penerima bantuan.

Terlihat ada baris Peserta, Bukan Peserta, dan Total.

Diduga Total Peserta dan Bukan Peserta akan selisih jika Peserta Bantuan telah diubah status dasarnya.

### Cara untuk mereplikasi errornya

Buat Program Bantuan Sasaran Penduduk, katakanlah saat ini ada 100 penduduk.
1. Input beberapa peserta, misal 2
2. Lalu cek Statistik Bantuan tersebut. maka akan tampil Peserta 2, Bukan Peserta 98, Total 100
3. Lakukan ubah status dasar (misal mati) penduduk salah satu peserta bantuan tersebut.
4. Cek kembali statistik bantuan di atas, maka akan tertulis, Peserta 2, Bukan Peserta 98, Total 99

ada selisih total 1 orang

### Hasil yg diharapkan

Sesuai kondisi saat ini

### Tangkapan layar dan log error

.

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Semua

**Comment by ariandii** [comment]
Sesuai kondisi saat ini = setalah terdapat penduduk yang diubah status dasarnya.

**Comment by agungsugiarto** [comment]
meskipun status penduduknya berubah menjadi mati, di statistik bantuan tetap ditampikan pak?
