### ISSUE TITLE
Bug/error: Redirect Hapus Arsip Surat Belum Benar

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#6238]
### Jelaskan error yg dialami

Coba hapus 1 arsip surat, di menu Layanan Surat -> Arsip Layanan klik yg hijau (arsip surat)

Ketika klik icon tempat sampah (hapus), maka halaman akan redirect ke Permohonan

### Cara untuk mereplikasi errornya

Coba hapus 1 arsip surat, di menu Layanan Surat -> Arsip Layanan klik yg hijau (arsip surat)

Ketika klik icon tempat sampah (hapus), maka halaman akan redirect ke Permohonan

### Hasil yg diharapkan

Seharusnya halaman tetap pada Arsip.

### Tangkapan layar dan log error

dicoba

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Berputar v23.01-premium-rev01

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1927
