### ISSUE TITLE
Tambahkan Peringatan No KIA Sudah ada Ketika Input data KIA baru.

### ISSUE THREAD

**Issue by RomziJazz** [OpenSID/OpenSID#6239]
### Apa kekurangan yg ingin diatasi?

Tidak ada pemberitahuan Nomor KIA sudah ada, ketika klik simpan langsung kembali ke halaman daftar seperti penyimpanan sukses, padahal ketika di cek lagi, data yang ada masih tetap yang lama yang tidak diketahui oleh operator.

di coba di berputar.opendisa.id juga sama.

### Jelaskan solusi yg diinginkan

Penambahan Peringatan Nomor KIA sudah ada ketika input data KIA baru. karena mekanisme pemberian nomor KIA tentu berbeda dan SDM yang menginput tentu juga berbeda.

### Apakah ada alternatif lain

Munculkan Peringatan untuk merubah no KIA.

### Untuk versi OpenSID mana

v23.02-premium

**Comment by yonathanrizky** [comment]
untuk menu input KIA ada dimana mas @RomziJazz ?

**Comment by yonathanrizky** [comment]
saya coba di berputar.opendesa.id sudah ada notifnya pak, apakah ada case lain yg menyebabkan tidak muncul notif ini?

**Comment by andifahruddinakas** [comment]
Sudah lama diterapkan.
