### ISSUE TITLE
Bug/error: latar belakang layanan mandiri tidak berubah

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#6240]
### Jelaskan error yg dialami

latar belakang tidak berubah pada pengaturan layanan mandiri

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v23.01-premium-rev01

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1932
