### ISSUE TITLE
Data penduduk tidak bisa di mutasi masuk 

### ISSUE THREAD

**Issue by mranca** [OpenSID/OpenSID#6244]
### Jelaskan error yg dialami

Saat penduduk yang akan di kembalikan status pada log penduduk muncul pesan error data gagal simpan 

### Cara untuk mereplikasi errornya

Penduduk - pilih aksi lainnya - log penduduk 

### Hasil yg diharapkan

.

### Tangkapan layar dan log error

.

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

22.12

### Tema Yang Digunakan

.

### Informasi tambahan

.

**Comment by andifahruddinakas** [comment]
Cek https://github.com/OpenSID/rilis-premium/releases/tag/v23.01-premium

Sudah diperbaiki.
