### ISSUE TITLE
Bug/error: Sepertinya </a> Pada Gambar Terlampir Berikut Tidak digunakan.

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#6245]
### Jelaskan error yg dialami

<img width="627" alt="image" src="https://user-images.githubusercontent.com/46939846/212353444-f417c50a-3d64-4869-bae7-9752dedb04cb.png">

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

-

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1930
