### ISSUE TITLE
Saat intall Awal sebutan pemerintah desa hanya tertulis pemerintah 

### ISSUE THREAD

**Issue by apidong** [OpenSID/OpenSID#6249]
seharusnya Sebutan Pemerintah Desa saat Install awal Adalah 
Pemerintah Desa

**Comment by apidong** [comment]
![image](https://user-images.githubusercontent.com/20056421/212466990-6e1d6c9e-c1c6-4522-837a-6d6ab7ca20e5.png)

**Comment by ariandii** [comment]
info tambahan,
walau default adalah desa,
namun kata desa bisa otomatis sesuai dengan Sebutan Desa di Pengaturan Aplikasi.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1929
