### ISSUE TITLE
setiap gambar yang berkaitan dengan photo bawaan jadi tidak tampil 

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#6250]
1. Pada penduduk masuk
<img width="416" alt="image" src="https://user-images.githubusercontent.com/59082428/212562575-5c222cbc-b8e2-41f1-a97d-4c603acd638d.png">
2. Penduduk lahir
3. Edit data penduduk
Lihat link jadi seperti ini : 
<img width="397" alt="image" src="https://user-images.githubusercontent.com/59082428/212562774-06c06d9c-f810-4f6d-80cf-8b19e4c3410b.png">
4. di tambah anggota keluarga 

perubahan berkaitan PR ini https://github.com/OpenSID/premium/pull/1923

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/1933
