### ISSUE TITLE
OpenKAB - SDGS (setting_aplikasi) - kode_desa_bps

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#6256]
SDGS (setting_aplikasi) - kode_desa_bps
- Perlu ditabahkan migrasi untuk kolom config_id yang berelasi dengan table config(id) 
- Setiap pemanggilan query perlu ditambahkan where(‘config_id’,$config_id) pada kode_desa_bps & confiq_id

**Comment by andifahruddinakas** [comment]
solusi lain bisa pindahkan ke tambel config untuk kode_desa_bps

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1948
