### ISSUE TITLE
OpenKAB - Lembaga desa - Pengelolaan Lembaga & kelompok (kelompok_master)

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#6257]
- pengerjaan pada pengelolaan Lembaga bisa sekalian dengan pengerjaan kelompok karena hanya berbeda tipe untuk kelompok & Lembaga pada table (kelompok_master) 
- Perlu ditabahkan migrasi untuk kolom config_id yang berelasi dengan table config(id) pada table (kelompok_master). 
- Setiap pemanggilan query perlu ditambahkan where(‘config_id’,$config_id)
- Untuk table (kelompok_master  ke kelompok relasikan lalu tambahkan delete cascade
& kelompok ke kelompok_anggota  tambahkan delete cascade)  agar Ketika salah satu data klompok_master di hapus maka akan mengharus turunan yang berkaitan dari table kelompok & kelompok anggota.
- Cetak Data Lembaga / Cetak Data kelompok  query perlu ditambahkan where(‘config_id’,$config_id)
- Unduh Data Lembaga / unduh data kelompok kelompok  query perlu ditambahkan where(‘config_id’,$config_id)

**Comment by apidong** [comment]
sudah diperbaiki melalui  https://github.com/OpenSID/premium/pull/2050
