### ISSUE TITLE
[Template Surat] Penambahan surat keterangan ahli waris & surat keterangan waris

### ISSUE THREAD

**Issue by healm4n** [OpenSID/OpenSID#626]
![18](https://user-images.githubusercontent.com/3977384/30519396-9e8fc34c-9bbf-11e7-8263-44519de91481.png)
![19](https://user-images.githubusercontent.com/3977384/30519395-9e6390e2-9bbf-11e7-9f9b-0d96f32ca6c9.png)

**Comment by siayi** [comment]
pak @healm4n sepertinya surat ini tidak memiliki kp desa ya?

**Comment by healm4n** [comment]
ada pak mungkin tidak terlihat pada screenshotnya, untuk lengkapnya saya lampirkan contoh dokumennya

[SURAT-KETERANGAN-WARIS.docx](https://github.com/eddieridwan/OpenSID/files/1322115/SURAT-KETERANGAN-WARIS.docx)
[SURAT-KETERANGAN-AHLI-WARIS.-newdocx.docx](https://github.com/eddieridwan/OpenSID/files/1322116/SURAT-KETERANGAN-AHLI-WARIS.-newdocx.docx)

**Comment by MUHAMMADRANGSEL** [comment]
Menurut kami tuk surat pernyataan waris dan pembagianwaris, surat jual beli sawah kebun dan sejenisnya, dan surat hibbah sebaiknya tdk dimasukkan di OpenSID krn sifatnya prinsip
