### ISSUE TITLE
OpenKAB - Suplemen – (table suplemen)

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#6262]
- Perlu ditabahkan migrasi untuk kolom config_id yang berelasi dengan table config(id) 
- Setiap pemanggilan query perlu ditambahkan where(‘config_id’,$config_id) 
- Form Data Suplemen perlu ditambahkan nilai default config_id
- Import Suplemen perlu ditambahkan nilai default config_id
- Daftar Terdata Suplemen perlu ditambahkan nilai default config_id
- Unduh Data Suplemen Penduduk perlu ditambahkan nilai default config_id
- Bersihkan perlu ditambahkan nilai default config_id
- Cari Data perlu ditambahkan where(‘config_id’,$config_id) secara default.

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2070
