### ISSUE TITLE
OpenKAB - Calon Pemilih

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#6263]
- Setiap pemanggilan query perlu ditambahkan where(‘config_id’,$config_id)
- Cetak perlu ditambahkan nilai default config_id
- Unduh perlu ditambahkan nilai default config_id
- Pencarian Spesifik perlu ditambahkan nilai default config_id
- Cari Data perlu ditambahkan where(‘config_id’,$config_id) secara default.

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2069
