### ISSUE TITLE
OpenKAB - Laporan Rentan Kelompok

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#6266]
- Setiap pemanggilan query perlu ditambahkan where(‘config_id’,$config_id)
- Cetak perlu ditambahkan nilai default config_id
- Unduh perlu ditambahkan nilai default config_id

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2061
