### ISSUE TITLE
OpenKAB Kehadiran  - kehadiran keluar

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#6271]
- Perlu ditabahkan migrasi untuk kolom config_id yang berelasi dengan table config(id) 
    - Setiap pemanggilan query perlu ditambahkan where(‘config_id’,$config_id)
     - Setiap tambah , edit & hapus perlu ditambahkan where(‘config_id’,$config_id)

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2006
