### ISSUE TITLE
Gagal simpan surat masuk

### ISSUE THREAD

**Issue by makhbub** [OpenSID/OpenSID#6273]
### Jelaskan error yg dialami

tidak dapat menyimpan data surat masuk karena pada bagian disposisi terdapat peringatan "kolom ini diperlukan" meskipun pilihan sudah dicentang

### Cara untuk mereplikasi errornya

Masuk Buku Administrasi desa >> Administrasi Umum >> Arsip Surat Masuk
coba input surat masuk 

### Hasil yg diharapkan

arsip surat masuk dapat berfungsi normal kembali

### Tangkapan layar dan log error

![bug surat masuk](https://user-images.githubusercontent.com/38773660/212580603-9c0beae3-6f64-4777-9daa-8c87bd0b262b.jpg)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

23.01 Premium rev 01

### Tema Yang Digunakan

silir

### Informasi tambahan

-

**Comment by andifahruddinakas** [comment]
https://berputar.opendesa.id/surat_masuk/form

![image](https://user-images.githubusercontent.com/57283157/212596042-cea9bc63-11f4-457e-b4a1-6990a78672ab.png)

**Comment by devrakapriyo** [comment]
pak @makhbub coba di refresh terlebih dahulu, karena saya cek di berputar normal
sementara issue di close
