### ISSUE TITLE
Bug/error: bekas pencarian tetap muncul di halaman berbeda 

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#6274]
### Jelaskan error yg dialami

replikasi
1. melakukan pencarian di halaman penduduk, contoh : AHLUL
2. setelah itu ke halaman artikel, maka pada kolom input pencarian artikel sudah terisi "AHLUL"

<img width="1440" alt="Screen Shot 2023-01-16 at 08 54 04" src="https://user-images.githubusercontent.com/36557759/212582387-ef5b2980-4a8f-41a8-a378-c0883016425c.png">

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v23.01-premium-rev01

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1931
