### ISSUE TITLE
Bug/error: tidak bisa hapus KK kosong

### ISSUE THREAD

**Issue by AlifMunjul** [OpenSID/OpenSID#6275]
### Jelaskan error yg dialami

Nomor KK kosong tidak bisa dihapus, dan tidak bisa di tambah anggota keluarga, error 33303

### Cara untuk mereplikasi errornya

masuk ke menu "keluarga" pilih "KK Kosong" lalu centang pada kotak urut, kemudian pilih aksi dan hapus, lalu muncul gagal

### Hasil yg diharapkan

sebaiknya data KK Kosong bisa diperbaiki atau dihapus untuk diinput ulang atau diperbaiki.

### Tangkapan layar dan log error

![Screenshot_20230116_130718](https://user-images.githubusercontent.com/122770925/212609588-16a3f27b-0d87-44e1-8659-faba9d1a1a77.png)
![Screenshot_20230116_130725](https://user-images.githubusercontent.com/122770925/212609603-d464ae48-1880-4b2b-aa62-def6b98ffda4.png)

### Rilis Versi OpenSID

Rilis Umum

### Versi OpenSID

v22.06

**Comment by devrakapriyo** [comment]
setelah saya cek menggunakan database desa kunir, ada KK yang bisa di hapus ada pula KK yang tidak bisa di hapus
dengan beberapa kasus

- [ ] tidak dapat di hapus jika di dalam KK tersebut masih ada anggota keluarga berstatuskan bukan kepala rumah tangga
- [ ] dapat di hapus jika di dalam KK tersebut tidak ada anggota keluarga
- [ ] tidak dapat di hapus sedangkan tidak anggota keluarga di dalam KK kosong tersebut

terlampir backup database : https://drive.google.com/drive/folders/1Vl-OtBhct5MV2HFksdohRVQkzIAES2UZ?usp=sharing

**Comment by vickyrolanda** [comment]
> setelah saya cek menggunakan database desa kunir, ada KK yang bisa di hapus ada pula KK yang tidak bisa di hapus dengan beberapa kasus
> 
> * [ ]  tidak dapat di hapus jika di dalam KK tersebut masih ada anggota keluarga berstatuskan bukan kepala rumah tangga
> * [ ]  dapat di hapus jika di dalam KK tersebut tidak ada anggota keluarga
> * [ ]  tidak dapat di hapus sedangkan tidak anggota keluarga di dalam KK kosong tersebut
> 
> terlampir backup database : https://drive.google.com/drive/folders/1Vl-OtBhct5MV2HFksdohRVQkzIAES2UZ?usp=sharing

mas @devrakapriyo kasus ini berhubungan dengan ubahan pada database , jika dicoba diberputar tidak ada masalah maka penggua perlu memberitahu apa yg pernah di oleh di databasenya karena dari informasi mas afila tweb_penduduk sempat di ubah.

**Comment by vickyrolanda** [comment]
karna ini versi database ubahan maka issue ini saya close untuk sementara jika memang ini ditemukan bug maka bisa dibuka kembali.
