### ISSUE TITLE
Permintaan fitur: Migrasi CodeIgniter3 ke Laravel

### ISSUE THREAD

**Issue by agungsugiarto** [OpenSID/OpenSID#6280]
### Apa kekurangan yg ingin diatasi?

Migrasi framework codeigniter ke laravel

### Jelaskan solusi yg diinginkan

checklist kebutuhan:

- [ ] Framework codeigniter akan tetap berjalan berdampingan dengan laravel, sebelum legacy code di ubah seluruhnya ke laravel.
- [ ] routing
- [ ] model 
- [ ] view
- [ ] controller
- [ ] library
- [ ] helper (jika penamaan helper sama dengan laravel ubah helper yang ada di codeigniter menggunakan prefix `ci`)
- [ ] pindah folder desa ke storage sesuai folder laravel
- [ ] dll

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

v23.12

**Comment by dobbleone** [comment]
jika ingin mengunakan ralavel apa tidak sebaiknya dibuat dengan full ralavel untuk menghindari ukuran aplikasi opensid yang besar
