### ISSUE TITLE
[bug] migrasi dari versi lama (mis: 1903) ke versi paling baru baik umum/atau premium akan gagal

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#6281]
Jika melakukan migrasi dari versi lama ke terbaru terjadi gagal migrasi.

Cek menggunakan DB berikut : 
https://drive.google.com/drive/folders/18Sxwh5ESdn_S91xhpi6K0QCDrWssgxLJ?usp=share_link

**Comment by apidong** [comment]
terkonfirmasi error 
![image](https://user-images.githubusercontent.com/20056421/215268114-8df5c27b-d7c8-4ba9-9f45-aad9e061e7c8.png)

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1968
