### ISSUE TITLE
Bug/error: gagal migrasi desa kunir

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#6282]
### Jelaskan error yg dialami

saat melakukan migrasi terjadi error 500 dan pesan pada log error "Query error: Cannot drop index 'kontak_ke_tweb_penduduk': needed in a foreign key constraint - Invalid query: DROP INDEX kontak_ke_tweb_penduduk ON kontak"

terlampir backup database desa kunir di gdrive OpenDESA : https://drive.google.com/drive/folders/1Vl-OtBhct5MV2HFksdohRVQkzIAES2UZ?usp=sharing

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Umum

### Versi OpenSID

v23.01

**Comment by vickyrolanda** [comment]
cek mas apakah ada lakukan ubahan sendiri atau import manual pada database.

**Comment by devrakapriyo** [comment]
info dari pengguna tidak ada perubahan dan tidak melakukan import manual, dan proses migrasi selalu gagal mulai dari versi v22.12 sampai versi yang terbaru sedangkan di versi v22.11 berjalan normal mas @vickyrolanda

**Comment by apidong** [comment]
@devrakapriyo @vickyrolanda database ini pernah mengalami perubahan manual, di lihat dari struktur schema dan databasenya ada yang tidak sesuai.
![image](https://user-images.githubusercontent.com/20056421/213082651-f0957b68-aad2-4c62-b041-81bc0564c5f3.png)
![image](https://user-images.githubusercontent.com/20056421/213082734-0ab0a710-0313-4ac2-b22a-e7e040c11d98.png)

kemungkinan pernah melakukan rename tweb_penduduk menjadi tweb_penduduk1 dan membuat table baru tweb_penduduk. hal ini mengakibatkan foreign key di table kontak ikut berubah menjadi tweb_penduduk1

**Comment by vickyrolanda** [comment]
dari informasi mas @apidong sudah cukup jelas dan ada bukti bahwa pengguna sempat melakukan perubahan mohon mas @devrakapriyo bisa sampaikan sama pengguna bahwa database yang melakukan ubahan tidak di anggap bug pada bawaan sistem.

sementara issue ini saya close jika ada informasi lebih lanjut dari pengguna bisa di comment di issue ini mas @devrakapriyo
