### ISSUE TITLE
Bug/error: Ubah Redaksi NIPD menjadi NIAP menyesuaikan Permendagri 47 Tahun 2016 tentang Administasi Pemerintahan Desa

### ISSUE THREAD

**Issue by mah-mudi** [OpenSID/OpenSID#6283]
### Jelaskan error yg dialami

Redaksi NIPD belum sesuai Permendagri 47 Tahun 2016 tentang Administasi Pemerintahan Desa

### Cara untuk mereplikasi errornya

1. Ke Halaman Buku Aparat Pemerintah Desa

### Hasil yg diharapkan

Ubah Redaksi NIPD menjadi NIAP menyesuaikan Lampiran Permendagri 47 Tahun 2016 tentang Administasi Pemerintahan Desa.

Nomor Induk Aparat Pemerintah Desa (NIAP) bagi perangkat desa yang bukan berasal dari Pegawai Negeri Sipil seperti kolom 3 gambar dibawah ini
![image](https://user-images.githubusercontent.com/57661283/212812738-bff6e5eb-4a43-47ad-a68e-0ef472648aeb.png)
![image](https://user-images.githubusercontent.com/57661283/212812781-010cfdf6-bdfe-4206-89cb-91947b1b46d6.png)

### Tangkapan layar dan log error

![niap1](https://user-images.githubusercontent.com/57661283/212811071-c0425ae4-c0be-4eac-9ba5-009acd858542.png)
![niap2](https://user-images.githubusercontent.com/57661283/212811068-a5266177-8531-4236-87c9-22d53b231b1d.png)
![niap3](https://user-images.githubusercontent.com/57661283/212811062-2f3dac7d-09d1-46b3-9b28-abc1e80a2153.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

23.01 Premium rev01

### Tema Yang Digunakan

Esensi

### Informasi tambahan

https://berputar.opendesa.id/

**Comment by andifahruddinakas** [comment]
Bisa di atur sendiri di Pengaturan Aplikasi.

**Comment by apidong** [comment]
![image](https://user-images.githubusercontent.com/20056421/213097553-f4ecb851-bfee-4f2a-bf96-eb5e3bbf61d2.png)

**Comment by vickyrolanda** [comment]
ijin pak @mah-mudi sesuai dengan dengan informasi di atas bisa di ataur sendiri ya pak.

**Comment by mah-mudi** [comment]
Oke pak
