### ISSUE TITLE
Bug/error: Surat TinyMCE di arsip layanan surat kolom keterangan terisi -

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#6284]
### Jelaskan error yg dialami

Surat TinyMCE di arsip layanan surat kolom keterangan terisi **-** walaupun pada waktu cetak surat kolom keterangan atau keperluan terisi 

### Cara untuk mereplikasi errornya

Pergi ke halaman 'Layanan Surat'
Klik tombol 'Cetak Surat'

Buat Surat TinyMCE dan isi kolom keterangan atau keperluan klik cetak
![image](https://user-images.githubusercontent.com/25834335/213248195-0ea32b1a-9504-447a-b6c3-436dd3230b5b.png)

selanjutnya Pergi ke halaman 'Arsip Layanan Surat'
Kolom Keterangan terisi -
![image](https://user-images.githubusercontent.com/25834335/213247517-c5d7574f-56a7-425f-9b2e-888f39fdd708.png)

### Hasil yg diharapkan

Kolom **Keterangan** di Arsip Layanan Surat Terisi sesuai dengan isian pada waktu mencetak surat seperti surat **rtf**

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/25834335/213247740-0f41b59e-47f1-463c-a9a2-f76a97774780.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

23.01 rev 02

### Tema Yang Digunakan

Denava

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1956
