### ISSUE TITLE
Permintaan fitur: Menampilkan poto penduduk di surat TinyMCE

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#6285]
### Apa kekurangan yg ingin diatasi?

Pada surat tertentu ketika ingin menampilkan poto penduduk di surat TinyMCE tidak bisa sedangkan di rtf sudah lama bisa menampilkan poto penduduk

### Jelaskan solusi yg diinginkan

di Surat TinyMCE poto penduduk bisa tampil seperti surat rtf

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

23.01 rev 02

**Comment by andifahruddinakas** [comment]
https://github.com/OpenSID/OpenSID/pull/3797
