### ISSUE TITLE
Bug/error: nama user yang mencetak surat kosong

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#6286]
### Jelaskan error yg dialami

untuk user yang membuat surat seringkali kosong yang dimana kasus ini terjadi jika terjadi internet lelet dan juga status user tiba logout tapi masih bisa cetak surat, kasus ini sudah terjadi beberapa bulan yang lalu namun tidak sempat melaporkannya
![image](https://user-images.githubusercontent.com/25834335/213342135-d109726b-a1b2-4c50-9359-880915c9fbaa.png)

### Cara untuk mereplikasi errornya

Nama user ang membuat surat kosonh
![image](https://user-images.githubusercontent.com/25834335/213342167-113a34cd-5aa5-4ecb-b500-c1f5eb3e5e16.png)

### Hasil yg diharapkan

Jika user tiba2 logout surat tdak tercetak

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/25834335/213342304-56c6972b-c1f2-42a5-ae9e-600e3b69cc1c.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

23.01 rev 02

**Comment by eddieridwan** [comment]
Apakah terjadi karena ada beberapa pengguna yg menggunakan akun yg sama? Sehingga satu yg logout mengakibatkan yg lain ikut logout juga?

Pastikan akun yg sama tidak digunakan bersama-sama sekaligus.

**Comment by vickyrolanda** [comment]
mas @MUHAMMADRANGSEL  saya sudah testing beberapa kondisi tidak mengalamin hal seperti ini , mohon jika berkenan bisa kirim database ke telegram saya mas, di @vickyrolanda

**Comment by vickyrolanda** [comment]
> mas @MUHAMMADRANGSEL saya sudah testing beberapa kondisi tidak mengalamin hal seperti ini , mohon jika berkenan bisa kirim database ke telegram saya mas, di @vickyrolanda

ijin pak @MUHAMMADRANGSEL sementara issue ini sy close karena masih belum tereplikasi bugnya, tpi jika pak @MUHAMMADRANGSEL  masih mengalami hal yg sama mohon bisa diopen kembali issuenya.
