### ISSUE TITLE
Permintaan fitur: Tambahkan Opsi Keperluan Buku Tamu yang dapat diketik manual

### ISSUE THREAD

**Issue by syahransaputra** [OpenSID/OpenSID#6287]
### Apa kekurangan yg ingin diatasi?

Untuk keperluan hanya tersedia dari data keperluan yg ditambahkan admin saja, tidak ada opsi untuk keperluan yg dapat diketik oleh tamu sendiri jika tidak tersedia di data keperluan

### Jelaskan solusi yg diinginkan

-

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

v23.01-premium-rev02

**Comment by syahransaputra** [comment]
up @andifahruddinakas

**Comment by MUHAMMADRANGSEL** [comment]
betul untuk keperluan diketik manual saja seperti alamat

**Comment by MUHAMMADRANGSEL** [comment]
![Screenshot 2024-04-28 232227](https://github.com/OpenSID/OpenSID/assets/25834335/2f05e3bd-082a-4b2a-8024-72864ae142b4)
karena masing2 tamu beda2 keperluan dan tidak mungkin operator atau admin akan menanyakan apa keperluan setiap tamu yang datang

**Comment by MUHAMMADRANGSEL** [comment]
![Screenshot 2024-04-29 010732](https://github.com/OpenSID/OpenSID/assets/25834335/359f8ac8-d065-4621-a4ee-10e33e9ceb51)
