### ISSUE TITLE
Bug/error: gagal proses backup database

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#6288]
### Jelaskan error yg dialami

Gagal backup database terjadi pada OpenSID online dan data tersebut lebih dari 12MB, sedangkan di local normal

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v23.01-premium-rev02

**Comment by vickyrolanda** [comment]
saya pikir ini bukan bug, karena errornya sepertiberikut ini : 
<img width="959" alt="image" src="https://user-images.githubusercontent.com/59082428/214217176-4c189a62-4f76-48ee-becd-bf821a16211b.png">

dimana memori sudah terbatas untuk mengakses file backup, namun jika di naikkan menjadi 
<img width="330" alt="image" src="https://user-images.githubusercontent.com/59082428/214217389-1c7d52a9-753a-441b-afb1-40d479dcca54.png">
maka bisa lakukan backup. 

ada 2 solusinya mas : 
1. Buat pemberitahuan di forum / panduan terkait ini 
2. Ditambahkan informasi bahwa ketika database cukup besar maka perlu di sesuaikan memori_limitnya perlu di tinggikan. 

**_tpi untuk solusi awal perlu diberitahu ke pengguna untuk menaikan memory_limit nya._** 

issue ini saya tutup di ganti dengan permintaan fitur sebagai berikut mas https://github.com/OpenSID/OpenSID/issues/6293
