### ISSUE TITLE
error simpan pengaturan program bantuan pada DTKS

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#6289]
1. Masuk ke menu rumah tangga
2. Klik edit dan centak terdaftar DTKS
3. lalu klik menu DTKS pada salah satu data dari daftar rumah tangga
4. setelah itu akan muncul POPUP 
<img width="680" alt="image" src="https://user-images.githubusercontent.com/59082428/213907178-e84fbfbb-c8b0-47b4-b5ec-e1bf86bf8be1.png">
5. Pilih Tab Bantuan Program Keluarga 
6. Pilih salah satu program bantuan 
7. Lalu simpan 
<img width="669" alt="image" src="https://user-images.githubusercontent.com/59082428/213907227-c3f05bab-9d96-45ae-825c-0992eb8d96f9.png">

**Comment by ruririzal** [comment]
ini mas @vickyrolanda

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1951
