### ISSUE TITLE
Bug/error: TIDAK BISA SIMPAN SAAT INPUT SURAT MASUK

### ISSUE THREAD

**Issue by agusterm** [OpenSID/OpenSID#6291]
### Jelaskan error yg dialami

tidak dapat menyimpan data surat masuk karena pada bagian disposisi terdapat peringatan "kolom ini diperlukan" meskipun pilihan sudah dicentang dan Kolom yang lain sudah diisi lengkap. sudah coba di Refresh tetap tidak mau

### Cara untuk mereplikasi errornya

Pergi ke menu Buku Administrasi Desa / Administrasi Umum / Buku Agenda - Surat Masuk
Klik tombol Simpan (Tidak Mau Menyimpan)

### Hasil yg diharapkan

Sebagaimana Mestinya

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/87739467/214207706-84d01fab-cf36-4fbc-90ea-8b12680f3710.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

23.01-premium-rev02

### Tema Yang Digunakan

Denatra

**Comment by vickyrolanda** [comment]
pak @agusterm  saya testing di rev02 untuk simpan dan edit surat masuk berhasil pak tidak ada kendala. 
<img width="802" alt="image" src="https://user-images.githubusercontent.com/59082428/214219376-482426b8-074a-46b0-96f4-b7c2504b61e0.png">

dan bisa coba jga di https://berputar.opendesa.id/surat_masuk saya tes juga berhasil simpan pak.

untuk sementara issue akan sy close jika masih mengalamin issue ini bisa hubungi saya melalui telegram pak @vickyrolanda agar bisa sy check.

**Comment by agusterm** [comment]
> pak @agusterm saya testing di rev02 untuk simpan dan edit surat masuk berhasil pak tidak ada kendala. <img alt="image" width="802" src="https://user-images.githubusercontent.com/59082428/214219376-482426b8-074a-46b0-96f4-b7c2504b61e0.png">
> 
> dan bisa coba jga di https://berputar.opendesa.id/surat_masuk saya tes juga berhasil simpan pak.
> 
> untuk sementara issue akan sy close jika masih mengalamin issue ini bisa hubungi saya melalui telegram pak @vickyrolanda agar bisa sy check.

tapi di saya tidak tersimpan pak

**Comment by agusterm** [comment]
> > pak @agusterm saya testing di rev02 untuk simpan dan edit surat masuk berhasil pak tidak ada kendala. <img alt="image" width="802" src="https://user-images.githubusercontent.com/59082428/214219376-482426b8-074a-46b0-96f4-b7c2504b61e0.png">
> > dan bisa coba jga di https://berputar.opendesa.id/surat_masuk saya tes juga berhasil simpan pak.
> > untuk sementara issue akan sy close jika masih mengalamin issue ini bisa hubungi saya melalui telegram pak @vickyrolanda agar bisa sy check.
> 
> tapi di saya tidak tersimpan pak

saya hubungi via telegram ya pak

**Comment by vickyrolanda** [comment]
Baik pak
