### ISSUE TITLE
Bedakan antara qrcode tte & opensid 

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#6292]
saat ini qrcode masih mengarah ke link qrcode OpenSID bawaan , perlu di buatkan halaman dengan konten yang berbeda. 
halaman ini bisa di akses jika status dokumen sudah tertanda tanganin secara elektronik.

referensi seperti berikut ini : 
<img width="428" alt="image" src="https://user-images.githubusercontent.com/59082428/214209617-4920b471-b3fb-43a4-95a2-ee57b7148122.png">

**Comment by andifahruddinakas** [comment]
Duplicate issue https://github.com/OpenSID/OpenSID/issues/6690
