### ISSUE TITLE
Kesehatan – Stunting

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#6297]
- Perlu ditabahkan migrasi untuk kolom config_id yang berelasi dengan table config(id) 
-  Setiap pemanggilan query perlu ditambahkan where(‘config_id’,$config_id)
- Setiap tambah , edit & hapus perlu ditambahkan where(‘config_id’,$config_id)

_**selain itu butuh issue masih perlu dilengkapin**_

**Comment by andifahruddinakas** [comment]
Issue dipecah ke : 
https://github.com/OpenSID/premium/issues/2112
https://github.com/OpenSID/OpenSID/issues/6471
https://github.com/OpenSID/OpenSID/issues/6472
https://github.com/OpenSID/OpenSID/issues/6473
https://github.com/OpenSID/OpenSID/issues/6474
https://github.com/OpenSID/OpenSID/issues/6475
https://github.com/OpenSID/OpenSID/issues/6476
https://github.com/OpenSID/OpenSID/issues/6477
https://github.com/OpenSID/OpenSID/issues/6478
