### ISSUE TITLE
Fitur pencarian di web

### ISSUE THREAD

**Issue by batudaa** [OpenSID/OpenSID#63]
Website belum memiliki fitur pencarian

**Comment by eddieridwan** [comment]
Saya sudah mengambil #53 Responsive Design untuk diterapkan. @batudaa, anda mau ambil yang ini?

**Comment by metalab25** [comment]
perlu dicoba nih versi responsifnya

**Comment by eddieridwan** [comment]
@metalab25, untuk diskusi responsive coba lihat https://groups.google.com/forum/#!topic/opensid/92bfV1CGTRU.

**Comment by siayi** [comment]
Artikel yang diposting di web SID bisa digunakan juga sebagai bentuk arsip/dokumentasi kegiatan desa.
Ketka artikel sudah cukup banyak diposting, jika **fitur pencarian** disediakan maka fitur ini akan sangat bermanfaat.

**Comment by MUHAMMADRANGSEL** [comment]
Issue ini sudah dikerjakan dan perlu ditutup
