### ISSUE TITLE
Buku Administrasi Desa - Administrasi Umum

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#6306]
- Perlu ditabahkan migrasi untuk kolom config_id yang berelasi dengan table config(id) 
-  Setiap pemanggilan query perlu ditambahkan where(‘config_id’,$config_id)
- Setiap tambah , edit & hapus perlu ditambahkan where(‘config_id’,$config_id)

- [x] https://github.com/OpenSID/OpenSID/issues/6482
- [x] https://github.com/OpenSID/OpenSID/issues/6493
- [x] https://github.com/OpenSID/OpenSID/issues/6494
- [x] https://github.com/OpenSID/OpenSID/issues/6495

**Comment by andifahruddinakas** [comment]
perlu di pisah jd beberapa issue

**Comment by agungsugiarto** [comment]
mas @vickyrolanda bisa bantu pecah issue untuk masing2 sub modul

**Comment by andifahruddinakas** [comment]
Sudah dipecah menjadi issue lebih kecil.
