### ISSUE TITLE
Buku Administrasi Desa - Administrasi Penduduk

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#6307]
- Perlu ditabahkan migrasi untuk kolom config_id yang berelasi dengan table config(id) 
-  Setiap pemanggilan query perlu ditambahkan where(‘config_id’,$config_id)
- Setiap tambah , edit & hapus perlu ditambahkan where(‘config_id’,$config_id)

_**selain itu butuh issue masih perlu dilengkapin**_

**Comment by agungsugiarto** [comment]
mas @vickyrolanda bisa bantu pecah issue untuk masing2 sub modul

**Comment by agungsugiarto** [comment]
mas @vickyrolanda issue ini bisa di close, karena semua query berkaitan dengan `Buku Administrasi Penduduk` sudah diterapkan

**Comment by vickyrolanda** [comment]
Ok mas
