### ISSUE TITLE
Penambahan Photo di form cetak surat keterangan

### ISSUE THREAD

**Issue by Nanjungwangi** [OpenSID/OpenSID#631]
Gan, bagaimana kalau Di menu cetak surat keterangan (Ket. KTP dlm proses, Ket. beda Identitas, Ket. Kurang Mampu, Dll) ditambahkan Pas Photo yang photonya 
diambil dari database Penduduk?
[surat_ket_ktp_dalam_proses.pdf](https://github.com/eddieridwan/OpenSID/files/1316929/surat_ket_ktp_dalam_proses.pdf)

**Comment by afa28** [comment]
Sudah di master versi premium

https://github.com/OpenSID/OpenSID/pull/3797
