### ISSUE TITLE
Bug/error: Hilangkan tombol pertinjau dan konsep setelah cetak surat

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#6323]
![image](https://user-images.githubusercontent.com/57283157/214461360-51ff2277-ffd3-44ee-a4ad-e63eee736a0b.png)
1. Masih bisa disimpan Sebagai draft, jika di tekan maka akan mengubah status surat yg siap ambil menjadi konsep.

![image](https://user-images.githubusercontent.com/57283157/214461562-ac4365fa-e2b2-4f9d-968d-49f6aeaccb27.png)
![image](https://user-images.githubusercontent.com/57283157/214461634-26361d64-f585-41e6-bc15-9e14e917044a.png)
2. Masih bisa di pertijau.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1957
