### ISSUE TITLE
Bug/error: siteman tidak ada batasan gagal login

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#6324]
### Jelaskan error yg dialami

issue ini terjadi jika mengaupdate ke OpenSID v23.01-premium-rev02 dengan cara pull, jika download file zip berjalan normal
terjadi di :
https://www.natairaya.desa.id/siteman
https://www.nataibaru.desa.id/siteman

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v23.01-premium-rev02

**Comment by vickyrolanda** [comment]
mas @devrakapriyo saya sudah test ini di beberpa tempat seprti berputar dan dev.opendesa.id batasan login berjalan baik untuk ini sy close dulu issue ini, satu indikasi mungkin migrasi untuk modul gagal login ini berlum termigrasi mungkin bisa coba dengan hapus data di table migrasi dan coba lkukan migrasi ulang.
