### ISSUE TITLE
Bug/error: saat migrasi loading tidak berhenti dengan solusi pull ulang

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#6325]
### Jelaskan error yg dialami

issue ini terjadi saat migrasi tetapi loading tidak berhenti, maka solusi sementara yaitu dengan cara pull ulang

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v23.01-premium-rev02

**Comment by devrakapriyo** [comment]
issue sudah clear, issue di close

**Comment by eddieridwan** [comment]
@devrakapriyo apakah betul? Di pertemuan rutin tadi anda laporkan bahwa @ariandii masih mengalami masalah ini di dua desa. Bagaimana dengan dua desa tersebut?

**Comment by devrakapriyo** [comment]
bukan issue ini pak @eddieridwan melainkan issue yang ini

https://github.com/OpenSID/OpenSID/issues/6324

**Comment by eddieridwan** [comment]
Ok
