### ISSUE TITLE
Bug/error: Error 500 Server Timeout saat Input Analysis

### ISSUE THREAD

**Issue by wahyabiantara** [OpenSID/OpenSID#6329]
### Jelaskan error yg dialami

Saat ini desakediri.id menggunakan fasilitas Analysis untuk melakukan input data SDGs baik form Keluarga maupun Individu. Sudah ada sekitar 3.000 data Keluarga yang berhasil di input dan 10.000 data penduduk Individu. Pada saat data yang di input masih dibawah 10.000, proses input masih berlangsung aman, namun saat data sudah mencapai 10.000, mulai terlihat proses input data menjadi sangat lambat, dan terkadang server menampilkan error 500 Server Timeout seperti berikut:

<img width="1173" alt="Screen Shot 2023-01-26 at 22 20 58" src="https://user-images.githubusercontent.com/4361979/214865331-8fa7f097-fa6b-4aaa-ad12-9200f3a9c0d0.png">

Konfigurasi php sudah diset sebagai berikut:

`<IfModule lsapi_module>`
`php_flag display_errors Off`
`php_value max_execution_time 1200`
`php_value max_input_time 1200`
`php_value max_input_vars 1000`
`php_value memory_limit 512M`
`php_value post_max_size 10M`
`php_value session.gc_maxlifetime 1440`
`php_value session.save_path "/var/cpanel/php/sessions/ea-php74"`
`php_value upload_max_filesize 20M`
`php_flag zlib.output_compression Off`
`</IfModule>`

### Cara untuk mereplikasi errornya

1. Login
2. Menu Analysis
3. Master Analysis
4. Rincian Analysis
5. Input Data Sensus / Survey

### Hasil yg diharapkan

Karena keterlambatan ini terjadi hanya pada menu _Input Data Survey_ dan _Laporan Hasil Klasifikasi_, kemungkinan hal ini terjadi karena adanya relational query database dengan jumlah data yang sangat banyak, dimana hal tersebut terjadi saat melakukan pengecekan data untuk Status Input? Jika iya maka saya rasa perlu ada metode lain agar query tidak menjadi lambat saat data jumlahnya banyak.

### Tangkapan layar dan log error

Tidak ada log error. Tangkapan layar sudah saya lampirkan diatas

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

23.01-Premium

### Tema Yang Digunakan

-

### Informasi tambahan

-

**Comment by vickyrolanda** [comment]
ijin pak @wahyabiantara pada umumnya untuk error 500 server timeout adalah error yg di aktibatkan proses respon tidak cukup untuk memproses action, memang benar modul analisis memliki beberapa relasi cakupan data sesuai dari pengaturan data yang di sajikan ,semakin besar maka perlu semakin besar jga proses di butuhkan. 

untuk mengatasi masalah yang bapk hadapi ada beebrapa yang perlu kami lakukan pengecheckkan apakah query OpenSID yang perlu di optimasi atau ada indikasi lainnya, untuk itu mohon bisa menyampaikan atau melapirkan backupan database pak @wahyabiantara melalui telegram pribadi saya @vickyrolanda. 

issue ini semntara sy jadikan analisis terlebih dahulu jika memang terbukti indikasi bug akan segera sy kabarin melalui issue ini , tentu menunggu backupan database pak @wahyabiantara .

**Comment by wahyabiantara** [comment]
Terima kasih pak. As requested, database sudah saya kirimkan untuk di analisa lebih lanjut.

**Comment by andifahruddinakas** [comment]
> ijin pak @wahyabiantara pada umumnya untuk error 500 server timeout adalah error yg di aktibatkan proses respon tidak cukup untuk memproses action, memang benar modul analisis memliki beberapa relasi cakupan data sesuai dari pengaturan data yang di sajikan ,semakin besar maka perlu semakin besar jga proses di butuhkan.
> 
> untuk mengatasi masalah yang bapk hadapi ada beebrapa yang perlu kami lakukan pengecheckkan apakah query OpenSID yang perlu di optimasi atau ada indikasi lainnya, untuk itu mohon bisa menyampaikan atau melapirkan backupan database pak @wahyabiantara melalui telegram pribadi saya @vickyrolanda.
> 
> issue ini semntara sy jadikan analisis terlebih dahulu jika memang terbukti indikasi bug akan segera sy kabarin melalui issue ini , tentu menunggu backupan database pak @wahyabiantara .

mas @vickyrolanda, Database bisa diteruskan ke saya.
