### ISSUE TITLE
Bug/error: Hilangkan Optional Jenis Anggaran ketika Aksi Ubah, karena sudah ada optional diawal

### ISSUE THREAD

**Issue by mah-mudi** [OpenSID/OpenSID#6331]
### Jelaskan error yg dialami

Terdapat Optional Jenis Anggaran **ganda** ketika Aksi Ubah, karena sudah ada optional diawal.

### Cara untuk mereplikasi errornya

1. Modul Keuangan
2. Input Data
3. Aksi Ubah

### Hasil yg diharapkan

Hilangkan Optional Jenis Anggaran ketika Aksi Ubah, karena sudah ada optional diawal.
agar tidak terjadi kebingungan user karena di lock.

### Tangkapan layar dan log error

![CEQ1](https://user-images.githubusercontent.com/57661283/215265812-5a02a8d2-4734-49b4-ba48-d0fd6e5a11dd.png)
![CEQ](https://user-images.githubusercontent.com/57661283/215265816-e97f957c-4016-42c4-a116-3e33a03802b6.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

23.01 Premium rev03

### Tema Yang Digunakan

Esensi

### Informasi tambahan

https://berputar.opendesa.id/keuangan_manual/manual_apbdes

**Comment by andifahruddinakas** [comment]
Tidak perlu dihapus, bug ini terjadi karena perubahan data melalui migrasi di PR https://github.com/OpenSID/premium/pull/1926

Ada pun view tsb sebagai Informasi yang akan di tambahkan dan tidak bisa di ubah.
