### ISSUE TITLE
Permintaan fitur:  Hasil Cetak Buku Tamu urutkan dari yang paling lama ke yang terbaru.

### ISSUE THREAD

**Issue by ai-skematik** [OpenSID/OpenSID#6332]
### Apa kekurangan yg ingin diatasi?

saat ini hasil cetak buku tamu diurutkan dari yang baru ke yang lama, sehingga berbeda dengan cara pengisian buku tamu manual pada umumnya. untuk tampilan di admin sudah sesuai yakni ditampilkan yang terbaru.

### Jelaskan solusi yg diinginkan

-

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

-

### Informasi tambahan

-

**Comment by ai-skematik** [comment]
<img width="949" alt="2023-01-30_09h57_16" src="https://user-images.githubusercontent.com/48144047/215379038-91d9ef18-f706-4795-a601-196ad0e73fce.png">

**Comment by andifahruddinakas** [comment]
Selesai melalui commit https://github.com/OpenSID/premium/commit/7e3d042c0df456d6585cd91123bff9fbcd2c9417
