### ISSUE TITLE
Permintaan fitur: Tambahkan pilihan sortir perbulan dan tahun pada buku tamu

### ISSUE THREAD

**Issue by ai-skematik** [OpenSID/OpenSID#6333]
### Apa kekurangan yg ingin diatasi?

saat ini buku tamu belum ada pilihan tampilkan perbulan atau pertahun. sehingga kesulitan mencari data tamu jika tamu sudah banyak.

### Jelaskan solusi yg diinginkan

-

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

22.03 Premium

**Comment by andifahruddinakas** [comment]
Sudah di kerjakan melalui PR https://github.com/OpenSID/premium/pull/1954
![image](https://user-images.githubusercontent.com/57283157/215405213-8e0014ed-9406-449d-8e5d-10c0564fb79d.png)
