### ISSUE TITLE
Permintaan fitur:  Data keperluan bisa di isi sendiri oleh yang bertamu jika keperluannya tidak ada di list.

### ISSUE THREAD

**Issue by ai-skematik** [OpenSID/OpenSID#6336]
### Apa kekurangan yg ingin diatasi?

-

### Jelaskan solusi yg diinginkan

-

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

23.01 Premium

### Informasi tambahan

-

**Comment by syahransaputra** [comment]
Duplikat issue #6287
