### ISSUE TITLE
Font Bookman Old Style tidak bisa cetak Tebal.

### ISSUE THREAD

**Issue by RomziJazz** [OpenSID/OpenSID#6341]
### Jelaskan error yg dialami

Font Bookman Old Style tidak bisa Bold / Cetak tebal

### Cara untuk mereplikasi errornya

Ketika Cetak Surat font Bookman Old Style tidak bold walau di pengaturan sudah bold.

### Hasil yg diharapkan

Font Ini Bisa Bold sesuai pengaturan.

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

23.02 rilis premium

**Comment by FirlianiF** [comment]
Bisa tolong di screeen shoot pak @RomziJazz bagian mana yg tidak bisa Bold nya, karena saya coba surat berhasil menjadi bold dengan font bookman old style.

mas @vickyrolanda bisa minta tolong di replikasi issue ini mas.

**Comment by vickyrolanda** [comment]
ini mbak @FirlianiF , 
1. di pengaturan saya set bagian yang bold 
<img width="739" alt="image" src="https://user-images.githubusercontent.com/59082428/216900128-f6737e58-aa7d-4deb-bb18-2f3c48fe5c46.png">
2. Klik pertinjau 
<img width="458" alt="image" src="https://user-images.githubusercontent.com/59082428/216900212-a3ecead1-c6b2-4bf8-8fe7-b202e790a55f.png">
3. Klik cetak juga tidak bold : 
<img width="593" alt="image" src="https://user-images.githubusercontent.com/59082428/216900308-6fd86079-3bff-4557-b502-451ba82877a0.png">
4. Pengaturan saya set bold : 
<img width="716" alt="image" src="https://user-images.githubusercontent.com/59082428/216900653-e570eddc-ad5a-484b-838a-56e170d885e3.png">
5. Hasil cetak jdai tidak bold dan berantakan jga sih. 
<img width="547" alt="image" src="https://user-images.githubusercontent.com/59082428/216900969-84d79bb6-66b8-4c27-a613-333660ce0c4e.png">

**Comment by FirlianiF** [comment]
mas @vickyrolanda bisa minta tolong bantu carikan font bookman old style yang full package, karena saya cari2 adanya yg 1 style, belum temukan yg free full package style .

hanya ada yg berbayar saja, seperti:
https://www.fonts.com/font/monotype/bookman-old-style/packages
https://www.myfonts.com/collections/bookman-old-style-font-monotype-imaging

**Comment by vickyrolanda** [comment]
karena setelah di check fotn bookman adalah font berbayar maka Solusi saat ini bisa menggunakan font yang serupa seperti times new roman font yang memiliki karakter serif typeface.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/2082
