### ISSUE TITLE
Tidak bisa nambah surat masuk  & surat keluar

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#6344]
ketika di check ternyata ketika ada isian denga dengan tanda berikut ini  \n maka surat masuk menjadi tidak dapat ditambah. 
![image](https://user-images.githubusercontent.com/59082428/216510139-21696eba-6d5b-4dcc-aedf-eef40ae82d46.png)

**Comment by FirlianiF** [comment]
Setelah di coba, berjalan normal, mohon dicek kembali mas @vickyrolanda .

**Comment by vickyrolanda** [comment]
mbak @FirlianiF kondisi terjadi memang ketika di surat yang sudah lama ke buat dimana didalam judulnya atau kontentnya terdapat simbol \n ini, simbol ini tidak bisa di input dan di edit tapi jika dilakukannya melalui query itu bisa misalkan begini : 
<img width="531" alt="image" src="https://user-images.githubusercontent.com/59082428/217098870-a96003c1-72ca-4cf8-a9d1-656943e9e26c.png">

lalukan update 1 data dan tambahkan di query simbol seperti di SC, 
lalu setelah itu masuk ke menu  : 
1. Administrasi Umum
2. Surat Keluar
3. lalu klik tambah atau edit (jika edit coba hapus centang di  disposisi surat) 
4. nah pada saat mau nambah akan kelihatan notifikasi tidak valid pada disposisi 
<img width="759" alt="image" src="https://user-images.githubusercontent.com/59082428/217099182-50310d0f-bf9d-4282-8158-8ea9c7dfefda.png">
5. Maka tombol tambah tidak dapat di klik seperti noaction 
6. Ini juga berlaku pada surat masuk.

**Comment by FirlianiF** [comment]
> mbak @FirlianiF kondisi terjadi memang ketika di surat yang sudah lama ke buat dimana didalam judulnya atau kontentnya terdapat simbol \n ini, simbol ini tidak bisa di input dan di edit tapi jika dilakukannya melalui query itu bisa misalkan begini : <img alt="image" width="531" src="https://user-images.githubusercontent.com/59082428/217098870-a96003c1-72ca-4cf8-a9d1-656943e9e26c.png">
> 
> lalukan update 1 data dan tambahkan di query simbol seperti di SC, lalu setelah itu masuk ke menu :
> 
> 1. Administrasi Umum
> 2. Surat Keluar
> 3. lalu klik tambah atau edit (jika edit coba hapus centang di  disposisi surat)
> 4. nah pada saat mau nambah akan kelihatan notifikasi tidak balid pada disposisi
> 
> <img alt="image" width="759" src="https://user-images.githubusercontent.com/59082428/217099182-50310d0f-bf9d-4282-8158-8ea9c7dfefda.png">
> 
> 5. Maka tombol tambah tidak dapat di klik seperti noaction 6. Ini juga berlaku pada surat masuk.

bisa dilihat pada opsi disposisi itu blm ada yg dipilih, makanya muncul alert kolom ini diperlukan dibawah pilihan disposisi

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/2001
