### ISSUE TITLE
Pengaturan - Info Sistem

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#6355]
- Perlu ditabahkan migrasi untuk kolom config_id yang berelasi dengan table config(id) 
-  Setiap pemanggilan query perlu ditambahkan where(‘config_id’,$config_id)
- Setiap tambah , edit & hapus perlu ditambahkan where(‘config_id’,$config_id)

_**selain itu butuh issue masih perlu dilengkapin**_

**Comment by apidong** [comment]
@vickyrolanda, mohon ijin untuk diperiksa ulang, setelah saya cek, tidak ada bagian yang perlu di perbaiki

**Comment by andifahruddinakas** [comment]
Sesuai hasil rapat, tidak ada kaitannya dengan tabel sehingga tidak perlu di ubah.
