### ISSUE TITLE
Pengaturan - QR Code

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#6356]
- Perlu ditabahkan migrasi untuk kolom config_id yang berelasi dengan table config(id) 
-  Setiap pemanggilan query perlu ditambahkan where(‘config_id’,$config_id)
- Setiap tambah , edit & hapus perlu ditambahkan where(‘config_id’,$config_id)

_**selain itu butuh issue masih perlu dilengkapin**_

**Comment by apidong** [comment]
@vickyrolanda setelah saya cek, tidak terdapat bagian yang perlu disesuaikan

**Comment by andifahruddinakas** [comment]
Sesuai hasil rapat, tidak ada kaitannya dengan tabel sehingga tidak perlu di ubah.
