### ISSUE TITLE
pengembangan pemasaran SID

### ISSUE THREAD

**Issue by datamso** [OpenSID/OpenSID#637]
Salam,
Saya tertarik akan aplikasi SID, dan kebetulan adik saya punya perusahaan, bolehkah saya menjual aplikasi sid menggunakan perusahaan adik saya, jika boleh syaratnya apa aja, dan kira2 nanti kami akan merubah beberapa fitur yang ada di SID untuk di sesuaikan dengan desa  yang akan kami pasarkan.karna setiad desa di memiliki karakter dan kebutuhan yang berbeda-beda, kami saat ini ingin memasarkannya di sulawesi atau di sumatera
salam

**Comment by eddieridwan** [comment]
Aplikasi OpenSID tidak diperjual-belikan. OpenSID akan selalu gratis dan bebas digunakan desa. Perbaikan/tambahan yang dibuat desa biasanya digabungkan kembali ke aplikasi OpenSID untuk dimanfaatkan bersama oleh semua pengguna. Setiap ubahan OpenSID tetap berlisensi GPL (open source) -- yaitu bebas digunakan oleh semua desa.

Tapi bagi yang menawarkan jasa pelatihan, pendampingan, atau kustomisasi tentunya boleh berbayar. Jika berminat, sebaiknya perusahaan adik anda coba jajaki menawarkan jasa -- dan TIDAK memungut biaya untuk aplikasinya sendiri. Karena pengguna OpenSID terus meningkat, jumlah desa yg memerlukan jasa tersebut akan bertambah terus.

Adanya satu aplikasi OpenSID standar (open source dan gratis) justru membantu teman2 yang menawarkan jasa, karena banyak yg berminat, mudah diupgrade, ada komunitas pendukungnya, ada panduannya. Aplikasi SID yg bervariasi malahan akan membingungkan dan menyusahkan desa nantinya. OpenSID lahir justru untuk mengatasi kerancuan banyaknya variasi SID terdahulu.

Jasa yg ditawarkan pada desa bisa juga berbentuk pemrograman, tapi yang sifatnya kustomisasi, seperti menambah jenis surat atau mengubah penampilan, atau menambah widget. Yaitu yang mengikuti aturan penyesuaian yg dimungkinkan oleh struktur aplikasi. Tapi jangan sampai keluar dari struktur kustomisasi aplikasi, karena nantinya akan menyusahkan desa untuk mengupgrade.

Ok, jika ingin diskusi lebih lanjut, sebaiknya tidak di issue ini (yang tujuannya untuk spesifikasi pemrograman!). Lebih baik bergabung di https://www.facebook.com/groups/OpenSID/ dan kirim PM melalui Facebook.

**Comment by datamso** [comment]
salam, terimakasih atas respon anda yang sangat cepat.

Berhubung lalu lintas pekerjaan utama kami yang sering berhubungan dengan
para pemerintahan di desa, dan kami melihat beberapa kebutuhan aplikasi di
desa, oleh sebap itu memasarkan suatu aplikasi or sistem untuk di miliki
desa.

Berdasarkan masukan dari bapak, maka yang kami perjualbelikan secara khusus
adalah *untuk pelatihan, pendampingan dan instalasi yang berupa jasa orang
terhadap pelayanan di desa tersebut*, dan kami membuat beberapa perobahan
di aplikasi tersebut yang mana penyesuian tersebut adalah atas permintaan
desa tersebut, misalnya untuk desa  yang memiliki perangkat adat atau hukum
adat di desa tersebut, sebagaimana masyarakat adat sudah masuk dalam
otonomi khusus dalam UU otonomi dareah
UNDANG-UNDANG NOMOR 9 TAHUN 2015
<http://www.bpn.go.id/Publikasi/Peraturan-Perundangan/Undang-Undang/undang-undang-nomor-9-tahun-2015-57853>
.

Maka oleh sebap itu kami akan menjaga Aplikasi OpenSID tidak
diperjual-belikan. OpenSID akan selalu gratis dan bebas digunakan desa.


Pada 26 September 2017 19.07, Eddie Ridwan <notifications@github.com>
menulis:

**Comment by eddieridwan** [comment]
Selalu pastikan desa tetap bisa upgrade ke rilis OpenSID selanjutnya dengan mudah. Yaitu, pastikan perubahan apapun yang dibuat, desa nantinya masih bisa mengikuti panduan https://github.com/eddieridwan/OpenSID/wiki/Panduan-Update-OpenSID untuk mengupgrade ke rilis selanjutnya. OpenSID senantiasa dikembangkan -- dan JANGAN sampai desa nantinya tidak bisa memanfaatkan fitur baru yg dirilis OpenSID. Karena kasihan nanti kalau desa sampai tergantung pada perusahaan anda selamanya.

Cara2 untuk kustomisasi dijelaskan diberbagai halaman panduan, seperti:

- https://github.com/eddieridwan/OpenSID/wiki/Mengubah-Template-Surat-Export
- https://github.com/eddieridwan/OpenSID/wiki/Pengelolaan-Widget
- https://github.com/eddieridwan/OpenSID/wiki/Mengubah-Penampilan-Web
- https://github.com/eddieridwan/OpenSID/wiki/Folder-Desa

Intinya, semua perubahan untuk desa harus bisa terisolir di folder _desa_ dan tidak mengubah file inti.

Jika nanti anda mendapat permintaan dari desa yang tidak bisa dilakukan hanya dengan cara2 yg sudah disediakan OpenSID, maka caranya adalah:

- bahas dengan kami, untuk kita kerjasama bagaimana permintaan tersebut bisa dipenuhi tanpa merusak prinsip di atas. Misalnya, bicarakan dengan kami persisnya bentuk fitur yang diminta desa  untuk menerapkan perangkat adat atau hukum adat di desa tersebut.

**Comment by MUHAMMADRANGSEL** [comment]
Ini juga issuenya perlu di tutup
