### ISSUE TITLE
Layanan Mandiri - Pengaturan

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#6372]
- Perlu ditabahkan migrasi untuk kolom config_id yang berelasi dengan table config(id) 
-  Setiap pemanggilan query perlu ditambahkan where(‘config_id’,$config_id)
- Setiap tambah , edit & hapus perlu ditambahkan where(‘config_id’,$config_id)

_**selain itu issue masih perlu dilengkapin**_

**Comment by yogiperdana** [comment]
Saya cek issue ini sudah terselesaikan karena tabel setting aplikasi sudah disesuaikan pada issue lain. Mohon untuk ditesting dulu untuk memastikan mas @vickyrolanda

**Comment by vickyrolanda** [comment]
> Saya cek issue ini sudah terselesaikan karena tabel setting aplikasi sudah disesuaikan pada issue lain. Mohon untuk ditesting dulu untuk memastikan mas @vickyrolanda

ia mas sudah  sesuai di pengaturan sudah di kerjakan oleh mas akas

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1949
