### ISSUE TITLE
Menu Dropdown untuk menu dinamis

### ISSUE THREAD

**Issue by bhien76** [OpenSID/OpenSID#638]
Bang @Eddie Ridwan, saya usul supaya menu dinamis juga menggunakan menu dropdown sama seperti menu statis, supaya enak dilihat
![menu](https://user-images.githubusercontent.com/28255642/30917918-a9572f64-a3cf-11e7-8fa2-eb89c56eabff.jpg)

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.

**Comment by DamesDamai** [comment]
kalo boleh usul untuk menu dropdown pada tampilan menu dinamis kalom bisa untuk semua tema seperti tema default yang menu dinamisnya pakai menu dropdown
