### ISSUE TITLE
Buku Tamu - Data Keperluan

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#6380]
- Perlu ditabahkan migrasi untuk kolom config_id yang berelasi dengan table config(id) 
-  Setiap pemanggilan query perlu ditambahkan where(‘config_id’,$config_id)
- Setiap tambah , edit & hapus perlu ditambahkan where(‘config_id’,$config_id)

Yang perlu di uji, 

- [ ] Tambah & edit & hapus data sesuai dengan perdesa
- [ ] Data yang tampil sesuai dengan perdesa

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2046
