### ISSUE TITLE
[BUG] HTML Injection

### ISSUE THREAD

**Issue by mugi789** [OpenSID/OpenSID#6383]
### Cara untuk mereplikasi errornya

1. Pergi ke halaman awal opensid [https://demosid.opendesa.id/](https://demosid.opendesa.id/)
2. Isi kolom pencarian dengan `"><center><h1>HTML Injection</h1><br><marquee><img src="https://media.tenor.com/vQlXY2a9WngAAAAj/goma-cat.gif"></marquee></center>`  atau dengan mengubah isi url
- Contoh `https://demosid.opendesa.id/index.php/?cari="><center><h1>HTML Injection</h1><br><marquee><img src="https://media.tenor.com/vQlXY2a9WngAAAAj/goma-cat.gif"></marquee></center>`
3. Lalu klik cari, maka akan tampil code html yg tadi dimasukan

### Tangkapan layar dan log error

![RekamLayar-2023-02-05_14 33 24](https://user-images.githubusercontent.com/32443765/216807386-aab3cecc-83c2-4633-b081-073b5d1cde68.gif)

### Rilis Versi OpenSID

Rilis Umum

### Versi OpenSID

v23.02

### Tema Yang Digunakan

Natra v22.06

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/1979
