### ISSUE TITLE
Selalu tampil Pemeriksaan Database sehabis Upgrade

### ISSUE THREAD

**Issue by topanzhr** [OpenSID/OpenSID#6384]
**### Selalu tampil Pemeriksaan Database setiap kali Upgrade versi terbaru**

**Pemeriksaan Database**
Sebuah Kesalahan Basis Data Telah Terjadi
<p>1406</p><p>Data too long for column 'ipAddress' at row 1</p>

Info!
Sepertinya database anda tidak lengkap, yang mungkin disebabkan proses migrasi yang tidak sempurna.

Pada halaman ini, didaftarkan masalah database yang terdeksi.

**Daftar Masalah**
**Masalah ini belum diketahui sebabnya**. Harap laporkan kepada OpenDesa untuk dibantu lebih lanjut. Harap periksa berkas logs dan laporkan juga isinya. Sementara bisa masuk kembali.

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki, bisa cek https://github.com/OpenSID/OpenSID/issues/5652
