### ISSUE TITLE
Permintaan fitur: adanya TTE di layanansurat_cetaksurat by admin/signer

### ISSUE THREAD

**Issue by hirdaputri** [OpenSID/OpenSID#6386]
### Apa kekurangan yg ingin diatasi?

Jika tidak ada fitur tersebut maka banyak surat yg masih tidak bisa menggunakan TTE

### Jelaskan solusi yg diinginkan

Mohon di adakan pengajuan TTE by admin atau signer, karena tidak semua surat bisa dikeluarkan hanya dengan layanan mandiri, agar lebih mudah menggunakan fitur dan fungsional TTE sebenarnya.

### Apakah ada alternatif lain

Akses Cetak TTE bukan hanya via layanan mandiri

### Untuk versi OpenSID mana

Versi 22.07Aplikasi OpenSID, dikembangkan oleh Komunitas OpenSID.

### Informasi tambahan

TOLONG segera di tambah fitur ini karena saya sebagai operator desa OpenSID merasa perlunya fitur ini (Pengajuan TTE by Signer/Admin )untuk menjalankan perihal surat menyurat lebih efisien dan fungsional, karena jika pengajuan TTE by layanan mandiri (warga) ada beberapa surat yang tidak membutuhkan detail informasi warga seperti surat pengumuman, SK organisasi, dan lain sebagainya di pemerintahan desa.

**Comment by andifahruddinakas** [comment]
Sudah diterapkan diversi terbaru melalu surat TinyMCE
