### ISSUE TITLE
Pendaftaran Kerjasama ( Halaman ini tidak ada yang perlu diubah karena hanya membaca data dari layanan)

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#6387]
Perlu di check apakah untuk menampilkan data kerja sama bisa sesuai kode desa & config_id , dan pengiriman pedaftaran kerja sama apakah perlu di sesuaikan dengan config_id

**Comment by andifahruddinakas** [comment]
Sesuai hasil rapat, tidak ada kaitannya dengan tabel sehingga tidak perlu di ubah.
