### ISSUE TITLE
Panduan sinkronisasi OpenDK

### ISSUE THREAD

**Issue by yogiperdana** [OpenSID/OpenSID#6388]

**Comment by yogiperdana** [comment]
![image](https://user-images.githubusercontent.com/14155050/218629701-26b8d92d-c6f3-46fd-9ace-5f0301f85155.png)

**Comment by yogiperdana** [comment]
![image](https://user-images.githubusercontent.com/14155050/218634068-1d07158f-e322-4ecc-a7a1-18f807f6d0dc.png)

**Comment by yogiperdana** [comment]
![image](https://user-images.githubusercontent.com/14155050/218634362-5c4cd2f6-40eb-4e9b-b59e-3ca8cf5d5e49.png)

**Comment by yogiperdana** [comment]
![image](https://user-images.githubusercontent.com/14155050/218634532-392de9bf-d217-41d6-abf9-28b53d62e3e3.png)

**Comment by yogiperdana** [comment]
![image](https://user-images.githubusercontent.com/14155050/218635634-c72530d8-4a16-424d-bc7f-69e4fbc3035a.png)

**Comment by yogiperdana** [comment]
Tolong dicek mas @scqolbu24 

https://panduan.opendesa.id/id/opensid/halaman-administrasi/opendk/sinkronisasi

**Comment by scqolbu24** [comment]
mas @yogiperdana ini panduan untuk OpenDK atau OpenSID? kalau dilihat dan dibaca OpenDK namun untuk urlnya OpenSID

![panduan opendk1](https://user-images.githubusercontent.com/68048807/218985390-c669cc87-be96-4c00-82dd-7f91618253da.png)

**Comment by yogiperdana** [comment]
Untuk opensid mas. Di opensid ada modu OpenDK @scqolbu24

**Comment by yogiperdana** [comment]
Mohon direview kembali mas @scqolbu24

**Comment by scqolbu24** [comment]
Mas @yogiperdana  cara ini https://panduan.opendesa.id/id/opensid/halaman-administrasi/opendk/sinkronisasi#menangkap-data-dari-opensid dilakukan di OpenDK ?

**Comment by yogiperdana** [comment]
> Mas @yogiperdana cara ini https://panduan.opendesa.id/id/opensid/halaman-administrasi/opendk/sinkronisasi#menangkap-data-dari-opensid dilakukan di OpenDK ?

Lebih tepatnya dilakukan di terminal server sebenarnya mas. Ada saran gimana mau buatnya

**Comment by scqolbu24** [comment]
> > Mas @yogiperdana cara ini https://panduan.opendesa.id/id/opensid/halaman-administrasi/opendk/sinkronisasi#menangkap-data-dari-opensid dilakukan di OpenDK ?
> 
> Lebih tepatnya dilakukan di terminal server sebenarnya mas. Ada saran gimana mau buatnya

kalau di terminal server OpenDK sebaiknya panduannya diletakan di OpenDK, karena tentunya yang mengelola server OpenDK adalah orang kecamatan

**Comment by yogiperdana** [comment]
Bisa review kembali mas @scqolbu24

**Comment by scqolbu24** [comment]
Pada Panduan Sinkronisasi sudah dikerjakan melalui panduan berikut:
https://panduan.opendesa.id/opendk/halaman-administrasi/pengguna#membuat-grup-pengguna-admin-desa-di-OpenDK
https://panduan.opendesa.id/id/opensid/halaman-administrasi/opendk/sinkronisasi
https://panduan.opendesa.id/id/opendk/lainnya#sinkronisasi
