### ISSUE TITLE
Tambahan Data Kelas Sosial

### ISSUE THREAD

**Issue by bhien76** [OpenSID/OpenSID#639]
Saya usul, supaya pada form ubah data KK, bukan hanya berisi Peserta Program Bantuan, tapi ditambahkan dengan data Kelas Sosial. dan rekap kelas sosial bisa ditampilkan di data desa
![tambahan form ks](https://user-images.githubusercontent.com/28255642/30918302-bb5aa618-a3d0-11e7-9d6f-170cbb03e424.jpg)
![kelas sosial 2](https://user-images.githubusercontent.com/28255642/30918356-e617717e-a3d0-11e7-9645-29934eccb2f6.jpg)

**Comment by eddieridwan** [comment]
@bhien76: harap jelaskan:

1. ketentuan pemberian klasifikasi _kelas sosial_ pada keluarga. Apakah ada aturannya (Permen atau lain)?
2. bagaimana caranya perangkat desa memberikan klasifikasi ini pada suatu keluarga?
3. diubah sekali berapa? Apakah ada masa berlaku? Apakah ada dokumentasinya (surat atau lain)?
4. apa kaitan klasifikasi _kelas sosial_ dengan program bantuan seperti _raskin_?

**Comment by eddieridwan** [comment]
Di tabel <em>kelas_sosial</em> saat ini klasifikasi _kelas sosial_ saat ini adalah:

'1', 'Tidak Miskin'
'2', 'Sedang'
'3', 'Miskin'
'4', 'Sangat Miskin'

Ini berbeda dengan klasifikasi di tampilan yang berikan @bhien76 .

**Comment by eddieridwan** [comment]
Klasifikasi yang diberikan @bhien76 sepertinya adalah tingkatan _Keluarga Sejahtera_ dari BKKBN (http://aplikasi.bkkbn.go.id/mdk/BatasanMDK.aspx, http://verlynelson31.blogspot.com/2013/11/pengertian-tujuan-dan-tingkatan.html).

Kalau itu yang dibutuhkan, mungkin lebih baik disebut sebagai _Keluarga Sejahtera_ bukan _Kelas Sosial_?

**Comment by eddieridwan** [comment]
Dari tampilan layar dari @bhien76, sepertinya sudah diterapkan di OpenSID anda. Jika memang demikian, silakan lampirkan scriptnya.

**Comment by bhien76** [comment]
1. Ketentuan pemberian Kelas Sosial berdasarkan pada Tingkatan Keluarga Sejahtera yang bersumber dari BKKBN. 
2. Sumber data yang diinput berasal dari data Sub PPKBD di tingkat desa
3. data diubah setahun sekali 
4. berdasarkan data kelas sosial, sebagai salah satu acuan penentuan penerima raskin.
saja bang @eddieridwan, selama ini saya tidak tau kalau sudah ada reff kelas sosial ygt berisi tidak miskin, sedang, miskin dan sangat miskin. itu sumber datanya berbeda. kalau yg itu sumber datanya hasil pendataan dari analisis kelas sosial

**Comment by eddieridwan** [comment]
@bhien76 apakah masih ingin tetap menggunakan judul 'Kelas Sosial' ? Tidak 'Tingkatan Keluarga Sejahtera'?

**Comment by eddieridwan** [comment]
Statistik _Klasifikasi Sosial_ sekarang bisa ditampilkan di web pada menu statis menggunakan tautan _statistik/kelas_sosial_.

Sudah dicommit ke master.

**Comment by bhien76** [comment]
maaf bang @eddieridwan, saya baru lihat. iya saya setuju untuk diganti tingkatan keluarga sejahtera
