### ISSUE TITLE
Tidak bisa klik show password pada profile 

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#6391]
Saat ini fungsi lihat password tidak bisa di klik. 
1. kodisi tidak bisa klik show jika buka profil di halaman dasbor
2. di halaman lain bisa seperti halaman pengguna
<img width="336" alt="image" src="https://user-images.githubusercontent.com/59082428/216927027-cd3eeaf2-6d65-49ac-9502-7bb77fecf006.png">

Cara replikasinya : 
1. klik icon profile di kanan atas
2. klik profile
3. lalu masukkan password dan klik icon mata

**Comment by FirlianiF** [comment]
Dihalaman apa mas? Mohon cantumkan langkah untuk replikasi nya.

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/1986
