### ISSUE TITLE
OpenKAB - Identitas desa (penyesuaian dengan lebih dari satu OpenSID)

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#6393]
Setelah Reveiw : https://github.com/OpenSID/premium/pull/1946

- [ ] Buat notifikasi bahwa config appkey tidak valid maka perlu berikan tombol reset untuk mengenerate ulang file appkey & appkey yang ada di config. (belum diterapkan, karena penanda untuk menentukan ini)
- [ ] simpan app key ke dalam cache sehingga ketika ada Source OpenSID baru (bisa kondisi install atau migrasi) akan memeriksa  cache jika masih kosong dan tidak terdapat appkey pada cache maka identitas desa akan kosong dan cache akan otomatis tergenerate. 
- [ ] tambahkan pemeriksaan appkey jika tersedia di database config maka ketika simpan akan update sesuai dengan appkey jika tidak ada yang sama maka proses menjadi Insert Identitas Desa sesuai dengan yang di input diform identitas desa

Setelah Review  perlu nantinya di cek kembali setelah pengerjaan issue penduduk: https://github.com/OpenSID/premium/pull/1947/ 
- [ ]  Perlu memastikan ketika mengakses menu wilayah desa berdasarkan config_id 
- [ ] Tambahkan kondisi pemeriksaan data input yang sama dengan config_id bukan hanya dengan nama saja 
- [ ] Perlu Memastikan yang tampil hanya data penduduk saja.
- [ ] Tambah data masih bisa di uji coba dengan 1 config_id  perlu memastikan kembali jika point identitas desa diatas telah diterapkan dan melihat apakah penambahan data sudah bisa berdasarkan config_id masing - masing.

**Comment by andifahruddinakas** [comment]
> Setelah Reveiw : [OpenSID/premium#1946](https://github.com/OpenSID/premium/pull/1946)
> 
> * [ ]  Buat notifikasi bahwa config appkey tidak valid maka perlu berikan tombol reset untuk mengenerate ulang file appkey & appkey yang ada di config. (belum diterapkan, karena penanda untuk menentukan ini)
> * [ ]  simpan app key ke dalam cache sehingga ketika ada Source OpenSID baru (bisa kondisi install atau migrasi) akan memeriksa  cache jika masih kosong dan tidak terdapat appkey pada cache maka identitas desa akan kosong dan cache akan otomatis tergenerate.
> * [ ]  tambahkan pemeriksaan appkey jika tersedia di database config maka ketika simpan akan update sesuai dengan appkey jika tidak ada yang sama maka proses menjadi Insert Identitas Desa sesuai dengan yang di input diform identitas desa
> 
> Setelah Review perlu nantinya di cek kembali setelah pengerjaan issue penduduk: [OpenSID/premium#1947](https://github.com/OpenSID/premium/pull/1947)
> 
> * [ ]   Perlu memastikan ketika mengakses menu wilayah desa berdasarkan config_id
> * [ ]  Tambahkan kondisi pemeriksaan data input yang sama dengan config_id bukan hanya dengan nama saja
> * [ ]  Perlu Memastikan yang tampil hanya data penduduk saja.
> * [ ]  Tambah data masih bisa di uji coba dengan 1 config_id  perlu memastikan kembali jika point identitas desa diatas telah diterapkan dan melihat apakah penambahan data sudah bisa berdasarkan config_id masing - masing.

app_key tidak disimpan di folder cache dan tdk menggunakan cache, app_key disimpan di folder desa.

file appkey di folder desa yg jadi patokan, bukan yg ada di database (tdk bisa menggunakan 2 patokan krn akan rancuh).

**Comment by andifahruddinakas** [comment]
Tambahan : 
- [ ] Hanya bisa digunakan pada kecamatan, kota/kabupaten, provinsi yang sama.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/2052
