### ISSUE TITLE
Buku Tamu - Tampilan depan disesuaikan dengan perubahan database gabungan

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#6395]
- [ ]  Setiap pemanggilan query perlu ditambahkan where(‘config_id’,$config_id)
- [ ]  Setiap kirim data sesuaikan berdasarkan config_id 

Perlu di uji : 

- [ ]  Tambah data sesuai dengan data perdesa
- [ ]  Data pendukung tampil sesuai dengan data perdesa

**Comment by andifahruddinakas** [comment]
Mas @vickyrolanda, @apidong, untuk issue ini akan selesai jika bagian admin (model) untuk buku tamu sudah disesuaikan. Bisa di cek kembali jika ke 4 issue buku tamu bagian admin sudah digabungkan, jika ada yang mau disesuaikan.

**Comment by andifahruddinakas** [comment]
Sudah sesuai
