### ISSUE TITLE
Pengecualian embed google map dari XSS Filtering

### ISSUE THREAD

**Issue by bhien76** [OpenSID/OpenSID#640]
Bang @Eddie Ridwan, kalau bisa XSS Filteringnya dikecualikan embed google map pada artikel. Karena embed google map banyak sekali manfaatnya buat desa yang ingin menampilkan data sebaran penerima bantuan, titik pembangunan, titik sentra kerajinan, dll. ini juga bermanfaat bagi pengawasan Pemda yang ingin mengetahui titik2 yang saya sebutkan tadi
![embed](https://user-images.githubusercontent.com/28255642/30918854-58327a64-a3d2-11e7-8cca-0ed8c3ef507c.jpg)

**Comment by afa28** [comment]
Apakah ini masih bermasalah / masih diperlukan??? Kalau tdk, silahkan di close.

**Comment by afa28** [comment]
Sudah di `master`.

Silahkan atur `$config['user_admin'] = 1;`
