### ISSUE TITLE
Tampilan Depan - Layanan Mandiri

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#6400]
Layanan mandiri pada halaman depan mungkin akan terbagi lagi menjadi beberapa issue.

- [Mandiri Login](https://github.com/OpenSID/OpenSID/wiki/Mandiri-Login)
- [Mandiri Daftar](https://github.com/OpenSID/OpenSID/wiki/Pendaftaran-Layanan-Mandiri-Online#proses-pendaftaran-akun-layanan-mandiri)
- [Mandiri Lupa PIN](https://github.com/OpenSID/OpenSID/wiki/Mandiri-Lupa-PIN)
- [Mandiri Beranda](https://github.com/OpenSID/OpenSID/wiki/Mandiri-Beranda)
- [Mandiri Profil](https://github.com/OpenSID/OpenSID/wiki/Mandiri-Profil)
- [Mandiri Surat](https://github.com/OpenSID/OpenSID/wiki/Mandiri-Surat)
- [Mandiri Pesan](https://github.com/OpenSID/OpenSID/wiki/Mandiri-Pesan)
- [Mandiri Lapak](https://github.com/OpenSID/OpenSID/wiki/Mandiri-Lapak)
- [Mandiri Bantuan](https://github.com/OpenSID/OpenSID/wiki/Mandiri-Bantuan)
- [Mandiri Kahadiran](https://github.com/OpenSID/OpenSID/wiki/Mandiri-Kahadiran)
- [Mandiri Pendapat](https://github.com/OpenSID/OpenSID/wiki/Mandiri-Pendapat)
- [Mandiri Ganti PIN](https://github.com/OpenSID/OpenSID/wiki/Mandiri-Ganti-PIN)
- [Mandiri Verifikasi](https://github.com/OpenSID/OpenSID/wiki/Mandiri-Verifikasi)

Issue dapat dibuat:
- [x] #6504
- [x] #6505
- [x] #6507

**Comment by yogiperdana** [comment]
> Layanan mandiri pada halaman depan mungkin akan terbagi lagi menjadi beberapa issue.

Cakupannya apa aja mas kalau sampai terbagi beberapa issue

**Comment by andifahruddinakas** [comment]
Sudah dipecah jadi beberapa issue
