### ISSUE TITLE
Sediakan Filter Aktif dan Tidak Aktif di menu Pengguna

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#6406]
### Jelaskan error yg dialami

saat ini secara default yang tampil adalah seluruh pengguna, yang sudah digembok maupun yang masih aktif.

### Cara untuk mereplikasi errornya

masuk menu Pengaturan -> Pengguna

### Hasil yg diharapkan

1. Buat Default Aktif dan sediakan filter aktif atau tida aktif (seperti menu Pemerintah Desa)
2. Buat default halaman adalah 10 data. karena saat ini hanya 5 dan tentu jumlah aparatur deda lebih dari itu. (Begitu juga dengan Menu Pendaftaran Layanan Mandiri saat ini default masih 5 baris per halaman)

### Tangkapan layar dan log error

cek di replikasi.

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Rilis Mendatang

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/2044
