### ISSUE TITLE
Tampilan error menggunakan elemen input-grup berantakan

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#6407]
Buat tampilan input grup dengan add-on berada dikanan element input (karena kalau add-on disebelah kiri input tidak bermasalah) dengan menggunakan dengan validasi misalnya required. Contoh : 
```
<div class="form-group">
    <label for="tanggallahir">Tanggal Lahir</label>
    <div class="input-group input-group-sm date">

        <input class="form-control input-sm pull-right required" id="tgl_lahir" name="tanggallahir"
            type="text" value="07-06-1995" onchange="myFunction()">
        <div class="input-group-addon">
            <i class="fa fa-calendar"></i>
        </div>
    </div>
</div>
```

Dan lakukan aksi simpan dengan mengosongkan isian tsb. Maka hasilnya akan berantakan : 
![image](https://user-images.githubusercontent.com/57283157/217450514-f4a600f8-c198-4002-a4d8-6cfa00c56286.png)

Atau bisa dilakukan pengecekan pada saat ubah password pada profil. Ini berkaitan dengan PR https://github.com/OpenSID/premium/pull/1986

![image](https://user-images.githubusercontent.com/57283157/217450693-96eef13d-9302-49c8-9ea9-060d9004c64d.png)

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/2007
