### ISSUE TITLE
Bug/error: Modul stunting tidak dapat menginput tinggi badan jika menggunakan tanda koma.

### ISSUE THREAD

**Issue by rockymakasar** [OpenSID/OpenSID#6417]
### Jelaskan error yg dialami

Pada modul stunting tidak dapat menginput tinggi badan jika menggunakan tanda koma

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

Bisa menggunakan tanda koma pada tinggi badan di form pemantauan bulanan 0-2 Tahun

### Tangkapan layar dan log error

![bfed932b-1206-4ee3-9ec2-ac0356daf45b](https://user-images.githubusercontent.com/94730877/218362682-42e6db61-d3a8-4ede-8b9d-1315305368c7.jpg)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v21.03-premium

### Informasi tambahan

-

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/2011
