### ISSUE TITLE
Bug/error: Tidak bisa simpan identitas desa jika kolom operator belum tersedia.

### ISSUE THREAD

**Issue by apidong** [OpenSID/OpenSID#6419]
### Jelaskan error yg dialami

eror tidak bisa ubah identitas desa

### Cara untuk mereplikasi errornya

1. install awal opensid
2. ubah identitas desa 
3. terjadi error

### Hasil yg diharapkan

tidak ada error

### Tangkapan layar dan log error

ERROR - 2023-02-14 18:24:22 --> Severity: error --> Exception: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'nomor_operator' in 'field list' (SQL: insert into `config` (`logo`, `kantor_desa`, `nama_desa`, `kode_desa`, `kode_pos`, `alamat_kantor`, `email_desa`, `telepon`, `website`, `nama_kecamatan`, `kode_kecamatan`, `nama_kepala_camat`, `nip_kepala_camat`, `nama_kabupaten`, `kode_kabupaten`, `nama_propinsi`, `kode_propinsi`, `nomor_operator`, `created_by`, `updated_by`, `updated_at`, `created_at`) values (, , Darul Ikhsan, 1101012015, 55465, fgsdfgfgdfd, , ?, , Bakongan, 110101, fgsfdgsf fg fd, , Aceh Selatan, 1101, Aceh, 11, ?, 1, 1, 2023-02-14 18:24:22, 2023-02-14 18:24:22))

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

-

### Tema Yang Digunakan

-

### Informasi tambahan

-

**Comment by eddieridwan** [comment]
Issue ini dibuka karena laporan masih terjadi dari @HerryWanda . Info lebih lanjut akan disediakan oleh @HerryWanda . Evaluasi awal dari @apidong terlihat ada error CORS.

@apidong harap anda coba dengan solusi balikkan ke pemanggilan Layanan dari server, supaya tidak terbentur CORS. Jika terbukti masih ada yg servernya tidak dapat mengakses Layanan, bisa sediakan kedua cara: dari server dan dari client (jika satu gagal coba yg satu lagi). Tapi pastikan bisa atasi masalah CORS dulu **tanpa membuka celah keamanan**.

**Comment by eddieridwan** [comment]
@vickyrolanda dalam melakukan review PR solusi issue ini, harap secara teliti memperhatikan faktor keamanan. CORS itu adalah fitur keamanan, supaya browser tidak dibajak oleh pihak ketiga. Solusi yg mengebiri atau mengabaikan CORS secara umum membuka celah keamanan. Yaitu jika tetap melakukan pemanggilan dari client, maka perlu mengikuti kaidah pemanggilan yg aman.

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2219
