### ISSUE TITLE
Statistik Kepemilikan KTP

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#642]
Prrlu dibuatkan statistik kepemilikan KTP bagi masyarakat spy bisa di control dari yg usia wajib KTP yg punya atau belum atau dlm proses

**Comment by eddieridwan** [comment]
#710 sudah dicommit ke master

**Comment by MUHAMMADRANGSEL** [comment]
Apa Link nya tuk kita tampilkan statistik kepemilikan KTP

**Comment by eddieridwan** [comment]
Heheh.. tidak teliti membaca. Statistik belum dibuat.

**Comment by eddieridwan** [comment]
@MUHAMMADRANGSEL :  Untuk membuat laporan statistik kepemilikan KTP, kami perlu jawaban untuk pertanyaan berikut:

Apa arti masing2 nilai kolom KTP EL

1. BELUM (belum apa? - belum wajib, belum diproses, belum diterima??)
2. KTP-EL (apa artinya ini? - sedang diproses, sudah diterima??)

Apa kaitan masing2 nilai kolom STATUS REKAM dengan kolom KTP EL

1. BELUM WAJIB (KTP EL harus 1?)
2. BELUM REKAM (KTP EL harus 1 atau boleh 2?)
3. SUDAH REKAM (KTP EL harus 1 atau 2?)
4. CARD PRINTED (KTP EL harus 1 atau 2?)
5. PRINT_READY_RECORD (KTP EL harus 1 atau 2?)
6. CARD SHIPPED (KTP EL harus 1 atau 2?)
7. SENT FOR CARD PRINTING (KTP EL harus 1 atau 2?)

**Comment by eddieridwan** [comment]
Dari Si Aditya: 

Proses Pembuatan KTP elektronik itu di bagi menjadi 5 tahapan :
1.      PROSES PEREKAMAN
   Data Penduduk yang telah memiliki NIK dengan minimal usia 16 Tahun akan di lakukan perekaman KTP EL dengan syarat NIK tersebut masih UNREGISTERED dengan kata lain NIK masih ke adaan kosong dari data perekaman, Setelah melakukan perekaman maka status dari NIK berubah menjadi BIO_CAPTURED yaitu status telah di rekam yang akan berubah menjadi PROCESSING dan berlanjut ke tahapan selanjutnya.

2.      PROSES PENGIRIMAN DATA                    
  Dalam tahap ini data yang telah di rekam akan melalui beberapa tahap pengiriman, SENT_FOR_ENROLLMENT (SFE) yaitu data perekaman di kirim ke data center pusat (data kemendagri) tetapi belum tentu data tersebut sampai karna proses pengiriman ini tergantung dari kelancaran jalur server daerah ke server pusat yang menggunakan jalur private bukan public seperti halnya berinternetan tetapi pengiriman data ini menggunakan private jalur yang membuat hambatan lama tetapi keamanan data terjamin, bisa di bayangkan seluruh server daerah se indonesia menggunakan jalur ini untuk mengirimkan data ke server pusat dan begitu padatnya. Status selanjutnya yaitu RECEIVED_AT_CENTRAL data yang telah di kirim sudah sampai di pusat tetapi akan di proses ke tahapan selanjutnya.

3.      PROSES PENGECEKAN DATA
      Setelah sampai di data pusat maka proses selanjutnya akan di bagi menjadi beberapa status data antara lain ENROLL_FAILURE_AT_CENTRAL yaitu hasil identifikasi di pusat tidak lengkap atau tidak terbaca proses ini bisa saja dari data yang belum sepenuhnya sampai ke pusat atau ada kesalah ketika perekaman di daerah, SEARCH_FAILURE_AT_CENTRAL adalah pencarian data gagal di data center , ENROLL_FAILURE_AT_CENTRAL adalah hasil verifikasi biometrik di daerah teridentifikasi tidak lengkap atau tidak terbaca di karnakan kesalahan kode area perkaman di daerah,
PACKET_ENTRY artinya paket data di kirim ulang , setelah melakukan beberapa tahap di atas dan data tersebut tidak mengalami hambatan pada saat melakukan proses di atas maka status akan berubah menjadi SENT_FOR_DEDUP yang artinya data dikirim untuk melakukan penunggalan data dan berlanjut ke tahap selanjutnya.

4.      PROSES PENUNGGALAN DATA
       Dalam proses penunggala data ada tiga tahap yang harus di lalui oleh data antara lain, DUPLICATE_RECORD yaitu data termasuk data ganda dalam tahapan ini data di seleksi dan di samakan secara keseluruhan dengan data yang ada di data center dengan melakukan proses one to one verifikasi bila data teridentifikasi ganda maka status akan berubah menjadi duplicate_record maka data awal lah yang akan tetap menjadi data tunggal, ADJUDICATE_RECORD yaitu kondisi data hasil perekaman sedang di verifikasi karena ada kemiripan dengan data yang lain, REQUEST_VALIDATION status ini memerlukan perifikasi dari daerah di karnakan ada kesimpangan data misalkan jenis kelamin laki-laki tetapi foto yang ada dalam data perekaman adalah foto perempuan.
Setelah melakukan tahap penunggalan jika data perkaman tidak terjaring oleh 3 status di atas maka data tersebut akan masuk ke tahapan selanjutnya.

5.      PROSES PERCETAKAN KTP EL
       Setelah melewati beberapa tahapan yang begitu panjang dan waktu yang begitu panjang juga maka data yang sudah masuk ke tahapan ini adalah data yang sudah siap untuk di cetak dengan status PRINT_READY_RECORD di pusat yang nantinya data tersebut akan di kirimkan ke server daerah untuk di lakukan pencetakan KTP elektronik SENT_FOR_CARD_PRINTING status data di kirim untuk dilakukan pencetakan KTP elektronik di daerah, CARD_SHIPPED yaitu data sudah dikirim ke daerah, CARD_PRINTED status data sudah melakukan percetakan KTP elektronik, CARD_ISSUED yaitu data sudah di cetak ktp elektronik dan sudah melakukan aktivasi.

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.

**Comment by eddieridwan** [comment]
Bisa ditambahkan ke menu statis dengan link 'statistik/18'.

**Comment by eddieridwan** [comment]
Dari Deni Efendi: 

stat rkm itu di skip aja... status itu di skip aja.... 
wajib ktp itu menandakan dia masuk kategori sudah wajib punya ktp... ktp-el itu menandakan dia sudah punya ktp atau belum...

**Comment by hirudi** [comment]
Hemat sy status2 tsb tdk perlu dimasukkan, cukup wajib ktp dan ktp-el saja
