### ISSUE TITLE
Bug/error: pesan : belum ada penanda tangan, silahkan tentukan a.n pada modul pemerintah desa

### ISSUE THREAD

**Issue by normansuherman** [OpenSID/OpenSID#6420]
### Jelaskan error yg dialami

tidak bisa mencetak surat karena ada pesan error belum ada penanda tangan, silahkan tentukan a.n pada modul pemerintah desa, padahal baru clean install opensid 23.02.
-import penduduk
-tambah aparatur pemerintah desa

### Cara untuk mereplikasi errornya

tidak ada

### Hasil yg diharapkan

ketika clean install versi terbaru, bisa cetak surat setelah import penduduk dan memasukkan apartur pemerintah desa 

### Tangkapan layar dan log error

<img width="941" alt="Screenshot 2023-02-15 034004" src="https://user-images.githubusercontent.com/122291997/218840230-219defbf-3666-45db-a0fa-511a50b85272.png">

tidak ada log apapun yang didapatkan

### Rilis Versi OpenSID

Rilis Umum

### Versi OpenSID

23.02

**Comment by balongbesuk** [comment]
sudah d tentukan a.n d menu pemerintahan?

**Comment by normansuherman** [comment]
sudah, dan tetap muncul pesan sama "tidak ditemukan penanda tangan ..... "
ini saya coba clean install 23.02 , dengan database default, kemudian saya lakukan import penduduk sedikit saja,, setelah itu saya lakukan isi aparatur pemerintahan desa di menu pemerintahan untuk a.n..

hasilnya tetap sama 

saya coba juga clean install di versi 23.01 dan tidak ada masalah, dan berjalan normal , kemudian saya coba lakukan update ke 23.02 hasilnya muncul pesan , tidak ditemukan penanda tangan.

**Comment by normansuherman** [comment]
solved ..saya coba roll back ke 12.12.1 menimpa donjo-app terlebih dahulu kemudian roll back databse via panel admin pengaturan - database
