### ISSUE TITLE
semua komponen input-group-addon menjadi berantakan

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#6422]
![image](https://user-images.githubusercontent.com/59082428/218947107-ba8f9e22-fd7f-4ff9-97cc-5d8cdad5299f.png)

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melalui pr https://github.com/OpenSID/premium/pull/2025

**Comment by andifahruddinakas** [comment]
cek komentar https://github.com/OpenSID/premium/pull/2025#issuecomment-1441250519

**Comment by andifahruddinakas** [comment]
https://user-images.githubusercontent.com/95505631/220896897-8b05df4b-c02e-40c5-bd58-780813014ffe.png

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2078
