### ISSUE TITLE
Panduan modul OpenDK

### ISSUE THREAD

**Issue by yogiperdana** [OpenSID/OpenSID#6423]

**Comment by yogiperdana** [comment]
Mohon direview mas @scqolbu24 

https://panduan.opendesa.id/opensid/halaman-administrasi/opendk

**Comment by scqolbu24** [comment]
Mas @yogi berikut dari hasil review:
![panduan opendk2](https://user-images.githubusercontent.com/68048807/218988730-2004de60-63bd-4a6f-b9bd-75c2db5c66bc.png)
![panduan opendk3](https://user-images.githubusercontent.com/68048807/218988765-22f59833-7c64-429b-b01f-10eda1bd4a39.png)

untuk Penjelasan Detailnya bisa sesuai pada sub menu di OpenDK
```
#Pesan
#Sinkronisasi 
```
![panduan opendk4](https://user-images.githubusercontent.com/68048807/218988796-7e84a163-f5ba-4522-9a3a-1cc8c94a0346.png)

**Comment by yogiperdana** [comment]
Berdasarkan hasil diskusi struktur panduan opensid akan diperbarui dan panduan ini dianggap telah terwakili pada halaman administrasi
