### ISSUE TITLE
Atasin masalah error ketika key OpenDK tidak tersedia

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#6431]
![image](https://user-images.githubusercontent.com/59082428/219543245-75150a01-9ef2-4432-9444-1f6345e34688.png)

 **log error "message":"Unauthenticated."**

solusi sementara dari pengguna : 
Hapus settingan buat key d opendk pak. Nanti kalau mau kirim data ke kecamatan buat lagi. Cara masuknya langsung aja ke https://namadomain.desa.id/penduduk ini hanya contoh

**Comment by FirlianiF** [comment]
mas @vickyrolanda minta tolong ditambahkan cara untuk mereplikasi bug tsb dan hasil yang diharapkan seperti apa mas, terimakasih.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/2062
