### ISSUE TITLE
Bug/error: Nomor surat tidak kembali ke nomor 1 ketika pergantian tahun

### ISSUE THREAD

**Issue by yogiperdana** [OpenSID/OpenSID#6432]
### Jelaskan error yg dialami

Nomor surat tidak kembali ke nomor 1 ketika pergantian tahun

### Cara untuk mereplikasi errornya

Buat surat Domisili Usaha Non Warga perhatikan nomor terakhir dibuat pada 2022 dan ketika buat baru nomor dilanjutkan berdasarkan nomor terakhir

### Hasil yg diharapkan

Nomor kembali menjadi 1 ketika pergantian tahun

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v23.02

### Informasi tambahan

Database sudah dikirim ke mas vicky via telegram

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/2059
