### ISSUE TITLE
Bug/error: Backup database berisi baris yg menyebabkan restore error

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#6433]
### Jelaskan error yg dialami

Backup database menghasilkan file sql dengan baris yg menyebabkan proses restore error.

<img width="1311" alt="image" src="https://user-images.githubusercontent.com/249563/219603381-7992d74f-6ff4-4d5b-87b7-1fd5a5d52789.png">

### Cara untuk mereplikasi errornya

Di Admin:

1. Buka Pengaturan > Database
2. Jalankan Backup database
3. Periksa isi file sql yg dihasilkan

### Hasil yg diharapkan

Baris penyebab error itu tidak di-output ke hasil backup.

### Tangkapan layar dan log error

<img width="1311" alt="image" src="https://user-images.githubusercontent.com/249563/219604059-47d5423b-ba83-463a-88be-b155e9e4c1b0.png">

### Rilis Versi OpenSID

Rilis Umum

### Versi OpenSID

23.02

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2081
