### ISSUE TITLE
Bug/error: Update dari 21.10 ke 23.02 error

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#6434]
### Jelaskan error yg dialami

Update dari versi 21.10 ke 23.02 gagal. Dan terlihat karena proses migrasi tidak dijalankan secara otomatis. Migrasi manual juga tidak dapat dijalankan, karena aplikasi tidak bisa masuk sama sekali. 

### Cara untuk mereplikasi errornya

1. Pasang database dari v21.10
2. Install OpenSID 23.02
3. Buka OpenSID
4. Perhatikan error 500
5. Di log perhatikan berbagai error database tidak ada kolom yg diperlukan

### Hasil yg diharapkan

Update berhasil tanpa error, di mana migrasi berhasil dijalankan secara otomatis

### Tangkapan layar dan log error

<img width="890" alt="image" src="https://user-images.githubusercontent.com/249563/219606946-d4438e46-6508-4d5f-b1af-09bd56048ca7.png">

### Rilis Versi OpenSID

Rilis Umum

### Versi OpenSID

23.02

### Tema Yang Digunakan

sembarang

### Informasi tambahan

Mengapa di 23.02, migrasi tidak lagi selalu dijalankan, termasuk pada waktu update? 
Jika setting_model.apply_setting() diubah supaya pemanggilan cek_migrasi() selalu menjalankan migrasi, maka proses update akan jalan normal.

<img width="1311" alt="image" src="https://user-images.githubusercontent.com/249563/219608933-49a778ab-f694-4154-ae37-a337fb837d4f.png">

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2080
