### ISSUE TITLE
Bug/error: Defaul Pilih Jenis Presentasi Pembagunan  pada Dokumentasi Pembagunan Tidak Sesuai

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#6435]
### Jelaskan error yg dialami

Saat menambahkan data dokumentasi pembagunan, form awal yang tampil tidak sesuai.
Tampil: 
![image](https://user-images.githubusercontent.com/57283157/219854769-df288afa-474b-4684-a82a-8d1300511830.png)

Harusnya:
![image](https://user-images.githubusercontent.com/57283157/219854783-2e348502-a79a-4995-8a3d-651d42ab8ef4.png)

### Cara untuk mereplikasi errornya

Buat dokumentasi pembangunan di modul pembangunan.

### Hasil yg diharapkan

Form yang tampil awal sesuai.

### Tangkapan layar dan log error

.

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

< v23.02-premium

### Tema Yang Digunakan

bawaan

### Informasi tambahan

.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/2057
