### ISSUE TITLE
Tambah penduduk lahir melalui modul keluarga terjadi error

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#6437]
### Jelaskan error yg dialami

Terjadi error simpan penduduk lahir melalui modul keluarga.

### Cara untuk mereplikasi errornya

1. Pergi ke modul keluarga.
![IMG_20230219_180915_364](https://user-images.githubusercontent.com/57283157/219941696-7b361744-4ce1-4478-8d78-73dedc6a6080.jpg)

2. Tambahkan data penduduk lahir.
![IMG_20230219_181212_568](https://user-images.githubusercontent.com/57283157/219941712-350ef177-0729-4283-bd11-a71eec272bf1.jpg)

3. Terjadi gagal simpan

### Hasil yg diharapkan

Tersimpan sesuai yg di harapkan.

### Tangkapan layar dan log error

```
Log Error :
Query error: Unknown column 'kk_level_lama' in 'field list' - Invalid query: INSERT INTO tweb_penduduk (id_kk, kk_level, id_cluster, nik, nama, ktp_el, status_rekam, tag_id_card, tempat_cetak_ktp, tanggal_cetak_ktp, no_kk_sebelumnya, kk_level_lama, sex, agama_id, `stat
s`, akta_lahir, tempatlahir, tanggallahir, waktu_lahir, tempat_dilahirkan, jenis_kelahiran, kelahiran_anak_ke, penolong_kelahiran, berat_lahir, panjang_lahir, pendidikan_kk_id, pendidikan_sedang_id, pekerjaan_id, suku, warganegara_id, dokumen_pasport, tanggal_akhir_paspor, dokumen_kitas, negara_asal, ayah_nik, nama_ayah, ibu_nik, nama_ibu, alamat_sebelumnya, alamat_sekarang, telepon, email, telegram, hubung_warga, status_kawin, golongan_darah_id, cacat_id, sakit_menahun_id, cara_kb_id, hamil, id_asuransi, no_asuransi, bpjs_ketenagakerjaan, bahasa_id, ket, tanggalperkawinan, tanggalperceraian, akta_perkawinan, akta_perceraian, created_by) VALUES ('197', '4', '49', '11111111111111111', 'INTAN RAUZATUL MA\'WA', NULL, NULL, NULL, '', NULL, '', '4', '2', '1', '1', '', 'ACEH UTARA', '2022-01-10', '10:11', '1', '1', '2', '1', NULL, NULL, '1', '1', '1', 'Aceh', '1', '', NULL, NULL, '', '', 'MUSLIADI', '', 'CUT', '', 'MEULWEUK', NULL, NULL, NULL, 'Telegram', '1', '13', '7', '14', NULL, '2', NULL, NULL, '', '0', '', NULL, NULL, '', '', 1)
```

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v23.02-premium

### Tema Yang Digunakan

bawaan

### Informasi tambahan

.

**Comment by FirlianiF** [comment]
mas @vickyrolanda bisa minta tolong di replikasi di tempat mas vicky, karena di saya data berhasil tersimpan meskipun Nomor KK sebelumnya tidak diisi.

**Comment by vickyrolanda** [comment]
1. saya check di tabelnya memang tidak ada kolom " kk_level_lama " namun sy test nambah penduduk baru lahir di berputar tidak terjadi error. 
<img width="617" alt="image" src="https://user-images.githubusercontent.com/59082428/220788067-54de23f1-4c2b-4271-b2b5-902d9c17ddb2.png">
- kalo check di coding memang ada nambah ke kolom kk_level_lama namun tidak terjadi error.

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2079
