### ISSUE TITLE
Bug/error: Terjadi gagal simpan artikel

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#6438]
### Jelaskan error yg dialami

Terjadi gagal simpan artikel dengan error berikut : 
`ERROR - 2023-02-20 09:00:08 --> Severity: error --> Exception: Call to undefined function exif_read_data() /www/wwwroot/desadadapkuning.gresikkab.go.id/donjo-app/core/MY_Log.php(206) : eval()'d code(1) : eval()'d code 417`

Indikasi: extention exif tidak aktif sessuai error (exif_read_data());

### Cara untuk mereplikasi errornya

1. Non Aktifkan extention exif
2. Buat atikel dan simpan
3. Akan terjadi hal tbs.

### Hasil yg diharapkan

Tampilkan informasi extention exif diperlukan, karena saat ini belum ada;

![image](https://user-images.githubusercontent.com/57283157/219997325-13e4efe4-59d3-4b68-bf1d-ba7f917dd290.png)

### Tangkapan layar dan log error

.

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v23.02-premium

### Tema Yang Digunakan

bawaan

### Informasi tambahan

exif ini sama dengan tidy, di apache tidak otomatis diaktifkan, kalau di openlitespeed otomatis aktif

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/2058
