### ISSUE TITLE
[security] Database di web demo terhapus

### ISSUE THREAD

**Issue by fahribaharudin** [OpenSID/OpenSID#644]
http://sid.bangundesa.info/index.php/siteman

**Comment by eddieridwan** [comment]
Database di web demo terhapus. Kemungkinan besar serangan sql injection.

Perlu dilacak titik masuknya serangan. 

Cek dulu isian di modul Web:

1. pengisian komentar. Ini sepertinya aman, karena sudah di-escape dan juga perlu diperiksa dulu oleh admin sebelum ditampilkan
1. pengisian layanan mandiri.

Berikutnya, periksa modul Admin. Serangan di modul ini hanya bisa dilakukan oleh pengguna yang mempunyai login. Dari segi praktis, apabila username/password aman, resiko serangan di modul Admin sebenarnya kecil --- karena tentu pengguna resmi tidak akan merusak database. Walaupun demikian, tetap perlu ditutup lobang keamanan yang ditemukan.

**Comment by afa28** [comment]
Silahkan di reopen issue ini jika masih bermasalah.
