### ISSUE TITLE
Bug/error: Tidak sesuai nya Jumlah Permohonan dan Jumlah Arsip pada Layanan Surat di Akun Administrator dan Akun Kepala Desa

### ISSUE THREAD

**Issue by mah-mudi** [OpenSID/OpenSID#6441]
### Jelaskan error yg dialami

Tidak sesuai nya Jumlah Permohonan dan Jumlah Arsip pada Layanan Surat di Akun Administrator dan Akun Kepala Desa.
Ada Perbedaan Jumlah.

### Cara untuk mereplikasi errornya

Login Administrator (admin by sistem)
1. Pergi Kehalaman Layanan Surat
2. Arsip Layanan

Login Akun Kepala Desa
1. Pergi Kehalaman Layanan Surat
2. Arsip Layanan

### Hasil yg diharapkan

Jumlah Permohonan dan Jumlah Arsip pada Layanan Surat di Akun Administrator dan Akun Kepala Desa **menunjukkan Jumlah yang SAMA**

### Tangkapan layar dan log error

![SURAT1](https://user-images.githubusercontent.com/57661283/220655119-6fb98110-464a-4053-9948-c7b2cde61e15.png)

![SURAT2](https://user-images.githubusercontent.com/57661283/220655167-4016455c-f0c6-487d-a3c7-fc5426e4c3b2.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

22.02-premiumrev02

### Tema Yang Digunakan

silir

**Comment by vickyrolanda** [comment]
ijin pak @mah-mudi saya coba replikasi tidak terjadi di berputar, mungkin mohon bisa kirim backup database ke saya pak agar bisa saya replikasi trigger bugnya karena apa. 

dan juga bisa coba kli perbaiki layana surat pak.

**Comment by mah-mudi** [comment]
@vickyrolanda saya kirim lewat telegram sampeyan ya

**Comment by vickyrolanda** [comment]
> @vickyrolanda saya kirim lewat telegram sampeyan ya

baik terima kasih pak.

**Comment by andifahruddinakas** [comment]
> > @vickyrolanda saya kirim lewat telegram sampeyan ya
> 
> baik terima kasih pak.

mas @vickyrolanda, bisa diteruskan ke telegram saya.

**Comment by vickyrolanda** [comment]
Sudah mas

**Comment by andifahruddinakas** [comment]
Setelah di cek memang ada perbedaan jumlah data dan yang ditampilkan : 
- [ ] Pada user kepala desa bagian data permohonan, jumlahnya ada 15 namun yg ditampilkan adalah 3
<img width="923" alt="image" src="https://user-images.githubusercontent.com/57283157/236099970-010744b0-d1cd-4106-b49c-939867f7cadf.png">

- [ ] Pada user kepala desa bagian data arsip, jumlahnya ada 6 namun yg ditampilkan adalah 8
<img width="910" alt="image" src="https://user-images.githubusercontent.com/57283157/236100167-9daf73c1-c16f-4a30-bf4a-420ffd13d311.png">

Sedangkan untuk kasus dimana data arsip layanan dengan grup administrator umum dengan administrator kades saya kira sudah sesuai. Agar yang ditampilkan hanya peromohonan surat yg perlu konfirmasi kades saja yg ditampilkan, tp perlu di analisis lg kondisi-kondisi termasuk sekdes.

**Comment by andifahruddinakas** [comment]
Bisa gunakan database https://drive.google.com/drive/u/0/folders/1wMTwZIqhqrSaZwz3NkRVmBRUt6XvBWTb

**Comment by pandigresik** [comment]
![image](https://github.com/OpenSID/OpenSID/assets/1853475/2ce72d76-ce7e-4d16-9077-8724dda3d9fa)

Seperti ini ya

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2403
