### ISSUE TITLE
Bug/error: tampilan bar tidak rata dengan Button di Buku tamu

### ISSUE THREAD

**Issue by usmanrahdi** [OpenSID/OpenSID#6443]
### Jelaskan error yg dialami

tampilan tidak rapi atau pada bar rentang tanggal tampak tinggi dari botton lain

### Cara untuk mereplikasi errornya

1. Pergi ke halaman Buku Tamu
2. Klik pada Data Tamu

### Hasil yg diharapkan

lebih rapi

### Tangkapan layar dan log error

![2023-02-23_19h39_43](https://user-images.githubusercontent.com/95505631/220896897-8b05df4b-c02e-40c5-bd58-780813014ffe.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

23.02-premium-rev03

**Comment by andifahruddinakas** [comment]
Duplicate issue https://github.com/OpenSID/OpenSID/issues/6422
