### ISSUE TITLE
Status Penduduk datang bagi penduduk yang pernah menjadi warga desa kemudian pindah

### ISSUE THREAD

**Issue by makhbub** [OpenSID/OpenSID#6444]
### Apa kekurangan yg ingin diatasi?

saat ada penduduk datang yang dulunya pernah menjadi warga desa kemudian pindah dan kembali lagi ke Desa, maka proses yang terjadi di OpenSID tidak menginput data penduduk, tetapi cukup masuk lohg penduduk, pilih data penduduk yang dimaksud kemudian pilih "kembalikan status"

akibat dari proses ini, penduduk tersebut tidak tercatat di laporan bulanan sebagai penduduk datang. padahal seharusnya penduduk tersebut tetap dianggap penduduk datang

### Jelaskan solusi yg diinginkan

ada pilihan "datang kembali" selain pilihan "kembalikan status" untuk log penduduk pindah
dan penduduk tersebut  tercatat sebagai penduduk datang di laporan bulanan maupun administrasi kependudukan

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

23.04-premium

### Informasi tambahan

-

**Comment by yonathanrizky** [comment]
fitur ini sudah tersedia pak, pilihan datang kembali akan muncul di log penduduk jika bulan pindah tidak sama dengan bulan datang kembali

**Comment by makhbub** [comment]
Owh, iya pak, 
Baru tahu ada fitur tersebut
Dengan ini issue saya tutup
