### ISSUE TITLE
Bug/error: Kolom "Pangkat / Golongan" pada Form "Staf Pemerintahan [sebutan_desa]"

### ISSUE THREAD

**Issue by jumaidilfadil** [OpenSID/OpenSID#6447]
### Jelaskan error yg dialami

Ketika mengisi form "Buku Administrasi Umum - Buku Aparat Pemerintah Desa",
pada menu "Buku Administrasi [sebutan_desa] > Administrasi Umum > Buku Aparat Pemerintah [sebutan_desa] > Tambah Aparat Pemerintahan atau Ubah Data" (url: namadomain.com/pengurus/form/[id]),

pada kolom "Pangkat / Golongan", saya isi misalnya: "Penata Tingkat I / III.d".
![FireShot Capture 014 - Sistem Informasi Kelurahan Kejaksaan - Pengurus - Form 14_ - kel-kejaksaan pangkalpinangkota go id](https://user-images.githubusercontent.com/54663301/221348915-c405e50f-f9a9-4c5a-8dfd-0af9222c003e.png)

Ketika saya klik tombol "Simpan", website ter-logout sendiri dan pergi menuju halaman login dengan url "namadomain.com/periksa/login"

Lalu saya lakukan login sebagai admin pada halaman tersebut, dan muncul halaman error seperti berikut:
![FireShot Capture 015 - Periksa Database - Kejaksaan - kel-kejaksaan pangkalpinangkota go id](https://user-images.githubusercontent.com/54663301/221348896-cf235b30-dbd6-476b-9b5c-135d1d000cb9.png)

Data yang simpan, terutama data "Pangkat / Golongan" tidak tersimpan.

### Cara untuk mereplikasi errornya

![FireShot Capture 015 - Periksa Database - Kejaksaan - kel-kejaksaan pangkalpinangkota go id](https://user-images.githubusercontent.com/54663301/221348896-cf235b30-dbd6-476b-9b5c-135d1d000cb9.png)

### Hasil yg diharapkan

Data berhasil tersimpan.

### Tangkapan layar dan log error

![FireShot Capture 015 - Periksa Database - Kejaksaan - kel-kejaksaan pangkalpinangkota go id](https://user-images.githubusercontent.com/54663301/221348896-cf235b30-dbd6-476b-9b5c-135d1d000cb9.png)

### Rilis Versi OpenSID

Rilis Umum

### Versi OpenSID

22.11. Kemungkinan besar semua versi sampai versi saat ini (23.02)

### Tema Yang Digunakan

Batuah (v22.11 s.d. 23.01)

### Informasi tambahan

Setelah saya telusuri, penyebabnya adalah pada code berikut tidak terdapat "maxlength=20":
https://github.com/OpenSID/OpenSID/blob/aa302485cf9fbc2943a80fca822c80797c8d6a4d/donjo-app/views/home/pengurus_form.php#L151
Sedangkan pada database, data tersebut dibatasi 20 karakter.
https://github.com/OpenSID/OpenSID/blob/aa302485cf9fbc2943a80fca822c80797c8d6a4d/donjo-app/models/Database_model.php#L749-L753
![image](https://user-images.githubusercontent.com/54663301/221349905-17745e10-5445-49d2-bfa0-db8fa7c946e4.png)

Sehingga jika saya memasukkan data >20 karakter, maka akan error.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/2077
