### ISSUE TITLE
cek default password pada saat ditampilkan selalu tertulis "radiisi" 

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#6452]
1. Masuk ke halaman pengguna
2. Edit salah satu user 
3. Klik mata untuk melihat password 
4. maka yang tertulis "radiisi" 
<img width="626" alt="image" src="https://user-images.githubusercontent.com/59082428/222059099-c2ed8505-d935-4c8b-a0a9-cd74fa265d19.png">

5. padahal passwordnya bukan itu, dan bisa lihat pada profil pengguna dan lihat password lama , lalu klik tombol mata maka sudah sesuai dengan password pengguna tersebut.

**Comment by apidong** [comment]
@vickyrolanda karena password di database berisi hash, maka tidak bisa ditampilkan lagi. 
solusinya, halaman ubah data dan ganti password sebaikanya di pisah saja.

**Comment by apidong** [comment]
solusinya hilangkan isian password, jika ingin mengubah password bisa langsung di isi saja

**Comment by vickyrolanda** [comment]
> solusinya hilangkan isian password, jika ingin mengubah password bisa langsung di isi saja

ia mas sesuai diskusi di telegram sebaiknya seperti ini, lebih baik password dikosongkan saja jangan ada isian defaultnya.

**Comment by andifahruddinakas** [comment]
Bisa lakukan pencarian global 'radiisi', maka akan menemukan kata tersebut masih digunakan dibagian tertentu. Jika ingin mengubah, sesuaikan jg dibagian backend nya. Karena penambahan kata 'radiisi' mungkin ada tujuan lain.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/2096

**Comment by vickyrolanda** [comment]
> Bisa lakukan pencarian global 'radiisi', maka akan menemukan kata tersebut masih digunakan dibagian tertentu. Jika ingin mengubah, sesuaikan jg dibagian backend nya. Karena penambahan kata 'radiisi' mungkin ada tujuan lain.

ia mas, sedang sy cek ulang apakah berpengaruh dengan ubah password
