### ISSUE TITLE
Perlu penyesuaian panjang karekter id_telegram agar dapat menampung data 10 digit  

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#6456]
```
Query error: Out of range value for column 'id_telegram' at row 1 - Invalid query: UPDATE user SET username = 'KADES', nama = 'H. ABDUR ROSYID', phone = '081231309708', email = 'abdur.rosyid@gresikkab.go.id', id_grup = '6', pamong_id = '36', foto = 'kuser.png', id_telegram = 600967856 WHERE id = '10'
```

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/2092

**Comment by andifahruddinakas** [comment]
Perbaikaan sebelumnya mengabaikan data yg sudaha terlanjur sudah ddi input. Sehingga menyebabkan gagal migrasi.

Solusi :
- sebelum mengubah panjang karakter suatu kolom, cek terlebih dahulu data sebelumnya agar tdk terjadi error.

**Comment by agungsugiarto** [comment]
saya tidak menemukan masalah, setelah mundur ke versi sebelum id_telegram dirubah kemudian melakukan migrasi lagi versi ubahan pada pr https://github.com/OpenSID/premium/pull/2092, bagaimana cara reproduce issuenya mas @andifahruddinakas ?

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2294
