### ISSUE TITLE
Permintaan fitur: Pengaturan grup pengguna dengan tingkatan wilayah (Dusun/RT/RW)

### ISSUE THREAD

**Issue by cepiandiana** [OpenSID/OpenSID#6458]
### Apa kekurangan yg ingin diatasi?

Pendataan Penduduk belum bisa diakses sesuai role user

### Jelaskan solusi yg diinginkan

Adanya Fitur Pendataan Penduduk oleh RT atau Petugas Khusus dari desa, yang mana petugas tersebut diberi akses login oleh admistrator untuk mengerjakan :
1. Melihat data penduduk sesuai akses RT nya
2. Edit data penduduk yang sudah ada, sesuai akses RT masing-masing
3. Tidak Bisa hapus data penduduk, hanya memberi keterangan saja seperti : Meninggal, Pindah dsb
4. Memasukan Potensi lingkungan RT masing-masing seperti, Jumlah MCK, Jumlah Masjid berikut namanya, Sekolah berikut namanya, wisata dsb
5. Mengisi Kuesioner seperti SDGS pada kepala keluarga dengan indikator pertanyaan yang hampir sama dengan SDGS namun lebih spesifik ke pertanyaan keadaan ekonomi dan lingkungan keluarga 

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

Premium 23.03

### Informasi tambahan

Karena di wilayah kabupaten kami sedang dan akan dilaksanakan pemutakhiran data penduduk

**Comment by vickyrolanda** [comment]
pak @cepiandiana apakah ini bug yang anda alamin, atau cara kerja pembagian modul belum anda coba dan atur , mohon lebih dirincikan agar lebih mudah menganalisis kondisinya.

**Comment by cepiandiana** [comment]
> pak @cepiandiana apakah ini bug yang anda alamin, atau cara kerja pembagian modul belum anda coba dan atur , mohon lebih dirincikan agar lebih mudah menganalisis kondisinya.

Pak @vickyrolanda pada bagian modul sudah dicoba, namun belum bisa untuk memberikan akses penduduk kepada masing2 user dengan role RT.. 

Lebih spesifiknya begini :  
1. Admin membuat user yang bertugas sebagai pendata warga (Bisa RT atau atau Petugas Khusus)
2. Ketika login, si user tersebut hanya bisa melihat data RT setempat saja (sesuai akses dia login), misalkan ketika diberi akses RT. 01 RW. 02, maka user tersebut hanya bisa melihat dan ubah data warga RT. 01 RW. 02 saja, begitupun seterusnya.

Begitu pak @vickyrolanda hehehe

**Comment by andifahruddinakas** [comment]
Untuk menerapkan issue ini, issue tambahan diperlukan.

Pecahan : 
- [ ] Tambahkan hak akses lainnya dengan daftar sbb (akses sesuai wilayah, dll) https://github.com/OpenSID/OpenSID/issues/7828
- [ ] Saat login filter berdasarkan wilayah jika dicek list hak akses wilyah. (mis: penduduk, keluarga, rtm, suplemen, dll)
