### ISSUE TITLE
Bug/error: Gagal saat buat artikel baru

### ISSUE THREAD

**Issue by FirlianiF** [OpenSID/OpenSID#6459]
### Jelaskan error yg dialami

-

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

harapannya jika sudah ada solusi bisa diberikan dulu agar desa tidak tertunda membuat artikel.

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/30171560/222338813-20d07ec8-be8c-4d3e-ad5d-a0e665120c15.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v23.03-premium

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/2091
