### ISSUE TITLE
Bagaimana saya bisa menambahkan submodul baru pada Modul Keuangan?

### ISSUE THREAD

**Issue by efronpaduansi** [OpenSID/OpenSID#6462]
### Apa kekurangan yg ingin diatasi?

Halo semuanya, saat ini saya sedang mengalami kendala dan memohon bantuan dari komunitas OpenSID agar diberikan pencerahan bagaimana saya bisa membuat/menambahkkan sebuah submodul baru pada Modul Keuangan. Saya membutuhkan submodul dengan nama "Iuran Bulanan". Mohon bantuannya, terima kasih.

### Jelaskan solusi yg diinginkan

Mohon bantuan dari komunitas OpenSID agar diberikan pencerahan bagaimana saya bisa membuat/menambahkkan sebuah submodul baru pada Modul Keuangan. Saya membutuhkan submodul dengan nama "Iuran Bulanan". Mohon bantuannya, terima kasih.

### Apakah ada alternatif lain

Mohon bantuan dari komunitas OpenSID agar diberikan pencerahan bagaimana saya bisa membuat/menambahkkan sebuah submodul baru pada Modul Keuangan. Saya membutuhkan submodul dengan nama "Iuran Bulanan". Mohon bantuannya, terima kasih.

### Untuk versi OpenSID mana

versi terbaru 21.03

**Comment by vickyrolanda** [comment]
bung @efronpaduansi, jika memiliki rancangan atau modul apa yang ingin di tambahkan boleh di jelaskan secra detail bagaimana cara kerja modul "Iuran Bulanan" yang ingin bung @efronpaduansi buat , lalu jika bung @efronpaduansi punya kemampuan untuk mengembangan modul saya mengajak bung @efronpaduansi untuk menjadi kontributor yang mana setiap pengerjaan PR akan ada poin yang setiap bulannya di hitung menjadi fee pengerjaan PR. silahkan bisa hubungi saya jika berminat ya bung.

**Comment by efronpaduansi** [comment]
Terima kasih bung @vickyrolanda . Ceritanya saya sedang mengkustomisasi OpenSID menjadi sebuah sistem yang bisa menunjang kegiatan di RW. Saat ini saya ingin menambahkan fitur "Iuran Bulanan" untuk mendata Iuran Bulanan warga se-RW. Terima kasih.

**Comment by andifahruddinakas** [comment]
> Terima kasih bung @vickyrolanda . Ceritanya saya sedang mengkustomisasi OpenSID menjadi sebuah sistem yang bisa menunjang kegiatan di RW. Saat ini saya ingin menambahkan fitur "Iuran Bulanan" untuk mendata Iuran Bulanan warga se-RW. Terima kasih.

Silahkan buat PR dari ubahan tsb, nanti akan dicek.

Untuk menambah modul bisa lihat contoh yang ada dimigrasi https://github.com/OpenSID/OpenSID/blob/c27d0630ce14d69c8af8d82d1bb5328c89777e79/donjo-app/models/migrations/Migrasi_fitur_premium_2205.php#L331

Ubahan sebaiknya dikirim sebagai PR agar nantinya jika ada rilis baru ubah tsb tidak hilang atau terjadi konflik.
