### ISSUE TITLE
Permintaan fitur: Database

### ISSUE THREAD

**Issue by samboputra2023** [OpenSID/OpenSID#6463]
### Apa kekurangan yg ingin diatasi?

Banyak teman-teman bahkan saya sendiri kesulitan saat ingin menjalankan OpenSID, dikarenakan tidak tahu nama dan lokasi Database nya. 

### Jelaskan solusi yg diinginkan

Buatkan folder khusus untuk Database

### Apakah ada alternatif lain

Tidak

### Untuk versi OpenSID mana

V23.03

### Informasi tambahan

Hanya Itu

**Comment by efronpaduansi** [comment]
Bung @samboputra2023 , sebelum anda menjalankan OpenSID pastikan sudah mengatur konfigurasi database yang ada di folder **desa/config/database.php**. Pastikan bahwa pengaturan database anda sudah sesuai seperti nama **hostname, username, password dan port**. Anda tidak perlu melakukan import database  jika baru pertama kali menginstall OpenSID pada komputer anda. Anda cukup membuat database baru didalam server anda. Semoga membantu.

**Comment by samboputra2023** [comment]
Jika saya ingin menjalankan OpenSID di localhost, berarti saya hanya perlu
membuat database baru tanpa harus meng-inport database dari folder "desa",
begitu ya pak?
Berarti database yang saya buat itu dibiarkan kosong tanpa ada tabel
didalamnya.
Terima kasih atas bimbingannya..
Salam dari Saya Imran di Kabupaten kerinci, Provinsi Jambi.
Hp. +6287777623717

**Comment by efronpaduansi** [comment]
Iya betul bung @samboputra2023 . Aplikasi OpenSID akan otomatis membuat table pada database anda saat proses penginstallan. Salam kenal juga saya Efron dari Tangerang Selatan, Banten.

**Comment by samboputra2023** [comment]
Pada Aplikasi "OpenSID-23.03" didalamnya tidak ada folder "desa".
Setelah saya cari-cari, ternyata file "database.php" terdapat didalam
folder "denjo-app/config".
Apakah itu sudah benar pak?

**Comment by efronpaduansi** [comment]
Oalah saya juga baru cek untuk versi terbarunya. Beberapa bulan lalu saya masih make versi lama yang ada folder desanya. Bung @samboputra2023 , silahkan disesuaikan saja.

**Comment by samboputra2023** [comment]
Baik pak.
Terima kasih dan sukses selalu

**Comment by vickyrolanda** [comment]
bung @samboputra2023 , 
Sebaiknya bisa juga baca step by step di wiki disana lengkap tutorial pengguaannya lihat disini https://github.com/OpenSID/OpenSID/wiki/Install-OpenSID-Baru, semoga membantu
