### ISSUE TITLE
Halaman kerjasama loading terus saat Simpan

### ISSUE THREAD

**Issue by apidong** [OpenSID/OpenSID#6465]
![image](https://user-images.githubusercontent.com/20056421/222954733-0f980fbd-bbfa-4eae-8b44-5b43708ee8f6.png)

**Comment by vickyrolanda** [comment]
mbak @FirlianiF  apakah issue ini sudah dicek di layanan? Bisa dilihat form status kosong.

**Comment by FirlianiF** [comment]
> mbak @FirlianiF apakah issue ini sudah dicek di layanan? Bisa dilihat form status kosong.

Sudah mas, akan diperbaiki di layanan.

**Comment by FirlianiF** [comment]
issue layanan https://github.com/OpenSID/wiki-layanan-opendesa/issues/272

**Comment by FirlianiF** [comment]
![verifff](https://user-images.githubusercontent.com/30171560/223304164-f2e84517-33e9-4341-a1f6-babe98c84d23.PNG)
desa tsb berhasil mengirim form pendaftaran kerjasama, bisa dilihat di status pelangaannya saat ini menunggu verifikasi email

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/2108
