### ISSUE TITLE
Bug : Tidak bisa menambah anggota grup

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#6467]
Terjadi gagal simpan saat menambahkan anggota grup pada daftar kontak hubung warga.

`ERROR - 2023-03-06 10:59:31 --> Severity: error --> Exception: SQLSTATE[HY000]: General error: 1364 Field 'id_grup' doesn't have a default value (SQL: insert into `anggota_grup_kontak` (`updated_at`, `created_at`) values (2023-03-06 10:59:31, 2023-03-06 10:59:31)) D:\PROJECT OPENDESA\OpenSID\vendor\illuminate\database\Connection.php 712
`

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/2106
