### ISSUE TITLE
Bug/error: surat keterangan kematian

### ISSUE THREAD

**Issue by Restony33** [OpenSID/OpenSID#6468]
### Jelaskan error yg dialami

hasil download saat pembuatan surat keterangan kematian hari, tanggal, jam dan tempat kematian tidak tampil dalam surat

### Cara untuk mereplikasi errornya

1. login admin
2. layanan surat
3. cetak surat
4. keterangan kematian
5. isi data dan cetak

![2023-03-06_12h39_30](https://user-images.githubusercontent.com/104592011/223028453-444d60fa-d71a-41ad-a09b-96383a66523a.jpg)

### Hasil yg diharapkan

berjalan normal

### Tangkapan layar dan log error

![2023-03-06_12h39_16](https://user-images.githubusercontent.com/104592011/223028710-c3404cc8-f416-480e-8a1e-27a8f885d28c.jpg)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v23.03-premium

### Tema Yang Digunakan

esensi

### Informasi tambahan

https://berputar.opendesa.id/

**Comment by apidong** [comment]
@vickyrolanda setelah saya cek, ini memang bug. tetapi ini bug untuk surat RTF. apakah perlu diperbaiki?

**Comment by vickyrolanda** [comment]
> @vickyrolanda setelah saya cek, ini memang bug. tetapi ini bug untuk surat RTF. apakah perlu diperbaiki?

ia mas tetap perlu mas, karena surat keterangan kematian belum ada TinyMCEnya jadi perbaikan tetap di perlukan.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/2113
