### ISSUE TITLE
Format Surat Keluar

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#647]
sesuai dengan PERATURAN MENTERI DALAM NEGERI REPUBLIK INDONESIA NOMOR 47 TAHUN 2016 TENTANG ADMINISTRASI PEMERINTAHAN DESA untuk format surat keluar seperti gambar dibawah ini : 
![image](https://user-images.githubusercontent.com/25834335/31224013-0bf4384a-a981-11e7-9b57-ce872963996a.png)

**Comment by MUHAMMADRANGSEL** [comment]
Dimensu sekretariat tinggal menu surat keluar yg belum dikerjakan, kami mohon para programmer spy ini menjadi prioritas

**Comment by eddieridwan** [comment]
Duplikat #558
