### ISSUE TITLE
Bug: Log migrasi

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#6479]
Terjadi error log migrasi gagal, namun migrasi tetap jalan terus.

Penyebab : 
1. return $hasil bukan keseluruhan (hanya bagian akhir)
2. kolom tidak ditemukan

Ditemukan saat mengerjakan OpenKab.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/2129
