### ISSUE TITLE
Administrasi Pemerintah Desa

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#648]
untuk lebih memantapkan lagi OpenSID yang sedang dikembangkan dan supaya Opensid menjadi Aplikasi yang luar bisa dan mantap dengan ditambahkannya MENU SEKRETARIAT maka saya mengusulkan supaya format tentang administasi tersebut semua ada di dalam sisetem sesuai dengan PERATURAN MENTERI DALAM NEGERI REPUBLIK INDONESIA NOMOR 47 TAHUN 2016 TENTANG ADMINISTRASI PEMERINTAHAN DESA
di Permendagri tersebut jenis dan model administrasi dibagi menjadi 5 macam :
**(1)	Administrasi Umum;**
Administrasi Umum Pasal 5
(1)	Kegiatan pencatatan data dan informasi mengenai kegiatan-kegiatan Pemerintahan Desa dimuat dalam Administrasi Umum.
(2)	Administrasi Umum sebagaimana dimaksud pada ayat (1) meliputi:
a.	Buku Peraturan Di Desa;
b.	Buku Keputusan Kepala Desa;
c.	Buku Inventaris dan Kekayaan Desa;
d.	Buku Aparat Pemerintah Desa;
e.	Buku Tanah Kas Desa;
f.	Buku Tanah di Desa;
g.	Buku Agenda;
h.	Buku Ekspedisi; dan
i.	Buku Lembaran Desa dan Buku Berita Desa.

**(2)	Administrasi Penduduk;**
Administrasi Penduduk Pasal 6
(1)	Kegiatan pencatatan data dan informasi mengenai kependudukan di Desa baik mengenai penduduk sementara, penambahan dan pengurangan penduduk maupun perkembangan penduduk dimuat dalam administrasi penduduk.
(2)	Administrasi Penduduk sebagaimana dimaksud pada ayat (1) meliputi:
a.	Buku Induk Penduduk;
b.	Buku Mutasi Penduduk Desa;
c.	Buku Rekapitulasi Jumlah Penduduk;
d.	Buku Penduduk Sementara; dan
e.	Buku Kartu Tanda Penduduk dan Buku Kartu 
Keluarga.

**(3)	Administrasi Keuangan;** 
Administrasi Keuangan Desa Pasal 7
(1)	Kegiatan pencatatan data dan informasi mengenai pengelolaan keuangan Desa dimuat dalam Administrasi Keuangan Desa.
(2)	Administrasi Keuangan Desa sebagaimana dimaksud pada ayat (1) meliputi:
a.	Buku APB Desa;
b.	Buku Rencana Anggaran Biaya;
c.	Buku Kas Pembantu Kegiatan;
d.	Buku Kas Umum;
e.	Buku Kas Pembantu; dan
f.	Buku Bank Desa.

**(4)	Administrasi Pembangunan; dan**
Administrasi Pembangunan Pasal 8
(1)	Kegiatan pencatatan data dan informasi mengenai pelaksanaan pembangunan dan pemberdayaan masyarakat dimuat dalam Administrasi Pembangunan.
(2)	Administrasi Pembangunan sebagaimana dimaksud pada ayat (1) meliputi:
a.	Buku Rencana Kerja Pembangunan Desa;
b.	Buku Kegiatan Pembangunan;
c.	Buku Inventarisasi Hasil-hasil Pembangunan; dan
d.	Buku Kader Pendampingan dan Pemberdayaan Masyarakat.

**(5)	Administrasi Lainnya.**
Administrasi Lainnya Pasal 9
(1)	Kegiatan pencatatan data dan informasi mengenai penyelenggaraan Pemerintahan Desa, pelaksanaan pembangunan, pembinaan kemasyarakatan, dan pemberdayaan masyarakat selain sebagaimana dimaksud dalam Pasal 5, Pasal 6, Pasal 7 dan Pasal 8 dimuat dalam Buku Administrasi Lainnya sesuai dengan kebutuhan.
(2)	Administrasi Lainnya sebagaimana dimaksud pada ayat (1) antara lain meliputi:
a.	Kegiatan Badan Permusyawaratan Desa dalam buku administrasi Badan Permusyawaratan Desa;
b.	Kegiatan musyawarah Desa dalam buku  musyawarah Desa; dan 
c.	Kegiatan Lembaga Kemasyarakatan Desa/Lembaga Adat dalam buku Lembaga Kemasyarakatan Desa/Lembaga Adat.

**Dan yang menjadi prioritas yang dimasukkan didalam aplikasi OpenSID adalah Point 1, 2, 4 dan 5 : **
**(1)	Administrasi Umum;**
**(2)	Administrasi Penduduk;**
**(4)	Administrasi Pembangunan; dan**
**(5)	Administrasi Lainnya.**

**untuk point nomor 3 **(3)	Administrasi Keuangan;** sudah ada aplikasi SISKUEDES**

Untuk Formatnya sekaligus cara pengisannya terlampir
[permen_no.47_th_2016.zip](https://github.com/eddieridwan/OpenSID/files/1359069/permen_no.47_th_2016.zip)

**Comment by MUHAMMADRANGSEL** [comment]
Harapan kedepan supaya OpenSID yang terus mengacu kepada peraturan yg berlaku yg membuat OpenSID menjadi semakin diminati dan terus jaya

**Comment by eddieridwan** [comment]
Issue ini tidak dalam bentuk yang bisa dikerjakan. Usulan di issue ini merupakan rancangan jangka panjang. Sebaiknya isi issue ini kita pindahkan ke tempat lain, mungkin ke dokumen 'road map' atau 'cetak biru' OpenSID.

Mungkin dokumen tsb bisa dilampirkan di slack di channel analisis-kebutuhan https://opensid.slack.com/messages/C6XQEDF3Q/details/.

Untuk dikerjakan, suatu issue harus terbatas pada satu fitur yang dijelaskan secara rinci. Lihat penjelasan di https://github.com/OpenSID/OpenSID/wiki/Pengelolaan-Masalah-dan-Permintaan-Perbaikan-SID dan di https://github.com/OpenSID/OpenSID/wiki/Prioritas-Pengembangan.

**Comment by MUHAMMADRANGSEL** [comment]
Siap

**Comment by mizwaruddin** [comment]
@afa28 sdh dibuat issue secara rinci. Bisa di close.
