### ISSUE TITLE
Bug : Data Buku Tamu - Kepuasan tidak tampil

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#6480]
Setelah melakukan pengisian kuisioner pada halaman buku tamu, pada halaman data pertanyaan tidak tampil.

<img width="526" alt="image" src="https://user-images.githubusercontent.com/57283157/223662096-2594f17e-013c-43cf-8c32-71f1bd34c8dd.png">

Solusi sementara, lakukan migrasi ulang.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/2131
