### ISSUE TITLE
Bug/error: Tidak bisa akses modul Pertanahan > Daftar Persil

### ISSUE THREAD

**Issue by agungsugiarto** [OpenSID/OpenSID#6483]
### Jelaskan error yg dialami

Tidak bisa akses modul Pertanahan > Daftar Persil

### Cara untuk mereplikasi errornya

Buka modul Pertanahan > Daftar Persil

### Hasil yg diharapkan

normal

### Tangkapan layar dan log error

<img width="382" alt="image" src="https://user-images.githubusercontent.com/10989147/223913770-7e128afc-f33c-41ba-b7b0-759f56784286.png">

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

23.03-premium-rev01

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2133
