### ISSUE TITLE
Gagal input token

### ISSUE THREAD

**Issue by FirlianiF** [OpenSID/OpenSID#6484]
![aaaaaaa](https://user-images.githubusercontent.com/30171560/223922953-a654bcf1-b16b-4ca5-b459-83bfbb23b8ea.PNG)
muncul alert tidak bisa input token, tapi token tersimpan k db, dan fitur2 premium bisa jalan normal.

**Comment by FirlianiF** [comment]
Access to fetch at 'https://layanan.opendesa.id/api/v1/pelanggan/pemesanan' from origin 'https://taopa.desa.id' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

Apa berpengaruh karena CORS juga?

**Comment by FirlianiF** [comment]
https://stackoverflow.com/questions/43871637/no-access-control-allow-origin-header-is-present-on-the-requested-resource-whe

**Comment by eddieridwan** [comment]
https://github.com/lamualfa/cors_id

**Comment by Yusuf302002** [comment]
Tidak bisa di akses gimana y 
https://pasegeran.banjarnegara-desa.id/index.php/soon.html

**Comment by andifahruddinakas** [comment]
Duplicate issue https://github.com/OpenSID/OpenSID/issues/6485
