### ISSUE TITLE
Bug/error: anjungan tidak dapat digunakan padahal fitur premium sudah aktif

### ISSUE THREAD

**Issue by FirlianiF** [OpenSID/OpenSID#6486]
### Jelaskan error yg dialami

 .

### Cara untuk mereplikasi errornya

.

### Hasil yg diharapkan

untuk anjungan dibuatkan cache seperti premium. karena sekarang kalau token gagal dimuat langsung tidak bisa dibuka. jd terhubung langsung dengan layanan

### Tangkapan layar dan log error

.

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/2154
