### ISSUE TITLE
Validasi Desa gagal saat nama desa memiliki Angka

### ISSUE THREAD

**Issue by apidong** [OpenSID/OpenSID#6488]
![image](https://user-images.githubusercontent.com/20056421/224254135-b1be349d-180c-427e-b12e-ae38c79f5745.png)

**Comment by vickyrolanda** [comment]
mas @apidong  PR OpenSID saya saya gabung https://github.com/OpenSID/premium/pull/2137 , apakah ini perlua da PR di API ?  soalnya sy lihat ada project API OpenSID.

**Comment by apidong** [comment]
@vickyrolanda gak usah pak, kemarin salah masukan project.
