### ISSUE TITLE
Tambahkan Peringatan saat hapus Penduduk

### ISSUE THREAD

**Issue by apidong** [OpenSID/OpenSID#6489]
Berikan peringatan pada fitur hapus penduduk, 
dengan pesan "Lakukan Hapus penduduk Jika ada kesalahan saat pengisian data atau penduduk tersebut tidak akan ditambahkan Kembali".

**Comment by eddieridwan** [comment]
Tambah kata "hanya". "Lakukan hapus penduduk hanya jika ada kesalahan saat pengisian data atau penduduk tersebut tidak akan ditambahkan kembali"

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/2148
