### ISSUE TITLE
SID3.10 - Penyesuaian Fitur Menu Analisis

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#649]
melihat fitur menu analisis yang ada di SID 3,10 yang simple yang akan lebih mudah dipahami dan sudah banyak perbaikan2, maka saya usulkan di OpenSID perlu disesuaikan lagi menu analisis yang ada dan saya usulkan perubahnnya 100%
![image](https://user-images.githubusercontent.com/25834335/31277074-06f7c202-aa54-11e7-9d3c-185aeadac6af.png)

sedang di OpenSID
![image](https://user-images.githubusercontent.com/25834335/31277094-1a705416-aa54-11e7-9831-6b610fe57506.png)

**Comment by MUHAMMADRANGSEL** [comment]
Semoga issue segera berada diprarilis

**Comment by MUHAMMADRANGSEL** [comment]
Mohon issue ini didahulukan mas eddie dikerjakan. Trima kasih sebelmnya

**Comment by eddieridwan** [comment]
Sudah dicommit ke master. 
Ubah supaya icon sesuai dengan versi Font Awesome yg digunakan di OpenSID.

**Comment by MUHAMMADRANGSEL** [comment]
tinggal Statistik Jawaban perlu disesuaikan seperti SID 3.10
![tangkapan layar 2017-10-15 15 04 36](https://user-images.githubusercontent.com/25834335/31582644-240e19c6-b1bc-11e7-8760-d5ad7f6a5046.png)
 
kalau di OpenSID pasca 2.5.1
![tangkapan layar 2017-10-15 15 05 26](https://user-images.githubusercontent.com/25834335/31582646-32770126-b1bc-11e7-8dc2-89603b6d3d96.png)
