### ISSUE TITLE
Bug/error: nomor kk sementara menampikan 0 saja

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#6499]
### Jelaskan error yg dialami

<img width="1440" alt="Screen Shot 2023-03-13 at 12 00 13" src="https://user-images.githubusercontent.com/36557759/224612147-f6ec8a8f-b2a2-4104-9012-dc4cdbf4d680.png">

pada saat membuat KK baru dengan nomor KK sementara pada saat melihat detail hanya menampikan 0 saja, seperti gambari di atas

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v23.03-premium-rev01

**Comment by andifahruddinakas** [comment]
Mas @vickyrolanda, untuk kasus ini dimana KK sementara kembali ditampilkan menjadi 0 memang dibuat seperti itu, karena tidak diperuntukkan digunakan untuk administrasi (sifatnya hanya sementara).

**Comment by vickyrolanda** [comment]
> Mas @vickyrolanda, untuk kasus ini dimana KK sementara kembali ditampilkan menjadi 0 memang dibuat seperti itu, karena tidak diperuntukkan digunakan untuk administrasi (sifatnya hanya sementara).

ia mas setuju , alasan kenpa di buat 0 karena mengingatkan petugas bawah NIK & NO KK memang masih kosong dan bersifat sementara. sehingga petugas harus memperbaruinya.
