### ISSUE TITLE
Pembuatan surat non warga 

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#650]
Pembuatan untuk surat non warga saya usulkan supaya jadi satu dengan surat warga tdk ubah seperti  surat keterangan lahir yang datanya ada di database dengan penduduk belum terdata supaya tdk terlalu banyak form surat  seperti gambar dibawah ini : 
![screenshot 2017-10-07 00 00 21](https://user-images.githubusercontent.com/25834335/31305627-07e2703c-aaf3-11e7-8638-e328e10ada9e.png)

**Comment by MUHAMMADRANGSEL** [comment]
Dan sudah saya coba mas eddie bisa cuma nama prnduduk yg buat surat di cetak surat keluar kosong

**Comment by eddieridwan** [comment]
Juga kembangkan surat_sporadik supaya menyediakan opsi pemohon dari luar desa (terusan issue #210).

**Comment by eddieridwan** [comment]
Pembuatan surat yang memungkinkan pemohon dari warga atau non-warga perlu dibuat per surat. Jadi perlu dibuatkan issue untuk setiap surat yang memerlukan. Misalnya, buat issue terpisah (#720) untuk Surat Perintah Perjalanan Dinas, di mana pemohon bisa dari warga atau non-warga.

Karena alasan di atas, issue ini akan ditutup.
