### ISSUE TITLE
Bug/error: nomor KK menjadi 0 setelah menambahkan anggota keluarga baru

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#6500]
### Jelaskan error yg dialami

issue ini terjadi ketika menambah anggota baru yang menyebabkan nomor KK menjadi 0, setelah di cek pada table tweb_keluarga field nik_kepala menjadi NULL

![IMG_32C5608FCD19-1](https://user-images.githubusercontent.com/36557759/224616702-532d208c-d050-4c5b-b781-940df3c54424.jpeg)

<img width="1440" alt="Screen Shot 2023-03-13 at 12 00 13" src="https://user-images.githubusercontent.com/36557759/224616915-0aca4a75-c406-4664-92d4-ba6b2e43bd5e.png">

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v23.03-premium-rev01

**Comment by apidong** [comment]
@vickyrolanda ini dikarenakan menggunakan kk sementara. mohon di cek, apakah ini memang aturan di opensid dari dulu atau memang bug.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/2150
