### ISSUE TITLE
Mandiri Beranda/Profil (Profil, Ganti PIN, Cetak Biodata, Cetak Salinan KK, Dokumen, Verifikasi, Pendapat, Keluar)

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#6505]
- Perlu ditabahkan migrasi untuk kolom config_id yang berelasi dengan table config(id) 
-  Setiap pemanggilan query perlu ditambahkan where(‘config_id’,$config_id)
- Setiap tambah , edit & hapus perlu ditambahkan where(‘config_id’,$config_id)

_**selain itu issue masih perlu dilengkapin**_

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/2166
