### ISSUE TITLE
SURAT KEMATIAN F-2.01 TIDAK TAMPIL

### ISSUE THREAD

**Issue by pemdeslinggapura** [OpenSID/OpenSID#6508]
### Jelaskan error yg dialami

File PDF Surat Kematian tidak menampilkan data apapun (blank)

### Cara untuk mereplikasi errornya

1. Layanan Surat
2. Cetak Surat
3. Surat Keterangan Kematian
4. Unduh RTF
5. Buka FIile PDF Surat Keterangan Kematian

### Hasil yg diharapkan

Manampilkan Formulir F-1.01 secara lengkap

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/89450861/225498208-d8959df7-3beb-44c3-b070-43f09468fb9f.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

V23.03-premium-rev01

**Comment by apidong** [comment]
@vickyrolanda mohon di cek pak, soalnya saya coba di berputar nomal dan template yang disediakan format f-2.29 bukan f1.0.1. ini mungkin lampiran custom.
![image](https://user-images.githubusercontent.com/20056421/226091872-0c0edd07-0f1d-4e14-8db3-492b92d57d3f.png)
![image](https://user-images.githubusercontent.com/20056421/226091879-923e4ba7-762b-439b-a4aa-7c8ef7e70265.png)

**Comment by eddieridwan** [comment]
@vickyrolanda Verifikasi dengan Permendagri terkait memastikan formulir mana yg berlaku saat ini.

**Comment by pemdeslinggapura** [comment]
Di file Template Surat versi Opensid premium terbaru di folder Surat Kematian isinya bukan file f-2.29
![image](https://user-images.githubusercontent.com/89450861/226150450-4698fa1f-a96c-41c7-9c19-0a62af03beed.png)

**Comment by apidong** [comment]
penyebabnya : karena migrasi yang mengubah format lampiran lama (f.2.29) ke format lampiran baru (f.2.01) menghilang.
solusi : tampilkan kembali migrasi tersebut

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/2212

**Comment by vickyrolanda** [comment]
sesuai lampiran issue berikut ini lampiran Kematian di update ke F-2.01 
https://github.com/OpenSID/OpenSID/issues/5259
https://github.com/OpenSID/OpenSID/issues/5654

berdasarkan peraturan dibawah ini : 
[Permendagri-No-109-Th-2019-Lampiran-Tentang-Formulir-dan-Buku-Yang-Digunakan-Dalam-Administrasi-Kependudukan.pdf](https://github.com/OpenSID/OpenSID/files/11104451/Permendagri-No-109-Th-2019-Lampiran-Tentang-Formulir-dan-Buku-Yang-Digunakan-Dalam-Administrasi-Kependudukan.pdf)
