### ISSUE TITLE
SID3.10 - Penyesuaian modul Kelompok

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#651]
SID 3.10 berisi beberapa perubahan untuk memudahkan pengelolaan Kelompok.

**Comment by bhien76** [comment]
iya bang @eddieridwan, kayaknya pengelolaan kelompok dari SID 3.10 bisa diterapkan di OpenSID karena lebih fleksibel.

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
