### ISSUE TITLE
Modul Keuangan - Laporan Bidang Semester 1 tidak sesuai

### ISSUE THREAD

**Issue by apidong** [OpenSID/OpenSID#6510]
di sisi admin pada laporan bidang semester 1, menampilkan format laporan kelompok. 
![image](https://user-images.githubusercontent.com/20056421/226086267-0ecdef9f-bdba-4015-94a6-0e0eee7ad038.png)
seharusnya sepertin laporan bidang semester 2
![image](https://user-images.githubusercontent.com/20056421/226086306-6bc48927-e95a-4992-bee9-55d3ab0636d9.png)

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/2172
