### ISSUE TITLE
Buat Pengaturan Identitas desa melalui config kode_desa

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/OpenSID#6514]
Cara Replikasi : 
1. Install Baru dengan database posisi kosong.
2. pada file config ditambahkan kode desa script sebgai berikut `$config['kode_desa'] = "xxxx.....";` (disesuaikan dengan kode desanya)
3. Jalankan melalui browser
4. Ketika menggunakan browser lain / incognito tidak Bisa login (tabel user kosong)

Tampilan Error sebagai berikut:
Tombol `Layanan Mandiri` Hilang
![testing-databasegabungan1](https://user-images.githubusercontent.com/68048807/226505859-6ba60c5c-db56-470a-8a9c-ae2c5f6daefe.JPG)

Ketika Klik Tombol `Login Admin`
![testing-databasegabungan2](https://user-images.githubusercontent.com/68048807/226505869-b08d8f70-8b57-4f39-bae4-8f151a7d7c8e.JPG)

**Comment by apidong** [comment]
1. buat alur case untuk token
2. buat solusi untuk masalah token yang di input melalui config

**Comment by scqolbu24** [comment]
> * buat alur case untuk token
> * buat solusi untuk masalah token yang di input melalui config

Dibuat issue tersendiri https://github.com/OpenSID/premium/issues/2180

**Comment by scqolbu24** [comment]
sudah dikerjakan melalui PR https://github.com/OpenSID/premium/pull/2176
