### ISSUE TITLE
Bug/error: SiapPakai #1

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#6517]
### Jelaskan error yg dialami

izin bertanya suhu, untuk tamabh data di pembangunan tidak ada kenapa ya ? di menu artikel juga.

kami pakai layanan opensid siap pakai bang

### Cara untuk mereplikasi errornya

apakah sudah dipastikan user tersebut punya akses untuk menambah data pak?

### Hasil yg diharapkan

jika dilihat dari gambar di atas, yg login adalah admin utama.

### Tangkapan layar dan log error

![photo_2023-03-21_12-09-24](https://user-images.githubusercontent.com/46939846/226524009-60ebdc2e-7449-4cd0-9018-eef1a0690c14.jpg)

![photo_2023-03-21_12-09-15](https://user-images.githubusercontent.com/46939846/226524015-16ddb6b7-f7ce-4ed5-be4e-18b070c22b53.jpg)

![photo_2023-03-21_12-13-11](https://user-images.githubusercontent.com/46939846/226524052-e180bf33-130e-4797-8359-2af7956b4142.jpg)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

SiapPakai

**Comment by apidong** [comment]
![image](https://user-images.githubusercontent.com/20056421/226570255-9d45167d-686b-41b2-94e2-238e9c7f5535.png)
dari info pak rudi, sudah diperbaiki. hanya dengan menjalankan migrasi database.
