### ISSUE TITLE
Permintaan fitur: tampilkan statistik bantuan di peta menurut wilayah

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#6519]
### Apa kekurangan yg ingin diatasi?

Kota Bima memerlukan fitur menampilkan statistik bantuan di peta, yg saat ini belum ada.

### Jelaskan solusi yg diinginkan

Tampilkan statistik bantuan di peta sesuai wilayah pada posisi kursor (desa/dusun/rw/rt).

Tampilkan statistik bantuan seperti yg sudah ada di menu `Statistik > Statistik Kependudukan > Statistik Program Bantuan > Penerima Bantuan Penduduk` dan `Penerima Bantuan Keluarga`.

Penerima Bantuan Keluarga juga perlu disesuaikan wilayah kursor.

Sediakan filter status bantuan Semua/Aktif/Tidak Aktif dan Tahun

### Apakah ada alternatif lain

Tidak ada

### Untuk versi OpenSID mana

v22.03-premium

### Informasi tambahan

Sejauh mungkin gunakan script sama dengan untuk `Statistik > Statistik Kependudukan > Statistik Program Bantuan > Penerima Bantuan Penduduk`. Supaya konsisten, ubah filternya sesuai gambar di bawah

<img width="1391" alt="image" src="https://user-images.githubusercontent.com/249563/227079953-6a729376-a110-447f-81bc-ea21f5753712.png">

Sejauh mungkin gunakan script sama dengan untuk `Statistik > Statistik Kependudukan > Statistik Program Bantuan > Penerima Bantuan Keluarga`. Supaya konsisten, ubah filternya sesuai gambar di bawah

<img width="1391" alt="image" src="https://user-images.githubusercontent.com/249563/227079563-6b87b840-6fde-402b-abd2-0b6b9de34c45.png">

**Comment by andifahruddinakas** [comment]
Batasan : 
- [ ] Tampilkan statistik bantuan pada peta (desa, dusun, rt, dan rw)
Contoh : 
<img width="540" alt="image" src="https://user-images.githubusercontent.com/57283157/235065207-653f6430-564e-41ec-8e7d-13c490c3460b.png">

- [ ] Tampilkan detail statistik bantuan
Contoh : 
<img width="538" alt="image" src="https://user-images.githubusercontent.com/57283157/235065386-9ba3c20c-079a-40e2-917f-b91ff6fa5cc3.png">

- [ ] Sediakan fitur tsb pada peta tema (halaman depan) dan admin

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/2274
