### ISSUE TITLE
SID3.10 - Gunakan contoh foto dan gambar 404 not found

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#652]
Dengan warna menarik.

**Comment by MUHAMMADRANGSEL** [comment]
Gunakan contoh foto dan gambar 404 not found menurut saya dibiarkan saja mas eddie seperti kondisi sekarang lebih ok

**Comment by MUHAMMADRANGSEL** [comment]
Di closed saja ini mas eddie

**Comment by eddieridwan** [comment]
Tidak akan dikerjakan.
