### ISSUE TITLE
Install Awal Menggunakan Config kode_desa memliki perbedaan dengan manual

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#6521]
Install awal menggunakan config kode_desa, data yang disimpan (kode desa, kecamatan, kabupaten) mengandung titik. Sedangkan jika dilakukan manual, data hanya berupa angka. Ini membuat konsisten dan menyebabkan gagal menambahkan desa baru pada OpenSID database gabungkan karena yang dibandingkan berbeda (ada titik dan tidak).

Database yang tersimpan dari install melalui config:
<img width="722" alt="image" src="https://user-images.githubusercontent.com/57283157/227130023-ac09b19a-9214-4b3f-af2c-4b0380533a9b.png">

Error admin tambah desa baru OpenSID DB gabungan:
<img width="196" alt="image" src="https://user-images.githubusercontent.com/57283157/227130689-8b50f87b-f45f-4a5e-b2cb-f2923034d33a.png">
```
<?php defined('BASEPATH') OR exit('No direct script access allowed'); ?>

ERROR - 2023-03-23 14:05:53 --> 5306 - 53.06
```

Solusi : 
- Samakan validasi tambah/ubah data config dari admin dan saat install awal dengan config kode_desa.
- Buat migrasi untuk hapus titik yang ada.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/2183
