### ISSUE TITLE
Bug/error: Menu kependudukan error 500, info sistem tdk menampilkan error

### ISSUE THREAD

**Issue by akmalfadli** [OpenSID/OpenSID#6528]
### Jelaskan error yg dialami

Error 500 Sebuah Kesalahan Basis Data Telah Terjadi pada halam Kependudukan->penduduk

### Cara untuk mereplikasi errornya

Instalasi baru OpenSID Versi 23.03 bukan upgrade

1. Pergi ke menu Kependudukan 
2. klik Penduduk
3. Error 500

### Hasil yg diharapkan

Menampilkan list penduduk

### Tangkapan layar dan log error

**Tampilan Error**

![error](https://user-images.githubusercontent.com/13087253/227861875-70f39e74-5a8e-4179-8549-02640e2ed2ea.PNG)

**Log Error**

![error 2](https://user-images.githubusercontent.com/13087253/227861959-5f856d96-a552-4b33-a1d2-b5c75747f011.PNG)

### Rilis Versi OpenSID

Rilis Umum

### Versi OpenSID

v23.03

### Tema Yang Digunakan

essensi

**Comment by andifahruddinakas** [comment]
Mas @emboxs, versi MySQL yang digunakan?

**Comment by akmalfadli** [comment]
@andifahruddinakas mysql versi 8, php versi 7.4

**Comment by andifahruddinakas** [comment]
> @andifahruddinakas mysql versi 8, php versi 7.4

Gunakan versi mysql 5* atau mariadb 10*

Bisa cek kebutuhan sistem di modul pengaturan > info sitem

<img width="411" alt="image" src="https://user-images.githubusercontent.com/57283157/228440581-9d93ff88-979e-4c6e-b2aa-11b7556aa009.png">

**Comment by akmalfadli** [comment]
@andifahruddinakas solved menggunakan mariadb v10, tapi di menu kebutuhan sistem pada saat menggunakan mysql v8 tidak menampilkan error / warning

**Comment by andifahruddinakas** [comment]
> @andifahruddinakas solved menggunakan mariadb v10, tapi di menu kebutuhan sistem pada saat menggunakan mysql v8 tidak menampilkan error / warning

<img width="530" alt="image" src="https://user-images.githubusercontent.com/57283157/228770258-d99ca8bc-2202-4eb0-90d2-141b8a1f0bea.png">

**Comment by andifahruddinakas** [comment]
https://github.com/OpenSID/OpenSID/issues/5639

bisa cek rilis yang akan datang untuk versi umum di https://github.com/OpenSID/OpenSID/wiki/Rilis-Umum-Yang-Akan-Datang

**Comment by ruririzal** [comment]
mas @andifahruddinakas 

setelah saya cek di Penduduk_model.php

![image](https://user-images.githubusercontent.com/28647065/231658908-e5aa0535-7ce3-484c-9d02-fc522446e663.png)

pemanggilan fungsi lookup_ref_penduduk() akan menambahkan tanda kurung tambahan

![image](https://user-images.githubusercontent.com/28647065/231659262-ff96ea1e-0fc4-44b1-86ae-690ee77c2d75.png)

solusi jika ingin menambahkan support halaman penduduk menggunakan mysql 8.^

![image](https://user-images.githubusercontent.com/28647065/231660117-e3a0ffff-c34b-4f6b-85c8-64fd2dc8a54d.png)

**Comment by andifahruddinakas** [comment]
> mas @andifahruddinakas 
> 
> setelah saya cek di Penduduk_model.php
> 
> ![image](https://user-images.githubusercontent.com/28647065/231658908-e5aa0535-7ce3-484c-9d02-fc522446e663.png)
> 
> pemanggilan fungsi lookup_ref_penduduk() akan menambahkan tanda kurung tambahan
> 
> ![image](https://user-images.githubusercontent.com/28647065/231659262-ff96ea1e-0fc4-44b1-86ae-690ee77c2d75.png)
> 
> solusi jika ingin menambahkan support halaman penduduk menggunakan mysql 8.^
> 
> ![image](https://user-images.githubusercontent.com/28647065/231660117-e3a0ffff-c34b-4f6b-85c8-64fd2dc8a54d.png)
> 

Untuk saat ini belum support mysql 8.

Untuk mendukung mysql 8 ada beberapa modul yg perlu disesuaikan salah satunya ini.

Silahkan dibuatkan PRnya mas @ruririzal

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/2256
