### ISSUE TITLE
Bug/error: Tidak bisa filter jenis peraturan desa

### ISSUE THREAD

**Issue by muhtar-coder** [OpenSID/OpenSID#6529]
### Jelaskan error yg dialami

ketika filter jenis peraturan desa untuk di cetak,,data blank padahal data ada
![image](https://user-images.githubusercontent.com/55665526/227936040-e0a4c7b9-12a2-4d93-9257-b4693b89383e.png)

### Cara untuk mereplikasi errornya

1. bumindes
2. buku perautaran desa
3. pilih jenis peraturan misal : peraturan desa atau pilihan lain nya juga sama
4. data peraturan yang sudah terisi semua menjadi blank

### Hasil yg diharapkan

bisa filter data untuk cetak sesuai jenis/tahun

### Tangkapan layar dan log error

![image](https://user-images.githubusercontent.com/55665526/227936596-202647d8-caed-43e7-a889-a6d3f8731214.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

23.03-premium-rev02

### Tema Yang Digunakan

-

### Informasi tambahan

-

**Comment by apidong** [comment]
@vickyrolanda mohon di verifikasi. saya coba filter tidak ada masalah
![image](https://user-images.githubusercontent.com/20056421/228630427-b33e9a18-adf6-4c3d-9102-013447b95b83.png)

hasil filter 
![image](https://user-images.githubusercontent.com/20056421/228630496-5a14d81a-c49f-4668-a25d-f12208c8504c.png)

**Comment by vickyrolanda** [comment]
saya coba juga berhasil : 
sebelum filter 
<img width="617" alt="image" src="https://user-images.githubusercontent.com/59082428/228632855-b5a96d76-7491-4c19-ab53-c03ca8a3d96c.png">

sesudah filter
<img width="615" alt="image" src="https://user-images.githubusercontent.com/59082428/228632914-b768d509-3397-41c9-a3ff-73ad8c622a7a.png">

ijin pak @muhtar-coder mungkin perhatikan jenis peraturannya, seingat saya ada yang sudah disesuaikan mungkin jenis peraturannya bisa di sesuaikan ulang sehingga bisa di filter berdasarkan jenis praturan yang tersedia.

untuk saat ini issue ini saya close dan jika menemukan bug yang terkait bisa buka kembali issue ini pak.
