### ISSUE TITLE
Lampiran surat kematian -  Tanggal kematian salah tidak sesuai inputan, jam, jenis kematian, tempat kematian

### ISSUE THREAD

**Issue by apidong** [OpenSID/OpenSID#6530]
Tanggal kematian salah tidak sesuai inputan, jam, jenis kematian, tempat kematian
![image](https://user-images.githubusercontent.com/20056421/227952785-6b8b89f6-89fc-4b99-8a1d-7f90e4c88928.png)

**Comment by apidong** [comment]
penyebabnya : karena migrasi yang mengubah format lampiran lama (f.2.29) ke format lampiran baru (f.2.01) menghilang. sehingga lampiran yang dipakai f2.29 dan variable  yang berubah
solusi : tampilkan kembali migrasi tersebut

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/2212
