### ISSUE TITLE
Bug/error: Perbaikan buku tamu yang mengakibatkan gagal migrasi rilis v23.04

### ISSUE THREAD

**Issue by apidong** [OpenSID/OpenSID#6536]

**Comment by vickyrolanda** [comment]
Perbaikan :

- [ ] Gunakan bidang, keperluan statis untuk data buku_kepuasan
- [ ] Buat migrasi penyesuaian
- [ ] Perbaikan validasi registrasi

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/2231
