### ISSUE TITLE
[TinyMCE] Sediakan pilihan otomatis menambahkan kode isian sesuai dengan format penulisan

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#6537]
Untuk memudahkan saat memasukkan kode isian (tidak perlu ganti manul) dan menghindari kesalahan penulisan, diperlukan tools untuk memudahkan hal tsb.

**Editor :** 
![Image](https://user-images.githubusercontent.com/57283157/229665484-38508d10-56f3-40d9-94be-21a4f1e4b9fe.png)

**Hasil :**
![Image](https://user-images.githubusercontent.com/57283157/229665651-ce5bc2b7-f727-41cb-9ef4-fd6922cefb32.png)

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/2241
