### ISSUE TITLE
[OpenSID DB Gabungan] Halaman periksa

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#6538]
Untuk halaman periksa perlu disesuaikan, kasus pada halaman periksa harus bisa jalan sebelum atau sesudah adanya config_id.

Bisa gunakan fuction **config_id_exist()**

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/2248
