### ISSUE TITLE
[TinyMCE] Kesalahan menampilkan kode_isian saat buat template header/footer dan surat

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#6539]
Bedakan salin template dan kode_isian untuk:
- [ ] Pengaturan header/footer
<img width="96" alt="image" src="https://user-images.githubusercontent.com/57283157/229666414-8175389b-fa09-4f29-bd37-3643bacded99.png">
<img width="165" alt="image" src="https://user-images.githubusercontent.com/57283157/229666438-7d68dea4-51c3-4cb1-9480-df5d51055ace.png">

- [ ] Pembuatan / Pencetakan Surat.
<img width="202" alt="image" src="https://user-images.githubusercontent.com/57283157/229666344-00919f88-8fdd-495e-a50c-6a2713c1f7bd.png">
<img width="98" alt="image" src="https://user-images.githubusercontent.com/57283157/229666370-f3509446-58a3-4a37-ba2d-4a6bdb35c4e4.png">

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/2242
