### ISSUE TITLE
[TinyMCE] Sediakan Pilihan template sistem atau desa saat buat tempate surat

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#6540]
Untuk menggunakan kembali template bawaan sistem belum ada pilihan tsb.

<img width="244" alt="image" src="https://user-images.githubusercontent.com/57283157/229666640-8cc8683a-5df5-48ba-a096-d46e8e871654.png">

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/2239
