### ISSUE TITLE
[TinyMCE] Permudah penambahan atribut required

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#6541]
Saat ini untuk menambahkan element required dilakukan secara manual dengan menambahkan class="required" pada kolom attribut. Dengan cara manual, akan besar kemungkinan untuk salah tulis.

SOLUSI : 
- [ ] Siapkan view dengan kolom required dengan isian box cekslist
- [ ] Lakukan migrasi dengan pengecekan form_isian, hapus data dengan class="required" jika ditemukan dan ganti ke format yg baru.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/2357
