### ISSUE TITLE
 Bug/error: Laporan Pindah Penduduk

### ISSUE THREAD

**Issue by redjoel** [OpenSID/OpenSID#6543]
### Jelaskan error yg dialami

Formulir Pindah Penduduk masih bisa diakses tapi :
1. Cetak Surat Pindah Penduduk tidak muncul File yang dimaksud (RTF dan pdfnya)
2. Penanda tangan hanya ada pilihan kepala desa dan sekretaris desa

### Cara untuk mereplikasi errornya

Cetak Sudat Pindah Penduduk

### Hasil yg diharapkan

1. File RTF dan PDF bisa muncul
2. Pilihan Penandatangan juga bisa muncul

### Tangkapan layar dan log error

**

### Rilis Versi OpenSID

Rilis Umum

### Versi OpenSID

23.04

### Tema Yang Digunakan

Natra

**Comment by vickyrolanda** [comment]
pak @redjoel solusinya bisa seperti ini pak : 
download tcpdf 6.6.2 di https://github.com/tecnickcom/TCPDF/archive/refs/tags/6.6.2.zip
trus ganti folder tcpdf di server folder vendor/tecnickcom

dan juga sementara sudah saya update di branch https://github.com/OpenSID/OpenSID/tree/dev-update 
silahkan di coba ya pak.
