### ISSUE TITLE
Bug/error: Isian Persetujuan Penggunaan OpenSID terdapat \n

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#6545]
Terjadi saat install baru.

<img width="302" alt="image" src="https://user-images.githubusercontent.com/57283157/230241376-6aec1498-41ac-4644-8dfe-37fda7406bb8.png">

Kasus ini kadang muncul dan kadang tidak dibeberapa instalasi awal. Perlu dicek kondisi yang menyebabkan hal tersebut terjadi.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/2251
