### ISSUE TITLE
Pindahkan Font TinyMCE untuk Pdf dari vendor ke folder desa agar bisa ditambahkan sendiri oleh pengguna

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#6546]
Saat ini font yang digunakan tinymce untuk generate pdf disimpan di folder vendor dan dicommit, ada kalanya package diupdate dan muncul peringatan perubahan commit sbb:
<img width="179" alt="image" src="https://user-images.githubusercontent.com/57283157/230242176-53cecf66-a28e-4171-8a73-342aab9c1033.png">

Jika tidak hati2, maka font2 tersebut akan ikut terhapus dan tercomit.

Solusi : 
Solusi A : 
1. Font bawaan disimpan difolder asset dalam bentuk .php yang sudah dikonversi.
2. Load font tsb saat menggunakan Html2Pdf pada lokasi asset.
Catatan : 
- Cara ini sudah dicoba, namu gagal karena fuction tambah/ambil font hanya berlaku di lokasi package tsb.
- https://stackoverflow.com/questions/28138913/how-to-add-ttf-font-to-html2pdf-php-program

Solusi B
1. Font bawaan disimpan difolder asset dalam .ttf
2. Konversi otomatis saat install awal atau kalau ada pembaruan/penambahan font.
3. ignore lokasi font pada pacage tsb (krn saat ini folder vendor masih dicommit)
4. Load font seperti biasanya saat generate pdf.

**Comment by eddieridwan** [comment]
@andifahruddinakas Siapa yg melakukan update font yg mengakibatkan muncul peringatan perubahan commit tersebut? Apakah pengguna? 

Jika pengguna yg melakukan, mungkin solusinya:

1. di folder desa disediakan folder khusus untuk font.
2. pada waktu mengambil font, prioritaskan yang ada di folder desa.

Dengan demikian, pengguna bisa juga menambah font sendiri sesuai kebutuhan, tanpa mempengaruhi rilis. 

Kalau menerapkan ini, maka menjadi issue tambah fitur (bukan teknis) karena berdampak pada apa yg dapat dilakukan pengguna.

**Comment by andifahruddinakas** [comment]
> @andifahruddinakas Siapa yg melakukan update font yg mengakibatkan muncul peringatan perubahan commit tersebut? Apakah pengguna?
> 
> Jika pengguna yg melakukan, mungkin solusinya:
> 
> 1. di folder desa disediakan folder khusus untuk font.
> 2. pada waktu mengambil font, prioritaskan yang ada di folder desa.
> 
> Dengan demikian, pengguna bisa juga menambah font sendiri sesuai kebutuhan, tanpa mempengaruhi rilis.
> 
> Kalau menerapkan ini, maka menjadi issue tambah fitur (bukan teknis) karena berdampak pada apa yg dapat dilakukan pengguna.

Saya coba demikian, dan bisa terjadi dirilis premium dan umum kalau ada yang gunakan composer. Karena saat ini composer disediakan namun folder vendor masih perlu dicommit.

Ok

**Comment by eddieridwan** [comment]
@andifahruddinakas kalau terjadi karena pengguna menggunakan composer, tentunya nanti akan juga dilakukan OpenDesa pada rilis berikutnya. Jadi dalam hal ini, biar mereka harus restore git dulu sebelum update. 

Tetapi sepertinya tetap ada use case untuk membuka jalan bagi pengguna menambah font sendiri, seperti untuk aksara lokal mereka atau kebutuhan khusus.

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2986
