### ISSUE TITLE
Kunci NIK

### ISSUE THREAD

**Issue by rsoeta** [OpenSID/OpenSID#6551]
### Apa kekurangan yg ingin diatasi?

Tolong buat edit NIK disable / readonly bagi akun selain Admin. 

### Jelaskan solusi yg diinginkan

Kalau bisa NIK yang sudah terdaftar itu terkunci dan tidak bisa diubah kecuali oleh admin web. 

### Apakah ada alternatif lain

Karena di pengaturan aplikasi pengguna hak ubah masih terlalu umum, artinya hak ubah disana berlaku pula untuk mengubah NIK yang sangat sensitif. 

### Untuk versi OpenSID mana

v2403.0.1

**Comment by balongbesuk** [comment]
sudah lihat d pengaturan pengguna?

**Comment by rsoeta** [comment]
> sudah lihat d pengaturan pengguna?

Sudah

**Comment by balongbesuk** [comment]
dah tau donk jawabanny?

**Comment by rsoeta** [comment]
> dah tau donk jawabanny?
> 

Iya pak, justru di pengaturan pengguna mah, ketika hak-ubah nya di buka maka NIK pun sama bisa diubah.
Dan ketika hak-ubah nya di non aktifkan semua data nya tidak bisa diubah mulai Nama, TTL, Alamat dll.

**Comment by balongbesuk** [comment]
nah sudah terjawab donk issueny?

**Comment by rsoeta** [comment]
> nah sudah terjawab donk issueny?

Nah oleh karena itu, semoga dirasa perlu agar membuat pengecualian bagi perubahan NIK hanya dapat dilakukan oleh Admin Web.

Terimakasih

**Comment by balongbesuk** [comment]
![image](https://user-images.githubusercontent.com/35319600/231202571-34a6ecf5-1bd3-4bdd-897f-849e9e0a1b4b.png)

tinggal d sesuaikan

**Comment by totoprayogo1916** [comment]
jika terjawab, semestinya issue ini ditutup
