### ISSUE TITLE
Bug/error: Gagal Setting Telegram maupun Upload Gambar Profil

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#6554]
### Jelaskan error yg dialami

Jika ingin setting telegram menjadi YA atau TIDAK, maka akan diminta isi password lama dan password baru.
Padahal tidak ingin ganti password, hanya ingin hal lain di fitur tersebut.

Gambar di bawah,.

### Cara untuk mereplikasi errornya

Login halaman admin.
Klik Profil di sisi kanan atas, pilih Profil dan coba pilih Notofikasi Telegram menjadi Ya atau sebaliknya, atau ingin ganti gambar. dll

Maka ketika klik simpan, muncul required kolom password wajib diisi, (padahal tidak ingin ganti password).

### Hasil yg diharapkan

Bormal sebagaimana mestinya.

### Tangkapan layar dan log error

<img width="396" alt="2023-04-12_19h26_45" src="https://user-images.githubusercontent.com/46939846/231456713-eb205f5b-2af1-41f9-9f96-40a2d17f5042.png">

<img width="418" alt="2023-04-12_19h26_21" src="https://user-images.githubusercontent.com/46939846/231456721-ac51db09-cfb2-4017-8f99-4324e93b47e1.png">

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Semua

**Comment by andifahruddinakas** [comment]
Solusi : 
- [ ] 1. Pisahkan view ubah data dan password dan proses simpan.
- [ ] 2. Pastikan bisa digunakan untuk view ci3 dan blade.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/2257
