### ISSUE TITLE
gagal update identitas desa karena field kades yang di minta isi ter disable

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#6557]

**Comment by ariandii** [comment]
kode desa belum lengkap sehingga token dianggap tidak sesuai.

ingin pilih ulang identitas desa, diminta isi kades namun kolom disable karena mengisinya lewat menu pemerintahan desa.

ketika klik menu pemerintahan desa, diminta masukkan token premium nya.

begitu seterusnya.

**Comment by ariandii** [comment]
Hal ini bisa dikarenakan desa yang menggunakan versi lama, saat itu masih input manual mengenai kode desa.

sehingga saat update mengalami kendala di atas.

**Comment by andifahruddinakas** [comment]
Ini sama kasusnya dengan nomor_telpon sebelumnya, cuma ini versinya lebih jauh dimana field kepala desa masih perlu di isi.

Solusinya agar bisa digunakan adalah selalu cek kolom tsb, kalau ada perlu diisi (jika form isian tdk ada, isi data diisi kosong) jika tidak ada tidak perlu disimpan.

**Comment by andifahruddinakas** [comment]
Bisa di infokan versi berapa?

**Comment by ariandii** [comment]
versi terbaru

**Comment by andifahruddinakas** [comment]
> versi terbaru

Dr versi berapa? (Sebelum update)

**Comment by ariandii** [comment]
Juli 2019

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/2258
