### ISSUE TITLE
Bug/error: Mohon Koreksi Nama Daerah Camat / Wilayah di Surat Keterangan Untuk Nikah N1 sd N7

### ISSUE THREAD

**Issue by rsoeta** [OpenSID/OpenSID#6565]
### Jelaskan error yg dialami

Nama Daerah Camat / Wilayah di Surat Keterangan Untuk Nikah N1 sd N7 tidak sesuai daerah Camat setempat

### Cara untuk mereplikasi errornya

1. Pergi ke halaman Layanan Surat
2. klik tombol Cetak Surat
3. pilih Surat Keterangan Untuk Nikah N1 sd N7
4. Unduh RTF
5. error ada di dalam surat

### Hasil yg diharapkan

Lokasi Camat/Kecamatan sesuai setempat

### Tangkapan layar dan log error

![2023-04-20_01h21_20](https://user-images.githubusercontent.com/86590833/233167610-644eae9a-fb4c-4a89-bc47-8e0e195fea7a.png)
![2023-04-20_01h21_46](https://user-images.githubusercontent.com/86590833/233167595-939454f1-97a2-4cf1-ba7f-22609edb4361.png)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2304.0.2-premium

### Tema Yang Digunakan

Natra v22.11

**Comment by andifahruddinakas** [comment]
Dicek lg mas @vickyrolanda,

<img width="367" alt="image" src="https://user-images.githubusercontent.com/57283157/234443394-65fdce7d-88db-47bb-ae64-57bbb22c6920.png">

https://github.com/OpenSID/OpenSID/issues/6176

**Comment by rsoeta** [comment]
Siap

**Comment by vickyrolanda** [comment]
> Dicek lg mas @vickyrolanda,
> 
> <img alt="image" width="367" src="https://user-images.githubusercontent.com/57283157/234443394-65fdce7d-88db-47bb-ae64-57bbb22c6920.png">
> 
> #6176

Saya cek dari issue sudah terisi juga : 
<img width="719" alt="image" src="https://user-images.githubusercontent.com/59082428/234482686-28a9d6cb-53e9-4aa8-9e65-2b9c13fe9561.png">

namun ada beberapa kode isian tidak terisi apakah ini termasuk bug ? 
1. [form_istri_ke]
<img width="404" alt="image" src="https://user-images.githubusercontent.com/59082428/234482989-91eae236-457f-428a-a302-ae790e6d85dc.png">
2. 
<img width="540" alt="image" src="https://user-images.githubusercontent.com/59082428/234483050-4aef4fc0-6ba0-4257-ac08-e927745e4447.png">
3. [nip_pamong]
<img width="334" alt="image" src="https://user-images.githubusercontent.com/59082428/234483220-c71f6c3c-7fb8-467c-9e98-906cc0c5a131.png">

4. [form_pendidikan_wanita]
<img width="593" alt="image" src="https://user-images.githubusercontent.com/59082428/234483307-0cd1a919-e7f1-4eef-849e-00a269c9ae10.png">

5. [ACAPSFORM_NAMA_WANITAACAPS]	
<img width="331" alt="image" src="https://user-images.githubusercontent.com/59082428/234483375-268ff1c8-e9c5-42ad-b78e-788117846122.png">

6. 
<img width="476" alt="image" src="https://user-images.githubusercontent.com/59082428/234483650-a8eb896d-edc4-4e91-9c37-a754cee8f388.png">

7. 
<img width="492" alt="image" src="https://user-images.githubusercontent.com/59082428/234483720-d0992b25-270d-4557-9b21-37593714498e.png">

8. untuk nik pamong warnanya jadi putih ketika saya cari dengan keyword [ baru ketahuan
<img width="490" alt="image" src="https://user-images.githubusercontent.com/59082428/234483824-f5694dae-3f21-4cd9-a8ca-ca5f8ca72941.png">

**Comment by andifahruddinakas** [comment]
https://github.com/OpenSID/premium/commit/3281aae222f44d4adef8ccae888c3ca99a2a9d4b#commitcomment-95755018

<img width="682" alt="image" src="https://user-images.githubusercontent.com/57283157/234660822-376de157-2b67-453e-ac0d-f032e99a1fc6.png">

**Comment by andifahruddinakas** [comment]
> > Dicek lg mas @vickyrolanda,
> > <img alt="image" width="367" src="https://user-images.githubusercontent.com/57283157/234443394-65fdce7d-88db-47bb-ae64-57bbb22c6920.png">
> > #6176
> 
> Saya cek dari issue sudah terisi juga : <img alt="image" width="719" src="https://user-images.githubusercontent.com/59082428/234482686-28a9d6cb-53e9-4aa8-9e65-2b9c13fe9561.png">
> 
> namun ada beberapa kode isian tidak terisi apakah ini termasuk bug ?
> 
> 1. [form_istri_ke]
> 
> <img alt="image" width="404" src="https://user-images.githubusercontent.com/59082428/234482989-91eae236-457f-428a-a302-ae790e6d85dc.png">
> 
> 2.
> <img alt="image" width="540" src="https://user-images.githubusercontent.com/59082428/234483050-4aef4fc0-6ba0-4257-ac08-e927745e4447.png">
> 
> 3. [nip_pamong]
> <img alt="image" width="334" src="https://user-images.githubusercontent.com/59082428/234483220-c71f6c3c-7fb8-467c-9e98-906cc0c5a131.png">
> 
> 4. [form_pendidikan_wanita]
> 
> <img alt="image" width="593" src="https://user-images.githubusercontent.com/59082428/234483307-0cd1a919-e7f1-4eef-849e-00a269c9ae10.png">
> 
> 5. [ACAPSFORM_NAMA_WANITAACAPS]
> 
> <img alt="image" width="331" src="https://user-images.githubusercontent.com/59082428/234483375-268ff1c8-e9c5-42ad-b78e-788117846122.png">
> 
> 
> <img alt="image" width="476" src="https://user-images.githubusercontent.com/59082428/234483650-a8eb896d-edc4-4e91-9c37-a754cee8f388.png">
> 
> 
> <img alt="image" width="492" src="https://user-images.githubusercontent.com/59082428/234483720-d0992b25-270d-4557-9b21-37593714498e.png">
> 
> 8. untuk nik pamong warnanya jadi putih ketika saya cari dengan keyword [ baru ketahuan
> 
> <img alt="image" width="490" src="https://user-images.githubusercontent.com/59082428/234483824-f5694dae-3f21-4cd9-a8ca-ca5f8ca72941.png">

di cek terlebih dahulu alur yg seharusnya, untuk issue ini masalahnya ada di penanda tangan camat. Sudah diperbaiki namun masih salah.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/2268

**Comment by khoyarun** [comment]
saya minggu lalu cetak N ini hasil RTF nya koq Blank ya,
hanya string 'akhiran_qr'
