### ISSUE TITLE
Bug/error: Font Bookman Old Style tidak bisa justify

### ISSUE THREAD

**Issue by RomziJazz** [OpenSID/OpenSID#6567]
### Jelaskan error yg dialami

Font Bookman Old Style tidak bisa justify. Dan line spacingnya tidak teratur. 

### Cara untuk mereplikasi errornya

Cetak surat jadi tidak bagus formatnya. 

### Hasil yg diharapkan

Bisa justify dan line spacingnya bisa teratur. 

### Tangkapan layar dan log error

![IMG_20230424_160955](https://user-images.githubusercontent.com/65128302/233953375-54851b22-c306-4f93-9273-e2cbcb0fff08.jpg)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2305.01

**Comment by andifahruddinakas** [comment]
https://github.com/spipu/html2pdf/issues/421

**Comment by andifahruddinakas** [comment]
Solusi yang bisa dicoba : 
- [x] mecari font bookman old style yang support justify (sudah dilakukan namun hasilnya sama)
- [ ] Gali lebih dalam untuk kasus ini di https://stackoverflow.com/, atau langsung pada https://github.com/spipu/html2pdf
- [ ] gunakan library lain untuk konversi html ke pdf, lakukan ujicoba untuk fontbookman terlebih dahulu. (Contoh: https://github.com/dompdf/dompdf)

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2542
