### ISSUE TITLE
Fitur susulan di tampilan buku tamu & anjungan yang baru

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#6568]
1. Button kembali ke layanan mandiri dihilangkan atribut target="_blank"
<img width="889" alt="image" src="https://user-images.githubusercontent.com/59082428/234479380-43c4618b-3d0a-4e5a-b409-e8b5f98fc7d6.png">
2. Tambahkan validasi jika nomor hp kurang agar ketika di simpan tau ada yang masih belum memenuhi syarat inputan
<img width="613" alt="image" src="https://user-images.githubusercontent.com/59082428/234479609-87bd6f15-3a17-4672-9654-538087814a1d.png">
3. Foto hasil capture tidak tersimpan atau tidak ditampilkan sehingga hanya tampil icon mohon untuk di cek kembali 
<img width="443" alt="image" src="https://user-images.githubusercontent.com/59082428/234480199-67a7f280-c83e-4f79-aa55-0c6535b6cedb.png">
4. Notifikasi Inputan buku tamu dengan sweet alrt hilang mohon bisa di kembalikan agar bisa tau inputan berhasil atau tidak sehingga tidak menjadi inputan berulang.

**Comment by andifahruddinakas** [comment]
<img width="638" alt="image" src="https://user-images.githubusercontent.com/57283157/234490319-dfac84e5-abcf-4e35-9335-f6b144ff5b4c.png">

Saat tekan indeks kepuasan sebaiknya berada dihalaman yang sama (sama seperti sebelumnya)

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/2267
