### ISSUE TITLE
Judul Halaman Tidak Sesuai

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#6569]
Judul halaman menampilkan id dari surat, seharusnya menampilkan nama surat yang akan dicetak.

<img width="681" alt="image" src="https://user-images.githubusercontent.com/57283157/234667379-9365fe74-ce98-4220-9d9c-2dd509ed55a0.png">

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/2269
