### ISSUE TITLE
Tombol perbaiki arsip layanan membuat duplikasi tombol ubah

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#6570]
Buat surat tinymce dengan status masih konsep, tekan tombol perbaikan : 
<img width="541" alt="image" src="https://user-images.githubusercontent.com/57283157/234673389-cb8ff417-53af-4362-8ce7-7c758ef0faa4.png">

maka surat yang ada di permohonan surat akan pindah ke arsip. pada bagian arsip terjadi duplikasi dan status surat tersebut masih konsep.
<img width="530" alt="image" src="https://user-images.githubusercontent.com/57283157/234673906-df7e5727-9e07-4eb8-b3a6-f634c65b1b57.png">

Seharunya tombol ubah keterangan (untuk rtf) / ubah surat (untuk tinymce) hanya tampil pada saat masih permohonan dengna status konsep (tdk berlaku untuk rtf).

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/2270
