### ISSUE TITLE
Assets Sweetallert tidak terpanggil

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#6571]
Seteleh di cek, pada pengerjaan issue https://github.com/OpenSID/OpenSID/issues/6554 dilakukan pemisahan halaman. yang selama ini beberapa modul nebeng load asset pada bagian tsb. Sehingga setelah di pisah ke modul baru, assets sweetaller tidak terpanggil kembali.

Solusi : 
- Load assets sweetaller secara global karena digunakan dibanyak tempat.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/2271
