### ISSUE TITLE
Sediakan filter status, tahun dan wilayah pada statistik > penduduk > bantuan

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#6572]
Sediakan filter status, tahun dan wilayah pada statistik > penduduk > bantuan, seragamkan dengan bantuan sasaran penduduk dan keluarga.

Contoh : 
<img width="540" alt="image" src="https://user-images.githubusercontent.com/57283157/235064386-192d9367-ce50-4895-89e5-5151cffd2ecf.png">

<img width="539" alt="image" src="https://user-images.githubusercontent.com/57283157/235064418-9521a050-ef94-4dec-98c2-6018070801aa.png">

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/2272
