### ISSUE TITLE
TCPDF ERROR: Unable to create output file: /tmp/preview.pdf 

### ISSUE THREAD

**Issue by apidong** [OpenSID/OpenSID#6574]
pada server devpremium.opendesa.id terjadi error 

Severity: error --> Exception: TCPDF ERROR: Unable to create output file: /tmp/preview.pdf /home/devpremium.opendesa.id/public_html/vendor/tecnickcom/tcpdf/tcpdf.php 3004

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/2276
