### ISSUE TITLE
Bug/error: iframe tag pada artikel tidak render semestinya

### ISSUE THREAD

**Issue by mitchelldirks** [OpenSID/OpenSID#6578]
### Jelaskan error yg dialami

pada laman https://demosid.opendesa.id/index.php/artikel/2016/8/26/wilayah-desa terdapat tag html yang tidak tereksekusi. mungkin dikarenakan editor tinyMCE dimana artikel tersebut dibuat dengannya
![Cuplikan layar 2023-05-01 184417](https://user-images.githubusercontent.com/46508197/235447308-a1217728-df4a-4bad-9fd0-1c3b7e4e4bc2.jpeg)

### Cara untuk mereplikasi errornya

url error artikel https://demosid.opendesa.id/index.php/artikel/2016/8/26/wilayah-desa

mungkin gunakan <?php echo ... dari pada <?=

saya ingin berkontribusi namun nampaknya file berada di repo yang berbeda

### Hasil yg diharapkan

tag hasil editor pada konten artikel tereksekusi dengan benar

### Tangkapan layar dan log error

![Cuplikan layar 2023-05-01 184417](https://user-images.githubusercontent.com/46508197/235447290-090f9373-e8f4-4b03-9c8d-68a50e1c5d2c.jpeg)

### Rilis Versi OpenSID

Rilis Umum

### Versi OpenSID

0

### Informasi tambahan

semoga dapat membantu

**Comment by andifahruddinakas** [comment]
Silahkan cek di pembahasan https://forum.opendesa.id/d/292-iframe-tag-pada-artikel-tidak-render-semestinya
