### ISSUE TITLE
Bug/error: Paginasi tidak sesuai pada modul Grup Pengguna

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#6579]
### Jelaskan error yg dialami

TIdak bisa melakukan paginasi pada modul pengaturan grup

### Cara untuk mereplikasi errornya

1. Buka modul Pengaturan > Pengguna > Pengaturan Grup
2. Cek dan lakukan paginasi, maka paginasi tidak sesuai

### Hasil yg diharapkan

Bisa melakukan paginasi dengan benar

### Tangkapan layar dan log error

<img width="538" alt="image" src="https://user-images.githubusercontent.com/57283157/235566952-ffa83502-2946-4561-b060-f1daa4f318c1.png">

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v2305.0.0-premium

### Tema Yang Digunakan

bawaan

### Informasi tambahan

.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/2286
