### ISSUE TITLE
Bug/error: Salah menampilkan pilihan tipe persentase saat ubah data dokumnetasi pembangunan

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#6580]
### Jelaskan error yg dialami

Saat melakukan ubah data persentase pembangunan dengan jenis presentase digunakan adalah tulis manual, pada form yang ditampilkan adalah jenis presetnasenya adalah pilih persentase.

### Cara untuk mereplikasi errornya

1. Masuk ke modul Pembangunan
2. Siapkan data pembangunan
3. Masuk ke bagian dokumentasi data pembangunan yang dibuat sebelumnya
4. Tambahkan dokumentasi dengan jenis presentase adalah tulis manual, isi data lainnya dan simpan
5. Lakukan ubah data pada data tsb.
6. Maka data yang ditampilkan pada persentase pembangunan adalah pilih persentase.

### Hasil yg diharapkan

Saat ubah data dokumentasi pembangunan, data yang ditampilkan sesuai dengan seharusnya. Untuk kasus ini adalah peresentase pembangunan.

### Tangkapan layar dan log error

Kesalahan : 
<img width="743" alt="image" src="https://user-images.githubusercontent.com/57283157/235568327-68cf273b-432d-40f3-ae11-5dded4d2a4e1.png">

Seharusnya : 
<img width="739" alt="image" src="https://user-images.githubusercontent.com/57283157/235568369-6b7582d2-d707-41d4-ba34-fb016e0519c0.png">

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v2305.0.0-premium

### Tema Yang Digunakan

bawaan

### Informasi tambahan

https://berputar.opendesa.id/admin_pembangunan/dokumentasi_form/3

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/2287
