### ISSUE TITLE
Bug/error: Tidak bisa filter user grup admin yang aktif atau grup lainnya secara bersamaan

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#6582]
### Jelaskan error yg dialami

Tidak bisa melakukan filter berdsarkan status dan grup pengguna secara bersamaan.

### Cara untuk mereplikasi errornya

1. Masuk ke modul Pengaturan > Pengguna > Pengaturan Pengguna
2. Lakukan filter status dan grup, pilihan filter status dan grup digabung jadi 1 sehingga tdk bisa melakukan scr bersamaan.

### Hasil yg diharapkan

Bisa melakukan filter berdasarkan status dan grup.

### Tangkapan layar dan log error

<img width="745" alt="image" src="https://user-images.githubusercontent.com/57283157/235579289-dd65ff9b-d366-4b3d-8dfc-9de517928ba3.png">

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v2305.0.0-premium

### Tema Yang Digunakan

bawaan

### Informasi tambahan

SOLUSI : 
- [ ] Pisahkan filter berdsarkan status dan grup
- [ ] Default filter saat modul dibuka adalah status = aktif dan grup = semua

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/2288
