### ISSUE TITLE
Bug/error: Error load datatables pada halaman home

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#6583]
### Jelaskan error yg dialami

Terjadi error load datatables pada halaman home, padahal halaman tsb di menggunakan datatable.

### Cara untuk mereplikasi errornya

1. Masuk ke modul home
2. Klik kanan > inspect > Console
3. Lihat error datatbles

### Hasil yg diharapkan

Tidak adanya error tsb dan hanya panggil komponen datatables pada bagian yang diperlukan saja.

### Tangkapan layar dan log error

<img width="960" alt="image" src="https://user-images.githubusercontent.com/57283157/235580447-58e6f0d1-9fed-4f94-a053-5a1c3e3d3fff.png">

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v2305.0.0-premium

### Tema Yang Digunakan

bawaan

### Informasi tambahan

SOLUSI : 
- [ ] Untuk view blade, pada bagian footer > script.js dihapus (tdk diload scr global)
- [ ] Jika ada komponen yang diperlukan scr global dari script.js, pindahkan ke admin.js (terbaru, hanya menyimpan fuction yang diload global saja pada view blade)
- [ ] Pastikan tidak membuat error modul lain yang sudah menggunakan view blade.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/2291
