### ISSUE TITLE
Bug/error: Data apartur pada tampilan anjungan ada data statis

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#6584]
### Jelaskan error yg dialami

Data pemerintah desa pada halaman anjungan juga menambahkan data statis, sehingga tidak sesuai dengan data yang ada di admin.

### Cara untuk mereplikasi errornya

1. Pastikan sudah aktifkan lisensi anjungan, dan daftarkan gawai.
2. Masuk ke halaman anjungan > apartur desa
3. Maka tampil data lain selain yang sudah di input

### Hasil yg diharapkan

Hanya menampilkan data sesuai yang di input

### Tangkapan layar dan log error

<img width="741" alt="image" src="https://user-images.githubusercontent.com/57283157/235583205-fd1f6b3e-8e00-412e-81b6-828ab05525fe.png">

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v2305.0.0-premium

### Tema Yang Digunakan

bawaan

### Informasi tambahan

SOLUSI : 
- [ ] Hapus data statis yang ada pada view aparat anjungan

<img width="552" alt="image" src="https://user-images.githubusercontent.com/57283157/235583316-eb687aea-90df-478a-bbfb-3ceec775145b.png">

**Comment by andifahruddinakas** [comment]
Cek commit https://github.com/OpenSID/premium/commit/d1757f6a2a5bee6646a67e2ff710fdd7b65fd6b7#diff-07591bc5b07034611f6941dde448d9cbb719b8be90babe644b44842646c207dd

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/2290

**Comment by andifahruddinakas** [comment]
Perubahan pada versi : v2305.0.0
