### ISSUE TITLE
Bug/error: Bisa simpan data yang diubah tanpa nama pada apratur desa

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#6586]
### Jelaskan error yg dialami

Masih bisa menyimpan nama pada aparatur desa saat melakukan ubah data pada modul Buku Administrasi Umum - Buku Aparat Pemerintah Desa

### Cara untuk mereplikasi errornya

1. Masuk ke modul Buku Administrasi Umum - Buku Aparat Pemerintah Desa
2. Pilih salah 1 aparat yang ingin diubah
3. Lakukan hapus data pada input nama dan simpan
4. Data tersimpan, tanpa pemberitahuan harus di isi seperti saat tambah data.

### Hasil yg diharapkan

Tampilkan infromasi jika data perlu di isi

### Tangkapan layar dan log error

Data nama jadi kosong
<img width="521" alt="image" src="https://user-images.githubusercontent.com/57283157/235588403-7b7e11fa-4d5b-49a3-ac82-d25b339f2adb.png">

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v2305.0.0-premium

### Tema Yang Digunakan

bawaan

### Informasi tambahan

SOLUSI : 
- [ ] tambahkan class required berdsarkan jenis data yang dipilih (warga desa / luar)
- [ ] pastikan tidak bisa menyimpan jika inputan nama masih kosong

<img width="523" alt="image" src="https://user-images.githubusercontent.com/57283157/235588747-cc4280c3-e1d1-4180-98e8-611971538731.png">

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/2315
