### ISSUE TITLE
Tambahan Menu Master Data

### ISSUE THREAD

**Issue by bhien76** [OpenSID/OpenSID#659]
Bang @eddieridwan, saya usul agar di modul penduduk ditambahkan menu master data. isiannya hampir sama dengan kelompok. bedanya, tidak ada ketua. menu ini fungsinya untuk merekam macam-macam data yang diinput desa. contohnya data rumah yang belum memiliki IMB, data keluarga yang belum punya listrik PLN, dan sebagainya
![form master data](https://user-images.githubusercontent.com/28255642/31313232-a867d908-ac0f-11e7-9a17-e494934fefde.jpg)
![modul data](https://user-images.githubusercontent.com/28255642/31313233-b58d3376-ac0f-11e7-8f43-e77baa499b2c.jpg)

**Comment by eddieridwan** [comment]
Diterapkan sebagai modul _Data Suplemen_.

Sudah dicommit ke master.
