### ISSUE TITLE
Bug/error: Penanda tangan pada lampiran f2.01 tidak sesuai

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#6593]
### Jelaskan error yg dialami

Saat melakukan cetak surat kelahiran yang lampirannya menggunakan f2.01, penanda tangan yang ditampilkan tidak sesuai.

### Cara untuk mereplikasi errornya

1. Masuk ke modul Layanan Surat > Cetak Surat
2. Cari surat Surat Keterangan Kelahiran > dalan lakukan pengisian > Cetak
3. Hasil cetak terdapat 2 file yg dicompres.
4. Buka file lampiran f2.01 berupa pdf
5. Cek pada bagian penanda tangan tidak sesuai

### Hasil yg diharapkan

Penanda tangan yang ditampilkan seharusnya hanya menampilkan pejabat dukcapil saja.

<img width="942" alt="image" src="https://user-images.githubusercontent.com/57283157/235824117-4e66eb45-eb53-4bb3-9dd4-0efbfbfe476a.png">

[ttps://github.com/OpenSID/OpenSID/files/9526633/Formulir-F2-01.pdf](https://github.com/OpenSID/OpenSID/files/9526633/Formulir-F2-01.pdf)

### Tangkapan layar dan log error
<img width="648" alt="image" src="https://user-images.githubusercontent.com/57283157/235824261-650a6cda-f8b5-49d7-8dc4-c10e221b371d.png">

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v2305.0.0-premium

### Tema Yang Digunakan

bawaan

### Informasi tambahan

.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/2322
