### ISSUE TITLE
Bug/error: Arsip Layanan tidak tampil jika melakukan cetak surat yang sama yang telah dihapus

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#6594]
### Jelaskan error yg dialami

Data arsip layanan tidak tampil saat melakukan cetak ulang pada surat dengan data yg sama untuk kasus tinymce dan rtf.

### Cara untuk mereplikasi errornya

1. Lakukan cetak surat misalnya Surat Keterangan Domisili Usaha > cetak
2. Masuk ke arsip layanan > lakukan hapus data pada surat yang sudah dibuat sebelumnya
3. Lakukan langkah 1 kembali, maka pada arsip layanan tidak akan tampil

Catatan lain: 
- Untuk duplikasi gunakan nomor surat yang sama
- Jika mengalami kendala, bisa bertanya terlebih dahulu

### Hasil yg diharapkan

Data tampil walau melakukan cetak ulang dengan data yang sama pada arsip layanan

### Tangkapan layar dan log error

Untuk tinymce, unduh surat tidak tersedia.
Untuk rtf, data arsip tidak tersedia

<img width="719" alt="image" src="https://user-images.githubusercontent.com/57283157/235831552-f0baf232-d765-4551-a7c2-d8b06800d398.png">

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v2305.0.0-premium

### Tema Yang Digunakan

bawaan

### Informasi tambahan

Indikasi saat ini: 
- Terjadi karena menerapkan soft delete, sehingga jika melakukan delete tidak menghapus data pada database tsb, hanya menambahkan tanggal pada delete_at. Sedangkan cara saat ini, jika menemukan surat dengan data yang sama, maka data tsb akan di update.

Solusi sementara yang dilakukan adalah pada kolom delete_at dibuat jadi null

**Comment by andifahruddinakas** [comment]
Solusi : 
- [ ] Jangan menimpa data yang sudah dihapus sebelumnya

**Comment by pandigresik** [comment]
![image](https://github.com/OpenSID/OpenSID/assets/1853475/32ccb771-f61e-45c8-b53c-2fd0511f7184)
Saya coba replikasi gagal kondisi tersebut

**Comment by pandigresik** [comment]
![image](https://github.com/OpenSID/OpenSID/assets/1853475/66ab7918-374e-453c-8e55-74c2c0ffe731)
Surat yang baru masih bisa dibuka dengan normal

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2494
