### ISSUE TITLE
Opsi penangalan Hijri

### ISSUE THREAD

**Issue by kayangan** [OpenSID/OpenSID#660]
Mohon tambahkan opsi penanggalan hijri untuk cetak surat, karna ini sangat penting dimana di desa kami sudah harus menyertakan Tanggal hijri di setiap surat keluar
[hijri scrip, versi 1.zip](https://github.com/eddieridwan/OpenSID/files/1366927/hijri.scrip.versi.1.zip)

**Comment by kayangan** [comment]
new Stup seperti yang sudah saya request silahkan di coba mudah mudahan bermanfaat
[New Stup Penanggalan Hijri otomatis.zip](https://github.com/OpenSID/OpenSID/files/1418182/New.Stup.Penanggalan.Hijri.otomatis.zip)

**Comment by eddieridwan** [comment]
@kayangan apakah fitur ini masih diperlukan?

**Comment by eddieridwan** [comment]
Telah dicommit ke master melalui PR #1740
