### ISSUE TITLE
[TinyMCE] Permudah penambahan data pilihan manual

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#6600]
Saat ini masih menggunakan input manual, untuk mengurangi resiko kesalahan penulisan pada saat menambahkan pilihan, bisa gunakan element select2 tags. Yang nantinya jika disimpan akan berbentuk array.

**Comment by habibie11** [comment]
![image](https://github.com/OpenSID/OpenSID/assets/56639378/f4d11acd-609f-48dd-8a5a-a3e6ff18e9a7)

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2426
