### ISSUE TITLE
Penyesuaia Anjungan dan Buku Tamu Tampilan Baru

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#6602]
Setelah tampilan baru di konversi, ada beberapa perubahan kecil yang terlewat : 
- [x] space artikel terlalu besar (bisa tambahkan panjang karakter judul)
<img width="347" alt="image" src="https://user-images.githubusercontent.com/57283157/235845100-25188ba5-4bff-40a1-95dd-67bcc3004cbc.png">

- [x] Ganti kata layanan mandiri jadi Anjungan pada buku tamu
- [x]  Ganti Berkunjung -> Bertemu pada Registrasi buku tamu

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/2292

**Comment by andifahruddinakas** [comment]
Perubahan pada versi : v2305.0.0
