### ISSUE TITLE
Bug/error: Fungsi full screan pada anjungan akan kembali jadi exitfullscreen jika membuka halaman yang lain

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#6604]
### Jelaskan error yg dialami

Jika sudah di set menjadi fullscreen dan membuka halaman lain pada anjungan, maka tampilkan akan keluar dari mode fullscreen.

### Cara untuk mereplikasi errornya

1. Masuk ke halaman anjunga (pastikan sudah aktifkan anjungan + lisensi)
2. Klik tombol Full Screen
<img width="960" alt="image" src="https://user-images.githubusercontent.com/57283157/235845976-c299fcc3-b674-4211-95f4-b689c75ee601.png">

3. Lakukan navigasi dengan tombol lainnya (mis. menampilkan idm), maka akan keluar dari mode fullscreen. Padahal pada icon masih tertulis fullscreen
<img width="960" alt="image" src="https://user-images.githubusercontent.com/57283157/235846098-7cb6c0c5-f986-42fc-bafa-eb0e9c97e63a.png">

### Hasil yg diharapkan

Jika yang aktif masih full screen, aktifitas apapun seharusnya tidak mengubah mode tsb kecuali melakukan exitfullscreen.

Alternatif lain yang efeksti digunakan saat ini adalah menggunakan fullscreen bawaan browser.

### Tangkapan layar dan log error

<img width="960" alt="image" src="https://user-images.githubusercontent.com/57283157/235846343-6b3b58ca-b632-4311-90e7-248b3f1021c3.png">

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v2305.0.0-premium

### Tema Yang Digunakan

bawaan

### Informasi tambahan

.

**Comment by andifahruddinakas** [comment]
Perubahan pada versi : v2305.0.0

**Comment by pandigresik** [comment]
https://stackoverflow.com/questions/29281986/run-a-website-in-fullscreen-mode/30970886#30970886

You can't force a website to display in fullscreen mode.

Imagine the security concerns if that were possible.
Malicious websites could "Hijack" a less computer literate person's desktop for all kinds of dubious business.

All of JS fullscreen api's will throw a error like this:
"Failed to execute 'requestFullScreen' on 'Element': API can only be initiated by a user gesture." If you try to simply call it from your code.

**Comment by pandigresik** [comment]
Bagaimana kalau solusinya menggunakan extension dari chrome https://chrome.google.com/webstore/detail/full-screen-for-google-ch/gmimocjjppdelmhpcmpkhekmpoddgima?hl=id

**Comment by pandigresik** [comment]
demo menggunakan extension
https://youtu.be/mLMm_s97PIc

**Comment by andifahruddinakas** [comment]
Tidak ada solusi langsung untuk menjaga mode fullscreen tetap aktif saat membuka halaman melayang atau popup baru. Kebijakan keamanan browser yang diterapkan untuk melindungi pengguna membatasi kemampuan halaman web untuk mempertahankan mode fullscreen di luar kendali pengguna.

Namun, ada beberapa alternatif yang dapat Anda pertimbangkan:

1. Menggunakan modals atau dialog internal: Daripada membuka halaman melayang atau popup baru, Anda bisa menggunakan modals atau dialog internal di dalam halaman web Anda. Modals atau dialog ini biasanya diimplementasikan menggunakan HTML, CSS, dan JavaScript, dan mereka tetap berada dalam aliran dokumen utama. Dengan cara ini, Anda dapat menjaga mode fullscreen aktif karena halaman utama tidak berubah.

2. Mengoptimalkan tata letak halaman: Dalam beberapa kasus, mungkin Anda dapat mendesain ulang tata letak halaman Anda untuk menghindari ketergantungan yang berlebihan pada mode fullscreen. Pertimbangkan untuk mengatur konten Anda agar dapat ditampilkan dalam ukuran yang memadai tanpa harus memasuki mode fullscreen. Dengan demikian, Anda dapat meminimalkan ketergantungan pada mode fullscreen dan menghindari masalah saat membuka halaman melayang.

3. Menggunakan API semacam iframe: Jika Anda mengontrol konten di halaman melayang atau popup, Anda dapat memanfaatkan API seperti iframe untuk menanamkan konten tersebut dalam halaman utama Anda. Dengan menggunakan iframe, Anda dapat menampilkan konten tersebut dalam konteks halaman utama dan menjaga mode fullscreen tetap aktif.
