### ISSUE TITLE
Bug: masalah mengakses surat waktu https diaktifkan DAN index.php dihilangkan

### ISSUE THREAD

**Issue by kelbatuix** [OpenSID/OpenSID#661]
Mohon bantuan atau penjelasan tentang masalah ini. Kondisi yang terjadi adalah pada saat instal update sid 2.5 dan sid 2.5.1 semuanya lancar dan menu surat dapat dibuka. Namun ketika melakukan pengamanan dengan merubah/edit file htaccess sesuai panduan wiki opensid, maka halaman pada menu surat hilang. Jika file htaccess dikembalikan pada file asli halaman menu surat kembali bisa dibuka. Terima kasih atas perhatian dan bantuannya.
![screenshot 1](https://user-images.githubusercontent.com/25999158/31322490-a66d99fe-acc2-11e7-9d47-94a2d247fcfd.png)

**Comment by siayi** [comment]
@kelbatuix apakah Anda telah membaca [Panduan Konfigurasi Aplikasi](https://github.com/eddieridwan/OpenSID/wiki/Panduan-Konfigurasi-Aplikasi) ?

**Comment by kelbatuix** [comment]
Ya kami sudah baca semua. 
untuk diketahui bahwa hal ini pernah kami bahas bersama pengembang, yakni munculnya pesan akses tidak aman yang mengakibatkan web kami di blok oleh penyedia hosting secara otomatis karena terdeteksi sebagai malware atau program gangguan. kemudian pengembang memberikan solusi dengan mengikuti langkah membuat [akses aman (HTTPS) SSL](https://github.com/eddieridwan/OpenSID/wiki/Akses-Aman-%28HTTPS%29-SSL). pada versi dibawah 2.4 tidak terdapat permasalahan. namun pada versi 2.5 keatas menu surat hilang.
Jika panduan konfigurasi dikembalikan seperti yg anda berikan maka web akan kembali pada akses tidak aman dan dikhawatirkan web kami akan di blok kembali.

**Comment by siayi** [comment]
@kelbatuix 
boleh saya lihat file .htaccess nya 
dan apakah anda menggunakan 
https://www.kel-batuix.go.id/...
atau
http://www.kel-batuix.go.id/... pada akses browsernya?

**Comment by kelbatuix** [comment]
ini file nya, mohon dibantu. kami menggunakan https://www.kel-batuix.go.id
[htaccess.txt](https://github.com/eddieridwan/OpenSID/files/1367550/htaccess.txt)

**Comment by kelbatuix** [comment]
untuk nama pda cpnel sudah diganti menjadi .htaccess

**Comment by siayi** [comment]
@kelbatuix di paste saj di sini isi file .htaccess nya

**Comment by kelbatuix** [comment]
#============
# Untuk menghapus index.php dari url OpenSID, ubah nama file ini menjadi .htaccess,
# sehingga misalnya, modul Web bisa dipanggil dengan http://localhost/first.
# Untuk menggunakan fitur ini, pastikan konfigurasi apache di server SID
# mengizinkan penggunaan .htaccess
#============
RewriteEngine on
RewriteBase /
# Apabila menggunakan sub-domain atau sub-folder gunakan bentuk berikut
# RewriteBase /nama-sub-folder/

# Prevent index dirs
RewriteCond $1 ^(surat)
RewriteRule ^(.*)$ index.php/$1 [L,QSA]

# General dirs / files
RewriteCond $1 !^(index\.php|resources|robots\.txt)
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ index.php?/$1 [L,QSA]

# Redirect HTTPS
RewriteCond %{HTTPS} !on [OR]
RewriteCond %{HTTP_HOST} !^www\.
RewriteRule ^(.*) https://www.kel-batuix.go.id [L,R=301]

**Comment by batudaa** [comment]
Coba rename folder **surat**. Misalnya jadi **surat-x**. Trus cek apa menu surat sudah bisa dibuka atau tidak (tentu akan blank ketika klik item di Layanan Surat Administrasi Kependudukan).

**Sekedar saran** untuk bang @eddieridwan seharusnya hindari membuat public folder dengan nama yang sama dengan uri path controller. Saya cek ada controller **surat**. Nanti bikin kompleks .htaccess. Atau ada konfigurasi yang mesti disesuaikan jika me-rename folder surat tersebut?

**Comment by eddieridwan** [comment]
@kelbatuix : apakah anda sudah pastikan hosting anda mengizinkan penggunaan .htaccess? Jika tidak, maka akan error seperti yang anda alami.

**Comment by kelbatuix** [comment]
iya saya sudah konfirm utk penggunaan .htaccess dpt digunakan.

**Comment by eddieridwan** [comment]
@kelbatuix: apakah masih mengalami masalah? Apakah Cetak Surat sudah bisa diakses?

**Comment by eddieridwan** [comment]
Sepertinya masalah ini terjadi di mana index.php dihilangkan DAN https diaktifkan. 
https://www.kel-batuix.go.id/index.php/first saat ini hanya mengaktifkan https, tetapi tidak lagi menghilangkan index.php.

**Comment by ariandii** [comment]
Mohon bantuan untuk case ini, saya menggunakan OpenSID versi 19.02
pada saat https tidak diaktifkan, akses website opensid sedikit terhampat oleh iklan p01 sampai p05 .notifa.info

pada saat https diaktifkan, website opensid sudah lancar tanpa loading lama.
namun pada saat cetak surat, akses /surat hasilnya 403 forbiden. sedangkan akses index.php/surat normal.

Apakah memang begitu?

Mohon pencerahan.
