### ISSUE TITLE
Pemasangan OpenSID dengan Wizard

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#6618]
Pemasangan OpenSID menggunakana wizard pernah diterapkan namun terpisah dengan Aplikasi OpenSID itu sendiri.

Source : https://github.com/OpenSID/installer
Panduan : https://github.com/OpenSID/installer/wiki/Panduan-Installer-OpenSID

Pada repo tsb menggunakan versi lama sehingga perlu disesuaikan dan ditambahkan :
- [ ] Sesuaikan impor database menggunakan seeder
- [ ] Tambahkan halaman folder permisson untuk folder desa
- [ ] Tambahkan extention, php version, db version yg dibutuhkan.
- [ ] Sediakan pilih desa sebagai data awal config desa
- [ ] Sediakan config email
- [ ] Sediakan tambah data awal user & password
- [ ] Jika sudah selesai, tambahkan file .instalasi berisikan tgf instalasi

Wizard hanya ditampilkan jika dideteksi pada folder desa/.instalasi, belum tersedia (buka lg menggunakan session)

Untuk tampilan bisa modifikasi tampilan lama, atau menggunakan  https://github.com/rashidlaasri/LaravelInstaller

Mas @vickyrolanda, bisa ditambahkan kalau ada yg kurang

**Comment by andifahruddinakas** [comment]
Sebaiknya dibuat menjadi seebuah package

**Comment by vickyrolanda** [comment]
mas @yogiperdana ini tetap harus masuk rilis bulan ini mas.

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2475
