### ISSUE TITLE
Buat modul anjungan agar mudah dipisah/digabungkan ke versi umum

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#6619]
Saat ini cara yang digunakan kurang baik, karena harus mengingat controller, model dan view modul tsb terpisah. Salah 1 cara ang mungkin yang bisa dilakukan adalah, dengan membuat modul anjungan menjadi bentuk modules atau bentuk package yang nantinya mudah dipasang atau dilepas.

mas @vickyrolanda, bisa tambahkan kalau ada yang kurang

**Comment by andifahruddinakas** [comment]
Sebaiknya dibuat menjadi seebuah package modul2 tsb

**Comment by andifahruddinakas** [comment]
Buat jadi moduls tp dicommit untuk tahap awal.

**Comment by agungsugiarto** [comment]
dibuat modul dengan cara seperti apa mas? Seperti info layanan pelanggan atau yg lain?

**Comment by andifahruddinakas** [comment]
> dibuat modul dengan cara seperti apa mas? Seperti info layanan pelanggan atau yg lain?

Seperti prodeskel mas, tp dipush saja. Kedepannya, anjungan dilepas agar bisa digunakan di premium dan umum.

**Comment by agungsugiarto** [comment]
mas @andifahruddinakas, ini semua yang ada di layanan mandiri ya ?

**Comment by andifahruddinakas** [comment]
> mas @andifahruddinakas, ini semua yang ada di layanan mandiri ya ?

Yg anjungan terkait anjungan sj
