### ISSUE TITLE
Tambahkan migrasi bawaan pada setting_aplikasi dengan key warna_tema untuk OpenSID Update Bukan Install Baru

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#6626]
Saat ini migrasi setting_aplikasi dengan key warna_tema hanya jalan ketika install baru, namun ketika OpenSID database gabungan sudah terinstall maka migrasi tidak jalan sehingga tampilannya tema menjadi blank tidak berwarna, 
<img width="950" alt="image" src="https://user-images.githubusercontent.com/59082428/236753742-cb25cedf-279a-48f1-bd94-527b3a874c57.png">

Hasil yang diinginkan , tambahkan migrasi untuk update ketika update maka default akan terpasang Kode Warna bawaan  berdasarkan Config_id  dengan kode warna : #eab308

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2302
