### ISSUE TITLE
Bug/error: Seharusnya tertulis Peraturan ... (sesuai sebutan di pengaturan)

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#6627]
### Jelaskan error yg dialami

![Screenshot_20230508_212952_Chrome](https://user-images.githubusercontent.com/46939846/236851476-b44c5572-eefd-439c-ae0f-b22b7e55f1dc.png)

### Cara untuk mereplikasi errornya

https://berputar.opendesa.id/peraturan-desa

perhatikan pada pilihan kategori.

### Hasil yg diharapkan

sesuai sebutan pada pengaturan sebutan kepala desa di sistem.

### Tangkapan layar dan log error

di atas

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Rilis Mendatang

**Comment by andifahruddinakas** [comment]
Yang perlu disesuaikan adalah tulisan **pengaturan** agar mengikuti ubahan desa yang ada dipengaturan aplikasi. Contoh : 
- Pada admin tertulis : 
<img width="85" alt="image" src="https://user-images.githubusercontent.com/57283157/236985787-78cda12e-35f5-452a-88bc-32bc0970ace1.png">
- Pada halaman website : 
<img width="121" alt="image" src="https://user-images.githubusercontent.com/57283157/236985871-1735e00e-785b-4442-a305-df1514705a67.png">

Solusi : 
pada tabel ref_dokumentasi, untuk id = 3 perlu diubah agar bisa menyesuaian pengaturan aplikasi. Misalnya ganti data **Peraturan** tsb menjadi **Peraturan Di [desa]** agar bisa mengikuti pengaturan.

pada bagian admin juga perlu disesuaikan agar mengikuti pengaturan.
<img width="526" alt="image" src="https://user-images.githubusercontent.com/57283157/236986232-9b55956f-07a1-4185-b6a5-b83c16c989dc.png">

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/2314
