### ISSUE TITLE
Bug/error: Restore dari OpenSID lama dimana ada kata kata yang utf_general

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#6631]
### Jelaskan error yg dialami

Perlu di cari solusi terkait backup dan restore dari OpenSID lama dimana ada kata kata yang tidak perlu ikut terbackup lalu ketika restore akan selalu gagal.

![image](https://user-images.githubusercontent.com/59082428/236973732-9d0263b8-a072-4ffb-94f7-d300ffd7a557.png)

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

Ada dua masalah : 
(a) menyaring/membersihkan hasil backup Phpmyadmin yg menyebabkan restore di OpenSID gagal 
(b) mencegah munculnya tulisan collation di akhir output backup OpenSID bagi database lama (yg masih berisi collation non-standar)

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v2305.0.0

**Comment by andifahruddinakas** [comment]
mas @agungsugiarto, perbaikan yang perlu dilakukan : 
- [ ] buat 1 fuction untuk menghapus kalimat yang tidak diperlukan tsb. Saat ini dibuat masing2 function untuk restore dan update. Sehingga, jika ada perubahan di restore perlu juga menyesuai pada bagian backup.
Contoh : 
    - pada backup : 
        ```
        $backup .= $this->do_backup($prefs);
        $backup .= $tabel_foreign_key;
        $backup .= $create_views;
        // Hilangkan ketentuan user dan baris-baris lain yang
        // dihasilkan oleh dbutil->backup untuk view karena bermasalah
        // pada waktu import dgn restore ataupun phpmyadmin
        $backup = preg_replace('/ALGORITHM=UNDEFINED DEFINER=.+SQL SECURITY DEFINER /', '', $backup);
        $backup = preg_replace('/COLLATE=utf8_general_ci|COLLATE=cp850_general_ci|COLLATE=utf8mb4_general_ci|COLLATE=utf8mb4_unicode_ci|utf8_general_ci;/', '', $backup);
        $db_name = 'backup-on-' . date('Y-m-d-H-i-s') . '.sql';```

   - pada restore : 
        ```
        $sql_line = trim($sql_line);
        $sql_line = preg_replace('/ALGORITHM=UNDEFINED DEFINER=.* SQL SECURITY DEFINER /', '', $sql_line);
        $sql_line = preg_replace('/utf8_general_ci;|utf8mb4_general_ci;|utf8mb4_unicode_ci;/', '', $sql_line);```

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2344
