### ISSUE TITLE
Bug/error: timeout ketika cetak/unduh data penduduk jika jumlah penduduk cukup besar pada modul penduduk

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#6636]
### Jelaskan error yg dialami

Terjadi timeout jika melakukan cetak data dengan jumlah penduduk cukup besar, contoh 4000 data.

### Cara untuk mereplikasi errornya

1. Menu penduduk
2. klik cetak/unduh data penduduk coba dengan 4000 data

### Hasil yg diharapkan

Tidak terjadi timeout/loading yang lama saat cetak/unduh data.

Bisa dengan cara, data yang di cetak hanya pada halaman yg di akses saja atau hanya pada data yg di ceklist saja..

### Tangkapan layar dan log error

<img width="683" alt="image" src="https://user-images.githubusercontent.com/57283157/237035194-0b1b54a7-42b8-41b8-bc91-287e7b3f1865.png">

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v2305.0.0-premium

### Tema Yang Digunakan

bawaan

### Informasi tambahan

.

**Comment by vickyrolanda** [comment]
mas akas issue ini sebenrnya sudah ada saya buat https://github.com/OpenSID/OpenSID/issues/6595 maksudnya jadi fitur tidak karena perubahan konsep, cetak dan ini perlu dibuat 1 contoh dan trs akan diterapkan kesemua fungsi cetak.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/2308

**Comment by MUHAMMADRANGSEL** [comment]
saat ini untuk cetak dan unduh data terbatas hanya sampai 100, sekedar usul apakah bisa ditambah pilihan 300, 500, 1000, supaya bisa mempermudah bagi desa, ini untuk mengantisifasi jika ada permintaan data berdasarkan RT, dan Dusun
