### ISSUE TITLE
Bug/error: timeout ketika cetak/unduh data penduduk jika calon pemilih cukup besar

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#6638]
### Jelaskan error yg dialami

Terjadi timeout jika melakukan cetak/unduh data dengan jumlah calon pemilih cukup besar, contoh 4000 data.

### Cara untuk mereplikasi errornya

1. Menu Calon Pemilih
2. klik cetak/unduh data calon pemilih coba dengan 4000 data

### Hasil yg diharapkan

Tidak terjadi timeout/loading yang lama saat cetak/unduh data.

Bisa dengan cara, data yang di cetak hanya pada halaman yg di akses saja atau hanya pada data yg di ceklist saja..

### Tangkapan layar dan log error

<img width="683" alt="image" src="https://user-images.githubusercontent.com/57283157/237036868-34fd010f-54b1-416d-a098-f6b0cb8445a9.png">

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v2305.0.0-premium

### Tema Yang Digunakan

bawaan

### Informasi tambahan

.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/2309
