### ISSUE TITLE
Bug/error: Nama modul salah dan ukuran kurang besar

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#6641]
### Jelaskan error yg dialami

Penamaan modul salah, yang dimana harusnya Klasifikasi Surat tapi tertulis Klasfikasi Surat. Dan ukuran tampilannya tidak full, sehingga paginasi menjadi dempet.

### Cara untuk mereplikasi errornya

1. Masuk ke modul Sekretariat > Klasifikasi Surat
2. Perhatikan nama dan tampilan modul tsb

### Hasil yg diharapkan

1. Nama modul sesuai yakni Klasifikasi Surat
2. Ukuran lebih besar lagi

### Tangkapan layar dan log error

<img width="681" alt="image" src="https://user-images.githubusercontent.com/57283157/237042761-09af17e4-6e42-489c-bbe1-74e7bd89772f.png">

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v2305.0.0-premium

### Tema Yang Digunakan

bawaan

### Informasi tambahan

Catatan : 
- Hanya update nama modul jika nama modul belum diubah.

**Comment by agungsugiarto** [comment]
issuenya perlu do close mas @andifahruddinakas  sudah diselesaikan https://github.com/OpenSID/premium/pull/2343
