### ISSUE TITLE
Permintaan fitur: Penambahan Asuransi

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/OpenSID#6644]
### Apa kekurangan yg ingin diatasi?

pada kota bima terdapat tambahan jenis asuransi sehingga perlu ditambahkan yaitu BPJS Bantuan Daerah.

### Jelaskan solusi yg diinginkan

-

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

v2305.0.0-premium

**Comment by andifahruddinakas** [comment]
Solusi : 
- [x] tambahkan data pada tabel **tweb_penduduk_asusransi** sbb `id : 4, nama : BPJS Bantuan Daerah` melalui migrasi
- [x] pada file impor penduduk tambahkan id : 4 pada baris berikut https://github.com/OpenSID/premium/blob/5a98e0ef88b8b112890938bc7bb23a0c669d4702/donjo-app/models/Impor_model.php#L273 atau buat dinamis mengikuti data yang ada pada tabel
- [x] pada contoh file impor penduduk, tambahkan informasi data yang ditambahkan di atas
- [x] untuk testing, coba lakukan impor penduduk dengan id asusransi 4
- [x] tambahkan migrasi

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2325
