### ISSUE TITLE
Performa untuk Wilayah Dusun

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/OpenSID#6645]
### Jelaskan error yg dialami

pada WIlayah administratif masih terasa lambat dalam membuka halamannya

### Cara untuk mereplikasi errornya

1. Masuk ke Modul Info Desa
2. Klik Menu Wilayah Administratif

### Hasil yg diharapkan

akses ke halaman administratif lebih cepat.

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v2305.0.0-premium

### Informasi tambahan

Solusi :
1. Data Wilayah administrasi diletakan di cache
2. Cache dihapus atau diperbaharui jika ada perubahan pada data wilayah, penduduk, dan KK.

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2351
