### ISSUE TITLE
Bug/error: Sering terjadi gagal menampilkan peta karena format path yg tidak valid

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#6651]
### Jelaskan error yg dialami

Sering terjadi gagal menampilkan peta wilayah jika format path tidak sesuai, bisa berasal dari ubah manual dari database, migrasi perubahan jenis peta dari polygon menjadi multypoligon yg tdk sempurna, atau hasil impor shp.

### Cara untuk mereplikasi errornya

1. Lakukan impor database bermasalah
2. Masuk modul Info Desa > Identitas Desa
3. Lakukan ubah peta wilayah desa
4. Tidak ada tools yang tampil, karena adanya wilayah dusun bermasalah (tdk sesuai)

### Hasil yg diharapkan

Adanya notifikasi dusun mana yang bermasalah tsb, agar mudah di cek.

### Tangkapan layar dan log error

<img width="531" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/1c62cec4-7ca7-444a-ba97-b6d5875c1277">

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v2305.0.0-premium

### Tema Yang Digunakan

bawaan

### Informasi tambahan

Solusi sementara yang dilakukan : 
1. Mengecek setiap path peta wilayah dengan isian berbeda (tdk seharusnya), contoh ygn bermasalah adalah : 
`[[[[-5.108730440441282,105.01993536963712],[-5.109061119350546,105.01997470859352],[-5.109212655750112,105.01950517304068],[-5.1090139218654835,105.01865118741992],[-5.1091161831059235,105.01863747834251],[-5.109169168837758,105.01857638384537],[-5.109224974581938,105.01851871610599],[-5.109271875203339,105.01845449206485],[-5.10933198511389,105.01834452149525],[-5.1093811118842885,105.01822650454415],[-5.109536655534085,105.01710772510708],[-5.1087144111988305,105.0171732902527],[-5.108641388690698,105.01687943939034],[-5.108006745838753,105.01709878430121],[-5.1077490887590065,105.01694977288938],[-5.106684620537826,105.01628756537684],[-5.105989717064773,105.01596033587705],[-5.105643304020201,105.0157350303198],[-5.104530150073429,105.01507937919088],[-5.1037500508944795,105.0146377085548],[-5.102638674891808,105.013801753521],[-5.102267028363762,105.0134912133399],[-5.102109405071978,105.01336425550109],[-5.1019063648424385,105.01321971416473],[-5.1018309668279995,105.01327484842479],[-5.1015272969641625,105.01296579848714],[-5.10126904374094,105.01330822722595],[-5.100973685059017,105.0130611658824],[-5.100787267696838,105.01353681089314],[-5.100570869027908,105.01391232015523],[-5.100027052284979,105.01468628643126],[-5.100615540225828,105.01501420692722],[-5.101047450549647,105.01524865630928],[-5.102124656148192,105.01609163201329],[-5.102313335872871,105.01623928495974],[-5.102634519015644,105.01658916458838],[-5.103047980249791,105.0168457030044],[-5.10321811045526,105.01695126296909],[-5.103444954444377,105.01711337749079],[-5.10421520149515,105.01766383655195],[-5.104996848814128,105.01799700420494],[-5.106909421098307,105.01868113491705],[-5.107394577242254,105.01879086657432],[-5.107526755867422,105.01882076248877],[-5.107681409420645,105.0188779830569],[-5.10782418939199,105.0189748406956],[-5.1080934228880555,105.01914888616739],[-5.108214830400614,105.01950770611077],[-5.108363843828309,105.01977890733544],[-5.108445771497617,105.019848942884],[-5.1085479139509165,105.01987995378117]]],[[]]]`

2. Masuk ke admin, buka ubah peta wilayah pada wilayah yang bermasalah tsb dan gunakan fungsi kosongkan peta. Dan membuat ulang kembali petanya.
<img width="364" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/a6df7940-3177-492b-ab19-ae617e7fde4d">

**Comment by andifahruddinakas** [comment]
Error onsole : 
<img width="439" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/80f696fe-18b0-4274-b1cf-3e6d5628b8f8">

**Comment by andifahruddinakas** [comment]
Perbaikan yang diperlukan : 
- [ ] Sediakan notifikasi saat menampilkan peta jika terdapat path yg tdk sesuai.
- [ ] Jangan tampilkan path yg bermasalah tsb pada peta.

**Comment by andifahruddinakas** [comment]
https://drive.google.com/drive/folders/1xBNyeeU8TSU3kZJzoBCp9UeISESLwycq

**Comment by pandigresik** [comment]
![image](https://github.com/OpenSID/OpenSID/assets/1853475/25ea441e-340a-4712-b3e0-40862a7e5198)

Menambahkan notifikasi path wilayah yang tidak valid

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2402
