### ISSUE TITLE
Permintaan fitur: Pengaturan Surat

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/OpenSID#6652]
### Apa kekurangan yg ingin diatasi?

Pada halaman pengaturan surat masih terasa lambat

### Jelaskan solusi yg diinginkan

-

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

v2305.0.0-premium

### Informasi tambahan

-

**Comment by andifahruddinakas** [comment]
Bagian yang perlu di sesuaikan : 
<img width="541" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/d39689a4-c7c1-490f-a940-b66216b19767">

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/2318
