### ISSUE TITLE
Bug/error: Perhatikan icon baterai di bawah ini.

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#6654]
### Jelaskan error yg dialami

<img width="523" alt="Cuplikan layar 2023-05-12 122029" src="https://github.com/OpenSID/OpenSID/assets/46939846/c5b0edd0-59d5-45bb-bfb6-d1ce7c65c865">
<img width="532" alt="Cuplikan layar 2023-05-12 122016" src="https://github.com/OpenSID/OpenSID/assets/46939846/b4d6931e-366c-4017-8d63-cb1f70407d6b">
<img width="541" alt="Cuplikan layar 2023-05-12 122000" src="https://github.com/OpenSID/OpenSID/assets/46939846/fef1c972-8f1c-475d-bcee-3a3d34c2f0fb">
<img width="528" alt="Cuplikan layar 2023-05-12 121945" src="https://github.com/OpenSID/OpenSID/assets/46939846/77f204b4-6d0c-40e2-a9d6-c2c67fc70ad1">
<img width="594" alt="Cuplikan layar 2023-05-12 121927" src="https://github.com/OpenSID/OpenSID/assets/46939846/b20c5e66-08a0-491c-8ba2-77c367a2db5d">
<img width="384" alt="Cuplikan layar 2023-05-12 121911" src="https://github.com/OpenSID/OpenSID/assets/46939846/a4f80573-ce5a-475a-b070-6be67307f78d">

### Cara untuk mereplikasi errornya

buka beberapa menu dan perhatikan batrainya.

### Hasil yg diharapkan

seragam, agar tidak ada pembeda antara batrai bertanda seru dan batrai polos.

### Tangkapan layar dan log error

di atas

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Seluruhnya

**Comment by andifahruddinakas** [comment]
Solusi :
Gunaakan 1 view header untuk tampilan bawaan ci3 dan blade

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/2320
