### ISSUE TITLE
Bug/error: Install baru v2305.0.1-premium masih ada data palsu

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#6655]
### Jelaskan error yg dialami

<img width="960" alt="image" src="https://github.com/OpenSID/OpenSID/assets/46939846/a8740b7a-ddde-4e24-a7c8-444625711fcb">

### Cara untuk mereplikasi errornya

buka halaman pengguna dan edit admin.
maka masih ada hp 123 dan email bukan email desa.

### Hasil yg diharapkan

sebaiknya dikosongkan saja, agar benar benar bersih tanpa contoh data awal.

### Tangkapan layar dan log error

di atas

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Seluruhnya

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2327

**Comment by andifahruddinakas** [comment]
Penyesuaian ulang untuk database gabungan melalui commit https://github.com/OpenSID/premium/commit/c365de2938d5786699911df6342a093f8350a907
