### ISSUE TITLE
Bug/error: Masalah simpan nama melalui halaman profil gagal bila ada tanda baca.

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#6656]
### Jelaskan error yg dialami

<img width="727" alt="2023-05-12_12h54_18" src="https://github.com/OpenSID/OpenSID/assets/46939846/587e729b-0efd-4620-b1b1-c1e4c42ece40">

### Cara untuk mereplikasi errornya

buat nama pengguna menggunakan tanda baca di menu Pengaturan -> Pengguna, lalu simpan

maka akan sukses tersimpan dengan nama bertanda baca misal Abdul, S.H.

namun, ketika dibuka melalui klik Profil seperti gambar di atas, lalu simpan, tanda baca akan hilang. (tidak tersimpan jika di isi melalui halaman profil)

### Hasil yg diharapkan

Samakan hasil simpan di Pengguna dan Profil

### Tangkapan layar dan log error

di atas

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Seluruhnya

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2330
