### ISSUE TITLE
Bug/error: Tampil nama tidak sesuai seharusnya

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#6657]
### Jelaskan error yg dialami

<img width="716" alt="image" src="https://github.com/OpenSID/OpenSID/assets/46939846/33b7b02b-69b6-4597-a31d-61ee26865449">

### Cara untuk mereplikasi errornya

perhatikan gambar di atas, buka halaman Pengaturan Pengguna dan lihat pada nama di pojok kanan atas juga termasuk jika diklik. nama akan berbeda.

### Hasil yg diharapkan

seharusnya sama 100% termasuk ejaan yg diketik pada Pengaturan Pengguna.

### Tangkapan layar dan log error

di atas

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Semua

**Comment by ariandii** [comment]
info tambahan, nama pada pojok kanan atas akan sesuai jika sudah logout dan login.

apakah betul begitu? atau bisa dibuat otomatis juga ikut berubah.

**Comment by andifahruddinakas** [comment]
> info tambahan, nama pada pojok kanan atas akan sesuai jika sudah logout dan login.
> 
> apakah betul begitu? atau bisa dibuat otomatis juga ikut berubah.

Ya, karena kalau logout sessionnya ke hapus. Pas login lg akakan di set ulang sesuai dataa baru.

**Comment by ariandii** [comment]
https://github.com/OpenSID/OpenSID/issues/6656

issue di link atas sudah saya edit agar khusus membahas simpan di halaman profil.

issue ini bisa diclose ya pak, jika masalah session saja. (berbeda tidak masalah kalau tidak logout dulu)
