### ISSUE TITLE
Bug/error: Data Tidak Sama

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#6658]
### Jelaskan error yg dialami

Nama yang ditampilkan pada Pengaturan Pengguna dan Profil berbeda walau sudah diubah. dengan username yang sama,

### Cara untuk mereplikasi errornya

<img width="960" alt="image" src="https://github.com/OpenSID/OpenSID/assets/46939846/5c019326-39fe-456d-b711-31e2dc0c2829">

### Hasil yg diharapkan

perhatikan pada gambar di atas, nama sudah berhasil berubah namun pada pojok kanan atas tetap nama lama.

jika di klik priofil juga tampil nama lama.

seharusnya sama, karena username yg sama

### Tangkapan layar dan log error

di atas

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Semua

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/2321
