### ISSUE TITLE
Peta: pada saat centang wilayah administratif, semua wilayah administratif (dusun, rw, rt) muncul

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#666]
pada saat centang wilayah administratif, semua wilayah administratif (dusun, rw, rt) muncul di menu peta

**Comment by eddieridwan** [comment]
<img width="1222" alt="wilayah-di-peta" src="https://user-images.githubusercontent.com/249563/35467202-be6fd442-035f-11e8-8ba0-63e50ae41a71.png">

**Comment by budiantoip** [comment]
Ok, saya akan pelajari issue ini terlebih dahulu

**Comment by eddieridwan** [comment]
Editing polygon untuk wilayah ada di menu Plan > Tipe Polygon --- untuk nantinya ditampilkan di Peta. Data polygon wilayah disimpan di database. Tapi fitur ini masih perlu dikembangkan. Silakan pelajari.

**Comment by eddieridwan** [comment]
Peta sekarang bisa menampilkan desa, dusun, rw, rt secara tersendiri.
