### ISSUE TITLE
Bug/error: Kolom Tidak Bisa diedit

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#6660]
### Jelaskan error yg dialami

<img width="536" alt="image" src="https://github.com/OpenSID/OpenSID/assets/46939846/27c3953d-5e5c-4463-be82-31d16ba011dc">

### Cara untuk mereplikasi errornya

buka menu Layanan Mandiri -> Kotak Masuk
dan klik aksi salah satu pesan untuk lihat detil pesan.

perhatikan seluruh kolom tidak bisa diedit, namun hanya 1 yang berwarne berbeda yaitu kolom "Pesan"

### Hasil yg diharapkan

jika seluruh kolom tidak dapat di edit, sebaiknya pula Pengirim, NIK, dan Subjek juga diberi warna abu abu seperti kolom pesan.
menandakan tidak dapat diedit. (readonly)

### Tangkapan layar dan log error

di atas

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Seluruhnya

**Comment by ariandii** [comment]
Begitu juga dengan kolom yang ada di kotak keluar.

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2336
