### ISSUE TITLE
Bug/error: Cek Gagal Akses API IDM tersimpan ke cache

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#6662]
### Jelaskan error yg dialami

apakah link API IDM masih di aktif?

atau ganti lagi ke URL lain.

### Cara untuk mereplikasi errornya

akses idm

### Hasil yg diharapkan

pernah terjadi perubahan sumber link API IDM di masa lalu.

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Seluruhnya

**Comment by andifahruddinakas** [comment]
API tsb sudah tidak aktif lg sesuai issue https://github.com/OpenSID/OpenSID/issues/5890, API yang aktif saat ini https://idm.kemendesa.go.id/open/api/desa/rumusan/6201022016/2022

Perbaiki tsb akan masuk diversi 2306.0.0, https://github.com/OpenSID/OpenSID/wiki/Rilis-Umum-Yang-Akan-Datang

**Comment by ariandii** [comment]
bisa di tes install baru 2305.0.1-premium dan buka idm apakah bisa?

**Comment by andifahruddinakas** [comment]
> bisa di tes install baru 2305.0.1-premium dan buka idm apakah bisa?

Umum 2305.0.1 masih dalam penyesuaian cherry-pick. Namun di umum yg akan datang perubahan url idm akan masuk did versi 2306.0.0

**Comment by ariandii** [comment]
yang saya tanyakan sejak awal di premium

**Comment by ariandii** [comment]
info tambahan, 
sesuai judul adalah koneksi IDM, bukan SDGs.

bisa coba dibuka apakah sukses tampil info IDM, jika belum memiliki file json IDM di folder desa/cache.

**Comment by andifahruddinakas** [comment]
> info tambahan, sesuai judul adalah koneksi IDM, bukan SDGs.
> 
> bisa coba dibuka apakah sukses tampil info IDM, jika belum memiliki file json IDM di folder desa/cache.

dari website tidak bisa menampilkan data idm dari desa, https://idm.kemendesa.go.id/rekomendasi.

<img width="614" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/030804f4-1fb2-4fce-a20e-e2971c8ef5b4">

jika dilakukan pengecekan langsung dari API yang disediakan, semua kode desa yang dimasukkan tidak ditemukan.
<img width="295" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/9354372e-04c5-49dc-a266-f0a2ae6330c4">

sampai saat ini belum ada info mengenai API IDM yang bisa digunakan.

**Comment by ariandii** [comment]
Info tambahan Penting:
dampak fatal saat ini adalah, desa yang sudah memiliki cache idm, akan direset ketika membuka web idm.

yang semula idm bisa tampil (file cache ada isinya), ketika akses web idm saat ini, isi file json menjadi kosong otomatis.

===
harapannya, file json yg sudah ada tidak terpengaruh ketika web kemendesa down.

**Comment by andifahruddinakas** [comment]
Solusi : 
1. Jangan simpan response error pada cache, hanya tampilkan saja. Untuk pesan : `Tidak dapat mengambil data IDM.`, Periksa koneksi internet Anda.'
2. Cek terlebih dahulu apakah sudah pernah ada cache atau belum. Jika sudah ada gunakan cache tsb.
3. Jika belum ada, akses API IDM. Jika ada respose dari server, simpan sebagai cache.
4. Jika tidak ada response dari cache, tampilkan pesan `Tidak dapat mengambil data IDM.` dan url API IDM + kode desanya.

**Comment by andifahruddinakas** [comment]
Yang membuat bermasalah pada script berikut : 
```
return get_instance()->cache->pakai_cache(static function () use ($kode_desa, $tahun) {
        if (! cek_koneksi_internet()) {
            return (object) ['error_msg' => 'Periksa koneksi internet Anda.'];
        }

        try {
            $client   = new \GuzzleHttp\Client();
            $response = $client->get(config_item('api_idm') . "/{$kode_desa}/{$tahun}", [
                'headers' => [
                    'X-Requested-With' => 'XMLHttpRequest',
                ],
                'verify' => false,
            ]);

            return json_decode($response->getBody()->getContents())->mapData;
        } catch (Exception $e) {
            log_message('error', $e->getMessage());

            return (object) ['error_msg' => 'Tidak dapat mengambil data IDM.'];
        }
    }, $cache, 604800);
```

penggunaan fuction pakai_cache jg menangkap respose gagal (trycatch dan cek koneksi), sehingga response tsb tersimpan di cache.

**Comment by andifahruddinakas** [comment]
Untuk uji coba, bisa gunakan cache idm berikut : 
[idm_2022_6303052054.zip](https://github.com/OpenSID/OpenSID/files/11479968/idm_2022_6303052054.zip)

**Comment by ariandii** [comment]
Isi file IDM dengan format lain. yang sempat terekam bulan lalu.
Untuk ujicoba selain file di atas:
[idm_2022_6201022016.zip](https://github.com/OpenSID/OpenSID/files/11480854/idm_2022_6201022016.zip)

**Comment by andifahruddinakas** [comment]
SOLUSI : 
- [ ] sesuaikan ambil data idm dengan alur berikut : 
1. cek apakah ada cache, jika ada gunakan cache tsb, jika tdk lanjut point 2
2. cek apakah ada koneksi, jika ada lanjut point 3, jika tidak tampilkan notif koneksi
3. cek apakah server idm bisa diakses, jika bisa lanjut point 4, jika tidak tampilkan notif gagal akses
4. cek apakah respose sukses dan ada data dari server idm, jika ada simpan ke cache, jika tidak tampilkan notif gagal / notif sesuai dari response server idm

*catatan : 
- Hanya simpan cache idm jika belum ada cache dan ada respose sukses dari server idm. selain itu tampilkan notif (notif tdk disimpan di cache)

**Comment by ariandii** [comment]
informasi, sore ini web idm sudah bisa diakses.

<img width="960" alt="image" src="https://github.com/OpenSID/OpenSID/assets/46939846/28733f03-a8a5-44fa-a846-6ef9204af5c5">

**Comment by andifahruddinakas** [comment]
> informasi, sore ini web idm sudah bisa diakses.
> 
> <img width="960" alt="image" src="https://github.com/OpenSID/OpenSID/assets/46939846/28733f03-a8a5-44fa-a846-6ef9204af5c5">
> 
> 

Ya, sy akses API nya sudah bisa. Namun issue ini masih diperlukan.

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2334

**Comment by ariandii** [comment]
masih terjadi upload backup json idm ke folder desa/cache.
ketika membuka web idm 2022, maka isi json kembali terbarukan sehingga data menjadi hilang kembali.
