### ISSUE TITLE
Bug/error: Penggunaan pengaturan sebutan_desa, sebutan_kepala_desa tidak sesuai pada modul Bumindes

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#6663]
### Jelaskan error yg dialami

![IMG_20230515_130733_506](https://github.com/OpenSID/OpenSID/assets/46939846/cb1e43b2-e860-4f3d-b129-91deb1750406)

![IMG_20230515_131054_550](https://github.com/OpenSID/OpenSID/assets/46939846/0bda27ac-1cdb-43a3-a3d1-fd508cb05c22)

### Cara untuk mereplikasi errornya

perhatikan hasilnya pada menu buku administrasi umum, dan pada halaman tambah data.

### Hasil yg diharapkan

disesuaikan sebutam sesuai yg ditentukan.

### Tangkapan layar dan log error

di atas

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Rilis Mendatang

### Informasi tambahan
Info Tambahan,
1. di sebutan desa di pengaturan -> aplikasi, sudah diubah kalurahan
2. di sebutan pemerintah desa sudah diubah pemerintah kalurahan
3. di sebutan jabatan sudah diubah kepala kalurahan

**Comment by ariandii** [comment]
Info tambahan:
pada Buku Aparat Pemerintah Desa sudah bisa disesuaikan pada menu Pemerintah desa di kolom Sebutan Pemerintah Desa.

namun yang lain. Buku Keputusan, dan Lembaran Desa masih belum menjadi Kelurahan.

ini jiga berdampak tampil pada Web Publik halaman tersebut.

**Comment by andifahruddinakas** [comment]
SOLUSI : 
- [x] Untuk tombol tambah data dibuat umum saja **Tambah**
<img width="108" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/59eca4a6-41aa-4423-9577-1964249030fb">

- [x] Buat konsisten penggunaan pengaturan sebutan_kepala_desa dan sebutan_desa pada navigasi buku lembaran desa dan  berita kelurahan
<img width="112" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/c1b32b41-3bf6-44c8-b99a-2c9dc238e0df">

- [x] Buat konsisten penggunaan pengaturan sebutan_kepala_desa dan sebutan_desa pada breadcrumb.
<img width="541" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/e3a021d2-59ed-472b-9145-e582c7f0a1f8">
<img width="532" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/0966544c-e859-45da-be33-025d19a5cb2a">
<img width="534" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/a4fae14c-025f-4362-a985-aaa68391371a">
<img width="529" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/e273b197-b595-4e9f-b107-7d7e502243c3">
<img width="538" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/826e9a92-1bb8-452b-af3b-089ba2b0e026">

- [x] Buat konsisten penggunaan pengaturan sebutan_kepala_desa dan sebutan_desa pada tombol kembali.
<img width="536" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/78d4539c-7014-40a6-b929-f4a6c6cddba3">
<img width="534" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/9eb665f5-0ae9-43ff-a094-13f7de1ce00e">
<img width="531" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/56469447-a080-4e3f-bd02-7f69679f9704">
<img width="533" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/1da9f827-8306-4d5f-ab6f-43901e457e6b">

- [x] Buat konsisten penggunaan pengaturan sebutan_kepala_desa dan sebutan_desa pada inputan form.
<img width="452" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/02b2f5da-5c45-4731-b6e4-0ef4e21b883e">
<img width="458" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/8e0b3eb4-e02d-461e-98f0-ed30e4bca4f7">

- 

- [x] Buat konsisten penggunaan pengaturan sebutan_kepala_desa dan sebutan_desa pada header cetak.
<img width="678" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/1cb91c52-a17c-4b77-8221-c4aa478d824c">
<img width="683" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/61acd731-9377-4c40-86e0-99eaf91fcb2c">

**Comment by ariandii** [comment]
termasuk yang tampil di halaman web.
agar dibuat statis.
karena bisa ada kemungkinan misal awalnya adalah Desa. maka di Jenis pada halaman web adalah Keputuran Kepala Desa atau Peraturan Kepala Desa, dan lainnya. dan jika tahun berikutnya ada perubahan desa menjadi kelurahan, maka pada arsip lama tidak akan berubah. file dan jenis tersebut tetap akan disebut keputusan kepala desa, peraturan kepala desa, dll.

karena bisa saja Desa berubah menjadi Kelurahan.

**Comment by andifahruddinakas** [comment]
Catatan : 
- Untuk data yang pernah tersimpan sebelumnya tetap sama (tidak mengikuti perubahan dari pengaturan).  Contoh : 
![image](https://github.com/OpenSID/OpenSID/assets/57283157/83bb14e0-415a-4008-86ad-18d072ede391)

**Comment by ariandii** [comment]
> Catatan :
> 
> * Untuk data yang pernah tersimpan sebelumnya tetap sama (tidak mengikuti perubahan dari pengaturan).  Contoh :
>   ![image](https://user-images.githubusercontent.com/57283157/238546252-83bb14e0-415a-4008-86ad-18d072ede391.png)

tambahan:
namun disediakan cara agar dapat diubah masing-masing atau secara massal, misal desa menjadi tiyuh. karena terlanjur input ketika belum merubah di Pengaturan Sebutan Desa.

(bukan desa menjadi kelurahan)

**Comment by andifahruddinakas** [comment]
> > Catatan :
> > 
> > * Untuk data yang pernah tersimpan sebelumnya tetap sama (tidak mengikuti perubahan dari pengaturan).  Contoh :
> >   ![image](https://user-images.githubusercontent.com/57283157/238546252-83bb14e0-415a-4008-86ad-18d072ede391.png)
> 
> tambahan: namun disediakan cara agar dapat diubah masing-masing atau secara massal, misal desa menjadi tiyuh. karena terlanjur input ketika belum merubah di Pengaturan Sebutan Desa.
> 
> (bukan desa menjadi kelurahan)

akan dibuat issue lain sebagai permintaan fitur.

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2391

**Comment by ariandii** [comment]
> Sudah diperbaiki melalui PR [OpenSID/premium#2391](https://github.com/OpenSID/premium/pull/2391)

<img width="908" alt="image" src="https://github.com/OpenSID/OpenSID/assets/46939846/1b4e2201-1ffd-4715-83ff-dcb4bc61514f">
