### ISSUE TITLE
Bug/error: Gagal Rekam Kehadiran saat Jam Pulang.

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#6664]
### Jelaskan error yg dialami

Ketika jam kehadiran di set 08.00 sampai 16.00 maka tampil di widget bahwa benar kantor desa buka jam 08.00 dan pulang jam 16.00

ketika jam 16.01 ingin lakukan rekam kehadiran karena sudah waktunya pulang, maka tidak bisa dilakukan karena batas telah lewat. sehingga tampil "Lupa Lapor Keluar".

### Cara untuk mereplikasi errornya

lakukan rekam kehadiran lewat jam 16.00 sesuai yg telah di set.
mengapa lakukan jam 16.01, karena memang sudah waktunya keluar.

menghindari tulisan Lupa Lapor Keluar.

### Hasil yg diharapkan

adanya pengaturan rentang waktu setelah jam pulang, karena tentu tidak dibenarkan lakukan rekam kehadiran sebelum waktu pulang.

dan menjadi kendala bagi yang rajin ingin lapor keluar menjadi gagal karena jam sudah lewat.

### Tangkapan layar dan log error

bisa dicoba.

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Seluruhnya

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2392
