### ISSUE TITLE
Bug/error: Log penduduk tidak terhapus setelah hapus penduduk

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#6669]
### Jelaskan error yg dialami

Kondisi saat ini : 
1. Wilayah dusun/rt/rw tidak dapat dihapus jika terdapat penduduk dan keluarga pada wilayah tsb
2. Penduduk dapat dihapus dengan kondisi, penduduk yang dihapus juga menghapus data terkait yakni bantuan dengan sasaran penduduk dan log hapus ditulis pada tabel log_penduduk_hapus. Namun terlupa untuk menghapus log_penduduk tsb, yang menyebabkan banyaknya sampah dan tidak digunakan dimanapun termasuk laporan bulanan krn log_penduduk perlu di joinkan dengan tabel tweb_penduduk.

### Cara untuk mereplikasi errornya

1. masuk ke modul Kependudukan > Penduduk
2. sediakan data penduduk
3. pilih salah 1 penduduk yang akan dihapus, dan perhatikan id nya
4. cek database log_penduduk, cari id_penduduk yang sudah dihapus tsb

### Hasil yg diharapkan

Jika menghapus penduduk, sebaiknya yang berkaitan dengan penduduk tsb juga dihapus. Dan hanya bisa hapus penduduk jika belum ada penggunaan di modul lain, misalnya bantuan sasaran penduduk, kelompo/lembaga, KK, dll. Tampilkan notifikasi seperti yang dilakukan pada modul wilayah.

### Tangkapan layar dan log error

.

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v2305.0.0-premium

### Tema Yang Digunakan

bawaan

### Informasi tambahan

SOLUSI : 
- [ ] sediakan migrasi untuk mengecek log_penduduk yang id_penduduknya tidak ada di tweb_penduduk, dan lakukan hapus data tsb.
- [ ] sediakan migrasi untuk membuat relasi dengan kondisi, jika data pada tweb_penduduk dihapus maka data pada log_penduduk yg berkaitan jg dihapus.
- [ ] pada tombol hapus data hanya lakukan jika menyatakan data belum lengkap pada pengaturan.

**Comment by eddieridwan** [comment]
@andifahruddinakas , penghapusan penduduk hanya diperbolehkan untuk satu kasus saja: yaitu salah membuat. Tantangannya bagaimana membatasi hanya untuk kasus salah membuat saja -- ada ketentuannya. Dan tidak boleh dihapus jika penduduk telah dinyatakan lengkap, karena akan mengubah riwayat mutasi penduduk. Log_penduduk digunakan untuk laporan mutasi penduduk dan harus mempertahankan riwayat mutasi penduduk. Karena memang seharusnya tidak boleh menghapus penduduk. 

**Seharusnya kita justru mengarah ke 'soft_delete' di mana penduduk tidak dihapus dari database, melainkan hanya ditandai telah dihapus.** 

Selain itu, perhatikan juga sinkronisasi dengan OpenDK. Ada log_hapus_penduduk di OpenSID untuk mencatat penduduk yg sudah dihapus supaya bisa dihapus juga di OpenDesa.

Perhatikan juga bahwa daftar ketentuan anda belum lengkap. ID penduduk juga digunakan di modul Analisis dan mungkin juga di tempat lain.

**Comment by andifahruddinakas** [comment]
> @andifahruddinakas , penghapusan penduduk hanya diperbolehkan untuk satu kasus saja: yaitu salah membuat. Tantangannya bagaimana membatasi hanya untuk kasus salah membuat saja -- ada ketentuannya. Dan tidak boleh dihapus jika penduduk telah dinyatakan lengkap, karena akan mengubah riwayat mutasi penduduk. Log_penduduk digunakan untuk laporan mutasi penduduk dan harus mempertahankan riwayat mutasi penduduk. Karena memang seharusnya tidak boleh menghapus penduduk. 
> 
> **Seharusnya kita justru mengarah ke 'soft_delete' di mana penduduk tidak dihapus dari database, melainkan hanya ditandai telah dihapus.** 
> 
> Selain itu, perhatikan juga sinkronisasi dengan OpenDK. Ada log_hapus_penduduk di OpenSID untuk mencatat penduduk yg sudah dihapus supaya bisa dihapus juga di OpenDesa.
> 
> Perhatikan juga bahwa daftar ketentuan anda belum lengkap. ID penduduk juga digunakan di modul Analisis dan mungkin juga di tempat lain. 

Kasus di atas itu untuk salah tambah data, saat ini dimenu penduduk tdk ada batasan untuk menghapus jadi sy tambahkn batasan di atas. Untuk kasus dimana data penduduknya sudah berhasil dihapus, namun di log_penduduk masih ada data dr penduduk tsb (akan jd sampah dan tdk bisa digunakan di modul manapun krn memerlukan relasi ke tweb_penduduk).


Untuk solusi soft_delete bisa diterapkan mungkin dgn catatan tambahan lainnya. (Perlu dicek lg).

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2404

**Comment by verlin884** [comment]
untuk pengaturan data belum lengkap apakah bisa diatur ya pak? jika bisa, diatur dari mana?. soalnya di desa saya ada kesalahan double input data penduduk dan sekarang terkendala tidak bisa hapus data penduduk. 
![image](https://github.com/OpenSID/OpenSID/assets/43753984/4103a0ac-3957-47d7-b18e-6ee5a1b3ddcd)
