### ISSUE TITLE
Bug/error: Jumlah Kolom Lampiran Surat Keterangan Kematian ( F-2.01) Kurang

### ISSUE THREAD

**Issue by wahyabiantara** [OpenSID/OpenSID#6671]
### Jelaskan error yg dialami

Jumlah kolom tahun pada surat keterangan kematian tidak sesuai pada form  F-2.01, sehingga data tahun muncul tidak lengkap seperti pada gambar berikut:

![image](https://github.com/OpenSID/OpenSID/assets/4361979/2ced0705-3c8a-4e39-84c9-3253714d9fbf)

### Cara untuk mereplikasi errornya

1. Buat Surat Keterangan Kematian RTF
2. Buka lampiran F-2.01 
3. Cek pada semua bari yang berisi Tahun

### Hasil yg diharapkan

Disediakan 4 kolom isian untuk tahun

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/4361979/2ced0705-3c8a-4e39-84c9-3253714d9fbf)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2305.0.1-premium

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2333

**Comment by andifahruddinakas** [comment]
berkaitan dengan https://github.com/OpenSID/OpenSID/issues/6683
