### ISSUE TITLE
Bug/error: Tombol Gear menu Layanan Pelanggan tidak berfungsi

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#6673]
### Jelaskan error yg dialami

info:
tombol gear pada menu Layanan Pelanggan tidak berfungsi di opensid v2305.0.2-premium rilis terbaru.

### Cara untuk mereplikasi errornya

terjadi juga di [berputar](https://berputar.opendesa.id/pelanggan)

### Hasil yg diharapkan

normal kembali

### Tangkapan layar dan log error

![photo_2023-05-22_00-44-34](https://github.com/OpenSID/OpenSID/assets/46939846/b8a61e42-e656-4c46-b317-1c404524cf62)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Berputar

**Comment by andifahruddinakas** [comment]
SOLUSI : 
- [ ] Perbaiki perubahan pada PR sebelumnya https://github.com/OpenSID/premium/pull/2320

**Comment by andifahruddinakas** [comment]
Perubahan pada versi : v2305.0.1

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2331

**Comment by ariandii** [comment]
bisa di tes, apakah icon batrai tidak muncul setelah penerapan ini?

**Comment by andifahruddinakas** [comment]
> bisa di tes, apakah icon batrai tidak muncul setelah penerapan ini?

muncul
<img width="433" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/4fff2726-ae25-47eb-9842-aab78ea5354b">
