### ISSUE TITLE
Error update dari rilis-dev ke OpenSID database gabungan

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#6674]
Saat ini baru digabung OpenSID database gabungan ke rilis-dev, lalu domain beta.opendesa.id  yang biasa akses rilis-dev di update pull terbaru, dan hasilnya seperti dibawah ini : 
 
<img width="422" alt="image" src="https://github.com/OpenSID/OpenSID/assets/59082428/95379a89-5fd0-4a15-ae70-209bbdf72f07">

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2329
