### ISSUE TITLE
Bug/error: eror update status IDM 2020 s.d 2023

### ISSUE THREAD

**Issue by mah-mudi** [OpenSID/OpenSID#6675]
### Jelaskan error yg dialami

eror update status IDM 2020 s.d 2023

### Cara untuk mereplikasi errornya

info desa -> statsu desa -> idm

### Hasil yg diharapkan

update status IDM 2020 s.d 2023, dapat berjalan dengan baik

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/57661283/9b883916-d6f0-4983-947b-4165aad22099)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

22.05-premium

### Tema Yang Digunakan

silir

**Comment by andifahruddinakas** [comment]
Duplicate issue https://github.com/OpenSID/OpenSID/issues/6662
