### ISSUE TITLE
Permintaan fitur: non-aktifkan ganti - ganti tema pada OpenSID

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#6676]
### Apa kekurangan yg ingin diatasi?

1. Saat ini penggunaan serentak pada 1 kabupaten dapat memilih atau mempunya akses untuk menyeragamkan tema 
2. Penyeragaman tema dapat di terapkan melalui SiapPakai
3. Namun saat ini pengguna OpenSID masih bisa mengganti Tema yang tersedia di pengaturan
4. Butuh Kondisi dimana pengaturan penggantian tema dapat di non-aktifkan

### Jelaskan solusi yg diinginkan

1. Tambahkan kondisi dimana ketika pengguna OpenSID yang lebih dari 1 config_id dapat menjalan 1 migrasi yaitu tambahkan field aktivasi_tema dimana defaultnya adalah aktif 
2. Namun ketika pengguna OpenKab nantinya dapat merubah status aktif & non-aktif  https://github.com/OpenSID/OpenKab/issues/180
3. Jika fitur di OpenKab belum diterapkan maka buat kondisi dimana pengaturan non-aktif dapat diubah melalui pengaturan di config.php seperti pengaturan bawaan warna_tema
4. jika menambahkan $config['aktivasi_tema'] = "non-aktif" maka pengaturan akan menjadi non-aktif 

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

v2305.0.0

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui commit https://github.com/OpenSID/premium/commit/3a5ce407a75cec0c3480ee88e992333e76f6155a
