### ISSUE TITLE
Install Awal masih ada prosess yang gagal dan error pasca pegabungan OpenSID gabungan 

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#6677]
1. sperti terlihat di screenshoot ini tampil setelah berhasil install awal : 
<img width="457" alt="image" src="https://github.com/OpenSID/OpenSID/assets/59082428/923d1f35-3fc7-48a4-8b5d-bcbbb03d8a79">

2. prosess install awal cukup lama
3. lalu setelah dibuka hasil install tadi di browser berbeda atau incognito berhasil tampil dan login : 
<img width="956" alt="image" src="https://github.com/OpenSID/OpenSID/assets/59082428/b5a3070c-0887-4dbf-a380-f5b9ee1f4ba0">

**Comment by andifahruddinakas** [comment]
Solusi : 
- [ ] Hapus session `$this->session->hak_akses_url` setelah berhasil install awal
- [ ] Hapus semua log_message yang ada pada install awal database gabungan

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2348
