### ISSUE TITLE
error pada saat setelah restore database pasca penggabungan OpenSID database gabungan

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#6678]
1. setelah install untuk 1 desa lalu 
2. mencoba restore database (proses tetap lambat) karena menjalankan database awal kembali terlihat dari log errornya 
3. lalu setelah berhasil restore tampilannya menjadi error seperti berikut ini : 
<img width="696" alt="image" src="https://github.com/OpenSID/OpenSID/assets/59082428/7378066a-f806-4472-991d-cf444170fee5">

4. Namun ketika di close dan buka lau di browser lain atau di incognito tampilan berhasil tampil kembali.
<img width="695" alt="image" src="https://github.com/OpenSID/OpenSID/assets/59082428/89e20501-7344-45ff-90ed-19b09b2b930f">

**Comment by andifahruddinakas** [comment]
Solusi : 
- [ ] Setelah restore lakukan otomatis logut, karena id modul kemungkinan berbeda.
- [ ] Setelah restore hapus session `$this->session->hak_akses_url`

**Comment by andifahruddinakas** [comment]
https://github.com/OpenSID/premium/commit/56c466fa8a41682810ce688e5dc8f09ca6ad2cde
