### ISSUE TITLE
Error untuk pengguna lain selain administrator misalkan group operator pasca penggabungan OpenSID database gabungan

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#6679]
1. Buat pengguna baru dengan group operator
2. Lalu coba login dengan operator 
3. maka akan tampil seprti berikut ini : 
<img width="793" alt="image" src="https://github.com/OpenSID/OpenSID/assets/59082428/e640c604-051b-48bd-8513-387534cfb356">

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2347
