### ISSUE TITLE
Sediakan pilihan menampilkan semua data pada 1 halaman

### ISSUE THREAD

**Issue by rockymakasar** [OpenSID/OpenSID#6680]
### Jelaskan error yg dialami

Saat cetak atau untuk data penduduk, data yang ditampilkan hanya data dari urutan pada halaman pertama, tidak dapat cetak keseluruhan penduduk

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

Dapat mencetak keseluruhan penduduk

### Tangkapan layar dan log error

![Screenshot 2023-05-24 075343](https://github.com/OpenSID/OpenSID/assets/94730877/c906df17-661e-4a0a-80e1-0b2ac813b02d)

![Screenshot 2023-05-24 075056](https://github.com/OpenSID/OpenSID/assets/94730877/f08afe8b-0261-4918-81ca-12e536e0f0c7)

![Screenshot 2023-05-24 075248](https://github.com/OpenSID/OpenSID/assets/94730877/8a49d27a-ec98-4308-b1f8-8458eaf42e80)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2305.0.2-premium

### Tema Yang Digunakan

-

### Informasi tambahan

-

**Comment by andifahruddinakas** [comment]
mas @rockymakasar, untuk data yang cukup besar akan membuat halaman menjadi lambat sehingga pada issue https://github.com/OpenSID/OpenSID/issues/6639 dibuat agar cetak dilakukan perhalaman bukan scr keseluruhan. Adapun perubahan ini perlu dilengkapi dengan penambahan jumlah semua ada perhalaman, sehingga ketika ada yg membutuhkan untuk cetak ada secara keseluruhan bisa ditangani dengan hal tsb.

Issue ini diubah menjadi "Sediakan pilihan menampilkan semua data pada 1 halaman" sehingga pilihan yang muncul adalah "Semua, 50, 100, 200"

**Comment by andifahruddinakas** [comment]
Bagian yang perlu disesuaikan yang pernah diubah : 
- [ ] https://github.com/OpenSID/OpenSID/issues/6640
- [ ] https://github.com/OpenSID/OpenSID/issues/6639
- [ ] https://github.com/OpenSID/OpenSID/issues/6638
- [ ] https://github.com/OpenSID/OpenSID/issues/6637
- [ ] https://github.com/OpenSID/OpenSID/issues/6636

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2369
