### ISSUE TITLE
Bug/error: Isian pada Lampiran Surat Formulir F-2.01, tidak sesuai

### ISSUE THREAD

**Issue by azzamy-bendungan** [OpenSID/OpenSID#6683]
### Jelaskan error yg dialami

Isian pada Lampiran Surat FormulirF-2.01, tidak sesuai, yaitu pada form isian Tanggal Lahir Orang Tua/Ayah, selalu yang terisi adalah tanggal 01/01/1970, sudah di padahal tanggal lahir bukan itu,
untuk tanggal lahir yang lainnya sudah pas

### Cara untuk mereplikasi errornya

Masuk Layanan Surat -> Cetak Surat -> Keterangan Kelahiran atau Keterangan Kematian -> isi data, cetak,
nanti pada kolom Tanggal Lahir Ayah, terisi 01/01/1970

### Hasil yg diharapkan

Kolom isian sesuai dengan data yang sebenarnya

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/96734091/c5dd6e07-069f-4483-b3d3-ab5941b2c5fd)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2305.0.2-premium

### Tema Yang Digunakan

Natra 22.11

**Comment by andifahruddinakas** [comment]
- [ ] Tanggal Lahir Ayah : 
<img width="639" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/3b8503ef-277c-452c-8ac5-ff2ac8904fa0">
<img width="469" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/5cf9afda-6270-4e79-9be0-4f48f354ed56">

- [x] Tanggal Lahir Ibu (sesuai): 
<img width="531" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/b53dc8e3-ba6f-4afe-afa9-e5efd93a6ba1">
<img width="521" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/4a4a194c-3f63-4abe-909b-f2ff07cfcd03">

- [x] Tanggal Lahir Anak (sesuai) : 
<img width="524" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/c0ff1def-6f1f-460c-b3f8-d9ff48db002c">
<img width="619" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/3ad13c23-58fe-4670-8fcb-526dc6df20c4">

**Comment by andifahruddinakas** [comment]
Perbaikan hanya dilakukan pada hasil cetak tanggal lahir ayah saja yang tidak disesuai.

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2372
