### ISSUE TITLE
Bug/error: Pengaturan Akun Pengguna tidak berfungsi

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/OpenSID#6684]
### Jelaskan error yg dialami

Setelah dilakukan pengaturan untuk akun pengguna dengan menerapkan beberapa menu tidak dapat diakses oleh akun tertentu, namun pada databasse gabungan pada pengaturan tersebut belum berfungsi yaitu masih ditampilkan pada akun tersebut, kemudian ketika diklik akan selalu diarahkan ke https://namadomain/bumindes_keuangan

### Cara untuk mereplikasi errornya

1. Login ke bagain admin dan klik modul Pengaturan
2. Klik Menu Pengguna
3. Klik `Pengaturan Grup`
4. Buat Grup Baru dengan pengaturan menu apa saja yang dapat ditampilkan/diakses
5. Klik `Pengaturan Pengguna` 
6. Buat Pengguna Baru dengan memilih Grup yang telah dibuat sebelumnya.
7. Login dengan akun pengguna yang telah dibuat
8. Menu yang seharusnya tidak tampil masih tampil, kemudian setelah diklik menu tersebut selalu mengarah ke https://namadomain/bumindes_keuangan

### Hasil yg diharapkan

pengaturan pengguna berfungsi sebagaimana mestinya.

### Tangkapan layar dan log error

Pengaturan Grup
![image](https://github.com/OpenSID/OpenSID/assets/68048807/a47f4ee7-3082-4230-a37e-c6584665316b)
![image](https://github.com/OpenSID/OpenSID/assets/68048807/36545729-e837-471f-9f7e-8f2d7849f6a4)

Menu yang ditampilkan dan setelah diklik
![photo_2023-05-25_05-59-22](https://github.com/OpenSID/OpenSID/assets/68048807/9caca843-6bf0-418e-8dbb-49581c6f57ad)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v2305.2.0-premium

### Tema Yang Digunakan

bima

**Comment by vickyrolanda** [comment]
Ini perlu di cek ulang sebelum di close
