### ISSUE TITLE
Bug/error: Log out sendiri saat impor database siskeudes

### ISSUE THREAD

**Issue by rockymakasar** [OpenSID/OpenSID#6688]
### Jelaskan error yg dialami

Saat melakukan impor database Siskeudes Tahun 2023 ke modul keuangan sistem log out sendiri

### Cara untuk mereplikasi errornya

1. masuk ke halaman impor data pada modul Keuangan
2. Klik tombil browse, kemudian pilih opensid_data hasil convert dari database siskeudes
3. Klik simpan
4. Sistem keluar ke halaman login

### Hasil yg diharapkan

impor data keuangan tersimpan dengan baik

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2305.0.3-premium

**Comment by andifahruddinakas** [comment]
Sertakan file yg di impor, bisa lelwat telegram @andifahruddinakas

**Comment by andifahruddinakas** [comment]
Duplicate issue https://github.com/OpenSID/OpenSID/issues/6689
