### ISSUE TITLE
Bug: pada saat centang point, semua point muncul

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#669]
pada saat centang point, semua point muncul di menu peta

**Comment by eddieridwan** [comment]
Menunggu review apakah pembuatan peta rinci sebaiknya dilakukan dengan aplikasi bantuan OpenStreetMap, seperti Qgis atau JOSM.

**Comment by egodasa** [comment]
Ini issuenya bagaimana Mas @eddieridwan ?

**Comment by eddieridwan** [comment]
Ini sepertinya sudah jalan di beta.opensid.info: klik pilihan Lokasi/Properti Desa sudah menampilkan semua lokasi (hasil kerja anda dulu). Jadi issue ini saya tutup saja.
