### ISSUE TITLE
Membedakan Tampilan link hasil Scan QrCode Surat yang di TTE dengan yang tidak di TTE

### ISSUE THREAD

**Issue by PemdesAdiwarno** [OpenSID/OpenSID#6690]
### Apa kekurangan yg ingin diatasi?

Tidak ada perbedaan ketika melakukan scan QR CODE surat, antara QR Code yang di TTE dari BSrE dengan Qr Code yang digenerate dari Aplikasi OpenSID.
![photo_2023-05-27_14-24-08](https://github.com/OpenSID/OpenSID/assets/124587672/d6062c3b-489c-4606-b46e-a45637f1b43c)

### Jelaskan solusi yg diinginkan

1. Muncul logo BSrE dan keterangan bahwa surat telah ditanda tangani secara elektronik di footer hasil scan QR Code dengan surat yang di TTE dari BsRE.
2. Tidak menampilkan logo BsRE dan keterangan bahwa surat telah ditanda tangani secara elektronik dst. untuk hasil scar QR Code Tanpa TTE dari BSrE.
![photo_2023-05-27_14-24-01](https://github.com/OpenSID/OpenSID/assets/124587672/e803d10f-b7c9-4aaf-a2e5-731be2eae7ba)
contoh seperti cek qr code KK dari dirjen disdukcapil
![tte](https://github.com/OpenSID/OpenSID/assets/124587672/4133b62c-9318-4210-9e70-41491f9c2ccb)

### Apakah ada alternatif lain

untuk membedakan hasil scan QRcode surat antara yang di Tanda tangani secara elektronik BSrE, dan yang tidak di TTE.

### Untuk versi OpenSID mana

23007.00-premium

**Comment by andifahruddinakas** [comment]
![image](https://github.com/user-attachments/assets/432940b9-f56a-44c7-bcd8-685f8725f999)

https://sultan.bandungkab.go.id/validasi/surat-eoffice/f1cc0a5d-a5fa-4404-bcde-76ecac65644e

**Comment by andifahruddinakas** [comment]
Duplicate of https://github.com/OpenSID/OpenSID/issues/8700
