### ISSUE TITLE
Bug/error: Tampilan arsip surat belum rapi

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#6693]
### Jelaskan error yg dialami

ketika membuka permohonan surat melalui hp, info ditolak ada di sisi kanan.

dan ketika buka arsip surat melalui hp, info ditolak pindah ke sisi kiri.

### Cara untuk mereplikasi errornya

buka menu Layanan Surat
masuk Arsip Surat.

### Hasil yg diharapkan

bisa dirapikan mengani Biru, Hijau, Merah

### Tangkapan layar dan log error

![Screenshot_20230528_135111_Edge](https://github.com/OpenSID/OpenSID/assets/46939846/aa8376e9-9a2f-467e-8c8e-31440a076fc9)

![Screenshot_20230528_135106_Edge](https://github.com/OpenSID/OpenSID/assets/46939846/c3266874-2e5b-4767-9a08-4608efb2bc44)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Seluruhnya

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2382
