### ISSUE TITLE
Tidak bisa Lihat Dokumen pada menu Informasi Publik

### ISSUE THREAD

**Issue by hasap86** [OpenSID/OpenSID#6696]
Saat akan melihat tampilan "Lihat Dokumen" pada menu Informasi Publik dipaksa untuk melakukan login terlebih dahulu, seharusnya tidak perlu login admin.

![ublik_1](https://github.com/OpenSID/OpenSID/assets/45263721/f4c7419b-fc8f-4a8f-8639-e87344a820cc)

![blik_02](https://github.com/OpenSID/OpenSID/assets/45263721/f2693143-273c-4a43-a81c-0d2717450e9d)

https://demosid.opendesa.id/informasi_publik

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2374

**Comment by hasap86** [comment]
Baik terimakasih, apakah scriptnya sudah bisa digunakan saat ini?
