### ISSUE TITLE
Hapus modul yang belum di pakai 

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#6697]
Test melalui devpremium.opendesa.id : 
<img width="948" alt="image" src="https://github.com/OpenSID/OpenSID/assets/59082428/68a24051-d9a1-42b1-af93-463f9389d1d6">

agar jga tidak masuk ke pengaturan group pengguna.

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2388
