### ISSUE TITLE
Bug/error: Background halaman periksa

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#6698]
### Jelaskan error yg dialami

saat membuka halaman periksa https://beta.opendesa.id/periksa/login
hanya tampil background putih. tanpa 

### Cara untuk mereplikasi errornya

buka web https://beta.opendesa.id/periksa/login
atau
https://berputar.opendesa.id/periksa/login

### Hasil yg diharapkan

background gambar bisa disesuaikan.

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Seluruhnya

**Comment by andifahruddinakas** [comment]
Duplicate issue https://github.com/OpenSID/OpenSID/issues/6702
