### ISSUE TITLE
Unggah dokumen pada data penduduk tidak load css

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#6703]
1. masukk ke menu kependudukan 
2. pilih salah satu penduduk lalu klik pilih aksi lalu kllik upload dokument penduduk
3. coba upload 1 dokumen seperti KTP 
4. setelah proses unggah tampilan akan berakhir seperti berikut ini : 
<img width="708" alt="image" src="https://github.com/OpenSID/OpenSID/assets/59082428/33169a46-e35f-4a14-843d-a596497bfcb9">

5. dan selanjutnya akan selalui muncul seperti diatas ketika masuk ke menu daftar document penduduk

**Comment by scqolbu24** [comment]
mas @vickyrolanda saya coba replikasi normal mas
![image](https://github.com/OpenSID/OpenSID/assets/68048807/60d7084b-5fab-44cd-bebb-8f26e1709534)


sepertinya sudah tertangani pada PR ini mas https://github.com/OpenSID/premium/pull/2364

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/2397
