### ISSUE TITLE
Penyesuaian Group yang tidak sesuai pada bantuan

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#6704]
Pada bagian group pengguna ada terdapat pengaturan bawah bantuan dapat 
- Hak Baca
- Hak Ubah
- Hak Hapus

Lalu ketika hanya di beri hak baca bagian tambah dan import serta tambah penerima tidak dapat dilakukan
<img width="383" alt="image" src="https://github.com/OpenSID/OpenSID/assets/59082428/9811ce71-1298-449c-a7a6-186146156901">

harapannya ketika tidak dapat hak ubah maka harus dibedakan antara tidak dapat ubah / tambah nama bantuan saja 
namun menambah penerima dapat dilakukan 
<img width="421" alt="image" src="https://github.com/OpenSID/OpenSID/assets/59082428/6d2092cd-d5c1-4725-a87d-1e872238028d">

berdasarkan logika diatas, permintaan kota bima menjadi tidak terpenuhi karena untuk user group operator kelurahan ingin dibuat tidak dapat menambah jenis bantuan namun dapat menambah penerima bantuan saja.

**Comment by andifahruddinakas** [comment]
itu tdk bisa diterapkan seperti itu, kalau mau ubah jadi sub modul dengan contoller terpisah.

**Comment by andifahruddinakas** [comment]
SOLUSI : 
- [ ] Buat modul baru dengan nama **peserta bantuan** namun dengan hidden 2 (tidak ditampilkan di menu)
- [ ] Tambahkan hak akses default.
- [ ] Pisahkan controller
- [ ] Sessuaikan url2 terkait, misalkan :
`http://opensid.test/index.php/program_bantuan/detail/1` menjadi `http://opensid.test/index.php/peserta_bantuan/1`
- [ ] Sesuaikan hak akses modul utama dan sub modul tsb.

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2652
