### ISSUE TITLE
Identitas desa error

### ISSUE THREAD

**Issue by metalab25** [OpenSID/OpenSID#671]
OpenSID versi pasca 2.5.1 fresh install error pada saat akses halaman identitas desa
![screenshot_5](https://user-images.githubusercontent.com/19917739/31389646-3f2ed4b8-ae04-11e7-83b4-4509050cf8e5.png)

**Comment by MUHAMMADRANGSEL** [comment]
Itu maslahnya di database provinsi kosoblng tdk ada data

**Comment by metalab25** [comment]
bukan, tapi tabel databasenya ga ada om

**Comment by eddieridwan** [comment]
Jalankan Database > Migrasi DB. Contoh data awal di versi pra-rilis biasanya perlu dimigrasi dulu, karena memang belum dilengkapi. Nanti di rilis betulan baru dilengkapi.
