### ISSUE TITLE
Tombol pada bagian peta perlu ditambahkan pengaturan agar bisa ditampilkan sesuai peraturan

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#6710]
Tombol peta seperti dibawah ini belum memiliki pengaturan untuk dapat ditampilkan dan disembunyikan 
hal yang perlu dilakukan adalah buat pengaturan untuk dapat menampilkan tombol.

- [ ] tambahkan pengaturan di pengaturan peta 
      - masuk ke menu peta
      - klik pengaturan
      
<img width="379" alt="image" src="https://github.com/OpenSID/OpenSID/assets/59082428/1c80961d-555e-4466-aa3d-64415fb17e24">

Tambahkan pengaturan seperti in : 
<img width="619" alt="image" src="https://github.com/OpenSID/OpenSID/assets/59082428/5187fd7f-d1be-4012-b74d-0bc0716486e8">
<img width="768" alt="image" src="https://github.com/OpenSID/OpenSID/assets/59082428/c63bcea8-5f51-4256-a7ad-0a8b598bf15d">

Maka yang akan tampil pada peta sesuai pada pengaturan di atas
<img width="363" alt="image" src="https://github.com/OpenSID/OpenSID/assets/59082428/a82fc728-bf34-4e89-898c-944a04b7aea9">

**Comment by pandigresik** [comment]
Agar popup itu muncul harus mengisi data peta dulu ya ? Jika iya akan lebih mudah jika sudah disediakan database yang sudah berisi data peta tersebut agar bisa fokus ke penyelesaian bug

**Comment by pandigresik** [comment]
![image](https://github.com/OpenSID/OpenSID/assets/1853475/51a7a439-6028-42bc-af81-2eb6ac759f9a)

**Comment by eddieridwan** [comment]
@vickyrolanda Tombol Keuangan dihapus saja (tidak disediakan pengaturan menampilkan). Keuangan tidak bersifat geospasial. Seharusnya dari awal tidak diletakkan di peta OpenSID.

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2405
