### ISSUE TITLE
Bug/error: Nomor Kartu Keluarga tertulis 0 ketika mau cetak salinan Kartu Keluarga

### ISSUE THREAD

**Issue by mah-mudi** [OpenSID/OpenSID#6712]
### Jelaskan error yg dialami

Nomor Kartu Keluarga tertulis 0 ketika mau cetak salinan Kartu Keluarga

### Cara untuk mereplikasi errornya

1. menu kependudukan
2. keluarga
3. pilih no kk yang akan dicetak
4. cetak

### Hasil yg diharapkan

Nomor Kartu Keluarga tertulis benar ketika mau cetak salinan Kartu Keluarga

### Tangkapan layar dan log error

![kk](https://github.com/OpenSID/OpenSID/assets/57661283/63c944b1-33d4-4d86-bdaf-82784196d8b2)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

22.06-premium

### Tema Yang Digunakan

silir

**Comment by ariandii** [comment]
pastikan saat cetak adalah Keluarga yg sudah input nomor KK resmi, bukan KK sementara.

ketika masih pakai KK sementara awalan 0, maka akan 0 saat cetak.

**Comment by mah-mudi** [comment]
ok sdh tertangani
