### ISSUE TITLE
Cara ubah pada pemerintah desa, aktifkan a.n dan matikan u.b gimana?

### ISSUE THREAD

**Issue by asepsetiawan9** [OpenSID/OpenSID#6713]
Cara ubah pada pemerintah desa, aktifkan a.n dan matikan u.b gimana?

_Originally posted by @ryanfigo12 in https://github.com/OpenSID/OpenSID/issues/5380#issuecomment-1463049295_

**Comment by andifahruddinakas** [comment]
https://panduan.opendesa.id/opensid/halaman-administrasi/layanan-surat/halaman-administrasi/pengaturan-penandatanganan
