### ISSUE TITLE
Bug/error: Tampilan Pendataan Penerima Vaksin Covid-19 pada Laporan Penduduk dan Laporan Rekap tidak normal

### ISSUE THREAD

**Issue by Restony33** [OpenSID/OpenSID#6714]
### Jelaskan error yg dialami

tampilan tidak normal saat buka Pendataan Penerima Vaksin Covid-19 pada Laporan Penduduk dan Rekap

### Cara untuk mereplikasi errornya

![2023-06-02_21h47_26](https://github.com/OpenSID/OpenSID/assets/104592011/327aefa9-81e0-4452-94f3-6a5deef79e64)
Login admin >>Menu Kesehatan >>Vaksin>>Laporan Penduduk dan Laporan Rekap

### Hasil yg diharapkan

Berjalan normal

### Tangkapan layar dan log error

![2023-06-02_21h48_13](https://github.com/OpenSID/OpenSID/assets/104592011/d73ef3a2-be41-49cc-a421-5e948345d0a8)
![2023-06-02_21h48_41](https://github.com/OpenSID/OpenSID/assets/104592011/266ccf20-f119-492c-ad0d-8d26735ae6c1)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Versi 2306.0.0-premium

### Tema Yang Digunakan

Esensi v22.11

### Informasi tambahan

https://berputar.opendesa.id/

**Comment by andifahruddinakas** [comment]
versi ubahan : v2306.0.0

**Comment by yogiperdana** [comment]
saya coba mundur ke versi 2305 untuk melihat perubahannya ada error grup pengguna @andifahruddinakas @vickyrolanda

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2410
