### ISSUE TITLE
Bug/error: Halaman Laporan Penduduk Vaksin Covid terjadi error

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/OpenSID#6715]
### Jelaskan error yg dialami

Terjadi error css pada halaman penduduk vaksin

### Cara untuk mereplikasi errornya

1. Masuk ke halaman Admin
2. Klik Modul Kesehatan
3. Klik Menu Vaksin
4. Klik Laporan Penduduk

### Hasil yg diharapkan

halaman normal

### Tangkapan layar dan log error

<img width="960" alt="laporan penduduk vaksin" src="https://github.com/OpenSID/OpenSID/assets/68048807/ccf136e5-a923-407c-beb7-070e9da838a6">

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Versi 2306.0.0-premium

### Tema Yang Digunakan

batuah

**Comment by andifahruddinakas** [comment]
Duplicate issue https://github.com/OpenSID/OpenSID/issues/6714
