### ISSUE TITLE
Bug/error: Data anggota saat cetak surat

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#6717]
### Jelaskan error yg dialami

Data anggota tidak tampil saat melakukan cetak berdasarkan penduduk yang statusnya kepala keluarga, sehingga kode isian klgx_nama tidak dapat digunakan pada template surat tinymce.

### Cara untuk mereplikasi errornya

1. Masuk ke layanan surat > pengaturan surat
2. Buat surat dengan jenis tinymce, masukkan kode isian anggota keluarga dan simpan. (Ganti x dengan urutan yg ingin ditampilkan)
<img width="560" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/ee9459fe-bae2-45ef-8cc9-ce60d20359df">
3. Masuk ke layanan surat > cetak surat
4. Lakukan cetak surat pada surat yg dibuat sebelumnya.
5. Pilih penduduk dengan status SHDKnya adalah kepala keluarga, pada view data anggota tidak tampil.
![image](https://github.com/OpenSID/OpenSID/assets/57283157/728b20b0-2dc0-4153-aaf0-2134ea83e748)
6. Lakukan cetak surat, kode isian klg...... tidak terganti

### Hasil yg diharapkan

Bisa tampilkan data anggota jika status penduduk yang terpilih adalah kepala keluarga.

### Tangkapan layar dan log error

.

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v2306.0.0-premium

### Tema Yang Digunakan

bawaan

### Informasi tambahan

Saat ini dibatasi dengan pengaturan masing2 surat ; 
<img width="712" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/37bf920a-5a23-4e2b-ad28-3a9256bf5b90">

**Comment by pandigresik** [comment]
![image](https://github.com/OpenSID/OpenSID/assets/1853475/8f52a3a6-d0ab-43ac-b963-b9be139e5f18)
 saya coba kok lancar saja

**Comment by pandigresik** [comment]
template surat , Ganti x dengan urutan yg ingin ditampilkan
![image](https://github.com/OpenSID/OpenSID/assets/1853475/d42341cb-1284-42c5-8ad5-ec7f67d86644)

**Comment by pandigresik** [comment]
![image](https://github.com/OpenSID/OpenSID/assets/1853475/30d98d8d-7fff-4dee-9b88-3e108b84995e)

**Comment by andifahruddinakas** [comment]
> ![image](https://user-images.githubusercontent.com/1853475/244982770-8f52a3a6-d0ab-43ac-b963-b9be139e5f18.png) saya coba kok lancar saja

SHDK ganti semua

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2427
