### ISSUE TITLE
mencetak salinan kartu keluarga secara keseluruhan

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#672]
Mohon dibuatkan fasilitas untuk mencetak salinan kartu keluarga secara keseluruhan dengan ada fasilitas misalkan mau mencetak salinan kartu keluarga dari 1-10 seperti gambar dibawah ini.
![image](https://user-images.githubusercontent.com/25834335/31420856-44294a92-ae6e-11e7-99fe-ba6acd362305.png)
![image](https://user-images.githubusercontent.com/25834335/31420867-51ad0636-ae6e-11e7-89c1-beb6c24c9bbc.png)

**Comment by eddieridwan** [comment]
@MUHAMMADRANGSEL : apa bedanya dengan salinan kartu keluarga yang ada saat ini? Maaf, kami kurang jelas apa persisnya yg diinginkan.

**Comment by MUHAMMADRANGSEL** [comment]
Yang sekarang tuk salinan cetak KK di cetak satu persatu inginnya supaya
cetak salinan KK bisa dicetak secara keseluruhan atau kita bisa tentukan
misalkan 1-10 dst

Pada tanggal 8 Nov 2017 08:09, "Eddie Ridwan" <notifications@github.com>
menulis:

**Comment by MUHAMMADRANGSEL** [comment]
![screenshot 2017-11-08 10 17 26](https://user-images.githubusercontent.com/25834335/32528536-7c39d4cc-c46e-11e7-92ac-e4bbef37965b.png)

**Comment by eddieridwan** [comment]
@MUHAMMADRANGSEL Masih belum mengerti. Salinan kartu keluarga hanya satu lembar.

Apakah yang dimaksud, dari daftar keluarga yang ada bisa memilih keluarga mana saja yang akan dicetak KKnya?

**Comment by MUHAMMADRANGSEL** [comment]
ya pas sekali kita bisa memilih mana saja kepala keluarga yg akan di cetak

Pada tanggal 8 Nov 2017 11:17, "Eddie Ridwan" <notifications@github.com>
menulis:

**Comment by eddieridwan** [comment]
Tambah menu 'aksi borongan' di halaman Keluarga untuk menghapus, mencetak kartu keluarga dan mengunduh kartu keluarga untuk beberapa keluarga sekaligus.

Sudah dicommit ke master.
