### ISSUE TITLE
Konversi  Kelompok/Lembaga menggunakan ORM dan Blade

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#6724]
Ubah modul  Kelompok/Lembaga menggunakan orm dan blade untuk CRUD + cetak/unduh : 
- [ ] kelompok
- [ ] kelompok anggota
- [ ] kelompok master

catatan : 
- [ ] hapus query lama
- [ ] hapus view lama

**Comment by agungsugiarto** [comment]
Mas @andifahruddinakas, perlu dipecah issuenya untuk kelompok master

**Comment by andifahruddinakas** [comment]
Issue ini hanya untuk modul master kelompok/lembaga
