### ISSUE TITLE
Waktu buat surat pindah dengan penduduk yang NIK nya 0 bermaslah

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#673]
maslahnya seperti ini
![tangkapan layar 2017-10-11 10 41 01](https://user-images.githubusercontent.com/25834335/31421537-203291ee-ae72-11e7-99cc-950c5423284d.png)
![tangkapan layar 2017-10-11 10 45 19](https://user-images.githubusercontent.com/25834335/31421543-2576cbca-ae72-11e7-9d3a-4ddfda2f9880.png)

![tangkapan layar 2017-10-11 10 46 20](https://user-images.githubusercontent.com/25834335/31421594-74f5e848-ae72-11e7-8c05-35af768bc8fc.png)

![tangkapan layar 2017-10-11 10 49 04](https://user-images.githubusercontent.com/25834335/31421638-a04458ae-ae72-11e7-9a94-3de8914b3aff.png)

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
