### ISSUE TITLE
Penambahan upload images pada widget

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#6730]
Saat ini bagain widget hanya ada judul dan inputan 
<img width="760" alt="image" src="https://github.com/OpenSID/OpenSID/assets/59082428/540059a0-e1c1-4e65-ac5f-0a5c92ccb484">

Perlu ditambahkan inputan images untuk dapat digunakan kebutuhan widget lainnya seperti : 
1. Menambahkan daftar link terkait dengan gambar
2. Menambahkan images di bagian tertentu seperti iklan 
3. Menambahkan Images dan teks pada serba - serbi seperti tema-bima

Batasan Pengerjaan issue ini : 
- [ ] Tambah kan inputan images ke bagian widget

Konsep selanjutnya: 
- Setiap Widget yang ditambahkan akan muncul kode penerapan dimana kode ini dapat ditambahkan di bagian - bagian mana saja yang akan mengganti tampilan sesuai yang dibuat di widget. 
<img width="267" alt="image" src="https://github.com/OpenSID/OpenSID/assets/59082428/c9d7e150-f141-4f66-a77d-3158194d0e12">

- Sedangkan untuk yang statis akan memilih tampilan berdasarkan widget yang dibuat kedalam file tertentu dan posisi ditampilkan dapat jga disesuaikan menggunakan kode penerapannya.

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2412
