### ISSUE TITLE
Bug/error: Kesalahan basis data saat memilih data ibu kandung dari database penduduk pada pembuatan surat keterangan kelahiran

### ISSUE THREAD

**Issue by rockymakasar** [OpenSID/OpenSID#6731]
### Jelaskan error yg dialami

Error saat memilih data ibu kandung dari database penduduk pada pembuatan surat keterangan kelahiran

### Cara untuk mereplikasi errornya

1. Pergi ke halaman cetak surat pada modul Layanan Surat
2. Pilih buat surat keterangan kelahiran
3. Saat di halaman buat surat keterangan kelahiran pilih database penduduk di data ibu kandung
4. Klik salah satu nama
5. Muncul error 500 kesalahan basis data telah terjadi

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/94730877/8da28b96-9605-4538-915b-edaf7ec362a5)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2306.0.0-premium

### Informasi tambahan

-

**Comment by andifahruddinakas** [comment]
Duplicate issue https://github.com/OpenSID/OpenSID/issues/6720

Solusi sementara bisa cek https://forum.opendesa.id/d/295-error-setelah-pilih-ibu-kandung-pada-saat-cetak-surat-keterangan-kelahiran
