### ISSUE TITLE
Isian surat yang di isi melalui mobile tidak semua tersimpan

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#6734]
1. buat surat identitas penduduk TinyMce 
2. lalu lakukan permintaan melalui mobile
3. isi semua data yang diperlukan 
4. lalu kirim
5. setelah itu check di bagian OpenSID disurat permohonan
6. lihat data yang diisi tidak semua terisi padahal semua sudah di isi melalui app mobile
<img width="739" alt="image" src="https://github.com/OpenSID/wiki-mobile/assets/59082428/64f72ceb-b9c3-4a40-b9bb-317da211b755">

**Comment by apidong** [comment]
> 1. buat surat identitas penduduk TinyMce
> 2. lalu lakukan permintaan melalui mobile
> 3. isi semua data yang diperlukan
> 4. lalu kirim
> 5. setelah itu check di bagian OpenSID disurat permohonan
> 6. lihat data yang diisi tidak semua terisi padahal semua sudah di isi melalui app mobile
> 
> <img alt="image" width="739" src="https://user-images.githubusercontent.com/59082428/241815427-64f72ceb-b9c3-4a40-b9bb-317da211b755.png">

ini tidak hanya terjadi di mobile, di layanan mandiri opensid juga seperti itu.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/2395
