### ISSUE TITLE
Error saat pindah config ke database baru lalu jika config di kembalikan ke database lama 

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#6738]
1. Silahkan lakukan install OpenSID atau jika sudah ada database yang ready silahkan config di arahkan ke database baru
2. Lalu database lama dijadikan backupan karena mungkin databse baru ingin di lakukan ujicoba OpenSID terbaru misalkan. 
3. lalu setelah uji coba berhasil di database baru, pengguna ingin kembalikan ke database lama, jadi pengguna hanya arahakan config ke database lama, 
4. maka tampilan OpenSID akan error , jika di check App_key didatabase lama dan app_key yg di folder desa sudah berbeda

**Comment by ariandii** [comment]
tambahan info:
1. di database tabel config muncul baris id baru
2. terkadang di tabel akan berbeda isi config_id (misal ada 1, lalu 2, dst. padahal masih db 1 desa). apakah bisa dibuatkan query jika masih 1 desa maka seluruh config_id 0, null. atau selain 1 maka dibuat 1 semua kembali.
3. ...
4. ...

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2437
