### ISSUE TITLE
Error database widget dan menu

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#6739]
```
ERROR - 2023-06-08 00:31:16 --> Query error: Can't create table `purwosar_db`.`widget` (errno: 150 "Foreign key constraint is incorrectly formed") - Invalid query: ALTER TABLE `widget`
	ADD CONSTRAINT `widget_config_fk` FOREIGN KEY (`config_id`) REFERENCES `config` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
```

```
ERROR - 2023-06-08 09:50:51 --> Query error: Can't create table `purwosar_db`.`menu` (errno: 150 "Foreign key constraint is incorrectly formed") - Invalid query: ALTER TABLE `menu`
	ADD CONSTRAINT `menu_config_fk` FOREIGN KEY (`config_id`) REFERENCES `config` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
```

Gunakan database terlampir.

**Comment by andifahruddinakas** [comment]
Cek hal beikut : 
- [x] Kolom yang dijadikan foreign key tidak memiliki tipe data yang sesuai dengan kolom referenced key. Pastikan tipe data kolom-kolom tersebut sama.
- [x] Kolom foreign key atau referenced key memiliki perbedaan dalam hal ukuran (length) atau atribut lainnya. Pastikan atribut-atribut kolom tersebut sesuai.
- [x] Nama kolom yang menjadi foreign key tidak ada di tabel yang seharusnya menjadi referenced key. Pastikan kolom tersebut ada di tabel yang benar.
- [x] Ada kesalahan sintaks dalam pernyataan pembuatan foreign key constraint. Periksa kembali pernyataan pembuatan constraint tersebut untuk memastikan tidak ada kesalahan sintaks.

**Comment by apidong** [comment]
> Cek hal beikut :
> 
> * [x]  Kolom yang dijadikan foreign key tidak memiliki tipe data yang sesuai dengan kolom referenced key. Pastikan tipe data kolom-kolom tersebut sama.
> * [x]  Kolom foreign key atau referenced key memiliki perbedaan dalam hal ukuran (length) atau atribut lainnya. Pastikan atribut-atribut kolom tersebut sesuai.
> * [x]  Nama kolom yang menjadi foreign key tidak ada di tabel yang seharusnya menjadi referenced key. Pastikan kolom tersebut ada di tabel yang benar.
> * [x]  Ada kesalahan sintaks dalam pernyataan pembuatan foreign key constraint. Periksa kembali pernyataan pembuatan constraint tersebut untuk memastikan tidak ada kesalahan sintaks.

troubel ketemu, ini dikarenakan engine yang dipakai di table config. untuk foreign key hanya berlaku untuk engine innodb.

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2430
