### ISSUE TITLE
Surat Perjalanan Dinas

### ISSUE THREAD

**Issue by PHAKaryono** [OpenSID/OpenSID#674]
Mohon dibuatkan Surat Tugas dan Surat Perjalanan Dinas dari 1(satu) hari sampai 5 (lima) hari
[SPPD Baru.docx](https://github.com/OpenSID/OpenSID/files/1376432/SPPD.Baru.docx)
Mohon juga dibuatkan permohonan KTP
[Permohonan KTP.pdf](https://github.com/OpenSID/OpenSID/files/1376463/Permohonan.KTP.pdf)

**Comment by eddieridwan** [comment]
Duplikat #720. Yang ini ditutup. Gunakan #720.
