### ISSUE TITLE
Bug/error: Penyesuaian atribut tinymce

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#6742]
### Jelaskan error yg dialami

Terdapat atribut dengan isian yang berbeda antar surat tinymce dengan isian required dan class="required", harusnya yang benar adalah class="required".

### Cara untuk mereplikasi errornya

1. Install baru
2. Masuk modul pengaturan surat
3. Buka salah 1 surat tinymce
4. Cek form isian, harunys berisi class="required"

### Hasil yg diharapkan

Dataawal sesuai dengan seharusnya.

### Tangkapan layar dan log error

<img width="202" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/3e0862ff-a2e2-492e-9f0f-1987e772a252">

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v2306.0.0-premium

### Tema Yang Digunakan

bawaan

### Informasi tambahan

SOLUSI : 
- [ ] Buat migrasi untuk mengubah data surat tinymce untuk form isian atribut="required"
- [ ] Perbaiki data awal sebagaimana seharusnya.. (attribut="class="required")

**Comment by pandigresik** [comment]
![image](https://github.com/OpenSID/OpenSID/assets/1853475/75b4d8b5-16a7-457b-924e-c22d89d3a8d5)
ini sudah berisi class="required" pada posisi install baru

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2449
