### ISSUE TITLE
Error Surat Keterangan Kelahiran

### ISSUE THREAD

**Issue by pemdeslinggapura** [OpenSID/OpenSID#6743]
### Jelaskan error yg dialami

Terjadi Error saat input Data Nama Ibu
![image](https://github.com/OpenSID/OpenSID/assets/89450861/f637a5ef-0151-45dd-86ac-e4995fc7dc8a)
Ketika memilih data ibu tersebut langsung tampil halaman ini :
![image](https://github.com/OpenSID/OpenSID/assets/89450861/3fd82789-8829-468e-b1c9-3894db2ecb9d)

### Cara untuk mereplikasi errornya

- Cetak Surat
- Keterangan Kelahiran
- Data Ibu Kandung
- Dari Database Penduduk
- Pilih data Ibu

### Hasil yg diharapkan

Bisa Cetak Kembali Keterangan Kelahiran

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/89450861/86cfc6fa-1d6b-4954-a08e-ebf885204246)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

V2306.0.0-premium

**Comment by pandigresik** [comment]
![image](https://github.com/OpenSID/OpenSID/assets/1853475/6731ad26-bb18-4b39-87b0-434172e81fdc)
di https://berputar.opendesa.id/surat/form/surat_ket_kelahiran#ibu aman tidak terjadi error

**Comment by pandigresik** [comment]
> ### Jelaskan error yg dialami
> Terjadi Error saat input Data Nama Ibu ![image](https://user-images.githubusercontent.com/89450861/245047600-f637a5ef-0151-45dd-86ac-e4995fc7dc8a.png) Ketika memilih data ibu tersebut langsung tampil halaman ini : ![image](https://user-images.githubusercontent.com/89450861/245047669-3fd82789-8829-468e-b1c9-3894db2ecb9d.png)
> 
> ### Cara untuk mereplikasi errornya
> * Cetak Surat
> * Keterangan Kelahiran
> * Data Ibu Kandung
> * Dari Database Penduduk
> * Pilih data Ibu
> 
> ### Hasil yg diharapkan
> Bisa Cetak Kembali Keterangan Kelahiran
> 
> ### Tangkapan layar dan log error
> ![image](https://user-images.githubusercontent.com/89450861/245047882-86cfc6fa-1d6b-4954-a08e-ebf885204246.png)
> 
> ### Rilis Versi OpenSID
> Rilis Premium
> 
> ### Versi OpenSID
> V2306.0.0-premium
> 
> ### Tema Yang Digunakan
> _No response_
> 
> ### Informasi tambahan
> _No response_

bisa lampirkan log errornya sekalian

**Comment by andifahruddinakas** [comment]
cek https://github.com/OpenSID/rilis-premium/releases/tag/v2306.0.1
