### ISSUE TITLE
Permintaan fitur: Menambahkan log query yang dihasilkan oleh eloquent ketika proses development

### ISSUE THREAD

**Issue by pandigresik** [OpenSID/OpenSID#6744]
### Apa kekurangan yg ingin diatasi?

Saat ini ketika menggunakan ORM eloquent untuk memastikan query yang dihasilkan oleh eloquent sudah benar atau belum, kita perlu melakukan log secara manual melalui method toSql() .

### Jelaskan solusi yg diinginkan

Menambahkan code untuk melakukan logging semua query yang dieksekusi oleh eloquent pada satu file yaitu MY_Controller

### Apakah ada alternatif lain

belum ada

### Untuk versi OpenSID mana

v2306.0.0-premium

**Comment by andifahruddinakas** [comment]
tampilkan ke develbar, query dari ORM : 
<img width="499" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/238ea353-b955-4fb4-90e7-a40736ceead1">

**Comment by pandigresik** [comment]
> tampilkan ke develbar, query dari ORM : <img alt="image" width="499" src="https://user-images.githubusercontent.com/57283157/245055561-238ea353-b955-4fb4-90e7-a40736ceead1.png">

kalau arahnya migrasi ke laravel, sepertinya kurang tepat menampilkan query ke develbar

**Comment by andifahruddinakas** [comment]
> > tampilkan ke develbar, query dari ORM : <img alt="image" width="499" src="https://user-images.githubusercontent.com/57283157/245055561-238ea353-b955-4fb4-90e7-a40736ceead1.png">
> 
> kalau arahnya migrasi ke laravel, sepertinya kurang tepat menampilkan query ke develbar

untuk sementara tampilkan dsana, query yg digunakan CI3 dan ORM. Kalau sudah migrasi ke laravel bisa pakai laravel debugbar. (ini masih lama)

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2524
