### ISSUE TITLE
Bug/error: Log Keluarga tidak sesuai dengan detail modul keluarga

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#6745]
### Jelaskan error yg dialami

Terjadi selisih dari laporan keluarga bulanan, dan saat menekan tombol detail data yg tampil tidak sesuai.

### Cara untuk mereplikasi errornya

1. gunakan database desa jawalaut (terlampir)
2. masuk modul statistik > laporan bulanan
3. cek kolom keluarga, terdapat nilai minus (-)
4. kemudian tekan angka tsb, akan di arahkan ke detail bulanan dengan jumlah data yg berbeda.

### Hasil yg diharapkan

Laporan bulanan untuk keluarga tampil normal, dan saat tekan detail juga normal.

### Tangkapan layar dan log error

Laporan Bulanan : 
<img width="120" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/38320a7f-aa1e-417d-addc-212a5762309d">

Detail Laporan: 
![image](https://github.com/OpenSID/OpenSID/assets/57283157/07cf37ee-2309-46cf-bd18-c5f99677410e)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v2306.0.0-premium

### Tema Yang Digunakan

bawaan

### Informasi tambahan

.

**Comment by pandigresik** [comment]
kita coba bandingkan dengan database opensid lain yang berasal dari issue 6441

select min(tgl_peristiwa) as tgl, 'log_keluarga_opensid_6441' as tabel from opensid_6441.log_keluarga where id_peristiwa = 1
union
select min(tgl_daftar) as tgl, 'tweb_keluarga_opensid_6441' as tabel from opensid_6441.tweb_keluarga tk
union 
select min(tgl_peristiwa) as tgl, 'log_keluarga_jawalaut' as tabel from log_keluarga where id_peristiwa = 1
union
select min(tgl_daftar) as tgl, 'tweb_keluarga_jawalaut' as tabel from tweb_keluarga tk 

![image](https://github.com/OpenSID/OpenSID/assets/1853475/66df9d97-1b62-4356-9545-ad60caae7d05)

**Comment by pandigresik** [comment]
> kita coba bandingkan dengan database opensid lain yang berasal dari issue 6441
> 
> select min(tgl_peristiwa) as tgl, 'log_keluarga_opensid_6441' as tabel from opensid_6441.log_keluarga where id_peristiwa = 1 union select min(tgl_daftar) as tgl, 'tweb_keluarga_opensid_6441' as tabel from opensid_6441.tweb_keluarga tk union select min(tgl_peristiwa) as tgl, 'log_keluarga_jawalaut' as tabel from log_keluarga where id_peristiwa = 1 union select min(tgl_daftar) as tgl, 'tweb_keluarga_jawalaut' as tabel from tweb_keluarga tk
> 
> ![image](https://user-images.githubusercontent.com/1853475/245336711-66df9d97-1b62-4356-9545-ad60caae7d05.png)

data normalnya adalah minimum tgl_peristiwa pada log_keluarga dan minimum tgl_daftar pada tweb_keluarga hampir sama

**Comment by pandigresik** [comment]
Solusi untuk saat ini adalah melakukan perbaikan data secara manual sambil mencari penyebab tidak terbentuknya / hilang data di log_keluarga.
Query berikut dapat digunakan
`insert into log_keluarga (config_id, id_kk, id_peristiwa, tgl_peristiwa, updated_by)
select 1 as config_id, id as id_kk, 1 as id_peristiwa, tgl_daftar as tgl_peristiwa, 1 as updated_by  from tweb_keluarga  
where id not in (
select id_kk from log_keluarga where id_peristiwa = 1
)
`

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2436
