### ISSUE TITLE
Bug/error: Log Penduduk tidak sesuai dengan detail modul penduduk

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#6746]
### Jelaskan error yg dialami

Terjadi selisih dari laporan penduduk bulanan, dan saat menekan tombol detail data yg tampil tidak sesuai.

### Cara untuk mereplikasi errornya

1. gunakan database desa jawalaut (terlampir)
2. masuk modul statistik > laporan bulanan
3. cek kolom keluarga, terdapat nilai minus (-)
4. kemudian bandingkan angka tsb dengan data yang ada di modul penduduk

### Hasil yg diharapkan

Laporan bulanan untuk keluarga tampil normal, dan saat tekan detail juga normal.

### Tangkapan layar dan log error

Laporan Bulanan : 
<img width="412" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/52fc7401-8586-48e9-af63-ea0e378c80b6">

Detail Laporan: 
![image](https://github.com/OpenSID/OpenSID/assets/57283157/3002d9ec-543c-49f1-b055-9343356d4aed)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v2306.0.0-premium

### Tema Yang Digunakan

bawaan

### Informasi tambahan

.

**Comment by pandigresik** [comment]
databasenya mana ?

**Comment by andifahruddinakas** [comment]
> databasenya mana ?

 database terlampir (cek grup)

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2438
