### ISSUE TITLE
Bug/error: Jumlah data pada wilayah tidak sesuai dengan detail saat di tampilkan

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#6747]
### Jelaskan error yg dialami

Terjadi selisih dari data wilayah dan detail data yg ditampilkan tidak sesuai.

### Cara untuk mereplikasi errornya

1. gunakan database desa jawalaut (terlampir)
2. masuk modul info desa > wilayah administratif
3. tekan detail oada angka tsb, maka akan diarahkan ke detail data misalnya penduduk. dalam kasus ini terjadi selisih antara jumlah data yg ditampilkan dengan detail datanya untuk data penduduk perempuan dusun "SATU"

### Hasil yg diharapkan

data wilayah  tampil normal, dan saat tekan detail juga sesuai.

### Tangkapan layar dan log error

Wilayah : 
![image](https://github.com/OpenSID/OpenSID/assets/57283157/31f839f3-e4a2-4a2d-afda-cf5722f14c32)

Detail Data: 
![image](https://github.com/OpenSID/OpenSID/assets/57283157/7f4ebec6-becf-4db0-a9e8-9f377bdb21fe)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v2306.0.0-premium

### Tema Yang Digunakan

bawaan

### Informasi tambahan

.

**Comment by pandigresik** [comment]
databasenya mana ?

**Comment by andifahruddinakas** [comment]
> databasenya mana ?

 database terlampir (cek grup)

**Comment by pandigresik** [comment]
Setelah dilakukan pengecekan terdapat satu nik yang memiliki id_cluster yang berbeda di tabel tweb_penduduk dan tweb_keluarga sehingga membuat agak salah ketika menampilkan resume jumlah penduduk berdasarkan wilayah
`select nik, id_cluster from tweb_penduduk tp where tp.nik = '63030762080XXXXX'
union 
select no_kk, id_cluster from tweb_keluarga tk where tk.id = (
	select id_kk from tweb_penduduk tp where tp.nik = '63030762080XXXXX'
)`

**Comment by pandigresik** [comment]
![image](https://github.com/OpenSID/OpenSID/assets/1853475/ed1f99df-2f9a-4cfa-b6a7-8c638ec8dbc5)
Data alamat untuk penduduk tersebut

**Comment by pandigresik** [comment]
> ![image](https://user-images.githubusercontent.com/1853475/245644447-ed1f99df-2f9a-4cfa-b6a7-8c638ec8dbc5.png) Data alamat untuk penduduk tersebut

![image](https://github.com/OpenSID/OpenSID/assets/1853475/6649d365-4e07-4212-8bb5-1b0116b2ce11)
Data alamat untuk keluarga penduduk tersebut

**Comment by pandigresik** [comment]
Setelah alamat penduduk pada biodata disesuaikan mengikuti alamat keluarga, jangan lupa hapus cache dulu di folder desa karena untuk menampilkan data tersebut menggunakan cache
