### ISSUE TITLE
Bug/error: Gagal migrasi karena tanggal tidak valid pada tabel covid19_vaksin

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#6748]
### Jelaskan error yg dialami

Gagal melanjutkan migrasi karena terjadi error saat menambahkan relasi pada tabel covid19_vaksi ke tabel config. Disebabkan karena pada kolom tgl_vaksin_1, tgl_vaksin_2 atau tgl_vaksin_3 berisikan data '0000-00-00'.

### Cara untuk mereplikasi errornya

1. Gunakan database yang bermasalah (terlampir)
2. Lakukan migrasi ulang
3. Akan terjadi error

### Hasil yg diharapkan

Migrasi jalan lancar, sediakan halaman untuk memperbaiki database.

### Tangkapan layar dan log error

```
ERROR - 2023-06-12 22:32:41 --> Query error: Incorrect date value: '0000-00-00' for column 'tgl_vaksin_3' at row 4 - Invalid query: ALTER TABLE `covid19_vaksin`
	ADD CONSTRAINT `covid19_vaksin_config_fk` FOREIGN KEY (`config_id`) REFERENCES `config` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
```

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v2306.0.0-premium

### Tema Yang Digunakan

bawaan

### Informasi tambahan

SOLUSI : 
- [ ] Tambahkan halaman periksa database untuk tabel `covid19_vaksin` dengan data '0000-00-00', ubah menjadi null (krn struktur kolomnya mengijikan adanya null)
- [ ] Lewati migrasi penambahan relasi tsb jika tabel masih bermasalah (krn sifatnya migrasi berulang, migrasi penambahan relasi bisa menyusul)

**Comment by pandigresik** [comment]
sepertinya ini hanya terjadi jika menggunakan Mysql versi 8, saya test di mariadb 10.3 tidak terjadi. Mungkin bisa dilampirkan file dump database yang bermasalah tersebut

**Comment by andifahruddinakas** [comment]
> sepertinya ini hanya terjadi jika menggunakan Mysql versi 8, saya test di mariadb 10.3 tidak terjadi. Mungkin bisa dilampirkan file dump database yang bermasalah tersebut

Sy coba di MySQL 5.7.33 menggunakan database terlampir (cek grup)

**Comment by pandigresik** [comment]
![image](https://github.com/OpenSID/OpenSID/assets/1853475/eb703ab3-450c-4f47-ad4e-26f2ba1fd126)
pakai mariadb 10.3

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2434
