### ISSUE TITLE
Bug/error: Nama Bidang pada Belanja, perlu disesuaikan dengan Permendagri Nomor 20 Tahun 2018

### ISSUE THREAD

**Issue by mah-mudi** [OpenSID/OpenSID#6749]
### Jelaskan error yg dialami

Nama Bidang pada Belanja, belum sesuai dengan Permendagri Nomor 20 Tahun 2018
Terutama redaksi 
Bidang Pembinaan Kemasyarakatan
Bidang Pemberdayaan Masyarakat

### Cara untuk mereplikasi errornya

1. keuangan
2. input data
3. isi belanja
4. pilihan belanja
5.  ubah aksi edit

### Hasil yg diharapkan

![image](https://github.com/OpenSID/OpenSID/assets/57661283/7e11208a-a6d8-4a77-baaf-134790353aea)
redaksi 
Bidang Pembinaan Kemasyarakatan
Bidang Pemberdayaan Masyarakat

diganti menjadi
Bidang Pembinaan Kemasyarakatan Desa
Bidang Pemberdayaan Masyarakat Desa

Sehingga tampilan bidang apbdesa di tampilan depan website sdh sesuai

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/57661283/466fe573-9094-471a-90ae-23cf6de2cbd0)
![image](https://github.com/OpenSID/OpenSID/assets/57661283/010637bd-056a-4782-8efd-1a47b128f999)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

22.06.0.1

### Tema Yang Digunakan

silir

### Informasi tambahan

https://demosid.opendesa.id/

terjadi di link tsb

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2440
