### ISSUE TITLE
Bug/error: Tidak dapat menghapus data penduduk pada Data Suplemen

### ISSUE THREAD

**Issue by rockymakasar** [OpenSID/OpenSID#6751]
### Jelaskan error yg dialami

Ketika menghapus penduduk pada Data Suplemen yang ditambahkan terjadi error

### Cara untuk mereplikasi errornya

1. Pergi ke halaman Kependudukan
2. Data Suplemen
3. Klik Rincian Data
4. Klik Tombol Hapus pada salah satu penduduk yang ditambahkan
5. Terjadi Error

### Hasil yg diharapkan

Data penduduk pada Data Suplemen dapat terhapus

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/94730877/0e4998af-ce5e-4926-8f6d-3b4a0eb29e97)

![image](https://github.com/OpenSID/OpenSID/assets/94730877/489f3459-56fd-4306-aa3c-6c3f00af590d)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2306.0.1-premium

### Tema Yang Digunakan

-

### Informasi tambahan

-

**Comment by andifahruddinakas** [comment]
versi ubahan : v2306.0.0

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2444
