### ISSUE TITLE
Kode isian hari dan tanggal untuk tinymce

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#6752]
Sediakan kode isian berupa : 
<img width="428" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/aa6eed1e-89f7-4604-ae96-26dbed39b388">

- [x] nama : input hari, dimana form isiannya tetap menggunakan tanggal, namun outputnya berupa hari dari input tgl tsb
- [x] nama : input hari dan tanggal, , dimana form isiannya tetap menggunakan tanggal, namun outputnya berupa hari dan tanggal dari input tgl tsb

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/2500
