### ISSUE TITLE
Permintaan fitur: Bisa Memilih Layanan Yang Akan Diperpanjang Lewat Aplikasi

### ISSUE THREAD

**Issue by mah-mudi** [OpenSID/OpenSID#6753]
### Apa kekurangan yg ingin diatasi?

belum ada fitur berlangganan otomatis via aplikasi openSID.
cara berlangganan ini masih manual via kontak person.

### Jelaskan solusi yg diinginkan

Dengan berlangganan otomatis, pengguna mendapatkan kemudahan dalam berlangganan.
Beri Opsi pengguna untuk berlangganan otomatis.
pada menu layanan pelanggan, beri informasi no rekening pembayaran berlangganan otomatis.
beri juga pilihan berlangganan 1 tahun , 2 tahun, 3 tahun, 5 tahun, 10 tahun.
misal : 
berlanggnan 2 tahun (diskon 5%)
berlangganan 3 tahun (diskon 10%)
berlangganan 5 tahun (diskon 15%)
berlangganan 10 tahun (diskon 20%)

metode pembayaran:
jika pengguna memilik paket berlangganan 10 tahun (diskon 20%), upload bukti transfer, jk verivikasi berhasil, masa berlangganan otomatis bertambah sesuai pilihan paket

### Apakah ada alternatif lain

.

### Untuk versi OpenSID mana

22.06-premium

### Informasi tambahan

.

**Comment by andifahruddinakas** [comment]
Sudah ada fiturnya, namun terbatas yang dipernjang adalah pemesanan terakhir (tdk bisa dipilih)

**Comment by andifahruddinakas** [comment]
Duplicate issue https://github.com/OpenSID/OpenSID/issues/7190
