### ISSUE TITLE
api key tidak berfungsi

### ISSUE THREAD

**Issue by ipaysx** [OpenSID/OpenSID#676]
saya pasang Api key google maps, tapi maps di peta desa tetap desa sebelummnya, sy ambil config dari desa senggigi sehingga maps yang muncul tetap desa tersebut, mohon bantuannya.

![screenshot_17](https://user-images.githubusercontent.com/12766544/31485129-f5ce8c1e-af5c-11e7-8ea7-8a4feb297fbc.jpg)

dan semestinya ini alamat maps kantor desa

https://www.google.com/maps/place/Kantor+Desa+(Alassumur+Kulon)/@-7.767437,113.461443,17z/data=!4m5!3m4!1s0x0:0x87222f4df6278e3b!8m2!3d-7.7680894!4d113.4610978?hl=en-US

mohon bantuannya.. trims

**Comment by eddieridwan** [comment]
Google maps API key digunakan untuk menampilkan peta. Jika sudah tampil, seperti contoh anda, ya API key itu sudah berfungsi betul.

Mengenai lokasi yang ditampilkan, ubah dengan mengikuti panduan https://github.com/OpenSID/OpenSID/wiki/Lokasi-Kantor-Desa. Jangan ubah scriptnya.

Rajin2 membaca panduan. Selalu cari solusi di panduan dulu.

Sebaiknya pertanyaan penggunaan OpenSID anda posting di https://www.facebook.com/groups/OpenSID/. Issues tujuannya untuk merekam tugas untuk memperbaiki bug betulan. Jadi yakin dulu memang bug, baru buat issue.
