### ISSUE TITLE
Belum tersedia tombol Tambah Satu atau Beberapa pada Data Suplemen

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#6764]
### Jelaskan error yg dialami

saat ini tombol Tambah Warga Terdata langsung menuju form tambah, yang jika menambah data lebih dari 1 akan bolak balik klik tombol tersebut.

<img width="380" alt="image" src="https://github.com/OpenSID/OpenSID/assets/46939846/80b14046-a967-430a-87a5-88d0fd0bb66d">

### Cara untuk mereplikasi errornya

Masuk menu Kependudukan -> Data Suplemen

Tambah SUplemen Baru, lalu masuk Suplemen tersebut. dan klik Tambah Warga Terdata

### Hasil yg diharapkan

tersedia Tambah Data bisa lebih dari 1. misal seperti di menu Bantuan atau menu Kelompok.

<img width="202" alt="image" src="https://github.com/OpenSID/OpenSID/assets/46939846/b662f77c-527f-43a7-822b-1952d8cebc26">

### Tangkapan layar dan log error

di atas

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Rilis Mendatang

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/commit/c7913a2b8295f49fcf46276ab8b6f0095af43dbc
