### ISSUE TITLE
Bug/error: ubah fungsi reset pada Tombol Batal menjadi tutup beserta kata di tombolnya, semua fungsi di popup.

### ISSUE THREAD

**Issue by mah-mudi** [OpenSID/OpenSID#6765]
### Jelaskan error yg dialami

Pilihan Tombol Batal berfungsi yg awalnya sebagai reset. diubah menjadi tutup.

### Cara untuk mereplikasi errornya

1. menu
2. menu statis
3. sub menu
4. ubah sub menu (salah satu contoh)
5. ada banyak tombol Batal yg perlu diganti Tombol tutup
### Hasil yg diharapkan

Ubah fungsi reset pada tombol batal diubah menjadi fungsi tutup untuk semua fungsi di popup.
Redaksi Tombol Batal, diubah menjadi Tutup

### Tangkapan layar dan log error

![AZXCV](https://github.com/OpenSID/OpenSID/assets/57661283/544db22b-f4b9-448b-8830-a7fb67ea5b0b)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

22.06.0.2

### Tema Yang Digunakan

silir

### Informasi tambahan

-

**Comment by ariandii** [comment]
Tambahan beberapa popup yang tombolnya perlu disesuaikan, dan bisa juga ada ditempat lainnya.

![IMG_20230619_143909_134](https://github.com/OpenSID/OpenSID/assets/46939846/b36e2005-41fa-4411-b24d-6a72847b2b76)

![IMG_20230619_143909_287](https://github.com/OpenSID/OpenSID/assets/46939846/dcdfc63d-7c48-43b1-beef-60493fbc99dd)

![IMG_20230619_143909_675](https://github.com/OpenSID/OpenSID/assets/46939846/b9fa2861-71d5-4f13-9b9f-640616f420f3)

**Comment by andifahruddinakas** [comment]
pada bagian https://github.com/OpenSID/OpenSID/wiki/Struktur-Form-Isian perlu diperbaiki pada bagian yang menggunakan modal : 
- [ ] Jika pada modal terdapat form isian, gunakan tombol batal (warna merah) yang digunakan untuk mengembalikan data pada isian semula.
Contoh : 
<img width="305" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/91118c6f-1cda-4769-86a1-1dc32f859fd3">

- [ ] Jika pada modal hanya ada proses (aksi) tanpa adanya isian, gunakan tombol tutup (warna orange) 
Contoh : 
<img width="317" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/81ff0d6f-9499-4376-ad9e-050b86ee085a">

Untuk kasus di Issue ini, sudah sesuai namun dibeberapa tempat ada yang belum sesuai.
Contoh : 
<img width="307" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/4fe4d4c6-9554-4ee7-99ed-e0e504192220">


Hal yang akan terjadi jika tombol diubah menjadi tombol tutup, langkah yang harus dilakukan untuk mengembalikan isian (menormalkan form) menjadi panjang. Dimana sebelumnya hanya perlu menekan tombol batal saja, namu jika diubah perlu melakukan tutup modal dan pilih ulang data yang akan diubah.

Adapun jika ingin menutup modal, tinggal menekan tombol **x** yang ada di pojok kanan atas yang sudah disediakan.

**Comment by ariandii** [comment]
https://github.com/OpenSID/OpenSID/wiki/Struktur-Form-Isian

cc pak @eddieridwan
