### ISSUE TITLE
Belum tersedia Pilihan pada Tambah Data Suplemen sesuai Panduan yang ada.

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#6767]
### Jelaskan error yg dialami

Perhatikan 2 gambar berikut.

![Screenshot_20230619_145048_Chrome](https://github.com/OpenSID/OpenSID/assets/46939846/e5ac450b-b8af-462e-8372-a649d7e85593)

![Screenshot_20230619_145056_Chrome](https://github.com/OpenSID/OpenSID/assets/46939846/1451873c-d354-400d-8532-b7221b131b29)

### Cara untuk mereplikasi errornya

Masuk menu Kependudukan -> Data Suplemen

Klik tombol Panduan dan Praktekkan.

yang ada hanya pilihan Penduduk dan Keluarga, tidak sesuai dengan Panduan seperti Rumah Tangga Maupun Kelompok/Organisasi

### Hasil yg diharapkan

tersedia pilihan sesuai Panduan, atau Panduan yang disesuaikan dengan ketersediaan pada Pilihan Tambah Data.

### Tangkapan layar dan log error

di atas

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Semua

**Comment by andifahruddinakas** [comment]
- [ ] Pindahkan semua panduan ke panduan.opendesa.id
- [ ] Hapus info panduan ini

**Comment by andifahruddinakas** [comment]
Bagian ini sudah tidak ada lagi.
