### ISSUE TITLE
kolom ubah data

### ISSUE THREAD

**Issue by ipaysx** [OpenSID/OpenSID#677]
mohon perbaikannya di kolom ubah data penduduk tidak ada  kolom untuk dusun,rt,rw. sehingga tidak bisa edit alamat penduduk. trims
![screenshot_18](https://user-images.githubusercontent.com/12766544/31485327-aa4ee6b6-af5d-11e7-9582-6468c9764ef5.jpg)
![screenshot_19](https://user-images.githubusercontent.com/12766544/31485350-b5889dc4-af5d-11e7-9d76-3c070bd0ac43.jpg)
![screenshot_20](https://user-images.githubusercontent.com/12766544/31485362-be39ab3e-af5d-11e7-8f1d-ee9fdcbad421.jpg)

**Comment by eddieridwan** [comment]
Alamat penduduk adalah alamat keluarga penduduk. Untuk mengubah alamat penduduk, gunakan fitur Ubah Alamat (tombol di Aksi) untuk keluarga penduduk. 

Lihat panduan https://github.com/OpenSID/OpenSID/wiki/Pengisian-Data-Keluarga.

SELALU baca panduan dulu sebelum bertanya.

Dan JANGAN gunakan issue untuk bertanya penggunaan OpenSID. Bertanya di https://www.facebook.com/groups/OpenSID/. Gunakan issue hanya kalau sudah yakin memang ada sesuatu untuk diperbaiki atau dilengkapi.
