### ISSUE TITLE
Penyesuaian menampilkan data dinamis

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#6770]
Sesuaikan bagian untuk kasus data dinamis : 
- [x] Cetak surat pada layanan surat 
- [ ] Cetak surat pada permohonan dari layanan mandiri
- [ ] Cetak surat pada layanan mandiri

**Comment by vickyrolanda** [comment]
mas @habibie11 , juga perlu dipisahkan antara kode isian yang bagian bawah itu dengan kode isian yang ditambah melalui . 
karena harisnya dengan nama yang sama bisa duplikat dan hanya 1 yang tampil. 

1. tambahkan tab baru dengan nama saksi
2. Lalu tambah kode isian seperti dibawah ini 
<img width="225" alt="image" src="https://github.com/OpenSID/OpenSID/assets/59082428/e27d432d-0717-45f9-ae45-f80b1a6a92b4">
3. lalu ditab utama juga tambahkan kode isian seperti diatas.
4. maka setelah di simpan akan muncul pilihan seperti ini : 
<img width="195" alt="image" src="https://github.com/OpenSID/OpenSID/assets/59082428/15dceae9-22a5-4c74-8260-a9970c614f82">

5. ketika di simpan data yang tampil bakal jadi sama 
<img width="168" alt="image" src="https://github.com/OpenSID/OpenSID/assets/59082428/3122c6bb-1660-4ce4-bdef-897b6078a0eb">

yang di harapkan di piliha kode isian itu baiknya juga di klasterkan berdasarkan bagian dari Saksi Saja. Sehingga ada perbedaan antara Tab Utama & Tab yang ditambah baru.

**Comment by habibie11** [comment]
Sudah diupdate sesuai permintaan, silahkan di cek kembali mas @vickyrolanda , terimakasih.
[https://github.com/OpenSID/premium/pull/2479](https://github.com/OpenSID/premium/pull/2479)

Kode isian percluster kategori
![Screenshot 2023-06-26 061634](https://github.com/OpenSID/OpenSID/assets/56639378/e43c21da-c191-49ee-933b-30d1eb01cf32)

Kode isian yang sama dengan data utama sudah tidak sama
![Screenshot 2023-06-26 100507](https://github.com/OpenSID/OpenSID/assets/56639378/85401d08-fb2b-4863-8e91-0bc9a8eae6eb)
