### ISSUE TITLE
Bug/error: muncul error id_user is null

### ISSUE THREAD

**Issue by Agungf19** [OpenSID/OpenSID#6772]
### Jelaskan error yg dialami

error muncul ketika buat surat dengan nomor surat yang tidak urut,

errornya seperti ini

Severity: error --> Exception: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'id_user' cannot be null (SQL: insert into log_surat (`id`, id_format_surat, id_pend, id_pamong, nama_jabatan, nama_pamong, id_user, tanggal, bulan, tahun, no_surat, keterangan, `keca 
atan`, isi_surat, nama_surat, `config_id`) values (?, 234, 465, 26, Kepala Desa, ATOK SETYO UTOMO, ?, 2023-06-16 07:27:42, 06, 2023, 36, Keterangan usaha rental mobil, 1, [logo]PEMERINTAH KABUPATEN BLORA KECAMATAN SAMBONGDESA POJOKWATU Jl. Raya Watubrem RT 002, RW 002, Ds. Pojokwatu, Kec. Sambong, Kab. Blora - Jawa Tengah Email: [info@pojokwatu.com](mailto:info@pojokwatu.com) Kode Pos: 58371SURAT KETERANGAN UMUMNomor : 045.2/036/3316062005/VI/2023Yang bertanda tangan di bawah ini Kepala Desa Pojokwatu, Kecamatan Sambong, Kabupaten Blora, Provinsi Jawa Tengah menerangkan dengan sebenarnya bahwa : 1.Nama Lengkap:SUBANGUN BRATA TJAHJONO 2.Kepala Keluarga:S wagiman 3.Tempat / Tanggal Lahir:Blora, 29 november 2002 4.Agama:Islam 5.Jenis Kelamin:Laki-laki 6.Pekerjaan:Karyawan Swasta 7.Bukti diri    KTP:3316062106720001  KK:3316062501084882 8.Tempat Tinggal:Dk. SIDOMULYO RT: 002 RW: 001 Desa Pojokwatu, Kecamatan Sambong, Kabupaten Blora - Jawa Tengah 9.Keperluan:Keterangan usaha rental mobil 10.Berlaku:23-04-2023 s/d 23-05-2023Demikian surat ini dibuat, untuk dipergunakan sebagaimana mestinya.  Pojokwatu, 23 April 2023Pemegang Surat Kepala Desa Pojokwatu  SUBANGUN BRATA TJAHJONO ATOK SETYO UTOMO   [qr_code]3316062005 045.2, surat-keterangan-umum_3316062106720001_2023-06-16_36.pdf, 1)) /home/mudaapps/[pojokwatu.id/vendor/illuminate/database/Connection.php](https://pojokwatu.id/vendor/illuminate/database/Connection.php) 712

### Cara untuk mereplikasi errornya

1. klik cetak surat
2. pilih salah satu surat
3. masukan nomor urut yang tidak sesuai dengan sistem aplikasi
4. kemudian buat surat baru lagi,
kadang error tersebut akan muncul, yg membuat tidak bisa cetak surat, dan muncul sweealert "ERROR", dan menu di sidebar jadi tidak tampil.

solusi sementara logout lalu login lagi,atau bisa clear cache

### Hasil yg diharapkan

mohon segera diperbaiki, agar tidak muncul error id_user is null

### Tangkapan layar dan log error

![photo_6084752143761388921_w](https://github.com/OpenSID/OpenSID/assets/43205017/a4187239-a22d-45ea-b4ba-c065b1a7f887)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Versi 2306.0.1-premium

### Tema Yang Digunakan

Batuah 23.02

### Informasi tambahan

-

**Comment by pandigresik** [comment]
saya coba kok gak error ya, kalau dari pesan errornya sepertinya karena session user telah habis sehingga id_user menjadi null

**Comment by pandigresik** [comment]
![image](https://github.com/OpenSID/OpenSID/assets/1853475/cf720f55-4bf0-4bf0-8926-e8ae606d7078)
Default dari sistem nomernya 41 kemudian saya ubah menjadi 42 lalu cetak lagi yang secara otomatis dapat nomer 43

**Comment by Agungf19** [comment]
maaf , bagaimana bisa sessionya bisa habis, padahal aplikasi sedang di operasikan beberapa menit ?
