### ISSUE TITLE
Bug/error: tampilan foto aparatur desa buram saat upload baru atau upload ulang

### ISSUE THREAD

**Issue by Akmal197** [OpenSID/OpenSID#6773]
### Jelaskan error yg dialami

tampilan foto aparatur desa buram saat upload baru atau upload ulang foto walaupun dengan resolusi yang sama dengan foto yang ada sebelumnya

### Cara untuk mereplikasi errornya

1. pergi ke info desa
2. ke menu pemerintah desa
3. ubah data dan uload gambar
4. upload via kependudukan pun sama

### Hasil yg diharapkan

mohon untuk diperbaiki agar kualitas gambar yang diupload tidak buram

### Tangkapan layar dan log error

gambar replikasi di berputar
![image](https://github.com/OpenSID/OpenSID/assets/76812689/76221a46-2abe-40c5-878d-a6e10579285e)
gambar di tema DeNatra
![image](https://github.com/OpenSID/OpenSID/assets/76812689/2a6715f6-6a0a-45f1-9f99-30d9067780ce)
gambar yg di upload sebelumnya
![image](https://github.com/OpenSID/OpenSID/assets/76812689/655ea9de-c525-450b-8b50-eefdbcf6b546)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2306.0.2

### Tema Yang Digunakan

DeNatra

**Comment by andifahruddinakas** [comment]
INFORMASI : untuk foto pamong maupun penduduk seblum diunggah dilakukan pengecilan resolusi agar tidak membebankan penyimpanan jika mengunggah file foto dengan resolusi besar.

<img width="661" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/4fac5487-20d0-4a17-9817-3f04afddbc43">

SOLUSI : 
- [ ] Sediakan pengaturan resolusi pada unggah foto dengan standar 200 x 200

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2491
