### ISSUE TITLE
Permintaan fitur: 

### ISSUE THREAD

**Issue by anggifs92** [OpenSID/OpenSID#6774]
### Apa kekurangan yg ingin diatasi?

Penambahan nama desa yang baru depenitif..Belum semua nagari diupdate..tolong diupdate min..
Nagari saya:nagari ranah koto tinggi, kecamatan koto balingka,kab pasaman barat

### Jelaskan solusi yg diinginkan

tolong penambahan..Nagari saya:nagari ranah koto tinggi, kecamatan koto balingka,kab pasaman barat

### Apakah ada alternatif lain

kalau bisa tambahkan nagari yang baru depenitif

### Untuk versi OpenSID mana

v23.06

**Comment by andifahruddinakas** [comment]
Solusi : https://forum.opendesa.id/d/296-nama-desa-tidak-sesuai
