### ISSUE TITLE
Permintaan fitur: Export & Import Artikel Website

### ISSUE THREAD

**Issue by hirudi** [OpenSID/OpenSID#6776]
### Apa kekurangan yg ingin diatasi?

Ketika mengalami Gagal update opensid biasanya kami install ulang Opensid terbaru kemudian import data penduduk sesuai database yang lama, namun kita tidak punya backup an Artikel Website yang sudah kita buat.

### Jelaskan solusi yg diinginkan

Untuk dibuatkan menu Export & Import Artikel 

![image](https://github.com/OpenSID/OpenSID/assets/4936934/7b4fd6e3-a67c-47ba-b8a0-df4ffaf34159)

### Untuk versi OpenSID mana

Opensid terbaru

**Comment by pandigresik** [comment]
Kalau proses update versi bisa lebih lancar seharusnya fitur ini tidak diperlukan lagi

**Comment by andifahruddinakas** [comment]
gunakan backup database
