### ISSUE TITLE
Deteksi folder desa jika terdapat permission yang tidak sesuai

### ISSUE THREAD

**Issue by hy-reza** [OpenSID/OpenSID#6777]
### Jelaskan error yg dialami

Saya tidak dapat mengungah / upload file berupa document maupun gambar 

### Cara untuk mereplikasi errornya

saat simpan perubahan ketika upload file

### Hasil yg diharapkan

Dapat upload file secara normal

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/93983098/1387fee5-9b97-4d4d-93d1-286ee1612711)

### Rilis Versi OpenSID

Rilis Umum

### Versi OpenSID

v2306.0.0

**Comment by andifahruddinakas** [comment]
SOLUSI : 
- [ ] permission folder 775
- [ ] deteksi folder permission jika tidak sesuai (https://github.com/OpenSID/premium/issues/2305), lakukan perbaikan menyeluruh pada folder2 tsb jika tdk sesuai. Bisa tab baru pada bagian ini : 
<img width="532" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/5705ece1-a02d-4784-b4e1-b037bd6d5c3e">

**Comment by hy-reza** [comment]
> SOLUSI :
> 
> * [ ]  permission folder 775
> * [ ]  deteksi folder permission jika tidak sesuai (https://github.com/OpenSID/premium/issues/2305), lakukan perbaikan menyeluruh pada folder2 tsb jika tdk sesuai. Bisa tab baru pada bagian ini :
> 
> <img alt="image" width="532" src="https://user-images.githubusercontent.com/57283157/247452971-5705ece1-a02d-4784-b4e1-b037bd6d5c3e.png">

Maaf tapi sepertinya solusi tersebut tidak menyelesaikan masalah saya, saya sudah mengubah permission dari folder tersebut ke 775 dan hasilnya masi tetap error. atau mungkin saya salah melakukannya ??

ada 3 folder yang saya coba ubah permission nya 
- 2 folder yang ada pada menu info system  (chache & views) (chmod 775 /var/www/html/resources/views
) & (chmod 775 /var/www/html/desa/cache)
- 1 folder upload pada dir desa (chmod 775 /var/www/html/desa/upload)

**Comment by hy-reza** [comment]
Ok, solved thanks

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2493
