### ISSUE TITLE
Sesuaikan jumlah lampiran sesuai pengaturan pada TinyMCE

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#6781]
1. Untuk beberapa jenis surat yang memiliki lebih dari 1 lampiran saat ini sudah berhasil membuat daftar lampiran dalam bentuk array pda tabel lampiran seperti dibawah ini : 
<img width="52" alt="image" src="https://github.com/OpenSID/OpenSID/assets/59082428/fd2b032e-82fc-4d21-b87a-b62e8ed33b1f">

Perbaikan dari PR Select Lampiran : https://github.com/OpenSID/premium/pull/2476
1. Ketika lampiran terselect lebih dari 2 misalkan 3 lampiran maka yg tersimpan hanya 2 di selected pada pengaturan surat 
<img width="655" alt="image" src="https://github.com/OpenSID/OpenSID/assets/59082428/584fb808-4a01-4bc9-8b50-db93e69b8162">

2.Lalu ketika surat sudah termigrasi dan tersimpan di kolom lampiran seperti data berikut ini : F-1.15,F-1.01,F-1.02 namun pada pengaturan surat malah lampiran tidak terselected hanya menampilkan kosong : 
<img width="664" alt="image" src="https://github.com/OpenSID/OpenSID/assets/59082428/0f4d2c52-cb91-49ee-9338-84816871fc57">

3. Ketika lampiran sudah di pilih 2 / 3 yang tampil hanya 1 lampiran saja sehingga perlu di sesuaikan berdasarkan jumlah lampiran yang terselect.

**Comment by scqolbu24** [comment]
Mas @vickyrolanda ini testing di branch mana?
saya coba testing di branch rilis-dev hasil seperti pada video berikut:

https://github.com/OpenSID/OpenSID/assets/68048807/38194186-83a6-4f98-a939-268b12f1ac2b

**Comment by scqolbu24** [comment]
setelah ditesting kembali sudah ketemu masalahnya mas, jika yang diisi tidak urut seperti F-1.15,F-1.01,F-1.02 nanti hasilnya yang terselect ketika akan diubah hanya 2, padahal yang tersimpan di database sebanyak 3.

**Comment by scqolbu24** [comment]
mas @vickyrolanda siap review.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/2497
