### ISSUE TITLE
Kode Isian Perisitiwa Kematian

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#6782]
View :
<img width="503" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/84899f72-bd28-4b47-a3e8-c7af996482a1">

Pengaturan :
dengan kondisi, mati, pindah dan hilang
<img width="517" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/caa02517-6260-4213-a4d3-727b7fa81532">

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/2512
