### ISSUE TITLE
View data orang tua

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#6783]
<img width="515" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/cfe5ff81-af99-4fbb-9558-95a1ab6e1ae5">

Dengan pengaturan, tampilkan data orang tua.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/2510
