### ISSUE TITLE
Bug/error: Kemana larinya jika klik Arsipkan Kotak Masuk dan Icon Amplop

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#6784]
### Jelaskan error yg dialami

![IMG_20230622_145507_098](https://github.com/OpenSID/OpenSID/assets/46939846/1e18da83-b5d9-4f79-a8bd-2cc11428145f)

![IMG_20230622_145239_088](https://github.com/OpenSID/OpenSID/assets/46939846/2ea4384f-7103-4d46-b1bc-85a40d975b6c)

### Cara untuk mereplikasi errornya

masuk menu Layanan Mandiri -> Kotak Masuk

klik tombol merah. arsipkan

klik tombol hitam. amplop

### Hasil yg diharapkan

apakah arsipkan menghapus data atau menyimpan? jika disimpan, dimana letak arsipnya?

amplop terbuka adalah surat belum terbaca sedangkan amplop tertutup sudah dibaca? (apakah tidak terbalik?)

### Tangkapan layar dan log error

di atas

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Semua

**Comment by andifahruddinakas** [comment]
tombol : 
- arsip, layaknya delete namun tidak dilakukan permanen (hanya mengubah status). untuk melihat pesan yang di arsipkan bisa melakukan filter berikut : 
<img width="536" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/3ad76827-959e-4866-b819-395315960517">
pada kasus filter "semua" tidak termasuk pesan yang diarsipkan.

- pesan baca/belum baca, hanya untuk menandai pesan apakah sudah dibaca atau belum. Untuk iconnya sendiri sepertinya terbalik.

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2490
