### ISSUE TITLE
Bug/error: Kirim Pesan Keluar, redirect ke Kotak Masuk

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#6785]
### Jelaskan error yg dialami

![Screenshot_20230622_145929_Chrome](https://github.com/OpenSID/OpenSID/assets/46939846/ccfc887d-20d1-4f31-b7c4-c0270d0d17ec)

### Cara untuk mereplikasi errornya

masuk memu Layanan Mandiri -> Kotak Pesan

klik Kotak Keluar

lalu isi kolom dan klik kirim.

lihat hasilnya.

### Hasil yg diharapkan

seharusnya berada pada tabel Kotak keluar, yang saat ini setelah kirim muncul notif berhasil namun tabel adalah kotak masuk

### Tangkapan layar dan log error

di atas

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Semua

**Comment by pandigresik** [comment]
harusnya di blok kotak masuk, tombol tulis pesan juga tidak ada ya ?

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2489
