### ISSUE TITLE
Pilihan Penadatanganan Surat TinyMCE/TTE untuk Kepala Desa/Sekretaris Desa

### ISSUE THREAD

**Issue by PemdesAdiwarno** [OpenSID/OpenSID#6786]
### Apa kekurangan yg ingin diatasi?

Tanda Tangan TTE di Aplikasi OpenSID masih hanya dapat dilakukan oleh kepala desa, sedangkan Sekretaris Desa juga memiliki kewenangan terhadap penandatanganan surat yang di terbitkan oleh pemerintah desa.

### Jelaskan solusi yg diinginkan

![image](https://github.com/OpenSID/OpenSID/assets/124587672/d9327802-3177-4df4-adaa-21e72ce99c4e)
Terdapat pilihan Penanda tangan Secara Elektronik di Surat TinyMCE untuk sekretaris desa, 
seperti pilihan penandatanganan surat yang ada di surat format RTF.

### Apakah ada alternatif lain

Mobilisasi Kepala Desa yang tinggi kadang menghambat penandatanganan surat permohonan dari warga, sehingga sekretaris Desa Dapat melakukan Penanda tanganan Surat Secara Elektronik

### Untuk versi OpenSID mana

v23.08-premium

**Comment by ariandii** [comment]
apakah sekdes juga diberi passkey TTE oleh kominfo?

**Comment by PemdesAdiwarno** [comment]
> 

Untuk sekretaris desa di kabupaten kami telah diberi passkey TTE

**Comment by ariandii** [comment]
saat ini sudah ada alur surat dengan pilihan Ya untuk verifikasi Sekdes dan misal pilih Tidak untuk Kades 

apakah itu masih perlu verifikasi sampai kades?

**Comment by PemdesAdiwarno** [comment]
> saat ini sudah ada alur surat dengan pilihan Ya untuk verifikasi Sekdes dan misal pilih Tidak untuk Kades
> 
> apakah itu masih perlu verifikasi sampai kades?

![image](https://github.com/OpenSID/OpenSID/assets/124587672/2b04fcba-044a-4e3c-972d-7a283b04b396)
ketika surat tinyMCE dibuat dengan alur Verifikasi Sekdes, untuk penadatangan otomatis kades

**Comment by ariandii** [comment]
walaupun dengan posisi verifikasi kades Tidak?
seperti gambar berikut.

![Screenshot_20230622_211146_Chrome](https://github.com/OpenSID/OpenSID/assets/46939846/37eab577-aeea-439c-95a8-ed9099bfe30c)

**Comment by PemdesAdiwarno** [comment]
> 

Walaupun dengan alur seperti itu, tetap penadatangannya adalah kades

**Comment by ndunks** [comment]
halo apakah belum ada update?

**Comment by andifahruddinakas** [comment]
> halo apakah belum ada update?

saat ini penanda tangan pada TTE masih Kades

**Comment by ndunks** [comment]
iya, lalu apakah ini di sengaja? atau itu kesalahan dan harus di ubah?

**Comment by andifahruddinakas** [comment]
> iya, lalu apakah ini di sengaja? atau itu kesalahan dan harus di ubah?

penerapan awal memang seperti itu. jika ada informasi surat seperti apa yang ditandatangani oleh sekdes bisa di lampirkan sebagai referensi.

**Comment by andifahruddinakas** [comment]
Duplicate of https://github.com/OpenSID/OpenSID/issues/7609
