### ISSUE TITLE
Bug/error: Fungsi Jadikan Headline tidak berfungsi

### ISSUE THREAD

**Issue by mah-mudi** [OpenSID/OpenSID#6787]
### Jelaskan error yg dialami

Fungsi Jadikan Headline tidak berfungsi

### Cara untuk mereplikasi errornya

1. artikel
2. halaman statis

### Hasil yg diharapkan

Fungsi Jadikan Headline dapat berfungsi sebagaimana mestinya

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/57661283/249bd8a8-5233-4b73-9e58-5e3c192e2ebc)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

22.06.0.3

### Tema Yang Digunakan

silir

### Informasi tambahan

-

**Comment by andifahruddinakas** [comment]
Duplicate issue https://github.com/OpenSID/OpenSID/issues/6771
