### ISSUE TITLE
Bug/error: Tidak bisa ubah email dan tombol versifikasi muncul walau email kosong

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#6788]
### Jelaskan error yg dialami

tidak bisa ubah email pengguna

### Cara untuk mereplikasi errornya

1. masuk ke profil
2. lakukan ubah data email

### Hasil yg diharapkan

- bisa ubah email
- tombol verifikasi dihilangkan jika belum ada email

### Tangkapan layar dan log error

<img width="326" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/9fd2b511-56d2-4135-ab15-b4826ae5675a">

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v2306.0.0-premium

### Tema Yang Digunakan

bawaan

### Informasi tambahan

SOLUS : 
- [ ] bisa ubah email
- [ ] tombol verifikasi hanya muncul jika ada email dan belum verifikasi
- [ ] setiap kali ubah email, verifikasi dilakukan ulang, tombol verifikasi tampil

**Comment by ariandii** [comment]
tambahan:
walau diinput,
email tidak berfungsi ketika belum di verifikasi. sesuai notif Tidak dapat menemukan pengguna dengan email tersebut.

agar benar benar email yg telah terverifikasilah yang bisa mendapatkan notif berhasil.

![Screenshot_20230623_212415_Gallery](https://github.com/OpenSID/OpenSID/assets/46939846/6c151f3e-e3ec-4a3b-8dfd-3770ffd7c108)

![Screenshot_20230623_130520_Chrome](https://github.com/OpenSID/OpenSID/assets/46939846/bd191963-4fb5-4ea4-a557-fadc6bb440d3)

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2495
