### ISSUE TITLE
Bug/error: Kesalahan Naskah Notifikasi Reset PiN Layanan Mandiri

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#6790]
### Jelaskan error yg dialami

Pada pengaturan Jabatan adalah Pj. Kepala Desa

namun yang tampil di naskah chat WA Notifikasi reset PIN tertulis Hormat kami Kepala Desa

### Cara untuk mereplikasi errornya

lakukan reset PIN melalui menu
Layanan Mandiri -> Pendaftaran Layanan Mandiri.

klik icon Kunci, lalu klik Reset PIN.

kemudian klik kirim WA.

### Hasil yg diharapkan

Sesuaikan sebutan Jabatan dengan yang ada di menu Jabatan

### Tangkapan layar dan log error

![Screenshot_20230623_224233_Chrome](https://github.com/OpenSID/OpenSID/assets/46939846/684b0cf7-f961-4355-816a-78f66fe17968)

![Screenshot_20230623_224137_Chrome](https://github.com/OpenSID/OpenSID/assets/46939846/cb8c4cca-76e5-47e8-b4d3-52fd05823346)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Semua

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2505
