### ISSUE TITLE
Bug/error: Tidak diminta ubah PIN setelah di reset

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#6791]
### Jelaskan error yg dialami

setelah lakukan seperti issue
https://github.com/OpenSID/OpenSID/issues/6790

maka pin baru dihasilkan oleh operator desa yang diberikan kepada warag tersebut.

namun setelah warga tsb login layanan mandiri, tidak redirect ke halaman ganti pin seperti semula.

### Cara untuk mereplikasi errornya

sepeeti di atas

### Hasil yg diharapkan

sesuai dengan pembuatan Pendaftaran Layanan Mandiri di awal, ketika PIN di reset, maka warga wajib ganti pin agar tetap rahasia. walauoun pin hasil reset.

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Rilis Mendatang

**Comment by andifahruddinakas** [comment]
mas @pandigresik, bisa di cek untuk kasus ini karena saya cek di https://berputar.opendesa.id/mandiri tidak ada masalah untuk kasus kirim lewat WA atau tanpa kirim.

[reset pin mandiri.zip](https://github.com/OpenSID/OpenSID/files/11862533/reset.pin.mandiri.zip)

**Comment by pandigresik** [comment]
saya coba reset pin juga otomatis minta ganti pin lagi
