### ISSUE TITLE
Session cetak surat kelahiran dan kematian tidak terhapus saat cetak surat kembali

### ISSUE THREAD

**Issue by apidong** [OpenSID/OpenSID#6792]
replikasi :
1. Buat surat keterangan kelahiran / kematian.
2. isi form surat menggunakan data warga desa
3. unduh rtf.
4. kembali ke modul cetak surat menggunakan menu atau tombol kembali ke daftar surat cetak
5. buat surat keterangan kelahiran / kematian

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2499
