### ISSUE TITLE
Error buat surat TinyMCE 

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#6793]
<img width="571" alt="image" src="https://github.com/OpenSID/OpenSID/assets/59082428/a9c0d74c-698c-4add-8095-4c466c308924">

Ketika buat surat pada rilis-dev error seperti diatas .

Lalu coba test melalui bug-fix maka berhasil.

kalo di cek ada di database cuma config_id tidak ada

<img width="69" alt="image" src="https://github.com/OpenSID/OpenSID/assets/59082428/b14c9539-63ae-4cd3-9c9a-6e92dfa89b54">

**Comment by apidong** [comment]
ini Tidak bisa Replikasi bug nya pak

**Comment by yogiperdana** [comment]
Diganti menjadi bug karena issue aslinya sudah dirilis dan bukan termasuk susulan lagi

**Comment by andifahruddinakas** [comment]
cek issue https://github.com/OpenSID/OpenSID/issues/6840

**Comment by scqolbu24** [comment]
mas @vickyrolanda, mas @andifahruddinakas  Sebelumnya saya pernah mengalami hal ini yaitu pada saat buat daftar surat baru di pengaturan surat, namun setelah pull rilis-dev terbaru sekarang sudah normal.

**Comment by andifahruddinakas** [comment]
> mas @vickyrolanda, mas @andifahruddinakas Sebelumnya saya pernah mengalami hal ini yaitu pada saat buat daftar surat baru di pengaturan surat, namun setelah pull rilis-dev terbaru sekarang sudah normal.

dalam beberapa pembahasan, fungsi seperte insert, updateOrCreate tdk men triger observer. namun pada kondisi ini, kadang terjadi error, kadang juga tdk. Mungkin solusi sementara yang bisa digunakan agar tdk berkelanjutan, seperti ini : 

- [ ] untuk insert, selalu sertakan config_id
- [ ] untuk updateOrCreate, selalu sertakan config_id

contoh : 
`Model::insert(['config_id' => 1, 'nama' => 'akas']);`
`Model::updateOrCreate(['id' => $this->request['id_surat'], 'config_id' => 1], static::validate($this->request));`
// pada validate tambahkan config_id

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2736
