### ISSUE TITLE
Hasil backup database menggunakan phpmyadmin bermasalah

### ISSUE THREAD

**Issue by apidong** [OpenSID/OpenSID#6795]
saat melakukan phpmyadmin terdapat kesalahan pada bagian create view.
kata-kata 1 union select all bergabung menjadi satu kalimat.
![image](https://github.com/OpenSID/OpenSID/assets/20056421/0a384377-671f-4974-b313-ee2ad9339994)

detail : 
versi phpmyadmin : phpMyAdmin 5.2.1
versi opensid : 2306.0.0
database : mariadb

catatan : 
- dari keterangan pak ariandi, pada versi opensid 22.09 tidak ada masalah.
- hanya terjadi pada server yang menggunakan cpanel.

**Comment by pandigresik** [comment]
![image](https://github.com/OpenSID/OpenSID/assets/1853475/ac7fd600-94cd-4d46-a413-9cc433675ef1)
Versi 2306 umum juga sama, versi phpmyadmin versi: 5.2.1

**Comment by pandigresik** [comment]
view dengan menggunakan union ini ada pada file Migrasi_fitur_premium_2106.php, yang bermasalah kemungkinan besar semua versi setelahnya jika diexport menggunakan phpmyadmin

**Comment by pandigresik** [comment]
hasil export kita coba import lagi menggunakan phpmyadmin juga bermasalah
#1064 - You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'allselect 'inventaris_gedung' AS `asset`,`inventaris_gedung`.`id` AS `id`,`in...' at line 1
versi phpmyadmin 5.2.1
versi mariadb 10.6.14-MariaDB - MariaDB Server
![image](https://github.com/OpenSID/OpenSID/assets/1853475/744ba6e6-663c-4484-a93f-82ff85369406)

**Comment by pandigresik** [comment]
https://github.com/phpmyadmin/phpmyadmin/issues/18515

**Comment by vickyrolanda** [comment]
issue ini sy ganti ke cek issue terlbih dahulu dan tidak di close sampai nanti ada jawaban dari issue yang di buat mas @pandigresik .
