### ISSUE TITLE
Aplikasi tidak bisa terhubung ke internet

### ISSUE THREAD

**Issue by apidong** [OpenSID/OpenSID#6796]
beberapa desa mengalami error tersebut saat membuka halaman admin dan halaman menjadi lama terbuka
![image](https://github.com/OpenSID/OpenSID/assets/20056421/7a1b2e9b-0181-4fda-9c75-62c5c1b0bd05)

analisis : 
pada script bagian ini. server tidak bisa melakukan komunikasi ke google ![image](https://github.com/OpenSID/OpenSID/assets/20056421/91bc43dc-80c5-4ca9-bcde-f55208767677)

**Comment by eddieridwan** [comment]
@andifahruddinakas bisa coba:

1. menggantikan www.google.com dengan situs lain yg lebih terjamin diakses melalui jaringan yg digunakan pengguna
2. mencoba akses ke beberapa situs, misalnya 2, dan sukses jika salah satu sukses. Jadi tidak langsung gagal jika satu gagal, karena akses ke situs tersebut kebetulan bermasalah.

**Comment by ariandii** [comment]
> @andifahruddinakas bisa coba:
> 
> 1. menggantikan [www.google.com](http://www.google.com) dengan situs lain yg lebih terjamin diakses melalui jaringan yg digunakan pengguna
> 2. mencoba akses ke beberapa situs, misalnya 2, dan sukses jika salah satu sukses. Jadi tidak langsung gagal jika satu gagal, karena akses ke situs tersebut kebetulan bermasalah.

ijin menambahkan,
poin nomor 2 perlu akses login halaman admin, karena efeknya terasa ketika login akan error 500 dan mencoba masuk slug menu menu lain loading sangat lama.

**Comment by pandigresik** [comment]
ketika posisi server sudah di shared hosting, bukankah sudah dapat diasumsikan pasti ada koneksi internetnya ?

**Comment by eddieridwan** [comment]
<img width="550" alt="image" src="https://github.com/OpenSID/OpenSID/assets/249563/16c7e92d-e6ff-4a08-a6d4-36c0fff99078">

**Comment by ariandii** [comment]
sedikit reminder sejak laporan awal: efeknya log server gona away namun notif nya mengenai koneksi internet.

===
poin utamanya ada 2 issue.

issue perbaiki gona away dan issue notif yg tidak sesuai mengenai jaringan internet.

karena hal ini sudah dibahas panjang dan berulang di berbagai tempat.

**Comment by pandigresik** [comment]
![image](https://github.com/OpenSID/OpenSID/assets/1853475/fbe7909e-83fd-4139-beb9-3ef64d5cdeb4)
Mungkin cek_koneksi_internet perlu dibatasi untuk dijalankan ketika server diset offline pada pengaturan modul

**Comment by pandigresik** [comment]
pakai solusi yang mana ini ?

**Comment by andifahruddinakas** [comment]
> pakai solusi yang mana ini ?

point 

> @andifahruddinakas bisa coba:
> 
> 1. menggantikan [www.google.com](http://www.google.com) dengan situs lain yg lebih terjamin diakses melalui jaringan yg digunakan pengguna
> 2. mencoba akses ke beberapa situs, misalnya 2, dan sukses jika salah satu sukses. Jadi tidak langsung gagal jika satu gagal, karena akses ke situs tersebut kebetulan bermasalah.

yang ini mas @pandigresik,

untuk saat ini notifikasi tsb bisa diabaikan melalui pengaturan aplikasi.
<img width="398" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/65670bdc-31ae-4e9b-a5e3-12925a001072">

mungkin defaultnya dibuat false saja.
<img width="326" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/2c4762ab-25e1-4cea-aff4-996d444320d2">
<img width="312" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/fd23b7be-0a57-4c23-bcbf-07263c434f0c">

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2507

Sudah di cek bersama mas @pandigresik melalui salah 1 website yg bermasalah, untuk kasus notifikasi koneksi tsb. Untuk kasus `gona away` pada mysql setelah login, dengan perubahan ini belum ditemukan log tsb pada website yg diuji.
