### ISSUE TITLE
Bug/error: halaman Admin Error 

### ISSUE THREAD

**Issue by mat22-wq** [OpenSID/OpenSID#6797]
### Jelaskan error yg dialami

1. Terjadi Masalah Saat Login, Gagal amasuk Pada halaman /hom.sid (Error 505)
2. Halaman Admin Sangat Lambat Di akses
3. Notif
Informasi .Aplikasi tidak dapat terhubung dengan koneksi internet, beberapa modul mungkin tidak berjalan dengan baik.

### Cara untuk mereplikasi errornya

error 505

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/80165352/d2ee938d-5aeb-464f-90dd-3c8b71e6673a)

### Rilis Versi OpenSID

Rilis Umum

### Versi OpenSID

v2306.0.0

### Tema Yang Digunakan

Silir

### Informasi tambahan

Hosting Niagahoster

**Comment by andifahruddinakas** [comment]
Duplicate issue https://github.com/OpenSID/OpenSID/issues/6796

**Comment by andifahruddinakas** [comment]
![image](https://github.com/OpenSID/OpenSID/assets/57283157/fd9ba3c5-a54a-4d11-a914-e4e8418b8ccb)
