### ISSUE TITLE
Bug/error: ID penduduk out of range 

### ISSUE THREAD

**Issue by hy-reza** [OpenSID/OpenSID#6798]
### Jelaskan error yg dialami

Surat tidak bisa di cetak karena error ID penduduk 

### Cara untuk mereplikasi errornya

Pergi ke halaman cetak surat
Pilih surat
Isi form surat
Klik tombol save
Klik tombol cetak
Lihat error (internal server error)

### Hasil yg diharapkan

Surat berhasil di cetak 

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/93983098/97f6e158-0ba9-4b87-bc39-cbe94576996e)

### Rilis Versi OpenSID

Rilis Umum

### Versi OpenSID

v2306.0.0

**Comment by andifahruddinakas** [comment]
mas @hy-reza, lampirkan database.

**Comment by hy-reza** [comment]
> mas @hy-reza, lampirkan database.

Maaf lampiran database dalam bentuk apa dan bagian mananya ya ?

**Comment by andifahruddinakas** [comment]
> > mas @hy-reza, lampirkan database.
> 
> Maaf lampiran database dalam bentuk apa dan bagian mananya ya ?

backup tabel log_surat aja

**Comment by hy-reza** [comment]
> > > mas @hy-reza, lampirkan database.
> > 
> > 
> > Maaf lampiran database dalam bentuk apa dan bagian mananya ya ?
> 
> backup tabel log_surat aja

**Comment by hy-reza** [comment]
> > > mas @hy-reza, lampirkan database.
> > 
> > 
> > Maaf lampiran database dalam bentuk apa dan bagian mananya ya ?
> 
> backup tabel log_surat aja

maaf maksudnya apakah dalam bentuk file sql ? saya mencoba upload file sql tapi sepertinya gthub tidak support

**Comment by hy-reza** [comment]
Saya bermasalah di bagian surat kematian yan saya buat manual mengguakan tinyMCE, jika dilihat di database id penduduk masih terlihat normal


![image](https://github.com/OpenSID/OpenSID/assets/93983098/cb971a14-05f5-4059-886d-fdc47df642e3)

**Comment by andifahruddinakas** [comment]
> Saya bermasalah di bagian surat kematian yan saya buat manual mengguakan tinyMCE, jika dilihat di database id penduduk masih terlihat normal
> 
> 
> ![image](https://github.com/OpenSID/OpenSID/assets/93983098/cb971a14-05f5-4059-886d-fdc47df642e3)
> 

Coba dikirimkaan template surat yg ddibuat

**Comment by andifahruddinakas** [comment]
dari errornya, yang tersimpan di tabel id_pend bukan id nya melainkan NIK nya.

untuk mengirim backup tempate tinymce yg dibuat :
<img width="298" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/786587b0-a3ff-48f1-b303-5a4f4b177552">

kirim file .json yg dihasilkan.

**Comment by hy-reza** [comment]
> dari errornya, yang tersimpan di tabel id_pend bukan id nya melainkan NIK nya.
> 
> untuk mengirim backup tempate tinymce yg dibuat : <img alt="image" width="298" src="https://user-images.githubusercontent.com/57283157/249046061-786587b0-a3ff-48f1-b303-5a4f4b177552.png">
> 
> kirim file .json yg dihasilkan.

Maaf saya kirim zip, karena format json juga tidak support 

[template_surat_tinymce_27_06_2023.zip](https://github.com/OpenSID/OpenSID/files/11878053/template_surat_tinymce_27_06_2023.zip)

**Comment by hy-reza** [comment]
Nama pelapor dari code isian [Nama] juga tidak terisi otomatis

![image](https://github.com/OpenSID/OpenSID/assets/93983098/c53dfe9a-18e7-4e92-b5fb-5c7717f3acad)

dan tidak bisa dicetak 

![image](https://github.com/OpenSID/OpenSID/assets/93983098/5f2b7082-6d57-4306-830d-6df8147c84bd)

**Comment by andifahruddinakas** [comment]
> Nama pelapor dari code isian [Nama] juga tidak terisi otomatis
> 
> ![image](https://user-images.githubusercontent.com/93983098/249048064-c53dfe9a-18e7-4e92-b5fb-5c7717f3acad.png)
> 
> dan tidak bisa dicetak
> 
> ![image](https://user-images.githubusercontent.com/93983098/249048478-5f2b7082-6d57-4306-830d-6df8147c84bd.png)

untuk kode_isian nik, jangan menggunakan nik karena sudah digunakan untuk menampilkan data secara umum.
<img width="486" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/4b67ae87-a4e2-47e4-afe3-4c61de7ec7a8">

bisa tambahkan prefix lain, misalnya NIK Almarhum, begitupun dengan kode_isian lainnya. cek kode isian yang sudah digunakan : 
<img width="224" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/cfda6567-0a94-40bf-af0f-58d3d5f5d8bf">

**Comment by andifahruddinakas** [comment]
mas @hy-reza, coba pakai ini : 
[kematian.zip](https://github.com/OpenSID/OpenSID/files/11878192/kematian.zip)

**Comment by hy-reza** [comment]
> mas @hy-reza, coba pakai ini : [kematian.zip](https://github.com/OpenSID/OpenSID/files/11878192/kematian.zip)

Sudah bisa di cetak mas @andifahruddinakas, tapi setiap cetak surat kok ada file seperti ini ya :

![image](https://github.com/OpenSID/OpenSID/assets/93983098/358ed017-c633-4ec0-98ab-6c55a3874a5a)
 
![image](https://github.com/OpenSID/OpenSID/assets/93983098/ac554182-78c6-48b2-b220-7ca50030c3b2)

**Comment by andifahruddinakas** [comment]
> > mas @hy-reza, coba pakai ini : [kematian.zip](https://github.com/OpenSID/OpenSID/files/11878192/kematian.zip)
> 
> Sudah bisa di cetak mas @andifahruddinakas, tapi setiap cetak surat kok ada file seperti ini ya :
> 
> ![image](https://user-images.githubusercontent.com/93983098/249051497-358ed017-c633-4ec0-98ab-6c55a3874a5a.png)
> 
> ![image](https://user-images.githubusercontent.com/93983098/249051530-ac554182-78c6-48b2-b220-7ca50030c3b2.png)

saat cetak ada tampil untuk menyimpan suratnya.

bisa dibahass di issue lain.
