### ISSUE TITLE
Bug/error: Tidak bisa menambah data suplemen

### ISSUE THREAD

**Issue by ai-skematik** [OpenSID/OpenSID#6799]
### Jelaskan error yg dialami

Tidak bisa menambah data suplemen

### Cara untuk mereplikasi errornya

Buat Data suplemen kemuadian tambahakan penduduk pada data tersebut

### Hasil yg diharapkan

Normal seperi biasa

### Tangkapan layar dan log error

<img width="960" alt="image" src="https://github.com/OpenSID/OpenSID/assets/48144047/6a0b34b0-9e46-4f31-9ccf-59c7c176dc02">

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

21.06 rev03

**Comment by pandigresik** [comment]
![image](https://github.com/OpenSID/OpenSID/assets/1853475/7109889b-ac05-4797-88c1-ec463b6be432)
Saya coba tambahkan 2 penduduk aman

**Comment by pandigresik** [comment]
![image](https://github.com/OpenSID/OpenSID/assets/1853475/bac05c2e-7739-48c2-b861-aefc5307ab03)
di berputar.opendesa.id memang error, di log aplikasi juga tidak ada info mengenai error tersebut. Harus cek log web servernya juga sepertinya

**Comment by andifahruddinakas** [comment]
> ![image](https://user-images.githubusercontent.com/1853475/249021470-bac05c2e-7739-48c2-b861-aefc5307ab03.png) di berputar.opendesa.id memang error, di log aplikasi juga tidak ada info mengenai error tersebut. Harus cek log web servernya juga sepertinya

<img width="623" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/0effd08d-eb0e-47af-8ba3-0791ca541398">

**Comment by pandigresik** [comment]
> > ![image](https://user-images.githubusercontent.com/1853475/249021470-bac05c2e-7739-48c2-b861-aefc5307ab03.png) di berputar.opendesa.id memang error, di log aplikasi juga tidak ada info mengenai error tersebut. Harus cek log web servernya juga sepertinya
> 
> <img alt="image" width="623" src="https://user-images.githubusercontent.com/57283157/249023291-0effd08d-eb0e-47af-8ba3-0791ca541398.png">

bisa share log web servernya, barangkali ada petunjuk lain

**Comment by andifahruddinakas** [comment]
> > > ![image](https://user-images.githubusercontent.com/1853475/249021470-bac05c2e-7739-48c2-b861-aefc5307ab03.png) di berputar.opendesa.id memang error, di log aplikasi juga tidak ada info mengenai error tersebut. Harus cek log web servernya juga sepertinya
> > 
> > 
> > <img alt="image" width="623" src="https://user-images.githubusercontent.com/57283157/249023291-0effd08d-eb0e-47af-8ba3-0791ca541398.png">
> 
> bisa share log web servernya, barangkali ada petunjuk lain

lognya ada di modul info_sistem > log

**Comment by pandigresik** [comment]
> > > > ![image](https://user-images.githubusercontent.com/1853475/249021470-bac05c2e-7739-48c2-b861-aefc5307ab03.png) di berputar.opendesa.id memang error, di log aplikasi juga tidak ada info mengenai error tersebut. Harus cek log web servernya juga sepertinya
> > > 
> > > 
> > > <img alt="image" width="623" src="https://user-images.githubusercontent.com/57283157/249023291-0effd08d-eb0e-47af-8ba3-0791ca541398.png">
> > 
> > 
> > bisa share log web servernya, barangkali ada petunjuk lain
> 
> lognya ada di modul info_sistem > log

log apache maksud saya, kalau log sistem sudah saya cek dan tidak ada informasi yang menunjukkan error tersebut

**Comment by pandigresik** [comment]
![image](https://github.com/OpenSID/OpenSID/assets/1853475/6aa67d21-f299-4b3a-8db4-758e77da58f3)
https://beta.opendesa.id/suplemen/rincian/1 aman

**Comment by andifahruddinakas** [comment]
Duplicate issue https://github.com/OpenSID/OpenSID/issues/6826
