### ISSUE TITLE
Bug/error: Data Rumah Tangga Terhapus Saat Update

### ISSUE THREAD

**Issue by wahyabiantara** [OpenSID/OpenSID#6800]
### Jelaskan error yg dialami

Sebelumnya desa sudah menginput data Rumah Tangga di masing - masing Banjar. Saat dilakukan upgrade, ternyata data Rumah Tangga tersebut hilang dari sistem. 

### Cara untuk mereplikasi errornya

Upgrade normal tanpa menimpa folder desa

### Hasil yg diharapkan

Jika ada perubahan struktur pada table, sebaiknya saat upgrade existing table tidak di hapus namun cukup di alter.

### Tangkapan layar dan log error

![56ddb4a5-cff3-4924-90b1-35c05e43463a](https://github.com/OpenSID/OpenSID/assets/4361979/c360b277-4af6-41e3-8afd-10ef6f6288ee)

### Rilis Versi OpenSID

Rilis Umum

### Versi OpenSID

2305.0.0

**Comment by andifahruddinakas** [comment]
mas @wahyabiantara, bisa di sertakan tangkapan layar struktur tabel tweb_rtm dan datanya (sensor data penting)

**Comment by wahyabiantara** [comment]
Berikut saya lampirkan mas @andifahruddinakas terima kasih

![image](https://github.com/OpenSID/OpenSID/assets/4361979/d14be9cd-fd46-46aa-bd9c-167ca4b9bbb3)
