### ISSUE TITLE
Permintaan fitur: Menambahkan Nama Data Suplemen kedalam Kode Isian Surat RTF TinyMCE

### ISSUE THREAD

**Issue by khiar-rara** [OpenSID/OpenSID#6802]
### Apa kekurangan yg ingin diatasi?

Saat ini data suplemen tidak dapat digunakan untuk meninjau kondisi penduduk saat pencetakan surat. Misalnya : Data Suplemen "Narapidana", dalam pencetakan surat catatan berkelakuan baik atau surat keterangan bukan narapidana, tidak dapat ditinjau langsung dari data suplemen.

### Jelaskan solusi yg diinginkan

![suplemen surat](https://github.com/OpenSID/OpenSID/assets/74307159/0d797964-25cf-4592-bd42-fd0991616e52)
Dapat menambahkan Kode Isian berdasarkan data suplemen

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

v21.08-premium

### Informasi tambahan

-

**Comment by andifahruddinakas** [comment]
mas @khiar-rara, seperti apa contoh surat yang akan dibuat. bisa lampirkan filenya?

**Comment by khiar-rara** [comment]
masalahnya begini pak, saya punya beberapa data suplemen antara lain data narapidana dan data nikah belum lapor. saya ingin saat membuat surat catatan kelakuan baik, ada peringatan bahwa orang itu mantan narapidana atau bukan. begitu juga saat ingin membuat surat pengantar nikah, ada peringatan bahwa orang tersebut masih menikah belum lapor atau tidak. mungkin dimasa depan ada suplemen data lain lagi yang dibutuhkan.

saya tahu solusi yang saya sampaikan diatas kurang tepat. barangkali tim programmer ada solusi yang lebih tepat. itu yang saya butuhkan. terima kasih
