### ISSUE TITLE
Bug/error: Ada file asing yang terunduh ketika mencetak surat 

### ISSUE THREAD

**Issue by hy-reza** [OpenSID/OpenSID#6803]
### Jelaskan error yg dialami

Ketika saya mencetak surat ada file lain selain file pdf surat yang terunduh secara bersamaan dan loading page nya tidak berhenti (terus berputar)

### Cara untuk mereplikasi errornya

Pergi ke halaman cetak surat
Pilih surat
Isi form surat dan save
Klik tombol  cetak surat
error : ada 2 file yang terunduh (pdf dan file lain tsb)
error : loading tidak berhenti 

### Hasil yg diharapkan

Hanya file pdf surat yang terunduh dan loading web selesai

### Tangkapan layar dan log error

2 file yang terunduh :
![image](https://github.com/OpenSID/OpenSID/assets/93983098/3271c257-5458-48db-a949-07638d638011)

loading pada halaman web tidak berhenti setelah file terdownload :
![image](https://github.com/OpenSID/OpenSID/assets/93983098/87336918-0c27-42d6-af38-47f8961c50f4)

ketika halaman web direfresh :
![image](https://github.com/OpenSID/OpenSID/assets/93983098/446e0b47-9ef5-4eaf-a836-3e86e2008af7)

### Rilis Versi OpenSID

Rilis Umum

### Versi OpenSID

v2306.0.0

### Informasi tambahan

Error terjaddi pada semua jenis surat ketika di cetak

detail file asing
![image](https://github.com/OpenSID/OpenSID/assets/93983098/e52dbfe6-7d5e-4549-9e1d-c28352a718cc)

**Comment by andifahruddinakas** [comment]
cek di https://devumum.opendesa.id/ untuk versi yang akan datang

**Comment by hy-reza** [comment]
> cek di https://devumum.opendesa.id/ untuk versi yang akan datang

apakah semua juga mengalami masalah ini ?
dan untuk umum kapan bisa update ke versi baru ya ?

**Comment by andifahruddinakas** [comment]
> > cek di https://devumum.opendesa.id/ untuk versi yang akan datang
> 
> apakah semua juga mengalami masalah ini ? dan untuk umum kapan bisa update ke versi baru ya ?

tgl 1

**Comment by pandigresik** [comment]
coba matikan dulu internet download managernya

**Comment by hy-reza** [comment]
> coba matikan dulu internet download managernya

Iya jika tidak pakai IDM normal

**Comment by andifahruddinakas** [comment]
https://forum.opendesa.id/d/299-terdapat-file-asing-saat-cetak-surat-tinymce
