### ISSUE TITLE
Tambahkan notifikasi terkait tombol backup tidak bisa di download

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#6805]
Backup tidak dapat dilakukan karena keterbatasan memori belum sesuai, silahkan periksa disini.

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2522

**Comment by gryve-lab** [comment]
Backup tidak dapat dilakukan karena keterbatasan memori belum sesuai. opensid 2407
