### ISSUE TITLE
Cek terkait lupa absen pulang di presensi aparatur desa

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#6806]
1. Ketika aparatur desa sudah melakukan abses datang 
2. lalu ketika lupa absen pulang biasanya ketika sudah lewat jam pulang akan berubah status menjadi lupa absesn pulang 
3. namun saat ini masih status itu tidak berubah

**Comment by agungsugiarto** [comment]
kurang spesifik tidak bisa saya test mas @vickyrolanda

**Comment by FirlianiF** [comment]
> kurang spesifik tidak bisa saya test mas @vickyrolanda

mas @vickyrolanda bisa dijelaskan langkah-langkah replikasi nya mas.

**Comment by andifahruddinakas** [comment]
Sementara issue di tutup sampai adannya laporan baru.
