### ISSUE TITLE
cek terkait tombol centang di aparatur desa ketika salah satu aparatur desa di uncentang maka info keterangan hadir masih muncul di halaman depan

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#6807]
1. ketika aparatur desa status 
<img width="472" alt="image" src="https://github.com/OpenSID/OpenSID/assets/59082428/7138d58b-c0b9-4fff-9dd2-15106db48da0">

2. tapi di tampilan aparatur desa bagian absennya masih muncul keterangan hadir seharusnya keterangan itu tidak muncul

**Comment by agungsugiarto** [comment]
kurang spesifik halaman depan itu maksudnya dibagian mana mas @vickyrolanda ?

**Comment by andifahruddinakas** [comment]
Admin : 
<img width="392" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/56983e8f-eda0-4c5c-9b65-6e25fead7bf4">

Hasil : 
![image](https://github.com/OpenSID/OpenSID/assets/57283157/f1c376ac-6cf3-4118-8ef7-a7dad3c76a48)

Harusnya info mengenai kehadiran tidak tampil sesuai pengaturan admin.

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2559
