### ISSUE TITLE
surat TinyMCE perjalanan dinas tidak dapat di cetak (SUSULAN)

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#6808]

**Comment by pandigresik** [comment]
Apakah muncul error seperti ini 
Exception: Xdebug has detected a possible infinite loop, and aborted your script with a stack depth of '256' frames /data/docker/opendesa/premium/vendor/tecnickcom/tcpdf/include/tcpdf_static.php 2516

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/OpenSID/issues/6808
