### ISSUE TITLE
Sesuaiakan Tampilan statistik jawaban dengan SID 3.10 

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#681]
statistik jawaban yang ada di pasca 2.5.1 tombol Cancel tidak ada
![tangkapan layar 2017-10-15 15 05 26](https://user-images.githubusercontent.com/25834335/31582701-af166b4e-b1bd-11e7-8748-468f3c61a475.png)
dan untuk statistinya di samping seperti SID 3.10
![tangkapan layar 2017-10-15 15 04 36](https://user-images.githubusercontent.com/25834335/31582704-c179961c-b1bd-11e7-9959-1be996148707.png)

**Comment by MUHAMMADRANGSEL** [comment]
Kalau yg lain sdh ok

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
Ujicoba di http://sid.bangundesa.info/index.php/analisis_statistik_jawaban/grafik_parameter/3.

Tapi pada penampilan awal, seluruh chart tidak tampil. Untuk ditampilkan secara keseluruhan, klik pemisah di sebelah kiri chart untuk tutup dan buka kembali.

Sementara belum ketemu solusinya.
