### ISSUE TITLE
Bug/error: Hasil eksport urutannya terbalik untuk tabel kelompok

### ISSUE THREAD

**Issue by pandigresik** [OpenSID/OpenSID#6812]
### Jelaskan error yg dialami

Hasil eksport urutannya terbalik untuk tabel kelompok, kelompok_master dan kelompok_anggota

### Cara untuk mereplikasi errornya

1. Lakukan eksport database melalui Pengaturan - database - unduh database
2. Lakukan import / restore dari hasil diatas
3. Terjadi gagal restore karena urutan tabel terbalik dengan pesan error seperti dibawah ini
`ERROR 1005 (HY000) at line 30622: Can't create table kelompok_anggota (errno: 150 "Foreign key constraint is incorrectly formed")`

### Hasil yg diharapkan

Hasil eksport valid dan dapat diimport lagi

### Tangkapan layar dan log error

ERROR 1005 (HY000) at line 30622: Can't create table batungsel.kelompok_anggota (errno: 150 "Foreign key constraint is incorrectly formed")

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2306.0.3

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2525

**Comment by andifahruddinakas** [comment]
maasih berkaitan dengan perubahan https://github.com/OpenSID/OpenSID/issues/6736
