### ISSUE TITLE
Bug/error: List Aparatur Desa masih muncul pada Data Staf Pengaturan Pengguna

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#6813]
### Jelaskan error yg dialami

data aparatur sudah digunakan pada salah satu pengguna dan berstatus aktif, ketika membuat pengguna baru, nama aparatur desa tersebut saat ini tetap muncul.

### Cara untuk mereplikasi errornya

1. masuk menu Pengaturan -> Pengguna
2. klik Tambah Pengguna baru
3. Pilih salah satu Data Staf

Lalu
1. klik Tambah Pengguna baru (lagi)
2. Pilih salah satu Data Staf, maka Data Staf yang semula sudah dibuat masih muncul

### Hasil yg diharapkan

Seharusnya Data Staf tidak muncul ketika sudah digunakan oleh Akun Pengguna Lain.

Begitu juga ketika Edit Pengguna, maka Data Staf hanya tampil yang sudah dipilih dan yang belum dipilih. 

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Rilis Mendatang

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2541
