### ISSUE TITLE
Bug/error: Tidak bisa simpan saat ubah pengaturan surat rtf

### ISSUE THREAD

**Issue by apidong** [OpenSID/OpenSID#6814]
### Jelaskan error yg dialami

Tidak bisa simpan saat ubah pengaturan surat rtf

### Cara untuk mereplikasi errornya

1. edit salah satu pengaturan surat rtf
2. simpan
3. error masuk halaman periksa

### Hasil yg diharapkan

-

### Tangkapan layar dan log error
![image](https://github.com/OpenSID/OpenSID/assets/20056421/8b19dfa1-bc13-421c-ba1f-054f2a0086bb)
![image](https://github.com/OpenSID/OpenSID/assets/20056421/87410c0a-d471-4c07-aca5-77de5885314a)
log error
```
ERROR - 2023-06-28 17:56:19 --> Query error: Unknown column 'id_surat' in 'field list' - Invalid query: UPDATE `tweb_surat_format` SET `id_surat` = '325', `kode_surat` = 'S-03', `nama` = 'Biodata Penduduk', `masa_berlaku` = '1', `satuan_masa_berlaku` = 'M', `logo_garuda` = '0', `mandiri` = '1', `url_surat` = 'surat_bio_penduduk'
WHERE   (
`config_id` = 3
 ) 
```
-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

-

### Tema Yang Digunakan

-

### Informasi tambahan

-

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/2536
