### ISSUE TITLE
Bug/error: Sesuaikan dengan Sebutan Aparatur Desa

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#6815]
### Jelaskan error yg dialami

Saat ini pada widget aparatur desa masih hardcode. belum menyesuaikan dengan Pengaturan sebutan Pemerintah Desa.

<img width="430" alt="image" src="https://github.com/OpenSID/OpenSID/assets/46939846/287eccc8-681d-4dd5-8281-4a98da7b6c60">

<img width="491" alt="image" src="https://github.com/OpenSID/OpenSID/assets/46939846/ab41adc8-400d-45c8-bf2e-ad4a3b766533">

### Cara untuk mereplikasi errornya

masih menu Info Desa -> Pemeitnah Desa, klik icon gear di pojok kanan atas, maka akan ada setting sebutan pemerintah desa.
yang sudah lama tersedia di Premium dan akan masuk umum rilis bulan Juli mendatang 2307

### Hasil yg diharapkan

Seharusnya disesuaikan.

### Tangkapan layar dan log error

di atas

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Rilis Mendatang

**Comment by andifahruddinakas** [comment]
SOLUSI : 
- [ ] sesuaikan halaman ini : 
<img width="500" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/3aeda06a-ead0-4286-b6e1-d8643180019c"><br>
- [ ] tambahkan migrasi untuk mengubah data widget pada tabel 'widget', dengan judul  'Aparatur Desa'. Ganti dengan  [Aparatur Desa]<br>
- [ ] sebelum menampilkan data, lakukan replace [Aparatur Desa] sesuai dengan pengaturan aplikasi untuk sebutan_aparatur_desa<br>
- [ ] sesuaikan halaman saat melihat detail data aparatur: <br>
![image](https://github.com/OpenSID/OpenSID/assets/57283157/8ab41429-a035-4e60-ba6b-5edca19bc8a6)<br>

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2566
