### ISSUE TITLE
Bug/error: botton surat menunggu ditandatangi tidak bisa di klik kepala desa

### ISSUE THREAD

**Issue by Agungf19** [OpenSID/OpenSID#6816]
### Jelaskan error yg dialami

saaat surat di disetujui dan diteruskan kepala desa, kepala desa tidak bisa meng klik button menunggu ditandatangani karena disable, mohon segera diperbaiki

### Cara untuk mereplikasi errornya

1. buat surat layanan mandiri
2. kemudian kirim
3. operator desa memverifikasi surat
4. disetujui
5. kemudian kepala desa tidak bisa klik button menunggu ditandatangi

### Hasil yg diharapkan

segera perbaiki

### Tangkapan layar dan log error

![1](https://github.com/OpenSID/OpenSID/assets/43205017/ae37498a-c2eb-4bce-a8df-35aa83224e75)
![2](https://github.com/OpenSID/OpenSID/assets/43205017/f982c34c-b05d-4eaf-84bd-7cfb65657acc)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Versi 2306.0.1-premium

### Tema Yang Digunakan

Batuah 23.02

### Informasi tambahan

-

**Comment by habibie11** [comment]
Sudah di cek tidak ada masalah. jika masih bermasalah bisa lakukan upgrade ke versi terbaru.
![image](https://github.com/OpenSID/OpenSID/assets/56639378/da8121d5-3c59-4ed8-aaa0-41ef90e70a31)
