### ISSUE TITLE
Bug/error: Nama Anak Tidak Muncul Saat Input KIA

### ISSUE THREAD

**Issue by wahyabiantara** [OpenSID/OpenSID#6817]
### Jelaskan error yg dialami

Saat mencoba memasukan KIA pada menu Stunting, setelah memilih nama Ibu, Nama Anak tidak mau muncul sehingga user tidak dapat memilih nama anak yang akan didaftarkan. Saya tidak menemukan error ini di https://berputar.opendesa.id/ namun dibeberapa website desa yang kami tangani hal ini masih tetap muncul.

Error log yang muncul di Pengaturan > Info Sistem
Severity: error --> Exception: Argument 1 passed to Illuminate\Database\Query\Builder::cleanBindings() must be of the type array, null given, called in /home/desabeng/pandakbandung.id/vendor/illuminate/database/Query/Builder.php on line 997 /home/desabeng/pandakbandung.id/vendor/illuminate/database

Error log yang muncul di browser console
Failed to load resource: the server responded with a status of 500 () getAnak?ibu=8519

### Cara untuk mereplikasi errornya

1. Klik menu Stunting
2. Klik Kesehatan Ibu dan Anak
3. Tambah
4. Masukan Nomor KIA
5. Pilih nama Ibu

### Hasil yg diharapkan

Pemilihan nama anak dapat berjalan sesuai harapan

### Tangkapan layar dan log error

<img width="1280" alt="Screen Shot 2023-06-29 at 10 45 03" src="https://github.com/OpenSID/OpenSID/assets/4361979/9ec630f6-0239-4275-9702-c435a868eab3">

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2306.0.2-premium

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2544

**Comment by wahyabiantara** [comment]
Terima kasih team. Berarti nanti akan masuk ke update 2308 premium ya?

**Comment by andifahruddinakas** [comment]
> Terima kasih team. Berarti nanti akan masuk ke update 2308 premium ya?

ya
