### ISSUE TITLE
Tidak bisa post html Artikel Video SID 2.5.1

### ISSUE THREAD

**Issue by adittravel** [OpenSID/OpenSID#682]
Dear teman2
Saat ini saya tidak bisa membuat artikel dengan embed Youtube Video, 
setelah saya rubah kode ini bisa dilakukan, tp apakah ini aman dilakukan?? atau ada cara lain ?terima kasih 

`		Line 88 $this->_enable_xss		= (config_item('global_xss_filtering') === TRUE);
`
menjadi 
`		Line 88 $this->_enable_xss		= (config_item('global_xss_filtering') === FALSE);
`
/* Location: ./system/core/Input.php */

**Comment by bhien76** [comment]
Memang. Sejak rilis versi 2.5 xss filtering dikatifkan untuk mencegah serangan xss. jadi semua file yang ada script html dan javascript jadi tidak berfungsi. Kalau mematikan xss, web kita jadi tidak aman. kalau mau tetap memasang embed youtube atau yg lain, untuk sementara xssnya dimatikan tidak apa2. setelah kita masukkan embednya, xssnya kita aktifkan lagi. itu yg saya lakukan di web desa saya

**Comment by adittravel** [comment]
baik mas terima kasih sharingnya, jadi harus di manualkan ya

**Comment by bhien76** [comment]
iya. karena itu yg saya laukan

**Comment by rahmatID** [comment]
bhien76@ cara mnonaktifkan xssnya gimana langkah-langkahnya terimaksih.

**Comment by bhien76** [comment]
itu seperti yg ditunjukkan @adittravel diatas. Global XSS Filtering yg berisi xss filtering nilainya dari True diganti False. tempat filenya ada di donjo-app\config\config.php
