### ISSUE TITLE
Bug/error: Pilih penduduk pada tambah data peserta suplemen langsung tampil

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#6826]
### Jelaskan error yg dialami

Saat menambahkan data pserta suplemen baru, data langsung terpilih tanpa melakukan sesuatu.

### Cara untuk mereplikasi errornya

1. Masuk modul suplemen
2. Pilih / buat salah 1 suplemen
3. Tambah data warga / peserta
4. Pada pilih data langsung tampil

### Hasil yg diharapkan

Sebelum melakukan pencarian data penduduk sebaiknya datanya tidak tampil.

### Tangkapan layar dan log error

Saat ini : 
<img width="529" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/0fab929e-eee2-48c8-8029-45d6563876d8">

Harusnya : 
<img width="533" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/3446240a-c831-4479-bf65-271b5e94752b">

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v2307.0.0-premium

### Tema Yang Digunakan

bawaan

### Informasi tambahan

Bug terjadi setelah penggabungan issue https://github.com/OpenSID/OpenSID/issues/6599

**Comment by Agungf19** [comment]
sama seperti saya kejadianya, kadang ketika di pilih warganya data seperti rt rw dibagian bawah tidak muncul, jika di paksa untuk di simpan, berhasil tersimpan tp datanya kosong

**Comment by habibie11** [comment]
ini ternyata sudah di fix di https://github.com/OpenSID/premium/pull/2557

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2557
