### ISSUE TITLE
Bug/error: tidak bisa tambah data persil

### ISSUE THREAD

**Issue by Agungf19** [OpenSID/OpenSID#6829]
### Jelaskan error yg dialami

saat mau tambah data persil, saya klik tombol tambah persil kemudian error 500

### Cara untuk mereplikasi errornya

1. klik menu pertanahan
2. menu daftar persil
3. klik tombol tambah persil
4. kemudian muncul error

di info sistem muncul error seperti ini

Severity: error --> Exception: Call to undefined method Data_persil::navigasi_peta() /home/mudaapps/pojokwatu.id/donjo-app/core/MY_Log.php(206) : eval()'d code(1) : eval()'d code 148

### Hasil yg diharapkan

mohon segera diperbaiki

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/43205017/0e788426-fc9e-4171-ab4e-ae4f4fd86574)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Versi 2306.0.1-premium

### Tema Yang Digunakan

Batuah 23.02

**Comment by andifahruddinakas** [comment]
perbarui ke versi 2306.0.2-premium atau di atasnya

**Comment by Agungf19** [comment]
ok saya coba
