### ISSUE TITLE
Tidak bisa upload template master surat

### ISSUE THREAD

**Issue by sucamzo** [OpenSID/OpenSID#683]
Adakah yang bisa bantu untuk mengatasi masalah seperti ini
![screenshot at 2017-10-19 09-17-37](https://user-images.githubusercontent.com/32834121/31751345-0f93859e-b4af-11e7-838e-bc456985d4dd.png)
![screenshot at 2017-10-19 09-17-06](https://user-images.githubusercontent.com/32834121/31751353-187186e8-b4af-11e7-9604-d1202abcc7d2.png)

**Comment by bhien76** [comment]
kalau saya lihat, kayaknya jenis file yg diupload salah. jenis file yg bisa diupload adalah .rtf sedangkan jenis file yg abang upload jenisnya .doc. coba ubah dulu file docnya ke rtf terus coba upload lagi

**Comment by MUHAMMADRANGSEL** [comment]
Issue ini mohon ditutup
