### ISSUE TITLE
Bug/error: tidak bisa hapus peserta pada menu data suplemen

### ISSUE THREAD

**Issue by Agungf19** [OpenSID/OpenSID#6830]
### Jelaskan error yg dialami

saat ingin mengahpus peserta pada menu data suplemen muncul error seperti ini

![image](https://github.com/OpenSID/OpenSID/assets/43205017/5c624b0b-5060-4be9-905c-affaee5184df)

### Cara untuk mereplikasi errornya

1. data suplemen
2. misal data Guru ngaji
3. hapus peserta
4. maka akan muncul error seperti ini

![image](https://github.com/OpenSID/OpenSID/assets/43205017/8685672a-730a-4ddf-a2a6-1c0bb26bc5bd)

### Hasil yg diharapkan

mohon segera diperbaiki

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/43205017/c225b9ea-dbd4-4da1-8f2b-302befd60a6d)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Versi 2306.0.1-premium

### Tema Yang Digunakan

Batuah 23.02

**Comment by pandigresik** [comment]
coba upgrade dulu ke versi terbaru 2307

**Comment by Agungf19** [comment]
ok saya coba

**Comment by andifahruddinakas** [comment]
Sudah normal melalui PR https://github.com/OpenSID/premium/pull/2557
