### ISSUE TITLE
Bug/error: menu sidebar sering hilang saat melakukan pengaturan surat

### ISSUE THREAD

**Issue by Agungf19** [OpenSID/OpenSID#6831]
### Jelaskan error yg dialami

error yagn saya alami, ketika setting -seetting surat dan tambah surat tinymce, tiba tiba menu sidebar hilang seperti ini
![image](https://github.com/OpenSID/OpenSID/assets/43205017/c35ac971-3c98-4b8b-b1b7-f7cbca2f4097)

dan harus relog, baru bisa muncul kembali menunya

### Cara untuk mereplikasi errornya

1. pengaturan surat
2. tambah / edit surat
3. tiba - tiba menu sidebar hilang
![image](https://github.com/OpenSID/OpenSID/assets/43205017/390fde4e-513a-4013-ac77-3f8ad471388a)

hal itu terjadi ketika sudah tambah / edit beberapa surat

### Hasil yg diharapkan

mohon segera di perbaiki

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/43205017/79669951-3857-4c68-bd6f-28f3b28846a7)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Versi 2306.0.1-premium

### Tema Yang Digunakan

Batuah 23.02

**Comment by andifahruddinakas** [comment]
dari tangkapan layar yang ditampilkan, user tsb data session terhapus, sehingga akses modul yang user tsb miliki tidak ada.

![image](https://github.com/OpenSID/OpenSID/assets/57283157/58e91b72-d6c7-4e9a-af6a-dfe3eff836e1)

bisa lakukan relogin

**Comment by Agungf19** [comment]
maaf , bagaimana bisa sessionya bisa habis, padahal aplikasi sedang di operasikan beberapa menit ?
