### ISSUE TITLE
Bug/error: settingan mapbox tidak ada di pengaturan aplikasi

### ISSUE THREAD

**Issue by Agungf19** [OpenSID/OpenSID#6832]
### Jelaskan error yg dialami

saya barusan update ke versi 2307.0.0, saya coba lihat dipengaturan aplikasi kok tidak ada kolom untuk setting mapbox nya ya, apakah hanya saya saja atau ada yg lainya yg mengalami ?

akhirnya saya coba masukan token mapbox lewat database, tapi petanya jadi hitam seperti pada gambar
dan muncul error saat saya coba inspect element

![image](https://github.com/OpenSID/OpenSID/assets/43205017/ae25a5a4-5233-407f-9109-4f4a92dfa30b)

### Cara untuk mereplikasi errornya

token mapbox yang barusa saya generate 

pk.eyJ1IjoiYWd1bmdmMTYiLCJhIjoiY2xqbTIyMXBmMTE1ajNxazI4dzVwZ3V6aCJ9.NRLHR3JgNfSVdzPoRwiNgQ

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/43205017/e8d9882b-0438-4167-81ca-1cc587b9e201)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Versi 2307.0.0-premium

### Tema Yang Digunakan

Batuah 23.02

**Comment by Agungf19** [comment]
kalau di versi 2306.0.3 aman

**Comment by andifahruddinakas** [comment]
mas @Agungf19, pengaturan dipindahkan ke modul pemetaan.

<img width="683" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/ce2dad91-9f64-4fc4-a44a-ae0fae5bf7ca">

**Comment by Agungf19** [comment]
terus masalah token yang saya ganerate kok g bisa itu kenapa ya?
pk.eyJ1IjoiYWd1bmdmMTYiLCJhIjoiY2xqbTIyMXBmMTE1ajNxazI4dzVwZ3V6aCJ9.NRLHR3JgNfSVdzPoRwiNgQ
