### ISSUE TITLE
Penyesuaian tampilan statistik di Front End dengan SID 3.10

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#684]
Tampilan statistik di Fron End SID 3.10
![screenshot 2017-10-22 19 19 59](https://user-images.githubusercontent.com/25834335/31863597-1c2361a0-b782-11e7-8603-74f04686831f.png)

sedangkan di OpenSID
![screenshot 2017-10-22 19 22 48](https://user-images.githubusercontent.com/25834335/31863605-3ece7672-b782-11e7-8970-7c5a6b4557d1.png)

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
