### ISSUE TITLE
Bug/error: Insert pengaturan program DTKS config null

### ISSUE THREAD

**Issue by ruririzal** [OpenSID/OpenSID#6840]
### Jelaskan error yg dialami

Insert pengaturan program DTKS config_id null

### Cara untuk mereplikasi errornya

1. pergi ke menu satu data -> DTKS 
2. ubah pengaturan program dtks
3. cek di database nilai config null

### Hasil yg diharapkan

config tidak null

### Tangkapan layar dan log error

null

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

premium

**Comment by andifahruddinakas** [comment]
mas @ruririzal, ini sama kasusnya dengan issue https://github.com/OpenSID/OpenSID/issues/6793

saat ini susah duplikasi, karena setiap di cek kadang berhasil dan gagal. Solusi sederhananya mmang hanya perlu menambahkan config_id saat buat data. Namun perlu di cek ada, kenapa fungsi trait yang di gunakan tidak berjalan normal.

![image](https://github.com/OpenSID/OpenSID/assets/57283157/1283460a-652f-4da7-82e6-0fbdcf4af095)

**Comment by ruririzal** [comment]
> mas @ruririzal, ini sama kasusnya dengan issue #6793
> 
> saat ini susah duplikasi, karena setiap di cek kadang berhasil dan gagal. Solusi sederhananya mmang hanya perlu menambahkan config_id saat buat data. Namun perlu di cek ada, kenapa fungsi trait yang di gunakan tidak berjalan normal.
> 
> ![image](https://user-images.githubusercontent.com/57283157/251325841-1283460a-652f-4da7-82e6-0fbdcf4af095.png)

mas @andifahruddinakas. setau saya Model::insert($params) pada laravel memang mengabaikan scope dan observer mas, jadi data yang di insert sesuai dengan $params (misal ada field created_at pada tabel dan tidak disertakan pada $params, maka created_at itu akan null sesuai setting default dbnya)

**Comment by ruririzal** [comment]
@andifahruddinakas

**Comment by andifahruddinakas** [comment]
> > mas @ruririzal, ini sama kasusnya dengan issue #6793
> > saat ini susah duplikasi, karena setiap di cek kadang berhasil dan gagal. Solusi sederhananya mmang hanya perlu menambahkan config_id saat buat data. Namun perlu di cek ada, kenapa fungsi trait yang di gunakan tidak berjalan normal.
> > ![image](https://user-images.githubusercontent.com/57283157/251325841-1283460a-652f-4da7-82e6-0fbdcf4af095.png)
> 
> mas @andifahruddinakas. setau saya Model::insert($params) pada laravel memang mengabaikan scope dan observer mas, jadi data yang di insert sesuai dengan $params (misal ada field created_at pada tabel dan tidak disertakan pada $params, maka created_at itu akan null sesuai setting default dbnya)


gunakan Model::create($params) yang mendukung, biar lebih mudah kedepannya. tidak perlu menambah di 1 per 1 fuction yang ada. Atau gunakan pendekatan lain agar Model::insert($params) bisa menggunakan observer.

**Comment by ruririzal** [comment]
> gunakan Model::create($params) yang mendukung, biar lebih mudah kedepannya. tidak perlu menambah di 1 per 1 fuction yang ada. Atau gunakan pendekatan lain agar Model::insert($params) bisa menggunakan observer.

mas @andifahruddinakas, saya kurang tau dan tidak mengikuti dari awal mengenai topik issue yg dicantumkan diatas https://github.com/OpenSID/OpenSID/issues/6793 . 

Masing-masing mempunyai fungsinya sendiri, untuk pengaturan program DTKS ini saya pilih insert karena tidak perlu trigger event model dan attribute casting

![image](https://github.com/OpenSID/OpenSID/assets/28647065/0448da5b-0a8b-4698-b25b-8cc42d33f3a7)

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2554
