### ISSUE TITLE
Permintaan fitur: Shortcode Golongan Darah Anggota Keluarga

### ISSUE THREAD

**Issue by riduansalim** [OpenSID/OpenSID#6845]
### Apa kekurangan yg ingin diatasi?

Tidak dapat menambahkan shortcodes golongan darah untuk anggota keluarga di template surat

### Jelaskan solusi yg diinginkan

Penambahan shortcode untuk anggota keluarga pada pembuatan template surat
<img width="453" alt="image" src="https://github.com/OpenSID/OpenSID/assets/10606056/f37ae4fe-fc55-4f6c-af15-29e0edf67736">

### Apakah ada alternatif lain

Ditulis manual saat membuat cetak surat

### Untuk versi OpenSID mana

v2307.0.0-premium

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2642
