### ISSUE TITLE
Bug/error: Parse Error saat cetak surat pdf atau tinjau pdf 

### ISSUE THREAD

**Issue by dedecs** [OpenSID/OpenSID#6847]
### Jelaskan error yg dialami

Pada saat membuat surat pada layanan surat terdapat pesan parse error setelah menekan tombol cetak atau tinjau pdf 
![errrrr](https://github.com/OpenSID/OpenSID/assets/16379032/39bf5f3a-9e78-4087-b275-789f68ecdac1)

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

Muncul tampilan PDF

### Tangkapan layar dan log error

![errrrr](https://github.com/OpenSID/OpenSID/assets/16379032/246a15d2-15ff-41f5-b447-89b3aa13e0ab)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

premium 2307-premium

### Tema Yang Digunakan

natra

**Comment by andifahruddinakas** [comment]
mas @dedecs, sertakan template surat yang digunakan.

**Comment by makhbub** [comment]
saya juga mengalaminya,
tapi saat database di replikasi ke offline pakai xampp cetak surat berfungsi normal
