### ISSUE TITLE
Bug/error: tidak bisa cetak jika surat menggunakan lampiran F.201

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#6856]
### Jelaskan error yg dialami

tidak bisa cetak surat jika menggunakan lampiran F.2.01 di surat jenis TinyMCE

### Cara untuk mereplikasi errornya

1. buat surat  baru 
2. pilih lampiran dengan F.2.01
3. Lalu coba buat surat 
4. lalu klik tinjau / download pdf

### Hasil yg diharapkan

dapat membuat surat dengan lampiran F.2.01

### Tangkapan layar dan log error

<img width="760" alt="image" src="https://github.com/OpenSID/OpenSID/assets/59082428/cbff6040-6d07-49b0-a8f0-d7ce087b0ae2">

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v2307.0.0

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2593
