### ISSUE TITLE
Penambahan data yang dikirim ke server tracker pantau.opensid.my.id

### ISSUE THREAD

**Issue by pandigresik** [OpenSID/OpenSID#6859]
### Apa kekurangan yg ingin diatasi?

Saat ini opensid belum mengirimkan data jumlah keluarga, agar issue https://github.com/OpenSID/tracksid/issues/146 bisa sempurna maka opensid perlu menambahkan data jumlah keluarga untuk dikirim ke server pantau

### Jelaskan solusi yg diinginkan

Menambahkan jml_keluarga pada function kirim_data di Track_model

### Apakah ada alternatif lain

Tidak ada

### Untuk versi OpenSID mana

2308.0.0-premium

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2887
