### ISSUE TITLE
Penyesuaian Laporan Kelompok Rentan di menu Statistik seperti SID 3.10

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#686]
Penyesuaian Laporan Kelompok Rentan di menu Statistik seperti SID 3.10 dan menghapus kolom sakit menahun
![screenshot 2017-10-07 07 03 43](https://user-images.githubusercontent.com/25834335/31863678-679be070-b783-11e7-9eb3-e58f3d895038.png)

**Comment by eddieridwan** [comment]
Perubahan ini perlu disetujui oleh Pokja secara kolektif, karena belum tentu semua setuju.

Status kehamilan akan cepat berubah dan perangkat desa harus bisa mengupdate info ini secara rutin supaya mencerminkan keadaan terkini. Apa mungkin? Kalau tidak diupdate, maka akan berisi data salah.
