### ISSUE TITLE
Bug/error: eror modul pengaturan, sub modul tidak dapat ditampilkan

### ISSUE THREAD

**Issue by mah-mudi** [OpenSID/OpenSID#6861]
### Jelaskan error yg dialami

sub modul pengaturan tidak dapat ditampilkan

### Cara untuk mereplikasi errornya

klik modul pengaturan

### Hasil yg diharapkan

sub modul pengaturan dapat berjalan sebagaimana mestinya

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/57661283/dd5d072e-e8eb-418d-9967-d6d2275e5127)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

23.07.0.1

### Tema Yang Digunakan

silir

**Comment by andifahruddinakas** [comment]
bung @mah-mudi, agar lebih mudah melacaknya, bisa duplikasikan error ini di https://berputar.opendesa.id/

**Comment by mah-mudi** [comment]
@andifahruddinakas ok dicoba
