### ISSUE TITLE
Bug/error: Saat buka menu kehadiran, edit pengaturan dengan memberi nilai kosong pada rentang waktu kehadiran akan terjadi error

### ISSUE THREAD

**Issue by pandigresik** [OpenSID/OpenSID#6862]
### Jelaskan error yg dialami

Terdapat error di log
`Exception: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ') as jam_keluar from `kehadiran_jam_kerja` where `nama_hari` = 'Sabtu' and (t...' at line 1 (SQL: select id, nama_hari, jam_masuk, status, keterangan, date_add(jam_keluar, interval  minute) as jam_keluar from `kehadiran_jam_kerja` where `nama_hari` = Sabtu and (time(`jam_masuk`) > 12:17 or date_add(jam_keluar, interval ? minute) < 12:17) and `kehadiran_jam_kerja`.`config_id` = 5 limit 1) /home/mqensrir/public_html/vendor/illuminate/database/Connection.php 712`

### Cara untuk mereplikasi errornya

1. Masuk menu kehadiran
2. Buka pengaturan melalui icon gear pojok kanan atas
3. Hapus nilai pada field **rentang waktu kehadiran** sehingga bernilai kosong
4. Simpan, maka akan muncul error

### Hasil yg diharapkan

Tidak ada error

### Tangkapan layar dan log error
![image](https://github.com/OpenSID/OpenSID/assets/1853475/84e41045-b2b8-4ded-a7b4-c80b3eaed4cd)

<?php defined('BASEPATH') OR exit('No direct script access allowed'); ?>
ERROR - 2023-07-08 11:37:29 --> Severity: error --> Exception: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ') as jam_keluar from `kehadiran_jam_kerja` where `nama_hari` = 'Sabtu' and (t...' at line 1 (SQL: select id, nama_hari, jam_masuk, status, keterangan, date_add(jam_keluar, interval  minute) as jam_keluar from `kehadiran_jam_kerja` where `nama_hari` = Sabtu and (time(`jam_masuk`) > 11:37 or date_add(jam_keluar, interval ? minute) < 11:37) and `kehadiran_jam_kerja`.`config_id` = 5 limit 1) /home/mqensrir/public_html/vendor/illuminate/database/Connection.php 712

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2307.0.0 premium

**Comment by pandigresik** [comment]
solusi : 
public function scopeJamKerja($query)
    {
        $waktu   = date('H:i');
        $rentang = setting('rentang_waktu_kehadiran') ?? SettingAplikasi::RENTANG_WAKTU_KEHADIRAN;

        return $query
            ->selectRaw('id, nama_hari, jam_masuk, status, keterangan')
            ->selectRaw(sprintf('date_add(jam_keluar, interval %s minute) as jam_keluar', $rentang))
            ->where('nama_hari', $this->getNamaHari())
            ->where(static function ($q) use ($waktu) {
                $q->whereTime('jam_masuk', '>', $waktu)
                    ->orWhereRaw('date_add(jam_keluar, interval ? minute) < ?', [$rentang, $waktu]);
            });
    }
ubah menjadi
public function scopeJamKerja($query)
    {
        $waktu   = date('H:i');
        $rentang = setting('rentang_waktu_kehadiran') ?? SettingAplikasi::RENTANG_WAKTU_KEHADIRAN;

        return $query
            ->selectRaw('id, nama_hari, jam_masuk, status, keterangan')
            ->selectRaw(sprintf('date_add(jam_keluar, interval %s minute) as jam_keluar', $rentang))
            ->where('nama_hari', $this->getNamaHari())
            ->where(static function ($q) use ($waktu, $rentang) {
                $q->whereTime('jam_masuk', '>', $waktu)
                    ->orWhereRaw('date_add(jam_keluar, interval ? minute) < ?', [$rentang, $waktu]);
            });
    }
pada file app/Models/JamKerja.php mulai baris 89

**Comment by andifahruddinakas** [comment]
tambahan : 
- [x] jika disimpan kosong, otomatis disimpan 0. tambahkan input sebagai angkan dimana min 0

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2584
