### ISSUE TITLE
Bug/error: dropdown kategori tidak muncul pada pengaturan peta

### ISSUE THREAD

**Issue by Agungf19** [OpenSID/OpenSID#6864]
### Jelaskan error yg dialami

dropdown kategori tidak muncul saat mau menambahkan lokasi, garis dan are

### Cara untuk mereplikasi errornya

1. pengaturan peta
2. lokasi
3. tambah lokasi
4. dropdown tidak muncul

### Hasil yg diharapkan

mohon di perbaiki

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/43205017/1b302268-69d5-4b67-aa75-d305e771bf3f)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Versi 2307.0.0-premium

### Tema Yang Digunakan

Batuah 23.02

**Comment by balongbesuk** [comment]
pada menu pengaturan peta > tipe lokasinya d isi dlu

**Comment by Agungf19** [comment]
sudah saya isi, tp tetep tidak muncul
![image](https://github.com/OpenSID/OpenSID/assets/43205017/ca0ead1d-a938-44d6-8195-9a47a9aa6b97)
