### ISSUE TITLE
Bug/error: Identitas desa tidak tampil pada anjugan mandiri

### ISSUE THREAD

**Issue by pandigresik** [OpenSID/OpenSID#6865]
### Jelaskan error yg dialami

![image](https://github.com/OpenSID/OpenSID/assets/1853475/1b33b14c-4925-45e6-a95e-6cce3616010c)
Buka anjugan mandiri, nama desa dan nama kecamatan tidak tampil

### Cara untuk mereplikasi errornya

Buka anjugan mandiri, nama desa dan nama kecamatan tidak tampil

### Hasil yg diharapkan

Identitas desa tampil sebagaimana mestinya

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/1853475/1b33b14c-4925-45e6-a95e-6cce3616010c)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2307.0.1 premium

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui commit https://github.com/OpenSID/premium/commit/81d855c494779f2c14a21eb7b9e1aa7dc409a41b
