### ISSUE TITLE
Bug/error: Identitas desa tidak muncul pada buku tamu

### ISSUE THREAD

**Issue by pandigresik** [OpenSID/OpenSID#6866]
### Jelaskan error yg dialami

Identitas desa tidak muncul pada halaman buku tamu

### Cara untuk mereplikasi errornya

1. Masuk ke halaman buku tamu
2. Pastikan sudah memiliki lisensi untuk akses anjungan
3. Identitas desa tidak tampil

### Hasil yg diharapkan

Identitas desa tampil sebagaimana mestinya

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/1853475/59d18c6e-a565-4793-a61b-19e492811092)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2307.0.1

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui commit https://github.com/OpenSID/premium/commit/81d855c494779f2c14a21eb7b9e1aa7dc409a41b
