### ISSUE TITLE
View data peristiwa lahir

### ISSUE THREAD

**Issue by yogiperdana** [OpenSID/OpenSID#6867]
1. Perlu ditambahkan kode isian khusus peristiwa lahir 
<img width="372" alt="image" src="https://github.com/OpenSID/OpenSID/assets/59082428/abe7bfa3-8a48-4b17-9b40-5d165ae2a896">

di bagian cetak muncul seperti berikut : 
<img width="407" alt="image" src="https://github.com/OpenSID/OpenSID/assets/59082428/feeae18a-a055-4690-8dac-1ad7d4f18402">

**Comment by yogiperdana** [comment]
Referensinya bisa lihat di data peristiwa yang lain. Ada di kode isian dan viewnya

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2635
