### ISSUE TITLE
Bug/error: Opensid eror tracker di pantau opensid

### ISSUE THREAD

**Issue by mah-mudi** [OpenSID/OpenSID#6868]
### Jelaskan error yg dialami

tracker tidak menampilkan update sebenarnya, dan menyebabkan lambat dalam penambahan menu dan penambahan kategori

### Cara untuk mereplikasi errornya

https://pantau.opensid.my.id/laporan/desa?status=1&kode_kabupaten=35.25&kode_provinsi=35

### Hasil yg diharapkan

tracker menampilkan sebenarnya, dan opensid dapat berjalan dengan lancar

### Tangkapan layar dan log error

GuzzleHttp\Exception\ConnectException: cURL error 28: Operation timed out after 5001 milliseconds with 0 bytes received (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://pantau.opensid.my.id/api/track/desa?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6bnVsbCwidGltZXN0YW1wIjo
NjAzNDY2MjM5fQ.HVCNnMLokF2tgHwjQhSIYo6-2GNXB4-Kf28FSIeXnZw in /home/desalerangresikk/public_html/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:210Stack trace:#0 /home/desalerangresikk/public_html/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(158): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)#1 /home/desalerangresikk/public_html/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(110): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))#2 /home/desalerangresikk/public_html/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(47): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))#3 /home/desalerangresikk/public_html/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(28): GuzzleHttp\Handler\CurlHandler->__invoke(Object(GuzzleHttp\Psr7\Request), Array)#4 /home/desalerangresikk/public_html/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(48): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}(Object(GuzzleHttp\Psr7\Request), Array)#5 /home/desalerangresikk/public_html/vendor/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php(64): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}(Object(GuzzleHttp\Psr7\Request), Array)#6 /home/desalerangresikk/public_html/vendor/guzzlehttp/guzzle/src/Middleware.php(31): GuzzleHttp\PrepareBodyMiddleware->__invoke(Object(GuzzleHttp\Psr7\Request), Array)#7 /home/desalerangresikk/public_html/vendor/guzzlehttp/guzzle/src/RedirectMiddleware.php(71): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Request), Array)#8 /home/desalerangresikk/public_html/vendor/guzzlehttp/guzzle/src/Middleware.php(66): GuzzleHttp\RedirectMiddleware->__invoke(Object(GuzzleHttp\Psr7\Request), Array)#9 /home/desalerangresikk/public_html/vendor/guzzlehttp/guzzle/src/HandlerStack.php(75): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Request), Array)#10 /home/desalerangresikk/public_html/vendor/guzzlehttp/guzzle/src/Client.php(333): GuzzleHttp\HandlerStack->__invoke(Object(GuzzleHttp\Psr7\Request), Array)#11 /home/desalerangresikk/public_html/vendor/guzzlehttp/guzzle/src/Client.php(169): GuzzleHttp\Client->transfer(Object(GuzzleHttp\Psr7\Request), Array)#12 /home/desalerangresikk/public_html/vendor/guzzlehttp/guzzle/src/Client.php(189): GuzzleHttp\Client->requestAsync('POST', Object(GuzzleHttp\Psr7\Uri), Array)#13 /home/desalerangresikk/public_html/vendor/guzzlehttp/guzzle/src/ClientTrait.php(95): GuzzleHttp\Client->request('POST', 'https://pantau....', Array)#14 /home/desalerangresikk/public_html/donjo-app/core/MY_Log.php(206) : eval()'d code(1) : eval()'d code(258): GuzzleHttp\Client->post('https://pantau....', Array)#15 /home/desalerangresikk/public_html/donjo-app/core/MY_Log.php(206) : eval()'d code(1) : eval()'d code(140): httpPost('https://pantau....', Array)#16 /home/desalerangresikk/public_html/donjo-app/core/MY_Log.php(206) : eval()'d code(1) : eval()'d code(73): Track_model->kirim_data()#17 /home/desalerangresikk/public_html/donjo-app/core/MY_Log.php(206) : eval()'d code(1) : eval()'d code(105): Track_model->track_desa('first')#18 /home/desalerangresikk/public_html/vendor/codeigniter/framework/system/core/CodeIgniter.php(533): First->index()#19 /home/desalerangresikk/public_html/index.php(284): require_once('/home/desaleran...')#20 {main}

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

23.07.0.1

### Tema Yang Digunakan

silir

### Informasi tambahan

https://pantau.opensid.my.id/laporan/desa?status=1&kode_kabupaten=35.25&kode_provinsi=35

**Comment by apidong** [comment]
> ### Jelaskan error yg dialami
> tracker tidak menampilkan update sebenarnya, dan menyebabkan lambat dalam penambahan menu dan penambahan kategori
> 
> ### Cara untuk mereplikasi errornya
> https://pantau.opensid.my.id/laporan/desa?status=1&kode_kabupaten=35.25&kode_provinsi=35
> 
> ### Hasil yg diharapkan
> tracker menampilkan sebenarnya, dan opensid dapat berjalan dengan lancar
> 
> ### Tangkapan layar dan log error
> GuzzleHttp\Exception\ConnectException: cURL error 28: Operation timed out after 5001 milliseconds with 0 bytes received (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://pantau.opensid.my.id/api/track/desa?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6bnVsbCwidGltZXN0YW1wIjo NjAzNDY2MjM5fQ.HVCNnMLokF2tgHwjQhSIYo6-2GNXB4-Kf28FSIeXnZw in /home/desalerangresikk/public_html/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:210Stack trace:#0 /home/desalerangresikk/public_html/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(158): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)#1 /home/desalerangresikk/public_html/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(110): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))#2 /home/desalerangresikk/public_html/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(47): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))#3 /home/desalerangresikk/public_html/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(28): GuzzleHttp\Handler\CurlHandler->__invoke(Object(GuzzleHttp\Psr7\Request), Array)#4 /home/desalerangresikk/public_html/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(48): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler{closure}(Object(GuzzleHttp\Psr7\Request), Array)#5 /home/desalerangresikk/public_html/vendor/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php(64): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler{closure}(Object(GuzzleHttp\Psr7\Request), Array)#6 /home/desalerangresikk/public_html/vendor/guzzlehttp/guzzle/src/Middleware.php(31): GuzzleHttp\PrepareBodyMiddleware->__invoke(Object(GuzzleHttp\Psr7\Request), Array)#7 /home/desalerangresikk/public_html/vendor/guzzlehttp/guzzle/src/RedirectMiddleware.php(71): GuzzleHttp\Middleware::GuzzleHttp{closure}(Object(GuzzleHttp\Psr7\Request), Array)#8 /home/desalerangresikk/public_html/vendor/guzzlehttp/guzzle/src/Middleware.php(66): GuzzleHttp\RedirectMiddleware->__invoke(Object(GuzzleHttp\Psr7\Request), Array)#9 /home/desalerangresikk/public_html/vendor/guzzlehttp/guzzle/src/HandlerStack.php(75): GuzzleHttp\Middleware::GuzzleHttp{closure}(Object(GuzzleHttp\Psr7\Request), Array)#10 /home/desalerangresikk/public_html/vendor/guzzlehttp/guzzle/src/Client.php(333): GuzzleHttp\HandlerStack->__invoke(Object(GuzzleHttp\Psr7\Request), Array)#11 /home/desalerangresikk/public_html/vendor/guzzlehttp/guzzle/src/Client.php(169): GuzzleHttp\Client->transfer(Object(GuzzleHttp\Psr7\Request), Array)#12 /home/desalerangresikk/public_html/vendor/guzzlehttp/guzzle/src/Client.php(189): GuzzleHttp\Client->requestAsync('POST', Object(GuzzleHttp\Psr7\Uri), Array)#13 /home/desalerangresikk/public_html/vendor/guzzlehttp/guzzle/src/ClientTrait.php(95): GuzzleHttp\Client->request('POST', 'https://pantau....', Array)#14 /home/desalerangresikk/public_html/donjo-app/core/MY_Log.php(206) : eval()'d code(1) : eval()'d code(258): GuzzleHttp\Client->post('https://pantau....', Array)#15 /home/desalerangresikk/public_html/donjo-app/core/MY_Log.php(206) : eval()'d code(1) : eval()'d code(140): httpPost('https://pantau....', Array)#16 /home/desalerangresikk/public_html/donjo-app/core/MY_Log.php(206) : eval()'d code(1) : eval()'d code(73): Track_model->kirim_data()#17 /home/desalerangresikk/public_html/donjo-app/core/MY_Log.php(206) : eval()'d code(1) : eval()'d code(105): Track_model->track_desa('first')#18 /home/desalerangresikk/public_html/vendor/codeigniter/framework/system/core/CodeIgniter.php(533): First->index()#19 /home/desalerangresikk/public_html/index.php(284): require_once('/home/desaleran...')#20 {main}
> 
> ### Rilis Versi OpenSID
> Rilis Premium
> 
> ### Versi OpenSID
> 23.07.0.1
> 
> ### Tema Yang Digunakan
> silir
> 
> ### Informasi tambahan
> https://pantau.opensid.my.id/laporan/desa?status=1&kode_kabupaten=35.25&kode_provinsi=35

untuk error koneksi ke pantau. lakukan pengecekan
1. Akses website pantau.opensid.my.id melalui web browser. jika tidak bisa diakses, kemungkinan website sedang down, solusinya tunggu beberapa saat.
2. lakukan ping melalui terminal ke pantau.opensid.my.id. jika gagal melakukan ping, hubungi pihak webhosting agar server bisa terhubung dengan pantau.
