### ISSUE TITLE
Sinergi Program

### ISSUE THREAD

**Issue by rahmatID** [OpenSID/OpenSID#687]
Mohon Bantuannya Para Master ketika load gambar di Widget Sinergi Program kenapa tidak muncul22 cuman tulisanny aja yang muncun terimaksih. saya pakainya OpenSID 2.5.1
Screnshoot seperti gambar dibawah.
![klh4](https://user-images.githubusercontent.com/33047455/31923922-e99daab6-b8a7-11e7-9c53-d044c6ff27ed.png)

**Comment by eddieridwan** [comment]
@rahmatID : masalah penggunaan sebaiknya ditanyakan di https://www.facebook.com/groups/OpenSID/ -- di situ ada banyak yang bisa membantu.

Issue fungsinya untuk tugas programming untuk masalah yang jelas perlu diperbaiki. 

Untuk masalah anda, coba lakukan di situs demo di http://sid.bangundesa.info. Kalau bisa di situs demo, berarti masalahnya terletak di instalasi anda.

Ok, kami akan tutup issue ini. Kalau nanti ternyata memang ada script yg perlu diperbaiki, silakan buat issue baru.
