### ISSUE TITLE
BUG: Login awal sebagai user pertama setelah install baru tidak bisa ganti password

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/OpenSID#6872]
### Jelaskan error yg dialami
Saat install baru di versi 2307.0.1-premium tidak dapat ubah password pada user pertama setelah install, seharusnya diarahkan ke halaman untuk ubah password bawaan agar diubah oleh pengguna. 

Pada issue ini diarahkan ke halaman berikut:
![image](https://github.com/OpenSID/OpenSID/assets/68048807/b1cd84fe-362b-420e-8dbf-0507353004c6)

Kemudian dilakukan pengubahan pada pengaturan pengguna, namun gagal seperti gambar berikut:
![gagal ubah password](https://github.com/OpenSID/OpenSID/assets/68048807/9998de40-c78d-4b4c-a1b1-bf7a9b42d28c)

### Cara untuk mereplikasi errornya
1. Install baru OpenSID Premium Versi 2307.0.1-premium
2. Login dengan user dan password bawaan
3. Klik Menu Pengaturan
4. Pilih Pengguna
5. Klik tombol Ubah pengguna dengan username admin
6. Ubah Password.
7. Klik tombol Simpan

### Hasil yg diharapkan
dapat berjalan normal ubah password bawaan.

### Rilis Versi OpenSID
Rilis Premium

### Versi OpenSID
2307.0.1-premium

### Informasi tambahan
hanya terjadi di user admin.
namun tidak terjadi ketika buat user baru maupun edit user baru.

**Comment by andifahruddinakas** [comment]
https://github.com/OpenSID/premium/commit/95d6ec56967783e6234a105955826800c7f2a212
