### ISSUE TITLE
Bug/error: Halaman pengaduan pengguna tidak dapat diakses

### ISSUE THREAD

**Issue by hy-reza** [OpenSID/OpenSID#6874]
### Jelaskan error yg dialami

Saat mengakses halaman pengaduan terjadi error dimana halaman tidak dapat tampil

### Cara untuk mereplikasi errornya

Pergi ke halaman pengaduan
Lihat error dimana loading terus berjalan

### Hasil yg diharapkan

Halaman pengaduan bisa diakses secara normal

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/93983098/6d1df0ea-bfeb-4964-a1b3-0aca2f8175e1)

### Rilis Versi OpenSID

Rilis Umum

### Versi OpenSID

2307.0.0

**Comment by andifahruddinakas** [comment]
gunakan tema natra, untuk kasus ini sudah dibuatkan issue di https://github.com/OpenSID/tema-esensi/issues/39
