### ISSUE TITLE
Permintaan fitur: Belum tersedia informasi link website desa

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#6875]
### Apa kekurangan yg ingin diatasi?

<img width="357" alt="image" src="https://github.com/OpenSID/OpenSID/assets/46939846/00b2ce3e-ec6b-4458-b84c-9f44d10724c0">

### Jelaskan solusi yg diinginkan

adanya info link web desa pada informasi pengajuan surat seperti halnya saat notifikasi Login halaman admin.

berikut adalah Informasi Login Admin yang diterapkan saat ini:
[...] login Halaman Admin [...] pada tanggal 12 Juli 2023 13:26:40

WANDA INTAN SARI login Halaman Admin https://www.natairaya.desa.id/ pada tanggal 12 Juli 2023 13:26:40

pada informasi pengajuan surat secara default bisa ditambahkan informasi link web desa.

### Apakah ada alternatif lain

saat ini sudah tersedia default di Pengaturan -> Aplikasi yang perlu ditambah kode link desa:
Segera cek Halaman Admin, penduduk atas nama [nama_penduduk] telah mengajukan [judul_surat] melalui [melalui] pada tanggal [tanggal]

TERIMA KASIH.     

<img width="521" alt="image" src="https://github.com/OpenSID/OpenSID/assets/46939846/4d706715-137a-442b-930f-48cb9ba4b9dc">

### Untuk versi OpenSID mana

Rilis Mendatang

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/commit/acfb94ba435b886e4a1e2dd5afe1f0d328f14047
