### ISSUE TITLE
Tabel provinsi tidak ditemukan

### ISSUE THREAD

**Issue by batudaa** [OpenSID/OpenSID#688]
Install baru menggunakan database **contoh_data_awal_20170918.sql**
Table 'opensid.provinsi' doesn't exist, saat buka halaman ```hom_desa/konfigurasi```.

**Comment by eddieridwan** [comment]
Seperti biasa, jalankan Database > Migrasi DB untuk melengkapi struktur database utk versi yang digunakan. 

Contoh data awal yang lengkap ada di rilis. Versi yang di pra-rilis belum tentu berisi contoh data yang lengkap (karena memang belum dirilis). 

Contoh data awal sekarang sudah dimutakhirkan, sebagai persiapan untuk rilis pada tanggal 1 Nopember.
