### ISSUE TITLE
Bug/error: luas peta wilayah desa tidak tampil

### ISSUE THREAD

**Issue by habibie11** [OpenSID/OpenSID#6882]
### Jelaskan error yg dialami

luas peta wilayah desa tidak muncul di halaman peta padahal di pengaturan peta tampilkan luas wilayah pada peta sudah dipilih ya.

![image](https://github.com/OpenSID/OpenSID/assets/56639378/d6c93267-ecb1-43b2-9f5b-24bd9bf1430e)

### Cara untuk mereplikasi errornya

1. Pergi ke halaman Pemetaan>Peta
2. Klik tombol gear di kanan atas
3. Pilih Ya pada pengaturan peta tampilkan luas wilayah pada peta
4. Maka di map tidak tampil lokasi luas wilayah desa

### Hasil yg diharapkan

Map wilayah desa tampil sesuai pengaturan peta

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/56639378/e4b9b22e-d72f-436e-b21b-53c9a0b16494)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v2307.0.2

**Comment by habibie11** [comment]
setelah dicek peta wilayah desa bisa tampil sesuai pengaturan peta.
cc mas @andifahruddinakas 
![image](https://github.com/OpenSID/OpenSID/assets/56639378/514b89af-5646-43c2-8c51-c9f3fb1b8f90)

**Comment by andifahruddinakas** [comment]
mas @habibie11, yang dimaksud dengan luas peta seperti ini : 
<img width="348" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/8b6acb45-b8c5-4faa-9f33-201577a74ba8">

SOLUSI : 
- [ ] terapkan pengaturan luas peta pada modul pemetaan. Untuk contohnya bisa cek modul indentitas desa, atau wilayah administratif.
<img width="706" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/d7acdb4b-249e-418b-a616-00039340de94">

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2658
