### ISSUE TITLE
Bug/error: Penyesuaian akses hapus data penduduk ketika dinyatakan lengkap

### ISSUE THREAD

**Issue by wahyabiantara** [OpenSID/OpenSID#6885]
### Jelaskan error yg dialami

Administrator / User Terpercaya saat ini tidak bisa menghapus data penduduk meskipun pada file /desa/config/config.php sudah diatur sebagai berikut $config['user_admin'] = 1;

### Cara untuk mereplikasi errornya

1. Login dengan admin
2. Klik menu Kependudukan > Penduduk
3. Tombol Hapus Data tidak muncul

![image](https://github.com/OpenSID/OpenSID/assets/4361979/8a8243e0-c603-468c-931d-9e23f2e38423)

### Hasil yg diharapkan

Tombol Hapus Data seharsunya muncul untuk user terpercaya

![image](https://github.com/OpenSID/OpenSID/assets/4361979/52f0ac46-81ea-4b30-a046-876c8ee206a1)

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/4361979/8a8243e0-c603-468c-931d-9e23f2e38423)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2307.0.1-premium

**Comment by andifahruddinakas** [comment]
pak @wahyabiantara, untuk melakukan hapus penduduk hanya bisa dilakukan jika data dinyatakan belum lengkap. Namun dalam kondisi saat ini sepertinya terbalik. Issue ini akan saya ubah untuk memperbaiki kesssalahan tsb.

<img width="315" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/a86d7052-5bfa-4e06-a1d1-e268cb3a92d3">

SOLUSI : 
- [ ] tetapkan jika data dinyatakan belum lengkap, batasi agar tidak bisa menghapus data penduduk
- [ ] tambahkan juga pengaturan data lengkap pada modul penduduk
<img width="342" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/cbd19f41-6a75-46c3-bf5b-81e5d08f274f">

- [ ] buatkan helper untuk menyatakan data lengkap, karena digunakan dibeberapa modul dan sifatnya berulang.

**Comment by balongbesuk** [comment]
bukanny kl data lengkap memang tdk boleh d hapus,

**Comment by andifahruddinakas** [comment]
> bukanny kl data lengkap memang tdk boleh d hapus,

ya, kalau data sudah dianggap lengkap tidak boleh hapus

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2621
