### ISSUE TITLE
Bug/error: Urutan Nama Perangkat Desa selain Kades dan Sekdes berubah

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#6886]
### Jelaskan error yg dialami

1. Pergi ke halaman 'Info Desa'
2. Klik tombol 'Pemerintahan Desa'
3. Pilih Ubah pada salah satu data perangkat desa selain Kades dan Sekdes
4. Maka Urutannya akan berubah ke paling bawah

### Cara untuk mereplikasi errornya

Ini Terjadi di Rilis Umum dan Premium

### Hasil yg diharapkan

Ketika Melakukan Perubahan maka urutannya tetap seperti biasa

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Rilis Umum 23.07.0.0 dan Rilis Premium 2307.0.1

### Tema Yang Digunakan

Denatra

**Comment by andifahruddinakas** [comment]
SOLUSI : 
- [ ] 1. jika update, jangan mengubah data urutan yang ada, hanya lakukan ketika menambah data baru saja.
- [ ] 2. untuk kondisi 1 hanya berlaku bagi pamong yang jabatannya bukan kades atau sekdes.

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2614
