### ISSUE TITLE
Bug/error: Tabel Penduduk Kurang Lengkap saat tampil "Data Tidak Tersedia"

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#6889]
### Jelaskan error yg dialami

<img width="960" alt="image" src="https://github.com/OpenSID/OpenSID/assets/46939846/26fc0b93-3594-44e6-a0d2-cecd4c94c0cb">

### Cara untuk mereplikasi errornya

buka menu penduduk yang masih kosong (install baru) atau dengan pencarian acak sehingga tidak menampilkan data.

perhatikan tabelnya pada kolom TGL TERDAFTAR. 

### Hasil yg diharapkan

normal

### Tangkapan layar dan log error

di atas

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Berputar

**Comment by ariandii** [comment]
juga terjadi di menu Rumah Tangga.

<img width="960" alt="image" src="https://github.com/OpenSID/OpenSID/assets/46939846/89e54774-b585-4b03-9032-b5646b135362">

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2618
