### ISSUE TITLE
Bug/error: Tabel Keluarga tidak tampil "Data Tidak Tersedia"

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#6890]
### Jelaskan error yg dialami

<img width="752" alt="image" src="https://github.com/OpenSID/OpenSID/assets/46939846/f4deb7ed-1da6-416c-8ce9-871ed44a5977">

### Cara untuk mereplikasi errornya

berbeda dengan tabel penduduk di issue https://github.com/OpenSID/OpenSID/issues/6889

buka menu keluarga yang masih kosong (install baru) atau dengan pencarian acak sehingga tidak menampilkan data.

### Hasil yg diharapkan

tabel menjadi kosong tanpa ada tulisan "Data Tidak Tersedia" seperti halnya lakukan hal sama di menu penduduk.

### Tangkapan layar dan log error

di atas

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Berputar

**Comment by ariandii** [comment]
terjadi juga di menu buku administrasi

<img width="764" alt="image" src="https://github.com/OpenSID/OpenSID/assets/46939846/0de10659-e626-4ec3-b167-d9c56660355c">

**Comment by ariandii** [comment]
di data bantuan masih menggunakan bahasa inggris

<img width="759" alt="image" src="https://github.com/OpenSID/OpenSID/assets/46939846/98b4447c-6251-40bc-b6e7-6b6e0dc8f939">

**Comment by ariandii** [comment]
juga terjadi di menu dinamis/kategori

<img width="765" alt="image" src="https://github.com/OpenSID/OpenSID/assets/46939846/bbb8bf2f-7d39-4ddb-8cc0-ed924f35525b">

**Comment by ariandii** [comment]
termasuk menu
1. komentar
2. galeri
3. teks berjalan
4. layanan mandiri -> kotak pesan dan keluar
5. dan menu menu lainnya

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2619
