### ISSUE TITLE
Sesuaikan pengaturan orang tua untuk data dinamis

### ISSUE THREAD

**Issue by yogiperdana** [OpenSID/OpenSID#6891]

**Comment by vickyrolanda** [comment]
mas @yogiperdana issue ini kan yang belum di perlukan saat ini sifatnya masih (optionalkan)

**Comment by yogiperdana** [comment]
Ini perlu mas untuk surat nikah @vickyrolanda

**Comment by yogiperdana** [comment]
Saat ini data orang tua baru ditetapkan di data penduduk utama. Buat agar bisa diterapkan di data saksi atau data dinamis

**Comment by yogiperdana** [comment]
Pengaturan yang dimaksud adalah data di tab kode isian bagian form isian

**Comment by andifahruddinakas** [comment]
untuk ini belum diperlukan, data lengkap seperti data pasangan dan data orang tua diperlukan hanya pada data utama saja.
