### ISSUE TITLE
Bug/error: Bisa mengakses folder /desa

### ISSUE THREAD

**Issue by habibie11** [OpenSID/OpenSID#6892]
### Jelaskan error yg dialami

Setelah install versi 2307.02 folder desa bisa diakses secara publik

![image](https://github.com/OpenSID/OpenSID/assets/56639378/fd3b03d6-6deb-4e09-8c58-6e16530b1c28)

### Cara untuk mereplikasi errornya

1. Install versi 2307.02
2. pergi ke /desa melalui url misalnya premium.test/desa

### Hasil yg diharapkan

![image](https://github.com/OpenSID/OpenSID/assets/56639378/26551cf3-80d9-4dde-99b9-9a119dfe6b91)

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/56639378/d031025b-5726-4d31-998a-434d779ad420)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2307.02

**Comment by andifahruddinakas** [comment]
Silahkan update .htaccess sesuai perubahan di rilis https://github.com/OpenSID/rilis-premium/blob/v2306.0.0/htaccess.txt

di local terutama widows tidak bisa jalanakan .htaccess, bisa lakukan test di webserver linux atau server demo yang ada
