### ISSUE TITLE
Permintaan fitur: Tambahkan aksi up down pada pengaturan surat

### ISSUE THREAD

**Issue by mah-mudi** [OpenSID/OpenSID#6893]
### Apa kekurangan yg ingin diatasi?

 Belum adanya aksi up down pada pengaturan surat, yang mengakibatkan pengaturan surat lebih lama karena untuk mengutamakan surat yg sering digunakan.

### Jelaskan solusi yg diinginkan

Sediakan aksi up down pada pengaturan surat untuk mempermudah dan mempercepat pengaturan surat pada pemilihan surat yang sering digunakan.

<img width="565" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57661283/c06053c6-2ca8-4e62-a3cc-b13638a0b67d">

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

23.08

### Informasi tambahan

-

**Comment by pandigresik** [comment]
tandai sebagai surat favorit saja, otomatis surat tersebut akan berada pada urutan atas

**Comment by mah-mudi** [comment]
> tandai sebagai surat favorit saja, otomatis surat tersebut akan berada pada urutan atas

iya pak, perihal itu sudah.
tapi ketika setting suratnya itu, yang biasanya butuh waktu lama, ke halaman yg ke 2,3,4. 
karena suratnya itu urutan ke 70, 50 jd memperpanjang settingnya.
banyak klik klik hanya untuk bolak balik cari suratnya.

jd jika ada up down , di pengaturan surat, mempercepat pekerjaan

**Comment by eddieridwan** [comment]
@mah-mudi , seperti dikatakan @pandigresik , gunakan Favorit untuk mengingat surat yg sering digunakan.

Untuk mencari surat yg diinginkan, yg dapat diperbaiki adalah cara **pencarian**. Saat ini fitur pencarian surat digunakan untuk langsung menemukan surat yg akan dicetak. **Cara yg lebih fleksibel adalah menggunakan fitur cari untuk filter daftar surat. Seperti yg tersedia di tabel penduduk, keluarga dll.** 

Yaitu, sediakan fitur untuk cari dan filter daftar surat. Kemudian setelah difilter, bisa pilih surat yg sering digunakan sebagai Favorit.  Filter lain yg dapat disediakan misalnya menurut jenis surat, apakah ada lampiran, dsbnya. 

Tapi harap jangan terapkan tombol naik/turun pada daftar surat. Itu bukan solusi yg baik. Silakan ubah issue ini untuk menyediakan filter pada daftar surat.

**Comment by mah-mudi** [comment]
ya barangkali bisa bisa diterapkan, kayak up down artikel. :-)
karena halaman defalut setting surat hanya nampilin 25 surat.

**Comment by eddieridwan** [comment]
@vickyrolanda issue ini mohon disesuaikan dengan komentar di https://github.com/OpenSID/OpenSID/issues/6893#issuecomment-1636925525.

**Comment by vickyrolanda** [comment]
Siap pak🙏
