### ISSUE TITLE
Bug/error: Klik Bersihkan pada Arsip Layanan Surat berakibat bug pada web pantau OpenSD

### ISSUE THREAD

**Issue by mah-mudi** [OpenSID/OpenSID#6894]
### Jelaskan error yg dialami

Klik Bersihkan pada Arsip Layanan Surat berakibat bug pada web pantau OpenSD.

### Cara untuk mereplikasi errornya

1. Layanan Surat
2. Arsip Surat
3. Bersihkan
4. Cek Pantau OpenSID https://pantau.opensid.my.id/laporan/desa?status=1&kode_kabupaten=35.25&kode_provinsi=35
5. di web pantau, yang awalnya modul TTE aktif menjadi tidak aktif, yang awalnya versi online terbaru menjadi versi lama
6. akan normal lg, jika membuat surat TTE lg, tanpa klik bersihkan

### Hasil yg diharapkan

Tidak terjadi bug lagi

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/57661283/95a28dc0-545f-4aa9-aaee-98129543497d)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

23.07.0.2

### Tema Yang Digunakan

silir

### Informasi tambahan

desaleran.gresikkab.go.id

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2636
