### ISSUE TITLE
Bug/error: ada muncul tombol hapus kategori padahal tidak ada kategori

### ISSUE THREAD

**Issue by habibie11** [OpenSID/OpenSID#6899]
### Jelaskan error yg dialami

ada muncul tombol hapus kategori padahal tidak ada kategori

### Cara untuk mereplikasi errornya

1. pilih menu admin web/artikel
2. tambah/edit artikel
3. ketika simpan muncul tombol hapus kategori tersebut

dan tertera 2 artikel di tabel.
padahal semua artikel dinamis ada 4 di berputar. dan artikel statis ada 20.

![image](https://github.com/OpenSID/OpenSID/assets/56639378/5e44c565-bfe7-4c38-9cb3-736457e1a63f)

### Hasil yg diharapkan

normal

### Tangkapan layar dan log error

diatas

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

berputar

### Informasi tambahan

info tambahan:
lakukan edit artikel dinamis yg ada lalu simpan. redirect nya ke artikel statis (tombol tambah di gambar tertulis Tambah Artikel Statis Baru)

**Comment by scqolbu24** [comment]
Replikasi di **local** menggunakan versi 23.07.02 hasil seperti berikut

https://github.com/OpenSID/OpenSID/assets/68048807/84c53cbe-611f-4fde-9a4f-5936d3287b77

Replikasi di **berputar** menggunakan versi 23.07.03 hasil seperti berikut

https://github.com/OpenSID/OpenSID/assets/68048807/db61c73c-d759-422e-994a-276f4dac4caa

**Comment by andifahruddinakas** [comment]
mas @habibie11, @scqolbu24, kasus ini masalahnya pada kategori yang ada di child yg sudah tidak memiliki parrent. Sudah pernah diperbaiki, namun di versi umum masih terjadi. 

Issue ini bisa saya duplikasi di versi umum yang sekarang:
<img width="548" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/89025333-d209-4e01-a04e-c96b51f3d720">

Perbaikan dilakukan melalui issue https://github.com/OpenSID/OpenSID/issues/6661
