### ISSUE TITLE
Sesuaikan data lampiran 2.01

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#6902]

**Comment by vickyrolanda** [comment]
mas @yogiperdana bisa bantu lengkapi issue ini data apa yang pelu disesuiakan.

**Comment by yogiperdana** [comment]
Detailnya bisa dicek pas cetak surat yang menggunakan lampiran ini. Cek jika ada input yang tidak sesuai. Khusunya kode isian select manual. Referensinya bisa lihat di lampiran 1.15

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/2628
