### ISSUE TITLE
Migrasi perlu persetujuan pengguna

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#6903]
Saat ini migrasi dijalankan otomatis setiap kali adanya rilis terbaru,kadang terdapat pengguna lupa melakukan backup database 
 / folder desa namun sudah memperbarui scriptnya. Yang menyebabkan database berubah dan tidak ada backup.

Harapanya:
- Pengguna selalu dilibatkan jika terdapat migrasi yg perlu dijalanakan agar tidak merusak database

Solusi:
- [ ] ubah migrasi otomatis menjadi manual dengan persetujuan pengguna.
- [ ] setiap kali ingin menjalankan migrasi, tampilkan notifikan konfirmasi backup database. jika konfirmasi belum, jangan lakukan migrasi.
- [ ] jika tederteksi migrasi dari rilis baru, ubah status sementara menjadi mode maitenance.
- [ ] point di atas ditambahkan dan hanya bisa dijalanakan diluar admin (extend ke MY_Controller), bisa diletakkan di controller periksa namun dengan mengganti urlnya. (misalnya: domain/migrasi-database)

**Comment by agungsugiarto** [comment]
mas @andifahruddinakas nanti bisa diskusi terkait issue ini?
