### ISSUE TITLE
Sebutan desa agar konsisten pada tampilan Anjungan

### ISSUE THREAD

**Issue by syahransaputra** [OpenSID/OpenSID#6905]
### Jelaskan error yg dialami

Pada Judul Berita

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v2307.0.2

**Comment by andifahruddinakas** [comment]
Duplicate issue https://github.com/OpenSID/OpenSID/issues/6834

**Comment by andifahruddinakas** [comment]
mas @syahransaputra, terima kasih. Sudah disesuaikan melalui commit https://github.com/OpenSID/premium/commit/5e27e11921cb2ee2fa8f870cc355af3db57e52bf
