### ISSUE TITLE
Bug/error: error rate limit menyebabkan tidak bisa akses menu homesid

### ISSUE THREAD

**Issue by habibie11** [OpenSID/OpenSID#6910]
### Jelaskan error yg dialami

Setelah update ke versi terbaru tidak bisa membuka menu homesid di admin sedangkan menu yang lain bisa dibuka, di log muncul error berikut :

![image](https://github.com/OpenSID/OpenSID/assets/56639378/c6530aa6-7a75-4c0b-a300-728849122743)

solusi sementara :
1. Jika respon limit, matikan notifikasi
2. Sediakan pengaturan notifikasi dalam beentuk harian, misalkan 7 hari, 14 hari, 30 hari yg dpt di input oleh pengguna. Jika isi 0 maka mematikan pemberitahuan jika ada rilis baru

### Cara untuk mereplikasi errornya

1. upgrade ke versi baru
2. pergi kehalaman homesid
3. tidak bisa diakses

### Hasil yg diharapkan

normal

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/56639378/a6f90589-eb67-41b9-8978-2115d9bc4a8e)

![image](https://github.com/OpenSID/OpenSID/assets/56639378/c6530aa6-7a75-4c0b-a300-728849122743)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2307.03

### Informasi tambahan

solusi sementara :
1. Jika respon limit, matikan notifikasi
2. Sediakan pengaturan notifikasi dalam beentuk harian, misalkan 7 hari, 14 hari, 30 hari yg dpt di input oleh pengguna. Jika isi 0 maka mematikan pemberitahuan jika ada rilis baru

**Comment by apidong** [comment]
> ### Jelaskan error yg dialami
> Setelah update ke versi terbaru tidak bisa membuka menu homesid di admin sedangkan menu yang lain bisa dibuka, di log muncul error berikut :
> 
> ![image](https://user-images.githubusercontent.com/56639378/255179462-c6530aa6-7a75-4c0b-a300-728849122743.png)
> 
> solusi sementara :
> 
> 1. Jika respon limit, matikan notifikasi
> 2. Sediakan pengaturan notifikasi dalam beentuk harian, misalkan 7 hari, 14 hari, 30 hari yg dpt di input oleh pengguna. Jika isi 0 maka mematikan pemberitahuan jika ada rilis baru
> 
> ### Cara untuk mereplikasi errornya
> 1. upgrade ke versi baru
> 2. pergi kehalaman homesid
> 3. tidak bisa diakses
> 
> ### Hasil yg diharapkan
> normal
> 
> ### Tangkapan layar dan log error
> ![image](https://user-images.githubusercontent.com/56639378/255179769-a6f90589-eb67-41b9-8978-2115d9bc4a8e.png)
> 
> ![image](https://user-images.githubusercontent.com/56639378/255179462-c6530aa6-7a75-4c0b-a300-728849122743.png)
> 
> ### Rilis Versi OpenSID
> Rilis Premium
> 
> ### Versi OpenSID
> 2307.03
> 
> ### Tema Yang Digunakan
> _No response_
> 
> ### Informasi tambahan
> solusi sementara :
> 
> 1. Jika respon limit, matikan notifikasi
> 2. Sediakan pengaturan notifikasi dalam beentuk harian, misalkan 7 hari, 14 hari, 30 hari yg dpt di input oleh pengguna. Jika isi 0 maka mematikan pemberitahuan jika ada rilis baru

bisa juga konfigurasi nya diganti menggunakan token key https://github.com/settings/tokens dan token key ini diinput melalui modul pengaturan. 
tempat generate key https://github.com/settings/tokens

dokumentasi https://docs.github.com/en/rest/quickstart?apiVersion=2022-11-28

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2664
