### ISSUE TITLE
Bug/error: tampilan modul keluarga berantakan

### ISSUE THREAD

**Issue by habibie11** [OpenSID/OpenSID#6911]
### Jelaskan error yg dialami

data KK sementara tidak muncul paling atas di menu Keluarga, seharusnya secara default KK sementara dipaling atas dengan KK < 16 digit. dan ketika di short kolom no KK maka nomor KK berada diatas dan icon-icon sedikit berantakan dan icon hapus tidak ada.

![image](https://github.com/OpenSID/OpenSID/assets/56639378/307a8e24-2c71-4ce7-be19-573c39e33bd4)

### Cara untuk mereplikasi errornya

1. pergi ke menu keluarga dengan mode mobile/responsive
2. data kk yang paling atas bukan kk sementara
3. lalu sort kk, maka icon-icon akan berubah menjadi sedikit berantakan dan kk sementara berada diatas

### Hasil yg diharapkan

normal

### Tangkapan layar dan log error

diatas

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2307.03

**Comment by andifahruddinakas** [comment]
untuk tampilan di atas, beberapa layout HP sy gunakan tidak menemukan.
<img width="683" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/76660fc4-7b90-4998-86c8-827373d3202b">
<img width="683" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/431011f9-c99d-4135-a9b3-54022a1e0079">
<img width="683" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/d746a635-e827-4af9-b5a0-9e68b249fe0b">


Namun hal lain yang berantakan seperti : 
![image](https://github.com/OpenSID/OpenSID/assets/57283157/0177a2ed-8c66-4e48-94dc-a311504112ca)

Agar solusinya seragam, bisa buat seperti ini : 
- [ ] buatkan helper untuk membuat tombol tambah, cetak, unduh, dll dengan di sesuaikan bisa digunakan dibeberapa tampilan perangkat. Agar ke depan tampilannya seragam.
- [ ] untuk order keluarga, buat jadi default adalah nik dan tgl buat
