### ISSUE TITLE
Bug/error: Poto Penduduk dan Keluarga Tidak Muncul Di Peta

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#6912]
### Jelaskan error yg dialami

poto penduduk dan keluarga tidak muncul di menu Peta
<img width="764" alt="Screenshot 2023-07-22 213009" src="https://github.com/OpenSID/OpenSID/assets/25834335/23056c62-8758-4ddd-b3e3-d65bd5ea64fa">

### Cara untuk mereplikasi errornya

Pergi ke halaman 'menu kependudukan/penduduk'
Klik tombol 'ubah'
upload poto penduduk dan berhasil di upload
<img width="702" alt="Screenshot 2023-07-22 213304" src="https://github.com/OpenSID/OpenSID/assets/25834335/b9ebfdfb-8c0f-471d-a991-27f3eb04c597">
<img width="705" alt="Screenshot 2023-07-22 213349" src="https://github.com/OpenSID/OpenSID/assets/25834335/4715b462-4d48-4305-b560-309208b715a9">

pergi ke menu Pemetaan/peta
pilih penduduk atau keluarga maka poto tidak muncul
<img width="764" alt="Screenshot 2023-07-22 213009" src="https://github.com/OpenSID/OpenSID/assets/25834335/db94a6af-af3a-4d79-b108-aa0d7fe15909">

### Hasil yg diharapkan

Poto Tampil Normal seperti rilis sebelumnya

### Tangkapan layar dan log error

<img width="764" alt="Screenshot 2023-07-22 213009" src="https://github.com/OpenSID/OpenSID/assets/25834335/1e54a423-4415-4ec5-b664-e0e497fab4b3">

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Rilis Umum 23.07.0.0 dan Rilis Versi 2307.0.3-premium

### Tema Yang Digunakan

Natra

**Comment by MUHAMMADRANGSEL** [comment]
Bug ini sudah lama terjadi

**Comment by andifahruddinakas** [comment]
> Bug ini sudah lama terjadi

ok

**Comment by andifahruddinakas** [comment]
SOLUSI : 
- [ ] jika tidak ada foto kecil, tampilkan foto besarnya.
- [ ] perbaiki unggah penduduk, selalu buat foto ukuran kecil dan aslinya.

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2673
