### ISSUE TITLE
Bug: Database Error 500 ketika input anggota keluraga baru

### ISSUE THREAD

**Issue by viikidna** [OpenSID/OpenSID#693]
Ketika akan menambahkan anggota keluarga baru, terjadi error seperti pada screnshoot.
database sudah saya migrasi pada menu database, dan tetap eror.

akan tetapi anggota keluarga baru yang di inputkan tersimpan dan masuk dalam KK tersebut dengan baik.
![screenshot-2017-11-1 database error](https://user-images.githubusercontent.com/33271657/32256447-b05c3264-bee1-11e7-88be-c3d33eaa1140.png)

**Comment by eddieridwan** [comment]
@viikidna seharusnya error ini tidak muncul dan kami tidak bisa me-replikasi. Anda menggunakan OpenSID versi berapa?

Namun demikian, cara penyimpanan log_penduduk telah diubah, supaya duplikasi tidak terjadi. Sudah dicommit ke master. Silakan coba dengan versi pra-rilis. Atau uji-coba di http://sid.bangundesa.info.

**Comment by viikidna** [comment]
mohon maaf sebelumnya saya mencobanya di versi 2.5.2
saya coba di versi 2.6 tetap error

tetapi ketika saya coba di http://sid.bangundesa.info. tidak terjadi eror

mungkin itu laporan sementara.thanks
