### ISSUE TITLE
Bug/error: Error data form isian ketika tambah surat dengan penduduk dinamis atau saksi

### ISSUE THREAD

**Issue by yogiperdana** [OpenSID/OpenSID#6931]
### Jelaskan error yg dialami

Error data form isian ketika tambah surat dengan penduduk dinamis atau saksi

### Cara untuk mereplikasi errornya

Buat surat baru. Lakukan langkah seperti tangkapan layar

### Hasil yg diharapkan

Berjalan normal

### Tangkapan layar dan log error

Sebelum simpan:

![image](https://github.com/OpenSID/OpenSID/assets/14155050/946682f8-8257-43c0-a4c3-1d72e49b8b9a)

![image](https://github.com/OpenSID/OpenSID/assets/14155050/71e66a07-e498-4714-8ede-78b1a8716671)

Setelah simpan:

![image](https://github.com/OpenSID/OpenSID/assets/14155050/11ae8b57-d6c1-44e9-beed-e49b86d20bcb)

![image](https://github.com/OpenSID/OpenSID/assets/14155050/80635e81-faf1-423f-ab75-21edec8ec380)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v2307-premium

**Comment by yogiperdana** [comment]
Data lain seperti jenis peristiwa tidak bisa diganti. Lalu untuk data shdk di data dinamis kadang data utama juga ikut berubah

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/2700
