### ISSUE TITLE
Bug/error: data form isian di data dinamis tidak berfungsi

### ISSUE THREAD

**Issue by yogiperdana** [OpenSID/OpenSID#6932]
### Jelaskan error yg dialami

data form isian di data dinamis tidak berfungsi

### Cara untuk mereplikasi errornya

Buat surat baru ganti data form isian di data dinamis

### Hasil yg diharapkan

Berjalan normal

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/14155050/e8f1ca44-3070-4964-b993-421430b6f2c9)

![image](https://github.com/OpenSID/OpenSID/assets/14155050/ac46712b-927f-43dc-aeb2-6db017b74506)

Data jenis kelamin, shdk, jenis peristiwa tidak berfungsi

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v2307-premium

**Comment by pandigresik** [comment]
![image](https://github.com/OpenSID/OpenSID/assets/1853475/8a684679-a473-45bf-be6d-fe3b535cc014)

data di pengaturan, SHDK lainnya

![image](https://github.com/OpenSID/OpenSID/assets/1853475/77f5ae33-9feb-408c-b067-8770dc97e753)

![image](https://github.com/OpenSID/OpenSID/assets/1853475/127175c3-4c13-4588-9624-2563792453e9)

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/2699
