### ISSUE TITLE
Sesuaikan posisi data peristiwa, orang tua dan pasangan

### ISSUE THREAD

**Issue by yogiperdana** [OpenSID/OpenSID#6934]
Saat ini form kode isian muncul terlebih dahulu dari data peristiwa orang tua ataupun pasangan. Hal ini tidak sesuai dengan form rtf. Untuk itu data disusun menjadi:
- Data peristiwa
- Data pasangan
- Data orang tua
- Kode isian

**Comment by scqolbu24** [comment]
sudah dikerjakan melalui PR https://github.com/OpenSID/premium/pull/2672
