### ISSUE TITLE
Sediakan Informasi Keterangan Surat System atau Surat Desa ketika Cetak Surat

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#6935]
### Jelaskan error yg dialami

<img width="535" alt="image" src="https://github.com/OpenSID/OpenSID/assets/46939846/465abf5f-abff-40d7-907b-9566327e169a">

### Cara untuk mereplikasi errornya

buat surat baru tinyMCE dengan nama surat yang sama dengan surat sistem.
bahkan bisa buat lah lebih dari 1.

buka menu Layanan Surat -> Cetak Surat
saat cari surat yg diinginkan, seperti gambar di atas. ada banyak jenis yg membuat bingung.

### Hasil yg diharapkan

tersedia keterangan Surat Desa atau Surat Sistem di sebelah tulisannya, atau cara lain.

### Tangkapan layar dan log error

di atas

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Seluruhnya

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2877
