### ISSUE TITLE
Penyesuain format tanggal dan untuk nama dibuat huruf besar dan bold agar sama dengan format lampiran yang lainnya

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/OpenSID#6936]
contoh untuk judul tidak center dan nama menggunakan huruf kecil
![image](https://github.com/OpenSID/OpenSID/assets/68048807/2cfb1352-f3bc-4b32-a1e6-2051bd8b0450)

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/2675
