### ISSUE TITLE
Bug/error: tanggal surat dan tanggal lahir pada pada Surat Keterangan Untuk Nikah (N-1 s/d N-7) Rtf semua berubah menjadi tanggal 01

### ISSUE THREAD

**Issue by Restony33** [OpenSID/OpenSID#6937]
### Jelaskan error yg dialami

hasil pada Surat Keterangan Untuk Nikah (N-1 s/d N-7) RTF semua tanggal lahir yang terdapat dalam formulir berubah menjadi tanggal 01 dan tanggal cetak semua  formulir menjadi 01 Juli 2023
![2023-07-26_20h47_29](https://github.com/OpenSID/OpenSID/assets/104592011/2742cc58-1873-4dc8-ad5b-1a3592915d3c)

### Cara untuk mereplikasi errornya

1. Login Admin
2. Layanan Surat >> Cetak Surat
3. Pilih Surat Keterangan Untuk Nikah (N-1 s/d N-7) RTF
4. Isi formulir kemudian Unduh RTF
![2023-07-26_20h49_58](https://github.com/OpenSID/OpenSID/assets/104592011/3ff4673c-e98c-4776-968a-12e6cd74004b)

### Hasil yg diharapkan

Berjalan Normal

### Tangkapan layar dan log error

![2023-07-26_20h47_29](https://github.com/OpenSID/OpenSID/assets/104592011/9e637416-8a0b-4ec0-876c-2639e5e95172)
![2023-07-26_20h53_14](https://github.com/OpenSID/OpenSID/assets/104592011/4938dfd8-4a40-40a0-974a-ac393603b45a)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Versi 2307.0.4-premium

### Tema Yang Digunakan

natra

### Informasi tambahan

https://devpremium.opendesa.id/

**Comment by andifahruddinakas** [comment]
solusi sementara yang bisa kami berikan bisa di cek https://forum.opendesa.id/d/303-pada-versi-230704-tanggal-pada-cetak-surat-tidak-sesuai

issue ini akan diperbaiki sebelum rilis tgl 1, terima kasih.

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui commit https://github.com/OpenSID/premium/commit/a9aaafb027288be9e86e7226731a41a3ed5f80ab
