### ISSUE TITLE
Penambahan isian manual link pada Tautan Teks Berjalan

### ISSUE THREAD

**Issue by mah-mudi** [OpenSID/OpenSID#6938]
### Jelaskan error yg dialami

Tautan ke Artikel pada Teks Berjalan, tidak berfungsi sebagimana mestinya

### Cara untuk mereplikasi errornya

1. admin web
2. teks berjalan
3. tautan ke artikel
4. hanya ada pilihan satu artikel

### Hasil yg diharapkan

tautan pada artikel diganti menjadi isian manual link, sehingga dapat difungsinya sebagaimana mestinya.
seperti ini
![photo1690392443](https://github.com/OpenSID/OpenSID/assets/57661283/e76223dd-c510-4cfb-98b0-916c3dd8a45c)

### Tangkapan layar dan log error

<img width="954" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57661283/eecfa39e-f378-465b-b70a-1931b6eae689">

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

23.07.0.4

### Tema Yang Digunakan

silir

### Informasi tambahan

desaleran.gresikkab.go.id

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/OpenSID/pull/7667
