### ISSUE TITLE
Bug/error: Urutan Daftar Anggota Keluarga tidak sesuai

### ISSUE THREAD

**Issue by Akmal197** [OpenSID/OpenSID#6940]
### Jelaskan error yg dialami

Daftar Urutan Angggota Keluarga tidak berurutan mengikuti tahun kelahiran seperti biasanya. tetapi hanya di rincian anggota keluarga, untuk di Salinan Kartu Keluarga normal.
![image](https://github.com/OpenSID/OpenSID/assets/76812689/74169ca2-3b8d-4e52-870f-9cb8162f043f)

### Cara untuk mereplikasi errornya

1. Menu Kependudukan
2. Keluarga
3. Rincian Anggota Keluarga/Kembali ke Daftar Anggota Keluarga

### Hasil yg diharapkan

Normal kembali seperti sebelumnya

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/76812689/1debcc9e-ac2d-46d2-ad15-487620f33279)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2307.0.4

### Tema Yang Digunakan

Natra

**Comment by ariandii** [comment]
info tambahan:
terlihat pada 2 anak tersebut.
seharusnya Faridah urutan ke-3 karena lahir tahun 2000
selanjutnya Erlangga Dwiko Saputro urutan ke-4 karena lahir tahun 2014

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui commit https://github.com/OpenSID/premium/commit/0fdad7d833b8ee65d4b13bdd1f26dd48c2fc9849
