### ISSUE TITLE
Bug/error: Kode isian normal tdk sesuai

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#6946]
### Jelaskan error yg dialami

Pada surat tinymce terdapat kode isian dengan beberapa pilihan, salah satunya adalah normal yakni sesuai dengan apa yg di input.

### Cara untuk mereplikasi errornya

1. siapkan data penduduk (mis. memliki alamat yang menggunakan kapital)
2. buat surat tinymce
3. tambahkan kode isian tsb pada tempalte yg bertipe normal (mis. alamat)
4. lakukan cetak pada surat tsb
5. hasilnya tidak sesuai yg di input

### Hasil yg diharapkan

Isian normail tampil sesuai yang diinput pengguna.

### Tangkapan layar dan log error

<img width="326" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/9dd92433-fff5-437f-baf4-bf0fe298d06d">

<img width="293" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/977084e7-ab4f-4fe3-9a55-8bf12ab9b309">

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v2307.0.0

### Tema Yang Digunakan

.

### Informasi tambahan

.

**Comment by andifahruddinakas** [comment]
pak @ariandii, setelah sy cek ulang saat ini sudah sesuai.

view : 
<img width="293" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/46a37ca0-ddb8-4b3f-b060-ce2ca8fc1eff">

<img width="275" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/09c19f77-ebd6-41ae-a6c8-371fde09e932">

coding : (dikembalikan tanpa adanya perubahan)
<img width="217" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/87b0f53d-f3fe-4c45-a9d6-065af989dd90">

Mungkin bisa bantu duplikasi.

**Comment by andifahruddinakas** [comment]
untuk kasus pendidikan jg sudah sesuai : 
<img width="136" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/7ec3ffdd-c484-4402-ace9-06b325aae69b">

Jika terdapat pada daftar berikut, akan di ubah huruf besar. Sama seperti versi yang lama.
<img width="82" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/784e6d78-5ac3-46aa-9cd1-da9c73b2a2e0">

**Comment by ariandii** [comment]
bisa DC ya pak
