### ISSUE TITLE
Bug/error: Tidak adanya tombol verivikasi pendaftaran warga pada layanan mandiri pd akun admin

### ISSUE THREAD

**Issue by mah-mudi** [OpenSID/OpenSID#6951]
### Jelaskan error yg dialami

Tidak adanya tombol verivikasi pendaftaran warga pada layanan mandiri pd akun admin

### Cara untuk mereplikasi errornya

1. layanan mandiri
2. pendaftar layanan mandiri
3. verivikasi pendaftaran warga
4. cek 

### Hasil yg diharapkan

adanya tombol verivikasi pendaftaran warga pada layanan mandiri pd akun admin

### Tangkapan layar dan log error

<img width="716" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57661283/49f8a684-2937-4d57-928c-0b199455d49e">

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

23.07.0.4

### Tema Yang Digunakan

natra

### Informasi tambahan

https://demosid.opendesa.id/

**Comment by ariandii** [comment]
normal saja jika tes di versi premium devpremium.opendesa.id

pengguna umum silakan tunggu giliran masuk rilis setelah 6 bulan tersedia di premium.
