### ISSUE TITLE
Permintaan fitur: sediakan tombol hapus pada lampiran artikel 

### ISSUE THREAD

**Issue by mah-mudi** [OpenSID/OpenSID#6952]
### Apa kekurangan yg ingin diatasi?

belum tersediakan tombol hapus pada lampiran artikel

### Jelaskan solusi yg diinginkan

sediakan tombol hapus pada lampiran artikel pada issues #5899
https://github.com/OpenSID/OpenSID/issues/5899

sudah pernah dibuatkan dan diselesaikan di
https://github.com/OpenSID/premium/pull/1967

namun fungsi hapus pada lampiran artikel belum ada

### Apakah ada alternatif lain

<img width="927" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57661283/5f27b2ad-fc64-4f49-b06b-5714a35fb388">

### Untuk versi OpenSID mana

23.08

### Informasi tambahan

https://berputar.opendesa.id/

**Comment by ariandii** [comment]
ini sudah ada di versi premium sejak beberapa bulan lalu.

penffuna umum silakan menunggu giliran rilis nya setelah 6 bulan.

ditunggu saja.

**Comment by mah-mudi** [comment]
@ariandii diberputar juga tidak ada tombol hapus lampiran artikel

<img width="947" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57661283/6120db58-bb8a-49e3-8998-7298740cf223">

**Comment by ariandii** [comment]
itu tombol merah di lampiran.
