### ISSUE TITLE
Bug/error: inputan required di form isian dinamis TinyMCE tidak berfungsi.

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#6955]
### Jelaskan error yg dialami

silahkan pilih salah satu surat dengan form isian yang required. lalu cetak tanpa mengisi form tersebut.
maka surat tetap tercetak.

### Cara untuk mereplikasi errornya

1. Pergi ke halaman pengaturan surat
2. pilih salah satu surat TinyMCE dengan kode isian required
3. lalu pergi ke halaman cetak surat
4. lalu pilih surat yang di edit ada diperiksa tadi
5. maka kosongkan form isian yang diminta di surat tersebut

### Hasil yg diharapkan

Seharusnya surat tidak tercetak atau tidak bisa masuk ke tahap berikutnya karena isian harus diisi

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v2307.0.0

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2739
