### ISSUE TITLE
Tulisan pada sub menu baik menu statis dan dinamis menggunakan huruf besar awal saja

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#696]
Seperti tertera pada gambar dibawah ini sebaiknya tulisan sub menu nya memakai huruf kapitas diawal saja contoh seperti si menu statis : **DATA WILAYAH ADMINISTRASI** di ubah menjadi **Data Wilayah Administrasi** 
![screenshot 2017-11-04 12 08 38](https://user-images.githubusercontent.com/25834335/32402212-04b8fdcc-c15a-11e7-8f38-10ad72c0ec4c.png)

Menu Dinamis : **BERITA DAERAH** diubah menjadi **Berita Daerah**
![screenshot 2017-11-04 12 08 47](https://user-images.githubusercontent.com/25834335/32402215-1a30844a-c15a-11e7-8b12-a2f187381417.png)

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.

**Comment by DamesDamai** [comment]
kalo boleh usul
kalo bisa untuk semua tema ada menu dropdown dinamisnya kayak tema default
