### ISSUE TITLE
Bug : Pengisian Blanko  Biodata Penduduk beberapa tidak mengikuti aturan Penulisan Blangko

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#6962]
### Jelaskan error yg dialami

Cetak surat biodata penduduk, lihat hasil, cek pada kolom jenis kelamin, golongan darah, agama, status perkawinan, status hub dalam keluarga, pendidikan dan pekerjaan, tertulis lengkap sedangkan aturan penulisan d tulis dengan angka

### Cara untuk mereplikasi errornya

pergi ke surat > cetak surat biodata penduduk > cek hasil lampiran surat

### Hasil yg diharapkan

sesuaikan dengan tata cara pengisian formulir yang ada

### Tangkapan layar dan log error

![asdasda](https://github.com/OpenSID/OpenSID/assets/35319600/b13e0c0a-209f-4226-bf1d-b7689c2a7fd7)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

berputar

### Tema Yang Digunakan

-

### Informasi tambahan

sesuaikan dengan tata cara pengisian formulir yang ada

![sadas](https://github.com/OpenSID/OpenSID/assets/35319600/452d43fb-23f3-4bb8-a4d2-dd0984d14e5e)

![asdasdasd](https://github.com/OpenSID/OpenSID/assets/35319600/e1988c4c-5075-4fe8-9b65-2fe6ddbaacb5)

sumber : 
[Formulir-F1-01.pdf](https://github.com/OpenSID/OpenSID/files/12232065/Formulir-F1-01.pdf)

**Comment by rizkiagungid** [comment]
hallo, bisa upload database nya ? karna saya cek di github sekarang ko tidak ada database nya ya ? bisa bantu backup database nya dan upload ke github kembali? terima kasih sebelumnya

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2745
