### ISSUE TITLE
Bug/error: Lampiran Surat Kematian Tahun Tidak Sesuai

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#6968]
### Jelaskan error yg dialami

Saat cetak surat keterangan kematian (RTF) dengan lampiran F.2-01, data tahun pada tgl lahir ayah tidak sesuai dan tgl kematian thn nya hanya 2 digit

### Cara untuk mereplikasi errornya

1. Masuk layanan surat
2. Cetak surat kematian
3. Isi datanya
4. Cetak
5. Lihat hasil dari lampiran yang dihasilkan

### Hasil yg diharapkan

Tgl sesuai yang dimasukkan

### Tangkapan layar dan log error

<img width="242" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/b8df4052-447c-4539-bf9d-7f093dd7ec05">

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v2308.0.0

### Tema Yang Digunakan

bawaan

### Informasi tambahan

SOLUSI : 
- [x] tgl lahir ayah, kematian disesuaikan dengan inputan
- [x] tgl lahir kematian pada tahun di buat jadi 4 kotak

**Comment by FirlianiF** [comment]
[surat-keterangan-kematian_5201143112797117_2023-08-04_2.pdf](https://github.com/OpenSID/OpenSID/files/12262603/surat-keterangan-kematian_5201143112797117_2023-08-04_2.pdf)
mas @andifahruddinakas bug tidak dapat direplikasi karena di lampiran tidak ada menampilkan data tersebut.

**Comment by andifahruddinakas** [comment]
> [surat-keterangan-kematian_5201143112797117_2023-08-04_2.pdf](https://github.com/OpenSID/OpenSID/files/12262603/surat-keterangan-kematian_5201143112797117_2023-08-04_2.pdf) mas @andifahruddinakas bug tidak dapat direplikasi karena di lampiran tidak ada menampilkan data tersebut.

masalah di atas terjadi dilampiran surat kematian rtf, karena surat rtf belum sepenuhnya dimatika masih perlu perbaikan pada surat tsb.

untuk mba @FirlianiF coba juga sepertinya bug untuk surat kematian tinymce, akan dibuat issue terpisah.

**Comment by scqolbu24** [comment]
mas @andifahruddinakas pada lampiran F.2-01 terdapat tanggal lainnya seperti tanggal kematian atau tanggal lahir ayah dan ibu yang kemungkinan akan ada bug jika pada database tidak terisi sehingga akan menghasilkan tanggal 01-01-1970 serta ada tahun yang hanya terisi 2 kotak, apakah perlu dibuatkan issue tersendiri atau terpisah?

contoh: 
Tanggal Lahir Anak, 
Tanggal lahir mati, 
Tanggal Pemberkatan,
Tanggal Melapor, 
Tanggal Penetapan,
Tanggal Perkawinan, 
Tanggal Akta Perkawinan, 
Tanggal Putusan Pengadilan, 
Tanggal Pelaporan Perkawinan
Tanggal Surat Keterangan Panitera Pengadilan
Tanggal Melapor
Tanggal Akta Perceraian
Tanggal Pelaporan
Tanggal Akta Kelahiran, 
Tanggal Penetapan Pengadilan

**Comment by andifahruddinakas** [comment]
> mas @andifahruddinakas pada lampiran F.2-01 terdapat tanggal lainnya seperti tanggal kematian atau tanggal lahir ayah dan ibu yang kemungkinan akan ada bug jika pada database tidak terisi sehingga akan menghasilkan tanggal 01-01-1970 serta ada tahun yang hanya terisi 2 kotak, apakah perlu dibuatkan issue tersendiri atau terpisah?
> 
> contoh: 
> Tanggal Lahir Anak, 
> Tanggal lahir mati, 
> Tanggal Pemberkatan,
> Tanggal Melapor, 
> Tanggal Penetapan,
> Tanggal Perkawinan, 
> Tanggal Akta Perkawinan, 
> Tanggal Putusan Pengadilan, 
> Tanggal Pelaporan Perkawinan
> Tanggal Surat Keterangan Panitera Pengadilan
> Tanggal Melapor
> Tanggal Akta Perceraian
> Tanggal Pelaporan
> Tanggal Akta Kelahiran, 
> Tanggal Penetapan Pengadilan

Sesuai issue sj yg dilaporkan pengguna.

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2771
