### ISSUE TITLE
Bug/error: Error 500 saat membuka menu penduduk

### ISSUE THREAD

**Issue by JosseWahid** [OpenSID/OpenSID#6978]
### Jelaskan error yg dialami

Pada saat ingin menambahkan data penduduk pada Kependudukan > Penduduk tidak dapat di buka terjadi error 500

### Cara untuk mereplikasi errornya

1. Buka halaman admin pada open sid
2. Login pada halam admin
3. Buka menu kependudukan > penduduk
4. Terjadi Error 500

### Hasil yg diharapkan

Dapat memperbaiki error 500 pada saat ingin menambahkan data penduduk supaya web desa saya bisa menambahkan data penduduk

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/47247610/d0c0fd6f-9cbb-480c-add2-57fac83abd1a)
![image](https://github.com/OpenSID/OpenSID/assets/47247610/3c7daaa2-dfd4-4e1e-bba3-5678df3e637b)

### Rilis Versi OpenSID

Rilis Umum

### Versi OpenSID

Versi 2307.0.0

### Tema Yang Digunakan

Tema esensi

**Comment by andifahruddinakas** [comment]
mas @JosseWahid, kirim file log nya

**Comment by JosseWahid** [comment]
> mas @JosseWahid, kirim file log nya
[log-2023-08-05.zip](https://github.com/OpenSID/OpenSID/files/12263523/log-2023-08-05.zip)
inii pak @andifahruddinakas mohon bantuannya

**Comment by ravivasandany** [comment]
Sama, dipunya saya juga error, mohon bantuannya

**Comment by pandigresik** [comment]
pastikan tidak menggunakan mysql 8 keatas
