### ISSUE TITLE
Bug/error: kode isian data orang tua tidak tampil dengan benar

### ISSUE THREAD

**Issue by mah-mudi** [OpenSID/OpenSID#6979]
### Jelaskan error yg dialami

kode isian pada template nama, nik, TTL, agama, pekerjaan, alamat ayah Ibu pada template surat tidak menampilkan data sebeagaimana mestinya

### Cara untuk mereplikasi errornya

1. layanan surat
2. pengaturan surat
3. tambah format surat
4. template baru
5. setting template, kode isian, ketika memasukkan seperti screenshoot, tidak menampilkan data sebagaimana mestinya

### Hasil yg diharapkan

kode isian pada template nama, nik, TTL, agama, pekerjaan, alamat ayah Ibu pada template surat dapat menampilkan data sebagaimana mestinya

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/57661283/5a38e2f5-81de-4795-9806-25574869a2c0)

![image](https://github.com/OpenSID/OpenSID/assets/57661283/6bb57a54-394e-42c6-a013-27ef6e21e2f7)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

23.08-premium

### Tema Yang Digunakan

silir

### Informasi tambahan

-

**Comment by andifahruddinakas** [comment]
PENYEBAB : 
- terdapatnya variabel data tumpang tindih, dimana data sebelumnya sudah ada datanya, namun di replace lg dengan data kosong.

LETAK MASALAH
            ```
$id_ayah = Penduduk::where('nik', $penduduk->ayah_nik)->first()->id;
            $id_ibu  = Penduduk::where('nik', $penduduk->ibu_nik)->first()->id;

            if (! $id_ayah && $penduduk->kk_level == StatusHubunganEnum::ANAK) {
                $id_ayah = Penduduk::where('id_kk', $penduduk->id_kk)
                    ->where(static function ($query) {
                        $query->where('kk_level', StatusHubunganEnum::KEPALA_KELUARGA)
                            ->orWhere('kk_level', StatusHubunganEnum::SUAMI);
                    })
                    ->where('sex', JenisKelaminEnum::LAKI_LAKI)
                    ->first()->id;
            }

            if (! $id_ibu && $penduduk->kk_level == StatusHubunganEnum::ANAK) {
                $id_ibu = Penduduk::where('id_kk', $penduduk->id_kk)
                    ->where(static function ($query) {
                        $query->where('kk_level', StatusHubunganEnum::KEPALA_KELUARGA)
                            ->orWhere('kk_level', StatusHubunganEnum::ISTRI);
                    })
                    ->where('sex', JenisKelaminEnum::PEREMPUAN)
                    ->first()->id;
            }

            // Data Ayah
            $data = array_merge($data, $this->getIsianPenduduk($id_ayah, 'ayah'));

            // Data Ibu
            $data = array_merge($data, $this->getIsianPenduduk($id_ibu, 'ibu'));

            

            $id_ayah = Penduduk::where('nik', $penduduk->ayah_nik)->first()->id;
            $id_ibu  = Penduduk::where('nik', $penduduk->ibu_nik)->first()->id;

            // Data Ayah
            $data = array_merge($data, $this->getIsianPenduduk($id_ayah, 'ayah'));

            // Data Ibu
            return array_merge($data, $this->getIsianPenduduk($id_ibu, 'ibu'));
```

SOLUSI : 
- Gunakan 1 alur konsisten untuk mendapatkan data orang tua.

**Comment by andifahruddinakas** [comment]
Alur data dari kode isian orang tua sbb:
1. Jika penduduk tsb berada dalam 1 keluarga dan SHDK anak, maka data orang tua akan diambil dari : 
1.1 ayah = kepala keluarga atau suami, dengan jenis kelamin laki-laki
1.2 ibu = kepala keluarga atau istri, dengan jenis kelamin perempuan

2. Jika penduduk tsb berda dalam 1 keluarga dan SHDK bukan anak atau tidak memiliki keluarga, maka data orang tua akan diambil dari isian data penduduk (nik, nama ayah dan ibu) berdasarkan kondisi berikut : 
2.1. Jika ada NIK dan ada pada data penduduk, maka data akan diambil berdasarkan NIK penduduk tsb.
2.2 Jika ada NIK namun tdk ditemukan pada data penduduk atau NIK ayah/ibu diisi kosong, maka data yang ditampilkan kosong.
2.3 Jika point 2.2 terpenuhu namun pada data nama_ayah atau nama_ibu saja ( krn wajib isi) maka tampilkan data yang ada.

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2758
