### ISSUE TITLE
membatasi hak akses user kontributor

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#698]
membatasi hak akses user KONTRIBUTOR yang sekarang di Menu WEB ADMIN ada 3 sub menu yang bisa diakses
1. Artikel >>> bisa menambah dan mengubah khusus artikel yang dibuat oleh kontributor dan tidak bisa melihat artikel yang dibuat oleh Admin, Operator maupun Redaksi **dan ini sudah ok / tidak ada masalah**
2. Galeri >>>>> bisa menambah dan mengubah Galeri
3. Dokumen >>> bisa  menambah, mengubah dan menghapus
![screenshot 2017-11-04 22 01 05](https://user-images.githubusercontent.com/25834335/32406119-7f9d0a12-c1ad-11e7-9396-dc529a85b660.png)
![screenshot 2017-11-04 22 01 13](https://user-images.githubusercontent.com/25834335/32406124-8fe81ccc-c1ad-11e7-818f-53e26eb6b2bc.png)
![screenshot 2017-11-04 22 01 19](https://user-images.githubusercontent.com/25834335/32406127-a59965ee-c1ad-11e7-9d06-95eeebcae52f.png)

Jadi menurut saya KONTRIBUTOR hanya di kasih akses sub menu ARTIKEL atau point 1

**Comment by eddieridwan** [comment]
Sudah diterapkan berdasarkan spesifikasi hak akses di http://bit.ly/2Vhqmyz.
