### ISSUE TITLE
Bug/error: Laporan bulanan terjadi perbedaan

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#6984]
### Jelaskan error yg dialami

Laporan bulanan pada bagian penduduk terdapat perbedaan. Contoh dalam kasusu ini, pada laporan Penduduk akhir bulan ini (Mei 2023) = 3972, saat pindah ke bulan senlanjutnya (April 2023) akan menjadi Penduduk awal bulan ini. Namun terlihat Penduduk awal bulan ini (April 2023) = 3973. Sehingga terjadi perbedaan pada laopran tersebut, untuk laporan yang benar sesuai data seharusnya adalah 3973.

### Cara untuk mereplikasi errornya

1. Gunakan database yang bermasalah (terlampir)
2. Masuk modul statistik > laporan bulanan
3. lakukan filter pada bulan mei
4. buka tab baru pada halaman yang sama, lakukan filter pada bulan juni
5. bandingkan jumlah penduduk akhir pada bulan mei dan penduduk awal bulan juni tidak sama

### Hasil yg diharapkan

Laporan sesuai sebagaimana mestinya

### Tangkapan layar dan log error

**Mei 2023**
<img width="525" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/09ecf557-e1c4-44f4-b731-8a39100ad451">

**Juni 2023**
<img width="518" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/7ffa1e3b-ee66-4d23-b9cd-1c1a69d20e4a">

**Dashborad**
<img width="140" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/8302779e-612c-41cc-818c-018f21729bca">

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v2308.0.0

### Tema Yang Digunakan

.

### Informasi tambahan

SOLUSI : 
- [ ] laporan penduduk akhir bulan ini, harusnya sama dengan laporan penduduk awal bulan yang akan datang.

**Comment by eddieridwan** [comment]
@vickyrolanda @andifahruddinakas 

Seperti dibahas di grup, masalah perbedaan ini sudah waktunya ditangani tuntas. Yaitu dengan melakukan peninjauan ulang secara menyeluruh. Karena masalahnya mencakup banyak menu/fitur/modul, maka perlu diuraikan secara sistematis dan rinci di dokumen terpisah. 

Kemudian rencana kerja berserta issue untuk dikerjakan diturunkan dari hasil analisis dan rancang ulang di dokumen tersebut.

Dokumen rancang ulang: https://docs.google.com/document/d/1c89XM2L5gCDfx3QE_tvHiR-VTyqqDNFgO6usBekhVAQ/edit?usp=sharing

**Comment by vickyrolanda** [comment]
Baik Pak biar saya lengkapi dlu kebtuhannya melalui dokumen itu.

**Comment by pandigresik** [comment]
Ada data yang aneh di pada tweb_penduduk status dasar 3 namun di log_penduduk terakhir kode_peristiwa adalah 5

`select id, id_pend, kode_peristiwa, tgl_lapor, updated_at  from log_penduduk lp where lp.id_pend  = 11405`

![image](https://github.com/OpenSID/OpenSID/assets/1853475/c3c248b4-9c17-484b-a369-f1cd5cd6a1b8)

`select id, nama, status_dasar  from tweb_penduduk tp where tp.id = 11405`

![image](https://github.com/OpenSID/OpenSID/assets/1853475/4d031811-85b7-4409-9052-eb2148b8e784)

Apakah ini anomali data ataukah memang seperti itu ?

**Comment by pandigresik** [comment]
Ada data yang agak aneh, dimana data pada penduduk memiliki status dasar = 3, namun di log terakhir kode_peristiwa 5. Sepertinya tidak cocok.
/**
     * KETERANGAN kode_peristiwa di log_penduduk
     * 1 = insert penduduk baru dengan status lahir
     * 2 = penduduk mati
     * 3 = penduduk pindah keluar
     * 4 = penduduk hilang
     * 5 = insert penduduk baru pindah masuk
     * 6 = penduduk tidak tetap pergi
     */

select id, id_pend, kode_peristiwa, tgl_lapor, created_at  from log_penduduk lp where lp.id_pend  = 11405
![image](https://github.com/OpenSID/OpenSID/assets/1853475/9ce7c973-dc5a-4000-adc3-d50634c94d53)

select id, nama, status_dasar, created_at, updated_at  from tweb_penduduk tp where tp.id = 11405
![image](https://github.com/OpenSID/OpenSID/assets/1853475/d8200926-8931-4ede-9f5b-11497c50133d)

Apakah memang seperti ini model datanya ?

**Comment by pandigresik** [comment]
Ini desa yang sama dengan issue ini https://github.com/OpenSID/OpenSID/issues/6745

**Comment by pandigresik** [comment]
Apakah database yang digunakan oleh desa ini masih asli dari aplikasi opensid ? 
Ataukah pernah dilakukan edit langsung di database tidak melalui aplikasi ?

Ada kode_peristiwa 12, menggunakan db dari issue #6984
![image](https://github.com/OpenSID/OpenSID/assets/1853475/89158d19-9694-4981-8bca-7154b342ed1a)

![image](https://github.com/OpenSID/OpenSID/assets/1853475/fe9d6aaa-81d4-4c87-be97-c5d839e08d2b)

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2859
