### ISSUE TITLE
di Sub menu Dokumen pilihan kategori dihapus

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#699]
Sub menu Dokumen yang ada di Menu Admin Web untuk PIlihan Kategori diperlu ada pilihan atau dihapus saja
![screenshot 2017-11-05 09 49 46](https://user-images.githubusercontent.com/25834335/32411171-4303d98e-c20f-11e7-9cfc-2b5a3e4439e4.png)

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui pull request #808
