### ISSUE TITLE
Bug/error: Permohonan Kartu Keluarga

### ISSUE THREAD

**Issue by afri18** [OpenSID/OpenSID#6993]
### Jelaskan error yg dialami

Pada menu cetak surat untuk Permohonan Kartu Keluarga masih tercantum anggota keluarga yang sudah pindah, seharusnya tidak

### Cara untuk mereplikasi errornya

terpaksa hapus manual

### Hasil yg diharapkan

Seharusnya yang tercantum anggota keluarga yang masih ada

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/6611881/30d389ff-1b40-4904-9b87-96d881377a41)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

beta

### Tema Yang Digunakan

https://beta.opendesa.id/

### Informasi tambahan

seharusnya anggota keluarga dengan status tetap saja yang terlampir/tercantum

**Comment by andifahruddinakas** [comment]
cek ulang issue ini jika issue https://github.com/OpenSID/OpenSID/issues/6987 mungkin terkait
