### ISSUE TITLE
Bug/error: Halaman Laporan Aset yang Dihapus Berantakan

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#6995]
### Jelaskan error yg dialami

![IMG_20230807_204416_123](https://github.com/OpenSID/OpenSID/assets/46939846/0ec82144-a8d1-4c25-994e-6cd7bc4c83cb)

![IMG_20230807_204418_434](https://github.com/OpenSID/OpenSID/assets/46939846/92030861-5e4a-4e11-b033-7ab8fec44e0d)

![IMG_20230807_204420_245](https://github.com/OpenSID/OpenSID/assets/46939846/31fc8201-7a7b-4e44-a24f-4f437dc719e3)

### Cara untuk mereplikasi errornya

masuk menu Inventaris
klik Laporan Semua Aset
klik Laporan Aset yang dihapus

seperti urutan panah pada gambar di atas.

### Hasil yg diharapkan

sebagaimana semestinya.

### Tangkapan layar dan log error

di atas

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Berputar

**Comment by andifahruddinakas** [comment]
SOLUSI : 
- [ ] perbaikan pada saat load view.

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2764
