### ISSUE TITLE
Bug/error: Luas wilayah peta tidak tampil di halaman peta (halaman depan)

### ISSUE THREAD

**Issue by WAHYUDIK** [OpenSID/OpenSID#6996]
### Jelaskan error yg dialami

ketika luas wilayah sudah diseting menjadi YA di pengaturan pemetaan dan di halaman admin sudah muncul luasnya, akan tetapi untuk halaman depan di menu peta tidak tampil luasnya

### Cara untuk mereplikasi errornya

buka menu peta kemudian centang peta wilayah desa

### Hasil yg diharapkan

luas wilayah juga tampil di bagian menu peta di tampilan depan, bukan hanya di admin saja

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/31026980/519eddf7-b1b0-4665-8c75-066413bf6e88)
![image](https://github.com/OpenSID/OpenSID/assets/31026980/855bfe73-9941-473c-8305-9fdc75695ba4)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

OpenSID 2308.0.1-premium |

### Tema Yang Digunakan

 Natra v22.1

**Comment by andifahruddinakas** [comment]
Untuk saat ini luas peta yang dikerjakan terlebih dahulu adalah pada bagian admin, karena penyesuaian tsb belum merata. Untuk bagian halaman web, akan dikerjakan setelah bagian admin rampung.

**Comment by yogiperdana** [comment]
Ini berarti perubahannya ke tema mas @andifahruddinakas ?

**Comment by andifahruddinakas** [comment]
> Ini berarti perubahannya ke tema mas @andifahruddinakas ?

Ya, bagian tema. Namun corenya ada di peta.js yg digunakan di tema dan admin.

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2888
