### ISSUE TITLE
Bug/error: Cek hasil Install Baru 2308.0.0-premium

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#6997]
### Jelaskan error yg dialami

terdapat isian tabel user id 1 dan 2. dengan data yang sama. kecuali:
config_id NULL pada id 1 dan 1 pada id 2.
id_group 1 pada id 1 dan 6 pada id 2.

setelah di cek pada user_group, ada penerapan ganda.
id 1 sampai 5 dengan config_id NULL
dan id 6 sampai 10 config_id 1

mengakibatkan user admin utama menjadi ber ID 2.

### Cara untuk mereplikasi errornya

di atas

### Hasil yg diharapkan

kembali normal seperti semula

### Tangkapan layar dan log error

bisa di tes

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Terbaru

**Comment by ariandii** [comment]
di tabel setting_aplikasi juga kacau, tabel kembar semua

**Comment by ariandii** [comment]
di tabel setting_modul juga kacau, tabel kembar semua

**Comment by ariandii** [comment]
di media_sosial juga kacau, tabel kembar semua

**Comment by ariandii** [comment]
di ref_jabatan juga kacau, tabel kembar semua

**Comment by ariandii** [comment]
dan semua tabel yang memiliki config_id, akan 2x lipat terdiri dari NULL dan config_id 1

**Comment by scqolbu24** [comment]
Terjadi eror juga pada pelanggan SiapPakai untuk pendaftaran pelanggan baru, semua tabel yang erdapat config_id akan terduplikat dengan status null dan sesuai config_id

![image](https://github.com/OpenSID/OpenSID/assets/68048807/c9e67bc4-7054-4368-9ac2-f2045baa13e7)
![image](https://github.com/OpenSID/OpenSID/assets/68048807/8aadb178-c130-4484-8acb-3bc1a0dd9b2d)

**Comment by andifahruddinakas** [comment]
Untuk bagian ini pernah diterapkan, jika sudah ada semua config_id null akan dihapus. Namun laporan terakhir terdapat pelanggan yang datanya terhapus (mungkin karena delay server jadi tidak sempat update config_id), maka perubahan di tiadakan.

Penyebab utamanya, karena adanya 2 Seeder yang dijalankan.

Solusi : 
- [ ] kerjakan issue https://github.com/OpenSID/premium/issues/2548 (namun pekerjaannya agak besar)
- [ ] kembalikan cara lama, yakni menghapus data config_id null jika sudah ada (mungkin akan berpengaruh bagi pengguna jika terjadi delay pada server)

**Comment by ariandii** [comment]
bagaimana nasib ID yg sudah tercipta? karena semua seluruhnya config_id 1 ada di hasil duplikatnya.

contoh ID 1 sampai 20 itu config_id nya NULL
yang berisi 1 adalah 21 sampai 40

bahkan banyak data kembar di tabel analisis di siappakai.

===
contoh lain seperti di gambarbatas,
user admin dengan config_id 1 ada di ID 2

termasuk jabatan, Kepala Desa config_id 1 jadi ID 3 dan sekdes ID 4

dan seterusnya.

**Comment by agungsugiarto** [comment]
Pak @ariandii bisa kirim backup databasenya yang berantakan ke saya atau ke mas @andifahruddinakas ?

**Comment by ariandii** [comment]
biaa dicoba saja lakukan install baru 2308.0.0 premium, maka akan memiliki db berantakan.

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2761
