### ISSUE TITLE
Bug/error: tes input Data penduduk 100% sama kecuali NIK

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#6998]
### Jelaskan error yg dialami

ada 2 aparatur desa input penduduk tanpa cek.

1 input data dengan NIK sementara (misal 1 januari 2020)
dan
1 input data dengan NIK betulan (misal 30 Juli 2023)

keduanya sudah melakukan aktifitas mulai cetak surat, bantuan, dll.

yang tanpa disadari.

### Cara untuk mereplikasi errornya

akan ada 2 penduduk dengan aktofitas masing masing di opensid
dengan penduduk yang sama.

### Hasil yg diharapkan

Apakah memungkinkan menggabungkan 2 atau lebih data NIK berbeda dengan orang yang sama.

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

-

**Comment by andifahruddinakas** [comment]
Untuk kasus seperti ini aplikasi belum mendukung tambah/ubah dengan kondisi data penduduk yang di input hampir sama karena parameternya berbeda-beda, adapun yang biasa digunakan sebagai pembanding yakni:nama, tgl_lahir, tempat_lahir, nama_ibu, nama_ayah.

Pak @eddieridwan, @ariandii, @vickyrolanda, bisa dicek untuk kasus di atas. Kalau mau diterapkan kasus di atas, bisa dimulai di versi yang akan datang karena melihat kondisi bug saat ini.

**Comment by eddieridwan** [comment]
@vickyrolanda @andifahruddinakas seharusnya tidak mungkin ada 2 NIK betulan berbeda untuk orang yg sama. Jika terjadi, kesalahan ada di Dukcapil, dan perlu diselesaikan melalui Dukcapil.

Untuk OpenSID, masalah yg relevan hanya jika penduduk dengan NIK sementara dibuat untuk orang yg sudah ada database dengan NIK betulan atau dengan NIK sementara lainnya. Jadi yg perlu diperhatikan adalah proses pembuatan penduduk baru dengan NIK sementara. Yaitu apakah ada proses yg dapat mengurangi terjadinya pembuatan penduduk dengan NIK sementara yg merupakan duplikat bagi penduduk lain yg sudah ada di database.

Terkait prioritas, pendapat saya tidak mendesak, dan dapat dijadwalkan analisisnya setelah bug dan kerancuan yg lebih mendesak dulu.

**Comment by vickyrolanda** [comment]
Kalo dilihat dari konteks sudut pandang user yang disampaikan pak ariandi bisa terjadi karna input data masih mengijinkan dilakukan jika NIK berbeda. 

Biasanya secara UI-UX duplikasi data juga bisa diminimalisir kan dengan konfirmasi setelah data penduduk di isi, dan dikonfirmasi untuk di simpan. 

Maka proses konfirmasi itu bisa dilakukan proses pemeriksaaan persamaan identik dengan menerapkan minimal 50℅ data sama dari field yg di isi maka muncul rekomendasi untuk mereplace (update data) atau tetap lanjut kependuduk baru. 

Maka jika tetap terjadi duplikasi data diatas maka kesalahan tentu ada pada operator karena system sebelum nya sudah memberitahu bahwa ada data yang mungkin sama. 

Dan hal diatas memang tidak bsa dihindari tpi bisa diminimalisir. 

Satu satunya data penduduk yg tidak akan sama hanya NIK. Selebihnya mukin bsa sama.

**Comment by andifahruddinakas** [comment]
> Kalo dilihat dari konteks sudut pandang user yang disampaikan pak ariandi bisa terjadi karna input data masih mengijinkan dilakukan jika NIK berbeda.
> 
> Biasanya secara UI-UX duplikasi data juga bisa diminimalisir kan dengan konfirmasi setelah data penduduk di isi, dan dikonfirmasi untuk di simpan.
> 
> Maka proses konfirmasi itu bisa dilakukan proses pemeriksaaan persamaan identik dengan menerapkan minimal 50℅ data sama dari field yg di isi maka muncul rekomendasi untuk mereplace (update data) atau tetap lanjut kependuduk baru.
> 
> Maka jika tetap terjadi duplikasi data diatas maka kesalahan tentu ada pada operator karena system sebelum nya sudah memberitahu bahwa ada data yang mungkin sama.
> 
> Dan hal diatas memang tidak bsa dihindari tpi bisa diminimalisir.
> 
> Satu satunya data penduduk yg tidak akan sama hanya NIK. Selebihnya mukin bsa sama.

Salah satu aplikasi SID ada disedikan status tingkat kemiripan data, dan parameter pembandingkan seperti nama, tgl_lahir, tempat_lahir, nama_ayah, nama_ibu, dan munkin paramter lainnya yg dianggap unik. Namun hanya memberikan informasi saja, untuk perbaikan datanya tetap dilakukan oleh pengguna itu sendiri, apakah di hapus atau proses lainnya.

**Comment by andifahruddinakas** [comment]
penerapan : 
- [ ] pada nik sementara
- [ ] jika terapat data yg sama pd isian : nama, tgl_lahir, tempat_lahir, jk.
- [ ] tampilkan notifikasi jika data tsb sudah ada
