### ISSUE TITLE
Bug/error: Token Input Sembarang pada Install Awal 2308.0.0 premium

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#6999]
### Jelaskan error yg dialami

ketika awal install 2308.0.0 premium diminta input token pada halaman yang terbuka.

karena desa belum dapat info, diisilah sembarang huruf. misal hanya 2 digit. dan simpan.

maka lolos dan bisa lanjut login untuk isi identitas desa.

### Cara untuk mereplikasi errornya

di atas

### Hasil yg diharapkan

keberadaan halaman input token menjadi Mubazir ketika diisi sembarang tetap bisa lolos untuk melanjutkan langkah install selanjutnya.

tujuannya apa? tidak ada.

hanya sekedar langkah tambahan yang tidak harus diisi betulan.

### Tangkapan layar dan log error

bisa dicoba

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2308.0.0 premium

**Comment by andifahruddinakas** [comment]
Walaupun lolos pengecekan dibagian halaman token, pada halaman admin akan di cek kembali. Namun alurnya akan terjadi 2 kali.

SOLUSI : 
- [ ] tammbahkan pengecekan ke layanan setiap kali simpan token.

**Comment by andifahruddinakas** [comment]
mas @agungsugiarto, bisa kerja ini dlu biar masuk rilis rev01.

**Comment by andifahruddinakas** [comment]
> Walaupun lolos pengecekan dibagian halaman token, pada halaman admin akan di cek kembali. Namun alurnya akan terjadi 2 kali.
> 
> SOLUSI :
> 
> * [ ]  tammbahkan pengecekan ke layanan setiap kali simpan token.

Tujuan adanya pengecekan di redirect ke halaman luar agar semua yang berkaitan dengan database dihilangkan. Mencegah rusaknya database termigrasi otomatis oleh aplikasi. 

Untuk saat ini, inputan token yang dicek hanyalah massa berlanggan apakah sesuai dengan aplikasi yang digunakan. Apapun pengecekan antara token dan identitas desa bisa dilakukan lewat installer yang sedang dikerjakan (https://github.com/OpenSID/premium/pull/2475)

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2757
