### ISSUE TITLE
Bug/error: 2 tombol berbeda dengan menampilkan hasil yang sama.

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#7001]
### Jelaskan error yg dialami

![Screenshot_20230807_212305_Chrome](https://github.com/OpenSID/OpenSID/assets/46939846/d6088cfd-c1db-4e54-b110-89b12a2831b6)

### Cara untuk mereplikasi errornya

Buka menu Data suplemen.

### Hasil yg diharapkan

agar tidak membingungkan dan agar konsisten. buat link 1 jenis saja.

### Tangkapan layar dan log error

di atas

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Berputar

**Comment by andifahruddinakas** [comment]
SOLUSI : 
- [ ] gunakan 1 tombol yakni tombol **rincian**, selain itu dihapus untuk menghindari duplikasi fungsi.

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2783
