### ISSUE TITLE
Bug/error: Gagal Input Pembangunan tidak konsisten

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#7002]
### Jelaskan error yg dialami

gambar 4
![Screenshot_20230807_213906_Chrome](https://github.com/OpenSID/OpenSID/assets/46939846/bde9d14b-95ad-44b5-ab2e-e93d238d37d9)

gambar 3
![Screenshot_20230807_213834_Chrome](https://github.com/OpenSID/OpenSID/assets/46939846/a426c34d-daf1-40c8-b082-7ee301f6296f)

gambar 2
![Screenshot_20230807_213746_Chrome](https://github.com/OpenSID/OpenSID/assets/46939846/d3e82f6d-73a3-43e7-a87f-2ae4f8a61a41)

gambar 1
![Screenshot_20230807_213729_Chrome](https://github.com/OpenSID/OpenSID/assets/46939846/73017dfb-3441-4440-b7eb-9f9f9bd40f9c)

### Cara untuk mereplikasi errornya

buka menu pembangunan, tambah data.

klik simpan.

hanya 2 kolom yg diwajibkan (gambar 1)
setelah diisi 2 kolom itu, klik simpan.
muncul kolom lain yg wajib diisi (gambar 2)

dan seterusnya.

### Hasil yg diharapkan

konsisten sebagaimana seharusnya.

### Tangkapan layar dan log error

di atas

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2308.0.0 premium

**Comment by andifahruddinakas** [comment]
SOLUSI:
- [ ] tampilkan sekaligus inputan yang wajib isi.

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2836
