### ISSUE TITLE
Bug/error: Data Orang Tua pada Surat TinyMCE Biodata Penduduk, tidak menampilkan data Nama Ibu, NIK Ibu, Nama Ayah, NIK Ayah

### ISSUE THREAD

**Issue by mah-mudi** [OpenSID/OpenSID#7003]
### Jelaskan error yg dialami

Data Orang Tua pada Surat TinyMCE Biodata Penduduk, tidak menampilkan data Nama Ibu, NIK Ibu, Nama Ayah, NIK Ayah

### Cara untuk mereplikasi errornya

1. cetak surat TinyMCE biodata penduduk
2. pilih penduduk
3. Tinjau Pdf

### Hasil yg diharapkan

data Nama Ibu, NIK Ibu, Nama Ayah, NIK Ayah dapat muncul sesuai data penduduk ybs

### Tangkapan layar dan log error

berikut data penduduk ybs
<img width="553" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57661283/f5b0c92b-130b-4d53-a6cd-357c45a73e89">

berikut kode isian pd surat tinyMCE Biodata Penduduk
<img width="695" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57661283/84647ba4-c239-4366-9ef7-e3a6b1c91dc4">

berikut hasil tinjau pdf nya
<img width="682" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57661283/2ec75d44-7ac1-42e3-9a9d-938ac361a474">

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

23.08.01

### Tema Yang Digunakan

natra

### Informasi tambahan

beta.opendesa.id

**Comment by ariandii** [comment]
https://github.com/OpenSID/OpenSID/issues/6979

**Comment by andifahruddinakas** [comment]
Duplicate issue https://github.com/OpenSID/OpenSID/issues/6979
