### ISSUE TITLE
Bug/error: Luas wilayah peta tidak tampil di halaman widget

### ISSUE THREAD

**Issue by WAHYUDIK** [OpenSID/OpenSID#7004]
### Jelaskan error yg dialami

luas wilayah peta di widget tidak tampil

### Cara untuk mereplikasi errornya

buka artikel (sembarang)
geser artikel ke bawah sampail widget peta terlihat

### Hasil yg diharapkan

luas wilayah di widget peta bisa ditampilkan

### Tangkapan layar dan log error

![2023-08-07_21h45_22](https://github.com/OpenSID/OpenSID/assets/31026980/db8049b1-2c6a-413e-acb8-76781eb4c260)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

beta.opendesa

**Comment by ariandii** [comment]
https://github.com/OpenSID/OpenSID/issues/6996

**Comment by andifahruddinakas** [comment]
Duplicate issue https://github.com/OpenSID/OpenSID/issues/6996
