### ISSUE TITLE
Bug/error: Pilihan Kode Isian penduduk pada data ayah dan ibu banyak yg ganda ketika setting template surat

### ISSUE THREAD

**Issue by mah-mudi** [OpenSID/OpenSID#7005]
### Jelaskan error yg dialami

Pilihan Kode Isian penduduk pada data ayah dan ibu banyak yg ganda ketika setting template surat

### Cara untuk mereplikasi errornya

1. pengaturan surat
2. template surat
3. kode isian - penduduk

### Hasil yg diharapkan

Pilihan Kode Isian penduduk pada data ayah dan ibu tidak ganda ketika setting template surat

### Tangkapan layar dan log error

kode isian penduduk, data ayah ganda
<img width="714" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57661283/829ce626-f04e-4f97-9cd4-5fd402d75f5c">

<img width="735" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57661283/3f4612e6-4e3f-4077-acda-26f74423195d">

kode isian penduduk, data ibu ganda
<img width="767" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57661283/320353d4-c5fe-4663-9b94-3d75115812a8">
<img width="786" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57661283/637527ba-d6e8-4cbd-92fa-ad79bcdb41ec">

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

23.08.01

### Tema Yang Digunakan

natra

### Informasi tambahan

beta.opendesa.id

**Comment by andifahruddinakas** [comment]
Pak @mah-mudi, yang ganda seperti apa? saya cek dan lihat di SS yang dikirim tidak ada yang ganda. Kalau yang dimaksu ganda adalah kode isian tempat dan tgl lahir ini, memang disediakan 2 kode isian.
<img width="133" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/8b0e8edf-43a9-449c-aab6-587b2d62f7c0">

**Comment by mah-mudi** [comment]
@andifahruddinakas saya jelaskan lewat video aja

https://github.com/OpenSID/OpenSID/assets/57661283/7ba14d43-4fb1-48f9-9384-d8f0be1da7ef
