### ISSUE TITLE
Bug/error: Hasil Cetak Data Arsip Layanan Surat, Nama dan Jabatan Kepala Desa menjadi dua baris

### ISSUE THREAD

**Issue by mah-mudi** [OpenSID/OpenSID#7006]
### Jelaskan error yg dialami

Hasil Cetak Data Arsip Layanan Surat, Nama dan Jabatan Kepala Desa menjadi dua baris

### Cara untuk mereplikasi errornya

1. arsip layanan
2. cetak
3. lihat nama jabatan dan nama kades menjadi dua baris

### Hasil yg diharapkan

Hasil Cetak Data Arsip Layanan Surat, Nama dan Jabatan Kepala Desa menjadi satu baris

### Tangkapan layar dan log error

<img width="256" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57661283/89dcf073-95ad-4439-9495-140fad882d89">

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

23.08.01

### Tema Yang Digunakan

natra

### Informasi tambahan

beta.opendesa.id

**Comment by andifahruddinakas** [comment]
Untuk kasus ini mungkin terjadi pada nama penduduk yang agak panjang, solusi sementara yang bisa dilakukan agar bisa digunakan, bisa lakukan ekspor excel.

SOLUSI:
- [ ] gunakan cara yang sama yang sudah diterapkan di beberapa modul lainnya, seperti modul pengurus dengan menggunakan view global tanda tangan
`<?php $this->load->view('global/blok_ttd_pamong.php', ['total_col' => 13, 'spasi_kiri' => 3, 'spasi_tengah' => 6]); ?>`

**Comment by andifahruddinakas** [comment]
Issue dibuat lebih umum pada https://github.com/OpenSID/OpenSID/issues/7012
