### ISSUE TITLE
Jabatan di sub menu kelompok masih bisa dipilih sehingga menggantikan jabatan yang sudah diinput sebelumnya

### ISSUE THREAD

**Issue by WAHYUDIK** [OpenSID/OpenSID#7007]
### Jelaskan error yg dialami

entri data kelompok beserta anggota, jabatan di kelompok yang sudah ada masih bisa dipilih dan disimpan, sehingga mengakibatkan data jabatan kelompok yang sudah ada sebelumnya tergantikan oleh jabatan yang baru dientri.

![image](https://github.com/OpenSID/OpenSID/assets/31026980/7237758c-d2a6-4e13-930c-1761d64a4a22)
data kelompok dengan ketua atas nama ariandi, 

![image](https://github.com/OpenSID/OpenSID/assets/31026980/f4c121d8-7dcc-4848-9065-e24487316ccc)
entri kembali 1 nama dengan jabatan ketua, berhasil disimpan akan tetapi mengganti posisi ketua yang sudah dientri sebelumnya

### Cara untuk mereplikasi errornya

1 pergi ke halaman sub menu kelompok
2. buat kelompok baru/tambah anggota/ketua di kelompok yang sudah ada
3. input 1 orang dengan jabatan yang sudah ada sebelumnya (misalkan ketua kelompok/dll)
4. simpan

### Hasil yg diharapkan

jabatan yang sudah ada  (khusus untuk ketua, wakil ketua, sekretaris dan bendahara)tidak bisa digunakan kembali oleh orang yang baru dientri, kecuali untuk anggota.

### Tangkapan layar dan log error

di atas

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

beta.opendesa 

### Informasi tambahan
jika memang ada lebih dari 1 wakil ketua/sekretaris/bendahara lebih baik ditambahkan pilihan wakil ketua 1, wakil ketua 2....dst.
_No response_

**Comment by andifahruddinakas** [comment]
jika alur ini diubah, perlu disediakan cara untuk mengubah jabatan jika ada pergantian dari ketua, wakil ketua, sekretaris dan bendahara. Adapun langkah yang panjang jika diterapkan nanti, untuk mengubah data ketua misalnya. Jabatan ketua diganti menjadi anggota, kemudian anggota yang akan di jadikan ketua diubah jabatannya.

Dalam hal ini, perubahan ini lebih mengarah ke permintaan fitur.

Pak @eddieridwan, apakah alur ini perlu diubah?

**Comment by eddieridwan** [comment]
Alur seperti ini terkait selera pengguna. **Bukan bug.** 

Opsi satu lagi: Jika anggota lain (termasuk yg baru) akan diubah jabatannya menjadi jabatan yg sudah dipegang orang lain, tampilkan notifikasi konfirmasi: "Jabatan xxx sudah dipegang yyy. Klik Simpan untuk konfirmasi akan menggantikan jabatan itu." Notifikasi ini pada waktu akan menyimpan perubahan/penambahan anggota, bukan pada waktu memilih jabatan.

Opsi ini tidak multi-langkah, dan akan memberi info bagi pengguna supaya dapat menghindari aksi keliru (seperti yg dikeluhkan oleh issue ini).
