### ISSUE TITLE
Bug/error: Nomor Surat pada berkas fisik berbeda dengan database, ketika cek TTE via Goolge Lens

### ISSUE THREAD

**Issue by mah-mudi** [OpenSID/OpenSID#7008]
### Jelaskan error yg dialami

Nomor Surat pada berkas fisik berbeda dengan database, ketika cek TTE via Goolge Lens

### Cara untuk mereplikasi errornya

1. arsip surat layanan surat yg sdh ber TTE
2. buka google lens, dan scan
3. nomor surat yg sdh berTTE di database berbeda dg nomor surat pd berkas fisik, hanya menampilkan format nomor persuratan

### Hasil yg diharapkan

Nomor Surat pada berkas fisik sama dengan database, ketika cek TTE via Goolge Lens

### Tangkapan layar dan log error

format penomoran surat pada setting surat
<img width="630" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57661283/533f553e-e8a3-4ea4-b73c-e4638c96f398">

hasil nomor surat fisik
<img width="493" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57661283/67c39a92-0205-4908-820a-62ae4c1f8409">

cek kebenaran surat sdh tercatat di database via Google Lens
![photo_6235777749532914868_y](https://github.com/OpenSID/OpenSID/assets/57661283/8f1d6f4e-132f-4cae-9f55-4f8045bf66cb)

hasil ketika cek dg google lens, nomor nya nembak ke format nomor surat bukan nembak ke nomor sebagaimana mestinya
![photo_6235777749532914867_y](https://github.com/OpenSID/OpenSID/assets/57661283/e611dde2-b3fa-478a-94fd-90d12f17918f)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

23.08.01

### Tema Yang Digunakan

silir

### Informasi tambahan

desaleran.gresikkab.go.id

**Comment by andifahruddinakas** [comment]
Cek di versi terbaru
