### ISSUE TITLE
Bug/error: kolom nomor anggota di sub menu kelompok masih bisa menyimpan nomor yang sama

### ISSUE THREAD

**Issue by WAHYUDIK** [OpenSID/OpenSID#7009]
### Jelaskan error yg dialami

saat kita menambah anggota kelompok dengan menggunakan nomor yang sudah ada, masih bisa tersimpan

### Cara untuk mereplikasi errornya

1. pergi ke halaman sub menu kelompok
2. buat kelompok baru/tambah anggota kelompok yang sudah ada
3. input nomor anggota dengan nomor anggota yang sudah tersimpan sebelumnya
4. simpan

### Hasil yg diharapkan

sistem menolak jika menambahkan anggota dengan nomor anggota yang sama

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/31026980/b3680981-196e-4a6e-8183-d0ef6babd44d)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

beta.opendesa

**Comment by andifahruddinakas** [comment]
SOLUSI : 
- [x] buat unique kolom config_id dan no_anggota
- [x] tampilkan notifikasi, jika no_anggota sudah digunakan

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2765
