### ISSUE TITLE
Setelah migrasi terjadi Duplikat Sekretariat

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#701]
di Rilis pasca 2.6 setiap kali klik Migrasi DB menu SEKRETARIAT menjadi Banyak atau DUPLIKAT seperti gambar dibawah ini : 
![screenshot 2017-11-05 20 42 16](https://user-images.githubusercontent.com/25834335/32414984-ad7e811c-c26c-11e7-930d-b2b805441f82.png)

![screenshot 2017-11-05 20 56 30](https://user-images.githubusercontent.com/25834335/32414994-c13c3c26-c26c-11e7-93f1-0e39b707f906.png)

mohon supaya segera dikerjakan karena sangat berpengaruh

**Comment by eddieridwan** [comment]
@MUHAMMADRANGSEL : Seharusnya tidak bisa. Kami tidak bisa replikasi. Di http://sid.bangundesa.info tidak bermasalah. Coba lampirkan database anda untuk dilacak masalahnya.

**Comment by eddieridwan** [comment]
@MUHAMMADRANGSEL: apakah masih mengalami masalah ini? Kalau masih, silakan lampirkan database anda untuk dilacak.

**Comment by MUHAMMADRANGSEL** [comment]
Sudah kami temukan ada.duplikat di database setting modul

Pada tanggal 8 Nov 2017 07:09, "Eddie Ridwan" <notifications@github.com>
menulis:
