### ISSUE TITLE
Bug/error: Tombol hapus di kategori kelompok seharusnya tidak berfungsi/non aktif apabila sudah ada data kelompoknya

### ISSUE THREAD

**Issue by WAHYUDIK** [OpenSID/OpenSID#7010]
### Jelaskan error yg dialami

tombol hapus yang ada di kategori kelompok masih berfungsi meskipun di data kelompoknya sudah ada daftar kelompok.

### Cara untuk mereplikasi errornya

1. pergi ke halaman sub menu kelompok
2. klik tambah kelola kategori kelompok
3. klik tombol hapus data kelompok yang sudah ada data kelompoknya

### Hasil yg diharapkan

apabila kategori kelompok/kelompok sudah ada isi/anggotanya seharusnya tombol delet dinonaktifkan, untuk menghindari kesahalan operator/admin salah maksud

### Tangkapan layar dan log error

https://github.com/OpenSID/OpenSID/assets/31026980/99b319f0-5f63-4867-84b8-660b4c673da1

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

beta.opendesa

**Comment by andifahruddinakas** [comment]
Kasus seperti ini mungkin banyak terjadi dimodul-modul lain yang menerapkan sistem sub data, karena bawaan cara lama kemungkinan belum disesuaikan.

SOLUSI :
- [ ] Terapkan kondisi hapus sbb:
Jika data utama sudah digunakan pada sub-sub data yang data, tombol hapus dihilangkan dan fungsi hapus (lewat url) tampilkan notifikasi gagal

**Comment by WAHYUDIK** [comment]
betul mas, di menu lembaga juga sama kasusnya

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2766

**Comment by WAHYUDIK** [comment]
![image](https://github.com/OpenSID/OpenSID/assets/31026980/cd861e3a-ef94-4030-acbb-96943dc72963)
sekalian untuk tombol hapusnya yang sudah ada datanya dinon aktifkan juga mas, seperti di bantuan
![image](https://github.com/OpenSID/OpenSID/assets/31026980/8f89203a-2d6a-4150-a94c-8b71d76bb742)


berlaku juga di menu lembaga.
