### ISSUE TITLE
Bug/error: kop dan judul LAPORAN DATA STATISTIK PENGUNJUNG WEBSITE SETIAP TAHUN tidak ada jarak dan tidak ada ttd mengetahui kades

### ISSUE THREAD

**Issue by mah-mudi** [OpenSID/OpenSID#7011]
### Jelaskan error yg dialami

kop dan judul LAPORAN DATA STATISTIK PENGUNJUNG WEBSITE SETIAP TAHUN tidak ada jarak

### Cara untuk mereplikasi errornya

1. admin web
2. pengunjung
3. cetak

### Hasil yg diharapkan

kop dan judul LAPORAN DATA STATISTIK PENGUNJUNG WEBSITE SETIAP TAHUN ada jarak

### Tangkapan layar dan log error

<img width="948" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57661283/9dc8a0e1-e005-4cbe-9712-54b725b3413c">

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

23.08.01

### Tema Yang Digunakan

natra

### Informasi tambahan

beta.opendesa.id

**Comment by andifahruddinakas** [comment]
SOLUSI : 
- [ ] agar konsisiten, buat 1 view header untuk cetak dengan menggunakan referensi header beikut:
<img width="245" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/5130df67-b76c-41eb-adad-7acc5471b364">
<br>ada di modul **Buku Induk Penduduk**

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2817
