### ISSUE TITLE
Bug/error: Hasil Cetak Data, Nama dan Jabatan Kepala Desa yang panjang

### ISSUE THREAD

**Issue by mah-mudi** [OpenSID/OpenSID#7012]
### Jelaskan error yg dialami

Hasil Cetak Data Persil, Nama dan Jabatan Kepala Desa menjadi dua baris

### Cara untuk mereplikasi errornya

1. pertanahan
2. daftar persil
3. cetak

### Hasil yg diharapkan

Hasil Cetak Data Persil, Nama dan Jabatan Kepala Desa menjadi satu baris

### Tangkapan layar dan log error

<img width="275" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57661283/b97ec7da-7527-46f7-a5a2-0f07ab9c92da">

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

23.08.01

### Tema Yang Digunakan

natra

### Informasi tambahan

beta.opendesa.id

**Comment by andifahruddinakas** [comment]
Untuk kasus ini mungkin terjadi pada nama penduduk yang agak panjang, solusi sementara yang bisa dilakukan agar bisa digunakan, bisa lakukan ekspor excel.

SOLUSI:
- [ ] gunakan cara yang sama yang sudah diterapkan di beberapa modul lainnya, seperti modul pengurus dengan menggunakan view global tanda tangan
`<?php $this->load->view('global/blok_ttd_pamong.php', ['total_col' => 13, 'spasi_kiri' => 3, 'spasi_tengah' => 6]); ?>`

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2767
