### ISSUE TITLE
Bug/error: eror 404 ketika klik nama program pada menu bantuan

### ISSUE THREAD

**Issue by mah-mudi** [OpenSID/OpenSID#7013]
### Jelaskan error yg dialami

eror 404 ketika klik nama program pada menu bantuan

### Cara untuk mereplikasi errornya

1. Bantuan
2. klik nama program BPNT, BLSM, PKH, Bedah Rumah, JAMKESMAS

### Hasil yg diharapkan

terjadi eror 404

### Tangkapan layar dan log error

ketika klik nama program
<img width="740" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57661283/025fa2db-da9f-4276-a6f3-a4a3ce74424c">

muncul eror 404
<img width="792" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57661283/ef1597c3-0afa-4d00-b05f-6347ba5836b1">

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

23.08.01

### Tema Yang Digunakan

natra

### Informasi tambahan

beta.opendesa.id

**Comment by andifahruddinakas** [comment]
Kasusnya sama dengan issue https://github.com/OpenSID/OpenSID/issues/7001, namun dengan tambah link yang digunakan berbeda.

SOLUSI :
- [ ] Hapus link detail yang ada pada naa program bantuan.
- [ ] Gunakan link detail_clear pada tombol rincian agar session cari, filter tidak ikut.

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2782
