### ISSUE TITLE
Bug/error: artikel berjalan bermasalah

### ISSUE THREAD

**Issue by WAHYUDIK** [OpenSID/OpenSID#7014]
### Jelaskan error yg dialami

bingung cara jelasinnya. hehehheh

https://github.com/OpenSID/OpenSID/assets/31026980/7fef433e-fbc2-4593-b368-4e9b990f7a76

![image](https://github.com/OpenSID/OpenSID/assets/31026980/41437e9c-e6af-4904-ba40-98d7b44d510b)

### Cara untuk mereplikasi errornya

video dan gambar diatas

### Hasil yg diharapkan

untuk kolom judul tauan seharusnya tidak menjadi wajib di isi

### Tangkapan layar dan log error

video dan gambar diatas

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

beta.opendesa

**Comment by andifahruddinakas** [comment]
SOLUSI : 
- [ ] tambahkan pengecekan sbb: 
1. jika tautan ada, maka judul tautan di tampilkan judul tautan wajib isi
2. jika tautan tidak ada, maka judul tautan di hilangkan dan tidak wajib isi.

**Comment by yogiperdana** [comment]
Tautan itu maksudnya tautan ke artikel mas @andifahruddinakas? Jadi jika tautan ke artikel diisi maka judul tautan tampil. Jika tidak diisi maka display none. Apakah maksudnya seperti itu mas

**Comment by andifahruddinakas** [comment]
> Tautan itu maksudnya tautan ke artikel mas @andifahruddinakas? Jadi jika tautan ke artikel diisi maka judul tautan tampil. Jika tidak diisi maka display none. Apakah maksudnya seperti itu mas

ya

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2763
