### ISSUE TITLE
Bug/error: Keterangan yang tampil di tambah anggota kelompok baru tidak konsisten

### ISSUE THREAD

**Issue by WAHYUDIK** [OpenSID/OpenSID#7015]
### Jelaskan error yg dialami

jika menambahkan anggota kelompok baru baik menggunakan fitur tambah satu-satu atau dengan banyak anggota, ketika kursor diarahkan ke tambah. keterangannya muncul tidak konsisten

### Cara untuk mereplikasi errornya

1. masuk ke kelompok
2. tambahkan anggota kelompok
3. arahkan kursor ke toolkit tambahkan satu anggota kelompok/tambahkan banyak anggota kelompok
4. cek tulisan yang tampil

### Hasil yg diharapkan

kalimat yang tampil sama

### Tangkapan layar dan log error

![2023-08-07_23h17_07](https://github.com/OpenSID/OpenSID/assets/31026980/ba548ec9-e7bc-4c4a-b15c-2869e89619a7)
![2023-08-08_00h04_10](https://github.com/OpenSID/OpenSID/assets/31026980/f90b342e-0777-488a-b6e5-17bac5fe7d4a)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

beta.opendesa

**Comment by andifahruddinakas** [comment]
SOLUSI : 
- [ ] Samakan title yang tampil saat kursor didekatkan dengan yang tampil di tombol.

**Comment by yogiperdana** [comment]
> SOLUSI :
> 
> * [ ]  Samakan title yang tampil saat kursor didekatkan dengan yang tampil di tombol.

Jadi tulisannya dibuat jadi apa mas?

**Comment by andifahruddinakas** [comment]
> > SOLUSI :
> > 
> > * [ ]   Samakan title yang tampil saat kursor didekatkan dengan yang tampil di tombol.
> 
> Jadi tulisannya dibuat jadi apa mas?

Sesuai judul yang tertulis di masing2 tombol saja.

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2760
