### ISSUE TITLE
Bug/error: Kesalahan penulisan di catatan rilis

### ISSUE THREAD

**Issue by WAHYUDIK** [OpenSID/OpenSID#7016]
### Jelaskan error yg dialami

ada kesahalan penulisan di catatan rilis, dibagian perbaikan BUG

### Cara untuk mereplikasi errornya

cek tulisan di catatan rilis

### Hasil yg diharapkan

mengurangi typo

### Tangkapan layar dan log error

![2023-08-07_23h20_42](https://github.com/OpenSID/OpenSID/assets/31026980/ee464b8e-f59b-4eaf-b29b-5e80420f273e)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

beta.opendesa

**Comment by andifahruddinakas** [comment]
pak @WAHYUDIK, terima kasih sudah melaporkan. Untuk catatan rilis akan dicek kembali sebelum melakukan rilis.
