### ISSUE TITLE
Bug/error: Notifikasi Kosong saat buat key

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#7017]
### Jelaskan error yg dialami

![Screenshot_20230808_221111_Chrome](https://github.com/OpenSID/OpenSID/assets/46939846/7fe25ac1-297e-450c-a955-166568918eed)

### Cara untuk mereplikasi errornya

Menu OpenDK, Sinkronisasi

Tap Buat Key

Langsung klik Buat Key. muncul popup kosong hanya tombol Ok

### Hasil yg diharapkan

Beri notifikasi yang sesuai. gambar di atas terjadi saat kolom tidak atau belum diisi.

### Tangkapan layar dan log error

di atas

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Beta

**Comment by ariandii** [comment]
![Screenshot_20230808_221410_Chrome](https://github.com/OpenSID/OpenSID/assets/46939846/d832e5f3-179b-45bb-a874-172d4c86755d)

juga terjadi saat kolom sudah diisi. notif kosong.

**Comment by andifahruddinakas** [comment]
SOLUSI : 
- [ ] hanya tampilkan tombol buat key jika api, user dan pass terisi. Karena  api, user dan pass tidak wajib isi (bisa dikosongkan)

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2802
