### ISSUE TITLE
Bug/error: Notif Data gagal disimpan saat verifikasi email muncul di menu lain

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#7018]
### Jelaskan error yg dialami

gambar 1
![Screenshot_20230808_221644_Chrome](https://github.com/OpenSID/OpenSID/assets/46939846/797fb073-93ca-47ec-a93e-9eedb0cb33b7)

gambar 2
![Screenshot_20230808_221530_Chrome](https://github.com/OpenSID/OpenSID/assets/46939846/ff77743e-b29f-4eae-b58d-582fe2f5175f)

### Cara untuk mereplikasi errornya

buka profilmelalui pojol kanan atas.

klik verifikasi email. tidak ada notif apapun. (gambar 1)

lalu iseng buka menu lain, dalam hal ini tes menu lembaga.
maka baru muncul notif gagal disimpan tidak berhasil mengirim verifikasi email (gambar 2) 

### Hasil yg diharapkan

agar sesuai alur fungsinya

### Tangkapan layar dan log error

di atas

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Beta

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2800
