### ISSUE TITLE
Bug/error: Masalah tombol Headline di Artikel

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#7019]
### Jelaskan error yg dialami

gambar 1
<img width="960" alt="image" src="https://github.com/OpenSID/OpenSID/assets/46939846/2064099d-3a1f-42d2-8c5e-9894462c85cf">

gambar 2
<img width="424" alt="image" src="https://github.com/OpenSID/OpenSID/assets/46939846/23327d60-ec8a-46d1-b272-99402bb4fe6c">

gambar 3
<img width="644" alt="image" src="https://github.com/OpenSID/OpenSID/assets/46939846/9a581c06-fb99-4f75-a9e0-eebfccb610b3">

### Cara untuk mereplikasi errornya

buat 1 atau beberapa artikel masukkan ke slide (gambar 1)

tekan bintang untuk salah 1 artikel jadikan headline (gambar 2)

hasilnya semua artikel yg masuk slider jadi keluar (gambar 3)

### Hasil yg diharapkan

normal sebagaimana mestinya, eksekusi headline tidak mempengaruhi slider pada artikel lain.
(bisa tes di versi umum).

### Tangkapan layar dan log error

di atas

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Beta

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2785
