### ISSUE TITLE
Bug/error: Tombol Gembok pada Daftar Album Tidak Berfungsi

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#7020]
### Jelaskan error yg dialami

<img width="630" alt="image" src="https://github.com/OpenSID/OpenSID/assets/46939846/2a4eff9a-99c5-41b0-8db3-78d154d0be2f">

### Cara untuk mereplikasi errornya

seperti gambar di atas,
masuk menu Admin Web -> Galeri

Pilih salah satu album dan klik Tampilkan di Slider.

Kemudian coba klik tombol Gembok (Nonaktifkan Album) pada Album yang telah ditampilkan di Slider tersebut, maka notifikasi sukses, namun gembok tetap terbuka.

### Hasil yg diharapkan

normal sebagaimana mestinya.

### Tangkapan layar dan log error

di atas

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Beta

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2784
