### ISSUE TITLE
Bug/error: Space karakter Isian pada Nomor SK Pengangkatan dengan Nomor SK Jabatan, tidak sama

### ISSUE THREAD

**Issue by mah-mudi** [OpenSID/OpenSID#7022]
### Jelaskan error yg dialami

Space karakter Isian pada Nomor SK Pengangkatan dengan Nomor SK Jabatan, tidak sama

### Cara untuk mereplikasi errornya

1. lembaga desa
2. edit data ketua RT (misal)
3. masukkan nomor SK Jabatan
4. masukkan nomor SK Pengangkatan

### Hasil yg diharapkan

Space karakter Isian pada Nomor SK Pengangkatan dengan Nomor SK Jabatan, sama

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/57661283/e9ca9c6b-be2e-45d5-bb1c-9f28735e63cc)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

23.08.01

### Tema Yang Digunakan

natra

### Informasi tambahan

beta.opendesa.id

**Comment by andifahruddinakas** [comment]
Duplicate issue https://github.com/OpenSID/OpenSID/issues/7023
