### ISSUE TITLE
Bug/error: Rubah redaksi SK dengan Keputusan Kepala Desa (Kepkades) agar sesuai Permendagri 111 Tahun 2014 dan Space karakter Isian pada Nomor SK Pengangkatan dengan Nomor SK Jabatan, tidak sama

### ISSUE THREAD

**Issue by mah-mudi** [OpenSID/OpenSID#7023]
### Jelaskan error yg dialami

Redaksi masih menggunakan SK, harusnya beredaksi Keputusan Kepala Desa (Kepkades) untuk menyesuaikan Permendagri 111 Tahun 2014.

Karena redaksi Surat Keputusan (SK) Kepala Desa kurang tepat, karena yang benar adalah Keputusan Kepala Desa (Kepkades)

### Cara untuk mereplikasi errornya

1. lembaga desa
2. edit data ketua RT (misal)
3. masukkan nomor SK Jabatan
4. masukkan nomor SK Pengangkatan

### Hasil yg diharapkan

1. redaksi nomor SK Jabatan dirubah menjadi nomor Keputusan Jabatan
2. redaksi nomor SK Pengangkatan dirubah menjadi nomor Keputusan Pengangkatan
3. Space karakter Isian pada Nomor SK Pengangkatan dengan Nomor SK Jabatan, sama

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/57661283/377faf7f-52ea-403a-9097-42afcf7cad75)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

23.08.01

### Tema Yang Digunakan

natra

### Informasi tambahan

beta.opendesa.id

**Comment by andifahruddinakas** [comment]
silahkan lengkapi issue ini dengan tambahan dari https://github.com/OpenSID/OpenSID/issues/7022

karena pada bagian yang sama.

**Comment by mah-mudi** [comment]
@andifahruddinakas sudah
