### ISSUE TITLE
Bug/error: Nama Lembaga Desa tidak lurus pada saat cetak laporan lembaga

### ISSUE THREAD

**Issue by mah-mudi** [OpenSID/OpenSID#7024]
### Jelaskan error yg dialami

Nama Lembaga Desa tidak lurus pada saat cetak laporan lembaga

### Cara untuk mereplikasi errornya

1. lembaga desa
2. cetak data lembaga

### Hasil yg diharapkan

Nama Lembaga Desa lurus pada saat cetak laporan lembaga

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/57661283/a2a2b9ab-78f1-4092-915d-7c2b1bf3f568)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

23.08.01

### Tema Yang Digunakan

natra

### Informasi tambahan

beta.opendesa.id

**Comment by andifahruddinakas** [comment]
https://github.com/OpenSID/OpenSID/issues/4415#issuecomment-914971954

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2816
