### ISSUE TITLE
Bug/error: Peta menggunakan Api Mapbox menjadi blank hitam ketika update 23.08.0.1

### ISSUE THREAD

**Issue by mah-mudi** [OpenSID/OpenSID#7025]
### Jelaskan error yg dialami

Peta menggunakan Api Mapbox menjadi balnk hitam ketika update 23.08.0.1

### Cara untuk mereplikasi errornya

1. peta
2. setting api mapbox

### Hasil yg diharapkan

peta menampilkan peta sebagaimana mestinya

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/57661283/370e6490-7523-41b5-a20d-790da79e6b72)

![eror peta](https://github.com/OpenSID/OpenSID/assets/57661283/6792b93e-05fd-4b14-9125-6fcc83ac4f0b)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

23.08.0.1

### Tema Yang Digunakan

silir

### Informasi tambahan

beta.opendesa.id

**Comment by ariandii** [comment]
<img width="960" alt="image" src="https://github.com/OpenSID/OpenSID/assets/46939846/232551e2-d8de-4663-86e6-a46823e5276d">

<img width="960" alt="image" src="https://github.com/OpenSID/OpenSID/assets/46939846/460e19d3-e22e-4f3c-8b4f-faed0cc42cde">
