### ISSUE TITLE
Bug/error: Status Perkawinan Penduduk kurang update?

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#7026]
### Jelaskan error yg dialami

surat blanko F1.01 biodata penduduk menampilkan kode yang kurang tepat

### Cara untuk mereplikasi errornya

cetak surat biodata penduduk > perhatikan kolom kode isian status perkawinan

### Hasil yg diharapkan

sesuai dengan tatacara pengisian blanko

### Tangkapan layar dan log error

![asdadda](https://github.com/OpenSID/OpenSID/assets/35319600/a0be797e-ac7d-4836-a350-47f39a413a2d)
![sadadwa](https://github.com/OpenSID/OpenSID/assets/35319600/52c7405b-93df-4413-833b-0db799c4cb8e)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

web berputar

**Comment by andifahruddinakas** [comment]
Pada OpenSID, kode isian berbeda dengan yang ada di cara pengisian yg ada di lampiran. Adapun solusi sementara yg bisa digunakan yakni, membandingkan dan konversi data dari database sesuai format penulisan yg ada di lampiran tsb.

**Comment by andifahruddinakas** [comment]
Saat ini di belum ada kondisi untuk menentukan AB-Cerai Hidup Tercatat dan Cerai Hidup Belum Tercatat, untuk secara umum Cerai Hidup dinyatakan sebagai AB-Cerai Hidup Tercatat dan Cerai Hidup Belum Tercatat.

akan dibuatkan issue lain untuk menambahkan status tsb.

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2791

**Comment by balongbesuk** [comment]
AB-Cerai hidup tercatat itu kemungkinan salah ketik/cetak mas karna di KK penerbitan baru yang ditulis tanpa AB yaitu cerai hidup tercatat

**Comment by balongbesuk** [comment]
penangannya sama seperti status perkawin dulu,
