### ISSUE TITLE
Bug/error: masalah pada judul artikel yang mengandung tanda petik (')

### ISSUE THREAD

**Issue by Akmal197** [OpenSID/OpenSID#7029]
### Jelaskan error yg dialami

Terjadi masalah ketika membuat artikel yang mengandung tanda petik ('), berubah menjadi &#039;

### Cara untuk mereplikasi errornya

1. Pergi ke Halaman Admin Web
2. klik menu artikel
3. buat artikel yang mengandung tanda petik, misalnya Taman Pendidikan Qur'an, maka kata Qur'an berubah menjadi Qur&#039;an

### Hasil yg diharapkan

normal seperti biasanya

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/76812689/05a1bc7e-752e-4993-bf79-2059acd4c696)
![image](https://github.com/OpenSID/OpenSID/assets/76812689/a8690b1c-0682-413d-98bc-0962eddd8f27)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

23.08.0.1

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2805
