### ISSUE TITLE
Bug/error: Klik angka pada tabel kelas Sosial dialihkan ke periksa.

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#7030]
### Jelaskan error yg dialami

![IMG_20230810_214451_252](https://github.com/OpenSID/OpenSID/assets/46939846/4ffa9bfd-e995-4b22-836a-55e4ce564ba6)

### Cara untuk mereplikasi errornya

masuk menu statistik kelas sosial. lalu klik angka pada tabel.

maka dialihkan ke periksa.

### Hasil yg diharapkan

normal seperti seharusnya.

### Tangkapan layar dan log error

di atas

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

beta

**Comment by andifahruddinakas** [comment]
Dari tabel yang ada tidak ada tabel `tweb_keluarga_kelas`, yang ada hanya `tweb_keluarga_sejahtera`.

SOLUSI : 
- [ ] sesuaikan dengan nama tabel yang ada.

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2789
