### ISSUE TITLE
Gunakan slug pada halaman web data statistik 

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#7031]
### Jelaskan error yg dialami

dalam issue ini membuat link https://www.nataibaru.desa.id/first/tampilkan/6 dapat diakses langsung.

hanya dengan menebak angka di belakang.

termasuk jika hanya akses https://www.nataibaru.desa.id/first/tampilkan
maka akan error 500.

### Cara untuk mereplikasi errornya

buka langsung URL tersebut

### Hasil yg diharapkan

sebaiknya dibuat unik/acak, agar URL tidak mudah ditebak.

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Beta

**Comment by andifahruddinakas** [comment]
Dulu ada issuenya untuk membuat url untuk data statistik menggunakan slug, namun walaupun diubaha menjadi slug tetap akan biisa ditebak walau tak semudah jika menggunakan angka saja karena sifatnya statis. Sama halnya dengan slug pada halaman statis lainnya.

Issue https://github.com/OpenSID/OpenSID/issues/2784

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/OpenSID/pull/7140
