### ISSUE TITLE
Bug/error: Data suplemen sasaran keluarga

### ISSUE THREAD

**Issue by afri18** [OpenSID/OpenSID#7032]
### Jelaskan error yg dialami

Saat menambahkan peserta di sasaran Keluarga pada data Suplemen tidak tampil setelah data di pilih

### Cara untuk mereplikasi errornya

harusnya data tampil agar bisa d simpan

### Hasil yg diharapkan

Harusnya data tampil dan dapat di simpan

### Tangkapan layar dan log error

saat data di pilih
![image](https://github.com/OpenSID/OpenSID/assets/6611881/b631cf7b-03dc-41dc-a5a3-f3bbc5ef6904)

setelah dipilih tidak tampil
![image](https://github.com/OpenSID/OpenSID/assets/6611881/042c4d40-2982-4653-9760-236dd080cf8e)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2308.0.1 dan di beta

### Tema Yang Digunakan

https://beta.opendesa.id/

### Informasi tambahan

informasi dari utay

**Comment by andifahruddinakas** [comment]
Terkait perubahan PR https://github.com/OpenSID/OpenSID/issues/6599

SOLUSI : 
- [x] bedakan API daftar peserta suplemen berdasarkan sasarannya, contoh bisa dilihat pada modul bantuan.

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2790
