### ISSUE TITLE
Bug/error: NAMA DESA TIDAK SESUAI KEPUTUSAN MENTERI DALAM NEGERI NOMOR 146.1-4717 TAHUN 2020

### ISSUE THREAD

**Issue by igenk** [OpenSID/OpenSID#7037]
### Jelaskan error yg dialami

nama desa di open SID tidak sesuai KEPUTUSAN MENTERI DALAM NEGERI NOMOR 146.1-4717 TAHUN 2020
![image](https://github.com/OpenSID/OpenSID/assets/142193789/41c39453-67b0-4c2c-a0d9-ee64b493308d)

### Cara untuk mereplikasi errornya

info desa - identitas desa

### Hasil yg diharapkan

nama desa menjadi MANYAR SIDOMUKTI

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/142193789/19a04d30-7be1-4372-92f6-4b0848f55c04)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2308.0.1-premium

### Tema Yang Digunakan

silir

**Comment by andifahruddinakas** [comment]
https://forum.opendesa.id/d/296-nama-desa-tidak-sesuai-tidak-terdaftar
