### ISSUE TITLE
tema hadakewa hanya header yang muncul

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#704]
untuk tema hadakewa hanya sepotong yng uncul di online sedangkan di offline berjalan lancar
![screenshot 2017-11-06 20 12 15](https://user-images.githubusercontent.com/25834335/32440714-528155f0-c32f-11e7-9cba-76ac7264e51b.png)

kalau dioflline
![screenshot 2017-11-06 20 16 27](https://user-images.githubusercontent.com/25834335/32440747-771516b8-c32f-11e7-9da8-25c6d01f74ae.png)

**Comment by MUHAMMADRANGSEL** [comment]
di sid.bangundesa.info berjalan lancar

**Comment by eddieridwan** [comment]
@MUHAMMADRANGSEL untuk dilacak perlu contoh website dengan masalah ini. 
@metalab25 : apakah anda dapat membantu melacak masalah ini?

**Comment by bzy39** [comment]
errornya.
`Fatal error: Uncaught Error: Using $this when not in object context in E:\VirtualSite\domain\desa.test\public\donjo-app\core\MY_Controller.php:117 Stack trace: #0 E:\VirtualSite\domain\desa.test\public\themes\hadakewa\template.php(7): Web_Controller::fallback_default('hadakewa', '/partials/conte...') #1 E:\VirtualSite\domain\desa.test\public\system\core\Loader.php(834): include('E:\\VirtualSite\\...') #2 E:\VirtualSite\domain\desa.test\public\system\core\Loader.php(420): CI_Loader->_ci_load(Array) #3 E:\VirtualSite\domain\desa.test\public\donjo-app\controllers\first.php(84): CI_Loader->view('../../themes/ha...', Array) #4 E:\VirtualSite\domain\desa.test\public\system\core\CodeIgniter.php(360): First->index() #5 E:\VirtualSite\domain\desa.test\public\index.php(208): require_once('E:\\VirtualSite\\...') #6 {main} thrown in E:\VirtualSite\domain\desa.test\public\donjo-app\core\MY_Controller.php on line 117`

**Comment by eddieridwan** [comment]
Masalah online karena menggunakan PHP 7. Pull request dari @batudaa berusaha memperbaiki. Silakan dicoba.

Masalah gambar header tidak memenuhi header (di offline) kemungkinan disebabkan css. Coba salin kembali desa/css/hadakewa dari desa-contoh/css/hadakewa.

Kami tutup issue ini. Kalau masih bermasalah silakan buka kembali.
