### ISSUE TITLE
Permintaan fitur: Sediakan menu on/off isian nik/pilih nik  pada surat tinymce

### ISSUE THREAD

**Issue by muhtar-coder** [OpenSID/OpenSID#7040]
### Apa kekurangan yg ingin diatasi?

Surat tinymce belum suport pembuatan surat yg tidak membutuhkan nik penduduk

### Jelaskan solusi yg diinginkan

di sediakan opsi pilihan aktifkan/hilangkan inputan NIK pada surat

![image](https://github.com/OpenSID/OpenSID/assets/55665526/af04f0b9-3571-4d31-971f-d182f2e2af20)

![image](https://github.com/OpenSID/OpenSID/assets/55665526/f38d75ce-8b0b-484e-9a45-bb045a1e472a)

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

premium

### Informasi tambahan

-

**Comment by firmanfansuriakmal** [comment]
Surat saat ini hanya bisa disediakan untuk warga. Ketika ingin membuat surat kebutuhan dinas masih belum bisa dikarenakan sistem masih mengunci terhadap penduduk atau non penduduk. Semoga kedepan bisa membuat surat kebutuhan dinas desa seperti surat pengantar pengiriman laporan pertanggungjawaban ke kabupaten atau surat undangan rapat melalui sistem dan surat-surat lainnya

**Comment by andifahruddinakas** [comment]
Hal ini tidak bisa diterapkan, karena setiap pengajuah surat memelukan nama dan nik dari pemohon yang dimana dicatat pada arsip layanan.
