### ISSUE TITLE
Permintaan fitur: Tampilkan layout halaman kertas seperti ms.word

### ISSUE THREAD

**Issue by muhtar-coder** [OpenSID/OpenSID#7041]
### Apa kekurangan yg ingin diatasi?

Surat tinymce ketika pembuatan jenis surat yang outputnya lebih dari satu lembar, agak susah mengaturnya kebagian bawah karena termuat dalam satu halaman di pengaturan surat.

### Jelaskan solusi yg diinginkan

dapat terlihat jelas halaman kertas atau batas kertas ketika melebihi satu lembar kertas surat. sehingga memudahkan pembuatan surat yg lebih dari satu lembar dan memudahkan pencetakan karena tidak repot edit sebelum cetak

![image](https://github.com/OpenSID/OpenSID/assets/55665526/2c05d25f-9277-4d29-97a1-ad10b1f8b423)

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

premium

### Informasi tambahan

-

**Comment by luxmant354** [comment]
sip mantab, sangat diperlukan ini 👍

**Comment by andifahruddinakas** [comment]
belum support https://github.com/tinymce/tinymce/issues/5090

**Comment by andifahruddinakas** [comment]
Commit https://github.com/OpenSID/premium/commit/3fd012bcf1a15947792a49d7c7169e8b9448855e menyesuaikan tampilan saja. Tidak mengubah batasan halaman baru (page break), sehingga issue ini masih diperlukan.

**Comment by andifahruddinakas** [comment]
mas @pandigresik, coba dicek ini. Siapa tau ketemu solusinya.

**Comment by vickyrolanda** [comment]
> mas @pandigresik, coba dicek ini. Siapa tau ketemu solusinya.

ini bisa di atasi dengan add tinymce baru untuk halaman baru, jadi 1 TinyMCE bisa mewakili 1 halaman. 
tinggal dibuat visual seperti halaman pertama dan halaman ke2 dengan slide navigation. 

mungkin bisa seperti itu mas

**Comment by pandigresik** [comment]
> > mas @pandigresik, coba dicek ini. Siapa tau ketemu solusinya.
> 
> ini bisa di atasi dengan add tinymce baru untuk halaman baru, jadi 1 TinyMCE bisa mewakili 1 halaman. tinggal dibuat visual seperti halaman pertama dan halaman ke2 dengan slide navigation.
> 
> mungkin bisa seperti itu mas

Artinya ketika tidak menekan **tombol tambah** ( tombol untuk membuat tinymce baru )  halaman misalnya akan tetap dianggap halaman1 padahal kalau di ms word ketika mengetik panjang otomatis akan pindah ke halaman 2 ketika sudah tidak cukup di halaman 1

**Comment by pandigresik** [comment]
![image](https://github.com/OpenSID/OpenSID/assets/1853475/a0051dc8-c6e0-4c22-bab4-f491f4be6cb2)

Hanya secara tampilan seperti kertas ketika insert page-break di tinyMCE
```
.mce-pagebreak {    
    border:none;
    cursor: default;
    display: block;
    height: 25px;
    margin-top: 15px;
    page-break-before: always;
    width: 120%;
    margin-left: -9.6%;
    background-color: #ECEEF4
}
```

**Comment by andifahruddinakas** [comment]
> ![image](https://user-images.githubusercontent.com/1853475/277610936-a0051dc8-c6e0-4c22-bab4-f491f4be6cb2.png)
> 
> Hanya secara tampilan seperti kertas ketika insert page-break di tinyMCE
> 
> ```
> .mce-pagebreak {    
>     border:none;
>     cursor: default;
>     display: block;
>     height: 25px;
>     margin-top: 15px;
>     page-break-before: always;
>     width: 120%;
>     margin-left: -9.6%;
>     background-color: #ECEEF4
> }
> ```

bisa seperti ini, untuk saat generate php tinggal di pecah saja. dan di generate pdfnya 1 persatu berdasarkan page break td. setelah semua selesai di conversi ke pdf, lanjut ke penggabungan hasil pdf tsb menjadi 1 pdf saja.

https://stackoverflow.com/questions/2117788/page-break-in-html2pdf
