### ISSUE TITLE
Permintaan fitur: Sediakan pilihan tampilkan header/kop surat untuk halaman utama atau halaman lain nya

### ISSUE THREAD

**Issue by muhtar-coder** [OpenSID/OpenSID#7042]
### Apa kekurangan yg ingin diatasi?

pengaturan tampilkan header/kop surat masih berlaku ke semua halaman kertas

### Jelaskan solusi yg diinginkan

di sediakan opsi pilihan tampilkan header/kop surat untuk lembar mana saja yang di butuhkan

![image](https://github.com/OpenSID/OpenSID/assets/55665526/e95a0361-e53c-4da8-9da4-b518fe273e40)

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

premium

### Informasi tambahan

-

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2871
