### ISSUE TITLE
Permintaan fitur: Sediakan Lampiran F-2.30

### ISSUE THREAD

**Issue by muhtar-coder** [OpenSID/OpenSID#7043]
### Apa kekurangan yg ingin diatasi?

Belum ada lampiran pdf F-2.30

[surat_ket_kematian.pdf](https://github.com/OpenSID/OpenSID/files/12337082/surat_ket_kematian.pdf)

![image](https://github.com/OpenSID/OpenSID/assets/55665526/efcb0e33-4ed3-495b-b91d-3145755633d1)

### Jelaskan solusi yg diinginkan

sediakan di lampiran surat

![image](https://github.com/OpenSID/OpenSID/assets/55665526/e1e1c3cc-2dbb-412b-8012-3af786f871ab)

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

premium

### Informasi tambahan

di haruskan oleh dukcapil

![image](https://github.com/OpenSID/OpenSID/assets/55665526/69eefba1-d909-4a75-aceb-da57c59bf01a)

**Comment by andifahruddinakas** [comment]
mas @habibie11, tambahkan kode isian untuk
**Peristwa Mati**
- [x] anak ke
- [x] jumlah saudara (filter berdasarkan status anak pada keluarga tsb)
- [x] bukti kematian (akta kematian)

**Peristiwa Lahir**
- [x]  jumlah saudara (filter berdasarkan status anak pada keluarga tsb)

**Penduduk**
- [x] anak ke
- [x] jumlah saudara (filter berdasarkan status anak pada keluarga tsb)
