### ISSUE TITLE
Bug/error: Gambar Pelaporan tidak muncul

### ISSUE THREAD

**Issue by mah-mudi** [OpenSID/OpenSID#7044]
### Jelaskan error yg dialami

Tidak bisa melakukan lebih dari 1 Pengaduan dalam 1 hari dan Gambar Pelaporan tidak muncul

### Cara untuk mereplikasi errornya

1. isi pengaduan , sukses (laporannya masuk ke akun admin)
2. isi pengaduan yg kedua pada hari dan tgl yg sama, sukses (laporannya tdk masuk ke akun admin)

### Hasil yg diharapkan

Bisa melakukan lebih dari 1 Pengaduan dalam 1 hari dan Gambar pelaporan yg diupload dapat muncul

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/57661283/908ec04a-e144-45b6-b212-4cbbe0b08dfa)

![image](https://github.com/OpenSID/OpenSID/assets/57661283/043ab361-c1ab-42ac-9ed9-a0fafad06c87)

![image](https://github.com/OpenSID/OpenSID/assets/57661283/30ea8687-010f-42a8-a54d-dda0506787ec)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

23.08.01

### Tema Yang Digunakan

DeNava

### Informasi tambahan

beta.opendesa.id

**Comment by andifahruddinakas** [comment]
Untuk batasan pelaporan dibatasi 1 kali pada 1 IP Address yang sama, untuk pembatasan itu jika mau diubah bisa melalui permintaan fitur.

**Comment by andifahruddinakas** [comment]
sy coba tidak ada masalah di lakukan test yg sama di https://beta.opendesa.id/

<img width="452" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/608b1377-2f3e-4a86-b836-054c5a010940">
