### ISSUE TITLE
mohon penambahan dan perbaikan cetak KK

### ISSUE THREAD

**Issue by ipaysx** [OpenSID/OpenSID#705]
mohon penambahan dan perbaikan di cetak KK.
1. Pangkat dan NIP Camat
2. No registrasi
3. Nama dan Nip Petugas Registrasi
4. Nama Pemohon default Nama KK
5. cetak otomatis landscape, untuk sementara masih potret.

sedikit sample.

![screenshot_23](https://user-images.githubusercontent.com/12766544/32532137-beb8e6d8-c47a-11e7-8ed5-43518969147a.jpg)

**Comment by eddieridwan** [comment]
@ipaysx harap perhatikan, ini adalah 'salinan' KK, yang kalau tidak salah hanya untuk informasi saja. Batas2 penggunaannya selama ini belum ditentukan secara pasti.

Mungkin teman2 Pokja dapat memberi masukan. Kami akan tanyakan di https://opensid.slack.com/messages/C6XQEDF3Q/details/. Silakan gabung di situ, kalau ingin ikut membahas.

**Comment by eddieridwan** [comment]
@ipaysx : harap lampirkan contoh tulisan yang akan ditampilkan di masing2 kotak baru yg diinginkan. Bukan keterangannya, tapi contoh seperti apa hasil akhir yang diinginkan.

**Comment by eddieridwan** [comment]
Nomor registrasi, nama dan NIP petugas registrasi tidak disimpan di database SID -- dan tidak diketahui pada saat mengunduh salinan KK. Jadi yang bisa ditampilkan hanya kolom isiannya saja.

Page layout sudah landscape.

**Comment by eddieridwan** [comment]
Sdh dicommit ke master.

**Comment by ipaysx** [comment]
[CONTOH KK yang saya inginkan.zip](https://github.com/OpenSID/OpenSID/files/1537838/CONTOH.KK.yang.saya.inginkan.zip)

ini contoh akhir form kk yang kami gunakan di kab probolinggo. trims
