### ISSUE TITLE
Bug/error: status perkawinan pada saat input penduduk lahir/tambah anggota keluarga lahir statusnya perkawinannya berubah otomatis dan diharuskan memilih kembali

### ISSUE THREAD

**Issue by WAHYUDIK** [OpenSID/OpenSID#7052]
### Jelaskan error yg dialami

ketika menambahkan penduduk lahir di menu tambah penduduk/tambah anggota keluarga lahir status perkawinannya berubah otomatis menjadi pilih status perkawinan ketika kita merubah/memilih status hubungan dalam keluarga menjadi anak. 

### Cara untuk mereplikasi errornya

1. masuk ke menu kependudukan
2. tambah penduduk lahir/tambah anggota keluarga lahir
3. ubah status hubungan keluarga menjadi anak
4. cek status perkawinan

### Hasil yg diharapkan

ketika menambah penduduk lahir/anggota keluarga lahir kemudian ubah status hubungan dalam keluarga menjadi anak, seharusnya status perkawinan tetap otomatis menjadi belum kawin

### Tangkapan layar dan log error

[2023-08-16_14h05_10.webm](https://github.com/OpenSID/OpenSID/assets/31026980/7973834f-46f6-4f38-9ea9-d9073dd90815)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

beta.opendesa

**Comment by nyomanjyotisa** [comment]
Issue ini sudah saya kerjakan pada PR berikut https://github.com/OpenSID/OpenSID/pull/7976

Regards,
I Nyoman Jyotisa

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melalui pr https://github.com/OpenSID/premium/pull/3997
