### ISSUE TITLE
Bug/error: jumlah anggota di Sub Menu Rumah Tangga tidak terhitung apabila kepala rumah tangganya berasal dari selain kepala keluarga

### ISSUE THREAD

**Issue by WAHYUDIK** [OpenSID/OpenSID#7054]
### Jelaskan error yg dialami

jumlah anggota tidak terhitung/terjumlah apabila menambah rumah tangga baru dimana yang menjadi kepala rumah tangganya berasal dari selain kepala keluarga, misal
menambahkan 1 rumah tangga dengan kepala rumah tangga berasal dari istri. 
![image](https://github.com/OpenSID/OpenSID/assets/31026980/e64a40e9-56f0-45a2-bf54-10723a480d88)
kemudian klik simpan,
![image](https://github.com/OpenSID/OpenSID/assets/31026980/b550a9db-0a6f-425f-ad9d-e425efdbec50)
jumlah yang terdata di kolom jumlah anggota hanya 1, sedangkan ketika di cek di menu keluarga yang bersangkutan berjumlah 3 anggota keluarga
![image](https://github.com/OpenSID/OpenSID/assets/31026980/b057c74b-56c4-4842-bdd3-ac376b246db7)

### Cara untuk mereplikasi errornya

tambah rumah tangga baru, pilih kepala rumah tangga berasal dari status hubungan dalam keluarga sebagai istri/anak
kemudian di simpan. cek di kolom jumlah anggota.

### Hasil yg diharapkan

jumlah anggota disesuaikan dengan jumlah anggota didalam keluarga yang bersangkutan, meskipun yang menjadi kepala rumah tangga berasal dari selain kepala keluarga

### Tangkapan layar dan log error

sesuai gambar di atas

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

beta.opendesa

**Comment by andifahruddinakas** [comment]
pak @WAHYUDIK, ini bukan bug. Dari kalimat saja yang tertera adalah "Tambah Data Rumah Tangga Per Penduduk" bukan per keluarga.

Jika membutuhkan fungsi dimana jika menambahkan data keluarga dengan status "Kepala Keluarga" otomatis anggotanya ikut, bisa dibuatkan permmintaan fitur.
