### ISSUE TITLE
Bug/error: tombol batal ketika ubah data rumah tangga tidak berfungsi

### ISSUE THREAD

**Issue by WAHYUDIK** [OpenSID/OpenSID#7055]
### Jelaskan error yg dialami

ketika ubah data rumah tangga dan ingin mebatalkan ubahan, ternyata tombol batalnya tidak berfungsi sebagaimana mestinya

### Cara untuk mereplikasi errornya

1. masuk ke sub menu rumah tangga
2. klik ubah data rumah tangga yang sudah ada
3. kemudian klik tombol batal

### Hasil yg diharapkan

tombol batal berfungsi sebagaimana mestinya

### Tangkapan layar dan log error

![2023-08-16_16h25_15](https://github.com/OpenSID/OpenSID/assets/31026980/7d44f9f0-66a7-4250-9f51-9c123a5bcd76)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

beta.opendesa 

### Informasi tambahan

sebenarnya sudah ada tombol X di pojok kanan atas, bisa juga di hapus saja tombol batalnya

**Comment by ariandii** [comment]
ketik sembarang kolom jika ingin ubah, lalu klik batal. maka fungsinya akan ketahuan.

**Comment by ariandii** [comment]
duplicate

**Comment by andifahruddinakas** [comment]
Duplicate issue https://github.com/OpenSID/OpenSID/issues/6765
