### ISSUE TITLE
Bug/error: Visual TTE (bersyarat) tidak menjadi YA saat disimpan.

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#7056]
### Jelaskan error yg dialami

replikasi di bawah.

### Cara untuk mereplikasi errornya

1. pilih menu Pengaturan Surat -> klik Pengaturan di sisi atas
2. buka tab Pengaturan TTE
3. posisi Aktifkan Modul TTE misal TIDAK dan Visual TTE juga TIDAK (gambar 1)

1. ketika Aktifkan Modul TTE YA dan Visual TTE dipilih YA (gambar 2), maka setelah klik simpan hanya Aktifkan Modul TTE yang tersimpan. (gambar 3). diketahui saat buka Pengaturan TTE kembali.
2. ketika Aktifkan Modul TTE TIDAK dan Visual TTE dipilih YA, maka setelah klik simpan tidak akan berdampak apapun.

Visual TTE akan bisa dipilih YA pada pengaturan kedua kalinya saat Aktifkan Modul TTE sudah terpilih YA

### Hasil yg diharapkan

1. jika Visual TTE tergantung pada status Aktifkan Modul TTE, sebaiknya hilangkan tombol pilihan YA atau TIDAK pada Visual TTE ketika Pilihan Aktifkan Modul TTE adalah Tidak.
2. Ketika Pilihan Aktifkan Modul YA dan Visual TTE YA, harusnya ketika klik simpan akan YA keduanya. yang saat ini hanya 1 menjadi YA pada Aktifkan Modul TTE saja.

### Tangkapan layar dan log error

gambar 1:
<img width="960" alt="2023-08-16_22h31_51" src="https://github.com/OpenSID/OpenSID/assets/46939846/313c2093-71ee-4fa1-9c3d-e8bab4fadb1d">

gambar 2:
<img width="960" alt="2023-08-16_22h31_58" src="https://github.com/OpenSID/OpenSID/assets/46939846/fb1b3400-7e60-42e6-ad25-3566844f50ba">

gambar 3:
<img width="960" alt="2023-08-16_22h32_14" src="https://github.com/OpenSID/OpenSID/assets/46939846/c0066aec-5056-4123-bbf2-7e993bb277f6">

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Beta

### Informasi tambahan

Jika kurang jelas, bisa didemokan ke DC.

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2804
