### ISSUE TITLE
Bug/error: akses https://beta.opendesa.id/database/acak berantakan

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#7057]
### Jelaskan error yg dialami

ketika buka https://beta.opendesa.id/database/acak tampilannya berantakan

### Cara untuk mereplikasi errornya

akses langsung https://beta.opendesa.id/database/acak

### Hasil yg diharapkan

bisa lebih dirapikan sebagaimana tabel seharusnya

### Tangkapan layar dan log error

<img width="960" alt="2023-08-16_22h58_10" src="https://github.com/OpenSID/OpenSID/assets/46939846/1b0d3349-a907-406c-9197-7ce2346211cd">

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Beta

**Comment by andifahruddinakas** [comment]
pak @ariandii, untuk tampilan dari awal sudah seperti itu.

SOLUSI : 
- [ ] Gunakan datatables untuk menampilkan data yang diubah
- [x] Pastikan yang diubah data desa tsb (berdasarkan config_id)
- [x] hanya bisa diakses superadmin

**Comment by ariandii** [comment]
atau bisa beri tambahan pengamanan kode verifikasi seperti restore folder desa. agar nik acak tersebut tidak untuk dicoba yg langsung eksekusi setelah klik acak.

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2837
