### ISSUE TITLE
Bug/error: tersedia tombol Selengkapnya, namun saat diklik tidak ada hasil (video terlampir) 

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#7058]
### Jelaskan error yg dialami

gagal di akhir video. namun masih bisa akses URL Wilayah Administratif Dusun beserta Sub nya (walau tidak ada tombol menu).

https://github.com/OpenSID/OpenSID/assets/46939846/646a6d4d-8fb9-434e-b976-14d2bc1ac8ef

### Cara untuk mereplikasi errornya

video di atas

### Hasil yg diharapkan

sebagaimana seharusnya.

### Tangkapan layar dan log error

di atas.

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Beta

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2857

**Comment by andifahruddinakas** [comment]
Catatan : 
- Dalam perbaikan ini hanya mengatasi bisa akses wilayah administarsi melalui url. Namun pada video terlihat bisa akses hom_sid walau pada navigasi tidak tersedia.
