### ISSUE TITLE
Bug/error: Lampiran F2.01 Cetak Surat Keterangan Kelahiran TinyMCE 

### ISSUE THREAD

**Issue by Akmal197** [OpenSID/OpenSID#7059]
### Jelaskan error yg dialami

Ketika cetak surat ket kelahiran dengan lampiran F2.01 tidak melampirkan lampiran yang seharusnya, melainkan yang terlampir atau yg tercentang adalah F2.01 Kematian

### Cara untuk mereplikasi errornya

1. Halaman Cetak Surat
2. pilih Cetak Surat Ket Kelahiran TinyMCE
3. lalu simpan dan cetak

### Hasil yg diharapkan

menampilkan lampiran yang seharusnya, yakni F2.01 Kelahiran

### Tangkapan layar dan log error

![photo_2023-08-16_22-25-15](https://github.com/OpenSID/OpenSID/assets/76812689/4148be79-ea5b-401c-abe1-642c3ee2c933)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

23.08.0.2 Premium

### Tema Yang Digunakan

bawaan

**Comment by andifahruddinakas** [comment]
catatan rilis masuk di https://github.com/OpenSID/OpenSID/issues/6968
