### ISSUE TITLE
(PENTING) Bantuan Pembuatan Form surat Perubahan KK (F-1.16)

### ISSUE THREAD

**Issue by alwalij** [OpenSID/OpenSID#706]
![f-1 16](https://user-images.githubusercontent.com/8839646/32580695-10c5cefc-c519-11e7-8495-3ce935ef2475.PNG)
tolong agan" :dancing_men:

**Comment by Agankdptegar** [comment]
Sekalian Om sama Form Permohonan Pembuatan KTP nya...keduanya penting banget

**Comment by eddieridwan** [comment]
@alwalij masing2 issue digunakan untuk satu topik saja. Kalau ada usul lain perlu buat issue terpisah. Tapi cek dulu apakah sudah ada issue untuk usulan tsb. Khusus untuk usul Form Permohonan Pembuatan KTP sudah ada issue https://github.com/OpenSID/OpenSID/issues/264.

Silakan lihat pembahasan di issue itu. Terutama:
"@Deni efendi (FB) memberitahu bahwa berdasarkan Permendagri No 8 Tahun 2016, khususnya Pasal 5, permohonan KTP tidak lagi memerlukan pengisian F-1.21 maupun F-1.06."

Deni effendi adalah petugas Disdukcapil.

**Comment by alwalij** [comment]
ini bukan untuk perubahan ktp mas tapi KK di gresik masih pakek form ini (F.1.16) bukan form (F.1.06)

http://dispendukcapil.gresikkab.go.id/paket-akte-kelahiran-dan-kartu-keluarga/
![dasd](https://user-images.githubusercontent.com/8839646/32656218-7adf3988-c643-11e7-840d-66735177f5bc.PNG)

**Comment by alwalij** [comment]
peraturan baru mas nomor 32 tahun 2016

**Comment by alwalij** [comment]
![f-2 01](https://user-images.githubusercontent.com/8839646/32656290-c4797b26-c643-11e7-926b-17f7e186a810.PNG)
F1.16 sama F2,01

**Comment by eddieridwan** [comment]
Duplikat #216

**Comment by metalab25** [comment]
mohon kirimkan formulir dengan format rtf atau doc agar bisa saya buatkan

**Comment by alwalij** [comment]
[F-1.16.docx](https://github.com/OpenSID/OpenSID/files/1560990/F-1.16.docx)

**Comment by alwalij** [comment]
sekalian sama yang kelahiran dong mas mohon bantuan 
[F-2.01.docx](https://github.com/OpenSID/OpenSID/files/1561017/F-2.01.docx)
