### ISSUE TITLE
Bug/error: sitemap.xml kurang tag pembuka

### ISSUE THREAD

**Issue by totoprayogo1916** [OpenSID/OpenSID#7062]
### Jelaskan error yg dialami

sitemap tidak ada tag pembuka
kadang beberapa validator sitemap.xml menganggap ini salah

### Cara untuk mereplikasi errornya

cek file sitemap.xml

### Hasil yg diharapkan

file sitemap.xml sesuai format https://www.sitemaps.org/
dengan adanya tag
`<?xml version="1.0" encoding="UTF-8"?>`

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Rilis Umum & Premium

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/OpenSID/pull/7027 dan commit https://github.com/OpenSID/premium/commit/9da4556592b4ea5e4ccc5a1a2c42fb2ec87e75f6
