### ISSUE TITLE
Bug/error: Kesalahan pada "pengecualian" file pada Git

### ISSUE THREAD

**Issue by totoprayogo1916** [OpenSID/OpenSID#7063]
### Jelaskan error yg dialami

Beberapa file yang di-"ignore" agar tidak ter-commit ada yang salah (tidak tepat)

### Cara untuk mereplikasi errornya

jalankan `git rm --cached -r . -f` pada branch `dev` atau mana saja
akan muncul perubahan, 
yang **dihapus** adalah yang seharusnya diignore padahal itu dibutuhkan.

### Hasil yg diharapkan

Folder/file yang ada repo sesuai yang semestinya diabaikan atau tidak

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Rilis Umum & Premium

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui commit https://github.com/OpenSID/premium/commit/e787ff3963ab2beeae54870c29cd59c65bf4bd44 dan PR https://github.com/OpenSID/OpenSID/pull/7036
