### ISSUE TITLE
Bug/error: Keamanan direktori dari bot (crawl)

### ISSUE THREAD

**Issue by totoprayogo1916** [OpenSID/OpenSID#7064]
### Jelaskan error yg dialami

direktori `backup_inkremental` & `template-surat` dapat di-crawl oleh mesin pencari,
hasilnya bisa tampil dihalaman pencarian, semestinya itu tidak ada.

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

jangan biargan bot menjelajahi direktori `backup_inkremental` & `template-surat`

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Rilis Umum & Premium

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/OpenSID/pull/7035 dan commit https://github.com/OpenSID/premium/commit/40c8883e025cd877500fce5d3ce470d196bf317d
