### ISSUE TITLE
Permintaan fitur: 

### ISSUE THREAD

**Issue by fishtank94** [OpenSID/OpenSID#7065]
### Apa kekurangan yg ingin diatasi?

Tidak adanya slideshow di dalam artikel, sehingga tidak dapat menampilkan rangkaian gambar secara berurutan di dalam artikel. Kemudian dalam artikel belum bisa menampilkan isi file pdf, yang tujuannya agar isi file pdf dapat dibaca tanpa perlu didownload

### Jelaskan solusi yg diinginkan

Diberikan tombol untuk membuat slideshow saat membuat artikel. Ketika tombol membuat slideshow tersebut diklik, maka ada pop up untuk memasukkan gambar.
Untuk menampilkan pdf seperti gambar yang terattach
![menampilkan-dokumen-pdf-pada-halaman-html-235753140](https://github.com/OpenSID/OpenSID/assets/90022841/20d8d56c-a8db-42c2-ba6e-5e53a65e6998)

### Apakah ada alternatif lain

Untuk saat ini belum alternatif lain

### Untuk versi OpenSID mana

Rilis Umum v2309.0.0

**Comment by andifahruddinakas** [comment]
https://github.com/OpenSID/OpenSID/wiki/Menulis-Artikel#memasukkan-video-ke-artikel
