### ISSUE TITLE
Bug/error: error bug di maps lokasi dan kependudukan dan sekretaris

### ISSUE THREAD

**Issue by pullz21** [OpenSID/OpenSID#7066]
### Jelaskan error yg dialami

error di maps lokasi dan kependudukan dan sekretaris

### Cara untuk mereplikasi errornya

![Screenshot (206)](https://github.com/OpenSID/OpenSID/assets/142792261/d6adca89-5c84-4550-9838-c0199f27fe31)

### Hasil yg diharapkan

semoga segera di fixed

### Tangkapan layar dan log error

![Screenshot (206)](https://github.com/OpenSID/OpenSID/assets/142792261/402b0cc6-6e6c-4a7b-9823-04c4ac2c6aa8)

### Rilis Versi OpenSID

Rilis Umum

### Versi OpenSID

2308.0.0

**Comment by andifahruddinakas** [comment]
gunakana versi database apa dan berapa?
