### ISSUE TITLE
TinyMCE kekurangan dalam konversi surat penghasilan orang tua

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#7069]
### Jelaskan error yg dialami

Surat keterangan penghasilan orang tua versi TinyMCE tidak sepenuhnya menyediakan fitur versi RTF. Khususnya tidak menyediakan penghitungan total penghasilan ayah + ibu secara otomatis.

Kekurangan ini dianggap penting oleh pengguna, karena pengisian total secara manual dirasa menggangu dan bisa salah.

### Cara untuk mereplikasi errornya

1. Lihat form pengisian surat RTF, perhatikan tidak perlu mengisi total penghasilan. Surat yg dihasilkan otomatis menghitung total penghasilan
2. Lihat form pengisian surat TinyMCE, perhatikan harus mengisi total penghasilan. Surat yg dihasilkan menampilkan isian total penghasilan, yg bisa saja salah.

### Hasil yg diharapkan

Dibuatkan rumus penghitungan otomatis seperti surat keterangan penghasilan orang tua versi rtf sebagaimana contoh terlampir 
![photo_2023-08-15_20-07-53](https://github.com/OpenSID/OpenSID/assets/44687953/e25278af-4964-4c78-b2a6-b93010cc426c)

### Tangkapan layar dan log error

n/a

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v23.08-premium

**Comment by eddieridwan** [comment]
Di RTF, penghitungan total penghasilan = penghasilan ayah + penghasilan ibu dilakukan di `template-surat/surat_ket_penghasilan_orangtua/data_rtf_surat_ket_penghasilan_orangtua.php`

Solusi untuk dipertimbangkan di TinyMCE adalah menyediakan kode isian expresi aritmatika sederhana.

Andaikan:
1. `[penghasilan-ayah]`, kode isian penghasilan ayah, katakan diisi oleh pengguna dengan nilai 80
2. `[penghasilan-ibu]`, kode isian penghasilan ibu, katakan diisi oleh pengguna dengan nilai 90

Maka bisa sediakan kode isian `[penghasilan-ayah + penghasilan-ibu]` yg menghasilkan totalnya.

Implementasinya bisa sebagai berikut:

1. substitusi dengan kode isian operand yg diisi pengguna, menghasilkan string "80 + 90"
2. parse dan eksekusi sebagai expresi aritmatika, menghasilkan "170"

Untuk langkah (2) dapat menggunakan eval, seperti di https://www.codespeedy.com/execute-and-calculate-string-as-a-mathematical-equation-in-php/#google_vignette. Tapi penggunaan eval berbahaya, karena kode isian expresi di-input oleh pengguna, jadi berpotensi rentan.

Alternatif lain membuat parser sendiri, menggunakan regex dsbnya, tapi ini memerlukan banyak testing.

Yg mungkin paling praktis, menggunakan library/class seperti di MathExecutor di https://www.phpclasses.org/package/7972-PHP-Parse-and-evaluate-strings-with-math-expressions.html

Kode isian expresi aritmatika seperti di atas dapat digunakan tidak hanya untuk kebutuhan surat keterangan penghasilan orang tua, melainkan dapat juga digunakan untuk segala jenis surat yg berisi bilangan dan penghitungan terkait.

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/3017
