### ISSUE TITLE
Wilayah Administratif RT

### ISSUE THREAD

**Issue by Nanjungwangi** [OpenSID/OpenSID#707]
setelah selesai mengimpor database penduduk nama ketua RT kenapa sama?

![capture](https://user-images.githubusercontent.com/30613757/32642467-0f9002f2-c607-11e7-9c11-7eae0dcbad07.JPG)

dan ketika dilakukan perubahan data, nama ketua RT sebelumnya otomatis salah

![capture1](https://user-images.githubusercontent.com/30613757/32642557-a99e7f04-c607-11e7-9101-f3852ae342dc.JPG)

**Comment by MUHAMMADRANGSEL** [comment]
Mungkin database nya yg bermaslah silahkan inport ulang databasenya
