### ISSUE TITLE
Bug/error: Keterangan telegram

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#7070]
### Jelaskan error yg dialami

<img width="960" alt="image" src="https://github.com/OpenSID/OpenSID/assets/46939846/ad89cc90-2b92-45fd-92e2-eebd4acbeecf">

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Beta

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2827
