### ISSUE TITLE
Bug/error: Status IDM Tahun 2023 eror

### ISSUE THREAD

**Issue by mah-mudi** [OpenSID/OpenSID#7072]
### Jelaskan error yg dialami

Status IDM Tahun 2023 eror

### Cara untuk mereplikasi errornya

1. status desa
2. idm tahun 2023

### Hasil yg diharapkan

Status IDM Tahun 2023 dapat tampil sebagaimana mestinya

### Tangkapan layar dan log error

[screen-capture (1).webm](https://github.com/OpenSID/OpenSID/assets/57661283/be607489-96b2-4bd3-b9d6-33166709f6fd)

![image](https://github.com/OpenSID/OpenSID/assets/57661283/32f3510b-655d-4953-9c1e-69b6b4a44b8f)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

23.08.03

### Tema Yang Digunakan

natra

### Informasi tambahan

https://berputar.opendesa.id/

**Comment by andifahruddinakas** [comment]
bisa di cek diserver beta.opendesa.id jika hanya terjadi pada 1 server saja, kemungkinan ada kesalahan konfirgurasi server.

dalam kasus ini setelah dicek adalah penggunaan server dan token melalui config, sbb : 
<img width="140" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/155bb647-f4dd-4d51-aa5f-af17567d78b6">

solusi : 
- [ ] jangan simpan token melalui config.php
- [ ] jika terpaksa menyimpan token melalui config.php karena alasan tertentu ganti penggunaan tanda **"** atau **'** pada isian token menjadi tanda **`**
- [ ] jika masih bermasalah, cek konfigurasi lainnya yang ada di desa/config/config.php dan desa/config/database.php. ganti config yang memungkinkan isiannya bisa terisi dengan tanda **"** atau **'** dengan tanda **`**. Contoh : **$db['default']['password'] = 'asasas*JbG3lF';** mejadi **$db['default']['password'] = `asasas*JbG3lF`;**

**Comment by andifahruddinakas** [comment]
https://forum.opendesa.id/d/305-gagal-akses-status-desa-idm
