### ISSUE TITLE
Bug/error: No surat tidak terganti saat pemeriksaan surat

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#7073]
### Jelaskan error yg dialami

1. ketika ingin verifikasi surat no surat tidak terganti

### Cara untuk mereplikasi errornya

1. aktifkan pengaturan tte
2. buat surat
3. klik verifikasi surat 

### Hasil yg diharapkan

Sesuaikan kode surat sesuai dengan urutan dan terganti dengan no surat yang lengkap

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/59082428/a6b37390-ffd6-425b-96e4-db1075feebf2)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v2308.0.3

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2850
