### ISSUE TITLE
Bug/error: field password pengaturan TTE

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#7074]
### Jelaskan error yg dialami

password masih terlihat dari inspect element 

### Cara untuk mereplikasi errornya

1. Pergi pengaturan tte
2. lalusorot ke bagian pasword TTE 
3. lalu klik kanan inspect element dan password bisa terlihat dari value field password tersebut.

### Hasil yg diharapkan

Sebaiknya password jangan di keluarkan sebagai value dalam field password agar password tidak dapat dilihat oleh petugas / operator lain.
bisa di tambahkan logic agar password tidak terupdate jika field password dikosongkan , namun ketika field password diisi berarti password bisaterupdate.

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/59082428/4aa7d603-c46a-4586-82b1-d90522162ff5)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v2308.0.3

**Comment by andifahruddinakas** [comment]
masuk dicatatan rilis issue https://github.com/OpenSID/OpenSID/issues/7056

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2845
