### ISSUE TITLE
Bug/error: Cek Teks Berjalan tidak tampil di website

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#7076]
### Jelaskan error yg dialami

teks berjalan tidak tampil di website

### Cara untuk mereplikasi errornya

masuk menu Admin Web -> Teks Berjalan

buat 1 teks lalu simpan (gembok terbuka)

cek apakah tampil di website.

===
buat 1 lagi teks lalu simpan (gembok terbuka)

cek apakah tampil di website juga

===
tukar posisi urutan 2 teks yg sudah dibuat.

cek juga apakah tampil di website 

### Hasil yg diharapkan

normal

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Terbaru

**Comment by andifahruddinakas** [comment]
SOLUSI : 
- [ ] kondisi aktif atau tidak aktif gunakan 1 atau 2. penerapan saat ini tidak konsisten
- [ ] saat melakukan simpan data status nilainya 0 (tidak aktif) nammun ditampilkan di tabel dengan icon kunci aktif (kondisi tidak sesuai)
- [ ] pada form, tambahkan isian status untuk aktif dan tidak aktif (tdk otomatis terisi 0)
- [ ] gunakan StatusEnum.php agar konsisten

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2868
