### ISSUE TITLE
Bug/error: Tambah penduduk baru lahir/ubah data biodata, data akseptor KB di bagian kesehatan tidak tersimpan

### ISSUE THREAD

**Issue by WAHYUDIK** [OpenSID/OpenSID#7077]
### Jelaskan error yg dialami

tambah penduduk lahir/masuk/ubah biodata pendududuk data akseptor KB di bagian informasi kesehatan tidak tersimpan

### Cara untuk mereplikasi errornya

1. tambah penduduk lahir/masuk/ubah biodata penduduk
2. isi semua isian atau yang penting2 saja
3. dibagian isian akseptor KB dipilih sesuai informasi kemudian simpan
4. masuk ke menu statistik, sub menu statistik kependudukan
5. cek statistik kependudukan bagian akseptor KB 

### Hasil yg diharapkan

hasil isian di bagian akseptor KB bisa tersimpan dengan benar, sehingga di statistik kependudukan dapat terbaca

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/31026980/3f114b37-c571-4128-b4ab-76c16404d9b0)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

beta.opendesa

**Comment by andifahruddinakas** [comment]
mas @WAHYUDIK, saya coba bisa dengan menggunakan kondisi berikut : 
- pastikan status perkawinan diisi dengan **KAWIN** sebelum mengisi cara akseptor kb.

<img width="167" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/81758dc9-1418-41ac-a534-ca2df6692627">

<img width="342" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/5e452d18-91f7-4e14-8786-8b952efd8c8c">


untuk kondisi di atas di terapkan sampai saat ini.

<img width="424" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/c1882433-8b12-4229-9ea2-f4c11e432c39">

Adapun yang bisa di ubah sesuai kondisi di atas adalah sebagai berikut : 
- [ ] tampilkan akseptor kb hanya jika status kawin saja
- [ ] tampilkan pilihan akseptor kb berdasarkan jenis_kelamin
