### ISSUE TITLE
Bug/error: Aparatur Desa yang sudah non aktif jabatannya muncul di disposisi surat

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#7078]
### Jelaskan error yg dialami

Ketika mengisi Buku agenda surat masuk ==> Disposisi Kepada masih muncul jabatan aparatur desa yang sudah non aktif jadi perangkat desa
<img width="773" alt="Screenshot 2023-08-26 153400" src="https://github.com/OpenSID/OpenSID/assets/25834335/ca820f89-c238-4b8c-82cd-144320ade83b">
<img width="323" alt="Screenshot 2023-08-26 153505" src="https://github.com/OpenSID/OpenSID/assets/25834335/6d31e94f-aeda-4097-8742-dd6aabbb3099">

### Cara untuk mereplikasi errornya

Pergi ke halaman 'Buku Administrasi Desa'
Klik Menu 'Administrasi Desa klik Buku Agenda Surat Masuk'
Gulir ke bawah sampai 'Disposisi Kepada'
Lihat Jabatan Perangkat yang sudah Non aktif Masih Muncul

### Hasil yg diharapkan

Jabatan Perangkat Desa yang sudah Non Aktif Tidak Muncul

### Tangkapan layar dan log error

<img width="773" alt="Screenshot 2023-08-26 153400" src="https://github.com/OpenSID/OpenSID/assets/25834335/ee0c75c3-d410-4f26-b807-7a2eb22596bf">

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Rilis  Versi 2308.0.3-premium

**Comment by andifahruddinakas** [comment]
Untuk saat ini yang tidak ditampilkan hanya jabatan kepala desa, belum termasuk jabatan lain yang non aktif.

SOLUSI : 
- [x] jangan tampilkan jabatan kades
- [x] jangan tampilkan jabatan yang tidak aktif dan tidak digunakan di pengurus. Contoh: pada modul jabatan ada Wakil XXX, namun pada pengurus tidak digunakan, maka pada jabatan disposisi juga tidak ditampilkan

**Comment by andifahruddinakas** [comment]
Karena pembekuan tgl 26-08-2023 dan bertepatan hari libur, kemungkinan perbaikan akan masuk rev01

**Comment by MUHAMMADRANGSEL** [comment]
ok siap bang

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2853
