### ISSUE TITLE
Permintaan fitur: Membalas Komentar di Artikel

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#7079]
### Apa kekurangan yg ingin diatasi?

Ketika Ada Komentar dari artikel admin desa merasa kesulitan untuk membalas komentar yang masuk

### Jelaskan solusi yg diinginkan

Masuk di Menu AdminWeb/ Komentar, untuk membalas komentar belum ada tombol yang disediakan saat ini admin desa harus membuka artikel yang diberi komentar dan untuk mambalas komentar admin desa harus mengisi form seperti warga, diharapkan untuk membalas komentar admin desa tidak perlu ke halaman web tetapi cukup melalui menu komentar tidak ubahnya seperti Chat Layanan Mandiri dengan warga yang memohon surat

### Apakah ada alternatif lain

Seperti Chat melalui Layanan Mandiri

### Untuk versi OpenSID mana

Rilis  Versi 2308.0.3-premium

**Comment by ariandii** [comment]
duplicate issue https://github.com/OpenSID/OpenSID/issues/4017

**Comment by MUHAMMADRANGSEL** [comment]
ok siap saya close aja kalau gitu bang
