### ISSUE TITLE
Bug/error: menambah anggota di menu lembaga eror dan diarahkan ke input data kelompok

### ISSUE THREAD

**Issue by WAHYUDIK** [OpenSID/OpenSID#7081]
### Jelaskan error yg dialami

coba menambahkan anggota lembaga dengan data yang sudah ada (misalkan menambah 1 anggota lembaga baru yang sudah menjadi ketua, dengan jabatan sebagai wakil ketua), kemudian klik simpan. sistem akan memberikan informasi data gagal disimpan. akan tetapi setelah di cek sistem mengarahkan ke data form anggota kelompok. 

### Cara untuk mereplikasi errornya

tambahkan 1 anggota lembaga yang sama.
klik simpan

### Hasil yg diharapkan

sistem tetap mengarahkan ke form anggota lembaga, meskipun muncul keterangan data gagal disimpan. 

### Tangkapan layar dan log error

https://github.com/OpenSID/OpenSID/assets/31026980/3741c03e-193b-4bca-a6ef-6dc47efa8b18

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

beta.opendesa

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2852
