### ISSUE TITLE
Bug/error: Sebutan Desa Tidak Sesuai Pengaturan pada Grafik APBDesa

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#7082]
### Jelaskan error yg dialami

Pada pengaturan aplikasi, sebutan desa adalah desa, hasilnya gambar 1.

ketika dibuah menjadi Gampong, maka hasilnya gambar 2.

gambar 1
<img width="960" alt="2023-08-27_16h49_33" src="https://github.com/OpenSID/OpenSID/assets/46939846/a3c24376-eda0-480b-b0f4-7738d720070f">

gambar 2
<img width="959" alt="2023-08-27_16h50_19" src="https://github.com/OpenSID/OpenSID/assets/46939846/e214591d-07a9-459b-9cdd-0791652357bb">

### Cara untuk mereplikasi errornya

masuk menu Pengaturan -> Aplikasi

dan sesuaikan seperti gambar berikut.

<img width="929" alt="2023-08-27_16h52_06" src="https://github.com/OpenSID/OpenSID/assets/46939846/ae287ecc-b196-40e5-b96f-e0e2ec4638ff">

### Hasil yg diharapkan

normal kembali

### Tangkapan layar dan log error

di atas

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Beta

**Comment by agungsugiarto** [comment]
sudah ok pak @ariandii ?



![Image](https://github.com/OpenSID/OpenSID/assets/10989147/d096220a-3c78-4476-b695-291ab49ef3c8)

**Comment by ariandii** [comment]
betul pak, dan judul APBDesa disesuaikan jadi APBG jika untuk Gampong

**Comment by ariandii** [comment]
namum ada yang perlu direvisi pada masing masing POS

**Comment by ariandii** [comment]
ini salah pak.

![IMG_20230828_173143_854](https://github.com/OpenSID/OpenSID/assets/46939846/7741dd8b-f751-4553-a8db-467de14b3c69)

tidak pakai kata desa/gampong.

**Comment by ariandii** [comment]
dan sebutan Dana Desa tetap, bukan diubah ke Dana Gampong

**Comment by ariandii** [comment]
Hasil Usaha Gampong
Dana Desa
Bagi Hasil Pajak dan Restribusi
Alokasi Dana Gampong
Bantuan Keuangan Kabupaten/Kota

**Comment by agungsugiarto** [comment]
sudah di sesuaikan pak @ariandii 

![image](https://github.com/OpenSID/OpenSID/assets/10989147/c6bad07c-b385-40bc-a12e-49159d725d34)

**Comment by ariandii** [comment]
terima kasih pak.

**Comment by ariandii** [comment]
> sudah di sesuaikan pak @ariandii
> 
> ![image](https://user-images.githubusercontent.com/10989147/263882114-c6bad07c-b385-40bc-a12e-49159d725d34.png)

bisa coba beri contoh lengkap nya pak?
seperti tampilkan Bunga Bank,  Swadaya, Partisipasi dan Gotong Royong, Bantuan Keuangan Provinsi, Penerimaan dari Hasil Kerjasama dengan Pihak Ketiga, Hibah dan Sumbangan dari Pihak Ketiga,  Koreksi Kesalahan Belanja Tahun-tahun Sebelumnya, Lain-lain Pendapatan Desa Yang Sah

agar yakin tidak ada imbuhan kata Sebutan Desa diakhir kata nya.

**Comment by ariandii** [comment]
judul APBG di atas, menjadi salah ketika sebutan adalah desa, mengapa sekarang menjadi APBD. seharusnya APBDesa

**Comment by agungsugiarto** [comment]
Pak @ariandii ini mohon di isi, yang di harapkan seperti apa perubahannya:

- Hasil Usaha Desa	=
- Hasil Aset Desa =
- Swadaya, Partisipasi dan Gotong Royong =
- Lain-Lain Pendapatan Asli Desa =
- Dana Desa =
- Bagi Hasil Pajak dan Retribusi =
- Alokasi Dana Desa =
- Bantuan Keuangan Provinsi =
- Bantuan Keuangan Kabupaten/Kota =
- Penerimaan dari Hasil Kerjasama Antar Desa =
- Penerimaan dari Hasil Kerjasama dengan Pihak Ketiga =
- Penerimaan Bantuan dari Perusahaan yang Berlokasi di Desa =
- Hibah dan Sumbangan dari Pihak Ketiga =
- Koreksi Kesalahan Belanja Tahun-tahun Sebelumnya =
- Bunga Bank =
- Lain-lain Pendapatan Desa Yang Sah =

**Comment by ariandii** [comment]
selain Dana Desa, semua sebutan desa yang muncul mengikuti pengaturan sebutan desa.

**Comment by agungsugiarto** [comment]
> selain Dana Desa, semua sebutan desa yang muncul mengikuti pengaturan sebutan desa.

Iya mohon di isi pak

**Comment by agungsugiarto** [comment]
untuk judul misal APBDesa seharusnya seperti apa pak @ariandii ?

**Comment by ariandii** [comment]
APBDesa, selain Desa disingkat menjadi APBK untuk Kampung APBG untuk Gampong, dll

jika Kalurahan, maka APBKal
jika Tiyuh, maka APBT

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2851
