### ISSUE TITLE
Bug/error: Notifikasi pengaduan hilang terlalu cepat

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#7083]
### Jelaskan error yg dialami

<img width="700" alt="image" src="https://github.com/OpenSID/OpenSID/assets/46939846/24457f14-29cd-4f88-a4cc-35fc136e5496">

<img width="411" alt="2023-08-27_20h36_09" src="https://github.com/OpenSID/OpenSID/assets/46939846/feddb5b8-0e72-4303-ae47-14afe7b34f4d">

### Cara untuk mereplikasi errornya

buka web pengaduan lalu isikan:
1. salahkan captcha
2. tes kirim aduan yg sesuai.

ketika captcha salah maka notifikasi masih berada dalam modal.
namun ketika tes kirim aduan sukses atau sudah kirim lebih dari 1 pada hari yang sama, maka notifikasi muncul terallu cepat hingga menghilang sebelum dibaca.

### Hasil yg diharapkan

buat notif tidak hilagn seperti komentar artikel. atau muncul notif pada jendela modal jika tidak ingin tertutup history apa yang telah diajukan.

### Tangkapan layar dan log error

di atas

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Beta

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2869
