### ISSUE TITLE
Permintaan fitur: Pengaturan nomor surat berurutan berdasarkan kode klasifikasi / conditional input surat yang sama "Input Data Warga atau Non Warga"

### ISSUE THREAD

**Issue by gdbrns** [OpenSID/OpenSID#7087]
### Apa kekurangan yg ingin diatasi?

Saat ini jika menggunakan settingan **Nomor berurutan untuk masing2 surat masuk dan keluar, dan untuk setiap surat layanan dengan jenis yang sama maka hasilnya** setiap surat tinymce akan berbeda2 nomor surat antar template suratnya (masing2). Jika di desa ada dua surat dg kode klasifikasi yang sama dan kedua surat ini semestinya nomornya bergabung/berurutan.

Contoh :

1. Surat keterangan usaha Kode (Klasifikasi  500)
2. Surat keterangan domisili usaha (Kode Klasifikasi  500)

Jika di set dua template tinymce yang berbeda, settingan nomor tidak akan bergabung tapi berurutan sesuai masing-masing surat/template.

### Jelaskan solusi yg diinginkan

Untuk fitur tiny mce, ada dua solusi yang memungkinkan:

1. Masing2 surat dengan template yang berbeda, tapi dg pengaturan nomor yang sekarang nomornya tidak akan bergabung tp berurutan masing2 meski kode klasifikasinya sama. Jika memungkinkan ada pengaturan keempat yaitu : Nomor berurutan untuk masing2 surat masuk dan keluar, dan untuk setiap surat layanan dengan kode klasifikasi surat yang sama

2. Suratnya satu jika seandainya ada pilihan conditional saat create surat, "Input Data Warga" dan "Input Data Non Warga"  jika "Input Data Non Warga" mengarah ke form yang dikustomisasi , kalau sekarang pengaturan data kategori individu di tinyMCE hanya bisa dipilih satu saja untuk setiap template yang dibuat, antara penduduk desa atau penduduk luar desa.

### Apakah ada alternatif lain

Sudah mencoba menggabungkan suratnya menjadi satu template tinymce, tapi tidak bisa karena pengaturan template wajib memilih jika sumber data individu harus salah satu di antara warga desa/warga laur desa.

Memisahkan menjadi dua template yang berbeda akan tetapi pengaturan nomor surat tidak dapat bergabung / terpisah tidak berurutan

### Untuk versi OpenSID mana

2308.0.3-premium

### Informasi tambahan

Ini jg bisa berlaku untuk surat yang berpotensi mengandung dua data penduduk dalam satu surat

**Comment by gdbrns** [comment]
Apakah ini permintaan fiturnya sudah ada pak sehingga statusnya closed  ?

**Comment by andifahruddinakas** [comment]
> Apakah ini permintaan fiturnya sudah ada pak sehingga statusnya closed ?

Close? Issue ini tidak ditutup, cuma ada issue yang serupa yang pernah buat sebelumnya. Agar tidak duplikasi, issue lama ditutup. 

https://github.com/OpenSID/OpenSID/issues/3472

**Comment by gdbrns** [comment]
oalah maaf mas sy ngelihat yg satunya #3472

**Comment by andifahruddinakas** [comment]
Duplicate of https://github.com/OpenSID/OpenSID/issues/7882
