### ISSUE TITLE
Bug/error: Permintaan Akses Kamera pada Buku Tamu

### ISSUE THREAD

**Issue by mah-mudi** [OpenSID/OpenSID#7088]
### Jelaskan error yg dialami

Buku Tamu tidak bisa diisi jika tidak ada kamera pada anjungan mandiri

### Cara untuk mereplikasi errornya

1. anjungan
2. isi buku tamu
3. tidak bisa klik simpan

### Hasil yg diharapkan

Meskipun tanpa kamera Buku Tamu harusnya bisa diisi

### Tangkapan layar dan log error

![WhatsApp Image 2023-08-31 at 15 16 17](https://github.com/OpenSID/OpenSID/assets/57661283/eb5df94a-7186-4a13-a921-02df1583e6f1)

![WhatsApp Image 2023-08-31 at 15 16 17 (1)](https://github.com/OpenSID/OpenSID/assets/57661283/dac05423-7aaf-4d07-ac34-b6b1923e1ebf)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

23.08.03

### Tema Yang Digunakan

denatra

### Informasi tambahan

-

**Comment by ariandii** [comment]
<img width="725" alt="image" src="https://github.com/OpenSID/OpenSID/assets/46939846/e2ebcfed-6ced-4b64-8b64-5a3b713b4f42">
