### ISSUE TITLE
Scan ktp elektronik memunculakan data yang tidak benar

### ISSUE THREAD

**Issue by mranca** [OpenSID/OpenSID#7091]
### Jelaskan error yg dialami

Saat scan ktp data yang muncul pada saat membuat surat menggunakan tinymce menghasilkan data yang tidak benar 

### Cara untuk mereplikasi errornya

.

### Hasil yg diharapkan

.

### Tangkapan layar dan log error

.

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

V2308.0.1

### Tema Yang Digunakan

Pusako

### Informasi tambahan

.

**Comment by andifahruddinakas** [comment]
Alur : 
1. Saya daftarkan id KTP dengan RFID pada penduduk.
<img width="671" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/760a8f09-8244-479f-8f79-c00be0ba3dd0">

2. Masuk ke salah 1 surat tinymce, misalnya surat keterangan beda identitas.
<img width="677" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/a3fbd639-520c-4368-90c4-49d81b55f543">

3. Setelah form tampil, lakukan scan menggunakan RFID dengan E-KTP yg sudah didaftarkan sebelumnya. Namun hasilnya berbeda, yang dimana seharusnya menampilkan data **AKAS**.
<img width="726" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/6e1804ac-0b71-4efc-ab99-ebdbc03f22d8">


Perbaikan : 
- [ ] Saat pertama kali buka form, pastikan autofocus mengarah pada select2 penduduk (data utama), sehingga bisa lakukan scan tanpa memilih select2 terlebih dahulu.
- [ ] Sesuaikan pencarian berdasarkan hasil scan RFID.

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2985
