### ISSUE TITLE
Penambahan status kepemilikan KTP di Form Isian Penduduk

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#710]
Supaya bisa ditampilkan di statistik terkait kepemilikan KTP perlu ditambahkan status kepemilikan KTP di Form Isian Penduduk
![screenshot 2017-11-12 21 06 16](https://user-images.githubusercontent.com/25834335/32699353-26594a04-c7ef-11e7-898b-97afa2f29bc1.png)

untuk bahasa status kepemilkan KTP bisa disesuaikan lagi

**Comment by MUHAMMADRANGSEL** [comment]
Untuk Statusn KTP-EL : 
1. BELUM WAJIB
2. BELUM REKAM
3. SUDAH REKAM
4. CARD PRINTED
5. PRINT_READY_RECORD
6. CARD SHIPPED
7. SENT FOR CARD PRINTING

UNTUK BISA DIBUATKAN STATISTIK KEPEMILIKAN KTP

**Comment by MUHAMMADRANGSEL** [comment]
WAJIB KTP
1. BELUM
2. WAJIB

**Comment by MUHAMMADRANGSEL** [comment]
KTP EL
1. BELUM
2. KTP -EL

**Comment by MUHAMMADRANGSEL** [comment]
dengan selesainya https://github.com/OpenSID/OpenSID/issues/351 maka issue Penambahan status kepemilikan KTP di Form Isian Penduduk #710 perlu segera dikerjakan

**Comment by eddieridwan** [comment]
Di contoh BIP yang berisi data e-ktp (https://github.com/OpenSID/OpenSID/files/1498598/BIP_KK_DOMPO.INDAH.zip),
ada 4 kolom terkait e-ktp:

1. 16-Wjb KTP
2. 17-KTP-eL
3. 18-Status
4.  19-Stat Rkm

Bung @MUHAMMADRANGSEL, pertanyaan bagi anda:

1. kolom (16- Wjb KTP), (17 - KTP-eL) dan (19 - Stat Rkm) sepertinya sesuai dengan ketiga kolom yang anda jelaskan di comment2 di atas. Bagaimana dengan kolom (18 - Status)? Apakah kolom ini diperlukan? Apa pilihan isinya?

<img width="1094" alt="contoh-bip-ektp" src="https://user-images.githubusercontent.com/249563/34645243-865944da-f39c-11e7-8ea0-2ee52bb44208.png">

**Comment by MUHAMMADRANGSEL** [comment]
Kalau kolom nomor 18 bisa diabaikan mas Eddie Krn pada prinsipnya sama
dengan kolom nomor 19

Pada tanggal 7 Jan 2018 8.29 AM, "Eddie Ridwan" <notifications@github.com>
menulis:

Di contoh BIP yang berisi data e-ktp (https://github.com/OpenSID/
OpenSID/files/1498598/BIP_KK_DOMPO.INDAH.zip),
ada 4 kolom terkait e-ktp:

   1. 16-Wjb KTP
   2. 17-KTP-eL
   3. 18-Status
   4. 19-Stat Rkm

Bung @MUHAMMADRANGSEL <https://github.com/muhammadrangsel>, pertanyaan bagi
anda:

   1. kolom (16- Wjb KTP), (17 - KTP-eL) dan (19 - Stat Rkm) sepertinya
   sesuai dengan ketiga kolom yang anda jelaskan di comment2 di atas.
   Bagaimana dengan kolom (18 - Status)? Apakah kolom ini diperlukan? Apa
   pilihan isinya?

[image: contoh-bip-ektp]
<https://user-images.githubusercontent.com/249563/34645243-865944da-f39c-11e7-8ea0-2ee52bb44208.png>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/OpenSID/OpenSID/issues/710#issuecomment-355789119>, or mute
the thread

**Comment by eddieridwan** [comment]
@MUHAMMADRANGSEL : 

1. Apa hubungan antara masing2 kolom? Yaitu, apa aturan/ketentuan isi masing-masing kolom Misalnya, kalau 16-Wjb KTP = BELUM, maka 17-KTP-el harus berisi BELUM, 18-Status harus BELUM REKAM dan 19-Stat Rkm harus BELUM WAJIB...?
2. Apakah data kepemilikan KTP ini akan di-update oleh operator desa atau hanya diimpor dari BIP-ektp? Jika diupdate oleh operator desa, dari mana diperoleh informasinya?

**Comment by MUHAMMADRANGSEL** [comment]
1. Points 1 saling berkaitan
2. Point 2 pertama kali ambil data dari dukcapil atau pendataan tentang
kepemilikan KTP dan juga setiap akhir tahun desa diberikan soft file data
BIP oleh dukcapil

Pada tanggal 7 Jan 2018 9.28 AM, "Eddie Ridwan" <notifications@github.com>
menulis:

**Comment by MUHAMMADRANGSEL** [comment]
Dan harus diupdate oleh desa shgg pemerintah desa tau berapa masyarakatnya
yg SDH dan belum punya ktp

Pada tanggal 7 Jan 2018 7.57 PM, "MUHAMMAD SPD" <muhammadrangsel@gmail.com>
menulis:

1. Points 1 saling berkaitan
2. Point 2 pertama kali ambil data dari dukcapil atau pendataan tentang
kepemilikan KTP dan juga setiap akhir tahun desa diberikan soft file data
BIP oleh dukcapil

Pada tanggal 7 Jan 2018 9.28 AM, "Eddie Ridwan" <notifications@github.com>
menulis:

**Comment by eddieridwan** [comment]
Heheh... Butir 1 - bahwa saling berkaitan sudah jelas. Tapi persisnya apa kaitan antara nilai2 ketiga kolom itu? Supaya bisa divalidasi. Satu contoh sudah diberikan di atas. 

Status 'Wajib KTP' sebenarnya ditentukan aturan: 'wajib untuk yang sudah berumur 17 atau pernah kawin' (https://id.wikipedia.org/wiki/Kartu_Tanda_Penduduk). Jadi sepertinya kolom ini sebaiknya dibuat otomatis tergantung tanggal lahir dan status kawin --- yaitu tidak bisa diedit ataupun diimpor. Bagaimana?

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
