### ISSUE TITLE
Bug/error: Margin lampiran

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#7100]
### Jelaskan error yg dialami

Margin lampiran mengikuti margin surat tinymce yang dicetak, sehingga lampiran jadi berantakan.

### Cara untuk mereplikasi errornya

1. cetak surat yang memiliki lampiran
2. perhatikan tampilan lampiran yang dihasilkan, margin mengikuti surat yg dicetak.

### Hasil yg diharapkan

Karena margin sifatnya statis, masih di atur dalam file, untuk margin seharunya mengikuti aturan pada file tsb.

### Tangkapan layar dan log error

Surat Keterangan Kelahiran TinyMCE, dengan lampiran : 
<img width="384" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/5c2daf22-4601-494d-902e-d958f52d7d8f">

Surat Keterangan Kelahiran RTF, dengan lampiran : 
<img width="471" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/39411bb0-8bc1-40ed-b3d0-4d9aebca737d">

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v2309.0.0

### Tema Yang Digunakan

.

### Informasi tambahan

.

**Comment by agungsugiarto** [comment]
library `spipu\html2pdf` belum mendukung untuk mengatur margin yang berbeda halaman.

**Comment by andifahruddinakas** [comment]
> library `spipu\html2pdf` belum mendukung untuk mengatur margin yang berbeda halaman.

coba cek ini 

https://stackoverflow.com/questions/4794435/merge-pdf-files-with-php

https://github.com/karriereat/pdf-merge

jadi di pisah dlu, baru digabungkan.

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2926
