### ISSUE TITLE
Bug/error: Penyesuaian Instalasi dengan Wizard

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#7101]
### Jelaskan error yg dialami

![IMG_20230902_115359_864](https://github.com/OpenSID/OpenSID/assets/46939846/8b66adac-6e0b-403a-9d87-c9f8d38b181c)

### Cara untuk mereplikasi errornya

lakukan install baru 2309.0.0-premium sampai sukses migrasi dan keluar pegaturan user pengguna.

### Hasil yg diharapkan

1. berikan info user yang dibuat admin atau boleh bebas
2. berikan kolom pengulangan password agar yakin dan tidak typo
3. berikan tombol intip password agar yakin yang diketik sudah sesuai
4. berikan pasholder di tiap kolom

### Tangkapan layar dan log error

di atas

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2309.0.0 premium

### Informasi tambahan

jika user wajib admin, sebaiknya user pengguna disable dan plasholder adalah admin

**Comment by andifahruddinakas** [comment]
issue terkait instalasi sy satukan disini https://github.com/OpenSID/OpenSID/issues/7102
