### ISSUE TITLE
Penyesuaian Instalasi dengan Wizard

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#7102]
### Jelaskan error yg dialami

saat ini loading saat install baru 2309.0.0-premium mengunakan wozard yang belum terlihat oleh pengguna secara mudah.

### Cara untuk mereplikasi errornya

lakukan install baru 2309.0.0 hingga proses migrasi

### Hasil yg diharapkan

adanya bar proses atau persentase proses seperti migrasi pada halaman admin

mengingat jumlah data adalah pasti yang dimigrasi tsb

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2309.0.0 premium

**Comment by andifahruddinakas** [comment]
Yang perlu disesuaikan : 
- [ ] berkaitan dengan password sediakan show hidden tombol untuk mmelihat password.
![image](https://github.com/OpenSID/OpenSID/assets/57283157/eb1e0543-10f4-40ef-acb1-a76c1499683d)

- [ ] tambahkan loading saat proses menunggu migrasi (contoh bar proses atau persentase proses seperti migrasi pada halaman admin)
