### ISSUE TITLE
Bug/error: Slider tidak muncul

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#7103]
### Jelaskan error yg dialami

slider 10 gambar utama artikel terbaru tidak otomatis tampil do 2309.0.0 -premium

### Cara untuk mereplikasi errornya

masuk menu artikel -> slider

pilih 10 gambar utama artikel terbaru paling atas dan simpan.

dan cek slider tidak akan muncul di web.

lecuali 1 atau lebih pada menu Admin Web -> artikel di klik masukkan slider. baru muncul.
walau itu untuk fungsi pengaturan 10 gambar utama artikel terbaru yang masuk ke slider atas tombol tengah di Pengaturan Slider.

### Hasil yg diharapkan

normal kembali

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2309.0.0 premium

**Comment by andifahruddinakas** [comment]
Duplicate of https://github.com/OpenSID/OpenSID/issues/7103

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2878
