### ISSUE TITLE
Bug/error: Rata kanan kiri, Rata Tengah dan Rata Kanan tulisan tidak berfungsi pada artikel

### ISSUE THREAD

**Issue by mah-mudi** [OpenSID/OpenSID#7104]
### Jelaskan error yg dialami

Rata kanan kiri, Rata Tengah dan Rata Kanan tulisan tidak berfungsi pada artikel

### Cara untuk mereplikasi errornya

1. artikel
2. rata kanan kiri
3. simpan
4. lihat artikel

### Hasil yg diharapkan

Rata kanan kiri, Rata Tengah dan Rata Kanan tulisan dapat berfungsi pada artikel sebagaimana mestinya pada artikel 

### Tangkapan layar dan log error

[screen-capture (1).webm](https://github.com/OpenSID/OpenSID/assets/57661283/6f7ba036-6d25-491c-bae9-eb937e0f56d5)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

23.09.0.0

### Tema Yang Digunakan

esensi

### Informasi tambahan

beta.opendesa.id

**Comment by andifahruddinakas** [comment]
Sumber masalahnya sama, yakini editor tinymce untuk artikel.

Issue ini ditutup dan dilengkapi di issue https://github.com/OpenSID/OpenSID/issues/7113
