### ISSUE TITLE
Bug/error: File JPG tidak bisa diupload di latar website dan Latar Login Admin ketika setting aplikasi

### ISSUE THREAD

**Issue by mah-mudi** [OpenSID/OpenSID#7105]
### Jelaskan error yg dialami

File JPG tidak bisa diupload di latar website dan Latar Login Admin ketika setting aplikasi

### Cara untuk mereplikasi errornya

1. pengaturan
2. aplikasi
3. latar website, atau latar login - pilih file jpg
4. simpan , maka akan gagal

### Hasil yg diharapkan

File JPG bisa diupload di latar website dan Latar Login Admin ketika setting aplikasi

### Tangkapan layar dan log error

[screen-capture (2).webm](https://github.com/OpenSID/OpenSID/assets/57661283/528fae5a-2e90-43ca-bf15-cab50f824740)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

23.09.0.0

### Tema Yang Digunakan

esensi

### Informasi tambahan

beta.opendesa.id

**Comment by andifahruddinakas** [comment]
mas @mah-mudi, saya coba sesuai intruksi error tsb tidak terjadi.

https://github.com/OpenSID/OpenSID/assets/57283157/a82286c8-2251-404c-b5e3-795569b193b8
