### ISSUE TITLE
Bug/error: Nama Ayah, Nama Ibu, NIK Ayah dan NIK Ibu Kode Isian tidak muncul padahal data kependudukan sudah lengkap data tsb, serta ada Kode Isian Nama Ayah Ibu GANDA

### ISSUE THREAD

**Issue by mah-mudi** [OpenSID/OpenSID#7106]
### Jelaskan error yg dialami

Nama Ayah, Nama Ibu, NIK Ayah dan NIK Ibu Kode Isian tidak muncul padahal data kependudukan sudah lengkap data tsb

Nama Ayah dan Nama Ibu pada Kode Isian = GANDA

### Cara untuk mereplikasi errornya

1. Layanan Surat
2. Cetak Surat

### Hasil yg diharapkan

Nama Ayah, Nama Ibu, NIK Ayah dan NIK Ibu Kode Isian dapat muncul sebagaimana mestinya
Nama Ayah dan Nama Ibu pada Kode Isian = TIDAK GANDA

### Tangkapan layar dan log error

https://github.com/OpenSID/OpenSID/assets/57661283/f43287a0-712a-4efe-b325-37af3c9c46f8

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

23.09.0.0

### Tema Yang Digunakan

esensi

### Informasi tambahan

beta.opendesa.id

**Comment by agungsugiarto** [comment]
Pak @mah-mudi saya tidak menemukan issue yang dimaksud, mas @andifahruddinakas bisa di replikasi issue ini?



![Image](https://github.com/OpenSID/OpenSID/assets/10989147/806012ab-dbaa-41ef-b3b8-7c07f88f8916)

**Comment by andifahruddinakas** [comment]
> Pak @mah-mudi saya tidak menemukan issue yang dimaksud, mas @andifahruddinakas bisa di replikasi issue ini?
> 
> 
> 
> ![Image](https://github.com/OpenSID/OpenSID/assets/10989147/806012ab-dbaa-41ef-b3b8-7c07f88f8916)
> 
> 

Coba diperhatikan video yg dikirim. Itu ada duplikasi untuk nama ayah dan ibu untuk kode isiannya.

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2894
