### ISSUE TITLE
Bug: untuk pilihan ukuran huruf di pembuatan artikel hilang yang diversi sebelumnya ada

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#711]
fitur untuk pilihan ukuran di versi sekarang hilang yang dulunya ada
![screenshot 2017-11-12 21 24 33](https://user-images.githubusercontent.com/25834335/32699416-4b058542-c7f0-11e7-8e8f-be6b51a05f5c.png)

**Comment by eddieridwan** [comment]
Sebaiknya tunggu pengerjaan Memodernkan Tampilan Modul Admin selesai dulu.

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR #1657
