### ISSUE TITLE
Bug/error:bug pada modul penduduk - keluarga

### ISSUE THREAD

**Issue by mcalifjr** [OpenSID/OpenSID#7110]
### Jelaskan error yg dialami

Mohon ijin lapor, saya menemukan bug pada modul penduduk - keluarga, ketika saya ingin ubah biodata anggota kelurga setelah di klik simpan maka alamat, no kk, rt/rw pada keluarga/salinan kartu keluarga menjadi tidak muncul. Apabila di ubah biodata pada kepala keluarga akan kembali normal. Terimakasih

### Cara untuk mereplikasi errornya

Mohon ijin lapor, saya menemukan bug pada modul penduduk - keluarga, ketika saya ingin ubah biodata anggota kelurga setelah di klik simpan maka alamat, no kk, rt/rw pada keluarga/salinan kartu keluarga menjadi tidak muncul. Apabila di ubah biodata pada kepala keluarga akan kembali normal. Terimakasih

### Hasil yg diharapkan

Bisa normal kembali

### Tangkapan layar dan log error

https://github.com/OpenSID/OpenSID/assets/87459676/c83f719b-f8cf-41dc-966d-aaa300de2acc

### Rilis Versi OpenSID

Rilis Umum

### Versi OpenSID

23.09.00

### Tema Yang Digunakan

Esensi

**Comment by andifahruddinakas** [comment]
Duplicate of https://github.com/OpenSID/OpenSID/issues/6888
