### ISSUE TITLE
Bug/error: Nomor Surat pada Lampiran F-1.25 berisi titik titik (tidak ada)

### ISSUE THREAD

**Issue by khiar-rara** [OpenSID/OpenSID#7111]
### Jelaskan error yg dialami

Nomor surat masih berupa titik-titik

![nomorsurat](https://github.com/OpenSID/OpenSID/assets/74307159/02176b33-46b8-4a99-b979-bd32cd262809)

### Cara untuk mereplikasi errornya

1. Cetak Surat Keterangan Pindah Penduduk
2. Lampiran F-1.25

### Hasil yg diharapkan

Nomor surat otomatis terisi berdasarkan format nomor surat terakhir

### Tangkapan layar dan log error

Sebagaimana gambar diatas

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v2309.0.0

### Tema Yang Digunakan

Esensi

### Informasi tambahan

Tidak Ada

**Comment by andifahruddinakas** [comment]
di versi sebelum2nya (pada versi rtf) memang tidak di isi otomatis. kalau tempatnya ini bukan bug, namun rancangan memang dibuat seperti itu.

Adapun perubahan ini bisa diterapkan dengan diskusi dari pengguna yg lainnya.

Pak @ariandii, mungkin ada tanggapan.

**Comment by ariandii** [comment]
lampiran tidak memerlukan nomor surat desa karena itu dibuat dan di ttd oleh pemohon.

**Comment by andifahruddinakas** [comment]
> lampiran tidak memerlukan nomor surat desa karena itu dibuat dan di ttd oleh pemohon.

pak @khiar-rara

**Comment by khiar-rara** [comment]
ada beberapa jenis surat system yang diberi nomor surat pak
![image](https://github.com/OpenSID/OpenSID/assets/74307159/8b9723b5-4702-4658-a439-27629e9668dd)

**Comment by ariandii** [comment]
kalau itu jelas surat desa pak. ber kop desa. yang memerlukan nomor registrasi desa.

berbeda dengan lampiran.
sedangkan lampiran adalah blanko yang biasa ditulis tangan oleh pemohon saat ke dukcapil. lampiran bukan menggunakan nomor register desa.
