### ISSUE TITLE
Lampiran format surat persyaratan nikah N1 N2 N4 

### ISSUE THREAD

**Issue by mranca** [OpenSID/OpenSID#7112]
### Jelaskan error yg dialami

Hasilnya dokumentnya terlihat skala masih kecil

### Cara untuk mereplikasi errornya

Masuk di 
1. Layanan surat
2. Pengaturan surat
3. Buat surat
4. Pilih lampiran 

### Hasil yg diharapkan

Di usahakan agar hasilnya agar tampil lebih besar misalnya menggunakan font 12

### Tangkapan layar dan log error

.

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

23.09

### Tema Yang Digunakan

-

### Informasi tambahan

-

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2893
