### ISSUE TITLE
Bug/error: Tools editor tinymce pada artikel tidak berfungsi dengan baik

### ISSUE THREAD

**Issue by mah-mudi** [OpenSID/OpenSID#7113]
### Jelaskan error yg dialami

Perubahan Ukuran Huruf dan Warna Huruf pada artikel tidak berfungsi

### Cara untuk mereplikasi errornya

1. artikel
2. tulis
3. default ukuran 16px, coba atur ukuran huruf 23px atau lainnya serta atur warna huruf
4. huruf dan warna huruf tidak berubah ukurannya, tetap ukuran 16px dan warna tetap hitam

### Hasil yg diharapkan

Perubahan Ukuran Huruf dan Warna Huruf pada artikel dapat berfungsi sebagaimana mestinya

### Tangkapan layar dan log error

https://github.com/OpenSID/OpenSID/assets/57661283/e662364e-ad87-4e4a-8bf3-28626f9c4b88

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

23.09.0.0

### Tema Yang Digunakan

esensi

### Informasi tambahan

beta.opendesa.id

**Comment by andifahruddinakas** [comment]
Contoh : 
- [ ] rata kiri, kanan, tengah, kiri kanan
- [ ] ukuran font
- [ ] underline
- [ ] pewarna font dan background font
- [ ] dll

**Comment by mah-mudi** [comment]
@andifahruddinakas @vickyrolanda 
NUMBERED LIST yg abjad juga eror
![image](https://github.com/OpenSID/OpenSID/assets/57661283/551135dd-4556-4cf8-bf10-ec1b045f2f24)

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2911
