### ISSUE TITLE
Bug/error: Tes Surat Keterangan Kelahiran TinyMCE sampai tercetak dan perhatikan hasilnya

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#7114]
### Jelaskan error yg dialami

hasil cetak masih banyak yang kosong.

### Cara untuk mereplikasi errornya

1. buat penduduk seorang suami (Kepala Keluarga)
2. buat penduduk seorang istri
3. buat penduduk seorang anak
4. buat penduduk seorang famili lain

mereka masih penduduk lepas, jangan jadikan keluarga.

cetak Surat Keterangan Kelahiran, pada pilihan:
1. hanya muncul nama status Kepala Keluarga dan anak
2. tidak ada nama lain, termasuk nama istri
3. ketika pilih nama anak, maka akan otomatis terisi data ayah dan ibu (padahal status 4 orang di atas masih lepas) belum 1 keluarga.
4. periksa list data pelapor dan saksi

5. ketika sudah pilih data pelapor dan isi kolom Hubungan Pelapor dengan bayi lalu pilih saksi, kolom Hubungan ini kosong kembali

6. ketika klik simpan, data dari seorang ibu tertulis tanda minus ( - ) sesuai dengan input nama ayah di identitas bayi, namun ada tertulis dengan NIK, Umur, Pekerjaan terisi.
8. identitas Istri dari juga sama

10. tanggal lahir di Tanggal lembar 1 poin nomor 2 bukan tanggal sebenarnya di identitas desa, yg muncul tanggal sekarang.
11. begitu juga tanggal lahir lembar 2 salah, tertera tanggal hari ini padahal Tanggal Lahir di Penduduk adalah 02-03-2022

### Hasil yg diharapkan

rilis yang normal

### Tangkapan layar dan log error

tes di beta

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Beta

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2916
