### ISSUE TITLE
Bug/error: Jumlah Penduduk

### ISSUE THREAD

**Issue by afri18** [OpenSID/OpenSID#7119]
### Jelaskan error yg dialami

Jumlah Penduduk di laporan bulanan makin tidak sama dengan data penduduk di menu HOME dan Wilayah di Web

### Cara untuk mereplikasi errornya

Harusnya Jumlah Penduduk di Laporan Bulanan sama dengan di Menu HOME > Penduduk dan Web di Menu Wilayah/Statistik

### Hasil yg diharapkan

Jumlah Penduduk di semua menu sama

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/6611881/4abe2407-03b2-438c-ba80-004218795843)
![image](https://github.com/OpenSID/OpenSID/assets/6611881/fc3df8e3-0074-4ada-942e-1117de029064)
![image](https://github.com/OpenSID/OpenSID/assets/6611881/36e83072-af2e-494b-b89b-b464c6899d7c)
![image](https://github.com/OpenSID/OpenSID/assets/6611881/d476637f-5997-47a6-98b0-c5de0cb85042)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v2309.0.1-premium

### Tema Yang Digunakan

Denatra

**Comment by andifahruddinakas** [comment]
Database terlampir

**Comment by pandigresik** [comment]
`SELECT `p`.id,`p`.status_dasar , `p`.status , `l`.`kode_peristiwa`
FROM `tweb_penduduk` `p`
JOIN (
                SELECT    MAX(id) max_id, id_pend
                FROM      log_penduduk
                where DATE_FORMAT(tgl_lapor, '%Y-%m') < '2023-10'
                GROUP BY  id_pend
            ) log_max ON `log_max`.`id_pend` = `p`.`id`
JOIN `log_penduduk` `l` ON `log_max`.`max_id` = `l`.`id` and `l`.`kode_peristiwa` not in (2, 3, 4)
WHERE   (
`l`.`config_id` = 6 and p.status_dasar != 1
 )`

hasilnya 

![image](https://github.com/OpenSID/OpenSID/assets/1853475/e7efb958-bb64-4b4c-8c42-13cb88150341)

Berdasarkan data diatas ada sedikit keanehan dimana log terakhir menunjukkan kode_peristiwa = 5 (BARU_PINDAH_MASUK) namun status di tweb_penduduk tidak menunjukkan status 1 namun status 2 (mati) 

Sebagai informasi : 
Untuk jumlah penduduk yang ditampilkan pada halaman dashboard adalah penduduk dengan status_dasar = 1

**Comment by pandigresik** [comment]
Contoh kasus penduduk dengan id 3351
`select id, id_pend, kode_peristiwa, meninggal_di, tgl_lapor, tgl_peristiwa, created_at, updated_at  
 from log_penduduk lp where lp.id_pend = 3351`

![image](https://github.com/OpenSID/OpenSID/assets/1853475/51a65471-976d-4eeb-8f31-769c8d6f760a)

Sekilas sepertinya data lognya terbalik, jadi perlu dicari penyebab penulisan log yang agak aneh ini

**Comment by pandigresik** [comment]
database yang digunakan adalah 

![image](https://github.com/OpenSID/OpenSID/assets/1853475/b6fbc2ae-8be4-4296-8596-6f00cdba548c)
