### ISSUE TITLE
Request: Integrasi Pemerintah Desa yang ada di Pengaturan ke Halaman Statis Pemerintah Desa

### ISSUE THREAD

**Issue by Galiarta** [OpenSID/OpenSID#712]
Untuk memudahkan pengisian dan juga update, bisa kiranya mengintegrasikan Pemerintahan desa yang ada di **.../index.php/pengurus** kedalam halaman statis yang ada di **../index.php/web/form/999/1/0/92**

Berikut Screenshotnya ;
Pemerintah Desa/Pengurus
#
![pengurus](https://user-images.githubusercontent.com/33612251/32707386-7a2023c8-c85e-11e7-85ec-19cfa951a99e.jpg)

Terimakasih,

Galiarta

**Comment by andifahruddinakas** [comment]
Hanya menampilkan nama2 pemerintah ke halaman website. Untuk bagan halaman pemerintah desa dengan bagan bisa gunakan artikel dan insert bagan dsna.

**Comment by agungsugiarto** [comment]
Sudah di fitur premium melalui pr https://github.com/OpenSID/premium/pull/944
