### ISSUE TITLE
Bug/error: Photo Pengguna

### ISSUE THREAD

**Issue by afri18** [OpenSID/OpenSID#7121]
### Jelaskan error yg dialami

Susahnya membedakan masih login atau sudah keluar dari halaman admin karna photo pengguna tidak tampil sesuai dengan data penduduk, padahal photonya ada

### Cara untuk mereplikasi errornya

seharusnya photo pengguna sama dengan data penduduk dan selaras (sinkron) dengan data pemerintah desa

### Hasil yg diharapkan

Tampilkan Photo pengguna sesuai yang ada di Biodata Penduduk, tidak usah upload ulang

### Tangkapan layar dan log error

Photo Perangkat/Pengguna
![image](https://github.com/OpenSID/OpenSID/assets/6611881/b400a369-b690-483c-b57b-a3cd543d4bad)

tidak tampil
![image](https://github.com/OpenSID/OpenSID/assets/6611881/d6e5e4dc-4c9f-4fc9-83d3-e2d93eb25818)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2309.0.1

### Tema Yang Digunakan

Denatra

### Informasi tambahan

Jadikan Biodata penduduk sebagai basis data aplikasi/pengguna

**Comment by andifahruddinakas** [comment]
untuk foto pengguna berdiri sendiri, tidak terkait dengan modul apapun.

Adapun jika akan di kaitkan dengan data pamong -> penduduk akan membuat rumit sistem, performa dan maintenace. Karena berberapa kondisi yang akan di cek secara berulang hanya untuk menampilkan foto pengguna saja. Contoh di bawah ini.

- cek apakah di kaitkan dengan pamong (ya/tidak)
— ya lanjut
— tdk gunakan foto yg diunggah user (jika tidak ada gunakan foto default)
- cek apakah pamong dari penduduk desa (ya/tidak)
— ya lanjut
— tidak gunakan foto yg diunggah pamong (jika tidak ada gunakan foto default)
- cek apakah ada foto penduduk (ya/tidak)
— ya tampilkan
— tidak, cek jenis kelamin (jika tidak ada gunakan foto default)

Jika kondisi di atas diterapkan, 
- akan menimbulkan bug baru terkait cara menampilkan foto pengguna yang dimana perlu di cek 1/1
- akan menurunkan performa aplikasi saat menampilkan data user, karena banyaknya cabang pengecekan
- dll yang belum ditemukan

Dari desain awal memang secara default foto pengguna tidak dikaitkan kemanapun.

**Comment by afri18** [comment]
Kalau begitu Issue ini d tutup aja ....
