### ISSUE TITLE
Bug/error: Halaman Web Sempat Error 500 Layar Hitam

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#7122]
### Jelaskan error yg dialami

Ketika load website, semula normal seperti biasa.

lalu terkadang error 500 walau sedang tidak ada aktifitas apapun selain membuka halaman website.

Log error yang muncul adalah sebagai berikut:

<img width="711" alt="image" src="https://github.com/OpenSID/OpenSID/assets/46939846/d0f5c8af-007b-45a5-af18-959cfd874395">

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

Normal tanpa walau tanpa koneksi ke link sesuai log

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Beta

**Comment by andifahruddinakas** [comment]
Agar bisa mereplikasi issue ini, ganti `https://www.covid19.go.id/feed/` menjadi `https://www.covid191.go.id/feed/` yang menunjukkan website tsb tidak aktif.

https://github.com/OpenSID/premium/blob/rilis-dev/donjo-app/libraries/Feed_Reader.php#L59C31-L59C62

Sesuaikan pengaturan :
<img width="520" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/a412d20f-fd82-4719-a883-a96ab38b142a">

**Comment by ariandii** [comment]
atau bisa dibuat kolom link tersebut dapat diisi di pengaturan aplikasi atau Admin Web - Pengaturan pada halaman admin. agar dapat disesuaikan secara mandiri oleh desa ketika ingin menampilkan feed dari web selain covid19.

jika kolom kosong maka defaultnya seperti sekarang.

**Comment by MUHAMMADRANGSEL** [comment]
Setuju dengan usulan dari bung [ariandii](https://github.com/ariandii) supaya ketika ada perubahan link bisa disesuaikan oleh desa tanpa menunggu ada perbaikan di rilis berikutnya

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2901

**Comment by ariandii** [comment]
walau di bawahnya sudah diganti ke link lain,

keterangan pada pilihan dinsisi atas masih tertulis Covid RSS. dan keterangannya masih Apakah akan tampilkan RSS Covid-19 di halaman muka.

apakah tidak sebaiknya dituliskan secara umum?

![IMG_20230919_090501_730](https://github.com/OpenSID/OpenSID/assets/46939846/ab0c96d4-b981-49af-90c2-0356c3ae6eb0)

![Screenshot_20230919_090511_Chrome](https://github.com/OpenSID/OpenSID/assets/46939846/23a48f03-7f29-40a8-a23f-04aee22247ec)
