### ISSUE TITLE
Bug/error: Surat Keterangan Kelahiran (Lampiran F-2.01)

### ISSUE THREAD

**Issue by argasurya** [OpenSID/OpenSID#7125]
### Jelaskan error yg dialami

Pada Surat Keterangan Kelahiran, ketika mengisi "Kelahiran Anak Ke" diisi >1, hasil yang didapat pada Data Anak, Surat Kode . F-2.01 tetap bernilai 1.

### Cara untuk mereplikasi errornya

Buat Surat Keterangan Kelahiran, pada bagian "Kelahiran Anak Ke" diisi >1

### Hasil yg diharapkan

Sesuai dengan inputan

### Tangkapan layar dan log error

![Screenshot_1](https://github.com/OpenSID/OpenSID/assets/7027634/2beb0de8-0761-4f26-82a5-5812e3891075)

Hasil --->>>

![Screenshot_2](https://github.com/OpenSID/OpenSID/assets/7027634/9168a182-bd65-47ef-8a5a-682575b00c4a)

### Rilis Versi OpenSID

Rilis Umum

### Versi OpenSID

v2309.0.0

### Tema Yang Digunakan

natra

**Comment by andifahruddinakas** [comment]
Cek : 
- inputan penduduk lahir, 
<img width="399" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/9318f3e1-b522-4312-b306-0784e7c70aa4">


- cek hasil lampiran,
<img width="339" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/26273039-58e6-4740-b572-67729fc4cf00">

Ada ketidak sesuaian hasil dari lampiran : 
- [ ] data anak ke-

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2902
