### ISSUE TITLE
Bug/error: Surat Keterangan Lahir

### ISSUE THREAD

**Issue by afri18** [OpenSID/OpenSID#7126]
### Jelaskan error yg dialami

1. Terjadi kesalahan saat cetak surat keterangan lahir untuk anak yang lahir pada tanggalnya
2. Di lampiran terjadi salah hari lahir

### Cara untuk mereplikasi errornya

Harusnya tanggal dan hari sesuai database

### Hasil yg diharapkan

Tanggal dan hari lahir anak sesuai dengan database

### Tangkapan layar dan log error

Keterangan Lahir
![image](https://github.com/OpenSID/OpenSID/assets/6611881/0d5b67c2-36a1-4151-9984-534dbd1cf60b)

Lampiran F-2.01
![image](https://github.com/OpenSID/OpenSID/assets/6611881/796d0021-5600-4277-907c-b495468b2243)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2309.0.1

### Tema Yang Digunakan

Denatra

### Informasi tambahan

Harusnya data sesuai dengan database

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2890
