### ISSUE TITLE
Bug/error: Tidak bisa menambah kode isian pada surat tinymce Keterangan Kelahiran 

### ISSUE THREAD

**Issue by agungsugiarto** [OpenSID/OpenSID#7127]
### Jelaskan error yg dialami

Tidak bisa menambah kode isian pada surat tinymce Keterangan Kelahiran 

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

bisa menambah

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/10989147/eee63f03-5e21-4435-a204-06dcc1bb04ba)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Versi 2309.0.1-premium

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2891
