### ISSUE TITLE
Bug/error: Terdapat ketidaksesuaian redaksi output APBDesa pada halaman utama Web

### ISSUE THREAD

**Issue by mah-mudi** [OpenSID/OpenSID#7128]
### Jelaskan error yg dialami

Terdapat ketidaksesuaian redaksi output APBDesa pada halaman utama Web

### Cara untuk mereplikasi errornya

1. keuangan
2. input data
3. isi anggaran misal Bantuan Keuangan Kabupaten/Kota
4. simpan
5. output APBDesa berubah menjadi Bantuan Keuangan Kabupaten/Kota Desa 

sistem sudah benar tp output footer terlihat rancu

### Hasil yg diharapkan

Redaksi misal Bantuan Keuangan Kabupaten/Kota menampilkan yang sebenarnya

### Tangkapan layar dan log error

https://github.com/OpenSID/OpenSID/assets/57661283/30ec5e7c-30ce-4f36-a040-bed927b24a51

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

23.09.0.1

### Tema Yang Digunakan

natra

### Informasi tambahan

https://berputar.opendesa.id/

**Comment by ariandii** [comment]
duplicate https://github.com/OpenSID/OpenSID/issues/7082#issuecomment-1695444885
