### ISSUE TITLE
Scan Barcode tidak memunculkan penandatangan yang benar

### ISSUE THREAD

**Issue by mranca** [OpenSID/OpenSID#7129]
### Jelaskan error yg dialami

Saat Scan barcode surat data yang di hasilkan tidak sesuai, misalnya yang melalukan penandatangan adalah urusan bagian namun yang muncul tetap kepala desa

### Cara untuk mereplikasi errornya

.

### Hasil yg diharapkan

.

### Tangkapan layar dan log error

![Screenshot_20230917_100011](https://github.com/OpenSID/OpenSID/assets/76085245/3020e952-7b86-4b0d-8fb2-11e8a1f8e8b6)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

V2309.0.1

### Tema Yang Digunakan

Pusako

### Informasi tambahan

.

**Comment by ariandii** [comment]
https://www.natairaya.desa.id/verifikasi-surat/czIybGgwbGRuajRrNG9nOGM0czAsMTU5NywxNjk0OTIwMzg2LDE1OTc

saya replikasi, normal.

penandatangan yg muncul sudah sesuai.

**Comment by mranca** [comment]
Saya coba di berputar.opendesa.id namun masih terjadi bug pak
