### ISSUE TITLE
Request : Menampilkan Nama Kepala Kewilayahan secara otomatis di Surat

### ISSUE THREAD

**Issue by Galiarta** [OpenSID/OpenSID#713]
Di Desa saya pemohon surat (penduduk)  tidak ditampilkan dalam surat. Yang ditampilkan biasanya Kepala Kewilayahan (dalam hal ini Kepala Dusun) dan Kepala Desa.
Format surat yang biasanya digunakan seperti dibawah ini ;
![surat usaha](https://user-images.githubusercontent.com/33612251/32708380-795ff8f4-c864-11e7-8168-20765531d58d.jpg)
File DOC nya ;
[surat_ket_usaha Jadi.docx](https://github.com/OpenSID/OpenSID/files/1465514/surat_ket_usaha.Jadi.docx)

Request saya, bisakah nama Kepala Kewilayahan ditampilkan secara otomatis, sesuai dengan Dusun yang bersangkutan.

Nama kepala kewilayahannya seperti yang ada di ../index.php/sid_core
![wilayah administrasi](https://user-images.githubusercontent.com/33612251/32708439-f2d78922-c864-11e7-88dc-31b8693b1d4e.jpg)

Jadi misalnya Penduduk A dari wilayah A, otomatis di kepala kewilayahannya terisi dengan Kepala Dusun A.

Terimakasih,

Galiarta

**Comment by afa28** [comment]
Krn data wilayah sifatnya dinamis, mungkin agak susah di terapkan.

**Comment by afa28** [comment]
Duplicate issue https://github.com/OpenSID/OpenSID/issues/2519
