### ISSUE TITLE
Bug/error: Rubah Redaksi Berita Kepala Desa menjadi Berita Desa, Menyesuaikan Permendagri 111 Tahun 2014 tentang Pedoman Teknis Peraturan di Desa

### ISSUE THREAD

**Issue by mah-mudi** [OpenSID/OpenSID#7131]
### Jelaskan error yg dialami

Redaksi masih menggunakan Berita Kepala Desa

### Cara untuk mereplikasi errornya

1. Buku Administrasi Desa
2. Administrasi Umum
3. Buku Peraturan Di Desa
4. Tambah

### Hasil yg diharapkan

Rubah Redaksi Berita Kepala Desa menjadi Berita Desa

### Tangkapan layar dan log error

![berita desa](https://github.com/OpenSID/OpenSID/assets/57661283/f53fd3ac-3675-4825-86cb-54fc220af0ac)

![image](https://github.com/OpenSID/OpenSID/assets/57661283/37102ab5-e8cc-46b3-b42e-60ecee16a82c)

![image](https://github.com/OpenSID/OpenSID/assets/57661283/a55ebf84-a05d-4b9d-997f-8cd844c7a6b0)

![image](https://github.com/OpenSID/OpenSID/assets/57661283/4f07dc54-788e-49ad-8dd6-fda00eda7ce0)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

23.09.0.1

### Tema Yang Digunakan

natra

### Informasi tambahan

[1. Permendagri-No-111-Tahun-2014-Tentang-Pedoman-Teknis-Peraturan-di-Desa.pdf](https://github.com/OpenSID/OpenSID/files/12651224/1.Permendagri-No-111-Tahun-2014-Tentang-Pedoman-Teknis-Peraturan-di-Desa.pdf)

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2904
