### ISSUE TITLE
Permintaan fitur: Notifikasi telegram khsusu TTE

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#7132]
### Apa kekurangan yg ingin diatasi?

Saat ini notifikasi yang diberikan melalui telegram masih terdapat kekurangan dari segi alur dimana saat ini informasi tte hanya sebatas informasi : Segera cek Halaman Admin, penduduk atas nama [nama_penduduk] telah mengajukan [judul_surat] melalui [melalui] pada tanggal [tanggal] TERIMA KASIH.  

tidak tersedia alternatif link yang diberikan untuk segera akses ke surat tersebut sehingga pengguna khususnya kepala desa yang akan melakukan tanda tangan akan sulit mencari surat berdasarkan notifikasi tersebut jika suratnya banyak.

### Jelaskan solusi yg diinginkan

Tambahkan alur dimana, 
1. Surat dibuat oleh perangkat desa dan diverifikasi ke kades
2. lalu di sisi kadesmendapat notifikasi melalui telegram bahwa ada surat yang perlu di tanda tangan digital dengan link alternatif
3. ketika Kades klik link tersebut kades perlu diminta login jika sudah login sebelumnya maka langsung diarahkan ke halaman surat berdasarkan surat notifikasi
4. dihalaman surat tersebut kades diminta verifikasi ulang 
5. lalu ketika kades verifikasi surat kades masih di halaman yang sama dan auto muncul popup untuk masukkan passphrase
6.  sehingga kades tidak perlu harus ke halaman daftar surat untuk klik passphrase kembali

Proses no 5 juga berlaku jika kades melakukannya melalui tahapan : 
1. login ke OpenSID
2. lalu ke daftar surat / arsip surat
3. pilih surat yang perlu verifikasi
4. lalu ketika kades verifikasi surat kades masih di halaman yang sama dan auto muncul popup untuk masukkan passphrase

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

2310.0.0 Premium

### Informasi tambahan

Alur diatas pengerjaannya tidak bergantung pada demo TTE sehingga tetap bisa di kerjain tanpa demo akun tte.

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2912
