### ISSUE TITLE
Bug/error: Notifikasi gagal pada select2 tetap tampil walau sudah diisi

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#7134]
### Jelaskan error yg dialami

Pada kasus penggunaan inputan berupa select2, jika terjadi gagal input maka akan menampilkan notifikasi misalnya **kolom ini diperlukan**. Namun setelah di isi, notifikasi tsb tidak hilang.

### Cara untuk mereplikasi errornya

1. Masuk modul penduduk
2. Tambah / ubah salah 1 data penduduk
3. Pada Hubungan Dalam Keluarga (atau inputan select2 lainnya) di kosongkan terlebih dahulu
4. Tekan simpan
5. Maka akan di arahkan pada kolom tsb dengan notifikasi
6. Isi kolom tsb, namun notifikasi gagal tetap tampil

### Hasil yg diharapkan

Normal, seperti isian lainnya. Jika sudah diisi sesuai, maka notifikasi juga hilang.

### Tangkapan layar dan log error

<img width="387" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/09cd7198-322e-48a3-b68e-cd92dfe45484">

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v2309.0.0-premium

### Tema Yang Digunakan

bawaan

### Informasi tambahan

Cek validasi untuk notifikasi yang menggunakan select2.

**Comment by agungsugiarto** [comment]
saya tidak mengalami masalah yang dimaksud mas @andifahruddinakas, bisa diskusi nanti terkait issue ini?

**Comment by andifahruddinakas** [comment]
mas @agungsugiarto, itu sudah ada jelas di alurnya.

ini sy buatkan video untuk memperjelas.
![select2](https://github.com/OpenSID/OpenSID/assets/57283157/30d96d86-c04c-4075-a48b-ea564d3b56c3)

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2921
