### ISSUE TITLE
Buku Administrasi Umum - Buku Inventaris dan Kekayaan Desa kosong

### ISSUE THREAD

**Issue by rockymakasar** [OpenSID/OpenSID#7136]
### Jelaskan error yg dialami

Sudah input di Menu Inventaris namun di Buku Administrasi Umum - Buku Inventaris dan Kekayaan Desa masih kosong
(di berputar juga sama)

### Cara untuk mereplikasi errornya

![image](https://github.com/OpenSID/OpenSID/assets/94730877/0bc89238-b5bc-4347-8643-af3a643ec11c)

![image](https://github.com/OpenSID/OpenSID/assets/94730877/fdb8177f-d2dd-4bc1-88cd-c15a51cd6d3f)

### Hasil yg diharapkan

kembali normal

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2309.0.2-premium

### Tema Yang Digunakan

-

### Informasi tambahan

-

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2920
