### ISSUE TITLE
Bug/error: Artikel yg berisi video dari Responsive Filemanager, tidak bisa berputar, hanya keluar script

### ISSUE THREAD

**Issue by mah-mudi** [OpenSID/OpenSID#7138]
### Jelaskan error yg dialami

Artikel yg berisi video dari Responsive Filemanager, tidak bisa berputar, hanya keluar script

### Cara untuk mereplikasi errornya

1. artikel
2. tambah artikel
3. upload video di responsive file manager
4. simpan artikel

### Hasil yg diharapkan

Artikel yg berisi video dari Responsive Filemanager, dapat berputar ketika simpan artikel

### Tangkapan layar dan log error

https://github.com/OpenSID/OpenSID/assets/57661283/ee42ebe8-be34-4592-9342-67cf00876fbe

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

23.09.02

### Tema Yang Digunakan

natra

### Informasi tambahan

https://berputar.opendesa.id/

**Comment by andifahruddinakas** [comment]
Duplicate of https://github.com/OpenSID/OpenSID/issues/7113
