### ISSUE TITLE
Bug/error: Surat Keterangan Pindah F-1.03 pemohon yang muncul selalu Kepala Keluarga

### ISSUE THREAD

**Issue by hirudi** [OpenSID/OpenSID#7143]
### Jelaskan error yg dialami

Ketika membuat surat keterangan pindah F.103, pemohon yang muncul di pengantarnya sudah benar tetapi yang di Formulir F-1.03 selalu nama Kepala Keluarga padahal yang mengajukan anggota keluarga.

![Pengantar sudah Betul](https://github.com/OpenSID/OpenSID/assets/4936934/206f1c3d-bd06-4325-b6c3-18e80e73bd2c)

![Pemohon selalu muncul kepala keluarga](https://github.com/OpenSID/OpenSID/assets/4936934/921c62b0-2eda-4013-96f5-e417720a3f05)

### Cara untuk mereplikasi errornya

---

### Hasil yg diharapkan

F-1.03 Sesuai dengan Pengantarnya

### Tangkapan layar dan log error

---

### Rilis Versi OpenSID

Rilis Umum

### Versi OpenSID

v2309.0.0

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2931
