### ISSUE TITLE
Mohon Di Tambahkan Format Surat F-2.49 

### ISSUE THREAD

**Issue by kayangan** [OpenSID/OpenSID#715]
Formulir Pelaporan Pembetulan Untuk Akta, Pembetulan KK, Pembetulan KTP
![img_20171117_105709](https://user-images.githubusercontent.com/32614693/32972608-cb3d3294-cc25-11e7-8438-f9a1d183093d.jpg)

**Comment by metalab25** [comment]
@kayangan : Itu setiap kotak kolom isian harus diisi tiap kotak 1 huruf atau bisa di tulis misalnya nama diisi dikotak kolom panjang ????

Lalu apakah si pelapor itu adalah penduduk yang bersangkutan atau bisa peapornya orang lain ?

**Comment by opensidserver** [comment]
Diatur oleh produk hukum Permendagri No 19 Tahun 2010: 
[permendagri-19-tahun-2010-ttg_formulirbukupendaftaranpendudukpencatatansipil.pdf](https://github.com/OpenSID/OpenSID/files/1564618/permendagri-19-tahun-2010-ttg_formulirbukupendaftaranpendudukpencatatansipil.pdf)

Petunjuk pengisian:

![permendagri-19-tahun-2010-ttg_formulirbukupendaftaranpendudukpencatatansipil](https://user-images.githubusercontent.com/31242214/34069121-1fc3b12e-e29e-11e7-9c94-c07ac6029e7a.png)

**Comment by metalab25** [comment]
Sepertinya issue ini juga perlu di prioritaskan
