### ISSUE TITLE
Bug/error: Navigasi tidak berfungsi pada halaman data-wilayah

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#7156]
### Jelaskan error yg dialami

https://beta.opendesa.id/data-wilayah

akses statistik tersebut maka navigasi tidak bisa diklik.

namun normal ketika buka statistik yang lain.

### Cara untuk mereplikasi errornya

di atas

### Hasil yg diharapkan

normal seperti sebelumnya

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Beta

**Comment by andifahruddinakas** [comment]
pak @ariandii, navigasi yang mana dimaksud pada issue ini.

<img width="819" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/86102b72-144c-4f28-a65c-29db83a9d2f0">

**Comment by ariandii** [comment]
sesuai PR tersebut ada di Esensi.

**Comment by ariandii** [comment]
https://github.com/OpenSID/premium/commit/ad029db8bd681ed8a53ec2ca5041f0c1a3d9efc3#diff-0faa85c9605248e75509590176cbb046245704f5e8cf24c40459a294acd0a9f3

**Comment by andifahruddinakas** [comment]
> sesuai PR tersebut ada di Esensi.

oh, di Esensi. dibeta pakai natra pantas tidak ketemu. OK

**Comment by andifahruddinakas** [comment]
pada bagian navigasi tidak dapat dipilih

<img width="959" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/2631c565-8ec3-4b72-a7b8-2f413a60b18e">

**Comment by ariandii** [comment]
> pada bagian navigasi tidak dapat dipilih
> 
> <img alt="image" width="959" src="https://user-images.githubusercontent.com/57283157/271519873-2631c565-8ec3-4b72-a7b8-2f413a60b18e.png">

navigasi Statistik Penduduk dan Statistik Keluarga tidak bisa diklik.

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui commit https://github.com/OpenSID/premium/commit/007e234ae80e2b6f4ae2d40986813644dfae5bc4
