### ISSUE TITLE
Pengertian back-end dan front-end

### ISSUE THREAD

**Issue by abdulrokim** [OpenSID/OpenSID#716]
Dalam halaman utama demo OpenSID ini ada pernyataan sebagai berikut: "Website desa ini memiliki fungsi yang terbagi dalam dua bagian, yakni bagian depan (front-end) yang bisa diakses oleh publik dan bagian dalam (back-end) yang hanya bisa diakses oleh administrator sistem."

Menurut pengetahuan saya, pengertian front-end dan back-end tidak seperti itu. Mohon diperhatikan lagi. Trims.

**Comment by eddieridwan** [comment]
@abdulrokim silakan usulkan kata2 penggantinya. Kata2 itu sdh ada sejak SID 3.04 dahulu kala.

**Comment by RedhoAri** [comment]
Download Sid version 3.04 dimana om?
Jika om berkenan kirim link atau program
Ke email saya. redhoarimeratno12@gmail.com

**Comment by eddieridwan** [comment]
Kata2 'front-end' dan 'back-end' telah dihapus dari halaman SID Home > SID.

Sudah dicommit ke master.
