### ISSUE TITLE
Bug/error: tambah dtks pada modul rumah tangga walu tidak ada akses pada modul tsb

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#7162]
### Jelaskan error yg dialami

Setelah mengatur grup tanpa adanya modul DTKS, namun pada modul rumah tangga fungsi terkait DTKS tetap tampil,

### Cara untuk mereplikasi errornya

1. Buat Grup dengan akses tanpa modul DTKS, tambahkan modul rumah tangga paling utama di issue ini.
2. Buat user berdasarkan modul tsb
3. Login menggunakan user yang dibuat
4. Masuk modul rumah tangga
5. Terlihat tombol tambah DTKS masih ada, padahal tidak ada akse modul

### Hasil yg diharapkan

sesuai akses yg diberikan

### Tangkapan layar dan log error

<img width="678" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/2f7a7635-6e64-4b82-bd76-7125d0cc1f8b">

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v2310.0.0-premium

### Tema Yang Digunakan

bawaan

### Informasi tambahan

Cek : 
- [ ] batasi tombol tambah dtks jika ada akses tambah/ubah modul dtks
- [ ] selain view, batasi akses secara langsung dari url

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melalui pr https://github.com/OpenSID/premium/pull/2961
