### ISSUE TITLE
Permintaan fitur: Sediakan Fitur Data Dinamis Penduduk Luar Desa

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#7163]
### Apa kekurangan yg ingin diatasi?

Belum ada pengaturan data dinamis untuk penduduk luar desa pada surat jenis tinymce

### Jelaskan solusi yg diinginkan

Adanya pengaturan agar bisa memilih menggunakan : 
- [ ] penduduk desa
- [ ] penduduk luar desa
- [ ] penduduk desa dan penduduk luar desa

### Apakah ada alternatif lain

tidak ada

### Untuk versi OpenSID mana

v2310.0.0-premium

### Informasi tambahan

Batas issue ini hanya untuk menambahkan pengaturan saja, untuk penerapannya bisa dikerjakan di issue https://github.com/OpenSID/OpenSID/issues/7060

**Comment by agungsugiarto** [comment]
mas @andifahruddinakas, pengaturannya untuk masing-masing surat tinymce atau global seperti halnya pengaturan font?

**Comment by andifahruddinakas** [comment]
> mas @andifahruddinakas, pengaturannya untuk masing-masing surat tinymce atau global seperti halnya pengaturan font?

masing2 surat

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2969
