### ISSUE TITLE
Bug/error: Alamat Link sama antara pakai akhiran /first (saja) maupun tidak

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#7167]
### Jelaskan error yg dialami

saat ini akses website pakai URL akhiran /first dan tidak sama sama menghasilkan halaman utama.

### Cara untuk mereplikasi errornya

akses alamat web pakai /first maupun tidak.

### Hasil yg diharapkan

ketika URL diakses /first saja, maka dapat dialihkan ke URL utama

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Seluruhnya

**Comment by agungsugiarto** [comment]
Tidak bisa diterapkan / belum ketemu caranya, codeigniter3 belum tersedia fitur ini.

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2956
