### ISSUE TITLE
Bug/error: Drag & Drop files pada insert file tidak berfungsi

### ISSUE THREAD

**Issue by mah-mudi** [OpenSID/OpenSID#7169]
### Jelaskan error yg dialami

Drag & Drop files pada insert file tidak berfungsi

### Cara untuk mereplikasi errornya

1. artikel
2. insert file
3. drag drop file tidak berfungsi

### Hasil yg diharapkan

Drag & Drop files pada insert file dapat berfungsi sebagaimana mestinya seperti 23.09 premium

### Tangkapan layar dan log error

https://github.com/OpenSID/OpenSID/assets/57661283/cc72e398-0a33-4392-9e9e-e17bb9dcc4d1

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

23.10.0.0-premium

### Tema Yang Digunakan

esensi

### Informasi tambahan

https://berputar.opendesa.id/

**Comment by andifahruddinakas** [comment]
saya coba https://berputar.opendesa.id/web/form tidak menemukan masalah ini.

https://github.com/OpenSID/OpenSID/assets/57283157/486ee5ef-eeeb-44ec-aad5-f9fe21f06970

**Comment by mah-mudi** [comment]
@andifahruddinakas drag drop nya gak bisa jika di drag drop ke folder

**Comment by andifahruddinakas** [comment]
> @andifahruddinakas drag drop nya gak bisa jika di drag drop ke folder

Silahkan masuk ke folder yang akan di drop filenya terlebih dahulu. RFM hanya menyediakan fungsi drop pada halaman yg terbuka. sama halnya dengan libarary dropzone.
