### ISSUE TITLE
Bug/error: Gagal menyimpan pdf, jika judul berisi karakter / pada Buku Keputusan Kepala Desa

### ISSUE THREAD

**Issue by mah-mudi** [OpenSID/OpenSID#7170]
### Jelaskan error yg dialami

Gagal menyimpan pdf, jika judul berisi karakter / pada Buku Keputusan Kepala Desa

### Cara untuk mereplikasi errornya

1. Buku Administrasi Umum
2. Buku Keputusan kepala Desa

### Hasil yg diharapkan

Dapat menyimpan pdf, jika judul berisi karakter / pada Buku Keputusan Kepala Desa

### Tangkapan layar dan log error

https://github.com/OpenSID/OpenSID/assets/57661283/be194ccc-56b5-41f0-aeec-fadb0523bc0d

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

23.10.0.0-premium

### Tema Yang Digunakan

esensi

### Informasi tambahan

berputar.opendesa.id

**Comment by andifahruddinakas** [comment]
karakter '/' tidak di ijikan dalam penamaan file, karena akan terbaca sebagai directory. Silahkan ubah nama file sebelum diunggah.

Tambah data
<img width="542" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/d54f3de4-de1b-4251-be5b-49d7e25c08dc">

Penamaan file
<img width="308" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/44772b37-178a-4413-87ac-75c1670ba0d7">

**Comment by mah-mudi** [comment]
@andifahruddinakas dulu tahun 2020 masih bisa ngisi judul yg ada karakter garis miring nya
![image](https://github.com/OpenSID/OpenSID/assets/57661283/37e95438-713f-4b3c-a624-a1bf83b36913)

**Comment by andifahruddinakas** [comment]
> @andifahruddinakas dulu tahun 2020 masih bisa ngisi judul yg ada karakter garis miring nya ![image](https://user-images.githubusercontent.com/57661283/272506411-37e95438-713f-4b3c-a624-a1bf83b36913.png)

mas @mah-mudi, cek komentar https://github.com/OpenSID/OpenSID/issues/7170#issuecomment-1746067388

yg bermasalah pada updload filenya. untuk judulnya tetap bisa masukkan '/'

**Comment by mah-mudi** [comment]
@andifahruddinakas divideo sudah saya sampaikan, nama file sama tanpa karakter /, eror nya di nama judul.
bukan nama file yg diupload
