### ISSUE TITLE
cetak surat tinyMCE ketika pilih TTD selain kepala desa 

### ISSUE THREAD

**Issue by mranca** [OpenSID/OpenSID#7172]
### Jelaskan error yg dialami

setiap cetak surat tinyMCE ketika pilih TTD selain kepala desa, maka otomatis yang tampil di tabel arsip surat  terecord di log_surat adalah id_pamong dan nama_pamong kepala desa

### Cara untuk mereplikasi errornya

.

### Hasil yg diharapkan

Nama yang TTD pada surat harus sesuai dengan tabel yang TTD pada arsip surat

### Tangkapan layar dan log error

.

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2310.0.0

### Tema Yang Digunakan

.

### Informasi tambahan

.

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2971
