### ISSUE TITLE
Bug/error: Tidak ada pilihan suku ketika input data KK masuk

### ISSUE THREAD

**Issue by mah-mudi** [OpenSID/OpenSID#7177]
### Jelaskan error yg dialami

Tidak ada pilihan suku ketika input data KK masuk

### Cara untuk mereplikasi errornya

Tambah KK
Pilihan Suku

### Hasil yg diharapkan

ada pilihan suku ketika input data KK masuk

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/57661283/0a18b899-23b9-4d01-b884-1218cf6ab6a8)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

23.10.0.0-premium

### Tema Yang Digunakan

esensi

### Informasi tambahan

berputar.opendesa.id

**Comment by andifahruddinakas** [comment]
sy coba beberapa kali 

https://berputar.opendesa.id/keluarga/form_peristiwa_a/5/1/1/41
<img width="960" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/f926bfd2-785b-4e5a-aa6d-163e8b6cf310">

https://berputar.opendesa.id/keluarga/form_peristiwa/5
<img width="956" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/e62f383c-cf0d-4863-b7c2-c6b2d73b6b7f">

[suku.webm](https://github.com/OpenSID/OpenSID/assets/57283157/72ace263-2f51-42d8-8df8-5866131a61b9)

Silahkan di bukan kembali jika masih ditemukan hal demikian, bisa lakukan dimode incognito.

**Comment by mah-mudi** [comment]
coba sampeyan isi data pada penmbahan KK, jgn langsung pilih suku/etnis.

https://github.com/OpenSID/OpenSID/assets/57661283/36e06555-6d3b-4ed9-bd94-2b844d267bdb

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/3001
