### ISSUE TITLE
Bug/error: Semua Statistik Bantuan Tidak tampil di WEB

### ISSUE THREAD

**Issue by syahransaputra** [OpenSID/OpenSID#7178]
### Jelaskan error yg dialami

Ketika mengakses menu Statistik Bantuan di WEB [Penerima Bantuan Penduduk](https://berputar.opendesa.id/first/statistik/bantuan_penduduk), [Penerima Bantuan Keluarga](https://berputar.opendesa.id/first/statistik/bantuan_keluarga) maupun [BPNT](https://berputar.opendesa.id/first/statistik/501) tidak menampilkan data namun di Dashboard admin Statistik Program Bantuan ada datanya

### Cara untuk mereplikasi errornya

1. Pertama2 pastikan data benar ada di di Dasboard admin https://berputar.opendesa.id/statistik/clear/bantuan_penduduk
2. jika ada silahkan buka https://berputar.opendesa.id/first/statistik/bantuan_penduduk
3. maka data yang diharapkan tidak tampil

### Hasil yg diharapkan

Seharusnya data tersebut tampil di Halaman Web

### Tangkapan layar dan log error

<img width="1161" alt="Jepretan Layar 2023-10-08 pukul 02 48 46" src="https://github.com/OpenSID/OpenSID/assets/26229332/d8e4e8ab-da80-4c05-8035-532565b8e29d">
<img width="1448" alt="Jepretan Layar 2023-10-08 pukul 02 49 17" src="https://github.com/OpenSID/OpenSID/assets/26229332/6008c20a-a66e-4a87-9c9d-e5eb710adcf8">

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v2310.0.0-premium

### Tema Yang Digunakan

Esensi v22.11

**Comment by andifahruddinakas** [comment]
Duplicate of https://github.com/OpenSID/OpenSID/issues/7174
