### ISSUE TITLE
Request:Ambil Foto Penduduk Menggunakan WebCam/Camera Eksternal

### ISSUE THREAD

**Issue by ciqwan** [OpenSID/OpenSID#718]
Untuk data Foto setiap penduduk, yang tengah berjalan diambil melalui Upload gambar secara manual yang fotonya bisa melalui scan atau difoto manual via HP or camera.
Untuk kemudahan pengambilan data foto,, bisa dipikirkan untuk ambil fotonya secara langsung melalui kamera yang terhubung ke Komputer, sama seperti aplikasi rekam e-KTP. pada aplikasi tinggal tambahkan Button ambil foto via Camera, kemudian hasil fotonya disimpan kedalam aplikasi.
Dan ini mungkin akanlebih praktis dalam ambil data foto setiap penduduk.

**Comment by MUHAMMADRANGSEL** [comment]
Usulan yg mqntap

**Comment by RedhoAri** [comment]
Download Sid version 3.04 dimana om?
Jika om berkenan kirim link atau program
Ke email saya. redhoarimeratno12@gmail.com

**Comment by eddieridwan** [comment]
Fitur foto penduduk ada di SISMINDUK.

**Comment by afa28** [comment]
Duplicate #3994
