### ISSUE TITLE
Bug/error: Pengaturan telegram masing2 pengguna

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#7180]
### Jelaskan error yg dialami

Pengaturan notifikasi telegram pada masing2 pengguna masih aktif walaupun pada pengaturan aplikasi tidak di aktifkan.

### Cara untuk mereplikasi errornya

1. Masuk pada modul pengaturan aplikasi, matikan notifikasi pengaturan
2. Masuk ke podul penggun, tambah/ubah pengguna
3. Cek pada bagian bawah, terdapat inputan notifikasi masih tampil walau tidak bisa di tambahkan/diubah

### Hasil yg diharapkan

Buat konsisten dengan modul lain untuk masalah aktif non aktif untuk inputan bertingkat.
- [ ] jika pengaturan aplikasi di atur tidak, hilangkan inputan Notifikasi Telegram dan User ID Telegram
- [ ] jika pengaturan aplikasi di atur ya, tampilkan inputan Notifikasi Telegram dan User ID Telegram
- [ ] pastikan jika pengaturan aplikasi di atur tidak, dan melakukan simpan, data lama tidak terhapus
- [ ] pastikan notifikasi jalan jika pengaturan pengaturan aplikasi dan pengguna di atur ya
- [ ] hapus `Untuk mengaktifkan notifikasi telegram, harap masukkan token telegram di modul setting aplikasi ` karena sudah disesuaikan pada pengaturan aplikasi alurnya

### Tangkapan layar dan log error

<img width="514" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/5abef86b-e54b-4cda-ae32-681e66a2ebe3">

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v2310.0.0

### Tema Yang Digunakan

bawaan

### Informasi tambahan

.

**Comment by pandigresik** [comment]
Apakah semua notifikasi telegram akan dikirimkan ke semua pengguna yang mengaktifkan notifikasi telegram ? Sekilas untuk saat ini notifikasi hanya dikirimkan ke user_id_telegram yang terdaftar di pengaturan aplikasi saja

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2978
