### ISSUE TITLE
Bug/error: Buku Tamu Semua Dropdown menjadi ganda

### ISSUE THREAD

**Issue by syahransaputra** [OpenSID/OpenSID#7183]
### Jelaskan error yg dialami

Setelah mengisi Nama pindah ke Input No. Telp/HP dan semua dropdown terlihat ganda

### Cara untuk mereplikasi errornya

1. masuk ke anjungan
2. klik buku tamu
3. isi Nama
4. isi nomor
5. dan terlihat errornya dropdown terlihat ganda semua

### Hasil yg diharapkan

perbaikan

### Tangkapan layar dan log error

<img width="1710" alt="Jepretan Layar 2023-10-09 pukul 19 36 00" src="https://github.com/OpenSID/OpenSID/assets/26229332/f9b043f2-e84b-4cdd-8e02-946fa4b9418c">

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v2310.0.0-premium

### Tema Yang Digunakan

bawaan

**Comment by andifahruddinakas** [comment]
[buku tamu.webm](https://github.com/OpenSID/OpenSID/assets/57283157/d6429a9e-604a-42de-a828-fe74271b6270)

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2968
