### ISSUE TITLE
Buat tabel log Notifikasi

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#7185]
Perlu adanya tabel untuk menyimpan data log Notifikasi.

Struktur : 
- id
- title
- lastMessage
- timestamp

Mas @apidong, kalau kurang sesuai bisa disesuaikan saat ngoding.

Referensi : 
https://firebase.google.com/docs/database/admin/structure-data?hl=id

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/2992
