### ISSUE TITLE
Modul Kirim API Push notifikasi ke FCM

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#7186]
Perlu adanya modul Kirim API Push notifikasi ke FCM, untuk : 
- [ ] Surat dibuat
- [ ] Surat disetujui
- [ ] Surat di tolak

**Comment by apidong** [comment]
cara kirim notifikasi memakai postman

Endpoint : https://fcm.googleapis.com/fcm/send
Method : POST
Headers :-
    -Authorization : key=<keyserver>
    -Content-Type : application/json

```
body :
  {
      "priority": "HIGH",
      "notification" : {
      "title" : "title",
      "body" : "isi"
  },
      "data": {
          "payload": <route>,
      },
    "to": "token_device"
  }

```
refrensi https://apoorv487.medium.com/testing-fcm-push-notification-through-postman-terminal-part-1-5c2df94e6c8d

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/3018
