### ISSUE TITLE
Bug/error: log_penduduk

### ISSUE THREAD

**Issue by afri18** [OpenSID/OpenSID#7187]
### Jelaskan error yg dialami

pertama kali input data penduduk dari menu KK input data anggota masuk berjalan normal, hanya di pilihan suku tidak menampilkan pilihan. Hasil di log_penduduk>tgl peristiwa sesuai dengan yang di input.
Saat edit biodata dari menu KK>Rincian Anggota Keluarga>edit biodata
Pilihan Suku/Bangsa muncul lalu simpan, nah saat simpan ini terjadi perubahan di
log_penduduk>tanggal peristiwa (tidak menampilkan saat mula di input berubah menjadi tanggal lahir)

### Cara untuk mereplikasi errornya

seharusnya saat edit biodata tidak berpengaruh pada log_penduduk>tanggal peristiwa

### Hasil yg diharapkan

Tanggal Peristiwa tidak berubah saat edit biodata

### Tangkapan layar dan log error

sesudah input pertama
![image](https://github.com/OpenSID/OpenSID/assets/6611881/460bb243-7cf6-4975-adb7-050a4ccbc728)

berubah saat edit biodata
![image](https://github.com/OpenSID/OpenSID/assets/6611881/aafc6682-8942-477f-a8ff-986d97a6b9ac)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2310.0.0

### Tema Yang Digunakan

denatra

### Informasi tambahan

harusnya tgl peristiwa tidak berubah kalau tidak di ubah

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2977
