### ISSUE TITLE
Format Tanggal pada isian layanan surat TinyMCE sebaiknya "DD-MM-YYYY"

### ISSUE THREAD

**Issue by luxmant354** [OpenSID/OpenSID#7193]
### Apa kekurangan yg ingin diatasi?

untuk saat ini ketika kita membuat layanan surat versi TinyMCE dengan isian tanggal / contoh tanggal lahir, hasilnya "YYYY-MM-DD" 
![Screenshot_5](https://github.com/OpenSID/OpenSID/assets/44687953/b257fb47-8856-4fff-921b-2a37111f374a)
sebagaimana contoh gambar terlampir

### Jelaskan solusi yg diinginkan

Karena umumnya untuk Indonesia pakai format DD-MM-YYYY maka sebaiknya disesuaikan dengan format tersebut. 

### Apakah ada alternatif lain

bisa disikapi menggunakan kode isian menggunakan Kode Teks biasa / **bukan format tanggal**

### Untuk versi OpenSID mana

2310.0.1-premium

**Comment by yogiperdana** [comment]
referensi untuk panduan: https://www.php.net/manual/en/datetime.format.php

**Comment by andifahruddinakas** [comment]
> referensi untuk panduan: https://www.php.net/manual/en/datetime.format.php

Pindahkan ke panduan cara penggunaan dengan bahasa indonesia agar mudah dimengerti.

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/3021
