### ISSUE TITLE
Bug/error: Ikon Hapus dan Tambah Tabel Saat Edit atau Buat Baru Surat TinyMCE tidak ada

### ISSUE THREAD

**Issue by Restony33** [OpenSID/OpenSID#7195]
### Jelaskan error yg dialami

Ikon Hapus dan Tambah Tabel Saat Edit atau Buat Baru Surat TinyMCE tidak ada
![2023-10-15_11h34_40](https://github.com/OpenSID/OpenSID/assets/104592011/eb824e3b-4bfb-4888-b7fb-84e228d607cb)

### Cara untuk mereplikasi errornya

1. Login Admin
2. Layanan Surat Kemudian Pengaturan Surat >> Tambah Surat

![2023-10-15_11h41_29](https://github.com/OpenSID/OpenSID/assets/104592011/ec207a33-5c84-4c6e-94c6-414e28c7cb64)

4. Pilih Template >> Salin Template >> Surat Raw TinyMCE >> Template Sistem
![2023-10-15_11h40_32](https://github.com/OpenSID/OpenSID/assets/104592011/1729e354-66c8-48e9-981d-25eeca3a6a51)
![2023-10-15_11h42_30](https://github.com/OpenSID/OpenSID/assets/104592011/a35e5091-479a-4ba0-beeb-ddddc86616cd)
5. Tidak Bisa Hapus atau Tambah Table
![2023-10-15_11h34_40](https://github.com/OpenSID/OpenSID/assets/104592011/4e35db13-8da3-41dc-89f1-d977ade4cdcb)

### Hasil yg diharapkan

Berjalan Normal
![2023-10-15_11h33_00](https://github.com/OpenSID/OpenSID/assets/104592011/c64df123-876c-412e-8e0f-fe2813a821e0)

### Tangkapan layar dan log error

![2023-10-15_11h34_40](https://github.com/OpenSID/OpenSID/assets/104592011/b524987d-a8a3-435c-959d-a7126d99c39e)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Versi 2310.0.1-premium

### Tema Yang Digunakan

Natra v22.11

### Informasi tambahan

.

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui commit https://github.com/OpenSID/premium/commit/8232fef03e3d90ac7063973a100ba46c5f00cdd8
