### ISSUE TITLE
Buat Surat Perintah Perjalanan Dinas

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#720]
Pemohon surat ini bisa dari warga atau non-warga.

Contoh surat yang di-share oleh Muhammad dari Rarang Selatan:
[surat_perintah_perjalanan_dinas.zip](https://github.com/OpenSID/OpenSID/files/1505841/surat_perintah_perjalanan_dinas.zip)

**Comment by RedhoAri** [comment]
Download Sid version 3.04 dimana om?
Jika om berkenan kirim link atau program
Ke email saya. redhoarimeratno12@gmail.com

**Comment by eddieridwan** [comment]
Bung @RedhoAri : issue di github bukan tempat bertanya. Silakan bergabung di https://www.facebook.com/groups/OpenSID dan bertanya di situ. Banyak yang bisa membantu di situ.

Issue tempat diskusi penerapan usulan pengembangan OpenSID.

**Comment by sukrimalendra** [comment]
Pak eddie di desa kami SPPD formatnya seperti ini 
[SPPD Pake.docx](https://github.com/OpenSID/OpenSID/files/1524006/SPPD.Pake.docx) mohon dibuatkan yang seperti file terlampir tersebut. Terimakasih

**Comment by eddieridwan** [comment]
@sukrimalendra @MUHAMMADRANGSEL, @afri18 apakah SPPD bagian dari menu Cetak Surat (Layanan) atau menu lain.

Kalau menu lain, di mana:

1. tempat membuat suratnya, apakah di Sekretariat > Surat Keluar atau menu terpisah?
2. apakah arsipnya di Sekretariat > Surat Keluar atau menu terpisah?

**Comment by MUHAMMADRANGSEL** [comment]
SPPD merupakan surat yg menyatu dengan surat layanan dan tdk terpisahkan
Krn yg dibuatkan merupakan perangkat desa yg merupakan warga desa setempat

Pada tanggal Min, 25 Mar 2018 20.00, Eddie Ridwan <notifications@github.com>
menulis:

**Comment by MUHAMMADRANGSEL** [comment]
Pengarsipan nya juga di surat keluar

Pada tanggal Min, 25 Mar 2018 20.00, Eddie Ridwan <notifications@github.com>
menulis:

**Comment by eddieridwan** [comment]
@MUHAMMADRANGSEL @afri18: apakah akan diperlukan laporan terpisah untuk SPPD? 
Apakah pengarsipan di menu Cetak Surat > Arsip Layanan atau di Sekretariat > Surat Keluar atau lainnya?

**Comment by MUHAMMADRANGSEL** [comment]
Cetak surat >>> arsip layanan
Pada tanggal Sen, 26 Mar 2018 05.45, Eddie Ridwan <notifications@github.com>
menulis:

**Comment by eddieridwan** [comment]
Dari @PHAKaryono (#674): 

Mohon dibuatkan Surat Tugas dan Surat Perjalanan Dinas dari 1(satu) hari sampai 5 (lima) hari
[SPPD Baru.docx](https://github.com/OpenSID/OpenSID/files/1376432/SPPD.Baru.docx)

**Comment by eddieridwan** [comment]
Bung @afri18, apakah anda setuju dengan pendapat @MUHAMMADRANGSEL?

**Comment by fathurvbf** [comment]
Kalau menurut saya harus terpisah dan penomoran harus terpisah. Sebab dalam sppd biasa ada biaya yg timbul. Dan pasti diambil dari dana add ataupun pad. Kalau 
Bisa masukkan dimenu skretariat. Knapa sperti itu. Setiap tahapan harus ada rekap laporan dalam bentuk cetak stidaknya fungsinya agar kades tau brapa spdd yg telah keluar dan kemana aja tujuan kegiatan dilakukukan. Shingga bisa diriview

**Comment by HerryWanda** [comment]
Kalo menurut saya , memang harus dipisahkan... jangan disatukan di arsip layanan dan masukkan dimenu sekretariat di Surat Keluar.
Kalo di Nagari / Desa di Sumatera Barat Surat Keterangan dibedakan dengan surat keluar Dinas, 
Kalo surat keterangan termasuk kedalam "REGISTRASI UMUM"
Sedang Surat seperti SPPD merupakan Registrasi Dinas, 
Jadi lebih baik SPPD penomoran dan pengarsipannya terpisah..

**Comment by afri18** [comment]
setuju dengan @HerryWanda

**Comment by afri18** [comment]
surat LAYANAN dengan surat SPPD di bedakan, SPPD bag dari surat perjalanan dinas mutlak sekretariat

**Comment by sarolangun** [comment]
saya sudah buat kan Format SPPD tapi baru lampiran SURAT PERINTAH TUGASNYA untuk lampiran SPPDnya blm sempat pada get lampiran

**Comment by eddieridwan** [comment]
Berikut ini SPPD buatan https://www.facebook.com/profile.php?id=100007193074639 Bagoes Sarolangun: https://www.dropbox.com/s/niiaoz9tokebcov/surat_sppd.rar?dl=0&fb=1.

**Comment by eddieridwan** [comment]
Sebelum fitur ini diterapkan, sebaiknya membuat konsep dulu: 

- alur proses SPPD
- menu
- form
- laporan

**Comment by afri18** [comment]
kalau menurut pendapatnsaya SPPD nya yang berupa pengantar aja, sedangkan timbulnya biaya karna sppd ini diserahkan di bagian bendahara, termsuk jenis surat keuangannya, jadi opensid murni mengelola admin sekretariat tentang surat

**Comment by eddieridwan** [comment]
SPPD sudah ditambahkan sebagai 'surat layanan' ke branch master melalui PR #2130. Tetapi masalah2 lain di atas belum ditangani. 

Template saat ini menggunakan nomor surat yg langsung dimasukkan sebagai `[kode_surat]/[nomor_surat]/64.07/20.2007/SK`. Jadi belum menggunakan setting aplikasi. Apakah format nomor surat untuk surat kantor desa seperti ini berbeda dengan format surat layanan?

**Comment by afri18** [comment]
Sama dengan surat layanan, yg membedakan jenis surat aja

**Comment by sukrimalendra** [comment]
Menurut saya pak @eddieridwan. Sppd ini terpisah dan terhubung dengan surat masuk. Jadi formnya beda. Isi dalam form “masukan nik lalu pilih surat masuk yg sudah dientri sebagai acuan dalam isian sppd. Yg diketik mungkin hanya lama perjalanan dinas dan nama pengikutnya.

**Comment by eddieridwan** [comment]
@sukrimalendra Surat SPPD sudah ada di rilis. Jadi issue ini akan kami tutup.

Silakan coba suratnya dan periksa. Sekiranya anda ada usul untuk perbaikan surat tersebut, silakan buat issue baru yang dilengkapi dengan penjelasan secara rinci apa yg perlu diubah.
