### ISSUE TITLE
Permintaan fitur: Proses Import Pindah Data atau Penggabungan data Pada Database Gabungan

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#7209]
### Apa kekurangan yg ingin diatasi?

Saat ini database gabungan sudah berjalan beberapa versi namun untuk penggabungan database yang sudah berjalan masih tetap tidak dapat di proses , hal ini akan menyulitkan jika ada pengguna baru dalam 1 kabupaten jika ingin menggunakan OpenKab.

### Jelaskan solusi yg diinginkan

Untuk penggabungan database maka ada beberapa langkah yang perlu di lakukan seperti : 
1. Tentukan Versi OpenSID yang akan di gabung
2. Samakan terlebih dahulu semua versi OpenSID sebelum digabung
3. Lalu setelah di update secara mandiri perlu backup database melalui OpenSID untuk masing -masing OpenSID yang akan di gabung
4. Lalu backup folder desa melalui aplikasi
5. Lalu install OpenSID baru dengan desa/kelurahan  yang akan di restore dengan database kosong
6. Lalu restore database & folder desa melalui OpenSID agar proses pegabungan dapat di lakukan oleh OpenSID

### Apakah ada alternatif lain

Proses solusi yang dinginkan seperti diatas namun perubahan yang perlu di terapkan adalah membuat algoritma dimana proses restore dapat menampung data dan mengelola data sehingga pada saat proses import yang di lakukan bukan dengan menghapus semua table melainkan menyimpan data yang tersedia lalu di eksekusi dengan menambah data sesuai dengan baris baru pada table yang sudah tersedia sebelumnya. 

teknologi diatas seperti import data dengan mneggunakan data csv ataupun json dimana bukan focus pada pembentukan ulang table melainkan update table dengan data yang baru dengan menambah di baris baru sehingga data yang sudah ada tidak terhapus. 

Syarat yang perlu dipertimbangan : 
1. Membuat / menyesuaikan config_id dengan app_key yang sudah tersedia pada table config 
2. Tentukan ketika restore folder desa maka akan ter restore ke folder desa pada desa yang ditujukan.
3. Tolak restore jika versi hasil backup tidak memiliki versi yang sama dengan versi OpenSID saat ini.

### Untuk versi OpenSID mana

2311.0.0

**Comment by vickyrolanda** [comment]
mas @agungsugiarto apakah issue ini sudah dibaca dan di pelajari mas, mohon kabari jika ada masukkan yang lebih baik dalam penerapannya dan mohon informasikan kira - kira lama pengerjaannya ya mas.

**Comment by agungsugiarto** [comment]
> Catatan
Untuk tahap awal library penggabungan database (python cli tool) hanya ditujukan untuk penanggung jawab admin aplikasi siap pakai. Kemudian pada tahap pengembangan selanjutnya library penggabungan database (python cli tool) akan di konversi ke bahasa pemrograman PHP dan terintegrasi ke aplikasi OpenSID (bakcend/ & frontend).

Petunjuk cara memakai script python cli tool

1. Copy file pada folder `bin\mysql_merge\config.py.example` ke `bin\mysql_merge\config.py`
2. Sesuaikan konfigurasi `merged_dbs` dan `destination_db` pada file `config.py`
3. Jalankan `python run.py`
