### ISSUE TITLE
Permintaan fitur: Sesuaikan data yang tampil untuk penduduk luar desa 

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#7219]
### Apa kekurangan yg ingin diatasi?

Saat ini pada pengaturan surat TinyMCE dibagian data individu seperti gambar dibawah terdapat pilihan data PENDUDUK DESA & PENDUDUK LUAR DESA namun dalam penerapannya saat ini jika dipilih PENDUDUK LUAR DESA masih menampilkan data penduduk dari dalam desa dimana seharusnya data yang akan tampil adalah form isian default untuk penduduk luar desa.
![image](https://github.com/OpenSID/OpenSID/assets/59082428/b92bcf2d-aacf-4935-8fed-512b9b336afb)
Berikut tampilan jika dipilih PNEDUDUK LUAR DESA 
![image](https://github.com/OpenSID/OpenSID/assets/59082428/2d777d28-9cf3-4385-ad3e-1d54da87dedb)

### Jelaskan solusi yg diinginkan

Seharusnya dalam penerapannya jika pada bagian form dipilih PENDUDUK LUAR DESA maka yang akan tampil ada form bawaan untuk mengisi data penduduk luar desa seperti berikut ini : 
![image](https://github.com/OpenSID/OpenSID/assets/59082428/7434a094-3d1d-45cb-985b-d9f4b06fd3ea)

sehingga fungsi pada pilihan data individu sesuai dengan tujuannya.

Solusi yang perlu diterapkan : 
1. Buat form isian bawaan untuk penduduk luar desa 
2. Tampilkan form isian sesuai jika dipilih penduduk luar desa
3. Sesuaikan Kode Isian yang di samakan dengan PENDUDUK DESA (harapannya tidak perlu ada penyesuaian jika penduduk dari dalam atau luar desa)

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

2310.0.0

**Comment by andifahruddinakas** [comment]
Sudah dikerjakan
