### ISSUE TITLE
Permintaan fitur: Tambahkan kondisi hubungan antara bagian form utama dengan bagian form tambahan

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#7220]
### Apa kekurangan yg ingin diatasi?

Ada kondisi dimana ketika pilih data akan di sesuaikan dengan kondisi tersebut (misalkan hubungan keluarga) maka ketika pilih data penduduk utama kepala keluarga lalu bagian form ke2 yang muncul hanya hubungan keluarga saja misalkan dibuat kondisi jika A maka munculkan form isian A , Jika B maka munculkan form isian B 

contoh penerapannya pada  Surat Keterangan Izin Orang Tua/Suami/Istri
![image](https://github.com/OpenSID/OpenSID/assets/59082428/304a2388-6a0b-4281-b164-15ed396a366c)

Sehingga perlu ada penyesuaian agar form bagian dapat saling berhubungan datanya.

### Jelaskan solusi yg diinginkan

Ketika menambahkan form bagian tambahkan satu pilihan pada bagian Sumber Data untuk memilih hubungan antar form, misalkan diberi judul Hubungan Data : maka muncul select (semua form bagian yang sudah ditambah tentu ada form bagian UTAMA yang secara default sudah ada karna bawaan) 
seperti berikut ini : 
![image](https://github.com/OpenSID/OpenSID/assets/59082428/428d90e9-a257-4c95-987f-75e05714418f)

maka form isian ini yang akan menjadi trigger untuk dapat memilih hubungan antara 1 form bagian ke 1 form bagian. 

Yang perlu tambah: 
1. Form Hubungan data pada Sumber Data
2. Tampilkan isi dari hubungan data sesuai form bagian yang telah ditambah 
3. Buat logika penerapan pada bagian cetak surat dimana ketika memilih penduduk dari form utama, akan ke tigger ke form bagian ke 2.

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

2311.0.0

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/3022
