### ISSUE TITLE
Permintaan fitur: Penambahan kode isian untuk inputan non-warga secara bawaan

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#7221]
### Apa kekurangan yg ingin diatasi?

Dalam penerapan surat terdapat wali , saksi dll dimana inputan yang dibutuhan adalah inputan warga, maka diperlukan form isian non-warga agar dapat ditempat kan sesuai kebutuhan surat lainnya.

Penerapannya seperti ini : 
![image](https://github.com/OpenSID/OpenSID/assets/59082428/46327158-9790-4f32-bdc5-b403259cc777)

### Jelaskan solusi yg diinginkan

maka perlu ditambah pada bagian kode isian dimana ada pilihan "Form Individu Warga" atau istilah lainnya dimana ketika pilih form dengan kode isian tersebut maka form yang akan di tampilkan bisa secara default serprti ini : 

![image](https://github.com/OpenSID/OpenSID/assets/59082428/23ee968b-d63c-4e7d-a910-6c240ffdf3e1)

 Maka akan tampil di bagian buat surat seperti ini : 
 
![image](https://github.com/OpenSID/OpenSID/assets/59082428/8444eaa7-9d13-48f1-8ef4-b7569eff55e2)
 

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

2311.0.0

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/3028
