### ISSUE TITLE
Permintaan fitur: Tambahkan kondisi agar dapat memilih kode isian dalam memilih sesuai dengan kondisi

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#7224]
### Apa kekurangan yg ingin diatasi?

Saat ini kode isian berdisi sendiri dimana tidak dapat menjadi parameter untuk menampilkan kode isian tertantu , misalkan pada pilihan form tertentu dapat di isi atau tidak diisi sesuai dengan kodisi , misalkan pada surat Nikah, terpadat pilihan Jika pria, terangkan jejaka, duda atau beristri : setiap pilihan menentukan form apa yang perlu diisi  kondisi ini untuk mengurangi jumlah form isian dan berkaitan pada lampiran. 

![image](https://github.com/OpenSID/OpenSID/assets/59082428/805264ae-1334-4722-9413-44da73753e86)

### Jelaskan solusi yg diinginkan

1. Tambahkan fungsi "kaitkan" 
![image](https://github.com/OpenSID/OpenSID/assets/59082428/d1da41ae-f877-4c39-a37a-01a60fa62b1a)
2. Akan muncul pop-up seperti berikut ini : 
![image](https://github.com/OpenSID/OpenSID/assets/59082428/f0e72961-6c41-4e4f-ba81-e4fee9455eb3)
akan ada 2 isian yang perlu di isi pertama tentukan value yang akan di jadikan parameter 
yang ke 2 adalah form isian yang akan di kaitkan , kondisi di poin ini dapat ditambah dinamis sesuai value yang akan dikaitkan jadi bisa 2 kondisi. Jika ini diterapkan maka value yang sudah dibuat kondisi tidak dapat ditambahkan kondisi lain lagi. 

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

2311.0.0

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/3025
