### ISSUE TITLE
Permintaan fitur: Buat susunan layout Form Isian pada pengaturan surat TinyMCE

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#7226]
### Apa kekurangan yg ingin diatasi?

1. Saat ini urutan form isian yang tampil pada cetak surat melalui urutan kode isian ditambahkan
2. Menjadi baku jika kode isian di isi tidak sesuai urutan 
3. dan sulit untuk menentukan urutan form isian dan harus membuat ulang  jika sudah terlanjut ditambahkan 

### Jelaskan solusi yg diinginkan

Tambah 1 tab pada bagian form seperti gambar berikut ini : 
![image](https://github.com/OpenSID/OpenSID/assets/59082428/4dd76556-72a0-4de0-b677-d691d0b44a09)

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

2311.0.0

**Comment by pandigresik** [comment]
Mirip dengan issue https://github.com/OpenSID/OpenSID/issues/7201
