### ISSUE TITLE
Permintaan fitur: Tambahkan kodisi form isian yang berkaitan dengan lampiran yang digunakan 

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#7227]
### Apa kekurangan yg ingin diatasi?

pada surat TRF ada kondisi dimana lampiran akan digunakan untuk form isian tertentu dan tergantung kondisinya hal ini diterapkan pada surat NIKAH dimana banyak lampiran yang tidak dipelukan juga akan tampil padahal tidak diperlukan. 

pada surat TinyMCE sudah diterapkan namun masih bersifat statis, bisa di replikasi menggunakan surat TinyMCE Keterangan Nikah.

### Jelaskan solusi yg diinginkan

Penerapan issue ini bisa di kerjakan jika issue ini juga di terapkan : https://github.com/OpenSID/OpenSID/issues/7224
maka bisa ditambahkan lampiran di setiap kondisi dari issue tersebut. 

dan juga bisa ditambahkan pada form bagian. 
sehingga lampiran bisa digunakan berdasarkan Form Bagian & juga berdasarkan Form Isian

### Apakah ada alternatif lain

Alternatif ini bisa diterapkan dengan motode lain jika diperlukan ata punya tahapan yang lebih sederhana.

### Untuk versi OpenSID mana

2311.0.0

**Comment by pandigresik** [comment]
Jika lampiran mengikuti inputan field seperti fitur field yang berelasi maka akan mengubah proses penentuan lampiran yang selama ini telah berjalan. Saat ini lampiran ditentukan di pengaturan utama surat tersebut bukan di dalam field inputan. Jadi sepertinya perlu dicek kembali issue ini untuk solusi penerapannya
