### ISSUE TITLE
Bug/error: Belum adanya pilihan ubah status dasar bagi penduduk yg mutasi pindah, lalu mau balik ke desa asal

### ISSUE THREAD

**Issue by mah-mudi** [OpenSID/OpenSID#7228]
### Jelaskan error yg dialami

Belum adanya pilihan ubah status dasar bagi penduduk yg mutasi pindah, lalu mau balik ke desa asal

### Cara untuk mereplikasi errornya

1. penduduk
2. setelah mutasi keluar/pindah
3. data penduduk pindah jika mau masuk kembali ke desa asal, tidak bisa karena tidak ada pilihan ubah status dasar

### Hasil yg diharapkan

adanya pilihan ubah status dasar bagi penduduk yg mutasi pindah, sehingga bisa balik ke desa asal

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/57661283/2d04a75b-5462-4832-81bb-720ea3561d47)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

23.10.0.2-premium

### Tema Yang Digunakan

natra

### Informasi tambahan

https://berputar.opendesa.id

**Comment by andifahruddinakas** [comment]
Sudah ada sebelumnya pada log penduduk.

<img width="724" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/916cda12-e03f-4d06-b63a-eadb4f6bf804">

Namun terdapat persyaratan, sbb : 
- [ ] penduduk yg bisa dinyatakan kembali masuk jika sudah lebih 1 bulan.
- [ ] jika belum cukup 1 bulan, bisa gunakan kembalikan status.
