### ISSUE TITLE
Bug/error: Ukuran Gambar Visual Pada Pengaturan Tinggi Lebar, tidak berfungsi

### ISSUE THREAD

**Issue by mah-mudi** [OpenSID/OpenSID#7229]
### Jelaskan error yg dialami

Ukuran Gambar Visual Pada Pengaturan Tinngi Lebar, tidak berfungsi

### Cara untuk mereplikasi errornya

1. pengaturan surat
2. pengaturan TTE

### Hasil yg diharapkan

Ukuran Gambar Visual Pada Pengaturan Tinngi Lebar, dapat berfungsi

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/57661283/6b571f9c-e58a-4b78-a252-80e1bc89d61a)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

23.10.0.2-premium

### Tema Yang Digunakan

natra

### Informasi tambahan

https://berputar.opendesa.id/

**Comment by andifahruddinakas** [comment]
mas @vickyrolanda, coba di cek ini mas.
