### ISSUE TITLE
Bug/error: Ubah pengaturan Ukuran huruf px menjadi pt, menyesuaikan kebiasaan pengguna dalam pembuatan surat pada word atau sejenisnya

### ISSUE THREAD

**Issue by mah-mudi** [OpenSID/OpenSID#7230]
### Jelaskan error yg dialami

pengaturan Ukuran huruf pada pengaturan surat menggunakan PX

### Cara untuk mereplikasi errornya

1. pengaturan surat

### Hasil yg diharapkan

Ubah pengaturan Ukuran huruf px menjadi pt, menyesuaikan kebiasaan pengguna dalam pembuatan surat pada word atau sejenisnya dengan tujuan pengguna lebih enak dalam pengaturan suratnya.

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/57661283/1ac452dc-0d7d-4c38-91d9-a778dec44ca2)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

23.10.0.2-premium

### Tema Yang Digunakan

natra

### Informasi tambahan

https://berputar.opendesa.id/

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/3046
