### ISSUE TITLE
Bug/error: Redaksi Pendapatan Desa pada output Footer kurang tepat

### ISSUE THREAD

**Issue by mah-mudi** [OpenSID/OpenSID#7231]
### Jelaskan error yg dialami

Redaksi Pendapatan Desa pada output Footer kurang tepat, diantaranya : 
1. Bagi Hasil Pajak Dan Retribusi Desa **harusnya** Bagi Hasil Pajak Dan Retribusi
2. Bantuan Keuangan Kabupaten/kota Desa **harusnya** Bantuan Keuangan Kabupaten/kota
3. Bunga Bank Desa **harusnya** Bunga Bank

### Cara untuk mereplikasi errornya

output footer keuangan APBDESA

### Hasil yg diharapkan

Redaksi footer keluar sebagaimana pada sistem

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/57661283/674a82af-eae0-404f-a736-f9a28986fee7)

![image](https://github.com/OpenSID/OpenSID/assets/57661283/21d9650d-e96a-4600-bd09-67cef43a5e2c)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

23.10.0.2-premium

### Tema Yang Digunakan

natra

### Informasi tambahan

-

**Comment by andifahruddinakas** [comment]
terkait perubahan issue https://github.com/OpenSID/OpenSID/issues/7082, jika ada yg kurang bisa dilaporkan ke issue tsb dan akan di reopen.
