### ISSUE TITLE
Bug/error: Membuat Surat Keterangan Kematian Tiny MCE untuk Pemohon yang statusnya hidup juga muncul

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#7232]
### Jelaskan error yg dialami

Ketika ingin membuat surat keterangan kematian untuk pemohon yang status dasarnya hidup, pindah juga muncul

### Cara untuk mereplikasi errornya

Pergi Ke layanan Surat
Klik Cetak surat
Cari Surat Keterangan Kematian
Pilih Pemohon yang muncul semua penduduk
<img width="765" alt="Screenshot 2023-10-19 173455" src="https://github.com/OpenSID/OpenSID/assets/25834335/f9798f51-9276-45a6-8981-8ef55a75ba5a">

### Hasil yg diharapkan

Seharusnya Pemohon yang muncul adalah yang statusnya mati seperti surat RTF
<img width="713" alt="Screenshot 2023-10-19 173412" src="https://github.com/OpenSID/OpenSID/assets/25834335/5b7cc16c-aecf-4578-9ad7-a3389a630bb8">

### Tangkapan layar dan log error

<img width="765" alt="Screenshot 2023-10-19 173455" src="https://github.com/OpenSID/OpenSID/assets/25834335/6775cc3c-0c8d-44cc-b31c-b7ee7b2e6183">

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Rilis  Versi 23.10.0.2-premium

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/3033
