### ISSUE TITLE
Bug/error: Tampilkan Poto di Surat TinyMCE tidak tampil

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#7233]
### Jelaskan error yg dialami

Ketika Membuat Surat Domisili dan ingin menampilkan poto penduduk, potonya tidak tampil
<img width="580" alt="Screenshot 2023-10-19 175223" src="https://github.com/OpenSID/OpenSID/assets/25834335/83d66a18-c85a-4838-997c-1c69bc63ec90">

### Cara untuk mereplikasi errornya

<img width="580" alt="Screenshot 2023-10-19 175223" src="https://github.com/OpenSID/OpenSID/assets/25834335/1d703965-a6d4-4142-b4e2-43e814fca474">

### Hasil yg diharapkan

poto tampil seperti pada surat RTF

### Tangkapan layar dan log error

<img width="580" alt="Screenshot 2023-10-19 175223" src="https://github.com/OpenSID/OpenSID/assets/25834335/9453bd27-1d3e-41ca-97ed-ff341d2407f3">

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

23.10.0.3 premium

**Comment by andifahruddinakas** [comment]
mas @MUHAMMADRANGSEL, foto di tampilkan saat buat pdf. jika masih pada editor, hanya muncul kode isian. Sama halnya dengan logo, qrcode, atau lainnya berkaitan dengan gambar.

<img width="481" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/bdd9b3be-081a-4fe0-9a86-da0039cf60e3">

**Comment by MUHAMMADRANGSEL** [comment]
saya coba di https://devpremium.opendesa.id/penduduk
<img width="460" alt="Screenshot 2023-10-23 202537" src="https://github.com/OpenSID/OpenSID/assets/25834335/3d4e64b0-a892-4455-a78a-ca46c8d9bd52">
hasilnya sama poto tidak tampil

**Comment by MUHAMMADRANGSEL** [comment]
setelah saya cek poto muncul jika pilihan Normal
<img width="845" alt="Screenshot 2023-10-23 203931" src="https://github.com/OpenSID/OpenSID/assets/25834335/4083cf02-055b-4c5c-83ad-aa76002b5bf9">
<img width="251" alt="Screenshot 2023-10-23 204126" src="https://github.com/OpenSID/OpenSID/assets/25834335/5b950d89-79df-45aa-995e-d71e7a30fd22">


jika memilih yang lain baru tidak muncul
