### ISSUE TITLE
Bug/error: Jika Pengaturan TTE dinonaktifkan maka Tinjau PDF di arsip surat tercatat sebagai konsep

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#7234]
### Jelaskan error yg dialami

Jika Pengaturan TTE dinonaktifkan maka Tinjau PDF di arsip surat tercatat sebagai konsep, 
<img width="783" alt="Screenshot 2023-10-19 194949" src="https://github.com/OpenSID/OpenSID/assets/25834335/e7f249b4-29a4-4e6c-850e-f0921ad77430">

### Cara untuk mereplikasi errornya

Masuk di Menu Layanan Surat Pengaturan surat Nonaktifkan Pengaturan TTE
setelah itu langsung ke menu Cetak Surat pilih salah satu surat TinyMCE
setelah itu tinjau PDF
<img width="657" alt="Screenshot 2023-10-19 195119" src="https://github.com/OpenSID/OpenSID/assets/25834335/b558f3ef-8ff9-46b2-89e1-ff0ec09ba61b">
setelah itu masuk ke arsip surat
<img width="775" alt="Screenshot 2023-10-19 195156" src="https://github.com/OpenSID/OpenSID/assets/25834335/195dfe27-1b6f-4d69-a6d7-f5e448abccad">

### Hasil yg diharapkan

1. Jika hanya tinjau PDF harapannya belum tercacat di menu arsip surat
2. Jika yang diklik cetak surat maka baru tercatat di arsip layanan 

### Tangkapan layar dan log error

<img width="783" alt="Screenshot 2023-10-19 194949" src="https://github.com/OpenSID/OpenSID/assets/25834335/ef893cb5-26d8-4302-a104-b2eb87b75d07">
<img width="657" alt="Screenshot 2023-10-19 195119" src="https://github.com/OpenSID/OpenSID/assets/25834335/d2c66736-a685-47a7-b651-388c861eb550">
<img width="775" alt="Screenshot 2023-10-19 195156" src="https://github.com/OpenSID/OpenSID/assets/25834335/1badf99f-7406-4752-93fa-9fac34eebd36">

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

23.10.0.2 premium

**Comment by andifahruddinakas** [comment]
Perubahan terkait https://github.com/OpenSID/OpenSID/issues/7100
