### ISSUE TITLE
Bug/error: Bukti Pembayaran Pada Layanan Pelanggan Tidak Tampil

### ISSUE THREAD

**Issue by Restony33** [OpenSID/OpenSID#7235]
### Jelaskan error yg dialami

Bukti Pembayaran Pada Layanan Pelanggan Tidak Tampil
![2023-10-19_21h09_34](https://github.com/OpenSID/OpenSID/assets/104592011/9ea9d516-477d-4a80-b63e-ea6421806cee)

### Cara untuk mereplikasi errornya

1. Login Admin
2. Menu Info Desa
3. Pilih Layanan Pelanggan
4. pada kolom rincian pemesanan Bukti Pembayaran tidak tampil saat di Klik

![image](https://github.com/OpenSID/OpenSID/assets/104592011/baaeab78-d995-41fb-80bc-abd91e4d7e4d)

### Hasil yg diharapkan

Bukti Pembayaran Tampil dan Berjalan Normal

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/104592011/bd0aed8d-b83b-44e8-9a16-80464614a6a8)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v2310.0.2-premium

### Tema Yang Digunakan

Batuah

**Comment by andifahruddinakas** [comment]
mas @Restony33, bisa infokan desanya apa? biar dicekkan di layanan.

**Comment by Restony33** [comment]
Desa mekar sari kecamatan pasir sakti kabupaten lampung timur provinsi lampung pak

**Comment by andifahruddinakas** [comment]
Bukti tsb digunakan oleh pelaksana layanan untuk mengkonfirmasi pengaktifan layanan yg dipesan, untuk pelanggan bisa gunakan invoice yg disediakan.

Sudah disesuaikan melalui commit https://github.com/OpenSID/premium/commit/213b5f2b68b06f8c721813d5c57c69e982d7ee51
