### ISSUE TITLE
Bug/error: Ada koding php yang tampil pada permintaan surat melalui layanan mandiri dan permohonan surat

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#7242]
### Jelaskan error yg dialami

Jika di lakukan pengajuan surat melalui layanan mandiri , akan muncul seperti ini : 
![image](https://github.com/OpenSID/OpenSID/assets/59082428/b014c96a-27ca-469b-8a26-629c4c8dc67c)

dan tidak hanya di layanan mandiri jika di lakukan pemeriksaan melalui halamanoperator koding tersebut juga akan tampil seperti ini : 
![image](https://github.com/OpenSID/OpenSID/assets/59082428/cd3b96bf-9ed5-4ded-ace5-8c115ff57b72)

### Cara untuk mereplikasi errornya

1. Login ke layanan mandiri
2.  Bisa tes di beta  setelah di cek pada berputar yaiut rilis bug-fix tidak terjadi 
3.  lalu lakukan permohonan surat 
4.  dan check pada halaman operator pada permohonan surat

### Hasil yg diharapkan

Perintah koding tidak di tampilkan agar tidak terlihat oleh user

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/59082428/40fafba2-f395-4aa4-bf0b-1788daff0f8c)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2310.0.2

**Comment by agungsugiarto** [comment]
mas @vickyrolanda saya tidak bisa replikasi masalah yang di maksud, mas @andifahruddinakas bisa bantu replikasi?

**Comment by andifahruddinakas** [comment]
> mas @vickyrolanda saya tidak bisa replikasi masalah yang di maksud, mas @andifahruddinakas bisa bantu replikasi?

PR https://github.com/OpenSID/OpenSID/issues/7194

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/3035
