### ISSUE TITLE
Permintaan fitur: Tambahkan migrasi untuk Data Pelaku secara bawaan menjadi Penduduk Desa / sesuaikan pada surat

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#7243]
### Apa kekurangan yg ingin diatasi?

Setelah di lakukan testing pada surat TinyMCE teradapat kekurangan dari issue https://github.com/OpenSID/OpenSID/issues/7163 dimana ketika menjalankan rilis-dev semua surat TinyMCE menjadi kosong sumper datanya seperti gambar berikut ini : 
![image](https://github.com/OpenSID/OpenSID/assets/59082428/a7a45723-5297-46cb-9d78-413ef71cd293)

dan jika di lihat dari pengaturan memang tidak ter isi sumbernya  : 
![image](https://github.com/OpenSID/OpenSID/assets/59082428/ca72fc98-4a6e-4eac-bf7d-ce2af5e7d62b)

di cek bebrapa surat memang terjadi bisa cek di beta.opendesa.id

### Jelaskan solusi yg diinginkan

1. Jika di lihat ada beberapa surat tidak memiliki sumber dari penduduk desa, berarti perlu di periksa dan perlu tambahkan nilai bawaan agar semua surat sudah memiliki sumber data bawaan. 
2. kawatir ini menjqdi membingungkan pengguna ketika ingin cetak surat namun suber data tidak ada.
3. mungkin solusinya bisa tambahkan migrasi untuk memberikan nilai bawaan untuk sumber data pelaku surat,

### Apakah ada alternatif lain

- 

### Untuk versi OpenSID mana

2311.0.0

**Comment by andifahruddinakas** [comment]
Sudah dikerjakan melalui PR https://github.com/OpenSID/premium/pull/3026, sepertinya karena migrasi tidak jalan sempurna setelah penggabungan PR https://github.com/OpenSID/premium/pull/3018
