### ISSUE TITLE
Permintaan fitur: format tanggal tidak sesuai dengan hasil surat yang di cetak

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#7244]
### Apa kekurangan yg ingin diatasi?

Berdasarkan issue ini https://github.com/OpenSID/OpenSID/issues/7193 Terdapat perbaikan dimana format disesuaikan berdasarkan aturan dari https://www.php.net/manual/en/function.date.php 

namun ketika di uji ulang format tidak sesuai dengan hasil  seperti berikut ini : 
1. Format yang tersetting 
![image](https://github.com/OpenSID/OpenSID/assets/59082428/761244d2-d9ce-40a0-9c9c-1f1d8d796daa)
2. Dari hasil pengaturan seharusnya format menjadi seperti ini : 
![image](https://github.com/OpenSID/OpenSID/assets/59082428/513331d2-ba8f-452d-a298-b1d421c226a2)
3. Namun hasil yang terjadi seperti berikut ini : 
![image](https://github.com/OpenSID/OpenSID/assets/59082428/4522a42b-8664-47cf-9920-a07f2ced8ce8)

### Jelaskan solusi yg diinginkan

Perbaikan yang diperlukan : 
1. Sesuaikan format pada hasil yang di hasilkan
2. Jika di pengaturan diberikan kode tanggal seperti itu maka perlu tambahkan info untuk pengguna bisa menyusun tanggal yang di inginkan secara umum seperti berikut ini : 
- Tambahkan tombol informasi seperti berikut : 
![image](https://github.com/OpenSID/OpenSID/assets/59082428/4750ec36-61b8-4039-975c-f52eb0346c8b)
- Tampilkan Pop-up seperti berikut ini dengan bahasa indonesia 
![image](https://github.com/OpenSID/OpenSID/assets/59082428/3eff7590-c05e-4e33-9c38-3f75322c4bb5)

### Apakah ada alternatif lain

- 

### Untuk versi OpenSID mana

2311.0.0

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/3065
