### ISSUE TITLE
Bug/error: Halaman Periksa

### ISSUE THREAD

**Issue by afri18** [OpenSID/OpenSID#7247]
### Jelaskan error yg dialami

saat tekan tombol perbaiki di halaman periksa penduduk data yang tadinya mati hidup, pindah jadi hidup lagi

### Cara untuk mereplikasi errornya

harunya perbaiki data berdasarkan status dasar bukan kode peristiwa

### Hasil yg diharapkan

jumlah penduduk dan Keluarga di halaman Home, Statistik, dan Laporan Bulanan SAMA

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/6611881/78c23b58-0ad1-4470-97a7-225a80563e92)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2310.0.2

### Informasi tambahan

Halaman Periksa sangat menjebak ....

**Comment by pandigresik** [comment]
pak @afri18  bisa dibaca kembali komentar pada issue https://github.com/OpenSID/OpenSID/issues/7119 
Agar sama-sama paham masalahnya

Pada issue #7119 juga kita memakai db desa natairaya bukan db dari desa pak @afri18 . Dan hal tersebut cukup menyulitkan juga karena bisa jadi kondisinya tidak sama

**Comment by afri18** [comment]
> pak @afri18 bisa dibaca kembali komentar pada issue #7119 Agar sama-sama paham masalahnya
> 
> Pada issue #7119 juga kita memakai db desa natairaya bukan db dari desa pak @afri18 . Dan hal tersebut cukup menyulitkan juga karena bisa jadi kondisinya tidak sama

kalau hasilnya sama dalam pandangan saya pasti strukturnya sama , istilah STATUS DASAR pasti sama semua untuk DATABASE OPENSID

**Comment by pandigresik** [comment]
> > pak @afri18 bisa dibaca kembali komentar pada issue #7119 Agar sama-sama paham masalahnya
> > Pada issue #7119 juga kita memakai db desa natairaya bukan db dari desa pak @afri18 . Dan hal tersebut cukup menyulitkan juga karena bisa jadi kondisinya tidak sama
> 
> kalau hasilnya sama dalam pandangan saya pasti strukturnya sama , istilah STATUS DASAR pasti sama semua untuk DATABASE OPENSID

kalau struktur sudah pasti sama, isi datanya yang bisa jadi berbeda. Sebagaimana di coment saya pada issue #7119 mengenai data yang aneh bukan strukturnya
