### ISSUE TITLE
Bug/error: Ubah status dasar hilang

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#7248]
### Jelaskan error yg dialami

ketika ingin mengubah status dasar penduduk tidak bisa tombol ubah status dasar tidak ada
<img width="932" alt="Screenshot 2023-10-23 202809" src="https://github.com/OpenSID/OpenSID/assets/25834335/f7f5e165-2bb2-498b-90d8-4c619a60290c">

### Cara untuk mereplikasi errornya

<img width="932" alt="Screenshot 2023-10-23 202809" src="https://github.com/OpenSID/OpenSID/assets/25834335/17728b76-4fe8-4aaf-943c-63fe7660edb2">

### Hasil yg diharapkan

Ubah status dasar muncul seperti versi sebelumnya

### Tangkapan layar dan log error

<img width="932" alt="Screenshot 2023-10-23 202809" src="https://github.com/OpenSID/OpenSID/assets/25834335/7b32a502-97ce-4880-bce2-36c30a5f8aba">

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Rilis  Versi 23.10.0.1-premium

**Comment by ariandii** [comment]
ini terjadi karena data belum dinyatakan lengkap. karena masih tampil tombol hapus.

tes jika data dinyatakan lengkap. icon gear pojok kanan atas. ibahbjadi YA.

maka ubah status dasar akan muncul.
