### ISSUE TITLE
Bug/error: edit anggota lembaga desa

### ISSUE THREAD

**Issue by afri18** [OpenSID/OpenSID#7249]
### Jelaskan error yg dialami

Saat edit data anggota lembaga desa setelah d simpan malah diarahkan kehalaman periksa, karna tidak ada tombol jangan periksa maka halaman saya mundurkan akibatnya data lembaga yang tadi di edit hilang semua

### Cara untuk mereplikasi errornya

harusnya data tersimpan sesuai dengan editan

### Hasil yg diharapkan

tidak di arahkan ke halaman periksa, walaupun di arahkan harusnya ada tonbol jangan periksa

### Tangkapan layar dan log error

setelah edit lembaga bpd hilang
![image](https://github.com/OpenSID/OpenSID/assets/6611881/c64b4097-10ec-45d1-a5de-3e86e0b41d45)

sedangkan sebelumnya ada, tersimpan di backupan
![image](https://github.com/OpenSID/OpenSID/assets/6611881/4968437f-a7fe-4e87-8a53-d3bdbc391790)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2310.0.2

### Informasi tambahan

seharusnya data tidak bisa d hapus bila sudah terisi

**Comment by andifahruddinakas** [comment]
ak @afri18  ada contoh database yg bisa gunaka? Atau bisa replikasike berputar untuk masalah ini dan database nya di backup.
