### ISSUE TITLE
Bug di folder surat

### ISSUE THREAD

**Issue by semmy** [OpenSID/OpenSID#725]
Jika kita menghilangkan **index.php** pada url aplikasinya melalui modifikasi _.htaccess_ maka url untuk menu **surat** menjadi http://localhost/opensid/surat/ sehingga yang akan tampil adalah file index.html pada **folder surat**. solusinya adalah **folder surat** diganti penulisannya.. mungkin pake nama **folder surats** misalnya :)) dan beberapa script yg perlu diubah di **Models** atau **Controllers**. Atau Url-nya diganti, misalnya http://localhost/opensid/persuratan

**Comment by eddieridwan** [comment]
Solusi masalah ini ada di panduan: https://github.com/OpenSID/OpenSID/wiki/Tanya-Jawab-Install-dan-Update. Gunakan contoh script htaccess di htaccess.txt.

Tidak perlu dilakukan perubahan.
