### ISSUE TITLE
Bug/error: Tombol Hapus di menu Lembaga

### ISSUE THREAD

**Issue by afri18** [OpenSID/OpenSID#7250]
### Jelaskan error yg dialami

Tombol Hapus di menu lembaga seharusnya tidak berfungsi apabila sudah ada anggotanya

### Cara untuk mereplikasi errornya

bila anggota lembaga sudah di isi tombol hapus seharusnya tidak muncul atau berfungsi

### Hasil yg diharapkan

Saat Anggota Lembaga sudah terisi tombol hapus tidak ada/berfungsi

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/6611881/5f1c5dd0-d418-4a3e-ac7b-ed209df250c0)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2310.0.2

### Informasi tambahan

tombol hapus saat anggota masih ada jangan berfungsi untuk menghindari data lembaga hilang

**Comment by andifahruddinakas** [comment]
buat sama dengan modul lain (misalnya bantuan), jika terdapat anggota di dalamnya tombol hapus disabled secara view dan fungsinya.

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/3039
