### ISSUE TITLE
Permintaan fitur: menambahkan fitur plugin pada modul Prodeskel

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#7251]
### Apa kekurangan yg ingin diatasi?

saat ini fitur pada OpenSID sudah cukup banyak dan banyak juga yang masih perlu penyesuaian dan penyempurnaan maka dari itu penambahan modul -modul baru yang sifatnya dipasang pada hard code internal berpotensi menambah beban dari aplikasi & juga berpotensi menimbulkan bug-bug baru. 

maka potensi terbaik saat ini OpenSID akan dikembangkan sebuah tambahan modul dengan pendekatan plug & play artinya perlu di pasang maka modul bisa jalan jika tidak dipasang maka modul tidak tersedia. 

Konsep ini sama seperti pemasangan plugin pada wordpress. 

jika dilihat dari konsep wordpress plugin dipasang pada folder wp-content lalu di dalam folder plugin. 
maka pada OpenSID kita memiliki folder desa sebagai folder utama yang tidak tercommit atau di baca oleh github. 

maka plugin / modul yang akan ditambahkan pada OpenSID jga baiknya ditambah pada folder desa. 
agar jika ada perbaikan atau perbaruan maka yang di perbaruin adalah folder modul tambahan saja. 

Struktur yang di sarankan bahwa akan ditambhkan folder plugin pada fodler desa

### Jelaskan solusi yg diinginkan

1. Sediakan menu plugin pada OpenSID
2. Lalu sediakan upload file zip
3. arahkan ke folder desa/plugin
4. extract file  .zip 
5. sesuaikan koding pada OpenSID agar membaca dan menditeksi folder baru pada direktory desa/plugin
6. maka perlu jalankan seeder untuk menyimpan nama plugin & table yang dibutuhkan untuk mendukung plugin (proses ini adalah proses install plugin )
7. tambahkan proses seeder agar menambah ke daftar menu/modul pada OpenSID

Juga perlu disiapkan dimana ketika modul / plugin di cabut maka data tidak terkait pada fungsi yang lain sehingga tidak membaut error pada menu lain. 

### Apakah ada alternatif lain

Silahkan berikan pandangan lain jika punya konsep lain agar mudah dalam penerapannya.

### Untuk versi OpenSID mana

2311.0.0

**Comment by MUHAMMADRANGSEL** [comment]
Yang Kami Harapakan ada menu singkronisasi OpenSID dengan Aplikasi Prodeskel terutama unyuk Data KK dan AK seperti Aplikasi SIDEKA ,  DIGIDES atau aplikasi serupa lainnya

**Comment by MUHAMMADRANGSEL** [comment]
apakah plugin maksudnya seperti itu,,?

**Comment by ruririzal** [comment]
Untuk teknis.
- bagaimana mekanisme dari alamat url untuk plugin (mengingat, kemungkinan banyaknya halaman yg ada dalam plugin) dan akses controller plugin nya
- bagaimana controller plugin bisa mengakses modal pada aplikasi utama
- bagaimana mekanisme view, js, css dikembangkan di plugin (mengingat, sepertinya view pada aplikasi utama menggunakan blade dan di cache)
- adakah potensi celah keamanan dari plugin?

**Comment by totoprayogo1916** [comment]
Sepertinya bisa menggunakan ini mas @ruririzal 
https://github.com/bethropolis/plugin-system

lebih mengarah ke Wordpress untuk pemanggilan dan pengaturan pluginnya
Saya akan coba terlebih dahulu untuk implementasinya sebelum menyesuaikan seluruh isi dari modul yang akan diterapkan.

**Comment by andifahruddinakas** [comment]
> Sepertinya bisa menggunakan ini mas @ruririzal 
> https://github.com/bethropolis/plugin-system
> 
> lebih mengarah ke Wordpress untuk pemanggilan dan pengaturan pluginnya
> Saya akan coba terlebih dahulu untuk implementasinya sebelum menyesuaikan seluruh isi dari modul yang akan diterapkan.
> 

Mungkin bisa buat contoh sederhana saja dlu penerapannya.
