### ISSUE TITLE
Permintaan fitur: penambahan formulir f-2.29 (surat keterngan kematian)

### ISSUE THREAD

**Issue by siwamdara** [OpenSID/OpenSID#7252]
### Apa kekurangan yg ingin diatasi?

tolong ditambahkan lampiran formulir f-2.29 surat keteranga kematian

### Jelaskan solusi yg diinginkan

cuma ditambahkan f-2.29 seperti dulu

### Apakah ada alternatif lain

formulir lampiran f-2.29 ini masih di pakai di dukcapil di kabupaten gianyar

### Untuk versi OpenSID mana

v23.10

**Comment by MUHAMMADRANGSEL** [comment]
Kami di Lombok Timur Juga mAsih Pakai

**Comment by makhbub** [comment]
UP

**Comment by andifahruddinakas** [comment]
pak @MUHAMMADRANGSEL, @makhbub, @siwamdara bisa sertakan lampirannya.

**Comment by makhbub** [comment]
![photo_2024-05-06_13-55-01](https://github.com/OpenSID/OpenSID/assets/38773660/a0e722c4-046f-41ef-b730-ed9241994cbb)
