### ISSUE TITLE
Bug/error: Tombol Simpan Tidak Berfungsi

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#7254]
### Jelaskan error yg dialami

Ketika membuat surat TinyMCE di https://devpremium.opendesa.id/, jika Sumber Data Pelaku di pengaturan Surat Penduduk Desa dan Penduduk Luar Desa (Lengkap) 
<img width="740" alt="Screenshot 2023-10-24 212051" src="https://github.com/OpenSID/OpenSID/assets/25834335/4e3ee77e-a838-49cf-bc11-c54c3e0795a5">
maka Tombol SIMPAN Tidak Berfungsi untuk **Sumber Pelaku dari Penduduk Desa**  kalau Penduduk Luar Desa (Lengkap) berfungsi dengan Baik
<img width="803" alt="Screenshot 2023-10-24 212228" src="https://github.com/OpenSID/OpenSID/assets/25834335/bfcf8eb7-ed02-4fd6-bab5-2f7ec0c760aa">

### Cara untuk mereplikasi errornya

Ketika membuat surat TinyMCE di https://devpremium.opendesa.id/, jika Sumber Data Pelaku di pengaturan Surat Penduduk Desa dan Penduduk Luar Desa (Lengkap) 
<img width="740" alt="Screenshot 2023-10-24 212051" src="https://github.com/OpenSID/OpenSID/assets/25834335/4e3ee77e-a838-49cf-bc11-c54c3e0795a5">
maka Tombol SIMPAN Tidak Berfungsi untuk **Sumber Pelaku dari Penduduk Desa**  kalau Penduduk Luar Desa (Lengkap) berfungsi dengan Baik
<img width="803" alt="Screenshot 2023-10-24 212228" src="https://github.com/OpenSID/OpenSID/assets/25834335/bfcf8eb7-ed02-4fd6-bab5-2f7ec0c760aa">

### Hasil yg diharapkan

Tombol Simpan Berfungsi baik  Sumber Data Pelaku  Penduduk Desa maupun Penduduk Luar Desa (Lengkap) 

### Tangkapan layar dan log error

<img width="803" alt="Screenshot 2023-10-24 212228" src="https://github.com/OpenSID/OpenSID/assets/25834335/4a81c156-dc73-43ad-b880-f03e07ec5902">

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Rilis  Versi 23.10.0.1-premium Dev

**Comment by andifahruddinakas** [comment]
Sudah disesuaikan yg terbaru

**Comment by MUHAMMADRANGSEL** [comment]
Ok SIAP BANG
