### ISSUE TITLE
Bug/error: DevelBar tidak muncul di environment development

### ISSUE THREAD

**Issue by totoprayogo1916** [OpenSID/OpenSID#7256]
### Jelaskan error yg dialami

Jika openSID dijalankan pada mode `development` maka muncul error 
```
Message: Call to a member function getDatabaseManager() on null
```

sangat susah mengetahui error yang terjadi jika tidak dalam mode development
mungkin bisa melihat log, tapi itu meribetkan

### Cara untuk mereplikasi errornya

atur agar environment menjadi `development`

### Hasil yg diharapkan

DevelBar muncul dan situs berjalan normal pada mode env development

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/2387514/22fd1154-92a3-4171-96ea-b81f6261832c)

### Rilis Versi OpenSID

Rilis Umum

### Versi OpenSID

v2310.0.0

**Comment by andifahruddinakas** [comment]
Cek commit perbaikan yang dilakukan di repo premium https://github.com/OpenSID/OpenSID/commit/8f779a663bd213d2711a936a15fe6284a2d2653b
