### ISSUE TITLE
tambahkan migrasi terkait pengaturan sumber penduduk bawaan sistem

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#7258]
Saat update ke rilis-dev sumber penduduk pada surat tinymce akan hilng karena harus di lakukan pengaturan ulang, ini akan membuat pengguna akanribut nantinya krna mengira ada bug, seperti gambar di bawah tidak ada sumber penduduk yang akan di buatkan surat. 

![image](https://github.com/OpenSID/OpenSID/assets/59082428/9e362c1b-5162-4811-8c03-fe434edbddc9)

sehingga perlu ditambahkan migrasi untuk memberikan nilai bawaan pada sumber penduduk pada pengaturan surat, agar sumber tetap sama seperti sebelumnya.

**Comment by vickyrolanda** [comment]
https://github.com/OpenSID/premium/pull/2987

**Comment by andifahruddinakas** [comment]
Mas @vickyrolanda sepertinya itu migrasi tdk jalan dari perpindahan bug-fix ke rilis-dev. Tinggal jalankan ulang migrasinya lewat admin.

Tapi seharusnya migrasi dari bug-fix ke rilis-dev jalan otomatis dengan perbedaan versi database nya.

**Comment by agungsugiarto** [comment]
masih ngebug mas @andifahruddinakas, jika dilakukan migrasi berulang, akan terus bertambah seiring migrasi

```json
{
  "individu": {
    "data": [
      [
        [
          "1"
        ]
      ]
    ],
    "sex": "",
    "status_dasar": "",
    "kk_level": "",
    "data_orang_tua": "1",
    "data_pasangan": "0"
  }
}
```

**Comment by andifahruddinakas** [comment]
> masih ngebug mas @andifahruddinakas, jika dilakukan migrasi berulang, akan terus bertambah seiring migrasi
> 
> ```json
> {
>   "individu": {
>     "data": [
>       [
>         [
>           "1"
>         ]
>       ]
>     ],
>     "sex": "",
>     "status_dasar": "",
>     "kk_level": "",
>     "data_orang_tua": "1",
>     "data_pasangan": "0"
>   }
> }
> ```

ini mas @habibie11
