### ISSUE TITLE
error pada saat verifikasi surat 

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#7259]
Saat TES TTE pada devpremium.opendesa.id terjadi error pada verifikasi surat , errornya seperti berikut ini : 
![image](https://github.com/OpenSID/OpenSID/assets/59082428/0d234904-8623-49eb-a1d4-46d0016d671a)

jika di test yang bug-fix di berputar tidak terjadi error seperti diatas

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/3050
