### ISSUE TITLE
Duplikasi pada input dari template keuangan manual

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#7265]
Saat menambahkan template keuangan untuk tahun yang sama, maka akan terjadi duplikasi. Contoh sbb : 

![image](https://github.com/OpenSID/OpenSID/assets/57283157/d698a3be-4693-4dfd-a319-209983728e31)

Info : 
```
tgl laporan : 26-10-2023
pelapor : pak ariandi

isi laporan : 
pak, saya coba tambah template , kadang double seperti video.

tapi, untuk Bidang (3) Pelaksanaan Pembinaan Kemasyarakatan dan (4) Pemberdayaan Masyarakat,
ketika di edit, kolom Kode Rincian menjadi Kosong.

kalau yang lain auto isi sesuai kode rincian awal.
```

**Comment by agungsugiarto** [comment]
kurang jelas issuenya mas, bisa kirim log error nya atau video langkahnya

**Comment by andifahruddinakas** [comment]
> kurang jelas issuenya mas, bisa kirim log error nya atau video langkahnya

Video sy kirim ke telegram krn tdk bisa terupload dsni
