### ISSUE TITLE
[Template Surat] Mohon Penambahan Form Pengajuan KTP el

### ISSUE THREAD

**Issue by ipaysx** [OpenSID/OpenSID#727]
mohon untuk penambahan form pengajuan ktp el.. trims
dan sudah saya upload hasil ahir tentang form ktp el yang di gunakan di daerah kami.. trims

[FORM KTP.zip](https://github.com/OpenSID/OpenSID/files/1537858/FORM.KTP.zip)

**Comment by metalab25** [comment]
Itu kolom isian harus diisi 1 kotak 1 huruf atau bisa diisi 1 kolom untuk setiap isian ?

**Comment by metalab25** [comment]
Baru aja coba" buat Formulir Permohonan E-KTP (F-1.12) dan ditambahkan ke Master Surat kalo ada yang mau menggunakan nanti silakan download di Files/Berkas Grup Pengguna dan Pegiat OpenSID

Bung @eddieridwan mohon maaf belum bisa PR karna internet lagi down dirumah

**Comment by metalab25** [comment]
untuk Form E-KTP ini sudah saya buatkan silakan dicoba.
@eddieridwan, mohon di review
[surat_formulir_permohonan_e-ktp.zip](https://github.com/OpenSID/OpenSID/files/1559332/surat_formulir_permohonan_e-ktp.zip)

**Comment by eddieridwan** [comment]
@ipaysx @metalab25 harap lampirkan Permen yang mengatur F-1.12 yang dimaksud. Yang saya temukan di Permendagri NOMOR 19 TAHUN 2010, F-1.12 adalah formulir Perubahan Biodata Penduduk Orang Asing.

Sebaiknya kita selalu tahu peraturan mana yang kita ikuti.

**Comment by eddieridwan** [comment]
@ipaysx @metalab25 : sementara menunggu informasi kepastian dasar peraturan F-1.12, issue ini tidak akan diprioritaskan untuk rilis OpenSID. Nanti kalau teman2 mendapatkan informasi tersebut, silakan dilampirkan dan issue ini dapat diprioritaskan kembali.

Tentunya teman2 tetap bisa menggunakan surat yang telah dibuat @metalab25 secara mudah dengan menambahkan ke folder desa/surat dan menjalankan Database > Migrasi DB.

**Comment by balongbesuk** [comment]
outdate bs d close
