### ISSUE TITLE
Bug/error: log keluarga

### ISSUE THREAD

**Issue by afri18** [OpenSID/OpenSID#7275]
### Jelaskan error yg dialami

Saat menambahkan keluarga datang dari menu keluarga setelah d simpan sistem mengarahkan kehalaman periksa, setelah di klik periksa maka terdapat log keluarga baru di table log keluarga dengan waktu yang sama, akibatnya di laporan bulanan tercatat sebagai keluarga baru dan keluarga datang, seharusnya yg tercatat itu cukup satu, atau hilangkan penambahan keluarga dari penduduk datang di menu keluarga

### Cara untuk mereplikasi errornya

saat menambahkan keluarga baru tidak d arahkan lagi kehalam periksa log keluarga, karna kalau diklik periksa akan tercatat sebagai keluarga datang dan keluarga baru

### Hasil yg diharapkan

berikan pilihahan seperti periksa log penduduk di periksa log keluarga agar sisitem mencatat hasil yg sebenarnya

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/6611881/89333124-0223-4c81-9ffd-44b69f7be43d)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2310.0.3

### Tema Yang Digunakan

denatra

### Informasi tambahan

karna tercatat 2 x di log keluarga maka di laporan bulanan di tambahkan di keluarga baru lahir dan keluarga baru datang

**Comment by afri18** [comment]
kalau d hapus di log keluarga untuk kode 5 (keluarga datang) maka jumlah jadi betul antara laporan bulanan dan keluarga aktif, hanya penambahannya salah, tercatat sebagai keluarga baru di laporan bulanan.

**Comment by andifahruddinakas** [comment]
> kalau d hapus di log keluarga untuk kode 5 (keluarga datang) maka jumlah jadi betul antara laporan bulanan dan keluarga aktif, hanya penambahannya salah, tercatat sebagai keluarga baru di laporan bulanan.

Yg diperbaiki sumber masuknya. Untuk yg sudah terlanjur masuk bisa di cek melalui halaman periksa.

**Comment by afri18** [comment]
> > kalau d hapus di log keluarga untuk kode 5 (keluarga datang) maka jumlah jadi betul antara laporan bulanan dan keluarga aktif, hanya penambahannya salah, tercatat sebagai keluarga baru di laporan bulanan.
> 
> Yg diperbaiki sumber masuknya. Untuk yg sudah terlanjur masuk bisa di cek melalui halaman periksa.

itu salah karna saya klik perbaiki d halaman periksa, jadi lognya keluarga baru dan keluarga datang

**Comment by afri18** [comment]
jangan di rilis 2312 (terlalu lama) merusak data, karna awal bulan nopember keluarga datang tidak tercatat/dihitung sebagai keluarga awal bulan ini
Kalau klik perbarui akan merusak log keluarga datang menjadi keluarga baru
![image](https://github.com/OpenSID/OpenSID/assets/6611881/cfe8205a-6047-45c2-aec2-533abc71977f)
makanya harus disegerakan
