### ISSUE TITLE
Bug/error: jumlah keluarga

### ISSUE THREAD

**Issue by afri18** [OpenSID/OpenSID#7276]
### Jelaskan error yg dialami

jumlah keluarga di halaman hom_sid berbeda sendiri dari statistik, keluarga aktif dan laporan bulanan

### Cara untuk mereplikasi errornya

samakan dengan halaman jumlah keluarga aktif

### Hasil yg diharapkan

jumlah keluarga untuk semua halaman/menu harusnya sama

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/6611881/6386cebd-5436-461d-91e8-4c5cbfddc6c4)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2310.0.3

### Tema Yang Digunakan

denatra

### Informasi tambahan

jumlah keluarga di halaman hom_sid beda sendiri

**Comment by andifahruddinakas** [comment]
Kerjakan issue https://github.com/OpenSID/premium/issues/3061 dulu sebelum issue ini.

**Comment by afri18** [comment]
> Member

siap komandan
info tambahan
![image](https://github.com/OpenSID/OpenSID/assets/6611881/38552935-f05f-48c8-ba8e-87542d1046ed)

**Comment by afri18** [comment]
sepertinya ini harus di dahulukan, karna saya cek di bulan sebelumnya ternyata tercatat dua kali juga, di keluarga baru(lahir) juga di keluarga datang
SANGAT PENTING
bisa jadi yg benar di halaman hom_sid, sedangkan di halaman keluarga aktif, statistik apalagi laporan bulanan tidak singkron
PRIORITASKAN @andifahruddinakas @eddieridwan

**Comment by andifahruddinakas** [comment]
database terlampir

**Comment by andifahruddinakas** [comment]
Sudah di kerjakan melalui issue https://github.com/OpenSID/OpenSID/issues/7275

Silahkan di cek kembali menggunakan database anda, jika masih bermasalah bisa duplikasi ke website https://beta.opendesa.id

**Comment by afri18** [comment]
> Sudah di kerjakan melalui issue #7275
> 
> Silahkan di cek kembali menggunakan database anda, jika masih bermasalah bisa duplikasi ke website https://beta.opendesa.id

saya coba dengan database sendiri malah kacau, kronologi : 
- banyak peringatan keluarga yang mempunyai log ganda, rata2 keluarga datang dengan keluarga baru
- setelah saya hapus keluarga baru (yakin keluarga itu datang karna no kk beda kode wilayah) lalu periksa laporan bulanan jumlah keluarga makin kacau.
-  jumlah keluarga di laporan bulanan tidak sama lagi dengan jumlah di statistik dan keluarga aktif
gambar
![image](https://github.com/OpenSID/OpenSID/assets/6611881/b00f4e6b-e347-4bf1-b28c-b71c66280125)

padahal kalau di lihat bulan lalu jumlah sudah sama semua, hanya saat tanggal 1 nopember jumlah keluarga awal bulan ini kurang 2 karna keluarga datang bulan oktober tidak di hitung (sitem menganggab harus dijadikan keluarga baru, kalaui klik perbaiki otomatis keluarga datang jadi baru dan log keluarga tidak sesuai)

**Comment by andifahruddinakas** [comment]
> > Sudah di kerjakan melalui issue #7275
> > Silahkan di cek kembali menggunakan database anda, jika masih bermasalah bisa duplikasi ke website https://beta.opendesa.id
> 
> saya coba dengan database sendiri malah kacau, kronologi :
> 
> * banyak peringatan keluarga yang mempunyai log ganda, rata2 keluarga datang dengan keluarga baru
> * setelah saya hapus keluarga baru (yakin keluarga itu datang karna no kk beda kode wilayah) lalu periksa laporan bulanan jumlah keluarga makin kacau.
> * jumlah keluarga di laporan bulanan tidak sama lagi dengan jumlah di statistik dan keluarga aktif
>   gambar
>   ![image](https://user-images.githubusercontent.com/6611881/281253684-b00f4e6b-e347-4bf1-b28c-b71c66280125.png)
> 
> padahal kalau di lihat bulan lalu jumlah sudah sama semua, hanya saat tanggal 1 nopember jumlah keluarga awal bulan ini kurang 2 karna keluarga datang bulan oktober tidak di hitung (sitem menganggab harus dijadikan keluarga baru, kalaui klik perbaiki otomatis keluarga datang jadi baru dan log keluarga tidak sesuai)

ada contoh database yg bisa digunakan? atau bisa replikasi ke https://beta.opendesa.id

**Comment by afri18** [comment]
@andifahruddinakas mohon info : 
1. jumlah keluarga aktif di statistik dan beranda dihitung via tabel log_keluarga atau tweb_keluarga ?
2. jumlah keluarga di laporan bulanan dihitung apa hanya via table log_keluarga ?

**Comment by andifahruddinakas** [comment]
> @andifahruddinakas mohon info : 
> 1. jumlah keluarga aktif di statistik dan beranda dihitung via tabel log_keluarga atau tweb_keluarga ?
> 2. jumlah keluarga di laporan bulanan dihitung apa hanya via table log_keluarga ?
> 

Jumlah keluarga aktif di cek dari log keluarga dengan kepala keluarga yg masih hidup
