### ISSUE TITLE
Bug/error: kolom peristiwa di log penduduk terasa janggal

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#7278]
### Jelaskan error yg dialami

ketika melihat isi tweb log_penduduk untuk kolom peristiwa kelihatan janggal sekali yang dimana kolom peristiwa terisi dengan tanggal-bulan tahun lahir dan juga ada yang terisi oleh tahun melebihi dari tahun sekarang seperti gambar dibawah ini
<img width="676" alt="Screenshot 2023-10-28 185803" src="https://github.com/OpenSID/OpenSID/assets/25834335/8e0975e1-63c4-4f8d-b806-9974d44e2040">
<img width="722" alt="Screenshot 2023-10-28 185821" src="https://github.com/OpenSID/OpenSID/assets/25834335/894649b9-a404-4b44-a25f-7b9642465191">

### Cara untuk mereplikasi errornya

ketika melihat isi tweb log_penduduk untuk kolom peristiwa kelihatan janggal sekali yang dimana kolom peristiwa terisi dengan tanggal-bulan tahun lahir dan juga ada yang terisi oleh tahun melebihi dari tahun sekarang seperti gambar dibawah ini
<img width="676" alt="Screenshot 2023-10-28 185803" src="https://github.com/OpenSID/OpenSID/assets/25834335/8e0975e1-63c4-4f8d-b806-9974d44e2040">
<img width="722" alt="Screenshot 2023-10-28 185821" src="https://github.com/OpenSID/OpenSID/assets/25834335/894649b9-a404-4b44-a25f-7b9642465191">

### Hasil yg diharapkan

untuk kolom peristiwa perlu diisi dengan data yang agak relefan dan dicarikan solusi yang tepat
sebab dikhawatirkan ini akan muncul di Menu Laporan Bulanan atau di Beranda,
ketika misal tanggal dan bulan itu tiba.

### Tangkapan layar dan log error

<img width="676" alt="Screenshot 2023-10-28 185803" src="https://github.com/OpenSID/OpenSID/assets/25834335/82524aca-b9cc-425e-9b65-efe97c28600b">
<img width="722" alt="Screenshot 2023-10-28 185821" src="https://github.com/OpenSID/OpenSID/assets/25834335/2dcdf0dd-a186-4f78-bf07-b344a793bbde">

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Rilis  Versi 23.10.0.3-premium

**Comment by afri18** [comment]
pola tanggalnya sama dengan database cigelam, 19, 20 dan 21 ... ajaib

**Comment by afri18** [comment]
sepertinya sistem salah eksekusi pola yg biasa di input manual di aplikasi
misal tanggal 30-01-21 dibaca 2030-01-20 padahal maksudnya 30-01-2021
![image](https://github.com/OpenSID/OpenSID/assets/6611881/c73c329f-a871-4429-b078-464e21d08fb7)

**Comment by andifahruddinakas** [comment]
Solusi : 
- Sediakan halaman periksa jika terdeteksi tgl_peristiwa dengan thn > dari thn sekrang.
- Sediakan pilih pada masing2 penduduk yg terdeteksi masalah tsb untuk diperbaiki (cek periksa log_penduduk sebelumny)

**Comment by agungsugiarto** [comment]
Mas @akas issue ini sepertinya sudah dikerjakan di pr ini? https://github.com/OpenSID/premium/pull/3092 dan issue ini juga identik sama dengan issue ini https://github.com/OpenSID/OpenSID/issues/7282

**Comment by andifahruddinakas** [comment]
pak @MUHAMMADRANGSEL, bisa kirim database yg bisa digunakan untuk mengerjakan issue ini?

https://t.me/andifahruddinakas
