### ISSUE TITLE
Bug: data tidak muncul di cetak KK di layanan mandiri

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#728]
cetak KK dilayanan mandiri datanya tidak muncul
![image](https://user-images.githubusercontent.com/25834335/33796061-21dfff7e-dd28-11e7-8afa-e76e8d32c126.png)
mengingat layanan mandiri ini sdh banyak yang memanfaatkannya mhon segera di tindak lanuti

**Comment by MUHAMMADRANGSEL** [comment]
ini mulai terjadi di rilis 2.7

**Comment by eddieridwan** [comment]
Sdh dicommit ke master.
