### ISSUE TITLE
Sesuaikan isi LICENSE  agar tidak ada asumsi pengguna  UMUM dan PREMIUM perlu di jelaskan pada isi dari LICENSE 

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#7281]
Dengan adanya persamaam antara LICENSE yang ad apada OpenSID umum & OpenSID Premium maka menimpulkan pertanyaan pada pengguna kenapa tidak bisa menggunakan yang premium padahal LICENSE sama. 

tentu Dari pengelola OpenSID yaitu OpenDesa menjawab bahwa : 

Tujuan adanya OpenSID Premium dijelaskan di https://opendesa.id/opensid-premium/; yaitu untuk mengajak desa berkontribusi supaya OpenSID dapat terus dikembangkan.

Untuk memberi nilai tambah bagi desa yg telah bersedia berkontribusi, script OpenSID Premium dikunci selama enam bulan. Setelah itu, rilis tersebut menjadi OpenSID Umum dan menjadi sumber terbuka murni. 

Saat ini, di rilis OpenSID Premium, yg dapat diambil dari https://github.com/OpenSID/rilis-premium/releases, script yg terkunci di-obfuscate supaya tidak dapat diambil oleh yg akan membuat ubahan dari rilis Premium. Juga untuk menjalankan OpenSID Premium, diperlukan token yg hanya diperoleh setelah berlangganan dan hanya aktif selama masa berlangganan.

maka itu perlu adanya perubahan isi dari LICENSE Premium : 
1. Ubah LICENSE menjadi : GNU GENERAL PUBLIC LICENSE
2. Lalu update ubahan seperti file yang terlampir pada issue

[GNU GENERAL PUBLIC LICENSE.txt](https://github.com/OpenSID/OpenSID/files/13197372/GNU.GENERAL.PUBLIC.LICENSE.txt)

**Comment by eddieridwan** [comment]
Saat ini pada repo rilis Premium di https://github.com/OpenSID/rilis-premium, terbaca readme dan licence yg berlaku bagi rilis Umum yang sumber terbuka murni. Sedangkan rilis Premium untuk menyediakan rilis bagi yang berlangganan Premium, sehingga mengakibatkan salah pengertian. Yaitu, ada yg menganggap rilis Premium sumber terbuka dan bebas diubah.

Readme dan lisensi perlu diperbaiki menjelaskan perbedaan Umum dan Premium dan perbedaan lisensi keduanya.

Naskah readme dan lisensi perlu disetujui Direktur Pengembangan Aplikasi sebelum digabung.
