### ISSUE TITLE
Bug/error: tanggal peristiwa

### ISSUE THREAD

**Issue by afri18** [OpenSID/OpenSID#7282]
### Jelaskan error yg dialami

tanggal peristiwa berubah menjadi tanggal lahir saat edit biodata

### Cara untuk mereplikasi errornya

seharusnya tanggal peristiwa tidak berubah saat edit biodata penduduk

### Hasil yg diharapkan

tanggal peristiwa tidak berubah saat edit biodata penduduk

### Tangkapan layar dan log error

table log penduduk
![image](https://github.com/OpenSID/OpenSID/assets/6611881/8788c5d4-b2e2-4e11-b567-ecf74204676a)

log penduduk aplikasi
![image](https://github.com/OpenSID/OpenSID/assets/6611881/25c0c76b-d758-4520-aa41-fbf582242e17)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2310.0.3

### Tema Yang Digunakan

denatra

### Informasi tambahan

tanggal peristiewa tidak berubah walau biodata penduduk dirubah berkali kali, yg berubah hanya tanggal diperbaruhi/update

**Comment by agungsugiarto** [comment]
saya tidak menemukan masalah, mas @andifahruddinakas bisa bantu replikasi?

**Comment by agungsugiarto** [comment]
Mas @akas issue ini sepertinya sudah dikerjakan di pr ini? https://github.com/OpenSID/premium/pull/3092
