### ISSUE TITLE
Penyesuaian Lampiran F-2.01

### ISSUE THREAD

**Issue by PemdesAdiwarno** [OpenSID/OpenSID#7284]
### Jelaskan error yg dialami

Pada lampiran F-2.01 saat ini (lampiran kematian/kelahiran) hanya tersedia Form Kelahiran/Form Kematian

### Cara untuk mereplikasi errornya

1. Buat Surat Keterangan Kelahiran
View Lampiran
![image](https://github.com/OpenSID/OpenSID/assets/124587672/3a931a84-a82b-42c2-9d90-97eb2e3d3f72)

### Hasil yg diharapkan

Menyesuaikan dengan Petunjuk Tekhnis Pelayanan Pencatatan Sipil Kepmendagri Nomor 400.8.2-5484.DUKCAPIL Tanggal 30 Desember 2022 Bahwa lampiran F-2.01 tercetak seluruhnya walaupun hanya beberapa form yang diisi.

![image](https://github.com/OpenSID/OpenSID/assets/124587672/68551d22-3ae7-41aa-b884-df3148f1ea9a)
![image](https://github.com/OpenSID/OpenSID/assets/124587672/7dbb3d72-c22a-4515-a527-fa031640102c)
![image](https://github.com/OpenSID/OpenSID/assets/124587672/33b8bc0d-659f-4d6b-9217-1ccdba9a1ff2)
![image](https://github.com/OpenSID/OpenSID/assets/124587672/59e48db9-88bb-489a-b9d6-74601f9d7031)

Lampiran : https://disdukcapil.cirebonkab.go.id/wp-content/uploads/2023/03/buku-petunjuk-teknis-pelayanan-pencapil4.pdf

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

23.10.0.2-premium

### Tema Yang Digunakan

denava

### Informasi tambahan

-

**Comment by Wiliyantoro** [comment]
di kabupaten kami juga demikian
Opsi: Tambah pengaturan khusus f.2.0.1 tampilkan lampiran yang terisi dan tampilkan seluruh lampiran

**Comment by andifahruddinakas** [comment]
untuk lampiran bentuk rtf sudah tidak dikembangkan lg.

untuk lampiran ini akan disesuaikan menggunakan format tinymce agar pengguna bisa lebih leluasa menyesuaikan formatnya.

**Comment by andifahruddinakas** [comment]
Penambahan : 
- [ ] saat isi form data surat, bagian akhir tersedia pilihan cetak lampiran semua atau yang ada datanya saja. (default semua)
