### ISSUE TITLE
Bug/error: Penggunaan Font Upload dari User belum berfungsi di TinyMCE

### ISSUE THREAD

**Issue by Wiliyantoro** [OpenSID/OpenSID#7285]
### Jelaskan error yg dialami

font yang di upload user dalam bentuk format .ttf belum berfungsi / ada pengaturan lain yang terlewatkan ?
1. pengaturan surat
2. menu lainnya
3. upload font
==================
1. Pengaturan Header
ketika saya copas salah satu kop surat di file word lalu paste ke pengaturan Kop Surat, saya ganti jenis fonnya ke balidb
![image](https://github.com/OpenSID/OpenSID/assets/44520382/cad13787-efb7-4ad5-8493-586e1fafa754)

klik simpan dan keluar,

2. Coba Buat Surat
coba salah satu surat apakah penerapan berhasil apa belum?
saya coba membuat surat keterangan domisili
lalu SIMPAN

3. Kemudian kita lihat dalam konsep surat, font yang tadi kita ubah ke format balidb masih belum berubah
![image](https://github.com/OpenSID/OpenSID/assets/44520382/473c1758-b707-4f19-adff-76aef91106a0)

4. coba kita cetak PDF dan hasilnya masih sama font belum berubah
![image](https://github.com/OpenSID/OpenSID/assets/44520382/7839ceb4-8901-4bbb-998f-d413bea34239)

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

font bisa diterapkan

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

devpremium

### Informasi tambahan

apakah ada pengaturan yg terlewatkan ?
ini terkait dengan issues #6546

**Comment by andifahruddinakas** [comment]
pak @Wiliyantoro, bisa sertakan font tsb pada issue.

catatan : 
- tidak semua font akan otomatis suppor pada tinymce, contoh salah 1 font yg pernah bermasalah yakni font bookman_old_style. Perlu dicari file font (.ttf) yg sesuai agar bisa support ke tinymce.

**Comment by Wiliyantoro** [comment]
/
[BALISIMBAR.zip](https://github.com/OpenSID/OpenSID/files/13215128/BALISIMBAR.zip)
Coba ini pak, ada 4 file,, akan saya coba font bali simbar yang lain

**Comment by Wiliyantoro** [comment]
https://bennylin.github.io/transliterasijawa/bali.html

**Comment by andifahruddinakas** [comment]
https://takepanbali.blogspot.com/2019/09/font-bali-jenar-std.html?m=1

**Comment by pandigresik** [comment]
Rekomendasi font nusantara dapat didownload di https://aksaradinusantara.com/
