### ISSUE TITLE
login using google recaptcha

### ISSUE THREAD

**Issue by khoiron81** [OpenSID/OpenSID#7286]
@rickzal13 , Kami usul penerapan issue ini menggunakan pendekatan berikut:

1. sediakan setting aplikasi <em>recaptcha_api_key</em>
2. pada login admin (/siteman), 
    1. tampilkan recaptcha jika <em>recaptcha_api_key</em> ada; 
    2. jika <em>recaptcha_api_key</em> tidak ada, biarkan seperti sekarang, tanpa capcha
3. pada form komentar
    1. tampilkan recaptcha jika <em>recaptcha_api_key</em> ada; 
    2. jika <em>recaptcha_api_key</em> tidak ada, biarkan seperti sekarang, dengan capcha yang ada sekarang

_Originally posted by @eddieridwan in https://github.com/OpenSID/OpenSID/issues/489#issuecomment-322101534_

**Comment by khoiron81** [comment]
Mohon maaf, apakah login dengan recaptcha ini pernah di implementasikan?

**Comment by totoprayogo1916** [comment]
> Mohon maaf, apakah login dengan recaptcha ini pernah di implementasikan?

pernah dikirim #1039

**Comment by totoprayogo1916** [comment]
Pernah juga mengimplementasikan tapi belum sempat kirim PR dan kini sudah dihapus karena sesuatu hal waktu itu ..

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/3193

pembatasan issue ini hanya pada masuk aplikasi saja
