### ISSUE TITLE
Sesuaikan ulang Surat Permohonan Duplikat Kelahiran

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#7290]
Tampilan RTF : 
<img width="692" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/3747744b-e61e-4725-bbee-bf0cca355c49">

<img width="752" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/ac8232c6-b062-499b-aee4-2d076ab82c24">

**Comment by agungsugiarto** [comment]
apa yang perlu di sesuaikan mas @andifahruddinakas ?

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/3097
