### ISSUE TITLE
Sesuaikan ulang Surat Keterangan Kelahiran

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#7299]
Tampilan RTF : 
<img width="711" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/2906e417-a926-43cd-ad11-4c62c0c94eb2">

<img width="722" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/e99dc895-8675-47b9-99b0-1fdf5832c34e">

<img width="705" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/fe4fca94-6eeb-4bc1-af56-68919b2a3029">

<img width="721" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/e14157ba-d399-40a1-af1b-c0d3d2b92e57">

<img width="692" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/7f2e5278-755a-4fbb-8f8f-f5971a773f73">

**Comment by yogiperdana** [comment]
Untuk data ayah dan ibu maunya dibuat jadi bisa ambil dari penduduk dan non penduduk apa gimana mas @andifahruddinakas

**Comment by andifahruddinakas** [comment]
> Untuk data ayah dan ibu maunya dibuat jadi bisa ambil dari penduduk dan non penduduk apa gimana mas @andifahruddinakas 

Bisa dari penduduk desa maupun luar desa

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/3127
