### ISSUE TITLE
Bug/error: Edit Anggota Lembaga

### ISSUE THREAD

**Issue by afri18** [OpenSID/OpenSID#7302]
### Jelaskan error yg dialami

Saat edit anggota lembaga ketika disimpan malah keluar dari aplikasi, saat masuk lagi di arahkan ke halaman periksa yg isinya pemeriksaan log keluarga dinyatakan ada keluarga yang belum mempunyai log keluarga baru padahal keluarga tersebut adalah pendatang (keluarga masuk).
Terpaksa halaman dikembalikan (reload) ke home lalu lihat lagi lembaga desa dan coba lihat anggota yang di edit tadi, data masih seperti awal, artinya data anggota lembaga tidak bisa di edit

### Cara untuk mereplikasi errornya

harusnya anggota lembaga dan ketua lembaga datanya bisa di edit, dan tidak ada kaitannya dengan log keluarga

### Hasil yg diharapkan

anggota lembaga bisa di edit dan disimpan secara normal

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/6611881/49d81123-f07d-4061-9703-6527215fb22f)
![image](https://github.com/OpenSID/OpenSID/assets/6611881/7df79e55-6454-4a83-8d3d-e7b60adb47ba)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2310.1.0

### Tema Yang Digunakan

denatra

### Informasi tambahan

harusnya anggota lembaga tidak terkait dengan log keluarga
kemungkinan log keluarga mendeteksi keluarga datang sebagai yg ilegal

**Comment by yogiperdana** [comment]
cara replikasinya gimana mas @andifahruddinakas atau adakah db yang bisa digunakan

**Comment by yogiperdana** [comment]
Setelah berdiskusi dengan pengguna, diperoleh kesimpulan bahwa setelah update ke 2311.0.1 bug ini sudah teratasi
