### ISSUE TITLE
Bug/error: halaman periksa

### ISSUE THREAD

**Issue by afri18** [OpenSID/OpenSID#7303]
### Jelaskan error yg dialami

halaman periksa mendeteksi keluarga datang sebagai keluarga yang tidak mempunyai log keluarga, kalau diklik perbaiki maka log keluarga menjadi keluarga baru, ini sudah terjadi di keluarga datang sebelumnya

### Cara untuk mereplikasi errornya

harusnya keluarga datang/masuk tidak di periksa sebagai keluarga yg belum mempunyai log keluarga baru

### Hasil yg diharapkan

keluarga datang/masuk tetap sebagai log keluarga baru dan tidak di periksa atau perbaiki

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/6611881/c823963f-2635-407a-b22b-6d4722d11784)
![image](https://github.com/OpenSID/OpenSID/assets/6611881/1e82ee6d-1189-4e8c-9f2a-06aa6dbef15d)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2310.1.0

### Tema Yang Digunakan

denatra

### Informasi tambahan

halaman periksa tidak bisa membaca log keluarga datang, selalu di anggap belum mempunyai log keluarga

**Comment by andifahruddinakas** [comment]
Databse terlampir

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/3082
