### ISSUE TITLE
Bug/error: Jumlah Keluarga

### ISSUE THREAD

**Issue by afri18** [OpenSID/OpenSID#7308]
### Jelaskan error yg dialami

Jumlah Keluarga Awal Bulan ini (Nopember) tidak sama dengan jumlah akhir Keluarga Bulan Lalu (Oktober), kemungkinan karna Keluarga Datang (log_keluarga_datang) masih di anggap ilegal.
terkait dengan isu halaman periksa yang menganggap keluarga datang belum mempunyai log keluarga baru

### Cara untuk mereplikasi errornya

Keluarga datang (log keluarga datang) harusnya menjadi log keluarga legal kalau di anggap ilegal berdampak pada keluarga datang harus di perbaiki menjadi log keluarga baru

### Hasil yg diharapkan

Jumlah keluarga akhir bulan lalu dengan jumlah keluarga awal bulan ini sama

### Tangkapan layar dan log error

lap bulan oktober
![image](https://github.com/OpenSID/OpenSID/assets/6611881/9b9279a5-dd1b-40a6-b2cc-7a0c9680996a)

lap bulan nopember
![image](https://github.com/OpenSID/OpenSID/assets/6611881/609fda69-405d-4eda-81a8-48c758915ead)

SELISIH 2
karna keluarga datang dianggap tidak mempunyai log

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2310.1.0

### Tema Yang Digunakan

denatra

### Informasi tambahan

kalau halaman klik perbaiki log keluarga di halaman periksa maka log keluarga datang menjadi keluarga baru

**Comment by andifahruddinakas** [comment]
Duplicate of https://github.com/OpenSID/OpenSID/issues/7275
