### ISSUE TITLE
[Usulan] untuk Pertumbuhan OpenSID 

### ISSUE THREAD

**Issue by siayi** [OpenSID/OpenSID#731]
Saya mengusulkan untuk pertumbuhan OpenSID , salah satu upayanya bisa dimasukan/didaftarkan ke programnya https://opencollective.com/

**Comment by siayi** [comment]
Saya lihat bintangnya sudah memenuhi syarat

**Comment by eddieridwan** [comment]
Sudah dibuatkan di https://opencollective.com/opensid.
