### ISSUE TITLE
Bug/error: data bagian kematian pada lampiran F-2.01 surat kematian kosong

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#7312]
### Jelaskan error yg dialami

data pada bagian kematian di surat kematian kosong : 
![image](https://github.com/OpenSID/OpenSID/assets/59082428/48079eb5-5bf4-469b-bdeb-af994e9ef3a9)

### Cara untuk mereplikasi errornya

1. Pergi cetak surat kematian 
2.  lalu lihat pada lampiran

### Hasil yg diharapkan

sesuaikan data sesuai dengan data kematian

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/59082428/f3f4bc20-38fb-4acf-9b02-11aab9318ddb)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2311.0.0

**Comment by andifahruddinakas** [comment]
mas @vickyrolanda, sy cek di bug-fix aman

**Comment by vickyrolanda** [comment]
sudah sy cek mas, ketika cek ketemu beberapa bug, termasuk ini https://github.com/OpenSID/OpenSID/issues/7341 bisa di cek lgi mas.
