### ISSUE TITLE
Bug/error: perbaiki lisensi dan readme menyesuaikan untuk Umum dan Premium

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#7313]
### Jelaskan error yg dialami

Saat ini pada repo rilis Premium di https://github.com/OpenSID/rilis-premium, terbaca readme dan licence yg berlaku bagi rilis Umum yang sumber terbuka murni. Sedangkan rilis Premium untuk menyediakan rilis bagi yang berlangganan Premium, sehingga mengakibatkan salah pengertian. Yaitu, ada yg menganggap rilis Premium sumber terbuka dan bebas diubah.

### Cara untuk mereplikasi errornya

Buka https://github.com/OpenSID/rilis-premium dan baca readme dan lisensi.

### Hasil yg diharapkan

Readme dan lisensi menjelaskan perbedaan Umum dan Premium dan perbedaan lisensi keduanya.

### Tangkapan layar dan log error

Bisa lihat pembahasan di grup OpenSID.

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

versi Premium

### Informasi tambahan

Naskah readme dan lisensi perlu disetujui Direktur Pengembangan Aplikasi sebelum digabung.

**Comment by andifahruddinakas** [comment]
Saya lihat sudah ada issuenya https://github.com/OpenSID/OpenSID/issues/7281

**Comment by eddieridwan** [comment]
Sudah ditambahkan komentar terkait di #7281 . Issue ini akan ditutup.
