### ISSUE TITLE
Penyesuaian Surat Keterangan Izin Orang Tua Suami Istri keterkaitan antara form bagian tambahan ke form bagian utama

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#7316]
### Apa kekurangan yg ingin diatasi?

Pada saat cetak Surat Keterangan Izin Orang Tua Suami Istri data form bagian penerima ijin masih tidak sinkron dengan data utama
![image](https://github.com/OpenSID/OpenSID/assets/59082428/7971b8c0-a8f8-46dd-8619-732201940cbd)

### Jelaskan solusi yg diinginkan

Saat ini sudah ada fungsi keterkaitan data antara form bagian namun pada surat ini perlu dilakukan pengaturan bawaan agar antara form bagian dapat terkait dengan data utama agar sesuai dengan data sumber pemberi ijin
![image](https://github.com/OpenSID/OpenSID/assets/59082428/b8f93140-8e59-455c-9fbb-8bb1d18b9a7f)

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

2311.0.0

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/3112
