### ISSUE TITLE
Permintaan fitur: Sesuaikan  layout pada Surat Keterangan Jual Beli

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#7317]
### Apa kekurangan yg ingin diatasi?

Karta penerapan lebel dan form bagian sudah  terimplementasi maka perlu ada penyesuaian tampilan pada surat keternagan jual beli berikut ini : 
![image](https://github.com/OpenSID/OpenSID/assets/59082428/0cf32878-5f4c-4d22-b138-b414e35df041)

### Jelaskan solusi yg diinginkan

Tampilanlayout yang di perlu di sesuaikan seperti berikut ini : 
![image](https://github.com/OpenSID/OpenSID/assets/59082428/52a6e964-6d26-4ca1-9cd1-3ddd80672eb9)

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

2311.0.0

**Comment by andifahruddinakas** [comment]
Duplicate of https://github.com/OpenSID/OpenSID/issues/7298
