### ISSUE TITLE
Permintaan fitur: Sesuaikan form bagian pada Surat Keterangan Kematian

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#7318]
### Apa kekurangan yg ingin diatasi?

Saat ini penerapan form bagian dengan data penduduk desa/ penduduk luar desa sudah bisa diterapkan maka pada bagian surat keterangan kematian perlu di sesuaikan sumber datanya. 

saat ini sumber datanya hanya dari penduduk desa seperti berikut ini : 
![image](https://github.com/OpenSID/OpenSID/assets/59082428/523a3c4f-fe0e-48f8-a758-9e1428e14986)

### Jelaskan solusi yg diinginkan

Lalu penyesuaiannya seperti berikut ini : 
![image](https://github.com/OpenSID/OpenSID/assets/59082428/f88e372f-991e-40e8-98e1-64dd0992120f)

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

2311.0.0

**Comment by andifahruddinakas** [comment]
\
Duplicate of https://github.com/OpenSID/OpenSID/issues/7300
