### ISSUE TITLE
Konversi Lampiran F-1.06

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#7319]
### Jelaskan error yg dialami

cetak surat Keterangan Beda Identitas namun pada lampiran data tidak ter isi dengan semesterinya , berikut hasil cetak pada lampiran.
![image](https://github.com/OpenSID/OpenSID/assets/59082428/dea55ba9-1356-4728-8880-9b5ef6d489aa)

### Cara untuk mereplikasi errornya

1. masuk pada cetak surat
2. cetak surat Keterangan Beda Identitas
3. lalu cek hasil cetak pada lampiran

### Hasil yg diharapkan

sesuaikan isi pada lampiran

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/59082428/34410dc4-13e6-4a7e-b51b-bdec8002acdc)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2311.0.0

**Comment by andifahruddinakas** [comment]
mas @vickyrolanda, data individu sudah tampil, namun untuk lampiran perubahannya sy lihat memang dari awal dikosongkan. Adapun jika perlu penyesuaikan mungki sebaiknya langsung di konversi jadi tinymce.

![image](https://github.com/OpenSID/OpenSID/assets/57283157/e7b9c845-80e5-4583-af49-4fe11a88cf03)
<img width="288" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/322b4e04-05cc-49e4-955e-ae7b6b082fdb">
