### ISSUE TITLE
Permintaan fitur: Sesuaikan sumber data pada Surat Keterangan Kelahiran

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#7321]
### Apa kekurangan yg ingin diatasi?

Saat ini penerapan sumber data sudah dapat di kustom maka perlu ada penyesuaian untuk sumber data surat Keterangan Kelahiran saat ini tampilan form isian & sumber data seperti berikut ini : 

![image](https://github.com/OpenSID/OpenSID/assets/59082428/0394a0ab-1e9c-4d61-a068-e7514ecccc7a)

### Jelaskan solusi yg diinginkan

yang perlu disesuaikan sumber data & layout serperti tampilan berikut ini : 

![image](https://github.com/OpenSID/OpenSID/assets/59082428/d648b95e-9a62-41c9-b38f-2a1033bf9501)

batasan pada ngerjaan issue ini terdapat hanya pada mengubah layout & penerapan form bagian.

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

2311.0.0

**Comment by andifahruddinakas** [comment]
Duplicate of https://github.com/OpenSID/OpenSID/issues/7322
