### ISSUE TITLE
Bug/error: Form isian pada Surat Keterangan Kelahiran & lampiran tidak sesuai

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#7322]
### Jelaskan error yg dialami

Jika dibandingkan dengan surat RTF banyak formisian yang tidak tersedia pada Surat Keterangan Kelahiran saat ini tampilan form surat seperti berikut ini : 
![image](https://github.com/OpenSID/OpenSID/assets/59082428/f04d3c18-4626-40c8-a575-e8a9c8d87ebc)

juga pada lampiran tidak terisi datanya.

### Cara untuk mereplikasi errornya

1. Pergi ke halaman cetak surat 
2. lalu pilih Surat Keterangan Kelahiran
3. lihat form isian 

### Hasil yg diharapkan

sesuaikan denganform isian seperti berikut iini : 
![image](https://github.com/OpenSID/OpenSID/assets/59082428/7dbdff79-434a-4f00-891d-2445fd2fb5a6)

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/59082428/94e68860-569a-40e9-bfb1-973b85045a40)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2311.0.0

**Comment by andifahruddinakas** [comment]
Duplicate of https://github.com/OpenSID/OpenSID/issues/7299
