### ISSUE TITLE
Bug:  form isian yang tidak terubah padasurat Keterangan Nikah

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#7323]
### Apa kekurangan yg ingin diatasi?

Jika mencetak surat Keterangan Nikah maka jika data tidak di isi ada banyak kode isian yang tidak terubah seperti gamabar berikut ini : 

![image](https://github.com/OpenSID/OpenSID/assets/59082428/eb687535-1d16-427e-b314-14f9d5e233f6)

### Jelaskan solusi yg diinginkan

Sesuaikan data jika kosong maka yang akantampil hanya data kosong tidak berupa kode isian.

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

2311.0.0

**Comment by andifahruddinakas** [comment]
Silahkan perubarui template bawaan
