### ISSUE TITLE
Bug/error: Penyesuaian Surat Keterangan Pengahsilan Ibu

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#7324]
### Jelaskan error yg dialami

saat ini terpantau hasil cetak pada surat : 
1. SURAT KETERANGAN PENGHASILAN IBU
2. SURAT KETERANGAN PENGHASILAN ORANG TUA

### Cara untuk mereplikasi errornya

1. Masuk ke menu cetak surat 
2. lalu pilih salah satu dari daftar surat di atas
3. dan lihat nominal yang tertera hanya ada angka namun tidak ada nominal terbilngnnya

### Hasil yg diharapkan

Sesuaikan semua surat dengan nominal terbilang

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/59082428/8bdc9a4b-3d95-4daf-add8-1446b9dba7d6)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2311.0.0

**Comment by andifahruddinakas** [comment]
untuk point 2 sudah diperbaiki melalui issue https://github.com/OpenSID/OpenSID/issues/7069

![image](https://github.com/OpenSID/OpenSID/assets/57283157/3371aee3-ffad-4c2b-af82-44273cff3470)

**Comment by andifahruddinakas** [comment]
Isse ini difokuskan pada surat keterangan penghasilan ibu.

Solusi :
- Gunakan kode isian terbilang, hitung dan opertor
- Contoh bisa melihat surat pengahasilan orang tua

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/3130
