### ISSUE TITLE
Permintaan fitur: Konversi surat RTF Keterangan Penghasilan Ayah ke TinyMCE

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#7325]
### Apa kekurangan yg ingin diatasi?

Saat ini ada surat RTF yang masih belum terkonversi ke TinyMCE yaitu Surat Keterangan Penghasilan Ayah : 
Form isian seperti berikut ini : 
![image](https://github.com/OpenSID/OpenSID/assets/59082428/856e315a-3e00-486a-868c-c65f2b0aaaba)

Lalu hasil surat seperti berikut ini : 
[surat_ket_penghasilan_ayah_3275014601977005_2023-11-06_1.pdf](https://github.com/OpenSID/OpenSID/files/13261037/surat_ket_penghasilan_ayah_3275014601977005_2023-11-06_1.pdf)

### Untuk versi OpenSID mana

2311.0.0

**Comment by andifahruddinakas** [comment]
Sudah ada sebelumnya, namu dimigrasi tidak terpanggil.

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/3117
