### ISSUE TITLE
Permintaan fitur: Sesuaikan layout Surat Keterangan Pindah Penduduk

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#7326]
### Apa kekurangan yg ingin diatasi?

saat ini form isian pada Surat Keterangan Pindah Penduduk terlihat kurang rapi jadi terkesan banyak isian tampilannya seperti berikut ini : 
![image](https://github.com/OpenSID/OpenSID/assets/59082428/7e814857-225f-43da-bfab-4d1ec901530f)

### Jelaskan solusi yg diinginkan

karna fungsi mengatur ukuran form sudah ada maka tampilan diatas dapat disesuaikan menjadi seperti berikut ini : 
![image](https://github.com/OpenSID/OpenSID/assets/59082428/c425a1ba-5a42-4388-a7fa-9a8942ef9d82)

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

2311.0.0

**Comment by andifahruddinakas** [comment]
Duplicate of https://github.com/OpenSID/OpenSID/issues/7294
