### ISSUE TITLE
Bug/error: Lampiran F-1.03, F-1.08, F-1.25, F-1.27 tidak terisi pada surat Keterangan Pindah Penduduk

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#7327]
### Jelaskan error yg dialami

Periksa semua lampiran F-1.03, F-1.08, F-1.25, F-1.27 pada surat  Keterangan Pindah Penduduk karena data tidak terisi
![image](https://github.com/OpenSID/OpenSID/assets/59082428/d1bcad8c-f37b-453e-94ec-3b9d652ec1a9)

### Cara untuk mereplikasi errornya

1. Pergi ke cetak surat
2. lalu cetak surat  Keterangan Pindah Penduduk
3. lihat hasil cetak lampiran

### Hasil yg diharapkan

sesuaikan data yang akan tampil pada lampiran

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/59082428/a810dc1c-3b96-4838-ba3d-6682014daf0e)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2311.0.0

**Comment by andifahruddinakas** [comment]
mas @vickyrolanda, cek di bug-fix sudah normal

**Comment by vickyrolanda** [comment]
ok sudah sy cek mas sesuai
