### ISSUE TITLE
Sesuaikan Surat Keterangan Beda Identitas

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#7329]
Tampilan RTF : 
![image](https://github.com/OpenSID/OpenSID/assets/57283157/93a65966-9532-497a-971c-3eda17c83265)

**Comment by yogiperdana** [comment]
Ini tetap pakai form biasa atau sebagian ambil dari penduduk luar desa mas? @andifahruddinakas

**Comment by andifahruddinakas** [comment]
> Ini tetap pakai form biasa atau sebagian ambil dari penduduk luar desa mas? @andifahruddinakas 

Itu pakai form biasa, karena isian itu merupakan perbaikan.

Cuma pada isian misalnya agama dibuat sebagai pilihan, maupun yg lainnya yg datanya sudah ada.

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/3118
