### ISSUE TITLE
datakeluarga

### ISSUE THREAD

**Issue by afri18** [OpenSID/OpenSID#733]
saat merubah data tanggal cetak kartu keluarga sekarang malah nggak bisa di OPENSID 2.8
![image](https://user-images.githubusercontent.com/6611881/34508783-e3450f0a-f075-11e7-99c3-c0142c35f7f7.png)

**Comment by eddieridwan** [comment]
Di http://sid.bangundesa.info tidak bermasalah.

Sepertinya di database anda ada lebih dari satu keluarga dengan Nomor KK 321412905071640. Coba di periksa dan hapus/ganti keluarga duplikat tersebut.

**Comment by afri18** [comment]
ma'af bung @eddieridwan  ternyata kesalahan saya, php edit_no_kk saya make versi saya, setelah diganti ke yg bawaannya jalan normal kembali

**Comment by MUHAMMADRANGSEL** [comment]
Mohon issue ini di closed
