### ISSUE TITLE
Surat Keterangan Beda Identitas KIS

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#7330]
Tampilan RTF
![image](https://github.com/OpenSID/OpenSID/assets/57283157/b9195f31-47f2-4b36-90ad-313b802b78e9)

**Comment by pandigresik** [comment]
Saya cek sudah sama

![image](https://github.com/OpenSID/OpenSID/assets/1853475/b6d84040-a8b3-4d1c-9dbf-cedeeb2ea7b3)

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/3121
