### ISSUE TITLE
Sesuaika Surat Keterangan Domisili

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#7331]
Pada surat RTF surat domisi menjadi 1 bagian untuk penduduk desa dan luar desa. Namun beda pada surat domisil tinymce dibedakan, karena sebelmunya belum bisa memilih keduanya.

Saat ini sudah disediakan fitur untuk memilih menggunakan penduduk desa atau luar desa, shingga surat domisili non warga perlu dihapus dari surat bawaan.

Tambahan pada surat keterangan domisi di tambahkan agar bisa memilih penduduk luar desa.

**Comment by yogiperdana** [comment]
Ini maskudnya hapus dari migrasi berdasarkan url dan template jsonnya juga mas @andifahruddinakas?

**Comment by andifahruddinakas** [comment]
> Ini maskudnya hapus dari migrasi berdasarkan url dan template jsonnya juga mas @andifahruddinakas?

Di file template saja yg ada di folder impor, yg sudah ada dibuat jd jenis 4 saja (tdk dianggap surat bawaan)

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/3119
