### ISSUE TITLE
Surat Kuasa

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#7334]
Tampilan RTF:
![image](https://github.com/OpenSID/OpenSID/assets/57283157/5732ad8d-2c58-4adf-a3c0-cee77ae638dd)

**Comment by agungsugiarto** [comment]
mas @andifahruddinakas  form untuk penduduk luar desa, yg terpakai di surat sudah sesuai, input selain itu tidak terpakai juga disurat, bisa dilihat di bawah kiri tinymce kanan rtf



![Image](https://github.com/OpenSID/OpenSID/assets/10989147/a05299d1-17c8-4d02-af8a-937f72626038)
