### ISSUE TITLE
Surat Permohonan Duplikat Surat Nikah

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#7336]
Tampilan RTF
![image](https://github.com/OpenSID/OpenSID/assets/57283157/2bb28452-7c06-4f81-865c-5290b75a9115)

**Comment by agungsugiarto** [comment]
Apa yg beda di surat ini, seharusnya sudah sesuai mas @andifahruddinakas

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/3116
