### ISSUE TITLE
Bug/error:  Salah fungsi pada tombol kembalikan pada ubah biodadata penduduk

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#7339]
### Jelaskan error yg dialami

Tombol kembalikan salah fungsi , ketika di klik mala infonya malah ingin hapus data.
![image](https://github.com/OpenSID/OpenSID/assets/59082428/2307be6e-bc04-4b56-a111-5c4cb2a1f47b)

info topupnya sepperti ini : 
![image](https://github.com/OpenSID/OpenSID/assets/59082428/b2a3dbec-31aa-460b-a9c3-c1eaa6df13cb)

### Cara untuk mereplikasi errornya

1. pilih ubah biodata penduduk
2. lalu klik kembalikan
3. lihat info popupnya

### Hasil yg diharapkan

Sesuaikan dengan fungsi seharusnya.

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/59082428/fdd50398-eef0-4590-848c-bb88ca8e4cf1)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2311.0.0

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/3134
