### ISSUE TITLE
Bug/error: gagal ubah status dasar ketika penduduk baru di tambah belum memiliki KK

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#7340]
### Jelaskan error yg dialami

Saat tambah penduduk baru lalu diubah status dasar maka akanm uncul error seperti ini : 
ERROR - 2023-11-06 21:14:58 --> Severity: error --> Exception: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'id_kk' cannot be null (SQL: insert into `log_keluarga` (`id_kk`, `id_peristiwa`, `tgl_peristiwa`, `id_pend`, `id_log_penduduk`, `updated_by`, `config_id`) values (?, 2, 2023-11-06 21:14:58, ?, 129, 1, 1)) D:\laragon\www\premium\vendor\illuminate\database\Connection.php 712

### Cara untuk mereplikasi errornya

1. Tambah penduduk masuk
2. Jangan tambahkanke KK baru
3. langsung pilih ubah status dasar
4. pilih status mati

### Hasil yg diharapkan

sesuaikan agar tidak error 

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/59082428/cab985aa-c8a8-447a-a828-909325821e47)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2311.0.0

**Comment by agungsugiarto** [comment]
saya tidak mengalami issue yang dimaksud, mas @andifahruddinakas bisa bantu replikasi?

**Comment by andifahruddinakas** [comment]
> saya tidak mengalami issue yang dimaksud, mas @andifahruddinakas bisa bantu replikasi?

buat statusnya penduduk yg dibuat jadi kepala keluarga.

<img width="390" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/5715172a-c17a-4753-8a08-d4589c60a37b">

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/3189/
