### ISSUE TITLE
Bug/error: cek kode isian pada surat keterangan kematian data tidak terubah 

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#7341]
### Jelaskan error yg dialami

Ketika uji ulang surat keterangan kematian masihada kode isian yang tidak terubah 
![image](https://github.com/OpenSID/OpenSID/assets/59082428/79da37e4-d1f6-49b7-816c-4db7a5b596a6)

### Cara untuk mereplikasi errornya

1. pilih cetak surat
2. pilih surat keterangan kematian
3. lalu cetak 
4. dan lihat ada kode isian yang tidak terubah

### Hasil yg diharapkan

jika data kosong maka kodeisian tetap terubah di kosongkan juga.

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/59082428/dbf7e5e1-6475-42a3-a2e4-3b14257c2239)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2311.0.0

**Comment by andifahruddinakas** [comment]
mas @vickyrolanda, ini sudah sesuai
![image](https://github.com/OpenSID/OpenSID/assets/57283157/e01e01e1-407c-44b9-b8b1-c27eb875403d)
