### ISSUE TITLE
Perbarui OpenSID menggunakan php 8.x

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#7344]
Saat ini OpenSID support hanya pada versi php 7.4 dan belum apa pembaruan. Padahal framework terbaru sudah menggunakan php versi terbaru. Karena menggunakan CI3 bisa cek referesh https://github.com/bcit-ci/CodeIgniter/pulls?q=is%3Apr+is%3Aclosed+php+8 yang sudah ada penggabungan terkait php 8.

Adapun kelebihan dari php 8 bisa dilihat https://www.niagahoster.co.id/blog/php-8-adalah/

**Comment by andifahruddinakas** [comment]
Untuk otomasi, bisa gunakan https://github.com/rectorphp/rector

**Comment by totoprayogo1916** [comment]
tambahan:
karena menggunakan composer, CI3-nya gunakan versi hasil pengembangan opensid (fork), 
bukan edit di direktori vendor CI nya

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/3246
