### ISSUE TITLE
Sesuaika ulang Surat Keterangan Jamkesos

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#7346]
Tampilan RTF : 
![image](https://github.com/OpenSID/OpenSID/assets/57283157/fe56107c-3d9e-43ac-8870-56cd4c528e1d)

Yang perlu diganti: 
- [ ] kode isian **No Kartu JAMKESOS** gunakan input teks (bukan teks area)

**Comment by FirlianiF** [comment]
mas @andifahruddinakas seperti nya bug ini sudah diperbaiki, di rtf dan di tiny inputan kode isian nomor kartu jamsostek nya sudah tidak menggunakan textarea, bisa di replikasi dengan restore surat nya terlebih dahulu.


![Screenshot 2023-11-08 101909](https://github.com/OpenSID/OpenSID/assets/30171560/523d4ff7-3a22-4b1f-9120-38e8e2525fb4)

**Comment by andifahruddinakas** [comment]
ok, ini sudah sesuai
