### ISSUE TITLE
Download SID

### ISSUE THREAD

**Issue by YOGAPM** [OpenSID/OpenSID#735]
Mohon informasi bagaimana caranya untuk download sid? Terima kasih

**Comment by eddieridwan** [comment]
@YOGAPM : issue bukan tempat bertanya cara menggunakan OpenSID. Silakan bergabung di https://www.facebook.com/groups/OpenSID/ dan tanyakan di situ.

Issue untuk melaporkan masalah yang betul2 bug atau untuk mengusulkan fitur yang yakin belum ada.
