### ISSUE TITLE
Bug/error: Belum tersedia pilihan Penduduk Sudah Ada pada Aksi Tambah di Tabel Keluarga

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#7350]
### Jelaskan error yg dialami

![image](https://github.com/OpenSID/OpenSID/assets/46939846/0e5e2b98-ce32-4b8c-9e68-c8e926488e73)

<img width="410" alt="image" src="https://github.com/OpenSID/OpenSID/assets/46939846/4282360f-234a-47e3-98de-ea907dd029f9">

### Cara untuk mereplikasi errornya

Buka menu Keluarga.

Dan klik Aksi Tambah pada salah satu keluarga. (belum ada pilihan Dari Penduduk Sudah Ada)

Harus masuk Aksi Rincian Anggota Keluarga tombol ungu dulu, baru ada pilihan tersebut.

### Hasil yg diharapkan

tampilkan pula pilihan Dari Penduduk Yang Sudah Ada pada Aksi Tambah Anggota Keluarga di Menu Keluarga

### Tangkapan layar dan log error

di atas

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Rilis Mendatang

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/3152
