### ISSUE TITLE
Permintaan fitur: Sediakan Laporan Khusus Dana Desa

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#7359]
### Apa kekurangan yg ingin diatasi?

<img width="960" alt="2023-11-09_09h47_13" src="https://github.com/OpenSID/OpenSID/assets/46939846/f699acea-30e0-451d-88a2-8e1b3022234f">

<img width="960" alt="2023-11-09_11h45_19" src="https://github.com/OpenSID/OpenSID/assets/46939846/b3872977-b947-4aec-9d8f-0932e3ca8eb5">

### Jelaskan solusi yg diinginkan

adanya info khusus dana desa

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

Rilis Mendatang

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/3140
