### ISSUE TITLE
Kode isian perlu disesuaikan selain teks

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#7361]
Pada kode isian ada beberapa jenis nilai, sbb:
- [ ] string (nama, pekerjaan, alamat, dll)
- [ ] int (nik, no_kk, dll)
- [ ] img (qr_code, foto_penduduk, logo, dll)

Dari ke 3 jenis kode tsb, int dan img tidak memerlukan konversi ke huruf besar, kecil atau lainnya.

Solusi :
- [ ] tambahkan parameter lain untuk menandakan tdk perlu di konversi ke huruf kecil atau besar.
- [ ] sesuaikan tampilan pada editor tinymce
- [ ] pada editor tinymce tdk ada muncul pilihan huruf besar, kecil atau lainnya

**Comment by agungsugiarto** [comment]
mas @andifahruddinakas, yg dipakai hanya yg `Normal` ?

**Comment by andifahruddinakas** [comment]
> mas @andifahruddinakas, yg dipakai hanya yg `Normal` ?

tidak ada pilihan.
misalkan NIK, tidak ada pilihan. jadi langsung pilih.

<img width="214" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/06b78ee4-77e3-4d47-a821-f766004f70cd">

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/3158
