### ISSUE TITLE
Pengaturan untuk aktifkan / nonaktifkan headline ( berita utama )

### ISSUE THREAD

**Issue by pandigresik** [OpenSID/OpenSID#7362]
### Apa kekurangan yg ingin diatasi?

Belum tersedia fitur untuk mengaktifkan atau menonaktifkan headline, saat ini hanya menjadikan artikel sebagai headline saja ( artinya hanya menggantikan headline bukan menonaktifkan)

![image](https://github.com/OpenSID/OpenSID/assets/1853475/5e04aa57-566a-4934-8748-7447ec980542)

### Jelaskan solusi yg diinginkan

- [ ] Disediakan fitur untuk menonaktifkan / aktifkan headline
- [ ] Ubah ejaan menjadi bahasa indonesia misalya **Berita Utama**

### Apakah ada alternatif lain

Tidak ada

### Untuk versi OpenSID mana

2312.0.0 premium

### Informasi tambahan

1. Masuk ke menu Admin web - Artikel
2. Jadikan salah satu artikel sebagai headline
3. Tidak bisa menonaktifkan headline tersebut, yang bisa hanya mengganti artikel lain sebagai headline

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/3187
