### ISSUE TITLE
Bug/error: Alamat pada modul kependudukan kosong

### ISSUE THREAD

**Issue by pandigresik** [OpenSID/OpenSID#7363]
### Jelaskan error yg dialami

Alamat pada modul penduduk tidak tampil padahal ketika dicek di detail kartu keluarga alamatnya ada

### Cara untuk mereplikasi errornya

1. Pergi ke halaman kependudukan - penduduk
2. Setelah tampil cek pada kolom alamat, maka alamatnya terlihat kosong
3. Namun ketika diklik pada no_kk alamat keluarga tersebut ada

### Hasil yg diharapkan

Alamat tampil juga pada modul penduduk

### Tangkapan layar dan log error

Pada penduduk Ahmad Habib alamatnya kosong
![photo_6233154435048127497_w](https://github.com/OpenSID/OpenSID/assets/1853475/91156c75-97d9-436b-ae3f-17ec558e1b4c)

Ketika diklik no_kk tampil alamat seperti dibawah ini
![photo_6233154435048127498_w](https://github.com/OpenSID/OpenSID/assets/1853475/6124dba5-21e8-4c66-923f-1c404f51db1d)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2312.0.0-premium

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/3151
