### ISSUE TITLE
Permintaan fitur: kirim login admin yg berhasil ke log

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#7364]
### Apa kekurangan yg ingin diatasi?

Saat ini tidak ada jejak kapan akun admin digunakan, dan dari mana. Info ini diperlukan untuk melacak jika diduga terjadi akses yg tidak seharusnya.

### Jelaskan solusi yg diinginkan

Catat setiap kali adanya login menggunakan akun admin ke log. Catat info yg memberi keterangan penting terkait akses login tersebut, seperti:

1. date
2. IP address
3. user-agent
4. referer
5. info lain yg mungkin bermanfaat dari httprequest headers (https://en.wikipedia.org/wiki/List_of_HTTP_header_fields)

### Apakah ada alternatif lain

Tidak ada.

### Untuk versi OpenSID mana

v2311 premium

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/3172
