### ISSUE TITLE
Permintaan fitur: kirim notifikasi jika ada login admin dari lokasi yg tidak biasa

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#7366]
### Apa kekurangan yg ingin diatasi?

Saat ini tidak diketahui jika ada login dari pihak yg bukan pengguna admin biasa, yaitu yg login dari lokasi atau gawai yg tidak biasa digunakan.

### Jelaskan solusi yg diinginkan

Pada setiap login akun admin yang berhasil, deteksi apakah dilakukan dari lokasi dan gawai yg biasa digunakan. Jika lokasi/gawai baru, kirim notifikasi ke kontak pengguna admin memberitahu dan menyarankan memeriksa akunnya. Bisa lihat contoh dari aplikasi lain untuk isi notifikasinya.

### Apakah ada alternatif lain

Tidak ada

### Untuk versi OpenSID mana

v2311 premium

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/3173
