### ISSUE TITLE
Bug/error: kepala keluarga perempuan

### ISSUE THREAD

**Issue by afri18** [OpenSID/OpenSID#7367]
### Jelaskan error yg dialami

saat kepala keluarga perempuan ikut suaminya Automatis Nomor Kartu Kelurga HANGUS/TERHAPUS (seharusnya), tapi di periksa di laporan bulanan tidak ada laporan keluarga hilang, seharusnya ada, sedangkan jumlah keluarga jadi berkurang (peristiwa/log pengurangan tidak tercatat)

### Cara untuk mereplikasi errornya

seharusnya Kepala Keuarga perempuan bila dipecah Kartu Keluarganya Automatis jadi pengurangan Keluarga Hilang dikarnakan ikut Nomor Kartu Keluarga Suaminya
Jadi di catatan peristiwa adalah Ikut Suami

### Hasil yg diharapkan

Tercatat di laporan bulanan di Keluarga Hilang bulan ini

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/6611881/e5d73d24-7c16-4c30-9e01-9b21b4f07bd7)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2311.0.1

### Tema Yang Digunakan

denatra

### Informasi tambahan

agar peristiwa kepala keluarga perempuan yg ikut suami tercatat dalam log peristiwa

**Comment by andifahruddinakas** [comment]
https://github.com/OpenSID/OpenSID/issues/7399
