### ISSUE TITLE
Bug/error: Pencarian pada arsip layanan persuratan

### ISSUE THREAD

**Issue by mah-mudi** [OpenSID/OpenSID#7368]
### Jelaskan error yg dialami

Pencarian pada arsip layanan persuratan tidak berfungsi sebagaimana mestinya

### Cara untuk mereplikasi errornya

1. layanan surat
2. arsip
3. pencarian

### Hasil yg diharapkan

Pencarian pada arsip layanan persuratan dapat berfungsi sebagaimana mestinya

### Tangkapan layar dan log error

https://github.com/OpenSID/OpenSID/assets/57661283/eed5e59a-ec94-45db-be2d-0402c6b91be0

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2311.0.1-premium

### Tema Yang Digunakan

natra

### Informasi tambahan

https://berputar.opendesa.id/

**Comment by andifahruddinakas** [comment]
mas @agungsugiarto, @mah-mudi, perlu diketahui untuk pencarian yang bisa dilakukan pada arsip surat berupa "nama penduduk, no_surat, penanda tangan saja. Adapun untuk nama surat bisa lakukan filter langsung.

![image](https://github.com/OpenSID/OpenSID/assets/57283157/12c81290-af9d-4ef7-870c-d14483d90ec7)

**Comment by andifahruddinakas** [comment]
> mas @agungsugiarto, @mah-mudi, perlu diketahui untuk pencarian yang bisa dilakukan pada arsip surat berupa "nama penduduk, no_surat, penanda tangan saja. Adapun untuk nama surat bisa lakukan filter langsung.
> 
> ![image](https://user-images.githubusercontent.com/57283157/283351126-12c81290-af9d-4ef7-870c-d14483d90ec7.png)

pak @mah-mudi, untuk kasus seperti ini bukan bug. modul ini hanya menyediakan pencarian sesuai sy jelaskan seperti di atas. Adapun jika memerlukan pencarian spesifik bisa dibuatkan issue permintaan fitur. Karena di modul2 lain juga sama.

Contoh di modul penduduk : 
- tidak semua kolom disediakan dalam pencarian, kolom yg penting saja yg ditambahkan. adapun pencarian lebih detail dibuat menjadi 1 fungsi sebgaia pencarian spesifik.
![image](https://github.com/OpenSID/OpenSID/assets/57283157/badd65ac-b75b-4e76-a453-25a8d047d332)

keluarga
<img width="524" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/bb8fc30d-0286-4ff3-b8c0-fe00b2afe6df">

Informasi Publik
![image](https://github.com/OpenSID/OpenSID/assets/57283157/4912afe6-1241-4110-8ae7-af107365e6ac)
