### ISSUE TITLE
Bug/error: Tabel di Artikel

### ISSUE THREAD

**Issue by afri18** [OpenSID/OpenSID#7369]
### Jelaskan error yg dialami

Bila Artikel menampilkan Tabel saat di buka di Handphon (HP) tidak responsive (tidak bisa geser geser)

### Cara untuk mereplikasi errornya

Jadikan halaman artikel yang menggunakan Table di artikel bisa di geser agar isi bisa terlihat semua

### Hasil yg diharapkan

Artikel menggunakan tabel bisa responsive saat di buka di HP

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/6611881/e9cb0f36-fa50-4d4e-a20b-f47be8c47ed3)

tidak bisa geser akibatnya nggak bisa lihat utuh isi tabel

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2311.0.1

### Tema Yang Digunakan

denatra

### Informasi tambahan

sebaiknya semua tampilan web baik artikel dan lainnya responsive terhadap perangkat yang di gunakan, agar pengunjung nggak kecewa

**Comment by andifahruddinakas** [comment]
Gunakan tema bawaan untuk setiap kasus tema

**Comment by afri18** [comment]
> Gunakan tema bawaan untuk setiap kasus tema

sama aja, make tema bawaan juga tidak bisa ...

**Comment by afri18** [comment]
ternyata penyakit tema

**Comment by ariandii** [comment]
tema normal, tidak ada penyakit.

contohnya:
https://www.natairaya.desa.id/artikel/2021/2/16/laporan-pertanggungjawaban-realisasi-apbdesa-natai-raya-tahun-anggaran-2020
