### ISSUE TITLE
Surat Keterangan Kematian

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#7379]
Buat pratinjau menggunakan data dummy, saat ini belum sesuai :
[Surat Keterangan Kematian.pdf](https://github.com/OpenSID/OpenSID/files/13371981/Surat.Keterangan.Kematian.pdf)

**Comment by andifahruddinakas** [comment]
![image](https://github.com/OpenSID/OpenSID/assets/57283157/37c424d6-1ea4-4344-bba1-7a23d2a80611)

**Comment by FirlianiF** [comment]
Sudah tidak error setelah pull menggunakan bug-fix terbaru pagi ini.
![Screenshot 2023-11-21 070510](https://github.com/OpenSID/OpenSID/assets/30171560/0f1d9f84-58b7-4037-bdf6-9c0e890df309)
