### ISSUE TITLE
Bug: data statistik di menu Agama opensid 2.8

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#739]
data statistik menunjukkan minus
![untitled121](https://user-images.githubusercontent.com/35319600/34805812-80057aea-f6b2-11e7-9c80-7f6302d2082f.jpg)

**Comment by eddieridwan** [comment]
Sepertinya ini 'bug', di mana pada jumlah masing2 agama terhitung semua penduduk, termasuk yang sudah mati/hilang/pindah; sedangkan hitungan baris Total terbatas pada penduduk dengan status dasar 'hidup'.

**Comment by eddieridwan** [comment]
Sdh dicommit ke master.
