### ISSUE TITLE
Surat Keterangan Pindah Penduduk

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#7393]
Buat pratinjau menggunakan data dummy, saat ini belum sesuai :
[Surat Keterangan Pindah Penduduk.pdf](https://github.com/OpenSID/OpenSID/files/13372229/Surat.Keterangan.Pindah.Penduduk.pdf)

**Comment by andifahruddinakas** [comment]
mas @pandigresik, yang perlu disesuaika di surat ini : 
![image](https://github.com/OpenSID/OpenSID/assets/57283157/43f6f4b5-c056-4d89-a165-ca7af46e1180)

dengan kode_isian : 
- [ ] input tanggal, bisa gunakan tgl sekarang
![image](https://github.com/OpenSID/OpenSID/assets/57283157/bbd32f46-2e30-4b0d-8a89-bcfa0725974b)

- dan kode isian **Alasan Pindah** jadinya kosong, harusnya menjadi **Masukkan Alasan Pindah**

**Comment by pandigresik** [comment]
> mas @pandigresik, yang perlu disesuaika di surat ini : ![image](https://user-images.githubusercontent.com/57283157/283718683-43f6f4b5-c056-4d89-a165-ca7af46e1180.png)
> 
> dengan kode_isian :
> 
> * [ ]  input tanggal, bisa gunakan tgl sekarang
>   ![image](https://user-images.githubusercontent.com/57283157/283718933-bbd32f46-2e30-4b0d-8a89-bcfa0725974b.png)
> * dan kode isian **Alasan Pindah** jadinya kosong, harusnya menjadi **Masukkan Alasan Pindah**

Untuk alasan pindah menggunakan select-manual bukan teks, sudah diperbaiki
