### ISSUE TITLE
PERMOHONAN FORM 

### ISSUE THREAD

**Issue by ipaysx** [OpenSID/OpenSID#740]
Adakah yang sudi untuk membuatkan 
1. Surat Pindah Antar Kabupaten
2. Surat Pindah Antar Kecamatan
3. Permohonan Akta Kelahiran

file sudah saya sertakan.. trims sebelumnya.

![screenshot_6](https://user-images.githubusercontent.com/12766544/34809808-1a33e90a-f6ca-11e7-9267-050120816c5d.jpg)
![screenshot_7](https://user-images.githubusercontent.com/12766544/34809813-2662e71c-f6ca-11e7-9f74-ecfcdaf06713.jpg)
![screenshot_8](https://user-images.githubusercontent.com/12766544/34809821-2f5748d6-f6ca-11e7-828b-7e399836aea2.jpg)

[PINDAH DAN AKTA KELAHIRAN.zip](https://github.com/OpenSID/OpenSID/files/1621337/PINDAH.DAN.AKTA.KELAHIRAN.zip)

**Comment by eddieridwan** [comment]
@ipaysx : Semua jenis surat pindah itu sudah lama ada. Surat permohonan akta kelahiran juga sudah ada. Apakah anda sudah periksa di menu Cetak Surat?

**Comment by eddieridwan** [comment]
@ipaysx : Kalau ingin mengusulkan perbaikan, silakan buat issue terpisah untuk setiap surat (jangan digabung), dan lampirkan formulir resmi dari (lampiran) Peraturan Menteri yg mengatur.

Sejauh mungkin, OpenSID berusaha mengikuti format formulir baku. Anggota POKJA Analisis Kebutuhan OpenSID, terutama bung Suparman, pakar administrasi desa, mudah2an dapat memberi rekomendasi apakah suatu perubahan pada formulir baku patut dilakukan atau tidak.
