### ISSUE TITLE
Bug/error: 500 error You have an error in your SQL syntax

### ISSUE THREAD

**Issue by Mardi1231** [OpenSID/OpenSID#7400]
### Jelaskan error yg dialami

waktu mau melakukan login ke admin muncul penringatan kesalahan basis data telah terjadi
ini merupakan log dari error
<?php defined('BASEPATH') OR exit('No direct script access allowed'); ?>

ERROR - 2023-11-17 01:34:27 --> Unable to connect to the database
NOTICE - 2023-11-17 01:37:25 --> Jalankan tabel_analisis
NOTICE - 2023-11-17 01:37:25 --> Jalankan tabel_mandiri
NOTICE - 2023-11-17 01:37:25 --> Jalankan tabel_peta
NOTICE - 2023-11-17 01:37:25 --> Jalankan tabel_web
NOTICE - 2023-11-17 01:37:25 --> Jalankan tabel_pertanahan
NOTICE - 2023-11-17 01:37:25 --> Jalankan tabel_desa
NOTICE - 2023-11-17 01:37:25 --> Jalankan tabel_covid19
NOTICE - 2023-11-17 01:37:26 --> Jalankan tabel_penduduk
NOTICE - 2023-11-17 01:37:26 --> Jalankan tabel_dokumen
NOTICE - 2023-11-17 01:37:26 --> Jalankan tabel_hubung_warga
NOTICE - 2023-11-17 01:37:26 --> Jalankan tabel_inventaris
NOTICE - 2023-11-17 01:37:26 --> Jalankan tabel_buku_admin
NOTICE - 2023-11-17 01:37:26 --> Jalankan tabel_keuangan
NOTICE - 2023-11-17 01:37:27 --> Jalankan tabel_surat
NOTICE - 2023-11-17 01:37:28 --> Jalankan tabel_sinkronisasi
NOTICE - 2023-11-17 01:37:28 --> Jalankan tabel_dashboard
NOTICE - 2023-11-17 01:37:28 --> Jalankan tabel_pembangunan
NOTICE - 2023-11-17 01:37:28 --> Jalankan tabel_lapak
NOTICE - 2023-11-17 01:37:28 --> Jalankan tabel_bantuan
NOTICE - 2023-11-17 01:37:28 --> Jalankan tabel_sistem
NOTICE - 2023-11-17 01:37:28 --> Jalankan tabel_pamong
NOTICE - 2023-11-17 01:37:28 --> Jalankan tabel_keluarga
NOTICE - 2023-11-17 01:37:28 --> Jalankan tabel_pengguna
NOTICE - 2023-11-17 01:37:30 --> Jalankan tabel_ada_foreign_key
NOTICE - 2023-11-17 01:37:31 --> Jalankan buat_view
NOTICE - 2023-11-17 01:37:34 --> Berhasil Jalankan migrasi_fitur_premium_2009
NOTICE - 2023-11-17 01:37:34 --> Berhasil Jalankan migrasi_fitur_premium_2010
NOTICE - 2023-11-17 01:37:34 --> Berhasil Jalankan migrasi_fitur_premium_2011
NOTICE - 2023-11-17 01:37:34 --> Berhasil Jalankan migrasi_fitur_premium_2012
NOTICE - 2023-11-17 01:37:34 --> Berhasil Jalankan migrasi_fitur_premium_2101
NOTICE - 2023-11-17 01:37:35 --> Berhasil Jalankan migrasi_fitur_premium_2102
NOTICE - 2023-11-17 01:37:35 --> Berhasil Jalankan migrasi_fitur_premium_2103
NOTICE - 2023-11-17 01:37:35 --> Berhasil Jalankan migrasi_fitur_premium_2104
NOTICE - 2023-11-17 01:37:36 --> Berhasil Jalankan migrasi_fitur_premium_2105
NOTICE - 2023-11-17 01:37:36 --> Berhasil Jalankan migrasi_fitur_premium_2106
NOTICE - 2023-11-17 01:37:36 --> Berhasil Jalankan migrasi_fitur_premium_2107
NOTICE - 2023-11-17 01:37:37 --> Berhasil Jalankan migrasi_fitur_premium_2108
NOTICE - 2023-11-17 01:37:37 --> Berhasil Jalankan migrasi_fitur_premium_2109
NOTICE - 2023-11-17 01:37:37 --> Berhasil Jalankan migrasi_2203_ke_2204
NOTICE - 2023-11-17 01:37:37 --> Berhasil Jalankan migrasi_fitur_premium_2110
NOTICE - 2023-11-17 01:37:37 --> Berhasil Jalankan migrasi_2204_ke_2205
NOTICE - 2023-11-17 01:37:37 --> Berhasil Jalankan migrasi_fitur_premium_2111
NOTICE - 2023-11-17 01:37:37 --> Berhasil Jalankan migrasi_2205_ke_2206
NOTICE - 2023-11-17 01:37:38 --> Berhasil Jalankan migrasi_fitur_premium_2112
NOTICE - 2023-11-17 01:37:38 --> Berhasil Jalankan migrasi_2206_ke_2207
NOTICE - 2023-11-17 01:37:39 --> Berhasil Jalankan migrasi_fitur_premium_2201
NOTICE - 2023-11-17 01:37:39 --> Berhasil Jalankan migrasi_2207_ke_2208
NOTICE - 2023-11-17 01:37:39 --> Berhasil Jalankan migrasi_foto_aparatur
NOTICE - 2023-11-17 01:37:39 --> Berhasil Jalankan migrasi_fitur_premium_2202
NOTICE - 2023-11-17 01:37:39 --> Berhasil Jalankan migrasi_2208_ke_2209
NOTICE - 2023-11-17 01:37:40 --> Berhasil Jalankan migrasi_fitur_premium_2203
NOTICE - 2023-11-17 01:37:40 --> Berhasil Jalankan migrasi_2209_ke_2210
NOTICE - 2023-11-17 01:37:41 --> Berhasil Jalankan migrasi_fitur_premium_2204
NOTICE - 2023-11-17 01:37:41 --> Berhasil Jalankan migrasi_2210_ke_2211
NOTICE - 2023-11-17 01:37:42 --> Berhasil Jalankan migrasi_fitur_premium_2205
NOTICE - 2023-11-17 01:37:42 --> Berhasil Jalankan migrasi_2211_ke_2212
NOTICE - 2023-11-17 01:37:43 --> Berhasil Jalankan migrasi_fitur_premium_2206
NOTICE - 2023-11-17 01:37:43 --> Berhasil Jalankan migrasi_2212_ke_2301
NOTICE - 2023-11-17 01:37:45 --> Berhasil Jalankan migrasi_fitur_premium_2207
NOTICE - 2023-11-17 01:37:45 --> Berhasil Jalankan migrasi_2301_ke_2302
NOTICE - 2023-11-17 01:37:45 --> Berhasil Jalankan migrasi_fitur_premium_2208
NOTICE - 2023-11-17 01:37:45 --> Berhasil Jalankan migrasi_2302_ke_2303
NOTICE - 2023-11-17 01:37:46 --> Kepala Desa tidak ditemukan
NOTICE - 2023-11-17 01:37:46 --> Sekretaris Desa tidak ditemukan
NOTICE - 2023-11-17 01:37:46 --> Berhasil Jalankan migrasi_fitur_premium_2209
NOTICE - 2023-11-17 01:37:46 --> Berhasil Jalankan migrasi_2303_ke_2304
NOTICE - 2023-11-17 01:37:47 --> Berhasil Jalankan migrasi_fitur_premium_2210
NOTICE - 2023-11-17 01:37:47 --> Berhasil Jalankan migrasi_2304_ke_2305
NOTICE - 2023-11-17 01:37:48 --> Berhasil Jalankan migrasi_fitur_premium_2211
NOTICE - 2023-11-17 01:37:48 --> Berhasil Jalankan migrasi_2305_ke_2306
NOTICE - 2023-11-17 01:37:48 --> Berhasil Jalankan migrasi_dtks
NOTICE - 2023-11-17 01:37:48 --> Berhasil Jalankan migrasi_fitur_premium_2212
NOTICE - 2023-11-17 01:37:48 --> Berhasil Jalankan migrasi_2306_ke_2307
NOTICE - 2023-11-17 01:37:49 --> Berhasil Jalankan migrasi_fitur_premium_2301
NOTICE - 2023-11-17 01:37:49 --> Berhasil Jalankan migrasi_2307_ke_2308
NOTICE - 2023-11-17 01:37:49 --> Berhasil Jalankan migrasi_fitur_premium_2302
NOTICE - 2023-11-17 01:37:49 --> Berhasil Jalankan migrasi_2308_ke_2309
NOTICE - 2023-11-17 01:37:49 --> Berhasil Jalankan migrasi_fitur_premium_2303
NOTICE - 2023-11-17 01:37:49 --> Berhasil Jalankan migrasi_2309_ke_2310
NOTICE - 2023-11-17 01:37:49 --> Berhasil Jalankan migrasi_fitur_premium_2304
NOTICE - 2023-11-17 01:37:49 --> Berhasil Jalankan migrasi_fitur_premium_2305
NOTICE - 2023-11-17 01:37:49 --> Berhasil Jalankan migrasi_2311_ke_2312
NOTICE - 2023-11-17 01:37:49 --> Berhasil Jalankan migrasi_layanan
NOTICE - 2023-11-17 01:37:51 --> Versi database sudah terbaru
ERROR - 2023-11-17 01:38:08 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')
 LIMIT 1' at line 4 - Invalid query: SELECT `url`
FROM `setting_modul`
WHERE `aktif` = 1
AND `url` IN()
 LIMIT 1
ERROR - 2023-11-17 01:38:44 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')
 LIMIT 1' at line 4 - Invalid query: SELECT `url`
FROM `setting_modul`
WHERE `aktif` = 1
AND `url` IN()
 LIMIT 1
ERROR - 2023-11-17 01:39:06 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')
 LIMIT 1' at line 4 - Invalid query: SELECT `url`
FROM `setting_modul`
WHERE `aktif` = 1
AND `url` IN()
 LIMIT 1
ERROR - 2023-11-17 01:39:38 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')
 LIMIT 1' at line 4 - Invalid query: SELECT `url`
FROM `setting_modul`
WHERE `aktif` = 1
AND `url` IN()
 LIMIT 1
ERROR - 2023-11-17 01:40:39 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')
 LIMIT 1' at line 4 - Invalid query: SELECT `url`
FROM `setting_modul`
WHERE `aktif` = 1
AND `url` IN()
 LIMIT 1
ERROR - 2023-11-17 01:41:39 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')
 LIMIT 1' at line 4 - Invalid query: SELECT `url`
FROM `setting_modul`
WHERE `aktif` = 1
AND `url` IN()
 LIMIT 1
ERROR - 2023-11-17 01:42:18 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')
 LIMIT 1' at line 4 - Invalid query: SELECT `url`
FROM `setting_modul`
WHERE `aktif` = 1
AND `url` IN()
 LIMIT 1
ERROR - 2023-11-17 01:42:32 --> 404 Page Not Found: Main%20error/index
ERROR - 2023-11-17 01:46:32 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')
 LIMIT 1' at line 4 - Invalid query: SELECT `url`
FROM `setting_modul`
WHERE `aktif` = 1
AND `url` IN()
 LIMIT 1
ERROR - 2023-11-17 01:47:58 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')
 LIMIT 1' at line 4 - Invalid query: SELECT `url`
FROM `setting_modul`
WHERE `aktif` = 1
AND `url` IN()
 LIMIT 1
ERROR - 2023-11-17 02:37:17 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')
 LIMIT 1' at line 4 - Invalid query: SELECT `url`
FROM `setting_modul`
WHERE `aktif` = 1
AND `url` IN()
 LIMIT 1
ERROR - 2023-11-17 02:59:29 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')
 LIMIT 1' at line 4 - Invalid query: SELECT `url`
FROM `setting_modul`
WHERE `aktif` = 1
AND `url` IN()
 LIMIT 1

### Cara untuk mereplikasi errornya

tidak ada

### Hasil yg diharapkan

bisa di fix secepat mungkin

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/108390374/45c51373-855e-479d-b43c-7cfd4cf3a05e)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

mis. v2306.0.0

**Comment by andifahruddinakas** [comment]
Bersihkan cache aplikasi
