### ISSUE TITLE
Sederhanakan perintah untuk tulis Log Notifikasi.

### ISSUE THREAD

**Issue by apidong** [OpenSID/OpenSID#7401]
- [x] buat fungsi untuk membuat log notifikasi, diletakan  di my_controller agar bisa dipanggil di admin_controller
- [x] hapus kolom device dan token di table log_notifikasi_admin, karena kolom tersebut tidak terpakai

issue ini juga berhubungan dengan issue https://github.com/OpenSID/wiki-mobile/issues/183

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/3171
