### ISSUE TITLE
Bug/error: Membuat Halaman di Surat TinyMCe

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#7408]
### Jelaskan error yg dialami

Ketika membuat surat yang terdiri dari 2 halaman pada waktu tinjau PDF 
<img width="813" alt="Screenshot 2023-11-20 185209" src="https://github.com/OpenSID/OpenSID/assets/25834335/35baf6a5-eba5-468e-8016-931041303eb0">

<img width="756" alt="Screenshot 2023-11-20 185148" src="https://github.com/OpenSID/OpenSID/assets/25834335/51926180-4f97-4656-aaec-1fdce9d1f3a9">

### Cara untuk mereplikasi errornya

Masuk Ke menu Layanan Surat Pengaturan SUrat buat surat yang terdiri dari 2 halaman

### Hasil yg diharapkan

Membuat surat yang terdiri dari 2 halaman bisa

### Tangkapan layar dan log error

<img width="756" alt="Screenshot 2023-11-20 185148" src="https://github.com/OpenSID/OpenSID/assets/25834335/9abf2035-98e6-49da-bcbf-c8e0b3e99360">
<img width="813" alt="Screenshot 2023-11-20 185209" src="https://github.com/OpenSID/OpenSID/assets/25834335/ae3dc5e2-59d9-417c-99c5-c7980d2484dc">

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2311.1.0

**Comment by vickyrolanda** [comment]
Cara mereplikasikannya adalah : 
1. masuk ke halaman tambah surat
2. salin template dari template bawaan 
3. lalu tambah halaman 
4. dan klik pertinjau 

bug ini terjadi pada buat surat & edit surat TinyMCE setiap menambah halaman baru atau memiliki 2 halaman tidak dapat melakukan tinjau pdf.

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/3191

**Comment by MUHAMMADRANGSEL** [comment]
saya cek di versi 2311.1.1 masih tidak bisa, masih error
<img width="959" alt="image" src="https://github.com/OpenSID/OpenSID/assets/25834335/60e1a75d-765a-4aa6-95c4-527b7e6c850e">

<html>
<body>

Severity: error --> Exception: Call to a member function exists() on null /home/berputar.opendesa.id/public_html/donjo-app/core/MY_Log.php(206) : eval()'d code(1) : eval()'d code 93
--



</body>
</html>

**Comment by MUHAMMADRANGSEL** [comment]
malah sekarang tinjau pdf 1 halaman error
<img width="938" alt="image" src="https://github.com/OpenSID/OpenSID/assets/25834335/60476455-34db-4696-b3c9-73efd23d1ca6">
di menu layanan surat/ pengaturan
