### ISSUE TITLE
BUG: waktu kosongkan db ada error

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#741]
pada rilis pasca 2.8 ketika kosongkan db terjadi error number 1701 dan juga menu penduduk tidak terhapus seperti data wilayah administrasi, data keluarga dan data penduduk tidak terhapus tampilan erorrnya seperti dibawah ini :

**Comment by MUHAMMADRANGSEL** [comment]
![screenshot 2018-01-13 18 17 59](https://user-images.githubusercontent.com/25834335/34906887-1d269d36-f8b1-11e7-851b-65fb2722c8c5.jpg)

**Comment by eddieridwan** [comment]
Sdh dicommit ke master.
