### ISSUE TITLE
Bug/error: Gagal Edit Kategori Artikel

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#7417]
### Jelaskan error yg dialami

<img width="784" alt="image" src="https://github.com/OpenSID/OpenSID/assets/46939846/55610836-81ed-414a-82f7-b11a76ba2101">

### Cara untuk mereplikasi errornya

Masuk Admin Web -> Menu
Pilih Menu Dinamis / Kategori
Edit salah satu Kategori (atau tambah dulu jika belum ada)

Ubah nama dengan merubah huruf kecil ke besar atau sebaliknya (misal nama awal berita pkk, ingin diubah jadi Berita PKK)-> dan simpan. Maka akan gagal sesuai gambar di atas.

### Hasil yg diharapkan

normal.

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Seluruhnya

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/3196
