### ISSUE TITLE
Statistik Kepala Keluarga Berdasarkan Jenis kelamin

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#743]
Perlu dibuatkan Statistik Kepala Keluarga berdasarkan Jenis Kelamin
![screenshot 2018-01-14 00 29 14](https://user-images.githubusercontent.com/25834335/34907945-1319381a-f8c2-11e7-83c4-1e02b812d823.jpg)

**Comment by eddieridwan** [comment]
@MUHAMMADRANGSEL apakah maksudnya untuk widget atau statistik di web?

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3474
