### ISSUE TITLE
Permintaan fitur: sesuaikan setruktur konten website desa

### ISSUE THREAD

**Issue by dobbleone** [OpenSID/OpenSID#7431]
### Apa kekurangan yg ingin diatasi?

- tidak ada perbedaan antara berita desa dan halaman statis lainya sehingga konten halaman statis yang tidak ingin di tampilkan sebagai berita desa akan ditampilkan juga sebagai berita desa pada halaman beranda web desa

### Jelaskan solusi yg diinginkan

pisahkan modul antara berita desa dan halaman statis kemudian  pada modul berita dan halaman statis dapat dibuat kategori baru yang dapat di gunakan pada masing-masing modul.
referensi https://wordpress.com/id/support/pos-vs-halaman/ 

### Apakah ada alternatif lain

belum diketahui

### Untuk versi OpenSID mana

opensid-umum

**Comment by andifahruddinakas** [comment]
Sudah diterapkan
