### ISSUE TITLE
Open SID

### ISSUE THREAD

**Issue by Syarif78** [OpenSID/OpenSID#7433]
![IMG_20231117_200326_699.jpg](https://github.com/OpenSID/OpenSID/assets/107384733/1c4d80a6-5f31-4ce1-a5ae-07285caf729b)

**Comment by eddieridwan** [comment]
@syarf mohon tidak gunakan issue di Github untuk menyebarkan info. Issue di Github khusus untuk kegiatan pengembangan aplikasi secara teknis.

Silakan muat berita desa anda di FB OpenDesa ataupun di berbagai grup Telegram yg dikelola oleh OpenDesa.

**Comment by Syarif78** [comment]
Siap... Mohon maaf Pak 🙏
