### ISSUE TITLE
Permintaan fitur: tambahkan Tooltip pada setiap Tombol?button

### ISSUE THREAD

**Issue by Agungf19** [OpenSID/OpenSID#7437]
### Apa kekurangan yg ingin diatasi?

![image](https://github.com/OpenSID/OpenSID/assets/43205017/32c89c40-6002-4ba0-8ba7-e624065f9ff2)

contoh nya pada gambar tersebut, saya kurang tahu fungsi button tersebut untuk apa, yg saya tau hanya button untuk hapus saja, lainya tidak tahu

### Jelaskan solusi yg diinginkan

jadi dengan adanya tooltips pengguna yang awam seperti saya bisa tau fungsi button tersebut untuk apa

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

Versi 2311.1.1-premium

### Informasi tambahan

-

**Comment by andifahruddinakas** [comment]
mas @apidong, cek juga dibagian kategori dinamis saat tambah/ubah

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/3251
