### ISSUE TITLE
Bug/error: TinyMCE lampiran gambar pada surat tidak muncul

### ISSUE THREAD

**Issue by Wiliyantoro** [OpenSID/OpenSID#7438]
### Jelaskan error yg dialami

saat melakukan pembuatan surat, lampiran image pada kop surat tidak muncul saat pratinjau ataupun cetak pdf
tapi di pengaturan surat pada bagian header muncul normal.

### Cara untuk mereplikasi errornya

layanan surat -> cetak surat

### Hasil yg diharapkan

lampiran gambar bisa terpanggil di header seperti sebelum update

### Tangkapan layar dan log error

![SOURCE CODE KOP PENGATURAN](https://github.com/OpenSID/OpenSID/assets/44520382/ad8f8c82-adb9-43fe-ad5a-b311efe35322)
sc di atas di pengaturan surat
![SC PRATINJAU](https://github.com/OpenSID/OpenSID/assets/44520382/103eac2d-58fb-4560-9cfc-d9904772e522)
sc di atas saat melakukan pratinjau

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

OpenSID 2311.1.1-premium

### Informasi tambahan

di berputar juga mengalami hal yang sama

**Comment by andifahruddinakas** [comment]
cek https://forum.opendesa.id/d/311-setelah-update-231111-fungsi-tinymce-tertentu-tidak-bisa-digunakan
