### ISSUE TITLE
Permintaan fitur: Media Sosil Dinamis

### ISSUE THREAD

**Issue by bangjin2024** [OpenSID/OpenSID#7452]
### Apa kekurangan yg ingin diatasi?

1. Penambahan **TikTok** di Menu MEDIA SOSIAL
2. Penambahan **UPLOAD SCAN C** Desa pada Menu PERTANAHAN

### Jelaskan solusi yg diinginkan

1. Banyak permintaan adanya Medsos TikTok
2. Gambar Scan Buku Letter C Desa sebagai bentuk Digitalisasi Arsip pertanahan

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

V2312 umum

**Comment by andifahruddinakas** [comment]
mas @bangjin2024, issue ini perlu dipisah : 
1. terkait medsos tiktok
2. terkait upload scan cdesa

**Comment by bangjin2024** [comment]
Penambahan TikTok pada Fitur Media Sosial

**Comment by andifahruddinakas** [comment]
Issue ini dipisahkan dan dibuat lebih spesifik terkait modul media sosial dibuat dinamis.

**Comment by andifahruddinakas** [comment]
pak @bangjin2024, untuk upload c-desa ada di issue https://github.com/OpenSID/OpenSID/issues/4619
