### ISSUE TITLE
Bug/error: Perbaiki Halaman Offline Mode

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#7454]
### Jelaskan error yg dialami

```
<!DOCTYPE html>
<html>
<head>
	<title>Offline Mode - Desa Natai Raya</title>
</head>
<body>
	<br/><br/><br/>
	<div align="center">
					<img class="profile-user-img img-responsive img-circle" src="
```

### Cara untuk mereplikasi errornya

Masuk menu Pengaturan -> Aplikasi

Buat halaman agar Offline Mode, lalu akses web nya. maka akan terhenti di src="

### Hasil yg diharapkan

Normal kembali,

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Terbaru

**Comment by yogiperdana** [comment]
![image](https://github.com/OpenSID/OpenSID/assets/14155050/8793a579-b18d-4c72-ad3e-3923dadca7ae)
 Saya coba normal mas @andifahruddinakas

**Comment by ariandii** [comment]
bisa tes

https://hargopancuran.opendesa.id/

view-source:https://hargopancuran.opendesa.id/

dan terjadi di beberapa web lainnya. termasuk natairaya dan nataibaru.

**Comment by ariandii** [comment]
Log nya adalah:

Severity: error --> Exception: Call to undefined function LogoDesa() /home/nataibaru/desa/offline_mode.php 10

**Comment by yogiperdana** [comment]
Apakah berkenan untuk memberikan akses servernya pak pak? Karena saya coba di berputas juga normal. Jika berkenan mohon di japri via telegram

**Comment by ariandii** [comment]
terlihat domain di atas .opendesa.id bisa login melalui client area.

**Comment by yogiperdana** [comment]
isi file desa/offline mode.php berbeda dengan versi terbaru mas @andifahruddinakas 

Saat ini saya samakan dengan versi terbaru sudah normal

**Comment by yogiperdana** [comment]
![image](https://github.com/OpenSID/OpenSID/assets/14155050/3a720937-d130-4f53-b0e9-7e7e713d623f)

**Comment by ariandii** [comment]
dengan demikian apakah perlu ada migrasi agar pengguna lama yg sudah lama ada folder desa menyesuaikan file php nya?

ketika ada ubahan di dalam folder desa ciptaan sistem di versi baru.

termasuk file lain yang alami perubahan selain offline_mode.php tsb.

**Comment by yogiperdana** [comment]
Harusnya demikian pak. Atau apakah ada usulan perbaikan lain mas @andifahruddinakas?
