### ISSUE TITLE
Bug/error: Pengaturan Kolom Layout Tidak berpengaruh pada pengaturan Kolom

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#7460]
### Jelaskan error yg dialami

Pengaturan kolom sudah di terapkan pada surat buatan baru seperti gamabr di bawah ini: 
![image](https://github.com/OpenSID/OpenSID/assets/59082428/7f02c635-dd7f-44db-973b-43b854f8a219)

namun hasilnya menjadi seperti ini : 
![image](https://github.com/OpenSID/OpenSID/assets/59082428/23ad81c3-21f6-4cc4-8971-0f587fdb04d9)

### Cara untuk mereplikasi errornya

1. Buat surat baru
2. Atur kode isian 
3. Sesuaikan kolom dengan grid col-6 & col-6 
4. Seharusnya form isian berada samping - sampingan

### Hasil yg diharapkan

sesuai dengan fungsi pada fitur tersebut

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/59082428/e8d75660-a94c-4ad6-9c22-de843d0a5eed)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2311.1.1

**Comment by pandigresik** [comment]
akan berada di posisi samping jika memiliki label yang sama. Bisa lihat contohnya di surat nikah bagian data perkawinan
