### ISSUE TITLE
Bug/error: Tombol  uduh pada klasifikasi surat tidak ada data

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#7461]
### Jelaskan error yg dialami

Ketika klik undu pada kode klasifikasi surat maka tampilannya kosong seperti dibawah ini : 
![image](https://github.com/OpenSID/OpenSID/assets/59082428/036e3162-cc95-4c87-bf1e-ce8930be586c)

### Cara untuk mereplikasi errornya

1. Masuk ke menu sekretariat
2. lalu klik menu klasifikasi surat
3. klik tombol unduh

### Hasil yg diharapkan

sesuaikan dengan fungsi pada tombol tersebut

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/59082428/c785f789-16b5-4d56-b667-57a186da2812)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2311.1.1

**Comment by andifahruddinakas** [comment]
Permsalahan pada pramter
