### ISSUE TITLE
Bug/error: gagal import kode klasifikasi surat 

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#7462]
### Jelaskan error yg dialami

Saat import kode klasifikasi surat maka error seperti berikut ini : 
[klasifikasi_surat_2023-11-26 (1).csv](https://github.com/OpenSID/OpenSID/files/13465989/klasifikasi_surat_2023-11-26.1.csv)

Hasil importnya: 
![image](https://github.com/OpenSID/OpenSID/assets/59082428/050e56e5-ec3d-4189-8dc1-ae0bf5e75b57)

### Cara untuk mereplikasi errornya

1. Masuk ke menu sekretariat
2. lalu klik menu klasifikasi surat
3. klik tombol import

### Hasil yg diharapkan

1. Tambahkan format import atau template yang digunakan
2. sesuaikan fugnsi agar berjalan sesuai dengan template no 1

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/59082428/ceb78567-8e77-4cd7-8092-8ba8ba94b33b)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2311.1.1

**Comment by andifahruddinakas** [comment]
Impor ini perlu disesuaikan mengikuti format yang ada.
Solusi : 
- [ ] Sediakan template impor yang bisa di unduh.
- [ ] Ganti cara lama, menggunakan librari. Contoh bisa di lihat di modul bantuan.
- [ ] Template impor dan unduh hasilnya sama.

Kerjakan issue ini setelah konversi menggunakan ORM dan Blade selesai dikerjakan. Issue https://github.com/OpenSID/OpenSID/issues/7425
