### ISSUE TITLE
Bug/error: Gagal cetak surat TinyMCE jika menggunakan page break atau halaman baru

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#7463]
### Jelaskan error yg dialami

setiap cetak surat akan muncul tampilan seperti berikut ini : 
![image](https://github.com/OpenSID/OpenSID/assets/59082428/fa7990e6-0a4c-4890-b84d-ff0c2d576541)

error ini terjadi setiap menggunakan halaman baru atau page break, jika tidak menggunakan halaman baru maka cetak sudar berhasil.

### Cara untuk mereplikasi errornya

1. Buat 1 surat atau edit 1 surat 
2. Lalu pastikan isi surat template menggunakan halaman baru atau lebih dari 1 halaman
3. Simpan surat tersebut
4. lalu pergi untuk cetak surat

### Hasil yg diharapkan

Sesuaikan agar dapat dilakukan cetak surat TinyMCE

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/59082428/55d24091-7368-4346-8a2d-18f6434fd4bd)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2311.1.1

**Comment by andifahruddinakas** [comment]
mas @vickyrolanda, coba test di bug-fix

**Comment by andifahruddinakas** [comment]
Sudah disesuaikan menggunakan penyeragaman cara generate pdf.
