### ISSUE TITLE
Bug/error: masuk ke menu pendaftaran layanan mandiri page non found

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#7466]
### Jelaskan error yg dialami

ketika masuk pada menu halaman pendaftaran layanan mandiri tampilan seperti ini, namun jika akses menggunakan url tanpa ada /clear maka berjalan normal.
![image](https://github.com/OpenSID/OpenSID/assets/59082428/007002b5-327c-4ac5-bd88-f85628d50d8b)

### Cara untuk mereplikasi errornya

1. Masukke menu layanan mandiri
2. Klik menu Pendaftaran layanan mandiri

### Hasil yg diharapkan

halaman tampil seperti biasanya.

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/59082428/a8976673-067e-446a-90b8-0e385853b3b6)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2311.1.1

**Comment by andifahruddinakas** [comment]
Jalankan ulang migrasi sampai notifikasi sukses
