### ISSUE TITLE
Bug/error: Cetak surat dengam menyisipak gambar pada header tinyMCE

### ISSUE THREAD

**Issue by Wiliyantoro** [OpenSID/OpenSID#7475]
### Jelaskan error yg dialami

saat melakukan pengaturan header surat demana keterbatasan font aksara yang dapat dugunakan pada TinyMCE saat ini, pengguna menyisipkan gambar aksara pada header surat dan ukuran telah disesuaikan dan berhasil disimpan, pada saat melakukan pembuatan surat saat tekan tombol simpan, tampilan editor gambar pada kop normal / muncul, tapi saat tekan tombol pratinjau / cetak pdf terjadi error

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

bisa menampilkan kop dengan sisipan gambar

### Tangkapan layar dan log error

![Screenshot 2023-11-28 082020](https://github.com/OpenSID/OpenSID/assets/44520382/70bea6c2-9ca4-4ac2-b316-b72db720f7f7)
![Screenshot 2023-11-28 082037](https://github.com/OpenSID/OpenSID/assets/44520382/ed0d1e99-ec89-4b04-b355-41dab7827c49)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2311.2.0-premium (beta)

### Informasi tambahan

pesan error  : Html2Pdf Error [2]
Unable to get the size of the image [/home/beta.opendesa.id/public_html/assets/../desa/upload/media/baris%201.png] File: /home/beta.opendesa.id/public_html/vendor/spipu/html2pdf/src/Html2Pdf.php Line: 1526 Image Src: /home/beta.opendesa.id/public_html/assets/../desa/upload/media/baris%201.png

**Comment by andifahruddinakas** [comment]
sudah diperbaiki dan masuk v2312.0.0
