### ISSUE TITLE
Bug/error: Tanggal Cetak KK

### ISSUE THREAD

**Issue by afri18** [OpenSID/OpenSID#7476]
### Jelaskan error yg dialami

Tanggal cetak Kartu Keluarga setelah di simpan di menu keluarga tampilan jadi aneh (tt yyyy)

### Cara untuk mereplikasi errornya

Tampilkan seperti semula tt mmmm yyyy

### Hasil yg diharapkan

menampilkan tanggal cetak Kartu Keluarga tt mmmm yyyy

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/6611881/fdba51a7-be46-438d-888b-a9994bb0f53e)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2311.2.0

### Tema Yang Digunakan

denatra

### Informasi tambahan

padahal versi sebelumnya aman

**Comment by afri18** [comment]
Ternyata di tanggal terdaftar juga berdampak 
![image](https://github.com/OpenSID/OpenSID/assets/6611881/978c6a3d-7144-4ffc-988e-72e22c097e44)

**Comment by andifahruddinakas** [comment]
Duplicate of https://github.com/OpenSID/OpenSID/issues/7478
