### ISSUE TITLE
Bug/error: Kepala Keluarga Pindah 

### ISSUE THREAD

**Issue by afri18** [OpenSID/OpenSID#7477]
### Jelaskan error yg dialami

saat Kepala keluarga pindah di laporan bulanan tercatat 2 x

### Cara untuk mereplikasi errornya

seharusnya cukup 1x

### Hasil yg diharapkan

jangan tercatat pindah 2x

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/6611881/08129d4e-3b57-4c4c-a438-a13d71111e6d)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2311.2.0

### Tema Yang Digunakan

denatra

### Informasi tambahan

log keluarga pindah jangan tercatat 2 kali

**Comment by pandigresik** [comment]
kami coba replikasi, hal diatas tidak terjadi 

Langkah : 

1. Cari satu penduduk dengan status sebagai kepala keluarga
2. Masuk menu penduduk, ubah status dasar kemudian pilih pindah dengan tujuan keluar desa / kelurahan
3. Cek laporan bulanan pada menu statistik - laporan bulanan
4. Hasil sudah sesuai, dimana kami coba untuk memindahkan 2 penduduk ( kepala keluarga ) dan di laporan bulanan tercatat 2 keluarga pindah sebagaimana screenshot dibawah ini

![image](https://github.com/OpenSID/OpenSID/assets/1853475/84015bd8-b4b2-4eda-bb0b-0845c7fe5e7a)

detailnya juga sudah sesuai
![image](https://github.com/OpenSID/OpenSID/assets/1853475/7c9d23d6-e07f-429a-bb53-5e68ca047cad)

**Comment by pandigresik** [comment]
> ### Jelaskan error yg dialami
> saat Kepala keluarga pindah di laporan bulanan tercatat 2 x
> 
> ### Cara untuk mereplikasi errornya
> seharusnya cukup 1x
> 
> ### Hasil yg diharapkan
> jangan tercatat pindah 2x
> 
> ### Tangkapan layar dan log error
> ![image](https://private-user-images.githubusercontent.com/6611881/286094363-08129d4e-3b57-4c4c-a438-a13d71111e6d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3NTU3NjksIm5iZiI6MTcwMTc1NTQ2OSwicGF0aCI6Ii82NjExODgxLzI4NjA5NDM2My0wODEyOWQ0ZS0zYjU3LTRjNGMtYTQzOC1hMTNkNzExMTFlNmQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDVUMDU1MTA5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2YyNWVhZDg5MWU0NDBlNmQ0YzIwYzk0NTNlYTAxYjVhYzM5ZTNlNjQ2M2ExZjcyNWU0NjkzYzJkNTNhMTg1ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.7Q2v9DYTMFHRicNsYpQYKJv5OoiAGTWDBoN4kjPU5Pk)
> 
> ### Rilis Versi OpenSID
> Rilis Premium
> 
> ### Versi OpenSID
> 2311.2.0
> 
> ### Tema Yang Digunakan
> denatra
> 
> ### Informasi tambahan
> log keluarga pindah jangan tercatat 2 kali

bisa dijelaskan kondisi ketika melakukan pindah penduduk, karena terlihat hanya ada 1 penduduk yang kembar padahal di gambar terlihat 2 kepala keluarga yang pindah. Artinya ada kondisi tertentu yang menyebabkan hal tersebut. Sebagaimana terlihat untuk penduduk dengan nama SOLEH hanya tercatata 1 kali saja

**Comment by afri18** [comment]
> > ### Jelaskan error yg dialami
> > saat Kepala keluarga pindah di laporan bulanan tercatat 2 x
> > ### Cara untuk mereplikasi errornya
> > seharusnya cukup 1x
> > ### Hasil yg diharapkan
> > jangan tercatat pindah 2x
> > ### Tangkapan layar dan log error
> > ![image](https://private-user-images.githubusercontent.com/6611881/286094363-08129d4e-3b57-4c4c-a438-a13d71111e6d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3NTU3NjksIm5iZiI6MTcwMTc1NTQ2OSwicGF0aCI6Ii82NjExODgxLzI4NjA5NDM2My0wODEyOWQ0ZS0zYjU3LTRjNGMtYTQzOC1hMTNkNzExMTFlNmQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDVUMDU1MTA5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2YyNWVhZDg5MWU0NDBlNmQ0YzIwYzk0NTNlYTAxYjVhYzM5ZTNlNjQ2M2ExZjcyNWU0NjkzYzJkNTNhMTg1ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.7Q2v9DYTMFHRicNsYpQYKJv5OoiAGTWDBoN4kjPU5Pk)
> > ### Rilis Versi OpenSID
> > Rilis Premium
> > ### Versi OpenSID
> > 2311.2.0
> > ### Tema Yang Digunakan
> > denatra
> > ### Informasi tambahan
> > log keluarga pindah jangan tercatat 2 kali
> 
> bisa dijelaskan kondisi ketika melakukan pindah penduduk, karena terlihat hanya ada 1 penduduk yang kembar padahal di gambar terlihat 2 kepala keluarga yang pindah. Artinya ada kondisi tertentu yang menyebabkan hal tersebut. Sebagaimana terlihat untuk penduduk dengan nama SOLEH hanya tercatata 1 kali saja

Saya juga bingung kenapa tercatat 2 kali, yg di atas dengan yg tercatat 2 kali hanya beda versi saat itu,

**Comment by andifahruddinakas** [comment]
mas @pandigresik, dari versi terbaru sudah tidak terjadi masalah ini. yang perlu diperbaiki data dari versi sebelumnya sehingga data tsb duplikasi. Bisa ditambahkan di bagian cek log_log keluarga.

**Comment by pandigresik** [comment]
Sudah ada fiturnya pada halaman periksa untuk hapus log keluarga ganda

![image](https://github.com/OpenSID/OpenSID/assets/1853475/37f55261-ad52-47aa-8c68-bda38d90e6c2)

![image](https://github.com/OpenSID/OpenSID/assets/1853475/a51cfebf-3b9e-44f1-aea4-b332f53609d1)
