### ISSUE TITLE
Bug/error: Tampilan Tanggal Lahir

### ISSUE THREAD

**Issue by afri18** [OpenSID/OpenSID#7478]
### Jelaskan error yg dialami

Di menu Keluarga > anggota keluarga
tanggal lahir yang di tampilkan tt yyyy

### Cara untuk mereplikasi errornya

tampilkan tanggal lahir di menu keluarga > anggota keluarga seperti tt-mm-yyyy

### Hasil yg diharapkan

tampilan tanggal lahir normal tt-mm-yyyy

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/6611881/5d8ca32f-3e3b-407a-9401-98cd83d72e1e)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2311.2.0

### Tema Yang Digunakan

denatra

### Informasi tambahan

seharusnya ini tidak berdampak saat update

**Comment by andifahruddinakas** [comment]
sudah diperbaiki dan masuk v2312.0.0
