### ISSUE TITLE
Bug: jenis kelompok data Statistik rentang umur tidak muncul ketika rentang umur diubah

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#748]
Ketika Mengatur statistik rentan umur jenis kelompok tidak muncul

![untitled2](https://user-images.githubusercontent.com/35319600/35083445-ca7e9f3a-fc51-11e7-9736-9067c01bcb2d.jpg)

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
