### ISSUE TITLE
Bug/error: Jumlah Penduduk dan Keluarga

### ISSUE THREAD

**Issue by afri18** [OpenSID/OpenSID#7480]
### Jelaskan error yg dialami

tidak ssesuai jumlah Penduduk dan Keluarga di beberapa menu/tab yang tersedia

### Cara untuk mereplikasi errornya

samakan jumlah penduduk dan keluarga di semua menu/tab yang ada

### Hasil yg diharapkan

Jumlah Penduduk dan Keluarga di menu/tab yan tersedia sama

### Tangkapan layar dan log error

Laporan Bulanan
![image](https://github.com/OpenSID/OpenSID/assets/6611881/01779500-5eed-4af1-85c9-1d5f6c31c874)

Wilayah
![image](https://github.com/OpenSID/OpenSID/assets/6611881/1dc15b2f-b244-4f11-a00d-176739b4f8d8)

Beranda
![image](https://github.com/OpenSID/OpenSID/assets/6611881/58dc99d9-07e8-4cca-98b3-fdbe64e6f0d4)

Rekapitulasi
![image](https://github.com/OpenSID/OpenSID/assets/6611881/31a24b12-8f65-43cb-82ff-42f8a0ceb0b2)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2311.2.0

### Tema Yang Digunakan

denatra

### Informasi tambahan

Mari cari solusinya kayak apa

**Comment by andifahruddinakas** [comment]
pak @afri18, silahkan di reopen jika contoh data yang diperlukan sudah ada.
