### ISSUE TITLE
Bug/error: Tambah Berita

### ISSUE THREAD

**Issue by afri18** [OpenSID/OpenSID#7481]
### Jelaskan error yg dialami

Saat tambah berita halaman admin web artikel eror

### Cara untuk mereplikasi errornya

seharusnya normal

### Hasil yg diharapkan

tampilan tambah artikel halaman edit artikel tampil

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/6611881/5c31209e-7eda-49a4-b03a-627b08b13074)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2311.2.0

### Tema Yang Digunakan

denatra

### Informasi tambahan

harusnya hal seperti ini diminimalisir

**Comment by andifahruddinakas** [comment]
sudah diperbaiki dan masuk v2312.0.0

**Comment by afri18** [comment]
> sudah diperbaiki dan masuk v2312.0.0
bisa di coba nggak ?? ambil d mana ???
