### ISSUE TITLE
Permintaan fitur: Cetak Laporan scorecard_konvergensi

### ISSUE THREAD

**Issue by afri18** [OpenSID/OpenSID#7485]
### Apa kekurangan yg ingin diatasi?

Cetak Laporan scorecard_konvergensi di menu Kesehatan>Stunting>scorecard_konvergensi

### Jelaskan solusi yg diinginkan

Bisa mencetak Laporan yg dihasilkan

### Apakah ada alternatif lain

Bisa import juga berupa excel

### Untuk versi OpenSID mana

2312.0.0

### Informasi tambahan

![image](https://github.com/OpenSID/OpenSID/assets/6611881/74b0c5ed-8f4e-49f3-9a88-88800f0d57dd)

**Comment by andifahruddinakas** [comment]
Duplicate of https://github.com/OpenSID/OpenSID/issues/6342
