### ISSUE TITLE
Sesuaikan group pengguna pada surat menyurat 

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#7491]
### Apa kekurangan yg ingin diatasi?

1. ketika pengguna membaut group dengan akses arsip saja karna group ini di peruntukan untuk kades yang hanya menggunakan untuk melihat surat dan tanda tangan surat
![image](https://github.com/OpenSID/OpenSID/assets/59082428/0a141b16-1028-4841-9458-a06119d285fb)
2. Namun ketika login menggunakan kades dan ketika ingin melakukan tanda tangan digital yang tampil seperti berikut ini : 
![image](https://github.com/OpenSID/OpenSID/assets/59082428/4c932be5-67a7-446c-9fa6-7b5592352479)

### Jelaskan solusi yg diinginkan

Sesuaikan group agar dapat memisahkan antara pengaturan surat arsip dan cetak surat karena fungsi popup tanda tangan dapat muncul jika akses cetak di berikan .

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

2312.0.0

**Comment by andifahruddinakas** [comment]
<img width="521" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/ddd420a2-bafe-4ca0-9b24-0082d0a4aae0">
