### ISSUE TITLE
Bug/error: Error 500 Anjungan Mandiri

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#7497]
### Jelaskan error yg dialami

setting anjungan mandiri akan alami error 500 saat buka halaman layanan-mandiri

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

normal kembalk

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Berputar

**Comment by andifahruddinakas** [comment]
Terkait issue https://github.com/OpenSID/OpenSID/issues/7498
