### ISSUE TITLE
Bug/error: gagal impor file gpx di peta desa

### ISSUE THREAD

**Issue by akmalfadli** [OpenSID/OpenSID#7500]
### Jelaskan error yg dialami

gagal import peta desa format gpx.
pada saat import peta desa dengan format gpx peta dapat dilihat di preview openstreet map halaman identitas desa -> Peta Wilayah Desa, tetapi setelah peta di simpan peta tidak dapat ditampilkan kembali.

### Cara untuk mereplikasi errornya

1. Pergi ke halaman identitas desa 
2. Pilih peta desa
3. import gpx

file peta gpx [download](https://drive.google.com/file/d/1Zw_HiLa-WScVPlXeQnn5ao1CfeaLr2z0/view?usp=sharing)
### Hasil yg diharapkan

peta dapat ditampilkan setelah peta di import atau disimpan ke database

### Tangkapan layar dan log error

**1. Tampilan pada saat belum disimpan**

![ggl](https://github.com/OpenSID/OpenSID/assets/13087253/d0c59d75-0159-4684-a488-d5181f55e849)

**3. Tampilan setelah peta disimpan**

![ggl2](https://github.com/OpenSID/OpenSID/assets/13087253/16f0ac9e-9816-4534-aea2-d94e6255cd28)

### Rilis Versi OpenSID

Rilis Umum

### Versi OpenSID

23.11

### Tema Yang Digunakan

essensi

### Informasi tambahan

setelah dilihat ke database, sepertinya ada masalah pada saat parsing path data gpx karena path data tidak lengkap.
![ggl3](https://github.com/OpenSID/OpenSID/assets/13087253/a2eb5041-7fec-4add-a7e7-551931a50873)

**Comment by luxmant354** [comment]
termasuk pakai shp juga trobel mas Akas
![Screenshot_10](https://github.com/OpenSID/OpenSID/assets/44687953/976d40ad-73cd-47e1-91dd-f5805c513584)
![Screenshot_11](https://github.com/OpenSID/OpenSID/assets/44687953/ea6af2cd-5d9c-4e3d-a7ee-0aaa24b3f42e)
![Screenshot_9](https://github.com/OpenSID/OpenSID/assets/44687953/54b5c562-c494-4bfd-b91e-d13c37905ec9)

**Comment by luxmant354** [comment]
Untuk File shp.zip bisa dicek di 
[coba.zip](https://github.com/OpenSID/OpenSID/files/13558522/coba.zip)

**Comment by andifahruddinakas** [comment]
Bung @akmalfadli, untuk https://drive.google.com/file/d/1Zw_HiLa-WScVPlXeQnn5ao1CfeaLr2z0/view tidak valid, sy coba impor tanpa adanya validasi pada petanya akan membuat peta jadi blank.
<img width="741" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/2f49a270-3636-4ed1-a3af-c93d34373a0f">

**Comment by andifahruddinakas** [comment]
> Untuk File shp.zip bisa dicek di [coba.zip](https://github.com/OpenSID/OpenSID/files/13558522/coba.zip)

ini jg akan gagal

**Comment by andifahruddinakas** [comment]
bung @akmalfadli, @luxmant354, apa benar itu peta desa? atau gabungan dari semua yang ada di desa, misalkan batas2, sawah, rumah, dll?

Yang bisa kami solusi saat ini agar tdk memberikan informasi saat melakukan impor. Karena jika dipaksa untuk ditampilkan akan menyebabkan error.

<img width="745" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/4d1b3013-92de-468d-aa80-56fc48366b3d">
