### ISSUE TITLE
Bug/error: Upload Gambar Artikel

### ISSUE THREAD

**Issue by afri18** [OpenSID/OpenSID#7501]
### Jelaskan error yg dialami

eror saat upload gambar artikel

### Cara untuk mereplikasi errornya

harusnya tersimpan

### Hasil yg diharapkan

bisa upload gambar artikel

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/6611881/06c79aa8-c437-4d3e-9ca7-ad78ac8049bd)
hasil setelah klik simpan
![image](https://github.com/OpenSID/OpenSID/assets/6611881/3dd0d80d-ceff-4248-bbe6-a13298a08e57)
hasil setelah kembalikan halaman
![image](https://github.com/OpenSID/OpenSID/assets/6611881/1ce5c216-8a4a-4b79-aa27-c580f7670909)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2312.0.0

### Tema Yang Digunakan

denatra

### Informasi tambahan

biasanya ini tidak eror

**Comment by andifahruddinakas** [comment]
Sudah di sesuaikan https://github.com/OpenSID/premium/commit/66ae5e8b74a8c18a54a3f81b5f6b1c987882965c
