### ISSUE TITLE
error saat unggah foto penduduk

### ISSUE THREAD

**Issue by pujocahyono** [OpenSID/OpenSID#7504]
### Jelaskan error yg dialami

error saat unggah foto penduduk

### Cara untuk mereplikasi errornya

unggah foto penduduk

### Hasil yg diharapkan

bisa unggah foto penduduk

### Tangkapan layar dan log error

Severity: error --> Exception: Argument 3 passed to UploadFoto() must be of the type string, null given, called in /home/berputar.opendesa.id/public_html/donjo-app/core/MY_Log.php(206) : eval()'d code(1) : eval()'d code on line 790 /home/berputar.opendesa.id/public_html/donjo-app/core/MY_Log.php(20
) : eval()'d code(1) : eval()'d code 173
<img width="960" alt="Cuplikan layar 2023-12-05 061133" src="https://github.com/OpenSID/OpenSID/assets/87228587/20ac67a4-0af7-4294-adfc-e327fefe2915">

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2312.0.0-premium

**Comment by andifahruddinakas** [comment]
Sudah disesuaikan https://github.com/OpenSID/premium/commit/66ae5e8b74a8c18a54a3f81b5f6b1c987882965c
