### ISSUE TITLE
Bug/error: nama desa kata kedua huruf kecil

### ISSUE THREAD

**Issue by Sukoharjo3** [OpenSID/OpenSID#7506]
### Jelaskan error yg dialami

Nama desa kata kedua pada surat tinymce tidak bisa sesuai Kemendagri, Sukoharjo III pada pengaturan surat tinymce menjadi Sukoharjo Iii/sukoharjo iii/SUKOHARJO III
tidak ada pilihan yg benar sesuai nama desa Kemendagri yaitu Sukoharjo III

### Cara untuk mereplikasi errornya

saat surat rtf setingan nama desa itu benar bisa sesuai Kemendagri, saat tinymce jadi salah
seharusnya [nama_desa] menggunakan isian seperti penandatanganan [atas_nama] yang bisa menyebut nama desa dengan benar
![Screenshot_20231206-213535](https://github.com/OpenSID/OpenSID/assets/112841792/88f8fe2c-9d65-4899-b9f8-29085e6a3a52)

![IMG-20231206-WA0013](https://github.com/OpenSID/OpenSID/assets/112841792/10e7158e-cff8-474a-8388-16f83ba1424e)

### Hasil yg diharapkan

nama desa pada surat tinymce sesuai dengan kode Kemendagri yaitu Sukoharjo III

### Tangkapan layar dan log error

![IMG-20231206-WA0013](https://github.com/OpenSID/OpenSID/assets/112841792/85f61e4f-3945-4e33-96ae-d1131160971d)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

premium v23.12.0.0

### Tema Yang Digunakan

silir 4.3

**Comment by eddieridwan** [comment]
@andifahruddinakas @vickyrolanda tambahkan numerik Romawi ke library pengaturan teks yg harus selalu tampil huruf besar.

**Comment by andifahruddinakas** [comment]
Bisa gunakan fungsi yang sudah disediakan, isian **Normal** tidak ada konversi format di dalamnya. Apa yang ada di database, hasilnya akan sama.
<img width="343" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/f5a4738c-8e48-4322-9640-46a2cac4af65">

Hasil

<img width="406" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/65a81987-815b-4bdc-974f-c69dfa69b887">

**Comment by andifahruddinakas** [comment]
> @andifahruddinakas @vickyrolanda tambahkan numerik Romawi ke library pengaturan teks yg harus selalu tampil huruf besar.

membuat berat library tinymce saat load dan generate pdfnya, jika ditambakan pengecekan tsb. Karena saat ini pengecekan di lakukan di 1 tempat yang sama, maka semua kode isian tinymce mendapatkan perlakuan yang sama.

**Comment by ai-skematik** [comment]
apakah akan berdampak ke dusun yg ada romawi. ? contoh Dusun III.

**Comment by ai-skematik** [comment]
Dulu waktu rtf dusun romawi juga seperti itu masalahnya, tp sudah diperbaiki di rtf

**Comment by eddieridwan** [comment]
@andifahruddinakas rasanya menggunakan regex untuk pengecualian atau manipulasi khusus tidak terlalu memberatkan. Yaitu menggunakan pola regex pola1 | pola2 | dstnya

**Comment by Sukoharjo3** [comment]
> Bisa gunakan fungsi yang sudah disediakan, isian **Normal** tidak ada konversi format di dalamnya. Apa yang ada di database, hasilnya akan sama. <img alt="image" width="343" src="https://private-user-images.githubusercontent.com/57283157/288590611-f5a4738c-8e48-4322-9640-46a2cac4af65.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5NTQ2MDIsIm5iZiI6MTcwMTk1NDMwMiwicGF0aCI6Ii81NzI4MzE1Ny8yODg1OTA2MTEtZjVhNDczOGMtOGU0OC00MzIyLTk2NDAtNDZhMmNhYzRhZjY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA3VDEzMDUwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwYzYzZTdhYzQ1Y2YzYTBiNjFlYjcwMWJiMzMzMGE1MDMxNWViMzdlMzVhODE0ODg4YjRiMDk2OGY4MTgwODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qq3UErSZvZ9XZmEkVPXKdpqY_trnReUmTXsyeN4blAg">
> 
> Hasil
> 
> <img alt="image" width="406" src="https://private-user-images.githubusercontent.com/57283157/288590401-65a81987-815b-4bdc-974f-c69dfa69b887.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5NTQ2MDIsIm5iZiI6MTcwMTk1NDMwMiwicGF0aCI6Ii81NzI4MzE1Ny8yODg1OTA0MDEtNjVhODE5ODctODE1Yi00YmRjLTk3NGYtYzY5ZGZhNjliODg3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA3VDEzMDUwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyYzdjZTI2OWQ5MmM3NzgxMTJiMzQxYzBkYjM2OTEyZGFhZDBiMjNjZGUwMGNjMjM3YzJhZDlmYzY2ZDM1ODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aSTCKvUijCeOb1bBapav4lv71y4yWrzkJL7nQyGxI14">

baik, bisa menggunakan ini pak
