### ISSUE TITLE
### bug hapus surat di arsip layanan untuk administrator

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#751]
status pengguna sebagai administrator juga tidak ada tombol hapus data
![screenshot 2018-01-21 17 47 26](https://user-images.githubusercontent.com/25834335/35192836-56bbc066-fed4-11e7-90fa-7a9c5b82e734.png)

seharusnya tuk administrator ada seperti dibawah ini
![screenshot 2018-01-21 17 56 06](https://user-images.githubusercontent.com/25834335/35192856-8fa498d0-fed4-11e7-89a3-9bc02a4c87b5.jpg)

**Comment by eddieridwan** [comment]
Sudah diperbaiki.
