### ISSUE TITLE
Kode isian data penduduk tidak ada saat pilihan Data Pelaku Penduduk Luar Desa

### ISSUE THREAD

**Issue by pujocahyono** [OpenSID/OpenSID#7514]
### Jelaskan error yg dialami

Kode isian data penduduk tidak ada saat pilihan Data Pelaku : 
<img width="960" alt="Cuplikan layar 2023-12-08 074659" src="https://github.com/OpenSID/OpenSID/assets/87228587/56cd1315-81ec-4247-8468-9fc11f01787e">
<img width="960" alt="Cuplikan layar 2023-12-08 074615" src="https://github.com/OpenSID/OpenSID/assets/87228587/e9b6f043-9f65-4e46-bdac-759c16b58c1e">
Penduduk Luar Desa. akan muncul kode isian jika pilihan Data Pelaku : Penduduk Desa

### Cara untuk mereplikasi errornya

Membuat surat dengan pilihan Data Pelaku hanya Penduduk Luar Desa atau Penduduk Luar Desa Lengkap

### Hasil yg diharapkan

Ada pilihan data penduduk jika Data Pelaku hanya Penduduk Luar Desa atau Penduduk Luar Desa Lengkap

### Tangkapan layar dan log error

<img width="960" alt="Cuplikan layar 2023-12-08 074659" src="https://github.com/OpenSID/OpenSID/assets/87228587/ef411022-b3f5-4602-8420-8bc001f23f6a">
<img width="960" alt="Cuplikan layar 2023-12-08 074615" src="https://github.com/OpenSID/OpenSID/assets/87228587/a85d5e6e-134b-4db8-896d-9ab21ebc23a4">

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2312.0.1-premium

**Comment by andifahruddinakas** [comment]
Solusi :
- [ ] selalu tampilkan kode isian kategori individu (utama)
