### ISSUE TITLE
Bug/error: Ubah Keluarga

### ISSUE THREAD

**Issue by afri18** [OpenSID/OpenSID#7515]
### Jelaskan error yg dialami

Ubah data keluarga dari menu Keluarga untuk data alamat, tanggal cetak KK dll saat disimpan menampilkan halaman kosong

### Cara untuk mereplikasi errornya

Seharusnya tersimpan dan data alamat untuk semua anggota keluarga menyesuaikan dengan alamat Kartu Keluarga

### Hasil yg diharapkan

Harusnya tersimpan dan data alamat untuk semua anggota keluarga sam

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/6611881/3d80776d-dabe-4c95-b9c0-74e511dd48fd)
hasil setelah klik simpan
![image](https://github.com/OpenSID/OpenSID/assets/6611881/a053d607-d7f1-4cf1-9ede-618b90277f3a)
alamat di biodata berubah padahal di Keluarga tidak
![image](https://github.com/OpenSID/OpenSID/assets/6611881/6b33faef-0a87-4bdb-ba68-bb2eba6d4277)
alamat di penduduk dan keluarga tetap
![image](https://github.com/OpenSID/OpenSID/assets/6611881/2b3eabaa-af44-4a47-9adc-65d4e4f2f4dc)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2312.0.1

### Tema Yang Digunakan

denatra

### Informasi tambahan

seharusnya saat simpan data keluarga yang berhubungan dengan alamat keluarga dan alamat untuk anggota keluarga sama

**Comment by andifahruddinakas** [comment]
pak @afri18, silahkan duplikasi ke https://berputar.opendesa.id, dan kirim log error dari web desa anda.

**Comment by afri18** [comment]
info > Nama Kepala Keluarga masuk dalam Perangkat Desa Sebagai Kadus dan operator Opensid dugaan saya karna yg bersangkutan Kepala Dusun yg menyebabkan eror, karna Kepala keluarga yg lain (bukan Perangkat Desa) aman

**Comment by afri18** [comment]
[log-2023-12-08.zip](https://github.com/OpenSID/OpenSID/files/13608066/log-2023-12-08.zip)

**Comment by afri18** [comment]
> pak @afri18, silahkan duplikasi ke https://berputar.opendesa.id, dan kirim log error dari web desa anda.

![image](https://github.com/OpenSID/OpenSID/assets/6611881/424d904d-84d6-4970-9aae-03f9e4bdf0ee)
hasil
![image](https://github.com/OpenSID/OpenSID/assets/6611881/3ec1ff52-a3e0-4475-bc19-582a564866f7)

**Comment by agungsugiarto** [comment]
mas @andifahruddinakas, saya tidak bisa replikasi issue ini, bisa dibantu meriplikasi?

**Comment by andifahruddinakas** [comment]
pak @afri18, silahkan di update ke versi 2401.0.0

**Comment by afri18** [comment]
> pak @afri18, silahkan di update ke versi 2401.0.0

sudah, 2401.0.1 rev sudah bisa d uji ???
