### ISSUE TITLE
Alamat Kop Surat jadi Berubah Jika Memilih Penduduk Luar Desa (Lengkap) di kolom Alamat di versi TinyMCE 

### ISSUE THREAD

**Issue by luxmant354** [OpenSID/OpenSID#7516]
### Jelaskan error yg dialami

Ketika membuat master surat kombinasi warga desa dan warga luar desa, dan ketika memilih warga luar desa kemudian mengisi kolom alamat diluar desa , maka hasilnya kop surat yg mestinya tidak berubah jadi ikut berubah dengan alamat warga luar desa.
![Screenshot_15](https://github.com/OpenSID/OpenSID/assets/44687953/7f8796cf-b07f-4735-b654-b83e2d856a19)

![Screenshot_14](https://github.com/OpenSID/OpenSID/assets/44687953/00d16b35-4657-450a-8924-4e9842bf2557)

### Cara untuk mereplikasi errornya

nihil

### Hasil yg diharapkan

Alamat Penduduk Luar Desa Sesuai dan tidak mempengaruhi alamat utama/ alamat yang ada di Kop Surat Layanan.

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2312.0.1-premium

**Comment by andifahruddinakas** [comment]
Sudah disesuaikan di issue https://github.com/OpenSID/OpenSID/issues/7514
