### ISSUE TITLE
selalu ke-direct ke admin panel

### ISSUE THREAD

**Issue by elgarsn14** [OpenSID/OpenSID#752]
Maaf sepuh, bagaimana cara mengatasi localhost/opensid yang selalu direct ke admin panel ? padahal sudah di logout dan dicoba pake private browser tetep saja. terimakasih

mohon maaf bila sudah pernah ada masalah yang sama, karena sdh dicari tp blm ketemu :)

**Comment by eddieridwan** [comment]
@elgarsn14 silakan tanyakan penggunaan OpenSID di Forum Pengguna dan Pegiat OpenSID (https://www.facebook.com/groups/OpenSID). 

Issue digunakan untuk daftar kerja, termasuk: (1) masalah yg telah dipastikan bug, (2) usulan dan permintaan.

Kalau pertanyaan anda nanti ternyata memang membutuhkan perbaikan aplikasi, baru membuat issue.
