### ISSUE TITLE
Tidak bisa memilih Alamat RW saat tambah penduduk baru

### ISSUE THREAD

**Issue by pujocahyono** [OpenSID/OpenSID#7522]
### Jelaskan error yg dialami

Tidak bisa memilih Alamat RW saat tambah penduduk baru

### Cara untuk mereplikasi errornya

Tambah penduduk baru

### Hasil yg diharapkan

Muncul pilihan RW dan RT

### Tangkapan layar dan log error

<img width="960" alt="Cuplikan layar 2023-12-17 072821" src="https://github.com/OpenSID/OpenSID/assets/87228587/41066997-6a4c-48f7-af26-a476cbba50db">

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2312.0.2-premium

**Comment by andifahruddinakas** [comment]
Sudah disesuaikan di commit https://github.com/OpenSID/premium/commit/546f874bf7dbb06d863569d069ebec99afb7acf8
