### ISSUE TITLE
Bug: tampilan di menu statistik untuk program bantuan tidak beraturan

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#753]
![screenshot 2018-01-21 23 16 38](https://user-images.githubusercontent.com/25834335/35195735-c64d5ec0-ff02-11e7-9370-46cc685b131e.png)

**Comment by eddieridwan** [comment]
Bug ini terjadi pada program bantuan dgn sasaran Keluarga/Rumah Tangga/Kelompok. Saat ini statistik kepala keluarga/rumah tangga/kelompok menurut gender (L/P) tidak dihitung.

Solusinya adalah dengan tidak menampilkan kolom Laki-laki/Perempuan, yang isinya sama dengan kolom Jumlah.

Sudah diperbaiki dan dicommit ke master.
