### ISSUE TITLE
Bug/error: ubah anggota pada menu lembaga error

### ISSUE THREAD

**Issue by Wiliyantoro** [OpenSID/OpenSID#7530]
### Jelaskan error yg dialami

saat ingin merubah rincian anggota pada menu lembaga seperti no anggota / keterangan terjadi error

### Cara untuk mereplikasi errornya

1. beranda
2. info desa
3. lembaga desa
4. rincian lembaga
5. ubah anggota
saat merubah no anggota terjadi error dan kembali ke halaman utama

### Hasil yg diharapkan

dapat merubah no anggota / keterangan

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/44520382/56e437f0-2ca9-48d9-af5e-2d89f1fc7333)
Query error: Duplicate entry '1-13-12191' for key 'id_kelompok_config' - Invalid query: UPDATE `kelompok_anggota` SET `no_anggota` = '5102102003202001', `jabatan` = '90', `no_sk_jabatan` = '', `keterangan` = '', `tipe` = 'lembaga', `nmr_sk_pengangkatan` = '', `tgl_sk_pengangkatan` = NULL, `nmr_sk_p
mberhentian` = '', `tgl_sk_pemberhentian` = NULL, `periode` = '', `id_kelompok` = '13'WHERE (`config_id` = 1 )AND `id_penduduk` = '12191'

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2312.0.3-premium

### Tema Yang Digunakan

denava

### Informasi tambahan

hal ini terjadi juga pada halaman berputar

**Comment by agungsugiarto** [comment]
Mas @andifahruddinakas, saya tidak bisa replikasi issue ini, bisa dibantu?

**Comment by andifahruddinakas** [comment]
> Mas @andifahruddinakas, saya tidak bisa replikasi issue ini, bisa dibantu?

bisa test di https://berputar.opendesa.id
