### ISSUE TITLE
Permintaan fitur: Laporan Penduduk Dikelompokan Berdasarkan KK

### ISSUE THREAD

**Issue by wahyabiantara** [OpenSID/OpenSID#7532]
### Apa kekurangan yg ingin diatasi?

Laporan data Penduduk (Cetak dan Unduh) yang saat ini masih belum dikelmpokan berdasarkan KK

### Jelaskan solusi yg diinginkan

Untuk memudahkan pencarian data penduduk berdasarkan KK pada laporan yang dicetak maupun di unduh, mohon dibuatkan laporan data penduduk yang telah dikelompokan berdasarkan KK sbb:

![image](https://github.com/OpenSID/OpenSID/assets/4361979/f75e2897-50b6-4c30-bba6-58a228679f1b)

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

2312.0.1-premium

**Comment by balongbesuk** [comment]
biasa kan kalau ngeshare contoh data dg data yang bukan sebenarnya,

**Comment by wahyabiantara** [comment]
> biasa kan kalau ngeshare contoh data dg data yang bukan sebenarnya,

Terima kasih remindernya. Data sudah sudah saya sensor

**Comment by andifahruddinakas** [comment]
pak @wahyabiantara bisa di urutkan berdasar kk dlu baru di cetak
