### ISSUE TITLE
Penambahan Jenis Pekerjaan 

### ISSUE THREAD

**Issue by typevant** [OpenSID/OpenSID#7534]
### Apa kekurangan yg ingin diatasi?

Saat ini pemerintah mengkategorikan P3K menjadi salah satu bagian dari ASN, oleh karena itu perlu penambahan jenis P3K sebagai salah satu pekerjaan.

### Jelaskan solusi yg diinginkan

Penambahan P3K sebagai salah satu jenis pekerjaan.

### Apakah ada alternatif lain

P3K (ASN)

### Untuk versi OpenSID mana

v.2401.00

**Comment by eddieridwan** [comment]
@vickyrolanda pelajari apakah P3K sudah termasuk dalam daftar pekerjaan Dukcapil. Saat ini daftar perkerjaan yg ada di OpenSID mengikuti yg dari Dukcapil. Jika ditambah, harus ada analisis bagaimana membedakan kategori Dukcapil dan yg bukan. Perlu dipelajari ada berapa kategori pekerjaan yg diakui pemerintah pusat. Sepertinya BPS ada daftar pekerjaan sendiri. Mungkin juga Kemendagri pada Prodeskel, dan Kemendes pada IDM/SDGs. Perlu dicari apakah P3K itu masuk di kategori pekerjaan yg baku dari instansi pusat. 

BPS bersama Kemnaker menyusun Klasifikasi Baku Jabatan Indonesia 2014, di https://satudata.kemnaker.go.id/publikasi/48. Tapi saya kita daftar itu terlalu rinci (ada ribuan kode) dan tidak praktis bagi kegunaan desa. 

Mungkin cari daftar pekerjaan yg digunakan dalam inisiatif Satu Data pemerintah pusat.

**Comment by eddieridwan** [comment]
Di Prodeskel ada isian Mata Pencaharian Pokok. Bisa lihat di petunjuk pengisian Prodeskel yg digunakan Ruri. Mungkin seperti terlampir? Tapi daftar itu lebih singkat dari yg digunakan Dukcapil.

[3003bea3f8b83699dbdfc39c27ca45e9.pdf](https://github.com/OpenSID/OpenSID/files/13785782/3003bea3f8b83699dbdfc39c27ca45e9.pdf)

**Comment by eddieridwan** [comment]
@vickyrolanda sebagai catatan umum, pada permintaan seperti ini, yang perlu ditanyakan adalah : "untuk apa?". Jika untuk pelaporan Dukcapil atau Prodeskel, harus menggunakan kode pekerjaan mereka. Jadi jika permintaan itu untuk pelaporan, perlu ditanyakan pelaporan pada siapa? Dan kemudian harus menggunakan kode pekerjaan pihak yg menerima laporan tersebut. 

Kalau hanya untuk penggunaan lokal saja, mungkin bisa menggunakan Data Suplemen.

**Comment by balongbesuk** [comment]
coba lampirkan bukti pendukung foto KK yang menampilkan pekerjaan P3K (ASN)

**Comment by vickyrolanda** [comment]
PPPK ini udah lama di susun dalam UU No 5 Tahun 2014 , namun di tahun ini presiden resmi merombak hak-hak aparatur sipil negara (ASN) baik PNS maupun PPPK melalui pengesahan Undang-undang (UU) Nomor 20 Tahun 2023 tentang ASN. 

Dalam peneraannya PPPK digunakan untuk pengganti pekerja Honorer pada pemerintah yang di rasa perlu dan berguna dalam Dinas dinas tertentu namun juga dalam seleksi PPPK juga terbuka bagi masyarakat umum tidak hanya untuk pekerja honorer. 

Maka memang PPPK menjadi salah satu pekerjaan yg terdaftar diperintah pusat dan juga terdaftar pada BKD karena thn 2024 honorer juga sudah tidak dpt dilanjutkan dimna diganti menjadi PPPK. 

Untuk contoh KK pastinya masih jarang sekali apa lagi PPPK ini bru aktif di thn 2023 ini. 

Untuk penambahan pada dukcapil sy masih mencari sumber yg terpercaya agar memang daftar pekerjaan terbaru.
