### ISSUE TITLE
Bug/error: Menampilkan widget Absensi Perangkat Desa

### ISSUE THREAD

**Issue by kreatormuda** [OpenSID/OpenSID#7535]
### Jelaskan error yg dialami

Bagaimana cara menampilkan menu absensi secara otomatis pada tema pusako seperti digambar demo tema, mohon bantuannya

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

Demo Pusako
![image](https://github.com/OpenSID/OpenSID/assets/111245222/c6e5b2f9-0443-4f26-905a-617f572ce8e8)

Sedangkan di web saya seperti ini
![image](https://github.com/OpenSID/OpenSID/assets/111245222/607d3ae6-8828-4097-b032-071577c6c766)

Mohon informasinya

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v2309.0.1-premium

### Tema Yang Digunakan

pusako

**Comment by andifahruddinakas** [comment]
mas @kreatormuda, bisa ditanyakan ke pengembang tema
