### ISSUE TITLE
Permintaan fitur: Buat modul management lampiran

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#7538]
### Apa kekurangan yg ingin diatasi?

ada kalanya lampiran juga tidak sesuai dengan yang ada di beberapa surat contoh di surat nikah, 
maka jika menggunakan RTF lampiran dapat di edit, sedangkan menggunakan TinyMCE Lampiran sudah baku. 

### Jelaskan solusi yg diinginkan

Dari masalah diatas butuh membuat modul managemen lampiran agar lampiran juga dinamis bisa ditambah dan bisa disesuaikan berdasarkan wilayah masing - masing.

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

2401.0.0

**Comment by andifahruddinakas** [comment]
Modulnya sudah dikerjakan :
https://github.com/OpenSID/OpenSID/issues/7307
https://github.com/OpenSID/premium/issues/3153
https://github.com/OpenSID/premium/issues/3110
https://github.com/OpenSID/premium/issues/3144

Kendala yang di alami, hasil generate template tinymce yang berantakan.

**Comment by khiar-rara** [comment]
mohon untuk didukung fungsi if, jika data sesuai maka ditampikan, jika tidak sesuai maka tidak ditampilkan. seperti pada lampiran surat nikah. <?php
if (($input['status_kawin'] == 'Duda' || $input['status_kawin'] == 'Janda') && ($input['tanggal_meninggal_pasangan_terdahulu'] != "") ) {
    include_once('view_individu.php');
}

if (($input['status_kawin_calon_pasangan'] == 'Duda' || $input['status_kawin_calon_pasangan'] == 'Janda') && ($input['tanggal_meninggal_pasangan_terdahulu_calon_pasangan'] != "") ) {
    include_once('view_calon_pasangan.php');
}

include_once('.php');
?>

**Comment by eddieridwan** [comment]
> mohon untuk didukung fungsi if, jika data sesuai maka ditampikan, jika tidak sesuai maka tidak ditampilkan. seperti pada lampiran surat nikah. <?php if (($input['status_kawin'] == 'Duda' || $input['status_kawin'] == 'Janda') && ($input['tanggal_meninggal_pasangan_terdahulu'] != "") ) { include_once('view_individu.php'); }
> 
> if (($input['status_kawin_calon_pasangan'] == 'Duda' || $input['status_kawin_calon_pasangan'] == 'Janda') && ($input['tanggal_meninggal_pasangan_terdahulu_calon_pasangan'] != "") ) { include_once('view_calon_pasangan.php'); }
> 
> include_once('.php'); ?>

@khiar-rara ada baiknya ditulis ketentuan ini dalam bahasa Indonesia yg jelas saja. Karena menggunakan pseudocode atau koding justru akan membingungkan.

Misalnya: "Jika dudu atau janda dan xxxx, maka tampilkan/jangan tampilkan xxx".

**Comment by khiar-rara** [comment]
diatas saya menyebutkan contoh view lampiran n6 surat nikah (keterangan kematian pasangan terdahulu). 

Jadi misal, input status catin pemohon yaitu duda, maka lampiran n6 yang berisi keterangan kematian pasangan catin pemohon ditampilkan. 
Jjika input status catin pemohon yaitu jejaka, maka lampiran n6 yang berisi keterangan kematian pasangan catin pemohon tidak ditampilkan.

**Comment by Sukoharjo3** [comment]
sangat menunggu fitur ini supaya pengantar nikah bisa di sesuaikan jika tak ada tempat penyesuaian ya surat yg menggunakan lampiran tidak akan pernah bisa digunakan karna perlu penyesuaian banyak
nama desa yang menggunakan spasi itu jadi turun

<img width="960" alt="image" src="https://github.com/OpenSID/OpenSID/assets/112841792/c8eec52f-bf79-49c5-8df2-db324b29e81a">

**Comment by eddieridwan** [comment]
@vickyrolanda @andifahruddinakas modul ini BUKAN untuk mengedit lampiran yg bersifat baku. Tapi hanya untuk memilih jika suatu wilayah menggunakan format yg berbeda. @vickyrolanda TIDAK disediakan fitur untuk menyesuaikan atau mengedit lampiran baku yg sudah disediakan.

**Comment by Sukoharjo3** [comment]
> @vickyrolanda @andifahruddinakas modul ini BUKAN untuk mengedit lampiran yg bersifat baku. Tapi hanya untuk memilih jika suatu wilayah menggunakan format yg berbeda. @vickyrolanda TIDAK disediakan fitur untuk menyesuaikan atau mengedit lampiran baku yg sudah disediakan.

lalu dimana bisa menyesuaikan nama desa saya yg turun ke baris berikutnya pak?

**Comment by eddieridwan** [comment]
@Sukoharjo3 hadir saja pada pertemuan hari Kamis tgl 18 Januari pukul 13:00 WIB, khusus membahas keluhan dan permintaan terkait lampiran surat TinyMCE. Di Ruang Support, di https://discord.gg/naVFdbY8

**Comment by balongbesuk** [comment]
> > @vickyrolanda @andifahruddinakas modul ini BUKAN untuk mengedit lampiran yg bersifat baku. Tapi hanya untuk memilih jika suatu wilayah menggunakan format yg berbeda. @vickyrolanda TIDAK disediakan fitur untuk menyesuaikan atau mengedit lampiran baku yg sudah disediakan.
> 
> lalu dimana bisa menyesuaikan nama desa saya yg turun ke baris berikutnya pak?

edit hardcode aja mas filenya ada di storage/app/template/lampiran

**Comment by Sukoharjo3** [comment]
> > > @vickyrolanda @andifahruddinakas modul ini BUKAN untuk mengedit lampiran yg bersifat baku. Tapi hanya untuk memilih jika suatu wilayah menggunakan format yg berbeda. @vickyrolanda TIDAK disediakan fitur untuk menyesuaikan atau mengedit lampiran baku yg sudah disediakan.
> > 
> > 
> > lalu dimana bisa menyesuaikan nama desa saya yg turun ke baris berikutnya pak?
> 
> edit hardcode aja mas filenya ada di storage/app/template/lampiran

wah bikin sakit kepala kalo itu pak
pas diupadte versi jg bakal ketimpa

**Comment by khiar-rara** [comment]
Jika tidak ingin tertimpa, simpan di folder desa-template surat-lampiran

**Comment by balongbesuk** [comment]
> > > > @vickyrolanda @andifahruddinakas modul ini BUKAN untuk mengedit lampiran yg bersifat baku. Tapi hanya untuk memilih jika suatu wilayah menggunakan format yg berbeda. @vickyrolanda TIDAK disediakan fitur untuk menyesuaikan atau mengedit lampiran baku yg sudah disediakan.
> > > 
> > > 
> > > lalu dimana bisa menyesuaikan nama desa saya yg turun ke baris berikutnya pak?
> > 
> > 
> > edit hardcode aja mas filenya ada di storage/app/template/lampiran
> 
> wah bikin sakit kepala kalo itu pak pas diupadte versi jg bakal ketimpa

nmny penyesuaian y harus d inget inget pak file apa sj yang d rubah, format surat pindah saya f103 modelnya landscape dg hasil cetak 3 lembar, sedangkan opensid mengacu ke peraturan baku yang mana modelnya potrait 1 lembar,

tiap ubahan yang ada d opensid dcatat sj dg notepad d hosting jadi gak bakal lupa apa saja yang dirubah, tinggal waktu update d backup
