### ISSUE TITLE
Permintaan fitur: tambahkan mode demo untuk pembuatan surat 

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#7540]
### Apa kekurangan yg ingin diatasi?

Mungkin bisa dipikirkan solusinya yg stabil. Misalnya, pada waktu membuat surat beri opsi menyatakan bahwa surat itu untuk ujicoba. Berikan notifikasi peringatan.

Dan kemudian terapkan ketentuan yg berlaku bagi surat ujicoba. Misalnya  di arsip layanan jelas ditandai sebagai surat ujicoba, yang dapat dihapus. Setelah ditandai sebagai ujicoba tidak dapat diubah menjadi surat biasa; dan surat biasa yg sudah masuk arsip layanan juga tidak dapat diubah menjadi surat ujicoba (sebelum masuk arsip layanan mungkin boleh diubah).

### Jelaskan solusi yg diinginkan

-

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

2401.0.0

### Informasi tambahan

-

**Comment by andifahruddinakas** [comment]
Tambahan : 
- sebaiknya tidak perlu banyak tambahan pengaturan, gunakan fungsi demo mode. jika di set demo mode, maka bisa hapus surat.

**Comment by andifahruddinakas** [comment]
login sebagai admin super user
