### ISSUE TITLE
Bug/error: tidak bisa membuat menu, hanya bisa membuat submenu

### ISSUE THREAD

**Issue by kembangbelor** [OpenSID/OpenSID#7541]
### Jelaskan error yg dialami

di menu admin web ada pilihan menu, ketika di klik dan pilih menu statis, harusnya kita bisa membuat menu dan submenu, tpi disitu langsung membuat sub menu tidak ada membuat menu, hasilnya kita tidak bisa membuat menu yang ada submenunya (dropdown)

### Cara untuk mereplikasi errornya

di menu admin web ada pilihan menu, ketika di klik dan pilih menu statis, harusnya kita bisa membuat menu dan submenu, tpi disitu langsung membuat sub menu tidak ada membuat menu, hasilnya kita tidak bisa membuat menu yang ada submenunya (dropdown)

### Hasil yg diharapkan

di menu admin web ada pilihan menu, ketika di klik dan pilih menu statis, harusnya kita bisa membuat menu dan submenu, tpi disitu langsung membuat sub menu tidak ada membuat menu, hasilnya kita tidak bisa membuat menu yang ada submenunya (dropdown)

### Tangkapan layar dan log error

![Capture](https://github.com/OpenSID/OpenSID/assets/155209565/400ac389-9b91-40e3-96cc-a560da52324a)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

OpenSID 2312.0.3-premium

### Tema Yang Digunakan

Tema Silir v4.3.

### Informasi tambahan

mohon segera ditindak lanjuti

**Comment by andifahruddinakas** [comment]
akan diperbaiki melalui issue https://github.com/OpenSID/OpenSID/issues/7548
