### ISSUE TITLE
ERROR 500 saat Tambah Surat

### ISSUE THREAD

**Issue by pujocahyono** [OpenSID/OpenSID#7543]
### Jelaskan error yg dialami

ERROR 500 saat Tambah Surat
<img width="960" alt="Cuplikan layar 2024-01-02 070313" src="https://github.com/OpenSID/OpenSID/assets/87228587/887a0e1e-25e6-4ed7-b092-fa9201d98d30">

### Cara untuk mereplikasi errornya

Tambah Surat Baru

### Hasil yg diharapkan

Dapat menambahkan surat

### Tangkapan layar dan log error

Severity: error --> Exception: in_array(): Argument #2 ($haystack) must be of type array, null given (View: /home/berputar.opendesa.id/public_html/resources/views/admin/pengaturan_surat/tinymce.blade.php) (View: /home/berputar.opendesa.id/public_html/resources/views/admin/pengaturan_surat/tinymce.b
ade.php) /home/berputar.opendesa.id/public_html/storage/framework/views/423cb10425b838213913782a64f5bf06eab869d3.php 121

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2401.0.0-premium

**Comment by andifahruddinakas** [comment]
mas @agungsugiarto, ini terkait php 8.x, jika tambah belum ada data tersedia.

Cek yang berkaitan dengan hal tsb :
`in_array()`

**Comment by ai-skematik** [comment]
@andifahruddinakas  solusi sementaranya donk. terlanjur update dan ga bisa tambah surat.

**Comment by andifahruddinakas** [comment]
> @andifahruddinakas solusi sementaranya donk. terlanjur update dan ga bisa tambah surat.

https://forum.opendesa.id/d/312-php-8x-pada-v240100-terjadi-gagal-akses-tambah-surat

**Comment by ai-skematik** [comment]
> > @andifahruddinakas solusi sementaranya donk. terlanjur update dan ga bisa tambah surat.
> 
> https://forum.opendesa.id/d/312-php-8x-pada-v240100-terjadi-gagal-akses-tambah-surat

sudah bisa menambah tapi tidak bisa disimpan.
