### ISSUE TITLE
Saat klik Surat Tercetak di Beranda. Hasilnya error 404

### ISSUE THREAD

**Issue by pujocahyono** [OpenSID/OpenSID#7544]
### Jelaskan error yg dialami

Saat klik Surat Tercetak di Beranda, hasilnya halaman tidak ditemukan.
Jika akses melalui menu Layanan Surat - Arsip Layanan hasinya muncul normal.

### Cara untuk mereplikasi errornya

Halaman Beranda - Surat Tercetak

### Hasil yg diharapkan

Menampilkan arsip layanan dengan normal

### Tangkapan layar dan log error

![Screenshot_2024-01-02-09-27-20-479_com android chrome](https://github.com/OpenSID/OpenSID/assets/87228587/b4708e0e-ff47-4a02-bdd3-c8da13729254)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v2401.0.0

**Comment by langonsari** [comment]
apabila dihapus /clear baru bisa

**Comment by andifahruddinakas** [comment]
> apabila dihapus /clear baru bisa

silahkan migrasi dijalankan ulang. sy coba di https://berputar.opendesa.id/keluar tidak ada masalah.

<img width="352" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/eb12dcf6-efa2-49a7-9116-e666bdbf29f2">

**Comment by Sukoharjo3** [comment]
ternyata jg berhubungan dgn qrcode
ketika di klik link yg ada di qrcode itu jadi eror
di semua arsip surat di tes qrcode nya eror
<img width="960" alt="image" src="https://github.com/OpenSID/OpenSID/assets/112841792/a5d5f09c-8c13-4248-aadb-4e1f140cd2df">
