### ISSUE TITLE
Komponen Laravel

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#7545]
Ganti penanganan komponen laravel yang digunakan. 

- [ ] Gunakan package https://github.com/andifahruddinakas/laravel-bridge
- [ ] Setup package agar bisa digunakan di CI3, letakkan di config/hook.
```
<?php

defined('BASEPATH') or exit('No direct script access allowed');

/*
| -------------------------------------------------------------------------
| Hooks
| -------------------------------------------------------------------------
| This file lets you define "hooks" to extend CI without hacking the core
| files.  Please see the user guide for info:
|
|	https://codeigniter.com/user_guide/general/hooks.html
|
*/

require_once __DIR__.'/database.php';

bridge(FCPATH, $db);
```

- [ ] Ganti atau hapus helper yang sama digunakan di laravel, contoh : session(), view(), app(), cache(), encrypt(), decrypt(), config_path(), config(), dll

**Comment by agungsugiarto** [comment]
referensi 

> https://github.com/laravel/lumen-framework/blob/10.x/src/Application.php
> https://github.com/laravel/lumen/blob/10.x/bootstrap/app.php

**Comment by andifahruddinakas** [comment]
> referensi
> 
> > https://github.com/laravel/lumen-framework/blob/10.x/src/Application.php
> > https://github.com/laravel/lumen/blob/10.x/bootstrap/app.php

pakai ini saja mas @agungsugiarto https://github.com/andifahruddinakas/laravel-bridge, sudah sy sesuaikan dari bawaan lumen.
