### ISSUE TITLE
Format import data penduduk perlu ditambahkan kolom status rekam ktp

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#755]
Dengan adanya data status rekam KTP dr dinas dukcapil, maka perlu ada penambahan kolom untuk status rekam KTP di format impor Excel 
![image](https://user-images.githubusercontent.com/25834335/35342348-b06c34ba-00dc-11e8-86eb-5ac40d5fe032.png)

form data yang kami dapatkan dari dukcapil ada kolom status rekam e-KTP nya
![image](https://user-images.githubusercontent.com/25834335/35342512-1b3213be-00dd-11e8-8e96-f89addb32f54.png)

**Comment by MUHAMMADRANGSEL** [comment]
kepemilikan adminduk kami dapatkan dari dinas dukcapil sehingga memudahkan operator dan pemerintah desa tidak 2 kali kerja, olehkarena perlu ditambahkan kolom import status kepemilkan KTP seperti yang tertera diatas

**Comment by MUHAMMADRANGSEL** [comment]
untuk issue ini sdh kami kerjakan dan bersama ini kami lampirkan perubahan scripnya dan peubahan format impor excel
[Import Data Beserta Status Kepemilikan KTP.zip](https://github.com/OpenSID/OpenSID/files/1751287/Import.Data.Beserta.Status.Kepemilikan.KTP.zip)

**Comment by MUHAMMADRANGSEL** [comment]
karena issue ini sdah dikerjakan dan sdh dilampirkan perubahan scrip dan format impor excel mohon dimasukkan di rilis

**Comment by eddieridwan** [comment]
Telah digabung, dengan perubahan:

1. File FormatImportExcel.xls mengikuti contoh dengan macro untuk menyediakan pilihan kode untuk kolom _KTP EL_ dan _Status Rekam_.
