### ISSUE TITLE
Bug/error Rilis UMUM: Di cPanel terjadi error Imunify360 "Report black hash triggering" yang aktif

### ISSUE THREAD

**Issue by saferomedia** [OpenSID/OpenSID#7552]
### Jelaskan error yg dialami

ketika kami export, file rtf nya kapasitasnya 0 kb, dan isi filenya kosong. mohon petunjuknya  

![Untitled](https://github.com/OpenSID/OpenSID/assets/74395430/65ad6206-ab77-420f-8bff-d91687a4666a)

### Cara untuk mereplikasi errornya

ketika ingin download surat, hasilnya kosong , file surat pun kapasitas 0 kb

### Hasil yg diharapkan

semoga bisa diperbaiki

### Tangkapan layar dan log error

![Untitled](https://github.com/OpenSID/OpenSID/assets/74395430/449e5452-2a8b-458c-9a1f-a43728ecdec6)

### Rilis Versi OpenSID

Rilis Umum

### Versi OpenSID

v22.01

**Comment by balongbesuk** [comment]
hosting dmn?

**Comment by aminalam75** [comment]
saya juga begitu 0 kb dan kosng ketika dibuka

**Comment by aminalam75** [comment]
> hosting dmn?

domainesia

**Comment by andifahruddinakas** [comment]
<img width="228" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/5f263602-1b7a-4c39-9d70-b5c9a3f39492">

**Comment by ricoAf13** [comment]
Halo team OpenSID, saya kebetulan bekerja di salah satu provider hosting, dan menemukan penyebab dari masalah export surat yang kosong.

Masalah ini disebabkan oleh rule Imunify360 "Report black hash triggering" yang aktif dan membuat script _Surat_model.php_ tidak bekerja.

Jadi kalau masalah ini terjadi, bisa sampaikan ke pihak provider hosting untuk periksa log Imunify360 (atau antivirus lain), apakah terdapat log event yang mirip seperti :
![image](https://github.com/OpenSID/OpenSID/assets/56908275/47ccd1dc-b36a-4887-9e15-94422033a3af)
![image](https://github.com/OpenSID/OpenSID/assets/56908275/02eda78f-66d4-4b13-8739-c1403029ea96)

Kemudian request supaya mereka "Ignore detected rule for this file".

**Comment by eddieridwan** [comment]
Lihat di serambi.opendesa.id untuk replikasi masalah ini. Perlu dicari apa di surat_model.php yg menyebabkan. https://github.com/OpenSID/OpenSID/issues/7552#issuecomment-1911213828

Telusuri apakah hal ini terjadi juga pada versi2 sebelumnya. Kalau tidak terjadi di versi sebelumnya, maka masalah disebabkan perubahan pada 2401.

@andifahruddinakas @scqolbu24

**Comment by balongbesuk** [comment]
saya masih menggunakan 22.05 juga mengalami msalah ini,

tapi ketika coba cetak KK .rtf berjalan normal

**Comment by apidong** [comment]
mungkin karena penggunaan str_replace yang terlalu banyak. karena di kata str_replace di tulis berkali-kali di halaman blockingnya imunify

**Comment by andifahruddinakas** [comment]
Pembahasan dapat dilanjutkan di https://forum.opendesa.id/d/319-cetak-surat-rtf-tidak-mendudukung-hosting-cpanel-terbaru

**Comment by eddieridwan** [comment]
@andifahruddinakas perlu ada solusinya. Dugaan saya tetap pada kode RTF di surat_model yg mencurigakan.

**Comment by andifahruddinakas** [comment]
> @andifahruddinakas perlu ada solusinya. Dugaan saya tetap pada kode RTF di surat_model yg mencurigakan.

sesuai point terakhir,
<img width="316" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/a812f742-cf81-47e4-b3a8-6189d3746a4c">

mungkin akan di ikutkan di rilis umum (ssat pengabungan) jika fitur rtf belum dihapus.

setelah sy komment semua replace data rtfnya, hasilnya jalan (tidak error).
<img width="663" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/8b525169-2939-48db-846c-e0d90392e1d4">

**Comment by andifahruddinakas** [comment]
Solusi bisa dilihat di https://forum.opendesa.id/d/319-cetak-surat-rtf-tidak-mendudukung-hosting-cpanel-terbaru/2
