### ISSUE TITLE
Konversi Modul Prodeskel menggunakan konsep modul

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#7554]
Setelah penggabungan PR https://github.com/OpenSID/premium/pull/3336, lakukan perubahan struktur pada PR https://github.com/OpenSID/premium/pull/2259 menggunakan konsep modular.

Yang perlu di selesaikan : 
- [ ] buat repo untuk modul ini (private)
<img width="443" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/19b296f7-b7cc-4b63-9488-a95b3686fef1">

- [ ] sesuaikan PR https://github.com/OpenSID/premium/pull/2259 konsep modular
- [ ] pastikan migrasi jalan dengan baik
- [ ] pastikan modul bisa digunakan

**Comment by andifahruddinakas** [comment]
mas @agungsugiarto, kerjakan yang komponen laravel saja ya. issue ini sy assign ke mas @pandigresik

**Comment by andifahruddinakas** [comment]
mas @pandigresik, perbaiki bagian ini
https://github.com/OpenSID/premium/pull/3394#issuecomment-1888557286

**Comment by pandigresik** [comment]
> mas @pandigresik, perbaiki bagian ini [OpenSID/premium#3394 (comment)](https://github.com/OpenSID/premium/pull/3394#issuecomment-1888557286)

Sudah disesuaikan https://github.com/pandigresik/modul-prodeskel/commit/83fdc44d057e6a33c6bcdcb8c857e8fa4bc18b25
https://github.com/pandigresik/modul-prodeskel/archive/refs/tags/v1.0.1.zip

**Comment by andifahruddinakas** [comment]
> > mas @pandigresik, perbaiki bagian ini [OpenSID/premium#3394 (comment)](https://github.com/OpenSID/premium/pull/3394#issuecomment-1888557286)
> 
> Sudah disesuaikan [pandigresik/modul-prodeskel@83fdc44](https://github.com/pandigresik/modul-prodeskel/commit/83fdc44d057e6a33c6bcdcb8c857e8fa4bc18b25) https://github.com/pandigresik/modul-prodeskel/archive/refs/tags/v1.0.1.zip

di pindahkan ke repo osid ya, yang private aja.

**Comment by pandigresik** [comment]
> > > mas @pandigresik, perbaiki bagian ini [OpenSID/premium#3394 (comment)](https://github.com/OpenSID/premium/pull/3394#issuecomment-1888557286)
> > 
> > 
> > Sudah disesuaikan [pandigresik/modul-prodeskel@83fdc44](https://github.com/pandigresik/modul-prodeskel/commit/83fdc44d057e6a33c6bcdcb8c857e8fa4bc18b25) https://github.com/pandigresik/modul-prodeskel/archive/refs/tags/v1.0.1.zip
> 
> di pindahkan ke repo osid ya, yang private aja.

mas @andifahruddinakas https://github.com/OpenSID/modul-prodeskel

**Comment by andifahruddinakas** [comment]
> > > > mas @pandigresik, perbaiki bagian ini [OpenSID/premium#3394 (comment)](https://github.com/OpenSID/premium/pull/3394#issuecomment-1888557286)
> > > 
> > > 
> > > Sudah disesuaikan [pandigresik/modul-prodeskel@83fdc44](https://github.com/pandigresik/modul-prodeskel/commit/83fdc44d057e6a33c6bcdcb8c857e8fa4bc18b25) https://github.com/pandigresik/modul-prodeskel/archive/refs/tags/v1.0.1.zip
> > 
> > 
> > di pindahkan ke repo osid ya, yang private aja.
> 
> mas @andifahruddinakas https://github.com/OpenSID/modul-prodeskel

ok
