### ISSUE TITLE
Fuction Surat_model::get_data_mati() tidak ditemukan 

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#7556]
Function Surat_model::get_data_mati() masih digunakan pada lampiran yang dimana menyebabkan error saat cetak surat yang memiliki lampiran tsb. Bisa cek pada surat keterangan kematian.

Hal ini terjadi setelah penghapuspan fuction yang tidak digunakan pada surtat_model. Cek https://github.com/OpenSID/premium/commit/632f65338c45e025da2559c5d30d0eaef2c2fcaf#diff-76867c202e85caa1039005d58bb675edae99688c38ae353dfedd0707d854b51f

**Comment by ariandii** [comment]
![image](https://github.com/OpenSID/OpenSID/assets/46939846/f087c451-1df9-4583-80c0-cc97782fb0f6)
info dari group premium
