### ISSUE TITLE
ERROR 500 saat buat surat di layanan mandiri

### ISSUE THREAD

**Issue by pujocahyono** [OpenSID/OpenSID#7559]
### Jelaskan error yg dialami

ERROR 500 saat buat surat di layanan mandiri

### Cara untuk mereplikasi errornya

1. Masuk layanan mandiri
2. Buat surat
3. Masukkan syarat
4. Klik Isi Form
<img width="958" alt="Cuplikan layar 2024-01-04 100345" src="https://github.com/OpenSID/OpenSID/assets/87228587/8bca38e9-1a9d-409b-ac5b-71d333ce0c10">

### Hasil yg diharapkan

Bisa membuat surat di layanan mandiri 

### Tangkapan layar dan log error

Severity: error --> Exception: Class "App\Models\DB" not found /home/berputar.opendesa.id/public_html/donjo-app/core/MY_Log.php(206) : eval()'d code(1) : eval()'d code 337
<img width="958" alt="Cuplikan layar 2024-01-04 100802" src="https://github.com/OpenSID/OpenSID/assets/87228587/93c83121-68e3-41ad-94cd-92c38d403dc9">

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2401.0.0-premium

**Comment by andifahruddinakas** [comment]
Duplicate of https://github.com/OpenSID/OpenSID/issues/7562
