### ISSUE TITLE
Bug: mengisi menu persil data yg tampil hanya 20 orang saja

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#756]
dimenu persil data yang bisa ditampilkan hanya 20 orang saja dan juga perlu ditambahkan di footernya seperti gambar dibawah ini : 
![screenshot 2018-01-24 07 35 21](https://user-images.githubusercontent.com/25834335/35341389-696c5696-00da-11e8-9163-3a52b5f0e549.jpg)

**Comment by MUHAMMADRANGSEL** [comment]
![image](https://user-images.githubusercontent.com/25834335/35341436-92ae2cdc-00da-11e8-809f-5407cc900502.png)

dan di footernya perlu ditambahkan sesuai dengan gambar dibawah ini : 

![image](https://user-images.githubusercontent.com/25834335/35341558-c559882a-00da-11e8-9f66-2e4561ed3e12.png)

**Comment by MUHAMMADRANGSEL** [comment]
masalah ini juga masih terjadi di SID 3.10 data yang sudah terinput 100 lebih tapi yang tampil hanya 20 orang
![image](https://user-images.githubusercontent.com/25834335/35344138-3572af96-00e1-11e8-9e2d-04b1b5e04987.png)

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
