### ISSUE TITLE
ERROR 500 saat Import Hari Libur

### ISSUE THREAD

**Issue by pujocahyono** [OpenSID/OpenSID#7560]
### Jelaskan error yg dialami

ERROR 500 saat Import Hari Libur

### Cara untuk mereplikasi errornya

1. Menu Kehadiran
2. Hari Libur
3. Import
<img width="959" alt="Cuplikan layar 2024-01-04 111433" src="https://github.com/OpenSID/OpenSID/assets/87228587/0d07ca01-02ee-4469-8229-9eb22d02ea00">

### Hasil yg diharapkan

Dapat impor hari libur

### Tangkapan layar dan log error

<img width="960" alt="Cuplikan layar 2024-01-04 111421" src="https://github.com/OpenSID/OpenSID/assets/87228587/207e3ff1-3e8c-4b58-af27-3a1c2523ace3">

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2401.0.0-premium

**Comment by andifahruddinakas** [comment]
error :
`Severity: error --> Exception: date_format(): Argument #1 ($object) must be of type DateTimeInterface, bool given /home/berputar.opendesa.id/public_html/donjo-app/core/MY_Log.php(206) : eval()'d code(1) : eval()'d code 188`
