### ISSUE TITLE
App\Models\DB tidak dikenali

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#7562]
Beberapa kondisi terjadi error sbb:
- [ ] Error Lakukan permohonan surat layanan mandiri. (tidak tersedia)
`ERROR - 2024-01-04 10:19:23 --> Severity: error --> Exception: Class "App\Models\DB" not found /home/sragi.web.id/public_html/donjo-app/core/MY_Log.php(206) : eval()'d code(1) : eval()'d code 328`

**Comment by yogiperdana** [comment]
![image](https://github.com/OpenSID/OpenSID/assets/14155050/0f50e133-a5e8-4c9f-b41d-7947bb80cf14)

Saya berhasil buat suratnya mas

**Comment by yogiperdana** [comment]
Saya coba di berputar juga hasilnya sama

**Comment by andifahruddinakas** [comment]
Di berputar sdh sy resolve,di restore dulu

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui commit https://github.com/OpenSID/premium/commit/c8ce6ddd7fe7afb4bbc3f6f0e34889b52d62e220
