### ISSUE TITLE
Bug/error: URGENT

### ISSUE THREAD

**Issue by utay-cugung** [OpenSID/OpenSID#7566]
### Jelaskan error yg dialami

Template surat tinymce yang di buat ketika versi di bawah 2401. tidak berfungsi ketika di import ke versi 2401, dengan masalah NIK tidak membuka data setelah di pilih dan hasil cetak menjadi kosong.

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

seharusnya normal karena versi sebelum 2401 adalah versi persiapan migrasi tinymce atau waktu pembuatan surat pengganti rtf sebelum 2401.

### Tangkapan layar dan log error

di versi 2401 nik tidak membuka data
![image](https://github.com/OpenSID/OpenSID/assets/155012206/e169c8ef-a8d3-4fc9-852f-f36f8e7318c7)

dibawah versi 2401 normal
![image](https://github.com/OpenSID/OpenSID/assets/155012206/9778b286-3fcf-478c-8818-11a80607996e)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2401 premium

### Tema Yang Digunakan

-

### Informasi tambahan

mohon di segerakan, karena kebutuhan harian

**Comment by andifahruddinakas** [comment]
Pak @utay-cugung, template suratnya disertakan

**Comment by utay-cugung** [comment]
https://www.cugung-rajabasa.desa.id/artikel/2024/1/4/download-kumpulan-surat-model-tinymce

**Comment by pandigresik** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/3358/files#diff-b4cb16815f813aeef8a9ba4496e264cf87da221b751efdd7869fda1b1dcdf453

**Comment by Sukoharjo3** [comment]
<img width="960" alt="Cuplikan layar 2024-01-08 142610" src="https://github.com/OpenSID/OpenSID/assets/112841792/6f2271a1-2b06-4c9b-ae23-3b7ba1dfcb41">
mengalami jg

**Comment by andifahruddinakas** [comment]
mas @pandigresik, diberputar masoh sama tp sy coba di local tidak ada masalah..
https://berputar.opendesa.id/surat/form/surat-keterangan-usaha
<img width="683" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/0f14ae7d-c224-4bfd-9c73-7eae4f45bc85">

http://opensid.test/index.php/surat/form/surat-keterangan-usaha
![image](https://github.com/OpenSID/OpenSID/assets/57283157/6fc52587-d681-4b1b-aa4d-2b6c7b525fec)

**Comment by pandigresik** [comment]
apakah efek dari obfuscate ?

**Comment by andifahruddinakas** [comment]
> apakah efek dari obfuscate ?

Mungkin dibagikan controller yg menampilkan view-nya.

**Comment by pandigresik** [comment]
> mas @pandigresik, diberputar masoh sama tp sy coba di local tidak ada masalah.. https://berputar.opendesa.id/surat/form/surat-keterangan-usaha <img alt="image" width="683" src="https://private-user-images.githubusercontent.com/57283157/296194892-0f14ae7d-c224-4bfd-9c73-7eae4f45bc85.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwNjU3NzAsIm5iZiI6MTcwNTA2NTQ3MCwicGF0aCI6Ii81NzI4MzE1Ny8yOTYxOTQ4OTItMGYxNGFlN2QtYzIyNC00YmZkLTljNzMtN2VhZTRmNDViYzg1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEyVDEzMTc1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyNGU1MGQzNDdjZmY2MDJkMDYyYjQxNGFhNzE2MDQzNWFkZmIwMzMwZWEwOWFlZDZhM2VmN2QyNDQ0OTVkZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CaIKc8NCSJTdWKEM1qPQ3nTZBHKZB5vtpbvba28XRQ8">
> 
> http://opensid.test/index.php/surat/form/surat-keterangan-usaha ![image](https://private-user-images.githubusercontent.com/57283157/296195373-6fc52587-d681-4b1b-aa4d-2b6c7b525fec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwNjU3NzAsIm5iZiI6MTcwNTA2NTQ3MCwicGF0aCI6Ii81NzI4MzE1Ny8yOTYxOTUzNzMtNmZjNTI1ODctZDY4MS00YjFiLWFhNGQtMmI2YzdiNTI1ZmVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEyVDEzMTc1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1NDYzYWM4MTM2OTEyMThkM2RhNDIyYmI3ZTcyZWYwNjkxZjczYzQ3ZWI0Yjc5MWQxOGM4MmFjMjVkZTY3NGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nmTzTJJdiCPE3vphoCMbpxJ1DYMdDrbfKETnNXa53d0)

Saya berhasil mereplikasi setelah klik tombol surat bawaan sistem
