### ISSUE TITLE
Bug/error: Tombol batal pada edit menu tidak bisa di klik

### ISSUE THREAD

**Issue by raamaj** [OpenSID/OpenSID#7567]
### Jelaskan error yg dialami

Tombol yang di tandai tidak bisa di klik atau modal tidak tertutup

### Cara untuk mereplikasi errornya

1. Pergi ke halaman Admin Web -> Menu
2. Klik tombol Edit pada salah satu data
3. Klik tombol batal

### Hasil yg diharapkan

Ketika klik tombol batal, modal akan tertutup

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/50396709/8e741ef8-1cdb-4c67-9ad6-b31d492644ef)

### Rilis Versi OpenSID

Rilis Umum

### Versi OpenSID

2401.0.0

**Comment by raamaj** [comment]
Pada menu edit Pengaturan Menu Dinamis / Kategori juga tidak bisa di klik (tidak kembali ke halaman sebelumnya)
![image](https://github.com/OpenSID/OpenSID/assets/50396709/3db191f4-8796-4fee-a81f-72f251360b0b)

**Comment by raamaj** [comment]
Pada menu tambah juga tidak bisa
![image](https://github.com/OpenSID/OpenSID/assets/50396709/9dc70aa6-992d-4a36-bc3f-eaa3f5891f39)

**Comment by andifahruddinakas** [comment]
mas @raamaj, cek pembahasan https://github.com/OpenSID/OpenSID/wiki/Struktur-Form-Isian

**Comment by raamaj** [comment]
> mas @raamaj, cek pembahasan https://github.com/OpenSID/OpenSID/wiki/Struktur-Form-Isian

ah iya mas, saya kira itu untuk close atau kembali ke halaman sebelumnya. Mungkin untuk kata nya bisa di ganti dengan "Hapus Isian Form" atau semacamnya yang menunjukan bahwa tombol itu untuk hapus semua isian pada form

**Comment by eddieridwan** [comment]
@andifahruddinakas "Kembalikan isian ke semula"
