### ISSUE TITLE
Permintaan fitur: kode isian form penerima kuasa belum ada pada menu kode isian di template surat

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#7571]
### Apa kekurangan yg ingin diatasi?

belum adanya kode form isian penerima kuasa

### Jelaskan solusi yg diinginkan

masukkan kode isian penerima kuasa pada template surat tinymce

### Apakah ada alternatif lain

dokumentasikan kode isian tinymce agar mempermudah pengecekan kode isian yang sudah ada dalam sistem dan yang belum

### Untuk versi OpenSID mana

premium

### Informasi tambahan

terdapat kode isian pada contoh template surat kuasa namun kode isian tersebut kurang lengkap seperti no kk, dll, agar memudahkkan melengkapi kode isian untuk penerima kuasa bisa di masukkan ke menu kode isian

**Comment by andifahruddinakas** [comment]
Sudah disediakan pengaturan data dinamis
