### ISSUE TITLE
Bug/error: Pemberitahuan

### ISSUE THREAD

**Issue by afri18** [OpenSID/OpenSID#7572]
### Jelaskan error yg dialami

Saat klik tombol tambah penduduk karna masuk (hampir semua klik menu) muncul pemberitahuan data berhasil disimpan, padahal belum simpan apa2

### Cara untuk mereplikasi errornya

harusnya pemberitahuan data berhasil disimpan hanya saat klik/tekan tombol simpan saja

### Hasil yg diharapkan

tidak ada pemberitahuan data berhasil di simpan

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/6611881/2ed5946d-b87e-42e8-9ff2-2c3e31437c59)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2401.0.0

### Tema Yang Digunakan

denatra

### Informasi tambahan

versi sebelumnya hal ini tidak terjadi

**Comment by andifahruddinakas** [comment]
pada bagian ini :
<img width="161" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/cc586436-9650-417f-bee0-f1690e3bec8e">

ganti dengan flash_session saja agar tidak perlu repot menghapus session notifikasi tsb.
