### ISSUE TITLE
Bug/error: restore database

### ISSUE THREAD

**Issue by afri18** [OpenSID/OpenSID#7575]
### Jelaskan error yg dialami

saat restore hasil backup an dari online di lokalan (offline) halaman web tidak bisa di akses

### Cara untuk mereplikasi errornya

sebaiknya hasil backup an di restore walau offline hasil sama

### Hasil yg diharapkan

sebaiknya hasil backup an di restore walau offline hasil sama

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/6611881/8dae4033-0c1e-48d0-98bd-f28ae1c3721f)
[log-2024-01-09.zip](https://github.com/OpenSID/OpenSID/files/13868255/log-2024-01-09.zip)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2401.0.0

### Tema Yang Digunakan

denatra

### Informasi tambahan

di versi sebelumnya hasil backupan kalau di restore tidak bermasalah

**Comment by andifahruddinakas** [comment]
Sepertinya backup database versi sebelumnya tidak lengkap, bisa lakukan backup ulang dengan versi terbaru yang sudah disesuaikan.
