### ISSUE TITLE
Bug/error: buat artikel

### ISSUE THREAD

**Issue by afri18** [OpenSID/OpenSID#7576]
### Jelaskan error yg dialami

saat klik menu Adminweb>artikel hasil menuju halaman web

### Cara untuk mereplikasi errornya

harusnya kehalaman menu artikel

### Hasil yg diharapkan

masuk menu artikel

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/6611881/8a70b038-e1c4-4a31-b74d-abe4a6db659d)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2401.0.0

### Tema Yang Digunakan

denatra

### Informasi tambahan

di coba offline bisa, hanya online setelah update 2401.0.0

**Comment by andifahruddinakas** [comment]
pak @afri18, sertakan log

**Comment by andifahruddinakas** [comment]
pak @afri18, sy coba tidak bermasalah https://berputar.opendesa.id/web
<img width="528" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/912fe449-ee16-4a96-86f5-2a13844f83cf">

**Comment by afri18** [comment]
ini karna migrasi tidak komplit, table artikel berbeda dengan yang awal instal

**Comment by afri18** [comment]
> pak @afri18, sy coba tidak bermasalah https://berputar.opendesa.id/web <img alt="image" width="528" src="https://private-user-images.githubusercontent.com/57283157/295123986-912fe449-ee16-4a96-86f5-2a13844f83cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5MzU4NTksIm5iZiI6MTcwNDkzNTU1OSwicGF0aCI6Ii81NzI4MzE1Ny8yOTUxMjM5ODYtOTEyZmU0NDktZWUxNi00YTk2LTg2ZjUtMmExMzg0NGY4M2NmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTExVDAxMTIzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhN2JiOGU3OGE5NzNmYTgyMDhjZmVmY2M0YThiM2U2NWRiMzk2OGE4OWEwNTk1ZjNjMmJlNDBjZDRmOWNiN2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.P1dztv4sZHetp9-mX0rrWcLN5XJi0a7B-Sr0kbUhDPE">

sudah saya periksa, memang bisa, dan offline di saya juga bisa, tapi online bermasalah, ternyata table artikel berbeda (tidak termigrasi) denga versi baru
