### ISSUE TITLE
Bug/error: saat simpan surat data kosong (versi 2401 premium)

### ISSUE THREAD

**Issue by f4hmyriza** [OpenSID/OpenSID#7578]
### Jelaskan error yg dialami

saat simpan surat data pada surat  kosong (versi 2401 premium)
![bug sid](https://github.com/OpenSID/OpenSID/assets/150425923/7c5b6e8c-0d41-4e8a-8b2f-116d83a510f4)

### Cara untuk mereplikasi errornya

1. Layanan surat - Cetak surat-buat surat-pilih nama/nik-simpan

### Hasil yg diharapkan

data bisa keluar seperti biasa

### Tangkapan layar dan log error

![bug sid](https://github.com/OpenSID/OpenSID/assets/150425923/c2510afb-369f-4973-a89f-eda07b468cc0)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v2401.0.0-premium

### Tema Yang Digunakan

silir 4.5

### Informasi tambahan

saat simpan surat data pada surat  kosong

**Comment by andifahruddinakas** [comment]
Duplicate issue https://github.com/OpenSID/OpenSID/issues/7566
