### ISSUE TITLE
Terjadi erro 500 saat tambah data penduduk

### ISSUE THREAD

**Issue by mranca** [OpenSID/OpenSID#7579]
### Jelaskan error yg dialami

Terjadi error 500 saat tambah data penduduk 

### Cara untuk mereplikasi errornya

.

### Hasil yg diharapkan

.

### Tangkapan layar dan log error

.

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

V2401

### Tema Yang Digunakan

.

### Informasi tambahan

.

**Comment by eddieridwan** [comment]
@mranca laporan ini tidak bisa ditindaklanjuti sebelum setiap bagian diisi dengan info yang diperlukan. Harap lengkapi. Pastikan juga dapat direplikasi bugnya di https://berputar.opendesa.id.
