### ISSUE TITLE
Download SID

### ISSUE THREAD

**Issue by KEDAMEAN** [OpenSID/OpenSID#758]
salam sejahtera saudara2 setanah air, saya minta bantuan cara mendonlot SID karena pendaftaran saya selalu gagal

**Comment by eddieridwan** [comment]
@KEDAMEAN : issue bukan tempat bertanya mengenai SID. Silakan bergabung di https://www.facebook.com/groups/OpenSID/. Di situ ada banyak yang bisa membantu. 

Issue adalah tempat mendaftarkan bug aplikasi, atau tugas/usulan/permintaan perbaikan aplikasi lainnya.

**Comment by KEDAMEAN** [comment]
Terimakasih atas petunjuknya

Pada tanggal 26 Jan 2018 5.41 PM, "Eddie Ridwan" <notifications@github.com>
menulis:

**Comment by KEDAMEAN** [comment]
Hai,

Saya baru saja menandatangani petisi "Presiden @Jokowi, Tolak Kembalinya
Dwi-Fungsi ABRI melalui Penempatan TNI di Lembaga Sipil. @bambangsoesatyo"
dan ingin tahu apakah Anda dapat membantu dengan menambahkan nama Anda.

Tujuan kami adalah untuk mencapai 35.000 tanda tangan dan kami membutuhkan
dukungan lebih banyak. Anda dapat membaca lebih banyak petisi dan
menandatanganinya di sini:

http://chng.it/tq6HMqdQVx

Terima kasih!
Harjo

**Comment by happyagung25** [comment]
Lag dia kampanye
