### ISSUE TITLE
Bug/error: cari artikel

### ISSUE THREAD

**Issue by afri18** [OpenSID/OpenSID#7580]
### Jelaskan error yg dialami

setelah artikel di buat baru konsep lalu simpan dan mau di edit dicari di pencarian tidak muncul

### Cara untuk mereplikasi errornya

harusnya saat cari artikel klik tombol cari menampilkan artikel yang di maksud karna mau d edit

### Hasil yg diharapkan

artikel tersimpan dan bisa di edit ulang

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/6611881/8abe09fe-2d02-41e8-b9e0-08bd01cfd4ab)
[cari_artikel_tdkmuncul.zip](https://github.com/OpenSID/OpenSID/files/13896011/cari_artikel_tdkmuncul.zip)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2401.0.0

### Tema Yang Digunakan

denatra

### Informasi tambahan

harusnya artikel tersimpan dan saat d cari muncul, dan urutan artikel mulai dari yang terbaru

**Comment by andifahruddinakas** [comment]
terkait issue https://github.com/OpenSID/premium/issues/3378
