### ISSUE TITLE
Bug/error: Jenis Artikel

### ISSUE THREAD

**Issue by afri18** [OpenSID/OpenSID#7582]
### Jelaskan error yg dialami

saat klik jenis artikel tidak menampilkan jenis artikel yang dimaksud

### Cara untuk mereplikasi errornya

harusnya yang tampil sesuai dengan jenis artikel yang di klik/maksud

### Hasil yg diharapkan

saat klik jenis artikel menampilkan sesuai jenis artikel

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/6611881/e0ee84cb-68f3-4970-82c3-68bc25d818f5)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2401.0.0

### Tema Yang Digunakan

denatra

### Informasi tambahan

versi sebelumnya bisa menampilkan jenis artikel yang di maksud

**Comment by andifahruddinakas** [comment]
Duplicate issue https://github.com/OpenSID/premium/issues/3378
