### ISSUE TITLE
Bug/error: halaman web eror

### ISSUE THREAD

**Issue by afri18** [OpenSID/OpenSID#7585]
### Jelaskan error yg dialami

saat update ke 2401.0.1 halaman web tidak tampil

### Cara untuk mereplikasi errornya

harusnya tampil seperti biasanya

### Hasil yg diharapkan

saat update halaman web tampil tidak blank/putih

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/6611881/0b2c9581-422c-4b05-a435-d2d8a16a2c60)

halaman siteman bisa diakses dan melakukan migrasi ke 2401.0.1 namun tetap halaman web gagal
![image](https://github.com/OpenSID/OpenSID/assets/6611881/b81f4717-446f-4e48-97bc-66f8fd40e688)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2401.0.1

### Tema Yang Digunakan

denatra

### Informasi tambahan

bisa akses siteman dan melakukan migrasi, sayangnya tetap halaman web gagal tampil

**Comment by afri18** [comment]
[log-2024-01-11.zip](https://github.com/OpenSID/OpenSID/files/13901922/log-2024-01-11.zip)

**Comment by andifahruddinakas** [comment]
pak @afri18, silahkan sertakan database yang bisa di ujicoba. atau bisa duplikasi error ini ke https://berputar.opendesa.id/

**Comment by afri18** [comment]
masa database d bagikan, itu data om, ada keterikatan dan tanggung jawab, berikan saja solusi atau table mana yv bermasalah, database utuh nggak mungkin...🙏🙏

**Comment by andifahruddinakas** [comment]
> pak @afri18, silahkan sertakan database yang bisa di ujicoba. atau bisa duplikasi error ini ke https://berputar.opendesa.id/

silahkan dibaca baik2 pesannya:
`pak @afri18, silahkan sertakan database yang bisa di ujicoba. atau bisa duplikasi error ini ke https://berputar.opendesa.id/`

**Comment by andifahruddinakas** [comment]
pak @afri18, kalau ada kesempatan bisa ke DC untuk diskusi langsung dengan programer yang bertugas untuk masalah ini dan masalah lain yang terkait database..

**Comment by afri18** [comment]
> pak @afri18, kalau ada kesempatan bisa ke DC untuk diskusi langsung dengan programer yang bertugas untuk masalah ini dan masalah lain yang terkait database..

tentukan waktunya ...

**Comment by afri18** [comment]
kasus ini akan sama saat menambahkan/menampilkan data suplemen ke menu
![image](https://github.com/OpenSID/OpenSID/assets/6611881/080be972-79b1-4580-b2d1-c02776f50e21)
![tambahmenu_suplemen_eror](https://github.com/OpenSID/OpenSID/assets/6611881/17ddd8b1-5a81-4825-89f9-8c685f0d65f1)

[log-2024-01-13.zip](https://github.com/OpenSID/OpenSID/files/13925215/log-2024-01-13.zip)
