### ISSUE TITLE
Eror saat Rekam Masuk Kehadiran

### ISSUE THREAD

**Issue by pujocahyono** [OpenSID/OpenSID#7586]
### Jelaskan error yg dialami

Eror saat Rekam Masuk Kehadiran

### Cara untuk mereplikasi errornya

Rekam Masuk Kehadiran

### Hasil yg diharapkan

Tidak eror saat Rekam Masuk Kehadiran

### Tangkapan layar dan log error

<img width="960" alt="Cuplikan layar 2024-01-12 101022" src="https://github.com/OpenSID/OpenSID/assets/87228587/038df20a-9822-4aca-b102-daef3d964f80">

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2401.0.1-premium

**Comment by andifahruddinakas** [comment]
Issue https://github.com/OpenSID/premium/issues/3335

Solusi sementara : 
https://forum.opendesa.id/d/314-rekam-masuk-404
