### ISSUE TITLE
Bug: Ejaan salah di Menu Laporan ==> Layanan Mandiri

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#759]
di Menu Laporan ==> Layanan Mandiri
untuk pembuatan pin ada kekeliruan penulisan PIN Waraga seharusnya PIN Warga
![pin warga](https://user-images.githubusercontent.com/25834335/35467576-0a1964ee-02c5-11e8-83aa-3a80f0ff970f.jpg)

**Comment by MUHAMMADRANGSEL** [comment]
masalahnya di folder donjo-app/views/mandiri
[mandiri.zip](https://github.com/OpenSID/OpenSID/files/1669700/mandiri.zip)

**Comment by MUHAMMADRANGSEL** [comment]
Mohon dimasukkan ke rilis mas Eddie

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
