### ISSUE TITLE
Bug/error: surat yg memakai lampiran tidak bisa di sesuaikan lampiran nya

### ISSUE THREAD

**Issue by Sukoharjo3** [OpenSID/OpenSID#7594]
### Jelaskan error yg dialami

saat membuat surat yg membutuhkan lampiran seperti pengantar nikah dibutuhkan penyesuaian pada halaman lampiran tersebut, tetapi saat ini yg bisa disesuaikan hanya halaman awal saja

### Cara untuk mereplikasi errornya

template surat tanpa lampiran atau bisa menyesuaikan lampiran surat

### Hasil yg diharapkan

template surat tanpa lampiran langsung banyak halaman di pengaturan surat atau bisa menyesuaikan lampiran surat

### Tangkapan layar dan log error

![Screenshot_20240112-223240](https://github.com/OpenSID/OpenSID/assets/112841792/6637a8e7-60ce-4289-939b-dab683944400)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2401.0.0

### Tema Yang Digunakan

denava

**Comment by eddieridwan** [comment]
@Sukoharjo3 beri contoh penyesuaian yg dimaksud. **Lampiran berupa format baku yg tidak untuk diubah**. Jadi jika ada yg saat ini tidak tepat, jelaskan persisnya kasus2 yg dimaksud, supaya dapat diperbaiki.

**Comment by andifahruddinakas** [comment]
terkait issue https://github.com/OpenSID/OpenSID/issues/7538
