### ISSUE TITLE
Error 404 saat akan menambahkan Kode Isian Surat

### ISSUE THREAD

**Issue by pujocahyono** [OpenSID/OpenSID#7598]
### Jelaskan error yg dialami

Error 404 saat akan menambahkan Kode Isian Surat

### Cara untuk mereplikasi errornya

1. Buat surat atau rubah surat
2. Klik **Kode Isian** pada template

### Hasil yg diharapkan

tidak error saat akan memasukkan kode isian

### Tangkapan layar dan log error

<img width="960" alt="Cuplikan layar 2024-01-13 063721" src="https://github.com/OpenSID/OpenSID/assets/87228587/75a5688f-3f9a-4af6-a57f-69b4f7b0c653">

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2401.0.1-premium

**Comment by pandigresik** [comment]
https://github.com/OpenSID/premium/pull/3357/commits/7f00dcaba75709d5e4f284ea220109ac7cd771fe
