### ISSUE TITLE
Eror saat Tambah Album Galeri 

### ISSUE THREAD

**Issue by pujocahyono** [OpenSID/OpenSID#7599]
### Jelaskan error yg dialami

Eror saat Tambah Album Galeri

### Cara untuk mereplikasi errornya

Tambah Album di Galeri Web

### Hasil yg diharapkan

Dapat menambahkan album pada menu galeri

### Tangkapan layar dan log error

<img width="960" alt="Cuplikan layar 2024-01-13 071123" src="https://github.com/OpenSID/OpenSID/assets/87228587/4a46e6ab-0151-4de4-86a4-8c5efb66e8e2">

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2401.0.1-premium

**Comment by andifahruddinakas** [comment]
pak @pujocahyono, sy coba di https://berputar.opendesa.id/ tidak ada masalah tsb
<img width="683" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/18ff5aac-a3fd-4326-8c68-7231066d6618">
