### ISSUE TITLE
Bug: di menu admin web untuk Kategori / Menu DInamis tidak ada paginasi

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#760]
di menu admin web untuk Kategori / Menu DInamis paginasinya tidak ada sedangkan di Menu Statis Ada
di menu statis
![menu statis](https://user-images.githubusercontent.com/25834335/35468576-d61142e6-02d5-11e8-8644-0d3b3c1c6883.jpg)

menu dinamis

![menu dinamis](https://user-images.githubusercontent.com/25834335/35468583-fc3a8db0-02d5-11e8-9d95-8977e136a680.jpg)

**Comment by ombimo** [comment]
![image](https://user-images.githubusercontent.com/20896126/35860087-3a1cd99c-0b75-11e8-833e-22ee30d2168d.png)
secara code ternyata sudah ada paginasi, cuma paginasi terbuang ke bawah jadi tidak kelihatan.
dan setelah saya cek, hal tersebut bisa terjadi hampir di semua halaman ketika ukuran layar terlalu kecil.
![image](https://user-images.githubusercontent.com/20896126/35860179-a82f002c-0b75-11e8-8f8d-8177a88160ab.png)
@eddieridwan enaknya bagaimana om ?

**Comment by MUHAMMADRANGSEL** [comment]
Tampilan yg diawal bagus

Pada tanggal 6 Feb 2018 8.42 PM, "Bimo Aji Pamungkas" <
notifications@github.com> menulis:

**Comment by ombimo** [comment]
@eddieridwan #781 sedikit perubahan di view agar terlihat paginasinya

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR #781
