### ISSUE TITLE
Error saat pilih Rumah Tangga pada Legenda di Peta

### ISSUE THREAD

**Issue by pujocahyono** [OpenSID/OpenSID#7600]
### Jelaskan error yg dialami

Error saat pilih Rumah Tangga pada Legenda di Peta

### Cara untuk mereplikasi errornya

Pilih Rumah Tangga pada Legenda
<img width="81" alt="Cuplikan layar 2024-01-13 094056" src="https://github.com/OpenSID/OpenSID/assets/87228587/d41795b7-25b3-4c9b-8864-04f311044ad2">

### Hasil yg diharapkan

Tidak eror saat pilihan Ruah Tangga pada Legenda di Peta

### Tangkapan layar dan log error

<img width="960" alt="Cuplikan layar 2024-01-13 094000" src="https://github.com/OpenSID/OpenSID/assets/87228587/01dff16e-528b-46b5-8448-a58e4612decb">

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2401.0.1-premium

**Comment by andifahruddinakas** [comment]
issue https://github.com/OpenSID/premium/issues/3335

**Comment by pandigresik** [comment]
> issue [OpenSID/premium#3335](https://github.com/OpenSID/premium/issues/3335)

https://github.com/OpenSID/premium/pull/3357/commits/1e144ac77fec3c8e685cd852bc936f4ce12c1d85

Hanya saja saya gak tau dari mana fitur ke alamat itu

**Comment by andifahruddinakas** [comment]
> > issue [OpenSID/premium#3335](https://github.com/OpenSID/premium/issues/3335)
> 
> [OpenSID/premium@1e144ac](https://github.com/OpenSID/premium/commit/1e144ac77fec3c8e685cd852bc936f4ce12c1d85)
> 
> Hanya saja saya gak tau dari mana fitur ke alamat itu

Sy cek sudah jalan
<img width="546" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/e1d84a9e-4385-4200-b4de-e62a296128d2">
