### ISSUE TITLE
Bug/error: Tampilan Pengaturan Surat

### ISSUE THREAD

**Issue by afri18** [OpenSID/OpenSID#7601]
### Jelaskan error yg dialami

Tampilan di pengaturan surat agak kacau

### Cara untuk mereplikasi errornya

seharusnya koding tidak d tampilkan

### Hasil yg diharapkan

tampilan normal dengan tidak ada tampilan bahasa pemograman

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/6611881/c5a96ed1-b00f-41ff-b5fe-b25b847291d7)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2401.0.1

### Tema Yang Digunakan

denatra

### Informasi tambahan

nggak ngarti kode pemograman

**Comment by andifahruddinakas** [comment]
pak @afri18, sudah ada di https://forum.opendesa.id/d/314-masalah-terkait-rilis-v240101

terkait obfuscate, dan ditambahkan di proses rilis https://github.com/OpenSID/premium/issues/3398

**Comment by afri18** [comment]
> pak @afri18, sudah ada di https://forum.opendesa.id/d/314-masalah-terkait-rilis-v240101
> 
> terkait obfuscate, dan ditambahkan di proses rilis [OpenSID/premium#3398](https://github.com/OpenSID/premium/issues/3398)

siap
