### ISSUE TITLE
Bug/error: Istri Terdahulu

### ISSUE THREAD

**Issue by afri18** [OpenSID/OpenSID#7603]
### Jelaskan error yg dialami

Poin A.4 mestinya berisi  data Nama Istri Terdahulu untuk calon laki-laki tidak muncul

### Cara untuk mereplikasi errornya

Tampilkan Poin A.4 untuk status calan laki-laki dengan status Kawin/Cerai Hidup/Cerai Mati

### Hasil yg diharapkan

Sistem bisa memilih data untuk Point A.4 (Istri Terdahulu) dan B.4 (Suami terdahulu)

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/6611881/5506ca6f-31b1-4ff3-994e-79d6ed95d1b2)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2401.0.1

### Tema Yang Digunakan

denatra

### Informasi tambahan

Bila Status Calon Pengantin Belum Kawin (Jejaka/Gadis) Data suami/isteri terdahulu jangan ditampilkan

**Comment by andifahruddinakas** [comment]
pak @afri18, untuk data dari isian tsb digunakan dimana?

**Comment by andifahruddinakas** [comment]
> pak @afri18, untuk data dari isian tsb digunakan dimana?

pak @afri18, bisa jawab yang ini?

**Comment by afri18** [comment]
> > pak @afri18, untuk data dari isian tsb digunakan dimana?
> 
> pak @afri18, bisa jawab yang ini?

berputar

**Comment by andifahruddinakas** [comment]
> > > pak @afri18, untuk data dari isian tsb digunakan dimana?
> > 
> > 
> > pak @afri18, bisa jawab yang ini?
> 
> berputar

buka, untuk data tambahan tsb ditampilkan di lampiran bagian mana? apakah ada tambahan lg? bisa beri contoh penggunaan data tsb.

**Comment by andifahruddinakas** [comment]
Sudah disesuaikan di v2407.0.0
