### ISSUE TITLE
Bug/error: halaman kosong

### ISSUE THREAD

**Issue by afri18** [OpenSID/OpenSID#7605]
### Jelaskan error yg dialami

saat ingin menampilkan halaman peristiwa  mati, datang atau pindah tampilan kosong

### Cara untuk mereplikasi errornya

tampilkan halaman yang dimaksud

### Hasil yg diharapkan

menampilkan halaman sesuai dengan pilihan

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/6611881/2f08b269-c582-491d-91a7-4545b2a5601e)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2401.0.1

### Tema Yang Digunakan

denatra

### Informasi tambahan

terjadi saat catatan peristiwa dipindah dari pencarian khusus

**Comment by andifahruddinakas** [comment]
pak @afri18, sy coba di berputar tidak ada masalah tsb.
<img width="672" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/1df899f1-146d-4efa-91cb-f75d3fd6eb7f">

**Comment by afri18** [comment]
> pak @afri18, sy coba di berputar tidak ada masalah tsb. <img alt="image" width="672" src="https://private-user-images.githubusercontent.com/57283157/296638056-1df899f1-146d-4efa-91cb-f75d3fd6eb7f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUyODU4NzAsIm5iZiI6MTcwNTI4NTU3MCwicGF0aCI6Ii81NzI4MzE1Ny8yOTY2MzgwNTYtMWRmODk5ZjEtMTQ2ZC00ZWZhLTkxY2ItZjc1ZDNmZDZlYjdmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE1VDAyMjYxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1NGE0ZTBiNTcwNDg2MDk2MjIwMDEzYjY4Yjk2YjMxOGY4YTQ2OGZlNzc0Y2Y1YTI5ODMyMzc1MzVjMzcwZDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JAkLPowtKHtHSDpIoPJoJ7NRSITM5lOTOtv8IhDasrA">

itu yg saya maksud, di berputar bisa tapi d 2401.0.1 yg saya gunakan tidak bisa, kalau tidak salah di berputar itu khusus layanan siap pakai, kemungkinan tidak sama dengan yg saya gunakan

**Comment by afri18** [comment]
> pak @afri18, sy coba di berputar tidak ada masalah tsb. <img alt="image" width="672" src="https://private-user-images.githubusercontent.com/57283157/296638056-1df899f1-146d-4efa-91cb-f75d3fd6eb7f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUyODY5NzQsIm5iZiI6MTcwNTI4NjY3NCwicGF0aCI6Ii81NzI4MzE1Ny8yOTY2MzgwNTYtMWRmODk5ZjEtMTQ2ZC00ZWZhLTkxY2ItZjc1ZDNmZDZlYjdmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE1VDAyNDQzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhZTM0ZDQxZDhiYmM5MGRlNDNlMTk5Y2UzYzY5YmU5NmVlZjA0YWVlNTA5ZTJiOTY4NmQ1ZDdhYTFiYmUzNjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.58WcQcZZo9wI2JapaHIn9GUFApEOJLLFYrT8QDAyrn8">

[catatan_peristiwa.zip](https://github.com/OpenSID/OpenSID/files/13934325/catatan_peristiwa.zip)

**Comment by andifahruddinakas** [comment]
> > pak @afri18, sy coba di berputar tidak ada masalah tsb. <img alt="image" width="672" src="https://private-user-images.githubusercontent.com/57283157/296638056-1df899f1-146d-4efa-91cb-f75d3fd6eb7f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUyODY5NzQsIm5iZiI6MTcwNTI4NjY3NCwicGF0aCI6Ii81NzI4MzE1Ny8yOTY2MzgwNTYtMWRmODk5ZjEtMTQ2ZC00ZWZhLTkxY2ItZjc1ZDNmZDZlYjdmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE1VDAyNDQzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhZTM0ZDQxZDhiYmM5MGRlNDNlMTk5Y2UzYzY5YmU5NmVlZjA0YWVlNTA5ZTJiOTY4NmQ1ZDdhYTFiYmUzNjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.58WcQcZZo9wI2JapaHIn9GUFApEOJLLFYrT8QDAyrn8">
> 
> [catatan_peristiwa.zip](https://github.com/OpenSID/OpenSID/files/13934325/catatan_peristiwa.zip)

apakah https://forum.opendesa.id/d/314-masalah-terkait-rilis-v240101 sudah diterapkan

**Comment by afri18** [comment]
> > > pak @afri18, sy coba di berputar tidak ada masalah tsb. <img alt="image" width="672" src="https://private-user-images.githubusercontent.com/57283157/296638056-1df899f1-146d-4efa-91cb-f75d3fd6eb7f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUyODY5NzQsIm5iZiI6MTcwNTI4NjY3NCwicGF0aCI6Ii81NzI4MzE1Ny8yOTY2MzgwNTYtMWRmODk5ZjEtMTQ2ZC00ZWZhLTkxY2ItZjc1ZDNmZDZlYjdmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE1VDAyNDQzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhZTM0ZDQxZDhiYmM5MGRlNDNlMTk5Y2UzYzY5YmU5NmVlZjA0YWVlNTA5ZTJiOTY4NmQ1ZDdhYTFiYmUzNjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.58WcQcZZo9wI2JapaHIn9GUFApEOJLLFYrT8QDAyrn8">
> > 
> > [catatan_peristiwa.zip](https://github.com/OpenSID/OpenSID/files/13934325/catatan_peristiwa.zip)
> 
> apakah https://forum.opendesa.id/d/314-masalah-terkait-rilis-v240101 sudah diterapkan

sudah...
