### ISSUE TITLE
Bug/error: Exception: Undefined constant "Provinsi" Saat Install Baru

### ISSUE THREAD

**Issue by f4hmyriza** [OpenSID/OpenSID#7607]
### Jelaskan error yg dialami

Terjadi erros saat fresh install atau install baru versi 2401.00 (umum), saat login tampilan blank putih,
log errornya : ERROR - 2024-01-15 14:09:28 --> Severity: error --> Exception: Undefined constant "Provinsi" (View: /var/www/clients/client20/web149/web/resources/views/admin/identitas_desa/index.blade.php)

### Cara untuk mereplikasi errornya

lihat file index.blade.php pada folder resources/views/admin/identitas_desa/index.blade.php) baris 73 pada Provinsi tambahkan tanda petik ' ' sehinggan menjadi 'Provinsi'

### Hasil yg diharapkan

tidak terjadi error lagi

### Tangkapan layar dan log error

ERROR - 2024-01-15 14:09:28 --> Severity: error --> Exception: Undefined constant "Provinsi" (View: /var/www/clients/client20/web149/web/resources/views/admin/identitas_desa/index.blade.php) /var/www/clients/client20/web149/web/storage/framework/views/9c1ea0bba561fb4d96f9ea82dd861cd1821bf6e2.php 72

### Rilis Versi OpenSID

Rilis Umum

### Versi OpenSID

v2401.00

### Tema Yang Digunakan

natra v22.11

**Comment by andifahruddinakas** [comment]
pak @nurlia-astika, bisa diganti dengan perubahan https://github.com/OpenSID/OpenSID/commit/5eb1d8832dca1c6a514fd9377b0e6cfad8f81c24

pada rilis https://github.com/OpenSID/premium/blob/v2312.0.3-premium-clear/resources/views/admin/identitas_desa/index.blade.php sudah diperbaiki.

namun terlihat error tsb karena penggunaan php yg strict, bisa gunakan php 7.4 untuk versi umum
