### ISSUE TITLE
Bug/error: error sidebar.blade.php

### ISSUE THREAD

**Issue by f4hmyriza** [OpenSID/OpenSID#7608]
### Jelaskan error yg dialami

Halaman Blank Putih saat install baru setelah dilakukan perbaikan pada error --> Exception: Undefined constant "Provinsi" masih terdapat error lagi.
pada sidebar.blade.php, Pesan kesalahan menunjukkan bahwa fungsi count() di PHP mengharapkan argumen bertipe Countable atau array, tetapi menerima null. Ini terjadi karena $mod['submodul'] adalah null.

### Cara untuk mereplikasi errornya

pergi ke sidebar.blade.php pada folder resources/views/admin/layouts/partials/sidebar.blade.php pada baris 45
<?php if (count($mod['submodul']) == 0): ?>
di ganti dengan
<?php if (isset($mod['submodul'])&& count($mod['submodul']) == 0): ?>

### Hasil yg diharapkan

tidak terjadi error lagi

### Tangkapan layar dan log error

Severity: error --> Exception: count(): Argument #1 ($value) must be of type Countable|array, null given (View: /var/www/clients/client20/web149/web/resources/views/admin/layouts/partials/sidebar.blade.php)

### Rilis Versi OpenSID

Rilis Umum

### Versi OpenSID

v2401.00

### Tema Yang Digunakan

natra v22.11

**Comment by andifahruddinakas** [comment]
pak @nurlia-astika, dari errornya merupakan stritc count dari php 8.x. Silahkan gunakan php 7.4, untuk rilis umum belum mendukung php 8.x
