### ISSUE TITLE
Bug: Format Center Text pada artikel statis tidak tersimpan

### ISSUE THREAD

**Issue by fhyan** [OpenSID/OpenSID#761]
saya edit visi dan misi, sudah saya seting rata tengah tapi pas di simpan hasilnya jadi rata kiri?

**Comment by MUHAMMADRANGSEL** [comment]
Ya memang setelah adanya perubahan, banyak fungsi yg seharusnya ada seperti sebelum adanya perubahan hilang. Dan ini perlu jadi perhatian programer

**Comment by eddieridwan** [comment]
Sebaiknya tunggu penyelesaian Memodernkan Tampilan Modul Admin.

**Comment by egodasa** [comment]
@eddieridwan Sepertinya bug ini terjadi karena method `$this->security->xss_clean()` pada https://github.com/OpenSID/OpenSID/blob/master/donjo-app/models/First_artikel_m.php#L279. Style pada post terhapus karena method tersebut.

**Comment by eddieridwan** [comment]
Sepertinya, untuk tetap mencegah serangan xss dan tetap menggunakan tinymce, pilihannya adalah:
1. mengganti xss_clean dengan library pembersihan html lain, seperti http://www.bioinformatics.org/phplabware/internal_utilities/htmLawed/ (misalnya lihat pembahasan di http://archive.tinymce.com/forum/viewtopic.php?id=28315), atau
2. extend `system/core/Security.php` untuk menghilangkan tag `style` dari `$naughty_tags` di method `_sanitize_naughty_html($matches)`. (caranya lihat https://www.codeigniter.com/userguide3/general/core_classes.html).

**Comment by egodasa** [comment]
@eddieridwan Kalau pakai opsi kedua, berarti kemampuan xss_clean akan berkurang Mas. Kalau misalkan pakai library, berarti xss_clean disemua file harus diganti dengan yang library penulisannya. Begitukah Mas?

Yang sudah Saya coba:
1. Extend class security dan mengganti proses xss_clean dengan proses htmLawed, hasilnya bug ini memang hilang. Tapi, dihalaman artikel menu sebelah kiri jadi hilang.
1. Extend class security dan membuat method baru bernama `html_xss_clean` dan menggunakannya di view. Dan hasilnya memang jalan. Tapi hal ini berarti Saya perlu mengganti xss_clean dihalaman lain dengan yang baru.
1. Dan terakhir, Saya mengganti proses method `_sanitize_naughty_html` dengan proses htmlLawed, dan hasilnya sama seperti yang pertama.

Bagaimana Mas?

**Comment by eddieridwan** [comment]
Saya pikir cara yg paling mudah kita kendalikan adalah:
- extend `system/core/Security.php` khusus untuk menggantikan  method `_sanitize_naughty_html($matches)`. Di method ubahan kita hilangkan tag `style` dari `$naughty_tags`, sehingga tag `style` tidak difilter.

**Comment by egodasa** [comment]
@eddieridwan Sepertinya variabel `$evil_attributes` yang lebih tepatnya diganti Mas.

`$naughty_tags` berarti melarang semua `<$naughty_tags>` dan perihal ini memang cukup berbahaya jika kita edit. Jika `style` dihilangkan, berarti di artikel pengguna bisa mengetik 
```
<style>
.artikel{
display: none;
}
</style>
```
Dan style tersebut bakal berpengaruh dihalaman artikel tersebut.

Sedangkan di artikel sendiri, style terletak secara inline yaitu `<p style='text-align: center;>'` dan style seperti ini yang terhapus oleh method `xss_clean()`.

Jadi sebaiknya, variabel yang kita hilangkan string style adalah variabel `$evil_attributes`.

**Comment by eddieridwan** [comment]
@egodasa 👍 

Sudah dicommit ke master melalui PR #1647
