### ISSUE TITLE
Data rw tidak muncul saat di cetak atau di unduh

### ISSUE THREAD

**Issue by mranca** [OpenSID/OpenSID#7612]
### Jelaskan error yg dialami

Saat cetak wilayah administratif dusun untuk nama rw dan nik rw tidak tampil

### Cara untuk mereplikasi errornya

Masuk di halaman admin  > wilayah desa > cetak atau unduh 

### Hasil yg diharapkan

Di usahakan agar nama pada kolom rw muncul nama dan nik nya

### Tangkapan layar dan log error

![snapshot_tongketongke desa id_1705406185959](https://github.com/OpenSID/OpenSID/assets/76085245/2c2eca99-a8ad-40a3-84d6-28669bd43608)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

V2401.01

### Tema Yang Digunakan

.

### Informasi tambahan

.

**Comment by andifahruddinakas** [comment]
pak @mranca, bisa cek https://berputar.opendesa.id/ atau https://beta.opendesa.id/ sbb
<img width="333" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/f8c86743-6cfc-49ca-9241-387aa6b6d804">
<img width="383" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/89d39329-38cf-4495-b2bb-c6fe92f3d681">

Bisa dibuka kembali issue ini jika masih terkendala.
