### ISSUE TITLE
Bug/error: calon pemilih

### ISSUE THREAD

**Issue by afri18** [OpenSID/OpenSID#7613]
### Jelaskan error yg dialami

klik modul calon pemilih eror 404

### Cara untuk mereplikasi errornya

kalau clear dihapus bisa

### Hasil yg diharapkan

tidak ada /clear

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/6611881/fbdf6b8f-c3a4-4015-80f8-ab9d44b9d8aa)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2401.0.2

### Tema Yang Digunakan

denatra

### Informasi tambahan

seharusnya langsung tampil

**Comment by andifahruddinakas** [comment]
pak @afri18, di https://berputar.opendesa.id/ dan https://beta.opendesa.id/ tidak ditemukan masalah ini.

<img width="412" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/7d0aa1d9-bdd8-49a5-a511-a107e0f67253">

Bisa lakukan migrasi ulang, krn perubahan tsb ada di versi 2401.0.0, migrasi tidak lengkap di versi tsb. Atau paksa melakukan migrasi dengan menghapus data pada tabel migrasi.
<img width="448" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/a9fa3f8a-7aff-43ff-8b8e-2c65fde4aa51">
<img width="425" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/c29643cb-33b1-483b-b815-c9df41dfc4c4">

Pastikan struktur database sudah sama.

**Comment by afri18** [comment]
> pak @afri18, di https://berputar.opendesa.id/ dan https://beta.opendesa.id/ tidak ditemukan masalah ini.
> 
> <img alt="image" width="412" src="https://private-user-images.githubusercontent.com/57283157/297230653-7d0aa1d9-bdd8-49a5-a511-a107e0f67253.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0NTYyMDcsIm5iZiI6MTcwNTQ1NTkwNywicGF0aCI6Ii81NzI4MzE1Ny8yOTcyMzA2NTMtN2QwYWExZDktYmRkOC00OWE1LWE1MTEtYTEwN2UwZjY3MjUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDAxNDUwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY4ZjA3NWU4MjlkNzFkZjMxYmYxZWQ0YjUxMDg2YzkwZGIzMzg1ZDg4NWVhZmI0YjZkZmRmNzhiYjQ0MzE5YmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ksBY7Brn9B1cos__RNb3YwD0akpKTGnWKyhQe_NrVG0">
> Bisa lakukan migrasi ulang, krn perubahan tsb ada di versi 2401.0.0, migrasi tidak lengkap di versi tsb. Atau paksa melakukan migrasi dengan menghapus data pada tabel migrasi. <img alt="image" width="448" src="https://private-user-images.githubusercontent.com/57283157/297231096-a9fa3f8a-7aff-43ff-8b8e-2c65fde4aa51.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0NTYyMDcsIm5iZiI6MTcwNTQ1NTkwNywicGF0aCI6Ii81NzI4MzE1Ny8yOTcyMzEwOTYtYTlmYTNmOGEtN2FmZi00M2ZmLThiOGUtMmM2NWZkZTRhYTUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDAxNDUwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYzMmM0NDQ5NDJlNzczY2U0MGZhNGVlYzAxYTVjMWU2MmRmMjlmOGY4MmZmNzY0M2FlNDg5YmU5YjhkNzdkYzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fR2Ki9UDuslVAuuFdu_SH7KBJ0nHQ696nL4H_OBUfKI"> <img alt="image" width="425" src="https://private-user-images.githubusercontent.com/57283157/297231168-c29643cb-33b1-483b-b815-c9df41dfc4c4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0NTYyMDcsIm5iZiI6MTcwNTQ1NTkwNywicGF0aCI6Ii81NzI4MzE1Ny8yOTcyMzExNjgtYzI5NjQzY2ItMzNiMS00ODNiLWI4MTUtYzlkZjQxZGZjNGM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDAxNDUwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2ZWY2YjRjNjFjODM2YTM2MmU0ZTdkNDBiZWFmYzIzOGY0NmYzOGQ3YjJkNTU0YzRkY2I0MzFhMTBkMjY0MDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PapfUICnlXTuqpnyanrv-ywVc5atyxR67YHceQIvUJM">
> 
> Pastikan struktur database sudah sama.

caba saya periksa

**Comment by afri18** [comment]
> pak @afri18, di https://berputar.opendesa.id/ dan https://beta.opendesa.id/ tidak ditemukan masalah ini.
> 
> <img alt="image" width="412" src="https://private-user-images.githubusercontent.com/57283157/297230653-7d0aa1d9-bdd8-49a5-a511-a107e0f67253.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0NTcwOTMsIm5iZiI6MTcwNTQ1Njc5MywicGF0aCI6Ii81NzI4MzE1Ny8yOTcyMzA2NTMtN2QwYWExZDktYmRkOC00OWE1LWE1MTEtYTEwN2UwZjY3MjUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDAxNTk1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzYTM3MzU1Yzg4YmQzZDEwYzQwNDM1OGQ5NGM2Mjc0NTZkZGY0NzIwZWQ5Yjg2YmZhZDg5ODhjNjUyOWU1ODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2KvtGKNwL8cbj4yvnPmLKLY9zgt3F8anI7cLwhklnKk">
> Bisa lakukan migrasi ulang, krn perubahan tsb ada di versi 2401.0.0, migrasi tidak lengkap di versi tsb. Atau paksa melakukan migrasi dengan menghapus data pada tabel migrasi. <img alt="image" width="448" src="https://private-user-images.githubusercontent.com/57283157/297231096-a9fa3f8a-7aff-43ff-8b8e-2c65fde4aa51.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0NTcwOTMsIm5iZiI6MTcwNTQ1Njc5MywicGF0aCI6Ii81NzI4MzE1Ny8yOTcyMzEwOTYtYTlmYTNmOGEtN2FmZi00M2ZmLThiOGUtMmM2NWZkZTRhYTUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDAxNTk1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjZTIwMWI1NzMxZTUyYzBjYWMxZTU5ZmU2YmQ1YzlhZDU0ZDg1YmY4NGM5MjMwZWQwMjc2ZWQ5YjgzMjMzYTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JKCPNPxtdCTlgW7JWx1bEVb2btRVX71Rup2fBv3HsoE"> <img alt="image" width="425" src="https://private-user-images.githubusercontent.com/57283157/297231168-c29643cb-33b1-483b-b815-c9df41dfc4c4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0NTcwOTMsIm5iZiI6MTcwNTQ1Njc5MywicGF0aCI6Ii81NzI4MzE1Ny8yOTcyMzExNjgtYzI5NjQzY2ItMzNiMS00ODNiLWI4MTUtYzlkZjQxZGZjNGM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDAxNTk1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4ZjNhOWIyNTAyMzYzMzFhZTIzZDY5M2YxNmE4YTFjODI3NGQ5N2I0NzA0YWZhMzgzZDUyZGE1Zjc5MzUyZTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zusXMyUJAYBY834BK-mTfCCP4UXMNGxvq7-JEG96-6k">
> 
> Pastikan struktur database sudah sama.

okeh permasalahan karna migrasi di 2401.0.0 kurang sempurna, setelah melaksanakan instruksi terselesaikan
sayangnya di CPANEL gagal melakukan itu, padahal database yg saya pake di offline hasil backupan cpanel

**Comment by afri18** [comment]
> pak @afri18, di https://berputar.opendesa.id/ dan https://beta.opendesa.id/ tidak ditemukan masalah ini.
> 
> <img alt="image" width="412" src="https://private-user-images.githubusercontent.com/57283157/297230653-7d0aa1d9-bdd8-49a5-a511-a107e0f67253.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0NTcwOTMsIm5iZiI6MTcwNTQ1Njc5MywicGF0aCI6Ii81NzI4MzE1Ny8yOTcyMzA2NTMtN2QwYWExZDktYmRkOC00OWE1LWE1MTEtYTEwN2UwZjY3MjUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDAxNTk1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzYTM3MzU1Yzg4YmQzZDEwYzQwNDM1OGQ5NGM2Mjc0NTZkZGY0NzIwZWQ5Yjg2YmZhZDg5ODhjNjUyOWU1ODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2KvtGKNwL8cbj4yvnPmLKLY9zgt3F8anI7cLwhklnKk">
> Bisa lakukan migrasi ulang, krn perubahan tsb ada di versi 2401.0.0, migrasi tidak lengkap di versi tsb. Atau paksa melakukan migrasi dengan menghapus data pada tabel migrasi. <img alt="image" width="448" src="https://private-user-images.githubusercontent.com/57283157/297231096-a9fa3f8a-7aff-43ff-8b8e-2c65fde4aa51.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0NTcwOTMsIm5iZiI6MTcwNTQ1Njc5MywicGF0aCI6Ii81NzI4MzE1Ny8yOTcyMzEwOTYtYTlmYTNmOGEtN2FmZi00M2ZmLThiOGUtMmM2NWZkZTRhYTUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDAxNTk1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjZTIwMWI1NzMxZTUyYzBjYWMxZTU5ZmU2YmQ1YzlhZDU0ZDg1YmY4NGM5MjMwZWQwMjc2ZWQ5YjgzMjMzYTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JKCPNPxtdCTlgW7JWx1bEVb2btRVX71Rup2fBv3HsoE"> <img alt="image" width="425" src="https://private-user-images.githubusercontent.com/57283157/297231168-c29643cb-33b1-483b-b815-c9df41dfc4c4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0NTcwOTMsIm5iZiI6MTcwNTQ1Njc5MywicGF0aCI6Ii81NzI4MzE1Ny8yOTcyMzExNjgtYzI5NjQzY2ItMzNiMS00ODNiLWI4MTUtYzlkZjQxZGZjNGM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDAxNTk1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4ZjNhOWIyNTAyMzYzMzFhZTIzZDY5M2YxNmE4YTFjODI3NGQ5N2I0NzA0YWZhMzgzZDUyZGE1Zjc5MzUyZTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zusXMyUJAYBY834BK-mTfCCP4UXMNGxvq7-JEG96-6k">
> 
> Pastikan struktur database sudah sama.

di cpanel gagal om 
[Uploading log-2024-01-17.zip…]()

![image](https://github.com/OpenSID/OpenSID/assets/6611881/a601215e-66fe-4ecb-a090-6c430c50a96d)

**Comment by afri18** [comment]
> pak @afri18, di https://berputar.opendesa.id/ dan https://beta.opendesa.id/ tidak ditemukan masalah ini.
> 
> <img alt="image" width="412" src="https://private-user-images.githubusercontent.com/57283157/297230653-7d0aa1d9-bdd8-49a5-a511-a107e0f67253.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0NjM4MDQsIm5iZiI6MTcwNTQ2MzUwNCwicGF0aCI6Ii81NzI4MzE1Ny8yOTcyMzA2NTMtN2QwYWExZDktYmRkOC00OWE1LWE1MTEtYTEwN2UwZjY3MjUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDAzNTE0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlOTE2ZWI5NjQxYWNkNDk2OGEwZjM4NGM1MjM1YWUzZTA4MDViYmVmYWM5ZGUxZjM5MjM0Nzc2N2Q0YWM1NjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dEMdLZpHQ5Jbg6p73jc07oEQVuM1NeVom_FSVi--vs8">
> Bisa lakukan migrasi ulang, krn perubahan tsb ada di versi 2401.0.0, migrasi tidak lengkap di versi tsb. Atau paksa melakukan migrasi dengan menghapus data pada tabel migrasi. <img alt="image" width="448" src="https://private-user-images.githubusercontent.com/57283157/297231096-a9fa3f8a-7aff-43ff-8b8e-2c65fde4aa51.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0NjM4MDQsIm5iZiI6MTcwNTQ2MzUwNCwicGF0aCI6Ii81NzI4MzE1Ny8yOTcyMzEwOTYtYTlmYTNmOGEtN2FmZi00M2ZmLThiOGUtMmM2NWZkZTRhYTUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDAzNTE0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0YzBkNzMyNjQ1MWUyOGVmZWFiMTkwNmU4YmUzZTRjYjU3NDE2ZGU0ZTY1NmZjZWMwM2RmNDk4ZjRiM2JkYjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EzpcqJl8BSIDhe-9G_Stzl2xeJA_xUAJjaJRZQlauaM"> <img alt="image" width="425" src="https://private-user-images.githubusercontent.com/57283157/297231168-c29643cb-33b1-483b-b815-c9df41dfc4c4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0NjM4MDQsIm5iZiI6MTcwNTQ2MzUwNCwicGF0aCI6Ii81NzI4MzE1Ny8yOTcyMzExNjgtYzI5NjQzY2ItMzNiMS00ODNiLWI4MTUtYzlkZjQxZGZjNGM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDAzNTE0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRkNzYxNWJhNTk2MWYxN2E4NDlmMTIzMGEzMDdhM2ExMmFiZjVhZWQ0ZTk5ZGMwYWYwZmQyZDQ5ZmQ2ZWM4MDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KNQXhaZdlrHY5IGbIEtXS1EEaKaE6b-lSIJ_SDZNE8c">
> 
> Pastikan struktur database sudah sama.

Terimakasih bung @andifahruddinakas , ternyata di CPANEL > HTMPublic ada file tidak dikenal, setalah saya hapus aplikasi OPENSID berjalan sesuai dengan https://berputar.opendesa.id/
Sepertinya v 2401.0.2 lebih stabil, walau saya belum uji persyuratannya, baru yg berkaitan dengan datadesa
