### ISSUE TITLE
Bug/error: pemberitahuan

### ISSUE THREAD

**Issue by afri18** [OpenSID/OpenSID#7614]
### Jelaskan error yg dialami

stiap pilih/klik di modul surat selalu ada pemberitahuan migrasi berhasil

### Cara untuk mereplikasi errornya

sebaiknya pemberitahuan migrasi berhasil hanya ada saat klita klik migrasi dan diberitahukan hasil berhasil atau gagal

### Hasil yg diharapkan

tidak ada pemberitahuan migrasi berhasil saat klik/pilih modul surat

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/6611881/0f0b333a-e53a-4a91-a9f4-8599060d96d8)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2401.0.2

### Tema Yang Digunakan

denatra

### Informasi tambahan

sebaiknya jangan ada pemberitahuna migrasi berhasil, bikin kaget, karna tidak klik migrasi

**Comment by andifahruddinakas** [comment]
pak @afri18, sama halnya dengan issue sebelumnya, di https://berputar.opendesa.id, https://beta.opendesa.id maupun di local tidak ditemukan masalah tsb. sepertinya masalah struktur database. bisa cek tabel migrasi.
<img width="210" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/d93cf361-2b27-4c75-9f13-58ea0b1ce036">
