### ISSUE TITLE
saat cetak surat kelahiran dan surat kematian tidak muncul apa-apa pada file rtf (kosong)

### ISSUE THREAD

**Issue by ElAndea** [OpenSID/OpenSID#7615]
### Jelaskan error yg dialami

saat cetak surat kelahiran dan kematian hasil file rtf kosong

### Cara untuk mereplikasi errornya

cetak surat kelahiran dan kematian

### Hasil yg diharapkan

ada tampilan isi pada file rtf

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/37187652/59feb42f-30dc-46cc-a9ed-54b432ac2b5a)

### Rilis Versi OpenSID

Rilis Umum

### Versi OpenSID

24.01

### Tema Yang Digunakan

tema silir

**Comment by andifahruddinakas** [comment]
pak @ElAndea, sy coba di https://demosid.opendesa.id/ tdk bermasalah. 
<img width="516" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/164670f7-d16b-499c-919a-6a42da03a0ea">
bisa cek jg pembahasan https://github.com/OpenSID/OpenSID/issues/7552
