### ISSUE TITLE
Permintaan fitur: Posyandu

### ISSUE THREAD

**Issue by afri18** [OpenSID/OpenSID#7616]
### Apa kekurangan yg ingin diatasi?

sepertinya janggal bila modul STUNTING tapi isinya sebenarnya kegiatan POSYANDU

### Jelaskan solusi yg diinginkan

Ganti nama modul STUNTING menjadi POSYANDU, karna stunting adalah bagian kegiatan posyandu
![image](https://github.com/OpenSID/OpenSID/assets/6611881/c850e07f-26e3-42c5-99c7-360e2845611c)

### Apakah ada alternatif lain

Agar lebih akrab denga KADER POSYANDU

### Untuk versi OpenSID mana

2401.0.2

### Informasi tambahan

Stunting adalah bagian kegiatan dari POSYANDU

**Comment by siayi** [comment]
Kalo saya disesuaikan di Pengaturan Modulnya.

![](https://i.imgur.com/hcEDgLE.gif)

**Comment by andifahruddinakas** [comment]
> Kalo saya disesuaikan di Pengaturan Modulnya.
> 
> ![](https://camo.githubusercontent.com/01ed2d1af25f552705b24cf949782dae993f367de072053b8e911835b9c0a0c2/68747470733a2f2f692e696d6775722e636f6d2f68634544674c452e676966) [ ![68747470733a2f2f692e696d6775722e636f6d2f68634544674c452e676966](https://camo.githubusercontent.com/01ed2d1af25f552705b24cf949782dae993f367de072053b8e911835b9c0a0c2/68747470733a2f2f692e696d6775722e636f6d2f68634544674c452e676966) ](https://camo.githubusercontent.com/01ed2d1af25f552705b24cf949782dae993f367de072053b8e911835b9c0a0c2/68747470733a2f2f692e696d6775722e636f6d2f68634544674c452e676966) [ ](https://camo.githubusercontent.com/01ed2d1af25f552705b24cf949782dae993f367de072053b8e911835b9c0a0c2/68747470733a2f2f692e696d6775722e636f6d2f68634544674c452e676966)

pak @afri18, bisa dengan cara ini
