### ISSUE TITLE
Bug/error: Rekapitulasi

### ISSUE THREAD

**Issue by afri18** [OpenSID/OpenSID#7617]
### Jelaskan error yg dialami

Rekapitulasi modul stunting/posyandu sebaiknya tampilan awal adalah bulan berjalan dan tahun berjalan dan perbulan bukan triwulan, karna kegiatan posyandu itu ada setiap bulan

### Cara untuk mereplikasi errornya

Tampilkan data sesuai bulan berjalan dan Tahun berjalan

### Hasil yg diharapkan

Saat Klik Rekapitulasi Dapat menampilkan langsung data bulan dan tahun berjalan, kecuali di pilih

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/6611881/91fbbe20-9eae-450d-9b88-037f6e5351c1)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2401.0.2

### Tema Yang Digunakan

denatra

### Informasi tambahan

Nantinya bisa jadi acuan laporan posyandu perbulan

**Comment by andifahruddinakas** [comment]
SOLUSI : 

- [ ] filter yang ditampilkan defaultnya sesuai dengan bulan dan tahun yang saat ini kalu belum ada filter yg aktif.

**Comment by pandigresik** [comment]
Kalau dibuat perbulan berarti bukan data rekapitulasi, karena di pemantauan sudah ditampilkan berdasarkan bulan juga

**Comment by pandigresik** [comment]
![image](https://github.com/user-attachments/assets/af8a2a84-4863-41b4-af0d-1736527a094a)

di pemantauan sudah bisa filter perbulan dan eksport ke excel juga

**Comment by pandigresik** [comment]
Lebih baik masuk fitur, karena sebelumnya ada PR https://github.com/OpenSID/OpenSID/issues/8771 masuk sebagai fitur

**Comment by andifahruddinakas** [comment]
> Lebih baik masuk fitur, karena sebelumnya ada PR #8771 masuk sebagai fitur

Ok.

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/4339

**Comment by afri18** [comment]
[opensid-2025-01-03.log](https://github.com/user-attachments/files/18298465/opensid-2025-01-03.log)
