### ISSUE TITLE
Bug: Jumlah salah di Widget Statistik Penduduk

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#762]
widget statistik hanya memunculkan data 1 laki 1 perempuan saja

![27021707_10210154540051746_8316555516714273916_o](https://user-images.githubusercontent.com/35319600/35491694-b1185928-04da-11e8-80ae-7e886a398f3b.jpg)

**Comment by MUHAMMADRANGSEL** [comment]
Betul ini perlu diperbaiki

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
