### ISSUE TITLE
Bug/error: Daftar Persyaratan

### ISSUE THREAD

**Issue by afri18** [OpenSID/OpenSID#7620]
### Jelaskan error yg dialami

Saat klik modul daftar persyaratan ada peringatan

### Cara untuk mereplikasi errornya

seharusnya muncul daftar persyaratan

### Hasil yg diharapkan

menampilkan daftar persyaratan walau pun masih kosong

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/6611881/ecc1c992-391a-4f29-96ec-a0b6a4cd1837)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2401.0.2

### Tema Yang Digunakan

denatra

### Informasi tambahan

di https://berputar.opendesa.id/surat_mohon 
sama

**Comment by andifahruddinakas** [comment]
pak @afri18, bisa cek di https://beta.opendesa.id/ masalah tsb sudah teratasi. krn terkait penghapusan rtf.

**Comment by afri18** [comment]
> pak @afri18, bisa cek di https://beta.opendesa.id/ masalah tsb sudah teratasi. krn terkait penghapusan rtf.

siap ....
