### ISSUE TITLE
Link Sosial Media OpenDesa

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#7621]
Terjadi beberapa perubahan pada media sosial OpenDesa, sehingga pada aplikasi juga harus ikut diubah.
![image](https://github.com/OpenSID/OpenSID/assets/57283157/953612bb-86e9-4b09-b921-ed84affbd4bc)

Perbaikan : 
- [ ] Point 3, untuk Facebook ganti url `https://www.facebook.com/groups/komunitasopendesa`
- [ ] Point 9, "Forum diskusi teknis pengembangan OpenSID" dengan url `https://t.me/+mi5ydVtVfmw0YWY1`

**Comment by agungsugiarto** [comment]
Point 3 tidak ada yang perlu dirubah karena sudah mengarah ke `https://www.facebook.com/groups/komunitasopendesa`
