### ISSUE TITLE
tidak bisa upload foto selalu C:/fakepath dan tidak selalu ada gambar

### ISSUE THREAD

**Issue by muhanifrafi** [OpenSID/OpenSID#7623]
### Jelaskan error yg dialami

![erroraplikasi](https://github.com/OpenSID/OpenSID/assets/82740977/4416fd93-0661-495a-bdd1-76463f71499a)

sorry mas maaf mengganggu saya menggunakan opensid 2308.0.0 saya sudah coba dihosting pake aws ec2 kemudian sudah jalan namun memiliki beberapa masalah yaitu tidak bisa upload gambar artikel jadi gambar tidak bisa di upload di website 

### Cara untuk mereplikasi errornya

coba untuk melakukan upload gambar artikel

### Hasil yg diharapkan

solusi dari permasalahan

### Tangkapan layar dan log error

![erroraplikasi](https://github.com/OpenSID/OpenSID/assets/82740977/a39eb197-b3ab-4307-8085-639971b5cfbd)

### Rilis Versi OpenSID

Rilis Umum

### Versi OpenSID

2308.0.0

**Comment by andifahruddinakas** [comment]
pak @muhanifrafi, pastikan folder artikel sudah ada.
<img width="314" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/6edac4d2-6816-4bf1-b59a-ca8ca51e9077">
