### ISSUE TITLE
Bug/error: Tambah Peserta Bantuan

### ISSUE THREAD

**Issue by afri18** [OpenSID/OpenSID#7630]
### Jelaskan error yg dialami

saat menambah peserta setelah di pilih menampilkan halaman kosong

### Cara untuk mereplikasi errornya

menampilkan data bantuan

### Hasil yg diharapkan

bisa menampilkan data dan memberi nomor pesrta lalu simpan

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/6611881/8e4d6e91-5797-40ae-b669-368b6b1eb8ea)
[tambah bantuan.zip](https://github.com/OpenSID/OpenSID/files/13971482/tambah.bantuan.zip)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2401.0.2

### Tema Yang Digunakan

denatra

### Informasi tambahan

seharusnya bisa menambahkan baik Kepala Keluarga, istri atau anak (Keluarga Inti)

**Comment by andifahruddinakas** [comment]
untuk kasus 404 bisa di komentar pada issue https://github.com/OpenSID/OpenSID/issues/7632
