### ISSUE TITLE
Bug/error: isian penduduk luar desa selain data pemohon utama hasilnya kosong atau -

### ISSUE THREAD

**Issue by khiar-rara** [OpenSID/OpenSID#7631]
### Jelaskan error yg dialami

Isian penduduk luar desa selain data pemohon utama hasilnya kosong atau -

### Cara untuk mereplikasi errornya

1. Cetak surat keterangan nikah
2. Isi data calon pasangan dari penduduk luar desa
3. Lanjutkan isian lainnya

### Hasil yg diharapkan

Isian data penduduk luar desa baik di data pemohon utama dan penduduk luar desa di data pendukung/berikutnya/lainnya, terisi sesuai dengan data yang diinput

### Tangkapan layar dan log error

![Screenshot_20240118_100809](https://github.com/OpenSID/OpenSID/assets/74307159/3d004b54-8390-4bd2-be72-3ecb201f2d97)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

V2401.0.2

### Tema Yang Digunakan

Esensi

### Informasi tambahan

Tidak ada

**Comment by Sukoharjo3** [comment]
up

**Comment by agungsugiarto** [comment]
mas @andifahruddinakas duplikat issue dengan https://github.com/OpenSID/premium/issues/3420

**Comment by andifahruddinakas** [comment]
> mas @andifahruddinakas duplikat issue dengan [OpenSID/premium#3420](https://github.com/OpenSID/premium/issues/3420)

Beda mas, coba cek issue ini terkait surat nikah.

**Comment by andifahruddinakas** [comment]
<img width="530" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/037d88f0-49a9-4ba4-ab4c-4b1e275f349a">

<img width="334" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/39ebe33e-b392-4ce1-9ac6-2f4a5a95fd56">

**Comment by Sukoharjo3** [comment]
> mas @andifahruddinakas duplikat issue dengan https://github.com/OpenSID/premium/issues/3420

ini issue yg beda pak, karna isian form nikah banyak sekali jd banyak issue
