### ISSUE TITLE
Terkait router 404

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#7632]
Issue terkait router : 
- [x] tambah anggota keluarga (https://github.com/OpenSID/OpenSID/issues/7627)
- [x] api tte
- [x] program bantuan (https://berputar.opendesa.id/peserta_bantuan/form/2) (https://github.com/OpenSID/OpenSID/issues/7630)
- [x] keluarga > pindah kolektif (https://berputar.opendesa.id/keluarga/proses_pindah)
- [x] pecah semua kk
![image](https://github.com/OpenSID/OpenSID/assets/57283157/25f3f2ca-ac53-4ac3-abcf-7b6fde14385f)

- [x] Surat favorit

**Comment by afri18** [comment]
kalau bisa berikan solusi cepat, ini terkait dengan laporan penduduk dan log penduduk nantinya

**Comment by andifahruddinakas** [comment]
> kalau bisa berikan solusi cepat, ini terkait dengan laporan penduduk dan log penduduk nantinya

akan di infokan ke forum dan diteruskan ke telegram

**Comment by davidyusufbumiratu** [comment]
https://berputar.opendesa.id/surat  jika salah satu surat dipilih sebagai Favorit maka akan error seperti gbr berikut
![Screenshot_10](https://github.com/OpenSID/OpenSID/assets/47467809/5a5b08a3-c052-40c9-924f-062f1b5fc9f6)

https://berputar.opendesa.id/surat/favorit/194/0
![Screenshot_12](https://github.com/OpenSID/OpenSID/assets/47467809/06c090c3-4250-4eeb-bd55-bf7478bc3d42)

**Comment by andifahruddinakas** [comment]
> https://berputar.opendesa.id/surat jika salah satu surat dipilih sebagai Favorit maka akan error seperti gbr berikut ![Screenshot_10](https://private-user-images.githubusercontent.com/47467809/297628150-5a5b08a3-c052-40c9-924f-062f1b5fc9f6.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1NjYyOTIsIm5iZiI6MTcwNTU2NTk5MiwicGF0aCI6Ii80NzQ2NzgwOS8yOTc2MjgxNTAtNWE1YjA4YTMtYzA1Mi00MGM5LTkyNGYtMDYyZjFiNWZjOWY2LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE4VDA4MTk1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY4NDNlMDk2N2Q1NTFkYTFkZDZiZTQ4ZmRlNTRlODE4MmZlMTUxN2U0M2NlMTBhNzFkM2FjMDY0MDI2OWE4NjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8Ahhe3ajGM-Gr176d-SkMvlPI8loo2GfkJURaNHQYG0)
> 
> https://berputar.opendesa.id/surat/favorit/194/0 ![Screenshot_12](https://private-user-images.githubusercontent.com/47467809/297628188-06c090c3-4250-4eeb-bd55-bf7478bc3d42.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1NjYyOTIsIm5iZiI6MTcwNTU2NTk5MiwicGF0aCI6Ii80NzQ2NzgwOS8yOTc2MjgxODgtMDZjMDkwYzMtNDI1MC00ZWViLWJkNTUtYmY3NDc4YmMzZDQyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE4VDA4MTk1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4Y2MxOTRmNGU3YTdlZDBjNzk0ZDM5ODdmMjBiMjc4YmVlYTc1NWY0OWJlY2IxNzdhNTg0MDgxOWViOTRmZTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4rfIC5sfLutGnsoZmoWVcKm1n-PDedkZDy_j1zgMdMI)

https://forum.opendesa.id/d/317-masalah-terkait-rilis-v240102

**Comment by davidyusufbumiratu** [comment]
hasilnya di https://berputar.opendesa.id/surat/favorit/215/0 masih sama bang, ketika pilih Favorit errornya tetap 
![Screenshot_15](https://github.com/OpenSID/OpenSID/assets/47467809/3216d697-d723-458b-a5ba-4cb22946b526)

**Comment by andifahruddinakas** [comment]
- [ ] update informasi publik
<img width="475" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/8b52e33e-e265-4c27-a590-bf95c7d28ba6">

**Comment by andifahruddinakas** [comment]
- [x] Program Bantuan (Paginasi) (https://github.com/OpenSID/OpenSID/issues/7657)
- [x] Program Bantuan Peserta (Paginasi)
<img width="254" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/acb5a8c3-4a30-4212-80b8-1f27a231db03">

- [x] Artikel (Paginasi)
<img width="255" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/8afb0fbe-b590-44ac-9245-b96e177c4035">

- [x] Penduduk Log (Paginasi)
<img width="128" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/63f2e93a-8c7f-4f69-928f-fd06065b2ace">

- [x] Pendataan Penerima Vaksin Covid-19 > Laporan Penduduk (Paginasi)
<img width="378" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/c07c0284-ee38-447e-8784-8146cbb0b67d">

- [x] Daftar Persil dan Daftar C-DESA (Paginasi)
<img width="413" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/78a4f8fc-938c-4866-97a8-6fc391eab175">

- [x] Surat favorit

**Comment by andifahruddinakas** [comment]
- [x] https://github.com/OpenSID/OpenSID/issues/7670
- [x] https://berputar.opendesa.id/identitas_desa/index/kosongkan/1
![image](https://github.com/OpenSID/OpenSID/assets/1853475/82d09776-0d54-405c-ad74-d8d50c3e24cb)
