### ISSUE TITLE
Antisipasi nama desa yang panjang

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#7634]
Jika terdapat nama desa yang panjang, contoh : "Tanjuang Haro Sikabu-Kabu Pondok Panjang" maka pada beberapa hasil cetak akan membuat baris baru.

Issue ini dicoba untuk surat keterangan nikah.

**Comment by Sukoharjo3** [comment]
perlu kolom yg lebih lebar

**Comment by yogiperdana** [comment]
saay coba cetak surat nikah masalahnya hanya di bagian penandatangan apakah benar demikian?
![image](https://github.com/OpenSID/OpenSID/assets/14155050/a5b55942-3b9e-4643-b713-06f7e54e5554)

**Comment by yogiperdana** [comment]
Saya coba di surat biasa juga sama pak akan menjadi 2 baris. Jadi tidak hanya berlaku untuk lampiran surat nikah

Apakah hasil seperti ini yang diharapkan?
[5fe4e80c-6d20-48bf-8bf6-2867f84d6b4d.pdf](https://github.com/OpenSID/OpenSID/files/13989603/5fe4e80c-6d20-48bf-8bf6-2867f84d6b4d.pdf)

**Comment by yogiperdana** [comment]
Untuk issue ini kapan bisa diskusi terkait solusi yang diinginkan mas @andifahruddinakas

**Comment by yogiperdana** [comment]
Cek
- [ ] Sebutan desa yang panjang (gampong)
- [ ] Atas nama penandatangan dengan nama jabatan yang panjang (sekretaris)
