### ISSUE TITLE
Permintaan fitur: Tambahkan kondisi agar dapat memilih tab (bagian) dalam memilih sesuai dengan kondisi

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#7635]
### Apa kekurangan yg ingin diatasi?

Saat ini kode isian berdisi sendiri dimana tidak dapat menjadi parameter untuk menampilkan kode isian tertantu , misalkan pada pilihan form tertentu dapat di isi atau tidak diisi sesuai dengan kodisi , misalkan pada surat Nikah, terpadat pilihan Jika pria, terangkan jejaka, duda atau beristri : setiap pilihan menentukan form apa yang perlu diisi  kondisi ini untuk mengurangi jumlah form isian dan berkaitan pada lampiran. 

### Jelaskan solusi yg diinginkan

1. Tambahkan fungsi "kaitkan" 
<img width="499" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/9da92932-9454-431a-9ea8-bf518acf97cb">
2. Akan muncul pop-up seperti berikut ini : 
<img width="306" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/1383e4de-40ac-43e2-8686-738c912fccda">
akan ada 2 isian yang perlu di isi pertama tentukan value yang akan di jadikan parameter 
yang ke 2 adalah form isian yang akan di kaitkan , kondisi di poin ini dapat ditambah dinamis sesuai value yang akan dikaitkan jadi bisa 2 kondisi. Jika ini diterapkan maka value yang sudah dibuat kondisi tidak dapat ditambahkan kondisi lain lagi.

**Comment by Sukoharjo3** [comment]
fitur yg sangat ditunggu
