### ISSUE TITLE
Informasi pemesanan

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#7639]
Jika di redirect ke halaman peringatan, tetap tampilkan informasi pemesanan yang ada.
Saat ini : 
<img width="682" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/6112868c-e4c0-4603-b714-f18256e9315d">

Seharusnya : 
<img width="671" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/d81975b6-9ea3-447b-937a-5fc7437c4ccb">

**Comment by andifahruddinakas** [comment]
@FirlianiF, tambahkan yang masih kurang.

**Comment by FirlianiF** [comment]
Sudah sesuai mas @andifahruddinakas .

**Comment by andifahruddinakas** [comment]
mas @agungsugiarto, selelu tampil seperti ini.
![image](https://github.com/OpenSID/OpenSID/assets/57283157/fc4f17ac-7290-4da5-ae0d-bffe974c0a39)

kalau yang sebelumnya akan refresh otomatis dan hilang.
