### ISSUE TITLE
Bug: di menu bantuan perlu dibuatkan tombol paginasi

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#764]
![pagnasi di menu bantuan](https://user-images.githubusercontent.com/25834335/35547898-ef34726e-05b6-11e8-97c0-9bdb4213e905.jpg)

**Comment by ombimo** [comment]
#773 silahkan di cek, sudah saya tambahkan paging di halaman bantuan
@eddieridwan

**Comment by MUHAMMADRANGSEL** [comment]
Siap

Pada tanggal 3 Feb 2018 8.24 PM, "Bimo Aji Pamungkas" <
notifications@github.com> menulis:

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR #773.
