### ISSUE TITLE
Permintaan fitur: Penambahan Lampiran F-2.01 pada Surat Keterangan Pernikahan Non Muslim

### ISSUE THREAD

**Issue by Wiliyantoro** [OpenSID/OpenSID#7641]
### Apa kekurangan yg ingin diatasi?

hanya tersedia lampiran F-2.12 dan belum ada lampiran F-2.01

### Jelaskan solusi yg diinginkan

tambahkan lampiran F-2.01 pada surat tersebut

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

v24.1.0.2 Premium

### Informasi tambahan

karna dukcapil di daerah kami sudah menggunakan form tersebut

**Comment by andifahruddinakas** [comment]
pak @Wiliyantoro, lampiran tsb sudah tersedia.
<img width="468" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/b934a258-a1b5-4650-b40a-20afa5006d9e">

**Comment by Wiliyantoro** [comment]
Lampiran belum suport , lampiran video sudah saya kirim di group telegram

**Comment by roaddee** [comment]
screenshoot f.201 nya dikrim ke sini saja pak
kalau perlu ms word gpp, buat contoh programmer dalam pengerjaannya

**Comment by Wiliyantoro** [comment]
Mungkin saya akan lampirkan foto bagian mana saja yang tampil untuk surat tersebut

**Comment by Wiliyantoro** [comment]
![IMG_20240208_102927](https://github.com/OpenSID/OpenSID/assets/44520382/9abdb402-a1d6-4725-99c1-a7f6ba6a4bbb)
![IMG_20240208_103225](https://github.com/OpenSID/OpenSID/assets/44520382/774846b0-ef76-4f97-a055-1e7c0f2d1f26)
![IMG_20240208_103256](https://github.com/OpenSID/OpenSID/assets/44520382/d22a923d-e341-4763-af1c-8a823155b952)
