### ISSUE TITLE
Bug/error: pasang baru

### ISSUE THREAD

**Issue by afri18** [OpenSID/OpenSID#7643]
### Jelaskan error yg dialami

saat coba pasang baru v 2401.0.2 di localhost(offline) gagal

### Cara untuk mereplikasi errornya

sebaiknya pasang baru bisa untuk semua versi

### Hasil yg diharapkan

bisa pasang baru di semua versi

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/6611881/567a8e54-e948-460d-bd58-011e798c820c)
[log-2024-01-20.zip](https://github.com/OpenSID/OpenSID/files/13996152/log-2024-01-20.zip)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2401.0.2 bug-fix

### Tema Yang Digunakan

-

### Informasi tambahan

untuk semua versi sebaiknya bisa pasang baru termasuk rev

**Comment by semplon** [comment]
saya juga error ketika install baru. 
proses installasi apakah memang tidak ada informasi yang ditampilkan ya ?

**Comment by afri18** [comment]
> saya juga error ketika install baru. proses installasi apakah memang tidak ada informasi yang ditampilkan ya ?

eror apa ?? kadang beda kasus, lampirkan log eror

**Comment by semplon** [comment]
ketika login siteman muncul error seperti ini om
![image](https://github.com/OpenSID/OpenSID/assets/3163608/1706744b-1168-499a-bc93-09f163e5e61d)

ketika proses instalasi, saya kira instalasi belum selesai, ternyata database sudah masuk. saya coba login admin. error 500.

**Comment by andifahruddinakas** [comment]
pak @afri18, @semplon, instalasi sbb : 
![install baru](https://github.com/OpenSID/OpenSID/assets/57283157/ef015450-d7a4-46b6-aa6d-6929ae1a5315)

pada bagian akhir harus masukkan token bagi pelanggan premium.
