### ISSUE TITLE
Bug/error: restore

### ISSUE THREAD

**Issue by afri18** [OpenSID/OpenSID#7644]
### Jelaskan error yg dialami

pasang baru v 2401.0.0 sukses
tingkatkan ke v 2401.0.2 bug-fix sukses
saat restore database dari cpanel gagal

### Cara untuk mereplikasi errornya

restore database dari cpanel menggunakan versi yang sama harusnya bisa

### Hasil yg diharapkan

bisa restore database online/cpanel ke offline/localhist

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/6611881/33779bc9-c667-414e-a26e-09948d76b2e4)
[log-2024-01-20.zip](https://github.com/OpenSID/OpenSID/files/13996623/log-2024-01-20.zip)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2401.0.2 bug-fix

### Tema Yang Digunakan

natra

### Informasi tambahan

localhost/offline
database dari backup an online via aplikasi

**Comment by andifahruddinakas** [comment]
pak @afri18, cek config database -> password nya
