### ISSUE TITLE
Error saat menjalankan rss feed

### ISSUE THREAD

**Issue by mranca** [OpenSID/OpenSID#7645]
### Jelaskan error yg dialami

Saat buka http://beta.opendesa.id/feed terjadi error 404

### Cara untuk mereplikasi errornya

Kunjungi halaman https://beta.opendesa.id/feed

### Hasil yg diharapkan

.

### Tangkapan layar dan log error

![Screenshot_20240120_175300](https://github.com/OpenSID/OpenSID/assets/76085245/d8c51e48-b7b2-4241-afe8-3651dd32dcdf)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Beta V24.01.02 

### Tema Yang Digunakan

Natra

### Informasi tambahan

.

**Comment by yogiperdana** [comment]
Saya reopen karena diassign ya mas @andifahruddinakas

**Comment by andifahruddinakas** [comment]
> Saya reopen karena diassign ya mas @andifahruddinakas 

Ya

sma route sitemap jg
