### ISSUE TITLE
terjadi error saat menambah program bantuan

### ISSUE THREAD

**Issue by mranca** [OpenSID/OpenSID#7646]
### Jelaskan error yg dialami

saat menambah program bantuan data tidak tersimpan dan di arahkan ke halaman website 

### Cara untuk mereplikasi errornya

1. masuk ke halaman admin
2. pilih bantuan 
3. klik tambah
4. isi data sasaran program misalnya penduduk/perorangan 
5. klik simpan

### Hasil yg diharapkan

seharusnya saat menambah program bantuan datanya tersimpan
[log-2024-01-20 (1).zip](https://github.com/OpenSID/OpenSID/files/13997673/log-2024-01-20.1.zip)

### Tangkapan layar dan log error

.

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Beta V24.01.02 

### Tema Yang Digunakan

natra

### Informasi tambahan

.

**Comment by andifahruddinakas** [comment]
SOLUSI : 
- [ ] kolom 'userid' sudah tidak digunakan, lakukan hapus kolom tsb lewat migrasi jika ditemukan.
- [ ] hapus tambah/ubah data terkait kolom 'userid'
