### ISSUE TITLE
error saat tambah surat keluar

### ISSUE THREAD

**Issue by pujocahyono** [OpenSID/OpenSID#7649]
### Jelaskan error yg dialami

error 500 saat tambah surat keluar baru

### Cara untuk mereplikasi errornya

1. menu buku administrasi desa
2. administrasi umum
3. buku agenda - surat keluar
4. tambah surat keluar baru

### Hasil yg diharapkan

tidak error menambahkan surat keluar baru

### Tangkapan layar dan log error

<img width="960" alt="Cuplikan layar 2024-01-21 070858" src="https://github.com/OpenSID/OpenSID/assets/87228587/3f115d16-7be3-4962-88ec-28c66b7073a9">

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2401.0.2-premium

**Comment by mranca** [comment]
di versi beta sudah berjalan bagus pak @pujocahyono
