### ISSUE TITLE
saat input data analisis maka di alihkan ke halaman beranda website 

### ISSUE THREAD

**Issue by mranca** [OpenSID/OpenSID#7650]
### Jelaskan error yg dialami

saat input data di master analisis langsung di arahakan ke halaman beranda website 

### Cara untuk mereplikasi errornya

1. masuk ke halaman admin
2. pilih analisis
3. klik master analisis
4. klik rincian analisis pada analisis keahlian individu
5. klik input sensus / Survei

### Hasil yg diharapkan

.

### Tangkapan layar dan log error

.

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Beta V24.01.02 

### Tema Yang Digunakan

Natra

### Informasi tambahan

.

**Comment by andifahruddinakas** [comment]
dari log errornya : 
```
ERROR - 2024-01-21 14:43:37 --> Query error: Unknown column 'a.config_id' in 'where clause' - Invalid query: SELECT (SELECT a.id_subjek FROM analisis_respon a WHERE a.id_subjek = u.id AND a.config_id =1 AND a.id_periode = 5 LIMIT 1) as cek, (SELECT b.pengesahan FROM analisis_respon_bukti b WHERE b.id_master = 1 AND b.id_periode = 5 AND b.id_subjek = u.id AND b.config_id =1) as bukti_pengesahan, `u`.`id`, `u`.`nik` AS `nid`, `u`.`nama`, `u`.`sex`, `c`.`dusun`, `c`.`rw`, `c`.`rt`
FROM `penduduk_hidup` `u`
LEFT JOIN `tweb_wil_clusterdesa` `c` ON `u`.`id_cluster` = `c`.`id`
WHERE   (
`u`.`config_id` = 1
 )
ORDER BY `u`.`id`
 LIMIT 50
```

**Comment by agungsugiarto** [comment]
error tersebut karena field `config_id` pada table `analisis_respon` dihapus pada migrasi https://github.com/OpenSID/premium/blob/da67f99b23e477ece8a451281fefa537ba53fad2/donjo-app/models/migrations/Migrasi_2024010171.php#L387-L392 pada pr https://github.com/OpenSID/premium/pull/3343, sehingga semua query akan mengalami error.

mas @andifahruddinakas apakah perlu memperbaiki semua query atau dikembalikan field tersebut?
