### ISSUE TITLE
saat menghapus surat keluar terjadi error 

### ISSUE THREAD

**Issue by mranca** [OpenSID/OpenSID#7651]
### Jelaskan error yg dialami

saat menghapus surat kerluar terjadi error dan muncul notif data yanng anda minta tidak ditemukan

### Cara untuk mereplikasi errornya

1. masuk ke admin
2. pilih administrasi Desa
3. klik Administarasi Umum
4. klik Buku Agenda - Surat Keluar
5. hapus salah satu data surat 

### Hasil yg diharapkan

.

### Tangkapan layar dan log error

![Opera Snapshot_2024-01-21_091106_beta opendesa id](https://github.com/OpenSID/OpenSID/assets/76085245/db5943b4-3a34-4a3c-a038-b8df23eefbbf)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Beta V24.01.02 

### Tema Yang Digunakan

natra

### Informasi tambahan

.

**Comment by andifahruddinakas** [comment]
Error terjadi pada bagian ini : 
<img width="329" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/6784b087-c024-481b-be4d-9b40f9aa70b8">
