### ISSUE TITLE
Bug/error: TOMBOL EDIT PADA SURAT KELUAR MENGARAH KE HALAMAN TAMBAH SURAT BARU

### ISSUE THREAD

**Issue by agussudiantara15** [OpenSID/OpenSID#7652]
### Jelaskan error yg dialami

Setelah melakukan klik edit pada salah satu surat keluar yang sudah ada, mengarah ke halaman tambah surat baru 

### Cara untuk mereplikasi errornya

menu administrasi umum/buku agenda-surat keluar, klik edit --- muncul seperti halaman tambah surat keluar baru

### Hasil yg diharapkan

Sebagaimana mestinya

### Tangkapan layar dan log error

**Klik Menu Edit**
![image](https://github.com/OpenSID/OpenSID/assets/157332306/f02cdc9b-e8f3-4e4e-9e32-42e76dc9f3ed)

**Muncul Halaman Seperti Menu Tambah Surat Masuk Baru**
![image](https://github.com/OpenSID/OpenSID/assets/157332306/ae62d77c-70fb-4aae-96a4-b28689aa9b25)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2401.0.2-premium

### Tema Yang Digunakan

Denatra

**Comment by andifahruddinakas** [comment]
Selesai melalui commit https://github.com/OpenSID/premium/commit/847208131441f0ea24e6d94d9d0939f43586ca0c

**Comment by agussudiantara15** [comment]
> Selesai melalui commit https://github.com/OpenSID/premium/commit/847208131441f0ea24e6d94d9d0939f43586ca0c

apa sudah bisa digunakan pak? masalahnya masih sama terjadi di kami
