### ISSUE TITLE
Bug/error: Nikah

### ISSUE THREAD

**Issue by afri18** [OpenSID/OpenSID#7653]
### Jelaskan error yg dialami

data ayah ibu jangan ganda
nama ayah kandung seharusnya isi auto

### Cara untuk mereplikasi errornya

sesuaikan kebutuhan

### Hasil yg diharapkan

tampilan awal surat jangan numpang nikah tetapi N2

### Tangkapan layar dan log error

https://drive.google.com/file/d/1NV5KuIlQ5yY9W94Rq_2E4xOnyYRmppOJ/view?usp=sharing

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2401.0.2 bug-fix

### Tema Yang Digunakan

natra

### Informasi tambahan

dicoba di berputar

**Comment by andifahruddinakas** [comment]
Terkait issue https://github.com/OpenSID/OpenSID/issues/7625
