### ISSUE TITLE
surat keterangan kematian kode isian pelapor tidak bisa panggil data dari database

### ISSUE THREAD

**Issue by mranca** [OpenSID/OpenSID#7654]
### Jelaskan error yg dialami

Untuk data pelapor khususnya untuk data form kabupaten, kecamatan, dan provinsi tidak bisa panggil data yang ada di database dan hanya menampilkan tanda (-)

### Cara untuk mereplikasi errornya

1. Masuk ke admin
2. Pilih layanan surat
3. Klik surat 
4. Buka surat keterangan kematian 
5. isi data pemohon dan pelapor lalu simpan 
6. Klik cetak pdf

### Hasil yg diharapkan

Pada kode isian pelapor Nama kabupaten, kecamatan dan provinsi harus terisi sesuai dengan indentitas desa jika pelapor berada dalam database desa 

### Tangkapan layar dan log error

![IMG_20240122_190957](https://github.com/OpenSID/OpenSID/assets/76085245/5ffbcf1b-140e-4d17-9416-4afe0d2135f0)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Beta V24.01.02 

### Tema Yang Digunakan

.

### Informasi tambahan

.

**Comment by andifahruddinakas** [comment]
mas @mranca, untuk surat bisa lakukan restore template dlu sebelum cek. agar menggunakan template bawaan, krn kemungkinan bisa diubah oleh yang lain atau masih menggunakan data lama.

<img width="407" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/4f029542-bc02-45fc-8c72-56f387d2afd4">

**Comment by mranca** [comment]
@andifahruddinakas ,saya sudah coba restore namun hasilnya tetap sama. mas akas yang tampilkan itu hasilnya adalah alamat dari pelapor akan tetapi issue yang saya laporkan mengenai alamat kabupaten, kecamatan dan provinsi pada pelapor yang tidak menampilkan datanya. Mungkin bisa di coba

**Comment by mranca** [comment]
@andifahruddinakas , mungkin bisa di coba untuk tes masukkan kode isian sesuai yang saya tunjukkan pada arah panah dan bisa di coba di buat surat kematian tersebut
![surat](https://github.com/OpenSID/OpenSID/assets/76085245/ea3cb192-a09d-4d53-a7a8-91a18a1583ea)
