### ISSUE TITLE
Terjadi error 404 saat tampilkan list bantuan

### ISSUE THREAD

**Issue by mranca** [OpenSID/OpenSID#7657]
### Jelaskan error yg dialami

Saat klik tampilkan bantuan misalnya tampilkan 50 maka akan error 404

### Cara untuk mereplikasi errornya

1. Masuk ke admin
2. Klik lihat detail pada dashboard bantuan
3. Klik tampilan 
4. Pilih tampilan 50

### Hasil yg diharapkan

.

### Tangkapan layar dan log error

![IMG_20240123_204010_837](https://github.com/OpenSID/OpenSID/assets/76085245/7e27ea54-e84c-465e-8206-b9ad552e1c2b)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Beta V24.01.02 

### Tema Yang Digunakan

.

### Informasi tambahan

.

**Comment by Zoel-WB** [comment]
Oke thanks, mantap..
