### ISSUE TITLE
Bug/error: Menu Analisis

### ISSUE THREAD

**Issue by pemdeskasokandel** [OpenSID/OpenSID#7659]
### Jelaskan error yg dialami

Saat membuat analisis terjadi error, analisis - input analisis-input data survei/sensus, pas di klik malah kembali ke menu HOME

### Cara untuk mereplikasi errornya

Analisis-input analisis-input data sensus/survey

### Hasil yg diharapkan

Bisa normal lagi

### Tangkapan layar dan log error

![Screenshot_2024-01-24-11-04-24-383_com android chrome](https://github.com/OpenSID/OpenSID/assets/92310810/f496ec10-b6f7-45dc-a230-70691530df9f)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

24.01.0.2

### Tema Yang Digunakan

Batuah 23.05

### Informasi tambahan

-

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui commit https://github.com/OpenSID/premium/commit/d03fef78dc0972859d38025402501d9a32cfb9f5

bisa cek kembali di https://beta.opendesa.id
