### ISSUE TITLE
Bug/error:  Error Tombol Dropdown Pilihan List Tampilkan Daftar Program Bantuan 

### ISSUE THREAD

**Issue by Zoel-WB** [OpenSID/OpenSID#7660]
### Jelaskan error yg dialami

.

### Cara untuk mereplikasi errornya

.

### Hasil yg diharapkan

Supaya cepat dapat teratasi mengingat kebutuhan awal tahun untuk daftar program bantruan baru untuk tahun berjalan

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/64481641/2177e4fc-5fec-493e-baff-e49007b7058e)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v2401.0.2-premium

### Tema Yang Digunakan

.

### Informasi tambahan

.

**Comment by andifahruddinakas** [comment]
Duplicate issue https://github.com/OpenSID/OpenSID/issues/7657
