### ISSUE TITLE
Dragable mode HP

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#7664]
Fungsi dragble pada mode HP tdk berfungsi dengan benar.
![image](https://github.com/OpenSID/OpenSID/assets/57283157/985dcad5-db00-430e-9746-34ae41f33f35)

CEK :
- https://github.com/furf/jquery-ui-touch-punch
- https://stackoverflow.com/questions/4641590/jquery-ui-sortable-how-to-get-it-work-on-ipad-touchdevices

**Comment by andifahruddinakas** [comment]
Dalam kasus ini ada 2 masalah : 
- [ ] jika mode mobile dengan kasus dragable aktif, maka fungsi untuk buttonnya tidak akan berfungsi.
- [ ] jika mode mobile dengan kasus dragable aktif, maka fungsi drafgable tidak dapat digunakan di mode mobile.

**Comment by yogiperdana** [comment]
Saya coba buka https://berputar.opendesa.id/wilayah dari ipad dan android normal mas. button dan dragable normal

**Comment by mranca** [comment]
@yogiperdana kalau masalah dragable normal akan tetapi itu masalahnya tombol yang lain tidak bisa di klik misalnya gembok dan list

**Comment by mranca** [comment]
@yogiperdana kalau masalah dragble normal akan tetapi itu masalahnya tombol yang lain tidak bisa di klik misalnya gembok dan list

**Comment by mranca** [comment]
![IMG_20240211_181823.jpg](https://github.com/OpenSID/OpenSID/assets/76085245/9a816dcb-a4bc-48b7-a502-30e2d7b04178)

Coba tes mas di https://berputar.opendesa.id/wilayah klik tombol sesuai yang saya tunjukkan menggunakan android/ipad

**Comment by yogiperdana** [comment]
Coba klik 2x mas

**Comment by mranca** [comment]
![IMG_20240211_181823.jpg](https://github.com/OpenSID/OpenSID/assets/76085245/9a816dcb-a4bc-48b7-a502-30e2d7b04178)

Coba tes mas di https://berputar.opendesa.id/wilayah klik tombol sesuai yang saya tunjukkan

**Comment by mranca** [comment]
Sdh mas masih tetap tidak bisa

**Comment by yogiperdana** [comment]
> Sdh mas masih tetap tidak bisa

Bisa diinformasikan jenis device yang digunakan pak

**Comment by mranca** [comment]
Saya pakai vivo v20

**Comment by andifahruddinakas** [comment]
> > Sdh mas masih tetap tidak bisa
> 
> Bisa diinformasikan jenis device yang digunakan pak

sy coba di 2 device,
- redmi tab berfungsi
- realeme 2 tidak berfungsi
