### ISSUE TITLE
Cetak surat error dengan font andale mono atau Times New Roman (mungkin selain System Font / Arial)

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#7666]
Terjadi loading yang lama jika cetak surat menggunakan default font andale mono.
<img width="170" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/42e9bab7-43a2-492e-bff7-99357fdde26c">

Cetak : 
<img width="248" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/49b4cb17-b1b7-4339-8c74-4a6dd4c14634">

Jika menggunakan font lain seperto bookmanoldstyle, arial, times aman

**Comment by eddieridwan** [comment]
@andifahruddinakas @pandigresik menggunakan font Times New Roman juga gagal, bisa direplikasi di berputar.opendesa.id (lihat pembahasan di https://t.me/c/1180597796/7290/12663). Jadi mungkin error untuk semua font kecuali System Font yg kebetulan Arial.

Sepertinya berusaha mengakses resource eksternal dan gagal. Harap cari solusi dan diatasi tuntas.

**Comment by agungsugiarto** [comment]
Font bermasalah

- [x] Andale Mono
- [x] Times New Roman
- [x] Courier New
- [x] Tahoma
- [x] Trebuchet MS
- [x] Verdana
- [x] Georgia
- [x] Comic Sans MS
- [x] Impact

**Comment by eddieridwan** [comment]
@agungsugiarto apakah di lokal bermasalah juga? Jika tidak, masalah ada di server, yg perlu dilacak. Jika di server, apakah hanya di VPS (berputar.opendesa.id) atau juga di cPanel (serambi.opendesa.id).

Apakah terjadi di versi sebelumnya? Jika tidak, masalah ada di rilis 2401.
