### ISSUE TITLE
SERVER TIDAK SUPPORT FORMAT RTF

### ISSUE THREAD

**Issue by saferomedia** [OpenSID/OpenSID#7671]
### Jelaskan error yg dialami

untuk server atau hosting niagahoster sudah tidak suport lagi format rtf ketika unduh surat, apkah ada rekomendasi hosting manakah yang tepat ? dan yang support rtf ?

### Cara untuk mereplikasi errornya

untuk server atau hosting niagahoster sudah tidak suport lagi format rtf ketika unduh surat, apkah ada rekomendasi hosting manakah yang tepat ? dan yang support rtf ?

### Hasil yg diharapkan

untuk server atau hosting niagahoster sudah tidak suport lagi format rtf ketika unduh surat, apkah ada rekomendasi hosting manakah yang tepat ? dan yang support rtf ?

### Tangkapan layar dan log error

untuk server atau hosting niagahoster sudah tidak suport lagi format rtf ketika unduh surat, apkah ada rekomendasi hosting manakah yang tepat ? dan yang support rtf ?

### Rilis Versi OpenSID

Rilis Umum

### Versi OpenSID

v22.01

**Comment by balongbesuk** [comment]
coba pindah vps cyberpanel niagahost, sy juga mantan sharehost niagahost pindah ke VPS cyberpanel lancar kembali cmn cyberpanelnya hosting lain

**Comment by andifahruddinakas** [comment]
Bisa ditanyakan di grup telegram

**Comment by andifahruddinakas** [comment]
https://github.com/OpenSID/OpenSID/issues/7552#issuecomment-1911213828
