### ISSUE TITLE
Menu arsip erorBug/error: tidak ada menu surat rtf

### ISSUE THREAD

**Issue by darogkeariston** [OpenSID/OpenSID#7672]
### Jelaskan error yg dialami

Menu arsip eror

### Cara untuk mereplikasi errornya

lihat eror

### Hasil yg diharapkan

diperbaiki 

### Tangkapan layar dan log error

![Screenshot (23)](https://github.com/OpenSID/OpenSID/assets/157740473/d76063e1-b58b-4a12-b524-9eab1182bdf1)
![Screenshot (23)](https://github.com/OpenSID/OpenSID/assets/157740473/6de74ac0-e5ec-4ebd-8e6e-33dfb45b9a74)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

240.1.0.2

### Tema Yang Digunakan

desa/denatra

### Informasi tambahan

Mohon dibantu untuk cetak surat lembar kerja kosong dan menu arsip layanan eror

**Comment by andifahruddinakas** [comment]
Update ke versi 2401.0.3
