### ISSUE TITLE
Error Ketika Login Admin Untuk Pertama Kalinya

### ISSUE THREAD

**Issue by aufasyaihan** [OpenSID/OpenSID#7673]
### Jelaskan error yg dialami

Saya ingin melakukan instalasi SID menggunakan OpenSID melalui github, saya telah mengikuti langkah-langkah pada github mulai dari download zip terbaru, setup database sampai muncul halaman utamanya, namun saat login admin (untuk pertama kalinya) saya menggunakan username **admin** dan password **sid304**, terjadi error 500 yang dimana saya telusuri errornya muncul keterangan error sebagai berikut :

`Message: Undefined constant "Provinsi" (View: C:\xampp\htdocs\opensid\resources\views\admin\identitas_desa\index.blade.php)`

saya sudah mencoba menambahkan ('') pada kata provinsi namun error tersebut berubah menjadi sebagai berikut :

`User
Message: count(): Argument #1 ($value) must be of type Countable|array, null given (View: C:\xampp\htdocs\opensid\resources\views\admin\layouts\partials\sidebar.blade.php) (View: C:\xampp\htdocs\opensid\resources\views\admin\layouts\partials\sidebar.blade.php) (View: C:\xampp\htdocs\opensid\resources\views\admin\layouts\partials\sidebar.blade.php)`

### Cara untuk mereplikasi errornya

1. Saya merubah production menjadi development yang dapat menunjukkan error
2. Halaman berubah menjadi informasi menunjukkan error
3. Error tersebut terletak pada resources\views\admin\identitas_desa\index.blade.php pada kata "Provinsi"

### Hasil yg diharapkan

Lanjut ke halaman ganti password untuk pertama kalinya

### Tangkapan layar dan log error

![IMG-20240126-WA0103](https://github.com/OpenSID/OpenSID/assets/90436215/8f35b7f6-95be-4d6a-b63a-054fad573d0d)
![IMG-20240126-WA0101](https://github.com/OpenSID/OpenSID/assets/90436215/fe7006a4-c6d1-4876-9c26-fd8ebf74dd91)

### Rilis Versi OpenSID

Rilis Umum

### Versi OpenSID

v2401.0.0

**Comment by andifahruddinakas** [comment]
pak @aufasyaihan, silahakan gunakana php 7.4 untuk versi umum dan bisa update ke versi 2402.0.0 (https://github.com/OpenSID/OpenSID/tree/dev) yang akan datang

**Comment by aufasyaihan** [comment]
> pak @aufasyaihan, silahakan gunakana php 7.4 untuk versi umum dan bisa update ke versi 2402.0.0 (https://github.com/OpenSID/OpenSID/tree/dev) yang akan datang

untuk php saya menggunakan versi 8 apakah belum support? berarti saya perlu menurunkan versi php?

**Comment by andifahruddinakas** [comment]
> > pak @aufasyaihan, silahakan gunakana php 7.4 untuk versi umum dan bisa update ke versi 2402.0.0 (https://github.com/OpenSID/OpenSID/tree/dev) yang akan datang
> 
> untuk php saya menggunakan versi 8 apakah belum support? berarti saya perlu menurunkan versi php?

belum
