### ISSUE TITLE
Bug/error : Eror 404 Ketika Cetak Agenda Surat Masuk

### ISSUE THREAD

**Issue by pongky87** [OpenSID/OpenSID#7674]
### Jelaskan error yg dialami

Ketika sudah input data surat masuk dan hendak di cetak agenda surat masuk muncul error 404 
![Untitled](https://github.com/OpenSID/OpenSID/assets/156563096/b86e5ebe-cee2-473c-ac19-79744d019ae7)

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

Muncul halaman Agenda Surat

### Tangkapan layar dan log error

ERROR - 2024-01-26 00:02:15 --> 404 Page Not Found: 
ERROR - 2024-01-26 00:02:37 --> 404 Page Not Found: 
ERROR - 2024-01-26 00:03:21 --> 404 Page Not Found: 
ERROR - 2024-01-26 00:03:32 --> 404 Page Not Found: 
ERROR - 2024-01-26 00:03:41 --> 404 Page Not Found: 
ERROR - 2024-01-26 00:06:42 --> 404 Page Not Found: 

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Rilis premium 24.01.03

### Tema Yang Digunakan

denatra

### Informasi tambahan

-

**Comment by mranca** [comment]
Mohon di buka mash ada bug

**Comment by mranca** [comment]
Masih belum bisa tercetak

**Comment by andifahruddinakas** [comment]
> Masih belum bisa tercetak

sudah disesuaikan

**Comment by mranca** [comment]
Oke
