### ISSUE TITLE
Bug/error: terjadi error saat mau menyimpan hasil input data analisis

### ISSUE THREAD

**Issue by pemdeskasokandel** [OpenSID/OpenSID#7675]
### Jelaskan error yg dialami

2401.0.3-premium
terjadi error 500 saat mau menyimpan hasil input data analisis

### Cara untuk mereplikasi errornya

analisis-master analisis-pilih data analisis-input data survei/sensus-input data-simpan terjadi error 500

### Hasil yg diharapkan

dapat normal kembali

### Tangkapan layar dan log error

![Uploading error.jpg…]()

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2401.0.3-premium

### Tema Yang Digunakan

batuah 23.05

**Comment by pandigresik** [comment]
Ini fitur yang mana, saya coba analisis_master lancar saja, gambar pada issue juga tidak jelas

[Screencast from 30-01-24 15:51:39.webm](https://github.com/OpenSID/OpenSID/assets/1853475/8e2caad8-82e6-4355-b498-90ef80878848)

**Comment by andifahruddinakas** [comment]
Duplicate of https://github.com/OpenSID/OpenSID/issues/7659
