### ISSUE TITLE
Data agenda tidak tampil

### ISSUE THREAD

**Issue by mranca** [OpenSID/OpenSID#7676]
### Jelaskan error yg dialami

Saat ingin menampilkan agenda kegiatan desa data kegiatan agenda tidak bisa tampil di halaman website / widget agenda

### Cara untuk mereplikasi errornya

1. Masuk halaman admin
2. Admin website
3. Widget 
4. Tambah widget agenda 

### Hasil yg diharapkan

.

### Tangkapan layar dan log error

![Screenshot_20240128_000521](https://github.com/OpenSID/OpenSID/assets/76085245/d214e24a-29ee-4b56-b098-3cdb573e3e29)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v2401.03

### Tema Yang Digunakan

Natra

### Informasi tambahan

.

**Comment by andifahruddinakas** [comment]
https://github.com/OpenSID/premium/issues/3460
