### ISSUE TITLE
Tidak Dapat Menghapus Data Dusun

### ISSUE THREAD

**Issue by aufasyaihan** [OpenSID/OpenSID#7677]
### Jelaskan error yg dialami

Saya sedang mencoba untuk menggunakan SID, saya melakukan import data penduduk melalui excel, yang dimana otomatis menambahkan data dusun, ketika seluruh data penduduk saya hapus, data dusun masih ada dan tidak dapat saya hapus, ketika saya mencoba menghapusnya muncul error yang telah saya lampirkan, padahal data penduduk sudah saya hapus

### Cara untuk mereplikasi errornya

1. Pada halaman admin buka menu info desa
2. Buka Sub Menu Wilayah Administrasi
3. Hapus Data

### Hasil yg diharapkan

Data Dusun Terhapus

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/90436215/165b8613-607e-4642-ab6b-bb23e541566e)

### Rilis Versi OpenSID

Rilis Umum

### Versi OpenSID

v2401.0.0

**Comment by andifahruddinakas** [comment]
pak @aufasyaihan, bisa hapus atau pindahkan penduduk yang ada di dusun tersebut.

**Comment by aufasyaihan** [comment]
> pak @aufasyaihan, bisa hapus atau pindahkan penduduk yang ada di dusun tersebut.

seluruh data penduduk sudah saya hapus sebelumnya, namun data dusun masih ada dan tidak dapat saya hapus
