### ISSUE TITLE
terjadi error 500 saat import data suplement

### ISSUE THREAD

**Issue by mranca** [OpenSID/OpenSID#7678]
### Jelaskan error yg dialami

saat import data suplement terjadi error 500

### Cara untuk mereplikasi errornya

1. masuk ke admin
2. kependudukan
3. data suplement
4. buat suplement
5. lakukan import data pada suplement yang sudah di buat

### Hasil yg diharapkan

.

### Tangkapan layar dan log error

![Screenshot (115)](https://github.com/OpenSID/OpenSID/assets/76085245/7a3c5be9-c04a-4698-a11d-536b421d7587)

dan log errornya

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

beta v2401.03

### Tema Yang Digunakan

.

### Informasi tambahan

.

**Comment by andifahruddinakas** [comment]
Error : 
```
Severity: error --> Exception: SQLSTATE[42000]: Syntax error or access violation: 1055 'beta_beta_premium.suplemen.config_id' isn't in GROUP BY (SQL: select `suplemen`.*, COUNT(suplemen_terdata.id) AS jml from `suplemen` left join `suplemen_terdata` on `suplemen_terdata`.`id_suplemen` = `suplemen`.
id` where `suplemen`.`id` = 1 and `suplemen`.`config_id` = 1 group by `suplemen`.`id` limit 1) /home/beta.opendesa.id/public_html/vendor/illuminate/database/Connection.php 712 
```
