### ISSUE TITLE
Bug/error: Daftar Persil Pertanahan

### ISSUE THREAD

**Issue by dwixhartanto** [OpenSID/OpenSID#7679]
### Jelaskan error yg dialami

Error saat daftar persil, di menu Pertanahan > Daftar Persil > tambah Persil

di log tertulis 

Query error: Out of range value for column 'luas_persil' at row 1 - Invalid query: INSERT INTO `persil` (`nomor`, `nomor_urut_bidang`, `kelas`, `id_wilayah`, `luas_persil`, `lokasi`, `path`, `id_peta`, `cdesa_awal`, `config_id`) VALUES ('14', '14', '1', '13', '103850000', NULL, '[[[-7.0475608388481  

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

Error Teratasi

### Tangkapan layar dan log error
![Screenshot_8](https://github.com/OpenSID/OpenSID/assets/89287777/7c93c8fe-670b-420d-9701-d8f1b0cf529e)

hasil dari error log
![Screenshot_7](https://github.com/OpenSID/OpenSID/assets/89287777/bc015f58-b97a-46a5-8591-2c6eeaf6b6c4)

### Rilis Versi OpenSID

Rilis Umum

### Versi OpenSID

24.01

### Tema Yang Digunakan

DeNatra v8.2

**Comment by pandigresik** [comment]
luas tanahnya memang 103850000 m persegi ? Luas sekali tanahnya

**Comment by andifahruddinakas** [comment]
SOLUSI : 
- [x] tambahkan validasi max input mis. 1.000.000
- [x] gunakan input number
