### ISSUE TITLE
Terapkan menu Sekretariat > Inventaris Desa

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#768]
Fitur ini telah diprioritaskan https://www.facebook.com/Hooaamz (Il Ham) yang telah mengirim donasi Rp500.000.

Untuk bisa dikerjakan, diperlukan spesifikasi rinci apa yang dibutuhkan:
- data yang akan disimpan
- fungsi (aksi apa saja)
- tampilan layar
- laporan

Beri contoh form dan laporan manual yang digunakan saat ini.

**Comment by balongbesuk** [comment]
kalau mengacu model A.3 seperti ini
![35602019-86e4a69a-0668-11e8-8f76-9ce934547909](https://user-images.githubusercontent.com/35319600/35664969-b910989c-0756-11e8-8206-5f6d7c1defc5.jpg)

**Comment by eddieridwan** [comment]
Model A.3 dan petunjuk pengisiannya ada di lampiran
PERATURAN MENTERI DALAM NEGERI REPUBLIK INDONESIA NOMOR 47 TAHUN 2016 TENTANG ADMINISTRASI PEMERINTAHAN DESA

[permen_no.47_th_2016.zip](https://github.com/OpenSID/OpenSID/files/1685298/permen_no.47_th_2016.zip)

**Comment by MUHAMMADRANGSEL** [comment]
![image](https://user-images.githubusercontent.com/25834335/35683405-bc2f4c42-079e-11e8-9cff-ede326f94d50.png)



[BUKU INVENTARIS DAN KEKAYAAN DESA.zip](https://github.com/OpenSID/OpenSID/files/1685839/BUKU.INVENTARIS.DAN.KEKAYAAN.DESA.zip)

**Comment by eddieridwan** [comment]
@MUHAMMADRANGSEL , @balongbesuk : harap lampirkan contoh _Buku Inventaris dan Kekayaan Desa_ yang sudah diisi -- lebih baik gunakan contoh nyata dari desa.

**Comment by MUHAMMADRANGSEL** [comment]
![image](https://user-images.githubusercontent.com/25834335/36062355-cb9daf9e-0ea5-11e8-8c56-e4d7930c161a.png)

**Comment by MUHAMMADRANGSEL** [comment]
Waktu kami di audit oleh Inspektorat pada waktu itu beliau minta Buku Inventaris Desa dan pada waktu itu kami belum punya sehingga pada waktu itu dari inspektorat memberikan kami file maslah inventaris desa sesuai dengan PERATURAN MENTERI DALAM NEGERI NOMOR 17 TAHUN 2007 TENTANG PEDOMAN TEKNIS PENGELOLAAN BARANG MILIK DAERAH  dan didalam permendagri tersebut ada 6 jenis yang perlu diisi 
![image](https://user-images.githubusercontent.com/25834335/36062395-aa0d1bc0-0ea6-11e8-9474-918063b6efc2.png)
dan ini saya lampirkan filenya bebrbentuk excel disana ada kode kodenya
[BAHAN ISIAN INVENTARIS.zip](https://github.com/OpenSID/OpenSID/files/1713408/BAHAN.ISIAN.INVENTARIS.zip)

**Comment by MUHAMMADRANGSEL** [comment]
sesuai dengan PERATURAN MENTERI DALAM NEGERI NOMOR 17 TAHUN 2007 TENTANG PEDOMAN TEKNIS PENGELOLAAN BARANG MILIK DAERAH  namun ini saya rasa sangat ribet mas eddie lebih baik mengacu kepada PERATURAN MENTERI DALAM NEGERI REPUBLIK INDONESIA NOMOR 47 TAHUN 2016 TENTANG ADMINISTRASI PEMERINTAHAN DESA lebih simple

**Comment by eddieridwan** [comment]
Dikerjakan mengacu pada PERATURAN MENTERI DALAM NEGERI REPUBLIK INDONESIA NOMOR 47 TAHUN 2016 TENTANG ADMINISTRASI PEMERINTAHAN DESA.

Sudah dicommit ke master.

**Comment by dediex** [comment]
berikut saya mengusulkan susunan tabel untuk project inventaris.
mohon maaf tidak bisa bantu untuk pemrograman php dengan framework CI.
[susunan db inventaris.xlsx](https://github.com/OpenSID/OpenSID/files/1734775/susunan.db.inventaris.xlsx)

**Comment by eddieridwan** [comment]
@dediex : itu susunan db dari aplikasi apa? Yang sudah diterapkan di issue ini tidak jauh beda. Yang penting hasilnya, seperti yg tampil di halaman Inventaris dan di Buku Inventaris dan Kekayaan Desa.

Untuk ke muka, harap anda memberi masukan SEBELUM suatu issue diterapkan, bukan SESUDAH. Kami sudah lama meminta masukan untuk issue ini.

**Comment by dediex** [comment]
@eddieridwan dulu pada waktu kerja disurabaya pernah disuruh membuat data inventaris setiap barang dan sekaligus membuat history dari barang tersebut, jadi bos bisa tahu spesifikasi barang inventaris tersebut dan pernah diservis berapa kali. itu nanti sebagai bahan pertimbangan apakah barang tersebut masih layak digunakan atau tidak.
