### ISSUE TITLE
Bug/error: EROR CETAK SURAT MASUK, SURAT KELUAR, DAN BUKU LEMBARAN DESA

### ISSUE THREAD

**Issue by agussudiantara15** [OpenSID/OpenSID#7681]
### Jelaskan error yg dialami

Eror terjadi pada saat akan melakukan cetak dan download pada saat cetak dan download di menu Administrasi Umum : 
1. Buku Agenda - Surat Keluar
2. Buku Agenda - Surat Masuk
3. Buku Lembaran Desa dan Berita Desa

### Cara untuk mereplikasi errornya

1. pergi ke menu administrasi umum
2. klik tombol cetak/download pada surat masuk, surat keluar, atau lembaran desa
3. muncul eror

### Hasil yg diharapkan

Sebagaimana mestinya

### Tangkapan layar dan log error

**TAMPILAN EROR SAAT CETAK DAN DOWNLOAD**
![image](https://github.com/OpenSID/OpenSID/assets/157332306/ca9659fd-6718-4a9f-aa65-3cdfb03d895a)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2401.0.3-premium

### Tema Yang Digunakan

Denatra

**Comment by ariandii** [comment]
https://github.com/OpenSID/OpenSID/issues/7674
