### ISSUE TITLE
Bug/error: berbeda besar kecil huruf pada gelar saat cetak surat

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#7685]
### Jelaskan error yg dialami

setting di halaman identitas desa
seharusnya:
Indra Wardana, S.STP., M.A.P

![image](https://github.com/OpenSID/OpenSID/assets/46939846/33a89d91-44f6-4f7d-afe0-2fe873408ac1)

hasil cetak surat. bawaan sistem (contoh ini cetak surat nikah)
Indra Wardana, S.stp., M.a.p

![image](https://github.com/OpenSID/OpenSID/assets/46939846/bb46241c-89a7-485d-b717-adb32c0950bc)

berbeda besar kecil huruf pada gelar.

### Cara untuk mereplikasi errornya

buat nama camat di identias desa dengan gelar,
maka saat cetak surat, muncul nama camat huruf pada gelarnya berubah.

### Hasil yg diharapkan

sesuai yang diketik di identitas desa

### Tangkapan layar dan log error

di atas

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Terbaru

**Comment by andifahruddinakas** [comment]
SOLUSI : 
- sesusikan helper gelar()
- jangan konversi nama sekaligus
- contoh : 
`gelar('Dr.', strtoupper('Akas'), 'S.Si')`
