### ISSUE TITLE
Bug/error: Hasil install baru, tidak muncul widget Jam Kerja bawaan sistem.

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#7686]
### Jelaskan error yg dialami

Seharusnya muncul widget Jam Kerja karena tersedia di OpenSID

### Cara untuk mereplikasi errornya

install baru dan lihat menu widget. belum terseid menu widget jam_kerja.php bawaan sistem

### Hasil yg diharapkan

tersedia jam_kerja.php bawaan sistem

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Terbaru

**Comment by andifahruddinakas** [comment]
SOLUSI : 
- [ ] tambahkan widget jam kerja dengan status terkunci jika belum tersedia melalui migrasi.
- [ ] pastikan migrasi jalan untuk database gabungan.
