### ISSUE TITLE
Bug/error: Tidak Tersedia Kategori Default, Kesulitan Membuat Artikel

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#7688]
### Jelaskan error yg dialami

Saat ini ketika install baru, pengguna terlihat jarang sekali membuat artikel. bahkan ketika membuat, mereka justru tambah di Artikel Statis karena ada tombol Tambah Artikel:

![image](https://github.com/OpenSID/OpenSID/assets/46939846/dd72044b-2f72-41c8-855a-3c7de64703aa)

### Cara untuk mereplikasi errornya

Install baru, dan mencoba membuat artikel.

seharusnya ada minimal 1 Kategori yang tersedia secara default misal:
"Berita Desa".

### Hasil yg diharapkan

Agar pengguna baru tidak bingung di awal. karena saat ini harus menambah Kategori dulu di Admin  Web -> Kategori (gambar 1)

Dan tidak membuat Artikel di Halaman Statis yang berbeda peruntukannya.

### Tangkapan layar dan log error

gambar 1:
![image](https://github.com/OpenSID/OpenSID/assets/46939846/e50a339c-f715-4bb9-9f75-51236face8ec)

gambar 2:
![image](https://github.com/OpenSID/OpenSID/assets/46939846/a11c1449-6932-4934-b227-f0d83535fc25)

gambar 3:
![image](https://github.com/OpenSID/OpenSID/assets/46939846/ae996338-83ba-4d93-a886-028aaeac30e7)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Terbaru

**Comment by ariandii** [comment]
Info Tambahan, pada Artikel Statis, ada tombol Hapus Kategori. seharusnya tidak ada karena Statis tidak memiliki Kategori.

![2024-02-02_11h19_43](https://github.com/OpenSID/OpenSID/assets/46939846/f0933d82-a668-4336-9777-b8ed032f5dec)

**Comment by andifahruddinakas** [comment]
mba @FirlianiF, cek : 
- [ ] hapus dan batasi juga (jika diakses langsung dr url) hapus kategori untuk semua artikel tipe selai dinamis;
<img width="571" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/0c46cf45-45a6-464d-9a6c-5f3b8948c08f">
