### ISSUE TITLE
Bug: Surat Kelahiran tidak ingat bayi penduduk yang baru ditambahkan

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#769]
![img1](https://user-images.githubusercontent.com/35319600/35762795-6950365c-08d0-11e8-8876-8dc73dc2156a.jpg)

ketika data bayi sudah diisi >selanjutnya> saya klik buat data penduduk baru (bayi menjadi penduduk terdata ) >selanjutnya> saya pilih pelapor (warga desa) >nah ketika setelah memilih pelapor> nama bayi hilang dan pilihan menjadi penduduk tidakterdata

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
