### ISSUE TITLE
Bagan Organisasi tidak tampil

### ISSUE THREAD

**Issue by pujocahyono** [OpenSID/OpenSID#7698]
### Jelaskan error yg dialami

Jika **Bagan - Offset** terisi angka. Bagan Organisasi tidak muncul di menu Buku Pemerintah Desa

### Cara untuk mereplikasi errornya

1. Menu Buku Administrasi Desa
2. Administrasi Umum
3. Buku Pemerintah Desa

![Screenshot_2024-02-05-21-14-33-986_com android chrome](https://github.com/OpenSID/OpenSID/assets/87228587/d68267e5-03f5-4d6e-9cf5-a346d2b9b3f5)

### Hasil yg diharapkan

Bagan Organisasi tampil dengan normal

### Tangkapan layar dan log error

![Screenshot_2024-02-05-21-14-54-867_com android chrome](https://github.com/OpenSID/OpenSID/assets/87228587/915a9703-b79a-490e-ba67-6362db6c35ae)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v2402.0.0

**Comment by mranca** [comment]
Ini krn blm di atur bagangnya di web demo

**Comment by pujocahyono** [comment]
D berputar sudah d coba. Silahkan d cek
