### ISSUE TITLE
menu BANTUAN halaman kosong

### ISSUE THREAD

**Issue by agilbarker** [OpenSID/OpenSID#7699]
### Jelaskan error yg dialami

menu bantuan pada halaman admin saat di klik cuma keluar halaman putih

### Cara untuk mereplikasi errornya

1. halaman admin
2. menu bantuan
3. tidak menampilkan halaman

### Hasil yg diharapkan

menampilkan halaman bantuan

### Tangkapan layar dan log error

![Untitled](https://github.com/OpenSID/OpenSID/assets/60205674/985e4614-5f23-4d34-8b76-1c89fd20c25c)
setelah di klik
![gambar](https://github.com/OpenSID/OpenSID/assets/60205674/c6cb3307-487f-4c63-862d-da90eab69a5e)

### Rilis Versi OpenSID

Rilis Umum

### Versi OpenSID

2402.0.0

### Tema Yang Digunakan

admin

**Comment by yogiperdana** [comment]
Ini kemungkinan karena salah resolve mas @andifahruddinakas

**Comment by yogiperdana** [comment]
Saya langsung perbaiki di dev mas @andifahruddinakas https://github.com/OpenSID/OpenSID/commit/7783bcfcbd2b78414b458661191e70d94300a831
