### ISSUE TITLE
Permintaan fitur: Nomor Surat Pindah Lampiran F-1.08

### ISSUE THREAD

**Issue by Agungf19** [OpenSID/OpenSID#7700]
### Apa kekurangan yg ingin diatasi?

mohon untuk bisa ditambahkan nomor surat seperti contoh
No. 475 / 002 / II / 2024
karena saya lihat pada setiap lampiran mulai dari F-1 sampai F-2 tidak ada nomor suratnya, pada bagian yang saya kasih tanda kotak merah. dan mohon juga untuk bisa di terapkan pada setiap lampiran surat, karena masih kosong, jd biar tidak mengisi manual
![image](https://github.com/OpenSID/OpenSID/assets/43205017/37098ddf-cc99-4ca3-8800-4ede309fb20a)

### Jelaskan solusi yg diinginkan

mohon untuk bisa ditambahkan nomor surat seperti contoh
No. 475 / 002 / II / 2024
karena saya lihat pada setiap lampiran mulai dari F-1 sampai F-2 tidak ada nomor suratnya, pada bagian yang saya kasih tanda kotak merah. dan mohon juga untuk bisa di terapkan pada setiap lampiran surat, karena masih kosong, jd biar tidak mengisi manual
![image](https://github.com/OpenSID/OpenSID/assets/43205017/37098ddf-cc99-4ca3-8800-4ede309fb20a)

### Apakah ada alternatif lain

tidak ada

### Untuk versi OpenSID mana

Versi 2403.0.0-premium

### Informasi tambahan

tidak ada

**Comment by andifahruddinakas** [comment]
Duplicate issue https://github.com/OpenSID/OpenSID/issues/7721
