### ISSUE TITLE
Foto pengurus pada bagan organisasi tidak tampil

### ISSUE THREAD

**Issue by pujocahyono** [OpenSID/OpenSID#7702]
### Jelaskan error yg dialami

Foto pengurus/pemerintah desa pada Bagan Organisasi tidak tampil

### Cara untuk mereplikasi errornya

1. Menu Buku Administrasi Desa
2. Administrasi Umum
3. Buku Pemerintah Desa
4. Bagan Organisasi

### Hasil yg diharapkan

Foto pengurus tampil dengan normal

### Tangkapan layar dan log error

![Screenshot_2024-02-07-21-18-22-490_com android chrome](https://github.com/OpenSID/OpenSID/assets/87228587/02c95c98-9097-47ac-a84a-bdb9424ee060)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v2402.0.1-premium

**Comment by ariandii** [comment]
foto muncul sesuai sumber foto aparatur desa (verssi sebelumnya), bukan dari foto penduduk (seperti di versi ini) sesuai issue ini:
https://github.com/OpenSID/OpenSID/issues/7687

berikut gambarnya yang muncul berbeda dengan foto penduduk tersebut. karena terdahulu foto perangkat desa terpisah dari penduduk (yang pernah diupload):
![image](https://github.com/OpenSID/OpenSID/assets/46939846/3ca5ed5d-5b53-46f9-bf64-5e389de0069c)

**Comment by andifahruddinakas** [comment]
BATASAN ISSUE :
- [ ] 1. jika penduduk desa dan pada tabel tweb_desa_pamong ada data kolom foto,  cek data foto pengurus dan tampilkan jika file tersedia
- [ ] 2. jika penduduk desa dan pada tabel tweb_desa_pamong tidak ada data kolom foto, ambil gambar dari data penduduk jika file tersedia
- [ ] 3. jika penduduk luar desa, ambil gambar dari data foto pengurus jika file tersedia
- [ ] 4. jika data ada namun file tidak tersedia, tampilkan foto sesuai jenis kelamin
