### ISSUE TITLE
Tombol menu tidak bisa di klik jika di akses menggunakan smartphone/android 

### ISSUE THREAD

**Issue by mranca** [OpenSID/OpenSID#7708]
### Jelaskan error yg dialami

Saat ingin klik tombol edit, gembok dan list menggunakan smartphone atau android tombol tidak bisa di klik

### Cara untuk mereplikasi errornya

Saya sarangkan untuk testing menggunakan smartphone/android untuk melakukan pengujian karena kalau menggunakan pc normal
1. Masuk admin
2. Admin web
3. Menu

### Hasil yg diharapkan

.

### Tangkapan layar dan log error

![IMG_20240210_155839](https://github.com/OpenSID/OpenSID/assets/76085245/f74027c6-ee41-4aa1-a59f-98358e2de677)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Terbaru

### Tema Yang Digunakan

.

### Informasi tambahan

.

**Comment by andifahruddinakas** [comment]
sama dengan laporannya pak @ariandii sebelum rilis tgl 1, terkait masalah tsb diterapkan di issue https://github.com/OpenSID/OpenSID/issues/7664.

**Comment by mranca** [comment]
Oke siap

**Comment by mranca** [comment]
@andifahruddinakas terjadi juga di menu widget
