### ISSUE TITLE
Bug/error: BUKU LEMBARAN DESA DAN BERITA DESA EROR 404

### ISSUE THREAD

**Issue by agussudiantara15** [OpenSID/OpenSID#7715]
### Jelaskan error yg dialami

terjadi eror 404 saat klik menu Buku Administrasi Umum/Buku Lembaran Desa dan Berita Desa. 
Namun eror tersebut tidak terjadi lagi setelah melakukan klik pada menu lainnya terlebih dulu, contoh klik buku ekspedisi selanjutnya kembali klik Buku Lembaran Desa terbuka normal.

**saat langsung menuju buku lembaran desa dan berita desa untuk pertama kali buka**
![image](https://github.com/OpenSID/OpenSID/assets/157332306/cabd8c30-fb48-453c-958a-4fb23347b117)

**terjadi eror 404**
![Screenshot 2024-02-12 090658](https://github.com/OpenSID/OpenSID/assets/157332306/ff001a17-8f75-4327-931d-8948c1d88c50)

**Saat beralih ke menu lainnya**
![image](https://github.com/OpenSID/OpenSID/assets/157332306/eb8ec5b2-0e48-4772-bb4a-2671e88b952a)

**Kembali ke Buku Lembaran Desa kembali normal**
![image](https://github.com/OpenSID/OpenSID/assets/157332306/5b40a844-62d2-486c-a0f9-d1dba8b6cadc)

### Cara untuk mereplikasi errornya

Sebagaimana mestinya

### Hasil yg diharapkan

Sebagaimana mestinya

### Tangkapan layar dan log error

Sebagaimana mestinya

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2402.0.1-premium

### Tema Yang Digunakan

Denatra

**Comment by andifahruddinakas** [comment]
pak @agussudiantara15, silahkan jalankan ulang migrasinya. krn sudah dilakukan perbaikan di versi sebelumnya. cek https://forum.opendesa.id/d/320-beberapa-url-yang-terdapat-clear-tidak-lagi-dapat-di-akses
