### ISSUE TITLE
Surat Konsep

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#7716]
Terjadi beberapa kendala ketika surat disimpan dalam bentuk konsep. Kendala tsb sbb : 
- [ ] surat yang disimpan sebagai konsep dan di pratinjau saja, statusnya akan berubah jadi cetak.
- [ ] urat yang disimpan sebagai konsep nomernya tidak tersimpan.
<img width="440" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/7b2fd515-3db7-48ef-b472-7b48f6e0d030">

- [ ] konsep saya edit lalu klil konsep lagi. eror 500.
- [ ] konsep saya edit dan klik pratinjau, lalu konsep lagi. maka saat edit isinya template nya yg ada, hilang.

**Comment by Wiliyantoro** [comment]
![image](https://github.com/OpenSID/OpenSID/assets/44520382/93984743-b85f-4552-8b16-7cbb5c095ab3)

kode pada surat tampil seperti di atas

**Comment by Wiliyantoro** [comment]
![image](https://github.com/OpenSID/OpenSID/assets/44520382/72dc5459-63a6-426d-b45a-d80c47cb4bda)

**Comment by andifahruddinakas** [comment]
> ![image](https://private-user-images.githubusercontent.com/44520382/305647975-72dc5459-63a6-426d-b45a-d80c47cb4bda.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgxODAwMjcsIm5iZiI6MTcwODE3OTcyNywicGF0aCI6Ii80NDUyMDM4Mi8zMDU2NDc5NzUtNzJkYzU0NTktNjNhNi00MjZkLWI0NWEtZDgwYzQ3Y2I0YmRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE3VDE0MjIwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1NWU3MGVlMmRlZjM5MjZmYTYxNzhhYWUzNGU2OGNlMzNiZThmYTBkMmMyMGVkNDM5NDQ2OWIzMzE4ZjI2ZTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uMq---AzheHyASNKmUXL1M_gq63rVvNlsHmB2sGDwDc)

silahkan di update ulang menggunakan https://github.com/OpenSID/rilis-premium/releases/tag/v2402.0.2
