### ISSUE TITLE
Verifikasi Recaptha sebelum digunakan

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#7720]
Perlu pengecekan untuk menggunakan recaptha, walaupun sudah diinput namun ternyata tidak valid.
<img width="196" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/04b4f81b-4219-4c73-95de-099116b71cd1">
<img width="357" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/8c1e4679-800d-4c7c-a4be-55e34b3bb32a">

SOLUSI : 
- [ ] Perlu adanya verifikasi Google Recaptcha valid atau tidak saat simpan pengaturan dan saat akses halaman yang memiliki captha.

**Comment by eddieridwan** [comment]
@andifahruddinakas bagaimana jika recaptcha key menjadi tidak valid SETELAH disimpan?

**Comment by andifahruddinakas** [comment]
> @andifahruddinakas bagaimana jika recaptcha key menjadi tidak valid SETELAH disimpan?

bisa tambahkan pengecekan juga pada halaman yang membutuhkan captha, jika saat akses captha tidak valid maka captha dibuat tidak aktif.

**Comment by andifahruddinakas** [comment]
https://stackoverflow.com/questions/31975099/php-validate-the-recaptcha-v2-response

**Comment by eddieridwan** [comment]
https://github.com/OpenSID/premium/pull/3526#issuecomment-2361301875

Pastikan sdh menerapkan ketentuan: kalau Google Recaptcha gagal, karena apapun, secara otomatis kembali gunakan captcha bawaan.

**Comment by andifahruddinakas** [comment]
Setelah di cek, terkait perubahan pada PR https://github.com/OpenSID/premium/pull/3957 yang mengkonversi halaman siteman. mas @agungsugiarto, bisa disesuaikan kembali sama seperti sebelum di konversi terkait google recaptha ini.

**Comment by agungsugiarto** [comment]
mas @andifahruddinakas bisa kirim site key dan private key google captcha ke dm.

**Comment by andifahruddinakas** [comment]
> mas @andifahruddinakas bisa kirim site key dan private key google captcha ke dm.

Sdh dikirm ke telegram
