### ISSUE TITLE
Bug/error: Nomor surat pada lampiran F.1-08, F.1-25 dan F.1-27 tidak ada

### ISSUE THREAD

**Issue by Agungf19** [OpenSID/OpenSID#7721]
### Jelaskan error yg dialami

beberapa lampiran surat , saya lihat nomor suratnya tidak ada, mohon untuk bisa diperbaiki, 
apakah memang ditulis manual, atau bisa dibuat otomatis seperti surat keterangan

### Cara untuk mereplikasi errornya

1. layanan surat
2. cetak surat yg ada lampirannya
3. isikan kolom yg diperlukan
4. cetak
5. lihat pada bagian lampiran surat, nomor suratnya kosong

### Hasil yg diharapkan

semoga untuk bisa buat nomor surat otomatis pada lampiran F-1 s/d F-2
mohon untuk bisa ditambahkan nomor surat seperti contoh
No. 475 / 001 / II / 2024

### Tangkapan layar dan log error

![gambar 1](https://github.com/OpenSID/OpenSID/assets/43205017/51822671-665f-4b97-89ee-dcde3b339e8b)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2402.0.2-premium

### Tema Yang Digunakan

Batuah 23.02

### Informasi tambahan

tidak ada

**Comment by andifahruddinakas** [comment]
pak @Agungf19, apakah nomor lampiran menggunakan nomor yang sama dengan yang ada disurat keterangan?

**Comment by Agungf19** [comment]
iya pak, apakah bisa? soalnya di kantor desa pada lampiran ada nomor
suratnya jg

Pada tanggal Sen, 19 Feb 2024 09.54, Andi Fahruddin Akas <
***@***.***> menulis:

**Comment by Agungf19** [comment]
contohnya seperti ini pak

![Screenshot_1](https://github.com/OpenSID/OpenSID/assets/43205017/f910b0aa-e629-40cc-89d9-ddcd21165664)

**Comment by Agungf19** [comment]
[ket lahir, mati,f108,106, lap perbulan.pdf](https://github.com/OpenSID/OpenSID/files/14327811/ket.lahir.mati.f108.106.lap.perbulan.pdf)

**Comment by Agungf19** [comment]
itu pak untuk contoh lampiranya

**Comment by andifahruddinakas** [comment]
Penambahan ini terkait lampiran : 

- [ ] F.1-08
- [ ] F.1-27
- [ ] F.1-25
