### ISSUE TITLE
Bug/error: Strict count array php 8.x pada lampiran dengan data pengikut tidak ada

### ISSUE THREAD

**Issue by Wiliyantoro** [OpenSID/OpenSID#7722]
### Jelaskan error yg dialami

saat membuat surat pindah terjadi error pada pratinjau dan cetak surat

### Cara untuk mereplikasi errornya

1. home
2. layanan surat
3. cetak surat
4. surat keterangan pindah

### Hasil yg diharapkan

bisa pratinjau dan cetak surat pindah dengan lampiran f.103

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/44520382/4fd11493-0392-45fb-bf05-a8d05399f7c9)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

versi 2402.0.2

**Comment by andifahruddinakas** [comment]
pak @Wiliyantoro, saat terjadi error bisa unduh log nya agar dikertahui masalahnya apa. karena wesbite berputar banyak digunakan orang, kemungkinan lognya tenggelam atau terhapus.
![image](https://github.com/OpenSID/OpenSID/assets/57283157/63fd2db9-ed5d-48c5-82a7-585d55450e23)

**Comment by Wiliyantoro** [comment]
RROR - 2024-02-16 10:00:56 --> Severity: error --> Exception: syntax error, unexpected token "endif", expecting end of file (View: /home/batungsel.desa.id/public_html/resources/views/admin/setting/info_sistem/index.blade.php) /home/batungsel.desa.id/public_html/storage/framework/views/b25a363ce9932b2b038a9ff5ac6f586d216c08e9.php 379
ERROR - 2024-02-16 10:03:49 --> Severity: error --> Exception: count(): Argument #1 ($value) must be of type Countable|array, null given /home/batungsel.desa.id/public_html/storage/app/template/lampiran/f-1.03/view.php 356
ERROR - 2024-02-16 10:03:51 --> Severity: error --> Exception: count(): Argument #1 ($value) must be of type Countable|array, null given /home/batungsel.desa.id/public_html/storage/app/template/lampiran/f-1.03/view.php 356
ERROR - 2024-02-16 10:03:56 --> Severity: error --> Exception: count(): Argument #1 ($value) must be of type Countable|array, null given /home/batungsel.desa.id/public_html/storage/app/template/lampiran/f-1.03/view.php 356
ERROR - 2024-02-16 10:03:59 --> Severity: error --> Exception: count(): Argument #1 ($value) must be of type Countable|array, null given /home/batungsel.desa.id/public_html/storage/app/template/lampiran/f-1.03/view.php 356
ERROR - 2024-02-16 10:04:15 --> Severity: error --> Exception: count(): Argument #1 ($value) must be of type Countable|array, null given /home/batungsel.desa.id/public_html/storage/app/template/lampiran/f-1.03/view.php 356

ini log error yang saya ambil dari web saya,, saya ambil lewat cpanel karna tidak bisa di ambil melalui info sistem

**Comment by Wiliyantoro** [comment]
![Screenshot 2024-02-22 203328](https://github.com/OpenSID/OpenSID/assets/44520382/46bb4653-799d-4722-a20b-a926b3802826)
![Screenshot 2024-02-22 203315](https://github.com/OpenSID/OpenSID/assets/44520382/3f9471ad-20af-4c5e-9e12-075f24d41b7a)
sc di atas saat lakukan tinjau dan cetak pdf, padahal sudah versi premium terbaru rev 03
![image](https://github.com/OpenSID/OpenSID/assets/44520382/1ad04fda-3bf2-4ffe-8c8a-3d80c55ca51e)

**Comment by Wiliyantoro** [comment]
<?php defined('BASEPATH') OR exit('No direct script access allowed'); ?>

NOTICE - 2024-02-22 20:30:53 --> Berhasil Jalankan Migrasi_2024010171
NOTICE - 2024-02-22 20:30:53 --> Berhasil Jalankan Migrasi_2024020171
NOTICE - 2024-02-22 20:30:53 --> Berhasil Jalankan Migrasi_2024020751
NOTICE - 2024-02-22 20:30:53 --> Berhasil Jalankan Migrasi_2024021451
NOTICE - 2024-02-22 20:30:53 --> Berhasil Jalankan Migrasi_2024022151
NOTICE - 2024-02-22 20:30:53 --> Berhasil Jalankan migrasi_dev
NOTICE - 2024-02-22 20:30:54 --> Versi database sudah terbaru
ERROR - 2024-02-22 20:30:54 --> updateConfigFile password - **************************************
ERROR - 2024-02-22 20:32:57 --> Severity: error --> Exception: count(): Argument #1 ($value) must be of type Countable|array, null given /home/batungsel.desa.id/public_html/storage/app/template/lampiran/f-1.03/view.php 356
ERROR - 2024-02-22 20:33:19 --> Severity: error --> Exception: count(): Argument #1 ($value) must be of type Countable|array, null given /home/batungsel.desa.id/public_html/storage/app/template/lampiran/f-1.03/view.php 356

ini log error

**Comment by Wiliyantoro** [comment]
https://forum.opendesa.id/d/322-lampiran-f103-error-saat-di-pratinjau-dan-cetak-surat

**Comment by andifahruddinakas** [comment]
selesai melalui commit https://github.com/OpenSID/premium/commit/e4e971b30a36b1676241a97963a1124a039aaf26
