### ISSUE TITLE
Bug/error: Halaman Galeri tidak muncul

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#7730]
### Jelaskan error yg dialami

walau sudah upload di menu galeri dan membuat menu nya, halaman galeri tetap tidak menampilkan gambar.

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

normal kembali

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Berputar

**Comment by yogiperdana** [comment]
Mohon maaf bisa dijelaskan dengan lebih spesifik maksudnya pak

**Comment by ariandii** [comment]
bisa di tes buka https://berputar.opendesa.id/galeri
