### ISSUE TITLE
Permintaan fitur: Pengaturan header dengan halaman yg bisa ditentukan

### ISSUE THREAD

**Issue by dwidita** [OpenSID/OpenSID#7731]
### Apa kekurangan yg ingin diatasi?

Kop surat bisa di pilih halaman yang di perlukan

### Jelaskan solusi yg diinginkan

Surat ada 3 halaman,  yg pakai kop surat halaman 1, dan 3 , halaman 2 egak pakai kop , pertanyaan bagai mana cara halaman 2 egak pakai kop surat mohon arahan

### Apakah ada alternatif lain

Karena setiap halaman TDK mesti ada kop

### Untuk versi OpenSID mana

240300

### Informasi tambahan

TDK ada

**Comment by pandigresik** [comment]
Untuk case seperti diatas sepertinya bisa dilakukan dengan menyesuaikan template saja, serta menonaktikan header (Tampilkan Header, pilih tidak ) untuk surat tersebut

[Screencast from 02-05-24 13:28:42.webm](https://github.com/OpenSID/OpenSID/assets/1853475/7985826c-6062-4f6c-9f0b-eca51b3a7d14)

**Comment by andifahruddinakas** [comment]
> Untuk case seperti diatas sepertinya bisa dilakukan dengan menyesuaikan template saja, serta menonaktikan header (Tampilkan Header, pilih tidak ) untuk surat tersebut
> 
>  Screencast.from.02-05-24.13.28.42.webm

mas @rgrahardi, bisa masukkan panduan.
