### ISSUE TITLE
Bug/error: GALERI

### ISSUE THREAD

**Issue by redhousman** [OpenSID/OpenSID#7732]
### Jelaskan error yg dialami

Pada Menu Galeri sudah dibuatkan, namun masih terjadi kesalahan 404

### Cara untuk mereplikasi errornya

![issue](https://github.com/OpenSID/OpenSID/assets/141497405/b2dc330c-e085-4385-8b44-d2b0fd88559b)

### Hasil yg diharapkan

![Galeri_foto](https://github.com/OpenSID/OpenSID/assets/141497405/d9f74aef-0df5-4b1a-99a3-fa769a1fdba2)

### Tangkapan layar dan log error

![info_sistem](https://github.com/OpenSID/OpenSID/assets/141497405/faf1bbc5-8305-45c4-921e-18d0d20373c4)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2402.0.3

### Tema Yang Digunakan

DeNava v10.1

**Comment by andifahruddinakas** [comment]
Duplicate issue https://github.com/OpenSID/OpenSID/issues/7730
