### ISSUE TITLE
Bug/error: Pencarian kumpulan KK belum bisa

### ISSUE THREAD

**Issue by achunp** [OpenSID/OpenSID#7735]
### Jelaskan error yg dialami

Saat memasukkan beberapa No, KK sesuai format yang disediakan, Pilihan Kumpulan KK tidak bisa ditampilkan hasilnya

### Cara untuk mereplikasi errornya

    private function kumpulan_kk_sql()
    {
        if (empty($this->session->kumpulan_kk)) {
            return;
        }

        $kumpulan_kk                = preg_replace('/[^0-9\,]/', '', $this->session->kumpulan_kk);
        $kumpulan_kk                = array_filter(array_slice(explode(',', $kumpulan_kk), 0, 20)); // ambil 20 saja
        $kumpulan_kk                = implode(',', $kumpulan_kk);
        $this->session->kumpulan_kk = $kumpulan_kk;
        **$this->db->where_in('u.no_kk ', $kumpulan_kk);**
    }

### Hasil yg diharapkan

Pencarian kumpulan KK belum bisa, semoga ketika di rilis bulan 3 sudah bisa menggunakan pencarian kumpulan KK dengan mengubah baris ke-123 pada folder donjo-app-->models-->keluarga_model.php menjadi :
$this->db->where("u.no_kk in ({$kumpulan_kk})");

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/54380652/0afe23d5-7638-4978-a2c3-7dbc29d08e32)

### Rilis Versi OpenSID

Rilis Umum

### Versi OpenSID

Versi 2402.0.0

### Tema Yang Digunakan

tema silir 4.7

**Comment by andifahruddinakas** [comment]
Untuk meminimalisir kesalahan inputan, bisa gunakan select2-tags.
Contoh : 
![image](https://github.com/OpenSID/OpenSID/assets/57283157/ec9b24b5-4608-402b-84e9-d7a3330f7dfe)

sehingga pada query tidak perlu banyak diubah.
```
private function kumpulan_kk_sql()
{
    if (empty($this->session->kumpulan_kk)) {
        return;
    }

    $kumpulan_kk                = preg_replace('/[^0-9\,]/', '', $this->session->kumpulan_kk);
    $kumpulan_kk                = implode(',', $kumpulan_kk);
    $this->session->kumpulan_kk = $kumpulan_kk;
    **$this->db->where_in('u.no_kk ', $kumpulan_kk);**
}
```

Tambahan : 
- [ ] tambahkan validasi data yg diinput hanya berupa angka saja dan tidak kurang / lebih dari 16 digit tiap datanya
- [ ] batasi jumlah data yg diinput tidak lebih dari 20 data (nik)
