### ISSUE TITLE
Surat Keluar tidak dapat ditambahkan ke Buku Ekspedisi

### ISSUE THREAD

**Issue by pujocahyono** [OpenSID/OpenSID#7739]
### Jelaskan error yg dialami

Saat klik tombol **Tambahkan ke Buku Ekspedisi** di arahkan ke Buku Ekspedisi. Tapi tidak muncul surat tersebut

### Cara untuk mereplikasi errornya

1. Buku Administrasi Desa
2. Administrasi Umum
3. Buku Agenda - Surat Keluar

### Hasil yg diharapkan

Buku ekspedisi terisi normal

### Tangkapan layar dan log error

![Cuplikan layar 2024-02-28 085152](https://github.com/OpenSID/OpenSID/assets/87228587/f47c2836-d5e3-4e4b-8e84-748c7b91e001)
![Cuplikan layar 2024-02-28 085831](https://github.com/OpenSID/OpenSID/assets/87228587/07ae8503-f660-4585-a59e-40348129d102)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2402.0.3 dan 2402.1.0

**Comment by andifahruddinakas** [comment]
Sudah disesuaikan melalui commit https://github.com/OpenSID/premium/commit/538c52e21baa18726e05878a6d4981f602143164 sebagai susulan perbaikan dari konversi orm ekspedisi.

bisa di cek ulang di beta.opendesa.id
