### ISSUE TITLE
Bug/error: tidak bisa import peserta bantuan

### ISSUE THREAD

**Issue by Agungf19** [OpenSID/OpenSID#7740]
### Jelaskan error yg dialami

error saat coba impor data peserta bantuan pakek format excel
tp data masuk

saya coba di berputar demo

### Cara untuk mereplikasi errornya

coba aja sendiri

### Hasil yg diharapkan

perbaiki

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/43205017/987241f9-3106-46fa-a623-ab13be280f0c)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2402.0.3

### Tema Yang Digunakan

-

### Informasi tambahan

-

**Comment by andifahruddinakas** [comment]
Termasuk:
![image](https://github.com/OpenSID/OpenSID/assets/57283157/774d3282-403e-4294-ad76-4b2e7fc6cdea)
`Severity: error --> Exception: in_array(): Argument #2 ($haystack) must be of type array, null given /home/berputar.opendesa.id/public_html/donjo-app/core/MY_Log.php(206) : eval()'d code(1) : eval()'d code 440`
