### ISSUE TITLE
Permintaan fitur:  mohon segera ubah format surat keterangan kelahiran model F-2.01 Karena sudah tidak sesuai dengan ketetapan dukcapil

### ISSUE THREAD

**Issue by utay-cugung** [OpenSID/OpenSID#7742]
### Apa kekurangan yg ingin diatasi?

format kelahiran f-2.01 yang tersedia sekarang tidak sesuai dengan 

ini format yang saat ini di opensid
![image](https://github.com/OpenSID/OpenSID/assets/155012206/755eaef2-0516-4f48-9707-9b0f082f16ca)

[sampel kelahiran asli.pdf](https://github.com/OpenSID/OpenSID/files/14434931/sampel.kelahiran.asli.pdf)

### Jelaskan solusi yg diinginkan

sesuaikan dengan permintaan dukcapil saat ini 
[Blangko permohonan kelahiran terlambat lampung selatan.pdf](https://github.com/OpenSID/OpenSID/files/14434912/Blangko.permohonan.kelahiran.terlambat.lampung.selatan.pdf)

### Apakah ada alternatif lain

tidak ada, karena rata-rata kabupaten menggunakan format seperti yang di minta

### Untuk versi OpenSID mana

semua versi

### Informasi tambahan

format yang tidak sesuai berakibat di tolaknya permohonan layanan akta kelahiran

**Comment by balongbesuk** [comment]
justru blanko yang bapak lampirkan itu versi yang lama, cek aja opensid 2020

**Comment by balongbesuk** [comment]
[#5654](https://github.com/OpenSID/OpenSID/issues/5654)

isu update blanko terbaru menyesuaikan Permendagri Nomor 109 Tahun 2019

**Comment by utay-cugung** [comment]
oke,, maaf akibat malas baca
