### ISSUE TITLE
Bug/error: kode surat tidak muncul

### ISSUE THREAD

**Issue by Zxce3** [OpenSID/OpenSID#7745]
### Jelaskan error yg dialami

saat cetak surat `[kode_surat]` tidak muncul

### Cara untuk mereplikasi errornya

Pergi ke halaman pengaturan surat > edit surat > tinjau pdf
atau
pergi ke halaman cetak surat > buat surat > cetak pdf

### Hasil yg diharapkan

Di perbaiki

### Tangkapan layar dan log error

![screen59](https://github.com/OpenSID/OpenSID/assets/57337800/a616198a-e22e-4abf-b91f-bfc3db7b13e2)

### Rilis Versi OpenSID

Rilis Umum

### Versi OpenSID

Versi 2402.1.0

### Tema Yang Digunakan

Esensi

### Informasi tambahan

Kemungkinan masalahnya di bagian tinymce atau fungsi cetak pdf nya

**Comment by andifahruddinakas** [comment]
Silahkan di update ke v2403.0.0

**Comment by Zxce3** [comment]
tetap sama, nomor surat tidak muncul

![screen63](https://github.com/OpenSID/OpenSID/assets/57337800/76ecfd5d-8fb2-4fca-b947-fa9a5b2f9750)

**Comment by Zxce3** [comment]
@andifahruddinakas 



> tetap sama, nomor surat tidak muncul
> 
> ![screen63](https://private-user-images.githubusercontent.com/57337800/311431426-76ecfd5d-8fb2-4fca-b947-fa9a5b2f9750.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4MTcxNjIsIm5iZiI6MTcxMDgxNjg2MiwicGF0aCI6Ii81NzMzNzgwMC8zMTE0MzE0MjYtNzZlY2ZkNWQtOGZiMi00ZmNhLWI5NDctZmE5YTViMmY5NzUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDAyNTQyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmZTZhYzQ1NzUyMDhmNTZlMjA4YzFhZmUyZGE3NDc5ZTQxM2UxMzE4MGQ1NDBhMzVjMmI2YTg2NmFjMjUxOTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VE5Hk6RAFZD9XM66aYX2SA5X7-pTUzgOLDpp96ebtIg)
