### ISSUE TITLE
Bug/error: di menu jenis bantuan tidak bisa tampil form input sasaran per jenis program

### ISSUE THREAD

**Issue by Desasukomangu-wq** [OpenSID/OpenSID#7746]
### Jelaskan error yg dialami

Bug/error: di menu jenis bantuan tidak bisa tampil form input sasaran per jenis program

### Cara untuk mereplikasi errornya

![Screenshot_20240229-095609](https://github.com/OpenSID/OpenSID/assets/83177852/6ce58acd-c10a-45b7-be9d-ebde57c2cbb6)

### Hasil yg diharapkan

Imput sasaran yang menerima jenis bantuan

### Tangkapan layar dan log error

![Screenshot_20240229-095918](https://github.com/OpenSID/OpenSID/assets/83177852/0987d4cb-e8d1-49c8-9493-67141c8bc982)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2402.0.0

### Tema Yang Digunakan

Natra v2401. 0.0

### Informasi tambahan

Per jenis bantuan mustinya bisa input daftar penerima

**Comment by andifahruddinakas** [comment]
Silahkan di update ke v2403.0.0
