### ISSUE TITLE
Upgrade CI Ke Versi 3 Dong

### ISSUE THREAD

**Issue by alsyundawy** [OpenSID/OpenSID#775]
CodeIgniter 2.x
CodeIgniter 2.2.6 is the legacy version of the framework.

The 2.x branch was originally released January 2011, the next major update (2.1.0) came in the fall of 2011, version (2.2.0) came out in July 2014, and the current version (2.2.6) came out in October 2015.

CodeIgniter 2 has reached its end-of-life for support and updates, as of October 31, 2015. No further updates are planned.
We encourage you to upgrade to CodeIgniter 3.x!

**Comment by eddieridwan** [comment]
@alsyundawy 👍 silakan ikut bantu! Mungkin anda bisa kerjakan? Tanpa bantuan teman2 seperti anda, pekerjaan rumah seperti ini tidak akan pernah bisa dilakukan (karena tidak akan diprioritaskan oleh Pokja Analisis Kebutuhan yang mewakili para pengguna).

**Comment by eddieridwan** [comment]
Sudah dikerjakan oleh programmer kenalan Syaifuddin Said, yang akan mengerjakan modernisasi tampilan modul Admin.

Sudah dicommit ke master.
