### ISSUE TITLE
Template Bawaan Surat Dinas

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#7765]
Terdapat beberapa template surat yang bisa di ikutkan sebagai template standar di OpenSID.

- [ ] Keputusan
- [ ] Tugas
- [ ] Nota Dinas
- [ ] Memo
- [ ] Disposisi
- [ ] Surat Kuasa Biasa
- [ ] Surat Dinas
- [ ] Surat Undangan
- [ ] Surat Pengantar Dinas
- [ ] Surat Keterangan Dinas
- [x] #8143

**Comment by andifahruddinakas** [comment]
Untuk sementara contoh template disediakan hanya 1 saja. jika ada permintaan lain, bisa dibuat issue terpisah.

**Comment by luxmant354** [comment]
> Untuk sementara contoh template disediakan hanya 1 saja. jika ada permintaan lain, bisa dibuat issue terpisah.

mungkin bisa untuk referensi tambahan contoh surat dinas ada dilampiran perbup
chrome-extension://efaidnbmnnnibpcajpcglclefindmkaj/https://jdih.mojokertokab.go.id/pencarian/MjYw/cGVyYnVwIE5vIDI4IDIwMjIgdHRnIHBlZG9tYW5hbiB0YXRhIG5hc2thaCBkaW5hcyBkaSBkZXNhLnBkZg==/8/download

**Comment by andifahruddinakas** [comment]
![image](https://github.com/OpenSID/OpenSID/assets/57283157/0e80ca12-91c7-40bf-b6f3-1a44a680b65b)

**Comment by andifahruddinakas** [comment]
> ![image](https://private-user-images.githubusercontent.com/57283157/346633447-0e80ca12-91c7-40bf-b6f3-1a44a680b65b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0NTQ1MTAsIm5iZiI6MTcyMDQ1NDIxMCwicGF0aCI6Ii81NzI4MzE1Ny8zNDY2MzM0NDctMGU4MGNhMTItOTFjNy00MGJmLWI2ZjMtMWE0NGE2ODBiNjViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA4VDE1NTY1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYzNjQ5ZTQ3NTYwMGE1OWM1M2Y3YjdmNTNjN2JmZDJjMzYxNjUxZjg1ZDUwMzc3OGQzZWFkOTU0Mzk5OTg5YzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._rY3vAVWiZ1fEQ7pQmlYhFq6fm7hP15OCFs8lqGsFJM)

pak @luxmant354, dari daftar tsb, yg mana sering digunakan oleh desa?

**Comment by luxmant354** [comment]
> > ![image](https://private-user-images.githubusercontent.com/57283157/346633447-0e80ca12-91c7-40bf-b6f3-1a44a680b65b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0NTQ1MTAsIm5iZiI6MTcyMDQ1NDIxMCwicGF0aCI6Ii81NzI4MzE1Ny8zNDY2MzM0NDctMGU4MGNhMTItOTFjNy00MGJmLWI2ZjMtMWE0NGE2ODBiNjViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA4VDE1NTY1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYzNjQ5ZTQ3NTYwMGE1OWM1M2Y3YjdmNTNjN2JmZDJjMzYxNjUxZjg1ZDUwMzc3OGQzZWFkOTU0Mzk5OTg5YzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._rY3vAVWiZ1fEQ7pQmlYhFq6fm7hP15OCFs8lqGsFJM)
> 
> pak @luxmant354, dari daftar tsb, yg mana sering digunakan oleh desa?

yang paling sering :

- Surat Perintah Tugas
- Surat Perjanjian
- Surat Undangan
- Surat Laporan
- Berita Acara
- Notulen dan
- Daftar Hadir
