### ISSUE TITLE
Bug/error: cetak prelis DTKS error

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#7767]
### Jelaskan error yg dialami

ketika mau cetak prelis dtks error

### Cara untuk mereplikasi errornya

Proses cetak dapat memakan waktu cukup lama dan memerlukan halaman ini untuk tetap terbuka
![Screenshot 2024-03-07 075047](https://github.com/OpenSID/OpenSID/assets/25834335/93832755-18f4-4da8-9211-1a7dd44ed8e5)
![Screenshot 2024-03-07 075055](https://github.com/OpenSID/OpenSID/assets/25834335/194f9c86-0f71-4b68-9bb9-b64973cdcfba)

### Hasil yg diharapkan

normal seperti sebelumnya
![Screenshot 2024-03-07 075415](https://github.com/OpenSID/OpenSID/assets/25834335/e4063b30-c4b6-4212-9aa8-46ab9bb2c26f)

### Tangkapan layar dan log error

![Screenshot 2024-03-07 075055](https://github.com/OpenSID/OpenSID/assets/25834335/ff2409c1-36fd-4254-9600-af51448ce2cb)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

403.0.0-premium

### Tema Yang Digunakan

DeNava

**Comment by MUHAMMADRANGSEL** [comment]
semoga cepat terealisasi, pantesan keamrin pas dibuka waktu ada kunjugan dari Bappenas Tidak bisa

**Comment by andifahruddinakas** [comment]
cek juga:
tambah data baru jadi 4040
![image](https://github.com/OpenSID/OpenSID/assets/57283157/80bc9053-d075-47e3-9dd9-ca7d03751f4e)

**Comment by MUHAMMADRANGSEL** [comment]
saya cek didemo Versi 2403.0.1-premium hasilnya ketika cetak prelis kosong seperti gambar dibawah ini
![Screenshot 2024-03-16 020939](https://github.com/OpenSID/OpenSID/assets/25834335/1daaab8b-070d-4827-ba44-d77f1f6b97d9)
