### ISSUE TITLE
cara membuat installer atau copy folder xammp

### ISSUE THREAD

**Issue by Cakwidod** [OpenSID/OpenSID#777]
cara Menjalankan Xampp
=======================FOLDER "htdocs" MASIH KOSONG.....SILAHKAN ISI APLIKASI OPENSID=================================
langkah-langkahnya :
tanpa membuat installer (copy langsung foldernya):

1.letakan folder "sid-pgn" di C: (system)
2.isikan semua aplikasi Opensid kedalam folder "htdocs"
3.buka "xampp-control"
4.centang kotak "apache" dan "Mysql" (dua kotak teratas)
5.jalankan keduanya (klik tulisan "stop") kalau sudah berjalan akan ada warna hijaunya
6.jika sudah berjalan keduanya tutup "xampp-control" dengan klik "exit"

membuat installer :
1.letakan folder "sid-pgn" laptop/komputer anda (jangan di C)
2.isikan semua aplikasi Opensid kedalam folder "htdocs"
3."xampp-control" kondisi tidak aktif
4.buat instaler dengan menggunakan "rar sfx" (jangan lupa setting otomatis path di C:)
5.cari panduan cara membuat extention (.exe) dengan "rar" sfx
6.klik "ok" untuk menjalankan paket instalasi "rar sfx"
7 tunggu sampai selesai, pakaet installasi ber extention .exe bisa dijalankan
8.buka "xampp-control" di C:sid-pgn
9.centang kotak "apache" dan "Mysql" (dua kotak teratas)
10.jalankan keduanya (klik tulisan "stop") kalau sudah berjalan akan ada warna hijaunya
6.jika sudah berjalan keduanya tutup "xampp-control" dengan klik "exit"

untuk xampp silahkan download https://drive.google.com/open?id=17-wDzdcxc1QQMLJiogjDDo11lwSrud0O

**Comment by metalab25** [comment]
Berikut ini saya buatkan Installer OpenSID 2.9 yang sudah include database contoh yang sudah terimport.
Installer ini akan memudahkan pengguna baru dalam proses installasi awal OpenSID

http://www.opensid.info/OpenSID.2.9-VC9-installer.exe

**Comment by afa28** [comment]
https://github.com/OpenSID/OpenSID/wiki/Pembuatan-Installer-Menggunakan-Innosetup
