### ISSUE TITLE
Error 404 saat mengurutkan data berdasarkan tanggal terdaftar pada menu Rumah Tangga

### ISSUE THREAD

**Issue by pujocahyono** [OpenSID/OpenSID#7771]
### Jelaskan error yg dialami

Error 404 saat mengurutkan data berdasarkan tanggal terdaftar pada menu Rumah Tangga

### Cara untuk mereplikasi errornya

1. Menu Rumah Tangga
2. Urutkan data dengan klik pada **TANGGAL TERDAFTAR**
![Cuplikan layar 2024-03-07 151741](https://github.com/OpenSID/OpenSID/assets/87228587/bcac38ed-e8d3-4ed5-a90b-8dc5aa86b999)

### Hasil yg diharapkan

Tidak error

### Tangkapan layar dan log error

![Cuplikan layar 2024-03-07 151725](https://github.com/OpenSID/OpenSID/assets/87228587/bcc262b7-21c4-4e2f-b5dd-da76c72d005a)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2403.0.0

**Comment by andifahruddinakas** [comment]
perbaikan melalui konversi
