### ISSUE TITLE
Bug/error: pilihan tanggal tidak tampil

### ISSUE THREAD

**Issue by INaon** [OpenSID/OpenSID#7773]
### Jelaskan error yg dialami

saat membuat surat baru tinyMCE yang ada pilihan tanggal, ketika memilih tanggal pilihan tanggal tidak muncul

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

![yang di harpakn](https://github.com/OpenSID/OpenSID/assets/65794146/d1572d27-4459-4db5-9ebd-64bee64dc604)

ada pilihan tanggal, seperti surat bawaan sistem pilihan tanggal tampil

### Tangkapan layar dan log error

![surat baru](https://github.com/OpenSID/OpenSID/assets/65794146/9aeced0c-c612-47be-ab03-d29de0dd99b7)
saat membuat surat baru pilihan tanggal tidak tampil

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

24.03

**Comment by andifahruddinakas** [comment]
saya coba bisa.
![image](https://github.com/OpenSID/OpenSID/assets/57283157/b95b5f1f-1d12-46c9-800d-a1016bd3f1e4)

mas @INaon, sertakan template surat yang dibuat untuk dicek.
