### ISSUE TITLE
Terjadi error 404 saat menambah foto pembagunan 

### ISSUE THREAD

**Issue by mranca** [OpenSID/OpenSID#7775]
### Jelaskan error yg dialami

Terjadi error 404

### Cara untuk mereplikasi errornya

1. Mask admin
2. Pembagunan
3. Klik rincian detail pembangunan
4. Tambahkan foto 

### Hasil yg diharapkan

.

### Tangkapan layar dan log error

![Screenshot_20240312_180742](https://github.com/OpenSID/OpenSID/assets/76085245/bee94fb6-f681-437e-95fe-8fea4eebdbb8)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Terbaru

### Tema Yang Digunakan

.

### Informasi tambahan

.

**Comment by habibie11** [comment]
cek diberputar, bisa. cc mas @andifahruddinakas 
![image](https://github.com/OpenSID/OpenSID/assets/56639378/e45eaba3-29f2-4f6b-8cc6-4e3a9fbbef28)

**Comment by mranca** [comment]
@habibie11 kalau di foto pembangunan upload menggunakan hp atau mobile tidak bisa pak terjadi error. Dan kalau menggunakan pc berjalan normal

**Comment by habibie11** [comment]
> @habibie11 kalau di foto pembangunan upload menggunakan hp atau mobile tidak bisa pak terjadi error. Dan kalau menggunakan pc berjalan normal

oke, noted.
