### ISSUE TITLE
Bug/error : Jumlah perempuan pada Menu Wilayah Administratif kosong

### ISSUE THREAD

**Issue by rockymakasar** [OpenSID/OpenSID#7776]
### Jelaskan error yg dialami

![image](https://github.com/OpenSID/OpenSID/assets/94730877/e2cd950e-1588-43f8-baa3-1ec4211035bc)

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

Normal

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2403.0.0-premium

### Tema Yang Digunakan

-

### Informasi tambahan

-

**Comment by andifahruddinakas** [comment]
Duplicate issue https://github.com/OpenSID/OpenSID/issues/7751
