### ISSUE TITLE
EROR SAAT TAMBAH ANGGOTA KELUARGA

### ISSUE THREAD

**Issue by pujocahyono** [OpenSID/OpenSID#7777]
### Jelaskan error yg dialami

EROR SAAT TAMBAH ANGGOTA KELUARGA
![Cuplikan layar 2024-03-15 101217](https://github.com/OpenSID/OpenSID/assets/87228587/7db402ca-aa55-4798-b858-373c6ad93928)

### Cara untuk mereplikasi errornya

MENU KELUARGA
TAMBAH ANGGOTA KELUARGA MASUK

### Hasil yg diharapkan

BERJALAN NORMAL

### Tangkapan layar dan log error

![Cuplikan layar 2024-03-15 101315](https://github.com/OpenSID/OpenSID/assets/87228587/6d476d8f-b82f-45cc-ab7c-b351e014232a)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2403.0.1

**Comment by andifahruddinakas** [comment]
https://github.com/OpenSID/rilis-premium
