### ISSUE TITLE
Bug/error: Halaman Pendaftar Layanan mandiri error setelah penduduk yang terdaftar dihapus

### ISSUE THREAD

**Issue by pandigresik** [OpenSID/OpenSID#7779]
### Jelaskan error yg dialami

Halaman pendaftar layanan mandiri error jika penduduk yang telah terdaftar di layanan mandiri dihapus melalui menu kependudukan

### Cara untuk mereplikasi errornya

1. Menu kependudukan - penduduk
2. Pilih icon gear (pengaturan) pada pojok kanan atas
3. Ubah pengaturan data lengkap menjadi tidak
4. Pergi ke menu layanan mandiri - pendaftar layanan mandiri
5. Salin nik salah satu penduduk yang telah terdaftar
6. Kembali ke menu kependudukan - penduduk
7. Cari nik yang disalin tadi
8. Hapus penduduk yang memiliki nik tersebut
9. Buka kembali halaman layanan mandiri - pendaftar layanan mandiri
10. Terjadi error pada datatable

### Hasil yg diharapkan

Tidak ada error

### Tangkapan layar dan log error

[Screencast from 16-03-24 06:14:15.webm](https://github.com/OpenSID/OpenSID/assets/1853475/a6fc26ef-a709-446f-ad04-d2161051c0ae)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v2403.0.1-premium

### Informasi tambahan

Pastikan pengaturan data lengkap penduduk telah diset menjadi tidak, agar tombol hapus muncul

**Comment by eddieridwan** [comment]
@andifahruddinakas @vickyrolanda seharusnya penduduk HANYA dihapus jika salah mengisi. Penduduk yg sudah digunakan dalam berbagai relasi, seperti layanan mandiri seharusnya TIDAK boleh dihapus (karena menunjukkan penduduk sebenarnya -- tidak salah buat). Penduduk tersebut hanya dapat dikeluarkan dari daftar penduduk 'hidup' dengan melalukan mutasi meninggal, pindah atau hilang. 

**Yaitu penduduk yg boleh dihapus hanya yang belum ada kegiatan, yaitu belum ada bantuan, layanan mandiri, data suplemen atau lainnya**.  Meskipun data dinyatakan belum lengkap, ketentuan itu tetap berlaku. Jadi jika pengguna bersikeras ingin menghapus penduduk tersebut, perlu menghapus semua data terkait itu dulu.

Untuk issue ini, terapkan ketentuan tersebut. Dan pada waktu pengguna berusaha menghapus, beri notifikasi popup berisi informasi di atas. Supaya pengguna harus klik 'ok' untuk menunjukkan telah membaca.

**Comment by andifahruddinakas** [comment]
Bisa cek yang diterapkan saat proses impor
![image](https://github.com/OpenSID/OpenSID/assets/57283157/8f7da5c1-e161-48f2-9fbd-455c1d980876)
