### ISSUE TITLE
Kasus Baru Surat Permohonan Kelahiran

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#778]
Hari ini ada warga desa kami yang memohon pengajuan akta anaknya, datanya seperti terlampir,
dalam hal ini istri menikah untuk ketiga kalinya (pertama siri, kedua siri)

![tesslide2](https://user-images.githubusercontent.com/35319600/35786835-97e5f104-0a5c-11e8-8aaf-12b375d7c28c.jpg)

permasalahan muncul pada surat keterangan kelahiran

ketika memilih nama ibu, otomatis terpilih nama ayah dalam kk

![tesslide](https://user-images.githubusercontent.com/35319600/35787054-02faaaa6-0a5e-11e8-9261-ce2716e360ab.jpg)

Solusi masalah, bisa buatkan opsi untuk memilih ayah diluar data penduduk

**Comment by suphm** [comment]
bisa diubah dulu status hubungan keluarga.

**Comment by eddieridwan** [comment]
Jadi maksudnya supaya membedakan ayah/ibu kandung dengan ayah/ibu tiri? Penkode-an Status Hubungan Dalam Keluarga dari Disdukcapil tidak mengenal perbedaan ini. 

Tapi mungkin kita bisa tambahkan kolom di data penduduk supaya merekam apa hubungan anak dengan ayah/ibu di keluarganya, dan kalau perlu mengaitkan dengan data ayah/ibu kandungnya.

**Comment by dankrez48** [comment]
bukankah solusinya bisa dengan input manual?
pilih pada data ibu kandung "TIDAK TERDATA" maka data si ibu dan "sang ayah" pun bisa diisi manual.
