### ISSUE TITLE
Bug/error: Failed to load resource: the server responded with a status of 500 (Internal Server Error)

### ISSUE THREAD

**Issue by aryateya** [OpenSID/OpenSID#7782]
### Jelaskan error yg dialami

saat mengubah APBDES manual input pada sub menu pengaturan yang ada pada menu admin web menjadi tampil atau ya, halaman awal web menjadi error tidak muncul apa apa

### Cara untuk mereplikasi errornya

pergi ke halaman pengaturan yang ada pada menu Admin web, lalu ubah PBDES manual input menjadi ya, lalu simpan, lalu pergi ke halaman awal website

### Hasil yg diharapkan

grafik apbdes muncul

### Tangkapan layar dan log error

![Screenshot_2](https://github.com/OpenSID/OpenSID/assets/73771366/4c865567-919a-4d47-81c5-6eb164da4d96)

### Rilis Versi OpenSID

Rilis Umum

### Versi OpenSID

Rilis umum v22.04

**Comment by andifahruddinakas** [comment]
silahkan cek error lognya dan lampirkan

**Comment by aryateya** [comment]
error log terakhir hanya memunculkan bulan januari kemarin
sedangkan yang sekarang itu bulan maret
