### ISSUE TITLE
Permintaan fitur: Tambahkan Pilihan Isian Non Warga

### ISSUE THREAD

**Issue by RomziJazz** [OpenSID/OpenSID#7787]
### Apa kekurangan yg ingin diatasi?

Sementara ini pilihan isian Non Warga Hanya mencakup pilihan Standar

![image](https://github.com/OpenSID/OpenSID/assets/65128302/9d89e337-d593-4aeb-a212-7786f9ced417)

### Jelaskan solusi yg diinginkan

Mohon Di Tambahkan Status Perkawinan, Status Hubungan dalam Keluarga, No Pasport, Nama Ayah Ibu. (Paling tidak sesuai isi KK Lengkap)

![image](https://github.com/OpenSID/OpenSID/assets/65128302/d7953ac0-708b-401b-bd92-88089ef71048)

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

2304.00 Premium

### Informasi tambahan

Usulan ini berdasarkan pada penggunaan surat penduduk luar desa yang kurang pada form status kawin.

**Comment by andifahruddinakas** [comment]
1. Tambahkan kode isian penduduk luar, sesuai isian yang dibutuhkan pada Kartu Keluarga : 

- [ ] Golongan Darah
- [ ] Status Perkawinan
- [ ] Tanggal Perkawinan
- [ ] Status Hubungan Dalam Keluarga
- [ ] No. Paspor
- [ ] No. KITAS / KITAP
- [ ] Nama Ayah
- [ ] Nama Ibu

2. Lakukan test pada kode isian tsb.
