### ISSUE TITLE
Bug/error: Lampiran Surat TinyMCE Data Hilang setelah di Verifikasi (Lampiran lebih dari satu) dan Data Saksi di Lampiran F-2.01 tidak tampil (Modul TTE Aktif) 

### ISSUE THREAD

**Issue by langonsari** [OpenSID/OpenSID#7788]
### Jelaskan error yg dialami

1. Lampiran Kedua dan Seterusnya untuk Surat Keterangan Kematian dan Surat Keterangan lainnya yang memiliki Lampiran lebih dari satu data setelah Cetak Muncul namun setelah diverifikasi data blank
2. Lampiran F-2.01 Data Saksi yang diinput dari Data Penduduk tidak muncul

Contoh Surat Kematian:
#**Setelah Cetak**
![image](https://github.com/OpenSID/OpenSID/assets/96863107/b6a782c9-23ec-42b5-a0e8-e4f9e26da26e)

#**Setelah Verifikasi Operator dan Verifikasi Kades**
![image](https://github.com/OpenSID/OpenSID/assets/96863107/da13a3c5-b196-4a37-9de5-a222d0ef6e7c)

### Cara untuk mereplikasi errornya

replikasi untuk Data Saksi yang tidak muncul dengan mengubah di data.php  
- Saksi 1 $input['id_pend_Saksi_I'] diubah menjadi huruf kecil semua $input['id_pend_saksi_i']
- Saksi 1 $input['id_pend_Saksi_II'] diubah menjadi huruf kecil semua $input['id_pend_saksi_ii']

![image](https://github.com/OpenSID/OpenSID/assets/96863107/7399eeda-0fab-47a4-bf00-c268561fd324)

### Hasil yg diharapkan

1. Data Lampiran dapat terus tampil setelah di Verifikasi & di TTE
2. Saksi di Lampiran F-2.01 dapat ditampilkan tanpa adanya replikasi

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/96863107/e66ded94-162d-4cac-b591-8f6cc0642b2f)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

V2403.0.2

### Tema Yang Digunakan

Denava

### Informasi tambahan

-

**Comment by andifahruddinakas** [comment]
Terlihat penamaan kategori tidak di konversi menggunakan huruf keci.
![image](https://github.com/OpenSID/OpenSID/assets/57283157/ba07a2e7-8219-4bb6-9d2d-1d33085b688d)

Solusi : 
- [ ] penamaan kategori baik di form_isian dan kode_isian di buat huruf kecil
- [ ] sesuaikan template surat bawaan (surat keterangan kematian, Pernyataan Penguasaan Fisik Bidang Tanah SPORADIK, Keterangan KelahiranKeterangan Kelahiran)
![image](https://github.com/OpenSID/OpenSID/assets/57283157/8c7c6c54-5d61-49dd-8d6c-a2659fdf5968)

- [ ] pada lampiran dengan variabel bukan huruf kecil diganti jadi huruf kecil
![image](https://github.com/OpenSID/OpenSID/assets/57283157/d86a9870-641d-471f-9418-8c9239d3b118)
