### ISSUE TITLE
Bug: user tidak bisa login kalau pergi ke menu di mana user tsb tidak mempunyai akses

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#779]
di versi 2.9 ketika membuat user/ pengguna status operator redaksi dan konributor hanya bisa masuk 1 kali dan setelah itu mengalami gagal seperti yang sekarang ada sid.bangundesa.info tadi saya sudah tambahkan user dengan username operator paswood operator hanya bisa masuk satu kali dan setelah itu gagal terus
![image](https://user-images.githubusercontent.com/25834335/35843093-435d43e0-0b41-11e8-9136-22dcda5cdae8.png)

mohon di perbaiki

**Comment by MUHAMMADRANGSEL** [comment]
diversi sebeumnya tidak bermaslah

**Comment by eddieridwan** [comment]
Baru saja mencoba di sid.bangundesa.info. Login operator beberapa kali. Tidak ada masalah.
Yakinkan username/password terisi benar.

Tidak ada perubahan di v2.9 yang mempengaruhi login.

**Comment by MUHAMMADRANGSEL** [comment]
Saya juga bingung mas Eddie tadi saya menambahkan pengguna baru hanya bisa
masuk 1 kali dan selanjutnya TDK bisa

Pada tanggal 6 Feb 2018 2.45 PM, "Eddie Ridwan" <notifications@github.com>
menulis:

**Comment by MUHAMMADRANGSEL** [comment]
Coba nanti saya coba lagi mas eddie

Pada tanggal 6 Feb 2018 6.05 PM, "MUHAMMAD SPD" <muhammadrangsel@gmail.com>
menulis:

**Comment by MUHAMMADRANGSEL** [comment]
Sudah saya coba mas Eddie hasilnya tetep aja sama, bisa masuk 1 kali pada
waktu klik salah satu menu kembali ke login lagi

Pada tanggal 6 Feb 2018 6.10 PM, "MUHAMMAD SPD" <muhammadrangsel@gmail.com>
menulis:

**Comment by eddieridwan** [comment]
Masalah ini sdh ada di beberapa versi sebelumnya. Terima kasih telah melaporkan.
Sudah diperbaiki dan dicommit ke master.
Silakan coba lagi.

**Comment by MUHAMMADRANGSEL** [comment]
ma eddie setelah saya cek masih terdapat masalah di menu analisis, plan dan peta yang tidak bisa diakses

**Comment by eddieridwan** [comment]
Itu bukan error. Tapi saat ini modul Analisis, Plan dan Peta hanya boleh diakses Administrator. Kalau perlu diubah, silakan buat issue baru. Mungkin sekalian buat pemetaan semua menu utama: user jenis apa yang boleh akses.

**Comment by MUHAMMADRANGSEL** [comment]
Ok siap. Terima kasih atas infonya mas Eddie

Pada tanggal 7 Feb 2018 4.12 PM, "Eddie Ridwan" <notifications@github.com>
menulis:
