### ISSUE TITLE
Bug/error: menu bantuan dan beberapa menu tidak muncul

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#7790]
### Jelaskan error yg dialami

menu bantuan  dan beberapa menu tidak muncul
![Screenshot 2024-03-22 021706](https://github.com/OpenSID/OpenSID/assets/25834335/0522caaa-dafb-40b5-9bb6-eb1390a419af)

### Cara untuk mereplikasi errornya

menu bantuan dan beberapa menu lainnya tidak muncul
![Screenshot 2024-03-22 021706](https://github.com/OpenSID/OpenSID/assets/25834335/0522caaa-dafb-40b5-9bb6-eb1390a419af)

### Hasil yg diharapkan

menu bantuan dan beberapa menu tampil seperti versi sebelumnya
![Screenshot 2024-03-22 021929](https://github.com/OpenSID/OpenSID/assets/25834335/4dc25d85-c119-4024-9de8-acbe9a6e6e0d)

### Tangkapan layar dan log error

menu bantuan dan beberapa menu lainnya tidak muncul
![Screenshot 2024-03-22 021706](https://github.com/OpenSID/OpenSID/assets/25834335/0522caaa-dafb-40b5-9bb6-eb1390a419af)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

OpenSID 2403.0.2-premium

### Tema Yang Digunakan

DeNava

**Comment by andifahruddinakas** [comment]
sudah disesuaikan melalui commit https://github.com/OpenSID/premium/commit/af20c1684906d575cafb0e0e834ef5702544335e
