### ISSUE TITLE
Bug/error: Tambah Dokumen Persyaratan Surat error

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#7793]
### Jelaskan error yg dialami

Tambah Dokumen Persyaratan Surat error
![Screenshot 2024-03-24 011425](https://github.com/OpenSID/OpenSID/assets/25834335/2d3c2fc7-ac49-41ba-b77e-4efa5a530dc6)

### Cara untuk mereplikasi errornya

Masuk di menu Layanan Surat/ daftar Persyaratan Klik Tambah persyaratan maka akan muncul 404
![Screenshot 2024-03-24 011723](https://github.com/OpenSID/OpenSID/assets/25834335/b78ce095-e9c4-4068-b727-f4a519f3fe28)

### Hasil yg diharapkan

Bisa menambahkan daftar persyaratan dokumen seperti versi sebelumnya

### Tangkapan layar dan log error

![Screenshot 2024-03-24 011723](https://github.com/OpenSID/OpenSID/assets/25834335/dfd61540-0030-4681-a382-6b4a48b6d298)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

OpenSID 2403.0.2-premium

### Tema Yang Digunakan

Natra

### Informasi tambahan

di Aplikasi https://berputar.opendesa.id/

**Comment by andifahruddinakas** [comment]
Sudah sesuai di versi terbaru, bisa cek https://beta.opendesa.id
