### ISSUE TITLE
Bug/error: Tampilan Cetak Arsip Layanan Surat

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#7794]
### Jelaskan error yg dialami

Tampilan Cetak Arsip Layanan Surat perlu penyesuaian

### Cara untuk mereplikasi errornya

Perhi ke halaman Layanan Surat/ Arsip Layanan klik Cetak Arsip Layanan
![Screenshot 2024-03-24 011942](https://github.com/OpenSID/OpenSID/assets/25834335/2c804541-40db-4e87-a387-d9dbb5cb097a)
akan muncul seperti gambar dibawah ini :
![Screenshot 2024-03-24 012000](https://github.com/OpenSID/OpenSID/assets/25834335/d24823cc-4f98-4a8c-9bf8-8d6e7b197f65)

### Hasil yg diharapkan

Tampilan Normal seperti di menu menu lainnya

### Tangkapan layar dan log error

![Screenshot 2024-03-24 012000](https://github.com/OpenSID/OpenSID/assets/25834335/d24823cc-4f98-4a8c-9bf8-8d6e7b197f65)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

OpenSID 2403.0.2-premium

### Tema Yang Digunakan

Natra

### Informasi tambahan

https://berputar.opendesa.id/

**Comment by habibie11** [comment]
klik yang di lingkari merah untuk melihat hasil cetakkannya pak @MUHAMMADRANGSEL 
![image](https://github.com/OpenSID/OpenSID/assets/56639378/5deb90b0-62cd-417b-8883-84d96bc9f93e)
