### ISSUE TITLE
Bug/error: Font Aksara Bali (hasil upload) pada pengaturan surat tidak terbaca sistem

### ISSUE THREAD

**Issue by melinggih** [OpenSID/OpenSID#7795]
### Jelaskan error yg dialami

Layanan Surat>Pengaturan Surat>Pengaturan>Header

### Cara untuk mereplikasi errornya

Layanan Surat>Pengaturan Surat>Pengaturan>Header

### Hasil yg diharapkan

font hasil upload ke sistem bisa terbaca dengan baik 

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/150767634/41a67cac-bf85-446d-981e-e4fde893db28)
![image](https://github.com/OpenSID/OpenSID/assets/150767634/e322fff9-dfd4-40a2-ac8c-787588dba412)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2312.0.3-premium

### Tema Yang Digunakan

tema silir

### Informasi tambahan

saya masih menggunakan versi lama, karena belum mengerti menggunakan TinyMce, dan sekarang akan beralih ke versi terbaru setelah mengikuti Pelatihan Layanan Surat

No Whatsapp : 081236019593

**Comment by melinggih** [comment]
saya upload font aksara bali, tidak terbaca oleh sistem

**Comment by andifahruddinakas** [comment]
Duplicate issue https://github.com/OpenSID/OpenSID/issues/7285
