### ISSUE TITLE
Bug/error: Format Hasil Surat berbeda dengan Format pada sistem 

### ISSUE THREAD

**Issue by melinggih** [OpenSID/OpenSID#7797]
### Jelaskan error yg dialami

layanan surat > Cetak Surat > Buat Surat > cth : Surat Keterangan
pada saat membuat surat (cth: surat keterangan) pada sistem formatnya sudah sesuai, akan tetapi format pada output surat berantakan (tidak sesuai dengan sistem) font, margin, space setiap paragraf berubah

### Cara untuk mereplikasi errornya

layanan surat > Cetak Surat > Buat Surat > cth : Surat Keterangan

### Hasil yg diharapkan

format surat disistem maupun hasilnya sesuai tidak ada perbedaan

### Tangkapan layar dan log error

![WhatsApp Image 2024-03-25 at 10 05 10_d3ef4769](https://github.com/OpenSID/OpenSID/assets/150767634/bf5c41fb-a283-40d1-9703-d9e69fbc32c9)
![WhatsApp Image 2024-03-25 at 10 04 48_2d707edb](https://github.com/OpenSID/OpenSID/assets/150767634/c60879e8-091b-4328-91f7-b0f52cab2609)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v2403.0.1-premium

### Tema Yang Digunakan

Silir

### Informasi tambahan

whtsapp. 081236019593 (Naning)

**Comment by andifahruddinakas** [comment]
pak @melinggih, bisa sertakan aturan-autran yang berlaku.

contoh: https://mediadesa.org/cara-menulis-surat-dengan-benar/
