### ISSUE TITLE
menu bantuan tidak muncul

### ISSUE THREAD

**Issue by pujocahyono** [OpenSID/OpenSID#7799]
### Jelaskan error yg dialami

menu bantuan tidak muncul meski di pengaturan modul sudah aktif

### Cara untuk mereplikasi errornya

menu bantuan

### Hasil yg diharapkan

tampil normal

### Tangkapan layar dan log error

![Cuplikan layar 2024-03-27 110804](https://github.com/OpenSID/OpenSID/assets/87228587/73ad60b0-73f1-48b7-b181-4ca4fce32949)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2403.0.2-premium

**Comment by andifahruddinakas** [comment]
Duplicate of https://github.com/OpenSID/OpenSID/issues/7790
