### ISSUE TITLE
Bug/error: Saat klik Ubah/Buat DTKS Baru terjadi error 404 

### ISSUE THREAD

**Issue by rockymakasar** [OpenSID/OpenSID#7800]
### Jelaskan error yg dialami

Di Modul DTKS saat klik Ubah/Buat DTKS baru terjadi error

### Cara untuk mereplikasi errornya

1. Rumah Tangga
2. Klik DTKS
3. Ubah/Buat DTKS Baru
4. error 404

![image](https://github.com/OpenSID/OpenSID/assets/94730877/f8bb4eca-eb07-4b50-a968-4df697a731f7)

### Hasil yg diharapkan

Normal

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/94730877/021264ae-56e9-4bb7-97ff-ba783cd6414d)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2403.0.2-premium

### Tema Yang Digunakan

-

### Informasi tambahan

-

**Comment by andifahruddinakas** [comment]
Selesai melalui commit https://github.com/OpenSID/premium/commit/6def37e55b1bf30c7691e4a8a1d1dcc750829d20
