### ISSUE TITLE
Bug/error: Hapus data master analisis sistem kembali pada halaman web

### ISSUE THREAD

**Issue by rockymakasar** [OpenSID/OpenSID#7801]
### Jelaskan error yg dialami

Data master analisis yang dihapus sistem kembali ke halaman depan

### Cara untuk mereplikasi errornya

1. Ke modul analisis
2. pilih master analisis
3. hapus salah satu master analisis yang dibuat
![image](https://github.com/OpenSID/OpenSID/assets/94730877/435d5079-d775-4b17-95a8-ee6d71d065a5)

### Hasil yg diharapkan

Data terhapus

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/94730877/e008b516-48d1-4942-a666-226ff27e5b92)

![image](https://github.com/OpenSID/OpenSID/assets/94730877/20f82b84-ba7c-4deb-bfd7-e638055a1f8e)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2403.0.2-premium

### Tema Yang Digunakan

-

### Informasi tambahan

-

**Comment by andifahruddinakas** [comment]
Selesai melalui commit https://github.com/OpenSID/premium/commit/0c511e438c3f03b9dcea3bdf59a401f809d8bb11
