### ISSUE TITLE
Bug/error: Widget aparatur pemerintah desa, pilihan gelar tidak ditampilkan, tidak dapat berfungsi

### ISSUE THREAD

**Issue by mah-mudi** [OpenSID/OpenSID#7803]
### Jelaskan error yg dialami

Widget aparatur pemerintah desa, pilihan gelar tidak ditampilkan, tidak dapat berfungsi

### Cara untuk mereplikasi errornya

1. admin web
2. widget aparatur pemerintah desa
3. pilih tidak menampilkan gelar

### Hasil yg diharapkan

Widget aparatur pemerintah desa, pilihan gelar tidak ditampilkan, dapat berfungsi sebagaimana mestinya

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/57661283/2fb6b152-c554-4818-aea0-8e0183df566a)

![image](https://github.com/OpenSID/OpenSID/assets/57661283/6249190a-c119-4ab4-955a-f4bb7aa05fac)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

24.03 premium

### Tema Yang Digunakan

silir

**Comment by andifahruddinakas** [comment]
mas @mah-mudi, apakah ini di widget atau di halaman? fungsi tersebut hanya berfungsi di bagian widget saja (tdk untuk halaman pemerintah)

![image](https://github.com/OpenSID/OpenSID/assets/57283157/c6d79ac2-c05d-413a-93ed-284207be674b)

![image](https://github.com/OpenSID/OpenSID/assets/57283157/c84dfb5d-3094-4ad3-b773-f2216c5f0ba0)

![image](https://github.com/OpenSID/OpenSID/assets/57283157/8c0ca47a-2f4e-48c2-9003-5dbc5f8ef686)

Jika menggunakan tema ubahan sendiri, bisa disesuaikan mengikuti tema bawaan.
