### ISSUE TITLE
Bug/error: Operasi Hitung tidak bisa Pengalian

### ISSUE THREAD

**Issue by RomziJazz** [OpenSID/OpenSID#7804]
### Jelaskan error yg dialami

Operasi hitung pada surat tinyMCE hanya mencakup penambahan dan pengurangan, tidak bisa pada pengalian.

### Cara untuk mereplikasi errornya

Contoh: jika saya tuliskan kode [HitunG][1+1] maka akan terjumlah menjadi 2, namun jika saya tuliskan [HitunG][1*1] maka akan tertulis 11

### Hasil yg diharapkan

ditambahkan operasi pengalian, karena di butuhkan pada beberapa surat seperti Rekom Pembelian BBM Jenis Tertentu sebagai berikut:
HASIL
![image](https://github.com/OpenSID/OpenSID/assets/65128302/93e20344-094b-4ba9-8777-b1f50f62035b)

ISIAN (Terlalu panjang jika penambahan terus menerus)
![image](https://github.com/OpenSID/OpenSID/assets/65128302/b5d9a3ed-745f-47d1-97f1-f3c6f3ea2e4d)

### Tangkapan layar dan log error

![WhatsApp Image 2024-03-29 at 05 04 49_aaacb5c5](https://github.com/OpenSID/OpenSID/assets/65128302/6de1a460-d14c-4c1e-a4ea-c31861d639c3)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2304.00

**Comment by andifahruddinakas** [comment]
Tambahkan Operasi Hitung untuk : 
- [ ] Perkalian
- [ ] Pembagian (Jika pembagi 0, maka hasilnya langsung 0 agar tidak infinity)

![image](https://github.com/OpenSID/OpenSID/assets/57283157/1dc6864a-56e4-4b9d-8b9b-4688f7db7abf)
