### ISSUE TITLE
Bug/error: Tambah Data Inventaris tidak bisa, setelah klik simpan redirect ke Beranda Data tidak bertambah

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#7827]
### Jelaskan error yg dialami

Tambah Data Inventaris tidak bisa, setelah klik simpan redirect ke Beranda Data tidak tersimpan.

### Cara untuk mereplikasi errornya

1. klik menu Sekretariat
2. klik menu Inventaris
3. klik tambah data
4. isi data inventaris
5. Simpan

### Hasil yg diharapkan

bisa tambah data inventaris

### Tangkapan layar dan log error

ketika di Klik Simpan 
![2024-04-02_11h59_02](https://github.com/OpenSID/OpenSID/assets/55429781/bac62e11-cdd8-41cb-a691-fbc284f0f9c9)

Redirect Kehalaman Beranda
![image](https://github.com/OpenSID/OpenSID/assets/55429781/876caa6d-d7e9-4c33-82ac-49c04585f87b)

Data Tidak tersimpan 

![image](https://github.com/OpenSID/OpenSID/assets/55429781/626ed01f-1f71-456e-8c1c-f7632d6415ef)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Version 2404.0.0-premium

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui commit https://github.com/OpenSID/premium/commit/41a0e511da9afcda966137f31fed369b1e842b4d, namun sepertinya ada perbedaan dengan yang di rilis pada https://github.com/OpenSID/rilis-premium dimana perubahan tersebut tidak ikut akibat forcepush.
