### ISSUE TITLE
Pengaturan Hak Akses Wilayah

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#7828]
- [ ] Buat migrasi untuk menambahkan kolom untuk menyimpan akses wilayah pada tabel **user**, misalnya(kolom: akses_wilayah)
isinya : 
[
   'akses' => true,
   'id_cluster' => (misalnya: 1, 2, atau lainnya),
];

- [ ] Sediakan pengaturan hak Akses Wiyah
![image](https://github.com/OpenSID/OpenSID/assets/57283157/048317a8-d478-4ba2-81dc-c178be740547)

- [ ] Jika pilih ya tampilkan pilihan dusun/rt/rw
- [ ] Jika pilih tidak sembunyikan pilihan dusun/rt/rw

catatan :
- proses ubah dari ya dan tidak pada akses wilayah tdk menghapus data sebelumnya, sehingga jika di aktifkan kembali akan menampilkan data yg sudah ada.

**Comment by pandigresik** [comment]
untuk pilihan wilayah bisakah kita menggunakan checkbox, jadi lebih flexible. Dengan asumsi seorang user bisa memiliki akses lebih dari satu wilayah

**Comment by andifahruddinakas** [comment]
> untuk pilihan wilayah bisakah kita menggunakan checkbox, jadi lebih flexible. Dengan asumsi seorang user bisa memiliki akses lebih dari satu wilayah

ok bisa, tp mungkin dibuat bertingkat. misalkan, jika tidak ada akses dusun, harusnya di bawahnya tidak bisa dipilih.

dan nantinya, pada bagian filter terkait wilayah ditampilkan sesuai akses wilayahnya saja.
![image](https://github.com/OpenSID/OpenSID/assets/57283157/c19d7bdd-c505-438d-b706-61c23c72401d)

misalkan user 1 : akses wilayahnya : 
- dusun : I
- rw : -
- rt : 1, 2, 3
maka yang tampil di list tsb hanya itu saja saat melakukan filter data

**Comment by rgrahardi** [comment]
link Panduan : https://panduan.opendesa.id/opensid/halaman-administrasi/pengaturan/pengguna#pengguna-wilayah-dusunrwrt
