### ISSUE TITLE
Cetak & unduh data wilayah administrasi perlu ditambahkan nama Dusun

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#783]
Cetak RT di data wilayah administrasi nama dusun perlu dimunculkan dan sekarang yang muncul RT perlu diganti dengan DUSUN ......... seperti gambar dibawah ini
![screenshot 2018-02-09 13 34 25](https://user-images.githubusercontent.com/25834335/36013331-87c5c796-0d9e-11e8-9bbb-5e04cce1ba81.png)

**Comment by MUHAMMADRANGSEL** [comment]
untuk masalah ini sudah kami coba perbaiki dan alhamdulilah berhasil seperti gambar dibawah ini 
![image](https://user-images.githubusercontent.com/25834335/36412598-e6d1bc44-1655-11e8-9047-0b7a959b4a9b.png)
dan 
![image](https://user-images.githubusercontent.com/25834335/36412621-f4fd0fa8-1655-11e8-9b96-56ea6165506f.png)

dan bersama ini kami lampirkan perubahn scripnya
[Scrip Data Wilayah yang sudah di perbaiki.zip](https://github.com/OpenSID/OpenSID/files/1739249/Scrip.Data.Wilayah.yang.sudah.di.perbaiki.zip)

**Comment by MUHAMMADRANGSEL** [comment]
mohon untuk isssue ini sudah ketemu solusinya supaya dimasukkan kedalam rilis

**Comment by eddieridwan** [comment]
Sudah dicommit ke master, dengan perubahan:

1. hilangkan penggunaan _unpenetration_
2. ganti 'Dusun' dengan $this->setting_sebutan_dusun
3. tambahkan favico.ico di tampilan cetak
4. beri nama file unduh wilayah_print yang lebih tepat
5. hapus file wilayah_cetak.php yg tidak digunakan.
