### ISSUE TITLE
Penerapan akses wilayah berdasarkan akses yang diberikan

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#7830]
Penerapan ini diterapkan pada modul berikut : 
- [x] Penduduk
- [x] Keluarga
- [x] RTM
- [ ] Data Suplemen
- [x] Calon Pemilih
- [ ] Peristiwa

Misalkan : 
- pengguna memiliki akses modul penduduk dgn tambahan akses wilayah yakni RT 01. Maka pada modul penduduk otomatis terfilter otomatis dengan menampilkan data penduduk wilayah RT 01.
![image](https://github.com/OpenSID/OpenSID/assets/57283157/f1846666-e652-4a35-8131-936d75667143)

**Comment by pandigresik** [comment]
> * [ ]  Penduduk
> * [ ]  Keluarga
> * [ ]  RTM
> * [ ]  Data Suplemen
> * [ ]  Calon Pemilih
> * [ ]  Peristiwa

Akan lebih mudah dilakukan ketika modul sudah dilakukan setelah konversi sekalian, dari modul diatas hanya modul penduduk yang belum dilakukan konversi. Jadi tidak 2 kali kerja juga

**Comment by andifahruddinakas** [comment]
> > * [ ]  Penduduk
> > * [ ]  Keluarga
> > * [ ]  RTM
> > * [ ]  Data Suplemen
> > * [ ]  Calon Pemilih
> > * [ ]  Peristiwa
> 
> Akan lebih mudah dilakukan ketika modul sudah dilakukan setelah konversi sekalian, dari modul diatas hanya modul penduduk yang belum dilakukan konversi. Jadi tidak 2 kali kerja juga

Bisa dibuat ataudi contohkan sj pada modul di atas yg sdh di konversi

**Comment by andifahruddinakas** [comment]
Kerjakan modul RTM yg sudah dikonversi
