### ISSUE TITLE
Bug/error: Buku Rekapitulasi penduduk  Ajax error

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#7832]
### Jelaskan error yg dialami

Klik menu Buku Rekapitulasi Penduduk muncul seperti digambar
![Screenshot 2024-04-02 161236](https://github.com/OpenSID/OpenSID/assets/25834335/0acf13a0-9658-4b70-a2db-a4158ca78e86)

### Cara untuk mereplikasi errornya

Klik menu Buku Rekapitulasi Penduduk muncul seperti digambar
![Screenshot 2024-04-02 161236](https://github.com/OpenSID/OpenSID/assets/25834335/0acf13a0-9658-4b70-a2db-a4158ca78e86)

### Hasil yg diharapkan

Normal seperti versi sebelumnya

### Tangkapan layar dan log error

![Uploading Screenshot 2024-04-02 161236.png…]()

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Versi 2404.0.0-premium

### Tema Yang Digunakan

Natra

### Informasi tambahan

demo berputar

**Comment by andifahruddinakas** [comment]
mas @habibie11, tambahkan fungsi ini sebelum di maping.

![image](https://github.com/OpenSID/OpenSID/assets/57283157/630d7183-fa03-4f9d-ac7f-a69d7be09136)

**Comment by habibie11** [comment]
> mas @habibie11, tambahkan fungsi ini sebelum di maping.
> 
> ![image](https://private-user-images.githubusercontent.com/57283157/318974790-630d7183-fa03-4f9d-ac7f-a69d7be09136.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwOTY2NzcsIm5iZiI6MTcxMjA5NjM3NywicGF0aCI6Ii81NzI4MzE1Ny8zMTg5NzQ3OTAtNjMwZDcxODMtZmEwMy00ZjlkLWFjN2YtYTY5ZDdiZTA5MTM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAyVDIyMTkzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwMWZkYTBmMjNmOWU4YTc4MmFiMjdjOTdjMzRjNzZhNWI0ZWEyMjRiNzZlMmUxMGRiOWI1OTUwMjgyZWY1ODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Dlb-MPPSqk6_si_ASoY0YuUEFk8WkbTexsBjxwLPHaM)

baik mas

**Comment by debitomika** [comment]
sudah saya lakukan seperti yang di instruksi @andifahruddinakas di file donjo-app/controllers/bumindes_penduduk_rekapitulasi.php baris 75, tapi error yang sama masih muncul

![image](https://github.com/user-attachments/assets/89c829d9-b8c0-4706-8e04-23b7ac61db70)
