### ISSUE TITLE
Bug/error :  Tahun perdes pada Produk hukum tidak Tampil dan pada Informasi Publik Tahun dan Kategori tidak Tampil

### ISSUE THREAD

**Issue by INaon** [OpenSID/OpenSID#7833]
### Jelaskan error yg dialami

Setelah Selesai Input Buku Peraturan Di desa dan Dismpan ketika dilihat di menu Produk Hukum Tahun perdes tidak Tampil, ini terjadi juga pada Menu Informasi Publik Tahun dan Jenis kategori tidak Tampil.

![Screenshot 2024-04-02 162633](https://github.com/OpenSID/OpenSID/assets/65794146/2a4a2e8e-afaa-4135-b2dc-1cb1927681d8)

![Screenshot 2024-04-02 162918](https://github.com/OpenSID/OpenSID/assets/65794146/9671c840-4a9f-4240-8d47-56143d01797e)

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

tahun perdes tampil pada produk hukum dan dan informasi publik tahun dan kategori tampil

![Screenshot 2024-04-02 163019](https://github.com/OpenSID/OpenSID/assets/65794146/3761fade-fbed-43c5-acba-e7421bc81e82)

![Screenshot 2024-04-02 162857](https://github.com/OpenSID/OpenSID/assets/65794146/89f80ac1-b3bf-4f51-9834-a37e07cb004a)

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

24.04

### Tema Yang Digunakan

denatra

**Comment by andifahruddinakas** [comment]
pak @INaon, untuk melaporkan sebaiknya menggunakan tema bawaan.

**Comment by INaon** [comment]
di gamti dengan tema bawaan sama pak tidak tampil, baik produk hukum maupun informasi publik


![Screenshot 2024-04-02 170800](https://github.com/OpenSID/OpenSID/assets/65794146/dc4e1223-42bb-4651-b5d3-e784d5ec2b67)

![Uploading Screenshot 2024-04-02 170901.png…]()

**Comment by andifahruddinakas** [comment]
Mas @yogiperdana, bisa duplikasi sbb:

1. tambahkan data pada informasi publik, kategori dan tahun tidak tampil
![image](https://github.com/OpenSID/OpenSID/assets/57283157/7956263d-a0fd-4f8e-a883-0df6f7d95e97)

2. tampilkan ke halaman wesite, kategori dan tahun tidak tampil
![image](https://github.com/OpenSID/OpenSID/assets/57283157/24a853cb-8591-4b31-bf5e-447dc06cf350)

**Comment by yogiperdana** [comment]
saya coba di berputar normal mas @andifahruddinakas 
![image](https://github.com/OpenSID/OpenSID/assets/14155050/c6710737-6c9f-49e6-9f73-b10b11435ebe)

**Comment by INaon** [comment]
@yogiperdana  coba cek nomor 7, tahun dan kategori tidak tampil
