### ISSUE TITLE
Bug/error: Jumlah Pada Stastik Penduduk tidak sama

### ISSUE THREAD

**Issue by INaon** [OpenSID/OpenSID#7834]
### Jelaskan error yg dialami

Jumlah Statistik kependudukan pada Umur (Kategori) dan juga terjadi Pada Jumlah Statistik kependudukan pada Umur (Rentang), Jumlah Belum Mengisi ketika di Klik Jumlah datanya Kosong seperti Gambar di bawah

![Screenshot 2024-04-02 171405](https://github.com/OpenSID/OpenSID/assets/65794146/8754c1e8-876c-4a1f-bba5-83f84c74f5a1)

![Screenshot 2024-04-02 171320](https://github.com/OpenSID/OpenSID/assets/65794146/fa10e854-fa4d-4078-8b91-cf4123366e71)

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

Data Sama Dengan Jumlah Penduduk

![Screenshot 2024-04-02 173805](https://github.com/OpenSID/OpenSID/assets/65794146/2b9bf47d-0663-4f67-bc2e-07b847aba643)

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

24.04

### Tema Yang Digunakan

Natra

**Comment by MUHAMMADRANGSEL** [comment]
saya juga mengalami hal yang sama

**Comment by andifahruddinakas** [comment]
pak @INaon, @MUHAMMADRANGSEL, bisa duplikasi ke https://berputar.opendesa.id/index.php/statistik untuk masalah ini

![image](https://github.com/OpenSID/OpenSID/assets/57283157/1e9844df-a011-40e8-b789-15d1c9ef75c5)

**Comment by andifahruddinakas** [comment]
pak @MUHAMMADRANGSEL, @INaon, untuk umur di ambil dari tanggal lahir dan seharusnya wajib isi. namun terlihat data pada bagian belum mengisi berupa minus.

apakah bisa sertakan database yang bisa digunakan atau bisa duplikasi ke https://berputar.opendesa.id/statistik untuk masalah ini.
