### ISSUE TITLE
Permintaan fitur: Penambahan Alur dalam pembuatan Surat Keterangan Kelahiran

### ISSUE THREAD

**Issue by Wiliyantoro** [OpenSID/OpenSID#7835]
### Apa kekurangan yg ingin diatasi?

data orang tua pada warga / pemohon akta kelahiran tidak muncul apabila :

1. data orang tua tidak berada dalam 1 kk dengan pemohon
2. jika pemohon berbeda kk / pisah kk dengan orang tuanya mustahil untuk dilakukan pencarian dalam data penduduk desa, hanya bisa dibuat dengan form penduduk luar desa

### Jelaskan solusi yg diinginkan

buat role seperti sebelum versi 24.04.0.0 yaitu: 
1. data orang tua di cari/diambil berdasarkan [nik_ayah/ibu] di data pemohon
2. apabila nik ayah tidak ada / tidak terisi dalam biodata pemohon maka munculkan form Ayah Ibu di Halaman Pembuatan surat
3. nantinya pencarian data ayah / ibu tidak terbatas dalam satu kk, tapi bisa diluar kk karena apabila pemohon pisah kk dengan orangtuanya pencarian data ayah / ibu bisa dilakukan.

melihat kasus yang terjadi saat ini permohonan surat keterangan kelahiran hanya terbatas dalam satu kk, pencarian data ortu pun hanya dalam satu kk ,, jika pisah kk hal tersebut tidak dapat dilakukan.

### Apakah ada alternatif lain

buat role / alur sesuai dengan case diatas

### Untuk versi OpenSID mana

2304.0.0 Premium

### Informasi tambahan

surat keterangan kelahiran setelah update ke versi saat ini harus menekan tombol mengembalikan surat bawaan/sistem agar dapat digunakan

**Comment by yogiperdana** [comment]
Jika kasus seperti ini sering terjadi maka sebaiknya secara default hubungan data dikosongkan saja. jika kasusnya tidak umum maka disesuaikan desa masing masing

**Comment by yogiperdana** [comment]
Jadinya disesuaikan dengan default hubungan data tidak terhubung agar kedua skenario dapat berjalan (baik untuk kk yang sama maupun beda) dengan pertimbangan operator/admin harusnya sudah mengetahui nama orang tua dari anak sehingga tidak diharuskan orang tua dipilih secara otomatis

**Comment by andifahruddinakas** [comment]
mas @rgrahardi, bisa dibuatkan panduannya

**Comment by rgrahardi** [comment]
baik mas @andifahruddinakas
