### ISSUE TITLE
Bug/error: Login terasa lamban diversi 24.04 premium

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#7836]
### Jelaskan error yg dialami

Login terasa lamban diversi 24.04 premium, saya cek di berputar juga sama

### Cara untuk mereplikasi errornya

Login terasa lamban diversi 24.04 premium, saya cek di berputar juga sama

### Hasil yg diharapkan

Normal seperti versi sebelumnya

### Tangkapan layar dan log error

looding lama

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

24.04.0.0

### Tema Yang Digunakan

Esensi

**Comment by andifahruddinakas** [comment]
pak @MUHAMMADRANGSEL, sy coba login prosesnya memakan waktu sekitar 4 detik.

![login](https://github.com/OpenSID/OpenSID/assets/57283157/f86cba58-be77-49ac-8fea-66b561282147)

**Comment by mah-mudi** [comment]
@MUHAMMADRANGSEL sama lambatnya kalau login.

**Comment by MUHAMMADRANGSEL** [comment]
kira2 kendalanya bang..?

**Comment by MUHAMMADRANGSEL** [comment]
ini terjadi di menu beranda dan submenu Shortcut aja bug @andifahruddinakas kalau menu yang lain normal

**Comment by andifahruddinakas** [comment]
> ini terjadi di menu beranda dan submenu Shortcut aja bug @andifahruddinakas kalau menu yang lain normal

ok, terima kasih infonya

**Comment by MUHAMMADRANGSEL** [comment]
semoga solusinya segera ditemukan

**Comment by langonsari** [comment]
Kalau saya sementara dihapus dulu semua info diberanda melalui Pengaturan submenu shortcut,,, Alhamdulillah lebih cepat loading pas masuk ke berandanya,,,

![image](https://github.com/OpenSID/OpenSID/assets/96863107/bf4d779d-034c-48d2-8d07-22c048728d40)
![image](https://github.com/OpenSID/OpenSID/assets/96863107/678c20b6-18fe-4935-baa8-0d94c7a4f6f1)

**Comment by langonsari** [comment]
> Reference

Kalau Data sudah banyak sampai puluhan ribu lumayan memakan waktu juga sampai lebih dari 3 menit,,,
Solusi awalnya Berandanya dikosongkan,, alhamdulillah bisa masuk dalam hitungan detik,,,

**Comment by MUHAMMADRANGSEL** [comment]
> > Reference
> 
> Kalau Data sudah banyak sampai puluhan ribu lumayan memakan waktu juga sampai lebih dari 3 menit,,, Solusi awalnya Berandanya dikosongkan,, alhamdulillah bisa masuk dalam hitungan detik,,,

setelah dikosongkan ditambahkan lagi shortcut nya...? atau bagaimana...?

**Comment by andifahruddinakas** [comment]
Solusi : 

- [ ] hasil dari query disimpan pada cache.
![image](https://github.com/OpenSID/OpenSID/assets/57283157/2ca435be-c03f-4138-b9da-02412703d7b1)

- [ ] setiap query yang disimpan dicache, jika ada perubahan data maka cache perlu di hapus

**Comment by MUHAMMADRANGSEL** [comment]
di Versi 2404.0.1-premium masih sama looding lambat

**Comment by MUHAMMADRANGSEL** [comment]
> Kalau saya sementara dihapus dulu semua info diberanda melalui Pengaturan submenu shortcut,,, Alhamdulillah lebih cepat loading pas masuk ke berandanya,,,
> 
> ![image](https://private-user-images.githubusercontent.com/96863107/322304025-bf4d779d-034c-48d2-8d07-22c048728d40.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzNzY2NjEsIm5iZiI6MTcxMzM3NjM2MSwicGF0aCI6Ii85Njg2MzEwNy8zMjIzMDQwMjUtYmY0ZDc3OWQtMDM0Yy00OGQyLThkMDctMjJjMDQ4NzI4ZDQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE3VDE3NTI0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTViZWU5ODNjNTc5YTNlY2VmM2QwMjc2MDg4YTBjOGNmMjc5OWZmODNmODhmMmFiY2I0NDNhNGFkZDhhZTM1NjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xXTg7SkaZJXX_VyjEhSbbJMHLzrbESecvhApd1guMBw) ![image](https://private-user-images.githubusercontent.com/96863107/322303944-678c20b6-18fe-4935-baa8-0d94c7a4f6f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzNzY2NjEsIm5iZiI6MTcxMzM3NjM2MSwicGF0aCI6Ii85Njg2MzEwNy8zMjIzMDM5NDQtNjc4YzIwYjYtMThmZS00OTM1LWJhYTgtMGQ5NGM3YTRmNmYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE3VDE3NTI0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5YWM5OTQ2ZTJkYTFmNTcwNmRiYTZkMGM0Y2ZjN2U0ZTVkZmIyNTJhZTA5NWEzZjY0MTdmODJjNzZlMTc5NDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RpoSJ9NN5ZsIHvdzehaXnV51_6pzKhOa-M3dD-lqsko)

pakai jurus ini dulu sementara 3 detik sudah bisa login

**Comment by andifahruddinakas** [comment]
> di Versi 2404.0.1-premium masih sama looding lambat

belum masuk rilis selama issue masih terbuka.
