### ISSUE TITLE
Bug/error: tidak berfungsinya tambah program bantuan

### ISSUE THREAD

**Issue by mah-mudi** [OpenSID/OpenSID#7839]
### Jelaskan error yg dialami

tidak berfungsinya tambah program bantuan

### Cara untuk mereplikasi errornya

1. bantuan
2. tambah bantuan program

### Hasil yg diharapkan

berfungsinya tambah program bantuan sebagaimana mestinya

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/57661283/073c5067-99eb-49af-b1ef-88cac4cab19f)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

24.04 premium

### Tema Yang Digunakan

silir

### Informasi tambahan

berputar.opendesa.id

**Comment by andifahruddinakas** [comment]
Selesai melalui commit https://github.com/OpenSID/premium/commit/eefee1507b138b76abab6e76e3f60d8a67f0c16d
