### ISSUE TITLE
Bug/error: Perbaikan Surat Dinas

### ISSUE THREAD

**Issue by RomziJazz** [OpenSID/OpenSID#7843]
### Jelaskan error yg dialami

1. Pada Pilihan **Tambahkan ke Surat Keluar** jika memilih **Tidak**, maka surat tidak dapat disimpan, sehingga bagian ini tidak ada fungsinya.
![image](https://github.com/OpenSID/OpenSID/assets/65128302/45cf4e12-310e-4727-8ca9-ebaf93e44eee)

2. Tombol kembali ke daftar surat, jika dipencet akan kembali ke Cetak Layanan Surat, tidak kembali ke Cetak Surat Dinas.
![image](https://github.com/OpenSID/OpenSID/assets/65128302/5668134b-c0fc-4b0a-85da-2085025545c1)

3. Menu Pengaturan Surat jika bisa ditautkan langsung dengan pengaturan surat layanan, karena pengaturan KOP dan Footer yang di pakai adalah pengaturan di menu layanan surat.
 
![image](https://github.com/OpenSID/OpenSID/assets/65128302/5ebf5953-7c28-4c6d-a801-eb90efd4b45b)

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2405.00

**Comment by andifahruddinakas** [comment]
Sudah satukan dengan issue https://github.com/OpenSID/OpenSID/issues/7838
