### ISSUE TITLE
Bug/error: Slider tidak muncul

### ISSUE THREAD

**Issue by indr14** [OpenSID/OpenSID#7844]
### Jelaskan error yg dialami

slider artikel terbaru di opensid versi 2404 tidak muncul.

### Cara untuk mereplikasi errornya

saya sudah mencoba tapi tidak bisa, mohon bantuannya

### Hasil yg diharapkan

slider kembali muncul

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/113086020/4657384e-7050-4bdd-9c62-9c5ca1fd01f6)

### Rilis Versi OpenSID

Rilis Umum

### Versi OpenSID

v2404.0.0

### Tema Yang Digunakan

natra

**Comment by andifahruddinakas** [comment]
pak @indr14, saya coba di https://demosid.opendesa.id/ bisa.

mungkin bisa lengkapi pengaturan slidernya seperti apa.

silahkan dibuka kembali jika masih mengalami masalah

**Comment by indr14** [comment]
pengaturannya seperti ini pak.
![image](https://github.com/OpenSID/OpenSID/assets/113086020/88fe274e-af38-46f2-adb0-fddc88c26879)
