### ISSUE TITLE
Bug/error: Ubah surat mengalami error 

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#7845]
### Jelaskan error yg dialami

ketika melakukan update surat atau sudah melakukan perubahan dan pada saat simpan mengalami error termasuk juga tinjau surat

### Cara untuk mereplikasi errornya

ketika melakukan update surat atau sudah melakukan perubahan dan pada saat simpan mengalami error termasuk juga tinjau surat
kali ini sebagai contoh Surat Keterangan Izin Orang Tua Suami Istri yang langsung saya coba di https://berputar.opendesa.id/surat_master/form/225, tampilan errornya sepperti gambar dibawah ini :
![Screenshot 2024-04-05 131117](https://github.com/OpenSID/OpenSID/assets/25834335/4898c2d8-ff29-46f6-8cb6-ba902aef5660)
![Screenshot 2024-04-05 131202](https://github.com/OpenSID/OpenSID/assets/25834335/dfe2e74d-b506-4fc9-a934-5a4b800ce689)
![Screenshot 2024-04-05 131456](https://github.com/OpenSID/OpenSID/assets/25834335/9aa422cc-1b48-4c02-abb3-2f5dc0b48ab3)

### Hasil yg diharapkan

Bisa menyimpan sekaligus tinjau surat seperti sebelumnya

### Tangkapan layar dan log error

![Screenshot 2024-04-05 131117](https://github.com/OpenSID/OpenSID/assets/25834335/4898c2d8-ff29-46f6-8cb6-ba902aef5660)
![Screenshot 2024-04-05 131202](https://github.com/OpenSID/OpenSID/assets/25834335/dfe2e74d-b506-4fc9-a934-5a4b800ce689)
![Screenshot 2024-04-05 131456](https://github.com/OpenSID/OpenSID/assets/25834335/9aa422cc-1b48-4c02-abb3-2f5dc0b48ab3)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

24.04.0.0

### Tema Yang Digunakan

Natra

### Informasi tambahan

-

**Comment by MUHAMMADRANGSEL** [comment]
data penerima izin tidak muncul formnya
![Uploading Screenshot 2024-04-05 134146.png…]()

**Comment by andifahruddinakas** [comment]
mas @habibie11, untuk perbaikan errornya sudah disesuaikan di commit https://github.com/OpenSID/premium/commit/ee4fb7e722621847e54aefc0dcefaabeeb90b340

tinggal perbaiki bagian form, datanya tidak berubah : 
![image](https://github.com/OpenSID/OpenSID/assets/57283157/1c138397-b0fd-40e0-9f5e-96c7cdb019c9)

![image](https://github.com/OpenSID/OpenSID/assets/57283157/74aa772c-c79d-41be-b67a-a3999594a746)

**Comment by MUHAMMADRANGSEL** [comment]
> mas @habibie11, untuk perbaikan errornya sudah disesuaikan di commit https://github.com/OpenSID/premium/commit/ee4fb7e722621847e54aefc0dcefaabeeb90b340
> 
> tinggal perbaiki bagian form, datanya tidak berubah : ![image](https://private-user-images.githubusercontent.com/57283157/320096252-1c138397-b0fd-40e0-9f5e-96c7cdb019c9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1MTEwMTEsIm5iZiI6MTcxMjUxMDcxMSwicGF0aCI6Ii81NzI4MzE1Ny8zMjAwOTYyNTItMWMxMzgzOTctYjBmZC00MGUwLTlmNWUtOTZjN2NkYjAxOWM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA3VDE3MjUxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwY2YxNmY5ZWE2MzkzMjU0NGM3NjNmNmM4OWU0YTE1M2MxMWQ0ZDUxMDNlNzk1YzBlYjYxYjE3YzBjYjY2ZWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oUsYC7aPxgTlSfXDHxPVxsrt58kCStV4HTEpUscPcs4)
> 
> ![image](https://private-user-images.githubusercontent.com/57283157/320096319-74aa772c-c79d-41be-b67a-a3999594a746.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1MTEwMTEsIm5iZiI6MTcxMjUxMDcxMSwicGF0aCI6Ii81NzI4MzE1Ny8zMjAwOTYzMTktNzRhYTc3MmMtYzc5ZC00MWJlLWI2N2EtYTM5OTk1OTRhNzQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA3VDE3MjUxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlYzIwOGQ4OWExZDczOWYyNTUzZDRhMDE1Y2Q1NzBlZTNhNDkyNTZjZGU5YzY0M2VmOGZkYjA3NGU0MjU4MWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.O9sTqLUJuloELQkVlxyj8vQgP17GyKxy2WAr69tHq0I)

terima kasih bang
