### ISSUE TITLE
Bug/error: Ketika input Kode Lembaga dengan angka 4, mendapat notif angka sudah digunakan, padahal terlihat pada tabel angka 4 belum digunakan

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#7846]
### Jelaskan error yg dialami

Ketika input Kode Lembaga dengan angka 4, mendapat notif angka sudah digunakan, pada terlihat pada tabel angka 4 belum digunakan

### Cara untuk mereplikasi errornya

1. klik info lembaga
2. lembaga desa
3. tamba 
4. masukan kode lembaga angka 4
5. simpan
dapat notif data tidak bisa di tambahkan kode lembaga 4 sudah digunakan 

### Hasil yg diharapkan

bisa menginputkan kode lembaga angka 4

### Tangkapan layar dan log error
1. terlihat data kode lembaga belum ada yang menggunakan angka 4
![image](https://github.com/OpenSID/OpenSID/assets/55429781/063b58f5-1b89-4d89-bdf3-f0113f0333d8)

2. tambah data lembaga, kode lembaga isi angka 4
![image](https://github.com/OpenSID/OpenSID/assets/55429781/fce21b82-5384-434b-b053-ca46676118a4)

3. notifikasi setelah klik simpan
![image](https://github.com/OpenSID/OpenSID/assets/55429781/2baf534d-7f34-4acb-99e3-b95676561d44)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2404.0.0-premium

**Comment by andifahruddinakas** [comment]
mas @rgrahardi, bisa sertakan database yang bisa digunakan, krn terkarkait struktur database.

kemungkinan kode 4 sudah digunakan di kelompok, karena lembaga dan kelompok menggunakan 1 tabel yang sama.

**Comment by MUHAMMADRANGSEL** [comment]
> mas @rgrahardi, bisa sertakan database yang bisa digunakan, krn terkarkait struktur database.
> 
> kemungkinan kode 4 sudah digunakan di kelompok, karena lembaga dan kelompok menggunakan 1 tabel yang sama.

mungkin perlu dibedakan tabelnya bang spy mudah dimengerti oleh teman2 pengguna

**Comment by andifahruddinakas** [comment]
mas @habibie11, bisa cek :
- [ ] relasi seharunya menggunakan tiga kolom, yakni (config_id, kode, tipe) karena tabel kelompok digunakan oleh 2 modul yang sama persis isinya.
- [ ] cek juga validasi uniq nya, perlu ditambahkan pengecekan tipenya jg

database bisa gunakan https://drive.google.com/drive/folders/1U3th7GbClL7lyh-tTzLsMeW7iwXfWYVs
