### ISSUE TITLE
Saat penduduk rubah status dasar jadi Pindah/Mati, masih muncul di anggota rumah tangga 

### ISSUE THREAD

**Issue by pujocahyono** [OpenSID/OpenSID#7847]
### Jelaskan error yg dialami

Saat penduduk rubah status dasar jadi Pindah/Mati, masih muncul di anggota rumah tangga

### Cara untuk mereplikasi errornya

1. ubah status dasar penduduk jadi Pindah/Mati
2. cek di anggota rumah tangga penduduk tersebut

### Hasil yg diharapkan

ketika rubah status dasar penduduk jadi pindah/mati harusnya di anggota rumah tangga juga ikut pindah atau tidak muncul lagi

### Tangkapan layar dan log error

![Cuplikan layar 2024-04-06 102825](https://github.com/OpenSID/OpenSID/assets/87228587/332480f7-fdf5-4791-a03c-9be92dfb4e84)
![Cuplikan layar 2024-04-06 102501](https://github.com/OpenSID/OpenSID/assets/87228587/78622a9b-fc84-4499-9565-878701348789)
![Cuplikan layar 2024-04-06 102442](https://github.com/OpenSID/OpenSID/assets/87228587/9faaafca-397e-494b-9828-75f9bd591455)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2404.0.0

**Comment by andifahruddinakas** [comment]
Solusi : 

- [ ] tambahkan scope penduduh hidup saja pada saat menampilkan anggota rumah tangga pada jumlah anggota rumah tangga, detail rumah tanggal dan cetak kartu rumah tangga,
