### ISSUE TITLE
Bug/error: Ketika melakukan hapus Kategori, Artikel juga ikut terhapus

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#7848]
### Jelaskan error yg dialami

Ketika melakukan hapus Kategori, Artikel juga ikut terhapus

### Cara untuk mereplikasi errornya

1. klik menu kategori
2. hapus kategori
3. cek artikel yang menggunakan kategori yang dihapus juga ikut terhapus

### Hasil yg diharapkan

1. pemberitahuan kategori sudah memiliki artikel, kategori tidak bisa dihapus

### Tangkapan layar dan log error

1. klik hapus kategori berita desa
![image](https://github.com/OpenSID/OpenSID/assets/55429781/7f22b545-2b92-4d0f-8fe2-b598810bfa47)
2. kategori berita desa sudah meliki artikel
![image](https://github.com/OpenSID/OpenSID/assets/55429781/e0a6f4d4-4c6b-4e77-bfb4-ee0246b3ab5c)
3. artikel juga ikut terhapus ketika kategori dihapus
![image](https://github.com/OpenSID/OpenSID/assets/55429781/617ed4be-2cbc-4941-8105-a87e36ec99d8)
![image](https://github.com/OpenSID/OpenSID/assets/55429781/dec39787-141c-4591-a26a-9f4b3e1f7cad)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2404.0.0-premium

**Comment by andifahruddinakas** [comment]
Karena tabel artikel saling berelasi (artikel dan kategori), maka kategori yang memiliki artikel tombol hapusnya perlu dihilangkan.
