### ISSUE TITLE
Bug/error: Isian data pelapor dan saksi pada pembuatan Surat Keterangan Kematian kosong

### ISSUE THREAD

**Issue by rockymakasar** [OpenSID/OpenSID#7849]
### Jelaskan error yg dialami

Pada saat membuat surat keterangan kematian, isian data pelapor dan saksi tidak ada

### Cara untuk mereplikasi errornya

1. Modul Layanan Surat
2. Cetak Surat
3. Pilih Surat Keterangan Kematian

### Hasil yg diharapkan

Normal

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/94730877/5d3945a1-7aba-4c21-a0cd-d84b5b155f9e)

![image](https://github.com/OpenSID/OpenSID/assets/94730877/6349e89f-a551-4d5b-9de6-3d3e013a05b6)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2404.0.0-premium

### Tema Yang Digunakan

-

### Informasi tambahan

-

**Comment by andifahruddinakas** [comment]
mas @rockymakasar, coba di restore ke template bawaan.

**Comment by rockymakasar** [comment]
Ok bung.. aman
