### ISSUE TITLE
OpenSID 2.9 versi exe

### ISSUE THREAD

**Issue by happyagung25** [OpenSID/OpenSID#785]
Berikut ini saya buatkan Installer OpenSID 2.9 yang sudah include database contoh yang sudah terimport.
Installer ini akan memudahkan pengguna baru dalam proses installasi awal OpenSID

http://www.opensid.info/OpenSID.2.9-VC9-installer.exe

**Comment by obhy08** [comment]
Bang..php to exe pkek app apa tuh? Sy pkek innosetup tp slalu salah di BD nya..mohon percerahan

**Comment by metalab25** [comment]
Buat apa bikin lagi kan sudah saya siapkan yang tinggal install

**Comment by eddieridwan** [comment]
Issue ini ditutup.
