### ISSUE TITLE
loading terasa lama

### ISSUE THREAD

**Issue by mranca** [OpenSID/OpenSID#7850]
### Jelaskan error yg dialami

saat loading di data penduduk atau yang lainnya terasa lama

### Cara untuk mereplikasi errornya

.

### Hasil yg diharapkan

.

### Tangkapan layar dan log error

.

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

terbaru

### Tema Yang Digunakan

.

### Informasi tambahan

.

**Comment by andifahruddinakas** [comment]
Duplicate of https://github.com/OpenSID/OpenSID/issues/7836
