### ISSUE TITLE
muncul pesan error

### ISSUE THREAD

**Issue by mranca** [OpenSID/OpenSID#7851]
### Jelaskan error yg dialami

saat buka buku rekapitulasi jumlah penduduk muncul pesan error tabel

### Cara untuk mereplikasi errornya

1. masuk admin
2. buku administrasi desa
3. administrasi penduduk
4. buku rekapitulasi jumlah penduduk

### Hasil yg diharapkan

.

### Tangkapan layar dan log error

![Screenshot (139)](https://github.com/OpenSID/OpenSID/assets/76085245/86230683-e29b-4fed-8355-34898063de76)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

terbaru

### Tema Yang Digunakan

.

### Informasi tambahan

.

**Comment by andifahruddinakas** [comment]
Duplicate of https://github.com/OpenSID/OpenSID/issues/7832
