### ISSUE TITLE
Permintaan fitur: Sederhanakan permohonan surat melalui Anjungan

### ISSUE THREAD

**Issue by ai-skematik** [OpenSID/OpenSID#7857]
### Apa kekurangan yg ingin diatasi?

Saat ini permohonan surat melalui anjungan masih menggunakan menu layanan mandiri yang dirasa menyulitkan oleh pengguna. selain itu fitur yang ada dalam layanan mandiri sudah ada di anjungan, sehingga di harapkan ada fitur khusus permohonan surat di anjungan.

### Jelaskan solusi yg diinginkan

-

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

24.04 Premium

### Informasi tambahan

referensi 
![image](https://github.com/OpenSID/OpenSID/assets/48144047/ec42a475-a8e6-467b-ac64-e15eec159d8e)

**Comment by luxmant354** [comment]
up

**Comment by andifahruddinakas** [comment]
Issue ini dipecah : 

- [ ] halaman awal setelah login dan halaman ketika akan logout (tampilkan notif survey kepuasan) https://github.com/OpenSID/OpenSID/issues/8042
- [ ] halaman daftar dan cetak surat https://github.com/OpenSID/OpenSID/issues/8043
