### ISSUE TITLE
Bug/error: Ubah daftar Program rentang waktu berubah otomatis

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#7859]
### Jelaskan error yg dialami

Ketika klik Ubah pada salah satu program yang ada di menu bantuan maka rentang waktu program ikut berubah sevara otomatis

### Cara untuk mereplikasi errornya

pergi ke menu bantuan klik ubah pada salah satu program bantuan yang ada maka rentang waktu program berubah secara otomatis

### Hasil yg diharapkan

rentang waktu tidak berubah ketika klik ubah program bangtuan

### Tangkapan layar dan log error

![Screenshot 2024-04-16 234839](https://github.com/OpenSID/OpenSID/assets/25834335/e154d87e-888e-4fe2-a804-bd7b0a41d53d)
![Screenshot 2024-04-16 234905](https://github.com/OpenSID/OpenSID/assets/25834335/c00067f5-c279-45b3-b6a7-205911f556e8)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

24.04.0.0 premium

### Tema Yang Digunakan

Esensi

### Informasi tambahan

masalah ini terjadi juga di berputar

**Comment by MUHAMMADRANGSEL** [comment]
ternyata tambah peserta juga mengalami bug seperti video https://www.youtube.com/watch?v=bfzWN-ngpOQ

**Comment by habibie11** [comment]
simpan program bantuan dengan sasaran programnya penduduk perorang,  rumah tangga, atau kelompok juga tidak bisa simpan. akan segera diperbaiki.
![image](https://github.com/OpenSID/OpenSID/assets/56639378/53c5f418-710f-4ff3-8d67-2dacf30a7145)
