### ISSUE TITLE
Penambahan Kolom Alamat dan NIK Kepala Rumah Tangga

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#786]
agar seragam seperti sub menu penduduk, Keluarga di SUB MENU RUMAH TANGGA perlu ditambahkan kolom alamat dan NIK Kepala Rumah Tangga seperti gambar dibawah ini
![screenshot 2018-02-10 11 48 41](https://user-images.githubusercontent.com/25834335/36058357-c8bfcad4-0e58-11e8-8b81-c1bef0bce4d2.png)

**Comment by metalab25** [comment]
Alamat Rumah Tangga ini apakah sesuai dengan alamat pada KK si Kepala Rumah Tangga ???

**Comment by MUHAMMADRANGSEL** [comment]
Ya sama dengan alamat si kepala keluarga

Pada tanggal 26 Feb 2018 9.34 PM, "Happy" <notifications@github.com>
menulis:

**Comment by eddieridwan** [comment]
Sdh dicommit ke master melalui PR #858.
