### ISSUE TITLE
terjadi error saat klik no kk di data penduduk

### ISSUE THREAD

**Issue by mranca** [OpenSID/OpenSID#7861]
### Jelaskan error yg dialami

error saat klik no kk 

### Cara untuk mereplikasi errornya

1. masuk admin
2. masuk di penduduk
3. klik no kk pada salah satu penduduk 

### Hasil yg diharapkan

.

### Tangkapan layar dan log error

![bug kkk](https://github.com/OpenSID/OpenSID/assets/76085245/0ba33031-61be-4f37-bd3f-9deb0e4894c1)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

terbaru

### Tema Yang Digunakan

.

### Informasi tambahan

.

**Comment by andifahruddinakas** [comment]
mas @mranca, untuk sementara bisa menghapus 2 angka sebelumnya.
![image](https://github.com/OpenSID/OpenSID/assets/57283157/56012cc9-cf9a-4255-8fbf-4c13b278b271)

jadi

![image](https://github.com/OpenSID/OpenSID/assets/57283157/f01019e4-a828-4a3d-ad21-4cbf80c45cf7)

**Comment by andifahruddinakas** [comment]
Perbaikan : 
- [ ] penduduk
- [ ] detail penduduk
- [ ] peristiwa

**Comment by andifahruddinakas** [comment]
Perbaikan melalui commit https://github.com/OpenSID/premium/commit/c32026e0feca27eff89f842909fde27a9826f94a
