### ISSUE TITLE
Bug/error: 

### ISSUE THREAD

**Issue by redhousman** [OpenSID/OpenSID#7863]
### Jelaskan error yg dialami

Data Kartu Keluarga terjadi kesalahan 404.

### Cara untuk mereplikasi errornya

![Annotation 2024-04-19 001359](https://github.com/OpenSID/OpenSID/assets/141497405/4a051574-1969-4be3-87b4-7de5063e9cfb)

### Hasil yg diharapkan

Data keluarga lengkap

### Tangkapan layar dan log error

![Annotation 2024-04-19 001424](https://github.com/OpenSID/OpenSID/assets/141497405/2af639f5-6399-4d29-be6c-b6c15a6ac923)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Versi 2404.0.1-premium

### Tema Yang Digunakan

DeNava v11.0

### Informasi tambahan

Dan dalam pencetakan surat, nama anggota keluarga  pada menu pencetakan surat data keluarga tidak muncul

**Comment by andifahruddinakas** [comment]
Duplicate of https://github.com/OpenSID/OpenSID/issues/7861
