### ISSUE TITLE
Bug/error: Gagal Tambah Widget

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#7864]
### Jelaskan error yg dialami

https://github.com/OpenSID/OpenSID/assets/46939846/88900d46-500c-41cc-9271-617b809c16a9

### Cara untuk mereplikasi errornya

di video atas

### Hasil yg diharapkan

normal kembali

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Berputar

**Comment by andifahruddinakas** [comment]
disatukan di issue yang berkaitan https://github.com/OpenSID/OpenSID/issues/7865
