### ISSUE TITLE
Bug/error: Gambar Widget Hilang

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#7865]
### Jelaskan error yg dialami

https://github.com/OpenSID/OpenSID/assets/46939846/15588912-92a1-4b31-9a2f-12abca145637

### Cara untuk mereplikasi errornya

semula pada sebuah widget terdapat gambar.

ketika diedit dan mencoba simpan. maka gambar menjadi hilang ketika dilihat kembali.

seperti divideo.

### Hasil yg diharapkan

normal

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Berputar

**Comment by ariandii** [comment]
info tambahan, file gambar tersebut pada folder desa/upload/widgets juga hilang.

**Comment by andifahruddinakas** [comment]
SOLUSI:

- [ ] perbaikan booted hapus gambar setelah update, hanya jika ada perubahan gambar.
- [ ] gagal tambah widget (https://github.com/OpenSID/OpenSID/assets/46939846/88900d46-500c-41cc-9271-617b809c16a9)
