### ISSUE TITLE
Permintaan fitur:  Mohon Buatkan Lampiran Surat F-2.30

### ISSUE THREAD

**Issue by utay-cugung** [OpenSID/OpenSID#7866]
### Apa kekurangan yg ingin diatasi?

tidak ada lampiran surat kematian F-2.30 Pada layanan surat keterangan kematian.
Lampiran tersebut diharuskan ada sebagai salah satu lampiran permohonan akta kematian di dukcapil lampung selatan.
sebelumnya sudah di buat berupa surat editan tetapi dengan muncul versi baru isian dari lampiran 2.01 kolom pelapornya kosong dan agar lampiran tersebut tersedia secara default sistem dan dapat digunakan banyak desa yg membutuhkan.

### Jelaskan solusi yg diinginkan

Tersedia Lampiran F-2.30 pelaporan kematian

![image](https://github.com/OpenSID/OpenSID/assets/155012206/b62a34f4-aded-47b8-a52e-f4ee1e87ea05)

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

premium

### Informasi tambahan

MOHON DI BUATKAN KARENA TANPA LAMPIRAN TERSEBUT, PERMOHONAN AKTA KEMATIAN DI TOLAK ALASAN BERKAS TIDAK LENGKAP

**Comment by andifahruddinakas** [comment]
pak @utay-cugung, untuk lampiran F-2.30 sudah ada sejak lama.
![image](https://github.com/OpenSID/OpenSID/assets/57283157/8a97c4f9-3596-4718-bf9c-94360b2acbf0)

![image](https://github.com/OpenSID/OpenSID/assets/57283157/81d1fa96-b745-4f62-9372-def615e07490)
