### ISSUE TITLE
Bug/error:  Tidak bisa input penduduk baru lewat menu keluarga

### ISSUE THREAD

**Issue by ai-skematik** [OpenSID/OpenSID#7867]
### Jelaskan error yg dialami

Saat input data penduduk lewat menu keluarga, pilihan rt tidak bisa di pilih sehingga data tidak bisa di simpan.

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

24.04 Premium

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui commit https://github.com/OpenSID/premium/commit/8f2fe36e4d06482e3e134fcecdaeb2618a694e57 sebagai sebagai susulan setelah konversi
