### ISSUE TITLE
Bug/error: menampilkan Salinan Kartu Keluarga melalui menu Penduduk muncul 404

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#7869]
### Jelaskan error yg dialami

menampilkan Salinan Kartu Keluarga melalui menu Penduduk muncul 404

### Cara untuk mereplikasi errornya

klik menu kependudukan/penduduk klik nomor KK maka akan muncul 404
sedangkan kalau melalui menu keluarga normal

### Hasil yg diharapkan

muncul salikan kartu keluarga seperti di menu keluarga atau seperti versi sebelumnya

### Tangkapan layar dan log error

saya cek di berputar juga sama

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

24.04.0.1

**Comment by ariandii** [comment]
https://github.com/OpenSID/OpenSID/issues/7861

**Comment by MUHAMMADRANGSEL** [comment]
saya close bang
