### ISSUE TITLE
TIDAK ADA PENGATURAN AKSES PENGGUNA UNTUK BUKU ADMINISTRASI UMUM

### ISSUE THREAD

**Issue by pujocahyono** [OpenSID/OpenSID#7870]
### Jelaskan error yg dialami

TIDAK ADA PENGATURAN AKSES PENGGUNA UNTUK BUKU ADMINISTRASI UMUM (BUKU PERATURAN, KEPUTUSAN, DLL) SEHINGGA PENGGUNA SELAIN ADMIN TIDAK MEMILIKI IJIN AKSES HALAMAN.

### Cara untuk mereplikasi errornya

1. MASUK DENGAN AKUN PENGGUNA SELAIN ADMIN
2. BUKU ADMINISTRASI DESA
3. ADMINISTRASI UMUM 

### Hasil yg diharapkan

KEMBALI NORMAL

### Tangkapan layar dan log error

![Cuplikan layar 2024-04-22 104302](https://github.com/OpenSID/OpenSID/assets/87228587/0eb6b91c-81d1-4c22-a1c7-541893656f6b)
![Cuplikan layar 2024-04-22 104217](https://github.com/OpenSID/OpenSID/assets/87228587/efeb09ad-5963-4579-b283-190628f3c973)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2404.0.1

**Comment by andifahruddinakas** [comment]
![image](https://github.com/OpenSID/OpenSID/assets/57283157/7c79f30f-4505-4524-ad59-ff262379a241)

![image](https://github.com/OpenSID/OpenSID/assets/57283157/2e72d531-1583-4781-bf22-b173d77b33bc)

Sebaiknya di buat level dengan 3 tingkatan pada pengaturan gropnya.

**Comment by andifahruddinakas** [comment]
Untuk sementara hak aksesnya bisa mengikuti submodulnya

**Comment by andifahruddinakas** [comment]
Selesai melalui commit https://github.com/OpenSID/premium/commit/bdbf8c83b92a5741b4d08ac05bd851bb19415269
