### ISSUE TITLE
Bug/error: saat melakukan ubah kk pengisian RT tidak bisa pilih tanda "-", jadi tidak bisa melakukan ubah data KK

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#7872]
### Jelaskan error yg dialami

saat melakukan ubah kk pengisian RT tidak bisa pilih tanda "-", jadi tidak bisa melakukan ubah data KK

### Cara untuk mereplikasi errornya

1. Klik menu Kependudukan
2. Klik sub menu Keluarga
3. klik ubah data - pada salah satu penduduk

### Hasil yg diharapkan

saat ubah data dapat memili tanda "-" pilihan RT karena pada Desa yang di Bali tidak menggunakan RT dan RW hanya menggunakan Dusun. 

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/55429781/c89bf1d2-d2b7-42a3-a48a-ccebb59ce8ca)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Versi 2404.0.1-premium

**Comment by andifahruddinakas** [comment]
Duplicate issue https://github.com/OpenSID/OpenSID/issues/7867, kasus yang sama
