### ISSUE TITLE
Detail Statistik RTM > BDT

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#7874]
Statistika RTM > BDT, 
![image](https://github.com/OpenSID/OpenSID/assets/57283157/bfea2477-e7c1-4afb-be70-126bc75d0144)

Detailnya berbeda
![image](https://github.com/OpenSID/OpenSID/assets/57283157/eaaa663d-82fb-4253-be38-0fc5d6885bb6)

Jika dilihat, statistik juga menghitung Rumah tanggah yang Kepala RT nya tidak ada.
![image](https://github.com/OpenSID/OpenSID/assets/57283157/29cbbb68-ed09-4c54-8466-21ad46b265a8)

**Comment by yogiperdana** [comment]
kalau tidak ada kepala rtm bukannya berarti data tidak valid mas? artinya ada yang mengganggu database. dengan demikian bukan termasuk bug melainkan kesalahan pada pengguna yang tidak sengaja menghapus kepala rtmnya langsung di database
