### ISSUE TITLE
Bug/error: PENULISAN KATA NIK/ NO. KTP berubah setelah disimpan

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#7876]
### Jelaskan error yg dialami

ketika membuat form penduduk luar Desa kata NIK/No. KTP terdapat perbedaan sebelum dengan setelah disimpan

### Cara untuk mereplikasi errornya

masuk di menu layanan surat
klik pengaturan surat
klik Form Penduduk Luar Desa
klik tombol tambah form Penduduk Luar Desa 
Centang semua pilihan input yang muncul NIK/No. KK
setelah disimpan muncul no_ktp
![Screenshot 2024-04-25 190532](https://github.com/OpenSID/OpenSID/assets/25834335/2cd47b5c-274f-472d-8e22-def50484357e)

![Screenshot 2024-04-25 190548](https://github.com/OpenSID/OpenSID/assets/25834335/7006d3ae-ce8f-429a-abb3-4e8fbf315805)

### Hasil yg diharapkan

menggunakan kata seragam dengan yang ada disistem atau no_ktp diganti dengan NIK 

### Tangkapan layar dan log error

![Screenshot 2024-04-25 190532](https://github.com/OpenSID/OpenSID/assets/25834335/b2e22ab1-219d-459f-8f5b-f11f211f125d)
![Screenshot 2024-04-25 190548](https://github.com/OpenSID/OpenSID/assets/25834335/c91eddd2-a0dd-4835-bc0d-f3f5573ce4f4)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

24.04.0.0

### Tema Yang Digunakan

bawan aplikasi

### Informasi tambahan

saya langsung coba disini https://devpremium.opendesa.id/surat_master/pengaturan

**Comment by andifahruddinakas** [comment]
mas @MUHAMMADRANGSEL, secara fungsi tidak ada masalah. adapun untuk perubahan ini yg perlu dilakukan sbb:

- [ ] simpan key dan value nya, contoh ['nama' => 'Nama', 'nik' => 'NIK / No. KTP]
