### ISSUE TITLE
Bug/error: Edit Data Buku Tamu error 500

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#7877]
### Jelaskan error yg dialami

Edit Data Buku Tamu error 500

### Cara untuk mereplikasi errornya

Edit Data Buku Tamu error 500

### Hasil yg diharapkan

normal

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

https://devpremium.opendesa.id/

### Tema Yang Digunakan

bawan aplikasi

### Informasi tambahan

https://devpremium.opendesa.id/

**Comment by andifahruddinakas** [comment]
Diperbaiki melalui commit https://github.com/OpenSID/premium/commit/37df9122ac3c0572e6ad43dda37103b4ca7edaee
