### ISSUE TITLE
Bug/error: Penulisan Alamat di Menu Kependudukan/ Penduduk dengan Keluarga berbeda

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#7879]
### Jelaskan error yg dialami

Penulisan Alamat di Menu Kependudukan/ Penduduk dengan Keluarga berbeda

### Cara untuk mereplikasi errornya

Penulisan Alamat di Menu Kependudukan/ Penduduk dengan Keluarga berbeda

### Hasil yg diharapkan

Penulisan alamat seperti yang ada di menu kependudukan ==> Penduduk spy seragam
![Screenshot 2024-04-26 153409](https://github.com/OpenSID/OpenSID/assets/25834335/c28d8cd8-347c-4d17-ad9e-6c77af0f0b68)

### Tangkapan layar dan log error

![Screenshot 2024-04-26 153409](https://github.com/OpenSID/OpenSID/assets/25834335/9e9a7c71-c544-4f81-9d14-05a25ddbd2a4)
![Screenshot 2024-04-26 153428](https://github.com/OpenSID/OpenSID/assets/25834335/b2043387-0a93-4851-8ddd-a79473b083ed)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Versi 2404.0.2-premium

### Tema Yang Digunakan

bawan aplikasi

### Informasi tambahan

https://berputar.opendesa.id/keluarga

**Comment by andifahruddinakas** [comment]
sudah siperbaiki memalui commit https://github.com/OpenSID/premium/commit/16c504e26c3340dfa5af3aa422236791a1ef7142 sebagai perbaikan susulan setelah konversi
