### ISSUE TITLE
TIDAK MEMILIKI IJIN AKSES SAAT KLIK LAPORAN SEMUA ASET PADA MENU INVENTARIS

### ISSUE THREAD

**Issue by pujocahyono** [OpenSID/OpenSID#7880]
### Jelaskan error yg dialami

SAAT KLIK LAPORAN SEMUA ASET PADA MENU INVENTARIS MUNCUL "Anda tidak memiliki akses untuk halaman tersebut!"

### Cara untuk mereplikasi errornya

1. MENU SEKRETARIAT
2. INVENTARIS
3. LAPORAN SEMUA ASET
![Cuplikan layar 2024-04-27 114427](https://github.com/OpenSID/OpenSID/assets/87228587/bd8d959c-e5af-4f4c-99c6-105977e45dd6)

### Hasil yg diharapkan

NORMAL

### Tangkapan layar dan log error

![Cuplikan layar 2024-04-27 114438](https://github.com/OpenSID/OpenSID/assets/87228587/8b81b1a7-abb9-4083-af81-076b3c44a038)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2404.0.2

**Comment by andifahruddinakas** [comment]
sudah di perbaiki melalui commit https://github.com/OpenSID/premium/commit/13a2b5368c8e5cf139288fe740ff1903d902f75e
