### ISSUE TITLE
penambahan pengaturan surat dinas

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#7882]
Perlu ditambahkan pengaturan surat dinas sbb:

- [ ] Penomoran Surat
- [ ] Panjang Nomor Surat

Catatan : 
- [ ] untuk pengaturan diletakkan di pengaturan surat dinas (pindahkan juga pengaturan surat layanan krn letaknya sama)
- [ ] Penomoran Surat, tambahkan pilihan baru yakni : **nomor berurutan untuk masing-masing klasifikasi surat yang sama**
- [ ] Sesuaikan juga penerapannya di surat dinas untuk pengaturan tsb

**Comment by andifahruddinakas** [comment]
pak @ariandii, bisa ditambahkan jika ada yang kurang

**Comment by andifahruddinakas** [comment]
Contoh:
![image](https://github.com/OpenSID/OpenSID/assets/57283157/c001e4b0-ef0a-47ee-a8b1-46383192a470)

Misalkan : 
1. Ada Surat Keterangan Pengantar dengan No Surat 1
2. Buat surat lg Keterangan Penduduk dengan No Surat 2
3. Buat Surat lg Keterangan Pengantar dengan No Surat 3
4. Buat Surat lg Keterangan Pengantar dengan No Surat 4
5. Buat surat lg Keterangan Penduduk dengan No Surat 5

**Comment by ariandii** [comment]
Tambahan

Misal ada Kodefikasi 900 dengan beberapa surat berikut:
1. Surat Laporan Konfirmasi Transfer nomor surat 88
2. Surat Pengantar Pencairan Dana nomor surat 89
3. Surat Permohonan Rekomendasi Pencairan Dana nomor surat 90
4. dan surat lainnya yang berkaitan keuangan dengan kodefikasi 900.

Juga misal Kodefikasi 500 untuk Undangan
1. Surat Undangan Musyawarah
2. Surat Undangan Rapat
3. Surat Undangan Sosialisasi
4. dll

Juga misal surat umum kodefikasi 000
1. Surat Himbauan
2. Surat pemberitahuan
3. Surat Panggilan
4. dll
