### ISSUE TITLE
Bug/error: ketika membuat surat setelah di pdf dan merubah data penduduk dari hidup ke mati tidak bisa di save

### ISSUE THREAD

**Issue by hamzannawawi** [OpenSID/OpenSID#7883]
### Jelaskan error yg dialami

[surat-keterangan-izin-orang-tua-suami-istri_5202050107620677_2024-04-23_10.pdf](https://github.com/OpenSID/OpenSID/files/15144478/surat-keterangan-izin-orang-tua-suami-istri_5202050107620677_2024-04-23_10.pdf)

### Cara untuk mereplikasi errornya

![Screenshot_394](https://github.com/OpenSID/OpenSID/assets/168386273/00af8349-38b9-4787-87df-b3819c5b056b)

### Hasil yg diharapkan

[surat-keterangan-izin-orang-tua-suami-istri_5202056602050005_2024-03-25_6.pdf](https://github.com/OpenSID/OpenSID/files/15144481/surat-keterangan-izin-orang-tua-suami-istri_5202056602050005_2024-03-25_6.pdf)

### Tangkapan layar dan log error

![Screenshot_394](https://github.com/OpenSID/OpenSID/assets/168386273/fd1c62d9-490a-4e3d-ae9e-32c2a2c4a094)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2404.0.1-Premium

### Tema Yang Digunakan

natra

### Informasi tambahan

beberapa form surat bermasalah

**Comment by andifahruddinakas** [comment]
mas @hamzannawawi, bisa di cekkan bagian ini:
![image](https://github.com/OpenSID/OpenSID/assets/57283157/61a10e28-606c-49a9-8009-64ea8960a516)

**Comment by hamzannawawi** [comment]
dubagian mana kita buka itu

**Comment by andifahruddinakas** [comment]
> dubagian mana kita buka itu

pengaturan surat > buka surat (mis: surat keteranngan .... ) > pilih tab form isian
