### ISSUE TITLE
Hak Akses Wilayah Modul Peristiwa

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#7887]
![image](https://github.com/OpenSID/OpenSID/assets/57283157/df9b8d44-f3c1-460e-8b89-0aaaa0df568b)

Cek modul penduduk untuk contoh penerapannya.

**Comment by andifahruddinakas** [comment]
Kerjakan setelah PR konversinya sudah digabungkan.

**Comment by pandigresik** [comment]
Otomatis mengikuti hak akses yang telah dikerjakan ketika konversi di PR https://github.com/OpenSID/premium/pull/3664
