### ISSUE TITLE
saat mengubah status dasar penduduk maka jumlah penduduk tidak berkurang 

### ISSUE THREAD

**Issue by mranca** [OpenSID/OpenSID#7893]
### Jelaskan error yg dialami

jumlah penduduk tidak berkurang saat ubah status dasar misalnya pindah 

### Cara untuk mereplikasi errornya

1. masuk admin
2. pilih aksi salah satu penduduk 
3. ubah status dasar
4. pilih pindah 
5. isi dan simpan

### Hasil yg diharapkan

seharunya data penduduk yang hidup akan berkurang sesasui data yang pidah 

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/76085245/f6852154-68ad-48bd-ab25-ebc7e5000b3f)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

devpremium.opendesa.id

### Tema Yang Digunakan

-

### Informasi tambahan

-

**Comment by andifahruddinakas** [comment]
mas @mranca, sy coba aman saja.

https://drive.google.com/file/d/1AfY_cFQzRc_hAOUalgqFdeQ5cfDjowPE/view?usp=sharing

bisa dibuka kembali jika masih mengalami kendala

**Comment by mranca** [comment]
Oke di close bung @andifahruddinakas  mungkin pengaruh jaringan td waktu saya coba
