### ISSUE TITLE
Permintaan fitur: Sediakan grup pengguna sesuai tupoksi perangkat desa

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#7895]
### Apa kekurangan yg ingin diatasi?

Saat ini grup pengguna yg disediakan tidak memperhatikan atau sesuai dengan tupoksi perangkat desa. Penyediaan grup pengguna sesuai tupoksi penting untuk memudahkan pembuatan akun bagi perangkat desa. Supaya semua perangkat desa menggunakan OpenSID sesuai tupoksi masing2.

### Jelaskan solusi yg diinginkan

Sediakan grup pengguna dengan hak akses sesuai tupoksi masing2 perangkat desa. Konsep awal sbb:

### Tugas Fungsi Pengelola Aplikasi OpenSID

Kepala Desa bertugas sebagai penangung jawab dari semua isi aplikasi SID

1. **Admin   1   (Sekretaris   Desa)**   

bertugas   memantau   dan monitoring pekerjaan masing – masing user, serta memberikan pengarahan terkait tata cara pengoperasian masing-masing menu OpenSID;

2. **Admin  2  (Kaur  Perencanaan)**  

bertugas  untuk    update berita,   edit   kontent,   edit   menu,   sub   menu,   artikel, pemetaan wilayah desa, wilayah RW dan RT pada menu pemetaan  desa dan  update versi untuk OpenSID online dan offline, serta menyamakan konten antara keduanya. Tugas lain Admin 1 adalah membantu Admin 2 dalam memberi pengarahan dan penjelasan tata cara pengerjaan pada masing-masing user;

3. **User   1   (Kasi   Pemerintahan)**   

bertugas   entry   data kependudukan (lahir, mati, datang, pergi), cetak Laporan Perkembangan Penduduk Bulanan, Entry data Produk Hukum Desa (Perdes, Keputusan Kepala Desa), Entry data Pertanahan;

4. **User 2 (Kasi Pelayanan)** 

bertugas Entry Data Pelayanan Umum khususnya surat-menyurat, cetak laporan surat masuk, surat keluar, serta membantu User 3 dalam pendataan penduduk miskin;

5. **User 3 (Kasi Kesejahteraan)** 

bertugas entry data penduduk miskin (BDT, PKH, non PKH), Analisis Kemiskinan, Penerima  Bantuan  RTLH,  data  penerima  jamkesos,  dan lain sebagainya;

6. **User 4 (Kaur Umum dan Perencanaan)**

 bertugas entry data Inventaris Desa untuk per jenis barang, mesin dan bangunan, Mencetak Kartu Inventaris Ruangan, Mencetak Nomor Register Barang, serta membuat laporan inventaris desa;

7. **User 5 (Kaur Keuangan)** 

bertugas import data keuangan dari Siskeudes ke Opensid, dan atau membuat laporan pendapatan, belanja, pembiayaan per semester;

8. **User 6 (Kepala Dusun)** 

bertugas membantu input data dari Kasi Pemerintahan, Kasi Pelayanan, Kasi Kesejahteraan, Kaur Umum dan Perencanaan, dan Kaur Keuangan.

### Apakah ada alternatif lain

Grup pengguna yg ada saat ini tidak cukup. Alternatif lain adalah supaya masing2 desa membuat grup pengguna sendiri2 sesuai tupoksi perangkat desa. Tetapi cara ini tidak efisien di mana setiap desa harus mengulangi sesuatu yg dapat disediakan sebagai default, karena ketentuan tupoksi perangkat desa seragam di semua desa. 

### Untuk versi OpenSID mana

2306-premium

### Informasi tambahan

Pegiat Rohman dapat berperan sebagai nara sumber terkait kebutuhan ini. Desa Rohman telah menerapkan dan dapat dimintai spesikasi grup pengguna mereka sebagai solusi awal untuk disesuaikan.

**Comment by Zoel-WB** [comment]
System group seperti ini sangat mendukung sekali untuk mengarah tugas secara langsung pada masing2 perangkat desa, dan saya kira teknik sangat bagus.

Cuma permintaan dari saya untuk system atau model admin utama yg dapat membuka dan menjalankan semua  semua fitur untuk sementara tetap dipertahankan karena masih banyak desa-desa yg masih di kerjakan oleh operator desa ataupun perangkat desa yg menguasai system informasi, karena didesa desa lebih2 desa tertinggal dan berkembang masih banyak perangkat desa yg belum menguasai teknologi semacam system informasi.

**Comment by rohmanudin05** [comment]
Siap, semoga dengan adanya Grup ini kita bisa mengoptimalkan kinerja perangkat desa, dan terus berkesinambungan pemakaian opensid premium secara SUSTAINABLE, kelemahan opensid tidak berkembang ada beberapa faktor, dianataranya opensid di serahkan sepenuhnya pada operator desa, yang mengakibatkan, hanya operator yang di wajibkan untuk mengetahui **TUPOKSI** perangkat desa yg ada di **OPENSID.**

![power_point](https://github.com/OpenSID/OpenSID/assets/61618963/6a49e2b5-1b05-4149-af19-070d251c35fc)

https://bit.ly/3xSQuZ6
Catatan:
             Slide Tupoksi Perangkat Desa Hal 14.

**Comment by balongbesuk** [comment]
utuk opsi pengaturan pengguna yang dinamis semoga masih tetap dipertahankan, 

semoga pengaturan hak akses masih bs fleksibel karena tupoksi terkadang menyesuaikan SDM Perangkat masing masing,

**Comment by eddieridwan** [comment]
Grup bawaan sistem seperti biasa dapat disesuaikan kebutuhan desa. Dengan
adanya grup bawaan, akan mempercepat prosesnya.

**Comment by yolisubhan** [comment]
untuk user 2 lebih tepatnya sesuai dengan Peraturan Menteri Dalam Negeri Republik Indonesia Nomor 84 Tahun 2015 Tentang Susunan Organisasi Dan Tata Kerja Pemerintah Desa dipegang oleh Kaur Tata Usaha dan Umum bukan kasi pelayanan

**Comment by balongbesuk** [comment]
> untuk user 2 lebih tepatnya sesuai dengan Peraturan Menteri Dalam Negeri Republik Indonesia Nomor 84 Tahun 2015 Tentang Susunan Organisasi Dan Tata Kerja Pemerintah Desa dipegang oleh Kaur Tata Usaha dan Umum bukan kasi pelayanan

saya jadi inget ada peraturan tentang tingkatan desa yang berdampak pada jumlah kaur dan kasi, untuk peraturan perundang undangannya masih belum nemu, cm nemu peraturan d tingkat kabupaten / kota

BAB III
 JENIS DESA
Pasal 15
(1) Susunan organisasi Pemerintah Desa disesuaikan dengan tingkat
perkembangan desa yaitu Desa Swasembada, Swakarya, dan
Swadaya.
(2) Desa Swasembada wajib memiliki 3 (tiga) urusan dan 3 (tiga) seksi.
(3) Desa Swakarya dapat memiliki 3 (tiga) urusan dan 3 (tiga) seksi.
(4) Desa Swadaya memiliki 2 (dua) urusan dan 2 (dua) seksi.

dengan ada jenis / tingkatan desa tersebut maka akan berdampak pula pada peraturan grup pengguna yang akan diterapkan pada opensid

![1726179205-perbup-5---2017-susunan-organisasi-dan-tata-kerja-pemerintah-desa_001](https://github.com/OpenSID/OpenSID/assets/35319600/9b4d5e60-97aa-4105-91bc-d3b383f172ef)
![1726179205-perbup-5---2017-susunan-organisasi-dan-tata-kerja-pemerintah-desa_002](https://github.com/OpenSID/OpenSID/assets/35319600/2ba527b1-3921-4b64-9e80-2242e570594d)
![1726179205-perbup-5---2017-susunan-organisasi-dan-tata-kerja-pemerintah-desa_003](https://github.com/OpenSID/OpenSID/assets/35319600/07848c0c-7b6d-4652-9a60-c66a828b32cd)

**Comment by andifahruddinakas** [comment]
pembagian grup bisa dilihat disni
https://docs.google.com/spreadsheets/d/1-S3QPcyIry0jodXmNqIOHMa6QsvWjcYTyIj8EcMOmHY/edit#gid=4236951
