### ISSUE TITLE
Tidak dapat login karena adanya proteksi csrf pada server tertentu.

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/OpenSID#7897]

**Comment by pandigresik** [comment]
Mungkin disebabkan nilai csrf pada form beda dengan yang di server, sempat mengalami hal seperti itu pada fitur import excel penduduk

https://github.com/OpenSID/premium/pull/3683/files#diff-cab09bb5fa952792efb81d942be63476b83b82b2f442d0904da77db572299988

**Comment by scqolbu24** [comment]
![csrf](https://github.com/OpenSID/OpenSID/assets/68048807/3625c4a0-b220-4544-93a3-749e1b390cad)

**Comment by pandigresik** [comment]
> ![csrf](https://private-user-images.githubusercontent.com/68048807/331030239-3625c4a0-b220-4544-93a3-749e1b390cad.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4MzI1NjcsIm5iZiI6MTcxNTgzMjI2NywicGF0aCI6Ii82ODA0ODgwNy8zMzEwMzAyMzktMzYyNWM0YTAtYjIyMC00NTQ0LTkzYTMtNzQ5ZTFiMzkwY2FkLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE2VDA0MDQyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3Njk1M2JkNDNkOGE4OTU2NWU3N2QxNmMyZGIwZmU5YzRlODlhNzYwYmU0YjFkNzQ2NmMwYzdmMmQ3ZGUxMzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Dc4oYEa2yIyltjZxZLos8_SithvvYC9gIZ_GPCSHvL4)

error tersebut karena csrf posisinya di non-aktifkan
![image](https://github.com/OpenSID/OpenSID/assets/1853475/99118ab6-0775-4e98-91e7-0597f9f0564c)

**Comment by andifahruddinakas** [comment]
selesai melalui commit https://github.com/OpenSID/premium/commit/e6e7377247f39ae0a0d84638ac0f86dde3294f6b
