### ISSUE TITLE
Link Detail Pada WIlayah Salah

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#7898]
<img width="731" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/71103e08-951f-4f2a-b6ca-43d58373130a">

Hasilnya menjadi 404 saat di klik
![image](https://github.com/OpenSID/OpenSID/assets/57283157/bb76fb6e-6d8d-4799-8986-1bcce01da8ad)

**Comment by langonsari** [comment]
- [ ] untuk yang User Kewilayahan Aktif nama Dusun dan RW tetap bisa terlihat.

- [ ] Apabila terlihat dubuat automatis terfilter ke tingkatan Wilayah sesuai pengaturan User.
