### ISSUE TITLE
Perlu adanya fasilitas Impor/ekspor data di sub menu Data Suplemen

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#790]
Untuk memudahkan operator atau pemerintah desa dalam memasukkan data perlu ditambahkan fasilitas impor dan ekspor data di menu Data Suplemen mengingat data yang dimasukkan berbasis Penduduk (NIK), Keluarga (KK)
![image](https://user-images.githubusercontent.com/25834335/36075277-94aca066-0f87-11e8-8319-aeb54bb50859.png)

**Comment by MUHAMMADRANGSEL** [comment]
Format Impor
1. Data Suplemen Sasaran Penduduk
[FormatImport_data_suplemen_penduduk.zip](https://github.com/OpenSID/OpenSID/files/1799291/FormatImport_data_suplemen_penduduk.zip)

2. Data Suplemen Sasaran Kepala Keluarga (KK)
[FormatImport_data_suplemen_KK.zip](https://github.com/OpenSID/OpenSID/files/1799292/FormatImport_data_suplemen_KK.zip)

**Comment by MUHAMMADRANGSEL** [comment]
Mohon ini di kerjakan bung Eddie dan para programmer lainnya

**Comment by afa28** [comment]
Apakah ini masih bermasalah / masih diperlukan??? Kalau tdk, silahkan di close.

**Comment by MUHAMMADRANGSEL** [comment]
Masih

Pada tanggal Sen, 24 Agt 2020 14.07, Andi Fahruddin Akas <
notifications@github.com> menulis:

**Comment by eddieridwan** [comment]
Sdh dicommit ke `rilis-dev` melalui https://github.com/OpenSID/premium/pull/111
