### ISSUE TITLE
Bug/error: Download PDF dari Arsip Layanan Surat tidak muncul

### ISSUE THREAD

**Issue by RomziJazz** [OpenSID/OpenSID#7901]
### Jelaskan error yg dialami

Error terjadi jika verifikasi Sekretaris Desa di Aktifkan. 
Pada Kolom Permohonan masih bisa di Download, sedangkan ketika sudah diverifikasi oleh sekretaris desa, surat otomatis pindah ke Arsip dan surat tidak bisa di dowload lagi (blank). Sudah di coba di berputar ternyata sama.
![image](https://github.com/OpenSID/OpenSID/assets/65128302/ac086e3c-8925-43e7-9383-6b444cd42bbc)

### Cara untuk mereplikasi errornya

1. Aktifkan Verifikasi Sekerataris Desa terlebih dahulu
2. Buat Surat pada menu Layanan Surat > Cetak Surat
3. Verifikasi di Arsip Layanan > Permohonan
4. Download lagi ketika sudah masuk di Arsip Layanan > Arsip
5. Blank Page akan muncul.
6. jika di buka di cpanelnya, file arsip memang hilang.

### Hasil yg diharapkan

Perbaikan Bug. sehingga tidak terjadi kehilangan arsip layanan

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/65128302/7f2bf279-ec5b-4e80-ade9-a66c7d25716a)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2405.0.1-Premium

**Comment by habibie11** [comment]
saya coba replikasi cara diatas, setelah verifikasi sekdes surat bisa diunduh di arsip, mas @andifahruddinakas
![image](https://github.com/OpenSID/OpenSID/assets/56639378/849af90c-dd80-4e9c-884c-e8f0eac4da91)
apa ada yang salah cara replikasi saya

**Comment by andifahruddinakas** [comment]
> saya coba replikasi cara diatas, setelah verifikasi sekdes surat bisa diunduh di arsip, mas @andifahruddinakas ![image](https://private-user-images.githubusercontent.com/56639378/330329796-849af90c-dd80-4e9c-884c-e8f0eac4da91.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3NDAxODcsIm5iZiI6MTcxNTczOTg4NywicGF0aCI6Ii81NjYzOTM3OC8zMzAzMjk3OTYtODQ5YWY5MGMtZGQ4MC00ZTljLTg4NGMtZThmMGVhYzRkYTkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE1VDAyMjQ0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2NjZiMzE4Nzc4YWMyMDkzODIzOTQ4YzliOTM1NTU5Y2I0OTIzNzU3Mzc3YTI5ZDM1MDAwMjFiOGRmZmUxNjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eA-QYC0kKDNwCuhEAI0BBNpAXWi2D8elgcen1bVpelU) apa ada yang salah cara replikasi saya

ini mas @habibie11, errornya tidak bisa buat ulang file pdf karena qrcodenya sudah tidak ada (hanya disimpan di tmp).

Html2Pdf Error [2]
Unable to get the size of the image [/tmp/qrcode_2024_01_03_15_06_05_temp.png] File: /home/berputar.opendesa.id/public_html/vendor/spipu/html2pdf/src/Html2Pdf.php Line: 1526 Image Src: /tmp/qrcode_2024_01_03_15_06_05_temp.png

Solusinya, buat ulang file qrcode (QRCOde OpenSID, bukan BSRE) setiap generate ulang surat (dimana jika file tdk ada)
https://berputar.opendesa.id/keluar/unduh/tinymce/102
