### ISSUE TITLE
Bug/error: Sesuaikan Angka pada Beranda dengan data aktual.

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#7904]
### Jelaskan error yg dialami

![2024-05-03_17h08_26](https://github.com/OpenSID/OpenSID/assets/46939846/99c9b65a-ae35-4c40-838c-5c58ab18fde1)

![2024-05-03_17h08_10](https://github.com/OpenSID/OpenSID/assets/46939846/00fd441a-70b0-4200-9767-47ddb7f426ea)

![image](https://github.com/OpenSID/OpenSID/assets/46939846/ebaa4f63-33f9-440d-ae43-2d2fddf15c0d)

### Cara untuk mereplikasi errornya

login aplikasi dan masuk menu
Pengaturan -> Shortcut

Tambah atau ubah Shortcut dengan memilih Jumlah Kepala Keluarga. seperti panah di gambar.

Hasil yang tampil ternyata seluruh kepada keluarga yang ada. (termasuk pindah, hilang, kosong dll)

Padahal jika diklik Lihat Detail, adalah Kepala Keluarga Aktif yang jumlahnya tidak sesuai dengan yang tampil di beranda.

### Hasil yg diharapkan

Sesuaikan seharusnya, jika saat diklik Lihat Detal adalah otomatis terfilter Keluarga Aktif, maka jumlah pada Beranda juga menampilkan angka Keluarga Aktif saja.

Begitu juga dengan Query Otomatis lainnya jika mengalami hal sama.

### Tangkapan layar dan log error

di atas

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2405.0.0-premium

**Comment by andifahruddinakas** [comment]
sama dengan point 2 pada issue https://github.com/OpenSID/OpenSID/issues/7902
