### ISSUE TITLE
Konversi Program Bantuan > Peserta menggunakan ORM dan Blade

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#7905]
![image](https://github.com/OpenSID/OpenSID/assets/57283157/8d74a397-bcfe-497e-b587-b9df00b6b626)

Ubah modul Program Bantuan > Peserta menggunakan orm dan blade untuk CRUD.

catatan : 
- [ ] hapus query lama
- [ ] hapus view lama dan gunakan blade (gunakan komponen blade; @if, @forrech, @select, dll)
- [ ] gunakan button non flat, untuk membedakan dengan modul yg sudah dikonversi
- [ ] sesuaikan kondisi terkait tte
- [ ] sederhanakan proses/fungsi yang rumit
- [ ] gunakan pengecekan hak akses yang baru

**Comment by habibie11** [comment]
ini saya lihat masih ada kode kode yang terhubung dengan modul program bantuan. mungkin bisa dikerjakan setelah https://github.com/OpenSID/premium/pull/3743 digabung
