### ISSUE TITLE
Layanan Mandiri --> Layanan

### ISSUE THREAD

**Issue by Hanisiti** [OpenSID/OpenSID#791]
di menu layanan mandiri, pengguna hanya bisa melakukan Laporan perubahan data dan melihat daftar rekam cetak surat. 

jika ditambah, pengguna bisa melakukan pelayanan pembuatan surat sendiri lebih bagus, 
tapi tidak bisa dicetak. harus tetap dicetak di kantor desa (terkait legalitas)

dikampung halaman saya, dalam satu desa terdapat 8 perumahan, warganya pada sibuk kurang punya waktu untuk ngurus data kependudukan, pegawai desa kerjanya juga banyak yg gak efektif...

**Comment by MUHAMMADRANGSEL** [comment]
Kalau Maslah ini kami kurang setuju kalau masyarakat langsung yg akan merubah datanya melalui layanan mandiri,, kami lebih setuju seperti apa yg ada sekarang ini Krn jangan sampai dengan diberikan nya fasilitas untuk bisa merubah datanya data penduduk akan jadi Amburadul

**Comment by MUHAMMADRANGSEL** [comment]
Mengapa kami TDK setuju Krn ketika masyarakat memiliki data yg beda dengan yang ada di Opensid lebih baik masyarakat langsung datang ke kantor desa dan minta lakukan perubahan dan perubahan itu TDK hanya sampai kantor desa tapi perlu di tindaklanjuti ke dinas dukcapil

**Comment by MUHAMMADRANGSEL** [comment]
Mengingat juga sekarang data masyarakat berbasis NIK yg SDH ditinggalkan oleh pemerintah pusat yang dimana perubahan data harus ditindaklanjuti ke Dinas Dukcapil shgg data desa dengan data di dinas dukcapil balance

**Comment by MUHAMMADRANGSEL** [comment]
Semoga Hanisiti bisa memahami Krn adanya regulasi yg harus di patuhi

**Comment by MUHAMMADRANGSEL** [comment]
Untuk pembuatan surat harus tetap dilakukan oleh pihak pemerintah desa

**Comment by iwanlib** [comment]
Meneruskan percakapan di grup facebook

https://mobile.facebook.com/groups/626787397486245?view=permalink&id=932029173628731&src=email_notif&_rdc=1&_rdr

Jadi pihak desa kami mengerti bahwa tidak boleh merubah data dukcapil dan memang tidak bisa connect ke databasenya dukcapil

Tapi ini untuk memudahkan surat menyurat pengantar ke dinas terkait

Bagaimana menurut Bapak?
Mohon tanggapannya

**Comment by MUHAMMADRANGSEL** [comment]
Ketika kita ingin supaya masyarakat itu sendiri yg buat surat yg menjadi persoalan sekarang di Opensid untuk penomoran surat itu belum secara otomatis dilakukan oleh sistem shgg persoalan ini akan membuat register surat keluar akan jadi kacau, terkecuali kalau penomoran surat itu dilakukan oleh sistem itu sendiri kemungkinan pembuatan surat oleh masyarakat itu baru bisa dilakukan atau diterapkan

**Comment by iwanlib** [comment]
Untuk penomoran dapat diinputkan secara manual atau diberi semacam petunjuk pengisian namun lebih fleksibel sehingga perangkat desa dapat mengubahnya sesuai dengan nomor surat desa masing-masing,

Seandainya jika dibuatkan semacam tabel tambahan khusus di database layanan mandiri yang di gunakan warga, mungkin kekacauan register surat keluar dapat diatasi,

Saya berharap tambahan ini bisa terlaksana di upgrade opensid yang akan datang
karena hal ini sangat vital

**Comment by eddieridwan** [comment]
Apakah ini sama dengan #2235, #398, #341, #1976?

Sepertinya fitur ini penting bagi banyak desa. Cara untuk mempercepat fitur ini adalah supaya desa2 yg memerlukan menganggarkan secara patungan, supaya kita bisa bayar programmer.

**Comment by eddieridwan** [comment]
Kita gunakan issue #2235 sebagai issue tunggal untuk layanan permohonan surat di Layanan Mandiri. Mohon gabungkan spesifikasi yg diperlukan ke issue tersebut.

**Comment by eddieridwan** [comment]
Sudah di commit sebagai fitur premium.
