### ISSUE TITLE
Bug/error: Data Lampiran Surat Keterangan Nikah menghilang setelah Surat di Verifikasi Operator (Modul TTE Aktif)

### ISSUE THREAD

**Issue by langonsari** [OpenSID/OpenSID#7910]
### Jelaskan error yg dialami

Seluruh Data Lampiran N1 - N6, SPS, SWN menghilang setelah diverifikasi pada Opensid dengan Modul TTE aktif kecuali (Identitas Desa, Tanggal Pembuatan, Kepala Desa) tidak hilang.

**Sebelum diVerifikasi**
![image](https://github.com/OpenSID/OpenSID/assets/96863107/a7f00753-79f7-42f7-9c42-367080ad5af2)

**Setelah diVerifikasi**
![image](https://github.com/OpenSID/OpenSID/assets/96863107/c78cb86d-35d9-41c2-9608-ac2e1a804473)

### Cara untuk mereplikasi errornya

Pada Menu Pelayanan Surat >> Arsip Layanan Surat >> Permohonan
Klik Verifikasi
sebelum diverifikasi pada saat Cetak Surat file PDF sudah terdownload otomatis dan isi Data Pemohon, Pasangan dan Orang Tua masih lengkap namun setelah diklik Verifikasi Data Pemohon Pasangan Calon dan Orang Tua hilang menjadi "-"

### Hasil yg diharapkan

Data pada PDF setelah verifikasi baik oleh operator, Sekretaris Desa maupun Kepala Desa tetap terisi data Lengkap sesuai inputan.

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/96863107/be66836a-cf0a-4046-a22c-19def0985d7d)
![image](https://github.com/OpenSID/OpenSID/assets/96863107/dc3d7a95-538a-4519-81bd-809bd049d1ef)
![image](https://github.com/OpenSID/OpenSID/assets/96863107/b1ca3332-0111-432e-8e7d-de206dc1e426)
![image](https://github.com/OpenSID/OpenSID/assets/96863107/4c0cf5a3-1fcf-49e1-a1c3-7ea47c3e27f7)
![image](https://github.com/OpenSID/OpenSID/assets/96863107/a362388b-b890-46da-b196-349273246150)
![image](https://github.com/OpenSID/OpenSID/assets/96863107/ab5f3ce9-c5a1-4a00-a985-c7f07d95b038)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2405.0.0-premium

### Tema Yang Digunakan

Denava

### Informasi tambahan

Termasuk Error pada Lampiran Surat Keterangan Pindah (F-1.03, F-1.08, F-1.25, F-1.27) maupun Surat Keterangan yang memiliki **lebih dari 1 Lampiran Surat**

**Comment by andifahruddinakas** [comment]
Duplicate of https://github.com/OpenSID/OpenSID/issues/7788, silahkan perbarui tempate suratnya berdasarkan perubahan bawaan sistem
