### ISSUE TITLE
Gagal Impor BIP

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#7911]
Masuk ke modul penduduk > Impor BIP dan lakukan impor penduduk menggunakan data excel yg sudah disediakan.

Maka akan terjadi halaman blank putih, dengan log error : 
`ERROR - 2024-05-06 15:20:57 --> Severity: error --> Exception: Argument 1 passed to GetInt4d() must be of the type array, string given, called in D:\PROJECT OPENDESA\OpenSID\donjo-app\libraries\Spreadsheet_Excel_Reader.php on line 118 D:\PROJECT OPENDESA\OpenSID\donjo-app\libraries\Spreadsheet_Excel_Reader.php 55`

karena menggunakan librari lama, sebaikknya di perbarui jg dengan librari openspout yg selalu di perbarui dan digunakan di OPenSID saat ini. Contoh impor bisa cek pada modul klasifikasi surat.

Format excel yg digunakan terlampir. https://drive.google.com/drive/folders/1HG7S4siG0vykcuZbXBqGpVX1uV_coK8W

**Comment by yogiperdana** [comment]
https://github.com/nuovo/spreadsheet-reader/blob/master/php-excel-reader/excel_reader2.php

**Comment by andifahruddinakas** [comment]
> https://github.com/nuovo/spreadsheet-reader/blob/master/php-excel-reader/excel_reader2.php

mas @yogiperdana, buat saja PRnya untuk mengembalikan ke versi tsb. sepertinya terjadi perubahan oleh rector yg menyebabkan beberapa function jd strict.

hal yg lain perlu ditambahkan, pada config rector tambahkan file tsb agar tidak diubah.
![image](https://github.com/OpenSID/OpenSID/assets/57283157/49a9ecf7-be35-47e0-8af8-b6fa31945475)

tambahkan jg pada php-csfixer
![image](https://github.com/OpenSID/OpenSID/assets/57283157/fcd492de-0e54-4221-af2a-78e0f0b1cddc)
