### ISSUE TITLE
Data Bawaan Analisis (Prodeskel)

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#7914]
Hapus data bawaan dari modul analisis :
![image](https://github.com/OpenSID/OpenSID/assets/57283157/99469cb0-233b-4691-ad54-f647c09c2dba)

cek yg dihapus :
- [x] ubah status dari sistem jadi tambahan desa agar tombol hapus tampil (bisa dihapus sendiri oleh pengguna) melalui migrasi
- [x] hapus tambah data awal

**Comment by MUHAMMADRANGSEL** [comment]
kenapa ini dihapus bang

**Comment by andifahruddinakas** [comment]
> kenapa ini dihapus bang

Yg dihapus adalah data bawaannya, bagi yg sdh menggunakan datanya tdk terhapus, cuma disediakan tombol hapus krn bukan bawaan sistem lg.
