### ISSUE TITLE
Permintaan fitur: IZINKAN PENULISAN HURUP DAN TANDA / PADA WILAYAH ADMINISTRASI SEMISAL WILAYAH RT

### ISSUE THREAD

**Issue by utay-cugung** [OpenSID/OpenSID#7916]
### Apa kekurangan yg ingin diatasi?

Saat ini penulisan alamat RT hanya boleh berupa angka, padahal di lapangan ada beberapa yg penulisan nya berupa Hurup
 Misal Sebagai Berikut:
![image](https://github.com/OpenSID/OpenSID/assets/155012206/54bc6dd7-22b1-4127-8983-8d97c9f8d787)

### Jelaskan solusi yg diinginkan

Izinkan penulisan angka dan Huruf pada penulisan wilayah administratif semisal RW/RT

![image](https://github.com/OpenSID/OpenSID/assets/155012206/bc7df81e-6991-4e84-9757-d954dee8f645)

### Apakah ada alternatif lain

Tidak ada, karena sudah melekat pada dokumen kependudukan di beberapa desa dan jika harus update KK akan membutuhkan biaya besar dan merusak data kependudukan warga yg sudah jadi

### Untuk versi OpenSID mana

semua versi

### Informasi tambahan

Mohon segera di tindak lanjuti karena kesulitan menyusun database penduduk

By. tim smartvillage lampung

**Comment by andifahruddinakas** [comment]
penambahan karakter /
