### ISSUE TITLE
Bug/error: Sesuaikan dan gabungkan dalam satu kesatuan Rentang Umur dan kategori umur OpenSID menjadi kelompok umur sesuai dg kependudukan dispendukcapil

### ISSUE THREAD

**Issue by mah-mudi** [OpenSID/OpenSID#7918]
### Jelaskan error yg dialami

Rentang Umur dan kategori umur OpenSID belum sesuai kelompok umur kependudukan dispendukcapil

### Cara untuk mereplikasi errornya

Rentang Umur dan kategori umur

### Hasil yg diharapkan

Rentang Umur dan kategori umur OpenSID jadikan satu menjadi kelompok umur sesuai kependudukan dispendukcapil

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/57661283/f6a1ab8d-44bc-4da1-8c78-d3842f94fe79)

![image](https://github.com/OpenSID/OpenSID/assets/57661283/a46c0675-a27c-47e1-b5f5-7264be239040)

![image](https://github.com/OpenSID/OpenSID/assets/57661283/b242f718-7063-4282-9551-d9533b02634a)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

24.05

### Tema Yang Digunakan

silir

### Informasi tambahan

http://dindukcapil.rembangkab.go.id/data/kelompok_umur

**Comment by andifahruddinakas** [comment]
pak @mah-mudi, yang disediakan di OpenSID sudah sesuai baik itu data berupa penduduk berdasarkan rentang umur maupun kategori umum. Sy cek yang diharapkan adalah pada bagian rentang umur (OpenSID) sebutannya pada dukcapil yakni kategori umur, sedangkan di OpenSID sudah ada kategori. hal lain, data-data terkait rentang umur tsb bisa disesuaikan sendiri oleh pengguna melalui halaman yang disediakan.

![image](https://github.com/OpenSID/OpenSID/assets/57283157/a154b80d-4435-4bb2-8163-670505cd72c0)
