### ISSUE TITLE
Bug/error: link belum mengisi, tidak menampilkan data sebenarnya, tp menampilkan data keseluruhan penduduk

### ISSUE THREAD

**Issue by mah-mudi** [OpenSID/OpenSID#7919]
### Jelaskan error yg dialami

link belum mengisi, tidak menampilkan data sebenarnya, tp menampilkan data keseluruhan penduduk

### Cara untuk mereplikasi errornya

1. statistik kependudukan
2. belum mengisi

### Hasil yg diharapkan

link belum mengisi dapat menampilkan data sebenarnya

### Tangkapan layar dan log error

[screen-capture (13).webm](https://github.com/OpenSID/OpenSID/assets/57661283/922b8c49-9cbc-4179-b194-a58b6c244c2f)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

24.05

### Tema Yang Digunakan

silir

### Informasi tambahan

-

**Comment by andifahruddinakas** [comment]
pak @mah-mudi, sepertinya ini terkait database. dari perhitungnya `BELUM MENGISI = TOTAL - JUMLAH`. bisa bantu cekkan dibagian kolom tanggal lahir pada tabel tweb_penduduk atau bisa sertakan database yg digunakan melalui telegram. alternative lain error ini bisa diduplikasikan ke https://berputar.opendesa.id

**Comment by mah-mudi** [comment]
@andifahruddinakas sdh aq kirim lewat telegram

**Comment by andifahruddinakas** [comment]
bagian perhitungan (jumlah) yg berbeda sbb:
<img width="591" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/459afbb3-dcda-4fb9-b041-04adb29f6f1d">

bisa gunakan database terlampir.

cek bagian cara hitung menggunakan query dan php. gunakan waktu 23:59:59 sebagai batas 1 hari.

**Comment by yogiperdana** [comment]
> bagian perhitungan (jumlah) yg berbeda sbb: <img alt="image" width="591" src="https://private-user-images.githubusercontent.com/57283157/330137267-459afbb3-dcda-4fb9-b041-04adb29f6f1d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2NzA5MjMsIm5iZiI6MTcxNTY3MDYyMywicGF0aCI6Ii81NzI4MzE1Ny8zMzAxMzcyNjctNDU5YWZiYjMtZGNkYS00ZmI5LWIwNDEtMDRhZGIyOWY2ZjFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE0VDA3MTAyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwMzcyN2UyN2YwZGQ2YjA3MjY4YjczMWM5ZDQ2YzdhYzEzMDk3ZjJiNDViNjRjZGMzMjJlMzAwMDZhYjg1ZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QDW_PKM9nNZI2g2UeDyh1Vyp94BQNxB_LZ3F2KQFX3w">
> 
> bisa gunakan database terlampir.
> 
> cek bagian cara hitung menggunakan query dan php. gunakan waktu 23:59:59 sebagai batas 1 hari.

berarti bugnya itu lebih ke query jumlah itu kan ya mas karena harusnya kolom belum mengisi selalu 0 sedangkan kolom jumlah dan total selalu sama jumlahnya

**Comment by yogiperdana** [comment]
oh iya mas @andifahruddinakas tolong kirim databasenya

**Comment by andifahruddinakas** [comment]
> > bagian perhitungan (jumlah) yg berbeda sbb: <img alt="image" width="591" src="https://private-user-images.githubusercontent.com/57283157/330137267-459afbb3-dcda-4fb9-b041-04adb29f6f1d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2NzA5MjMsIm5iZiI6MTcxNTY3MDYyMywicGF0aCI6Ii81NzI4MzE1Ny8zMzAxMzcyNjctNDU5YWZiYjMtZGNkYS00ZmI5LWIwNDEtMDRhZGIyOWY2ZjFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE0VDA3MTAyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwMzcyN2UyN2YwZGQ2YjA3MjY4YjczMWM5ZDQ2YzdhYzEzMDk3ZjJiNDViNjRjZGMzMjJlMzAwMDZhYjg1ZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QDW_PKM9nNZI2g2UeDyh1Vyp94BQNxB_LZ3F2KQFX3w">
> > 
> > bisa gunakan database terlampir.
> > 
> > cek bagian cara hitung menggunakan query dan php. gunakan waktu 23:59:59 sebagai batas 1 hari.
> 
> berarti bugnya itu lebih ke query jumlah itu kan ya mas karena harusnya kolom belum mengisi selalu 0 sedangkan kolom jumlah dan total selalu sama jumlahnya

Untuk cara perhitungan total, belum mengisi dan jumlah sdah sesuai (krn sifatnya global untuk statistik). Ini terkait cara perhitungan umurnya.
