### ISSUE TITLE
Bug/error: wajib identitas berubah

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#7921]
### Jelaskan error yg dialami

ketika klik ubah biodata penduduk maka wajib KTP kosong padahal sudah terisi, sehingga harus melakukan pengisian ulang

### Cara untuk mereplikasi errornya

masuk ke menu penduduk klik ubah biodata penduduk maka wajib identitas menjadi kosong

### Hasil yg diharapkan

terisi seperti biasanya

### Tangkapan layar dan log error

![Screenshot 2024-05-09 132959](https://github.com/OpenSID/OpenSID/assets/25834335/e36c9b11-8e20-4845-94cb-e21ece067bf3)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

24.05.0.1

### Informasi tambahan

di berputas juga sama

**Comment by MUHAMMADRANGSEL** [comment]
masalah ini masih terjadi, malah sekarang di Status Perkawinan untuk Tanggal kawin atau Tanggal Perceraian perlu di croscek kembali, Tempat dilahirkan berubah menjadi Lainnya walaupun pilihannya lain'

**Comment by MUHAMMADRANGSEL** [comment]
mungkin perlu dilakukan pengecekan lebih detail untuk yang ini, soalnya ini sangat menggangu sekali jalan sampai ini bermasalah ke KARTU KELUARGA WARGA solanya dari dukcapil mengikuti surat pengantar dari DESA

**Comment by andifahruddinakas** [comment]
> masalah ini masih terjadi, malah sekarang di Status Perkawinan untuk Tanggal kawin atau Tanggal Perceraian perlu di croscek kembali, Tempat dilahirkan berubah menjadi Lainnya walaupun pilihannya lain'

pak @MUHAMMADRANGSEL, untuk wajib KTP sudah disesuaikan dengan issue ini.

https://github.com/OpenSID/OpenSID/assets/57283157/27c37da7-8a87-4b1e-b6e2-6dd40d1ddf45


untuk kasus lain akan dicek dan diperbaiki jika tereplikasi di berputar.

**Comment by andifahruddinakas** [comment]
pak @MUHAMMADRANGSEL, sudah disesuaikan melalui commit https://github.com/OpenSID/premium/commit/be9e47ffddbf639ba684e0b5605853deaaee59d0 terkait permsalahan tempat dilahirkan.

**Comment by MUHAMMADRANGSEL** [comment]
KALAU BISA DICANTUMKAN SOLUSI SEMENTARA TERKAIT MASALAH INI TERUTAMA UNTUK PERUBHAN BIODATA PENDUDUK DI FORUM.OPENDESA
