### ISSUE TITLE
Bug/error: e 500 ketika edit shortcut

### ISSUE THREAD

**Issue by utay-cugung** [OpenSID/OpenSID#7924]
### Jelaskan error yg dialami
halaman beranda error.
muncul e500 ketika klik tombol edit shortcut

### Cara untuk mereplikasi errornya

pengaturan> shortcut> edit> 

### Hasil yg diharapkan

normal bisa edit

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/155012206/10b9bafd-8394-4843-abbc-491b172248e2)

![image](https://github.com/OpenSID/OpenSID/assets/155012206/6c9ed8d9-116d-4663-b386-e28b8f5a0c93)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2405.0.1 premium

### Tema Yang Digunakan

denava

### Informasi tambahan

alternatif tidak akses dengan https://www.cugung-rajabasa.desa.id/beranda
 tetapi misal https://www.cugung-rajabasa.desa.id/identitas_desa

**Comment by utay-cugung** [comment]
![image](https://github.com/OpenSID/OpenSID/assets/155012206/3877d996-a084-44df-a0e7-a6508bfef77e)

**Comment by MUHAMMADRANGSEL** [comment]
cek database bang, kami posisi aman, diberputar juga aman

**Comment by luxmant354** [comment]
di saya aman versi 2405.0.1

**Comment by andifahruddinakas** [comment]
pak @utay-cugung, jika masih terjadi coba masuk halaman pengaturan > info_sistem > optimasi, pilih bersihan

![image](https://github.com/OpenSID/OpenSID/assets/57283157/a0712aa8-3059-42b1-8ace-415bf723b826)
