### ISSUE TITLE
Bug/error: Login halaman beranda admin tampilan blank

### ISSUE THREAD

**Issue by redhousman** [OpenSID/OpenSID#7925]
### Jelaskan error yg dialami

Login kehalaman admin siteman di menu utama, setelah pada halaman beranda admin tampilan kosong (blank), sehingga tidak ada tampilan layar setelah masuk url: domain.desa.id/beranda

### Cara untuk mereplikasi errornya

pada masuk halam admin beranda, seharusnya menampilkan di menu utama keseluruhan info desa, kependudukan, layanan surat.dll

### Hasil yg diharapkan

![yes_opns](https://github.com/OpenSID/OpenSID/assets/141497405/77c764a3-45d6-4f46-a2c3-9da1eed7661b)

### Tangkapan layar dan log error

![log_error](https://github.com/OpenSID/OpenSID/assets/141497405/8911e6b3-f981-44a8-bce1-6b18717ded3c)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Versi 2405.0.1

### Tema Yang Digunakan

DeNava 11.1

**Comment by MUHAMMADRANGSEL** [comment]
cek database, diberputar aman

**Comment by pandigresik** [comment]
cek pengaturan - shortcut

**Comment by redhousman** [comment]
error pada Shortcut dan di kembalikan semula (default) hasilnya normal. tks
