### ISSUE TITLE
Bug/error: Pengaturan Font pada surat tidak bisa dirubah

### ISSUE THREAD

**Issue by RomziJazz** [OpenSID/OpenSID#7926]
### Jelaskan error yg dialami

Mengaturan Font system tidak bisa di rubah dari Arial ke font lain.

### Cara untuk mereplikasi errornya

langsung cetak pada menu layanan surat tidak menjadi font arial semua. tidak berubah sesuai pengaturan font.

### Hasil yg diharapkan

font sesuai di pengaturan

### Tangkapan layar dan log error

-
![image](https://github.com/OpenSID/OpenSID/assets/65128302/62eb2dcc-8528-491a-a8fc-b2e74e2af779)

![image](https://github.com/OpenSID/OpenSID/assets/65128302/59353885-86d9-4e0f-81e0-ffbdfbca972f)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2405.0.2

**Comment by andifahruddinakas** [comment]
mas @pandigresik, cek bagian ini jg.

- [ ] saat cetak atau priview surat dgn font ddiubah lewat editor akan jd blank.
![image](https://github.com/OpenSID/OpenSID/assets/57283157/5eb8d515-b13f-461e-b4d8-7876bb2d7a36)
hasil
![image](https://github.com/OpenSID/OpenSID/assets/57283157/02c5bde7-6183-4e1e-8041-3d33b35c0ab7)

**Comment by andifahruddinakas** [comment]
Catatan : 
- Default font hanya diterapkan pada bagian html yang fontnya tidak disesuaikan. Sehingga bisa menggunakan multifont dalam 1 jenis surat.
- Default font dapat dilihat saat melakukan cetak, sedangkan untuk editor tdk akan terpengaruh. (terkait multifont)
