### ISSUE TITLE
Bug: timezone perlu di-setting

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#793]
Diperlukan untuk hosting di mana date.timezone tidak ada setting default dan juga di mana setting timezone hosting tidak sesuai dengan timezone lokal. Kalau tidak ada setting default, akan terjadi error di mana function opensid_helper umur() akan menghasilkan _null_.

```
//  https://stackoverflow.com/questions/16765158/date-it-is-not-safe-to-rely-on-the-systems-timezone-settings
	date_default_timezone_set('Asia/Makassar');//ganti ke timezone lokal
```

Tambahkan ke _Pengaturan > Setting Aplikasi_.

**Comment by ombimo** [comment]
Asia/Jakarta
Asia/Jayapura
Asia/Makassar

timezonenya cuma ada 3 itu kan om ?

**Comment by eddieridwan** [comment]
Ya, sepertinya begitu. Ada tiga zona waktu di Indonesia.

**Comment by ombimo** [comment]
wah sepertinya harus buat base_controller supaya bisa set_timezone di semua halaman, biar tidak terlalu banyak copy-paste code ke semua controller, gmna om ?

**Comment by ombimo** [comment]
tp kalau tanpa ambil config ke database, bisa ditaruh di config. tetapi kalau mau mengubah timezone harus edit php nya langsung

**Comment by eddieridwan** [comment]
@ombimo : hanya tinggal ditambahkan ke Pengaturan > Setting Aplikasi.

1. tambah setting _timezone_ melalui migrasi di database_model.php
2. di setting_model.php, jalankan _date_default_timezone_set()_ untuk setting timezone PHP

_setting_model.php_ berfungsi sebagai konfigurasi aplikasi tambahan, yang settingnya disimpan di database.

Sudah dikerjakan dan dicommit ke master.

Kalau ada usul perbaikan, silakan.

**Comment by ombimo** [comment]
wah ternyata ada autoloadnya ya, hihihi
soalnya pas mau code, bingung _date_default_timezone_set_ mau ditaruh dmna biar di semua tempat jalan.
*baru pertama pegang CI
