### ISSUE TITLE
Bug/error: FORM PENDUDUK LUAR DESA LENGKAP

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#7931]
### Jelaskan error yg dialami

pada saat memilih form penduduk luar desa lengkap isian yang ditampilkan form semua jenis data yang tertera di kartu keluarga, ini membuat kesulitan dan proses lama dalam penmgimputan surat

### Cara untuk mereplikasi errornya

pada saat memilih form penduduk luar desa lengkap isian yang ditampilkan form semua jenis data yang tertera di kartu keluarga, ini membuat kesulitan dan proses lama dalam penmgimputan surat

### Hasil yg diharapkan

untuk form penduduk luar desa (lengkap) dibuat dinamis sehingga dibsa di centang sesuai dengan kebutuhan didesa seperti form saksi yang ditambahkan oleh operator
![Screenshot 2024-05-13 091934](https://github.com/OpenSID/OpenSID/assets/25834335/62a9d4e1-ae0b-43f5-8d09-cfcf5f93f3d4)
ini akan mempermudah bagi desa 

### Tangkapan layar dan log error

![Screenshot 2024-05-13 091506](https://github.com/OpenSID/OpenSID/assets/25834335/a77358ae-e848-4f75-ac65-bb456681523a)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

24.05.0.1

### Tema Yang Digunakan

Natra

### Informasi tambahan

berputar

**Comment by andifahruddinakas** [comment]
pak @MUHAMMADRANGSEL, bisa buat pengturan baru. agar jika ada update perubahan dari sistem tidak mengubah penguturan yang sudah dibuat sebelumnya. 

Untuk membedakan penduduk luar desa dan penduduk luar desa (lengkap) terdapat pada isiannya.

**Comment by MUHAMMADRANGSEL** [comment]
Contoh seperti apa bang

Pada tanggal Sen, 13 Mei 2024 10.36, Andi Fahruddin Akas <
***@***.***> menulis:

**Comment by MUHAMMADRANGSEL** [comment]
![Screenshot 2024-05-15 001213](https://github.com/OpenSID/OpenSID/assets/25834335/11ee1762-2ee4-41ec-930a-ae6d97eb0703)
seperti inikah bung....?

**Comment by andifahruddinakas** [comment]
> ![Screenshot 2024-05-15 001213](https://github.com/OpenSID/OpenSID/assets/25834335/11ee1762-2ee4-41ec-930a-ae6d97eb0703)
> seperti inikah bung....?

Ya silahkan buat pengaturannya sendiri sesuai kebutuhan, nanti tinggal disuratnya gunakan pengaturan tsb.
