### ISSUE TITLE
Gagal impor Daftar Program Bantuan Sasaran Keluarga dan Rumah Tangga

### ISSUE THREAD

**Issue by makhbub** [OpenSID/OpenSID#7934]
### Jelaskan error yg dialami

saat impor program bantuan dengan sasaran keluarga dan Rumah tangga, program bantuannya terinput tetapi penerimanya gagal terinput
untuk program bantuan sasaran individu tidak ada masalah

### Cara untuk mereplikasi errornya

1. pergi ke halaman bantuan,
2. klik tombol impor
3. download contoh format impor program bantuan
4. ubah dsasaran menjadi keluarga (2) atau Rumah Tangga (3)
5. upload data tersebut

### Hasil yg diharapkan

impor bantuan sasaran keluarga dan Rumah Tangga kembali normal

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2405.0.1

### Tema Yang Digunakan

-

### Informasi tambahan

-

**Comment by andifahruddinakas** [comment]
pak @makhbub, sy coba tidak ada masalah. bisa sertakan log error atau notifikasi setelah impor, kalau gagal biasanya ditampilkan terkait gagal krn apa.


https://github.com/OpenSID/OpenSID/assets/57283157/842b3938-2fe8-4772-8863-452823fa0ede

**Comment by andifahruddinakas** [comment]
Silahkan dibuka kembali jika masih mengalami hal yg sama.

**Comment by makhbub** [comment]
saya coba di berputar masih gagal,
saya coba upload vidio dan log nya disini, tapi gagal
nanti saya kirim lewat japri telegram

**Comment by andifahruddinakas** [comment]
pak @makhbub, dari file impor yg dikirimkan. Yang diubah hanya sasarannya saja. Sedangkan tiap sasaran beda cara pengecekannya.

contoh : 
- jika sasaran 1 (penduduk) maka nopesertanya adalah nik
- jika sasaran 2 (keluarga) maka nopesertanya adalah no_kk

jika program bantuan di set sasaran 2 dari format impor yg seharusnya sasaran 1, maka data tidak akan ditemukan. seharunya jika sasaran diubah, maka pada bagian peserta diganti jg sesuai masing2 sasaran.

**Comment by makhbub** [comment]
oke, solved
ternyata untuk sasaran penerima keluarga
- kolom penerima diisi no KK penerima
- kolom NIK diisi nomor NIK nama penerima

terima kasih pak,
