### ISSUE TITLE
Mapbox API Key

### ISSUE THREAD

**Issue by mediputra** [OpenSID/OpenSID#7935]
### Apa kekurangan yg ingin diatasi?

Pada versi sebelumnya masih terdapat form mapbox api key di pengaturan aplikasi, saat ini versi 24.05 pengaturan tersebut hilang sehingga tampilan maps di widget lokasi kantor dan wilayah desa tidak dapat ditampilkan ke tampilan satelit

### Jelaskan solusi yg diinginkan

Seharusnya form ini masih tetap ada sehingga pengguna dapat melihat lokasi dengan jelas pada mode satelit mapbox

### Apakah ada alternatif lain

Tidak ada. 

### Untuk versi OpenSID mana

24.05

### Informasi tambahan

Pengaturan ini biasanya berasa di pengaturan aplikasi berada satu halaman dengan pengaturan theme

**Comment by andifahruddinakas** [comment]
Pak @mediputra , pengaturan tsb sdh lama dipindahkan di modul pemetaan > peta.

Mas @rid, bisa buatkan panduannya.
