### ISSUE TITLE
Bug/error: pristiwa, saksi dan pelapor kematian pada Surat Keterangan Kematian tidak muncul

### ISSUE THREAD

**Issue by isnantomch** [OpenSID/OpenSID#7936]
### Jelaskan error yg dialami

Di berputar.opendesa.id form isian pelapor dan saksi2nya gak muncul.
![Screenshot_20240514_144857_Chrome](https://github.com/OpenSID/OpenSID/assets/59205349/b0d4523d-e65d-4b89-91aa-2dc63667be74)

### Cara untuk mereplikasi errornya

Pada saat pembuatan / cetak surat keterangan kematian.
![Screenshot_20240514_144941_Chrome](https://github.com/OpenSID/OpenSID/assets/59205349/9059871d-e537-419f-a51c-8e8a4e63008f)

### Hasil yg diharapkan

Bisa normal kembali.

### Tangkapan layar dan log error

![Uploading Screenshot_20240514_182340_Chrome.jpg…]()

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v2405.0.1-premium

### Tema Yang Digunakan

Batuah v24.0424.03

### Informasi tambahan

Klau di https://tegalrejo-musirawas.desa.id/ hari, tanggal, jam tempat dan penyebab kemtaian yang tidak muncul di konsep surat

**Comment by isnantomch** [comment]
[surat-keterangan-kematian_5201140305936994_2024-05-14_2 (1).pdf](https://github.com/OpenSID/OpenSID/files/15307626/surat-keterangan-kematian_5201140305936994_2024-05-14_2.1.pdf)

**Comment by isnantomch** [comment]
![Screenshot_20240514_182340_Chrome](https://github.com/OpenSID/OpenSID/assets/59205349/edf18899-b0ba-4208-a7df-941e9d52001a)
Logs error

**Comment by andifahruddinakas** [comment]
Pak @isnantomch, untuk error yg ditampilkan di SS, bisa perbarui template suratnya dengan bawaan sistem.


Untuk error yg di tampilkan di log, datbasenya tdk lengkap.
