### ISSUE TITLE
Bug/error: lampiran F2.01 ada yang tidak terisi

### ISSUE THREAD

**Issue by Akmal197** [OpenSID/OpenSID#7937]
### Jelaskan error yg dialami

lampiran F2.01 surat keterangan lahir pada data anak ada yang tidak terisi otomatis dan pilihan jenis kelamin dua-duanya laki-laki
![image](https://github.com/OpenSID/OpenSID/assets/76812689/b1b1ad21-80ea-4e32-9761-ec7e622f253d)

### Cara untuk mereplikasi errornya

cetak surat keterangan lahir

### Hasil yg diharapkan

normal

### Tangkapan layar dan log error

diatas

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

terbaru

**Comment by andifahruddinakas** [comment]
pak @Akmal197, sy cek sudah sesuai.
![image](https://github.com/OpenSID/OpenSID/assets/57283157/79169dac-eddc-4de2-9c1c-9553d51a315e)

pada website https://berputar.opendesa.id/surat/pratinjau/surat-keterangan-kelahiran juga aman
![image](https://github.com/OpenSID/OpenSID/assets/57283157/74e6d60e-0a89-4fb3-855a-110ee994c0f6)
