### ISSUE TITLE
Bug/error: Gagal Hapus Beberapa Artikel (404)

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#7938]
### Jelaskan error yg dialami

https://github.com/OpenSID/OpenSID/assets/46939846/bcea21a7-16c8-486d-8492-0aff9c6e38a2

### Cara untuk mereplikasi errornya

Centang beberapa artikel lalu klik hapus

### Hasil yg diharapkan

Normal kembali

### Tangkapan layar dan log error

di video atas

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Berputar

**Comment by andifahruddinakas** [comment]
sudah diperbaiki melalui commit https://github.com/OpenSID/premium/commit/b23e765bee3c3afda9f91a9402d844a059cd217f
