### ISSUE TITLE
Permintaan fitur: Penulisan a.n kepala desa yang menandatangani surat belum bisa disesuaikan seperti tata naskah dinas yang berlaku

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#7940]
### Apa kekurangan yg ingin diatasi?

saat ini penandatangan menggunakan an. kepala desa dan ub penulisannya belum sesuai dengan tata naskah dinas.

### Jelaskan solusi yg diinginkan

Pada saat membuat surat dan yang menandatangani surat menggunakan a.n. dan u.b
saat ini model penulisan pejabat yang menandatangi surat menggunakan a.n
![Screenshot 2024-05-16 182213](https://github.com/OpenSID/OpenSID/assets/25834335/b124f97a-1c59-49a6-abf0-479c242d8f03)
sedangkan di Tata Naskah yang berlaku seperti gambar dibawah ini :
![Screenshot 2024-05-16 182401](https://github.com/OpenSID/OpenSID/assets/25834335/27acef5d-76f4-4ad9-9006-e8661ba7b1e9)

### Apakah ada alternatif lain

saat ini sebelum dicetak diedit dulu

### Untuk versi OpenSID mana

24.05.0.2 Premium

### Informasi tambahan

bersama ini kami lampirkan tata naskah dinas kami yang berlaku di lombok timur
[PERBUP Lombok Timur No 32 Tahun 2019 Tentang Tata Naskah Dinas.pdf](https://github.com/OpenSID/OpenSID/files/15333472/PERBUP.Lombok.Timur.No.32.Tahun.2019.Tentang.Tata.Naskah.Dinas.pdf)

**Comment by MUHAMMADRANGSEL** [comment]
mungkin perlu dicarikan alternatif lain atau solusi lain spy pengguna bisa menyesuaikan dengan tata naskah dinas mengingat bisa jadi masing2 kabupaten atau provinsi beda beda model tata naskah dinasnya terkat penandatangan

**Comment by andifahruddinakas** [comment]
mas @yogiperdana, alternatif yg bisa digunakan : 

- [ ] tambahkan kode isian Atas Nama (Simbol) => [a.n_simbol]
- [ ] tambahkan kode isiaan Atas Nama (Jabatan) => [a.n_jabatan]

sehingga nantinya bisa disesuaikan sendiri oleh pengguna jika ada perubahan tampilan.

![image](https://github.com/OpenSID/OpenSID/assets/57283157/b67be187-8fd7-4770-b981-5b500255e366)

contoh penerapan yg nantinya bisa dilakukan oleh pengguna.
![image](https://github.com/OpenSID/OpenSID/assets/57283157/09121eb1-3983-4b3a-89cf-bfbf10e4fc5d)

**Comment by yogiperdana** [comment]
Jadi a.n simbol dan a.n jabatan isinya apa mas @andifahruddinakas

**Comment by andifahruddinakas** [comment]
> Jadi a.n simbol dan a.n jabatan isinya apa mas @andifahruddinakas

**[a.n_simbol]** >replace> **a.n, A.n, A.N, a.n**
**[a.n_jabatan]** >repalce> **kepala desa, Kepala desa, Kepala Desa, KEPALA DESA** (sesuai penamaan di jabatan yg mewakili)

inti dari kode ini biar yang selama ini digabung misalnya `a.n Kepala Desa Siwa <br> Sekretaris Desa` dengan kode isian `[Atas_namA]` bisa di pecah menjadi `[a.n_simbol] [Sebutan_kepala_desA][NaMa_desa] <br>[a.n_jabatan]`
