### ISSUE TITLE
Bug/error: pencarian menggunakan TAG ID CARD tidak bisa

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#7942]
### Jelaskan error yg dialami

Pencarian Data Penduduk menggunakan TAG ID CARD tidak bisa

### Cara untuk mereplikasi errornya

Pencarian Data Penduduk menggunakan TAG ID CARD tidak bisa

### Hasil yg diharapkan

Normal seperti versi sebelumnya

### Tangkapan layar dan log error

Pencarian Data Penduduk menggunakan TAG ID CARD tidak bisa

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

24.05.0.2 Premium

**Comment by andifahruddinakas** [comment]
pak @MUHAMMADRANGSEL, sudah disesuaikan melalui commit https://github.com/OpenSID/premium/commit/01f9e64ea5b424008dc1c31c3554b7320be5fc43

**Comment by MUHAMMADRANGSEL** [comment]
OK SIAP BUNG
