### ISSUE TITLE
Bug/error: export data penduduk jumlah penduduk pada menu penduduk tidak sama dengan jumlah penduduk hasil export di file excel

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#7943]
### Jelaskan error yg dialami

Bug/error: export data penduduk jumlah penduduk pada menu penduduk tidak sama dengan jumlah penduduk hasil export di file excel

jumlah di openSID 101 penduduk 
jumlah penduduk di file excel 98

### Cara untuk mereplikasi errornya

1. menu penduduk
2. export penduduk

### Hasil yg diharapkan

jumlah penduduk hasil export di file excel dsama dengan jumlah penduduk di openSID

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/55429781/fdc1956f-5504-49c7-8bfb-89f3bdbb22f8)
![image](https://github.com/OpenSID/OpenSID/assets/55429781/a245bd9f-6e67-4264-909b-20cc354ddd8c)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2405.0.2-premium

**Comment by andifahruddinakas** [comment]
dari pengecekan di berupar. data yg tidak terekspor dan menyebabkan selisih adalah penduduk yg tidak memiliki no kk.

<img width="960" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/f20adee2-d465-4bcc-91da-3ce53565b2ab">
