### ISSUE TITLE
Bug/error: bagian form selain form utama untuk rincian sumber data hilang

### ISSUE THREAD

**Issue by khiar-rara** [OpenSID/OpenSID#7945]
### Jelaskan error yg dialami

Berakibat pada hilangnya isian data saat cetak surat (terjadi di surat dengan beberapa bagian form). Mohon cek juga hasil cetak surat yang ada lampirannya jika dilakukan perbaikan

### Cara untuk mereplikasi errornya

1. Cetak surat
2. Pilih surat kelahiran (kematian/yang terdiri beberapa bagian form

### Hasil yg diharapkan

Tidak terjadi lagi hal demikian saat update versi berikutnya

### Tangkapan layar dan log error

![Screenshot_20240517_152050](https://github.com/OpenSID/OpenSID/assets/74307159/41f2080f-d59e-4778-9f19-c57aeb1203b6)
![Screenshot_20240517_152146](https://github.com/OpenSID/OpenSID/assets/74307159/72047f1d-fc9f-43cf-86a6-5a857c5678a2)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v2405.0.2-premium

### Tema Yang Digunakan

Esensi

### Informasi tambahan

-

**Comment by andifahruddinakas** [comment]
Duplicate issue https://github.com/OpenSID/OpenSID/issues/7936
