### ISSUE TITLE
Permintaan fitur: Penulisan angka,hurup dan tanda baca pada penulisan wilayah dusun dan rt

### ISSUE THREAD

**Issue by utay-cugung** [OpenSID/OpenSID#7946]
### Apa kekurangan yg ingin diatasi?

Ternyata ada beberapa desa yg sudah berlaku penulisan berupa angka,hurup dan tanda baca pada alamat dusun dan rt

### Jelaskan solusi yg diinginkan

Agar bisa tulis hurup,angka dan tanda baca pada kewilayahan dusun dan rt

![IMG-20240517-WA0032](https://github.com/OpenSID/OpenSID/assets/155012206/bc6440db-a0e8-495e-a893-9aa121a8b3bd)
![IMG-20240517-WA0031](https://github.com/OpenSID/OpenSID/assets/155012206/d3096e30-4d39-43f4-a738-3fe32678bbe6)

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

Versi 2405.0.3 premium

### Informasi tambahan

Mohon segera di tindak lanjut karena kesulitan penginputan database penduduk

**Comment by nyomanjyotisa** [comment]
Issue ini sudah saya kerjakan pada PR berikut https://github.com/OpenSID/OpenSID/pull/7956

**Comment by andifahruddinakas** [comment]
Duplicate of https://github.com/OpenSID/OpenSID/issues/7916
