### ISSUE TITLE
Bug/error: Donasi Pengembangan OpenSID not found

### ISSUE THREAD

**Issue by nyomanjyotisa** [OpenSID/OpenSID#7950]
### Jelaskan error yg dialami

Donasi Pengembangan OpenSID not found

### Cara untuk mereplikasi errornya

- Klik icon informasi di pojok kanan atas
- Klik Donasi
- Klik Donasi Pengembangan OpenSID

### Hasil yg diharapkan

Menampilkan informasi lebih lanjut tentang Donasi

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/73281575/a3ecf822-acc9-4688-8a4c-a47dbd63898c)

![image](https://github.com/OpenSID/OpenSID/assets/73281575/1024448f-aaac-43ad-94ec-0a15ee6af763)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

semua

Regards,
I Nyoman Jyotisa

**Comment by andifahruddinakas** [comment]
pak @eddieridwan, halaman https://opendesa.id/donasi sudah tidak ada. apakah sudah tidak diperlukan?

**Comment by eddieridwan** [comment]
@andifahruddinakas masih diperlukan. Nanti Sekretariat akan diminta untuk membuat ulang.

**Comment by andifahruddinakas** [comment]
Ok.

issue ini akan ditutup, karena yang bermasalah ada pada halaman https://opendesa.id/donasi yang belum tersedia/hilang.

adapun jika ada perubahan pada url tsb yang membutuh penyesuaian pada aplikasi, akan dibuatkan issue untuk menyesuaikan.
