### ISSUE TITLE
Bug/error: CheckBox label "Tampilkan kata sandi" issue

### ISSUE THREAD

**Issue by nyomanjyotisa** [OpenSID/OpenSID#7953]
### Jelaskan error yg dialami

ketika klik "Tampilkan kata sandi" checkbox tidak checked

### Cara untuk mereplikasi errornya

1. Buka halaman login admin

### Hasil yg diharapkan

Ketika text "Tampilkan kata sandi" idealnya checkbox juga di-check karena text tersebut merupakan labelnya

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/73281575/89e6b313-f6b0-4167-83fc-ce491368bcfe)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

semua

Regards,
I Nyoman Jyotisa

**Comment by nyomanjyotisa** [comment]
Issue ini sudah saya kerjakan pada PR berikut https://github.com/OpenSID/OpenSID/pull/7955

**Comment by andifahruddinakas** [comment]
sudah

**Comment by andifahruddinakas** [comment]
mas @nyomanjyotisa, bisa hubungi mas @vickyrolanda untuk penjelasan terkait kontibusi di OpenDesa.
