### ISSUE TITLE
Bug/error: Pengaturan TTE selalu aktif

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#7957]
### Jelaskan error yg dialami

https://github.com/OpenSID/OpenSID/assets/46939846/0a30ba28-bc61-4b99-9146-2df097c53dd9

### Cara untuk mereplikasi errornya

seperti vide di atas, masuk pengaturan surat, dan non aktifkan TTE, maka yang terjadi setelah di cek kembali selalu aktif.

### Hasil yg diharapkan

buat agar mengikuti pengaturan yang ditentukan,

agar pengguna dapat replikasi cetak surat jika alami error di web desanya dan tidak pakai TTE.

### Tangkapan layar dan log error

di atas

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Berputar

**Comment by andifahruddinakas** [comment]
sudah di sesuaikan di commit https://github.com/OpenSID/premium/commit/61bb3d7ea4c5efe918768ffb093235f6b0df2f34
