### ISSUE TITLE
Bug/error: Simpan Konsep tidak Menuju ke halaman Konsep

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#7958]
### Jelaskan error yg dialami

https://github.com/OpenSID/OpenSID/assets/46939846/e0104c2b-dd25-42bc-8b7c-8602e2059e1a

### Cara untuk mereplikasi errornya

seperti vide, ketika klik konsep, maka saat ini redirect ke halaman Cetak Surat kembali.

Diharapkan redirect ke halaman konsep surat. agar dapat di cek kembali atau di edit kembali.

### Hasil yg diharapkan

selain itu, bisa dipertimbangkan untuk pindah tombol konsep ke sebelah kiri.

agar sisi paling kanan adalah cetak surat. bersebelahan dengan pratinjau.

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Berputar

**Comment by nyomanjyotisa** [comment]
Issue ini sudah saya kerjakan pada PR berikut https://github.com/OpenSID/OpenSID/pull/7960
