### ISSUE TITLE
Bug/error: Penandatangan Surat tidak muncul

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#7959]
### Jelaskan error yg dialami

![image](https://github.com/OpenSID/OpenSID/assets/46939846/069f1d48-3c79-44d1-8003-df00849ae88b)

### Cara untuk mereplikasi errornya

seperti gambar di atas, penandatangan tidak muncul ketika akan cetak surat, hanya ada tombol langsung simpan.

hal ini terjadi karena Pengaturan TTE Aktif.

namun pengguna sempat merasa bingung mengapa tidak bisa menentukan si Penandatangan misal Kades, Sekdes, atau lainnya.
walau sudah di set a.n. dan u.b. pada menu Pemerintah Desa.

### Hasil yg diharapkan

beri keterangan atau sejenis, agar ketika akan cetak surat, pengguna tidak alami kendala pilih penandatangan akibat TTE Aktif.

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Berputar

**Comment by andifahruddinakas** [comment]
pak @ariandii,

- [ ]  untuk TTE aktif bagian pilih penanda tangan tidak ditampilkan, bisa cek dipenganturan untuk melihat pengaturannya.

![image](https://github.com/OpenSID/OpenSID/assets/57283157/af22059c-5193-4242-bf01-bbeb59288cb1)

- [ ] untuk kondisi pengecekan penanda tangan akan gagal (akan ridirect ke halaman pengurus) jika belum ada kepala desa yg aktif.

mungkin masalahnya terkait issue https://github.com/OpenSID/OpenSID/issues/7957 dimana pengaturan tte selalu aktif.

**Comment by ariandii** [comment]
![Screenshot_20240520_071030_Chrome](https://github.com/OpenSID/OpenSID/assets/46939846/8483d347-fdd2-45b3-9e8e-552049643c6a)

sesuai dengan kalimat yang sudah dismpaikan di atas.

**Comment by andifahruddinakas** [comment]
> ![Screenshot_20240520_071030_Chrome](https://private-user-images.githubusercontent.com/46939846/331910601-8483d347-fdd2-45b3-9e8e-552049643c6a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxNjQ4NzksIm5iZiI6MTcxNjE2NDU3OSwicGF0aCI6Ii80NjkzOTg0Ni8zMzE5MTA2MDEtODQ4M2QzNDctZmRkMi00NWIzLTllOGUtNTUyMDQ5NjQzYzZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDAwMjI1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyN2IyYWVkM2QwYmUzZDUwNTViZTA2N2E3YjUwMmFjY2MyNTdjYjgwOWIwODg4Y2E2MTkxMWIxMDg4YTVhNmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Zwu-xIC6_vrTk3MmK1Ifn4RTL9ohIeR6MdRtI_Sxb-c)
> 
> sesuai dengan kalimat yang sudah dismpaikan di atas.

Untuk penanda tangan dengan pengaturan TTE aktif akan otomatis yg bertandatangan adalah kepala desa dengan menggunakan TTE. Adapun pengaturan lebih lanjut untuk TTE, terkait verifikasi sekdes dan kades.

Jika ingin menampilkan dan memilih penanda tangan misalnya kepala desa, a.n kepala desa (sekretaris), u.b hanya bisa dilakukan dengan pengaturan TTE tidak aktif.

**Comment by ariandii** [comment]
https://github.com/user-attachments/assets/1bd26b07-416c-48fd-a632-5b41aa244f20

bisa diperhatikan video atas sampai selesai.
menggunakan OpenSID premium Rilis terakhir.
