### ISSUE TITLE
Nomor surat dapat diinput berulang.

### ISSUE THREAD

**Issue by fathurvbf** [OpenSID/OpenSID#796]
Om @eddieridwan untuk penomoran surat saya temukan dapat diinput berulang kali, jika dapat penomoran surat, jika diinput nomor yang sama tidak bisa.
![nomor surat dobel](https://user-images.githubusercontent.com/26631297/36263919-e4e121d8-129d-11e8-9d7f-18b2e1245dea.png)

**Comment by MUHAMMADRANGSEL** [comment]
memang sekarang ini masih bisa dicetak dengan nomor yang sama selama surat yang dibuat berbeda, kalau satu jenis surat maka yang akan muncul hanya satu

**Comment by MUHAMMADRANGSEL** [comment]
paling tidak spy masalah tersebut bisa diatasi, perlu menjadi titik tekan di nomor register surat dan tahun pembuatan surat : 
1. Kalau nomor dan tahun pembuatan sama dan dengan jenis surat berbeda surat tidak bisa diexport dengan ada muncul peringatan 
2. kalau nomor sama sedang tahun pembuatan surat berbeda maka surat bisa diexport

mengapa demikian karena per 1 januari register surat dimulai dari 001

**Comment by balongbesuk** [comment]
saya juga sering mengalami hal ini, sebelum mencetak surat teman teman perangkat desa antri buku register surat, untuk penomoran surat, agar file yang tercetak tidak ganda, (akibatnya pelayanan sedikit terhambat karena masalah ini)

akan lebih baik dibuat otomatis dengan aplikasi akan mendeteksi kode surat dan nomor log surat terakhir pada jenis surat yang dibuat, selanjutnya memberikan nomor pada surat yang sedang diproses cetak oleh aplikasi, sehingga walaupun pengguna aplikasi mencetak surat secara bersamaan nomor surat tidak akan ganda (berkelanjutan) 

( dengan catatan nomor surat pertama bs diimput manual surat baru / pengguna baru dan setiap pergantian tahun nomor surat kembali ke 1 / input manual tadi )

![untitled](https://user-images.githubusercontent.com/35319600/36293360-6f128fb4-130b-11e8-8e37-cb40f3b46055.jpg)

**Comment by pandigresik** [comment]
Cara paling gampang dan mudah adalah menambahkan constraint unique untuk kombinasi field (id_format_surat,tahun,no_surat)

**Comment by eddieridwan** [comment]
Issue ini duplikat dari #997. Silakan teruskan pembahasan di #997.

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui #997.
