### ISSUE TITLE
Permintaan fitur: pengaturan surat Data Pelaku

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#7967]
### Apa kekurangan yg ingin diatasi?

saat ini banyak teman-teman desa yang binggung ketika ada surat yang pemohonnya perlu dimunculkan berulang
dimana saat ini untuk settingaan data berulang ada dimasing-masing surat, alangkah baiknya dijadikan global ditaruh di menu layanan surat/ pengaturan surat/lainnya
![Screenshot 2024-05-20 150603](https://github.com/OpenSID/OpenSID/assets/25834335/dacf1453-71e8-448c-a10e-4f00270aa6c6)

### Jelaskan solusi yg diinginkan

![Screenshot 2024-05-20 151109](https://github.com/OpenSID/OpenSID/assets/25834335/0a88d5e0-6d8c-4261-85bd-4de5fd66652c)

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

24.05.0.2

**Comment by andifahruddinakas** [comment]
pak @MUHAMMADRANGSEL, pengaturan tsb dimaksudkan karena tidak semua surat mempunyai perlakuan yg sama. Jika mau dibuat seperti saran di atas, sebaiknya sperti ini.

Sediakan pengaturan pada pengaturan surat > lainnya, yakni pilihan data pelaku berulang (global) sama seperti margin global.
