### ISSUE TITLE
Bug/error: Bolehkan berisi karakter alfanumerik, spasi dan strip pada jabatan aparatur desa

### ISSUE THREAD

**Issue by mah-mudi** [OpenSID/OpenSID#7968]
### Jelaskan error yg dialami

tidak bisa menambahkan karakter titik pada jabatan Pj. Kepala Desa

### Cara untuk mereplikasi errornya

Buku Aparatur Pemerintah Desa
Jabatan

### Hasil yg diharapkan

Boleh berisi karakter alfanumerik, spasi dan strip pada jabatan aparatur desa

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/57661283/7622a1a2-3ee4-4941-9de8-b992e8b2c0a7)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

24.05.02

### Tema Yang Digunakan

silir

### Informasi tambahan

https://berputar.opendesa.id/

**Comment by andifahruddinakas** [comment]
pak @mah-mudi, penerapan Pj. akan diterapkan melalui issue https://github.com/OpenSID/OpenSID/issues/7970, bisa tinggalkan komentar pada issue tsb.

**Comment by mah-mudi** [comment]
oke
