### ISSUE TITLE
Bug/error: Kolom dempet di Laporan PDF di Buku Rekapitulasi jumlah Penduduk 

### ISSUE THREAD

**Issue by ilhamwahyu-ni** [OpenSID/OpenSID#7969]
### Jelaskan error yg dialami

Kolom dempet ketika lihat hasil rekap jumlah warga yang mencapai ribuan warga

### Cara untuk mereplikasi errornya

Buku Administrasi > Administrasi Penduduk > Buku Rekapitulasi Jumlah Penduduk>Laporan Pdf

### Hasil yg diharapkan

kolom tidak depet seperti menggunkan tombol cetak

### Tangkapan layar dan log error

![untitled](https://github.com/OpenSID/OpenSID/assets/85351181/0f4f2f67-c7b4-47ff-8142-248f76480d3e)

![1untitled](https://github.com/OpenSID/OpenSID/assets/85351181/46f58aa9-c160-46af-8ac8-6cab4be0dfae)
![2untitled](https://github.com/OpenSID/OpenSID/assets/85351181/2e9d4eb2-1ad0-4604-8331-5fac3a0857f2)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

24.05.02

### Tema Yang Digunakan

pusako

**Comment by andifahruddinakas** [comment]
Solusi yg bisa diterapkan: 
- [ ] pada bagian judul yg panjang, bisa di wrap agar tidak terlalu panjang.

**Comment by andifahruddinakas** [comment]
Catatan : 
- Untuk perbaikan ini dicoba maksimal 4 digit, jika lebih tetap akan berantakan krn ukuran yg tidak mencukupi.
