### ISSUE TITLE
Bug/error:  Duplikasi Nomor Urut pada Buku Agenda - surat masuk

### ISSUE THREAD

**Issue by ilhamwahyu-ni** [OpenSID/OpenSID#7971]
### Jelaskan error yg dialami

Duplikasi Nomor Urut pada Buku Agenda - surat masuk

### Cara untuk mereplikasi errornya

https://github.com/OpenSID/OpenSID/assets/85351181/30edc830-d614-49a6-872b-da667e636580

### Hasil yg diharapkan

Supaya ada notif yang sama seperti pembuatan layanan surat, " pada cetak surat "

![Screenshot 2024-05-21 115026](https://github.com/OpenSID/OpenSID/assets/85351181/51f149b6-e171-4028-ad4e-3545bd8e4aee)

### Tangkapan layar dan log error

![Screenshot 2024-05-21 121253](https://github.com/OpenSID/OpenSID/assets/85351181/64fa7fa0-8613-46a5-ac4c-d8c7044820f1)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

24.05.03

### Tema Yang Digunakan

pusako

### Informasi tambahan

di local dan di berputar sudah dicoba juga.

**Comment by mah-mudi** [comment]
harusnya di buku agenda surat masuk, tidak perlu no urut
