### ISSUE TITLE
Bug/error:  HTTP ERROR 500 saat cetak dan unduh Buku Peraturan desa

### ISSUE THREAD

**Issue by ilhamwahyu-ni** [OpenSID/OpenSID#7974]
### Jelaskan error yg dialami

HTTP ERROR 500 saat cetak dan unduh Buku Peraturan desa

### Cara untuk mereplikasi errornya

https://github.com/OpenSID/OpenSID/assets/85351181/96d114a5-e559-4790-be5d-00be844cf7a1

### Hasil yg diharapkan

normal kembali bisa cetak dan unduh

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/85351181/f169783d-de1f-44a1-b508-3114e2509004)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

24.05.02 dan 24.05.03

### Tema Yang Digunakan

pusako

### Informasi tambahan

sudah dicoba juga di web desa dan Berputar

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui commit https://github.com/OpenSID/premium/commit/7b5420672f45564323607b4b28e6ee033a7c6bf0
