### ISSUE TITLE
Bug/error: Halaman tambah dokumen layanan mandiri tidak bisa di scroll di desktop maupun mobile

### ISSUE THREAD

**Issue by nyomanjyotisa** [OpenSID/OpenSID#7981]
### Jelaskan error yg dialami

Halaman tambah dokumen layanan mandiri tidak bisa di scroll di desktop maupun mobile

### Cara untuk mereplikasi errornya

Buka https://berputar.opendesa.id/layanan-mandiri/dokumen/form

### Hasil yg diharapkan

Bisa di scroll

### Tangkapan layar dan log error

https://github.com/OpenSID/OpenSID/assets/73281575/0e51c7c7-22dc-408e-acf9-f5705956e5b3

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

semua

### Informasi tambahan

Regards,
I Nyoman Jyotisa

**Comment by andifahruddinakas** [comment]
cek issue https://github.com/OpenSID/OpenSID/issues/7826

dan komentar https://github.com/OpenSID/OpenSID/issues/7986#issuecomment-2132613938
