### ISSUE TITLE
Bug/error: PENDIDIKAN DALAM KK yang muncul PENDIDIKAN SEDANG DI TEMPUH

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#7984]
### Jelaskan error yg dialami

di Menu Penduduk PENDIDIKAN DALAM KK yang muncul PENDIDIKAN SEDANG DI TEMPUH

### Cara untuk mereplikasi errornya

di Menu Penduduk PENDIDIKAN DALAM KK yang muncul PENDIDIKAN SEDANG DI TEMPUH
![Screenshot 2024-05-24 154721](https://github.com/OpenSID/OpenSID/assets/25834335/7b5e1d67-cebf-47f4-af05-ae9091e9d9cd)

### Hasil yg diharapkan

PENDIIDIKAN YANG MUNCUL ADALAH PENDIDIKAN DALAM KK

### Tangkapan layar dan log error

![Screenshot 2024-05-24 154721](https://github.com/OpenSID/OpenSID/assets/25834335/ebe73256-0af1-4913-ae52-aa12a8cd10c6)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

OpenSID 2405.0.3-premium

**Comment by habibie11** [comment]
ini maksudnya bagaimana? pak @MUHAMMADRANGSEL
cc mas @andifahruddinakas

**Comment by andifahruddinakas** [comment]
> ini maksudnya bagaimana? pak @MUHAMMADRANGSEL cc mas @andifahruddinakas

pada kolom pendidikan gunakan data dari **Pendidik dalam KK**

**Comment by habibie11** [comment]
> > ini maksudnya bagaimana? pak @MUHAMMADRANGSEL cc mas @andifahruddinakas
> 
> pada kolom pendidikan gunakan data dari **Pendidik dalam KK**

di kolom pendidikan dalam kk sudah pakai data pendidikan dalam kk, saya cek tidak menemukan data pendidikan yang sedang ditempuh
![image](https://github.com/OpenSID/OpenSID/assets/56639378/21f01317-fc7d-42be-8597-1b21bafd7b1e)
![image](https://github.com/OpenSID/OpenSID/assets/56639378/f13b1e83-bec9-4eed-b4de-561667539e54)

**Comment by andifahruddinakas** [comment]
pak @MUHAMMADRANGSEL, @habibie11, setelah di cek secara struktur kode sudah sesuai,
untuk pendidikan yang ditampilkan pada daftar penduduk menggunakan pendidikan dalam kk
