### ISSUE TITLE
Bug/error: Terdapat sortable icon pada kolom 'NO' di halaman permohonan surat layanan mandiri

### ISSUE THREAD

**Issue by nyomanjyotisa** [OpenSID/OpenSID#7986]
### Jelaskan error yg dialami

Terdapat sortable icon pada kolom 'NO' di halaman permohonan surat layanan mandiri, yang dimana seharusnya kolom tersebut tidak sortable/orderable. Dan juga ketika di klik kolom tersebut tidak berfungsi

### Cara untuk mereplikasi errornya

buka https://berputar.opendesa.id/layanan-mandiri/kehadiran

### Hasil yg diharapkan

tidak ada sortable icon

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/73281575/9558e171-c5e7-41bf-8af3-20cc9c730f97)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

-

### Informasi tambahan

Regards,
I Nyoman Jyotisa

**Comment by nyomanjyotisa** [comment]
Issui ini sudah saya kerjakan pada PR berikut https://github.com/OpenSID/OpenSID/pull/7988

Regards,
I Nyoman Jyotisa

**Comment by andifahruddinakas** [comment]
mas @nyomanjyotisa, untuk issue seperti ini yg tidak fatal untuk saat ini belum diperlukan. Karena bulan depan terdapat target pengerjaan konversi halaman layanan mandiri web. sehingga perbaikan yg dilakukan akan hilang.
