### ISSUE TITLE
Bug/error: sort by jabatan pada halaman perangkat layanan mandiri tidak berfungsi

### ISSUE THREAD

**Issue by nyomanjyotisa** [OpenSID/OpenSID#7987]
### Jelaskan error yg dialami

sort by jabatan pada halaman perangakat layanan mandiri tidak berfungsi

### Cara untuk mereplikasi errornya

buka https://berputar.opendesa.id/layanan-mandiri/kehadiran

### Hasil yg diharapkan

data diurutkan sesuai pilihan sort jabatan

### Tangkapan layar dan log error

https://github.com/OpenSID/OpenSID/assets/73281575/4f937e22-488a-4203-89bb-ab6e6aa49a37

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

-

**Comment by nyomanjyotisa** [comment]
Issue ini sudah saya kerjakan pada PR berikut https://github.com/OpenSID/OpenSID/pull/7989

Regards,
I Nyoman Jyotisa

**Comment by andifahruddinakas** [comment]
cek issue https://github.com/OpenSID/OpenSID/issues/7826

dan komentar https://github.com/OpenSID/OpenSID/issues/7986#issuecomment-2132613938
