### ISSUE TITLE
Perlu ditambkan Menu Cetak PERDES & SK Pertahun

### ISSUE THREAD

**Issue by fathurvbf** [OpenSID/OpenSID#799]
Bung @eddieridwan Pada Menu Skertariat, pengeloaan PERDES dan SK, Perlu ditambahkan menu cetak laporan. Nanti Menu Cetak Laporan Berdasarkan Pertahun, Tujuan adalah agar dapat diketahui jumlah SK dan Perdes yang Keluar pertahun, hal ini kadang diminta sebagai laporan. 
![perdes](https://user-images.githubusercontent.com/26631297/36265585-1f6372b2-12a2-11e8-9bbb-e50bb7afa9ca.png)
![sk](https://user-images.githubusercontent.com/26631297/36265588-2117696a-12a2-11e8-9ceb-857a3b983b42.png)
Berkut Saya Lampirkan Format Buku Laporan.
[Laporan Perdes.xlsx](https://github.com/OpenSID/OpenSID/files/1728330/Laporan.Perdes.xlsx)
[Laporan SK.xlsx](https://github.com/OpenSID/OpenSID/files/1728331/Laporan.SK.xlsx)

**Comment by MUHAMMADRANGSEL** [comment]
betul sekali dan juga supaya pak kades bisa mengecek perdes dan sk yang sdh di buat

**Comment by hudabikhoir** [comment]
![screenshot from 2018-02-20 11-28-35](https://user-images.githubusercontent.com/35209506/36407445-48652d94-1631-11e8-8034-16c42bc959ca.png)

bisakah saya minta database terbaru untuk OpenSID nya? soalnya dipunya saya kok error..

**Comment by eddieridwan** [comment]
@hudabikhoir : issue bukan tempat bertanya penggunaan OpenSID. Tanyakan di https://www.facebook.com/groups/OpenSID. Jangan lupa melampirkan tampilan layar error yg alami, seperti di atas.

Issue digunakan untuk daftar tugas, termasuk error yg dipastikan adalah bug.

**Comment by MUHAMMADRANGSEL** [comment]
![screenshot 2018-03-06 10 09 14](https://user-images.githubusercontent.com/25834335/37010560-1ca1c0d6-2127-11e8-91eb-19e198f93667.png)
![screenshot 2018-03-06 10 09 24](https://user-images.githubusercontent.com/25834335/37010561-1d58ec84-2127-11e8-99e6-d314a210927d.png)

**Comment by MUHAMMADRANGSEL** [comment]
Penambahan fasilitas  cetak dan unduh di seub menu SK Kades dan Perdes seperti gambar diatas

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
