### ISSUE TITLE
Bug/error: Search pada kolom status kehadiran tetap berfungsi ketika tampilkan_kehadiran tidak aktif

### ISSUE THREAD

**Issue by nyomanjyotisa** [OpenSID/OpenSID#7990]
### Jelaskan error yg dialami

ketika tampilkan_kehadiran == 0, search pada kolom status kehadiran tetap berfungsi, meskipun kolomnya tidak ditampilkan

### Cara untuk mereplikasi errornya

/layanan-mandiri/kehadiran

### Hasil yg diharapkan

search harusnya tidak berfungsi pada kolom yang tidak ditampilkan

### Tangkapan layar dan log error

https://github.com/OpenSID/OpenSID/assets/73281575/a7687c40-e6f7-4f7f-9fed-184656869983

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

-

### Informasi tambahan

Regards,
I Nyoman Jyotisa

**Comment by nyomanjyotisa** [comment]
Issue ini sudah saya kerjakan pada PR berikut https://github.com/OpenSID/OpenSID/pull/7991

Regards,
I Nyoman Jyotisa

**Comment by andifahruddinakas** [comment]
cek issue https://github.com/OpenSID/OpenSID/issues/7826

dan komentar https://github.com/OpenSID/OpenSID/issues/7986#issuecomment-2132613938

**Comment by andifahruddinakas** [comment]
Sudah disesuaikan saat konvers
