### ISSUE TITLE
Bug/error: Pengaturan Modul tidak berfungsi

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#7995]
### Jelaskan error yg dialami

ketika menonaktifkan atau mengunci salah satu modul menu tetap muncul, seharusnya kalau di sudah digembok/ dikunci menu tersebut tidak tampil lagi

### Cara untuk mereplikasi errornya

ketika menonaktifkan atau mengunci salah satu modul menu tetap muncul, seharusnya kalau di sudah digembok/ dikunci menu tersebut tidak tampil lagi

### Hasil yg diharapkan

Menu Pengaturan Modul Berfungsi seperti diversi sebelumnya

### Tangkapan layar dan log error

![Screenshot 2024-05-25 004819](https://github.com/OpenSID/OpenSID/assets/25834335/67899ad4-2c9f-47a9-8079-46691e7bea11)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

24.05.0.3

**Comment by ariandii** [comment]
tes login selain admin utama.

**Comment by andifahruddinakas** [comment]
pak @MUHAMMADRANGSEL, untuk super admin tidak terpegaruh perubahan tsb. misalkan super-admin tidak sengaja (di https://berputar.opendesa.id/ biasa terjadi, atau mungin sengaja) menonaktifkan semua modul, maka cara untuk mengembalikannya lewat admin tidak ada. sehingga harus diaktifkan kembali melalui database.
