### ISSUE TITLE
Bug/error: Ketika tambah dusun, dusun yang ditambahkan tidak tampil dalam list wilayah administrasi  dusun

### ISSUE THREAD

**Issue by ilhamwahyu-ni** [OpenSID/OpenSID#7998]
### Jelaskan error yg dialami

Ketika tambah dusun pada wilayah administrasi dusun yang ditambahkan tidak tampil dalam list wilayah administrasi dusun namun ketika ditambahkan dengan nama yang sama data gagal disimpan.

### Cara untuk mereplikasi errornya

Info desa > wilayah administrasi 

### Hasil yg diharapkan

Normal kembali bisa tambah duaun

### Tangkapan layar dan log error

Uploading eror.mp4...

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

24.05.03

### Tema Yang Digunakan

-

### Informasi tambahan

Terjadi hal yang sama pada web desa.

**Comment by ilhamwahyu-ni** [comment]
![Screenshot_2024-05-25-20-07-08-389_com android chrome](https://github.com/OpenSID/OpenSID/assets/85351181/ed60b59d-b432-4c9c-8edb-d0ad36f91fd9)


Tangkapan layar..

**Comment by andifahruddinakas** [comment]
sudah diperbaiki melalui commit https://github.com/OpenSID/premium/commit/28bdd21f452eef4f4066d4b648f1f4ea8df1f7b3

**Comment by andifahruddinakas** [comment]
terkait perubahan issue https://github.com/OpenSID/OpenSID/issues/7916
