### ISSUE TITLE
Integrasi Data BDT 2015 kedalam OpenSID

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#800]
Dalam Rangka mempercepat proses integrasi data BDT tahun 2015 kedalam OpenSID yang sekarang ini masih prosesnya panjang perlu disederhakan
kalau sekarang proses yang dilalui seperti dibawah ini
1. Impor Analisis yang sudagh dibuat berbetuk excel
    Analisis BDT ada 2 : 
    1. Analisis Rumah Tangga
    2. Analisis Penduduk/ Individu
2. Impor Pengelompokan Rumah Tangga yang diambil dari Data BDT
3. Export Rumah Tangga melalui Menu Analisis ==> Input Data ==>   Form Excel
    ![image](https://user-images.githubusercontent.com/25834335/36265798-f62d4950-12aa-11e8-8345-d648403e2e40.png)
![image](https://user-images.githubusercontent.com/25834335/36265934-4bb6c4e6-12ab-11e8-95cf-097d4919760e.png)

dan  bisa di tes dengan contoh anailisi yg sdh kami buat
[Analisis BDT Penduduk 2018.zip](https://github.com/OpenSID/OpenSID/files/1728358/Analisis.BDT.Penduduk.2018.zip)
[Analisis BDT Rumah Tangga 2018.zip](https://github.com/OpenSID/OpenSID/files/1728359/Analisis.BDT.Rumah.Tangga.2018.zip)
contoh data BDT
[Contoh Data BDT.zip](https://github.com/OpenSID/OpenSID/files/1728370/Contoh.Data.BDT.zip)

**Comment by MUHAMMADRANGSEL** [comment]
Penyederhanaan yang diiinginkan adalah : Import Analisis dan Jawaban dilakukan 1 kali

**Comment by eddieridwan** [comment]
@MUHAMMADRANGSEL : versi awal sudah siap untuk diujicoba di branch _bdt_ (unduh di https://github.com/OpenSID/OpenSID/tree/bdt).

Belum sempurna, tapi sebaiknya anda coba dulu dan beri umpan balik.

Prosesnya:

1. Impor Analisis BDT yang sudah dibuat berbentuk excel
    1. Analisis Rumah Tangga
    2. Analisis Penduduk/ Individu
2. Di halaman _analisis respons_ (http://localhost:8080/OpenSID/index.php/analisis_respon) untuk analisis rumah tangga, klik tombol baru _Impor BDT 2015_
3. Di halaman _analisis respons_ (http://localhost:8080/OpenSID/index.php/analisis_respon) untuk analisis penduduk, klik tombol baru _Impor BDT 2015_

Pengelompokan rumah tangga dilakukan secara otomatis. Juga pengambilan data respons.

**Catatan: asumsi menggunakan analisis BDT seperti yg digunakan di Bima, dan data BDT dari TNP2K mengikuti format yg diperoleh Bima.**

<img width="1126" alt="impor-bdt" src="https://user-images.githubusercontent.com/249563/36668627-fe0a1c36-1b45-11e8-92ea-77af21fccd7e.png">

**Comment by MUHAMMADRANGSEL** [comment]
Ok. Siap untuk di ujicoba mas eddie

Pada tanggal 26 Feb 2018 7.40 PM, "Eddie Ridwan" <notifications@github.com>
menulis:

**Comment by eddieridwan** [comment]
Ditambahkan opsi di form Analisis Master untuk menampilkan tombol impor data BDT 2015, supaya hanya tampil di analisis yang membutuhkan.

Sudah dicommit ke master.
