### ISSUE TITLE
jumlah kk di wilayah desa tidak sama dengan jumlah kartu keluarga

### ISSUE THREAD

**Issue by mranca** [OpenSID/OpenSID#8001]
### Jelaskan error yg dialami

jumlah kk tidak sama dengan  jumlah kk yang ada pada menu keluarga 

### Cara untuk mereplikasi errornya

1. masuk admin
2. klik wilayah desa

### Hasil yg diharapkan

normal

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/76085245/8ddaab39-2454-4c74-b1d0-80171abb31bc)
sedankan jumlah pada keluarga
![image](https://github.com/OpenSID/OpenSID/assets/76085245/682b4c03-f4c0-4055-b12f-4c8dcedd05e9)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

beta

### Tema Yang Digunakan

.

### Informasi tambahan

.

**Comment by pandigresik** [comment]
ada database yang digunakan untuk issue ini ? agar kondisinya sama

**Comment by andifahruddinakas** [comment]
> ada database yang digunakan untuk issue ini ? agar kondisinya sama

Bisa gunakan backup di beta
