### ISSUE TITLE
Bug/error: Tidak seluruhnya memakai Kop surat pada Buku Administrasi Umum

### ISSUE THREAD

**Issue by ilhamwahyu-ni** [OpenSID/OpenSID#8002]
### Jelaskan error yg dialami

 Pada saat klik tombol cetak,  Tidak seluruhnya memakai Kop surat pada Buku Administrasi Umum, hanya dua buku administrasi umum yang memakai kop surat selebihnya tidak ada kop surat,  yang memakai kop surat hanya buku ekspedisi dan buku keputusan kepala desa.

Setidaknya ada logo desa

### Cara untuk mereplikasi errornya

https://github.com/OpenSID/OpenSID/assets/85351181/2db7d6da-c946-4b95-b39d-7fe496c7642f

### Hasil yg diharapkan

Seluruhnya memakai kop surat atau logo desa

### Tangkapan layar dan log error

![Screenshot_2024-05-26-13-53-04-890_com android chrome](https://github.com/OpenSID/OpenSID/assets/85351181/092805d8-369e-40a8-a531-7ca4bf7bb511)

Buku administrasi umum,> klik tombol cetak

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

24.05.03

**Comment by andifahruddinakas** [comment]
pak @ilhamwahyu-ni, untuk kop masing-masing modul berbeda, tergantung permintaan dari pengguna saat modul tsb dikerjakan.

**Comment by ilhamwahyu-ni** [comment]
baik pak @andifahruddinakas , klw memang seperti itu.
