### ISSUE TITLE
Tampilkan tombol hapus dan lengkapi notifikasi hapus wilayah

### ISSUE THREAD

**Issue by ilhamwahyu-ni** [OpenSID/OpenSID#8004]
### Jelaskan error yg dialami

Ada beberapa tombol delete yang tidak aktif pada wilayah administrasi dusun.

### Cara untuk mereplikasi errornya

Info desa>Wilayah Administratif

### Hasil yg diharapkan

Tombol delete aktif dan bisa hapus data

### Tangkapan layar dan log error

https://github.com/OpenSID/OpenSID/assets/85351181/ac5e7d4a-d508-4128-acb6-3da6981625ca

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

24.05.03

**Comment by andifahruddinakas** [comment]
mas @ilhamwahyu-ni, @rgrahardi, bisa ditambahkan pada panduan. untuk tombol hapus data pada wilyah (untuk semua tingkatan), hanya aktif dan bisa lakukan hapus data jika belum ada data penduduk/keluarga/yg berkaitan dengan wilayah tsb.

**Comment by eddieridwan** [comment]
@andifahruddinakas sebaiknya juga ada notifikasi pada pengguna mengapa tombol hapus tersebut tidak aktif. Supaya mengurangi pertanyaan yg berulang ini.

**Comment by ilhamwahyu-ni** [comment]
Pak @andifahruddinakas apakah  case nya juga sama untuk isu yang ini #7998 pak?

**Comment by andifahruddinakas** [comment]
Untuk menyeragamkan, semua tombol delete tetap diaktifkan, namun saat lakukan eksekusi jika kondisi tdk terpenuhi maka akan menampilkan pesan kesalahan yang harus dilakukan.

Karena beberapa modul cara penanganan untuk kasus seperti ini berbeda2, ada yg tombolnya di hilangkan, ada yg disabled, ada yg tampil tp notifikasi yg diperjelas. Agar kedepannya lebih konsisten penanganan terkait hal ini.

**Comment by andifahruddinakas** [comment]
Tambahan terkait issue ini:
- [ ] tampil tombol issue (tidak perlu di disable atau dihilangkan), cukup perjelas pada bagian notifikasi.
- [ ] pada notifikasi sebaiknya diperjelas bagianmana yang bermasalah, contoh issue https://github.com/OpenSID/OpenSID/issues/8099, arahkan ke data yg bermasalah yg membuat gagal hapus data dusun.
