### ISSUE TITLE
Bug/error: Nama Kolom pada wilayah administrasi jorong tidak sama dengan hasil cetak

### ISSUE THREAD

**Issue by ilhamwahyu-ni** [OpenSID/OpenSID#8005]
### Jelaskan error yg dialami

Saat kita klik tombol cetak pada wilayah administrasi terjadi perbedaan nama kolom, 

saat priview yang tampil adalah NIK KEPALA/KETUA seharusnya NIK Kepala jorong

Nama Kolom pada wilayah administrasi jorong tidak sama dengan hasil cetak, 

### Cara untuk mereplikasi errornya

info nagari > Wilayah administrasi

### Hasil yg diharapkan

sama hasilnya antara yang tampil di wilayah administrasi dengan yang di cetak

### Tangkapan layar dan log error

![Screenshot 2024-05-27 081724](https://github.com/OpenSID/OpenSID/assets/85351181/60d7fee3-8fc3-4fd2-97a6-4defb12c11ff)

![Screenshot 2024-05-27 081805](https://github.com/OpenSID/OpenSID/assets/85351181/5e2cf9ae-1a6f-4eb1-9417-7d7226972e7e)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

24.05.03

**Comment by andifahruddinakas** [comment]
pak @ilhamwahyu-ni, pada bagian wilayah yg dipilih secara khusus, namun untuk cetak mencakup semua data rw/wt dibawahnya. sehingga tidak relevan jika sebutan dusun diberlakukan umum pd halaman tsb.
