### ISSUE TITLE
Bug/error: FORM ISIAN SURAT TIDAK MUNCUL SETELAH PILIH "PENDUDUK DESA" ATAU "PENDUDUK LUAR DESA (LENGKAP)"

### ISSUE THREAD

**Issue by pujocahyono** [OpenSID/OpenSID#8007]
### Jelaskan error yg dialami

FORM ISIAN SURAT TIDAK MUNCUL SETELAH PILIH "PENDUDUK DESA" ATAU "PENDUDUK LUAR DESA (LENGKAP)"

FORM AWAL :
![Cuplikan layar 2024-05-27 114312](https://github.com/OpenSID/OpenSID/assets/87228587/a69ba858-c887-419d-9c0e-efa0ac2c84d1)

SETELAH KLIK "PENDUDUK DESA" ATAU "PENDUDUK LUAR DESA (LENGKAP)"
![Cuplikan layar 2024-05-27 114345](https://github.com/OpenSID/OpenSID/assets/87228587/35c3cd8a-1d57-47be-9bca-b21333943212)

### Cara untuk mereplikasi errornya

1. MASUK KE LAYANAN SURAT YANG MENGGUNAKAN PILIHAN "PENDUDUK DESA" ATAU "PENDUDUK LUAR DESA (LENGKAP)"
2. KLIK "PENDUDUK DESA" ATAU "PENDUDUK LUAR DESA (LENGKAP)"

### Hasil yg diharapkan

KEMBALI NORMAL

### Tangkapan layar dan log error

SEPERTI PENJELASAN ERROR

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2405.0.3

**Comment by ariandii** [comment]
Uploading 2024-05-27_11h54_27.mp4…

**Comment by andifahruddinakas** [comment]
https://github.com/OpenSID/OpenSID/assets/57283157/355459e8-1b8a-4f8f-991c-1f7efcc03612

**Comment by andifahruddinakas** [comment]
pak @pujocahyono, alur memang dibuat seperti itu agar hanya salah 1 yg aktif. jadi, jika sudah memasukkan nik di penduduk desa dan pindah ke penduduk luar, maka data penduduk desa akan dihapus agar tidak duplikasi pada surat.

**Comment by ariandii** [comment]
https://github.com/OpenSID/OpenSID/assets/46939846/1133a71f-245a-41e9-ab2e-ed135f3c2f25

**Comment by pujocahyono** [comment]
yang saya maksud isian yang bawahnya gak muncul. seperti barang jual beli, identitas pembeli, dll pak @andifahruddinakas

**Comment by andifahruddinakas** [comment]
> yang saya maksud isian yang bawahnya gak muncul. seperti barang jual beli, identitas pembeli, dll pak @andifahruddinakas 

Ok, mungkin selanjutnya ditandai bagian yg dimaksud atau sertakn videoonya
