### ISSUE TITLE
Bug/error: Tidak bisa upload dokumen di Layanan Mandiri

### ISSUE THREAD

**Issue by melinggih** [OpenSID/OpenSID#8008]
### Jelaskan error yg dialami

Login Layanan Mandiri > Dokumen > Tambah Dokumen > Browse

### Cara untuk mereplikasi errornya

Login Layanan Mandiri > Dokumen > Tambah Dokumen > Browse

### Hasil yg diharapkan

Login Layanan Mandiri > Dokumen > Tambah Dokumen > Browse

### Tangkapan layar dan log error

![Screenshot 2024-05-28 102625](https://github.com/OpenSID/OpenSID/assets/150767634/46fdd2e6-a17e-42be-a7d0-d0432cadccef)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v2405.0.3-premium

### Tema Yang Digunakan

Silir

**Comment by habibie11** [comment]
kalo di test diberputar dan dilocal saya aman, namun jika dilihat errornya sepertinya data array tidak ada. akan dibuatkan perbaikan sesuai kondisi itu.
![image](https://github.com/OpenSID/OpenSID/assets/56639378/2a478d4e-fb50-432a-a671-1cc8f83f3f02)

cc mas @andifahruddinakas

**Comment by andifahruddinakas** [comment]
> kalo di test diberputar dan dilocal saya aman, namun jika dilihat errornya sepertinya data array tidak ada. akan dibuatkan perbaikan sesuai kondisi itu. ![image](https://private-user-images.githubusercontent.com/56639378/334264596-2a478d4e-fb50-432a-a671-1cc8f83f3f02.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4NzA2MDEsIm5iZiI6MTcxNjg3MDMwMSwicGF0aCI6Ii81NjYzOTM3OC8zMzQyNjQ1OTYtMmE0NzhkNGUtZmI1MC00MzJhLWE2NzEtMWNjOGY4M2YzZjAyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI4VDA0MjUwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM5N2VjNWZjYzM5YzMzMWU5MmE3MWNhYjdmZDAxOWZmNDBlM2Y1MGU0MzlhMzE3ODUwNWZjMGM5YmJkNWM5M2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.G64Gz2RdLBLQw86KH8Gw022H_h9OSq0RoVXCFzB_BHg)
> 
> cc mas @andifahruddinakas

cek pada kepala keluarga yg memiliki anggota keluarga.

![image](https://github.com/OpenSID/OpenSID/assets/57283157/23ca54b3-590d-4b24-9381-fef808211d10)

stack
![image](https://github.com/OpenSID/OpenSID/assets/57283157/15793cfc-1575-4839-871f-91c31f86f775)
