### ISSUE TITLE
Bug/error: Cetak Surat menghasilkan Penanda Tangan turun ke Halaman 2.

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#8011]
### Jelaskan error yg dialami

https://github.com/OpenSID/OpenSID/assets/46939846/ad7498a3-bbd7-4d61-9a8d-5772cfc7eba3

### Cara untuk mereplikasi errornya

tes cetak surat Pengantar seperti video, termasuk surat lain yang menggunakan template penuh 1 halaman.

### Hasil yg diharapkan

disesuaikan

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Berputar

**Comment by andifahruddinakas** [comment]
mas @yogiperdana, bisa sesuaikan template surat bawaan saja. untuk tahap ini kerjakan sesuai issue yakni template surat biodata penduduk. 

pada issue secara umum terkait template bawaan yg perlu dicek dan dibuatkan issue pada masing2 template surat yang formatnya tidak sesuai.
