### ISSUE TITLE
Bug/error: tidak bisa menggunakan kararter ≤ saat di cetak surat atau tinjau pdf karakter berubah menjadi tanda ?

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8012]
### Jelaskan error yg dialami

pada saat melakukan cetak surat karakter ≤ berubah menjadi ? 

### Cara untuk mereplikasi errornya

1. menu cetak surat
2. pada surat insert karakter ≤ 
3. cetak surat / tinjau pdf lihat karakter ≤  berubah jadi ? 

### Hasil yg diharapkan

dapat menampilkan karakter ≤  saat di tinjau pdf dan cetak surat. 

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/55429781/9e1d271d-82d8-4c77-b46c-cad9c33bd6e7)
![image](https://github.com/OpenSID/OpenSID/assets/55429781/e56523df-5633-452c-a015-ecc3374985cd)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2405.0.3-premium

**Comment by habibie11** [comment]
catatan : selain karakter "≤", karakter "≥" juga berubah menjadi "?"

**Comment by pandigresik** [comment]
Solusi mudah yang bisa dipakai adalah dengan memilih font yang support untuk karakter tersebut, seperti comic sans

[Screencast from 30-05-24 06:58:48.webm](https://github.com/OpenSID/OpenSID/assets/1853475/917cb9a3-3e1c-4848-841b-46eaee45791f)

**Comment by habibie11** [comment]
> Solusi mudah yang bisa dipakai adalah dengan memilih font yang support untuk karakter tersebut, seperti comic sans
> 
>  Screencast.from.30-05-24.06.58.48.webm

iya mas sepertinya simbol2 itu tidak terbaca oleh font yang digunakan sehingga perlu diganti dengan font lain. solusi yang sedang diterapkan saat ini jika dalam surat itu ada simbol-simbol serupa akan digantikan dengan font yang support.

**Comment by andifahruddinakas** [comment]
tambahkan yg perlu sj:
<img width="360" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/4203be2f-494b-48c1-b240-04385dd3fc9d">
<img width="362" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/901e9545-7c2c-4325-83b1-d746b633e2f0">
<img width="363" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/7f2b0d86-e5eb-4aff-b988-ad98a6ee8bb7">
<img width="364" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/bb57e9f7-21e4-4c6a-aaaa-aab908f67be3">

karena dari simbol2 tsb tidak semua akan digunakan oleh desa, jd tambahkan dan perbaiki yg sy tanda kotak merah

**Comment by andifahruddinakas** [comment]
perbaikan dilakukan hanya pada simbol2 yang biasan digunakan
