### ISSUE TITLE
Bug/error: eror 500 di rilis dev

### ISSUE THREAD

**Issue by ilhamwahyu-ni** [OpenSID/OpenSID#8013]
### Jelaskan error yg dialami

Test Instalasi rilis dev dari awal sukses..

kemudian coba di backup desa yang terahir menggunakan versi 24.05.3 menjadi rilis dev terdapat eror. 500

### Cara untuk mereplikasi errornya

- gunakan rilis dev
- backup folder desa terahir versi 24.05.03 dan database
- tes di local
- eror 500

### Hasil yg diharapkan

berjalan normal

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/85351181/6a3e9dec-0177-4e76-9603-946d968e9b73)

log =================

<?php defined('BASEPATH') OR exit('No direct script access allowed'); ?>

ERROR - 2024-05-29 05:57:26 --> Unable to connect to the database
ERROR - 2024-05-29 05:57:29 --> Severity: error --> Exception: Please provide a valid cache path. D:\laragon\www\versi\vendor\illuminate\view\Compilers\Compiler.php 36
ERROR - 2024-05-29 06:00:28 --> Unable to connect to the database
ERROR - 2024-05-29 06:00:28 --> Severity: error --> Exception: Please provide a valid cache path. D:\laragon\www\versi\vendor\illuminate\view\Compilers\Compiler.php 36
ERROR - 2024-05-29 06:00:35 --> Unable to connect to the database
ERROR - 2024-05-29 06:00:36 --> Severity: error --> Exception: Please provide a valid cache path. D:\laragon\www\versi\vendor\illuminate\view\Compilers\Compiler.php 36
ERROR - 2024-05-29 06:01:34 --> Unable to connect to the database
ERROR - 2024-05-29 06:01:35 --> Severity: error --> Exception: Please provide a valid cache path. D:\laragon\www\versi\vendor\illuminate\view\Compilers\Compiler.php 36
ERROR - 2024-05-29 06:01:43 --> Unable to connect to the database
ERROR - 2024-05-29 06:01:44 --> Severity: error --> Exception: Please provide a valid cache path. D:\laragon\www\versi\vendor\illuminate\view\Compilers\Compiler.php 36
NOTICE - 2024-05-29 13:02:03 --> Berhasil Jalankan Migrasi_2024052771
NOTICE - 2024-05-29 13:02:03 --> Berhasil Jalankan migrasi_dev
NOTICE - 2024-05-29 13:02:05 --> Versi database sudah terbaru
ERROR - 2024-05-29 13:02:08 --> Query error: The user specified as a definer ('batipua1_sidba'@'localhost') does not exist - Invalid query: SELECT `u`.*, COUNT(p.id) AS jumlah, COUNT(CASE WHEN p.sex = 1 THEN p.id END) AS laki, COUNT(CASE WHEN p.sex = 2 THEN p.id END) AS perempuan
FROM `tweb_penduduk_sex` `u`
LEFT JOIN `penduduk_hidup` `p` ON `u`.`id` = `p`.`sex` AND `p`.`config_id` = 1
LEFT JOIN `tweb_wil_clusterdesa` `a` ON `p`.`id_cluster` = `a`.`id`
GROUP BY `u`.`id`
ERROR - 2024-05-29 13:02:08 --> ["Error Number: 1449","The user specified as a definer ('batipua1_sidba'@'localhost') does not exist","SELECT `u`.*, COUNT(p.id) AS jumlah, COUNT(CASE WHEN p.sex = 1 THEN p.id END) AS laki, COUNT(CASE WHEN p.sex = 2 THEN p.id END) AS perempuan\nFROM `tweb_penduduk_sex` `u`\nLEFT JOIN `penduduk_hidup` `p` ON `u`.`id` = `p`.`sex` AND `p`.`config_id` = 1\nLEFT JOIN `tweb_wil_clusterdesa` `a` ON `p`.`id_cluster` = `a`.`id`\nGROUP BY `u`.`id`","Filename: D:\/laragon\/www\/versi\/vendor\/codeigniter\/framework\/system\/database\/DB_driver.php","Line Number: 692"]
NOTICE - 2024-05-29 13:03:37 --> Berhasil Jalankan Migrasi_2024052771
NOTICE - 2024-05-29 13:03:37 --> Berhasil Jalankan migrasi_dev
NOTICE - 2024-05-29 13:03:38 --> Versi database sudah terbaru
ERROR - 2024-05-29 13:03:39 --> Query error: The user specified as a definer ('batipua1_sidba'@'localhost') does not exist - Invalid query: SELECT `u`.*, COUNT(p.id) AS jumlah, COUNT(CASE WHEN p.sex = 1 THEN p.id END) AS laki, COUNT(CASE WHEN p.sex = 2 THEN p.id END) AS perempuan
FROM `tweb_penduduk_sex` `u`
LEFT JOIN `penduduk_hidup` `p` ON `u`.`id` = `p`.`sex` AND `p`.`config_id` = 1
LEFT JOIN `tweb_wil_clusterdesa` `a` ON `p`.`id_cluster` = `a`.`id`
GROUP BY `u`.`id`
ERROR - 2024-05-29 13:03:39 --> ["Error Number: 1449","The user specified as a definer ('batipua1_sidba'@'localhost') does not exist","SELECT `u`.*, COUNT(p.id) AS jumlah, COUNT(CASE WHEN p.sex = 1 THEN p.id END) AS laki, COUNT(CASE WHEN p.sex = 2 THEN p.id END) AS perempuan\nFROM `tweb_penduduk_sex` `u`\nLEFT JOIN `penduduk_hidup` `p` ON `u`.`id` = `p`.`sex` AND `p`.`config_id` = 1\nLEFT JOIN `tweb_wil_clusterdesa` `a` ON `p`.`id_cluster` = `a`.`id`\nGROUP BY `u`.`id`","Filename: D:\/laragon\/www\/versi\/vendor\/codeigniter\/framework\/system\/database\/DB_driver.php","Line Number: 692"]
ERROR - 2024-05-29 13:04:02 --> Query error: The user specified as a definer ('batipua1_sidba'@'localhost') does not exist - Invalid query: SELECT `u`.*, COUNT(p.id) AS jumlah, COUNT(CASE WHEN p.sex = 1 THEN p.id END) AS laki, COUNT(CASE WHEN p.sex = 2 THEN p.id END) AS perempuan
FROM `tweb_penduduk_sex` `u`
LEFT JOIN `penduduk_hidup` `p` ON `u`.`id` = `p`.`sex` AND `p`.`config_id` = 1
LEFT JOIN `tweb_wil_clusterdesa` `a` ON `p`.`id_cluster` = `a`.`id`
GROUP BY `u`.`id`
ERROR - 2024-05-29 13:04:02 --> ["Error Number: 1449","The user specified as a definer ('batipua1_sidba'@'localhost') does not exist","SELECT `u`.*, COUNT(p.id) AS jumlah, COUNT(CASE WHEN p.sex = 1 THEN p.id END) AS laki, COUNT(CASE WHEN p.sex = 2 THEN p.id END) AS perempuan\nFROM `tweb_penduduk_sex` `u`\nLEFT JOIN `penduduk_hidup` `p` ON `u`.`id` = `p`.`sex` AND `p`.`config_id` = 1\nLEFT JOIN `tweb_wil_clusterdesa` `a` ON `p`.`id_cluster` = `a`.`id`\nGROUP BY `u`.`id`","Filename: D:\/laragon\/www\/versi\/vendor\/codeigniter\/framework\/system\/database\/DB_driver.php","Line Number: 692"]
ERROR - 2024-05-29 13:11:17 --> Query error: The user specified as a definer ('batipua1_sidba'@'localhost') does not exist - Invalid query: SELECT `u`.*, COUNT(p.id) AS jumlah, COUNT(CASE WHEN p.sex = 1 THEN p.id END) AS laki, COUNT(CASE WHEN p.sex = 2 THEN p.id END) AS perempuan
FROM `tweb_penduduk_sex` `u`
LEFT JOIN `penduduk_hidup` `p` ON `u`.`id` = `p`.`sex` AND `p`.`config_id` = 1
LEFT JOIN `tweb_wil_clusterdesa` `a` ON `p`.`id_cluster` = `a`.`id`
GROUP BY `u`.`id`
ERROR - 2024-05-29 13:11:17 --> ["Error Number: 1449","The user specified as a definer ('batipua1_sidba'@'localhost') does not exist","SELECT `u`.*, COUNT(p.id) AS jumlah, COUNT(CASE WHEN p.sex = 1 THEN p.id END) AS laki, COUNT(CASE WHEN p.sex = 2 THEN p.id END) AS perempuan\nFROM `tweb_penduduk_sex` `u`\nLEFT JOIN `penduduk_hidup` `p` ON `u`.`id` = `p`.`sex` AND `p`.`config_id` = 1\nLEFT JOIN `tweb_wil_clusterdesa` `a` ON `p`.`id_cluster` = `a`.`id`\nGROUP BY `u`.`id`","Filename: D:\/laragon\/www\/versi\/vendor\/codeigniter\/framework\/system\/database\/DB_driver.php","Line Number: 692"]

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

rilis dev

**Comment by andifahruddinakas** [comment]
Hasil export dari phpnyadmin idetifier nya di hapus jdkan local saja

**Comment by andifahruddinakas** [comment]
Atau backup dan restore lewat aplikasi
