### ISSUE TITLE
Bug/error: List Jorong Pada Peta yang ditambahkan sebelumnya terlihat Tetapai Pada wilaya administrasi masih tidak ada listnya

### ISSUE THREAD

**Issue by ilhamwahyu-ni** [OpenSID/OpenSID#8015]
### Jelaskan error yg dialami

List Jorong Pada Peta yang ditambahkan sebelumnya terlihat ada tambahan Tetapi Pada wilayah administrasi masih tidak ada listnya.

isu sebelumnya = https://github.com/OpenSID/OpenSID/issues/7998

### Cara untuk mereplikasi errornya

pemetaan >> peta >>control panel >> pilih jorong (dusun)

### Hasil yg diharapkan

sesuai dengan wilayah administrasi dan bisa hapus jorong yang ditambahkan sebelumnya

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/85351181/206aa6ee-b5f0-47d7-8c39-f375e8b0bee7)

1.

![image](https://github.com/OpenSID/OpenSID/assets/85351181/972584db-4823-4856-b9a3-39dce14649a9)

2

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

rilis dev

**Comment by andifahruddinakas** [comment]
Duplicate of https://github.com/OpenSID/OpenSID/issues/7998
