### ISSUE TITLE
Permintaan fitur: Bisa Menambah/ Mengurangi Menu Statis/ Dinamis di Tampilan Halaman Depan Anjungan

### ISSUE THREAD

**Issue by luxmant354** [OpenSID/OpenSID#8017]
### Apa kekurangan yg ingin diatasi?

1. Saat ini halaman depan anjungan menunya terbatas dan tidak bisa diubah sesuai dengan kebutuhan desa, 
2. Menu tambah data di menu admin anjungan tidak ada penambahan link external
![Screenshot_50](https://github.com/OpenSID/OpenSID/assets/44687953/f8c0b498-1826-4cc6-b547-ed017f0ff9b1)

### Jelaskan solusi yg diinginkan

Bisa merubah menu halaman depan anjungan secara flexibel sesuai kebutuhan desa, dan ada penambahan link external
![Screenshot_51](https://github.com/OpenSID/OpenSID/assets/44687953/0ef2f8ec-3412-4805-9adf-78b4145ae0ac)
![Screenshot_52](https://github.com/OpenSID/OpenSID/assets/44687953/1d7189fc-f5eb-4fa6-b665-8e60011e957c)

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

2405.0.0 premium

**Comment by ai-skematik** [comment]
bisa kasih contoh menu yang mau ditambahkan ?

**Comment by ai-skematik** [comment]
karena untuk penambahan menu sesuai kebutuhan desa sudah disiapkan di bagian bawah

**Comment by luxmant354** [comment]
> bisa kasih contoh menu yang mau ditambahkan ?

![Screenshot_69](https://github.com/OpenSID/OpenSID/assets/44687953/00686509-4f4c-4c55-8128-c80037afb5ec)

di desa terkadang ada aplikasi tertentu yang perlu di backlink, dan perlu adanya link external seperti pada menu admin web

**Comment by andifahruddinakas** [comment]
Batasan untuk issue ini hanya pada menu dinamis link eksternal
