### ISSUE TITLE
Bug/error:  Jenis Peristiwa surat kematian dan Judul FOrm berbeda

### ISSUE THREAD

**Issue by ilhamwahyu-ni** [OpenSID/OpenSID#8018]
### Jelaskan error yg dialami

Ketika buat surat kematian >> judul isian nama kurang pas (Tidak sesuai) yang seharusnya adalah IDENTITAS JENAZAH dan yang tampil adalah KETERANGAN PEMOHON.

Kemudian untuk isian jenis peristiwa juga tidak sesuai karena include semua jenis peristiwa yang mana seharussnya hanya jenis peristiwa  (MATI) 

### Cara untuk mereplikasi errornya

Cetak / Buat surat Kematian dari sistim

### Hasil yg diharapkan

Normal seperti biasa

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/85351181/d2084651-3ca3-466e-a828-5323db2b72cd)

![image](https://github.com/OpenSID/OpenSID/assets/85351181/fa902dd0-ec36-4b28-9804-7b255ac11232)

seharusnya..

![image](https://github.com/OpenSID/OpenSID/assets/85351181/803f2222-6046-427e-9824-bca5ca14dabd)

![image](https://github.com/OpenSID/OpenSID/assets/85351181/12ab8831-83f7-4cd3-bea3-3aeb61390920)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

rilis dev

**Comment by andifahruddinakas** [comment]
pak @ilhamwahyu-ni, bisa cek https://berputar.opendesa.id/surat_master/form/227. perbaikan tersebut sudah dilakukan bulan2 sebelumnya. terkait perubahan template surat bawaan, bisa lakukan scr mandiri restore surat bawaan. Karena kemungkinan surat sudah digunakan.

![image](https://github.com/OpenSID/OpenSID/assets/57283157/3fdbbfcd-4cca-41d2-8f78-3e8900e2723b)
![image](https://github.com/OpenSID/OpenSID/assets/57283157/88285691-63d0-4e36-a5b4-d5af353baa54)
![image](https://github.com/OpenSID/OpenSID/assets/57283157/67983090-0b63-4c5d-ad92-c0e584febfa1)
