### ISSUE TITLE
Bug/error: Jumlah Staff Pemerintahan tidak Lengkap di akun warga

### ISSUE THREAD

**Issue by ilhamwahyu-ni** [OpenSID/OpenSID#8019]
### Jelaskan error yg dialami

ketika login dengan akun warga dan ingin melihat siapa Staff pemerintahan.. 

staff pemerintahan berkurang 1 orang dari staff yang ada. 

### Cara untuk mereplikasi errornya

- login dengan akun warga
- klik menu perangkat
- lihat list staff pemerintahan

### Hasil yg diharapkan

lengkap dengan staff pemerintahan yang ada saat ini

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/85351181/08596155-d3f3-42ff-9419-d471f7a7ffb4)

jumlah perangkat yang aktif 16

![image](https://github.com/OpenSID/OpenSID/assets/85351181/88b0845c-a300-458f-9490-0be6186b8fdf)

di akun warga hanya 12 orang

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

rilis dev

### Informasi tambahan

juga sudah di coba berputar 

https://berputar.opendesa.id/

terjadi hal yang sama.

7 staff menjadi 6 staff

![image](https://github.com/OpenSID/OpenSID/assets/85351181/ffc91a49-85cb-425d-a531-f9ac0c458de2)

**Comment by andifahruddinakas** [comment]
bisa gunakan database https://berputar.opendesa.id/pengurus
