### ISSUE TITLE
Bug/error: isian data PENDUDUK LUAR DESA (NAGARI) lampiran surat kematian kosong

### ISSUE THREAD

**Issue by ilhamwahyu-ni** [OpenSID/OpenSID#8020]
### Jelaskan error yg dialami

ketika buat surat kematian dan megisi data dengan PENDUDUK LUAR DESA (NAGARI) baik itu pelapor maupun saksi >> setelah di cetak lampiran f-2.02 atau f2.29 data nya kosong

### Cara untuk mereplikasi errornya

- buat surat kematian 
- isi data pelapor maupun saksi dengan  PENDUDUK LUAR
- pilih lampiran  f-2.02 atau f2.29
- cetak surat

### Hasil yg diharapkan

ter isi datanya

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/85351181/ae8df079-ce6e-4b02-ad9e-e54b1cd8035a)

note : saksi ke 2 dari screen shot adalah data penduduk..

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

rilis dev

### Informasi tambahan

sudah lakukan "mengembalikan surat bawaan/sistim"

**Comment by andifahruddinakas** [comment]
untuk lampiran isiannya masih statis dan belum support untuk penduduk luar. adapun yg bisa diterapkan yakni langsung menggunakan kode isian. namun karena sifatnya yg statis, jika terdapat ubahan kode isian pada pengaturan suratnya, datanya tidak akan tampil.

solusi:
- [ ] ambil data dari kode isiannya
