### ISSUE TITLE
Bug/error:  Ada Tanda Kutip di angka Ribuan pada arsip surat 

### ISSUE THREAD

**Issue by ilhamwahyu-ni** [OpenSID/OpenSID#8021]
### Jelaskan error yg dialami

saya memiliki arsip surat sudah sampai 3230, 

pada tampilan anngka yang ada menjadi 3'230

ada tanda kutip di depan angka 2.

### Cara untuk mereplikasi errornya

surat >> arsip surat >> lihat jumlah entri surat

### Hasil yg diharapkan

angka tampa tanda kutip

### Tangkapan layar dan log error

![Screenshot 2024-05-30 184651](https://github.com/OpenSID/OpenSID/assets/85351181/7de9d499-d325-4e05-bb1f-2d6898d0cc89)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

rilis dev

### Informasi tambahan

juga terjadi di kependudukan >> penduduk dan Keluarga

**Comment by andifahruddinakas** [comment]
![image](https://github.com/OpenSID/OpenSID/assets/57283157/21f608b8-9760-4d16-b3a3-12ca4223e718)
