### ISSUE TITLE
Bug/error: Tambah Dusun data berhasil disimpan namun pada aplikasi data yang baru ditambah tidak tampil

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8026]
### Jelaskan error yg dialami

Tambah Dusun data berhasil disimpan namun pada aplikasi data yang baru ditambah tidak tampil

### Cara untuk mereplikasi errornya

1. menu wilayah administratif
2. tambah dusun
3. simpan
4. pemberi tahuan data berhasil disimpan

### Hasil yg diharapkan

dapat menampilkan dusun yang sudah ditambahkan ke aplikasi

### Tangkapan layar dan log error

![2024-05-31_17h15_38](https://github.com/OpenSID/OpenSID/assets/55429781/5630dae4-b9c5-4981-9c2b-52d4f8c93ecf)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Versi 2405.0.3-premium

**Comment by pandigresik** [comment]
sudah diperbaiki pada commit https://github.com/OpenSID/premium/commit/28bdd21f452eef4f4066d4b648f1f4ea8df1f7b3

**Comment by andifahruddinakas** [comment]
sy buatkan migrasi agar yang terlanjur datanya dapat ditampilkan. https://github.com/OpenSID/premium/commit/904b4afa7f291e85c46b0b2ec2dc76d742083a1f
