### ISSUE TITLE
Bug/error: Tinjau PDF Pada Pengaturan Surat Kematian dan Surat Keterangan Lahir Mati Gagal Memuat dokumen pdf dan error

### ISSUE THREAD

**Issue by luxmant354** [OpenSID/OpenSID#8028]
### Jelaskan error yg dialami

ketika akan mengubah font surat keterangan kematian atau surat keterangan lahir mati, saat ditinjau maka tampilan tidak muncul

### Cara untuk mereplikasi errornya

untuk surat keterangan kematian, di form isian kalau di isi jenis peristiwa ditambahkan kode hidup, maka surat keterangan kematian bisa tampil tinjau pdf

### Hasil yg diharapkan

di pengaturan surat bisa di tinjau pdf seperti surat lainya

### Tangkapan layar dan log error

Tampilan Surat Keterangan Kematian
![Screenshot_55](https://github.com/OpenSID/OpenSID/assets/44687953/d19ef54d-2cf3-4328-9a49-8c8b9bc827f9)

Tampilan Surat Keterangan Lahir Mati
![Screenshot_56](https://github.com/OpenSID/OpenSID/assets/44687953/589fd200-4b85-4fa4-b1d1-386ce824c398)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v2406.0.0-premium

### Tema Yang Digunakan

-

### Informasi tambahan

-

**Comment by andifahruddinakas** [comment]
pak @luxmant354, bisa lakukan migrasi ulang semua jika masih mengalami hal yg sama.
