### ISSUE TITLE
Bug/error: Nama ketua RW tidak tampil ketika melakukan cetak pada fitur wilayah

### ISSUE THREAD

**Issue by pandigresik** [OpenSID/OpenSID#8030]
### Jelaskan error yg dialami

Nama ketua RW tidak tampil

### Cara untuk mereplikasi errornya

1. Pilih menu Info Desa - Wilayah Administratif
2. Set Ketua RW
3. Kembali ke daftar dusun
4. lakukan cetak

### Hasil yg diharapkan

Nama ketua RW tampil, sebagai contoh pada video Ketua RW 01 pada dusun LOCO telah diisi penduduk dengan nama Sata, namun ketika melakukan cetak nama ketua untuk wilayah tersebut kosong

### Tangkapan layar dan log error

[Screencast from 02-06-24 15:37:52.webm](https://github.com/OpenSID/OpenSID/assets/1853475/19f0e704-0021-43a3-87fe-a0c47db37403)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2406.0.0-premium

**Comment by andifahruddinakas** [comment]
mas @agungsugiarto, contoh:
- nama ketua RW pada dusun lonco, RW 01 yakni : asd
![image](https://github.com/OpenSID/OpenSID/assets/57283157/4b12c5de-2f7c-42ba-b918-833d81d05961)

- ketika cetak pada halaman dusun yang tampil
![image](https://github.com/OpenSID/OpenSID/assets/57283157/8c204237-21be-4569-9fc2-8d581eb2d5bf)

**Comment by andifahruddinakas** [comment]
Perhatikan
<img width="722" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/b0ac67fe-19b1-4792-a775-cb12aa97f096">

tidak tampil pada saat cetak
<img width="953" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/06c20d9f-dd0f-41dc-9cd3-e10c3dde45c5">
