### ISSUE TITLE
Hitungan jumlah rw tidak sesuai pada wilayah administratif dusun 

### ISSUE THREAD

**Issue by mranca** [OpenSID/OpenSID#8031]
### Jelaskan error yg dialami

Jumlah rw menampilkan data yang tidak sesuai 

### Cara untuk mereplikasi errornya

1. Mask admin
2. Klik wilayah desa

### Hasil yg diharapkan

Seharusnya data rw  di hitung berdasarkan jumlah input data bukan menjumlahkan angka nomor rw 

### Tangkapan layar dan log error

![snapshot_tongketongke.desa.id_1717319979297.png](https://github.com/OpenSID/OpenSID/assets/76085245/e9f3c036-9197-4d25-a32c-17beaa3cd395)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Terbaru

### Tema Yang Digunakan

.

### Informasi tambahan

.

**Comment by andifahruddinakas** [comment]
pak @mranca, bisa diperjalas untuk issue ini.

**Comment by mranca** [comment]
@andifahruddinakas itu pak cc misalnya dusun saya di bentengnge dimana data rw hanya satu namun yang muncul berjumlah 2 dan total rw ada 12 padahal jumlahnya hanya 7 saja

**Comment by andifahruddinakas** [comment]
> @andifahruddinakas itu pak cc misalnya dusun saya di bentengnge dimana data rw hanya satu namun yang muncul berjumlah 2 dan total rw ada 12 padahal jumlahnya hanya 7 saja

mas @mranca, bisa teruskan database yg bisa digunakan untuk dicek.

**Comment by mranca** [comment]
Oke z kirim lewat telegram saja

**Comment by andifahruddinakas** [comment]
> Oke z kirim lewat telegram saja

ok

**Comment by andifahruddinakas** [comment]
Solusi:
- [ ] jangan hitung rw default -
