### ISSUE TITLE
Bug/error: Form penduduk tidak memberikan notifikasi error, ketika hanya memilih alamat RW tanpa alamat RT

### ISSUE THREAD

**Issue by pandigresik** [OpenSID/OpenSID#8032]
### Jelaskan error yg dialami

Form penduduk tidak memberikan notifikasi error, ketika hanya memilih alamat RW tanpa alamat RT baik melalui menu penduduk maupun keluarga

### Cara untuk mereplikasi errornya

Melalui menu keluarga,
1. Pilih tambah penduduk masuk
2. Isi semua data kecuali pada bagian alamat, pilih dusun dan rw saja ( tanpa memilih RT )
3. Tekan tombol simpan, tombol simpan hanya diam dan aplikasi tidak menampilkan pesan kesalahan

### Hasil yg diharapkan

Memberikan pesan kesalahan, agar pengguna bisa memperbaiki bagian yang belum diisi tersebut

### Tangkapan layar dan log error

https://github.com/OpenSID/OpenSID/assets/1853475/e493dd06-5d2d-40b9-b180-60477ef99d7a

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2406.0.0-premium

**Comment by andifahruddinakas** [comment]
Solusi :
- [ ] tambahkan notifikasi error jika tingkatan dusun/rw/rt belum dipilih
cek versi sebelumnya
![image](https://github.com/OpenSID/OpenSID/assets/57283157/68eb930b-c2e3-477a-81ce-a992ff3a91b0)
