### ISSUE TITLE
Bug/error: Surat Keterangan Pengantar Rujuk atau Cerai Dobel

### ISSUE THREAD

**Issue by luxmant354** [OpenSID/OpenSID#8033]
### Jelaskan error yg dialami

Surat Keterangan Pengantar Rujuk atau Cerai ganda dengan Keterangan Pengantar Rujuk/Cerai	

### Cara untuk mereplikasi errornya

tidak ada error hanya dobel surat saja

### Hasil yg diharapkan

dihapus salah satu, cukup satu saja yang digunakan

### Tangkapan layar dan log error

![Screenshot_58](https://github.com/OpenSID/OpenSID/assets/44687953/3089aded-a937-4cc3-ab88-8b1aa7b0b60c)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v2406.0.0-premium

**Comment by andifahruddinakas** [comment]
Solusi : 

- [ ] ubah surat Keterangan Pengantar Rujuk/Cerai jadi surat desa agar bisa dihapus mandiri

**Comment by ariandii** [comment]
> Solusi :
> 
> * [ ]  ubah surat Keterangan Pengantar Rujuk/Cerai jadi surat desa agar bisa dihapus mandiri

![image](https://github.com/OpenSID/OpenSID/assets/46939846/85d87a50-66ac-4021-989a-38de7015aa28)
 menjadi surat sisitem keduanya. tidak ada tombol hapus.

**Comment by andifahruddinakas** [comment]
> > Solusi :
> > 
> > * [ ]   ubah surat Keterangan Pengantar Rujuk/Cerai jadi surat desa agar bisa dihapus mandiri
> 
> ![image](https://private-user-images.githubusercontent.com/46939846/335935663-85d87a50-66ac-4021-989a-38de7015aa28.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczODg4MTIsIm5iZiI6MTcxNzM4ODUxMiwicGF0aCI6Ii80NjkzOTg0Ni8zMzU5MzU2NjMtODVkODdhNTAtNjZhYy00MDIxLTk4OWEtMzhkZTcwMTVhYTI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAzVDA0MjE1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzZWE2MGY3OTJmNjEzZTZmYWRiOTJhZjE5NmMwYWJlZjJlNjI3YzY5NTA1MmU1OTMxNTZkOTBiNmJkZmVjNjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NYf5lWW3S-49ql0LRRJwt1xfkeEFWX--Nz9P18krAu0) menjadi surat sisitem keduanya. tidak ada tombol hapus.

bisa di cekkan slugnya?

**Comment by ariandii** [comment]
no 1 : https://www.nataibaru.desa.id/surat_master/form/282
dan
no 2 : https://www.nataibaru.desa.id/surat_master/form/297

**Comment by andifahruddinakas** [comment]
> no 1 : https://www.nataibaru.desa.id/surat_master/form/282 dan no 2 : https://www.nataibaru.desa.id/surat_master/form/297

yg ininya pak
![image](https://github.com/OpenSID/OpenSID/assets/57283157/6d794b53-b053-4334-98a2-57c476eb4aeb)

**Comment by ariandii** [comment]
![image](https://github.com/OpenSID/OpenSID/assets/46939846/c5e67735-d992-4b3f-a0a9-41b5db306831)

**Comment by andifahruddinakas** [comment]
> ![image](https://private-user-images.githubusercontent.com/46939846/335938841-c5e67735-d992-4b3f-a0a9-41b5db306831.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczODk1OTcsIm5iZiI6MTcxNzM4OTI5NywicGF0aCI6Ii80NjkzOTg0Ni8zMzU5Mzg4NDEtYzVlNjc3MzUtZDk5Mi00YjNmLWEwYTktNDFiNWRiMzA2ODMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAzVDA0MzQ1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlZTYzMTBhZDdkYmUzMzY4MjMzMWM3YjVlZGU5ZWE4YTBhY2ZiODE4Yzg0YzQ5MzI0MzYxOWVlMjkyOTllMzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rcXkYqqJ00Zflr8QeIFt1_t6j23MdjGGnolwow9CScM)

ok, untuk template yg digunakan bawaan opensid.

![image](https://github.com/OpenSID/OpenSID/assets/57283157/2aca8c78-b234-45f7-b55b-2d912ae2a356)

**Comment by ariandii** [comment]
ID 38 tidak muncul di menu Pengaturan Surat.
ID 297 apakah klik hapus manual di db? sebab muncul kembar di Pengaturan Surat.

**Comment by andifahruddinakas** [comment]
> ![image](https://private-user-images.githubusercontent.com/46939846/335938841-c5e67735-d992-4b3f-a0a9-41b5db306831.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczODk1OTcsIm5iZiI6MTcxNzM4OTI5NywicGF0aCI6Ii80NjkzOTg0Ni8zMzU5Mzg4NDEtYzVlNjc3MzUtZDk5Mi00YjNmLWEwYTktNDFiNWRiMzA2ODMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAzVDA0MzQ1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlZTYzMTBhZDdkYmUzMzY4MjMzMWM3YjVlZGU5ZWE4YTBhY2ZiODE4Yzg0YzQ5MzI0MzYxOWVlMjkyOTllMzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rcXkYqqJ00Zflr8QeIFt1_t6j23MdjGGnolwow9CScM)

sudah disesuaikan

![image](https://github.com/OpenSID/OpenSID/assets/57283157/d7964d24-10bf-4764-a30a-4aeed750c603)

**Comment by ariandii** [comment]
![image](https://github.com/OpenSID/OpenSID/assets/46939846/ec9205da-cf29-4799-b28a-6354434f83b5)

terima kasih, sudah sesuai.

**Comment by andifahruddinakas** [comment]
> ID 38 tidak muncul di menu Pengaturan Surat. ID 297 apakah klik hapus manual di db? sebab muncul kembar di Pengaturan Surat.

yg 38 surat rtf, tidak ditampilkan lg.
