### ISSUE TITLE
Bug/error: kode isian surat TinyMCE PENDUDUK LUAR DESA (LENGKAP) jadi angka

### ISSUE THREAD

**Issue by luxmant354** [OpenSID/OpenSID#8034]
### Jelaskan error yg dialami

ketika memilih surat layanan yang berasal dari sumber PENDUDUK LUAR DESA (LENGKAP) tampilan di tinjau pdf menjadi kode angka.
 

### Cara untuk mereplikasi errornya

input data yang bersumber dari PENDUDUK LUAR DESA (LENGKAP)

### Hasil yg diharapkan

normal kembali seperti versi sebelumnya (v2405.0.3-premium)

### Tangkapan layar dan log error

![Screenshot_59](https://github.com/OpenSID/OpenSID/assets/44687953/55b0d9ef-955a-4c71-973c-f12bd2340334)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v2406.0.0-premium

**Comment by andifahruddinakas** [comment]
Solusi : 

- [ ] cek pada bagian isian pilihan yg menggunakan enum, dikonversi terlebih dahulu ke value nya
