### ISSUE TITLE
Bug/error: tidak bisa menambahkan peserta di daftar program bantuan

### ISSUE THREAD

**Issue by ilhamwahyu-ni** [OpenSID/OpenSID#8035]
### Jelaskan error yg dialami

Ketika menambahkan daftar program bantuan yang baru... Kemudian ingin menambahkan daftar peserta di program bantuan tombol tambah peserta tidak ada.

### Cara untuk mereplikasi errornya

Menu bantuan >> tambah program bantuan >> tombol tambah peserta tidak ada

### Hasil yg diharapkan

Ada tombol tambah peserta seperti ini 
![IMG_20240602_214733](https://github.com/OpenSID/OpenSID/assets/85351181/73ef0631-39b9-40fc-b027-7bb2c2226743)

### Tangkapan layar dan log error

![IMG_20240602_214757](https://github.com/OpenSID/OpenSID/assets/85351181/5d0c7069-cf51-4921-83af-12421d36a625)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

 2406.0.0

**Comment by andifahruddinakas** [comment]
pak @ilhamwahyu-ni, hanya bisa menambahkan peserta bantuan jika masih dalam priode yg aktif. bisa cek dibagian kolom status programbantuannya.

mas @rgrahardi, bisa tambahkan di panduan

**Comment by ilhamwahyu-ni** [comment]
oke pak..🙏
