### ISSUE TITLE
Bug/error: Tombol Delete tidak aktif di Daftar program bantuan 

### ISSUE THREAD

**Issue by ilhamwahyu-ni** [OpenSID/OpenSID#8036]
### Jelaskan error yg dialami

Tidak bisa hapus daftar program bantuan 

### Cara untuk mereplikasi errornya

Manu Bantuan >> tekan tombol hapus

### Hasil yg diharapkan

Bisa di hapus

### Tangkapan layar dan log error

![IMG_20240602_214526](https://github.com/OpenSID/OpenSID/assets/85351181/5468d219-894d-4aab-a4f6-fed8606c531b)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

 2406.0.0

**Comment by andifahruddinakas** [comment]
pak @ilhamwahyu-ni, tombol hapus hanya aktif jika tidak ada peserta pada program tsb.

mas @rgrahardi, bisa tambahkan panduannya

**Comment by ilhamwahyu-ni** [comment]
Baik pak..🙏🏻
