### ISSUE TITLE
Bug/error: Icon Arsip Tidak Pas dan Nama Tombol Berbeda Pada pesan Masuk

### ISSUE THREAD

**Issue by ilhamwahyu-ni** [OpenSID/OpenSID#8037]
### Jelaskan error yg dialami

Ketika mencoba mengarsipkan kotak masuk dan kotak keluar, tombol yang terlihat itu adalah tombol delete dan namanya arsip kemudian ketika ditekan tombol arsip itu konfirmasi pop up yang muncul pada tombol adalah hapus

### Cara untuk mereplikasi errornya

Pesan masuk

![IMG_20240602_231151](https://github.com/OpenSID/OpenSID/assets/85351181/1016681d-5d1c-4aee-8b4b-e4850159b044)

### Hasil yg diharapkan

Bisa ganti icon hapus dengan yang lebih sesuai dan ganti nama tombol pop up hapus menjadi arsipkan

### Tangkapan layar dan log error

![IMG_20240602_231232](https://github.com/OpenSID/OpenSID/assets/85351181/81f41fe4-6c35-4f53-acbf-a53758c1853f)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

 2406.0.0

**Comment by andifahruddinakas** [comment]
Solusi:

- [ ] ganti jd arsipkan
