### ISSUE TITLE
Bug/error: Ubah Kode Isian Alias dan Tombol Hapus

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#8038]
### Jelaskan error yg dialami

1. Saat Ubah Kode Isian Alias dan disimpan, notifikasi berhasil namun akan terjadi dulplikat seperti gambar dibawah ini
![Screenshot 2024-06-03 005702](https://github.com/OpenSID/OpenSID/assets/25834335/7219d133-a323-4d15-85a2-9a8c1ad9dbf8)

2. Tombol Hapus tidak berfungsi

### Cara untuk mereplikasi errornya

Saat Ubah Kode Isian Alias dan disimpan, notifikasi berhasil namun akan terjadi dulplikat seperti gambar dibawah ini
![Screenshot 2024-06-03 005702](https://github.com/OpenSID/OpenSID/assets/25834335/7219d133-a323-4d15-85a2-9a8c1ad9dbf8)

### Hasil yg diharapkan

1. tidak terjadi duplikat
2. Tombol Hapus berfungsi 

### Tangkapan layar dan log error

![Screenshot 2024-06-03 005702](https://github.com/OpenSID/OpenSID/assets/25834335/ef79943a-d9c4-4df3-9a42-fccde0c69fbd)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

24.06.0.0 premium

**Comment by andifahruddinakas** [comment]
pak @MUHAMMADRANGSEL, setiap kali memasukkan judul yg sama akan terdeteksi duplikasi. jika ada celah bisa melewai hal tsb mungkin dijelaskan lebih detail lg.
![image](https://github.com/OpenSID/OpenSID/assets/57283157/792bab7c-2b19-4d6f-b8f4-16bcac2854a2)

**Comment by MUHAMMADRANGSEL** [comment]
saya cek lagi sudah aman
