### ISSUE TITLE
Bug/error: penulisan Judul dan Alias Terbatas

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#8039]
### Jelaskan error yg dialami

PENULISAN JUDUL DAN ALIAS TERBATAS 
![Screenshot 2024-06-03 010230](https://github.com/OpenSID/OpenSID/assets/25834335/f3034692-27dd-46a2-ad52-d72ba1a6af5e)
supaya ada perbedaan dengan bawaan sistem seperti :
Alamat = bawaan sistem
Alamat Lengkap = dari kode isian alias

### Cara untuk mereplikasi errornya

PENULISAN JUDUL DAN ALIAS TERBATAS 
![Screenshot 2024-06-03 010230](https://github.com/OpenSID/OpenSID/assets/25834335/f3034692-27dd-46a2-ad52-d72ba1a6af5e)
supaya ada perbedaan dengan bawaan sistem seperti :
Alamat = bawaan sistem
Alamat Lengkap = dari kode isian alias

### Hasil yg diharapkan

jumlah huruf ditambah

### Tangkapan layar dan log error

![Screenshot 2024-06-03 010230](https://github.com/OpenSID/OpenSID/assets/25834335/620d45f4-c7be-4abd-aa70-abfb33ce6097)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

24.06.0.0

**Comment by andifahruddinakas** [comment]
Solusi : 

- [ ] bisa tambahkan batasan karakter yg bisa digunakan 20 karakter

**Comment by MUHAMMADRANGSEL** [comment]
siap bang
