### ISSUE TITLE
gagal generate csrf token yang kedaluwarsa

### ISSUE THREAD

**Issue by mranca** [OpenSID/OpenSID#8040]
### Jelaskan error yg dialami

terjadi error saat menambah anggota keluarga 

### Cara untuk mereplikasi errornya

1. masuk di admin
2. klik keluarga
3. pilih salah satu kk dan tambahkan anggota keluarga

### Hasil yg diharapkan

.

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/76085245/8b1d688e-0114-49e2-b9a7-8709dffd308a)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

terbaru 

### Tema Yang Digunakan

.

### Informasi tambahan

.

**Comment by andifahruddinakas** [comment]
pak @mranca, bisa sertakan lognya jg

**Comment by mranca** [comment]
Baik

**Comment by mranca** [comment]
@andifahruddinakas close saja issuenya bung sudah normal mungkin pengaruh jaringan tadi hingga muncul demikian

**Comment by ariandii** [comment]
Info Tambahan:
ini juga sempat terjadi ketika klik Login Siteman. Error 500 tidak ada log.

dan ulang login, kembali normal.

==

**Comment by ariandii** [comment]
Usul pak @mranca judul Issue ini dapat diganti (disesuaikan) karena terjadi tidak hanya menambah anggota keluarga, namun kadang saat login, menambah penduduk, ubah data penduduk/keluarga, dll. 

yang tidak ada log nya ketika terjadi erro500

**Comment by mranca** [comment]
@ariandii baik pak

**Comment by andifahruddinakas** [comment]
Mas @agungsugiarto, ini terkait regenerate csrf yg di false, namun dijika di buat true, layanan siap pakai akan jd errror.

**Comment by mranca** [comment]
@andifahruddinakas saat menambah artikel juga terjadi demikian dan tidak ada log error
