### ISSUE TITLE
Cetak Surat

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#8043]
Sediakan halaman untuk menampilkan daftar surat yg bisa dicetak.

![image](https://github.com/OpenSID/OpenSID/assets/57283157/36b9bc7b-e7ed-4ea7-a3d8-4a4fdfa20db0)

- [ ] halaman daftar surat yang bisa dicetak
- [ ] halaman form dengan isian yang perlu di isi pengguna

**Comment by andifahruddinakas** [comment]
Alur Cetak Surat : 
- [ ] saat klik icon tombol cetak surat, arahkan ke form surat.
![image](https://github.com/OpenSID/OpenSID/assets/57283157/25e8b5c5-a45a-4b14-bafb-ec5bba7e53dc)

- [ ] isi form dan klik cetak, maka akan menampilkan notifikasi "surat siap cetak, menunggu verifikasi opertator"
- [ ] arahkan ke halama surat yg sudah tercetak.

catatan :
- daftar surat dibuat dalam bentuk icon, contoh:
![image](https://github.com/OpenSID/OpenSID/assets/57283157/3ebf9d02-43bb-4fab-af24-702787073b23)
- tambahkan autoscroll vertical

**Comment by ai-skematik** [comment]
apakah cetak surat tidak sebaiknya untuk surat yang sudah disetujui kades. jadi tinggal cetak saja. untuk permohonan, sebaiknya namanya buat surat atau permohonan surat

**Comment by andifahruddinakas** [comment]
Pisahke issue https://github.com/OpenSID/OpenSID/issues/8123
