### ISSUE TITLE
drop php 7.4

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#8044]
Batasi versi php yg digunakan 8.1 untuk memudahkan pengembangan.

- [ ] cek terkait strict php 8.1
- [ ] hapus file :
![image](https://github.com/OpenSID/OpenSID/assets/57283157/db41e99e-e4a0-45a8-b18d-631d96c26683)

- [ ] perbarui semua package di composer.json

**Comment by agungsugiarto** [comment]
`cocur/slugify` tidak bisa dihapus karena di butuhkan di package `cviebrock/eloquent-sluggable`

![Image](https://github.com/OpenSID/OpenSID/assets/10989147/85fe2101-2d9e-4537-9bd6-66e770b65783)

**Comment by andifahruddinakas** [comment]
>  `cocur/slugify` tidak bisa dihapus karena di butuhkan di package `cviebrock/eloquent-sluggable`
> 
> ![Image](https://github.com/OpenSID/OpenSID/assets/10989147/85fe2101-2d9e-4537-9bd6-66e770b65783)
> 
> 

Buka packagenya yg di hapus, tapi file modifilkasinya. Ada di foldee storage/app/vendor
