### ISSUE TITLE
Bug/error: Tombol Aksi terpilih di Hak akses Baca Tidak Berfungsi

### ISSUE THREAD

**Issue by ilhamwahyu-ni** [OpenSID/OpenSID#8051]
### Jelaskan error yg dialami

Bug/error: Tombol Aksi terpilih di Hak akses Baca Tidak Berfungsi, atau sebernarnya tombol ini memang tidak ada untuk hak akses baca. 

### Cara untuk mereplikasi errornya

menu pengaturan >> pengguna >> Pengaturan group >> tambah group >> berikan akses baca saja pada pengguna 

![Screenshot 2024-06-03 102551](https://github.com/OpenSID/OpenSID/assets/85351181/fe06c8b6-a089-4814-a87d-2a99c662d4da)

### Hasil yg diharapkan

dihilangkan saja klw memang tidak aktif/tidak digunakan

### Tangkapan layar dan log error

![Screenshot 2024-06-03 102149](https://github.com/OpenSID/OpenSID/assets/85351181/bca0127e-92bf-4936-9d36-c3ccef5f6248)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

 2406.0.0

**Comment by ilhamwahyu-ni** [comment]
![Screenshot 2024-06-03 103137](https://github.com/OpenSID/OpenSID/assets/85351181/357ee5bb-800c-400c-84b0-4b6143496c1c)


hal yang sama terjadi tidak terjadi aksi apapun ketika tombol aksi ditekan

**Comment by ilhamwahyu-ni** [comment]
![Screenshot 2024-06-03 103137](https://github.com/OpenSID/OpenSID/assets/85351181/d35385c3-b4a5-49e7-bbe2-58f1af2cb1b5)

hal yang sama terjadi tidak terjadi aksi apapun ketika tombol aksi ditekan

**Comment by andifahruddinakas** [comment]
sama dengan issue ini https://github.com/OpenSID/OpenSID/issues/8058, terkait hak akses pada fungsi checklist
