### ISSUE TITLE
Konversi Layanan Mandiri Web > Dokumen menggunakan ORM dan Blade

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#8055]
![image](https://github.com/OpenSID/OpenSID/assets/57283157/16aef01e-d6e1-480b-a66d-04e645553c96)

Ubah modul Layanan Mandiri Web > Dokumen menggunakan orm dan blade untuk CRUD.

catatan : 
- [ ] hapus query lama
- [ ] hapus view lama dan gunakan blade (gunakan komponen blade; @if, @forrech, @select, dll)
- [ ] gunakan button non flat, untuk membedakan dengan modul yg sudah dikonversi
- [ ] sesuaikan kondisi terkait tte
- [ ] sederhanakan proses/fungsi yang rumit
- [ ] gunakan pengecekan hak akses yang baru

**Comment by scqolbu24** [comment]
sudah dikerjakan melalui PR https://github.com/OpenSID/premium/pull/3839
