### ISSUE TITLE
Konversi Layanan Mandiri Web > Verifikasi menggunakan ORM dan Blade 

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#8057]
![image](https://github.com/OpenSID/OpenSID/assets/57283157/b209cd79-52c9-4a2a-b4ad-45c741a3b580)

Ubah modul Layanan Mandiri Web > Verifikasi menggunakan orm dan blade untuk CRUD.

catatan : 
- [ ] hapus query lama
- [ ] hapus view lama dan gunakan blade (gunakan komponen blade; @if, @forrech, @select, dll)
- [ ] gunakan button non flat, untuk membedakan dengan modul yg sudah dikonversi
- [ ] sesuaikan kondisi terkait tte
- [ ] sederhanakan proses/fungsi yang rumit
- [ ] gunakan pengecekan hak akses yang baru

**Comment by scqolbu24** [comment]
sudah dikerjakan melalui PR https://github.com/OpenSID/OpenSID/issues/8057
