### ISSUE TITLE
Bug/error: Tidak diperlukan CheckBox di surat keluar dan surat masuk ( HAK AKSES BACA) 

### ISSUE THREAD

**Issue by ilhamwahyu-ni** [OpenSID/OpenSID#8058]
### Jelaskan error yg dialami

CheckBox di surat keluar dan surat masuk tidak berfungsi / sebenarnya tidak diperlukan

### Cara untuk mereplikasi errornya

![Screenshot 2024-06-03 103709](https://github.com/OpenSID/OpenSID/assets/85351181/d84e795a-f705-4f3d-81b1-0270d2db89b4)

### Hasil yg diharapkan

bisa digunakan atau dihapus saja

### Tangkapan layar dan log error

![Screenshot 2024-06-03 103709](https://github.com/OpenSID/OpenSID/assets/85351181/0d108cf5-b11b-4714-b3fc-116ec92dc1fa)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

 2406.0.0

**Comment by andifahruddinakas** [comment]
perubahan seperti ini perlu dibuat konsisten, akan dicek semua terkait hak akses seperti ini.

**Comment by andifahruddinakas** [comment]
mba @FirlianiF, cek juga pembahasan https://github.com/OpenSID/OpenSID/issues/8051

**Comment by andifahruddinakas** [comment]
Perlu pengecekan lebih detail terkait hak akses ini, terutama modul2 yang tidak berada pada menu navigasi.
