### ISSUE TITLE
Bug/error: tidak bisa tambah data Pembangunan, setelah isi data pembangunan klik tombol simpan error blank putih

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8059]
### Jelaskan error yg dialami

tidak bisa tambah data Pembangunan, setelah isi data pembangunan klik tombol simpan error blank putih

### Cara untuk mereplikasi errornya

1. klik menu pembangunan
2. klik tambah
3. isi data
4. klik simpan

### Hasil yg diharapkan

dapat menambahkan data pembangunan

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/55429781/814e4496-04a8-445b-a6e7-2b64f2bc09ed)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2406.0.0-premium

**Comment by andifahruddinakas** [comment]
mas @rgrahardi, sertakan log errornya.

**Comment by ariandii** [comment]
![image](https://github.com/OpenSID/OpenSID/assets/46939846/e57ea0d3-be59-47de-ac0a-17ef867fcec9)
