### ISSUE TITLE
[Pertanahan] [PBB] Tambah catatan pelunasan PBB di data persil

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#806]
https://github.com/noefa86 mengusulkan:

Tambahan: Persil berhubungan dengan pembayaran PBB P-2, di desa kami PBB dibayarkan melalui kasir desa (bendahara PBB). misalkan pada modul Persil ini ditambahkan tabel catatan tentang pelunasan PBB di tahun berjalan dan PBB terutang di tahun sebelumnya mungkin akan membantu desa untuk memonitor tanah persil mana yang sdh lunas atau belum, sehingga memudahkan desa untuk melakukan penagihan.

**Comment by MUHAMMADRANGSEL** [comment]
bangus ini sehingga nanti kepala desa bisa menontrol langsung siapa saja masyarakat yang belum melunasi PBB dan juga banyak desa yang menjadikan persyaratan pelayanan adalah harus melunasi PBB
