### ISSUE TITLE
Bug/error: Kode isian warga negara pada surat dan lampiran sistem

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8060]
### Jelaskan error yg dialami

Bug/error: lampiran pada surat nikah yaitu SURAT PERNYATAAN STATUS (SPS) penulisan WNI salah

### Cara untuk mereplikasi errornya

1. cetak surat nikah
2. cek lampiran sps
3. cek kata WNI 
4. tulisan pada surat Wni seharusnya WNI huruf besar semua 

### Hasil yg diharapkan

Wni menjadi WNI

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/55429781/161276f9-98ac-4250-bf20-2bd025919bf7)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Versi 2406.0.0-premium

**Comment by andifahruddinakas** [comment]
gunakan kode isian untuk warga negara yakni huruf besar. yg perlu diganti
![image](https://github.com/OpenSID/OpenSID/assets/57283157/79a9a236-ca61-4586-89b5-b69b639e94db)
