### ISSUE TITLE
Bug/error: Modul Akses Yang diberikan Masih Banyak di sidePanel Walaupun sudah di Kurangi 

### ISSUE THREAD

**Issue by ilhamwahyu-ni** [OpenSID/OpenSID#8061]
### Jelaskan error yg dialami

Hak akses yang awalnya diberi penuh seluruhnya bisa memakai modul, kemudian setelah dikurangi menu / modul  masih tampil di sidepanel

### Cara untuk mereplikasi errornya

menu pengaturan >> pengguna >> Pengaturan group >> tambah group >> berikan seluruh  akses >> buat pengguna.

kemudian login.

dan kembali ke Pengaturan group >> tambah group >>edit group >> berikan hanya satu menu/modul>> simpan

kemudian coba reload pengguna

### Hasil yg diharapkan

menu /modul (hak akses) yang diberikan admin sama dengan yang dimiliki pengguna

### Tangkapan layar dan log error

![Screenshot 2024-06-03 120507](https://github.com/OpenSID/OpenSID/assets/85351181/fa88845f-ac05-441d-895a-602813e8f841)

seluruh akses

![Screenshot 2024-06-03 120355](https://github.com/OpenSID/OpenSID/assets/85351181/053385b3-fb9e-4657-b398-bfd01eac9835)

==============================
kurangi akses

![Screenshot 2024-06-03 120557](https://github.com/OpenSID/OpenSID/assets/85351181/c7f1c850-8625-4ee1-ab4a-295ec9b8fd5e)

pengguna

![Screenshot 2024-06-03 120730](https://github.com/OpenSID/OpenSID/assets/85351181/12582a99-f402-41ca-8734-2e271d08f9cf)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

 2406.0.0

**Comment by andifahruddinakas** [comment]
mas @ilhamwahyu-ni, bisa eksport hak akses grupnya biar di cek diberuptar.

![image](https://github.com/OpenSID/OpenSID/assets/57283157/e0b0f2da-f598-4e91-8cb7-e989e0dcc234)

**Comment by ilhamwahyu-ni** [comment]
[grup_pengguna_03_06_2024.json](https://github.com/user-attachments/files/15529108/grup_pengguna_03_06_2024.json)

ini pak @andifahruddinakas

**Comment by ilhamwahyu-ni** [comment]
![Screenshot 2024-06-03 123251](https://github.com/OpenSID/OpenSID/assets/85351181/8659aa83-b302-43c3-b5d7-dc62ffce8382)

sudah di expor  grop ke berputar mas... @andifahruddinakas 

hal yang sama terjad

**Comment by andifahruddinakas** [comment]
> 
> ![Screenshot 2024-06-03 123251](https://github.com/OpenSID/OpenSID/assets/85351181/8659aa83-b302-43c3-b5d7-dc62ffce8382)
> 
> sudah di expor  grop ke berputar mas... @andifahruddinakas 
> 
> hal yang sama terjad 

Sy login menggunakan akun tsb normal.

**Comment by ilhamwahyu-ni** [comment]
Karna saya penasaran,,

saya coba beberapa device, beberapa browser mas @andifahruddinakas 

di smartphone menggunakan berputar

ketika ditambah akses modul atau dikurangi dan ini hasil nya

![image](https://github.com/OpenSID/OpenSID/assets/85351181/1aa22bd7-9ae2-46aa-b4c9-ea8b3f544f12)


rubah ke akses penuh

**Comment by ilhamwahyu-ni** [comment]
![IMG_20240603_130346](https://github.com/OpenSID/OpenSID/assets/85351181/735da005-f9a9-4e06-90a4-2c3db958a823)


Penampakan di smartphone browser = mi browser dari xiomi

Mas @andifahruddinakas

**Comment by andifahruddinakas** [comment]
mas @agungsugiarto, hal ini terkait cache admin menu yg tidak terhapus saat melakukan update data.
