### ISSUE TITLE
Bug/error: Jumlah Layanan Surat Pada arsip tidak sesuai

### ISSUE THREAD

**Issue by ilhamwahyu-ni** [OpenSID/OpenSID#8063]
### Jelaskan error yg dialami

Jumlah berbeda pada layanan syrat pada arsip

### Cara untuk mereplikasi errornya

![IMG_20240603_190854](https://github.com/OpenSID/OpenSID/assets/85351181/c202a429-332f-4bc8-a980-2e6db89e20aa)

![IMG_20240603_191037](https://github.com/OpenSID/OpenSID/assets/85351181/144bbf44-8dd8-4231-9c55-ae5b9b4ec047)

### Hasil yg diharapkan

Jumlahnya sama pada semua arsip

### Tangkapan layar dan log error

![IMG_20240603_191315](https://github.com/OpenSID/OpenSID/assets/85351181/5c39b7b7-ee9a-4524-a4fd-8bd30332960b)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

 2406.0.0

**Comment by andifahruddinakas** [comment]
pak @ilhamwahyu-ni, bisa duplikasi masalah ini di https://berputar.opendesa.id/keluar

**Comment by ilhamwahyu-ni** [comment]
Izin mas @andifahruddinakas , ini sudah di berputar mas..

**Comment by ariandii** [comment]
Info Tambahan, jumlah di dashboard terhitung termasuk surat yang masih Konsep,

yang seharusnya sesuai judul yaitu Surat Tercetak. (siap cetak).

bisa dicoba membuat surat lalu klik konsep, maka di dashboard akan bertambah 1. (seharusnya tidak)

**Comment by andifahruddinakas** [comment]
> Info Tambahan, jumlah di dashboard terhitung termasuk surat yang masih Konsep,
> 
> yang seharusnya sesuai judul yaitu Surat Tercetak. (siap cetak).
> 
> bisa dicoba membuat surat lalu klik konsep, maka di dashboard akan bertambah 1. (seharusnya tidak)

bisa ganti pada bagian shorcutnya menggunakan surat tercetak.

**Comment by ariandii** [comment]
![image](https://github.com/OpenSID/OpenSID/assets/46939846/83c68df6-2eb7-4bd5-a777-348180b342a0)

karena gagal upload disini.
saya kirim melalui pesan DC.

**Comment by andifahruddinakas** [comment]
Cek:
![image](https://github.com/user-attachments/assets/572ccb31-2ce1-4ad9-b745-42bec303cbca)

![image](https://github.com/user-attachments/assets/486dcaf1-e57c-4901-9e27-7d1deead4b6a)

Berbeda dengan
![image](https://github.com/user-attachments/assets/9e628063-2eb5-40dd-bf29-8c36a411ad6a)

![image](https://github.com/user-attachments/assets/a61b162f-613c-425e-b632-cf02e4daf7a1)

database terlempir
