### ISSUE TITLE
Bug/error: notifikasi bagi pengguna bila IDM Kemendes tidak bisa diakses

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8066]
### Jelaskan error yg dialami

klik tombol perbarui tidak bisa, dan tidak ada notifikasi kalau IDM Kemendes tidak bisa diakses

### Cara untuk mereplikasi errornya

1. klik menu status desa
2. klik perbarui tidak bisa 

### Hasil yg diharapkan

jika di klik perbarui tidak bisa, terdapat nofikasi notifikasi kalau IDM Kemendes tidak bisa diakses

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/55429781/1b470b71-53cc-415d-bb03-77a1d29de4a8)

![image](https://github.com/OpenSID/OpenSID/assets/55429781/f9c4a8f6-c68b-4b93-9366-07243e8749f4)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Versi 2406.0.0-premium

**Comment by ariandii** [comment]
info, sumber API IDM beberapa hari terakhir sedang off,
contoh:
https://idm.kemendesa.go.id/open/api/desa/rumusan/6201022016/2023

solusi sementara jika terdahulu pernah sukses ambil data json nya, 
dan sudah pernah dibackup folder desa, bisa upload ulang folder desa/cache nya.

**Comment by andifahruddinakas** [comment]
Penerapan saat ini, data eksternal disimpan pada cache, dan kemungkinan akan terhapus dengan beberapa cara. Namun diluar itu, penyebab utama yakni, cache terupdate walau responsenya error.

Solusi : 
- Buat tabel untuk menyimpan data external, dengan struktru : id, judul, key, option, isi
- Cek data yg ada di cache, jika ada pindahkan ke tabel.
- Proses simpan/update hanya dilakukan jika ada response sukses dari server. jika response error jangan disimpan agar data lama tdk terhapus.

**Comment by andifahruddinakas** [comment]
> info, sumber API IDM beberapa hari terakhir sedang off, contoh: https://idm.kemendesa.go.id/open/api/desa/rumusan/6201022016/2023
> 
> solusi sementara jika terdahulu pernah sukses ambil data json nya, dan sudah pernah dibackup folder desa, bisa upload ulang folder desa/cache nya.

mas @rgrahardi, solusi ini bisa digunakan sampai issuenya selesai dikerjakan.

**Comment by andifahruddinakas** [comment]
Website tempat menarik data IDM masih bermasalah https://idm.kemendesa.go.id/rekomendasi, untuk sementara bisa gunakan backup cache.
