### ISSUE TITLE
Permintaan fitur: Penomoran Surat Dinas dan Layanan dijadikan satu

### ISSUE THREAD

**Issue by alit2310** [OpenSID/OpenSID#8072]
### Apa kekurangan yg ingin diatasi?

Supaya tidak terjadi penomoran dobel, Kami didesa untuk surat dinas dan layanan nomornya jadi satu, yg membedakan itu nomor klasifikasi

### Jelaskan solusi yg diinginkan

penomoran surat dijadikan satu

### Apakah ada alternatif lain

Kami didesa untuk surat dinas dan layanan nomornya jadi satu, yg membedakan itu nomor klasifikasi

### Untuk versi OpenSID mana

24.06.1.0

### Informasi tambahan

Kami didesa untuk surat dinas dan layanan nomornya jadi satu, yg membedakan itu nomor klasifikasi

**Comment by ariandii** [comment]
![image](https://github.com/OpenSID/OpenSID/assets/46939846/541a0d82-bda2-4775-b880-a6a4eea7b1c8)

nampaknya hal ini sudah ada, silakan pihak desa tentukan penomoran surat yang sesuai di Pengaturan Surat nya.

seperti panah tersebut.
