### ISSUE TITLE
jumlah calon pemilih berbeda dengan yang tampil halaman admin dan halaman website

### ISSUE THREAD

**Issue by mranca** [OpenSID/OpenSID#8074]
### Jelaskan error yg dialami

jumlah calon pemilih berbeda yang tampil pada halaman admin dengan halaman calon pemilih website

### Cara untuk mereplikasi errornya

1. masuk admin
2. masuk kependudukan
3. klik calon pemilih
4. dan buka pada halaman beranda juga

### Hasil yg diharapkan

.

### Tangkapan layar dan log error

pada halaman admin calon pemilih
![image](https://github.com/OpenSID/OpenSID/assets/76085245/75035b42-5fe1-427c-875d-5e6dc64c77c1)
pada halaman calon pemilih website
![image](https://github.com/OpenSID/OpenSID/assets/76085245/e0765e9e-3719-4bfd-8639-e68af4d323bb)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

terbaru

### Tema Yang Digunakan

natra

### Informasi tambahan

,

**Comment by andifahruddinakas** [comment]
database terlampir

**Comment by mranca** [comment]
Di periksa saja yang z kirimkan database dulu bung

**Comment by andifahruddinakas** [comment]
> Di periksa saja yang z kirimkan database dulu bung

iya, sudah sy lampirkan di GD. tp tdk sy tampilkan dsni krn public.

**Comment by mranca** [comment]
@andifahruddinakas baik bung
