### ISSUE TITLE
Bug/error: Beranda eror 500 ketika tambah shortcut

### ISSUE THREAD

**Issue by ilhamwahyu-ni** [OpenSID/OpenSID#8075]
### Jelaskan error yg dialami

Ketika Tambah shortcut dengan isian tidak lengkap maka pada saat disimpan akan berhasil, kemudian lihat shorcut dii beranda akan terllihan eror 500.

tampa mengisi query..

### Cara untuk mereplikasi errornya

![image](https://github.com/OpenSID/OpenSID/assets/85351181/be0c11c3-8069-4ce7-a703-db2d01d613eb)

### Hasil yg diharapkan

ada validasi nya

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/85351181/8013f504-7043-4a47-b343-93e45a8e1796)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

 2406.0.0

### Informasi tambahan

sudah dicobakan di berputar

**Comment by ilhamwahyu-ni** [comment]
![image](https://github.com/OpenSID/OpenSID/assets/85351181/0e6015bd-ac33-4267-8543-deaeb948126f)

pemilihan warna sepertinya juga

**Comment by andifahruddinakas** [comment]
Solusi : 

- [ ] tambahkan validasi required pada isian hak akses, query dan warna
