### ISSUE TITLE
Bug/error: 404 ketika beri balasan pesan singkat Konfirmasi belum lengkap

### ISSUE THREAD

**Issue by ilhamwahyu-ni** [OpenSID/OpenSID#8076]
### Jelaskan error yg dialami

saat ada mengajukan surat dan persyaratan belum lengkap, kemudian admin akan mengirim pesan singkat ke warga setelah klik tombol simpan terjadi 404 terjadi 404 

### Cara untuk mereplikasi errornya

![image](https://github.com/OpenSID/OpenSID/assets/85351181/d24e5817-0a64-46c2-9ccc-d3056144577f)

![image](https://github.com/OpenSID/OpenSID/assets/85351181/368ae594-fe8d-430c-b846-643815097870)

### Hasil yg diharapkan

pesan terrkirim dan status berubah jadi belum lengkap

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/85351181/abfed9db-8104-44e4-91b7-7b31f2ba606c)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

 2406.0.0

**Comment by ilhamwahyu-ni** [comment]
![image](https://github.com/OpenSID/OpenSID/assets/85351181/2485aa3f-6529-4d94-8220-dbb86468c0a4)

**Comment by andifahruddinakas** [comment]
pak @ilhamwahyu-ni, pada permohonan bagian admin sy tidak mengalami kendala tsb. yg sy temukan kendala ketika melakukan kirim kembali surat yg sudah dibatalkan sebelumnya (sebagai penduduk)

![image](https://github.com/OpenSID/OpenSID/assets/57283157/af132e0a-1f72-4f04-9c93-cdc5e1f629c7)
![image](https://github.com/OpenSID/OpenSID/assets/57283157/de711e19-d85d-4593-8c84-53c9456fcc1f)

**Comment by ilhamwahyu-ni** [comment]
Ya,, saya menemukannya kemaren tu mas,, saat pakai versi 2406, apakah mas sudah coba versi 2406?


Link url ya pun jelas mas..

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melalui pr https://github.com/OpenSID/premium/pull/3887
