### ISSUE TITLE
Bug/error: Gagal membuka menu Lembaga Desa di Halaman Admin (setelah Install Baru)

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#8077]
### Jelaskan error yg dialami

![image](https://github.com/OpenSID/OpenSID/assets/46939846/277bcb15-7530-480f-a405-1d8c3821da03)

### Cara untuk mereplikasi errornya

Install baru, dan buka menu Info Desa -> Lembaga Desa

maka akan muncul seperti gambar atas.

### Hasil yg diharapkan

normal kembali

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v2406.0.0

**Comment by andifahruddinakas** [comment]
pak @ariandii, sy coba install baru dari awal aman. mungkin ada log dari error tersebut.


https://github.com/OpenSID/OpenSID/assets/57283157/3ad0b952-fbce-4518-a3d3-7ce154eebca8

**Comment by rgrahardi** [comment]
pak @ariandii apakah bisa bergabung di sesi Klinik Bug agar kita replikasi bersama terkait issue ini ?
