### ISSUE TITLE
Bug/error: Data Kematian tidak muncul, walau sudah diisi di data pwnduduk mati

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#8080]
### Jelaskan error yg dialami

cetak surat kematian. data kematian tidak terisi

### Cara untuk mereplikasi errornya

cetak surat kematian bawaan sistem

### Hasil yg diharapkan

norml

### Tangkapan layar dan log error

![Screenshot_20240610_093025_Adobe Acrobat](https://github.com/OpenSID/OpenSID/assets/46939846/33b10382-c853-4606-a8e6-eb5391155012)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Terbaru

**Comment by andifahruddinakas** [comment]
disesuaikan melalui commit https://github.com/OpenSID/premium/commit/76d0456b61354b027b3299078506d7268eca47c9, terkait perubahan https://github.com/OpenSID/premium/pull/3769
