### ISSUE TITLE
Bug/error: Sulit membedakan Urutan Foto Produk

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#8084]
### Jelaskan error yg dialami

https://github.com/OpenSID/OpenSID/assets/46939846/af64e0e3-0095-43d1-80cd-9481a5d9e0d1

### Cara untuk mereplikasi errornya

![image](https://github.com/OpenSID/OpenSID/assets/46939846/9310f881-8ddf-48b7-94c6-cfd0dc871c97)

### Hasil yg diharapkan

bisa diberi info angka pada setiap foto tambahan.

misal :
Foto Tambahan 1
Foto Tambahan 2
dst

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Semua

**Comment by andifahruddinakas** [comment]
sudah disesuaikan melalui commit https://github.com/OpenSID/premium/commit/612d3aac6e45c488d55414afab3d5aef3d8c8103
