### ISSUE TITLE
Bug/error: tidak bisa memasukkan pdf surat masuk di buku administrasi umum-administrasi umum

### ISSUE THREAD

**Issue by mah-mudi** [OpenSID/OpenSID#8086]
### Jelaskan error yg dialami

tidak bisa memasukkan pdf surat masuk di buku administrasi umum-administrasi umum

### Cara untuk mereplikasi errornya

buku administrasi umum-administrasi umum

### Hasil yg diharapkan

memasukkan pdf surat masuk di buku administrasi umum-administrasi umum, dapat normal kembali

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/57661283/4a19d236-5729-48aa-95ff-2d6514497d3d)

![image](https://github.com/OpenSID/OpenSID/assets/57661283/3b4f9339-90e0-486d-b9c9-2c78c1f51cae)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

24.06

### Tema Yang Digunakan

silir

### Informasi tambahan

https://berputar.opendesa.id/

**Comment by andifahruddinakas** [comment]
pak @mah-mudi, sy coba di https://berputar.opendesa.id/surat_masuk/form

![image](https://github.com/OpenSID/OpenSID/assets/57283157/e7057ff4-beba-410c-908c-bbaee97a30f3)

![image](https://github.com/OpenSID/OpenSID/assets/57283157/6ab22725-11e9-40e6-bf3f-c584612224fe)

terkait issue https://github.com/OpenSID/OpenSID/issues/8040

untuk sementara, bisa coba tambahkan config di folder desa/config/config.php

`$config['csrf_expire']       = 300; // sesuaikan sendiri, misalkan 1 jam 3600`

**Comment by mah-mudi** [comment]
@andifahruddinakas jika ditambahkan config di folder desa/config/config.php

$config['csrf_expire']       = 300; // sesuaikan sendiri, misalkan 1 jam 3600

mengalami eror ketika upload juga, jd gak bisa narik pdf.

kalau tidak dikasih tambahan $config['csrf_expire']       = 300; , bisa narik pdf tp tidak bisa disimpan, eror 500
