### ISSUE TITLE
Bug/error: Progress di Layanan Surat Tidak Sesuai

### ISSUE THREAD

**Issue by zahrotunnisa24** [OpenSID/OpenSID#8087]
### Jelaskan error yg dialami

1. Di akun kades ini yg urutan no 2, sudah siap cetak, tapi di akun admin dan warga masih menunggu ttd
2. Permohonan surat dari warga sudah di cek dan di setujui admin, tapi tidak masuk di akun kades

### Cara untuk mereplikasi errornya

Mohon untuk di cek sinkronisasi antara 3 akun

### Hasil yg diharapkan

Sinkronisasi antara 3 akun 

### Tangkapan layar dan log error

![TAMPILAN AKUN ADMIN](https://github.com/OpenSID/OpenSID/assets/172345333/a53e07db-c288-4e15-9d95-b265e8ef00ff)
![TAMPILAN AKUN KADES](https://github.com/OpenSID/OpenSID/assets/172345333/e87a3098-5c8c-49de-8c75-9a1855658b6b)
![TAMPILAN AKUN WARGA](https://github.com/OpenSID/OpenSID/assets/172345333/613e2d19-aa1e-4d7a-b236-d6b669874930)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2402.0.3

### Tema Yang Digunakan

De Nava

### Informasi tambahan

-

**Comment by rgrahardi** [comment]
pak / bu @zahrotunnisa24 apakah bisa bergabung di sesi Klinik Bug agar kita replikasi bersama terkait issue ini ?

**Comment by andifahruddinakas** [comment]
alur saat ini, surat yg sudah di tte atau manual, pada permohonan harus diupdate statusnya
