### ISSUE TITLE
Bug/error: Muncul pop-up error keteka membuka menu layanan surat-Permohonan surat

### ISSUE THREAD

**Issue by zahrotunnisa24** [OpenSID/OpenSID#8088]
### Jelaskan error yg dialami

Muncul pop-up error keteka membuka menu layanan surat-permohonan surat

### Cara untuk mereplikasi errornya

Mohon dijelaskan penyebab munculnya pop-up error tersebut

### Hasil yg diharapkan

Error menghilang

### Tangkapan layar dan log error

![ERROR DI PERMOHONAN SURAT](https://github.com/OpenSID/OpenSID/assets/172345333/18ddd15a-7b9e-47fe-8109-6d7001795d71)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2402.0.3

### Tema Yang Digunakan

De Nava

### Informasi tambahan

-

**Comment by andifahruddinakas** [comment]
pak @zahrotunnisa24, dari error yg terlihat terdapat permohonan surat dari penduduk tertentu, namun penduduknya sudah tidak ada.

**Comment by zahrotunnisa24** [comment]
Apakah di ,enu permohonan surat tidak ada menu hapus?
supaya saya bisa menghapus permohonan di kolom 24 sehingga tidak muncul notif error lagi

**Comment by andifahruddinakas** [comment]
sudah disesuaikan, jika relasi penduduk tidak ada akan ditampilkan kosong agar tidak terjadi error.
