### ISSUE TITLE
Bug/error: data wilayah tidak muncul

### ISSUE THREAD

**Issue by ilhamwahyu-ni** [OpenSID/OpenSID#8089]
### Jelaskan error yg dialami

 data wilayah tidak tampil 

### Cara untuk mereplikasi errornya

![image](https://github.com/OpenSID/OpenSID/assets/85351181/0d8c0b6a-118f-45ce-892e-7b40dd86d03f)

### Hasil yg diharapkan

bisa lihaat data wilayah

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/85351181/1af6fd86-1279-4915-88dd-c2c93ddf8a16)

![image](https://github.com/OpenSID/OpenSID/assets/85351181/58026d22-fb32-4c5d-87ec-af9e40baa337)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

bug fix

**Comment by andifahruddinakas** [comment]
mas @ilhamwahyu-ni, bisa gunakan https://beta.opendesa.id/wilayah sebagai web tester terupdate. dari error yg terlihat, di database tsb view tidak lengkap, bisa lihat struktur dari view maupun table saat install baru.
