### ISSUE TITLE
Bug: unduh data penerima bantuan dalam format excel di MENU BANTUAN

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#809]
waktu mau unduh data penerima bantuan yang ada di menu bantuan tidak seluruh data yang diunduh misalkan data yang sebanyak 320 yang ditampilkan 200 maka akan data yang terunduh hanya 200 dan sebaliknya jika data yang ditampilkan 50 maka yang akan diunduh adlah 50 dari 320 : 
![screenshot 2018-02-20 22 32 07](https://user-images.githubusercontent.com/25834335/36429812-93a44cec-168e-11e8-8d56-0922b9cad8db.png)

**Comment by eddieridwan** [comment]
Sdh digabung ke master melalui PR #835.
