### ISSUE TITLE
Bug/error: ada (-) kepala desa tidak memiliki NIPD

### ISSUE THREAD

**Issue by ilhamwahyu-ni** [OpenSID/OpenSID#8090]
### Jelaskan error yg dialami

buat surat pindah seperti biasa dan cetak, jika kepala desa tidak memiliki NIPD terlihat ada tanda (-)

### Cara untuk mereplikasi errornya

- cetak surat pindah
- isi data seperrti biasa
- cetak surat

### Hasil yg diharapkan

tidak menampilkan (-) / kosongkan saja jika kepala desa tidak memiliki NIPD

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/85351181/8acd6448-68dc-441f-83c0-90aede8919c5)

![image](https://github.com/OpenSID/OpenSID/assets/85351181/8648d168-9c34-4b0e-8d47-a85f807332bf)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

bug fix

desa kami belum memiliki NIPD

_No response_

**Comment by andifahruddinakas** [comment]
mas @ilhamwahyu-ni, perubahan tsb bisa disesuaikan masing2 pengguna melalui pengaturan yg sudah disediakan.

![image](https://github.com/OpenSID/OpenSID/assets/57283157/b451d93b-2174-4c18-80da-2146c85165b2)

mas @rgrahardi, bisa dibuatkan panduannya.

**Comment by ilhamwahyu-ni** [comment]
oke mas..
