### ISSUE TITLE
Bug/error: tombol tooltips nya masih menampilkan hapus 

### ISSUE THREAD

**Issue by ilhamwahyu-ni** [OpenSID/OpenSID#8091]
### Jelaskan error yg dialami

arsipkan menjadi hapus data..

### Cara untuk mereplikasi errornya

pesan >> klik tombol arsipkan

### Hasil yg diharapkan

beri notif arsipkan

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/85351181/722acffa-fe67-4f82-99cb-e6ffa7aa8532)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

bug fix

pada kotak masuk dan kotak keluar

_No response_

**Comment by andifahruddinakas** [comment]
disesuaikan melalui commit https://github.com/OpenSID/premium/commit/253cda48f360d864814e7b216fad55733a99a106

bisa dijelaskan bagian2 mana yang perlu diperbaiki.

**Comment by ilhamwahyu-ni** [comment]
Hanya merubah titlenya menjadi arsipkan mas @andifahruddinakas
