### ISSUE TITLE
Daftar pemilih perlu disesuaikan untuk pemilihan Kades

### ISSUE THREAD

**Issue by ilhamwahyu-ni** [OpenSID/OpenSID#8094]
### Jelaskan error yg dialami

Data DPT seharusnya adalah warga 17 tahun keatas pada saat pemilihan kepala desa

![image](https://github.com/OpenSID/OpenSID/assets/85351181/f8ce5a23-3684-4c31-b30c-683e951594d0)

### Cara untuk mereplikasi errornya

![image](https://github.com/OpenSID/OpenSID/assets/85351181/37617f79-2854-4207-9c0f-6e69ef3a4863)

### Hasil yg diharapkan

filter batas umur 17 tahun keatas saja

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/85351181/73f0787a-8ac3-48d0-b3bb-53d6dbd1911a)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

bug fix dan rilis premium

**Comment by eddieridwan** [comment]
<img width="1391" alt="image" src="https://github.com/OpenSID/OpenSID/assets/249563/2a2b4150-27c8-4dc3-9489-aa3713cd8ac4">


@ilhamwahyu-ni apakah syarat pemilihan Kepala Desa berbeda dengan pemilihan umum, yaitu yg masuk ke DPT termasuk yg sudah pernah nikah, meskipun di bawah umur 17 tahun?

Jika memang berbeda, harap lampirkan peraturannya.

@vickyrolanda @andifahruddinakas kalau memang peraturannya berbeda, solusi yg lebih baik adalah menyediakan pilihan apakah untuk (1) Pemilihan Umum atau (2) Pemilihan Kades. Yaitu **tidak** menyediakan filter seperti yg diminta di issue ini.

**Comment by eddieridwan** [comment]
@rgrahardi pastikan syarat DPT telah dipindahkan juga ke panduan.opendesa.id

**Comment by ilhamwahyu-ni** [comment]
Masih sama seperti pemilihan umum pak @eddieridwan, 

Yang saya komentari/bug adalah ada pemilih kades itu berumur 4 tahun pak sesuai gambar diatas

**Comment by eddieridwan** [comment]
@ilhamwahyu-ni kalau dilihat dari tabel anda di atas, kedua orang itu sudah pernah kawin. Di situ masalahnya. Kalau status itu salah, perbaiki status kawin tersebut. 

@andifahruddinakas jadi issue ini ditutup saja. Karena tidak ada yg perlu diperbaiki.

**Comment by ilhamwahyu-ni** [comment]
Wah.. benar jga pak @eddieridwan, saya hanya fokus ke umur, terimakasih koreksinya pak.
