### ISSUE TITLE
Bug/error: Judul kolom tidak sesuai dengan List data Komentar { HAK AKSES BACA}

### ISSUE THREAD

**Issue by ilhamwahyu-ni** [OpenSID/OpenSID#8096]
### Jelaskan error yg dialami

Judul kolom tidak sesuai dengan List data Komentar { HAK AKSES BACA}

### Cara untuk mereplikasi errornya

![image](https://github.com/OpenSID/OpenSID/assets/85351181/79eb0852-8d94-4b30-aaeb-70dd0bea0071)

### Hasil yg diharapkan

normal

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/85351181/43ca8ebe-9a2c-4642-9c1a-ac41b2061dbd)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

 2406.0.1

**Comment by andifahruddinakas** [comment]
terkait issue https://github.com/OpenSID/OpenSID/issues/8058, masalah hak akses
