### ISSUE TITLE
Gagal Export DTKS

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#8097]
![image](https://github.com/OpenSID/OpenSID/assets/57283157/e12d757e-0bd3-4635-bd05-96b069950838)

Saat melakukan export data dtk terjadi gagal eksport.

`ERROR - 2024-06-14 15:14:35 --> Severity: error --> Exception: Call to undefined relationship [pendidikan] on model [App\Models\Penduduk]. D:\PROJECT OPENDESA\OpenSID\vendor\illuminate\database\Eloquent\RelationNotFoundException.php 35
`

Dari error tsb, relasi pendidikan tidak ada, karena pada tabel penduduk sudah tidak menggunakan relasi tsb. Sekarang sudah menggunakan EnumPendidikanSedang.

Solusi:

- [ ] sesuaikan data yang akan diekspor untuk pendidikan gunakan enum yg sudah disediakan.

**Comment by agungsugiarto** [comment]
> Catatan
Menjadi rancu karena sebelumnya referensi pendidikan di ambil dari table `tweb_penduduk_pendidikan` sekarang menjadi duplikat di dua tempat di table dan  `PendidikanSedangEnum`.
 - https://github.com/OpenSID/OpenSID/issues/5129
 - https://github.com/OpenSID/premium/pull/3710

**Comment by andifahruddinakas** [comment]
> > Catatan
> > Menjadi rancu karena sebelumnya referensi pendidikan di ambil dari table `tweb_penduduk_pendidikan` sekarang menjadi duplikat di dua tempat di table dan  `PendidikanSedangEnum`.
> 
> * [Permintaan fitur: Tambahkan pilihan (TIDAK TAMAT SLTP/SLTA) pada kolom kategori pendidikan sedang di tempuh #5129](https://github.com/OpenSID/OpenSID/issues/5129)
> * [WIP: Tambah Referensi Pendidikan Yang Sedang Ditempuh premium#3710](https://github.com/OpenSID/premium/pull/3710)

Sudah disesuaikan di tempat lain, tinggal Dtks yg belum.
