### ISSUE TITLE
Permintaan fitur: saat Tambah Kk baru, terdapat Notifikasi pemberitahuan No KK sudah digunakan, tambahkan pada notifikasi tautan yang bisa diklik untuk melihat No Kk yang sudah digunakan.

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8098]
### Apa kekurangan yg ingin diatasi?

pada Notifikasi pemberitahuan No KK sudah digunakan belum ada tautan yang bisa diklik untuk melihat No KK yg sudah digunakan tersebut. 

![image](https://github.com/OpenSID/OpenSID/assets/55429781/20f91ef0-2c5b-477e-a14a-f91b949ee0b5)

### Jelaskan solusi yg diinginkan

Tambahkan pada notifikasi tautan yang bisa diklik untuk melihat No Kk yang sudah digunakan, agar pengguna bisa klik tautan dan melihat data keluarga / No kk yang sudah digunakan.

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

OpenSID 2407.0.0-premium

### Informasi tambahan

-

**Comment by andifahruddinakas** [comment]
TODO: 

- [ ] tambahkan detail informasi jika NIK sudah digunakan
