### ISSUE TITLE
Bug/error: ketika hapus Dusun terdapat pemberitahuan dan tautan,  Jika diklik tautan belum mengarah ke data Penduduk yang disebutkan status mati, hilang, pergi, tidak valid, atau status KK hilang/pindah dan KK kosong

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8099]
### Jelaskan error yg dialami

ketika hapus Dusun terdapat pemberitahuan dan tautan,  Jika diklik tautan belum mengarah ke data Penduduk yang disebutkan status mati, hilang, pergi, tidak valid, atau status KK hilang/pindah dan KK kosong

### Cara untuk mereplikasi errornya

1. klik menu info desa
2. klik wilayah administratif
3. hapus Dusun
4. terdapat notifikasi dan tautan klik tautan

### Hasil yg diharapkan

ketika klik tautan sesuai ke data penduduk yang menyebabkan dusun tidak bisa di hapus

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/55429781/c69265fb-f8f1-4163-bbb3-4ef56d2a8434)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Versi 2406.0.1-premium

**Comment by andifahruddinakas** [comment]
Duplicate of https://github.com/OpenSID/OpenSID/issues/8004
