### ISSUE TITLE
Bug: Sasaran Keluarga tidak ada pilihan di menu bantuan dan data suplemen, di online

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#810]
pada waktu input data penerima bantuan dengan sasaran Keluarga/ KK fasilitas cari penerima dari database tidak ada begitu juga di data suplemen. permaslahan ini terjadi dihosting kalau di offline berjalan lancar
![screenshot 2018-02-20 22 16 26](https://user-images.githubusercontent.com/25834335/36460013-7d7f66f0-16f1-11e8-9076-058b950deb3d.png)

**Comment by eddieridwan** [comment]
@MUHAMMADRANGSEL: Error ini disebabkan ada data no_kk yang berisi karakter non-alpha. Di keluarga dengan nomor KK '5203031811110017', ubah data KK: hapus nomor KK dan ketik ulang.

Solusi jangka panjang: tambahkan validasi nomor KK: #813

**Comment by MUHAMMADRANGSEL** [comment]
terima kasih banyak mas eddie sekarang sudah bisa, dengan slusi diatas,
walaupun memang kelihatan tdk ada penulisan nomor KK yang aneh tapi itu
yang menyebabkannya error

2018-02-22 19:57 GMT+08:00 Eddie Ridwan <notifications@github.com>:
