### ISSUE TITLE
Bug/error: Data Pada Lampiran Surat Nikah Non Muslim Muncul Tidak Sesuai Isian

### ISSUE THREAD

**Issue by wahyabiantara** [OpenSID/OpenSID#8100]
### Jelaskan error yg dialami

Saat mengisi form Surat Nikah Non Muslim, Data sudah diisi sesuai, namun terjadi beberapa hal yang menjadi permasalahan sebagai berikut:

1. Saat mengisi data Istri, dimana istri juga berasal desa yang sama sehingga data KK ada pada database. Seharusnya data orang tuanya muncul saat memilih data tersebut secara otomatis sama seperti saat memilih data Suami. Namun hal ini tidak muncul
2. Karena data Ayah dan Ibu Istri tidak muncul, kami coba mengisi secara manual, namun pada lampiran data istri, ayah dan ibunya tidak muncul
3. Pada bagian petugas pencatat, nama yang muncul adalah pasangan pria, seharusnya kosong

Berikut adalah data Lampiran yang saya coba di berputar

[ef12b37a-7461-41c3-a1c4-ad1613fb419a.pdf](https://github.com/user-attachments/files/15838365/ef12b37a-7461-41c3-a1c4-ad1613fb419a.pdf)

### Cara untuk mereplikasi errornya

1. Cetak Surat
2. Pilih Surat Nikah Warga Non Muslim

### Hasil yg diharapkan

1. UX isian pada form agar diperbaiki, sehingga tidak terjadi double input terlalu banyak. Jika data orang tuan sudah terdaftar, sebaiknya datanya dimunculkan juga pada form isian.
2. Data lampiran yang muncul agar sesuai dengan form input

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/4361979/30e53d80-0235-4a20-b80f-f0904605f388)

![image](https://github.com/OpenSID/OpenSID/assets/4361979/bbd6b4d2-e543-441a-8f13-2634c065c591)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2406.0.0

**Comment by andifahruddinakas** [comment]
https://github.com/OpenSID/OpenSID/issues/8100
