### ISSUE TITLE
Bug/error: Muncul Error saat TTE

### ISSUE THREAD

**Issue by zahrotunnisa24** [OpenSID/OpenSID#8102]
### Jelaskan error yg dialami

Muncul Error saat TTE sehingga TTE tidak bisa dibuat

### Cara untuk mereplikasi errornya

1. Login di akun Kepala Desa
2. Klik Menu Layanan Surat
3. Klik Menu Arsip Layanan
4. Pilih salah satu surat
5. Klik di Icon Kunci
6. Masukkan Passphrase
7. Muncul Error

### Hasil yg diharapkan

Error Diperbaiki sehingga bisa melakukan TTE

### Tangkapan layar dan log error

![ERROR SAAT TTE](https://github.com/OpenSID/OpenSID/assets/172345333/2985cf6c-9254-47c6-b0bb-850283180d55)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2402.0.3-premium

### Tema Yang Digunakan

De Nava

### Informasi tambahan

-

**Comment by andifahruddinakas** [comment]
bisa dicek pada surat pdf yg dikirim. bisa sertakan template surat yg digunakan.

**Comment by rgrahardi** [comment]
pak/bu @zahrotunnisa24 apakah bisa bergabung di sesi Klinik Bug agar kita replikasi bersama terkait issue ini ?
