### ISSUE TITLE
Bug/error: klik enter search peserta bantuan 404

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8103]
### Jelaskan error yg dialami

klik enter search peserta bantuan 404

### Cara untuk mereplikasi errornya

1. klik bantuan
2. klik rincian bantuan
3. search nama peserta bantuan klik enter
4. muncul 404

### Hasil yg diharapkan

dapat search peserta bantuan dan ketika di enter tidak 404

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/55429781/c4a4779e-0070-468d-89fa-e33bc04456f7)

![image](https://github.com/OpenSID/OpenSID/assets/55429781/23cd7de8-4997-4818-8f2e-717cb7d1b06b)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Versi 2406.0.1-premium

**Comment by andifahruddinakas** [comment]
Sudah disesuaikan melalui commit https://github.com/OpenSID/premium/commit/b137ba8562395f015793d22959255c3f2b71f223

Pada modul ini akan dikonversi menggunakan datatables.
