### ISSUE TITLE
Impor Data Siskeudes Tahun 2024 kembali ke laman web

### ISSUE THREAD

**Issue by rockymakasar** [OpenSID/OpenSID#8106]
### Jelaskan error yg dialami

Saat kita impor data keuangan menggunakan database Siskeudes Tahun 2024. kembali ke halaman web
Data gagal masuk

![image](https://github.com/OpenSID/OpenSID/assets/94730877/4d32b280-0769-4e40-886f-10de2c4e168f)

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

Normal

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2406.0.1-premium

### Tema Yang Digunakan

-

### Informasi tambahan

-

**Comment by andifahruddinakas** [comment]
mas @rockymakasar, bisa sertakan file yg di impor

**Comment by rockymakasar** [comment]
[
[opensid_data.zip](https://github.com/user-attachments/files/15895104/opensid_data.zip)
](url)

**Comment by rockymakasar** [comment]
[Uploading dataapbdesa.zip…]()

**Comment by andifahruddinakas** [comment]
Sudah disesuaikan melalui commit https://github.com/OpenSID/premium/commit/2578087849a6a7de30620a29bd741248a33831c5
