### ISSUE TITLE
Bug/error: Galeri tidak bisa tampil di web

### ISSUE THREAD

**Issue by binrosyad** [OpenSID/OpenSID#8107]
### Jelaskan error yg dialami

Ketika kita menambahkan gambar pada album yg kita buat di galergambar tersebut bisa tampil di slider tapi tidak muncul di halaman Galeri.

### Cara untuk mereplikasi errornya

![galerieror1](https://github.com/OpenSID/OpenSID/assets/106864811/ed227231-fba9-422b-add5-7d3d711329bf)

### Hasil yg diharapkan

Saya berharap agar galeri ini bisa berjalan kembali sebagaimana sebelumnya

### Tangkapan layar dan log error

![galeror2](https://github.com/OpenSID/OpenSID/assets/106864811/8b6f513f-9559-4cf1-9c8e-7d139f927d0a)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2406.0.1-premium

### Tema Yang Digunakan

DeNava v12.0

**Comment by andifahruddinakas** [comment]
pak @binrosyad, untuk galeri agar bisa tampil, bisa tambahkan terlebih dahulu pada menu.

mas @rgrahardi, bisa tambahkan dipanduan.

**Comment by arifpriadi** [comment]
Pada galeri terdapat 2 jenis gambar, yang menggunakan upload atau url. Pada halaman geleri hanya menampilkan upload saja.
