### ISSUE TITLE
Bug/error: Perbaikan Bug issue tidak terurut

### ISSUE THREAD

**Issue by ilhamwahyu-ni** [OpenSID/OpenSID#8109]
### Jelaskan error yg dialami

sebagai tester..

supaya pengecekan bug tidak tertinggal,
supaya tidak terjadi pengulangan isu,

isu pada catatan rilis di aplikasi harusnya di sort()

### Cara untuk mereplikasi errornya

![image](https://github.com/OpenSID/OpenSID/assets/85351181/db493b3e-aad0-42bf-aaa8-b7ad402e6d56)

### Hasil yg diharapkan

terurut

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/85351181/4b9ed0d3-a4c8-4d61-814d-3050396febe8)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

 2406.0.1

**Comment by andifahruddinakas** [comment]
mas @ilhamwahyu-ni, issue dicatatan berdasarkan pengerjaan yang digabungkan. bukan pada urutan issue pembuatan.

**Comment by ilhamwahyu-ni** [comment]
Baik mas..
