### ISSUE TITLE
Permohonan KTP

### ISSUE THREAD

**Issue by djowah** [OpenSID/OpenSID#811]
Kapan ada menu Surat Permohonan KTP F.1-21?

[F-1.21 Formulir Permohonan Kartu Tanda Penduduk (KTP) WNI - Unduhan Dinas Kependudukan Dan Pencatatan Sipil Kabupaten Agam.pdf](https://github.com/OpenSID/OpenSID/files/1742944/F-1.21.Formulir.Permohonan.Kartu.Tanda.Penduduk.KTP.WNI.-.Unduhan.Dinas.Kependudukan.Dan.Pencatatan.Sipil.Kabupaten.Agam.pdf)

**Comment by balongbesuk** [comment]
sudah pernah dibahas, tidak dimasukkan dalam opensid, karena F.1-21 secara "resmi" sudah tidak digunakan,

https://github.com/OpenSID/OpenSID/issues/264

untuk desa yang masih menggunakannya bisa dibuat sendiri, atau demo ke dispendukcapil setempat untuk segera melaksanakan peraturan "Permendagri No 8 Tahun 2016, khususnya Pasal 5, permohonan KTP tidak lagi memerlukan pengisian F-1.21 maupun F-1.06."

**Comment by eddieridwan** [comment]
Issue ini ditutup, karena duplikat dari #264.
