### ISSUE TITLE
Bug/error: Tampilan kondisi Cetak data penduduk dan keluarga sementara tidak sama

### ISSUE THREAD

**Issue by ilhamwahyu-ni** [OpenSID/OpenSID#8110]
### Jelaskan error yg dialami

Tampilan kondisi Cetak data penduduk dan keluarga sementara tidak sama

### Cara untuk mereplikasi errornya
Penduduk

![image](https://github.com/OpenSID/OpenSID/assets/85351181/5507cefb-4b00-4181-b805-109aefc523bd)

![image](https://github.com/OpenSID/OpenSID/assets/85351181/19187b2d-275e-4c96-ae0f-352e641d2c77)

![image](https://github.com/OpenSID/OpenSID/assets/85351181/3c6ea970-3c96-4020-8694-226e75670083)

=========================================================================

Keluarga

![image](https://github.com/OpenSID/OpenSID/assets/85351181/7cf37475-6bcc-4887-aa24-3ce0a5b4da8f)

![image](https://github.com/OpenSID/OpenSID/assets/85351181/ba0fd898-5231-4a6f-962a-1f4858d6c450)

### Hasil yg diharapkan

buat dalam satu kondisi saja (seragam),

klw memang harus nik DAN nkk sementara itu  "0 "

atau dengan pilihan yang lain, supaya kita mengetahui jels bahwa itu data sementara

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/85351181/79e70098-493c-453e-9ab5-7ac19c275bbe)

![image](https://github.com/OpenSID/OpenSID/assets/85351181/b8e30cae-eac9-4d32-ade6-8d6412b05093)

![image](https://github.com/OpenSID/OpenSID/assets/85351181/ff5a8a69-13a3-4793-9867-e212a781e328)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

 2406.0.1

**Comment by andifahruddinakas** [comment]
Bagian yg perlu disesuaikan:

- [ ] untuk filter no_kk semenatara bisa disamakan (pindahkan) dengan yg ada dipenduduk. krn untuk nik dan no_kk sementara pada penduduk tidak bisa dibuat filter karena bukan bagian dari mutasi, begitupun dengan keluarga.
- [ ] untuk cetak, mulai seragamkan, bagian terkait administrasi di nik dan no_kk di kembalikan jadi 0 (tdk bisa digunakan). tahap awal yg pernah dilakukan yakni bagian terkait administrasi kependudukan dan persuratan. Bagian yang lain saat ini belum membutuhkan, jika ada kebutuhan tsb bisa dibuatkan issue permintaan.

**Comment by andifahruddinakas** [comment]
TODO:

- [ ] buat issue untuk cetak penduduk dan keluarga dengan pilihan, kembalikan nik dan no kk semenatara. sama seperti sensor nik.
