### ISSUE TITLE
Bug/error: Form no.telepn pada Produk layanan mandiri tidak ada fungsinya

### ISSUE THREAD

**Issue by ilhamwahyu-ni** [OpenSID/OpenSID#8111]
### Jelaskan error yg dialami

warga yang belum memiliki produk,

kemudian cek menu produk.

ada form no telepon.. 

kemudian selanjutnya apa?

### Cara untuk mereplikasi errornya

login layanan mandiri

![image](https://github.com/OpenSID/OpenSID/assets/85351181/042faea3-52f9-4d01-9d9c-95a1b903c52d)

### Hasil yg diharapkan

normal

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/85351181/0e94dcc1-4011-4c71-b7bf-a98d509c2a9a)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

 2406.0.1

**Comment by andifahruddinakas** [comment]
mas @ilhamwahyu-ni, bisa baca notifikasi yg ditampilkan. pelapak harus didaftarkan dulu oleh admin.

mas @rgrahardi, bisa  buatkan panduan untuk fitur baru ini.

mas @ilhamwahyu-ni, jika ada alur yang ingin diubah, bisa diajukan sebagai permintaan fitur.

**Comment by ilhamwahyu-ni** [comment]
baik mas
