### ISSUE TITLE
Bug/error: Tombol Simpan pada aset tetap lainnya tidak berfungsi

### ISSUE THREAD

**Issue by ilhamwahyu-ni** [OpenSID/OpenSID#8112]
### Jelaskan error yg dialami
Tidak bisa  simpan data aset tetap lainnya

![image](https://github.com/OpenSID/OpenSID/assets/85351181/4983fe76-89a7-4cfb-8e27-80d87486db79)

### Cara untuk mereplikasi errornya

![image](https://github.com/OpenSID/OpenSID/assets/85351181/1165f115-92cb-4d79-8414-936f9d36dbf1)

### Hasil yg diharapkan

bisa simpan data

### Tangkapan layar dan log error

Query error: Field 'nama_barang' doesn't have a default value - Invalid query: INSERT INTO `inventaris_asset` (`kode_barang`, `register`, `jenis`, `jumlah`, `tahun_pengadaan`, `asal`, `harga`, `keterangan`, `visible`, `created_by`, `updated_by`, `config_id`) VALUES ('73.10.11.2001.04.1947', '1', 'H
wan Ternak', '70', '1947', 'Pembelian Sendiri', '9000000', 'Omnis officiis ullam', 1, 1, 1, 1)

log
==========
![image](https://github.com/OpenSID/OpenSID/assets/85351181/e745291c-53f1-4da0-ad49-27f16212999f)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

 2406.0.1

**Comment by andifahruddinakas** [comment]
mas @ilhamwahyu-ni, sy cek dibeta aman dengan mengisi semua form yg ada.
![image](https://github.com/OpenSID/OpenSID/assets/57283157/13517a5b-7331-4406-b9c0-6755c75ed94a)

untuk inventaris bisa prioritaskan pada pengecekan yg sudah dikonversi. https://github.com/OpenSID/OpenSID/issues?q=is%3Aissue+Konversi+Inventaris+is%3Aclosed
