### ISSUE TITLE
bug pada menu sekretariat > sk kades

### ISSUE THREAD

**Issue by kodingku** [OpenSID/OpenSID#812]
pada saaat tambah dokumen baru bisa dan tampil dokumen yang sudah diinput
![screen shot 2018-02-22 at 12 27 34](https://user-images.githubusercontent.com/35604216/36521877-e6d99672-17cb-11e8-9484-a251007dd48c.png)
tetapi setelah di refresh halaman sk kades maka tampilan menjadi kosong list file yang sudah diinput tidak ada
![screen shot 2018-02-22 at 12 28 55](https://user-images.githubusercontent.com/35604216/36521905-0dae2754-17cc-11e8-8987-caf6a6fb107f.png)

**Comment by eddieridwan** [comment]
Kami tutup issue ini. Tapi kalau masih bermasalah, silakan buka lagi.
