### ISSUE TITLE
Bug/error: Form pelapor surat lahir mati kosong

### ISSUE THREAD

**Issue by ilhamwahyu-ni** [OpenSID/OpenSID#8120]
### Jelaskan error yg dialami

buat surat lahir mati

### Cara untuk mereplikasi errornya

![image](https://github.com/OpenSID/OpenSID/assets/85351181/997c444d-31c6-4e10-9fc2-325202447ef7)

![image](https://github.com/OpenSID/OpenSID/assets/85351181/672c8394-420f-402c-8f20-95e3fed313bb)

![image](https://github.com/OpenSID/OpenSID/assets/85351181/7736c705-4833-42b7-bf90-ba5934d33070)

### Hasil yg diharapkan

ada pelapor

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/85351181/fa6aba59-abc0-4af6-be39-00e8b4d80b4e)

lampiran..
[surat-keterangan-lahir-mati_5201141412121724_2024-06-24_1.pdf](https://github.com/user-attachments/files/15949722/surat-keterangan-lahir-mati_5201141412121724_2024-06-24_1.pdf)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

 2406.0.2

**Comment by andifahruddinakas** [comment]
ganti seperti ini

![image](https://github.com/OpenSID/OpenSID/assets/57283157/7a134f5c-60dd-43ae-b434-514db7bd357c)
