### ISSUE TITLE
Penyesuaian Status Kawin

### ISSUE THREAD

**Issue by mranca** [OpenSID/OpenSID#8124]
### Jelaskan error yg dialami

saat mengisi tanggal perkawinan maka seharusnya data yang muncul pada status di kartu keluarga adalah kawin tercatat dan jika tanggal perkawinan di kosongkan maka status hanya tercatat kawin 

### Cara untuk mereplikasi errornya

1. masuk admin
2. klik detail penduduk
3. tambah penduduk dan coba isikan tanggal perkawinan

### Hasil yg diharapkan

data yang seharunya mucul pada kartu keluarga adalah kawin tercatat saat mengisi tanggal perkawinan seperti gambar di bawah kartu keluarga yang di keluarkan oleh dinas capil 
![image](https://github.com/OpenSID/OpenSID/assets/76085245/0df2cd11-0e5b-44c2-b4e6-b16d2e328be0)

### Tangkapan layar dan log error

hanya tampil kawin meski sudah mengisi tanggal perkawinan
![image](https://github.com/OpenSID/OpenSID/assets/76085245/ad5144f5-5842-41bf-b328-94c64290a0e3)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

terbaru

### Tema Yang Digunakan

.

### Informasi tambahan

.

**Comment by agungsugiarto** [comment]
Pak @mranca
Mengutip dari https://disdukcapil.tegalkab.go.id/berita/149-begini-penjelasan-dari-kawin-belum-tercatat

`Status perkawinan tercatat dan belum tercatat dimaksudkan untuk membedakan antara warga yang sudah atau belum memiliki surat nikah yang dikeluarkan Kantor Urusan Agama (KUA) atau akta perkawinan yang dikeluarkan oleh Dinas Dukcapil.`

Jadi meskipun sudah tercatat tanggal perkawinan namun belum memiliki surat nikah yang dikeluarkan KUA atau akta perkawinan maka statusnya kawin belum tercatat.

**Comment by mranca** [comment]
@agungsugiarto,seharunya pak menyesuiakan saja apabila tanggal perkawinan di isi maka kawin tercatat tanpa perlu mengisi nomor akta perkawinan, akan tetapi lebih baiknya nomor akta perkawinannya di input juga jika dokumennya ada

**Comment by mranca** [comment]
@agungsugiarto,seharunya pak menyesuiakan saja apabila tanggal perkawinan di isi maka kawin tercatat tanpa perlu mengisi nomor akta perkawinan

**Comment by mranca** [comment]
@agungsugiarto saya coba input tanggal perkawinan dan mengisi nomor akta perkawinan masih statusnya hanya kawin saja

**Comment by agungsugiarto** [comment]
> @agungsugiarto saya coba input tanggal perkawinan dan mengisi nomor akta perkawinan masih statusnya hanya kawin saja

pr perbaikan https://github.com/OpenSID/premium/pull/3859

**Comment by balongbesuk** [comment]
tanggal nikah itu mengacu pada bukti  Akta pernikahan, sedangkan d cetak KK, sepertinya memang d sembunyikan,

dan sekarang Status Cerai Mati juga ada status Cerai Mati Tidak Tercatat dan Cerai Mati Tercatat dengan bukti nomor Akta Kematian Pasangan,

**Comment by mranca** [comment]
Status kawin tercatat pernah diterapkan di opensid versi sebelumnya hanya dengan mengisi tanggal perkawinan, dan saya rasa itu sudah sesuai dan menyesuaikan juga yang ada di kartu keluarganya

**Comment by andifahruddinakas** [comment]
Perbaikan susulan https://github.com/OpenSID/premium/commit/a72e7df952e3beaa09873866aeadab00e9274a1c
