### ISSUE TITLE
shortcut tidak tampil tidak rapih 

### ISSUE THREAD

**Issue by mranca** [OpenSID/OpenSID#8125]
### Jelaskan error yg dialami

tampilan halaman admin tidak rapih apabilah shurtcut yang tampilh lebih dari 11 

### Cara untuk mereplikasi errornya

1. masuk admin
2. klik pengaturan 
3. klik shortcut 
4. tambah shutcut sampai 12 

### Hasil yg diharapkan

di rapikan tampilan jika mode mobile/hp

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/76085245/451e877d-d490-4964-bd52-584f04b90845)
 tampilan saat mode tablets normal
![image](https://github.com/OpenSID/OpenSID/assets/76085245/9a7fd623-b172-47a8-83a0-1ae81b89b3cf)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

terbaru

### Tema Yang Digunakan

.

### Informasi tambahan

.

**Comment by agungsugiarto** [comment]
saya tidak menemukan masalah yang dimaksud, coba di akses lewat real hp pak @mranca

**Comment by mranca** [comment]
Gambar di bawah saya menggunakan hp vivo v21 pak shortcutnya tidak simetris dengan yang di samping tampilannya turun ke bawah 
![snapshot_tongketongke.desa.id_1719550838823.png](https://github.com/OpenSID/OpenSID/assets/76085245/de7c4d8a-f174-4148-9c70-352ebd2cdc44)

**Comment by andifahruddinakas** [comment]
> Gambar di bawah saya menggunakan hp vivo v21 pak shortcutnya tidak simetris dengan yang di samping tampilannya turun ke bawah ![snapshot_tongketongke.desa.id_1719550838823.png](https://private-user-images.githubusercontent.com/76085245/344038197-de7c4d8a-f174-4148-9c70-352ebd2cdc44.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4MjMwMTMsIm5iZiI6MTcxOTgyMjcxMywicGF0aCI6Ii83NjA4NTI0NS8zNDQwMzgxOTctZGU3YzRkOGEtZjE3NC00MTQ4LTljNzAtMzUyZWJkMmNkYzQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAxVDA4MzE1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk4M2IzMTQ3MjJlMzk0ZTBjYjcxNTNjZDgyNmY0NzM3N2JlMmZjZDUzN2QzOWQ2YjRkMmJkM2M0NzZmOGU0MmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UOM_IrbWoilNPjwZXpXVmJ5027V63mEDVSr0h-7JnsU)

mas @agungsugiarto, @mranca, untuk mengecek disetiap ukuran masing2 layar HP kumungkinan agak sulit dilakukan, karena banyaknya variasi ukuran layar. Namun yg bisa dilakukan yakni:

- [x] jika ukuran layar Hp (umum) dibuat jadi full (ukuran 12)
- [x] jika ukuran tablet (2 kali2 ukuran hp atau agak lebar) bisa dibuat bagi 2 (ukuran 6)

**Comment by andifahruddinakas** [comment]
bisa diseragamka dengan dengan penerapan yg dilakukan pada modul lapak
