### ISSUE TITLE
perbaikan tampilan offline mode

### ISSUE THREAD

**Issue by mranca** [OpenSID/OpenSID#8126]
### Jelaskan error yg dialami

offline mode tidak rapih

### Cara untuk mereplikasi errornya

1. masuk admin
2. klik pengaturan 
3. klik offline mode
4. klik web non aktif sama sekali

### Hasil yg diharapkan

.

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/76085245/1e443524-2f9a-4a53-bc04-540851939781)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

terbaru

### Tema Yang Digunakan

esensi

### Informasi tambahan

.

**Comment by andifahruddinakas** [comment]
dari yg terlihat, pada branch bug-fix sudah sesuai. tinggal masing2 tema menyesuaikan. Bisa cek di https://berputar.opendesa.id/ atau https://beta.opendesa.id/

bisa diinfokan versi yg digunakan.
