### ISSUE TITLE
Bug/error: Menu Shorcut >>Tombol Nonaktif menjadi tombol hapus

### ISSUE THREAD

**Issue by ilhamwahyu-ni** [OpenSID/OpenSID#8128]
### Jelaskan error yg dialami

![image](https://github.com/OpenSID/OpenSID/assets/85351181/2f429e46-330e-43a3-b2a9-28c4b22cb930)

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

bisa non aktifkan shorcut

### Tangkapan layar dan log error

[bug_shorcut.webm](https://github.com/OpenSID/OpenSID/assets/85351181/8bbd5359-68cd-4521-8bf5-9d7d06d9dda3)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

 2406.1.0

**Comment by agungsugiarto** [comment]
Issue ini saya tutup.

Shortcut yang di non aktifkan tidak akan tampil, untuk melihat shortcut yang tidak aktif lakukan filter berdasarkan pilihan `tidak aktif`.

**Comment by ilhamwahyu-ni** [comment]
oke mas
