### ISSUE TITLE
menu masih aktif meski sudah di nonaktifkan 

### ISSUE THREAD

**Issue by mranca** [OpenSID/OpenSID#8130]
### Jelaskan error yg dialami

saat menonaktifkan modul menunya masi muncul meski sudah di gembok

### Cara untuk mereplikasi errornya

1. masuk admin
2. klik pengaturan
3. klik modul
4. nonaktikan salah satu menu
5. dan coba cek apakah masih muncul atau tidak

### Hasil yg diharapkan

.

### Tangkapan layar dan log error
sudah di gembok/dinonaktifkan
![image](https://github.com/OpenSID/OpenSID/assets/76085245/cf06b4aa-0cea-4872-bd70-bd36182e4e77)
menunya masih muncul meski sudah di nonaktikan
![image](https://github.com/OpenSID/OpenSID/assets/76085245/ac42359e-0072-4ecc-8fad-33675c7c7161)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

terbaru

### Tema Yang Digunakan

.

### Informasi tambahan

.

**Comment by agungsugiarto** [comment]
Issue ini saya close, untuk grup akses admin meskipun modul di non aktifkan menu akan tetap tampil (tidak berpengaruh).

**Comment by mranca** [comment]
@agungsugiarto baik pak
