### ISSUE TITLE
Bug/error: Tidak Bisa Salin Template di Template Surat Dinas

### ISSUE THREAD

**Issue by ilhamwahyu-ni** [OpenSID/OpenSID#8131]
### Jelaskan error yg dialami

coba buat surat dinas tidak bisa salin template.

### Cara untuk mereplikasi errornya

![image](https://github.com/OpenSID/OpenSID/assets/85351181/dc0d44e8-fad0-44cb-864e-af91e3ce7b3f)

coba Tambah Surat....

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/85351181/525bba29-c413-416f-9b50-5776c0e16eb8)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

 2406.1.0

**Comment by andifahruddinakas** [comment]
Surat bawaan belum tersedia, sehingga tidak ada tempalate bawaan yg bisa disalin. Dikerjakan issue https://github.com/OpenSID/OpenSID/issues/7765
