### ISSUE TITLE
Terjadi Error saat klik tombol Sedang diperiksa pada Daftar Permohonan surat dari Surat yang dibuat melalui layanan Mandiri

### ISSUE THREAD

**Issue by rockymakasar** [OpenSID/OpenSID#8137]
### Jelaskan error yg dialami

Setelah dibuat surat melalui layanan mandiri, operator melakukan verifikasi pada halaman admin dengan mengklik daftar tombol Sedang diperiksa pada Modul permohonan Surat untuk verifikasi, namun terjadi error
![image](https://github.com/OpenSID/OpenSID/assets/94730877/80f32c74-e7a5-4814-b47c-c4e02af0776b)
![image](https://github.com/OpenSID/OpenSID/assets/94730877/fa03472c-6321-4815-aff8-bd1157e9dc91)

### Cara untuk mereplikasi errornya

1. Layanan Surat
2. Permohonan Surat
3. Klik Tombol Sedang Diperiksa
4. Error 500

### Hasil yg diharapkan

Normal

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2407.0.0-premium

### Tema Yang Digunakan

-

### Informasi tambahan

-

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui commit https://github.com/OpenSID/premium/commit/392b380f3959ab59accebe8790868010b6a57e85, bukan terkait csrf
