### ISSUE TITLE
TIDAK BISA UBAH ANGKA DI "Manual Input Anggaran dan Realisasi APBDes"

### ISSUE THREAD

**Issue by pujocahyono** [OpenSID/OpenSID#8138]
### Jelaskan error yg dialami

TIDAK BISA UBAH ANGKA DI "Manual Input Anggaran dan Realisasi APBDes"

### Cara untuk mereplikasi errornya

1. MENU KEUANGAN
2. INPUT DATA
3. UBAH DATA

### Hasil yg diharapkan

KEMBALI NORMAL

### Tangkapan layar dan log error

![Cuplikan layar 2024-07-02 104637](https://github.com/OpenSID/OpenSID/assets/87228587/8dfb2d91-0e02-43a0-8640-decdebf278fb)

SETELAH DI UBAH ANGKA TETAP
![Cuplikan layar 2024-07-02 104650](https://github.com/OpenSID/OpenSID/assets/87228587/7a821d1c-7904-4f71-9259-99fb0d5160e6)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2407.0.0

**Comment by andifahruddinakas** [comment]
mas @habibie11, cek jg bagian modal lain.
![image](https://github.com/OpenSID/OpenSID/assets/57283157/5604bd39-3b8d-4774-a4b6-f7d94fe4f489)

tekait csrf
