### ISSUE TITLE
Bug/error: Klik Modul Status Desa untuk lihat IDM tidak bisa masuk (hanya loading)

### ISSUE THREAD

**Issue by rockymakasar** [OpenSID/OpenSID#8141]
### Jelaskan error yg dialami

Klik Modul Status Desa untuk lihat IDM tidak bisa masuk (hanya loading)
di berputar juga sama

### Cara untuk mereplikasi errornya

1. Info Desa
2. Status Desa

### Hasil yg diharapkan

Normal

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2407.0.0-premium

### Tema Yang Digunakan

-

### Informasi tambahan

-

**Comment by andifahruddinakas** [comment]
terkait issue https://github.com/OpenSID/OpenSID/issues/8066

**Comment by langonsari** [comment]
![image](https://github.com/user-attachments/assets/8ba41979-dddd-48a5-9da4-27a8dc3446cb)

![image](https://github.com/user-attachments/assets/51295b1f-1f26-48ac-8375-4379cad77b02)
Versi 2410.0.2-premium masih belum tampil

**Comment by pandigresik** [comment]
Sudah diperbaiki pada PR https://github.com/OpenSID/premium/pull/4192

**Comment by pandigresik** [comment]
done
