### ISSUE TITLE
Surat Pernyataan

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#8143]
Contoh Surat Pernyataan : https://darmasaba.desa.id/berita/53669-surat-pernyataan-oleh-kepala-desa-bersama-inspektorat-kab-badung-dan-kadis-pmd-kab-badung

<img width="321" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/74e0fbf0-4d9f-4d8c-8584-a643bd087a1b">

Pada bagian yg ditandai merah, ganti dengan kode isian.

**Comment by habibie11** [comment]
kode isian yang belum ada seperti perbekel, inspektorat, beserta nama dan NIP-nya itu bagaimana mas @andifahruddinakas, ambil dari form isian?

**Comment by andifahruddinakas** [comment]
> kode isian yang belum ada seperti perbekel, inspektorat, beserta nama dan NIP-nya itu bagaimana mas @andifahruddinakas, ambil dari form isian?

Buat di form isian

**Comment by habibie11** [comment]
> > kode isian yang belum ada seperti perbekel, inspektorat, beserta nama dan NIP-nya itu bagaimana mas @andifahruddinakas, ambil dari form isian?
> 
> Buat di form isian

di surat dinas belum ada sumber data penduduk, apakah data penduduk pakai form isian juga?

**Comment by andifahruddinakas** [comment]
> > > kode isian yang belum ada seperti perbekel, inspektorat, beserta nama dan NIP-nya itu bagaimana mas @andifahruddinakas, ambil dari form isian?
> > 
> > 
> > Buat di form isian
> 
> di surat dinas belum ada sumber data penduduk, apakah data penduduk pakai form isian juga?

Pakai Form Isian
