### ISSUE TITLE
Konversi dan buat ulang laporan keuangan dengan modul baru yg sudah dibuat di point 1 dan 2. GUnakan referensi laporan hasil impor yg lengkap.

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#8147]
Sama dengan laporan sebelumnya, laporan yg baru tetap ada dan mengikuti format sebelumnya pada laporan impor. sedangkan laporan manual digabungkan atau menggunakan fungsi yg sama.

Adapun bagian2 yg perlu disesuaikan, bisa dilihat pada bagian navigasinya.
![image](https://github.com/OpenSID/OpenSID/assets/57283157/fd167e4a-5dac-408f-ab51-dcd51fe92fea)

Karena setiap navigasi menampilkan data yg berbeda.
![image](https://github.com/OpenSID/OpenSID/assets/57283157/d7f0e023-68ae-4713-af59-7e445f860445)

Data pendudukung bisa cek di https://github.com/OpenSID/OpenSID/issues/8145

**Comment by pandigresik** [comment]
mas @andifahruddinakas sepertinya acuan yang digunakan seharusnya adalah laporan manual bukan laporan hasil import dikarenakan saat ini semua data dimasukkan dalam tabel yang sama yaitu keuangan. Tabel keuangan secara struktur itu menggantikan keuangan_manual_rinci

**Comment by andifahruddinakas** [comment]
> mas @andifahruddinakas sepertinya acuan yang digunakan seharusnya adalah laporan manual bukan laporan hasil import dikarenakan saat ini semua data dimasukkan dalam tabel yang sama yaitu keuangan. Tabel keuangan secara struktur itu menggantikan keuangan_manual_rinci

OK, untuk sementara seperti itu. Karena data yang ditampung sudah tidak sebenyak dlu dan sudah diseragamkan dari hasil impor dan manual. Harusnya model laporan jg dibuat 1 format.

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/4206
