### ISSUE TITLE
Bug: Penambahan data Penduduk melalui Keluarga Pilihan E-KTP tidak Muncul

### ISSUE THREAD

**Issue by xnuser** [OpenSID/OpenSID#815]
Penambahan Data Penduduk melalui Browser dan bukan Upload via Excel pada menu Penduduk >> +Penduduk Domisili Pilihan E-KTP berjalan dengan baik. namun jika kita hendak menambah Penduduk sekaligus mengelompokkan KK nya melalui menu Penduduk >> Keluarga >> Tambah KK Baru  nah disini Status Kepemilikan KTP pilihannya tidak muncul.
![screenshot_3](https://user-images.githubusercontent.com/36754277/36579036-6fdaeb02-1893-11e8-9257-89580cbeeaca.png)

**Comment by nangalan** [comment]
melalui menu Penduduk >> Keluarga >> Tambah KK >>dikolom isian NIK Kepala KK juga tidak muncul.
![kk](https://user-images.githubusercontent.com/15683308/36818410-763ad272-1d17-11e8-8d04-4ad53438e210.jpg)

**Comment by eddieridwan** [comment]
@nangalan : 
1. masalah yang berbeda harus dibuat issuenya sendiri. Setiap issue harus dibatasi untuk satu masalah/usul saja.
2. yang anda laporkan bukan bug. Daftar penduduk yang muncul di form itu adalah penduduk 'lepas' atau penduduk 'domisili' -- yaitu penduduk yang sudah dimasukkan ke database tapi belum menjadi anggota keluarga manapun. Lihat panduan: https://github.com/OpenSID/OpenSID/wiki/Pengisian-Data-Keluarga.

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
