### ISSUE TITLE
Bug/error: Hasil unduh dan cetak buku administrasi kependudukan tidak semuanya terisi

### ISSUE THREAD

**Issue by Akmal197** [OpenSID/OpenSID#8153]
### Jelaskan error yg dialami

ketika mendownload atau mencetak via pdf buku administrasi kependudukan, terdapat kolom kosong pada kolom kedudukan dalam keluarga dan nomor kartu keluarga.

**1. gambar dibawah ketika cetak pdf**

![image](https://github.com/OpenSID/OpenSID/assets/76812689/84be9b2b-8475-479c-8fff-492da1845d4d)

1. **gambar dibawah ketika unduh excel**

![image](https://github.com/OpenSID/OpenSID/assets/76812689/fecff105-8c93-41fd-a1aa-c65ae2381fb1)

### Cara untuk mereplikasi errornya

1. menu administrasi desa
2. administrasi kependudukan
3. buku induk penduduk
4. unduh/cetak

### Hasil yg diharapkan

hasil unduh dan cetak terisi lengkap

### Tangkapan layar dan log error

diatas

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2407.0.0

### Tema Yang Digunakan

bawaan

**Comment by andifahruddinakas** [comment]
Cek bagian enum SHDK
