### ISSUE TITLE
Bug/error: Surat Keterangan Beda Identitas KIS (Cetak surat) tidak sejajar dan alamt kosong

### ISSUE THREAD

**Issue by ilhamwahyu-ni** [OpenSID/OpenSID#8155]
### Jelaskan error yg dialami

Surat Keterangan Beda Identitas KIS (Cetak surat) tidak sejajar dan alamat kosong

### Cara untuk mereplikasi errornya

kembalikan surat ke default master >> buat surat >> isi data >> cetak

### Hasil yg diharapkan

Sejajarkan Checkbox

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/85351181/e3ba68d1-dde6-4828-b5c5-51b45a40d48f)

dan

![image](https://github.com/OpenSID/OpenSID/assets/85351181/4cc54ea9-32d5-4c99-b4bd-fd3337071e3d)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

 2407.0.0

**Comment by habibie11** [comment]
setelah dicoba, untuk alamat data penduduk ahyar tersebut memang kosong, sudah dicoba menggunakan penduduk yang memiliki alamat berikut tampil :
![image](https://github.com/OpenSID/OpenSID/assets/56639378/b24816d0-9939-4b04-b806-41cb04a21fd4)
