### ISSUE TITLE
Bug/error: QRCode tidak tampil di surat 

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8156]
### Jelaskan error yg dialami

QRCode tidak tampil di surat saat di klik pratinjau surat maupun hasil cetak surat

### Cara untuk mereplikasi errornya

1. klik menu pengaturan surat pada surat keterangan domisili
2. pilih 'Ya' pada pengaturan tampilkan qrcode
3. atau tambahkan kode isian qr code pada surat keterangan domisili
4. klik simpan
5. masuk ke menu cetak surat / pratinjau surat

### Hasil yg diharapkan

dapat menampilkan qrcode pada surat

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/55429781/c8acdea2-e70b-4025-8e46-4e4b76ef8145)

![image](https://github.com/OpenSID/OpenSID/assets/55429781/a8365fab-782a-410d-a42a-afbd314431a1)

![image](https://github.com/OpenSID/OpenSID/assets/55429781/6fb25204-9349-4e99-a4ae-14f9108bef20)

![image](https://github.com/OpenSID/OpenSID/assets/55429781/37729021-fb22-4bb9-974b-2927438155dc)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Versi 2407.0.0-premium

**Comment by habibie11** [comment]
saya test di berputar dan local, aman mas @rgrahardi @andifahruddinakas
![image](https://github.com/OpenSID/OpenSID/assets/56639378/db1584f6-f410-4528-937c-1e6e5d0eb5f7)

**Comment by habibie11** [comment]
test di beta cc mas @andifahruddinakas 
![image](https://github.com/OpenSID/OpenSID/assets/56639378/23f29720-7954-40de-a910-2b820a8566f8)

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melalui pr https://github.com/OpenSID/premium/pull/3888
