### ISSUE TITLE
BUG: Surat tinymce kode isian form input terdapat duplikat `name` yang sama

### ISSUE THREAD

**Issue by agungsugiarto** [OpenSID/OpenSID#8157]
![Image](https://github.com/OpenSID/OpenSID/assets/10989147/c71cab9c-e580-49ae-9981-30fc8c7a08d0)

![Image](https://github.com/OpenSID/OpenSID/assets/10989147/f04abb35-39f3-49ee-aa01-7b75ada75bec)

**Comment by agungsugiarto** [comment]
solusi:
Lihat pada contoh Surat Keterangan Nikah Warga Non Muslim
saat penambahan/mengubah surat validasi periksa duplikasi `name` bandingkan form utama (individu) dengan form lain, jika terdapat duplikasi tambahkan suffix sesuai prefix bagian form.
Contoh:

`anak_ke_cpw`

**Comment by andifahruddinakas** [comment]
> solusi: Lihat pada contoh Surat Keterangan Nikah Warga Non Muslim saat penambahan/mengubah surat validasi periksa duplikasi `name` bandingkan form utama (individu) dengan form lain, jika terdapat duplikasi tambahkan suffix sesuai prefix bagian form. Contoh:
> 
> `anak_ke_cpw`

untuk solusi ini kurang tepat, dan masalah ini sifatnya global. karena pembuatan awal form kode isian tidak dikelompokkan berdasarkan kategorinya.

masalah di atas hanya akan terjadi jika ada kode isiaan yg sama. 
misalnya, kode isian **telepon**, **perkawinan_ke**, **anak_ke** pada surat nikah non muslim. biar nanti prefix menyesuaikan dengan kategorinya.
![image](https://github.com/OpenSID/OpenSID/assets/57283157/d8919aee-012f-4165-9541-c42f0249cefc)

mending dibuat masuk ke kategorinya masing2, tp template surat lain akan terpengaruh karena kode isian perlu disesuaikan pada templatenya.

**Comment by andifahruddinakas** [comment]
Sebaiknya diselesaikan diakar masalahnya. Agar tdk berulang.

**Comment by agungsugiarto** [comment]
Iya perbaikan bukan untuk hasil formnya, tapi di template surat.

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melalui pr https://github.com/OpenSID/premium/pull/3881
