### ISSUE TITLE
Permintaan fitur: Export tempelate surat layanan data form penduduk luar tidak berubah

### ISSUE THREAD

**Issue by luxmant354** [OpenSID/OpenSID#8159]
### Apa kekurangan yg ingin diatasi?

ketika kita membuat surat layanan baru dan disitu ada penduduk luar yang kita sesuaikan dengan kebutuhan, dan sudah sukses sesuai.
dan ketika ada desa lain menginginkan tempelate tersebut ketika kita impor maka kendalanya adalah penduduk luar desa yang sudah kita sesuaikan sesuai kebutuhan tidak ikut terimpor di desa yang kita beri tempelate surat tersebut.
![Screenshot_46](https://github.com/OpenSID/OpenSID/assets/44687953/eba6de85-6a61-4616-87dc-08a1c477c6ab)
![Screenshot_47](https://github.com/OpenSID/OpenSID/assets/44687953/441dcad2-a981-4f81-abc9-1ce56886a3c6)
![Screenshot_48](https://github.com/OpenSID/OpenSID/assets/44687953/7c08843d-3578-4ae2-a214-24be86945def)

### Jelaskan solusi yg diinginkan

perubahan penduduk luar yang kita bikin sendiri/ menyesuaikan kebutuhan desa ikut ter export ke dalam tempelate surat, sehingga desa-desa yang kita beri tempelate surat tidak membuat ulang data form penduduk luar desa yang sudah di sesuaikan

### Apakah ada alternatif lain

desa yang diberi tempelate harus mereplikasi / membuat lagi data form luar desa sesuai arahan pemberi tempelate

### Untuk versi OpenSID mana

2407.0.0-premium

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melalui pr https://github.com/OpenSID/premium/pull/3890
