### ISSUE TITLE
Menampilkan nomor Akta Kelahiran

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#816]
Ketika Klik Kepemilikan Akta Kelahiran yang diinginkan supaya nomor Akta Kelahiran muncul pada waktu cetak dan unduh
![screenshot 2018-02-25 21 27 31](https://user-images.githubusercontent.com/25834335/36641966-53fb1042-1a73-11e8-8a35-8beb0f8ef474.png)
![screenshot 2018-02-25 21 29 29](https://user-images.githubusercontent.com/25834335/36641968-5fa8cef2-1a73-11e8-9862-c2bf9e1d3a53.png)

**Comment by kodingku** [comment]
D reportnya mau ada no akta y om

**Comment by MUHAMMADRANGSEL** [comment]
ya om

**Comment by MUHAMMADRANGSEL** [comment]
Dan juga yang untuk kepemilikan KTP perlu juga

**Comment by kodingku** [comment]
D saya sdh bisa om,hanya saya masih namanya field rumah tangga yang d tampilkan

**Comment by MUHAMMADRANGSEL** [comment]
Bisa dikirimkan perubahan scriptnya

Pada tanggal 26 Feb 2018 8.57 PM, "adirahman" <notifications@github.com>
menulis:

**Comment by MUHAMMADRANGSEL** [comment]
untuk No. AKTA KELAHIRAN JUGA MAS
