### ISSUE TITLE
BUG: Tidak dapat ubah kata sandi ketika pertama kali login (hanya terjadi instalasi baru)

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/OpenSID#8160]
Ketika install baru, akan mengubah kata sandi namun gagal. Informasi tambahan : terjadi pada rilis 2407.0.0 untuk 2406.0.2 masih normal. 
![image](https://github.com/OpenSID/OpenSID/assets/68048807/9c4b4a70-35a1-44a2-ae04-36eca4f4091e)

![image](https://github.com/OpenSID/OpenSID/assets/68048807/1869b7eb-a509-410b-9229-82de6e25345e)

**Comment by andifahruddinakas** [comment]
kasusnya sama dengan  issue https://github.com/OpenSID/OpenSID/issues/8158

tapi sy coba bisa
![image](https://github.com/OpenSID/OpenSID/assets/57283157/28eb255b-5e8a-402d-81af-911c1db13d37)

**Comment by scqolbu24** [comment]
hanya terjadi ketika install baru mas @andifahruddinakas, saya coba di local install baru mengalami eror tersebut
