### ISSUE TITLE
Permintaan fitur: sosialisasikan supaya pemohon memeriksa surat pada tahap pratinjau

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#8161]
### Apa kekurangan yg ingin diatasi?

Saat ini, pada alur yang biasa diterapkan, petugas finalkan surat untuk dicetak dan diberikan pada pemohon. Karena surat sudah final, surat tidak dapat diubah lagi sekiranya pemohon menginginkan perubahan.

Padahal sudah ada fitur untuk cetak pratinjau surat, yg dapat digunakan pemohon untuk memeriksa suatu surat sudah cocok. Karena masih tahap pratinjau, mudah untuk melakukan perubahan surat yang diperlukan. 

### Jelaskan solusi yg diinginkan

1. sosialisasikan fitur untuk mencetak surat pada tahap pratinjau, untuk dapat diperiksa oleh pemohon
2. surat cetakan pratinjau perlu dibubuhi tanda jelas bahwa cetakan itu masih bersifat draf. Misalnya, bubuhi `watermark` bertulisan "DRAF"
3. pastikan panduan memberi petunjuk jelas alur pemeriksaan cetak pratinjau oleh pemohon.

### Apakah ada alternatif lain

Bukan alternatif, tetapi tambahan, dapat juga menyediakan cara supaya petugas dapat menunjukkan layar pratinjau kepada pemohon untuk diperiksa. Tapi itu mungkin sulit secara praktis. 

### Untuk versi OpenSID mana

2408-premium

### Informasi tambahan

Fitur ini merupakan prioritas untuk diterapkan pada 2408, untuk mengatasi keluhan berkelanjutan atas sulitnya mengubah surat hasil cetak fitur surat TinyMCE.

**Comment by pandigresik** [comment]
saat posisi pratinjau, pdf sudah bisa didownload untuk dilakukan proses cetak

**Comment by andifahruddinakas** [comment]
alurnya dikerjakan disini https://github.com/OpenSID/OpenSID/issues/8162
