### ISSUE TITLE
Bug/error: 404 saat hapus data buku tamu

### ISSUE THREAD

**Issue by ilhamwahyu-ni** [OpenSID/OpenSID#8164]
### Jelaskan error yg dialami

hapus data => 404

### Cara untuk mereplikasi errornya

![image](https://github.com/OpenSID/OpenSID/assets/85351181/a2308eab-2b03-42f3-8123-731ff5181642)

### Hasil yg diharapkan

normal

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/85351181/dddee821-8dfe-4d59-b17b-693d87016b50)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

 2407.0.0

**Comment by andifahruddinakas** [comment]
Ini terkait csrf, sudah disesuaikan melalui issue https://github.com/OpenSID/OpenSID/issues/8158
