### ISSUE TITLE
Permintaan fitur: sediakan spesifikasi layout surat yg standar, dan mudah disesuaikan

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#8165]
### Apa kekurangan yg ingin diatasi?

Saat ini, banyak pengguna yang mengeluh sulitnya mengatur layout surat, terutama untuk kasus2 data banyak supaya muat dalam satu halaman

### Jelaskan solusi yg diinginkan

1. Terapkan adanya spesifikasi layout surat standar terpisah untuk Surat Layanan dan Surat Dinas, sesuai ketentuan, mencakup antara lain:

- ukuran halaman F4
- margin atas/bawah/kiri/kanan
- spasi/jarak antar baris 
- jenis font standar/baku
- ukuran font (berapa point, PX)
- dalam tabel, berapa jarak ke garis pinggir cell (padding berapa)

2. Desa dapat menyesuaikan spesifikasi standar tersebut sesuai ketentuan dan kebutuhan daerah masing2.

3. Kemudian sediakan fitur yang memudahkan perubahan layout (pengaturan layout, semacam "page setup") tersebut pada surat cetak (yang tidak mempengaruhi template). Terutama mengubah margin dalam usaha memuat suatu surat tercetak ke dalam satu halaman

4. Sediakan fitur untuk mengembalikan suatu surat cetak ke layout standar

### Apakah ada alternatif lain

Seperti yg dilakukan sekarang, yg terbukti sulit dan menjadi sumber keluhan. 

### Untuk versi OpenSID mana

v23.08-premium

### Informasi tambahan

Gunakan layout standar tersebut pada semua surat bawaan. Dan gunakan untuk menguji tampilan setiap surat. Himpun contoh data ekstrim untuk surat2 yg sering dikeluhkan dan uji kemudahkan menggunakan pengaturan layout untuk menghasilkan tampilan cetak yg diinginkan. 

Fitur ini merupakan prioritas untuk diterapkan pada 2408, untuk mengatasi keluhan berkelanjutan atas sulitnya menyesuaikan surat hasil cetak fitur surat TinyMCE.

**Comment by eddieridwan** [comment]
Contoh peraturan Tata Naskah Dinas Pemerintah Desa terlampir dari Lombok Timur. Tampaknya bersifat per daerah, belum tentu global. Dan terlihat font dsbnya berbeda tergantung jenis surat. Misalnya lihat Pasal 12 dan Pasal 14. Meskipun naskah seperti itu masih menggunakan istilah lama seperti `pica`, masih dapat disari dan digunakan sebagai basis awal untuk spesikasi standar di surat Layanan dan surat Dinas. 

**Untuk lebih fleksibel, sediakan spesifikasi layout standar yg berbeda untuk surat layanan dan surat dinas.** 

[PERBUP Lombok Timur No 32 Tahun 2019.pdf](https://github.com/user-attachments/files/16115114/PERBUP.Lombok.Timur.No.32.Tahun.2019.pdf)

**Comment by luxmant354** [comment]
Untuk ukuran font saran kami default pakai pt bukan px pak

**Comment by eddieridwan** [comment]
Berikut contoh Perbup lain, dari Kab Mojokerto. Lihat Pasal 14. Spesifikasinya singkat saja. Pakai arial, ukuran huruf 12 `atau disesuaikan kebutuhan`. Berarti, spesikasi standar yg disediakan harus dapat diatur sendiri oleh pengguna sesuai kebutuhan mereka. Spesifikasi standar default yg disediakan bisa mengambil dari contoh2 itu, tapi harus bisa disesuaikan oleh desa.

[perbup 28 2022 ttg pedomanan tata naskah dinas di desa.pdf](https://github.com/user-attachments/files/16122263/perbup.28.2022.ttg.pedomanan.tata.naskah.dinas.di.desa.pdf)

**Comment by andifahruddinakas** [comment]
![image](https://github.com/OpenSID/OpenSID/assets/57283157/ecfbda5d-c51a-4bea-9777-33b4e602b3cc)
