### ISSUE TITLE
Bug/error: Isian (No KK dan nama Kepala keluarga) tidak ada di Penduduk Luar

### ISSUE THREAD

**Issue by ilhamwahyu-ni** [OpenSID/OpenSID#8166]
### Jelaskan error yg dialami

isian (No KK dan nama Kepala keluarga) tidak ada di Penduduk Luar dan jarak terlalu lebar,

serta isian alamat juga berlebih..

### Cara untuk mereplikasi errornya

Kembalikan ke surat master >> buat surat domisili >> input isian data penduduk luar

### Hasil yg diharapkan

normal

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/85351181/eacbce63-b11b-4227-a142-872629c2ff5a)

![image](https://github.com/OpenSID/OpenSID/assets/85351181/30a830a9-1ac8-4e0d-a2b6-ed587a468753)

![image](https://github.com/OpenSID/OpenSID/assets/85351181/ea6bd21a-1b21-41d7-ac90-e277b041122b)

lampiran

[surat-keterangan-domisili_2015741411519913_2024-07-06_25.pdf](https://github.com/user-attachments/files/16115106/surat-keterangan-domisili_2015741411519913_2024-07-06_25.pdf)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

 2407.0.0

**Comment by andifahruddinakas** [comment]
Untuk isian penduduk luar selain yang ada di kartu keluarga belum disediakan. terkait perbaikan template surat akan dilakukan secara menyeluruh melalui issue https://github.com/OpenSID/OpenSID/issues/8157

**Comment by ilhamwahyu-ni** [comment]
Baik mas..

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melalui pr https://github.com/OpenSID/premium/pull/3886
