### ISSUE TITLE
Bug/error: Saat klik rincian pada Laporan Hasil Klasifikasi pada Modul Analisis terjadi error

### ISSUE THREAD

**Issue by rockymakasar** [OpenSID/OpenSID#8167]
### Jelaskan error yg dialami

Saat kita membuat sebuah analisis lalu datanya diinput, lalu kita masuk pada Laporan hasil Klasifikasi dan ingin melihat rincian hasil klasifikasi namun terjadi error
![image](https://github.com/OpenSID/OpenSID/assets/94730877/73527a75-3139-49f8-a9d5-68719835e484)

![image](https://github.com/OpenSID/OpenSID/assets/94730877/2f3e9339-922b-40d3-9df9-c4699af0da0e)

![image](https://github.com/OpenSID/OpenSID/assets/94730877/0401e77f-8691-4d69-8150-4e17ad548909)

### Cara untuk mereplikasi errornya

1. Masuk Menu analisis
2. Klik Master Analisis
3. Pilih Salah satu Rincian analisis (misalnya AKP Lombok Tengah) pada https://berputar.opendesa.id/analisis_master/menu/2
4. Lalu Pilih Laporan Hasil Klasifikasi
5. Klik salah satu tombol rincian untuk melihat rincian
6. terjadi error

### Hasil yg diharapkan

Berjalan normal

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/94730877/d0efeab6-836a-44b9-9943-529c068a603f)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2407.0.0 premium

### Tema Yang Digunakan

-

### Informasi tambahan

-

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melalui pr https://github.com/OpenSID/premium/pull/3883
