### ISSUE TITLE
Bug/error: Tambah Data Manual Input Anggaran dan Realisasi APBDes tidak bisa

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8168]
### Jelaskan error yg dialami

Tambah Data Manual Input Anggaran dan Realisasi APBDes tidak bisa, data tidak bertambah dan tidak ada alert / pemberitahuan data tidak berhasil di tambah

### Cara untuk mereplikasi errornya

1. klik Modul Keuangan 
2. klik Menu Inpun Manual
3. Klik Tambah Data
4. Isi Data
5. Simpan

### Hasil yg diharapkan

Dapat menyimpan Tambah Data Manual Input Anggaran dan Realisasi APBDes

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/55429781/25bb2ecb-d551-4b0b-b653-dbdfa4bd71bd)
![image](https://github.com/OpenSID/OpenSID/assets/55429781/b8b2ad57-f8bc-4542-9702-02fccd82b920)
![image](https://github.com/OpenSID/OpenSID/assets/55429781/3ca9b5b2-146d-45d4-a9c0-ef8f5986ca1a)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Versi 2407.0.0-premium

**Comment by andifahruddinakas** [comment]
Terkait issue https://github.com/OpenSID/OpenSID/issues/8158
