### ISSUE TITLE
Bug/error: 403 saat delete laporan APBDES

### ISSUE THREAD

**Issue by ilhamwahyu-ni** [OpenSID/OpenSID#8169]
### Jelaskan error yg dialami

![image](https://github.com/OpenSID/OpenSID/assets/85351181/a26a4c73-36e7-4cc3-b465-0ae6a740ea8e)

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

normal

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/85351181/22be397e-4434-4936-ba81-a2d2ac802ad5)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

 2407.0.0

### Informasi tambahan

terjadi hal yang sama di berputar.

**Comment by andifahruddinakas** [comment]
Ini terkait csrf, sudah disesuaikan melalui issue https://github.com/OpenSID/OpenSID/issues/8158
