### ISSUE TITLE
Bug: nama berisi petik (') tidak muncul di surat keterangan izin orang tua/suami/istri

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#817]
ketika nama yang memberikan izin terdapat tanda petik (') maka nama yang diberi izin  tdk muncul seperti contoh yang memberi Izin MAS'ARIAH selaku istri maka nama suami yang diberi izin tidak muncul. Maslah ini hanya terdapat pada NAMA yang ada tanda Petik (')
![36652586-9dc63de2-1aea-11e8-86b4-81196faa9eb0](https://user-images.githubusercontent.com/25834335/36652721-6a523ef6-1aeb-11e8-835c-1d44e4c96876.png)

Mohon di bantu para programer

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
