### ISSUE TITLE
Bug/error: Data penerima izin Kosong (fieldnya tidak ada) di Surat Keterangan Izin Orang Tua Suami Istri

### ISSUE THREAD

**Issue by ilhamwahyu-ni** [OpenSID/OpenSID#8170]
### Jelaskan error yg dialami

Data penerima izin Kosong di Surat Keterangan Izin Orang Tua Suami Istri

### Cara untuk mereplikasi errornya

kembalikan surat ke default master..

![image](https://github.com/OpenSID/OpenSID/assets/85351181/2dc1c8a8-9f0b-4696-b79c-6d76e2215133)

### Hasil yg diharapkan

normal

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/85351181/068aa2bc-511c-48f6-b496-0e127944b7b5)

==================
lampiran.
[surat-keterangan-izin-orang-tua-suami-istri_5201141003666996_2024-07-07_1.pdf](https://github.com/user-attachments/files/16118619/surat-keterangan-izin-orang-tua-suami-istri_5201141003666996_2024-07-07_1.pdf)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

 2407.0.0

**Comment by andifahruddinakas** [comment]
pak @ilhamwahyu-ni, sy cek diberputar aman.

![image](https://github.com/OpenSID/OpenSID/assets/57283157/187fae16-e135-400d-abb6-75cdab6d7812)

hasil
![image](https://github.com/OpenSID/OpenSID/assets/57283157/503bca75-5355-4553-9ffb-2143cdb054c8)

**Comment by andifahruddinakas** [comment]
Dari yang terlihat, pada bagian formnya tidak ada pilihan penduduk.
![image](https://github.com/OpenSID/OpenSID/assets/57283157/01696558-68e6-49d3-9cf8-695458f15f1f)
harusnya seperti ini
![image](https://github.com/OpenSID/OpenSID/assets/57283157/da313858-3886-4ccc-8284-ba1e803febbd)

**Comment by ilhamwahyu-ni** [comment]
Baik mas, klw boleh tahu..
Izin..

Kapan waktu reset di berputar ya??

Padahal isu itu, saya sudah kembalikan surat de default masternya,

Kemumgukinan setelah saya kebalikan ke master .....

waktu resetnya aktif.. 

Dan saya membuat surat kembali ke sebelum surat dafault masternya..🙏🏻🙏🏻🙏🏻
