### ISSUE TITLE
Bug/error: SURAT KETERANGAN JAMKESOS, jarak dan penulisan Pendidikan tidak sesuai

### ISSUE THREAD

**Issue by ilhamwahyu-ni** [OpenSID/OpenSID#8171]
### Jelaskan error yg dialami

SURAT KETERANGAN JAMKESOS, jarak atas bawah (pendidikan dan pekerjaan) rapat dan penulisan Pendidikan tidak sesuai

### Cara untuk mereplikasi errornya

kembalikan surat ke default master >> buat surat >> isi data

### Hasil yg diharapkan

normal

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/85351181/c09ec16e-bf52-475c-8e3d-5c0bd48709c4)

===========

lampiran
[surat-keterangan-jamkesos_5201141003666996_2024-07-07_19.pdf](https://github.com/user-attachments/files/16118640/surat-keterangan-jamkesos_5201141003666996_2024-07-07_19.pdf)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

 2407.0.0

**Comment by ilhamwahyu-ni** [comment]
jarak atas bawah juga terjadi di : SURAT KETERANGAN PENGHASILAN IBU

lampiran..

[surat-keterangan-penghasilan-ibu_5201141412121724_2024-07-07_1.pdf](https://github.com/user-attachments/files/16118663/surat-keterangan-penghasilan-ibu_5201141412121724_2024-07-07_1.pdf)

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melalui pr https://github.com/OpenSID/premium/pull/3884
