### ISSUE TITLE
Bug/error: cetak surat keterangan nikah, lembar lampiran n1-n5 tidak tampil

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8172]
### Jelaskan error yg dialami

lampiran n5 pengatin pria tidak tampil di surat keterangan nikah, yang tampil saat ini n5 penganti wanita

### Cara untuk mereplikasi errornya

1. Klik cetak surat keterangan nikah
2. Klik Tinjau Surat
3. cek lampiran n5, tidak terlampir lembar N5 untuk pengantin pria

### Hasil yg diharapkan

dapat melampirkan lembar n5 untuk pengantin pria 

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/55429781/8c4989b2-9202-4e92-8158-b6028d51e652)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

 OpenSID 2407.0.0-premium

**Comment by andifahruddinakas** [comment]
Surat nikah lama
https://github.com/OpenSID/OpenSID/blob/v2404.0.0/template-surat/surat_ket_nikah/surat_ket_nikah.rtf

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melalui pr https://github.com/OpenSID/premium/pull/3891
