### ISSUE TITLE
Bug/error: gagal simpan perubahan input data realisasi-keuangan

### ISSUE THREAD

**Issue by mah-mudi** [OpenSID/OpenSID#8175]
### Jelaskan error yg dialami

gagal simpan perubahan input data realisasi-keuangan

### Cara untuk mereplikasi errornya

1. keuangan
2. input data
3. masukkan angka realisasi
4. simpan
5. data tidak berubah

### Hasil yg diharapkan

input data keuangan dapat berubah

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/57661283/ae9b572e-7134-4482-b491-a7044a5024b8)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

24.07 premium

### Tema Yang Digunakan

silir

### Informasi tambahan

-

**Comment by andifahruddinakas** [comment]
pada branch bug-fix sudah tidak bermasalah.
![image](https://github.com/OpenSID/OpenSID/assets/57283157/c197e7b4-be28-4033-8217-535e992a475b)

![image](https://github.com/OpenSID/OpenSID/assets/57283157/26767214-5133-476f-a9f8-c8f8c1706e62)
