### ISSUE TITLE
Bug/error: Field Pendidikan Kosong >> Tambah Data Suplemen

### ISSUE THREAD

**Issue by ilhamwahyu-ni** [OpenSID/OpenSID#8177]
### Jelaskan error yg dialami

Pendidikan warga tidak tampil saat memilih warga

### Cara untuk mereplikasi errornya

![image](https://github.com/OpenSID/OpenSID/assets/85351181/39882f51-970f-41a4-8c70-60d3493ddf8e)

### Hasil yg diharapkan

normal

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/85351181/9340ce54-2429-4c46-97d7-9ae0b30526a2)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

 2407.0.0

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melalui pr https://github.com/OpenSID/premium/pull/3892
