### ISSUE TITLE
Bug/error: Pesan eror tidak rapi dan mepet

### ISSUE THREAD

**Issue by ilhamwahyu-ni** [OpenSID/OpenSID#8178]
### Jelaskan error yg dialami

Pesan eror tidak rapi dan mepet..

saya pakai resolusi leptop seperi ini..
SS

![image](https://github.com/OpenSID/OpenSID/assets/85351181/f53c5712-47b4-4a71-9bff-a6264a876758)

### Cara untuk mereplikasi errornya

![image](https://github.com/OpenSID/OpenSID/assets/85351181/9dde8d4b-17ae-41dd-8ca8-d697db11bb1f)

### Hasil yg diharapkan

normal

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/85351181/fd4cf13a-c867-4d4c-bed3-651188b8594a)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

 2407.0.0

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melalui pr https://github.com/OpenSID/premium/pull/3894
