### ISSUE TITLE
Permintaan fitur: tambahkan filter penduduk yang belum memiliki no kk di menu penduduk

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8180]
### Apa kekurangan yg ingin diatasi?

pada menu penduduk belum ada filter penduduk yang belum memiliki no kk

### Jelaskan solusi yg diinginkan

tambahkan filter penduduk yang belum memiliki no kk di menu penduduk, untuk membantu mempercepat menemukan penduduk yang belum memiliki no kk

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

OpenSID 2408.0.0-premium

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/3905
