### ISSUE TITLE
Bug/error: Muncul error ketika ingin menampilkan semua entri penduduk di menu Kependudukan > Penduduk

### ISSUE THREAD

**Issue by bagusmahendra85** [OpenSID/OpenSID#8181]
### Jelaskan error yg dialami

Muncul error ketika akan menampilkan semua entri penduduk di menu Kependudukan > Penduduk

### Cara untuk mereplikasi errornya

1. Pergi ke menu Kependudukan
2. Mengklik submenu Penduduk
3. Merubah tampilan list penduduk dari 10 ke "Semua"
4. Muncul pesan "Sedang Memproses"
5. ~5 detik kemudian muncul error berikut
![photo_2024-07-11_12-18-27](https://github.com/OpenSID/OpenSID/assets/99731198/8f62f0fd-1d15-4ff3-bd31-5347c44d8447)

### Hasil yg diharapkan

Bisa menampilkan list semua penduduk, yang akan saya unduh, atau bisa ditambahkan button untuk mengunduh semua penduduk tanpa harus merubah jumlah list pagination terlebih dahulu.

Menu untuk mengunduh semua penduduk juga boleh, nanti ditampilkan filternya (dusun, umur, jenis kelamin, dll) dan kemudian di unduh

### Tangkapan layar dan log error

![photo_2024-07-11_12-18-27](https://github.com/OpenSID/OpenSID/assets/99731198/84328211-260f-4005-8bd1-016479f824a2)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

 Versi 2407.0.0-premium 

### Tema Yang Digunakan

Silir

**Comment by rgrahardi** [comment]
pak @bagusmahendra85 apakah bisa bergabung di sesi Klinik Bug agar kita replikasi bersama terkait issue ini ?

**Comment by bagusmahendra85** [comment]
mohon maaf saya baru cek, baik saya akan join sesi klinik bug hari ini di sesi ketiga

**Comment by bagusmahendra85** [comment]
sudah solved dengan sendirinya, terimakasih min supportnya
