### ISSUE TITLE
Bug/error: Gelar Double saat Cetak dan Unduh

### ISSUE THREAD

**Issue by ilhamwahyu-ni** [OpenSID/OpenSID#8183]
### Jelaskan error yg dialami

Gelar Double saat Cetak dan Unduh Wilayah administrasi

### Cara untuk mereplikasi errornya

![image](https://github.com/OpenSID/OpenSID/assets/85351181/e10443a4-4c9d-47cb-9f89-b7142b38133d)

### Hasil yg diharapkan

normal

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/85351181/f63243d7-807a-4abb-a252-613df874027d)

![image](https://github.com/OpenSID/OpenSID/assets/85351181/69ae570f-1f14-4c40-9be0-c60515451030)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

 2407.0.1

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melalui pr https://github.com/OpenSID/premium/pull/3899
