### ISSUE TITLE
Bug/error: "Maksud dan Tujuan Kedatangan" pada biodata Penduduk "Tidak Tetap" tidak tersimpan

### ISSUE THREAD

**Issue by ilhamwahyu-ni** [OpenSID/OpenSID#8184]
### Jelaskan error yg dialami

"Maksud dan Tujuan Kedatangan" pada biodata Penduduk "Tidak Tetap" tidak tersimpan

### Cara untuk mereplikasi errornya

![image](https://github.com/OpenSID/OpenSID/assets/85351181/4e8a9438-e7ba-4462-9b12-d7fe0a1c1ea9)

![image](https://github.com/OpenSID/OpenSID/assets/85351181/54f3142e-fc47-4cdb-8e86-2b05904a8a12)

![image](https://github.com/OpenSID/OpenSID/assets/85351181/42660ec6-8d9f-48c5-acae-0a1c61cc96de)

### Hasil yg diharapkan

normal

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/85351181/b26cb88e-0041-424d-9da6-ed9d2f71feef)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

 2407.0.1

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melalui pr https://github.com/OpenSID/premium/pull/3903
