### ISSUE TITLE
[pertemuan] Preview Dokumen Halaman Web

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#8185]
tidak dapat menampilkan preview pdf (harus login terlebih dahulu), padahal publik

![image](https://github.com/OpenSID/OpenSID/assets/57283157/9637c729-edfd-4fa1-94fc-b335c6703ee1)

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melalui pr https://github.com/OpenSID/premium/pull/3900
