### ISSUE TITLE
Bug/error: Deklarasi ganda fungsi `kodePeristiwaAll()` di `App/Models/LogKeluarga.php`

### ISSUE THREAD

**Issue by lc-at** [OpenSID/OpenSID#8186]
### Jelaskan error yg dialami

Terdapat deklarasi ganda fungsi `kodePeristiwaAll()` di `App/Models/LogKeluarga.php` yang mengakibatkan error ketika menjalankan migrasi (mungkin saja error di tempat lain juga, namun belum dites).

https://github.com/OpenSID/OpenSID/blob/9e18b614c201f46c38a2a5dae157f53fbcb2408c/app/Models/LogKeluarga.php#L99-L134

### Cara untuk mereplikasi errornya

Install versi 2407.0.0, harusnya akan gagal ketika sampai di tahap menjalankan migrasi, dan instalasi jadi broken

### Hasil yg diharapkan

Seharusnya migrasi berhasil dijalankan (respon 200) dan OpenSID berhasil terinstall sempurna.

### Tangkapan layar dan log error

![image](https://github.com/OpenSID/OpenSID/assets/30001379/540dd973-e469-4119-aa1a-225152438972)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v2307.0.0

### Tema Yang Digunakan

N/A

### Informasi tambahan

Workaround sementara menunggu patch adalah dengan menghapus salah satu dari dua deklarasi ganda fungsi `kodePeristiwaAll()` di dalam file `App/Models/LogKeluarga.php`. Terima kasih @rhazesw sudah mengidentifikasi bug ini di awal.

**Comment by andifahruddinakas** [comment]
Sudah di sesuaikan melalui commit https://github.com/OpenSID/OpenSID/commit/8b0eb975e78b2eb8484651f3cf6858746699b826 karena kesalahan penggabungan
