### ISSUE TITLE
Bug: View dan Cetak Kartu Rumah Tangga Alamat Kosong

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#819]
Pada View dan Cetak Kartu Rumah Tangga Alamat Kosong
![screenshot 2018-02-26 23 02 15](https://user-images.githubusercontent.com/25834335/36677703-d514d092-1b49-11e8-9071-ed26d31c42c3.png)
![screenshot 2018-02-26 23 03 20](https://user-images.githubusercontent.com/25834335/36677725-e4e753b4-1b49-11e8-94e2-77df0c637a62.png)

**Comment by ombimo** [comment]
sudah ada di PR om

**Comment by eddieridwan** [comment]
Sudah digabung melalui PR #839.

@ombimo : Terima kasih. Issue dan PR-nya sebaiknya ada linknya. Bisa tambahkan #819 di judul PR, atau tambahkan #839 di comment issue ini.
