### ISSUE TITLE
Bug/error: Size Font edit surat  ( tidak sama) "pt" && "px"

### ISSUE THREAD

**Issue by ilhamwahyu-ni** [OpenSID/OpenSID#8190]
### Jelaskan error yg dialami

ketika edit surat dilakukan size font ada yang pt ada yang px, jadi ragu size ukuran yang seharusnya, 

klw orang awam mungkin sulit mebedakannya..

### Cara untuk mereplikasi errornya

![image](https://github.com/user-attachments/assets/3d71c198-a781-482b-a8e4-2db6897e9444)

![image](https://github.com/user-attachments/assets/2b245d53-1432-408c-8369-b80cbd45dc2f)

>> simpan

### Hasil yg diharapkan

seragamkan saja ukuran font, biar tidak ambigu..

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/7d7e8fc5-30cd-4ffb-9d8e-8d8ec8cbeb05)

![image](https://github.com/user-attachments/assets/9be211f6-b041-4434-aeab-d23f833d750f)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

 2407.0.1

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melalui pr https://github.com/OpenSID/premium/pull/3908
