### ISSUE TITLE
Bug/error: Lampiran F-1.01 surat-permohonan-perubahan-kartu-keluarga "Alamat Kosong"

### ISSUE THREAD

**Issue by ilhamwahyu-ni** [OpenSID/OpenSID#8191]
### Jelaskan error yg dialami

Lampiran F-1.01 surat-permohonan-perubahan-kartu-keluarga "Alamat Kosong"

### Cara untuk mereplikasi errornya

cetak surat >> surat-permohonan-perubahan-kartu-keluarga 

### Hasil yg diharapkan

normal

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/238e81d0-baa6-495d-a169-2d7d58d584e9)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

 2407.0.1

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melalui pr https://github.com/OpenSID/premium/pull/3906
