### ISSUE TITLE
Gagal Lakukan Pencarian TagIdCard

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#8192]
Saat melakukan pencarian spesifik pada data tag_id_card, data yg ditampilkan tidak sesuai.

Pencarian
![image](https://github.com/user-attachments/assets/267ac5f2-e867-4c95-ac06-a95111d4ac87)

Hasil
![image](https://github.com/user-attachments/assets/4a93e033-0dec-4045-a6d4-f5c26c32d3b8)

Data Tersedia
![image](https://github.com/user-attachments/assets/d7f4af83-29d9-4b2f-866b-e36a98c35654)

Cek modul:
- Penduduk
- Dpt

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melalui pr https://github.com/OpenSID/premium/pull/3904
