### ISSUE TITLE
Bug/error: Kolom aksi pada daftar arsip surat di Layanan mandiri tidak diperlukan

### ISSUE THREAD

**Issue by ilhamwahyu-ni** [OpenSID/OpenSID#8195]
### Jelaskan error yg dialami

Kolom aksi pada daftar arsip surat di Layanan mandiri tidak diperlukan

### Cara untuk mereplikasi errornya

login layanan mandiri >> lihat arsip surat yang pernah dibuat >> ada kolom aksi

### Hasil yg diharapkan

hapus saja kolomnya

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/f9ed78d6-d291-4e4b-93d0-59025ac67ee6)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

 2407.0.1

**Comment by andifahruddinakas** [comment]
pak @ilhamwahyu-ni, kolom tersebu diperlukan untuk unduh surat yg bentuk .pdf (menggunakan tte). mungkin yg perlu dilakukan yakni menghilangkan kolom tersbut jika tidak menggunakan tte.

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melalui pr https://github.com/OpenSID/premium/pull/3910
