### ISSUE TITLE
Gagal periksa permohonan surat

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#8196]
Saat periksa permohonan surat dengan template format nomor suratnya manual tp isiannya kosong akan terjadi error.

error
`ERROR - 2024-07-14 11:30:34 --> Severity: error --> Exception: Unsupported operand types: string + int D:\PROJECT OPENDESA\OpenSID\app\Models\LogSurat.php 393
`
no surat terakhir isinya string kosong.
![image](https://github.com/user-attachments/assets/e4281404-1fe5-462c-9d59-910b48fabfa9)

jika dilihat juga, pengaturan suratnya:
![WhatsApp Image 2024-07-14 at 12 02 19_08fa1c96](https://github.com/user-attachments/assets/a3325f2c-848d-46d3-affb-619b835d738e)

database terlampir

**Comment by andifahruddinakas** [comment]
ini pak @roaddee

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melalui pr https://github.com/OpenSID/premium/pull/3909
