### ISSUE TITLE
Bug/error: backup folder desa hasil 0 kb 

### ISSUE THREAD

**Issue by Wiliyantoro** [OpenSID/OpenSID#8197]
### Jelaskan error yg dialami

saat ingin melakukan backup foler desa dimana size folder > 1 GB hasil output 0 kb 

### Cara untuk mereplikasi errornya

home -> pengaturan -> database -> unduhfolder desa
hasil donwload 0 kb

### Hasil yg diharapkan

bisa melakukan backup folder

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/4aa5be2f-40ec-436a-a3fa-445a4b336063)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

OpenSID Siap Pakai Diskominfo Tabanan

### Informasi tambahan

Backup Incremental juga mohon diperbaiki

**Comment by andifahruddinakas** [comment]
mas @Wiliyantoro, @rgrahardi, sy coba replikasi dilocal aman dengan data 1 gb. mungkin bisa bantu replikasi untuk issue in.

**Comment by Wiliyantoro** [comment]
> mas @Wiliyantoro, @rgrahardi, sy coba replikasi dilocal aman dengan data 1 gb. mungkin bisa bantu replikasi untuk issue in.

mohon maaf pak, sata tidak bisa replikasi pada localhost karna data desanya ada di dashboard siap pakai diskominfo tabanan

**Comment by scqolbu24** [comment]
Terkonfirmasi BUG mas @andifahruddinakas 
![image](https://github.com/user-attachments/assets/50fd9c1a-557c-4f41-a81e-105766ae481b)

**Comment by andifahruddinakas** [comment]
Informasi tambahan:
- terkait database gabungan
- terkait siappakai
