### ISSUE TITLE
PERBAIKAN INTEGRASI BDT VERSI BIMA

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#820]
Pada waktu impor Data BDT yang Kepala Rumah Tangganya tidak ada NIK 0 (kosong) di Data BDT tetapi Anggota keluarganya ada didatabase penduduk, Tampilan di Kolom Kepala Rumah Tangga, Dusun, RW, RT Kosong
 
![image](https://user-images.githubusercontent.com/25834335/36679565-7a9666f8-1b4e-11e8-836b-0617a1f776fc.png)

Setelah dicek didatabase penduduk ternya Kepala Rumah Tangga tersebut sudah ada dengan kita cek melalui ANggota Keluarga dengan klik Rincian dan copy paste nik anggota tersebut dan nama kepala Rumah Tangga teernyata ada didatabase penduduk
![image](https://user-images.githubusercontent.com/25834335/36679575-81e76240-1b4e-11e8-89a0-f59c54d458b4.png)
 
Setelah itu Tambah Anggota baru yang sekaligus hubungannya kita jadikan sebagai Kepala Rumah Tangga 
![image](https://user-images.githubusercontent.com/25834335/36679593-89d65704-1b4e-11e8-8e68-6d77543e7727.png)
![image](https://user-images.githubusercontent.com/25834335/36679609-938be84a-1b4e-11e8-93b3-dc1c5abafbc8.png)
![image](https://user-images.githubusercontent.com/25834335/36679645-b17637ca-1b4e-11e8-86b3-3e4facc74059.png)
![image](https://user-images.githubusercontent.com/25834335/36679650-b377bbc0-1b4e-11e8-9f7a-8fcc6af227db.png)
  
SEHARUSNYA NAMA KEPALA RUMAH TANGGA yang sudah ditambahkan tersebut muncul di INPUT DATA SENSUS/ SURVEY tetapi sekarang BLANK/ KOSONG
![image](https://user-images.githubusercontent.com/25834335/36679662-badaaf8a-1b4e-11e8-9144-a59afe6ce7b1.png)

SELANJUTNYA JUGA ICON DIPERLU PERBAIKI SUPAYA TDK MUNCUL SEPERTI
 ![image](https://user-images.githubusercontent.com/25834335/36679670-c2310068-1b4e-11e8-8996-4c448d33af11.png)

**Comment by eddieridwan** [comment]
Masalah icon yg hilang sudah diperbaiki dan sudah dicommit ke master. Ada di pra-rilis.

**Comment by eddieridwan** [comment]
@MUHAMMADRANGSEL : apakah yg anda usulkan di sini untuk mencari Kepala Rumah Tangga (yg kosong) secara otomatis? Apakah Kepala Keluarga anggota yg ada selalu bisa digunakan sebagai Kepala Rumah Tangga?

Bagaimana dengan kasus di mana ada anggota rumah tangga datang dari dua kartu keluarga yang berbeda (Rumah Tangga bisa beranggotakan beberapa keluarga)? Kepala keluarga mana yang akan dipilih sebagai kepala rumah tangga? Mungkin lebih aman apabila pelengkapan ini dilakukan secara manual.

Yang mungkin dapat dipikirkan adalah: fitur apa yang dapat membantu untuk memudahkan proses pelengkapan manual ini....

**Comment by MUHAMMADRANGSEL** [comment]
Yang saya usulkan ketika kita sudah menambahkan Kepala Rumah Tangga melalui rincian tambahan anggota keluarga maka di Input data sensus/survey nama yang SDH kita tambah itu yg sekaligus menjadi kepala rumah tangga muncul mas Eddie

**Comment by eddieridwan** [comment]
Ok, sudah diperbaiki dan dicommit ke master. Ada di versi pra-rilis.
