### ISSUE TITLE
Permintaan fitur: tambah kode isian yang bisa menunjukkan "nama hari ini"  sesuai kalender berjalan saat surat dibuat

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8202]
### Apa kekurangan yg ingin diatasi?

tambah kode isian yang bisa menunjukkan "nama hari ini"  sesuai kalender berjalan saat surat dibuat

![image](https://github.com/user-attachments/assets/932572ea-bb08-45b2-b99e-afbb8625c552)

### Jelaskan solusi yg diinginkan

terdapat kode isian nama hari ini pada surat

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

Versi 2408.0.0-premium

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/3913
