### ISSUE TITLE
Bug/error: Menu Info nagari Sering hilang

### ISSUE THREAD

**Issue by ilhamwahyu-ni** [OpenSID/OpenSID#8206]
### Jelaskan error yg dialami

ini Tejadi 2 bulan terakhir, sering kehilangan menu Info nagari

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

normal

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/b8418f6d-fcbc-43bd-8b04-2d7d1fbeab0b)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

 2407.0.1

### Informasi tambahan

![image](https://github.com/user-attachments/assets/4474e643-6825-446f-9028-5f7b357d53cb)

cara atasi sementara >> migrasi semua database.

tetapi ketika sudah agak beberapa hari info nagari akan hilang kembali..

kan capek juga harus selalu migrasi database setiap saat

**Comment by andifahruddinakas** [comment]
mas @ilhamwahyu-ni,  untuk kasus seperti ini untuk deteksi/replikasi masalah ini agak susah karena spesifik pada desanya dan tergantung waktunya jg (harus menunggu pada waktu N). Karena aktiftas masing2 user beda2.

**Comment by eddieridwan** [comment]
@andifahruddinakas apakah sudah dipertimbangkan disebabkan oleh cache modul? Yg ada pemicunya dikembalikan. Gejalanya indikasi adanya pengembalian cache.

**Comment by andifahruddinakas** [comment]
> @andifahruddinakas apakah sudah dipertimbangkan disebabkan oleh cache modul? Yg ada pemicunya dikembalikan. Gejalanya indikasi adanya pengembalian cache.

untuk cache akan mengambil data status modul terbaru jika tidak ada cache yg ditemukan (buka data lama).

**Comment by eddieridwan** [comment]
@andifahruddinakas maksudnya skenario seperti berikut:

1. hilangkan menu info nagari
2. pastikan info modul di-cache dengan kondisi tidak ada info nagari (yaitu status cache modul tidak ada info nagari)
4. jalankan migrasi semua database, supaya info nagari kembali

Apakah cache modul diperbaharui, atau masih berisi kondisi tidak ada info nagari?

Apakah ada event yg secara otomatis mengambil dan restore dari cache modul tersimpan tsb (yg tidak ada info nagarinya)?

**Comment by rgrahardi** [comment]
pak @ilhamwahyu-ni apakah bisa bergabung di sesi Klinik Bug agar kita replikasi bersama terkait issue ini ?

**Comment by rgrahardi** [comment]
setelah di konfirmasi ke Pak Ilham di telegram, issue di tutup Karna versi terbaru ini tidak terjadi lagi
