### ISSUE TITLE
Sesuaikan semua penerapan status kawin tercatat

### ISSUE THREAD

**Issue by mranca** [OpenSID/OpenSID#8207]
### Jelaskan error yg dialami

saat unduh kartu keluarga hanya kawin saja seharunya mengikuti yang di tampilkan yaitu kawin tercacat

### Cara untuk mereplikasi errornya

1. masuk admin
2. klik kartu keluarga
3. klik salah satu kartu keluarga
4. klik unduh 

### Hasil yg diharapkan

Seharunya tampil seperti di bawa
![image](https://github.com/user-attachments/assets/9ac97e8f-0d88-4631-bff3-1b1f6747b3ea)

### Tangkapan layar dan log error
hasil unduh kk
![image](https://github.com/user-attachments/assets/1df53dd9-b046-48d3-bdfc-1ef5bcb145f4)
sedangkan yang tampil pada kartu keluarga
![image](https://github.com/user-attachments/assets/2d4c3523-f3cc-4f33-8956-a6543bdbe6e7)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

terbaru

### Tema Yang Digunakan

.

### Informasi tambahan

.

**Comment by andifahruddinakas** [comment]
mas @mranca, sudah sesuai.
![image](https://github.com/user-attachments/assets/ee85f31f-b882-449f-a48d-f0f733eadae4)

Duplicate of https://github.com/OpenSID/OpenSID/issues/8124

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melalui pr https://github.com/OpenSID/premium/pull/3926

**Comment by mranca** [comment]
Oke

**Comment by mranca** [comment]
@andifahruddinakas maksudnya saya kalau kknya di donwload bung hanya tertulis kawin saja
