### ISSUE TITLE
tidak bisa cetak surat

### ISSUE THREAD

**Issue by mranca** [OpenSID/OpenSID#8209]
### Jelaskan error yg dialami

saat cetak surat tidak di conversi ke pdf 

### Cara untuk mereplikasi errornya

1. masuk admin
2. klik layanan surat
3. klik dan buat salah satu surat
4. cetak pdf

### Hasil yg diharapkan

semua hasil surat seharusnya jadi pdf

### Tangkapan layar dan log error

hasilnya seperti ini
![image](https://github.com/user-attachments/assets/714ef285-30d3-42b2-bdb2-2d0abf7a45f6)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

terbaru

### Tema Yang Digunakan

.

### Informasi tambahan

.

**Comment by andifahruddinakas** [comment]
mas @mranca, bisa kirim template yg digunakan.

**Comment by mranca** [comment]
[template_surat_tinymce_17_07_2024.json](https://github.com/user-attachments/files/16258364/template_surat_tinymce_17_07_2024.json)
@andifahruddinakas

**Comment by andifahruddinakas** [comment]
mas @mranca, setelah diperiksa templatenya. errornya karena ada penggunaan font yg tidak ada. Jika menambahkan memang sudah menambahkan font, bisa tambahkan lewat editornya (tidak diketik manual). Jika melakukan restore template dari desa lain, bisa cek terlebih dahulu templatenya lewat preview template untuk memastikan template tsb bisa digunakan.

Ada penggunaan Font TIme New Rowman
![image](https://github.com/user-attachments/assets/a0570226-c866-49cc-8861-2281456d407f)

**Comment by mranca** [comment]
@andifahruddinakas oke done
