### ISSUE TITLE
Log penduduk dibuatkan menu cetak

### ISSUE THREAD

**Issue by Cakwidod** [OpenSID/OpenSID#821]
di log penduduk dibuatkan log cetak atau unduh....

**Comment by hansahdarmawan** [comment]
baik

**Comment by hansahdarmawan** [comment]
apakah report / unduh formatnya di samakan dengan format kependudukan?? @Cakwidod

**Comment by MUHAMMADRANGSEL** [comment]
Ya disamakan

**Comment by eddieridwan** [comment]
@MUHAMMADRANGSEL bukannya disamakan dengan tampilan Log Penduduk? Supaya terlihat kolom2 seperti Tanggal Peristiwa dan Catatan Peristiwa?

**Comment by MUHAMMADRANGSEL** [comment]
Betul sekali mas Eddie sorry salah tangkap

Pada tanggal Kam, 26 Apr 2018 19.38, Eddie Ridwan <notifications@github.com>
menulis:

**Comment by eddieridwan** [comment]
Ok, @hansahdarmawan sepertinya issue ini sekarang sudah bisa dikerjakan. Format laporan cetak/unduh disamakan dengan halaman _Log Penduduk_. 

Ikuti contoh method `cetak()` dan `excel()` di `controllers/Dpt.php`, di mana hanya ada satu file berisi laporannya (`views/dpt/dpt_print.php`). File `views/dpt/dpt_excel.php` hanya membuat file tersebut terunduh sebagai excel.

Silakan perbaiki PR anda #952.

**Comment by hansahdarmawan** [comment]
Okee baik

**Comment by eddieridwan** [comment]
PR #952 tidak diteruskan.
Sudah dikerjakan terpisah dan sekarang sudah dicommit ke master.
