### ISSUE TITLE
Tidak dapat cetak/unduh buku KTP dan KK

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#8211]
Terjadi error saat melakukan cetak/unduh buku KTP dan KK.

Dengan error sbb:
`ERROR - 2024-07-17 10:59:53 --> Severity: error --> Exception: Bumindes_penduduk_ktpkk::{closure}(): Return value must be of type array, App\Models\Penduduk returned D:\PROJECT OPENDESA\OpenSID\donjo-app\controllers\Bumindes_penduduk_ktpkk.php 157
`

**Comment by mranca** [comment]
![image](https://github.com/user-attachments/assets/76a89786-bbfa-4a02-b331-d1e32617a12a)
hasil donwlod niknya tampil seperti di  gambar 
@andifahruddinakas

**Comment by andifahruddinakas** [comment]
> ![image](https://private-user-images.githubusercontent.com/76085245/349761692-76a89786-bbfa-4a02-b331-d1e32617a12a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyNzMxODAsIm5iZiI6MTcyMTI3Mjg4MCwicGF0aCI6Ii83NjA4NTI0NS8zNDk3NjE2OTItNzZhODk3ODYtYmJmYS00YTAyLWIzMzEtZDFlMzI2MTdhMTJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE4VDAzMjEyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmN2MxMzNiZTEwZDQ2NzMxYTg4YjZkMjhhZDYzMTc3Y2E1NjAyYzkyZmEwZDMyMjcyYWUwNGU3ZTQ0Y2U0NWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZpuZUSgFF3lJv-4OsiJaboxbVXycd4wADXnpJNTALBM) hasil donwlod niknya tampil seperti di gambar @andifahruddinakas

bisa buatkan permintaan untuk sensor data tsb, sama seperti modul penduduk.
