### ISSUE TITLE
surat tercetak ganda 

### ISSUE THREAD

**Issue by mranca** [OpenSID/OpenSID#8212]
### Jelaskan error yg dialami

saat cetak surat terkadang doubel pada arsip layanan surat

### Cara untuk mereplikasi errornya

1. masuk admin
2. klik layanan surat
3. cetak surat
4. cek di bagian arsip surat

### Hasil yg diharapkan

.

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/730c17f1-78cc-4dc1-93c0-89194381fff8)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

terbaru

### Tema Yang Digunakan

.

### Informasi tambahan

.

**Comment by andifahruddinakas** [comment]
mas @mranca, coba replikasi issue ini tp hasilnya normal.

**Comment by rgrahardi** [comment]
pak @mranca apakah bisa bergabung di sesi Klinik Bug agar kita replikasi bersama terkait issue ini ?

**Comment by mranca** [comment]
@rgrahardi saya lagi di luar pak ada kerjaan,

**Comment by mranca** [comment]
Saya close saja issue ini kalau yang lain sudah normal
