### ISSUE TITLE
Bug/error: ada " ;; " pada cetak KK

### ISSUE THREAD

**Issue by ilhamwahyu-ni** [OpenSID/OpenSID#8215]
### Jelaskan error yg dialami

-

### Cara untuk mereplikasi errornya

cetak dan unduk kk

### Hasil yg diharapkan

normal

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/ad06c9fd-769c-4714-bfbf-73f9e863bef5)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

 2407.0.2

**Comment by andifahruddinakas** [comment]
Selesai melalui commit https://github.com/OpenSID/premium/commit/cea3db6cab1dc8a96239a6a4614f40910408a9c1
