### ISSUE TITLE
Konversi Statistik Penduduk Kategori Keluarga menggunakan ORM dan Blade

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#8219]
![image](https://github.com/user-attachments/assets/760e923d-aaf2-45d0-9926-7e1dac211b3f)

catatan : 
- [ ] hapus query lama
- [ ] hapus view lama dan gunakan blade (gunakan komponen blade; @if, @forrech, @select, dll)
- [ ] pindahkan ke controller baru agar tidak bengkak
- [ ] sesuaikan router jika ada perubahan
- [ ] gunakan button non flat, untuk membedakan dengan modul yg sudah dikonversi
- [ ] sesuaikan kondisi terkait tte
- [ ] sederhanakan proses/fungsi yang rumit
- [ ] gunakan pengecekan hak akses yang baru

**Comment by agungsugiarto** [comment]
mas @andifahruddinakas konversi ini tidak hanya untuk `Penduduk Kategori Keluarga` tapi keseluruhan terkait viewnya agar tidak konflik dengan yg dikerjakan mas @habibie11 bisa menunggu yg saya kerjakan dulu.

**Comment by habibie11** [comment]
> mas @andifahruddinakas konversi ini tidak hanya untuk `Penduduk Kategori Keluarga` tapi keseluruhan terkait viewnya agar tidak konflik dengan yg dikerjakan mas @habibie11 bisa menunggu yg saya kerjakan dulu.

Oke baik mas
