### ISSUE TITLE
Bug: jumlah 'sedang diperbaiki' salah di mutasi inventaris barang

### ISSUE THREAD

**Issue by Cakwidod** [OpenSID/OpenSID#822]
untuk barang inventaris pada mutasi "sedang diperbaiki" jumlahnya ada ketidak cocokan/kesalahan penjumlahannya

**Comment by eddieridwan** [comment]
@Cakwidod mohon lampirkan screenshot contoh error ini.

**Comment by Cakwidod** [comment]
![new picture 9 a](https://user-images.githubusercontent.com/33275940/36773881-59527cde-1c8e-11e8-8331-83fb356f52e4.jpg)

**Comment by eddieridwan** [comment]
Ok, perlu dicari cara untuk membatasi jumlah mutasi untuk jenis mutasi 'status diperbaiki' supaya tidak melebihi jumlah barang yang rusak.

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
