### ISSUE TITLE
Tidak bisa simpan surat yang baru di buat

### ISSUE THREAD

**Issue by mranca** [OpenSID/OpenSID#8230]
### Jelaskan error yg dialami

Saat tambah surat baru tombol simpan dan keluar tidak aktif 

### Cara untuk mereplikasi errornya

1. Masuk admin 
2. Klik layanan surat
3. Pengaturan surat
4. Tambah
5. Coba buat surat surat baru dan klik simpan dan keluar

### Hasil yg diharapkan

.

### Tangkapan layar dan log error
![tombol](https://github.com/user-attachments/assets/29b1c93a-25a7-4a92-8b76-7b44dc33732c)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

terbaru

### Tema Yang Digunakan

.

### Informasi tambahan

.

**Comment by agungsugiarto** [comment]
Pak @mranca issue ini saya close, untuk bisa menyimpan pastikan semua form input sudah benar, jika dilihat pada tampilan screenshot di atas template surat belum di input.

**Comment by mranca** [comment]
@agungsugiarto coba tes di berputar pak sebelum close issuenya
