### ISSUE TITLE
Tabel Halam edit dan preview beda

### ISSUE THREAD

**Issue by pemdescalor** [OpenSID/OpenSID#8231]
### Jelaskan error yg dialami

Tabel yang ditampilkan tidak sama antara di halaman edit dan halaman preview

### Cara untuk mereplikasi errornya

1. Tambah Surat
2. insert tabel
3. posisikan sesuai halam diatasnya

### Hasil yg diharapkan

Sama antara Halaman Edit dan Preview

### Tangkapan layar dan log error

![Screenshot_4](https://github.com/user-attachments/assets/5c6b0540-ccce-47f1-b239-f471870e4b35)
![Screenshot_3](https://github.com/user-attachments/assets/c7a2454b-60a4-4503-8825-0b4300dc306a)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v2407.0.2

### Tema Yang Digunakan

silir

**Comment by agungsugiarto** [comment]
issue ini saya close, karena duplikat dengan https://github.com/OpenSID/OpenSID/issues/8027
