### ISSUE TITLE
Bug/error: Tambah anggota / warga terdata di suplemen error

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8232]
### Jelaskan error yg dialami

Tambah anggota / warga terdata di suplemen error

### Cara untuk mereplikasi errornya

1. Klik menu Data Suplemen
2. Tambah Suplemen 
3. Tambah Anggota / Warga Terdata Suplemen 

### Hasil yg diharapkan

Dapat Menambahkan Anggota / Warga Terdata di Suplemen

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/d4a12085-c642-4fd1-a30e-81179d0b097d)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Versi 2407.0.2-premium

**Comment by agungsugiarto** [comment]
mas @rgrahardi issue ini saya close, karena duplikat dengan issue https://github.com/OpenSID/OpenSID/issues/8223
