### ISSUE TITLE
Bug/error: LAPORAN KEPENDUDUKAN BULANAN MENAMPILKAN DATA YANG KURANG SESUAI

### ISSUE THREAD

**Issue by emanuel-simon** [OpenSID/OpenSID#8233]
### Jelaskan error yg dialami

Laporan Kependudukan Bulanan mengambil data berdasarkan **Tanggal Laporan**, Bukan **Tanggal Peristiwa**, sehingga Laporan Kependudukan Bulanan menampilkan data yang salah atau tidak sesuai dengan kejadian sebenarnya.

### Cara untuk mereplikasi errornya

Misalnya Data Kematian, Penduduk yang mati pada bulan/tahun yang lain, masuk ke Laporan Bulanan pada bulan sesuai tanggal Lapor, Contoh, Penduduk yang mati pada bulan 26 November 2023, tapi lapornya di 13 Juli 2024, akan tercatat pada Laporan Kependudukan Bulan Juli 2024.

### Hasil yg diharapkan

Agar Laporan Kependudukan Bulanan dapat mengambil data pada **Tanggal Peristiwa**, bukan Tanggal Lapor, sehingga Laporan Bulanan sesuai dengan keadaan di lapangan.

Karna Kebiasaan di desa, Peristiwanya kematian/kelahiran/pindah/datang tidak langsung dilaporkan oleh ybs pada bulan tersebut, kadang bisa bertahun-tahun baru dilaporkan, itu juga karna ada kebutuhan surat pengantar/keterangan dari desa baru dilaporkan. 

Jadi Perangkat Desa bisa mencatat peristiwa kependudukan tsb di OpenSID dulu, tanpa harus menunggu laporan. Dan Laporan Kependudukan yang dihasilkan OpenSID (termasuk Aplikasi Kelola Desa) sesuai dengan di Lapangan.

### Tangkapan layar dan log error

Kematian di bulan Juli 2024 hanya 1, tetapi tabel menampilkan 12
![2024-07-15_13h38_50](https://github.com/user-attachments/assets/a7f87ce1-cea0-4033-8f1f-3c0fef87d540)
Tenyata Data diambil dari TGL LAPOR
![2024-07-15_13h40_46](https://github.com/user-attachments/assets/ecc4fe3f-3e95-4fed-b3af-e626f99f8fdc)
Aplikasi Kelola Desa Juga menampilkan data yg sama
![Screenshot 2024-07-22 131238](https://github.com/user-attachments/assets/e81c8fed-696c-4555-91be-ed5fd4a5f43f)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2407.0.2-premium

### Tema Yang Digunakan

DeNava v14.0

**Comment by andifahruddinakas** [comment]
Terkait pencatatan ini yang dihitung adalah tgl lapornya, bukan tanggal peristiwa. Untuk alasannya sy lupa jg, pernah dibahas juga waktu pembuatan buku administrasi desa > terkait kependudukan. Dan diskusi tersebut untuk peristiwa yg dihitung adalah tgl lapornya.

Mungkin pak @eddieridwan bisa konfirmasi terkait hal ini. Karena sudah lama.

**Comment by balongbesuk** [comment]
sudah benar tgl lapor bukan tanggal peristiwa

**Comment by eddieridwan** [comment]
@andifahruddinakas yg benar adalah menggunakan tgl lapor. Alasannya supaya laporan mutasi bulanan konsisten, karena berbasis tgl lapor, bukan kapan terjadinya peristiwa. Sebagai contoh, kelahiran/kematian belum tentu dilaporkan oleh warga pas pada kejadian. Bisa pada bulan berikutnya. Sedangkan laporan mutasi bulanan yg diterbitkan bagi pihak berwenang adalah berdasarkan pelaporan tersebut, dan tidak mengubah laporan mutasi bulan2 sebelumnya. 

@rgrahardi harap penjelasan seperti itu ditambahkan ke Panduan, supaya dapat dipahami oleh pengguna. Di panduan laporan bulanan.

**Comment by rgrahardi** [comment]
baik pak @eddieridwan

**Comment by eddieridwan** [comment]
Menurut bung Utay (Telegram https://t.me/ut_ay, @ut_ay) masalah ini masih terjadi. Jadi harap bung @rgrahardi ajak bung Utay ke Klinik Bug untuk berbagi contoh konkret masalah ini. Yaitu dapatkan database yg bermasalah.

Berikut komentar dari Utay:

"Masalah ini gak selesai selesai sudah bertahun tahun. Saya bahkan sudah gak pake form tsb karena selalu selisih, tidak sesuai."

**Comment by emanuel-simon** [comment]
> @andifahruddinakas yg benar adalah menggunakan tgl lapor. Alasannya supaya laporan mutasi bulanan konsisten, karena berbasis tgl lapor, bukan kapan terjadinya peristiwa. Sebagai contoh, kelahiran/kematian belum tentu dilaporkan oleh warga pas pada kejadian. Bisa pada bulan berikutnya. Sedangkan laporan mutasi bulanan yg diterbitkan bagi pihak berwenang adalah berdasarkan pelaporan tersebut, dan tidak mengubah laporan mutasi bulan2 sebelumnya.
> 
> @rgrahardi harap penjelasan seperti itu ditambahkan ke Panduan, supaya dapat dipahami oleh pengguna. Di panduan laporan bulanan.

Baik pak, sudah mengerti saya soal Laporan Bulanan, Tanggal Lapor & Tanggal Peristiwa.
Kami desa kecil, jd agak mudah memantau perkembangan penduduknya, mungkin berbeda dengan teman2 di desa yang jumlah penduduknya banyak.
Saya skrng mengakalinya agar laporan bulanannya sesuai adalah dengan menyamakan tanggal lapor & tanggal peristiwa.
Cara ini bisa mengatasi kebutuhan data di desa kami.

**Comment by balongbesuk** [comment]
> > @andifahruddinakas yg benar adalah menggunakan tgl lapor. Alasannya supaya laporan mutasi bulanan konsisten, karena berbasis tgl lapor, bukan kapan terjadinya peristiwa. Sebagai contoh, kelahiran/kematian belum tentu dilaporkan oleh warga pas pada kejadian. Bisa pada bulan berikutnya. Sedangkan laporan mutasi bulanan yg diterbitkan bagi pihak berwenang adalah berdasarkan pelaporan tersebut, dan tidak mengubah laporan mutasi bulan2 sebelumnya.
> > @rgrahardi harap penjelasan seperti itu ditambahkan ke Panduan, supaya dapat dipahami oleh pengguna. Di panduan laporan bulanan.
> 
> Baik pak, sudah mengerti saya soal Laporan Bulanan, Tanggal Lapor & Tanggal Peristiwa. Kami desa kecil, jd agak mudah memantau perkembangan penduduknya, mungkin berbeda dengan teman2 di desa yang jumlah penduduknya banyak. Saya skrng mengakalinya agar laporan bulanannya sesuai adalah dengan menyamakan tanggal lapor & tanggal peristiwa. Cara ini bisa mengatasi kebutuhan data di desa kami.

kalau warga bapak meninggal di akhir bulan atau ada warga pindah beberapa tahun yang lalu atau ada kelahiran d akhir bulan, dan baru keluarga lapor / bapak ketahui, kira kira bapak masukkan pembukuan administrasi kependudukan di bulan sebelumnya apa bulan berjalan?
