### ISSUE TITLE
Permintaan fitur:  tidak semua Kades dan Perangkat yang sudah memiliki NIPD jadi operator harus mengahpus NIPD pada semua template surat agar ketika di cetak NIPD tidak muncul

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8237]
### Apa kekurangan yg ingin diatasi?

 tidak semua Kades dan Perangkat yang sudah memiliki NIPD jadi operator harus mengahpus NIPD pada semua template surat agar ketika di cetak NIPD tidak muncul
 
 
![image](https://github.com/user-attachments/assets/2909df42-8ac7-4412-827e-2f37181cfb5f)
![image](https://github.com/user-attachments/assets/b3d1428b-c2ae-4d7d-b350-27414682b7ce)

### Jelaskan solusi yg diinginkan

Solusi Permintaan Fitur baru terdapat pengaturan pilihan tampilkan NIPD atau tidak pada Surat

### Apakah ada alternatif lain

![image](https://github.com/user-attachments/assets/ba11ba50-60a1-41cf-9b97-82e1af61d23f)

kalau NIPD kosong maka kata NIPD pada surat di hilangkan dihilangkan

### Untuk versi OpenSID mana

2408.0.0-premium

**Comment by ariandii** [comment]
solusi yg diinginkan:
Perbaiki agar yang tidak mengisi / NIPD kosong pada data Pemerintah Desa, maka `[SEbutan_nip_desa]` **tidak perlu** Tampil seperti `NIPD :` di bawah nama Pamong pada saat cetak surat.
