### ISSUE TITLE
Bug/error: di menu keluarga no kk penduduk sebagai kepala keluaga masih bisa dipakai padahal status dasarnya sudah meninggal dunia / mati

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8239]
### Jelaskan error yg dialami

Bug/error: di menu keluarga "no kk penduduk sebagai kepala keluaga" masih bisa dipakai padahal status dasarnya sudah meninggal dunia / mati

"seharusnya jika yang meninggal kepala keluarga sudah tidak boleh ada anggota keluarga yang menggantikan no kk tersebut untuk dipakai, dan harus membentuk kk dengan nomor KK baru."

### Cara untuk mereplikasi errornya

1. Klik Menu Keluarga 
pilih keluarga yang memiliki anggota keluarga contoh Putra Saputra sebagai kepala keluarga no KK 51111111111111 memilki anggota keluarga 4 jadi 5 tambah kepala keluarga.

2. Klik menu Penduduk ubah status dasar mati untuk kepada keluarga I MADE ARDIANA

3. masuk ke detail keluarga Putra Saputra sebagai kepala keluarga sudah tidak ada karena sudah diubah status dasar menjadi mati.

awalnya jumlah nya 5 sekarang tinggal 4 dan nomor KK pemilik kepala keluarga sudah meninggal I MADE ARDIANA 
masih digunakan untuk anggota kelurga yang 4 ke 4 anggota keluarga ini masih menggunakan no kk yang kepala keluarganya sudah meninggal yaitu Putra Saputra sebagai kepala keluarga no KK 51111111111111

catatan alur diatas salah karena nomor KK kepala keluarga I made tidak boleh dipakai lagi 
tetapi masih terpakai oleh istri dan anak dan akan dibuatkan issue perbaiknya.

### Hasil yg diharapkan

seharusnya jika yang meninggal kepala keluarga sudah tidak boleh ada anggota keluarga yang menggantikan no kk tersebut untuk dipakai, dan harus membentuk kk dengan nomor KK baru.

ini juga berpengaruh ke laporan keluarga seharusnya jumlah keluarga 500 jika ada kepala keluarga yang meninggal jumlahnya  keluarga pasti berkurang 1 keluarga, tetapi akan bertambah juga karena istri dan anak atau anggota kelaurganya akan di daftarkan ke kk yang baru, karena no kk sebelumnya tidak bisa lagi digunakan. pada laporan data keluarga ada kelurga yang berkurang dan ada keluarga yang baru.

usulan perbaikan : 

opsi 1
beri notifikasi jangan pernah ubah status dasar penduduk yang berstatus kepala keluarga dan masih memiliki anggota keluarga, 
lakukan pecah kk dahulu kepada anggota kepala keluarga yang akan diubah status dasarnya menjadi mati

opsi 2 
ketika ubah status dasar kepala keluarga meninggal terdapat centang untuk memeberikan no kk baru ke anggota keluarga agar tidak perlu pecah kk

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Versi 2407.0.2-premium

### Tema Yang Digunakan

natra

### Informasi tambahan

-

**Comment by andifahruddinakas** [comment]
pak @eddieridwan, apakah alur ini di fixkan, karena selama ini kita masih membolehkan no_kk diwarikan ke anggota keluarganya (walaupun yg selama ini kita ketahui tidak boleh). Karena ada pengguna yang masih menerapkan cara tsb.

**Comment by eddieridwan** [comment]
@andifahruddinakas sebaiknya tidak boleh lagi. Karena itu merupakan salah satu sumber selisih antara jumlah keluarga di laporan bulanan dan yg di daftar keluarga (karena kepala keluarga meninggal, jumlah keluarga di laporan bulanan berkurang, tetapi di daftar keluarga masih ada keluarga tsb). Dan memang menyalahi aturan. 

Nanti kalau ada desa yg minta diperbolehkan mewariskan nomor KK, kita harus cari cara supaya tidak mengakibatkan selisih. Kalau tidak salah yg memerlukan dulu itu karena perlu membuat surat keterangan pakai KK lama karena masih menunggu Dukcapil menerbitkan KK baru. Jadi nanti kita teliti lagi persisnya kebutuhannya (dan alasannya) dan terapkan solusi yg tidak mengakibatkan kerancuan data.

**Comment by eddieridwan** [comment]
@andifahruddinakas beritahu kalau sdh diterapkan. Supaya saya bisa beritahu pengguna, dan ajak mereka untuk memberitahu kalau ada kasus yg memerlukan: dan info persisnya mengapa diperlukan dan apakah bersifat permanen atau sementara. Kalau bisa temukan pembahasan dulu terkait ini tolong juga beritahu.

**Comment by andifahruddinakas** [comment]
> @andifahruddinakas sebaiknya tidak boleh lagi. Karena itu merupakan salah satu sumber selisih antara jumlah keluarga di laporan bulanan dan yg di daftar keluarga (karena kepala keluarga meninggal, jumlah keluarga di laporan bulanan berkurang, tetapi di daftar keluarga masih ada keluarga tsb). Dan memang menyalahi aturan.
> 
> Nanti kalau ada desa yg minta diperbolehkan mewariskan nomor KK, kita harus cari cara supaya tidak mengakibatkan selisih. Kalau tidak salah yg memerlukan dulu itu karena perlu membuat surat keterangan pakai KK lama karena masih menunggu Dukcapil menerbitkan KK baru. Jadi nanti kita teliti lagi persisnya kebutuhannya (dan alasannya) dan terapkan solusi yg tidak mengakibatkan kerancuan data.

Solusi : 
- [ ] tidak dapat ubah status penduduk dengan SHDK yg merupakan Kepala Keluarga yang masih memiliki anggota keluarga.
- [ ] tambahkan keterangan pada bagian tsb.
plihan mati tidak ada.
![image](https://github.com/user-attachments/assets/99bb4587-c6bb-4d40-a10d-c72211add1ad)

ada info sbb:
![image](https://github.com/user-attachments/assets/234bd0a7-4355-43b5-a556-71a3f15f2ba0)

- [ ] tambahkan panduan untuk perubahan alur tsb. (@rgrahardi)

**Comment by andifahruddinakas** [comment]
> @andifahruddinakas beritahu kalau sdh diterapkan. Supaya saya bisa beritahu pengguna, dan ajak mereka untuk memberitahu kalau ada kasus yg memerlukan: dan info persisnya mengapa diperlukan dan apakah bersifat permanen atau sementara. Kalau bisa temukan pembahasan dulu terkait ini tolong juga beritahu.

Sudah disesuakan dan akan masuk di rilis berikutnya.
