### ISSUE TITLE
Bug/error: Tidak ada inputan untuk penjelasan penyebab kematian / hilang hanya terdapat pilihan / option

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8240]
### Jelaskan error yg dialami

terdapat pemberitahuan pada ubah status dasar "Jika meninggal atau hilang, jelaskan penyebabnya." tetapi tidak terdapat inputan untuk menjelaskan penyebab kematian atau hilang hanya berupa pilihan / option.

### Cara untuk mereplikasi errornya

1. pilih data penduduk 
2. ubah status dasar
3. pilih mati
4. terdapat pemberitahuan  "Jika meninggal atau hilang, jelaskan penyebabnya."
5. tidak ada inputan untuk menuliskan penjelasan penyebab meninggal atau hilang hanya ada pilihan / option

### Hasil yg diharapkan

terdapat inputan untuk menjelaskan penyebab meninggal atau hilang

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/1bb2ac75-aa76-4ef2-8036-8d5086816017)
![image](https://github.com/user-attachments/assets/5fffc75e-a29a-4068-b6c9-d99310806a88)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Versi 2407.0.2-premium

**Comment by ariandii** [comment]
Hasil yg diharapkan "BUKAN"
terdapat inputan untuk menjelaskan penyebab meninggal atau hilang

namun lebih kepada mana yang sesuai, antara informasi pada notifikasi yang diberikan dengan prakteknya.

**Comment by andifahruddinakas** [comment]
mas @rgrahardi, penjelasan detail dari penyebab kematian biasa di jelaskan lewat catatan peristiwa.

**Comment by ariandii** [comment]
![2024-07-24_19h37_56](https://github.com/user-attachments/assets/7cc87dd2-558e-4b76-a02f-c9f658582744)

Nampaknya kalimat ini perlu disesuaikan, jika mengacu pada catatan peristiwa.

**Comment by andifahruddinakas** [comment]
Untuk informasi dibuat lebih umum, karena tiap status sudah memiliki isian tersendiri.

![image](https://github.com/user-attachments/assets/15904c12-39d6-4eb7-8663-4832d2ee0971)

melalui commit https://github.com/OpenSID/premium/commit/f29c2502d7b544fcb13c42cbc4fd96dea727cf82
