### ISSUE TITLE
Bug/error: Tidak ada Pemberitahuan query manual salah pada Shortcut data tetap tersimpan dan menyebab blank putih pada halaman beranda dan data shortcut tidak bisa diubah lagi.

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8241]
### Jelaskan error yg dialami

Tidak ada Pemberitahuan query manual salah pada Shortcut data tetap tersimpan dan menyebab blank putih pada halaman beranda dan data shortcut tidak bisa diubah lagi.

### Cara untuk mereplikasi errornya

1. Klik Menu Pengaturan 
2. Klik Shortcut
3.  tambah shorcut
4. piliih query manual 
5. masukan query Penduduk::count()
6. simpan
7. menu beranda blank putih

### Hasil yg diharapkan

terdapat pemeritahuan jika inputan query manual salah agar tidak menyebabkan blank pada beranda

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/553c561e-745b-483b-94fd-83bd291e7bb3)

![image](https://github.com/user-attachments/assets/807ab16a-51ce-4928-9d62-a021c5217484)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Versi 2407.0.2-premium

**Comment by andifahruddinakas** [comment]
Cek:
- [ ] jika query yg diinput tidak valid atau tidak return angka, maka shortcut jgn ditampilkan.
