### ISSUE TITLE
Bug/error: Cetak Nota Faktur di menu Layanan Pelanggan error 500

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#8243]
### Jelaskan error yg dialami

https://github.com/user-attachments/assets/b785167c-6613-4d1f-b4aa-124cecc97c7f

Replikasi di video atas

### Cara untuk mereplikasi errornya

Cetak Nota Faktur di menu Layanan Pelanggan error 500

### Hasil yg diharapkan

Normal

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2407.0.2

**Comment by andifahruddinakas** [comment]
Ini jg tidak tampil

![image](https://github.com/user-attachments/assets/8fc0dea6-ce42-4c08-9bca-7320eda370a6)

**Comment by andifahruddinakas** [comment]
Sekalian perbaiki kelebihan { pada issue https://github.com/OpenSID/OpenSID/issues/8242

**Comment by ilhamwahyu-ni** [comment]
![image](https://github.com/user-attachments/assets/5d678519-5731-4414-8c53-adc168ae4d92)

apakah ini bug yang sama,
atau saya buatkan isu yang baru mas @andifahruddinakas 

Info : batipuah ateh juga sudah langganan => anjungan.

**Comment by andifahruddinakas** [comment]
> ![image](https://private-user-images.githubusercontent.com/85351181/351972975-5d678519-5731-4414-8c53-adc168ae4d92.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4ODYzMjMsIm5iZiI6MTcyMTg4NjAyMywicGF0aCI6Ii84NTM1MTE4MS8zNTE5NzI5NzUtNWQ2Nzg1MTktNTczMS00NDE0LThjNTMtYWRjMTY4YWU0ZDkyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI1VDA1NDAyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiMDBiNDVlZjM0NTZhNGI5YWQxY2QyNzYwYmRlMTg1NTY5ZmIyZDlhMTk1M2M2ZWVkYThhY2FhN2EzMGFmYTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.g_sWYL1fCiYSeLte8ubo1N6RNdbaJ369JLf7cJ3af5A)
> 
> apakah ini bug yang sama, atau saya buatkan isu yang baru mas @andifahruddinakas
> 
> Info : batipuah ateh juga sudah langganan => anjungan.

ini terkait request layanan, sudha perbah ada issue https://github.com/OpenSID/wiki-layanan-opendesa/issues/675

tp coba sy periksa lg disisi OpenSIDnya

**Comment by langonsari** [comment]
![image](https://github.com/user-attachments/assets/94bca21f-43f5-441e-ae49-2b39bc187841)
![image](https://github.com/user-attachments/assets/05047d9a-dc18-4981-a168-c76d2ca03e53)
sepertinya masalah gagal koneksi ke API Layanan Opendesa.id

**Comment by habibie11** [comment]
dari pengecekkan issue ini error ketika cetak nota faktur yang sepertinya masalahnya ada dilayanan. saya tidak menemukan masalah disisi opensidnya cc mas @andifahruddinakas @vickyrolanda 
![image](https://github.com/user-attachments/assets/e8c3e347-dd70-4b3e-98c0-69c81f52cc7b)

**Comment by pandigresik** [comment]
Sudah ada perbaikan di layanan https://github.com/OpenSID/Layanan_OpenDESA/pull/666

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/Layanan_OpenDESA/pull/666
