### ISSUE TITLE
Terjadi server  eror 500 saat cetak faktur

### ISSUE THREAD

**Issue by mranca** [OpenSID/OpenSID#8245]
### Jelaskan error yg dialami

Saat cetak nota faktur terjadi server error 500

### Cara untuk mereplikasi errornya

1. Masuk admin
2. Klik info layanan pelanggan / logo baterai 
3. Klik nota faktur

### Hasil yg diharapkan

.

### Tangkapan layar dan log error

![Screenshot_20240724_221323](https://github.com/user-attachments/assets/7b21e3b5-e7ef-4673-9b8c-9e91ffd6501d)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

terbaru

### Tema Yang Digunakan

.

### Informasi tambahan

.

**Comment by ariandii** [comment]
duplicate https://github.com/OpenSID/OpenSID/issues/8243
