### ISSUE TITLE
Bug/error: Belum tampilnya nomor HP Desa di tampilan login layanan mandiri, dan perlu penataan alamat

### ISSUE THREAD

**Issue by mah-mudi** [OpenSID/OpenSID#8246]
### Jelaskan error yg dialami

Belum tampilnya nomor HP Desa di tampilan login layanan mandiri dan penempatan penulisan yang tepat pada alamat di tampilan login layanan mandiri

### Cara untuk mereplikasi errornya

contoh ke link https://desaleran.gresikkab.go.id/layanan-mandiri/masuk

karena berputar.opendesa.id eror

### Hasil yg diharapkan

nomor HP Desa di tampilan login layanan mandiri, dan perlu penataan alamat di tampilan login layanan mandiri.

misal semula 

LAYANAN MANDIRI
DESA LERAN

Kecamatan Manyar
Kabupaten Gresik
Jl. Darussalam RT 004 RW 001
Kodepos 61151

Silakan hubungi operator desa untuk mendapatkan kode PIN anda.

**menjadi**

LAYANAN MANDIRI
DESA LERAN

Jl. Darussalam RT 004 RW 001 Desa Leran
Kecamatan Manyar Kabupaten Gresik
Kode Pos 61151

Silakan hubungi 087712345678 (sesuaikan no HP Desa) atau operator desa untuk mendapatkan kode PIN anda.

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/600f3aac-d255-4f07-a5c3-e7f1d45f71db)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

24.07.02 premium

### Tema Yang Digunakan

silir

### Informasi tambahan

-

**Comment by andifahruddinakas** [comment]
Belum ada pengaturan untuk mennetukan nomor operator siapa yang ditampilkan pada halaman tsb

**Comment by mah-mudi** [comment]
@andifahruddinakas nomor nembak di Nomor HP yang di identitas desa aja pak
