### ISSUE TITLE
Bug/error: tombol unduh dan printer di pratinjuau membingungkan

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8250]
### Jelaskan error yg dialami

tombol unduh dan printer di pratinjuau membingungkan pengguna karena ketika klik unduh hasilnya sama dengan cetak  perangkat desa mengira sudah mencetak surat padahal belum. sehingga status surat tetap konsep tidak berganti ke siap cetak dan ketika hasil pratinjau yang di cetak penomoran surat tetap jalan ketika cetak surat lain nomornya bertambah padahal yang di cetak sebelunya pratinjau.

### Cara untuk mereplikasi errornya

1. klik cetak surat
2. klik pratinjau 
3. terdapat tombol unduh dan cetak

### Hasil yg diharapkan

usulan  

solusi pertama
1. tombol unduh dan tombol printer dihapus agar pengguna tida mencetak dari tombol unduh / printer pratinjau

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/e29756ce-af11-4c22-802d-784b5c2bbe4a)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Versi 2407.0.2-premium

**Comment by eddieridwan** [comment]
@rgrahardi judul issue jangan dibuat terlalu panjang. Singkat saja, misalnya "tombol unduh dan printer di pratinjuau membingungkan".

**Comment by ariandii** [comment]
https://github.com/OpenSID/OpenSID/issues/8162

https://github.com/OpenSID/premium/pull/3911

https://github.com/OpenSID/premium/pull/3911/files#diff-057c04a41ef473e11a65753a9395dc66abce26624a804270aa6463684abb7be8

**Comment by andifahruddinakas** [comment]
sy kurang tau jg kalau tools bawaan tsb bisa dihilangkan atau tidak, tp mungkin bisa dicoba dlu.
