### ISSUE TITLE
Bug/error: Cetak data pemerintahan tidak sesuai

### ISSUE THREAD

**Issue by ilhamwahyu-ni** [OpenSID/OpenSID#8252]
### Jelaskan error yg dialami

![image](https://github.com/user-attachments/assets/e00cf7a4-0786-48e5-8615-165164c49f44)

### Cara untuk mereplikasi errornya

cetak anggota pemerinrahan

### Hasil yg diharapkan

normal

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/54857939-7f02-448d-9d2d-de24188bd828)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

 2407.0.3

**Comment by andifahruddinakas** [comment]
Bisa disesuaika sbb:

- [ ] cetak/unduh berdasarkan datatable yg aktif. bisa lihat contoh modul penduduk
