### ISSUE TITLE
Bug/error: Log eror salah tempat

### ISSUE THREAD

**Issue by ilhamwahyu-ni** [OpenSID/OpenSID#8253]
### Jelaskan error yg dialami

tampil pesan eror di rumah tangga

![image](https://github.com/user-attachments/assets/58a8d1be-b14f-4831-9ced-db4257d7aa20)

### Cara untuk mereplikasi errornya

kependudukan >> rumah tangga >> tampil pesan eror

### Hasil yg diharapkan

seharusnya pesan ada di log..

### Tangkapan layar dan log error

[eror.webm](https://github.com/user-attachments/assets/4ab3e1d5-5c15-4e19-b83a-43168f154f0a)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

 2407.0.3

**Comment by andifahruddinakas** [comment]
error tsb hanya tampil jika mode development, untuk website yg sudah siap, sebaiknya dibuat jd production.

**Comment by ilhamwahyu-ni** [comment]
Gimana cara nya mas?
