### ISSUE TITLE
Bug/error:  Penomoran Dokumen Desa Menjadi String (" ")

### ISSUE THREAD

**Issue by ilhamwahyu-ni** [OpenSID/OpenSID#8255]
### Jelaskan error yg dialami

-

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

normal

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/1d53fc36-c654-45bd-90f2-0a61ad1bd671)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

 2407.0.3

**Comment by andifahruddinakas** [comment]
mas @ilhamwahyu-ni, mungkin bisa disertakan contoh input datanya.

![image](https://github.com/user-attachments/assets/07cb5ab0-3814-4aa0-a0d5-657821b781d9)

**Comment by ilhamwahyu-ni** [comment]
![image](https://github.com/user-attachments/assets/8f4eaf50-b09a-40f1-977a-8a17aab1dd29)

![image](https://github.com/user-attachments/assets/abf459e3-cfac-48db-a18f-508db18b782a)



ini mas @andifahruddinakas

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melalui pr https://github.com/OpenSID/premium/pull/3995
