### ISSUE TITLE
Bug/error: Daftar Penerima Bantuan dan informasi-publik data sedang memproses

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8256]
### Jelaskan error yg dialami

Daftar Penerima Bantuan dan informasi-publik data sedang memproses

hasil penelusuran Tema OpenSID

1. DeNatra aman
2. Batuah Bantuan tidak aman dan informasi-publik aman
3. Natra dan Esensi aman
4. DeNava informasi-publik dan bantuan tidak aman
5. Pusako aman

### Cara untuk mereplikasi errornya

1. halaman informasi-publik
2. halaman statistik bantuan

### Hasil yg diharapkan

dapat menampilkan daftar penerima bantuan dan informasi-publik

### Tangkapan layar dan log error

Tema Denatra

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Versi 2407.0.2-premium

**Comment by andifahruddinakas** [comment]
mas @rgrahardi, issue ini sy close karena di tema bawaan normal. untuk selanjutnya laporkan terkait tema bawaan saja.

untuk kasus ini sy masih bantu menyelesaikannya.
