### ISSUE TITLE
Bug/error: Pop Up Persetujuan Cookies Pada Absensi pada Device iPhone

### ISSUE THREAD

**Issue by wahyabiantara** [OpenSID/OpenSID#8258]
### Jelaskan error yg dialami

Saat membuka link absensi kehadiran pertama kali melalui perangkat Desa di HP/Mobile, Pop up permintaan persetujuan Cookies tidak muncul dengan baik sehingga user tidak dapat melakukan persetujuan.

### Cara untuk mereplikasi errornya

Buka halaman tumbakbayuh.desa.id/kehadiran

### Hasil yg diharapkan

Pop Up muncul pada layar mobile, sehingga memudahkan pengguna untuk memberikan persetujuan

### Tangkapan layar dan log error

![screeshot-1721895287](https://github.com/user-attachments/assets/dbe9bbdf-6c71-4dd9-b10d-b4fb9701edd3)
![screeshot-1721895138](https://github.com/user-attachments/assets/311712df-6b52-45b8-880c-0e3d040abaf6)
![screeshot-1721895085](https://github.com/user-attachments/assets/222e8587-c824-4ffa-ab94-bb97e11def33)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2406.0.1

**Comment by ariandii** [comment]
tidak hanya IPhone, Android juga alami hal sama, Huawai juga sama. dll

gunakan mode desktop pada browser tersebut, agar muncul.
