### ISSUE TITLE
Bug/error: Font Time New Roman tidak bisa menggunakan bold dan garis miring

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8259]
### Jelaskan error yg dialami

Font Time New Roman ketika di pengaturan sudah di bold dan garis miring ketika di cetak tidak muncul bold dan garis miringnya, pakai arial aman

### Cara untuk mereplikasi errornya

1. Cetak Surat
2. Kop Surat Pakai Time New Roman buat Bold dan Miring
3. Cetak lihat hasilnya 

### Hasil yg diharapkan

Time new roman bisa berfungsi bold dan miring

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/dd79a5db-d2c2-495d-acaf-fdc676b5c2ac)
![image](https://github.com/user-attachments/assets/5d3128bc-9b3e-4605-80ba-e1bce808d792)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Versi 2407.0.2-premium

**Comment by eddieridwan** [comment]
@rgrahardi terus diingatkan, harap judul issue singkat saja, tidak panjang2 seperti yg anda buat.

**Comment by agungsugiarto** [comment]
@rgrahardi perlu di replikasi, 
- font untuk header dan isian sebaiknya menggunakan satu font yg sama.
- lakukan ubahan bold dan miring pada header

@andifahruddinakas sebaiknya, di pengaturan header dan footer pilihan font di disable, jadi mengikut global / di isian surat

**Comment by agungsugiarto** [comment]
Saya test menggunakan font times new roman, sesuai replikasi di atas aman



![Image](https://github.com/user-attachments/assets/7462ef0b-961e-4524-bd47-50a2c8546447)

**Comment by ariandii** [comment]
> Saya test menggunakan font times new roman, sesuai replikasi di atas aman
> 
> ![Image](https://private-user-images.githubusercontent.com/10989147/352905911-7462ef0b-961e-4524-bd47-50a2c8546447.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyMjU5MTksIm5iZiI6MTcyMjIyNTYxOSwicGF0aCI6Ii8xMDk4OTE0Ny8zNTI5MDU5MTEtNzQ2MmVmMGItOTYxZS00NTI0LWJkNDctNTBhMmM4NTQ2NDQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI5VDA0MDAxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwYjlmMjg4NmYzZGQ4MjIyNmIxZWY4NzllNDY0Y2FjMDEwYjljMTNkZGJmOTk5YWZhOGI3NWM0NjdjYmEyMjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.L4b7EziacVc0r7tyiRTbvrKAhWD5qZr_FLMu44Lyqm8)

jika dilihat sekilas, yang terlihat di layar ini bukan jenis font Times New Roman

**Comment by andifahruddinakas** [comment]
> Saya test menggunakan font times new roman, sesuai replikasi di atas aman
> 
> ![Image](https://private-user-images.githubusercontent.com/10989147/352905911-7462ef0b-961e-4524-bd47-50a2c8546447.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyMjYxNjksIm5iZiI6MTcyMjIyNTg2OSwicGF0aCI6Ii8xMDk4OTE0Ny8zNTI5MDU5MTEtNzQ2MmVmMGItOTYxZS00NTI0LWJkNDctNTBhMmM4NTQ2NDQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI5VDA0MDQyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyM2JhZjUzODQyYjdkODM3ODJkNzUzYmNmMjVhYjQwYjdiOTY2YzFhNWY2MDUxY2ZlZjc1ZTg0OWQyMjQyYjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6aR-zM9x9E17Xp9JX_kkgVxPHzLJXR2E7AB3r4mqCvg)

ini mas pakai font times new roman
![image](https://github.com/user-attachments/assets/6df63e70-32b7-4a8b-bea0-e7cf772348e6)

cetak/tinjau
![image](https://github.com/user-attachments/assets/6c8728ef-7a9a-4128-970c-410a8e89ebe6)

untuk melihat font yg digunakan, bisa arahkan pada bagian kalimat tsb. Contoh : 
<img width="712" alt="image" src="https://github.com/user-attachments/assets/c4f22858-77a4-4882-8ad7-c7b180cc8961">
