### ISSUE TITLE
Bug/error: Input Keterangan pada surat terlalu panjang surat menjadi error

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8268]
### Jelaskan error yg dialami

Input Keterangan pada surat terlalu panjang surat menjadi error

### Cara untuk mereplikasi errornya

1. Klik Cetak surat keterangan domisili
2. input isian keperluan / keterangan dengan text yang panjang
3. cetak surat

### Hasil yg diharapkan

input keterangan bisa menyimpan keterangan yang panjang.

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/a78b98f9-2962-4c76-9fa7-80b66ebcfaea)
![image](https://github.com/user-attachments/assets/e9a15989-2eb8-423f-ab8d-38e094a1789a)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Versi 2407.0.3-premium

**Comment by andifahruddinakas** [comment]
Mungkin bisa tambahkan default max input 200 karakter jika pada form attributenya kosong.
