### ISSUE TITLE
Bug/error: pengaturan lebar dan tinggi photo perangkat desa tidak berfungsi

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8269]
### Jelaskan error yg dialami

1. ukuran gambar di cek di local komputer L 400px dan T 600px 
2. saat diupload ukuran dikasih L 600 dan T 600 berhasil disimpan, di cek ukuran gambar pada web ukuran tidak L 600 x T 600 tetap L 400px dan 600px
 

### Cara untuk mereplikasi errornya

1. Menu pemerintah desa
2. upload gambar pemerinta desa kasih size 600px dan 600px
3. saat di simpan size kembali ke 200px dan 200px pada menu pemerintah desa dan di cek gambar (Inspect elemen)pada website size mengikuti ukuran gambar yang di komputer local

### Hasil yg diharapkan

bisa mengatur lebar dan Tinggi gambar pada menu pemerintah desa

### Tangkapan layar dan log error

1. Ukuran gambar di Local
![image](https://github.com/user-attachments/assets/2b91e7af-8ced-4b79-96ba-cc4f9ee4d4c2)

Upload ke pemerintah desa 

![image](https://github.com/user-attachments/assets/0a278727-ee18-4fc2-880b-d6fa98d0a6cd)

pas di cek inspect elemen ukuran bukan 600 x 600 tetapi mengikut ukuran yang di local

![image](https://github.com/user-attachments/assets/c3d5e644-f0c2-4d51-924a-5d1d5e40dddf)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Versi 2407.0.3-premiumAplikasi

**Comment by andifahruddinakas** [comment]
untuk ukuran gambar, tidak ada proses menyimpan data tersebut ke database. karena langsung di implementasikan saat ganbar diunggah.

Jadi masalahnya ada saar melakukan update lg, ketika langsung disimpan. ukuran yg pernah disimpan misalnya 600 x 400 akan kembali ke defaultnya yakni 200 x 200.

Bisa dibuat seperti ini:
- Jika update, ambil ukuran gambar dan tampilkan pada saat edit jika file memang ada.
![image](https://github.com/user-attachments/assets/181249d0-199e-4028-b55e-f8428046fde5)
