### ISSUE TITLE
Bug/error: form isian belum ada. surat pernyataan dinas

### ISSUE THREAD

**Issue by ilhamwahyu-ni** [OpenSID/OpenSID#8271]
### Jelaskan error yg dialami

-

### Cara untuk mereplikasi errornya

![image](https://github.com/user-attachments/assets/c3fc4994-2105-44ac-afec-cc62a588007b)

### Hasil yg diharapkan

normal

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/ae962a63-627a-4eef-8b9a-49b0365316dc)

![image](https://github.com/user-attachments/assets/32604340-fe0b-4d52-933d-ba1664589f67)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

 2407.1.0

**Comment by andifahruddinakas** [comment]
mas @ilhamwahyu-ni, bisa gunakan atau restore ke surat bawaan yg sudah disediakan.

![image](https://github.com/user-attachments/assets/812958f8-0bb0-4f39-b5f4-ce2eb8b21489)

**Comment by ilhamwahyu-ni** [comment]
Baik mas
