### ISSUE TITLE
Bug/error: pengaturan surat kelahiran "Sediakan di Layanan Mandiri" pilih ya tidak tersimpan

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8274]
### Jelaskan error yg dialami

pengaturan surat kelahiran "Sediakan di Layanan Mandiri" pilih ya tidak tersimpan

### Cara untuk mereplikasi errornya

1. Klik Pengaturan Surat
2. klik pengaturan Surat Kelahiran 
3.  Sediakan di Layanan Mandiri pilih `Ya` centang syarat surat
4. simpan dan keluar
5. lihat lagi pengaturan Surat Kelahiran, Sediakan di Layanan Mandiri kembali ke pengaturan `Tidak`

### Hasil yg diharapkan

Sediakan di Layanan Mandiri pilih `Ya` dapat berfungsi 

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/bd7dca1d-e4df-4118-9eae-42f27a292ddb)
![image](https://github.com/user-attachments/assets/07f1140c-34c6-414d-9014-c958d335ab9d)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Versi 2407.0.3-premium

**Comment by ariandii** [comment]
surat kelahiran perlu saksi (data pihak ketiga), tidak diperkenankan masuk Layanan Mandiri.

sesuai namanya "Layanan Mandiri" maka hanya digunakan untuk Data Mandiri saja, misal Surat Keterangan Usaha, Surat Domisili, Surat Biodata Penduduk dll.

Kalau surat Kuasa, Nikah, Kelahiram dll. tentu melibatkan data pihak ke 3 yang tidak pantas diajukan melalui Layanan Mandiri. Harus Datang Ke Kantor untuk Validasi

**Comment by eddieridwan** [comment]
@andifahruddinakas @vickyrolanda untuk kasus seperti ini, di mana pengguna menjadi bingung mengapa sesuatu tidak dapat dilakukan, sebaiknya diterapkan solusi yg memberi tahu pengguna bahwa aksi itu tidak dapat dilakukan dan mengapa tidak dapat dilakukan. 

Supaya tidak berulang dilaporkan.
