### ISSUE TITLE
Bug/error: Pengaturan Nomor surat Global tidak berfungsi

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8275]
### Jelaskan error yg dialami

Pengaturan Nomor surat Global pilih tidak kemudian masukan nomor surat manual di 2407.0.0.1 bisa digunakan nomor surat-manual di versi 2407.0.0.3 dan rilis beta tidak bisa lagi

### Cara untuk mereplikasi errornya

1. Pengaturan surat biodata penduduk
2. Gunakan Penomoran Surat Global pilih tidak 
3. masukan [kode_surat]/[nomor_surat, 3]/[kode_desa]/[tahun]
4. simpan 
5. cetak surat bioda penduduk lihat penomorannya mengikuti pemomoran global, padahal sudah menggunakan nomor manual

### Hasil yg diharapkan

Gunakan Penomoran Surat Global pilih tidak berfungsi pada surat

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/04cc5fe3-8c18-49ad-b8c7-2d317084db91)
![image](https://github.com/user-attachments/assets/d3a32bf3-92bf-4c74-b5a9-709f8a64bf8e)
![image](https://github.com/user-attachments/assets/759c6461-3e91-43dd-a982-bb3d222d5e33)
![image](https://github.com/user-attachments/assets/434add58-7464-44f5-916e-55f68e2969f0)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2407.0.0.3

**Comment by andifahruddinakas** [comment]
Sudah diperbaikan melalui commit https://github.com/OpenSID/premium/commit/721b6853fb7279ce6f8c95c4992d125c5db4b3eb
