### ISSUE TITLE
Bug/error: Proses migrasi database, mohon ditunggu Progress : Jalankan Migrasi_202407297 [Proses berhenti disini]

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8276]
### Jelaskan error yg dialami

Proses migrasi database, mohon ditunggu Progress : Jalankan Migrasi_202407297 [Proses berhenti disini]
1. Website error 500
2. log ->  ERROR - 2024-07-30 14:55:49 --> Severity: error --> Exception: Call to undefined method stdClass::update() C:\xampp\htdocs\opensid-premium\app\Imports\SuratDinasImports.php 108

### Cara untuk mereplikasi errornya

1. menu pengaturan 
2. database
3. migrasi semua
4. proses migrasi berhenti Jalankan Migrasi_202407297

### Hasil yg diharapkan

migrasi semua berhasil

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/d649489b-353c-421d-9737-151a29e33ccf)
![image](https://github.com/user-attachments/assets/b0492224-d7c1-48a6-8e52-7bbf0ee24a9f)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Versi 2407.1.0-premium

**Comment by andifahruddinakas** [comment]
mas @rgrahardi, bisa sertakan juga database yg digunakan.

**Comment by rgrahardi** [comment]
mas @andifahruddinakas jika melakukan migrasi semua pada Versi 2407.1.0-premium akan mengalami hal yang sama ?

**Comment by andifahruddinakas** [comment]
sudah diperbaiki melalui commit https://github.com/OpenSID/premium/commit/9e14f1f0833ce5b17c0ac5420faaf06f221a2f10
