### ISSUE TITLE
Bug/error: Keterangan surat Dinas menjadi surat bawaan sistem

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8277]
### Jelaskan error yg dialami

Keterangan surat Dinas di impor pada versi sebelumnya ketika update ke Versi 2407.1.0-premium surat menjadi bawaan sistem tidak berubah warna seperti surat desa

### Cara untuk mereplikasi errornya

1. impor surat Keterangan surat Dinas pada OpenSID sebelum  Versi 2407.1.0-premium
2. update Versi 2407.1.0-premium
3. surat tetap berwarna putih seperti surat bawaan sistem padahal surat impor

### Hasil yg diharapkan

surat Keterangan surat Dinas menjadi surat desa karena di impor

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/1f27e929-9469-48ae-98cd-807153c3cfc1)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Versi 2407.1.0-premium

**Comment by andifahruddinakas** [comment]
mas @rgrahardi, untuk surat bawaan terbaca dari jenis dan urlnya, walaupun ditimpa dengan ubahan desa selama masih menggunakan url surat bawaan akan tetap terbaca bawaan. Bisa membuat surat lain yg isinya sama dengan nama / url surat yang berbeda.

Penerapan ini juga diterapkan pada surat layanan yang sudah ada sebelumnya, bisa test import  pada surat layanan bawaan.
