### ISSUE TITLE
Bug/error: Penyesuaian surat dinas

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8278]
### Jelaskan error yg dialami

Surat Dinas masih pakai pengaturan surat biasa, di tambahi romawi di surat dinas tidak bisa tapi tambahi romawi di surat biasa di hasil cetak surat dinas ada romawi juga, sepertinya pengaturan format penomoran surat dinas masih mengikut ke surat biasa

### Cara untuk mereplikasi errornya

1. pengaturan surat dinas
2. masukan format penomoran surat [kode_surat]/[nomor_surat, 3]/[kode_desa]/[bulan_romawi]/[tahun]
3. simpan 
4. cetak surat dinas tidak muncul bulan_romawi
5. jika bulan romawi ditambahkan di surat biasa pada template surat dinas tampil bulan_romawi

### Hasil yg diharapkan

format penomoran surat dinas berfungsi baik

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/1f42ff3a-3d3b-4af5-8927-92f58b46d3dd)
![image](https://github.com/user-attachments/assets/a206b433-50db-400f-bd43-e3a1ecdef70a)
![image](https://github.com/user-attachments/assets/3d4b0744-1bb9-4a15-bdba-02b10dad9106)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Versi 2407.0.3-premium

**Comment by andifahruddinakas** [comment]
Beberapa bagian yang perlu disesuaikan:
- [ ] pengaturan header, footer, penomoran masih menggunakan surat layanan. Termasuk salin template header maupun foternya.
![image](https://github.com/user-attachments/assets/4906253f-e6d8-4749-858a-6b4c0ce10ca8)

- [ ] ketika pratinjau pada surat masternya maka, pengaturan yg digunakan masih surat layanan walaupun sudah disetting pada pengaturannya.
![image](https://github.com/user-attachments/assets/ebde86eb-1f9b-4601-aa13-ba415520b677)

Hasil
![image](https://github.com/user-attachments/assets/54a37edf-82a9-48c7-ab7c-0f0c9654b96d)
