### ISSUE TITLE
Bug/error: backup .sid tidak bisa

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8282]
### Jelaskan error yg dialami

backup .sid tidak bisa error 500

Log Error : 

Severity: error --> Exception: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'opensid_6441.pesan' doesn't exist (Connection: default, SQL: SHOW KEYS FROM pesan WHERE Key_name = 'PRIMARY') /data/docker/opendesa/premium/vendor/illuminate/database/Connection.php 829

Severity: error --> Exception: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`berp_opensid`.`suplemen_terdata`, CONSTRAINT `suplemen_terdata_suplemen_fk` FOREIGN KEY (`id_suplemen`) REFERENCES `suplemen` (`id`) ON DELETE CASC

### Cara untuk mereplikasi errornya

1. Klik Pengaturan 
2. Database
3. backup .sid

### Hasil yg diharapkan

Backup Seluruh Database SID (.sid)

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/d69756a0-36b5-48ac-9364-da0309e83b58)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2407.0.3-premium

**Comment by andifahruddinakas** [comment]
mas @rgrahardi, untuk terkait backup, bisa sediakan database yg digunakan.

**Comment by rgrahardi** [comment]
mas @andifahruddinakas mohon maaf saya lupa menambahkan informasi ini terjadi di desa yg menggunakan dabase gabungan diskominfo mas, ketika di klik backup .sid dibawah ke url ini, mohon petunjuk selanjutnya mas 

![image](https://github.com/user-attachments/assets/cb1862c0-54fd-474d-b582-6afedfe7103e)

**Comment by Wiliyantoro** [comment]
Ini log errornya
Severity: error --> Exception: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1102379' for key 'PRIMARY' (Connection: default, SQL: update `widget` set `id` = `id` + 1102002 where `config_id` = 1102019) /var/www/html/master-opensid/premium/vendor/illuminate/database/Connecti
n.php 824

**Comment by andifahruddinakas** [comment]
> mas @andifahruddinakas mohon maaf saya lupa menambahkan informasi ini terjadi di desa yg menggunakan dabase gabungan diskominfo mas, ketika di klik backup .sid dibawah ke url ini, mohon petunjuk selanjutnya mas
> 
> ![image](https://private-user-images.githubusercontent.com/55429781/353775811-cb1862c0-54fd-474d-b582-6afedfe7103e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0Mzc2NzgsIm5iZiI6MTcyMjQzNzM3OCwicGF0aCI6Ii81NTQyOTc4MS8zNTM3NzU4MTEtY2IxODYyYzAtNTRmZC00NzRkLWI1ODItNmFmZWRmZTcxMDNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDE0NDkzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlZjY3NDE1YzU2MmFlN2E1MThmMWEwODU5YzZhNGQwNWEzMWFjMmYyOWQ2ZjJiMTU3YTUwZTVlOTYzMjM4NDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jY9Rh1QjyglC9z5esQKCWXK2bhnTpY_PA8tUWIWeZMI)

kirim ke telegram databasenya

**Comment by apidong** [comment]
> mas @rgrahardi, untuk terkait backup, bisa sediakan database yg digunakan.

cara duplikasi 
1. buat data suplemen 
2. masuk ke rincian data suplemen yang telah di buat. 
3. tambahkan data rinciannya.
4. lakukan backup database yang .sid
![image](https://github.com/user-attachments/assets/0bdd63f0-3075-4603-81e2-bf28ecaf2de7)
![image](https://github.com/user-attachments/assets/0857268b-b032-4bc4-97bd-6884b44f9ef6)
![image](https://github.com/user-attachments/assets/61336054-747a-4338-875e-a6cfa87f6d44)
