### ISSUE TITLE
Bug/error:  rentang umur tidak boleh tumpang tindih dan kosong

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8283]
### Jelaskan error yg dialami

rentang umur tidak boleh tumpang tindih. Supaya tidak terjadi penghitungan dobel. Dan juga tidak boleh ada yg kosong.

Jadi tidak boleh seperti berikut:

1. 0-1, 1-2 (1 ada di dua rentang)
2. 0-1, 3-4 (2 kosong)

berikut rentan umur yang digunakan 
![image](https://github.com/user-attachments/assets/c96437cd-26b6-40db-87ca-27527bae6c65)
![image](https://github.com/user-attachments/assets/3f732dee-68fa-463c-ad98-dc0238362294)

### Cara untuk mereplikasi errornya

1. Klik Menu Statistik
2. Klik Statistik Penduduk
3. Klik Umur (Rentan)

### Hasil yg diharapkan

tidak ada data yang dobel dan kosong

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/ca37e89b-8984-4673-950f-bc96c8e51bee)

![image](https://github.com/user-attachments/assets/13f8e506-b523-403e-a8dd-9b82457affa2)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Versi 2407.0.3-premium

**Comment by andifahruddinakas** [comment]
mas @rgrahardi, ini format dari mana. Bisa cek format standar yang selama ini digunakan di OpenSID.
Misalkan X - Y, Perhitungan X >= Umur <= Y, dengan nilai masing-masing yang dihitung adalah tahun, jadi jika ada misalnya 1 tahun lebih 6 bulan tetap masuk di rentang 0 - 1.

Sehingga, jika menggunakan format yang dilampirkan akan terhitung 2 kali pada setiap rentang umur karena ke 2 nya memenuhi.

![image](https://github.com/user-attachments/assets/48325cac-def2-433c-9e29-21cc07e76570)

**Comment by eddieridwan** [comment]
@andifahruddinakas @vickyrolanda kalau diperlukan rentang untuk satu tahun saja, misalnya hanya untuk umur 3 tahun saja, bagaimana penulisannya?

1. cukup bilangan '3' saja, atau
2. rentang '3-3'?

**Comment by andifahruddinakas** [comment]
> @andifahruddinakas @vickyrolanda kalau diperlukan rentang untuk satu tahun saja, misalnya hanya untuk umur 3 tahun saja, bagaimana penulisannya?
> 
> 1. cukup bilangan '3' saja, atau
> 2. rentang '3-3'?

3-3

**Comment by andifahruddinakas** [comment]
pak @eddieridwan, untuk kasus ini apakah alur lama perlu diubah?

Bisa dibuat seperti ini:
- Umur M > x <= Umur N

misalnya Umur 0 sampai 1, artinya hanya menampilkan Umur x > 0 dan x <= 1.
jadi untuk 1 tahun lebih 1 haripun tidak terhitung untuk kasus ini.

namun dengan perubahan tsb, perlu juga merubahn format yg selama ini digunakan. baik itu kelompok umur beerdasarkan rentang atau kategori.
Contoh:
![image](https://github.com/user-attachments/assets/6b6e94fe-daf6-49d0-9ebc-5de5f0e629e2)
jd
![image](https://github.com/user-attachments/assets/e942ae41-0538-421d-9d75-ab2744eb3c11)

**Comment by eddieridwan** [comment]
@andifahruddinakas saat ini saya coba di berputar tidak bisa membuat rentang hanya satu umur, misalnya hanya 3 tahun saja. Yaitu tidak bisa mengisi rentang [3,3]. Kalau bisa masukkan itu, saya kira sudah cukup. Bisa saja tampilkan rentang ini sebagai "3 S/D 3 TAHUN", tapi mungkin lebih jelas kalau ditampilkan sebagai "3 TAHUN" saja. Dan akan hanya menampilkan yg umurmnya persis 3 tahun s/d 4 tahun kurang sehari. 

Sedangkan rentang [1,2], seperti yg sekarang berlaku, akan menampilkan yg umurnya persis 1 tahun s/d 3 tahun kurang sehari.

Kemudian, terapkan aturan supaya rentang tidak boleh berhimpitan. Misalnya, tidak boleh ada rentang [0,1] (0 S/D 1 TAHUN) dan juga rentang [1,2] (1 S/D 2 TAHUN) , karena yg berumur "persis 1 tahun s/d 2 tahun kurang sehari" akan tampil di kedua rentang.

Yang boleh adalah rentang seperti:

1. [0,1], [2,3]
2. [0,0], [1,3], [4,5]

Jadi dalam migrasi, tandakan rentang lama yg berhimpitan sebagai rentang invalid dan perlu diubah.

**Comment by andifahruddinakas** [comment]
> @andifahruddinakas saat ini saya coba di berputar tidak bisa membuat rentang hanya satu umur, misalnya hanya 3 tahun saja. Yaitu tidak bisa mengisi rentang [3,3]. Kalau bisa masukkan itu, saya kira sudah cukup. Bisa saja tampilkan rentang ini sebagai "3 S/D 3 TAHUN", tapi mungkin lebih jelas kalau ditampilkan sebagai "3 TAHUN" saja. Dan akan hanya menampilkan yg umurmnya persis 3 tahun s/d 4 tahun kurang sehari.
> 
> Sedangkan rentang [1,2], seperti yg sekarang berlaku, akan menampilkan yg umurnya persis 1 tahun s/d 3 tahun kurang sehari.
> 
> Kemudian, terapkan aturan supaya rentang tidak boleh berhimpitan. Misalnya, tidak boleh ada rentang [0,1] (0 S/D 1 TAHUN) dan juga rentang [1,2] (1 S/D 2 TAHUN) , karena yg berumur "persis 1 tahun s/d 2 tahun kurang sehari" akan tampil di kedua rentang.
> 
> Yang boleh adalah rentang seperti:
> 
> 1. [0,1], [2,3]
> 2. [0,0], [1,3], [4,5]
> 
> Jadi dalam migrasi, tandakan rentang lama yg berhimpitan sebagai rentang invalid dan perlu diubah.

untuk data bawaan rentang umurnya sudah sesuai.
![image](https://github.com/user-attachments/assets/f903ca5f-22c9-420b-b933-8ff9e0df8189)

berarti yang diperbaiki pengkondisian rentangnya dan validasi agar tidak ada rentang yang berhimpitan.

Jadi, format yang diissue ini tidak bisa diterapkan.
![image](https://github.com/user-attachments/assets/50dca545-1705-4163-8e9b-0c46edd95019)

**Comment by balongbesuk** [comment]
format contohnya sudah salah, umur 0 - 1 tahun, 1 - 2 tahun, umur 1 tahunnya sudah terhitung 2x,

rentan umur sudah benar d buat dinamis karena tiap dinas membutuhkan format rentan yang berbeda beda
