### ISSUE TITLE
Bug/error: jumlah karakter tautan luar dibatasi, sehingga tidak bisa memproses ke link tujuan

### ISSUE THREAD

**Issue by mah-mudi** [OpenSID/OpenSID#8285]
### Jelaskan error yg dialami

jumlah karakter tautan luar dibatasi, sehingga tidak bisa memproses ke link tujuan

### Cara untuk mereplikasi errornya

1. Admin Web
2. Teks Berjalan
3. Isi Tautan Luar

### Hasil yg diharapkan

jumlah karakter tautan luar tidak dibatasi, sehingga bisa memproses ke link tujuan

misal 
https://desaleran.gresikkab.go.id/index.php/artikel/2023/8/28/membanggakan-pemerintah-desa-leran-sabet-juara-1-lomba-desa-digital-nawakarsa-award-kabupaten-gresik-tahun-2023

tp yg hanya bisa dipastekan hanya
https://desaleran.gresikkab.go.id/index.php/artikel/2023/8/28/membanggakan-pemerintah-desa-leran-sabet-juara-1-lomba-desa-digital-nawakarsa-award-kabu

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/69f3b1b5-c5ea-4ca0-8fc7-4a1da452ad33)
![image](https://github.com/user-attachments/assets/741257fd-4dbd-4580-9a70-d461d4bc7106)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

24.07.02 premium

### Tema Yang Digunakan

silir

### Informasi tambahan

-

**Comment by eddieridwan** [comment]
@mah-mudi url panjang bisa dipersingkat menggunakan pemendek URL, seperti di https://s.id, pemendek URL buatan Indonesia.

**Comment by mah-mudi** [comment]
@eddieridwan menurut kebiasaan pengguna biasanya tinggal copas.

barangkali bisa dibatasi 500 karakter :-)

**Comment by eddieridwan** [comment]
@andifahruddinakas @vickyrolanda jika url melebihi batas, beri notifikasi menyarankan menggunakan penyingkat URL, beri referensi ke https://s.id, dan isi kembali menggunakan url yg sdh dipersingkat.

**Comment by andifahruddinakas** [comment]
Tambahkan : 
- [ ] validasi forntend, tambahkan informasi jika penjang karakter melebihi. Misalkan : **Silahkan menyingkat URL menggunakan https://s.id/ atau sejenisnya.**
![image](https://github.com/user-attachments/assets/186a4438-b9d8-4486-8b10-b7c3ebe9a5ef)

- [ ] tambahkan validasi max input karakter : gunakan panjang karakter yang sama dengan panjang kolom pada database.
![image](https://github.com/user-attachments/assets/45348186-6bd9-42e5-8373-bfa1ca7a6501)

- [ ] sebaiknya penerapan ini dilakukan secara menyeluruh baik terkait validasi url (terkait point 1-3) maupun validasi lainnya (terkait point 3).
