### ISSUE TITLE
Bug/error: Cetak buku pemerintahan nama pamong ganda

### ISSUE THREAD

**Issue by ilhamwahyu-ni** [OpenSID/OpenSID#8287]
### Jelaskan error yg dialami

-

### Cara untuk mereplikasi errornya

![image](https://github.com/user-attachments/assets/0ebf464a-0fbc-4332-87fd-0d334c20d5dc)

### Hasil yg diharapkan

normal

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/15e5f886-1cea-48af-87fa-98a415538a37)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

 2408.0.0

**Comment by andifahruddinakas** [comment]
mas @ilhamwahyu-ni, pada bagian penanda tangan bisa dipilih dan disesuaikan masing2 pengguna. Sedangkan bagian mengetahui otomatis terisi adalah kepala desa.

Bisa dijelaskan seperti apa yang diharapkan bagian penanda tangan ini.
- apakah modelnya fix (otomatis mengetahui adalah kades, dan penandatangan adalah sekdes). Contoh: bumindes umum.
- apakah modelnya bisa disesuaikan. contoh: wilayah administratif.

**Comment by ilhamwahyu-ni** [comment]
baik mas, versi sebelumnya default otomatis seekretaris,,

 bearti aman..🙏
