### ISSUE TITLE
Bug/error: Tombol "Mengembalikan Surat" pada surat dinas tidak seragam dengan surat biasa

### ISSUE THREAD

**Issue by ilhamwahyu-ni** [OpenSID/OpenSID#8289]
### Jelaskan error yg dialami

pada surat biasa "mengembalikan surat" ada di sini...

![image](https://github.com/user-attachments/assets/ee47d8a0-42e1-4908-82eb-35b7f6f42bb1)

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

seragamkan saja, 

supaya tidak banyak pertanyaan dari user

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/135139ae-8eba-4cf1-aad5-0cb68bfd3eb9)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

 2408.0.0

**Comment by agungsugiarto** [comment]
mas @andifahruddinakas ini fitur sepertinya bukan bug,
