### ISSUE TITLE
Bug/error: Surat Beda identitas KIS isian "Keterangan" tidak terekap Pada arsip

### ISSUE THREAD

**Issue by ilhamwahyu-ni** [OpenSID/OpenSID#8291]
### Jelaskan error yg dialami

-

### Cara untuk mereplikasi errornya

🔄️ kembalikan surat master

![image](https://github.com/user-attachments/assets/60e66c66-20f9-49ca-9e92-6c2b01c580d0)

### Hasil yg diharapkan

normal

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/56da0045-87f0-4e41-abcc-ed673dfaa90c)

![image](https://github.com/user-attachments/assets/649980c9-0ce2-4400-8427-3099c6fa47d5)

![image](https://github.com/user-attachments/assets/f6cd515f-9d25-46f4-8083-0c7ca236a428)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

 2408.0.0

**Comment by andifahruddinakas** [comment]
mas @ilhamwahyu-ni, untuk keterangan sudah tidak digunakan lg pada TinyMCE karena data form isian disimpan di kolom yang lain. Kolom tsb digunakan untuk menampung data sebelumnya yang diperlukan oleh surat RTF. Saat ini kolom tersebut tidak dihilangkan karena kemungkinan masih ada arsip dari surat RTF pada masing2 desa.

**Comment by andifahruddinakas** [comment]
Terkati issue https://github.com/OpenSID/OpenSID/issues/8268
