### ISSUE TITLE
Bug/error: 404 akse web halaman kelompok/lembaga

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#8292]
### Jelaskan error yg dialami

Terjadi gagal akses halaman kelompok/lembaga setelah ubah data pada halaman admin dengan yang diakses menggunakan url yang sama.

### Cara untuk mereplikasi errornya

1. Siapkan terlebih dahulu halaman yang akan di cek pada halaman web. Bisa buat 1 menu pada salah 1 kelompok.
![image](https://github.com/user-attachments/assets/9dfb3abb-361f-4426-bc32-b995d97f849f)

2. Lakukan ubah data pada kelompok tsb
3. Akses kembli url tsb

### Hasil yg diharapkan

Normal

### Tangkapan layar dan log error

Sebelum Ubah Data
![image](https://github.com/user-attachments/assets/3f0072af-8652-421f-93da-e7eb1f34a39a)

Setelah Ubah Data
![image](https://github.com/user-attachments/assets/2592ab5d-bfd8-4ce6-926c-dbe28daffe25)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v2408.0.0

### Tema Yang Digunakan

bawaan

### Informasi tambahan

Dari hasil pengecekan, hal tsb disebabkan karena perubahan slug setelah memperbarui data.

Seharusnya, untuk slug hanya dibuat sekali saja tanpa diubah walaupun data lain diubah (dan refrensi slug).

Bisa gunakan Cviebrock\EloquentSluggable\Sluggable, contoh penerapannya ada dimodul Suplemen.

Perlu diperhatikan, slug harus unique. Namun karena kelompok dan lembaga menggunakan tabel yang sama, maka unique tsb dicek berdasarkan masing2 modul. Jadi slug bisa sama asalkan beda modul.

**Comment by andifahruddinakas** [comment]
Cek jg bagian no_sk tidak berubah saat edit, cek

**Comment by ariandii** [comment]
info tambahan:

edit pertama dan simpan web menjadi 404 karena slug berubah,
namun ketika edit kedua kalinya dan simpan web normal kembali dengan slug pertama. reload
