### ISSUE TITLE
Bug/error: Edit surat "tinjau surat eror" dan "kop surat ganda" 

### ISSUE THREAD

**Issue by ilhamwahyu-ni** [OpenSID/OpenSID#8293]
### Jelaskan error yg dialami

saat edit surat >> ketika di tinjau maka akan muncul eror..

setelah itu cek kembali arsip maka edit surat => konsep menjadi ganda

### Cara untuk mereplikasi errornya

saya buat surat keterangan tidak mampu ...
kemudian di edit

![image](https://github.com/user-attachments/assets/0bca50eb-53c4-46a0-a713-e3c3cc729f99)

lakukan tinjau

![image](https://github.com/user-attachments/assets/b3878753-c129-483a-8c9b-316b6945ed5f)

![image](https://github.com/user-attachments/assets/6f5b03b0-5eef-45cb-96a2-23ec8a7999c4)

### Hasil yg diharapkan

normal

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/fef0ab49-d5f9-4f50-b1ea-e89ce5b61163)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

 2408.0.0

### Informasi tambahan

log_____________________________

Html2Pdf Error [2]
Unable to get the size of the image [/home/batipua1/public_html/home/batipua1/public_html/desa/logo/1716173433_Desain_tanpa_judul_20240520_094938_0000.png] File: /home/batipua1/public_html/vendor/spipu/html2pdf/src/Html2Pdf.php Line: 1526 Image Src: /home/batipua1/public_html/home/batipua1/public_html/desa/logo/1716173433_Desain_tanpa_judul_20240520_094938_0000.png

**Comment by andifahruddinakas** [comment]
mas @ilhamwahyu-ni, bisa sertakan template json nya. karena sy coba aman, seprtinya haln ini terjadi karena error ditempalate saat ubah, sehinga ketika error akan disimpan sebagai konsep.

**Comment by ilhamwahyu-ni** [comment]
ini mas,,
[template_surat_tinymce_02_08_2024.json](https://github.com/user-attachments/files/16464847/template_surat_tinymce_02_08_2024.json)

saya juga sudah pastikan bahwa sudah mengembalikan surat ke default sistim mas..

**Comment by andifahruddinakas** [comment]
mas @habibie11, untuk ubah surat yang pernah dicetak. Jika gagal jangan disimpan sebagai konsep.
