### ISSUE TITLE
Bug/error: openstreetmap tidak tampil pada menu peta dan peta wilaya desa

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8295]
### Jelaskan error yg dialami

openstreetmap tidak tampil pada menu peta dan peta wilaya desa

### Cara untuk mereplikasi errornya

1. klik menu peta
2. tampilan openstreetmap tidak tampil

### Hasil yg diharapkan

dapat menampilkan openstreetmap 

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/dabedcbd-79a1-44da-9029-f7e92f7582ec)

![image](https://github.com/user-attachments/assets/e13c3dbc-c1d0-47c5-b41f-2ded0d373ba9)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Versi 2408.0.0-premium

**Comment by andifahruddinakas** [comment]
mas @rgrahardi, biasa terjadi : 

- [ ] salah input token,
- [ ] salah masukkan peta wilayah.

bisa kirimkan backup databasenya untuk dicek

**Comment by wahyabiantara** [comment]
Secara default token OpenStreet Map nya kosong. Sehingga perlu dipastikan token sudah dimasukan melalui menu Pemetaan > Peta > Settings ( icon gear pojok kanan atas)

**Comment by scqolbu24** [comment]
mas @andifahruddinakas dan mas @rgrahardi ini dikarenakan pada path ketika migrasi tidak valid sehingga akan muncul blank putih. Terjadi pada proses penggabungan database di satu database gabungan. 

solusinya adalah hapus cache pada pengaturan->info sistem-> optimasi

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melalui pr https://github.com/OpenSID/premium/pull/3994

**Comment by alit2310** [comment]
kami juga mengalami maslah seperti itu, saat mengakses menu peta loading dan stuck
mohon bantuannya
![Screenshot 2024-08-21 142134](https://github.com/user-attachments/assets/63338258-78cb-4a28-b1cb-f0a13a4dd803)
