### ISSUE TITLE
Bug/error: Permohonan Surat Admin Error 500

### ISSUE THREAD

**Issue by sirepson** [OpenSID/OpenSID#8296]
### Jelaskan error yg dialami

Saya sudah memperbarui OpenSID ke v2408.0.0 namun tautan Permohonan Surat Admin masih error 500, bug tersebut juga terjadi di tautan demo OpenSID https://demosid.opendesa.id/permohonan_surat_admin

### Cara untuk mereplikasi errornya

1. Pergi ke panel Admin
2. Klik tombol dengan icon surat diheader pojok kanan

### Hasil yg diharapkan

Dapat diakses

### Tangkapan layar dan log error

<img width="1822" alt="Screenshot 2024-08-02 at 13 10 34" src="https://github.com/user-attachments/assets/0d3dccac-767f-4d4a-a8cb-b8b04a79e426">
<img width="1822" alt="Screenshot 2024-08-02 at 13 15 44" src="https://github.com/user-attachments/assets/734b2d84-7a15-40f3-b4fc-bdd22d06718f">
<img width="1822" alt="Screenshot 2024-08-02 at 13 10 34" src="https://github.com/user-attachments/assets/e7a0f49c-88cf-4b71-86c7-017acbbac80e">

### Rilis Versi OpenSID

Rilis Umum

### Versi OpenSID

2408.0.0

### Tema Yang Digunakan

Silir

**Comment by andifahruddinakas** [comment]
pak @sirepson, bisa gunakan branch https://github.com/OpenSID/OpenSID/tree/dev
