### ISSUE TITLE
Permintaan fitur: ketika klik menu yang belum dibuat tampil halaman peberitahuan

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8297]
### Apa kekurangan yg ingin diatasi?

Masalah di bawah terus berulang 

Yaitu, pengguna berasumsi adanya menu/tombol default yg disediakan tema padahal menunya belum dibuat, sehingga menimbulkan error 404.

### Jelaskan solusi yg diinginkan

Solusi 
jika diklik atau akses menu yang belum dibuat tampilkan pemberitahuan menu belum dibuat dan tautan ke panduan pembuatan menu

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

Versi 2409.0.0-premium

**Comment by andifahruddinakas** [comment]
Duplicate of https://github.com/OpenSID/OpenSID/issues/8294

lengkapi di issue itu
