### ISSUE TITLE
Bug/error: Tautan Kirim WhatsApp Error 500 Setelah Pembuatan Pin Layanan Mandiri

### ISSUE THREAD

**Issue by sirepson** [OpenSID/OpenSID#8298]
### Jelaskan error yg dialami

Setelah membuat Penggguna, akan muncul tombol WhatsApp untuk mengirimkan detail pin layanan mandiri, namun saat klik tombol tersebut terjadi error 500

### Cara untuk mereplikasi errornya

1. Pergi ke halaman pendaftar layanan mandiri (Cth: https://demosid.opendesa.id/mandiri)
2. Tambah pengguna, cari penduduk, dan klik tombol simpan
3. Akan tampil tombol kirim WhatsApp

Fungsi tombol kirim WhatsApp berjalan normal ketika reset pin

### Hasil yg diharapkan

Dapat digunakan

### Tangkapan layar dan log error

Severity: error --> Exception: Call to a member function toArray() on null /home/NamaDesa/public_html/donjo-app/controllers/Mandiri.php 303

<img width="624" alt="Screenshot 2024-08-02 at 16 10 28" src="https://github.com/user-attachments/assets/d739bb4b-db39-48a1-b40c-3dac6627db1d">

<img width="1822" alt="Screenshot 2024-08-02 at 16 24 52" src="https://github.com/user-attachments/assets/e837570a-0d7b-4c69-90b0-eec92e252ed5">

<img width="1057" alt="Screenshot 2024-08-02 at 15 59 05" src="https://github.com/user-attachments/assets/1ec953a0-f47e-4368-95ed-1ff7c3c756d5">

### Rilis Versi OpenSID

Rilis Umum

### Versi OpenSID

2408.0.0

### Tema Yang Digunakan

Silir

**Comment by andifahruddinakas** [comment]
mas @sirepson, sy coba bisa

![image](https://github.com/user-attachments/assets/242bfffb-44b1-4e48-adc2-8ab149e77c26)

mungkin bisa disertakan log errornya
