### ISSUE TITLE
Bug/error: notif Pesan Komentar "belum lengkap", => notif komentar artikel

### ISSUE THREAD

**Issue by ilhamwahyu-ni** [OpenSID/OpenSID#8299]
### Jelaskan error yg dialami

saat komentari pesan belum lengkap dari warga yang membuat surat, notif pesan komentar yang ada di admin jadi aktif

### Cara untuk mereplikasi errornya

kometari pesan belum lengkap

![image](https://github.com/user-attachments/assets/9b2af9ca-0309-4387-91d5-72c4ca818f9e)

### Hasil yg diharapkan

normal

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/4cd6f219-4ca2-4fee-b1d5-5c42c81d8302)
![image](https://github.com/user-attachments/assets/26ba2722-ec48-4ce2-804b-b5df41240d78)

![image](https://github.com/user-attachments/assets/ab7c9597-e1f8-4294-83a8-dd1b172be6bc)
![image](https://github.com/user-attachments/assets/4b21e4c2-8fd6-4314-b14f-d31ec0a5c911)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

 2408.0.0

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melalui pr https://github.com/OpenSID/premium/pull/3993
