### ISSUE TITLE
Bug/error: DataTables warning: table id=tabeldata - Ajax error

### ISSUE THREAD

**Issue by Mangapu** [OpenSID/OpenSID#8300]
### Jelaskan error yg dialami

Error terjadi saat akses Layanan Mandiri, yaitu saat pilih menu "Surat" dan "Bantuan"

### Cara untuk mereplikasi errornya

![1](https://github.com/user-attachments/assets/f9e84cc8-baf2-4eed-b2a4-670a14baf8ab)

### Hasil yg diharapkan

Normal

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/63b6ca2e-1b0a-4c95-8766-721e1cb5e824)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2407.0.3

**Comment by andifahruddinakas** [comment]
mas @Mangapu, @rgrahardi, sy coba duplikasi tidak menemukan masalah tsb.
![image](https://github.com/user-attachments/assets/2d9edfdd-b4dc-4e16-a457-8e2070c43e7b)

Bisa lakukan update versi ke 2408.0.0 terlebih dahulu

**Comment by Mangapu** [comment]
Baik kak
