### ISSUE TITLE
Permintaan fitur: Belum adanya fitur edit tanggapan pengaduan yang selesai diproses

### ISSUE THREAD

**Issue by mah-mudi** [OpenSID/OpenSID#8302]
### Apa kekurangan yg ingin diatasi?

Belum adanya fitur edit tanggapan pengaduan yang selesai diproses
![image](https://github.com/user-attachments/assets/b7d57b32-098d-4da0-9cbd-438f6e413f7e)

### Jelaskan solusi yg diinginkan

Adanya fitur edit tanggapan pengaduan yang selesai diproses

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

24.09 premium

### Informasi tambahan

-

**Comment by andifahruddinakas** [comment]
mas @mah-mudi, alur proses seperti ini sebaiknya tidak diterapkan agar yang di isi oleh warga tetap sama (murni). Namun disisi lain, sudah disediakan tombol hapus jika terdapat hal2 yang kurang berkenan untuk ditampilkan.

Alur proses ini sama halnya dengan https://www.lapor.go.id/
