### ISSUE TITLE
Permintaan fitur: Belum adanya fitur up down pada pengaturan menu dan sub menu

### ISSUE THREAD

**Issue by mah-mudi** [OpenSID/OpenSID#8303]
### Apa kekurangan yg ingin diatasi?

Belum adanya fitur up down pada pengaturan menu dan sub menu
![image](https://github.com/user-attachments/assets/1073d122-369e-47c7-bb1c-00018a784cc0)

### Jelaskan solusi yg diinginkan

Adanya fitur up down pada pengaturan menu dan sub menu, untuk mempercepat pengaturan menu

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

24.09 premium

### Informasi tambahan

-

**Comment by andifahruddinakas** [comment]
pak @mah-mudi, untuk melakukan perubahan posisi, bisa lakukan dengan menggeser menu tsb pada posisi yg diinginkan.

**Comment by eddieridwan** [comment]
@rgrahardi apakah sudah ada panduannya?
