### ISSUE TITLE
Judul Desa Salah :error 

### ISSUE THREAD

**Issue by purwoasri** [OpenSID/OpenSID#8304]
### Jelaskan error yg dialami

Judul Desa yang Benar : Desa Purwoasri Kec. Kebonagung, Kab. PACITAN
Judul Salah (saat ini) : Desa Purwosari Kec. Kebonagung, Kab. PACITAN

### Cara untuk mereplikasi errornya

1. Info Desa
2. Identitas Desa
3. Ubah Data Desa
4. Nama Desa
5. Tertulis Purwosari , Purwoasri Kec. Kebonagung, Kab. Pacitan TIDAK ADA

### Hasil yg diharapkan

Nama Desa diedit, disesuaikan dengan nama desa secara administratif

### Tangkapan layar dan log error

<img width="508" alt="Nama Desa Salah" src="https://github.com/user-attachments/assets/b659eb78-0c22-4f0e-b1f1-7c400f268c72">

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Rilis umum v2312.0.0

**Comment by ariandii** [comment]
Kirimkan SK Pengangkatan Kepala Desa oleh Bupati sebagai bentuk Validasi penyesuaian nama desa yang benar,
SK bisa dikirim ke Telegram @ariandi
