### ISSUE TITLE
Bug/error: Default Tampil Peta Wilayah tidak tampil di web

### ISSUE THREAD

**Issue by pujocahyono** [OpenSID/OpenSID#8305]
### Jelaskan error yg dialami

setelah pilih pengaturan Default Tampil Peta Wilayah. hasil di web tidak muncul
![Cuplikan layar 2024-08-06 073323](https://github.com/user-attachments/assets/c8d65ed3-f439-4dda-b9d5-25031757bb53)

![Cuplikan layar 2024-08-06 073341](https://github.com/user-attachments/assets/1ef65815-8ed9-4ae4-840b-ea2e400fc001)

### Cara untuk mereplikasi errornya

1. peta
2. pengaturan
3. pilih Default Tampil Peta Wilayah

### Hasil yg diharapkan

sesuai dengan pengaturan. akan muncul d web

### Tangkapan layar dan log error

seperti di atas

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2408.0.0

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melalui pr https://github.com/OpenSID/premium/pull/3992
