### ISSUE TITLE
Bug/error: Tidak Bisa Masuk Home di Insert File

### ISSUE THREAD

**Issue by mah-mudi** [OpenSID/OpenSID#8308]
### Jelaskan error yg dialami

Tidak Bisa Masuk Home di Insert File

### Cara untuk mereplikasi errornya

1. admin web
2. artikel-buat artikel
3. insert file

### Hasil yg diharapkan

Bisa Masuk Home di Insert File

### Tangkapan layar dan log error

[screen-capture (14).webm](https://github.com/user-attachments/assets/479c1643-b097-4776-a565-6baaff7bac6d)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

24.08 premium

### Tema Yang Digunakan

silir

### Informasi tambahan

-

**Comment by agungsugiarto** [comment]
Pak @mah-mudi folder home mana yg di maksud?, default folder yg sekarang berada di `desa/upload/media` untuk artikel

**Comment by mah-mudi** [comment]
![image](https://github.com/user-attachments/assets/cd4daf25-8964-461d-b4a8-0a083a863e34)

yang gambar rumah pak

**Comment by andifahruddinakas** [comment]
mas @mah-mudi, perlu diketuhui. untuk folder yg ditampilkan pada RFM hanya sampai folder desa/upload/media saja.

**Comment by mah-mudi** [comment]
@andifahruddinakas  padahal banyak media yang sudah ada foldernya tersendiri, jd ketika nambah folder bisa tapi g bisa tampil.

kenapa tdk diatur seperti sedia kala?
kalau dulu enak, bisa buat folder lagi, masing-masing folder bisa dikasih foto

**Comment by mah-mudi** [comment]
@andifahruddinakas   bisa cek lagi divideo ini
[screen-capture (15).webm](https://github.com/user-attachments/assets/7f49bbb6-1fdd-4c66-9b8f-cdc9202c3673)
