### ISSUE TITLE
Tambahkan Field No HP & Nama PIC Perangkat Desa

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#8311]
![image](https://github.com/user-attachments/assets/7238e33b-bc73-45a5-aabe-7c7c67acd9c0)

Tambahkan menu diatas yang sifatnya required sebagai Kontak Pemberitahuan, kontak ini akan di sinkronkan dengan data pelanggan yang ada pada layanan sehingga jika diOpenSID maka akan terpengaruh pada Layanan. 

- [ ] Tambahkan field baru di identitas desa sebagai kontak informasi yang bersifat wajib diisi 
- [ ] Sambungkan dengan kontak perangkat desa pada layanan

**Comment by pandigresik** [comment]
> Tambahkan menu diatas yang sifatnya required sebagai Kontak Pemberitahuan, kontak ini akan di sinkronkan dengan data pelanggan yang ada pada layanan sehingga jika diOpenSID maka akan terpengaruh pada Layanan.
> 
> * [ ]  Tambahkan field baru di identitas desa sebagai kontak informasi yang bersifat wajib diisi
> * [ ]  Sambungkan dengan kontak perangkat desa pada layanan

Datanya dikirim ke layanan atau pantau ?
