### ISSUE TITLE
Bug/error: Tidak Bisa Upgrade ke 2408

### ISSUE THREAD

**Issue by argasurya** [OpenSID/OpenSID#8314]
### Jelaskan error yg dialami

Versi terakhir yang saya gunakan adalah 2406, setelah itu upgrade ke 2407, hari ini saya coba melakukan upgrade ke 2408 dan terjadi error. Dengan peringatan minimal versi 2407.
Di versi 2407 saya coba cek di menu aplikasi, pada informasi "Current Version" ternyata masih versi 2406

### Cara untuk mereplikasi errornya

Dari versi 2407 upgrade ke versi 2408

### Hasil yg diharapkan

Lancar upgrade dari 2407 ke 2408

### Tangkapan layar dan log error

1. Versi yang saya gunakan
![Screen Shot 2024-08-06 at 12 18 45 PM](https://github.com/user-attachments/assets/02a2bd9c-ad8f-4ee1-bf8c-6c7437d67557)

2. Current Version berbeda
![Screen Shot 2024-08-06 at 12 18 25 PM](https://github.com/user-attachments/assets/dced9c20-9ebd-4425-a677-a5678626853d)

3. Setelah Upgrade ke 2408
![Screen Shot 2024-08-06 at 12 20 54 PM](https://github.com/user-attachments/assets/b54b5278-cb50-4e8c-82e6-2b8c0c7fded4)

### Rilis Versi OpenSID

Rilis Umum

### Versi OpenSID

v2407.0.0

### Tema Yang Digunakan

esensi

**Comment by andifahruddinakas** [comment]
Mas @, bisa tambahkan solusinya di forum

**Comment by rgrahardi** [comment]
mas @andifahruddinakas berikut linknya https://forum.opendesa.id/d/341-error-ketika-update-dari-2407-versi-umum-ke-2408-versi-umum
