### ISSUE TITLE
Bug/error: Fungsi Center artikel pada gambar yang diambil dari source link gambar, tidak berfungsi.

### ISSUE THREAD

**Issue by mah-mudi** [OpenSID/OpenSID#8319]
### Jelaskan error yg dialami

Fungsi Center artikel pada gambar yang diambil dari source link gambar, tidak berfungsi.

### Cara untuk mereplikasi errornya

1. artikel
2. ambil gambar dari dari source link gambar tujuan
3. atur center
4. center tdk berfungsi

### Hasil yg diharapkan

Fungsi Center artikel pada gambar yang diambil dari source link gambar, dapat berfungsi sebagaimana mestinya.

### Tangkapan layar dan log error

[screen-capture (16).webm](https://github.com/user-attachments/assets/5b5932e1-ec70-4571-8714-51500e67ad1c)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

24.08 premium

### Tema Yang Digunakan

silir

### Informasi tambahan

-

**Comment by andifahruddinakas** [comment]
pak @mah-mudi, untuk laporan terkait tema, usahakan menggunakan tema bawaan.

**Comment by mah-mudi** [comment]
oke
