### ISSUE TITLE
Bug/error: penulisan nama produk di menu lapak tibak bisa pakai -

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#8320]
### Jelaskan error yg dialami

penulisan nama produk di menu lapak tibak bisa pakai -

### Cara untuk mereplikasi errornya

penulisan nama produk di menu lapak tibak bisa pakai -

### Hasil yg diharapkan

penulisan nama produk bisa pakai -

### Tangkapan layar dan log error

penulisan nama produk di menu lapak tibak bisa pakai -

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

24.08.0.0

### Tema Yang Digunakan

Denava

**Comment by habibie11** [comment]
saya coba replikasi disini bisa pakai -, bisa diinfokan replikasinya seperti apa pak @MUHAMMADRANGSEL @andifahruddinakas 
<img width="329" alt="image" src="https://github.com/user-attachments/assets/8ed05b30-203e-4a89-a891-0efe80ca61d0">

**Comment by MUHAMMADRANGSEL** [comment]
Di kategori produk

Pada tanggal Kam, 8 Agu 2024 18.50, Habibie ***@***.***>
menulis:
