### ISSUE TITLE
Bug/error: sebaiknya tombol ubah dan hapus dilayanan mandiri dihilangkan

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#8322]
### Jelaskan error yg dialami

masuk ke layanan mandiri klik dokumen maka akan tersedia tombol ubah, hapus dan download
untuk menghindari adanya penghapuasan atau perubahan dokumen yang sudah diupload oleh operator desa maka sebaiknya tombol ubah dan hapus di tiadakan
![photo_6168121556375551152_y](https://github.com/user-attachments/assets/3e965eee-ebeb-419c-bad7-b1e7e4c50f17)

### Cara untuk mereplikasi errornya

masuk ke layanan mandiri klik dokumen maka akan tersedia tombol ubah, hapus dan download
untuk menghindari adanya penghapuasan atau perubahan dokumen yang sudah diupload oleh operator desa maka sebaiknya tombol ubah dan hapus di tiadakan
![photo_6168121556375551152_y](https://github.com/user-attachments/assets/3e965eee-ebeb-419c-bad7-b1e7e4c50f17)

### Hasil yg diharapkan

diharapan tombol yang ada tombol view dan download seperti yang ada di menu kependudukan/identitas/kepemikan dokumen
![photo_6168121556375551153_y](https://github.com/user-attachments/assets/37c3ca28-067d-468b-bb7d-43a59dd4e6cc)

### Tangkapan layar dan log error

![photo_6168121556375551152_y](https://github.com/user-attachments/assets/d5dc22b3-defb-4ef9-bd85-2b6b0745516e)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

24.08.0.0

### Tema Yang Digunakan

Denava

**Comment by andifahruddinakas** [comment]
Pak @MUHAMMADRANGSEL, untuk alur yang diterapkan dari dulu sampai saat ini. Dokumen bisa diubah oleh pengguna, atau dibatasi oleh admin. lewat dokument penduduk.

![image](https://github.com/user-attachments/assets/1cde5148-1430-40d7-af96-ceb709fb38fb)

**Comment by MUHAMMADRANGSEL** [comment]
Siap bang, cuma perlu ditambahkan tombol view

Pada tanggal Kam, 8 Agu 2024 16.26, Andi Fahruddin Akas <
***@***.***> menulis:
