### ISSUE TITLE
Bug/error: klik dokumen di layanan mandiri 

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#8323]
### Jelaskan error yg dialami

https://github.com/user-attachments/assets/9d0938e1-41e1-4c8d-a402-05b2563b8c79

### Cara untuk mereplikasi errornya

https://github.com/user-attachments/assets/608f6371-f090-43c2-92c3-115682c89d9a

### Hasil yg diharapkan

normal

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

24.08.0.0

### Tema Yang Digunakan

Denava

**Comment by andifahruddinakas** [comment]
pak @MUHAMMADRANGSEL, sy coba ini aman.
![image](https://github.com/user-attachments/assets/7d06d62a-e9db-4f2b-8b93-bec8e0ffde3c)

mungkin jika ada log nya bisa disertakan
