### ISSUE TITLE
Bug/error: kEPERLUAN DI ARSIP SURAT TERISI -

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#8324]
### Jelaskan error yg dialami

KETIKA CETAK SURAT DIARSIP LAYANAN UNTUK KETERANGAN TERISI - SEHARUSNYA TERISI SESUAI DENGAN YANG DIISI DI FORM KETERANGAN/KEPERLUAN
![image](https://github.com/user-attachments/assets/083cfd1a-ecaf-4bc7-9986-046876939acd)

### Cara untuk mereplikasi errornya

KETIKA CETAK SURAT DIARSIP LAYANAN UNTUK KETERANGAN TERISI - SEHARUSNYA TERISI SESUAI DENGAN YANG DIISI DI FORM KETERANGAN/KEPERLUAN
![image](https://github.com/user-attachments/assets/083cfd1a-ecaf-4bc7-9986-046876939acd)

### Hasil yg diharapkan

KETERANGAN TERISI SEPERTI VERSI 24.07.0

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/083cfd1a-ecaf-4bc7-9986-046876939acd)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

24.08.0.0

### Tema Yang Digunakan

Denava

**Comment by andifahruddinakas** [comment]
pak @MUHAMMADRANGSEL, untuk kolom keterangan ini sifatnya statis dan digunakan untuk jenis surat RTF diversi sebelumnya. Untuk tinymce kolom tsb tidak digunakan, karena dipindahkan ke kolom form_isian.

**Comment by MUHAMMADRANGSEL** [comment]
Kedepannya form keterangan yang diarsip layanan tidak berfungsi lagi
begitulah...?

Pada tanggal Kam, 8 Agu 2024 15.45, Andi Fahruddin Akas <
***@***.***> menulis:

**Comment by andifahruddinakas** [comment]
Disesuaikan melalui commit https://github.com/OpenSID/premium/commit/6ec65269b3a30241c7b455fd2088a3bd9f5af80f
