### ISSUE TITLE
Bug/error: isi dari semua lampiran surat nikah hilang setelah selesai verifikator oleh operator

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8327]
### Jelaskan error yg dialami

isi dari semua lampiran surat nikah hilang setelah selesai verifikator oleh operator, ini terjadi pada surat yang menggunakan TTE

### Cara untuk mereplikasi errornya

1. cetak surat nikah
2. verikator oleh admin sebelum di kirim ke kades

### Hasil yg diharapkan

lampiran surat Nikah bisa normal lagi pada pengguna TTE 

### Tangkapan layar dan log error

**1. Lampiran Surat nikah sebelum di verifikasi oleh verikator**

![image](https://github.com/user-attachments/assets/d0700bce-35c2-4c28-bcd2-3bd62eab5f90)

**2. Lampiran Surat Nikah sesudah verifikasi**

![image](https://github.com/user-attachments/assets/6dbbb62c-73d9-48f2-9563-bfe7f79d3c98)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Versi 2408.0.0-premium

**Comment by andifahruddinakas** [comment]
mas @rgrahardi, cek struktur tabelnya, pada tabel log_surat apakah ada kolom **input**?

**Comment by andifahruddinakas** [comment]
karena sama issuenya dengan https://github.com/OpenSID/OpenSID/issues/7788

**Comment by rgrahardi** [comment]
mohon bantuannya mas @scqolbu24 mas @apidong untuk pengecekan di database pengguna siapPakai juga mengalami desa Sukosari

**Comment by langonsari** [comment]
> karena sama issuenya dengan #7788

betul pak andi memang hampir mirip ini dengan issue ini, 
di issue #7788 baru close untuk yang penulisan di Saksinya sedangkan untuk Data yang hilang/menjadi ("-") setelah di Verifikasi untuk pengguna Modul TTE Aktif ini masih belum terselesaikan sehingga bagi Pengguna dengan Modul TTE aktif masih terjadi Bug Data yang hilang/menjadi ("-") untuk Lampiran F-2.30 untuk Suket Keterangan Kematian dan Lampiran N-1,N-2,N-4,N-5,N-6,SPS,SWN untuk Surat Keterangan Nikah setelah diverifikasi oleh Operator.

**Comment by langonsari** [comment]
sebagai Informasi tambahan setelah replikasi pengaturan di source Lampiran F.2-30:
![image](https://github.com/user-attachments/assets/db2128a8-6004-4caf-a073-48879e85883e)
hasilnya:
![image](https://github.com/user-attachments/assets/92d32c17-e054-4a4a-8427-ef27da3c43fd)

setelah di ubah Data tetap ada setelah di verifikasi maupun di TTE oleh Kepala Desa:
![image](https://github.com/user-attachments/assets/fa4bbf76-82c8-4db8-b90c-d92f9300a094)
hasilnya:
![image](https://github.com/user-attachments/assets/0569d450-2163-46cd-bf8d-568c429dbede)
