### ISSUE TITLE
Bug/error: pengaturan surat pada kop surat menggunakan logo gambar ceta surat error

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8328]
### Jelaskan error yg dialami

pada kop surat menggunakan logo gambar dari file manager di simpan berhasil, ketika surat di cetak error

### Cara untuk mereplikasi errornya

1. ganti logo kop surat pada pengaturan menggunakan gambar dari file manager
2. cetak surat

### Hasil yg diharapkan

dapat menggunakan logo dari file manager, pada body surat juga dapat menggunakan gambar dari file manager, ketika di klik cetak surat berhasil

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/cb91a77a-8f21-42bc-969b-aed6d67b6270)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Versi 2408.0.0-premium

**Comment by andifahruddinakas** [comment]
mas @rgrahardi, ini bisa sy coba https://berputar.opendesa.id/surat/pratinjau/surat-keterangan-domisili

![image](https://github.com/user-attachments/assets/d217c195-b3a3-4519-9a89-16f339006be3)

**Comment by rgrahardi** [comment]
saya cek di berputar sudah aman mas @andifahruddinakas

**Comment by rgrahardi** [comment]
saya coba replikasi di berputar sudah aman mas @andifahruddinakas ijin saya close
