### ISSUE TITLE
layanan mandiri pada frontend website

### ISSUE THREAD

**Issue by kodingku** [OpenSID/OpenSID#833]
apakah data bantuan yang diinput dari SID hanya dapat menamplkan satu data bantuan ketika login dengan layanan mandiri yang di frontend ??
karna ketika saya input lebih dari satu bantuan untuk satu NIK itu hanya tampil satu dan ketika saya coba yang jamkesmas bisa,tetapi yg lain tidak bisa

apakah ada solusinya,saya coba di SID versi 2.8

**Comment by eddieridwan** [comment]
Sepertinya contoh data awal ada yg tidak lengkap. Coba hapus penerima program bantuan yg ada dan tambahkan lagi.

**Comment by afa28** [comment]
Sdah ad di master terbaru
