### ISSUE TITLE
Bug/error: Edit Kelompok "Lama" rubah Nama ketua  dan slug tidak berubah

### ISSUE THREAD

**Issue by ilhamwahyu-ni** [OpenSID/OpenSID#8331]
### Jelaskan error yg dialami

ubah data lama kelompok dan mengganti nama ketua.

Tampilan pada websitenya tidak berubah

serta
rubah nama kelompok seharusnya slugnya sesuai tang telah dirubah

### Cara untuk mereplikasi errornya

![image](https://github.com/user-attachments/assets/c623b9cf-5ddf-4d75-86d8-3f100f796757)

### Hasil yg diharapkan

normal

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/f621fad3-c97e-4c02-8cb9-72c77834fbf0)

![image](https://github.com/user-attachments/assets/9fc88406-5900-41f1-ba3f-f128e36dea54)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

 2408.0.1

### Informasi tambahan

jika mas @andifahruddinakas  berkenan, bisa replikasi ke nagari saya..

**Comment by andifahruddinakas** [comment]
mas @ilhamwahyu-ni, terkait slug bisa simak pembahasan https://github.com/OpenSID/OpenSID/issues/8292

**Comment by ilhamwahyu-ni** [comment]
Baik mas

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melalui pr https://github.com/OpenSID/premium/pull/4001

**Comment by ilhamwahyu-ni** [comment]
![image](https://github.com/user-attachments/assets/68c00c3a-9b2e-4535-950d-4dfae97aba1c)
