### ISSUE TITLE
Bug/error: ekspor penduduk error

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8332]
### Jelaskan error yg dialami

klik ekspor penduduk error

### Cara untuk mereplikasi errornya

1. Klik menu penduduk
2. Klik ekspor

### Hasil yg diharapkan

bisa ekspor penduduk

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/70f5d599-0b40-4452-8a59-d458843dab1e)

![image](https://github.com/user-attachments/assets/d301971d-eb79-41bf-87a2-8e68f4f9c188)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Versi 2408.0.1-premium

### Informasi tambahan
- terjadi hanya spesifik di desa tersebut
- database saya kirim melalui telegram

_No response_

**Comment by andifahruddinakas** [comment]
mas @rgrahardi, dari errornya terdapat tgl dengan nilai null. 

![image](https://github.com/user-attachments/assets/f9216019-9b82-4951-ba29-0fdcd82d3194)

bisa perbaiki datanya dlu.

untuk data seperti ini perlu diperbaiki oleh pengguna. yang bisa dilakukan disisi sitem, memperketat validasi untuk tgl yg dimana tgllahir seharusnya tidak boleh null, baik saat tambah/ubah ataupun export.

**Comment by rgrahardi** [comment]
masih terjadi error yang sama mas @andifahruddinakas dan terjadi juga di desa Sungairumbai pengguna siapPakai juga

![image](https://github.com/user-attachments/assets/9d11d8fd-4bf0-4abb-8c1c-b9838e1e5355)



saya cek periksa seperti ini mas 
![image](https://github.com/user-attachments/assets/00a05a80-a449-4c87-b46e-5dc2c4f73616)

**Comment by andifahruddinakas** [comment]
> masih terjadi error yang sama mas @andifahruddinakas dan terjadi juga di desa Sungairumbai pengguna siapPakai juga
> 
> ![image](https://private-user-images.githubusercontent.com/55429781/365947988-9d11d8fd-4bf0-4abb-8c1c-b9838e1e5355.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5NTU5MTksIm5iZiI6MTcyNTk1NTYxOSwicGF0aCI6Ii81NTQyOTc4MS8zNjU5NDc5ODgtOWQxMWQ4ZmQtNGJmMC00YWJiLThjMWMtYjk4MzhlMWU1MzU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEwVDA4MDY1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxZjg5ZjBiZTc2ZDBiMzk4ZTI4NDUzNTQ5MDJjMWJhYzIzNzRlNGUxOGI3ZjZlYjk0NTJiMzA0YzkyMjU0NjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xPHEBJyQomnuU5rRwB1yrpKtdPYW7JyG7dIAF_a5vaQ)
> 
> saya cek periksa seperti ini mas ![image](https://private-user-images.githubusercontent.com/55429781/365947483-00a05a80-a449-4c87-b46e-5dc2c4f73616.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5NTU5MTksIm5iZiI6MTcyNTk1NTYxOSwicGF0aCI6Ii81NTQyOTc4MS8zNjU5NDc0ODMtMDBhMDVhODAtYTQ0OS00Yzg3LWI0NmUtNWRjMmM0ZjczNjE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEwVDA4MDY1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0MTkzNjViYTZhOGZhN2UwMGU3MzA0ZmI5MDIwOWM4N2QxZjJmNTBmNjllYjU0ZDNjMTEwYTgyYmRjNTA4NGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.laFUXS7M_cpaQIHzaA6aQW_rQWYclkBiPZRRdTAGS0E)

apakah sudah diperbaiki databasenya agar tgl lahir tidak null?

**Comment by rgrahardi** [comment]
mohon bantuannya mas @apidong terjadi pada Desa Sungairumbai dan SungaiRambai

**Comment by andifahruddinakas** [comment]
Selesai melalui PR https://github.com/OpenSID/premium/commit/aa7e182a1888b69f2feb87e0de6f72a0ce03a6e7
