### ISSUE TITLE
Data anggota lembaga tidak dapat di ubah

### ISSUE THREAD

**Issue by mranca** [OpenSID/OpenSID#8333]
### Jelaskan error yg dialami

Saat ingin mengubah nama anggota lembaga, nama anggota tidak bisa di klik atau di ganti namaya

### Cara untuk mereplikasi errornya

1. Masuk admin
2. Klik info desa
3. Klik salah satu lembaga 
4. Pilih salah satu anggota lembaga yang ingin di ganti atau di ubah

### Hasil yg diharapkan

.

### Tangkapan layar dan log error

![snapshot_tongketongke desa id_1723457062521](https://github.com/user-attachments/assets/7edc4fe9-d2b8-4417-9954-6db869a43064)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Terbaru

### Tema Yang Digunakan

.

### Informasi tambahan

.

**Comment by andifahruddinakas** [comment]
mas @mranca, alurnya memang seperti itu. untuk data yang dipilih terkait penduduk, tidak dapat diubah melalui update. jika terjadi kesalahan input bisa lakukan hapus data sja. Alur ini diterapkan secara umum (suplemen, bantuan, kelompok/lembaga)
