### ISSUE TITLE
Bug/error: hapus kolom jenis pada surat karena sudah tidak digunakan 

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8334]
### Jelaskan error yg dialami

hapus kolom jenis pada surat karena sudah tidak digunakan, sebelumnya kolom jenis digunakan untuk membedakan dengan surat rtf dan surat tinymce

### Cara untuk mereplikasi errornya

1. klik cetak surat
2. lihat kolom jenis surat

### Hasil yg diharapkan

hapus kolom jenis

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/b7367ded-71b5-4808-a49d-40651ef5d2ad)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

OpenSID 2408.0.1-premium

**Comment by andifahruddinakas** [comment]
Sesuaikan untuk surat layanan dan surat dinas
