### ISSUE TITLE
Bug/error: menu inventaris error

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8336]
### Jelaskan error yg dialami

menu inventaris error

### Cara untuk mereplikasi errornya

1. tambah menu 
2. pilih jenis link halaman statis lainnya
3. pilih link inventarsi

### Hasil yg diharapkan

menu inventaris dapat di akses

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/b464ea58-8b61-411b-b06b-b5ab9a60a21f)

![image](https://github.com/user-attachments/assets/f895d9b3-66f6-43ad-96b4-66fe82adeccc)

### Rilis Versi OpenSID

Rilis Umum

### Versi OpenSID

Versi 2408.0.1-premium

**Comment by andifahruddinakas** [comment]
Sudah disesuaikan melalui commit https://github.com/OpenSID/premium/commit/18a59ab7b98bbf0e5107edb94d22a479c91f3da5
