### ISSUE TITLE
Bug/error: Menu Pembangunan input lokasi manual muncul  lokasi tidak ditemukan 

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8337]
### Jelaskan error yg dialami

menu pembangunan lokasi kegiatan input manual maka yg akan muncul lokasi tidak ditemukan / lokasi tidak diketauhi

### Cara untuk mereplikasi errornya

1. klik menu pembangunan
2. tambah pembangunan
3. lokasi pembagunan pilih tulis manual

### Hasil yg diharapkan

dapat melakukan input lokasi manual

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/59d21e4e-a95a-4c57-9957-4371700c680d)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Versi 2408.0.1-premium

**Comment by andifahruddinakas** [comment]
cek ulang jg pada halaman websitenya

![image](https://github.com/user-attachments/assets/b8e15382-091a-4b02-b2a3-9e5ea347a579)
