### ISSUE TITLE
Security: Form user_setting perlu diperkuat

### ISSUE THREAD

**Issue by mugi789** [OpenSID/OpenSID#834]
nemu bug yg bisa ditanem shell backdoor, takutnya ada orang jahat yg mau ngacak2 webnya

letak bug tersebut http://sid.bangundesa.info/index.php/user_setting

**Comment by mugi789** [comment]
ketika saya upload shell backdoor dgn nama file in.php;.png itu berhasil masuk, mohon diperbaiki lagi mas websitenya

**Comment by eddieridwan** [comment]
Masukan di kolom isian mana? Di gambar?

**Comment by mugi789** [comment]
di setting user >> upload avatar

**Comment by eddieridwan** [comment]
Sdh digabung ke master melalui PR #836.
