### ISSUE TITLE
Bug : login Eror untuk group Kasi Pemerintahan

### ISSUE THREAD

**Issue by apidong** [OpenSID/OpenSID#8341]
![Screenshot_20](https://github.com/user-attachments/assets/cb5e8df7-ca9b-4f33-84ea-9b87f8cb5d2c)

**Comment by andifahruddinakas** [comment]
Bisa gunakan database di web berputar

**Comment by agungsugiarto** [comment]
grup yg mana mas @apidong, @andifahruddinakas 

demo berputar
![Image](https://github.com/user-attachments/assets/d72749b8-fbf8-48de-b4bf-8086ae172655)

**Comment by apidong** [comment]
> grup yg mana mas @apidong, @andifahruddinakas
> 
> demo berputar ![Image](https://private-user-images.githubusercontent.com/10989147/358143115-d72749b8-fbf8-48de-b4bf-8086ae172655.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3MDQ4NDcsIm5iZiI6MTcyMzcwNDU0NywicGF0aCI6Ii8xMDk4OTE0Ny8zNTgxNDMxMTUtZDcyNzQ5YjgtZmJmOC00OGRlLWI0YmYtODA4NmFlMTcyNjU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE1VDA2NDkwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhMzdjNjBkZGY1Njg3Y2U5MDg4ODQ1MzhjMmJhNTZiODVhYmFlYWI4MTJlODg4NzQzMzUyNThhMTAzMzk3OTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gn0Fx6LABmCDJVUHD4d2dVPDHjLs_8JJMF84nGCD1UI)

sebentar mas, setelah di restore di berputar gak tau kenapa group nya ilang

**Comment by andifahruddinakas** [comment]
> > grup yg mana mas @apidong, @andifahruddinakas
> > demo berputar ![Image](https://private-user-images.githubusercontent.com/10989147/358143115-d72749b8-fbf8-48de-b4bf-8086ae172655.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3MDQ4NDcsIm5iZiI6MTcyMzcwNDU0NywicGF0aCI6Ii8xMDk4OTE0Ny8zNTgxNDMxMTUtZDcyNzQ5YjgtZmJmOC00OGRlLWI0YmYtODA4NmFlMTcyNjU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE1VDA2NDkwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhMzdjNjBkZGY1Njg3Y2U5MDg4ODQ1MzhjMmJhNTZiODVhYmFlYWI4MTJlODg4NzQzMzUyNThhMTAzMzk3OTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gn0Fx6LABmCDJVUHD4d2dVPDHjLs_8JJMF84nGCD1UI)
> 
> sebentar mas, setelah di restore di berputar gak tau kenapa group nya ilang

masih terkunci kalau bawaan

**Comment by agungsugiarto** [comment]
> > grup yg mana mas [@apidong](https://github.com/apidong), [@andifahruddinakas](https://github.com/andifahruddinakas)
> > demo berputar ![Image](https://private-user-images.githubusercontent.com/10989147/358143115-d72749b8-fbf8-48de-b4bf-8086ae172655.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3MDQ4NDcsIm5iZiI6MTcyMzcwNDU0NywicGF0aCI6Ii8xMDk4OTE0Ny8zNTgxNDMxMTUtZDcyNzQ5YjgtZmJmOC00OGRlLWI0YmYtODA4NmFlMTcyNjU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE1VDA2NDkwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhMzdjNjBkZGY1Njg3Y2U5MDg4ODQ1MzhjMmJhNTZiODVhYmFlYWI4MTJlODg4NzQzMzUyNThhMTAzMzk3OTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gn0Fx6LABmCDJVUHD4d2dVPDHjLs_8JJMF84nGCD1UI)
> 
> sebentar mas, setelah di restore di berputar gak tau kenapa group nya ilang

kalau dilihat dari pesan error karena di line 97 id grup null atau slug dari grup nya null, dari sesi login user

![Image](https://github.com/user-attachments/assets/e9914c9a-f94a-47fa-8674-792dd085c0f5)
