### ISSUE TITLE
Tidak bisa login ketika Google recaptcha aktif

### ISSUE THREAD

**Issue by apidong** [OpenSID/OpenSID#8342]
log ERror 

ERROR - 2024-08-15 12:12:37 --> Severity: error --> Exception: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'g-recaptcha-response' in 'where clause' (Connection: default, SQL: select * from `user` where `username` = admindesa and `g-recaptcha-response` = 03AFcWeA5DOzE4PMwugHPGy0vRvmJFjIxpAIIfeF_prId7uzKlYnEu2vEPid5HZokOMMtxwzPpCXgpvPYkcblvVzt1DmTf-tomnZNiGB1u13SQfeo43o4BZIzLSTt76_BsffA1DM4EkvWb92TaeFXjY6otRyGaE2HM9kt8-Nbn3MGEbODiIsOS65mCaRzvxfBd-A7799kHl2PSzkyyBot1Vr-ptMC2wQsBjpGU4ojBait3jrUIS83-I29HSV8vfvVS6mboQdAwZ-J50ThqwRJfl7fNstt9RZaUuTzkcH58qGgejhPsEaclqXmiECYo1KpbkGrRFgAJauRCu2IHWxXrjzq4pit5FfiXvKpCEkE1lHaBdHFXl-rCRQqkuXh0cHIhw2RCrFpl_40rxIRvtsXWpdgd3uiqRn2xJOyo6LgR2FqaY3JB9ULGDEXSgZtax9BMd5cqgxHhwugD3kXCo9UN5QgGavmP_9OLAndkY0oE7IYw-31DdMcOdl_upmhxN-HZbGiE0vstQ4JHDJj-jr9KsaFvMmgiNKTe6F7HEBfb06FJiNl_i7iGeve_g863nZuOmr9UiKGSnnbZXK9ofC4bfgdBaO8sgFFOuSRH6JBP4pzWt3cK7E71Y63LWCCsZCo6lrYvTi73T7O4CdduIuv0J30mClARq-WVdewFXPnru8UZtPQcFsQcAiBB834r3AUdsmKMrkhC50mATECb402XA_z8CbMPwipSwYbC_N4KqevooWAtIK0qG5pM6BAFL2fMtUj72Vofb92pCZC873iMQZfhcxtBY7H47hz-Vv0XNZETp3NkpPo2fVq71LYsyM4rMfTn0cdrwe8kA_-UAT5yDMWXkrwDELrZggurgzqS6IpOGmLpVQ7zLQOAv6SEK09qXnbyBdQD0orEKvdtISOv9zzkj1zX7ySPnDXMMRNLC3oHqzcgFE8UCfY1bF4lPmAcN3Oqn0ebXuwGMVbwG94c8I59tRuDzX0FV5QgLcMNkMxr1bgMCpG-9ttvXDcmNm9_7Ow9xgy37Gi6RG-DjKLP_GLonUkZ-Up77XvCzAKvSD0kRQV6zYNhBfkKPukh97ci9QBMbMoOTNL-fpvpbmliFBgrq_ln-BbKuz9z3ow0XQhobTQ__eyI2SWUFfTqS80rPq4TIpkdShgLITNHDz1O1C_Iibwc1zQgtvM7sUW6a1tnuvzrerj2pQC74E3VRnCybyDlpCBUvZW9-iSSqvkj-VONtPwknjIAHT4kL9vz9aIe7syRpB58gBq7GbABEXIdEmj8ZQHVQTrDH_Wj3e_01leUHB6ffTxqDQLA7AJ9ZMVwNSjIqQaoshdSRKlShoYkt0m14XOH0OeUH6Y-kSHyfA7-oY4JeNdJHeQQM3qOecJqsLQqcxAtCJt3K7hIf423bRdKe1XxBlrjIYnfmuBqEZk15zZwAKtOUe94lEc6LtGkUOcYOiT0xNztZ_XaBb1LDLKaGHRsR75NzqQ0k8nDCqluu-kHLIEO_8jMqnr86DO0Mo0ZM04WINM6S6wMfPFdINV_xBo9KXJkm2CWZSkTaw1NxbhbnyYNFJ6S655XEAHKsxAQjTGaR-7-RsfkcMUk2McNkniOrBTAWPZ8CpXuJ0c5NlhWTgtuzL4iIe6QM4Q8Y5gpBxNoofm3xTV8eQT7rZQSHlwwKgShVSZINcBly8jDblVsef8QCjXZmHOgFzYHYN0Tr_USMsM17IuU8bf2Y-yHpbYNw8Z7ilpKaF0zGUFFrnfz1CMkgSR7RzDTYS97rycl9fH1JORrutlrXndkaYyXcz1o9tUp6twl33ukEsRNySw8YrJ6Fakebn9jq1INUTLPxqfEK49OFrULPYMkvD9Se8ObVKrLFmPyUW6-YGPrKWfMgDa1nn9Lug4_Jhg0pdCxlqv7fF0y8GPAR656IWeqOQdrCC0g and `active` = 1 and `user`.`config_id` = 1 limit 1) /home/mekarsari-pasirsakti.desa.id/public_html/vendor/illuminate/database/Connection.php 829

**Comment by andifahruddinakas** [comment]
sudah disesuaikan di commit https://github.com/OpenSID/premium/commit/a8235204c7f524c352f4ad95ed0de06a7ab8e2af

**Comment by apidong** [comment]
siap mas
