### ISSUE TITLE
Bug/error: Ketika Klik Ubah di Menu Arsip surat dilakukan tinjau PDF terjadi error

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#8347]
### Jelaskan error yg dialami

Ketika Klik Ubah di Menu Arsip surat dilakukan tinjau PDF terjadi error

### Cara untuk mereplikasi errornya

Ketika Klik Ubah di Menu Arsip surat dilakukan tinjau PDF terjadi error
![image](https://github.com/user-attachments/assets/6f5e1e03-3cec-475f-8ab8-2131556a8b4b)
![image](https://github.com/user-attachments/assets/bc81094b-a2d6-4e06-b493-b54db0d0d006)
![image](https://github.com/user-attachments/assets/19e9d5e9-4984-4a39-af81-67dae1742cca)
kalau saya lihat-lihat error karena logo surat
![image](https://github.com/user-attachments/assets/b609978b-c05f-41bd-bad3-a724f3416681)

### Hasil yg diharapkan

tidak error

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/b609978b-c05f-41bd-bad3-a724f3416681)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

24.08.0.2

### Tema Yang Digunakan

Natra

### Informasi tambahan

saya coba di https://berputar.opendesa.id/keluar/edit_surat/28

**Comment by MUHAMMADRANGSEL** [comment]
Jika logo dihapus maka tinjau PDF berhasil

**Comment by Sukoharjo3** [comment]
cetak dr tinjau pun eror tempat sy pak
![image](https://github.com/user-attachments/assets/cfe8aea5-27ca-41ef-b4b8-88c7a40b65f5)

**Comment by Sukoharjo3** [comment]
![image](https://github.com/user-attachments/assets/7ac6a7ad-8ea5-47ef-b4d5-0b69b206ccd1)

**Comment by Syahrulmuhamad** [comment]
Semoga segera ditindak lanjuti

**Comment by andifahruddinakas** [comment]
Duplicate of https://github.com/OpenSID/OpenSID/issues/8293
