### ISSUE TITLE
Bug/error: tinjau surat hasil edit di arsip layanan error

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8356]
### Jelaskan error yg dialami

lakukan edit surat yang di arsip layanan kemudian klik tinjau pdf error

### Cara untuk mereplikasi errornya

1. arsip layanan
2. klik ubah surat
3. klik tinjau surat

### Hasil yg diharapkan

dapat melakukan tinjau dan cetak surat yg di edit di arsip surat

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/b67e1186-3c86-46af-b1e2-a79e8b69de54)
![image](https://github.com/user-attachments/assets/a3537040-d4a1-40e0-9455-7281e33ab086)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Versi 2408.0.2-premium

### Informasi tambahan

-

**Comment by andifahruddinakas** [comment]
# Duplicate issue https://github.com/OpenSID/OpenSID/issues/8293
