### ISSUE TITLE
Bug/error: impor penduduk error Tanggal lahir tidak boleh kosong

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8358]
### Jelaskan error yg dialami

impor penduduk error Tanggal lahir tidak boleh kosong terjadi di database gabungan

### Cara untuk mereplikasi errornya

1. penduduk
2. impor penduduk

### Hasil yg diharapkan

impor penduduk berhasil

### Tangkapan layar dan log error

impor penduduk dibukan database gabungan berhasil

![image](https://github.com/user-attachments/assets/cbae3aa5-9266-49ea-9459-142419aae93e)

impor penduduk didatabase gabungan 

![image](https://github.com/user-attachments/assets/a653233e-c8b4-425f-93b4-0572ee7c13e7)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Versi 2408.0.2-premium

**Comment by rgrahardi** [comment]
terjadi di database gabungan mohon bantuannya mas @scqolbu24 mas @apidong

**Comment by pandigresik** [comment]
duplikat issue https://github.com/OpenSID/OpenSID/issues/8351
