### ISSUE TITLE
Bug/error: Sortir dan pengaturan Galeri tidak berfungsi sebagaimana mestinya

### ISSUE THREAD

**Issue by mah-mudi** [OpenSID/OpenSID#8361]
### Jelaskan error yg dialami

Sortir dan pengaturan Galeri tidak berfungsi sebagaimana mestinya

### Cara untuk mereplikasi errornya

1. Admin web
2. Galeri
3. Pengaturan Galeri

### Hasil yg diharapkan

Sortir Galeri yg terupload tgl akhir misal nomo 12 tdk bisa diseret ke nomor 1, padahal ingin di tampilkan di widget galeri. apa yg diseret di nomor 123, keluar urutan 123, yg sekrang tampilan di admin web tidak seperti itu.

Selanjutnya pengaturan Jumlah Gambar Galeri maksimal, ubah menjadi album galeri jangan dibatasi 10 album galeri.
Dapat meniru widget pembangunan yang ada 
![image](https://github.com/user-attachments/assets/06180ffe-79b6-4464-b6ab-1c445b1d6e6c)

### Tangkapan layar dan log error

[screen-capture (20).webm](https://github.com/user-attachments/assets/024ec683-907d-4d32-ab00-edbacd7a4559)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

24.08.03 premium

### Tema Yang Digunakan

natra

### Informasi tambahan

https://berputar.opendesa.id/

**Comment by andifahruddinakas** [comment]
pak @mah-mudi, untuk pengaturan tsb hanya untuk halaman depan pada widget galeri yg ditampilkan.
