### ISSUE TITLE
Bug/error: Upload Peta Desa selalu Gagal

### ISSUE THREAD

**Issue by desapurwoasri** [OpenSID/OpenSID#8362]
### Jelaskan error yg dialami

Saat Upload Peta Desa selalu Error

### Cara untuk mereplikasi errornya

Admin Web-Galeri

### Hasil yg diharapkan

Perbaikan agar bisa diuplaod

### Tangkapan layar dan log error

![Picture1](https://github.com/user-attachments/assets/c92e8256-8bb3-427b-ba4d-a59a13c9da43)
![Picture2](https://github.com/user-attachments/assets/e2738c40-f739-4490-9d45-471d5a0407e1)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2312.0.0

### Informasi tambahan

-

**Comment by agungsugiarto** [comment]
Pak @desapurwoasri bisa dilampirkan log errornya?

**Comment by desapurwoasri** [comment]
Sudah bisa pak. Ternyata gambarnya terlalu besar ukuran pixcelnya. Terima
kasih

Pada Sel, 20 Agu 2024 13.28, Agung Sugiarto ***@***.***>
menulis:
