### ISSUE TITLE
Bug/error: menu layanan pelanggan blank

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8364]
### Jelaskan error yg dialami

menu layanan pelanggan blank, pengguna yang opensid premium sudah berakhir layanan pelanggan menjadi blank padahal didalamnya masih ada lisensi anjungan, berdampak anjungan mandiri tidak bisa diakses

### Cara untuk mereplikasi errornya

1. klik menulayanan pelanggan yang opensid premium sudah berakhir dan punya lisensi anjungan

### Hasil yg diharapkan

lisensi anjungan tetap terbaca dan anjungan mandiri tetap bisa digunakan

saran dari pengguna pisahkan penempatan lisensi anjungan dengan lisensi opensid premium

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Versi 2408.0.2-premium

### Informasi tambahan

-

**Comment by apidong** [comment]
dari hasil penelusuran, penyebabnya dikarenakan token perlu diperbarui.

**Comment by eddieridwan** [comment]
@apidong @rgrahardi @vickyrolanda @andifahruddinakas dalam kasus seperti ini, harap tidak ditutup begitu saja. 

Pastikan disesuaikan issuenya untuk mengatasi sumber keluhan, supaya tidak ada lagi yg mengeluh kasus itu lagi. Kalau tidak ditindaklanjuti, hampir pasti ke depan akan ada lagi yg mengeluh atau bertanya untuk kasus yg persis sama. Sedangkan itu yg ingin kita hindari. Kita tidak ingin waktu kita habis menelurusi dan menjawab kasus-kasus berulang seperti ini.

Misalnya, dalam kasus ini, beri notifikasi bahwa langganan Premiumnya telah berakhir dan tokennya perlu diperbaharui. Tidak hanya menampilkan halaman kosong.

**Comment by andifahruddinakas** [comment]
cek:
- cache belum tercipta, saat diakses akan kosong.
![image](https://github.com/user-attachments/assets/62521230-96ad-4bb9-b7d5-29f253928f64)

- seharusnya jika cache belum ada maka akan request dlu kelayanan dan buat cache.
