### ISSUE TITLE
Bug/error: salah input latitute dan longitude peta blank

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8365]
### Jelaskan error yg dialami

terdapat pengguna yang menginput latitute dan longitude tidak sesuai menyebabkan peta blank, karena ada pengguna yg meninputkan copy paste data dari excel.

seperti berikut ini input latitue yang salah : --8.483832804795249 

strip 2 kali tidak disadari oleh pengguna menyebabkan peta blank

### Cara untuk mereplikasi errornya

1. klik menu identitas desa
2. klik lokasi kantor
3. input latitute : --8.483832804795249 

### Hasil yg diharapkan

terdapat pemberitahuan jika salah menginputkan nilai latitute dan longitue, sehingga data yang tidak sesuai tidak tersimpan ke database.

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/4da4bd7a-9e3f-484e-8fe1-8d0407e4f5da)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Versi 2408.0.2-premium

**Comment by andifahruddinakas** [comment]
mas @habibie11, tambahkan validasi.
