### ISSUE TITLE
Bug/error: data anggota lembaga ketika di klik rincian kosong

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8366]
### Jelaskan error yg dialami

data anggota lembaga berjumlah 8 ketika di klik rincian datanya kosong

### Cara untuk mereplikasi errornya

1. klik lembaga desa
2. klik rincian anggota 

### Hasil yg diharapkan

data anggota tampil normal sesuai jumlah anggota

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/3d29b714-1616-4ee1-b39f-8a089d2567f7)
![image](https://github.com/user-attachments/assets/149618b6-f218-45ca-940b-57d4dbb5501c)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

OpenSID 2408.0.2-premium

### Informasi tambahan
- berputar aman
- Desa Saing Prupuk (Pengguna Diskominfo Paser)

**Comment by agungsugiarto** [comment]
mas @andifahruddinakas, @rgrahardi perlu database contoh untuk replikasi.
