### ISSUE TITLE
Bug/error: lihat rincian warga terdata datanya kosong

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8367]
### Jelaskan error yg dialami

 lihat rincian warga terdata datanya kosong

### Cara untuk mereplikasi errornya

1. klik data suplemen
2. klik rincian data

### Hasil yg diharapkan

data warga terdata tampil normal

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/0bc6b548-ac86-4098-ad0f-eb184362b95a)
![image](https://github.com/user-attachments/assets/166507b0-238b-448c-b130-021c37578299)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

OpenSID 2408.0.2-premium

### Informasi tambahan

- Berputar aman
- Desa Saing Prupuk (Pengguna Diskominfo Paser)

**Comment by agungsugiarto** [comment]
mas @andifahruddinakas, @rgrahardi perlu database contoh untuk replikasi.

**Comment by andifahruddinakas** [comment]
Untuk database gabungan yang sudah terlanjur masuk dimana id_terdata tidak terupdate datanya, maka perlu disesuaikan lagi oleh pengguna.
