### ISSUE TITLE
Bug/error: Jumlah penduduk di dasbord dan di laporan bulanan tidak sama

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8368]
### Jelaskan error yg dialami

Jumlah penduduk di dasbord dan di laporan bulanan tidak sama

### Cara untuk mereplikasi errornya

1. Klik menu statistik
2. Klik sub menu laporan bulanan

### Hasil yg diharapkan

solusi agar tidak terjadi lagi perbedaan jumlah penduduk dan laporan penduduk

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/ab0fca31-d161-4d9c-8ead-aa35df76ff8e)
![image](https://github.com/user-attachments/assets/4fd413ab-a1d9-4916-8ce3-db46d3b2ce83)

![image](https://github.com/user-attachments/assets/4940a58b-74f6-44fd-8d0b-9098364117a7)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

 2408.0.2-premium

**Comment by rgrahardi** [comment]
mas @andifahruddinakas databasenya saya kirim lewat telegram

**Comment by andifahruddinakas** [comment]
dari yg terlihat, yg tidak sesuai adalah jumlah penduduk laki2
<img width="960" alt="image" src="https://github.com/user-attachments/assets/08ac6056-5696-4f5b-847f-37dcf4341c4c">


<img width="960" alt="image" src="https://github.com/user-attachments/assets/5c573735-b9a2-4a10-b25d-da34c336e2b3">

database terlampir.
