### ISSUE TITLE
Bug/error: klik tinjau pdf internal server error

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8369]
### Jelaskan error yg dialami

tinjau pdf gagal / internal server error

Log Error

ERROR - 2024-08-22 09:42:05 --> Severity: error --> Exception: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'isi_surat_temp' in 'field list' (Connection: default, SQL: insert into `log_surat` (`id`, `id_format_surat`, `id_pend`, `id_pamong`, `nama_jabatan`, `nama_pamong`, `id_user`, `tanggal`, `bulan`, `tahun`, `no_surat`, `keterangan`, `kecamatan`, `pemohon`, `input`, `isi_surat`, `isi_surat_temp`, `nama_surat`, `config_id`) values (?, 2309541, 3597183, 1204159, Perbekel, ANAK AGUNG MAYUN WIDIADNYANA, 1204126, 2024-08-22 09:42:04, 08, 2024, , ?, 1, ?, {"url_surat":"surat-keterangan-domisili-usaha","url_remote":"https:\/\/kerambitan.desa.id\/surat\/nomor_surat_duplikat","id_surat":"2309541","nomor":"3","individu":{"nik":"3597183"},"nik":"3597183","nama_usaha":"Coba Surat","mulai_berlaku":"22-08-2024","berlaku_sampai":"22-09-2024","pilih_atas_nama":""}, <table style="border-collapse: collapse; width: 100%;">
<tbody>
<tr>

### Cara untuk mereplikasi errornya

1. layanan surat
2. cetak surat
3. klik tinjau pdf

### Hasil yg diharapkan

tinjau pdf normal kembali 

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/16bb04d5-ea31-4e15-9ab0-3e70dcba4335)
![image](https://github.com/user-attachments/assets/6162fe01-c728-40ae-ac66-5b2435906580)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

 2408.0.3-premium

### Informasi tambahan

terjadi pada Desa Kerambitan dan Desa Mambang Kab Tabanan

**Comment by rgrahardi** [comment]
mas @scqolbu24 mas @apidong mas @andifahruddinakas terjadi juga di siapPakai yang bukan database gabungan

![image](https://github.com/user-attachments/assets/5d53db71-50c9-4fff-92d7-a979abc51b6c)


ERROR - 2024-08-22 08:44:49 --> Severity: error --> Exception: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'isi_surat_temp' in 'field list' (Connection: default, SQL: insert into `log_surat` (`id`, `id_format_surat`, `id_pend`, `id_pamong`, `nama_jabatan`, `nama_pamong`, `id_user`, `tanggal`, `bulan`, `tahun`, `no_surat`, `keterangan`, `kecamatan`, `pemohon`, `input`, `isi_surat`, `isi_surat_temp`, `nama_surat`, `config_id`) values (?, 251, 4791, 42, Sekretaris Desa, JAJANG KOMARUDIN, 22, 2024-08-22 08:44:49, 08, 2024, , ?, 1, ?, {"url_surat":"surat-keterangan-kematian","url_remote":"https:\/\/margasari-ciawi.desa.id\/surat\/nomor_surat_duplikat","id_surat":"251","nomor":"25","individu":{"nik":"4791"},"nik":"4791","anchor":"","pelapor":{"nik":"112"},"id_pend_pelapor":"112","hubungan_pelapor_dengan_yang_mati_pelapor":"sodara","saksi_i":{"nik":"4858"},"id_pend_saksi_i":"4858","saksi_ii":{"nik":"4801"},"id_pend_saksi_ii":"4801","lampiran":["f-2.01"],"pilih_atas_nama":"a.n"}, <table style="border-collapse: collapse; width: 100%;">

**Comment by rgrahardi** [comment]
info dari pak Ariandi

![image](https://github.com/user-attachments/assets/fac80a12-c6fe-49c7-860f-dd225b5232a2)

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui commit https://github.com/OpenSID/premium/commit/178a5eeb43b9594440bd1acdb781d0faba1cec10

**Comment by rgrahardi** [comment]
mas @andifahruddinakas mas @scqolbu24 mas @apidong 

solusi sementara tidak bisa diterapkan di database gabungan
https://forum.opendesa.id/d/343-solusi-sementara-untuk-tinjau-pdf-gagal


Error ketika klik semua migrasi di database gabungan
![image](https://github.com/user-attachments/assets/6bb23ab1-9c75-452b-930b-215b7a0060fc)


cek periksa
![image](https://github.com/user-attachments/assets/840cc6f3-4d06-4f3f-81f3-265b2044343b)

**Comment by andifahruddinakas** [comment]
> mas @andifahruddinakas mas @scqolbu24 mas @apidong 
> 
> solusi sementara tidak bisa diterapkan di database gabungan
> https://forum.opendesa.id/d/343-solusi-sementara-untuk-tinjau-pdf-gagal
> 
> 
> Error ketika klik semua migrasi di database gabungan
> ![image](https://github.com/user-attachments/assets/37b0422a-916e-4f0e-979c-22782baa8b42)
> 
> cek periksa
> ![image](https://github.com/user-attachments/assets/840cc6f3-4d06-4f3f-81f3-265b2044343b)
> 
> 

Ini error lain, bisa di tabel tweb_penduduk pd kolom tanggallahir cek data yg kosong

**Comment by pandigresik** [comment]
> mas @andifahruddinakas mas @scqolbu24 mas @apidong
> 
> solusi sementara tidak bisa diterapkan di database gabungan https://forum.opendesa.id/d/343-solusi-sementara-untuk-tinjau-pdf-gagal
> 
> Error ketika klik semua migrasi di database gabungan ![image](https://private-user-images.githubusercontent.com/55429781/360279413-6bb23ab1-9c75-452b-930b-215b7a0060fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMDA3ODMsIm5iZiI6MTcyNDMwMDQ4MywicGF0aCI6Ii81NTQyOTc4MS8zNjAyNzk0MTMtNmJiMjNhYjEtOWM3NS00NTJiLTkzMGItMjE1YjdhMDA2MGZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDA0MjEyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlkZTcwMDY0MGQ1MjRjMzdjM2EwMzNkNDJlZTRhNzhjMDY3MDcxYzNjYzZiMTZiYzEzYTM0MmE5OGU5Njg2MjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DW8friwzQb69z2ag5dnfO8tev6_khkIu1My_9lrDSFw)
> 
> cek periksa ![image](https://private-user-images.githubusercontent.com/55429781/360278751-840cc6f3-4d06-4f3f-81f3-265b2044343b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMDA3ODMsIm5iZiI6MTcyNDMwMDQ4MywicGF0aCI6Ii81NTQyOTc4MS8zNjAyNzg3NTEtODQwY2M2ZjMtNGQwNi00ZjNmLTgxZjMtMjY1YjIwNDQzNDNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDA0MjEyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1NTMyYWFhYTk0OTdmMDA0YzFmM2NjMDZjNzMyMDRkNjM3OWM4MTkyZDMwMWFlMjY1NGZiMmVjN2M5ODdkNTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qDha_mXqp8WqHE0lROX-3k7tCbEVibLLHyK_apkELkY)

pilih migrasi terbaru saja
