### ISSUE TITLE
Format BIP

### ISSUE THREAD

**Issue by Budisasmika** [OpenSID/OpenSID#837]
menurut pengalaman saya data BIP perlu di rubah atau ditambahkan lagi kolom-kolomnya karna dilombok timur format BIP sudah dirubah

**Comment by eddieridwan** [comment]
@Budisasmika : jangan lupa melampirkan contoh BIPnya. Tanpa contoh, tidak bisa diterapkan.

**Comment by Budisasmika** [comment]
mohon maaf pak gimana cara membuat lampirannya

**Comment by eddieridwan** [comment]
Lihat panduan: https://github.com/OpenSID/OpenSID/wiki/Pengelolaan-Masalah-dan-Permintaan-Perbaikan-SID

**Comment by Budisasmika** [comment]
![untitled2](https://user-images.githubusercontent.com/35210351/36931541-2530cc50-1f25-11e8-91e5-46bdf0f84130.png)

**Comment by eddieridwan** [comment]
@Budisasmika : itu bukan Buku Induk Penduduk (BIP). Itu sepertinya file output khusus -- tidak mengikuti standar yang kami ketahui. BIP bentuknya laporan cetak berdasarkan keluarga (kartu keluarga). Silakan lihat contoh format BIP (ada 4) di menu Database > Impor BIP.

Kami anjurkan anda berkonsultasi dengan bung Muhammad dari Rarang Selatan mengenai cara memperoleh data dari Disdukcapil Lombok Timur dalam format yang bisa langsung diimpor ke database OpenSID. 

File yang anda peroleh itu sepertinya bisa saja anda sesuaikan dengan format Database > Impor Database (BUKAN submenu Impor BIP). Lihat contoh formatnya di submenu itu. Sepertinya tinggal ubah urutan kolom2nya.
