### ISSUE TITLE
Bug/error: link verifikasi email dan reset password ketika diklik

### ISSUE THREAD

**Issue by AbankGendutz** [OpenSID/OpenSID#8370]
### Jelaskan error yg dialami

Bug/error: link verifikasi email dan reset password saat diakses not found 404

### Cara untuk mereplikasi errornya

klik link verivikasi dan reset passowrd

### Hasil yg diharapkan

diperbaiki

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/f5617cf4-ed5b-4a89-b0c6-bc04240141b3)

### Rilis Versi OpenSID

Rilis Umum

### Versi OpenSID

v24.08

### Tema Yang Digunakan

natra

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/3715
