### ISSUE TITLE
Permintaan fitur: tambahkan kode isian jenis kelamin untuk inisial P dan L

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8371]
### Apa kekurangan yg ingin diatasi?

tambahkan kode isian jenis kelamin untuk inisial P dan L

contoh menggunakan kode isian jenis kelamin memakan banyak tempat pada tabel

![image](https://github.com/user-attachments/assets/8d21eb7e-3d59-4b7e-a13e-73004787355d)

setelah di ubah manual isinya menjadi inisial 

![image](https://github.com/user-attachments/assets/fe621de1-6c34-4963-9e22-3a142c5eb770)

### Jelaskan solusi yg diinginkan

terdapat kode isian inisial L dan P untuk jenis kelamin

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

OpenSID 2409.0.0-premium

### Informasi tambahan

- Usulan Fitur dari Bapak Syahrul Desa Lapokainse

**Comment by eddieridwan** [comment]
@rgrahardi untuk setiap permintaan fitur, juga lampirkan siapa dan dari desa mana yg mengusulkan fitur tsb.
