### ISSUE TITLE
Bug/error: Peta Wilayah Desa blank putih

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8378]
### Jelaskan error yg dialami

Peta Wilayah Desa blank putih, sudah di clear cache tetap tidak muncul

### Cara untuk mereplikasi errornya

1. menu info desa
2. menu identitas desa
3. klik tombol wilayah desa

### Hasil yg diharapkan

peta muncul 

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/482ece97-feec-4365-9fcb-bd42a9369b2a)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Versi 2408.0.3-premium

### Informasi tambahan

Desa Bantiran Database Gabungan Kab. Tabanan

**Comment by habibie11** [comment]
apakah bisa dikirimkan database yang digunakan?
