### ISSUE TITLE
### Bug Input SK KADES dan PERDES

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#838]
pada waktu input SK KADES dan PERDES ternyata error seperti gambar dibawah ini : 
![screenshot 2018-03-05 23 17 21](https://user-images.githubusercontent.com/25834335/36983137-8f2f1c6c-20cc-11e8-81b2-95c4f0b4ebb0.png)
![screenshot 2018-03-05 23 22 54](https://user-images.githubusercontent.com/25834335/36983145-986b4904-20cc-11e8-91ac-e42abc8bdf14.png)

**Comment by eddieridwan** [comment]
Di http:/sid.bangundesa.info bisa, normal saja. Cek ukuran file dan jenis berkas yang diunggah.

Coba unggah di http:/sid.bangundesa.info.

**Comment by MUHAMMADRANGSEL** [comment]
alhamdulillah ternyata benar mas eddie jadi yang menyebabkan error dan gagal disimpan karena lampiran SK wajib dilampirkan shgg issue ini saya akan closed
