### ISSUE TITLE
Bug/error: Tampilan sortir urutan sinergitas program tidak sesuai urutannya dengan tampilan website

### ISSUE THREAD

**Issue by mah-mudi** [OpenSID/OpenSID#8380]
### Jelaskan error yg dialami

Tampilan sortir urutan sinergitas program tidak sesuai dengan tampilan website

### Cara untuk mereplikasi errornya

sinergitas program

### Hasil yg diharapkan

Tampilan sortir urutan sinergitas program dapat sesuai urutannya dengan tampilan website

### Tangkapan layar dan log error

https://github.com/user-attachments/assets/510948f0-fa56-41ef-b21c-e59b5badf8e8

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

24.08.03 premium

### Tema Yang Digunakan

natra

### Informasi tambahan

https://berputar.opendesa.id/sinergi_program

**Comment by habibie11** [comment]
untuk issue ini akan dicek lebih lanjut karna memang di berputar dan beta datatablenya tidak berfungsi, mungkin bisa diinfokan juga apakah di desa masing-masing atau dilocal mengalami yang sama. cc @andifahruddinakas @mah-mudi

**Comment by mah-mudi** [comment]
iya tidak berfungsi

**Comment by andifahruddinakas** [comment]
Selesai melalui commit https://github.com/OpenSID/premium/commit/29c37c53e9e45d9e0bcccb78ae514096ca27f6d9
