### ISSUE TITLE
Bug/error: Favicon pada calon pemilih berganti ke logo opendesa

### ISSUE THREAD

**Issue by ilhamwahyu-ni** [OpenSID/OpenSID#8381]
### Jelaskan error yg dialami

-

### Cara untuk mereplikasi errornya

![image](https://github.com/user-attachments/assets/8f57e33e-84d4-4c99-9234-18324e82ed0f)

### Hasil yg diharapkan

seharusya masih logo kabupaten setempat

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

 2408.0.3

### Informasi tambahan

sudah dicoba juga di device lain..

SS di hp

![IMG_20240823_144343](https://github.com/user-attachments/assets/1f05ac81-77f4-4751-9b81-5b4e40529b3a)

**Comment by andifahruddinakas** [comment]
![image](https://github.com/user-attachments/assets/028e41eb-71c9-43cc-8758-fcbd2c056647)

**Comment by ilhamwahyu-ni** [comment]
Kira2 kenapa ya mas, dari sekian banyak page, hanya page ini yang bedo favicon nya..

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui commit https://github.com/OpenSID/premium/commit/6224ff96fd4114809877b628ce980b6b9c035fe4
