### ISSUE TITLE
Bug/error: impor penduduk gagal

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8382]
### Jelaskan error yg dialami

impor penduduk tidak ada pesan berhasil atau gagal impor halaman berpindah ke halaman penduduk

### Cara untuk mereplikasi errornya

1. impor penduduk 

### Hasil yg diharapkan

solusi agar tidak terjadi lagi saat proses impor berjalan tidak ada pesan berhasil atau gagal halaman lansung berpindah ke halaman publik

### Tangkapan layar dan log error

https://github.com/user-attachments/assets/0548feac-cea8-4b77-80f6-ed3e3f5c27bd

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Versi 2408.0.2-premium

### Informasi tambahan

Desa Carangsari Pengguna SiapPakai

**Comment by andifahruddinakas** [comment]
mas @rgrahardi, sertakan log error dan file yg di impor. bisa kirim ke telegram

**Comment by rgrahardi** [comment]
![image](https://github.com/user-attachments/assets/16f1c0eb-fd96-47b5-8886-2eb01d50a8a2)
![image](https://github.com/user-attachments/assets/713fab03-64e4-40cf-a68b-2652e5a20657)

cc mas @andifahruddinakas mas @pandigresik
