### ISSUE TITLE
Terpasang artikel judi online ?

### ISSUE THREAD

**Issue by SamX23** [OpenSID/OpenSID#8383]
Halo

Saya sedang cek versi gratis [disini](https://demosid.opendesa.id/), dan ternyata ada promosi judi online.

Apakah ini kecolongan atau sponsor?

![image](https://github.com/user-attachments/assets/a203bffa-124e-44cf-bcbd-c262c48e76eb)
[URL](https://demosid.opendesa.id/artikel/2024/8/9/rajatoto-situs-slot-gacor-online-hari-ini-rajatoto-mudah-jp-maxwin-2024)

Terima kasih

**Comment by balongbesuk** [comment]
nmny juga website demo siapa saja bisa masuk siapa saja bisa bikin artikel, tiap jam 12 malam biasanya otomatis d reset ke database awal,

**Comment by andifahruddinakas** [comment]
pak @SamX23, terima kasih atas laporannya. website demo tentunya terbuka secara umum dan bisa ditambahkan oleh siapa saja. Adapun yg biasa dilakukan, setiap 1 hari sekali melakukan reset.
