### ISSUE TITLE
Bug/error: nomor surat hanya muncul bagian tahun tidak muncul

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8384]
### Jelaskan error yg dialami

Surat Keterangan Penduduk nomor surat bagian tahun tidak muncul Nomor : S-02/001/3328122008/TAHUN]

### Cara untuk mereplikasi errornya

1. cetak surat 
2. pilih surat keterangan penduduk
3. tinjau pdf
4. cetak surat

### Hasil yg diharapkan

tahun pada nomor surat muncul kembali

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/383f05e2-a792-49ff-920b-8185b1dc04f9)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Versi 2408.0.3-premium

**Comment by andifahruddinakas** [comment]
mas @rgrahardi, saya coba aman
![image](https://github.com/user-attachments/assets/f6a95d4a-5eed-4e9e-ba97-036ed86ef51a)

bisa cek kembali format penomoran suratnya.
![image](https://github.com/user-attachments/assets/de6e7ed6-d144-4b21-aa49-19be5313f33b)

cek apakah ada kurung yg berlebih

**Comment by rgrahardi** [comment]
![image](https://github.com/user-attachments/assets/c1c3a384-3f9f-47bf-9062-fdd2e526d4ed)
![image](https://github.com/user-attachments/assets/38a2debc-cd1b-41f8-b006-a3b6b33f9058)


sudah bisa issue saya close
