### ISSUE TITLE
Bug/error: tombol file manager bug

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8385]
### Jelaskan error yg dialami

tombol file manager ada 2 di artikel

### Cara untuk mereplikasi errornya

1. admin web
2. artikel 
3. upload gambar file manager

### Hasil yg diharapkan

saran jika ada 2 file manager dapat membingungkan
jika file manager nomor 1 tetap di adakan perbaiki errornya

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/f79db821-0b6f-4fd7-997e-f5487c367bf9)
![image](https://github.com/user-attachments/assets/113535a8-adad-4410-b448-3ae529691afb)
![image](https://github.com/user-attachments/assets/9baf4a02-8a2d-4444-bf29-fbe2646f8eeb)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Versi 2408.0.3-premium

**Comment by andifahruddinakas** [comment]
mas @rgrahardi, untuk fugsi tsb dikembalikan karena sempat hilang setelah upgrade versi RFM, bisa cek di versi yang lama. Adapun jika pengembalian fungsi tsb ada error, bisa infokan seperti apa. Bisa cek jg pembahasan https://github.com/OpenSID/premium/pull/3998,

**Comment by ariandii** [comment]
pak @andifahruddinakas ini bug,
bisa tes klik icon angka 1, maka tidak menampilkan popup file manager, tetapi tampil siteman didalam popup tersebut.

pak @rgrahardi mungkin judulnya disesuaikan, penekanannya pada saat klik tombol icon 1 tidak sesuai hasil tampilannya.

**Comment by rgrahardi** [comment]
baik pak @ariandii sudah saya update judulnya

**Comment by andifahruddinakas** [comment]
ok, sepertinya bentrok antara RFM yang ada di point 1 dan 2. mungkin dihilangkan saja, untuk selanjutnya jika ada pertanyaan unggah gambar/file lewat RFM bisa dijelaskan lewat panduan.

**Comment by andifahruddinakas** [comment]
Disesuaikan melalui commit https://github.com/OpenSID/premium/commit/6dd4f0845519533b764191318edfef1330fda80e
