### ISSUE TITLE
Icon tidak nampak pada modal komfirmasi

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#8386]
Saat install awal akan menampilkan notifikasi persetujuan sbb
![image](https://github.com/user-attachments/assets/8df8bd4f-f5ad-4e3d-8952-15aebac4af60)

Setelah melakukan persetujuan akan menampilkan modal proses, namun yang tampil saat ini iconnya tidak tampil.
![image](https://github.com/user-attachments/assets/987c6a8d-f69f-44ec-8acd-916c15fbeec3)

Itu juga terjadi pada notifikasi persetujuan menonaktifkan tracking
![image](https://github.com/user-attachments/assets/67f4c906-8a49-48a9-aa99-e409d6e77fe9)

![image](https://github.com/user-attachments/assets/e9ddece6-7459-41d0-aecb-11d3fca3d2af)

**Comment by ariandii** [comment]
![image](https://github.com/user-attachments/assets/20003a62-7a76-4319-bc95-8e621387cd7e)

dan beberapa icon di lokasi lain yang muncul di popup.
termasuk saat impor penduduk di gambar atas.
