### ISSUE TITLE
Penanganan log akses 404

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#8388]
Saat pengguna mengakses halaman yang tidak ada, maka pada log akan menampilkan log error, 
`404 Page Not Found: `

![image](https://github.com/user-attachments/assets/d26a9252-85b6-454b-9689-4e05774213df)

Mungkin sebaiknya log tersebut dihilangkan saja agar log tidak membengkak.

**Comment by andifahruddinakas** [comment]
pak @ariandii, mungkin ada masukan?

**Comment by eddieridwan** [comment]
Kecuali yg dicurigakan usaha peretasan. Mungkin dalam hal itu, yg perlu masuk log adalah URL yg berusaha dicari, seperti filemanager, config dan serupa.
