### ISSUE TITLE
Bug/error: Menghapus Anggota di Menu Lembaga Poto di Menu Kependudukan Hilang

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#8392]
### Jelaskan error yg dialami

Menghapus Anggota di Menu Lembaga Poto di Menu Kependudukan Hilang

### Cara untuk mereplikasi errornya
![image](https://github.com/user-attachments/assets/7d0e82ba-d97d-429b-9343-4e260c04cbe3)
![image](https://github.com/user-attachments/assets/55e75d0c-a58c-4be3-ba04-bf5f99c7738e)
![image](https://github.com/user-attachments/assets/6075f2b5-5da3-461c-8259-ffb3217e5009)
![image](https://github.com/user-attachments/assets/ec69b8a9-9323-4e39-94ca-a575b25472e0)

Masuk di Menu Lembaga hapus salah satu anggota lembaga yang sudah diupload potonya di menu kependudukan, setelah dihapus dicek di menu kependudukan potonya jadi hilang ikut terhapus

### Hasil yg diharapkan

Poto di menu kependudukan tidak hilang walaupun datanya dihapus sebagai anggota lembaga

### Tangkapan layar dan log error

Poto di menu kependudukan tidak hilang walaupun datanya dihapus sebagai anggota lembaga

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

24.08.0.3

### Tema Yang Digunakan

Denava

**Comment by ariandii** [comment]
https://github.com/OpenSID/OpenSID/issues/8367
