### ISSUE TITLE
Bug/error: Poto Tidak Muncul dan data tidak ditampilkan saat tambah anggota lembaga walaupun di menu penduduk sdh ada poto

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#8393]
### Jelaskan error yg dialami

pada saat menambah anggota lembaga maka datanya potonya tidak tampil serta datanya tidak ditampilkan seperti halnya di menu suplemen 

### Cara untuk mereplikasi errornya

masuk di menu lembaga
![image](https://github.com/user-attachments/assets/f79d3ea8-dcd4-4b70-aab8-ba7907154701)

### Hasil yg diharapkan

1. poto tampil
2. data ditampilkan seperti gambar dibawah ini
![image](https://github.com/user-attachments/assets/cdecf9ec-c18a-4a93-9b47-ee5d912dbb43)

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/f79d3ea8-dcd4-4b70-aab8-ba7907154701)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

24.08.0.3 premium

### Tema Yang Digunakan

Denava

**Comment by ariandii** [comment]
https://github.com/OpenSID/OpenSID/issues/8367
