### ISSUE TITLE
Bug/error: tinjau pdf blank putih

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8394]
### Jelaskan error yg dialami

tinjau pdf pada menu cetak surat dan pengaturan surat blank putih saja dan di cetak blank putih saja file pdf nya, sudah cek log error tidak ada, sudah di bersikan cache juga

### Cara untuk mereplikasi errornya

1. layanan surat
2. cetak surat
3. pilih surat
4. tinjua pdf

### Hasil yg diharapkan

bisa cetak surat dan tinjau surat 

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/ae854fcc-0806-4780-a410-bfed858bc83c)
![image](https://github.com/user-attachments/assets/059188d1-e9f0-40fc-aeee-3d333d16f7ef)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

OpenSID 2408.0.3-premium

### Informasi tambahan

Desa Desa Karya Sari Kab. Tabanan

**Comment by andifahruddinakas** [comment]
mas @rgrahardi, bisa sertakan template surat yg digunakan. Cek jg di versi v24081.0.0 karena terkait pratinjau yg blank sudah diperbaiki.

**Comment by rgrahardi** [comment]
terjadi di semua template mas @andifahruddinakas 

ini template surat keterangan domisili dan biodata penduduk bawaan sistem

![image](https://github.com/user-attachments/assets/8fce9593-5c48-4229-90c7-b39209dafc9e)
![image](https://github.com/user-attachments/assets/d5ec5947-d054-4352-bf6d-673fec7e63f1)

db saya kirim dari telegram mas

**Comment by agungsugiarto** [comment]
mas @rgrahardi databasenya apakah sama yg dimention ke saya kemarin?

**Comment by rgrahardi** [comment]
Issuenya masih terjadi di Desa Karya Sari versi  2409.0.0-premium
![image](https://github.com/user-attachments/assets/d86ab0ab-435f-4f79-a5c7-083fa798be15)

**Comment by agungsugiarto** [comment]
mas @rgrahardi sudah di perbaiki di versi rev  v2409.0.1, apakah masih bermasalah?

**Comment by rgrahardi** [comment]
mas @agungsugiarto baik mas saat ini Desa Karyawa Sari masihversi OpenSID 2409.0.0-premium, akan di infokan lagi setelah rilis rev01 mas terimakasih
