### ISSUE TITLE
Bug/error: template surat menggunakan "page break" tidak bisa di tinjau

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8401]
### Jelaskan error yg dialami

template surat menggunakan "page break" tidak bisa di tinjau

### Cara untuk mereplikasi errornya

1. pengaturan surat
2. ubah template surat
3. klik insert
4. klik page break
5. tinjau pdf 

### Hasil yg diharapkan

bisa menggunakan page break

### Tangkapan layar dan log error

1. Sebelum di berikan page break
![image](https://github.com/user-attachments/assets/e4648eb1-d13b-4310-b542-b79b6041925c)

2. setelah diberikan page break
![image](https://github.com/user-attachments/assets/3e9879d5-29dc-4729-9eb7-6886dd989f08)

3. di cetak error

![image](https://github.com/user-attachments/assets/0ac2ffde-ba07-4ae9-9fe9-b40d2a143c5d)

![image](https://github.com/user-attachments/assets/d15de975-801f-4546-8a9c-c7ed9ba1d7ce)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Versi 2408.0.3-premium

**Comment by andifahruddinakas** [comment]
mas @rgrahardi, bisa gunakan branch rilis-dev atau bug-fix. Bisa diinfokan jg ini untuk surat mana?

sy coba replikasi aman menggunakan surat domisili.
![image](https://github.com/user-attachments/assets/1b8b5283-294a-4aad-a405-7e7f86972d49)

hasil
![image](https://github.com/user-attachments/assets/c6060a80-15af-454e-ad26-75fea4c7608b)
