### ISSUE TITLE
Bug/error: setelah berhasil login redirect ke /siteman/auth

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8402]
### Jelaskan error yg dialami

setelah login berhasil redirect ke websitedesa/siteman/auth

kalau mau masuk admin harus 

/siteman/auth di hapus ketik /beranda

### Cara untuk mereplikasi errornya

1. login 
2. masuka user name dan password

### Hasil yg diharapkan

berhasil login lansung redirect ke beranda 

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

OpenSID v2408.0.3-premium

### Tema Yang Digunakan

-

### Informasi tambahan

terjadi di Desa https://margasari-ciawi.desa.id/siteman/auth Pengguna SiapPakai1

**Comment by andifahruddinakas** [comment]
mas @rgrahardi, dilocal dan https://berputar.opendesa.id/ aman. bisa mintakan/buatkan user semetara yang bisa di test.

**Comment by andifahruddinakas** [comment]
error:
```
Severity: error --> Exception: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'db_3206362003.log_login' doesn't exist (Connection: default, SQL: insert into `log_login` (`username`, `ip_address`, `user_agent`, `referer`, `lainnya`, `config_id`, `uuid`, `updated_at`, `created_at`) values
Administrator, 180.247.252.238, Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36 Edg/128.0.0.0, https://margasari-ciawi.desa.id/siteman, {"city":"Surabaya","state":"East Java","country":"Indonesia","country_code":"ID","continent":"Asia","continent_code":"AS"}, 1, 71776196-0d31-4c95-b926-f51d8be96e1a, 2024-08-29 15:29:44, 2024-08-29 15:29:44)) /www/wwwroot/master-opensid/premium/vendor/illuminate/database/Connection.php 829
```

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui commit https://github.com/OpenSID/premium/commit/dcf18ad1be803bb39794487ad76d9c6a9c6ffbd4
