### ISSUE TITLE
Bug/error: Tinjau surat error

### ISSUE THREAD

**Issue by alit2310** [OpenSID/OpenSID#8403]
### Jelaskan error yg dialami

pada saat membuat surat dengan menambahkan banyak tabel, pada saat ditinjau terjadi error. berikut tangkapan log nya : "Severity: error --> Exception: count(): Argument #1 ($value) must be of type Countable|array, int given /home/berputar.opendesa.id/public_html/vendor/spipu/html2pdf/src/Html2Pdf.php 5163"

### Cara untuk mereplikasi errornya

[template_surat_tinymce_29_08_2024 (1).json](https://github.com/user-attachments/files/16792657/template_surat_tinymce_29_08_2024.1.json)
diatas contoh surat yang kami buat, dengan judul "Rekomendasi Pembelian BBM Tertentu"

### Hasil yg diharapkan

tolong segera diperbaiki, supaya bisa mengkastum surat menyurat

### Tangkapan layar dan log error

![Screenshot 2024-08-29 134615](https://github.com/user-attachments/assets/8dbaf191-e752-4ced-b869-2f91704ce155)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

24.09

### Tema Yang Digunakan

Pusako 2.4

**Comment by agungsugiarto** [comment]
Pak @alit2310 format template surat tersebut tidak memenuhi standar kebutuhan, periksa kembali template surat yang dibuat, ikuti contoh surat yang sudah ada. Jika masih kesulitan dalam membuat surat sendiri silahkan berdiskusi dengan komunitas agar dibimbing. Terima kasih

cc: @rgrahardi

**Comment by alit2310** [comment]
maksud dari template surat tidak sesuai standar kebutuhan itu seperti apa pak @agungsugiarto ?
ijin kalau bisa surat menyuratnya bisa dicustom sesuai keinginan user pak, kebetulan di desa kami ada warga yang membutuhkan surat seperti itu. Kmi berkeinginan agar semua surat menyurat berada dalam satu aplikasi, biar tidak ada yang buat manual di word dan penomoran suratnya biar bisa jadi satu.

**Comment by agungsugiarto** [comment]
Semua surat bisa di ubah atau dibuat sendiri sesuai kebutuhan desa pak @alit2310, selengkapnya ada dipanduan.

https://panduan.opendesa.id/opensid/halaman-administrasi/layanan-surat/pengaturan

**Comment by alit2310** [comment]
panduannya sudah saya baca pak, saya membuat surat sesuai dengan panduan dan pada saat tinjau dia error @agungsugiarto 
dan minta bantuannya pak terkait peta kami no respon saat membuka peta 
![Screenshot 2024-09-02 095300](https://github.com/user-attachments/assets/f4b12135-b1f3-4d1b-abc9-ecdd8a71badd)

**Comment by pandigresik** [comment]
pak @alit2310 coba pakai template dibawah ini

[template_surat_tinymce_03_09_2024.json](https://github.com/user-attachments/files/16842123/template_surat_tinymce_03_09_2024.json)

**Comment by andifahruddinakas** [comment]
pak @alit2310, apa benar fomnya seperti ini?
![image](https://github.com/user-attachments/assets/aaee62bb-3f16-459d-b9f3-ee231483dca3)

**Comment by rgrahardi** [comment]
mohon infonya pak @alit2310 apakah issue masih terjadi ? jika iya dapat dibawakan ke klinik bug pak

**Comment by andifahruddinakas** [comment]
pak @alit2310, jika masih bermasalah bisa dibuka kembali. dengan melampirkan log_error, contoh tempate surat yg bermasalah, menggunakan rilis terbaru
