### ISSUE TITLE
Bug/error: Tidak bisa mengirim Notifikasi Login ke Group Telegram

### ISSUE THREAD

**Issue by langonsari** [OpenSID/OpenSID#8405]
### Jelaskan error yg dialami

Tidak bisa mengirim Notifikasi Login melalui Group Telegram setelah di Update ke Versi 2408.0.0-premium dan Muncul error 
**Telegram responded with an error `400 - Bad Request: TOPIC_CLOSED`**

Namun untuk Notifikasi yang diarahkan ke ID Telegram personal tidak terjadi error
![image](https://github.com/user-attachments/assets/dd535d81-240b-4540-9bb8-a6173f67e15a)

### Cara untuk mereplikasi errornya

![image](https://github.com/user-attachments/assets/84bb5055-7a44-4c0a-b5bb-a0f172a34179)

### Hasil yg diharapkan

Dapat mengirim kembali notifikasi login ke Group Telegram sebagai pemantau penggunaan OpenSID
![image](https://github.com/user-attachments/assets/24c6983a-dadf-4c39-ba6f-5a8a54ddc8d0)

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/622d16cc-a79a-499c-a70e-4686cc64be7f)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2408.0.0-premium

**Comment by pandigresik** [comment]
pastikan bot telah dimasukkan kedalam grup tersebut

**Comment by langonsari** [comment]
> pastikan bot telah dimasukkan kedalam grup tersebut

sudah pak pandi,,
bahkan saya pakai bot yang lain pun juga sama

**Comment by langonsari** [comment]
setelah di ujicoba dengan Desa yang lain dan membuat Group Baru bisa dianilisi hasilnya:

- [ ] type ID Telegram Group dengan lebih dari 13 digit angka contoh (_-1001591563482_) keluar log error Telegram responded with an error `400 - Bad Request: TOPIC_CLOSED`

- [x] type ID Telegram Group baru dengan 11 digit angkat contoh (_-4510184620_) berhasil menerima notifikasi
![image](https://github.com/user-attachments/assets/5302a3d2-c250-46f7-b41a-bd5ceb7d8b7c)

**Comment by rgrahardi** [comment]
mohon infonya pak @langonsari apakah issue masih terjadi ? jika iya dapat dibawakan ke klinik bug pak

**Comment by andifahruddinakas** [comment]
pak @langonsari, jika masih bermasalah bisa dibuka kembali.
