### ISSUE TITLE
Bug/error: ekspor DTKS ke Excel tidak bisa

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#8406]
### Jelaskan error yg dialami

untuk melalkukan export hasil pendataan DTKS muncul :
This site can’t be reachedThe webpage at https://**namadesa**.desa.id/dtks/ekspor?versi=2 might be temporarily down or it may have moved permanently to a new web address.
ERR_INVALID_RESPONSE
setelah di cek di log muncul : 
Severity: error --> Exception: App\Services\DTKSRegsosEk2022k::syncKetDemografi(): Argument #3 ($kepala_keluarga) must be of type App\Models\Penduduk, null given, called in /home/**_namadesa_**.desa.id/public_html/donjo-app/core/MY_Log.php(206) : eval()'d code(1) : eval()'d code on line 318 /home/namadesa.

### Cara untuk mereplikasi errornya

masuk di Menu Satu Data/DTKS klik centang beberapa data lanjut klik esport ke excel maka akan tampil
This site can’t be reachedThe webpage at https://**namadesa**.desa.id/dtks/ekspor?versi=2 might be temporarily down or it may have moved permanently to a new web address.
ERR_INVALID_RESPONSE
setelah di cek di log muncul : 
Severity: error --> Exception: App\Services\DTKSRegsosEk2022k::syncKetDemografi(): Argument #3 ($kepala_keluarga) must be of type App\Models\Penduduk, null given, called in /home/**_namadesa_**.desa.id/public_html/donjo-app/core/MY_Log.php(206) : eval()'d code(1) : eval()'d code on line 318 /home/namadesa.

### Hasil yg diharapkan

bisa eksport seperti versi sebelumnya

### Tangkapan layar dan log error

This site can’t be reachedThe webpage at https://**namadesa**.desa.id/dtks/ekspor?versi=2 might be temporarily down or it may have moved permanently to a new web address.
ERR_INVALID_RESPONSE
setelah di cek di log muncul : 
Severity: error --> Exception: App\Services\DTKSRegsosEk2022k::syncKetDemografi(): Argument #3 ($kepala_keluarga) must be of type App\Models\Penduduk, null given, called in /home/**_namadesa_**.desa.id/public_html/donjo-app/core/MY_Log.php(206) : eval()'d code(1) : eval()'d code on line 318 /home/namadesa.

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

24.08.0.2

### Tema Yang Digunakan

Denava

**Comment by MUHAMMADRANGSEL** [comment]
Kalau Cetak Prelist aman kalau pilih satu tapi jika pilih 2 maka error

**Comment by MUHAMMADRANGSEL** [comment]
di Versi 24.09.0.1 masalah ini belum teratasi, yang muncul keterrangan :
**This site can’t be reachedThe webpage at https://namadesa/dtks/ekspor?versi=2 might be temporarily down or it may have moved permanently to a new web address.
ERR_INVALID_RESPONSE**

**Comment by MUHAMMADRANGSEL** [comment]
log error : Severity: error --> Exception: App\Services\DTKSRegsosEk2022k::syncKetDemografi(): Argument #3 ($kepala_keluarga) must be of type App\Models\Penduduk, null given, called in /home/**_namadesa.desa.id_**/public_html/donjo-app/core/MY_Log.php(206) : eval()'d code(1) : eval()'d code on line 318 /home/_**namadesa**_.

**Comment by MUHAMMADRANGSEL** [comment]
belum ada solusikah...?

**Comment by andifahruddinakas** [comment]
> belum ada solusikah...?

Bisa di update ke v2409.0.2

![image](https://github.com/user-attachments/assets/430ba194-ca8a-486d-b72b-54d3d73998ca)

dan bisa cek di https://berputar.opendesa.id/dtks

**Comment by MUHAMMADRANGSEL** [comment]
Ok

Pada tanggal Kam, 19 Sep 2024 07.29, Andi Fahruddin Akas <
***@***.***> menulis:
