### ISSUE TITLE
Bug/error: mencetak lebih dari 1 prelist error

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#8407]
### Jelaskan error yg dialami

mencetak lebih dari 1 prelist error
![image](https://github.com/user-attachments/assets/89be29a1-12b2-4181-aeb0-061039aa4a88)

### Cara untuk mereplikasi errornya

![image](https://github.com/user-attachments/assets/28b06443-c618-4269-8379-b8606941223b)

### Hasil yg diharapkan

Bisa Cetak seperti versi sebelumnya

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/c8689c6e-237b-4f5f-9989-657ae5bd99d0)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

24.08.0.2

### Tema Yang Digunakan

Denava

**Comment by agungsugiarto** [comment]
Pak @MUHAMMADRANGSEL saya tidak bisa replikasi issue ini, bisa dikirimkan video agar lebih jelas. Terima kasih

**Comment by MUHAMMADRANGSEL** [comment]
Ok siap pak

Pada tanggal Jum, 30 Agu 2024 11.30, Agung Sugiarto <
***@***.***> menulis:
