### ISSUE TITLE
Permintaan fitur: Kehadiran

### ISSUE THREAD

**Issue by afri18** [OpenSID/OpenSID#8409]
### Apa kekurangan yg ingin diatasi?

Terlalu Tepatnya isi kehadiran di jam kerja masuk dan pulang yang kadang kita sudah datang awal lupa isi kehadiran
![image](https://github.com/user-attachments/assets/3b36ddba-3390-43b6-b2cf-9370895f230c)

### Jelaskan solusi yg diinginkan

Berikan tenggang waktu 2 jam sebelum dan sesudah Jam Kerja untuk mengurangi keterlambatan dan lupa tidak melapor

### Apakah ada alternatif lain

Tenggang waktu aktif jam kehadiran 2 jam sebelum dan sesudah

### Untuk versi OpenSID mana

2410.0.0

### Informasi tambahan

agar yg sudah datang awal dapat mengisi kehadiran dan yg pulang lewat jam kerja bisa isi keluar/pulang

**Comment by agungsugiarto** [comment]
Pak @afri18 issue ini saya close karena fitur ini sudah ada dan bisa diatur rentang tenggangnya.

1. Masuk ke menu Kehadiran > Jam kerja
2. Klik icon pengaturan pada pojok kanan atas
3. Ubah pada Rentang Waktu Kehadiran (misalkan 120 dalam satuan menit)

cc: @rgrahardi bisa ditambahkan ke panduan, jika belum ada

**Comment by afri18** [comment]
> Pak @afri18 issue ini saya close karena fitur ini sudah ada dan bisa diatur rentang tenggangnya.
> 
> 1. Masuk ke menu Kehadiran > Jam kerja
> 2. Klik icon pengaturan pada pojok kanan atas
> 3. Ubah pada Rentang Waktu Kehadiran (misalkan 120 dalam satuan menit)
> 
> cc: @rgrahardi bisa ditambahkan ke panduan, jika belum ada

yang ada tenggang waktu pulang, sedangkan tenggang waktu masuk tidak tersedia
![image](https://github.com/user-attachments/assets/f95f7d9a-2b3d-406a-8b0d-ccb5d781238e)

**Comment by agungsugiarto** [comment]
Pak @afri18, setelah saya lihat tenggang waktu masuk memang tidak tersedia, untuk "Rentang Waktu Kehadiran" saya samakan ya misalkan 2 jam sebelum masuk dan 2 jam sesudah keluar?

**Comment by afri18** [comment]
> Pak @afri18, setelah saya lihat tenggang waktu masuk memang tidak tersedia, untuk "Rentang Waktu Kehadiran" saya samakan ya misalkan 2 jam sebelum masuk dan 2 jam sesudah keluar?

okeh, atau bisa disesuaikan dengan kebutuhan desa masing2
