### ISSUE TITLE
Bug: gagal unggah gambar pada artikel

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#841]
pada situs demo sid.bangundesa.info ketika membuat artikel >> unggah gambar utama / gambar tambahan, gambar (.jpeg) tidak bisa di unggah

![sedang_1518844567_bansos rastra](https://user-images.githubusercontent.com/35319600/37030210-ba3be67e-216c-11e8-9b32-a722e92fbcfa.jpg)

**Comment by MUHAMMADRANGSEL** [comment]
dan juga upload gambar digaleri juga error

**Comment by MUHAMMADRANGSEL** [comment]
mohon ini untuk segera diselesaikan

**Comment by MUHAMMADRANGSEL** [comment]
maslahnya disini mungkin belum fix, setelah saya hapus yang saya blok ini poto bisa disimpan kembali
![image](https://user-images.githubusercontent.com/25834335/37035510-c667c362-2187-11e8-90ed-cb2efd8bee79.png)

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
