### ISSUE TITLE
Bug/error: Menu Satu Data / DTKS penambahan Data Baru

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#8410]
### Jelaskan error yg dialami

pada saat menambahkan data baru di menu satu data/DTKS data yang sudah masuk juga tampil dan bisa masuk lebih dari satu kali

### Cara untuk mereplikasi errornya

pada saat menambahkan data baru di menu satu data/DTKS data yang sudah masuk juga tampil dan bisa masuk lebih dari satu kali

### Hasil yg diharapkan

pada saat menambahkan data baru di menu satu data/DTKS data yang sudah masuk juga tampil dan bisa masuk lebih dari satu kali

### Tangkapan layar dan log error

pada saat menambahkan data baru di menu satu data/DTKS data yang sudah masuk juga tampil dan bisa masuk lebih dari satu kali

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

24.08.0.2 premium

**Comment by agungsugiarto** [comment]
Pak @MUHAMMADRANGSEL  yg dimaksud apakah pilihan kepala rumah tangga? yg sudah ditambahkan tidak tampil



![Image](https://github.com/user-attachments/assets/6c983eea-788f-4b57-bd78-2066aeb5a415)

**Comment by MUHAMMADRANGSEL** [comment]
ya bang yang sudah ditambahkan di DTKS muncul kemabli

**Comment by MUHAMMADRANGSEL** [comment]
![image](https://github.com/user-attachments/assets/923f0060-1439-4b5a-80e4-af471820cb6b)

**Comment by MUHAMMADRANGSEL** [comment]
di menu rumah tangga juga sama kasusnya
