### ISSUE TITLE
Bug/error: Hasil Tinjau dan Cetak Surat TinyMCe tidak Sesuai

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#8411]
### Jelaskan error yg dialami

![image](https://github.com/user-attachments/assets/8b778f99-e651-4606-a343-77cc3986c37a)
hasilnya
![image](https://github.com/user-attachments/assets/383b6b7e-d84c-4b4d-ad49-721fc220b566)

### Cara untuk mereplikasi errornya

![image](https://github.com/user-attachments/assets/3ccdb58f-2c34-47a2-b785-3d5e50d9fc1c)
hasilnya 
![Uploading image.png…]()

### Hasil yg diharapkan

tampilan tinjau dan cetak sesuai dengan settingan di Template

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/52134b65-1827-488c-8124-c2cb58e5b726)
hasilnya
![Uploading image.png…]()

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

24.08.0.2

**Comment by andifahruddinakas** [comment]
pak @MUHAMMADRANGSEL, ini bukan bug, jika mau cells tsb isinya berada di tengah, bisa sesuaikan dibagian vertical align.
![image](https://github.com/user-attachments/assets/05c72132-2a9b-42b9-a6fd-ac4ca4352c52)

![image](https://github.com/user-attachments/assets/b0099916-3492-4faa-964a-0ac8eb27a6b8)

hasil pratinjau
![image](https://github.com/user-attachments/assets/7ce765e7-32c3-45f5-bf0d-9845bc5fb2a4)

**Comment by MUHAMMADRANGSEL** [comment]
Bukan di tengah bang tapi diatas

Pada tanggal Jum, 30 Agu 2024 15.23, Andi Fahruddin Akas <
***@***.***> menulis:

**Comment by MUHAMMADRANGSEL** [comment]
> pak @MUHAMMADRANGSEL, ini bukan bug, jika mau cells tsb isinya berada di tengah, bisa sesuaikan dibagian vertical align. ![image](https://private-user-images.githubusercontent.com/57283157/363079756-05c72132-2a9b-42b9-a6fd-ac4ca4352c52.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUwMzQ5OTUsIm5iZiI6MTcyNTAzNDY5NSwicGF0aCI6Ii81NzI4MzE1Ny8zNjMwNzk3NTYtMDVjNzIxMzItMmE5Yi00MmI5LWE2ZmQtYWM0Y2E0MzUyYzUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMwVDE2MTgxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmZGI2NTQzOGJkMDc4N2FhZmFmNDQxNTE3NmUyMDI4Y2IxOTg0OGQyNDIxYjkxMjA1NzhlZDI0NTk3YjhkNTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nklmtvORyUEchW2WCcp2Ye6MSFoZVRIZ3_eNKR1jWSA)
> 
> ![image](https://private-user-images.githubusercontent.com/57283157/363079939-b0099916-3492-4faa-964a-0ac8eb27a6b8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUwMzQ5OTUsIm5iZiI6MTcyNTAzNDY5NSwicGF0aCI6Ii81NzI4MzE1Ny8zNjMwNzk5MzktYjAwOTk5MTYtMzQ5Mi00ZmFhLTk2NGEtMGFjOGViMjdhNmI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMwVDE2MTgxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRkNTE0YThiMDE2NmZjODBlNWEyZTFiMTBiNDAzYmE5YjhiYjBjNDI4YzZkYmNmNTQ2ZGVjNTU0OThlZGEyNzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Xj4KNiCgZHNklPftX4MWz6ODPFatcd6FSgN-EMsiDUU)
> 
> hasil pratinjau ![image](https://private-user-images.githubusercontent.com/57283157/363080046-7ce765e7-32c3-45f5-bf0d-9845bc5fb2a4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUwMzQ5OTUsIm5iZiI6MTcyNTAzNDY5NSwicGF0aCI6Ii81NzI4MzE1Ny8zNjMwODAwNDYtN2NlNzY1ZTctMzJjMy00NWY1LWJmMGQtOTg0NWJjNWZiMmE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMwVDE2MTgxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU2OWRjZDgyYTZkZjU3NDJmZmQwNzhmMmMwYjEyMDBlOWRiMzZlZGQxOGMyYzEzMDFlNjc5ZWUyNTY5MDYwYTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Aj2V2XRYiFK8YCx7RPanYhq65RB5u4MnCf8Wyu8KUio)

VERSI BERAPA INI BANG

**Comment by MUHAMMADRANGSEL** [comment]
SAYA COBA DI BERPUTAR BELUM BISA
![image](https://github.com/user-attachments/assets/bdd35773-5d8b-49c1-a32a-c634e5e5a658)

**Comment by andifahruddinakas** [comment]
> SAYA COBA DI BERPUTAR BELUM BISA ![image](https://private-user-images.githubusercontent.com/25834335/363264622-bdd35773-5d8b-49c1-a32a-c634e5e5a658.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyMzI5MjEsIm5iZiI6MTcyNTIzMjYyMSwicGF0aCI6Ii8yNTgzNDMzNS8zNjMyNjQ2MjItYmRkMzU3NzMtNWQ4Yi00OWMxLWEzMmEtYzYzNGU1ZTVhNjU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAxVDIzMTcwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5NjU5YjZkYTI0NTliOGQ3MTNiOGYxZjA4MWFkMzZjM2FiYjYyNDNhNWNhOTJhY2EzZjBkZjQ3YjNlMmM5YzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EJgeEpzAHat9vNbsgQ6Na7XnszuyH9-10NtM8SFMOLg)

coba dikembalikan ke bawaan, mungkin ada yg ubah.
![image](https://github.com/user-attachments/assets/cef9b3bd-f8ab-40f7-a342-ad57308923c4)

**Comment by eddieridwan** [comment]
@andifahruddinakas selalu usahakan mencari akar permasalahan. Jika template ubahan bermasalah, telusuri ubahan apa yg menyebabkan masalah tsb. Kemudian atasi, misalnya:

1. cegah ubahan seperti itu
2. deteksi ubahan itu dan beri notifikasi akan menyebabkan masalah
3. lainnya?

**Comment by MUHAMMADRANGSEL** [comment]
INI SUDAH FIX
