### ISSUE TITLE
Bug/error: Error Saat Ubah Surat Yang Sudah Di Arsip

### ISSUE THREAD

**Issue by wahyabiantara** [OpenSID/OpenSID#8412]
### Jelaskan error yg dialami

Saat mencoba melakukan perubahan pada surat yang sudah di Arsip muncul error, sehingga proses editing tidak bisa dilanjutkan.

### Cara untuk mereplikasi errornya

1. Buat surat Keterangan Usaha
2. Tinjau PDF dan Cetak
3. Menuju ke Arsip Surat
4. Ubah Surat yang baru saja dibuat dan masukan alasan pengubahan
5. Muncul Form Editor.
6. Disinilah error muncul, dimana tag logo yang muncul berupa broken image
7. Klik Kode Isian muncul error 200 Syntax Error

### Hasil yg diharapkan

Tidak ada broken image pada form editor, melainkan tag logo desa dan qrcode.

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/0723af20-be69-4efe-a4e9-af5bc26b509c)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2408.0.2-premium

**Comment by luxmant354** [comment]
update versi terbaru (2408.0.3) sudah di fixkan problem ini
