### ISSUE TITLE
Bug/error: Sortiran Tahun di Buku Keputusan tidak berfungsi sebagaimana mestinya

### ISSUE THREAD

**Issue by mah-mudi** [OpenSID/OpenSID#8413]
### Jelaskan error yg dialami

Sortiran Tahun di Buku Keputusan tidak berfungsi sebagaimana mestinya, mustinya sortiran **misal** tahun 2024 hanya menampilkan keputusan yang hanya 2024. tapi versi sekarang sortirannya berdasarkan judul dokumen yang ada karakter 2024.

### Cara untuk mereplikasi errornya

1. Buku Peraturan Di Desa
2. Buku Keputusan Kepala Desa

### Hasil yg diharapkan

Ganti Sortiran Tahun di Buku Keputusan yang semula berdasarkan judul dokumen menjadi **berdasarkan kolom isian tanggal penetapan keputusan**

### Tangkapan layar dan log error

[screen-capture (19).webm](https://github.com/user-attachments/assets/1a9a0c21-bc8c-4e02-8ebe-8833052e60dd)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

24.08.03 premium

### Tema Yang Digunakan

silir

### Informasi tambahan

-

**Comment by andifahruddinakas** [comment]
Yang beramasalah cuma di bukun keputusan kepala desa
