### ISSUE TITLE
Data Anak Yatim Piatu 

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#842]
![sedang_1518844567_bansos rastra](https://user-images.githubusercontent.com/35319600/37031842-fa2eb8dc-2172-11e8-8d13-a54b0ae8d47e.jpg)

**Comment by MUHAMMADRANGSEL** [comment]
Data ini lebih baik dimasukkan di Data Suplemen lebih pas menurut saya

**Comment by balongbesuk** [comment]
jika dasarnya menggunakan database penduduk, saya pikir lebih ke otomatis terupdate, misal ketika salah satu anggota orang tua meninggal >> ubah status istri / suami cerai mati otomatis terekam anak anak pada tabel yatim / piatu, begitu jg ketika orangtua yang berstatus cerai mati menikah lagi misalkan, maka data anak2nya otomatis keluar dari kelompok yatim / piatu,

**Comment by HerryWanda** [comment]
Usulan / masukan dari saudara balongbesuk sangat bagus juga,
tambahan dari kami  Kalo masalah data anak yatim, juga harus diberi batasan umur , berapa batas maksimal  umur yang masih tergolong anak yatim. kalo tidak diberi batasan, jadi setiap orang yang sudah meninggal orang tuanya, maka nanti akan tergolong anak yatim semuanya.

**Comment by afa28** [comment]
Apakah ini masih bermasalah / masih diperlukan??? Kalau tdk, silahkan di close.

**Comment by MUHAMMADRANGSEL** [comment]
Masih diperlukan

Pada tanggal Sen, 24 Agt 2020 14.06, Andi Fahruddin Akas <
notifications@github.com> menulis:

**Comment by afa28** [comment]
> Usulan / masukan dari saudara balongbesuk sangat bagus juga,
> tambahan dari kami  Kalo masalah data anak yatim, juga harus diberi batasan umur , berapa batas maksimal  umur yang masih tergolong anak yatim. kalo tidak diberi batasan, jadi setiap orang yang sudah meninggal orang tuanya, maka nanti akan tergolong anak yatim semuanya. 

Jd berapa batasan maksimal umur dikatakan yatim???

**Comment by MUHAMMADRANGSEL** [comment]
Ada yg mengatakan 12 ada yg 15 tahun

Pada tanggal Sen, 24 Agt 2020 18.33, Andi Fahruddin Akas <
notifications@github.com> menulis:

**Comment by balongbesuk** [comment]
bisa menggunakan pengaturan rentan usia seperti d statistik usia

karena biasanya pemberi santunan anak yatim yg menentukan rentan usia yg akan d santuni

**Comment by mizwaruddin** [comment]
Yatim tdk bisa ditentukan dg batasan usia. Anak dikatakan yatim jika ayahnya meninggal dan belum baligh. Batasan baligh antara satu dg yg lain berbeda. Klo terkait dg bantuan, sya sarankan utk kros cek ke yg bersangkutan. Utk laki2 ditanya apakah sdh prnh mimpi basah, sedangkan utk perempuan ditanya apkh sdh haid.

**Comment by balongbesuk** [comment]
kalau menurut islam memang seperti itu, tapi pemberi santunan biasanya / kadang minta data yatim / piatu merujuk ke usia atau pendidikan,

**Comment by mizwaruddin** [comment]
Jika data anak yatim pada permintaan sampean mensyaratkan status cerai mati, menurut saya juga tidak bisa dijadikan sebagai dasar. Mengapa? Data anak yatim juga bisa dihasilkan dari Kepala Keluarga yang status perkawinannya "KAWIN". Contoh kasus: Seorang istri yang ditinggal suami karena mati, maka anak-anaknya yang belum baligh menyandang status sbg anak yatim. kemudian istri tsb menikah lagi yg menjadikan status perkawinannya menjadi "KAWIN", maka anak-anaknya jg masih menyandang status anak yatim.

**Comment by balongbesuk** [comment]
baik, mungkin teman teman non muslim bisa memberi masukkan definisi yatim di agamanya masing masing? (kalau ada),

**Comment by muhtar-coder** [comment]
Kalo di saya biasanya tiap ada permintaan data yatim/ piatu.  Yg di minta umur di bawah 15 tahun... Patokan tsb bisa disesuaikan melihat quota bantuan/santunan yg akan di bagi...misal jumlah quota sebanyak 10 paket. Sedang jumlah yatim ada 15, (umur 0 - 15 tahun).. Nah biasa nya di kami mengurangi batas umur nya  misal di ambil umur 0-12 tahun atau untuk mencukupkan quota santunan..

**Comment by andifahruddinakas** [comment]
Bisa dimasukkan ke data suplemen.

**Comment by hasap86** [comment]
Fitur ini ada progresnya gak ya?

sekarang diperlukan untuk pengajuan Bantuan YAPI (Yatim Piatu) BBM :)
