### ISSUE TITLE
Bug/error: tidak bisa tambah penerima bantuan 

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8421]
### Jelaskan error yg dialami

tidak bisa tambah penerima bantuan 

### Cara untuk mereplikasi errornya

1. Klik bantuan 
2. Klik Program Bantuan
3. Tambah Penerima / Peserta bantuan

### Hasil yg diharapkan

berhasi tambah peserta bantuan

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/3aea3bee-a243-4736-af35-304a07a593bb)

![image](https://github.com/user-attachments/assets/3136cb2a-c36f-4755-af16-322ac3e643e4)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Versi 2408.0.3-premium

### Informasi tambahan

Desa Podenura

**Comment by andifahruddinakas** [comment]
mas @rgrahardi, mungkin kasus yang normal di local maupun website demo diberikan contoh datanya untuk mereplikasi.

**Comment by rgrahardi** [comment]
mas @agungsugiarto sudah saya ke telegram

**Comment by makhbub** [comment]
bug ini juga dialami oleh saya.
saya memakai opensid Versi 2409.0.0-premium
![bantuan 1](https://github.com/user-attachments/assets/e3c1ffd3-5822-4cac-abd6-e60ba57804d9)
![bantuan 2](https://github.com/user-attachments/assets/2bdcd5f3-d842-4876-857e-30fa7e0d4d8a)
