### ISSUE TITLE
Permintaan fitur: Penambahan informasi Profil, Visi, Misi Serta Sambutan Kepala Desa

### ISSUE THREAD

**Issue by fachmifaisal** [OpenSID/OpenSID#8422]
### Apa kekurangan yg ingin diatasi?

Sejauh ini OpenSID belum menampilkan Profil, Sejarah Desa, Visi, Misi, serta Sambutan Kepala Desa. Adapun beberapa alasan penting, di antaranya:

1. Transparansi dan Akuntabilitas: Profil, Visi, dan Misi desa memberikan gambaran jelas kepada masyarakat tentang arah dan tujuan yang ingin dicapai oleh pemerintah desa. Hal ini meningkatkan transparansi dan akuntabilitas pemerintahan desa kepada warganya.

2. Meningkatkan Partisipasi Masyarakat: Dengan menampilkan informasi ini, masyarakat dapat lebih memahami visi dan misi pemerintah desa, serta bagaimana mereka dapat berpartisipasi dalam mencapai tujuan bersama. Ini mendorong partisipasi aktif warga dalam pembangunan desa.

3. Membangun Identitas dan Kebanggaan Desa: Profil desa yang mencakup sejarah, budaya, dan potensi desa membantu membangun identitas dan kebanggaan warga terhadap desa mereka. Ini juga penting untuk menarik perhatian investor atau pengunjung yang mungkin tertarik dengan potensi desa.

4. Peningkatan Pelayanan Publik: Dengan menampilkan sambutan Kepala Desa, warga dapat merasakan kedekatan dan keterlibatan pemimpin mereka dalam keseharian mereka. Sambutan ini juga dapat digunakan untuk menyampaikan informasi penting, arahan, atau pesan motivasi kepada masyarakat.

5. Promosi dan Branding Desa: Profil, Visi, dan Misi desa yang jelas dan menarik dapat digunakan sebagai alat promosi untuk memperkenalkan desa ke khalayak yang lebih luas. Ini penting dalam upaya mengembangkan potensi desa, baik dalam bidang pariwisata, ekonomi, atau sosial.

6. Pedoman dan Acuan Pembangunan: Visi dan Misi desa berfungsi sebagai pedoman bagi seluruh kebijakan dan program kerja pemerintah desa. Menampilkannya di website membantu memastikan bahwa semua pihak, termasuk warga dan pemangku kepentingan lainnya, memahami dan mendukung arah pembangunan desa.

Secara keseluruhan, menampilkan informasi tersebut di website desa adalah langkah penting dalam membangun komunikasi yang efektif antara pemerintah desa dan warganya, serta memperkuat identitas dan arah pembangunan desa.

### Jelaskan solusi yg diinginkan

![image](https://github.com/user-attachments/assets/1d58f847-19cc-4541-95dd-0102a70b5b82)

Fitur ini bisa dimasukkan di sub menu Info Desa - Identitas Desa dengan menambahkan field input baru yaitu : 

1. Profil, 
2. Visi, 
3. Misi, 
4. Sambutan Kepala Desa

![image](https://github.com/user-attachments/assets/32e79068-7bae-460e-8fc8-1c5acea11a40)

Untuk view profil, visi, misi dan sambutan Kepala Desa beserta Foto Kepala Desa semuanya ditampilkan berada di halaman depan.

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

Rilis Umum 2412.0.0

**Comment by andifahruddinakas** [comment]
mas @fachmifaisal, fitu ini sudah ada sebelumnya, sudah bisa ditambahkan melalu artikel statis yang sudah disediakan. atau bisa dibuat secara mandiri dan ditambahkan pada menu webnya.
