### ISSUE TITLE
Bug/error: mohon bantuannya terkait Peta kami di Desa

### ISSUE THREAD

**Issue by alit2310** [OpenSID/OpenSID#8423]
### Jelaskan error yg dialami

Peta kami mengalami no respon, stuck pada saat mengakses peta. Sudah hampir 6 bulan kami mengalami kendala seperti ini. Berikut tangkapan layarnya :
![Screenshot 2024-09-02 095300](https://github.com/user-attachments/assets/aec7ac84-18a3-4225-8b5d-cf551b27c7e0)

### Cara untuk mereplikasi errornya

![Screenshot 2024-09-02 095300](https://github.com/user-attachments/assets/3dffa2ab-d28f-40aa-af8f-484e39653151)

### Hasil yg diharapkan

mohon bantuannya agar peta kami, bisa digunakan seperti biasanya

### Tangkapan layar dan log error

![Screenshot 2024-09-02 095300](https://github.com/user-attachments/assets/0a600c43-044c-4d96-b4e5-e03a1c387a99)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

24.10

### Tema Yang Digunakan

Pusako 2.4

**Comment by MUHAMMADRANGSEL** [comment]
coba reset petanya bang

**Comment by andifahruddinakas** [comment]
pak @alit2310, bisa cek peta lokasi dan wilayah untuk desa, dusun, rt, rw apakah sudah valid. Cek komentar https://github.com/OpenSID/OpenSID/issues/8446

**Comment by alit2310** [comment]
> pak @alit2310, bisa cek peta lokasi dan wilayah untuk desa, dusun, rt, rw apakah sudah valid. Cek komentar #8446

ini screenshoot peta wilayah nya pak, mohon bantuannya
![Screenshot 2024-09-09 143306](https://github.com/user-attachments/assets/9d288bfa-d776-4f32-864c-9a3f2dae7161)
![Screenshot 2024-09-09 143248](https://github.com/user-attachments/assets/cc047ec5-2017-4a3e-a42c-f6dcdf666e50)

**Comment by andifahruddinakas** [comment]
> > pak @alit2310, bisa cek peta lokasi dan wilayah untuk desa, dusun, rt, rw apakah sudah valid. Cek komentar #8446
> 
> ini screenshoot peta wilayah nya pak, mohon bantuannya
> ![Screenshot 2024-09-09 143306](https://github.com/user-attachments/assets/9d288bfa-d776-4f32-864c-9a3f2dae7161)
> ![Screenshot 2024-09-09 143248](https://github.com/user-attachments/assets/cc047ec5-2017-4a3e-a42c-f6dcdf666e50)
> 

Coba hapus map api key nya

**Comment by alit2310** [comment]
> > > pak @alit2310, bisa cek peta lokasi dan wilayah untuk desa, dusun, rt, rw apakah sudah valid. Cek komentar #8446
> > 
> > 
> > ini screenshoot peta wilayah nya pak, mohon bantuannya
> > ![Screenshot 2024-09-09 143306](https://private-user-images.githubusercontent.com/167724918/365536446-9d288bfa-d776-4f32-864c-9a3f2dae7161.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc2Nzc4NjMsIm5iZiI6MTcyNzY3NzU2MywicGF0aCI6Ii8xNjc3MjQ5MTgvMzY1NTM2NDQ2LTlkMjg4YmZhLWQ3NzYtNGYzMi04NjRjLTlhM2YyZGFlNzE2MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkzMFQwNjI2MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNTNkMTFhOTgxMGZmNTE5YTRiZmY2NmJlZTYyYmMyOWQxOTc3N2UyNjJjOGMwYzYyYTQwMzRiMGQ0NzFiZTM1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.FfkAuyMRnqwpC8X92OOuu3ErA5PC6fLyECRlJkjIv2c)
> > ![Screenshot 2024-09-09 143248](https://private-user-images.githubusercontent.com/167724918/365536452-cc047ec5-2017-4a3e-a42c-f6dcdf666e50.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc2Nzc4NjMsIm5iZiI6MTcyNzY3NzU2MywicGF0aCI6Ii8xNjc3MjQ5MTgvMzY1NTM2NDUyLWNjMDQ3ZWM1LTIwMTctNGEzZS1hNDJjLWY2ZGNkZjY2NmU1MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkzMFQwNjI2MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NWIyMTNiZjI5ZjI4MWQ2NjM3ZjhmNTgyZWQyMThhYTE4ZjE2ZWNmYWVlOWY3OTY1ZDgyZDYxODE5ODEyOTYwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.juCBb-59fBYUsKCjQRg0ZJRs7I2hcre-1qLuMvHcbT4)
> 
> Coba hapus map api key nya

tidak bisa dihapus pak, pada saat buka peta sudah tidak ada respon, seperti not responding, jadi tidak bisa mengakses pengaturan petanya

**Comment by alit2310** [comment]
ADA YANG BISA BANTU, MASLAH KAMI TERKAIT PETA ?
KEMANA KAMI BISA KOORDINASI ?
