### ISSUE TITLE
Penanganan Sasaran Pada Peserta Program Bantuan 

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#8424]
Pada kasus database gabungan, cara yang diterapkan saat ini akan suli untuk dilakukan backup. Karena tidak ada relasi antara data sasaran peserta program bantuan dengan masing-masing sasarannya. Sehingga jika dilakukan backu dan direstore kembali, kemungkinan akan terjadi kerancuan.

Solusi yang sudah diterapkan saat ini, bisa melihat contoh pada modul suplemen. Dengan masing-masing tipe sasaran dibuatkan kolomnya beserta relasinya.

Contohh issue serupa : https://github.com/OpenSID/OpenSID/issues/8367

**Comment by agungsugiarto** [comment]
yg dimasud di field relasi apa mas @andifahruddinakas?, saya lihat di tabel `program_peserta` field `kartu_id_pend` sudah ada relasinya.



![Image](https://github.com/user-attachments/assets/98b2ef89-7baa-47d0-b46c-0e23a5692703)

**Comment by andifahruddinakas** [comment]
> yg dimasud di field relasi apa mas @andifahruddinakas?, saya lihat di tabel `program_peserta` field `kartu_id_pend` sudah ada relasinya.
> 
> ![Image](https://private-user-images.githubusercontent.com/10989147/363877215-98b2ef89-7baa-47d0-b46c-0e23a5692703.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzNTA2NjYsIm5iZiI6MTcyNTM1MDM2NiwicGF0aCI6Ii8xMDk4OTE0Ny8zNjM4NzcyMTUtOThiMmVmODktN2JhYS00N2QwLWI0NmMtMGUyM2E1NjkyNzAzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDA3NTkyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYwMWM5NGUzMjJiZTdkNWQ0MDZlNjViZThkMTAxZDRmNjVmNjZkMTVhZGVhMDMzYjY1ZGY5NTcwNWVkOGQ3ZmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jnke7IPZrSCAQn7boCEwgEDrT0mOda1ELx0q-0uesJA)

Sepertinya sudah diterapkan namun dengan cara berbeda, menggunakan 1 relasi yakni penduduk.
