### ISSUE TITLE
Bug/error: - Buku rekapitulasi jumlah penduduk tidak sesuai

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8426]
### Jelaskan error yg dialami

Buku rekapitulasi jumlah penduduk tidak sama dengan jumlah di menu penduduk dan wilayah administratif

### Cara untuk mereplikasi errornya

1. klik Modul Buku Administrasi Desa
2. klik Administrasi Penduduk
3. Klik Buku Rekapitulasi Jumlah Penduduk
4. total penduduk

### Hasil yg diharapkan

data tidak berbeda beda dengan menu penduduk, laporan bulanan penduduk, wilayah administratif

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/8e7068cc-794c-4a5d-baef-8a532a92c0a5)

Screenshoot dari Menu Wilayah Administratif, Laporan Bulanan : 

![image](https://github.com/user-attachments/assets/95115dc7-8dcb-48bf-803e-ddbae22b64e1)

![image](https://github.com/user-attachments/assets/314ce68d-a383-4d07-be50-caae0daca24d)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Versi 2409.0.0-premium

### Informasi tambahan

Replikasi di Berputar

**Comment by andifahruddinakas** [comment]
mas @rgrahardi, sertakan contoh databasenya

**Comment by rgrahardi** [comment]
mas @andifahruddinakas saya replikasi di berputar mas

**Comment by andifahruddinakas** [comment]
> mas @andifahruddinakas saya replikasi di berputar mas

Informasi yg diperlukan bisa ditambahkan di bagian **Infromasi Tambahan**

**Comment by agungsugiarto** [comment]
bagaiaman cara replikasinya mas @rgrahardi, @andifahruddinakas case apa yang dilakukan ketika menambah atau mengubah penduduk?

**Comment by andifahruddinakas** [comment]
> bagaiaman cara replikasinya mas @rgrahardi, @andifahruddinakas case apa yang dilakukan ketika menambah atau mengubah penduduk?

Bisa cek langsung database yg digunakan di berputar atau terlampir. Itu database lama, bisa lakukan pengecekan.

**Comment by agungsugiarto** [comment]
@andifahruddinakas, @rgrahardi memeriksanya saja sangat sulit karena ini terkait kode peristiwa dan tanggal lapor, yg diperlukan informasi yang jelas alur peristiwa apa yang menyebabkan data tidak sama.

**Comment by andifahruddinakas** [comment]
> @andifahruddinakas, @rgrahardi memeriksanya saja sangat sulit karena ini terkait kode peristiwa dan tanggal lapor, yg diperlukan informasi yang jelas alur peristiwa apa yang menyebabkan data tidak sama.

ini menggunakan data lama, dari datanya masuk dari tambah penduduk versi lama. Yg bisa dilakukan yakni membuat halaman periksa data terkait kode peristiwa yg tidak sesuai. Issue yang sama yg solusinya yakni membuat halaman periksa https://github.com/OpenSID/OpenSID/issues/8368

**Comment by andifahruddinakas** [comment]
masing2 kurang 1 penduduk laki-laki dan 1 penduduk perempuan.
![image](https://github.com/user-attachments/assets/fe658329-64cb-4047-b545-f1d18cd15a38)

![image](https://github.com/user-attachments/assets/c7cc815b-3870-42af-adbc-4a08c4795ce8)

**Comment by agungsugiarto** [comment]
mas @andifahruddinakas setelah saya telusuri dengan **sangat melelahkan**, penyebabnya karena query `id_kk` dan `kk_level` null pada tabel penduduk. Seharusnya bagaimana perbaikan untuk field ini?

**Comment by andifahruddinakas** [comment]
> mas @andifahruddinakas setelah saya telusuri dengan **sangat melelahkan**, penyebabnya karena query `id_kk` dan `kk_level` null pada tabel penduduk. Seharusnya bagaimana perbaikan untuk field ini?

Untuk menghitung jumlah penduduk (jiwa) seharusnya tidak memerlukan id_kk dan kk_level. Bisa diperbaiki querynya sama dengan di wilayah administratif.
