### ISSUE TITLE
Bug/error: Fungsi getAttributes

### ISSUE THREAD

**Issue by khiar-rara** [OpenSID/OpenSID#8427]
### Jelaskan error yg dialami

Tidak tahu kenapa ?/
Severity: error --> Exception: array_key_exists(): Argument #2 ($array) must be of type array, null given /home/***/public_html/vendor/illuminate/database/Eloquent/Concerns/HasAttributes.php 438

### Cara untuk mereplikasi errornya

1. Cetak surat : saat pengambilan data penduduk kadang tidak bisa dimuat. Kadang baru berhasil cetak 1-2 jenis surat, cetak surat berikutnya eror dan halaman web tidak bisa berfungsi.
2. Jika diclear cache dan kuki browser, halaman web dapat diakses normal

### Hasil yg diharapkan

Eror teratasi atau setidaknya ada petunjuk/solusi perbaikan jika kesalahan terjadi dipihak kami

### Tangkapan layar dan log error

![IMG_20240902_224353](https://github.com/user-attachments/assets/9820e005-2f07-435f-af11-1714112fd978)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v2409.0.0-premium

### Tema Yang Digunakan

Esensi

### Informasi tambahan

-

**Comment by agungsugiarto** [comment]
Pak @khiar-rara terima kasih sudah melaporkan issue, untuk surat apa yang bermasalah pak? Pastikan di demo berputar juga menemukan masalah yang sama, jika hanya ditemukan masalah di tempat bapak harap lampirkan database untuk diperiksa ke telegram @rgrahardi. Terima kasih

**Comment by khiar-rara** [comment]
sesuai saran pak @agungsugiarto. saya tidak menemui eror tersebut di berputar. saya akan mencoba menghubungi pak @rgrahardi jika erornya masih terus berulang. sementara akan kami cek kembali barangkali ada pengaturan yang salah dengan merujuk ke web berputar. maaf sudah merepotkan. saya close isu ini. terima kasih
