### ISSUE TITLE
Bug/error: Informasi Publik tidak urut "terbaru", document, "tidak benomor" dan "route" nya salah.

### ISSUE THREAD

**Issue by ilhamwahyu-ni** [OpenSID/OpenSID#8428]
### Jelaskan error yg dialami

Dokumen informasi publik, akan menjadi arsip desa

### Cara untuk mereplikasi errornya

![image](https://github.com/user-attachments/assets/091614d6-666c-4d29-b4cd-149a82283a13)

![image](https://github.com/user-attachments/assets/16df0c21-49e1-441a-b805-010d20d6c097)

![image](https://github.com/user-attachments/assets/b52af563-f916-4a16-9616-b82d0f12d59e)

### Hasil yg diharapkan

- urutkan dari yang terbaru dibuat..
-  ada nomor dokument
- benarkan routenya..

### Tangkapan layar dan log error

normal

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

 2409.0.0

**Comment by habibie11** [comment]
pak @ilhamwahyu-ni saya coba replikasi di berputar data informasi publik masuk ke modul informasi publik bukan di arsip desa, atau apakah ada yang salah replikasi saya.
cc mas @andifahruddinakas 
![image](https://github.com/user-attachments/assets/bfb7d5c0-92d8-4399-abc0-47279d2300fa)

**Comment by andifahruddinakas** [comment]
> pak @ilhamwahyu-ni saya coba replikasi di berputar data informasi publik masuk ke modul informasi publik bukan di arsip desa, atau apakah ada yang salah replikasi saya. cc mas @andifahruddinakas ![image](https://private-user-images.githubusercontent.com/56639378/363888806-bfb7d5c0-92d8-4399-abc0-47279d2300fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzNTA1NjYsIm5iZiI6MTcyNTM1MDI2NiwicGF0aCI6Ii81NjYzOTM3OC8zNjM4ODg4MDYtYmZiN2Q1YzAtOTJkOC00Mzk5LWFiYzAtNDcyNzlkMjMwMGZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDA3NTc0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0MDkzNWIwYzVjMTMyNjk0MjMzNzc5M2ExZTUyNWYxMzYxODUwZWZjZGJhMjYyZmE0NGE1YjRhMTVkMjdkN2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KZOxfbNTG5IVkfbV9rLrPkZWotpoN5AyhXoW-6Qasfk)

kategori dokumen desa

![image](https://github.com/user-attachments/assets/e39a84bf-32b1-432c-9fb0-2f7c9db95e4f)
