### ISSUE TITLE
Bug/error: Import surat mengalami error

### ISSUE THREAD

**Issue by pandigresik** [OpenSID/OpenSID#8429]
### Jelaskan error yg dialami

Terjadi error ketika melakukan import surat tinymce

### Cara untuk mereplikasi errornya

Lakukan import sebagaimana divideo

[template_surat_tinymce_03_09_2024.json](https://github.com/user-attachments/files/16842152/template_surat_tinymce_03_09_2024.json)

[Screencast from 03-09-24 07:51:15.webm](https://github.com/user-attachments/assets/102306ba-4243-47b1-8147-156913bb844c)

### Hasil yg diharapkan

Berhasil import surat

### Tangkapan layar dan log error

[Screencast from 03-09-24 07:51:15.webm](https://github.com/user-attachments/assets/102306ba-4243-47b1-8147-156913bb844c)

log `Severity: error --> Exception: array_merge(): Argument #2 must be of type array, null given /home/berputar.opendesa.id/public_html/donjo-app/controllers/Surat_master.php 956`

![image](https://github.com/user-attachments/assets/9ad4a139-fa06-4e25-916a-a7c60e50ed41)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2409.0.0

**Comment by andifahruddinakas** [comment]
Sudah disesuaikan melalui commit https://github.com/OpenSID/premium/commit/cc30adc7ca93faabfab912cbee5f609808ccbc9d
