### ISSUE TITLE
Gagal Update NIK Penduduk

### ISSUE THREAD

**Issue by tofikcilik** [OpenSID/OpenSID#843]
Terjadi Error ketika saya mengubah NIK Penduduk yang awalnya 0, karena sudah mendapatkan NIK lengkap maka saya masukkan NIK yang sesuai dengan data Penduduk tsb. Apakah ini bug?
![bug update nik](https://user-images.githubusercontent.com/33724406/37093177-0d83bbf2-2241-11e8-9ced-bcf0a8cd9c74.png)

**Comment by eddieridwan** [comment]
Error ini bukan karena perubahan NIK. Terjadi karena anda belum menjalankan Database > Migrasi DB untuk mengubah struktur database sesuai dengan versi OpenSID yg anda gunakan.
