### ISSUE TITLE
Bug/error: gagal periksa permohonan surat

### ISSUE THREAD

**Issue by sidikbukandalbo** [OpenSID/OpenSID#8431]
### Jelaskan error yg dialami

Ketika Klik Periksa Permohonan Surat Layanan Mandiri terjadi Error

### Cara untuk mereplikasi errornya

1. pergi ke permohonan surat
2. klik tombol sedang diperiksa

### Hasil yg diharapkan

dapat memeriksa dan mencetak surat

### Tangkapan layar dan log error

<img width="492" alt="Capture" src="https://github.com/user-attachments/assets/317ebf34-64d7-4d38-a989-b43203aba209">

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v2409.0.0

### Tema Yang Digunakan

Denava

**Comment by andifahruddinakas** [comment]
mas @sidikbukandalbo, bisa sertakan log errornya

**Comment by andifahruddinakas** [comment]
![image](https://github.com/user-attachments/assets/ecf82c27-658a-441a-a0a5-24b5be501d7a)

**Comment by ndunks** [comment]
sama kena juga, cek ini untuk fixnya:

https://github.com/ndunks/OpenSID/commit/b24f24f7b2da478a92267277bc135be638fd0ddb

Tapi kyknya beda versi ya.

**Comment by sidikbukandalbo** [comment]
> mas @sidikbukandalbo, bisa sertakan log errornya

<img width="512" alt="Capture2" src="https://github.com/user-attachments/assets/f7552b22-06e3-4c85-b771-6ae7bec98a40">

itu pak log.nya

**Comment by andifahruddinakas** [comment]
Selesai melalui commit https://github.com/OpenSID/premium/commit/a2ba65748d6cd6151b808b09b60c941f7a24e301

**Comment by sidikbukandalbo** [comment]
> Selesai melalui commit https://github.com/OpenSID/premium/commit/a2ba65748d6cd6151b808b09b60c941f7a24e301

nda bisa dibuka link.nya pak
