### ISSUE TITLE
Bug/error: error ketika melihat arsip layanan surat  keterangan error "TCPDF ERROR: Could not include font definition file: bookman_old_style"

### ISSUE THREAD

**Issue by lwiradarma** [OpenSID/OpenSID#8435]
### Jelaskan error yg dialami

<img width="959" alt="error saat akses arsip layanan surat" src="https://github.com/user-attachments/assets/a570a704-4cc8-49c2-9772-27fd0eabe218">

### Cara untuk mereplikasi errornya

1. pergi ke halaman layanan surat
2. klik tombol arsip layanan
3. klik salah satu surat yang ingin di cetak
4. lihat error

### Hasil yg diharapkan

arsip layanan surat bisa di cetak kembali

### Tangkapan layar dan log error

<img width="959" alt="error saat akses arsip layanan surat" src="https://github.com/user-attachments/assets/e5eb9945-de7e-44f2-b81d-1ee65607324f">

### Rilis Versi OpenSID

Rilis Umum

### Versi OpenSID

v2409.0.0

### Tema Yang Digunakan

denatra

**Comment by pandigresik** [comment]
Studi kasus gagal pratinjau surat karena font tidak ditemukan

https://youtu.be/ySwQCiI-ZXE
