### ISSUE TITLE
Sebutan Dusun

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#8437]
Pindahkan pengaturan sebutan dusun pada modul wilayah administrasi .
![image](https://github.com/user-attachments/assets/cb631c86-02b7-409e-b15c-dc435e0d5ef3)

**Comment by agungsugiarto** [comment]
Maksudnya dipindah seperti apa mas @andifahruddinakas ?

**Comment by andifahruddinakas** [comment]
> Maksudnya dipindah seperti apa mas @andifahruddinakas ?

Letakkan di pojok kanan atas

**Comment by agungsugiarto** [comment]
Menu wilayah administratif dipindah ke pojok kanan atas?

**Comment by andifahruddinakas** [comment]
> Menu wilayah administratif dipindah ke pojok kanan atas?

Buat seperti ini
![image](https://github.com/user-attachments/assets/2541edd5-751a-4945-9ae7-d5f75f7fad5e)
