### ISSUE TITLE
Dragable pada modul pengurus

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#8439]
Fungsi Dragable pada modul pengurus

![image](https://github.com/user-attachments/assets/61e8b1ed-99d0-4b9f-aa75-d1a708aabf76)

**Comment by habibie11** [comment]
maksudnya bagaimana mas @andifahruddinakas , bukankah draggable sudah ada dan berfungsi?
<img width="287" alt="image" src="https://github.com/user-attachments/assets/f6a7ba5c-2ea7-41a2-90cd-35428391afbe">

**Comment by andifahruddinakas** [comment]
> maksudnya bagaimana mas @andifahruddinakas , bukankah draggable sudah ada dan berfungsi? <img alt="image" width="287" src="https://private-user-images.githubusercontent.com/56639378/364220909-f6a7ba5c-2ea7-41a2-90cd-35428391afbe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0MjU3NjMsIm5iZiI6MTcyNTQyNTQ2MywicGF0aCI6Ii81NjYzOTM3OC8zNjQyMjA5MDktZjZhN2JhNWMtMmVhNy00MWEyLTkwY2QtMzU0MjgzOTFhZmJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA0VDA0NTEwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYwOTk0ODhjOWFmNzEwNjFiOTYwNWM5ZTFkZTUxNjZjMzAyNTU1ZmJhMDVmMzZhZWRhYmQ0YmQyMDRmNzc4ZWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6lvxoowu1ePFqmDa7KppmpLVKv6qTL2mFJeid0QNB60">

cek telegram
