### ISSUE TITLE
Bug/error: Import surat TinyMCE error

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#8443]
### Jelaskan error yg dialami

pada saat import surat tiny MCE terrjadi error

### Cara untuk mereplikasi errornya

pada saat import surat tiny MCE terrjadi error
![image](https://github.com/user-attachments/assets/148634e6-65c2-48ef-87b0-ef550b421080)

### Hasil yg diharapkan

bisa import surat seperti versi sebelumnya

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/2fd629a5-05a9-435b-9b3d-0c43b7f410ad)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

24.09.0.0 PREMIUM

**Comment by MUHAMMADRANGSEL** [comment]
ini terjadi di SURAT LAYANAN kalau SURAT DINAS aman

**Comment by andifahruddinakas** [comment]
Duplicate of https://github.com/OpenSID/OpenSID/issues/8429
