### ISSUE TITLE
Manajemen Pengguna

### ISSUE THREAD

**Issue by SahlaniAfnan** [OpenSID/OpenSID#845]
Ketika dibuatkan pengguna/user: Operator, Redaksi maupun Kontributor, tidak bisa login

![operator](https://user-images.githubusercontent.com/15683308/37108357-7b7029b6-2269-11e8-9cf4-4a0a9f3b8d16.jpg)

![redaksi](https://user-images.githubusercontent.com/15683308/37108818-d1e752e6-226a-11e8-9423-eb7a22589807.jpg)

![kontributor](https://user-images.githubusercontent.com/15683308/37108931-2fd79f64-226b-11e8-90bb-678fd8965cb5.jpg)

**Comment by nangalan** [comment]
makasih kang @MUHAMMADRANGSEL  Info yang sangat membantu. Namun ketika login menjadi operator pada saat mencoba menu analisis,  plan dan peta aplikasi logout seketika. mohon pencerahan........

**Comment by MUHAMMADRANGSEL** [comment]
Memang sekarang belum TDK ada akses untuk operator

Pada tanggal 9 Mar 2018 3.02 AM, "Sahlani Afnan" <notifications@github.com>
menulis:

**Comment by nangalan** [comment]
Oke matur suwun Infonya Kang @MUHAMMADRANGSEL mudah2 kedepan OpenSID lebih sempurna lagi. sebab manajemen pengguna berdampak pada keamanan (lihat, tambah, edit maupun hapus) data. Salam OpenSID

**Comment by eddieridwan** [comment]
Sudah diterapkan, berdasarkan spesifikasi hak akses di http://bit.ly/2Vhqmyz
