### ISSUE TITLE
Klik Statistik dari Peta Desa di halaman web tidak berfungsi

### ISSUE THREAD

**Issue by rockymakasar** [OpenSID/OpenSID#8455]
### Jelaskan error yg dialami

Tersedia peta wilayah Desa yang ditampilkan di halaman web,  juga dengan pilihan statistik yang dapat dipilih untuk melihat statistik penduduk melalui peta desa
namun saat diklik tidak berfungsi
![image](https://github.com/user-attachments/assets/911df4ce-23b7-4878-9742-dbaea8d8be5a)

### Cara untuk mereplikasi errornya

1. Klik menu peta desa
2. aktifkan Peta wilayah desa
3. arahkan kursor ke wilayah peta
4. akan muncul keterangan wilayah Desa
5. klik Statistik Penduduk
6. Pilih salah satu menu statistik
7. tidak berfungsi

### Hasil yg diharapkan

Normal

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/7dc2b703-47d4-4ca8-84df-de36b7d1e18c)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

OpenSID 2409.0.0-premium

### Tema Yang Digunakan

Batuah

### Informasi tambahan

Error juga terjadi di peta wilayah dusun

**Comment by andifahruddinakas** [comment]
pak @rockymakasar, untuk setiap laporan terkait halaman depan sebaiknya menggunakan tema bawaan.

**Comment by rockymakasar** [comment]
ok bung

**Comment by rockymakasar** [comment]
di berputar yang menggunakan tema natra klik menu peta terjadi error 500
![image](https://github.com/user-attachments/assets/8f36e088-685b-44d6-a093-8e01bf7b2428)

**Comment by andifahruddinakas** [comment]
> di berputar yang menggunakan tema natra klik menu peta terjadi error 500 ![image](https://private-user-images.githubusercontent.com/94730877/365908636-8f36e088-685b-44d6-a093-8e01bf7b2428.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5NDgyNTgsIm5iZiI6MTcyNTk0Nzk1OCwicGF0aCI6Ii85NDczMDg3Ny8zNjU5MDg2MzYtOGYzNmUwODgtNjg1Yi00NGQ2LWEwOTMtOGUwMWJmN2IyNDI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEwVDA1NTkxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwYzUyOWViYzlhNDMxMTE3NmJjYjM0NzlhNWVmY2Q0MjliODJiNzFjNGQ3ZTIzYjE0NDNkOTk5ZGE3ZGJhNzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PITNDMJL7ZiMBsn9ZAiedmPpSzi_5hkztU4J3IKzwd4)

Untuk yg ini sudah disesuaikan https://github.com/OpenSID/premium/commit/1bfb724f19ab072563f02ebc4da95cc39675e572

bisa gunakan tema esensi

**Comment by rgrahardi** [comment]
mohon infonya pak @rockymakasar apakah issue masih terjadi ? jika iya dapat dibawakan ke klinik bug pak

**Comment by rockymakasar** [comment]
Sebentar saya dtg di klinik bug pukul 16.00
