### ISSUE TITLE
Bug/error: Belum bisanya hasil cetak Peraturan di Desa dan Keputusan Kepala Desa, urut menyesuaikan Nomor urutan penetapan Peraturan atau Keputusan tersebut

### ISSUE THREAD

**Issue by mah-mudi** [OpenSID/OpenSID#8461]
### Jelaskan error yg dialami

Belum bisanya hasil cetak Peraturan di Desa dan Keputusan Kepala Desa, urut menyesuaikan Nomor atau tanggal urutan penetapan nya

### Cara untuk mereplikasi errornya

1. Buku Administrasi Umum
2. Buku Peraturan Di Desa dan Buku Keputusan Kepala Desa

### Hasil yg diharapkan

Hasil cetak Peraturan di Desa dan Keputusan Kepala Desa, dapat urut menyesuaikan Nomor atau tanggal urutan penetapan nya

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/caa1b83b-564f-4060-8a40-354ff0af5b3d)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

24.09 premium

### Tema Yang Digunakan

silir

### Informasi tambahan

-

**Comment by agungsugiarto** [comment]
Pak @mah-mudi urutannya ascending atau descending ?

**Comment by mah-mudi** [comment]
@agungsugiarto harapannya hasil cetakan kolom nomor urut 1 menampilkan peraturan/keputusan nomor 1 dan seterusnya.

sehingga pengurutan nomor terurut, terstruktur dengan baik.

**Comment by agungsugiarto** [comment]
Jadi mau berdasarkan nomor atau tanggal ditetapkan pak?

**Comment by mah-mudi** [comment]
@agungsugiarto Urut berdasarkan Nomor penetapan
