### ISSUE TITLE
Permintaan fitur: TAMBAHKAN KODE ISIAN STATUS PERKAWINAN PADA PELAKU SELAIN PELAKU UTAMA

### ISSUE THREAD

**Issue by pujocahyono** [OpenSID/OpenSID#8463]
### Apa kekurangan yg ingin diatasi?

KODE ISIAN STATUS PERKAWINAN TIDAK ADA PADA KODE ISIAN PELAKU SELAIN PELAKU UTAMA.
KARENA DI BEBERAPA SURAT DIBUTUHKAN ISIAN STATUS PERKAWINAN PADA PELAKU SELAIN PELAKU UTAMA.

### Jelaskan solusi yg diinginkan

TAMBAHKAN KODE ISIAN **STATUS PERKAWINAN** PADA PELAKU SELAIN PELAKU UTAMA.

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

Rilis Premium 2410.0.0

### Informasi tambahan

-

**Comment by MUHAMMADRANGSEL** [comment]
Sekalian NAMA AYAH JUGA

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/4094
