### ISSUE TITLE
Mapbox Key Tidak Valid atau Expired

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#8468]
Terjadi gagal muat halaman peta jenis mapbox satelit-street jika mapbox key tidak valid atau expired.
![image](https://github.com/user-attachments/assets/4af0184e-2e49-495c-bfea-d4f41e43847a)

Contoh : 
![image](https://github.com/user-attachments/assets/ad605e1f-2307-43d0-b1ab-881f51ceb9f1)

`pk.eyJ1IjoicHV0cmlrYWhmaSIsImEiOiJjbDVobTB0dmgwYW8xM2NxcWwwM2MzOTlvIn0.vbXHgu2SEOpgJChWh1mz0A`

Solusi : 
- Sebaiknya tampilkan notifikasi jika mapbox key tidak valid.
- Jika tidak valid, otomatis menggunakan jenis map default (openstreap map)

**Comment by agungsugiarto** [comment]
mas @andifahruddinakas jika token tidak valid atau expired di ubah ke jenis openstreap map juga tidak bisa mas, jadi harus valid tokennya.

**Comment by ariandii** [comment]
info tambahan, hal tersebut tidak hanya terjadi di halaman peta, tetapi di semua tampilan peta, seperti:
info desa -> lokasi kantor desa, wilayah desa,
widget lokasi dan wilayah
peta di frontend

yang menggunakan  <?= setting('mapbox_key') ?> dan MAPBOX_KEY
