### ISSUE TITLE
Bug: Error penambahan peserta program Bantuan sasaran Kelompok

### ISSUE THREAD

**Issue by Topohudoyo** [OpenSID/OpenSID#847]
Info Eror Program Bantuan, buat mas Ridwan n temen2 programer aku temukan ada error pada fitur prgram **bantuan katagori Kelompok** yakni tidak bisa operasional halaman jadi blank ketika kita memasukan peserta program bantuan untuk katagori kelompok (lihat gambar) ini terjadi pada aplikasi online maupun ofline saya cek di versi 2.9 dan 2.10 hasilnya sama. mohon untuk bisa di perbaharui
![error program bantuan-1](https://user-images.githubusercontent.com/25343964/37147146-87d34938-22f8-11e8-8225-953d6e986fe3.jpg)

**Comment by eddieridwan** [comment]
Sudah dicommit ke master. Sekalian perbaiki menampilkan daftar program untuk peserta, untuk semua sasaran.
