### ISSUE TITLE
Bug/error: Agenda pada Widget tidak tampil di halaman Web (depan)

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/OpenSID#8472]
### Jelaskan error yg dialami

Ketika menambahkan artikel pada agenda terdapat notifikasi gagal simpan, namun agenda berhasil diismpan. 
Ketika cek log terdapat informasi bahwa sudut rotasi diperlukan untuk memutar gambar. 

### Cara untuk mereplikasi errornya

1. Pergi ke halaman admin
2. Klik Admin Web, Artikel 
3. Pada Artikel Statis Pilih Agenda
4. Tambah Agenda dan Gambar

### Hasil yg diharapkan

Normal dapat muncul pada widget agenda.

### Tangkapan layar dan log error

![agenda1](https://github.com/user-attachments/assets/b5bef03c-5094-4184-b1e2-ed00e4db1c6c)
![agenda](https://github.com/user-attachments/assets/38e0e306-ebfa-48cd-b1da-26d63a3e2f2b)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v2409.0.1

### Tema Yang Digunakan

Silir

### Informasi tambahan

di versi v2409.0.0 normal

**Comment by andifahruddinakas** [comment]
Sudah diselesaikan melalui commit https://github.com/OpenSID/premium/commit/67a34bc9f095849f790cab6bc9b57381046773b6
