### ISSUE TITLE
Bug/error: menu 'hasil cetak aset tetap lainnya' harusnya KIB E bukan KIB F

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8476]
### Jelaskan error yg dialami

hasil cetak menu 'aset tetap lainnya' harusnya KIB E bukan KIB F

### Cara untuk mereplikasi errornya

1. Modul Sekretariat
2. Menu Inventaris
3. Sub Menu Aset tetap Lainnya
4. cetak

### Hasil yg diharapkan

KIB E bukan KIB F

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/85a270b2-b939-4996-8126-a646d02d17cf)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Versi 2409.0.1-premium

**Comment by andifahruddinakas** [comment]
Sduah diselesaikan melalui commit https://github.com/OpenSID/premium/commit/8fd1acf3c32f4589fcda697701c14ba8b594ddc0
