### ISSUE TITLE
Bug/error: gagal impor  penduduk data penduduk tidak muncul di menu penduduk 

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8478]
### Jelaskan error yg dialami

gagal impor penduduk pemberitahuan data dobel, data di menu penduduk kosong, tetapi di statistik tercatat data penduduknya

### Cara untuk mereplikasi errornya

1. impor penduduk
2. cek menu penduduk
3. cek statistik penduduk

### Hasil yg diharapkan

jika impor gagal data penduduk, data penduduk tidak tercatat di statistik penduduk

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/325165df-346d-44e7-a3f3-de116a3a982a)

![image](https://github.com/user-attachments/assets/7099da11-8e4a-446b-b928-902ed3643df1)

![image](https://github.com/user-attachments/assets/e317204d-7537-4846-ab9f-3a530e437c36)

![image](https://github.com/user-attachments/assets/87e2abad-658a-4824-9f8d-e4e7eb97518b)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Versi 2409.0.1-premium

### Informasi tambahan

Data Impor dan Database sudah saya PM, sudah di klik perbaiki di halaman periksa tetap tidak selesai masalahnya

**Comment by habibie11** [comment]
setelah dilakukan pengecekan menggunakan db dan file excel terlampir, data penduduk sudah berhasil terimport lalu cek di modul penduduk tidak ada penduduk sedangkan di statistik ada, itu karna pengaturan admin akses_wilayahnya aktif dan tidak ada wilayah yang dipilih sehingga dimodul penduduk tidak tampil penduduk wilayah manapun.

![image](https://github.com/user-attachments/assets/84121a05-e1fc-4c5e-b029-0b8fe924c288)
tes import

![image](https://github.com/user-attachments/assets/2c8ddd46-7523-4650-b47c-e2ea4753991f)
penyebab tidak tampil penduduk dari data impor

<img width="695" alt="image" src="https://github.com/user-attachments/assets/724cd3c6-acbf-409b-b32b-3415dd22951b">

setelah pilih wilayah yang bisa diakses di pengaturan admin, penduduk dari impor tampil dimodul penduduk

solusi bisa pilih wilayah yang ingin bisa diakses oleh admin tersebut atau nonaktifkan pengaturan akses_wilayah jika tidak dibutuhkan cc mas @rgrahardi 

mohon koreksi jika ada yang salah cc mas @andifahruddinakas

**Comment by andifahruddinakas** [comment]
> setelah dilakukan pengecekan menggunakan db dan file excel terlampir, data penduduk sudah berhasil terimport lalu cek di modul penduduk tidak ada penduduk sedangkan di statistik ada, itu karna pengaturan admin akses_wilayahnya aktif dan tidak ada wilayah yang dipilih sehingga dimodul penduduk tidak tampil penduduk wilayah manapun.
> 
> ![image](https://private-user-images.githubusercontent.com/56639378/369366101-84121a05-e1fc-4c5e-b029-0b8fe924c288.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4MjkyMzgsIm5iZiI6MTcyNjgyODkzOCwicGF0aCI6Ii81NjYzOTM3OC8zNjkzNjYxMDEtODQxMjFhMDUtZTFmYy00YzVlLWIwMjktMGI4ZmU5MjRjMjg4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIwVDEwNDIxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJmZmI2YzI2ODdmMDI3MWUxYzdjZjUyZGJjNzE1OTkwOWEzZDQ4NWNlYTUzYTk1ZGE3MTEzNzEyN2M4MjdlZWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.raZ2UIIsrrMb3odFlrCGonKRG-D2FUc_fAsi-jTawv0) tes import
> 
> ![image](https://private-user-images.githubusercontent.com/56639378/369366431-2c8ddd46-7523-4650-b47c-e2ea4753991f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4MjkyMzgsIm5iZiI6MTcyNjgyODkzOCwicGF0aCI6Ii81NjYzOTM3OC8zNjkzNjY0MzEtMmM4ZGRkNDYtNzUyMy00NjUwLWI0N2MtZTJlYTQ3NTM5OTFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIwVDEwNDIxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0YjQwZDVhNzkwZWNmZDVlZjAxYTdlZDNiZjBmZjRjOTNiZmVhYjVkZGExNGI4MDhmY2NlYjc2ZGRhOGE4YjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.9Paeg3IRTr-t_oCkxcJsBbyHjOR55vHTaqwSD9R9xT0) penyebab tidak tampil penduduk dari data impor
> 
> ![image](https://private-user-images.githubusercontent.com/56639378/369366726-d4a1fd67-c75f-4423-8a97-ddcd82adf1db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4MjkyMzgsIm5iZiI6MTcyNjgyODkzOCwicGF0aCI6Ii81NjYzOTM3OC8zNjkzNjY3MjYtZDRhMWZkNjctYzc1Zi00NDIzLThhOTctZGRjZDgyYWRmMWRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIwVDEwNDIxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhNGJmZDVmNTBlZmY4NmVkNTAyMDRmNTkzNzg3NzI2YjVjNzEwN2Y2NGUzNTUxMDBhZmExMGMyNzc1Y2JkNTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.tFT1koP2uSHuoT8LyxRZW3BQR9ZoQrWX94F5Vsn4ahk) setelah pilih wilayah yang bisa diakses di pengaturan admin, penduduk dari impor tampil dimodul penduduk
> 
> solusi bisa pilih wilayah yang ingin bisa diakses oleh admin tersebut atau nonaktifkan pengaturan akses_wilayah jika tidak dibutuhkan cc mas @rgrahardi
> 
> mohon koreksi jika ada yang salah cc mas @andifahruddinakas

Jika akses wilayahnya tidak aktif artinya bisa melihat semua penduduk. Namun jika kondisinya aktif namun tidak ada wilayah aksesnya, bisa dibuat tidak aktif (validasi saat simpan pengguna). Untuk yg sudah terlanjur seperti itu, perlu ditambahkan pengecekan aktif dan ada wilayah yang dibatasi.

**Comment by andifahruddinakas** [comment]
> > setelah dilakukan pengecekan menggunakan db dan file excel terlampir, data penduduk sudah berhasil terimport lalu cek di modul penduduk tidak ada penduduk sedangkan di statistik ada, itu karna pengaturan admin akses_wilayahnya aktif dan tidak ada wilayah yang dipilih sehingga dimodul penduduk tidak tampil penduduk wilayah manapun.
> > ![image](https://private-user-images.githubusercontent.com/56639378/369366101-84121a05-e1fc-4c5e-b029-0b8fe924c288.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4MjkyMzgsIm5iZiI6MTcyNjgyODkzOCwicGF0aCI6Ii81NjYzOTM3OC8zNjkzNjYxMDEtODQxMjFhMDUtZTFmYy00YzVlLWIwMjktMGI4ZmU5MjRjMjg4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIwVDEwNDIxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJmZmI2YzI2ODdmMDI3MWUxYzdjZjUyZGJjNzE1OTkwOWEzZDQ4NWNlYTUzYTk1ZGE3MTEzNzEyN2M4MjdlZWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.raZ2UIIsrrMb3odFlrCGonKRG-D2FUc_fAsi-jTawv0) tes import
> > ![image](https://private-user-images.githubusercontent.com/56639378/369366431-2c8ddd46-7523-4650-b47c-e2ea4753991f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4MjkyMzgsIm5iZiI6MTcyNjgyODkzOCwicGF0aCI6Ii81NjYzOTM3OC8zNjkzNjY0MzEtMmM4ZGRkNDYtNzUyMy00NjUwLWI0N2MtZTJlYTQ3NTM5OTFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIwVDEwNDIxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0YjQwZDVhNzkwZWNmZDVlZjAxYTdlZDNiZjBmZjRjOTNiZmVhYjVkZGExNGI4MDhmY2NlYjc2ZGRhOGE4YjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.9Paeg3IRTr-t_oCkxcJsBbyHjOR55vHTaqwSD9R9xT0) penyebab tidak tampil penduduk dari data impor
> > ![image](https://private-user-images.githubusercontent.com/56639378/369366726-d4a1fd67-c75f-4423-8a97-ddcd82adf1db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4MjkyMzgsIm5iZiI6MTcyNjgyODkzOCwicGF0aCI6Ii81NjYzOTM3OC8zNjkzNjY3MjYtZDRhMWZkNjctYzc1Zi00NDIzLThhOTctZGRjZDgyYWRmMWRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIwVDEwNDIxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhNGJmZDVmNTBlZmY4NmVkNTAyMDRmNTkzNzg3NzI2YjVjNzEwN2Y2NGUzNTUxMDBhZmExMGMyNzc1Y2JkNTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.tFT1koP2uSHuoT8LyxRZW3BQR9ZoQrWX94F5Vsn4ahk) setelah pilih wilayah yang bisa diakses di pengaturan admin, penduduk dari impor tampil dimodul penduduk
> > solusi bisa pilih wilayah yang ingin bisa diakses oleh admin tersebut atau nonaktifkan pengaturan akses_wilayah jika tidak dibutuhkan cc mas @rgrahardi
> > mohon koreksi jika ada yang salah cc mas @andifahruddinakas
> 
> Jika akses wilayahnya tidak aktif artinya bisa melihat semua penduduk. mungkin perlu dicek jg, apakah aktif dan memiliki data. Perlu ditambahkan validasi pada pengaturan menu jika aktif harus memilih salah 1.

**Comment by ariemusbandi** [comment]
Terima kasih, masalah nya solve
