### ISSUE TITLE
Prodeskel - buat analisis master keluarga

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#848]
Kita mulai menggabungkan data prodeskel ke menu Analisis. Untuk itu kita perlu bakukan analisis masternya. Issue ini untuk analisis master pengumpulan data keluarga.

Issue terkait:
* #849 
* #850

**Comment by MUHAMMADRANGSEL** [comment]
Untuk Analisis DDK Prodeskel dan Format Impor nya
[Analisis DDK dan Format Impor  Prodeskel.zip](https://github.com/OpenSID/OpenSID/files/1811769/Analisis.DDK.dan.Format.Impor.Prodeskel.zip)

**Comment by MUHAMMADRANGSEL** [comment]
dan sudah bisa diuji coba di http://sid.bangundesa.info/index.php/first

**Comment by eddieridwan** [comment]
@MUHAMMADRANGSEL mohon isi contoh isian data prodeskel menggunakan keluarga yang ada di data contoh awal yang disediakan di rilis OpenSID:

[FormatImportDDK.xls.zip](https://github.com/OpenSID/OpenSID/files/1815120/FormatImportDDK.xls.zip)

**Comment by MUHAMMADRANGSEL** [comment]
format impor DDK yang sudah diisi ini dia mas eddie
[Format Import DDK.zip](https://github.com/OpenSID/OpenSID/files/1815793/Format.Import.DDK.zip)

**Comment by eddieridwan** [comment]
Bung @MUHAMMADRANGSEL : format impor yang diisi dari anda itu kebanyakan barisnya sama -- jadi tidak menunjukkan analisis yang realistis. Apakah bisa diisi data DDK dari desa yang sebenarnya? Juga inginnya data realistis itu diisikan ke daftar keluarga yang ada di contoh data awal rilis OpenSID (terlampir di atas), supaya bisa dimasukkan ke rilis. Mungkin bung Arcom bisa bantu anda mengisi?

Kalau kita lakukan ini, contoh data awal akan siap dipakai untuk pelatihan integrasi Prodeskel dengan OpenSID.

**Comment by MUHAMMADRANGSEL** [comment]
Itu kan hanya contoh mas eddie

Pada tanggal 16 Mar 2018 8.02 AM, "Eddie Ridwan" <notifications@github.com>
menulis:

**Comment by eddieridwan** [comment]
Betul, tapi kami ingin gabungkan sekalian ke contoh data awal yang disediakan sebagai bagian dari rilis.

**Comment by eddieridwan** [comment]
Analisis DDK Profil Desa sudah ditambahkan sebagai analisis sistem yang tidak bisa dihapus atau diubah.

Sdh dicommit ke master.
