### ISSUE TITLE
Bug/error: TOMBOL DOWLOAD DIGANTI DENGAN TOMBOL VIEW

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#8480]
### Jelaskan error yg dialami

SAAT INI DI LAYANAN MANDIRI ADA TOMBOL DOWNLOADS SEBAIKNYA TOMBOL DOWNLOAD DIGANTI DENGAN VIEW SPY TIDAK TERDAPAT BANYAK UNDUHAN DOKUMEN MELALUI LAYANAN MANDIRI

### Cara untuk mereplikasi errornya

SAAT INI DI LAYANAN MANDIRI ADA TOMBOL DOWNLOADS SEBAIKNYA TOMBOL DOWNLOAD DIGANTI DENGAN VIEW SPY TIDAK TERDAPAT BANYAK UNDUHAN DOKUMEN MELALUI LAYANAN MANDIRI

### Hasil yg diharapkan

TOMBOL DOWNLOAD DIGANTI DENGAN TOMBOL VIEW

### Tangkapan layar dan log error

SAAT INI DI LAYANAN MANDIRI ADA TOMBOL DOWNLOADS SEBAIKNYA TOMBOL DOWNLOAD DIGANTI DENGAN VIEW SPY TIDAK TERDAPAT BANYAK UNDUHAN DOKUMEN MELALUI LAYANAN MANDIRI

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

24.09.0.1

**Comment by agungsugiarto** [comment]
di menu apa saja pak @MUHAMMADRANGSEL

**Comment by agungsugiarto** [comment]
mas @andifahruddinakas, bisa minta tolong tombol die menu mana saja yang harus diubah?

**Comment by MUHAMMADRANGSEL** [comment]
Di menu layanan mandiri/dokumen

Pada tanggal Jum, 20 Sep 2024 15.13, Agung Sugiarto <
***@***.***> menulis:

**Comment by andifahruddinakas** [comment]
mas @agungsugiarto, ubah dibagian modul dokumen layanan mandiri, dari unduh dokumen jadi lihat dokumen.
