### ISSUE TITLE
Bug/error: AKSES MENU BANTUAN DILAYANAN MANDIRI TERJADI ERROR

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#8481]
### Jelaskan error yg dialami

AKSES MENU BANTUAN DILAYANAN MANDIRI TERJADI ERROR

### Cara untuk mereplikasi errornya

AKSES MENU BANTUAN DILAYANAN MANDIRI TERJADI ERROR

### Hasil yg diharapkan

BISA MENGAKSES MENU BANTUAN DILAYANAN MANDIRI

### Tangkapan layar dan log error

AKSES MENU BANTUAN DILAYANAN MANDIRI TERJADI ERROR

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

24.09.0.1

**Comment by andifahruddinakas** [comment]
pak @MUHAMMADRANGSEL, bisa disertakan log dan tangkapan layar yang error agar muda dipahami. Sy ciba akses :
![image](https://github.com/user-attachments/assets/e27fcd83-93ac-487a-b0ac-9a15c32dd5b1)

**Comment by andifahruddinakas** [comment]
pak @MUHAMMADRANGSEL, jika masih bermasalah silahkan di buka kembali dengan menyertakan tangkapan layar dan log errornya.
