### ISSUE TITLE
Bug/error: PENGATURAN SEBUTAN DUSUN TIDAK TAMPIL

### ISSUE THREAD

**Issue by pujocahyono** [OpenSID/OpenSID#8482]
### Jelaskan error yg dialami

PENGATURAN SEBUTAN DUSUN PADA MENU WILAYAH ADMINISTRATIF TIDAK TAMPIL SAAT DI KLIK

### Cara untuk mereplikasi errornya

1. MENU WILAYAH ADMINISTRATIF
2. KLIK PENGATURAN

### Hasil yg diharapkan

NORMAL

### Tangkapan layar dan log error

![Cuplikan layar 2024-09-19 065426](https://github.com/user-attachments/assets/6cf0e620-d2c0-4dfb-bccb-e1557ee93542)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2409.0.2-premium

**Comment by andifahruddinakas** [comment]
Selesai melalui commit https://github.com/OpenSID/premium/commit/450f5b431b3f84a334f1a21b40954599199b7fa8

**Comment by ariandii** [comment]
![image](https://github.com/user-attachments/assets/6681e4db-f80d-4431-8daa-e60b2fb46e21)

bisa sekaliguis sebutan kepala dusun juga ada di lokasi yang sama tersebut

saat ini sebutan dusun dan kepala dusun masih terpisah di menu Pengaturan - Aplikasi

**Comment by andifahruddinakas** [comment]
> ![image](https://github.com/user-attachments/assets/6681e4db-f80d-4431-8daa-e60b2fb46e21)
> 
> bisa sekaliguis sebutan kepala dusun juga ada di lokasi yang sama tersebut
> 
> saat ini sebutan dusun dan kepala dusun masih terpisah di menu Pengaturan - Aplikasi

Ok
