### ISSUE TITLE
Bug/error: widget agenda error di klik error

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8483]
### Jelaskan error yg dialami

 widget agenda ketika di klik url mengarah kesini https://berputar.opendesa.id/web/tab/1000 dan tampilan error

### Cara untuk mereplikasi errornya

1. admin web
2. widget
3. klik widget agenda

### Hasil yg diharapkan

widget agenda ketika di klik tidak error

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/d9a7d837-dac6-483b-922a-215b74a4b90d)
![image](https://github.com/user-attachments/assets/3ca6e2d8-e95d-4b1c-b7bb-cccc972b7de7)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

OpenSID 2409.0.2-premium

**Comment by andifahruddinakas** [comment]
Selesai melalui commit https://github.com/OpenSID/premium/commit/09866e9a2f3a9a7cc8fb469bcc63aed9f3a99845
