### ISSUE TITLE
Prodeskel: buat analisis master anggota keluarga

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#849]
Kita mulai menggabungkan data prodeskel ke menu Analisis. Untuk itu kita perlu bakukan analisis masternya. Issue ini untuk analisis master pengumpulan data anggota keluarga.

Issue terkait:

* #848 
* #850

**Comment by MUHAMMADRANGSEL** [comment]
Contoh Analisis Anggota Keluarga dan Contoh Format Impor
[Analisis Anggota Keluarga dan COntoh Format Impor.zip](https://github.com/OpenSID/OpenSID/files/1816361/Analisis.Anggota.Keluarga.dan.COntoh.Format.Impor.zip)

**Comment by eddieridwan** [comment]
Terima kasih, bung @MUHAMMADRANGSEL. Apakah contoh format impor bisa dibuatkan supaya:

1. menggunakan penduduk yang ada di contoh data awal di rilis OpenSID
2. berisi data yg realistis

Dengan demikian, contoh data awal bisa siap digunakan untuk pelatihan mengintegrasikan data Prodeskel dengan OpenSID.

**Comment by MUHAMMADRANGSEL** [comment]
Yg sekarang Krn banyak kode yg berbeda, shgg belum bisa sepenuhnya kita
pakai data awal dari Opensid

Pada tanggal 16 Mar 2018 8.18 AM, "Eddie Ridwan" <notifications@github.com>
menulis:

**Comment by eddieridwan** [comment]
Maksudnya, contoh menggunakan penduduk (NIK, nama) yang ada di data awal. Supaya nyambung. Data isiannya sendiri, ya apa saja, asal realistis. Contoh yang anda berikan penduduknya tidak ada, jadi tidak bisa diimpor.

**Comment by eddieridwan** [comment]
Analisis DAK Profil Desa sudah ditambahkan sebagai analisis sistem yang tidak bisa dihapus atau diubah.

Sdh dicommit ke master.
