### ISSUE TITLE
Bug/error: MIgrasi Premium to Umum Eror

### ISSUE THREAD

**Issue by arinal95** [OpenSID/OpenSID#8496]
### Jelaskan error yg dialami

Saya melakukan migrasi, dari versi premium ke versi umum. Namun pada tampilan beranda eror 500, namun pada halaman admin bisa diakases dengan lancar.

### Cara untuk mereplikasi errornya

akses ke website utama.

### Hasil yg diharapkan

Halaman utama bisa diakses dengan lancar.

### Tangkapan layar dan log error

![Screenshot 2024-09-24 at 06-07-57 Database Error](https://github.com/user-attachments/assets/856ad362-fdee-4fb5-842a-344f99c4034e)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v2406

### Tema Yang Digunakan

Silir

**Comment by andifahruddinakas** [comment]
pak @arinal95, untuk error bisa disertakan log errornya.

**Comment by pandigresik** [comment]
Bisa dicoba https://t.me/komunitasopensidstop/43510

**Comment by arinal95** [comment]
> pak @arinal95, untuk error bisa disertakan log errornya.

[log-2024-09-24.txt](https://github.com/user-attachments/files/17106299/log-2024-09-24.txt)

**Comment by eddieridwan** [comment]
@arinal95 migrasi dari Premium versi berapa? Dan dimigrasi ke versi Umum berapa? Ingat, versi Umum adalah versi Premium enam bulan sebelumnya. Perlu dilihat kesetaraan versinya. Tidak dapat migrasi ke versi sebelumnya. Kesetaraan versi Premium dan Umum ada di https://panduan.opendesa.id/id/opensid/rilis-umum-yang-akan-datang. 

**Misalnya, tidak valid untuk migrasi dari Premium 2403 ke Umum 2408 (karena setara dengan Premium 2401, yaitu mundur).**

@andifahruddinakas @vickyrolanda pastikan migrasi tidak dimungkinkan kalau mundur versi berdasarkan kesetaraan versi tersebut.

**Comment by arinal95** [comment]
Dari versi 2401.0.2-premium , saya langsung migrasi ke 2407. Yang saya tidak paham, mundur 6 bulan itu dari versi rilis terbaru premium saat ini ? atau dari yang saya install (SID yg saya pakai saat ini) ?

Atau bisakah anda membantu menyarankan, jika versi 2401.0.2-premium (yg saya pakai saat ini), maka untuk migrasi saya saya harus pakai SID yg versi berapa ?

**Comment by arinal95** [comment]
> Bisa dicoba https://t.me/komunitasopensidstop/43510

Ini sudah saya coba, tetap tidak berhasil. halaman beranda tetap tidak bisa di akses. link website untuk case ini di https://kt.desamu.id . Sedangkan halaman /siteman itu bisa diakases

**Comment by eddieridwan** [comment]
@arinal95 apakah sudah lihat daftar kesetaraan versi Premium dan Umum di https://panduan.opendesa.id/id/opensid/rilis-umum-yang-akan-datang

Terlihat di situ Premium 2401 setara dengan Umum 2408. Tentunya tidak dapat migrasi ke Umum 2407, karena akan mundur.  Yaitu Premium 2401 persis sama dengan Umum 2408. Jadi kalau mau update, hanya bisa update ke Umum 2409. 

@andifahruddinakas @vickyrolanda buat issue untuk memastikan migrasi mundur seperti ini tidak dapat dilakukan.

<img width="682" alt="image" src="https://github.com/user-attachments/assets/2e115fda-a758-4a4d-bbb1-4eeb31fcaec5">

**Comment by arinal95** [comment]
Saua sudah coba lakukan migrasi ke versi  v2408 namun diminta untuk migrasi minimal ke versi : v2407. Intinya ke dua versi tersebut sudah saya coba, namuntetap eror 500. Berikut log eror yg muncul :
[log-2024-09-24(4).txt](https://github.com/user-attachments/files/17106929/log-2024-09-24.4.txt)

**Comment by arinal95** [comment]
> @arinal95 migrasi dari Premium versi berapa? Dan dimigrasi ke versi Umum berapa? Ingat, versi Umum adalah versi Premium enam bulan sebelumnya. Perlu dilihat kesetaraan versinya. Tidak dapat migrasi ke versi sebelumnya. Kesetaraan versi Premium dan Umum ada di https://panduan.opendesa.id/id/opensid/rilis-umum-yang-akan-datang.
> 
> **Misalnya, tidak valid untuk migrasi dari Premium 2403 ke Umum 2408 (karena setara dengan Premium 2401, yaitu mundur).**
> 
> @andifahruddinakas @vickyrolanda pastikan migrasi tidak dimungkinkan kalau mundur versi berdasarkan kesetaraan versi tersebut.

Saya sudah coba mundur 6 bulan dari versi yg saya pakai, tetap saya ero
[log-2024-09-24(4).txt](https://github.com/user-attachments/files/17106764/log-2024-09-24.4.txt)

**Comment by eddieridwan** [comment]
Bawa ke Klinik Bug untuk direplikasi bersama bung @rgrahardi .  Lihat info Klinik Bug di https://t.me/c/1238304761/54950/69401 atau hubungi bung Ridho di https://t.me/rgandarahardi

**Comment by eddieridwan** [comment]
Atau bung @andifahruddinakas atau @pandigresik ada solusi terkait masalah di error log itu (migrasi gagal karena ada field yg ambiguous).

**Comment by pandigresik** [comment]
> Atau bung @andifahruddinakas atau @pandigresik ada solusi terkait masalah di error log itu (migrasi gagal karena ada field yg ambiguous). 

pesan error field ambiguous itu bukan ketika migrasi, namun ketika buka halaman website
migrasi ulang, tapi sebelumnya pastikan halaman /periksa sudah bersih

**Comment by andifahruddinakas** [comment]
Sudah dibuatkan issue untuk menangani update ke versi baru ke versi lama, https://github.com/OpenSID/OpenSID/issues/8507
