### ISSUE TITLE
Bug/error: data penduduk yang sudah digunakan untuk pembuatan surat dan bantuan tidak dapat dihapus 

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8498]
### Jelaskan error yg dialami

data penduduk yang sudah digunakan contohnya untuk pembuatan surat dan daftar peserta bantuan, data penduduk tersebut tidak bisa lagi dihapus.

### Cara untuk mereplikasi errornya

1. penduduk
2. hapus penduduk

### Hasil yg diharapkan

1. penduduk 
2. hapus penduduk
3. pemberitahuan data penduduk tidak bisa dihapus karena sudah digunakan untuk pembuatan surat dan peserta bantuan

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/94d5c1f3-08bf-4393-a7f2-aadb4132fe50)
![image](https://github.com/user-attachments/assets/0b0c4e4c-a9aa-48ad-a7de-8323244dcf4b)
![image](https://github.com/user-attachments/assets/e20122d2-493a-4b67-98b7-27596518c53f)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Versi 2409.0.2-premium

**Comment by agungsugiarto** [comment]
mas @rgrahardi kenapa tidak boleh dihapus jika sudah digunakan untuk pembuatan surat dan bantuan? Saat ini jika penduduk tersebut dihapus maka akan otomatis terhapus juga pada peserta bantuan.

**Comment by eddieridwan** [comment]
@agungsugiarto seharusnya bantuan dan surat tercetak tidak boleh dihapus melalui penghapusan penduduk. Karena merupakan arsip desa dan riwayat bantuan. Harus hapus bantuan dan surat secara eksplisit dulu, tidak melalui penduduk. Sebenarnya penduduk tersebut tidak boleh dihapus kalau sudah ada kegiatan seperti itu. Karena merupakan penduduk sebetulnya. Hanya boleh dimutasikan (pindah, meninggal, hilang), tidak dihapus. 

Penduduk yg boleh dihapus hanya yg bersifat salah buat.
