### ISSUE TITLE
Surat Layanan Bawaan 

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#8499]
Untuk surat bawaan perlu disesuaikan sebagai berikut : 

- [ ] Untuk surat bawaan menampilkan tombol lihat bukan tombol ubah, dengan form yang hanya bisa dilihat saja isinya (tidak ada proses tambah/ubah)
- [ ] Sediakan tombol salin pada setiap surat, sama halnya dengan modul grup pengguna. (sudah ada)

**Comment by agungsugiarto** [comment]
mas @andifahruddinakas masih kurang jelas informasi bagian ini

> - [ ] Sediakan tombol salin pada setiap surat, sama halnya dengan modul grup pengguna. (sudah ada)

Saat ini sudah ada tombol salin di setiap surat, apa yang perlu disalin lagi?

**Comment by andifahruddinakas** [comment]
> mas @andifahruddinakas masih kurang jelas informasi bagian ini
> 
> > - [ ] Sediakan tombol salin pada setiap surat, sama halnya dengan modul grup pengguna. (sudah ada)
> 
> Saat ini sudah ada tombol salin di setiap surat, apa yang perlu disalin lagi?
> 

Yg point 1 mas, yg point 2 tinggal sesuaikan sj krn sdh sy kasih keterangan sudah ada.
