### ISSUE TITLE
Pratinjau Lampiran Surat

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#8500]
Pada modul pengaturan surat, masing-masing surat disediakan tombol untuk pratinjau surat yang dibuat dengan data yang digunakan data acak. Namun pada kasus lain terdapat surat yang memiliki lampiran, dan pratinjau saat ini belum mengikutkan laporan tersebut.

Solusi : 
- [ ]  ikutkan pratinjau pada saat tinjau surat dengan lampiran yang dipilih
- [ ] pada data pratijau diambil atau disesuaikan berdasarkan pengaturan form yang dibutuhkan. Contoh: untuk lampiran surat nikah dengan beberapa inputan penduduk, maka data acak yang digunakan sebanyak pengaturan dari formnya.
![image](https://github.com/user-attachments/assets/a943a318-1b27-4c09-a892-d053e3e4d39a)

![image](https://github.com/user-attachments/assets/382be8f1-8093-43d9-bcf5-0c17e4390713)

**Comment by agungsugiarto** [comment]
mas @andifahruddinakas prantinjau saat ini di disable untuk surat bawaan, apakah harus diaktifkan terkait pr ini https://github.com/OpenSID/premium/pull/4121 ?

**Comment by andifahruddinakas** [comment]
> mas @andifahruddinakas prantinjau saat ini di disable untuk surat bawaan, apakah harus diaktifkan terkait pr ini [OpenSID/premium#4121](https://github.com/OpenSID/premium/pull/4121) ?

Untuk pratinjaunya dibuat aktif.

**Comment by agungsugiarto** [comment]
> > mas [@andifahruddinakas](https://github.com/andifahruddinakas) prantinjau saat ini di disable untuk surat bawaan, apakah harus diaktifkan terkait pr ini [OpenSID/premium#4121](https://github.com/OpenSID/premium/pull/4121) ?
> 
> Untuk pratinjaunya dibuat aktif.

sudah saya buatkan pr susulan mas @andifahruddinakas  https://github.com/OpenSID/premium/pull/4125
