### ISSUE TITLE
Bug/error: Bolehkan pengisian pada jabatan Plt Plh Kepala Desa berisi karakter alfanumerik, spasi, slash dan strip 

### ISSUE THREAD

**Issue by mah-mudi** [OpenSID/OpenSID#8501]
### Jelaskan error yg dialami

Belum diperbolehkan pengisian pada jabatan Plt Plh Kepala Desa berisi karakter alfanumerik, spasi, slash dan strip 

### Cara untuk mereplikasi errornya

1. buku aparat pemerintahan desa
2. jabatan

### Hasil yg diharapkan

Bolehkan pengisian pada jabatan Plt Plh Kepala Desa berisi karakter alfanumerik, spasi, slash dan strip 
karena menyesuaiakan tata nashkah dinas
![image](https://github.com/user-attachments/assets/ee900aea-783f-4b15-817f-c5dcceb716ad)

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/e32828eb-2214-4c62-bf0b-a87bfd6bef35)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

24.09.0-2 premium

### Tema Yang Digunakan

silir

### Informasi tambahan

-

**Comment by andifahruddinakas** [comment]
Cara ini tdk relevan, krn sdh disediakan fitur terkait plt ini. Mas @rgrahardi bisa dibuatkan panduan terkait jabatan plt ini.

**Comment by rgrahardi** [comment]
berikut panduannya https://panduan.opendesa.id/id/opensid/halaman-administrasi/layanan-surat/pengaturan#tanda-tangan-pj-kepala-desa

cc pak @andifahruddinakas pak @mah-mudi
