### ISSUE TITLE
Bug/error: menu yang terkunci tetap muncul diberanda

### ISSUE THREAD

**Issue by typevant** [OpenSID/OpenSID#8506]
### Jelaskan error yg dialami

Menu disembunyikan tetap muncul di halaman dashbor website

### Cara untuk mereplikasi errornya

1. Buat menu baru
2. Sembunyikan menu (gembok)
3. Refresh halaman website

### Hasil yg diharapkan

Menu yang disembunyikan agar tidak muncul di depan

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/91a6160c-05fb-4619-96ee-7e8cf8e5c121)
![image](https://github.com/user-attachments/assets/309d0823-cbcd-4118-ae4e-45d1b14e1b90)

### Rilis Versi OpenSID

Rilis Umum

### Versi OpenSID

v.2409.0.0

### Tema Yang Digunakan

DeNava

**Comment by andifahruddinakas** [comment]
Duplicate of https://github.com/OpenSID/OpenSID/issues/7690
