### ISSUE TITLE
Bug: Error menu kosongkan db saat fresh install v2.10

### ISSUE THREAD

**Issue by hirudi** [OpenSID/OpenSID#851]
Sy coba fresh install V2.10, ada error waktu klik kosongkan db... di demo sy coba juga terjadi error... terimakasih

Error Number: 1701

Cannot truncate a table referenced in a foreign key constraint (`administrasi`.`mutasi_inventaris`, CONSTRAINT `mutasi_inventaris_ibfk_1` FOREIGN KEY (`id_barang`) REFERENCES `administrasi`.`inventaris` (`id`))

TRUNCATE inventaris

Filename: /home/ . . . . . . /public_html/models/database_model.php

Line Number: 1880

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
