### ISSUE TITLE
Bug/error: pilihan penduduk calon pengantin wanita tidak ada

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8510]
### Jelaskan error yg dialami

pilihan penduduk calon pengantin wanita tidak ada pada surat nikah non muslim 

### Cara untuk mereplikasi errornya

1. Cetak Surat
2. Pilih surat Keterangan Untuk Nikah Warga Non Muslim
3. Isi Data Pengantin wanita

### Hasil yg diharapkan

terdapat pengisian penduduk pengantin wanita

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/cebbb196-67e4-4bc8-b933-9083cb073003)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Versi 2409.0.2-premium

**Comment by andifahruddinakas** [comment]
mas @rgrahardi, perhatikan pada bagian form suratnya. apakah lengkap seperti ini?
![image](https://github.com/user-attachments/assets/c3bdc210-6728-4ab9-802d-af9802a4f510)

sehingga saat ditampilkan 
![image](https://github.com/user-attachments/assets/f83b9077-873d-4ad4-bb4e-b0a4aedbe151)

untuk versi lama bisa menggunakan cara **mengembalikan surat bawaan/sistem**.
![image](https://github.com/user-attachments/assets/3233a9a5-7aa8-417b-bd4b-e570a175ca24)

sedangkan untuk selanjutnya untuk surat versi bawaan akan otomatis ikut terperbarui.
