### ISSUE TITLE
Bug/error: tambah lampiran F-2.01 pada Keterangan Untuk Nikah Warga Non Muslim gagal

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8511]
### Jelaskan error yg dialami

tambah lampiran F-2.01 pada Keterangan Untuk Nikah Warga Non Muslim gagal, surat tidak bisa disimpan

### Cara untuk mereplikasi errornya

1. Pengaturan Surat
2. Pilih surat Keterangan Untuk Nikah Warga Non Muslim gagal
3. tambahkan lampiran F-2.01
4. simpan

### Hasil yg diharapkan

bisa simpan 

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/a1b03d58-8852-438e-a2e3-5cda3d4a7d0f)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

 OpenSID 2409.0.2-premium

**Comment by andifahruddinakas** [comment]
mas @rgrahardi, sy coba bisa
![image](https://github.com/user-attachments/assets/141f4aaf-218e-47fc-9758-a749b149bbd0)

Informasi tambahan: untuk rilis selanjutnya untuk surat bawaan tidak bisa diubah lg. adapun jika ingin memodifikasi surat bawaan bisa dengan melakukan cloning pada surat tsb.
