### ISSUE TITLE
Bug/error: Tambah Rumah tangga terdapat data tidak dikenali masuk ke rumah tangga

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8513]
### Jelaskan error yg dialami

saat tambah rumah tangga terdapat pilihan penduduk sebagai kepala rumah tangga saat rumah tangga berhasil disimpan terdapat kepala penduduk dari desa lain, saat di cek penduduk tersebut tidak ada di database penduduk desa, ini terjadi di Desa Gunung Salak database gabungan Kab. Tabanan

### Cara untuk mereplikasi errornya

1. Kependuduk
2. Rumah Tangga
3. tambah rumah tangga

### Hasil yg diharapkan

data rumah tangga benar sesuai penduduk desa 

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/af83d9b2-1065-45a7-a047-264d03602e9c)

![image](https://github.com/user-attachments/assets/aca1b7fd-43f0-4d57-8a61-2dc20ac6d2e5)

![image](https://github.com/user-attachments/assets/334712a9-3a47-47fa-9fee-ebd7d85c9baa)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2409.0.2-premium

**Comment by agungsugiarto** [comment]
mas @rgrahardi informasi replikasi kurang spesifik pada poin 3.
Tambah rumah tangga yang dimaksud yang mana?

![Image](https://github.com/user-attachments/assets/0e54ded4-80f8-4c7a-b0f4-e58b421105fc)
![Image](https://github.com/user-attachments/assets/1425b309-0e9c-49fe-aebf-26ae49c86886)

**Comment by rgrahardi** [comment]
Tambah Yang ini mas
![image](https://github.com/user-attachments/assets/36c36760-7c2b-455e-beaa-9f4cf4ae9777)


Tambah Rumah tanggal ada inputan kepala rumah tanggan setelah berhasil di simpan lihat rincian data rumah tangga ada data dari desa lain masuk mas dan status kepala rumah tangga
