### ISSUE TITLE
Bug/error: data suplemen warga terdata kosong

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8514]
### Jelaskan error yg dialami

data suplemen warga terdata kosong terjadi di database gabungan Kab. Tabanan

### Cara untuk mereplikasi errornya

1. kependuduk
2. suplemen
3. warga terdata

### Hasil yg diharapkan

data sesuai

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/4da101da-34ae-48b8-90cc-5a1ac8d94b20)
![image](https://github.com/user-attachments/assets/496d7ef4-50b5-4d2b-bac0-40070f4f1397)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2409.0.2-premium

**Comment by andifahruddinakas** [comment]
Ini terkait struktur tabel suplemen terdata yang tidak berelasi, sehingga ketika melakukan export dan impor pada database gabungan akan menyebabkan kolom yg merujuk pada penduduk dan keluarga (sasaran) tidak diperbarui (memakai id penduduk/keluarga yang lama). 

Namun untuk versi terbaru untuk sasaran sudah dibuatkan kolom masing2 dan berelasi pada tabel sesuai sasarannya.

Solusi yang perlu dicari yakni, cara menentukan atau mencari id berdasarkan sasaran tsb berdasarkan id peserta yg sudah terdaftar yg menggunakan id lama (bukan dari hasil restore)

Contohnya, id_terdata masih ratusan, sedangkan data id pada penduduk sudah ribuan.
![image](https://github.com/user-attachments/assets/d6026702-cd15-4b70-920a-e31fbbd57dcd)

![image](https://github.com/user-attachments/assets/417f8aa7-e6a6-42cf-b71e-e52d552ab4ca)

database terlampir pada folder database gabungan, untuk kab. paser

**Comment by pandigresik** [comment]
sepertinya harus di mapping manual

**Comment by andifahruddinakas** [comment]
> sepertinya harus di mapping manual

Iya, bisa ditambahkan ke halaman periksa. Karena untuk otomatis sepertinya tidak bisa, karena tidak ada paramter lain yang bisa digunakan (hanya id_penduduk/kelaurga saja sesuai sasaran).

**Comment by pandigresik** [comment]
mungkin lebih cepat hapus data suplemen kemudian import ulang menggunakan data excel

**Comment by andifahruddinakas** [comment]
> mungkin lebih cepat hapus data suplemen kemudian import ulang menggunakan data excel

iya, alternatif lain seperti itu, buat file untuk diimport dari database yg belum digabungkan.

**Comment by andifahruddinakas** [comment]
> > mungkin lebih cepat hapus data suplemen kemudian import ulang menggunakan data excel
> 
> iya, alternatif lain seperti itu, buat file untuk diimport dari database yg belum digabungkan.

mas @rgrahardi, sudah dibuatkan halaman periksa untuk memperbaiki data yang tidak tampil. namun bisa juga dilakukan hapus dan impor ulang data suplemen tsb.
