### ISSUE TITLE
Bug/error: Penulisan Alamat Lengkap

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#8516]
### Jelaskan error yg dialami

saat membuat surat untuk alamat menggunakan alamat lengkap saat tinjau pdf maka penulisan alamatnya perlu ada perbaikan
![image](https://github.com/user-attachments/assets/1b172307-e8ca-452b-93c7-cd53013627e4)
saat tinjau
![image](https://github.com/user-attachments/assets/1328108b-468b-4db4-8ed0-9c50facf7183)

### Cara untuk mereplikasi errornya

saat membuat surat untuk alamat menggunakan alamat lengkap saat tinjau pdf maka penulisan alamatnya perlu ada perbaikan
![image](https://github.com/user-attachments/assets/1b172307-e8ca-452b-93c7-cd53013627e4)
saat tinjau
![image](https://github.com/user-attachments/assets/1328108b-468b-4db4-8ed0-9c50facf7183)

Alamat / Tempat Tinggal : Dasan Bunut **Rt** 005 / **Rw** - Dusun Seganteng**,** Desa Rarang
Selatan**,** Kecamatan Terara**,** Kabupaten Lombok Timur, Provinsi Nusa Tenggara Barat

Penulisan RT dan RW serta hilangkan tanda koma

### Hasil yg diharapkan

untuk penulisan diharapkan seperti dibawah ini : 
Alamat / Tempat Tinggal : Dasan Bunut RT 005 / RW - Dusun Seganteng Desa Rarang Selatan Kecamatan Terara Kabupaten Lombok Timur Provinsi Nusa Tenggara Barat

### Tangkapan layar dan log error

saat membuat surat untuk alamat menggunakan alamat lengkap saat tinjau pdf maka penulisan alamatnya perlu ada perbaikan
![image](https://github.com/user-attachments/assets/1b172307-e8ca-452b-93c7-cd53013627e4)
saat tinjau
![image](https://github.com/user-attachments/assets/1328108b-468b-4db4-8ed0-9c50facf7183)

Alamat / Tempat Tinggal : Dasan Bunut **Rt** 005 / **Rw** - Dusun Seganteng**,** Desa Rarang
Selatan**,** Kecamatan Terara**,** Kabupaten Lombok Timur, Provinsi Nusa Tenggara Barat

Penulisan RT dan RW serta hilangkan tanda koma

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

24.09.0.1 premium

### Tema Yang Digunakan

DeNava

**Comment by agungsugiarto** [comment]
Pak @MUHAMMADRANGSEL bukankah seperti ini seharusnya penulisan yang benar?

Dasan Bunut RT 005 / RW - Dusun Seganteng, Desa Rarang Selatan, Kecamatan Terara, Kabupaten Lombok Timur, Provinsi Nusa Tenggara Barat

mas @andifahruddinakas bisa bantu cari referensi yang sesuai

**Comment by andifahruddinakas** [comment]
> Pak @MUHAMMADRANGSEL bukankah seperti ini seharusnya penulisan yang benar?
> 
> Dasan Bunut RT 005 / RW - Dusun Seganteng, Desa Rarang Selatan, Kecamatan Terara, Kabupaten Lombok Timur, Provinsi Nusa Tenggara Barat
> 
> mas @andifahruddinakas bisa bantu cari referensi yang sesuai

Perbaiki pada bagian rt dan rw sj yang harusnya huruf besar, untuk penggunaan koma pada masing2 tingkatan wilayah sesuai kebutuhan masing2 desa sj. Dimana bisa membuat kode isian sendiri, pada kode isian alias.
![image](https://github.com/user-attachments/assets/48418931-d185-44d6-802e-5d6059bd6ddf)
