### ISSUE TITLE
Bug/error: Pembuatan surat saat ini kesulitan diukuran kertas F4

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#8517]
### Jelaskan error yg dialami

saat ini ketika membuat surat yang redaksi suratnya agak panjang kesulitan untuk mengatur menjadi F4, walaupun sudah menggunakan F4 masih terasa menggunakan A4
misalkan surat yang akan kita buat kalau di buat di word ukuran F4 dengan ukuran font 12 masih nampung dan rapi tetapi ketika kita buat di tiny mCE masih sulit untuk diatur supaya jadi 1 lembar

### Cara untuk mereplikasi errornya

saat ini ketika membuat surat yang redaksi suratnya agak panjang kesulitan untuk mengatur menjadi F4, walaupun sudah menggunakan F4 masih terasa menggunakan A4
misalkan surat yang akan kita buat kalau di buat di word ukuran F4 dengan ukuran font 12 masih nampung dan rapi tetapi ketika kita buat di tiny mCE masih sulit untuk diatur supaya jadi 1 lembar

### Hasil yg diharapkan

untuk surat yang redaksinya agak panjang bisa dengan mudah diatur agar muat di F4 dan menjadi satu lembar

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/69661927-b71d-49c4-bcfa-07cc323c0ccb)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

24.09.0.1

**Comment by MUHAMMADRANGSEL** [comment]
mungkin perlu dicek untuk ukuran F4 nya

**Comment by luxmant354** [comment]
termasuk untuk ukuran font kalau bisa default menggunakan 12 pt BUKAN 16px

**Comment by pandigresik** [comment]
mengikuti ukuran disini ya https://id.wikipedia.org/wiki/Ukuran_kertas, untuk F4 indonesia 215 mm x 330 mm

![image](https://github.com/user-attachments/assets/57608b77-3f6a-47cc-b3c4-8aa95132b234)

**Comment by luxmant354** [comment]
> mengikuti ukuran disini ya https://id.wikipedia.org/wiki/Ukuran_kertas, untuk F4 indonesia 215 mm x 330 mm
> 
> ![image](https://private-user-images.githubusercontent.com/1853475/372688104-57608b77-3f6a-47cc-b3c4-8aa95132b234.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4NjE3MDksIm5iZiI6MTcyNzg2MTQwOSwicGF0aCI6Ii8xODUzNDc1LzM3MjY4ODEwNC01NzYwOGI3Ny0zZjZhLTQ3Y2MtYjNjNC04YWE5NTEzMmIyMzQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMDJUMDkzMDA5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjcyMmNkYmYwMDJmZDE4MzE4ZThkM2U3MjE1OTg3MGU4NWFkMWUyZWQzOGUwZDkyOTQ5YzM3NzlmOGNkMGZlMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.9P-dQl4lIQZ1p2dAPdVNuWkuW_oeTSyThzN1_X5-VgA)

secara informasi di web seprti itu Pak @pandigresik tapi kalau di praktekan di TinyMCE antara pt dan px beda, kalau 16px lebih kecil dari 12pt

contoh : yang font warna hitam 16px dan yang merah 12pt
![Screenshot_1](https://github.com/user-attachments/assets/ab9bdb34-b425-4ca1-a2ee-a4537d6f084b)

**Comment by MUHAMMADRANGSEL** [comment]
Mungkin lebih baik seragamkan pakai pt

Pada tanggal Rab, 2 Okt 2024 17.33, luxmant354 ***@***.***>
menulis:

**Comment by pandigresik** [comment]
kita bahas ukuran kertas dulu agar sama persepsinya

**Comment by pandigresik** [comment]
> > mengikuti ukuran disini ya https://id.wikipedia.org/wiki/Ukuran_kertas, untuk F4 indonesia 215 mm x 330 mm
> > 
> > ![image](https://private-user-images.githubusercontent.com/1853475/372688104-57608b77-3f6a-47cc-b3c4-8aa95132b234.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4NjE3MDksIm5iZiI6MTcyNzg2MTQwOSwicGF0aCI6Ii8xODUzNDc1LzM3MjY4ODEwNC01NzYwOGI3Ny0zZjZhLTQ3Y2MtYjNjNC04YWE5NTEzMmIyMzQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMDJUMDkzMDA5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjcyMmNkYmYwMDJmZDE4MzE4ZThkM2U3MjE1OTg3MGU4NWFkMWUyZWQzOGUwZDkyOTQ5YzM3NzlmOGNkMGZlMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.9P-dQl4lIQZ1p2dAPdVNuWkuW_oeTSyThzN1_X5-VgA)
> 
> secara informasi di web seprti itu Pak @pandigresik tapi kalau di praktekan di TinyMCE antara pt dan px beda, kalau 16px lebih kecil dari 12pt
> 
> contoh : yang font warna hitam 16px dan yang merah 12pt
> ![Screenshot_1](https://github.com/user-attachments/assets/ab9bdb34-b425-4ca1-a2ee-a4537d6f084b)
> 

Sepertinya ketika font tidak diset ukurannya maka akan menggunakan ukuran font default, kalau tidak salah default 10 pt. Dan saat ini juga belum ada pengaturan untuk ukuran font secara default

**Comment by andifahruddinakas** [comment]
Sudah disesuaikan melalui PR https://github.com/OpenSID/premium/pull/4141 terkait ukuran kertas F4 sesuai ukuran indonesia. Untuk ukuran font dll, bisa dibuat dan didiskusikan diissue lainnya.
