### ISSUE TITLE
Bug/error: gagal impor redirect ke halaman utama

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8520]
### Jelaskan error yg dialami

gagal impor redirect ke halaman utama, tanggal lahir sudah sesuai dengan contoh file impor

### Cara untuk mereplikasi errornya

1. klik penduduk
2. klik impor

### Hasil yg diharapkan

berhasil impor

### Tangkapan layar dan log error

file impor di bagi perbanjar untuk proses impornya ke 3 file impor gagal

1. Error File impor Banjar Munduk Temu Kelud
![image](https://github.com/user-attachments/assets/ca44b5fd-a6fe-447f-a361-fc569c22811c)

2. Error File impor Banjar Anggarsari Kelod

![image](https://github.com/user-attachments/assets/110f95e3-db57-4f62-8b36-79218f42917b)

3. Error File Banjar Kebonjero Kangin

![image](https://github.com/user-attachments/assets/fc698ab3-ae62-4466-b37f-c45a0d6fc814)

4. Error File Kebonjero Kauh

![image](https://github.com/user-attachments/assets/774cc208-dbe5-4b28-97bf-f4a35238fa4c)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

OpenSID 2409.0.2-premium

**Comment by andifahruddinakas** [comment]
Contoh file impor terlampir

**Comment by andifahruddinakas** [comment]
mas @rgrahardi, bisa ditambahkan dipanduan untuk data isian tanggal sebaiknya menggunakan format tanggal pada saat inputannya.
![image](https://github.com/user-attachments/assets/7c1185bd-7f09-472d-a461-15e4320c2cbe)

Bisa lihat contoh format impor yang disediakan.

Terkait notifikasi error tanggal sudah diperbaiki melalui commit https://github.com/OpenSID/premium/commit/7e5814a6960fde48e96dde651bd9c966db0a11d2
