### ISSUE TITLE
Bug/error: cetak surat pengantar nikah error

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8522]
### Jelaskan error yg dialami

cetak surat pengantar nikah error

### Cara untuk mereplikasi errornya

1. cetak surat 
2. pilih sruat pengantar nikah
3. cetak surat
4. klik tinjau pdf
5. klik cetak

### Hasil yg diharapkan

berhasil cetak surat pengantar nikah

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/bb348cb2-18ea-47d2-bc6a-a61a08be9c2a)

nomer suratnya tidak terbaca di surat tsb
![image](https://github.com/user-attachments/assets/29fa51a9-1028-4e6d-b162-294c46294431)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Versi 2409.0.2-premium

**Comment by andifahruddinakas** [comment]
![WhatsApp Image 2024-09-30 at 22 15 30_384eb383](https://github.com/user-attachments/assets/06885f44-8c5b-4e8e-a90c-b9ef0801ae24)

kode isian yang benar adalah **nomer_surat**

**Comment by andifahruddinakas** [comment]
Sudah disesuaikan melalui commit https://github.com/OpenSID/premium/commit/431c04b31dc01ba7eb652467160fca20b7074e26
