### ISSUE TITLE
Bug/error: kode isian tahun menampilkan hari dan bulan

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8523]
### Jelaskan error yg dialami

kode isian tahun menampilkan hari dan bulan, seharusnya hanya menampilkan tahun

### Cara untuk mereplikasi errornya

1. pengaturan surat
2. template surat
3. pilih kode isian tahun
4. tinjau

### Hasil yg diharapkan

kode isian tahun menampilkan tahun saja

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/16a08f18-5447-4958-9e31-9bf64302db81)

![image](https://github.com/user-attachments/assets/418c189b-33cd-4b70-b3a0-86282009d3de)

![image](https://github.com/user-attachments/assets/2726a1b0-1d75-4d7a-a7cd-1354fecf86db)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Versi 2409.0.2-premium

**Comment by andifahruddinakas** [comment]
Sudah disesuaikan melalui commit https://github.com/OpenSID/premium/commit/ed0d6c01f5545a28ffe8f5dc6d0a8b2916efd18f
