### ISSUE TITLE
Bug/error: data keluarga error

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8524]
### Jelaskan error yg dialami

data keluarga error 

### Cara untuk mereplikasi errornya

1. Klik Kependuduk
2. Klik Keluarga

### Hasil yg diharapkan

data keluarga tampil

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/ab82bc73-a335-4038-b84b-e1af60be1361)
![image](https://github.com/user-attachments/assets/03217a9b-93a3-421d-964a-5903ac443552)
Versi 2409.0.2-premium

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Versi 2409.0.2-premium

**Comment by andifahruddinakas** [comment]
Sudah disesuaikan melalui commit https://github.com/OpenSID/premium/commit/bd30ec671ae88a79ea1a6b7635621a097f419808
