### ISSUE TITLE
Bug/error: Penduduk Tidak Tetap tidak bisa ubah status menjadi Tetap

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8526]
### Jelaskan error yg dialami

Penduduk Tidak Tetap yang sudah masuk ke Keluarga status tidak bisa diubah menjadi penduduk Tetap

Penduduk sudah memiliki Surat Keterangan Pindah Domisili dan Desa ingin mengganti Status Penduduk tersebut menjadi Tetap.
### Cara untuk mereplikasi errornya

1. Penduduk
2. Pilih Penduduk Tetap yang sudah memiliki No KK / Masuk Ke Keluarga
3. Ubah Status Penduduk Menjadi Tetap

### Hasil yg diharapkan

Penduduk Tidak tetap yang sudah masuk ke menu Keluarga tetap bisa di Ubah statusnya ke Penduduk Tetap

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/bf61dc5d-b572-4590-bd9e-a0862c96fb9b)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

OpenSID v2409.0.2-premium

**Comment by balongbesuk** [comment]
untuk perubahan status tersebut nantinya masuk ke log penduduk nanti seperti apa? pengaruh ke buku laporan penduduk bagaimana?

**Comment by ariandii** [comment]
nampaknya sejak lama penduduk yang berstatus tidak tetap, tidak bisa ditambah ke Keluarga.

yang bisa muncul saat menambah Keluarga hanya penduduk berstatus Tetap.
