### ISSUE TITLE
Bug/error: sortir usia calon pemilih di bawah 17 tahun

### ISSUE THREAD

**Issue by typevant** [OpenSID/OpenSID#8529]
### Jelaskan error yg dialami

Pada saat menyortir calon pemilih, terdapat usia di bawah 17 tahun yang tersaring.
![image](https://github.com/user-attachments/assets/c682991f-1918-4d80-bcb1-cccc3d76c875)

### Cara untuk mereplikasi errornya

1. Pergi menu kependudukan
2. Pilih Calon Pemilih
3. Sortir Umur Pada ....

### Hasil yg diharapkan

Usia yang tersaring pada calon pemilih di atas 17 tahun.

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/2716179b-525c-4e45-b72e-f437385796e6)

### Rilis Versi OpenSID

Rilis Umum

### Versi OpenSID

v2411.0.0

### Tema Yang Digunakan

DeNava

**Comment by andifahruddinakas** [comment]
Mas @typevant , untuk data DPT yg ditampilkan yakni penduduk minimal yang sdh berumur 17 atau status perkawinan sdh kawin.
