### ISSUE TITLE
Jumlah RW

### ISSUE THREAD

**Issue by abieroni** [OpenSID/OpenSID#853]
![test](https://user-images.githubusercontent.com/25345246/37307416-77ff41ec-266d-11e8-95eb-c32c402eecad.jpg)

Kenapa di Menu Penduduk Tab Wilayah Administrasi jumlah RW di tabel tidak muncul. Mohon bantuannya?

**Comment by eddieridwan** [comment]
Apakah hasil import atau pengisian di menu Penduduk > Wilayah Administratif?

Seperti contoh di situs demo http://sid.bangundesa.info, bisa saja memang tidak ada RW (misalnya di Lombok Barat tidak ada RW), yaitu diisi '-'.

**Comment by abieroni** [comment]
Awalnya ada Om, di data Penduduk semua RW masih ada

**Comment by pandigresik** [comment]
Coba klik rincian, kemudian lakukan proses tambah RW. kemudian lihat lagi hasilnya apakah masih 0 atau sudah berubah.

**Comment by SahlaniAfnan** [comment]
Pilih Menu Keluarga/penduduk. Cek RW Apakah sudah terisi dengan benar....?
![keluarga](https://user-images.githubusercontent.com/15683308/37626584-38ada5e2-2c03-11e8-9994-63e84083a9c0.jpg)

**Comment by eddieridwan** [comment]
Sepertinya masalah di data anda. Untuk bisa dibantu, harap:

1. lampirkan data yg anda impor
2. jelaskan secara RINCI, langkah yg anda lakukan setelah mengimpor data. Perubahan apa saja yang telah anda lakukan
3. lampirkan backup lengkap data sekarang (.sql), di mana menurut laporan anda: di penduduk RW tampil, tetapi di keluarga tidak

Kalau datanya tidak boleh dipublikasikan, kirim ke inbox di FB (Eddie Ridwan).
