### ISSUE TITLE
Permintaan fitur: ubah dan tambah kategori umur oleh pengguna

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8530]
### Apa kekurangan yg ingin diatasi?

terdapat update kategori umur dari laman Kemenkes dengan perubahan tersebut pada fitur statistik kependuduk (kategori umur) pada OpenSID juga dapat diubah atau ditambah oleh Desa agar dapat menyesuaikan dengan kategori umur pada laman Kemenkes

![image](https://github.com/user-attachments/assets/4eda4be1-a71e-4b1a-8a83-bb31ab481c3d)
![image](https://github.com/user-attachments/assets/026cccaa-67e9-4001-836c-d69312ea409e)

### Jelaskan solusi yg diinginkan

Kategori Umur dapat diubah atau ditambah dari OpenSID oleh Pengguna.

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

Versi 2409.10.1-premium

### Informasi tambahan

Fitur ini dibuat untuk mendukung Perlombaan Desa Cantik

**Comment by andifahruddinakas** [comment]
Duplicate issue https://github.com/OpenSID/OpenSID/issues/8397
