### ISSUE TITLE
Bug/error: galeri pada halaman website hanya menampilkan 10 galeri

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8533]
### Jelaskan error yg dialami

galeri pada halaman website hanya menampilkan 10 galeri, pada halaman admin memiliki lebih dari 10 galeri yang aktif

### Cara untuk mereplikasi errornya

1. admin web
2. galeri

### Hasil yg diharapkan

menampilkan galeri sesuai yang ada di menu admin galeri

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/2220b3c9-c9b1-4cff-9419-112cecdd1826)

![image](https://github.com/user-attachments/assets/1f3112f4-1a59-4862-b58c-7398936e2eea)

![image](https://github.com/user-attachments/assets/be493c61-d0ee-45de-ad7b-b8973f8bd94b)

![image](https://github.com/user-attachments/assets/b562e7f5-dc56-45f4-8122-bc7f389597d3)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

OpenSID 2410.0.0-premium

**Comment by andifahruddinakas** [comment]
Sudah disesuaikan melalui commit https://github.com/OpenSID/premium/commit/31617831785c5a5f18499a7e62e4ef1a4a6d98f4
