### ISSUE TITLE
Filter status surat master

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#8534]
Perlu ditambahkan filter untuk menyaring data master surat berdasarkan statusnya, agar tidak tampil semua bisa buat defaultnya yakni yang aktif.

![image](https://github.com/user-attachments/assets/20c7aeb7-e3aa-4bfb-88d9-4e6596d0b5cf)

Catatan : 
- [ ] tambahkan juga untuk surat dinas
- [ ] pada cetak surat, tampilkan surat yang aktif saja
- [ ] pada cetak surat layanan madiri, tampilkan surat yang aktif saja

**Comment by pandigresik** [comment]
Sudah diselesaikan pada PR https://github.com/OpenSID/premium/pull/4185
