### ISSUE TITLE
Bug/error: layanan mandiri error 500

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8547]
### Jelaskan error yg dialami

layanan mandiri error 500, ketika di klik tombol layanan mandiri error 500 link 

### Cara untuk mereplikasi errornya

1. klik tombol layanan mandiri

### Hasil yg diharapkan

tombol layanan mandiri normal kembali

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/0126692a-2e46-4dc2-a753-5c56ec9c37b3)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

OpenSID 2410.0.0-premium -

### Informasi tambahan

ini terjadi di database gabungan Kab. Paser dan Kab. Tabanan, di berputar aman

**Comment by pandigresik** [comment]
cara replikasinya bagaimana kalau di berputar aman ?

**Comment by pandigresik** [comment]
mungkin lebih baik untuk layanan mandiri url-nya diganti menjadi layanan-mandiri/masuk jadi lebih mudah tanpa harus masuk ke anjungan terlebih dahulu, padahal saat ini anjungan dijadikan sebagai module dimana ada kemungkinan desa bisa melepas/ menghapus module tersebut 

`Route::group('layanan-mandiri', ['namespace' => 'fmandiri'], static function (): void {
    Route::get('/', static function (): void {
        redirect(route('anjungan.index'));
    });`

Saat ini layanan-mandiri akan diarahkan ke module anjungan lalu kemudian diredirect kembali ke layanan mandiri berdasarkan kondisi tertentu. Akan lebih sederhana jika link dibedakan masing-masing: 

1. Link layanan mandiri
2. Link anjungan
3. Link buku tamu

**Comment by rgrahardi** [comment]
Ijin Mengupdate Informasi

Desa yang Melapor

1. Desa Saingprupuk Kab Paser Layanan Mandiri sudah aman bersamaan di Perbaiki menu Anjungan Jum'at sore 

![image](https://github.com/user-attachments/assets/e374861d-fc16-4e31-809f-5877e76ed904)

**Comment by rgrahardi** [comment]
Desa yang Melapor 

Desa Angseri Kab Tabanan belum aman

![image](https://github.com/user-attachments/assets/f86f1344-c47e-449f-8a7e-e1a7a5608f00)
![image](https://github.com/user-attachments/assets/75e14fdc-9aa3-4559-ab52-74e5647b9a22)


cc mas @andifahruddinakas mas @scqolbu24 mas @apidong

**Comment by rgrahardi** [comment]
cc mas @pandigresik

**Comment by pandigresik** [comment]
> Desa yang Melapor
> 
> Desa Angseri Kab Tabanan belum aman
> 
> ![image](https://private-user-images.githubusercontent.com/55429781/374073760-f86f1344-c47e-449f-8a7e-e1a7a5608f00.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyOTAxNDAsIm5iZiI6MTcyODI4OTg0MCwicGF0aCI6Ii81NTQyOTc4MS8zNzQwNzM3NjAtZjg2ZjEzNDQtYzQ3ZS00NDlmLThhN2UtZTFhN2E1NjA4ZjAwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA3VDA4MzA0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU5Nzg5MGRiNWZmNzk5ZmFlY2FjOWFjZTE5MWUwYjhjYmI2NGE1MzMyZmFmNDE0NzNhMjgzNzJjOTE1MDBhYjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ZZSlE-k6YxzERfN43PxBzExepYWH8s009sj9LetfSLM) ![image](https://private-user-images.githubusercontent.com/55429781/374074008-75e14fdc-9aa3-4559-ab52-74e5647b9a22.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyOTAxNDAsIm5iZiI6MTcyODI4OTg0MCwicGF0aCI6Ii81NTQyOTc4MS8zNzQwNzQwMDgtNzVlMTRmZGMtOWFhMy00NTU5LWFiNTItNzRlNTY0N2I5YTIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA3VDA4MzA0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwNmM5MThkNDI4YTJiMmVjYzAzMzZiZmQ2YTg3YTc3MDA4NjI4NGJmMjZlODAzMThkMGI2ZDFjMGQ1ZmE3YzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.m3bEnuff-SEoUXGKC63B1RS0ANjqntKdNUlQXQ0HKxs)
> 
> cc mas @andifahruddinakas mas @scqolbu24 mas @apidong

apakah ini sudah dilakukan perbaikan seperti di paser ?

**Comment by andifahruddinakas** [comment]
Sudah diarahkan ke 
![image](https://github.com/user-attachments/assets/ca2c85bb-1102-4d21-9e16-7035f79b7071)
