### ISSUE TITLE
Bug/error: Update terbaru, menu anjungan tidak bisa digunakan 

### ISSUE THREAD

**Issue by ilhamwahyu-ni** [OpenSID/OpenSID#8549]
### Jelaskan error yg dialami

harus ada aktivasi?

padahal sudah langganan.

![image](https://github.com/user-attachments/assets/a161ca2d-2b26-491c-8a8a-2826f64e678b)

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

normal bisa akses menu anjungan

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/25ed3787-d678-4315-bc94-9cc932b35556)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

 2410.0.0

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki, bisa cek https://forum.opendesa.id/d/348-solusi-sementar-error-anjungan/2 untuk solusi sementara
