### ISSUE TITLE
Prodeskel: hubungkan isian data prodeskel dengan isian data penduduk

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#855]
Issue2 terkait di bawah menyediakan analisis master untuk memasukkan Data Dasar Keluarga dan Data Anggota Keluarga Prodeskel ke modul Analisis.

Jika juga menginginkan agar data isian di data Prodeskel disinkronkan dengan data isian Penduduk dan Keluarga di database OpenSID.

Misalnya, pada Data AK Prodeskel, isian Nomor Akte Kelahiran, Hubungan dengan Kepala Keluarga, Status Perkawinan, dll juga ada di data Penduduk OpenSID. Tentunya kita inginkan data Prodeskel dan data OpenSID sama.

Issue ini adalah untuk menyusun spesifikasi persamaan dan konversi antara data isian Prodeskel dan data OpenSID. Misalnya, kode untuk Mata Pencaharian Pokok/Pekerjaan (Prodeskel) berbeda dengan kode Pekerjaan di OpenSID (yang berbasis kode Disdukcapil). Apakah bisa diharmoniskan?

Issue terkait:

* #848 
* #849 
* #850

**Comment by eddieridwan** [comment]
Data Prodeskel diatur oleh Permendagri Nomor 12 Tahun 2007. Pengisian data keluarga diatur oleh Lampiran 1 dari Permendagri tersebut.

* [Permendagri 12/2007](https://github.com/OpenSID/OpenSID/files/1822238/permendagrino-141028093304-conversion-gate02.pdf)
* [Permendagri 12/2007 Lampiran 1](https://github.com/OpenSID/OpenSID/files/1822239/permendagrino-141028094431-conversion-gate01.pdf)
* [Permendagri 12/2007 Lampiran 2](https://github.com/OpenSID/OpenSID/files/1822240/permendagrino-141028094807-conversion-gate02.pdf)
* [Permendagri 12/2007 Lampiran 3](https://github.com/OpenSID/OpenSID/files/1822241/permendagrino-141028100428-conversion-gate02.pdf)
[Permendagri 12/2007 Lampiran 4](https://github.com/OpenSID/OpenSID/files/1822242/permendagrino-141028111022-conversion-gate01.pdf)

**Comment by eddieridwan** [comment]
Rumus persamaan data Penduduk OpenSID dengan data Prodeskel didokumentasikan di http://bit.ly/persamaan-prodeskel

**Comment by eddieridwan** [comment]
Ternyata daftar pilihan dan kode isian DAK dan DDK di form isian Prodeskel online BERBEDA dengan yang ada di Lampiran 1 Permendagri 12/2007.

Kita harus mengikuti form isian Prodeskel online, karena data Prodeskel akan kita unggah dan isi di situ.

Jadi analisis master data anggota keluarga dan DDK perlu diubah dan disesuaikan dengan form isian Prodeskel online.

Analisis data anggota keluarga berikut telah disinkronkan dengan form isian di portal Prodeskel Kemendagri.

[analisis_DAK_Profil_Desa.xls.zip](https://github.com/OpenSID/OpenSID/files/1822547/analisis_DAK_Profil_Desa.xls.zip)

Perlu bantuan untuk mengubah analisis master DDK supaya sinkron dengan form isian Prodeskel online.

**Comment by eddieridwan** [comment]
Berikut ini berkas analisis master DDK yang perlu disesuaikan dgn form isian Prodeskel online.

[analisis_DDK_Profil_Desa.xls.zip](https://github.com/OpenSID/OpenSID/files/1822592/analisis_DDK_Profil_Desa.xls.zip)

**Comment by eddieridwan** [comment]
Bung https://github.com/MUHAMMADRANGSEL, bisa bantu memperbaiki analisis_DDK_Profil_Desa.xls seperti dijelaskan di atas? Produksi galian sudah saya pindahkan dari analisis DAK ke analisis DDK, tapi urutannya perlu disesuaikan.

**Comment by MUHAMMADRANGSEL** [comment]
alhamdulillah issue ini sudah selesai dikerjakan dan bisa dicoba sid.bangundesa.info
![image](https://user-images.githubusercontent.com/25834335/37634189-7aea27e6-2c30-11e8-8601-291ce2ec3402.png)
![image](https://user-images.githubusercontent.com/25834335/37634204-8a91ca8c-2c30-11e8-9a53-3c978acca061.png)
![image](https://user-images.githubusercontent.com/25834335/37634210-9288de42-2c30-11e8-8d25-0d888487cbde.png)
dan kami lampirkan analisisnya : 
[analisis_DDK_Profil_Desa.zip](https://github.com/OpenSID/OpenSID/files/1827794/analisis_DDK_Profil_Desa.zip)

**Comment by eddieridwan** [comment]
@MUHAMMADRANGSEL hebat! Sudah ditambahkan ke rilis sebagai analisis bawaan sistem.

Tugas berikutnya adalah melengkapi http://bit.ly/persamaan-prodeskel. Itu tugas utama issue ini.
