### ISSUE TITLE
kepemilikan buku nikah tidak bisa filter data sesuai jumlahnya

### ISSUE THREAD

**Issue by mranca** [OpenSID/OpenSID#8556]
### Jelaskan error yg dialami

saat klik jumlah data yang memiliki buku nikah maka data yang telfiter tidak menampilkan jumlah yang seharusnya

### Cara untuk mereplikasi errornya

1. masuk admin
2. klik statistik kependudukan
3. klik buku nikah
4. klik jumlah pemilik buku nikah

### Hasil yg diharapkan

.

### Tangkapan layar dan log error

jumlah pemilikan buku nikah
![Sistem-Informasi-Desa-Tongke-Tongke-10-09-2024_06_29_AM](https://github.com/user-attachments/assets/09db4d71-a32a-4e86-8056-077f267f670a)
jumlah data yang di tampilkan
![Sistem-Informasi-Desa-Tongke-Tongke-10-09-2024_06_31_AM](https://github.com/user-attachments/assets/5d677825-02ab-45ac-af27-4398f5090ce6)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

terbaru

### Tema Yang Digunakan

.

### Informasi tambahan

.

**Comment by andifahruddinakas** [comment]
Sudah disesuaikan melalui commit https://github.com/OpenSID/premium/commit/b20ef921aeccc1ef0f94601bead2210eba12b0a6
