### ISSUE TITLE
Gagal Menambahkan Foto Produk

### ISSUE THREAD

**Issue by Pedry08** [OpenSID/OpenSID#8557]
### Jelaskan error yg dialami

Tidak bisa isi foto produk di Lapak Desa

### Cara untuk mereplikasi errornya

1. Pergi ke halaman "Admin"
2. Masuk ke "Lapak"
3. Klik "Produk", "tambah produk"
4. Tidak bisa menambahkan Foto

### Hasil yg diharapkan

Bisa menambahkan foto produk

### Tangkapan layar dan log error

![Foto Produk](https://github.com/user-attachments/assets/45dccb37-d529-4f89-8bdf-946ba9e184fd)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2410

**Comment by andifahruddinakas** [comment]
Pak @, bisa sertakan log errornya

**Comment by Pedry08** [comment]
> Pak @, bisa sertakan log errornya

tidak mucul log errornya kak, cuman saat mau isi foto produk, setelah klik "open", langsung kembali ke explorer.

**Comment by andifahruddinakas** [comment]
pak @Pedry08, @rgrahardi, bisa replikasi ke https://berputar.opendesa.id/lapak_admin/produk_form, karena sy coba tidak menemukan masalah tsb.

**Comment by Pedry08** [comment]
baik kak, udah solve.
