### ISSUE TITLE
Bug/error: form isian surat keterangan nikah warga untuk non muslim belum terupdate

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8558]
### Jelaskan error yg dialami

form isian surat keterangan nikah warga untuk non muslim bawaan sistem belum terupdate 

### Cara untuk mereplikasi errornya

1. cetak surat
2. buat surat keterangan nikah warga untuk non muslim bawaan sistem 

### Hasil yg diharapkan

menggunakan form isian terbaru

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/86286953-02b5-4b49-8a05-a0f4bc23cd35)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

OpenSID v2410.0.0-premium

**Comment by andifahruddinakas** [comment]
Duplicate of https://github.com/OpenSID/OpenSID/issues/8554
