### ISSUE TITLE
Bug/error: nomor surat dengan nomor surat hasil scan tidak sesuai

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8559]
### Jelaskan error yg dialami

nomor surat hasil cetak dengan nomor surat hasil scan tidak sesuai

### Cara untuk mereplikasi errornya

1. Modul Layanan Surat
2. Menu Arsip Surat
3. klik qrcode
4. scan qrcode

![image](https://github.com/user-attachments/assets/c5569587-646f-43e2-ad91-0605f35d0286)

### Hasil yg diharapkan

nomor surat sesuai surat hasil cetak dan surat scan qrcode

### Tangkapan layar dan log error

Nomor Surat Hasil Cetak Surat
![image](https://github.com/user-attachments/assets/f71cf432-1baa-468f-8412-e4a1df7a6755)

Nomor Surat Scan di arsip surat

![image](https://github.com/user-attachments/assets/cdb21bf5-3046-465d-9016-3b88e1ff561d)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Versi 2410.0.0-premium

### Informasi tambahan

Laporan Desa Antap Kab. Tabanan Bali

**Comment by andifahruddinakas** [comment]
mas @rgrahardi, sertakan databasenya.

**Comment by rgrahardi** [comment]
sudah saya lampirkan mas @andifahruddinakas

**Comment by pandigresik** [comment]
Sudah diperbaiki PR https://github.com/OpenSID/premium/pull/4158
