### ISSUE TITLE
Bug NIP Perangkat Desa

### ISSUE THREAD

**Issue by maswidtubanjatim** [OpenSID/OpenSID#856]
NIP Pamong desa tidak bisa tampil di semua surat pelayanan untuk kelurahan. Export doc hasil ubahan
![nip](https://user-images.githubusercontent.com/37429011/37503115-20397ce0-2909-11e8-86e0-f3c6902994ff.png)

**Comment by MUHAMMADRANGSEL** [comment]
Solusinya ini coba copy paste khususus untuk NIP
[surat_ket_domisili.zip](https://github.com/OpenSID/OpenSID/files/1818109/surat_ket_domisili.zip)

**Comment by eddieridwan** [comment]
@maswidtubanjatim : masing2 jenis surat dikembangkan sendiri-sendiri. Harap jelaskan khususnya surat mana yang bermasalah.

**Comment by suphm** [comment]
sepertinya ini masalahnya. hanya satu staff yang normal/ yang ada nip nya.
![2018-11-10_1366x768_scrot](https://user-images.githubusercontent.com/3823496/48289800-4b5d2d80-e4a3-11e8-8bcc-5ffa785011b7.png)

**Comment by suphm** [comment]
sudah saya coba ubah data nip pamong dan hasil normal.

saya kira tutup saja isu ini.

**Comment by eddieridwan** [comment]
@maswidtubanjatim issue ini akan kami tutup, karena sepertinya lebih terkait cara penggunaan, bukan bug yg perlu diperbaiki. Misalnya, lihat panduan https://github.com/OpenSID/OpenSID/wiki/Kode-Isian-Template-Surat.
