### ISSUE TITLE
Bug/error: default ukuran font saat ini default 16px 

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8560]
### Jelaskan error yg dialami

- default opensid saat ini menggunakan 16 px diganti menggunakan defaultnya menggunakan 12pt ( aturan seragam dengan surat ms word )
- px tidak digunakan lagi gunakan ukuran pt

### Cara untuk mereplikasi errornya

1. pengaturan surat
2. tambah surat
3. ukuran font 

![image](https://github.com/user-attachments/assets/09a8d8d0-4510-4a87-ae4f-b0a4f1a03900)

### Hasil yg diharapkan

default ukuran font opensid 12pt dan ukuran yang digunakan di OpenSID pakai pt tidak pakai px

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

OpenSID 2410.0.0-premium

### Informasi tambahan

Laporan Pak Lukman OpenDesa

**Comment by pandigresik** [comment]
Sepertinya tcpdf jika ukuran font tidak diset maka otomatis akan diset menjadi 10 pt
https://github.com/OpenSID/OpenSID/issues/8517#issuecomment-2388482375
