### ISSUE TITLE
grafik pendapatan desa dan belanja desa hilang

### ISSUE THREAD

**Issue by mranca** [OpenSID/OpenSID#8561]
### Jelaskan error yg dialami

grafik total akumulasi pendapatan dan Belanja hilang 

### Cara untuk mereplikasi errornya

lihat pada halaman footer website, jika apbdes belm aktif maka bisa di aktifkan di 

1. masuk adamin
2. klik admin web
3. klik pengaturan
4. klik apbdes footer dan tampilkan ya

### Hasil yg diharapkan

seharunya data belanja desa dan pendapan desa muncul sesuai dengan versi sebelumnya

### Tangkapan layar dan log error

![Website-Resmi-Desa-Tongke-Tongke-Kecamatan-Sinjai-Timur-Kabupaten-Sinjai-10-10-2024_06_37_AM](https://github.com/user-attachments/assets/3f2345e1-65c6-41ab-a1c9-147023c05635)

contoh gambar di bawah yang tampil belanja dan pendapatan desa
![Website-Resmi-Desa-Pasimarannu-10-10-2024_06_39_AM](https://github.com/user-attachments/assets/77f6b058-befe-44cc-b8e5-3781130290f3)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v2410.0.1

### Tema Yang Digunakan

.

### Informasi tambahan

.

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/4167
