### ISSUE TITLE
Bug/error: Ada yang bisa bantu kami terkait peta, masih not responding (page unrespon)

### ISSUE THREAD

**Issue by alit2310** [OpenSID/OpenSID#8564]
### Jelaskan error yg dialami

Ada yang bisa bantu kami terkait peta, masih not responding (page unrespon)
atau minta tolong dicek database kami, karena kami sangat perlu terkait fitur peta di opensid
![Screenshot 2024-10-10 133238](https://github.com/user-attachments/assets/718191d2-5aa3-4eb7-b12f-def22c688afe)

### Cara untuk mereplikasi errornya

Ada yang bisa bantu kami terkait peta, masih not responding (page unrespon)
atau minta tolong dicek database kami, karena kami sangat perlu terkait fitur peta di opensid

### Hasil yg diharapkan

Ada yang bisa bantu kami terkait peta, masih not responding (page unrespon)
atau minta tolong dicek database kami, karena kami sangat perlu terkait fitur peta di opensid

### Tangkapan layar dan log error

![Screenshot 2024-10-10 133238](https://github.com/user-attachments/assets/069f8676-e1f7-4fed-a18b-cab72f6ca5e1)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

24.10

### Tema Yang Digunakan

Pusako 2.4

**Comment by andifahruddinakas** [comment]
https://github.com/OpenSID/OpenSID/issues/8423

**Comment by rgrahardi** [comment]
sudah ada pembahasan di  issue pak https://github.com/OpenSID/OpenSID/issues/8423 jika masih bermasalah silakan dibawa ke Klinik OpenSID pak untuk ditelusuri bersama
