### ISSUE TITLE
Bug/error: Lampiran di pratinjau pengaturan surat tidak tampil

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8565]
### Jelaskan error yg dialami

- Lampiran di pratinjau pengaturan surat tidak tampil
- Lampiran di pratinjau cetak surat saja yang tampil

### Cara untuk mereplikasi errornya

1. pengaturan surat
2. lihat template surat
3. tinjau pdf

### Hasil yg diharapkan

di menu pengaturan surat bisa pratinjau lampiran seperti di menu cetak surat

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/3692a934-6506-4265-abfa-d5f707aa7d30)
![image](https://github.com/user-attachments/assets/78c6bfd1-2490-440d-b526-a47ad75b69d4)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Versi 2410.0.1-premium

Laporan Desa Gunung Salak
_No response_

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/4162
