### ISSUE TITLE
Bug/error: tidak dapat meninjau pdf surat keterangan kelahiran dengan lampiran F-2.01

### ISSUE THREAD

**Issue by zeneight** [OpenSID/OpenSID#8566]
### Jelaskan error yg dialami

Ketika cetak surat keterangan kelahiran dengan lampiran F2.01 tidak dapat ditinjau pdf nya

### Cara untuk mereplikasi errornya

1. Buka halaman layanan surat > cetak surat > Pilih 'Buat Surat' Keterangan Kelahiran
2. Mengisi formulir surat dengan mencentang lampiran F-2.01
3. Setelah submit dan setelah itu di halaman selanjutnya mengklik tombol 'tinjau pdf'
4. Muncul popup error

### Hasil yg diharapkan

Muncul pdf surat keterangan lahir dengan lampiran F-2.01

### Tangkapan layar dan log error

![WhatsApp Image 2024-10-10 at 16 04 57_db40fe49](https://github.com/user-attachments/assets/24f92e06-9763-444f-a4c9-cb704b57a917)
![WhatsApp Image 2024-10-10 at 16 02 39_ee5c86da](https://github.com/user-attachments/assets/194a507b-8c28-47c4-a657-08f86db71c82)
![WhatsApp Image 2024-10-10 at 16 02 15_b80c4623](https://github.com/user-attachments/assets/498d57b5-3626-4fdf-bce2-80ebd7214d04)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2410.0.0-premium

### Tema Yang Digunakan

Pusako 2.4

**Comment by pandigresik** [comment]
@zeneight bisa export surat yang mengalami error dan lampirkan di issue ini, agar mudah melakukan replikasi

**Comment by Pedry08** [comment]
kak @zeneight , apakah menggunakan Internet Download Manager (IDM)? kalo iya, mungkin bisa dicoba nonaktifkan terlebih dahulu.

**Comment by pandigresik** [comment]
Kami coba aman saja, jadi perlu dipastikan dulu template surat yang digunakan

![image](https://github.com/user-attachments/assets/548348ba-29b3-41d4-8308-b910722d31c6)

**Comment by zeneight** [comment]
> @zeneight bisa export surat yang mengalami error dan lampirkan di issue ini, agar mudah melakukan replikasi

maksudnya jsonnya ya pak? ini saya lampirkan
[template_surat_tinymce_15_10_2024.json](https://github.com/user-attachments/files/17372075/template_surat_tinymce_15_10_2024.json)

ini tambahan pada console log ada respon error 500
![WhatsApp Image 2024-10-15 at 11 48 37_f362a295](https://github.com/user-attachments/assets/b39e8d28-13ae-461b-8883-d00652253d01)

**Comment by rgrahardi** [comment]
pak @zeneight saya coba replikasi aman pak di versi rev 03, jika masih bermsalahan dapat dibawakan ke klinik OpenSID pak 

![image](https://github.com/user-attachments/assets/c7521f6d-f8f9-4157-9adc-148b5f8082ac)
