### ISSUE TITLE
Bug/error: Lampiran F2-01 surat kelahiran tidak sesuai

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8567]
### Jelaskan error yg dialami

Formulir Lampiran F2-01 surat kelahiran tidak sesuai

### Cara untuk mereplikasi errornya

1. cetak surat
2. pilih surat kelahiran
3. pratinjau surat dan lampiran

### Hasil yg diharapkan

lampiran F2-01 sesuai

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/223bc404-1165-4727-aa15-b909a7902907)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Versi 2410.0.1-premium

### Informasi tambahan

Laporan Desa Gunung Salak

**Comment by pandigresik** [comment]
mas @rgrahardi  tampilan yang benar seperti apa ?

**Comment by pandigresik** [comment]
F2-01 seingat saya digunakan oleh beberapa surat, tidak hanya surat kelahiran saja

**Comment by balongbesuk** [comment]
itu format simpel yang dipakai d beberapa daerah, yang baku bisa 3 lembar

**Comment by andifahruddinakas** [comment]
Untuk F-2.01 digunakan disurat kelahiran dan kematian.

**Comment by andifahruddinakas** [comment]
mas @rgrahardi, hal yang perlu dikertahui. Karena lampiran digunakan untuk beberapa surat dan maka lampiran F-2.01 dibagi menjadi F-2.01-Kelahiran dan F-2.01-Kematian.
