### ISSUE TITLE
Bug/error:  realisasi pelaksanaan anggaran tidak tampil

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8568]
### Jelaskan error yg dialami

 - menu Input Manual ->  data pelaksanaan anggaran/ realisasi tidak tampil
 - menu laporan manual -> grafik data pelaksanaan anggaran / realisasi tidak tampil
 - 
### Cara untuk mereplikasi errornya

1. modul keuangan 
2. input manual 
3. pilih jenis anggaran pendapat
4. isi nilai anggaran 
5. isi nilai realisasi
6. simpan

### Hasil yg diharapkan

realisasi anggaran pendapatan tampil normal di menu grafik laporan manual dan halaman utama website APDES

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/210d245d-6549-4985-8938-e79e45e1365f)
![image](https://github.com/user-attachments/assets/9fdcfd54-21a8-4c8f-8aa6-ab155e3558ef)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Versi 2410.0.1-premium

### Informasi tambahan

Laporan Desa Sidokumpul

**Comment by andifahruddinakas** [comment]
mas @rgrahardi, cek issue https://github.com/OpenSID/OpenSID/issues/8561
