### ISSUE TITLE
Bug/error: Daftar Peserta Bantuan tidak tampil

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8569]
### Jelaskan error yg dialami

Daftar Peserta Bantuan tidak tampil hanya terjadi di Desa https://babang.desa.id/
- migrasi sudah berhasil
- sudah di cek periksa
- database sudah saya lampirkan

### Cara untuk mereplikasi errornya

1. KLik menu bantuan
2. klik bantuan
3. lihat daftar peserta

### Hasil yg diharapkan

daftar peserta bisa tampil lagi

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/e8db787d-44ca-4eb1-893c-51ba02225fc3)
![image](https://github.com/user-attachments/assets/f866d75d-dcf7-46f6-8096-47ef46deff58)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

OpenSID v2410.0.1-premium

### Informasi tambahan

Laporan Desa Babang dan hanya terjadi di Desa tersebut.

**Comment by andifahruddinakas** [comment]
mas @rgrahardi, jika hanya terjadi didesa2 tertentu bisa disertakan databasenya jg. untuk lebih jauh, bisa dibuatkan akses panel sementara untuk dicek secara langsung.

**Comment by rgrahardi** [comment]
mas @andifahruddinakas DB sudah saya lampirkan

**Comment by pandigresik** [comment]
Sudah diperbaiki PR https://github.com/OpenSID/premium/pull/4159
