### ISSUE TITLE
gagal unggah tema

### ISSUE THREAD

**Issue by mranca** [OpenSID/OpenSID#8572]
### Jelaskan error yg dialami

saat unggah tema tidak berhasil, dan tidak ada notifikasi berhasil, log error pun tidak ada

### Cara untuk mereplikasi errornya

1. masuk admin
2. klik admin web
3. klik tema
4. klik unggah tema
5. klik pindai

### Hasil yg diharapkan

.

### Tangkapan layar dan log error

![tema](https://github.com/user-attachments/assets/91e0f8e2-da44-41bc-a8de-e88e366d57ad)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

terbaru

### Tema Yang Digunakan

.

### Informasi tambahan

.

**Comment by andifahruddinakas** [comment]
mas @mranca, bisa diperjelas seperti apa msalahnya. mungkin bisa sertakan video saat melakukan hal tsb.

**Comment by mranca** [comment]
Ok saya buat videony @andifahruddinakas

**Comment by mranca** [comment]
https://github.com/user-attachments/assets/96560c8b-4ac1-47ab-9d9c-9f83cd2024a7

tema tidak muncul setelah unggah @andifahruddinakas

**Comment by apidong** [comment]
saya dump error karena ini 
![image](https://github.com/user-attachments/assets/d5544a84-a94b-4103-a4eb-20f067e2d9c9)
