### ISSUE TITLE
Bug/error: Hapus Surat Desa Secara Masal tidak Berfungsi

### ISSUE THREAD

**Issue by luxmant354** [OpenSID/OpenSID#8576]
### Jelaskan error yg dialami

Ketika akan menghapus surat ubahan Versi Desa Secara Masal tidak berfungsi, hanya kehapus 1 item saja
![Screenshot_74](https://github.com/user-attachments/assets/37e98b8a-8371-452a-808f-730931fe59a7)

### Cara untuk mereplikasi errornya

dihapus satu per satu

### Hasil yg diharapkan

centang semua, kemudian tombol hapus secara masal berfungsi dengan baik

### Tangkapan layar dan log error

tidak terdeteksi error karena di notifikasi berhasil hapus

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2410.0.1-premium

**Comment by pandigresik** [comment]
Sudah diperbaiki pada PR https://github.com/OpenSID/premium/pull/4164
