### ISSUE TITLE
Bug/error: form utama surat pernyataan tidak muncul saat cetak surat dinas

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8577]
### Jelaskan error yg dialami

form utama surat pertanyaan tidak muncul saat cetak surat dinas

### Cara untuk mereplikasi errornya

1. Surat Dinas
2. Cetak Surat
3. Buat Surat
4. Form Utama tidak ada inputan seperti pada template surat

### Hasil yg diharapkan

pada form utama terdapat inputan sesuai dengan template surat pernyataan

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/51aacb04-a9b8-42fe-89a9-2f57b5438072)

![image](https://github.com/user-attachments/assets/eef3e792-ca9c-48cf-bac4-187e6a55d42c)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Versi 2410.0.1-premium

**Comment by andifahruddinakas** [comment]
Duplicate of https://github.com/OpenSID/OpenSID/issues/8554

![image](https://github.com/user-attachments/assets/956555c8-377e-401c-8a2c-c7eacfff3c95)
