### ISSUE TITLE
Bug/error: README.md bagian Kontributor, banyak berisikan foto kontributor yang tidak muncul

### ISSUE THREAD

**Issue by agung2001** [OpenSID/OpenSID#8578]
### Jelaskan error yg dialami

Pada file [README.md](https://github.com/OpenSID/OpenSID/blob/umum/README.md) kita dapat menemukan banyak foto yang tidak muncul dikarenakan ada beberapa syntax yang salah.

saya mengusulkan untuk menggunakan syntax berikut: https://contrib.rocks/image?repo=OpenSID/OpenSID
```
[![Contributors](https://contrib.rocks/image?repo=OpenSID/OpenSID)](https://github.com/OpenSID/OpenSID/graphs/contributors)
```
untuk men generate kontributor secara otomatis, sehingga masalah foto yang tidak muncul, tidak akan lagi terjadi
salah satu contoh repository yang menggunakan cara ini adalah: https://github.com/redis/node-redis

### Cara untuk mereplikasi errornya

1. Pergi ke halaman github OpenSID: https://github.com/OpenSID/OpenSID
2. Scroll ke bagian `👨‍💻KONTRIBUTOR`
3. **FAILED**: banyak foto kontributor tidak muncul

### Hasil yg diharapkan

Untuk meningkatkan branding dan professionalitas halaman GitHub OpenSID, perlu memperbaiki bagian `👨‍💻KONTRIBUTOR` nya

### Tangkapan layar dan log error

![Screenshot 2024-10-14 at 09 30 30](https://github.com/user-attachments/assets/e1c31dcb-3384-45c4-b9f2-2d549c15c29b)

### Rilis Versi OpenSID

Rilis Umum

### Versi OpenSID

Rilis v2410.0.0

**Comment by agung2001** [comment]
saya dapat membuat PR untuk issue ini, 
kalau berkenan bisa mengassign issue ini kepada saya
lalu saya bisa buatkan PR untuk issue ini

**Comment by andifahruddinakas** [comment]
mas @agung2001, silahkan buat PRnya dan tautkan link issue ini

**Comment by andifahruddinakas** [comment]
https://github.com/OpenSID/OpenSID/pull/8580
