### ISSUE TITLE
Bug/error: 

### ISSUE THREAD

**Issue by tamatea88** [OpenSID/OpenSID#8579]
### Jelaskan error yg dialami

saat login admin muncul error 500 bisa masuk ke dasboard admin setelah di back dr browsernya 

link saat terjadi error
https://desa.pituruh.id/siteman/auth

### Cara untuk mereplikasi errornya

login admin
input user pass
login

error 500

### Hasil yg diharapkan

tidak terjadi error saat login

### Tangkapan layar dan log error

![Screenshot_8](https://github.com/user-attachments/assets/6d9dfb6a-d784-4476-bae0-2e2f9140245c)

### Rilis Versi OpenSID

Rilis Umum

### Versi OpenSID

2408

**Comment by andifahruddinakas** [comment]
pak @tamatea88, bisa lakukan update ke versi terbaru, dan lakukan duplikasi ke https://demosid.opendesa.id/, bisa saja karena konfigurasi server dan cara install yg salah.

**Comment by tamatea88** [comment]
saat saya melakukan update ke versi 2410 web malah tidak bisa di buka dengan keterangan koneksi database.
config sudah di sesuaikan masih tetap error
