### ISSUE TITLE
Permintaan fitur: peningkatan Pull Request Template

### ISSUE THREAD

**Issue by agung2001** [OpenSID/OpenSID#8583]
### Apa kekurangan yg ingin diatasi?

**Pull Request template (PR Template)** bertindak sebagai pemandu saat melakukan kontribusi dan memberikan ringkasan terhadap perubahan yang terjadi pada repository maka dari itu peranya menjadi penting

https://github.com/OpenSID/OpenSID/blob/umum/.github/PULL_REQUEST_TEMPLATE.md
Menurut saya, saat ini PR template yang ada masih belum memiliki standard yang baik untuk digunakan. 
beberapa section seperti :
- Deskripsi
- Masalah Terkait (Related Issue)
- Langkah untuk mereproduksi (Steps to Reproduce)
- Daftar Periksa (Checklist)
- Tangkapan Layar (Screenshot)

### Jelaskan solusi yg diinginkan

Kita dapat menambahkan PR Template yang disediakan pada artikel berikut: https://axolo.co/blog/p/part-3-github-pull-request-template
dan membuatnya seperti berikut
```
## Deskripsi
<!--- Jelaskan perubahan Anda -->

## Masalah Terkait (Related Issue)
<!--- Proyek ini hanya menerima permintaan penarikan (pull request) terkait dengan (issue) yang masih terbuka -->
<!--- Jika mengusulkan fitur atau perubahan baru, harap diskusikan terlebih dahulu dalam (issue) -->
<!--- Jika memperbaiki bug, harus ada masalah yang menjelaskannya dengan langkah-langkah untuk mereproduksi -->
<!--- Harap berikan tautan (link) ke masalah tersebut di sini -->
<!--- Misalnya: 
- Solusi untuk {perbaikan|fitur baru} terkait issue {#1} 
- Solusi untuk {perbaikan|fitur baru} terkait issue {#2} 
- Solusi untuk {perbaikan|fitur baru} terkait issue {dst} 
-->

## Langkah untuk mereproduksi (Steps to Reproduce)
<!--- Jelaskan langkah-langkah yang diperlukan untuk mereproduksi masalah atau bug yang diperbaiki -->
<!--- Misalnya: 
1. Buka halaman utama
2. Klik tombol "Login"
3. Masukkan kredensial yang salah
4. Lihat pesan error yang muncul
-->

## Daftar Periksa (Checklist)
- [ ] Saya telah mematuhi [aturan penulisan script](https://github.com/OpenSID/OpenSID/wiki/Aturan-Penulisan-Script).
- [ ] Saya telah mengikuti [proses review pull request](https://github.com/OpenSID/OpenSID/wiki/proses-review-pull-request).

## Tangkapan Layar (Screenshot)
<!--- Mohon berikan Tangkapan Layar (Screenshot) untuk mempermudah proses evaluasi -->
```

### Apakah ada alternatif lain

ada banyak template yang tersedia pada artikel ini: https://axolo.co/blog/p/part-3-github-pull-request-template
akan tetapi solusi template yang saya berikan diatas, telah mewakili.

### Untuk versi OpenSID mana

Rilis v2410.0.0

**Comment by agung2001** [comment]
jika berkenan bisa assign issue ini ke saya
saya bisa membuat PR untuk issue ini

**Comment by andifahruddinakas** [comment]
> jika berkenan bisa assign issue ini ke saya saya bisa membuat PR untuk issue ini

Bisa menggunakan branch dev untuk memulai pekerjaan.
