### ISSUE TITLE
Tambahkan fungsi cetak & unduh data pada halaman statistik penduduk

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#8585]
![Image](https://github.com/user-attachments/assets/899726bc-57d6-44b7-8f2b-e53ffb2af67a)

Tambahkan fungsi cetak & export data pada halaman statistik yang ada di public seperti contoh pada halaman admin : 

![Image](https://github.com/user-attachments/assets/d7e88ad8-89d3-4333-8d5a-551d6a2f0566)

**Comment by andifahruddinakas** [comment]
Untuk penanda tangannya langsung kades saja

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/4186

**Comment by ariandii** [comment]
![Screenshot_20241024_070356_Print Spooler](https://github.com/user-attachments/assets/6cef3f35-c7a6-4793-821d-1ee5da75c0d9)

pada hasil klik cetak/unduh hanya muncul kolom jumlah, sedangkan judulnya tertulis menurut jumlah dan persentase.

apakah demikian?

**Comment by andifahruddinakas** [comment]
> ![Screenshot_20241024_070356_Print Spooler](https://private-user-images.githubusercontent.com/46939846/379497803-6cef3f35-c7a6-4793-821d-1ee5da75c0d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3MzIzMDYsIm5iZiI6MTcyOTczMjAwNiwicGF0aCI6Ii80NjkzOTg0Ni8zNzk0OTc4MDMtNmNlZjNmMzUtYzdhNi00NzkzLTgyMWQtMWVlNWRhNzVjMGQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI0VDAxMDY0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdjMWM4ZGM5NDBmYTA2YTg2M2E5NGNjZDM4YTdiMDFhZTRlYzk2NzIyNWU0MzhjMjczZWJhN2FkOTVhNjRkZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Ylxs3VUA3sN7b5JCslg3ELbvTfcPulgduYwCjnOXNKQ)
> 
> pada hasil klik cetak/unduh hanya muncul kolom jumlah, sedangkan judulnya tertulis menurut jumlah dan persentase.
> 
> apakah demikian?

Sesuai dengan kebutuhan issue disamakan dengan halaman admin, mungkin judulnya aja yg disesuaikan lg.
