### ISSUE TITLE
Tambah fungsi cetak & unduh data pada halaman statistik keluarga

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#8586]
![Image](https://github.com/user-attachments/assets/d44a04f8-9e44-4cd6-a0fd-79ff196c00e6)

Pada halaman statistik keluarga di halamanpublic juga perlu ditambahkan fungsi cetak & export data seperti yang ada di halaman admin : 

![Image](https://github.com/user-attachments/assets/757ea127-60b8-4667-b426-e6c5346c3381)

**Comment by andifahruddinakas** [comment]
Untuk penanda tangannya langsung kades saja

**Comment by habibie11** [comment]
ini sepertinya sudah terselesaikan di PR https://github.com/OpenSID/premium/pull/4178

cc mas @pandigresik @andifahruddinakas
