### ISSUE TITLE
Tambahkan fungsi cetak & unduh data pada halaman statistik program bantuan

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#8587]
![Image](https://github.com/user-attachments/assets/22fe2b9e-f2a5-4b7c-a266-4f2433537811)

Pada halaman public statistik program bantuan juga perlu ditambahkan fungsi cetak dan unduh seperti yang ada pada halaman admin 
data yang di unduh juga pastikan bahwa data yang di tampilkan di halaman admin saja. 

![Image](https://github.com/user-attachments/assets/753430db-0a57-4ab2-91ca-de109695ee27)

**Comment by andifahruddinakas** [comment]
Untuk penanda tangannya langsung kades saja

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/4186
