### ISSUE TITLE
Tambahkan fungsi cetak & unduh data pada halaman statistik kesehatan stunting

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#8588]
![Image](https://github.com/user-attachments/assets/92c1f38e-8b4a-49c5-ab94-d1877cf78d74)

Pada halaman e-stunting juga perlu ditambahkan fungsi cetak & unduh terkait data yang ditampilkan pada table diatas .
fungsi ini juga sudah tersedia pada halaman admin tinggal mengikuti fungsi tersebut .

![Image](https://github.com/user-attachments/assets/2ce7781b-c8ae-493d-966b-35e9ffdf7a48)

**Comment by andifahruddinakas** [comment]
Untuk penanda tangannya langsung kades saja
