### ISSUE TITLE
Sesuaikan file konfig untuk menerima pengaturan dari siappakai level yang akan digunakan pada database gabungan

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/OpenSID#8590]
Penambahan terkait pengaturan yang ada di config untuk menerima pengaturan yang ada pada SiapPakai untuk menentukan validasi yang digunakan sebagai batasan wilayah di database gabungan.

**Comment by andifahruddinakas** [comment]
gabung di issue https://github.com/OpenSID/OpenSID/issues/8589 saja
