### ISSUE TITLE
Bug/error: fress instal halaman website berantakan

### ISSUE THREAD

**Issue by ilhamwahyu-ni** [OpenSID/OpenSID#8596]
### Jelaskan error yg dialami

saya insttall ulang dari awal aplikasi opensid ini dan untuk tampilan halaman web berantakan..

### Cara untuk mereplikasi errornya

install dari awal

### Hasil yg diharapkan

rapi

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/48c79634-029b-4e1f-bdd9-9c65160e577d)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

terbaru

**Comment by rgrahardi** [comment]
Hasil Install di Local tidak ada masalah yg ditemukan, jika masih mengalami dapat dibawakan ke klinik OpenSID untuk kita replikasi bersama dengan Programmer pak @ilhamwahyu-ni 

![image](https://github.com/user-attachments/assets/1044f23f-5480-468f-b161-2de32903c3d3)
