### ISSUE TITLE
Bug/error: ubah menu bagian status menjadi tidak aktif  padahal status menu aktif

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8597]
### Jelaskan error yg dialami

![image](https://github.com/user-attachments/assets/37954d88-c26d-4fc0-994a-825794634ce7)

![image](https://github.com/user-attachments/assets/c3ea0a6f-22ac-424e-95e9-7322eadd8fc4)

![image](https://github.com/user-attachments/assets/de45b376-a7b6-40ea-84bd-f60bbcc38af0)

### Cara untuk mereplikasi errornya

1. Klik Admin Web
2. Klik Menu
3. Klik Ubah

### Hasil yg diharapkan

Sstatu di Ubah menu Sesuai dengan status Menu

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Versi 2410.0.2-premium

**Comment by pandigresik** [comment]
Sudah diperbaiki pada PR https://github.com/OpenSID/premium/pull/4176

**Comment by ariandii** [comment]
![image](https://github.com/user-attachments/assets/b93fd647-1b7f-49f6-9a65-3ce5554a3bfa)

pada saat klik ubah atau tambah. pilihan status di sisi atas hilang. (sesuai panah merah dan biru)

**Comment by pandigresik** [comment]
saya coba menggunakan branch bug-fix aman

https://github.com/user-attachments/assets/739ad03a-1b99-43b2-bdc0-b2a49b8bf0ed
