### ISSUE TITLE
Bug/error: Lampiran Model N6 tidak muncul

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8599]
### Jelaskan error yg dialami

Lampiran Model N6 tidak muncul di surat pengantar nikah bawaan sistem dan surat pengatar nikah desa

### Cara untuk mereplikasi errornya

1. Cetak Surat
2. Surat Pengatar Nikah 
3. Tinjau PDF

### Hasil yg diharapkan

Model N6 bisa di cetak dan tinjau PDF pengaturan surat dan Cetak surat

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/3c7a7094-1563-42fd-bef2-eaac90a06696)
![image](https://github.com/user-attachments/assets/fa54e1ee-a705-4aba-89b4-7004cb4e6153)

Lampiran terakhir sampia Model N5

![image](https://github.com/user-attachments/assets/ede42a2b-3f28-4351-8531-c848b2fdd9a1)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Versi 2410.0.2-premium

### Informasi tambahan

Laporan Desa Sukosari

**Comment by pandigresik** [comment]
Sudah diperbaiki pada PR https://github.com/OpenSID/premium/pull/4184
