### ISSUE TITLE
Bug: Usia Penduduk yang sudah meninggal masih ikut TAHUN BERJALAN

### ISSUE THREAD

**Issue by redjoel** [OpenSID/OpenSID#860]
Selamat sore,
Kami baru akan mengimplementasikan OPENSID beberapa waktu yang akan datang. Saat ini kami diberikan data Kependudukan Manual oleh Pemerintah Desa yang adalah data tahun 2014.
Dari data tersebut pasti sudah banyak yang lahir dan tidak sedikit yang sudah meninggal dunia. Lalu kemudian permasalahn muncul yaitu :
**Data Usia pada Penduduk yang kami ubah [Mati] pada status dasarnya, masih menunjukkan Usia orang tersebut pada tahun ini, bukan Usia ketika meninggal.**
Mohon diprioritaskan untuk penanganan ini karena ini cukup krusial :D 
Terima kasih

**Comment by eddieridwan** [comment]
Juga untuk penduduk yang statusnya [Hilang].

**Comment by eddieridwan** [comment]
Sudah diperbaiki dan sudah dicommit ke master.

**Comment by redjoel** [comment]
Thanks pak Eddieridwan
Bravo OpenSID
