### ISSUE TITLE
Bug/error: Tambah Informasi Publik pilih Tipe Dokumen URL tidak bisa di Simpan

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8601]
### Jelaskan error yg dialami

Tambah Informasi Publik pilih Tipe Dokumen URL tidak bisa di Simpan

### Cara untuk mereplikasi errornya

1. Modul Sekretariat
2. Menu Informasi Publik
3. Tambah 
4. pilih Tipe Dokumen URL

### Hasil yg diharapkan

dapat menyimpan informasi publik tipe dokumen url

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/fa256f1a-e3ce-4d01-b3a2-4e2d524f5963)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Versi 2410.0.2-premium

**Comment by pandigresik** [comment]
Sudah diperbaiki pada PR https://github.com/OpenSID/premium/pull/4183
