### ISSUE TITLE
Bug/error: TIDAK BISA RUBAH SUB MENU KEDUA

### ISSUE THREAD

**Issue by pujocahyono** [OpenSID/OpenSID#8607]
### Jelaskan error yg dialami

TIDAK DAPAT MELAKUKAN PERUBAHAN NAMA SUB MENU KEDUA

### Cara untuk mereplikasi errornya

1. ADMIN WEB
2. MENU
3. LAKUKAN UBAH PADA SUB MENU KEDUA

### Hasil yg diharapkan

NORMAL KEMBALI

### Tangkapan layar dan log error

![Cuplikan layar 2024-10-18 100227](https://github.com/user-attachments/assets/c52b8121-b6e2-4967-b368-b5d019355d91)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2410.0.1-premium

**Comment by andifahruddinakas** [comment]
pak @pujocahyono, sudah diperbaiki melalui issue https://github.com/OpenSID/OpenSID/issues/8597. Bisa update ke versi 2410.0.2

**Comment by pujocahyono** [comment]
> pak @pujocahyono, sudah diperbaiki melalui issue #8597. Bisa update ke versi 2410.0.2

untuk menu dan sub menu pertama bisa pak di v2410.0.2, untuk sub menu kedua saya coba muncul notifikasi gagal.
mau coba di berputar versinya masih v2410.0.1

**Comment by pujocahyono** [comment]
![Cuplikan layar 2024-10-18 104732](https://github.com/user-attachments/assets/6adaaedf-9165-4cb1-8288-222d565a24e2)
![Cuplikan layar 2024-10-18 104759](https://github.com/user-attachments/assets/6802d497-0519-420d-b50e-6051b659a5c7)

**Comment by ariandii** [comment]
https://t.me/c/1238304761/1/69927
