### ISSUE TITLE
Penambahan Menu SisKeuDes

### ISSUE THREAD

**Issue by SahlaniAfnan** [OpenSID/OpenSID#861]
Mudah2an Bermanfaat...

**Comment by eddieridwan** [comment]
@SahlaniAfnan tidak bermanfaat kalau anda membuat issue tanpa perincian. Issue yg bermanfaat adalah yang menjelaskan secara rinci apa yang diperlukan. Ini pekerjaan yang besar, dan sudah dibahas panjang lebar di http://bit.ly/OpenSKD.

Kalau anda mau membantu silakan bergabung di forum teknis di https://opensid.slack.com. Ada ruangan khusus di situ untuk membahas OpenSKD. Kirim email untuk diinvite -- tapi hanya kalau anda akan ikut aktif kontribusi informasi, pikiran, rancangan, dsbnya.

**Comment by SahlaniAfnan** [comment]
oke matur suwun Kang @eddieridwan  , Mungkin begitu maksud saya.. yaitu mengarah ke RPJMDES, RKP, dan APBDES. Ketransfaransian dari pihak desa masalah "keuangan" untuk sementara saya kira untuk opsi 2 dan 3 pada konsep Open SKD hmmm no comment deh....
