### ISSUE TITLE
Bug/error: Hapus dusun gagal

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8610]
### Jelaskan error yg dialami

Terdapat Pemberitahuan saat hapus Dusun masih belum valid ketika penduduk dan keluarga yang di klik data tersebut kosong

pada informasi jumlah penduduk dan keluarga pada dusun tersebut sudah 0 

Hanya terjadi di https://kurniakotosalak.desa.id/

### Cara untuk mereplikasi errornya

1. Pilih Dusun
2. Hapus Dusun

### Hasil yg diharapkan

Dapat menghapus Dusun E karena tidak digunakan

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/7e6f54f2-5721-486f-be4e-39e1cc161c75)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Versi 2410.0.2-premium

**Comment by andifahruddinakas** [comment]
Mas @rgrahardi , bisa sertakan databasenya

**Comment by rgrahardi** [comment]
mas @andifahruddinakas sudah saya lampirkan

**Comment by pandigresik** [comment]
Ketika ada kejanggalan maka usahakan untuk melakukan pengecekan pada halaman periksa untuk memastikan bahwa data sudah bebas dari masalah
