### ISSUE TITLE
Bug/error: TTD ada tulisan PJ nya

### ISSUE THREAD

**Issue by ilhamwahyu-ni** [OpenSID/OpenSID#8612]
### Jelaskan error yg dialami

buat surat  kemudian saat pratinjau ada tulisan PJ  wali nagari,,

saat ini kami masih memiliki wali  nagari dan belum ada jabatan peganti wali nagari..

![image](https://github.com/user-attachments/assets/6a4f2a0b-8524-40d1-b7b1-7aad8559d9f8)

### Cara untuk mereplikasi errornya

buat surat biodata penduduk bawaan sistim

### Hasil yg diharapkan

normal

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/3e3f646b-b4e9-45da-a963-8e9239481334)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

 24010.0.2

**Comment by andifahruddinakas** [comment]
pak @ilhamwahyu-ni, bisa dicek bagian status jabatan. Jika masih aktif (bukan Pj), maka bagian tsb tidak diaktifkan.
![image](https://github.com/user-attachments/assets/588be564-c598-41f3-ae42-dc465ac7f57c)
