### ISSUE TITLE
Teknis: Pemberitahuan Hapus dusun

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8613]
### Jelaskan error yg dialami

Pemberitahuan hapus dusun diganti tidak lagi mengarahkan untuk hapus penduduk, tetapi mengintruksikan pindah wilayah kolektif

### Cara untuk mereplikasi errornya

1. Klik Info Desa
2. Klik Wilayah Administrasi
3. Hapus Dusun, RT dan RW

### Hasil yg diharapkan

Ketika Hapus Dusun, RT, RW Pemberitahuan Pindah Wilayah Kolektif, tidak lagi hapus penduduk pada dusun tersebut.

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/1b67f369-b171-4dcd-94d1-2a57c4ccacad)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Versi 2410.0.2-premium

**Comment by andifahruddinakas** [comment]
mas @rgrahardi, silahkan lanjut membuat panduannya untuk memindahkan alamat wilayah penduduk/keluarga secara kolektif.
