### ISSUE TITLE
Bug/error: Menu DDK menapilkan semua data Keluarga Database Gabungan

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8614]
### Jelaskan error yg dialami

Menu DDK menapilkan semua data Keluarga Database Gabungan

### Cara untuk mereplikasi errornya

1. Klik Modul Prodeskel
2. Klik DDK

### Hasil yg diharapkan

data DDK hanya menampikan data Keluarga pada Desa Batungsel saja.

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/b7471c2b-af55-4c73-ad82-82c9f0a185c7)
![image](https://github.com/user-attachments/assets/d4a9b75e-e118-4404-9639-d0e6f8b4dd39)
![image](https://github.com/user-attachments/assets/0341f7b2-0381-47a9-8107-fa4cadf096da)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

OpenSID v2410.0.2-premium

### Informasi tambahan

Laporan Desa Batungsel

**Comment by andifahruddinakas** [comment]
Duplicate of https://github.com/OpenSID/modul-prodeskel/issues/365
