### ISSUE TITLE
Bug/error: data penerima bantuan sample tampil pada laman dashbord

### ISSUE THREAD

**Issue by typevant** [OpenSID/OpenSID#8617]
### Jelaskan error yg dialami

Penduduk penerima bantuan pada sample, tampil pada laman dashbord website
![image](https://github.com/user-attachments/assets/c204a835-2692-4b13-9f8b-88838e7d335a)
![image](https://github.com/user-attachments/assets/36bda8b8-8df3-42e4-90b2-57d1449232ef)

### Cara untuk mereplikasi errornya

Pergi ke halaman statistik bantuan, lihat daftar bantuan penduduk

### Hasil yg diharapkan

data sample untuk isian penerima bantuan tidak tampil pada laman dashbord website desa

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/69cb73f2-2e23-480e-a7fc-2754d11cfacb)

### Rilis Versi OpenSID

Rilis Umum

### Versi OpenSID

v2411.0.0

### Tema Yang Digunakan

DeNava

**Comment by andifahruddinakas** [comment]
pak @typevant, jika menggunakan contoh data awal (versi yg lama), sebaiknya dihapus terlebih dahulu.
