### ISSUE TITLE
Bug/error: DataTables warning: table id=tabeldata - Ajax error.

### ISSUE THREAD

**Issue by tamatea88** [OpenSID/OpenSID#8618]
### Jelaskan error yg dialami

Saat mengakses Buku peraturan desa dan buku keputusan pemerintah desa muncul error 

DataTables warning: table id=tabeldata - Ajax error. For more information about this error, please see http://datatables.net/tn/7

### Cara untuk mereplikasi errornya

klik 
Buku Administrasi Umum

### Hasil yg diharapkan

tidak terjadi error saat mengkases menu tersebut

### Tangkapan layar dan log error

![datatables2](https://github.com/user-attachments/assets/d67273ea-c941-4e6a-8c9c-edf7db00b79e)

### Rilis Versi OpenSID

Rilis Umum

### Versi OpenSID

v2410.0.0

### Tema Yang Digunakan

Batuah 24.08

**Comment by tamatea88** [comment]
error sudah terkondisikan
dengan merubah file htaccess.txt menjadi .htaccess

**Comment by rgrahardi** [comment]
baik pak @tamatea88 untuk issuenya kita close pak karena sudah terkondisikan

**Comment by kiraware** [comment]
> error sudah terkondisikan dengan merubah file htaccess.txt menjadi .htaccess

Saya mencoba rename file nya di localhost, tapi hasilnya malah begini

![image](https://github.com/user-attachments/assets/3b3f39db-1218-46da-904d-cd288a814f7d)

Saya coba cari tahu, kemungkinan karena Apache di Laragon tidak memperbolehkan penggunaan file `.htaccess`. untuk memperbaikinya kita perlu konfigurasi Apache di Laragon dengan edit file `httpd.conf`.

Cari teks berikut di file `httpd.conf`

```
<Directory "C:/laragon/www">
```

Kemudian tambahkan `AllowOverride All` menjadi ini

```conf
<Directory "C:/laragon/www">
    AllowOverride All
    # Direktif lainnya
</Directory>
```

**Namun hal ini tetap saja menimbulkan error seperti sebelumnya**. Jadi menurut saya dengan rename file `htaccess.txt` menjadi `.htaccess` bukan solusinya. Saya menggunakan OpenSID 2501.0.0. Mohon issue nya dibuka kembail @rgrahardi
