### ISSUE TITLE
Bug/error: hapus produk error

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8619]
### Jelaskan error yg dialami

Bug saat hapus produk di lapak, jika hapus produk tanpa gambar akan muncul error.
Jika produk ada gambarnya, hapus produk berjalan normal.

### Cara untuk mereplikasi errornya

1. Lapak
2. Hapus Produk

### Hasil yg diharapkan

Solusi: 
1. user diwajibkan utk upload foto saat tambah produk
2. Munculkan notifikasi gagal hapus karena saat hapus produk tanpa foto

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/a8bd175e-1ac1-456a-9bc7-ed95077e5c06)
![image](https://github.com/user-attachments/assets/5d928a83-07a7-4645-a7d0-3b18d8c10d0c)

Hapus Produk yang tidak punya gambar produk

![image](https://github.com/user-attachments/assets/0db1d8fd-869b-489c-bff7-5a14b87d15a1)

![image](https://github.com/user-attachments/assets/9052bd61-1cf9-4648-b81f-f58585dbc300)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Versi 2410.0.2-premium

### Informasi tambahan

Laporan Desa Sinduwati

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui commit https://github.com/OpenSID/premium/commit/6667577534d380215cdc53f1e365b72b334643ec
