### ISSUE TITLE
Bug: kesalahan Pengetikan di f-2.29 Lampiran Kematian

### ISSUE THREAD

**Issue by SetiawanRidwan** [OpenSID/OpenSID#862]
di alamat terdapat salah ketik, seharusna Desa/Kelurahan di Opensid tertulis Desa/Keluarga
![lampiran surat](https://user-images.githubusercontent.com/20785500/37582873-748ce942-2b81-11e8-8263-9dc71543efaf.png)

**Comment by eddieridwan** [comment]
Terima kasih telah melaporkan. 

Perbaikan sudah dicommit ke master.
Bisa diunduh di versi pra-rilis.
