### ISSUE TITLE
Bug/error: Tombol Hapus pada Daftar persyaratan surat tidak Berfungsi "404"

### ISSUE THREAD

**Issue by ilhamwahyu-ni** [OpenSID/OpenSID#8620]
### Jelaskan error yg dialami

-

### Cara untuk mereplikasi errornya

![image](https://github.com/user-attachments/assets/8d826359-4a4f-44ac-bc79-29c5aab72b6a)

### Hasil yg diharapkan

normal

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/f7f0a496-6ec1-42d5-9c3b-beca078d2692)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

bug fix

**Comment by andifahruddinakas** [comment]
Sudah disesuaikan melalui commit https://github.com/OpenSID/premium/commit/ab37ca5ed5ee8492d3c08879890b42de6c8cd169
