### ISSUE TITLE
Update tinymce 6 ke 7

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#8623]
Infromasi terkait https://www.tiny.cloud/docs/tinymce/latest/migration-from-6x/

Pembahasan : 
https://github.com/OpenSID/OpenSID/security/dependabot/15
https://github.com/OpenSID/OpenSID/security/dependabot/14

**Comment by agung2001** [comment]
Terkait https://github.com/OpenSID/OpenSID/issues/8626 bisa dilakukan sambil memindah file tinymce ke directory `assets/lib/js`
