### ISSUE TITLE
Bug/error: Data Peserta Penerima Bantuan tidak tampil

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8629]
### Jelaskan error yg dialami

- Data Peserta Penerima Bantuan Tidak tampil, Tambah Peserta Data Bantuan juga tidak tampil
- Migrasi dan halaman Periksa aman

### Cara untuk mereplikasi errornya

1. Bantuan
2. Rincian Bantuan

### Hasil yg diharapkan

data bantuan berhasil tampil

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/1a84b899-a84e-4ed4-a8de-0fb7269a6314)
![image](https://github.com/user-attachments/assets/e57b79a1-6f79-45ca-8360-0f08a5bb797b)
![image](https://github.com/user-attachments/assets/8860d063-9c6d-4277-910f-e4823eaae285)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

OpenSID v2410.0.2-premium

### Informasi tambahan

Terjadi Pada Desa Sumbersuko, Data Bantuan dibutuhkan untuk mendata peserta bantuan.

**Comment by andifahruddinakas** [comment]
Duplicate of https://github.com/OpenSID/OpenSID/issues/8630

**Comment by rgrahardi** [comment]
Hasil Penelusuran Programmer data bantuan tampil, 

dari database yg dikirim sy cek tampil dengan benar menggunakan versi terbaru 2410.1.0

![image](https://github.com/user-attachments/assets/229807f1-8023-49e6-bbe2-b6aed2a8d13a)
