### ISSUE TITLE
Alamat tidak muncul, setelah Tambah KK

### ISSUE THREAD

**Issue by matrix2110** [OpenSID/OpenSID#863]
Setelah tambah KK, alamat tidak muncul
![alamat](https://user-images.githubusercontent.com/35619997/37635704-e248cfce-2c2f-11e8-8fed-71d4b6e6839c.PNG)

**Comment by xnuser** [comment]
Alamat yang muncul disana adalah alamat yang di isi saat pengisian KK baru (+ Tambah KK Baru) pak @matrix2110 
![screenshot_17](https://user-images.githubusercontent.com/36754277/37875791-1b326b14-306e-11e8-8b4c-3753fae2b16f.png)

**Comment by Nurhidayat29** [comment]
issues sudah terselesaikan di OpenSID terbaru
