### ISSUE TITLE
Bug/error: Data Peserta Penerima Bantuan tidak tampil

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8630]
### Jelaskan error yg dialami

Data Peserta Penerima Bantuan tidak tampil, di replikasi berputar aman

### Cara untuk mereplikasi errornya

1. Bantuan
2. Rincian Bantuan

### Hasil yg diharapkan

Data Pesertam bantuan tampil

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/860d95f5-0e7c-4d0d-920b-7bd5a3c0b135)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

OpenSID v2410.0.2-premium

### Informasi tambahan

Terjadi di Desa Sukoharjo3

**Comment by Sukoharjo3** [comment]
![Screenshot_20241023-185807](https://github.com/user-attachments/assets/3d378660-cb39-4e61-960d-da92e7297812)
di halaman periksa muncul ini, di klik perbaiki data tetap seperti itu tidak ada perubahan 
sama seperti isu ini
https://github.com/OpenSID/OpenSID/issues/8569

**Comment by eddieridwan** [comment]
**@rgrahardi kalau terjadi hanya di desa ybs, SELALU sediakan datanya atau akses ke datanya kepada programmer.** 

Catatan: tidak di issue, karena bersifat publik. @andifahruddinakas @vickyrolanda rancang prosedur penyampaian data atau akses data secara aman dan konsisten.

**Comment by andifahruddinakas** [comment]
> **@rgrahardi kalau terjadi hanya di desa ybs, SELALU sediakan datanya atau akses ke datanya kepada programmer.**
> 
> Catatan: tidak di issue, karena bersifat publik. @andifahruddinakas @vickyrolanda rancang prosedur penyampaian data atau akses data secara aman dan konsisten.

Sudah ada prosedurnya dan selalu diingatkan terkait issue yg memerlukan data.

**Comment by rgrahardi** [comment]
Database Terlampir

**Comment by andifahruddinakas** [comment]
mas @rgrahardi, @Sukoharjo3, dari database yg dikirim sy cek tampil dengan benar menggunakan versi terbaru 2410.1.0

<img width="960" alt="image" src="https://github.com/user-attachments/assets/f697b722-eebf-4c71-9966-976898b5a837">

**Comment by Sukoharjo3** [comment]
> mas @rgrahardi, @Sukoharjo3, dari database yg dikirim sy cek tampil dengan benar menggunakan versi terbaru 2410.1.0
> 
> <img alt="image" width="960" src="https://private-user-images.githubusercontent.com/57283157/379523652-f697b722-eebf-4c71-9966-976898b5a837.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3MzkwMDEsIm5iZiI6MTcyOTczODcwMSwicGF0aCI6Ii81NzI4MzE1Ny8zNzk1MjM2NTItZjY5N2I3MjItZWViZi00YzcxLTk5NjYtOTc2ODk4YjVhODM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI0VDAyNTgyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiZGUxNjBkMzg4N2YzZWZmYTEzYTNjOGViMzYxZTg4YzhjMTdkY2JjMzBmZmMyNmIyMDg5MzE3YTVjMmE3ZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.NoFHesSIEGvEQfwkDtGt6hrufrEruURTkVGTbxmZG3U">

kemungkinan karna server hosting tidak support pak, setelah sy cek jenis tabel utf8 tidak tersedia
![Screenshot 2024-10-24 095157](https://github.com/user-attachments/assets/a90b3f36-7d30-4503-8774-ae1da5722deb)

**Comment by rgrahardi** [comment]
dapat melaporkan ke penyedia hosting pak @Sukoharjo3, saat ini issue kita tutup.

**Comment by rgrahardi** [comment]
Ijin pak @Sukoharjo3 hasil penelusuran programmer dari sisi database aman, mohon di berikan akses panelnya pak untuk bisa di periksa lansung oleh programmer pak, terimakasih

**Comment by apidong** [comment]
> Ijin pak @Sukoharjo3 hasil penelusuran programmer dari sisi database aman, mohon di berikan akses panelnya pak untuk bisa di periksa lansung oleh programmer pak, terimakasih

untuk versi mariadb 10.6 ke atas, utf8_general_ci sudah tidak didukung.
berikut ini hasil dari chat GBT
https://chatgpt.com/share/671eccca-4d5c-800d-9390-b841bac98596

**Comment by pandigresik** [comment]
Mungkin bisa dicoba menampilkan data peserta bantuan tanpa menggunakan join table, gunakan relasi dari eloquent saja

**Comment by rgrahardi** [comment]
bagaimana pak @Sukoharjo3 info dari penyedia hosting ? 

Kami menyarankan untuk menggunakan Paket Layanan SiapPakai pak agar tidak dipusingkan dengan hal hal teknikal seperti ini pak.

**Comment by andifahruddinakas** [comment]
Duplicate of https://github.com/OpenSID/OpenSID/issues/8629

**Comment by Sukoharjo3** [comment]
> > Ijin pak @Sukoharjo3 hasil penelusuran programmer dari sisi database aman, mohon di berikan akses panelnya pak untuk bisa di periksa lansung oleh programmer pak, terimakasih
> 
> untuk versi mariadb 10.6 ke atas, utf8_general_ci sudah tidak didukung. berikut ini hasil dari chat GBT https://chatgpt.com/share/671eccca-4d5c-800d-9390-b841bac98596

ya pak betul, sy tanya ke penyedia hosting justru yg dipakai sudah versi terbaru
yg digunakan opensid justru model lama sehingga tidak ketemu
banyak dilaporkan berulang yg mengalami kejadian seperti ini berarti kan para penyedia hosting nya mulai upgrade, sistem kita yg blm upgrade

**Comment by binrosyad** [comment]
maaf pak, saya pikir bukan karena faktor utf8_general_ci atau utf8mb3_general_ci, karena pada versi-versi sebelumnya meski kita menggunakan utf8mb3_general_ci semua lancar-lancar aja, dan perlu diketahui pada desa-desa yg sudah melakukan pengisian data Bantuan pada versi sebelumnya(versi sebelum masalah ini muncul) datanya tetap muncul atau tampil, hanya tidak dapat memasukkan data baru.
Harapan saya tolong dikaji ulang mengenai masalah ini

**Comment by rgrahardi** [comment]
Hasil Penelusuran dengan pengguna Desa Babang terdapat ID yang seperti ini mas @andifahruddinakas mas @pandigresik mas @apidong mohon petunjuknya 

Issue juga terjadi di Desa Babang, Desa Melinggih, Desa Sumber Suko Gempol, sudah saya sampaikan database pengguna sudah dites di server OpenDesa dan Bantuan Aman
![image](https://github.com/user-attachments/assets/fdb44c91-780a-4d03-9e28-5b6abcdd64e8)

**Comment by andifahruddinakas** [comment]
> Hasil Penelusuran dengan pengguna Desa Babang terdapat ID yang seperti ini mas @andifahruddinakas mas @pandigresik mas @apidong mohon petunjuknya
> 
> Issue juga terjadi di Desa Babang, Desa Melinggih, Desa Sumber Suko Gempol, sudah saya sampaikan database pengguna sudah dites di server OpenDesa dan Bantuan Aman ![image](https://private-user-images.githubusercontent.com/55429781/383068883-fdb44c91-780a-4d03-9e28-5b6abcdd64e8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3OTY3MzEsIm5iZiI6MTczMDc5NjQzMSwicGF0aCI6Ii81NTQyOTc4MS8zODMwNjg4ODMtZmRiNDRjOTEtNzgwYS00ZDAzLTllMjgtNWI2YWJjZGQ2NGU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA1VDA4NDcxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWViMjM5NDAxNWY2ZDRhZjJlZGVjZmQzNTE4OThhZGUzYTdmOWM0NjliZmI2NjA5OWQ0OWMwZDg4OTlkNWY4MjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.17AzzqYnRgQRXon4s40yXwiV1tyWMsmD787DdTWIfJQ)

yg di permasalahkan dan diberi contoh pada issue
![image](https://github.com/user-attachments/assets/b9163641-57ba-48fa-b012-4029fe857d6c)

apa hubungannya dengan data yg ditampilkan di awal issue. untuk id bisa saja besar apalagi menggunakan database gabungan.

**Comment by rgrahardi** [comment]
> Mungkin bisa dicoba menampilkan data peserta bantuan tanpa menggunakan join table, gunakan relasi dari eloquent saja

cc mas @andifahruddinakas

**Comment by rgrahardi** [comment]
Issuenya kita tutup karena permasalahan bukan di Aplikasi OpenSID

Solusi silahkan centang bagian yang di lingkari

![image](https://github.com/user-attachments/assets/f8c130bf-3606-4591-bcde-df59991952fa)


Peserta Bantuan berhasil tampil kembali

![image](https://github.com/user-attachments/assets/ebf9c562-93ce-4e40-822c-7564f3858ea1)
