### ISSUE TITLE
jumlah kk tidak sama yang tampil di halaman admin dan di website

### ISSUE THREAD

**Issue by mranca** [OpenSID/OpenSID#8631]
### Jelaskan error yg dialami

terjadi selisih jumlah data kepala keluarga yang tampil di halama admin dan di website

### Cara untuk mereplikasi errornya

1. masuk admin
2. klik kepala keluarga
3. filter data berdasarkan dusun 
4. cek di website jumlah masing-masing perdusun

### Hasil yg diharapkan

.

### Tangkapan layar dan log error

jumlah data yang muncul pada halaman website
![Website-Resmi-Desa-Tongke-Tongke-Kecamatan-Sinjai-Timur-Kabupaten-Sinjai-10-23-2024_08_41_PM](https://github.com/user-attachments/assets/a021460b-4192-4b6e-9ee2-484d6c6d0f6f)

jumlah data yang muncul pada halama admin
![Sistem-Informasi-Desa-Tongke-Tongke-10-23-2024_08_45_PM](https://github.com/user-attachments/assets/72b8077b-8b2c-4970-a333-098d033e8ef1)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

terbaru

### Tema Yang Digunakan

pusako

### Informasi tambahan

saya sudah menggunakan tema bawaan namun hasilnya tetap sama jumlah masih selisih

**Comment by andifahruddinakas** [comment]
pak @mranca, terlihat selsihnya karena ada data keluarga yang nik_kepalanya kosong.
![image](https://github.com/user-attachments/assets/4a0d6d68-c5f8-4cd1-815e-78b5053b1fa7)

**Comment by andifahruddinakas** [comment]
Database terlampir

**Comment by mranca** [comment]
@andifahruddinakas , saya close saja issuenya bung saya sudah cek di halaman periksa dan sudah normal
