### ISSUE TITLE
Bug/error: Kolom Jenis Kelompok  Akte kelahiran rentangnya terlalu Jauh "UMUR 75 S/D 99999 TAHUN"

### ISSUE THREAD

**Issue by ilhamwahyu-ni** [OpenSID/OpenSID#8637]
### Jelaskan error yg dialami

-

### Cara untuk mereplikasi errornya

Menu Statistik

### Hasil yg diharapkan

Sama Seperti Rentang Umur

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/2ae58392-22b8-4b42-be90-8d80e601789c)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

rilis terbaru

**Comment by ilhamwahyu-ni** [comment]
tambahan...

![image](https://github.com/user-attachments/assets/ade5b411-723a-4dbf-b4ad-7fc36b91da53)

![image](https://github.com/user-attachments/assets/3d271bd4-fe42-445e-9021-de7b129ba4fc)

**Comment by andifahruddinakas** [comment]
Solusi : 
- Batasi maksimal 150 tahun saja.

pak @ilhamwahyu-ni, apada cukup sampai 150 tahun?

**Comment by ilhamwahyu-ni** [comment]
Sepertinya cukup pak..

**Comment by ilhamwahyu-ni** [comment]
![image](https://github.com/user-attachments/assets/22cab8c8-74b9-4239-a27d-2fec5415f669)

masih belum fix,,,,
