### ISSUE TITLE
Permintaan fitur: Generate Masal PIN Warga Untuk Layanan Mandiri

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8639]
### Apa kekurangan yg ingin diatasi?

belum ada fitur generate PIN warga untuk Layanan Mandiri, Jumlah Data penduduk pada Desa mencapai Ribuan Penduduk sehingga di usulkan untuk membuat fitur generate masal PIN Warga

### Jelaskan solusi yg diinginkan

membuat fitur generate masal PIN warga untuk Layanan Mandiri

![image](https://github.com/user-attachments/assets/645130df-684c-4cdf-9902-8712e9bb5d82)

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

Versi 24011.0.1-premium

### Informasi tambahan

Usulan Desa Munduk Temu

**Comment by pandigresik** [comment]
ketika sudah digenerate, bagaimana metode distribusi pin ke masing2 warga ?

**Comment by ariandii** [comment]
==
hal ini sebaiknya tidak diterapkan, karena yang membutuhlan PIN adalah warga yang mampu menggunakan Layanan Mandiri.

bukan semua warga atau bahkan bayi yang ada di database ingin/bisa menggunakan Layanan Mandiri.

===
jika pun mau diterapkan,
hindari generate seluruh warga menggunakan PIN yang sama.

bisa berakibat dilakukan login oleh orang yang tidak bertanggungjawab ketika PIN sama.

==
dan ketika generate PIN berbeda, tentu sulit pula mendistribusikannya.

**Comment by andifahruddinakas** [comment]
mas @rgrahardi, sudah pernah dibahas pada  issue https://github.com/OpenSID/OpenSID/issues/4015
