### ISSUE TITLE
Bug/error: Gagal mengganti latar halaman kehadiran

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#8640]
### Jelaskan error yg dialami

ketika pilih gambar dan simpan, gambar latar pada halaman kehadiran tidak berubah.

### Cara untuk mereplikasi errornya

1. login siteman
2. masuk salah satu menu kehadiran
3. klik icon gear pojok kanan atas
4. pilih gambar latar
5. simpan

lihat hasil pada halaman kehadiran

### Hasil yg diharapkan

seharusnya normal kembali.

dan berikan hasil foto latar yang diunggah pada pengaturan kehadiran agar yakin foto sudah terupload.

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2410.1.0

**Comment by andifahruddinakas** [comment]
Sudah disesuaikan melalui commit https://github.com/OpenSID/premium/commit/209a2c4a308d3603f52fd3100a82d6270e701a6b

Untuk melihat hasil perubahan bisa dilihat pada tombol liat (mata)
![image](https://github.com/user-attachments/assets/23a5778a-5a4b-429e-a1c9-ad86cc061f31)

**Comment by ariandii** [comment]
juga terjadi tidak bisa ubah gambar latar website dan latar login admin di pengaturan aplikasi.

**Comment by andifahruddinakas** [comment]
> Sudah disesuaikan melalui commit [OpenSID/premium@209a2c4](https://github.com/OpenSID/premium/commit/209a2c4a308d3603f52fd3100a82d6270e701a6b)
> 
> Untuk melihat hasil perubahan bisa dilihat pada tombol liat (mata) ![image](https://private-user-images.githubusercontent.com/57283157/380587700-23a5778a-5a4b-429e-a1c9-ad86cc061f31.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxMzI5OTcsIm5iZiI6MTczMDEzMjY5NywicGF0aCI6Ii81NzI4MzE1Ny8zODA1ODc3MDAtMjNhNTc3OGEtNWE0Yi00MjllLWExYzktYWQ4NmNjMDYxZjMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI4VDE2MjQ1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjMjcxNjdlMjNmY2IxMzVkMmYyOTNmZjg0YjE4ZmEzMmJhNzFlMWM3NGFmOTgwNzAyZGExYzY5NDZhNWZmMGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.PPXYO6ksQoUDt_AcCcH2mIUhAhVKNF-GXnY1ZpCuTW4)

Sudah disesuaikan di commit ini karena menggunakan fungsi yang sama.

**Comment by ariandii** [comment]
tes di berputar versi hari ini pun, masih tidak bisa merubah gambar latar halaman kehadiran

**Comment by ariandii** [comment]
https://berputar.opendesa.id/kehadiran/masuk

sedangkan di klik tombol mata pada pengaturan latar kehadiran sudah berhasil upload
https://berputar.opendesa.id/desa/pengaturan/siteman/images/q5FBQ_1732859379latar_kehadiran.jpg?v5195d54aa8d81e23296c77c7f52254c1

**Comment by andifahruddinakas** [comment]
mas @agungsugiarto, pada bagian admin sudah sesuai. bisa disesuaikan pada halaman kehadiran agar background tampil sesuai dengan yang diunggah.

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/4310

pak @ariandii, bisa dicek kembali
