### ISSUE TITLE
Bug/error: Info Login belum menampilkan Urutan Login Terakhir

### ISSUE THREAD

**Issue by ariandii** [OpenSID/OpenSID#8641]
### Jelaskan error yg dialami

ketika membuka Log Login. baris awal terlihat waktu acak.

### Cara untuk mereplikasi errornya

1. Login siteman
2. Klik menu Pengaturan -> Info Sistem
3. klik tab Log Login

perhatikan hasil pada kolom tanggal akses di setiap barisnya.

### Hasil yg diharapkan

urutan nomor 1, teratas, seharusnya waktu login terakhir saat ini.

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2410

**Comment by andifahruddinakas** [comment]
Sudah disesuaikan melalui commit https://github.com/OpenSID/premium/commit/8b3419e20ee29aa4e138a238dd5f4aed61e9ac50
