### ISSUE TITLE
Teknis : Surat Sistem Kelahiran dan Kematian belum otomatis menggunakan Lampiran terbaru

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8644]
### Jelaskan error yg dialami

Surat Sistem Kelahiran dan Kematian belum otomatis menggunakan Lampiran terbaru yaitu lampiran  F-2.01-Kelahiran dan F-2.01-Kematian.

Lampiran F-2.01 jikat tidak digunakan hapus saja 

### Cara untuk mereplikasi errornya

![image](https://github.com/user-attachments/assets/9f4d358e-ff9b-4d1b-a89e-54ac84281ac2)

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Versi 2410.1.0-premium

### Informasi tambahan

-

**Comment by andifahruddinakas** [comment]
mas @rgrahardi, surat bawaan otomatis diperbarui. bisa cek di
![image](https://github.com/user-attachments/assets/6ab986e3-a2cc-4df5-ac85-aeefebb86cf9)
https://berputar.opendesa.id/surat_master

Jika masih belum sesuai, bisa jalankan semua migrasi.

**Comment by rgrahardi** [comment]
Baik mas @andifahruddinakas 
![image](https://github.com/user-attachments/assets/3afcd39a-8d94-4c45-9727-ed7afb216823)
