### ISSUE TITLE
Bug/error: Badge/flag pada Kolom data tidak center (diluar kolom)

### ISSUE THREAD

**Issue by ilhamwahyu-ni** [OpenSID/OpenSID#8649]
### Jelaskan error yg dialami

-

### Cara untuk mereplikasi errornya

info login

### Hasil yg diharapkan

normal

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/bc919b4a-32dc-4023-82a2-bf54b35808c8)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

bux fix

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui commit https://github.com/OpenSID/premium/commit/b34716cf4e4fcc655523258ed2871bd05f518eb0
