### ISSUE TITLE
Bug/error: Tidak bisa hapus kategori lembaga

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8652]
### Jelaskan error yg dialami

Tidak bisa hapus kategori lembaga, lembaga yg menggunakan kategori tersebut sudah di hapus, tetapi kategori nya tetap tidak bisa dihapus

### Cara untuk mereplikasi errornya

1. Info Desa
2. Lembaga Desa
3. Kategori
4. Hapus Kategori 

### Hasil yg diharapkan

dapat menghapus kategori lembaga

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/0dcbac88-a243-445f-a4ed-6c64968c630c)

![image](https://github.com/user-attachments/assets/101c375f-8c31-4258-897b-3ec6d1ebdd66)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Versi 2410.1.0-premium

### Informasi tambahan

Laporan Desa Lalang Linggah
Telegram @BhujaAsmika

**Comment by pandigresik** [comment]
dari gambar terlihat masih ada 1 lembaga pada kategori tersebut, bisa dicek di lembaga dengan menghilangkan filter status, secara default menampilkan lembaga dengan status aktif

**Comment by rgrahardi** [comment]
mas @pandigresik tetap tidak tampil mas Afandi

![image](https://github.com/user-attachments/assets/374abd54-da6d-47bd-b002-f3873206c4cb)

**Comment by rgrahardi** [comment]
mas @andifahruddinakas mas @pandigresik database terlampir

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/4236
