### ISSUE TITLE
tidak bisa upload dokument penduduk

### ISSUE THREAD

**Issue by mranca** [OpenSID/OpenSID#8662]
### Jelaskan error yg dialami

tidak bisa upload dokument penduduk terjadi pesan error (please enter a value with a valid extension

### Cara untuk mereplikasi errornya

1. masuk admin
2. klik penduduk
3. pilih aksi salah satu penduduk 
4. klik upload dokument penduduk 

### Hasil yg diharapkan

.

### Tangkapan layar dan log error

![Sistem-Informasi-Desa-Kembang-Merta-11-01-2024_07_14_AM](https://github.com/user-attachments/assets/00b06fbc-3e77-4369-a70c-8e100b32d16d)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Terbaru

### Tema Yang Digunakan

.

### Informasi tambahan

.

**Comment by andifahruddinakas** [comment]
mas @mranca, file yg diunggah harus berformat gambar atau .pdf

bisa perhatikan nama file yg diunggah, terdapat nama extention nya
![image](https://github.com/user-attachments/assets/1338308e-de37-459a-8522-33e94a55931b)
