### ISSUE TITLE
Bug/error: favicon masih opendesa saat lihat documen

### ISSUE THREAD

**Issue by ilhamwahyu-ni** [OpenSID/OpenSID#8665]
### Jelaskan error yg dialami

saat ingin lihat documen, favicon seharusnya adalah logo kab/kota setempat.

### Cara untuk mereplikasi errornya

![image](https://github.com/user-attachments/assets/e6089834-32df-46ba-ac39-dcad01b823a9)

### Hasil yg diharapkan

favicon logo setempat

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/ac15fcdf-75f8-4f0e-b308-573b9f89283e)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

 2411.0.0

**Comment by andifahruddinakas** [comment]
untuk favicon pada pembacaan file tidak bisa diubah atau dialihkan untuk membaca favicon di folder lain. Otomatis membaca favicon default yg ada di root.

![image](https://github.com/user-attachments/assets/b06806d5-247f-4a99-98e3-5f95a3b0d2e4)

Alternatif lain yang bisa dilakukan agar bisa menggunakan favicon setiap kali preview yakni: membuat view sendiri, dan lakukan iframe untuk dokumen tsb.

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/4233
