### ISSUE TITLE
Bug/error: icon diluar kotak pada layanan pelanggan

### ISSUE THREAD

**Issue by ilhamwahyu-ni** [OpenSID/OpenSID#8666]
### Jelaskan error yg dialami

-

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

normal

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/8132dc7c-a5e1-499c-bee2-89c24c995550)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

 2411.0.0

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/OpenSID/issues/8666
