### ISSUE TITLE
Bug/error: Pengaturan Surat Untuk Cell Properties Height Hilang

### ISSUE THREAD

**Issue by luxmant354** [OpenSID/OpenSID#8669]
### Jelaskan error yg dialami

Pengaturan Surat Untuk Cell Properties Height Hilang, padahal pilihan tersebut sangat penting, karena hampir semua isian surat layanan menggunakan tabel, ketika pengaturan Height pada Cell Properties hilang, diberi jarak berapapun tidak ada efek, di tampilan seperti ada spasi heightnya, tapi ketika di pratinjau maka tidak sama / tidak ada efek sama sekali.
![Screenshot_4](https://github.com/user-attachments/assets/6ca7d052-5673-4d12-8ca6-bbce05fd22aa)

### Cara untuk mereplikasi errornya

Kembali Ke Versi 2410.0.2 surat berjalan dengan normal
![Screenshot_2](https://github.com/user-attachments/assets/8f2c2e45-45e2-447b-9728-fd80bed9bdc9)

### Hasil yg diharapkan

Kembalikan Pengaturan Surat Untuk Cell Properties Height yang Hilang kembali, sehingga bisa memberikan jarak atas dan bawah sesuai dengan yang diharapkan.

### Tangkapan layar dan log error

![Screenshot_3](https://github.com/user-attachments/assets/5b05d430-222f-47b7-9fc0-74bcdd0d6c19)

![Screenshot_5](https://github.com/user-attachments/assets/4c29ff26-83c5-4f1f-88ce-37b2c92c312d)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v2411.0.0-premium

**Comment by pandigresik** [comment]
https://github.com/tinymce/tinymce/blob/888c545780139fa4d74a31881c4c5600eafbe0dc/.changes/tinymce/7.0.0.md?plain=1#L21

- Remove the height field from the `table` plugin cell dialog. The `table` plugin row dialog now controls the row height by setting the height on the `tr` element, not the `td` elements. #TINY-10617
- Change table height resizing handling to remove heights from `td`/`th` elements and only apply to `tr` elements. #TINY-10589

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/4223

pak @luxmant354, untuk mengatur tinggi cell bisa dilakukan pada row nya.
![image](https://github.com/user-attachments/assets/1a1216ac-8017-4550-ac26-717fd434b349)

**Comment by luxmant354** [comment]
> Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/4223
> 
> pak @luxmant354, untuk mengatur tinggi cell bisa dilakukan pada row nya. ![image](https://private-user-images.githubusercontent.com/57283157/383394829-1a1216ac-8017-4550-ac26-717fd434b349.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4NjM5NDYsIm5iZiI6MTczMDg2MzY0NiwicGF0aCI6Ii81NzI4MzE1Ny8zODMzOTQ4MjktMWExMjE2YWMtODAxNy00NTUwLWFjMjYtNzE3ZmQ0MzRiMzQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA2VDAzMjcyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyOWEzMTc4ZjcxMGZjZDY3MzAzZGRhNGJmMmYyZGQwNDg2YjdmNjBiN2Y2YTM1NTVmNWIyNGUxNDlhODYzZjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.mU-iHHn68BOv1yF_VbqSTQ0OiKgTDxX0KwZTJDVK9Ko)

Sudah kami coba tidak ngefek mas (di pratinjau tetap tidak berubah) @andifahruddinakas
