### ISSUE TITLE
Bug/error: IFRAME DENGAN SUMBER GOOGLE DRIVE TIDAK TAMPIL

### ISSUE THREAD

**Issue by pujocahyono** [OpenSID/OpenSID#8670]
### Jelaskan error yg dialami

SAAT BUAT ARTIKEL DENGAN MENYISIPKAN IFRAME DENGAN SUMBER GOOGLE DRIVE HASILNYA TIDAK TAMPIL

### Cara untuk mereplikasi errornya

1. BUAT ARTIKEL
2. SISIPKAN IFRAME DENGAN SUMBER GOOGLE DRIVE

### Hasil yg diharapkan

NORMAL

### Tangkapan layar dan log error

DI VERSI TERBARU
![Cuplikan layar 2024-11-03 143948](https://github.com/user-attachments/assets/2fee66f7-b239-42d6-830a-fc2fce18294f)

VERSI SEBELUMNYA
![Cuplikan layar 2024-11-03 143939](https://github.com/user-attachments/assets/2c31dd10-a3c3-45bb-aa92-00c57de4ba98)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2411.0.0

**Comment by andifahruddinakas** [comment]
Terkait pembahasan https://www.tiny.cloud/docs/tinymce/latest/security/#sandbox-iframes

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/4224
