### ISSUE TITLE
Teknis : Tampilan Anjungan belum menggunakan versi yang simpel

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8671]
### Jelaskan error yg dialami

Tampilan Permohonan surat di Anjungan tidak menggunakan versi yang simpel

![image](https://github.com/user-attachments/assets/fd3244c7-7906-4966-8062-7b07038fa1d1)

### Cara untuk mereplikasi errornya

1. https://berputar.opendesa.id/anjungan-mandiri
2. Klik Tombol Layanan Mandiri
3. Masukan Nik dan Pin Warga

### Hasil yg diharapkan

Tampilan Surat pada Anjungan Mandiri menggunakan versi yang simpel

![image](https://github.com/user-attachments/assets/c4763848-4a09-4a83-9156-14560ce2cf9b)

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/a893c1d8-b80a-4c2b-bd5c-0b5ac23f0322)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Versi 2411.0.0-premium

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/4292
