### ISSUE TITLE
Bug/error: Judul dan Isi statikstik Penduduk cetak dan unduh tidak sesuai

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8675]
### Jelaskan error yg dialami

Judul dan Isi statikstik Penduduk cetak dan unduh tidak sesuai

### Cara untuk mereplikasi errornya

1. Klik Modul Statistik
2. Klik Menu Statistik Penduduk

### Hasil yg diharapkan

Sesuaikan Judul dan Isi Data Statisktik Kependudukan ketika di cetak dan di unduh

### Tangkapan layar dan log error

Contoh : 

![image](https://github.com/user-attachments/assets/03f64f5f-5266-435d-b341-48bddab59306)

![image](https://github.com/user-attachments/assets/ebcf766a-0c5b-41b8-bbc6-ab3d7b587a2c)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Versi 2411.0.0-premium

**Comment by eddieridwan** [comment]
@andifahruddinakas bukannya view/method untuk cetak dan unduh disatukan, tidak duplikasi?

**Comment by andifahruddinakas** [comment]
> @andifahruddinakas bukannya view/method untuk cetak dan unduh disatukan, tidak duplikasi?

Yg bermasalah hanya judulnya sj.

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/4227
