### ISSUE TITLE
Bug/error: Konversi autentikasi perangkat menggunakan fitur bawaan laravel auth.

### ISSUE THREAD

**Issue by agungsugiarto** [OpenSID/OpenSID#8677]
### Jelaskan error yg dialami

*

### Cara untuk mereplikasi errornya

*

### Hasil yg diharapkan

*

### Tangkapan layar dan log error

*

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2411.0.0

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/4202
