### ISSUE TITLE
Bug/error: Hasil PDF error

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8678]
### Jelaskan error yg dialami

Klik Laporan PDF pada Buku Rekapitulasi Jumlah Penduduk hasil pdf ada yang error dan logo tidak muncul

### Cara untuk mereplikasi errornya

1. Modul Buku Administrasi Desa
2. Menu Administrasi Penduduk
3. Sub Menu Buku Rekapitulasi Jumlah Penduduk
4. Klik Laporan PDF

### Hasil yg diharapkan

Laporan dapat di download PDF 

### Tangkapan layar dan log error

 
![image](https://github.com/user-attachments/assets/df8b40de-12ad-4cf4-a03f-76fd7f48d834)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Versi 2411.0.0-premium

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/4228
