### ISSUE TITLE
Bug/error: Perbaikan Isi lampiran Surat Nikah Warga Non Muslim

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8679]
### Jelaskan error yg dialami

Tanggal Perkawinan tidak sesuai dengan yang di isi pada form 

### Cara untuk mereplikasi errornya

1. Klik menu Cetak Surat
2. Pilih Surat Keterangan untuk nikah warga non muslim
3. Cetak Surat

### Hasil yg diharapkan

Tidak ada lagi kesalahan data pada Surat dan Lampiran Surat Keterangan untuk nikah warga non muslim, agar surat bisa segera di gunakan oleh Desa

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/50b66b26-5f33-4283-8b94-4393b5df0dc0)

![image](https://github.com/user-attachments/assets/404aa7fc-b4c3-45a6-8cfd-ee7e3bedfb21)

![image](https://github.com/user-attachments/assets/e48b77ba-1256-48ad-8d29-3956628506da)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Versi 2411.0.0-premium

### Informasi tambahan

Laporan Desa Gunung Salak Kab Tabanan Bali
@sumerta

**Comment by andifahruddinakas** [comment]
mas @rgrahardi, sesuai pembahasan dipertemuan. untuk mengurangi issue yang berulang seperti surat nikah ini, yang bisa dilakukan mengecek secara keseluruhan bagian-bagian mana saja yang masih belum sesuai. Cotoh : 

- [ ] penulisan tanggal perkawinan
![image](https://github.com/user-attachments/assets/04150588-3a6e-4e68-b66b-7a589d8c91be)
- [ ] penulisan tanggal melapor
![image](https://github.com/user-attachments/assets/17c4b6b9-2590-438c-8545-cd896723b4a7)

**Comment by rgrahardi** [comment]
baik mas @andifahruddinakas

**Comment by andifahruddinakas** [comment]
> baik mas @andifahruddinakas

Akan diperbaiki sesuai issue awal, silahkan buat issue lain jika masih ada masalah pada lampiran tsb.

**Comment by rgrahardi** [comment]
baik mas @andifahruddinakas
