### ISSUE TITLE
Bug/error: Lampiran Surat Keterangan Nikah tidak Muncul Surat Pernyataan Calon Pengantin dan Pasangan Calon Pengantin & QR-Code untuk Lampiran N-1, N-6, Surat Keterangan Wali Nikah Surat Nikah (Modul TTE Aktif) 

### ISSUE THREAD

**Issue by langonsari** [OpenSID/OpenSID#8681]
### Jelaskan error yg dialami

- [ ] Lampiran Surat Pernyataan Calon Pengantin & Pasangan Calon Pengantin tidak muncul
- [ ] QR-Code untuk Lampiran N-1, N-6, Surat Keterangan Wali Nikah Surat Nikah Untuk muncul setelah diverifikasi Kepala Desa
![image](https://github.com/user-attachments/assets/d2350544-8a6c-4ba0-8777-374f7b545045)
![image](https://github.com/user-attachments/assets/75d1bdfa-1752-40dd-83b0-76a141d44873)
![image](https://github.com/user-attachments/assets/6182412d-19c5-49a7-8547-2a10deabf4b2)

### Cara untuk mereplikasi errornya

- [ ] **Lampiran Surat Pernyataan Calon Pengantin & Pasangan Calon Pengantin tidak muncul**
![image](https://github.com/user-attachments/assets/8231d5d0-bd26-4db9-809c-16fd693c5f20)
![image](https://github.com/user-attachments/assets/320ccd01-a403-4a9f-b59b-3f7ed04f174a)
Mengganti isi view.php sesuai dengan nama file yang ada/rename file lampiran sesuai dengan isi dari view.php.
//    include_once '**view_individu.php**'; (_diganti view_pria.php_)
//    include_once '**view_calon_pasangan.php**'; (_diganti view_wanita.php_)

### Hasil yg diharapkan

QR-Code di Lampiran muncul seperti pada Surat Keterangan nikah
![image](https://github.com/user-attachments/assets/4f7a5ad6-5873-45ca-9e83-b9252619096a)

### Tangkapan layar dan log error

tidak muncul logs error

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2411.0.0-premium

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/4231
