### ISSUE TITLE
Bug/error: Instalasi Baru isian Nama desa tidak ada

### ISSUE THREAD

**Issue by ilhamwahyu-ni** [OpenSID/OpenSID#8683]
### Jelaskan error yg dialami

instalasi baru

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

bisa mencaari nama desa denggan cepat

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/cf217396-0490-4343-a7d2-5b5b24af5986)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

bux fix

**Comment by andifahruddinakas** [comment]
pak @ilhamwahyu-ni, saat install pertama kali memang data desa awal kosong. https://panduan.opendesa.id/id/opensid/instalasi

Jika terkait pilih data identitas desa karena mengambil data dari luar (https://pantau.opensid.my.id/ akan terpengaruh jika sedang MT atau masalah lainnya.

**Comment by ilhamwahyu-ni** [comment]
> pak @ilhamwahyu-ni, saat install pertama kali memang data desa awal kosong. https://panduan.opendesa.id/id/opensid/instalasi
> 
> Jika terkait pilih data identitas desa karena mengambil data dari luar ([pa](https://pantau.opensid.my.id/) akan terpengaruh jika sedang MT atau masalah lainnya.

Apa ada hubungannya dengan yang ini mas 

![image](https://github.com/user-attachments/assets/6f4cd51d-0739-4ff5-84bd-58c747b8a714)
