### ISSUE TITLE
Bug/error: Gagal dapat seluruh akses setelah instalasi baru (fresh) setelah menggunakan Restore DB 

### ISSUE THREAD

**Issue by ilhamwahyu-ni** [OpenSID/OpenSID#8690]
### Jelaskan error yg dialami

setelah insttalasi terbaru dari opensid kemudian kita akan menggunakan database desa/nagari kita,

dengan menggunakan fitur restore..

nah disini terjadi akses gagal di seluruh menu yang ada.

### Cara untuk mereplikasi errornya

install baru > restore db desa/nagari

![image](https://github.com/user-attachments/assets/fb7dc3b5-0238-4d24-b39a-36ba06966e86)

coba login lagi

### Hasil yg diharapkan

normal.

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/509a0a90-1a7d-41c0-a982-fa45ab7cb0d6)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

bux fix

### Informasi tambahan

alternatif >> menghapus seluruh migrasi di DB desa/nagari kemudian baru login

**Comment by andifahruddinakas** [comment]
pak @ilhamwahyu-ni, bisa gunakan versi rilis untuk ini. di versi bug-fix terdapat migrasi yang perlu dijalankan manual, namun jika sudah masuk tahapan rilis dimasukkan sebegai migrasi otomatis.
