### ISSUE TITLE
Permintaan fitur: Kode isian bulan angka

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8692]
### Apa kekurangan yg ingin diatasi?

belum ada kode isian bulan angka

### Jelaskan solusi yg diinginkan

terdapat kode isian bulan angka untuk kebutuhan nomor surat

![image](https://github.com/user-attachments/assets/32cfa1de-fa0a-4c6d-8c20-b9db07c467b4)

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

Versi 2411.0.1-premium

### Informasi tambahan

Permintaan Desa Sumber Sari Kab Kutai Kartanegara
Telegram @Ungkys

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/4282
