### ISSUE TITLE
Bug/error: Ada koma " , " diantara kecamatan dan kabupaten pada buku tamu

### ISSUE THREAD

**Issue by ilhamwahyu-ni** [OpenSID/OpenSID#8694]
### Jelaskan error yg dialami

-

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

normal

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/25dc4131-5c93-47d9-a149-202856c9af37)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

bux fix

### Informasi tambahan

izin mas @andifahruddinakas 
bolehkan saya memperbaiki ini, saya sambil belajar..

saya menemukannya di sini..

🙏

![image](https://github.com/user-attachments/assets/1ec6bb0d-053d-4446-8667-1342bcc7349d)

**Comment by andifahruddinakas** [comment]
perbaiki jg di anjungan
![image](https://github.com/user-attachments/assets/fde03e9b-e444-4c22-8a9e-caf73a6883af)

**Comment by ilhamwahyu-ni** [comment]
> perbaiki jg di anjungan ![image](https://private-user-images.githubusercontent.com/57283157/384272932-fde03e9b-e444-4c22-8a9e-caf73a6883af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwNTI1MTQsIm5iZiI6MTczMTA1MjIxNCwicGF0aCI6Ii81NzI4MzE1Ny8zODQyNzI5MzItZmRlMDNlOWItZTQ0NC00YzIyLThhOWUtY2FmNzNhNjg4M2FmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA4VDA3NTAxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY4Yjk0Y2FlZGQxZWExZDBmMWRlNmNlZGY4NmQ3NWQ2YTgwNTBlZjQyMzUxMTI2MzA0MGY5N2JjMjg1OTA5NzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.PkocPVQ-MXbGahZDPf3JHmoioHjnR7r-HoV4h5kSOlg)

sudah mas,,

![image](https://github.com/user-attachments/assets/e483d053-801b-438d-a1e9-f6e5ce68a0b9)

lalu untuk commitnya
gimana ste-stepnya mas @andifahruddinakas  ?

**Comment by andifahruddinakas** [comment]
> > perbaiki jg di anjungan ![image](https://private-user-images.githubusercontent.com/57283157/384272932-fde03e9b-e444-4c22-8a9e-caf73a6883af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwNTI1MTQsIm5iZiI6MTczMTA1MjIxNCwicGF0aCI6Ii81NzI4MzE1Ny8zODQyNzI5MzItZmRlMDNlOWItZTQ0NC00YzIyLThhOWUtY2FmNzNhNjg4M2FmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA4VDA3NTAxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY4Yjk0Y2FlZGQxZWExZDBmMWRlNmNlZGY4NmQ3NWQ2YTgwNTBlZjQyMzUxMTI2MzA0MGY5N2JjMjg1OTA5NzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.PkocPVQ-MXbGahZDPf3JHmoioHjnR7r-HoV4h5kSOlg)
> 
> sudah mas,,
> 
> ![image](https://private-user-images.githubusercontent.com/85351181/384278629-e483d053-801b-438d-a1e9-f6e5ce68a0b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwNTM1MDEsIm5iZiI6MTczMTA1MzIwMSwicGF0aCI6Ii84NTM1MTE4MS8zODQyNzg2MjktZTQ4M2QwNTMtODAxYi00MzhkLWExZTktZjZlNWNlNjhhMGI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA4VDA4MDY0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4YWRiMmQwZTUzOTAyNGMzZWQ1NmQ3MTZkYzkzODg2ZjJmZjQzMDBhNzMyY2ViNjQ1NmM5Mzc0OTM2OWViYmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.3jN_RyvUx0iogysHNCtYLDwExboKI-alddOLqeQEpq4)
> 
> lalu untuk commitnya gimana ste-stepnya mas @andifahruddinakas ?

https://github.com/OpenSID/OpenSID/wiki/Pull-Requets-Dengan-Github-Desktop

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/4239
