### ISSUE TITLE
Bug/error: Pengaturan Margin Ubah Layanan Surat Tidak Sesuai Dengan Tinjau Pdf

### ISSUE THREAD

**Issue by luxmant354** [OpenSID/OpenSID#8697]
### Jelaskan error yg dialami

Ketika Surat Layanan Pertama Kali Dibuat Maka Surat tersebut sudah sesuai jika di ubah melalui pengaturan margin
![pengaturan komplit](https://github.com/user-attachments/assets/3e57c1f4-dad2-4c9d-9bb6-d57be3d29ed9)

tapi ketika surat sudah di cetak, dan ternyata ada perubahan sehingga diubah melalui fitur ubah surat layanan, pengaturan margin tidak ada, dan ketika coba diubah header/ foother di pengaturan menjadikan tampilan surat jadi kacau tidak sesuai dengan tinjau pdf
![pengaturan tidak komplit](https://github.com/user-attachments/assets/8a484974-c99b-45c5-92cf-9319c104093b)
![Screenshot_7](https://github.com/user-attachments/assets/9c6626be-6bff-480e-ab61-e13c6c935a45)
![Screenshot_8](https://github.com/user-attachments/assets/c67dd1d9-69b9-4c2e-a3a2-8d524cb021fa)

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

Pengaturan di ubah layanan surat komplit ada margin yang sesuai dengan tinjau pdf dan hasil cetakan juga sesuai
![pengaturan komplit](https://github.com/user-attachments/assets/f26da3bc-b1e1-47b7-9441-a4b04faf9709)

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v2411.0.0-premium

### Tema Yang Digunakan

-

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/4242
