### ISSUE TITLE
di menu Bantuan Perlu di buatkan fasilitas CARI

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#870]
untuk lebih memudahkan aparat desa dalam pengentrian dan juga pecarian nama masyarakat yang sudah mendapatkan bantuan program maka dipandang perlu dan penting untuk ditambahkan Fasilitas CARI di Setiap Prosetiap Program seperti gambar dibawah ini : 
![screenshot 2018-03-24 11 19 26](https://user-images.githubusercontent.com/25834335/37859871-eb581416-2f55-11e8-88b6-88e6d4508c45.png)
 
fasilitas carinya seperti di menu penduduk atau keluarga
![screenshot 2018-03-24 11 24 50](https://user-images.githubusercontent.com/25834335/37859887-201b3944-2f56-11e8-9e4c-1b44ca579fc4.png)

**Comment by dankrez48** [comment]
[GIT_WILDAN.zip](https://github.com/OpenSID/OpenSID/files/3210733/GIT_WILDAN.zip)
silahkan ganti beberapa file terlampir pada folder donjo-app

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR #2053
