### ISSUE TITLE
Bug/error: pilihan jenjang pendidikan tidak lengkap 

### ISSUE THREAD

**Issue by typevant** [OpenSID/OpenSID#8704]
### Jelaskan error yg dialami

pada saat ingin mengisi jenjang pendidikan, pilihan maksimal hanya sampai Strata I saja

### Cara untuk mereplikasi errornya

1. Penduduk
2. Ubah data penduduk
3. Jenjang pendidikan

### Hasil yg diharapkan

Isian sesuai dengan yang ada seperti pada versi sebelumnya.

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/3114948f-f5d9-47f6-be09-1bfdef132434)

### Rilis Versi OpenSID

Rilis Umum

### Versi OpenSID

v2411.0.0

### Tema Yang Digunakan

DeNava

**Comment by andifahruddinakas** [comment]
pak @typevant, sy cek di https://berputar.opendesa.id/penduduk/form_peristiwa/1
![image](https://github.com/user-attachments/assets/145f57d4-c1a4-4018-bf86-4b012190c1ad)

**Comment by typevant** [comment]
Brrti apakah hanya terjadi pada web desa saya saja pak?@andifahruddinakas
