### ISSUE TITLE
Bug/error: Icon diluar kotak pada SKOR IDM MINIMAL dan STATUS IDM

### ISSUE THREAD

**Issue by ilhamwahyu-ni** [OpenSID/OpenSID#8705]
### Jelaskan error yg dialami

-

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

normal

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/7b976771-bb07-4d50-809e-7d846135a981)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

bux fix

### Informasi tambahan

izin  mas @andifahruddinakas  untuk perbaiki CSS nya

jadi seperti ini..

![image](https://github.com/user-attachments/assets/2325eee1-c02c-47c5-956a-0dec95bf6984)

**Comment by andifahruddinakas** [comment]
Sekalian untuk : 

- [ ] pelanggan
- [ ] status idm
- [ ] stunting

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/4252
