### ISSUE TITLE
DI DATA SUPLEMEN juga perlu ditambahkan fasilitas CARI .... 

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#871]
di data suplemen juga perlu ditambahkan fasilitas cari seperti yang ada di menu penduduk
![screenshot 2018-03-24 11 27 00](https://user-images.githubusercontent.com/25834335/37859897-5671fef6-2f56-11e8-8326-5ca79bbb5dde.png)

Menu Penduduk
![screenshot 2018-03-24 11 24 50](https://user-images.githubusercontent.com/25834335/37859907-735659b8-2f56-11e8-9670-868b06882248.png)

**Comment by afa28** [comment]
Sudah tersedia di versi terbaru.

**Comment by afa28** [comment]
Apakah ini masih bermasalah??? Kalau tdk silahkan di close.

**Comment by MUHAMMADRANGSEL** [comment]
Perlu karena saat ini fitur pencarian belum ada

Pada tanggal Sen, 24 Agt 2020 14.04, Andi Fahruddin Akas <
notifications@github.com> menulis:

**Comment by afa28** [comment]
Duplicate #3511
