### ISSUE TITLE
Teknis: Impor Penduduk 

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8714]
### Jelaskan error yg dialami

Impor Penduduk Berhasil, Data penduduk tidak masuk ke database dan log error kosong.
![image](https://github.com/user-attachments/assets/e97b1326-44de-4429-a7f0-79dcd81f1884)
![image](https://github.com/user-attachments/assets/b15b66f2-0b26-4383-a0f1-912d356864ec)
![image](https://github.com/user-attachments/assets/158c8d61-3dff-4e53-94d5-b1e96916f1df)

Penyebabnya file impor yang di dapat dari opensid nama sheet belum di ganti menjadi Data Penduduk seperti nama sheet di file impor yang satu lagi

![image](https://github.com/user-attachments/assets/8dbf77d3-fdb5-4413-bdfd-d06f36e199b5)

pada file impor yang satu lagi nama sheet sudah tepat

![image](https://github.com/user-attachments/assets/7af6c443-e54c-4893-8c07-dca9cd1f1a63)

### Cara untuk mereplikasi errornya

1. Menu Penduduk
2. Impor Penduduk

### Hasil yg diharapkan

Usulan Teknis

![image](https://github.com/user-attachments/assets/b8b43feb-1aa8-40a1-a405-da645e8899fd)

Contoh Data gunakan juga FIle yang ini 

![image](https://github.com/user-attachments/assets/c0b56975-7848-4da3-9e12-5e3f16c22946)

Tidak lagi menggunakan File yang ini 

![image](https://github.com/user-attachments/assets/e4cb17e6-7ccb-4999-aa14-60a684a9d22e)

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Versi 2411.0.1-premium

### Informasi tambahan

-

**Comment by rgrahardi** [comment]
Hasil pertemuan menggunakan 1 file saja untuk impor penduduk cc mas @andifahruddinakas dan mas @vickyrolanda 

![image](https://github.com/user-attachments/assets/e28790eb-991e-4247-9e86-5b9daccea47e)

**Comment by andifahruddinakas** [comment]
Sudah disesuaikan melalui commit https://github.com/OpenSID/premium/commit/0c89a0a4c671f12ac4fd8810680ffcd0c428cdc6
