### ISSUE TITLE
Bug/error: Surat Keterangan Pengantar Rujuk Atau Cerai ada 2

### ISSUE THREAD

**Issue by ilhamwahyu-ni** [OpenSID/OpenSID#8718]
### Jelaskan error yg dialami

-

### Cara untuk mereplikasi errornya

lakukan pencarian surat keyword "rujuk"

### Hasil yg diharapkan

satu saja

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/06ca8daa-774b-4cb7-9cdd-da54fbac3097)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

bux fix

**Comment by andifahruddinakas** [comment]
![image](https://github.com/user-attachments/assets/8a0d66f1-d3b6-4661-9bc4-45152dc59e11)

Hapus berdasarkan url dan jenis surat (bawaan)

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/4251
