### ISSUE TITLE
Usul tambah opsi Warga dan Bukan Warga

### ISSUE THREAD

**Issue by otnayile** [OpenSID/OpenSID#872]
Min kalo pada surat di menu cetak surat ditambah opsi warga dan bukan warga? jadi kalo di pilih warga, muncul box lanjutan untuk pilih nik yang nanti keluar otomatis. kalau dipilih bukan warga muncul box inputan manual. soalnya beberapa surat dibuat untuk non warga sekalipun.
trus sama mau tanya kalo menambahkan huruf romawi biar otomatis pake [code] apa ya?

**Comment by balongbesuk** [comment]
![untitled23](https://user-images.githubusercontent.com/35319600/37862241-5f2d50ec-2f7c-11e8-84cb-c5779319f100.jpg)

**Comment by otnayile** [comment]
maksud saya bisa muncul opsi seperti yang di surat kematian pada info pelapor. bila di-klik warga muncul opsi pilih nik. bila diklik bukan warna muncul box isian manual gitu pak

**Comment by eddieridwan** [comment]
Pilihan penduduk warga atau non-warga perlu ditentukan untuk masing2 surat, tidak bisa dilakukan secara menyeluruh.

Tetapi perlu dilihat dulu apakah suatu surat memang perlu diberi opsi tersebut. Belum tentu suatu surat berlaku untuk non-warga. Misalnya, pada surat kematian, pelapor boleh warga/non-warga. Tetapi yang meninggal harus dari warga, karena desa tidak akan membuat surat kematian untuk non-warga.

Kami akan tutup issue ini. Kalau anda ingin mengusulkan perubahan pada surat tertentu (issue HARUS spesifik -- tidak bisa bersifat umum), silakan buat issue baru. Kalau ada beberapa surat yang ingin diubah, buat issue terpisah untuk setiap surat. 

Dan ikut pedoman cara penulisan issue yang baik di https://github.com/OpenSID/OpenSID/wiki/Pengelolaan-Masalah-dan-Permintaan-Perbaikan-SID.
