### ISSUE TITLE
Bug/error: C-Desa pada Pemetaan

### ISSUE THREAD

**Issue by binrosyad** [OpenSID/OpenSID#8720]
### Jelaskan error yg dialami

Sebetulnya ini bukan Bug, hanya minta agar C-Desa tidak ditampilkan di Website, karena menurut hemat kami ini bukan bagian dari sesuatu yang bisa dikonsumsi publik, ini sangat riskan, karena masih banyak tanah yg sudah dimiliki oleh pemilik baru, tapi di C-desa masih atas nama pemilik lama, karena dulu pada saat transaksi orang tua kita kebanyakan taransaksi hanya dengan lisan, tanpa ada surat apapun apalagi balik nama. dikhawatirkan bahkan udah sering terjadi, ahli waris dari pemilik nama C-Desa melakukan Gugatan atas peralihan tanah itu, padahal dulu emang benar telah terjadi transaksi, oleh karena itu kami minta agar C-DESA JANGAN DITAMPILKAN DI WEBSITE.

### Cara untuk mereplikasi errornya

1. buka website desa
2. klik Peta
3. klik infrastruktur desa
4. C-Desa terlihat di Peta

### Hasil yg diharapkan

C-Desa Tidak Tampil di Website

### Tangkapan layar dan log error

![cdesa](https://github.com/user-attachments/assets/d0a3ef50-3a16-4ed0-8882-57a5c7c5ab6b)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Saat ini pakai 2411.0.0

### Tema Yang Digunakan

DeNava v16.0

**Comment by eddieridwan** [comment]
@rgrahardi pastikan panduan sudah menjelaskan cara menonaktifkan/mengaktifkan penampilan data di peta web, dan kemudian publikasikan supaya lebih banyak pengguna paham bahwa apa yg ditampilkan di web sepenuhnya dapat mereka atur sendiri. 

@andifahruddinakas periksa juga penyediaan API tema supaya setiap tema premium (seperti DeNava yg digunakan di kasus ini) dapat dengan mudah mengatur supaya tampilan suatu data menjadi aktif/nonaktif.

cc @vickyrolanda

**Comment by andifahruddinakas** [comment]
> @rgrahardi pastikan panduan sudah menjelaskan cara menonaktifkan/mengaktifkan penampilan data di peta web, dan kemudian publikasikan supaya lebih banyak pengguna paham bahwa apa yg ditampilkan di web sepenuhnya dapat mereka atur sendiri. 
> 
> @andifahruddinakas periksa juga penyediaan API tema supaya setiap tema premium (seperti DeNava yg digunakan di kasus ini) dapat dengan mudah mengatur supaya tampilan suatu data menjadi aktif/nonaktif.
> 
> cc @vickyrolanda 

Fitur seperti itu belum ada di pertanahan, yg ada di modul analisis.

**Comment by andifahruddinakas** [comment]
Solusi : 
- [ ] sediakan pengaturan pada masing2 c-desa/persil yg akan ditampilkan di peta(seperti modul analisis)
- [ ] sediakan pengaturan secara global untuk menampilkan peta cdesa/persil ke peta. (Ya/Tidak)

**Comment by pandigresik** [comment]
> * sediakan pengaturan pada masing2 c-desa/persil yg akan ditampilkan di peta(seperti modul analisis)

ini yang mana, saya cek di modul analisis tidak ditemukan pengaturan seperti itu

**Comment by andifahruddinakas** [comment]
> > * sediakan pengaturan pada masing2 c-desa/persil yg akan ditampilkan di peta(seperti modul analisis)
> 
> ini yang mana, saya cek di modul analisis tidak ditemukan pengaturan seperti itu

Untuk masing2 c-desa/persil yg ditampilkan di peta web, bisa ikuti pengaturan analisis sbb. (bagian publish)
![image](https://github.com/user-attachments/assets/901d7eb2-37b5-4ddd-a688-7037e66834db)

Untuk pengaturan globalnya, bisa dibuat seperti menampilkan lapak. (bagian tampilkan)
![image](https://github.com/user-attachments/assets/05360f1d-0746-4fa1-9850-b9f26189163e)

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/4298
