### ISSUE TITLE
Teknis : Gagal Impor : Pemberitahuan ID 11 diganti dengan keterangan Text 

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8726]
### Jelaskan error yg dialami

Gagal Impor : Pemberitahuan ID 11 diganti dengan keterangan Text

![image](https://github.com/user-attachments/assets/c8bc9d17-5c36-424a-9363-c8f607e54bf5)

Referensi : 

![image](https://github.com/user-attachments/assets/231f7866-24b7-4b65-8b0b-6ea52241077b)

### Cara untuk mereplikasi errornya

1. Modul Kependudukan
2. Penduduk
3. Impor Penduduk

### Hasil yg diharapkan

Pemberitahuan ID 11 menggunakan keterangan text 

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Versi 2411.0.2-premium

### Informasi tambahan

-

**Comment by andifahruddinakas** [comment]
Sudah disesuaikan melalui commit https://github.com/OpenSID/premium/commit/37f3d8b1d9be44005374403c48007f7cd1c13d00

![image](https://github.com/user-attachments/assets/05462205-ae45-4b12-946b-91b1aabce085)
