### ISSUE TITLE
Bug/error: Tidak bisa meload helper pada Modules

### ISSUE THREAD

**Issue by agungsugiarto** [OpenSID/OpenSID#8727]
### Jelaskan error yg dialami

Tidak bisa meload helper pada Modules karena tidak dinamis saat dijalankan menggunakan windows / unix

### Cara untuk mereplikasi errornya

1. Pergi ke halaman Prodeskel / DDK / Klik edit pada salah satu daftar

### Hasil yg diharapkan

Error diperbaiki

### Tangkapan layar dan log error

*

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2411.0.0

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/4257
