### ISSUE TITLE
Bug/error: Klik migrasi semua terjadi gagal migrasi

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8728]
### Jelaskan error yg dialami

Klik migrasi semua terjadi gagal migrasi

### Cara untuk mereplikasi errornya

1. Modul Pengaturan
2. Menu Database
3. Migrasi
4. Migrasi Semua

### Hasil yg diharapkan

Migrasi semua berhasil 

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/3e34ef88-bb8d-4dfb-b485-cefc6b26daf6)
![image](https://github.com/user-attachments/assets/bcb8b563-d701-424b-88d4-d3f08cf49d14)
![image](https://github.com/user-attachments/assets/0d352326-7d03-4701-94cb-6920b650bb93)
![image](https://github.com/user-attachments/assets/e9802013-8e82-47ad-a010-042be633aeb1)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

OpenSID v2411.0.1-premium

### Informasi tambahan

Migrasi Terbaru lancar

**Comment by andifahruddinakas** [comment]
Sudah disesuaikan melalui commit https://github.com/OpenSID/premium/commit/c77056e800b65a31e6b3b4588c4c1a3821fdfd17
