### ISSUE TITLE
Bug/error: setingan default margin sama tapi hasil/tampilan beda pada  Surat keterangan Domisili 

### ISSUE THREAD

**Issue by ilhamwahyu-ni** [OpenSID/OpenSID#8729]
### Jelaskan error yg dialami

-

### Cara untuk mereplikasi errornya

buat surat keterangan domisili

### Hasil yg diharapkan

normal

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/2a4386fa-dbea-4b3d-98ed-321e4479b053)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

bux fix

**Comment by andifahruddinakas** [comment]
pak @ilhamwahyu-ni, untuk hasil generate pdf tidak mengikuti margin yg ada di editor, melakikan mengikuti margin yg sudah diatur pada pengaturan surat.

**Comment by ilhamwahyu-ni** [comment]
> pak @ilhamwahyu-ni, untuk hasil generate pdf tidak mengikuti margin yg ada di editor, melakikan mengikuti margin yg sudah diatur pada pengaturan surat.

iya mas saya paham mas tetapi bukankah setingan seluruh usrat itu sama..

ex.

![image](https://github.com/user-attachments/assets/56e809b6-462e-4d65-b6ae-8eaaca9e3f8c)

ini hasil..

![image](https://github.com/user-attachments/assets/8b5bbb9d-2b46-4a05-8c94-450e5223b041)


kalau domisili..

![image](https://github.com/user-attachments/assets/8dbec24a-e6c1-486d-8b0d-f12216abbf30)

hasill beda..

![image](https://github.com/user-attachments/assets/9099de5a-4ff7-459d-a6ba-8b6bbd7eb44b)


mas @andifahruddinakas

**Comment by ilhamwahyu-ni** [comment]
izin mas @andifahruddinakas

**Comment by ilhamwahyu-ni** [comment]
izin mas @andifahruddinakas
