### ISSUE TITLE
Tidak bisa push ke master

### ISSUE THREAD

**Issue by esyede** [OpenSID/OpenSID#873]
Halo! saya ingin berkontribusi di opensid.
Tetapi saya tidak bisa push ke opensid, apakah ada langkah saya yang salah?

![screenshot_1](https://user-images.githubusercontent.com/10582583/37866486-296b4d4a-2f83-11e8-8c75-15256c81879a.png)

**Comment by eddieridwan** [comment]
Untuk kontribusi, ikuti panduan: https://github.com/OpenSID/OpenSID/wiki/Panduan-mengirimkan-perubahan-repo-OpenSID, yaitu kirim pull request.

Juga silakan baca panduan: https://github.com/OpenSID/OpenSID/wiki/Cara-Ikut-Mengembangkan-OpenSID

Dan kirim email untuk diinvite ke forum teknis di https://opensid.slack.com. Tempat bertanya dan diskusi teknis di situ.
