### ISSUE TITLE
Bug/error: 9 Kolom pada Cetak dan unduh Buku KTP kosong

### ISSUE THREAD

**Issue by ilhamwahyu-ni** [OpenSID/OpenSID#8733]
### Jelaskan error yg dialami

pada tampilan admin seluruh kolom memiliki nilai tetapi saat cetak dan unduh ada **9** kolom yang kosong.

### Cara untuk mereplikasi errornya

![image](https://github.com/user-attachments/assets/f9e05e95-0cdf-4468-aca6-4b867bd5c11f)

### Hasil yg diharapkan

diperbaiki sesuai di dasbor admin

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/782f770e-e634-453e-9ffd-086c1a0333cc)
 dan..

![image](https://github.com/user-attachments/assets/30972118-67d1-4dba-8ced-377a6f3b3daf)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

bux fix

**Comment by ilhamwahyu-ni** [comment]
mas @andifahruddinakas 
mohon izin memperbaikinya mas🙏

![image](https://github.com/user-attachments/assets/bd31742e-10ff-458f-b787-66fa2ea4edb1)

karena $collected adalah aray maka akses datanya pun dengan aray..[''] 

mohon arahan..🙏

**Comment by andifahruddinakas** [comment]
> mas @andifahruddinakas 
> mohon izin memperbaikinya mas🙏
> 
> ![image](https://github.com/user-attachments/assets/bd31742e-10ff-458f-b787-66fa2ea4edb1)
> 
> karena $collected adalah aray maka akses datanya pun dengan aray..[''] 
> 
> mohon arahan..🙏

Silahkan, sekalian gunakan enum kolom referensinya.

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/4265
