### ISSUE TITLE
Teknis : Akses Menu Keluarga Berat dan Pencarian Keluarga juga berat

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8739]
### Jelaskan error yg dialami

Akses Menu Keluarga Berat dan Pencarian Keluarga juga berat

Jumlah Penduduk di Pantau : 7433
Jumlah Keluarga : 2451
loading time akses menu keluarga  : 1 menit 10 detik
loading time pencarian keluarga : 1 meni 27 detik

Pada versi 2409.0.0-premium akses menu keluar dan pencarian tidak sampai 30 detik.

![image](https://github.com/user-attachments/assets/de1902fa-0556-4e7e-b8a9-8bea5a6ac6b3)
![image](https://github.com/user-attachments/assets/dc4ebf9e-13ef-4744-8fde-1d16da1f6d5d)
![image](https://github.com/user-attachments/assets/c6051da9-544c-45ee-b633-0a6b9239a12f)

### Cara untuk mereplikasi errornya

1. Klik Modul Kependuduk
2. Klik Menu Keluarga
3. Pencarian Menu Keluarga

### Hasil yg diharapkan

Akses Data Keluarga dan Pencarian Data Keluarga cepat 

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Versi 2411.0.2-premium

### Informasi tambahan

Laporan Desa Cigelam 
Pak @Syafri18

**Comment by eddieridwan** [comment]
@rgrahardi jumlah keluarga berapa? Dapatkan data dari bung Syafri jumlah data pada tabel2 lain terkait query yg dijalankan.

**Comment by rgrahardi** [comment]
sudah saya tambahkan jumlah keluarga pak @eddieridwan

**Comment by eddieridwan** [comment]
@andifahruddinakas @vickyrolanda untuk pengujian solusinya, pastikan diuji lolos oleh bung Syafri, Desa Cigelam, sebelum issue ini ditutup.

**Comment by pandigresik** [comment]
lebih baik jika menggunakan data desa pak syafri, serta bisa diinformasikan spesifikasi server yang digunakan desa cigelam

**Comment by eddieridwan** [comment]
@pandigresik Cigelam hosting di OpenDesa. Bisa dapatkan spesifikasinya dari @scqolbu24 atau @anangnovriadi .

Sebelumnya Desa Cigelam tidak bersedia berbagi datanya. Tapi bisa dikonfirmasi ulang. 

Pastikan testing sebelum solusinya dirilis dilakukan oleh bung Syafri menggunakan data Cigelam.

**Comment by pandigresik** [comment]
Kami test dengan data penduduk 8223 dan data keluarga 2519 aman saja sebagaimana terlihat di video. Dari hasil test di local kami untuk membuka halaman keluarga dari beranda + 2 kali pencarian membutuhkan waktu sekitar 30 detik
Note : data penduduk dan keluarga sudah diacak

https://github.com/user-attachments/assets/d99de96e-d2a5-46cf-a57f-6b8f5cfb78b3

**Comment by eddieridwan** [comment]
Verifikasi bersama bung Syahri di Discord. @rgrahardi mohon anda koordinasi bersama Syahri untuk verifikasi ulang dengan @pandigresik

**Comment by pandigresik** [comment]
https://t.me/c/1238304761/52729/70410

![image](https://github.com/user-attachments/assets/8288c75f-7daa-4bfe-86cc-b519769ad7ea)
