### ISSUE TITLE
PENGATURAN LOGOUT OTOMATIS

### ISSUE THREAD

**Issue by SahlaniAfnan** [OpenSID/OpenSID#874]
penambahan fitur logout otomatis, hal ini bertujuan untuk mengamankan data dari pengguna yang lupa logout..
![pengaturan logout otomatis](https://user-images.githubusercontent.com/15683308/37868528-60ef0a0c-2fda-11e8-9560-708c8687fd13.jpg)

**Comment by eddieridwan** [comment]
Timeout diatur oleh Codeigniter sessions. Setting saat ini (di donjo-app/config/config.php):

```
$config['sess_expiration']		= 7200;
$config['sess_expire_on_close']	= FALSE;
$config['sess_match_ip']		= FALSE;
$config['sess_match_useragent']	= TRUE;
$config['sess_time_to_update']	= 300;
```

Saat ini setiap controller memeriksa $_SESSION['sesi'] untuk verifikasi user masih login. Data ini diambil dari database yg berisi data unik utk setiap user ditulis sekali pada saat membuat user baru. Data ini tidak menggunakan session_id. 

Karena itu yang berlaku adalah waktu $config['sess_expiration'] dan bukan $config['sess_time_to_update']. Yaitu, saat ini waktu logout otomatis adalah 7200 detik, yaitu 2 jam tidak ada kegiatan.

Saat ini belum ada fitur untuk memungkinkan admin mengubah waktu ini. Jika itu dibutuhkan, silakan ubah issue ini untuk menjelaskan apa yang diinginkan.

**Comment by SahlaniAfnan** [comment]
Makasih Infonya Kang @eddieridwan
