### ISSUE TITLE
Bug/error: Menu Daftar Anjungan tidak bisa diakses

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8740]
### Jelaskan error yg dialami

Menu Daftar Anjungan tidak bisa diakses

### Cara untuk mereplikasi errornya

1. Klik Modul Anjungan 
2. Klik Menu Daftar Anjungan

### Hasil yg diharapkan

Menu Daftar Anjungan bisa diakses

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/bf91b289-3105-41bd-8699-a8aa6707691f)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

OpenSID v2411.0.1-premium

### Informasi tambahan

Laporan Desa Rarang Selatan
pak @muhammadrangsel

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/4269
