### ISSUE TITLE
Bug/error: Statistik Kependudukan - Kepemilikan KTP dan Kepemilikan KIA tidak bisa diakses

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8741]
### Jelaskan error yg dialami

Kependudukan - Kepemilikan KTP dan Kepemilikan KIA tidak bisa diakses

### Cara untuk mereplikasi errornya

1.Modul Statistik
2. Menu Statistik Kependudukan
3. Statistik Kependudukan - Kepemilikan KTP
4. Statistik Kependudukan - Kepemilikan KIA

### Hasil yg diharapkan

Statistik Kepemilikan KTP dan KIA bisa di akses

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/a48da28c-d9eb-4049-8ad9-079f9556a3fc)
![image](https://github.com/user-attachments/assets/0da99310-096a-4e52-9c6d-65de25f85280)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Versi 2411.0.1-premium

### Informasi tambahan

Laporan Desa Sidokumpul 
pak @afif

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/4271
