### ISSUE TITLE
Bug/error: QRCODE tidak muncul di Pratinjau PDF

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8742]
### Jelaskan error yg dialami

QRCODE tidak muncul di Pratinjau PDF

### Cara untuk mereplikasi errornya

1. Layanan Surat
2. Pengaturan 
3. Klik Template Surat 
4. Klik Tinjau PDF

### Hasil yg diharapkan

QRCode tampil di Tinjau PDF

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/430e1bae-ba9b-4f17-bfe7-dc785e2e6bba)

![image](https://github.com/user-attachments/assets/abb6a08f-29ad-4194-8718-d4424336cc67)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Versi 2411.0.1-premium

### Informasi tambahan

Laporan Desa Antap
Pak @sam

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/4273/
