### ISSUE TITLE
Bug/error: Hak Akses Baca "Kolom aksi" masih ada

### ISSUE THREAD

**Issue by ilhamwahyu-ni** [OpenSID/OpenSID#8745]
### Jelaskan error yg dialami

keluarga ->anggota
catatan peristiwa
sinergi program

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

normal

### Tangkapan layar dan log error

anggota keluarga
![image](https://github.com/user-attachments/assets/6f086541-5148-424c-ac0c-29217574bc91)

catatan peristiwa
![image](https://github.com/user-attachments/assets/11ddb24a-8d7d-4fee-a7df-52cecd1002bb)

sinergi program

![image](https://github.com/user-attachments/assets/1b5cef3a-016f-4dfc-a843-747126dbe0f5)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

bux fix

**Comment by ilhamwahyu-ni** [comment]
izin perbaiki mas @andifahruddinakas 🙏

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/4276
