### ISSUE TITLE
Teknis : Panjang Judul Surat

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8747]
### Jelaskan error yg dialami

Pengisian Judul Surat : Rekomendasi Pembelian Jenis BBM Tertentu Minyak Solar dan Khusus Penugasan Pertalite 1

![image](https://github.com/user-attachments/assets/7c4ba1cb-7ffa-4e05-a705-589e59aa6d32)

Error : 

![image](https://github.com/user-attachments/assets/764a2ec1-a6ff-4ad3-bfbc-56721bf7ea4a)

### Cara untuk mereplikasi errornya

1. Tambah Template Surat
2. Isi Judul yang panjang
3. Isi template 
4. Isi Form Isian
5. Simpan

### Hasil yg diharapkan

Usulan 1

- Surat bisa menyimpan dengan judul yang panjang seperti : Rekomendasi Pembelian Jenis BBM Tertentu Minyak Solar dan Khusus Penugasan Pertalite 1

Usulan 2 

- ketika Klik Simpan Terdapat Notifkasi / Pemberitahuan Judul Surat Terlalu Panjang, Saat ini notifikasi hanya Pesan Error.

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Versi 2411.0.3-premium

### Informasi tambahan

Laporan Desa Angseri
Pak @Ketut_Ayag_Oyog

**Comment by andifahruddinakas** [comment]
Tambahan validasi dan pengecekan saat impor.

**Comment by habibie11** [comment]
saya coba replikasi dengan langkah-langkah tercantum di issue, surat berhasil tersimpan
![image](https://github.com/user-attachments/assets/d4249779-ca68-4d0d-a89e-3227344acf4f)

cc @andifahruddinakas @rgrahardi

**Comment by pandigresik** [comment]
> saya coba replikasi dengan langkah-langkah tercantum di issue, surat berhasil tersimpan
> ![image](https://github.com/user-attachments/assets/d4249779-ca68-4d0d-a89e-3227344acf4f)
> 
> cc @andifahruddinakas @rgrahardi 

Kalau dari pesan errornya di log_surat berarti error terjadi ketika buat surat bukan ketika menu pengaturan surat

**Comment by pandigresik** [comment]
kalau cek struktur tabelnya, bisa menampung sampai dengan 100 karakter. Coba masukkan nama surat yang lebih panjang misalnya "Rekomendasi Pembelian Jenis BBM Tertentu Minyak Solar dan Khusus Penugasan Pertalite 1 untuk percobaan 212"

**Comment by habibie11** [comment]
Oke mas, sedang ditelusuri lebih lanjut.

> kalau cek struktur tabelnya, bisa menampung sampai dengan 100 karakter. Coba masukkan nama surat yang lebih panjang misalnya "Rekomendasi Pembelian Jenis BBM Tertentu Minyak Solar dan Khusus Penugasan Pertalite 1 untuk percobaan 212"

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/4283
