### ISSUE TITLE
Bug/error: Teknis Error illuminate/console component info

### ISSUE THREAD

**Issue by agungsugiarto** [OpenSID/OpenSID#8748]
### Jelaskan error yg dialami

Error illuminate/console component info ketika menjalankan `php index.php artisan cache:clear`, error ini terjadi karena library illuminate/console tidak terupdate secara sempurna.

### Cara untuk mereplikasi errornya

jalankan `php index.php artisan cache:clear`

### Hasil yg diharapkan

error hilang

### Tangkapan layar dan log error

*

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2412.0.0

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/4278
