### ISSUE TITLE
Bug/error: Teknis tambahkan command view:clear untuk memudahkan menghapus cache view blade.

### ISSUE THREAD

**Issue by agungsugiarto** [OpenSID/OpenSID#8749]
### Jelaskan error yg dialami

Saat ini untuk menghapus cache blade dilakukan secara manual yang menyulitkan programmer saat ingin menghapus

### Cara untuk mereplikasi errornya

*

### Hasil yg diharapkan

Tambahkan command view:clear

### Tangkapan layar dan log error

*

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2412.0.0

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/4279
