### ISSUE TITLE
Bug/error: Modul Analilsis Hak akses baca bisa ubah dan hapus

### ISSUE THREAD

**Issue by ilhamwahyu-ni** [OpenSID/OpenSID#8750]
### Jelaskan error yg dialami

sub menu nya juga ada yang bisa ubah dan hapus

### Cara untuk mereplikasi errornya

![image](https://github.com/user-attachments/assets/03c7d99c-10b4-4af4-97a7-1f9fd6b621d6)

### Hasil yg diharapkan

normal

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/74593f97-bb46-4e46-a37e-fd70512171cd)

sub menu
![image](https://github.com/user-attachments/assets/943f489d-1acd-471e-940c-7280a3616315)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

bux fix

**Comment by andifahruddinakas** [comment]
Sdh diperbaiki, namun terdapat kasus khusus untuk hak akses pada modul analisis dan perlu dianalisis lebih lanjut.
