### ISSUE TITLE
Hapus Penggunaan Input Query Manual di Modul Shortcut

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#8753]
![image](https://github.com/user-attachments/assets/820333e1-b58a-4fb5-9564-48b5694a46ee)

Seharusnya tidak diperbolehkan secara bebes pengguna melakukan query secara langsung. Jika pada jenis data  yg diberikan belum ada yang sesuai maka dibuatkan pada issue baru.

**Comment by pandigresik** [comment]
Sudah diperbaiki PR https://github.com/OpenSID/premium/pull/4291
