### ISSUE TITLE
Bug/error: Keluarga Baru

### ISSUE THREAD

**Issue by afri18** [OpenSID/OpenSID#8757]
### Jelaskan error yg dialami

Saat input keluarga baru dari penduduk yg sudah ada tidak terdeteksi di Lap Statistik>Bulanan

### Cara untuk mereplikasi errornya

Seharusnya d Statistik>Lap Bulanan saat penambahan Keluarga BAru dari penduduk yg sudah ada terdeteksi sebagai Keluarga Baru

### Hasil yg diharapkan

Penambahan Keluarga Baru dari Penduduk yg sudah ada Harus Terhitung sebagai Keluarga Baru/Lahir di Stasistik>Lap Bulanan

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/c542fb44-4f79-47b5-ae30-bebe7cebb44e)
hasil d Statistik>LAp Bulanan tidak terbaca
![image](https://github.com/user-attachments/assets/231ab378-0fea-4346-a69f-c6ca279a71fb)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2411.0.2

### Tema Yang Digunakan

denatra

### Informasi tambahan

sudah beberapa edisi/versi tidak terdeteksi

**Comment by andifahruddinakas** [comment]
mas @habibie11, cek : 

- [ ] saat klik detail dari angka tsb datanya kosong

<img width="960" alt="image" src="https://github.com/user-attachments/assets/ddd5b4dd-a195-44d9-b7a2-9aa53a4d2474">

![image](https://github.com/user-attachments/assets/fdc15a33-af57-4b01-8654-1a95ddb9b8ae)
