### ISSUE TITLE
Bug/error: Data C-Desa Tidak Muncul

### ISSUE THREAD

**Issue by binrosyad** [OpenSID/OpenSID#8758]
### Jelaskan error yg dialami

Data C-Desa di halaman Admin Tidak muncul, Kita tidak bisa melakukan pengeditan apapun

### Cara untuk mereplikasi errornya

1 Pergi Kehalaman Admin
2. Klik Pertanahan-C-Desa
3. Muncul eror

### Hasil yg diharapkan

Data C-desa di halaman Admin menu pertanahan Muncul sebagaimana semula.

### Tangkapan layar dan log error

![cdesaeror](https://github.com/user-attachments/assets/238dcb8f-ad36-456c-a07f-c46fea2faec0)
![image](https://github.com/user-attachments/assets/fd605ac5-e680-4e6c-b128-7af7c0b705ac)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2411.0.2

### Tema Yang Digunakan

DeNava v16.0

**Comment by andifahruddinakas** [comment]
Duplicate of https://github.com/OpenSID/OpenSID/issues/8792
