### ISSUE TITLE
tidak bisa simpan saat buat tombol shorcut menggunakan query manual 

### ISSUE THREAD

**Issue by mranca** [OpenSID/OpenSID#8760]
### Jelaskan error yg dialami

saat ingin membuat shortcut menggunakan query manual tidak bisa tersimpan

### Cara untuk mereplikasi errornya

1. masuk admin
2. klik pengaturan 
3. klik shorcut
4. buat shortcut menggunakan query manual 
5. klik simpan

### Hasil yg diharapkan

.

### Tangkapan layar dan log error

![121](https://github.com/user-attachments/assets/a24f02ca-1a5a-459d-a7a4-ae1b910c3314)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

terbaru

### Tema Yang Digunakan

.

### Informasi tambahan

.

**Comment by eddieridwan** [comment]
@mranca fitur query manual akan segera dihapus, karena melanggar kaidah2 keamanan data. Sekiranya ada pencarian yang belum tersedia, silakan buat issue terpisah. Seperti biasa pastikan issue tersebut menjelaskan alasan dan contoh yg lengkap.

cc @andifahruddinakas

**Comment by mranca** [comment]
@eddieridwan siap pak

**Comment by andifahruddinakas** [comment]
Duplicate of https://github.com/OpenSID/OpenSID/issues/8753
