### ISSUE TITLE
Bug/error: surat sistem tidak lengkap

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8761]
### Jelaskan error yg dialami

surat sistem tidak lengkap

### Cara untuk mereplikasi errornya

1. Layanan Surat 
2. Pengaturan Surat
3. Template Surat Sistem

### Hasil yg diharapkan

sudah sistem lengkap

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/35cb9c6f-b66e-4188-9e82-30ef1f6b555c)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Versi 2411.0.2-premium

### Informasi tambahan

Laporan Desa Harjo Mulyo
Pak @jefri

**Comment by rgrahardi** [comment]
Database Terlampir.

**Comment by andifahruddinakas** [comment]
> Database Terlampir.

Untuk menambahkan ulang surat sistem cukup jalankan ulang migrasinya dari awal.

**Comment by rgrahardi** [comment]
berhasil migrasi mas tetap tidak tampil mas surat sistemnya mas @andifahruddinakas 
![image](https://github.com/user-attachments/assets/c86564a8-521a-4a4b-9c44-dc92da882c4e)

**Comment by rgrahardi** [comment]
![image](https://github.com/user-attachments/assets/ccdcdc59-c442-40ee-9ad6-1273ab177602)

**Comment by andifahruddinakas** [comment]
mas @pandigresik, cek
- [ ] bagian ini perlu dibalik, jadi yang jadi data awal yakni data yg ada pada file json nya.
![image](https://github.com/user-attachments/assets/b708b3af-c941-4dd3-913f-e19df9780d6d)

- [ ] dan diganti atau ditambahkan jika belum ada.
- [ ] terapkan juga disurat dinas

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/4300, dan akan masuk di v2412.0.1
