### ISSUE TITLE
Bug/error: tidak bisa tinjau surat 

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8762]
### Jelaskan error yg dialami

tidak bisa tinjau surat sistem dan desa

### Cara untuk mereplikasi errornya

1. Layanan Surat
2. Pengaturan Surat
3. Klik salah satu template surat sistem
4. Klik Tinjau PDF

### Hasil yg diharapkan

Dapat Tinjau dan Cetak surat

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/727d04ef-55db-48aa-b825-8cbbd2b5ca1f)

Tidak ada log error
![image](https://github.com/user-attachments/assets/7c711795-c451-404e-8253-15258cd6f337)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Versi 2411.0.2-premium

### Informasi tambahan

Laporan Nagari Andaleh
pak @syaiful

**Comment by rgrahardi** [comment]
Database terlampir

**Comment by andifahruddinakas** [comment]
> Database terlampir

Sdah cek di beputar?

**Comment by pandigresik** [comment]
tidak ada petunjuk apapun dari informasi issue ini

**Comment by pandigresik** [comment]
> Database terlampir

saya cek di https://drive.google.com/drive/folders/1lCts6xlq-SNwXDNjodwHFMML8ae4aank tidak ada

**Comment by rgrahardi** [comment]
mohon ditunggu ya mas @pandigresik sedang diproses

**Comment by pandigresik** [comment]
https://github.com/user-attachments/assets/8feb9d39-2506-4d7f-bc0a-732919b5b536

aman

**Comment by pandigresik** [comment]
saya coba aman saja, dengan database desa

**Comment by rgrahardi** [comment]
kalau di server tidak bisa ya mas @pandigresik mas @andifahruddinakas 
![image](https://github.com/user-attachments/assets/7c3a0c7c-b9e1-4523-b3ee-2d54042321c0)

**Comment by andifahruddinakas** [comment]
> kalau di server tidak bisa ya mas @pandigresik mas @andifahruddinakas ![image](https://private-user-images.githubusercontent.com/55429781/389429520-7c3a0c7c-b9e1-4523-b3ee-2d54042321c0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1MjIwNDgsIm5iZiI6MTczMjUyMTc0OCwicGF0aCI6Ii81NTQyOTc4MS8zODk0Mjk1MjAtN2MzYTBjN2MtYjllMS00NTIzLWIzZWUtMmQ1NDA0MjMyMWMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI1VDA4MDIyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyNDAwZTFlZDc5OTgzZTU1ZDAwODc3NDdjYzdmZWQwMDU5NmVkNjkxYjMwYzQzM2EyNDAxZWQ2YmNiMGZhN2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.lji28qbzDAtodDGiXbzjSHb2hERXzVEzewkv-s0L_Sg)

ini diserver

![image](https://github.com/user-attachments/assets/8a9eb50f-8e13-4a2d-8085-d57827e855e4)

**Comment by pandigresik** [comment]
Ketika saya coba di local, dengan database desa tersebut, pratinjau berjalan normal. Adakah yang berhasil melakukan replikasi case tersebut ?

**Comment by rgrahardi** [comment]
di berputar memang aman mas @andifahruddinakas saya beri label siapPakai1 mas karena hanya terjadi di desa tersebut mas, sesuai arahan mas @vickyrolanda waktu pertemuan rutin programmer mas @andifahruddinakas

**Comment by eddieridwan** [comment]
@pandigresik bisa uji di devsiappakai. Server itu memang untuk melakukan testing terkait SiapPakai.

**Comment by pandigresik** [comment]
> @pandigresik bisa uji di devsiappakai. Server itu memang untuk melakukan testing terkait SiapPakai.

apakah ini artinya bahwa sebuah bug bisa dianggap terverifikasi ketika terjadi di berputar dan devsiappakai ? Karena seingat saya sebelumnya acuan kita adalah berputar

**Comment by eddieridwan** [comment]
Berputar hanya satu alat pembantu. Kalau jelas disebut di SiapPakai dan tidak di berputar, tentunya perlu diverifikasi di SiapPakai. Karena itu tanggung jawab kita. Juga kalau di Database Gabungan yg juga tanggung jawab kita. Penggunaan berputar hanya satu cara. Bukan bukti tidak ada masalah. Ingat, kalau masalah itu terjadi di data desa pelapor, kita juga harus telurusi sampai tuntas menggunakan data desa tersebut. Itu target kita. Mengatasi bug sampai tuntas, sehingga tidak dilaporkan lagi.

**Comment by rgrahardi** [comment]
mohon maaf pak @eddieridwan mas @pandigresik tadi saya dan pengguna hanya melakukan cek halaman /periksa perbaiki data dan hapus cache saya belum melakukan migrasi setelah saya migrasi berhasil dan aman

![image](https://github.com/user-attachments/assets/4ace0e10-9016-4543-a478-d2c56b09b703)

**Comment by rgrahardi** [comment]
sudah diperbaiki menggunakan fitur migrasi semua dan migrasi terbaru
![image](https://github.com/user-attachments/assets/e4014349-1755-4068-9d25-3392d5bc9759)
