### ISSUE TITLE
Bug/error: Surat Keterangan Untuk Nikah Warga Non Muslim

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8763]
### Jelaskan error yg dialami

1. Surat Keterangan Untuk Nikah Warga Non Muslim calon pengantin dari penduduk luar desa tidak tampil
2. kode pos dilampiran kosong

### Cara untuk mereplikasi errornya

1. Layanan Surat
2. Cetak Surat
3. Pilih Surat Surat Keterangan Untuk Nikah Warga Non Muslim
4. Klik Buat Surat Surat
5. Pengantin Pria Pilih Penduduk Luar Desa 

### Hasil yg diharapkan

1. Pada Lampiran Data Pengatin Pria dari Luar Desa terisi
2. Kode Pos terisi otomatis dari OpenSID

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/f1362322-086d-4a97-a723-7febea84cc0d)
![image](https://github.com/user-attachments/assets/6c07de83-5127-468c-bb27-be71757838e7)
![image](https://github.com/user-attachments/assets/0e6f43bd-e4a4-4387-b44f-e72aee9f6316)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

OpenSID v2411.0.2-premium

### Informasi tambahan

Laporan Desa Gunung Salak
pak @sumerta

**Comment by andifahruddinakas** [comment]
Cek diberputar sama
![image](https://github.com/user-attachments/assets/1abf0f35-decb-48c6-b437-acc4eb6454d8)

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/4299, sesuai dengan masalah yang disebutkan pada issue.
