### ISSUE TITLE
Teknis : Penambahan Nama pada log KK yang ganda

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8765]
### Apa kekurangan yg ingin diatasi?

Tidak terdapat nama pada log ganda pada keluarga

cara replikasi

1. domaindesa/periksa

![image](https://github.com/user-attachments/assets/da8c94ed-6d45-483f-8539-b7405c8ded73)

### Jelaskan solusi yg diinginkan

Penambahan Nama pada log KK yang ganda

### Apakah ada alternatif lain

0

### Untuk versi OpenSID mana

Versi 2412.0.0-premium

### Informasi tambahan

-

**Comment by andifahruddinakas** [comment]
mas @rgrahardi : 

- [ ] kasus seperti ini databasenya bisa dilampirkan
- [ ] jika dilihat, untuk data keluarga ganda namun namanya tidak ada disebabkan pada no kk tsb sudah tidak aktif (sudah dilakukan pecah kk)

**Comment by rgrahardi** [comment]
baik mas @andifahruddinakas untuk kk nya terdapat log ganda dan sudah di pilih salah satu log terbaru, terimakasih informasinya mas akas, saya mengira tadi belum ada kolom untuk nama nya mas akas. issuenya saya tutup mas
