### ISSUE TITLE
Bug/error: Nama bulan tidak Seragam di tampilan Anjungan #footer

### ISSUE THREAD

**Issue by ilhamwahyu-ni** [OpenSID/OpenSID#8767]
### Jelaskan error yg dialami

-

### Cara untuk mereplikasi errornya

akses anjungan-mandiri

### Hasil yg diharapkan

seragam dengan nama bulan di artikel

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/b7732640-4cd2-4aec-b9b8-d52bcd4cbc9b)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

bux fix

**Comment by ilhamwahyu-ni** [comment]
izin Perbaiki mas @andifahruddinakas 🙏

**Comment by ilhamwahyu-ni** [comment]
mas @andifahruddinakas  izin juga yang lalinnya 

![image](https://github.com/user-attachments/assets/35a21b11-8c5e-4c42-abbb-febe0f335813)

**Comment by andifahruddinakas** [comment]
> mas @andifahruddinakas izin juga yang lalinnya
> 
> ![image](https://private-user-images.githubusercontent.com/85351181/390949842-35a21b11-8c5e-4c42-abbb-febe0f335813.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4NTAxOTgsIm5iZiI6MTczMjg0OTg5OCwicGF0aCI6Ii84NTM1MTE4MS8zOTA5NDk4NDItMzVhMjFiMTEtOGM1ZS00YzQyLWFiYmItZmViZTBmMzM1ODEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI5VDAzMTEzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3ODc2ZmE3MDk0OTE3NTlmMDk0ZmIzM2NlMDM1ODQ5MWVjMGE3MGE4ZmQ1ZGU3OGM1NzVmN2UxYWVhYWY2YmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.DpaESCOWwcdn4JyuyRzeFZawVe9sUWXqUdyhS5z4GuE)

Untuk yg jv.php jangan diganti karena itu bawaan library carbonnya dan kita tidak gunakan lang tsb.

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/4304
