### ISSUE TITLE
Permintaan fitur: Tambahkan Inputan NIK untuk pemilik Tanah dari Luar Desa

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8769]
### Apa kekurangan yg ingin diatasi?

Tidak ada inputan NIK pada pemilik Tanah dari Luar Desa pada C-Desa

### Jelaskan solusi yg diinginkan

Tambahkan Inputan NIK untuk pemilik Tanah dari Luar Desa

![image](https://github.com/user-attachments/assets/712c5e58-e45a-407f-a275-3c32f360bbb9)

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

Versi 2501.0.0-premium

### Informasi tambahan

Usulan Desa Cilukrak Cirebon
Pak @B_Rosyad

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/4311
