### ISSUE TITLE
Bug/error: Nama Pemilik Awal di Tambah Daftar Persin Tidak Muncul

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8770]
### Jelaskan error yg dialami

Nama Pemilik Awal dari Penduduk Luar di Tambah Daftar Persin Tidak Muncul

![image](https://github.com/user-attachments/assets/c3408df2-fc97-45f9-bde3-d57102615fba)

Nama Arina penduduk luar tidak muncul dan tidak bisa di cari

![image](https://github.com/user-attachments/assets/0b9f8cef-7760-48ef-a02f-a74bf288a0c7)

Penduduk Desa Namanya Muncul Di pilihan pemilik Tanah.

### Cara untuk mereplikasi errornya

1. Tambah C-Desa 
2. Pemilik Tanah dari penduduk luar
3. simpan

1. Tambah Daftar Persil
2. Pilihan Pemilik Tanah dari penduduk Luar tidak muncul

### Hasil yg diharapkan

Nama Pemilik tanah dari penduduk luar muncul di Pilihan Tambah data Persil

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Versi 2412.0.1-premium

### Informasi tambahan

Usulan Desa Cilukrak Cirebon
Pak @B_Rosyad

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/4309
