### ISSUE TITLE
Permintaan fitur: Rekapitulasi Anak 2-6 Tahun

### ISSUE THREAD

**Issue by afri18** [OpenSID/OpenSID#8771]
### Apa kekurangan yg ingin diatasi?

Menu Kesehatan>Stunting(Posyandu)>Pemantauan> ada klasifikasi anak 2-6 tahun
Menu Kesehatan>Stunting(Posyandu)>Rekapitulasi> tidak ada klasifikasi anak 2-6 tahun

### Jelaskan solusi yg diinginkan

Harusnya setiap ada pemantauan di samakan laporan klasifikasinya dengan Rekapitulasi/Laporan

### Apakah ada alternatif lain

Buat juga Rekapitulasi untuk anak 2-6 tahun
![image](https://github.com/user-attachments/assets/4b2d6ad4-7407-4962-8ce5-63b57cd65794)

Rekapitulasi
![image](https://github.com/user-attachments/assets/92f7326f-dd50-44d5-803e-7c23c2cfba68)

### Untuk versi OpenSID mana

2501.0.0

### Informasi tambahan

Usahakan setiap ada kegiatan Pemantauan ada laporannya

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/4332
