### ISSUE TITLE
Bug/error: Status Pemesanan Tidak Sesuai 

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8775]
### Jelaskan error yg dialami

Status Pemesanan Tidak Aktif padahal Pemesanan sudah di input di Layanan.

![image](https://github.com/user-attachments/assets/30ef69e0-1f4d-4f97-8032-26bf82c0ac2e)

### Cara untuk mereplikasi errornya

1. Info Desa
2. Layanan Pelanggan

### Hasil yg diharapkan

setiap Pemesanan kolomnya terpisah, jangan disatukan seperti ini 

![image](https://github.com/user-attachments/assets/78256ba0-0095-4d2c-babb-2153526db839)

agar lebih jelas pemesanan mana yang tidak aktif

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Versi 2412.0.1-premium

**Comment by andifahruddinakas** [comment]
mas @rgrahardi, cek response layanan pesanan tsb tidak aktif.

![image](https://github.com/user-attachments/assets/97603fd6-2317-43f2-86e6-94a2fb01c888)

Yang bisa diperbaiki untuk issue ini, yakni pemisahan pemesanan yang digabungkan.
![image](https://github.com/user-attachments/assets/2d7ac374-c668-424c-ad0f-8debced866da)

Untuk respose dari layanan yang tidak sesuai perlu diperbaiki dilayanan itu sendiri.

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/4315
