### ISSUE TITLE
Bug/error: Sub Menu Urutan tidak berfungsi

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8779]
### Jelaskan error yg dialami

Pengurutan Sub Menu Tidak berfungsi

### Cara untuk mereplikasi errornya

1. Admin web
2. menu
3. menu utama
4. sub menu

### Hasil yg diharapkan

Pengurutan Sub menu berfungsi dengan baik 

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/6b93ef0d-bfa3-4c16-9129-bcd57b9b6174)
![image](https://github.com/user-attachments/assets/cedbd81a-75ae-43a7-b442-425a90a24840)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Versi 2412.0.1-premium

**Comment by andifahruddinakas** [comment]
Duplicate of https://github.com/OpenSID/OpenSID/issues/8776
