### ISSUE TITLE
Bug: Error database pada menu statistik E-KTP

### ISSUE THREAD

**Issue by xnuser** [OpenSID/OpenSID#878]
Pada statistik, ketika kita melihat data statistik kepemilikan E-KTP disana tertera berapa banyak warga yang belum di input datanya, ketika data itu kita klik maka terjadi error database.

Klik ini:
![screenshot_15](https://user-images.githubusercontent.com/36754277/37875610-26a02952-306c-11e8-9d9a-184d9c89fc68.png)

Errornya  gini:
![screenshot_16](https://user-images.githubusercontent.com/36754277/37875611-26b86e68-306c-11e8-9d7e-d53e9934c5b8.png)

**Comment by balongbesuk** [comment]
tambahan, hampir semua submenu statistik penduduk ketika data belum mengisi di tekan, muncul error tersebut, sudah saya cek di website demo,

**Comment by eddieridwan** [comment]
Sdh dicommit ke master sekalian dengan perbaikan pada beberapa tautan lainnya di bilangan statistik.
