### ISSUE TITLE
Teknis : Migrasi semua

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8782]
### Jelaskan error yg dialami

setiap lakukan migrasi semua, struktur data di table tweb_surat_format tidak sesuai format json yang valid. 

1. seharusnya "[\"2\",\"3\",\"1\"]"  menjadi [2,3,1]
2. isian null harusnya bukan berupa tulisan null atau pun "null"

![photo_2024-12-03_13-39-04](https://github.com/user-attachments/assets/fc2f5ee5-7d64-4786-ba60-3394ed2ff58d)

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Versi 2412.0.1-premium

**Comment by pandigresik** [comment]
saya coba sudah sesuai hasilnya 

https://github.com/user-attachments/assets/0ad6d341-8e16-48f9-bd61-9c355fdc05f9

**Comment by pandigresik** [comment]
kalau melihat data di kode_isian juga sudah sesuai untuk format penyimpanannya
`select syarat_surat,nama, kode_isian from tweb_surat_format where syarat_surat is not null and kode_isian is not null`
![image](https://github.com/user-attachments/assets/5b6cc64b-f297-4253-a279-efbc36e64490)

**Comment by andifahruddinakas** [comment]
mas @pandigresik, perbaiki yg ini saja mas:
![image](https://github.com/user-attachments/assets/58a19bac-3940-43b1-9c8d-29118f27d111)

Cara replikasi : 

1. Buat surat baru
2. Isi datanya dan Ceklist syaratnya, kemudian simpan
![image](https://github.com/user-attachments/assets/dff4fe39-36c2-4fd2-826a-29b05f54dbca)

3. Lakukan edit surat yg diubah tadi, kemudian hapus syaratnya. nanti yg tersimpan adalah 'null' (string) buka null (dari database)

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/4341
