### ISSUE TITLE
Bug/error: Shortcut Lembaga tidak tampil

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8783]
### Jelaskan error yg dialami

Shortcut Lembaga tidak tampil

### Cara untuk mereplikasi errornya

1. Pengaturan
2. Shortcut
3. Tambah
4. Pilih Query Lembaga
5. simpan

### Hasil yg diharapkan

Query Lembaga muncul di beranda

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/8486c124-5c47-4c7c-9783-db86d22c6f24)
![image](https://github.com/user-attachments/assets/817ba349-7477-4590-bd3c-0d39b6d4ee5f)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Versi 2412.0.1-premium

**Comment by andifahruddinakas** [comment]
Cek juga, link dari shorcutnya. Misalkan link dokumen penduduk harusnya mengarah ke modul penduduk.

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/4317
