### ISSUE TITLE
Teknis : Update Collection OpenSID

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8785]
### Apa kekurangan yg ingin diatasi?

Sesuai arahan mas akas di pertemuan Pasca Rilis buat issue di OpenSID perlu menyesuaikan versi colection terbaru mariadb karena yang sekarang tidak di suport

### Jelaskan solusi yg diinginkan

opensid perlu menyesuaikan versi colection terbaru mariadb karena yang sekarang tidak di suport

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

Versi 2412.0.1-premium

**Comment by andifahruddinakas** [comment]
`ERROR - 2024-12-01 14:57:37 --> You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'utf8mb3_general_ci' at line 1<br>`

pada mariadb 11.5.2 sudah tidak tersedia utf8_general_ci
![image](https://github.com/user-attachments/assets/606b22df-f99e-45f8-805a-3659ab84c75c)

dimana secara default CI3 menggunakan utf8_general_ci
![image](https://github.com/user-attachments/assets/e9f82350-9c83-4d38-a4d4-fa489a93c7ba)

**Comment by andifahruddinakas** [comment]
Perlu diperbaiki : 
- [ ] Install Awal
- [ ] Periksa (collection)
- [ ] Cek migrasi lama terkait ubah collection

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/4320
