### ISSUE TITLE
SHORTCUT DENGAN QUERY "JUMLAH LEMBAGA" TIDAK MUNCUL PADA BERANDA

### ISSUE THREAD

**Issue by pujocahyono** [OpenSID/OpenSID#8786]
### Jelaskan error yg dialami

SHORTCUT DENGAN QUERY "JUMLAH LEMBAGA" TIDAK MUNCUL PADA BERANDA

### Cara untuk mereplikasi errornya

BUAT SHORTCUT DENGAN QUERY "JUMLAH LEMBAGA"

### Hasil yg diharapkan

KEMBALI NORMAL

### Tangkapan layar dan log error

![Cuplikan layar 2024-12-04 092002](https://github.com/user-attachments/assets/9d79d552-8def-43ea-888a-d69be436112e)

HASILNYA:
![Cuplikan layar 2024-12-04 092037](https://github.com/user-attachments/assets/ea6000c8-171e-495a-9941-276a820275f9)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2412.0.0

**Comment by andifahruddinakas** [comment]
Duplicate of https://github.com/OpenSID/OpenSID/issues/8783
