### ISSUE TITLE
Bug/error: Ubah Suplemen keterangan tooltip tidak sesuai

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8787]
### Jelaskan error yg dialami

Ubah Suplemen keterangan tooltip tidak sesuai

![image](https://github.com/user-attachments/assets/1ebce13a-cdbc-4745-bce0-7c417482fb44)

### Cara untuk mereplikasi errornya

1. Kependudukan
2. Suplemen
3. Arahkan Kursor ke Tombol Ubah suplemen

### Hasil yg diharapkan

-

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Versi 2412.0.1-premium

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/4316
