### ISSUE TITLE
Bug/error: Penduduk status mati masih tampil pada peta

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8788]
### Jelaskan error yg dialami

Penduduk status mati masih tampil pada peta

![image](https://github.com/user-attachments/assets/217652e2-603a-41fb-a5d9-db9260e32542)

### Cara untuk mereplikasi errornya

1. Kependudukan
2. Penduduk
3. Ubah status dasar menjadi mati
4. cek di peta penduduk masih muncul

### Hasil yg diharapkan

penduduk mati tidak muncul lagi di peta

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/55b36767-1b45-4675-b716-45b172377cf9)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Versi 2412.0.1-premium

### Informasi tambahan

Laporan Desa Rarang Selatan
Pak @Muhammad

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/4318
