### ISSUE TITLE
Teknis : Ubah semua data anggota keluarga pada anggota

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8789]
### Apa kekurangan yg ingin diatasi?

  di menu keluarga ada fitur tentukan titik koordinate keluarga , ketika filter penduduk muncul semua keluarga titik koordinatenya

![image](https://github.com/user-attachments/assets/5bbd9452-2397-4310-8dbf-e82ed6077ebb)

### Jelaskan solusi yg diinginkan

Ubah semua data anggota keluarga pada anggota, sehingga pada peta untuk penduduknya tampil

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

Versi 2412.0.1-premium

### Informasi tambahan

Desa Rarang Selatan
Pak @Muhammad

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/4326
