### ISSUE TITLE
Bug OpenSID

### ISSUE THREAD

**Issue by bizril** [OpenSID/OpenSID#879]
Bug OpenSID :
=============
1. 	Bisa menambahkan RT tanpa terlebih dahulu mengisi RW
2. 	Tidak ada fasilitas Pilih semua - Hapus pada data RT, harus dihapus satu persatu
3. 	Setelah menghaspus salahsatu RT kembali halaman input RW padahal belum semua RT dihapus
4. 	Jika RW ditambahkan lebih dari 1 x keluar halaman database Error harusnya ada pesan bahwa RW tersebut sudah ada dan kembali ke halaman input RW
	Hal serupa muncul juga muncul di halaman input RT dengan kasus yang sama
5.	Menu peta masih Error 
6. 	Login form turun naik saat diisi karena ada form data cache, sebaiknya dimatikan
7.	Terjadi overlap antara gambar logo dan judul situs (nama Desa pada header wrap), harusnya ada opsi logo atau text
	
Catatan : browser yang digunakan Google Chrome Version 64.0.3282.186 (Official Build) (32-bit)

Sebagai usulan untuk mempercepat proses input agar tidak loading page saat input, disarankan menggunakan jQuery Ajax lebih cepat daripada submit form

**Comment by eddieridwan** [comment]
@bizril : terima kasih atas laporannya. Tetapi harap mengikuti pedoman https://github.com/OpenSID/OpenSID/wiki/Pengelolaan-Masalah-dan-Permintaan-Perbaikan-SID.

Satu issue supaya hanya berisi satu masalah -- karena hanya akan ditangani satu-per-satu. Lampirkan tampilan layar yg menjelaskan permasalahannya. 
Silakan tulis ulang.

Kalau anda programmer, silakan sekalian kirim solusinya melalui pull request: https://github.com/OpenSID/OpenSID/wiki/Panduan-mengirimkan-perubahan-repo-OpenSID.

Dan bergabung di https://opensid.slack.com untuk diskusi teknis.

**Comment by eddieridwan** [comment]
@bizril harap lihat comment di atas. Kalau masalahnya masih ada, mohon dibuatkan issue terpisah untuk setiap masalah.

**Comment by afa28** [comment]
Silahkan buat issue terpisah untuk setiap masalah, beberapa dr issue di atas sudah diperbaiki di versi terbaru.
