### ISSUE TITLE
Teknis : Kategori ini sudah tidak ada

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8790]
### Apa kekurangan yg ingin diatasi?

Kategori ini sudah tidak ada
![image](https://github.com/user-attachments/assets/547bc8f2-c6a2-43ed-aba7-b119fe6c18de)

### Jelaskan solusi yg diinginkan

-

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

Versi 2412.0.1-premium

**Comment by andifahruddinakas** [comment]
Link tsb berada pada halaman tema
![image](https://github.com/user-attachments/assets/b86ec7ad-31ed-43ae-992f-9b6a5d5124f7)

Jadi untuk perbaikannya dilakukan pada masing2 tema bawaan.

Solusi :
- [ ] untuk artikel kategori statis untuk saat ini jangan ditampilkan.

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/4328
