### ISSUE TITLE
Bug/error: C-Desa tidak tampil

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8792]
### Jelaskan error yg dialami

Tambah C-Desa berhasil data tidak muncul

![image](https://github.com/user-attachments/assets/df533d61-9db2-4ab8-819b-d3ebb28c3899)
![image](https://github.com/user-attachments/assets/06791da5-8ad9-4300-a5f1-d54c9788af7d)

Log Error

Severity: error --> Exception: SQLSTATE[42000]: Syntax error or access violation: 1055 'berp_opensid.cdesa.config_id' isn't in GROUP BY (Connection: default, SQL: select `cdesa`.*, `cdesa`.`id` as `id_cdesa`, `cdesa`.`created_at` as `tanggal_daftar`, `cdesa_penduduk`.`id_pend`, `tweb_penduduk`.`nik

### Cara untuk mereplikasi errornya

1. Pertanahan
2. C-Desa

### Hasil yg diharapkan

C-Desa bisa normal kembali

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Versi 2410.0.2-premium

### Informasi tambahan

Laporan Desa Langon Sari
Pak @Surya

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/4323
