### ISSUE TITLE
Teknis : Menu Inventaris tidak muncul

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8793]
### Apa kekurangan yg ingin diatasi?

Menu Inventaris tidak muncul

![image](https://github.com/user-attachments/assets/21499506-d5de-45d1-92da-853d09b27b7f)

![image](https://github.com/user-attachments/assets/062427bc-81a9-4dd7-a2c1-692a1204602a)

![image](https://github.com/user-attachments/assets/4629f46b-6281-491b-ab56-eeaa38067cab)

### Jelaskan solusi yg diinginkan

-

### Apakah ada alternatif lain

-

### Untuk versi OpenSID mana

Versi 2412.0.1-premium

### Informasi tambahan

-

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/4330
