### ISSUE TITLE
Bug/error: Belum urutnya tahun sortiran dari tahun terkecil/terbesar ketika memilih tahun produk hukum di tampilan web

### ISSUE THREAD

**Issue by mah-mudi** [OpenSID/OpenSID#8794]
### Jelaskan error yg dialami

Belum urutnya tahun sortiran dari tahun terkecil/terbesar ketika memilih tahun produk hukum di tampilan web

### Cara untuk mereplikasi errornya

tampilan web pd produk hukum

### Hasil yg diharapkan

tahun sortiran dari tahun terkecil/terbesar ketika memilih tahun produk hukum di tampilan web

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/a4a63808-065f-49ed-82c3-5e4d68cbcc6f)

![image](https://github.com/user-attachments/assets/267dba10-48f8-451d-947f-d61f20f96fd8)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

22.11.01

### Tema Yang Digunakan

silir

### Informasi tambahan

https://berputar.opendesa.id/peraturan-desa

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/4325
