### ISSUE TITLE
Bug/error: Perbaikan isian saksi pada surat keterangan kelahiran

### ISSUE THREAD

**Issue by typevant** [OpenSID/OpenSID#8795]
### Jelaskan error yg dialami

pada saat akan membuat surat keterangan kelahiran, isian data saksi tidak muncul

### Cara untuk mereplikasi errornya

1. Halaman surat
2. Pilih surat keterangan kelahiran
3. lihat pada bagian isian saksi

### Hasil yg diharapkan

isian saksi untuk dapat ditampilkan

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/ca89b2b8-aec9-41ff-bcd6-a19f84e14688)

### Rilis Versi OpenSID

Rilis Umum

### Versi OpenSID

v2412.0.0

### Tema Yang Digunakan

DeNava

**Comment by andifahruddinakas** [comment]
pak @typevant, bisa duplikasi ke https://berputar.opendesa.id/surat/form/sistem-surat-keterangan-kelahiran

![image](https://github.com/user-attachments/assets/c2b76262-b3a6-4002-b8d8-d7cae34193b4)
