### ISSUE TITLE
sediakan pilihan untuk jenis query jumlah surat masuk dan surat keluar 

### ISSUE THREAD

**Issue by mranca** [OpenSID/OpenSID#8797]
### Apa kekurangan yg ingin diatasi?

saat ini belum tersedia fitur jenis query untuk jumlah surat masuk dan surat keluar 

### Jelaskan solusi yg diinginkan

tambahkan query untuk jenis surat masuk dan surat keluar agar memudahkan saat membuat shurcut pada halaman dashboard, query surat masuk dan keluar   terletak di bagian 

1. buka halaman admin
2. buka buku administrasi  desa
3. klik administrasi umum 
4. buku agenda surat keluar 
5. buku agenda surat masuk 

### Apakah ada alternatif lain

.

### Untuk versi OpenSID mana

Terbaru

### Informasi tambahan

.

**Comment by andifahruddinakas** [comment]
Tambahkan untuk : 

- [ ] Buku Peraturan di Desa (Semua, Aktif, Tidak Aktif)
- [ ] Buku Keputusan Kepala Desa (Semua, Aktif, Tidak Aktif)
- [ ] Buku Inventaris dan Kekayaan Desa (Semua)
- [ ] Buku Pemerintah Desa (Semua, Aktif, Tidak Aktif)
- [ ] Buku Tanah Kas Desa (Semua)
- [ ] Buku Tanah di Desa (Semua)
- [ ] Buku Agenda - Surat Keluar (Semua)
- [ ] Buku Agenda - Surat Masuk (Semua)
- [ ] Buku Ekspedisi (Semua)
- [ ] Buku Lembaran Desa Dan Berita Desa  (Semua, Aktif, Tidak Aktif)

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/4329

**Comment by mranca** [comment]
Mantap terimakasih
