### ISSUE TITLE
Bug/error: Kolom Checkbok dan tombol hapus masih ada pada hak akses ubah

### ISSUE THREAD

**Issue by ilhamwahyu-ni** [OpenSID/OpenSID#8798]
### Jelaskan error yg dialami

-

### Cara untuk mereplikasi errornya

-

### Hasil yg diharapkan

normal

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/edc153a1-1434-46d0-a84d-6306ec6749fa)
====================================================================
![image](https://github.com/user-attachments/assets/318b99f6-dc36-4b80-a76c-a2a1b3ed2702)
==================================================================
![image](https://github.com/user-attachments/assets/7dcded51-7d40-4859-b101-4aa711cda6dc)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

bux fix

**Comment by ilhamwahyu-ni** [comment]
izin perbaiki mas @andifahruddinakas

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/4327/

**Comment by ilhamwahyu-ni** [comment]
mas @andifahruddinakas pas di cek masih ada yang teritinggal mas.. hak ubah masih ada tombol hapus di komentar

![image](https://github.com/user-attachments/assets/8a707152-3291-4952-a92c-cc91ff85ca0b)

izin lansung buat PR nya ya mas🙏
