### ISSUE TITLE
Bug/error: Filter Komentar

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/OpenSID#8799]
### Jelaskan error yg dialami

![image](https://github.com/user-attachments/assets/011695bc-c6a8-46b9-9e66-ff42f55fb359)

![image](https://github.com/user-attachments/assets/9af63f88-67da-4851-b3aa-96297a79dfc4)

![image](https://github.com/user-attachments/assets/bc1323cc-9ab1-4143-8741-c9940c5f7b4e)

### Cara untuk mereplikasi errornya

1. Klik Komentar
2. Filter Aktif, Tidak Aktif, Semua

### Hasil yg diharapkan

Usulan Default Filter adalah Filter Semua

### Tangkapan layar dan log error

-

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Versi 2412.0.1-premium

### Tema Yang Digunakan

-

### Informasi tambahan

-

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/4336
