### ISSUE TITLE
### di Data Suplemen Paging Page tidak jalan

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#880]
DI Data Suplemen untuk Paging Page tidak jalan 
![screenshot 2018-03-26 13 42 39](https://user-images.githubusercontent.com/25834335/37888804-e13dabce-30fb-11e8-8f93-9af526877cea.png)

**Comment by afa28** [comment]
Diversi terbaru sudah solved
