### ISSUE TITLE
Bug/error: Install baru premium, password sudah sesuai dengan keterangan tapi tetap gagal simpan

### ISSUE THREAD

**Issue by ruririzal** [OpenSID/OpenSID#8800]
### Jelaskan error yg dialami

Install baru premium, pembuatan akun pertama, password sudah sesuai dengan keterangan yg muncul tapi tetap gagal simpan 

### Cara untuk mereplikasi errornya

1. instalasi baru premium
2. setup koneksi db
3. ketika di halaman pembuatan akun pertama muncul error

### Hasil yg diharapkan

keterangan diperbaiki/sistem diperbaiki

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/2ac69f2e-8cc0-4ea7-82a6-dd782c18fa70)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2412.0.1

**Comment by ruririzal** [comment]
@vickyrolanda @andifahruddinakas

**Comment by ruririzal** [comment]
donjo-app\controllers\Install.php

line 377

$this->form_validation->set_message('syarat_sandi', 'Harus 8 sampai 20 karakter dan sekurangnya berisi satu angka dan satu huruf besar dan satu huruf kecil dan satu karakter khusus');

**Comment by andifahruddinakas** [comment]
> donjo-app\controllers\Install.php

Harus ada 1 simbol

![image](https://github.com/user-attachments/assets/f59a6dac-64d1-467e-9164-27e4c833d47e)

Keterangannya perlu diganti

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/4337
