### ISSUE TITLE
Duplikasi Fungsi Log

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#8801]
![image](https://github.com/user-attachments/assets/286e7cea-2963-4fcf-99bf-30e53df465b7)

Terdapat duplikasi untuk melaporkan log pada OpenSID, yakni log dari CI3 dan Laravel. Sehingga log yg tercipta dari laravel tidak terbaca pada modul info_sistem > log karen memiliki format yang berbeda.
![image](https://github.com/user-attachments/assets/a3a5bb18-65aa-48d6-8aa2-5a3bfedce095)

SOLUSI : 

- [ ] solusi 1: yang bisa diterapkan saat ini yakni menggunakan 1 format yang sama dimana digunakan untuk CI3 dan Laravel.
- [ ] solusi 2: gunakan format log laravel. ganti semua log_message(), menggunakan logger->xxx(). tapi karena terlalu banya ubahan akan menyusahkan.

**Comment by pandigresik** [comment]
Sudah dikerjakan melalui PR https://github.com/OpenSID/premium/pull/4338
