### ISSUE TITLE
Sisa View CI3

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#8807]
![image](https://github.com/user-attachments/assets/fb41db4c-46e4-4d31-87f6-1d80b3acff2b)

LAKUKAN : 

- [ ] hapus view yang sudah tidak digunakan
- [ ] sesuaiakan view yang belum dikonversi, kemudian hapus
- [ ] biarkan view yang masih digunakan oleh modul yang akan dihapus.

**Comment by andifahruddinakas** [comment]
Lanjutan dari PR https://github.com/OpenSID/premium/pull/4210

**Comment by agungsugiarto** [comment]
catatan yang belum bisa dihapus

- covid19 modul belum dihapus
- file print/headjs.php masih digunakan di modul covid19
- file global/format_cetak.php menginclude file print/headjs.php
- file global/confirm_delete.php masih digunakan di modul covid19
- file global/dialog_cetak.php masih digunakan di modul covid19
- file global/paging.php masih digunakan di modul covid19
- file global/validasi_form.php masih digunakan di modul covid19
