### ISSUE TITLE
di Data Suplemen Seharusnya masyarakat yang sudah terdata tidak muncul lagi

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#881]
di Data Suplemen Seharusnya masyarakat yang sudah terdata tidak muncul lagi waktu tambah warga terdata seperti di menu Bantuan
![screenshot 2018-03-26 14 19 38](https://user-images.githubusercontent.com/25834335/37889868-eff8b5aa-3100-11e8-8a7b-755446a7c76c.png)

**Comment by afa28** [comment]
Versi terbaru sudah solved
