### ISSUE TITLE
ERROR 500 

### ISSUE THREAD

**Issue by lwiradarma** [OpenSID/OpenSID#8812]
### Jelaskan error yg dialami

Setelah selsesai update opensid versi terbaru yaitu versi 24.12 saya mengalami error 500 dengan keterangan unable to load the requested file : head_tags_front.php

### Cara untuk mereplikasi errornya

1. Update opensid versi 24.12
2. Selseai
3. Tes akses situs web
4. Lalu mengalami error 500

### Hasil yg diharapkan

Langkah2 supaya orror 500 tersebut bisa di selseaikan

### Tangkapan layar dan log error

Error 500
![17344941119227779782063313573719](https://github.com/user-attachments/assets/496d7857-bf26-4722-9e9e-dac1378717d6)

### Rilis Versi OpenSID

Rilis Umum

### Versi OpenSID

24.12

### Tema Yang Digunakan

Denatra

**Comment by andifahruddinakas** [comment]
pak @lwiradarma, silahkan update temanya sesuai versi opensidnya

**Comment by eddieridwan** [comment]
@rgrahardi pastikan di forum.opendesa.id ada petunjuk cara melaporkan error, termasuk cara menampilkan log error. 

Selain itu juga sediakan penjelasan terkait penanganan error di versi Umum. Bahwa semua error diperbaiki di versi Premium dan akan muncul di versi Umum enam bulan kemudian. Yaitu, versi Umum tidak akan diperbaiki.

Bisa saja error yg dialami sudah diperbaiki di versi Premium. Dengan demikian opsi bagi pengguna Umum sbb:

1. Tunggu sampai perbaikan error muncul di versi Umum
2. Berlangganan Premium supaya langsung memanfaatkan perbaikan terbaru
3. Meminta bantuan komunitas di grup OpenSID Umum untuk solusi sementara, jika ada. 

@rgrahardi Mohon anda juga pantau issue baru di Github dan harap tindaklanjuti semua laporan error di versi Umum.
