### ISSUE TITLE
Bug/error: Menu Info Sistem pada modul pengaturan saat dibuka HTTP Error 500

### ISSUE THREAD

**Issue by Restony33** [OpenSID/OpenSID#8816]
### Jelaskan error yg dialami

Saat membuka menu Info Sitem Pada Modul Pengaturan HTTP Error 500

### Cara untuk mereplikasi errornya

1. Login admin
2. Pilih Modul Pengaturan
3. Menu Info Sistem

### Hasil yg diharapkan

normal

### Tangkapan layar dan log error

![image](https://github.com/user-attachments/assets/3a53cff6-ef98-4802-95f0-dd99a951f25b)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

Versi 2412.0.2-premium

### Tema Yang Digunakan

DeNava

**Comment by eddieridwan** [comment]
@Restony33 mana log errornya? Mohon ikuti petunjuk cara melaporkan error di https://panduan.opendesa.id dan https://forum.opendesa.id. Apakah sudah verifikasi error tersebut terjadi juga di https://berputar.opendesa.id?

Jika bingung, sebaiknya dibawa ke Klinik OpenSID yg diadakan setiap hari. Info terkait Klinik OpenSID terus diumumkan di grup OpenSID Premium. 

@rgrahardi pastikan Panduan dan Forum sangat jelas cara untuk melaporkan error.

**Comment by Restony33** [comment]
[opensid-2024-12-18.log](https://github.com/user-attachments/files/18192152/opensid-2024-12-18.log)
ini pak log errornya

**Comment by andifahruddinakas** [comment]
pak @Restony33, bisa gunakan rilis https://github.com/OpenSID/rilis-premium/releases/tag/v2412.0.2
