### ISSUE TITLE
Bug/error: TIDAK BISA AKSES MENU BUKU TAMU

### ISSUE THREAD

**Issue by pujocahyono** [OpenSID/OpenSID#8819]
### Jelaskan error yg dialami

SAAT AKSES MENU BUKU TAMU DI ARAHKAN KE "Pengaturan Paket Tambahan" DAN MUNCUL NOTIFIKASI BERIKUT:
![Cuplikan layar 2024-12-19 083743](https://github.com/user-attachments/assets/968fa577-211b-4589-8866-530f2985f7d1)

### Cara untuk mereplikasi errornya

AKSES MENU BUKU TAMU PADA HALAMAN ADMIN

### Hasil yg diharapkan

KEMBALI NORMAL

### Tangkapan layar dan log error

SEPERTI DI ATAS

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2412.0.2

**Comment by andifahruddinakas** [comment]
Duplicate of https://github.com/OpenSID/OpenSID/issues/8820
