### ISSUE TITLE
Migrasi data untuk database gabungan

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#8824]
Saat ini jika melakukan migrasi untuk database gabungan, desa pertama kali akses setelah update yang akan menanggung beban migrasi otomatis. Karena dijalankan sekali untuk semua desa yang ada pada database gabungan.
![image](https://github.com/user-attachments/assets/41df15c5-78df-42c2-93ff-9bd6d79fa766)

Akibatnya, jika migrasi otomatis dijalankan pada database gabungan yang memiliki banyak desa migrasinya akan sangat lama, belum lagi fungsi yg dijalankan berulang kali pada 1 kali migrasi.

Yang perlu diterapkan untuk migrasi database gabungan : 

- [ ] untuk migrasi perubahan struktur tabel hanya dilakukan sekali, pastikan selalu mengeceknya. misalkan penambahan kolom, cek terlebih dahulu apakah kolom tsb ada atau tidak.
- [ ] untuk migrasi data perbahan dari datanya, jika data desa yg sensitive dan perlu konfirmasi dari desanya, sebaiknya diletakkan pada halaman periksa.
- [ ] untuk migrasi data perbahan dari datanya, jika data desa sifatnya umum, jalankan migrasi untuk desa itu saja saat akses. Migrasi otomatis dijalankan hanya pada desa itu saja. Untuk point ini diperlukan perubahan struktur tabel migrasi, dengan penambahan kolom config_id. Dan perubahan pengenalan untuk menjalankan migrasi scr otomatis.

**Comment by eddieridwan** [comment]
@andifahruddinakas @scqolbu24 migrasi untuk Database Gabungan tepatnya dilakukan oleh Dasbor SiapPakai, pada saat update ke versi terbaru.

**Comment by andifahruddinakas** [comment]
> @andifahruddinakas @scqolbu24 migrasi untuk Database Gabungan tepatnya dilakukan oleh Dasbor SiapPakai, pada saat update ke versi terbaru.

Untuk SiapPakai hanya triger saja, di OpenSID tetap yang jalankan kalau ada update yg membutuhkan migrasi.

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/4358
