### ISSUE TITLE
http://salarehaiautara.desa.id/ - Titik Koordinate Penduduk

### ISSUE THREAD

**Issue by apidong** [OpenSID/OpenSID#8828]
Cara Replikasi : 

1. Buka Menu Peta lihat satu titik kordinate penduduk

![image](https://github.com/user-attachments/assets/58ee755b-ae9c-4795-a701-a3bcc5f23e12)

2. Buka Menu Pendududk atas Nama Ade Putra
![image](https://github.com/user-attachments/assets/729c0dc2-47a1-4995-8ce5-9b5894c0859a)

3. Lihat Lokasi Tempate Tingal
![image](https://github.com/user-attachments/assets/2100e0ce-29b6-4758-9f67-24d18eb065da)

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/4352
