### ISSUE TITLE
Bug/error: JABATAN PADA SCAN QR CODE TIDAK SESUAI DENGAN SURAT

### ISSUE THREAD

**Issue by pujocahyono** [OpenSID/OpenSID#8829]
### Jelaskan error yg dialami

JIKA JABATAN KEPALA DESA SEBAGAI PJ.
SAAT SCAN QR CODE PADA JABATAN HASILNYA TETAP TERTULIS KEPALA DESA BUKAN PJ. KEPALA DESA.

### Cara untuk mereplikasi errornya

1. UBAH JABATAN KEPALA DESA MENJADI PJ.
2. BUAT SURAT DENGAN MENAMPILKAN QR CODE
3. SCAN QR CODE

### Hasil yg diharapkan

JABATAN PADA QR CODE SAMA DENGAN PADA SURAT. JIKA STATUS KEPALA DESA PJ. MAKA TERTULIS **PJ. KEPALA DESA** PADA HASIL SCAN QR CODE.

### Tangkapan layar dan log error

JABATAN PJ. PADA KEPALA DESA
![Screenshot_2024-12-21-21-39-31-027_com android chrome](https://github.com/user-attachments/assets/57b3bd6d-8bc9-47b6-b3e2-f1620d79bb19)

HASIL PADA SURAT TERCETAK PJ. KEPALA DESA
![Screenshot_2024-12-21-21-38-21-476-edit_cn wps moffice_eng](https://github.com/user-attachments/assets/fc2a11c7-3660-4c9a-b72b-23720e0e9fde)

HASIL SCAN QR CODE TETAP KEPALA DESA
![Screenshot_2024-12-21-21-38-40-552_com android chrome](https://github.com/user-attachments/assets/d2e61474-7082-458c-b1d9-6a2de4375073)

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

2412.0.2

**Comment by andifahruddinakas** [comment]
Cek juga issue https://github.com/OpenSID/OpenSID/issues/8830, karena menggunakan ORM yg smaa, seharusnya cukup ubah di 1 tempat.
