### ISSUE TITLE
Bug: Kesalahan penulisan pada Form Surat Kematian

### ISSUE THREAD

**Issue by SahlaniAfnan** [OpenSID/OpenSID#883]
salah penulisan pada form surat keterangan kematian pada kotak isian : Hari / Tanggal / Jam. seharusnya tertulis ***Isi waktu Meninggal/Kematian** namun tertulis ***Isi waktu kelahiran**

![salah tulis kelahiran](https://user-images.githubusercontent.com/15683308/37933014-2c73f576-3174-11e8-8b7f-aeca6a0e91d3.png)

**Comment by kodingku** [comment]
Saya coba kerjakan pak eddie

**Comment by kodingku** [comment]
sudah saya pull ya pak eddie

**Comment by eddieridwan** [comment]
@kodingku : PR #889 anda masih berisi perubahan file untuk tema _jdn_. Harap diperbaiki supaya PR itu **HANYA** berisi perubahan untuk surat kematian, supaya bisa digabungkan.

**Comment by MUHAMMADRANGSEL** [comment]
ini perubahannya hanya saja saya tidak bisa melakukan PR
[surat_ket_kematian.zip](https://github.com/OpenSID/OpenSID/files/1869904/surat_ket_kematian.zip)

**Comment by eddieridwan** [comment]
Sudah dikerjakan oleh @kodingku di PR #889, tapi masih menunggu bung Adi memperbaiki (masih belajar melakukan PR yang bersih).

Bung @MUHAMMADRANGSEL , silakan lihat cara membuat PR di  https://github.com/OpenSID/OpenSID/wiki/Panduan-mengirimkan-perubahan-repo-OpenSID.

Mungkin bisa sama2 belajar dengan @kodingku .

**Comment by MUHAMMADRANGSEL** [comment]
Siap

Pada tanggal Sel, 3 Apr 2018 09.45, Eddie Ridwan <notifications@github.com>
menulis:

**Comment by kodingku** [comment]
siap pak

**Comment by eddieridwan** [comment]
Sdh dicommit ke master melalui PR #905 .
