### ISSUE TITLE
Tidak bisa menggunakan helper pada AppServiceProvider

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#8832]
Saat membuat service provider, kadang memerlukan helper yang berkaitan dengan storage untuk mengambil lokasi suatu directory. Namun saat digunakan, saat ini terjadi error sbb:

![image](https://github.com/user-attachments/assets/41b5f0d7-5fd2-44fe-b224-a77fe07d1980)

![image](https://github.com/user-attachments/assets/c8624f5c-426d-4519-8791-3e7de621249e)

Jika dilihat alurnya, helper (illumintae_helper) yang berkaitan dengan storage belum diload saat AppServiceProvider dipanggil.

**Comment by agungsugiarto** [comment]
mas @andifahruddinakas karena keterbatasan saat ini, masih belum bisa memanggil helper dari ci ke service provider. Alternatif lain bisa dengan menggunakan cara seperti ini:

 ```php
class AppServiceProvider extends ServiceProvider
{
    /**
     * Register any application services.
     *
     * @return void
     */
    public function register()
    {
        $this->app->basePath('path/anda");
    }
}
```

**Comment by andifahruddinakas** [comment]
> mas @andifahruddinakas karena keterbatasan saat ini, masih belum bisa memanggil helper dari ci ke service provider. Alternatif lain bisa dengan menggunakan cara seperti ini:
> 
>  ```php
> class AppServiceProvider extends ServiceProvider
> {
>     /**
>      * Register any application services.
>      *
>      * @return void
>      */
>     public function register()
>     {
>         $this->app->basePath('path/anda");
>     }
> }
> ```

Sdh dilakukan seperti itu, namun tujuannya agar tidak banya diubah saat pindah.

https://github.com/OpenSID/premium/blob/rilis-dev/app/Providers/AppServiceProvider.php#L199

**Comment by agungsugiarto** [comment]
saya coba oprek lagi

**Comment by agungsugiarto** [comment]
di coba dulu mas @andifahruddinakas https://github.com/OpenSID/premium/pull/4355

**Comment by andifahruddinakas** [comment]
> di coba dulu mas @andifahruddinakas https://github.com/OpenSID/premium/pull/4355

Ok

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/4355
