### ISSUE TITLE
error Db Gabungan : Tidak ada rentang_waktu_notifikasi_rilis pada table setting_aplikasi

### ISSUE THREAD

**Issue by apidong** [OpenSID/OpenSID#8835]
![image](https://github.com/user-attachments/assets/8c2adba2-3578-4cb9-a07d-1f4751018594)
![image](https://github.com/user-attachments/assets/e14d69d5-00ef-460f-8b31-195d03d72bbb)

1. sudah dilakukan migrasi semua, 
2. sudah dilakukan hapus data table migrasi.

Kasus Desa Mengesta Kab Tabanan

**Comment by andifahruddinakas** [comment]
mas @agungsugiarto, cek : 
- [ ] buat seeder untuk menampung semua data pengaturan. ada sekitar 169 pengaturan yg perlu didaftarkan.
![image](https://github.com/user-attachments/assets/c86d2584-9454-4088-91bc-f91c42b8082b)

- [ ] untuk menambahkan setting bisa gunakan fuction $this->createSetting() yang ada pada trait/Migrator.php

- [ ] untuk saat ini tambahkan pengaturan sebanya jumlah config yang ada.
![image](https://github.com/user-attachments/assets/0b553337-b008-4bd3-a704-998e52929a04)
