### ISSUE TITLE
Bug/error: Query error: Column 'id_grup' cannot be null

### ISSUE THREAD

**Issue by padukadafa** [OpenSID/OpenSID#8841]
### Jelaskan error yg dialami

Ketika menginstall opensid pertama kali muncul error id_group cannot be null

### Cara untuk mereplikasi errornya

install biasa menggunakan php versi 8.1

### Hasil yg diharapkan

dapat menginstall opensid tanpa kendala

### Tangkapan layar dan log error

ERROR - 2024-12-26 14:48:12 --> Query error: Column 'id_grup' cannot be null - Invalid query: INSERT INTO `grup_akses` (`id_grup`, `id_modul`, `akses`, `config_id`) VALUES (NULL, '357', 3, 1)
ERROR - 2024-12-26 14:48:12 --> ["Error Number: 1048","Column 'id_grup' cannot be null","INSERT INTO `grup_akses` (`id_grup`, `id_modul`, `akses`, `config_id`) VALUES (NULL, '357', 3, 1)","Filename: core\/MY_Model.php","Line Number: 234"]

### Rilis Versi OpenSID

Rilis Umum

### Versi OpenSID

v2412.0.0

**Comment by andifahruddinakas** [comment]
Sudah disesuaikan di bug-fix terbaru
