### ISSUE TITLE
rincian jumlah pada statistik tidak bisa di klik

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#885]
![untitled23](https://user-images.githubusercontent.com/35319600/37953513-516b1f0e-31cd-11e8-8a29-f0a51c6794a2.jpg)

terjadi pada seluruh submenu statistik
website demo

**Comment by eddieridwan** [comment]
Saat ini memang belum diterapkan, karena bukan prioritas.

**Comment by afa28** [comment]
Diversi terbaru sudah solved

**Comment by balongbesuk** [comment]
Apakah versi demo sudah terbaru? Kl iya. Fungsi ini belum diterapkan

**Comment by afa28** [comment]
> Apakah versi demo sudah terbaru? Kl iya. Fungsi ini belum diterapkan

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #3432
