### ISSUE TITLE
Security: celah upload script php melalui surat masuk

### ISSUE THREAD

**Issue by Snoopy-Sec** [OpenSID/OpenSID#887]
Mas webnya ada bug :) path yang mas banyak yang masih ada bugnya :)

**Comment by eddieridwan** [comment]
@Snoopy-Sec : harap beri rincian bug yang anda temukan supaya bisa ditangani.

**Comment by Snoopy-Sec** [comment]
Di open SID yang ver 2.3 tingkatin lagi mas, bisa upload shell/backdoor si attacker  :)

**Comment by eddieridwan** [comment]
@Snoopy-Sec : jangan cek di versi lama -- ada rilis baru setiap tgl 1; semua pengguna dianjurkan untuk selalu update. 

Cek di versi terkini: https://github.com/OpenSID/OpenSID/releases. Saat ini v2.10, nanti tgl 1 April akan dirilis v2.11 (versi pra-rilis dapat diunduh di https://github.com/OpenSID/OpenSID). Atau cek di website demo di http://sid.bangundesa.info.

**Comment by Snoopy-Sec** [comment]
v2.10 dengan 3.10 beda vendor? 3.10 juga memiliki bug yang sama mas :)

**Comment by eddieridwan** [comment]
SID CRI 3.10 dikembangkan oleh Combine Resource Institution, lembaga non-pemerintah. OpenSID awalnya dikembangkan dari SID CRI 3.04 dan juga menggabungkan fitur SID CRI 3.10. OpenSID dikembangkan oleh Komunitas OpenSID, komunitas open source.

Silakan pentest OpenSID v2.10 di http://sid.bangundesa.info, dan beritahu secara rinci celah yang anda temukan supaya bisa ditangani.

**Comment by eddieridwan** [comment]
@Snoopy-Sec : bagaimana, sudah lakukan pentest pada OpenSID v2.10? Apa hasilnya?

**Comment by Snoopy-Sec** [comment]
Bug di statistik data/arsip masih belum di filter buat file ext file php mas :) ada celah buat si attacker :)

System: Linux mocha3015.mochahost.com 3.10.0-714.10.2.lve1.4.79.el6h.x86_64 #1 SMP Thu Jan 4 14:26:00 EST 2018 x86_64
User: eddier (1055) Group: ? (1051)
Server IP: 198.38.82.225

**Comment by eddieridwan** [comment]
@Snoopy-Sec , di menu mana celah itu (di menu Statistik tidak ketemu)? Mohon beri penjelasan, supaya bisa segera diperbaiki.

**Comment by Snoopy-Sec** [comment]
Ada bug di surat masuk, belum di filter ext filenya mas :) Attacker bisa upload backdoor mas :)
Mohon di perbaiki :)
![screenshot 74](https://user-images.githubusercontent.com/36057801/38139788-1ef71858-345b-11e8-9777-ae818fdd9c80.png)

**Comment by esyede** [comment]
Terimakasih @Snoopy-Sec

**Comment by Snoopy-Sec** [comment]
Open SID v.2.11 masih ada celahya pak :)
Setelah saya scan coba perhatikan path http://sid.bangundesa.info/desa/upload/user_pict/aEG1ZM_up.php
Disitu ada uploader tersembunyi yang sangat memungkin attacker bisa upload backdoor :)
Mohon di tutup ya pak :)

![screenshot 75](https://user-images.githubusercontent.com/36057801/38171311-65e5d800-35c1-11e8-9c29-b741469be78f.png)

**Comment by eddieridwan** [comment]
@Snoopy-Sec : terima kasih. Tapi jangan ganti nama issue yang sedang/sudah dikerjakan. Buat issue baru untuk celah baru yang anda temukan. Issue dikerjakan satu per satu. Satu issue hanya boleh satu masalah. Kalau anda ganti nama issue yg sedang dikerjakan atau menambah masalah, akan membingungkan. Jadi mohon buat issue baru. Terima kasih.

**Comment by esyede** [comment]
Terimakasih @Snoopy-Sec . Nice catch! 👍.
Seperti saran pak @eddieridwan, silahkan langsung dibuatkan issue baru agar teman - teman lebih mudah untuk mengirim pull request.

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR #898.

**Comment by zaenjr** [comment]
Mantap liat komenw nya.. Si pentester pro sangad

**Comment by zaenjr** [comment]
Mantap liat komenw nya.. Si pentester pro sangad
