### ISSUE TITLE
Cara mengatasi masalah tampilan di Layanan Mandiri WP-SID

### ISSUE THREAD

**Issue by AlfaridzhE** [OpenSID/OpenSID#888]
Assalamu'alaikum...
Terima kasih sebelumnya kepada opensid yang telah membuat kemudahan bagi penggunanya untuk dapat mengakses opensid dari mana saja.
Tapi disini saya menemukan beberapa kendala yang saya alami sampai harus bongkar script nya (untuk beberapa hal), namun kali ini saya benar2 mengalami masalah serius di bagian tampilan Layanan Mandiri yang terintegrasi ke Wordpress, tampilannya sangat kacau, saya minta sedikit solusi nya agar bisa membereskan itu dan bisa melanjutkan pekerjaan saya untuk selanjutnya saya publikasikan kepada yang lain.
Sedikit saran dari saya, tolong wpsid (plugin wordpress) diperbarui, karena mungkin saja itu hal dari masalah yang saya sedang alami.
Terima kasih
Wassalam

**Comment by eddieridwan** [comment]
@AlfaridzhE , wpsid-shortcode bukan bagian dari rilis OpenSID. Plugin ini dibuat oleh simasta (https://profiles.wordpress.org/simasta). Silakan hubungi pengembangnya untuk bantuan dan memberi usul.
