### ISSUE TITLE
Permasalahan nama penduduk yang memiliki tanda petik ada di seluruh surat master

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#893]
bug ini terjadi di seluruh surat master bukan cuma surat keterangan saja, form.raw suratnya juga perlu di sesuaikan agar pengguna yang membuat surat baru tidak mengalami bug ini,

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR #1025.
