### ISSUE TITLE
Bug: data 'JUMLAH' ikut masuk grafik statistik data

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#895]
dalam aplikasinya sudah benar tapi pada tampilan website data 'jumlah' statistis masih ikut ditampilkan
![untitled23](https://user-images.githubusercontent.com/35319600/38126185-1b5599d2-3419-11e8-871e-426d838dd9b6.jpg)

**Comment by eddieridwan** [comment]
Sdh dicommit ke master.
