### ISSUE TITLE
Buat daftar kontributor di readme.md

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#897]
Mengikuti contoh https://github.com/netlify/netlify-cms.

Kumpulkan daftar tautan untuk masing2 kontributor OpenSID.

**Comment by mugi789** [comment]
https://github.com/mugi789

**Comment by esyede** [comment]
Suyadi: https://github.com/esyede

**Comment by eddieridwan** [comment]
Daftar kontributor sudah masuk ke readme.md
