### ISSUE TITLE
Security: Hidden uploader script

### ISSUE THREAD

**Issue by Snoopy-Sec** [OpenSID/OpenSID#899]
Open SID v.2.11 masih ada celahya pak :)
Setelah saya scan coba perhatikan path **/desa/upload/user_pict/aEG1ZM_up.php**
Disitu ada uploader tersembunyi yang sangat memungkin attacker bisa upload backdoor :)
Mohon di tutup ya pak :)

![screenshot 75](https://user-images.githubusercontent.com/36057801/38173948-c5ae00b8-35ef-11e8-96f4-a9e28bed96f2.png)

**Comment by eddieridwan** [comment]
Bagi programmer: masalah ini timbul karena saat ini, function berikut masih mengambil mime type file dari kiriman browser:

- ` user_model.insert()`
- `user_model.update()`
- `pict_helper.UploadFoto()`

Perlu diubah. Idealnya menggunakan uploader CI. Atau menggunakan fungsi `$finfo = finfo_open(FILEINFO_MIME_TYPE)`, dan/atau `opens_helper.isPHP()`. Perlu diuji menggunakan file image yg berisi script php, seperti file aEG1ZM_up.php yang dilaporkan @Snoopy-Sec . File tersebut sudah dihapus dari situs demo. Tapi kami bisa sediakan di forum teknis bagi yg membutuhkan untuk menguji hasil perbaikan.

**Comment by esyede** [comment]
@eddieridwan:
Kalau misalnya bug ini dikerjakan, kira - kira conflict tidak dengan pull #898 ?
Bagaimana cara membuat branchnya?
Soalnya kalau saya buat branch dari master di lokal saya, file `donjo-app/models/user_model.php` masih sama seperti master yang ada di `OpenSID/OpenSID`, tidak seperti yang ada di #898 . Saya khawatir akan terjadi conflict dengan #898 jika saya pull file  `donjo-app/models/user_model.php` ke `OpenSID/OpenSID`. 
Sedangkan saya butuh mengedit file itu untuk fixing bug ini, terutama method `user_model::update_setting`

**Comment by eddieridwan** [comment]
Seharusnya tidak conflict dengan #898. #898 sebenarnya berurusan dengan 'dokumen' bukan gambar (ada penamaan function/variable yang keliru). user_model hanya berurusan dengan image. Penanganannya harusnya beda. Controller dan modelnya beda. #898 seharusnya tidak mengubah user_model.php.

**Comment by eddieridwan** [comment]
Sdh dicommit ke master melalui PR #920
