### ISSUE TITLE
Bug: Centang penduduk di menu peta tampilkan blank kalau ada nama penduduk berisi tanda petik

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#900]
ketka pilih centang penduduk di menu peta tampilan blank
![image](https://user-images.githubusercontent.com/25834335/38182050-3fbacebc-3669-11e8-8ae6-dceae1c62626.png)

**Comment by eddieridwan** [comment]
Di situs http://sid.bangundesa.info normal. Cek apakah ada nama penduduk berisi tanda petik (').

<img width="1301" alt="peta-penduduk" src="https://user-images.githubusercontent.com/249563/38188027-61ed2046-369d-11e8-92fc-f78638646c7d.png">

**Comment by balongbesuk** [comment]
![untitled23](https://user-images.githubusercontent.com/35319600/38189522-dd834810-368a-11e8-8e37-a4b44297c6b7.jpg)

aman pak Opensid 2.11

**Comment by eddieridwan** [comment]
Konfirmasi tampilkan halaman kosong kalau ada nama penduduk berisi tanda petik (').

**Comment by MUHAMMADRANGSEL** [comment]
Ada mas Eddie

Pada tanggal Sen, 2 Apr 2018 16.31, balongbesuk <notifications@github.com>
menulis:

**Comment by eddieridwan** [comment]
Tidak lagi diprioritaskan, dan mungkin nanti ditutup. Karena kemungkinan besar semua fitur Peta akan dipindahkan menggunakan OpenStreetMap.

**Comment by eddieridwan** [comment]
Peta sudah dikonversi ke OpenStreetMap. Dan juga masalah nama penduduk berisi tanda petik (') sudah diperbaiki di model melalui issue lain.

Issue ini bisa ditutup.
