### ISSUE TITLE
Bug: Tempat kelahiran salah di Surat Keterangan Kelahiran

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#901]
![sedang_1519876576_rastraii](https://user-images.githubusercontent.com/35319600/38182243-5da78228-3662-11e8-8c40-f4a26238ebb9.jpeg)

![sedang_1519876576_rastraii](https://user-images.githubusercontent.com/35319600/38182363-0dd9276e-3663-11e8-9e65-7a8f382a4590.jpeg)

seharusnya Kota / Kabupaten dimana yang Anak tersebut Lahir, Kenapa Jadi Alamat dilahirkan?

dengan begitu isian alamat lahir bisa masuk ke tempat lahir

![sedang_1519876576_rastraii](https://user-images.githubusercontent.com/35319600/38182469-dbbc0d90-3663-11e8-91ed-ba8aaaf7ca18.jpeg)

**Comment by eddieridwan** [comment]
@afri18, @muhammadrangsel: harap beri tanggapan. Setuju?

**Comment by afri18** [comment]
yang betul TEMPAT LAHIT > bukan ALAMAT LAHIR
TEMPAT LAHIR > Nama Kota atau Kabupaten (bukan kecamtan apalagi desa)

**Comment by kodingku** [comment]
yg dirubah apa ya??apakah boleh dicoba

**Comment by metalab25** [comment]
sudah saya ubahkan silakan direview
[surat_ket_kelahiran.zip](https://github.com/OpenSID/OpenSID/files/1872353/surat_ket_kelahiran.zip)

**Comment by eddieridwan** [comment]
@metalab25 , silakan buat pull requestnya supaya bisa di-review.

**Comment by metalab25** [comment]
sudah saya kirim PR

**Comment by eddieridwan** [comment]
@metalab25 , maaf belum sempat review. Mudah2an dalam beberapa hari ini.

**Comment by eddieridwan** [comment]
Ternyata issue ini lebih rumit dari terpikir pada awalnya. 

Karena interpretasi yg berbeda pada waktu Surat Keterangan Kelahiran dibuat, saat ini di tabel tweb_penduduk ada kolom `alamat_tempat_lahir` untuk menyimpan alamat jalan tempat orang itu dilahirkan. 

Untuk menerapkan perubahan di issue ini, sesuai dengan petunjuk pengisian F-2.01, kolom `alamat_tempat_lahir` tidak diperlukan lagi, karena isian _Tempat Kelahiran_ (nama kota atau kabupaten tempat kelahiran) sudah ada kolomnya di `tweb_penduduk`, yaitu `tempatlahir`.

Dengan demikian, perubahan yang diperlukan untuk issue ini mencakup:

1. menghapus kolom `alamat_tempat_lahir` dari tabel `tweb_penduduk`. Masukkan penghapusan kolom ini sebagai migrasi di <em>database_model.php</em>
2. menghapus tampilan kolom `alamat_tempat_lahir` dari <em>donjo-app/views/sid/kependudukan/penduduk_detail.php</em>
3. menghapus kolom isian `alamat_tempat_lahir` dari <em>donjo-app/views/sid/kependudukan/penduduk_form_isian.php</em>
4. mengubah `alamat_tempat_lahir` dengan `tempatlahir` di <em>surat/surat_ket_kelahiran/data_form_surat_ket_kelahiran.php</em>, <em>surat/surat_ket_kelahiran/data_rtf_surat_ket_kelahiran.php</em>, <em>surat/surat_ket_kelahiran/f-2.01.php</em>, <em>surat/surat_ket_kelahiran/surat_ket_kelahiran.php</em>
5. tambahkan catatan <em>"(nama kota atau kabupaten kelahiran)"</em> di form surat, dan juga di form isian penduduk, supaya jelas apa yg perlu diisi untuk <em>Tempat Kelahiran</em>

Perlu dicek, pengisian _Tempat Kelahiran_ di form Surat Keterangan Kelahiran mengubah data `tempatlahir` di tabel `tweb_penduduk` (dan tampil di semua tampilan penduduk).

**Comment by afri18** [comment]
kenapa jadi ruwet ya ? padahal pakai tempat lahir yg di tweb_penduduk aja, lalu tambahkan satu file untuk alamat_dilahirkan
itu menurut saya yg bodoh

**Comment by eddieridwan** [comment]
Yang ada di rilis sekarang hasil pengertian di issue dulu (beberapa bulan yang lalu) yang di bahas di https://github.com/OpenSID/OpenSID/issues/632 dan direview teman2. Ya, selama ini tidak ada yg comment. Baru @balongbesuk yg meneliti.

Karena itu, teman2 yg mengerti SELALU diminta memberi spesifikasi yg jelas dan SELALU diminta untuk memeriksa setiap issue yang siap diujicoba.

**Comment by eddieridwan** [comment]
Telah dicommit ke master melalui PR #961.
