### ISSUE TITLE
Tambahkan Log Surat Pada >> Arsip Lanyanan >> Rekam Perorangan

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#902]
![sedang_1519876576_rastraii](https://user-images.githubusercontent.com/35319600/38229296-64475a92-3732-11e8-886e-210bd6fb1dbf.jpeg)

tambahkan Arsip surat pada Rekam Surat Perorangan

**Comment by MUHAMMADRANGSEL** [comment]
di kami tampilammya seperti ini : 
![image](https://user-images.githubusercontent.com/25834335/38185792-56d442d6-3682-11e8-8f8f-1d90012716cb.png)
tidak ada masalah dan menggunakan rilis 2.11 juga

**Comment by balongbesuk** [comment]
yang rekam surat perorangannya pak @MUHAMMADRANGSEL

**Comment by balongbesuk** [comment]
![sedang_1519876576_rastraii](https://user-images.githubusercontent.com/35319600/38229296-64475a92-3732-11e8-886e-210bd6fb1dbf.jpeg)

**Comment by balongbesuk** [comment]
![untitled24](https://user-images.githubusercontent.com/35319600/39320509-87739b00-49ae-11e8-96da-ced38b6ae558.jpg)

alhamdulillah berhasil belajar sedikit sedikit, lanjut besok belajar pull request Opensid,
semoga bermanfaat bagi operator yang mencari arsip surat penduduk, tinggal klik arsip suratnya (tanpa harus lama lama mencari di paginasi surat keluar)

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR #962.
