### ISSUE TITLE
Alamat Pada Log Rekam Surat Perorangan cuma menampilkan jalan

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#903]
![sedang_1519876576_rastraii](https://user-images.githubusercontent.com/35319600/38184630-27acbfc4-3673-11e8-871d-805d4ef641ca.jpeg)

**Comment by MUHAMMADRANGSEL** [comment]
di kami memakai rilis 2.11 tdk masalah
![image](https://user-images.githubusercontent.com/25834335/38185713-0c7f91f4-3682-11e8-8ca4-a21854a2a0db.png)

mungkin belum melakukan migrasi atau databasenya gangguan

**Comment by balongbesuk** [comment]
sudah saya cek ulang alamat yang ditampilkan cuma alamat Jalan

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR #962
