### ISSUE TITLE
Ubah aikon menu Sekretariat supaya berbeda dengan Cetak Surat

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#906]
Saat ini aikon menu Sekretariat sama dengan menu Cetak Surat. Sebaiknya dibedakan.

<img width="1115" alt="icon-sekretariat" src="https://user-images.githubusercontent.com/249563/38235377-485b3a42-3764-11e8-814d-119e1d273292.png">

**Comment by eddieridwan** [comment]
Perubahan dilakukan di tabel <em>setting_modul</em>.
Cara melakukan perubahan adalah melalui migrasi di <em>models/database_model.php</em>.
Tambahkan database commandnya di method `migrasi_211_ke_212()`.

**Comment by eddieridwan** [comment]
Kolom `icon_kecil` untuk Sekretariat juga perlu diubah (cari yang sesuai dengan aikon besar yang dipilih). Aikon kecil ini ditampilkan di menu drop-down di avatar user (sebelah kanan atas) pada waktu menampilkan menu _Peta_).

**Comment by kodingku** [comment]
icon sekretariat dan small icon di plan sudah saya rubah,itu dari database pak,dan untuk membuat pull request nya??
apakah yg saya kirim dbnya atau gmna?? karna tidak ada file yg diedit,kalaupun di database_model command yg dimaksud?? query atau hanya comand tanda // slash

**Comment by eddieridwan** [comment]
Cukup di database_model.php. Method method `migrasi_211_ke_212()` nanti dieksekusi pada waktu menjalankan Database > Migrasi DB. Jadi jangan ubah database secara manual. Tes dulu menggunakan Database > Migrasi DB. Itu fungsinya database_model.php: untuk mengubah database melalui Migrasi DB.

**Comment by eddieridwan** [comment]
Pull request tidak pernah ada databasenya. Perubahan database selalu melalui database_model.php yang dijalankan pada waktu Database > Migrasi DB.

**Comment by kodingku** [comment]
Ok sdh d migrasi db dan sdh berhasil ko pak,selanjutnya??

**Comment by kodingku** [comment]
Sdh saya migrasikan pak

**Comment by eddieridwan** [comment]
Kalau sudah ok, ya silakan kirim pull requestnya. PR-nya seharusnya hanya berisi satu file, yaitu perubahan di database_model.php.

**Comment by eddieridwan** [comment]
Di method `migrasi_211_ke_212()` di database_model.php tambahkan command semacam berikut:

```
    // Ubah ikon modul sekretariat
    $this->db->where('url','sekretariat')->update('setting_modul',array('ikon'=>'ikon_baru.png', 'ikon_kecil'=>'fa fa-ikon-baru fa-lg'));
```

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR #907
