### ISSUE TITLE
Bug: Menghapus dan mengubah surat masuk perlu menghapus berkas lama di-arsip

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#909]
Saat ini, berkas scan lama masih tersimpan dan tidak dihapus, walaupun surat masuk yang bersangkutan telah dihapus atau berkasnya sudah diganti dengan berkas lain.

**Comment by esyede** [comment]
Untuk menu *'Ubah'*, file memang sengaja tidak dihapus jika checkbox *'Hapus Berkas Lama?'* tidak di-centang.

Untuk menghapus file lama, silahkan centang checkbox *'Hapus Berkas Lama?'* tersebut. Karena defaultnya checkbox tersebut tidak ter-centang, maka file lama di disk tidak ikut dihapus (Ini intended behaviour).

Apakah perlu default checkbox diubah menjadi `checked` ?

**Comment by esyede** [comment]
Saya ambil opsi ke-dua, mohon direview.
Cc: @eddieridwan

**Comment by eddieridwan** [comment]
Checkbox _'Hapus Berkas Lama'_  dimaksudkan untuk menghapus berkas lama tanpa mengganti dengan yang baru -- yaitu surat masuk yang berkasnya belum diunggah (masih kosong). Kasus ini mungkin terjadi kalau berkas salah unggah, sedangkan berkas yg benar belum siap.

Kalau mengubah berkas dgn yang baru,  yang lama harus selalu dihapus (meskipun checkbox tidak dicentang), karena secara praktis tidak bisa diakses lagi oleh pengguna. 

Demikian juga kalau surat masuk dihapus, berkasnya tidak bisa diakses lagi oleh pengguna -- dan harus selalu dihapus, walaupun checkbox tidak dicentang.
