### ISSUE TITLE
Dibuatkan Menu Kelembagaan Desa

### ISSUE THREAD

**Issue by SahlaniAfnan** [OpenSID/OpenSID#914]
Untuk mengadministrasi Kelembagaan yang ada di Desa Seperti:
1. BPD dan Anggota
2. MUI dan Anggota
3. Karang Taruna
4. PIK-KRR
5. PKK
yang berfungsi jika ada undangan Musyawarah desa, nama-nama yang diundang tidak ditulis manual.

![menu kelembagaan](https://user-images.githubusercontent.com/15683308/38329265-8ede1494-3877-11e8-90a9-0a3d4730df9a.jpg)

![surat undangan otomatis](https://user-images.githubusercontent.com/15683308/38329390-dd6c585a-3877-11e8-887e-bcc48de28958.jpg)

**Comment by eddieridwan** [comment]
Catatan: Surat ini bukan bagian dari menu _Cetak Surat > Cetak Surat_, karena bukan surat layanan. Surat ini bagian dari menu _Sekretariat > Surat Keluar_ (yang belum dikerjakan).

**Comment by MUHAMMADRANGSEL** [comment]
Kalau saya lebih condong buat menu baru Maslah kelembagaan itu

**Comment by mizwaruddin** [comment]
@afa28 bisa dibuat melalui menu dan artikel statis.
