### ISSUE TITLE
Ganti default language ke bahasa indonesia

### ISSUE THREAD

**Issue by esyede** [OpenSID/OpenSID#917]
Tindak lanjut untuk penambahan language file pada komentar di pull #898 poin ke-3.

3. penambahan donjo-app/language/english/upload_lang.php idealnya untuk language file 'indonesia', bukan perubahan language file 'english'. Tapi kalau terlalu sulit, kali ini biarkan saja. Tambahkan saja issue untuk menambahkan language file 'indonesia' -- untuk diterapkan lain kali.

**Comment by eddieridwan** [comment]
Sdh dicommit ke master melalui pR #918

**Comment by sudiyono86** [comment]
ok

**Comment by Muhammad99masrury** [comment]
Ganti default bahasa Indonesia #918
