### ISSUE TITLE
Duplikasi Data Pada Log Penduduk

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#921]
![untitled-1](https://user-images.githubusercontent.com/35319600/38454791-3cf83862-3a98-11e8-9f00-5e701fca7cde.jpg)

**Comment by eddieridwan** [comment]
Masalah ini sudah diperbaiki dan solusi sudah dicommit ke master. Commit https://github.com/OpenSID/OpenSID/commit/75cdbc0527e9f6872556a793dc020489dd78c378.
