### ISSUE TITLE
Security: Tutup celah unggah berkas script melalui menu _Setting User_

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#922]
Celah unggah script melalui menu _Pengguna > Manajemen Pengguna_ sudah ditutup. Tetapi fitur serupa di menu di bawah ikon pengguna (_Setting User_) belum dikerjakan.

**Comment by ombimo** [comment]
bukankah untuk setting user pernah ditutup pak ?

**Comment by eddieridwan** [comment]
Yang dikerjakan sebelumnya: https://github.com/OpenSID/OpenSID/issues/899 menutup celah di menu _Pengguna > Manajemen Pengguna_. Sepertinya penerapan menu _Setting User_ (di menu dropdown avatar user) bisa digabungkan dengan penerapan _Pengguna > Manajemen Pengguna_.

**Comment by ombimo** [comment]
ini saya trace, di dalam menu _setting user_ sudah ada penggunaan finfo.
apakah perlu di recode menggunakan uploader ci ?

![image](https://user-images.githubusercontent.com/20896126/39045299-bd8573e0-44bc-11e8-9e99-c4e2baa90980.png)
![image](https://user-images.githubusercontent.com/20896126/39045314-ca801014-44bc-11e8-9ded-f33dc87ba811.png)
![image](https://user-images.githubusercontent.com/20896126/39045337-dcbed5a8-44bc-11e8-92df-f8aa85c8d8da.png)
![image](https://user-images.githubusercontent.com/20896126/39045382-fd1f9dfa-44bc-11e8-98cd-00de5fed7fad.png)

**Comment by eddieridwan** [comment]
@ombimo : anda betul -- terima kasih telah melacak. Ya, sudah dikerjakan dulu (https://github.com/OpenSID/OpenSID/issues/834 -- di v2.11). Ok, sudah di-tes, dan bisa menolak mengunggah script php. Kami akan tutup issue ini.

Perubahan menggunakan uploader CI perlu digunakan, tetapi sebaiknya dibuat issue terpisah.

**Comment by ombimo** [comment]
mungin setelah pindah ke ci 3 saya bantu merubah codenya,
dan sepertinya fungsi resize (pembuatan thumbnail, memperkecil) harus dipisah sama code upload.
