### ISSUE TITLE
Security: Tambahkan suffix acak pada nama berkas foto pengguna

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#924]
Perlu ditambahkan suffix acak pada nama berkas foto pengguna yg diunggah melalui menu _Pengguna > Manajemen Pengguna_, supaya nama berkas tidak bisa ditebak, misalnya `desa/upload/user_pict/kecil_kitten.jpg`.

**Comment by egodasa** [comment]
@eddieridwan Apakah issue ini masih perlu diselesaikan Mas?

**Comment by eddieridwan** [comment]
Gunakan method seperti `Surat_masuk_model.tambahSuffixUniqueKeNamaFile();`. Karena mungkin digunakan diberbagai tempat, mungkin masukan ke helper file. Mungkin di `pict_helper.php`.

**Comment by egodasa** [comment]
Suffix sekarang menggunakan string "kecil_". Yang saya dapat suffixnya adalah seperti pada foto dibawah.
![suffix](https://user-images.githubusercontent.com/9961837/39345267-affd819a-4a11-11e8-921f-d1db5a44bf36.jpg)
Dimana `microtime(true)*10000` adalah waktu sekarang dalam milidetik sejak tahun 1970. Mirip getTime() pada javascript. Dan hasilnya unik karena milidetik sangat cepat perubahan nilainya dan kedepannya tidak akan terjadi redudansi.

Kemudian hasilnya di hash menggunakan md5 dan diambil  5 digit didepan dari hash tersebut sehingga nama foto menjadi `kecil_5ff43_namafoto.jpg`. Bagaimana Mas?

**Comment by LIQRGV** [comment]
Kalo pake unix time, ada kemungkinan user memiliki hash yang sama walaupun
kecil.
Mungkin sebaiknya md5 diganti dengan BCrypt saja, pak.
Cmiiw

**Comment by egodasa** [comment]
@LIQRGV Baik Mas. Maaf Saya newbie. Kita tunggu Mas @eddieridwan tanggapannya.

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR #967
