### ISSUE TITLE
Pesan error pada waktu menggungah foto pengguna perlu dirinci

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#925]
Pesan error pada waktu mengunggah foto pengguna melalui menu _Pengguna > Manajemen Pengguna_ perlu dirinci, misalnya jenis berkas salah --- sekarang hanya pesan gagal saja

**Comment by afa28** [comment]
Apa ini masih perlu pak @eddieridwan ???

**Comment by eddieridwan** [comment]
Mohon periksa. Karena sdh lama, tidak jelas statusnya.
