### ISSUE TITLE
Security: tambah cara untuk mengharuskan pengguna mengganti password default

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#927]
Ternyata banyak desa online yang masih menggunakan password default. Untuk mengamankan website mereka, perlu dicari cara untuk memaksa passwordnya diganti.

Dan juga harus mengganti password paling lama dalam waktu 3 bulan.

Perlu juga ditambah cek agar password yang digunakan harus memenuhi syarat kekuatan tertentu.

**Comment by metalab25** [comment]
Saya hanya mereport karna kebetulan saya bisa berkomunikasi langsung dengan para attackernya.

**Comment by metalab25** [comment]
Kebetulan saat ini ada 3 attacker di grub fb. Kita harus berterimakasih kepada mereka atas bantuannya mengetes keamanan OpenSID

**Comment by eddieridwan** [comment]
Kemarin mereka juga sudah memberi peringatan di FB bahwa banyak website masih menggunakan password default -- sebelum melakukan hacking. Tapi kita juga sudah lama tahu -- ini bukan info baru. Banyak desa yang sepertinya sama sekali tidak mengerti keamanan. Fitur teknis kemampuannya terbatas. Celah utama selalu ada pada pengguna. Dan kembalinya pada pendampingan yang melekat dan bertanggung jawab.

**Comment by metalab25** [comment]
Celahnya bukan karna password tidak diganti tapi lebih mendalam. Ada baiknya sementara desa" kosongkan dulu data penduduknya. Sementara gunakan data penduduk dalam versi offline

**Comment by eddieridwan** [comment]
Apakah anda diberitahu apa masalah yang 'lebih mendalam' itu? Kalau kita tidak tahu, akan sukar ditutup. Ternyata para pentester sulit diajak untuk diskusi di forum teknis.

**Comment by metalab25** [comment]
Coba nanti saya tanyakan celahnya dimana hingga bisa ditembus. Kemarin yg saya dapat info celah ada pada script upload

**Comment by metalab25** [comment]
Coba nanti saya tanyakan celahnya dimana hingga bisa ditembus. Kemarin yg saya dapat info celah ada pada script upload

**Comment by eddieridwan** [comment]
Kalau script upload juga sudah lama diketahui --- tapi celah itu ada HANYA kalau bisa login ke modul Admin. Apakah ada celah lain yang mereka ketahui --- yang 'lebih mendalam'?

**Comment by metalab25** [comment]
Iya benar. 
Attacker ga perlu account untuk masuk ke website.
Attacker punya cara sendiri yang ga mungkin dibongkar ke kita om.

**Comment by eddieridwan** [comment]
Ya, katanya mereka mau membantu. Kalau mau membantu, tentunya akan memberitahu apa yg perlu dilakukan untuk menutup celah. Kalau tidak mau, berarti mereka hanya ingin tertawa melihat orang sengsara....

**Comment by metalab25** [comment]
Bung eddie silakan langsung chat sama attackernya aja biar saya grupkan

**Comment by eddieridwan** [comment]
Ada yg sudah di slack. Tapi tidak bisa diajak membahas.

**Comment by eddieridwan** [comment]
Contoh dari Laravel untuk memaksa penggantian password: http://laraveldaily.com/password-expired-force-change-password-every-30-days/

**Comment by suphm** [comment]
Saya minta izin bergabung disini ya.
 
Menurut saya, memaksa metode mengganti password rutin kurang pas di-UX. pasti admin bosen nantinya.
Usul saya, bisa tambahkan config variabel konstan untuk username/password pertama. implementasinya, pengecekan dilakukan seteleh login berhasil. misalnya:
```php
if ($user->is_using_default_login_info()) {
	// pesan warning ke user dan alihkan ke halaman ubah password
}

function is_using_default_login_info() {
	return $username == $config_admin_username && $password === $config_admin_password;
}
```

**Comment by eddieridwan** [comment]
@suphm : kalau ada solusi silakan kirim pull request. Ikuti petunjuk https://github.com/OpenSID/OpenSID/wiki/Cara-Ikut-Mengembangkan-OpenSID.

**Comment by eddieridwan** [comment]
Mengikuti usul @suphm , issue ini dibatasi hanya untuk memperingati admin mengganti password kalau masih menggunakan password default.

PR #966 telah menerapkan perubahan itu.

Issue ini akan ditutup. Kalau perubahan berikut yg belum dikerjakan masih diperlukan, akan dibuka issue baru:

- pengguna harus mengganti password paling lama dalam waktu 3 bulan.
- password yang digunakan harus memenuhi syarat kekuatan tertentu.
