### ISSUE TITLE
Pengaturan login/logout supaya menggunakan session class Codeigniter

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#928]
Saat ini user 'session' dibuat satu kali, pada waktu user ditambah, dan tidak diupdate lagi. Dan tidak menggunakan fitur Codeigniter.

Seharusnya, user 'session' perlu sering diubah dan diperkuat. Ganti cara mengelola user session dan gunakan fitur session security Codeigniter. Pelajari celah2 yang diketahui dan perkuat pertahanannya.

Misalnya, lihat https://www.dionach.com/blog/codeigniter-session-decoding-vulnerability.

**Comment by suphm** [comment]
om @eddieridwan, Sebetulnya untuk CI session sudah diterapkan. Dari dokumentasinya, data CI session bisa diakses seperti biasa memakai variabel global $_SESSION. Yang perlu diubah mungkin hampir semua controller sekarang ada penggunaan ```session_start()```,  padahal sebetulnya sudah tidak diperlukan lagi karena sudah di-autoload.
Dan maksudnya "user 'session' dibuat satu kali" itu gimana om?

**Comment by eddieridwan** [comment]
@suphm saat ini belum digunakan untuk mengatur login user. Saat ini `$_SESSION['sesi']` yang digunakan per user pada waktu pertama kali mendaftar user, dan tidak pernah perubah lagi. Sedangkan variabel itu digunakan untuk cek apakah boleh akses ke setiap controller: 
`$grup	= $this->user_model->sesi_grup($_SESSION['sesi']);`

Jadi tidak menggunakan, misalnya:
`$this->session->set_userdata('logged_in', $sess_array);` atau
`if ( ! $this->session->userdata('logged_in'))`.

Yaitu, 'sesi' yang digunakan static dan tidak bisa di-expire.

**Comment by suphm** [comment]
Kalau begitu ini bahasannya ACL/RBAC barangkali, om.
Ini bisa saya perbaiki mungkin tapi untuk referensi list controller untuk masing-masing grupnya saya belum tahu.

**Comment by suphm** [comment]
Ada dua isu yang saya tangkap, mungkin dipecah saja:

- "user 'session' perlu sering diubah".  bisa dengan fungsi php ```session_regenerate_id()```.
- User group / ACL: Entitinya: User, Grup, Aksi (controller/method).
  Saya ada contoh kode:
```php
$aksionList = "select * from aktions where grup=current_user.grup";
echo in_array($currentAksion, $aksionList) ? "user allowed" : "403 Forbidden";
```

**Comment by eddieridwan** [comment]
@suphm sepertinya saya keliru dan belum paham betul penggunaan session. Anda betul, saat ini sudah menggunakan session untuk mengatur login. Saya kira yg membingungkan adalah penamaan kolom _session_ di tabel _user_. Isinya sebenarnya adalah _user_hash_ dan bukan info mengenai session. Penggunaannya tampaknya sebagai pengganti _user_id_ saja.

Mungkin yg diperlukan adalah mengubah penggunaan session dalam pengaturan login/logout supaya lebih mengikuti cara/contoh Codeigniter (https://www.codeigniter.com/user_guide/libraries/sessions.html). Jadi akan lebih mudah dimengerti oleh teman2 yg akan support OpenSID ke depan.

Mengenai ACL/RBAC, memang perlu ditata ulang juga. Tapi sebaiknya dibuatkan issue baru. Anda bisa?

**Comment by suphm** [comment]
Ok om, nanti saya langsung PR saja untuk ACL.
