### ISSUE TITLE
Pengubahan Alamat Siteman

### ISSUE THREAD

**Issue by SahlaniAfnan** [OpenSID/OpenSID#929]
sebetulnya saya belum memahami tentang keamanan sebuah website. namun ini hanya pendapat saja... sebaiknya alamat siteman dapat diubah pada modul admin. sebab saya kira alamat ini yang berhak mengakses hanya orang-orang tertentu saja (pejabat desa). walaupun kenyataannya semua jenis keamanan dapat dijebol. 
![siteman](https://user-images.githubusercontent.com/15683308/38581226-6a66defc-3d36-11e8-8363-7055c87bb5c4.jpg)

**Comment by hansahdarmawan** [comment]
untuk perubahan alamat login/siteman bisa dilakukan perubahan script pada beberapa folder yang terdapat di donjo-app antara lain config , 
controllers dan views dengan rincian perubahan sebagai berikut : 
1. pada folder donjo-app/config/ lakukan perubahan pada routes.php
dari : 
$route['default_controller'] = 'main';
$route['404_override'] = '';
$route['translate_uri_dashes'] = FALSE;

jadi  

$route['default_controller'] = "main";
$route['404_override'] = '';
$route['nama_alamat_sesuai_anda']='siteman';
$route['siteman']='404';

2.  selanjutnya lakukan perubahan script beberapa file *.php pada folder controllers antara lain :
-analisis_indikator.php
-analisis_kategori.php
-analisis_klasifikasi.php
-analisis_laporan.php
-analisis_periode.php
-garis.php
-main.php
-siteman.php

rubah script redirect('siteman');   jadi  redirect('nama_alamat_sesuai_anda');

3. dan selanjutnya lakukan perubahan pada header.php yg terdapat di folder views
pada line ke 69 terdapat :

<li><a href="<?php echo site_url()?>siteman"><i class="fa fa-power-off fa-lg"></i>Log Out</a></li>

rubah jadi 	:
<li><a href="<?php echo site_url()?>nama_alamat_sesuai_anda"><i class="fa fa-power-off fa-lg"></i>Log Out</a></li>

smoga bermanfaat dan dapat meminimalisir orang" yg iseng,, hho

**Comment by hansahdarmawan** [comment]
untuk perubahan alamat login/siteman bisa dilakukan perubahan script pada beberapa folder yang terdapat di donjo-app antara lain config , 
controllers dan views dengan rincian perubahan sebagai berikut : 
1. pada folder donjo-app/config/ lakukan perubahan pada routes.php
dari : 
```
$route['default_controller'] = 'main';
$route['404_override'] = '';
$route['translate_uri_dashes'] = FALSE;

```
jadi  

```
$route['default_controller'] = "main";
$route['404_override'] = '';
$route['nama_alamat_sesuai_anda']='siteman';
$route['siteman']='404';
```

2.  selanjutnya lakukan perubahan script beberapa file *.php pada folder controllers antara lain :
-analisis_indikator.php
-analisis_kategori.php
-analisis_klasifikasi.php
-analisis_laporan.php
-analisis_periode.php
-garis.php
-main.php
-siteman.php

rubah script `redirect('siteman'); `  jadi  `redirect('nama_alamat_sesuai_anda');`

3. dan selanjutnya lakukan perubahan pada header.php yg terdapat di folder views
pada line ke 69 terdapat :

`<li><a href="<?php echo site_url()?>siteman"><i class="fa fa-power-off fa-lg"></i>Log Out</a></li>`

rubah jadi 	:
`<li><a href="<?php echo site_url()?>nama_alamat_sesuai_anda"><i class="fa fa-power-off fa-lg"></i>Log Out</a></li>`

smoga bermanfaat dan dapat meminimalisir orang" yg iseng,, hho

**Comment by SahlaniAfnan** [comment]
makasih infonya kang @hansahdarmawan, Ilmu yang sangat bermanfaat dan menambah kepahaman saya tentang dunia coding...

**Comment by eddieridwan** [comment]
Issue ini akan kami tutup. Silakan buka lagi kalau perlu.
