### ISSUE TITLE
Fitur: Pada waktu restore database gagal, tidak ada info sebab kegagalan

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#93]
Langkah yang diikuti:
1. Pada modul Administrasi, pergi ke laman Backup/Restore (klik Database > Backup/Restore)
2. Pilih file yang melebihi setting ukuran file maksimum di php.ini di server SID (biasanya maksimum tsb 2M) untuk di-restore dan klik Restore

Restore akan gagal, tetapi pengguna tidak diberitahu sebab kegagalan.

**Comment by afa28** [comment]
Duplicate of #2940
