### ISSUE TITLE
Embed Video Tidak terbaca

### ISSUE THREAD

**Issue by SahlaniAfnan** [OpenSID/OpenSID#930]
Embed video jika masih di modul admin terbaca, namun di tampilan Website tidak terbaca....

![embed video 1](https://user-images.githubusercontent.com/15683308/38639487-916ef82a-3dfb-11e8-9f0b-f11d5221dea0.jpg)

![embed video 2](https://user-images.githubusercontent.com/15683308/38639496-9a49439c-3dfb-11e8-9892-68731d2140ad.jpg)

![embed video 3](https://user-images.githubusercontent.com/15683308/38639502-a032a26c-3dfb-11e8-976e-3bb11d3371d7.jpg)

**Comment by Cakwidod** [comment]
embed video di halaman web tidak terbaca, tapi dihalaman admin terbaca

**Comment by egodasa** [comment]
@eddieridwan Issue ini bagaimana Mas? Apakah sebaiknya di close saja?

**Comment by bila2015** [comment]
jangan diclose dulu, solusinya gimana itu karena saya juga mengalami hal yang sama
