### ISSUE TITLE
Data : Buat sinkron data penduduk dengan data BDT 2018

### ISSUE THREAD

**Issue by haryandi** [OpenSID/OpenSID#931]
Sekarang setiap desa survei penduduk unduk menginput data bdt, dan setiap bulan nya tersinkron ke pusat, bagai mana biar tidak nginput data 2 x dan bisa menghemat waktu, dan data nya sesuai.. tks

**Comment by eddieridwan** [comment]
indikator survei nya seperti ini https://drive.google.com/file/d/1NO5eEPvUWXgouABu9w7ayhph8IjHAFQx/view
