### ISSUE TITLE
Security: Pindahkan folder _desa_ di luar folder _public_html_

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#932]
Sekarang folder _desa_ disimpan di folder _public_html_. Karena folder ini berisi informasi yang sensitif, sebaiknya dipindahkan, karena file di _public_html_ bisa diakses siapa saja.

**Comment by eddieridwan** [comment]
Beberapa diskusi meletakkan file di luar _public_html_:

https://paragonie.com/blog/2015/10/how-securely-allow-users-upload-files
https://forums.phpfreaks.com/topic/249604-how-to-url-link-to-files-outside-of-webroot/
https://bytes.com/topic/php/answers/886538-retrieve-images-located-outside-web-root-using-php

**Comment by metalab25** [comment]
Apa tidak semakin beresiko kalo diletakan pada root directory

**Comment by ind0saputra** [comment]
secara akses, file di luar public_html tidak bisa diakses via web. akan tetapi apabila dilihat dari celah keamanan masih mungkin terjadi. prinsipnya sama dg folder/file yang bisa diakses oleh user secara remote baik melalui web, ftp, ssh dsb (hal ini perlu permission dan owner yang sesuai, biasanya saya kasih 755 utk folder dan 644 utk file), bahkan apabila user bisa akses server dan login bisa hapus semua :slightly_smiling_face:
