### ISSUE TITLE
Perlu Ada Pilihan Penghasilan Form Data Kependudukan Dan Statistika

### ISSUE THREAD

**Issue by muhamaddifa** [OpenSID/OpenSID#933]
Perlu Ada Pilihan Penghasilan Form Data Kependudukan Dan Statistika Untuk Mempermudah

**Comment by metalab25** [comment]
@muhamaddifa :  perlu dijelaskan lebis spesifik

**Comment by muhamaddifa** [comment]
![image](https://user-images.githubusercontent.com/38423803/42267569-897269e2-7fa3-11e8-8b0d-a04fc34269e4.png)

**Comment by afa28** [comment]
Apakah ini untuk mendapatkan data penghasilan data penduduk desa??? Dan kemudian bisa disanjikan dalam bentuk statistik???

**Comment by afa28** [comment]
> > Apakah ini untuk mendapatkan data penghasilan data penduduk desa??? Dan kemudian bisa disanjikan dalam bentuk statistik???
> 
> Betul pa, agar bisa mengetahui penghasilan penduduk tersebut berapa dan mengetahui statistik nya juga rata2 pengahsilan didesa tersebut berapa
> 
> agar ketika mencetak surat keterangan kurang mamapu juga bisa di cantumkan , agar tidak sembarangan

Bisa diberikan contohnya pak???

Misal rentang pengahasilannya, biar ada gambaran.

**Comment by mizwaruddin** [comment]
Sudah ada di menu analisis. Untuk isian di data kependudukan sebaiknya tidak dihasilkan dari hasil survey yg sewaktu2 dapat berubah, melainkan data yang didukung bukti otentik.

**Comment by andifahruddinakas** [comment]
Bisa gunakan modul analisis.
