### ISSUE TITLE
Bug: di surat kelahiran, hari selalu 'Kamis'

### ISSUE THREAD

**Issue by djowah** [OpenSID/OpenSID#935]
Pada Surat Kelahiran, untuk hari dan tanggal tidak singkron... Hari selalu "Kamis" Padahal tanggal sudah betul...
![screenshot_13](https://user-images.githubusercontent.com/36688215/38912204-2fd0ce60-42fe-11e8-8d3f-fca74c9000c7.png)

Tanggal 29 oktober 2011 seharusnya "SABTU"

**Comment by eddieridwan** [comment]
@djowah , harap beri penjelasan lebih rinci:

- versi berapa?
- untuk data siapa: ibu, ayah, yang lahir, dsbnya?
- data warga dari database atau data bukan warga?

Karena issue serupa (https://github.com/OpenSID/OpenSID/issues/736) sudah diselesaikan dan ada sejak v2.9

**Comment by djowah** [comment]
Saya menggunakan versi 2.11 data bayi yang penduduk setempat

Pada tanggal 18 Apr 2018 12.42 PM, "Eddie Ridwan" <notifications@github.com>
menulis:

**Comment by djowah** [comment]
Bayi dari database... Saya sudah coba instalasi ulang tetap saja begitu...

Pada tanggal 19 Apr 2018 12.31 PM, "Ratno Khaliki" <mz.ratno@gmail.com>
menulis:

**Comment by balongbesuk** [comment]
OpenSID 2.11 saya aman baik yang lahir tahun 2013 ataupun yang baru lahir, hari bayi sudah betul menunjukkan hari pada tanggal yang dipilih,

![untitled23](https://user-images.githubusercontent.com/35319600/39001605-e155d1da-4420-11e8-84da-5f3bca65d8a6.jpg)


![untitled233](https://user-images.githubusercontent.com/35319600/39001779-4b2147fc-4421-11e8-852c-72c74e235048.jpg)

**Comment by djowah** [comment]
Saya mendapati masalah tersebut kalau data bayi dari database penduduk...
Untuk input bayi baru atau belum masuk database penduduk, hari sudah benar
atau sesuai... Mungkin komputer saya yang bermasalah....
Terimakasih untuk tanggapan teman teman OpenSider..

Pada tanggal 19 Apr 2018 10.31 PM, "balongbesuk" <notifications@github.com>
menulis:

**Comment by balongbesuk** [comment]
sudah saya tes untuk penduduk yang sudah dalam database memang Bug "tampilan" hasilnya benar

![untitled23](https://user-images.githubusercontent.com/35319600/39032647-93390918-4498-11e8-8382-4a1ef98ec7fc.jpg)

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
