### ISSUE TITLE
Jumlah Artikel Ditampilkan

### ISSUE THREAD

**Issue by bizril** [OpenSID/OpenSID#936]
Mau tanya cara setting jumlah artikel yang ditampilkan di homepage (misal ingin ditampilkan hanya 5 artikel saja), apakah bisa disetting? sudah cari di menu apapun engga ketemu.
Trims

**Comment by balongbesuk** [comment]
bagus nih bisa meringankan beban loading website jg

**Comment by hansahdarmawan** [comment]
untuk setingan jumlah artikel bisa dilakukan perubahan jumlah data yang terdapat di folder opensid/donjo-app/models/first-artikel_m.php --> lakukan pengeditan pada baris 52   dari $cfg['per_page'] = 8; jadi	$cfg['per_page'] = 5;   lakukan save dan refresh halaman webny..

**Comment by eddieridwan** [comment]
@hansahdarmawan sekalian kirim pull request. Ikuti panduan: https://github.com/OpenSID/OpenSID/wiki/Panduan-mengirimkan-perubahan-repo-OpenSID. Jangan lupa lakukan testing untuk berbagai skenario pengguna.

Juga baca: https://github.com/OpenSID/OpenSID/wiki/Cara-Ikut-Mengembangkan-OpenSID.

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR #1742
