### ISSUE TITLE
Manajemen akses SID: operator klik menu analisis, plan dan pengaturan langsung log out

### ISSUE THREAD

**Issue by sugiantoe** [OpenSID/OpenSID#937]
Manajemen aksis SID

tingkat user: operator

apakah menu analisis, plan dan pengaturan tidak boleh diakses oleh operator? saat saya coba klik menu tersebut, aplikasi langsung log out.

![operator](https://user-images.githubusercontent.com/28652833/39007620-74c44c4e-4430-11e8-8f2f-4b0230884080.jpg)

note:
- OpenSid versi 2.11
- tes dilocalhost, karena saya tidak bisa log in di web demo, apakah hanya saya? 
( http://demo.opensid.info/index.php/siteman. Masukkan Username = admin dan Password = sid304. )

**Comment by sugiantoe** [comment]
ternyata sudah ada issue serupa #885 
jika tidak ada akses untuk operator, apakah tidak sebaiknya menu tersebut disembunyikan saja.

**Comment by eddieridwan** [comment]
Sudah diterapkan berdasarkan spesifikasi hak akses di http://bit.ly/2Vhqmyz
