### ISSUE TITLE
Ubah penerapan teks berjalan, bukan sebagai artikel

### ISSUE THREAD

**Issue by sugiantoe** [OpenSID/OpenSID#938]
Manajemen akses SID

tingkat user : kontributor

berita/artikel yang ditulis kontributor langsung aktif di tampilan informasi website (tanpa aktifasi dari redaksi / operator), meskipun status berita tidak aktif.

![kontributor](https://user-images.githubusercontent.com/28652833/39008355-a49dc4fc-4432-11e8-9660-eae2ea448f56.jpg)

note:
- OpenSid versi 2.11
- tes dilocalhost, karena saya tidak bisa log in di web demo, apakah hanya saya?
( http://demo.opensid.info/index.php/siteman. Masukkan Username = admin dan Password = sid304. )

**Comment by didikkurniawan** [comment]
@sugiantoe mohon maaf pak untuk di saya bug tersebut tidak teridentifikasi. boleh mnta SC dari tampilan awalnya yg menampilkan artikel tsb.

**Comment by sugiantoe** [comment]
![image](https://user-images.githubusercontent.com/28652833/39343140-84762e48-4a05-11e8-8b7d-5fc20bb50d34.png)

ini screen shot teks berjalan yang ditulis oleh kontributor, status artikel TIDAK aktif, namun teks berjalan sudah tampil.

**Comment by eddieridwan** [comment]
@sugiantoe : teks berjalan adalah kasus khusus -- saat ini tidak dicek aktif atau tidak. Penerapan saat ini peninggalan SID CRI. Mungkin sebaiknya tidak diterapkan sebagai artikel -- karena isinya hanya teks, dan sifatnya bukan artikel. Sepertinya lebih mirip penanganan widget atau slider (yaitu spesifik -- tidak numpang pada artikel).

Kalau itu yg anda maksud, sebaiknya topik issue ini diganti menjadi misalnya: "Ubah penerapan teks berjalan, bukan sebagai artikel".

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.

**Comment by ariandii** [comment]
Terkait dengan penerapan tambahan Menu Teks Berjalan pada 19.05-pasca yang mengambil record dari TABLE `setting_aplikasi` di database, value pada tabel tersebut hanya 200 karakter. Saran agar dapat ditambah jumlah karakternya, dengan pertimbangan kata yang akan dimunculkan pada teks berjalan tersebut panjang dan agar informasi jelas.

Terima kasih.

**Comment by eddieridwan** [comment]
@ariandii silakan usulkan berapa panjang teks yg memadai. Dan silakan kirim pull requestnya sekalian. Terima kasih.

**Comment by ariandii** [comment]
usul pak, untuk panjang teks jika ada ketentuan max nya, bisa diubah mencapai 300 karakter, namun jika diijinkan value pada tabel tersebut untuk menggunakan text, bukan variable supaya karakternya tanpa batas. terima kasih.
