### ISSUE TITLE
Kontrak: modernkan tampilan modul Admin

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#939]
Issue ini untuk mendokumentasikan arahan & pertimbangan teknis untuk pengerjaan 'memodernkan tampilan modul Admin'.

Programmer memerlukan petunjuk "ttg rule modernisasi modul admin tsb. dia minta penjelasan hal- hal apa saja yg dilarang/tdk di bolehkan/ tdk di inginkan kwan2 programer yg lain.. dlm melakukan modernisasi admin nantinya... supaya lbh enak dan nyaman.. dan bisa di hindari....???"

Materi yg disiapkan untuk pekerjaan ini nantinya perlu kita salin ke panduan, karena akan berlaku bagi semua kontributor OpenSID.

**Comment by eddieridwan** [comment]
Pedoman umum kontribusi pada OpenSID ada di:

- https://github.com/OpenSID/OpenSID/wiki/Cara-Ikut-Mengembangkan-OpenSID, dan
- https://github.com/OpenSID/OpenSID/wiki/Panduan-mengirimkan-perubahan-repo-OpenSID

Yaitu, pada dasarnya perlu menggunakan _git_ dan mengirim hasil pekerjaan sebagai _pull request_.

**Comment by eddieridwan** [comment]
Untuk kodingnya sendiri, pedoman umum:

Ikuti praktik terbaik dalam koding anda. 

Gunakan coding style standar:
* [PSR-1](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-1-basic-coding-standard.md)
* [PSR-2](https://www.php-fig.org/psr/psr-2/)

Lakukan testing secara saksama sebelum koding anda bisa dianggap selesai.

Petunjuk lain :

- hindari menggunakan _inline style_. Sejauh mungkin letakkan semua css di file stylesheet di folder _assets/css. Ini akan memudahkan kustomisasi tampilan oleh pengguna melalui folder _desa/css_
- gunakan penamaan variabel yang jelas; tulis komentar mengenai pengunaan variable. Terutama parameter fungsi; misalnya apa itu $p? apa itu $o? tipe data apa yg bisa saya oper ke $p dan $o itu? string, array, objek, integer, boolean, atau apa?

**Comment by ombimo** [comment]
mumpung ada penataan assets, lebih baik jika assets yang berupa library (bootstrap, jquery, jquery-ui, tinymce, ...) dipisah dari assets yang buatan sendiri.
seperti dipindah ke folder 

> assets/vendor/bootstrap
> assets/vendor/jquery
> ....
> atau
> assets/library/bootstrap
> assets/library/jquery
> ...

**Comment by eddieridwan** [comment]
Pertimbangkan menggunakan template engine, untuk memisahkan secara jelas logic dan penampilan (supaya lebih mudah dimengerti dan dimaintain):

- template parser Codeigniter, atau 
- template engine library, seperti Smarty atau Twig (https://www.sitecrafting.com/top-5-php-template-engines/)

**Comment by egodasa** [comment]
Saya vote blade untuk template engine. Karena sintaknya mudah dipahami dan sudah banyak digunakan. Terutama pengguna laravel. Tapi instalasinya harus menggunakan composer.

**Comment by eddieridwan** [comment]
Contoh tampilan layar:

![modul-admin-01](https://user-images.githubusercontent.com/249563/39414745-96ef317a-4c7e-11e8-99fc-d1719524bba1.jpg)
![modul-admin-02](https://user-images.githubusercontent.com/249563/39414746-9725023c-4c7e-11e8-9746-699ce64fd812.jpg)
![modul-admin-03](https://user-images.githubusercontent.com/249563/39414747-975aadc4-4c7e-11e8-8d66-35fb30f39717.jpg)
![modul-admin-04](https://user-images.githubusercontent.com/249563/39414749-979075c6-4c7e-11e8-99e5-e4ec330afed4.jpg)
![modul-admin-05](https://user-images.githubusercontent.com/249563/39414750-97c6a876-4c7e-11e8-9f8d-6141ef301090.jpg)
![modul-admin-06](https://user-images.githubusercontent.com/249563/39414751-97fe1c2a-4c7e-11e8-9a11-c7d413b37474.jpg)
![modul-admin-07](https://user-images.githubusercontent.com/249563/39414752-98364a64-4c7e-11e8-8d3d-dc82046e89d3.jpg)
![modul-admin-08](https://user-images.githubusercontent.com/249563/39414753-986c585c-4c7e-11e8-9103-01a9f4b00588.jpg)
![modul-admin-09](https://user-images.githubusercontent.com/249563/39414754-98a3e088-4c7e-11e8-8993-cf3386b84269.jpg)
![modul-admin-10](https://user-images.githubusercontent.com/249563/39414757-98db6b34-4c7e-11e8-8d56-a951d3181489.jpg)
![modul-admin-11](https://user-images.githubusercontent.com/249563/39414758-99159ab6-4c7e-11e8-929d-0f0815195d3f.jpg)
![modul-admin-12](https://user-images.githubusercontent.com/249563/39414759-994bd0ea-4c7e-11e8-86be-290245832095.jpg)
![modul-admin-13](https://user-images.githubusercontent.com/249563/39414760-99965066-4c7e-11e8-8eff-8c2aad3c7106.jpg)

**Comment by suphm** [comment]
Wah bagus ini. usul pakai composer tidak perlu push vendor/script library lain  seperti jquery dlsb.

**Comment by balongbesuk** [comment]
mohon maaf tidak bisa bantu usul, karena tidak paham programing, hanya pengguna desa, ikut teman teman programer gimana baiknya,

**Comment by esyede** [comment]
Mungkin teman2 bisa menggunakan ini untuk usul blade https://github.com/EFTEC/BladeOne
