### ISSUE TITLE
Security: unduh surat di menu Cetak Surat > Arsip Layanan tidak boleh langsung

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#941]
Saat ini unduh surat dan lampiran di menu _Cetak Surat > Arsip Layanan_ langsung mengarah ke file di folder desa, sehingga bisa diketahui pengguna. Ganti menggunakan script untuk mengunduh surat dan lampiran dari arsip.

**Comment by egodasa** [comment]
Seperti ini? https://stackoverflow.com/questions/12295604/php-simple-download-script
Pas kita cetak dokumen juga langsung mengarah ke lokasi asli file. Apakah juga perlu diterapkan di tombol cetak?

**Comment by eddieridwan** [comment]
@egodasa ikuti contoh yang sudah ada di `controllers/Surat_masuk.php` action `unduh_berkas_scan()`. Yaitu lihat cara kerja tombol _Unduh_ di menu _Sekretariat > Surat Masuk_.

Tapi coba pindahkan logicnya ke model (untuk issue ini masukkan ke `Surat_keluar_model.php`). Karena praktek baik umumnya berusaha agar controller tidak membengkak, dan memasukkan logic ke model yang berurusan dengan data yg bersangkutan.

**Comment by egodasa** [comment]
Maaf Mas, apakah sebaiknya method `unduh_berkas_scan()` dijadikan sebagai method di helper? Jadi nanti semua dokumen yang diunduh bisa memakai method tersebut.

**Comment by eddieridwan** [comment]
@egodasa ya, setuju.

**Comment by egodasa** [comment]
Mau dijadikan ke helper atau extend controller CI atau Mas punya saran? kalau extend controller, nanti semua berkas bisa diunduh dengan url yang sama. Semacam `controller/unduh_berkas/:id_berkas`?

**Comment by suphm** [comment]
CI sudah sediakan helper http://codeigniter.com/user_guide/helpers/download_helper.html

**Comment by egodasa** [comment]
Helper tersebut memang digunakan @suphm yaitu `force_download()`

**Comment by egodasa** [comment]
Maaf Mas @eddieridwan lokasi unduh surat semuanya di folder desa/arsip ya?

**Comment by eddieridwan** [comment]
@egodasa peran setiap subfolder di folder desa ada di https://github.com/OpenSID/OpenSID/wiki/Folder-Desa. Kalau ada yang salah atau kurang lengkap, silakan tanyakan di https://opensid.slack.com/messages/C6BLLFETH/details/ atau kalau sudah yakin silakan perbaiki sendiri.

**Comment by egodasa** [comment]
@eddieridwan Maaf Mas, saya masih bingung. Kalau `unduh_berkas_scan()` dijadikan helper, berarti kita masih perlu bikin method di controller untuk menjalankan helper tersebut. Saya kepikiran untuk memindahkan method tersebut ke class CI untuk di extend agar semua class bisa memakai method tersebut dengan cara extend class `MY_controller`

**Comment by eddieridwan** [comment]
Method di helper bisa dipanggil dari mana saja, termasuk dari controller atau model. Yang dipindahkan adalah proses mengambil/menyiapkan berkas untuk diunduh. `force_download` nya sendiri tetap di controller. 

Tetapi sebaiknya untuk tahap ini pindahkan ke model `Surat_keluar_model.php` saja. Karena yang tahu tempat penyimpanan arsip dan tahu struktur penamaan berkas harusnya model itu. Nanti kalau kita kerjakan pengunduhan lainnya, mungkin bisa di-abstract lebih lanjut dan sebagian yang sifatnya umum dipindahkan ke helper.

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR #995
