### ISSUE TITLE
Bug: ketika menghapus surat di Arsip Layanan Surat

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#943]
Bug ketika menghapus surat di Arsip Layanan Surat, keluar peringatan error data gagal disimpan dan tampilannya seperti gambar dibawah ini : 
![screenshot 2018-04-21 22 58 34](https://user-images.githubusercontent.com/25834335/39085612-d328c93a-45b7-11e8-8808-dde2c88ae5c0.png)

**Comment by egodasa** [comment]
Tapi datanya masih tetap kehapus bukan? Hanya muncul pesan error yang gk sesuai, yang seharusnya data berhasil dihapus, tetapi malah pesan gagal disimpan

**Comment by eddieridwan** [comment]
Masalah ini disebabkan cara kerja $this->db->error() yang berbeda di CI v3.x.

Solusinya, ubah semua penggunaan kalimat itu. 

Sdh dicommit ke master.

**Comment by egodasa** [comment]
Maaf Mas @eddieridwan , menurut dokumentasi cara pengecekan errornya adalah `if(!$this->db->where('id', $id)->delete('log_surat')) {
			$_SESSION['success'] = -1;
		}`
