### ISSUE TITLE
Usulan penambahan fungsi data persil

### ISSUE THREAD

**Issue by kelbatuix** [OpenSID/OpenSID#950]
Mohon izin menyampaikan usulan, sekiranya pencatatan persil tanah dapat juga buatkan dalam bentuk pencatatan GPS yang kemudian menjadi peta otomatis pada basemap open street map seperti pada laman peta online bpn peta.bpn.go.id
Demikian, dan terima kasih kami atas perbaikan2 pada website yg sangat membantu untuk pelayanan di kelurahan.

**Comment by mizwaruddin** [comment]
@afa28 ganda
