### ISSUE TITLE
Bagaimana Cara merubah (rename) folder desa ?

### ISSUE THREAD

**Issue by codesimple1000** [OpenSID/OpenSID#953]
Bagaimana Cara merubah (rename) folder desa ?

**Comment by eddieridwan** [comment]
Penggunaan OpenSID harap ditanyakan di https://www.facebook.com/groups/OpenSID/.

Issue tempat melaporkan bug atau membuat usulan. Lihat panduan https://github.com/OpenSID/OpenSID/wiki/Pengelolaan-Masalah-dan-Permintaan-Perbaikan-SID.
