### ISSUE TITLE
bug: error page saat operator hapus log penduduk

### ISSUE THREAD

**Issue by sugiantoe** [OpenSID/OpenSID#954]
error terjadi saat operator menghapus log penduduk (seharusnya operator tidak bisa menghapus log penduduk).

![image](https://user-images.githubusercontent.com/28652833/39193780-7ddcd86c-4806-11e8-936f-90193fe851d0.png)

![image](https://user-images.githubusercontent.com/28652833/39193874-ad2361ea-4806-11e8-9927-c620f2e6047f.png)

**Comment by sugiantoe** [comment]
data bisa dihapus jika dicheklis terlebih dahulu data yang mau dihapus, kemudian klik tombol hapus di atas.

![image](https://user-images.githubusercontent.com/28652833/39194405-dd8f8ed4-4807-11e8-8bc6-6d85b10a8d23.png)

**Comment by egodasa** [comment]
Maaf Mas, pada gambar pertama adressbarnya tidak sesuai dengan halamannya. Halaman tersebut saya cek didemo seharusnya `http://demo.opensid.info/index.php/penduduk`

**Comment by eddieridwan** [comment]
Ternyata bug ini sudah ada sejak SID 3.10. Terima kasih telah melaporkan.

Tapi komentar anda betul: apakah sebaiknya fitur ini dihilangkan saja, supaya pengguna tidak bisa menghapus log penduduk?

**Comment by eddieridwan** [comment]
@egodasa error terjadi di halaman _Log Penduduk_ bukan di halaman _Penduduk_. Lihat gambar berikut.

<img width="982" alt="error-log-penduduk" src="https://user-images.githubusercontent.com/249563/39235016-25ec4838-48b8-11e8-8ce4-d58e37bd28e9.png">

Tetapi pertanyaan yang lebih penting adalah: "apakah sebaiknya kita hilangkan saja tombol hapus, karena sebaiknya pengguna tidak diperbolehkan menghapus log penduduk?".

**Comment by egodasa** [comment]
Apakah tombol hapus jadi dihilangkan untuk semua pengguna termasuk admin? Karena Saya sudah coba hapus tombol hapusnya jadi seperti ini.
![hapus](https://user-images.githubusercontent.com/9961837/39344208-35ba6dc2-4a0b-11e8-89a9-7b56eacb33d1.jpg)

**Comment by eddieridwan** [comment]
@egodasa Belum ada tanggapan dari POKJA. Kita perlu kesepakatan dulu dari POKJA.

**Comment by MUHAMMADRANGSEL** [comment]
Untuk tombol hapus sebaiknya muncul ketika pengguna statusnya menjadi admin

**Comment by MUHAMMADRANGSEL** [comment]
Sehingga seragam dengan yang lain,,, yg dimana hanya admin saja yg bisa menghapus

**Comment by eddieridwan** [comment]
@MUHAMMADRANGSEL : Tetapi pertanyaan yang lebih penting adalah: "apakah sebaiknya kita hilangkan saja tombol hapus, karena sebaiknya pengguna tidak diperbolehkan menghapus log penduduk?".

Silakan komentar, juga POKJA lainnya. Menurut kami, lebih baik tombol hapus dihilangkan sama sekali dari _log penduduk_.

**Comment by eddieridwan** [comment]
Ganti tombol _Hapus_ menjadi _Kembalikan Status_, untuk mengembalikan status penduduk menjadi _hidup_.

**Comment by MUHAMMADRANGSEL** [comment]
Usul bagus itu bung Eddie

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
