### ISSUE TITLE
Bug: di surat kematian, drop-down konfirmasi yang meninggal keliru menampilkan nama untuk kolom alamat

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#956]
Dilaporkan @balongbesuk:

![untitled23](https://user-images.githubusercontent.com/35319600/39033221-45d59e0e-449b-11e8-81b7-99b615c4122c.jpg)

alamat pemohon surat menampilkan nama,

**Comment by egodasa** [comment]
Saya rasa penyebab alamat menampilkan nama karena ini : https://github.com/OpenSID/OpenSID/blob/master/donjo-app/models/Penduduk_model.php#L1096

Namun pada query https://github.com/OpenSID/OpenSID/blob/master/donjo-app/models/Penduduk_model.php#L1091 tidak menghasilkan alamat sehingga tidak ada alamat yang ditampilkan.

Dan sebenarnya di baris itu juga, kita bisa menggunakan concat untuk memformat output dari sql tanpa perlu looping lagi kedata yang sudah kita dapatkan tersebut.

**Comment by egodasa** [comment]
Kira-kira seperti ini menurut Saya seharusnya https://gist.github.com/egodasa/d288770ea6ae0115213c4feff8d8018f Namun diquery asli tersebut yaitu tabel tweb_penduduk, hanya ada kolom "alamat_sebelumnya" dan "alamat_sekarang". Dan di Penduduk_model, diperlukan kolom "alamat".

Dan diskrip yang Saya buat tersebut, alamat saya ganti sementar dengan nik karena kolom alamat tidak ada di tabel tweb_indonesia.

**Comment by eddieridwan** [comment]
@egodasa : lihat contoh di surat lain, misalnya surat_ket_penduduk. Sebaiknya diseragamkan saja dengan surat yang lain. Di situ 'alamat' menampilkan RW, RW dan Dusun berdasarkan KK penduduk tersebut.

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR #960
