### ISSUE TITLE
Statistik umur? dibawah 1 Tahun?

### ISSUE THREAD

**Issue by balongbesuk** [OpenSID/OpenSID#957]
![sedang_1519876576_rastraii](https://user-images.githubusercontent.com/35319600/39224305-e3316312-4870-11e8-9326-b11840ea8f5b.jpeg)

pemahaman saya jika dibawah 1 tahun rentan usia 0 - 0 tahun, jika 0 - 1 tahun penduduk yang berusia 1 tahun ikut masuk dalam data statistik,

**Comment by hansahdarmawan** [comment]
Kalo mnurut pemahaman saya itu sama aja  dibawah 1 tahun pengertiannya 0 -1 jg..

**Comment by balongbesuk** [comment]
jika rentan usia yang dipilih 0 - 1 tahun maka penduduk yang berusia 1 tahun akan ikut masuk dalam data statistik penduduk, 

saya pikir untuk pemilihan "dibawah 1 tahun untuk rentan usia 0-1 kurang pas, dan seharusnya 0 - 0

saya menemukan ini karena saya baru saja dimintai data statistik penduduk dengan isian sbb :
![sedang_1519876576_rastraii](https://user-images.githubusercontent.com/35319600/39226604-96514d0c-487d-11e8-84a3-cce031e2e496.jpeg)

**Comment by afa28** [comment]
Buat issue baru jika masih bermasalah.
