### ISSUE TITLE
Export Import Database sampai 9 MB

### ISSUE THREAD

**Issue by djowah** [OpenSID/OpenSID#958]
Selamat siang... mengapa import database .sql saya sampai hampir 9 MB, sedangkan untuk import maksimal 2 MB?

**Comment by eddieridwan** [comment]
Pertanyaan penggunaan OpenSID harap ditanyakan di https://www.facebook.com/groups/OpenSID/.

Issue digunakan khusus untuk melaporkan bug (yang yakin adalah bug) dan usulan (cek dulu belum dilaporkan sebelumnya).
