### ISSUE TITLE
Security: Celah bisa unggah script php melalui unggah logo desa

### ISSUE THREAD

**Issue by mugi789** [OpenSID/OpenSID#963]
masih ada celah/bug pada upload logo desa
Perlu diperbaiki lagi

**Comment by egodasa** [comment]
Maaf bisa diperjelas langkah-langkah hingga munculnya bug tersebut?

**Comment by eddieridwan** [comment]
Coba namakan suatu file php menggunakan ekstensi .jpg, misalnya _script.php.jpg_.
Di menu SID Home > Identitas Desa, coba unggah file tersebut sebagai logo. Bisa diunggah tanpa error, padahal seharusnya tidak bisa.

Error ini disebabkan saat ini fitur unggah logo menggunakan mime type yg disediakan browser -- yang mudah ditipu. 

Method yang bersangkutan: `update()` di `Config_model.php`, dan `UploadLogo()` di `pict_helper.php`.

Ubah supaya menggunakan library _upload_ yang disediakan Codeigniter. Lihat contoh penggunaan library _upload_ di `Surat_masuk_model.php`. Pelajari dan lihat apakah bisa dibuat menjadi method umum yang bisa diletakkan di `pict_helper.php` untuk digunakan di semua fungsi unggah berkas.

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
