### ISSUE TITLE
Security: celah security saat unggah foto pengguna di Setting User

### ISSUE THREAD

**Issue by doublegunz** [OpenSID/OpenSID#968]
coba testing unggah shell sederhana dengan ekstensi php di menu pengaturan pengguna, ternyata masih bisa diunggah..
![selection_001](https://user-images.githubusercontent.com/13196484/39403560-36cd359c-4ba9-11e8-84a5-60a6641ad747.png)

**Comment by eddieridwan** [comment]
@doublegunz : Tools apa yang digunakan untuk mengunggah? Upload biasa sdh tidak bisa. Mohon info supaya kami bisa coba menggunakan untuk testing.

**Comment by eddieridwan** [comment]
File shell.php diawali signature untuk file jpeg (ffd8 ffe0). Walaupun demikian, kalau diunggah biasa, library _upload_ Codeigniter bisa mendeteksi bukan jpeg. Jadi perlu tool lain untuk menipu library _upload_.

Solusi yg diterapkan kali ini adalah untuk mendeteksi file berisi script php secara langsung, sebelum dilempar ke library _upload_.

**Comment by eddieridwan** [comment]
Ternyata masalah ini ada di menu _Setting User_ bukan _Pengguna_. Dan masalahnya adalah penggunaan signature jpeg berhasil menembus/menipu pendeteksian mime type melalui:
```
    $finfo = finfo_open(FILEINFO_MIME_TYPE);
    $tipe_file = finfo_file($finfo, $lokasi_file);
```
Sekarang sudah diperbaiki dengan menambahkan pendeteksian file berisi script php secara langsung.
