### ISSUE TITLE
[pertanyaan] Kalau ganti temanya masih cara hard code ya?

### ISSUE THREAD

**Issue by suphm** [OpenSID/OpenSID#970]

**Comment by balongbesuk** [comment]
jika ada pertanyaan bisa ditanyakan ke https://www.facebook.com/groups/OpenSID/,  disini untuk pelaporan issue (bug/error) pada aplikasi,

OpenSID sudah memiliki 3 thema (default, hadakewa, dan batudaa ) ganti thema cukup di rupah pada setting modul aplikasi opensid https://github.com/OpenSID/OpenSID/wiki/Panduan-Konfigurasi-Aplikasi

**Comment by suphm** [comment]
OK thankyou, om.

**Comment by eddieridwan** [comment]
Pertanyaan teknis bisa ditanyakan di https://opensid.slack.com.

Untuk bergabung, klik http://bit.ly/opensid-slack dan buat akun.
