### ISSUE TITLE
Mohon konfirmasi, Arsip surat Ini cuma 3 baris?

### ISSUE THREAD

**Issue by suphm** [OpenSID/OpenSID#971]
Step:
- Lakukan cetak surat yang mana saja
- Buka Arsip Layanan

Hasilnya, di surat keluar atau rekam surat perseorangan cuma tiga baris. 
di versi sekarang. master (opensid@8e69684) malah 2 baris saja.

And #902 sepertinya belum fix.

**Comment by balongbesuk** [comment]
bisa di cek di demo.opensid.info pak, untuk perubahan / penambahan fungsi / fitur ,

scriptnya rekam surat perorangan nyontek dari script surat keluar,

**Comment by suphm** [comment]
yang sekarang aja om, yang di master

Sekarang saya tes lagi malah cuma 2 baris, apakah memang begitu.

**Comment by suphm** [comment]
maaf ini saya baru tahu, ternyata, di [Panduan Mencetak-Surat](https://github.com/OpenSID/OpenSID/wiki/Panduan-Mencetak-Surat#tombol-cetak) tidak akan merekam surat yang di cetak melainkan hanya yang diexpor doc yang akan direkam. tapi walau begitupun masih sedikit kesalahan. surat yang dicetak  masih direkam dan setiap cetak surat baru akan direkam lagi dengan menimpa data yang sebelumnya dicetak makanya kata saya cuma 3 baris (atau selalu 3 baris)
