### ISSUE TITLE
Bug: Menu Cetak Surat > "Rekam surat perseorangan" Tombol "Cetak" tapi mengunduh.

### ISSUE THREAD

**Issue by suphm** [OpenSID/OpenSID#972]

**Comment by eddieridwan** [comment]
Juga di menu _Arsip Layanan > Surat Keluar_.

**Comment by eddieridwan** [comment]
Mungkin ubah judul tombol, menjadi 'Surat', menunjukkan unduh surat -- untuk membedakan dengan unduh lampiran.

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
