### ISSUE TITLE
Tidak bisa bersihkan poligon wilayah desa.

### ISSUE THREAD

**Issue by suphm** [OpenSID/OpenSID#978]
### Bagaimana alurnya sampai muncul masalah?
Dari Home Desa
Ubah peta "wilayah Desa"
Buat gambar poligon wilayah.
Klik "Bersihkan"

### Apa yang terjadi?
Tombol "Bersihkan" tidak berfungsi.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.12
| Versi PHP        | 7.1
| Browser   | Chromium  65.0
|OS |Ubuntu 16

**Comment by egodasa** [comment]
@suphm Tombol "bersihkan" sudah dihilangkan dan diganti dengan tombol "trash" bawaan peta. Mungkin Mas mau close issue ini.

**Comment by suphm** [comment]
Ok om, sudah berfungsi juga ya.
