### ISSUE TITLE
Pindahkan dialog Wilayah Desa menggunakan OpenStreetMap

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#980]
### Bagaimana alurnya sampai muncul masalah?
Di SID Home > Identitas Desa klik tombol Wilayah Desa.

### Seperti apa yang diharapkan?
Dialog untuk mengubah peta Wilayah Desa di SID Home > Identitas Desa menggunakan OpenStreetMap.

### Apa yang terjadi?
Saat ini menggunakan Google Maps, sedangkan nanti pada tanggal 11 Juni 2018, penggunaannya akan memerlukan pendaftaran kartu kredit.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.12
| Versi PHP        | 
| System operasi   |

**Comment by egodasa** [comment]
Apakah opensid bakal beralih ke openstreetmap secara keseluruhan Mas? Berarti issue #900 gk berlaku lagi Mas? Karena kita gk pake google maps API lagi.

**Comment by balongbesuk** [comment]
desa saya masih pulih polos pak openstreetmap, hahaha, apalagi yang dipelosok,?

**Comment by eddieridwan** [comment]
@egodasa sepertinya begitu.

**Comment by egodasa** [comment]
Beneran pake OSM Mas? Kalau ini https://www.microsoft.com/en-us/maps/choose-your-bing-maps-api ?

**Comment by eddieridwan** [comment]
@egodasa kalau Google saja berbayar, apalagi Microsoft!

**Comment by egodasa** [comment]
Maaf gk keliatan Mas td :v

**Comment by eddieridwan** [comment]
Dialog Wilayah Desa maksudnya digunakan untuk membuat/mengupdate polygon batas wilayah desa. Fitur ini belum berfungsi.

Idealnya hasil update menggunakan dialog Wilayah Desa digunakan untuk menampilkan widget Peta Desa (issue #983).

**Comment by eddieridwan** [comment]
Apakah mungkin konversi wilayah desa yg ada di Google Maps ke OSM (mengambil data batas2 wilayah desa yg ada di Google Maps)?

**Comment by eddieridwan** [comment]
Sudah digabung ke master.
