### ISSUE TITLE
Pindahkan widget Peta Desa menggunakan OpenStreetMap

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/OpenSID#983]
### Bagaimana alurnya sampai muncul masalah?
Di modul Web, perhatikan widget _Peta Desa_. Kalau tidak tampil, aktifkan dulu widget ini di _Admin Web > Widget_.

### Seperti apa yang diharapkan?
Widget _Peta Desa_ menggunakan OpenStreetMap.

### Apa yang terjadi?
Saat ini menggunakan Google Maps, sedangkan nanti pada tanggal 11 Juni 2018, penggunaannya akan memerlukan pendaftaran kartu kredit.

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.12
| Versi PHP        | 
| System operasi   |

**Comment by egodasa** [comment]
@eddieridwan Pakai ini Mas jquerygeo.com? Atau udah diurus dimodul admin yang baru nanti?

**Comment by eddieridwan** [comment]
Pekerjaan memodernkan penampilan modul Admin tidak akan mengubah peta. Diskusi teknis konversi dari Google Maps ke OpenStreetMap kita lakukan di https://opensid.slack.com/messages/C7DDGHC1M/details/, karena akan berlaku pada semua issue terkait konversi peta. Silakan ke sana.

**Comment by eddieridwan** [comment]
@egodasa , saat ini widget Peta Desa disediakan sebagai contoh widget dinamis ubahan desa (bisa dihapus). Sebaiknya sekarang widget ini diubah menjadi widget sistem, dan menampilkan polygon wilayah desa yg dikerjakan di #980. Ikuti contoh widget Lokasi Kantor Desa.

**Comment by eddieridwan** [comment]
Apakah #981 dan #984 sudah dikerjakan?
Juga dialog mengedit wilayah desa tidak jalan di hosting http://demo.opensid.info -- bisa lihat? Di lokal ok.

**Comment by egodasa** [comment]
Nanti Saya kerjakan Mas. Sekarang lg gk pegang laptop. Jd gk bisa liat peta di web demo.

**Comment by egodasa** [comment]
@eddieridwan Widget peta desa sudah saya ubah jadi sistem Mas. Tapi untuk menampilkan widget tersebut, saya harus tambah widgetnya secara manual didatabase. Bagaimana cara Saya bikin PR nya? Apakah cukup dengan commit file peta wilayah desa tsb?

**Comment by eddieridwan** [comment]
@egodasa lihat komentar di PR #1016.

**Comment by eddieridwan** [comment]
Sudah digabung ke master.
