### ISSUE TITLE
penataan user

### ISSUE THREAD

**Issue by afri18** [OpenSID/OpenSID#99]
Bisa dibuatkan hak akses user seperti ini :
1. Administrator > semua
2. Operator > untuk menu admin webnya dihilangkan, saat ini ada
3. Redaksi > tetap seperti yg sudah ada, cuma artikel tidak langsung muncul alias terkunci dulu
4. Kontributor >Hanya bisa akses menu Analisis
Mungkin bung Eddie bisa bantu

**Comment by dadannurman** [comment]
Gan gimana kalo tambah 1 user > pengelola surat aja, jadi khusus untuk user pelayanan

**Comment by eddieridwan** [comment]
Sudah diterapkan, berdasarkan spesifikasi hak akses di http://bit.ly/2Vhqmyz
