### ISSUE TITLE
Bug: Foto di Widget Aparatur Desa masih menampilkan aparatur yang tidak aktif

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#990]
### Bagaimana alurnya sampai muncul masalah?
1. Klik ubah pada Menu SID Home ==> sub menu pemerintah desa
![screenshot 2018-05-04 23 17 59](https://user-images.githubusercontent.com/25834335/39636159-02194bf4-4ff2-11e8-9b8d-7c3dff55e28e.png)
2. Klik Status menjadi tidak aktif
![screenshot 2018-05-04 23 17 39](https://user-images.githubusercontent.com/25834335/39636214-265a2aa6-4ff2-11e8-9000-a7f043de87d5.png)
3. gambar di widget masih muncul
![screenshot 2018-05-04 23 18 13](https://user-images.githubusercontent.com/25834335/39636240-3a002eca-4ff2-11e8-8d94-579e84869a09.png)

### Seperti apa yang diharapkan?
1. Ketika sudah melakukan point 1 dan 2 diatas maka seharusnya Fhoto Aparatur Desa yang sudah 
     diubah menjadi tidak aktif di Widget Tidak Muncul 
2. Fhoto yang muncul diwidget hanya pemerintah desa yang statusnya AKTIF
### Apa yang terjadi?
Bikin Fhoto di WIdget tdk pas

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | pasca 2.12
| Versi PHP        | PHP Version 5.6.35
| System operasi   | windows 10

**Comment by egodasa** [comment]
@eddieridwan Cara penyelesaian terbaiknya gimana Mas? Aakah kita tambahkan `if pamong_status == 1` di https://github.com/OpenSID/OpenSID/blob/master/donjo-app/views/widgets/aparatur_desa.php#L31 atau kita edit sumber datanya dengan `SQL where pamong_status = 1` ?

**Comment by eddieridwan** [comment]
Mungkin `Pamong_model.list_data()` ditambah parameter untuk mengambil semua data atau yg aktif saja. Default semua. Misalnya di `Web_widget_model.get_widget_data()` bisa panggil `pamong_model->list_data($aktif=true);`

**Comment by eddieridwan** [comment]
Supaya lebih mudah memeriksa, sebaiknya status aktif/non-aktif setiap pamong desa ditampilkan di halaman _SID Home > Pemerintah Desa_. Tugas ini sudah dibuatkan issue #992.

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR #994

**Comment by MUHAMMADRANGSEL** [comment]
Thanks
