### ISSUE TITLE
Bug: Penambahan Program Bantuan Gagal

### ISSUE THREAD

**Issue by wongcilikpoenya** [OpenSID/OpenSID#991]
Penambhan  Program Bantuan gagal Ket : Unable to locate the specified class: Session.php
sebelumnya di OpenSid Versi 2.11 penambahan program bantuan tidak ada masalah, tapi di OpenSid Pasca 2.12 tidak bisa menambahkan program bantuan

**Comment by eddieridwan** [comment]
@wongcilikpoenya terima kasih telah melaporkan. Selalu gunakan template pelaporan yg disediakan pada waktu membuat issue baru. Selalu usahakan melampirkan tampilan layar error supaya lebih mudah dilacak.

**Comment by eddieridwan** [comment]
Sekarang sudah diperbaiki di versi pra-rilis.
