### ISSUE TITLE
Tambahkan Fitur Live Chat Pada Website

### ISSUE THREAD

**Issue by HerryWanda** [OpenSID/OpenSID#996]
### Informasi tambahan 
Kegunaan fitur live chat mepermudah masyarakat atau warga untuk berkomunikasi dengan pemerintah Desa/Nagari, dan memangkas biaya komunikasi . Mungkin banyak manfaat lain kalau kita menambahkan fitur live chat pada website..

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.x
| Versi PHP        | 
| System operasi   |

**Comment by balongbesuk** [comment]
sambil menunggu bisa menggunakan widget pihak ketiga kalau mau pak, https://whatshelp.io/widget

**Comment by HerryWanda** [comment]
Cara menggunakannya gimana mas balongbesuk..?

2018-05-07 10:38 GMT+07:00 balongbesuk <notifications@github.com>:

**Comment by balongbesuk** [comment]
semoga sedikit membantu https://www.mahadisuta.com/artikel/59cf6f6f5946f/tutorial-memasang-widget-aplikasi-chating-populer-di-website-anda

**Comment by suphm** [comment]
Ini bisa sebagai penyempurnaan [Layanan mandiri](/OpenSID/OpenSID/wiki/Layanan-Mandiri)

**Comment by balongbesuk** [comment]
simplenya tinggal pasang https://codepen.io/demoonkevin/pen/MvPEpV

**Comment by afa28** [comment]
Sebaiknya diterapkan scr mandiri u/ desa yg membutuhkan sj dgn cara penambahan plugin live chat pd tema yg ada.

**Comment by afa28** [comment]
Dan dilayanan mandiri jg sdah disediakan fitur pesan yg hanya bisa digunakan oleh warga yg sdah terdaftar.
