### ISSUE TITLE
NOMOR REGISTER SURAT

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#997]
### Bagaimana alurnya sampai muncul masalah?
Cetak Surat

### Seperti apa yang diharapkan?
Yang diharapkan ketika nomor surat sama maka tidak bisa cetak surat atau export surat

### Apa yang terjadi?
membuat nomor surat keluar berantakan

### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.12
| Versi PHP        | 
| System operasi   | win 10

**Comment by eddieridwan** [comment]
Berantakan seperti apa? Harap lampirkan contoh.

**Comment by balongbesuk** [comment]
mengulang issue #796 masalah ini muncul ketika desa memiliki banyak pengguna

**Comment by MUHAMMADRANGSEL** [comment]
Berantakan yg kami maksud  misalkan nomor surat SDH sampai 354 karena kurang kejelian nomor berikutnya menjadi 255 seperti gambar dibawah ini : 
![screenshot_2018-05-09-18-39-58-523_com android chrome](https://user-images.githubusercontent.com/25834335/39810734-b1cb84c6-53b8-11e8-812b-de56d85e8ef3.png)

**Comment by MUHAMMADRANGSEL** [comment]
Sehingga  yg diinginkan ketika Nomor registrasi surat itu sama maka TDK bisa cetak atau export surat

**Comment by MUHAMMADRANGSEL** [comment]
Memang didesa itu bukan hanya operator desa yg buat surat tetapi semua staf sesuai dengan bidang masing2

**Comment by MUHAMMADRANGSEL** [comment]
untuk memunculkan nomor secara otomatis di form Nomor Surat
<tr>
          <th>Nomor Surat</th>
          <td> <input name="nomor" type="text" class="inputbox required" size="6" **value="<?php echo $surat_terakhir['no_surat']+1;?>**" onchange="nomor_surat(this.value);"/>			
            <span>Terakhir: <?php echo $surat_terakhir['no_surat'];?> (tgl: <?php echo $surat_terakhir['tanggal']?>)</span></td>
</tr>

**Comment by suphm** [comment]
saya salin [solusi ini](https://github.com/OpenSID/OpenSID/issues/796#issuecomment-365963095) 

>paling tidak spy masalah tersebut bisa diatasi, perlu menjadi titik tekan di nomor register surat dan tahun pembuatan surat :
>1. Kalau nomor dan tahun pembuatan sama dan dengan jenis surat berbeda surat tidak bisa diexport dengan ada muncul peringatan
>2. kalau nomor sama sedang tahun pembuatan surat berbeda maka surat bisa diexport
mengapa demikian karena per 1 januari register surat dimulai dari 001

Nah, perlu ditambah lagi dengan judul surat gak om? jadi ```1 nomer untuk 1 judul surat per 1 tahun```

**Comment by eddieridwan** [comment]
Apakah issue ini duplikat dari #796?

Sebelum menerapkan issue ini, kita perlu menguraikan secara rinci spesifikasi penomoran surat. 

Perlu teman2 simak dulu aturan penomoran yang ada saat ini dulu. Dan kemudian baru mengusulkan perubahan secara rinci. Apapun yg diusulkan harus bisa berlaku bagi SEMUA PENGGUNA. Yaitu disepakati oleh POKJA. 

Aturan saat ini:

1. Di form surat, yang ditampilkan adalah nomor surat terakhir yang telah digunakan sebelumnya, sebagai informasi saja. Pembuat surat bebas memasukkan nomor surat sendiri. Cara ini dulu diterapkan karena tidak ada kesepakatan di antara pengguna cara penomoran surat yang baku.
2. Nomor surat terakhir yang ditampilkan adalah berdasarkan tanggal, dan bukan berdasarkan bilangan. Jadi kalau kemarin dibuat surat dengan nomor 234, dan hari ini dibuat surat dengan nomor 101, yang akan ditampilkan adalah nomor 101.
3. Nomor surat terakhir yang ditampilkan bisa di-setting: apakah per jenis surat atau untuk semua jenis surat (https://github.com/OpenSID/OpenSID/wiki/Panduan-Konfigurasi-Aplikasi). Cara ini dulu diterapkan karena tidak ada kesepakatan di antara pengguna cara penomoran surat yang baku.
4. Pada waktu mencetak surat, aturan penyimpanan surat di _Arsip Layanan_ dijelaskan di https://github.com/OpenSID/OpenSID/wiki/Arsip-Layanan:

> Daftar Arsip Layanan berisi satu baris untuk setiap surat dengan atribut [jenis-surat][NIK-pemohon][tanggal-cetak][nomor-surat] yang unik. Jika suatu surat dicetak berkali-kali (misalnya untuk memperbaiki isian data) maka jumlah baris surat di Arsip Layanan tidak akan bertambah. Tetapi, apabila surat yang sama dicetak-ulang pada tanggal berbeda (misalnya esok harinya), maka pencetakan ini akan menghasilkan baris baru di daftar Arsip Layanan.

**Comment by eddieridwan** [comment]
Dalam mengusulkan perubahan cara penanganan nomor surat dan pengelolaan _Arsip Layanan_, teman2 sebaiknya menyediakan uraian:

1. Dasar peraturan administrasi penomoran/pengarsipan surat yang baku, yang ingin diterapkan. Lampirkan peraturannya, dengan contoh buku register surat dan laporan lainnya.
2. Apakah aturan yang ingin diterapkan akan diberlakukan untuk SEMUA pengguna OpenSID, atau disediakan sebagai pilihan yang dapat ditentukan di setting aplikasi. Pertimbangannya adalah, apakah semua daerah menerapkan aturan yang sama; apakah aturan desa dan kelurahan (karena juga ada kelurahan yang menggunakan) sama?
3. Apakah nomor surat dipaksa unik? Yaitu, pengguna tidak dapat menggunakan nomor surat yang telah digunakan sebelumnya.
4. Kalau nomor surat dipaksa unik, bagaimana caranya untuk mengubah surat yang perlu dicetak ulang untuk memperbaiki isian data?
5. Kalau nomor surat yang diisi pada waktu membuat surat tidak harus unik, apa aturan penyimpanan di _Arsip Layanan_ (lihat aturan saat ini di komentar sebelumnya)?

**Comment by eddieridwan** [comment]
@MUHAMMADRANGSEL @balongbesuk @suphm @pandigresik @fathurvbf : silakan tanggapi, dan uraikan aturan yang ingin diterapkan sesuai komentar di atas.

**Comment by suphm** [comment]
oke menyimak dulu

**Comment by suphm** [comment]
[Aturan penulisan surat ini](http://ainamulyana.blogspot.com/2014/12/aturan-penulisan-nomor-surat-dinas.html) berlaku gak di desa?

**Comment by balongbesuk** [comment]
saya pernah bertanya di Facebook untuk penulisan nomor surat, dan tiap daerah memiliki ciri masing masing,
https://www.facebook.com/groups/OpenSID/permalink/943283475836634/

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
