### ISSUE TITLE
Custom Nama Desa

### ISSUE THREAD

**Issue by suanggie** [OpenSID/OpenSID#998]
Terimak kasih Untuk semua team yang membantu dalam SID, perkenalkan saya dri Papua Kab. Merauke
persoalannya adalah tidak semua daerah memakai nama "Desa" seperti halnya di Papua namanya "Kampung" di Bali namanya "Nagari" atau yang lain, untuk itu agar di sediakan pilihan utnuk Hal tersebut

Terimakasih

**Comment by eddieridwan** [comment]
@suanggie : issue bukan tempat bertanya penggunaan OpenSID (seperti diingatkan oleh template pada waktu membuat issue baru). Mohon bertanya di https://www.facebook.com/groups/OpenSID/.

Dan jangan lupa pula rajin2 membaca panduan: https://github.com/OpenSID/OpenSID/wiki. Misalnya, di https://github.com/OpenSID/OpenSID/wiki/Panduan-Konfigurasi-Aplikasi dijelaskan cara mengganti sebutan desa.
