### ISSUE TITLE
Ubah penulisan Jenis Pekerjaan PETANI/PERKEBUNAN

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/OpenSID#999]
Jenis pekerjaan di Aplikasi PETANI/PERKEBUNAN Sedangkan dikartu keluarga dan di KTP terteta PETANI/PEKEBUN

### Seperti apa yang diharapkan?
SUPAYA SESUAI DENGAN YG ADA DI DINAS DUKCAPIL PADA KARTU KELUARGA DAN KTP

### Apa yang terjadi?

ADANYA PERBEDAAN
### Informasi tambahan 

| Tanya            | Jawab
| ---------------- | ---
| Versi OpenSID    | 2.12
| Versi PHP        | 
| System operasi   |

**Comment by metalab25** [comment]
berdasarkan disdukcapik apa miq ?

**Comment by MUHAMMADRANGSEL** [comment]
Ya

Pada tanggal Sel, 8 Mei 2018 23.10, Happy <notifications@github.com>
menulis:

**Comment by andriawan** [comment]
Ya saya akan kerjakan issue ini @eddieridwan

**Comment by eddieridwan** [comment]
@andriawan :  Lihat cara menambahkan perubahan database di https://github.com/OpenSID/OpenSID/wiki/Menambah-Migrasi-Database

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR #1681
